### ISSUE TITLE
Error while binary response serialization [ONetworkProtocolBinary] java.lang.ClassCastException

### ISSUE THREAD

**Issue by adriancoca** [orientechnologies/orientdb#10004]
## Steps to reproduce  

Runing an Orient Sql in OrientDb Studio return result without problem, but from code the same Sql seems to crash the connection.
Query is send from nodejs using orientjs library.

Only message found in orient console is ->  Error while binary response serialization [ONetworkProtocolBinary]
java.lang.ClassCastException

I can also provide the sql if it helps.

**Comment by tglman** [comment]
Hi,

Yes the query will be useful usually this kind of problems are because some types cannot be serialized correctly on the network, the http protocol in this cases it just do a "toString" of the value, making it looks like it works, also an example of the result set you get from http would be useful.

Regards

**Comment by adriancoca** [comment]
{
  "result": [
    {
      "commandUuid": "bf1af52c-e177-4a83-99ec-37dbf1ae113b",
      "packagesUuid": [
        "38d761eb-62d0-4577-96fc-df1242c55956"
      ],
      "clientName": "etc S.R.L.",
      "commandNumber": "92239",
      "locality": "ORADEA",
      "county": "BIHOR",
      "headquarterName": null,
      "commandId": "223510",
      "clientCui": "RO199999917",
      "numberOfPackages": 1,
      "driver": {
        "delegateId": 324234,
        "carId": 0,
        "carLicensePlate": null,
        "driverName": "AGENT CURIER",
        "driverCINumber": null,
        "driverCISeries": null
      },
      "rank": 1,
      "headquarterId": 3414,
      "deliverDate": "2023-07-20 00:00:00",
      "numberOfPackagesScanned": 0
    }
  ],
  "dbStats": {
    "@type": "d",
    "@version": 0,
    "@fieldTypes": "loadedRecords=l,averageLoadRecordTimeMs=l,minLoadRecordTimeMs=l,maxLoadRecordTimeMs=l,prefetchedRidbagsCount=l,ridbagPrefetchTimeMs=l,minRidbagPrefetchTimeMs=l,maxRidbagPrefetchTimeMs=l",
    "loadedRecords": 15,
    "averageLoadRecordTimeMs": 0,
    "minLoadRecordTimeMs": 0,
    "maxLoadRecordTimeMs": 0,
    "prefetchedRidbagsCount": 0,
    "ridbagPrefetchTimeMs": 0,
    "minRidbagPrefetchTimeMs": 0,
    "maxRidbagPrefetchTimeMs": 0
  },
  "executionPlan": {
    "@type": "d",
    "@version": 0,
    "@fieldTypes": "cost=l,steps=z",
    "type": "QueryExecutionPlan",
    "javaType": "com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan",
    "cost": 0,
    "prettyPrint": "+ FETCH FROM SUBQUERY \n  + FETCH FROM SUBQUERY \n    + FETCH FROM INDEX RouteDelivery.uuid\n      uuid = \"128781b3-5943-4b11-86a1-1b692dc504c5\"\n    + EXTRACT VALUE FROM INDEX ENTRY\n      filtering clusters [383,384,413,391,389,390,387,388,385,314,386,45,139,138,140,8,277,276,133,275,132,135,134,137,136,396,397,394,177,395,392,393,30,31,154,156,155,69,265,249,263,248,264,247,101,89,19,20,194,225,32,18,109,108,111,110,113,13,112,114,212,211,210,196,195,107,106,2,9,209,43,201,44,42,333,331,332,77,29,46,47,163,131,162,303,80,305,304,311,78,312,79,164,313,50,48,52,51,270,183,184,182,81,237,127,126,125,124,21,64,326,63,62,165,262,217,289,288,287,173,260,259,261,87,86,88,250,193,49,251,252,253,1,72,71,70,123,122,291,121,292,120,293,119,189,343,342,382,75,76,221,74,302,141,142,269,268,266,258,306,267,278,144,414,285,283,284,192,191,190,204,203,202,57,186,187,188,41,103,102,104,216,215,214,176,175,73,174,218,376,377,220,378,219,379,272,422,273,421,423,380,418,381,417,420,271,419,416,415,96,254,366,94,95,286,408,412,411,410,409,232,231,256,296,257,295,255,181,230,301,300,299,334,329,328,297,327,61,40,39,38,401,400,399,407,406,159,405,158,404,403,160,233,402,321,97,375,319,320,372,371,374,373,239,357,368,240,356,367,355,370,354,369,353,352,351,3,238,325,324,398,323,359,358,153,152,151,150,149,148,213,147,438,146,439,145,290,54,281,434,55,280,435,279,436,437,28,27,431,26,432,433,37,34,100,36,98,35,99,168,167,11,10,12,17,143,166,93,6,129,53,130,128,341,340,205,339,338,337,336,335,14,16,15,161,185,68,344,345,5,346,67,347,66,348,349,56,310,180,178,179,157,208,207,206,350,241,294,172,22,171,198,199,318,200,7,4,274,23,24,0,105,440,443,444,441,442,246,445,115,116,170,117,427,426,429,428,227,425,228,424,226,309,308,307,229,330,282,60,58,59,244,243,245,65,365,85,322,363,364,361,362,33,360,236,235,234,242,317,197,298,315,316,90,430,91,92,169,82,118,84,83,222,224,223,25]\n    + FILTER ITEMS BY CLASS \n      routedelivery\n    + CALCULATE PROJECTIONS\n      in(\"ON_ROUTEDELIVERY\") AS cmd, @rid AS routeNode\n  + UNWIND cmd\n+ LET (for each record)\n  $offerNode = cmd.out(\"PART_OF\")[0].out(\"IS_A\")[0]\n+ LET (for each record)\n  $packageNode = cmd.in(\"PART_OF\")[key = \"COMANDA INTERNA\"].out(\"HAS_PACKAGE\")\n+ CALCULATE PROJECTIONS\n  routeNode.delegate AS driver, cmd.rank.asInteger() AS rank, cmd.uuid AS commandUuid, cmd.data.commandNumber AS commandNumber, cmd.data.commandId AS commandId, $offerNode.client.address.headquarterName AS headquarterName, $offerNode.client.name AS clientName, $offerNode.client.fiscalCode AS clientCui, $offerNode.client.address.headquarterId AS headquarterId, $offerNode.client.address.city AS locality, $offerNode.client.address.conunty AS county, $packageNode.uuid AS packagesUuid, $packageNode[status = \"FINISHED\"].size() AS numberOfPackagesScanned, $packageNode.size() AS numberOfPackages, $offerNode.deliverDate AS deliverDate, cmd.rank.asInteger() AS _$$$ORDER_BY_ALIAS$$$_0\n+ ORDER BY _$$$ORDER_BY_ALIAS$$$_0 ASC\n+ CALCULATE PROJECTIONS\n  commandUuid, packagesUuid, clientName, commandNumber, locality, county, headquarterName, commandId, clientCui, numberOfPackages, driver, rank, headquarterId, deliverDate, numberOfPackagesScanned",
    "steps": [
      {
        "@type": "d",
        "@version": 0,
        "@fieldTypes": "cost=l",
        "name": "SubQueryStep",
        "type": "SubQueryStep",
        "targetNode": "SubQueryStep",
        "javaType": "com.orientechnologies.orient.core.sql.executor.SubQueryStep",
        "cost": -1,
        "subSteps": [],
        "description": "+ FETCH FROM SUBQUERY \n   + FETCH FROM SUBQUERY \n      + FETCH FROM INDEX RouteDelivery.uuid\n        uuid = \"128781b3-5943-4b11-86a1-1b692dc504c5\"\n      + EXTRACT VALUE FROM INDEX ENTRY\n        filtering clusters [383,384,413,391,389,390,387,388,385,314,386,45,139,138,140,8,277,276,133,275,132,135,134,137,136,396,397,394,177,395,392,393,30,31,154,156,155,69,265,249,263,248,264,247,101,89,19,20,194,225,32,18,109,108,111,110,113,13,112,114,212,211,210,196,195,107,106,2,9,209,43,201,44,42,333,331,332,77,29,46,47,163,131,162,303,80,305,304,311,78,312,79,164,313,50,48,52,51,270,183,184,182,81,237,127,126,125,124,21,64,326,63,62,165,262,217,289,288,287,173,260,259,261,87,86,88,250,193,49,251,252,253,1,72,71,70,123,122,291,121,292,120,293,119,189,343,342,382,75,76,221,74,302,141,142,269,268,266,258,306,267,278,144,414,285,283,284,192,191,190,204,203,202,57,186,187,188,41,103,102,104,216,215,214,176,175,73,174,218,376,377,220,378,219,379,272,422,273,421,423,380,418,381,417,420,271,419,416,415,96,254,366,94,95,286,408,412,411,410,409,232,231,256,296,257,295,255,181,230,301,300,299,334,329,328,297,327,61,40,39,38,401,400,399,407,406,159,405,158,404,403,160,233,402,321,97,375,319,320,372,371,374,373,239,357,368,240,356,367,355,370,354,369,353,352,351,3,238,325,324,398,323,359,358,153,152,151,150,149,148,213,147,438,146,439,145,290,54,281,434,55,280,435,279,436,437,28,27,431,26,432,433,37,34,100,36,98,35,99,168,167,11,10,12,17,143,166,93,6,129,53,130,128,341,340,205,339,338,337,336,335,14,16,15,161,185,68,344,345,5,346,67,347,66,348,349,56,310,180,178,179,157,208,207,206,350,241,294,172,22,171,198,199,318,200,7,4,274,23,24,0,105,440,443,444,441,442,246,445,115,116,170,117,427,426,429,428,227,425,228,424,226,309,308,307,229,330,282,60,58,59,244,243,245,65,365,85,322,363,364,361,362,33,360,236,235,234,242,317,197,298,315,316,90,430,91,92,169,82,118,84,83,222,224,223,25]\n      + FILTER ITEMS BY CLASS \n        routedelivery\n      + CALCULATE PROJECTIONS\n        in(\"ON_ROUTEDELIVERY\") AS cmd, @rid AS routeNode\n   + UNWIND cmd"
      },
      {
        "@type": "d",
        "@version": 0,
        "@fieldTypes": "cost=l",
        "name": "LetExpressionStep",
        "type": "LetExpressionStep",
        "targetNode": "LetExpressionStep",
        "javaType": "com.orientechnologies.orient.core.sql.executor.LetExpressionStep",
        "cost": -1,
        "subSteps": [],
        "description": "+ LET (for each record)\n  $offerNode = cmd.out(\"PART_OF\")[0].out(\"IS_A\")[0]"
      },
      {
        "@type": "d",
        "@version": 0,
        "@fieldTypes": "cost=l",
        "name": "LetExpressionStep",
        "type": "LetExpressionStep",
        "targetNode": "LetExpressionStep",
        "javaType": "com.orientechnologies.orient.core.sql.executor.LetExpressionStep",
        "cost": -1,
        "subSteps": [],
        "description": "+ LET (for each record)\n  $packageNode = cmd.in(\"PART_OF\")[key = \"COMANDA INTERNA\"].out(\"HAS_PACKAGE\")"
      },
      {
        "@type": "d",
        "@version": 0,
        "@fieldTypes": "cost=l",
        "name": "ProjectionCalculationStep",
        "type": "ProjectionCalculationStep",
        "targetNode": "ProjectionCalculationStep",
        "javaType": "com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep",
        "cost": 0,
        "subSteps": [],
        "description": "+ CALCULATE PROJECTIONS\n  routeNode.delegate AS driver, cmd.rank.asInteger() AS rank, cmd.uuid AS commandUuid, cmd.data.commandNumber AS commandNumber, cmd.data.commandId AS commandId, $offerNode.client.address.headquarterName AS headquarterName, $offerNode.client.name AS clientName, $offerNode.client.fiscalCode AS clientCui, $offerNode.client.address.headquarterId AS headquarterId, $offerNode.client.address.city AS locality, $offerNode.client.address.conunty AS county, $packageNode.uuid AS packagesUuid, $packageNode[status = \"FINISHED\"].size() AS numberOfPackagesScanned, $packageNode.size() AS numberOfPackages, $offerNode.deliverDate AS deliverDate, cmd.rank.asInteger() AS _$$$ORDER_BY_ALIAS$$$_0"
      },
      {
        "@type": "d",
        "@version": 0,
        "@fieldTypes": "cost=l",
        "name": "OrderByStep",
        "type": "OrderByStep",
        "targetNode": "OrderByStep",
        "javaType": "com.orientechnologies.orient.core.sql.executor.OrderByStep",
        "cost": 0,
        "subSteps": [],
        "description": "+ ORDER BY _$$$ORDER_BY_ALIAS$$$_0 ASC"
      },
      {
        "@type": "d",
        "@version": 0,
        "@fieldTypes": "cost=l",
        "name": "ProjectionCalculationStep",
        "type": "ProjectionCalculationStep",
        "targetNode": "ProjectionCalculationStep",
        "javaType": "com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep",
        "cost": 0,
        "subSteps": [],
        "description": "+ CALCULATE PROJECTIONS\n  commandUuid, packagesUuid, clientName, commandNumber, locality, county, headquarterName, commandId, clientCui, numberOfPackages, driver, rank, headquarterId, deliverDate, numberOfPackagesScanned"
      }
    ]
  },
  "elapsedMs": 1
}

**Comment by adriancoca** [comment]
Hello, @tglman do you find something ? Should I run a repair on database or it doesn't help ?

**Comment by tglman** [comment]
Hi,

I went trough the query and the result, but I cannot really pin point which type is causing problem do you have a bit more detail in the exception ? like the types that it fail to cast to would be really useful

Regard

**Comment by adriancoca** [comment]
@tglman I tried to "prune" the sql , i don't have other exception message.

```
 select * from
        ( select  from (
                select in("ON_ROUTEDELIVERY") as cmd ,@rid as routeNode
                from routedelivery where uuid="128781b3-5943-4b11-86a1-1b692dc504c5"
            ) unwind cmd
        )
     LET $someNode =cmd.in("PART_OF")
```

this is the part where it fails
`LET $someNode =cmd.in("PART_OF")`

(this is ok LET $someNode =cmd   maybe a link is in broken state )
but if I'm not using LET it works ->

```
select cmd.in("PART_OF") as someNode from
        ( select  from (
                select in("ON_ROUTEDELIVERY") as cmd ,@rid as routeNode
                from routedelivery where uuid="128781b3-5943-4b11-86a1-1b692dc504c5"
            ) unwind cmd
        )
```

**Comment by tglman** [comment]
Hi,

I could reproduce this, should be fixed in the last develop, will be released in 3.2.22

Bye

**Comment by tglman** [comment]
The  release 3.2.22 is out please check if is also fixed at your side

**Comment by adriancoca** [comment]
It seems to be ok, thanks a lot.
