### ISSUE TITLE
Wrong last()  result after Database repair

### ISSUE THREAD

**Issue by adriancoca** [orientechnologies/orientdb#10026]
## Expected behavior  
If i have node 0 and make links in time with node 1  , after that  with node 2 and node 3, the function return last(out("son")) = node 3

## Actual behavior  
After running REPAIR DATABASE with the parameters from documentation, the REPAIR seems to relink in other order.

I don't know if it is because of performance reasons the initial order is not maintained or is a normal behavior and i shouldn't use last in this case.

last returns NODE 3 (ignore @rid from picture, it is the same picture for example)

![beforerepair](https://github.com/orientechnologies/orientdb/assets/7643185/c22678d3-d76d-4602-bed8-ac2a4eed7d9c)

After repair last return NODE 1
![afterrepair](https://github.com/orientechnologies/orientdb/assets/7643185/93affa63-73b8-4751-bd0a-54db7ef7aa0e)

**Comment by tglman** [comment]
Hi,

By default OrientDB do not guarantee the order of relationships, there is a workaround for this and use the type `LINKLIST` for relationship underlying collection, and this will try to keep the order in the way the relationships were added, but when repairing the database all the  underlying collections for relationships are rebuild from scratch following the order of the record in the database, so this will make the original order be lost.

The best way to have ordered relationships is to keep some metadata that establish the order in the edge.

Regards
