### ISSUE TITLE
OServer.listDatabases() needs to long for huge databases.

### ISSUE THREAD

**Issue by Goldritter** [orientechnologies/orientdb#10024]
### OS: <Windows 11>  

I have only one huge database (more than 20 GB with 4 Vertex classes and over 1000 edges) and if I want to use OrientStudio I cannot connect to the database. 
The reason for this is that listDatabase is called, then this request is not answered and a new request is executed. So OrientDB Studio sends a new request every second and still waits for the answers of the sent requests. 

When OServer.listDatabases() was called directly, it took 122537.7191 msecs to return the name of the only database. This is clearly too long. 

All other operations are fast enough. Except for starting the server, which also takes several minutes.

## Expected behavior  
The call to OServer.listDatabases() should actually take less than a second. 

## Actual behavior  
The call to OServer.listDatabases() currently takes about 122537.7191 msec.

## Steps to reproduce  
I think it has somethig to do with the size of my Database. If the Database is much smaller the call needs much less than 1 second.

**Comment by tglman** [comment]
Hi,

one additional information to try to reproduce the case, how many files are in the database folder ?

**Comment by Goldritter** [comment]
There are 89028 Files in the Folder. 
The biggest three are ca. 1.4 GB, ca. 1.3 GB and 1GB which are Index-Files. The biggest files are all Index-Files.

**Comment by tglman** [comment]
Hi,

Just release 3.2.23 with an improvement in database listing, let me know if this fix your problem.

Regards

**Comment by Goldritter** [comment]
Thank you, it works fine now. 
Actually it takes in my slow i5 about 118 milliseconds. :) 

Thank you for your efforts and I think this eissue can be closed now.

With best regards
Marcus
