### ISSUE TITLE
 How to use the enterprise version now that it has been released?

### ISSUE THREAD

**Issue by dodogeller** [orientechnologies/orientdb#10049]
### OS: Linux Ubunto 22.04

When entering the orientdb website, the documentation tells me just this

https://orientdb.org/docs/3.2.x/ee/Enterprise-Edition.html

And when I click to start the enterprise version, it sends me an email, I try to get in touch and they don't respond. I need the version to back up with the database in production and not stop it to do the same. Does anyone have a step-by-step guide on how to adjust? Thanks in advance

**Comment by adriancoca** [comment]
Hello, you can download agent jar from here https://repo1.maven.org/maven2/com/orientechnologies/agent/3.2.25/
(https://central.sonatype.com/artifact/com.orientechnologies/agent)

**Comment by dodogeller** [comment]
> Hello, you can download agent jar from here https://repo1.maven.org/maven2/com/orientechnologies/agent/3.2.25/ (https://central.sonatype.com/artifact/com.orientechnologies/agent)

Thank you very much my friend, it worked perfectly. Thank you very much
