### ISSUE TITLE
Remove com.orientechnologies.orient.core.storage.cache.OCachePointer#getBufferDuplicate 

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#10068]
The new JDK 21 API allows it to work with all ByteBuffer operations using offsets. Using internal positions inside the byte buffer is unnecessary.  Remove the creation of new ByteBuffer instances and use ByteBuffer API that does not rely on internal position inside byte buffer.

**Comment by tglman** [comment]
Hi, 

That's good, what is the minimum java version this API is supported ?

**Comment by andrii0lomakin** [comment]
Java 17 should work

**Comment by andrii0lomakin** [comment]
Fixed.
