### ISSUE TITLE
Move form concurrent hash map based to array based cache

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#10079]
Files are removed quite rarely, so it is okay to keep a list of files with some gaps in this list for the removed files.
Also, files are either completely truncated or grown.
So, instead of a cache based on concurrent hash maps, it proposed having CAS-based array lists (that we already implemented).

Each file will have a separate list of page pointers that could be null or contain a pointer to the page itself.
In such a scheme, a cache with a database size of 1TB will require 1GB of heap space to manage, which is negligible overhead. 

But as a result, we will have an almost instant fetch of the page from the cache upon request and do not need to create a key-object to fetch the page.

**Comment by tglman** [comment]
Hi,
yeah that's cool, the only thing that may not be ideal is that you have to connect the RAM usage to the size of the database on the disc, but I guess the implementation of this can be hidden behind a interface and we can keep also a hashmap version around that user may switch to it when they do not want to connect their database sizes to the ram usage.

**Comment by andrii0lomakin** [comment]
Sure, we will keep old and new implementations. Users will be able to change cache implementation if there are problems.
