### ISSUE TITLE
Update Query Not Reflecting Changes in Linked Records

### ISSUE THREAD

**Issue by Aniket-Lonare** [orientechnologies/orientdb#10077]
## Expected behavior  
The expected behavior is that the data should be updated successfully when executing the linked query.

## Actual behavior  
Despite receiving a response indicating that the record has been updated, the actual data remains unchanged.

### Steps to reproduce

1. We have a class named "States" with three properties: ID, Name, and Hidden. Hidden is a Boolean property.

2. We also have another class named "Objects" with four properties: ID, Name, Hidden, and State. The "State" property is linked to the "States" class, and the "ID" property is indexed with the following configuration:
   ```
   Index for "ID" property:
   CREATE INDEX Objects.ID ON Objects (ID) UNIQUE_HASH_INDEX ENGINE HASH_INDEX
   ```

3. Attempting to update the information of a "States" class object using the following query:
   ```
   Update Objects set Hidden = true, States.Hidden = true return after States:{*} as StateInfo where ID = "1234"
   ```

4. After executing the query, the hidden property from the "States" class appears to be updated in the result. However, when fetching the record using the ID of the "States" class, it is observed that the update is not reflected.

The above query was working in the 3.2.24 version.
Please let me know if you need any more information to look into this issue.

Thank you.

**Comment by andrii0lomakin** [comment]
Hi @Aniket-Lonare 
Could you provide the code that you use to execute the query and test results?

**Comment by Aniket-Lonare** [comment]
Hi @laa
We have executed the query on orientDB studio. We have attached the sample database for reference, this db has only two classes Objects and States.

If we execute the following query, 
`Update Objects set Hidden = true, State.Hidden = true return after *, State:{*} as StateInfo where ID = "1234"`
Then, we get the response as - where StateInfo shows the data has been updated
![image](https://github.com/orientechnologies/orientdb/assets/53806566/1e342ec5-f167-4702-ba7a-6918444f75e1)

Whereas when we get the information of the state record using the following query, we get the old data.
`select from States where ID = "3571" or select from #26:0`
![image](https://github.com/orientechnologies/orientdb/assets/53806566/a753d7be-0307-472d-8200-6e30d5d2981f)

Below is the explanation of the update query - 
explain Update Objects set Hidden = true, State.Hidden = true return after *, State:{*} as StateInfo where ID = "1234"
+ FETCH FROM SUBQUERY 
  + FETCH FROM CLASS Objects
    + FETCH FROM CLUSTER 22 ASC
    + FETCH FROM CLUSTER 23 ASC
    + FETCH FROM CLUSTER 24 ASC
    + FETCH FROM CLUSTER 25 ASC
    + FETCH NEW RECORDS FROM CURRENT TRANSACTION SCOPE (if any)
  + FILTER ITEMS WHERE 
    ID = "1234"
+ CONVERT TO UPDATABLE ITEM
+ UPDATE SET
  Hidden = true
  State.Hidden = true
+ SAVE RECORD
+ CONVERT TO REGULAR RESULT ITEM
+ CALCULATE PROJECTIONS
  *, State :{*} AS StateInfo

[Sample.gz](https://github.com/orientechnologies/orientdb/files/14126567/Sample.gz)

Please let me know, if you need more information.

**Comment by andrii0lomakin** [comment]
That is quite useful, thank you. That is all at the moment.

**Comment by tglman** [comment]
Hi,

I fixed the regression, will be release in 3.2.28

Regards

**Comment by tglman** [comment]
Hi, 

3.2.28 has been released with the fix, closing, feel free to reopen the issue if you experience the problem.

Regards

**Comment by Aniket-Lonare** [comment]
Okay, Thank you
