### ISSUE TITLE
Facing test issues for oreintdb:3.2.27 on PPC64LE architecture.

### ISSUE THREAD

**Issue by vinodk99** [orientechnologies/orientdb#10074]
### OS: NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
 

## Expected behavior  
Test cases should pass.
## Actual behavior  
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ETLJobTest.shouldLoadWithHandler:85 » IllegalArgument Class 'null' not found in database
[INFO] 
[ERROR] Tests run: 81, Failures: 0, Errors: 1, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OrientDB 3.2.27:
[INFO] 
[INFO] OrientDB ........................................... SUCCESS [  8.740 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [ 25.028 s]
[INFO] OrientDB Core ...................................... SUCCESS [20:24 min]
[INFO] OrientDB Client .................................... SUCCESS [  9.048 s]
[INFO] OrientDB Object .................................... SUCCESS [ 53.731 s]
[INFO] OrientDB Tools ..................................... SUCCESS [ 32.697 s]
[INFO] OrientDB Server .................................... SUCCESS [27:02 min]
[INFO] OrientDB Security Plugin ........................... SUCCESS [  0.490 s]
[INFO] OrientDB GraphDB ................................... SUCCESS [05:48 min]
[INFO] OrientDB Tests ..................................... SUCCESS [07:01 min]
[INFO] OrientDB Distributed Server ........................ SUCCESS [06:47 min]
[INFO] OrientDB Lucene full text index .................... SUCCESS [10:35 min]
[INFO] OrientDB JDBC Driver ............................... SUCCESS [01:32 min]
[INFO] OrientDB ETL ....................................... FAILURE [02:08 min]
[INFO] OrientDB Community Distribution .................... SKIPPED
[INFO] OrientDB Community Distribution Tinker Pop 2 ....... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:23 h
[INFO] Finished at: 2024-01-29T06:41:31Z
[INFO] ------------------------------------------------------------------------

**Comment by andrii0lomakin** [comment]
Hi.
Could you provide the output of the test? Without even having a stack trace of exception it is tough to fix such an issue.

**Comment by vinodk99** [comment]
Hi @laa ,Attaching test failures entire log:
[OrientDB_Test_failure.txt](https://github.com/orientechnologies/orientdb/files/14082779/OrientDB_Test_failure.txt)

**Comment by andrii0lomakin** [comment]
I see. I suppose I understood the reason. 

I will fix it in a couple of days. That is a concurrency issue that can be reproduced only on nonx86 architecture.  I do appreciate that you reported it.

**Comment by vinodk99** [comment]
> I see. I suppose I understood the reason.
> 
> I will fix it in a couple of days. That is a concurrency issue that can be reproduced only on nonx86 architecture. I do appreciate that you reported it.

Thanks @laa

**Comment by andrii0lomakin** [comment]
@vinodk99 I fixed the issue. Please try again, but be aware of the 3.2.x version is branched off.
