### ISSUE TITLE
Add hasEdge and getEdgeNames methods into new graph API

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#10078]
Currently, implementation of such methods requires knowledge of the internals of OrientDB and so should be provided by API.

**Comment by andrii0lomakin** [comment]
Also, OVertex should filter out edge properties from the returned list of properties.

**Comment by tglman** [comment]
Hi,

Yes we do need this, maybe also other APIs for similar use cases

**Comment by andrii0lomakin** [comment]
Hi @tglman 
I will use this issue to gather all the methods I need during my current activities.
Later, we can add them and then use them instead of the hacks that I am using right now.

**Comment by andrii0lomakin** [comment]
#removeEdge method also should be added. 
With the new API, removing the edge using the OVertex interface is impossible.

**Comment by andrii0lomakin** [comment]
We also need to be sure that OVertexDocument is loaded by default instead of ODocument so we ensure that users do not mangle with edge-related properties. The same about OEdgeDocuemnt

**Comment by andrii0lomakin** [comment]
It looks like it is already done; cool, then we just need to restrict operations on edge-related properties.

**Comment by tglman** [comment]
Hi,

Yep, it is, we just need to make sure we fix internal use case before restrict use from users.

**Comment by andrii0lomakin** [comment]
@tglman I did not understand what you meant. What internal use case do you mean?

**Comment by andrii0lomakin** [comment]
In a couple of weeks, I would like to add:

1. Changes in the TX commit protocol that will allow the added validation to enforce different types of n..n relations without the usage of indexes at all.
2. More unit tests will be added.
