### ISSUE TITLE
Provide API to convert all lighweight edges into regular edges

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#10099]
Because lightweight edges have been prohibited since 4.0, we need to create a tool for users (likely SQL command, which will temporarily exist until the 5.0 version) to convert all lightweight edges into regular edges.

After implementing the given issue, we need to announce the deprivation of lightweight edges and describe converting them into larger ones.

**Comment by tglman** [comment]
Hi,

As today we do have repair graph, this could be used also for this use case.

Regards
