### ISSUE TITLE
Add short cut links to speed up traversal between vertexes in case of regular edges

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#10104]
During the addition of links to the edge records during edge creation, also add links directly between vertices. This will allow us to:

1. Restrict the cardinality of edges, which is very important.
2. Allow to execute navigation between vertices with the same speed as we do right now for lightweight edges.

**Comment by andrii0lomakin** [comment]
Fixed.

**Comment by tglman** [comment]
Hi,

I think I reverted this

**Comment by andrii0lomakin** [comment]
Sure no problem
