### ISSUE TITLE
Add createEdge method to the schema

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#10103]
Add a created edge method to the schema that will create two things:

1. Creates property with the appropriate name in the schema and with the type of LINK_BAG.
2. Creates Edge class if such one does not exist.
3. A unique index is created if edge cardinality is restricted to 0..n.
4. If edge cardinality is restricted to 1..n, then no null requirement is added.

Related SQL commands also should be added.

This issue is related to issue #10100

Related documentation is also should be updated.

**Comment by andrii0lomakin** [comment]
It would also be good to add OType.EDGE will work as an alias for OType.LINKBAG, except that changing of such type will be allowed only inside edge modification methods. Also, all parameters above in such cases can be reflected in the schema but will be immutable. However, in the case of metadata management, we need to think through corner cases carefully.

**Comment by andrii0lomakin** [comment]
@tglman what do you think about the following:
Instead of relying on a naming pattern, add two property types: OUT_EDGE and IN_EDGE (those essentially will be synonymous of OTypy.LINKBAG).
Extend OClass to the OVertexClass and OEdgeClass.

Add `createEdge(OVertecClass to, ODirection direction)` method and related methods into the OVerteClass.
When we manipulate edges on documents, we work only with Edge properties but read old types of edges, too.

To ensure restrictions on the number of connections, implement the following change in ridbag:
Read `getMin` and `getMax` from the property during transaction commit and pass it to ridbag for validation. 
In such a case, we will not need to create a unique index to ensure such constraints. It will be more lightweight than the usage of the index.

**Comment by tglman** [comment]
Hi, 
OType is a bit everywhere, based on it is the record disk serialization and network record serialization as well, adding types is quite complex, not because of the complexity itself but because of the impact on the external things, happy to add restrictions, and limit use/hide `out_` `in_` collections, but I would prefer to add this constraint somewhere else

**Comment by andrii0lomakin** [comment]
@tglman OK. All of this can be done without the introduction of a new type by relying on the naming pattern of properties. It's not a big deal.
