### ISSUE TITLE
Resole all reported compiler warnings

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#10116]
Resolve all existing compiler warnings and fail build in case of the presence of new ones.

**Comment by tglman** [comment]
Hi,

The majority of warnings as today from a quick check with a maven build, are about use of deprecated methods/classes the most of them are actually OrientDB method used internally for backward compatibility, or in test cases, this set of "deprecated uses" will be every time present as far as there is a deprecated method, so to make a build fail in case of warnings is need to exclude this specific warnings from checks, without whitelisting each of them.

Regards
