### ISSUE TITLE
Add configuration property to define limit of clusters per class

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#10117]
Modern servers have hundreds of cores.
We create a number of clusters equal to the number of cores.

The creation of 128 clusters per class looks like absolute overkill.
It is proposed to set an upper limit, e.g., 16, on the number of clusters per class.
Otherwise even empty databases will consume gigabytes of data.

**Comment by tglman** [comment]
Hi,

I think is wise to detach this concept of one cluster per core, I think is ok to still have multiple clusters, but 4 or 8 by default is a good fix number and we can remove the automatic association with the CPU cores.

**Comment by andrii0lomakin** [comment]
Hi @tglman I agree. 
Especially taking into account virtual threads, there will be no connection between cores and IO scalability numbers.

**Comment by andrii0lomakin** [comment]
Fixed
