### ISSUE TITLE
Convert LHPEPS cluster implementation to hash index engine. [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1011]
This is [Issue 1011](http://code.google.com/p/orient/issues/detail?id=1011) moved from a Google Code project.
Added by 2012-08-09T05:13:21.000Z by [lomakin....@gmail.com](http://code.google.com/u/110615750300902819680/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

### Original description

    During implementation of auto sharding we have created new cluster that is based on LHPEPS but this implementation is at the same time is fully functional index engine. On my tests I have about only 16-18% slowdown on insertion if compare it with OClusterLocal implementation which means that this index engine has high performance. So I propose to do following:
    
    1. Create one more index engine that will not support range queries but will have high performance and low memory consumption. Which actually will not require huge amount of time.
    2. Migrate ORIDSet from tree to hash index implementation (it should be done in different issue).

**Comment by laa** [comment]
Not relevant any more
