### ISSUE TITLE
Throw meaningful exception in case users use aliases with dots  [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1024]
This is [Issue 1024](http://code.google.com/p/orient/issues/detail?id=1024) moved from a Google Code project.
Added by 2012-08-19T18:07:06.000Z by [lomakin....@gmail.com](http://code.google.com/u/110615750300902819680/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low, Release

### Original description

    OrientDB release? 
    1.2.0 - SNAPSHOT 
    
    If users execute queries like &quot;SELECT Name.FisrtName as Name.FirstName, Name.LastName as Name.LastName,  City.Name as City.Name FROM Person&quot; 
    
    and try to read data using code 
    
    String firstName = result.field(&quot;Name.FisrtName&quot;);
    String lastName = result.field(&quot;Name.LastName&quot;);
    
    returned results are null but no error or explanation is thrown.

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot. Dots are not allowed in aliases, now a validation exception is thrown.
