### ISSUE TITLE
Cannot drop property from class

### ISSUE THREAD

**Issue by Afler** [orientechnologies/orientdb#10282]
## Expected behavior  
DROP PROPERTY command worked 

## Actual behavior  
Trying to drop a property from a class:
![image](https://github.com/user-attachments/assets/ac3f6f29-d831-4084-9b0e-8c6bd332222a)
and got the exception:
```
Error parsing query: DROP PROPERTY kamaz:Resource.testProperty ^ Encountered " <DROP> "DROP "" at line 1, column 1. Was
expecting one of: <SELECT> ... <TRAVERSE> ... <MATCH> ... <INSERT> ... <RETURN> ... <FIND> ... <REBUILD> ... <OPTIMIZE> ...
<GRANT> ... <REVOKE> ... <BEGIN> ... <COMMIT> ... <ROLLBACK> ... <IF> ... <SLEEP> ... <CONSOLE> ... <MOVE> ... <SELECT> ... 
<SELECT> ... <TRAVERSE> ... <MATCH> ... <FIND> ... <INSERT> ... <MOVE> ... DB name="kamaz-db-tp3" Error Code="1"
```
Same behavior with the Java API:
![image](https://github.com/user-attachments/assets/88c7e31a-43d9-4666-a88d-7baeceddcaaf)

## Steps to reproduce  
Run docker orientdb:3.2.32-tp3
Add a property to class 
Try to drop property with DROP command

**Comment by tglman** [comment]
Hi,

I think the issue there is the `:` try to escape the name of the class:

```
drop property `kamaz:Resource`.testProperty
```

**Comment by Afler** [comment]
@tglman Yeah, found it out right now, ty
