### ISSUE TITLE
RESTORE DATABASE from INCREMENTAL_BACKUP does not accept directory name.

### ISSUE THREAD

**Issue by Nulhiedbriks** [orientechnologies/orientdb#10319]
## Expected behavior  
Database restored from incremental backup files

## Actual behavior  
I did the incremental backup from the enterprise edition. I got 3 files from the backup in a directory (`/backup/mydb`)
`mydb_2024-09-25-14-12-56_0_full.ibu3` `mydb_2024-09-25-14-19-05_1.ibu3` `mydb_2024-09-25-14-20-04_2.ibu3`

From the doc, i delete `mydb` then recreate empty `mydb` via `console.sh` and execute the command `RESTORE DATABASE /path/to/backup/mydb` 
Here what i got : 

```
orientdb {db=mydb}> restore database /path/to/backup/mydb
Restoring database 'database /path/to/backup/mydb' from full backup...
Database restored in 0,00 seconds
Error: java.io.FileNotFoundException: '/path/to/backup/mydb'  (is directory)
```
In source code there is no mention of incremental restore. I suppose there is a specific configuration for that case but there is no documentation.

Thanks in advance.

**Comment by tglman** [comment]
Hi,

here are the docs: https://orientdb.dev/docs/3.2.x/admin/Incremental-Backup-And-Restore.html#incremental-restore-via-the-console

Bye

**Comment by Nulhiedbriks** [comment]
Thansk a lot ! 

I was looking on the wrong doc page : https://orientdb.dev/docs/3.2.x/console/Console-Command-Restore.html
