### ISSUE TITLE
Null @version attribute

### ISSUE THREAD

**Issue by johny65** [orientechnologies/orientdb#10332]
## Expected behavior  
`select @version from V` to return the vertex version.

## Actual behavior  
It returns null.

## Steps to reproduce  

Just create some vertices and then execute `select @version from V` and the result will be null for each vertex. In previous versions of OrientDB it worked correctly. With `select from V` you can see that the `@version` attribute does have a value.

**Comment by tglman** [comment]
Hi,

This should be fixed in 3.2.36, let me know if you can verify it on your side.

**Comment by johny65** [comment]
Thanks for the fix, it works correctly now.
