### ISSUE TITLE
Problems with prepared query parameters in nested query [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1069]
This is [Issue 1069](http://code.google.com/p/orient/issues/detail?id=1069) moved from a Google Code project.
Added by 2012-09-24T07:43:38.000Z by [MilenDya...@gmail.com](http://code.google.com/u/114975002325789911081/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Release

### Original description

    It seams query parameters (both positional and named) don't work in nested queries. There is no error - the query simply does not return any results. 
    A simple test case reproducing the problem is available here: https://gist.github.com/3246359#file_query_param_test.java 
    
    There are 3 tests :
    
    - one using positional parameter
    - one using named parameter
    - one manually replacing the '?' withe the appropriate value 
    
    and only the last one returns records.

**Comment by n0lf** [comment]
When this is solved, will it be possible to use named and/or positional parameters or  when you assign a context variable to the result of a sub-query?

**Comment by luigidellaquila** [comment]
the new parser fixes all these cases. 
It was committed in 2.1 snapshot with some test cases.
Closing this, please re-open if you find uncovered corner cases

**Comment by dmarcelino** [comment]
Glad to hear that, thanks @luigidellaquila.
