### ISSUE TITLE
Command to check existence of a cluster [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1104]
This is [Issue 1104](http://code.google.com/p/orient/issues/detail?id=1104) moved from a Google Code project.
Added by 2012-10-11T14:36:36.000Z by [polisini...@gmail.com](http://code.google.com/u/111543071756386647716/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v2.1.0
### Original description

```
Is needed a command to check the existence of a specified cluster.

See forum thread https://groups.google.com/forum/?fromgroups=#!topic/orient-database/IS2RznRyZDI
```

**Comment by wouterv** [comment]
+1
We are creating clusters on the fly and I need to check if a clustername already exists

**Comment by luigidellaquila** [comment]
In v 3.0 there is a `SELECT FROM metadata:storage` that also returns cluster information. It can be used to check cluster existence

Closing
