### ISSUE TITLE
New SQL statement: DELETE GRAPH [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1108]
This is [Issue 1108](http://code.google.com/p/orient/issues/detail?id=1108) moved from a Google Code project.
Added by 2012-10-12T14:43:06.000Z by [sfinx.so...@gmail.com](http://code.google.com/u/110336626902504915186/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v1.4.0
### Original description

```
Implement the DELETE GRAPH statement needed for deleting the sub-graph starting from some vertex/edge. The two variants proposed:

Simple: DELETE GRAPH from (traverse V.out, E.in from V)

This variant simply loads the traverse graph RID's to memory and executes DELETE VERTEX/EDGE on given list according to the element type. The RID's are small data types, so even the big graph can be deleted using default memory limits.

Complex: DELETE GRAPH from #X:Y

More sophisticated variant, that does traversing by itself starting from node #X:Y and deletes objects in parallel. May be this variant can break the graph to small parts and call the first variant on it.
```

**Comment by stevehu** [comment]
@lvca This is the feature I am waiting for. Is there any way we can cascade delete a sub graph using traverse or select now? Thanks.

**Comment by grossvater** [comment]
Any news on this?

**Comment by luigidellaquila** [comment]
Hi @grossvater 

did you already try the following:

```
DELETE VERTEX FROM (TRAVERSE both() FROM #x:y)
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
As described above, this is already possible via SQL

Closing, thanks

Luigi
