### ISSUE TITLE
TTL for Documents with Hook for automatic Clean Up Code  [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1110]
Hi  
A requested feature in the Orient Group was a  TTL / Tombstone Feature in OrientDB. This would be a great functionality and should at least have following possibilities: 

```
Define TTL while Document Creation 
Set TTL after Document Creation 
Set TTL to &quot;Tombstone&quot; Value (ex. -1) for automatic 
```

Have a hook - which could be used to access this feature - so different use cases are possible: 

```
Archiving Doc - to another database (out of hot &quot;Data&quot;)
Search for linked &quot;Docs&quot; to this Record - to not break Integrity 
Flag Doc for Cleaning 
Track Doc &quot;Deletion&quot; for compress the database while online 
```

Hope this is enough information on this 
Michael

**Comment by dmarcelino** [comment]
:+1: for this

Another way to implement it is to only delete the document when reading it. So:

1. find the document
2. verify if expired
  * if expired delete it
3. return query result

This way there are no tasks running continuously. Though we could probably have a task running every few hours to delete expired tokens with the purpose of saving space.

**Comment by gottlike** [comment]
:+1: .. As I need TTL quite often and would love to use OrientDB as my "general purpose" DB.

**Comment by Solido** [comment]
As a heavy user of NoSQL this feature is not at 'low priority' for me ;)

Simple example working with User Session. Having TTL in OrientDB make it quite a pleasure, just create a Session document with User as a linked field when login succeed. When a request arrive check for the session asking directly to OrientDB. Yeak Quick WIN !

Without OrientDB :/

1 -> put a non distributed session cache in your application -> no more stateless app
2 -> install a distributed cache with TTL : Redis, HBase, EHCache, whatever Go apps, etc. Duplicate repositories and administration
3 -> 'easily' implements it in OrientDB 

The implementation need to provide events listeners so we can follow what's going on.

I love OrientDB and use it in production right now but this feature is really missing. 
Thank you for you attention.
