### ISSUE TITLE
DELETE FROM command wipes index records [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1130]
This is [Issue 1130](http://code.google.com/p/orient/issues/detail?id=1130) moved from a Google Code project.
Added by 2012-10-22T12:11:48.000Z by [pawel.ba...@gmail.com](http://code.google.com/u/107589873079481649177/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Release

### Original description

    OrientDB release:
    orientdb-graphed-1.3.0-SNAPSHOT-r7048
    
    System / Platform details:
    Ubuntu 12.04 64bit
    java version &quot;1.7.0_07&quot;
    Java(TM) SE Runtime Environment (build 1.7.0_07-b10)
    Java HotSpot(TM) 64-Bit Server VM (build 23.3-b01, mixed mode)
    
    What steps will reproduce the problem:
    
    1) prepare OrientDB without changing any default configuration:
    
    mkdir ~/servers/orient
    cd ~/servers/orient
    svn checkout http://orient.googlecode.com/svn/trunk/ orient-read-only
    
    # use your revision ID which you can see after svn checkout
    ORIENT_REV=7048
    
    cd orient-read-only
    
    # regular version
    ant clean
    ant install
    
    # graphed version
    ant clean
    ant installg
    
    cd ../releases/
    
    mv orientdb-1.3.0-SNAPSHOT orientdb-1.3.0-SNAPSHOT-r$ORIENT_REV
    mv orientdb-graphed-1.3.0-SNAPSHOT orientdb-graphed-1.3.0-SNAPSHOT-r$ORIENT_REV
    
    cd orientdb-graphed-1.3.0-SNAPSHOT-r$ORIENT_REV
    
    chmod +x bin/*.sh
    
    touch log/orient-server.log
    
    cd ./bin/
    
    # start the server
    ./server.sh
    
    # open new console and go the same &quot;bin&quot; directory
    
    # start the console
    ./console.sh
    
    
    2) using the running console perform these operations:
    
    # create database
    # replace sample path with your path 
    create database local:/some/local/path/databases/bugs/development admin admin local
    
    # change database's type
    ALTER DATABASE TYPE graph
    
    # disconnect from the database
    disconnect
    
    # establish connection to the database again
    # replace sample path with your path 
    connect local:/some/local/path/databases/bugs/development admin admin
    
    3) copy the content of the attached file &quot;wiped_indexes_issue_queries.sql&quot; and paste it into the console
    
    
    What is the expected output / result:
    
    After each run of the &quot;info&quot; command we should see more and more index records being created inside different indexes
    
    What do you see instead:
    
    After each run of the &quot;info&quot; command (except last one) we see that the previously created index records are being removed, except those which are being created after the closest &quot;delete from&quot; command (in relation to our &quot;info&quot; command) by using &quot;insert&quot; commands
    
    After the last &quot;info&quot; command we see that there are no index records at all.
    
    For a full log of console commands and responses , please see the attached file &quot;wiped_indexes_issue_console_output.txt&quot;

**Comment by luigidellaquila** [comment]
Old issue, this kind of problems was fixed long time ago

Closing

Thanks

Luigi
