### ISSUE TITLE
SQL select command - lack of syntax validation [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1134]
This is [Issue 1134](http://code.google.com/p/orient/issues/detail?id=1134) moved from a Google Code project.
Added by 2012-10-23T14:20:06.000Z by [pawel.ba...@gmail.com](http://code.google.com/u/107589873079481649177/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Release

### Original description

    OrientDB release:
    ********************************************************
    orientdb-graphed-1.3.0-SNAPSHOT-r7058
    
    <b>What steps will reproduce the problem?</b>
    ********************************************************
    1.open console
    2.execute queries presented below:
    
    select some crazy text ;
    select * some crazy text ;
    
    What is the expected output:
    ********************************************************
    
    raised syntax errors
    
    What do you see instead?
    ********************************************************
    no errors being raised at all
    
    orientdb> select some crazy text ;  
    
    ---+---------
      #| RID     |
    ---+---------
      0|    #-2:1
    ---+---------
    
    1 item(s) found. Query executed in 0.0 sec(s).
    
    orientdb> select * some crazy text again ;
    
    ---+---------
      #| RID     |
    ---+---------
      0|    #-2:1
    ---+---------
    
    1 item(s) found. Query executed in 0.0 sec(s).
    
    Additional description:
    ********************************************************
    In both cases above there is completely no syntax validation which leads to confusion when you make this sort of typo (there should be &quot;from&quot; not &quot;form&quot;):
    
    orientdb> select * form orole;                                                     
    
    ---+---------
      #| RID     |
    ---+---------
      0|    #-2:1
    ---+---------
    
    1 item(s) found. Query executed in 0.0 sec(s).

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot
