### ISSUE TITLE
support tabs as whitespace in sql files [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1138]
This is [Issue 1138](http://code.google.com/p/orient/issues/detail?id=1138) moved from a Google Code project.
Added by 2012-10-28T15:07:56.000Z by [mat.tay...@gmail.com](http://code.google.com/u/112638151891566594624/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Release

### Original description

    <b>OrientDB release? (If you're using a SNAPSHOT please attach also the build</b>
    number found in &quot;build.number&quot; file):
    1.2
    
    <b>What steps will reproduce the problem?</b>
    1. create a sql file with some insert statements (using spaces between words)
    2. run file as an argument to console.sh - should work
    3. replace or extend spaces with tabs, and run file - will fail.
    
    Using tabs in complex files makes for significantly enahnced  readiablility

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot (develop branch)
