### ISSUE TITLE
Async notification of metadata changes [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1155]
This is [Issue 1155](http://code.google.com/p/orient/issues/detail?id=1155) moved from a Google Code project.
Added by 2012-11-02T18:25:38.000Z by [chrisloo...@gmail.com](http://code.google.com/u/102166781604868791983/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v2.1.0
### Original description

```
OrientDB should provide a way to asynchronously notify the clients when the metadata changes on the server.

Option for an automatic metadata reload is also a nice to have.

This may improve consistency when one client changes the metadata while the database is used by many other clients. It also makes periodic reloads (which is needed because of the previously described case) unnecessary.
```

**Comment by tglman** [comment]
Hi,

This is implemented in 3.0, will be relased in 3.0 final.

Closing
