### ISSUE TITLE
Vertex Centric indices [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1156]
```
Vertex Centric indices can allow us so deal with Supernodes in a performant way.

See this page for background on vertex-centric indices: http://thinkaurelius.com/2012/10/25/a-solution-to-the-supernode-problem/

Opening issue to track the implementation of this.

Discussion here: https://groups.google.com/d/topic/orient-database/p-j07AV2dDA/discussion
```

**Comment by nidaca** [comment]
+1

**Comment by smolinari** [comment]
:+1: :+1: Next to the ES integration in Titan, this is also another important feature I like about Titan.

Scott

**Comment by baltag** [comment]
+1

**Comment by lvca** [comment]
This will be supported in new OrientDB SQL "MATCH" statement.

**Comment by smolinari** [comment]
That is great! 

How will the indices be created/ specified?

Scott

**Comment by smolinari** [comment]
I just ran into this. 

https://github.com/orientechnologies/orientdb/issues/1895

Scott

**Comment by Odomontois** [comment]
In the recent thing, I need hardly some fast narrowing edges by range of date attribute.
Please tell if indexed `BETWEEN` condition will be supported in `MATCH` statement.

**Comment by luigidellaquila** [comment]
Hi @Odomontois 

BETWEEN condition will be supported for indexed search, but in the meantime you can use two conditions with `<` and `>` and the index will be correctly used

Thanks

Luigi

**Comment by lvca** [comment]
Not relevant anymore. The new `MATCH` is able to understand if an index has been built on the edge class and can use it.
