### ISSUE TITLE
Object Database in operator error. [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1174]
This is [Issue 1174](http://code.google.com/p/orient/issues/detail?id=1174) moved from a Google Code project.
Added by 2012-11-18T23:06:30.000Z by [emanuele...@gmail.com](http://code.google.com/u/114517674467421514157/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Release

### Original description

    revision:trunk Object Database
    
    if try to execute a query like this:&quot;select  from Person where name  in :name&quot;
    giving in the parameter &quot;name&quot; an java.util.Collection the object database try to persist the list before execute the query occurring in an exception.
    
    I tried to fix the problem, in attachment an patch but i don't know where put an test for this use case, can you tell me where are the object database tests?
    
    
    tnks bye.

**Comment by tglman** [comment]
really old bug, i think this cannot happen anymore, closing.
