### ISSUE TITLE
Select from multiple clusters (and classes)

### ISSUE THREAD

**Issue by siriux** [orientechnologies/orientdb#1222]
On the discussion from : https://groups.google.com/forum/#!topic/orient-database/hUK970_o_YA

I discovered that it's not possible to perform a select from multiple clusters, something like:

select * from [cluster:foo, cluster:bar] ....

Find references and traverse already accept a list of clusters (although I couldn't make it work for traverse), so it seem useful to have it also for select.

Other thing to consider would be to allow a list of classes. That would be really useful too, allowing to return elements from multiple classes in a single query.

**Comment by lvca** [comment]
Supported as:
```sql
