### ISSUE TITLE
order by with multiple fields not documented properly (or not supported properly)

### ISSUE THREAD

**Issue by davidmoten** [orientechnologies/orientdb#1228]
Hi

I tried a query like this

    select from Entry order by a,b 

which according to syntax on https://github.com/nuvolabase/orientdb/wiki/SQL-Query should work but fails with a syntax exception.

The only way I could get this to work is by writing:

    select from Entry order by a asc,b asc

which is not described accurately enough by the documentation. Please update the docs or fix the parsing of the sql.

Thanks
Dave

**Comment by dxxr** [comment]
See also #2094

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot
