### ISSUE TITLE
config command doesn't work in console v1.3.0

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#1236]
Using the console, If I connect to the server, e.g. remote:localhost, the config command hangs.

If I connect to a specific database, e.g. remote:localhost/test1, the config command always generates: "Error: com.orientechnologies.orient.core.exception.ODatabaseException: Connection is closed", even though other commands (e.g. "info") work fine indicating the connection is good.

**Comment by lvca** [comment]
Old issue, tested with 2.2.0-rc1 and works.
