### ISSUE TITLE
Atomic test and set for fields

### ISSUE THREAD

**Issue by krisztiankocsis** [orientechnologies/orientdb#1242]
Hi!

I need something atomic 'test-and-set' support for primitive fields of classes.
A Java API and SQL like command is welcome too.

Something like that:
<RET> ODocument.testAndSet(String field, <RET> oldValue, <RET> newValue);
boolean ODocument.testAndSet(String field, Object oldValue, Object newValue);

Set 'field' to 'newValue' if 'currentValue' is 'oldValue' and return 'oldValue' or 'true' (in case of exchange), 'null' or 'false' otherwise.

If it is needed than I can help if somebody gives a starting point.

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
