### ISSUE TITLE
Console parser: example query not working

### ISSUE THREAD

**Issue by gabipetrovay** [orientechnologies/orientdb#1250]
Error: com.orientechnologies.orient.core.exception.OSerializationException: Found invalid ) character. Ensure it is opened and closed correctly.

```
insert into Profile(name,surname) VALUES ('Jay','Miner'),('Frank','Hermier),('Emily','Saut')
```

Workarounds? (other than sending two commands)

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot (develop branch)
