### ISSUE TITLE
Link to create class command wrong

### ISSUE THREAD

**Issue by FluxoDE** [orientechnologies/orientdb#1284]
The link to watch how to create a class is wrong, it leads to:

https://github.com/nuvolabase/orientdb/wiki/Console-Command-Create-Db

Root page: 
https://github.com/nuvolabase/orientdb/wiki/Console-Commands

**Comment by luigidellaquila** [comment]
Not relevant anymore, these docs pages no longer exist.

Closing

Thanks

Luigi
