### ISSUE TITLE
Multidimensional queries support for composite queries 

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1288]
Currently composite indexes support range queries in which all field values are equal and only last one is different.
The reason of such behavior is the way how we concatenate keys. key1 + key2 + key3.

But if  we will interleaving binary representations of keys http://en.wikipedia.org/wiki/Z-order_(curve) we can implement multidimensional queries support.
It is relatively easy to do because can be implemented on the base of SB-Tree by providing new serializers for composite keys and comparator + changes in SQL engine.

**Comment by kevbaker** [comment]
It would be good to see more advanced geo spatial queries like bounding box, radius etc... e.g. PostGIS/Geocouch features. 

This is likely a big undertaking, but good to put out to see what level of support there is.

**Comment by ympons** [comment]
Hi guys, Is there any progress on this?

**Comment by laa** [comment]
Hi, not yet. We are concentrated now multi core scalability.
