### ISSUE TITLE
Extend the fetchplan format parameter of the ODocument.toJSON()  

### ISSUE THREAD

**Issue by giastfader** [orientechnologies/orientdb#1308]
Hi, 
how discussed in the forum ( http://bit.ly/14dyUHG ), it would useful to have a new value to set in the fetchplan to avoid a field creation in the JSON string.
It would also be useful if this value can be propagated to all the linked documents  traversed by the toJSON() method

**Comment by lvca** [comment]
Not relevant anymore, in v3.0 fetchplan are deprecated in favor of new SELECT extended projections
