### ISSUE TITLE
Traversing map key 

### ISSUE THREAD

**Issue by idpspace** [orientechnologies/orientdb#1318]
Augmenting the traverse function so that it crosses relationships when an rid is the key of a map and not only when an rid is a value in a map.

https://groups.google.com/d/topic/orient-database/l3uyNr3kjSY/discussion

**Comment by luigidellaquila** [comment]
I'm closing this issue as it's old and not relevant anymore.
Class keys cannot be RIDs, they can only be strings

Thanks

Luigi
