### ISSUE TITLE
${ORIENTDB_HOME} shown instead of full path (regression)

### ISSUE THREAD

**Issue by F21** [orientechnologies/orientdb#1334]
Using the latest master 11d6b34dab (1.4.0-SNAPSHOT).

I first create a new database using the web interface (REST) called `newdb`.
I then created another new database using the binary protocol called `newdb2`.

I then ask the server to list all databases using the binary protocol.

```
array (size=6)
  'newdb' => string 'local:${ORIENTDB_HOME}/databases/newdb' (length=38)
  'newdb2' => string 'local:${ORIENTDB_HOME}/databases/test222' (length=40)
  'test' => string 'local:/usr/local/orientdb/databases/test' (length=40)
  'mydb' => string 'local:/usr/local/orientdb/databases/mydb' (length=40)
  'testtest' => string 'local:/usr/local/orientdb/databases/testtest' (length=44)
```

`test`, `mydb` and `testtest` were created many months ago with the 1.4.0-SNAPSHOT at the time. Today, I built the latest snapshot and copied those databases into the `databases` folder.

However, `newdb` and `newdb2` were created using the latest SNAPSHOT, so I suspect something has broken here.

I suspect that this the bug fixed in #1176 has regressed.

**Comment by lvca** [comment]
Fixed log time ago.
