### ISSUE TITLE
CREATE/ALTER CLUSTER command enhancement

### ISSUE THREAD

**Issue by dm-ordb** [orientechnologies/orientdb#1337]
Hi,

What about the following enhancement request:

new SIZE attribute for CREATE CLUSTER and ALTER CLUSTER commands:
- CREATE CLUSTER - to specify initial size (replace the defaults)
- ALTER CLUSTER - shrink/enlarge cluster's size

Thank you.

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
