### ISSUE TITLE
Database import via REST

### ISSUE THREAD

**Issue by veny** [orientechnologies/orientdb#1345]
I am trying to import an exported database via REST API but the documentation to this entry point is weak. can you provide a CURL sequence which demonstrates the import?

my attempt:
 > curl --user admin:admin --form filename=temp http://localhost:2480/import/mydb

with already ungziped exported JSON file or

 > curl --user admin:admin --form filename=temp.gz http://localhost:2480/import/mydb

with gziped exported  database.

what I see:

 >  HTTP/1.1 500 Internal Server Error
 > java.lang.NullPointerException

**Comment by luigidellaquila** [comment]
Docs updated.

https://github.com/orientechnologies/orientdb-docs/blob/master/OrientDB-REST.md

you just have to pass the JSON of the export as the call body.

Closing, thanks

Luigi
