### ISSUE TITLE
BUG console, can't insert string with a ; inside

### ISSUE THREAD

**Issue by fsicre** [orientechnologies/orientdb#1359]
using a document database with OrientDB 1.3.0

orientdb> create class a
Class created successfully. Total classes in database now: 11
orientdb> create property a.title string
Property created successfully with id=1

orientdb> insert into a set title="poil;pipo";
Inserted record 'a#12:0{title:null} v0' in 0,004000 sec(s).
!Unrecognized command: 'pipo"'

orientdb> insert into a set title="poil\;pipo";
Error: com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: OCommandSQL [text=insert into a set title="poil\]
Error: java.lang.ArrayIndexOutOfBoundsException: 6!Unrecognized command: 'pipo"'
orientdb> 

Do I have missed something ?

**Comment by AaronSchulz** [comment]
```insert into a set title="poil;pipo";``` works fine in SNAPSHOT-2.0.
