### ISSUE TITLE
Allow store immutable objects, like case classes

### ISSUE THREAD

**Issue by MercurieVV** [orientechnologies/orientdb#1361]
Scala language have "case classes", they often used as entity classes in scala language. Fields of that classes are immutable - final fields assigned in constructors.
Create empty constructor (for proxing) for such fields is not a problem.
- Problem 1 is that final fields marked as transien by OrientDB
- Problem 2 that case classes equals/getHash/toString methods do not use standart getters, like "getFieldName()", but like "fieldName()"
- Solution for problem 1 is: in OObjectEntitySerializer:386 remove " || Modifier.isFinal(fieldModifier) " condition
- Solution for problem 2 - modify OObjectMethodFilter or create custom. Custom can be something like:

``` scala
  class FieldMethodFilter extends OObjectMethodFilter {
    override def getFieldName(m: Method) = m.getName
    override def isSetterMethod(fieldName: String, m: Method) = !m.getParameterTypes.isEmpty
    override def isGetterMethod(fieldName: String, m: Method) = m.getParameterTypes.isEmpty
  }
```

Regards,
Victor

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
