### ISSUE TITLE
1.3.0 - aggregate functions do not work on embedded documents collection

### ISSUE THREAD

**Issue by dm-ordb** [orientechnologies/orientdb#1373]
Versions:
-1.3.0 release 
-OrientDB 1.4.0-SNAPSHOT 20130227-0214

Hi, could you try the following sequence:

create class collection

insert into collection set data = [{"size": 0}, {"size": 0}, {"size": 30}]

select
data.size, 
data.size(),
min(data.size),
max(data.size), 
sum(data.size), 
avg(data.size)  
  from collection

returned:
{
  "result": [{
      "@type": "d", "@rid": "#-2:0", "@version": 0,
"data": [0, 30],
"data2": 3,
"sum": 30,
"avg": 15
    }
  ]
}

expected:
{
  "result": [{
      "@type": "d", "@rid": "#-2:0", "@version": 0,
"data": [0, 0, 30],
"data2": 3,
"min": 0,
"max": 30
"sum": 30,
"avg": 10
    }
  ]
}

It seems the aggregation is made on the set of values (not the list) .

**Comment by luigidellaquila** [comment]
this is fixed in develop branch. 
I just added a test case.

**Comment by red-0ne** [comment]
Is this merged to 2.2 branch ?
