### ISSUE TITLE
Use RID for pagination is not efficient enough

### ISSUE THREAD

**Issue by djunhao** [orientechnologies/orientdb#1380]
Currently orientdb uses "@rid > ? limit ?" for pagination. but rid is not saved continuous that some records have been deleted, so we can not get the exactly paged data sources by using rid.
In web app, pagination is related with "page" param, such as "?page=x", so we need continuous id to get the paginated data sources by getPagedList(startIndex, maxResults) with "index > :startIndex limits :maxResults".

**Comment by martingg88** [comment]
any update on this?

**Comment by lvca** [comment]
You can use SKIP and LIMIT but to be more efficient you should use the RID. If you delete records in the middle of a pagination, with the RID you're safe.
