### ISSUE TITLE
Avoid rebuilding indexes if nothing has changed

### ISSUE THREAD

**Issue by Mark-A-W** [orientechnologies/orientdb#1390]
This issue has been raised by request in response to this thread:

https://groups.google.com/forum/#!topic/orient-database/d_axtYG4fGs

Currently (OrientDB Server v1.3.0 (build 16)), if the DB server job is ended by the OS (e.g. if terminating a Java program running in the Eclipse IDE with embedded OrientDB), the indexes are rebuilt the next time the server is started even though no records have been created, updated or deleted.

Luca says: "What we need is to reset the softly close flag only at first change."

That would be a good and helpful step. Maybe the next step would be to record when an individual index was dirty and only rebuild such indexes at server start. This should reduce the rebuilds to almost nil, only rebuilding those indexes where the update was in progress when the server was terminated.

**Comment by lvca** [comment]
Implemented with WAL CHECKPOINT in 2.0

**Comment by jwang628** [comment]
Sir,  Is this feature implemented in the community edition please?

**Comment by lvca** [comment]
Absolutely yes.

**Comment by jwang628** [comment]
Thanks a lot, Sir.  Would you shed some light how to code it please?  I am reading your javadoc:  http://orientdb.com/javadoc/latest/index.html?com/tinkerpop/blueprints/impls/orient/OrientGraphFactory.html  
and also asking people on the google group: https://groups.google.com/forum/#!topic/orient-database/d_axtYG4fGs

I wish to open the database in read-only mode so two or more applications can query the same database (in plocal mode not remote mode).  Is this possible please?  Do I have to use remote mode please?

Thanks  a lot in advance

**Comment by lvca** [comment]
Sorry this is not the right place. I'll comment the topic.
