### ISSUE TITLE
Extending SQL language to handle multiple add/put to collection/map at once

### ISSUE THREAD

**Issue by fredericBregier** [orientechnologies/orientdb#1396]
I suggest that the 2 following improvement could be made in SQL capability:

1) Capability to retrieve a list of values 
a) from a map as 
          mynumber[key1, key2, ...] => [ val1, val2, ...]
        As it seems possible to make something close from collection : 
          coll[rank1-rank2] => [val1, val2, ... ],
b) And therefore maybe having the same col[rank1, rank2, ...] => [val1, val2, ...]

One of them at least (map 1-a) seems done by Luca (8489e9df1f56a230b633c918ebc2b0a2d0d06b01).

2) Add the possibility to insert more than one by one element within a collection or a map since it is really costly to add 1 by 1
a) 
 i) update ... addAll collection = val1, val2, ...
 ii) update ... addAll collection = [ val1, val2, ... ] or { val1, val2, ... }
b) 
  i) update ... putAll map = 'key1', val1, 'key2', val2, ...
  ii) update ... putAll map = [ { 'key1', val1 }, { 'key2', val2 } , ... ]

I believe option a-ii and b-ii are more readable (parsable) and is more conforming to JSON list notation.
However it could also another option.

 Best regards,
Frederic

**Comment by luigidellaquila** [comment]
In v 3.0 we added new operators to manipulate collection fields, see http://orientdb.com/docs/3.0.x/sql/SQL-Syntax.html
