### ISSUE TITLE
Provide official OrientDB DataNucleus plugin

### ISSUE THREAD

**Issue by matthewadams** [orientechnologies/orientdb#1398]
DataNucleus, a popular and versatile persistence tool, employs a plugin architecture for underlying data stores.

This request is for OrientDB to supply an official DataNucleus plugin so that existing and new DataNucleus JDO & JPA codebases can use OrientDB as the underlying data store.

See forum discussion at https://groups.google.com/forum/?fromgroups=#!topic/orient-database/GMP2RRIYWqo

**Comment by chrisco484** [comment]
I was hoping you would have DataNucleus support too. Given we have large apps written to the JDO spec then to leverage the performance of OrientDB, if there was a OrientDB DataNucleus plugin, we would be able to switch from MySQL to OrientDB with very little, if any, code changes. That would be awesome!
