### ISSUE TITLE
DROP PROPERTY Problem

### ISSUE THREAD

**Issue by junnel1001** [orientechnologies/orientdb#1401]
Hello,

My Database is in partial-mode schema.

When I query accidentally like this

UPDATE class_name set following.rid = "Hello"

It created a property in my class now  "following.rid"(which is supposedly not and should return an error since that property name is not valid).

Now I want to drop this property because it is so annoying.

But as expected it returns an error since first of all following.rid is not a valid property.

This is my DROP property syntax:

DROP PROPERTY class_name.following.rid

returns:

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #39: Expected <class>.<property>. Use DROP PROPERTY <class>.<property>
Command: DROP PROPERTY class_name.following.rid

Can you please check this one? thanks.

**Comment by luigidellaquila** [comment]
This is an old issue, it is not valid anymore in current release. 

Anyway:
- the UPDATE does not create a property in the schema, it just inserts data. 
- that statement does not create a property called "following.rid", it creates a "rid" property in the "following"
- in v 2.2 you can use back-tick quoting to support dots in property names,  eg.
```
UPDATE class_name set `following.rid` = "Hello"
CREATE PROPERTY class_name.`following.rid`
DROP PROPERTY class_name.`following.rid`
```

Closing

Thanks

Luigi
