### ISSUE TITLE
Improve current storage durability

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1404]
Current storage uses MMAP as disk buffer which means that management of disk pages relies upon OS not DB itself as result  we can control cache behavior in limited manner and this also makes storage not safe in case of power failure to improve given situation following is proposed:
 1.  Replaced MMAP by our own 2Q cache which was designed for usage in DBs as disk cache + write cache which will contain records are going to be flushed sorted by position which will minimize random IO operations.
2. Implement paginated storage so we can treat pages as atomic units of data, as side effect we can remove storage global lock and replace 2 disk seeks IO by one disk seek IO for retrieval of record by id
3. Implement WAL inside of paginated storage.
4. Use direct memory for page cache to avoid GC overhead (Unsafe + JNA fallback).

**Comment by lvca** [comment]
@laa What's the status of this?

**Comment by laa** [comment]
we may close this issue
