### ISSUE TITLE
Problem with limit and compound indexes

### ISSUE THREAD

**Issue by federicoemartinez** [orientechnologies/orientdb#1409]
I'm using the 1.4.0-SNAPSHOT. In the console I have the following query:

select * from ExampleEdgeVersion where versioned_edge = #17:1305 and (end_date is null or end_date > 1364231981454) and begin_date <= 1364231981454

that query gives me one record. However if I add a "limit 1" it gives me nothing. Looking at the explain I get:

explain select * from ExampleEdgeVersion where versioned_edge = #17:1305 and (end_date is null or end_date > 1364231981454) and begin_date <= 1364231981454
Profiled command '{current:#18:4,compositeIndexUsed:1,indexReads:3,documentAnalyzedCompatibleClass:3,involvedIndexes:[1],elapsed:0.00203451,resultType:collection,resultSize:1}' in 0.003000 sec(s):
{
  "@type":"d","@version":0,"current":"#18:4","compositeIndexUsed":1,"indexReads":3,"documentAnalyzedCompatibleClass":3,"involvedIndexes":["EdgeVersion_versioned_edge_end_date_idx"],"elapsed":0.00203451,"resultType":"collection","resultSize":1,"@fieldTypes":"compositeIndexUsed=l,indexReads=l,documentAnalyzedCompatibleClass=l,elapsed=f"
}

explain select * from ExampleEdgeVersion where versioned_edge = #17:1305 and (end_date is null or end_date > 1364231981454) and begin_date <= 1364231981454 limit 1

Profiled command '{current:#18:2,compositeIndexUsed:1,indexReads:1,documentAnalyzedCompatibleClass:1,involvedIndexes:[1],elapsed:0.001042662,resultType:collection,resultSize:0}' in 0.003000 sec(s):
{
  "@type":"d","@version":0,"current":"#18:2","compositeIndexUsed":1,"indexReads":1,"documentAnalyzedCompatibleClass":1,"involvedIndexes":["EdgeVersion_versioned_edge_end_date_idx"],"elapsed":0.001042662,"resultType":"collection","resultSize":0,"@fieldTypes":"compositeIndexUsed=l,indexReads=l,documentAnalyzedCompatibleClass=l,elapsed=f"
}

EdgeVersion_versioned_edge_end_date_idx is an automatic index over the columns versioned_edge (type link) and end_date (type float).

**Comment by federicoemartinez** [comment]
Why has the bug label been removed? It does look like a bug to me

**Comment by lvca** [comment]
Sorry, dunno why I removed the label, by reading the description is a bug. Any chance to try it with a recent version of OrientDB? Let's say 2.1.2?

**Comment by federicoemartinez** [comment]
I haven't tried again, to be honest it was a deal-breaker by that time. We have decided to test orientdb again. I'll let you know if this works now.

**Comment by federicoemartinez** [comment]
it seems it's working now. I'm closing this issue.
Thank you!
