### ISSUE TITLE
Order by Random in our query

### ISSUE THREAD

**Issue by junnel1001** [orientechnologies/orientdb#1414]
ORDER BY should also include where user can get his data in random order rather than using ASC or DESC order.

It would be a nice feature for OrientDB for having this kind of feature.

Thanks

**Comment by rpietro** [comment]
agree that this would be a really nice feature for things like randomized experiments (random allocation) or random sampling to create a subset

**Comment by rpietro** [comment]
agree that this would be a nice feature. I currently have a very large healthcare database and to get a random sample i have to do it through a python query rather than directly from the query. this functionality would definitely solve my problem

**Comment by joaovissoci** [comment]
I was hoping this functionality would become a priority soon.  Really needed this for a problema with randomization.

**Comment by niels006** [comment]
Yup, would be tremendously helpful. Right now I am using an R script to do the same thing after the query.

**Comment by MarciaCanteri** [comment]
seems like a lot of people like this feature and so I will join the group. I use orientdb to store large healthcare databases and sampling in the query would certainly save me a few steps and a good amount of time

**Comment by JulioCanteri** [comment]
this would be extremely useful, thumbs up for this feature

**Comment by walterwhitebb** [comment]
Hi,
I'm just another person that decided to create a github account on Feb 2nd.

**Comment by lvca** [comment]
Hey, so many votes for this issue! Ok, let's move its priority. WDYT about this syntax:

    select ... order by random

**Comment by lucasxteixeira** [comment]
This would be very useful for problems that requires subsetting.
Order by random combined with traverse would be a killer feature for analysis of large databases.
Right now I'm doing this directly in Python.

**Comment by tglman** [comment]
i think is more correct a sintax like:
`order by field [ask| desc|random]`

**Comment by lvca** [comment]
Why use the field also for random?

**Comment by lucasxteixeira** [comment]
Field is not needed in my opinion.
The sintax below is perfect:
```
select ... order by random
```

**Comment by tglman** [comment]
`select .. order by random` conflict with the case you have a field called random.

**Comment by lucasxteixeira** [comment]
You are right.
The convention dictates that `asc` is not mandatory, so making it mandatory it is not good.

**Comment by luigidellaquila** [comment]
this can be easily achieved this way:

- define your random() function in js

```
SELECT *, random() as random from YourClass order by random 
```

**Comment by pkoppstein** [comment]
@luigidellaquila - Could you please elaborate on your your remark that:
> this can be easily achieved this way:
>define your random() function in js
> SELECT *, random() as random from YourClass order by random 

I have tried both:

    js r=function() { return Math.random();}; print( r() ); end

   select r() from ouser

and

    CREATE FUNCTION random return Math.random() LANGUAGE JAVASCRIPT

    select random() from ouser

but no luck.  Thank you.

**Comment by luigidellaquila** [comment]
Hi @lucasxteixeira 

did you try to create and test the funciton from Studio?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Sorry, my last comment was for @pkoppstein

**Comment by pkoppstein** [comment]
@luigidellaquila - I would like to know how to get this to work using console.sh.  I have an uptodate version (2.1.x branch):
```
$ git log -1
commit aabf99e1aab1c6e21495c18b079fc3748cbcb4a8
Author: lvca <l.garulli@gmail.com>
Date:   Tue Jan 12 20:22:07 2016 +0100

    Fixed compilation problems
$ git branch
* 2.1.x
  master
```
Thanks.

**Comment by lvca** [comment]
Already available by using math_rand() function and ordering by it. Example:

```
select a, b, math_rand() as c from X order by c
```
