### ISSUE TITLE
Remote protocol type validation for strict mode class

### ISSUE THREAD

**Issue by CJdeVos** [orientechnologies/orientdb#1429]
When specifying values for fields it seems as if default values are inserted when the passed value is not of the correct type. I would however expect either an OSerializationException or OValidationException.
Consider the following:
- LINK field: Put a numeric, string or array value. A NULL value is inserted. An exception was expected.
- LINKSET: Accepts [#8:0, #8:1, (OTHERCLASS@A:"B")] but throws errors in the console. 
- BOOLEAN: accepts ANY value but only puts it as true when the value is actually true. 
- EMBEDDED: accepts ANY value but puts NULL when it is not an embedded document.
For any of these (and more...) cases I would have expected errors to be thrown because it's being asked to use values which are not accepted by the strict class.

**Comment by tglman** [comment]
this isn't true anymore, since 2.0 the value are converted on set or an exception is thrown.

closing
