### ISSUE TITLE
User password handling with Dependency Injection

### ISSUE THREAD

**Issue by FHeNuS** [orientechnologies/orientdb#1471]
The current user password implementation creates a hash of the password and stores in the database. If we want to change the hash implementation, or don't use hash at all, this is not possible. Changing the password handling implementation to an injectable dependency, the consumer can choose witch one he wants to use, or create new ones. The IPasswordHandler should deal with the creation of a new user and also the opening process of a new connection).

**Comment by lvca** [comment]
SALT has been implemented, there is no big reason to support this.
