### ISSUE TITLE
large binary data using a stream

### ISSUE THREAD

**Issue by CJdeVos** [orientechnologies/orientdb#1475]
Please provide a new implementation to save/update/get a (binary or flat) record using a stream:
- the server should flush the data of the stream directly to the underlying storage engine.
- the server/client should not keep the data (in a byte array) in memory.

This new implementation should make it easier to read/write records of 2Gb without resorting the (ugly) 'hacks'.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
