### ISSUE TITLE
Allow base64 values in SQL queries

### ISSUE THREAD

**Issue by CJdeVos** [orientechnologies/orientdb#1477]
Trying to insert BINARY data (base64 encoded) through simple queries always give me null values. Examples are below:

1) insert into A (mybytes) values(_AA_)

2) insert into A content {mybytes: _AA_}

It is however possible to insert BINARY data (base64 encoded) through RECORD_CREATE and RECORD_UPDATE. Please allow base64 data in standard SQL queries.

**Comment by lvca** [comment]
Already implemented using `encode()` and `decode()` functions.
