### ISSUE TITLE
Completely disable Authorization: header

### ISSUE THREAD

**Issue by dvv** [orientechnologies/orientdb#1486]
Hi!

Is there an option to completely disable basic authorization header check? Am driving a thin (angular.js powered) site which uses Windows Integrated Authentication (which sets Authorization: NTLM .....) and subsequent calls to underlying orientdb have this header set which chokes orientdb auth.

TIA,
--Vladimir

**Comment by maggiolo00** [comment]
@dvv 
No there is no way to disable basic header.
