### ISSUE TITLE
Memoryleak during massive insert in Version 1.4.0

### ISSUE THREAD

**Issue by EricSchreiner** [orientechnologies/orientdb#1519]
java version SUN 1.7.0_21 (I've also tried other versions)
Windows 8 64 Bit
please see sample code and Heap analysis

![memoryleak](https://f.cloud.github.com/assets/4680347/643502/bf0d1fd6-d376-11e2-9cd1-e9f3e398f5d8.jpg)
![memoryleak1](https://f.cloud.github.com/assets/4680347/643506/c88bc238-d376-11e2-9b2f-ab30336bddbf.jpg)
![memoryleak2](https://f.cloud.github.com/assets/4680347/643507/d0267d62-d376-11e2-83e1-187d73d63605.jpg)

/*
- Created on 10.05.2013
  *
- Author:      Eric
- Copyright:   Contecon Software GmbH
- 
- History:     10.05.2013 created
- 
  */
  package de.contecon.picapport.db;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import org.junit.Test;

import com.orientechnologies.orient.core.config.OGlobalConfiguration;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.intent.OIntentMassiveInsert;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OClass.INDEX_TYPE;
import com.orientechnologies.orient.core.metadata.schema.OProperty;
import com.orientechnologies.orient.core.metadata.schema.OSchema;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.orientechnologies.orient.core.record.impl.ODocument;
import com.orientechnologies.orient.core.storage.OStorage.CLUSTER_TYPE;

public class TestOrientBulkInsert {

  private static int NUM_INSERTLOOPS=500000;

  @Test
  public void test() throws Exception {

```
// FIXME Eric_08.05.2013
// Mit der 1.3 von Orientdb gab es Memory Leak probleme beim inserten der Photos
// Mit den folgenden Parametern und dem Aufruf von
//                                      this.dbWrapper.setMassiveInserts();
// wurde es besser aber immer noch nicht 100%
// 
OGlobalConfiguration.CACHE_LEVEL1_ENABLED.setValue(false);  // Turn off cache
OGlobalConfiguration.CACHE_LEVEL1_SIZE.setValue(0);         // Turn off cache
OGlobalConfiguration.CACHE_LEVEL2_ENABLED.setValue(false);  // Turn off cache
OGlobalConfiguration.CACHE_LEVEL2_SIZE.setValue(0);         // Turn off cache

OGlobalConfiguration.INDEX_AUTO_LAZY_UPDATES.setValue(0);   // Turn off cache 
OGlobalConfiguration.INDEX_MANUAL_LAZY_UPDATES.setValue(0); // Turn off cache

OGlobalConfiguration.FILE_MMAP_STRATEGY.setValue(4);        // Kein Memory Filemapping  
OGlobalConfiguration.TX_USE_LOG.setValue(false);            // Keine Transaction logs benutzen   

Map defaultsMap=new HashMap<String, Object>();
defaultsMap.put("mvrbtree.lazyUpdates", 1);                    // Index wird immer direkt upgedated (Memory)
defaultsMap.put("index.auto.lazyUpdates", 1);                  // Index wird immer direkt upgedated (Memory)
defaultsMap.put("index.manual.lazyUpdates", 1);                // Index wird immer direkt upgedated (Memory)
defaultsMap.put("index.auto.rebuildAfterNotSoftClose", false); // Index wird nicht eigenständig aufgebaut (memory Probleme)

OGlobalConfiguration.setConfiguration(defaultsMap);    



new File("./playground").mkdirs();
File dbFile = new File("./playground/bulktest");

ODatabaseDocumentTx database = new ODatabaseDocumentTx("local:./playground/bulktest"); // reopen
database.create();

OSchema schema = database.getMetadata().getSchema();

OClass cBulk = schema.createClass("classBulk",database.addCluster("cluster_bulk", CLUSTER_TYPE.PHYSICAL));

// Declare some fields
for(int i=1; i<10; i++) {
    cBulk.createProperty("fieldString"+i, OType.STRING).setMandatory(true);
   }  
OProperty p2 = cBulk.createProperty("fieldBinary1", OType.BINARY).setMandatory(false);

// Declare some Indexes
cBulk.createIndex("indexField1", INDEX_TYPE.NOTUNIQUE,  "fieldString1");
cBulk.createIndex("indexField2", INDEX_TYPE.UNIQUE,     "fieldString2");
cBulk.createIndex("indexField3", INDEX_TYPE.DICTIONARY, "fieldString3");


database.declareIntent( new OIntentMassiveInsert() );


for(int i=0; i<NUM_INSERTLOOPS; i++) {
   database.save(createRandomDocument());

   if(i%1000==0) {
     System.out.println("Instert document:"+i);
     }

   // Slow duration of test down to 5 Minutes
   // Comment next line for faster execution
   // Thread.sleep(1000*60*5 / NUM_INSERTLOOPS);
   }

database.close();

do {
   // gives us time to analyse....
   System.gc();
   Thread.sleep(10000);
  } while (true);    
```

  }

  private ODocument createRandomDocument() {
    ODocument document = new ODocument("classBulk");

```
for(int i=1; i<10; i++) {
  document.field("fieldString"+i,  getRandomText(50));
  }  
document.field("fieldBinary1",   new byte[1024]);
return document;
```

  }

  static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"; 
  static Random rnd = new Random();
  static int counter=0;

  private String getRandomText(int len) {

```
  StringBuilder sb = new StringBuilder( len );
  for( int i = 0; i < len; i++ ) {
     sb.append( AB.charAt( rnd.nextInt(AB.length()) ) );
      }             
  String s=sb.toString() + " - "+ (++counter);
  // System.out.println(s);
  return s;
```

  }

}

**Comment by GrumpyPants** [comment]
I am also having this issue. Memory is just slowly climbing as I do bulk inserts. I would really like to see successful example of massive insert in orientdb.

**Comment by lvca** [comment]
This issue is pretty old and closed. Please open a new one with all the information about your use case: orientdb version, os, hw cfg, API used and also a snippet of code responsible of the massive insertion.

**Comment by GrumpyPants** [comment]
lvca, no problem. I've created the issue here https://github.com/orientechnologies/orientdb/issues/3381. I realize that this is most likely something I am doing wrong rather than a bug with orientdb so let me know if it would be better for me to ask on google group rather than create a new issue and I will close it. Thanks.
