### ISSUE TITLE
BUG: unclosed quote updates all records in cluster and deletes field

### ISSUE THREAD

**Issue by vemod** [orientechnologies/orientdb#1526]
unclosed quote in update statement does not throw syntax error but updates all records in cluster. Thats dangerous!. 

```orientdb> update cluster:proxies set ip="127.0.0.3 where @rid=#11:2;
Updated 3 record(s) in 0,003000 sec(s).```

and the field "ip" completely disappeared from the cluster.

full statements:
```
orientdb> select from cluster:proxies
----+-----+---------+----+------+------------+-------
#   |@RID |ip       |port|comment     |context
----+-----+---------+----+------+------------+-------
0   |#11:0|127.0.0.1|8080|test proxy  |null   
1   |#11:1|127.0.0.2|8080|test proxy 2|[3]    
2   |#11:2|127.0.0.2|8080|test proxy 3|[2]    
----+-----+---------+----+------+------------+-------
3 item(s) found. Query executed in 0.0020 sec(s).

orientdb> update cluster:proxies set ip="127.0.0.3 where @rid=#11:2;                 
Updated 3 record(s) in 0,003000 sec(s).

orientdb> select from cluster:proxies                               
----+-----+----+------+------------+-------
#   |@RID |port|comment     |context
----+-----+----+------+------------+-------
0   |#11:0|8080|test proxy  |null   
1   |#11:1|8080|test proxy 2|[3]    
2   |#11:2|8080|test proxy 3|[2]    
----+-----+----+------+------------+-------
3 item(s) found. Query executed in 0.0010 sec(s).

orientdb> update cluster:proxies set ip="127.0.0.3" where @rid=#11:2;
Updated 1 record(s) in 0,002000 sec(s).

orientdb> select from cluster:proxies                                
----+-----+----+------+------------+-------+---------
#   |@RID |port|comment     |context|ip       
----+-----+----+------+------------+-------+---------
0   |#11:0|8080|test proxy  |null   |null     
1   |#11:1|8080|test proxy 2|[3]    |null     
2   |#11:2|8080|test proxy 3|[2]    |127.0.0.3
----+-----+----+------+------------+-------+---------
3 item(s) found. Query executed in 0.0010 sec(s).
```
This simple mistake of forgetting to put closing quote resulted to data loss. 

Sure you can say if i mistype something it can result to data loss.. True. But such obvious case is easy to handle and help to avoid stupid mistakes.

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot (develop branch)
