### ISSUE TITLE
The query result ODocuments does not contains attributes with null value

### ISSUE THREAD

**Issue by laszlohordos** [orientechnologies/orientdb#1528]
I'm using OrientDB 1.4 studio for describing how to reproduce but It's the same if I use the Java API.

I created a new class called "sample" and then I created a new object.
  
```json
{
	"name":"test01",
	"nullValue":null
}
```        
I got this correct response.

```json
{
	"@type":"d",
	"@rid":"#9:0",
	"@version":0,
	"@class":"sample",
	"name":"test01",
	"nullValue":null
}  
```   
   
When I open the object from the studio or I use the getRecord method I receive all the attributes.
                      
```java 
ODocument result = database.getRecord(new ORecordId("#12:1"))
```     

If I execute the following query, then the "nullValue" attribute is missing from the response. 

```sql
select from sample where name = "test01"
```
    
Same with the Java call:

```java  
OSQLSynchQuery<ODocument> query =
                new OSQLSynchQuery<ODocument>("select from sample where name = ?");
List<ODocument> result = database.query(query, "test01");
```  

I didn't have the time to debug where does it come from but If I'll have time I'm going to comment the results later.

**Comment by luigidellaquila** [comment]
This issue was fixed long time ago

Closing, please reopen if you still experience similar problems

Thanks

Luigi
