### ISSUE TITLE
toJSON() supporting various representation formats

### ISSUE THREAD

**Issue by sohrabjk** [orientechnologies/orientdb#1529]
As of 1.4.0, the toJSON() function returns a flat line JSON representation of the document it is applied to. This is in contrast to version 1.3.0 where that function returned a formatted representation (\n after each [key/]value) of nested elements which was more readable when using, e.g, the console. The downside was that each [key/]value was not indented.

It would be handy to have toJSON(int level, boolean indented) which would add \n to each [key/]value at depths <= level and whether or not the representation should be indented (also at depths <= level). 

The current toJSON() would then amount to toJSON(-1, false).

In 1.4.x: 
{"@type":"d", "@rid":"#19:0", "@version":1, "@class":"Language", "locale": {"@type":"d", "@rid":"#19:0", "@version":1, "@class":"Language","isoLanguage":"fr","isoCountry":"ch"}, "name":"Fran\u00e7ais"}

vs. 

In 1.3.0:
{
    "@type":"d",
    "@rid":"#19:0",
    "@version":1,
    "@class":"Language",
    "locale": 
        {
            "@type":"d",
            "@rid":"#19:0",
            "@version":1,
            "@class":"Language",
            "isoLanguage":"fr",
            "isoCountry":"ch"
        },
    "name":"Fran\u00e7ais"
}

**Comment by lvca** [comment]
Not relevant anymore, closing it.
