### ISSUE TITLE
invoking OFunctions that are part of document graph from SQL query

### ISSUE THREAD

**Issue by twarogowski** [orientechnologies/orientdb#1540]
It would be great to have an ablity to write SQl query like this:

_SELECT Name, CalcFunction(15) FROM Calculator_

where CalcFunction is defined like this:

_CREATE PROPERTY Calculator.CalcFunction LINK OFunction_

In other words: to invoke functions attached (or referenced by) to documents that are part of query results. This should be possible with both idemponent and non-idempotent OFunctions. This will lead to great flexibility in extendeing data model with behavior, defined in functions. 

Linking OFunctions to data records is already possible, what we need is a way to invoke OFunctions from query or command.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
