### ISSUE TITLE
Not possible to open local database via console in OrientDB 1.4.1 on windows

### ISSUE THREAD

**Issue by nlumb** [orientechnologies/orientdb#1552]
OrientDB 1.4.1 on Windows with ORIENT_HOME "U:\orientdb"

Once running in the console, the starting directory can not be altered so when you start the console in a directory outside %ORIENT_HOME%\bin it is not possible to open a local database using local/..databases/<name> even though this database exists. When providing the full path:

U:\orientdb\databases\test
or
U:/orientdb/databases/test
or any other combination in the connect command it appears to be ignored.

Output in console is:

Disconnecting from the database [null]...OK
Connecting to database [local:U:/orientdb/databases/test] with user 'root'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '../databases/test' with mode=rw
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'test' because it does not exist in path: ../databases/test
orientdb>

Problem: 
- The console seems to always search the path" ../databases"
- The console offers the command pwd to see the current directory but does not allow the directory to be changed. 

This is a minor issue: A workaround is to start manually in %ORIENT_HOME%/bin in which case:

connect local:../databases/<name> <uid> <pwd>

works correctly

However, a cd function in the console would be usefull

**Comment by lvca** [comment]
This is very old and "local" is not supported anymore. Use rather plocal.

**Comment by nlumb** [comment]
Thanks Luca

**Comment by mindplay-dk** [comment]
The documentation for this is really poor. I can't at all figure out the format of `plocal`, what it's relative to, or why - using for example `plocal:/../databases/xyz`, my database ended up in a new `databases` folder in the root of my harddrive, and it doesn't seem to accept an absolute path like `plocal:/orientdb/databases/xyz`. How do you encode the drive letter on Windows? (The documentation on Loaders and ETL in general is incredibly sparse...)

**Comment by lvca** [comment]
Try this: `plocal:C/databases/xyz`

**Comment by amyth** [comment]
I am facing the same issue even when I try connecting to a `plocal` database. Following is the command I use
`orientdb> connect plocal:/tmp/db/konn admin admin
`
and following is the response in console.

```
Disconnecting from the database [null]...OK
Connecting to database [plocal:/tmp/db/konn] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/tmp/db/konn' with mode=rw

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'konn' because it does not exist in path: /tmp/db/konn
```

**Comment by lvca** [comment]
@amyth what release are you using?

**Comment by amyth** [comment]
I am at v2.1.17. Guess it was just a corrupt db (most probably happened while import data from graphml file). I dropped that database and created a new one and all work absolutely fine now.

**Comment by lvca** [comment]
Ok, thanks for the report.

**Comment by tomasaftalion** [comment]
experiencing same problem (v2.2, ubuntu 14.04).

Had setup db with:

`create database remote:localhost/<dbname> <user> <password> plocal graph`

I can't log in as:

`connect plocal:../databases/<dbname> <user> <password>`

but I can connect as:

`connect remote:localhost/<dbname> <user> <password>`

Note: I did change the installation paths in /bin/orientdb.sh when setting up.

**Comment by jackiszhp** [comment]
because you guys bind the binary protocol to some specific IP, rather than 0.0.0.0

**Comment by valenpo** [comment]
same story with plocal

```
orientdb> connect 'plocal:/Library/Application\ Support/MailArchiva/ROOT/database/archiva/' admin      
Enter password: 

Connecting to database [plocal:/Library/Application\ Support/MailArchiva/ROOT/database/archiva/] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/Library/Application/ Support/MailArchiva/ROOT/database/archiva' with mode=rw
	DB name="archiva"

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'archiva' because it does not exist in path: /Library/Application/ Support/MailArchiva/ROOT/database/archiva
	DB name="archiva"
```

**Comment by valenpo** [comment]
`plocal:/Library/Application Support/MailArchiva/ROOT/database/archiva/` solve the problem
