### ISSUE TITLE
unable to access class after truncate 

### ISSUE THREAD

**Issue by fabriziofortino** [orientechnologies/orientdb#1555]
Sometimes after executing "truncate class" command the class and its cluster become unusable and the following error message is displayed:

**Error: com.orientechnologies.common.io.OIOException: You cannot access outside the file size (0 bytes). You have requested portion 10-11 bytes. File: File: data.ocl os-size=1001024, stored=1000000, filled=0, max=524287995**

**Comment by luigidellaquila** [comment]
Old issue, it was fixed long time ago

Closing

Thanks

Luigi
