### ISSUE TITLE
Object database custom proxy handler implementation

### ISSUE THREAD

**Issue by ZoltanMantric** [orientechnologies/orientdb#1584]
As discussed on the google group forums, it would be very useful if we could give Orient our own custom implementation of proxy object handlers. This would be especially useful in my use case to save the connection the POJO was created from in the proxy handler and therefore always get the appropriate connection in the pool when doing proxied calls.

This would allow a proxied POJO from Orient to be sent to any thread and make UI code or applicative layers independent from Orient which is desirable.

We would need to be able to set a custom factory for making our own version of the invoke method of the com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler class.

Note that a custom for Lazy object collections would also be very nice, since these lazy lists may also make calls to the database and we do not want the application/UI layers to have to worry about connections set in threadlocal.

**Comment by tglman** [comment]
I think this does not make sense anymore, closing
