### ISSUE TITLE
a word segmenter can be setted to support Chinese FULLTEXT index

### ISSUE THREAD

**Issue by ninesunqian** [orientechnologies/orientdb#1596]
Hello!
I want to set a word segmenter to segment Chinese sentence to words to build FULLTEXT index.  Do you have the plan to in the near future ?

for example : 
mmseg : http://technology.chtsai.org/mmseg/
standfordNLP: http://nlp.stanford.edu/software/segmenter.shtml

the segmenter implements the interface Analyzer of Lucene. Orientdb can use a  Analyzer object to segment sentence.

**Comment by andyhu** [comment]
Is it already done? I saw from the documentation page that it says full text search now is provided by using lucene engine

**Comment by ninesunqian** [comment]
Yes, I changed the source code of orientdb-lucene and used SmartChineseAnalyzer.
I know the IBM ICU project, but I did not find the appropriate analyzer for all the language in the project.

**Comment by ninesunqian** [comment]
Yes, I changed the source code of orientdb-lucene and used SmartChineseAnalyzer.
I know the IBM ICU project, but I did not find the appropriate analyzer for all the language in the project.

**Comment by andyhu** [comment]
@ninesunqian Thanks for your reply. Is it easy to change? I don't have much knowledge in both lucene and java. I think the official should document more on this, and make it configurable without any hacking of source code.
By the way, did you mean you would like to support segmenting all languages? I know [a solution](http://www.basistech.com/solutions/search/elasticsearch/) which support more than 40 languages, but it's a commercial software and it's based on elasticsearch. I've tested it with a trial version, it's powerful but a bit overwhelmed in my project so I didn't use it. Not sure if there's any other opensource solution to do it.

**Comment by ninesunqian** [comment]
@andyhu very easy. I am not familliar with query language of orientdb，so changing the source code is the simplest method.
I am writing a mindmap tool, so want a "all-purpose" word segmentor. But the requirment is open source.

**Comment by martingg88** [comment]
any idea how to solve the following issue. 

try to index with following analyzer but class not found . 

{"analyzer":"org.apache.lucene.analysis.cn.smart.SmartChineseAnalyzer"}

try to install the plugin for org.apache.lucene.analysis.cn.smart.SmartChineseAnalyzer but have following error 

15-11-16 16:50:21:047 SEVER Plugin definition file ('plugin.json') is not found for dynamic plugin 'lucene-analy
rs-smartcn-4.7.0.jar' [OServerPluginManager]Error on installing dynamic plugin 'lucene-analyzers-smartcn-4.7.0.j
'

**Comment by ninesunqian** [comment]
@martingg88 you must add SmartChineseAnalyzer dependency in your pom.xml

**Comment by martingg88** [comment]
i can't find any pom.xml in orientdb folder

**Comment by ninesunqian** [comment]
Sorry, I thought you develop your program using jar file.
If you use server binary package, add jar file of  SmartChineseAnalyzer to lib/orientdb-core-xxx.jar

**Comment by martingg88** [comment]
thanks for your info

**Comment by andyhu** [comment]
SmartChineseAnalyzer is a pretty weak one. Is it possible to integrate IK Analyzer?

**Comment by ninesunqian** [comment]
Putting all the segmenter to a directory is the best

**Comment by robfrank** [comment]
Analyzers are loaded using java reflection.
So, just put the jar in the lib dir.
OrientDB comes with lucene-analyzers-common, that  includes a lot of anlayzers.  

To use lucene as index engine in orientDB refer to doc:
http://orientdb.com/docs/last/Full-Text-Index.html
