### ISSUE TITLE
Vacuum and removal of cluster level lock for plocal storage.

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1600]
Currently updates are in place updates (use the same record space) to keep rid unchanged  and record creation operations are forced to perform page defragmentation if it is not enough space which is not occupied by deleted records (some times will generate a lot of WAL records). 
But we able to perform append only record updates and creations. The page defragmentation(removal of unused space) will be performed on schedule basis (a la Apache Cassandra - compaction, InnoDB - purge, PostgreSQL - vacuum) by background process (lets call it Vacuum too )) ) . Such append only updates/creations will be - fast, will minimize amount of data in WAL, will not require record locking at all (we always have new record instance during update).

P.S. As side effect it will be useful to create some kind of performance suite to test all such big storage changes in future.

**Comment by lvca** [comment]
@laa What's the status of this?

**Comment by laa** [comment]
It is part of https://github.com/orientechnologies/orientdb/issues/1677
