### ISSUE TITLE
Provide new RIDSet implementation based on SBTree data structure

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1604]
RIDSet is not durable now if we will base our implementation of SBTree it will solve given issue.

Here is the list of subtasks which we have to implement:
- [x] 1. Make LINKBAG tracked data structure (2 hours) - DONE.
- [ ] 2. Implement atomic updates, so now we have atomic updates for single db component but if we have to use sbtree as LINKBAG inside of document we should make updates of sbtree and document to be single atomic unit, otherwise tx mode will not work (3-4 days). (Artem)
- [x] 3. Port graphdb implementation (4 days) - DONE. 
- [x] 4. Create MT test for LINKBAG (1 -2 days) - DONE.
- [x] 5. Implement JSON serialization (2 days). - DONE
- [x] 6. Implement means to work and serialize LINKBAG through remote connection (3 days). - DONE (Artem)
- [x] 7. Partition SBTree data structure by clusters (4 h) - DONE.
- [x] 8. Implement embedded version of LINKBAG (2 days) - DONE. 
- [x] 9. Make LINKBAG indexable (2 days).  - DONE
- [x] 10. If document is removed all LINKBAG entries should be removed too (4-7 days). - DONE
- [x] 11. Create MT test for the whole Graph DB which is based on LINKBAG (2-3 days). - DONE
- [x] 12. Run blueprints test not only on plocal but on remote too (2-4 days). (Artem) - DONE
- [x] 13. Backward compatibility or automatic migration procedure of graph (5 days). (Artem) -DONE
- [x] 14. Wiki page about RidBag (1-2 days) (Artem) - DONE
- [x] 15. Add embedded LINKBAG  lazy serialization/deserialization (3 days) - DONE
- [x] 16. Remove global lock from mvrbtreesset and force to use only embedded mode - DONE
- [ ] 17. Distributed storage support
  - [x] partial solution. Use embedded bag in distributed mode
  - [ ] Support tree-based bag in distributed mode
## Bugs:
- [x] **BUG-1**: Preliminary remove and then add previously not contained record cause absence of this record in Bag - FIXED
- [x] **BUG-2**: Size becomes inconsistent after removing nonexistent value from bag. - FIXED

So in total it is 20 days for whole team.
After 6-th task is completed we can integrate it inside develop branch.

**Comment by lvca** [comment]
Should we move this forward again?

**Comment by laa** [comment]
Will add in 3.0 once https://github.com/orientechnologies/orientdb/issues/5267 will be fixed. 3.1 for now

**Comment by andrii0lomakin** [comment]
Fixed in 3.2.
