### ISSUE TITLE
unable to traverse links in SQL conditions when indexes are used.

### ISSUE THREAD

**Issue by mattaylor** [orientechnologies/orientdb#1609]
I have a couple of classes, one which references the other and an index on the LINK, as follows...

```
<< create class myClass1
<< create property myClass1.name STRING

<< create class myClass2
<< create property myClass2.ref LINK myClass1

<< create index myClass2.ref

```

I then create a couple of objects which reference each other as in ..

```
<< insert into myClass1 set name='myName1'

<< insert into myClass2 set ref = (select from myClass1 where name = 'myName1')
```

All is good when I do queries which use the RID of class1 in the condition eg..

```
<<  select from myClass2 where ref = #10:1
>> 1 result found
```

However if I try to use where conditions that traverse the link, I get no results eg 
```
<<  select from myClass2 where ref.name = 'myName1'
>>  0 results found
```
If I drop the the index however, the above query works as expected.
```
<< drop index myClass2.ref
<< select from myClass 2 where ref.name = 'myName1'
>> 1 result found
```

**Comment by lvca** [comment]
Tried with 2.1-rc4 and works.
