### ISSUE TITLE
Publish some performance data!

### ISSUE THREAD

**Issue by hansgru** [orientechnologies/orientdb#1634]
You mention on the main site that _"It's written in Java and it's amazing fast: can store up to 150,000 records per second on common hardware."_

Would you please publish some real performance data, measurements, comparisons, benchmarks or whatever? Something more than just "marketing slogans".
I don't mean this: https://github.com/orientechnologies/orientdb/wiki/GraphDB-Comparison , but something more useful such as Poleposition http://polepos.org/ or some comparison to the widely used MongoDB or Redis ?

regards

**Comment by hansgru** [comment]
@emrul 
> the point I'd intended to make was OrientDb offers features not available to some other databases. So, comparing on one generic benchmark is not going to establish which product is 'best' for your use-case.

That's why there are different tracks and the official tests already cover quite allot (even MongoDB is there).

Even if OrientDB has unique features, most people will pick it for quite common features: e.g. "JSON Document DB as alternative to MongoDB, since it's not native and has transcactions" would be the No. 1 reason people would choose it.

> Therefore, the better option is always to make your own performance tests that reflect your intended usage of a product.

That's not happening, and it will also usually not happen in most of the cases: people will use the published results. Poleposition has the advantage that it's "independent" so those charts are more credible compared to in-house benchmarks of different DBs.

emrul/orient-polepos#1
emrul/orient-polepos#2

**Comment by lvca** [comment]
Not relevant anymore, closing it.
