### ISSUE TITLE
Any open source projects using OrientDB?

### ISSUE THREAD

**Issue by hansgru** [orientechnologies/orientdb#1635]
Are there any open source projects using OrientDB?

I mean **real** and working open source projects that make use of OrientDB as a database/persistence. I haven't really found something usable so far :(.

I don't mean the plug-ins listed here: https://github.com/orientechnologies/orientdb/wiki/Plugins

regards.

**Comment by hansgru** [comment]
@giastfader thank you for the link!

Are there any more projects?
A WIKI page with the projects using it would be helpful. There is one for commercial use, but those are not helpful to see how stuff is done.

**Comment by lvca** [comment]
This is a duplicate of this question: https://github.com/orientechnologies/orientdb/issues/4806
