### ISSUE TITLE
Infinite Time-Waiting Threads in OrientDB Client while Adding Edges

### ISSUE THREAD

**Issue by edalorzo** [orientechnologies/orientdb#1636]
### Overview

My OrientDB client freezes in a very simple concurrent scenario Evidence shows several of my threads get into waiting state. They are waiting on one or more OrientDB threads that went into timed-waiting state and never got out of it. 

Following the evidence and the description on how to reproduce the problem.
### System Information
- **OrientDB Version**.......: 1.5.0
- **Tinkerpop Blueprints**.......: 2.4.0
- **Operating System**......: Windows 7 Enterprise
- **Installed RAM**............: 8 GB
- **Processor**.................: Intel Core i5/2.6Ghz
- **System Type**.............: 64/bit
- **Java Version**..............: JDK-1.7.0_25-b17/64-bit
### Downloads
- [OrientDB Configuration Dump](http://dalorzo.com/tmp/orientdb-bugs/orientdb-configuration-dump.txt)
- [Thread Dump for my Thread Pool](http://dalorzo.com/tmp/orientdb-bugs/orientdb-threaddump-locked.txt)
- [Database Schema and Data](http://dalorzo.com/tmp/orientdb-bugs/orientdb-ddl-dml.txt)
### Preconditions
- Create a database as described in the schema file provided above and populate it with the data provided in that file.
- The data is simple, a set of SKUs and a set of attributes (colors).
- I am using the following JVM options to run my test:

```
-d64 -server -Xmx1024m 
-XX:+UseConcMarkSweepGC -XX:+AggressiveOpts -XX:CompileThreshold=200 
-Dcache.level1.enabled=false
```

For experimantation purposes I also I tried the settings below in certain occasions to see if I would get different results:

```
OGraphDatabase.LOCK_MODE.NO_LOCKING
-Ddb.mvcc=false
```

However, I got the same results of thread-locking problems.
### The Failing Scenario

The failing scenario consists simply in using a set of threads to add all attributes to a given SKU. Therefore the code will simply add edges to the database.

This is what my threads do. It looks for an SKU vertex, and then iterates over a collection of attribute IDs, which I look up and then add an edge from the Sku vertex to the attribute vertex.

``` java
public class DeadlockTest {

    private static final int THREAD_POOL_SIZE = 10;


    private static class AddAttributes implements Callable<Object> {

        private final String skuId;
        private final String[] attributeIds;

        public AddAttributes(String skuId, String[] attributeIds) {
            this.skuId = skuId; 
            this.attributeIds = attributeIds; 
        }

        @Override
        public Object call() {
            for (int i = 0; i < 10; i++) {
                try {
                    attempt();
                    return null;
                } catch (OTransactionException | ONeedRetryException ignore) {
                    System.out.println("Retyring transaction: " + ignore.getMessage());
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
            System.out.println("Exhausted number of attempts");
            return null;
        }

        private void attempt() throws Exception {
            OrientGraph g = new OrientGraph("remote:localhost/fixme", "admin", "admin");
            try {
                try {
                    Vertex skuVertex = g.getVertex(skuId);
                    for (String attribute : this.attributeIds) {
                        Vertex attrVertex = g.getVertex(attribute);
                        g.addEdge("class:HashValue", skuVertex, attrVertex, "HasValue");
                        System.out.printf("Added Edge from %s to %s in thread %s%n",
                                skuVertex,
                                attrVertex,
                                Thread.currentThread().getName());
                    }
                } catch (Exception propagate) {
                    g.rollback();
                    throw propagate;
                }
            } finally {
                g.shutdown();
            }
        }
    }

    public static void main(String[] args) throws Exception {
        String[] skus = new String[20];
        for(int i=0; i < 20; i++) {
            skus[i] = String.format("#12:%d", i);
        }
        String[] attributes = new String[16];
        for(int i=0; i <= 15; i++) {
            attributes[i] = String.format("#11:%d", i);
        }

        OGlobalConfiguration.dumpConfiguration(System.out);

        Collection<Callable<Object>> tasks = new ArrayList<>();
        for (String sku : skus) {
            tasks.add(new AddAttributes(sku, attributes));
        }

        ExecutorService service = Executors.newFixedThreadPool(THREAD_POOL_SIZE);

        List<Future<Object>> results = service.invokeAll(tasks);
        for (Future<Object> result : results) {
            result.get();
        }

        System.exit(0);//this line is never reached.

    }
}
```

This is my main method. This code freezes invariably every time I run it:
### Initial Diagnosis of the Problem

I ran this test several times and analyzed what was going on using both [JConsole](http://docs.oracle.com/javase/6/docs/technotes/guides/management/jconsole.html) and [JVisual VM](http://docs.oracle.com/javase/6/docs/technotes/tools/share/jvisualvm.html).

Invariably, it seems that several threads get into TIME_WAITING state and never come out of it:

```
"pool-1-thread-8" - Thread t@18
   java.lang.Thread.State: TIMED_WAITING
    at java.lang.Object.wait(Native Method)
    - waiting on <6bd79538> (a java.util.ArrayList)
    at com.orientechnologies.orient.client.remote.OStorageRemote.beginRequest(OStorageRemote.java:1805)
...
```

In fact, I found several other threads in this state. They never get out of it. The rest of the treads get blocked by these threads:

```
"pool-1-thread-2" - Thread t@12
   java.lang.Thread.State: WAITING
    at sun.misc.Unsafe.park(Native Method)
    - waiting to lock <3d5a95c3> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync) owned by "pool-1-thread-8" t@18
    ...
```

**Comment by NLPScott** [comment]
@lvca  hi ,I have a problem,could you give me some advise?  I set the db.pool.min and db.pool.max in the orientdb-server-config.xml , <entry value="50" name="db.pool.min"/>
        <entry value="200" name="db.pool.max"/> ,but I can't get db.pool.min =50 and db.pool.max =200 from OGlobalConfiguration.dumpConfiguration(System.out)

**Comment by lvca** [comment]
@NLPScott what's your problem and what are you trying to accomplish?
