### ISSUE TITLE
Command Cluster Status Failing

### ISSUE THREAD

**Issue by edalorzo** [orientechnologies/orientdb#1638]
The undocumented command cluster status fails when I run it from the OrientDB command-line console.

### Steps to Reproduce
1. Have your root user properly configured in the OrientDB server configuration  file.
2. Start the OrientDB server.
3. Open an OrientDB command-line console.
4. ```connect remote:localhost/tinkerpop root root```
5. Run the command: ```cluster status```

I get the following output:
```
Cluster status:

!ERROR: Error on executing 'Cluster status'
-> User or password not valid for database: 'tinkerpop'
```

If I run the command a second time I get:

```
Cluster status:
{}
```

### System Information

 * **OrientDB Version**.......: 1.5.0
 * **Tinkerpop Blueprints**.......: 2.4.0
 * **Operating System**......: Windows 7 Enterprise
 * **Installed RAM**............: 8 GB
 * **Processor**.................: Intel Core i5/2.6Ghz
 * **System Type**.............: 64/bit
 * **Java Version**..............: JDK-1.7.0_25-b17/64-bit

**Comment by lvca** [comment]
Replaced with `HA STATUS` in v2.2
