### ISSUE TITLE
Internal Scheduler Handler does not works with plocal databases

### ISSUE THREAD

**Issue by giastfader** [orientechnologies/orientdb#1653]
The internal scheduler managed by the class OScheduleHandler does not work with plocal databases.

The problem is in the method exists() that performs a check on the existence of the default.0.oda file.
That file does not exists for plocal databases, so the handler returns an error and does not execute the scheduled functions.

**Comment by lvca** [comment]
It's on our roadmap a rewriting of the Scheduler: https://github.com/orientechnologies/orientdb/issues/6125
