### ISSUE TITLE
Check if a field exists in a document [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#166]
This is [Issue 166](http://code.google.com/p/orient/issues/detail?id=166) moved from a Google Code project.
Added by 2010-12-01T09:49:40.000Z by [emailmat...@gmail.com](http://code.google.com/u/101508822421503325316/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Fixed).

Original labels: Type-Enhancement, Priority-Low, v1.0rc3
### Original description

```
A handy feature would be to check if a field exists within a document. Like MongoDB's $exists: http://www.mongodb.org/display/DOCS/Advanced+Queries#AdvancedQueries-%24exists
```

**Comment by lightjiao** [comment]
Is this in the document? I can't find this in the document.
[http://orientdb.com/docs/2.2.x/Types.html?q=is%20defined](url)
