### ISSUE TITLE
Command Config Fails in Console

### ISSUE THREAD

**Issue by edalorzo** [orientechnologies/orientdb#1660]
### System Information

 * **OrientDB Version**.......: 1.5.0
 * **Tinkerpop Blueprints**.......: 2.4.0
 * **Operating System**......: Windows 7 Enterprise
 * **Installed RAM**............: 8 GB
 * **Processor**.................: Intel Core i5/2.6Ghz
 * **System Type**.............: 64/bit
 * **Java Version**..............: JDK-1.7.0_25-b17/64-bit

### Stetps to Reproduce

1. Open and OrientDB console
2. Connect to a database: ```connecte remote:localhost/tinkerpop```
3. Run the command: ```config```

I get this error every time:

> Error: com.orientechnologies.orient.core.exception.ODatabaseException: Connection is closed

My connection is fine, because even after the error if I issue any other type of query like  ```select from OUser``` I get good results in the output.

The problem also appears in any other combinations of the ```config``` command like:

```config set cache.level1.size 100```

**Comment by lvca** [comment]
Fixed long time ago.
