### ISSUE TITLE
Provide lock free version of hash index

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1675]
We should use these papers as base http://www.cs.ucf.edu/~dcm/Teaching/COT4810-Spring2011/Literature/SplitOrderedLists.pdf  http://www.azulsystems.com/events/javaone_2007/2007_LockFreeHash.pdf

Do not forget that we use JNA and support platforms beyond Oracle JDK which means that we should work with native memory barriers like this one http://trac.mcs.anl.gov/projects/openpa it has very good multiplatform support but robustness should be investigated.

**Comment by laa** [comment]
Not relevant any more

**Comment by smolinari** [comment]
Can you give a quick explanation why? Or, maybe just a reference to the change that makes it irrelevant?

Scott

**Comment by laa** [comment]
Hi @smolinari 
We are working now on new tx model which will be based on locks with page granularity.
But in some cases will allow to hold write-write , read-write, write-read locks by different threads at the same time.
It will allow us to automatically convert all data structures to their mt version with low level of contention between threads.

We tried to base our tx mechanics on CAS model, but in case of high load it requires a lot of retries and as result system SLA becomes unpredictable. 

After finishing of page lock based MT model we will concentrate on algorithms which oriented on NUMA architecture, we think it will bring even more performance gains than additional improvements in MT scalability.

**Comment by smolinari** [comment]
Although most of that flew above my head, it sounds good. Thank you for the explanation.

Scott

**Comment by laa** [comment]
@smolinari well main idea is that in case of high load, cas or lock-free protocols require many retries and amount of such retries is not predictable and as result client SLA also becomes unpredictable. So we use approach when we use locks but with very low granularity to avoid contention of threads.

**Comment by smolinari** [comment]
What does SLA mean?

Scott

**Comment by laa** [comment]
service level agreement, in other words distribution of latency of operations.

**Comment by smolinari** [comment]
I thought that is what you meant, I just wasn't sure how an SLA could relate to multi-threading. But, I guess, if the database is supposed to meet certain specs as a purchase point and those specs are guaranteed, then I guess I can understand it. It isn't really SLA's though. It is more like fulfilling contractual obligations. 

Scott
