### ISSUE TITLE
Provide multi threaded TXs support

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1677]
Current implementation provides support for serialized transactions, we should move to multithreaded TXs to support modern multicore processors.

**Comment by StarpTech** [comment]
Any updates?

**Comment by lvca** [comment]
This is for v3.0.

**Comment by laa** [comment]
Moved to 3.1 version, in 3.0 we will implement https://github.com/orientechnologies/orientdb/issues/6013 instead.
