### ISSUE TITLE
Multicore support phase 1

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1678]
We have excellent single thread performance but weak multicore support to fix this following issue should be fixed: https://github.com/orientechnologies/orientdb/issues/1676 https://github.com/orientechnologies/orientdb/issues/1611 https://github.com/orientechnologies/orientdb/issues/1610 https://github.com/orientechnologies/orientdb/issues/1600

**Comment by laa** [comment]
it is umbrella issue can  not be implemented in rc-2 because too wide set of features.

**Comment by laa** [comment]
we do not need this umbrella issue any more

**Comment by rdelangh** [comment]
@lvca , @laa 
Is multi-core support for the server Java processes implemented in your upcoming version 3.0 ? The current version (2.2.12) is running purely single-threaded on a single-core only. A big waste of hardware resources in modern servers...

**Comment by laa** [comment]
@rdelangh we already implemented component wide level locks instead of storage level locks. In next version (later than 3.0) we are going to implement key / record level locks which will provide high level of scalability https://github.com/orientechnologies/orientdb-labs/issues/10
