### ISSUE TITLE
Order of records in dataset breaks aggregate functions when using LET assignment

### ISSUE THREAD

**Issue by jakefeasel** [orientechnologies/orientdb#1723]
Using 1.5.1, I have found a very subtle (but significant) problem with LET assignment of aggregate values.

Here are some queries which demonstrate the problem:

```
SELECT 
  source,
  max(year) as maxYear
FROM
  (
    SELECT expand( $union )
    LET 
    $a = (SELECT 'A' as source, '2013' as year),
    $b = (SELECT 'B' as source, '2012' as year),
    $union = union($a,$b)
  )
GROUP BY
  source
```

This simple query correctly returns a result set like so:

```
A | 2013
B | 2012
```

Similarly, this form of the query also works as expected, returning the same result:

```
SELECT 
  source,
  $maxYear as maxYear
FROM
  (
    SELECT expand( $union )
    LET 
    $a = (SELECT 'A' as source, 2013 as year),
    $b = (SELECT 'B' as source, 2012 as year),
    $union = union($b,$a)
  )
  LET
    $maxYear = max(year)
GROUP BY
  source
```

Note that now we are using the LET assignment for the value of the aggregate, rather than having it in the select list.  Also, note that I have changed the order of the records in the union, so that the value I'm aggregating is in ascending order.

Now try running this query:

```
SELECT 
  source,
  $maxYear as maxYear
FROM
  (
    SELECT expand( $union )
    LET 
    $a = (SELECT 'A' as source, 2013 as year),
    $b = (SELECT 'B' as source, 2012 as year),
    $union = union($a,$b)
  )
  LET
    $maxYear = max(year)
GROUP BY
  source  
```

It is the same as the above, except the values being aggregated are no longer in ascending order (union($b,$a) => union($a,$b)). With this query, you get this incorrect result:

```
A | 2013
B | 2013
```

I haven't found a way to force the order of the result set to be ascending using an ORDER BY clause either. There is no way around this that I have found, short of simply not using LET assignment for aggregate values.

**Comment by lvca** [comment]
This issue is very old. @luigidellaquila could we write a test case for that against latest snapshot?

**Comment by luigidellaquila** [comment]
Yes, I'm on it

**Comment by luigidellaquila** [comment]
due to current executor implementation, it's not possible to implement this in current release. 
I'm postponing this. 
In the meantime I added a validation check for this kind of query, so that this kind of queries (LET of aggregate function + GROUP BY) throws a parsing exception, instead of returning inconsistent result.
