### ISSUE TITLE
Feature Request:  Array of Field Validation Errors

### ISSUE THREAD

**Issue by delebash** [orientechnologies/orientdb#1726]
Currently field validation errors throw OValidationException , this class just has a list of string messages that include the field name in the string message.

It would be nice instead to have an array of fieldName,className,errorMsg,errorCode, returned when an OValidationException this way you can consume it in your client application easier.  Some client frameworks expect field validation errors to be returned from the server as fieldName, errorMsg, this way you can match the errorMsg with the field the user is trying to edit.  For now you have to parse the error string and manually pull out the fieldName, className and errorMsg.  This way you can build a custom errorMsg to be displayed on the client with fieldName and erroMsg

The errorCode would just be an easy way to match up custom errorCodes on the client,  Example if you have a field is mandatory error, but you want to word the errorMsg different from what the server generates you can just make a map on your client matching server side errorCodes with the ones on your client to produce a custom worded errorMsg of the same type.  ie ErrorCode 123 = mandatory ErrorCode 456 = Not Null ect.

Thanks,

Dan

**Comment by lvca** [comment]
Not relevant anymore, closing it.
