### ISSUE TITLE
Server side level txs

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1731]
This issue is more discussion than plan to do , but I thought about following,
With WAL we do not need to track txs on client side only, because we do not need to keep all the changes in memory, so no server overhead.
It gives as following:
1. No temporary tx rids  which got complains in ML, only valid ones.
2. No memory overhead because we need to keep all tx records in memory before commit, so heap which is wasted now in tx mode and usually empty will be used for disk cache, we need really a few memory to serialize/deserialize object in case of big graphs just hundred megabytes.
3. No problem with SQL queries in TX mode, new and updated records will not be lost.
4. Code will be cleaner, because we simply drop good amount of code )).

Disadvantage of course is (may be ...)  performance will be slower on tx server mode, it is easy to test just drop begin/commit for big set of commands, make indexes fully durable in non tx mode (we have option for this) and lets check.

WDYT ?

**Comment by laa** [comment]
Assigned to @tglman

**Comment by tglman** [comment]
Hi,

As today the support of server side tx is done, with the support on server side of both: client that maintain the status of the tx, and client that leave the status only on the server.

Closing
