### ISSUE TITLE
COLA Tree indexes

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1756]
We successfully implemented sbtree index engine BUT it contains just a few optimizations for big data processing COLA trees are much faster in big data case (about 200 times faster on inserts in case of almost all content is places out or RAM and we have billions of records). 
This issue requires to resolve several open questions:
1. Durability 
2. Efficient multi core (it is even harder than multi threading) implementation.

My estimation is 3 months of full time development for single person and 2 months in pair but we will have a dramatic speedup on big data case.

This change have to be implemented after completion of plocal storage and multi core support for new disk cache.

**Comment by CasperCLD** [comment]
Any news on this? When is this going to be implemented?

**Comment by laa** [comment]
We need  time to implement this. so now we work on smaller issues.

**Comment by tychota** [comment]
Any plan in near road or starmap ??

**Comment by laa** [comment]
Hi,

Now we concentrated on multicore scalability.
But then will work on mitigation of random IO overhead.

So for next several months we will not work on this issue.

**Comment by tychota** [comment]
Ty for answer ;)

**Comment by laa** [comment]
I think with new transaction system which we are working on problems listed in issue description will be solved automatically , so we will have all tools to implement given issue.

**Comment by saeedtabrizi** [comment]
@lvca  , @laa is there any chance to have cola index in OrientDB 3 release ?

**Comment by laa** [comment]
@laa there were big chances that we put it in 3.x release. I am working now on design to gather together all pieces of implementation of coal tree indexes. We will start with detiled design proposal during a couple of months and then will put it on our schedule.

**Comment by lvca** [comment]
This means it will be not available for 3.0, but later.

**Comment by saeedtabrizi** [comment]
@laa , @lvca it's a good news for orientdb lovers . :+1:

**Comment by laa** [comment]
Not actual any more

**Comment by pontusvision** [comment]
Sorry, please explain what happened with this issue; have the changes been implemented, or are they no longer relevant?  The documentation points to this page, but I cannot understand whether it has been implemented, or it has been cancelled.

**Comment by jankotek** [comment]
@pontusvision my understanding COLA trees (buffer trees) are obsolete by append only  store such as  RocksDB. I am not sure how OrientDB, but I never implemented it in MapDB.
