### ISSUE TITLE
expand() returns wrong number of results

### ISSUE THREAD

**Issue by Sysvision** [orientechnologies/orientdb#1763]
We just encountered some strange behavior with the expand() function. Because unfortunality when using OR operator in a SELECT statement the whole statement is executed as cluster scan, which is pretty slow for 200k+ rows (see #1751) we thought we split the query into multiple parts (that can make use of indexes) and use union() function to join the results.

We are using v.1.6.0-SNAPSHOT (20131010-1330)

```
SELECT $c LET
$a = (SELECT FROM V1 WHERE ...),
$b = (SELECT FROM V1 WHERE ...),
$c = union($a, $b)
----+-----+----
#   |@RID |$c
----+-----+----
0   |#-2:0|[0]
----+-----+----
```

If we select $c.size() we get 2, which is correct in this case:
```
SELECT $c.size() LET
$a = (SELECT FROM V1 WHERE ...),
$b = (SELECT FROM V1 WHERE ...),
$c = union($a, $b)
----+-----+----
#   |@RID |$c
----+-----+----
0   |#-2:0|2
----+-----+----
```

But if we select expand($c) we get 3 results:
```
SELECT expand($c) LET
$a = (SELECT FROM V1 WHERE ...),
$b = (SELECT FROM V1 WHERE ...),
$c = union($a, $b)
----+-----+-------
#   |@RID |user   
----+-----+-------
0   |#11:0|1000000
1   |#11:1|1000001
2   |#-2:0|null   <--- ????
----+-----+-------
```

But if we wrap this in a sub-query we get the correct number of results again:
```
SELECT expand(inner) FROM (
    SELECT $c as inner LET
    $a = (SELECT FROM V1 WHERE ...),
    $b = (SELECT FROM V1 WHERE ...),
    $c = union($a, $b)
)
----+-----+-------
#   |@RID |user   
----+-----+-------
0   |#11:0|1000000
1   |#11:1|1000001
----+-----+-------
```

**Comment by luigidellaquila** [comment]
This is an old issue, it's supposed to be fixed long time ago. I just checked it on v 2.1.5 and it works fine.

I'm closing it, please reopen in case I missed something

Thanks

Luigi
