### ISSUE TITLE
Escaping not handled correctly when updating

### ISSUE THREAD

**Issue by rore** [orientechnologies/orientdb#1772]
If you insert a JSON document through the REST which looks like this:
{ "name" : "\"a\"" }
The quotation mark escaping is handled correctly, and the name test appears as "a".

But if you try to do the same via update SQL:
update #13:1 set name = "\"a\""

The text of the field includes the escaping, and looks like this: "\"a\""

**Comment by AaronSchulz** [comment]
This works on SNAPSHOT now after various escaping fixes.

**Comment by lvca** [comment]
Thanks @AaronSchulz to inspect old issues ;-)
