### ISSUE TITLE
 Prepared queries not working with functions and limit in SQL

### ISSUE THREAD

**Issue by darkredz** [orientechnologies/orientdb#1795]
I have tested a piece of code here:

ODatabaseDocumentTx db = ODatabaseDocumentPool.global().acquire("remote:localhost/testme", "admin", "admin");

        HashMap<String, Object> param = new HashMap<String, Object>();
        param.put("name", "len");

        OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>("select from Product where name.toLowerCase().indexOf( :name ) > -1 limit 20");
        List<ODocument> result = db.command(query).execute( param );

        for(ODocument rs : result){
            System.out.println( rs.toJSON() );
        }

the parameter is :name but it doesn't give me any result when there's a record in my class which contains the name "Leng".
Further investigation make it looks even weirder.

This parameter returns the correct result
 param.put("nm", "len");
 where name.toLowerCase().indexOf( :nm )

Then I tried this
 param.put("ss", "len");
 where name.toLowerCase().indexOf( :ss )

it gives me all the records from the class (limit 20).

Related discussion: https://groups.google.com/forum/#!topic/orient-database/leaYdCtwTm0

**Comment by luigidellaquila** [comment]
It's already fixed in v.2.1. 

I'm closing it

Thanks

Luigi
