### ISSUE TITLE
console connect plocal failure followed by connect local fails

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#1796]
orientdb : 1.6
os : OSX (but I assume it is os agnostic)

ISSUE:
Create a local database (e.g. /tmp/test
This correctly fails b/c it is not a plocal database:

orientdb> connect plocal:/tmp/test admin admin
Connecting to database [local:/tmp/test] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/tmp/test' with mode=rw
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'db' because it does not exist in path: /tmp/test

But then this fails and continues to fail unless you quit the console and start it again:

orientdb> connect local:/tmp/test admin admin
Connecting to database [local:/tmp/test] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/tmp/test' with mode=rw
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'db' because it does not exist in path: /tmp/test

WORKAROUND:
Quit console and start it again.

**Comment by luigidellaquila** [comment]
"local" storage is no longer supported. 

Closing

Thanks

Luigi
