### ISSUE TITLE
Time machine

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#180]
This is [Issue 180](http://code.google.com/p/orient/issues/detail?id=180) moved from a Google Code project.
Added by 2010-12-13T00:39:19.000Z by [l.garu...@gmail.com](http://code.google.com/u/111607061083712272202/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v1.4
### Original description

```
It would be awesome to support something like a &quot;Time Machine&quot; inside OrientDB. My idea is:
- to allow to certain classes to keep the history of changes
- every create/update/delete will be kept as version
- new operator to execute a query as it would be executed back in the past:

SELECT FROM Customer WHERE ... BACK TO 2010-01-01 00:00:00
```

**Comment by gregid** [comment]
Is this feature still considered for Milestone 3.0. I would require it for one of my projects (simulating workflow changes on past data) so curious if there has been any change in this regards.

**Comment by lvca** [comment]
Sorry, this isn't a priority, postponed.

**Comment by marktshaw** [comment]
I can't stress enough at how this would be a significant differentiator for OrientDB. To handle bi-temporal datasets would be outstanding. We are investing a great deal of time and effort bending OrientDB into something that supports this and if it was simply a flick of the switch... we would never be tempted by alternative technology.
