### ISSUE TITLE
LINKLIST: provide a better serialized implementation for many items

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1808]
This is related to the issue #1807.

Right now the linklist is stored as [<rid>,<rid>]. This doesn't scale when you've many items because everytime OrientDB has to un-marshall the full list, add an item and re-marshall it. So we need something like we did for LINKSET but with LIST. The first idea in my mind is linked list, but probably there can be better impl.

**Comment by tglman** [comment]
Hi,

This has no meaning anymore, closing
