### ISSUE TITLE
Improve performance of compound queries

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1816]
Lets suppose that we have query 
"select from Client where address in (select from Address where city='Montreal')"
There are two way to execute it:
1. Execute internal query, retrieve list of results of this query and execute external query iterating through internal query results as parameters. This approach allows to provide minimum overhead and use indexes as for outer and for inner queries.
2. Fetch every record from class Client and execute inner query using record which is processed by outer query as optional parameter (current approach). This approach provides much more flexibility in query creation but does not allow to use indexes for external query and requires much more resources.

Lets suppose that Address class has 100 records and Client class has 100 records.
And inner query returns 10 records.

Then execution of query using 1-st approach requires 100 + 10 \* 100 = 1 100 iterations.
Execution of query using 2-nd approach requires 100 \* 100 = 10 000  iterations.

So using first approach we can execute sample query 10 times faster.

So it would be good to detect the types of queries when inner queries do not depend on outer queries and use 1-st approach to execute them.

**Comment by laa** [comment]
Assigned to @luigidellaquila

**Comment by luigidellaquila** [comment]
In v 3.0 the execution planner understands when inner queries depend on the context of the parent query and when they don't. The execution plan adapts accordingly, executing the inner query only once when possible

Closing, thanks!

Luigi
