### ISSUE TITLE
Console: allow authentication as parameter rather than "connect" command.

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1822]
This would allow command like:
    console.sh -url remote:localhost/demo -u admin:admin "select from Orders"

**Comment by robfrank** [comment]
Using the LOAD SCRIPT console command (http://orientdb.com/docs/last/Console-Command-Load-Script.html) it's easy to don't include the credentials in the script:
```sql
console.sh "CONNECT REMOTE:localhost/demo admin admin;LOAD SCRIPT /path/to/scripts/data.osql"
```

**Comment by lvca** [comment]
Ok, so we don't need this. Closing.
