### ISSUE TITLE
Object oriented disk cache

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1830]
Now when we load page we load page pointer, create new page object, perform operations, remove object. So we always have object creation overhead even if object page always cached. To avoid it, it would be good to allow cache not pointers but links to "page" objects. For cache no difference at all and heap overhead will be small. But we avoid constant object initialization overhead.

**Comment by lvca** [comment]
Seems low-pri, postponing it to 2.2

**Comment by laa** [comment]
Not sure it is needed any more , milestone was removed.

**Comment by laa** [comment]
Not actual any more
