### ISSUE TITLE
Transaction: failed commit() is different from rollback()

### ISSUE THREAD

**Issue by wardev** [orientechnologies/orientdb#1871]
First, thank you for making Orientdb!

I've noticed that when a commit() fails due to concurrent modification the transaction is not properly rolled back. I've posted a failing test case that shows the issue here: https://gist.github.com/wardev/b66e191b988f3f7debb6

If I replace the last graph.commit() with graph.rollback() (on line 34) the test passes. I would expect that a commit that fails would be the same as a rollback operation.

I'm using blueprints-orient-graph 2.4.0.

**Comment by luigidellaquila** [comment]
Fixed long time ago (the source issue was fixed in 2013)

Closing

Thanks

Luigi
