### ISSUE TITLE
MongoDB Capped Collections equivalent

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1878]
MongoDB has capped collections, namely fixed-size collections with circular writes:

http://architects.dzone.com/articles/mongodb-pubsub-capped

It's very easy to implement some interesting feature of Capped Collection on top of OrientDB. This could be useful for queues or logging.

**Comment by saeedtabrizi** [comment]
@lvca is there any update ?

**Comment by lvca** [comment]
We were too busy with other issues this wasn't in the roadmap, sorry. We could think of an implementation for 3.1/3.2.

**Comment by sakno** [comment]
I see that this feature is not implemented yet. Could you please provide some workaround that helps to implement ring buffer functionality (similar to capped collections) with minimal overhead?

**Comment by sakno** [comment]
Why closed? Is it implemented?

**Comment by andrii0lomakin** [comment]
Hi @sakno , we are not going to implement it in foreseen future. We can return back to this feature after some time. But that will be the subject of additional disucussion.
