### ISSUE TITLE
Add support for vertex - centric indexes in graphdb.

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1895]
- [ ] 1. Implement IndexMap and integrate it with bonsai collection manager (2 day)
- [ ] 2. Implement atomic updates, so now we have atomic updates for single db component (2 days)
- [ ] 3. [EXCLUDED] graphdb integration (4 days)
- [ ] 4. Create MT test for IndexMap (2 days)
- [ ] 5. Implement JSON serialization (2 days)
- [ ] 6. Implement means to work and serialize IndexMap through remote connection (3 days)
- [ ] 7. Partition SBTree data structure by clusters (4 h)
- [ ] 8. [EXCLUDED] Implement embedded version of IndexMap (2 days)
- [ ] 9. If document is removed all IndexMap entries should be removed too (2 days). - DONE
- [ ] 10. Create MT test for the whole Graph DB which is based on IndexMap (2-3 days). - DONE
- [ ] 11. [EXCLUDED] Add embedded IndexMap lazy serialization/deserialization (3 days) - DONE
- [ ] 12. [EXCLUDED] Distributed storage support
- [ ] 13. Make iterator based on cursor (port from sbtree) (3 days)
- [ ] 14. Support cursor based iteration in remote storage (2 days)

**Comment by lvca** [comment]
@luigidellaquila will follow up with a new issue about this.

**Comment by lvca** [comment]
We don't need this anymore, but rather the MATCH executor will use indexes on edges if any.
