### ISSUE TITLE
Ordering doesn't work with projection

### ISSUE THREAD

**Issue by studiodev** [orientechnologies/orientdb#1911]
Hello,

I've just discovered a weird behavior on ordering. The result is not the same between a `SELECT FROM X` and `SELECT Y FROM X` with ordering.

The dabatase used for this example is attached to this issue.

`SELECT FROM MediationNetwork ORDER BY stats_nbIndividuals DESC` or `SELECT @rid, stats_nbIndividuals FROM MediationNetwork ORDER BY stats_nbIndividuals DESC`

> 12:62000, 12:64837, 12:48976, 12:55737... It's good

`SELECT @rid FROM MediationNetwork ORDER BY stats_nbIndividuals DESC``

> 12:32799, 12:32800, 12:32801, 12:32802, 12:32803...

_Configuration_
OrientDB 2.0-SNAPSHOT (build 12/23/2013)
Storage: plocal
DB : https://mega.co.nz/#!6R10UahI!RYWK41eoQlX5rhL4pNpFAnglbU9Ey5fUj9I3zctJ8RY

**Comment by luigidellaquila** [comment]
The execution planner in v 3.0 solves this problem, implicitly calculating order projections (without returning them in the result) when they are not explicitly declared

Closing, thanks!

Luigi
