### ISSUE TITLE
Restore data in small batches to avoid probability of OOM during data restore.

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#1913]
Currently we perform restore of data after DB crash by accumulating of all operations for given atomic unit in RAM and then applying these operations in direct (commit) or reverse (rollback) order. But if tx was big it can lead to OOM.

So to prevent such behavior following is proposed:

1. Apply changes to cache pages during WAL iteration and accumulate only records LSNs.
2. If we have to rollback changes, do following fetch 10 last pages, apply old page values in reverse order, go back to 20 pages, read 10 pages, apply old page values in reverse order  and so on.

Of course rollbacks will be handled slower than commits but rollbacks are pretty rare and will not affect overall performance.

**Comment by lvca** [comment]
@laa Is this already fixed?

**Comment by lvca** [comment]
@laa probably you changed the WAL restore in last branch. Is this still valid?

**Comment by lvca** [comment]
What's the role of this issue with the new WAL?

**Comment by laa** [comment]
Hi guys it is invalid, we may fix it.
