### ISSUE TITLE
Error on opening database: the engine 'plocal' was not found

### ISSUE THREAD

**Issue by synthbeat** [orientechnologies/orientdb#1925]
Error on opening database: the engine 'plocal' was not found. URL was: plocal:D:/program-files/orientdb-community-1.6.3/databases/Person. Registered engines are: [local, memory]

How should I register the plocal engine? I have searched all over the documentation and still haven't found a way to do it.

**Comment by dattatray123** [comment]
i facing same issue  with google apps connector

**Comment by dattatray123** [comment]
is there  any solution to register plocal
