### ISSUE TITLE
increase upper limit of number of clusters

### ISSUE THREAD

**Issue by tedsmithgroup** [orientechnologies/orientdb#1930]
Is it possible to increase the max allowed number of clusters rather than
at fixed 32767 (perhaps int/32 type)?  this upper limit could be reached
in quite some use cases and we would have y2k like issue.

**Comment by wouterv** [comment]
+1

**Comment by 8forty** [comment]
+1

**Comment by tglman** [comment]
to solve this we need to review this two main parts:
 - ridbag serialization that may be solved with this: https://github.com/orientechnologies/orientdb/issues/4500
 - Cluster Position map, that need a design solution that is not going to break binary compatibility

**Comment by cwaldron** [comment]
What is the status of this issue.  This issue is scheduled in 2.2.0-rc1 release but is still open at this time.  To have a major feature change open for an RC at this stage seem incorrect to me.  If this issue is still open it would have be moved out of RC to another milestone.  Is this the case or is this issue closed?

**Comment by lvca** [comment]
This was moved in v3.0 in our roadmap, this issue hasn't been updated.

**Comment by krullert** [comment]
+1

**Comment by abuising** [comment]
+1

**Comment by mcaramma** [comment]
+1

**Comment by lvca** [comment]
Hi guys, we moved this issue forward because with high number of clusters you'd have many files opened and this could cause problems if the underlying OS is not properly set. So the storage team is working on improving managing open files, then we can support this feature.

**Comment by krullert** [comment]
Thanks Luca, that would be a big help!

**Comment by lightjiao** [comment]
> can anyone please confirm if this issue has been implemented (ie raise of max number of clusters)?

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

No, the limit is still 32k

Thanks

Luigi

**Comment by lightjiao** [comment]
Hi @luigidellaquila 
do you have any plan to raise the max number of clusters ?

**Comment by andrii0lomakin** [comment]
We do not consider increasing the limit in overseen future.
