### ISSUE TITLE
Console.sh is not working if the $ORIENTDB_HOME directory has a folder with spaces

### ISSUE THREAD

**Issue by Dante-666** [orientechnologies/orientdb#1934]
>sudo console.sh
Error: Could not find or load main class Databases.OrientDB.releases.orientdb-community-1.6.3.bin.config.orientdb-client-log.properties

The "Databases" folder is actually the folder "Graph Database" and there are folders above it too.

**Comment by joaobarcia** [comment]
Hi @lvca, this is still hapenning to me. I am running Ubuntu 15.04 and tested 2.1rc5 and 2.1rc6
One the parent folders of OrientDB were named "../Webdev tests/Meteor/Orient/orientdb-community-2.1-rc5".

When I try to launch the console I receive the error ```Error: Could not find or load main class tests.Meteor.orientdb-community-2.1-rc5.config.orientdb-client-log.properties```
