### ISSUE TITLE
ODatabaseImport writes to System.err instead of using logging or simply propogating the exception

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#1935]
The following line is writing to System.err which probably should not be done.  It should either just propogate the exception or log using the standard logging api in orientdb (slf4j preferrably but since that is not used directly, java.util.logging).

com.orientechnologies.orient.core.db.tool.ODatabaseImport.java:210
      System.err.println("Error on database import happened just before line " + jsonReader.getLineNumber() + ", column "
          + jsonReader.getColumnNumber());

**Comment by mathieubodin** [comment]
In 2.0-rc1 version, there are still two uses of ```System.err``` on line 1306 and 1309.
