### ISSUE TITLE
Console backup doesn't work

### ISSUE THREAD

**Issue by studiodev** [orientechnologies/orientdb#1937]
Hello,

I've an error when I try to backup a DB from an Orient console, is it the good command?

This is the scenario:

`create database remote:localhost/test root root plocal graph`
OK

`backup database /tmp/test` (https://github.com/orientechnologies/orientdb/wiki/Console-Command-Backup)

> Backuping current database to: database /tmp/test...
Error: java.lang.UnsupportedOperationException: backup

Environment : OrientDB 1.6.3 (mac&debian)

**Comment by bmcgavin** [comment]
+1 for better error message, still not clear in 2.1

**Comment by lvca** [comment]
Reopened to have better exception
