### ISSUE TITLE
support query projections for multiple properties from a linkset or linklist

### ISSUE THREAD

**Issue by mattaylor** [orientechnologies/orientdb#1938]
A SQL feature we use a lot is to select only a single property records in a linkset or linklist for example..

```
select name, roles.name from ouser
```

This could be written as 

```
select name, roles[name] from ouser
```

It would be super usefull if this syntax could be expanded to support retreival of multiple properties from a linkset or linklist 

eg...

```
<< select name, roles[name,@rid],from ouser
>> name:'admin', roles:[{@rid:'#2:1', name:'reader'}]
```

**Comment by Kalatheeswaran** [comment]
Hi, 
How to get the value of 'b' for a particular value of 'a' (say if a =1 then b = 10) from this linkset query Select roles.include('a','b') from user ?

**Comment by luigidellaquila** [comment]
V 3.0 solves this use case with nested projections:

http://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections

Closing

Thanks

Luigi
