### ISSUE TITLE
the console seems not work for me

### ISSUE THREAD

**Issue by Sanyorke-Han** [orientechnologies/orientdb#1941]
Hi,
   Today is the first time I use OrientDB. when I download, the server can run up, and i can use the browser to connect. but the console didn't work for me. I use  64 bit windows 7 with java 1.7.0_04. here is the final command while run the console.bat. it looks hanging there.

```
D:\Program\orientdb-1.6.3\bin>call "C:\Program Files\Java\jdk1.7.0_04\bin\java" -client -Dcache.leve
l1.enabled=false -Dcache.level2.enabled=false -Djava.util.logging.config.file="D:\Program\orientdb-1
.6.3\config\orientdb-client-log.properties" -Djava.awt.headless=true -Dfile.encoding=utf-8 -Dorientd
b.build.number="UNKNOWN@r${buildNumber}; 2013-12-27 19:58:08+0100" -cp "D:\Program\orientdb-1.6.3\li
b\*;" com.orientechnologies.orient.graph.console.OGremlinConsole
```

thanks.
![orientdb-console-hanging](https://f.cloud.github.com/assets/2055205/1885403/8889151c-79cc-11e3-9509-35464169c7b2.JPG)

**Comment by craigbroadbear** [comment]
I get the same issue.  Windows 8, x64 java 1.8.0_45-b14

**Comment by rakeshghodasara** [comment]
I am facing similar issue in linux.  The console just doesnt do anything whatever I type
![image](https://cloud.githubusercontent.com/assets/13034507/10286578/f23fd944-6b53-11e5-9777-d4de6b147ee8.png)

**Comment by brumsel** [comment]
Any update on this one? Having same issue as rakeshghodasara
![orientdb console problem](https://cloud.githubusercontent.com/assets/8542954/11335357/fa0b38b8-91db-11e5-9a93-d6d85aab2dd8.jpg)

**Comment by anurag2090** [comment]
@brumsel @rakeshghodasara @lvca I had the similar issue, I just started console.sh with sudo, and it started working (on a *nix machine)
