### ISSUE TITLE
Build number is probably incorrect in 1.6.3 script files.

### ISSUE THREAD

**Issue by bckfnn** [orientechnologies/orientdb#1953]
When starting version 1.6.3 server with server.bat it report a version of

 1.6.3 (build UNKNOWN@r${buildNumber}; 2013-12-27 19:58:08+0100)

when calling DB_OPEN, which I guess is not the intended value.

The server.bat file contains the incorrect number:

-Dorientdb.build.number="UNKNOWN@r${buildNumber}; 2013-12-27 19:58:08+0100"

Obviously a minor issue.

**Comment by luigidellaquila** [comment]
Fixed long time ago, closing
