### ISSUE TITLE
first() query operator

### ISSUE THREAD

**Issue by enisher** [orientechnologies/orientdb#1961]
The SQL operator that take any Iterable or SQL subquery result and returns a single record.

It also could be implemented as (query)[0] syntax. However I think this variant is less readable.
# Usecases
- Assign query result to a property as a single variable

``` SQL
insert into UsesTool set CarId = first(select @Rid from Car where name='Mercedes' limit 1)
```
- Filtering with equity operator instead of in operator

``` SQL
select from UsesTool where CarId = first(select @Rid from Car where name='Mercedes' limit 1)
```

**Comment by lvca** [comment]
Not relevant anymore, closing it. We can already use `[0]`
