### ISSUE TITLE
Schema generator creates properties for transient fields

### ISSUE THREAD

**Issue by imeszaros** [orientechnologies/orientdb#1965]
Using the object database interface, automatic schema generator creates properties for fields detected as "transient" by the serializer (transient, @Transient, static).

I guess this is not the preferred behavior. If so, the mistake is in

```
com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.generateSchema(Class<?>, ODatabaseRecord) [line 238]
```
when it calls 
```
com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.getClassFields(Class<?>)
```
which returns all fields not the only the persistent ones.

**Comment by lvca** [comment]
Fixed long time ago.
