### ISSUE TITLE
Loading Graph ML file into specific SCHEMA 

### ISSUE THREAD

**Issue by guntukaramakrishna** [orientechnologies/orientdb#1970]
Hi Luca,

As per the thread from orient db groups ,https://groups.google.com/forum/#!topic/orient-database/bOPpJxwzr5Y, the graphml file should be loaded into specific SCHEMA.

The blueprints is not providing such kind of facility at api level.

It is some thing like,

reader.inputGraph(filename); instead of this, reader.inputGraph(filename, schema) is available it would be great.
- Troy.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
