### ISSUE TITLE
Database repair tool [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#200]
This is [Issue 200](http://code.google.com/p/orient/issues/detail?id=200) moved from a Google Code project.
Added by 2011-01-17T10:05:50.000Z by [l.garu...@gmail.com](http://code.google.com/u/111607061083712272202/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, v1.4
### Original description

```
We need a new tool to repair the database in some cases like:
- accidental removing of admin user/role
- broken indexes
- ...
```

**Comment by valenpo** [comment]
Is it possible to check that database corrupted on embedded mode and if, start repair in background?
