### ISSUE TITLE
Remove recursion during document serialization

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#2002]
Currently we can see many requests in mailing list and in bug tracker which say that users see stackoverflow exception during document serialization but it is always possible using well known approaches to replace recursion used in document serialization by loop.

**Comment by lvca** [comment]
@tglman Is this part of Dirty Manager?

**Comment by tglman** [comment]
yes is definitly related to https://github.com/orientechnologies/orientdb/issues/2620

**Comment by tglman** [comment]
the current develop, doesn't use anymore recursion on save, closing.
