### ISSUE TITLE
Edges creation/deletion permissions on ORestricted nodes

### ISSUE THREAD

**Issue by giastfader** [orientechnologies/orientdb#2003]
Hi,
the current available features related to the ORestricted class and permissions settings don't allow to implement this particular use case of ours:
Imagine a user make a simple blog post (or update his Facebook status), in this case he is the owner of the record and has full permissions.
Other users can see his post (they have the _allowRead permission) and want to leave a comment. So they write their own comments but they cannot link the comment nodes with the post node because they have no update permission on it.
And they never should be able to update the original post!
So what should be very useful is a new kind of permission, something similar to _allowAddEdge (and _allowRemoveEdge).

WDYT?

**Comment by red-0ne** [comment]
Any news on that feature? We have this exact problem and can't find any workaround. Allowing the update of vertices will oblige us to rewrite a great part of our project. Could the use of heavyweight edges be of any help?

**Comment by red-0ne** [comment]
Any chance to have a milestone for this issue?

**Comment by micha-nerdlichter** [comment]
Same problem here: I want to create edges with a user that has no update permission for the vertex. For me this doesn't seem to be such an uncommon case as soon as you use restricted permissions in a graph db scenario.

Is there still no solution for this?

**Comment by red-0ne** [comment]
We use a "superuser" account to create/remove the edges, but this is completely against what is promoted by the restricted permissions feature and it may not apply to all use cases. Also this case is valid in all "append only" kind of applications
