### ISSUE TITLE
SQL and locking strategies

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2010]
It's time to start discussing about the record locking strategies we'll support in OrientDB. I prefer to open this thread to all the users here, instead of talk about it internally in Orient Technologies, because I'm confident we could receive good idea and contributions.

Even tough Optimistic approach (CAS like) is great for many use cases, sometimes users need a more "Pessimistic" approach by locking resources. This is the case of persistent queues or any other operation I need to be sure no other thread/client is fetching the same record.

Few of the issues related to this topic:
- Pessimistic TX: https://github.com/orientechnologies/orientdb/issues/12
- Non-TX Atomic ops: https://github.com/orientechnologies/orientdb/issues/1056

Now we've the ORecordLockManager that extends the OLockManager (that has been developed more than 2 years ago, so probably it would need a refresh about better synchronization policies?) that does the job: locking RID in read or write mode.

We already use it internally, but I'd like to let to the user to expressly lock resources. I don't know if I'd like the classic RDBMS way to just use the transaction (or some variant of SQL like SELECT FOR UPDATE) or better to offer a more explicit way to lock resources giving more control/power to developers.

Below my initial proposal.
## Support LOCK/UNLOCK directly in SELECT, UPDATE AND DELETE

Examples:

``` sql
SELECT FROM Client WHERE city.name = 'London' LOCK SHARED
UPDATE Client SET local = true WHERE city.name = 'London' LOCK EXCLUSIVE
DELETE FROM Client WHERE local = true LOCK EXCLUSIVE
```
## New SQL LOCK command

Syntax: 

``` sql
LOCK <cluster-name|rid|(select-statement)> SHARED|EXCLUSIVE
```
## New SQL UNLOCK command

Syntax:

``` sql
UNLOCK <cluster-name|rid|(select-statement)|*> SHARED|EXCLUSIVE
```

Where:
- "*" means release all the acquired locks
## Automatic releasing of locks

Locks are kept by ODatabase instance that represents a client connection. Once the server disconnects a database it should close it. The ODatabase.close() should free all the acquired locks.
## Real use cases: FIFO queue management

Even though we could provide better way to manage a queue, this would work. Push a message into a queue (class Queue):

``` sql
INSERT INTO Queue SET payload = 'yeah', date = sysdate()
```

Pop the first message (returning is a new keyword part of the issue https://github.com/orientechnologies/orientdb/issues/1056):

``` sql
DELETE FROM Queue ORDER BY date LIMIT 1 LOCK exclusive RETURNING before
```

This is also related to the issue #1056 

Full thread on: 
https://groups.google.com/forum/#!searchin/orient-database/Record$20Locking/orient-database/fD-UNnq9zmc/Gw1DiV6zK1EJ

**Comment by giggs131400** [comment]
can the lock or unlock statement use in orientdb?
