### ISSUE TITLE
OServer isActivated() and isConfigured()

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#2012]
Please add

public boolean isActivated();
public boolean isConfigured();

to:
com.orientechnologies.orient.server.OServer

isActivated corresponds to the activate and shutdown methods.

isConfigured corresponds to the startup methods (maybe it should be called isStarted but that will be confused with the isActivated method... I'd actually argue that the startup methods should have been named "configure" instead...

In any case, these methods will allow us to determine the status of the OServer without having to look for open ports.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
