### ISSUE TITLE
Studio UI covers New Class and Rebuild All Indexes if width is too small

### ISSUE THREAD

**Issue by eutheria** [orientechnologies/orientdb#2014]
![mozilla firefox_004](https://f.cloud.github.com/assets/1312853/2051498/4614aad8-8a8a-11e3-8351-beb500035332.png)

because i have a long database name the dark menubar drops down covering the New Class, Rebuild Indexes and Search box

**Comment by maggiolo00** [comment]
Fixed long time ago with media queries on header menu
