### ISSUE TITLE
Improve export/import with multiple formats: GRAPHML, GRAPHJSON and SQL

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2033]
We'd need a more powerful export/import that support format. Right now we use a OrientDB proprietary JSON format, but it would be nice supporting:
- **SQL**: this would be similar to RDBMS, where re-running the export.sql would produce an identical database
- **GRAPHML**, we could use the Graph API that already support it
- **GRAPHJSON**, we could use the Graph API that already support it (https://groups.google.com/forum/#!topic/gremlin-users/SD7yXKT8DXY)

**Comment by Eric24** [comment]
+1

**Comment by lvca** [comment]
In last 2.2.9 import is already able to import from GraphML and GraphSON. It's still missing:
- export in GraphML (easy to do because it's already in TinkerPop libs)
- export in GraphSON (easy to do because it's already in TinkerPop libs)
- export in SQL. This requires more code.
