### ISSUE TITLE
Console command should return standard exit status

### ISSUE THREAD

**Issue by studiodev** [orientechnologies/orientdb#2034]
Hello,

An improvement proposal that could be useful for people who need to write scripts using OrientDB (eg: migration tool).

The console should return different exit status according to the last command result. `0` if OK, `1` (or another int) in case of failure.

```
console.sh "connect remote:localhost/rsu admin admin; SELECT FROM V;"
echo $?
0 // OK

console.sh "connect remote:localhost/rsu admin wrongpwd; SELECT FROM V;"
echo $?
0 // Expected: all except 0
```

**Comment by robfrank** [comment]
It works. We use exec "java...." to run the console. 
This command contains errors:
```shell
console.sh "connect remote:localhost/demodb admin adm; select from Countrie"
echo $?

1
```
and returns 1
