### ISSUE TITLE
Implement Console Command: drop database if exists

### ISSUE THREAD

**Issue by ameertamboli** [orientechnologies/orientdb#2038]
If there is requirement to drop the existing database and create new one on OrientDB Console, then following commands can be used:

drop database remote:localhost/testgraphdb1 root xyz

create database remote:localhost/testgraphdb1 root xyz local graph;

If database doesn't exist already, it gives error:
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot delete the remote storage: testgraphdb1

New command "drop database if exists" will avoid the error and continue the execution of the next command without error. Something like this will be helpful:

drop database if exists remote:localhost/testgraphdb1 root xyz

create database remote:localhost/testgraphdb1 root xyz local graph;

**Comment by mscarlett** [comment]
See also #3597.

**Comment by loganmzz** [comment]
> We've the workaround in #2606, so this is low priority.

This is not an acceptable workaround as you can't determine if there was a deletion problem or just because database doesn't exist.
