### ISSUE TITLE
Create Link should support edges too

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2045]
Now the [create link command](https://github.com/orientechnologies/orientdb/wiki/SQL-Create-Link) supports the raw Document model only. This is the syntax:

```
CREATE LINK <link-name> TYPE [<link-type>] FROM <source-class>.<source-property> TO <destination-class>.<destination-property>
```

We could add a new <link-type>, like "EDGE", to force the creation of edges instead of links. But this would be more a CREATE EDGE command, so probably the best is to  support this syntax in CREATE EDGE command?

**Comment by gongdo** [comment]
Well, the milestone has been set, but here's +1 for it.
It's good idea for 1-to-1 relationship. I want to avoid to use LINK instead of edge.

**Comment by zhuobao** [comment]
How is this going? what is the timeline expected?

**Comment by zhuobao** [comment]
@lvca how is this going and what would be the timeline? this is really crucial for using orientdb as an analytical tool facing general analysts.

**Comment by lvca** [comment]
@zhuobao the target is for 3.1 This command is usually needed or the initial import, so it's not so crucial IMHO. You can use OrientDB ETL for that or writing a small piece of code that do that.

**Comment by zhuobao** [comment]
@lvca I see the very high demands of this command in social media, customer segmentation and cash/portfolio management and other scenarios which requires edges/networks are in constantly changing/testing. In an organization, with 100+ database users, data production environment ETL processes can not be changed that frequently. The same to a massive create vertex, insert into vertex, insert into edges. I Just do not think analyst would like to use java or python writing vulnerable code to manipulate huge amount data cross systems to perform these options.
