### ISSUE TITLE
Object DB: Saving POJOs inside a Transaction

### ISSUE THREAD

**Issue by dxxr** [orientechnologies/orientdb#2062]
OrientDB v1.6.3

With no transactions it is possible to save a POJO to the database, which always results in an INSERT operation.

In contrast, saving a POJO inside a transaction leads to an exception stating that the object needs an @Version annotated field. But this would introduce an otherwise unnecessary dependency on the JPA to my simple data beans.

As a workaround, I'm currently creating proxied instances via db.newInstance() which can be saved inside the transaction. But this approach requires an open database connection where the instances are created, which I otherwise wouldn't need.

It would be nice if _inserting_ a POJO into the database would also work inside transactions.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
