### ISSUE TITLE
[Bug] Studio Link property creation "linked class" select not enabled

### ISSUE THREAD

**Issue by jsnoriegam** [orientechnologies/orientdb#2063]
### Small OrienDB Studio bug:

![orientdb studio - class link linked type](https://f.cloud.github.com/assets/1829140/2240715/d9c0dbd0-9ca5-11e3-9556-db156f5d3051.PNG)

It can still be changed on the properties table.

Tested in 1.6.4 and 1.7RC1

**Comment by luigidellaquila** [comment]
Fixed long time ago

Closing

Thanks

Luigi
