### ISSUE TITLE
Document Field Part with hyphens - 1.7RC

### ISSUE THREAD

**Issue by BeyondBounds** [orientechnologies/orientdb#2078]
The following fails:
select name[culture='en-us'].value from item where key = "GSXR1000"

With error:
java.lang.NumberFormatException: For input string: "culture='en"

The following succeeds:
select name[culture="en-us"].value from item where key = "GSXR1000"

It seems that you cannot use a single quote if there is a hyphen after the equals operator. This is not true when used as part of the where clause, e.g. select name from item where key = 'GSX-R1000' - returns success

**Comment by luigidellaquila** [comment]
This bug is already fixed in v 2.1

Closing. Please reopen if you experience similar problems

Thanks

Luigi
