### ISSUE TITLE
osgi.export seems incorrect in distributed

### ISSUE THREAD

**Issue by npetzall** [orientechnologies/orientdb#2085]
In distributed/pom.xml the osgi.export is: com.orientechnologies.orient.server.cluster.hazelcast.* which doesn't exist in distributed.

So either the package is incorrect in distributed or the osgi.export is incorrect since the package is: com.orientechnologies.orient.server.hazelcast

In any case currently nothing is exported.

**Comment by lvca** [comment]
Fixed.
