### ISSUE TITLE
Security issue - OUser and ORole not sub-classes of ORestricted

### ISSUE THREAD

**Issue by gauravdhiman** [orientechnologies/orientdb#2095]
As OUser / ORole are not sub classes of ORestricted, all records of these classes can be fetched by any DB user and no record level access be can be applied for records in these classes. 

To overcome this, wont it be good if all classes are derived from ORestricted, including OIdentity. As per my understanding of OrientDB security, I think it will be good to have below class structure

ORestricted --> OIdentity --> OUser
ORestricted --> OIdentity --> ORole
ORestricted --> Other developer defined classes

Kindly refer the related discussion here - https://groups.google.com/forum/#!topic/orient-database/M-4-DXJ2gcg

Regards,
Gaurav

**Comment by lvca** [comment]
You can do this in v2.1 with multiple inheritance.
