### ISSUE TITLE
FetchPlan notation enhancement

### ISSUE THREAD

**Issue by BonesGit** [orientechnologies/orientdb#2101]
Hi all, 

I have a feature request for the fetch plan notation as it applies to ORecordAbstract.toJson( String iFormat ).  If it works for the rest of the fetch plan use cases all the better.

The following is in regards to 1.7-rc1.  First I'll show the code, then I will explain.

com.orientechnologies.orient.core.fetch.OFetchHelper.java 
Replace line 146 with the following (not tested)
```
		if (fieldFetchDefinition.startsWith("*.")) {
			if ( fieldFetchDefinition.endsWith("*") ) {
				if ( iFieldPath.contains(fieldFetchDefinition.substring(1, fieldFetchDefinition.length()-1)) ) {
					depthLevel = iFetchPlan.get(fieldFetchDefinition);
			        break;
				}
			} else {
				if ( iFieldPath.endsWith(fieldFetchDefinition.substring(1, fieldFetchDefinition.length())) ) {
					depthLevel = iFetchPlan.get(fieldFetchDefinition);
			        break;
				}
			}
		} else if ( fieldFetchDefinition.endsWith("*") ) {
			if ( iFieldPath.startsWith(fieldFetchDefinition.substring(0, fieldFetchDefinition.length()-1)) ) {
				depthLevel = iFetchPlan.get(fieldFetchDefinition);
		        break;
			}
		} else if (iFieldPath.equals(fieldFetchDefinition)) {
```

Add "*." to allow matching of a property at any level.
This will allow one to do something like:
```
fetchPlan:*:-1 *.password:-2
```
This will block any password property at any level of the json output.
This way I do not have to write different paths for different object/graph structures.  It will simply block all passwords from serializing no matter where they are.  For instance:
```
user.password
contact.user.password
group.contact.user.password
```

Next add "*" suffix.
This allow for prefix matching.
```
fetchPlan:*:-1 out_*:-2 in_*:-2
```
This will block all out and in edges from serializing to json, so one doesn't have to know all defined edges ahead of time.

By Combining both of these you can do something like the following:
```
fetchPlan:*:-1 *.out_*:-2
OR
fetchPlan:*:-1 *.user.out_*:-2
```
This will block all out edges anywhere in the resulting json structure or block all the user out edges anywhere from the json.

Thoughts?

**Comment by lvca** [comment]
This syntax could be confusing, because the * has too many meanings. I'd prefer adding something better, like the depth level concept. We could use `[]`to express it. Valid syntaxes are:
- depth level, example: `[1]`
- range of depth levels, example: `[0-5]`
- any level, example: `[*]`

Your examples above would become:

    fetchPlan:*:-1 [*]out_*:-2

OR

    fetchPlan:*:-1 [*]user.out_*:-2
