### ISSUE TITLE
Studio login failed

### ISSUE THREAD

**Issue by arebya** [orientechnologies/orientdb#2108]
With orientdb-community-1.7-rc1,when I click the "Server" on studio page,it shows the dialog for username and password ,but I have tried many times unsuccessfully.
I have modified the generated password to be a string such as "admin", which is easy to be remembered.

I don't know why that happens sometime,and how to fix it!Thank you!

**Comment by luigidellaquila** [comment]
When logging into the "Server" panel you have to use root credentials.

If a problem existed on this, it was fixed a long time ago

Closing

Thanks

Luigi
