### ISSUE TITLE
Unable to access databases through functions

### ISSUE THREAD

**Issue by codeblood** [orientechnologies/orientdb#2109]
Hello everyone, I'm currently using OrientDB 1.7-rc2 and I've created the following function with the studio:

```Javascript
return orient.getDatabase().query('select from ouser');
```
When I try running it, I get the following message:

> Error on parsing script at position #0: Error on execution of the script Script: test ------^ sun.org.mozilla.javascript.internal.WrappedException: Wrapped com.orientechnologies.orient.core.exception.OConfigurationException: No database instance found in context (#2) in at line number 2 Wrapped com.orientechnologies.orient.core.exception.OConfigurationException: No database instance found in context (#2) No database instance found in context

I have the following (default) handler set on the server configuration file:

```xml
<handler class="com.orientechnologies.orient.graph.handler.OGraphServerHandler">
    <parameters>
        <parameter value="true" name="enabled"/>
        <parameter value="50" name="graph.pool.max"/>
    </parameters>
</handler>
```
Is there anything I can do to get this working?

**Comment by blue-coder** [comment]
Any workaround till it is fixed?

**Comment by lvca** [comment]
Please don't use a so old version, also unstable (rc2). Please try with 2.0.5

**Comment by luigidellaquila** [comment]
It's already fixed in stable release.

Closing
