### ISSUE TITLE
Projections for nested documents in query

### ISSUE THREAD

**Issue by enisher** [orientechnologies/orientdb#2118]
# The problem

Current syntax of projections comes from relational world where everything is a flat table. However there is links and nested records in document model. And there is no possibility to project fields of linked or nested documents and keep nesting.

There is a possibility to prevent loading of some fields of linked documents using fetch plan. But it is not allow to include only specific fields.

For example you have a Shop, Merchandise and Producer. And you want to select all shops with merchandise and its producers, but producer have a lot of properties and you need to load only its name and country.

```
SELECT name, include(merchandise, 'name', 'producer') FROM Shop
```

The query above loads all properties of producer.

**fetchPlan and include/exclude functions**
Some use-cases can be implemented by fetchPlan and include/exclude functions, however this is less convenient and provide less flexibility.
# Proposed syntax

```
selectQuery ::= SELECT <projections> FROM ...
projections ::= <projection>(, <projection>)*
projection ::= <fieldName>(':{' <projections> '}')? (as <alias>)?
```
# Examples

```
SELECT 
  name, 
  address:{country:{name, capital} as country, city.name as city, street, building} 
FROM Customer
```

Result example:

```
{
  name: "Customer1"
  address: {
    country: {
      name: "Ukraine", 
      capital: "Kiev"
    }
    town: "Dnipropetrovsk"
    street: "..."
    building: 99
  }
}
```

**Graph example:**

```
SELECT 
  name, 
  out('repositories').out('commits'):{date, message} as commits 
FROM Developer
```

Result example:

```
{
  name: "Martin",
  commits: [
    {date: "12-08-2013", message: "Fix minor bug"}
    {date: "13-08-2013", message: "Fix major bug"}
  ]
}
```

**Comment by luigidellaquila** [comment]
I don't like this syntax very much, in particular I don't see the need for the initial "fieldname:".
My proposed syntax is jut

SELECT name, 
    {
"country": {"name": name, "capital": capital }}

**Comment by luigidellaquila** [comment]
I don't like this syntax very much, in particular I don't see the need for the initial "fieldname:".
My proposed syntax is jut

SELECT name, 
    {
"country": {"name": name, "capital": capital }}

**Comment by luigidellaquila** [comment]
I don't like this syntax very much, in particular I don't see the need for the initial "fieldname:".
My proposed syntax is jut

SELECT name, 
    {
"country": {"name": name, "capital": capital }}

**Comment by lvca** [comment]
+1 for this syntax

**Comment by tortis** [comment]
+1 This would be awesome.

**Comment by StarpTech** [comment]
+1 very nice

**Comment by serebro** [comment]
+1

**Comment by luigidellaquila** [comment]
Hi guys,

some news on this issue. In v.2.2 this is already supported in MATCH statement.

The following query is valid (GratefulDeadConcerts)

```
MATCH {class:V, as: v, where: (name like '%en%') }
return {
   "name":v.name, 
   "metadata":{
      "type":v.type
   }
}
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Some more news here. In V 3.0 this syntax is also supported in SELECT statement

Thanks

Luigi

**Comment by luigidellaquila** [comment]
The nested projection syntax is implemented in develop branch (3.0 SNAPSHOT). It will be released with 3.0 M2.

For more details https://github.com/orientechnologies/orientdb-docs/blob/3.0.x/sql/SQL-Projections.md

**Comment by jpstrikesback** [comment]
Big win!

**Comment by jpstrikesback** [comment]
@luigidellaquila will we be able to use the RETURN keyword in SELECT like in MATCH? It is rather nice as it allows one to template a response shape (with easy aliases etc).

In addition will RETURN in MATCH inherit the behaviour of the new SELECT nested projections (I assume this new capability handles returning nested list properties)

**Comment by luigidellaquila** [comment]
Hi @jpstrikesback 

there is no need for a RETURN keyword in the SELECT, RETURN is just the equivalent of the projections in the SELECT, eg.

MATCH {class:V, as: v, where: (name like '%en%') }
return {
   "name":v.name, 
   "metadata":{
      "type":v.type
   }
}
is the same as

```
SELECT
{
   "name": name, 
   "metadata": {
      "type": type
   }
}
FROM V WHERE name like '%en%'
```

Thanks

Luigi

**Comment by thinklinux** [comment]
Is there a way for doing this with the projection api?

https://stackoverflow.com/questions/49495351/orientdb-returning-json-with-embedded-vertices-from-a-match-query

I'm trying for hours now and I can't find the right syntax or any examples of this use case.
