### ISSUE TITLE
storage.diskCache.pageSize cannot be <= 16k

### ISSUE THREAD

**Issue by carloprad** [orientechnologies/orientdb#2120]
If storage.diskCache.pageSize value in orientdb-server-config.xml is equal or less then "16" I cannot create a new plocal database, and a monster internal.pcl file appears in $ODB_HOME/databases:

orientdb> create database remote:localhost/kubique root root plocal graph;

Creating database [remote:localhost/kubique] using the storage type [plocal]...Cannot create the remote storage: kubique
Exception during response processing.
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:264)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:231)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:202)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:113)
-> com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1856)
-> com.orientechnologies.orient.client.remote.OStorageRemote.getResponse(OStorageRemote.java:1872)
-> com.orientechnologies.orient.client.remote.OServerAdmin.createDatabase(OServerAdmin.java:201)
-> com.orientechnologies.orient.client.remote.OServerAdmin.createDatabase(OServerAdmin.java:165)
-> com.orientechnologies.orient.console.OConsoleDatabaseApp.createDatabase(OConsoleDatabaseApp.java:272)
-> sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
-> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
-> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-> java.lang.reflect.Method.invoke(Method.java:606)
-> com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:279)
-> com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:156)
-> com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:94)
-> com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:53)
Cannot create database
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:264)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:231)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:202)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:113)
-> com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1856)
-> com.orientechnologies.orient.client.remote.OStorageRemote.getResponse(OStorageRemote.java:1872)
-> com.orientechnologies.orient.client.remote.OServerAdmin.createDatabase(OServerAdmin.java:201)
-> com.orientechnologies.orient.client.remote.OServerAdmin.createDatabase(OServerAdmin.java:165)
-> com.orientechnologies.orient.console.OConsoleDatabaseApp.createDatabase(OConsoleDatabaseApp.java:272)
-> sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
-> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
-> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-> java.lang.reflect.Method.invoke(Method.java:606)
-> com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:279)
-> com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:156)
-> com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:94)
-> com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:53)
The field 'OUser.roles' has been declared as LINKSET but contains a null record (probably a deleted record?)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:264)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:231)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:202)
-> com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:113)
-> com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1856)
-> com.orientechnologies.orient.client.remote.OStorageRemote.getResponse(OStorageRemote.java:1872)
-> com.orientechnologies.orient.client.remote.OServerAdmin.createDatabase(OServerAdmin.java:201)
-> com.orientechnologies.orient.client.remote.OServerAdmin.createDatabase(OServerAdmin.java:165)
-> com.orientechnologies.orient.console.OConsoleDatabaseApp.createDatabase(OConsoleDatabaseApp.java:272)
-> sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
-> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
-> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-> java.lang.reflect.Method.invoke(Method.java:606)
-> com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:279)
-> com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:156)
-> com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:94)
-> com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:53)
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create the remote storage: kubique
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database
Error: com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.roles' has been declared as LINKSET but contains a null record (probably a deleted record?)

root@orientdbZone:~# ls -la /opt/orientdb-community-1.6.4/databases/kubique/
total 806
drwxr-xr-x   2 root     root          21 Mar 12 18:52 .
drwxr-xr-x   3 root     root           3 Mar 12 18:51 ..
-rw-r--r--   1 root     root        1367 Mar 12 18:52 database.ocf
-rw-r--r--   1 root     root        1024 Mar 12 18:52 default.cpm
-rw-r--r--   1 root     root       17408 Mar 12 18:52 default.pcl
-rw-r--r--   1 root     root       17408 Mar 12 18:51 dictionary.sbt
-rw-r--r--   1 root     root       17408 Mar 12 18:52 index.cpm
-rw-r--r--   1 root     root       17408 Mar 12 18:52 index.pcl
-rw-r--r--   1 root     root       17408 Mar 12 18:52 internal.cpm
-rw-r--r--   1 root     root     1150599336049001472 Mar 12 18:52 internal.pcl
-rw-r--r--   1 root     root           0 Mar 12 18:52 kubique.0.wal
-rw-r--r--   1 root     root           0 Mar 12 18:52 kubique.wmr
-rw-r--r--   1 root     root       17408 Mar 12 18:52 manindex.cpm
-rw-r--r--   1 root     root       17408 Mar 12 18:52 manindex.pcl
-rw-r--r--   1 root     root         572 Mar 12 18:51 name_id_map.cm
-rw-r--r--   1 root     root       17408 Mar 12 18:52 orole.cpm
-rw-r--r--   1 root     root       17408 Mar 12 18:51 ORole.name.sbt
-rw-r--r--   1 root     root       17408 Mar 12 18:52 orole.pcl
-rw-r--r--   1 root     root        1024 Mar 12 18:52 ouser.cpm
-rw-r--r--   1 root     root       17408 Mar 12 18:51 OUser.name.sbt
-rw-r--r--   1 root     root       17408 Mar 12 18:52 ouser.pcl

Here my environment:
ODB: 1.6.4 community
OS: Solaris 11.1 64bit
JVM: 1.7.51 64 bit

**Comment by laa** [comment]
It is very old, I am closing it.
