### ISSUE TITLE
Allow parametrized target in SQL queries.

### ISSUE THREAD

**Issue by enisher** [orientechnologies/orientdb#2122]
Allow set parameter as a target in sql queries. Value of this parameter could be `OIdentifieble` or `Collection<OIdentifieble>`

It will allow to simplify query like:
```SQL
traverse * from (select from V where @rid = :rid)
traverse * from (select from V where @rid in :rids)
```
to:
```SQL
traverse * from :rid
```

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot
