### ISSUE TITLE
Maven repository for stables in wiki error

### ISSUE THREAD

**Issue by arebya** [orientechnologies/orientdb#2123]
Maven repository for stables for orientdb in wiki is error.

it should be below without" <type>bundle</type>"
<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orient-commons</artifactId>
			<version>${orientdb.version}</version>
		</dependency>
		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-core</artifactId>
			<version>${orientdb.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-client</artifactId>
			<version>${orientdb.version}</version>
		</dependency>

**Comment by luigidellaquila** [comment]
This issue is not valid anymore. 


Closing
