### ISSUE TITLE
Java document API page is broken

### ISSUE THREAD

**Issue by ericdcobb** [orientechnologies/orientdb#2128]
I visited the java document API page today and was presented with a blank form. I typed "why is the empty" into the form and submitted it, now that's all your doc  API page says:

https://github.com/orientechnologies/orientdb/wiki/Java-Tutorial:-Document-API

If this documentation isn't written yet, someone might want to change the entry to a TODO instead of my one comment.

**Comment by luigidellaquila** [comment]
Old issue, This page is not referenced by any other doc page.

Current docs can be found here

http://orientdb.com/docs/last/

Closing, thanks

Luigi
