### ISSUE TITLE
addEdge with orid to minimize dependency on referenced Vertex.

### ISSUE THREAD

**Issue by acmeguy** [orientechnologies/orientdb#2132]
Allow edges to be created with ORID:
- someVertex.addvertex(type, orid)
- graph.addvertex(type,source_orid,target_orid)

This would mean that I'm only referencing the target vertex and that NO other update is requested for the target vertex

Resolved during during commit:
- The <orid> is resolved to the latest version of the target vertex (JIT)
- The edge is created (JIT)
- Retry this X times if the target vertex is locked or on concurrent exception

See this discussion:
https://groups.google.com/forum/?fromgroups=#!topic/orient-database/qbXlDJbK8m8

**Comment by acmeguy** [comment]
Hi, Can this be done using the Java API?

**Comment by lvca** [comment]
Ys, it's already there.

**Comment by acmeguy** [comment]
already where? :)

**Comment by lvca** [comment]
@acmeguy We implemented it in SQL command. Did you mean the addEdge() in Java API? You can do:

    Edge e = g.addEdge( null, new OrientVertex( g, "#12:33" ) ), new OrientVertex( g, "#134:9348" ), "Friend" );

**Comment by acmeguy** [comment]
Luca, this line makes no sense :) 

I'm trying to add edges to existing vertices from a new vertex without updating the version number of the existing vertex. I thought I had this working but it's updating version numbers like crazy.

My line is:
newVertex.addEdge(type, existingVertex, properties);

**Comment by lvca** [comment]
This is another problem: set `-Dindex.embeddedToSbtreeBonsaiThreshold=1` and you always have a separate structure to handle edges and the vertices will be not updated anymore.

**Comment by acmeguy** [comment]
I have that set already: OGlobalConfiguration.RID_BAG_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD.setValue(1);

Sorry, I thought the two were linked.

is this irrelevant:
RID_BAG_SBTREEBONSAI_TO_EMBEDDED_THRESHOLD

**Comment by lvca** [comment]
Sorry, copy and paste: you should set it to `-1` that means ALWAYS. The value RID_BAG_SBTREEBONSAI_TO_EMBEDDED_THRESHOLD is for the opposite: when downscale to embedded from a tree.

**Comment by acmeguy** [comment]
yeah, I had it at -1 :)

**Comment by stevehu** [comment]
2.1-SNAPSHOT I have OGlobalConfiguration.RID_BAG_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD.setValue(-1);  
 
in my factory when getting OrientGraph and the vertex version still increasing and constantly getting concurrency modification exceptions and transaction rollback. I am using Java API and I don't think it does retry if it fails.  In my use case, I consider vertex changed only when properties are changed but not edges. Could anyone point me to the right place on how the above configuration works? I will try to use -D in command line but it is not ideal. Thanks.

**Comment by lvca** [comment]
Are you using OrientDB embedded or remote? In case of remote, where did you set that -D ?

**Comment by stevehu** [comment]
Embedded using plocal. Thank.

**Comment by lvca** [comment]
Are you working with distributed server (replication)? However, could you provide the code responsible of the exception?

**Comment by stevehu** [comment]
No. I only have one server with embedded plocal server. I tried to put 
-Dindex.embeddedToSbtreeBonsaiThreshold=-1
as VM Options but it still not working.
    "@type": "d",
    "@rid": "#14:0",
    "@version": 276,     // should be 0
    "@class": "User",

My code is complicated and there are several classes involved. I will create a test case based on 2.1-SNAPSHOT. Thanks.

**Comment by stevehu** [comment]
Here is the three line of code which is called by passing in different data with the same userId. The third line increase the user version for each edge creation.

            Vertex createUser = graph.getVertexByKey("User.userId", data.remove("createUserId"));
            rule = graph.addVertex("class:Rule", data);
            createUser.addEdge("Create", rule);

**Comment by lvca** [comment]
I've just added 2 test cases in ec23c69316f8c484380302babd34e82575ee5c40 commit and adding elements in tree ridbag doesn't increment version. Please could you send us a running test case to demonstrate the problem?

**Comment by stevehu** [comment]
@lvca Thanks for the quick response. I think your test case only focuses on ridbag but it doesn't mean version won't be changed by other functions when edge is added. I have created a test case [here](https://gist.github.com/stevehu/bba2cc4fea8b87086f15) to show you that version is increased to 3. Thanks.

**Comment by lukeasrodgers** [comment]
Thanks for this fix -- it appears to have helped the issue we were having as well (using HTTP API).
