### ISSUE TITLE
Smarter index rebuild policy

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2133]
if I kill the JVM, all the indexes are rebuild. But why? Can we flag the indexes updated and in case rebuild only those where have changed we're not sure are flushed? In my case I didn't changed the database, only queries.

To be sure that something is not flushed we should set flag this it is not flushed and force sync it on disk every time when something is not flushed. 

It will make all modification operations slower. Now we avoid IO bottleneck by doing all write IO in background, such force sync will put IO operations back to runtime  it should slowdown all updates which related to index.
1. Force sync flag when we are going to  have dirty index, but before any index update, do insert.
2. Flush in backgorund
3. Force sync flag that all is flushed.

Better to rebuild all of them, it is not so typical to kill db.

But with bug/huge database this is simply unacceptable: when you've a few of indexes and millions/billions of record it could takes hours!

I understand if we cannot manage it, for example in the case the index has been updated and we kill the JVM before the flush, but in all the other cases it should be smarter:
1. when index are never modified, why rebuild all the indexes?
2. when only one index is used and is dirty, after the jvm kill it should rebuild ONLY that index, not all indexes

Can we provide a callback on disk-cache? In this way each index could setup/clean dirty flag every time a page of own index is dirty and clean it once has been flushed? This would decouple the low-level Disk-Cache with index structures.

**Comment by lvca** [comment]
@laa  What's the status of this issue?

**Comment by laa** [comment]
Already fixed by forcing to rebuild it only for non tx mode
