### ISSUE TITLE
Unidirected edges

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2147]
Sometimes bi-directional edges are too expensive and mono-directional could be enough. For such reason we'd like to introduce Unidirected edges in 2.0, because all the edges now are always bi-directional. With Unidirected edge, under the hood will be identical to have a LINK (documentdb api), but at least you remain at GraphDB API level.

**Comment by kwoxer** [comment]
Hey Luca, is there a tutorial about this? Would like to use it instead of usual edges. Could you please share some Java code. Thank you.

**Comment by lvca** [comment]
This is for 2.2, so it's not present yet.
