### ISSUE TITLE
Lazy opening of multi-segment files [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#216]
This is [Issue 216](http://code.google.com/p/orient/issues/detail?id=216) moved from a Google Code project.
Added by 2011-01-31T15:40:18.000Z by [l.garu...@gmail.com](http://code.google.com/u/111607061083712272202/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, v1.4.0

### Original description

    OrientDB relies on segments. Each segments can be compound of one or multiple files. In big databases these files can be so many. This is the reason why we need to load files in lazy way.
    
    This will optimize os resources consumption and db open time.

**Comment by lvca** [comment]
Relative to the opened files.

**Comment by laa** [comment]
This issue is not valid any more, we do not have mulit segment files.
