### ISSUE TITLE
Composite index are not always used

### ISSUE THREAD

**Issue by lucab74** [orientechnologies/orientdb#2178]
I've this composite index against 2 fields:
- data_contabile
- sistema

Now, even if I execute a query with both fields as filter, only the first one is used:

``` sql
select count(*)
from DatiContabiliVLTGioco 
where ( data_contabile between 1388534400000 and 1419984000000  and  sistema = #15:9 )
```

So by looking in debug only the between uses the index, and then all the records are deserialized to get "sistema". The problem is that in this range I've 10M of record on such dates, but only 100k if the index worked! So I've 100x more reads than necessary.

**Comment by luigidellaquila** [comment]
This is was fixed in v 3.0 with the implementation of the new execution planner

Closing, thanks

Luigi
