### ISSUE TITLE
Find object by rid without use cluster id

### ISSUE THREAD

**Issue by yapro** [orientechnologies/orientdb#2205]
Hi,

How I can find object by rid without use cluster id, example:
```
SELECT FROM Language WHERE @rid = '1'
```
I pointed class name: Language

I pointed id object: 1

So, what's a problems? You can implement this feature in next release?

Details: https://groups.google.com/forum/#!topic/orient-database/lc01GwrCUhQ

Thank you.

**Comment by luigidellaquila** [comment]
Invalid: a class can have multiple clusters, so that syntax does not make sense

Closing

Thanks

Luigi
