### ISSUE TITLE
Refactor tracked collections regarding to composite reuse principle

### ISSUE THREAD

**Issue by enisher** [orientechnologies/orientdb#2208]
Our implementation of tracked collections doesn't follow the Composite Reuse Principle, and as a result contain a bunch of bugs. The bugs reveal themselves when I updated to Java 8 and implementation of putAll does not call put anymore.
The other is that methods that have been added to LinkedHashMap in Java 8 doesn't work properly anymore, because they are not overloaded in OTrackedMap. The similar issue is in the other collections.

I fixed the failing test, but I would like to rewrite collections according to CR principle. 
I don't think it may lead to negative consequences, but it is still a big change of public API.

**Comment by tglman** [comment]
Hi,

This issue is still valid in 3.0, but having the java 8 support in 3.0 we can solve this simply specializing the new method introduced in java 8 with our specialization that override the base standard library implementation.

Regards
