### ISSUE TITLE
Schema generates unwanted fields when using code coverage tools

### ISSUE THREAD

**Issue by eutheria** [orientechnologies/orientdb#2209]
Hello,

this is more of a feature request to ease the work-around i have put in for using code coverage tools.

I use cobertura to do code coverage, it seems that cobertura manipulates the byte code and adds it's own field __cobertura_counters, this is ok until you start to use inheritance in your schema.
right now I've abstracted the schema generation away and wrapped a function that will remove unwanted fields after the schema has been generated, it would be ideal if some fields could be ignored during schema creation,

maybe something like:

db.getMetadata().getSchema().generateSchema(myClass.class, new String[] {"abc"});

where the array of strings are the ignored fields.  or simply just ignore any fields with a double underscore?

**Comment by lvca** [comment]
Not relevant anymore, closing it.
