### ISSUE TITLE
Issue reading database file after crash 

### ISSUE THREAD

**Issue by thierry-github** [orientechnologies/orientdb#2214]
I'm using the last OrientDB release (orientdb-community-1.7-rc2) on windows x64, JDK 7
 After a sever crash (seems to be a network issue), the server has problem to access the database file.

Error message :

2014-04-11 11:08:20:248 SEVE Internal server error:
 java.lang.IllegalArgumentException: Cannot get allocation information for database 'geography' because it is not a disk-based database [ONetworkProtocolHttpDb]

geography is physical DB.

this situation leads to poor performances from console (6.7 second to retrieve 1000 items) while I have at the same time pretty good performances from the studio ( 0.418 s for 10 000 items)

**Comment by luigidellaquila** [comment]
Problem fixed a long time ago

Closing

Thanks

Luigi
