### ISSUE TITLE
inappropriate date conversions

### ISSUE THREAD

**Issue by underrun** [orientechnologies/orientdb#2218]
inserting data into a STRING attribute via the http batch api sometimes converts the strings to a datetime object. for instance, sometimes people create domain names that look like partial ip address ranges such as:

    10-1-1.somedomain.com

was inserted as:

    wed jan 01 00:00:00 pst 10

which is totally in appropriate. the type specification doesn't seem to have a way to force STRING types either ...

**Comment by luigidellaquila** [comment]
Hi @underrun 

This issue was fixed long time ago. I also tried to create records with that value from SQL and from batch HTTP API, always successfully.

 I'm closing this ticket, please reopen if you still see similar problems.

Thanks

Luigi
