### ISSUE TITLE
Poor password security

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#2242]
There are a number of serious issues with the way orient currently stores passwords:

1. **User passwords are stored as direct hashes**. This means:
  - I can google for a hash and often retrieve the original password.
  - I can use rainbow tables to crack common passwords extremely efficiently.
  - I can use a GPU to bruteforce password hashes with relative ease.
  - If two or more users share the same password, I recover them all at once.

  **this is very very very bad.**. At the very least we need to introduce per user salts which would defeat the easiest of the attacks, but the correct solution is to use scrypt or bcrypt here. It is possible to fix this without requiring users to change their passwords or having to wait until they next log in, see this post: http://blog.jgc.org/2012/06/one-way-to-fix-your-rubbish-password.html

2. **I can execute a query that retrieves passwords**. There are no circumstances where it actually makes sense to be able to retrieve a user's hashed password. It definitely makes no sense for an arbitrary user to be able to retrieve another user's password. Yet at the moment it's as simple as:
  ```sql
  SELECT name, password FROM OUser;
  ```
  and as far as I can tell, it's not actually possible to restrict this using the current permissions system.

  Orient currently supports a `readonly` restriction for properties, I propose we add a `writeonly` restriction too and apply it to `OUser.password`. Such properties should never be returned from queries or record load commands.

3. **System passwords are stored in plaintext**. While Orient generates a strong random root password on first build, it's stored as plain text in orient's configuration file. If I can find a way to read the configuration file, I can access every record in the system, even if I have no further access. The solution is to generate a strong password on first build, present it to the user for them to remember, and store the **strong** hash (bcrypt, scrypt) in the config file. So now even if I can read the config file, I can't use the credentials to actually login to the database.

**Comment by hho** [comment]
This is security-relevant and has now been open for more than a year… :worried:

**Comment by lvca** [comment]
Part 3) has been fixed in #2811.

**Comment by lvca** [comment]
Part 1) has been implemented: #1229

**Comment by lvca** [comment]
Part 2) has ben fixed by allowing only to "admin" the permission to access to OUser and ORole clusters.
