### ISSUE TITLE
delete vertex should accepts a sub query

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2254]
There are cases when it's faster to delete vertices crossing relationships. Example:

```
delete vertex Work where out('status') contains (work-state = 'Not Started')
```

Could become this (assuming the status vertex is called "State"):

```
delete vertex from (select in('status') from State where work-state = 'Not Started')
```

Look also at: http://stackoverflow.com/questions/23156580/mass-group-delete-orientdb-java

**Comment by martingg88** [comment]
The following query is not longer work for version 2.1-rc5

DELETE VERTEX FROM (SELECT EXPAND(OUT("target")) FROM #45:4)
