### ISSUE TITLE
Query Embedded type is very slow for large dataset

### ISSUE THREAD

**Issue by egyMaak** [orientechnologies/orientdb#2256]
I have an "Article" class that contains 10.15M vertices. The URI property is a embedded map of String type. running the following query from studio:

```
select from Article where URI[en] = 'anyword'
```

whatever the index being used, I get the following: 

```
Query executed in 269.804 sec. Returned 1 record(s)
Query executed in 315.438 sec. Returned 1 record(s)
```

It takes around 4.5  minutes to retrieve single record !

**Comment by laa** [comment]
Hi we do not support usage of  indexes in braces, we have already discussed this once.
Bottom line is that design of SQL engine is not ready for this, but may be it is already changed.
Assign to @luigidellaquila . 

You may use contains and containsKey .
