### ISSUE TITLE
FETCHPLAN - Option to avoid cyclic reference check

### ISSUE THREAD

**Issue by gauravdhiman** [orientechnologies/orientdb#2259]
Currently fetchplan do check for cyclic reference, which is required to avoid infinite loop, but in few case (as given below), this check need to be avoided.

Lets say the class (A) have links createByUser, modifiedByUser and allUsers pointing to same record (#10:3) of OUser class.

If we specify FETCHPLAN ("*:-1") to fetch deep level records, only one link is expanded (allUsers), rest other two (createByUser, modifiedByUser) are not expanded. The reason for this is that all three link points to same OUser record (same @rid).

Query:
SELECT FROM A FETCHPLAN *:-1

In this case if we want to expand all Links (createByUser, modifiedByUser and allUsers), we must have some mechanism to avoid cyclic reference check.

Suggestion:
It can be done in two ways:
1. Do not check for cyclic reference check if FETCHPLAN does not mention infinite depth (-1)
2. An option can be added in FETCHPLAN to explicitly avoid cyclic reference check.

Reference link:
https://groups.google.com/forum/?hl=en#!topic/orient-database/KWF1qYr2yNk

Regards,
Gaurav

**Comment by lvca** [comment]
Not relevant anymore. Closing it. Fetchplans are deprecated in 3.0 in favor of sql extended projections.
