### ISSUE TITLE
query all values of  embedded map type

### ISSUE THREAD

**Issue by egyMaak** [orientechnologies/orientdb#2260]
I create Party class that has Contact property as EMBEDDEDMAP of String as follow:

```
CREATE class Party extends V
CREATE property Party.contact EMBEDDEDMAP STRING

insert into Party (contact) values ({"mobile":"123", "home":"456" })
```

I can lookup for certain contact using this query - from the studio: 
`select from Party where contact[mobile] = "123"`

But the following query did not return results in same time it not raise error
`select from Party where contact = "123"`

I expect that query should search for all records in the map what the Key, or i suggest supporting this syntax `contact[_]`:

`select from Party where contact[_] = "123"`

N.E: I know that we can use the following query 

```
select * from Party where contact containsvalue = "123"
```

**Comment by luigidellaquila** [comment]
This issue is definitely invalid, the CONTAINSVALUE syntax is intended exactly for this, there is no need for an additional syntax

Thanks

Luigi
