### ISSUE TITLE
Truncate vertex class not delete dangled Edges

### ISSUE THREAD

**Issue by egyMaak** [orientechnologies/orientdb#2280]
I create a ```Person``` vertex class and populate the DB with data then i create internal relations "edges" between persons. 
When I ```truncate class person``` ALL internal edges become dangled and i have remove them manually. 

I suggest support cascading in case of truncating or deleting a class to remove dangled edges.

**Comment by lvca** [comment]
In v2.1 we introduced a check on this. To still bypass the check use UNSAFE keyword.
