### ISSUE TITLE
Embedded property : case insensitive collate not working

### ISSUE THREAD

**Issue by thierry-github** [orientechnologies/orientdb#2289]
Working on 1.7 rc2 release on windows x64 computer.

I have a first class named MyClass with a string property named  Title. the Collate attribute is set to "Case insensitive".

I have a second class named MySecondClass with an embedded property named  P (of MyClass type)

I have a MyClass record with the Title set to "MyValue".

The following search fails :
 - select from MySecondClass where P.Title = "myvalue"
this one works :
 - select from MySecondClass where P.Title  = "MyValue"

**Comment by lvca** [comment]
@thierry-github It's fixed in 2.0.1
