### ISSUE TITLE
Customer 39 - Test nashorn's 'loadWithNewGlobal' to avoid creating new instances of ScriptEngine on every request

### ISSUE THREAD

**Issue by mattaylor** [orientechnologies/orientdb#2294]
Currently the javascript scriptEngine needs to be reinstatiated on every request to avoid multi threading issues. 

Although the new java 1.8 javascript engine is not threadsafe, it does introduce some more controls to support multi threaded execution environments. In particular the use of shared 'global' contexts can be avoided if scripts are invoked via the 'loadWithNewGlobal' command. If the DB object is then locally assigned to this script engine, this should eliminate multithreading concerns without the overhead of creating new engines on every request.

see: https://blogs.oracle.com/nashorn/entry/nashorn_multi_threading_and_mt

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
