### ISSUE TITLE
Hot change of distributed configuration

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2305]
In Community Edition via command line (console) and in visual way in the Workbench of the Enterprise Edition (commercial licensed).

**Comment by iafilatov** [comment]
Could you please share your plans regarding this feature? Do the most recent label changes mean that when done, it will only be available in Enterprise?

**Comment by pires** [comment]
This can be achieved with `hazelcast` for in-memory configuration or with `confd` + distributable keystore for file-based configuration.

**Comment by lvca** [comment]
This is already available for EE.
