### ISSUE TITLE
single GROUP BY ignores null values

### ISSUE THREAD

**Issue by fabriziofortino** [orientechnologies/orientdb#2312]
I have a class that looks like this

CODE | PRIORITY
---------|--------------
0001 | HIGH
0001 | LOW
0001 | LOW
0002 | HIGH
null | HIGH

Executing the following query

```sql
select CODE, count(*) as count group by (CODE)
```
I get

CODE|count
--------|-------
0001|3
0002|1

Executing a multi group by select
```sql
select CODE, PRIORITY, count(*) as count group by (CODE, PRIORITY)
```
I get

CODE|PRIORITY|count
--------|-------------|--------
0001|HIGH|1
0001|LOW|2
0002|HIGH|1
null|HIGH|1

In my opinion, the first query should return a result for the null group

CODE|count
--------|-------
0001|3
0002|1
null|1

**Comment by johnmelba** [comment]
I assume this is still an open issue, not fixed it?. Is there a work around ? say syntax like this --  group by (CODE, somethingdummy)
