### ISSUE TITLE
Prepare APT and RPM packages

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#2314]
It would be very nice if it was as easy to install OrientDB as it is MySQL, or Nginx etc. On debian/ubuntu I should be able to:

```
apt-get install orientdb
```

and the yum equivalent on RHEL/Centos.

Elasticsearch [already offers this](http://www.elasticsearch.org/blog/apt-and-yum-repositories/), perhaps we can reuse their package structures?

**Comment by dblaber** [comment]
Is anyone all ready working on a debian package? If not, I can make one and get it into debian/debian derived distros

**Comment by lvca** [comment]
@dblaber It would be amazing!

**Comment by tglman** [comment]
yep, @dblaber you have all our support, feel free to ask any question, and i can point you to some already done work.

**Comment by RichAyotte** [comment]
@dblaber :+1:

**Comment by Koc** [comment]
@dblaber @tglman is there any news on this issue?

**Comment by smolinari** [comment]
I'd also welcome it too. :+1: 

Scott

**Comment by tglman** [comment]
Hi All,

Not yet done, not sure when will be :(

**Comment by gzliudan** [comment]
I want a RPM package which runs on CENTOS 7.X
