### ISSUE TITLE
OSerializationException when uploading binary data

### ISSUE THREAD

**Issue by krichter722** [orientechnologies/orientdb#2336]
In the studio frontend of 1.7-rc2 I'm experiencing the following exception 

`"com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content for record #15:0\r\n--> com.orientechnologies.common.io.OIOException: Bad Base64 input character decimal 36 in array position 0"`

when I want to upload a pdf file or the base64 encoded version of that pdf (in a plain text file) into a BINARY field and save the record. The result is that the record changes are not saved. The issue is unrelated to other class fields. The types table in the wiki (https://github.com/orientechnologies/orientdb/wiki/Types) states that the binary field should work with "base64 encoded binary" (I'm using the linux base64 command of GNU coreutils 8.21).

**Comment by beebase** [comment]
Is there a code snippet somewhere that shows how to upload images through rest api ?

**Comment by Silur** [comment]
still getting this error, it's 2016 already please do something

**Comment by maggiolo00** [comment]
hi @Silur 
i know we will target this in 3.0

**Comment by krichter722** [comment]
I don't find the location where labels are documented. I don't understand intuitively which reply you're waiting on.

**Comment by krichter722** [comment]
The studio shipped with 2.2.22 tarball causes a `BINARY` field to be set to null after a file for upload is selected and the new record saved.

Since this is an issue for 3 years now, I suggest to at least provide a helpful error message because the initial `OSerializationException` doesn't reveal that storing binary data through the studio isn't supported and setting the field to `null` and displaying a green JSON representation of the object (assiociated with success) is extremely misleading.

**Comment by maggiolo00** [comment]
Hi @krichter722 

Since uploading binary is not supported i suggest to add a warning and do not allow the operation. WDYT?

**Comment by krichter722** [comment]
> Since uploading binary is not supported i suggest to add a warning and do not allow the operation. WDYT?

Agreed. That's what I meant.
