### ISSUE TITLE
(Customer ID 39) - traversal on multiple conditions and 'like' operations return zero results.

### ISSUE THREAD

**Issue by enisher** [orientechnologies/orientdb#2338]
I have a 'stats' class with links to 'user' and 'metric' classes as follows..

```
create property stats.user link user
create property stats.metric link metric
create propery stats.time datetime

create index stats.user NOTUNIQUE
create index stats.metric NOTUNIQUE
create index stats.unique on stats (user, metric, time) UNIQUE
```

When we add some test data and run the following queries - all works as expected. 

```
select user, user.name, metric, metric.name  from stats  where  user.name =  'subject1$study3$test'
select user, user.name, metric, metric.name  from stats  where  user=#11:25487 and metric = #14:40
```

```
@rid    @version    user    user2   metric  metric2
#-2:1   0   #11:25487   subject1$study3$test    #14:40  stepCount
#-2:2   0   #11:25487   subject1$study3$test    #14:40  stepCount
```

However when we try to combine two or more conditions that traverse projections which should return the same results as above we now get zero results....

```
select user, user.name, metric, metric.name  from stats  where  user=#11:25487 and metric.name = 'stepCount'
select user, user.name, metric, metric.name  from stats  where  user.name like '%study3$test'
select user, user.name, metric, metric.name  from stats  where  user.name  =  'subject1$study3$test' and metric = #14:40
```

I have tried removing all the indexes but it makes no difference. 

These queries were all working fine up untill the builds from late last week. 
We have not tried with any new builds since friday as we are waiting for confirmation that the exclusive locking issues on users have been resolved and verified. 

This could be related to #2332

**Comment by luigidellaquila** [comment]
This issue is mainly related to indexes.
Renaming a class and creating another one with the same name does not create any problems as long as there are no indexes involved.

On the other hand, if an index is defined on the first class, after the rename/create, the index does not follow the original class.


How to reproduce:

create class A

create property A.a String

create index A.a on A (a) NOTUNIQUE

insert into A (a) values ('foo')

alter class A name B

create class A

select from B where name = 'foo'

**Comment by luigidellaquila** [comment]
Class rename should also rename/move indexes to the new class.
At this stage there is no such API/functionality for indexes, so I'm adding a check on class rename that inhibits class renaming when indexes are present (to preserve consistency). It will be always possible to rename classes using UNSAFE keyword.

Moving the issue to 2.2 for complete fix
