### ISSUE TITLE
Embedding via maven, why use bundles?

### ISSUE THREAD

**Issue by asaf** [orientechnologies/orientdb#2339]
Hey,

According to:
https://github.com/orientechnologies/orientdb/wiki/Download

It seems like the default configuration is to use OSGI bundles,
OSGI is not so adapted and bundles may cause configuration errors in standard archives,

Is there a reason why you guys suggest using bundles ?

(I use the same configs but without the 'bundle' dependency type and everything work just fine),

Thanks.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
