### ISSUE TITLE
Support using JS function in "ORDER BY" statement

### ISSUE THREAD

**Issue by tdhung80** [orientechnologies/orientdb#2352]
Hi,

We could use JS function in SELECT and WHERE, but it won't work in ORDER BY. It should be working, so that developer could use a formula in ORDER BY.

Reference: https://groups.google.com/forum/#!topic/orient-database/xEwQWI1lzfE

I have tested on OrientDB v1.6.0

My Best,
Hung Tran

**Comment by luigidellaquila** [comment]
It was fixed in v 3.0 with the new SQL executor

Closing, thanks

Luigi
