### ISSUE TITLE
obinaryconverterfactory + ocomparatorfactory do not use Oglobalconfiguration

### ISSUE THREAD

**Issue by zerovian** [orientechnologies/orientdb#2359]
orientdb 1.6.4

OBinaryConverterFactory and OComparatorFactory classes do not use OGlobalConfiguration.MEMORY_USE_UNSAFE.  Instead they go directly to system properties.  This causes a problem if you try to set this property through OGlobalConfiguration in java code instead of as a system property.  This property is ignored and can result in crashes on solaris64, hpux (ia64), and aix64 where unsafe memory access isn't aligned properly for plocal.

These classes should use oglobalconfiguration so this can be configured correctly and in one location through java code instead of setting system properties.

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
