### ISSUE TITLE
Support JSON Payload to set Javascript Server-side Parameters 

### ISSUE THREAD

**Issue by tommykennedy** [orientechnologies/orientdb#2363]
It would be nice to have the HTTP command interface to support the setting of variables by using a JSON pay load. 

http://admin:admin@localhost:2480/function/demo/insertData

insertData is a server side javascript function which takes two parameters "a" and "b"

Set the payload {"a":5,"b":10}

Then once we have set the post vars. The server side will unmarshal the content into Objects.

**Comment by patrickhoeffel** [comment]
I would like to +1 this request. This would be extremely helpful in the system we are currently building.

**Comment by lvca** [comment]
Already implemented in OrientDB 2.2
