### ISSUE TITLE
SQL Scripts do not work over RESTful interface

### ISSUE THREAD

**Issue by Barth** [orientechnologies/orientdb#2365]
A transaction like:

{ "transaction" : true, 
  "operations" : [ 
    {
      "type" : "script",
      "language" : "sql",
      "script" : [ "insert into user (username,age) values ('user21',34)",
					"insert into user (username,age) values ('user22',54)"]
    }
  ]
}

Produces: 
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.insert into user (username,age) values ('user21',34)
insert into user (username,age) values ('user22',54)

Tested with server and client running on Windows.

**Comment by matanshukry** [comment]
Might be a bug that's fixed, but as far as I can tell this is working.

I used server on windows and CURL as client.
running the following:

```
curl http://localhost:2481/batch/test -u root:root -d '{ "transaction": true, "operations": [ { "type": "script", "language": "sql", "script": [ "insert into user (id, name) values (2, Matan)", "insert into user (id, name) values (3, Joe)" ] } ] }'
```

Inserted two users.
This seems a bit old, I suggest we give it another week and close it if there is no response.

p.s.
If anyone noticed, the string values (matan and joe) aren't quotes, and won't work. I had a bit of trouble with escaping and windows. But that's irrelevant, the command it self work, and if escaped and executed correctly, the values are working.

**Comment by lvca** [comment]
Closing because no response.
