### ISSUE TITLE
@OCluster and @OCluss annotations support

### ISSUE THREAD

**Issue by trainings** [orientechnologies/orientdb#2371]
I propose to add support for @OCluster and @OClass annotations for domain entity.
As well as use of annotations OId and OVersion.
In the field marked as @OCluster will be set the cluster name,
In the field marked as @OClass will be set the class name,

For example:
class Customer {
  @OId
  String rid

  @OCluster
  String cluster;

  @OClass
  String clazz;
}

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
