### ISSUE TITLE
SQL : Better wildcard support in projections

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#2372]
Wildcard "*" support in projections is currently limited.  For example, the following does not work:
```
select in_knows.name, * from V
```
Currently (1.7-SNAPSHOT) this is interpreted as:
```
select * from V
```

This makes it hard to efficiently get all of the properties from each record without knowing their names (i.e. each record may have different properties).

**Comment by lvca** [comment]
Now it supports more flexible usage like:

```sql
select *, $l.* as leases, $u.* as uses, $p.* as photocopiesWith, $locks.* as locksIn
  from Teacher
    let $l = out('Leases')[0],
        $u = out('Uses')[0],
        $p = out('PhotocopiesWith')[0],
        $locks = out('LocksIn')[0]
```

**Comment by Bretto** [comment]
How come this is not working for me ? orientdb-community-2.1-rc2
```
select *, $o.* as Own from Item 
let $o = in('Own')[0]
```
I get :

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " "." ". "" at line 1, column 13. Was expecting one of: <EOF> <TIMEOUT> ... <AS> ... <FETCHPLAN> ... <LOCK> ... <LET> ... <NOCACHE> ... <PARALLEL> ... ";" ... "," ... <AS> ... "," ...

**Comment by luigidellaquila** [comment]
reopening for a quick fix
