### ISSUE TITLE
(customer 39) select distinct() depends on limits

### ISSUE THREAD

**Issue by mattaylor** [orientechnologies/orientdb#2376]
Using distinct in a projection will only itermate over the current limited results cursor, rather than the whole query result set. 

Not sure this is bug, but it is certainly undocumented and very misleading. 

Given 100 distinct keys distributed evenly over 1000 instances of `myClass` and a default query limit of 20 ..

```
<< select distinct(key) from myClass
>> returns 2 keys
```

However..

```
<< select distinct(key) from myClass limit -1
>> returns 100 records
```

**Comment by AaronSchulz** [comment]
GROUP BY (at least in some cases) is applying LIMIT before the grouping. I file separate issue for that.

**Comment by thiagopm** [comment]
Hi @lvca,

We are having the same problem, we need to list first 5 distinct Users of Feed class.

First we tried the SQL tradicional way:
select DISTINCT(UserId) from Feed Where UserName LUCENE 'Mar*'  LIMIT 5
or
select UserId from Feed Where UserName like 'Mar*'  LIMIT 5

It is fast, but as limit is been applied before distinct we were getting only 3 registers.

Then after we found this post we tried to use group by:
select UserId from Feed Where UserName LUCENE 'Mar*' GROUP BY UserId  LIMIT 5

But it's taking 33 seconds...

Do you have a suggestion to solve it?

thanks

**Comment by luigidellaquila** [comment]
Hi guys

IMHO this is definitely a bug.
@thiagopm the only thing you can try here is a subquery, eg.

```sql
select from (
select DISTINCT(UserId) from Feed Where UserName LUCENE 'Mar' 
) LIMIT 5
```

but I'm not sure it will give you better results. 
As an additional optimization, you can add a wider limit to the inner query, but it doesn't guarantee the result. Eg if you are sure that in the first 100 records there will be 5 distinct user ids, you can try

```sql
select from (
select DISTINCT(UserId) from Feed Where UserName LUCENE 'Mar'  limit 100
) LIMIT 5
```

**Comment by luigidellaquila** [comment]
AFAIK it was fixed long time ago. I just tried it in v 2.2.24 and it seems to work fine

I'm closing this issue

Thanks

Luigi

**Comment by luigidellaquila** [comment]
AFAIK it was fixed long time ago. I just tried it in v 2.2.24 and it seems to work fine

I'm closing this issue

Thanks

Luigi
