### ISSUE TITLE
Map multiple Java bean classes over the same Orient db class

### ISSUE THREAD

**Issue by ivanocortesini** [orientechnologies/orientdb#2395]
This is to propose an enhancement about the use of Object mapping facilities available in Orient database. By using OObjectDatabaseTx connection I can create select queries mapping the resulting documents to a specified pre-registered entity class. I propose to auto register the class passed to the query if it isn't yet. Again it'll be useful to have the possibility to map the same database entity to different bean classes. By applying this enhancement to Orient db, it'll be extremely simple to implement a crud rest service layer with the json output controlled by simple bean templates. In few words, by it I can pass to the Jackson library the same proxy beans returned by Orient with the specific output configuration I need.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
