### ISSUE TITLE
OSQLFunctionShortestPath uses inefficient algorithm

### ISSUE THREAD

**Issue by enisher** [orientechnologies/orientdb#2398]
`OSQLFunctionShortestPath` uses the same Dijkstra algorithm where all weights of edges equal to 1.
This function could be implemented with breadth-first search algorithm.

- Complexity of __Dijkstra algorithm__ is `O(|E| + |V|*log|V|)`
- Complexity of __Breadth-first search__ is `O(|E| + |V|)`. Moreover far not all vertices will be explored in average.

That might be much more efficient in a big data sets.

We can reuse `OTraverse` for that.

**Comment by luigidellaquila** [comment]
v. 2.2 includes `astar()` implementation, that is more flexible and allows optimizations based on heuristics.
I'm closing this issue

Thanks

Luigi
