### ISSUE TITLE
Cannot create a JS function in Console

### ISSUE THREAD

**Issue by tdhung80** [orientechnologies/orientdb#2415]
Hi,

I cannot create a JS Function in Console based on OrientDB syntax, it does not work properly. I am using OrientDB v1.7
## Syntax

CREATE FUNCTION &lt;name&gt; &lt;code&gt; [PARAMETERS [&lt;comma-separated list of parameters' name&gt;]] [IDEMPOTENT true|false] [LANGUAGE &lt;language&gt;]
## Example

orientdb {test}> create function sum "return a + b" PARAMETERS [a,b] IDEMPOTENT true LANGUAGE Javascript
## Result

It created a SQL function without parameter instead of a JS function with (a,b) parameters

Reference: https://groups.google.com/forum/#!topic/orient-database/stezHWiuQ5M

My Best,
Hung Tran

**Comment by jetheurer** [comment]
I am having trouble with the `CREATE FUNCTION`.  In particular, when I am writing and OSQL statement inside Javascript inside the OSQL `CREATE FUNCTION` like

```
CREATE FUNCTION basic_traverse '''edge_type = edge_type.replace(',','","'); var sql = 'TRAVERSE direction("edge_type") FROM (SELECT FROM V WHERE key  = "value")';sql = sql.replace('key',key).replace('value',value).replace('edge_type',edge_type).replace('direction',direction); return  orient.getDatabase().query(sql)''' PARAMETERS edge_type, key, value, direction LANGUAGE Javascript;
```

I get a syntax error which may be from my use of double and single quotes.  

```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Syntax Error. Missing function parameter(s): CREATE FUNCTION <name> <code> [PARAMETERS [<comma-separated list of parameters' name>]] [IDEMPOTENT true|false] [LANGUAGE <language>]
```

Any suggestions are welcome

**Comment by jetheurer** [comment]
Update: 
```
CREATE FUNCTION basic_traverse "var sql = 'TRAVERSE direction(\'edge_type\') FROM (SELECT FROM V WHERE key  = \'value\')'; sql = sql.replace('key',key).replace('value',value).replace('edge_type',edge_type).replace('direction',direction);  return  orient.getDatabase().query(sql)" PARAMETERS [edge_type, key, value, direction] LANGUAGE javascript;
```
is almost working.  I'm just not sure how to make sure the `\` passes through to the orientdb
