### ISSUE TITLE
Allow surrounding property names with backtics (`) when property names contain 'strange' characters (or start with $)

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#2423]
Properties starting with $ can be added to the dabase using 
<code>insert into MyClass content { "$$mystrangeproperty": 5 }

But it is impossible currently to do
<code>select $$mystrangeproperty as strangeprop from MyClass

because $ is reserved for LET variables

Some RDMS's use backtics for property names with spaces and other strange characters, so maybe it would be an option to support this too, such that I can query these properties without problems.

You would get (replaced by single quotes ' because github does funny things with backtics)
<code>select '$$mystrangeproperty' as strangeprop from MyClass

**Comment by luigidellaquila** [comment]
in 2.1 it's supported only for reserved keywords (eg. SELECT, FROM, WHERE).
Moving forward for complete support

**Comment by luigidellaquila** [comment]
V 2.2 has full support for this

Closing

Thanks

Luigi
