### ISSUE TITLE
Escaping backslashes and newlines in strings has problems

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#2424]
The whole explanation can be found in this thread:
https://groups.google.com/forum/#!topic/orient-database/znZhid64EjU

Trying to store newlines in a property, I tried things like

<code>UPDATE MyClass set mytext = 'Hello\nWorld'</code>
and
<code>UPDATE MyClass set mytext = "Hello\nWorld"</code>
but no luck.
<code>insert into MyClass content { key: 1, mytext: "Hello\nWorld" }</code>
does work as expected...

Then I thought I found a workaround using the MERGE command
<code>update V merge { "value2": "Hello\nWorld! Backslash = \\ " } where key = "x"</code>

BUT there are other strange issues with escaped BACKSLASHES!
The following FAILS with java.lang.IllegalStateException: `Missing closed string character: '"', position: 75`
<code>update V merge { "value2": "Backslash = \\" } where key = "x"</code>
while this seems to work (added a space character at the very end)
<code>update V merge { "value2": "Backslash = \\ " } where key = "x"</code>

but when I want to update a javascript function, I have to escape each backslash twice !!!

The following will _not_ behave as expected
<code>update OFunction merge { code : "// \\/\\/" } where name = 'testBackslashInComment'</code>

A select query on the database will return
<code>"code": "// //"</code>
instead of the expected
<code>"code": "// \\/\\/"</code>

But the following query
<code>update OFunction merge { code : "// \\\\/\\\\/" } where name = 'testBackslashInComment'</code>
will produce 
<code>"code": "// \\/\\/"</code>

But using SET instead of MERGE, we get:
<code>update OFunction set code = "// \\/\\/" where name = 'testBackslashInComment'</code>
we get the expected 
<code>"code": "// \\/\\/"</code>

(but then we are back to the \n not working...)

**Comment by stanonyime** [comment]
I'm still experiencing this problem in a different form. All my latex equations are stripped of backslashes. Example: "\frac{2}{3}" is stripped to "rac{2}{3}". The worst thing is that I have little control over the data source

**Comment by omgold** [comment]
I also have trouble escaping. I can't find a clear definition of how it is supposed to work. Can someone give me list of characters that need to be escaped inside a single-quoted string in an SQL-query and how to escape them?

**Comment by ErikShiken** [comment]
This is still an issue. It should not be closed

**Comment by futureglorydev** [comment]
This comment helped me
https://github.com/orientechnologies/orientdb/issues/5469#issuecomment-164777360
