### ISSUE TITLE
Query cursor (not iterator)

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#2425]
Some of queries results are huge and lead to OOM. 
To solve this problem we should split queries on 2 types:
1.  Require processing of whole fetched data (we have 3 cases in current query processing engine implementation: order by, distinct and group by).
2. Do not require processing of whole fetched data.

First query type is addressed by https://github.com/orientechnologies/orientdb/issues/2022 but second query type is much more popular, to avoid OOM during processing of second query type we should use cursors. We already have index cursor so what we only need is cluster cursor which will allow as to create query cursor, send it to the client and work with queries  results as it is done in JDBC result set, which allows to handle chunks of data on demand. 

What I mean.
Lets say we have query like "select from HugeClass" currently we fetch all data to the server memory and then send results to the client. This can lead to OOM. 

As alternative approach  we propose to use asynchronous query which as result can lead to OOM on client side, also not all clients are ably to use asynchronous queries.

So proposed solution is to create cursor on client side and perform filtering of data on demand  by batches of let say 100 of records (should be configurable on query instance level), usually it more than enough as for process ruining in background for processing of huge data and as for process requires immediate response on user request (no human being usually look at such amount of data at once).

As result we will get following advantages:
1. Implicit pagination which will increase query processing performance for 80% of cases.
2. OOM problems will be fixed.

**Comment by luigidellaquila** [comment]
Already implemented in develop branch (next v 3.0)
