### ISSUE TITLE
Remove server dependencies from graphdb module

### ISSUE THREAD

**Issue by enisher** [orientechnologies/orientdb#2433]
**orientdb-graphdb** depends on too many unnecessary things like:
- tools
- server
- enterprise
- object
  That is not really convenient, because if the only thing that I need is a graph client I have a bunch of redundunt jars in classpath.

Our server is not used without graph anymore so we can move graph console to tools and graph commands/functions to server.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
