### ISSUE TITLE
(early) tinkerpop3 support

### ISSUE THREAD

**Issue by sslavic** [orientechnologies/orientdb#2441]
Tinkerpop3 3.0.0-SNAPSHOT version artifacts can be found on [Sonatype OSS snapshots repostory](https://oss.sonatype.org/content/repositories/snapshots/com/tinkerpop/tinkerpop3/) and documentation on [tinkerpop website](http://www.tinkerpop.com/docs/tinkerpop3/3.0.0-SNAPSHOT/).

**Comment by lvca** [comment]
Hey, 
Michael Pollmeier already started it! https://github.com/mpollmeier/orientdb-gremlin. Any volunteer to help him on this?

**Comment by omidb** [comment]
Any update on Tinkerpop3 ?

**Comment by pabloa** [comment]
+1

**Comment by lodrion** [comment]
+1

**Comment by Jotschi** [comment]
I completely missed https://github.com/mpollmeier/orientdb-gremlin - Looks really good. 
The project contains TP3 "compliant" classes for OrientGraph etc.

I have just added a PR that adds transaction handling support to the project.

@lvca Maybe you or some other dev could perhaps take a few minutes to clarify some points that i mentioned in https://github.com/mpollmeier/orientdb-gremlin/issues/16

I wrote my own OrientDB 2.1.x TP3 wrapper before i even noticed that orientdb-gremlin exists.
https://github.com/Jotschi/orientdb2-tinkerpop3-wrapper (It is very basic and should also not be used in production) 
It may be helpful for someone that wants to tinker with TP3 and prepare for a potential project migration from TP 2.4.x to TP 3.

**Comment by lvca** [comment]
@Jotschi WDYT about merging your project with orientdb-gremlin?

**Comment by Jotschi** [comment]
@lvca I have already added the transaction code or at least the things i learned from my project to orientdb-gremlin (via pending PR). I have already linked orientdb-gremlin within my README.md file. I'll delete or clear my project once i'm happy with the state of orientdb-gremlin. 

**I suggest that people that read this check out orientdb-gremlin first and contribute to that project.**

**Comment by basdek** [comment]
+1

**Comment by velo** [comment]
FWIW github.com/mpollmeier/orientdb-gremlin

We run the same compatibility suite that other gremlin drivers do, so, orientdb support should be in really good shape.

**Comment by joan38** [comment]
+1

**Comment by TarmoKalling** [comment]
When can we hope for official TinkerPop3-OrientDB implementation?

**Comment by lvca** [comment]
Supported as an external plugin for OrientDB v2.2.x and in bundle with OrientDB v3.0.
