### ISSUE TITLE
mismatch size number:  out('A').out('B')   and out('A').out('B').size()

### ISSUE THREAD

**Issue by oliveagle** [orientechnologies/orientdb#2448]
all data with the same schema , index and turned lightweightededge off.  
`size()` function is using a different mechanism ?

![qq20140606-3](https://cloud.githubusercontent.com/assets/2270205/3213025/79dc7130-ef7e-11e3-8946-e62794235ffe.png)

**Comment by luigidellaquila** [comment]
Old issue, is it still valid?
Is there a way to reproduce it?

Thanks

Luigi

**Comment by lvca** [comment]
No answer after long time. In case please reopen/comment this issue.
