### ISSUE TITLE
 perfomance problem (about factor 100 times) [ indexing problem ]

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#2462]
orientdb 1.7.2
----------------------------------------ORIENTDB------------------------------------------
i executed this code using console.
<pre>
jss for(i=0;i &lt;5313845;i++) 
db.command('insert into a1 set a = '+i);
</pre>
time for create 371,466003 sec
<pre>
select from a1 where a = 1
</pre>
time for find 87.825 sec(s).
<pre>
select from a1 where a = 5000000
</pre>
time for find 77.623;

----------------------------------------------------------------------------------------------
------------------------------------------POSTGRES----------------------------------------
then 
i executed in postgres this code
<pre>
CREATE FUNCTION somefunc2() RETURNS integer AS $$
<< outerblock >>
BEGIN
    FOR i IN 1..5313845 LOOP
    insert into aa values(i);
END LOOP;  
  
    RETURN 0;
END;
$$ LANGUAGE plpgsql;
</pre>

<pre>select somefunc2();
</pre>
time for create 52.9 sec
<pre>SELECT a from aa where a = 1 
</pre>
time for find 0.9 sec
</pre>
<pre>select a from aa where a = 5000000;
</pre>
time for find 0.9 sec
<pre>delete from aa </pre>
time for delete 27.021 sec

 Tryng ... with indexes ... on multiple properties .... if all cases are handled ..
<pre>
-------------------------------+-------------+-------------------------------+-----------+----------+----------+-----------+-----------+----------+
 NAME                          | TYPE        | LINKED TYPE/CLASS             | MANDATORY | READONLY | NOT NULL |    MIN    |    MAX    | COLLATE  |
-------------------------------+-------------+-------------------------------+-----------+----------+----------+-----------+-----------+----------+
 c                             | STRING      | null                          | false     | false    | false    |           |           | default  |
 b                             | INTEGER     | null                          | false     | false    | false    |           |           | default  |
 d                             | DOUBLE      | null                          | false     | false    | false    |           |           | default  |
 a                             | INTEGER     | null                          | false     | false    | false    |           |           | default  |
-------------------------------+-------------+-------------------------------+-----------+----------+----------+-----------+-----------+----------+
Indexes (1 altogether):
-------------------------------+----------------+
 NAME                          | PROPERTIES     |
-------------------------------+----------------+
 ind                           | a (+)          |
                               | b (+)          |
                               | c (+)          |
                               | d              |
-------------------------------+----------------+
</pre>
THIS TIME CLASS CONTAINS 1.000.000 ELEMENTS
BEFORE INDEX
<pre>select from a1 where a = 100 and b = 101 and c = '100'
</pre> 
1 item(s) found. Query executed in 2.085 sec(s).
AFTER INDEX 
 0.007 sec
 1) <pre>select from a1 where a= 100</pre> , 0.003   OK 
 2) <pre>select from a1 where a= 100  or a = 101</pre> , 18 sec   (dont use index? )
all the other more complex query give response in about 20-23 secs .

Using posgres 
all query response in 0.3 secs
also more complex query  ( select * from aa where  ( a = 100 or a = 101 ) and d = '101'  )

The conclusion is the time response of orientdb is about 100 slower of sql server. 
and index help just in a simplified/minimal set of cases.
Considering the most application make use not so simplified query and the acceptable response time is about 1-2 secs ... it is possible to use just class with less then 100.000 elements.
The is also significant perfomance tuning ? A possible way for making faster orientdb could be convert it in native code? other solutions? 
Now, I gave a look also to wiki for indexes for understanding ...: i m not expert in indexes but it seams (seeing the behaviour, i dont see code) you use essentialy a map for indexing without  to build the clusters(indexing set) for   executing ,then, the operations on these sets, and you use as set directlly a map.  In this way is not possible to create a fast path for complex query because it can t to think about the relationship among  keys(values) with query operators. In fact , when i used operators > ,< >= <= indexes seams be skipped ( seeing the long time response). 
The interface have essentially get,put but for my opinion is not sufficient for a complete indexing. You might have :  put that could be ok (if i can retrive info about metadata type fastly) , get might be a kind of <Identifiable,execution_instance> get (key,operator_type,value,execution_instance): for example get('a1.a',>,10,instance) that can return element with property a1.a > 10. Instance it is usefull if you return data using cursor.
Pratically you can have a indexer for every couple (property,operator).There also a functionfor know if a rid is related to a specific couple(property,operator). You have also a stack for understand in the query waht is the first index to recall in the query in a logic bottom up of Expression Tree. You can  translate logic operators in set operators: you can skip  internally to call indexer after a 'or' condition if first condition is already true. Pratically you verify the expression for every row detected by indexers.In fact, when a indexer find a row for a condition , the rest of the expression have just to verify that the other indexers (for every sub condition in the expression) have this row ( if  no index exists, verify the condition on the row). In this way you have a scalable solution cause it reads a row for every step and is flexible : it permits to use also a mix , a indexer for a part of expression and no index for another part of query. In addition it works for for all query and the structure of the query expression is indipendent from the index definition. You define a index just for a property for for multiple properties , because the combination of properties in a query expression is infinite.   
 Another problem that i see is now get return a set of all the row id having that property. You image you have a class with a property valued with the same value for millions of rows. This set could have too much data ... it seams this set not a scalable solution. 
Instead if you use a cursor you can return a  rid for each fetch to pass to the client.    
Then i passed to test lucene  plugin
it seams have response time very fast also for query complex, so in general the query management in the indexer seams to be handled but there is another problem now 
<pre>
orientdb {GratefulDeadConcerts}> select * from a1 where [ a , b ] LUCENE " a = 100 and b = 103  "  

----+----------+----+----+----+-------
     |@RID      |a   |b   |c   |d      
----+----------+----+----+----+-------
0   |#12:100099|100 |101 |100 |100.1  
1   |#12:100102|103 |104 |103 |103.103
----+----------+----+----+----+-------
</pre>

as you can see the result set is wrong (i reindex 2 times the class , no changes)!  
Another wrong query:
<pre>
 select * from a1 where [ a , b , c , d ] LUCENE " a:[* TO 10] " 

0 item(s) found. Query executed in 0.016 sec(s).

</pre>
<pre>
orientdb {GratefulDeadConcerts}> info class a1

Class................: a1
Default cluster......: a1 (id=12)
Supported cluster ids: [12]
Cluster selection....: round-robin
Properties:
-------------------------------+-------------+-------------------------------+-----------+----------+----------+-----------+-----------+----------+
 NAME                          | TYPE        | LINKED TYPE/CLASS             | MANDATORY | READONLY | NOT NULL |    MIN    |    MAX    | COLLATE  |
-------------------------------+-------------+-------------------------------+-----------+----------+----------+-----------+-----------+----------+
 c                             | STRING      | null                          | false     | false    | false    |           |           | default  |
 b                             | INTEGER     | null                          | false     | false    | false    |           |           | default  |
 d                             | DOUBLE      | null                          | false     | false    | false    |           |           | default  |
 a                             | INTEGER     | null                          | false     | false    | false    |           |           | default  |
-------------------------------+-------------+-------------------------------+-----------+----------+----------+-----------+-----------+----------+
Indexes (1 altogether):
-------------------------------+----------------+
 NAME                          | PROPERTIES     |
-------------------------------+----------------+
 lind                          | a (+)          |
                               | b (+)          |
                               | c (+)          |
                               | d              |
-------------------------------+----------------+
orientdb {GratefulDeadConcerts}> select index:lind 

----+-----
#   |@RID 
----+-----
0   |#-2:0
----+-----

1 item(s) found. Query executed in 0.044 sec(s).

</pre>

It is correct last result set on 1000.000 of elements ?

**Comment by lvca** [comment]
Closed because no answer after a while. In case please comment this issue or reopen it if you're the author.
