### ISSUE TITLE
Improve logging with diagnostic context

### ISSUE THREAD

**Issue by fabriziofortino** [orientechnologies/orientdb#2468]
I have an OrientDB server with several databases (more than 150).

server.log outputs are interleaved because the server handles multiple clients pointing to different databases simultaneously. This makes the log almost impossible to read.

In this cases, it would be extremely useful to uniquely stamp each log request. This technique is gracefully implemented by log4j or logback using Mapped Diagnostic Context (http://logback.qos.ch/manual/mdc.html).

I think this could be easily implemented in Orient getting these information from the thread local context.

What do you think?

**Comment by jdillon** [comment]
FTR I still *strongly* recommend using Slf4j and Logback over JUL, lots of things become much simpler, in config, in code, in features.  Really worth considering IMO.

**Comment by lvca** [comment]
@jdillon what implications we'd have adding Slf4 in terms of dependencies (jars, sizes, etc) ?

**Comment by jdillon** [comment]
@lvca minimum, 2 jars:

main api: http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar 32119 bytes
jul-backend: http://repo1.maven.org/maven2/org/slf4j/slf4j-jdk14/1.7.10/slf4j-jdk14-1.7.10.jar 7895 bytes

However the JUL backend still is very limiting, so if you wanted a more robust and modern backend, I'd recommend logback, which is a bit more:

http://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar 418870 bytes
http://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar 264600 bytes

Though this is optional, by using the slf4j-api you are free to use whatever backend makes most sense for the application.  So you may, to reduce binary download size for your dist, choose to use the JUL backend which is fairly small.  But others, like myself, can use logback.  Though your users of the server distribution OOTB may appreciate the features of logback much more than what JUL gives you so it may be a good choice to go with that anyways, but its really up to you guys.

Additional goodness comes from sfl4j api which helps avoid string contact and avoids additional guard blocks with its standard "{}" placeholder syntax:

http://www.slf4j.org/manual.html

ie:
```
log.debug("Database created: {}", databaseName);
```

Defers string contatication until this log event is actually rendered, and avoids need to guard, ie:

```
if (log.isDebugEnabled()) {
     log.debug("Database created: " + databaseName);
}
```
This is a real saver on lines of code and code simplicity.

As well as the ability to use a MDC, which is also part of the standard api, and is *very* useful to solve problems like discussed here to encode additional information in log messages, but allow the formatting of those to be deferred to the underlying impls pattern renderer and not need to add complication to your entire codebase to include these details.

```
MDC.put("database", databaseName);
try {
   doOperation();
}
finally {
    MDC.remove("database");
}
```

And then supporting backends can include a pattern, like "%X{database}" in logback http://logback.qos.ch/manual/mdc.html, to include this value in logging.

All logging done by `doOperation()` will include this MDC value, so there is no need to change all of the logging done by this codepath to include these details, adding additional logging complexity to your codebase.

JUL is very limiting in terms of API as well as implementation and configuration.  I think your users will find the features of Logback *much* more compelling in terms of what can be done and how it can be configured.

I'd personally not build a server-platform w/o slf4j and logback.  And strongly recommend you guys consider it... or at the very least, consider using slf4j-api w/the JUL backend if you are worried about the size if logback.

Hope that helps.

--jason

**Comment by lvca** [comment]
Thanks @jdillon for the long comment. I think now it's too late to add it in 2.0 final, but I could put the database from ThreadLocal if present. This is much easier to add in current codebase.

**Comment by jdillon** [comment]
ya, way too late for 2.0, but still strongly suggest you guys consider a switch for the next major release.  you won't regret it ... I promise :-P

**Comment by lvca** [comment]
We added the database. For a configurable context logging, I'm going to postpone this to 3.0

**Comment by bquenin** [comment]
+1
