### ISSUE TITLE
Feature Request - Add modifiers support for MATCHES in Sql request

### ISSUE THREAD

**Issue by PiotrChr** [orientechnologies/orientdb#2479]
The Features Request:

It would be really helpful if MATCHES in SQL query could support modifiers. I'm working currently on orient-db based service and I'm really exited about its speed. I was even more amused by speed of regexp filter, untill I found out there's no support for modifiers, and particularly 'case insensitive' flag. 
I'm aware that this kind of filtering can be done in (at least) two ways - parsing input string to return each alphabetical char as a collection of uppercase and lowercase (i.e. ^[Ff][oO][oO].*), or creating a custom JS function. 
Although each way is not that problematic, using a modifiers would be much less time consuming.

**Comment by lvca** [comment]
Ok, so we already have this, right?

**Comment by buzzkillington** [comment]
@lvca - I don't know if this was the intended implementation, or a coincidence/side-effect. If the team has:
 * evaluated the implementation, 
 * determined that this is the preferred syntax, and 
 * (if it was an "accidental" feature) ensured that it's considered a documented part of the API moving forward

then the status/labeling for this issue makes sense.
