### ISSUE TITLE
[rexster/gremlin] Can not query any vertices after addVertex()

### ISSUE THREAD

**Issue by takaomag** [orientechnologies/orientdb#2488]
The original question can be found in this thread:
https://groups.google.com/forum/#!topic/orient-database/6s2Rr5u3uiQ

* Environment
OrientDB: 1.7.3
Rexster: 2.5.0

* Description
Using gremlin through Rexster console (i.e. Rexpro protocol),
   1. Add one new vertex using "graph.addVertex()".
   2. Then, query the other existing (not-changed) vertex than the new one, but null is returned.

* Example
```
rexster[groovy]> g = rexster.getGraph('m_test0')
==>orientgraph[remote:localhost/m_test0]

## Successful query (User.uid == 1)
rexster[groovy]> user_1 = g.query().labels('User').has('uid', 1).vertices().toList()[0]
==>v(User)[#142:0]

## Add one vertex (User.uid == 3)
rexster[groovy]> new_user = g.addVertex('class:User', 'uid', 3, 'nickname', 'mago')
==>v(User)[#140:-2]

## Can not query the other vertex (User.uid == 1) than the new one. What's wrong ?
rexster[groovy]> user_1_again = g.query().labels('User').has('uid', 1).vertices().toList()[0]
==>null

## Also, can not query the other existing vertex (User.uid == 2).
rexster[groovy]> user_2 = g.query().labels('User').has('uid', 2).vertices().toList()[0]
==>null

rexster[groovy]> g.commit()
==>null

## Even after commit(), all query fails.
rexster[groovy]> user_1_again = g.query().labels('User').has('uid', 1).vertices().toList()[0]
==>null

rexster[groovy]> user_3 = g.query().labels('User').has('uid', 1).vertices().toList()[0]
==>null
```

Even if I use "g.V('@class', 'User').has('uid', 1)" instead of "g.query().labels('User')", same result.

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
