### ISSUE TITLE
ObjectDB: Problem with dirty state / saving of Object hierarchies

### ISSUE THREAD

**Issue by dxxr** [orientechnologies/orientdb#2490]
OrientDB v1.7.3
Considering the following 3-level object hierarchy and (shortened) algorithm:
* Class A with a property of List&lt;B&gt; stored as LINKEDLIST
* Class B with a property of List&lt;C&gt; stored as LINKEDLIST
* Class C
```
 1  A a = db.query( ..."SELECT FROM A WHERE key='a1' ... );
 2  BigDecimal sum = BigDecimal.ZERO;
 3  for ( B b: a.getList() ) {
 4      for ( C c: b.getList() ) {
 5          c.setValue( ... some value ... );
 6          sum = sum.add( c.getAmount() );
 7      }
 8  }
 9  a.setTotal(sum);
10  db.save(a);
```

As of OrientDB v1.7-rc2 the change to the lowest level elements in line 5 would cause the affected `C` to become dirty as well as its parent `B` and `A`. Therefore the `save()` operation at the end would store the whole object tree into the database.

In contrast, as of OrientDB v1.7.3 the dirty state does *not* get propagated from C to its parent B anymore. Therefore the `save()` operation at the end would only store the A which became dirty in line 9. This causes a loss of all changes applied to the Cs.

Note that the `saveOnlyDirty` flag of the database connection is set to `false` in both cases/versions.

Question:
Is this change in behaviour intended and do we need to adapt our program to be able to migrate to OrientDB 1.7.3, e.g. by setting the Bs manually to 'dirty'?
Or is this a bug/regression that will be fixed eventually?

**Comment by tglman** [comment]
this is a really old bug, but the dirty management has been changed i 2.2.x so this bug is not valid anymore.

Now all the graph of references is saved when on of it's element is saved.
