### ISSUE TITLE
Exception in OTransactionOptimistic (v.2.0)

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#2494]
Hi i m inserting a new Object and give this exception 
   throw new OSchemaException("Record saved into cluster " + iClusterName + " should be saved with class "
                  + clusterIdClass + " but saved with class " + recordClass);

Seeing runtime in debug : 
Class has  2 cluster : 3 and 22 . 
Default cluster for class is 22. 

The problem is rid.clusterId contains 3 not 22. When code call  getClassByClusterId(3) give another class. 
I think is a bug in 2.0 cause in the previous i havent this error.

  
final ORecordSchemaAwareAbstract recordSchemaAware = (ORecordSchemaAwareAbstract) iRecord;
            final OClass recordClass = recordSchemaAware.getSchemaClass();
            final OClass clusterIdClass = database.getMetadata().getSchema().getClassByClusterId(rid.clusterId);
            if (recordClass == null && clusterIdClass != null || clusterIdClass == null && recordClass != null
                || (recordClass != null && !recordClass.equals(clusterIdClass)))
              throw new OSchemaException("Record saved into cluster " + iClusterName + " should be saved with class "
                  + clusterIdClass + " but saved with class " + recordClass);

**Comment by lvca** [comment]
@publicocean0 Could you please retry with a more recent version of OrientDB, like 2.1.2?

**Comment by publicocean0** [comment]
this problem i remember.... I  solved with a little trick : i moved the position in the code where i put setAbstract .... in this way i had no more problems. Anyway the problem in orientdb was in a block of code where you set Abstract .... inside the function there was a bug.

**Comment by lvca** [comment]
@publicocean0 do you remember what king of bug?

**Comment by publicocean0** [comment]
It was a previous version surely .... I remember  that when you set abstract inside the function was not reinitiealized all the data structure  correctly  so when you call this function in particular  moments you create a inconsistent state. For this reason there was a error as 
"The problem is rid.clusterId contains 3 not 22".

**Comment by tglman** [comment]
the cluster selection is evolved a lot since 1.7.*, this should be already fixed by the various refactor, i'll close it, if happen again we can reopen it.
