### ISSUE TITLE
Improve the ability to read data.

### ISSUE THREAD

**Issue by trainings** [orientechnologies/orientdb#2506]
I suggest the following approach:

select from cluster:some_cluster - selected data from cluster (so works now)

select from class:some_class - selected data from class (all clusters for class) without class hierarchy

select from some_class - selected data from class hierarchy (so works now)

**Comment by luigidellaquila** [comment]
Hi guys, 

Personally I think that our SQL syntax is already too cluttered of reserved words, we should work to simplify it, not to add new variants.

I'd like to drop an close this issue, WDYT?

Thanks

Luigi
