### ISSUE TITLE
Possible to improve  shutdown of orient client (now throw exceptions)? 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#2508]
lication [/aa] appears to have started a thread named [Timer-0] but has failed to stop it. This is very likely to create a memory leak.
23-Jun-2014 09:57:04.334 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoader.clearReferencesThreads The web application [/aa] appears to have started a thread named [OrientDB MemoryWatchDog] but has failed to stop it. This is very likely to create a memory leak.
23-Jun-2014 09:57:04.335 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoader.clearReferencesThreads The web application [/aa] appears to have started a thread named [OrientDB <- Asynch Client (/127.0.0.1:2424)] but has failed to stop it. This is very likely to create a memory leak.
^C23-Jun-2014 09:58:44.651 INFO [Thread-11] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
23-Jun-2014 09:58:44.667 INFO [Thread-8] org.apache.catalina.loader.WebappClassLoader.loadClass Illegal access: this web application instance has been stopped already.  Could not load com.orientechnologies.orient.core.storage.fs.OMMapManagerLocator.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
 java.lang.IllegalStateException
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1169)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1128)
    at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:200)
    at com.orientechnologies.orient.core.OrientShutdownHook.run(OrientShutdownHook.java:28)

Exception in thread "Thread-8" java.lang.NoClassDefFoundError: com/orientechnologies/orient/core/storage/fs/OMMapManagerLocator
    at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:200)
    at com.orientechnologies.orient.core.OrientShutdownHook.run(OrientShutdownHook.java:28)
Caused by: java.lang.ClassNotFoundException: com.orientechnologies.orient.core.storage.fs.OMMapManagerLocator
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1286)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1128)
    ... 2 more
23-Jun-2014 09:58:44.717 INFO [Thread-11] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-8009"]
23-Jun-2014 09:58:44.769 INFO [Thread-11] org.apache.catalina.core.StandardService.stopInternal Stopping service Catalina
23-Jun-2014 09:58:44.860 INFO [Thread-11] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
23-Jun-2014 09:58:44.861 INFO [Thread-11] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-8009"]
23-Jun-2014 09:58:44.863 INFO [Thread-11] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
23-Jun-2014 09:58:44.865 INFO [Thread-11] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-8009"]

**Comment by publicocean0** [comment]
Hi again error:  <pre> 10:01:39,272 DEBUG ApplicationBootstrap:158 - Stopping Orientdb ...
30-Dec-2015 10:01:39.273 INFO [localhost-startStop-2] com.orientechnologies.common.log.OLogManager.log - closing storage: abc...
30-Dec-2015 10:01:39.276 INFO [localhost-startStop-2] com.orientechnologies.common.log.OLogManager.log - closing storage: abc...
30-Dec-2015 10:01:39.276 INFO [localhost-startStop-2] com.orientechnologies.common.log.OLogManager.log - closing storage: abc...
30-Dec-2015 10:01:39.277 INFO [localhost-startStop-2] com.orientechnologies.common.log.OLogManager.log - closing storage: abc...
30-Dec-2015 10:01:39.280 INFO [localhost-startStop-2] com.orientechnologies.common.log.OLogManager.log - closing storage: abc...
30-Dec-2015 10:01:39.504 INFO [localhost-startStop-2] com.orientechnologies.common.log.OLogManager.log OrientDB Engine shutdown complete
10:01:39,505 DEBUG ApplicationBootstrap:160 - Stopping HanzelCast ...
10:01:41,170  INFO EhCacheManagerFactoryBean:181 - Shutting down EhCache CacheManager
30-Dec-2015 10:01:41.230 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoader.checkThreadLocalMapForLeaks The web application [/abc] created a ThreadLocal with key of type [com.orientechnologies.orient.client.remote.OStorageRemoteThreadLocal] (value [com.orientechnologies.orient.client.remote.OStorageRemoteThreadLocal@7aaf4ccc]) and a value of type [com.orientechnologies.orient.client.remote.OStorageRemoteThreadLocal.OStorageRemoteSession] (value [com.orientechnologies.orient.client.remote.OStorageRemoteThreadLocal$OStorageRemoteSession@1c2889de]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
30-Dec-2015 10:01:41.230 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoader.checkThreadLocalMapForLeaks The web application [/abc] created a ThreadLocal with key of type [com.orientechnologies.orient.core.db.OExecutionThreadLocal] (value [com.orientechnologies.orient.core.db.OExecutionThreadLocal@7c0a770f]) and a value of type [com.orientechnologies.orient.core.db.OExecutionThreadLocal.OExecutionThreadData] (value [com.orientechnologies.orient.core.db.OExecutionThreadLocal$OExecutionThreadData@11eb088c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
30</pre>

**Comment by laa** [comment]
Hi, this issue was opened year ago, what version do you use ?

**Comment by publicocean0** [comment]
2.1.6
