### ISSUE TITLE
out("**")[ ***  > number ] does not work

### ISSUE THREAD

**Issue by derek0377** [orientechnologies/orientdb#2517]
Hi,sorry to distrbute.

This my sql work well:

select count( distinct(@rid)) from  (  select expand(out('bu_server').out('server_release')[appId = 130500]) from #21:2 ) 

appId  is INTEGER which set by "create  property xmonreleases.appId INTEGER"

this my sql does not work

select count( distinct(@rid)) from  (  select expand(out('bu_server').out('server_release')[appId > 130500]) from #21:2 ) 

does the out filter support  ">" ?

Thank you

**Comment by lvca** [comment]
Closed because no answer after a while. In case please comment this issue or reopen it if you're the author.
