### ISSUE TITLE
Check refs console command

### ISSUE THREAD

**Issue by enisher** [orientechnologies/orientdb#2518]
A console command that allow to check and fix broken or inconsistent links.

It should allow user to specify what does he want to do with broken link:
- skip
- remove
- set value manually

For **edges** in graph db it should also check consistency of edge. That both vertexes aware of the specific edge. In case if edge is not consistent auto-fixing is possible, command should allow to do that automatically.

**Comment by lvca** [comment]
Already implemented with `repair database` console command.
