### ISSUE TITLE
DetachAll should deal with cyclic links

### ISSUE THREAD

**Issue by cmendis** [orientechnologies/orientdb#2525]
It should be possible to deal with DetachAll without causing StackOverflow exceptions. One possibility: DetachAll can keep a (thread) local hash map of objects traversed so that it can prevent going into a cycle on previously detached objects. This will also ensure that each persisted object in the object graph is instantiated only once and linked to wherever it is linked to in the object graph.

**Comment by thewall13** [comment]
I think there is a little problem with the map containing the already detached objects. The key to find the already detached object is based on ODocument hashCode(). The result of this method is not unique. This leads to some big problems, the map will return the wrong already detached object, if an other object has the same hash ->  in most cases we will have an ClassCastException.

I suggest to use getIdentity() with an ORID as key ?

**Comment by wouterv** [comment]
I you can make an example testcase, I'm happy to see if I can fix it.

**Comment by vitorenesduarte** [comment]
I don't think it's about a testcase. The codomain of a hash function is finite, so there might be collisions. ORID seems the best solution as @thewall13 suggested.

**Comment by wouterv** [comment]
Every change should have a testcase. It is to prevent regressions.
Op 30 jan. 2015 09:41 schreef "Vitor Enes Duarte" <notifications@github.com

**Comment by thewall13** [comment]
Yes, there should be a test-case for this function. 
I don't no why there is no one or maybe I don't find him. 
But in fact I agree to @vitorenesduarte that the missing test-case is an other problem. Of course it can also be fixed together with the key problem.

**Comment by wouterv** [comment]
I think you misunderstood me. There is a testcase for detachAll with cycles, which works fine. See commit https://github.com/orientechnologies/orientdb/commit/de09f08d16a419f57b5fa44d2ed3e4cb88d1adbd

What I am asking is an additional testcase showing the issues you are having. So give us some class definitions and object instantations which cause the ClassCastException you are experiencing, as I am not having such problems.

**Comment by vitorenesduarte** [comment]
It's not about cyclic links but about two different records having the same hashCode().
Look at hashCode() implementation in [this link](https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/id/ORecordId.java). It's unlikely, but as there are more inputs than outputs, collisions may happen.

**Comment by thewall13** [comment]
So if i don't totally missunderstood than are the hashValues of cluster X on position 31 the same as the hash of Cluster X+1 on position 0.      And so    X:32   ==  X+1:1  ; X:33   ==  X+1:2   -> etc.

This seems not very unlikely. The hashCode method seems very strange for me. For every cluster position number with an size of max 32bit the hash code will be:    (31 * clusterId) +  clusterPosition. 

So and for every position id bigger 32 bit it wil be something else, but this case is most of the time irrelevant.

**Comment by thewall13** [comment]
@wouterv : Sorry that I didn't see the test. I only looked into the test-folder of orientdb-object.

**Comment by thewall13** [comment]
https://github.com/orientechnologies/orientdb/issues/3561
