### ISSUE TITLE
UPDATE and UPSERT for CREATE VERTEX/EDGE

### ISSUE THREAD

**Issue by pumpupapp** [orientechnologies/orientdb#2561]
This would make the graphing SQL much more useful.

Idea generated from http://stackoverflow.com/questions/24644022/what-is-the-difference-between-insert-and-create-vertex-in-orientdb?noredirect=1#comment38246603_24644022

**Comment by luigidellaquila** [comment]
I updated this https://github.com/orientechnologies/orientdb/issues/1114 adding this case. 

I'm closing this because now it's duplicated
