### ISSUE TITLE
Allow sub inserts to create of linked documents from SQL JSON

### ISSUE THREAD

**Issue by mattaylor** [orientechnologies/orientdb#2570]
This works..

```
insert into class1 set key1 = (insert into class2 set key2 = 'test' ) 
```

It would be great to support subinserts for JSON based inserts and updates as well. Perhaps using some syntax like..

```
insert into class content { key1: { key2:'test', @type:'d', @class:'class2' } }
```

Perhaps the '@class' could be omitted and infered automaticallt if the schema for 'class1' specifies 'key1' as link to 'class2'

**Comment by lvca** [comment]
Not relevant anymore, closing it.
