### ISSUE TITLE
Exception with SQL Batch command with .NET Binary driver 

### ISSUE THREAD

**Issue by mikeg-ish-star** [orientechnologies/orientdb#2580]
1.  OrientDB release version 1.7.5
2.  I am using the .NET Binary driver from yojimbo87.  I am attempting to execute a SQL Command to insert a single record into a default class cluster.  When not using the SQL Batch syntax the INSERT is fine.  When I try to wrap the single INSERT command in the SQL Batch syntax I get the following exception:  

"com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.begin\n let mainEntity = INSERT INTO Account SET InstanceId = 'f534de26-c5af-47b4-869a-180d5fdbc10c', ExternalId = '', SourceSystem = '', RecordState = 1, IsDeactivated = False, IsDeleted = False,Created = '2014-07-16 17:14:03', CreatedById = #19:0,Name = 'My First Test Account',Website = 'http://www.redicecreations.com',Category = 'Standard',Classification = 'Commercial',Type = 'Prospect'\n commit\n return $mainEntity\n"

I also get the same error when trying to INSERT multiple records inside the SQL Batch syntax:

com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.begin\n let mainEntity = INSERT INTO Account SET InstanceId = '0b62da9c-3321-48da-8e3f-524aefdaee52', ExternalId = '', SourceSystem = '', RecordState = 1, IsDeactivated = False, IsDeleted = False,Created = '2014-07-16 18:04:31', CreatedById = #19:0,Name = 'My First Test Account',Website = 'http://www.redicecreations.com',Category = 'Standard',Classification = 'Commercial',Type = 'Prospect'\n let mainEntity2 = INSERT INTO Account SET InstanceId = '0b62da9c-3321-48da-8e3f-524aefdaee52', ExternalId = '', SourceSystem = '', RecordState = 1, IsDeactivated = False, IsDeleted = False,Created = '2014-07-16 18:04:32', CreatedById = #19:0,Name = 'My First Test Account',Website = 'http://www.redicecreations.com',Category = 'Standard',Classification = 'Commercial',Type = 'Prospect'\n commit\n return $mainEntity\n
1.  No custom settings.
2.  Expected behavior is for the records to be properly inserted into the DB with no exceptions being thrown.
3.  N/A

I look forward to your response as the need for ACID Transactions while perisisting Enity/Object Graphs is highly desired for the application I am building.

Regards,
Mike Griehm

**Comment by deacix** [comment]
I have the same problem with jdbc java driver. I am getting: 
Cause: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.....
