### ISSUE TITLE
Aggregation works incorrect with group by

### ISSUE THREAD

**Issue by kozlov-p-v** [orientechnologies/orientdb#2585]
I created simple entity names TestEntity with "ts" of type "datetime" and "id" of type "integer" and insert some data:

select from TestEntity

@rid	@version	@class	ts	id
#12:0	1	TestEntity	2014-07-17 12:47:35	0
#12:1	2	TestEntity	2014-07-17 12:48:33	0
#12:2	1	TestEntity	2014-07-16 12:49:06	0
#12:3	1	TestEntity	2014-07-17 12:49:34	1
#12:4	1	TestEntity	2014-07-15 12:49:59	1

When I try to do this query, I see:
select max(ts),@rid from TestEntity group by id
#-2:1	0	#12:2	2014-07-17 12:48:33
#-2:3	0	#12:4	2014-07-17 12:49:34

Which is incorrect, rid=12:4 doesn't match date "2014-07-17 12:49:34".

**Comment by AaronSchulz** [comment]
Does ```select max(ts),id from TestEntity group by id``` give a correct result?

**Comment by jlowenz** [comment]
I have the same problem. Selecting the max value over a group actually returns the fields from the wrong record. In fact, it seems to be returning the fields from the record in the group with the highest `@rid`. Is this actually correct behavior? If so, how would I return values from the record in the group with the max value?

My query looks like:

`select max(tx),@rid,name,valid from Test group by name`

where `name` (string), `tx` (long), `valid` (boolean) are in a "unique" index. Neither `@rid` nor `valid` match the record that actually contains the max `tx` value for each `name`

Using version OrientDB 2.1.0, studio version 2.1.

**Comment by lvca** [comment]
@jlowenz max() works separately than other fields. You could do something like:

    select tx,@rid,name,valid from Test where tx = (select max(tx) from Test group by name)
