### ISSUE TITLE
(Client=55) console.sh "set echo true" doesn't work

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#2588]
I want to open the console and write to it via shell. This is extremely important to enable automation and speed up development. I also believe a script-sharing area in the ODB community would be extremely useful, and this would enable that.

Here is a simple script that opens the console and connects to your database. I tried using the new 2.0-SNAPSHOT `set echo true` as advised (https://stackoverflow.com/questions/24689477/write-into-database-console-after-running-it-through-shell-script) but it's not working:

**Normal:** (no echo; enters console successfully)
```
gsquare567@Macintosh ~/S/p/s/l/o/bin> ./console.sh

OrientDB console v.2.0-SNAPSHOT (build UNKNOWN@r; 2014-07-15 07:31:49-0400) www.orientechnologies.com
Type 'help' to display all the commands supported.
Installing extensions for GREMLIN language v.2.5.0

orientdb> ⏎
```
**Echo:** (exits console once command is complete)
```bash
gsquare567@Macintosh ~/S/p/s/l/o/bin> ./console.sh "set echo true;CONNECT remote:localhost/pumpup root pass;"

OrientDB console v.2.0-SNAPSHOT (build UNKNOWN@r; 2014-07-15 07:31:49-0400) www.orientechnologies.com
Type 'help' to display all the commands supported.
Installing extensions for GREMLIN language v.2.5.0

orientdb> set echo true


echo = true

orientdb> CONNECT remote:localhost/pumpup root 6D919A2C4B555C13B1FF78B0B5DCCE687592C34D705977AFED449D429A993E0C

Connecting to database [remote:localhost/pumpup] with user 'root'...OK
gsquare567@Macintosh ~/S/p/s/l/o/bin>
```
similarly, `echo`ing inline after the console starts does nothing
```bash
bash-3.2$ ./console.sh && echo "set echo true;CONNECT remote:localhost/pumpup root test"

OrientDB console v.2.0-SNAPSHOT (build UNKNOWN@r; 2014-07-15 07:31:49-0400) www.orientechnologies.com
Type 'help' to display all the commands supported.
Installing extensions for GREMLIN language v.2.5.0

orientdb>
```

**Comment by SangWoo-Maeng** [comment]
You can use batch script like this
console.bat "connect remote:localhost/demo;select * from profile"
or
./console.sh "connect remote:localhost/demo;select * from profile"

See
http://orientdb.com/docs/last/Console-Commands.html

**Comment by lvca** [comment]
By using "set echo true" before the other commands does the job.
