### ISSUE TITLE
Where did GratefulDeadConcerts go?

### ISSUE THREAD

**Issue by braco** [orientechnologies/orientdb#2593]
I can't seem to find it in the repo, and this renders the documentation invalid, as none of the commands referencing "GratefulDeadConcerts" work.

**Comment by nakoba** [comment]
`TestLoadGraph` run with `-DstorageType=memory`

So if need GratefulDeadConcerts database, I execute:

```
ant -Dorientdb.test.env=release clean install
```
(thanks)
