### ISSUE TITLE
Parametrized query doesn't work in one particular case (nested query with @rid = ?)

### ISSUE THREAD

**Issue by young-druid** [orientechnologies/orientdb#2594]
Let's say we have a query like
```sql
select * from File where in("Contains").@rid in (select * from (traverse out("Contains") from (select * from Group where in("Owns").@rid in #11:0) while @class = "Group") where @rid = #12:0)
```
This query will work
And the query below won't work
```sql
select * from File where in("Contains").@rid in (select * from (traverse out("Contains") from (select * from Group where in("Owns").@rid in #11:0) while @class = "Group") where @rid = ?)
```
By [this](https://drive.google.com/file/d/0B55JU7RHUffnWGR0U0QxcTdycnM/edit?usp=sharing) link you can find a maven project with a failing junit test.
This issue could be related to [this](https://github.com/orientechnologies/orientdb/issues/2122) issue

**Comment by luigidellaquila** [comment]
Fixed (long time ago) in v 2.1.0 with the new parser

Closing

Thanks

Luigi
