### ISSUE TITLE
Document.fromJSON filters backslash

### ISSUE THREAD

**Issue by asaf** [orientechnologies/orientdb#2596]
Hey,

I have some json string containing a json property value with a backslash such:

```
"regex": "^\S+$"
```
(I also tried `"^\\S+$"` too)

Value is stored in the document as a `"^S+$"`,

I'd like the backslash to be stored as apart of the string,

Apparently, the method `OStringParser.getWords` filters backslash even though the next char is a backslash too.

Thanks.

**Comment by luigidellaquila** [comment]
Hi @asaf 

This issue is already fixed in v 2.2

I'm closing it, please reopen if you see any related problems

Thanks

Luigi
