### ISSUE TITLE
Index NULL values for EMBEDDEDMAP

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#2611]
It would be ideal if `EMBEDDEDMAP` indexes, when including `{ignoreNullValues : false}`, had the entire value of the property (not just values in the key/value pairs) indexed as null. Currently, indexing an `EMBEDDEDMAP` provides no benefit if searching for null/non-null values of the property.

This idea was taken from the following SO post: http://stackoverflow.com/questions/24895743/optimal-index-for-query-in-orientdb

**Comment by lvca** [comment]
Not relevant anymore, closing it.
