### ISSUE TITLE
Create back up tool which allows fast and effecient backups

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#2618]
On version 1.7 backup is simple:
We flush all memory cache and copy all files but in case of database is terrabytes of size it takes days to finish it. 
One of possible solutions is usage of following alghorithm:
1. Freeze database.
2. Create LVM like snapshot you can find steps here for linux http://www.lullabot.com/blog/article/mysql-backups-using-lvm-snapshots and here for windows http://technet.microsoft.com/en-us/magazine/dd348398.aspx
3. Release database.
4. Mount file system snapshot and do additional steps according to your application infrastructure.

**Comment by lvca** [comment]
Implemented long time ago.
