### ISSUE TITLE
Drop Database command doesn't drop database on all cluster nodes

### ISSUE THREAD

**Issue by srgg** [orientechnologies/orientdb#2619]
It seems that it drops database only on node on which it was executed.

Following test fails:

        final OServerAdmin serverAdmin = new OServerAdmin(embeddedOrientDB.getRemoteConnectionString());
        serverAdmin.connect(embeddedOrientDB.getUser(), embeddedOrientDB.getPassword());
        try{
            serverAdmin.dropDatabase(embeddedOrientDB.getDbStorageMode());
        }catch(Throwable t){
            serverAdmin.close();
            throw t;
        }

        // Wait a bit
        Thread.sleep(10000);

        final AbstractOrientDBCluster cluster = ((EmbeddedOrientDBRule)embeddedOrientDB).getCluster();
        for(int i=0; i<cluster.size(); ++i){
            final String user = cluster.getAdminName(i);
            final String pwd = cluster.getAdminPassword(i);
            final String connection = String.format("remote:%s/%s", cluster.getConnectionString(i), embeddedOrientDB.getDBName());
            final OServerAdmin a = new OServerAdmin(connection).connect(user, pwd);
            try{
                if(a.existsDatabase()){
                    fail(String.format("Database '%s' was dropped, but still exists on node %s",
                            embeddedOrientDB.getDBName(),
                            connection
                        ));
                }
            }catch(Exception e){
                a.close();
                throw e;
            }
        }

I've got:
> "Database 'testdb' was dropped, but still exists on node remote:127.0.0.1:63005/testdb"

**Comment by lvca** [comment]
I'm going to work on this in the next days. I was thinking to drop the database from all the nodes by default and adding this new setting:

    DROP DATABASE -server=china2

To drop the database only on server china2. Sounds good?

**Comment by lvca** [comment]
Supported distributed `DROP DATABASE`. Now, the only way to selectively drop a database is to use the Enterprise command `stop replication <server> -dropDatabase`.
