### ISSUE TITLE
Errors after removing all users

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#2621]
After removing all `OUser`s, I get an error on inserting a new one:

``` bash
orientdb {pumpup}> select from ouser


0 item(s) found. Query executed in 0.001 sec(s).
orientdb {pumpup}> insert into ouser set status='ACTIVE', name='garrett', password='test'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #5

Error: java.lang.NullPointerException
```

My fear is that during an import, a user will already have admin, reader, or writer as their name.

This is using 1.7.7.

**Comment by santo-it** [comment]
Thanks for opening this issue. Closing it as we are unable to replicate. Please reopen if appropriate. Thanks again
