### ISSUE TITLE
Improve record locking

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2627]
Right now the record lock manager holds the single locks, but with operations like "sql update" we could involve hundreds of records. We could scale up single locks in range-locks:

```
{
  from: #13:0,
  to: #13:10000
}
```

This means 1 only lock to handle 10,000 of them. But lighter. We should also provide a way to scale down locks. For example if I only unlock record ```#13:100```, I'd have:

```
{
  from: #13:0,
  to: #13:99
},
{
  from: #13:101,
  to: #13:10000
}
```

**Comment by laa** [comment]
That is not true, even if we update  million of records we always use only few threads. So this issue is irrelevant. Feel free to reopen it if you do not agree.
