### ISSUE TITLE
Bug in SQL Update PUT into embedded map

### ISSUE THREAD

**Issue by mav-im** [orientechnologies/orientdb#2642]
Orient DB v1.7.7
Hi guys, first thanks for the great DB!
I'm working on query builder for Orient DB (will be part of nodejs ORM for Orient). It's based on [oriento](https://github.com/codemix/oriento) package.
I see that SQL update for embedded map type with linked class is not working.
Based on [example](https://github.com/orientechnologies/orientdb/wiki/SQL-Update#example-5-put-a-map-entry-into-a-map) I thought the following query will work properly:

``` sql
update #20:2 put emb = "new", {"@type":"d","@class":"EmbClass","test":"value","var":[444,666]}
```

But got error in studio:

```
com.orientechnologies.orient.core.exception.OValidationException: The field 'TestR.emb' has been declared as EMBEDDEDMAP but the value is the RecordID #-1:-1
```

The same error if there is no linked class.

Also, the same error for ADD in embedded list, as mentioned here [#2480](https://github.com/orientechnologies/orientdb/issues/2480):

``` sql
update #20:2 add emblist = {"@type":"d","@class":"EmbClass","test":"value","var":[444,666]}
```

WIth error:

```
com.orientechnologies.orient.core.exception.OValidationException: The field 'TestR.emblist' has been declared as EMBEDDEDLIST but the value is the RecordID #-1:-1
```

I'm truing to implement update query statement with full support of commands from [Update](https://github.com/orientechnologies/orientdb/wiki/SQL-Update), but I see it's not possible currently.

Do you plan to fix it in nearest future?

**Comment by selmeci** [comment]
Same problem with EmbeddedMap in 2.0.2 and also this way
```json
update Book set section.intro= {"@class" : "BookSection", "@type" : "d", "title" : "Introduction", "createdAt" : {"@class":"TimeStamp","@type":"d", "timestamp" : "2015-02-14 13:37:44", "author" : #14:0}} where hash = "ajh78adh8asdhka7aaj"
```
does not work (only version of document is increased, but data are not saved).
PUT command return same error message as above.
