### ISSUE TITLE
Error on connecting to 127.0.0.1:2424/

### ISSUE THREAD

**Issue by sixter** [orientechnologies/orientdb#2644]
Hello 

I have followed all of the steps thus far and am stranded on https://github.com/orientechnologies/orientdb/wiki/Tutorial:-Run-the-console.
When I type in 
connect remote:localhost root password
I am getting : Connecting to remote Server instance [remote:localhost] with user 'root'...Error on retrieving the connection from pool: 127.0.0.1:2424/
Error on connecting to 127.0.0.1:2424/
-> com.orientechnologies.orient.client.remote.ORemoteConnectionManager.createNetworkConnection(ORemoteConnectionManager.java:210)
-> com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:74)
-> com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:71)
-> com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:82)
....

I have looked at issue #1783 and I have tried the few suggestions from the last post, but nothing is working. I have a Mac version 10.6.8. Maybe it is a problem with my security settings? If so, how do I go about removing these settings? What is the URL of the remote server?

I am very new to programming.

Any suggestions would be really really helpful!
Thank you,
Sixter

**Comment by lvca** [comment]
No answer after long time, closing.
