### ISSUE TITLE
min/max functions aren't optimized for indexes

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2655]
There are about 600 000 vertices of specific type (let say CustomType) in my graph database. Also CustomType have unique LONG field 'ID'. I've created index for this field (create index customtype_id on CustomType (ID) unique).
So searching through the IDs:

```
select from CustomType where ID=...
```

is pretty quick (~0.05s).

But when I execute the next query:

```
select min(ID) from CustomType
```

it takes more than one minute. 

I have expected that min() function should work as fast as search by field itself.

Isn't it a bug?

min() and max() functions are not optimized for this kind of cases. As a workaround you could try this:

   select ID from CustomType order by ID limit 1

**Comment by sblommers** [comment]
Any idea when this is getting resolved? This is a problem in all versions
