### ISSUE TITLE
Bug in Update PUT multiple key-value pairs into embedded map

### ISSUE THREAD

**Issue by mav-im** [orientechnologies/orientdb#2665]
OrientDB 1.7.7
I have a class with field:
```Javascript
embmap: type = EMBEDDEDMAP, linked-type = String
```
When I want to put 2 key-value pairs with single update sql:
```Javascript
UPDATE #20:0 PUT embmap = "test", "Luca", embmap = "test2", "Alex"
```
the only last pair will be added:
```
embmap = {"test2": "Alex"}
```
but the first key-value pair will be lost.
I didn't find this use case in wiki for [Update SQL](https://github.com/orientechnologies/orientdb/wiki/SQL-Update) but thought it should work like I wrote.

Also tried query:
```Javascript
UPDATE #20:0 PUT embmap = "test", "Luca" PUT embmap = "test2", "Alex"
```
but got error:
```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #44: Invalid keyword EMBMAP. Use UPDATE |cluster:> [SET|ADD|PUT|REMOVE|INCREMENT|CONTENT {}|MERGE {}] [[,] = |]* [LOCK ] [UPSERT] [RETURN ] [WHERE ] Command: UPDATE #20:0 PUT embmap = "test", "Luca" PUT embmap = "test2", "Alex" ----------------------------------------------------^
```

Do you have an example for such use case (i.e. putting more then 1 key-value pair at one SQL update) ?

**Comment by lvca** [comment]
Done. Now multiple PUT is supported. Thanks for reporting it.
