### ISSUE TITLE
Mistake in the RDBMS Wiki

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb#2666]
I don't know if it's the correct area for wiki change requests. So tell me where to post such stuff next time.

Alright the issue is that somehow in the old wiki
https://code.google.com/p/orient/wiki/ImportFromRDBMS
it correctly says: "
**CREATE LINK comments TYPE linkset FROM comment.postId To post.id INVERSE**"

what works well. In the new wiki
https://github.com/orientechnologies/orientdb/wiki/Import-RDBMS-to-Graph-Model
it says: "**CREATE EDGE E TRANSFORM comment.postId TO post.id INVERSE**"

which comes up with: 
**Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: E
rror on execution of command: sql.create EDGE E TRANSFORM comment.postId TO post
.id INVERSE Error: java.lang.NullPointerException**

Somehow the ID is no String on so does not work as an edge.

Is that just a mistake or did I something wrong in the tutorial.

Thanks.

**Comment by kennethpjdyer** [comment]
It appears that these issues were addressed at some point before the transition to the orientdb-docs repo.  None of the offending examples are present in the current build.

**Comment by luigidellaquila** [comment]
Hi @kennethpjdyer 

Thank you for the feedback! I'm closing then

Thanks

Luigi
