### ISSUE TITLE
[1.7.7] Query parsed and executed w/o exception (double where clause)

### ISSUE THREAD

**Issue by andreysorokin** [orientechnologies/orientdb#2671]
The following query is executed w/o exception

    select * FROM E where @class = 'ApplicationToFilter' WHERE out.name = 'debug'

An exception should be thrown as query syntax is invalid.

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot
