### ISSUE TITLE
Benchmark on AWS

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2677]
Now we have the official AMI:

https://aws.amazon.com/marketplace/pp/B00M07FHAO

It would be cool to address users to the best choice as price/performance.

AWS allows many choices, the SSD disk is the faster solution, but more expensive. We didn't execute a report about different performance against configuration, but this is something we'd like to do.

**Comment by Jotschi** [comment]
Is there a reason why the AMI is still using OrientDB 2.2.31 and not version 3? 
https://aws.amazon.com/marketplace/reviews/reviews-list/B00VKPTLUO
