### ISSUE TITLE
possible cache-related issue in browser with studio

### ISSUE THREAD

**Issue by alexpmorris** [orientechnologies/orientdb#2693]
In v1.7.8, after restarting a node in a 2 node distributed setup, I had this happen after both were running again:

Link: http://127.0.0.1:2480/studio/index.html#/database/mydb/browse/edit/11:2

Would immediate redirect to: http://127.0.0.1:2480/studio/index.html#/404

With json: {"data":"","status":0,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/document/mydb/11:2","headers":{"Accept":"application/json, text/plain, /"}},"statusText":""}

This seems to be some sort of cache-related issue (even though all the studio requests in chrome were set to no-cache), because when I tried the link in another chrome tab it worked fine on the same database.  Could this be related to javascript code that may be making an incorrect json request?

**Comment by lvca** [comment]
Fixed long time ago.
