### ISSUE TITLE
Support Amazon EBS Snapshot

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2705]
http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-CreateSnapshot.html

**Comment by G4br13l3** [comment]
Taking snapshots in order to make copies of instance store volumes is not so relevant from the OrientDB side. It should be better working for backups to Amazon S3. 
Closing this issue and moving the topic here: 

https://www.prjhub.com/#/issues/9056 



Thanks, 
Gabriele
