### ISSUE TITLE
SELECT COUNT(field) is very slow

### ISSUE THREAD

**Issue by Athelionas** [orientechnologies/orientdb#2706]
OrientDB 1.7.8

<pre>PROPERTIES
+-------------+-------------+-------------------+-----------+----------+----------+
| NAME        | TYPE        | LINKED TYPE/CLASS | MANDATORY | READONLY | NOT NULL |
+-------------+-------------+-------------------+-----------+----------+----------+
| birthday    | DATETIME    | null              | true      | false    | true     |
| firstName   | STRING      | null              | true      | false    | true     |
| password    | STRING      | null              | true      | false    | true     |
| salt        | STRING      | null              | true      | false    | true     |
| active      | BOOLEAN     | null              | true      | false    | true     |
| groups      | LINKSET     | Group             | true      | false    | true     |
| email       | STRING      | null              | true      | false    | true     |
| username    | STRING      | null              | true      | false    | true     |
| lastName    | STRING      | null              | true      | false    | true     |
+-------------+-------------+-------------------+-----------+----------+----------+

INDEXES
+-------------------------------+----------------+
| NAME                          | PROPERTIES     |
+-------------------------------+----------------+
| UserEmailIndex                | email          |
| UserSaltIndex                 | salt           |
| UserUsernameIndex             | username       |
+-------------------------------+----------------+
</pre>

The following query executes very slowly:

<pre>orientdb > select count(username) from User where username like '%12%'          

----+-----+-----
#   |@RID |count
----+-----+-----
0   |#-2:0|49401
----+-----+-----

1 item(s) found. Query executed in 7.768 sec(s).</pre>

<pre>orientdb > explain select count(username) from User where username like '%12%'

Profiled command '{documentReads:1000000,current:#11:999999,documentAnalyzedCompatibleClass:1000000,recordReads:1000000,projectionElapsed:4,fetchingFromTargetElapsed:7829,evaluated:1000000,groupByElapsed:0,elapsed:7829.875,resultType:collection,resultSize:1}' in 7.832000 sec(s):
{"@type":"d","@version":0,"documentReads":1000000,"current":"#11:999999","documentAnalyzedCompatibleClass":1000000,"recordReads":1000000,"projectionElapsed":4,"fetchingFromTargetElapsed":7829,"evaluated":1000000,"groupByElapsed":0,"elapsed":7829.875,"resultType":"collection","resultSize":1,"@fieldTypes":"documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,projectionElapsed=l,fetchingFromTargetElapsed=l,evaluated=l,groupByElapsed=l,elapsed=f"}</pre>

Interestingly, query execution time is very close to the following select, so it looks like count also fetches records it touches instead of just checking for existence.

<pre>orientdb > explain select username from User where username like '%12%'

Profiled command '{documentReads:1000000,current:#11:999999,documentAnalyzedCompatibleClass:1000000,recordReads:1000000,fetchingFromTargetElapsed:7911,evaluated:1000000,elapsed:7911.414,resultType:collection,resultSize:49401}' in 7.912000 sec(s):
{"@type":"d","@version":0,"documentReads":1000000,"current":"#11:999999","documentAnalyzedCompatibleClass":1000000,"recordReads":1000000,"fetchingFromTargetElapsed":7911,"evaluated":1000000,"elapsed":7911.414,"resultType":"collection","resultSize":49401,"@fieldTypes":"documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,evaluated=l,elapsed=f"}</pre>

Results with select \* are very similar.

**Comment by mindplay-dk** [comment]
Same problem here. Testing with a content database of 2.5 million articles, and count queries are essentially unusable. I'm using a LUCENE index.

**Comment by mindplay-dk** [comment]
In the log entries, I'm seeing a notice:

`2015-10-05 15:05:53:501 INFO  {db=fsa} [TIP] Query 'SELECT COUNT(*) FROM Article WHERE body LUCENE "odense"' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index [OProfilerStub]`

So, "create an index or change the query to use an existent index", but that's what I'm doing already.

**Comment by lvca** [comment]
That TIP is not very useful, working to provide that TIP only the target is not already an index. Created issue https://github.com/orientechnologies/orientdb/issues/5056 to track it apart.

**Comment by lvca** [comment]
@maggiolo00 are you already working on this days ago, right?

**Comment by maggiolo00** [comment]
@lvca  i saw that the count is not optimized and a was trying to optimize it in case of indexes. I don't know yet with other indexes but  case of lucene index can be optimized a lot.

@mindplay-dk  could you run this query and paste here the result?

```SQL
explain SELECT * FROM Article WHERE body LUCENE "odense" limit 1
```

**Comment by mindplay-dk** [comment]
```json
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 1,
            "fullySortedByIndex": false,
            "documentAnalyzedCompatibleClass": 1,
            "recordReads": 1,
            "luceneIndex": true,
            "fetchingFromTargetElapsed": 2,
            "Article_body_title_totalHits": 405664,
            "indexIsUsedInOrderBy": false,
            "score": 5.435673,
            "current": "#11:286933",
            "totalHits": 405664,
            "involvedIndexes": [
                "Article.body_title"
            ],
            "limit": 1,
            "evaluated": 1,
            "elapsed": 63.753193,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,score=f,current=x,involvedIndexes=e,evaluated=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 0.076 sec. Returned 1 record(s)"
}
```

**Comment by maggiolo00** [comment]
@mindplay-dk  as you can see in Article_body_title_totalHits you will get the total hits even with limit 1.
That is because lucene is optimized in that. But wrapped in select count(*)  the SQL engine
will load the results set from the index and count them. 
I'm working on this to make it use that value.

**Comment by mindplay-dk** [comment]
> wrapped in select count(*) the SQL engine will load the results set from the index and count them. 

That's what I suspected. Is this a general feature of OrientDB, or a limitation due to using this special index type?

@lvca Does OrientDB perform any optimizations for nested queries (such as what e.g. MySQL would do) or does it merely execute the inner queries and then operate on the resulting sets?

> I'm working on this to make it use that value.

Cool! I assume you will post an update here if/when that happens? Thanks :-)
