### ISSUE TITLE
HTTP Batch POST does not return the number of operations executed

### ISSUE THREAD

**Issue by lhsvobodaj** [orientechnologies/orientdb#2728]
According to OrientDB 1.7.8 HTTP API documentation (item [10.6](http://www.orientechnologies.com/docs/1.7.8/orientdb.wiki/OrientDB-REST.html)) the expected response of a batch POST is the number of operations executed. Although, in my test-case the response of a batch request contains the information about the last record created.

The following request is being sent:
```
Method: POST
URL: http://localhost:2480/batch/testdb
Body:
{"transaction": true,
  "operations": [
  {"type": "c",
    "record": {
      "@class": "Device",
      "hostname": "7.7.7.1"
  }},
  {"type": "c",
    "record": {
      "@class": "Device",
      "hostname": "7.7.7.2"
  }}]
}
```
Both operations are performed as expected since after the batch request completes my testdb contains both device instances (7.7.7.1 and 7.7.7.2). However, the response isn't compliant with the documentation:
```
Headers:
Status Code: 200 OK
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: Keep-Alive
Content-Length: 94
Content-Type: application/json; charset=utf-8
Date: Wed Aug 27 09:22:39 BRT 2014
Pragma: no-cache
Server: OrientDB Server v.1.7.8 (build UNKNOWN@r; 2014-08-13 15:56:07+0200)
Set-Cookie: OSESSIONID=OS1409142159085-5081225217702636342; Path=/; HttpOnly

Body:
{"result":[{"@type":"d","@rid":"#11:15","@version":1,"@class":"Device","hostname":"7.7.7.2"}]}
```

The response does not contain the number of operations, furthermore, it only contains information about the last record created (with `@type` "d"?).

**Comment by mitom** [comment]
Are there any news on this one, or an ETA maybe?

**Comment by sebastiandev** [comment]
Im still seeing this bug in the 2.1.0 version

**Comment by lvca** [comment]
Docs is wrong: returns last value. Updated docs. Thanks.
