### ISSUE TITLE
LIMIT required with ORDER BY and SKIP

### ISSUE THREAD

**Issue by srednal** [orientechnologies/orientdb#2743]
A document query using both ORDER BY and SKIP appears to require LIMIT (or else it returns an empty collection).

For example:
This returns the expected number of rows:
SELECT from alphabet SKIP 7
But this returns zero:
SELECT from alphabet ORDER BY letter SKIP 7
As does this
SELECT from alphabet ORDER BY letter SKIP 7 LIMIT -1

Experimentation indicates that you must supply an actual LIMIT in all cases when ordering.
As in:  SELECT from alphabet ORDER BY letter SKIP 7 LIMIT 100

**Comment by luigidellaquila** [comment]
hi @srednal 

I added your test case to develop branch (see https://github.com/orientechnologies/orientdb/blob/develop/core/src/test/java/com/orientechnologies/orient/core/sql/OCommandExecutorSQLSelectTest.java) and it seems to be fixed. 
Please reopen if I'm missing something

Thanks
