### ISSUE TITLE
Internal Scheduler Handler was removed on version 1.7.8

### ISSUE THREAD

**Issue by edinardo** [orientechnologies/orientdb#2769]
The class OScheduleHandler (com.orientechnologies.orient.server.schedule) was deleted on version 1.7.8.

Has any other scheduler that is taking place to handle the current records on OSchedule?

**Comment by lvca** [comment]
It's on our roadmap a rewriting of the Scheduler: https://github.com/orientechnologies/orientdb/issues/6125

**Comment by lvca** [comment]
Duplicated of It's on our roadmap a rewriting of the Scheduler: https://github.com/orientechnologies/orientdb/issues/6125.
