### ISSUE TITLE
Studio UI no longer has running query history stored in local storage

### ISSUE THREAD

**Issue by huckelliott** [orientechnologies/orientdb#2770]
Not sure in which version this changed but the query history feature which blindly (in a good way) saved recent queries in local storage was replaced by the new bookmarks feature (it actually requires the "_studio_bookmark" table to be explicitly defined which is kind of weird for a built in feature ). Bookmarks is a good concept but from a developer's point of view it does not hold a candle to the local storage alternative. Now when a db blown away and started from scratch all bookmarks are gone. During app development this could happen multiple times a day. Before this change queries remained in history until browser cache was cleared. It would be very nice to have both methods of maintaining query history availabe.

**Comment by lvca** [comment]
Closing this issue after no response in almost 2 years. Anyway, this feature is still there.
