### ISSUE TITLE
Attempting to connect console to DB with custom compression leaves it locked/corrupted

### ISSUE THREAD

**Issue by mcculls** [orientechnologies/orientdb#2775]
If an application creates a database and adds some records with custom compression (by setting `OCluster.ATTRIBUTES.COMPRESSION` for the record's cluster) then that database cannot then be opened by the console using a 'plocal' connection, because the console doesn't know about the custom compression:
```
orientdb> connect plocal:myapplication/db/config admin admin  
Connecting to database [plocal:myapplication/db/config] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage 'myapplication/db/config' with mode=rw  
Error: java.lang.IllegalArgumentException: Compression with name mycompression is absent.
```
This leaves the database in a locked state even after the console is detached, and subsequent attempts to open the database using the application that created it fail because it is seen as locked/corrupted.

Ideally it should still be possible to connect the console to a database that uses custom compression. Clusters that use an unknown compression could be marked as unreadable or only show compressed content. Clusters that use one of the default compressions, or no compression, would be readable.

If that's not achievable then the console should at least leave the database in a consistent unlocked state. Otherwise anyone can accidentally lock/corrupt a database with custom compression by simply attempting to attach the console to it via a 'plocal' connection.

**Comment by laa** [comment]
It will be fixed in "small pages" enhancement we plan to add functionality which will override any global settings by storage settings.
