### ISSUE TITLE
Security - Permission operation 'Read' against the resource: database.cluster.*

### ISSUE THREAD

**Issue by lucfranken** [orientechnologies/orientdb#2783]
**Target: Delete edge as a restricted user**
A user gets a role via an edge. User created the edge himself which works without issues. Delete of the edge fails.

**Expected result**

The edge should get deleted, should not give error and confirm it has been deleted.
ALSO: If I would not have permissions on a specific resource (I might have configured it wrong) then I would not expect a general database.cluster.* error but something like: database.cluster.hasrole DELETE not allowed.

**SQL command**

    DELETE EDGE FROM #5:3 TO #17:5

also tested with same negative result:

    DELETE EDGE HasRole FROM #5:3 TO #17:5

Query validated and works when sent in as admin via web tool.

**Error:**

````
Orient returned exception: 401 - com.orientechnologies.orient.core.exception.OSecurityAccessException: User 'xxxxxxxxxx' has no the permission to execute the operation 'Read' against the resource: database.cluster.*
````

**Rights in role setup (slimmed down)**
````
{
    "database": 2,
    "database.schema": 2,
    "database.cluster.internal": 2,
    "database.class.ouser": 15,
    "database.cluster.ouser": 15,
    "database.command": 15,
    "database.hook.record": 15,
    "database.cluster.myrole": 7,
    "database.class.myrole": 7,
    "database.cluster.hasrole": 15,
    "database.class.hasrole": 15,
}
````

Also tested with same negative result:

    "database.cluster.myrole": 15,
    "database.class.myrole": 15,

**Rights setup target I have**

User is **allowed to create and delete edges** between them.
User is **not allowed to delete myrole**.
User should be allowed to edit only it's own user. (not implemented yet, gave 15 on ouser as test).
User should not be able to read all data off course. So I did not give: cluster.* read access.

**Comment by lvca** [comment]
Cannot reproduce it.
