### ISSUE TITLE
Nullpointer exceptions

### ISSUE THREAD

**Issue by lucfranken** [orientechnologies/orientdb#2788]
As a user I get many time a null pointer exception without any useful information.

For example I am debugging a query in studio:

```
SELECT in(MyEdge) FROM MyVertex
```

The error I get in Studio, in the new red bar:

```
java.lang.NullPointerException
```

**Server console**

```
2014-09-10 09:35:46:677 SEVE Internal server error:
java.lang.NullPointerException [ONetworkProtocolHttpDb]
2014-09-10 09:35:48:265 SEVE Internal server error:
java.lang.NullPointerException [ONetworkProtocolHttpDb]
2014-09-10 09:36:01:571 SEVE Internal server error:
java.lang.NullPointerException [ONetworkProtocolHttpDb]
```

As a user I expect: A normal error like other databases do, something like SQL error: Unknown function, unknown table, whatever. I do not expect a null pointer exception.

From my Googling I understand that it's hard to fix this in total in Java though I suspected this would be fixed in some way by the testing routines you run before pushing a new snapshot/release?

Another example:

```
Example in manual:
create edge from #10:3 to #11:4
DELETE EDGE from #11:101 TO #11:117 Where date >= "2012-01-15"

My code made from that example:

CREATE EDGE FROM #5:3 TO #17:0
DELETE EDGE FROM #5:3 TO #17:0
Results in: java.lang.NullPointerException

DELETE EDGE FROM #17:0 TO #5:3
Returns no exception but value: = 0 (which seems to not delete the edge?)
```

**Comment by MathildeLemee** [comment]
Using 2.1.6 enterprise edition and have a lot of 

java.lang.NullPointerException [ONetworkProtocolHttpDb]
2015-11-25 20:24:06:633 SEVER Internal server error:

in my logs too :(

**Comment by wolfwood18** [comment]
Hi @MathildeLemee 

Is this happens when you use the sql profiler?
