### ISSUE TITLE
[1.7.8 ObjectDB] Linked entity references null after transaction commit

### ISSUE THREAD

**Issue by carlopolisini** [orientechnologies/orientdb#2810]
I am using a transaction for storing my entity but I found that after the commit, and not just after the save, linked references of the entity are all null.

Full details and test case available on OrientDB discussion group at https://groups.google.com/forum/#!topic/orient-database/8EF_jlh7cns

**Comment by laa** [comment]
I have ran tests several times and always get

universe galaxy found :)
universe galaxy found :)

So I close issue.

**Comment by mamdouhweb** [comment]
Just got the same issue here

`Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#17:0) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:1) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:14) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:9) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:4) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:5) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:6) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:17) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:18) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:0) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:7) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:14) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:9) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:4) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:5) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:6) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:17) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:18) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:0) is null
Feb 19, 2016 12:49:37 AM com.orientechnologies.common.log.OLogManager log
WARNING: Record (#15:7) is null
`
by trying to add and remove an Edge between two vertices, using orient 2.1.9
