### ISSUE TITLE
Server password should be hashed

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2811]

**Comment by lvca** [comment]
I have created also the following commands in console:
- list server users
- create server user <name> <passwd> <permission>
- drop server user <name>

**Comment by lvca** [comment]
Documented:
- http://orientdb.com/docs/last/Console-Command-List-Server-Users.html
- http://orientdb.com/docs/last/Console-Command-Set-Server-User.html
- http://orientdb.com/docs/last/Console-Command-Drop-Server-User.html

**Comment by nagarajasr** [comment]
@lvca sorry it is not clear "In order to drop the user the current system user that is running the console, must have the permissions to write the file $ORIENTDB_HOME/config/orientdb-server-config.xml"

does it mean that console user should be connected to server with plocal connection for the drop server user command to work?

**Comment by smolinari** [comment]
I would imagine it means, the users using the console to change Orientdb users must also be logged into the computer as a system user, who is able to access and manipulate the orientdb-server-config.xml file at system level.

Scott

**Comment by lvca** [comment]
@nagarajasr and @smolinari you're both right. Allowing to manage server users from remote connection is not implemented. However I think current implementation is good enough to avoid editing the XML file by hand.

**Comment by nagarajasr** [comment]
@smolinari the point is, in case of remote user logged in to the console, there is no way to determine if that remote system user has permissions to access and manipulate the server's orientdb-server-config.xml. this is particularly obvious if the remote user is on a different operating system (say, windows) than the server (which is on, say, linux).
to be fair, i have not tested this patch myself, but it appears that the console program reads/writes the LOCAL orientdb-server-config.xml (i.e., on the same host where the console is running) so it makes no sense connecting to a remote database. in fact could be quite misleading.
