### ISSUE TITLE
Make OrientDB json-schema aware

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#2812]
What if OrientDB class schemas are [json-schema](http://json-schema.org/) aware? So we can define custom types and have required fields and all the functionnality that json-schema can provide?
The goal is to be able to do something like that:

```
create property Car.color string,enum:['red', 'black', 'pink'],required
create property City.zipcode string,pattern:/[0-9]{5}/
```

http://spacetelescope.github.io/understanding-json-schema/ for more info.

**Comment by btiernay** [comment]
This would be great. I'm working on a project currently that does this at the application level.

**Comment by jcwright77** [comment]
also could use this. even an example application would help. Idea is to have data driven schema. this seems to come up every few years but haven’t seen an example implementation.
