### ISSUE TITLE
JVM crash when Hazelcast plugin is used

### ISSUE THREAD

**Issue by lubomirbenes** [orientechnologies/orientdb#2834]
JVM crashes when started Orient DB as distributed server. There is even no error log created. After some research I found out that Hazelcast health monitor is responsible for it. Turn off health monitor by parameter <pre>hazelcast.health.monitoring.level=OFF</pre> is a workaround. 

It does not happen everytime even if the platform is the same. Mine was Java 8 update 20 64bit, Windows 7. On one PC was ok on the other never ran.

**Comment by lvca** [comment]
Documented for further users: https://github.com/orientechnologies/orientdb-docs/blob/master/Distributed-Configuration.md
