### ISSUE TITLE
OObjectLazyList lazyload doesn't work with Java8 .stream()

### ISSUE THREAD

**Issue by neuhausjulian** [orientechnologies/orientdb#2835]
Hi everybody,

we discovered a little problem with lazyloading and the new java8 stream-api. The stream-api is using methods of ArrayList with direct access to the elementData-Array. So there is no way that OObjectLazyList can load the lazy values.

It seems like there is no easy way to solve the problem without a java8 version of orientdb. The method can not be "Override" because it contains a  java8 class as parameter.

Any suggestions or is there a plan to migrate to java8 ?

**Comment by thewall13** [comment]
So I forgot this  :D 

Any new suggestions ? So I read in the wiki, that the support of orientdb-object is cooling down. What about a Java8-Branch ?
