### ISSUE TITLE
[2.0-M1] Unexpected behavior with delete edge

### ISSUE THREAD

**Issue by Ndrou** [orientechnologies/orientdb#2848]
Hi,
I have a unexpected behavior when i try to delete edges with ranges.

![image](https://cloud.githubusercontent.com/assets/7899853/4417474/a52bb266-4554-11e4-8fac-ad04b890a473.png)

When I execute the command : 

```sql
DELETE EDGE TestEdge FROM (SELECT FROM Account Where @rid = '#32:0') TO (Select from City)
```

It deletes the 3 edges !

When I execute this command : 
```sql
DELETE EDGE FROM (SELECT FROM Account Where @rid = '#32:0') TO (Select from City) WHERE @class='TestEdge'
```

It works, it deletes only 1 edge !

**Comment by luigidellaquila** [comment]
Hi @Ndrou 

it seems to be already fixed in 2.1 (I cannot reproduce it).
I'm closing this issue, please reopen if needed
