### ISSUE TITLE
SQL Parsing error when ‘<‘ (less than) with no space

### ISSUE THREAD

**Issue by ginojohn** [orientechnologies/orientdb#2851]
When ‘<‘ (less than) with no space is used the following exception is thrown. 

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #126: Invalid keyword '2147483647'
Command: select from ClassName where name='name' and mean <2147483647 order by name sac

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot
