### ISSUE TITLE
WAL refactoring

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#2874]
As Luca wrote many times and as it is seen in ML one of the biggest problems are db availability after crash. Rebuild of indexes is taking forever.

I would like to tell that it is big problem for big guys.
Also solutions which we discussed till now mostly can be described like "lets track which files are changed and rebuild indexes only for them". But still it is very slow till we will not implement https://github.com/orientechnologies/orientdb/issues/1756 and https://github.com/orientechnologies/orientdb/issues/1757 .

So I propose a bit different approach.
Lets rid off from non-tx mode and implement parallel txs at least for not-distributed storage.

In such case we will never need to rebuild indexes.
I propose to start tx before first before_callback during document save and commit after last after_callback.

Also our project is used mostly as graph db so we will have more gains than pitfalls.

More details how it will work.

WAL design.

When we write data to any page we do not write data directly to the page instead we write changes into thread local WAL buffer as records.
When we read data from page/pages we apply recorded changes to the data are read. To make it fast we may use augmented tree as index, this tree is used to index interval (2-dimensional) values with log N complexity.
If we commit tx we write all records from wal thread local buffer to disk based wal and apply changes to the pages.
During rollback we just clear wal buffer.

So very important observation from this are:
   
1. Rollbacks are very fast.
2. We have read committed visibility level out of the box and I have doubts that we will need more levels during couple of next years.
3. We need to write 1/3 less amount of data which makes things faster.

Locks design.

We need to lock data when tx is running to avoid data inconsistencies so I propose to lock on pages level.
When we read page we apply read lock, when we write we apply write lock til tx is completed.

So what about deadlocks.

1. Tree structures can be locked using algorithm which avoids deadlocks.
2. Append only cluster "by definition" has low probability to generate such deadlock.
3. Rollbacks are fast so we can do rollback and retry.
4. We can keep higher level locks when it is needed to avoid deadlocks.

Also as it is seen we can remove most of the high level locks from our data structures and make them more mutli core scalaible.
We remove "stop the world" problem in our current implementation during tx commit, low level data structures will not know about high level so we will rid off dead lock issues and also we can implement change when changes in tx for remote storage will be visible for sql queries by replicating changes to server side transaction on sql request.

So I propose to make it as one main features of 2.1 .

What do you think ?

**Comment by sajalgupta1976** [comment]
Hi @laa ,
Since the probability of commit happening is more than rollback, won't it be prudent to write the latest changes to pages and maintain the old page data in wal thread local for read consistent view and rollback? That way in case of commit we just have to just clear the thread local making commit faster and during rollback apply the old changes. Just a thought.

**Comment by laa** [comment]
HI, in such case we can not restore data integrity during crash.

**Comment by sajalgupta1976** [comment]
Hi, after this fix, do we still need to acquire exclusive lock on storage during commit? So mt commit still not possible?

And there are multiple exclusive locks on cluster 1) in the OPaginatedCluster and 2) in the acquireExclusiveLockTillOperationComplete method in OAtomicOperationsManager, Why is this required? Anyway to avoid this?
