### ISSUE TITLE
Remote database and transaction problem

### ISSUE THREAD

**Issue by aswarcewicz** [orientechnologies/orientdb#2875]
I have a issue with transaction. In local embedded database everything is fine with following sequence:
1. Begin Transaction
2. Add Vertex with any custom property CID (my equivalent of ID) for example CID = 12345
3. Get Vertex  with CID = 12345
4. Commit

But in remote database in step 3, Function return null (getVertices().hasNext() == false)

**Comment by laa** [comment]
Assigned to @tglman

**Comment by tglman** [comment]
Hi,

This is solved with the support of remote transactions in 3.0.

Closing
