### ISSUE TITLE
Dense node or not dense node ? ...

### ISSUE THREAD

**Issue by MarcelPitch** [orientechnologies/orientdb#2878]
Hi All,

Here's the context. 
Our graph is composed of :
- 4M vertices
- 8M edges

The schema looks like that :

`v.Item` ----- `e.HAS_LABEL` -----> `v.Label` ----- `e.HAS_CULTURE` -----> `v.Culture`

One `Culture` vertex has about 4M incoming `HAS_CULTURE`  edges from `Label` vertices.

The problem is that a `DELETE VERTEX Label WHERE @rid = #XX:XXXX` request, for a Label connected on this dense vertex, takes about 30s to execute.
But the same request takes about 1s on a `Label` vertex, which is connected on another `Culture` vertex with only 2 000 incoming `HAS_CULTURE`  edges.

Could it be the reason of the slownless ?

If so, is there a way to ignore the amount of edges of the `Culture` dense vertex ?

Or do we have to create intermediate meta-nodes between `Label` and `Culture` vertices ?

Thank you in advance and have a good evening.

**Comment by laa** [comment]
Assigned to @tglman we have already discussed this issue with him
