### ISSUE TITLE
Bug in SELECT query

### ISSUE THREAD

**Issue by gauravdhiman** [orientechnologies/orientdb#2894]
I faced a weird issues with SELECT query.

Below query returns 2 records, where as it should have returned 0 record.

Query:

SELECT FROM Product WHERE ( ( (baseProduct.name LIKE '%This%') OR (baseProduct.description LIKE '%This%') OR (tags LIKE '%This%') OR (offerDetails LIKE '%This%') OR (business.name LIKE '%This%') OR (business.description LIKE '%This%') OR (business.tagline LIKE '%This%') ) AND ( (baseProduct.name LIKE '%space%') OR (baseProduct.description LIKE '%space%') OR (tags LIKE '%space%') OR (offerDetails LIKE '%space%') OR (business.name LIKE '%space%') OR (business.description LIKE '%space%') OR (business.tagline LIKE '%space%') ) ) OR ( (baseProduct.name LIKE '%what is your, space%') OR (baseProduct.description LIKE '%what is your, space%') OR (tags LIKE '%what is your, space%') OR (offerDetails LIKE '%what is your, space%') OR (business.name LIKE '%what is your, space%') OR (business.description LIKE '%what is your, space%') OR (business.tagline LIKE '%what is your, space%') ) OR ( ( (baseProduct.name LIKE '%smart%') OR (baseProduct.description LIKE '%smart%') OR (tags LIKE '%smart%') OR (offerDetails LIKE '%smart%') OR (business.name LIKE '%smart%') OR (business.description LIKE '%smart%') OR (business.tagline LIKE '%smart%') ) ) OR ( ( (baseProduct.name LIKE '%user%') OR (baseProduct.description LIKE '%user%') OR (tags LIKE '%user%') OR (offerDetails LIKE '%user%') OR (business.name LIKE '%user%') OR (business.description LIKE '%user%') OR (business.tagline LIKE '%user%') ) ) AND isApproved = true

Screenshot:
![sql-1](https://cloud.githubusercontent.com/assets/5612223/4557153/987b6db0-4ed0-11e4-98fb-56c5196a4a0c.png)

Now if move the last condition in WHERE clause to make it the first condition of WHERE clause, the query works fine (returns 0 record). In below query, just note that I made "isApproved = true" as first condition in WHERE clause where as it was the last condition in above query, otherwise both queries are same and should give same result.

Query:
SELECT FROM Product WHERE isApproved = true AND ( ( (baseProduct.name LIKE '%This%') OR (baseProduct.description LIKE '%This%') OR (tags LIKE '%This%') OR (offerDetails LIKE '%This%') OR (business.name LIKE '%This%') OR (business.description LIKE '%This%') OR (business.tagline LIKE '%This%') ) AND ( (baseProduct.name LIKE '%space%') OR (baseProduct.description LIKE '%space%') OR (tags LIKE '%space%') OR (offerDetails LIKE '%space%') OR (business.name LIKE '%space%') OR (business.description LIKE '%space%') OR (business.tagline LIKE '%space%') ) ) OR ( (baseProduct.name LIKE '%what is your, space%') OR (baseProduct.description LIKE '%what is your, space%') OR (tags LIKE '%what is your, space%') OR (offerDetails LIKE '%what is your, space%') OR (business.name LIKE '%what is your, space%') OR (business.description LIKE '%what is your, space%') OR (business.tagline LIKE '%what is your, space%') ) OR ( ( (baseProduct.name LIKE '%smart%') OR (baseProduct.description LIKE '%smart%') OR (tags LIKE '%smart%') OR (offerDetails LIKE '%smart%') OR (business.name LIKE '%smart%') OR (business.description LIKE '%smart%') OR (business.tagline LIKE '%smart%') ) ) OR ( ( (baseProduct.name LIKE '%user%') OR (baseProduct.description LIKE '%user%') OR (tags LIKE '%user%') OR (offerDetails LIKE '%user%') OR (business.name LIKE '%user%') OR (business.description LIKE '%user%') OR (business.tagline LIKE '%user%') ) )

Screenshot:
![sql-2](https://cloud.githubusercontent.com/assets/5612223/4557204/f8f39960-4ed0-11e4-9e9a-1b23c155f618.png)

**Comment by luigidellaquila** [comment]
Fixed long time ago

Closing

Thanks!

Luigi
