### ISSUE TITLE
question: (SQL) select multiple relations(4) flattened with data?

### ISSUE THREAD

**Issue by matgames** [orientechnologies/orientdb#2905]
hi, I currently have the following data:
```
member (Vertex): email, name
appointment (Vertex): some_date
InApp(Edge): is_maker [ from member to appointment ]
```
what I am trying to do is select an appointment some_date and the users in it, flattened, their emails.
the amount of users shouldn't be too big, but if impossible, I can hardcode limit it to 4.
I manage to get the list of members and emails by using expand, but that created that into rows. I was hoping there is some way to get into a single column (json?).

Also, it seems as if selecting both some_date with expand doesn't work, getting this error:
    Projection not allowed with FLATTEN() and EXPAND() operators

What I got so far:
(1)
    select expand(in().email) from appointment where appoint_id = 1

which returns 2 rows, one for each edge currently exists.

(2)
    select some_date, in() from appointment where session_id = 1

which returns 1 rows with 2 columns, yet second column is simply "[2]".

**Comment by luigidellaquila** [comment]
Current Studio version displays all the results.

Additionally, in v. 2.1 you can use the UNWIND function
