### ISSUE TITLE
[2.0-M2] regression in fetchplan when depth-level is set to 1

### ISSUE THREAD

**Issue by giastfader** [orientechnologies/orientdb#2906]
Hi,
I don't know if this is a bug or a feature:
I have a record that has some links to other records belonging to a class that extends ORestricted.
When I executed a statement like:
```
select @this.tojson("fetchPlan:visibleByFriends:1,indent:0") from _bb_user
```
I have different results between OrientDB 1.7.x and OrientDB 2.0-M2
If the user that is actually executing the statement does not have the right to read the visibleByFriends property, the 1.7.x version returns a JSON similar to:
```
{"visibleByTheUser":null}
```

the 2.0-M2 returns the RID of the linked record:
```
{"visibleByTheUser":"#14:31"}
```

**Comment by giastfader** [comment]
still present in 2.0.7

**Comment by lvca** [comment]
@giastfader Please could you provide a test case that reproduce this problem?

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Comment by giastfader** [comment]
Hi guys, 
sorry, I missed the reply.

The issue is still valid, for me, against 2.1.2 GA Community Edition.
Here is the steps to reproduce the problem:

````
connect plocal:/databases/test_issue_2906 admin admin
create class _bb_user
create class _BB_UserAttributes extends ORestricted
create property _BB_User.visibleByAnonymousUsers link _BB_UserAttributes
insert into _BB_UserAttributes set email = "example@example.com"
insert into _bb_user set _author="me", visibleByAnonymousUsers = #13:0 --<-- according to the output of the previous statement

connect plocal:/databases/test_issue_2906 reader reader
select @this.tojson("fetchPlan:visibleByAnonymousUsers:1,indent:0") from _bb_user
````

OrientDB 1.7.9:
````
{"_author":"me","visibleByAnonymousUsers":null}
````

OrientDB 2.1.2:
````
{"visibleByAnonymousUsers":"#13:0","_author":"me"}
````
