### ISSUE TITLE
request to move console history file location

### ISSUE THREAD

**Issue by ravihara** [orientechnologies/orientdb#2910]
I'm using 1.7.8 version of OrientDB. I have a feature request since, I feel it is pretty useful, atleast for Linux users.

Currently, console.sh command is creating tty console history (i.e., orientdb command history) under $ORIENTDB_HOME/bin folder. Instead, I would request it to be created under $HOME (Ex., $HOME/.orientdb_history.

Best regards,
Ravi

**Comment by robfrank** [comment]
History is saved in a dedicated orientdb dir in the user's home: ~.orientdb/orientdb_history

The directory ~.orientdb/ is created if not present. Could be used to store other settings

**Comment by ravihara** [comment]
Thanks for the fix!

**Comment by robfrank** [comment]
It will be part of 3.0.x series.
