### ISSUE TITLE
2.0-M2 prints server heap warning in java client

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#2911]
Running the Document API "Introduction" code, I get this message in my console output:

Oct 08, 2014 9:30:20 PM com.orientechnologies.common.log.OLogManager log
WARNING: Your maximum heap size is 2.17GB, but OrientDB uses off-heap memory to avoid GC pauses. In the case OrientDB is running as standalone, we recommend to use smaller amount of heap memory to let OrientDB using the rest as off-heap. 512 megabytes is recommended value of heap size.

That's should only be a server message right?   I need to use more than 2GB in client to support GUI, etc.

**Comment by laa** [comment]
I have ran tests several times and always get

universe galaxy found :)
universe galaxy found :)

So I close issue.

**Comment by laa** [comment]
We do not use this message any more
