### ISSUE TITLE
Distributed: asynchronous connects/updates too slow for production

### ISSUE THREAD

**Issue by nethertek** [orientechnologies/orientdb#2913]
After enabling asynchronous replication, inserts and deletes perform well, however connects and updates are still too slow for a production environment:

dserver.sh with one node up:

connect: 0.002266 s
insert: 0.000607 s
update:0.000972 s
delete: 0.000280 s

dserver.sh with two nodes up:

connect: 0.118694 s
insert: 0.000548 s
update: 1.292313 s 
delete: 0.000533 s

The full discussion can be found here:

https://groups.google.com/forum/embed/?place=forum/orient-database&theme=default&fragments=true&showsearch=true&showtabs=true&hideforumtitle=true&hidesubject=true&parenturl=http%3A%2F%2Fwww.orientechnologies.com%2Factive-user-community%2F#!topic/orient-database/xvOam45FXmc

**Comment by nethertek** [comment]
is this being worked on?

**Comment by nethertek** [comment]
What is the ETA for orientdb to support asynchronous CONNECT and UPDATE?

**Comment by lvca** [comment]
Unfortunately update & connect would need a bigger refactoring because how they are designed. This has been postponed to 2.2.

**Comment by lvca** [comment]
According to @nethertek this issue has been fixed.
