### ISSUE TITLE
JDBC driver doesn't work

### ISSUE THREAD

**Issue by ghost** [orientechnologies/orientdb#2915]
Tried JDBC driver 1.7 against the latest orientdb 2.0 release.

Connection conn =  DriverManager.getConnection("jdbc:orient:remote:localhost/GratefulDeadConcerts", info);

Results in:

java.sql.SQLException: No suitable driver found for jdbc:orient:remote:localhost/GratefulDeadConcerts

**Comment by MayraTrejo** [comment]
I need some help! i have tried a lot of things...
i´m using Netbeans, i have include the library JDBC+OrientDB libraries  (orientdb-jdbc-2.0.8-all.jar) in the directory and in netbeans, i have also include the connector in the proyect (i have include the connector in the Classpath),
but i still have the same problem : 

Exception in thread "main" java.sql.SQLException: No suitable driver found for jdbc:orient:remote:localhost/GratefulDeadConcerts
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at Aconexion.AConexion.main(AConexion.java:15)
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)

my code:
package Aconexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import com.orientechnologies.orient.jdbc.OrientJdbcConnection;
public class AConexion {
    public static void main(String[] args) throws SQLException {       
        Properties info = new Properties();
        info.put("user", "admin");
        info.put("password", "admin");
        Connection conn = (OrientJdbcConnection) 
        DriverManager.getConnection("jdbc:orient:remote:localhost/GratefulDeadConcerts", info);
        try{	
        Class.forName("com.orientechnologies.orient.jdbc.OrientJdbcDriver");
	Connection connection = (OrientJdbcConnection)
                DriverManager.getConnection("jdbc:orient:remote:localhost/GratefulDeadConcerts", info);
        }catch (ClassNotFoundException e) {
               e.printStackTrace();
        }
    }
}
![captura de pantalla 2015-05-11 11 36 33](https://cloud.githubusercontent.com/assets/11575396/7570020/7b001b90-f7d2-11e4-9c2e-ab9567aa4be1.png)

**Comment by luigidellaquila** [comment]
Hi,

I think the problem is that you have to move

Class.forName("com.orientechnologies.orient.jdbc.OrientJdbcDriver");

at the beginning, before you try to open a connection (line 14/15)

Let me know if it works

Luigi


2015-05-11 18:41 GMT+02:00 MayraTrejo <notifications@github.com>:

**Comment by abhimanyu-bitsgoa** [comment]
@luigidellaquila  You saved my life . Thanks a lot !!!
