### ISSUE TITLE
OChannelBinaryServer]Error on unmarshalling content. Class: c

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#2924]
Hi,

I have got logs in recent days, I don't understand why it happens, it worked before. Really strange!

"
2014-10-10 13:30:39:869 INFO /127.0.0.1:26725 - Read 237 bytes:    ☺c   ∩┐╜UPDATE Campaign  SET EntityInfo.State = :state  WHERE (EntityInfo.State <> :state) AND @rid in ( SELECT  Parent FROM    RecipientSource WHERE   (EntityInfo.State <> :state) AND (List = :p0) )☺   ▼params:{"p0":#39:9,"state":200}  [OChannelBinaryServer]Error on unmarshalling content. Class: c
Error on unmarshalling field 'params' in record #-1:-1 with value:
-> sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
-> sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
-> sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
-> java.lang.reflect.Constructor.newInstance(Constructor.java:525)
-> com.orientechnologies.common.log.OLogManager.exception(OLogManager.java:189)
-> com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.fromString(ORecordSerializerSchemaAware2CSV.java:248)
-> com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.fromStream(ORecordSerializerStringAbstract.java:657)
-> com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.deserializeFields(ORecordSchemaAwareAbstract.java:436)
-> com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1471)
-> com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:1607)
-> com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:538)
-> com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:558)
-> com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.fromStream(OCommandRequestTextAbstract.java:143)
-> com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.fromStream(OCommandRequestTextAbstract.java:73)
-> com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerAnyStreamable.fromStream(OStreamSerializerAnyStreamable.java:73)
-> com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1122)
-> com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:342)
-> com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:169)
-> com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)
Cannot load map because the type was not the expected: key=state(type class java.lang.String), value=200(type class java.lang.String)
"

Any help will be very appreciated!

**Comment by tglman** [comment]
added checks on the '-' sign, fixed, closing
