### ISSUE TITLE
Manipulating @RIDs through json notation

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#2927]
The official docs state that we can add a relationship (in a insert statement for example) this way:

```
insert into Employee (name, boss) values ('jack', #11:99 )
```

We can also insert a new record using JSON notation:

```
insert into Profile CONTENT {"name": "Jay", "surname" = "Miner"}
```

But what about inserting/updating a record involving a @rid with JSON notation? Is

```
insert into Profile CONTENT {"name": "Jay", "boss": #11:99}
```

Possible? Knowing that this leads to invalid JSON and enclosing a @rid into a string adds confusion with a legitimate "#11:99" string

**Comment by luigidellaquila** [comment]
At this stage we cannot introduce a new syntax (we are in RC), postponing it to 2.2

**Comment by luigidellaquila** [comment]
In V 3.0 we added an extended syntax for RID representation inside json:

```
insert into Profile CONTENT {"name": "Jay", "boss": {"@rid":"#11:99"}}
```

This should solve the problem

Thanks

Luigi
