### ISSUE TITLE
if append semicolon in alter DATETIMEFORMAT command it will be part of date format

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#2948]
Here is simple example:
alter database DATETIMEFORMAT yyyy-MM-dd HH:mm:ss Z;
create vertex Action set created_at = ‘2014-07-04 11:39:25 +0400’;

and we get Error on conversion of date '2014-07-04 11:39:25 +0400' using the format: yyyy-MM-dd HH:mm:ss Z

**Comment by luigidellaquila** [comment]
fixed in 2.2, now this syntax is no longer accepted

```
alter database DATETIMEFORMAT yyyy-MM-dd HH:mm:ss Z; 
```

you have to do this instead:
```
alter database DATETIMEFORMAT "yyyy-MM-dd HH:mm:ss Z"; 
```

that is not ambiguous

Thanks

Luigi
