### ISSUE TITLE
Javascript API: ODatabase.open() calls the wrong REST command

### ISSUE THREAD

**Issue by vmatare** [orientechnologies/orientdb#2955]
In orientdb-api.js from the 1.7.9 release, in ODatabase.prototype.open(), line 180, an ajax request is made for http://hostname/connect/dbname. This is supposed to retrieve info on the database and fill the databaseInfo field via the supplied callback. However none of the callbacks are ever called, since hostname/connect/dbname does not return data, as per the HTTP API spec: http://www.orientechnologies.com/docs/last/orientdb.wiki/OrientDB-REST.html#connect

When I change the ajax call to hostname/database/dbname, I get the expected result, i.e. the databaseInfo field is filled by the callback.

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
