### ISSUE TITLE
add network.http.sessionExpireTimeout to list of properties exposed via "server" HTTP call

### ISSUE THREAD

**Issue by aappddeevv** [orientechnologies/orientdb#2963]
In order to make it easier to program auto-authentication in a RESTful orientdb driver, provide the timeout in the http://server:port/server http api call.

network.http.sessionExpireTimeout

**Comment by lvca** [comment]
What do you mean? Could you please elaborate it more?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
