### ISSUE TITLE
[2.0M2] order by @rid desc query renders orientdb nonresponsive

### ISSUE THREAD

**Issue by javalama** [orientechnologies/orientdb#2966]
Problem 1: Queries like the following should be very fast:

    select from Address order by @rid desc

The Address class has ~10 million records, so even with a disk-sort, this should be pretty fast. With an inverse cluster cursor, the query should be very fast, according to http://www.orientechnologies.com/docs/2.0/orientdb.wiki/SQL-Query.html. 

But in fact, the query renders orientdb completely non-responsive. I can't even log into the server using the console (socket timeout). Seems like I triggered some kind of bug.

Note that the same problem occurs with ascending sort.

Problem 2: Probably as a side effect of Problem 1 (I had to kill the server), orientdb on restart now starts rebuilding indices. This takes a long time, and clients are unable to connect until it's ready. Such long startups renders orientdb a dubious choice in high-availability settings. Should be fixed in 2.0 IMO (that is, at least make the database available while indices are rebuilding)

This is a non-distributed database, running on a 64-bit machine/jvm with plenty of memory.

Thanks.

**Comment by lvca** [comment]
Fixed in 2.0-final.
