### ISSUE TITLE
Create Spatial Index failed for remote DB

### ISSUE THREAD

**Issue by phsmip** [orientechnologies/orientdb#2969]
The following line throws an error when executing it against a remote database:
<code>
oClass.createIndex("Place.latitude_longitude", "SPATIAL", null, null, "LUCENE", new String[] { "latitude", "longitude" });
</code>

See this post on Google Group:
https://groups.google.com/forum/#!topic/orient-database/u-L833_cNIo

**Comment by atlantux** [comment]
Workaround confirmed. Executing as a db.command() via Java API works fine.

**Comment by maggiolo00** [comment]
Fixed
https://github.com/orientechnologies/orientdb-lucene/issues/45
