### ISSUE TITLE
SELECT FROM V does sometimes only give 20 results back via Console.sh

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb#2976]
So here are the two ways to check if the same happens to you, too.

In the first way the **server is down**. Then you open the console and connect via "CONNECT plocal:C:/orientdb-community-2.0-M1/databases/Titles admin admin". Now logged in you search for "SELECT FROM V LIMIT 100". But instead getting back 100 results now we only get 20.
```sql
LIMIT EXCEEDED: resultset contains more items not displayed (limit=20)
```

The second way is when the **server is online**. So make sure the server is online and then start the console. Then you open the console and connect via "CONNECT plocal:C:/orientdb-community-2.0-M1/databases/Titles admin admin". Now logged in you search for "SELECT FROM V LIMIT 100". Now we correctly get back 
```sql
100 item(s) found. Query executed in 0.018 sec(s).
```

So I believe that in the plocal mode when the server is down the LIMIT 100 is ignored.

Also tested with remote for sure. But remote needs a server that is online. So not reproducable with remote.

PS: searching e.g. in the second example for "SELECT FROM Person LIMIT 100" gives back 100 result. So it's a special thing of **plocal, server down and V**!

**Comment by lvca** [comment]
You can remove limit in console:

    set limit -1
