### ISSUE TITLE
Improve WAL MT scalability.

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#2989]
After https://github.com/orientechnologies/orientdb/issues/2874  we have all chances to impove WAL scalability.

WAL can be presented as multi producer - single consumer queue. 
To implement this queue we can use single producer - single consumer queue where each separate thread will play producer role and WAL thread will play consumer role.
Queues can be stored inside of thread aware hash map as we did for RW spin lock.

For SPSC queue we can use improved version of Lamprot queue  or Fast Flow queue.
To keep append only (queue like) WAL nature and prevent reordering of records on producers side
we will calculate LSN on producers side using atomic variable, on consumer side we will use simple TreeMap to sort records by LSN as criticical size of buffer or time limit will be reached we will flush all WAL records which have no gaps between each other on disk.

**Comment by lvca** [comment]
Related also to https://github.com/orientechnologies/orientdb/issues/3882

**Comment by laa** [comment]
Optional for 3.0

**Comment by laa** [comment]
Implemented in 3.0.9
