### ISSUE TITLE
OrientDB2.0: Cannot route COMMAND operation to the distributed node

### ISSUE THREAD

**Issue by aprasad** [orientechnologies/orientdb#2993]
What I am trying to achieve is edge E between two vertices V1 and V2, where V1 is in cluster1 (Server1) and V2 is in cluster2(Server2).

While trying to do it manually, I followed the following steps and got the following error:

Console commands:

Server 1:
`create cluster cluster_0`
`create cluster cluster_1 `
`create class Person extends V cluster 18,19`
`create class Friend extends E`

Server 1:
`create vertex Person cluster:cluster_0 content {"UUID":"1","type":"Person", "first": "Dodong", "last":"Juan"}`

Server 2:
`create vertex Person cluster:cluster_1 content {"UUID":"3","type":"Person3", "first3": "Dodong3", "last3":"Juan3"}`

Server 1:
`create edge Friend #18:0 to #19:1`

The exception that I get is:

`Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot route COMMAND operation to the distributed node`
`Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.create edge Friend #18:0 to #19:1`
`Error: java.lang.NullPointerException`

Is cross server, inter-cluster edges not supported in OrientDB 2.0?
I verified that if the two clusters are in the same server, edges between them do get created. And the traversal also happens fine.

**Comment by lvca** [comment]
Fixed in 2.0
