### ISSUE TITLE
Console query bugging when copying some statement in

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb#3003]
So I'm now about testing several speed tests. I prepared some statements and now pasting them into the console. In this example when I pasted

```sql
orientdb {db=Prototyp1}> SELECT FROM (SELECT title,ID FROM Appln WHERE title LUCENE "solar" ORDER BY ID) LIMIT 10
```
I sent it. it was fine. But now I hit arrow up and wanted to move to the keyword to change it into **panel**. But somehow that was not liked by the console. On every hit I got a new lines.

Proof: http://i.imgur.com/7JErTMc.png

It's a visual bug, nothings else. But really awkward because now I really need to scrool up much.

Priority: high

PS1: I for sure checked that with the copy there was no ending whitespace or linebreak
PS2: console window is putty(winscp) in full width size

**Comment by taburet** [comment]
Fixed on 2.1.x and develop branches. Native TTY cursor now used instead of emulated one, bash/readline-like multiline prompt support added. Fixed hint list with old prompt garbage, if old prompt length is greater that the hint list item length.
