### ISSUE TITLE
Creation of vertices in distributed db causes exception

### ISSUE THREAD

**Issue by VladimirZenkevich** [orientechnologies/orientdb#3012]
I tried to create some vertices with edges. On my local environment (single db instance) it works fine: vertices has been created, appropriate edge also.
But when I tried to do the same on cluster which contains two nodes (distributed mode), the next exceptions has been thrown

The next exception has been thrown:

com.orientechnologies.orient.core.exception.OStorageException: Error on updating record #14:6 (cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@5adbb855)
Received:
{node1411049911259=166, node1411050518935=com.orientechnologies.orient.core.exception.OStorageException: Error on updating record #14:6 (cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@5adbb855)}

org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:114)
org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:323)
org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:207)
org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:209)
org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:152)
org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:114)
org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:185)
org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:108)
javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:164)
</pre></p><p><b>root cause</b> <pre>org.apache.cxf.interceptor.Fault: Quorum 2 not reached for request (id=1289 from=node1411049911259 task=record_update(#14:6 v.165) userName=admin). Servers in timeout/conflict are:

    node1411050518935: com.orientechnologies.orient.core.exception.OStorageException: Error on updating record #14:6 (cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@5adbb855)
    Received: {node1411049911259=166, node1411050518935=com.orientechnologies.orient.core.exception.OStorageException: Error on updating record #14:6 (cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@5adbb855)}

    org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:155)
    org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:121)
    org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:165)
    org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:92)
    org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
    java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    java.util.concurrent.FutureTask.run(FutureTask.java:262)
    org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
    org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:106)
    org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:263)
    org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:207)
    org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:209)
    org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:152)
    org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:114)
    org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:185)
    org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:108)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:164)
    </pre></p><p><b>root cause</b> <pre>com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=1289 from=node1411049911259 task=record_update(#14:6 v.165) userName=admin). Servers in timeout/conflict are:
    node1411050518935: com.orientechnologies.orient.core.exception.OStorageException: Error on updating record #14:6 (cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@5adbb855)
    Received: {node1411049911259=166, node1411050518935=com.orientechnologies.orient.core.exception.OStorageException: Error on updating record #14:6 (cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@5adbb855)}

    com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:525)
    com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:287)
    com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:456)
    com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:196)
    com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:369)
    com.orientechnologies.orient.server.distributed.ODistributedStorage.updateRecord(ODistributedStorage.java:452)
    com.orientechnologies.orient.core.db.raw.ODatabaseRaw.save(ODatabaseRaw.java:277)
    com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeSaveRecord(ODatabaseRecordAbstract.java:1121)
    com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:84)
    com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:322)
    com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:297)
    com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:40)
    com.orientechnologies.orient.core.db.ODatabaseRecordWrapperAbstract.save(ODatabaseRecordWrapperAbstract.java:292)
    com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:320)
    com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:257)
    com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:56)
    com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.updateRecord(OBinaryNetworkProtocolAbstract.java:325)
    com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.updateRecord(ONetworkProtocolBinary.java:1343)
    com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:309)
    com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:170)
    com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)

Actually vertex was created, and some edges also. but not all I need.

**Comment by lvca** [comment]
Please could you retry with 2.0-SNAPSHOT?

**Comment by lvca** [comment]
Fixed in 2.0-SNAPSHOT.
