### ISSUE TITLE
NullPointerException when executing DELETE EDGE (DB corruption?)

### ISSUE THREAD

**Issue by ghost** [orientechnologies/orientdb#3020]
This happens using the REST API as part of a batch process of multiple deletes.
After it happens, it consistently happens on the console as well:

DELETE EDGE #24:199

**Comment by zifnab87** [comment]
@lvca I have a database dump I could email you that has this issue - not only that but I believe it corrupts the database afterwards in such a way that exporting isn't done properly and dump is not usable..(not sure about this part though)- I will have to check

**Comment by lvca** [comment]
@zifnab87 this issue is old and closed. Are you saying you received the same exception on 2.1-rc5?

**Comment by zifnab87** [comment]
Yeap I did and 10 edges of a class that I deleted with DELETE EDGE were not deleted.. I figured out that the database becomes corrupt after that and if that was the reason creates unusable export files and doesn't allow new classes to be introduced

**Comment by zifnab87** [comment]
@lvca I freshly imported the database to 2.2-alpha and gives NullPointer exception as well when I am trying to delete all the edges of specific type..

**Comment by lvca** [comment]
If you use the Graph API you should never be in this situation. However, I'm looking for #4582 to fix it in case edges are broken anyway. Thanks for the report.

**Comment by zifnab87** [comment]
Thanks @lvca most probably I was able to remove the vertices that were on edges from studio since my application doesn't delete anything through code yet
