### ISSUE TITLE
Query over Restful API returns invalid JSON (2.0-SNAPSHOT)

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#3021]
QUERY 
select from V where type = 'song' and name = 'HEY BO DIDDLEY' fetchPlan *:1

returns (find out_sung_by and you will see that a closing brace } is missing before the array is closed with ] )

<pre>
{
	"result": [
		{
			"@type": "d",
			"@rid": "#9:1",
			"@version": 25,
			"@class": "V",
			"song_type": "cover",
			"name": "HEY BO DIDDLEY",
			"type": "song",
			"performances": 5,
			"out_followed_by": [
                {
                    "@type": "d",
                    "@rid": "#11:0",
                    "@version": 2,
                    "@class": "followed_by",
                    "out": "#9:1",
                    "in": "#9:2",
                    "weight": 1
                },
                {
                    "@type": "d",
                    "@rid": "#11:1",
                    "@version": 2,
                    "@class": "followed_by",
                    "out": "#9:1",
                    "in": "#9:3",
                    "weight": 2
                },
                {
                    "@type": "d",
                    "@rid": "#11:2",
                    "@version": 2,
                    "@class": "followed_by",
                    "out": "#9:1",
                    "in": "#9:4",
                    "weight": 1
                },
                {
                    "@type": "d",
                    "@rid": "#11:3",
                    "@version": 2,
                    "@class": "followed_by",
                    "out": "#9:1",
                    "in": "#9:5",
                    "weight": 1
                },
                {
                    "@type": "d",
                    "@rid": "#11:4",
                    "@version": 2,
                    "@class": "followed_by",
                    "out": "#9:1",
                    "in": "#9:6",
                    "weight": 1
                }
            ],
            "out_written_by": [
                {
                    "@type": "d",
                    "@rid": "#9:7",
                    "@version": 19,
                    "@class": "V",
                    "in_written_by": ["#9:1", "#9:6", "#9:369", "#9:579", "#9:579", "#9:651", "#9:713", "#9:749", "#9:803"],
                    "in_sung_by": ["#9:579", "#9:579", "#9:651", "#9:713", "#9:749", "#9:764", "#9:803"],
                    "name": "Bo_Diddley",
                    "type": "artist",
                    "@fieldTypes": "in_written_by=g,in_sung_by=g"
                }
            ],
            "out_sung_by": [
				{
					"@type": "d",
					"@rid": "#9:8",
					"@version": 47,
					"@class": "V"
            ],
            "in_followed_by": [
				{
					"@type": "d",
					"@rid": "#11:10",
					"@version": 2,
					"@class": "followed_by",
					"out": "#9:3",
					"in": "#9:1",
					"weight": 2
				},
				{
					"@type": "d",
					"@rid": "#11:150",
					"@version": 2,
					"@class": "followed_by",
					"out": "#9:5",
					"in": "#9:1",
					"weight": 2
				},
				{
					"@type": "d",
					"@rid": "#11:2578",
					"@version": 2,
					"@class": "followed_by",
					"out": "#9:49",
					"in": "#9:1",
					"weight": 1
				},
				{
					"@type": "d",
					"@rid": "#11:5574",
					"@version": 2,
					"@class": "followed_by",
					"out": "#9:25",
					"in": "#9:1",
					"weight": 1
				}
            ], 
          	"@fieldTypes": "in_followed_by=g"
		}
    ]
}
</pre>

**Comment by lvca** [comment]
We fixed it in 2.0-SNAPSHOT. Please could you retry it?

**Comment by luigidellaquila** [comment]
Hi @mrft 

AFAIK it's fixed on both 1.7.* and 2.0.
We did not receive any other feedback in last seven days, so I'm closing.
Please re-open if needed
