### ISSUE TITLE
Creating Vertex with EmbededSet Property as JSON throws Exception (2.0)

### ISSUE THREAD

**Issue by daniellawry** [orientechnologies/orientdb#3024]
Issue occurs in STUDIO version 2.0

Summary of Schema:

ConceptVersion -> a class that extends V
Has the following properties:
"id" (String)
"vid" (String)
"vocabularyEntries (EMBEDDEDSET of VocabularyEntry)

VocabularyEntry -> a class that extends V
"default" (Boolean)
"locale" (String)
"label" (String)
"description" (String)

Query:

create vertex ConceptVersion content 
{ 
	"id" : "1", 
	"vid" : "1", 
	"vocabularyEntries" : [
		{
			"default" : true, 
			"locale" : "en_US", 
			"label" : "concept", 
			"description" : "concept"
		}, 
		{ 
			"locale" : "es_US", 
			"label" : "concepto", 
			"description" : "concepto"
		}
	]
}

Error:

com.orientechnologies.orient.core.exception.OValidationException: The field 'ConceptVersion.vocabularyEntries' has been declared as EMBEDDEDSET but an incompatible type is used. Value: {locale=es_US, label=concepto, description=concepto}

It looks as though the JSON is formatted properly.  I would have expected the behavior to allow for the creation of the embedded VocabularyEntry objects using this JSON format

Note: using the same JSON for each of the two vocabularyEntries values I can create VocabularyEntry vertices directly using the exact same JSON

**Comment by lvca** [comment]
Put `@type: 'd'`inside each embedded object
