### ISSUE TITLE
Bad transaction semantics in OrientGraphFactory

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3025]
Anytime I call OrientGraphFactory.getTx() or .getNoTx() to get another instance from the pool, my transaction is silently committed then reopened by the initGraph() function.  

This could be a big surprise to users, thinking that they can still rollback() a transaction that's in progress but discovering that it's already been committed.

**Comment by laa** [comment]
This conversation was inactive for many days, so I close it.
