### ISSUE TITLE
LET ... problem

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#3029]
<pre>
select out_followed_by.asList().asString() as fb
from V 
where type = 'song' and name = 'HEY BO DIDDLEY'
</pre>

works and

<pre>
select $ofb as fb, name
from V 
let $ofb = out_followed_by.asList().asString()
where type = 'song' and name = 'HEY BO DIDDLEY'
</pre>

doesn't

(for milestone 2.1 where the query parser implementation will be rewritten)

**Comment by luigidellaquila** [comment]
fixed in develop branch and added a test case
