### ISSUE TITLE
Method in OrientVertex for counting Edges to destination vertex by optionally giving the Edge labels

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3040]
As adviced by Luca, in the topic https://groups.google.com/forum/#!topic/orient-database/dfsaWsESB-Y at google groups, I am creating this issue 

This is to have a method in OrientVertex class as per below signature

```java
int OrientVertex.countEdges(OrientVertex destination, Direction direction, String... labels)
```

This will reduce OrientVertex.getEdges() method calls just to check existence and if the Edge objects are not needed.

Pls tell me if I have to give any other information

**Comment by lvca** [comment]
By reading the thread, the problem was in hasNext() that compute lazy the traversal. So having a count() wound't optimize this case.
