### ISSUE TITLE
Performance of select query using index is extremely low

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#3041]
<pre>
create property V.name string
create index vname on V( name ) notunique
</pre>

<pre>
select from V where name = 'HEY BO DIDDLEY'
</pre>

=> Query executed in 0.069 sec. Returned 1 record(s) 

<pre>
explain select from V where name = 'HEY BO DIDDLEY'
</pre>

returns

<pre>
             "limit": -1,
            "compositeIndexUsed": 1,
            "involvedIndexes": [
                "vname"
            ],
            "fullySortedByIndex": false,
            "indexIsUsedInOrderBy": false,
            "current": "#9:1",
            "evaluated": 1,
            "fetchingFromTargetElapsed": 0,
            "documentReads": 1,
            "user": "#5:0",
            "documentAnalyzedCompatibleClass": 1,
            "recordReads": 1,
            "elapsed": 1.978317,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "compositeIndexUsed=l,involvedIndexes=e,evaluated=l,fetchingFromTargetElapsed=l,documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 0.068 sec. Returned 1 record(s)"
</pre>

which indicates the index is being used.

69 milliseconds, for fetching 1 single record, you could beat that performnce by a serial search. This is a severe contrast with OrientDB boasting about its speed on the website...

Oh, and I am running OrientDB locally (so no network latency), and ran this query through the studio (but that doesn't really matter). Version 1.7.9 or 2.0-M2 doesn't matter also

**Comment by mrft** [comment]
Purely informational, some new becnhmark results using v2.0.

First without indexes, and then with indexes (notunique) on name, type and song_type columns

## WITHOUT INDEXES

Start the benchmark with 1000 queries (select from V where name = 'STANDER ON THE MOUNTAIN' ).
Time : 113533730 ns. counter : 1000
Running this query (returning 1 results) 1000 times took 11353.373027 ms. That's 88.07955112739202 per second, and 11.353373027 ms per event.

Start the benchmark with 1000 queries (select from V where name = 'HEY BO DIDDLEY' ).
Time : 113843996 ns. counter : 1000
Running this query (returning 1 results) 1000 times took 11384.399627 ms. That's 87.83950254419507 per second, and 11.384399627 ms per event.

Start the benchmark with 1000 queries (select * from V where song_type = 'original' ).
Time : 126442780 ns. counter : 184000
Running this query (returning 184 results) 1000 times took 12644.278037 ms. That's 79.08715682095689 per second, and 12.644278037 ms per event.

Start the benchmark with 1000 queries (select * from V where song_type = 'original' limit 100 ).
Time : 53345030 ns. counter : 100000
Running this query (returning 100 results) 1000 times took 5334.50304 ms. That's 187.4588865170091 per second, and 5.3345030399999995 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'song' limit 100 ).
Time : 34360785 ns. counter : 100000
Running this query (returning 100 results) 1000 times took 3436.078525 ms. That's 291.0294374020454 per second, and 3.436078525 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'song' limit 500 ).
Time : 122897201 ns. counter : 500000
Running this query (returning 500 results) 1000 times took 12289.720153 ms. That's 81.36881780468318 per second, and 12.289720153000001 ms per event.

Start the benchmark with 1000 queries (select name from V where type = 'song' limit 100 ).
Time : 48835848 ns. counter : 100000
Running this query (returning 100 results) 1000 times took 4883.584849 ms. That's 204.76761045828204 per second, and 4.883584849 ms per event.

Start the benchmark with 1000 queries (select name from V where type = 'song' limit 500 ).
Time : 176030408 ns. counter : 500000
Running this query (returning 500 results) 1000 times took 17603.040805 ms. That's 56.808366865567805 per second, and 17.603040805 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'song' ).
Time : 141386616 ns. counter : 584000
Running this query (returning 584 results) 1000 times took 14138.661688 ms. That's 70.72805206512132 per second, and 14.138661688000001 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'artist' limit 100 ).
Time : 86256039 ns. counter : 100000
Running this query (returning 100 results) 1000 times took 8625.60399 ms. That's 115.93391038579317 per second, and 8.62560399 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'artist' limit 200 ).
Time : 130524879 ns. counter : 200000
Running this query (returning 200 results) 1000 times took 13052.487977 ms. That's 76.61374611201451 per second, and 13.052487977 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'artist' ).
Time : 139536159 ns. counter : 224000
Running this query (returning 224 results) 1000 times took 13953.615931 ms. That's 71.66601151593643 per second, and 13.953615931 ms per event.

Start the benchmark with 1000 queries (select distinct( type ) from V ).
Time : 138131889 ns. counter : 2000
Running this query (returning 2 results) 1000 times took 13813.18893 ms. That's 72.39457920018474 per second, and 13.81318893 ms per event.

## WITH INDEXES

Start the benchmark with 1000 queries (select from V where name = 'STANDER ON THE MOUNTAIN' ).
Time : 6926333 ns. counter : 1000
Running this query (returning 1 results) 1000 times took 692.633384 ms. That's 1443.7652343941886 per second, and 0.692633384 ms per event.

Start the benchmark with 1000 queries (select from V where name = 'HEY BO DIDDLEY' ).
Time : 9111726 ns. counter : 1000
Running this query (returning 1 results) 1000 times took 911.172603 ms. That's 1097.486905013978 per second, and 0.911172603 ms per event.

Start the benchmark with 1000 queries (select * from V where song_type = 'original' ).
Time : 55548184 ns. counter : 184000
Running this query (returning 184 results) 1000 times took 5554.818462 ms. That's 180.02388500018634 per second, and 5.554818462 ms per event.

Start the benchmark with 1000 queries (select * from V where song_type = 'original' limit 100 ).
Time : 38716364 ns. counter : 100000
Running this query (returning 100 results) 1000 times took 3871.636488 ms. That's 258.28871153050255 per second, and 3.871636488 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'song' limit 100 ).
Time : 38406157 ns. counter : 100000
Running this query (returning 100 results) 1000 times took 3840.615723 ms. That's 260.37491697265546 per second, and 3.840615723 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'song' limit 500 ).
Time : 105795004 ns. counter : 500000
Running this query (returning 500 results) 1000 times took 10579.500426 ms. That's 94.5224216393448 per second, and 10.579500426000001 ms per event.

Start the benchmark with 1000 queries (select name from V where type = 'song' limit 100 ).
Time : 47336915 ns. counter : 100000
Running this query (returning 100 results) 1000 times took 4733.691577 ms. That's 211.25161699566303 per second, and 4.733691576999999 ms per event.

Start the benchmark with 1000 queries (select name from V where type = 'song' limit 500 ).
Time : 153366976 ns. counter : 500000
Running this query (returning 500 results) 1000 times took 15336.697631 ms. That's 65.20308504868117 per second, and 15.336697631 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'song' ).
Time : 113562996 ns. counter : 584000
Running this query (returning 584 results) 1000 times took 11356.299655 ms. That's 88.0568521771716 per second, and 11.356299655 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'artist' limit 100 ).
Time : 28642008 ns. counter : 100000
Running this query (returning 100 results) 1000 times took 2864.200856 ms. That's 349.13752570989385 per second, and 2.864200856 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'artist' limit 200 ).
Time : 43286484 ns. counter : 200000
Running this query (returning 200 results) 1000 times took 4328.648443 ms. That's 231.01899199440254 per second, and 4.328648443 ms per event.

Start the benchmark with 1000 queries (select * from V where type = 'artist' ).
Time : 47580440 ns. counter : 224000
Running this query (returning 224 results) 1000 times took 4758.044031 ms. That's 210.17039638236167 per second, and 4.758044031000001 ms per event.

Start the benchmark with 1000 queries (select distinct( type ) from V ).
Time : 150766144 ns. counter : 2000
Running this query (returning 2 results) 1000 times took 15076.61445 ms. That's 66.32788835427174 per second, and 15.07661445 ms per event.

**Comment by mrft** [comment]
Some more test results on OrientDB version 2.0.5.

For the last query **select name, $sungbyrecord as x_sungby from V let $sungby = outE()[ @class = 'sung_by' ], $sungbyrecord = list( (select in.name from $sungby ) ) where name='HEY BO DIDDLEY'**, the difference between with and without indexes is incredible, which I find peculiar, since traversing edges is being advertised as have a very low cost, so you would expect this time to always (indexes or not) be very close to a simple **select name from V where name='HEY BO DIDDLEY'** but it takes 10 times as long without indexes, and about the same time with indexes.

Without indexes
---------------------

query | # rows /query | # queries /sec | # rows /sec | ms /query | ms /row | # queries | totalTime (ms)
:---- | ------------: | -------------: | ----------: | --------: | ------: | --------: | -------------:
select * from V where song_type = 'original' | 184 | 71.441 | 13145.172 | 13.998 | 0.076 | 1000 | 13997.535
select * from V where song_type = 'original' limit 100 | 100 | 165.990 | 16598.958 | 6.024 | 0.060 | 1000 | 6024.475
select * from V where type = 'song' limit 100 | 100 | 257.518 | 25751.799 | 3.883 | 0.039 | 1000 | 3883.224
select * from V where type = 'song' limit 500 | 500 | 77.580 | 38790.167 | 12.890 | 0.026 | 1000 | 12889.865
select name from V where type = 'song' limit 100 | 100 | 215.258 | 21525.838 | 4.646 | 0.046 | 1000 | 4645.580
select name from V where type = 'song' limit 500 | 500 | 57.107 | 28553.438 | 17.511 | 0.035 | 1000 | 17511.026
select * from V where type = 'song' | 584 | 68.734 | 40140.737 | 14.549 | 0.025 | 1000 | 14548.811
select * from V where type = 'artist' limit 100 | 100 | 109.713 | 10971.268 | 9.115 | 0.091 | 1000 | 9114.717
select * from V where type = 'artist' limit 200 | 200 | 75.247 | 15049.494 | 13.289 | 0.066 | 1000 | 13289.484
select * from V where type = 'artist' | 224 | 70.668 | 15829.675 | 14.151 | 0.063 | 1000 | 14150.638
select distinct( type ) from V | 2 | 69.532 | 139.063 | 14.382 | 7.191 | 1000 | 14381.942
select name, $sungbyrecord as x_sungby from V let $sungby = outE()[ @class = 'sung_by' ], $sungbyrecord = list( (select in.name from $sungby ) ) where name='HEY BO DIDDLEY' | 1 | 7.289 | 7.289 | 137.198 | 137.198 | 1000 | 137198.168

With indexes (3 x notunique on name, song_type and type)
-----------------

query | # rows /query | # queries /sec | # rows /sec | ms /query | ms /row | # queries | totalTime (ms)
:---- | ------------: | -------------: | ----------: | --------: | ------: | --------: | -------------:
select from V where name = 'STANDER ON THE MOUNTAIN' | 1 | 998.787 | 998.787 | 1.001 | 1.001 | 1000 | 1001.215
select from V where name = 'HEY BO DIDDLEY' | 1 | 1533.218 | 1533.218 | 0.652 | 0.652 | 1000 | 652.223
select * from V where song_type = 'original' | 184 | 192.444 | 35409.669 | 5.196 | 0.028 | 1000 | 5196.321
select * from V where song_type = 'original' limit 100 | 100 | 267.173 | 26717.287 | 3.743 | 0.037 | 1000 | 3742.895
select * from V where type = 'song' limit 100 | 100 | 267.646 | 26764.556 | 3.736 | 0.037 | 1000 | 3736.285
select * from V where type = 'song' limit 500 | 500 | 99.432 | 49716.195 | 10.057 | 0.020 | 1000 | 10057.085
select name from V where type = 'song' limit 100 | 100 | 228.666 | 22866.639 | 4.373 | 0.044 | 1000 | 4373.183
select name from V where type = 'song' limit 500 | 500 | 66.468 | 33234.237 | 15.045 | 0.030 | 1000 | 15044.726
select * from V where type = 'song' | 584 | 85.948 | 50193.442 | 11.635 | 0.020 | 1000 | 11634.986
select * from V where type = 'artist' limit 100 | 100 | 353.443 | 35344.267 | 2.829 | 0.028 | 1000 | 2829.313
select * from V where type = 'artist' limit 200 | 200 | 226.790 | 45358.027 | 4.409 | 0.022 | 1000 | 4409.363
select * from V where type = 'artist' | 224 | 200.577 | 44929.252 | 4.986 | 0.022 | 1000 | 4985.616
select distinct( type ) from V | 2 | 64.084 | 128.168 | 15.605 | 7.802 | 1000 | 15604.579
select name, $sungbyrecord as x_sungby from V let $sungby = outE()[ @class = 'sung_by' ], $sungbyrecord = list( (select in.name from $sungby ) ) where name='HEY BO DIDDLEY' | 1 | 1006.478 | 1006.478 | 0.994 | 0.994 | 1000 | 993.564

**Comment by mattaylor** [comment]
try without the subselect. Ie..

select name, $sungbyrecord, $sungby.in.name from V let $sungby = outE()[ @class = 'sung_by' ] where name='HEY BO DIDDLEY'


Sent from my Verizon Wireless 4G LTE smartphone

**Comment by mrft** [comment]
That's a different query.

What you propose would be similar to
<pre>
select name, $followedby.in.name, $followedby.in.performances,
from V 
let $followedby = outE()[ @class = 'followed_by' ]
where name='HEY BO DIDDLEY'
</pre>
which returns 2 lists, 1 for name, and one for performances

which is a completely different thing than
<pre>
select name, $followedbyrecord as followedbylist
from V 
let $followedby = outE()[ @class = 'followed_by' ],
	$followedbyrecord = list( (select in.name as name, in.performances as performances from $followedby) )
where name='HEY BO DIDDLEY'
</pre>
which returns 1 list with objects containing 2 properties.


I am not looking for alternative queries, I am trying to let the developers know where improvements could be made.

**Comment by mrft** [comment]
Another performance related question from someone else:
https://groups.google.com/forum/?pli=1#!topic/orient-database/LpG4kQSyqc8

**Comment by laa** [comment]
This issue is not specific , it is more like there are list of queries which are slow, there is no concrete query it is like aggregation of slow queries so I remove milestone from this issue.

**Comment by laa** [comment]
Also problem lies not in embedded version but n remote version so I assign @tglman to this issue.

**Comment by laa** [comment]
Hi, if this issue still actual please let us know otherwise we will close it.
