### ISSUE TITLE
Property changes not available for graph elements in onBeforeTxCommit

### ISSUE THREAD

**Issue by pangloss** [orientechnologies/orientdb#3048]
When updating a plain document, the changes are present, but for elements typed with V or E, they are not.

**Comment by lvca** [comment]
Do you have a test case for that? V and E are regular documents, so no special treatment is done at that level.

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
