### ISSUE TITLE
JDK1.8 json format

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#3051]
Follow up issue  : https://github.com/orientechnologies/orientdb/pull/2983

create function toJSON, 

toJSON :
<code>
try {
  return JSON.parse("{\"@rid\":\"#51:2051\"}");
} catch(e) {
}
</code>
Runing under JDK1.7
[
    {
        "@rid": "#51:2051"
    }
]

Runing under JDK1.8 
[
    {
        "@type": "d",
        "@version": 0,
        "value": {
            "@rid": "#51:2051"
        }
    }
]

**Comment by mattaylor** [comment]
Please can we get this reopened or a new ticket created to implement luigis proposals.

**Comment by vertex-github** [comment]
I like the "same for all results" approach - keeping things consistent between results with regards to the envelope makes it easier for developers to understand/diagnose/inspect values.

**Comment by mattaylor** [comment]
Luigi's proposal gives developers the option for implementing whatever response structure you like. The existing envelop approach does not and also creates major and un resolvable inconsitencies between functions which return db.queries and functions which return custom built lists.

**Comment by mattaylor** [comment]
In order to minimise back compatability issues, can we add a flag on Ofunction to signal how to serialise the function response. if this flag is missing then the old style is used, if the flag is there then the new style should be used. We could also havea global default properties as to whether new functions should use this flag by default, and also whether or not it should forced on existing functions as well.

**Comment by optimuspaul** [comment]
I was trying my hand at javascript functions in orient and let me just say I am majorly disappointed. I want to do something simple like load some results and inspect their properties. I can't figure out how to do that. It appears that if I look at a record in the JS function it's completely empty. However if I return it from the function it's all filled out with data, WTF?  Also in the Studio testing functions that do things like queries across edges I don't get anything back, yet calling the same function with the same param on the rest api I get data, WTF? Consistency would be nice, but it seems you are consistent about one thing, being inconsistent.

**Comment by lvca** [comment]
@optimuspaul it's hard to help you without any example... Could you provide what is working via REST and not in Studio? Something I can copy & paste on an empty db.

**Comment by optimuspaul** [comment]
@lvca of course you are right. Here is an example:
I have two vertex classes, `eos_object` and `eos_fingerprint`.

make some stuff
```
create vertex eos_object content {"uid": "2424"}
create vertex eos_fingerprint content {"fingerprint": "aaa"}
create edge E from #12:4 to #13:5  --- of course make those id's match yours.
```

I have a function `object_ping`, with one parameter `fingerprint`

```
var gdb = orient.getGraph();
try {
  return gdb.command("sql", 'select uid, @rid as rid, out(eos_fingerprint).@rid as out_rid, out(eos_fingerprint).fingerprint as fingerprint from eos_object where out(eos_fingerprint)[fingerprint] IN ?', [fingerprint]);
} catch(e) {
  return {"status": "ERROR", "error": e.toString()};
}
```

in the studio, on the function page, when I test the function with "aaa" as the fingerprint to check I get 0 results. But on the rest API I get:

```
{
"result": [
{
"@type": "d",
"@rid": "#-2:0",
"@version": 0,
"uid": "2424",
"rid": "#12:4",
"out_rid": [
"#13:5"
],
"fingerprint": [
"aaa"
],
"@fieldTypes": "rid=x,out_rid=z"
}
]
}
```

When I run `select object_ping("aaa")` in the browse tab I do get:
```
[{"@type":"d","@rid":"#-2:0","@version":0,"uid":"2424","rid":"#12:4","out_rid":["#13:5"],"fingerprint":["aaa"],"@fieldTypes":"rid=x,out_rid=z"}]
```
 Which does't seem quite right, is that json? Why didn't it make it look like other results?
