### ISSUE TITLE
OClass getBase functions are confusing 

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3060]
the functions OClass.getBaseClasses() and OClass.getAllBaseClasses() return the **derived** classes of the given OClass object, not the base classes.

Also it would also be nice if there were some docs describing the difference in these 2 functions.

**Comment by lvca** [comment]
I agree, the name should be getDerivedClasses().

**Comment by lvca** [comment]
@luigidellaquila this was the issue I was talking about. Closing it...

**Comment by luigidellaquila** [comment]
Thanks!

2015-03-05 20:36 GMT+01:00 Luca Garulli <notifications@github.com>:

**Comment by 8forty** [comment]
What is the difference between the new functions getSubclasses() and getAllSubclasses()?  Might be a good idea to add javadoc telling the diff.

**Comment by luigidellaquila** [comment]
The difference is that getSubclasses() returns only direct subclasses, while getAllSubclasses() returns all the subclasses tree.
Reopening to update Javadoc

**Comment by luigidellaquila** [comment]
done
