### ISSUE TITLE
Clusters of the edge class

### ISSUE THREAD

**Issue by alexspirtmsu** [orientechnologies/orientdb#3066]
I am testing OrientDB-2.0-M2 with python driver: pyorient.
Server is running in single mode (non-distributed). 
I created edge class with round-robin strategy. It consists of 32 clusters.
After some inserts (about 10 millions) (create edge myedge from #..... to #.....) I have only 8 clusters containing records. Other clusters are empty.
But when I use vertex class all clusters contain data.
Are there any limitations on the amount of edge clusters and why are 24 clusters empty?

**Comment by lvca** [comment]
Please could you write here the output of the command:

orientdb> info class myedge

**Comment by lvca** [comment]
Close for inactivity.
