### ISSUE TITLE
WARN [OVariableParser.resolveVariables] Error on resolving property: distributed

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb#3073]
Well I cannot really say why I get this WARN. Every time when I start the OrientDB server.

http://i.imgur.com/RBfsWk4.png

Is this a warning or an error. The message is a bit strange I think.

If it's a WARN only. Could you maybe rename error to **issue**. Would really help to see that it can be easily ignored.

Just cosmetic I think, so low prio. =)

**Comment by likemusic** [comment]
Have the same message when start OrientDB Community v2.1.12 on Win7 Ultimate with jre1.8.0_73:

> INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]

After I'm install jdk1.8.0_74 and still have this message on start server by bin/server.bat.

What means this message? Do I need fix this error? How I can do it?

**Comment by likemusic** [comment]
On [2-nd Udemy Getting Started course](https://www.udemy.com/orientdb-getting-started/learn/#/lecture/1726182) in video on 04:17 position, when demonstrated install and run OriendDb server on Windows 7 this message is also present.

Therefore, I think, most likely this error is not critical and does not require fix.
