### ISSUE TITLE
Distributed databases out of sync

### ISSUE THREAD

**Issue by tamassoltesz** [orientechnologies/orientdb#3090]
We have created a setup of three nodes with orientDB 2-M3. The three servers are using the same configuration.The problem is that out of the three servers only are two in synchron with each other. 
We name the nodes as orientDBMain, orientDBNode1, orientDBNode2. (Note that the naming are from an initial misunderstanding regarding the architecture. It's cleared up..)
So, let's say we have a database called "test". The database is created manually on one of the nodes, and it's copied by the DB to all of the nodes. After it we create a class, called "TestClass". This is visible on two nodes (on one which we created, the 'Main', and on the 'Node2'. On Node2 it's deployed by the orientDB.) The 'Node1' node get's the message, but it seems it's stuck.

Here is the part of the log from which I think the messages are stuck:

> 2014-11-21 16:15:14:783 INFO  [orientDBNode1] installed database 'test' [OHazelcastPlugin]
> 2014-11-21 16:15:14:785 WARNING [orientDBNode1] found 2 messages in queue orientdb.node.orientDBNode1.test.request, aligning the database... [OHazelcastDistributedMessageService]
> 2014-11-21 16:15:14:984 INFO  [orientDBNode1] Installing distributed storage on database 'test' [ODistributedStorage]
> 2014-11-21 16:15:15:902 INFO  [orientDBNode1]<-[orientDBNode2] received updated status orientDBNode2.test=ONLINE [OHazelcastPlugin]

The other thing, If we create instances for this TestClass let's say on the 'Main' and then we query them, 
a) on main we get back the instances we created
b) on Node2 we don't
Why is that? Are we missing something? 

If you need any more information please let me know!

**Comment by alonsod86** [comment]
This exact same thing is happening to me. Some times, when the cluster tries to sync it fails due to this error parsing a query. That error must be a bug in the sync process that has not been resolved in 2.1.2 release yet. I am unable to use the distributed version of Orient because of many many errors like this.

**Comment by lvca** [comment]
@alonsod86 do you have any log?
