### ISSUE TITLE
Comments on https://github.com/orientechnologies/orientdb/wiki/Download

### ISSUE THREAD

**Issue by lichtin** [orientechnologies/orientdb#3097]
Looking at https://github.com/orientechnologies/orientdb/wiki/Download
I've three minor points:

- it's not necessary to add the "maven-bundle-plugin" to the pom.xml.
   (it's only required if you want to _build_ OSGi bundles).
- it's not necessary to specify <type>bundle</type> when refering to the artifacts.
- there's no need to explicitly depend on orient-commons, as orientdb-core already does

**Comment by luigidellaquila** [comment]
Old issue (no longer valid)

Closing

Thanks

Luigi
