### ISSUE TITLE
"delete from" significantly slows down database inserts

### ISSUE THREAD

**Issue by gemmell** [orientechnologies/orientdb#3100]
Created this ticket as a result of a google group thread: https://groups.google.com/forum/#!topic/orient-database/laAWCeqV28g

Essentially once you do a "drop from Element" inserts slow to a crawl. Here's a further description with some code from the thread:
After creating the database from scratch and inserting 15K records a few times, it works pretty quickly (around 2s/15K with a unique index on Element.id).
I then run "delete from Element" from the web console and try again.  Now the inserts are taking close to 20s per 15K and the only way to fix it is to drop and create the database.

Thanks!

PS I'm using this very simple insert script for a single class Element:

ODatabaseDocumentTx db = ODatabaseDocumentPool.global().acquire("remote:localhost/IceTest", "root", "password");
            try {
                db.begin();
                db.declareIntent(new OIntentMassiveInsert());
                Date now = new Date();
                long last = System.currentTimeMillis();
                for (int i = 0; i < 15000; i++) {
                    ODocument el = db.newInstance("Element");
                    el.field("dateCreated", now);
                    el.field("lastEdited", now);
                    el.field("id", UUID.randomUUID().toString());
                    el.save();
                }
                db.commit();
                System.out.println(System.currentTimeMillis() - last);
            } finally {
                db.close();

**Comment by stuartcarnie** [comment]
This is a concerning issue – wouldn't this happen on a regular production database with lots of inserts and deletes?

**Comment by doppelrittberger** [comment]
Any updates on this issues? This is also very important for the usage in my project...

**Comment by laa** [comment]
Hi,
It will be part of new transaction design so we plan solution for this
issue till the end of the year.

**Comment by laa** [comment]
duplication of https://github.com/orientechnologies/orientdb/issues/5267
