### ISSUE TITLE
unable to index embeddedlist property having linked type embeddedmap or linked class

### ISSUE THREAD

**Issue by nlac** [orientechnologies/orientdb#3101]
Hi, i'm wondering if it is possible to achieve any type of indexing on the "rules2" and "rules3" properties in the example below... as you may see i'm getting exceptions for these ones:

``` sql
CREATE CLASS Organization EXTENDS V
CREATE CLASS Permission EXTENDS V

CREATE PROPERTY Organization.rules2 EMBEDDEDLIST EMBEDDEDMAP
CREATE INDEX idx_org_rules2 ON Organization (rules2) NOTUNIQUE
```

Response:
com.orientechnologies.orient.core.index.OIndexException: Cannot create the index 'idx_org_rules2'
 --> com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Error creation of sbtree with nameidx_org_rules2
 --> java.lang.NullPointerException

``` sql
CREATE PROPERTY Organization.rules3 EMBEDDEDLIST Permission
CREATE INDEX idx_org_rules3 ON Organization (rules3) NOTUNIQUE
```

Response:
com.orientechnologies.orient.core.index.OIndexException: Linked type was not provided. You should provide linked type for embedded collections that are going to be indexed.

**Comment by mjmeyer** [comment]
Notice that this is marked duplicate but cant seem to find what it is considered dupe of.

Is it still the case that we cant index embedded Lists as of 2.0.6?
