### ISSUE TITLE
OrientGraph.query() does not leverage indices.

### ISSUE THREAD

**Issue by uiterlix** [orientechnologies/orientdb#3103]
Version: Orient 2.0M3
OrientGraph.query() does not leverage indices.

DefaultGraphQueryIterable.getElementIterable checks the HasContainers against the key indices. The key indicates are retrieved using getIndexedKeys(elementClass) which calls getIndexedKeys(elementClass) on OrientGraphQueryIterable. This call is as follows: ((OrientBaseGraph) graph).getIndexedKeys(elementClass, true);

The 'true' indicates the classname should be returned as part of the key. These keys are matches against the HasContainers.key which does not have the classname as part of the key, so there's never a match which results in a graph.getVertices() instead of return graph.getVertices(container.key, container.value).

**Comment by philmes** [comment]
Hi,

this seems to be broken in 2.0.4 again - the fix for this issue was reverted. Can we have an update please?
