### ISSUE TITLE
Close files in disk cache if they are not used any more

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#3111]
We need to close files if we do not have pages of them in both disk read and write cache and if amount of open files reached limit of open files.  It seems like the most fast approach is usage of com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache#filePages state.
If limit of open files is reached we find files with zero amount of pages in cache or if such ones do not exist, files with smallest amount of pages are closed. If limit of open files is reached amount of closed files is calculated using following approach:
1. All files which do not have associated pages in cache are closed, without exception.
2. If limit of files which should be closed is not reached, files with smallest amount of pages are closed till limit is reached.

**Comment by laa** [comment]
I will introduce first checked exception inside of OrientDB , OFileClosedException. It is needed because files now are closed automatically it they are not used for a long time.

**Comment by laa** [comment]
ETA for this issue is 3 days, so it will be fixed at 6-th of Mat (holidays are taken in account).

**Comment by laa** [comment]
I do suggest to move it to 2.2 version. Too much of changes for rc version.
Also this fix is not urgent at all.

**Comment by lvca** [comment]
:+1: Let's discuss in the private group chat what's missing for 2.1-rc2

**Comment by laa** [comment]
too much of effort better to manage open storages through lru list and close least recently used one.
