### ISSUE TITLE
Little Bobby Tables

### ISSUE THREAD

**Issue by stebbi** [orientechnologies/orientdb#3119]
I inadvertently executed

    alter class MyOldClassName name = 'MyNewClassName'

in the web interface. Much to my dismay I now have a class named

    = 'MyNewClassName'

An error would have been more friendly. 

A fix for this would be great. A helpful comment about correctly escaping the space would be even more great. So far I've tried

    alter class = 'MyNewClassName' name=MyNewClassName
    alter class =\\ \\'MyNewClassName\\' name=MyNewClassName
    alter class =\ \'MyNewClassName\\' name=MyNewClassName

but none of these work.

**Comment by lvca** [comment]
Characters "=", ";" and "@" are not allowed anymore.
