### ISSUE TITLE
prepared query not accepting parameterized record id (Java API)

### ISSUE THREAD

**Issue by rjackson64840** [orientechnologies/orientdb#3122]
This is for 2.0-M3

Given some document that contains a list of linked address objects (field = addresses),

The following query:
```java
String query = "select count(*) from (traverse addresses from :id while $depth <= 1) where city = :attr";
```
when executed as follows:
```java
        List<ODocument> result = getDb()
.command(new OSQLSynchQuery<ODocument>(query))
.execute(DaoUtil.params("id", DaoUtil.getRecordId(id), "attr", value));
```
Results in the following exception:
```java
com.orientechnologies.orient.core.exception.OCommandExecutionException: Class ':ID' was not found in current database
```

The expectation would be that the target of the 'from', when 'from' represents a particular document, should accept a parameter so that the record ID can be injected into the query.

Note: DaoUtil.getRecordId() converts a string to an ORecordId object

**Comment by luigidellaquila** [comment]
This was fixed in 2.1.
Closing
