### ISSUE TITLE
Default users with default passwords are a security hazard

### ISSUE THREAD

**Issue by usmanismail** [orientechnologies/orientdb#3126]
Every time a new database is created the default users are added to the database. This is a security hazard people will often forget to change the passwords and leave the defaults there. We should either use random default passwords, force user to create passwords for reader writers or not create the users automatically.

**Comment by lvca** [comment]
I agree 1) o 2) could be good. OrientDB can be used not only behind the server, but also directly though "plocal" protocol and any JVM languages. For this reason at least "admin" database user it's needed. But I agree the create database should ask for the password. On console, if not provided, a password is asked. WDYT?

**Comment by compensator** [comment]
While you're addressing this, what are the access controls on non-admin users related to user listing, etc.  Only a user in the admin role should be able to list users.

Another item is the "guest/guest" user that is used by the Studio.  This should be system/system, or something other than guest and the guest user is able to login via the console and list databases.  This user should be somehow buried in your system in a manner that removes it from the attack surface.

**Comment by lvca** [comment]
@compensator In 2.2 accessing even in READ mode to OUSer and ORole classes/clusters is forbidden. Only "admin" can do that on fresh databases.

About guest user, it's there only for `/listDatabase` command executed in Studio (you can still disable it in orientdb-server-config.xml).

**Comment by compensator** [comment]
That's the mitigation we suggested to the customer during our evaluation.  I haven't tested it yet, so I don't know what appears on the login page when guest is disabled.

**Comment by laa** [comment]
Moved to 3.0 because of big effort is need to fix it.

**Comment by mamoit** [comment]
:+1: the server guest with the listing permissions on the studio really creeps me out.
