### ISSUE TITLE
getVertexByKey does not work.

### ISSUE THREAD

**Issue by syshex** [orientechnologies/orientdb#3128]
This was already reported at google group : https://groups.google.com/forum/#!topic/orient-database/WTOQrG2kzpA

Apparently `getVertexByKey` does not work for searching in indexes or at least it is not working in the way that I am using it. Maybe it is only supposed to be used with Index with specific constraints ( like UNIQUE ) or something, but nothing like this is stated on the javadocs. 

I found this problem this way : 

1-  create the following Vertex type and index :

    OrientGraphNoTx graph = factory.getNoTx();
    graph.createVertexType("Government");
    graph.createKeyIndex("itemid", Vertex.class, new Parameter<>("class", "Government"));
    graph.createKeyIndex("nif", Vertex.class, new Parameter<>("class", "Government"));
    graph.commit();

2- go on to create a Vertex of that type :

    OrientGraph graph = factory.getTx();
    Vertex node = graph.addVertex("class:Government");
    node.setProperty("itemid", 45);
    node.setProperty("nif", "1234567890");
    node.setProperty("description", "Somewhere");
    graph.commit() ;

3- Search for it:

    Vertex exists = graph2.getVertexByKey("Government.itemid", 45);

exists at this point will be null. 

I'm running 2.0-M3 on linux and the following dependencies :

    "com.orientechnologies" % "orientdb-client" % "2.0-M3",
    "com.orientechnologies" % "orientdb-enterprise" % "2.0-M3",
    "com.orientechnologies" % "orient-commons" % "2.0-M1",
    "com.orientechnologies" % "orientdb-core" % "2.0-M3",
    "com.orientechnologies" % "orientdb-graphdb" % "2.0-M3",
    "com.tinkerpop.blueprints" % "blueprints-core" % "2.6.0",

I have also provided a test case source code class on the google group thread that shows this problem.

**Comment by lvca** [comment]
No answer after long time, closing.
