### ISSUE TITLE
SQL increment column

### ISSUE THREAD

**Issue by fabriziofortino** [orientechnologies/orientdb#3145]
The syntax to increment the value of a column in OrientDB is:

`UPDATE myclass INCREMENT column = 1`

The standard SQL to do the same is:

`UPDATE myclass SET column = column + 1`

Would it be possible to extend/change this to have the SQL standard notation?

**Comment by luigidellaquila** [comment]
Already implemented in v 3.0.0 M2

Closing

Thanks

Luigi
