### ISSUE TITLE
NPE in collate case insensitive index creation

### ISSUE THREAD

**Issue by carlopolisini** [orientechnologies/orientdb#3152]
OrientDB version is **1.7.8**
The field which needs to be indexed is a String. The purpose is to be able to perform a case insensitive ordering.
Running the following command on the command console I get a **null pointer exception**:

    orientdb {testdb}>  CREATE INDEX productbyTitle on Product (title COLLATE CI) notunique

    Creating index...
    Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.create INDEX productbyTitle on Product (title COLLATE CI) notunique

    Error: java.lang.NullPointerException

**Comment by lvca** [comment]
I think this has been already resolved in 2.0

**Comment by lvca** [comment]
Fixed in 564faebeb5c92127c8bcad6eca475c39df582a64
