### ISSUE TITLE
Returning a JS object in a function work incorrectly

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3154]
From: https://github.com/orientechnologies/orientdb-studio/issues/209

returning a javascript object from a server side function does not work properly (or displays output improperly). See image attached, it breaks the properties of the object into their own object.

![screen shot 2014-12-02 at 9 26 21 pm](https://cloud.githubusercontent.com/assets/2651311/5274921/1d71dae4-7a6a-11e4-8429-d168874737f9.png)

**Comment by luigidellaquila** [comment]
fixed a long time ago. Cannot be reproduced in 2.1
