### ISSUE TITLE
Token: Add documentation and tests

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3155]
Linked to: https://github.com/orientechnologies/orientdb/issues/2229

**Comment by mattaylor** [comment]
Can we get some clarity on the status of this access_token feature. 

From #2229 it seemed like this should now be available in 2.0, however when I try

```
curl --data "grant_type=password&username=admin&password=admin" http://localhost:2480/token/myDb
```

As per comments in #2229  I just get a NPE returned.

**Comment by lvca** [comment]
@tglman please could you help on this?

**Comment by mattaylor** [comment]
I figured this out - needed to update the config to  'enable' token auth and set the oauth2 key.

**Comment by smolinari** [comment]
I am also having difficulty with the token system. Can someone elaborate a bit more on how to go about turning it on and what is needed from the client side, so it works properly? When I set the plugin parameter "enabled" to true, it breaks ODB, as in, it won't start at all.

Scott

**Comment by a-unite** [comment]
That is, as well as JS dirver's support for this feature are quite important for us also.
Is there any chance to shed more light and attention on this functionality?

**Comment by smolinari** [comment]
I found out that you have to add an oAuth key to the settings. Then the token system started to work properly. Silly me, actually, to think it would work without it. But for sure, this needs documentation for all the other silly people like me. :blush: 

Scott

**Comment by a-unite** [comment]
Dear Scott, thank you!

I'm aware of that setting, but there are more questions than that. 

I'd like to know, how this could help to utilize connections (why do we need integer session ID anyway, as described here http://orientdb.com/docs/last/Network-Binary-Protocol.html#Session-Id), what is the best practice to expire/renew and revoke the token (do we have some easy mechanism to change expiration field), and, particularly, clear explanations on how it should work with OrientJS/binary protocol.

Coming here from https://github.com/orientechnologies/orientdb/issues/2229 and I believe original discussion had more information on this issue, than any other ODB resource yet.

**Comment by smolinari** [comment]
To be honest, I personally wouldn't use the database authentication for application authentication, which it sounds like what you are wanting to do. You don't expire, renew, revoke the token, but rather ODB does this. The token is simply a method to allow a faster validation of the incoming inquiry from the database's perspective for the client you are using. You'll still need this at application level too. 

Well, that is how I understand this. I might be completely wrong too. LOL! :smile: 

Scott

**Comment by tglman** [comment]
@a-unite the Session-Id in case of the token it's only needed for match a response to a request, it could happen that while you are waiting for an answer on a connection you receive a push request, and you can understand the difference using the Session-Id.

The token was designed to Support the application user as database user, but the expire of the token is only based on time, and the renew is automatic if you  do a request after the half of the session length. 

The only other way to revoke a token is change the key, but this will cause the revoke of all the tokens.

**Comment by smolinari** [comment]
So, in other words, and as the other discussion pointed out, this token system is not flexible enough to be a software user authentication system. 

Scott

**Comment by emrul** [comment]
@smolinari I'm the original contributor of the token authentication system.  The system is very flexible but would require some additional development if you want things like revoking tokens, etc.  The JWT format contains a 'jti' property for this purpose but crucially provides no guidance on how implementers should make use of this.

There are many ways to handle revoking tokens.  For our use case we've created a separate app that serves tokens with a short expiry and forces clients to refresh their tokens frequently.  An alternative approach will be to maintain a list of issued tokens in the database along with whether they're revoked and to check this on each request (obvious incurs a performance hit which we weren't willing to accept).

I haven't seen the latest code @tglman has been working on but the system is modular and designed specifically for users to be able to customise how a token is handled within ODB.

**Comment by a-unite** [comment]
@tglman, @emrul,
thank you!
We've been watching for token idea from the start, and now there is definitely more information (documentation) needed.
Will try to learn more on how to refresh token with OrientJS driver, it was not obvious last time we've tried.
Thanks

**Comment by a-unite** [comment]
Dear team, are there any news on that feature?
Will this be production ready in v2.2?
Any updates on documentation and drivers?

**Comment by lvca** [comment]
Tests are completed, I don't know @tglman if the docs have been updated too. Any news?

**Comment by bradhilton** [comment]
Is there any documentation available for this feature yet? Very interested in seeing this prod ready.

**Comment by tglman** [comment]
hi,

The documentation on how to use the token is online, that is enough for a correct use of the token, closing.

Regards
