### ISSUE TITLE
Different results with first(out()) operators

### ISSUE THREAD

**Issue by MarcelPitch** [orientechnologies/orientdb#3168]
Hi,

I'm working with 2.0 M3.

I have a graph like this :

![first out](https://cloud.githubusercontent.com/assets/7402969/5391528/715ddb18-811c-11e4-8ae2-b9c3c7afce96.PNG)

I have different results for a query, depending on the syntax used.

I'd get the first `VertexTwo`, linked by `EdgeOne` to the `VertexOne` where uuid = 3.

I wrote the request like this :

``` sql
SELECT 
    $myVar
FROM 
    VertexOne
WHERE
    uuid = 3
LET 
    $myVar = first(out('EdgeOne'))
```

**RESULT** : I get the `#11:0` Vertex. Wrong ...

---

But when I wrote the request like this :

``` sql
SELECT 
    $myVar
FROM 
    #10:1
LET 
    $myVar = first(out('EdgeOne'))
```

**RESULT** : I get the `#11:1` Vertex. Right !!!

---

And now, when I wrote the request like this :

``` sql
SELECT 
    first($myVar)
FROM 
    VertexOne
WHERE
    uuid = 3
LET 
    $myVar = out('EdgeOne')
```

**RESULT** : I get the `#11:1` Vertex. Right !!!

---

And now, when I wrote the request like that :

``` sql
SELECT 
    $myVar
FROM 
(
    SELECT
    FROM
        VertexOne
    WHERE
        uuid = 3
)
LET 
    $myVar = first(out('EdgeOne'))
```

**RESULT** : I get the `#11:1` Vertex. Right !!!

---

I did the test on 2.0 M2, and same result.

I don't know if it's an anomaly or just a misunderstanding with orient SQL synthax.
I thought I wrote the same request but in different way.

Thank you and have a nice day !

**Comment by luigidellaquila** [comment]
@lvca I don't get how this has to be fixed...
If the original behavior has to be preserved, then the index has to be ignored every time there is a LET. I don't like this very much.

IMHO this can be managed in a consistent way only in one of the following:
1. breaking backward compatibility
2. defining another function for that

**Comment by lvca** [comment]
@luigidellaquila what's your proposal for 1 and 2?
