### ISSUE TITLE
Sequence of data in REQUEST_RECORD_LOAD

### ISSUE THREAD

**Issue by mindplay-dk** [orientechnologies/orientdb#3175]
The response format of `REQUEST_RECORD_LOAD` makes it impossible for a client to load the entire response sequentially:

```
[(payload-status:byte)[(record-content:bytes)(record-version:int)(record-type:byte)]*]+
```

In order to read sequentially over the entire response, the client needs to know the `record-type` in advance, so the order of this data appears to be backwards currently.

I believe the record format of each payload chunk would need to change, placing the payload metadata `record-type` and `record-version` ahead of `record-content`, e.g.:

```
[(payload-status:byte)[(record-type:byte)(record-version:int)(record-content:bytes)]*]+
```

With the new binary serialization format, which doesn't require parsing, client implementations could then be made simpler and more memory-efficient, if they didn't need to load/buffer `record-content` in-memory before interpreting the data.

I would be extremely glad to see this change made to the protocol before the final 2.0 release, as I am implementing a client that targets 2.0+ exclusively.

**Comment by mindplay-dk** [comment]
On a related note, while working on a binary driver, I discovered this change will not in fact enable a binary client to read through the data stream sequentially.

The issue here, is the binary serialization format, for which the documentation is incomplete - I had to discover (by reading the source code) what negative values for `length` means, that it is not in fact a length, but a property in the schema.

The concept of "global properties" isn't defined in the documentation at all, and there is no explanation on how to find them - I had to discover (also by reading the source code) that you need to do another round-trip doing an SQL select from schema:metadata, another undocumented feature.

The problem is, there is no way a client can know about the necessary schema in advance - hence, still no way to read sequentially through the serialized document. You have to buffer it in-memory, then do another round-trip to obtain the schema, before you can deserialize.

Possible solution: every change to the schema could result in an updated hash of the whole schema. Clients could then cache the schema, and specify the hash of the schema they have cached locally, when they connect - so that the server would know if the client has the latest schema or not, and could supply it up front, at connection-time. It makes sense, I think? Seeing as how the client cannot deserialize records without the schema information - in fact, it probably doesn't make much sense to connect without this information? Every client currently needs to send the query for the scheme metadata upon connecting anyway - there's no reason this needs to be optional, is there?

If you're concerned about large schema with frequent changes, I would suggest including both a hash and a serial number for schema changes - every change to a class/cluster/property would increase the serial number, and the serial number would be attached to the schema entity that was updated/added. This would enable the server to send incremental schema changes to the clients.

Thoughts?

**Comment by tglman** [comment]
@mindplay-dk 
One point is that we are seriusly thinking to remove the global ploperty id from network serialization, this will have a small overhead in terms of bandwidth, but for some client implemetation(like php) would be much easier.

Sorry for the not updated documentation that's my fault going to fix that now.

for the schema push we have a plan for do it but not design done till now, your idea si not bad.

**Comment by mindplay-dk** [comment]
> we are seriusly thinking to remove the global ploperty id from network serialization

If I'm frequently fetching small records with (say) lots of integer fields, the metadata could outweigh the actual data in volume.

I would strongly advice against that.

Adding schema-awareness to the client/server protocol sounds like a more natural and scalable (for all scenarios) approach, but it sounds like you like that idea as well.

**Comment by mindplay-dk** [comment]
(I would rather wait for a solid solution than have an interim or "patch" solution arriving sooner...)
