### ISSUE TITLE
Support deleted all incoming or outgoing edges from a vertex

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3185]
It would be nice if `delete edge from #RID` or `delete edge to #RID` were supported.

I'm not sure what the fastest way to delete outgoing edges at the moment.

**Comment by suyogdilipkale** [comment]
If I delete vertex, does it take care of deleting all in/out edges? If not then what else is recommend approach? 
delete edge from #vertex, delete edge to #vertex , delete vertex #vertex

**Comment by luigidellaquila** [comment]
Hi @suyogdilipkale 

Yes, if you delete a vertex, OrientDB will also remove all the connected edges

Thanks

Luigi

**Comment by suyogdilipkale** [comment]
OK thank you.

I have one more query, how we can write upsert query for edge that if it
not exist then insert or else just update. Please provide me sample example.
