### ISSUE TITLE
Mass insertion of edges slows down over time

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3191]
Running a script that inserts millions of edges starts of fast and then slows down to crawl (1 edge/second) after hours. Disk I/O is goes down though CPU use is normal. If I restart the server, it exits fairly quickly as normal. I can immediately restart the server and resume the import script, and edges are added very quickly again. I'm not seeing leaks in the import script (it would just OOM if the heap was >256MB) itself.

Heap is 2GB, and diskcache is 8GB. I'm using concurrent Mark-Sweep GC if that matters. Note that some edges have indexes. I also have  -Dstorage.wal.syncOnPageFlush=false set.

I didn't have this problem in 1.7.10, and I'm not sure how to work around it other than restarting things every few hours. Are there any known issues that make this problem likely? Would disabling the level1 cache help?

**Comment by laa** [comment]
Cool. Actually it was fixed yesterday by https://github.com/orientechnologies/orientdb/commit/d899c284366b9d6892e63b67ed5858874c5e5770  . Unneeded timer thread hold implicit link to connection level cache. That is why we had those objects in heap. Could you try now. Sorry for such long fix.

**Comment by laa** [comment]
Hi,
Are there any updates on this ?

**Comment by lvca** [comment]
Yes, the TimerTask let the cache to be strongly reachable. In @AaronSchulz screenshots I didn't see many DB instances neither OLocalRecordCache instances. So I think this is fixed. @AaronSchulz any chance to reproduce it again?

**Comment by AaronSchulz** [comment]
I'll rebuild the DB again to see.

**Comment by AaronSchulz** [comment]
Seems to be fixed after running for many hours.

**Comment by maxxiej** [comment]
Hi! I am encountering a similar issue while loading a dataset of 25GB size. On the server.sh I keep getting messages like:

 Open server.sh (or server.bat on Windows) and change the following variables: 1) MAXHEAP=-Xmx807M 2) MAXDISKCACHE=4656 [OAbstractProfiler$MemoryChecker]

I have set already MAXHEAP=-Xmx2g and running th upload with the arguments:
java -Xmx2g -Dcache.local.enabled=false -XX:+UseConcMarkSweepGC -XX:+PrintGCDetails 

Here are some of the last messages:
[GC[ParNew: 36096K->3968K(36096K), 0.0163810 secs] 42190K->12772K(116288K), 0.0164650 secs] [Times: user=0.04 sys=0.00, real=0.02 secs] 
[GC[ParNew: 36096K->2776K(36096K), 0.0047820 secs] 44900K->11843K(116288K), 0.0048630 secs] [Times: user=0.00 sys=0.00, real=0.00 secs] 
[GC[ParNew: 34904K->3968K(36096K), 0.0109770 secs] 43971K->13035K(116288K), 0.0110780 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
[GC[ParNew: 36096K->3968K(36096K), 0.0112370 secs] 45163K->13035K(116288K), 0.0113340 secs] [Times: user=0.01 sys=0.00, real=0.01 secs] 
[GC[ParNew: 36096K->1508K(36096K), 0.0022800 secs] 45163K->10575K(116288K), 0.0023660 secs] [Times: user=0.01 sys=0.00, real=0.00 secs] 
[GC[ParNew: 33636K->3404K(36096K), 0.0314820 secs] 42703K->12471K(116288K), 0.0315850 secs] [Times: user=0.03 sys=0.00, real=0.03 secs] 
[GC[ParNew: 35532K->2543K(36096K), 0.0048520 secs] 44599K->11610K(116288K), 0.0049520 secs] [Times: user=0.01 sys=0.00, real=0.00 secs] 
[GC[ParNew: 34671K->960K(36096K), 0.0026970 secs] 43738K->10027K(116288K), 0.0028810 secs] [Times: user=0.00 sys=0.00, real=0.00 secs] 
[GC[ParNew: 33088K->3285K(36096K), 0.0077140 secs] 42155K->12352K(116288K), 0.0077980 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
[GC[ParNew: 35413K->2394K(36096K), 0.0042610 secs] 44480K->11461K(116288K), 0.0043400 secs] [Times: user=0.01 sys=0.00, real=0.00 secs] 
[GC[ParNew: 34522K->3967K(36096K), 0.0097170 secs] 43589K->13195K(116288K), 0.0098000 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
[GC[ParNew: 36095K->3968K(36096K), 0.0183630 secs] 45323K->16629K(116288K), 0.0184630 secs] [Times: user=0.04 sys=0.00, real=0.02 secs] 
[GC[ParNew: 36096K->2914K(36096K), 0.0044000 secs] 48757K->15756K(116288K), 0.0044810 secs] [Times: user=0.01 sys=0.00, real=0.00 secs] 
[GC[ParNew: 35042K->3968K(36096K), 0.0089880 secs] 47884K->16840K(116288K), 0.0090670 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
[GC[ParNew: 36096K->3020K(36096K), 0.0061950 secs] 48968K->15905K(116288K), 0.0062910 secs] [Times: user=0.02 sys=0.00, real=0.00 secs] 
[GC[ParNew: 35148K->2481K(36096K), 0.0032050 secs] 48033K->15367K(116288K), 0.0032870 secs] [Times: user=0.00 sys=0.00, real=0.00 secs] 
[GC[ParNew: 34609K->3968K(36096K), 0.0085900 secs] 47495K->16854K(116288K), 0.0086750 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
[GC[ParNew: 36096K->2821K(36096K), 0.0054360 secs] 48982K->15708K(116288K), 0.0055200 secs] [Times: user=0.01 sys=0.00, real=0.00 secs] 
[GC[ParNew: 34949K->2195K(36096K), 0.0020930 secs] 47836K->15081K(116288K), 0.0021880 secs] [Times: user=0.01 sys=0.00, real=0.01 secs] 
[GC[ParNew: 34323K->3745K(36096K), 0.0094920 secs] 47209K->16631K(116288K), 0.0095750 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
[GC[ParNew: 35873K->2562K(36096K), 0.0063970 secs] 48759K->15448K(116288K), 0.0064770 secs] [Times: user=0.00 sys=0.00, real=0.01 secs] 
[GC[ParNew: 34690K->1924K(36096K), 0.0016270 secs] 47576K->14811K(116288K), 0.0017230 secs] [Times: user=0.00 sys=0.00, real=0.00 secs] 
[GC[ParNew: 34052K->3294K(36096K), 0.0077900 secs] 46939K->16181K(116288K), 0.0078880 secs] [Times: user=0.01 sys=0.00, real=0.01 secs] 
[GC[ParNew: 35422K->2410K(36096K), 0.0040580 secs] 48309K->15297K(116288K), 0.0041610 secs] [Times: user=0.01 sys=0.00, real=0.01 secs] 
[GC[ParNew: 34538K->3968K(36096K), 0.0091910 secs] 47425K->16955K(116288K), 0.0092730 secs] [Times: user=0.03 sys=0.00, real=0.01 secs] 
[GC[ParNew: 36096K->3968K(36096K), 0.0170090 secs] 49083K->20017K(116288K), 0.0171090 secs] [Times: user=0.04 sys=0.00, real=0.01 secs] 
[GC[ParNew: 36096K->2908K(36096K), 0.0048840 secs] 52145K->19153K(116288K), 0.0049630 secs] [Times: user=0.00 sys=0.00, real=0.00 secs] 
[GC[ParNew: 35036K->3968K(36096K), 0.0086970 secs] 51281K->20212K(116288K), 0.0087750 secs] [Times: user=0.02 sys=0.00, real=0.00 secs] 

Any idea what I can be doing better to ensure a faster upload?

**Comment by maxxiej** [comment]
It has been 34 hours since I started the upload of the 25gb data file and it seems less than half of it is loaded. Is this normal?

**Comment by laa** [comment]
Hi,
I have a question.
Did you reuse the same record during data insertion , or create new one
each time ?

On Tue, May 19, 2015 at 7:33 PM, maxxiej <notifications@github.com> wrote:

> It has been 34 hours since I started the upload of the 25gb data file and
> it seems less than half of it is loaded. Is this normal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3191#issuecomment-103581427>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by maxxiej** [comment]
I used different records each time.. the loading is being done using the SailLoader from tinkerpop.
https://github.com/tinkerpop/blueprints/blob/master/blueprints-graph-sail/src/main/java/com/tinkerpop/blueprints/oupls/sail/SailLoader.java

**Comment by laa** [comment]
HI,
Could you send me heap dump ,during massive insertion.

On Tue, May 19, 2015 at 10:25 PM, maxxiej <notifications@github.com> wrote:

> I used different records each time.. the loading is being done using the
> SailLoader from tinkerpop.
>
> https://github.com/tinkerpop/blueprints/blob/master/blueprints-graph-sail/src/main/java/com/tinkerpop/blueprints/oupls/sail/SailLoader.java
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3191#issuecomment-103642190>
> .
>



-- 
Best regards,
Andrey Lomakin.
