### ISSUE TITLE
Auto incrementing primary key

### ISSUE THREAD

**Issue by sanjaypavangp** [orientechnologies/orientdb#3196]
I'm trying to auto increment the id, which is the primary key, of my class when I insert a record to it.
But I see no option to do so.

**Comment by ArkeologeN** [comment]
If you're doing `increment ... ` then why `counter1 = 1`. I think that's kind of a invalid logical thing. The previously suggested method should be supported.

**Comment by uisuru** [comment]
https://orientdb.com/docs/2.0/orientdb.wiki/Sequences-and-auto-increment.html
