### ISSUE TITLE
Problems re-deploying on Tomcat 8 with OrientDB 2.0-M3 (similar to #2734)

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#3200]
Hi guys. 

I guess this issue is similar to #2734, however since the setup is different and that issue is closed i opened a new one.

Basically i have an IntelliJ 13 + Tomcat 8 + Spring 4.1.2 + OrientDB 2.0-M3. when I redeploy war file to the running instance of a Tomcat a bunch of errors regarding dangling threads is thrown in the log. After a few re-deployments Tomcat runs out of memory and becomes unresponsive, so now I am forced to restart server every time i need to re-deploy.

Here is the [GIST](https://gist.github.com/andreyvk/ae2e54a73c6d4feaec6e) which includes the pom file, the database factory that I use as a db provider bean and the log itself. Plz, let me know if i can provide anything else.

**Comment by mkalus** [comment]
I also have these problems with 2.0.6. Is there some kind of workaround or fix?

**Comment by n0lf** [comment]
We get the same error messages in glassfish 4.1 though the server actually seems to be able to kill threads over time so the memory leak is prevented.

**Comment by lvca** [comment]
The output is normal IMHO, because you shouldn't create any thread in webapps. However if you don't have any memory leak problem, you can ignore them.
