### ISSUE TITLE
Denormalization in the REST API

### ISSUE THREAD

**Issue by mindplay-dk** [orientechnologies/orientdb#3202]
How come e.g. LINKs are denormalized when using the REST API?

I would expect embedded documents to appear as embedded in their parent document, because they're value objects, not entities. But links? These are references to other entities. Only the reference itself (the key) is actually part of the parent aggregate - the entity itself is not. Why should it appear inside the entity as though it were an embedded value object?

And what about circular references? If you use the default fetch strategy, can you send the server into a circular tail spin? (How would you resolve circular references in a client?)

I was expecting a data format more along the lines of `REQUEST_RECORD_LOAD` in the binary API, e.g. with the returned records in a collection at the top of the response, and "prefetched" records (e.g. those retrieved via LINKS etc.) in a separate collection.

Is this "by design"?

Because it mostly defeats the purpose of fetch strategies, in my opinion.

With a relational database, we're forced to denormalize, if we want related data in a single roundtrip. Say, a list of customers with country names. We're forced to join customers with countries, which means that, for 100 customers in 3 countries, the server needs to encode and send the same 3 country names a total 100 times, and the client then needs to sort through and discard the duplicate data while mapping the results to objects.

With a document database, this should not be necessary - we should not need to denormalize, transfer, encode or decode the same entity more than once during a single round-trip.

Am I missing something obvious? Is there something fundamental about the REST API that I haven't understood yet?

**Comment by mindplay-dk** [comment]
Any thoughts on this? 

I'd like to use the REST API as a first step towards adopting OrientDB, but I don't want to write a client that expects this format, if it turns out this denormalization issue is indeed a blunder.

**Comment by mindplay-dk** [comment]
@lvca sorry to bump this, but if this requires a BC break, you'd probably want to get it into the 2.0 release? The REST API is not really usable to me as it is, I'm afraid - I'm pretty sure it needs to send the records from the root of the query separately from related records for pre-caching on the client? Same approach as in the binary client. But this is a breaking change to clients, perhaps so major that it should have a separate "/v2" in the REST URL for the new version?

I hope this issue at least gets reviewed before the 2.0 release.

**Comment by lvca** [comment]
@mindplay-dk This is by design: doesn't matter if you have document as embedded or linked, the resulting JSON is pretty the same. However I understand your needs, and we could slightly improve the API to avoid expanding linked documents. Is it enough?

**Comment by lvca** [comment]
@mindplay-dk This is by design: doesn't matter if you have document as embedded or linked, the resulting JSON is pretty the same. However I understand your needs, and we could slightly improve the API to avoid expanding linked documents. Is it enough?

**Comment by lvca** [comment]
@mindplay-dk This is by design: doesn't matter if you have document as embedded or linked, the resulting JSON is pretty the same. However I understand your needs, and we could slightly improve the API to avoid expanding linked documents. Is it enough?

**Comment by phpnode** [comment]
@lvca to do that whilst still supporting fetchplans will be a big BC break, better to switch to something which can accurately describe linked graphs in JSON, e.g. [JSON-LD](https://github.com/orientechnologies/orientdb/issues/2273) :)

**Comment by red-0ne** [comment]
I second @mindplay-dk on that. We also have problems with getting *entities* nested into a root one. As we frequently have to manipulate them as standalone objects that could be saved, and refreshed separately from the rest. We actually have to normalize them on query basis which is a very short-life solution.

Selects with fetchplan have this behaviour. @mindplay-dk, do you have other query types that behave this way?

**Comment by mindplay-dk** [comment]
> we could slightly improve the API to avoid expanding linked documents. Is it enough?

Doesn't really address the problem, as this would mean multiple subsequent round-trips to get related documents - we could already do something similar by just specifying a fetch-plan, so it doesn't help much, and as @phpnode pointed out, it's a major BC break.

The binary API has the right approach - applying that to the REST API, where the response is currently `{"result":[...]}` it needs to be e.g. `{"result":[...], "cache":[...]}`, and references need to be returned as RIDs rather than denormalized and embedded.

Switching to something like JSON-LD is probably a bigger operation than this? And not really necessary to address the problem of denormalization, in my opinion - circular references, for example, can be described just fine using RIDs, and Orient already internally executes fetch plans with circular references avoiding duplicates in pre-fetched records. The problem is addressed just fine by the binary API, I think - I hope to see the REST API more closely resembling that.

Of course, we are still talking about a major BC break either way, so this probably needs to be either a `/v2/` in the API URLs, or (minimally) a server-configurable setting to use the legacy protocol - unless you think it's OK to break BC in the upcoming major 2.0 release?

> We also have problems with getting entities nested into a root one

I hadn't even thought that far, but that is also an extremely valid point - when it comes to mapping records to entities on the client-side, I don't want entities aggregated inside entities in the first place, so on the client-side I'd have to disassemble what the REST server put together to restore the proper shape of the entities.

To use an example, in domain terms, the Country entity is not part of the Customer entity - only the Country RID is part of the Customer entity; this isn't strictly a form of denormalization, it's actually a case of of the shape of the data structure getting mangled by the server. It's also another way in which the REST API deviates from the binary API.

> Selects with fetchplan have this behaviour. @mindplay-dk, do you have other query types that behave this way?

Yes, fetch plans is what causes this issue - with the binary API, fetch plans are a killer feature that enable you to minimize the number of round-trips to the server; with the REST API unfortunately they have the side-effect of denormalization.

@lvca I suspect maybe the REST API was designed with the OrientDB admin tool in mind to begin with, at least initially? Embedding the results probably works fine for the admin tool, where data redundancy and bandwidth/CPU overhead isn't really a concern. I'm sure the admin tool relies heavily on the REST API in it's current form, so maybe a v2 REST protocol is the best approach, allowing the admin tool (and third-party applications) to continue working normally without any changes?

**Comment by phpnode** [comment]
> Switching to something like JSON-LD is probably a bigger operation than this?

Not really, it would be very straightforward.

>  in my opinion - circular references, for example, can be described just fine using RIDs

There are a *lot* of problems with the way RIDs currently work in the REST API, they're a potentially horrible security issue.

https://github.com/orientechnologies/orientdb/issues/3313
https://github.com/orientechnologies/orientdb/issues/2243
https://github.com/codemix/oriento/issues/184#issuecomment-68880072
https://github.com/nitrog7/node-orientdb/commit/c0bc2169bdd57883e0c0a39afbd2ccb671382c1b#commitcomment-5926663

**Comment by phpnode** [comment]
To make sure you get the point, here's the effect of equating strings with RIDs:
```sql
create class Wat extends V;
create vertex Wat set name = "hello world";
create vertex Wat set name = #5:0;
select from Wat fetchplan *:1; -- boom!
```

**Comment by mindplay-dk** [comment]
> There are a lot of problems with the way RIDs currently work in the REST API, they're a potentially horrible security issue

Yep, I see the problem there.

In my own work with JSON/REST, when dealing with de/serialization, I usually solve this problem by encoding object values as hashes with a reserved key, using a prefix such as `#` which can't collide with property-names in native objects; for example, I might encode a RID as `{"#RID":"10:2"}`.

Obviously, this would be another breaking change - I wonder if we're getting too far off track here?

**Comment by phpnode** [comment]
@mindplay-dk this is why I proposed JSON-LD, because it can express RIDs and the rest of the various data structures in a way that doesn't require that kind of edge case:

```json
{
  "@id": "#5:0",
  "@type": "db:OUser",
  "name": "admin",
  "status": "ACTIVE",
  "roles": {
    "@type": "orient:LinkSet",
    "@value": [
      {
       "@type": "orient:RID",
       "@value": "#4:0"
      }
     ]
  }
}
```

or similar

**Comment by red-0ne** [comment]
@phpnode, I think something like that is a must have and could be involved in a proper fix for this problem but it is not the at core of this issue.

According to @lvca, nesting entities is the the way to go which IMO is not. Of course getting this kind of (nested) structure is useful for short-lived result sets that generally exist to fulfil a one-time task (generally processing and/or display). But for long-lived entities we (most of the time) have to express a *graph state* where a node is the root one in a view and is a mere child in another one and where orientdb comes to expand and enrich such graphs through its powerful queries.

**Comment by phpnode** [comment]
@red-0ne it's very much related to this issue, otherwise Orient needs to invent some other way of indicating a list of "prefetched" records that are separate from the main result set, (some new special envelope in the JSON) and then you run into issues where a record could appear in the main result set *and* the list of prefetched records - it can get ugly very quickly. 

If the solution requires a BC break, why not fix the issue properly? Otherwise it's just hacks on top of hacks. 

This is how a list of 2 users, with their roles, could look in JSON-LD:
```json
{
  "@graph": [
    {
      "@type": "orient:Collection",
      "@value": [
        {
          "@type": "orient:RID",
          "@id": "db:#5:0"
        },
        {
          "@type": "orient:RID",
          "@id": "db:#5:1"
        }
      ]
    },
    {
      "@id": "db:#5:0",
      "@type": "db:OUser",
      "name": "admin",
      "status": "ACTIVE",
      "roles": {
        "@type": "orient:LinkSet",
        "@value": [
          {
           "@type": "orient:RID",
           "@id": "db:#4:0"
          }
         ]
      }
    },
    {
      "@id": "db:#5:1",
      "@type": "db:OUser",
      "name": "reader",
      "status": "ACTIVE",
      "roles": {
        "@type": "orient:LinkSet",
        "@value": [
          {
           "@type": "orient:RID",
           "@id": "db:#4:1"
          }
         ]
      }
    },
    {
      "@id": "db:#4:0",
      "@type": "db:ORole",
      "name": "admin"
    },
    {
      "@id": "db:#4:1",
      "@type": "db:ORole",
      "name": "reader"
    }
  ]
}

```

**Comment by red-0ne** [comment]
@phpnode, I agree, it is very related to this issue, but OrientDB team sould consider normalized result sets as the prime behaviour first (this is not what @lvca seems to think :/ ).

**Comment by lvca** [comment]
Guys, I like the idea from @mindplay-dk about supporting a result set as:

```json
{"result":[...], "cache":[...]}
```

Where in result objects are shallow and cache contains objects from fetch plan, like with binary protocol. Also the JSON-LD format is not bad, but it could be harder to implement unless we rewrite the serializer from scratch.

**Comment by phpnode** [comment]
@lvca let's pretend that `OUser` has a `LINK` field called `referrer`, it's a link to the person who referred that user to the application. Let's say that the admin user invited the reader user, so reader (`#5:1`) has a link to admin (`#5:0`). I then execute this query:
```sql
SELECT FROM OUser FETCHPLAN *:1
```
This will retrieve all the users and their roles, but it will also materialize the link between admin and reader. Where should that prefetched record go?

- If it goes in `result` but not in `cache` then the client must look in both lists every time it's resolving RID references.
- If it goes in both, the client must dedupe.


Both are quite ugly imho.

**Comment by mindplay-dk** [comment]
@phpnode I don't see a problem - the example you quoted would have everything in `result` and nothing in `cache`, since both records are part of the root of the result of your query.

Records at the root of any query goes in `result`, and other prefetched records go in `cache`, unless of course they are already in `result` - we never want duplicates, and we want all the records from the root of the query in `result`.

The main reason we need to separate the result from prefetched records, is because the order of the records in `result` is meaningful - whereas the order of additional records in `cache` is arbitrary. This is how the binary protocol and client works, as far as I understand.

> If it goes in `result` but not in `cache` then the client must look in both lists every time it's resolving RID references

That would never happen - it's not how binary clients work, and it's not how we should implement a REST client either, I think... assuming the REST protocol is changed to deliver results in the same way as the binary protocol.

A client would not look in either list when resolving RID references - instead, it would inject everything from `result` as well as from `cache` into it's own internal cache; resolving RID references afterwards requires one lookup in the client's own internal cache.

Perhaps the name `cache` is misleading - `prefetch` might be clearer? The actual "cache" is something the client maintains - additional records returned due to a fetch plan are just a way to obtain related records ahead of time so you can inject them into the client's internal cache.

Make sense?

**Comment by mindplay-dk** [comment]
@lvca any progress on this? I still feel that the REST API seems like it was designed for Studio's needs specifically, and a BC break is needed to bring it in line with the binary API. As it is, the REST API is still of no use to me in the real world - the denormalization issue is a roadblock preventing us from reaping the benefits of avoiding redundancy (vs RDBMS and JOINs) and optimizing with fetch plans - these features are key arguments for using OrientDB, but currently are not applicable to the REST interface...

**Comment by mindplay-dk** [comment]
You might want to consider [JSON-graph](http://netflix.github.io/falcor/documentation/jsongraph.html) for a version 2 of your JSON API.

I really, honestly keep sitting here, waiting for a grand announcement, that you're implementing a simple, usable, high-performance version 2.0 of the JSON API, which would be easy to adopt and support everywhere.

**Comment by red-0ne** [comment]
@mindplay-dk, we have exactly the same needs and I agree with you on everything (denormalization, binary/rest api alignment,  fetchplan consistency). We are waiting for a move on that direction too.

**Comment by jcwright77** [comment]
Just a me too here, would like to see a minimal consistent REST API that allows for creation of all objects/properties and has a uniform JSON payload for both GET and POST operations.
