### ISSUE TITLE
Hash indexes aren't used for IN with composite indexes

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3204]
In spite of an (iid,val) hash index, the following query is very slow:

orientdb {db=WikiData}> explain SELECT id FROM (SELECT expand(out) FROM HPwSV WHERE iid=311 AND (val IN ['cat','says','meow'])) TIMEOUT 5000

Also, slow is:

orientdb {db=WikiData}> explain SELECT id FROM (SELECT expand(out) FROM HPwSV WHERE iid=311 AND (val IN ['cat'])) TIMEOUT 5000

However, the next query is very fast:

orientdb {db=WikiData}> explain SELECT id FROM (SELECT expand(out) FROM HPwSV WHERE iid=311 AND (val='cat')) TIMEOUT 5000

**Comment by luigidellaquila** [comment]
Hi @AaronSchulz 

I fixed your use case enhancing a little bit the query optimizer.
This fix does not cover all cases (eg. multiple IN clauses involving the same hash index). I'll open another issue about that and it will be fixed in next release, with the help of the new SQL parser.
