### ISSUE TITLE
Binary serialization: simplified variable-length integers

### ISSUE THREAD

**Issue by mindplay-dk** [orientechnologies/orientdb#3215]
I would like to propose an option to enable an alternative, simplified encoding scheme for variable-length integers.

A bit of context: I'm working on a binary client for PHP, and it took me well over a week of after-hours tinkering to get a working implementation of functions to read/write variable-size integers. The implementation is rather slow, with no way to optimize, since PHP only has one, platform-dependent, signed 32-bit or 64-bit integer type. It's also brittle, since there's no practical way to support values larger than 2 billion on a 32-bit PHP build.

Having a simplified, alternative encoding option for variable-length integers isn't just to simplify implementation in scripting languages though - a more important thing to consider, is the trade-off between bandwidth overhead and CPU overhead.

For example, in a replication scenario, where two servers are physically far from each other, conserving bandwidth may be the most desirable option.

On the other hand, in a scenario where an application server is on the same local network as the database server, saving CPU overhead from encoding on the database server, and CPU overhead from encoding/decoding on the application server (especially if this is running a client written in a scripting language like PHP or JS) a bit more bandwidth overhead may be a better trade-off.

I would propose a very simple encoding scheme:

```
(type:byte)(value:bytes)
```

Where `type` is e.g. 1, 2, 3 or 17 (integer, short, long or byte) and the following `value` is a variable number of bytes depending on the type of integer.

For values < 127, that means an extra byte of overhead. For values 127-255, it's two bytes, same as now, and for higher values it's a byte more or the same as the current scheme.

Computationally though, this should be much simpler and faster to encode and decode - and much simpler to implement.

I'd be curious to see a bandwidth benchmark with this change in place in a real-world scenario - in practice, the difference in bandwidth may be almost negligible, and defaulting to a simplified encoding may actually be the best choice, slow networks being the only reasonable exception.

**Comment by mindplay-dk** [comment]
> @phpnode demonstrated that a well written impl is fast enough ;-)

Ehm, no - JS may be suitable for this sort of thing, but PHP is not. This approach will never be fast in PHP.

If msgpack is not the way to go, please consider my previous proposal - using a greatly simplified integer encoding. I'm pretty sure the bandwidth overhead is hugely outweighed by the CPU benefit, and it's a fairly small change, which will simplify client implementations on all platforms.

It's a much smaller change anyhow, and may be enough to solve the problem at hand.

**Comment by phpnode** [comment]
@mindplay-dk is using CSV presenting an actual performance problem for you or just a perceived one? [This implementation](https://github.com/codemix/php-orientdb/blob/master/src/OrientDB/Records/Deserializer.php) does 1Mb/sec on my machine, which may not be stellar but that's still a *lot* of records. It's also a direct port from the JS, with no PHP specific optimisations, I'm sure it could go a lot faster (e.g. it currently allocates an array for every returned value, that could be avoided by using references instead). 

Given Orient's connection model I'd bet 99.99% of apps will spend much more time establishing the connection to the database on each request than any time spent deserializing.

**Comment by mindplay-dk** [comment]
@phpnode granted, the problem is "perceived", but I know from past experience that state machine type parsers are something you should strictly avoid in PHP, with a few possible exceptions (like template engines) where the result can be cached.

Also, it's not only a matter of CPU overhead on the client, but also of bandwidth overhead between the client and server, and of encoding overhead on the server - turning everything into strings and then back into values is not efficient, neither in terms of CPU usage or or network/memory bandwidth.

> Given Orient's connection model I'd bet 99.99% of apps will spend much more time establishing the connection to the database on each request than any time spent deserializing

Even if more time is spent establishing the connection, this is idle time on the client (e.g. non-blocking socket waiting time) which is not CPU time.

I would be very surprised if this contributes substantially to CPU time when profiled (e.g. xdebug and KCacheGrind) - I'd be surprised if most of the CPU time isn't spent in the deserializer.

Also note, this isn't only a (CPU/memory/bandwidth) performance issue - it's also a matter of complexity. Implementing a client for this (in PHP, or any language) is quite difficult - writing a parser for a structured serialization format is far more involved than simply reading sequential data.

**Comment by mindplay-dk** [comment]
@lvca any chance your team can prioritize a *simple* solution to this problem sooner, rather than a complete protocol revamp that we would have to wait much longer for? I am eager to use and promote OrientDB, but my day job is PHP, and I can't get behind the current (CSV) protocol as a durable solution.

If I'm going to get behind OrientDB at work, I need to know that the current solution is temporary and that this will be addressed - then we could proceed experimentally with the current PHP driver until a real binary driver becomes available for production use.

I would imagine that things like replication and clustering would benefit hugely from a fully binary protocol too? Memory, bandwidth and CPU use should get considerable improvements over CSV, which should make OrientDB even more competitive on performance overall, right? :-)

**Comment by phpnode** [comment]
I think the issue is not as significant as you make out, and the solution you're proposing isn't as easy as it sounds because it requires that orient change their on disk format. I played with varints recently and they were not slow. There is already a maintained php driver that uses the binary protocol, why not use it?

Also, to be clear, there are no issues with the  "durability" of the CSV format, you just don't like it.

**Comment by mindplay-dk** [comment]
I wasn't aware that the data is stored physically in this format - obviously this negates my concerns about encoding overhead - which now becomes a storage overhead concern instead, which is less of a concern for me, personally, but may actually be a greater concern in some scenarios.

My concerns about bandwidth overhead in transport, decoding overhead on the client, CPU and memory overhead from loading and parsing the full document, etc. are all still real, I think.

> there are no issues with the "durability" of the CSV format, you just don't like it

Okay, the term "durability" was inappropriate - what I meant was, it's not a good long-term solution, since it's sub-optimal both in terms of transport and decoding.

As said, I know the problem is "perceived" to some degree, but I hope you don't think I'm just here to quibble about words? I would like to be a strong advocate for OrientDB and promote it at my workplace - I already am, but still don't feel like I can get behind it 100% as our new production database and total replacement for MySQL in new applications, until these issues are addressed.

I guess the main reason the CSV thing irks me so much, is that, this was supposed to be a binary protocol, and it isn't, really - It's a binary wrapper around a CSV format. CSV isn't binary, and since it is the protocol used for the actual data, in practice, the bulk of the overall message exchange payload in most scenarios is going to be CSV. That means we get all the complexity of having to deal with a binary format, and all the overhead of a having to deal with a CSV format. I think it's fair to say, that's not ideal.

The variable-length encoding of integers in the binary portion of the overall protocol seems like a pointless micro-optimization, seen in perspective against the CSV portion of the protocol, which encodes the majority of numbers exchanged in message payloads, overall, as strings. If the majority of the overall message protocol is going to be strings anyway, I'd rather be using a fully string-based protocol, which would be much simpler on the client-side, e.g. JSON/REST, but at the moment #3202 is keeping me from pursuing that. Also, knowing now that the native storage is CSV, I guess JSON adds both decoding and encoding overhead for every record exchanged, so I'm not sure I would want to use it all anymore.

As said though, I don't need a solution here and now - I just need an indication that this will be addressed eventually, so I can proceed with the existing driver. Is that silly?

**Comment by mindplay-dk** [comment]
@lvca oh, wait... so if the documents are natively stored in the CSV format on the server, does that mean the new binary protocol is going to incur an overhead for decoding that encoding in the binary serialization format every time a record is requested?? (if so, is there even going to be any net gain from supporting the binary protocol? or just more CPU overhead overall, plus some bandwidth savings?)

**Comment by phpnode** [comment]
The binary format is the on disk format, it's much more efficient than CSV.

**Comment by phpnode** [comment]
> I hope you don't think I'm just here to quibble about words?

No, I know you're here with good intentions, I just want to clarify things:

1. OrientDB uses the binary format to store records on disk. When using the binary serialization format on the binary network protocol it is possible for orient to stream records directly to the socket. This is the most efficient option for the server.

2. Using the CSV format is more expensive - it requires more CPU + space to both read and write. I'm going to move away from it for oriento.

3. Varints are not as bad as it seems and are certainly a lot faster than using the CSV format. It would  have been nicer to use fixed lengths, but it's not a show stopper.

4. The REST API is *slow* in comparison to the binary protocol - unless your use case consists of exactly one, pre-authenticated request which returns a *lot* of data. And if you're doing that, it's probably going to be pretty memory intensive, because you can't (*easily*) use a streaming parser on JSON. 


If you're writing a new driver from scratch, and you care about performance, the binary serialization format on the binary protocol is going to beat the pants off any of the other options. *But*, in the time we've been discussing this, @ostico forked the PHP driver I started, simplified and removed a load of stuff I think you found distasteful (e.g. traits) and is actively maintaining it - https://github.com/Ostico/PhpOrient - have you looked at that driver? It would be better to collaborate on one single codebase rather than having a lot of competing implementations.

**Comment by mindplay-dk** [comment]
Thank you for those clarifications. Yeah, the varints are not a show stopper, but they did stop the show for me - it has taken me a couple of months to understand what it is and come up with a working implementation. For something as trivial as reading and writing integers, it took a lot of steam out of me - I could have been half way done with the actual driver in that time... :-/

I have looked closely at Ostico's driver - I'm still referencing it for certain things. It still uses traits though, and lots of statics, and a bunch of other patterns I don't agree with - obviously it would be better to focus our efforts on one implementation, but the way the codebase looks right now, I doubt we'd agree on most things. My approach is quite different.

**Comment by phpnode** [comment]
@mindplay-dk if I remember correctly you wanted a lower-level driver, right? No reason why you couldn't still collaborate - your lower level driver could be the foundation upon which a more batteries included option could be built, you could split phporient in two.

**Comment by mindplay-dk** [comment]
Hmm, it probably would make more sense to fork and contribute... I'll think about it :-)

**Comment by mindplay-dk** [comment]
@lvca FYI, msgpack is now well-supported (by a PECL extension) in PHP as well. I wonder how much complexity and overhead you could remove both from the native OrientDB drivers and clients and from third-party clients by switching to msgpack?

**Comment by smolinari** [comment]
Hey Fynske,

How far did you get with your PHP driver?

Scott

**Comment by mindplay-dk** [comment]
@smolinari long-since abandoned - I don't have the time and it doesn't seem worth the effort. I've since moved from MySQL to PostgreSQL for new projects - it's not a graph DB of course, but it is quite capable as a document DB these days, and the drivers are solid, so I've settled for that.

**Comment by smolinari** [comment]
That's too bad. 

I am also pushing for a more robust driver standard (with the little influence I have). I am no expert, but I've been reading up on both gRPC and msgpack and both sound like a much better basis to work with than what is currently available, simply because they are already well supported and documented in many languages. 

I too would like to know how much work would be involved to switch to one of these quasi-standards. It has to be what I would call an enabling step for ODB, because currently, all the driver support is still on wobbly legs. It must allow the actual drivers to be programmed much easier you would think. And for sure, it is the language driver support that makes or breaks things like a database.

Scott

**Comment by StarpTech** [comment]
I come to the same conclusion after years of experience with orientdb and the binary driver. We need a more robust and standardized Response/Request protocol. I recommend http://www.grpc.io/ it is available for ton of languages and it would give orientdb a big boost in the right direction.

It would solve fundamental problems:

- Streaming support
- Standardized Status Codes
- Standardized protocol
- Performance
- Payload Agnostic
