### ISSUE TITLE
delete vertex fails and OOMs server

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3216]
This command fails:
delete vertex Item where id=17153945

That vertex only has two ongoing links (1 for out_HP and 1 for out_HPwIV, as [size=x] shows). There are no incoming links.

Trying to delete via #RID fails similarly:

delete vertex Item #11:7996381

**Comment by AaronSchulz** [comment]
I'll send a dump if I can reproduce. I don't have this corrupt dataset anymore (I trashed it).

**Comment by lvca** [comment]
Closed, unless @AaronSchulz can provide a dump for this.
