### ISSUE TITLE
cleanup com.orientechnologies.common.concur.lock.OReadersWriterSpinLock

### ISSUE THREAD

**Issue by rtm81** [orientechnologies/orientdb#3219]
When i stop my application with embedded OrientDB server in Tomcat 7,
i get Memory-leak warnings from Tomcat.

Most of the warnings are related to com.orientechnologies.common.concur.lock.OReadersWriterSpinLock. It seems that the entries in ThreadLocal are not cleared during shutdown of the server.

Dez 17, 2014 1:27:24 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SCHWERWIEGEND: The web application [/webapp] created a ThreadLocal with key of type [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$2] (value [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$2@bc3f7ee]) and a value of type [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.WNode] (value [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$WNode@3e7e643f]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Dez 17, 2014 1:27:24 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SCHWERWIEGEND: The web application [/webapp] created a ThreadLocal with key of type [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$1] (value [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$1@ffa64c7]) and a value of type [com.orientechnologies.common.types.OModifiableInteger] (value [0]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Dez 17, 2014 1:27:24 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SCHWERWIEGEND: The web application [/webapp] created a ThreadLocal with key of type [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$2] (value [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$2@4e0b3c6]) and a value of type [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.WNode] (value [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$WNode@10085833]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Dez 17, 2014 1:27:24 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SCHWERWIEGEND: The web application [/webapp] created a ThreadLocal with key of type [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$1] (value [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$1@5d1a9991]) and a value of type [com.orientechnologies.common.types.OModifiableInteger] (value [0]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Tested with 
Orientdb 2.0-M3

**Comment by rtm81** [comment]
https://gist.github.com/rtm81/1aa8255a58437f481a1d

I am calling Orient.instance().shutdown(),
see this line in the log.

2015-01-05 17:24:18:894 INFO  OrientDB Engine shutdown complete [Orient]

I send the heapdump via Email.

**Comment by laa** [comment]
Hi,
I have fixed obvious leaks.
Could you try now ?

**Comment by rtm81** [comment]
I just tested with the latest 2.0-Snapshot based on Commit 0f6b773da08750cd85af15d2f0ab549834ff2047.

Here the Tomcat logs: https://gist.github.com/rtm81/ad515fc8caf30a61af2d

The tomcat log still indicates leaks in com.orientechnologies.common.concur.lock.OReadersWriterSpinLock

2015-01-07 14:50:27:084 SEVERE The web application [/odb-web] created a ThreadLocal with key of type [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$1] (value [com.orientechnologies.common.concur.lock.OReadersWriterSpinLock$1@22f63b4b]) and a value of type [com.orientechnologies.common.types.OModifiableInteger] (value [0]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak. [WebappClassLoader]

**Comment by laa** [comment]
Hi,
Could you try now ?

**Comment by laa** [comment]
Fixed, but if problem still persists please reopen the issue.

**Comment by rtm81** [comment]
i created a pullrequest, please check.
https://github.com/orientechnologies/orientdb/pull/3374

**Comment by rtm81** [comment]
Threadlocal usage and thread in a threadpool (like in tomcat) is always problematic.
See this answer:
http://stackoverflow.com/a/13870612/2003273

For me it is OK like it is today. but please consider my pullrequest, 
otherwise the onShutdown() will never be called.

**Comment by laa** [comment]
Yes, I know about threadpoll issue but I was sure and now I am sure that it
was fixed by my previous fix, before this isssue was created by shutdown
listeners merely was not called. Do not you mind if I revert rwlock clean
up and will move resetListeners bellow cycle where listeners are called. My
point is that rwlock instances are not static and problem was in container
object not in rwlock itself.

On Mon, Jan 12, 2015 at 6:17 PM, rtm81 <notifications@github.com> wrote:

> Threadlocal usage and thread in a threadpool (like in tomcat) is always
> problematic.
> See this answer:
> http://stackoverflow.com/a/13870612/2003273
>
> For me it is OK like it is today. but please consider my pullrequest,
> otherwise the onShutdown() will never be called.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3219#issuecomment-69595335>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by laa** [comment]
Hi, could you kindly try now ?

**Comment by rtm81** [comment]
it is OK for me.
