### ISSUE TITLE
Invalid serialized document on Windows (?)

### ISSUE THREAD

**Issue by mindplay-dk** [orientechnologies/orientdb#3224]
Running the [latest snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.0-SNAPSHOT/orientdb-community-2.0-20141217.112353-489-distribution.zip) under Windows, when doing a basic `REQUEST_RECORD_LOAD`, the returned serialized appears to have an incorrect number of bytes on the class-name:

```
2014-12-17 22:06:04:181 INFO  /127.0.0.1:58905 - Writing bytes (4+34=38 bytes): [0, 12, 80, 101, 114, 115, 111, 110, 41, 0, 0, 0, 19, 43, 0, 0, 0, 26, 0, 12, 82, 97, 115, 109, 117, 115, 14, 83, 99, 104, 117, 108, 116, 122] [OChannelBinaryServer]
```

The class name is "Person" (80, 101, 114, 115, 111, 110) so the length according to [the spec](http://www.orientechnologies.com/docs/last/orientdb.wiki/Record-Schemaless-Binary-Serialization.html) should be 6, not 12.

What gives?

My Java environment is build 1.7.0_51-b13.

**Comment by mindplay-dk** [comment]
Okay, documentation is a bit clearer on this point now, saying encoding is identical to that of protobuf - so I referenced a PHP implementation of protobuf, and looks like I finally have a working var-int reader/writer. I get as far as reading the classname now. But then I can't make sense of the data that follows that.

```
     0 : 00 0c 50 65 72 73 6f 6e 29 00 00 00 13 2b 00 00 [..Person)....+..]
    10 : 00 00 00 06 42 6f 62 [....Bob]
```

So immediately after `Person`, the next byte is hex `29`, which according to the [spec](https://github.com/orientechnologies/orientdb/wiki/Record-Schemaless-Binary-Serialization) is supposed to be the length of the field name in the first field_definition... but that's `-21` in decimal, so obviously that's not a string length... Looking at the binary response above, I don't see any field names in there at all - is something missing from the spec??

**Comment by GoorMoon** [comment]
Do you use Schema in the class ?

**Comment by mindplay-dk** [comment]
Yes.

**Comment by GoorMoon** [comment]
As far i understood then negative number come in the field_definition then
you must read property type from the metadata and in the this field is not
length is encoded property id.
look here
https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/serialization/serializer/record/binary/ORecordSerializerBinaryV0.java#L153

**Comment by mindplay-dk** [comment]
The documentation doesn't even mention any concept of "global properties" - in fact, it specifically says, "with no need of a external schema definition"... but so the client does need to obtain the schema definition from elsewhere? I mean, that makes sense, but the documentation is so misleading I didn't even grok that after reading the code... They really need to have someone with better english skills proof read this documentation...

**Comment by mindplay-dk** [comment]
So to get the metadata, you would need `REQUEST_RECORD_METADATA`? Which isn't even documented? How do you guys go about writing the drivers for this stuff? You reverse engineer from the source code or what..??

**Comment by GoorMoon** [comment]
If i am remember, REQUEST_RECORD_METADATA get BACK ORID and Version only.
to get metadata you need to sql query `select expand(properties) from
(select expand(classes) from metadata:schema) where name = 'OUser'`

**Comment by mindplay-dk** [comment]
Then presumably the metadata comes back "schemaless", with the actual field_definitions in the result? Otherwise, where would the client get the schema for the metadata?

I've never seen this `metadata:schema` syntax either, is that documented?

**Comment by GoorMoon** [comment]
nope :(

**Comment by mindplay-dk** [comment]
Oh, dear. I was under the impression this was really well-documented, but clearly the documentation is pretty far behind the actual product...
