### ISSUE TITLE
SQL NOT operator

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3231]
According to https://github.com/orientechnologies/orientdb/wiki/SQL-Where , NOT is not supported.

Some queries seem to work with correct results anyway:

select id from Property where id NOT IN [279,16]
select id from Property where NOT (id IN [22,32,35,19])

Is this just outdated documentation or are there edge cases that don't work?

**Comment by lvca** [comment]
@AaronSchulz maybe the doc is old. I'm not sure if NOT works in all the cases.

**Comment by AaronSchulz** [comment]
There some cases where it doesn't, so this is waiting on the new parser.

**Comment by lvca** [comment]
NOT works if you use parenthesis on the right.

**Comment by lvca** [comment]
Update docs according
