### ISSUE TITLE
impossibility to delete a property

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#3232]
after peforming the incorrect request to the data base through the studio, a property named "**= sec**" has developed

Now it's impossible to delete is,due to the constant indication of mistake

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #20: Expected <class>.<property>. Use DROP PROPERTY <class>.<property> Command: DROP PROPERTY xDirs.= sec ----------------------------^

**Comment by Ivanov-Yuriy** [comment]
##### there is nearly the same problem in DB version 2.1.0
##### I can't delete or rename property which has white space in name

orientdb {db=test}> __create class test extends V__
Class created successfully. Total classes in database now: 12

orientdb {db=test}> __create property test.testName string__
Property created successfully with id=1

orientdb {db=test}> __select expand(properties) from (select  expand(classes) from metadata:schema) where name = 'test'__
----+------+--------+----+--------+---------+--------+-------+------------+----+----+------+------------+-------
\#   | @ CLASS|name    |type|globalId|mandatory|readonly|notNull|defaultValue|min |max |regexp|customFields|collate
----+------+--------+----+--------+---------+--------+-------+------------+----+----+------+------------+-------
0   |null  |testName|7   |20      |false    |false   |false  |null        |null|null|null  |null        |default
----+------+--------+----+--------+---------+--------+-------+------------+----+----+------+------------+-------
1 item(s) found. Query executed in 0.004 sec(s).

orientdb {db=test}> __alter property test.testName name hello mistake__
Property updated successfully

orientdb {db=test}> __select expand(properties) from (select  expand(classes) from metadata:schema) where name = 'test'__
----+------+--------------+----+--------+---------+--------+-------+------------+----+----+------+------------+-------
\#   | @ CLASS|name          |type|globalId|mandatory|readonly|notNull|defaultValue|min |max |regexp|customFields|collate
----+------+--------------+----+--------+---------+--------+-------+------------+----+----+------+------------+-------
0   |null  |hello mistake|7   |21      |false    |false   |false  |null        |null|null|null  |null        |default
----+------+--------------+----+--------+---------+--------+-------+------------+----+----+------+------------+-------
1 item(s) found. Query executed in 0.002 sec(s).

orientdb {db=test}> __alter property test.hello mistake  name renemeMistake__
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #26: Unknown property attribute 'MISTAK
E'. Supported attributes are: [LINKEDTYPE, LINKEDCLASS, MIN, MAX, MANDATORY, NAME, NOTNULL, REGEXP, TYPE, CUSTOM, READONLY, COLLATE, DEFAULT]
Command: alter property test.hello mistake  name renemeMistake
----------------------------------^

Error: java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OProperty.ATTRIBUTES.MISTAKE

orientdb {db=test}> __drop property test.hello mistake__

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #33: Wrong query parameter
Command: drop property test.hello mistake
-----------------------------------------^

**Comment by lvca** [comment]
Have you tried with back tick (`)? Example:

    alter property `test.hello mistake  name` renemeMistake

**Comment by Ivanov-Yuriy** [comment]
#### I tried to put different signs in different places but always was getting mistake

orientdb {db=test}> __alter property test.'hello mistake'  name renemeMistake__

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Property 'test.'hello mistake'' not exists

orientdb {db=test}> alter property 'test.hello mistake'  name renemeMistake

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Source class ''test' not found

orientdb {db=test}> alter property test.'hello mistake'  name renemeMistake

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Property 'test.'hello mistake'' not exists

orientdb {db=test}> alter property test.`hello mistake`  name renemeMistake

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #26: Unknown property attribute 'MIS
E`'. Supported attributes are: [LINKEDTYPE, LINKEDCLASS, MIN, MAX, MANDATORY, NAME, NOTNULL, REGEXP, TYPE, CUSTOM, READONLY, COLLATE, DEFAULT]
Command: alter property test.`hello mistake`  name renemeMistake
----------------------------------^

Error: java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OProperty.ATTRIBUTES.MISTAKE`

orientdb {db=test}> alter property `test.hello mistake`  name renemeMistake

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #26: Unknown property attribute 'MIS
E`'. Supported attributes are: [LINKEDTYPE, LINKEDCLASS, MIN, MAX, MANDATORY, NAME, NOTNULL, REGEXP, TYPE, CUSTOM, READONLY, COLLATE, DEFAULT]
Command: alter property `test.hello mistake`  name renemeMistake
----------------------------------^

Error: java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OProperty.ATTRIBUTES.MISTAKE`

orientdb {db=test}> alter property "test.hello mistake"  name renemeMistake

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Source class '"test' not found

orientdb {db=test}> alter property 'test.hello mistake  name' renemeMistake

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #41: Unknown property attribute 'REN
MISTAKE'. Supported attributes are: [LINKEDTYPE, LINKEDCLASS, MIN, MAX, MANDATORY, NAME, NOTNULL, REGEXP, TYPE, CUSTOM, READONLY, COLLATE, DEFAULT]
Command: alter property 'test.hello mistake  name' renemeMistake
-------------------------------------------------^

Error: java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OProperty.ATTRIBUTES.RENEMEMISTAKE

orientdb {db=test}> alter property "test.hello mistake"  name renemeMistake

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Source class '"test' not found

orientdb {db=test}> alter property test."hello mistake"  name renemeMistake

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Property 'test."hello mistake"' not exists

**Comment by luigidellaquila** [comment]
Fixed in develop branch (2.2.1)

Closing, please reopen if you still see any incorrect behaviors here

Thanks

Luigi
