### ISSUE TITLE
How to perform Java unit test against in memory OrientDB ?

### ISSUE THREAD

**Issue by mathieubodin** [orientechnologies/orientdb#3242]
Hi, I'm wondering what is the preferred way of testing Java code against an OrientDB server.
My case is quite simple: I'm using OrientDB as the database backing the application. I tried instantiating it from code, but quickly I'm facing strange behaviors, certainly due to misuses from my code...

So, do you have any suggestion, best practice ? I'm really looking for advices :D

**Comment by lvca** [comment]
There are no particular advices. What's your problem? Could you please elaborate it more?
