### ISSUE TITLE
Can not restore 0 WAL master record

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3259]
Creating a brand new DB, importing vertexes (~16mil via https://github.com/AaronSchulz/WikiDataQueryOrient), using shutdown.sh and starting it again consistency results in:

2014-12-22 18:19:41:116 SEVERE Can not restore 0 WAL master record for storage WikiData crc check is failed [ODiskWriteAheadLog]

I never notice anything broken, so it might mostly be noise, but the notice is worrisome. There are no other errors logged.

**Comment by laa** [comment]
Is it still reproducible on latest sources, I have added fix for this issue during fuzzy checkpoints implementation.
