### ISSUE TITLE
What's the best way to know if an edge exists?

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3261]
Hi, 

I'm using Java Document API and lightweight edges.
Is there a better way to know if an edge exists than:

``` sql
select expand(out('Follows')) from 12:11
```

and iterate through the result?

Maybe something like:

``` sql
select from 12:11 to 12:12
```

Thanks,

**Comment by luigidellaquila** [comment]
This is a pretty old question (no idea why it was not answered so far) but I think it deserves an answer.

In SQL, the best way to do this is

```
select outE('Follows')[@rid = #12:12] from #12:11
```

Anyway, it's not optimized and cannot be optimized with lightweight edges.

With regular edges, of course, the best way to achieve this is to define an index on `EdgeClass[out, in]` and query on it

Thanks

Luigi
