### ISSUE TITLE
Inconsistent behaviour of Binary/REST protocols using fetchplan of -2

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#3263]
Specifying `FETCHPLAN *:1 in_SomeEdge:-2` via the binary protocol will still return a RIDBag for `in_SomeEdge`. The same query via the REST API will not include `in_SomeEdge` at all, it behaves similar to `exclude(in_SomeEdge)`. Combined with an error in the docs this leads to broken user expectations, see [this comment](https://github.com/codemix/oriento/issues/175#issuecomment-68000365) for full details.

**Comment by garrett-gottlieb** [comment]
@lvca, any updates?

**Comment by tglman** [comment]
Hi @garrett-gottlieb, for this issue i feel that my patch created some problems, I'm going to revert back the changes to a stable version and re-design and re-elaborate the fix, this will take some time, not less than one week, the reason is that the binary protocol wasn't designed to support negative fetch plan, so i have to check if the things are designed and tested properly.

I understand the importance of this in your use case, we are trying to put an extra care on this, keeping in mind that we are few days far the final stable release.

**Comment by garrett-gottlieb** [comment]
Hi @tglman,

Stability comes first, of course. Let me know any way I can help you speed this up, as we are going down daily on our old database and this is the biggest issue standing in the way of us launching OrientDB in production.

**Comment by tglman** [comment]
hi,

I written the tests and tried to solve the problem, but I've found some issues in the protocol design, I've this test https://github.com/orientechnologies/orientdb/blob/develop/tests/src/test/java/com/orientechnologies/orient/test/database/auto/FetchPlanTest.java#L233 that is failing with the fix, the reason that the fetch plan should not remove the data from the record but not load it and let the client load it on request. for do that we need concept like partial fetched record and diff update, that are not present as concept in the protocol. On the http protocol instead this concept are present like described in the doc http://www.orientechnologies.com/docs/last/orientdb.wiki/OrientDB-REST.html#put---document allowing to do partial record lazy loading. 

Another important point that describe why this was never implemented in the binary protocol is that in most of the case huge set of references are managed outside the record with a tree like structure, fully supported in the binary protocol, and not supported in the http protocol.

so introduce this new concept(for the binary protocol) right now it need correct full design, time for contributors to updated the drivers, and finally it may introduce instability.

on the other side i understand the performance concern you have in you use case, and i think i can improve the exclude function to cover nested property use case, without lead to general project instability.

**Comment by lvca** [comment]
The only problem I can see here is when users use -2 in fetchPlan to remove properties and then save those records: OrientDB would save them without the removed properties.

So we should decide between:
- support -2 and give to the user the responsibility to don't save the record back
- improve exclude() method to support nested properties

**Comment by lvca** [comment]
Fixed in 2.1-SNAPSHOT

**Comment by stevehu** [comment]
@lvca Could you please let us know which option you chose to fix the issue? I am going to check out develop branch to try it out. Thanks.
