### ISSUE TITLE
Function to collapse collections into a JSON string

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3265]
Maybe this already exists, but I can't find it in any docs.

A query like:
```
orientdb {db=WikiData}> select id,out_HPwIV[pid=106][best=1]['val'] AS vals from Item where id=23

Gives results like:

#   |@CLASS|id  |vals
----+------+----+----
0   |null  |23  |[4]
```
It would be nice to be able to wrap the "out_HPwIV[pid=106][best=1]['val']" part in some function that turns it into a JSON string. That way each result would have "id" and "vals" for each row. I don't want to use expand() as that creates (id,vals) pairs for each collection value and only works if there is 1 expand call.

**Comment by lvca** [comment]
This is the UNWIND, available since v2.0.x.
