### ISSUE TITLE
Documents vs Vertices

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#3267]
Why does there need to be a separation between documents and vertices? It's confusing for users and means that "strange" things like `ALTER CLASS OUser SUPERCLASS V` are necessary. Is `ODocument` a vestigial remnant from a time before the graph API? If so, could it be removed / merged in a future version?

**Comment by lvca** [comment]
OrientDB is a multi-model database with a graph engine, so documents are still relevant in OrientDB.
