### ISSUE TITLE
Invalid keyword error in UPDATE SET clause with JSON

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3273]
update Item set claims={"1465":[{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":9218484}],"1036":[{"snaktype":"value","rank":-1,"best":1,"valuetype":"string","datavalue":"2--434145"}],"17":[{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":183}],"373":[{"snaktype":"value","rank":0,"best":1,"valuetype":"string","datavalue":"Gie\u00dfen"}],"131":[{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":7904},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":7931},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":1199}],"94":[{"snaktype":"value","rank":0,"best":1,"valuetype":"string","datavalue":"Wappen Gie\u00dfen.svg"}],"31":[{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":134626},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":1187811},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":515},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":262166}],"242":[{"snaktype":"value","rank":0,"best":1,"valuetype":"string","datavalue":"Landkreis Gie\u00dfen Gie\u00dfen.png"}],"150":[{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":2648414},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":1571834},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":1880499},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":2179359},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":1522977}],"439":[{"snaktype":"value","rank":0,"best":1,"valuetype":"string","datavalue":"06531005"}],"625":[{"snaktype":"value","rank":0,"best":1,"valuetype":"globecoordinate","datavalue":{"lat":50.583333333333,"lon":8.6666666666667}}],"227":[{"snaktype":"value","rank":0,"best":1,"valuetype":"string","datavalue":"1028168-X"}],"910":[{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":8491982}],"214":[{"snaktype":"value","rank":0,"best":1,"valuetype":"string","datavalue":"239401042"}],"982":[{"snaktype":"value","rank":0,"best":1,"valuetype":"string","datavalue":"bdfef083-f06c-44fe-b2a6-1d4da9d15ae6"}],"646":[{"snaktype":"value","rank":0,"best":1,"valuetype":"string","datavalue":"/m/022xzn"}],"190":[{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":180139},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":209988},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":192225},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":13362},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":240247},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":172157},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":496381},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":42635},{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":621}],"1464":[{"snaktype":"value","rank":0,"best":1,"valuetype":"wikibase-entityid","datavalue":8050655}],"1566":[{"snaktype":"value","rank":0,"best":1,"valuetype":"string","datavalue":"2920512"}]} where id=3874

PHP Fatal error:  Uncaught exception 'Exception' with message 'Command failed (500). Got:com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #3435: Invalid keyword }]}. Use UPDATE <class>|cluster:<cluster>> [SET|ADD|PUT|REMOVE|INCREMENT|CONTENT {<JSON>}|MERGE {<JSON>}] [[,] <field-name> = <expression>|<sub-command>]* [LOCK <NONE|RECORD>] [UPSERT] [RETURN <COUNT|BEFORE|AFTER>] [WHERE <conditions>]

This works fine in the console but fails when using the HTTP JSON SQL batch interface.

**Comment by luigidellaquila** [comment]
Fixed. The fix will be released with 2.1.10

Thanks

Luigi
