### ISSUE TITLE
DROP CLUSTER allows to drop default class clusters

### ISSUE THREAD

**Issue by deividasjackus** [orientechnologies/orientdb#3277]
Normally, CREATE CLASS also creates a cluster used by the class, DROP CLASS also drops the cluster used by the class:

However, there are no warnings when you drop a cluster that is used by a class:

```
CREATE CLASS Test
DROP CLUSTER Test
```

The cluster "Test" was dropped, but the class "Test" still remains, even though it can no longer be used:

```
SELECT FROM Test
    Error: java.lang.ArrayIndexOutOfBoundsException: 0
INSERT INTO Test CONTENT {}
    Error: java.lang.IllegalArgumentException: Cluster name null is not configured
```

You can no longer drop the class either, really:

```
DROP CLASS Test
Error: java.lang.IllegalArgumentException: Cluster 12 is null
```

I understand this is a rare scenario, but think it would be still wise to either (I am a bigger fan of #2):
1. Throw warnings when DROP CLUSTER is performed on the _default_ cluster of an existing class.
2. Add support for _DEFAULTCLUSTERID_ to _ALTER CLASS_ and make sure _DROP CLUSTER_ does not allow to drop a default cluster for a class.

**Comment by tglman** [comment]
hi,
The drop of a cluster of a class remove it from the class and it give an error if is the last one suggesting to drop de class instead, so this is already implemented, closing.
