### ISSUE TITLE
Support chaining document field part in projections of embedded fields

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3284]
This is the actual feature request from #3274 but without the unrelated confusion.

If a create a JSON field for a row, I can have projections that filter it by key/value, but I can't filter the filtered result. So if the field is claims={valuetype=string, datavalue=101061288, rank=0, snaktype=value, best=1}, I can do:

```sql
select claims[rank=0]
```

But not:
```sql
select claims[rank=0][best=1]
```

The later always gives empty results.

According to https://github.com/orientechnologies/orientdb/wiki/Document-Field-Part , the chaining feature is only for links, which indeed works, e.g:
```
orientdb {db=WikiData}> select out_HIaPV[pid=40][rank=0][best=1] from #11:2

----+------+---------
#   |@CLASS|out_HIaPV
----+------+---------
0   |null  |#20:16
----+------+---------

1 item(s) found. Query executed in 0.002 sec(s).
orientdb {db=WikiData}> select out_HIaPV[pid=40][rank=0][best=2] from #11:2

----+------
#   |@CLASS
----+------
0   |null
----+------
```
Would it be possible to extend this chaining feature to JSON fields as well?

**Comment by lvca** [comment]
Now embeddedmap (json) have the same behavior of document with condition in [].

**Comment by AaronSchulz** [comment]
I noticed that this sometimes doesn't work now. E.g.:

orientdb {db=WikiData}> select id,claims[40][rank=0] from Item where id=23 and claims[40] contains (snaktype = "value")

----+------+----+--------------------------------------------------------------------------------
#   |@CLASS|id  |claims
----+------+----+--------------------------------------------------------------------------------
0   |null  |23  |{valuetype=wikibase-entityid, datavalue=1701323, rank=0, snaktype=value, best=1}
----+------+----+--------------------------------------------------------------------------------

1 item(s) found. Query executed in 0.0 sec(s).
orientdb {db=WikiData}> select id,claims[40][rank=0] from Item where id=23 and claims[40][rank=0] contains (snaktype = "value")

0 item(s) found. Query executed in 0.0 sec(s).

In other cases it does work:

orientdb {db=WikiData}> select id,claims[190][rank=0][best=1] from Item where id=62 and claims[190][rank=0][best=1] contains (best=1)

----+------+----+------
#   |@CLASS|id  |claims
----+------+----+------
0   |null  |62  |[29]
----+------+----+------

1 item(s) found. Query executed in 0.0 sec(s).

Note that "claims" is an embedded map of embedded.

When chaining doesn't work, I also noticed that the console shows the string JSON after the first filter and when it does work the console just shows [X]. I tried deleting and resetting "claims" for Item 23 but it didn't help. It's as if JSON is sometimes stored and handled slightly differently in some cases, though I don't know why.

**Comment by lvca** [comment]
I think field chaining is working now, but as you said, the json was entered bad. Please could you provide me a SQL to reproduce the problem?

**Comment by AaronSchulz** [comment]
I suppose you do:

create class Test extends V;
create property Test.claims EMBEDDEDMAP embedded;

create vertex Test set id=23

update Test set claims={"509":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":356405,"rank":0,"best":1}],"947":[{"snaktype":"value","valuetype":"string","datavalue":"000025437","rank":0,"best":1}],"19":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":494413,"rank":0,"best":1}],"20":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":731635,"rank":0,"best":1}],"26":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":191789,"rank":0,"best":1,"qlfrs":{"580":[{"snaktype":"value","valuetype":"time","datavalue":"+00000001759-01-06T00:00:00Z"}]}}],"21":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":6581097,"rank":0,"best":1}],"109":[{"snaktype":"value","valuetype":"string","datavalue":"George Washington signature.svg","rank":0,"best":1}],"22":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":768342,"rank":0,"best":1}],"25":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":458119,"rank":0,"best":1}],"40":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":1701323,"rank":0,"best":1}],"27":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":30,"rank":0,"best":1}],"106":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":1734662,"rank":0,"best":1},{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":131512,"rank":0,"best":1},{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":189290,"rank":0,"best":1},{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":82955,"rank":0,"best":1}],"237":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":5138446,"rank":0,"best":1}],"94":[{"snaktype":"value","valuetype":"string","datavalue":"COA George Washington.svg","rank":0,"best":1}],"9":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":850421,"rank":0,"best":1}],"7":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":5083373,"rank":0,"best":1},{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":6219733,"rank":0,"best":1},{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":7412891,"rank":0,"best":1}],"373":[{"snaktype":"value","valuetype":"string","datavalue":"George Washington","rank":0,"best":1}],"18":[{"snaktype":"value","valuetype":"string","datavalue":"Gilbert Stuart Williamstown Portrait of George Washington.jpg","rank":0,"best":1}],"227":[{"snaktype":"value","valuetype":"string","datavalue":"11876439X","rank":0,"best":1}],"244":[{"snaktype":"value","valuetype":"string","datavalue":"n86140996","rank":0,"best":1}],"214":[{"snaktype":"value","valuetype":"string","datavalue":"31432428","rank":0,"best":1}],"213":[{"snaktype":"value","valuetype":"string","datavalue":"0000 0001 2095 8599","rank":0,"best":1}],"345":[{"snaktype":"value","valuetype":"string","datavalue":"ch0028228","rank":0,"best":1}],"569":[{"snaktype":"value","valuetype":"time","datavalue":"+00000001732-02-22T00:00:00Z","rank":0,"best":1}],"570":[{"snaktype":"value","valuetype":"time","datavalue":"+00000001799-12-14T00:00:00Z","rank":0,"best":1}],"166":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":721743,"rank":0,"best":1},{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":3519573,"rank":0,"best":1}],"119":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":731635,"rank":0,"best":1,"qlfrs":{"585":[{"snaktype":"value","valuetype":"time","datavalue":"+00000001799-12-18T00:00:00Z"}]}}],"39":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":11696,"rank":0,"best":1,"qlfrs":{"580":[{"snaktype":"value","valuetype":"time","datavalue":"+00000001789-04-30T00:00:00Z"}],"582":[{"snaktype":"value","valuetype":"time","datavalue":"+00000001797-03-04T00:00:00Z"}],"156":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":11806}],"155":[{"snaktype":"novalue"}]}}],"410":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":3100539,"rank":0,"best":1,"qlfrs":{"585":[{"snaktype":"value","valuetype":"time","datavalue":"+00000001976-07-04T00:00:00Z"}]}},{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":1115127,"rank":0,"best":1,"qlfrs":{"580":[{"snaktype":"value","valuetype":"time","datavalue":"+00000001775-06-15T00:00:00Z"}],"582":[{"snaktype":"value","valuetype":"time","datavalue":"+00000001783-12-23T00:00:00Z"}]}}],"349":[{"snaktype":"value","valuetype":"string","datavalue":"00621629","rank":0,"best":1}],"269":[{"snaktype":"value","valuetype":"string","datavalue":"027333140","rank":0,"best":1}],"646":[{"snaktype":"value","valuetype":"string","datavalue":"/m/034rd","rank":0,"best":1}],"535":[{"snaktype":"value","valuetype":"string","datavalue":"11816","rank":0,"best":1},{"snaktype":"value","valuetype":"string","datavalue":"1075","rank":0,"best":1},{"snaktype":"value","valuetype":"string","datavalue":"6781","rank":0,"best":1}],"409":[{"snaktype":"value","valuetype":"string","datavalue":"35592539","rank":0,"best":1}],"245":[{"snaktype":"value","valuetype":"string","datavalue":"500126198","rank":0,"best":1}],"268":[{"snaktype":"value","valuetype":"string","datavalue":"11928912p","rank":0,"best":1}],"735":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":15921732,"rank":0,"best":1}],"463":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":466089,"rank":0,"best":1},{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":41726,"rank":0,"best":1}],"102":[{"snaktype":"novalue","rank":0,"best":1}],"241":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":54122,"rank":0,"best":1}],"607":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":40949,"rank":0,"best":1}],"31":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":5,"rank":0,"best":1}],"910":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":8488276,"rank":0,"best":1}],"691":[{"snaktype":"value","valuetype":"string","datavalue":"jn19990008936","rank":0,"best":1}],"906":[{"snaktype":"value","valuetype":"string","datavalue":"241381","rank":0,"best":1}],"949":[{"snaktype":"value","valuetype":"string","datavalue":"000145507","rank":0,"best":1}],"734":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":2550388,"rank":1,"best":1}],"1273":[{"snaktype":"value","valuetype":"string","datavalue":"a11452754","rank":0,"best":1}],"1415":[{"snaktype":"value","valuetype":"string","datavalue":"101061288","rank":0,"best":1}],"1430":[{"snaktype":"value","valuetype":"string","datavalue":"6109","rank":0,"best":1}],"361":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":186539,"rank":0,"best":1}],"1196":[{"snaktype":"value","valuetype":"wikibase-entityid","datavalue":3739104,"rank":0,"best":1}],"1017":[{"snaktype":"value","valuetype":"string","datavalue":"ADV10077200","rank":0,"best":1}],"1309":[{"snaktype":"value","valuetype":"string","datavalue":"001094942","rank":0,"best":1}],"1006":[{"snaktype":"value","valuetype":"string","datavalue":"069038171","rank":0,"best":1}],"1207":[{"snaktype":"value","valuetype":"string","datavalue":"n01036872","rank":0,"best":1}],"1005":[{"snaktype":"value","valuetype":"string","datavalue":"64839","rank":0,"best":1}]} where id=23

orientdb {db=WikiData}> select claims[1415][rank=0] From Test where claims[1415] contains (best=1)

----+------+-----------------------------------------------------------------------
#   |@CLASS|claims
----+------+-----------------------------------------------------------------------
0   |null  |{valuetype=string, datavalue=101061288, rank=0, snaktype=value, best=1}
----+------+-----------------------------------------------------------------------

1 item(s) found. Query executed in 0.001 sec(s).
orientdb {db=WikiData}> select claims[1415][rank=0] From Test where claims[1415][rank=0] contains (best=1)


0 item(s) found. Query executed in 0.0 sec(s).

**Comment by lvca** [comment]
This seems correct, because claims[1415][rank=0] work on the map and current value becomes the map itself (in chain). You should rather do:

    select claims[1415][rank=0] From Test where claims[1415] contains (best=1 AND rank=0)
