### ISSUE TITLE
Retrieving record from Index of Abstract class kind of retrieves the record

### ISSUE THREAD

**Issue by RapidTransit** [orientechnologies/orientdb#3286]
When querying from an index of an abstract class, it isn't retrieving the actual record, to work around I can call document.field("rid") which returns the actual record

This is 2.0.0-rc3

**Comment by lvca** [comment]
Could you please post the query?

**Comment by RapidTransit** [comment]
It's been a while, this was when I was investigating using OrientDB, what would happen was I would have an index in an abstract class and I would query against it. The returned document would not load unless I called ```document.field("rid")``` if I called ANY other field without calling this first it would throw an Exception (I think, it's been a while) or not load at all.

**Comment by lvca** [comment]
if you query directly from an index, like:

    select from index:myindex where key = 'Jay'

OrientDB returns a pair of `key` and `rid`, so it's correct. You should rather use:

    select expand(rid) from index:myindex where key = 'Jay'

or

    select expand(rid) from (select rid from index:myindex where key = 'Jay')
