### ISSUE TITLE
Field 'in_XX' cannot be added during CREATE EDGE when class schema is defined as STRICT

### ISSUE THREAD

**Issue by a-unite** [orientechnologies/orientdb#3289]
*I'm not sure this is a bug, but it looks like one for me, because it makes STRICTMODE concept almost unpractical:*

when you try to CREATE EDGE for any vertex or edge, which has STRICTMODE enabled - OValidationException occurs, something like this:

```Caused by: com.orientechnologies.orient.core.exception.OValidationException: Found additional field 'in_'. It cannot be added because the schema class 'A' is defined as STRICT```

of course this happens for all four in_ and out_ fields participating in operation if we have all three classes in strict mode.

**Comment by a-unite** [comment]
Luca, should we avoid strict mode for any Graph databases then?

It is OK for us, if this issue will be fixed in next minor release, but I need to make all architecture related decisions as soon as possible. 

Thank you and Happy new year!

**Comment by lvca** [comment]
Issue #3534 can't be reproducible with v2.0.1+. What release are you using here?

**Comment by a-unite** [comment]
Luca, we are always trying to keep to the latest snapshot available.

Tried with 2.1 (02 feb), tested with 2.0.2 (05 feb)

Here is the sample code to reproduce, it might be my mistake, though:
```
create class M extends V
create class N extends V
create class M_N extends E

alter class M strictmode TRUE
alter class N strictmode TRUE

create property M.val integer
create property N.val integer

create vertex M set val=1
create vertex N set val=101

create edge M_N from (select from M limit 1) to (select from N limit 1)
```

Here what I always get for the most recent ODB versions available:

`2015-02-06 02:48:25:128 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OValidationException: Found additional field 'in_m_n'. It cannot be added because the schema class 'N' is defined as STRICT [ONetworkProtocolHttpDb]`

Should we explicitly add `N.in_m_n` and `M.out_m_n` properties then?

**Comment by a-unite** [comment]
Ok. I see your comment on the linked issue.
So we should add proper `Vv.in_eE` and `Vv.out_eE` fields for every possible edge classes between those two vertexes and this is expected behavior, not bug but a feature. That is all I wanted to know.
Thanks.
