### ISSUE TITLE
restore from WAL prevents JVM shutdown

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#3293]
1) The application is started
2) DB is opened
3) DB found corrupted. 
4) DB begins restoring from WAL.
5) This process can take hours
6) User gets frustrated and attempts to shutdown the server
7) Restore from WAL thread prevents server shutdown. Other resources in our software are not closed

Orient ought to have some way of recognizing that the JVM wants to exit and shutting the restore from WAL process down so that it can continue where it left off when the server starts up again.

 Stacks at 11:39:49 AM (uptime 6m 16 sec)

 service [RUNNABLE]
java.util.zip.CRC32.updateBytes(int, byte[], int, int) CRC32.java (native)
java.util.zip.CRC32.update(byte[], int, int) CRC32.java:65
com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment.checkPageIntegrity(byte[]) ODiskWriteAheadLog.java:565
com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment.readRecord(OLogSequenceNumber) ODiskWriteAheadLog.java:402
com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.read(OLogSequenceNumber) ODiskWriteAheadLog.java:876
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFrom(OLogSequenceNumber) OAbstractPaginatedStorage.java:2110
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromBegging() OAbstractPaginatedStorage.java:2095
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL() OAbstractPaginatedStorage.java:1934
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreIfNeeded() OAbstractPaginatedStorage.java:1334
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(String, String, Map) OAbstractPaginatedStorage.java:163
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(String, String) ODatabaseDocumentTx.java:209
com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate() OrientBaseGraph.java:1716
com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(String, String, String) OrientBaseGraph.java:162
com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(String, String, String, boolean) OrientTransactionalGraph.java:102
com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(String, String, String) OrientTransactionalGraph.java:98
com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(String) OrientGraph.java:69

**Comment by laa** [comment]
After fuzzy checkpoints were implemented restore process does not take hours.
But idea is nice, I will try to implement it in 2.0 if we will have time.
Meanwhile could you try latest version and verify that restore process now will not take much of time.
Create database, fill the date, wait 15-20 min and kill server.
Let see time which we need to restore data.

**Comment by jamieb22** [comment]
Andrey

I am using RC1 and the following properties are set:

index.auto.rebuildAfterNotSoftClose = false
index.txMode=FULL

Yet, a corrupted database is taking half an hour to restore. In our 
multitenant product, each instance has a database, and there may be 30 
or more of them.

I really don't understand the logic behind this.

In our case:

- Orient db shutdown seems to be executed, yet the DB still appears 
corrupted.
- If even if the above weren't true, we are not executing kill -9 on the 
process, we are only performing kill -6
- If kill -6 is executed, surely the shutdown hook would be executed, 
and Orient db would be shutdown correctly
- Even in the even that kill -9 was executed, surely, the database would 
only restored from the point of corruption. It seems to be restoring 
everything from the WAL. This is taking forever as it has to rebuild the 
entire database, not just the damaged part.

Orient appears to overly sensitive and we cannot get it to behave in a 
robust manner.

Any input would be most appreciated.

Jamie

**Comment by lvca** [comment]
We already fixed this problem in 2.0-SNAPSHOT, please could you switch to this release?

**Comment by laa** [comment]
Closed, because of no answer.
