### ISSUE TITLE
ODocument.fromJSON strange behaviour

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3299]
Guys,

I found quite strange behaviours of fromJSON() method. Might be that are not bugs and that are working as expected, but at leasts more documentantation (Java Docs as min) will be really appreciated.

1) fromJSON might return other object than "this". (ODocument doc2 = doc.fromJSON(json); doc2!=doc). 
2) if needReload specified it doesn't preserve "loaded" version from DB and finally it leads to versions collisions. I guess it works not as expected for needReload=true.
3) fromJSON(InputStream inputStream) returns this in any case, but "this" might not be equal to document returned by internal fromJSON(String) (see p.1) 

Please let me know what is bug and what is not a bug: I might try to fix that by myself.

**Comment by lvca** [comment]
1) No, it always return the same document
2) What do you mean?
3) always current document is returned

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Comment by PhantomYdn** [comment]
@lvca let me disagree with you on points 1 and 3. On first level in ODocument and ORecord yes - you are right that "this" can be only returned. But if you take a look into ORecordSerializerJSON.fromString - you will see that there are several places when iRecord can be recreated for json currently used.

2) needReload - that's a parameter of ORecordSerializerJSON.fromString and sometimes it's being used. And if it set to true - you will see mentioned effect.
