### ISSUE TITLE
ODocument save() doesn't set Identity on new object

### ISSUE THREAD

**Issue by darkredz** [orientechnologies/orientdb#3307]
Hi,

I am testing some stuffs on 2.0 RC1, I found out that the behaviour that used to work in 1.7 doesn't work any more in 2.0.

// CREATE A NEW DOCUMENT AND SAVE IT
ODocument doc = new ODocument("Person");
doc.field( "name", "Luke" );
doc.field( "surname", "Skywalker" );
doc.field( "city", new ODocument("City").field("name","Rome").field("country", "Italy") );

// SAVE THE DOCUMENT
doc.save();
log( doc.getIdentity().toString());

After saving (which create a new document), trying to getIdentity() on the same doc object will return null. It was returning the actual ID of the saved document in previous version

**Comment by darkredz** [comment]
It's without transaction

**Comment by lvca** [comment]
Tried and works. Could you provide a test case that reproduce the problem?

**Comment by darkredz** [comment]
ok i cannot reproduce it, it seems that it might be a miss used of the older Jars with the database
