### ISSUE TITLE
2.0-rc1: server.sh MAXDISKCACHE parameter causes startup error

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3310]
It's near the end of the file, if you put in the value "8192" as suggested in the comment you get an error "Error: Could not find or load main class 8192"

**Comment by 8forty** [comment]
One followup question: there's also a setting for this in orientdb-server-config.xml, so if it is set in both places which one is used?  Shouldn't it be documented and used in just one place rather than 2, that seems confusing.  I guess I don't understand why it was added to server.sh when it was already working fine in the ...config.xml?

**Comment by lvca** [comment]
You could set this in orientdb-server-config.xml, but there isn't in default cfg. We prefer to keep `storage.diskCache.bufferSize` and JVM -Xmx in the same place to make this tuning easier.

**Comment by ropeladder** [comment]
The comment in server.bat as of 2.0.12 is still misleading (though server.sh is fixed), as are the recommendations from the server when you are using too much disk cache.

**Comment by lvca** [comment]
Changed in 2.0.13
