### ISSUE TITLE
`@fieldTypes` in REST response does not indicate RIDs

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#3313]
The `@fieldTypes` field in responses to REST requests does not indicate the type of fields containing record IDs, this makes it impossible to reliably parse responses. The [docs](https://github.com/orientechnologies/orientdb/wiki/OrientDB-REST#json-data-type-handling-and-schema-less-mode) indicate that it should send an `"x"` to indicate `LINK`, but I never receive such a response.

This is related to #2243

**Comment by phpnode** [comment]
The same is also true for e.g. `EMBEDDEDMAP`,  `LINKMAP`, `LINKLIST` etc, it's essentially impossible to determine the type of these containers without guessing by peeking inside, or hoping that the field is described in the schema which is not guaranteed.

**Comment by lvca** [comment]
Supported LINK and LINKLIST. It's missing LINKMAP and EMBEDDEDMAP but they are not in the protocol as different type.
