### ISSUE TITLE
Incorrect warning on startup (2.0 RC-1); leads to bad behavior

### ISSUE THREAD

**Issue by zanerock** [orientechnologies/orientdb#3315]
I looks like the physical memory check is not dealing with the ',' ? Gives misleading warning and more seriously changes DISKCACHE.

2015-01-01 20:28:10:247 WARNING No enough physical memory available: 2,007MB (heap=61MB). Set lower Heap and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]

**Comment by laa** [comment]
Hi,
Could you be more specific ?

**Comment by zanerock** [comment]
Sure, the WARNING message seems to be inconsistent with itself. It's claiming that there is not enough physical memory and then quotes a number which clearly shows there is plenty of physical memory. (I've checked actual available memory too, and there's plenty; nothing else is running.) I.e., 2007 > 61.

The bad behavior is then to increase the disk cache unnecessarily. In this case, should be '0'.

Of course, also possible that the there is a problem and this is a 'wrong warning' problem. But in any case, the message at least appears to be incorrect.

**Comment by lvca** [comment]
We fixed this problem in 2.0-SNAPSHOT. Please could you try it?

**Comment by lvca** [comment]
Sorry, I was wrong. The message you refer is the one is given at run-time. Looking at it right now.

**Comment by lvca** [comment]
Gotcha. How much physical memory do you have on your server in total?

**Comment by zanerock** [comment]
2GB; it's virtual so I can move that around if useful for testing. I'm going off a note I saw that OrientDB can run with a relatively low footprint so starting it out at -Xmx64M

**Comment by lvca** [comment]
OrientDB can run with low RAM, but depends by your operations, database size, concurrency, etc. By the way we reduced occupied memory in 2.0-SNAPSHOT.

**Comment by zanerock** [comment]
That's my understanding. The DB is microscopic.
