### ISSUE TITLE
2.0: making non-lightweight edges the default breaks a LOT of documentation

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3325]
I've seen lightweight edges documented as the default for all new databases in several places in the wiki, here's one I ran across today: https://github.com/orientechnologies/orientdb/wiki/Choosing-between-Graph-or-Document-API

These should be found and fixed quickly or there might be more user confusion due to the change than there was using the lightweight edges.

**Comment by lvca** [comment]
Created new page: https://github.com/orientechnologies/orientdb/wiki/Lightweight-Edges and updated documentation.
