### ISSUE TITLE
Abort queries pre-emptively if heap usage is high to avoid OOM

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3326]
Using Runtime.getRuntime() or the like, it might be nice if every X (say 1000) records scanned in query, Orient checked if the heap was down to Y% space left (some configurable amount, maybe 10% by default). If so, then the query might abort itself with probability from 1-100%. Once the heap is down to Z% left (e.g 5%), the probability will always be 100%. The probability could factor in Y-Z (closeness to final threshold) and the number of rows the current query scanned so far (which would need to be tracked). This pretty much requires no coordination (e.g. locking) among the different threads handling queries if done with some simple assumptions.

An algorithm for the heap check method might look like:

``` java
if QUERY_ROWS_SCANNED < POOM_RECORD_SCAN_THRESHOLD
    return
percHeapLeft = 100 * (1 - CURRENT_HEAP_SIZE / MAX_HEAP_SIZE)
if percHeapLeft < Y
    percHeapLeftPreOOM = max( percHeapLeft - Z, 0 )
    antiweight = 1 - min( QUERY_ROWS_SCANNED / EST_MAX_RECORDS_SCAN, 1)
    rmax = (integer) pow(3, antiweight * percHeapLeftPreOOM) - 1
    if random.nextInt(rmax) == 0
        ...abort...
```

Provided:
Y = 10 (configurable)
Z = 5 (configurable)
EST_MAX_RECORDS_SCAN = 100000 (configurable)
POOM_RECORD_SCAN_THRESHOLD = 1000 (configurable)

A more expensive approach would be to actually track the count of rows scanned of all currently running queries in a table and the one with the highest would abort when the heap is near full. I don't know how much locking overhead this would have, it would depend a lot on X (check frequency).

**Comment by lvca** [comment]
Actually we fixed all known memory leak so far. The only operations that could consume heap in query are:
- order by: it's executed in RAM, @luigidellaquila has a good idea to store on such situation
- group by: it's executed in RAM, but it's quite cheap in comparison of order by
- synchronous query with big results: the result is collected in RAM

Which case of these do you have?

**Comment by AaronSchulz** [comment]
Don't queries acquire locks for READ_COMMITTED? That will still be O(N) memory usage. ORDER BY and GROUP BY are common (I'm using both atm). Also, in distributed mode, the coordinating server will have to do some map/reduce work in RAM right? That could be a of significant RAM usage too. Also, what about subqueries, are the implemented as chains of lazy iterators or do they ever get all the results first?

Are async queries streamed to the client? I use the HTTP interface right now and I'm not sure whether that builds up results or does streaming JSON. In any case, the queries always have LIMIT 1000 if nothing else (that may go up, but not beyond 10k I'd imagine).

**Comment by lvca** [comment]
I'd like to implement this issue asap. Your first algorithm would be super easy to implement.

**Comment by laa** [comment]
Hi Luca,
I have implemented very efficient one as part of Wal restore approach.
Problem with current one that we may be not in time to prevent OOM . For
example big TX commit will consume all memory and query still will throw
OOM . But if we use list of soft references and reference queue we will
able to detect memory problems on early stage and return result of
reasonable size so we 100% guarantee absence of OOM during query execution
. It does not require much resources to implement also.
23 Янв 2015 г. 18:42 пользователь "Luca Garulli" <notifications@github.com>
написал:

**Comment by lvca** [comment]
I like this idea. I tested a solution inspired by @AaronSchulz but doesn't work properly: in cases where you do:

    select from V limit 800000

Maybe the first time works, but then the JVM free memory remains low. This is because the GC is not executed between the 2 queries. Calling `System.gc()` is not an affordable solution, so we should rely on something else.

**Comment by laa** [comment]
I have no time to implement it right now but I can share my idea with
Luigi.
So he will be able to do it.

On Sun, Jan 25, 2015 at 3:03 PM, Luca Garulli <notifications@github.com>
wrote:

> I like this idea. I tested a solution inspired by @AaronSchulz
> <https://github.com/AaronSchulz> but doesn't work properly: in cases
> where you do:
>
> select from V limit 800000
>
> Maybe the first time works, but then the JVM free memory remains low. This
> is because the GC is not executed between the 2 queries. Calling
> System.gc() is not an affordable solution, so we should rely on something
> else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3326#issuecomment-71371907>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
