### ISSUE TITLE
(Client=55) Indexed query takes 2.2s

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3327]
Our main feed query takes 2.7s to complete. We get this query 10M+ times per month, and it is the first thing a user sees. Our entire goal with OrientDB was to make this query faster due to the heavy amount of joins it requires, so let's see how fast we can make it!

This query grabs a batch of 10 Posts:
```sql
SELECT
  @rid as @rid,
  @class,
  actionId,
  commentCount,
  facebook,
  featurePostOnDate,
  forcedPrivate,
  instagram,
  isReported,
  likeCount,
  note,
  photo,
  private,
  new,
  popular,
  twitter,
  createdAt,
  updatedAt,
  in_UserWrotePost
FROM indexvaluesdesc:Post.newFeed
WHERE new = true AND actionId IN [1,207,8,1300,2000,2001,2002,2003,2004] AND in_UserWrotePost.size() = 1 AND (private = false OR private IS NULL)
LIMIT 10
FETCHPLAN in_UserWrotePost.out:0 in_UserWrotePost.out.out_UserHasSettings:0 in_UserWrotePost.out.out_UserHasSubscription:0 in_UserWrotePost.out.out_UserHasPromoCode:0 in_UserWrotePost.out.out_UserAddedActivityLog:-2 in_UserWrotePost.out.out_UserAddedWeightLog:-2 in_UserWrotePost.out.out_UserAddedWorkoutLog:-2 in_UserWrotePost.out.out_UserBuiltWorkout:-2 in_UserWrotePost.out.out_UserClaimedPromoCode:-2 in_UserWrotePost.out.out_UserFollowsUser:-2 in_UserWrotePost.out.out_UserHadError:-2 in_UserWrotePost.out.out_UserLikesPost:-2 in_UserWrotePost.out.out_UserSentInvite:-2 in_UserWrotePost.out.out_UserWroteComment:-2 in_UserWrotePost.out.out_UserWrotePost:-2 in_UserWrotePost.out.in_NotificationIsFromUser:-2 in_UserWrotePost.out.in_NotificationIsToUser:-2 in_UserWrotePost.out.in_UserFollowsUser:-2
``` 

Here is the index:
```sql
CREATE INDEX Post.newFeed ON Post (new, actionId, createdAt) NOTUNIQUE
```

Simply selecting from the index is slow, as described at https://github.com/orientechnologies/orientdb/issues/3312, so I'm looking at any way to make this query faster. Without using the index directly, it is incredibly slow (I cut it off after 30s).

I'm also worried that query caching is not working, as running the query multiple times yields the same time (2.2s).

For some reason, since working on this query with @tglman a week ago, the speed of this query has more than doubled. I'm thinking this may be due to some recent changes, as we are using the latest commit in the `develop` branch.

This query speed for Binary Protocol is also dependent on https://github.com/orientechnologies/orientdb/issues/3248 and https://github.com/orientechnologies/orientdb/issues/3263, which are of higher priority, but this is next in line.

**Comment by luigidellaquila** [comment]
Hi @garrett-gottlieb 

I remember I changed that index removing "actionId", this way:

CREATE INDEX Post.newFeed ON Post (new, createdAt) NOTUNIQUE

and it reduced execution time to ~1 sec

Is it possible that you re-created it? (maybe I'm wrong and I don't remember correctly...)

**Comment by luigidellaquila** [comment]
Hi @garrett-gottlieb 

could you try my suggestion? Do you have a feedback about this?

**Comment by luigidellaquila** [comment]
@garrett-gottlieb I had no feedback about this, I'm closing.
Please re-open (or let's talk about it in chat) if needed
