### ISSUE TITLE
Unable to override default password for 'admin' (2.0-RC1)

### ISSUE THREAD

**Issue by zanerock** [orientechnologies/orientdb#3329]
To recreate, using 2.0-RC1

- setup new database in the 'storage'; define userName='admin' and userPassword="anything-but-admin" (I assume not a factor, but I'm random UUIDs); example:

<storage name="conveyor" path="plocal:/home/user/.conveyor/data/dogfoodsoftware.com/conveyor-core/databases/conveyor"
	       userName="admin" userPassword="d190386a-9341-40b7-9b66-0b29c3b665e7"
	       loaded-at-startup="true" />

- start database
- start console and attempt to connect to database using 'admin' and new password.

Result:

- it fails
- you can login with 'admin' as password, however

Also if the userName is not 'admin' (I tested with 'conveyor'), everything works fine.

**Comment by lvca** [comment]
admin is a database user, not server user. Look at:

http://www.orientechnologies.com/docs/last/orientdb.wiki/Security.html#work-with-users

**Comment by zanerock** [comment]
I agree; the response doesn't seem to answer the issue or I misunderstand your meaning. I'm trying to setup the database user 'admin' with a non-default password and it's not working.

**Comment by lvca** [comment]
What command have you used?

**Comment by zanerock** [comment]
Via the 'storages' element in 'orientdb-server-config.xml'. Updated original description (had my formatting wrong).

**Comment by zanerock** [comment]
And then started server with the 'server.sh' script.

**Comment by lvca** [comment]
In storages you enlisted your database, but how did you create it?

**Comment by zanerock** [comment]
That's what I mean; I listed the database in storage and then started server with the 'server.sh' script. The startup process creates any non-existent databases.
