### ISSUE TITLE
'V' class does not exist initially (2.0-RC1)

### ISSUE THREAD

**Issue by zanerock** [orientechnologies/orientdb#3330]
After creating a new database via the 'storage' element in the 'orientdb-server-config.xml', if I connect as the admin user and issue:

orientdb {db=conveyor}> CREATE CLASS Person EXTENDS V

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #27: Super-class V not exists
Command: create CLASS Person EXTENDS V
-----------------------------------^

orientdb {db=conveyor}> DELETE VERTEX

Delete record(s) '0' in 0.302000 sec(s).

orientdb {db=conveyor}> CREATE CLASS Person EXTENDS V

Class created successfully. Total classes in database now: 11

--------------

Additionally, issuing 'classes' initially does not show 'V' or 'E', but after the 'DELET VERTEX' both 'V' and 'E' show up.

**Comment by lvca** [comment]
How did you create the database? You should use "graph" as type. Starting from 2.0 this is by default. However you can create classes V and E in your database and everything works.

**Comment by zanerock** [comment]
It was created by inserting a 'storage' (plocal) element into 'orientdb-server-config.xml' file and then starting the database.

Is the 'graph' type documented yet? I'm referring to:

http://www.orientechnologies.com/docs/2.0/

**Comment by lvca** [comment]
It's when you create the database. Look at: 

http://www.orientechnologies.com/docs/last/orientdb.wiki/Console-Command-Create-Database.html

**Comment by zanerock** [comment]
Ahh, I see, the 'db-type'. It seems like there's still a problem though. If I create via the console, V and E show up fine. If I create via 'storage' element, they do not. It's acting as if the 'graph' default db-type not getting set for that route. And / or is there a way to specify that in the XML? (I looked but didn't find a 'dbType' attribute in the docs; I'll glance at the code.)

<storages>
      <storage name="conveyor" path="plocal:/home/user/.conveyor/data/dogfoodsoftware.com/conveyor-core/databases/conveyor"
               userName="conveyor" userPassword="password"
               loaded-at-startup="true" />
    </storages>
