### ISSUE TITLE
[bug]  sql SELECT via HTTP GET returns always only 20 results

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb#3331]
Hi,
thank you for this great DB !!!
sql SELECT via HTTP GET (query) always returns 20 results (even if LIMIT is set ie. 200)
SELECT via HTTP POST (command) and Binary sql select both work fine.
I've tried this on 2.0-M3 and  2.0-rc1

**Comment by AaronSchulz** [comment]
Note that using LIMIT in the SQL part of the URL does nothing, you have to use the /<LIMIT> in the end of URL. Where did you specify LIMIT?

This is slightly confusing though. Probably Orient should apply both (if any), the SQL one and then the URL one, like a subquery.

**Comment by SpareShade** [comment]
well, i have tried many variations
ie:
http://mylocal.local:2480/query/mydb/sql/select from MyClass/limit 200
response:
java.lang.NumberFormatException: For input string: "limit"

how is the query supposed to be formatted?

**Comment by dcardin** [comment]
Syntax: http://<server>:[<port>]/query/<database>/<language>/<query-text>[/<limit>][/<fetchPlan>]
http://mylocal.local:2480/query/mydb/sql/select from MyClass/200

for more info, see: 
http://www.orientechnologies.com/docs/last/orientdb.wiki/OrientDB-REST.html#query
