### ISSUE TITLE
Support `console.log()` or `print()` via JS

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#3332]
The docs refer to a `print(row)` function in JS, but calling this function does not appear to do anything. This makes debugging JS super awkward because there's no way to inspect the state of the system. It would be nice if `print()` pretty printed its argument to STDOUT, or ideally, if `console.log()` and `console.error()` were implemented to do the same thing (`console.error()` should write to STDERR).

**Comment by lvca** [comment]
@phpnode JS print() send output to the console. Look at OrientDB server output. However I like your proposal on providing support for console.

**Comment by phpnode** [comment]
@lvca ah thanks ok, I see it now, I was missing the output. The result is still not really helpful though, e.g. for this:
```js
var user = db.query("select from #5:0");
print(user);
return user;
```
I get something like: 
```
[Lcom.orientechnologies.orient.core.db.record.OIdentifiable;@3af3cfe
```

Ideally, I'd see something more like:

```json
    {
        "@type": "d",
        "@rid": "#5:0",
        "@version": 2,
        "@class": "OUser",
        "name": "admin",
        "password": "{SHA-256}8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918",
        "status": "ACTIVE",
        "roles": [
            "#4:0"
        ]
    }
```

**Comment by lvca** [comment]
That result is because the result set is a JS array of ODocument object. We could provide console.log() and error() that properly manage it
