### ISSUE TITLE
shortestPath or dijkstra BUGs in console

### ISSUE THREAD

**Issue by Stephanevincenza** [orientechnologies/orientdb#3333]
In a console, simply typing:
select shortestPath(#12:0:#12:7)
returns
Error: com.orientechnologies.orient.core.exception.OSerializationException: Found invalid ) character at position 70 of text shortestPath: [com.tinkerpop.blueprints.impls.orient.OrientVertex|#12:0),com.tinkerpop.blueprints.impls.orient.OrientVertex|#12:1),com.tinkerpop.blueprints.impls.orient.OrientVertex|#12:6),com.tinkerpop.blueprints.impls.orient.OrientVertex|#12:0)]. Ensure it is opened and closed correctly.

What is this ) ??????

**Comment by lvca** [comment]
You should specify comma (,) between RID. Try this:

    select shortestPath(#12:0, #12:7)

**Comment by Stephanevincenza** [comment]
Thanks you so much, but my copy paste from the window of my console didn't
work.
I've typed
select shortestPath(#12
<https://github.com/orientechnologies/orientdb/issues/12>:0, #12
<https://github.com/orientechnologies/orientdb/issues/12>:7)
and got the
I give you a screen capture to have a look. It seems to be a bug.
More than this, the ID's of the vertex given in the error are the good
ones. The shortestPath is retrieved.....


2015-01-05 12:45 GMT+01:00 Luca Garulli <notifications@github.com>:

**Comment by lvca** [comment]
I don't understand the problem. Is it the same as before or another one?

**Comment by Stephanevincenza** [comment]
Yes, this is the same problem but I MADE A ERROR when I sent you the first
issue. I mean when writing the message..... Sorry...
From the beginning, I typed
select shortestPath(#12:0,#12:7) in the console....  you can have a look on
the screen capture.


2015-01-05 13:07 GMT+01:00 Luca Garulli <notifications@github.com>:

**Comment by lvca** [comment]
I don't see any scree capture. Please could you use GitHub to comment the issue rather than the email? GitHub allows you to drag & drop images.

**Comment by Stephanevincenza** [comment]
![capture](https://cloud.githubusercontent.com/assets/10373149/5612946/f3e83c08-94dc-11e4-9837-33700287c4d0.jpg)

**Comment by lvca** [comment]
what OrientDB release are you using?

**Comment by Stephanevincenza** [comment]
1.7.10

**Comment by Stephanevincenza** [comment]
The strange thing is that the Id's of the nodes given in the error string (#12:0, #12:1, #12:6, #12:7) is the right shortest path from #12:0 to #12:7 in the set of records i'm using to developp my application. So it seems to be an error after the calculation of the shortest path.

**Comment by lvca** [comment]
Try to specify also directions:

    select shortestPath(#12:0, #12:7, 'BOTH')

**Comment by Stephanevincenza** [comment]
I've got the same error specifiying the direction. But I've found that
select shortestPath(#12:0,#12:7)
works fine in orientDB studio on the same server.......
And more
select expand(shortestPath) from (select shortestPath(#12:0,#12:7,'OUT')) works fine in the console.............
Finaly, that's what I wanted to obtain : the list of vertices traversed by the shortets path. So I've got my solution.
But It seems that there's really a bug you should try to correct.
In all case, I'd like to thank you so much for your reactivity.
Best regards
Stéphane VINCENZA

**Comment by lvca** [comment]
Maybe it's only a problem of spaces. Please could you try:

    select shortestPath( #12:0, #12:7, 'BOTH' ) 

(I've added more spaces before/after parenthesis).

**Comment by Stephanevincenza** [comment]
Doesn't work .... even with a space after the last )

**Comment by Stephanevincenza** [comment]
![capture2](https://cloud.githubusercontent.com/assets/10373149/5614591/e1dd4254-94f2-11e4-9953-51d60720edc5.jpg)

**Comment by Stephanevincenza** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/10373149/5614652/657a8946-94f3-11e4-90a1-245a14dd6c4e.jpg)

**Comment by Stephanevincenza** [comment]
It looks like a bug ......
Don't hesitate to ask to me for other tests.
Best regards

**Comment by lvca** [comment]
Ok, I'll leave this issue open.

**Comment by thejeed** [comment]
I'm not sure if I should comment on that because you propably saw this, but Stéphane wrote 
>I've got the same error specifiying the direction. But I've found that
>select shortestPath(#12:0,#12:7)
>works fine in orientDB studio on the same server.......
>And more
>select expand(shortestPath) from (select shortestPath(#12:0,#12:7,'OUT')) works fine in the >console.............
>Finaly, that's what I wanted to obtain : the list of vertices traversed by the shortets path. So I've got my >solution.
>But It seems that there's really a bug you should try to correct.
>In all case, I'd like to thank you so much for your reactivity.
>Best regards
>Stéphane VINCENZA

He provided two Screenshots for this. The errors on the first screenshot appear because he wrote 'shorttestPath' instead of 'shortestPath', so this wouldn't work, of course.

Best wishes,

David

**Comment by lvca** [comment]
@thejeed You're right I didn't get it before. Closing this issue...
