### ISSUE TITLE
shortestPath or dijkstra BUGs in console

### ISSUE THREAD

**Issue by Stephanevincenza** [orientechnologies/orientdb#3334]
Thanks to lvca, But my copy paste from the window of my console didn't work.
I've typed
select shortestPath(#12:0, #12:7)
and got this error
Error: com.orientechnologies.orient.core.exception.OSerializationException: Found invalid ) character at position  70 of text shortestPAth:[com.tinkerpop.blueprints.impls.orient.OrientVertex|#12:0),com.tinkerpop.blueprints.impls.orient.OrientVertex|#12:1),com.tinkerpop.blueprints.impls.orient.OrientVertex|#12:6),com.tinkerpop.blueprints.impls.orient.OrientVertex|#12:7)]. Ensure it is opened and closed correctly.

**Comment by lvca** [comment]
Why did you create another identical issue?
