### ISSUE TITLE
[1.7.10] data inconsistency when a class name contains @

### ISSUE THREAD

**Issue by giastfader** [orientechnologies/orientdb#3340]
Hi,
A user of mine found a problem that occurs when a class contains the @ character.

`````
orientdb {db=baasbox}> create class a@b
Class created successfully. Total classes in database now: 27
````
````
orientdb {db=baasbox}> insert into a@b content {"k":"v"}
Inserted record 'a@b#27:0{k:v,b@k:v} v1' in 0.004000 sec(s).

orientdb {db=baasbox}> select from a@b                  
----+-----+----
#   |@RID |b@k 
----+-----+----
0   |#27:0|v   
----+-----+----
1 item(s) found. Query executed in 0.001 sec(s).
`````
As you can see the inserted record is completely wrong. The "k" field became "b@k" .

**Comment by phpnode** [comment]
class names are not validated and this can cause some *particularly* unpleasant issues. IMHO they should be restricted to match `/^[A-Z_][A-Z0-9_]*$/i`

**Comment by lvca** [comment]
@phpnode is right, but OrientDB doesn't check for @. I've added @ as forbidden char.

**Comment by lvca** [comment]
Fixing field names
