### ISSUE TITLE
add an UNSAFE keyword for CREATE PROPERTY.

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#3341]
add to the CREATE PROPERTY an UNSAFE keyword to skip the persistent data check, this will speedup a lot the property creation, but should be documented properly because can lead to runtime errors.

**Comment by tglman** [comment]
implemented and linkded in this issue https://github.com/orientechnologies/orientdb/issues/3399 closing

**Comment by lvca** [comment]
@tglman you forgot the release....changing it
