### ISSUE TITLE
The word 'FROM' in square bracket clause's causes error

### ISSUE THREAD

**Issue by khendricks** [orientechnologies/orientdb#3347]
If you have the word "FROM" surrounded by spaces in a square bracket clause the query will return an error.

Ex:
```
SELECT in()[name = ' FROM '] FROM Object;
```

The errors are random:
Missing closed string character: '''
Class 'xxxxx' was not found in the current database

I tried other keywords but it seems FROM is the only one that messes things up.

This happens on 1.7.10, 2.0-rc1, and the 20150108 2.0 SNAPSHOT.

**Comment by khendricks** [comment]
Looks like this also happens with the 'LET' keyword.

**Comment by lvca** [comment]
@luigidellaquila is this already resolved?

**Comment by luigidellaquila** [comment]
no, AFAIK

**Comment by mathieubodin** [comment]
Got the same problem with property named 'from'. Got it working changing to 'fromXXX'

**Comment by luigidellaquila** [comment]
@mathieubodin FROM is a reserved word, so you should not be able to use it as a property name (there is another issue about avoiding this when creating schema). Also new parser will complain about this.

Another story is inside strings, where it's supposed to work fine

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot

**Comment by tglman** [comment]
by the way we could support 'select `from` from example' it should be quite easy in the new parser
