### ISSUE TITLE
OFunction and OScheduler as ODocumentWrapper

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3349]
Guys,

Classes OFunction and OScheduler operate as wrappers over corresponding ODocument, but, in fact, they are not extending ODocumentWrapper.

Do you mind if I rewrite this 2 classes? Extention of ODocumentWrapper gives following:
1) More solid architecture.
2) OOB ability in Orienteer to invoke operations on that classes if they extends ODocumentWrapper.

If you don't see any problems with this idea: I will send PR in a couple of days.

**Comment by PhantomYdn** [comment]
@lvca , Guys,

Please concider applying PR #3422

**Comment by lvca** [comment]
Merged, thanks! (I see you fixed also a few bugs...)
