### ISSUE TITLE
LUCENE * not working properly

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3353]
I have this:
```sql
create class Test extends V
create property Test.name string
create index Test.name FULLTEXT ENGINE LUCENE
create vertex Test set name  = 'a'
create vertex Test set name  = 'aa'
```

And this:
```sql
select from Test where name LUCENE 'a*'
```
returns only the second record.

In [this recommended link](http://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Wildcard%20Searches) says that the wildcard __*__  looks for 0 or more characters. 

What is happening?

**Comment by vitorenesduarte** [comment]
__+__ operator does also seem to have some problem.

`select from Test where name LUCENE '+a'`does not returns the first record;

`select from Test where name LUCENE '+aa'`returns the second record.

**Comment by maggiolo00** [comment]
i guess that 'a' 
is skipped as it is an English stop Word as the default analyzer is StandardAnalyzer

**Comment by vitorenesduarte** [comment]
Thanks @maggiolo00 
Can I define a new analyzer?

**Comment by maggiolo00** [comment]
Yes @vitorenesduarte 
see here
http://www.orientechnologies.com/docs/last/orientdb-lucene.wiki/Full-Text-Index.html

**Comment by vitorenesduarte** [comment]
:+1:
