### ISSUE TITLE
OJPAPersistenceProvider does not play well with other JPA providers on the classpath

### ISSUE THREAD

**Issue by tmcsys** [orientechnologies/orientdb#3355]
Does OJPAPersistenceProvider consult the `<provider>` tag in persistence.xml? 

I'm trying to deploy an OrientDB application with orientdb-object/1.7.10/orientdb-object-1.7.10.jar on the classpath.  Hibernate JPA is provided by the EE6 Application server.

The Hibernate provider is clearly identified in the persistence.xml file

```
<provider>org.hibernate.ejb.HibernatePersistence</provider>
```

On deployment, the server displays this message:

INFO `[com.orientechnologies.orient.object.jpa.OJPAPersistenceProvider]` (MSC service thread 1-1) Can't parse 'META-INF/persistence.xml' :Something goes wrong while parsing persistence.xml

Perhaps that's the key: it can not parse the file (which contains multiple persistence units) and so does not know that it should ignore the file.

Later, when the application tries to obtain an EntityManagerFactory, it throws this error:

```
java.lang.NullPointerException 
  at com.orientechnologies.orient.object.jpa.OJPAPersistenceProvider.createContainerEntityManagerFactory(OJPAPersistenceProvider.java:73)
  at com.orientechnologies.orient.object.jpa.OJPAPersistenceProvider.createEntityManagerFactory(OJPAPersistenceProvider.java:57) 
  at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:63)
  at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)
```

It appears that OJPAPersistenceProvider insists on handling the persistence unit, when persistence.xml indicates it should not.

It would be a simple matter to exclude orientdb-object from the classpath, but it contains orient.object.db classes required by my application.

This is the last step in replacing db4o, so any help in resolving this would be very much appreciated.

**Comment by arisAlexis** [comment]
any update on this? i am using the hibernate validator for other reasons in my program. i use maven

INFO: Can't parse 'META-INF/persistence.xml' :Something goes wrong while parsing persistence.xml

i get this message since i started using orient. excluding the oriendb-object artifact does not make a difference

**Comment by nkoterba** [comment]
+1 here.  

I'm trying to use Hibernate's JPA Persistence Provider `org.hibernate.jpa.HibernatePersistenceProvider` and also have the Orient provider on my classpath.

My persistence.xml is as follows:
```xml
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
             http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
             version="2.0">
    <persistence-unit name="admin">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
    </persistence-unit>
    <persistence-unit name="dev">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
    </persistence-unit>
</persistence>
```

In my unit tests, I need to obtain a factory for the above.  Here is that code:
```java
      this.emFactory = Persistence
          .createEntityManagerFactory(persistenceUnitName, persistenceProperties);
```

However, I **always** get the `OJPAPersistenceProvider` instance instead of Hibernate's even when explicitly using the `<provider>` tag in the `.xml` file and when also passing it directly as a persistenceProperty:
```java
properties.put(AvailableSettings.PROVIDER, "org.hibernate.jpa.HibernatePersistenceProvider");
```

@tmcsys Did you ever find a suitable workaround?

**Comment by nkoterba** [comment]
As a follow-up, I believe the issue lies here: https://github.com/orientechnologies/orientdb/blob/7e6e319fa04378c3b02c1ecc6bb49adb89aef457/object/src/main/java/com/orientechnologies/orient/object/jpa/OJPAPersistenceProvider.java#L68-69

```java
PersistenceUnitInfo unitInfo = PersistenceXmlUtil.findPersistenceUnit(emName, persistenceUnits);
return createContainerEntityManagerFactory(unitInfo, map);
```

Although the PersistenceUnitInfo is obtained there is no check to see if the `provider` for this JPA Persistence unit is indeed Orient or some other provider (like hibernate).

The hibernate JPA Provider does do such a check:
```java
// See if we (Hibernate) are the persistence provider
			if ( ! ProviderChecker.isProvider( persistenceUnit, properties ) ) {
				log.debug( "Excluding from consideration due to provider mis-match" );
				continue;
			}
```

Hibernate source: https://github.com/hibernate/hibernate-orm/blob/2964ecbf1b74003fcc337b0574487c724638fe94/hibernate-entitymanager/src/main/java/org/hibernate/jpa/HibernatePersistenceProvider.java#L109-112

**Comment by nkoterba** [comment]
@lvca I think this should actually be switched from an Enhancement to a Bug since OJPA should not satisfy persistence units with different providers.

**Comment by nkoterba** [comment]
So I was able to work around this issue by using the solution below. 

I set a persistence provider resolver and have it just return the Hibernate one.  This seems to work ok and not interfere with the underlying things going on in Orient:

```java
// TODO: Remove once Orient JPA Provider behaves well
		// See: https://github.com/orientechnologies/orientdb/issues/3355
		PersistenceProviderResolverHolder.setPersistenceProviderResolver(
				new PersistenceProviderResolver() {
					@Override
					public List<PersistenceProvider> getPersistenceProviders() {
						return Lists.newArrayList(new HibernatePersistenceProvider());
					}

					@Override
					public void clearCachedProviders() {
					}
				});
```

**Comment by xavier-atero** [comment]
Just for reference, I am copying the configuration and code required to set up Hibernate using @nkoterba workaround

**persistence.xml**
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0"
    xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="appJpaUnit">
        <!-- provider>com.orientechnologies.orient.object.jpa.OJPAPersistenceProvider</provider -->
		<provider>org.hibernate.jpa.HibernatePersistence</provider>
		
        <!-- JPA entities must be registered here -->
        <class>Automaticu.WebAPI.ManchesterPlan.Planning.Model.Agent</class>

        <properties>
            <property name="javax.persistence.jdbc.driver" value="com.orientechnologies.orient.jdbc.OrientJdbcDriver" />       
            <property name="javax.persistence.jdbc.url" value="jdbc:orient:remote:localhost/ManchesterPlan03" />
            <property name="javax.persistence.jdbc.user" value="admin" />
            <property name="javax.persistence.jdbc.password" value="admin" />
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQLDialect" />          
        </properties>
    </persistence-unit>
</persistence>
```

Not including:
``` xml
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQLDialect" />          
```
will throw the following exception:
```
org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
```


**build.gradle**
``` groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:2.0.5.RELEASE")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

bootJar {
    baseName = 'gs-rest-service'
    version =  '0.1.0'
}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

def orientDb = '3.0.0'

dependencies {
    compileOnly("org.springframework.boot:spring-boot-starter-data-jpa")
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("com.orientechnologies:orientdb-client:${orientDb}")    
    compile("com.orientechnologies:orientdb-object:${orientDb}")
    compile files("C:/orientdb-3.0.12/lib/orientdb-jdbc-3.0.12.jar")
    testCompile('org.springframework.boot:spring-boot-starter-test')
    testCompile('com.jayway.jsonpath:json-path')
}
```

**To get the entity manager**
``` java
        PersistenceProviderResolverHolder.setPersistenceProviderResolver(
                new PersistenceProviderResolver() {
                    @Override
                    public List<PersistenceProvider> getPersistenceProviders() {
                        return Lists.newArrayList(new HibernatePersistenceProvider());
                    }

                    @Override
                    public void clearCachedProviders() {
                    }
                });	
		      
		Map<String, String> properties = new HashMap<String, String>(); 
		properties.put(AvailableSettings.PROVIDER, "org.hibernate.jpa.HibernatePersistenceProvider");
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("appJpaUnit",properties);
		entity_manager = emf.createEntityManager();
```
