### ISSUE TITLE
Cosole might print obsolete database properties

### ISSUE THREAD

**Issue by mirobimbo** [orientechnologies/orientdb#3358]
Just small issue in console, but made me crazy for a while.
1) update database properties, eg
    
    ALTER DATABASE DATEFORMAT yyyy-MM
2) and then run 'info' or 'list properties', printed property value is not updated, eg there is still
    
    Date format                | yyyy-MM-dd

3) disconnect and reconnect is needed to get fresh values.

This is same also with other properties.
tried on 2.0-rc1

**Comment by lvca** [comment]
This is already fixed i 2.1.x when after an ALTER DATABASE command, the db info are reloaded.
