### ISSUE TITLE
Support a construct to deduplicate rows based on a field list

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3359]
Sometimes you want to query things like "get the last 10 different world champion winners". If you just wanted the people's IDs and the latest award dates, you could do:

SELECT personid,MAX(date) FROM WCWinners GROUP BY personid ORDER BY date DESC LIMIT 10

With a (date,personid) index and a _very_ smart query planner, this could be fast on massive tables. It would scan down the index in reverse date order and keep a map of (personid => date) for rows encountered, skipping rows that already exists in the map, eventually stopping when the map has 10 records. This works sense DESC order and the MAX go well together; the date value in the map _is_ MAX(date). This requires a complex query planner and is syntactically hard if you want more fields than just personid,MAX(date); what if you also wanted firstname,lastname? ANSI standard would require an aggregator for those, which would wreck performance since the above plan would not work.

A simple and powerful ability would be to avoid GROUP BY and instead do something like:

SELECT personid,date,firstname,lastname FROM WCWinners ORDER BY date DESC DEDUPLICATE BY personid LIMIT 10

This would scan rows by descending date, adding them to the result set if and only if no other row with the same personid was already added to the result set. Internally, a hash table could be used.

DEDUPLICATE BY <field>\* could take n-tuples of fields as an argument instead of just one field. It would be defined as being applied _after_ ORDER BY (which itself is after GROUP BY) and before LIMIT.

Implementing this shouldn't be complex (unlike GROUP BY stuff).

**Comment by AaronSchulz** [comment]
Any chance of something like this making it in 2.1/2.2?

**Comment by luigidellaquila** [comment]
Hi Aaron,

the roadmap for 2.1 is well defined and I'm afraid this will not be
included.
We can think about including it in 2.2, but we have to analyze it in detail
and give a formal definition of that (eg. will it take first row or last
one?).

Luigi


2015-02-17 11:02 GMT+01:00 Aaron <notifications@github.com>:

**Comment by AaronSchulz** [comment]
I was thinking FIRST, so it plays well with ORDER BY.

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
