### ISSUE TITLE
Fetchplan sometimes returns duplicates via binary protocol

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#3360]
Certain queries cause the same record to be prefetched more than once.

@tglman warned that this bug is *impossible*, but it seems to be occurring, [this test](https://github.com/codemix/oriento/commit/332a2fd1f070156c08d832442dd15cad8e612d9e) replicates the issue, thanks to @dmarcelino for reporting.

See https://github.com/codemix/oriento/issues/186 for more details.

**Comment by tglman** [comment]
fixed, closed
