### ISSUE TITLE
Index not triggered

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3362]
Hi,

```sql
create class Test extends V
create property Test.name string

create index TestLucene on Test (name) FULLTEXT ENGINE LUCENE

create vertex Test set name = 'mike'          (13:0)
...
create vertex Test set name = 'phoebe'      (13:3) 
```
After the above, this:
```sql
explain select from Test where name LUCENE '+mike'
```
shows that TestLucene index was triggered.

Now
```sql
alter database custom useLightweihghtEdges=true
create class Try extends E

create edge Try from 13:0 to 13:3
```
`select expand(in('Try')) from 13:3` returns mike as expected.
But:
```sql
explain select from (select expand(in('Try')) from 13:3) where name LUCENE '+mike'
```

shows that TestLucene index was not triggered.
Is this the expected behaviour?

After this I dropped the lucene index and created another:
```sql
drop index TestLucene
create index TestSBTREE on Test (name) UNIQUE
explain select from Test where name = 'mike'
```
and the last shows that this new index was triggered.

But:
```sql
explain select from (select expand(in('Try')) from 13:3) where name = 'mike'
```
does not trigger the index again.

Am I doing something wrong?

**Comment by lvca** [comment]
Indexes cannot be used when the target is a subquery. Try rather using Lucene with:

    select from Test where name = 'mike'

and cross the relationships you need.

**Comment by vitorenesduarte** [comment]
In a situation when I only have access to #13:3, you're suggesting that I have to call the database twice when I can do it only once?

@lvca , I don't understand why this was labeled as bug, but now it's not.

**Comment by lvca** [comment]
This should use the index:

    select from Test where name = 'mike' and out('Try') in #13:3

**Comment by vitorenesduarte** [comment]
It doesn't work.
And I've tried:
```
select from Test where name = 'mike' and #13:3 in out('Try')
```

But even if it did, it wouldn't be way slower?

**Comment by lvca** [comment]
Probably the fastest way would be:
```sql
select expand( intersect( $a, $b ) )
let $a = ( select expand( in('Try') ) from #13:3 )
let $b = ( select from Test where name = 'Mike' )
```

**Comment by vitorenesduarte** [comment]
Can't make it work. But it's not really the point since I believe is practically the same.
What you recommend is : __If you have indexes, don't use subqueries?__

**Comment by lvca** [comment]
Unfortunately the SQL engine is not so smart (yet), so such optimization are in charge to the user :-( However indexes are never used with sub-queries

**Comment by vitorenesduarte** [comment]
I have very few knowledge of the database world. If that is true, it's sad.

**Comment by lvca** [comment]
We're working to the new SQL engine where we could do smarter things.

**Comment by vitorenesduarte** [comment]
Nice!

@lvca can this not be closed then?
Just adress it to the milestone which you believe this will be fixed.

**Comment by lvca** [comment]
This is already part of new SQL engine feature set.
