### ISSUE TITLE
Property value can not be null [ONetworkProtocolHttpDb]

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3365]
A small portion of the time, queries like the following give errors:
```json
create edge HPwIV from #11:16849580 to #12:543 content {"val":252,"oid":2792359,"iid":17,"rank":0,"best":1,"sid":"Q2792359$879916EA-0DE8-4123-BACE-BAAFF182C819","qlfrs":{},"refs":{},"odeleted":null}
```
I sometimes get:
java.lang.IllegalArgumentException: Property value can not be null [ONetworkProtocolHttpDb]

The odeleted property is not set as being NOT NULL, it's just:
create property HPwIV.odeleted boolean;

Normally it should just unset that field (SET works like that already).

**Comment by tglman** [comment]
Hi @AaronSchulz,

I Found the reason of this exception, it come from:
https://github.com/orientechnologies/orientdb/blob/develop/graphdb/src/main/java/com/tinkerpop/blueprints/impls/orient/OrientElement.java#L536

It's seems made on purpose, you can work around it not sending the property at all, is it this a good workaround for you ?

**Comment by AaronSchulz** [comment]
I'm basically doing that work around already. 

This is really odd since I *can* do:
```
orientdb {db=WikiData}> create vertex V content {'id':3,'deleted':null}
Created vertex 'V#9:0{id:3} v1' in 0.003000 sec(s).
```

Maybe it's just edges?

**Comment by lvca** [comment]
You can disable this behavior by setting:

    alter database custom standardElementConstraints=false

Only in last 2.0-SNAPSHOT.

**Comment by ritesh0919** [comment]
Hi,

I am facing the below error:
Error in Pipeline execution: java.lang.IllegalArgumentException: Property value can not be null

I am using orientdb ETL too migrate a mapping table from a RDBMS to edge. This edge has got some properties and whenever there is a null as property value (of this edge), I see the above error. 

I even altered the database to set standardElementConstraints as false. But looks like it is of no affect. I am on orientdb community 2.2.0. 

Any help will be appreciated. 

Regards,
Ritesh

**Comment by lvca** [comment]
This issue is closed and different. Could you please open a new issue?

**Comment by ritesh0919** [comment]
Sure Luca
