### ISSUE TITLE
Can't replace an ODocument field value with a dirty version of the same value

### ISSUE THREAD

**Issue by stebbi** [orientechnologies/orientdb#3366]
Hi, 

I think there is a bug in ODocument.field(String, Object, OType...) at line ODocument.java:1059:

          if (iPropertyValue.equals(oldValue)) {

In the case I ran into, oldValue and iPropertyValue are ODocuments with the same RID and version, but oldValue is clean (dirty = false) and iPropertyValue is dirty (dirty = true). The equals method does not notice this and simply declares oldValue and iPropertyValue to be equal. 

The emerging behavior results in the following, which I think is a problem:

1. Query for an outer document with an inner document as a field value for field X
2. Clone the inner document and change the clone
3. Assign the changed clone to the field X of the outer document
4. Save the outer  
5. Nothing changes because the inner and the clone have the same identity and version

I'm pasting a test below that reproduces this. If the bug is in the equals method (it is, isn't it?) then I'd consider it fairly severe? 

I think, but haven't verified, that the behavior is as expected if the RID is removed from the clone, or if the clone is saved before the outer is saved. If the RID is removed from the clone then a single save of the outer is sufficient to save the outer and the clone. But if the clone has to be saved first, to retain the RID, then the result becomes a lot of unnecessary saves when the scenario is extended to a large tree rooted at the outer? 

Cheers, 

Stefan

**Comment by stebbi** [comment]
package com.orientechnologies.orient.core.record.impl;
    
    import static org.junit.Assert.*;
    
    import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
    import com.orientechnologies.orient.core.sql.query.OSQLSynchQuery;
    import org.junit.After;
    import org.junit.Before;
    import org.junit.Test;
    
    import java.util.List;
    
    public class ODocumentTest {
    
        private ODatabaseDocumentTx tx;
    
        @Before
        public void setup() {
            tx = new ODatabaseDocumentTx("memory:test/ODocumentTest");
            tx.create();
        }
    
        @After
        public void teardown() {
            tx.drop();
            tx.close();
        }
    
        /**
         * 1. Creates an outer ODocument with an inner ODocument as a
         * field value.
         *
         * 2. Changes the inner document and verifies that
         * the change is revealed when accessed through the outer
         * document.
         *
         * 3. Clones the inner document, changes the clone and
         * verifies that the change does not affect the outer document.
         *
         * 4. Attempts to replace the inner with the (unsaved) clone but
         * (incorrectly?) fails because OrientDb considers the clone
         * equal to the inner, even though the inner is clean and the
         * clone is dirty (inner dirty = false, outer dirty = true).
         */
        @Test
        public void testField() {
            // Create the inner:
            ODocument odx = new ODocument();
            odx.field("x1", "x1v1");
            odx.save();
            List<ODocument> rs1 = tx.query(new OSQLSynchQuery<ODocument>(
                "select from cluster:default"));
            ODocument inner = rs1.get(0);
    
            // Create the outer:
            ODocument ody = new ODocument();
            ody.field("y1", "y1v");
            ody.field("yx", inner);
            ody.save();
            List<ODocument> rs2 = tx.query(new OSQLSynchQuery<ODocument>(
                "select from cluster:default where y1 = 'y1v' "));
            ODocument outer = rs2.get(0);
    
            // Check the inner and outer are as expected:
            assertEquals("#3:0{x1:x1v1} v1", inner.toString());
            assertEquals("#3:1{y1:y1v,yx:#3:0} v1", outer.toString());
    
            // Change the inner and verify the change affects the outer:
            inner.field("x1", "x1v2");
            assertEquals("x1v2", inner.field("x1"));
            assertEquals("x1v2", outer.<ODocument>field("yx").field("x1"));
    
            // Clone the inner, change the clone and verify the change does
            // not affect the outer:
            ODocument clone = inner.copy();
            assertEquals(inner.getIdentity(), clone.getIdentity());
            assertEquals(inner.getVersion(), clone.getVersion());
            assertEquals(inner, clone);
            clone.field("x1", "x1v3");
            assertEquals("x1v3", clone.field("x1"));
            assertEquals("x1v2", inner.field("x1"));
            assertEquals("x1v2", outer.<ODocument>field("yx").field("x1"));
    
            // Weirdness ensues:
            assertNotEquals(clone.field("x1"), inner.field("x1")); // OK
            assertEquals(inner, clone); // Huh???
    
            // Attempt to change the outer by replacing the inner with
            // the clone; this is actually a no-op:
            outer.field("yx", clone);
    
            // The field should have been updated but wasn't:
            assertEquals("x1v3", outer.<ODocument>field("yx").field("x1"));
    
            // The last assertion fails because outer.field("yx", clone)
            // is a no-op:
            /*
            org.junit.ComparisonFailure:
            Expected :x1v3
            Actual   :x1v2
                    <Click to see difference>
                    at org.junit.Assert.assertEquals(Assert.java:115)
            at org.junit.Assert.assertEquals(Assert.java:144)
            at com.orientechnologies.orient.core.record.impl.ODocumentTest.testField(ODocumentTest.java:87)
            */
        }
    }

**Comment by stebbi** [comment]
I have to work around this issue somehow to keep going with my code, figure I'll type up what I come across in case it helps.

Here is ORecordAbstract.equals:

    @Override
    public boolean equals(final Object obj) {
      if (this == obj)
        return true;
      if (obj == null)
        return false;
  
      if (obj instanceof OIdentifiable)
        return _recordId.equals(((OIdentifiable) obj).getIdentity());
  
      return false;
    }

This is simply using the RID to decide, so equals is purely identity-based, which causes the problem. 

If two versions (e.g. versions 1 and 2) with the same RID are compared, they're equal. This definitely seems wrong to me. 

And if an unsaved, modified (dirty) copy is compared with the original, they're equal. This is what I'm dealing with. 

Perhaps a solution would be to modify the equals method to consider identify *and* version, then also modify ODocument.field to also consider the dirty bit? Or perhaps a equals should be value-based?

A full value-based equals might work like so:

1. Equality first compares RID (false if different)
2. Then version (false if different)
3. Then the dirty bits (false if different)
4. Then value-by-value 

Value-by-value has the added complication of figuring out where to stop if the document is linked into a large graph. A "can't compare" runtime exception might have to be thrown. This doesn't sound great...?

The value-based hashCode can be derived analogously, with the same caveat about deep value-by-value. 

With value-based equals/hashCode it would no longer be possible to hold ODocuments in a hash and replace an existing, unmodified document with a new version or a modified clone, which is possible now. Etc.

**Comment by tglman** [comment]
Hi @stebbi,

The design of the ODocument API was made on purpose to not allow two ODocument instance of the same record during the same session, this was made to guarantee consistency in the session and eventual transaction.

We suggest to apply the changes directly on the document instances that come from the database and save them.

so this is not a bug, is the expected way to behave.

**Comment by stebbi** [comment]
Alright, fair enough. I will try to work around like you suggest. Can't say I quite like the outcome, but I appreciate that you guys took the time to look into this :)
