### ISSUE TITLE
order by@rid desc in 1.7.10

### ISSUE THREAD

**Issue by axXYgiGG8bB6kAntAxJ0Dymfk5eRHl** [orientechnologies/orientdb#3369]
According:https://github.com/orientechnologies/orientdb/wiki/SQL-Query

Order by record creation. Starting from 1.7.7, using the expression "order by @rid desc", allows OrientDB to open an Inverse cursor against clusters. This is extremely fast and doesn't require classic ordering resources (RAM and CPU):

I'm almost sure it has worked in 1.7.9 but in 1.7.10
orientdb {db=abcde}> select * from Customer order by @rid desc                

----+------+----+-------------------------+--------+-------+-----
#   |@RID  |name|email                    |accounts|wallets|phone
----+------+----+-------------------------+--------+-------+-----
0   |#26:0 |null|ik@email.cz         |[1]     |[0]    |null 
1   |#26:1 |null|jiroupil.cz         |[1]     |[0]    |null 
2   |#26:2 |null|tiail.com     |[0]     |[3]    |null 
3   |#26:3 |null|michalkroo@gmail.com     |[1]     |[2]    |null 
4   |#26:4 |null|ac@gmail.com   |[0]     |[2]    |null 
5   |#26:5 |null|jirich@gmail.com  |[0]     |[2]    |null 
6   |#26:6 |null|rich@gmail.com      |[0]     |[2]    |null 
7   |#26:7 |null|jiriek@web.de        |[0]     |[2]    |null 
8   |#26:8 |null|honcbi-net.cz         |[0]     |[1]    |null 
9   |#26:9 |null|jard@centrum.cz|[0]     |[1]    |null 
10  |#26:10|null|wdotmail.com       |[0]     |[2]    |null 
11  |#26:11|null|vaaromersky.org    |[0]     |[1]    |null 
12  |#26:12|null|webmdata.org          |[0]     |[1]    |null 
13  |#26:13|null|proid@gmail.com    |[1]     |[2]    |null 
14  |#26:14|null|zelquick.cz           |[0]     |[3]    |null 
15  |#26:15|null|kuta@seznam.cz      |[4]     |[17]   |null 
16  |#26:16|null|iammaly.net        |[0]     |[1]    |null 
17  |#26:17|null|seentrum.cz         |[1]     |[2]    |null 
18  |#26:18|null|luk@gmail.com     |[1]     |[0]    |null 
19  |#26:19|null|jos@atlas.cz|[0]     |[4]    |null 
----+------+----+-------------------------+--------+-------+-----
the order does not seem descending anymore.

**Comment by axXYgiGG8bB6kAntAxJ0Dymfk5eRHl** [comment]
I tested it with 1.7.9 and I confirm it works!

**Comment by lvca** [comment]
Have you tried with 2.0-SNAPSHOT?
