### ISSUE TITLE
Sub-query + $parent.$current

### ISSUE THREAD

**Issue by MarcelPitch** [orientechnologies/orientdb#3372]
Hi all,

I'm working with **OrientDB 2.0-RC1** and **Oriento 1.0.0**.

Here's a part of my db schema :

![capture](https://cloud.githubusercontent.com/assets/7402969/5701803/e015e8c8-9a50-11e4-8d2c-23c9beaeeee9.PNG)

I execute this request in order to get all the comments for a post, ordered by creation date descending :

```SQL
SELECT
	uuid,
	data
FROM
(
	SELECT
		expand(out('HAS_COMMENT'))
	FROM
	(
		SELECT 
		FROM 
			Post 
		WHERE 
			uuid = '1'
	)
	ORDER BY
		creation_date DESC
)
```
With **OrientDB Studio**, I have this result :
```JSON
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:1",
            "@version": 0,
            "uuid": "2",
            "data": "My first comment"
        },
        {
            "@type": "d",
            "@rid": "#-2:2",
            "@version": 0,
            "uuid": "3",
            "data": "My second comment"
        }
    ],
    "notification": "Query executed in 0.01 sec. Returned 2 record(s)"
}
```

-----------------------------------

Now, I have to write the request this way (cause it's just a part of a more complex one) :
```SQL
SELECT
	$Comments AS comments
FROM
	Post
LET
	$Comments = (
					SELECT
						uuid,
						data
					FROM
					(
						SELECT
							expand(out('HAS_COMMENT'))
						FROM
							$parent.$current
						ORDER BY
							creation_date DESC
					)
				)
WHERE
	uuid = '1'
```
With **OrientDB Studio**, I have this result :
```JSON
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:1",
            "@version": 0,
            "comments": [
                {
                    "@type": "d",
                    "@rid": "#-2:1",
                    "@version": 0,
                    "uuid": "2",
                    "data": "My first comment"
                },
                {
                    "@type": "d",
                    "@rid": "#-2:2",
                    "@version": 0,
                    "uuid": "3",
                    "data": "My second comment"
                }
            ]
        }
    ],
    "notification": "Query executed in 0.012 sec. Returned 1 record(s)"
}
```

I'm surprised to see the same temporary RID for the main `result` and the first `comments`.

And, in my **node.js** program, I can't access the first `comments` cause there's a circular reference for `#-2:1`. 

Is it normal ?

If so, is there any workaround for this case ?

Thanks !

**Comment by MarcelPitch** [comment]
Hi,

same result with **2.0-rc2**.

**Comment by MarcelPitch** [comment]
Hi,

Sorry but may I come back to you for this question ?

I know it's not a priority for this **2.0 Final Release day** :), but it would be very nice !

 I have to confess it's blocking for my development cause many queries depend of this question.

Thanks and good luck for today !

**Comment by lvca** [comment]
Unfortunately the sub query start from -1 with RID assignment. I'm working to have a unique RID also on sub-queries.

**Comment by MarcelPitch** [comment]
OK Luca, great !!!

Thank you for your answer !

**Comment by MarcelPitch** [comment]
Great, Luca !!!

I don't have this problem anymore !

Thank you

**Comment by tglman** [comment]
tests on ci are failing, disabled the test and reopened the issue
