### ISSUE TITLE
Error: Type LINKBAG not supported to convert value

### ISSUE THREAD

**Issue by sowee15** [orientechnologies/orientdb#3375]
Hi,

Using the binary protocol v21 on release 1.7.8 from 2014-08-13, I am getting the error "Type LINKBAG not supported to convert value [size=117]" in the orientdb console when running this query:

select in_E_LinkedTo.out.out_E_Created

By.in.in_E_CreatedBy from #33:3

#33:3 has many "things" linked to it through E_LinkedTo, each one has one edge E_CreatedBy pointing out to a user. The goal of the query is to get all the stuff created by the users who created the things linked to #33:3.

Maybe there's a better way to express this query, but should this query be valid? What could be the source of the error I am getting? Please find a log of the error at the end of this message.

Thanks!

PS. I am using a .net driver (https://github.com/yojimbo87/OrientDB-NET.binary). I am a contributor on this project.

PPS. Here's a link to the discussion related to this issue on google group: https://groups.google.com/d/topic/orient-database/xu5w95QzaJs/discussion

Error log:
2015-01-07 19:35:58:042 INFO /127.0.0.1:51269 - Writing bytes (4+0=4 bytes): null [OChannelBinaryServer]Error on unmarshalling record #-2:1 (java.lang.IllegalArgumentException: Type LINKBAG not supported to convert value: [size=117])
Type LINKBAG not supported to convert value: [size=117]
-> com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.fieldTypeToString(ORecordSerializerStringAbstract.java:229)
-> com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.embeddedCollectionToStream(ORecordSerializerCSVAbstract.java:823)
-> com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:520)
-> com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:495)
-> com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:673)
-> com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:258)
-> com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.toStream(ORecordSchemaAwareAbstract.java:420)
-> com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.toStream(ORecordSchemaAwareAbstract.java:415)
-> com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:446)
-> com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:337)
-> com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:118)
-> com.orientechnologies.orient.server.network.protocol.binary.OAsyncCommandResultListener.result(OAsyncCommandResultListener.java:56)
-> com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:531)
-> com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:474)
-> com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:437)
-> com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:925)
-> com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:383)
-> com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:344)
-> com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:60)
-> com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:94)
-> com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:83)
-> com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:69)
-> com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:29)
-> com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1181)
-> com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:340)
-> com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:169)
-> com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)

**Comment by tglman** [comment]
hi @sowee15, 

Do you have a test case to reproduce this ? it will speed up a lot things.

**Comment by sowee15** [comment]
No, I can't send our database. I could check to create one from the GratefulDeadConcerts, but I can't today. Let me know if you're unable to reproduce it and I'll look into it.

**Comment by tglman** [comment]
any news about this ?
