### ISSUE TITLE
doc.removeField() works not as expected

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3377]
Guys,

Following testcase is failing (please read comments):

```java
       @Test
	public void testRemovingReadonlyField()
	{
		ODatabaseDocument db = ODatabaseRecordThreadLocal.INSTANCE.get();
		OSchema schema = db.getMetadata().getSchema();
		OClass classA = schema.createClass("TestRemovingField");
		classA.createProperty("name", OType.STRING);
		OProperty property = classA.createProperty("property", OType.STRING);
		property.setReadonly(true);
		
		ODocument doc = new ODocument(classA);
		doc.field("name", "My Name");
		doc.field("property", "value1");
		doc.save();
		
		doc.field("name", "My Name 2");
		doc.field("property", "value2"); //setting of value to readonly document
		doc.removeField("property");  //we changed our mind: decided don't modify readonly field
		doc.save();  // failing right here
	}
```

**Comment by PhantomYdn** [comment]
Btw, this failing as well:

```java
@Test
	public void testRemovingReadonlyField2()
	{
		ODatabaseDocument db = ODatabaseRecordThreadLocal.INSTANCE.get();
		OSchema schema = db.getMetadata().getSchema();
		OClass classA = schema.createClass("TestRemovingField2");
		classA.createProperty("name", OType.STRING);
		OProperty property = classA.createProperty("property", OType.STRING);
		property.setReadonly(true);
		
		ODocument doc = new ODocument(classA);
		doc.field("name", "My Name");
		doc.field("property", "value1");
		doc.save();
		
		doc.field("name", "My Name 2");
		doc.field("property", "value2");
		doc.undo(); //we decided undo everything
		doc.field("name", "My Name 3"); //change something
		doc.save();
	}
```

In a meanwhile, let me propose small enhancement: please allow to undo just 1 field.

**Comment by tglman** [comment]
Hi @PhantomYdn,

The scope of removeField is not revert to the previous value, as today there's no api for do that, the correct way to do it is with undo, as is shown in your second test case.
I fixed it, now the second test case work as expected.

Anyway thank you very much, you issue are everytime filled of perfect details and test cases.

closing

**Comment by PhantomYdn** [comment]
Thank you, @tglman,

Can you please add "undo()" just for 1 field?

Let me clarify a use case.

There is a possibility to have "calculable" properties in [Orienteer](https://github.com/PhantomYdn/Orienteer).  The value is calculated either onRead or onWrite(this type is in a road map). Functionality is implemented by [special hook](https://github.com/PhantomYdn/Orienteer/blob/master/orienteer-core/src/main/java/ru/ydn/orienteer/hooks/CalculablePropertiesHook.java).

Logic is simple (for onRead calculation):
1. onRecordAfterRead() we are calculating value and updating document accordingly
2. onRecordBeforeUpdate() we should clean value before actual storing of the document

And problem is in p.2: if property defined as "read-only" it's not possible to clear just one that field. As a work around calculable attribute should not be marked "read-only", but that's quite strange for calculable attribute.

So, if you can provide functionality to undo() or clear() just one field it will be really appriciated!
