### ISSUE TITLE
How to create an index over an property which is a list of objects in OrientDB?

### ISSUE THREAD

**Issue by dharmax** [orientechnologies/orientdb#3378]
0 down vote favorite
	

i'd like a class that stores a structure such as this: 
{ 
   name: "blabla", 
   metaData: [ {a: "mya"}, { a:"mya2"} ]
}

Now, i would like to have an index over the metaData[?].a fields.

    1. What is the best way to represent this metaData in a schema? As an embeddedList?
    2. Is it possible to have that index i want?
    3. If so, who should the query for retrieving an entity by it's "a" value should look like?
    4. Alternatively, if we have, instead of that metaData, a field called "myAs" that is a simple array of string - would it be easier?

Note that i'm using the Node.JS oriento library.

Thank you.

**Comment by luigidellaquila** [comment]
Hi @dharmax 

in current release indexing on embedded properties is not supported. There is an issue for this, https://github.com/orientechnologies/orientdb/issues/2945 so this is a duplicate, I'm going to close it.
Please, watch the other issue to stay in touch with its evolution, it will be addressed in next release.
