### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3380]
Hi,
To get all the posts of the users that __11:0__ is following I tried:
```sql
SELECT expand(out_Follows.out_Posts) FROM 11:0
```
This only gave the RIDs. Why?

To accomplish the desired I had to:
```sql
SELECT expand(out_Posts) FROM (SELECT expand(out_Follows) FROM 11:1) 

# or

SELECT expand(value) FROM (SELECT expand(out_Follows.out_Posts) FROM 11:0) 
```

Is there a better way?
Thanks,

**Comment by lvca** [comment]
Try this:

    SELECT expand(out('Follows').out('Posts')) FROM 11:0

**Comment by lvca** [comment]
Uses always out/in/both and outE/inE/bothE functions instead of fields.

**Comment by vitorenesduarte** [comment]
Thanks :+1:
