### ISSUE TITLE
Memory Leak during Massive insert

### ISSUE THREAD

**Issue by GrumpyPants** [orientechnologies/orientdb#3381]
Hey all,
    I've been getting Out of Memory errors when trying to import a largish graph (12 million vertex, 90 million edges) into orientdb using the Java API. With this latest version (I tweaked some settings) of project linked below memory is constantly climbing and  i'm still expecting it to get OOM but processing has not finished yet. I will post results once I get back from work and it finishes running. Any insight you might have would be appreciated thank you!

OrientDB version: orientdb-community-2.0-M3
OS: Windows 7
hardware: 16gb RAM, 200G available disk space

ImportGraph http://pastebin.com/rxhZRCAc

NodeCreator http://pastebin.com/Ne14ec9U

RelationshipCreator http://pastebin.com/nxt9FCnF

**Comment by 8forty** [comment]
In our experience building long chains of vertex-edge-vertex-edge... in java with a variable in memory that holds the beginning vertex will cause (client-side) memory-use to grow unbounded.  We had to modify our code to build the chains in smaller pieces (a few hundred vertex/edges at a time seemed to be the max with 4G available for client), then commit and free the original vertex variable(s) and start a new transaction from the last saved vertex.

**Comment by GrumpyPants** [comment]
Hmm do you think I would be having the same issue even though I am not
using transactions? Also could you clarify on how I would "free up" vertex
variables in my case? They are done one at a time in a method not in a for
loop so I'm unsure how I would do that... Thanks for the quick reply by the
way!

**Comment by tglman** [comment]
Hi @GrumpyPants,

did you tried to run with the  orientdb-community-2.0-rc2, since the M3 we fix a few leaks and reduced the overall memory usage, so i think this is already fixed.

**Comment by GrumpyPants** [comment]
Hello tglman,

No I have not tried rc2 yet. I will try that once I get home today and post
results. Thank you.

**Comment by 8forty** [comment]
Sure, so we had some base vertexes (in a variable in memory) that were the front end of chains connected edge-vertex-edge-vertex... thousands long.  We were creating a committing transactions in chunks, but because we kept the base vertexes in memory the entire chains were also being kept in memory.  So once we "freed" them (i.e. by using a local variable in separate function for each chain rather than a set of variables initialized at the start of a loop) we saw the memory usage on the client go back the familiar saw-tooth pattern.

**Comment by GrumpyPants** [comment]
Just got back from work. The import process is still running from this morning. About 9 hours now. No OOM yet but it is creating edges much slower. Process is consuming 10 gb of ram so far. Looks to be slowly climbing as well? Hard to tell to be honest. I wonder if I were to let it run for the rest of the day if it would finish or if I would get OOM. I'm going to cancel and try with rc-2. Will post results.

**Comment by GrumpyPants** [comment]
8forty, 
    I believe I understand your scenario now. Am I incorrect in saying that it does not apply to my situation based on how my code is layed out? I'm not keeping any vertices in memory (as far as I know). I'm just directly adding vertices/edges to the graph. I am not using transactions either so while I really do appreciate your help I don't think it will help me in this case.

**Comment by GrumpyPants** [comment]
Process has been running for about 30 minutes now and the memory is steadily rising still. I suspect it would get OOM if I let it run overnight. I am trying to get heap dump for you all but i'm not too familiar on how to do that so I am looking it up now.

**Comment by lvca** [comment]
@GrumpyPants a thread dump would be useful, and also a dump of memory since this is your problem. You could use the FREE trial of YourKit or any other Java Profiler. With such tools it's quite easy to find who is responsible of keeping object in heap.

**Comment by GrumpyPants** [comment]
Here is a "leak report" from MAT (http://i.imgur.com/1jxQJ7R.png). Is this useful at all? Maybe I didn't generate it correctly. Sorry, I am a little out of my depth if you can't tell haha. I will try and get a thread/ memory dump for you.

**Comment by GrumpyPants** [comment]
Thread dump http://pastebin.com/aHeXx2uZ

**Comment by GrumpyPants** [comment]
Objects with most retained heap http://i.imgur.com/TDz6874.png. Memory is still climbing but at a much slower rate. It has imported 10 out of ~90 million edges. Maybe it will finish this time? Going to let it run over night unless anyone has any other ideas.

**Comment by lvca** [comment]
How is going after 15 hours? I see 25M of cache objects. Is 25M the number of object or RAM?

**Comment by tglman** [comment]
No answer so far, i consider this fixed, most of the object showed in the screenshots are associated to caches.

closing

**Comment by GrumpyPants** [comment]
Hey everyone. Sorry for the delayed response. I checked it the following night and it looks like it imported correctly. Memory was indeed slowly climbing the entire time but I guess my memory was big enough that it didn't go out of memory this time with the changes I made I guess. Thanks for all your help everyone.
