### ISSUE TITLE
Pivoting link in documentation returns 404

### ISSUE THREAD

**Issue by ronin1** [orientechnologies/orientdb#3383]
In performance tuning page for example: http://www.orientechnologies.com/docs/last/orientdb.wiki/Performance-Tuning.html

Your "pivoting" link returns 404 under the "Right use of Graph" section:
http://www.orientechnologies.com/docs/last/orientdb.wiki/Pivoting-With-Query.html

**Comment by lvca** [comment]
That doc is old. Removed. Thanks.
