### ISSUE TITLE
WARNING messages in case of common mistakes

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3386]
We already have done something with DiskCache and RAM setting. Now we need to report common mistakes to users by writing WARNING message to the console. Below the cases:
- [x] Query scan where scanned records are major than X (X=50k)
- [ ] Query result set is bigger than X (X=10k)

**Comment by vitorenesduarte** [comment]
:+1:

**Comment by lvca** [comment]
Created OProfiler.reportTip() to make this easier and avoid multiple messages of the same tip.

**Comment by lvca** [comment]
Now HTTP "command" and "query" commands returns a new array "warnings" in case tips are found in query. Studio will report them in nice way.
