### ISSUE TITLE
Problem with threadlocal listener mgmt when embedding

### ISSUE THREAD

**Issue by jdillon** [orientechnologies/orientdb#3389]
In rc2 seeing lots of NPE due to threadlocals helpers having null state, where rc1 worked fine.

I'm guessing these (and related) changes are culprit:

https://github.com/orientechnologies/orientdb/issues/3219

This looks related:

https://github.com/orientechnologies/orientdb/issues/3387

And seems to stem from this:

https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/orient/core/Orient.java#L290

Introduced recently by:

https://github.com/orientechnologies/orientdb/commit/2001365e56722bcb2db21ab80dfac9f8d6dc210c

**Comment by jdillon** [comment]
```
Caused by: java.lang.NullPointerException: null
at com.orientechnologies.orient.core.serialization.serializer.ONetworkThreadLocalSerializer.getNetworkSerializer(ONetworkThreadLocalSerializer.java:33)
```

I also have run into the same NPE reported in https://github.com/orientechnologies/orientdb/issues/3387 and likely any other part of the codebase that uses listeners to manage threadlocal state also have the same problem after the very recent changes to this internal implementation.

**Comment by lvca** [comment]
Ok, seems a simple NPE. Fixing it now...

**Comment by jdillon** [comment]
Unsure its a simple NPE, but you guys know best.  Looks like its a problem of clearing the listeners on shutdown() that are only created/registered when the class is loaded.  So subsequent usage to startup another embedded instance will fail and have no means to re-register those listeners that establish the expected state for the threadlocal helpers.

**Comment by PhantomYdn** [comment]
Thank you @jdillon from bringing this up.

According to my observations: problem is somewhere in shutdown-startup synchronization.

So my opinion is following: of course, that might be fixed by introducting getInstance() (see some comment regarding that below), but it will just hide mode deeper problem with lifecycle synchronization...

Comment regarding INSTANCE: I don't know why you decided to use "public static XXX INSTANCE" plus listeners construction instead of having instance private and lazy method getInstance(): but I think, that first approach is much dangerous.

**Comment by PhantomYdn** [comment]
@lvca , your fix doesn't fix all listeners related issues. Please take a look to my issue: #3387

**Comment by jdillon** [comment]
Right, all of the listeners are going to have this problem due to having them all removed on shutdown() and never put back, since that only happens when the class loads once.

**Comment by PhantomYdn** [comment]
Ooo, I see... You are absolutly right!:) Just checked on my case. But, you know, strange thing is following: it's not 100% reproducable... In my case it's 100% reproducable just on travis-ci, but on my own env: just from time to time. And I can't figure out why... So might be just something wrong with synchronization...

**Comment by jdillon** [comment]
Yes its odd, I couldn't make a simple repro either, and it behaved differently on java7 and java8... its a race of some sort, could be related to the introduction of weak-refs to track these as well, but can't say 100%

**Comment by jdillon** [comment]
personally would like to see those changes reverted, but thats just my preference... hopefully @laa can sort out a solution that fixes the reported leak and also don't mess up the embedding.

**Comment by jdillon** [comment]
FTR I'm still seeing problems with various threadlocal wrappers after this change:

https://github.com/orientechnologies/orientdb/commit/f0cca38b714fd2531812ca03ba0479a55d6b6fd8

**Comment by jdillon** [comment]
Tested this change https://github.com/orientechnologies/orientdb/commit/6e84112fb388b27ac54a80d61ca5fe1dcdb8110b and seems *much* better now.

**Comment by lvca** [comment]
Can we fix it?

**Comment by jdillon** [comment]
@lvca so far it looks as if its fixed post this change yes.  I think @laa also felt he understood why it broke now so unless I find anything else I think its sorted.
