### ISSUE TITLE
broken pipe [ONetworkProtocolHttpDb]

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb#3395]
Not sure if this should be here, but just in case:

Artwork has some 50,000 + records

querying it via http breaks down (and it takes a while):  

```
2015-01-15 20:20:33:971 SEVERE Internal server error:
java.net.SocketException: Broken pipe [ONetworkProtocolHttpDb]
```

 php error

```
Doctrine\OrientDB\Binding\Client\Http\CurlClient has been unable to retrieve a response for the resource at http://127.0.0.1:2480/command/galleryapp/sql/select%20from%20Artwork%20order%20by%20%40rid%20desc 
```

while binary query (PhpOrient) is super fast and no breakage ...

**Comment by lvca** [comment]
I guess it goes out of memory by formatting the returning JSON.

**Comment by lvca** [comment]
We should provide creation of resulting json in streaming mode.

**Comment by mmacfadden** [comment]
I think this is somewhat related to #6474 and #6598.  In all these cases we are getting an internal server error and a socket exception, with no real stack trace.

**Comment by mmacfadden** [comment]
I actually did a lot of debugging and the issue I am having is specifically related to the HTTP streaming stuff that was recently added.  I am going to open a separate issue.

**Comment by tglman** [comment]
hi @mmacfadden,

Thank you for digging deeply on it,anyway  you can disable the http streaming setting `network.http.streaming` to false.

we are as well checking that implementation hoping to find any related issue soon, any help is welcome.

Bye

**Comment by tglman** [comment]
Hi @mmacfadden,

Do you still have problem with 2.2.10 ?

**Comment by mmacfadden** [comment]
@tglman Since we have a workaround in place I am not sure.  I will upgrade to 2.1.10 and enable streaming and see if the problem is still there.

**Comment by G4br13l3** [comment]
Hi @mmacfadden, do you have any update? Can we close the issue?

**Comment by mmacfadden** [comment]
I will also test this with 2.2.14

**Comment by lvca** [comment]
I'm closing this issue because no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.

**Comment by mmacfadden** [comment]
@lvca I believe this has been fixed.  Sorry I thought I had responded!

**Comment by lvca** [comment]
NP ;-)
