### ISSUE TITLE
`@type` and `@class` should be optional when inserting embedded documents via SQL

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#3398]
Assuming I have a database structure like this:
```sql
CREATE CLASS Person;
CREATE CLASS Address;
CREATE PROPERTY Person.addresses EMBEDDEDSET Address;
```

When I execute the following query, I'd expect it to create a Person with a single Address:
```sql
INSERT INTO Person SET name = "foo", addresses = [{"line1":"123 Fake Street"}]
```
unfortunately this doesn't work, it seems that both `@type` and `@class` are required:
```sql
INSERT INTO Person SET name = "foo", addresses = [{"@type": "d", "@class": "Address", "line1":"123 Fake Street"}]
```
This is quite unintuitive and seems unnecessary, especially so because I don't think it's possible to insert anything which has an `@type` other than "d". 

I think it should look like this:

1. `@type` should not be required, it should default to "document"
2. if not specified, `@class` should default to the type for the field, so in this example it would be "Address"

**Comment by lvca** [comment]
:+1:

**Comment by lvca** [comment]
Added also 4 new test cases.

**Comment by phpnode** [comment]
awesome, thanks @lvca

**Comment by lvca** [comment]
That was super easy ;-)

**Comment by vitorenesduarte** [comment]
Nice! :+1:

**Comment by vitorenesduarte** [comment]
If the property is declared as EMBEDDEDMAP the problem is the same. 
Was this done too?

**Comment by lvca** [comment]
@vitorenesduarte EMBEDDEDMAP was missing, reopening it.

**Comment by phpnode** [comment]
@lvca also the plain `EMBEDDED` type? (maybe you've already done that, I've not tried it yet)

**Comment by lvca** [comment]
@phpnode You're right, it wasn't supported. Adding also EMBEDDED...

**Comment by phpnode** [comment]
and of course `EMBEDDEDLIST` for completeness :)

**Comment by lvca** [comment]
Fixed. EMBEDDEDLIST was already there.

**Comment by daniellawry** [comment]
Would the @class be needed in some cases? Here's an example:

take an EMBEDDEDLIST of class X. You should still be able to insert objects of class Y into the list as long as they extend class X, correct?  If so, would the @class parameter actually be needed to distinguish what's being inserted?

(side note, totally agree that @type shouldn't be needed)

If I'm off track on this one, let me know!

**Comment by vitorenesduarte** [comment]
Then it could be optional.

**Comment by phpnode** [comment]
@lvca it still seems to require `@type` when inserting into an embedded field, i've not checked the other property types yet.

**Comment by lvca** [comment]
@phpnode Just tested and works with 2.0.2-hotfix:

```
CREATE CLASS Person;
CREATE CLASS Address;
CREATE PROPERTY Person.addresses EMBEDDED Address;
INSERT INTO Person SET name = "foo", addresses = {"line1":"123 Fake Street"}
```
Result:
#12:0	1	Person	foo	{"@type":"d","@version":0,"@class":"Address","line1":"123 Fake Street"}

**Comment by phpnode** [comment]
@lvca did you also fix this for `LINK`/`LINKSET`/`LINKMAP`/`LINKLIST` fields?

**Comment by lvca** [comment]
@phpnode yes, I did.

**Comment by phpnode** [comment]
@lvca @matuszeman reported this failing on latest 2.0.3 (I can replicate):
```sql
create class Poll extends V
create class PollOption
create property Poll.createdAt string
create property PollOption.text string
create vertex Poll set createdAt = "2015-02-20T19:52:22.651Z", options = [{"@class": "PollOption", "text": "Yep"}, {"@class": "PollOption",  "text": "Nope"}]
```

Changing the last line to include `@type` works:
```sql
CREATE VERTEX Poll SET createdAt = "2015-02-20T19:52:22.651Z", options = [{"@class": "PollOption", "@type": "d", "text": "Yep"}, {"@class": "PollOption", "@type": "d",  "text": "Nope"}]
```
