### ISSUE TITLE
using parent "out" data in query

### ISSUE THREAD

**Issue by ghominejad** [orientechnologies/orientdb#3401]
In my scenario users can follow them and each user can publish posts. I can select posts of followed users  by this  query.
```SQL
select expand(out(follow).out(publish)) from users where username = 'testuser'
```
but i need an efficient query that includes some information about the user itself same as sql inner join in addition to post class fields.
```SQL
select *, in(publish)[0].username from (select expand(out(follow).out(publish)) from users where username = 'testuser')
```
Is there any performance issues in this query?

**Comment by vitorenesduarte** [comment]
In the first query, (let's says textuser's RecordID is #12:0) it would be way faster (especially when you have lots of users) to do this:
```sql
select expand(out('follow').out('publish')) from #12:0
```

But I'm guessing you want info about the second.

**Comment by vitorenesduarte** [comment]
@lvca is it weird that 
```sql
select expand(out(Follows).out(Posts)) from #12:0
select expand(out('Follows').out('Posts')) from #12:0
```
these two give me different results?

**Comment by ghominejad** [comment]
I have lots of users (10 millions) and i also need the `username` in the result.
Assume that i have an array of users that i can't use their `username` statically in query. i am looking a query that selects the username from `Follows` relation.

Thanks for response.

**Comment by vitorenesduarte** [comment]
If you're worried about performance I really think you should use the recordId instead of the username.

I didn't understand the array part, but:

username of the followed:
```sql
select username 
from (
    select expand(out('Follows')) 
    from 11:0
)
```

username of the followed who have posts:
```sql
select username
from (
    select expand(out('Follows')) 
    from 11:0
)
where out('Posts').size() > 0
```

**Comment by ghominejad** [comment]
Thank you very much
