### ISSUE TITLE
Studio visual editor: DATETIME using second precision

### ISSUE THREAD

**Issue by DeividasJackus** [orientechnologies/orientdb#3403]
When editing records with DATETIME properties using the Studio plugin, you are allowed to change the date, hour and minute, but not the seconds?

**Comment by maggiolo00** [comment]
@sinfex 
we uses this component that  does not allow that
http://mgcrea.github.io/angular-strap/#/timepickers#timepickers

**Comment by maggiolo00** [comment]
I can try to hack the component and extend it to support seconds
