### ISSUE TITLE
Studio: deleting edges

### ISSUE THREAD

**Issue by sinfex** [orientechnologies/orientdb#3404]
Performing a "SELECT FROM E" and clicking on one of the listed RIDs allows to edit an edge's properties and, just like when editing a vertex, the editor's "Actions" menu contains the items "New" and "Delete", both of which are not working.

Clicking on "New", when editing an edge, could result in a popup dialog requesting input of incoming and outgoing vertices, instead it seems to just create a temporary, disconnected edge.

Clicking on "Delete" should issue a *DELETE EDGE* on the target edge; instead it seems to issue a *DELETE VERTEX*, which, of course, fails.

**Comment by maggiolo00** [comment]
Hi @sinfex 

Delete Edge has been fixed
For new the temporary Edge/Vertex is normal, 
you can fill it with your property and save. 
But you have to add property of in/out manually

**Comment by maggiolo00** [comment]
You could open a an issue here for improved edge creation 
here
https://github.com/orientechnologies/orientdb-studio/issues
