### ISSUE TITLE
Different behaviors when inserting into class/cluster 

### ISSUE THREAD

**Issue by mamobyz** [orientechnologies/orientdb#3406]
When working with a class bound with multiple clusters, I can observe different behaviors regarding schema conformity:

1. For integer properties, it is possible to use quoted string to set the property values when inserting the records directly to the class, whereas quoted string for integer properties is refused when inserting into a cluster.
-> This suggests, that the database validates the input more restrict in case of inserting into clusters.
2. For mandatory properties, it is possible to skip them when inserting into a cluster, whereas the same will be refused by the database when inserting into the class.
-> This implies, that the database does not perform validation in case of clusters.

The following SQL statements should illustrate the issues:
[code starts here]
create database remote:localhost/Issues root root memory
create cluster demo1
create cluster demo2
create cluster demo3

create class Demo extends V cluster 11,12,13
create property Demo.id integer
alter property Demo.id mandatory true
create property Demo.subject string

insert into demo set id='1', subject='into class directly with id as string'
insert into demo set id=2, subject='into class directly with id as int'

(The following one will be rejected, which is still ok, but not quite in accordance with the first one above)
insert into cluster:demo1 set id='3', subject='into cluster instead with id as string'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster ...
Error: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number

insert into cluster:demo1 set id=3, subject='into cluster instead with id as int'

(How comes that the next one succeeds?)
insert into cluster:demo1 set subject='into cluster instead with id as int'
[code ends here]

**Comment by tglman** [comment]
hi @mamobyz,

you should use this syntax:
``` insert into demo cluster demo1 set id='3', subject='into cluster instead with id as string' ```

otherwise you are not specifying  the class of the document so validation is not triggered correctly.

for more datail look to:
http://orientdb.com/docs/last/orientdb.wiki/SQL-Insert.html#insert-a-new-record-of-type-profile-but-in-a-different-cluster-than-the-default-one

**Comment by mamobyz** [comment]
Hi @tglman,
Thanks for the hint. I don't know whether I overlooked that section on that page, or it is recently added. 

But anyways, I think, you should revise the syntax documents and use a proper syntax notation. What is the notation currently used, as I see, it is neither EBNF nor RegEx, but something mixed. Can you point me the notation describing document which I can consult?

As the **insert** syntax (http://orientdb.com/docs/last/orientdb.wiki/SQL-Insert.html#syntax) suggests, to add a record to a specific cluster, I should use ```insert into cluster:XYZ set ...```. And the alternative with ```[class:]<class>``` does not suggest the variant you provide above.
