### ISSUE TITLE
OrientVertex record constructor public, but OrientEdge is protected? (java)

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3410]
We have some use-cases where we need to create vertex/edge from raw objects (e.g. ODocument).   OrientVertex(graph, OIdentifiable) lets us do this (public), but OrientEdge(graph, OIdentifiable) doesn't (protected).  

I think the OrientEdge constructor should be public.

**Comment by lvca** [comment]
You can use:

    g.getEdge( ODocument );
