### ISSUE TITLE
Name of the database when exception is logged

### ISSUE THREAD

**Issue by ginojohn** [orientechnologies/orientdb#3411]
We have multiple database hosted on the server and when there is an exception, the log message don’t have name of the database that generated the exception. Can we add the database name as part of the exception logging

**Comment by lvca** [comment]
:+1:

**Comment by fabriziofortino** [comment]
I think is related to #2468

**Comment by lvca** [comment]
@fabriziofortino yes, I remember this old issue. It's pretty the same.

**Comment by ginojohn** [comment]
The #2468 is the same. It is very critical to manage multiple database in the same server
