### ISSUE TITLE
OrientDB Core and Server relationship

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3413]
Guys,

As I know, orientdb server is working above orientdb core. And core doesn't even know about presence of a server.

And there is a question: why if server can be started separatly from core, it (server) sending to shutdown core when server it's being shuteddown? 
In other words: it would be quite natural if server can be run and down separatly from core: even several times on the same runnning core instance.

Do you see any problems in removing of Orient.instance().shutdown() from code of OServer.shutdown() method?

**Comment by laa** [comment]
Seems reasonable, I propose to introduce flag during server start-up which will indicate whether server should automatically shutdown core.

**Comment by lvca** [comment]
:+1:
