### ISSUE TITLE
GremlinGroovyScriptEngineFactory defined as service in orientdb-graphdb-{version}.jar

### ISSUE THREAD

**Issue by rmuller** [orientechnologies/orientdb#3414]
The orientdb-graphdb-{version}.jar artifact contains a service definition (in META-INF/services) for
com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngineFactory. It should not be there. It is already present in the optional artifact `com.tinkerpop.gremlin:gremlin-groovy` (correct). It is confusing ,generating an warning (ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngineFactory not found) and also not i line with the Java Service Provider framework.

**Comment by lvca** [comment]
@rmuller Please could you send us a PR to `develop` branch?

**Comment by rmuller** [comment]
At your service: https://github.com/orientechnologies/orientdb/pull/3419

**Comment by lvca** [comment]
Merged
