### ISSUE TITLE
Can't get RID after commit in 2.0-rc2

### ISSUE THREAD

**Issue by azzazeli** [orientechnologies/orientdb#3426]
I've tried to use orientdb 2.0.rc-2 and found an issue with RID. After graph commit  RID contains negative values. My code worked fine with version 1.7.10.
Note that this happens when I use remote connection.
Code sample:
```java
TransactionalGraph graph = getGraph();
v = graph.addVertex(null);
v.setProperty("test1", "value");
graph.commit();
System.out.println(v.v.getId());
```

Thanks,
Alex.

**Comment by lvca** [comment]
Did you created that piece of code ad-hoc for the issue? It contains errors.

**Comment by lvca** [comment]
The classic mistake is that you call .begin() twice, so your commit() is nested and real tx is never committed.

**Comment by azzazeli** [comment]
Here is my test:
```java
    @Test
    public void tt(){
        TransactionalGraph graph = TmGraph.INSTANCE.getGraph();
        try {
            Vertex v  =  graph.addVertex(null);
            v.setProperty("test", "value");
            graph.commit();
            System.out.println(v.getId());
        } finally {
            graph.shutdown();
        }
    }
```
And the output is:
#-1:-2

What do you mean by call begin()? Graph does not have begin method

**Comment by lvca** [comment]
Ok, I'm trying this test...

**Comment by lvca** [comment]
Ok, it works:

  @Test
  public void testPersistentRID() {
    TransactionalGraph g = new OrientGraph("memory:testPersistentRID");
    try {
      Vertex v = g.addVertex(null);
      v.setProperty("test", "value");
      g.commit();
      System.out.println(v.getId());
      Assert.assertTrue(((ORID) v.getId()).isPersistent());
    } finally {
      g.shutdown();
    }
  }

**Comment by azzazeli** [comment]
Please try using remote. With memory it works fine

**Comment by lvca** [comment]
Same result also with remote: works. The problem should be in your `TmGraph.INSTANCE.getGraph()`: you're reusing a graph where the tx status is not "clean". Please could you try with a fresh new OrientGraph instance?

**Comment by azzazeli** [comment]
ok.
I've changed the code:
Here is it:
```java
    @Test
    public void tt(){
        BaseConfiguration config = new BaseConfiguration();
        config.setProperty("blueprints.orientdb.password", "manager");
        config.setProperty("blueprints.orientdb.username", "user");
        config.setProperty("blueprints.orientdb.url", "remote:localhost/testdb");
        config.setProperty("blueprints.graph", "com.tinkerpop.blueprints.impls.orient.OrientGraph");

        TransactionalGraph graph =(TransactionalGraph) GraphFactory.open(config);
        try {
            Vertex v  =  graph.addVertex(null);
            v.setProperty("test", "value");
            graph.commit();
            System.out.println(v.getId());
        } finally {
            graph.shutdown();
        }
    }
```

The output: 
#-1:-2

**Comment by lvca** [comment]
Please could you try the same with 2.0-SNAPSHOT?

**Comment by azzazeli** [comment]
Should I reconfigure my maven project to use snapshot jars?

**Comment by lvca** [comment]
yes, just point to 2.0-SNAPSHOT.

**Comment by azzazeli** [comment]
The same thing with 2.0-SNAPSHOT

**Comment by lvca** [comment]
I'm trying this:
```java

**Comment by azzazeli** [comment]
I'm using this url for shapshots:
https://oss.sonatype.org/content/repositories/snapshots
Is is correct?

**Comment by lvca** [comment]
This is last one:

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.0-SNAPSHOT/orientdb-community-2.0-20150119.132456-566-distribution.tar.gz

**Comment by azzazeli** [comment]
I use this one : orientdb-graphdb-2.0-20150119.132211-649.jar
The issue persists.:(

**Comment by azzazeli** [comment]
One more thing. After running this code I cannot see new inserted record in the database. I've open orient console and run a simple sql query: I cant see my new inserted record here.

**Comment by laa** [comment]
I have proposal, could you create separate maven project, so we will download it and run the test ? In such case we will be on the same page.

P.S. I am sure you have active running tx which was not committed.

**Comment by azzazeli** [comment]
I've created the sample
https://www.dropbox.com/s/6izf8m1tcobeut4/orient-rid.zip?dl=0

**Comment by azzazeli** [comment]
My server runs in distributed mode

**Comment by lvca** [comment]
Distributed? This was an important information to share.

**Comment by azzazeli** [comment]
Yes. distributed. In "normal" mode all works fine

**Comment by azzazeli** [comment]
Are you going to release 2.0 with this issue?

**Comment by lvca** [comment]
I'm working on it, almost finished...
