### ISSUE TITLE
2.0-rc1 Fetchplan with partial wildcard ignores depth-level

### ISSUE THREAD

**Issue by mirobimbo** [orientechnologies/orientdb#3428]
Let's create small graph:

    create class Person extends V
    create class Follow extends E

    create vertex Person set name = 'A'
    create vertex Person set name = 'B'
    create vertex Person set name = 'C'
    
    create edge Follow from (select from Person where name = 'A') to (select from Person where name = 'B')
    create edge Follow from (select from Person where name = 'B') to (select from Person where name = 'C')

If there is only wildcard `*` or link name `out_Follow` fetchplan works as expected and stops on N-th recursion round:
    
    select @this.toJSON('fetchPlan:*:2') from (select from Person where name='A')
    {
        "name": "A",
        "out_Follow": [{
                "out": "#11:0",
                "in": {
                    "name": "B",
                    "in_Follow": ["#12:0"],
                    "out_Follow": ["#12:1"]
                }
            }]
    }

But if there is partial wildcard `out_*`, it will fetch recursively all records
    
    select @this.toJSON('fetchPlan:out_*:2') from (select from Person where name='A')
    {
        "name": "A",
        "out_Follow": [{
                "out": "#11:0",
                "in": {
                    "name": "B",
                    "in_Follow": ["#12:0"],
                    "out_Follow": [{
                            "out": "#11:1",
                            "in": {
                                "name": "C",
                                "in_Follow": ["#12:1"]
                            }
                        }]
                }
            }]
    }

**Comment by lvca** [comment]
Please, could you try it with 2.0 final?

**Comment by mirobimbo** [comment]
Sorry, I haven't seen that Final release is out :) But yes, the same behavior is on 2.0 Final.

**Comment by lvca** [comment]
This is related to this issue: https://github.com/orientechnologies/orientdb/issues/2101
