### ISSUE TITLE
Behaviour of `expand()` on links is inconsistent in REST vs Binary protocols

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#3432]
_setup_:

``` sql
create class TestClass extends V;
create property TestClass.name STRING;
create property TestClass.user LINK OUser;
create vertex TestClass set name = "hello world", user = #5:0;
```

via REST and console:

``` sql
select expand(user) from TestClass
```

returns the user directly, but on the binary protocol it only returns the user's RID. 

Via the binary protocol I must use a fetchplan:

``` sql
select expand(user) from TestClass fetchplan user:1
```

It would be nice to get these inconsistencies cleaned up, yielding different results for the same query is causing a lot of headaches for oriento users.

**Comment by MarcelPitch** [comment]
Hi @phpnode,

Just a question : 

You use `fetchplan ` to retrieve all the user data. But I see that you use `link` to connect `TestClass`to `oUser`.

In my db, I'm using *edges*. Your `fetchplan` workaround doesn't have any effect in this case. Do you have a workaround for this ?

**Comment by MarcelPitch** [comment]
Hi,

Allow me to remind this post.

I do not know how I could execute queries like above.

Thanks

**Comment by Ndrou** [comment]
Hi guys !

Any news about solving this problem?

Thanks

**Comment by lvca** [comment]
Guys,
The REST protocol returns JSON and the fetch plan is managed to format the JSON properly by nesting objects rather than RID. With binary protocol, we never modify the returning object. The fetchplan is used only to do a early load of connected records, so as soon as the client fetch them, they are already there.

**Comment by MarcelPitch** [comment]
Hi Luca,

OK ! 

So if I understand, I've to precise the FECTHPLAN with Binary in order to do early load of connected records, right ?

But I just tried it like this :
```SQL
SELECT 
	name, 
	$DescendingPosts AS Posts
FROM 
	#12:0 
LET 
	$DescendingPosts = (
							SELECT 
      							@rid,
      							message, 
      							creation_date 
      						FROM 
      						(
								SELECT 
									expand(out('WROTES'))
                              	FROM 
									$parent.$current
                            ) 
							ORDER BY 
								creation_date DESC
    					)
FETCHPLAN
	Posts:1
```

or like this :
```SQL
SELECT 
	name, 
	$DescendingPosts AS Posts
FROM 
	#12:0 
LET 
	$DescendingPosts = (
      						SELECT 
      							@rid,
      							message, 
      							creation_date 
      						FROM 
      						(
                              	SELECT 
                              		expand(out('WROTES'))
                              	FROM 
                              		$parent.$current
                              	FETCHPLAN
									Posts:1
                            ) 
      						ORDER BY 
      							creation_date DESC
    					)

```

But the result is the same.

I send you a tiny server function in order to recreate the test :

```js
var g = orient.getGraphNoTx();

g.command('SQL', 'CREATE CLASS User extends V', []);
g.command('SQL', 'CREATE PROPERTY User.name STRING', []);

g.command('SQL', 'CREATE CLASS Post extends V', []);
g.command('SQL', 'CREATE PROPERTY Post.message STRING', []);
g.command('SQL', 'CREATE PROPERTY Post.creation_date DATETIME', []);

g.command('SQL', 'CREATE CLASS WROTES extends E', []);


g.command('SQL', "CREATE VERTEX User SET name='Monica Bellucci'", []);

g.command('SQL', "CREATE VERTEX Post SET message='My 1st post', creation_date=sysdate()", []);
g.command('SQL', "CREATE VERTEX Post SET message='My 2nd post', creation_date=sysdate()", []);

g.command('SQL', "CREATE EDGE WROTES FROM (SELECT FROM User) TO (SELECT FROM Post)", []);
```

Please, could you help me on this ? It would be a huge help !!!

Thanks !

*I close the other Issue #3499*

**Comment by martingg88** [comment]
any update about this issue?
