### ISSUE TITLE
Suggestion about Embedded Objects

### ISSUE THREAD

**Issue by Ajrarn** [orientechnologies/orientdb#3437]
I really enjoy the possibility to describe a class with embedded *somethings* (class, map, set, list).
I tried to use abstract classes in embedded fields and it doesn't work because we can't instantiate abstract class.

I totally agree with this. It have sense in java.

But I think that in the case where a class will never be used outside an embedded *something*, it will be useful to describe this class as this and prevent bad use of this class. Perhaps a property like Abstract name Embedded Only or something else.

**Comment by lvca** [comment]
@Ajrarn you opened 3 issues! Look to #3435 and #3436. Please pay attention on it.

**Comment by Ajrarn** [comment]
I'm sorry for that. I have to be more careful with my keyboard.

**Comment by vitorenesduarte** [comment]
Hi @Ajrarn. I think you already can. 
Try this:

```sql
create class AbstractDocument ABSTRACT
create class ConcreteVertex extends V
create property ConcreteVertex.prop EMBEDDEDLIST AbstractDocument
insert into ConcreteVertex set prop = [{"@class":"AbstractDocument", "values":["A", "B", "C"]}]
```

**Comment by Ajrarn** [comment]
Yes you are right !
I tried this with different versions but not the 2.0 Final.
And it works !

Do you want me to close this issue ?
