### ISSUE TITLE
OCommandExecutionException during import

### ISSUE THREAD

**Issue by biliards** [orientechnologies/orientdb#3438]
I'm following the training and with orientdb-community-2.0-rc2 on a small server, I tested the export and import commands: see the details into zip file http://download.bilardi.net/download/public/orientdb/import.error.zip.
The principal error log is:

Error on database import happened just before line 0, column 1
com.orientechnologies.orient.core.exception.OCommandExecutionException: 'DROP CLASS' command cannot drop class 'Person' because contains Vertices. Use 'DELETE VERTEX' command first to avoid broken edges in database, or apply the 'UNSAFE' keyword to force it                                               

At your service.

**Comment by lvca** [comment]
We fixed it in 2.0 final.
