### ISSUE TITLE
Strange confusing OrientDB TIPS

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3441]
Guys,

I have following SQL

``` SQL
select from Registration SKIP 0 LIMIT 20 ORDER BY phone_num
```

and in logs I see following tip:

```
INFO  {db=orienteer} [TIP] Query 'select from Registration SKIP 0 LIMIT 20 ORDER BY phone_num' returned a result set with more
than 10000 records. Reduce it to improve performance and reduce RAM used [OProfiler]
```

So, I have 4 questions:
1) As you can see query should return just 20 or less. Why did this message apear?
2) I understand that for ordering OrientDB should go through all records. But: 10000 is not a very-very big amount for data stored in a table. Is it realy recommended to have in a table less than 10000 records?:)
3) My next project will require more than 10^10 records in a table. Question: if ordering will be required - what the maximum records might be ok to sort on a) not indexed property b) indexed property. I understand - it might depends on hardware, but I need highlevel estimations...
4) Can OrientDB parallel ordering queries amond several nodes in distrubuted mode?

**Comment by mathieubodin** [comment]
I think the 'order by phone_num' clause is the reason ODB works on more than 20 Registrations.

Do you have index on phone_num ?

Could it be used for order_by ?

:+1:  on 2) and 3)

**Comment by lvca** [comment]
2) 10k is the result set. Returning >10k records has a cost and often hides a bad query
3) it's not a problem of cluster size, it's about the query. If you do a full scan of a cluster with millions of records, it's obvious that will be super slow. Just uses indexes or refactor your db
4) not yet
