### ISSUE TITLE
Lightweight Edge LinkBag Index Does Not Enforce Unique Constraint (OrientDB 2.0 Final)

### ISSUE THREAD

**Issue by SDIPro** [orientechnologies/orientdb#3442]
If an index with a unique constraint is created against an outgoing lightweight edge property on a vertex and if the same vector is added as a lightweight edge, an ORecordDuplicatedException should be thrown.  However, multiple links to the same vector will be added to the LinkBag, and the index will contain only a single copy of each vector RID.

Original post:
https://groups.google.com/forum/#!topic/orient-database/YzSFP1EZYrE

**Comment by laa** [comment]
Sorry, but I added test and it passes. You can find test in issue log. If you still think that there is a bug, please modify test to reproduce it and reopen issue.

**Comment by SDIPro** [comment]
The test case passes and throws an ORecordDuplicatedException if you add vertexInTwo to vertexOutTwo.  However, if you add vertexInOne to vertexOutOne a second time, no exception is raised.

Here's what I mean:
vertexOutOne.addEdge("link", vertexInOne);
vertexOutOne.addEdge("link", vertexInTwo);
vertexOutOne.addEdge("link", vertexInOne);  <----- this never throws an ORecordDuplicatedException 

Also, when I run the test case that you created that does throw an exception against a plocal database, after I get the ORecordDuplicatedException, if I check the state of the database, vertexOutOne will be present but its out_link property will be null (or sometimes empty) while vertexInOne will still point to vertexOutOne, and vertexInTwo will still point to both vertexOutOne and vertextOutTwo.  So, that's a problem if vertexOutOne is being created yet its out links to vertexInOne and vertexInTwo are lost.

This morning I tested this using real Edges and with the DB set to useLightweightEdges=false.  The problem occurs with real Edges as well.

**Comment by SDIPro** [comment]
I added a code sample to https://github.com/orientechnologies/orientdb/issues/3456.

As far as the inconsistent state of vertices after an ORecordDuplicatedException is thrown, it only happens when running on distributed servers.  Running in a single server environment, the transaction rolls back all the changes properly.

-Colin
