### ISSUE TITLE
selecting content from an EMBEDDEDLIST of abstract document types fails

### ISSUE THREAD

**Issue by daniellawry** [orientechnologies/orientdb#3452]
Version: OrientDB 2.0 (using Studio)

Steps to Reproduce: 
(1) create an abstract document class called "AbstractDocument"
(2) create a concrete document class that extends the abstract document class called "ConcreteDocument"
(3) create a concrete vertex class (extends V) called "ConcreteVertex"
(4) add a single EMBEDDEDLIST property called "Properties" to "ConcreteVertex" with the list class type set to "AbstractDocument"
(4) insert a new instance of "ConcreteVertex" with the "Properties" EMBEDDEDLIST property containing a single "ConcreteDocument" instance
(5) try to select the EMBEDDEDLIST content from the inserted document using the query:

select properties from [insert @rid here]

Expected Result: I'd expect to see the content of the "Properties" property as a JSON object

Actual Result: The query executes with no exceptions but no results are returned

My Exact Example:

Here's a sample "Concept" object I created with an @rid of #14:0
(Concept is a concrete class that extends V)

{
	"@type" : "d",
	"@version" : 0,
	"@class" : "Vocabulary",
	"vocabularyEntries" : [{
			"@type" : "d",
			"@version" : 0,
			"@class" : "VocabularyEntry",
			"default" : true,
			"label" : "English Label",
			"description" : "English Description",
			"locale" : {
				"@type" : "d",
				"@version" : 0,
				"@class" : "Locale",
				"language" : "en",
				"country" : "US"
			}
		}, {
			"@type" : "d",
			"@version" : 0,
			"@class" : "VocabularyEntry",
			"default" : false,
			"label" : "French Label",
			"description" : "French Description",
			"locale" : {
				"@type" : "d",
				"@version" : 0,
				"@class" : "Locale",
				"language" : "fr",
				"country" : "CA"
			}
		}
	],
	"properties" : [{
			"@type" : "d",
			"@version" : 0,
			"@class" : "IntegerProperty",
			"values" : [1, 2, 3]
		}, {
			"@type" : "d",
			"@version" : 0,
			"@class" : "StringProperty",
			"values" : ["A", "B", "C"]
		}
	]
}

"properties" is an EMBEDDEDLIST of "Property"
"Property" is an abstract document type
"IntegerProperty" and "StringProperty" are concrete document types that extend Property

I'm trying to write a query that will return the "properties" portion of this object but nothing seems to work

Note: I'm using OrientDB 2.0 and using the studio for my queries

Query 1: select properties from #14:2
this executes without error but returns nothing

Query 2: select expand(properties) from #14:2
this also executes without error and returns nothing

I do have another EMBEDDEDLIST in use with the vocabulary.vocabularyEntries object
When I run the query: select vocabulary.vocabularyEntries from #14:2
I do see the following results:

[
	{
		"@type" : "d",
		"@version" : 0,
		"@class" : "VocabularyEntry",
		"default" : true,
		"label" : "English Label",
		"description" : "English Description",
		"locale" : {
			"@type" : "d",
			"@version" : 0,
			"@class" : "Locale",
			"language" : "en",
			"country" : "US"
		}
	}, {
		"@type" : "d",
		"@version" : 0,
		"@class" : "VocabularyEntry",
		"default" : false,
		"label" : "French Label",
		"description" : "French Description",
		"locale" : {
			"@type" : "d",
			"@version" : 0,
			"@class" : "Locale",
			"language" : "fr",
			"country" : "CA"
		}
	}
]

Is my issue that the "properties" field is an EMBEDDEDLIST of an abstract document type (even though what it contains are concrete document types)?  If so, is the only workaround to use a concrete document type instead of an abstract one?

**Comment by vitorenesduarte** [comment]
Hi @daniellawry,

```sql
create class AbstractDocument ABSTRACT
create class ConcreteDocument extends AbstractDocument
create class ConcreteVertex extends V
create property ConcreteVertex.prop EMBEDDEDLIST AbstractDocument
insert into ConcreteVertex set prop = [{"@class":"ConcreteDocument", "values":["A", "B", "C"]}] # returns 13:0
select prop from 13:0
```

Are these the steps to reproduce your problem?
It's not easy to understand. If yes, don't see any.

**Comment by daniellawry** [comment]
Hi Vitor,

Yes, those are steps to reproduce the problem.

1. Create some property in a vertex class that is of type "EMBEDDEDLIST" of some Abstract Document Class.

2. Insert a new vertex with this property populated with values from a concrete class that extends the Abstract Document Class

3. Query to retrieve the Vertex and things look ok

4. Query to retrieve the property of the Vertex and I get nothing

**Comment by vitorenesduarte** [comment]
If you run my steps you have the same problem?
Without a sequence of steps like mine that show your problem, I don't know if someone can help you.

**Comment by daniellawry** [comment]
Hi Vitor,

I followed your steps and things work for me now.  I must have had something wrong with my setup.  If I figure it our, I'll let you know, but you can consider this issue closed since your steps work.  Thanks again!

**Comment by lvca** [comment]
Cool, I set it as INVALID/WON'T fix.
