### ISSUE TITLE
Unable to connect with user of a class extending OUser

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#3453]
On current `develop` branch, via console
```
create database remote:localhost/test root root memory
create class exuser extends ouser
insert into exuser (name, password, status, roles) values ('user', 'pass', 'ACTIVE', (select from orole where name = 'admin'))
disconnect
connect remote:localhost/test user pass
```
Instead of establishing a connection I get
```
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'test'
```

**Comment by red-0ne** [comment]
Current develp branch is used.

**Comment by red-0ne** [comment]
Found that the issue is `password` not being hashed automatically on extended classes. After inserting into `exuser` the password is stored in clear. But after manually updating the password with
```
var hashed_password = crypto.createHash('sha256').update(user.password).digest('hex');
user.password = '{SHA-256}'+hashed_password.toUpperCase() //hash must be upper case
//execute query...
```
I can finally connect.
I think some trigger in OUser does not get executed on extended classes.

PS: The password hash has to be in uppercase, which I think is incorrect as `1F` has to be equal to `1f`
PPS: Do you have plans to provide possibility to salt password hashes?

**Comment by lvca** [comment]
About SALT: https://github.com/orientechnologies/orientdb/issues/2242

**Comment by tglman** [comment]
it may be there some security reason why this is not allowed, an example is that the any user could insert a new user skipping the stardand user/profile management built in.

the actual fix is not to complex but may open to security holes
@lvca  what do you think ?

**Comment by red-0ne** [comment]
Is "extending" OUser insufficient to trigger user/profile management on extended classes? I actually can connect if I manually hash the password.

**Comment by lvca** [comment]
While SALT has been (finally) implemented, I'm looking at this old issue. I think extending from OUSer could be dangerous, so I'd say to ban this possibility in OrientDB 2.2. WDYT?

**Comment by red-0ne** [comment]
Prevent extending OUser could be a serious brake to make OrientDB act as an application level authentication/authorization system through the use of OUser as base class to something like Admin, Moderator, Member and AnonymousUser classes. Roles, record level security and other aspects of OrientDB encourage this kind of design

But of course, if it introduces such security concerns it should be banned.

**Comment by lvca** [comment]
I always liked the ability to customize OrientDB for the more different use cases, so let's sit down for a while to understand all the possible security flaws. We could introduce a new restriction on extending classes: the user that do the command should have write authorization against the extending class. So in this example, if you'd do `create class Member extends OUser` as "writer" it should give you an error, because writer has no write rights on OUser. In this way users can't create own extensions, but it must be "admin" or somebody with such privileges. WDYT?

**Comment by lvca** [comment]
Furthermore, we could add this rule: the extended class inherit rules form the super classes if not expressly defined. In your example, Member would inherit OUser restrictions, but if you set restrictions against Member class, then they would win against the OUser.

**Comment by red-0ne** [comment]
Yes the extended class should have at most the same privileges as the super class.

About the rights to extends a class, I think looking up the right to create an instance of a class should suffice to allow its extension (If a user can insert into `Member` then he should also be able to extend it)

**Comment by lvca** [comment]
Ok, fixed.

**Comment by lvca** [comment]
The OUserTrigger now is polymorphic, so it will encode passwords of any sub-classes. To extend OUser the user must have the privilege of UPDATE against OUser.

**Comment by red-0ne** [comment]
Awesome! Thank you @lvca
