### ISSUE TITLE
Lightweight Outgoing Edge Index Does Not Enforce Unique Constraint (OrientDB 2.0 Final)

### ISSUE THREAD

**Issue by SDIPro** [orientechnologies/orientdb#3456]
This is a follow-up to my original issue report:
https://github.com/orientechnologies/orientdb/issues/3442

The test case passes and throws an ORecordDuplicatedException if you add vertexInTwo to vertexOutTwo. However, if you add vertexInOne to vertexOutOne a second time, no exception is raised.

Here's what I mean:
vertexOutOne.addEdge("link", vertexInOne);
vertexOutOne.addEdge("link", vertexInTwo);
vertexOutOne.addEdge("link", vertexInOne); <----- this never throws an ORecordDuplicatedException

Also, if you run the test case that throws the ORecordDuplicatedException against a plocal db, if you check the state of the database, vertexOutOne will be present but its out_link property will be null (or sometimes empty) while vertexInOne will still point to vertexOutOne, and vertexInTwo will still point to both vertexOutOne and vertextOutTwo. So, that's a problem if vertexOutOne is being created yet its out links to vertexInOne and vertexInTwo are lost.  I would expect none of the vertices to be created if an exception is thrown during commit.

This morning I tested this using real Edges and with the DB set to useLightweightEdges=false. The leftover, unlinked vertices problem occurs with real Edges as well.

**Comment by laa** [comment]
Could you provide real test case not text description or could you highlight me changes of test which I pushed with description which you provided. Because I unfortunately can not see deference.

**Comment by SDIPro** [comment]
Here ya go.  This test does not throw an ORecordDuplicatedException.  Look for the <-------- line.  Maybe my assumption is wrong, but I don't know how else to prevent a duplication on an outgoing edge.

private void testOutLinksUniquenessTwo()
	{
		final String url = "memory:" + this.getClass().getSimpleName();

		OrientGraph graph = new OrientGraph(url, "admin", "admin", false);
		graph.drop();

		graph = new OrientGraph(url, "admin", "admin", false);
		graph.setUseLightweightEdges(true);

		graph.createEdgeType("link");

		OClass outVertexType = graph.createVertexType("IndexedOutVertex");
		outVertexType.createProperty("out_link", OType.LINKBAG);
		outVertexType.createIndex("uniqueLinkIndex", "unique", "out_link");
		
		graph.setAutoStartTx(true);
		
		Vertex vertexOutOne = graph.addVertex("class:IndexedOutVertex");
		
		Vertex vertexInOne = graph.addVertex(null);
		Vertex vertexInTwo = graph.addVertex(null);
		
		vertexOutOne.addEdge("link", vertexInOne);
		vertexOutOne.addEdge("link", vertexInTwo);
		vertexOutOne.addEdge("link", vertexInOne);	// <----- Should this be allowed if the indexed value of out_link is supposed to be unique?
		
//		Vertex vertexOutTwo = graph.addVertex("class:IndexedOutVertex");
//		vertexOutTwo.addEdge("link", vertexInTwo);

		try
		{
			graph.commit();
			//in vertex can be linked by only one out vertex.
		}
		catch (ORecordDuplicatedException e)
		{
			System.out.println("OrientTest.testOutLinksUniquenessTwo() Exception: " + e);
		}
		graph.drop();
	}

**Comment by laa** [comment]
It should not throw exception because all edges belongs to single document, so no duplications in database. Duplications are absent because only and only one document contains data not 2 documents. That is contract of unique index.  First 2 tests achieve condition that "in vertex" has links to only "single out vertex" if you want to achieve condition "out vertex" has links to single "in vertex" please use example form test 3. If you want to achieve condition I have single and only single edge between 2 vertexes you have to use "normal" edges.

**Comment by SDIPro** [comment]
Thanks for the detailed explanation.  Sorry for wasting your time on this.  Would it be possible to update the Lightweight Edges page to include this information?

Appreciate it!

-Colin

**Comment by micha-nerdlichter** [comment]
I had the same issue. It is very irritating that a unique_hash_index has no effect on an out_ property when using lighweight edges. Allthough Luca's explanation is pretty clear, it should be added to "Disadvantages" in https://orientdb.com/docs/2.2/Lightweight-Edges.html that there is no way to control duplicate edges when using lightweight edges.
