### ISSUE TITLE
Input data validation

### ISSUE THREAD

**Issue by matuszeman** [orientechnologies/orientdb#3459]
Version: 2.0

I'm constantly running into issue with 'corrupted' data during development - like I accidentally store into "LINK" property a string instead of valid RID. It is stored as "#-1:-1" value.

This ends up with error:
```
SEVERE Error on unmarshalling field 'ouser' of record 'User{displayName:John Zemi}': value '#5:5"' is not a link [ORecordSerializerSchemaAware2CSV]
```
This also causes Studio not being able to fetch data from that class anymore with error: "The command has not been executed"

POST request:
http://localhost:2480/command/test/sql/-/20?format=rid,type,version,class,graph  
select * from User

With response (notice ouser property):
```
{
"result":
[
{"@type":"d","@rid":"#12:3","@version":1,"@class":"User","displayName":"John Zemi","ouser":{null}}
]
}
```

**Proposal**
OrientDB validates input values so that incorrect data won't be stored but exception is raised instead.

**Comment by lvca** [comment]
OrientDB already validates it if you setup the property as LINK in schema.

**Comment by matuszeman** [comment]
That's weird - I'm using https://github.com/codemix/oriento adapter with binary protocol.
I still believe though, even when adapter is doing something wrong, DB should not allow this to happen.

I'll try to discuss my use-case with project maintainers, although it would be nice to get your opinion on this too and direct me right way.

**Comment by phpnode** [comment]
@matuszeman in oriento you must explicitly mark a RID (Link) by wrapping it in an `Oriento.RID` object, otherwise it'd be impossible to differentiate RIDs from strings.

**Comment by matuszeman** [comment]
@phpnode Thanks, but I think I tried that already also - I will try again tonight. But question still remains - why insert like that is not rejected? Is "#-1:-1" considered being valid value for LINK properties? If so, it would be nice if it didn't brake when I query from Studio.
