### ISSUE TITLE
orientdb count slow

### ISSUE THREAD

**Issue by dewj** [orientechnologies/orientdb#3462]
orientdb {db=test}> select count(*) from v where index > 9

----+------
     |count
----+------
0   |399990
----+------

1 item(s) found. Query executed in 19.8 sec(s).
orientdb {db=test}> select count(*) from v where index between 2 and 344444

----+------
     |count
----+------
0   |344443
----+------

1 item(s) found. Query executed in 14.263 sec(s).

it take much time to count by where conditions.

1、https://github.com/orientechnologies/orientdb/issues/1537
2、https://groups.google.com/forum/#!topic/orient-database/2KJuo6DShxI

but noting to me,what can i do?

**Comment by lvca** [comment]
Like with RDBMS, create an index on "index" field:

    create property v.index integer
    create index v.index on V (index) UNIQUE

Change UNIQUE to NOTUNIQUE in case you can have duplicates on "index" field.

**Comment by dewj** [comment]
@lvca 
orientdb {db=test}> create property v.index integer

Property created successfully with id=1

orientdb {db=test}> create index v.index on V (index) UNIQUE


Creating index...
Created index successfully with 400000 entries in 23.650000 sec(s).


Index created successfully

orientdb {db=test}> select count(*) from v where index between 9 and 329873

----+------
     |count
----+------
0   |329865
----+------

1 item(s) found. Query executed in 7.94 sec(s).

it still 7.94 sec(s),while oracle take 0.078 sec(s).
i download orientdb-community-2.0-M2,how can reduce to 1 second?

**Comment by lvca** [comment]
To be sure it's using the index, can you execute:

    explain select count(*) from v where index between 9 and 329873

**Comment by dewj** [comment]
orientdb {db=test}> explain select count(*) from v where index between 9 and 329873

Profiled command '{limit:-1,compositeIndexUsed:1,fullySortedByIndex:false,evalua
ted:329865,documentAnalyzedCompatibleClass:329865,projectionElapsed:47,involvedI
ndexes:[1],groupByElapsed:0,indexIsUsedInOrderBy:false,current:#13:329063,fetchi
ngFromTargetElapsed:10431,documentReads:329865,recordReads:329865,elapsed:10599.
837,resultType:collection,resultSize:1}' in 10.649000 sec(s):
{"@type":"d","@version":0,"limit":-1,"compositeIndexUsed":1,"fullySortedByIndex"
:false,"evaluated":329865,"documentAnalyzedCompatibleClass":329865,"projectionEl
apsed":47,"involvedIndexes":["v.index"],"groupByElapsed":0,"indexIsUsedInOrderBy
":false,"current":"#13:329063","fetchingFromTargetElapsed":10431,"documentReads"
:329865,"recordReads":329865,"elapsed":10599.837,"resultType":"collection","resu
ltSize":1,"@fieldTypes":"compositeIndexUsed=l,evaluated=l,documentAnalyzedCompat
ibleClass=l,projectionElapsed=l,involvedIndexes=e,groupByElapsed=l,fetchingFromT
argetElapsed=l,documentReads=l,recordReads=l,elapsed=f"}
orientdb {db=test}>

**Comment by lvca** [comment]
Does this changes anything?

    explain select count(*) from v where index >= 9 and index <= 329873

**Comment by dewj** [comment]
orientdb {db=test}> select count(*) from v where index >= 9 and index <= 329873

----+------
    |count
----+------
0   |329865
----+------

1 item(s) found. Query executed in 7.673 sec(s).
orientdb {db=test}> explain select count(*) from v where index >= 9 and index <=
 329873

Profiled command '{limit:-1,compositeIndexUsed:1,fullySortedByIndex:false,evalua
ted:329865,rangeQueryConvertedInBetween:1,documentAnalyzedCompatibleClass:329865
,projectionElapsed:32,involvedIndexes:[1],indexIsUsedInOrderBy:false,groupByElap
sed:0,current:#13:329063,fetchingFromTargetElapsed:7706,documentReads:329865,rec
ordReads:329865,elapsed:7721.0684,resultType:collection,resultSize:1}' in 7.7380
00 sec(s):
{"@type":"d","@version":0,"limit":-1,"compositeIndexUsed":1,"fullySortedByIndex"
:false,"evaluated":329865,"rangeQueryConvertedInBetween":1,"documentAnalyzedComp
atibleClass":329865,"projectionElapsed":32,"involvedIndexes":["v.index"],"indexI
sUsedInOrderBy":false,"groupByElapsed":0,"current":"#13:329063","fetchingFromTar
getElapsed":7706,"documentReads":329865,"recordReads":329865,"elapsed":7721.0684
,"resultType":"collection","resultSize":1,"@fieldTypes":"compositeIndexUsed=l,ev
aluated=l,documentAnalyzedCompatibleClass=l,projectionElapsed=l,involvedIndexes=
e,groupByElapsed=l,fetchingFromTargetElapsed=l,documentReads=l,recordReads=l,ela
psed=f"}

**Comment by lvca** [comment]
Ok, seems the SQL engine doesn't use the index properly. @luigidellaquila is it possible something is changed in the optimizator?

**Comment by tobiemh** [comment]
+1

Even though the index appears to be used, the query still reads through all of the records, making any `count(*)` on large data sets slow and pretty much unusable.

OrientDB version: 2.0.2

**Comment by ajob61** [comment]
Any Progress on this? We are experiencing the same behaviour of indexes being used but the query still reading through the entire record data set which becomes particulary unusable on large data sets as mentioned by @tobiemh. We greatly appreciate a fix or a suggested work around.

**Comment by luigidellaquila** [comment]
Moving to 2.2 because current index API does not allow this

**Comment by seeden** [comment]
+1 for fix of this

**Comment by dmikov** [comment]
Happy new year. It's has been a more then a year. Milestones keep changing. The performance of indexes are crucial to database usage. Do you have a real ETA on this. Our company needs to make decision about back end and while some driver issues are ok to wait on index problems are not ok. Please help with info.

**Comment by gerdhub** [comment]
+1 for fix of this, this is also related to #5945.

**Comment by andreipop-reea** [comment]
+1

**Comment by StarpTech** [comment]
+1

**Comment by TheAdamGalloway** [comment]
+1, this is mission critical for a lot of use cases.

**Comment by seeden** [comment]
run

**Comment by StarpTech** [comment]
@luigidellaquila any progress?

**Comment by gerdhub** [comment]
+1

**Comment by bbourgois** [comment]
+1
