### ISSUE TITLE
Unable to export database while using switch with multiple values

### ISSUE THREAD

**Issue by pdolega** [orientechnologies/orientdb#3465]
I am trying to export database with use of following command:

```
export database /dump.json -compressionLevel=0 -includeInfo=false -includeClusterDefinitions=false -includeSchema=false -includeSecurity=false -includeIndexDefinitions=false -includeManualIndexes=false -includeCluster=cluster1 cluster2 cluster3
```

Unfortunately this doesn't take into account any cluster other than cluste1. I tried to pass this params as:

`-includeCluster="cluster1, cluster2, cluster3"` or ``-includeCluster="cluster1 cluster2 cluster3"`` or `-includeCluster=[cluster1, cluster2, cluster3]` plus couple of more combinations but it didnt help. 

I am using 2.0 version.

**Comment by lvca** [comment]
Fixed.
