### ISSUE TITLE
Error during insertion of key in index

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb#3466]
using 2.0 Final.

I am getting the bellow index error although the record gets inserted into db.
I have tried re-building indexes, deleting and dropping class and it's clusters but to no avail...

```
com.orientechnologies.orient.core.index.OIndexException: Error during insertion of key in index
--> com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Error creation of sbtree with namePhoneNumber.countryCode.irs
--> java.io.FileNotFoundException: /opt/orientdb_databases/galleryapp/PhoneNumber.countryCode.irs [ONetworkProtocolHttpDb]
```

**Comment by laa** [comment]
Hi,
It is too few of information, could you provide you database ?
Do you have any kind of exceptions when you drop and the recreate index ?

**Comment by SpareShade** [comment]
huh!! ah!!
so sorry, the problem was that somehow those files were owned and belonged to the root, which must have happened during rsync...
... it was late, early morning too trigger happy was not thinking to check the files themselves ...
:) ...
