### ISSUE TITLE
WHERE @class.extends('MyAbstractClass')

### ISSUE THREAD

**Issue by MarcelPitch** [orientechnologies/orientdb#3467]
Hi,

I'm using **OrientDB 2.0 Final**.

If there's a way to write a WHERE clause as in the issue subject ?

Example :

![inherits](https://cloud.githubusercontent.com/assets/7402969/5902516/6cc27568-a57b-11e4-9853-6107c5635fc6.PNG)

**The Vertex Class `Jokes` and `Outburst` both extend the abstract Class `PostCategory`**.

**The Vertex Class `Post` and `Comment` both extend the abstract Class `Item`**.

**The Edge Class `HAS_POST` and `HAS_COMMENT` both extend the abstract Class `HAS_ITEM`**.

Because I don't know if 
- I'm starting from a `Post` or a `Comment`
- I'm working in `Jokes` or `Outburst`
in order to get the `Jokes` or `Outburst` Vertex, I would like to write a query like this :
```SQL
SELECT 
FROM 
(
  TRAVERSE 
  	in('HAS_ITEM') 
  FROM 
  (
    SELECT 
    FROM 
    	Item
    WHERE 
    	uid = '12345'
  ) 
  WHILE 
  	$depth <=2
) 
WHERE 
	@class.extends('PostCategory')
```

If it's not possible, I think it could be a nice methods, no ?

But, may be, I'm the only one...

**Comment by lvca** [comment]
Uses:

    Where @this instanceof YourClass

**Comment by MarcelPitch** [comment]
Oh great !!! :+1:

Thank you Luca !

**Comment by SamHard** [comment]
It looks like this function, "instanceof", still needs to be added to the docs.

**Comment by lvca** [comment]
I can find it here: http://orientdb.com/docs/2.2/SQL-Where.html.

**Comment by SamHard** [comment]
Okay, thanks!  That's a logical place to look for it.  For some reason, it doesn't come up using the search function -- maybe content in tables is not indexed.
