### ISSUE TITLE
JAVA API - Returns "misspelled" document @rid

### ISSUE THREAD

**Issue by lrondanini** [orientechnologies/orientdb#3468]
Hi all,

It may be just my fault but, using the JAVA API (document), I'm not able to retrieve a "useful" @rid from the results. Furthermore, it seems to happen only when projections are present (* does not seem to cause this problem). FYI, I've tested this on both MAC and Linux.

To replicate: 

1. install
2. delete the grateful dead db
3. create database Testing
4. run (I tried this from both the web interface and the JAVA apis)
  * create class Person extends V
  * insert into Person set name="Mark"
5. retrieve:

```java
OPartitionedDatabasePool pool = new OPartitionedDatabasePool("remote:localhost/Testing", "root", "password");
ODatabaseDocumentTx database =  pool.acquire();

String query = "select name from Person";
List<ODocument> result = database.query(new OSQLSynchQuery<ODocument>(query));
for(ODocument res: result) {
   System.out.println( res.field( "@rid" )+" "+res.field( "name" ) );
}
```
res.field( "@rid" ) return "#-2:0" instead of the expected "#12:0" but if I change the query to "select from Person" everything is fine (returns "#12:0").

I tried to play around with identity and I can see the right value stored in JSON as rid property but I don't want to have to parse a JSON just to retrieve an id.

Thanks a lot,
Luca

**Comment by lvca** [comment]
What release?

**Comment by lrondanini** [comment]
2.0

**Comment by PhantomYdn** [comment]
@lrondanini , actually in the following your sql

```sql
select name from Person
```
you are quering for list of names, but not a list of objects. That's why return doesn't have valid RID.
If you want to obtain list of objects but with only one field populated you should use SQL:
```sql
select from Person
```
with fetchplan: "name:0 *:-2"

**Comment by lrondanini** [comment]
Thanks a lot, this actually makes total sense! Sorry, I may be still thinking the old SQL way.
