### ISSUE TITLE
Query is slow on a large dataset when using WHERE and ORDER BY clause with different properties

### ISSUE THREAD

**Issue by ArtemShvydchenko** [orientechnologies/orientdb#3470]
We have OrientDb 2.0 graph plocal single-node storage with class Users which contains ~300 000 records.

Execution of following query:

```
    SELECT * FROM Users WHERE active = true ORDER BY name SKIP 0 LIMIT 25
```

takes ~20 seconds to complete.

Both properties 'name' and 'active' are indexed. If we remove either WHERE or ORDER BY clause query will take less then second, which is OK. It seems like combination of indexes in query makes it slow.

**Comment by ArtemShvydchenko** [comment]
For the first time we executed this query we got

**Comment by ArtemShvydchenko** [comment]
Also, for the first time we executed this query we got 
```
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessin
gException: Exception during response processing.

Error: java.lang.OutOfMemoryError: Java heap space
```
Only after increasing server JVM initial Heap size from 512m to 2048m we got query results. We haven't seen this message on ODB 1.7.7

**Comment by laa** [comment]
Hi Artem,
You index filter by one property but order by other one. In such case you should do query like `select from indexvaluesasc:index_name where active = true limit 25`.
Could you try and provide feedback.

**Comment by ArtemShvydchenko** [comment]
Hi Andrey,

Yes, it helps. Following query 
```
select from indexvaluesasc:User__Name_UNIQUE_IDX where active = true skip 0 limit 25
```
takes less than a second.
However, if I put non existent index name after 'indexvaluesasc' I'm getting 
```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command

Error: java.lang.NullPointerException
```
Also, a question is: can we somehow order by multiple columns e.g. name and creation_date? As we are going to build flexible grid component with abilities to order query results by multiple columns it will be very usefull.

Thanks

**Comment by laa** [comment]
@luigidellaquila could you answer on this question ?

**Comment by luigidellaquila** [comment]
Hi Artem,

yes, you can define a composite index (an index on multiple properties) and
you will get this result.

About the NullPointerException, of course a query on a non existing index
is not supposed to work, but we will fix it to return a clearer message.

Luigi


2015-01-27 13:54 GMT+01:00 Andrey Lomakin <notifications@github.com>:

**Comment by ArtemShvydchenko** [comment]
Hi Luigi,

Sorry, just trying to understand how it actually works. Ok, lets assume we have class User with properties 'id', 'name', 'active', 'created_on'. Then we create composite index for all this properties, right? The question is:
1. If we need ordering by 'name' and 'created_on' but with different directions. i.e. 
```
select * from users order by name ASC, created_on DESC
```
What will be the query for such case?
2. If we need ordering by 3 fields - 'id', 'name', 'created_on' excluding 'active' do we need to create separate composite index for this?

Thank you.

**Comment by luigidellaquila** [comment]
Hi Artem,

unfortunately current index implementation (tree index I mean) only support
ordering based on the order of defined fields, that means that an index
defined on "id", "name", "active", "created_on" is ordered by these fields
(in order), so you can use it only in a query like eg.

select * from users order by id ASC, name ASC, created_on ASC


but not, for other cases where you mix ASC and DESC, eg.

select * from users order by id ASC, name DESC, created_on ASC


and not for other cases where you omit first fields in the index, eg.

select * from users order by name ASC, created_on ASC


So if you need all the possible combinations you should define a lot of
indexes, or just rely on basic sorting functionality


Luigi






2015-01-27 16:46 GMT+01:00 Artem <notifications@github.com>:

**Comment by ArtemShvydchenko** [comment]
Thanks for the answer, Luigi.
In our case creating indexes on all possible cases would be too expansive on large amount of fields.
Do you have any plans to make current index implementation more flexible?

**Comment by luigidellaquila** [comment]
Hi Artem,

a more flexible index management (especially for partial match) is in our
intentions, but at this time it's not officially in the roadmap. I suggest
you to follow this group to have news about it.

Thanks

Luigi

2015-01-28 7:51 GMT+01:00 Artem <notifications@github.com>:

**Comment by nidaca** [comment]
Artem, you should try to make a composite index on the [active, name] fields, in this order, because the order is very important as Luigi already mentioned. Then you should actually use the index in this way:

SELECT FROM Users WHERE active = true ORDER BY active ASC, name ASC LIMIT 25

I think this is the way to avoid the overhead of filtering (or sorting) an entire (indexed) cluster, like in:

SELECT FROM indexvaluesasc:Users.(active_)name WHERE active = true LIMIT 25

**Comment by seeden** [comment]
@nidaca non of your tips is not working. I have tried everything without any success.

**Comment by davloperez** [comment]
We are having a similar problem. In this post, my colleague has specified the problem with the alternatives tested, but none has worked.
https://groups.google.com/forum/#!topic/orient-database/fapNCt2fCKo
