### ISSUE TITLE
Script for creating DB

### ISSUE THREAD

**Issue by sanjaypavangp** [orientechnologies/orientdb#3473]
I want to create the SCHEMA from a script (May be through dos prompt) with one go.
Any idea how to proceed will be helpful.
Thank you.

**Comment by vitorenesduarte** [comment]
I use something like [this](https://gist.github.com/vitorenesduarte/c339ec0efaee1f2057ab).

To run it:
```bash
console.sh create.sql
```

Hope it helps.

**Comment by sanjaypavangp** [comment]
Error: java.lang.IllegalArgumentException: Storage type 'plocal' is different by
 storage type in URL

**Comment by vitorenesduarte** [comment]
I just tried, and I it goes without any problems.
Maybe someone can understand that log and help you.
