### ISSUE TITLE
OrientDB 2.0: Schema replication fails on 3-node cluster

### ISSUE THREAD

**Issue by srgg** [orientechnologies/orientdb#3478]
On clean 3-node cluster graph/plocal database was created. System classes had been replicated successfully, hovewer, on different nodes they had "clusters" fields with different values.
During albums-service start, schema was created on only 2 nodes of 3. During database and schema creation, *all 3 nodes were up and running*.

There are workarounds for successfully schema creation and replication on 3 node cluster. However, they are not convenient for usage.

- switch off 2 nodes
- create database and schema on remaining running node
- switch on 2 other in consecutive order

or ("offline" mode)

- switch of all nodes
- create database on one of them in "offline" mode  (create database plocal:/path/to/database/dir user password)
- run this node
- create schema on this node
- switch on 2 other in consecutive order

**Comment by lvca** [comment]
This has been resolved. Could you try with last 2.1.x version?
