### ISSUE TITLE
OrientDB 2.0: Regression in creation of non-lightweight edges

### ISSUE THREAD

**Issue by srgg** [orientechnologies/orientdb#3481]
We found that one of our test cases which was shared in  scope of  https://github.com/orientechnologies/orientdb/issues/2582 fails because in_ and out_ edges are switched. It seems that something wrong with edge direction.

**Comment by lvca** [comment]
Are you able to reproduce this issue on 2.1-rc4?

**Comment by lvca** [comment]
Closing because no answer. In case please reopen/comment this issue.
