### ISSUE TITLE
Detach enhancement

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3482]
**detach** function could take an argument indicating the depth-level intended.

**Comment by lvca** [comment]
Thanks @vitorenesduarte. It could be:

    doc.detach( String iFetchPlan );

In this way the fetchplan syntax is taken, allowing complex rules. Cool!

**Comment by lvca** [comment]
To detach only the first level, it would be:

    doc.detach( "*:1" );

**Comment by vitorenesduarte** [comment]
Great :+1:

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
