### ISSUE TITLE
SQL parser issue than inserting decimal values

### ISSUE THREAD

**Issue by GoorMoon** [orientechnologies/orientdb#3483]
I think is affected all versions
```
orientdb {db=Temp}> create class testclass
Class created successfully. Total classes in database now: 13

orientdb {db=Temp}> insert into testclass set salary=100.178899999c
Inserted record 'testclass#12:0{salary:null} v1' in 0.001000 sec(s).

orientdb {db=Temp}>
```

**Comment by poindextrose** [comment]
Is there a place in the wiki where the 'c' postfix on the number in the example above is documented?

**Comment by GoorMoon** [comment]
https://github.com/orientechnologies/orientdb/wiki/Record-CSV-Serialization

**Comment by lvca** [comment]
The "c" is only in CSV serialization protocol, not in SQL. However, I realized a `decimal()` function is missing. If you work in schema-less there is no a way to set a decimal.

**Comment by GoorMoon** [comment]
@lvca,
Yes in remote binary protocol we have two serializers one CVS and second Binary schema less serialization.
In CSV serialization for decimal values you have to end with 'c' and in the second serializer scale + value. My test case for .NET Driver throw assertion on this values. In my opinion this issue need to be fixed or corrected by changing documentation for binary protocol that decimal values is not supported. However this is a big problem consider that you have database that created by java client and you access to this database from .NET Driver or php , python ...

**Comment by luigidellaquila** [comment]
in v 2.1 there is a function called decimal() that takes a string as an input parameter and converts it to a decimal (absolute precision). Closing.

**Comment by GoorMoon** [comment]
@luigidellaquila ,
so if i send INSERT command via binary protocol i must use this function ?
for example insert into testclass set xxx=decimal('222222222222.33333333')
What about REQUEST_RECORD_CREATE and REQUEST_RECORD_UPDATE ?

**Comment by luigidellaquila** [comment]
Hi @GoorMoon 

I'm reopening this an forwarding to @tglman that can better answer this question

**Comment by tglman** [comment]
@GoorMoon if you use SQL(so using REQUEST_COMMAND) you should use the `decimal()` function, everything else as you know already support decimal so nothing is changed there.

**Comment by lvca** [comment]
Removing In Progress label...

**Comment by GoorMoon** [comment]
@tglman ,@lvca
Double check this and you are right in  REQUEST_RECORD_CREATE and REQUEST_RECORD_UPDATE this is not a issue, why i am remember different ...

Sorry for doubt
