### ISSUE TITLE
Orient 2.0: sum() with multiple args and group by don't work together correctly

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3484]
Test case:
```
create database remote:localhost/testdb root root plocal
insert into V (x, n1, n2, n3) values (1, 1, 2, 3)
insert into V (x, n1, n2, n3) values (1, 5, 6, 7)
insert into V (x, n1, n2, n3) values (2, 10, 20, 30)
insert into V (x, n1, n2, n3) values (2, 100, 200, 300)

# min() and max() work correctly with group by
select x,min(n3),max(n3) from V group by x

----+------+----+----+----
#   |@CLASS|x   |min |max 
----+------+----+----+----
0   |null  |1   |3   |7   
1   |null  |2   |30  |300 
----+------+----+----+----

# sum(n1) works correctly, but sum(n1, n2) doesn't (it appears to just use the last row of the group)
select x,sum(n1),sum(n1,n2) from V group by x   

----+------+----+----+----
#   |@CLASS|x   |sum |sum2
----+------+----+----+----
0   |null  |1   |6   |11  
1   |null  |2   |110 |300 
----+------+----+----+----
```
So the "sum2" column should be 14 where x=1 and 330 where x=2.

**Comment by lvca** [comment]
It's not a bug, but by design: http://www.orientechnologies.com/docs/last/orientdb.wiki/SQL-Functions.html#inline-mode

**Comment by 8forty** [comment]
Maybe I don't understand the doc correctly, but it doesn't mention anything about the behavior in the presence of group by?

Inline mode seems to work as documented without group by, but the results when combined with group by are surprising and IMHO wrong, since it apparently applies the function only to the LAST row of the group and ignores all the others

**Comment by 8forty** [comment]
Ok, so some more testing resulted in this:
```
select x,sum(sum(n1),sum(n2)) from V group by x              

----+------+----+----
#   |@CLASS|x   |sum 
----+------+----+----
0   |null  |1   |14  
1   |null  |2   |330 
----+------+----+----
```
...giving the results I wanted.   

Still I think the Inline mode of the functions aren't working properly when there's a "group by" present, since they arbitrarily just use the last row of the group.  Why not the first row?  Why not all the rows?
