### ISSUE TITLE
Issue with renaming class property

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb#3489]
Hello 

Not sure if this has already been reported, but it could be a bug.

After renaming a class property ie. from 'type' to 'relationType' it is not possible to create an index on 'relationType' unless the DB is rebooted, the error thrown is:
```
Index with name : 'Partnership.relationType' cannot be created on class : 'Partnership' because field: 'relationType' is absent in class definition.
```
trying to drop it:
```
 com.orientechnologies.orient.core.exception.OSchemaException: Property 'relationType' not found in class Partnership
``` 
After restarting the DB everything works fine, ie. it is possible to index 'relationType' etc ...

:)

**Comment by tglman** [comment]
this is a doplicate of https://github.com/orientechnologies/orientdb/issues/3498, now is fixed.
