### ISSUE TITLE
Github wiki links to other markdown files opening in raw view

### ISSUE THREAD

**Issue by Fab1n** [orientechnologies/orientdb#3490]
Take this site:  
https://github.com/orientechnologies/orientdb/wiki/Pivoting-With-Query

Click on the first link there ("SELECT"):  
https://github.com/orientechnologies/orientdb/wiki/SQL-Query.md
^^^
This is where you get.  

Solution: Remove all ".md"-endings from links and we get to the correct view of markdown files on github!!!

**Comment by lvca** [comment]
The Home Wiki Page says: "This wiki is the main source of documentation for developers working with (or contributing to) the OrientDB Open Source project. If this is your first time hearing about OrientDB, we recommend starting with the Orient Technologies website."

We use GitHub only as documentation source, but everything is published on:

http://www.orientechnologies.com/docs/last/index.html

**Comment by lvca** [comment]
.md is because GitBook needs this suffix to work.
