### ISSUE TITLE
Warning log during backup

### ISSUE THREAD

**Issue by biliards** [orientechnologies/orientdb#3492]
I'm following the training and with orientdb-community-2.0-rc2 on a small server, I tested the backup command. The functionality works because the zip file is created, but there is a warning: see the details into zip file
http://download.bilardi.net/download/public/orientdb/backup.warning.zip.
The warning log is:

WARNING Unrecognized parameter /path/file.zip, skipped [OGremlinConsole]                                                                                

May be connected to: https://github.com/orientechnologies/orientdb/issues/2615, but the zip file is not empty.

At your service.

**Comment by lvca** [comment]
Do you have the same issue with 2.0 GA?

**Comment by biliards** [comment]
I have the same issue with 2.0.1 version. I updated the zip file with the details.

**Comment by lvca** [comment]
Could you type here the exact command you executed?

**Comment by biliards** [comment]
I used the one described in the training:
orientdb {db=ConsoleDemo}> backup database /path/file.zip

**Comment by biliards** [comment]
tools/src/main/java/com/orientechnologies/orient/console/OConsoleDatabaseApp.java, L1571
      final int sep = item.indexOf('=');
      if (sep == -1) {                                                                 
        OLogManager.instance().warn(this, "Unrecognized parameter %s, skipped", item); 
        continue;                                                                      
      }
