### ISSUE TITLE
Select statement using AS to assign name to columns not working

### ISSUE THREAD

**Issue by syshex** [orientechnologies/orientdb#3493]
https://groups.google.com/forum/#!topic/orient-database/EI2CEkDV4RI

    select 
    unionall( out("HadProblems"))  as peopleWithProblems ,
    unionall( in("Invited"))  as invitedPeople ,
    unionall( in("Contestant")) as contestants
    from (
     select 
      expand(out("OfType").in("OfType")) 
      from 
      Announcement 
      where 
      itemid = "java123"
      limit -1 
    )
    where 
     out("lecturer").out("Announced").itemid contains "java123"
    limit -1

returns 1 record with 3 columns,   called :  unionall1  , unionall2  and  contestants

And it should have been  peopleWithProblems,  invitedPeople ,  contestants

**Comment by syshex** [comment]
using 2.0

**Comment by lvca** [comment]
I think it was the double space in the first 2 cases. After 2.1 this works.
