### ISSUE TITLE
Support PUSH messages also for db/schema changes

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3496]
Today we support PUSH message from Server to Client only to send changes of Distributed Cfg. We could use it also for:
- [ ] schema changes
- [ ] db clusters add/remove/rename

**Comment by metametametameta** [comment]
Can this be generalized to support *all* metadata changes? (i.e. anything under db.getMetadata()) and not just "schema" and "clusters"

**Comment by lvca** [comment]
Sorry, we are so in late with v2.2 that this feature, even if little, has to be postponed.

**Comment by wouterv** [comment]
You\ re saying that this feature is little. Cant it be planned then for a 2.2.x release, instead of us having to wait yet another 6 months?

**Comment by lvca** [comment]
@tglman what's the status of this issue in v3.0?

**Comment by tglman** [comment]
hi,

It's a working in progress, the infrastructure of push is there, the messages for specific operations are not yet there, due to the mapping of what we actually need and what we actually don't.

**Comment by tglman** [comment]
Hi,

The implementation of all the update of db metadata is implemented, closing this.

Regards
