### ISSUE TITLE
decimal point

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3502]
is that possible to make the following decimal values work as  expected below?

input       =     output(orientdb)
3            =     3.000000
3.1667   =    3.166700

**Comment by lvca** [comment]
@martingg88 the problem is not clear. Do you want help on writing the function "output" that does what you want?

**Comment by martingg88** [comment]
yes.. i wana the output to be with the exact decimal point. 

for example... i wana 3 to be 3.00 if for 2 decimal points.

**Comment by lvca** [comment]
Ok, use the format function. Example:

    select amount.format("%.2f") from salary

**Comment by martingg88** [comment]
Thanks.

But. it there possible to fix certain decimal points (etc: 2/more decimal points) without rounding?

**Comment by lvca** [comment]
What do you mean for fix?

**Comment by martingg88** [comment]
sorry for type error...i mean to fit decimal points with rounding. 

for example as follows: 

3.567 will be 3.56 instead of 3.57.

**Comment by lvca** [comment]
Try to work at string level. Not tested but try this:

    select amount.asString().substring( 0, eval( "$current.amount.indexOf('.') + 3 ") ) from salary

**Comment by martingg88** [comment]
yes. thanks.  this work for select query. 

how about insert query?

I have tried the following, but it still appear as 101.7 in orientdb table

insert into place set lat = '101.700000'.asString().substring( 0, eval( "101.700000.indexOf('.') + 7 ") )
