### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3503]
Hi,

I was iterating through an ORidBag and I noticed it had a null OIdentifiable inside.
Unfortunately I don't have a test case to reproduce it.

But how is this possible? Am I not deleting vertices / edges properly?

Thanks,

**Comment by lvca** [comment]
Is it possible you executed some operation non in tx?

**Comment by vitorenesduarte** [comment]
Hi @lvca 

Don't know if this is enough, but all my connections come from something like this:
```java
public class OrientDatabaseFactory implements ODatabaseThreadLocalFactory {
   @Override
   public ODatabaseDocumentInternal getThreadDatabase() {
      return ODatabaseDocumentPool.global().acquire(url, user, password);
   }
}

**Comment by PhantomYdn** [comment]
@vitorenesduarte in case of using pool: are you closing DB at the end of use?

**Comment by lvca** [comment]
Are you using DocumentDB API, right? Do you ever call:
    db.begin()/commit()
?

**Comment by vitorenesduarte** [comment]
Sorry for the delay guys.
@PhantomYdn Yes, I always close the DB.

@lvca No.
Creating vertices:
```java
try{
  db.open(...);
  // ...
  doc.save();
} finally{
  db.close();
}
```

Creating edges and Deleting vertices / edges:
```java
try{
  db.open(...);
  db.command(...).execute();
} finally{
  db.close();
}
```

**Comment by lvca** [comment]
@vitorenesduarte why are you using DocumentDB API with graph?

**Comment by vitorenesduarte** [comment]
It's not recommended?
For what I understood, Graph API works above Document API, but Document API is faster, just more difficult to code.
