### ISSUE TITLE
ClassCastException using Gremlin

### ISSUE THREAD

**Issue by phaidinyak** [orientechnologies/orientdb#3504]
I'm getting a ClassCastException executing the following code...
The exception when executing the Gremlin Command is suppose to return a Vertex and is returning an ODocument.

   

  OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/ems_graph").setupPool(1, 10);
  OGremlinHelper.global().create();  // ????

    // - Create a graph instance to the database that will not use transactions. 
    OrientGraphNoTx graph = factory.getNoTx();
    try
    {
      OCommandGremlin command = new OCommandGremlin("g.v('#12:0')");
      Map<String, Object> params = new HashMap<String, Object>();
      Vertex vertex = graph.getRawGraph().command(command).execute();
      System.out.println(vertex);
    }
    finally
    {
      graph.shutdown(); 
    }

**Comment by lvca** [comment]
Please can you write here the full exception?

**Comment by phaidinyak** [comment]
Turns out if you change the line...
Vertex vertex = graph.getRawGraph().command(command).execute();
to...
Vertex vertex = graph.command(command).execute();

it works as advertised
