### ISSUE TITLE
It is not possible to select NULL as result value

### ISSUE THREAD

**Issue by DanielRuthardt** [orientechnologies/orientdb#3505]
It seems that all value types except NULL can be selected as result values. The following select
```
SELECT 1 AS integer, 'Test' AS string, NULL AS nothing, [] AS array, {} AS object
```
will select the integer, the string, the array and the object value just fine, but won't select the NULL value.
I have also tried to find hackish ways of selecting a NULL value like calling a SQL or JS function returning NULL or selecting properties from classes with NULL values, but I haven't event found one hackish way to select a NULL value. As soon as projection is used, NULL values are eliminated from the result set.

It doesn't matter if the query is issued from the console or from remote the result is always the same.

For me this is a rather important issue, as it makes
```
INSERT INTO ... FROM (SELECT ...) ...
```
queries impossible, as soon as the target class has mandatory properties, of which some should be filled with NULL.

**Comment by luigidellaquila** [comment]
fixed in develop branch
