### ISSUE TITLE
Application not starting with orientdb (plocal mode) after application crash

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3507]
After crash of our application that uses orientdb in plocal mode and we restarted it, the below log and exception come in nohup.out and it does not start

https://www.dropbox.com/s/67jpm7znckawvz6/nohup.out-application-not-starting-after-crash.txt?dl=0

**Comment by lvca** [comment]
What release?

**Comment by adithyank** [comment]
Orientdb 2.0.1

**Comment by laa** [comment]
Hm,
That is bad.

I think you started and stopped it using the same version ?
Do you have this db ?

On Sun, Feb 1, 2015 at 4:59 AM, K Adithyan <notifications@github.com> wrote:

> Orientdb 2.0.1
> On 31-Jan-2015 11:39 PM, "Luca Garulli" <notifications@github.com> wrote:
>
> > What release?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/orientechnologies/orientdb/issues/3507#issuecomment-72328720>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3507#issuecomment-72348821>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by adithyank** [comment]
Yes. I have the db. Can you tell which files you want. I will upload....

**Comment by laa** [comment]
I think wal files would be enough.

On Mon, Feb 2, 2015 at 2:25 PM, K Adithyan <notifications@github.com> wrote:

> Yes. I have the db. Can you tell which files you want. I will upload....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3507#issuecomment-72449597>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by adithyank** [comment]
Pls find the below the URL of full DB

url : http://nmsworks.co.in/ORIENTDB/rcainv.tar.bz2
login : orientdb
pwd : !@QWnms$

Pls update after you downloaded this... I will have to remove it from our server

**Comment by laa** [comment]
WAL array out of bounds is fixed in 2.0.4 when we fixed durability issue.

**Comment by laa** [comment]
WAL array out of bounds is fixed in 2.0.4 when we fixed durability issue.
