### ISSUE TITLE
Extending OUser and ORestricted, bad OSecurityException handling

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#3509]
Trying to have a `Member` class that extends `OUser` and `OIdentity` extending `ORestricted` with this simplified batch:
```
CREATE DATABASE remote:localhost/testdb root root memory

ALTER CLASS OIdentity SUPERCLASS ORestricted;

CREATE CLASS Member EXTENDS OUser;

#Inserting user_one
INSERT INTO Member SET name = "user_one", status = "ACTIVE", password = "pass", roles = (SELECT FROM ORole WHERE name = 'writer');
UPDATE Member SET password = format("{SHA-256}%s", password.hash('SHA-256')) WHERE name  = 'user_one';

#Inserting user_two
INSERT INTO Member SET name = "user_two", status = "ACTIVE", password = "pass", roles = (SELECT FROM ORole WHERE name = 'writer'), _allowRead = roles;
UPDATE Member SET password = format("{SHA-256}%s", password.hash('SHA-256')) WHERE name  = 'user_two';

#Allowing user_two to manipulate itself
UPDATE Member add _allow = @rid WHERE name = 'user_two';

#Connect with user_one
DISCONNECT;
CONNECT remote:localhost/testdb user_one pass;

#Trying to update user_two with user_one who has a readonly right
UPDATE Member SET name = "changed_user_two" WHERE name = 'user_two';
```

I get as expected the `OSecurityException`
```
Error: com.orientechnologies.orient.core.exception.OSecurityException: Cannot update record #11:1: the resource has restricted access
```
But when inspecting the updated record (with admin user) all its properties are nulled!
Although, the following variants work perfectly:
 * Working with `OUser` instead of `Member`.
 * Removing the query updating the allow field (`UPDATE Member add _allow = @rid WHERE name = 'user_two';`).
 * Removing the `_allowRead` assignment from user_two creation
 * Removing the `roles` assignment from user_two creation

**Comment by red-0ne** [comment]
Using develop branch, commit 5f3ee79

**Comment by red-0ne** [comment]
Any chance to get this issue addressed?

**Comment by lvca** [comment]
What do you mean with "But when inspecting the updated record (with admin user) all its records are nulled!". Which records of the updated record? Could you post here the record?

**Comment by red-0ne** [comment]
Sorry I meant the record properties.

**Comment by red-0ne** [comment]
Before
```
...
#Allowing user_two to manipulate itself
UPDATE Member add _allow = @rid WHERE name = 'user_two';
...```
I get https://gist.github.com/red-0ne/af92b2b9855548b8402f

But after, here's what I get: https://gist.github.com/red-0ne/ab972ab5c38967ed8963

**Comment by red-0ne** [comment]
I don't mean to push this issue but could you at least point out if this is a misbehaviour of orientdb or are we doing something bad. The direction that our application will take will (at some point) depend on how this issue and this one #3590 are handled.

Thank you for dedicating some of your precious time.

**Comment by lvca** [comment]
This is like https://github.com/orientechnologies/orientdb/issues/3453, I'd say to ban the possibility to extend OUser, but rather create a link from/to it.
