### ISSUE TITLE
tool like p6spy

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3510]
Hi,

Is there a tool, or a log setting that can be changed, so I can track all database calls against OrientDB?
If I were using the JDBC connection I could accomplish this with [p6spy](https://github.com/p6spy/p6spy). I'm looking for something like this but for the Java (native) API.

Thanks,

**Comment by lvca** [comment]
Look at: https://code.google.com/p/log4jdbc/

**Comment by vitorenesduarte** [comment]
Hi @lvca.
Thank you for the link. I'm not using OrientDB JBDC driver, but I'll look into it.

**Comment by vitorenesduarte** [comment]
I've look into all logging configurations but it doesn't log what I'm looking for.
I was hopping to see in the logs all queries/commands against the database, or when I do doc.save(), e.g.

If this is not possible, close the issue @lvca.
Thanks again,
