### ISSUE TITLE
Documentation of Network Binary Protocol for Golang Driver 

### ISSUE THREAD

**Issue by webgini** [orientechnologies/orientdb#3512]
Hello , as there is no driver for golang by community , i thought to create small for myself. but i am struggling with network binary protocol stiff , so if possible can any one explain how it works , so i can have batter understanding and will be able to create golang driver or atleast start supporting Orientdb as i can. thank you in advance.

**Comment by GoorMoon** [comment]
Look here,
https://github.com/quux00/ogonori
Maybe you can join effort with Michael.
I can help with binary protocol.

**Comment by webgini** [comment]
thanks man...

On Mon, Feb 2, 2015 at 8:06 PM, Roman Gordon <notifications@github.com>
wrote:

> Look here,
> https://github.com/quux00/ogonori
> Maybe you can join effort with Michael.
> I can help with binary protocol.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3512#issuecomment-72466904>
> .
>



-- 

[image: --]

Vijay Bambhaniya
[image: http://]about.me/vbambhaniya
<http://about.me/vbambhaniya?promo=email_sig>
