### ISSUE TITLE
Lucene engine not available in console

### ISSUE THREAD

**Issue by rmuller** [orientechnologies/orientdb#3521]
`$ORIENTDB_HOME/plugins/orientdb-lucene-2.0-dist.jar` should be added to the class path in `console.[bat|sh]`

Also note that in version 2.0.1 this is still hard code: (notice "UNKNOWN")
`-Dorientdb.build.number="UNKNOWN@r${buildNumber};`

**Comment by lvca** [comment]
@tglman Do you know a way to manage automatically build with maven?

**Comment by lvca** [comment]
Done: plugins are now linked by console.

**Comment by lvca** [comment]
Closed in 2.0
