### ISSUE TITLE
ODatabaseDocumentPool deprecated

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3524]
Hi,

In [this link](http://www.orientechnologies.com/docs/last/orientdb.wiki/Java-Multi-Threading.html), suggests:

``` java
public class MyCustomRecordFactory implements ODatabaseThreadLocalFactory {

  public ODatabaseRecord getDb(){
   return ODatabaseDocumentPool.global().acquire(url, "admin", "admin");
  }
}
```

But I see that ODatabaseDocumentPool is deprecated.
Now the recommended is something like this?

``` java
public class MyCustomRecordFactory implements ODatabaseThreadLocalFactory {

   private OPartitionedDatabasePool pool;

   public MyCustomRecordFactory(String url, String user, String password) {
         pool = new OPartitionedDatabasePool(url, user, password);
   }

   @Override
   public ODatabaseDocumentInternal getThreadDatabase() {
      return pool.acquire();
   }
}
```

**Comment by lvca** [comment]
@laa Please could you update all docs with the new approach?

**Comment by laa** [comment]
Sure.

**Comment by vitorenesduarte** [comment]
Until 2.1 shall I use the deprecated class?

**Comment by laa** [comment]
you should not, you are right about pool usage.

**Comment by vitorenesduarte** [comment]
Thanks @laa (:

**Comment by PhantomYdn** [comment]
And more over: according to my tests deprecated code doesn't work as before. So it's quite dangerous to use it. But we easely moved to OPartitionedDatabasePool.

**Comment by laa** [comment]
@vitorenesduarte why are you so sad ?

**Comment by vitorenesduarte** [comment]
@PhantomYdn your approach is similar to mine?
@laa I'm not sad. That was a happy smile xD
Thank you guys,

**Comment by PhantomYdn** [comment]
@vitorenesduarte Not exactly:

```java
private OPartitionedDatabasePoolFactory poolFactory = new OPartitionedDatabasePoolFactory();
//and in code:
poolFactory.get(url, username, password).acquire();
```

Some details:
[OrientDbSettings](https://github.com/PhantomYdn/wicket-orientdb/blob/master/wicket-orientdb/src/main/java/ru/ydn/wicket/wicketorientdb/OrientDbSettings.java)
[DefaultODatabaseThreadLocalFactory](https://github.com/PhantomYdn/wicket-orientdb/blob/master/wicket-orientdb/src/main/java/ru/ydn/wicket/wicketorientdb/DefaultODatabaseThreadLocalFactory.java)

**Comment by vitorenesduarte** [comment]
Great. Thanks @PhantomYdn

**Comment by unidust** [comment]
So there is currently no way of calling registerEntityClass() from inside of the ODatabaseThreadLocalFactory as it was in the old variant with ODatabaseRecord (see first post)? It was really nice to have a database instance automatically acquired when proxied POJOs were accessed. :(
