### ISSUE TITLE
fetchplan with select expand not working

### ISSUE THREAD

**Issue by AhtashamImtiyaz** [orientechnologies/orientdb#3527]
```
select from (SELECT EXPAND( $c ) LET $a = ( SELECT expand( out('eat')  ) from #13:0 ), $b = ( select expand( out('Follow').out('eat')  ) from #13:1 ), $c = UNIONALL( $a, $b )) fetchPlan in_eat:2
```

This query isn't working in binary protocol. I want to get all the restaurant where #13:1 and people #13:1 'follows' eat. It works but i also want the names of the people as well so using fetchplan. Fetchplan works in studio but not working in binary protocol.

**Comment by tglman** [comment]
Hi,

new query engine in 3.0 deprecate the fetch plan and provide a new way to do the same query, closing this.

Regards
