### ISSUE TITLE
Connection pool issues with multi db instance environment

### ISSUE THREAD

**Issue by uttamatsimility** [orientechnologies/orientdb#3529]
I've created my spring transaction manager to manage odb connection and transactions. It works well until I started playing with multiple databases. After a while I start getting following errors

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
com.orientechnologies.orient.core.exception.ODatabaseException: Database instance has been released to the pool. Get another database instance from the pool with th
e right username and password
	at com.orientechnologies.orient.object.db.OObjectDatabaseTxPooled.checkOpeness(OObjectDatabaseTxPooled.java:137)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.getMetadata(OObjectDatabaseTx.java:144)
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
public class OrientDbPoolDocumentTransactionManager extends AbstractPlatformTransactionManager implements
        InitializingBean, DisposableBean {
    private static final Logger LOG = Logger.getLogger(OrientDbPoolDocumentTransactionManager.class);

    private static final long serialVersionUID = -1837116040878560582L;

    private Map<String, OObjectDatabasePool> poolMap = new HashMap<>();
    private Map<String, PoolInfo> poolInfoMap;

    public void setPoolInfoMap(Map<String, PoolInfo> poolInfoMap) {
        this.poolInfoMap = poolInfoMap;
    }

    public void afterPropertiesSet() throws Exception {
        LOG.debug("afterPropertiesSet");
        if(poolInfoMap == null || poolInfoMap.isEmpty()) {
            throw new IllegalArgumentException("Need to set pool info");
        }

        for(Map.Entry<String, PoolInfo> poolInfoEntry : poolInfoMap.entrySet()) {
            PoolInfo poolInfo = poolInfoEntry.getValue();

            OObjectDatabasePool pool = new OObjectDatabasePool(poolInfo.getDatabaseURL(),
                    poolInfo.getUsername(), poolInfo.getPassword());
            pool.setup(poolInfo.getMinConnections(), poolInfo.getMaxConnections());

            poolMap.put(poolInfoEntry.getKey(), pool);
        }
    }

    public void destroy() throws Exception {
        for(OObjectDatabasePool pool : poolMap.values()) {
            pool.close();
        }
    }

    @Override
    protected boolean isExistingTransaction(Object transaction) {
        LOG.debug("isExistingTransaction " + transaction);
        TransactionHolder txObject = (TransactionHolder) transaction;
        return txObject != null && txObject.isActive();
    }

    @Override
    protected Object doGetTransaction() throws TransactionException {
        TransactionHolder holder = (TransactionHolder) TransactionSynchronizationManager.getResource(ODatabase.class);

        LOG.debug("doGetTransaction " + holder);

        if (holder == null) {
            holder = new TransactionHolder(poolMap);
            TransactionSynchronizationManager.bindResource(ODatabase.class, holder);
        }

        return holder;
    }

    @Override
    protected void doBegin(Object transactionObject, TransactionDefinition definition) throws TransactionException {
        LOG.debug("doBegin");
        TransactionHolder holder = (TransactionHolder) transactionObject;
        holder.begin();
    }

    @Override
    protected void doCommit(DefaultTransactionStatus status) throws TransactionException {
        LOG.debug("doCommit");
        TransactionHolder holder = (TransactionHolder) status.getTransaction();
        try {
            holder.commit();
        } catch (Exception ex) {
            throw new TransactionSystemException("Could not rollback OrientDB transaction", ex);
        }
    }

    @Override
    protected void doRollback(DefaultTransactionStatus status) throws TransactionException {
        LOG.debug("doRollback");
        TransactionHolder holder = (TransactionHolder) status.getTransaction();
        try {
            holder.rollback();
        } catch (Exception ex) {
            throw new TransactionSystemException("Could not rollback OrientDB transaction", ex);
        }
    }

    @Override
    protected Object doSuspend(Object transaction) {
        LOG.debug("doSuspend");
        return ((TransactionHolder)transaction).suspend();
    }

    @Override
    protected void doResume(Object transaction, Object suspendedResources) {
        LOG.debug("doResume");
        ((TransactionHolder)transaction).resume((Map) suspendedResources);
    }

    @Override
    protected void doCleanupAfterCompletion(Object transaction) {
        LOG.debug("Closing connection");
        ((TransactionHolder)transaction).close();
    }
}
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
package com.simility.odb.spring;

/**
 * Transaction holder, wrapping an ODatabaseRecord database and a OTransaction.
 */

import com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal;
import com.orientechnologies.orient.object.db.OObjectDatabasePool;
import com.orientechnologies.orient.object.db.OObjectDatabaseTx;

import java.util.HashMap;
import java.util.Map;

public class TransactionHolder {
    private final Map<String, OObjectDatabasePool> poolMap;
    private Map<String, OObjectDatabaseTx> databaseMap = new HashMap<>();
    private boolean active = false;

    public TransactionHolder(Map<String, OObjectDatabasePool> poolMap) {
        this.poolMap = poolMap;
    }

    public void begin() {
        // create and register new transaction
        for(Map.Entry<String, OObjectDatabasePool> pool : poolMap.entrySet()) {
            databaseMap.put(pool.getKey(), pool.getValue().acquire());
        }

        for(OObjectDatabaseTx database : databaseMap.values()) {
            database.getTransaction().begin();
        }
        active = true;
    }

    public void rollback() {
        for(OObjectDatabaseTx database : databaseMap.values()) {
            database.getTransaction().rollback();
        }
        active = false;
    }

    public void commit() {
        for(OObjectDatabaseTx database : databaseMap.values()) {
            database.getTransaction().commit();
        }
        active = false;
    }

    public void close() {
        for(Map.Entry<String, OObjectDatabaseTx> connEntry : databaseMap.entrySet()) {
            OObjectDatabaseTx oObjectDatabaseTx = connEntry.getValue();
            ODatabaseRecordThreadLocal.INSTANCE.set( oObjectDatabaseTx.getUnderlying() );
            oObjectDatabaseTx.close();
            poolMap.get(connEntry.getKey()).release(oObjectDatabaseTx);

        }
        databaseMap.clear();
        active = false;
    }

    public Map<String, OObjectDatabaseTx> suspend() {
        active = false;
        Map<String, OObjectDatabaseTx> conMap = new HashMap<>(this.databaseMap);
        this.databaseMap.clear();
        return conMap;

    }

    public void resume(Map<String, OObjectDatabaseTx> databaseMap) {
        this.databaseMap.clear();
        this.databaseMap.putAll(databaseMap);
        active = true;
    }

    public boolean isActive() {
        return active;
    }

    public OObjectDatabaseTx getDatabase() {
        if(databaseMap.size() == 1) {
            OObjectDatabaseTx oObjectDatabaseTx = databaseMap.values().iterator().next();
            ODatabaseRecordThreadLocal.INSTANCE.set( oObjectDatabaseTx.getUnderlying() );
            return oObjectDatabaseTx;
        }

        return getDatabase("Default");
    }

    public OObjectDatabaseTx getDatabase(String name) {
        if(!databaseMap.containsKey(name)) {
            throw new IllegalArgumentException("Could not find " + name + " pool");
        }

        OObjectDatabaseTx oObjectDatabaseTx = databaseMap.get(name);
        ODatabaseRecordThreadLocal.INSTANCE.set( oObjectDatabaseTx.getUnderlying() );
        return oObjectDatabaseTx;
    }

    @Override
    public String toString() {
        return "TransactionHolder{" +
                "database=" + databaseMap +
                ", active=" + active +
                '}';
    }
}
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by uttamatsimility** [comment]
Here's the error stack trace

ERROR processing 9172004 Error: com.orientechnologies.orient.core.exception.ODatabaseException: Database instance ha
s been released to the pool. Get another database instance from the pool with the right username and password
com.orientechnologies.orient.core.exception.ODatabaseException: Database instance has been released to the pool. Get another database instance from the pool with th
e right username and password
	at com.orientechnologies.orient.object.db.OObjectDatabaseTxPooled.checkOpeness(OObjectDatabaseTxPooled.java:137)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.getMetadata(OObjectDatabaseTx.java:144)

**Comment by laa** [comment]
Closed because unstable previous implementation of pool was used.
