### ISSUE TITLE
Question : Recommended Index

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3530]
Hi,

What's the recommended index for boolean properties? NOTUNIQUE or NOTUNIQUE_HASH_INDEX? 
Or there's another option?

Thanks,

**Comment by lvca** [comment]
NOTUNIQUE_HASH_INDEX since you can't do ranges with booleans: or true or false ;-)

**Comment by vitorenesduarte** [comment]
Thanks @lvca.
