### ISSUE TITLE
unable to access results of custom functions when called from sql

### ISSUE THREAD

**Issue by mattaylor** [orientechnologies/orientdb#3531]
It used to be (java 1.7) that functions like..
```
_1 = function() { return "hello" },
_2 = function() { return { greet: "hello" },
_3 = function() { return db.query("select from user limit 1");
```

Could be called from sql (or binary) using 

```
select from _1()
select from _2()
select from _3()
etc..
```

and the response would be returned from sql as per the function.

Using 1.8 this is no longer the case, as although the functions are executed, the response values are not returned which effectively renders functions unusable unless invoked through the web api

This is possibly related to #3051

**Comment by lvca** [comment]
The problem seems the function name. If you call _1() as f1() works.

**Comment by lvca** [comment]
Fixed the problem with functions that starts with _

**Comment by mattaylor** [comment]
Agreed that this the '_' is part of the problem, but there is more...

```
test1 = function() { return db.query("select from ouser limit 1") } 

sql> select from test1()

```

I would expect a user record to come back but in fact nothing does.

**Comment by lvca** [comment]
Testing it now...

**Comment by mattaylor** [comment]
any joy?

**Comment by lvca** [comment]
Hey Mat. I tried and works. There was a typo on it. You should rather execute:

    select test1()

**Comment by mattaylor** [comment]
I did try this - but it does not return the document as expected - it just returns a temporary doc which must be expanded from a subselect

eg..

`select expand(test1) from (select test1())`

This is nasty.

**Comment by lvca** [comment]
This is how any function works, but distinct and expand.
