### ISSUE TITLE
upsert support with various factors

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3532]
upsert is able to support of following case?
1. specify which fields are only for insert, only for update, or for both.
   for example, it's useful to specify created timestamp for insert, or modified timestamp for update

**Comment by tglman** [comment]
hi @martingg88 

If i got it right what you are asking is solved in upsert with where clause for ex : 'upsert Test set timestamp = 1 where timestamp =1 ' is that what you are looking for ?

**Comment by martingg88** [comment]
here is the case. 

The following will be updated or inserted. But certain field will be applicable to update/insert respectively. 

1. name , created_date, modified_date.
2. we will need to include 'name, created_date, modified_date.' for insert operation. 
3. we will need to include 'name, modified_date' for update operation. 

how to solve this issue?

**Comment by Ziink** [comment]
+1

Mongodb has $setOnInsert that works in tandem with upsert.

MySQL has
INSERT ... ON DUPLICATE KEY UPDATE

**Comment by snig-b** [comment]
I have a similar issue, Coming from Neo4j which offers MERGE ON CREATE, ON SET , I can't find a similar behavior in OrientDB. Can we get a response on this soon please. 

As such use cases are integral part of our application.

**Comment by tglman** [comment]
we don't support this feature today.

you can do it using the hook interfaces anyway: http://orientdb.com/docs/last/Hook.html

**Comment by Ziink** [comment]
I use **@version** and **if** as workaround. The set clause would look like:

SET field1 = IF(@version, 'updated value', 'initial value')


If you have an ADD clause or a PUT clause, be sure to have a SET clause for the same field so that it get's initialized. Otherwise, the ADD or PUT will fail for an upsert.

**Comment by martingg88** [comment]
@tglman. any example if my super class is vertex?

for example class invoice extends V. 
how can i extends OTriggered to have hook feature?

**Comment by red-0ne** [comment]
@martingg88, this should work:
```sql
ALTER CLASS V SUPERCLASS OTriggered
```

**Comment by martingg88** [comment]
am i still get the graph features if i extend V to Otriggered?

**Comment by red-0ne** [comment]
Yes. I was going to post a simple example but unfortunately simple hooks did not work for me.

**Comment by red-0ne** [comment]
Here it is:
```
orientdb> CREATE DATABASE remote:localhost/test root root memory

Creating database [remote:localhost/test] using the storage type [memory]...
Connecting to database [remote:localhost/test] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost/test
orientdb {db=test}> ALTER CLASS V SUPERCLASS OTriggered

Class updated successfully

orientdb {db=test}> CREATE FUNCTION triggerIt "print('\\nVertex created');" LANGUAGE Javascript

Function created successfully with id=#6:0

orientdb {db=test}> ALTER CLASS V CUSTOM onAfterCreate=triggerIt

Class updated successfully

orientdb {db=test}> CREATE VERTEX V SET name = 'a'

Created vertex 'V#9:0{name:a} v1' in 0.061000 sec(s).

orientdb {db=test}> CREATE VERTEX V SET name = 'b'

Created vertex 'V#9:1{name:b} v1' in 0.011000 sec(s).

orientdb {db=test}> CREATE EDGE E FROM (SELECT FROM V WHERE name = 'a') TO (SELECT FROM V WHERE name = 'b')

Created edge '[E#10:0{out:#9:0,in:#9:1} v2]' in 0.007000 sec(s).
```

As you see, graph specific commands are still working. As well as the triggers that print two `Vertex created` (on the server log as per #4560)

**Comment by martingg88** [comment]
ok. thanks.
