### ISSUE TITLE
INSERT INTO with subquery

### ISSUE THREAD

**Issue by DuskoV** [orientechnologies/orientdb#3540]
I have existing VAuth vertex with "device" property, and VDevice vertex. I try to run this query:

insert into VDevice from (SELECT distinct(device) AS type from VAuth)

If I try to run this query, it's throwing:
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.(SELECT distinct(device) AS type from VAuth)

I'm using the latest v2.0 instance.

**Comment by lvca** [comment]
Have you tried:

    insert into VDevice from SELECT distinct(device) AS type from VAuth
