### ISSUE TITLE
Inconsistent behavior in SQL queries when using RID

### ISSUE THREAD

**Issue by rmuller** [orientechnologies/orientdb#3541]
These are both correct queries:

    select from #19:10000
    select from 19:10000

This is not consistent with:

    select from ProdSpec where @rid > #19:10000  (correct)
    select from ProdSpec where @rid > 19:10000  (not correct, console hangs)

**Comment by vitorenesduarte** [comment]
```sql
delete vertex 19:10000
select from V where @rid in [19:10000]
```
These only work with __#__.

**Comment by lvca** [comment]
Even if OrientDB auto convert numbers to RIDs, please use always # as prefix.
