### ISSUE TITLE
distinct does not work for large collections

### ISSUE THREAD

**Issue by rmuller** [orientechnologies/orientdb#3542]
Using the simple query:

    select distinct(gln) from Party

Works fine for this collection (few 1k records). But the same query (same database) for large collections (> 10M records), gives wrong results (query returns very fast with just a few records).

    select distinct(mfGln) from Product

Used: OrientDB 2.0.1 CE, Java 8_u31 @ Ubuntu 14.04, OrientDB console

**Comment by mattaylor** [comment]
see #2376

**Comment by rmuller** [comment]
Okay, i see this is a duplicate :)

This behavior is not consistent with other dbs, so imo this is a bug.
