### ISSUE TITLE
rand() with sub-query (select) 

### ISSUE THREAD

**Issue by AhtashamImtiyaz** [orientechnologies/orientdb#3543]
Something like

```
select from rand(select from User) limit 3
```

Is it there? If not then i think this would be good.

**Comment by ahtasham637** [comment]
@lvca any update with this?

**Comment by lvca** [comment]
Already available by using math_rand() function and ordering by it. Example:

```
select a, b, math_rand() as c from X order by c
```

**Comment by luigidellaquila** [comment]
Little fix here, the function name is `math_random()`
