### ISSUE TITLE
Transaction rollbacked back issue. 

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3544]
it will cause the transaction was rolled back more times than it was started for the following script. 

1. execute the two following statements in "parallel".

    a. place.update(); 
    b. place.update();

    each of a and b will trigger the following statement. 

     Begin
       Let place = 'insert....'
       Let live = 'create.....'
    Commit
    return $place

**Comment by lvca** [comment]
We fixed this in 2.0.1. Please could you try it?

**Comment by martingg88** [comment]
it doesn't work for 2.0.1. but i put these following two methods in async.parallel() then it work fine.
a. place.update(); 
b. place.update();

async.parallel([
    function(){ place.update();  },
    function(){place.update();}
], callback);

**Comment by laa** [comment]
Hi @martingg88 ,
We are not experts in Node.js could you provide us detailed steps which we need to do in your code or could you provide us separate test case to reproduce this issue ?

**Comment by martingg88** [comment]
seems like this issue is already fixed.

**Comment by laa** [comment]
Cool ! Thank you for feedback.
