### ISSUE TITLE
Index in Embedded Documents

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3548]
```sql
create class Account
create property Account.id string
create index Account.id unique

create class User extends V
create property User.accounts EMBEDDEDLIST Account
```

This works:
```sql
insert into User set accounts = [{"id":"1"}]
insert into User set accounts = [{"id":"1"}]
```

This doesn't:
```sql
insert into Account set id = "1"
insert into Account set id = "1"
```

Why indexes are not supported in the first?

**Comment by Ziink** [comment]
This is not a bug. 

The index on Account is separate from User and does not effect the embedded accounts within User.

You could add the following index to Users for what you want.

create index User.index1 on User(acounts.id) unique string

**Comment by vitorenesduarte** [comment]
Thanks. I see what you're saying.
But I was not able to follow your suggestion. I believe my problem is the same as this #2945.

**Comment by Ziink** [comment]
Try
```SQL
create index User.index1 on User(acounts.id) unique string
```
and then 
```SQL
insert into User set accounts = [{"id":"1"}]
insert into User set accounts = [{"id":"1"}]
```
and you'll see that the second insert is indeed not allowed. I tried it on 2.1rc2

**Comment by vitorenesduarte** [comment]
I removed __string__ from:
```sql
create index User.index1 on User(acounts.id) unique string
```
I didn't know this was possible.
Thanks @Ziink :)

**Comment by Ziink** [comment]
This isn't working for me anymore. Have no idea why it worked earlier and now it doesn't.

**Comment by micha-nerdlichter** [comment]
In 2.1.4: this prevents double inserts as soon as I use an unique_hash_index, but it breaks on updates. See #2945
