### ISSUE TITLE
Wrong sum of a field result

### ISSUE THREAD

**Issue by eugene-kamenev** [orientechnologies/orientdb#3549]
Just migrated data from mysql into orientdb, a class that contains integer field named 'sum', 
Then tried to query: select sum(sum) from OrderDoc
And got negative value result

there is 1 765 000 of documents, and orientdb gave me sum = -160597446 while mysql gave me sum = 4134369850

what I missed here or it is a bug?

**Comment by lvca** [comment]
could it possible that the sum is bigger then Integer bounds? Try doing:

    select sum(sum.asLong()) from OrderDoc
