### ISSUE TITLE
PreparedStatement.executeUpdate() class cast exception 

### ISSUE THREAD

**Issue by j-klm** [orientechnologies/orientdb#3553]
Following code throws `com.orientechnologies.orient.core.record.impl.ODocument cannot be cast to java.lang.Integer` exception with a fresh orient 2.0.1 database and orientdb-jdbc version 2.0

      Properties info = new Properties();
      info.put("user", "root");
      info.put("password", "pass");

      String dbURL = "remote:localhost/testDB";

      OServerAdmin admin = new OServerAdmin(dbURL).connect("root", "pass");
      admin.createDatabase("graph", "plocal");

      Class.forName("com.orientechnologies.orient.jdbc.OrientJdbcDriver");
      OrientJdbcConnection conn = null;
      conn = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:" + dbURL, info);

      conn.createStatement().executeQuery("CREATE CLASS Article ");
      
      PreparedStatement statement = conn.prepareStatement("INSERT INTO Article ( id ) VALUES (?)");
      statement.setString(1, "string value");
      statement.executeUpdate();

This error doesn't occur with a document database. Method `executeUpdate()` should return number of rows inserted instead the code returns `ODocument` object.
 
    public int executeUpdate() throws SQLException {
        try {
            query = new OCommandSQL(sql);
            return database.command(query).execute(params.values().toArray());
        } catch (OQueryParsingException e) {
            throw new SQLSyntaxErrorException("Error on parsing the command", e);
        }
    }

**Comment by vertex-github** [comment]
We've also just hit this issue (2.0.2 server and 2.0.2 JDBC driver)

**Comment by lvca** [comment]
@luigidellaquila can we process prepared statements also with UPDATE, INSERT, etc. with the new parser for 2.1?

**Comment by lvca** [comment]
Guys, are we sure UPDATE/INSERT must return integer in JDBC standard?

**Comment by vertex-github** [comment]
http://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#executeUpdate

executeUpdate returns an int.  executeLargeUpdate returns a long.

'''
Returns:
either (1) the row count for SQL Data Manipulation Language (DML) statements or (2) 0 for SQL statements that return nothing
'''

**Comment by lvca** [comment]
I've checked it and it returns an integer. We have also this test case:

```java
 @Test
  public void shouldUpdateAnItem() throws Exception {

    assertFalse(conn.isClosed());

    Statement stmt = conn.createStatement();
    int updated = stmt.executeUpdate("UPDATE Item set text = 'UPDATED'  WHERE intKey = '10'");

    assertFalse(stmt.getMoreResults());
    assertEquals(1, updated);

    stmt = conn.createStatement();
    ResultSet rs = stmt.executeQuery("SELECT stringKey, intKey, text, length, date FROM Item where intKey = '10' ");
    rs.next();
    assertEquals("UPDATED", rs.getString("text"));

  }
```

Please could you provide a test case?

**Comment by vertex-github** [comment]
Yes, UPDATE does, but INSERT does not (please check the comments on this issue) and also the pull request we issued against orientdb-jdbc last night: https://github.com/orientechnologies/orientdb-jdbc/pull/18

**Comment by lvca** [comment]
It's in 2.0.3-SNAPSHOT.

**Comment by vertex-github** [comment]
Are snapshots built and available on a Maven repo anywhere?

**Comment by lvca** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-jdbc/2.0.3-SNAPSHOT/orientdb-jdbc-2.0.3-20150212.142809-2.jar

**Comment by vertex-github** [comment]
Thanks Luca - how much work would it be to produce a jdbc-all JAR?

**Comment by lvca** [comment]
If you clone the project, execute:

    mvn clean assembly:assembly

And you'll have that jar.

**Comment by vertex-github** [comment]
Understood - but we're wondering if it can be built as part of the artifacts published to the Maven repos - that makes it much easier for client applications to connect to OrientDB

**Comment by lvca** [comment]
I'm not a maven expert, but if you can find a way I definitely do that.
