### ISSUE TITLE
OEntityManager.registerEntityClasses does not check for cycles.

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#3554]
Have a class A that has a reference to B that has a reference to A.

OEntityManager.registerEntityClasses(A.class, true) will give a stackoverflow error.

**Comment by tglman** [comment]
add some tests, seems that this is already fixed. closing.

**Comment by schernolyas** [comment]
Hi @wouterv !

I develop hibernate ogm for OrientDB. Do You want to try it for your project?

**Comment by wouterv** [comment]
Hi @schernolyas 

We developed our own custom solution, so unfortunately it came about a year too late ;-)

**Comment by schernolyas** [comment]
Hi @wouterv !
Can You get link to your implementation?

**Comment by wouterv** [comment]
Hi @schernolyas 
I'm sorry, but the code is proprietary. And it is very much interwoven with our application that it is hardly usable for someone else...

**Comment by schernolyas** [comment]
Hi @wouterv 
Okey. Thank You!
