### ISSUE TITLE
OrientGraphFactory.getTx() expensive

### ISSUE THREAD

**Issue by daniellawry** [orientechnologies/orientdb#3557]
I was noticing some of my queries for an API I'm building were taking fairly long to run (over a second for what I thought were rather simple queries)

Running a test locally using the OrientDB 2.0 Graph API inside Java I'm noticing that the OrientGraphFactory.getTx() is very expensive.

Here's the Java code I'm using to get a handle on the database and start a transaction...

`private OrientGraphFactory factory = new OrientGraphFactory("plocal:C:/OrientDB/orientdb-community-2.0/databases/test").setupPool(1, 10);`
`long start = new Date().getTime();`
`OrientGraph graph = factory.getTx();`
`long end = new Date().getTime();`
`System.out.println("Time to get graph: " + ((Long) (end - start)).doubleValue() / 1000 + "s");`

... followed by some arbitrary query against the DB

When run, the following is logged:

`Time to get graph: 1.201s`

Is that right?  That seems rather expensive.  Is there something I'm doing incorrectly?

**Comment by lvca** [comment]
Are you measuring the first call or further calls?

**Comment by daniellawry** [comment]
first call

**Comment by daniellawry** [comment]
FYI, I just ran a multithreaded test with several API calls and the retrieval of the graph after a few calls drops to 0.0s.

**Comment by daniellawry** [comment]
Is that just the cost to initialize the OrientGraph and add it to the pool the first time?

**Comment by lvca** [comment]
Yes, just the first call ;-)

**Comment by daniellawry** [comment]
Thanks lvca :)
