### ISSUE TITLE
Use of blank spaces in projections

### ISSUE THREAD

**Issue by n0lf** [orientechnologies/orientdb#3559]
Consider the following three identical queries:
    1)select name as projection from OUser
    2)select name [extra blank space] as projection from OUser
    3)select name as  [extra blank space] projection from OUser
The only difference is the number of blank spaces around the "as" sql keyword. I think all three queries gave the same result in orientdb 1.7, but in 2.0 the first one works as intended, the second one returns a field "name" and the third one crashes with a "java.lang.IllegalArgumentException". 

Not a big deal of course but a bit annoying and bad for backwards compatibility.

**Comment by lvca** [comment]
This will be addressed in 2.1

**Comment by luigidellaquila** [comment]
fixed in 2.1 snapshot
