### ISSUE TITLE
make lightweight edges class specific

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#3560]
At the moment lightweight edges are disabled by default. When they're enabled, they're enabled database wide, and this can result in unexpected behaviour - e.g. an edge becomes lightweight merely because it has no properties. Rather than letting OrientDB do this transformation magically, it should be opt in per class:

``` sql
CREATE CLASS Knows EXTENDS E;
ALTER CLASS Knows useLightweightEdges true;
```

This way, the user has control over which edges are lightweight, it's explicitly opt in and means that a query like this doesn't result in magic behavior, it can simply be rejected because it's trying to set properties on a lightweight edge:

``` sql
CREATE EDGE Knows FROM #5:0 TO #5:1 SET foo = "bar"
```

**Comment by lvca** [comment]
:+1:

**Comment by adithyank** [comment]
:+1:
