### ISSUE TITLE
Not unique identifier in detachAll [orientdb-object]

### ISSUE THREAD

**Issue by thewall13** [orientechnologies/orientdb#3561]
This issue is based on: #2525 

To avoid cycles in the detachAll method, all detached objects will be added to a map. The key is based on ODocument.hashCode().

But the method hashCode() has to much collisions to use it as key. 

Example:   
The Object with the ORID   #9:31 has the same hashcode as an Object with #10:0

So I suggest to use the ORID itself as key. The only difference would be a real unique key in the alreadyDetached map.

**Comment by thewall13** [comment]
https://github.com/orientechnologies/orientdb/pull/3562

**Comment by tglman** [comment]
the related pull requests are merged, closing
