### ISSUE TITLE
Link Creation between two big data full classes

### ISSUE THREAD

**Issue by beingsagir** [orientechnologies/orientdb#3571]
what will be the right way to to create a link between two big amount of data classes ? should we create the link during the creation of the class or we can build the link after the data dump ? 

Here the issue is, it is taking more than enough time to create the link after huge amount of data dumped in the classes.

**Comment by lvca** [comment]
It depends by the use case, but usually UPDATE could be expensive, so in most of the cases if you can that at creation time is better.
