### ISSUE TITLE
removecluster

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3574]
Hi,

I was playing with clusters in studio and noticed the following situations:
```sql
create class User
alter class User addcluster EuropeUsers
alter class User removecluster User
```
After this, the studio shows that the default cluster in __User__ class is __-1__, although it still inserts in __EuropeUsers__ cluster (no big problem here).

____
```sql
create class User
alter class User removecluster User
```
This is allowed. The default cluster is __-1__ and the class clusters are __[ ]__.
When trying to insert:
```bash
SEVERE Internal server error:
java.lang.ArithmeticException: / by zero [ONetworkProtocolHttpDb]
```

____

It's possible to change the default cluster? I've look into docs and I can't find it.
Thanks,

**Comment by tglman** [comment]
hi, 
i fixed the first minor problem, but i'm not sure that if there's no cluster it should be the default, is not wrong but i would like to have additional feedback from the rest of the team.

@lvca @laa @luigidellaquila @maggiolo00  WDYT ?

**Comment by lvca** [comment]
If there is no cluster, default should be ok, but usually this is not what users expected, because it's hard to query them once they are there. I think the main problem here is the bug on assigning the next available cluster: EuropeUsers. Does it work now?

**Comment by tglman** [comment]
yes this case is fixed, closing, i'll open another issue for the case of drop of last cluster of a class
