### ISSUE TITLE
"Load Balancing" documentation and implementation is misleading

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3575]
This [link](http://www.orientechnologies.com/docs/last/orientdb.wiki/Distributed-Configuration.html#load-balancing) describes how to setup automatic client-failover.  This technique and implementation does NOT do any load balancing as it is commonly understood, e.g.: https://en.wikipedia.org/wiki/Load_balancing_(computing)

My recommendation would be to re-title that section and add another section for true load balancing that discusses orient's sharding and the possibility of using software load balancing front-ends.

**Comment by lvca** [comment]
:+1: However we could provide a true load balancing by using Hazelcast library on client side, or simply connecting to all the available servers and plug some strategies like round-robin, balanced, etc.

**Comment by lvca** [comment]
@8forty I read you already did this in your project. Would you like to write something we can publish online?

**Comment by 8forty** [comment]
All we've done is run a set of identical orientdb servers on identical hardware.  The data we're storing is loaded by a java app on every server and stored in its local orientdb, so we're not doing any load balancing or automatic failover, just using redundancy to provide increased availability and reliability.

We've done some load-balancing on other projects in the past using apache + tomcat, but I don't think that's applicable to orientdb.  Maybe Samsung has something that will help :)

**Comment by lvca** [comment]
Implemented in develop branch (v2.2.0-SNAPSHOT). It's missing only documentation to close this issue.
