### ISSUE TITLE
Please support CREATE DATABASE SQL

### ISSUE THREAD

**Issue by vertex-github** [orientechnologies/orientdb#3576]
Being able to create databases on the fly for testing is a big help.  Currently, OrientDB doesnt support a CREATE DATABASE type of operation via a JDBC connection.

If this cant be added, how about allowing in-memory DBs to be created on the fly with the addition of a JDBC URL parameter, something like "createIfNotExists".  That way we can configure our unit tests and/or Spring beans to reference an in-mem DB that's created on the fly.

**Comment by lvca** [comment]
We can't do that because you should be logged in the server, but you can't execute SQL commands if you are not connected

**Comment by vertex-github** [comment]
Even for in-memory DBs?

**Comment by lvca** [comment]
It's a problem of security. A user can't create other databases.

**Comment by lvca** [comment]
You can create remote databases on server. Just use OServerAdmin API with root credentials ;-)
