### ISSUE TITLE
missing closed string character

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3582]
the following caused the 'missing closed string character'. 
i suspect there must be the escaped character issue for 'http://gshop.google.com'.

update log add channel = [ {
    'request': 'http://gshop.google.com',
    '@type': 'd',
    '@class': 'channel' } ]

**Comment by luigidellaquila** [comment]
This issue is related to Studio. It removes single line comments before sending the query to the server.
In this case the double slash in the URL is wrongly considered a comment.
Tried the query in console and it works fine.

**Comment by ArkeologeN** [comment]
I tried running the an UPDATE query in `1.7.9` and getting the same error. However, the same query works fine with `Orient Studio`. Any way around? I am using it with php.

**Comment by luigidellaquila** [comment]
it's already fixed in develop branch. Closing
