### ISSUE TITLE
Wrong syntax in documentation

### ISSUE THREAD

**Issue by jonasseglare** [orientechnologies/orientdb#3586]
I believe that a command is wrong in the documentation here

http://www.orientechnologies.com/docs/1.7.8/orientdb.wiki/Tutorial-SQL.html

On one row it says
```
delete Employee where city <> 'London'
```
I believe the correct syntax is
```
delete from Employee where city <> 'London'
```
that is, ```from``` is missing.

**Comment by lvca** [comment]
Fixed in: https://github.com/orientechnologies/orientdb/wiki/Tutorial-SQL. Will be published on Monday. Thanks
