### ISSUE TITLE
OSecurityAccessException upon second connect on a config.xml defined storage

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#3590]
We created a memory based storage in `config/orientdb-server-config.xml`:
```xml
<storage name="test" path="memory:test" userName="user" userPassword="pass" load-at-startup="true" />
```
When starting the server and authenticating for the first time (through console.sh), everything is ok. But as soon as we disconnect and try to reconnect using the same user (`user`:`pass`) a OSecurityAccessException is raised. Shouldn't we be able to reconnect using this user as many times as wanted?

**Note:** If we add a:
```xml
<user name="user" password="pass" resources="*" />
```
Into the `<users />` entry, then subsequent authentications are successfull. But we don't want `user` to have `root` rights and should be authorized to act only upon the `test` database.

Beside that, when the (memory based) database is created on server start, it ships with the default users/passwords (admin, writer, reader) which are completely useless and has to be removed and decent users/passwords defined. More importantly this is IMO a security issue as an attacker might inject records (using default `admin`:`admin`) as soon as the server restarts and before the application get `OUsers` redefined.

On such cases (memory based databases, created upon server start and defined in the config file) the only "predictable" and useful credentials are the ones defined on the `<storage />` entry and no other ones should be created on behalf of the developer/application

OrientDB 2.1-SNAPSHOT (5f3ee79) is used

**Comment by lvca** [comment]
Look at https://orientdb.com/docs/last/DB-Server.html#storages, you should use "loaded-at-startup" instead of "load-at-startup"
