### ISSUE TITLE
[bug] Query on indexed linked records fails or trys to fetch all records

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb#3594]
Hello,
the query on indexed linked records trys to fetch all records when no LIMIT is specified or LIMIT is greater than the actual number of records; or it fails when using arbitrary case insensitive search

Case:
I have Artwork that is linked to ArtworkProfile linked to Artist (which extends Person and inherits lastName). lastName is indexed (notunique) and is case insensitive.

Artist "Berkowitz" has 14 Artworks, orientdb throws the bellow if no LIMIT (or LIMIT is greater than 14)

`select from Artwork where artworkProfile.artist.lastName like "Berkowitz" limit 25' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index [OProfiler`

or it fails if trying to use arbitrary case insensitive like 

`'select from Artwork where artworkProfile.artist.lastName like "%berkowitz%" limit 5' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index'. Exception: java.util.UnknownFormatConversionException: Conversion = '"'`

using 2.0

**Comment by nishantkumar1292** [comment]
Is this fixed? I am still getting this error using version 2.2.21

**Comment by luigidellaquila** [comment]
Hi @SpareShade @nishantkumar1292 

I'm checking it, it's an old query but I'd say there are two problems here:

1. a query with `like "%something%"` cannot be indexed in general (no index stores "central" parts of words for search), so the performance problem is definitely hard to fix. Anyway, the message about  50000 records is just a warning, you can ignore it

2. the UnknownFormatConversionException: this is what concerns me more, I'll see if I can reproduce it

Thanks

Luigi

**Comment by nishantkumar1292** [comment]
I am getting this..
` [TIP] Query 'SELECT FROM vertex_class WHERE @rid = "#17:250006"' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index [OProfilerStub]`

Ideally the query should return only one record. So why this warning? Is there something wrong in my query.

**Comment by luigidellaquila** [comment]
Hi @nishantkumar1292 

The query is not being optimized correctly, this is why you are having this warning. My suggestion is to change it as follows:

```
SELECT FROM #17:250006
```

Thanks

Luigi

**Comment by nishantkumar1292** [comment]
If I understand correctly the first query I mentioned fetches the records for `vertex_class` first and then filters the rid. Whereas the second query directly fetches the result.
Is this correct?

**Comment by luigidellaquila** [comment]
Yes, it's correct

Thanks

Luigi
