### ISSUE TITLE
Parity between `DELETE VERTEX`, `DELETE EDGE` and `DELETE`

### ISSUE THREAD

**Issue by dmarcelino** [orientechnologies/orientdb#3595]
Hi,

With OrientDB 2.0 I had to move from `DELETE` to `DELETE VERTEX` (and that's fine) but one thing I'm sorely missing is the option (`RETURN <returning>`) to return the deleted record(s). Looking at the documentation `DELETE` has a few more options that its counterparts:

**DELETE**

``` sql
DELETE FROM <Class>|cluster:<cluster>|index:<index> [LOCK <default|record>] [RETURN <returning>] [WHERE <Condition>*] [LIMIT <MaxRecords>] [TIMEOUT <timeout>]
```

**DELETE VERTEX**

``` sql
DELETE VERTEX <rid>|<class>|FROM (<subquery>) [WHERE <conditions>] [LIMIT <MaxRecords>>]
```

**DELETE EDGE**

``` sql
DELETE EDGE <rid>|FROM <rid>|TO <rid>|[<class>] [WHERE <conditions>]> [LIMIT <MaxRecords>]
```

Where possible I suggest adding the options missing on DELETE VERTEX/EDGE and bring them up to par as these options will likely be useful to users.

Thanks!

**Comment by karolmie1** [comment]
Yes, lack of return this is painful, especially since lack of native method graph.getEdges(from: V, to: V)

**Comment by lvca** [comment]
@karolmie1 you can use this:

```
Iterable<Edge> v1.getEdges(v2, Direction.BOTH);
```

The methos is `Iterable<Edge> OrientVertex.getEdges(final OrientVertex iDestination, final Direction iDirection, final String... iLabels)`

**Comment by karolmie1** [comment]
Oh, yes, thanks. I missed it because methods like `graph.getVertices()` have return type Vertex, and this interface is more constrained.
