### ISSUE TITLE
Support IF NOT EXISTS and IF EXISTS for CREATE and DROP commands

### ISSUE THREAD

**Issue by vertex-github** [orientechnologies/orientdb#3597]
Being able to create/drop tables/classes without errors is very helpful.

**Comment by yujinlim** [comment]
+1

**Comment by AlexanderRay** [comment]
+1

**Comment by baojie** [comment]
+1

**Comment by pisaruk** [comment]
+1

**Comment by rmchale** [comment]
+1

**Comment by smolinari** [comment]
+1

**Comment by mscarlett** [comment]
+1

**Comment by elexx** [comment]
+1

**Comment by stein321** [comment]
+2

**Comment by matteoredaelli** [comment]
+2

**Comment by StarpTech** [comment]
+1

**Comment by micha-nerdlichter** [comment]
+1

**Comment by micha-nerdlichter** [comment]
would be very helpful for ```create property``` to create migration scripts

**Comment by malibuworkcrew** [comment]
+1

**Comment by smolinari** [comment]
@luigidellaquila - another one to mark as an API Improvement. :wink: 

Scott

**Comment by luigidellaquila** [comment]
Hi guys,

this seems to be next most voted enhancement (after https://github.com/orientechnologies/orientdb/issues/1114), I think it will go high priority soon ;-)

Thanks

Luigi

**Comment by DevMoore94** [comment]
+1

**Comment by tintinweb** [comment]
+1

**Comment by luigidellaquila** [comment]
Hi guys,

This is one of the most voted issues in our issue tracker, so I'm happy to announce that this feature will be available in v 2.2.13 for

- CREATE CLASS
- DROP CLASS
- CREATE PROPERTY
- DROP PROPERTY

Thanks!

Luigi

**Comment by luigidellaquila** [comment]
See full syntax: 

http://orientdb.com/docs/2.2.x/SQL-Create-Class.html
http://orientdb.com/docs/2.2.x/SQL-Drop-Class.html
http://orientdb.com/docs/2.2.x/SQL-Create-Property.html
http://orientdb.com/docs/2.2.x/SQL-Drop-Property.html

**Comment by smolinari** [comment]
@luigidellaquila - Hey Luigi,

If you think about it, with [a full NoSQL ODB](https://github.com/orientechnologies/orientdb-labs/issues/13), all this would be baked into ODB and the DDL wouldn't be needed. :stuck_out_tongue_winking_eye: 

Thanks for the improvement though. For full SQL ODB, it is a nice addition. 

Scott

**Comment by saeedtabrizi** [comment]
Hi @luigidellaquila 
Thanks to hear my voice :) 
https://github.com/orientechnologies/orientdb/issues/6063 . so you can close(partially) this issue . 
Is there any plan for implementing the  TTL feature on the next release ?

Thanks
Saeed Tabrizi

**Comment by maratius1** [comment]
OrientDB Server v2.2.13 (build 2.2.x@r90d7caa1e4af3fad86594e592c64dc1202558ab1; 2016-11-15 12:04:05+0000)
OS: Windows

_Command:_
DROP CLASS NonExistentClass IF EXISTS

_Result:_
Error: java.lang.IllegalArgumentException: Class 'qwe' not found in database
