### ISSUE TITLE
.countClass() doesnt reflect transactional updates

### ISSUE THREAD

**Issue by vertex-github** [orientechnologies/orientdb#3598]
OrientDB v2.02

Insert a row into a class inside a transaction . Invoke countClass() on the class you just inserted into - the API does not reflect the correct count.

SELECT * FROM TestClass issued within the same transaction *does* reflect the correct count.

**Comment by lvca** [comment]
Are you executing it from remote connection?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
