### ISSUE TITLE
[Question] How to Integrate OrientDB with Meteor.js

### ISSUE THREAD

**Issue by wuxianliang** [orientechnologies/orientdb#3602]
Dear Friends
OrientDB is great. I want to use it in Meteor.js projects. I have found two ways to achieve this.

The first one is following @dr-dimitru 's ostrio-Neo4jreactivity https://github.com/VeliovGroup/ostrio-Neo4jreactivity, and he inform us that ---" I've implement reactivity layer based on MongoDB because Neo4j doesn't have any hooks, watchers, observers.". OrientDB have hooks actually.

The second one is following @numtel 's meteor-mysql https://github.com/numtel/meteor-mysql which depends on mysql-live-select https://github.com/numtel/mysql-live-select. "mysql-live-select" is a NPM Package to provide events when a MySQL select statement result set changes. There are already similar discussions in our community by @phpnode. 

Obviously, we prefer a "native" way, the point is that, because oriento https://github.com/codemix/oriento has support hooks, how to custom hooks to define "request sensitive data" to update changes reactively.
We need a OrientDB-live-select. 

I am reading the documents and projects mentioned above and thinking how to do this with OrientDB, but I have found that our OrientDB is different. Maybe, there are smart ways to achieve the same logic which need deep understanding of OrientDB. So I open this issue for related knowledges and suggestions.

I hope I can achieve this project soon. 

Greatly Thank you,  both @lvca  and @dr-dimitru.

**Comment by wuxianliang** [comment]
I have work out a rough demo and will polish codes from next week.
I greatly appreciate @dr-dimitru, @lvca and @numtel. Without their helps I will achieve nothing.
https://github.com/wuxianliang/meteor-orientdb-demo

**Comment by gauravdhiman** [comment]
This may be of some help, have a look at http://www.slideshare.net/LuigiDellAquila/fully-reactive-from-data-to-ui-with-orientdb-nodejs-socketio

Here is the branch for it: https://github.com/orientechnologies/orientdb/tree/livequery

**Comment by auterium** [comment]
@wuxianliang your meteor project is missing the .meteor folder. Could you add it to the repo? I would like to check the packages you used and test your work. Thanks!

**Comment by gauravdhiman** [comment]
@wuxianliang even I tried it and meteor says its not a meteor project. It will be good if you can make a meteor project.

**Comment by wuxianliang** [comment]
@gauravdhiman @auterium 
Sorry. I have upload the meteor files. But I found reactivity does not work any more and I have no time to fix it recently.

I think we have two approaches to a working Meteor-OrientDB package. 
1.  modifying numtel's meteor-pg. This demo has proven this approach is not difficult. Especially with LiveQuery months later.
2.  extending @agershun 's alasql.js to support OrientDB SQL, and modifying meteor-stream's meteor-postgres. This is difficult, but more "Meteor" way.

I am a math teacher of a primary school. If nobody want to code Meteor-OrientDB package, I will. But I still wish some professional programmer will do it.

To SQL tables, trees, graphs in one app is fine worth fighting for.

**Comment by agershun** [comment]
@wuxianliang Can we discuss whet kind of modifications to AlaSQL are required? You can write me a letter or we can skype.

**Comment by wuxianliang** [comment]
@joaobarcia

**Comment by gauravdhiman** [comment]
LiveQuery is now part of Oriento - https://github.com/codemix/oriento/pull/306. It got merged yesterday. Now the job is much simpler, now we just need to write a atmosphere package for Meteor using Oriento. I will look into it and try to come up with something. Hope it will be useful for many people who want Orient and Meteor to work together.

**Comment by luigidellaquila** [comment]
Hi Gaurav,

if you need help on the OrientDB side (you know, LiveQuery is a very new
feature...) just let me know, I'll be happy to give support

Thanks

Luigi


2015-05-20 15:52 GMT+02:00 Gaurav Dhiman <notifications@github.com>:

**Comment by auterium** [comment]
This is good news! Though it still on the master branch and it hasn't been released as a version yet, this means that it will soon. I would be happy to help on the development of the package if anybody is up for it.

**Comment by joaobarcia** [comment]
Great news! Definitely useful for us. I'm not sure how much help I can be in terms of development, but I'll help debug as much as possible.

**Comment by gmonk** [comment]
Any updates on this ?   

Thanks

**Comment by joaobarcia** [comment]
Really looking forward to this implementation as well. I'll happily help you beta test, if you need help let me know!

Cheers

**Comment by avently** [comment]
I'm waiting too:)

**Comment by sadlerdavid** [comment]
Not strong enough technically to contribute to the development.  Willing to assist with testing, and very interested in utilizing a (Meteor - Orientdb) integration.

**Comment by imdark** [comment]
I aould love to start working on this, has anyone made any progress on this or shoul I start my own branch?

**Comment by auterium** [comment]
@imdark I don't think there's any recent progress published around, so if you want to start your own branch you can go ahead. There's quite a bit of people interested in this but that have no idea on where to start (myself included), so if you know where/how to start, you can create the repo, add some initial code and you'll have quite some people helping you out (again, myself included)

**Comment by mikestaub** [comment]
Integrating OrientDB with meteor in a way similar to mongo/minimongo is quite an undertaking, but it is possible now that they support live queries. The biggest challenge I think would be on the client side though, re implementing the mongo api in the browser was not trivial. Luckily, I know of a couple project that are already trying to port graph databases to javascript. They both are targeting the tinkerpop gremlin API, so that it can be used with all the major graph DBs (Titan, Neo4j, OrientDB, etc). I don't have enough time myself to work on this, but hopefully this helps someone get a head start. http://entrendipity.github.io/helios.js/ https://github.com/jbmusso/tinkergraph-js

**Comment by sadlerdavid** [comment]
@mikestaub Thank you for the info and link!  definitely appreciated.

**Comment by imdark** [comment]
The demo is working again, it is only selects from orient via pubsub but I hope to get the live query part working today https://github.com/imdark/meteor-orientdb-demo
As far as the client side api, I would first prefer to get a collection like api working via fetch and sql query builder, and for the orient graph backend to take care of returning normelized data

**Comment by imdark** [comment]
update, the demo does work fully now and synchronizes scores across multiply sessions using live query.
it is very hacky and there are a few limitation in the orient db live query api that will make it nearly impossible to make it truly generic.
orientdb live query does not return the 'rid' of the row making it necessary to make up my own generic id column (i used names in this case), this might be a bug in orientjs.
it also does not return updates in the location of the returned record in an ordered query or allow for rownum as a virtual column, making it a must for the client/meteor server sort the data manually after the network boundary.
also it only works using the experimental branch of orientdb so production use would not be smart

**Comment by lvca** [comment]
@imdark we can do small improvement to Live Query before 2.1 GA. @luigidellaquila why we don't return rids? About the experimental branch what do you mean? This is already part of 2.1-rc5.

**Comment by imdark** [comment]
Rid might be just an issue with orientjs il try to debug that later today.
And as far as rc5 I did mean that branch.
The docs talk about possible memory leaks and disconnection issues and I have seen a faire share of random disconnections.
so I figured this is an issue with the release candidate not being fully pached and tested yet.
This might also be an issue with my configuration.
By the way, do you guys receive pull requests?
When is is the release due? I might try to make a sample implementation  of the the api I would like to see if I have the time.

**Comment by imdark** [comment]
another update on that subject of ids, it seems that on rc, when reciving an updated or new record in a live-query you are passed an object that looks like this:
{ content: { '@type': 'd', '@class': 'players', name: 'Maxwell', score: 120 }, type: 'd', cluster: 12, position: 41, version: 0 } }
Iv filled an issue in orient js, since I belive this should not be solved on the application level
https://github.com/orientechnologies/orientjs/issues/35
so the rid can be created by joining the cluster and position parameters as described here
http://orientdb.com/docs/2.0/orientdb.wiki/Tutorial-Record-ID.html

for now I  am solving this in my own code

**Comment by joaobarcia** [comment]
hi imdark, thanks a lot for your work! I've tested it now and most things seem to be quite nice. I'm just running into a bug when I click 3-4 times quickly on the "add 5 points" button. Let me know if there is another place where I should submit comments/bugs, but I did not find an issues page on your github.

Here is the error log. I'm running Ubuntu 15.04, Meteor 1.1.0.2, OrientDB 2.1 RC5.
'''
W20150716-18:26:57.305(1)? (STDERR) Unhandled rejection OrientDB.ProtocolError: Unsupported operation status: 6
W20150716-18:26:57.306(1)? (STDERR)     at Connection.process (/home/joaobarcia/Dropbox/Diskorse/WebDev tests/Meteor/meteor with orientdb layer/meteor-orientdb-demo-master/.meteor/local/isopacks/npm-container/npm/node_modules/orientjs/lib/transport/binary/connection.js:411:23)
W20150716-18:26:57.306(1)? (STDERR)     at Connection.handleSocketData (/home/joaobarcia/Dropbox/Diskorse/WebDev tests/Meteor/meteor with orientdb layer/meteor-orientdb-demo-master/.meteor/local/isopacks/npm-container/npm/node_modules/orientjs/lib/transport/binary/connection.js:281:17)
W20150716-18:26:57.306(1)? (STDERR)     at Socket.emit (events.js:95:17)
W20150716-18:26:57.306(1)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20150716-18:26:57.306(1)? (STDERR)     at Socket.emit (events.js:92:17)
W20150716-18:26:57.306(1)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20150716-18:26:57.306(1)? (STDERR)     at emitReadable (_stream_readable.js:423:5)
W20150716-18:26:57.306(1)? (STDERR)     at readableAddChunk (_stream_readable.js:166:9)
W20150716-18:26:57.306(1)? (STDERR)     at Socket.Readable.push (_stream_readable.js:128:10)
W20150716-18:26:57.306(1)? (STDERR)     at TCP.onread (net.js:529:21)
W20150716-18:26:57.307(1)? (STDERR) From previous event:
W20150716-18:26:57.307(1)? (STDERR)     at Connection._sendOp (/home/joaobarcia/Dropbox/Diskorse/WebDev tests/Meteor/meteor with orientdb layer/meteor-orientdb-demo-master/.meteor/local/isopacks/npm-container/npm/node_modules/orientjs/lib/transport/binary/connection.js:81:10)
W20150716-18:26:57.307(1)? (STDERR)     at Connection.send (/home/joaobarcia/Dropbox/Diskorse/WebDev tests/Meteor/meteor with orientdb layer/meteor-orientdb-demo-master/.meteor/local/isopacks/npm-container/npm/node_modules/orientjs/lib/transport/binary/connection.js:65:17)
W20150716-18:26:57.307(1)? (STDERR)     at BinaryTransport.send (/home/joaobarcia/Dropbox/Diskorse/WebDev tests/Meteor/meteor with orientdb layer/meteor-orientdb-demo-master/.meteor/local/isopacks/npm-container/npm/node_modules/orientjs/lib/transport/binary/index.js:191:43)
W20150716-18:26:57.307(1)? (STDERR)     at Server.send (/home/joaobarcia/Dropbox/Diskorse/WebDev tests/Meteor/meteor with orientdb layer/meteor-orientdb-demo-master/.meteor/local/isopacks/npm-container/npm/node_modules/orientjs/lib/server/index.js:112:25)
W20150716-18:26:57.307(1)? (STDERR)     at Db.<anonymous> (/home/joaobarcia/Dropbox/Diskorse/WebDev tests/Meteor/meteor with orientdb layer/meteor-orientdb-demo-master/.meteor/local/isopacks/npm-container/npm/node_modules/orientjs/lib/db/index.js:152:24)
W20150716-18:26:57.307(1)? (STDERR)     at process._tickCallback (node.js:442:13)
W20150716-18:26:57.307(1)? (STDERR) From previous event:
W20150716-18:26:57.307(1)? (STDERR)     at Db.send (/home/joaobarcia/Dropbox/Diskorse/WebDev tests/Meteor/meteor with orientdb layer/meteor-orientdb-demo-master/.meteor/local/isopacks/npm-container/npm/node_modules/orientjs/lib/db/index.js:144:4)
W20150716-18:26:57.307(1)? (STDERR)     at Db.exec (/home/joaobarcia/Dropbox/Diskorse/WebDev tests/Meteor/meteor with orientdb layer/meteor-orientdb-demo-master/.meteor/local/isopacks/npm-container/npm/node_modules/orientjs/lib/db/index.js:247:22)
W20150716-18:26:57.307(1)? (STDERR)     at LiveOrientDB.execute (app/server/LiveOrientDB.js:76:25)
W20150716-18:26:57.307(1)? (STDERR)     at [object Object].Meteor.methods.incScore (app/server/server.js:40:16)
W20150716-18:26:57.307(1)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
W20150716-18:26:57.307(1)? (STDERR)     at packages/ddp/livedata_server.js:648:1
W20150716-18:26:57.307(1)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150716-18:26:57.308(1)? (STDERR)     at packages/ddp/livedata_server.js:647:1
W20150716-18:26:57.308(1)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150716-18:26:57.308(1)? (STDERR)     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
W20150716-18:26:57.308(1)? (STDERR)     at packages/ddp/livedata_server.js:546:1
'''

**Comment by imdark** [comment]
I have opened an issues section on my repository, you are welcome to put any issues there.
About creating a demo app it seems resonable, as long as your usecase is not too complex you can even use the current implemnation with predefiend parameterized queries on the server (after the connection issue is fixed, If il have some time I might try to fork and solve it myself).
If you could eleborate on the use case and kinds of queries you intend to use I might be able to offer a more complete estimation (sql?, sorted results?, gremlin?, inserts?, publish level security?, client user auth?, schema design?)
Mostly the connection issues come from the orientjs code itself, i have opened issues about it.
Until the orientjs and orientdb sorting issues are resolved I have started working on a generic meteor package That would contain orient itself (without some of the extra fat) so to allow for easy and quick deployment.
The other main remaining issue is client side api, I have seen an exprimental js wrapper for orient online but for now I am mostly intersted in something like the mongo collection api with a simple getConnectedDocs extension.

**Comment by wuxianliang** [comment]
Thank you very much for your work! @imdark 
Have you seen ccorcos/meteor-any-db https://github.com/ccorcos/meteor-any-db, maybe this package can simplify integration between meteor and orientdb. AlaSQL has a plan to support OrientDB in 0.4 version. https://github.com/agershun/alasql/blob/master/RELEASES.md

**Comment by imdark** [comment]
@joaobarcia I have fixed the connection issues with orientjs and made a pull request, you can now download the code and it should no longer throw those errors.
@wuxianliang I have seen the alasql but the main issue i see is its not really possible to implement security at that implementaion, orientjs already provides a pretty good json return value, string formatting in query and cli.
meteor-any-db look more intersting but not by much.
this kinda looked cool: https://github.com/orientechnologies/orientdb-js
or even just to implement https://github.com/orientechnologies/orientjs#query-builder-delete-record as an object api on the browser might do the trick.

**Comment by joaobarcia** [comment]
Hi @imdark, great! :) I will check the fix today and try to implement your code with our project this week. Will get back to you on progress/issues.

We are creating a crowd based learning platform, with some deep learning algorithms running on the DB side to estimate when the user is ready to learn new concepts.

Regarding our needs: a way to do queries/inserts (be it sql or gremlin, we're agnostic), sorted results is a must, publish level security and client user auth would be nice but we can demo without it and the schema design we can work on it on the OrientDB side, I don't think we have the need to do it from meteor. We also use the OrientDB Studio quite heavily.

The generic meteor package sounds really good. I'm not at all experienced with the behind-the-scenes of Orient packages. Do you think it would be possible, for instance, to use OrientDB and the "accounts" packages? Or is it hardcoded for Mongo and MiniMongo?

**Comment by imdark** [comment]
@joaobarcia I just finished refactoring out and moving the code into an external package you are welcome to use it, the demo was changed to use it as well.
https://github.com/imdark/meteor-orientdb/
https://atmospherejs.com/imdark/meteor-orientdb

As far as the sorted results, you can use sorted results right now but the order does not update from the server since the live query api simply does not give you index information, one way to solve this is to implement client side sorting of the data, this of course will not work well with paged result set but it might do for your demo.
Otherwise I have opend an issue on the orient issue tracker you are wellcome to add feedback there https://github.com/orientechnologies/orientdb/issues/4603
this feature might not be really possible on large datasets since it might not be possible to implement in the db layer and would require you to make the sorting on the server or client side.
I will be looking at the orient java code the next few days to try and implement this myself
another possible way to resolve this is to maintain matrialize ordered views inside orient, I dont think this feature is supported yet but might be fun to implement.
and another alternative is to just implement this using server side pooling, but the performance will be hurt badly. agin if the data base can fit into memory then maybe just sorting on the server or on the client in a webworker is the best way out.

**Comment by joaobarcia** [comment]
Hi @imdark, any news? I've posted two issues on the https://github.com/imdark/meteor-orientdb-demo example. Thanks

**Comment by joaobarcia** [comment]
Hi, just to mention that this issue should not be closed. It is still far from possible to integrate OrientDB with Meteor.js in a proper and stable manner

**Comment by angenome** [comment]
I've being looking forward to the porting of Orientdb to Meteor, and the example in https://github.com/imdark/meteor-orientdb-demo works great. But if I start to extend the example to add/delete players, the client does not reactively update itself (need to refresh the browser for change to show up). Also, the newly added item got exception when I tried to add points. I'm doing something as follows. Can someone give an example what's the proper way to add/del players from the client? Thanks.

// server.js ==============
Meteor.methods({
...
  'delPlayer': function(options) {
      orientdb.execute('delete from players where @rid=:rid', { params:options });
    },
  'addPlayer': function(options) {
      orientdb.execute('insert into players set name=:name, score=50', { params:options });
    }
...
  });

// leaderboard.js  ==============
Template.leaderboard.events({
...
  'click .del': function () {
    var player = oplayers.filter(function(player){
      return player['@rid'] === Session.get("selectedPlayer")['@rid'];
    })[0];
    Meteor.call('delPlayer', { rid: player['@rid'] });
    delete Session.keys["selectedPlayer"];
  },
  'submit .newPlayer': function () {
    var text = event.target.text.value;
    Meteor.call('addPlayer', { name: text });
  }
...
});

// leaderboard.html  ==============
...
  {{#if selectedName}}
    <div class="details">
      <div class="name">{{selectedName}}</div>
      <button class="inc" id="add">Add 5 points</button>
      <button class="del">Delete</button>
    </div>
  {{else}}
    <div class="message">Click a player to select</div>
  {{/if}}
  <form class="newPlayer">
    <input type="text" name="text" placeholder="Player name" />
  </form>

// Newly added item got exception, though the point showed up properly in the client.
I20151129-02:03:15.268(-8)? Exception in handling DDP message: TypeError: Cannot set property '@type' of undefined
I20151129-02:03:15.269(-8)?     at packages/underscore/packages/underscore.js:877:1
I20151129-02:03:15.269(-8)?     at Array.forEach (packages/es5-shim/packages/es5-shim.js:458:1)
I20151129-02:03:15.269(-8)?     at _.each._.forEach (packages/underscore/packages/underscore.js:134:1)
I20151129-02:03:15.269(-8)?     at Function._.extend (packages/underscore/packages/underscore.js:874:1)
I20151129-02:03:15.269(-8)?     at Object.connection.registerStore.update (packages/imdark_meteor-orientdb/packages/imdark_meteor-orientdb.js:428:1)
I20151129-02:03:15.269(-8)?     at Object.store.(anonymous function) [as update] (packages/ddp-client/packages/ddp-client.js:1056:1)
I20151129-02:03:15.269(-8)?     at packages/ddp-client/packages/ddp-client.js:1836:1
I20151129-02:03:15.269(-8)?     at Array.forEach (packages/es5-shim/packages/es5-shim.js:458:1)
I20151129-02:03:15.269(-8)?     at Function._.each._.forEach (packages/underscore/packages/underscore.js:134:1)
I20151129-02:03:15.270(-8)?     at packages/ddp-client/packages/ddp-client.js:1835:1
I20151129-02:03:15.270(-8)?     at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
I20151129-02:03:15.270(-8)?     at [object Object]._.extend._livedata_data (packages/ddp-client/packages/ddp-client.js:1832:1)
I20151129-02:03:15.270(-8)?     at onMessage (packages/ddp-client/packages/ddp-client.js:862:1)
I20151129-02:03:15.270(-8)?     at runWithEnvironment (packages/meteor/packages/meteor.js:1067:1)
I20151129-02:03:15.270(-8)?     at packages/meteor/packages/meteor.js:1080:1
I20151129-02:03:15.270(-8)?     at packages/ddp-client/packages/ddp-client.js:253:1

**Comment by tcastelli** [comment]
Was there any final update to this? just got to find this, and seems very interesting :)
