### ISSUE TITLE
Missing sample database breaks the tutorial

### ISSUE THREAD

**Issue by rjmooney** [orientechnologies/orientdb#3605]
I'm new to OrientDB. I've followed the installation instructions for Ubuntu on the OrientDB [site here](http://www.orientechnologies.com/docs/2.0/orientdb.wiki/Tutorial-Installation.html) and on the DigitalOcean [site here](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-orientdb-on-an-ubuntu-12-04-vps). After cloning the OrientDB repository, I ran *ant clean install* and received a bunch of warnings including:

> [copy] Warning: /home/user/Source/orientdb/graphdb/target/databases/GratefulDeadConcerts does not exist.

I was able to download the database after browsing the [public-databases](https://github.com/orientechnologies/public-databases) repository and copying the database link out of the metadata but now I'm not sure how to import it.

It would be great if the tutorial included instructions on:

* How to download the sample database, and 
* How to import/restore the sample database.

Or better yet, it would be great if the installer did this for me. Additionally:

* While attempting to understand how to import the sample database I downloaded, I clicked on the [Restore Database](http://www.orientechnologies.com/docs/2.0/orientdb.wiki/Console-Command-Restore.html) link under *See Also* on the [Console - IMPORT](http://www.orientechnologies.com/docs/2.0/orientdb.wiki/Console-Command-Import.html) page, which resulted in an HTTP 404.

* The page linked to by [Install on Linux Ubuntu](http://famvdploeg.com/blog/2013/01/setting-up-an-orientdb-server-on-ubuntu/) refers to a release URL that does not exist: https://s3.amazonaws.com/orientdb/releases/orientdb-1.3.0.tar.gz.

As it stands, OrientDB is already dead in the water and I haven't even made it past the installation page.

**Comment by vitorenesduarte** [comment]
Hi @rjmooney 
If you want to easily pass through installation page, why not download the binaries instead of compiling your own OrientDB? :)

**Comment by rjmooney** [comment]
There are two options in the tutorial: Download Binaries and Compile Your Own Community Edition. I chose the latter. 

Unfortunately, there is nothing to indicate in that section that in order to follow the rest of the guide, you'll need to download and install the sample database, nor are there are instructions on how to actually install the database.

If your suggestion is really to just download the binaries, I suggest removing the option to clone source code from the tutorial. Otherwise, if you want people to be able to build from source, I suggest providing instructions on how to download and install the database.

Since I've already consumed a few hours on this, here's how to install a sample database:

1. Clone the source code per the installation instructions.
2. Find the URL of a sample database in the metadata from the [public-databases](https://github.com/orientechnologies/public-databases) [config.json](https://github.com/orientechnologies/public-databases/blob/master/config.json).
3. Download the database. e.g.,
> cd releases/orientdb-community-2.0.2
> mkdir databases && cd databases
> wget http://www.orientechnologies.com/public-databases/GratefulDeadConcerts.zip

4. Extract and copy the database to the *databases* directory. e.g.,
> mkdir GratefulDeadConcerts && cd GratefulDeadConcerts
> unzip ../GratefulDeadConcerts.zip

5. Start the server. e.g.,
> cd ../../bin
> server.sh &

6. Start the client. e.g.,
> client.sh

7. Connect to the sample database. e.g.,
> orientdb> connect remote:localhost/GratefulDeadConcerts admin admin

8. *(optional)* Browse the database via OrientDB Studio at [http://localhost:2480/](http://localhost:2480/).

Finally, it may be *worthwhile to open up the wiki* so that anyone can edit it, because there is incontinuity and numerous errors in the instructions. ;)

**Comment by lvca** [comment]
If you want to generate GratefulDeadConcerts you should run:

    ant clean install -Dorientdb.test.env=ci

**Comment by lvca** [comment]
We've removed the ant support starting from v2.2. The proper way to generate a release is using maven:

    mvn clean install

However we created a script in v2.2 to do it quickly:

    _base/script/deploy.sh

**Comment by rubymorillo** [comment]
Thanks @lvca; when will the Apache Maven instructions be updated in the docs? I'm trying to update the OrientDB tutorial for DigitalOcean and I could definitely use the help with having the most up-to-date steps. Thanks again!
