### ISSUE TITLE
SELECT In return incorrect result.

### ISSUE THREAD

**Issue by gohsianghwee** [orientechnologies/orientdb#3606]
Hi,

I was doing some testing on the SELECT IN operation. The is a Employee class in the database with 2 columns (Name, Age). Only 1 record had been inserted. 

INSERT INTO Employee(Name, Age) VALUES ('GOH', 33). The Name property is set as case insensitive.

When I tried to retrieve the record with this statement. 
SELECT FROM Employee where Name IN ['goh','tan'], 
it returned a correct result. However, when I change it to SELECT * FROM Employee where Name IN ['GOH','tan'], it returned no result. 'GOH' is the correct result if it is case sensitive. In terms of case insensitive, both should also return a record. Am I missing out something? Thanks.

Cordially,
Goh

**Comment by lvca** [comment]
How did you declare the case insensitive? Could you try executing this?

    SELECT * FROM Employee where Name = 'GOH'
