### ISSUE TITLE
Skip duplicate vertices in ETL

### ISSUE THREAD

**Issue by gfinger** [orientechnologies/orientdb#3607]
Hi,
I would like to propose an extension to the vertex component in ETL. Currently if you try to create a vertex that would violate the unique constraint of a corresponding index, you get an exception that stops the complete ETL processing. My proposal is that there should be a configuration parameter for this transformation that gives the option not to stop the whole ETL process but rather skip the current record. I made an exemplary implementation as change to the OVertexTransformer class. Here are the changes:

    public ODocument getConfiguration() {
        return new ODocument().fromJSON("{parameters:[" + getCommonConfigurationParameters() + ","
                + "{class:{optional:true,description:'Vertex class name to assign. Default is V'}}]"
                + ",input:['OrientVertex','ODocument'],output:'OrientVertex'"
                + ",skipDuplicates:{optional:true,description:'Vertices with duplicate keys are skipped', default:false}}"); 

    public Object executeTransform(final Object input) {
    ...
    if (vertexClass != null && !vertexClass.equals(v.getRecord().getClassName())) {
      try {
        v.setProperty("@class", vertexClass);
      } catch (ORecordDuplicatedException e) {
        if (skipDuplicates) {
          return null;
        } else {
          throw e;
        }
      }
    }

**Comment by lvca** [comment]
Hey @gfinger, I like your implementation. Could you send us a Pull Request for ETL project? In this way you figure as contributor and author of this fix. WDYT?

**Comment by gfinger** [comment]
Hi Luca, it looks like there is no develop branch existing in the orientdb-etl repository.

**Comment by lvca** [comment]
Thanks for this contribution. I'm going to update the docs :-)
