### ISSUE TITLE
Edges in Studio 

### ISSUE THREAD

**Issue by lucaiacono** [orientechnologies/orientdb#3609]
ciao, 

quando si creano degli edge tra 2 vertex, nella versione 2, in Studio, ora compare il rid dell'Edge invece di far comparire il rid del vertex che l'edge unisce. come nella versione 1.
saluti
Luca

**Comment by lvca** [comment]
This is because, starting from v2.0, lightweight edges are disabled by default. Enable it to have the same behavior as before.
