### ISSUE TITLE
Using LUCENE filter in WHERE clause along with other filters

### ISSUE THREAD

**Issue by tobiemh** [orientechnologies/orientdb#3611]
Using a LUCENE fulltext index at the same time as another index does not work. Therefore you must use subqueries to limit the result, which is very inefficient when there are many records.

The query...

```sql
SELECT * FROM Person WHERE firstname LUCENE 'Tobie~ OR John~ OR Will~'
```

works correctly, but...

```sql
SELECT * FROM Person WHERE cool=true AND firstname LUCENE 'Tobie~ OR John~ OR Will~'
```

returns no records, and does not produce any errors

***

Using a subquery is successful, but will not use indexes on the outer query and is therefore pretty inefficient on large data sets...

```sql
SELECT * FROM (
    SELECT * FROM Person WHERE firstname LUCENE 'Tobie~ OR John~ OR Will~'
) WHERE cool = true
```

OrientDB version: 2.0.2

**Comment by jagrutkosti** [comment]
Hi,

I am facing the same issue. 
I have 4 tables, Table1, Table2, Table3 and Table4. The search function will first hit Table1 which is indexed using Lucene Engine. I fetch the records using the "lucene" keyword in my query. 
Now, I use 'IN' clause to fetch data from Table2 based on data from Table1.

The data I receive from Table2 is used to perform multiple queries on Table3 and Table4 and then joining them using "UNIONALL" function.

Now this method works but is taking too long to process the query.
I am using the Graph API of tinker pop.

I would really appreciate any help regarding this or any other method by which I can attain the same.

**Comment by maggiolo00** [comment]
Backported to 2.1.x you can use lucene along with other filters
