### ISSUE TITLE
[ObjectDB] unecessary reload of lazyfields

### ISSUE THREAD

**Issue by neuhausjulian** [orientechnologies/orientdb#3614]
The OObjectProxyMethodHandler reloads a field everytime if the version of the object changed. 
Class A declares a field of the type Class B and we update A but the field of B doesn't changed, the object of the B-Field will be reloaded and a new object created.
This seems very unecessary to me. Also it destroys all references to this field content. 

Are there some reasons for this behaviour ?

**Comment by tglman** [comment]
if the version is changed means that the data you have in the object is outdated, that's the reason for the reload of the filed.

**Comment by thewall13** [comment]
The problem I see: 

If B is a registered entiy than is there only one reason to update the field, if B will be replaced with null or an other db-entry of B. In any other case it isn't necessary to update the field and to reload B from Database and to create another proxied instance.

But actually this will be done everytime in case of an update of A and an invoke of the B-getter. 

Every update in the object B itself, will be handled from B and has nothing to do with A.

So if the version of A changed, the field with B should only be reloaded if the database-entry isn't the same anymore. In any other case, it isn't necessary.

Could you please recheck my description ?

**Comment by tglman** [comment]
Hi,

I fixed some wrong reload of data in the object layer long time ago, closing this.

Regards
