### ISSUE TITLE
#3:0

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3615]
Hi, 

```java
      ODatabaseDocument db = new ODatabaseDocumentTx("remote:localhost/New");
      try {
         db.open("admin", "admin");

         db.command(new OCommandSQL("create class Product extends V")).execute();
         db.command(new OCommandSQL("create property Product.data EMBEDDED")).execute();

         db.getMetadata().getSchema().reload();

         ODocument image = new ODocument();
         image.field("url", "images.google.com");
         image.field("size", "80x80");

         ODocument data = new ODocument();
         data.field("image", image);
         data.field("price", 300);

         ODocument product = new ODocument("Product");
         product.field("data", data);
         product.save();
      } finally {
         db.close();
      }
```

Then from studio:
![screen shot 2015-02-17 at 17 19 51](https://cloud.githubusercontent.com/assets/4520516/6233127/caeffc1a-b6c8-11e4-9189-1878037ede10.png)

Why is `#3:0` is being created?

**Comment by rmuller** [comment]
You did not define property `data.image` as EMBEDDED, so a new document is stored in the default cluster #3:0. So it should be: 

````java
data.field("image", image, OType.EMBEDDED);
````

Also note:

+ You do not need to reload the schema
+ `ODocument` offers a fluent / builder style API
+ You are mixing the Document DB with GraphDB (`extends V`)

Also note my previous remark about support vs issues :)

**Comment by vitorenesduarte** [comment]
Hi @rmuller,

I'm reloading because of this #3480.
I now I'm mixing. It's not advisable?

(This morning I posted my new question on stackoverflow, as you recommended)
Thanks again.

**Comment by rmuller** [comment]
Okay, was not aware of #3480. Thanks! (BTW without reloading, it just works for me, just checked).

Mixing Document and Graph commands in this example is strange imo. I do not have a opinion on being good or bad, you should be aware of it.

**Comment by PhantomYdn** [comment]
@rmuller, I guess you are using PLOCAL. In case of remote engine you need to reload: I have this issue too.

@vitorenesduarte , I recommend creation of classess and properties through API. Reloading of schema can lead to unpredictable errors if you are caching somewhere OClass and OProperty

**Comment by rmuller** [comment]
@PhantomYdn yes, I use plocal. Using remote I have the same issue. Did not know that. Thanks!

I fully agree that defining the meta data by API is far better. I do it that way, and have zero issues.

**Comment by vitorenesduarte** [comment]
Hi @PhantomYdn.
My schema is created with a script. I don't need OClass neither OProperty. And to be honest, I haven't take a look to that part of the API. But I will. 
Thanks :+1:
