### ISSUE TITLE
SELECT COUNT(fieldname) does not use an index

### ISSUE THREAD

**Issue by tobiemh** [orientechnologies/orientdb#3622]
Doing a COUNT(fieldname) in sql does not use the index for that field, but reads all records. If it does use the index then #3462 is a subsequent problem

``` sql
CREATE CLASS Person EXTENDS V
CREATE PROPERTY Person.name STRING
CREATE INDEX Person.name NOTUNIQUE_HASH_INDEX
```

``` sql
EXPLAIN SELECT count(name) FROM Person
```

returns...

``` json
{
    "result": [
        {
            "evaluated": 35387,
            "documentReads": 35387,
            "documentAnalyzedCompatibleClass": 35387,
            "recordReads": 35387,
            "resultSize": 1,
        }
    ],
}
```

Related to:
- #3462 - but different as `count(fieldname)` not `count(*)`
- #2706 - but different as not using any where clause

---

OrientDB version: 2.0.2

**Comment by gerdhub** [comment]
+1
