### ISSUE TITLE
orientdb.sh for RedHat chkconfig

### ISSUE THREAD

**Issue by gfinger** [orientechnologies/orientdb#3628]
For enabling the orientdb.sh script with the chkconfig tool on RedHat Linux, certain headers must be included at the beginning of the script. These headers are quite simple, and I think they are of no harm for other Linuxes. Thus I would like to propose to include these headers in the delivery.
These headers are:

```
# chkconfig: 2345 20 80
# description: OrientDb init script
# processname: orientdb.sh
```

they should be included right on the next line after the shebang.

**Comment by lvca** [comment]
What does mean 

    chkconfig: 2345 20 80

? Could you send us a Pull Request to "develop" branch, please? We'll more than happy to merge it.

**Comment by gfinger** [comment]
This denotes the script will start the OrientDB server for the runlevels 2, 3, 4 and 5. In addition, the start priority will be set to 20 while the stop priority will be 80.
Yes, I will send a pull request to the develop branch.

**Comment by lvca** [comment]
Thanks!

**Comment by robfrank** [comment]
Headers are present on orientdb.sh:

https://github.com/orientechnologies/orientdb/blob/develop/distribution/script/orientdb.sh
