### ISSUE TITLE
Renaming Property

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3629]
**SNAPSHOT**

Hi,

``` sql
create class User
create property User.propA string
create index User.propA unique

insert into User set propA = 'valueA'

alter property User.propA name propB

select from User
```

![screen shot 2015-02-19 at 16 02 35](https://cloud.githubusercontent.com/assets/4520516/6270255/7ac0cbe6-b850-11e4-82cc-a308452a1015.png)

propA and it's value are kept in the record. Is this supposed to happen?
Besides that, I was also hoping that the index would be updated:

``` sql
insert into User set propA = 'valueA' # this should work (doesn't)
insert into User set propB = 'valueA' # this shouldn't work (does)
```

Let me know if I did something wrong. 
Thanks

**Comment by PhantomYdn** [comment]
Let me subscribe: I know about this issue...

Could you please clarify what kind of engine are you using? Remote, plocal or memory?

**Comment by vitorenesduarte** [comment]
A noticed this using Studio.

**Comment by hohwille** [comment]
I just downloaded latest OrientDB (community 2.1.9) and logged into studio to play around.
When I rename properties a lot of strange things happen. E.g. I renamed a property only changing the Case. Then I technically had the same property duplicated (name and Name) what I could see when I query data but in schema when I list properties only the renamed property (Name) is shown. The more I tried to fix this by dropping property and or renaming back the worse it got.
To me it seems that the feature to rename properties is currently broken and the handling of properties in different views of studio is inconsistent.

Anyhow, thanks for creating OrientDB. From a conceptual point of view it looks really cool and I like the first impression. I am planning to use it for an big open-source project and might consider it also in commercial projects. However, if things are buggy (and I just hit the surface) this is of course a showstopper... Keep going and let me know if you need further input how to reproduce the problem.

**Comment by smolinari** [comment]
I can confirm. Renaming properties doesn't seem to work properly or rather as expected in Studio.

Working with 2.1.9.

Scott

**Comment by hohwille** [comment]
As I am new to OrientDB I did some anaylsis and investigation. To sum up this is not a critical bug as there are simple workaround to get the intended result.

First of all it seems that the data (vertices, edges, etc.) in OrientDB are rather generic. The Schema and the Data are only loosely coupled. If you change the Schema the Data is not always updated accordingly and might turn inconsistent. That only appears on the first view. It gives you a lot of flexibility and in the end even in strictly typed RDBMS you need to write SQL to migrate your data if you change the schema (yes all these ugly creation of temporary columns and conversion logic, etc.). That is what you also can do in OrientDB. However, when you save a data entity then OrientDB will check it against the schema.

Now if you currently rename a property in the schema, that is properly done in the schema itself. However, the data itself still holds the old property with its value. With simple SQL you can copy the data to the new property (update myclass set newproperty = oldproperty) and remove the old property (update myclass remove oldproperty). So currently the only thing is that renaming a property in schema does not automatically do that for you.

Actually in some cases the data was also automatically copied to the new property. However, if I only change the case of the property name then this never happened.

**Comment by smolinari** [comment]
Out of curiosity, did you also try playing with strictmode? 

`ALTER CLASS User STRICTMODE TRUE`

Scott

**Comment by smolinari** [comment]
@hohwille , it seems ODB's property names are case-insensitive. However, when playing with capitalization, the first result after inserting with an incorrectly written property name returns a duplicated property. 

![image](https://cloud.githubusercontent.com/assets/3314957/12686153/7f1a8d08-c6c8-11e5-800a-34f4a64fef07.png)

I'll write up a bug tomorrow morning. 

Scott

**Comment by smolinari** [comment]
Hmmm...actually I can't tell if there is case sensitivity or not. 

I've written up the issue. 

Scott
