### ISSUE TITLE
.include misbehave with @rid

### ISSUE THREAD

**Issue by josegomezr** [orientechnologies/orientdb#3630]
Reopening #3587, this time no typos.

Query 1

``` sql
select *, inE('puntua').include('comida', 'servicio', 'extras') as puntuaciones, inE('puntua') as taster from Sitio
```

Result:

``` js
{
    "result": [
        {
            "@type": "d",
            "@rid": "#13:0",
            "@version": 7,
            "@class": "sitio",
            "in_come": [
                "#14:3",
                "#14:4",
                "#14:7"
            ],
            "nickname": "alejox",
            "nombre": "El Navegante del Sabor",
            "in_puntua": [
                "#15:0"
            ],
            "puntuaciones": [
                {
                    "@type": "d",
                    "@version": 0,
                    "comida": 8,
                    "servicio": 7,
                    "extras": 5
                }
            ],
            "taster": [
                "#15:0"
            ],
            "@fieldTypes": "in_come=g,in_puntua=g,puntuaciones=z,taster=z"
        }
// ....
    ],
    "notification": "Query executed in 0.043 sec. Returned 2 record(s)"
}
```

Query 2

``` sql
select *, inE('puntua').include('@rid', 'comida', 'servicio', 'extras') as puntuaciones, inE('puntua') as taster from Sitio
```

Result:

``` js
{
    "result": [
        {
            "@type": "d",
            "@rid": "#13:0",
            "@version": 7,
            "@class": "sitio",
            "in_come": [
                "#14:3",
                "#14:4",
                "#14:7"
            ],
            "nickname": "alejox",
            "nombre": "El Navegante del Sabor",
            "in_puntua": [
                "#15:0"
            ],
            "puntuaciones": [
                "#15:0"
            ],
            "taster": [
                "#15:0"
            ],
            "@fieldTypes": "in_come=g,in_puntua=g,puntuaciones=z,taster=z"
        },
       // ...
        }
    ],
    "notification": "Query executed in 0.057 sec. Returned 2 record(s)"
}
```

Notice how `puntuaciones` became an array with only RID, and the other columns where omitted.

**Comment by yujinlim** [comment]
I have the same issue as well. is there any better way to include `@rid` in the query results?

**Comment by kiejo** [comment]
Does anyone know a workaround for this?

**Comment by red-0ne** [comment]
It is very annoying. One could use fetchplan instead, but it is not an option for us. A workaround is very welcome.

**Comment by marcelooliveira** [comment]
I got the same issue. My workaround was to create two different columns in SELECT clause: the first one includes the properties I want, and the second includes only the RIDs. In client side (I use C#), I combine properties and RIDs from both columns in the same object.

**Comment by martingg88** [comment]
any update to solve this issue?

**Comment by salsaysal** [comment]
there seems to be a related issue with 'exclude' method: seems you need to exclude the @rid so that it works.

**Comment by Neglexis** [comment]
Any update on this @lvca or @luigidellaquila? There has been no official statement from you guys, and the milestone just gets changed every now and then.

**Comment by luigidellaquila** [comment]
Hi guys,

I'm afraid we cannot do much for this in v 2.2.x. Each element in the list is a document, if it has an invalid RID it's considered as an embedded document and it's serialized as it is; if it has a regular RID it's considered a linked document, so only the RID is serialized (except if you have an explicit FETCHPLAN that changes this behavior).

So the solution for now is only to have a proper fetchplan in the query.

Good news is that in V 3.0 we completely changed this logic, we deprecated fetchplans and added nested projections (see http://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections), this will hopefully solve the problem once and forever

Thanks

Luigi

**Comment by NaveenAlapati** [comment]
adding toJSON() method after include should solve your problem. Check below sample
select *, inE('puntua').include('@rid', 'comida', 'servicio', 'extras').toJSON() as puntuaciones, inE('puntua') as taster from Sitio

**Comment by NaveenAlapati** [comment]
Adding toJSON() method should work as a work around for now. Check the sample below
select *, inE('puntua').include('@rid', 'comida', 'servicio', 'extras').toJSON().replace("}{", "},{") as puntuaciones, inE('puntua') as taster from Sitio

**Comment by luigidellaquila** [comment]
OrientDB v 3.0 solves problems related to FETCHPLAN and include() with nested projections 
( https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections ), so this issue is no longer relevant.

Closing, thanks

Luigi
