### ISSUE TITLE
OIOException when trying to ORDER BY DESC

### ISSUE THREAD

**Issue by johansjob** [orientechnologies/orientdb#3632]
So I have a GenericCrash class and a SpecificCrash class that extends GenericCrash. At the moment I only have records in the GenericCrash while the SpecificCrash is empty.

When I try to run:

```SELECT FROM GenericCrash WHERE @class='GenericCrash'  ORDER BY @rid DESC```

I get the following error:

SEVERE Internal server error:
com.orientechnologies.common.io.OIOException: You cannot access outside the file
 size (0 bytes). You have requested portion -65536-0 bytes. File: File: specific
crash.cpm os-size=1024, stored=0, filled=0, max=0 [ONetworkProtocolHttpD
b]

If I remove the DESC part I don't get any errors and everything works perfectly if I wrap the select in another select like this:
```SELECT FROM (SELECT FROM GenericCrash WHERE @class='GenericCrash')  ORDER BY @rid DESC```

**Comment by lvca** [comment]
@luigidellaquila I think it's the way we build the inverse iterator when polymorphic classes are involved.

**Comment by luigidellaquila** [comment]
fixed on 2.1 SNAPSHOT (develop branch)
