### ISSUE TITLE
Limit does not work with Lucene indexing

### ISSUE THREAD

**Issue by acmeguy** [orientechnologies/orientdb#3635]
I'm using 2.03 with Lucene which is working fine until I add a limit parameter.

This  "select from ASCustomerEntity where [entity_id,presentation] LUCENE 'venue' " returns 9 entries (correct)
but this "select from ASCustomerEntity where [entity_id,presentation] LUCENE 'venue' limit 5" returns only the first 3  (strange)

**Comment by SpareShade** [comment]
LUCENE  seems to ignore the rest of query parameters  #3640

**Comment by acmeguy** [comment]
is there a ETA available for this fix? (crossing fingers)

**Comment by maggiolo00** [comment]
hi @SpareShade do you have some script to reproduce it?

**Comment by lvca** [comment]
Any chance to have more information on this?

**Comment by acmeguy** [comment]
Hi, Sorry I only saw this question now.

Do you need to know if it has been fixed or do you need a more comprehensive test?
The select statement posted is pretty simple and should result in the same (mis)behavior on any Lucene index.  As soon a limit is added to the query the results become wrong.

Regards,
 -Stefan

**Comment by maggiolo00** [comment]
@acmeguy is this still happening with 2.0.12?

**Comment by maggiolo00** [comment]
hi @acmeguy 
is this still valid?
If yes can you provide a way to reproduce it?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
