### ISSUE TITLE
Cannot use urls in REST request

### ISSUE THREAD

**Issue by rinatio** [orientechnologies/orientdb#3636]
Hello guys,

I'm trying to use simple function and pass a url into it. Here'a an artificial example:

![screen shot 2015-02-21 at 7 49 59 pm](https://cloud.githubusercontent.com/assets/426879/6314943/d59e404e-ba02-11e4-85e0-4219f42ab02b.png)

For some reason it's not processed as full URL even though I see it's urlencoded in the request itself.

**Comment by lvca** [comment]
Try passing: `http%3A%2F%2Fexample.com`

**Comment by rinatio** [comment]
Hi @lvca 

The real issue was with nginx configuration since I used it to proxy to the studio server. Here's a link to the similar [SO](http://stackoverflow.com/q/20496963/1224211) question and the [answer](http://stackoverflow.com/a/20544409/1224211) that helped me. Thank you for response!

**Comment by lvca** [comment]
Ok, so I can close this issue. Thanks.
