### ISSUE TITLE
Add ability to create distributed databases at runtime

### ISSUE THREAD

**Issue by fridgebuzz** [orientechnologies/orientdb#3637]
Currently in-memory databases can't be distributed, but that's set to be changed in v2.2 (issue #3203). Another helpful enhancement would be the ability to create distributed databases via the 
Java API after the nodes are all started, rather than only being able to do so at startup time through a controlled sequence of actions.

**Comment by lvca** [comment]
You can already do that. What's the issue?

**Comment by fridgebuzz** [comment]
Your response to my question on #3203 said that this was not currently supported.

**Comment by lvca** [comment]
This is already allowed, but not for in-memory databases.
