### ISSUE TITLE
sql batch issue

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3638]
The following give me an nullpointer exception or Cannot serialize record. 

any idea?

BEGIN
LET user = SELECT expand(in("own")) FROM account WHERE email = "gan@gmail.com"
LET payment = SELECT expand(out('own')) from $user
COMMIT
RETURN [$user, $payment]

**Comment by rmuller** [comment]
You should use:

````
LET $user = ...
LET $payment = ...
````

($ character is used for identifiers, so the use differs from how bash handles this)

**Comment by martingg88** [comment]
ok thanks

**Comment by phpnode** [comment]
this isn't the case. you don't need sigils when declaring vars

**Comment by martingg88** [comment]
ok thanks. i believe "own" edge refers to two different classes, and thus it cause this issue. sorry it was my mistake

**Comment by rmuller** [comment]
Sorry for the confusion. I had to check it before answering. Within the SELECT statement this is different.
@phpnode Thanks for the correction. Again learned something today :)

**Comment by lvca** [comment]
Yeah, while declaring variables the $ is optional.
