### ISSUE TITLE
Select query with LUCENE in multiple parameters does not return expected results

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb#3640]
Sorry I had to change the heading a few times, it wasn't clear to me where the issue lay.

In the nutshell it seems that when  LUCENE is used in query all other parameters are ignored or not interpreted correctly, related to #3635 .
The relevant use case is in my second comment.

Hello,
just as per heading, I am getting no results, or all records, which are never the expected ones when query has the linked record parameters at the beginning.

OrientDB 2.0.3 :))

For example:
```
select count(*) from Artwork WHERE artist.lastName LUCENE "Smith"  AND galleryReference LUCENE "some AND long AND gallery AND reference"
```
will return all artwork records  by the given artist, instead of only 7 or so.

If the artist's lastName index is changed to NOTUNIQUE 
```
select count(*) from Artwork WHERE artist.lastName = "Smith"  AND galleryReference LUCENE "some AND long AND gallery AND reference"
```
will return no results.

**Comment by SpareShade** [comment]
the things appear to be more convoluted.

in part it is related to #3635 issue involving LUCENE search where it seems that you can't use it on multiple parameters of the same query.
eg.
```
select count(*) from Artwork 
WHERE title  LUCENE "untitled*"  
AND galleryReference LUCENE "some AND  gallery AND reference"
```
will only yield results for 
```
WHERE title  LUCENE "untitled*"  
```
ignoring the rest of query

**Comment by phpnode** [comment]
@SpareShade this is a [known issue](https://github.com/orientechnologies/orientdb-lucene/issues/41), until it's fixed, you can work around it with this:

```sql
SELECT count(*) FROM (
    SELECT intersect($a, $b)
    LET $a = (SELECT FROM Artwork WHERE title  LUCENE "untitled*"),
        $b = (SELECT FROM Artwork WHERE galleryReference LUCENE "some AND  gallery AND reference")
)
```

**Comment by SpareShade** [comment]
@phpnode oo yep that is pretty handy, thank you!

**Comment by luigidellaquila** [comment]
Hi guys, 

This issue is already fixed in v. 2.1

I'm closing it, please reopen if you experience any similar problems

Thanks

Luigi
