### ISSUE TITLE
classCastException for cluster

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3643]
i do have following issue when insert into cluster. However it's working fine for insert class instead. 

Failed for cluster as follows: 
java.lang.String cannot be cast to java.util.Date
INSERT INTO cluster:log_visit SET  ctime = '2015-02-23T18:42:31+0000'

work for class as follows: 
INSERT INTO log SET  ctime = '2015-02-23T18:42:31+0000'

**Comment by martingg88** [comment]
i believe the cluster is not inherited schema from class itself and thus it cause the issue. do you have any idea how to make sure the new created cluster inherited coherent schema from class itself?

**Comment by 8forty** [comment]
You might need to add the cluster to the class, e.g. "ALTER CLASS ADDCLUSTER log_vist"

**Comment by martingg88** [comment]
i tried this command...but it still doesn't work..strange..

**Comment by martingg88** [comment]
tested. it worked for version  2.0.1. But it doesn't work for version  2.0.3. anyone can check it?

**Comment by martingg88** [comment]
yes...seem like this issued has been solved for 2.0.5 version. 
Yet cluster is inherited scheme from parent class

**Comment by lvca** [comment]
Cool, Closing it.
