### ISSUE TITLE
Enterprise Auditing (Enteprise Edition)

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3647]
Enterprise Edition.

Features:
- Pluggable output:
 - File
 - DB
- Permissions:
 - Change configuration
 - Read/Write auditing information
 - Purge 
 - Auto-rotate

**Comment by lvca** [comment]
Implemented in Enterprise Edition

**Comment by lvca** [comment]
Documented: https://github.com/orientechnologies/orientdb-docs/wiki/Auditing

**Comment by yon86** [comment]
any chance this comes to the community edition

**Comment by lvca** [comment]
@yon86 I'm sorry but this is part of EE product. You can still use it in development and if you need EE in production you could contact the info|--at--|orientdb.com to have a quote. If you are a startup or you need OEM licenses prices are very low.
