### ISSUE TITLE
Add support for Java 8 date and time types (JSR-310) to Object API

### ISSUE THREAD

**Issue by sovanegger** [orientechnologies/orientdb#3652]
It would be great to have a support for Java 8 date and time types in the Object API.

**Comment by JWGmeligMeyling** [comment]
:+1: Here as well!

**Comment by ddrozdov** [comment]
Any progress here?

**Comment by tglman** [comment]
Hi,

No, no progress here, probably will come something later in 3.1 /3.2

Regards

**Comment by mslowiak** [comment]
Hi there,
Any updates?
