### ISSUE TITLE
server.bat - java not found (although it exists)

### ISSUE THREAD

**Issue by asherchayyim** [orientechnologies/orientdb#3653]
When starting the orientdb server via console, in the script "server.bat" there is a line:

```if exist "%JAVA_HOME%\bin\java.exe" goto setJavaHome```

the issue is that when the variable %JAVA_HOME% contains itself double-quotes, the above line doesn't function as expected, because it is interpreted like:

```if exist ""C:\Program Files\Java\jre7"\bin\java.exe" goto setJavaHome```

notice the double double-quotes **inside** the already double-quoted string. 
this makes the full path incorrect and java is not found, although it exists right there.

so, this line in the script "server.bat" should actually be:

```if exist "%JAVA_HOME:"=%\bin\java.exe" goto setJavaHome```

notice the **:"=** added inside the variable.
this removes any double quotes from the variable value and the script begins to work correctly.

---------------------------------------------------------------------------------------------

same issue for another line below:

```set JAVA="%JAVA_HOME%\bin\java"```

in this case, the possible double-quotes have to be removed again, like this:

```set JAVA="%JAVA_HOME:"=%\bin\java"```

again, notice the **:"=** added inside the variable.

---------------------------------------------------------------------------------------------

Please update the "server.bat" script ASAP.

Also, please search for other occurrences of this bug in other .bat scripts in the installation.

Thank you.

**Comment by lvca** [comment]
@asherchayyim WDYT about providing a Pull Request with such changes? This is the best way to become a contributor. Please send it against "develop" or "2.0.4-hotfix" branch.

**Comment by lvca** [comment]
@G4br13l3 can you please test this?

**Comment by G4br13l3** [comment]
With this alternative syntax the server.bat script works even with paths already containing double quotes.
@asherchayyim thanks for your contribution.
