### ISSUE TITLE
RIDs reuse or online .cmp compaction are needed for fast changing data

### ISSUE THREAD

**Issue by kitaeff** [orientechnologies/orientdb#3654]
In persisted queues lifetime for individual record is small which keeps data file (.pcl) relatively small. But uniqueness of record ids causes unlimited .cmp growth without possibilities to shrink its size (except total database rebuilding)

**Comment by laa** [comment]
yes, it is true, 4 bytes per deleted record, do you have issues with such approach ?

**Comment by kitaeff** [comment]
Our tests showed file size is about 12-13 megabytes per million records. Actual data file never grew over 5Mb. With planned load .cmp file will exceed gigabyte in couple of month. This *is* a big issue.

**Comment by lvca** [comment]
We could provide a command like "compact cluster x" to do compaction. @laa Does it make any sense?

**Comment by laa** [comment]
Current rid -> phisical position mapping does not support compaction without breaking rids of records and as result data consistency. If we want to keep all links unbroken we need other implementation of this mapping like linear hashing or hopscotch hashing for example. To keep O(1) complexity for reads but not for writes.

**Comment by lvca** [comment]
By using hashing we already tested that it would be extremely slow in comparison to current O(1). Note also that

    current O(1) < O(1) of hashing

**Comment by laa** [comment]
when did we test it  ? also everything has trade off space vs performance usual one.

**Comment by lvca** [comment]
Don't you remember more than 1y ago when you tried to do that, but performance penalty was high?

**Comment by laa** [comment]
May be, but any way , it was different architecture, and what is more important we always have trade off hash table the most inexpensive data structure which supports removal without space overhead. So  either this one or we live with holes.

**Comment by thePunIssuer** [comment]
Hi, we're facing the same issue. We are using OrientDb to store data on a Smart Home Gateway, and we noticed that a rolling set of power consumption values makes the database directory grow indefinitely, and rather quickly.
Unfortunately, we found out that offline compacting via export/import (as Andrey Lomakin suggested in https://groups.google.com/d/msg/orient-database/SBMxmWoKxBE/O6qJisZ-76EJ) does not work for us either, as it changes the RIDs we are using throughout the system.
This is a major issue for us, and currently we cannot see any other way forward than switching to a different storage system.

**Comment by lvca** [comment]
@thePunIssuer We have in our roadmap a `COMPACT DATABASE|CLASS|CLUSTER` that compact the cluster space internally and optimizing the layout of internal records by RID to make scan faster. The first implementation will lock the database/class/cluster during the compact, but then will work in background.

**Comment by manuelmager** [comment]
@lvca In what month will the first implementation be available approximately? Are we talking 4 weeks or 9 months? Just trying to get a rough feeling.

**Comment by lvca** [comment]
hey guys, is your problem only with the CMP file (the file that maps the RIDs to physical positions) or in general you noticed the space wasn't reclaimed?

**Comment by manuelmager** [comment]
Problems we are facing:
* *.cpm is growing fast and cannot be shrinked without changing the RIDs.
* collections_x.sbc files are getting large. We do not know what it contains exactly, can you help our understanding?
* *.pcl should be okay by configuring file.defrag.holeMaxDistance, but we are only in the process of deleting old values and reclaiming space, so we have not experienced whether that works as expected.

**Comment by laa** [comment]
@manuelmager " file.defrag.holeMaxDistance" is old parameter and it is not used in current implementation.  .sbc files contain collection of edges in your database.

**Comment by manuelmager** [comment]
Is there anything that can or should be configured to improve reclaiming of space?

**Comment by laa** [comment]
@manuelmager you can set the parameter "sbtreebonsai.freeSpaceReuseTrigger" to 0, so your edge containers will reuse all free space.
