### ISSUE TITLE
Wrong link on sql where documentation page

### ISSUE THREAD

**Issue by xvik** [orientechnologies/orientdb#3655]
On page http://www.orientechnologies.com/docs/last/orientdb.wiki/SQL-Where.html
at the bottom of the page
```
To set custom variable use the LET keyword.
```
LET link goes to https://code.google.com/p/orient/wiki/SQLQuery#LET_block
correct link is:
http://www.orientechnologies.com/docs/last/orientdb.wiki/SQL-Query.html#let-block

**Comment by lvca** [comment]
Done, soon online. thanks.
