### ISSUE TITLE
(docs) Record version for new records

### ISSUE THREAD

**Issue by tight** [orientechnologies/orientdb#3656]
According to docs : http://www.orientechnologies.com/docs/last/orientdb.wiki/Concepts.html#record-version

> When a record is created, the version is zero.

Looks like the version is set to 1 for new records

```
> create class Foo extends V  

Class created successfully. Total classes in database now: 15

> insert into Foo set name = 'bar'

Inserted record 'Foo#14:0{name:bar} v1' in 0.005000 sec(s).

> select @version from Foo
----+------+-------
#   |@CLASS|version
----+------+-------
0   |null  |1      
----+------+-------

1 item(s) found. Query executed in 0.004 sec(s).
```

**Comment by tight** [comment]
PS: tested against Odb 2.0.3

**Comment by lvca** [comment]
Version can be 1 or higher depending on different cases. Removed that from docs. Thanks.
