### ISSUE TITLE
GridFS anternative with OrientDB?

### ISSUE THREAD

**Issue by hansgru** [orientechnologies/orientdb#3658]
Hi,

OrientDB seems like quite a good replacement for MongoDB apps if Java is a requirement as running platform. Are there any plans for a GridFS similar support too?
http://docs.mongodb.org/manual/core/gridfs/
http://www.slideshare.net/chrisjpowers/grid-fs

**Comment by lvca** [comment]
We supports "BLOB" in this way: http://www.orientechnologies.com/docs/last/orientdb.wiki/Binary-Data.html

**Comment by hansgru** [comment]
> We supports "BLOB" in this way: http://www.orientechnologies.com/docs/last/orientdb.wiki/Binary-Data.html

Other "cons" for "Store on file system and save the path in the document":
- no transaction support, and bad error management.
- hard to move, backup/restore and keep stuff in sync.

The main selling point of GridFS is the extremely simple to use API (besides the performance).
IMHO none of the solutions listed in the "Binary Data" document come close to GridFS.
http://blog.mongodirector.com/when-to-use-gridfs/

So it would be really helpful if OrientDB would have such support: it could be almost a "drop in replacement" for MongoDB.

**Comment by lvca** [comment]
I agree that creating a simple interface like GridFS on top of OrientDB would be straightforward with the additional pros:
- transactions
- links: you could crete a real file system as tree in OrientDB with no indexes

**Comment by lvca** [comment]
Not relevant anymore, closing it.
