### ISSUE TITLE
Creating a simple + function with REST API

### ISSUE THREAD

**Issue by tight** [orientechnologies/orientdb#3659]
With ODB 2.0.3, when creating a simple function containing a plus sign, the function is not correctly saved, the plus sign disappear (but it works with studio)

```
$ curl --user admin:admin -X POST http://localhost:2480/document/temp -d "{
  '@class': 'OFunction',
  'name': 'plus',
  'language': 'javascript',
  'parameters': [\"a\", \"b\"],
  'code': 'return a + b;',
  'idempotent': true
}"

$ curl --user admin:admin http://localhost:2480/document/temp/6:0
{
    "@type": "d",
    "@rid": "#6:0",
    "@version": 1,
    "@class": "OFunction",
    "name": "plus",
    "language": "javascript",
    "parameters": [
        "a",
        "b"
    ],
    "code": "return a   b;",
    "idempotent": true
}
```

**Comment by red-0ne** [comment]
The query payload must be urlencoded. Replacing `a + b` with `a %2B b` should give the intended result.

Note that *all* the payload have to be encoded.

**Comment by tight** [comment]
Thanks !

Also, looks like adding `--header "Content-Type: application/json"` to `curl`also works

**Comment by red-0ne** [comment]
Yes, as it overrides the default(?)  `application/x-www-form-urlencoded` content-type
