### ISSUE TITLE
Cannot connect to local DB with root credentials

### ISSUE THREAD

**Issue by rinatio** [orientechnologies/orientdb#3660]
Hello guys,

I'm trying to follow [this](https://github.com/orientechnologies/orientdb/wiki/Console-Command-Connect) wiki page and connect to local database with root username password, here's an error I get:

```
orientdb> connect plocal:/opt/orientdb/databases/GratefulDeadConcerts root

Disconnecting from the database [null]...OKEnter password:

Connecting to database [plocal:/opt/orientdb/databases/GratefulDeadConcerts] with user 'root'...
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'GratefulDeadConcerts'
```

While it works with admin/admin and it works with root credentials + remote connect.

**Comment by SDIPro** [comment]
Did you by chance leave off the root password when you tried connecting to plocal?

-Colin

**Comment by rinatio** [comment]
@SDIPro I tried both with explicit password and password prompt multiple times. Does it work for you?

**Comment by SDIPro** [comment]
The reason you cannot connect to plocal with the root credentials is that the database knows nothing about the root user.  That's a credential that's loaded from the orientdb-server-config.xml file as one of the users when the OrientDB server is started.

Hope that clears up the confusion.  :-)

-Colin

**Comment by rinatio** [comment]
@SDIPro That seems kind of confusing and inconsistent even though I understand the case. Thank you anyway.
