### ISSUE TITLE
How does one plug in a binary serializer?

### ISSUE THREAD

**Issue by russwyte** [orientechnologies/orientdb#3661]
I have created a binary Serializer based on the (somewhat out of date) info in the Index documentation.

I created a jar with the serializer - and put it (and its dependancies) in the server lib directory.

I have this code(scala) to test the index:
    OBinarySerializerFactory.getInstance().registerSerializer(new CFISerializer(), null);
    val index = db.getMetadata.getIndexManager.createIndex("cfi","UNIQUE",new ORuntimeKeyIndexDefinition[CFI](CFISerializer.ID),null,null,null)

But when I try to use it I get this:

com.orientechnologies.orient.core.exception.OConfigurationException: Runtime index definition cannot find binary serializer with id=100. Assure to plug custom serializer into the server.
	at com.orientechnologies.orient.core.index.ORuntimeKeyIndexDefinition.<init>(ORuntimeKeyIndexDefinition.java:48)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:255)
...

I am afraid I am stumped... How do I "plug it into the server?"

Sorry If I missed something in the docs - but I have spent a few hours scratching my head.

Thanks!
Russ

**Comment by tglman** [comment]
hi @russwyte,

It seems all right, the only thing i don't understand is when you register that plugin, to work correctly the plugin should  be loaded at the moment that the database is open.

Can You tell me how do you deploy the plugin?

**Comment by russwyte** [comment]
@tglman I am not confident I know the correct way to do that. Where can I find out how?

**Comment by tglman** [comment]
here is a guide on the plugins coding: http://orientdb.com/docs/last/Extend-Server.html which case did you use?

**Comment by lvca** [comment]
Closed because no answer after a while. In case please comment or reopen this.
