### ISSUE TITLE
Can't insert multiple record from query

### ISSUE THREAD

**Issue by apaichon** [orientechnologies/orientdb#3663]
Hi OrientDB Team
I try version 1.5.1 and 2.0.2. I try to insert multiple records from query like following:
1. create tmp class.
2. run command on Query Page.
   insert into tmp from (select name from OUser)
3. The output show below no any records insert to tmp class.
Query executed in 0.014 sec. Returned 0 record(s)
if i try insert by  
insert into tmp (name) values ('a'),('b'), ('c')
It work as well but i would like to insert multiple records from exist table if you have other solution please recommended.
Best Regards,
PUP

**Comment by luigidellaquila** [comment]
Hi,

just try to remove the parentheses:

insert into tmp from select name from OUser

it should work fine. These issues are being addressed in 2.1

Thanks

Luigi



2015-02-26 5:37 GMT+01:00 apaichon <notifications@github.com>:

**Comment by apaichon** [comment]
Hi Luigi
Thank a lot. From your recommend It work fine in 2.0.2
Best Regards,
PUP
