### ISSUE TITLE
orientdb.sh status exit code incorrect

### ISSUE THREAD

**Issue by mdbelt** [orientechnologies/orientdb#3665]
Greetings.  The exit code when running a status on orientdb.sh is incorrect.

Currently it's coded to exit with the PID as the return code "exit $PID".  This is causing automated deployment problems with Chef as when attempting to issue an automated start Chef first checks the status.  According to the standards doc it should be returning 0 when everything is fine & 3 when the program is not running.  Since it's returning the PID which is 0 when the service is stopped it is incorrectly notifying via the exit code that it's running.  Thus backwards.

Can this be changed for "status" to "exit 0" when the "OrientDB server daemon is running with PID...." ; and "exit 3" when the "OrientDB server daemon is NOT running" ? 

See standards spec:  http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html

See offending line:  https://github.com/orientechnologies/orientdb/blob/master/server/script/orientdb.sh#L71

**Comment by mdbelt** [comment]
For any other Chef user that's hitting this, you can get around this status bug by over-riding the default status command & flipping the exit code with grep in the Chef recipe.

'''
service 'orientdb' do
  action [:enable, :start]
  status_command '/etc/init.d/orientdb status | /bin/grep -q "is running with PID" && exit 0 || exit 3'
end
'''

**Comment by mdbelt** [comment]
In addition I would recommend the ampersand be removed from the end of the script that is run for a stop command.  With the ampersand present it is returning back control even though orientdb hasn't shutdown yet.  This could lead to machine shutdown before orientdb shutdown is complete.

See stop command script (&) at end:
https://github.com/orientechnologies/orientdb/blob/master/server/script/orientdb.sh#L36

**Comment by lvca** [comment]
Makes sense. Changed in develop branch (2.2.0-SNAPSHOT)

**Comment by lvca** [comment]
Feel free to send a PR or any other useful tips ;-)
