### ISSUE TITLE
CREATE CLASS with custom clusterid

### ISSUE THREAD

**Issue by vovagp** [orientechnologies/orientdb#3666]
OrientDB 2.0.3

create class custom-cluster-id cluster 1000

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #38: Cluster with id 1000 does not exists
Command: create class custom-cluster-id cluster 1000

**Comment by lvca** [comment]
I think the error is on the name. Is this working?

    create class custom-cluster-id cluster myClustrer1000

**Comment by vovagp** [comment]
Yes. But how can i create class with specified cluster id (1000, 123, 999, 100202 etc)?

Maybe wiki page https://github.com/orientechnologies/orientdb/wiki/SQL-Create-Class is outdated because there:

...
Create the class 'Car' with clusterId 10:
CREATE CLASS Car CLUSTER 10
...

Sorry for my english.

**Comment by giacomoParigi** [comment]
I have a similar problem, I post it here, let me know if it's useful to open a new issue on the tracker.

In my use case I've three graph databases that partially overlap. I want to be able to identify from which db a vertex come, from a class that doesn't have direct access to them, and my ideal solution would use only  the rid of the vertex to pinpoint the source db. To do that a possibility is to make the cluster ids (left part of the vertex id) of each database start from a given offset (in that way, cluster ids between given thresholds would directly identify each source db).
Is there a simple way to obtain this?

I hoped in the `<POSITION>` keyword when creating a cluster, but the parser seems to ignore it at once (I can write anything I want after the name of the newly created cluster, and no error is triggered), and I haven't found any other way to operate directly on the cluster id. The workaround I'm using is to create _n_ fake unused clusters before the actual ones, but besides being a really ugly solution, I'm not even sure how it may affect the performances of the system.

**Comment by smolinari** [comment]
Since you can give clusters names, couldn't you use a naming convention to make the overlaps? And actually, you would think you would need the naming convention at class level too, because the cluster is only a location. The class name is the actual identifier. 

Scott

**Comment by giacomoParigi** [comment]
The problem is that in several queries (i.e. when looking for paths) the result vertices are given only as rids. If I want to avoid querying each single vertex (or implementing some risky code magic based on assumed meanings of the rids...!) before going on with my procedure, I would need the rid to be a sufficient identifier. Nonetheless, I'm starting to think that the class naming convention with all the subsequent queries it is the only way to go...

Do you have any idea on the performances loss with many empty clusters?

**Comment by StarpTech** [comment]
@giacomoParigi  As far I know a cluster is created per cluster so I think it would impact the performance.
