### ISSUE TITLE
Class with non-existent cluster

### ISSUE THREAD

**Issue by vovagp** [orientechnologies/orientdb#3667]
OrientDB 2.0.3

create class custom-cluster-id             
Class created successfully. Total classes in database now: 12

alter class custom-cluster-id addcluster 1000   
Class updated successfully

browse class custom-cluster-id               
Error: com.orientechnologies.orient.core.exception.OConfigurationException: Cluster id 1000 was not found in database 'test'

**Comment by lvca** [comment]
You should create the cluster before that association.

**Comment by lvca** [comment]
Sorry, the problem must be with the name: try using a name rather a number.

**Comment by vovagp** [comment]
No. Problem with the logic: ALTER CLASS should check for the presence of a cluster in the database.

**Comment by vovagp** [comment]
Perhaps should add "if exists"

``` alter class ... addcuster if exists .... ```
