### ISSUE TITLE
empty date.

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3668]
is that possible to set date file to empty value or remove value for date field?

**Comment by luigidellaquila** [comment]
Hi @martingg88 

you can use 

UPDATE ClassName REMOVE fieldName where...

Please, do not use the issue tracker for your questions, use the mailing list instead
http://www.orientechnologies.com/active-user-community/

Regards

Luigi

**Comment by martingg88** [comment]
thanks. noted about that.
