### ISSUE TITLE
Support for rdbms like sequences [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#367]
This is [Issue 367](http://code.google.com/p/orient/issues/detail?id=367) moved from a Google Code project.
Added by 2011-05-20T05:44:14.000Z by [pieter.m...@gmail.com](http://code.google.com/u/105425430167625004620/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v2.1.0

### Original description

    Our current use case wants to use a sequence to retrieve a unique number for every new transaction.
    
    Thanks
    Pieter

**Comment by vertex-github** [comment]
+1 on this - we'd also make use of incrementing sequences, especially in our distributed platform

**Comment by mgurevin** [comment]
+1 for the idea if it will work distributed and transaction independent.

**Comment by dmarcelino** [comment]
:+1:

**Comment by lvca** [comment]
Implemented in 2.2.0-SNAPSHOT

**Comment by lvca** [comment]
Reopened to change the PR to:
- remove # as sequence prefix
- create a new SQL function `sequence(<name>)`
- create the following new SQL methods:
 - `current()`
 - `next()`
 - `reset()`

**Comment by lvca** [comment]
Done, updated docs too: http://orientdb.com/docs/last/Sequences-and-auto-increment.html

**Comment by smolinari** [comment]
That is a pretty cool feature. It is more flexible than MySQL's auto-increment column.

Thanks Luca!

Out of curiosity, how are the sequences handled internally with a distributed scenario? 

Scott

**Comment by lvca** [comment]
@smolinari we should thanks to @matanshukry for its implementation, I just adapted small things to fit better in OrientDB picture. Increments follows the OrientDB "optimistic" approach by saving the number in a document that is updated following the MVCC. In case of concurrent increment, the increment is re-executed again. All is transparent at app level.

**Comment by smolinari** [comment]
Then :+1:  to @matanshukry. 

My concern was, there should be no performance concerns with a larger distributed database, when working with sequences. If there are none, then that is simply great. This feature makes ODB fit our use case even better. 

Scott

**Comment by nagarajasr** [comment]
thanks.

could we have a new feature to implement that a property is automatically assigned a value from a sequence whenever a new record is inserted?
something similar to default values, but assigned using a sequence

```
alter property myclass.myproperty sequence sequence_id
```

**Comment by smolinari** [comment]
I'd imagine it would be best to start a new issue for that enhancement. I'd :+1:  it too.

Scott

**Comment by lvca** [comment]
:+1: for a new issue ;-)

**Comment by decibel** [comment]
My suggestion for distributed sequences would be to pre-assign a range of values to each node, though perhaps with how caching is being done that's what's actually happening?

Also, I can't tell if the sequence is being logged in WAL or not... be aware that if it isn't you can end up with values being re-used after a crash.

**Comment by lvca** [comment]
Sequences is an high level structure, so it uses the WAL
