### ISSUE TITLE
Strictmode ignored for embedded classes

### ISSUE THREAD

**Issue by micha-nerdlichter** [orientechnologies/orientdb#3672]
Hi, I do the following:
```sql
create class A
alter class A strictmode=true

create class B abstract
alter class B strictmode=true

create property A.b embedded B
```
Now I insert a record into A:
```sql
insert into A content {"invalid":"data"}
```
This fails as expected. But
```sql
insert into A content {"b": {"@type":"d", "@class":"B", "invalid":"data"}}
```
passes! I would expect OrientDB to deny this insert, as the embedded document of the strict class B has an invalid property. It only fails if b is of the wrong @class, not if the data doesn't match the B-schema. Why isn't the data validated as soon as Classes are abstract and embedded?

This can become quite a security issue as soon as I want to select A-records with a fetchplan. Consider the following:
```sql
insert into A content {"b": {"@type":"d", "@class":"B", "hack":"#5:0"}}
select from A fetchplan *:2
```

**Comment by micha-nerdlichter** [comment]
@lvca This Issue exists uncommented since 3 months now... I think this is a security problem that should be discussed. In the example I gave I can just inject any rid into A. As soon as the A-record is fetched I get the data of the injected rid along with it. ```#5:0``` for example is the default admin user.

Strictmode is supposed to prevent injected data that doesn't meet the schema. But as strictmode doesn't work for embedded classes there is no way to control what rids are injected there. This means that I can't use any embedded classes in my db or I will just open a huge security hole.

**Comment by micha-nerdlichter** [comment]
I guess a simple ```doc.validate()``` in Line 494 of https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/orient/core/record/impl/ODocument.java solves the problem.

**Comment by lvca** [comment]
You're right, a validate in that line should do the job.

**Comment by lvca** [comment]
Let me write a new test case for it.
