### ISSUE TITLE
sql batch return invalid results 

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3673]
The following query return nullPointerException. any idea?
I believe some data in this class make it return null pointer exception. 

how can i send you guys a dummy data for your debug?

BEGIN
 LET interest = SELECT * FROM interest ORDER BY (title ASC)
COMMIT
RETURN [$interest]

**Comment by StarpTech** [comment]
Hi
1. How do you send this data?  (Java, Binary, REST) ?
2. Which orientdb version are you using?

**Comment by martingg88** [comment]
i have tried this at both console.bat and rest. both of them can't work as well. 
FYI. i'm using latest version 2.0.3. i guess my data will cause this issue. Should i send you my schema for your debug?

**Comment by martingg88** [comment]
i still have the issue after tested with 2.0.4 version. 
FYI ..i will only work without array bracket.

A. Working Fine
-----------------------------------------
BEGIN
LET interest = SELECT * FROM interest ORDER BY (title ASC)
COMMIT
RETURN $interest

B. No working
---------------------------------------------------
BEGIN
LET interest = SELECT * FROM interest ORDER BY (title ASC)
COMMIT
RETURN [$interest]

**Comment by lvca** [comment]
Tested and works. Created a function test():
```
BEGIN
LET interest = SELECT * FROM OUser ORDER BY name ASC
COMMIT
RETURN [$interest]
```

Then I've executed it from SQL:

```sql
select test()
```
Result:

```json
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:1",
            "@version": 0,
            "test": [
                [
                    "#5:0",
                    "#5:1",
                    "#5:2"
                ]
            ],
            "@fieldTypes": "null=z"
        }
    ],
    "notification": "Query executed in 0.123 sec. Returned 1 record(s)"
}
```

**Comment by martingg88** [comment]
this is what i have at my end. any idea?

Cannot serialize record: com.orientechnologies.orient.core.sql.query.OResultSet@dc8ffcfd [ONetworkProtocolBinary]
