### ISSUE TITLE
Wiki Download page / update latest snapshot versions + dependency inconsistencies in Sonatype

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#3674]
Hello! Please update latest snapshot versions that exist on Sonatype (since the listed ones are not there anymore https://github.com/orientechnologies/orientdb/wiki/Download). 
First of all blueprints-orient-graph shouldn't be here ...since it is only for versions <1.7 (as stated here: https://github.com/orientechnologies/orientdb/wiki/Graph-Database-Tinkerpop). Secondly I had to remove orient-commons. I am not sure about that. I also had to add another repository to get blueprint-core version 2.6 that is used from the new orientdb-graphdb 2.1.SNAPHSHOT. This version is not available in SonaType obviously since it is a release https://oss.sonatype.org/content/repositories/snapshots/com/tinkerpop/blueprints/blueprints-core/
This is my final dependencies list that made it work:

```xml

 	<repositories>
	    <repository>
	        <id>sonatype-nexus-snapshots</id>
	        <name>Sonatype Nexus Snapshots</name>
	        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
	    </repository>
	    <repository>
	    	<id>mvn-repository-com-artifacts</id>
	    	<name>mvnrepository.com</name>
	    	<url>http://mvnrepository.com/artifact/</url>
	    </repository>
	</repositories>
	<dependencies>
        <dependency>
		  <groupId>com.tinkerpop.blueprints</groupId>
		  <artifactId>blueprints-core</artifactId>
		  <version>2.6.0</version>
		  <type>bundle</type>
		</dependency>
		<dependency>
		  <groupId>com.orientechnologies</groupId>
		  <artifactId>orientdb-core</artifactId>
		  <version>2.1-SNAPSHOT</version>
		  <type>bundle</type>
		</dependency>
		<dependency>
		  <groupId>com.orientechnologies</groupId>
		  <artifactId>orientdb-client</artifactId>
		  <version>2.1-SNAPSHOT</version>
		  <type>bundle</type>
		</dependency>
		<dependency>
		  <groupId>com.orientechnologies</groupId>
		  <artifactId>orientdb-enterprise</artifactId>
		  <version>2.1-SNAPSHOT</version>
		  <type>bundle</type>
		</dependency>
		<dependency>
		  <groupId>com.orientechnologies</groupId>
		  <artifactId>orientdb-graphdb</artifactId>
		  <version>2.1-SNAPSHOT</version>
		  <type>bundle</type>
		</dependency>
	</dependencies>
```

Thank you,
Michail

**Comment by lvca** [comment]
How did you arrive to that page?

**Comment by zifnab87** [comment]
https://github.com/orientechnologies/orientdb/wiki --> there is a link Download at the bottom. Google got me to wiki

**Comment by lvca** [comment]
I can't find it. Could you attach a screenshot please?

**Comment by lvca** [comment]
Nevermind: found it and fixed. Thanks.
