### ISSUE TITLE
SELECT with 'LUCENE or LIKE' returns wrong results

### ISSUE THREAD

**Issue by orangemug** [orientechnologies/orientdb#3683]
A very odd query parser problem, given the following query in my test database with 9 rows

    SELECT username,firstName,lastName FROM User WHERE [firstName, lastName] LUCENE "Bob Burn" LIMIT 20

Returns

    username422765dd  Bob Burns
    usernamef05c2ea6  Bob Burns
    username95fe49b3  Bob Burns
    usernameb3590d7f  Bob Burnquist
    username3c668fde  Bob Burnquist
    username9e3e9ba8  Bob Burnquist

And using a `LIKE` on username

    SELECT username, firstName, lastName FROM User WHERE username LIKE "foo%" LIMIT 20

Returns **zero** rows. Great works so far now lets compose the 2 queries

    SELECT username, firstName, lastName FROM User WHERE [firstName, lastName] LUCENE "Bob Burn" OR username LIKE "foo%" LIMIT 20

This returns all rows in the table, including rows that don't match either part of the where clause, for example

    username172ed6f0  Homer Last 915f0eeb

Do you have any idea whats going on here? This was tested in v2.0.2

**Comment by luigidellaquila** [comment]
Hi @orangemug 

This issue was fixed long time ago, I'm closing this. 
Please reopen if you see any other problems

Thanks

Luigi
