### ISSUE TITLE
OrientDB ORecordHookAbstract is firing onRecordAfterRead twice if no index is present

### ISSUE THREAD

**Issue by ardias** [orientechnologies/orientdb#3684]
I'm using the hook functionality in OrientDB to implement encryption of some document fields "transparently" to the caller. Basically the process is:

1 : when onRecordBeforeCreate or onRecordBeforeUpdate event fires we apply encryption to some data fields and change the document before is created or updated

    byte[] data = doc.field("data");
    byte[] encrypted = encrypt(data);
    doc.field("data", encrypted);

2 : when onRecordAfterRead fires we get the encrypted data from the document fields, decrypt them, and change the document fields again with the decrypted data.

    byte[] encrypted = doc.field("data");
    byte[] decrypted = decrypt(encrypted);
    doc.field("data", decrypted);

The problem is that the event onRecordAfterRead is firing twice and in the first time the data decrypts correctly (because is encrypted) but on the second time the decryption fails because we already had decrypted it, and so the document "load" fails.

It happens if the query that i execute to load the document uses some field of the document in the filter (where clause). So for example, the following query does not trigger the problem:

    select count from Data;

but the following query triggers the problem:

    select from Data where status ="processed";

This is because i don't have an index on the status field. If i add an index then it fires the event only once. So this is related with the use or not of the indexes. Should the events be fired if OrientDB is "scanning" the documents when executing a query? Shouldn't it only fire when the matching documents are in fact loaded? Is there a way around this?

It's very easy to reproduce: Create a database, register a hook, save a document, and query the database by some field with an index and a fields without an index. You will notice that onRecordAfterRead will be raised once for the query with the index and twice for the query without the index

**Comment by ardias** [comment]
You can check a sample that reproduces the bug here: https://github.com/ardias/snippets

**Comment by tglman** [comment]
fixed there was a wrong call.

**Comment by lvca** [comment]
Great.

**Comment by lvca** [comment]
Can you back port it in 2.0.5?

**Comment by ardias** [comment]
Thanks! It would be really great if you could port it back 2.0.x

**Comment by tglman** [comment]
ported.

**Comment by ardias** [comment]
Tks, that's great!
