### ISSUE TITLE
server.database.path not being used

### ISSUE THREAD

**Issue by puggimer** [orientechnologies/orientdb#3685]
I have seen where this issue is supposed to be resolved, yet is it still occurring for me.

I'm running an embedded server in Windows 7 using Eclipse Luna 1a(4.4.1) / Java 1.7
Please correct me if there is something I'm missing.
The code is fairly simple:

OServer server = OServerMain.create();
server.startup(configFileStream);
server.activate();
ODatabaseDocumentTx db = new ODatabaseDocumentTx("plocal" + dbName);
db.create();

dbName is a string - the configFileStream is an InputStream.  The database is created in the directory where the process has been started.

My log shows:
Mar 03, 2015 11:00:25 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=1,079MB (heap=894MB os=4,021MB disk=37,062MB)
Mar 03, 2015 11:00:25 AM com.orientechnologies.common.log.OLogManager log
INFO: Loading configuration from input stream

server.database.path : C:/workspace/SMS_SERVER/com.tdkc.statemodel.OrientDB/databases/

2015-03-03 11:00:26:140 INFO  OrientDB Server v2.1-SNAPSHOT is starting up... [OServer]
2015-03-03 11:00:26:162 INFO  Databases directory: C:\workspace\SMS_SERVER\com.tdkc.statemodel.OrientDB\databases [OServer]

so the log shows the correct location based on the server.database.path set in the orientdb-server-config.xml file that is being passed in to the server.startup() method.

ORIENTDB_HOME is not set, but even when I set it as a system property it does not change anything.

**Comment by tglman** [comment]
hi @puggimer 

this:
ODatabaseDocumentTx db = new ODatabaseDocumentTx("plocal" + dbName);
db.create();

create the database in local not on the running server.
you should use OServerAdmin for create the database to the server have a look to :
http://www.orientechnologies.com/docs/last/orientdb.wiki/Server-Management-Java.html

closing this issue is invalid

**Comment by puggimer** [comment]
Thanks.  Very counter-intuitive to have to use a remote connection to an embedded server.

When would you use the ODatabaseDocumentTx.create() method - if you need to create it via the OServerAdmin then why does this method exist?

I am finding the documentation very lacking, even after reading Tesoriero's book ( https://www.packtpub.com/big-data-and-business-intelligence/getting-started-orientdb ) (which I thought was going to help).

**Comment by lvca** [comment]
After the db has been created, you can access to it using "plocal:" as well. It's just the first creation of DB the "problematic" part.

**Comment by puggimer** [comment]
The only way I have been able to access it via "plocal" is to give it the entire path to the database - which kind of defeats the purpose of setting server.database.path in the first place.

**Comment by lvca** [comment]
You can use env variables in path. Example:

"plocal:${ORIENTDB_HOME}/databases/test"
