### ISSUE TITLE
Unable to see asynchronous replication working

### ISSUE THREAD

**Issue by somedeveloper2015** [orientechnologies/orientdb#3691]
I'm currently using release 2.0.3 and have a distributed setup comprised of 2 nodes where both nodes have the same configuration.

When executionMode in default-distributed-db-config.json is specified as 'asynchronous', vertexes and edges are not being replicated on insertion when using the gremlin console.

I did not face the same problem however performing inserts using SQL through the OrientDb web browser because it appears to distribute the data synchronously despite the asynchronous setting.

To reproduce
1. Create the following classes and properties in non-distributed mode by running server.bat

create class One extends v
create class Two extends v
create property One.k string
create property One.v string
create property Two.k string
create property Two.v string

2. Stop the server then copy the database to another server (i.e., to ..\serverInstall\databases)
3. Make sure executionMode in default-distributed-db-config.json is set to 'asynchronous'
4. Start up 2 nodes in distributed mode by running dserver.bat from each OrientDb bin folder
5. Launch gremlin.bat (console) and issue the following commands
g = new OrientGraph("remote:localhost/Test1", "user", "password")
g.addVertex("class:One", "key", "k1", "name", "name1")
g.addVertex("class:Two", "key", "k2", "name", "name2")
g.commit()

If you type g.V, nothing will be printed.  Additionally, if you open the OrientDb web browsers on localhost:2480 and 2481 and execute 'select from v', you will only see results on the 2nd node (port 2481) and not the first (port 2480).

Replication otherwise works using gremlin when executionMode is set to 'undefined' which should default to synchronous based on OrientDb's documentation.

If asynchronous replication works, can you please share a working example?

**Comment by somedeveloper2015** [comment]
Hi - just following up; please let me know if there's any more info you need from me.  

Getting an asynchronous replication setup is very much desired so your feedback is much appreciated.

The contents of the default-distributed-db-config.json are:

{
    "autoDeploy": true,
    "hotAlignment": false,
    "executionMode": "asynchronous",
    "readQuorum": 1,
    "writeQuorum": 2,
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "*": {
            "servers" : [ "<NEW_NODE>" ]
        }
    }
}

**Comment by tobiemh** [comment]
Yes I've found the same with this. The records are added to all of the other database nodes in a 5-node cluster except for the one on which the query was executed.

Just out of interest have you tried removing `"executionMode": "asynchronous"` and setting `"writeQuorum": 1`? Although I'm not sure if this achieves what you are trying to do...

**Comment by lvca** [comment]
@somedeveloper2015 Could you please upgrade to 2.0.5? I guess your problem is not `asynchronous` but an issue we fixed days ago.

**Comment by tobiemh** [comment]
I can confirm with OrientDB-2.0.5 that when using `"executionMode": "asynchronous"` the record is added to all of the nodes in the cluster except for the one on which the query was executed. In addition no errors occur on any of the nodes in the cluster.

Simple test:

1st node:
```sql
CONNECT remote:172.17.8.101/testdatabase root root

CREATE VERTEX Person SET fullname = 'Joe Bloggs'
# Created vertex 'Person#25:-2{fullname:Joe Bloggs} v0' in 0.003000 sec(s).

SELECT FROM Person
# 0 item(s) found. Query executed in 0.002 sec(s).
```

2nd node:
```sql
CONNECT remote:172.17.8.102/testdatabase root root
SELECT FROM Person

----+-----+------+----------
#   |@RID |@CLASS|fullname  
----+-----+------+----------
0   |#25:0|Person|Joe Bloggs
----+-----+------+----------

1 item(s) found. Query executed in 0.005 sec(s).
```

3rd node:
```sql
CONNECT remote:172.17.8.103/testdatabase root root
SELECT FROM Person

----+-----+------+----------
#   |@RID |@CLASS|fullname  
----+-----+------+----------
0   |#25:0|Person|Joe Bloggs
----+-----+------+----------

1 item(s) found. Query executed in 0.005 sec(s).
```

***

OrientDB version: 2.0.5

**Comment by lvca** [comment]
Reproduced

**Comment by lvca** [comment]
Found the problem, testing the fix now...

**Comment by lvca** [comment]
Porting also to 2.1-SNAPSHOT (develop branch)...

**Comment by lvca** [comment]
Done
