### ISSUE TITLE
Is it possible to have the package org.xerial.snappy as optional in OrientDB Core ?

### ISSUE THREAD

**Issue by barjo** [orientechnologies/orientdb#3693]
So the bundle won't require org.xerial.snappy when deployed (on osgi). 

```
org.xerial.snappy;resolution:=optional,
```

**Comment by lvca** [comment]
It should be optional, because it's not used by default. Please could you fork OrientDB, fix the OSGi file in "develop" branch and send us a Pull Request against "develop" branch?

**Comment by barjo** [comment]
:+1: Thanks, I create the pull request -> #3694
