### ISSUE TITLE
EXPLAIN gives odd results with sub query

### ISSUE THREAD

**Issue by orangemug** [orientechnologies/orientdb#3695]
Given the query

    EXPLAIN select from (select from Vertex) LIMIT 1

I get the results

    elapsed: 2514.5999
    recordReads: 1
    documentReads: 1
    resultSize: 1
    evaluated: 1

Given the query took `2.5seconds` I would have expected some of those numbers to be a lot higher (recordReads, documentReads, resultSize, evaluated)

**Comment by lvca** [comment]
This is more a question than an issue. Please post in Community Group where more than 2k users can answer to your question.

**Comment by orangemug** [comment]
@lvca I saw it more as a bug / feature request, but I'll raise it in the forum. Out of interest would the orientdb team prefer all issues / feature request to go via the forum first, and is there a doc explaining what to raise where for newbies?

**Comment by orangemug** [comment]
Raised for discussion in forum https://groups.google.com/forum/#!topic/orient-database/BSuiP8a9nqQ
