### ISSUE TITLE
Please add an upsert flag to document api's save method

### ISSUE THREAD

**Issue by KIC** [orientechnologies/orientdb#3697]
I am migrating from mongodb and one of its best features is that mongodb.save() allows you to upsert  documents on existing duplicate keys. Since you already have the merge(document, boolean updateOnly, boolean deepMerge) you could easily add a save method with the same flags - i.e. save(document, boolean updateOnly, boolean deepMerge) right before throwing the duplicate key exception.

This would be a very great improvement!

Today you only can:
a)
1 catch the exception by an error message (which is bad anyway - building logic on top of error stings)
2 load the existing object
3 merge the new object
4 save

or if you expect more updates than inserts b)
1 figure out the unique index (which is not easy in a generic way!)
2 get the index by index manager
3 insert if null
4 load the document by identifiable 
5 merge new document
6 save

c) 
using sql language which is absolutely not preferable when working with the document api

All of this is whether a nice way of doing upserts nor a performance booster. So a mongo like save upsert = true feature is a really missing one.

**Comment by lvca** [comment]
:+1:
