### ISSUE TITLE
ORecordDuplicatedException: 2 Node Distributed

### ISSUE THREAD

**Issue by jamesecahill** [orientechnologies/orientdb#3698]
I have a 2 node orient distributed setup with the following default distributed settings:
```
{
    "autoDeploy": true,
    "hotAlignment": false,
    "executionMode": "asynchronous",
    "readQuorum": 1,
    "writeQuorum": 2,
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "*": {
            "servers" : [ "<NEW_NODE>" ]
        }
    }
}
```

I'm using the tinkerpop API to create the database on node1. After it's created, I'm inserting _TONS_ of records very quickly from multiple threads. No errors are returned from the API, but on the second node a bunch of ```com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #16:379: found duplicated key '<redacted>' in index 'Address.email' previously assigned to the record #16:65 RID=#16:65```  are being logged. Also, no data is being committed to node1... 

Is it possible to do mass parallel insertion into a distributed environment like this? 

For reference, here is a sample of how I'm inserting items:

```
for (int i = 0; i < MAX_TX_RETRIES; i++) {
    try {
        g.begin();
        Vertex thread;
        thread = g.getVertexByKey("Thread.messageId", threadMsgId);
        if (thread == null) {
            thread = g.addVertex("class:Thread");
            thread.setProperty("messageId", threadMsgId);
        }
        g.addEdge(null, msg, thread, "threaded_by");
        g.commit();
        break;
    } catch (ONeedRetryException | ORecordDuplicatedException | ODatabaseException ex) {
        g.rollback();
        if (i == MAX_TX_RETRIES - 1) {
            System.err.println("Hit MAX_TX_RETRIES");
            throw ex;
        }
    }
}
```

**Comment by lvca** [comment]
Which release? Please try with a recent version, namely 2.0.15, 2.1.2 or 2.2.0-SNAPSHOT.

**Comment by jamesecahill** [comment]
Hi @lvca. I gave up on working with it a while back. This was found using version 2.0.3. If I have a chance, I'll retry using something later, but I doubt I'll get around to it. Thanks for the response!

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
