### ISSUE TITLE
Clicking on the orientdb logo/home link in the studio closes the connection without confirmation

### ISSUE THREAD

**Issue by krichter722** [orientechnologies/orientdb#3702]
Hitting the back button in the browser is not authorized (HTTP 401 error). Regarding the fact that the authorization is dropped as well, closing the connection should be confirmed. It'd also be nice to get an explicit feedback that the connection was closed properly and that the server is still running (and didn't crash like one might think with the current inexisting feedback) (in doubt add a red/green running/not running label at the top right corner).

experienced in 2.0.4 in Firefox 36.0.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
