### ISSUE TITLE
OrientElementIterator throws NPE (orient 2.0)

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3707]
In a large project, we call OrientElement.getProperty("field1") to get a field that is an embedded-list containing 2 vertices (as shown by studio), which returns an OrientElementIterable.  When next() is called on that, we end up in an instance OrientElementIterator with graph set to null, so this line throws an NPE:
```
if (ODocumentInternal.getImmutableSchemaClass(currentDocument).isSubClassOf(graph.getEdgeBaseType()))
```

**Comment by 8forty** [comment]
There is a related bug in OrientElement.getProperty(final String key) -- if the element.graph is null, an exception is thrown on this line:
```
return (T) graph.getElement(fieldValue);
```

**Comment by lvca** [comment]
I can put a check there. In your case are you using detached elements? Why the graph instance is null?

**Comment by 8forty** [comment]
Yes they are "automatically" detached.

**Comment by laa** [comment]
Hi,
Small warning, if you use internal API you have no guarantee that contract of this API will stay the same in next version of database.

**Comment by vitorenesduarte** [comment]
@laa what do you mean?

**Comment by 8forty** [comment]
@lvca your changes did not prevent the NPE in OrientElementIterator, so I recommend re-opening the issue.  Here's the stack on where the NPE is about to be thrown since the graph in the OrientElementIterator is null:
```
OrientElementIterator<T>.next() line: 73	
OrientElementIterator<T>.next() line: 34	
OdbVertexElement(OdbElement).getField(String) line: 289	
...
```
My OdbVertexElement.getField() function has just used OrientVertex.getProperty() to get an OrientElementIterable of a LINKLIST field, then tried to loop over the property value which called OrientElementIterator.next().  So your changes to OrientElement don't help to prevent the NPE here.

**Comment by 8forty** [comment]
@laa note that I'm not using any internal API, just trying to iterate over a LINKLIST property (which is returned as an OrientElementIterable)

**Comment by lvca** [comment]
Checked if graph == null. Note that in this case the graph element can't be retrieved, but you rather should re-attach it.

**Comment by 8forty** [comment]
@lvca that doesn't seem right, I'm using the automatic attach/detach mode as documented in this [forum post](https://groups.google.com/forum/?fromgroups#!searchin/orient-database/detach%7Csort:date/orient-database/O8b_dOLwpB0/80bU0gqJcQ0J) where it's stated that I never need to attach/detach.

**Comment by 8forty** [comment]
Should I create another issue to track the automatic attach/detach mode problem?

**Comment by lvca** [comment]
@8forty yes, please. In this way we can be more effective. Thanks.
