### ISSUE TITLE
Code style rules and checkstyle plugin setup

### ISSUE THREAD

**Issue by krichter722** [orientechnologies/orientdb#3708]
I was thinking about contributing code to the project, but quickly became a worried about that going as easy as it could be by the lack of code style rules. What do you think about:

  * enforcing a line feed like `git config core.autocrlf true` does?
  * minimizing java compiler warnings
  * Indentation (currently not enforced which might even cause merge difficulties one day)
  * setting up the maven-checkstyle-plugin (which implies the former points)

and summarizing all that in a `CONTRIBUTING` file and give it some time to get in place.

**Comment by lvca** [comment]
Actually all the committers use the rules in:

`_base/ide/eclipse-formatter.xml`

**Comment by krichter722** [comment]
That doesn't handle one of my points. `git config core.autocrlf true` doesn't seem to be generally right, forcing in `.gitattributes` (as suggested in [a stackoverflow.com question][1]) seems best.

Run `grep -r -I '\\t' .` in the source root to see that indentation isn't handled correctly (and fixing that shouldn't occur in a IDE-dependent file, but in the checkstyle plugin as suggested).

[1]:http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git
