### ISSUE TITLE
Support OrientDB in Microsoft Azure

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3714]

**Comment by jiujiu1123** [comment]
That would be amazing.

**Comment by PhantomYdn** [comment]
@lvca , Yes - that will be cool! Can you also work with Heroku to have OrientDB in their DB stack?

**Comment by mikestaub** [comment]
@Ivca I second Phantom's suggestion

**Comment by lvca** [comment]
Can I host OrientDB servers under Heroku or do they need an external access?

**Comment by PhantomYdn** [comment]
As I know: no need in external access - that's hosted on their servers. But there is almost no information how to become one of supported DBs.

**Comment by mikestaub** [comment]
https://addons.heroku.com/provider

**Comment by SDIPro** [comment]
Release 2.0.10 to the Azure Marketplace.
