### ISSUE TITLE
new parser missing syntax

### ISSUE THREAD

**Issue by danrub** [orientechnologies/orientdb#3718]
When using the new parser and the database has the custom property strictSql=true,
the SQL parser failing when FROM clause contains path syntax (as specified by documentation).

example1:

SELECT $e 
FROM [#1:1,#1:2]
LET $e = (SELECT FROM $current.prop1)

example2:

SELECT $e 
FROM [#1:1,#1:2]
let $e = (SELECT
             FROM (SELECT FROM $parent.$current))

tested on development branch fea808f9b93728cf2756fe65f5477820d4cec9d3 (3/2/2015 3:04:29 PM)

**Comment by luigidellaquila** [comment]
fixed in 2.1 SNAPSHOT
