### ISSUE TITLE
Create a Java EE studio frontend

### ISSUE THREAD

**Issue by krichter722** [orientechnologies/orientdb#3728]
I just dived into the code a little and was wondering how easy it would be to write a studio frontend using Java EE technology, e.g. Java Server Faces (JSF) for the web pages and profit from maximal code reusage in EJBs in the backend. I got started with a list of necessary changes:

  * abstracting some client classes into interfaces and implementations and reflecting that by splitting in different maven subprojects (for EJB packaging) (e.g. orientdb-client)
  * adding some default constructors and abstract some initialization routines and enforcing encapsulation (no more `protected` fields)
  * creating a studio project under the parent maven project with a jar, web and ejb project and an ear to test on Java EE server)
  * most of the angularjs code can be converted into JSF and backing beans easily. Everything would look extremely ugly for quite some time, the funtionality could be reestablished quickly
  * I saw that there're almost no test cases in the studio, so no work lost there, but quite some ahead

There's no need to do something fancy regarding distributed EJBs as everything regarding distribution is already there. EJBs would just allow code reusage and the web frontend to profit from already present methods in EJBs which can be used in JSF backing beans.

Thoughts?!?

**Comment by PhantomYdn** [comment]
I recommend to check my project: https://github.com/PhantomYdn/Orienteer
I would not recommend to use EJB with mix of NoSQL DB... There are several corner points - main differencies between RDBM and OrientDB. And the last lead to not some sideeffects in case of EJB.

**Comment by krichter722** [comment]
I'm not familiar with wicket, but it seems absolutely possible to learn and then contribute to your project which seems to cover the main aspect of code reusage already very well. Thanks for the pointer and the warning of the corner points; details could be discussed in your project. If there's every a need for a J2EE-based studio it should derive from Orienteer.

**Comment by PhantomYdn** [comment]
Sure! Link to the mentioned issue for a history: https://github.com/PhantomYdn/Orienteer/issues/130
