### ISSUE TITLE
"commit retry 100" seems to always cause repeated execution

### ISSUE THREAD

**Issue by thenesk** [orientechnologies/orientdb#3730]
The "retry" operation in SQL batch mode is causing repeated statement execution even though the statements in the batch worked the first time.  The following example in python uses `commit retry 100` and results in the statements executing 101 times:

```python
import requests

url='http://127.0.0.1:2480/batch/mydb'
user = 'admin'
pswd = 'admin'

data = """{
    "transaction" : false,
    "operations" : [
    {
    "type" : "script",
    "language" : "sql",
    "script" : [ "begin;",
    "let a = create vertex set script = true;",
    "let b = select from v limit 1;",
    "let e = create edge from $a to $b;",
    "commit retry 100;" ]
    }
    ]
    }"""
    
r = requests.post(url, data=data, auth=(user,pswd))
```

I would only expect the above code to insert one vector and one edge, but looking at my database I see 101 additional vectors and 101 additional edges.

**Comment by lvca** [comment]
Already fixed in 2.0.5-SNAPSHOT

**Comment by lvca** [comment]
As workaround use the RETURN statement at the end.

**Comment by thenesk** [comment]
ok, thanks!  In the mean time I'll try out the workaround.
