### ISSUE TITLE
NullPointerException in OObjectProxyMethodHandler.getDocFieldValue

### ISSUE THREAD

**Issue by aheintz** [orientechnologies/orientdb#3731]
After upgrading from 1.7.10 to 2.0.4 I experience a few issues with OrientDB using the Object Database.

In addition to #3604, I get a NullPointerException in OObjectProxyMethodHandler.getDocFieldValue(final Object self, final String fieldName). The "null" is that ODocument.getSchemaClass() returns null.

The error is consistent in my application when I have a new clean database, but I haven't had the time to reproduce it in a test case. Here's what I've deduced from debugging the app.

My scenario (I'm aware it's a bit unorthodox, but I still think it should work).
- I use multiple databases, one database per customer for easy separation of data.
- Users are stored in a common database with a reference to that user's customer database name

The process:
1. Read the user object from the common database. 
2. Opens the customer database (where there are no, and shouldn't be any such User objects as in the common database).
3. Creates a new Object using information from the User object loaded from the common database.
4. Results in a NullPointerException when invoking a get method on the common User object, probably due to the fact that there are no User objects in the customer-specific database. The class is a registered entity though.

One workaround that's probably possible is to read the properties from the common User object before opening the customer database.

**Comment by aheintz** [comment]
After applying my workaround I got the same NPE when a field of my object is embedded (i.e. never present as a record of its own in the database). Looking at ODocument.getSchemaClass(), it's obvious that that method can return null and therefore I added a null check to handle this and it seems to work. Haven't had the time to get a get  together to reproduce it though...

My change:
```java
--- a/object/src/main/java/com/orientechnologies/orient/object/enhancement/OObjectProxyMethodHandler.java
+++ b/object/src/main/java/com/orientechnologies/orient/object/enhancement/OObjectProxyMethodHandler.java
@@ -359,7 +359,8 @@ public class OObjectProxyMethodHandler implements MethodHandler {
   }
 
   protected Object getDocFieldValue(final Object self, final String fieldName) {
-    if (doc.getSchemaClass().existsProperty(fieldName))
+    OClass schemaClass = doc.getSchemaClass();
+    if (schemaClass != null && schemaClass.existsProperty(fieldName))
       return doc.field(fieldName);
     else {
       OType expected = OObjectEntitySerializer.getTypeByClass(self.getClass(), fieldName);
```

**Comment by lvca** [comment]
Thanks for the contribution. Next time you could also send a Pull Request ;-)

**Comment by aheintz** [comment]
Will do, thanks!
