### ISSUE TITLE
snapshot 2.1 bug?: collate ci doesn't work with create index

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#3733]
Edit: (it is no longer a question but possibly a bug ?)
Similar to #3475
While this works:
```create index Entity.text on Entity (text) fulltext;```
this doesn't:
```create index Entity.text on Entity (text collate ci) fulltext;```

The error (in Studio): 
```java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OClass.INDEX_TYPE.FULLTEXT;```

I am using SNAPSHOT 2.1

-------------------
(Old)
I wonder if it is possible to set the fulltext indexing to automatically convert to lowercase the text about to be indexed. Alternatively I could have another property on my verticies that will be converted to lowercase. Thanks

**Comment by PhantomYdn** [comment]
You should just specify collate=ci ("ci" means "case insensitive").

**Comment by zifnab87** [comment]
Thank you!

**Comment by zifnab87** [comment]
While this works:
create index Entity.text on Entity (text) fulltext;
this doesn't:
create index Entity.text on Entity (text collate ci) fulltext;

The error (in Studio): java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OClass.INDEX_TYPE.FULLTEXT;

**Comment by tglman** [comment]
you can set the collate on the property using alter : http://orientdb.com/docs/last/SQL-Alter-Property.html, that's the only way to set the collate on the index today
