### ISSUE TITLE
subquery LET clause is never executed

### ISSUE THREAD

**Issue by danrub** [orientechnologies/orientdb#3735]
When using let inside sub-query, the let command is never executed.

example:

CREATE class Test extends V
CREATE class Test2 extends V

let $a = CREATE Vertex Test
let $b = CREATE Vertex Test2

CREATE EDGE E FROM $a TO $b

SELECT $sq, $v FROM Test
LET $sq = (SELECT @rid, $v2 FROM $current.out
                   LET $v2 = eval('1 + 1')
                   ),
$v = eval('2 + 2')
LIMIT 10

expected behavior: $sq will return for each row 2 columns: @rid, $v2 (equals 2)
actual behavior: $sq returns row with @rid column only

**Comment by lvca** [comment]
I think the problem here is the CR+LF: put the LET on one line and try again.

**Comment by danrub** [comment]
I have traced the parsing logic, it is working fine. LET command is parsed as expected.
It seems that assignLetClauses method never called due to some optimization logic at OCommandExecutorSQLSelect line 428.

I'm guessing the logic trying execute the LET command once and cache it, but when it inside sub query the target parameter is not null already, so the inside subquery fail to execute it again

can you please take a look at it. 
Thanks

**Comment by luigidellaquila** [comment]
Hi @danrub 

I tried it in 2.1 snapshot and I had some trouble understanding the situation.

This query:

```sql
SELECT @rid, $sq.@rid, $v FROM Test
LET $sq = (SELECT $foo as foo FROM $parent.$current let $foo = eval("1 + 1")
	),
$v = eval('2 + 2')
LIMIT 10
```
works fine, the ```eval("1 + 1")``` is correctly evaluated and returned to the parent query. This makes me think that it's not a matter of LET evaluation in the subqueries.

Actually I don't understand exactly what you want to achieve with your query, but ```select from  $current.out``` does not make any sense. At most you can do ```select from $parent.$current``` that refers to current record in the outer query.

If that is the only problem, maybe I can close this issue. Please let me know
