### ISSUE TITLE
Problem with dropping class in distributed mode

### ISSUE THREAD

**Issue by tobiemh** [orientechnologies/orientdb#3747]
After dropping, and recreating, a class in a database in distributed mode, the new class clusters do not synchronise across to the other nodes.

```sql
CONNECT remote:172.17.8.105/testdatabase root root
CREATE CLASS Person extends V
DROP CLASS Person
CREATE CLASS Person extends V
```

Console output:

```shell
Class created successfully. Total classes in database now: 12
Removed class in 0.111000 sec(s).
Class created successfully. Total classes in database now: 12
```

After the first time the class is created:
![screen shot 2015-03-10 at 23 06 31](https://cloud.githubusercontent.com/assets/1588290/6587311/89e3de0e-c77a-11e4-9528-65b20fa6a64c.png)

After the class is dropped and recreated:
![screen shot 2015-03-10 at 23 07 36](https://cloud.githubusercontent.com/assets/1588290/6587314/960d89e6-c77a-11e4-9db4-efd44691c562.png)

This is the same on all nodes in the cluster.

NOTE: This is the same using the Console, Binary or Studio

***

OrientDB version: 2.0.3 and 2.0.4

**Comment by lvca** [comment]
This is not an issue: once class has been removed, additional clusters should be added manually. It only get the first one because the convention on names between class <-> cluster. Do you need to drop classes at run-time or was it only a test? In case you need it, could you call addCluster() with all the clusters you know (server name)?

**Comment by tobiemh** [comment]
Yeah there isn't really a need for it in production - I was just using DROP CLASS for running tests across the database, but it's not required, so I'm just using DROP DATABASE instead to start from scratch for tests.
