### ISSUE TITLE
expand function ignores other projections

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3755]
Hi,
```sql
SELECT expand(in('Accounts'))
FROM (
   SELECT FROM Account WHERE type = 'Facebook' AND accountId IN [1]
)

SELECT accountId
FROM (
   SELECT FROM Account WHERE type = 'Facebook' AND accountId IN [1]
)
```
The queries above work great, but when I want both projections I doesn't seem to work.
When combined:
```sql
SELECT accountId, expand(in('Accounts'))
FROM (
   SELECT FROM Account WHERE type = 'Facebook' AND accountId IN [1]
)
# accountId is ignored

SELECT expand(in('Accounts')), accountId
FROM (
   SELECT FROM Account WHERE type = 'Facebook' AND accountId IN [1]
)
# com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Projection not allowed with FLATTEN() and EXPAND() operators
```

The projection __is ignored / not supported__ or am I doing something wrong?

If I define [a function](https://cloud.githubusercontent.com/assets/4520516/6601126/bcbbd804-c80b-11e4-9320-2549a6a56a54.png) and then:

```sql
SELECT id, someFun(type)
FROM (
   SELECT FROM Account WHERE type = 'Facebook' AND id IN [1]
)
```
it [works great](https://cloud.githubusercontent.com/assets/4520516/6601153/e27a200a-c80b-11e4-88d8-68695654e3e5.png)! Somehow, __expand__ function is different.

**Comment by gibrit** [comment]
any news? .. when this will be fixed ? :(

**Comment by ashcrok** [comment]
still bugged ? or any workarounds ?

**Comment by tetotechy** [comment]
have a look at [my answer on SO] (http://stackoverflow.com/a/29538215/2010597) to [@vitorenesduarte's question](http://stackoverflow.com/questions/28534120/orientdb-sql-query-to-select-edge-and-vertex-fields-property)

**Comment by martingg88** [comment]
any update about his bug?
will have the issue for following query. 

"release_date" field which is link data type will be ignored in result set if * is applied in query. 

select *, story.release_date as release_date from resource
order by release_date DESC, ctime DESC

**Comment by luigidellaquila** [comment]
Hi guys,

the expand() function is a very particular one and it cannot be easily refactored.
In OrientDB 2.1 we defined a new keyword called UNWIND that does exactly what you expected from the expand function. Here you can find all the details

http://orientdb.com/docs/last/SQL-Query.html#unwind

I'm closing this issue, as UNWIND is supposed to replace expand() in this use case
Luigi

**Comment by cegprakash** [comment]
Unwind does not work.. I'm trying

`select first_name, expand(all) from (select first_name, out('has_physical_property') as all from User where id  = '6143545896216109') unwind all
`
First name does not get projected
Can we reopen this please..

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

I don't know which OrientDB version you are referring to, this issue was for v 2.1 that is no longer supported.
In V 3.0 you cannot use `expand()` and `unwind` together that way.

You have many alternatives depending of what is your goal:

```
select first_name, all from (select first_name, out('has_physical_property') as all from User where id = '6143545896216109') unwind all
```

```
select first_name, all:{*} from (select first_name, out('has_physical_property') as all from User where id = '6143545896216109') 
```

```
select first_name, all:{*} as all from (select first_name, out('has_physical_property') as all from User where id = '6143545896216109') unwind all
```

I hope it helps

Thanks

Luigi

**Comment by cegprakash** [comment]
The first query does expand any property. The 2nd and 3rd queries seem to work fine in 3.0.8. However they do not work in 2.2.36

**Comment by cegprakash** [comment]
The first query does not expand any property. The 2nd and 3rd queries seem to work fine in 3.0.8. However they do not work in 2.2.36
