### ISSUE TITLE
automatic attach/detach problem

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3756]
As documented in [this issue](https://github.com/orientechnologies/orientdb/issues/3707) and [this forum post](https://groups.google.com/forum/?fromgroups#!searchin/orient-database/detach%7Csort:date/orient-database/O8b_dOLwpB0/80bU0gqJcQ0J), it doesn't appear that the automatic attach/detach handles LINKLIST properties correctly.

**Comment by lvca** [comment]
@8forty In your case, did you call detach() on any element? Do you have an active Graph in current thread?

**Comment by 8forty** [comment]
No, I removed all calls to detach() (and attach()) when the automatic mode was added.  In this case, I do not have an active graph: I used an instance of OrientGraph from OrientGraphFactory.getNoTx() to query the Vertex, then used OrientGraph.shutdown() to release it, they tried to get the value of the LINKLIST.

**Comment by pabloa** [comment]
+1
