### ISSUE TITLE
Distributed mode does not work

### ISSUE THREAD

**Issue by gemmell** [orientechnologies/orientdb#3757]
The following is copied from our support channel in gitter. 

gemmell March 5 2015  
Hey guys, just a heads up that orientechnologies/orientdb#3690 is still broken, we have updated the sample code to demonstrate it (see the bottom of the tickert), however the ticket is still marked as closed. Can I get you to re-open it pls.
lvca March 6 2015  
Hi @gemmell did you write to prjhub?
gemmell 12 hours ago
No.
gemmell 11 hours ago
Any chance someone could look into it today? Is there a work around? Perhaps using the graph API rather than document API or something? It's totally broken at the moment and we are getting to the point where we have to make a decision on whether we continue to wait or start looking into alternatives. What would we need to do to just get this bug fixed? Pay some more? (are we still under a support contract?). It's going to be cheaper for us to pay for that than port our system to another db.

**Comment by lvca** [comment]
Hi, Your contract is expired on Feb 26th 2015. However we're looking at the issue. Please don't open a new issue with that topic, but rather send me an email.
