### ISSUE TITLE
Broken HTTP Basic Authentication in 2.0.5

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3759]
Guys,

There is very simple testcase:

```java
@Test
	public void testAuthentication() throws Exception
	{
                String userUrl = "/query/test/sql/select+from+$user";
		WicketOrientDbTester tester = wicket.getTester();
		String content = tester.executeUrl(userUrl , "GET", null, "reader", "reader");
		assertTrue(content.contains("reader"));
		content = tester.executeUrl(userUrl , "GET", null, "writer",  "writer");
		assertTrue(content.contains("writer"));
		content = tester.executeUrl(userUrl , "GET", null, "admin",  "admin");
		assertTrue(content.contains("admin"));
	}
```

executeUrl method just get content by URL with specifing HTTP Basic Auth for username/password

This testcase is OK on 2.0.4, but failing right on first assert in 2.0.4: it constantly returning previously authenticated in DB user instead of newly passed. 

And one more observation: if I'm trying to debug OrientDB code - it's passing from time to time. So it seems to me that there is some asynchronization introduced into 2.0.5 code.

**Comment by PhantomYdn** [comment]
According to `git bisect` bag was introduced by the following commit:
https://github.com/orientechnologies/orientdb/commit/992630fcdbfd0569242bcda87d6fe493f2199c5b

It seems that "Keep-Alive" are not fully supported by the rest of the functionality and that commit just reveal lots of stuff to fix...

**Comment by PhantomYdn** [comment]
After investigation bug is in following: by default java is keeping URL connections for reuse. If your application is authenticating through HTTP frequently: pay attention to avoiding of "Keep-Alive" usage or explicitly close HTTP connection to OrientDB prior to next authentication. 

So for now it seems more "client" bug rather than OrientDB. But I guess, we might have some unpredictable bug in 3rd party libraries due to closing of original bug with Keep-Alive.

**Comment by lvca** [comment]
@PhantomYdn maybe we should comment this on HTTP page on documentation. Could you write something we can add on it? (in short time docs will be stored on separate repo to allow changes to a wider set of contributors)

**Comment by PhantomYdn** [comment]
Good idea:)

I would like to see something like that in a section about REST and HTTP API:

```md
*Attention*: OrientDB HTTP API utiliaze 'Keep-Alive' feature feature for better performance, but be sure to use new HTTP connection for authentication instead of reuse existing one. 
```
