### ISSUE TITLE
Distributed: support for ORecordBytes on multiple clusters (like OClass)

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3762]

**Comment by robgratz** [comment]
If this is targeted for 2.2, when will this be released?  We cannot move to 2.x until we can automatically handle ORecordBytes fields.

**Comment by lvca** [comment]
About this feature now you should pass the cluster name to the ORecordbytes .save(). Example: you have 10 servers, named server1, server2, etc. If you want to execute your code against server7, you should call:

```java
ORecordBytes rb = ...
...
rb.save( "binary_server7" );
```

So now the selection of the right cluster for binary data is in charge to the developer.

**Comment by robgratz** [comment]
We can't do that because we don't control the server names.  Every customer could have different names and numbers of nodes.  It has to be dynamic for us to be useful.

**Comment by lvca** [comment]
Hey @robgratz is this still need from your side? Did you already migrate without this feature?

**Comment by tglman** [comment]
Added in 2.2 the support for "blob clusters", not yet supported in distributed, moving this to 3.0

**Comment by lvca** [comment]
@tglman what's missing to support it in HA?

**Comment by tglman** [comment]
Hi,

The main missing thing is the cluster selection strategy, and as well make sure that the "blob clusters" are in the distributed configuration, but that should work, to check as well the distributed flow, as today is quite targeted on ODocument, it may miss all the part specialized for blobs (with eventual class cast exception)

**Comment by tglman** [comment]
Hi,

The main missing thing is the cluster selection strategy, and as well make sure that the "blob clusters" are in the distributed configuration, but that should work, to check as well the distributed flow, as today is quite targeted on ODocument, it may miss all the part specialized for blobs (with eventual class cast exception)

**Comment by voondo** [comment]
Hi,

I get `Java::ComOrientechnologiesOrientServerDistributed::ODistributedException : Error on inserting into cluster 'default' where local node 'node-03' is not the master of it, but it is 'node-02'`.
Just to be sure : is it related to this issue ?

**Comment by voondo** [comment]
Also a warning about it on https://orientdb.com/docs/last/Binary-Data.html would be nice.

**Comment by FeldrinH** [comment]
https://orientdb.com/docs/3.2.x/java/Binary-Data.html?highlight=binary#store-it-with-orecordbytes still links to this issue with a warning that ORecordBytes is not supported in distributed mode.
Is the warning accurate or is the documentation out of date?
