### ISSUE TITLE
date format issue

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3766]
I have declared birthday field as date data type. But it will store the value as datetime format. 

for example....
i posted/saved the value 2015-01-01 to database.
after that, it will stored as 2015-01-01T00:00:00+0000 (datetime format)

**Comment by lvca** [comment]
How did you retrieve that value? SQL?

**Comment by martingg88** [comment]
select birthday from user

**Comment by lvca** [comment]
Use:

    select birthday.asDate() from user

**Comment by martingg88** [comment]
ok..but it's a bit trouble to doing that for each query i have everywhere in my code. anyway, i will keep with that first. furthemore, i do have following error even my class have only one record. 

Error on retrieving record
Caused by: com.orientechnologies.common.concur.OTimeoutException:
or 
Caused by: com.orientechnologies.common.concur.lock.OLockException: Cannot unlock a never acquired lock
