### ISSUE TITLE
Distributed read-only transactions are slow

### ISSUE THREAD

**Issue by lukeworthtkbt** [orientechnologies/orientdb#3768]
Not sure if this is a bug or just a misuse, but in distributed mode in the console we can go
```
begin
select * from myTable
commit
```
and the `commit` can run really slowly, probably trying to reach quorum. It would be great if this were fast since there were no writes to the database.

Internally in our code, we create a transaction after connection to the db, and commit just before disconnecting, so we have to change the read-only procedures to do a `rollback` at the end instead of a `commit`.

**Comment by lvca** [comment]
Executing a query inside a transaction has no sense. Try just executing the select.
