### ISSUE TITLE
OrientDB Studio - Unable to login into database once logout

### ISSUE THREAD

**Issue by bestcool** [orientechnologies/orientdb#3775]
**Environment details:**
---
OrientDB version: Orientdb-community-2.0-M3
Platform: Windows 7 Professional (64-bit) SP1
JAVA Version: JDK 1.7.0_67
Eclipse: Kepler

**Maven Dependencies:**
---
Spring MVC Version: 4.1.5.RELEASE
OrientDB Version: 2.0.5
JavaEE Web API: 7.0
JSTL: 1.2
Maven Compiler Plugin: 3.2
Jetty Server: org.mortbay.jetty

**Steps:**
---

I have created a new database using OrientDB Studio named **SpringMVC_DB** with user credentials **root/root**. It is created successfully. Then I **logged out from the OrientDB** studio.

I wrote a **Java program** to create Vertices & Edges in the above DB. The vertices named **FS** & **ABC** & an edge in between them called **has customer** are created successfully.

Now, I want **to view them in Graph mode** so, I **shutdown the Jetty server & again login to OrientDB Studio**. **It'll ask me to enter user credentials**. I tried **root/root**, **admin/admin**, **root/pwd**. But, none of them allow me access my database. I also tried to drop this database from OrientDB Studio, but stuck on the same problem.

I have also tried to **reset password** by login into another DB (the default one, GratefulDeadConcerts) using below command, password reset but, **no success in login** to SpringMVC_DB.

    update ouser set password = 'admin' where name = 'admin'

**OrientDB Console Output:**
       The output of the console shows some other process has locked the configuration file. But, there is no process accessing the OrientDB.

![error login orientdb database](https://cloud.githubusercontent.com/assets/9652745/6703400/7d1a2808-cd61-11e4-8479-3bd9b332bca8.PNG)

After so many tries & Googling I fade up & **restart my PC & starts only OrientDB using server.bat** file then console shows 

    WARNING segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment] 
    WARNING Storage SpringMVC_DB was not closed properly. Will try to restore from write ahead log. [OLocalPaginatedStorage]

See below screenshot:

![error login orientdb after shutdown](https://cloud.githubusercontent.com/assets/9652745/6703422/a89f3400-cd61-11e4-87df-91751a786ac7.PNG)

I also read http://comments.gmane.org/gmane.comp.db.orientdb.user/13487 discussion where @AndreyLomakin told that, **This issue was already fixed in 1.7-rc2 release**. I think it's not fixed even in **orientdb-community-2.0-M3** release.

I have also posted question on the stackoverflow http://stackoverflow.com/questions/29098646/orientdb-studio-unable-to-login-into-database-once-logout, but I didn't get any solution.

*Can OrientDB team give any solution on this ?*

It would be great if anyone solve this issue.

Thanks a lot

**Comment by bestcool** [comment]
Did you find any reason, why OrientDB raised `segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment] ` error ? Is this issue in progress ? What is the fix for it ?

**Comment by lvca** [comment]
Why using release 2.0-M3 when we finally released stable weeks ago? Please try 2.0.5 and let us know if you have the same issue again (in case reopen it).

**Comment by bestcool** [comment]
**This issue has been resolved in `orientdb-community-2.0.5`**. I have tried the same procedure I m following with `Orientdb-community-2.0-M3` release & didn't face any problem. Only it doesn't allow me  access DB by two different application i.e. 

**If I run server.bat & access DB & at the same time I run my project in Eclipse or vice versa, then it doesn't allow to access DB.**

Is OrientDB doesn't support this feature ? Is OrientDB accessible in multi-threading environment ?

**Comment by TheFlow0360** [comment]
Is it possible that this problem resurfaced? I'm using 2.2.37 and am facing a similar problem.

    OrientGraph g = new OrientGraph("plocal:databases/Test2", "root", "root");
    ...
    g.commit();
    g.shutdown(true);

This call does work when the database doesn't exist, but as soon as I start my application for the second time, it fails with 
> Exception in thread "main" com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'Test2'

**Comment by TheFlow0360** [comment]
I just rebuilt this to use the graph factory and default credentials, now it works. However, I don't consider this a solution, rather a workaround.

**Comment by TheWizl** [comment]
I cannot login to the database demodb through studio v3.0.22 at all. Restarted the whole server. Still Session expired.
