### ISSUE TITLE
Problem on parsing of slash for sql json.

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#3778]
We got two cases where the new sql parser fail to parse a json content
ex
```
insert into test content {
	"node_id": "MFmqvmht//sYYWB8="
}

insert into test content {
	"node_id": "MFmqvmht\/\/GYsYYWB8="
}
```

**Comment by SangWoo-Maeng** [comment]
@tglman Any workaround for this?

**Comment by luigidellaquila** [comment]
this issue was related to Studio. 
Now in develop branch the first statement works fine.
In the second one, if you want to also store the backslashes, you have to quote them:
```
  {
    "node_id": "MFmqvmht\\/\\/GYsYYWB8="
  }
```
