### ISSUE TITLE
Cannot UPDATE the record because the version is not the latest HTTP REST API

### ISSUE THREAD

**Issue by genietto84** [orientechnologies/orientdb#3779]
Hi,
I'm trying to use transaction on HTTP REST API with this request
http://127.0.0.1:2480/batch/mydbname

content:

```
{
	"transaction":true,
	"operations":[
		{
			"type":"u",
			"record":{
				"@rid":"#43:31",
				"name":"Luca"
			}
		}
	]
} 
```

The response is

"com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #43:31 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v1 your=v0)"

What's wrong
Tnx

**Comment by lvca** [comment]
You should pass also the version to pass the MVCC. Try this:
```json
{
    "transaction":true,
    "operations":[
        {
            "type":"u",
            "record":{
                "@rid":"#43:31",
                "@version":1,
                "name":"Luca"
            }
        }
    ]
} 
```

**Comment by jpstrikesback** [comment]
In our case, we were getting this via SQL over binary (OJS) as well as in the Studio with certain vertices, it turned out those vertices always had an embedded doc with the @type set, like:

```json
{
  "someProp": 123,
  "someEmbedded": {
    "@type": "d",
    "someProp: [...]
  }
}
```

When we removed the inner embedded docs @type flag, we no longer experienced the concurrency exception.
