### ISSUE TITLE
Import records using CipherInputStream

### ISSUE THREAD

**Issue by unQualsevol** [orientechnologies/orientdb#3781]
I'm trying to export and import using 
<code>public ODatabaseExport(final ODatabaseDocumentInternal iDatabase, final OutputStream iOutputStream,
      final OCommandOutputListener iListener)</code>
and 
<code>public ODatabaseImport(final ODatabaseDocumentInternal database, final InputStream iStream, final OCommandOutputListener iListener)</code>
in encrypted way using CipherOutputStream and CipherInputStream.

The export is working fine but the import seems to have problems when the process tries to check if the InputStream is ready. If I force a read the process can read like 512 bytes but then the ready turns false and the process stop. I think this only happen this JSON objects bigger than 512 bytes. 

This can be solved in some way?

**Comment by lvca** [comment]
No more relevant, closing it.
