### ISSUE TITLE
Support parameters in the REST API

### ISSUE THREAD

**Issue by Pajn** [orientechnologies/orientdb#3782]
Query parameters should be supported fro both SQL and Gremlin queries in the REST API.

**Comment by lvca** [comment]
What do you mean?

**Comment by Pajn** [comment]
When passing a query like `SELECT * FROM Movie WHERE name = "Avatar"` and the name comes from the user one is vulnerable for SQL injections, the same is true for Gremlin queries.

**Comment by Pajn** [comment]
To clarify: Orient Db already supports this in the Java API (<http://www.orientechnologies.com/docs/last/Document-Database.html#prepared-query> and <http://www.orientechnologies.com/docs/last/Gremlin.html#passing-input-parameters>)  but there seems to be no way of using it from the REST (or binary?) API.

**Comment by Pajn** [comment]
Is there any workaround until there are real support for parameterized queries, some official doc on all tokens to escape?

**Comment by lvca** [comment]
Ok, this is really needed, I set 2.2 as milestone. The easiest way is to support a JSON in the payload of `/command` like:

```json
{ "parameters": { "name": "Avatar" } }
```

and also positional:

```json
{ "parameters": [ "Avatar" ] }
```

**Comment by josebalius** [comment]
+1 on this

**Comment by josebalius** [comment]
@lvca awesome job! this will be available in the next release?

**Comment by lvca** [comment]
Yes, 2.2
