### ISSUE TITLE
MOVE VERTEX no longer updates edges

### ISSUE THREAD

**Issue by CasperCLD** [orientechnologies/orientdb#3783]
The title pretty much says all. I want to move a record in OrientDB from the 'Asset' class to a new class (that keeps the old version of the class 'Asset'). This is possible with MOVE VERTEX x to y. However this creates a new RID for the node and none of the relations with the old RID are updated to the new RID. @lvca  said [here] (http://stackoverflow.com/questions/29147230/orientdb-how-to-move-a-vertex-and-maintain-relations/29147292#29147292) that it should change the RID, so it's broken in 2.0.5

**Comment by lvca** [comment]
What's the command you executed?

**Comment by CasperWW** [comment]
The command: ```MOVE VERTEX #12:0 TO CLASS:Version```

To reproduce, the sequence was as follows:
```
CREATE VERTEX Asset
CREATE VERTEX Asset
CREATE EDGE FROM #12:0 TO #12:1
MOVE VERTEX #12:0 TO CLASS:Version
```
Then ```SELECT FROM E``` shows me that edge ```#10:0``` still references ```#12:0``` and ```#12:1```

**Comment by lvca** [comment]
Reproduced, thanks.
