### ISSUE TITLE
UPSERT should manage OConcurrentModificationException

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3786]
In case of concurrency, the OConcurrentModificationException should be caught and managed properly by applying changes on loaded record.

**Comment by machinelearner** [comment]
Hello,
This looks familiar and interesting. It'll be good if you can describe scenarios when this is likely to occur and the effects of the fix. 
Is it going to not throw up during edge creation concurrently with a common vertex(essentially no content change but internal properties, by means of edge creation, of a vertex changed)

**Comment by lvca** [comment]
@machinelearner this is only for UPDATE and UPSERT.

**Comment by machinelearner** [comment]
@lvca true. But edge addition is in a way **update** on the vertex it is being added to, no?
 Or Is this just going to affect document database and not the graph api?

**Comment by lvca** [comment]
This is only for doc db api.
