### ISSUE TITLE
ingoing edge, filters on edge properties and limit

### ISSUE THREAD

**Issue by agiuliano** [orientechnologies/orientdb#3787]
I think I found a bug on the limit usage.
This is my test environment (~1million edge, 1 million vertices):
User (extends V), Book (extends V), Rate (extends E).
Rate has a property "rating" representing the user's rate for a particular book, so I have:
`User --- Rate --> Book`

Now I want to select all those users who have rated a book with a rating equals to 7.
This is the query:
`select expand(inE()[rating=7]) from Book limit 15`
This query returns 6 items even though the limit is 15. 
So I thought that the limit was on the books and it make sense.

But when I increase the limit, something happens:
`select expand(inE()[rating=7]) from Book limit 20` returns 20 items
`select expand(inE()[rating=7]) from Book limit 30` returns 30 items
`select expand(inE()[rating=7]) from Book limit 40` returns 40 items
and so forth...

Then I though to separate the limits in order to see where is the error.
This is the query:
`select from (select expand(inE()[rating=7]) from Book limit 20) limit 15` returns 15 items
and
`select from (select expand(inE()[rating=7]) from Book limit 15) limit 15` returns the 6 items corresponding to the `select expand(inE()[rating=7]) from Book limit 15` query.

Finally I tried:
`select from (select expand(inE()[rating=7]) from Book limit 40) limit 100` returns 40 items
`select from (select expand(inE()[rating=7]) from Book limit 50) limit 100` returns 50 items
`select from (select expand(inE()[rating=7]) from Book limit 60) limit 100` returns 60 items

Obviously there isn't a rating of value 7 for every book (some are rated 7 more times, some others have no 7 rating).

The question is: is there a bug in the `limit` interpretation in these cases?

**Comment by luigidellaquila** [comment]
Hi @agiuliano 

This issue was fixed long time ago. I'm closing it, please reopen if you experience related problems

Thanks

Luigi
