### ISSUE TITLE
Prefixing the system properties with 'orientdb'

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3788]
When issuing 'ps -ef | grep java' and seeing the command line for our server java process, the system property `-Dstorage.diskCache.bufferSize=10000` is visible.

It is better to prefix it like `-Dorientdb.diskCache.bufferSize=10000` in order to differentiate it from the system properties of other libraries running in that JVM.

This is not a high priority task.

**Comment by lvca** [comment]
it would be nice to have, but it would break all settings we already have.

**Comment by lvca** [comment]
No more relevant, closing it.
