### ISSUE TITLE
problem with the renaming of class

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#3791]
I have class "testClass"

> create class testClass
> Class created successfully. Total classes in database now: 24

if you do a bad request
> ALTER CLASS testClass NAME = 'rename_class'
> Class updated successfully

class name is "= 'rename_class'"
then the class can not be deleted or renamed

> ALTER CLASS = 'rename_class' NAME goodName
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #22: Unknown class's attribute '' NAME goodName'. Supported attributes are: [NAME, SHO
RTNAME, SUPERCLASS, OVERSIZE, STRICTMODE, ADDCLUSTER, REMOVECLUSTER, CUSTOM, ABSTRACT, CLUSTERSELECTION]
Command: alter CLASS = 'rename_class' NAME goodName
------------------------------^

> DROP CLASS = 'rename_class'
Removed class in 0,045000 sec(s).

but
> classes
----------------------------------------------+----------------------
-------------+
 NAME                                         | SUPERCLASS
CORDS        |
----------------------------------------------+----------------------
-------------+
= 'rename_class'                                | 
           0 |
 _studio                                      |
           0 |

**Comment by tglman** [comment]
fixed closing
