### ISSUE TITLE
count(*) is counting object twice if two conditions match and parallel is enabled

### ISSUE THREAD

**Issue by KIC** [orientechnologies/orientdb#3793]
While this query is showing me a correct count = 1 

<pre>
select @class, count(*) from foo1 where (name LUCENE 'test' or text LUCENE 'test'  ) group by @class
</pre>

The same query with parallel shows me an incorrect count of 2:

<pre>
select @class, count(*) from foo1 where (name LUCENE 'test' or text LUCENE 'test'  ) group by @class parallel
</pre>

How to reproduce:

<pre>
create class foo1
create property foo1.name string
create property foo1.text string
CREATE INDEX 'foo1.text' ON foo1 (text) FULLTEXT ENGINE LUCENE
CREATE INDEX 'foo1.name' ON foo1 (name) FULLTEXT ENGINE LUCENE
insert into foo1 content {"name" : "test", "text" : "test"}
select @class, count(*) from foo1 where (name LUCENE 'test' or text LUCENE 'test'  ) group by @class
select @class, count(*) from foo1 where (name LUCENE 'test' or text LUCENE 'test'  ) group by @class parallel
</pre>

**Comment by lvca** [comment]
Fixed long time ago.
