### ISSUE TITLE
NPE while retrieving field from document

### ISSUE THREAD

**Issue by uttamatsimility** [orientechnologies/orientdb#3795]
Randomly ODB throws NPE while retrieving field from document. It was was reported in 2.0.1 and we were told that it was taken care of. We are on 2.0.4 and the issue appears again...
I thought it was taken care earlier. We are on 2.0.4 and the issue appears again...

java.lang.NullPointerException
	com.orientechnologies.orient.core.metadata.OMetadataDefault$ThreadLocalSchemaSnapshot.access$100(OMetadataDefault.java:279)
	com.orientechnologies.orient.core.metadata.OMetadataDefault.clearThreadLocalSchemaSnapshot(OMetadataDefault.java:122)
	com.orientechnologies.orient.core.record.impl.ODocument.getGlobalPropertyById(ODocument.java:1474)
	com.orientechnologies.orient.core.record.impl.ODocumentInternal.getGlobalPropertyById(ODocumentInternal.java:55)
	com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getGlobalProperty(ORecordSerializerBinaryV0.java:275)
	com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:175)
	com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:74)
	com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1796)
	com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2189)
	com.orientechnologies.orient.core.record.impl.ODocument.toString(ODocument.java:723)

One this happens, restarting OrientDB remains the only option to get out of it...

**Comment by tglman** [comment]
hi @uttamatsimility 
I just add a check that should fix this problem in 2.0.6, the really good news is that this logic is quite changed in 2.1 so this cannot happen.

by the way is weird, this should not affect all the orientdb but just one thread, if you have also a test case to reproduce this error, will help us a lot to double check the fix.

**Comment by lvca** [comment]
I'm closing the issue. If it's not fixed, please reopen this.
