### ISSUE TITLE
The way to get minimum of childrens's field recursively by Query

### ISSUE THREAD

**Issue by nishikawatai** [orientechnologies/orientdb#3797]
Hi,

Excuse me if my English is difficult to understand.

I use orientdb-community-2.0.4.
I make a graph  by Nodes that have a Date type's field as below:

Node #12:0 -> Node #12:1 -> Node #12:2 -> ...
                                           -> Node #12:3 -> ...
                    -> Node #12:4 -> ...

I want to make a Query to do .
  1. A target node (ex. #12:2) gets minimum of Date field from its children and sets it to own field.
  2. Then, #12:1 also gets minimum of field from its children and sets it.
  3. It continues until Node #12:0 finishes.

I made a Query as below, but null is set to #12:0's, #12:1's and #12:2's fields after Executing it.

-----------------------

Update ( Select from ( Traverse in() from #12:2 ) let $currentNode = $current) set dateField = $minDate['min'][0] let $minDate = ( Select min(dateField) as min from ( Traverse out() from $currentNode) )

----------------------

I don't know what is wrong.
Please tell me the correct way.

Kind Regards, 
Taichi Nishikawa

**Comment by lvca** [comment]
This is more a question than an issue. Please post in Community Group where more than 2k users can answer to your question:

https://groups.google.com/forum/#!forum/orient-database
