### ISSUE TITLE
OrientDB query second level of relationship keeping the intermediate id

### ISSUE THREAD

**Issue by ashcrok** [orientechnologies/orientdb#3800]
I want to query a vertex in OrientDB graph database to get the second level vertices, keeping the in between vertex id.

The relationship would be represented as such:

```
User <--edge--> User <--edge--> User
(1)             (2)             (3)
```

For User 1, I want to get all User 3 (distance of 2 edges), but I want to keep as a result all User 2 rids. The direction isn't important (will use both() method to traverse)

An example:

```
#10:1 <--edge--> #10:2
#10:1 <--edge--> #10:3
#10:2 <--edge--> #10:4
#10:2 <--edge--> #10:5
#10:3 <--edge--> #10:6
```

For the example above, the query for #10:1 should return: (don't know how to represent this any better, but the query should return the object from the class User AND the rid from the intermediate User)

```
User(#10:4), #10:2
User(#10:5), #10:2
User(#10:6), #10:3
```

The query to find the vertices from the second level would look like: select expend(both('edge').both('edge')) from #10:2 (of course the query can be optimized with set function and other conditions in case of inter-relations of the output users). To this output, I would like to see an additional field (property / column, whatever you want to call it) where I can see the in between vertex of this kind of relationship.

Hope somebody can help me with this, tell me if you need more information, or if you did not understand something. Thank you.

UPDATE:

I found out how it should be done, but it does not work (I believe that it is a bug of some sort, reported it and I'm waiting for an answer right now).

The query that should work, looks something like this:

```
select *,$id from (
  select both('edge') from (
    select from (
      select both('edge') from <rid>
    ) let $id = @rid
  )
)
```

Of course, the query can be optimized (less sub-queries), but for the sake of the logic, I stated it like this.

The problem with the query is that for example stated above, all of the $id values will be #10:3, because it is the last value of the records. The LET clause doesn't point individual values to each record, but associates the last value with all of the records (as I mentioned in the example).

Maybe I'm wrong and it is not a bug, if anyone knows something about it, hope you can help me. If it is a bug, I am open to suggestions to work around the problem. Thank you.

**Comment by lvca** [comment]
I've reformatted the message. Please use markdown formatting to let us reading the code.

**Comment by atboo** [comment]
Why not using "both('edge').both('edge')" ?

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
