### ISSUE TITLE
Delete doesn't delete records

### ISSUE THREAD

**Issue by johnmelba** [orientechnologies/orientdb#3803]
I am trying to add an index to table/class with existing data. I am trying to run a delete statement prior to creation of index. When executed from studio, the statement deletes duplicate records. But when executed under java, the index creation fails stating duplicate records present

Here's my code...
```java
OObjectDatabaseTx odb = //init;
            odb.command(
                    new OCommandSQL("delete from RE where @rid in (" +
                            "select rid from (select name, min(@rid) as rid from RE where name in ( " +
                            "select entityId, name from (select entityId, name, count(*) " +
                            "from RE group by  entityId, name) where count > 1) " +
                            "group by name))")).execute();
//Code to add unique index
OClass entityClass = odb.getMetadata().getSchema().getClass("RE");
entityClass.createIndex("RE.entityId_ruleName", OClass.INDEX_TYPE.UNIQUE_HASH_INDEX, "entity", "name");
```

I get exception at createIndex. 

NOTE: Table doesn't have much data - only 72 records.

**Comment by lvca** [comment]
Have you tried running the inner query in studio to see the results?

**Comment by lvca** [comment]
Any update on this?
