### ISSUE TITLE
Javascript API has dependency on jQuery

### ISSUE THREAD

**Issue by stokito** [orientechnologies/orientdb#3804]
[Javascript API ](http://www.orientechnologies.com/docs/last/Javascript-Driver.html) uses jQuery for performing XHR requests. But it's not mentioned in documentation.
Also if we use other framework, like AngularJS it can have own AJAX implementation.
So, it would be good to make XHR abstract or at least mention in documentation about jQuery dependency.

**Comment by lvca** [comment]
JS API is remained quite old, because there are no many contributors and users. @stokito Would you like to contribute to it and send us a Pull Request (against "develop" branch)?

**Comment by stokito** [comment]
Yes, it would be interesting for me. You may assign this issue on me

**Comment by lvca** [comment]
Great ;-)

**Comment by olegshestakov** [comment]
What is the status of this issue?

**Comment by stokito** [comment]
I didn't made anything on this. But meanwile last jQuery version contains Slim distribution without Ajax.

**Comment by olegshestakov** [comment]
As I understand this JS API is deprecated. What the sense of this issue?  (sorry, for question but I try to find issue for contribution)

**Comment by stokito** [comment]
I created this issue two years ago, i think is not important anymore so I'll xlose it
