### ISSUE TITLE
Error adding a document with DATETIME field from Studio

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#3806]
Hi,

There seems to be a problem using DATETIME fields when creating a document from Studio for OrientDB 2.0.5. 

Steps to reproduce:

1. Create a new class with a DATETIME property
2. Do "+ New Record"
3. Select **only date value** (i.e. do not touch the time field) and click "Save"
4. If you modify time value then saves goes through
. 5Also, if record is refreshed, time value may disappear

**Comment by maggiolo00** [comment]
Tested in 2.2.x and it has been fixed.

Thanks
