### ISSUE TITLE
insert into V content {  "url": "http://www.google.com" 	} } FAILS

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#3809]
OrientDB 2.0.5

If insert into V content { ... } should allow us to simply add content in json-notation, it shouldn't fail with this query
<code>insert into V content {  "url": "http://www.google.com" 	} }</code>

This will work if I make sure it is
<code>insert into V content {  "url": "http:\/\/www.google.com" 	} }</code>

but that seems like a bug to me, since the first version is proper json.

The returned message is:
<code>java.lang.IllegalStateException: Missing closed string character: '"', position: 39</code>

**Comment by mrft** [comment]
Seems to be the same issue as #3778

**Comment by martingg88** [comment]
it related to https://github.com/orientechnologies/orientdb/issues/3582

**Comment by luigidellaquila** [comment]
Hi @mrft 
this issue was related to Studio, it's fixed now in develop branch.
Just to be sure I added a couple of test cases

Luigi
