### ISSUE TITLE
delete vertex with limit throws errors

### ISSUE THREAD

**Issue by johnmelba** [orientechnologies/orientdb#3810]
Syntax
delete vertex XXXXXX  limit 10000

Does NOT work. Error -- 
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Class 'LIMIT was not found

and same table ...................

delete vertex XXXXXX where 1=1  limit 10000

WORKS with a dummy where clause. 10000 rows deleted.

**Comment by luigidellaquila** [comment]
fixed in develop branch
