### ISSUE TITLE
Error on edge creation within a tranasaction don't make rollback on vertexs whit REST API

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientdb#3813]
I'm using orientdb 2.0.5 and postman to make the post that shows below.

```javascript
{ 
    "transaction": false,
    "operations": 
        [ 
            { 
                "type": "script",
                "language": "sql",
                "script": "begin\nlet p1 = insert into Person content {'id':24,'firstName':'Manuel','lastName':'Vargas'}\nlet p2 = insert into Person content {'id':25,'firstName':'Fernanda','lastName':'López'}\nlet ed = create edge Knows from $p1 to $p2 content { fech: 2014-3-25 23:19:56 }\ncommit retry 100\nreturn $ed" 
            } 
        ] 
}
```

***Note*** that fech property on Knows edge is datetime type and i'm sending it as number type to force an error.

And i get the next response, as expected.

> com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content for record: fech: 2014-3-25 23:19:56
--> java.lang.NumberFormatException: For input string: "2014-3-2523"

But when i check the database, i notice that the vertex p1 and p2 were created and the Knows edge wasn't.

I suppose that the transaction has to make a rollback on p1 and p2 when the edge creation fails.

**Comment by shekhei** [comment]
I am facing similar problems with binary protocol, console and even custom functions.

```
begin
create vertex ...
create vertex ... #duplicate record error thrown
create vertex ...
commit
```
With the 2nd create statement throwing error, I expected everything to rollback. Instead, the 4th statement was also executed, along with the commit...

**Comment by shekhei** [comment]
any updates?

**Comment by lvca** [comment]
NumberFormatException? you should put the date in string quotes: 

    fech: '2014-3-25 23:19:56'

**Comment by lvca** [comment]
Reopened, because the issue is on TX.

**Comment by lvca** [comment]
@tglman is this already fixed?

**Comment by tglman** [comment]
fixed

**Comment by shekhei** [comment]
nice~~ so I suppose this would be in for 2.0.7? when is it going to be released?
