### ISSUE TITLE
Error executing simple function from Studio

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#3814]
Hi,

OrientDB 2.0.5 studio throws an exception trying to execute a simple function:

``
var db = orient.getDatabase();
return true;
``

There error is as follows:

``
Erroronparsingscriptatposition#0: ErroronexecutionofthescriptScript: createActionLog------^sun.org.mozilla.javascript.WrappedException: Wrappedcom.orientechnologies.orient.core.exception.OConfigurationException: Nodatabaseinstancefoundincontext(<Unknownsource>#2)in<Unknownsource>atlinenumber2Wrappedcom.orientechnologies.orient.core.exception.OConfigurationException: Nodatabaseinstancefoundincontext(<Unknownsource>#2)Nodatabaseinstancefoundincontext
``

As a workaround for now you can use ``orient.getGraph()`` and work with graph instance of the database.

**Comment by ravihara** [comment]
I'm seeing this issue in OrientDB 2.0.8 Studio too. Please help.

**Comment by luigidellaquila** [comment]
fixed in develop and 2.0.x branches
