### ISSUE TITLE
How is it possible to view Class custom properties from Studio?

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#3815]
I've extended an OTriggered and added an onBeforeUpdate custom property to my class.

1. How is it possible to view this property in the studio? 
2. If studio cant show this info yet, then how is it possible to view it using either SQL or console command?

**Comment by Ivanov-Yuriy** [comment]
I use this command to the studio and console
*select customFields from (select expand(classes) from metadata:schema) where name =* '**myClassName** '

**Comment by andreyvk** [comment]
Hi Yuriy, 

Thanks for the pointer here. This one didnt work right out of the box, but i got the idea. I modified your query a little and this one does the job perfectly:

```sql
select expand(properties) from (select expand(classes) from metadata:schema) where name = 'myClassName'
```

Thanks again!

**Comment by Ivanov-Yuriy** [comment]
Your welcome.
Note. Your query shows properties' custom field and my - classes' custom
field

Hi Yuriy,

Thanks for the pointer here. This one didnt work right out of the box, but
i got the idea. I modified your query a little and this one does the job
perfectly:

select expand(properties) from (select expand(classes) from
metadata:schema) where name = 'myClassName'

Thanks again!

—
Reply to this email directly or view it on GitHub
<https://github.com/orientechnologies/orientdb/issues/3815#issuecomment-107868072>
.

**Comment by andreyvk** [comment]
Yup, i replied too soon and then realized that my query was wrong :) Had to mod my answer quickly!
