### ISSUE TITLE
Error on parametrized query in javascript function

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#3816]
Hi,

I have this function code which returns an error. What am I doing wrong?

```javascript
var gdb = orient.getGraphNoTx();

var v = gdb.command("sql", "create vertex ActionLog content { \"time\": ?, \"note\": ? }", [(new Date().getTime()), 'note']);

return v;
```

The error is as follows:

```
Erroronparsingscriptatposition#0: ErroronexecutionofthescriptScript: createActionLog------^sun.org.mozilla.javascript.WrappedException: Wrappedcom.orientechnologies.orient.core.exception.OSerializationException: ErroronunmarshallingJSONcontentforrecord: "time": ?,
"note": ?(<Unknownsource>#4)in<Unknownsource>atlinenumber4Wrappedcom.orientechnologies.orient.core.exception.OSerializationException: ErroronunmarshallingJSONcontentforrecord: "time": ?,
"note": ?(<Unknownsource>#4)ErroronunmarshallingJSONcontentforrecord: "time": ?,
"note": ?Forinputstring: "?"
```

Note: TestV is a class extending V. Non-parametrized queries work fine though.

**Comment by optimuspaul** [comment]
I see a similar thing except no error. I just don't get any results if the query has parameters, but only in Studio, works fine in REST API

**Comment by lvca** [comment]
Try this:

    var v = gdb.command("sql", "create vertex ActionLog content { \"time\": ?, \"note\": ? }", [ new Date().getTime(), 'note'] );

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
