### ISSUE TITLE
document and edges

### ISSUE THREAD

**Issue by yujinlim** [orientechnologies/orientdb#3817]
Hi,

I created few classes and insert some documents in it. I was able to create edges between documents, but when I do `traverse out('property') from #12:1`, it returns only a single document(#12:1). I was able to get all nodes via `traverse all()` command.

Questions:
- should document database able to create edges?
- if they able to create edges, should they be able to use `traverse` command as a graph database?

Please advice. Thanks

**Comment by lvca** [comment]
Documents can't have edges, but rather LINKs. How did you created edges against documents? Can you send us the sequence of commands that did it?

**Comment by yujinlim** [comment]
I'm using OrientDB version 2.0

```
create class user
create class socials
create class owns extends E

// #12:1 is from user and #18:1 from socials
create edge owns from #12:1 to #18:1
```

Thanks

**Comment by lvca** [comment]
User and Socials must extend "V" to being considered as vertices.
