### ISSUE TITLE
ClassCastException on saving document with a BOOLEAN field in Studio

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#3818]
Hi,

Im getting the following error in OrientDB 2.0.5 studio sometimes while trying to save a document with a BOOLEAN field in it:

```
2015-03-26 10:08:55:769 SEVERE Internal server error:
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String [ONetworkProtocolHttpDb]
```

Below is the screenshot:
![error-boolean](https://cloud.githubusercontent.com/assets/1415506/6844036/0e154886-d3db-11e4-987c-29fba6f18d7d.png)

**Comment by maggiolo00** [comment]
Is the field isDeleted declared in the Test class?

**Comment by andreyvk** [comment]
Hi @maggiolo00. Im now using the 2.0.8 and I cant reproduce the problem anymore. I tried same class ```isDeleted``` attribute and parent class ```isDeleted``` attribute to no avail. I think it's safe to close the issue. Next time I'll give a more detailed description of the problem. Cheers
