### ISSUE TITLE
fetchplan should not return in_ and out_ edges by default

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#3820]
Using fetchplan in_*:-2 and fetchplan out_*:-2 can be used to not return the adjacent nodes.

I think this should be the default behaviour, because an edge is expressing a relationship, and a relationship is not a direct property of the node (and it's inefficient when you have thousands of edges going in or out a node).

The node is a simple concept, only having properties directly applicable to that node. For example a Person has a name, an email address etc.

So when you do

<pre>select * from Person</pre>

you simply want to get a list of names and email addresses.

If you wanted to know something about this Person's friends, you would find the relevant edges, follow them and get to his friends.

The good thing about a graph database should be that, in contrast to a relational database, you don't have to store something like a 'foreign key' inside of your objects. The graph model should abstract that away for the user (despite of how it could be modelled internally). Other objects should only become visible when you start traversing edges.

So I think that OrientDB should not even expose the fact that, when you create an edge between two nodes, actually a link to the edge is kept in both nodes also. This is just for performance reasons, but should be internal to the database. I think edges should always be saved separately from the nodes (except maybe in some 'more efficient' lower-level import strategy).

Here a thread to which the poster never got a proper answer: https://groups.google.com/forum/#!topic/orient-database/dkvcle-s-RA
Another question that is related: should edges influence the version of nodes?
https://groups.google.com/forum/?pli=1#!topic/orient-database/XiJX4Drn7eM

And I have been fighting for a long time to just get out of the database what I need, but taking the crap out is hard to do, to say the least. It should not be done by using fetchplan ["don't load any properties starting with in_"], that is name_based and will fail quickly in some more complex situations.

So this is more than a plea for sensible defaults (hide adjacent nodes by default).
I goes further, I am arguing that the adjacent nodes, and the edges should be accessible only through the functions ( out(), outE(), etc. ). The fact that each side of the relationship is kept up-to-date with a list of neighbours, should be invisible for the user (that is simply "the way it works", in order to get the performance you want, but is not relevant - and even disturbing - for the user).

**Comment by mrft** [comment]
Another argument for abstracting how edges are actually handled internally is that if one uses 'lightweight' edges, the actual SQL for traversing has to be changed. This means that the 'edge' is not abstract enough.
It makes sense that, if an edge has no properties, it can be stored without actually creating an object of class edge in the database. This will be more efficient for storing and for traversing edges, but in the mental modal that the user has about a graph database, the edge is still an edge, and he shouldn't have to be aware of that difference (at least not when writing SQL queries).

**Comment by mrft** [comment]
Another thing that would be useful is, if you want to get the from or to-nodes from an edge, to have functions that are called **from()** and **to()** (or fromV() and toV()), because that is much more intuitive than in and out (quite confusing on edges).

And here is another recent thread that asks (rightfully in my opinion) how you can avoid updating the vertex version when an edge is added: https://groups.google.com/forum/?pli=1#!searchin/orient-database/mrft%7Csort:date/orient-database/XIkV6z_P1wQ/yUeFktaEI7gJ

Again I think this should be the default behaviour.

A question of mine (all related to the same basic problem) to which I didn't get a proper answer either: https://groups.google.com/forum/?pli=1#!searchin/orient-database/mrft%7Csort:date/orient-database/XIkV6z_P1wQ/yUeFktaEI7gJ

*So, to rephrase the whole point of this ticket*: **In OrientSQL, a lot of work has to be done to make sure a graph-database is really abstracted fully as being a graph database to the user**, at this time - although OrientDB is claimed to be both a document DB and a graph DB - OrientDB is not a graph database (yet). As soon as a class is a subclass of a Vertex or an Edge, the behaviour should be changed, and the 'links' to other Vertices or to other Edges should be 'invisible'.

And why is the SQL language so important? Because it allows for declarative programming, which is less error-prone that declarative programming.

I'd love to hear the developers' comments on this.

**Comment by mrft** [comment]
Surprised to see the 'performance' label added to this ticket...

**Comment by smolinari** [comment]
Yeah, this is more about usability, which is something that I also feel needs to be looked at, especially as a relative newcomer to ODB. 

I've been watching the ODB Google group and the issues here for the past few months and a lot of time spent by the ODB team is explaining alternative/ corrected SQL queries to get certain and proper results out of ODB (and obviously some of those questions go unanswered too, probably because there are simply too many???). One could say, "do a better job answering the questions". However, a better and more pragmatic and time saving approach is to improve the concepts and abstractions behind the ODB SQL language, which is what I believe you are asking for @mrft?

Or, do a much, much better job explaining the concepts and abstractions in the documentation, if the language itself cannot be simplified. 

Scott

**Comment by mrft** [comment]
@smolinari indeed that is what I am asking for :)

**Comment by martingg88** [comment]
Yeap. I have experienced the poor performance for this issue if you have a vertex that have 100k edge.

**Comment by a-unite** [comment]
Fully agree with @mrft.
