### ISSUE TITLE
detachAll(*, true) for record with embedded fields works incorrectly

### ISSUE THREAD

**Issue by gypergrand** [orientechnologies/orientdb#3823]
Seems that 'detachAll' command improperly collecting identities for embedded field records in the map 'alreadyDetached' in OObjectEntitySerializer, which are always '#-1:-1', and therefore creating wrong nonProxiedInstance object.

Here is the simple JUnit test:

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.not;
import static org.junit.Assert.assertThat;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import org.junit.Test;
import com.orientechnologies.orient.object.db.OObjectDatabaseTx;

public class DetachAllTest {
    @Entity
    public static class EmbeddedClass {
        public EmbeddedClass() {
            super();
        }
    	private String name;

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}
    }
    
    @Entity
    public static class ContainingClass {
    	@Embedded
    	private EmbeddedClass field1;
    	@Embedded
    	private EmbeddedClass field2;
		public ContainingClass() {
			super();
		}
		public EmbeddedClass getField1() {
			return field1;
		}
		public void setField1(EmbeddedClass field1) {
			this.field1 = field1;
		}
		public EmbeddedClass getField2() {
			return field2;
		}
		public void setField2(EmbeddedClass field2) {
			this.field2 = field2;
		}
    }
    
    @Test
    public void detachAllForRecordsWithEmbeddedFieldsBugTest() {
    	OObjectDatabaseTx db = new OObjectDatabaseTx("plocal:./LocalTestDB");
    	if (!db.exists()) {
    		db.create();
    	} else {
    		db.open("admin", "admin");
    	}
    	try {
			db.setAutomaticSchemaGeneration(true);
			db.getEntityManager().registerEntityClass(EmbeddedClass.class);
			db.getEntityManager().registerEntityClass(ContainingClass.class);
			db.reload();
			EmbeddedClass emb1 = new EmbeddedClass();
			emb1.setName("emb1");
			EmbeddedClass emb2 = new EmbeddedClass();
			emb2.setName("emb2");
			ContainingClass con = new ContainingClass();
			con.setField1(emb1);
			con.setField2(emb2);
			con = db.save(con);
			ContainingClass concopy = db.detachAll(con, true);
			emb1 = concopy.getField1();
			emb2 = concopy.getField2();
			assertThat(emb1.getName(), is(not(equalTo(emb2.getName()))));
    } catch (Exception e) {
			throw e;
		} finally {
			db.drop();
			db.close();
		}
    }
}

So, I'm using OrientDB 2.0.5 release, and after detachAll, emb1 and emb2 objects for me are the same javassist proxies!

**Comment by nathanmbrown** [comment]
Fixed by PR https://github.com/orientechnologies/orientdb/pull/6072

**Comment by tglman** [comment]
merged the relative pull request, closing
