### ISSUE TITLE
why space is not valid in field

### ISSUE THREAD

**Issue by lincoln310** [orientechnologies/orientdb#3827]
I use etl to import from json, and failed due to the space in field.
     Caused by: java.lang.IllegalArgumentException: Invalid field name '中 文'. Character ' ' is invalid

i checked the code:
public static Character checkFieldNameIfValid(String iName) {
    if (iName == null)
      throw new IllegalArgumentException("Name is null");

    iName = iName.trim();

    final int nameSize = iName.length();

    if (nameSize == 0)
      throw new IllegalArgumentException("Name is empty");

    for (int i = 0; i < nameSize; ++i) {
      final char c = iName.charAt(i);
      if (c == ':' || c == ',' || c == ';' || c == ' ' || c == '%' || c == '=')  // why space is not valid?
        // INVALID CHARACTER
        return c;
    }

    return null;
  }

**Comment by lvca** [comment]
Spaces are not allowed as field names, like also in many languages, you cannot have properties with spaces. Can you replace them with underscore or any other character?
