### ISSUE TITLE
Are there any future plans for supporting spring-data OGM binding like the one that NEO4J has?

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#3828]
I know about Tinkerpop Frames (https://github.com/tinkerpop/frames/wiki) but I would like to see something that is built on top of that. I also know about this project (https://github.com/orientechnologies/spring-data-orientdb) but this is built similar to http://projects.spring.io/spring-data-mongodb/ and doesn't have the functionalities and mapping of http://projects.spring.io/spring-data-neo4j/

``` Java
@NodeEntity
public class Movie {
  @GraphId Long id;

  @Indexed(type = FULLTEXT, indexName = "search")
  String title;

  Person director;

  @RelatedTo(type="ACTS_IN", direction = INCOMING)
  Set<Person> actors;

  @RelatedToVia(type = "RATED")
  Iterable<Rating> ratings;

  @Query("start movie=node({self}) match 
          movie-->genre<--similar return similar")
  Iterable<Movie> similarMovies;
}
```

Thanks,
Michail

**Comment by lvca** [comment]
Would you like to contribute to the https://github.com/orientechnologies/spring-data-orientdb project?

**Comment by zifnab87** [comment]
Are there small todos so it could get me started? I don't know if OGM annotations could be the easiest but I would be interested in those. Given my busy schedule I cannot guarantee commitment at this point but I could give it a try :)

**Comment by lvca** [comment]
Spring data is up & running project, closing it.
