### ISSUE TITLE
Queries taking longer when it hits the same node which is under load

### ISSUE THREAD

**Issue by machinelearner** [orientechnologies/orientdb#3829]
sample query:
``` select from Subject where ( _id='a@b,com'  tenantId='testTenant )```

hits a coomposite index(UniqueIndex) on _id and tenantId

Same query when run on a less loaded instance takes the same time initially but subsequent requests are at acceptable  sub-second response. 
```
Stressed node: 2.5sec to respond
Free node: 0.173sec to respond

Subject is an abstract class. Snippet of list classes


 Group | Subject | 13,21,33,58,72,92,101,118,129,140 | 16009 |
 User   | Subject | 12,25,42,57,66,81,95,115,133,146   |   2929 |
```
Running 2.0.5 and 3 node cluster default configuration using hazelcast

**Comment by machinelearner** [comment]
is there a way to avoid this problem by getting a load balancing capabilities for the Orientdb java client? so that it does not hit the same node for all queries.

**Comment by lvca** [comment]
This is the issue to refer: https://github.com/orientechnologies/orientdb/issues/3165

**Comment by lvca** [comment]
Duplicated of #3165.
