### ISSUE TITLE
OCommandGremlin collection return bug

### ISSUE THREAD

**Issue by Nialit** [orientechnologies/orientdb#3830]
OrientDB 2.0.5
Blueprints 2.6.0

I am quering remote db via gremlin from Java like this:

``` java
OrientBaseGraph graph = OrientGraphFactory.getNoTx(); \\a bit of pseudocode in this line
OGremlinHelper.global().setMaxGraphPool(100).create();

String query = "g.E().groupBy{it.weight}{it}.cap.next()";
OCommandGremlin cmd = new OCommandGremlin(query);
Object tt = graph.command(cmd).execute();
```

Everything is ok and result is correct when query doesn't contain groupBy clause. 
I suppose that the problem is in returning a collection of elements except Vertices or Edges(collection of Vertices\Edges is returned ok), because the returned Iterable has right number of elements, corresponding to the groups count or another non-Vertex\edge elements. But all the elements are nulls.
E.g. this works:

``` gremlin
g.E.filter{ it.weight != 3}.weight[4]
```

and this does not:

``` gremlin
g.E.filter{ it.weight != 3}.weight[1..4]
```

but the size of returned Iterable is 4(for second exemple query), full of nulls. In case of groupBy query the size of array returned is corresponding to groups, that should be fetched out.
Iterable's size corresponds to real groups count, but contains nulls. So, it probably is correctly fetched, but incorrectly returned. 
My application depends on this functionality much and I greatly appreciate your efforts on fixing it and would be glad to render all my support.
Thanks.

**Comment by lvca** [comment]
@Nialit Please could you retry with 2.1.2?

**Comment by Nialit** [comment]
Retried, error still there.

**Comment by lvca** [comment]
Please could you provide me the DDL to create the database where I can run the same query?

**Comment by Nialit** [comment]
Yes, of course!
Sql for preparing DB:
```SQL
insert into V set weight = 2
insert into V set weight = 3
```
gremlin query that works in Java:
```gremin
g.V.weight[0]
```


gremlin query that returns null in Java:
```gremin
g.V.weight[0..1]
```

Some of Java code dragging data:
```Java
String query = "g.V.weight[0..1]";
OrientDynaElementIterable tt = graph.command(cmd).execute();
if (tt.iterator().hasNext())
	    System.out.println(tt.iterator().next()); //NullPointerException here
```
