### ISSUE TITLE
OrientDB 1.7.8 fails to start in AIX in pLocal mode

### ISSUE THREAD

**Issue by shajigopal** [orientechnologies/orientdb#3831]
The snappy-java 1.1.0.1 library throws the following error on start-up:
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=AIX and os.arch=ppc64

When I upgraded snappy to snappy-java 1.1.1.6 and tried, it started without any issues.

Please recommend if this is a known issue and is fixed in any version after 1.7.8?

**Comment by lvca** [comment]
In 2.0 we don't use snappy anymore by default. Could you upgrade to 2.0.5?
