### ISSUE TITLE
OCommandExecutorNotFoundException when trying to insert using select

### ISSUE THREAD

**Issue by nooruls143** [orientechnologies/orientdb#3832]
Hi,
 I am trying to insert data by running select query 

    insert into Inf_Price from (select from Inf_Price where storeRefKey = 76)

on Orient Studio but I am getting the following error:

    com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.(select from Inf_Price where storeRefKey = 76)

It is a simple copy from the same class. Can you please check this issue

**Comment by luigidellaquila** [comment]
Hi,

just try removing the round braces:

insert into Inf_Price from select from Inf_Price where storeRefKey = 76



2015-03-30 7:59 GMT+02:00 nooruls143 <notifications@github.com>:

**Comment by daanv1987** [comment]
[The SQL insert documentation](http://orientdb.com/docs/last/SQL-Insert.html) has as example: 
>INSERT INTO GermanyClient FROM ( SELECT *, true AS copied FROM Client WHERE country = 'Germany' )

I had to find this issue to know what the 'solution' was. A solution that is inconsistent with other sub-select queries. Please change the documentation or allow round braces in this sub select query.
