### ISSUE TITLE
SQL IN with no values in the parameter causes major memory leak

### ISSUE THREAD

**Issue by dshurt** [orientechnologies/orientdb#3835]
When passing empty list to an IN clause it results in a java.lang.OutOfMemoryError: Java heap space
It appears that memory is leaked as the 'Old Gen' fills and doesn't seem to clear out.

Version: 1.7.10
Query example: 

'select from A where name IN :nameList'
Pass an empty list to the mapped parameter.  

Workaround: 
Avoid making the query if there's no IN list.

I haven't tested other versions...so it may only apply to this version.

**Comment by tglman** [comment]
i tried this with 2.0 and  2.1-SNAPSHOT and i couldn't reproduce it, closing
