### ISSUE TITLE
Binary protocol returns incorrect 'virtual' recordids 

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#3836]
All details can be found at
https://github.com/codemix/oriento/issues/294

Since I thought it was a oriento bug at first. But @phpnode told me it is a bug in orientdb.

**Comment by mrft** [comment]
Related to this ticket are a few (currently unanswered) questions I have about the necessity of treating subselects as virtual records, instead of just inlining them.

https://groups.google.com/forum/?pli=1#!topic/orient-database/XIkV6z_P1wQ

**Comment by lvca** [comment]
We already fixed this problem in 2.0.x. Have you tried 2.0.6? In this case the temporaty RIDs are never reused.

**Comment by mrft** [comment]
It's not fixed in 2.0.6.

Please try the query for yourself and add it to the test-suite.

**Comment by lvca** [comment]
What's the result of the query? Could you post the json here, please?

**Comment by mrft** [comment]
<pre>
[
  {
    "type": "p",
    "content": {
      "classId": 0,
      "type": "d",
      "cluster": -2,
      "position": 0,
      "version": 0,
      "value": {
        "@type": "d",
        "in": "Garcia",
        "in2": "artist"
      }
    }
  },
  {
    "type": "r",
    "content": {
      "classId": 0,
      "type": "d",
      "cluster": -2,
      "position": 0,
      "version": 0,
      "value": {
        "@type": "d",
        "name": "HEY BO DIDDLEY",
        "x_sungby": [
          "#-2:0"
        ]
      }
    }
  }
]
</pre>

**Comment by tglman** [comment]
we should avoid to return not unique temporary rid, this fix https://github.com/orientechnologies/orientdb/issues/3360 also make sure that we send on the network only one record with a specific rid, so this means we may loosing some query result replacing them with the first found result.
this is strictly related to the binary protocol, in case of rest we return a nested json, and in case of embedded it remain the tree in memory, so the only case that is effect by this issue is binary protocol.

**Comment by tglman** [comment]
by the way @mrft,
trying your query:
```
select name, $sungbyrecord as x_sungby 
from V 
let $sungby = outE()[ @class = 'sung_by' ], 
    $sungbyrecord = list( (select in.name, in.type from $sungby ) ) 
where name='HEY BO DIDDLEY'
```
i found out that we had a data problem in the DB that you can fix it running:
```
alter class sung_by superclass E
```
and
```
alter class written_by superclass E
```

done this you can change your query in:
```
select name, out('sung_by') from V where name='HEY BO DIDDLEY'
```
and this doesn't have that problem

**Comment by mrft** [comment]
Possibly, but 

out('sung_by') 

is not the same as   

name, type

as I am selecting in my query

**Comment by tglman** [comment]
I checked with the last version of the database and of orient, temporary id are still there but are not used for send the record back because that record are embedded in the parent record in the result set, so this issue is closed.
