### ISSUE TITLE
OrientDB(2.0.5): Error in restoring the Database through plocal

### ISSUE THREAD

**Issue by SampathTele** [orientechnologies/orientdb#3838]
Having an issue in V2.0.5, I'm able to take back up using backup command through plocal successfully. While restoring database with zip file its giving an error that "uncompromising database.ocf file :
The process cannot access the file because another process has locked the file.".  I'm checked that any other process is locking that datafbase.ocf file. Found no other process is locking that.
I have uploaded the screen shots to know exactly what is issue.
  
![backup](https://cloud.githubusercontent.com/assets/11735655/6917672/4d6ba4fc-d7c4-11e4-8e37-5feb5916fa7f.png)

![restore](https://cloud.githubusercontent.com/assets/11735655/6917687/72df838e-d7c4-11e4-85b6-f976ed632edc.png)

**Comment by lvca** [comment]
Seems a configuration problem of permissions on directories and running OrientDB console or servers.
