### ISSUE TITLE
Orient(1.7.6):Facing error connecting  to database through plocal after connecting through Java Application

### ISSUE THREAD

**Issue by SampathTele** [orientechnologies/orientdb#3839]
Facing an issue in v1.7.6. What i have done is connected to a database using plocal through Java application created a schema and closed db connection in application. After that I'm not able access the database from console.bat  plocal and remotely. Application only able to connect to the Database. Some how console unable to load database configuration. I have added code and screen shots for better understanding. 

![cretingdatabase](https://cloud.githubusercontent.com/assets/11735655/6918326/d605196e-d7ca-11e4-948c-01c9e0cb5d83.png)

public static void main(String[] args) {
		ODatabaseDocumentTx db = new ODatabaseDocumentTx("plocal:C:/adtran/adtran3rd/orientdb/databases/TeleDB");
		try
		{
		db.open("admin", "admin");
		OClass vertexSuperClassInstance= db.getMetadata().getSchema().getClass("V");
		
		OClass newClass = db.getMetadata().getSchema().createClass("Emp",vertexSuperClassInstance);
		db.commit();
		db.close();
		System.out.println("Hello");
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
			e.printStackTrace();
			db.close();
			
		}
	}

![dbconnection](https://cloud.githubusercontent.com/assets/11735655/6918333/f27acb48-d7ca-11e4-9bc3-e1adcdd8b213.png)

**Comment by lvca** [comment]
It's because in 1.7.x by default storage remains open. Try setting this at startup of your JVM:

```java
OGlobalConfiguration.STORAGE_KEEP_OPEN.setValue(false);
```
