### ISSUE TITLE
Deadlock issue on mass update

### ISSUE THREAD

**Issue by johnmelba** [orientechnologies/orientdb#3841]
If we execute the update statement that modified lots of records, then OrientDB locks itself. The ONewLockManager maintains array of 512 locks and for some reason assigns same lock id for records with different ids. That causes deadlock and only recovery is system restart.

**Comment by laa** [comment]
Could you provide script which you use for mass update ?

**Comment by laa** [comment]
If you prefer , you may send thread dump instead . Probably it should be enough .

**Comment by lvca** [comment]
@johnmelba any news on this?

**Comment by kowalot** [comment]
Please check it

``` java
/// part of TestQueryRecordLockUnlock

  @Test
  public void testMassUpdate_Regression3841_3631() throws InterruptedException {
    ODatabaseDocumentTx db = null;
    final String targetDB = "memory:testMassUpdate_Regression3841_3631";
    final int recordsCount = 1024;// more than lock buckets
    try {

      db = new ODatabaseDocumentTx(targetDB);
      if (db.exists()) {
        db.open("admin","admin");
        db.drop();
      }
      db.create();


      // prepare records for locking all buckets
      for (int x = 0;x<recordsCount; x++ )
      {
        ODocument doc = new ODocument();
        doc.setClassName("Doc");
        doc.field("count", 1);
        doc = db.save(doc);
      }

      db.commit();
    } finally {
      if (db != null)
        db.close();
    }
    int scans = 20;

    ExecutorService pool = Executors.newFixedThreadPool(10);
    for (int i = 0; i < scans; i++) {
      pool.submit(new Runnable() {

        @Override
        public void run() {
          ODatabaseDocumentTx db = null;
          try {
            db = new ODatabaseDocumentTx(targetDB);
            db.open("admin", "admin");
            String asql = "update Doc INCREMENT count = 1 RETURN AFTER LOCK RECORD ";
            db.command(new OCommandSQL(asql)).execute();
            Thread.sleep(50);
          } catch (Exception e) {
              e.printStackTrace();
          } finally {
            db.close();
          }
        }
      });
    }
    pool.shutdown();
    pool.awaitTermination(20, TimeUnit.SECONDS);

    db = new ODatabaseDocumentTx(targetDB);
    db.open("admin", "admin");
    OResultSet<ODocument> res = db.query(new OSQLSynchQuery<Object>("SELECT SUM(count) FROM Doc"));
    final int sumNum = res.get(0).field("SUM");
    Assert.assertEquals(sumNum,recordsCount*(scans+1));
    db.close();

  }


```

**Comment by johnmelba** [comment]
@Luca, as we discussed over chat, I've provided all the information to @laa earlier. This issue is created to make sure that our problem is getting fixed while you are making changes for WAL refactoring / enhancement. The original mail trail was concluded with @laa stating http://www.prjhub.com/#/issues/189 is going to fix it.

**Comment by laa** [comment]
Hi, according  to our chant we agreed that it is not deadlock and that updates are slow because of serial nature of locks in WAL. Do you agree with this ?

**Comment by kowalot** [comment]
@laa please try my test case and you will get full picture what's going on.

**Comment by laa** [comment]
I run now with big lock timeout let see what we get.

**Comment by laa** [comment]
Reproduced, I am on it.

**Comment by kowalot** [comment]
Big thanks! I added some information here #3631 . I think they could be partially relevant to this issue.

**Comment by laa** [comment]
Fixed.  Could you try from devleop branch ?

**Comment by johnmelba** [comment]
We were waiting for the fix for last 2 months and it was prioritized for next major release stating its WAL issue. Now did it get fixed in 5 hrs? At that time I provided the test case that was very similar to one provided by @kowalot . What I could have done differently to get issue fixed earlier? Also can you shed some light on what was fixed? That should boost my confidence on the fix.

**Comment by lvca** [comment]
@johnmelba This is the fix accordingly to GitHub: https://github.com/orientechnologies/orientdb/commit/dc3738149eb835c5951e7f80190877faa10090ed

**Comment by kowalot** [comment]
@laa I checked it and it works. Thank you!
