### ISSUE TITLE
User can't change his record in OUser

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3842]
There is very good feature of OrientDB: ability to use OrientDB security for in app authorization and security stuff. (Discussed there: #2229)

But there are few things that prevent using this feature for the full power:

1) A user (except admin) can't modify his record in OUser. For example he can't change his password.
2) A user has access to SHA password and other information for other users.

Imho, security for OUser, ORole and inherited classes should be changed. Main thoughts:

1) User should have RW access to his record except changing of roles
2) OUser should be inherited from ORestricted to allow more granular security. For example: in some cases `select from OUser` should return just 1 record for an user, but whole set of user for admin - and so on.

What do you think?

**Comment by lvca** [comment]
@PhantomYdn About:
1) This is not possible now because you can't limit changes to only certain fields. However this could be implemented in `OUserTrigger`
2) Makes sense, but I should execute some test if everything is ok

**Comment by lvca** [comment]
This has ben fixed today: you can't browse ouser anymore. However updating current OUser could be dangerous, also changing the user's name could have impacts at application level.

**Comment by PhantomYdn** [comment]
Can't browse OUser? But what about systems which use OUser/ORole for user management? Sounds scarry...

**Comment by lvca** [comment]
@PhantomYdn it's all configurable. reader & writer cannot read users anymore, but you can decide the permissions to assign. So in your app you could configure that users have READ permission ;-)

**Comment by PhantomYdn** [comment]
Got it! Thanks! Wil check. Am I right that in case of READ permission I will be able to Read only "myself" if I'm not admin? Honestly, it will be cool to have that configurable... There are applications which everybody should see everybody: like forums. But for others just limited set of other users should see you. I have in plans to play with ORestricted on OUser...

**Comment by lvca** [comment]
In theory (only partially tested), you can let OUser to extend ORestricted and this would be or free.
