### ISSUE TITLE
HTTP POST Property ignore linkedType

### ISSUE THREAD

**Issue by twittek** [orientechnologies/orientdb#3843]
First, there might be a mistage in the manual (2.0)
10.7 HTTP API

Multiple property creation
{
  "fieldName": {
      "propertyType": "<property-type>"
  },
  "fieldName": {
      "propertyType": "LINK",
      "linkedClass": "<linked-class>"
  },
  "fieldName": {
      "propertyType": "<LINKMAP|LINKLIST|LINKSET>",
      "linkedClass": "<linked-class>"
  },
  "fieldName": {
      "propertyType": "<LINKMAP|LINKLIST|LINKSET>",
      "linkedType": "<linked-type>"
  }
}

The last element "<LINKMAP|LINKLIST|LINKSET>" should be "<EMBEDDEDMAP|EMBEDDEDLIST|EMBEDDEDSET>", in combination with linkedType.

And this linkedType (e.g. STRING) will be ignored, but works with a sql command.

**Comment by lvca** [comment]
I didn't understand the purpose of the command above.

**Comment by twittek** [comment]
Sorry the content is now missing in my post, all the "" are empty - this makes no sense. I try it again!

First, there might be a mistage in the manual (2.0)
10.7 HTTP API

Multiple property creation
{
  "fieldName": {
      "propertyType": "\<property-type>"
  },
  "fieldName": {
      "propertyType": "LINK",
      "linkedClass": "\<linked-class>"
  },
  "fieldName": {
      "propertyType": "\<LINKMAP|LINKLIST|LINKSET>",
      "linkedClass": "\<linked-class>"
  },
  "fieldName": {
      "propertyType": "\<LINKMAP|LINKLIST|LINKSET>",
      "linkedType": "\<linked-type>"
  }
}

The last element "\<LINKMAP|LINKLIST|LINKSET>" should be "\<EMBEDDEDMAP|EMBEDDEDLINKLIST|EMBEDDEDLINKSET>", in combination with linkedType.

And this linkedType (e.g. STRING) will be ignored, but works with a sql command.

**Comment by twittek** [comment]
Example:

I post to http://myorientdb:2480/property/CMDB/Server/

{
  "ipAddress": {
      "propertyType": "\<EMBEDDEDLIST>",
      "linkedType": "\<STRING>"
  }
}

A property will be created, but without a linkedType.

but
create property Server.ipAddress EMBEDDEDLIST STRING
works great!

**Comment by luigidellaquila** [comment]
Hi @twittek 

Are you sending the strings with angular braces?
Did you try the following:

```
{
  "ipAddress": {
      "propertyType": "EMBEDDEDLIST",
      "linkedType": "STRING"
  }
}
```

Thanks

Luigi
