### ISSUE TITLE
Orient Graph API - setProperties(Object... fields) doesn't save vertex changes

### ISSUE THREAD

**Issue by G4br13l3** [orientechnologies/orientdb#3844]
Managing a OrientGraphNoTX through Graph API the method setProperties(Object... fields) doesn't save the vertex changes unless vertex.save() method is explicitily called.
This issue doesn't appear setting a single property through the method setProperty(String key, Object value), beacause the save operation is implicit.

	OrientGraphFactory factory = new OrientGraphFactory(this.graphDBUrl);
	OrientGraphNoTx orientGraph = factory.getNoTx();
	Map<String,Object> props = new HashMap<String,Object>();
	props.put("name", "Jill");
	props.put("age", 33);
	props.put("city", "Rome");
	props.put("born", "Victoria, TX");
	vertex.setProperties(props);

	vertex.save(); // ESSENTIAL!

The issue of course doesn't involve transactional graph.

**Comment by lvca** [comment]
It's now a bug, but how it works. Javadocs says:

```
(Blueprints Extension) Sets multiple properties in one shot against Vertices and Edges. This improves performance avoiding to save the graph element at every property set.
```

I've added now the additional line:

```
After calling this method, the vertex is dirty and need to be saved by calling the {@link #save()} method.
```

To make things clearer.

**Comment by tglman** [comment]
actually to keep this conform to all the rest of the api we should call save, the setProperty call save, so also setProperties should call save from my point of view. i would suggest a reopen with a line fix and relative test case.

**Comment by lvca** [comment]
I agree. We should rename setProperties() in setPropertiesInternal that doesn't save, and setProperties() should call it + save(). I take it.

**Comment by wcraigtrader** [comment]
You may want to consider back-porting this to 2.0.X.

**Comment by lvca** [comment]
Done ;-)
