### ISSUE TITLE
Incoherence when inserting property defined as string

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3845]
```sql
create class Person 
create property Person.name string

insert into Person set name = true
insert into Person set name = false
insert into Person set name = 0
insert into Person set name = {}
insert into Person set name = []
# all the above work (they shouldn't?)
insert into Person set name = randomName # this doesn't as expected
```
```sql
select from Person
```
![screen shot 2015-04-01 at 12 19 18](https://cloud.githubusercontent.com/assets/4520516/6939849/77e371c0-d868-11e4-9e5e-44244fb9e006.png)

**Comment by lvca** [comment]
The string type does a .toString() of the input value. That's why is allowed now. @luigidellaquila is this already fixed in 2.1?

**Comment by luigidellaquila** [comment]
@lvca what's the expected fix?
All the statements pass, they all do a toString() of the property except last one, that just stores null (randomName is not defined, so it's evaluated to null)

**Comment by lvca** [comment]
Ok, so the behavior is expected. @vitorenesduarte is it clear for you current behavior?

**Comment by vitorenesduarte** [comment]
Yes @lvca.
Although it's weird. I was expecting it would only accept strings.
Thanks for clarifying it.
