### ISSUE TITLE
Autosharding section in doc

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#3848]
Sorry , autosharding section in the last documentation is not present. 
It is a error ? or is changed the orientdb setting ?

**Comment by lvca** [comment]
With Distributed cfg, the sharding is up to the developer. OrientDB will select the cluster local to the server node where the client is connected. Look at "Cluster Locality" in http://www.orientechnologies.com/docs/last/Distributed-Sharding.html. In the next releases we'll provide auto-sharding strategies in bundle.
