### ISSUE TITLE
Case insensitivity: OClass.propertiesMap()

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3853]
For almost all properties methods OrientDB use case insensitive approach. For example the following calls will return the same(prerequisite: myClass has "mySuperProperty" property):

```java
myClass.getProperty("mySuperProperty");
myClass.getProperty("mysuperproperty");
myClass.getProperty("MYSUPERPROPERTY");
```

but OClass.propertiesMap() will return HashMap with property name as an key. So only first call from the following will return not null;

```java
myClass.propertiesMap().get("mySuperProperty");
myClass.propertiesMap().get("mysuperproperty");
myClass.propertiesMap().get("MYSUPERPROPERTY");
```

What's the idea to have such map? Might be it's better to make all keys lower case? Otherwise it's hard to use this method in reality... What do you think?

**Comment by tglman** [comment]
i see your point, but that is a public api, people may relay on this behavior, i think is better create an additional api, or change this in a major version, by the way i'm quite sure that this will not land in 2.1 due to the fact that we are really close to the final, moving to 2.2

**Comment by PhantomYdn** [comment]
I've already workaround that, so major version will be OK. Honestly,I don't think that people use this method because of mentioned issue. Or someone might use just for lowcase params, but it means that there will no impact for this case.

**Comment by lvca** [comment]
I think it's correct propertiesMap returns the map as is. The getProperty(), instead, works case insensitive. Did I miss your point?

**Comment by PhantomYdn** [comment]
The point is in fact that this map become useless. To use a map you should definetly know original case.

**Comment by lvca** [comment]
Properties are case sensitive, so it's correct if you want all the properties that they are returned with their name. Example: `dateOfBirth`
