### ISSUE TITLE
Namespaced classnames

### ISSUE THREAD

**Issue by shekhei** [orientechnologies/orientdb#3854]
I have a couple of use cases where by it would be beneficial for me to share a db between different services, for example, one model in a "db" might be more effectively filtered when I "join" the data from another "db", so, either I build a separate service just for these search, or, I "join" them, for example

BaseService contains a person's information
Application1 contains some information on whether this person has activated this service provided by application1
Application1 needs to filter according to some application1.person.activiation_status + baseservice.person.signup_location(a simplified filter)

It would be really beneficial if I could use "namespaces", in such case, I would not need to have a central governance thingy to care about things as granular as "typenames".

Another case would be, sharing a db, and storing migration information in the db. For example, oriento stores them under a classname "Migration", although I would change the classname, it would easily become confusing, and not very "generic".

But of course, I could separate them into different db and I could potentially reduce this possible problem of clashing class names, or perhaps putting all the migrations and class designs into a central governance kinda model, and then, build a search layer that we "index" them.

However, that is a huge hassle and I would lose the benefits of "graphs".

Namespaces however, would solve such issues,

baseservice.user
baseservice.migration
application1.user
application1.migration

and so on.

Any plans on implementing something like this?

**Comment by lvca** [comment]
No more relevant, closing it.
