### ISSUE TITLE
Unexpected server behavior when token expires

### ISSUE THREAD

**Issue by dcarr178** [orientechnologies/orientdb#3864]
Running binary network protocol on orientdb server 2.0.5, storing server token on client and re-using it for multiple requests works fine. However, if enough time elapses (15 minutes I think but can't be sure) between server requests then token expires and orientdb server does not return a message and close the connection. Instead, the socket_read just hangs and eventually times out. In testing, I can get the same thing to happen if I append a character to the end of a valid token like this:

$this->db = new PhpOrient(env('orientDB_HOST'),2424, $orientdbSessionToken . 'a');
$this->db->query("select from V limit 10");

Expected behavior: when token expires or server receives unrecognized token then it should return an error message and close the connection.

**Comment by lvca** [comment]
@dcarr178 Sorry this is an issue of PHP driver. Please could you open the same very issue under: https://github.com/orientechnologies/PhpOrient/issues ?

**Comment by dcarr178** [comment]
Will do. Thanks
