### ISSUE TITLE
Gremlin queries close database for session

### ISSUE THREAD

**Issue by kstock** [orientechnologies/orientdb#3866]
An initial gremlin query works, but any subsequent queries causes the following error:

com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/orientdb-community-2.0.6/databases/GratefulDeadConcerts' is closed

This affects the REST API and the studio. you can do more queries by reconnecting to the database and starting a new session.

I've noticed this bug in 2.0.5 and 2.0.6
---
How to replicate:

1) connect to a database in the studio
2) execute g.V[0]
3) execute g.V[0] again

----
This was noted on the google group:
"I encountered the same problem after updated from 2.0.3 to 2.0.5, if you update studio page, then connection is reestablished correctly, so after every gremlin query you need to press f5. Database is not closed probably, merely studio connection drops.  I think it's a new bug, have to make an issue on github." - Natal Kaplya 

https://groups.google.com/forum/#!searchin/orient-database/gremlin|sort:date/orient-database/pwLOhbN7U-k/sw5m_4V_PDEJ

**Comment by lvca** [comment]
Reproduced.

**Comment by ruliana** [comment]
Work correctly for us in 2.0.4
