### ISSUE TITLE
ORecordAbstract<T>  model

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#3867]
I m seeing ORecordAbstract<T>  that contains     bytearray   _source;
So every orecord loaded by database/client is all in memory. 
In the most of cases, it is surely right but with big data (big file for example) it can create a outofmemory.
The solution to split binary in chunks is good but it can fulfill all orientdb cluster (where is saved files)  with few big files (but a huge number of chunks), so the design of this part of database dont scale pratically in the same way as the remaing part of database. Anyway , chunks could be used for for files biggers then 2gb. 
In addition this solution is strongly dependent by maximun machine space: pratically i can load 1 gb file just if machine have this memory space  and, aboveall, if i have the luck that in the same time no other people are asking big data. 
For big data  i suggest to add a new class (for example ORecordStream) to remove _source and open inputstream for reading or outputstream for output directly with datatabase when client is asking for it : so client and server use always few memory space also for big data and in every context. 
if i open a branch and 
1) i rename (using refactor tool) ORecordAbstract<T> in  ODocumentAbstract<T>, so ODocument extends now ODocumentAbstract<T>  and all as before. 
2) i add in OSerializableStream the methods 
    OutputStream toSteam
    fromStream(inputStream iStream) 
3) i introduce a new middle class  ORecordAbstract<T> over  ODocumentAbstract<T>  without _source reference(  i purge duplicated code if necessary)  and rewriting  toStream() and  fromStream methods, so classes hierarchy is consistent. 
4) i refactor class ORecordBytes (or create a new class ORecordStream) extends ORecordAbstract<Closeable>( or ORecordAsbtract<OSerializableStream>) 
 where 
- Closeable is the common interface of inputstream and outputstream,  
- ORecordAbstract2 is equals to ORecordAbstract  rewrites  toStream() and  fromStream methods
.... 

You know better the code deeply and all the parts ... Could this solution work?
If it works i can offer this integration freely, working in the few free time i have got.

**Comment by lvca** [comment]
@publicocean0 this is not possible today, because we have 2 different layers between database/record and storage. Storage works with byte[] and all the internal cache and paging works with byte[].
