### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by lacivert** [orientechnologies/orientdb#3878]
I remember this happened yeras ago when I first started to try OrientDB and I remember someone solved this problem but now I see it happens again (may be about another cause)

I create a class called "Kisi", it creates the class well. But then I cannot reach the class by its name "Kisi". I can only reach it by with only capital letters "KİSİ"

Be careful on the İ letter. It has a dot on it. It is uppercase of "i" in Turkish, and there is another letter "ı" (without dot) in Turkish and its uppercase version is "I" (without dot)

### i → uppercase → İ

So, there is a problem on OrientDB Studio. It may or may not only happen in Studio.

By the way, to be more specific check this:
http://blog.codinghorror.com/whats-wrong-with-turkey/
https://msdn.microsoft.com/en-us/library/ms973919.aspx#stringsinnet20_topic5

**Comment by lacivert** [comment]
Now I realize that it happens on "insert" command but there is no problem on "select" queries.

I created a class by this query:

    create class Kisi extends V

Then I try to insert some records:

    insert into Kisi (ad,soyad) values ("A","B")

I get this error message:

    com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #11: Class KISI not found in database Command: insert into Kisi values ("A","B") -------------------^

As you see, I write "Kisi" but it parses the class name as "KISI" and problem occurs. But somehow, select has no problem on it:

    select * from Kisi

So I guess query parsers has some different methods on this.

**Comment by luigidellaquila** [comment]
fixed in develop branch
