### ISSUE TITLE
Test Env: move all ANT tests to MAVEN

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3883]
Do also:
- [ ] Code Coverage
- [ ] Support also creation of GratefulDeadConcerts database (now with `ant clean install -Dorientdb.test.env=ci`)

**Comment by tglman** [comment]
this can be considerate closed, the code coverage is not there, but i prefer open another issue about it, waiting just for get all test passed on jenkins and remove the old ant tests.

**Comment by tglman** [comment]
test on jenkins are pretty fine in last few days, closing
