### ISSUE TITLE
Sql Functions parameters

### ISSUE THREAD

**Issue by maggiolo00** [orientechnologies/orientdb#3886]
Parameters in sql functions are not properly binded

**Comment by nagarajasr** [comment]
i still see there is an issue when passing parameter to function call within a sub-query:
i have created simple test to reproduce the issue:

https://gist.github.com/nagarajasr/2dc4995b9a8067b3c617

i am using OrientDB 2.0.8

**Comment by luigidellaquila** [comment]
Hi @nagarajasr 

this issue was addressed in 2.1, it will be available soon as a stable release
