### ISSUE TITLE
Transactions design

### ISSUE THREAD

**Issue by danfma** [orientechnologies/orientdb#3888]
Hey guys,

I saw that the API thas a Transaction property which I can batch some commands. Did the Orientdb has some other way to work with transactions? Something like in RDBMS world where I can begin and then commit or rollback after any operation in that scope? Or the transactions are only write only batches in OrientDB?

(I was using the .NET Client)

**Comment by lvca** [comment]
OrientDB supports ACID tx like RDBMS, but I think the .NET driver doesn't support this feature but work only in batch mode.

**Comment by danfma** [comment]
Can I simulate the ACID calls using the HTTP protocol? (I am thinking in write a new one client)

**Comment by lvca** [comment]
Unfortunately the HTTP, for its nature, is stateless, so it has no state.

**Comment by GoorMoon** [comment]
.Net Driver support transactions via remote protocol not batch
