### ISSUE TITLE
collate case-sensitive

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3890]
field set up with collate to case-insentive doesn't work for following query. 

The following 1 and 2 will be treated differently due to case-sensitive. 

1. select expand(out('target')[venue = 'singapore') from news
2. select expand(out('target')[venue = 'Singapore') from news

The following 3 and 4 will work identically. 
3. select from place where venue = 'singapore'
4. select from place where venue = 'Singapore'

**Comment by lvca** [comment]
When you use projections you loose the collate, because that value is the result of an expression. I suggest you to use .toLowerCase() and compare it with a lowered case string.
