### ISSUE TITLE
OCommandExecutorNotFoundException on simple record copy

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#3897]
Hi,

I am using Orient 2.0.5 and trying to make the copy example work. Here's my command:

```
insert into User from ( select from Tenant where @rid = #12:0 )
```

This produces the following error:

```
Error: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.( select from Tenant where @rid = #12:0 )
```

Record ```#12:0``` is in database. User class is a simple class without any properties defined or restricted (i.e. just a shell).

**Comment by lvca** [comment]
Remove parenthesis

**Comment by lvca** [comment]
However this isn't the first time the very same report happens. Can we check the docs about it? Or maybe support also this syntax?

**Comment by andreyvk** [comment]
That worked very well, thank you!

**Comment by andreyvk** [comment]
Hi @lvca,

There's another problem which I stumbled upon right away. I'd like to return ```@rid``` or ```@this``` after query executes, but apparently I cannot do that.

```
insert into User from (select from Tenant where @rid = #12:0) return @this
```

gives initial error and the the other one without parenthesis

```
insert into ActionLog from select from Tenant where @rid = #12:0 return @this
```

throws the following at me:

```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #38: Invalid keyword 'RETURN'
Command: select from Tenant where @rid = #12:0 RETURN @this
----------------------------------------------^
```

What do i do?

**Comment by andreyvk** [comment]
Hi @luigidellaquila, 

Regarding my question above. Is there any workaround that I can use in this case?

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

have you tried this?

```insert into ActionLog return @this from select from Tenant where @rid = #12:0 ```

**Comment by andreyvk** [comment]
Hi @luigidellaquila,

That works well actually. Thanks!
