### ISSUE TITLE
Javascript dynamic hook question

### ISSUE THREAD

**Issue by Bretto** [orientechnologies/orientdb#3898]
In a dynamic hook in Javascript how can you reference the current object on which the hook is being applied, let's say a createdAt hook, how do i get a ref to the instance in the functions management of Studio ?

**Comment by lvca** [comment]
You can access to the variable "doc" referring to the current document/record.

**Comment by lvca** [comment]
@Bretto, please use the Community Group to ask questions: https://groups.google.com/forum/#!forum/orient-database
