### ISSUE TITLE
Suggestion: use bloomfilter in traverse algorithm

### ISSUE THREAD

**Issue by CasperWW** [orientechnologies/orientdb#3901]
Currently the 'traverse' method speed is limited to 
- A. the lookup of the index engine (SB-Tree, Lucence, etc.) 
- B. the speed of communication with the Java client (network link).
- C. The Java 'Set' data structure which has O(N). 
I want to suggest a bloomfilter which has O(1) complexity. The bloomfilter resizes on disk and does not fill the client memory. Sole problem is that you must specify the size of the bloomfilter up front.

**Comment by laa** [comment]
Why do you thing that set has O(N) complexity, could you elaborate more about this ?

**Comment by CasperWW** [comment]
Assuming OrientDB currently uses the HashSet.
``` 
This class offers constant time performance for the basic operations (add, remove, contains and size), assuming the hash function disperses the elements properly among the buckets. 
Iterating over this set requires time proportional to the sum of the HashSet instance's size (the number of elements) plus the "capacity" of the backing HashMap instance (the number of buckets)
```
(see http://docs.oracle.com/javase/8/docs/api/java/util/HashSet.html)

**Comment by laa** [comment]
How iteration is related over set is related to traverse ? Do we use iterators there ?

**Comment by CasperWW** [comment]
Excuse me for my incompleteness. No, recursion is used:

```
private boolean traverse(Object iTarget, final OSQLFilterCondition iCondition, final int iLevel,
                             final Set<ORID> iEvaluatedRecords, final OCommandContext iContext) {
        if (endDeepLevel > -1 && iLevel > endDeepLevel)
            return false;

        if (iTarget instanceof OIdentifiable) {
            if (iEvaluatedRecords.contains(((OIdentifiable) iTarget).getIdentity()))
                // ALREADY EVALUATED
                return false;
```

**Comment by laa** [comment]
Correct me if I wrong but we use contains which is O(1) , it is lookup method, not iteration method.

**Comment by CasperWW** [comment]
You're completely correct. Time for a break.. Sorry for wasting your time.

**Comment by laa** [comment]
No problem, thank you that you are taking care about our project.
