### ISSUE TITLE
Export and import with empty data

### ISSUE THREAD

**Issue by unQualsevol** [orientechnologies/orientdb#3905]
Hello,

I'm using the export and import functionalities and I found the following issue.
If I export records and there is no record the content of the exported file is 
<code>{"records":[]}</code>
That's right.
Then if I do an import with a file containing this the following exception is throwed:

>Error on database import happened just before line 0, column 14
>com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content '': content must be between { }
>	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.unwrapSource(ORecordSerializerJSON.java:399)
>	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:173)
>	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:169)
>	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecord(ODatabaseImport.java:1237)
>	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecords(ODatabaseImport.java:1187)
>	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:425)

In my way of think any exported file by OrientDb export process should be imported with the OrientDb import process.

In my case is not a big problem because I have to filter the entries before import them.

Thank you for your efforts!

**Comment by lvca** [comment]
Have you tried with 2.1.2?

**Comment by unQualsevol** [comment]
Hi! I don't know, I changed project and now I'm not using OrientDB anymore...
Thank you for reply!
See you!

**Comment by lvca** [comment]
Fixed in v2.1.1.
