### ISSUE TITLE
default property doesn't work with roles orientdb-community-2.1-SNAPSHOT

### ISSUE THREAD

**Issue by Bretto** [orientechnologies/orientdb#3910]
Setup
```
CREATE CLASS User extends OUser
CREATE PROPERTY User.created datetime    
ALTER PROPERTY User.created default sysdate() readonly
ALTER PROPERTY User.roles default [#4:2] readonly
```
POST Request
```
http://localhost:2480/document/test

content
{
@class: "User"
name: "Brett"
password: "root"
status: "ACTIVE"
}
```
Error
com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.roles' has been declared as LINKSET but an incompatible type is used. Value: [#4:2].field( readonly)

the 'created' property works as expected

**Comment by tglman** [comment]
fixed with the refactor of validation closing
