### ISSUE TITLE
Can't create unique fulltext index.

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#3914]
Hi,
it is possible to create a LUCENE index and an unique index on a property?
Use case: I want the power of lucene to search for my vertexes but I also want the restriction that no other vertex has the same property value.

My morkaround is: `CREATE INDEX users.Id unique` and then use the sql `LIKE` keyword.

**Comment by lvca** [comment]
We removed this option because OrientDB indexes were much more efficient on this.

**Comment by vitorenesduarte** [comment]
I believe this was also reported here #3354 (which, aparently, it's not considered a bug anymore).
I don't understand why the index is not triggered if I explicitly write `LUCENE`.
