### ISSUE TITLE
delete edge in distributed mode not working

### ISSUE THREAD

**Issue by AlexFiverr** [orientechnologies/orientdb#3917]
hey, 

I asked about this issue several times, and after seeing other people struggling with it, I think it is a bug and not some wrong config on my part. 

when trying to delete vertex/edge in a 3 node cluster, i get: 
```
2015-04-09 10:13:13:387 WARNING [orientdb01] detected 2 node(s) in timeout or in conflict and quorum (3) has not been reached, rolling back changes for request (id=504320 from=orientdb01 task=command_sql(DELETE EDGE FROM $buyer_vertex to $order) userName=) [ODistributedResponseManager]
2015-04-09 10:13:13:387 WARNING [orientdb01] Quorum 3 not reached for request (id=504320 from=orientdb01 task=command_sql(DELETE EDGE FROM $buyer_vertex to $order) userName=). Timeout=9ms Servers in timeout/conflict are:
 - orientdb02: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.DELETE EDGE FROM $buyer_vertex to $order
 - orientdb03: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.DELETE EDGE FROM $buyer_vertex to $order
Received: {orientdb02=com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.DELETE EDGE FROM $buyer_vertex to $order, orientdb01=com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.DELETE EDGE FROM $buyer_vertex to $order, orientdb03=com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.DELETE EDGE FROM $buyer_vertex to $order} [ODistributedResponseManager]
```

every other time...

I am using REST API against version 2.0.6 of orientdb. 
I am running in a 3 node cluster. 
hazelcast configuration:
```
<hazelcast
        xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.0.xsd"
        xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <group>
                <name>graph</name>
                <password>*****@</password>
        </group>
        <network>
                <port auto-increment="true">2434</port>
                <join>
                        <multicast enabled="false">
                                <multicast-group>235.1.1.1</multicast-group>
                                <multicast-port>2434</multicast-port>
                        </multicast>
                        <tcp-ip enabled="true">
                                <member>orientdb01:2434</member><member>orientdb02:2434</member><member>orientdb03:2434</member>
                        </tcp-ip>
                </join>
        </network>
        <executor-service>
                <pool-size>16</pool-size>
        </executor-service>
</hazelcast>
```

the default-distributed-dg-config.json:
```
{
    "autoDeploy": true,
    "hotAlignment": true,
    "executionMode": "asynchronous",
    "readQuorum": 1,
    "writeQuorum": 2,
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "*": {
            "servers" : [ "orientdb01","orientdb02","orientdb03","<NEW_NODE>" ]
        }
    }
}
```

**Comment by lvca** [comment]
The problem seems the command:

    DELETE EDGE FROM $buyer_vertex to $order

How did you execute this? Variables are not resolved.

Furthermore don't use `hotAlignment :true` on current release. See also: http://orientdb.com/docs/last/Distributed-Architecture.html

**Comment by AlexFiverr** [comment]
@lvca - this command is part of a full transaction: 

["LET $buyer_vertex = UPDATE User CONTENT {id: 1, name: 'alex' } UPSERT RETURN AFTER @rid WHERE id=1",                    
"LET $seller_vertex = UPDATE User CONTENT {id: 2, name: 'luca' } UPSERT RETURN AFTER @rid WHERE id=2",
"LET $order = UPDATE Order CONTENT {id: 3, amount: 20} UPSERT RETURN AFTER @rid WHERE id=3", 
"DELETE EDGE FROM $buyer_vertex to $order",
"DELETE EDGE FROM $seller_vertex to $order",
"CREATE EDGE bought FROM $buyer_vertex TO $order",
"CREATE EDGE sold FROM $seller_vertex TO $order"]

passed to the /batch route through the REST API.

waiting for your reply. thanks.

**Comment by lvca** [comment]
@AlexFiverr are you using any driver or HTTP directly? If it's plain HTTP, could you send the entire payload you send to the server?

**Comment by AlexFiverr** [comment]
plain http. 
payload:
data = { 
        'transaction': true,  
        'operations': [
          { 'type': 'script',
            'language': 'sql',
            'script': ["begin","LET $buyer_vertex = UPDATE User CONTENT {id: 1, name: 'alex' } UPSERT RETURN AFTER @rid WHERE id=1", "LET $seller_vertex = UPDATE User CONTENT {id: 2, name: 'luca' } UPSERT RETURN AFTER @rid WHERE id=2","LET $order = UPDATE Order CONTENT {id: 3, amount: 20} UPSERT RETURN AFTER @rid WHERE id=3", "DELETE EDGE FROM $buyer_vertex to $order","DELETE EDGE FROM $seller_vertex to $order","CREATE EDGE bought FROM $buyer_vertex TO $order","CREATE EDGE sold FROM $seller_vertex TO $order", "'commit retry 200"] }]}

**Comment by AlexFiverr** [comment]
@lvca  - waiting for your input on this matter. thanks :)

**Comment by lvca** [comment]
If you manually control the TX, set `'transaction': false`

**Comment by AlexFiverr** [comment]
changed it, did not help. 
still getting the exception.

**Comment by lvca** [comment]
I found a `'` before the commit. Please could you double check it?

**Comment by AlexFiverr** [comment]
this was just a copying error on my part, anyway i changed to this:

```
data = { 
        'transaction': true,  
        'operations': [
          { 'type': 'script',
            'language': 'sql',
            'script': ["LET $buyer_vertex = UPDATE User CONTENT {id: 1, name: 'alex' } UPSERT RETURN AFTER @rid WHERE id=1", 
"LET $seller_vertex = UPDATE User CONTENT {id: 2, name: 'luca' } UPSERT RETURN AFTER @rid WHERE id=2",
"LET $order = UPDATE Order CONTENT {id: 3, amount: 20} UPSERT RETURN AFTER @rid WHERE id=3", 
"DELETE EDGE FROM $buyer_vertex to $order",
"DELETE EDGE FROM $seller_vertex to $order",
"CREATE EDGE bought FROM $buyer_vertex TO $order",
"CREATE EDGE sold FROM $seller_vertex TO $order"] }]}
```

getting same result on the delete command...

**Comment by AlexFiverr** [comment]
any updates on this ?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Comment by lukeasrodgers** [comment]
Not sure if it's exactly the same issue, but we were having problems with `delete edge RELATIONSHIP from RID` (also to RID), running in distributed mode. For records with many relationships, the query would hang, CPU would spike on all nodes, and ultimately orientdb would become response, and starting logging out-of-memory errors.

Is this a known issue with the performance of that command?

**Comment by lvca** [comment]
@lukeasrodgers what release are you using?

**Comment by lukeasrodgers** [comment]
@lucaolivari 2.1.5
