### ISSUE TITLE
import CSV problem

### ISSUE THREAD

**Issue by yongshengpang** [orientechnologies/orientdb#3920]
import from CSV problem .This json file do not work in UTF-8 encoding in windows7 X64, chinese
                  
E:\orientdb-community-2.0.6\bin>oetl.bat e:\import\ppe.json
OrientDB etl v.2.0.6 (build @BUILD@) www.orientechnologies.com
Exception in thread "main" com.orientechnologies.orient.core.exception.OSerializ
ationException: Error on unmarshalling JSON content '?{
    "source": {
        "file": {
            "path": "E:/import/CCB_CFA2014.csv"
        }
    },
    "extractor": {
        "row": {}
    },
    "transformers": [
        {
            "csv": {
                "nullValue": "Null",
                "columns": [
                    "帐簿:string",
                    "资产类型:string",
                    "期初数标志: string"
                ]
            }
        },
        {
            "vertex": {
                "class": "ppe"
            }
        }
    ],
    "loader": {
        "orientdb": {
            "dbURL": "plocal: E:/orientdb-community-206/databases/nndb",
            "dbAutoCreate": true,
            "dbType": "graph",
            "wal": false,
            "classes": [
                {
                    "name": "ppe",
                    "extends": "V"
                }
            ],
            "indexes": [
                {
                    "class": "ppe",
                    "fields": [
                        "资产编号: string"
                    ],
                    "type": "UNIQUE"
                }
            ]
        }
    }
}': content must be between { }
        at com.orientechnologies.orient.core.serialization.serializer.record.str
ing.ORecordSerializerJSON.unwrapSource(ORecordSerializerJSON.java:399)
        at com.orientechnologies.orient.core.serialization.serializer.record.str
ing.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:173)
        at com.orientechnologies.orient.core.record.ORecordAbstract.fromJSON(ORe
cordAbstract.java:165)
        at com.orientechnologies.orient.core.record.impl.ODocument.fromJSON(ODoc
ument.java:1649)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.jav
a:145)

**Comment by lvca** [comment]
Please, could you provide me the input file (just 2-3 lines) and the etl.json?

**Comment by yongshengpang** [comment]
thanks.

import file utf-8 encoding (CCB_CFA2014.csv):

帐簿,资产类型,期初标志
CCB_信用卡_账簿,CAPITALIZED,10192531
CCB_信用卡_账簿,CAPITALIZED,10192532

ppe.json ： do not work in UTF-8 encoding.

{
      "source": {
               "file": {
                        "path": "E:/import/CCB_CFA2014.csv"
                }
      },
      "extractor": {
                "row": {}
     },
     "transformers": [
          {
               "csv": {
                          "nullValue": "Null",
                          "columns": [
                                   "帐簿:string",
                                   "资产类型:string",
                                   "期初数标志: string"
                           ]
                        }
          },
         {
               "vertex": {
                        "class": "ppe"
                }
         }
    ],
    "loader": {
           "orientdb": {
                 "dbURL": "plocal: E:/orientdb-community-206/databases/nndb",
                 "dbAutoCreate": true,
                 "dbType": "graph",
                 "wal": false,
                 "classes": [
                      {
                           "name": "ppe",
                           "extends": "V"
                      }
                ],
                "indexes": [
                     {
                          "class": "ppe",
                          "fields": [
                                      "资产类型: string"
                           ],
                          "type": "UNIQUE"
                     }
                 ]
            }  
     }
}

**Comment by yongshengpang** [comment]
E:\orientdb-community-2.1-rc1\bin>oetl.bat e:\import\ppe.json
OrientDB etl v.2.1-rc1 (build @BUILD@) www.orientechnologies.com
Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigur
ationException: Error on creating ETL processor
        at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.ja
va:277)
        at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.ja
va:185)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.jav
a:160)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Canno
t create database 'nndb'
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.cre
ate(ODatabaseDocumentTx.java:422)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.cre
ate(ODatabaseDocumentTx.java:332)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(
OrientGraphFactory.java:128)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(
OrientGraphFactory.java:111)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getNoTx(Orie
ntGraphFactory.java:90)
        at com.orientechnologies.orient.etl.loader.OOrientDBLoader.configure(OOr
ientDBLoader.java:270)
        at com.orientechnologies.orient.etl.OETLProcessor.configureComponent(OET
LProcessor.java:493)
        at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.ja
va:250)
        ... 2 more
Caused by: java.lang.IllegalStateException: Location passed in WAL does not exis
t, or IO error was happened. DB can not work in durable mode in such case.
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OD
iskWriteAheadLog.<init>(ODiskWriteAheadLog.java:669)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OD
iskWriteAheadLog.<init>(ODiskWriteAheadLog.java:611)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocal
PaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:283)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.create(OAbstractPaginatedStorage.java:227)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocal
PaginatedStorage.create(OLocalPaginatedStorage.java:112)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.cre
ate(ODatabaseDocumentTx.java:354)
        ... 9 more
E:\orientdb-community-2.1-rc1\bin>

**Comment by lvca** [comment]
Seems the db path doesn't exist.
