### ISSUE TITLE
Docs - easy fix

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3922]
[Here](http://orientdb.com/docs/2.0/orientdb.wiki/Distributed-Sharding.html#define-the-target-clustershard) we have:
```sql
INSERT INTO Client CLUSTER:client_usa SET name = 'Jay'
```
which does not seem to work. 
Maybe:
```sql
INSERT INTO CLUSTER:client_usa SET name = 'Jay'
```

**Comment by lvca** [comment]
Thanks, done: https://github.com/orientechnologies/orientdb-docs/wiki/Distributed-Sharding

**Comment by vitorenesduarte** [comment]
:+1:
