### ISSUE TITLE
bad value for embedded string

### ISSUE THREAD

**Issue by seeden** [orientechnologies/orientdb#3923]
Next query:

```js
UPDATE #17:0 SET title = "He \\said \"hello\".", paragraphs= [
    {
        "@type": "document",
        "@class": "BlogAParagraphs",
        "subTitle": "He \\said \"hello\"."
    }
] RETURN after @this
```

Will produce:
```js
title: "He \said \"hello\"."
paragraphs: [{
    "subTitle": "He \\\\said \\\"hello\\\".",
}]
```
FYI: title and subTitle have a type string, paragraphs is embedded list of abstract class

As you can see there is a bad value for subTitle. I guess that you are forgeted unescape subdocument. There is a problem with characters: " and \

**Comment by luigidellaquila** [comment]
Hi @seeden 

which OrientDB version?

**Comment by seeden** [comment]
2.0.4 - 2.0.6

**Comment by luigidellaquila** [comment]
Hi,

this issue is a duplicate of #3449
Closing, please track the other one
