### ISSUE TITLE
import csv data to orientdb, the speed issue

### ISSUE THREAD

**Issue by rwnew2012** [orientechnologies/orientdb#3927]
Hi, I am importing data from four csv files (which are grabbed from SQL server) to orientdb, each represents a vertex class  and has more than a hundred thousand rows, and might even more edges bwteen them but this is depends on joinIDs. 

e.g, I have, A.json, B.json, C.json,
and C.json have edge info, between A to C and B to C,  (building edges by specifying lookup and jointFieldname in json file if I understand correctly).

I created vertices A and B without any problems and the process is fast. I oetl C.json after A.json and B.json have been oetled.

The issue is that, it is very slow to be oteled to orientdb, probably will take 60 days to finish oetling the C.json. is this the correct way to do that? that normal, how to speed it up? 

Another question is, does the order really matter, could I oetl the json files when edge info included but lookup field class has not been oetling yet. I tried it, and it creates a column in vertiex table instead of directly to edge tables. Then if it is faster, that is no problem, How to create the edge by selecting two columns of vertices. because right now it throws errors to me and create edge will just be fully connectted when list of vertices are provided. Thanks so much!

**Comment by rwnew2012** [comment]
forgot to provide hardware info that I am running this,

a laptop, not distributed system, 64G memory, 1TB disk. what is the way to finish it in a reasonable time by using only one laptop? Thanks

**Comment by lvca** [comment]
What's the throughput in terms of vertices/edges per second? Did you create indexes on fields you're looking up?

**Comment by rwnew2012** [comment]
ahh, that is a good point and I kinda know the problem is. the lookup fields are not indexed, so I put edge info in wrong json files. let me edit the json files

**Comment by rwnew2012** [comment]
Thanks so much, @lvca. the problem is solved. I have two more questions.
1. the order of json files to be oteled, seems important.is that true?
2. if one of json oetl process fails because of unexpected error, right now I need to re-etl previous json files again. Is there way to handle this?

Thanks

**Comment by lvca** [comment]
@rwnew2012 
1. order matters depending by how you're using it
2. with last release (2.0.9-SNAPSHOT and 2.1-SNAPSHOT) you can declare "haltOnErrors":false to let it continue importing
