### ISSUE TITLE
Issue with LIKE used with concatenated params and OR

### ISSUE THREAD

**Issue by peterperron** [orientechnologies/orientdb#3932]
Issue reproduced on versions 2.0.3 and 2.0.7
Reproduced using the java API and also an test OrientDB SQL function.

**Here's a simple example:**
Suppose I have a function receiving one searchText param with the following query

`select * from Client where firstName like '%' + :searchText + '%' OR lastName like '%' + :searchText + '%'`

The combination of the like operation with the concatenation of the param causes the OR to not work properly. In fact, the first filter "firstName" must be true otherwise the whole thing returns false.

**After a lot of tests here's what works:**
If I remove the param and write the search text directly:

`select * from Client where firstName like '%' + 'George' + '%' OR lastName like '%' + 'George' + '%'`

*Notice here that I kept the useless concatenation just to make sure that this wasn't the issue...*

If I use 2 parameters with different names and pass them the same search text:

`select * from Client where firstName like '%' + :searchText1 + '%' OR lastName like '%' + :searchText2 + '%'`

For the moment, we fixed it by doing string concatenation in code instead of passing a param...

**Comment by luigidellaquila** [comment]
fixed in develop branch
