### ISSUE TITLE
On master with strictSql enabled, SQL query fails because of escaped newline

### ISSUE THREAD

**Issue by stuartcarnie** [orientechnologies/orientdb#3933]
```
{
  "transaction": true, 
  "operations": [
    {
      "type": "script", 
      "language": "sql", 
      "script": [
        "let $d0 = INSERT INTO Country SET name=\"one\\ntwo\" RETURN @rid", 
        "return { n0 : $d0 }"
      ]
    }
  ]
}
```

**Comment by stuartcarnie** [comment]
It's works fine with 2.0.7, and correctly stores and retrieves the encoded newline

**Comment by luigidellaquila** [comment]
Hi @stuartcarnie 

how are you executing this query?
I have a test case on develop branch that passes correctly, so maybe it's due to the rest of the stack (console, REST call?)

Thanks

Luigi

**Comment by stuartcarnie** [comment]
It was a REST call

**Comment by luigidellaquila** [comment]
fixed in develop branch
