### ISSUE TITLE
It's possible to have shards and unique indexes?

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3939]
Hi,
I was testing how the indexes behave with shards and noticed that is possible to have **two records** with the same **unique** property.
My schema:

``` sql
ALTER DATABASE MINIMUMCLUSTERS 3

create class User extends V
create property User.name string
create index User.name unique
alter cluster user_0 name user_usa
alter cluster user_1 name user_eur
alter cluster user_2 name user_chi
```
- [hazelcast.xml](https://gist.github.com/vitorenesduarte/8f821d50a0cb8a000d30)
- [default-distributed-db-config.json](https://gist.github.com/vitorenesduarte/72247455623aac1d083c)

[This code](https://gist.github.com/vitorenesduarte/4f6586491fe17a8808a5) will reproduce it. 
The output is:

``` bash
0 : ok
1 : ok
2 : ok
3 : ko -> result : [mike, mike]
4 : ko -> result : [mike, mike]
5 : ko -> result : [mike, mike]
```

Start first node **usa** so that its port is **2424**. Then **eur** -> **2425**. Then **chi** -> **2426**.

After the first insert (on **chi** node), I believe this is what happens:
- Node **eur** see that it does not have a record with name **mike** and asks node **usa** if it has, but it doesn't (only **chi** node has a record with name **mike**).
- As **writeQuorum** is **2**, the record is inserted.

My question is: if it's an unique index, shouldn't the **writeQuorum** be disrespected, and check all nodes?

**v2.0.7**
Logs:
- [usa node](https://gist.github.com/vitorenesduarte/7aa65dd80393b3dffbba)
- [eur node](https://gist.github.com/vitorenesduarte/3171727a7455fe52e2fc)
- [chi node](https://gist.github.com/vitorenesduarte/7b579538ad80c5c15919)

**Comment by lvca** [comment]
This is not supported yet.

**Comment by lvca** [comment]
This will be supported in v3.0 with the autosharded index. In v2.2 we already have a local implementation, in v3.0 will be supported in distributed mode to have a regular DHT.

**Comment by hossein-md** [comment]
Hi @lvca 
I have tried this issue to reproduce the result with the version 2.2.33. I can't!
But  I could after I had changed my Orientdb version to 2.0.7.
I don't understand why it happens. ( This is my problem that I mention in #8234 )
