### ISSUE TITLE
Critical bug with Lucene index, sql parser.

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#3941]
Hello,
I found a strange issue with the lucene `fulltext` index. I create a `fulltext` lucene index on the `DisplayName` property in my `Node` class. When I start a query against this property - orientdb involves the fulltext index with the wildcard option '*' even though I didn't use it. This results in a wrong result set.

Another issue in the beginning of the gif informs me about a wrong command executor o_O called `Bernd Eck` This describes another issue in the sql parser.

` SEVERE Internal server error:
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.'Bernd Eck' [ONetworkProtocolHttpDb]`

**Gif:** https://drive.google.com/file/d/0B2vAA9xbTc4WY3ROMXFvUjFiUUU/view?usp=sharing

OrientDB Server v2.0.2

**Comment by maggiolo00** [comment]
Hi @StarpTech 
which version of OrientDB?

**Comment by StarpTech** [comment]
@maggiolo00 OrientDB Server v2.0.2

**Comment by maggiolo00** [comment]
How can i replicate this?
do you have some queries?

**Comment by StarpTech** [comment]
Look at the gif in the comment.

**Comment by maggiolo00** [comment]
The problem is that you select in studio 'Bernd Eck' from the sql editor and run the query with selection. It is normal that is giving that error

**Comment by maggiolo00** [comment]
For lucene index you have to use the lucene operator

select from Node where DisplayName lucene 'Some text'

**Comment by StarpTech** [comment]
ok, I dont know that selection works. It is a little bit confusing. But the first error still occurs.
It seems it has somehting to do with the space in the 'DisplayName' property.

When Im looking for vertexes with the `DisplayName = 'Bernd'` I found my item but when another item exist with the same value in his `DisplayName` and separated with a space in the property they found both.

`select from Node where DisplayName = 'Karl'`
```
{
    "result": [
        {
            "@type": "d",
            "@rid": "#18:271",
            "@version": 164,
            "@class": "Node",
            "DisplayName": "Karl",
            "Email": "karl@local",
            "Points": 10,
            "Position": "Member",
            "Active": true,
            "Created": "2015-04-16 20:28:09",
            "SponsoredBy": "#19:21",
            "References": [
                "#18:274",
                "#18:273",
                "#18:272"
            ],
            "in_BroughtIntoRight": [
                "#23:117"
            ],
            "InsertedAtDepth": 0,
            "out_BroughtIntoLeft": [
                "#22:154"
            ],
            "out_BroughtIntoRight": [
                "#23:118"
            ],
            "Mid": "55301b5dc958ddc80bc9b24d",
            "@fieldTypes": "Created=t,SponsoredBy=x,References=n,in_BroughtIntoRight=g,out_BroughtIntoLeft=g,out_BroughtIntoRight=g"
        },
        {
            "@type": "d",
            "@rid": "#12:0",
            "@version": 1,
            "@class": "Node",
            "DisplayName": "Karl eck"
        }
    ],
    "notification": "Query executed in 0.012 sec. Returned 2 record(s)"
}
```

Then I rename the vertex to `Karleck` and retry the query it works.

**Comment by maggiolo00** [comment]
We have this bug opened
https://github.com/orientechnologies/orientdb-lucene/issues/44
to prevent lucene index to be used with = operator

**Comment by StarpTech** [comment]
Does exist any workaround to use the fulltext search without lucene?

**Comment by maggiolo00** [comment]
There is the native fulltext
http://orientdb.com/docs/last/FullTextIndex.html

**Comment by StarpTech** [comment]
Thanks
