### ISSUE TITLE
OrientDB Jepsen & Hermitage Test 

### ISSUE THREAD

**Issue by atrniv** [orientechnologies/orientdb#3944]
Hi,

I just ran into OrientDB while looking for an alternative to FoundationDB.  I would really love to see some information on how orient performs on the Jepsen and Hermitage tests. It would really give me a lot of confidence in making a decision to switch to OrientDB from our existing setup which consists of (Redis, Cassandra, Couchbase & MongoDB).

**Comment by shekhei** [comment]
+1

**Comment by atvictor** [comment]
+1

**Comment by spscacyost** [comment]
+1

**Comment by StarpTech** [comment]
+1

**Comment by eugene-kamenev** [comment]
+1

**Comment by oillio** [comment]
+1

**Comment by Overbryd** [comment]
+1

**Comment by smolinari** [comment]
+1

**Comment by shekhei** [comment]
any news on this?

**Comment by StarpTech** [comment]
@lvca

**Comment by StarpTech** [comment]
Good for reference https://github.com/ept/hermitage

**Comment by WnP** [comment]
+1

**Comment by smolinari** [comment]
Here is the repo for the Jepsen tests. https://github.com/aphyr/jepsen

Scott

**Comment by lvca** [comment]
Hi guys,
We have an external contributor that started working on it. Unfortunately (at least for me) Jepsen test suite is written in Clojure and it's not that easy to work with. Anybody would like to help us by spend some time on it ?

**Comment by smolinari** [comment]
I have no idea about Clojure, so sorry. I'm out.

Scott

**Comment by StarpTech** [comment]
This guy can analyse orientdb when nobody will be found.
http://jepsen.io/

**Comment by luigidellaquila** [comment]
Hi guys,

A quick update on this: we staffed some resources to work on this internally, hopefully we will be able to give some further updates soon

Thanks

Luigi

**Comment by francoisprunier** [comment]
Hi @luigidellaquila,

Could you let us know where you are on this ? Any tests running ? Bugs found ?

Thanks
Francois

**Comment by lvca** [comment]
Unfortunately there is no Clojure skill in OrientDB. It would be great if somebody can help us on doing it. Any volunteer?

**Comment by StarpTech** [comment]
@lvca As already mentioned the author of http://jepsen.io/ is able to do such tests.

**Comment by bermi** [comment]
Hi @luigidellaquila, @lvca,

Has there been progress on this front recently? Is this still waiting for volunteers? Have you contacted with @aphyr to run the tests for you?

Thanks,

Bermi

**Comment by elimisteve** [comment]
Would definitely love to see how OrientDB fares against the Jepsen test barrage!

**Comment by dumblob** [comment]
Also very much interested in this. The DB world nowadays kind of considers Jepsen tests as the very bare minimum to even consider a DB for any (even small) production use.
