### ISSUE TITLE
cluster schema

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3945]
for version 2.0.6
Cluster schema is no longer inherited when doing sql insert.
this happen after i did export and then import database.

this statement will inherited schema
1. INSERT INTO log cluster log_visit  set ......

this statement will not work
2. insert into cluster:log_visit set.......................

**Comment by lvca** [comment]
If you insert into `cluster:` directly, it's up to you setting class. Try this:

```sql
insert into cluster:log_visit set @class = 'log'
```

**Comment by martingg88** [comment]
wow...it's working..
can i set @class for every insert or update query?

**Comment by lvca** [comment]
you can't for update but only on inserts.

**Comment by martingg88** [comment]
@lvca the following query will not longer work due to the issue from this link https://github.com/orientechnologies/orientdb/issues/4168 . Any idea? 
FYI. this issue is for version 2.1-rc3

insert into cluster:log_visit set @class = 'log'

**Comment by luigidellaquila** [comment]
Hi @martingg88 

no, this query will not work anymore with the new parser.
Every cluster belongs to only one class, so you cannot set it explicitly.
You can just remove the ```set @class = 'className'``` and everything will work fine

**Comment by martingg88** [comment]
I'm confused about every cluster belongs to only one class? I though it suppose to have one class that may have more than one clusters. isn't it?

Come to this issue. if i remove the set @class = 'className' for insert operation then cluster schema is no longer inherited anymore.

**Comment by lvca** [comment]
The following 2 statements aren't opposite:
- every cluster belongs to only one class
- one class that may have more than one clusters

So you cannot share a cluster with multiple classes, and yes, a class can have multiple clusters.

**Comment by martingg88** [comment]
so how to make sure the cluster will always inherited schema. should i need to add @class when doing insert or update operation?
