### ISSUE TITLE
ConcurrentModificationException when using OCommandScript

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3948]
I was running something like [this](https://gist.github.com/vitorenesduarte/0b60aa309605a291accf) when I got this exception.
The [server log](https://gist.github.com/vitorenesduarte/9a2f9159e5ac5b08849f) for this example.

**Comment by lvca** [comment]
@vitorenesduarte Thanks for the test case. I changed a couple of lines of code to get it working: get the graph from the pool when the thread is running, so it's bound to that thread. ``` package com.orientechnologies.orient.test;

import java.io.IOException;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.orientechnologies.orient.client.remote.OServerAdmin;
import com.orientechnologies.orient.core.command.script.OCommandScript;
import com.orientechnologies.orient.core.intent.OIntentMassiveInsert;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OSchema;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.orientechnologies.orient.core.sql.query.OSQLSynchQuery;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
import com.tinkerpop.blueprints.impls.orient.OrientVertex;

public class TestOCommandScript {

  private static final Logger logger               = Logger.getLogger(TestOCommandScript.class.getName());
  private static final String URL                  = "remote:localhost/Testing";
  private static final int    SOURCE_TARGET_NUMBER = 1000;
  private static final int    BATCH_SIZE           = 1000;
  private static final int    NUMBER_OF_EDGES      = 10000;

  public static void main(String[] args) throws IOException {
    test(1);
    test(4);
  }

  private static void test(int N_THREADS) throws IOException {
    dropDBIfExists(URL, "root", "root");
    createDBIfDoesNotExist(URL, "root", "root");
    OrientGraphFactory pool = new OrientGraphFactory(URL, "admin", "admin").setupPool(0, 64);
    createSchema(pool.getNoTx());

    OrientGraph graph = pool.getTx();
    try {
      graph.declareIntent(new OIntentMassiveInsert());
      Integer sourceClusterID = null, targetClusterID = null;

      for (int i = 1; i <= SOURCE_TARGET_NUMBER; i++) {
        OrientVertex source = graph.addVertex("class:Source", "name", "source" + i);
        OrientVertex target = graph.addVertex("class:Target", "name", "target" + i);
        if (i % BATCH_SIZE == 0) {
          System.out.println(i);
          graph.commit();
        }
        if (i == SOURCE_TARGET_NUMBER) {
          sourceClusterID = source.getIdentity().getClusterId();
          targetClusterID = target.getIdentity().getClusterId();
        }
      }

      List<String> sourceRIDs = new ArrayList();
      List<String> targetRIDs = new ArrayList();
      for (int i = 0; i < SOURCE_TARGET_NUMBER; i++) {
        sourceRIDs.add("#" + sourceClusterID + ":" + i);
        targetRIDs.add("#" + targetClusterID + ":" + i);
      }

      Thread[] workers = new Thread[N_THREADS];
      for (int i = 0; i < N_THREADS; i++) {
        workers[i] = new EdgeCreator(pool, new ArrayList(sourceRIDs), new ArrayList(targetRIDs), NUMBER_OF_EDGES / N_THREADS);
        workers[i].start();
      }
      for (int i = 0; i < N_THREADS; i++) {
        workers[i].join();
      }

      String query = "SELECT count(*) as count FROM TheEdge";
      Iterable it = graph.command(new OSQLSynchQuery(query)).execute();
      long numberOfEdges = ((OrientVertex) it.iterator().next()).getProperty("count");
      System.out.println("Edge count : " + numberOfEdges);

    } catch (InterruptedException ex) {
      logger.log(Level.SEVERE, null, ex);
    } finally {
      graph.declareIntent(null);
      graph.shutdown();
      pool.close();
    }
  }

  private static class EdgeCreator extends Thread {

    private final OrientGraphFactory graphF;
    private final List<String>       sourceRIDs;
    private final List<String>       targetRIDs;
    private final int                edgesNumber;

    private EdgeCreator(OrientGraphFactory graphF, List<String> sourceRIDs, List<String> targetRIDs, int edgesNumber) {
      this.graphF = graphF;
      this.sourceRIDs = sourceRIDs;
      this.targetRIDs = targetRIDs;
      this.edgesNumber = edgesNumber;
    }

    @Override
    public void run() {
      final OrientGraph graph = graphF.getTx();

      try {
        StringBuilder cmd = new StringBuilder("begin\n");

        SecureRandom random = new SecureRandom();
        for (int i = 1; i <= edgesNumber; i++) {
          int sourceIndex = random.nextInt(SOURCE_TARGET_NUMBER);
          int targetIndex = random.nextInt(SOURCE_TARGET_NUMBER);

          cmd.append("CREATE EDGE TheEdge FROM ").append(sourceRIDs.get(sourceIndex)).append(" TO ")
              .append(targetRIDs.get(targetIndex)).append(" retry 10000\n");
          if (i % BATCH_SIZE == 0) {
            System.out.println(i);
            cmd.append("commit\n");
            graph.command(new OCommandScript("sql", cmd.toString())).execute();
            cmd = new StringBuilder("begin\n");
          }
        }
      } finally {
        graph.shutdown();
      }
    }
  }

  private static void createSchema(OrientGraphNoTx graph) {
    try {
      OSchema schema = graph.getRawGraph().getMetadata().getSchema();
      OClass vClass = schema.getClass("V");
      OClass eClass = schema.getClass("E");

      OClass sourceClass = schema.createClass("Source");
      sourceClass.createProperty("name", OType.STRING);
      sourceClass.setSuperClass(vClass);

      OClass targetClass = schema.createClass("Target");
      targetClass.createProperty("name", OType.STRING);
      targetClass.setSuperClass(vClass);

      OClass theEdgeClass = schema.createClass("TheEdge");
      theEdgeClass.setSuperClass(eClass);

    } finally {
      graph.shutdown();
    }
  }

  private static void createDBIfDoesNotExist(String url, String user, String pass) throws IOException {
    OServerAdmin server = new OServerAdmin(url).connect(user, user);
    if (!server.existsDatabase("plocal")) {
      server.createDatabase("graph", "plocal");
    }
    server.close();
  }

  private static void dropDBIfExists(String url, String user, String pass) throws IOException {
    OServerAdmin server = new OServerAdmin(url).connect(user, pass);
    if (server.existsDatabase("plocal")) {
      server.dropDatabase("plocal");
    }
    server.close();
  }
}
```

**Comment by vitorenesduarte** [comment]
Great. Thanks @lvca !
