### ISSUE TITLE
Proposal to enhance OSecurity

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3950]
Guys,

Right now OSecurity class contains only methods:

1) To create/manage users and roles
2) Grant and revoke security rights

But there is now methods for actual checking of allowance to do something with some object. Functionality for that are spread over the code and some things are quite hard to use out side: for example there is no way to check does this user has access to a document or not.  [Example](https://github.com/OrienteerDW/wicket-orientdb/blob/master/wicket-orientdb/src/main/java/ru/ydn/wicket/wicketorientdb/security/OSecurityHelper.java#L110)

So I propose make following changes/refactoring:

Add methods for checking security rights for a specific user to a specific document. There should be 2 kinds of checks: check according to security rights and if that's OK - additional check according to ORestricted logic.

If you argue against that: please make something with ORestrictedAccessHook.isAllowed() method - it's pretty usable in [real life](https://github.com/OrienteerDW/wicket-orientdb/blob/master/wicket-orientdb/src/main/java/ru/ydn/wicket/wicketorientdb/security/OSecurityHelper.java#L110)

P.S. I can prepare PR if you don't mind.
P.P.S. Btw, it will be cool to have additional read-only group in your organization for active contributors: just to be able to assign issues to somebody outside your employees.

**Comment by lvca** [comment]
+1 about a PR. About contributors team, good idea. Just created it.

**Comment by PhantomYdn** [comment]
Thanks! Just FYI: read only team members can't self-assign issues. (It's highly desirable feature by github community, but still is not realized) So, only real team members can assign issues - including contributors (who is in read-only mode). Simply saying: I can't self assign this issue:)

**Comment by lvca** [comment]
Assigned to you ;-)
