### ISSUE TITLE
select or update edge SQL: is it possible ?

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb#3952]
Hi,
sorry tried to search if this has ever been asked but no luck.

I cannot 'select' nor 'update' edge with sql; ie.
InvitedTo is edge; Collector is vertext;

select from InvitedTo where out = #20:777 //  works fine (where #20:777 is collector's RID).
but:
select from InvitedTo where out = (select from Collector where id ="some-id") // does not work.

same goes for update sql...

I guess this relates to #1114 ...

**Comment by luigidellaquila** [comment]
Hi,

Are you having an error or it just does not return expected results?
have you tried with IN operator?

select from InvitedTo where out IN (select from Collector where id
="some-id")





2015-04-18 2:57 GMT+02:00 SpareShade <notifications@github.com>:

**Comment by lvca** [comment]
Direct updates of edges could cause broken links if the updated fields are `out` and `in`.
