### ISSUE TITLE
RETURN BEFORE keyword doesn't work for DELETE VERTEX

### ISSUE THREAD

**Issue by ramazanpolat** [orientechnologies/orientdb#3953]
While it is OK for UPDATE, RETURN BEFORE doesn't work for DELETE.

this:
    
     DELETE VERTEX user WHERE user_id = "2" RETURN BEFORE

throws: 

    Error on parsing command at position #38: Invalid keyword 'RETURN' Command: select from user where user_id = "2" RETURN BEFORE

**Comment by luigidellaquila** [comment]
fixed in develop branch (2.1)
