### ISSUE TITLE
 error in sub query with $parent.$current

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#3956]
```
select $p from #41:7
 let $p = ( select rid from index:index_1 where key = $parent.$current )

----+-----+----
#   |@RID |$p  
----+-----+----
0   |#-2:1|[0] 
----+-----+----
```

but 

```
select rid from index:index_1 where key = #41:7
```

give rows

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

this should be fixed in 2.1-SNAPSHOT, could you please double check? (or give me some additional info about your db to reproduce the issue)

Thanks

**Comment by lvca** [comment]
Closed because no futher feedback. In case, please comment it.

**Comment by publicocean0** [comment]
Hi , sorry for the delay. I tried with a similar query in my db . It seams to work correctly :)
