### ISSUE TITLE
[ Binary Protocol - OrientDB All versions ] Token Session Expired / Bad Token

### ISSUE THREAD

**Issue by Ostico** [orientechnologies/orientdb#3958]
I report an issue when the token sent by a client is wrong or expired.

The issue is explained here:

https://github.com/orientechnologies/PhpOrient/issues/6

**Comment by tglman** [comment]
hi @Ostico,
I added the error send before the drop of the connection, can you please double check if now is right?

the connection unfortunately should be dropped because we cannot clear the data on the network.

closing this, reopen it if the problem persist.
