### ISSUE TITLE
Javascript function: can't find method OScriptGraphWrapper.query(string)

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#3964]
Executing a database function having this body
```javascript
var db = orient.getGraph();
db.query('SELECT FROM V');
```
raises the following exception:
```
sun.org.mozilla.javascript.internal.EvaluatorException: Can't find method com.orientechnologies.orient.graph.script.OScriptGraphWrapper.query(string). (<Unknown source>#4) in <Unknown source> at line number 4
Can't find method com.orientechnologies.orient.graph.script.OScriptGraphWrapper.query(string). (<Unknown source>#4)
```

**Comment by lvca** [comment]
@red-0ne you should rather use:

```sql
db.command('sql', 'SELECT FROM V');
```

Did you see that API in any part of our documentation?

**Comment by red-0ne** [comment]
Yes that's what I am using. But what about query, I don't mind using `command` but query is sated so many times in documentation.

**Comment by lvca** [comment]
Do you have any pages in documentation, so we can fix it?

**Comment by lvca** [comment]
.query() returns a GraphQuery object to execute TinkerPop Blueprints queries.

**Comment by red-0ne** [comment]
Almost all the examples starting from this section
http://orientdb.com/docs/last/Functions.html#access-to-the-databases-from-functions

**Comment by lvca** [comment]
That's `orient.getDatabase().query()` but it's a different API. Examples with orient.getGraph() are correct.

**Comment by red-0ne** [comment]
Yes, that's true. I misunderstood the exclusive aspect of getDatabase and getGraph.
Thank you very much for your support.
