### ISSUE TITLE
difference function with unexpected result

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#3969]
<pre> 
select *, difference(m2,m1), name from   .... 

----+-----+-----+----+----+----+----------
#   |@RID |rid  |m2  |m1  |name|difference
----+-----+-----+----+----+----+----------
0   |#-2:1|#45:0|[6] |[0] |agos|[0]       
----+-----+-----+----+----+----+----------

 select *, difference(m1,m2),name  from   ....

----+-----+-----+----+----+----+----------
#   |@RID |rid  |m2  |m1  |name|difference
----+-----+-----+----+----+----+----------
0   |#-2:1|#45:0|[6] |[0] |agos|[0]       
----+-----+-----+----+----+----+----------

select  expand(m1)  from ...
0 item(s) found. Query executed in 0.001 sec(s).

select  expand(m2)  from

----+------+-------------------------------------------------------------------------
#   |@RID  |value                                                                    
----+------+-------------------------------------------------------------------------
0   |#-1:-1|a                                                          
1   |#-1:-1b                                                
2   |#-1:-1|c  
3   |#-1:-1|d                                          
4   |#-1:-1|e              
5   |#-1:-1|f
----+------+-------------------------------------------------------------------------

select difference([1,2,3],[1,2])

----+-----+----------
#   |@RID |difference
----+-----+----------
0   |#-2:0|[2]       
----+-----+----------

</pre>

**Comment by luigidellaquila** [comment]
fixed in develop branch
