### ISSUE TITLE
 Unhandled rejection OrientDB.RequestError: Server user not authenticated.

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3970]
i'm facing about following issue even i have set up everything correctly..
this will happen after i log in successfully.
Server user not authenticated.

**Comment by lvca** [comment]
It's not clear what OrientDB version, who is raising this error and in what use case. Please provide more info.

**Comment by martingg88** [comment]
it happen for 2.0.8. this happen when i save my node.js code. feel very strange. let's me check with oriento's guys first as I'm using this oriento library for my remote connection.

**Comment by lvca** [comment]
Any news on this?

**Comment by martingg88** [comment]
let's close about this issue since i have never see this issue again after update to latest orientdb version.

**Comment by lvca** [comment]
Ok, thanks.
