### ISSUE TITLE
Management of the drop of the last cluster of a class

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#3971]
In case of the drop of the last cluster referred by a class, the default cluster of a class should became "default" or should be thrown an error that suggest to drop the class instead.

The today behaviour put the default cluster of the class to -1, that make any operation on the class throw an error.

**Comment by lvca** [comment]
I'd prefer to avoid removing the cluster, because setting the "default" cluster risk to put confusion in the users mind.

**Comment by tglman** [comment]
fixed closing
