### ISSUE TITLE
Alter class name of Edge type can drive to issues on graph navigation

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#3973]
if a class of type Edge is renamed, the out(?) and in(?) navigation function will stop to work, because they rely on the fact that the name of the out/in field in the vertexes are the same of the Edge type, as today is a good solution disable the alter for Edge types.

**Comment by lvca** [comment]
+1 for this solution.

**Comment by lvca** [comment]
Implemented. Supported "UNSAFE" in case the user wanna force it.
