### ISSUE TITLE
Generics: List<E> not saved properly in an OObjectDB

### ISSUE THREAD

**Issue by adufour** [orientechnologies/orientdb#3975]
Hi,
I have a generic `abstract class A<E>` containing a field of type `List<E>` with proper getter and setter.
I then have a sub-implementation `class S extends A<String>`.
Both classes are registered in the db, but when saving an instance of `S` to the db (more precisely, adding an element to an instance that is already stored in the db), I get a 
`SEVERE: Error on creating object of class String`
followed by the expected
`Type String cannot be serialized because is not part of registered entities. To fix this error register this class`
This error does not occur if I don't use generics (i.e. if my field is a `List<String>` instead of `List<E>`).
Any help here?
Thx

**Comment by adufour** [comment]
If it helps, I've just tried with the 2.1 RC1 (to get the stracktrace lines correct), here it is:
`com.orientechnologies.orient.core.exception.OSerializationException: Type String cannot be serialized because is not part of registered entities. To fix this error register this class`
`	at ...object.db.OObjectDatabaseTx.newInstance(OObjectDatabaseTx.java:168)`
`	at ...object.db.OObjectDatabaseTx.newInstance(OObjectDatabaseTx.java:113)`
`	at ...object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:93)`
`	at ...object.db.OObjectLazyList.add(OObjectLazyList.java:102)`

**Comment by tglman** [comment]
should be fixed by this pull request: https://github.com/orientechnologies/orientdb/pull/4359, reopen if still occours
