### ISSUE TITLE
OPartitionedDatabasePoolFactory/OPartitionedDatabasePool does not support Object Database

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#3979]
In 2.0.x,
I get the impression that OPartitionedDatabasePool is the way to go with managing pool connections to orientdb. However, OPartitionedDatabasePool.aquire() only returns ODatabaseDocumentTx. As an enhancement, I would suggest enhancing OPartitionedDatabasePool to support aquiring other types such as OObjectDatabaseTx. Please close this issue if this it not the intention of OPartitionedDatabasePool.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
