### ISSUE TITLE
OrientVertex.addEdge never considers className

### ISSUE THREAD

**Issue by fabriziofortino** [orientechnologies/orientdb#3980]
OrientVertex.addEdge

https://github.com/orientechnologies/orientdb/blob/master/graphdb/src/main/java/com/tinkerpop/blueprints/impls/orient/OrientVertex.java#L850-L944

does not consider className parameter. Instead label parameter is always used as edge class name.

**Comment by lvca** [comment]
Look at:

https://github.com/orientechnologies/orientdb/blob/master/graphdb/src/main/java/com/tinkerpop/blueprints/impls/orient/OrientVertex.java#L890-L892

**Comment by fabriziofortino** [comment]
className is considered only when label is null. When both are specified className is not used anymore. In my opinion if className and label are available it should create an edge of type className with the specified label. Am I wrong?

**Comment by fabriziofortino** [comment]
Look at the test included in my PR.

**Comment by lvca** [comment]
In OrientDB, label and class name are synonyms.

**Comment by lvca** [comment]
Which PR?

**Comment by fabriziofortino** [comment]
#3981

**Comment by fabriziofortino** [comment]
If label and className are synonyms perhaps the API is a bit misleading. What about removing the className parameter and leave just label?

**Comment by fabriziofortino** [comment]
@lvca any thought on this?
