### ISSUE TITLE
including return { f: $val } in SQL script does not return a record with key / value pairs using binary protocol

### ISSUE THREAD

**Issue by stuartcarnie** [orientechnologies/orientdb#3982]
When using the binary protocol, the following SQL script:

```
let res = INSERT INTO V SET name = 'bill' RETURN @rid
return { result: $res }
```

The expected result should be a record type with a key of `result` and a value of type `RID`, instead it simply returns a list of RIDs

However, using the HTTP protocol does return the expected result.

**Comment by lvca** [comment]
The result seems correct (tried with 2.0.x branch):

```json
[
    {
        "@type": "d",
        "@version": 0,
        "result": "#9:7",
        "@fieldTypes": "result=x"
    }
]
```

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
