### ISSUE TITLE
Demo function in docs is not consistent to behaviour

### ISSUE THREAD

**Issue by bvhme** [orientechnologies/orientdb#3987]
_(New to OrientDB)_

I've been trying out making functions in Studio and have found out that when I create the basic `sum(a,b)` function that is in the [docs](http://orientdb.com/docs/last/orientdb.wiki/Functions.html) the behaviour is not the same as it doesn't add a to b but it concat's the strings

Steps to reproduce:
1. Make new function `sum` in Studio, set language to `Javascript` and make parameters `a` and `b`.
2. Body of the function 
```javascript 
  return a + b
```
3. Save
4. Execute with `a` = `1`, `b` = `1`

Expected result: 
`2`

Actual Result:
`11`

Workaround:
Use parseInt() on the variables
```javascript 
  return parseInt(a) + parseInt(b)
```

**Comment by red-0ne** [comment]
It's rather a Studio problem. If you execute the query `SELECT sum(1, 1)` everything should be ok. I suspect Studio to pass the arguments as string.

**Comment by luigidellaquila** [comment]
hi @bvhme 

it's not actually an issue, it's just that Studio passes parameters as strings and Javascript does not make any complaint on types.

**Comment by luigidellaquila** [comment]
I'm keeping this open because I think docs require a little upgrade

**Comment by lvca** [comment]
Updated here: http://orientdb.com/docs/last/Functions.html.
