### ISSUE TITLE
SKIP not working with expand()

### ISSUE THREAD

**Issue by Torwori** [orientechnologies/orientdb#3988]
Consider the following test case:

    create class A extends V
    create class B extends V
    create class C extends V
    create class AB extends E
    create class BC extends E
    insert into A (name) values ('A name')
    insert into B (name) values ('B name 1')  // create 3 of these with different names
    insert into C (name) values ('C name 1')  // create 10 of these with different names
    create edge AB from (select from A) to (select from B)
    create edge BC from (select from B) to (select from C)
This query works nicely:
     `select expand(set(out('AB').out('BC'))) from A where name='A name' limit 3`

However, this returns nothing:
     `select expand(set(out('AB').out('BC'))) from A where name='A name' limit 3 skip 3`

All commands executed using studio on version 2.0.6

**Comment by Torwori** [comment]
The same issue occurs in 2.1-rc1.

**Comment by luigidellaquila** [comment]
Hi @Torwori 

skip-limit constraints work on the target of the query (in this case A). In this example you just have one record in A, so the second query will skip it.

Try this, I think it's what you are looking for

```sql
select from (select expand(set(out('AB').out('BC'))) from A where name='A name') skip 3 limit 3
```

If I missed something please reopen
