### ISSUE TITLE
unique index not enforced on edges

### ISSUE THREAD

**Issue by AlexFiverr** [orientechnologies/orientdb#3990]
Hi, 

I have an edge 'bought' defined like this: 

https://www.dropbox.com/s/jzq46mjdydi2bob/Screenshot%202015-04-21%2022.43.31.png?dl=0

when creating the edge bought between the same user and order: 

https://www.dropbox.com/s/b63mz0f7le3pmni/Screenshot%202015-04-21%2022.44.20.png?dl=0

it gets created, even the unique index is defined.

https://www.dropbox.com/s/f6zj7b6w7ye6rq1/Screenshot%202015-04-21%2022.45.21.png?dl=0

orientdb version 2.0,6

this is something that worked, and all of a sudden stopped working. 
what may be the reason?

**Comment by laa** [comment]
Hi, What do you mean by stops working. Could you provide more details. Like set of steps (expected vs. actual) . Or example of database ?

**Comment by laa** [comment]
One more  thing we changed tx mechanics in rc1 could you try it ?

**Comment by AlexFiverr** [comment]
I don't actually understand the set of operations that caused it, we are struggling with upserting edges for a long time now, and this index was our safeguard for double edges not to be created, but as you can clearly see, edges ARE begin created twice and more between same 2 vertices....

is a temp workaround available for this ?

**Comment by laa** [comment]
Wen do not know reason of issue , so we can not find workaround till we will not identify this reason. Did you use transactions during manipulation of edges ?

**Comment by AlexFiverr** [comment]
I added screenshots of what i did in the orientdb studio, step by step...did you take a look at those?

**Comment by laa** [comment]
Yes, sure , if you do it on database any then yours, you will see no problems. So I need more information. Database itself would be handy. Did you try to recreate the same database with 2.0 RC1 we changed tx mechanics there ? What is content of unique index itself how much edge entries does it contain ?

**Comment by AlexFiverr** [comment]
hey - here is an export of the database

https://gist.githubusercontent.com/AlexFiverr/8d4d1ac0594f82e19918/raw/31ef0a68f9ddc468edaa5c446bc292e8dd63fa4a/gistfile1.txt

hope this helps

do you need anything else?

**Comment by AlexFiverr** [comment]
@laa  - any updates on this please? :)

**Comment by AlexFiverr** [comment]
tried on rc1, can't even create a unique index: 

https://www.dropbox.com/s/n51oao02trt1t2y/Screenshot%202015-04-30%2012.13.33.png?dl=0

**Comment by AlexFiverr** [comment]
@laa - did you have the chance to look at it ? :) 
thanks

**Comment by laa** [comment]
What does it mean that you can not create. You have error or something ?

**Comment by AlexFiverr** [comment]
the button is disabled...

**Comment by tglman** [comment]
@AlexFiverr  i added some tests to be sure that this kind of indexing is working correctly.

also i imported your schema and i run
```
create vertex Order set amount =10 , user_id =1, id =1, seller_id =1 ,status =1
create Vertex User  set id =1 ,email ="some@some.com", status=1,username ="bla"

create edge bought from  #66:0 to #19:0
```
i ran create edge twice and the second time was failing, but i feel like your use case is more complex than this, can you post a list of command for reproduce it?

I've done this on 2.1-rc2

**Comment by tglman** [comment]
for my tests work,  going to close this.
