### ISSUE TITLE
Looping over large dataset and doing loop-nested writing transactions (moved to private)

### ISSUE THREAD

**Issue by cstamas** [orientechnologies/orientdb#3996]

**Comment by cstamas** [comment]
Hi there, we need some advice regarding iterating over potentially large dataset, and narrow-scoped updates during that.

The OrientDB document database layout with expected/assumed cardinalities attached:
http://take.ms/pkqry

FTR we use "plocal" connection (Nexus have OrientDB embedded), and in future we do plan to use distributed features of OrientDB, so factor that in into advice please. I described this in the "environment" assigned to this issue.

We'd like to bulk process components and their belonging assets of a given bucket (or all of them, or just some "cross section" or slice of components). The processing might involve creation/updates of components and assets too, but not all of them have to be updated (ie. one loop cycle might not update, just read).

Some example in pseudo code:
```
loop components
  loop assets
    tx.begin
    // read or write component and asset
	tx.end
  endloop
endloop
```

What is the recommended way to loop a huge table, and perform small-scale, narrow, well targeted updates (so writing transactions) during that loop?

Some example use cases:
- loop/process all component (and their assets) belonging to given bucket
- loop/process some component (and their assets) that match some criteria (criteria would mostly match properties in unique index)
- loop/process some component (and their assets) and insert new assets to most of them
- etc.

What approach you recommend for this case? How to loop over ~1M components, but in the same time have transactions within that loop that would modify the belonging assets and/or create new assets? Would you recommend some Orient specific approach, like Java custom functions are over "plain" SQL and java code? 

We were basically tinkering with following two approaches:

a) Java API
```
loop 'select distinct(group) from components where bucket=?' (~20k)
  loop 'select distinct(name) from components where group=?' (~100)
    loop 'select version from components where group=? and name=?'
	  tx.begin
	  component = 'select from component where bucket=? and group=? and name=? and version=?' (1, unique)
	  if component == null -> continue; // deleted during loop, is okay
	  assets[] = 'select from asset where bucket=? and component=?' (~10)
	  // read/update/create asset
	  // read/update component
	  tx.commit
	endloop
  endloop
endloop
```
Is this possible at all (is writing transaction within loop affecting outer loops)? Also, we could tear down result set sizes by doing some sort of paging, but how stable that paging would be given it spans across writing TXes?


b) Orient Custom Java functions

Something like this, where process() would be our custom Java function. How would this behave in distributed case? What limitations, if any, custom functions have?
```
SELECT process(version) FROM components WHERE components.bucket = ? GROUP BY group,name
```




Thanks in advance.

**Comment by cstamas** [comment]
Hi there, we need some advice regarding iterating over potentially large dataset, and narrow-scoped updates during that.

The OrientDB document database layout with expected/assumed cardinalities attached:
http://take.ms/pkqry

FTR we use "plocal" connection (Nexus have OrientDB embedded), and in future we do plan to use distributed features of OrientDB, so factor that in into advice please. I described this in the "environment" assigned to this issue.

We'd like to bulk process components and their belonging assets of a given bucket (or all of them, or just some "cross section" or slice of components). The processing might involve creation/updates of components and assets too, but not all of them have to be updated (ie. one loop cycle might not update, just read).

Some example in pseudo code:
```
loop components
  loop assets
    tx.begin
    // read or write component and asset
	tx.end
  endloop
endloop
```

What is the recommended way to loop a huge table, and perform small-scale, narrow, well targeted updates (so writing transactions) during that loop?

Some example use cases:
- loop/process all component (and their assets) belonging to given bucket
- loop/process some component (and their assets) that match some criteria (criteria would mostly match properties in unique index)
- loop/process some component (and their assets) and insert new assets to most of them
- etc.

What approach you recommend for this case? How to loop over ~1M components, but in the same time have transactions within that loop that would modify the belonging assets and/or create new assets? Would you recommend some Orient specific approach, like Java custom functions are over "plain" SQL and java code? 

We were basically tinkering with following two approaches:

a) Java API
```
loop 'select distinct(group) from components where bucket=?' (~20k)
  loop 'select distinct(name) from components where group=?' (~100)
    loop 'select version from components where group=? and name=?'
	  tx.begin
	  component = 'select from component where bucket=? and group=? and name=? and version=?' (1, unique)
	  if component == null -> continue; // deleted during loop, is okay
	  assets[] = 'select from asset where bucket=? and component=?' (~10)
	  // read/update/create asset
	  // read/update component
	  tx.commit
	endloop
  endloop
endloop
```
Is this possible at all (is writing transaction within loop affecting outer loops)? Also, we could tear down result set sizes by doing some sort of paging, but how stable that paging would be given it spans across writing TXes?


b) Orient Custom Java functions

Something like this, where process() would be our custom Java function. How would this behave in distributed case? What limitations, if any, custom functions have?
```
SELECT process(version) FROM components WHERE components.bucket = ? GROUP BY group,name
```




Thanks in advance.

**Comment by cstamas** [comment]
Hm, sorry for triple posting, but prjhub initially did not create the issue (hence, description is empty, and cannot edit it), then while creating comment it was unresponsive, and it seems multiple clicks created multiple comments with same content. Delete of comments is not effective either :(

**Comment by jdillon** [comment]
heh, I was just gonna ask why you posted 3 times :-P

**Comment by luigidellaquila** [comment]
Hi Tamas,

This is not properly an issue (I'm going to close it) but rather a
question, so I suggest to move this discussion in the mailing list.
Looping on very large datasets with a single query can be a problem in
current engine implementation, because it could require a lot of memory. As
a first step I suggest you to split the fetch of origins in different pages
(using skip-limit or better filtering on RID ranges, that is more stable).
The same if for transactions, your approach of doing small commits in the
internal loop is a good solution, while doing a single transaction for all
would probably lead to memory problems.

Both Javascript and Java solutions are a good approach, they are supposed
to work fine also in distributed mode.

Luigi



2015-04-23 20:02 GMT+02:00 Jason Dillon <notifications@github.com>:

**Comment by cstamas** [comment]
@luigidellaquila yes, I initially posted this on prj as "question" :) Dunno how it got here too.

Thanks for hints, I _assumed_ also that single loop will not do. Will take a peek at RID range paging as stability of "paging" was one of the issues I was tinkering about. I did keep TX "small scale" on my mind, that part is cool then. Thanks!
