### ISSUE TITLE
Wrong Long (64bit Integer) stored in database

### ISSUE THREAD

**Issue by nightrise** [orientechnologies/orientdb#4002]
Hi all,

So this seems like a major issue, but I'm fairly new to graph databases so maybe there's something I'm missing here.

In some of my unit tests, I generate random long (64 bit integer) which represent unique IDs. The long is then stored as a property on a vertex. Unfortunately, while the node object in java reflects the correct value, the wrong one is stored in the database.

For example: 

2016543311865278327 becomes 2016543311865278200 in the database

At first I thought this might be a problem with my code, but the same issue is visible if you create a vertex from the OrientDB web interface (Add Vertex). 

I've tested this in OrientDB v2.06, v2.08 and v2.1-rc1, and the issue is present in all versions.

Can somebody please repro or let me know if there's something I'm doing wrong?

**Comment by maggiolo00** [comment]
Hi @nightrise how do you check the value inserted from Studio?

**Comment by maggiolo00** [comment]
Or do you Assert the value with a JUnit test via java?

**Comment by nightrise** [comment]
Hi @maggiolo00 

I checked the inserted values both from Studio and from the command-line Console. Likewise, I inserted the value both via my unit test and via Studio.

As for asserting the value, immediately after creating the vertex the value stored within the vertex object is consistent with what I provided if I break on it, though when I look at it in the database it's wrong.

You should be able to easily repro this yourself. Can you let me know if you're also experiencing the bug?

**Comment by maggiolo00** [comment]
Which api do you use?

**Comment by maggiolo00** [comment]
There are a tons of test on storing types so it is not a database problem. For studio
see it is normal that cannot handle that number

https://jsfiddle.net/hmnxuppL/

**Comment by nightrise** [comment]
Hey @maggiolo00 

You're right @maggiolo00. Thank you for your patience and quick responses! The values I verified in the console were ones I inserted from Studio - hence the flawed value. When I inserted the values via the unit test and checked in the console, they were accurate.

I'll close this issue, apologies for the misunderstanding! Go OrientDB Team!
