### ISSUE TITLE
JSON API's error messages are not JSON

### ISSUE THREAD

**Issue by bvhme** [orientechnologies/orientdb#4003]
For the API to be a JSON API the error messages should also be wrapped in JSON. If the API is a JSON API, and the headers request a JSON response, developers should be able to trust that what they get from the server is always valid JSON.

The lack of a proper JSON response on error makes it very difficult to use certain libraries, such as polymer core-ajax, which asks to specify the returned format when doing the call.

**Comment by maggiolo00** [comment]
Had to reopen not all api responds to json
