### ISSUE TITLE
database is closed after timeout

### ISSUE THREAD

**Issue by zpl** [orientechnologies/orientdb#4004]
Hello.

If I trying execute query after some timeout from web-interface, and query has "GREMLIN" part - it gives me error: "com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/home/dan/orient/orientdb-community-2.0.6/databases/test' is closed"

However I can execute query without gremlin.

And if I re-login to web interface, everything is working again.

Thanks.

**Comment by lvca** [comment]
We already fix this in 2.0.8.
