### ISSUE TITLE
OrientDB Studio stores Longs (64bit Integers) incorrectly

### ISSUE THREAD

**Issue by nightrise** [orientechnologies/orientdb#4005]
Hi all,

This is a follow-up to a previous issue which turned out to be less critical but still hindersome. Thanks to @maggiolo00 for clarifying.

This is really a limitation with javascript handling of 64bit Integers, but there are plenty of workarounds out there (the simplest of which is to deal with the number as a string). 

Essentially, if you go into OrientDB Studio and add/modify a property which is a "Long" (64bit Integer), you will end up with the wrong value getting stored in the database due to javascript approximating.

As such:

2016543311865278327 becomes 2016543311865278200

Demo here: https://jsfiddle.net/hmnxuppL/

Since OrientDB Studio makes extensive use of javascript for posting information, this becomes an issue. Studio is a great tool for viewing and editing existing data -- this could unfortunately lead to wrong data getting stored in the database.

I've verified the presence of this issue in all 2.x versions up to 2.1rc1.

**Comment by 8forty** [comment]
Just to clarify a little: javascript uses 64-bit floating point (IEEE 754), which means you only get 52 bits of actual integer precision (plus a sign bit).

**Comment by nightrise** [comment]
That's right @8forty, hence the incorrect values getting stored. Perhaps it would make more sense to treat it as a string as I suggested? There also javascript libraries dedicated to dealing with 64bit integers.

**Comment by maggiolo00** [comment]
We can make studio handle long as string but it is not enough. 
Some changes has to be made on OrientDB it self (JSON encoder/decoder)

**Comment by nightrise** [comment]
Makes sense; any chance this fix will make it in 2.1?
