### ISSUE TITLE
Shortestpath

### ISSUE THREAD

**Issue by boriswexler** [orientechnologies/orientdb#4009]
Are the rIDs required in ShortestPath or is there a way to build a query that resembles:

select ShortestPath((select from User where userId=85), (select from User where userId=89), 'OUT')

In other words do I have to make three separate queries (two to get the rIDs of users with those userIds, then the shortestPath query) or is there a more efficient way to do this?

Thanks

**Comment by luigidellaquila** [comment]
Hi Boris,

you can rewrite the query this way:

select shortestPath($from, $to, 'OUT')
let
$from = (select from User where userId=85),
$to = (select from User where userId=89)

Luigi



2015-04-24 2:00 GMT+02:00 boriswexler <notifications@github.com>:
