### ISSUE TITLE
sql batch doesn't respect to unique index for 2.0.8 version

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4010]
It won't throw unique index exception for the following query. It works before 2.0.7 version but not for 2.0.8
Please take note the unique index here is "email"

BEGIN
 LET user_one = INSERT INTO user SET first_name = "ckgan", country = "MY", ctime = "2015-04-24T03:29:58+0000", mtime = "2015-04-24T03:29:58+0000"
 LET account = INSERT INTO account SET email = "ckgan@hotmail.com", password = "d8", username = "ckgan200421644", nickname = "ckgan2004", language = "en", timezone = "Asia/Kuala_Lumpur", active= false, online = false, ctime = "2015-04-24T03:29:58+0000", mtime = "2015-04-24T03:29:58+0000"
COMMIT
RETURN $user_one

**Comment by lvca** [comment]
Did you see 2 records with the same email? What kind of index id you create?

**Comment by lvca** [comment]
@tglman Did you already fix this in 2.0.8, right? @martingg88 reports that this worked in 2.0.7.

**Comment by martingg88** [comment]
FYI. this work at 2.0.6. It won't create two duplicate records but never throw an exception when it try to insert. the behavior for 2.0.6 will throw the unique exception.
