### ISSUE TITLE
removeEdge leaves traces in Vertex

### ISSUE THREAD

**Issue by ctampak** [orientechnologies/orientdb#4013]
I hava a very simple relationship

>Player --> plays --> Team

When I remove the relationship (edge) between class Player and class Team using the following java code
```java
Iterator<Edge> team_edges = player.getEdges(Direction.OUT, "plays").iterator();
while(team_edges.hasNext()) {
    final Edge edge = team_edges.next();
    graph.removeEdge(edge);
}
```
The edges are all successfully removed, but when I check the OrientStudio I can still see the link to the edge in both the Player and the Team as out and in respectively. 
If I try to remove the occurence I get a 404 not found error. At first I though that was a bug in the studio, but when I used the countEdges method on the Player object I got the exact same amount of edges the studio reported.
If i count the steps of the above iterator or print the edge before the remove action I only get the remaining edges as expected.  
As a side note, I have the same problem for every relationship in my application, this was just the simple case.

I am developing a pure java application using the Java Graph API and the above problem occurs in both 2.0.6 and 2.0.8 versions.

**Comment by tglman** [comment]
find out the root cause, if have the edge class with a different case of the label it fail to remove the links, easy to reproduce with:
```
graph.createEdgeType("Plays");
player.addEdge("plays", team); 
//and here the remove
```

**Comment by fabriziofortino** [comment]
@tglman I think this issue is somehow related to #3980 
In my opinion it's not clear how to use labels and class names together for an edge. As reported in the other issue, if label and className are synonyms the API is misleading: In 

https://github.com/orientechnologies/orientdb/blob/master/graphdb/src/main/java/com/tinkerpop/blueprints/impls/orient/OrientVertex.java#L850-L944

if you specify both label and className only the label is used. I would like to have some clarification on this.

**Comment by tglman** [comment]
@fabriziofortino yes the className is there only for backward compatibility, before remove it could be better deprecate it, i'm going to do some fix to make the use of the labels an classes consistent.

**Comment by tglman** [comment]
@ctampak  by the way as work around you can check that all the label have the same case of the related Edge class

**Comment by tglman** [comment]
found a work around  to fix this specific use case, closing

**Comment by ctampak** [comment]
I just tried the proposed solution and I can confirm that it works!

I also agree with @fabriziofortino that the documentation should clearly state the situation.

@tglman I will now close the bug and mark it fixed.

Thank you all for your time

**Comment by ctampak** [comment]
Fixed
