### ISSUE TITLE
Support for Map with not String Key

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#4015]
As today we support only Maps with String as key, is it possible to support Map with a key not String and the Record Binary Serialization specification already support it we just need to change the map serialization from:

``` java
      OType type = OType.STRING;
      writeOType(bytes, bytes.alloc(1), type);
      writeString(bytes, entry.getKey().toString());
```

to:

``` java
      OType type = getTypeFromValueEmbedded(entry.getKey());
      writeOType(bytes, bytes.alloc(1), type);
      writeSingleValue(bytes, entry.getKey(), type, null);
```

The rest of the engine support it quite well, there are only two main missing point:
JSON specification doesn't support maps with key != string, so could happen that a record containing map with a key != String if updated through REST API(so using JSON) will loose the keys types converting every thing to string, as a partial workaround to this could be define the keyType in OProperty, so it can force conversion by schema.  

The second issue is that the export/import function are based on JSON as well, so they could loose information during export/import, but in this case we can define our specific format based on JSON to handle different key types.

We can choose as well to not support it because JSON doesn't, but in this case we should improve the validation to avoid this cases:

```
 Map<OIdentifiable, String> map = new HashMap<OIdentifiable, String>();
 map.put(ORecordId(10,20), "something");
 doc.field('aMap',map);
```

now what happen is an implicit conversion to String, that lead to this two issues:
https://github.com/orientechnologies/orientdb/issues/2941
https://github.com/orientechnologies/orientdb/issues/2954

**Comment by tglman** [comment]
This use case went in rellay low priority, and we are thinking to not support this at all.

**Comment by lvca** [comment]
Not valid for now, closing it.
