### ISSUE TITLE
property's attribute 'read only' problem

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#4017]
I created a class wich has property 'read only' and another one...

>create class test
>Class created successfully. Total classes in database now: 300

>create property test.prop1 STRING
>Property created successfully with id=1

>create property test.propReadOnly STRING
>Property created successfully with id=2

>alter property test.propReadOnly readonly true 
>Property updated successfully

then insert a record

>insert into test content {"prop1":"hello","propReadOnly":"only read"}
>Inserted record 'test#216:1{prop1:hello,propReadOnly:only read} v1' in 0,003000 sec(s).

>select from #216:1
>----+------+------+-----+------------
>\#   |@RID  |@CLASS|prop1|propReadOnly
>----+------+------+-----+------------
>0   |#216:1|test  |hello|only read
>----+------+------+-----+------------
>1 item(s) found. Query executed in 0.003 sec(s).

When I try to update this record, the DB returns an error. What is correct.

>update #216:1 CONTENT {"prop1":"by","propReadOnly":"updata record"}

>Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on >execution of command: sql.select from #216:1

>Error: com.orientechnologies.orient.core.exception.OValidationException: The field >'test.propReadOnly' is immutable and cannot be altered. Field value is: updata record

> select from test

>----+------+------+-----+------------
>\#   |@RID  |@CLASS|prop1|propReadOnly
>----+------+------+-----+------------
>1   |#216:1|test  |hello|only read
>----+------+------+-----+------------

But if I update only one property which doesn't have 'read only' attribute, the record updates and error message doesn't appear. 

>update #216:1 CONTENT {"prop1":"by"}
>Updated record(s) '1' in 0,127000 sec(s).

And property with 'read only' attribute loses it's value.

>select from test
>----+------+------+-----+------------
>\#   |@RID  |@CLASS|prop1|propReadOnly
>----+------+------+-----+------------
>1   |#216:1|test  |by   |null
>----+------+------+-----+------------
>1 item(s) found. Query executed in 0.003 sec(s).

**Comment by tglman** [comment]
hi @Ivanov-Yuriy 

this happen because the 'update ? CONTENT ?' is made for replace all the content of the document, if you use instead: 'update #216:1 set prop1="by"  ' the validation work correctly, so as workaround I'll suggest you to use 'update ? set ?' syntax

by the way we should not allow to replace all the content if this break the validation rules. so it's a bug.
