### ISSUE TITLE
ETL - transformers, assign edge field values

### ISSUE THREAD

**Issue by rwnew2012** [orientechnologies/orientdb#4019]
Firstly, ETL is a great tool to import large amount of data, and luca is very kindly to answer my questions.

Suppose if I have a json file to import:

```json
[
 {
  "name": "orientdb",
  "ID": 4,
  "friend": [5,6,7],
  "since" : [2010,2011,2012]
 },
 {
  "name": "Luca",
  "ID": 5,
  "friend": [2,3,4],
  "since" : [2000,2002,2010]
 }
]
```
The transformer use 
"edgeFields": {
               "since": "${input.since}"
 }

but if I want to assign different value to different edges, for example
```
4--since:2000->5
```

how could I do that in ETL? is it possible? Thanks!

**Comment by lvca** [comment]
I don't understand. Could you elaborate it?

**Comment by rwnew2012** [comment]
@lvca , sorry, I did not explain clearly. When I import json file to graph, how could assign values separately to edges fields, then edge table looks like,

rid, class, out, in, year
1,friendSince,5,2,2000
2,friendSince,5,3,2002
3,friendSince,5,4,2010
4,friendSince,4,5,2010
5,friendSince,4,6,2011
6,friendSince,4,7,2012

**Comment by lvca** [comment]
You could also execute a command transformer with this command:

    create edge FriendSince from (select from Account where id = ${input.out} ) to (select from Account where id = ${input.in} ) set year = ${input.year}

**Comment by rwnew2012** [comment]
thanks so much, @lvca !
