### ISSUE TITLE
Expand shortest path with variables

### ISSUE THREAD

**Issue by boriswexler** [orientechnologies/orientdb#4020]
Trying select expand(shortestPath) from(select shortestPath($from, $to, 'OUT') let $from = (select from User where entityId="85"), $to = (select from User where entityId="89")) - doesn't give me any results.

However select expand(shortestPath) from(select shortestPath(#12:8, #12:10, 'OUT') works fine. 
So does select shortestPath($from, $to, 'OUT') let $from = (select from User where entityId="85"), $to = (select from User where entityId="89")

Can the two not be combined? Thanks you

**Comment by lvca** [comment]
Which OrientDB version? Please always report it.

**Comment by boriswexler** [comment]
2.0.7
Thanks

**Comment by lvca** [comment]
I tried with 2.0.9-SNAPSHOT and the first database I have under my hands and

    select shortestPath($from, $to, 'OUT') let $from = (select from V limit 1), $to = (select from V limit 1 skip 1)

Returned:

![image](https://cloud.githubusercontent.com/assets/312606/7385527/199d3e7a-ee48-11e4-898c-da77c6acbbac.png)

So I can't reproduce it. Could you please try with 2.0.9-SNAPSHOT?
