### ISSUE TITLE
binary protocol does not support update command

### ISSUE THREAD

**Issue by baojie** [orientechnologies/orientdb#4021]
I use pyorient

Error message:
pyorient.exceptions.PyOrientCommandException: Cannot find a command executor for the command request: sql. UPDATE my_class CONTENT {"holiday": "sea", "work": "universe", "accommodation": "house"} UPSERT WHERE holiday="sea"  - com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException

**Comment by lvca** [comment]
This is supported. Could you provide the full stack trace?

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
