### ISSUE TITLE
ODB stopped listening at port 2424

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4025]
For some reason odb stopped listening at port 2424, surprisingly studio was running fine at port 2480. Restarting odb put things back in order. Attached is the compressed log directory for analysis. (Sent to support@orientdb.com).

**Comment by tglman** [comment]
from the logs, i could see that the server had a long series of 'java.lang.OutOfMemoryError: Java heap space' errors that made the server unstable, the fact that the server stopped listening on port 2424 has been only a case the out of memory error can hit any part of the system, the only way to recover from it is restarted the server as you have done.
