### ISSUE TITLE
OrientDB allows to create a class beginning with '#' character 2.0.8, 2.1-rc1

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb#4028]
orientdb {db=testdb}> create class #13

Class created successfully. Total classes in database now: 15

orientdb {db=testdb}> select from #13

Error: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Error on parsing query
Query:  #13
------^

Error: java.lang.IllegalArgumentException: Argument '#13' is not a RecordId in form of string. Format must be: <cluster-id>:<cluster-position>

orientdb {db=testdb}> create class #tag

Class created successfully. Total classes in database now: 16

orientdb {db=testdb}> select from #tag

Error: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Error on parsing query
Query:  #tag
------^

Error: java.lang.IllegalArgumentException: Argument '#TAG' is not a RecordId in form of string. Format must be: <cluster-id>:<cluster-position>

orientdb {db=testdb}>

**Comment by luigidellaquila** [comment]
fixed in develop branch
