### ISSUE TITLE
Support of OData

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4029]
Guys,

Do you have plans to become compatible with OData?

http://www.odata.org/

There is quite big community over it: so automatically will gain benefits for OrientDB as well.

**Comment by lvca** [comment]
It would be nice, but it's not hi-pri now.

**Comment by celumuser** [comment]
+1

I need this feature as well

**Comment by kvikster** [comment]
+1

**Comment by lvca** [comment]
Not relevant anymore, closing it.
