### ISSUE TITLE
date data type

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4030]
Date data type is not store the value as date format, but datetime format. 

for this case, we will have the timezone issue as it won't return the exact value you have stored. 
It will convert the value to timezone that you set into database and return the local timezone. 

for the datetime data type. it will always return you the exact value without timezone conversion . 
for example,  i store the value as 2015-04-22T21:24:09+0000 and it will return the same value.

**Comment by tglman** [comment]
Hi,

This is not valid anymore new serialization store with absolute time and return the date with the server timezone, closing this.

Regards
