### ISSUE TITLE
Add support for FetchType.LAZY on @OneToOne relations 

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#4032]
We have some object graphs that when fully loaded from orient can be quite large. When running attached mode, this is no problem, because we can steer the loading using fetch plans.

However when detaching using detachAll(object, true), the whole object graph will be loaded. I propose that adding @OneToOne(fetch = FetchType.LAZY) will have an detachAll skip those fields, inserting only a placeholder object with the id inserted, so the user can manually load the record when needed. So that would not be the responsibility of orient, as the object inserted is not a proxy.

**Comment by lvca** [comment]
Hey @wouterv is this already in your merged PR?

**Comment by wouterv** [comment]
Yes it is.
