### ISSUE TITLE
[ Binary Protocol - Enhancement ] Error codes with the Exception

### ISSUE THREAD

**Issue by Ostico** [orientechnologies/orientdb#4034]
I will report a question and a possibile enhancement to the binary protocol:

https://github.com/Ostico/PhpOrient/issues/18

**Comment by tglman** [comment]
Hi,

In 3.0 we introduced error codes in the protocol, anyway the server still send too generic errors, It's fixed but I leave this open for when we start to give back proper error codes.

Regards
