### ISSUE TITLE
select * from CustomClass order by @rid DESC fails

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#4035]
Hello I have a couple custom classes and I tried to order by @rid DESC but it failed with: 

com.orientechnologies.common.io.OIOException: You cannot access outside the file size (0 bytes). You have requested portion -65536-0 bytes. File: File: innerentity.cpm os-size=1024, stored=0, filled=0, max=0

Not all classes fail with that..order by @rid ASC works though

**Comment by lvca** [comment]
Which OrientDB version?

**Comment by zifnab87** [comment]
You can close it - it seems it is not a problem anymore in 2.2 version - thanks

**Comment by luigidellaquila** [comment]
Thank you very much.
Closing
