### ISSUE TITLE
Default in memory database "temp" dissapeared, not default to graph

### ISSUE THREAD

**Issue by cdeadlock** [orientechnologies/orientdb#4036]
This is orientdb-community-2.0.6
The first time I ran the server it would automatically create the default in memory database "temp"

A couple of days later it seems as if it was not creating this in memory databse. After finding a copy of the config file online I added this to the orientdb-server-config.xml
```
<!-- Default in-memory storage. Data are not saved permanently. -->
                <storage path="memory:temp" name="temp" userName="admin" userPassword="admin" loaded-at-startup="true" />
        </storages>
```
I don't remember editing the config file to remove such a thing? The best I can think of is maybe I ran the server.sh from a different working directory and perhaps that uses a different config file?

So after manually adding this to the orientdb-server-config.xml. The temp database is being run automatically. But it is not default to a "graph" type, as the documentation says. I am making this assumption because I have no "V" class in the schema.

Is there a way to set the database type to graph in the config file? Is there an XSD somewhere that explains all the possible options in orientdb-server-config.xml?

**Comment by lvca** [comment]
Fixed in 2.1
