### ISSUE TITLE
The field 'Client.matters' has been declared as LINKSET but contains a null record (probably a deleted record?)

### ISSUE THREAD

**Issue by gemmell** [orientechnologies/orientdb#4037]
We have sent you some code to reproduce the error privately. It looks to us that it is something to do with orient's lazy loading - if we go through and print the values out before committing the transaction everything works fine. This is in a single database (not distributed) and seems to have been introduced since 2.0.1 as the code I sent passes when using 2.0.1.

**Comment by tglman** [comment]
Thank you @gemmell 

Going to debug and let you know.

**Comment by gemmell** [comment]
Great, let me know if you need clarification on anything.

**Comment by lvca** [comment]
Tested with 2.0.2 and works. The first release broken is 2.0.3. We're investigating the commit caused this problem.

**Comment by tglman** [comment]
fixed in 2.0.x and develop branch the fix will be out with 2.0.9.

relative commit : https://github.com/orientechnologies/orientdb/commit/5e41595f7909264b93b13143c60cda9c89f346df

closing
