### ISSUE TITLE
Warning: Found record in transaction with the same RID #2132:5 but different instance. 

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#4038]
I get this warning a lot when loading via the Object API multiple times during a transaction in our code:

WARNING: {db=test} Found record in transaction with the same RID #2132:5 but different instance. Probably the record has been loaded from another transaction and reused on the current one: reload it from current transaction before to update or delete it

However somehow I cannot recreate this with a unit test in the orient source, but I did manage to find the problem and will provide a pull request with the fix.

**Comment by lvca** [comment]
Closing because merged your PR.
