### ISSUE TITLE
Query execution on single node returns different results than in distributed mode

### ISSUE THREAD

**Issue by ccasenove** [orientechnologies/orientdb#4043]
Using OrientDB version 2.0.6, the result of a sql query is different depending on the distributed mode of the server. This happens when functions like list() are used in the query.

- Start OrientDB with server.sh/.bat, then execute the following query in the console:

```text
orientdb {db=testdb}> select list("a","b")             

----+------+----
#   |@CLASS|list
----+------+----
0   |null  |[2] 
----+------+----

1 item(s) found. Query executed in 0.029 sec(s).
```
The list has 2 elements as expected, "a" and "b".

- Now start OrientDB with dserver.sh/.bat, and execute the same query:

```text
orientdb {db=testdb}> select list("a","b")         

----+------+----
#   |@CLASS|list
----+------+----
0   |null  |[1] 
----+------+----

1 item(s) found. Query executed in 0.003 sec(s).
```

There is only 1 element in the list and its value is:

```text
orientdb {db=testdb}> select list("a","b")[0] 

----+------+--------------------------------
#   |@CLASS|list                            
----+------+--------------------------------
0   |null  |{node=ta.testdb, context=[a, b]}
----+------+--------------------------------

1 item(s) found. Query executed in 0.004 sec(s).
```

So in distributed mode, it seems we need to get the *context* attribute of the result to retrieve the real value of the list.

**Comment by lvca** [comment]
Fixed in 3d2fda97a0f45535bc4724a000d911608883517c
