### ISSUE TITLE
Milestone for REST/binary changes listener?

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#4052]
Hi,

I would just like to ask if there's any plan on implementing some sort of REST/binary changes provider much like the one available in CouchDB. Basically, client either constantly polls or long-polls from the server. Once change happened, client becomes notified or which record was changed.

**Comment by lvca** [comment]
We already provide it as Live Query. Check this in documentation.

**Comment by andreyvk** [comment]
Nice! Cutting edge stuff

**Comment by andreyvk** [comment]
Understandably it says "*This feature is experimental and not covered by commercial support...*". Can you provide some insight on whether you guys will keep this feature in later versions and, if yes, then by which version of OrientDB is it expected to become stable?

**Comment by luigidellaquila** [comment]
Hi Andrey,

we would have liked to release it as a stable feature in 2.1, but it was
too close to the release, so we decided to release it anyway, but as
experimental.
In 2.2 it should be released as a stable feature, you can just expect some
minor changes in the API.

Luigi


2015-04-29 11:00 GMT+02:00 Andrey <notifications@github.com>:

**Comment by andreyvk** [comment]
That's great news. I'll start using this feature then, since it's going to grow mature. Thanks guys
