### ISSUE TITLE
Documentation: non working function example

### ISSUE THREAD

**Issue by denistoikka** [orientechnologies/orientdb#4053]
I'm trying to execute function from orientdb documentation: [link](http://orientdb.com/docs/last/Functions.html)

```
function user_create( name, role ){
  var db = orient.getDatabase();
  var role = db.query("select from ORole where name = ?", roleName);
  if( role == null ){
    response.send(404, "Role name not found", "text/plain", "Error: role name not found" );
  } else {

    db.begin();
    try{
      var result = db.save({ "@class" : "OUser", name : "Luca", password : "Luc4", status: "ACTIVE", roles : role});
      db.commit();
      return result;
    }catch ( err ){
      db.rollback();
      response.send(500, "Error on creating new user", "text/plain", err.toString() );
    }
  }
}
```

Initially I got an error: "No database instance found in context", but [these changes](http://stackoverflow.com/questions/23829704/orientdb-no-database-instance-found-in-context-error) fixed it.

Then I got:
"Can't find method com.orientechnologies.orient.core.command.script.OScriptDocumentDatabaseWrapper.query(string, string)".

After changing
`var role = db.query("select from ORole where name = ?", roleName);`
to
`var role = db.query("select from ORole where name = " + roleName);`
I am getting:
"InternalError: The choice of Java method com.orientechnologies.orient.core.command.script.OScriptDocumentDatabaseWrapper.save matching JavaScript argument types (object) is ambiguous; candidate methods are: 
    class com.orientechnologies.orient.core.record.impl.ODocument save(com.orientechnologies.orient.core.record.ORecord)
    class com.orientechnologies.orient.core.record.impl.ODocument save(java.util.Map) (<Unknown source>#10)"

OrientDB v2.0.7

**Comment by red-0ne** [comment]
If you are using graph database
```javascript
var gdb = orient.getGraph();
var role = db.command("sql", "select from ORole where name = ?", roleName);
```

**Comment by denistoikka** [comment]
I'm trying to use exact example from documentation.
