### ISSUE TITLE
Binary Protocol: return context in commands

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4055]
We need to return the context as ODocument to let client to use variable there. This is useful with:
- [ ] Lucene Facets search
- [ ] Profiling, since profiling information are stored in context

**Comment by tglman** [comment]
by the way, this is a new feature to me, and should not target an RC ;)

**Comment by lvca** [comment]
So the @maggiolo00 feature about Lucene facetted search is useless.

**Comment by lvca** [comment]
@maggiolo00 So your facet search will go in 2.2 as well.
