### ISSUE TITLE
Query that involves counting edges and traversing vertices results in abnormal performance, even with indexes

### ISSUE THREAD

**Issue by hbCyber** [orientechnologies/orientdb#4056]
OrientDB Version: orientdb-community-2.0.7
Not using custom settings.

Certain queries that involves vertices, edges and indexes result in abnormal slow performance.

My example scenario:
- We have User vertices and Tag vertices
- User can connect to Tag vertices via a UserUsedTag edge (timestamp stored on that edge)
- I want to calculate, for a given User, which tags are his/her favourite based on how many times the User used the tag during a certain time period (this is where the performance problem occurs)

Steps to reproduce:
1- Initialize the database schema (done using SQL)

``` sql
CREATE CLASS User EXTENDS V;
CREATE PROPERTY User.username STRING;
CREATE INDEX User.username UNIQUE_HASH_INDEX;

CREATE CLASS Tag EXTENDS V;
CREATE PROPERTY Tag.name STRING;
CREATE INDEX Tag.name UNIQUE_HASH_INDEX;

CREATE CLASS UserUsedTag EXTENDS E;
CREATE PROPERTY UserUsedTag.timestamp DATETIME;
CREATE INDEX UserUsedTag.timestamp NOTUNIQUE;
```

![schema_tag](https://cloud.githubusercontent.com/assets/7698618/7405729/730009ac-ef29-11e4-89c6-b99da9bb8a5d.jpg)
![schema_user](https://cloud.githubusercontent.com/assets/7698618/7405731/7306dfca-ef29-11e4-8650-feee4b499fa3.jpg)
![schema_user_used_tag](https://cloud.githubusercontent.com/assets/7698618/7405730/7305c7e8-ef29-11e4-9fd2-1393ee8f1cd3.jpg)

2- Populate random data (done using Java code)

``` java
OrientVertex userVertex = graph.addVertex("class:User");     
Map<String, Object> properties = new HashMap<>();
properties.put("username", "john.doe");
userVertex.setProperties(properties);

OrientVertex tagVertex1 = graph.addVertex("class:Tag");            
Map<String, Object> properties = new HashMap<>();
properties.put("name", "baseball");
tagVertex1.setProperties(properties);

OrientVertex tagVertex2 = graph.addVertex("class:Tag");            
Map<String, Object> properties = new HashMap<>();
properties.put("name", "soccer");
tagVertex2.setProperties(properties);

int numIterations = 10000;
for (int i = 0; i < numIterations; i++) {            
    long random = Math.round(Math.random());
    Vertex tagVertex = (random == 0? tagVertex1 : tagVertex2);

    // Create the edge
    OrientEdge userUsedTagEdge = graph.addEdge(
        null, 
        userVertex, 
        tagVertex, 
        "UserUsedTag");

    Map<String, Object> properties = new HashMap<>();
    properties.put("timestamp", new Date().getTime());
    userUsedTagEdge.setProperties(properties);
}
```

3- Run the query. In this example: find a user's favourite tags.

``` sql
SELECT inV().name AS name, COUNT(*) AS weight FROM (
    SELECT expand(outE("UserUsedTag")) 
    FROM user
    WHERE username = "john.doe"
) 
WHERE timestamp < date()
GROUP BY in
ORDER BY weight DESC
```

(I include the condition WHERE timestamp < date() above to indicate that I need the ability to filter on a date range).

Running the query in the OrientDB Studio yields the following result for me:

```
baseball    5011
soccer  4989
Query executed in 0.358 sec. Returned 2 record(s)
```

The EXPLAIN JSON is below:

```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 10000,
            "current": "#14:31120",
            "recordReads": 10000,
            "limit": -1,
            "fetchingFromTargetElapsed": 198,
            "projectionElapsed": 6,
            "expandElapsed": 3,
            "orderByElapsed": 0,
            "evaluated": 10000,
            "groupByElapsed": 0,
            "user": "#5:0",
            "elapsed": 298.94913,
            "resultType": "collection",
            "resultSize": 2,
            "@fieldTypes": "documentReads=l,current=x,recordReads=l,fetchingFromTargetElapsed=l,projectionElapsed=l,expandElapsed=l,orderByElapsed=l,evaluated=l,groupByElapsed=l,user=x,elapsed=f"
        }
    ],
    "notification": "Query executed in 0.338 sec. Returned 1 record(s)"
}
```

A similar query and structure built using PostgreSQL was 40x faster. I'm not expecting OrientDB to surpass PostgreSQL but there must be something abnormal with this performance.

**Comment by hbCyber** [comment]
Another user has experienced the same performance problem when trying to compute how many people were linked to records of a "Gender" table. Essentially the same kind of scenario as described above.

You can find his post on the Google Groups:
https://groups.google.com/forum/#!topic/orient-database/qgLnRmCn38o

To summarize his situation:
- He has a class Person and a class Gender
- When a Person vertex is created, it is linked to one of the Gender records
- When trying to count how many Persons there are per Gender, the performance issue arises (20s for 2.1 million records) even though proper indexes seem to be in place.
```sql
select gender, count(gender) from Person group by gender 
```

**Comment by luigidellaquila** [comment]
With a good usage of indexes, this query would take ~50ms instead of 350.
Unfortunately current query executor is not able to do this; this optimization will be implemented in 2.2

**Comment by martingg88** [comment]
can we treat this issue as higher priority. i dun think current query executor will have promised and good performance. for example, it will give the slow query performance especially applied for where/order clause.

**Comment by TheAdamGalloway** [comment]
This is a big issue imo. Facebook's TAO database has a very good edge count inbuilt.

**Comment by gerdhub** [comment]
This is really a big issue, are there any definite plans on when there will be any improvements?
Thank you for a rough estimate.

**Comment by bbourgois** [comment]
+1

**Comment by vivekjustthink** [comment]
Hi, have we sorted this out?
