### ISSUE TITLE
Syntax of Insert and Update of embedded document types are inconsistent

### ISSUE THREAD

**Issue by mamobyz** [orientechnologies/orientdb#4057]
The following is reported on v2.0.7:

For embedded documents, the insert and update statements are different. While insert copes with a plain quasi-JSON object (single-quotes suffice, not necessarily double-quotes, thus quasi-JSON), does update not work with this plain JSON type. The additional specs @class and @type must be added. The following statements can be used to illustrate the issue:
```
create class Address
create property Address.street String
create property Address.city String

create class Client
create property Client.name String
create property Client.phones embeddedSet String
create property Client.addresses embeddedList Address

insert into client set name = 'James Bond', phones = ['1234', '34567'], addresses = [{'city':'Shanghai', 'zip':'3999'}, {'city':'New York', 'street':'57th Ave'}]
update client add addresses = [{'city':'London', 'zip':'67373'}] # not working
update client add addresses = [{'@type':'d','@class':'Address','city':'London', 'zip':'67373'}] # works
```

**Comment by vitorenesduarte** [comment]
Hi @mamobyz.
I believe this was already reported here #3621.

**Comment by mamobyz** [comment]
Hi @vitorenesduarte, thanks for the hint!
They are probably too busy with other issues. As you reported this issue months ago, it is sometimes really frustrating to wait for at least an opinion from OrientDB. As @lvca stated, it was super easy to fix #3398, I truly believe that! I don't understand why they need so much time to not respond.

So I will leave also this one open, until someone from OrientDB respond.

**Comment by maggiolo00** [comment]
@mamobyz 

are you getting 
```
com.orientechnologies.orient.core.exception.OValidationException: The field 'Client.addresses' has been declared as EMBEDDEDLIST but an incompatible type is used. Value: 67373
```

**Comment by mamobyz** [comment]
@maggiolo00: Yes, this is the error message.

**Comment by mamobyz** [comment]
I just tested this issue on 2.0.10. It still does not work. Isn't the fix already merged into 2.0.9?

**Comment by mamobyz** [comment]
And it does not work on 2.1-rc3 either. To be frank, it is really frustrating!

**Comment by luigidellaquila** [comment]
Hi @mamobyz 

it's fixed in 2.1 RC3 but not in 2.0.10.
Are you sure you tried correctly with latest RC? I just tried it and it seems to work fine

Luigi

**Comment by lvca** [comment]
I found this issue as fixed, but when has been fixed? I can't find the relative commit.

**Comment by mamobyz** [comment]
@luigidellaquila: If the download file for rc3 provided on your Web page is really rc3, I guess I have got it tested on rc3!

@lvca: I hope, you are not waiting for my reply! I have no influence on your commits. If you have added milestone 2.0.9 and 2.1-rc2 (see above) and closed the ticket afterwards, I assume it is fixed on both milestones.

Sorry, it seems a bit chaotic there ...

**Comment by luigidellaquila** [comment]
mmm... ok, I'm trying it again... 
@lvca good question, I tried it on the snapshot and it's OK (or so it seems, I'm checking it again)

**Comment by luigidellaquila** [comment]
Guys, I tried it again, just did this:
- downloaded 2.1 RC3 from the website (usually I work on develop branch, but you never know...)
- unzipped and launched (root password asked, so it's a new instance, no doubt)
- created a new db (!!! this could be the point, are you working with an old db?)
- in Studio, copied-pasted your statements and executed one by one

After every insert/update I did a select to check the actual content of the record, and it was ok...
Any thoughts? 

Thanks

**Comment by mamobyz** [comment]
@luigidellaquila: Maybe you should test it on console. The __console__ uses a different (de-)serializer, is it right. It could well be, that the REST interface adds the superfluous tags so that the final writes works, but it still replies on that the input entails these tags, i.e. @type, @class
