### ISSUE TITLE
In case of perenthesis in the order by clause the parser fail

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#4059]
This bug come from oriento, so fixed this also some tests on oriento should get fixed, the relative test case can be found in this branch: https://github.com/orientechnologies/orientdb/tree/bug_order_by feel free to merge it as soon as it fixed.

**Comment by luigidellaquila** [comment]
what is this syntax for???


2015-04-30 15:22 GMT+02:00 tglman <notifications@github.com>:

**Comment by nagarajasr** [comment]
I'm guessing that this syntax could be due to order by parameter coming from a sub-query?

**Comment by luigidellaquila** [comment]
fixed in "develop" branch, will be released in 2.1 rc2
