### ISSUE TITLE
Cluster and Class - cluster selection don't work

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4067]
Hi
in my database there are 2 main classes and two cluster.

- `Node` -> cluster `de_business`
- `Root` -> cluster `de_root`

But now I can't select my `Root` vertex by the cluster selection `select from cluster:de_root`. The class is attached to the cluster but I find no way to solve this problem. This issue is very strange for me because the class was already attached and during some updates of orientdb I crashed into this situation. Is it possible to reassign the class or something like that? I tried `addcluster`, `removecluster` but nothing helped. Thanks.

Thats my cluster settings when I do an export of my db

```json
    {
      "name": "de_root",
      "id": 19
    }
```
Vertex:
```json
{
        "name": "Root",
        "default-cluster-id": 13,
        "cluster-ids": [
          13,
          19
        ],
        "oversize": 0.0,
        "super-class": "Node",
        "cluster-selection": "round-robin",
        "properties": [
          {
            "name": "Cycles",
            "type": "LINKLIST",
            "collate": "default"
          },
          {
            "name": "Name",
            "type": "STRING",
            "collate": "default"
          },
          {
            "name": "Settings",
            "type": "LINK",
            "collate": "default"
          }
        ]
      },
```

This is the related vertex which can not be found by the cluster selection

```json
{
      "@type": "d",
      "@rid": "#13:0",
      "@version": 2,
      "@class": "Root",
      "DisplayName": "company",
      "Name": "company",
      "Email": "info@company.de",
      "Points": 0,
      "Position": "",
      "Active": true,
      "Created": 1427045163762,
      "Mid": "550efb2c086e22ca61626ed8",
      "References": [
        "#12:53",
        "#12:1",
        "#18:52",
        "#12:0",
        "#18:0",
        "#18:1"
      ],
      "InsertedAtDepth": 0,
      "out_BroughtIntoRight": [
        "#14:0"
      ],
      "out_BroughtIntoLeft": [
        "#15:0"
      ],
      "@fieldTypes": "Created=t,References=n,out_BroughtIntoRight=g,out_BroughtIntoLeft=g"
    },
```
During import no vertex will be imported to the `de_root` cluster :/

OrientDb: 2.0.8, Studio

**Comment by StarpTech** [comment]
I want to use the `MOVE VERTEX` command but when I execute this I get following issue:

```sql
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Root{DisplayName:BodyClub24,Name:BodyClub24,Email:info@bodyclub24.de,Points:0,Position:,Active:true,Created:Sun Mar 22 18:26:03 CET 2015,Mid:550efb2c086e22ca61626ed8,References:[6],InsertedAtDepth:0,out_BroughtIntoRight:[size=1],out_BroughtIntoLeft:[size=1],ProfilePictureS3Key:users/550efb2c086e22ca61626ed8/images/profile-picture.png}: found duplicated key 'info@bodyclub24.de' in index 'Node.Email' previously assigned to the record #13:0 RID=#13:0
```

**Comment by lvca** [comment]
Issue #4074 was fixed time ago. About this issue, I don't understand what's the problem: are you trying importing the same record with a different RID?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
