### ISSUE TITLE
Create Vertex and edges at once from JSON

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4068]
Hi,
is it possible to create a Vertex with his edges only with JSON like`CREATE VERTEX V CLUSTER X CONTENT <JSON>` ?

**Comment by shekhei** [comment]
how does this actually work? may I know how would the json look like?

**Comment by lvca** [comment]
This is not possible, because creating an edge means updating another vertex and this can't be expressed with only one JSON. The best solution is to use SQL BATCH where you put both commands in the same script.

**Comment by shekhei** [comment]
@lvca then what was the referencing this issue? was it a mistake? I thought it gotten implemented :P
