### ISSUE TITLE
Exception while restoring orientdb backup

### ISSUE THREAD

**Issue by shajigopal** [orientechnologies/orientdb#4072]
OrientDB version 2.0.5
Blueprints API version:2.6.0

We are getting the following exception while restoring an orientdb backup file. Here is what we do:

1. We have an orientDB running in embedded mode in tomcat. When our webapp is initialized we start orientdb too.
2. When a restore-graph command is invoked we stop the orientdb by calling graph.shutdown()
3. Once shutdown completes we invoke the orientdb restore API
4. It throws the following exception:

java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at com.orientechnologies.common.io.OIOUtils.copyStream(OIOUtils.java:157)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.extractFile(OZIPCompressionUtil.java:94)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.uncompressDirectory(OZIPCompressionUtil.java:80)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restore(OLocalPaginatedStorage.java:171)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.restore(ODatabaseDocumentTx.java:2504)
	
Why does OrientDB lock files even after shut-down? A google search pointed us to a link which stated that orient does a soft shutdown and setting the parameter STORAGE_KEEP_OPEN will release all locks. We tried that too without any luck.

Please let us know of any setting that would unlock all files after calling shutdown so that restore is successful.

Attached here is a sample JUnit test-case function:

@Test
	public void restore() throws Exception {
		Graph graph = GraphTestUtils.setupGraph();
		System.out.println("GraphDB intialized");
		System.out.println("Press any key to start restore...");
		System.in.read();
		System.out.println("GraphDB shutting down...");
		GraphTestUtils.shutDownGraph(graph);
		String fileName = "C:\\temp\\graph\\orient\\backup.zip";
		ODatabaseDocumentTx db = new ODatabaseDocumentTx("plocal:"+GraphTestUtils.graphLocation);		
		InputStream in = null;
		try{
			db.open("admin", "admin");
			OCommandOutputListener listener = new OCommandOutputListener() {
				@Override
				public void onMessage(String iText) {
					log.info(iText);
				}
			};
			in = new FileInputStream(fileName);
			db.restore(in,null,null,listener);
		}catch(Throwable e) {
			e.printStackTrace();
		}finally {
			db.close();
			GraphTestUtils.shutDownGraph(graph);
		}
	}

**Comment by shajigopal** [comment]
Can someone please provide some help here?

**Comment by ninesunqian** [comment]
Have you fix it ?

**Comment by lvca** [comment]
Guys, this issue seems old. Have you tried with a more recent version? Let's say 2.1.2?

**Comment by shajigopal** [comment]
What changed?

**Comment by lvca** [comment]
Try calling `Orient.closeAllStorages()` before restoring it.

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
