### ISSUE TITLE
Can't move vertex with unique index

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4074]
I want to use the `MOVE VERTEX` command but when I execute this I get following issue:

`
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Root{DisplayName:Company,Name:Company,Email:info@company.de,Points:0,Position:,Active:true,Created:Sun Mar 22 18:26:03 CET 2015,Mid:550efb2c086e22ca61626ed8,References:[6],InsertedAtDepth:0,out_BroughtIntoRight:[size=1],out_BroughtIntoLeft:[size=1],ProfilePictureS3Key:url}: found duplicated key 'info@company.de' in index 'Node.Email' previously assigned to the record #13:0 RID=#13:0
`

The  `MOVE VERTEX` command doesn't respect indexes.

OrientDb: 2.0.8, Studio

**Comment by lvca** [comment]
What's the `MOVE VERTEX` command? Could you please report here?

**Comment by StarpTech** [comment]
A simple one `MOVE VERTEX #13:0 to CLUSTER:Root`

**Comment by lvca** [comment]
I guess this problem has been already fixed by #4094. Could you please try last 2.1-SNAPSHOT?
