### ISSUE TITLE
possible enhancement?

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4075]
Consider a extreme case in cui i have a application with a strong dynamic for insertion /removal of rows . 
Every time i insert a new row, OrientDB  increments counter for the current rid . so, 
It could reach the maximum value just with 1 row present in database (with many insert, delete)
OClusterPosition could wrap a Number not a long, so the dimension of this number can be dynamic(long or biginteger if is necessary).
A side effect of this problem is also in distrubuted system: what does it happen if cluster in a server reach the maximum rid ? 
Is there some technical problem to make it ? It could be usefull to know it for understanding if in the future i need  it if i have a way for solving it.

**Comment by lvca** [comment]
With long numbers you can store 2^63. This means that with a rate of insertion of 1,000 records/sec, you'd need 106,751,991,167 years to have this problem. I think we can close this issue.
