### ISSUE TITLE
Multiple edges created between two vertexes

### ISSUE THREAD

**Issue by atboo** [orientechnologies/orientdb#4076]
It can create serval edges in same class between two specified vertexes.

just like following query result:

![Uploading scr.png…]()

**Comment by nagarajasr** [comment]
Could you please elaborate why you consider this as an issue? If you would like to restrict that only one edge (of a particular class) can be created between two vertices, apply a unique composite index on the 'in' and 'out' properties of the edge class, as described in the section 'Setting constraints on Edges' over here: http://orientechnologies.blogspot.it/2013/08/orientdb-using-schema-with-graphs.html

**Comment by maggiolo00** [comment]
Which is the issue here? Could you elaborate?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
