### ISSUE TITLE
Move vertex don't considered connected Vertex/Edges

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4077]
Hello orientdb,
this is fucking shame. Sry but I found no other words to express my feelings. Luckily, I could fix this issue manually. I like orientdb very much but where is your focus and what is your philosophy behind orientdb?

1. `move vertex Animal to cluster:germany`
2. I have to update all propertys of all vertex which has a reference to the vertex above. On a use case with million of records and connections this would be the horror worst case.

OrientDb: 2.0.8, Studio

**Comment by lvca** [comment]
What version? We already fixed this in 2.0.x

**Comment by StarpTech** [comment]
OrientDb: 2.0.8, Studio

**Comment by lvca** [comment]
Why do you say "update all propertys of all vertex which has a reference to the vertex above"? Are you using links instead of edges? Can you provide the json of any of those vertex?

**Comment by StarpTech** [comment]
E.g this is the root vertex which has the ID `#19:0`
```json
{
            "@type": "d",
            "@rid": "#19:0",
            "@version": 5,
            "@class": "Root",
            "DisplayName": "Company",
            "Name": "Company",
            "Email": "info@Company.de",
            "References": [
                "#18:52",
                "#12:0",
                "#12:1",
                "#12:53",
                "#18:0",
                "#18:1"
            ]
}
```

therefore I could have lots of vertexes which has a reference to that vertex e.g in the `SponsoredBy` property.
```json
{
              "@type": "d",
            "@rid": "#19:0",
            "@version": 5,
            "@class": "Node",
            "DisplayName": "Company",
            "Name": "Company",
            "Email": "info@Company.de",
            "SponsoredBy": "#19:0"
}
```
When I move the vertex to another cluster the integrity will break.

**Comment by lvca** [comment]
`MOVE VERTEX` takes care of updating edges, not links:

http://orientdb.com/docs/last/SQL-Move-Vertex.html

**Comment by lvca** [comment]
@StarpTech, please keep the tone moderated. Things like "this is fucking shame. Sry but I found no other words to express my feelings" is very un-constructive for OrientDB product and community.

**Comment by StarpTech** [comment]
@lvca there is always a point where you can't talking moderate anymore. I find so much issues in the core like parser or transactions and the only echo I get from orientdb is "we have introduce new feature X" instead to make the core more stable.  Also on my open issues I receipt only occasional response. This roadmap is very un-constructive for OrientDB product and community.

**Comment by lvca** [comment]
@StarpTech in this case the issue not even exist. I saw that the more friendly the user is, the more the community helps him.

**Comment by StarpTech** [comment]
@lvca sure, I understand you but it should be clear that core functionality has more priority. I help where I can. They aren't dramatic ?:

- broken transactions issue: https://github.com/orientechnologies/orientdb/issues/4045
- Unable to move vertex with unique index issue: https://github.com/orientechnologies/orientdb/issues/4074
