### ISSUE TITLE
IndexOutOfBounds Exception while Exporting Database Schema

### ISSUE THREAD

**Issue by sunnybt** [orientechnologies/orientdb#4083]
I am trying to export the database schema using the following command from console : 
export database filename -excludeAll -includeSchema

I am getting the following error and not able to export

Exporting current database to: database filename -excludeAll -includeSchema in GZipped JSON format ...

Error: java.lang.IndexOutOfBoundsException: Index: 0

Please help.

**Comment by maggiolo00** [comment]
hi @sunnybt which version of OrientDB?

**Comment by sunnybt** [comment]
I tried on 2.0.6. 
But yes i got a fix with this command : 
export database filename -excludeAll -includeSchema=true , it works. 

Closing the Issue.
