### ISSUE TITLE
Decimal precision

### ISSUE THREAD

**Issue by dehbmarques** [orientechnologies/orientdb#4084]
Hi,

When I execute this command:
```
create class Address extends V
create property Address.lat decimal
create vertex Address set lat = -46.63124830000004
```

The decimal -46.63124830000004 gets rounded to -46.63125

I'm using OrientDB 2.0.8. This problem happens using the Studio and the binary protocol (Oriento)

**Comment by maggiolo00** [comment]
Hi @dehbmarques 
i tried with the latest 2.1.rc2  from Studio
and it worked

**Comment by dehbmarques** [comment]
@maggiolo00 thanks, using the binary protocol it worked too
