### ISSUE TITLE
Using variable for from field in traverse not working

### ISSUE THREAD

**Issue by omgold** [orientechnologies/orientdb#4086]
When I create an SQL script and assign a previous query result to a local variable with let, I cannot pass this result to the FROM field of the TRAVERSE command:

let res = select from obj where name = "entry2";
traverse parent from $res;

This does not work as expected. If I do that with SELECT instead of TRAVERSE it is fine. Below is a python example that demonstrates that behavior.

---

#!/usr/bin/python2

import pyorient

user   = "root"
passwd = "abcdefg"

client = pyorient.OrientDB( "localhost" )
client.connect( user, passwd )

 # client.db_drop( "demo" )

if not client.db_exists( "demo" ):
    client.db_create( "demo" )

    client.command( "create class obj" )
    client.command( "create property obj.name string" )
    client.command( "create property obj.parent link obj" )
    obj1 = client.command( 'insert into obj content {"name":"entry1"}' )[0]._rid
    client.command( 'insert into obj content {"name":"entry2","parent":"%s"}' % obj1 )
else:
    session_id = client.db_open( "demo", user, passwd )

obj2 = client.query( 'select from obj where name = "entry2"' )[0]._rid

res = client.batch("""\
let res = select from obj where name = "entry2";
select parent from $res;
""" )

print [ i.oRecordData for i in res ]

res = client.batch("""\
traverse parent from %s;
"""  % obj2 )

print [ i.oRecordData for i in res ]

res = client.batch("""\
let res = select from obj where name = "entry2";
traverse parent from $res;
""" )

print [ i.oRecordData for i in res ]

**Comment by omgold** [comment]
I withdraw the issue. My fault. It must be:

traverse parent from $parent.$res;

I didn't consider that traverse creates a new context, while select does not

**Comment by maggiolo00** [comment]
Ok i'm closing it
