### ISSUE TITLE
gremlin.bat script

### ISSUE THREAD

**Issue by rwnew2012** [orientechnologies/orientdb#4087]
Hi,  I am using orientdb-community-2.1-rc1. in gremlin.bat file, :script session, it is 
"java %JAVA_OPTIONS% %JAVA_ARGS% -cp %CP% com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine %strg%".

when I tried to use gremlin.bat to read script file via
java -cp "lib\*" com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine example.groovy
(The above is equivalent to gremlin.bat -e example.groovy. correct me if I am wrong. )
it throw me errors like 

Error: main method not found in class com.tinkerpop.gremlin.groovy.jsr223.gremlinGroovyScriptEngine, please define the main method as:
public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

if I call intead 
"java -cp "lib\*" com.tinkerpop.gremlin.groovy.jsr223.ScriptEngine example.groovy" 

problem is solved. Is there anything I misunderstand? Thanks!

**Comment by luigidellaquila** [comment]
Hi @rwnew2012 

class ```com.tinkerpop.gremlin.groovy.jsr223.ScriptEngine``` does not exist, do you mean ```com.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor```?

**Comment by luigidellaquila** [comment]
fixed in develop branch
