### ISSUE TITLE
Query optimization issues

### ISSUE THREAD

**Issue by nmcintyre2014** [orientechnologies/orientdb#4088]
Query optimization seems to have some issues.  Here's an example...  We're trying to query a type that has 3.4M vertices.  The type has two indices defined, the first is a UNIQUE_HASH_INDEX on the 'identifier' column (string with guids).  This is to do fast lookups with a known 'identifier'.  The other index is a NOTUNIQUE index on a 'timestamp' column (a date).  The index on 'timestamp' is for fast date range queries.  Queries that only use one column or the other are, as expected, fast.  Examples:

The following query returns 2072 results in ~5 seconds.  Not too bad...
SELECT \* FROM Acquisition WHERE timestamp > '2014-02-16' and timestamp < '2014-02-19' LIMIT 5000

This one returns one result in .1 second.  Also, not too bad.
SELECT \* FROM Acquisition WHERE identifier = '10100100125F5300' LIMIT 5000

This one, however, returns 9 records in 30+ seconds.  Not good.
SELECT \* FROM Acquisition WHERE timestamp > '2014-02-16' and timestamp < '2014-02-19' AND identifier like '10100100125F5%' LIMIT 5000

When I run an 'EXPLAIN' on the first and third query, both show the same 'involvedIndexes' (the index on 'timestamp').  However, the first query shows 'evaluated'=2072 while the second query shows 'evaluated'=874234.  Why would the index return more results for the third query than for the first?  Is there a way to optimize the query using a different type of index or something comparable to hints?

**Comment by nagarajasr** [comment]
The third query is using a "like" query which is possibly why the query is returning more number of records. 
To optimize the query, try changing the query into a sub-query:

``sql
select from (select from Acquisition WHERE timestamp > '2014-02-16' and timestamp < '2014-02-19') where identifier like '10100100125F5%' LIMIT 5000
```

This should ensure that the timestamp index is used within the sub-query. The outer query will still likely not use the index, as it is a "like" query (I could be wrong on this).

**Comment by nmcintyre2014** [comment]
I'm seeing the same behavior with a sub-query.  Response time is 30+ seconds.
