### ISSUE TITLE
Query error only on distributed

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4098]
Hi Guys, This error happens only when is running on distributed server: 
sql.SELECT UserId FROM User WHERE OrganizationId = 1
server.java.lang.ClassCastException: com.orientechnologies.orient.server.distributed.ODistributedStorage cannot be cast to com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage

Thanks

**Comment by tglman** [comment]
this issue is a duplicate of this: https://github.com/orientechnologies/orientdb/issues/4177, closed few months ago.
