### ISSUE TITLE
little bug in console? 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4104]
Using console: 
select from #3:1 

if 3:1 is a binary data (ORecordBytes)

console log 

"no result" even if data exists (it would be usefull if it prints also the size of binary data)

**Comment by lvca** [comment]
What release?

**Comment by publicocean0** [comment]
For your question , i suppose you solved the problem in last weeks :)  I use 2.0.

**Comment by lvca** [comment]
Cool, so I'm going to close it ;-)

**Comment by publicocean0** [comment]
i downloaded last version but same problem is here
