### ISSUE TITLE
Error with multiple fetchplans

### ISSUE THREAD

**Issue by weinr0ck** [orientechnologies/orientdb#4106]
To recreate this you need 2 different types of vertices and 1 type of edge.
1. Start off with a person class that extends V, a car class that extends V, and person_car class that extends E.
2. (This step might not be needed) Create a quick schema for both person and car that has the properties in_person_car and out_person_car that are linkedlists for the person_car class. Then create the in and out links for person_car but don't specify the class.
3. Create a record for person and car. Then create 2 edges, one from person to car and one from car to person. Hence both person and car should have in_person_car and out_person_car set.
4. From person execute the following SQL (assuming #12:0 is the person) "select \* from #12:0 fetchplan in_person_car:2 out_person_car:2". Notice how out_person_car has been followed 2 degrees while in_person_car has been followed only 1 degree. Also, even the fetchplan *:2 only follows in_person_car 1 degree.

Thanks.

**Comment by tglman** [comment]
hi @weinr0ck,

The fetch plan works at document level in 2.x, and one graph relationship is 2 level links at document level, so for have two graph levels you should get 4 link levels ex: `select from #12:0 fetchplan in_person_car:4 out_person_car:4`

Regards
