### ISSUE TITLE
NullPointerException getting broken link field value with Object connection

### ISSUE THREAD

**Issue by ivanofenix** [orientechnologies/orientdb#4110]
I'm using Orient 2.0.5 embedded... I'm loading documents by using an Object connection
If the document contains a broken link the execution of the correspondent "get" method on the mapped bean produce a null pointer
here is the stack trace
java.lang.NullPointerException at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.convertDocumentToObject(OObjectProxyMethodHandler.java:721) at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.lazyLoadField(OObjectProxyMethodHandler.java:606) at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:314) at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:300) at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.manageGetMethod(OObjectProxyMethodHandler.java:289) at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.invoke(OObjectProxyMethodHandler.java:115) at org.fao.fenix.commons.msd.dto.full.MeIdentification$$_jvst40b_0.getDsd(MeIdentification$$_jvst40b_0.java)

**Comment by tglman** [comment]
fixed on develop, do you need port to 2.0.x ?

**Comment by tglman** [comment]
ported
