### ISSUE TITLE
Parser problem: Alter class silently succeeds when trying to make class abstract (which is not supported)

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb#4114]
As per the doc "http://orientdb.com/docs/last/SQL-Alter-Class.html", it is not supported to alter class to make it abstract. However, when the command is issued "alter class testClass abstract extends V" the command silently succeeds, giving the impression that the class has been redefined abstract but is in fact not the case.
Note that the command "alter class testClass abstract" fails (correctly) with StringIndexOutOfBoundsException

**Comment by tglman** [comment]
@nagarajasr  We support the alter of the abstract, with "alter class abstract true" and "alter class abstract false" going to update the documentation, this will be fixed when the new parser will be used also for parse DDL.

thank you for reporting this.

**Comment by luigidellaquila** [comment]
Hi @nagarajasr 

This issue is fixed in v 2.2 GA

I'm closing this ticket, please reopen if you see any related problems

Thanks

Luigi
