### ISSUE TITLE
Check if a vertex entry belongs to the cluster

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4116]
Hi
is it possible to check the current cluster of a vertex?
Use case:
I create some vertices and I forgot to assign them to the cluster during the create command. Now I want to select the subset and reassign them to the cluster. How can I do this?

As far I know only the cluster rid indicate the corresponding cluster.
This query works but that shouldn't be the way
`select from node where @rid containsText '#18'`

**Comment by maggiolo00** [comment]
If you know the cluster name you could do
select from cluster:cluster_name

**Comment by StarpTech** [comment]
Yes but you can also creates vertices which don't belongs to the cluster and how you can identify them? Of course you can select them by the cluster selection but  e.g create 5 vertices which belongs to cluster `test` and 5 vertices which belongs only to the class itself. Now try to select only the 5 vetices with the class `test`. You can do `select from <class>` but this will include all.

**Comment by maggiolo00** [comment]
Each Class has 1 or more clusters so vertex will be always have a cluster.
If you want to catch them all you do 
`select from <class>`
but you can query single cluster of a class
with the syntax i wroter before

**Comment by StarpTech** [comment]
yes I catch them all but how can I select only such which exist in the cluster?

For better understanding:

````
alter class test addcluster clusterTest
create vertex test content { name : "Peter" }
```

```
create vertex test cluster:clusterTest content { name : "Julia" }
```

How can I select only Peter which wasn't transferred to the cluster?
1. I can select all via `select from <class>`
2. I can select the cluster `select from <cluster><class>`

But no solutions above can check that the vertex x exist in the cluster as record.

**Comment by StarpTech** [comment]
```
+------------------+                              
|                  |                              
|   TestCluster    |                              
|                  |                              
|  #12      +----------------+                    
|           | #12:1|---------|                    
|           | #12:0|---------|                    
|           |      |-|#11:1|--------------+  Peter
+----------------------------|                    
            |----------------|                    
            |----|Test|------|                    
            |----|#11--------|                    
            |----------------|                    
            +----------------+          
```

**Comment by maggiolo00** [comment]
`select from cluster:test` ?

**Comment by StarpTech** [comment]
yes o_O  thanks so a class is also a cluster? Then a cluster is just a extended class?

**Comment by maggiolo00** [comment]
Each class has 1 or more clusters. Cluster are physical file were the data are written.
By Default when you create a class you have one file/cluster with the name of the class

**Comment by StarpTech** [comment]
ok, thanks very much.
