### ISSUE TITLE
Cluster toggle when create new vertex in Studio

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4119]
http://pasteboard.co/jrO15wo.gif

Cluster: `[12, 18]`
The default cluster is `12`

**Comment by maggiolo00** [comment]
Hi @StarpTech 
if you have 2 or more cluster it is normal
The default cluster selection strategy is round robin

http://orientdb.com/docs/2.0/orientdb.wiki/Cluster-Selection.html

**Comment by StarpTech** [comment]
Cool, thanks @maggiolo00 can you also answer this question https://github.com/orientechnologies/orientdb/issues/4116
