### ISSUE TITLE
Schema Evolution

### ISSUE THREAD

**Issue by wcraigtrader** [orientechnologies/orientdb#4120]
Our application has been in development for several months, but now that we've had our first internal beta, we are getting pressed to make changes to our graph schema. What support does OrientDB offer for evolving the schema of a populated database?  (Creating new empty databases isn't a problem.)

Schema Evolution Tasks:

  1. Add a new property to an existing Class
  1. Rename an existing property
  1. Change the type of data for a property (eg: Set -> List, Integer -> Long, String -> List<String>)
  1. Remove an existing property from a Class
  1. Pull Up a property from a sub-class to its parent class
  1. Push Down a property from a super-class to a child class
  1. Change the inheritance structure of an existing Class
  
Again, the problem revolves around a production database with active data.  
Right now it appears that the solution would be to *export* all the data, 
recreate the database with the new schema, and then *import* the data.

**[edit]**
All of our nodes and edges are typed, and derive from super-classes.  EG: Vertex Foo extends MyNode extends V; Edge Sees extends Senses extends MyEdge extends E. All properties have types, and all edges are heavyweight.
**[/edit]**

**Comment by wcraigtrader** [comment]
Do the Export/Import commands support graphs?

**Comment by StarpTech** [comment]
Yes, it does. You can export/import your complete database as JSON and try to configure your new db structure. But moving data to another cluster or class is limited only edges are supported. https://github.com/orientechnologies/orientdb/issues/4125 The json export don't includes your index structure so you have to rebuild it at every import process.

The `ALTER` command should cover the most cases of your schema changes.

**Comment by lvca** [comment]
@StarpTech +1

**Comment by lvca** [comment]
I assigned this to @tglman that worked to the schema migration recently. @tglman could you please respond to all the questions and in case update the documentation? Thanks.

**Comment by tglman** [comment]
Yes we support schema change, but it's slightly different from the relational world.

1. Add a new property to an existing Class:  
You can use [Create Property](http://orientdb.com/docs/last/SQL-Create-Property.html) that will check also if there is not consistent data. 
1. Rename an existing property:  
You can use [Alter Property](http://orientdb.com/docs/last/SQL-Alter-Property.html) but be aware that this will updated all the relative record, and it may take a while.
1. Change the type of data for a property:  
You can use as well [Alter Property](http://orientdb.com/docs/last/SQL-Alter-Property.html) if the data conversion is not possible the alter will fail and do nothing.
for migrate non compatible data you can do a [Drop Property] (http://orientdb.com/docs/last/SQL-Drop-Property.html), update your data, and Create Property   
1. Remove an existing property from a Class:  
You can use  [Drop Property] (http://orientdb.com/docs/last/SQL-Drop-Property.html) and do [Update](http://orientdb.com/docs/last/SQL-Update.html) remove if you want also remove the data.
1. Pull Up a property from a sub-class to its parent class:  
Just use Drop Property and Create Property, no  data will be changed.
1. Push Down a property from a super-class to a child class:  
Same way of Pull Up
1. Change the inheritance structure of an existing Class:  
you can do with [Alter Class](http://orientdb.com/docs/last/SQL-Alter-Class.html) set  SUPERCLASS, be aware that changing this will cause the change in query results following the new hierarchy structure.

The only caveat is that the Create Property and Alter Property, do some check/update of data, that may take a while depends on the amount of your data, and can slow down your system, so I'll suggest to not do it on production system while in heavy use.

**Comment by grexe** [comment]
Is the Migration support specific to the JS backend? Why isn't this available in the Java API?
https://github.com/orientechnologies/orientjs#migrations
Then I could just use the OrientDB.Migration.Manager and implement the interfaces.
