### ISSUE TITLE
Move vertex also with links and edges.

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4125]
Hi
in my opinion the use case that someone move data across clusters or classes  is not an isolated case. Orientdb offers you to connect data by edges or referenced and embedded relationships. It should be able to optionally move vertexes with all relationships and edges. So a user can move data without any fears to loose the data integrity.

e.g
```sql
MOVE VERTEX <source> TO <destination> LINKS TRUE [SET [<field>=<value>]* [,]] [MERGE <JSON>]
```

**Comment by lvca** [comment]
Moving links could be very expensive, because they are uni-directional and finding all the records that are pointed by the vertex you're going to delete requires a full database scan (`find references` command does that).

**Comment by StarpTech** [comment]
Yes it will be very expensive but sometimes it is the last chance to upgrade an existing graph structure without to start from scratch.
