### ISSUE TITLE
Different results of outE()

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4126]
```
outE()[@class=BroughtIntoRight] as outEdgeRight
```

Results no record => `undefined` when a result isn't found otherwise a record as object

```
outE('BroughtIntoRight') as outEdgeRight
```

Results `[]` empty array when a result isn't found otherwise a filled array of records

Both methods should return the same result. By the way: What happens under the hood when I use the syntax `<collection>[<filter>]` in contrast to the pure functional way? I think the second way is the preferred option right?

Driver: Oriento
OrientDb: 2.0.8

**Comment by lvca** [comment]
I confirm the result should be the same. The preferred is the second one because it filters the result set at the beginning, while the second one filters at the end.

**Comment by lvca** [comment]
Now both returns empty array in case of no result.

**Comment by StarpTech** [comment]
thanks
