### ISSUE TITLE
OrientDB allows forward-compatibility!

### ISSUE THREAD

**Issue by G4br13l3** [orientechnologies/orientdb#4130]
OrientDB allows the use of 2.1-x dependencies with 2.0.x installed server, but generates logical errors.

**Comment by lvca** [comment]
OrientDB should check if versions are > than current and raise errors. @tglman can you take this?

**Comment by tglman** [comment]
yes, i'll check that

**Comment by tglman** [comment]
I did some check and we didn't do any breaking changes in the protocol so it should work, and there shouldn't be a problem (also if do that is not a suggested thing to do), can you send us some stacktraces so we can investigate a bit more.

Thank you

**Comment by G4br13l3** [comment]
No Exception is raised, but several unexpected behaviors occur in the final result caused by the version mismatch. I found in my case logical errors on the updating of the properties of the vertices, but no runtime errors occur.

**Comment by lvca** [comment]
@tglman It's not only binary protocol version, but also any of:
- ridbag version
- storage version
- schema version?

**Comment by tglman** [comment]
latest development version of 2.1 doesn't allow to connect, closing
