### ISSUE TITLE
Adding value into EMBEDDEDSET is not working only on first time

### ISSUE THREAD

**Issue by SangWoo-Maeng** [orientechnologies/orientdb#4132]
OrientDB version : 2.0.7
Add property in a vertex schema 
- Name : testprop
- Type : EMBEDDEDSET
- Linked_type : STRING

On first execution following query, not working.
Executing same query on second time, it works.

* update #12:64 add testprop = "aaaaaa"

Before execution field looks empty in studio.
After first execution field value is "[]". Like empty array.
After second execution it works well. Value looks ["aaaaaa"]

EMBEDDEDLIST is works well on first time.
Only EMBEDDEDSET does.

I don't know what did I wrong.

**Comment by Ziink** [comment]
In orientdb-community-2.1-rc3 it doesn't work the second time either. It works only when the field is not null to begin with.
