### ISSUE TITLE
merge clusters

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4133]
If i create too many clusters against one class, is there anyway to merge several clusters to one cluster?

**Comment by StarpTech** [comment]
yes, you can use the `MOVE` command http://orientdb.com/docs/last/SQL-Move-Vertex.html

1. Move all elements to the cluster
2. Drop the old clusters http://orientdb.com/docs/2.0/orientdb.wiki/SQL-Drop-Cluster.html

but be aware "MOVE VERTEX command updates all connected edges, but not links"

**Comment by henryzhao81** [comment]
Thanks
