### ISSUE TITLE
Feature Request ChangeFeed

### ISSUE THREAD

**Issue by tychotatitscheff** [orientechnologies/orientdb#4134]
Maybe it's what #2652 is about.

I would like to know if a changesfeed stream is planned. For example one can think of http://rethinkdb.com/docs/changefeeds/javascript/

It would help a lot to build real time app.

As far as I understand, with #2652, we could just create a suscription to a table ! Then #1227 or something like this should be able to stream change.

WDYT ?

**Comment by lvca** [comment]
Not relevant anymore, closing it.
