### ISSUE TITLE
Problem with NULL in query SELECT

### ISSUE THREAD

**Issue by AntonSukhov** [orientechnologies/orientdb#4136]
In my database IM_0609 OrientDB version 2.0.8 is a class MARKS:
CALIBRATION_DATE:date.
DEVICE_MARK:string
DEVICE_NAME:string
END_MARK_NUM:decimal
MARK_NUM:decimal
PERIOD:decimal
SERIAL_NUM:string

In the class MARKS of 42898973 rows and I have created the index as follows:
CREATE INDEX MARK_NUM_END_MARK_NUM on MARKS(MARK_NUM,END_MARK_NUM) NOTUNIQUE.

I run the following query quickly:
select * from MARKS where (MARK_NUM =84278511 AND END_MARK_NUM
=84278511 AND END_MARK_NUM IS NOT NULL)
```
----+------------+------+-------------------+------------+----------------------------
---------------+------------+--------+-----------+------
#   |@RID        |@CLASS|CALIBRATION_DATE   |DEVICE_MARK |DEVICE_NAME
               |END_MARK_NUM|MARK_NUM|SERIAL_NUM |PERIOD
----+------------+------+-------------------+------------+----------------------------
---------------+------------+--------+-----------+------
0   |#12:42684830|MARKS |2015-02-12 00:00:00|����������������-230|�������������� ���������������������������� ����������
������������ 3-������������|84278511    |84278511|17639127-14|72
----+------------+------+-------------------+------------+----------------------------
---------------+------------+--------+-----------+------

1 item(s) found. Query executed in 0.097 sec(s).
```
And this requires a request to create an index or update query:
select * from MARKS where MARK_NUM =84278511 AND END_MARK_NUM IS NULL
The server displays the following message:
2015-05-12 15:46:43:129 INFO  {db=IM_0609} [TIP] Query 'select * from MARKS where MARK
_NUM =84278511 AND END_MARK_NUM IS NULL' fetched more than 50000 records: to speed up
the execution, create an index or change the query to use an existent index [OProfiler
]

Q: Why do so runs the second query?

**Comment by luigidellaquila** [comment]
Hi @AntonSukhov 
could you please post the result of the following query?

```
EXPLAIN select * from MARKS where (MARK_NUM =84278511 AND END_MARK_NUM
=84278511 AND END_MARK_NUM IS NOT NULL)
```

Thanks

**Comment by luigidellaquila** [comment]
Hi @AntonSukhov 

I double checked it, I think it's because you did not configure the index to store null values, see http://orientdb.com/docs/last/Indexes.html -> "Null values" paragraph
