### ISSUE TITLE
Inconsistent fetchPlan result

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4139]
I just want to execute some simple querys and come across this strange behaviour.

http://orientdb.com/docs/last/Network-Binary-Protocol.html#request_command

Binary driver as `OSQLSynchQuery` **correct result**

```
select from #12:0 fetchplan fetchPlan sponsoredBy:1
```

Results:

```
[ { '@type': 'd',
    '@class': 'Node',
    DisplayName: 'peter',
    Email: 'peter@local',
    Points: 0,
    Position: 'Member',
    Active: false,
    Created: Tue May 12 2015 21:39:13 GMT+0200 (W. Europe Daylight Time),
    SponsoredBy:
     { '@type': 'd',
       '@class': 'Root',
       Name: 'test',
       DisplayName: 'test',
       Email: 'test@local',
       Points: 100,
       Position: 'Admin',
       Active: true,
       Created: Tue May 12 2015 21:39:13 GMT+0200 (W. Europe Daylight Time),
       References: [Object],
       InsertedAtDepth: 0,
       out_BroughtIntoLeft: [Object],
       out_BroughtIntoRight: [Object],
       Mid: '555256e41ea7cb4c1f959812',
       '@rid': [Object] },
    References: [ [Object], [Object] ],
    in_BroughtIntoLeft: [ [Object] ],
    InsertedAtDepth: 0,
    out_BroughtIntoLeft: [ [Object] ],
    Mid: '555256e41ea7cb4c1f959814',
    '@rid': { [String: '#18:1001'] cluster: 18, position: 1001 } } ]
```

---

Binary driver as `OCommandSQL` **doesn't works**

```
[ { '@type': 'd',
    '@class': 'Node',
    DisplayName: 'peter',
    Email: 'peter@local',
    Points: 0,
    Position: 'Member',
    Active: false,
    Created: Tue May 12 2015 21:39:13 GMT+0200 (W. Europe Daylight Time),
    SponsoredBy: { [String: '#19:78'] cluster: 19, position: 78 },
    References: [ [Object], [Object] ],
    in_BroughtIntoLeft: [ [Object] ],
    InsertedAtDepth: 0,
    out_BroughtIntoLeft: [ [Object] ],
    Mid: '555256e41ea7cb4c1f959814',
    '@rid': { [String: '#18:1001'] cluster: 18, position: 1001 } } ]
```

---

Binary driver as `OCommandScript`  **doesn't works**

```
[ { '@type': 'd',
    '@class': 'Node',
    DisplayName: 'peter',
    Email: 'peter@local',
    Points: 0,
    Position: 'Member',
    Active: false,
    Created: Tue May 12 2015 21:39:13 GMT+0200 (W. Europe Daylight Time),
    SponsoredBy: { [String: '#19:78'] cluster: 19, position: 78 },
    References: [ [Object], [Object] ],
    in_BroughtIntoLeft: [ [Object] ],
    InsertedAtDepth: 0,
    out_BroughtIntoLeft: [ [Object] ],
    Mid: '555256e41ea7cb4c1f959814',
    '@rid': { [String: '#18:1001'] cluster: 18, position: 1001 } } ]
```

---

Why it is different? and by the way can you explain me which command is the right tool for which situation?

OrientDb: 2.0.8
Driver: Oriento

**Comment by maggiolo00** [comment]
@StarpTech 

do you still need help on this?

**Comment by lvca** [comment]
Closing because no answer after months. In case please reopen/comment this.

**Comment by StarpTech** [comment]
@lvca if you compare the dates 

Created:  13 May 2015
First Response: 10 Jun

you can see that I got no response of this and nobody inspect or try this issue. What you expect from me? The issue cannot be solved itself.

**Comment by lvca** [comment]
@StarpTech, I run a script that closes the issues in status "waiting reply" but without any answer since long time. This is to avoid zombie.

In this particular case the issue could be still there, let's reopen it and put it in a higher priority to avoid it's there for months again.

**Comment by lvca** [comment]
@tglman could you please look at this asap, maybe it's already fixed because last fix on the return objects?

**Comment by tglman** [comment]
this is fixed in 2.2.x branch, will be released in 2.2.14

**Comment by StarpTech** [comment]
Hi @tglman great News can you reference the commit.

**Comment by tglman** [comment]
hi,

I linked it to the github issue, here it is: https://github.com/orientechnologies/orientdb/commit/4fcb97b1a94b4d89891c326a12b1a7ebcb7e307c

bye

**Comment by tglman** [comment]
Hi,

This has been release in 2.2.14, 
i'm closing this.

Regards
