### ISSUE TITLE
Import of Export Fails due to deleted rows

### ISSUE THREAD

**Issue by jrspriggs** [orientechnologies/orientdb#4140]
Import fails severely when we imported a database another developer had exported.  We encountered this from one of our developers creating a new database and populating it with some small amount of data, but had deleted one of the documents for a class that is used as a linkset.  

So for example, we would have a class vPerson, one of their properties is Race, this is set as a linkset as a person may be multiracial.  For Races, we like having a lookup table, so we create a class of just Race.  It is populated with varying races that a person can claim (Caucasian, Native American, etc).  During the initial loading of this lookup table we had something wrong and deleted the first row.  For example, #16:0.  But we created all of the other records, added Persons and linked them to races.  

Our developer then exported that database for our other developers to import.  We receive a Severe failure error on import.  It appears this is because the json generated for the export correctly links the Person records to the races via the ids in the original database (#16:1, #16:2 etc) but the new database on import doesn't respect those ids on the linked set and starts at #16:0 for creating the records in the Race cluster.   Then the import routine attempts to link the Person record to the selected races, but it uses the original cluster ids (so no #16:0).  So the races end up being incorrectly linked and we hit the Severe Failure error when a Person is linked to the last race (since #16:0 is used again, the ids all bump back one, so array out of bounds error gets tossed with a note about "Severe failure encountered")

**Comment by lvca** [comment]
Do you have any log about this problem on both export and import?

**Comment by lvca** [comment]
Closed after 17 days with no response. In case please reopen it or just comment this.
