### ISSUE TITLE
Zero results when query contains use of lucene index but uses some other index

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#4141]
```SQL
create class test extends v
create property test.user string
create property test.essay string
create index test.user unique
create index test.essay fulltext engine lucene
create vertex test set user = 'myname', essay = 'very short essay'

select from test where essay lucene 'short' and user = 'myname'
select from test where user = 'myname' and essay lucene 'short'
```

The first select query will return a result but the second will not. If we remove index:test.user, then the second select query also works.

In general it seems that OrientDB picks an index based on the first part of the where clause and if thereafter an 'and' condition uses a lucene index, then the query returns zero results.

**Comment by nagarajasr** [comment]
Which version of OrientDB are you using? I am using 2.1-SNAPSHOT and i get a parse error for both queries:

```java
select from test where essay lucene 'short' and user = 'myname'

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #29: Invalid keyword 'LUCENE'
Command: SELECT FROM test WHERE essay LUCENE 'short' AND user = 'myname'

select from test where user = 'myname' and essay lucene 'short'

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #49: Invalid keyword 'LUCENE'
Command: SELECT FROM test WHERE user = 'myname' AND essay LUCENE 'short'

```

**Comment by hbCyber** [comment]
I also ran into this problem, as described in my Google Groups post:
"Unable to use LUCENE FULLTEXT index on field with other indexes"
https://groups.google.com/forum/#!topic/orient-database/pEbUZugDi-s

Needs to be fixed.

**Comment by StarpTech** [comment]
Lucene with orientdb is not well tested. I had also some issues. Use the native fulltext search.

**Comment by hbCyber** [comment]
I have my reasons for using the Lucene index instead of the native fulltext one, such as some Lucene-specific query parameters like fuzziness. If OrientDB boasts the capability of having Lucene indexes, I would prefer if they worked.

**Comment by lvca** [comment]
Current limitation with Lucene is that you have to use it as first condition. You can also do:

```sql
select from ( select from test where essay lucene 'short' ) where user = 'myname'
```

**Comment by hbCyber** [comment]
There are other issues as well. I am also unable to retrieve more than one (1) record using LUCENE even if the query is proper (only one WHERE condition).

Example: I query for a field 'title' in my vertices of type 'Channel'
```sql
SELECT title FROM Channel
```
I get two (2) results:
```
my first #channel
another #channel #test
```

I query with LUCENE:
```sql
SELECT title FROM Channel
WHERE title LUCENE "channel"
```
Only returns one (1) result:
```
another #channel #test
```

Why is that?

**Comment by luigidellaquila** [comment]
Hi guys, 

This issue is already fixed in v. 2.1.

I'm closing it, please reopen if you experience any similar problems

Thanks

Luigi
