### ISSUE TITLE
Using empty List/Set as query parameter in SQL prepared statement causes OStorageException

### ISSUE THREAD

**Issue by hbCyber** [orientechnologies/orientdb#4142]
Using OrientDB 2.0.7 Community

When using SQL prepared statements, passing an empty List or Set will cause an OStorageException to be raised (caused by a inner NoSuchElementException).

This will crash:
```java
OrientGraph db = ...
String sql = "SELECT FROM MyUsers WHERE username NOT IN :usernames";
Map<String, Object> queryParams= new HashMap<>();            
queryParams.put("usernames", new HashSet<String>());

Iterable<Vertex> results = ((Iterable<Vertex>)                     
    db.command(new OSQLSynchQuery<>(sql))
        .execute(queryParams));
```

Instead of crashing, I would've expected the output SQL command to be:
```sql
SELECT FROM MyUsers WHERE username NOT IN []
```

As soon as there is a value, the crash does not occur.
```java
OrientGraph db = ...
String sql = "SELECT FROM MyUsers WHERE username NOT IN :usernames";
Map<String, Object> queryParams= new HashMap<>();            
queryParams.put("usernames", new HashSet<String>() {{ add("test"); }});

Iterable<Vertex> results = ((Iterable<Vertex>)                     
    db.command(new OSQLSynchQuery<>(sql))
        .execute(queryParams));
```
(the above works fine)

I have also reported this in the Google Groups:
https://groups.google.com/forum/#!topic/orient-database/Cs-xNsLMwvo

**Comment by hbCyber** [comment]
As a workaround, you can do this:

If the Set/List is empty, simply do not add the Set/List as a parameter. This way, the query will remain:
```sql
SELECT FROM MyUsers WHERE username NOT IN :usernames
```
Apparently this is valid SQL and will work with OrientDB. And since the Set/List is empty, the above statement would be semantically equivalent.

**Comment by luigidellaquila** [comment]
Hi @hbCyber 

which OrientDB version? Have you tried it against 2.1 rc?

Luigi

**Comment by hbCyber** [comment]
Using OrientDB 2.0.7 Community

Haven't tried 2.1 RC since it is not production ready.
