### ISSUE TITLE
lucene engine issue for v2.1-rc2

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4143]
I do have following issue when create fulltext index wiht lucene engine. any idea?

java.lang.AbstractMethodError: com.orientechnologies.lucene.OLuceneIndexFactory.getLastVersion()I"

**Comment by Ziink** [comment]
You should give more details. I use the same version but don't have any issue creating a lucene index.

**Comment by martingg88** [comment]
1. put orientdb-lucene-2.0-SNAPSHOT-dist.jar into plugins folder and server the server. 
2. create the fulltext index from studio.

**Comment by Ziink** [comment]
Mine is orientdb-lucene-2.1-rc2-dist.jar which came with the orientdb download.
Maybe the problem is due to the mismatch.

**Comment by martingg88** [comment]
where you get this jar library? i can't find it from master download. any idea?

**Comment by Ziink** [comment]
http://orientdb.com/download/

**Comment by martingg88** [comment]
i thought the jar file should come with master download. right?

**Comment by martingg88** [comment]
finally...i got jar plugin only for if i download orientdb from official website. shouldn't we include it when build release for master download?

**Comment by lvca** [comment]
Lucene is an external plugin, so you should compile it apart and put the jars in "plugin" directory.
