### ISSUE TITLE
Unable to execute a custom java function (plugin) from OrientDb's java API

### ISSUE THREAD

**Issue by vinaySimility** [orientechnologies/orientdb#4145]
Hi,
I have created a Custom-Java function which internally uses Guava library to do some hashing of strings.
While this function works without any issue from studio as well as from console, invoking the same from java-api fails with "Error on deserialization of Serializable".

This is happening only when executed from JAVA-API (Object database api). I tried invoking many other functions in the same jar from Java API, they worked fine.

**Comment by lvca** [comment]
The ObjectDB API wraps result set in POJO. I suggest you to use underlying Document API to execute the function.
