### ISSUE TITLE
Projection order impacts of result

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4147]
This works
```sql
select Name as name, * from Node where Email = 'julia@local' fetchPlan SponsoredBy:1
```

and this results in incorrect projection

```sql
select *, Name as name from Node where Email = 'julia@local' fetchPlan SponsoredBy:1
```

The projection `Name` is not transformed to `name`. This issue is unusual.

**Comment by lvca** [comment]
I don't understand. Please could you update the description which statement is working as expected and which is not?

**Comment by StarpTech** [comment]
@lvca updated

**Comment by luigidellaquila** [comment]
fixed in develop branch
