### ISSUE TITLE
ODocument serialization shouldn't invoke save()

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4149]
Guys,

There is following test-case. And it's failing on marked line.

```java
@Test
	public void testSerialization() throws Exception
	{
		ODatabaseDocument db = wicket.getTester().getDatabase(); //CHANGE to your way to get DB
		OSchema schema = db.getMetadata().getSchema();
		OClass classA = schema.createClass("SerA");
		OClass classB = schema.createClass("SerB");
		
		classA.createProperty("name", OType.STRING);
		classB.createProperty("name", OType.STRING);
		classA.createProperty("child", OType.LINKLIST, classB);
		classB.createProperty("parent", OType.LINK, classA);
		
		ODocument docA = new ODocument(classA);
		docA.field("name", "Doc A");
		doSerialization(docA);
		assertEquals(0, db.countClass(docA.getClassName()));
		ODocument docB = new ODocument(classB);
		docB.field("name", "Doc B");
		doSerialization(docB);
		assertEquals(0, db.countClass(docB.getClassName()));
		docA.field("child", Arrays.asList(docB));
		doSerialization(docA);
		assertEquals(0, db.countClass(docA.getClassName()));
		assertEquals(0, db.countClass(docB.getClassName()));  //FAILING HERE!
		doSerialization(docB);
		assertEquals(0, db.countClass(docA.getClassName()));
		assertEquals(0, db.countClass(docB.getClassName()));
		docB.field("parent", Arrays.asList(docA));
		doSerialization(docA);
		assertEquals(0, db.countClass(docA.getClassName()));
		assertEquals(0, db.countClass(docB.getClassName()));
		doSerialization(docB);
		assertEquals(0, db.countClass(docA.getClassName()));
		assertEquals(0, db.countClass(docB.getClassName()));
	}
	private void doSerialization(ODocument doc) throws IOException {
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		ObjectOutputStream oos = new ObjectOutputStream(baos);
		oos.writeObject(doc);
		oos.flush();
		oos.close();
	}
```

I found several issues, which might indirectly linked: #2002 #3851 

In general requirement looks simple: **It should be able to serialize any kind of ODocuments without touching of actual database.**

**Comment by tglman** [comment]
hi @PhantomYdn this is due to the fact that the serialization use the toStream() inside that make recursive save, this is going to be addressed in orient 2.2 with this: https://github.com/orientechnologies/orientdb/issues/2620

**Comment by PhantomYdn** [comment]
Thanks! It's really important for web-frameworks which like to serialize a state between requests. There is no problems with already commited to DB documents, but if you need to work with some documents which were not commited yet (for example, user is working on full-filling of new document) - it become a problem.

I guess you can mark this as dupplicate, if you wish. But I think, that it will be cool to have this testcase in final version.

**Comment by tglman** [comment]
this is implemented in the last develop, closing

**Comment by PhantomYdn** [comment]
@tglman could you please include the testcase in the build? It's failing for me on develop branch...

**Comment by tglman** [comment]
ok, i'll reopen

**Comment by tglman** [comment]
Hi @PhantomYdn,

I tested it, the reason of the failure are some assert that we have in the code for avoid that we write temporary id on the disc, i'll try to think for a solution for work around this problem.

**Comment by tglman** [comment]
Hi @PhantomYdn,

Can we close this issue and open another with the specific topic about not db dependent java serialization ?

The title of this issue confuse me all the time, because since 2.2 this is not true i think we can close this.

Bye

**Comment by PhantomYdn** [comment]
@tglman , sure! New issue has been created for that: #6140
