### ISSUE TITLE
UPDATE UPSERT information after operation

### ISSUE THREAD

**Issue by snig-b** [orientechnologies/orientdb#4150]
Is there a way to know whether update upsert created the record or updated it?
We have a use case that needs separate operations on create and match - something like Neo4j's Merge - ON CREATE & ON MATCH.
How can we do such a thing in orientdb?

**Comment by kowalot** [comment]
What about Version of the record? Can you use that?

**Comment by snig-b** [comment]
Right that is some information, but then again it would require me to do 2 queries. Wouldn't it defeat the purpose of UPSERT all together? 
If I want to set a particular field only on 'modify' or 'create' and not both then I would require 2 queries for this, it would be the same case as selecting the count of existing records and if it is zero then do something for create else update.

Am I right? Any other alternative than this?

On a side-note..while googling about this I came across multiple requests by other users for this same feature. Can we expect any work on this in the near future? It is quite an important distinction between Orientdb and it's competitors that do offer this query support.

**Comment by snig-b** [comment]
@kowalot Thanks for the quick response, I just ran a few tests, and version no. is not very reliant for this purpose. Consider the following scenario:

select from Email where email='test100.hello.com'
Returned 0 records

create vertex Email set email='test100.hello.com'
Returned 1 record @version: 2

delete vertex Email where email='test100.hello.com'
returned 1 row @version: 0 ( successfully deleted )

create vertex Email set email='test100.hello.com'
Returned 1 record @version: 3

Even though the record was newly created, it incremented the version as if it was updated.

**Comment by kowalot** [comment]
As OrientDB user for your purposes I would reconsider
 UPDATE SET ..... UPSERT RETURN BEFORE
You won't get previous record content for record creations, based on that you can change logic.
Additionaly to that I would use 
UPDATE SET X = IFNULL(X,1) ....
which updates only non-present field (for new record)
Does it solve partially your needs?

**Comment by snig-b** [comment]
It does, that's a great help.
Thanks :)

Do also consider a simpler syntax for a combination of these commands as I guess this is a nice and important feature.
