### ISSUE TITLE
Allowing wildcard lucene queries with leading *

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#4151]
Hi,

Is there any setting to allow lucene queries start from a ```*```? Example:

```
SELECT FROM City WHERE name LUCENE "*york*"
```

Apparently this is the default Lucene behavior to keep its performance and a higher level. However, sometimes this comes in useful.

**Comment by andreyvk** [comment]
Invalid? What's invalid about trying to search the way you want to?

Here's a [link](https://wiki.apache.org/lucene-java/LuceneFAQ#What_wildcard_search_support_is_available_from_Lucene.3F) explaining why Lucene does not enable leading wildcard search by default. Which leads to a question: if someone wants to find a part of a word in OrientDB using Lucene indexing, what can he/she do?

**Comment by luigidellaquila** [comment]
Hi Andrey,

maybe I'm wrong, but the issue is still open, so I guess that "invalid"
flag was put there by mistake ;-)

Luigi


2015-05-19 8:54 GMT+02:00 Andrey <notifications@github.com>:

**Comment by andreyvk** [comment]
Thanks for your prompt reply @luigidellaquila. Looking forward to seeing what could be done here :)

**Comment by maggiolo00** [comment]
@andreyvk  i think is not a valid syntax in lucene query

**Comment by andreyvk** [comment]
Hi @maggiolo00,

The ```CommonQueryParserConfiguration.setAllowLeadingWildcard(boolean allowLeadingWildcard)``` (see [referece](https://lucene.apache.org/core/4_4_0/queryparser/org/apache/lucene/queryparser/flexible/standard/CommonQueryParserConfiguration.html#setAllowLeadingWildcard(boolean))) allows leading wildcard characters and therefore the syntax is valid for the query. For the sake of speed and efficiency this option set to ```false``` by default.

The leading wildcard would work exactly as the ```LIKE``` operator in the following query

```sql
select from V where name like '%drey%'
select from V where name lucene '*drey*'
```

Why deny the opportunity for developers to have another powerful search ability? All I am asking is to add a **setting** to OrientDB to be able to turn on or off leading wildcard search. For instance, they do that in [couchdb-lucene](https://github.com/rnewson/couchdb-lucene#other-tricks).

**Comment by pzhan** [comment]
I agree with andreyvk, though Lucene isn't optimized for leading wildcard queries, we should be able to enable it since one might need it and Lucene makes it possible.

For now I'm using 
```SQL
select from V where name like '%drey%'
```
And it's starting to be slow. 

With OrientDB embedded fulltext search, seems like you can't have a partial match search too.

**Comment by robfrank** [comment]
impemented in 2.2.1-SNAPSHOT with a dedicated metadata flag:
```sql

create index Song.title on Song (title) FULLTEXT ENGINE LUCENE metadata {"allowLeadingWildcard": true}
```

HANDLE WITH CARE!

**Comment by smolinari** [comment]
@robfrank - why handle with care?

Scott

**Comment by robfrank** [comment]
Enabling this will slow down the search.  That's all. Use only if you know what you are doing.

**Comment by andreyvk** [comment]
@robfrank thanks! This is great news.
