### ISSUE TITLE
ODistributedException Quorum Questions

### ISSUE THREAD

**Issue by SatishAMP** [orientechnologies/orientdb#4152]
```
--> com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 3 not reached for request (id=1362557 from=Masterlaa2app2266xrp task=tx userName=admin). Timeout=91578ms No server in conflict. Received: {Nodelaa2app2266xrp=[81], Nodelaa2app2264xrp=[81], Masterlaa2app2266xrp=waiting-for-response, Nodelaa2app2265xrp=[81]} [ONetworkProtocolHttpDb]
```

- Question 1 : What is the meaning of  [81] here ? 
- Question 2 : In above log snippet Quorum is 3 and i see that 3 nodes responded one node waiting for response , Still why it failed ?

**Comment by lvca** [comment]
This is a rare case when the timeout is fired and while the management of conflict/timeout, the answer arrives. How many logs like this did you see?

**Comment by SatishAMP** [comment]
I can see lot of logs like this . When our ETL process updates DB using RESTAPi calls . THis is usually happens when the load 20 - 30 upadtes / Sec and the load ran for more than 2 hours.

**Comment by lvca** [comment]
Seems one node start to be slower and timeout expires. Are you executing concurrent operation against nodes during ETL?

**Comment by SatishAMP** [comment]
ETL process always updates only on one node (master) and expected to replicate to all slave nodes.

**Comment by lvca** [comment]
Do you execute any operation on slaves nodes that can slow down the single node? Like queries?

**Comment by SatishAMP** [comment]
Queries will be executed on all the slave nodes (they all are embedded instances) but not sure executing queries will slow down the node performence ?

**Comment by lvca** [comment]
Executing queries will slow down the node for sure, but depends by the kind of query and how many query/sec. Do you have any data on this? The problem could be that a particular node is stressed and quorum is not reached.

**Comment by SatishAMP** [comment]
Do you have any suggestions to handle the Stressed node ?

**Comment by lvca** [comment]
What's the update rate? Could you test by executing just 1 call of batch via HTTP that executes 1 transactions with all your changes? This would reduce the messages between servers of 3x if you have 3 transactions in your batch.

**Comment by SatishAMP** [comment]
Closing this issue .
