### ISSUE TITLE
Outdated documentation on Java API dependencies

### ISSUE THREAD

**Issue by LongYC** [orientechnologies/orientdb#4154]
The [official documentation](http://orientdb.com/docs/last/ "OrientDB Manual - version 2.0") has outdated information regarding the required library to use the Java API in the following pages:

- [Graph API](http://orientdb.com/docs/last/Graph-Database-Tinkerpop.html "Graph API  | OrientDB Manual - version 2.0")
- [Document API](http://orientdb.com/docs/last/Document-Database.html "Document API  | OrientDB Manual - version 2.0")
- [Object API](http://orientdb.com/docs/last/Object-Database.html "Object API  | OrientDB Manual - version 2.0")

`orient-commons-*.jar` is stated as required but this is not true since version 2.0 as it has been absorbed into `orientdb-core-*.jar`. This will probably confuse a lot of new users. It should be either be removed or there should be an explanation that it only applies to version prior to 2.0.

**Comment by lvca** [comment]
You're right, fixed. Thanks.
