### ISSUE TITLE
Console: repair edges tool

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4156]
Edges could be broken for many reasons, like managing graphs in non transaction context. The good thing about edges is that they are bidirectional, so we could repair broken edges easily. Example:

```
#10:4 -> #22:333 -> #14:11
 V1        Edge       V2
```

This is the normal situation on database:

```json
V1(#10:4) = { "out_Friend": "#22:333" }
Edge(#22:333) = { "out": "#10:4", "in": "#14:11" }
V2(#14:11) = { "in_Friend": "#22:333" }
```

In case we have:

```json
V1(#10:4) = { "out_Friend": "#22:333" }
Edge(#22:333) = { "out": "#10:4", "in": "#14:11" }
V2(#14:11) = { "in_Friend":  }
```

We can put `#22:333` inside V2 because by looking at Edge, the back-link is missing.

**Comment by StarpTech** [comment]
+1

**Comment by lvca** [comment]
We already have `repair database --fix-graph` that does this.
