### ISSUE TITLE
Field level security

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4157]
Many users ask for field-level security. This is not supported by OrientDB, but it could be done in the same Security hook. This is my initial proposal:
1. We can store authorization in ORole in the format: `property.<class-name>.<field-name> = CRU`
2. On read if no "R" permission is set, we could just remove the field. On update of document we should merge new content with existent one to avoid non accessible fields are removed 
3. On update if no "U" permission is set and the field arrives as changed, then a OSecurityException is raised
4. On create if no "C" permission is set and the field arrives as filled, then a OSecurityException is raised

**Comment by PhantomYdn** [comment]
+1!
But the following should be taken into consideration: classes and properties might be renamed - so rules should be updated accordingly.

**Comment by lvca** [comment]
@PhantomYdn right.

**Comment by nagarajasr** [comment]
Is the security context passed on to database hooks?

**Comment by joaobarcia** [comment]
+1! This would be extremely valuable for us

**Comment by kbrandwijk** [comment]
What's the current state of this? I'm evaluating OrientDB, but field level security is essential. Also, a way to dynamically define it somehow.

**Comment by lvca** [comment]
This issue has recently got the interest from an OrientDB client that is evaluating of sponsoring it. We should have news in the next week. I keep you posted.

**Comment by PhantomYdn** [comment]
Dear OrientDB team, how is this feature going? We in Orienteer almost implemented this feature and can theoretically port back to OrientDB.

Few words how that was implemented in Orienteer:

1) New ORule.ResourceGeneric which we called simply "FEATURE".
2) OProperty or OClass can have a custom field "orienteer.feature". Multiple properties and classes can have the same value for this field. The same value means that all these classes and properties are logically interconnected. For example, if your app has a "feature" for "bank-accounts management", developer can specify the same value for this custom field to "bank-account" on properties and classes and that will be managed in a single approach.
3) Go to required ORole and add new rule for feature. Resource Generic = FEATURE and specification should be equal to name of your feature (for example "bank-account").

**Comment by kbrandwijk** [comment]
Closed because implemented, or...?

**Comment by andrii0lomakin** [comment]
Hi @kbrandwijk . We are not going to implement this feature in foreseen future. We have added predicate based security and thinks that set of security features is not needed to be extended.

**Comment by kbrandwijk** [comment]
Thanks for the context. That makes sense.
