### ISSUE TITLE
move vertex

### ISSUE THREAD

**Issue by rwnew2012** [orientechnologies/orientdb#4159]
I am using orientDB 2.0.6, I want to move amount of vertices from V to other vertex class.  I tried the command, e.g.

move vertex (select * from V where type=''post") to class:post

it does not move vertex or throws errors. I did it on orientdb console, under both plocal and remote settings with admin. what are possible reasons that it does not work? Thanks

**Comment by lvca** [comment]
Did you tried with 2.0.9?

**Comment by rwnew2012** [comment]
2.0.9 does not work either @lvca

**Comment by lvca** [comment]
@rwnew2012, your query is invalid. you used 2 times ' character before post.

**Comment by rwnew2012** [comment]
I think that is my typo in github, and it would throw me error if the query is invalid. I tried both double quotes and simple quotes
-----------------------------------------------------
orientdb {db=10Mtestgraph}> create class person extends V
Class created successfully. Total classes in database now: 12
orientdb {db=10Mtestgraph}> move vertex (select * from V where nodeType='person') to class:person
orientdb {db=10Mtestgraph}> list classes


CLASSES
----------------------------------------------+------------------------------------+------------+----------------+
 NAME                                         | SUPERCLASS                         | CLUSTERS   | RECORDS        |
----------------------------------------------+------------------------------------+------------+----------------+
 _default                                     | E                                  | 11         |       20000000 |
 E                                            |                                    | 10         |              0 |
 OFunction                                    |                                    | 6          |              0 |
 OIdentity                                    |                                    | -          |              0 |
 ORestricted                                  |                                    | -          |              0 |
 ORIDs                                        |                                    | 8          |              0 |
 ORole                                        | OIdentity                          | 4          |              3 |
 OSchedule                                    |                                    | 7          |              0 |
 OTriggered                                   |                                    | -          |              0 |
 OUser                                        | OIdentity                          | 5          |              3 |
 person                                       | V                                  | 12         |              0 |
 V                                            |                                    | 9          |       10000000 |
----------------------------------------------+------------------------------------+------------+----------------+
 TOTAL = 12                                                                                             30000006 |
----------------------------------------------+------------------------------------+------------+----------------+

**Comment by lvca** [comment]
What's the result of this command?
```sql
select count(*) from V where nodeType='person'
```

**Comment by rwnew2012** [comment]
orientdb {db=10Mtestgraph}> select count(*) from V where nodeType='person'

----+------+-------
#   |@CLASS|count
----+------+-------
0   |null  |3333333
----+------+-------

1 item(s) found. Query executed in 89.63 sec(s).

I found that I could run this command in pyorient (a python module), which makes me think how my query is wrong. Thanks, @lvca

**Comment by lvca** [comment]
@rwnew2012 Sorry I didn't understand: what was the problem?

**Comment by rwnew2012** [comment]
@lvca , sorry to make you confused. The problem is, I have 333333 for nodeType 'person', and I want to move vertex in orientDB console, which does not work. I am not sure whether you knows about pyorient, it is python module, in there I used

client.command("move vertex (select * from V where nodeType='person') to class:person")

but it is not straightforward as orientDB console. I want to use orientDB console to do this database management command. Hope I made myself understood. Thanks!

**Comment by lvca** [comment]
Ok, so the problem exists. Reopened.

**Comment by lvca** [comment]
Tried moving some vertices with demo database and works as expected. Is there any chance to provide your database where I can execute that command? If you can zip it, please remove all *.wal files. Thanks.

**Comment by rwnew2012** [comment]
could you please share the list of command lines that you did on sample database? because the GratefulDeadConcerts does not work for me. The zip file is about one gigabyte, too big to share

**Comment by lvca** [comment]
Found the problem: console doesn't execute "move vertex" command. I fixed this in "develop" branch. @rwnew2012 please could you try the same command from API or Studio (non console)?

**Comment by rwnew2012** [comment]
I am trying it on studio. Thanks so much, @lvca

**Comment by lvca** [comment]
Thanks for the report ;-)
