### ISSUE TITLE
exception when upgrade 1.7.x database to 2.x in distributed mode

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4160]
Create a single node database using odb 1.7.6, then copy whole database to odb 2.0.8 and start by distributed mode, use console to open database (connect remote:localhost/<database> admin admin), it throws deserialized exception but it works fine if log in by studio. The issue similar to https://github.com/orientechnologies/orientdb/issues/3098 but on distributed mode. My observation is distribution configuration document cannot be deserialized correctly.

**Comment by tglman** [comment]
Hi @henryzhao81,
I know the source of the problem, checking and fixing :)

**Comment by tglman** [comment]
hi fixed in develop and 2.0.x, will be out with 2.0.10, closing
