### ISSUE TITLE
invalid count for development version.

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4163]
1. SELECT OUT("task")[@class="assignment"] FROM user WHERE @rid =  #16:487
 return result = []

2. SELECT COUNT(OUT("task")[@class="assignment"]) FROM user WHERE @rid =  #16:487
return result = 1

FYI. By right, it should return 0 instead.

**Comment by lvca** [comment]
What's the problem here? Which version?

**Comment by martingg88** [comment]
1. This is for development version.
2. The issue is return invalid count figure. 
3. as per example above,
    - question 1 have empty result, so question 2 have to return 0 instead. But it return me invalid count which is 1.

**Comment by lvca** [comment]
You should rather do:

    SELECT OUT("task")[@class="assignment"].size() FROM user WHERE @rid = #16:487

or

    SELECT COUNT(EXPAND(OUT("task")[@class="assignment"])) FROM user WHERE @rid = #16:487
