### ISSUE TITLE
Functions variable "orient" is OScriptOrientWrapper not OScriptGraphOrientWrapper

### ISSUE THREAD

**Issue by kstock** [orientechnologies/orientdb#4164]
This error was discovered in 2.0.9, it did not exist in 2.0.8

How to reproduce:

1) create a groovy function in studio in 2.0.9
    `return orient.getGraph()`
2)  try to execute it, you will get the error:

Erroronparsingscriptatposition#0: ErroronexecutionofthescriptScript: fdsf------^org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: Nosignatureofmethod: com.orientechnologies.orient.core.command.script.OScriptOrientWrapper.getGraph()isapplicableforargumenttypes: ()values: [
    
]Possiblesolutions: getClass(),
getAt(java.lang.String),
grep()groovy.lang.MissingMethodException: Nosignatureofmethod: com.orientechnologies.orient.core.command.script.OScriptOrientWrapper.getGraph()isapplicableforargumenttypes: ()values: [
    
]Possiblesolutions: getClass(),
getAt(java.lang.String),
grep()Nosignatureofmethod: com.orientechnologies.orient.core.command.script.OScriptOrientWrapper.getGraph()isapplicableforargumenttypes: ()values: [
    
]Possiblesolutions: getClass(),
getAt(java.lang.String),
grep()

the same function will work in 2.0.8, the expected behavior is being able to access the graph as explained in the docs
```orient.getGraph(), returns the current transactional graph database instance```

Running
```return orient.class```
showed that in 2.0.9 orient has the class OScriptOrientWrapper , while in 2.0.8 it is OScriptGraphOrientWrapper.

**Comment by luigidellaquila** [comment]
Hi @kstock 

this problem was already fixed in 2.1, I'll backport it to 2.0.x

Luigi

**Comment by BrunoSupiot** [comment]
This issue remain in version 2.1RC2

**Comment by luigidellaquila** [comment]
Hi @BrunoSupiot 
it was fixed after RC2, you can find it in "develop" branch and it will be released with RC3

**Comment by luigidellaquila** [comment]
fixed in both 2.0.x and develop (2.1) branches
