### ISSUE TITLE
Wildcard support in projections

### ISSUE THREAD

**Issue by Bretto** [orientechnologies/orientdb#4166]
#2372  as shown in this issue we should be able to have:

```
select *, $o.* as Own from Item 
let $o = in('Own')[0]
```

But in practise I can't get it to work with 2.1 RC-2

error:
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " "." ". "" at line 1, column 13. Was expecting one of: <EOF> <TIMEOUT> ... <AS> ... <FETCHPLAN> ... <LOCK> ... <LET> ... <NOCACHE> ... <PARALLEL> ... <UNWIND> ... ";" ... "," ... <AS> ... "," ...

**Comment by Bretto** [comment]
is this supposed to work ?

**Comment by lvca** [comment]
@luigidellaquila Is this woking with 2.1.2?

**Comment by luigidellaquila** [comment]
yes, it's working fine since first stable 2.1.
@Bretto could you please confirm that it's also working for you?

Thanks

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
