### ISSUE TITLE
OCommandSQLParsingException for update RECORD_ATTRIBUTE

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4168]
this issue apply for developement version. 

will have this exception if you update any record_attribute like @rid, @class...

example as follow 
1. update page set @rid = #56:0 where @rid = #56:0
1. update page set @class = 'test' where @rid = #56:0

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <RECORD_ATTRIBUTE> "@rid "" at line 1, column 38.

**Comment by luigidellaquila** [comment]
Hi @martingg88 

@rid attribute is assigned by the storage and cannot be changed, the same is for @class. If you want to move a document from a class to another or from a cluster to another you have to recreate it.

In graph API there is a MOVE VERTEX statement for this http://orientdb.com/docs/last/SQL-Move-Vertex.html

**Comment by martingg88** [comment]
let's forget about @rid. 

first, I may need @class to store data in cluster. 
second, I may need to update @version if necessary. 

As i know, update on RECORD_ATTRIBUTE work without any issue for previous version. can you bring it back?

**Comment by luigidellaquila** [comment]
Hi Martin,

the same is for @class and @version:

For @class consider this: every cluster belongs to only one class, so all
the records in a cluster have the same @class attribute. Changing the
@class attribute would mean moving the record to another cluster, that is a
high level operation.

@version is used by the transaction engine to manage optimistic
transactions (MVCC), so the use is not allowed to change it manually.

Luigi


2015-05-18 16:36 GMT+02:00 martingg88 <notifications@github.com>:
