### ISSUE TITLE
creating a pLocal factory with .setupPool(min,max) throws an error

### ISSUE THREAD

**Issue by acmeguy** [orientechnologies/orientdb#4172]
hi,

This worked in 2.06 but fails in 2.09:
OrientGraphFactory factory = new OrientGraphFactory("plocal:/var/www/data/" + tenant).setupPool(1, 3000);

Regards,
 -Stefan

**Comment by lvca** [comment]
which error?

**Comment by lvca** [comment]
Fixed long time ago.
