### ISSUE TITLE
not important bug for synch schema

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4174]
Hi i submit a little bug , but is not blocking obviously. 
If i use a Class with name "cluster" or a property with name "cluster" the synchronization of schema give a internal error Error on parsing command at position #0: Encountered " "cluster" "cluster "" at line 1, column 44.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...

**Comment by santo-it** [comment]
Hi,

Thanks for opening this

I was checking some old issues and noticed this one. I have tried to reproduce this with OrientDB v. 2.2.17 but was not able. Please could you provide additional info to reproduce the problem, if this is still current / happening?

It would be interesting to understand if a similar issue is still happening with latest GA version

This issue does not include comments from other users, which can be seen as a good sign

I believe it's safe to tag this with "cannot replicate". Please comment if you are affected or you feel this is still current

Many Thanks,
