### ISSUE TITLE
take the OrientDB as graph databases, The problem of import of big data sets

### ISSUE THREAD

**Issue by hhungry** [orientechnologies/orientdb#4179]
when I import the massive graph with one million nodes and three million edges，it is very slow，the whole time is five hours，why？how can I improve the speed？the code of importing  graph is：

private static void insertVertexs(OrientGraph graph, String vexPath)throws Exception {
		long startTime = 0, endTime = 0;
		double buildTime = 0d;
		startTime = System.nanoTime();
		System.out.println("the begin of inserting nodes...");
		File file = new File(vexPath);
		String line = null;
		try {
			BufferedReader bf = new BufferedReader(new FileReader(file));
			while ((line = bf.readLine()) != null) {
				OrientVertex vex = graph.addVertex(null);
				vex.setProperty("vid", line);// 此处不能设置属性名为"id"，因为系统中已经设置该属性名
			}
			bf.close();
			graph.commit();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			graph.rollback();
			e.printStackTrace();
		}
		endTime = System.nanoTime();
		buildTime = (double) (endTime - startTime) / (1e9);
		System.out.println("the time of inserting nodes in OrientDB is：：" + buildTime);
	}

	private static void insertEdges(OrientGraph graph, String path)throws Exception {
		
		long startTime = 0, endTime = 0;
		double buildTime = 0d;
		startTime = System.nanoTime();

		System.out.println("the begin of inserting edges...");
		File file = new File(path);
		String line = null;
		String[] arrs = null;
		String startId = null, endId = null;
		Vertex startNode = null, endNode = null;
		int num = -1;
		try {
			BufferedReader bw = new BufferedReader(new FileReader(file));
			while ((line = bw.readLine()) != null) {
				if (!line.startsWith("#")) {
					++num;
					if(num==0)
						graphKind=line;
					if (num != 0 && num != 1) {
						arrs = splitt(line);
						startId = arrs[0];
						endId = arrs[1];
						//cost=Integer.parseInt(arrs[2]);//此处用随机数产生相应的权值
						startNode = graph.getVertexByKey("vid", startId);
						endNode = graph.getVertexByKey("vid", endId);
						Edge edge=graph.addEdge(null, startNode, endNode, "Link");
						edge.setProperty("weight", 1);//初始化每条边的权值为1 
						
					}
				}
			}
			bw.close();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			graph.rollback();
			e.printStackTrace();
		}
		endTime = System.nanoTime();
		buildTime = (double) (endTime - startTime) / (1e9);
		System.out.println("the time of inserting edges in OrientDB is：" + buildTime);
	}

**Comment by luigidellaquila** [comment]
Hi,

you can take a look at OGraphBatchInsert and OGraphBatchInsertBasic
classes, just take into consideration that they use RAM as a temporary
cache, so be ready to provide some...

ps. please, use the mailing list for this kind of questions (
https://groups.google.com/forum/#!forum/orient-database), not the issue
tracker

Thanks


2015-05-19 13:25 GMT+02:00 hhungry <notifications@github.com>:
