### ISSUE TITLE
LOCAL SERVER CONFIGURATION displays incorrect entries.

### ISSUE THREAD

**Issue by Arne-Pfeilsticker** [orientechnologies/orientdb#4181]
I changed in the file two configuration parameters in the server.sh file:

```
ORIENTDB_SETTINGS="-Dprofiler.enabled=true -Dstorage.useWAL=false -Dstorage.wal.path=/Volumes/Daten/OrientDBwal/"
```

On the Server Managemet config page in studio the changed parameters are displayed and work correctly.

If the config command is entered, then the changes are not displayed:

```
$ console.sh config
```

OrientDB console v.2.0.8 (build UNKNOWN@r; 2015-04-22 20:47:49+0000) 

LOCAL SERVER CONFIGURATION:

| NAME | VALUE |
| --- | --- |
| storage.useWAL | = true |
| storage.wal.path | = null |

Even if the parameters are changed with a set command:

```
orientdb> set storage.useWAL false
```

and confirmed: storage.useWAL = false
the changes are not shown on a next config call.

Could it be that this error is the cause of the 

```
INFO [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies] 
```

on Server start?

**Comment by dmarcelino** [comment]
I'm experiencing a similar issue with OrientDB v2.0.5 and v2.0.10. In orientdb-server-config.xml I set:

```xml
    <properties>
        ...
        <entry name="ridBag.embeddedToSbtreeBonsaiThreshold" value="2147483647" />
    </properties>
```

Start the server and then check the config via console:

``` shell
$ ./console.sh
orientdb {db=mydb}> connect remote:localhost/mydb admin admin
orientdb {db=mydb}> config

...
| ridBag.embeddedToSbtreeBonsaiThreshold= 40                             |
...
```

No matter what value I try it never changes. If I check via studio it shows the correct value, so I get the impression there is a problem with console.

**Comment by Kalatheeswaran** [comment]
@dmarcelino How did you check via studio?

**Comment by kstock** [comment]
I'm having the same kind of problem in 2.1.0

We have
`<entry value="false" name="index.auto.rebuildAfterNotSoftClose"/>`
in the xml config

if I connect 

`connect remote:localhost root <PW>`

I see the values indicated in the xml configuration. 
I also see those values in the studio if I click 'server management' 

When I connect like

`connect remote:localhost/$dbname root <PW>`


I see index.auto.rebuildAfterNotSoftClose still set to the default true.
I can set it with 
`config set index.auto.rebuildAfterNotSoftClose false`
and it tells me

`Local configuration value changed correctly`


I can disconnect and reconnect and see the value I changed.
If I close the console and start it again, however, the setting is back to true!!


1) is this setting somehow db-specific (as in the values I'm seeing in the server management part of the studio are somehow global config settings that I need to override for each db?)
2) How can I for sure set index.auto.rebuildAfterNotSoftClose to false?

**Comment by lvca** [comment]
Ok, seems a bug in console.

**Comment by laa** [comment]
Hi,

Parameter  index.auto.rebuildAfterNotSoftClose is not relevant any more, it
does not produce any affect.
We rebuild indexes only when you perform any not transaction operation,
otherwise index will not be rebuild.

**Comment by lvca** [comment]
This happened because the parameter was deprecated. Closing the issue.

**Comment by dineiar** [comment]
This is still happening. I'm experiencing the same issue with OrientDB Community v2.2.20 and `storage.useWAL=false`
I'm not sure if my configurations are being ignored or if it's just the console showing the wrong values on read.

**Comment by slenglet** [comment]
I' m experiencing the same bug with the 2.2.30 release . 

```
<properties>
        ...
        <entry name="ridBag.embeddedToSbtreeBonsaiThreshold" value="2147483647" />
</properties>
```

after starting server

```
../bin/console.sh config | grep -i ridBag.embeddedToSbtreeBonsaiThreshold
|84  |ridBag.embeddedToSbtreeBonsaiThreshold             |40   
```
