### ISSUE TITLE
Java client api CPU spikes under heavy load and does not recover

### ISSUE THREAD

**Issue by nmcintyre2014** [orientechnologies/orientdb#4182]
We're seeing an issue with CPU spiking to 100% on orient client boxes when we load test our application (load is substantial, we're basically simulating a DOS attack).  All the threads that are using significant CPU are orient client related threads.  Below is the output from 'top -H' (so the PID column is showing a thread id, not a process id) and a thread dump from the running application.Top output is at https://s3-us-west-2.amazonaws.com/ipe-deps/clone2.tdump.  The thread dump https://s3-us-west-2.amazonaws.com/ipe-deps/clone2_top.txt.

**Comment by tglman** [comment]
Hi @nmcintyre2014l, i checked your dump and i didn't find anything critical, i see a lot of the 'application server' threads getting data from the 'orient server' or queuing up for do a request, this is normal after a kind of DOS attack, the server need some time for get rid of all queued request, by the way after some time(few minutes) it should return to normality, it will be useful to get also the orient server dump if the server, if after a while it don't return to normality.

**Comment by tglman** [comment]
no replay, closing
