### ISSUE TITLE
Database type inconsistency

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4183]
Guys,

**What are you going to do with database type?**
Let me clarify. There are several places where database type just "somehow" mentioned, but there is no actual support of this "feature". And, honestly, I think it will be better to have all DBs created as "graph" (with E and V) and mark "type" as deprecated.

Several snippets from different places

```java
//ODatabaseDocumentTx.set(...)

case TYPE:
      throw new IllegalArgumentException("Database type property is not supported");
...
final static String TYPE = "document";
  public String getType() {
    return TYPE;
  }

//ODatabaseFactory: there is no "storing of a type"

public ODatabaseDocumentTx createDatabase(final String iType, final String url) {
    if (iType.equals("graph"))
      return new ODatabaseDocumentTx(url) {
        @Override
        public <THISDB extends ODatabase> THISDB create() {
          final THISDB db = super.create();
          checkSchema((ODatabase<?>) db);
          return db;
        }
      };
    return new ODatabaseDocumentTx(url);
  }

// And there is no usage of ODatabase.getType() at all.
```

**Comment by lvca** [comment]
We removed db type in 2.2

**Comment by PhantomYdn** [comment]
@lvca , question: will it be possible to use orientdb-core without huge jar from orientdb-graphdb?

**Comment by lvca** [comment]
orientdb-core doesn't depend by orientdb-graphdb, so yes.
