### ISSUE TITLE
Heap Memory Consumption high during continues ETL updates

### ISSUE THREAD

**Issue by SatishAMP** [orientechnologies/orientdb#4185]
Our ETL process updating the DB continuously ( for more than 36 hours now) using Http REST APi . This process supposed to run 24 * 7 . TOday we observed that Orient process taking 98 % of heap size resulting in not accepting any other connections to DB ( like we are trying to connect DB using Binary protocol) , We tok the thread dump and identified that so many threads are in blocked state. This is very high priority . Unable to attach the thaed dump here so will send in mail.

**Comment by tglman** [comment]
Hi All,

I'm helping @luigidellaquila  on the investigation on the stack traces you sent to us, the good point is that we didn't find any deadlock, there are a lot of threads blocked but most of them are part of pool and are waiting for get some data from a queue or something like that, this is quite normal on a massive insert, all the thread pool are stretched to be able to elaborate all the data, and they may be in status blocked while getting more data. I saw other traces in status running or blocked by a running thread, so nothing wrong there.

So the fact that the server is not accepting more connection it doesn't seems related on the number of blocked thread.
For understand what is going on, i would like to know what kind of error you got on the server log when it was not accepting connection anymore, I'm thinking there is a memory related issue.

It can be very useful have a memory dump of the server process together with the sever log, that will allow us to have a complete picture.

In the meanwhile we will try to run some massive import test over http for try to reproduce the problem.

**Comment by SatishAMP** [comment]
Unfortunately , We didn't collected memeory dump and error messages we got while connecting during issues we olst as we resterted process to reduce the outage time. We are also trying to reproduce the issue . Once we reproduce the issue , We will provide all the details.

**Comment by tglman** [comment]
hi @SatishAMP, 

Thank you for your help, we will continue our investigation in parallel as well, one question that may help to delimit the case: do you use server side function in the import procedure?

**Comment by SatishAMP** [comment]
Can you please explain what is Server Side function means ? We are not aware of that terminology.

**Comment by luigidellaquila** [comment]
Hi Satish,

a server side function is a custom Java or Javascript function defined in
the server that can be used in queries or as a REST service.

http://orientdb.com/docs/last/Functions.html
http://orientdb.com/docs/last/SQL-Functions.html#custom-functions-in-java

As far as I can remember, you are not using such a feature in the ETL, but
I don't know about the rest of the application.

Regards

Luigi


2015-05-21 16:06 GMT+02:00 SatishAMP <notifications@github.com>:

**Comment by SatishAMP** [comment]
Hi , Yes your are correct , We are not using any custom java code to make RESTFul API call

**Comment by lvca** [comment]
@SatishAMP What's your configuration? How much total memory do you have on the machine and how much memory did you reserve to OrientDB (look in bin/server.sh file, last line)?

**Comment by tglman** [comment]
hi @SatishAMP,

I did some benchmark, and i produced one fix (this one: https://github.com/orientechnologies/orientdb/commit/76368218da160ba3d4fcf90588354b5c3a689b4f) that should reduce the overload of the closed connections, in this way if the database goes out of memory it will recover in a easier way.

**Comment by lvca** [comment]
@tglman Could you please backport this on 2.0.x (the Ameriprise version is using) ?

**Comment by tglman** [comment]
it's already backported.

**Comment by lvca** [comment]
Closed after no answer. In case please reopen this issue.
