### ISSUE TITLE
invalid result for let part for version  2.1-rc2

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4187]
SELECT *, $story as story FROM page LET $story = (SELECT @rid as rid, url, metadata, done FROM story WHERE $
current.page = $parent.current.@rid and $current.done = false ORDER BY metadata.release_date DESC)

decompose "story" get the following invalid result. you can refer to following url for more discussion . 
https://github.com/codemix/oriento/issues/314#issuecomment-103854210

[ { [String: '#-2:1'] cluster: -2, position: 1 },
{ [String: '#-2:2'] cluster: -2, position: 2 },
{ [String: '#-2:0'] cluster: -2, position: 0 },
{ [String: '#-2:3'] cluster: -2, position: 3 },
{ [String: '#-2:4'] cluster: -2, position: 4 },
{ [String: '#-2:6'] cluster: -2, position: 6 },
{ [String: '#-2:7'] cluster: -2, position: 7 },
{ [String: '#-2:5'] cluster: -2, position: 5 } ]

**Comment by nagarajasr** [comment]
I am not an expert, but I don't think this is a bug. $story is result of a sub-query, OrientDB creates a temporary document to hold the result of the sub-query hence you are seeing the negative rid.

**Comment by martingg88** [comment]
beside the rid. it should return me other fields (etc: url, metadata and doen)  in array structure.  But it return me nothing now.

**Comment by alpeshgaglani** [comment]
I have the same issue - Interestingly, I do see the results in OrientDB studio. I think the results are not coming back in the binary protocol?

**Comment by martingg88** [comment]
yes. i think it's a bug

**Comment by maggiolo00** [comment]
@martingg88 

have you solved this?

**Comment by martingg88** [comment]
Sorry. I don't have any idea about your orientdb in java environment. Please ask your team member to help. thanks.

**Comment by maggiolo00** [comment]
@martingg88 

this should be solved with the latest version of ODB and orientjs
see https://github.com/orientechnologies/orientjs/issues/199

Thanks
