### ISSUE TITLE
Vertex version increased by 2 when creating edge in async replication mode

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4188]
In a asynchronous replication mode create edge operation in certain conditions (e.g. if the edge type is created before the vertex type) increases one of the vertices version by 2 instead of 1, which causes replication issues.

**Comment by optimuspaul** [comment]
I saw something similar, except that I wasn't in async mode and the version was set to the rid, i.e. it was 105 and the rid was #14:105.  It was odd.

**Comment by lvca** [comment]
reproduced.
