### ISSUE TITLE
When one create a specific edge class, it seems that the class name cannot be requested with the in() and out() operator : only labels can be requested. So, is it interesting to create edge classes?

### ISSUE THREAD

**Issue by BrunoSupiot** [orientechnologies/orientdb#4189]
I have the same question for the Java API: in getEdges(final Direction iDirection, final String... iLabels) you can specify labels, but not edge classes

**Comment by micha-nerdlichter** [comment]
I don't know if I got your question right, but by using in() and out() you get the vertex, not the edge. If you want so select by the edge class use ```select outE('YourEdgeClass') from YourVertex```

You even can do ```select outE('YourEdgeClass').in from YourVertex``` to select by the edge class and return the other Vertex.

To return all edge classnames use ```select outE().@class from YourVertex```

**Comment by BrunoSupiot** [comment]
Hello.

 

My question was about the selection of a vertex via a vertex class.

outE() is what I needed.

 

I have the same question with the java API.

This is an extract from my code (where v and vCopy are vertices):

 

                               // iterate from 'owns' OUT edge

                               Iterator<Edge> iter = v.getEdges(Direction.OUT, "owns").iterator();

                               while (iter.hasNext()) {

                                               // get edge from 'owns'

                                               Edge e = iter.next();

                                               db.addEdge("class:owns", vCopy, e.getVertex(Direction.IN), "owns");

                                               …

 

I know that the edge class is ‘Owns’. May I get  v.getEdges() with an Edge class ?

Considering performances, is it better having:

-          A specific edge class for each type of relation ?

-          Standard egdes with labels ?

-           

Thank you for your answer

Bruno

 

 

De : Micha Heigl [mailto:notifications@github.com] 
Envoyé : mercredi 20 mai 2015 22:01
À : orientechnologies/orientdb
Cc : BrunoSupiot
Objet : Re: [orientdb] When one create a specific edge class, it seems that the class name cannot be requested with the in() and out() operator : only labels can be requested. So, is it interesting to create edge classes? (#4189)

 

I don't know if I got your question right, but by using in() and out() you get the vertex, not the edge. If you want so select by the edge class use select outE('YourEdgeClass') from YourVertex

You even can do select outE('YourEdgeClass').in from YourVertex to select by the edge class and return the other Vertex.

To return all edge classnames use select outE().@class from YourVertex

**Comment by luigidellaquila** [comment]
Hi Bruno,

What Tinkerpop calls "label" in Orient DB is mapped to classes, so when you do

``` v.getEdges(Direction.OUT, "owns")```

you are actually asking for outgoing edges where edge class is "owns".
In terms of traversal performance, having different edge classes for different "conceptual" types will give you an advantage, because different edge sets are stored in different fields of the vertex.

**Comment by luigidellaquila** [comment]
This is not actually an issue, so I'm closing this
