### ISSUE TITLE
Out of Memory (Memory Leak)

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4194]
Hi Luca, today i running load testing again 2.0.8, after running for a while, system became extremely slow, and java heap dump file was generated (java_pidxxxx.hprof). In server log, it keep prompting memory monitor log : 
```
2015-05-20 23:03:11:145 INFO  [odb2]:2434 [orientdb] [3.3] processors=8, physical.memory.total=15.6G, physical.memory.free=189.6M, swap.space.total=2.0G, swap.space.free=2.0G, heap.memory.used=394.9M, heap.memory.free=60.6M, heap.memory.total=455.5M, heap.memory.max=455.5M, heap.memory.used/total=86.70%, heap.memory.used/max=86.70%, minor.gc.count=660, minor.gc.time=6280ms, major.gc.count=211, major.gc.time=118413ms, load.process=100.00%, load.system=100.00%, load.systemAverage=780.00%, thread.count=93, thread.peakCount=123, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operation.size=0, executor.q.priorityOperation.size=0, executor.q.response.size=0, operations.remote.size=2, operations.running.size=0, proxy.count=11, clientEndpoint.count=0, connection.active.count=1, connection.count=1 [HealthMonitor]
```

Open jconsole, memory usage was high, and i click 'Perform GC', memory usage was not reduced anymore, so i suspect it maybe a memory leak.

Use the memory dump file to run memory analyze. Following is Leak Suspects result
```
  Problem Suspect 1

13,107 instances of "jdk.nashorn.internal.runtime.RecompilableScriptFunctionData", loaded by "sun.misc.Launcher$ExtClassLoader @ 0xe0048f88" occupy 237,164,384 (61.99%) bytes. These instances are referenced from one instance of "java.lang.Thread", loaded by "<system class loader>"

Keywords
java.lang.Thread
sun.misc.Launcher$ExtClassLoader @ 0xe0048f88
jdk.nashorn.internal.runtime.RecompilableScriptFunctionData

Details »
``

**Comment by lvca** [comment]
We received similar reports by users. @tglman is working on it.

**Comment by tglman** [comment]
hi @henryzhao81, 

Thanks for the reporting, can you send us the jdump? If you cannot will be cool if you can get out the retention paths, that will speed up a lot the fix time.

**Comment by tglman** [comment]
by the way, i've done some small tests on the script invocation, on an local in memory database to check if we have issues there, but i haven't find any.

so it's more luckily that the problem is related to the javascript function  ran from http

**Comment by henryzhao81** [comment]
@tglman please forget my previous memory dump file, i think i may pick up the wrong one. I just did few dumps, here is the result.
Leak Suspects

System Overview

 Leaks 

 Overview


  Problem Suspect 1

One instance of "com.orientechnologies.orient.core.Orient" loaded by "sun.misc.Launcher$AppClassLoader @ 0xe017fea8" occupies 254,485,160 (82.20%) bytes. The memory is accumulated in one instance of "com.orientechnologies.common.concur.resource.OPartitionedObjectPool$PoolPartition[]" loaded by "sun.misc.Launcher$AppClassLoader @ 0xe017fea8".

Keywords
sun.misc.Launcher$AppClassLoader @ 0xe017fea8
com.orientechnologies.common.concur.resource.OPartitionedObjectPool$PoolPartition[]
com.orientechnologies.orient.core.Orient

Details »

**Comment by henryzhao81** [comment]
@tglman please forget my previous memory dump file, i think i may pick up the wrong one. I just did few dumps, here is the result. Leak Suspects

System Overview

Leaks

Overview

Problem Suspect 1

One instance of "com.orientechnologies.orient.core.Orient" loaded by "sun.misc.Launcher$AppClassLoader @ 0xe017fea8" occupies 254,485,160 (82.20%) bytes. The memory is accumulated in one instance of "com.orientechnologies.common.concur.resource.OPartitionedObjectPool$PoolPartition[]" loaded by "sun.misc.Launcher$AppClassLoader @ 0xe017fea8".

Keywords sun.misc.Launcher$AppClassLoader @ 0xe017fea8 com.orientechnologies.common.concur.resource.OPartitionedObjectPool$PoolPartition[] com.orientechnologies.orient.core.Orient

Details »

**Comment by henryzhao81** [comment]
The behavior i observe is, when i increased the concurrent size, the memory usage which cannot be GCed (i keep hitting perform GC in jconsole) is increase as well. 

Eg, at first i send bunch of requests with 2 concurrent, testing for a while then stop wait for avg load drop to 0, using jconsole to monitor the memory, hit the 'perform GC', the memory cannot be GCed is about 130MB. Then i increased the concurrent to 5, sending same requests. After test done, hit 'perform GC', not the memory cannot be GCed is about 340MB. If i set concurrent at large number, the server will running out of memory soon and never get chance to flush those memory.

**Comment by lvca** [comment]
@henryzhao81 thanks for these useful information. OPartitionedObjectPool is used to cache JS (Nashorn in your case) scripts. Seems you keep something in memory in your context. Did you use global variables in your Javascript functions?

**Comment by henryzhao81** [comment]
@lvca, is binding.put(key,value) count as global variables?

**Comment by lvca** [comment]
I guess it remains in the context

**Comment by henryzhao81** [comment]
i am using a clean build without my third-party jar, i still can reproduce this issue

**Comment by lvca** [comment]
Any chance to have a test case that reproduces it? We're going to release 2.1-rc3 and I'd like to fix this if it's a bug.

**Comment by lvca** [comment]
We received the test case at support-@-orientechnologies.com. Thanks.

**Comment by lvca** [comment]
I installed you db in a server on localhost, then I started the test with localhost as host, but I have so many errors like:
```
org.apache.commons.httpclient.NoHttpResponseException: The server localhost failed to respond
	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1976)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.proteus.concurrent.test.HttpClientProxy.send(HttpClientProxy.java:189)
	at com.proteus.concurrent.test.RequestJob2.remoteTest(Test.java:769)
	at com.proteus.concurrent.test.RequestJob2.doIt(Test.java:724)
	at com.proteus.concurrent.threadpool.ThreadHandler.run(ThreadHandler.java:70)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by henryzhao81** [comment]
Hi Luca, i build tag 2.0.8 from scratch, download the file i send to you, copy database files to releases/orientdb-community-2.0.8/databases folder, and run (java -Dfile.encoding=UTF8 -cp "./dist/concurrentTest.jar:./lib/*" com.proteus.concurrent.test.Test 100 20 localhost), i can get response from server correctly. 
Not sure what's going on in your side, can you help check 1. Dose your server can resolve localhost, 2. Make sure there is no space after localhost. 
BTW, you may need jdk1.8.

**Comment by lvca** [comment]
@henryzhao81 I run it with 2.0.11-SNAPSHOT and afte the full run the client ended. Then I open YourKit to see the pending RAM, but after a GC all the memory was freed.

![image](https://cloud.githubusercontent.com/assets/312606/7823578/be011148-03fc-11e5-83d9-85f03b0a08a9.png)

**Comment by lvca** [comment]
By the way the test ended with no problem. How can I reproduce it? Do you have other application parts responsible of memory retain?

**Comment by lvca** [comment]
I also see these messages on OrientDB console:
```
2015-05-26 23:06:18:314 SEVERE {db=pharos} illegal class or method : com.proteus.orientdb.api.security.DataSync/beforeReadRestrictedRecord [OClassTrigger]
2015-05-26 23:06:18:315 SEVERE {db=pharos} illegal class or method : com.proteus.orientdb.hook.security.DrugHandler/beforeReadDrug [OClassTrigger]
```

**Comment by henryzhao81** [comment]
![screenshot 2015-05-26 16 51 44](https://cloud.githubusercontent.com/assets/2687613/7825938/c250c322-03c7-11e5-9db7-2028292ef6cc.png)

**Comment by henryzhao81** [comment]
Luca, testing against develop branch with latest source code, attachment is jconsole screen shot. There are 2 round of tests, each time after test finished, i will do Perform GC. Both had 400MB memory which cannot be free, i think those are the caching. Is the test result looks good to you?

**Comment by lvca** [comment]
I run your test against a OrientB Server 2.0.11-SNAPSHOT, and then I profiled the server, is it right? I can't see your peak of non garbaged memory. Did you install any plugin in the server? Or is it a plain server?

**Comment by henryzhao81** [comment]
It is plain server. What's the spec of your server, i found one line of code in OPartitionedObjectPool.java (  private final int                  maxPartitions  = Runtime.getRuntime().availableProcessors() << 3;), i change this maxPartitions number to << 2, now the test result it different, only 180M memory cannot be GCed, which is pretty similar to your test result.

**Comment by lvca** [comment]
Now only 1 partition is used with `script.pool.maxSize` instances (20 by default). Please let me know if this fixes the problem.
