### ISSUE TITLE
Issues with Authentication using OETL tool and JTDS drivers.

### ISSUE THREAD

**Issue by dreamingbinary** [orientechnologies/orientdb#4195]
I'm having an issue with OETL. I'm trying to use JTDS drivers, which I know works from a different tool (IntelliJ). Wondering if anyone can provide insight.

When I use the following URL with a domain account, this exception is tossed: java.sql.SQLException: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.

I know that this works because I use the same drivers/connection string in IntelliJ just fine.
    "jdbc": {
              "driver": "net.sourceforge.jtds.jdbc.Driver",
              "url" : "jdbc:jtds:sqlserver://10.24.34.20:1433;databaseName=MDM;domain=CARS",
              "userName": "userAccount",
              "userPassword": "password123",
              "query": "select top 10 * from [mdm].[Cars] with (nolock)"
            }

However, when I remove the "domain=CARS" property, and test with a non-domain account, I'm able to access the database. I would rather not use a local SQL account.
    "jdbc": {
              "driver": "net.sourceforge.jtds.jdbc.Driver",
              "url_doesnt_work" : "jdbc:jtds:sqlserver://10.24.34.20:1433;databaseName=MDM",
              "userName": "userAccount",
              "userPassword": "password123",
              "query": "select top 10 * from [mdm].[Cars] with (nolock)"
            }
 
My apologies if this is not the avenue to post this. I've tried with #orientdb IRC channel on Freenode as well.

**Comment by lvca** [comment]
This seems more a JDBC problem. Try looking at some forum about SQL Server like:
- https://social.msdn.microsoft.com/Forums/sqlserver/en-US/bc1373f5-cb40-479d-9770-da1221a0bc95/connecting-to-sql-server-in-a-different-domain-using-jdbc-driver?forum=sqldataaccess and
- http://objectmix.com/jdbc-java/42398-jdbc-connection-sql-server-2005-domain-user.html

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
