### ISSUE TITLE
invalid data return for Embeddedmap

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4198]
I do have found no class or class is empty due to the following flow. any idea?

First, i have stored the data as follows;
{ credit: { crew: [],actor: [] }},

Second, when i query from database and it return me the result which have add the '@type', 'type' and '@class' into the data? any idea. 
{ credit: { '@type' : '', @class: '', type: 'document', crew: [],actor: [] }},

i will have the issue if i save the data that is returned from the previous query because the @class is null/empty. I think @class shouldn't be involved into this json data.

**Comment by lvca** [comment]
In OrientDB you should always specify a class. This will be enforced in the future.

**Comment by martingg88** [comment]
huh? this is just a pure Json data that is not related to any existing class in my database. So  what is the recommend solution to store Json data with no care about @class property?
