### ISSUE TITLE
Wrong number of clusters in distributed

### ISSUE THREAD

**Issue by optimuspaul** [orientechnologies/orientdb#4200]
I set up a single node and added a few classes.  Then added 4 nodes to the group, The classes cluster counts went up to 5, which is probably expected. Then I added another class, but it's cluster count was only 3, so two nodes didn't have a local cluster for that class (as far as I can tell). I added 2 more nodes. the count went up to 5. So still missing 2, right?

So I fixed it by finding which ones were missing and restarting them. It's a familiar pattern to have to restart to fix inconsistencies. Can we not have to do that?

**Comment by optimuspaul** [comment]
It didn't do it wrong the second time I tried it though.

**Comment by lvca** [comment]
Please let me know if you can reproduce this error again with v2.0.15 or v2.1.2.
