### ISSUE TITLE
DB hook for create edge doesn't contain vertices info

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4201]
When creating an edge via: v1.addEdge("edgetype", v2) previously the DB hook was firing with an AFTER_CREATE edge event that contained the information about out and in vertices. In 2.1-SNAPSHOT behaviour changed: now the AFTER_CREATE edge event doesn't contain the information about out and in vertices, but there's one more event that follows: AFTER_UPDATE edge that contains this information. Is it a bug or an expected change of behaviour?

**Comment by lvca** [comment]
This is normal in case your have a tree of object to save. Example:
    V1--->E1--->V2
When OrientDB saves V1, recursively save E1, then V2. But at this point if finds E1 (connections are always bidirectional), so in this case where links are circular, the record is saved as empty, just to get the RID, and then saved. It's not a bug and before 2.1 was the same. 

If you want to avoid this behavior you could try saving the edge: the connected vertices should be saved with just one operation. Please let me know if works.

**Comment by ylopotun** [comment]
But something for sure changed in the recent days. In 2.1-rc2 when we created vertex1, vertex2 and an edge between them, we were getting AFTER_CREATE edge event with vertice ids. With exactly the same scenario in 2.1-SNAPSHOT the behaviour is different... I can send you a small unit test showing this if you need.

**Comment by lvca** [comment]
Can you manage this different behavior in your app?

**Comment by ylopotun** [comment]
yes, we can adjust. I was just making sure it's going to stay like this, so that we don't make useless changes.

**Comment by ylopotun** [comment]
As I can see, AFTER_CREATE edge event in 2.1-SNAPSHOT again contains out/in vertices data. Was the behaviour changed back?

**Comment by lvca** [comment]
I don't know which change was responsible of this apart the changes I did for past your bugs.

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
