### ISSUE TITLE
Exception on executing UPDATE statement in Function in SQL language

### ISSUE THREAD

**Issue by snig-b** [orientechnologies/orientdb#4207]
I am running OrientDB Enterprise Edition 2.1-rc1

When I run the UPDATE command via a Function created in SQL Language I get the following exception:  java.lang.ClassCastException: key should be a String [ONetworkProtocolHttpDb]

Steps to Reproduce:
1.In Studio create a function and choose the language as sql
2.Write an update command eg: UPDATE Person SET name="foo" UPSERT where name="bar"
3.Save and execute the function.

The read command runs fine : Select * from Person

What am I doing wrong?

**Comment by lvca** [comment]
Have you tried with 2.1-rc2?

**Comment by red-0ne** [comment]
I confirm this is happening in studio. Using develop branch (861727d).

**Comment by luigidellaquila** [comment]
fixed in develop branch
