### ISSUE TITLE
Re: [orientdb] Different responses to node selection in studio ?

### ISSUE THREAD

**Issue by redskate** [orientechnologies/orientdb#4210]
Dear community

Waiting for rc3 - I loaded a thesaurus (STW) into an orientDB Java embedded Database which is also visible to orientDB studio from where I try to access / manipulate data. 

Following the tutorial http://orientdb.com/docs/last/Tutorial-Working-with-graphs.html

I started with a simple vertex selection and built the queries: 

1) Select * from V limit 10
2) Select * from V where value like '%dcterm%'
3) select * from V where value = 'http://dbpedia.org/resource/Thesaurus'
4) select * from V where value = 'http\:\/\/dbpedia.org\/resource\/Thesaurus' (a bit awful ...)

Studio results seem to be very different depending on which tab is on:

Tab "Browse":
1) - 10 records (OK)
2) - 0 records (NOK)
3) - a syntax error com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 37. Encountered: <EOF> after : "\'http:"
Probably due to "/" in "http://"  (?)
4) - 0 records after 10 seconds (NOK)

Tab "Graph":
1) - 10 records (OK)
2) - 10 records (the same as 1)) (NOK)
3) - like 2) (NOK)
4) - a syntax error com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 37. Encountered: ":" (58), after : "\'http\\"

So maybe I have picked up the wrong documentation or the wrong orientDB version [ 2.1-rc2], what I would like to formulate and execute is a selection query concerning vertices and edges in a logical RDF context (since data comes from an RDF thesaurus).

Why are the responses so different in both tabs?
How could I formulate a correct query like I wanted?

Thank you in advance

**Comment by maggiolo00** [comment]
hi @redskate 
it is related to
https://github.com/orientechnologies/orientdb/issues/4250
Fixed
