### ISSUE TITLE
 Database 'GreatfulDeadConcerts' is not configured on server 

### ISSUE THREAD

**Issue by beebase** [orientechnologies/orientdb#4211]
How do I authenticate with rest api?
I can't get in with admin/admin. 

com.orientechnologies.orient.core.exception.OConfigurationException: Database 'GreatfulDeadConcerts' is not configured on server (home=/Users/maarten/orientdb-2.1-rc2/databases/) [ONetworkProtocolHttpDb]
2015-05-22 21:18:59:904 SEVERE Internal server error:

![image](https://cloud.githubusercontent.com/assets/446089/7778211/9582eae2-00c9-11e5-91ee-ee1bed7ec695.png)

**Comment by lvca** [comment]
Is it working with Studio? Try to log what Studio does.

**Comment by beebase** [comment]
I can log in with Studio, but the server log does give me a warning:

2015-05-23 06:43:42:032 WARNING ->0:0:0:0:0:0:0:1: Command not found: GET.sqlProfiler/GratefulDeadConcerts [ONetworkProtocolHttpDb]

**Comment by beebase** [comment]
fyi: authentication works fine with other db's like MovieRatings or self created ones.
GratefulDeadConcerts still won't. (also tried on stable release 2.0.9)
