### ISSUE TITLE
Transaction boundary problem

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4212]
Guys,

There is the following test case:

``` java
@Test
    public void testTransactions() throws Exception {
        ODatabaseDocument db = wicket.getTester().getDatabase();
        try {
            assertFalse(db.getTransaction().isActive());
            OSchema schema = db.getMetadata().getSchema();
            OClass classA = schema.createClass("TransA");
            classA.createProperty("name", OType.STRING);
            ODocument doc = new ODocument(classA);
            doc.field("name", "test1");
            doc.save();
            ORID orid = doc.getIdentity();
            db.begin();
            assertTrue(db.getTransaction().isActive());
            doc = orid.getRecord();
            assertEquals("test1", doc.field("name"));
            doc.field("name", "test2");
            doc = orid.getRecord();
            assertEquals("test2", doc.field("name"));
            //There is NO SAVE!
            db.commit();
            /* COMMENT START */
            db.close();
            db = wicket.getTester().getDatabase();
            /* COMMENT STOP */
            doc = orid.getRecord();
            assertEquals("test1", doc.field("name"));

        } finally {
            db.commit();
        }
    }
```

Looks logical - right? We set name=test2 within transaction and didn't save that record - that's why outside of transaction we see old value "test1".

But, please try to comment 2 lines marked correspondingly. After `db.commit()` we should be already outside of transaction and should obtain "test1" as well. But... testcase is failing.

Visibility of changed value outside of transaction leads to quite interesting side effects in case of pooled/shared connections.

There is the workaround: invoke 'db.getLocalCache().clear();' after each `commit()`, but that looks quite strange.

So - what do you think? I understand that inclusion of  'db.getLocalCache().clear();' into `commit()` might lead to some other problems in OrientDB logic.

**Comment by PhantomYdn** [comment]
And one more very interesting test case:

```java
@Test
	public void testTransactions2() throws Exception {
		ODatabaseDocument db = wicket.getTester().getDatabase();
		try {
			assertFalse(db.getTransaction().isActive());
			OSchema schema = db.getMetadata().getSchema();
			OClass classA = schema.createClass("TransB");
			classA.createProperty("name", OType.STRING);
			ODocument doc = new ODocument(classA);
			doc.field("name", "test1");
			doc.save();
			ORID orid = doc.getIdentity();
			
			db.begin();
			assertTrue(db.getTransaction().isActive());
			doc = orid.getRecord();
			assertEquals("test1", doc.field("name"));
			doc.field("name", "test2");
			doc.save();
			doc = orid.getRecord();
			assertEquals("test2", doc.field("name"));
			doc.field("name", "test3");
			assertEquals("test3", doc.field("name"));
			//There is NO SAVE!
			db.commit();
			db.getLocalCache().clear();
			/* COMMENT START */
			//db.close();
			//db = wicket.getTester().getDatabase();
			/* COMMENT STOP */
			doc = orid.getRecord();
			assertEquals("test2", doc.field("name"));
			
		} finally {
			db.commit();
		}
	}
```

As you can see: we are within transaction setting name to "test2", then we are saving that document. And then one more time we are changing the name to "test3" without invocation "save()". And finally "test3" was commited: but we didn't "save" doc with "test3".

**So, something really strange with transactions in OrientDB**

If try to make some analogies between OrientDB and RDBMS it should work like following:

1) `save()` should be used just to "INSERT" new document
2) Once document "loaded" in a transaction: all modifications should be saved on `commit()` (no need explicitly invoke `save()`
3) If p.2 contradict logic of OrientDB - `save()` should be invoked each time we actually change something and wants to allow "commit" those changes at the end of transaction.

**Comment by lvca** [comment]
Did you test this against 2.1-rc3?

**Comment by PhantomYdn** [comment]
That's tested on 2.1-SNAPSHOT.

**Comment by laa** [comment]
Unfortunatelly previous tx mechanics related on logs had flaws it will take about 8-10 days to reimplement it. We have few MT issues I fix them and will reimplement com.orientechnologies.orient.core.tx.OTransactionOptimistic .

**Comment by lvca** [comment]
Hey guys, I don't see this problem as really critical. OrientDB keep track of changed documents, so once you do save() it's in TX heap. If you change the document before the commit, changes are in TX as well. We could fix this problem with a ODocument.copy() on OTx.addRecord(). @laa WDYT?

**Comment by lvca** [comment]
My proposal is to change OTransactionOptimistic:476 from:
```java
txEntry = new ORecordOperation(iRecord, iStatus);
```

to:

```java
txEntry = new ORecordOperation(iRecord.copy(), iStatus);
```

WDYT?

**Comment by laa** [comment]
It will lead to noticalb e performance slowdown for big records, also dirty
fields are not copied on such way, only binary record's content.

On Mon, May 25, 2015 at 3:41 PM, Luca Garulli <notifications@github.com>
wrote:

> My proposal is to change OTransactionOptimistic:476 from:
>
> txEntry = new ORecordOperation(iRecord, iStatus);
>
> to:
>
> txEntry = new ORecordOperation(iRecord.copy(), iStatus);
>
> WDYT?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/4212#issuecomment-105226271>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by lvca** [comment]
You're right. So we could create a document of dirty fields separated by action. Like:
```json
{ "updated": { "name", "Luca" }, "created" : { "amount", "23323" }, "deleted", [ "total" ] }

**Comment by laa** [comment]
ok, example.
We have record let say 512 bytes.
And we update first fiels , call save and then update second field and call save.
Previous tx size was about 512 bytes and new tx size would be 1 kB.
Speed of network operation is 100 times slower  https://gist.github.com/jboner/2841832 than memory operation so we will see noticalble slowdown on remote storage especially if we take in account that we never do disk writes instead we write everything in memor to avoid IO pitfalls. 

It seems like rare operation but every setProperty on graph elelments looks like:
doc.field("f_name", f_value)
doc.save();

so all graph applications which updates more than one field will experience slowdown.
I think that it is too much overhead for this soluition.

WDYT ?

**Comment by lvca** [comment]
@laa why the solution I proposed is bad? Sorry I don't understand.

**Comment by laa** [comment]
In nutshel because it increases set of data which is needed to be sent over network as much time as we cal setProperty of single graph element in graph application. as result noticalble decreasing speed of applications which which work with graph database and remote connection.

**Comment by lvca** [comment]
In my proposal I send only the delta, so much smaller traffic. In past example it was very unfortunate: one   field updated, one created and one removed. In the most common case when you update just one field you'd have something like:
```json
{
  "updated": { "name": "Luca" },
  "version": 23
}
```
Furthermore on the server side it would be much faster because you don't have to call `ODocument.field()` foreach field, but only for changed.

**Comment by laa** [comment]
But what is defference with what I proposed in chat ?

**Comment by PhantomYdn** [comment]
Guys,

I personally, think that making a copy is not an solution. It might lead to a huge number of problems: OOM, reference leakage, "branching" of changes and etc.

I think that following "changes" will make OrientDB transactions more logical:

1) For new objects(documents) to be inserted into DB method `persist()` should be invoked.
2) Once objects loaded in a transaction they should be automatically linked with a the transaction. So every changes will be reflected in DB without need explicitly call `save()`
3) If object was created outside of current transaction: it should be "registered" if we want to keep his state updated by this transaction. Something like `joinTransaction()` might be used.
4) If there is no transaction: `save()` should be invoked explicitly.

Or we can live ahead with just good documenting of current behavior... The only thing, that I would really recommend to change: clearing of cache on commit - ability to see transaction's changes outside of it really strange...

**Comment by laa** [comment]
@PhantomYdn I think we can sort it out without dramatic changes in API, we can not afford them becaus of backwarkd compatiblity.

**Comment by lvca** [comment]
@laa I didn't see any solution in chat, just the idea to put the delta. I was proposing how to store delta in documents.

**Comment by laa** [comment]
First part of issue is fixed. Second part will be fixed in 2.2 version.

**Comment by laa** [comment]
I am developing new design for parallel transactions. It will be fixed as part of this design implementation.

**Comment by PhantomYdn** [comment]
Are you excepting requirements?:)

It will be cool: 

1) To have saving points within transactions.
2) Run hooks also in transaction with proper saving points.
3) To have timeout associated with transaction and checked by oriented core.
4) To have ability to have new rid right in transaction, without need to explicitly commit

**Comment by laa** [comment]
Hi @PhantomYdn 
Yes you are right, we plan to have saving points in transaction, may be not visible at first.
And yes we are planning to update rids at once without delay. But we perform design in background so it is slow movement, but we plan to speed up it once we release live incremental backup.

**Comment by laa** [comment]
Moved to 3.0 as that is ETA of implementation of parallel transactions.

**Comment by laa** [comment]
Will implement in 3.0 if have time
