### ISSUE TITLE
Advance query in Filter field

### ISSUE THREAD

**Issue by Bretto** [orientechnologies/orientdb#4213]
I remember seeing a post on "introducing the full query syntax within the filter area" like

```
select *, in('Discuss')[in('Started')[name ='julie']] as roomId from item
``` 
but I can't find it anymore does anyone know where I can follow the progress on this issue ?
To put my problem in context here is my example:
I am building a chat room engine and I have a graph like so:
```
User---Started--->Room----Discuss--->Item<---Own---User
```
I would like to get all the Items and the roomId associated to the Item for a particular User.
```
select 
    *, in('Discuss').in('Started')[name ='julie'] as roomId
from item
```
so this is going threw the right 'Room' and finds the one started by 'Julie' but it returns Julie's Id, how do I get with this query the Id of that room ? It's like i need to do a 'one back' and get @rid...

I am new to graphs so any pointers would be appreciated.

**Comment by Ziink** [comment]
Bretto, you shouldn't post questions here. It just adds noise and is unlikely to be answered here anyway.

Better places to ask questions
1. https://groups.google.com/forum/#!forum/orient-database
2. http://stackoverflow.com

**Comment by Bretto** [comment]
I did, 
http://stackoverflow.com/questions/30407135/query-on-orientdb-graph
https://groups.google.com/forum/#!topic/orient-database/50zN5O1glNU
still waiting ...
