### ISSUE TITLE
Performance issue with SELECT .. IN ()

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#4218]
The following shows that only two documents were read
```sql
explain select from Item where @rid in [#16:104]
```

but the following shows that the entire Class was scanned.
```sql
explain select from Item where @rid in (#16:104)
```

Similarly the following form of select scans the entire Class.
```sql
select from Item where @rid in (select in() from Tag where tag = 'a tag')
```

Version : orientdb-community-2.1-rc3

**Comment by lvca** [comment]
In this case the fastest way is:
```sql
select from #16:104
```

**Comment by Ziink** [comment]
But there is no workaround for the 3rd form which I imagine is fairly common.

**Comment by lvca** [comment]
The form:

    select from Item where @rid in (select in() from Tag where tag = 'a tag')

Is wrong by design in a GraphDB: you're doing a JOIN. If you're connecting Tag with Item, you can do:

    select expand( in() ) from Tag where tag = 'a tag'

Much faste and readable.

**Comment by Ziink** [comment]
Totally agree on this specific example. 

How would you do updates though? Basically starting from a record of one Class, how would you follow links to records in other classes and modify them in a performant way? 

For example

```sql
update Item set field1 = 'someVal' where @rid in (select in() from Tag where tag = 'a tag')
```

Now, this scans the entire Class. The workaround is to first execute the subquery in the client and then use the return value to use a syntax like 

```sql
update Item set field1 = 'someVal' where @rid in [list of @rids]
```

Maybe the query optimization with IN can be scheduled for sometime down the line?

**Comment by lvca** [comment]
The query above wouldn't scan the entire class, because the IN works with the result set in memory.

**Comment by Ziink** [comment]
Do you mean that the statement
```SQL
update Item set field1 = 'someValue' where @rid in (select in() from Tag where tag = 'a tag')
```
would not do a total scan? The EXPLAIN statement implies that it does..

**Comment by lvca** [comment]
Do you have an index on Tag.tag property?

**Comment by Ziink** [comment]
Yes. I do have an Index on Tag.tag.

The thing is even if the sub-query returns a single value, the main query does a total scan of **Item**.
