### ISSUE TITLE
Studio Usability #1

### ISSUE THREAD

**Issue by redskate** [orientechnologies/orientdb#4219]
Hi

I am using Studio 2.09-rc3, Tab BROWSE and I executed a query showing edges.
In the table for each edge are displayed vertex rid's as url's. Clicking on one of those url's take you to the vertex showing its details. 

Pressing browser "Back" leads you to a blank studio page, where the query and its results are erased.
This is very annoying since one has to reconstruct the query results or to browse links always into new tabs.

Could you please assure that the history() function be executed correctly?

**Comment by maggiolo00** [comment]
I've tested it with 2.0.13 without losing history?
Have you tried with 2.0.13?

**Comment by isturlic** [comment]
@maggiolo00 
It doesn't work in 2.1 rc-5. I agree that it is very annoying.
It should work not only with back button but when you change pages by clicking on "Browse", "Graph" etc.

**Comment by lvca** [comment]
Hi guys, have you tried with a recent v2.2.7?

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
