### ISSUE TITLE
huge amount of memory consumed by OThreadCounters$HashTable

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4223]
OThreadCounters$HashTable grows to the point where it consumes a huge amount of heap space. 

With a heap of 4.4 GB, OThreadCounters$HashTable consumes 47% of memory. OrientDB is consuming around 2.5GB of heap in total.

**Comment by laa** [comment]
It is fixed in rd3 I will backport this .

**Comment by jamieb22** [comment]
Andrey, please us know ASAP when the backport is ready. We have 
production systems that are crashing.

**Comment by jamieb22** [comment]
Andrey

As a long shot, we replaced OThreadCountersHashTable with the latest frm 
the source tree. It made no difference. OThreadCountersHashTable still 
grows . EntryHolder expands to 53m objects, and  consumes 1.7 / 2.5GB of 
RAM.

Jamie

**Comment by jamieb22** [comment]
Updating the classes in the package 
com.orientechnologies.common.concur.lock seems to resolve. Presumably, 
this was a bug in OReadersWriterSpinLock. I've left our server 
processing for 40 minutes now and memory appear stable.

**Comment by jamieb22** [comment]
Andrey, any update on whether you've been able to backport the changes? 
Surely, this issue is classified as critical, thus urgent update is 
necessitated?

**Comment by laa** [comment]
Fixed in 2.0.11 and 2.1
