### ISSUE TITLE
Maybe a filter bug in RC-2

### ISSUE THREAD

**Issue by Bretto** [orientechnologies/orientdb#4225]
This query is returning a array of @rid when only one answer is matching the filter
```
select 
    *, in('Discuss').in('Started')[name ='julie'].out('Started') as roomId
from item
```

A more detail explanation of this issue can be found here: 
https://groups.google.com/forum/#!topic/orient-database/50zN5O1glNU

**Comment by luigidellaquila** [comment]
Hi @Bretto 

This issue was fixed a few months ago in 2.1 (we rewrote the way filters are evaluated when defined in square brackets).

I did a couple of test to double check and and everything seems to be correct. I'm closing this issue, please reopen if you see any related problems

Thanks

Luigi
