### ISSUE TITLE
Exception occurred during query when Edge has named "rid" property.

### ISSUE THREAD

**Issue by mswokk** [orientechnologies/orientdb#4226]
In OrientDB 2.0.7
There is vertex A and B and edge E connect them.
### A--- E ---> B

When I add String property named "rid"  (not @rid), 
following query occurs exception. (where #12:54 is @rid of vertex A)
### select out() from #12:54

Is there any document for reserved or forbidden property name?
Otherwise, I think this should be fixed or documented. 
It was hard to find problem.

**Comment by luigidellaquila** [comment]
Up to v 2.2 "rid" was a reserved word in SQL.
This problem was fixed in v 3.0, now it works as expected

Closing, thanks

Luigi
