### ISSUE TITLE
Problem with composite index that has embeddedset followed by datetime

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#4227]
The following sequence of statements cause exception listed below.

```sql
create class test extends v
create property test.set1 embeddedset string
create property test.t datetime
create index test.i_set1_t on test(set1, t) notunique
create vertex test set set1 = 'asdf', t = sysdate()
update test remove set1 = 'asdf' where set1 = 'asdf'
delete vertex test
```

com.orientechnologies.orient.core.index.OIndexException: Error during removal of entry by key
 --> java.lang.ClassCastException

**Comment by luigidellaquila** [comment]
Reproduced in 2.0.x branch.
See OCompositeKeySerializer, row 376, it seems that the composite index key does not match key types. @laa any ideas?

**Comment by laa** [comment]
Hi @Ziink I have tried several times and can not reproduce the issue on the latest version. Please reopen the issue if you reproduce it.
