### ISSUE TITLE
Scala object changes doesn't persist

### ISSUE THREAD

**Issue by anssirantanen** [orientechnologies/orientdb#4229]
I have scala application that uses OrientDB as database. Database uses object api. I encountered problem when i tried to change fetched entry and save it afterwards.

i'm using following class:

``` scala
class Player
{
  @Id var id: String =_
  var description: String =_
  var ip: String =_
  var last: java.util.Date =_
  var uuid: String =_
  var background_color: String =_
  var logo:String =_
  var mode: String=_
  var offlinemode: String = _
  var refresh: Integer = _
  var ip6: String =_
  var WMAC: String =_
  var LMAC: String =_
  @Version var version: String = _
}


def playerRequest:JsValue =
{
    db= new OObjectDatabaseTx(remote:localhost/DeviceDB).open("admin","admin)
    db.getEntityManager.registerEntityClass(classOf[Player])
      query = db.query(new OSQLSynchQuery[Player]("select from player where uuid= " + uuid.get))

      if (!query.isEmpty) {
        val player: Player = query.get(0)
        player.ip = "1.1.1.1"
        db.get.save(player)
        db.get.close()
        null
}
}
```

Code runs fine doesn't raise any exception or errors and returns null like it should. Problem is that some reason database doesn't register changes. I have other functions that runs one directional transactions just fine without problems but when i try to query and save in same transaction this problem comes up. This can be avoided by creating new player object and copy fields from first player to new player. After copying saving new player works fine.

**Comment by anssirantanen** [comment]
I have managed to isolate the problem. OSQL returns player object but corrupts some fields. Fields are readable but you cant transfer them into other classes. I have tried to transfer values into new objcet but the problem still persist after transfer. if you set second objects id via sql object and use load() to fetch from db will be also corrupted. Loaded player has some fields set up as null instead of correct value.

**Comment by willks** [comment]
Did you ever find a workaround for this? I've been trying to get fields to update once I converted my project to Scala. Initial persist works, but subsequent field updates don't update the POJO (scala). I had to use the BeanProperty annotation to get things just to populate. Maybe it's the way POJOs are converted to java, where by setter methods refer to "this" for property access?

**Comment by anssirantanen** [comment]
Our project switched to document API. If i remember correctly object API handled int fields incorrectly and tried to save them as string field. When we put DB save statement into try and catch block we found some exceptions that was related to this issue.
