### ISSUE TITLE
Index entry left behind on deleting the item that triggered a dynamic hook

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#4234]
Tried in onBeforeUpdate as well as in OnAfterUpdate

```
doc.delete()
```

The record gets deleted but the index entry remains. The index is an automatic unique index.

Also get same result for db.delete(id) and orient.getGraph().command('sql',"delete vertex #17:0" ) where #17:0 is the RID of the current record.

Note: If I delete some other record, then things are find.

orientdb-community-2.1-rc3

**Comment by tglman** [comment]
hi @Ziink,

Indexes are not triggered if you do a delete from an hook, because indexes as well are hooks, please do the delete outside the hook.

This may be fixed in 3.0.

**Comment by tglman** [comment]
Hi,

This has been fixed in 3.0.0

Closing
