### ISSUE TITLE
"Removing disconnected network channel '127.0.0.1:2424/XXX'"/"Database 'remote:localhost/xxx' is closed" when executing queries

### ISSUE THREAD

**Issue by markieww** [orientechnologies/orientdb#4235]
Take the following program:

* create database remote:localhost/testme root rootpw plocal
* Take this code 
```
package orientdb;

import com.orientechnologies.orient.core.sql.query.OSQLSynchQuery;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;

public class NewClass_NoTx
{

    public static void main(String[] args)
    {
        // create database remote:localhost/testme root rootpw plocal
        OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/testme", "root", "rootpw")
                .setupPool(1, 1);

        // Add some vertexes
        {
            OrientGraph graph = factory.getTx();
            {
                for (int i = 0; i < 10000; i++)
                {
                    graph.addVertex(i);
                }
                graph.commit();
            }
            graph.shutdown();
            System.out.println();
            System.out.println("initialisation of vertexes done");
        }

        // Query for vertexes
        System.out.println("starting queries...");
        // OrientGraph graph = factory.getTx();
        OrientGraphNoTx graph = factory.getNoTx();
        OSQLSynchQuery largeQuery = new OSQLSynchQuery("select from V limit 1");

        int size = 0;
        int i = 0;
        try
        {
            for (i = 0; i < 1000000; i++)
            {

                Iterable<Vertex> largeQueryIter = (Iterable<Vertex>) graph.command(largeQuery).execute();
                for (Vertex v : largeQueryIter)
                {
                    size++;
                }
            }
            System.out.println("everything was fine");
        }
        catch (Exception e)
        {
            System.out.println("Error at round " + i + ": # of items=" + size);
            e.printStackTrace();
        }
        graph.shutdown();
    }

}
```
* execute Let it run several times -> exceptions/FATAL warnings (if there are no warnings/exceptions, try it again and again)
  * ```Removing disconnected network channel '127.0.0.1:2424/testme'```
  * ```Error at round 28111: # of items=28111
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'remote:localhost/testme' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2700)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:742)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:119)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:75)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:48)
	at orientdb.NewClass.main(NewClass.java:63)```

What I am doing wrong? 

There is enough heap space.
INFORMATION: OrientDB auto-config DISKCACHE=4.278MB (heap=1.808MB os=8.134MB disk=11.650MB)

I also tested it with several versions of OrientDB 2.0.8/2.0.9/2.0.10/2.1rc3 (on server and client side) with the same result.

The OrientDB server is still running and can be accessed via http://localhost:2480/studio/index.html

**Comment by lvca** [comment]
Found the problem: the problem doesn't happen factory running in debug. I found that the GC is more aggressive in non-debug and call the finalize() of OrientDB OrientGraphFactory causing such problems. If you put the entire code in a try/finally block where the finally call `factory.close()` everything works. Could you test it?

**Comment by markieww** [comment]
So our application has to hold the reference to the OrientGraphFactory?

**Comment by markieww** [comment]
The test works, when the factory is manually hold.
{code}
package sample.orientdbconnectionlostissue;

import com.orientechnologies.orient.core.sql.query.OSQLSynchQuery;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;

public class NewClass_NoTx
{

    public static void main(String[] args)
    {
        // create database remote:localhost/testme root rootpw plocal
        OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/testme", "root", "rootpw")
                .setupPool(1, 1);

        // Add some vertexes
        {
            OrientGraph graph = factory.getTx();
            {
                for (int i = 0; i < 10000; i++)
                {
                    graph.addVertex(i);
                }
                graph.commit();
            }
            graph.shutdown();
            System.out.println();
            System.out.println("initialisation of vertexes done");
        }

        OrientGraphNoTx graph = null;
        // Query for vertexes
        System.out.println("starting queries...");
        // OrientGraph graph = factory.getTx();
        graph = factory.getNoTx();
        OSQLSynchQuery largeQuery = new OSQLSynchQuery("select from V limit 1");

        int size = 0;
        int i = 0;
        try
        {
            final int MAX = 1000000;
            for (i = 0; i < MAX; i++)
            {

                Iterable<Vertex> largeQueryIter = (Iterable<Vertex>) graph.command(largeQuery).execute();
                for (Vertex v : largeQueryIter)
                {
                    size++;
                }
                if (i % 50000 == 0 && i != 0)
                {
                    System.out.println(String.format("%d/%d = %d%%", i, MAX, i * 100 / MAX));
                }
            }
            System.out.println("everything was fine");
        }
        catch (Exception e)
        {
            System.out.println("Error at round " + i + ": # of items=" + size);
            e.printStackTrace();
        }
        System.out.println("Hold a reference to the factory, so it won't get gc'ed " + factory);
        graph.shutdown();
    }

}

{code}

**Comment by lvca** [comment]
The correct way is to close the factory at the end: `factory.close()`.

**Comment by gsine** [comment]
@lvca , I am a bit confused with your comment about "the correct way is to close the factory at the end".

Per documentation in http://orientdb.com/docs/last/orientdb.wiki/Graph-Factory.html, we could acquire the factory once, and then getTx() and shutdown() as and when a transaction instance is required.

In a wildfly kind of environment, the factory could be there "forever". Transaction instances could be acquired and released on-demand.

I am seeing a problem where some graph/tx instance acquired and shutdown are perhaps not closed.
After a while, when I shutdown the wildfly server, I see the following messages -
01:58:39,694 SEVERE [com.orientechnologies.orient.client.remote.OStorageRemote] (default task-11) Removing disconnected network channel '127.0.0.1:2424/testdb'...

**Comment by lvca** [comment]
If you look at the end of the page you mentioned, you'll see you should call factory.close() to remove all the instances in the pool. A pool is a pool, because keeps instances open and reuse it. So the close is needed at the end to free them.
