### ISSUE TITLE
Optimization: set ODocument.setAllowChainedAccess(false) on query and traverse

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4236]
By setting `ODocument.setAllowChainedAccess(false)` reading fields is much more efficient. This is valid on SQL select, traverse and OTraverse as well.

**Comment by tglman** [comment]
Shall we declare the chain access deprecated and false by default ?

this will speed up all the operation against odocument, and in long term this could be solved in a better way by the query engine.

**Comment by lvca** [comment]
:+1:

**Comment by lvca** [comment]
WDYT to set it deprecated now ad change the default behavior in 2.1? Does everything work by setting it to false?

**Comment by tglman** [comment]
tests fail if ran with the setting set to false by default, it need more work that can be done for 2.2

**Comment by lvca** [comment]
Which test fail? The tests that use the field chain?

**Comment by tglman** [comment]
the test failing where test related to sql, so this depends on the refactor of the sql executors.

**Comment by tglman** [comment]
Hi,

With the new query engine this has no meaning anymore, closing.

Regards
