### ISSUE TITLE
How to bulk insert thousands of vertices and edges at once via C#?

### ISSUE THREAD

**Issue by marcelooliveira** [orientechnologies/orientdb#4239]
So far we inserted single vertices/edges via ordinary SQL string, but what the best practice for bulk insert scenario? Thanks in Advance.

**Comment by andreyvk** [comment]
How about using [ETL](http://orientdb.com/docs/2.0/orientdb-etl.wiki/Import-from-DBMS.html) for one?

Another way is to have an (quote-unquote) `SQL` file ready and import it through console. Something like this:

```
# Usage: /path/to/orientdb/bin/console.sh mydata.sql

connect remote:localhost/dbName user pass

declare intent massiveinsert

insert into V set id = uuid(), name = "Foo Bar", data={"foo": "bar"}
insert into V set id = uuid(), name = "Foo Bar 2", data={"foo": "bar 2"}
# etc.
```

All of these are not `C#` specific, but they are classical example of batch inserts. 

Hope someone else can throw some more suggestions on the issue.

**Comment by bato3** [comment]
For verticles: standard INSERT

`INSERT INTO V (id, name, data) VALUES (uuid(),'Foo','bar'), (uuid(),'Foo','bar')`

For edges SQL Bath: https://orientdb.com/docs/2.2/SQL-batch.html

```
begin;
CREATE EDGE E FROM #34:3349  TO #32:3349 ;
CREATE EDGE E FROM #41:10971 TO #33:3348;
commit retry 100;
```
