### ISSUE TITLE
Query on lucene index slower after rebuilding indexes (2.1rc2 and 2.1rc3)

### ISSUE THREAD

**Issue by quantussoftware** [orientechnologies/orientdb#4240]
After rebuilding the lucene index in versions 2.1rc2 or 2.1rc3, the query on this index gets about 3 times slower. Means if query time is 1s, duration is 3s after the 1st rebuild and 9s after the 2nd rebuild and so on.

**Comment by maggiolo00** [comment]
hi @quantussoftware  can you retry with 2.1.2 ?
