### ISSUE TITLE
Distributed in-memory graph database support

### ISSUE THREAD

**Issue by pm-mahesh-wable** [orientechnologies/orientdb#4241]
Hello everyone . 

I am using oriendb 2.0 snapshot and try to distribute graph database on multiple servers using clusters sharding feature supported by oriendb having memory storage , but there is an problem while inserting an more records , the ability of distribution is stoped. Means at one stage we can not access the records from another server.  
Is this is bug or i am doing something wrong ? 

I want to know  is orientdb fully support  in-memory distributed  graph database ?

**Comment by lvca** [comment]
This will be possible thanks to the new incremental backup.

**Comment by pm-mahesh-wable** [comment]
On 09/19/2015 05:42 AM, Luca Garulli wrote:
>
> This will be possible thanks to the new incremental backup.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/orientechnologies/orientdb/issues/4241#issuecomment-141599410>.
>


Hi luca ,

         I dont have very much idea about incremental backup , how to 
possible this with distributed
in-memory graph database . Can you elaborate please ?


thanks & regards

Mahesh Wabale

**Comment by lvca** [comment]
duplicated
