### ISSUE TITLE
Linking Records in a Transaction Does not Work

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#4242]
**Scenario:**

I have two classes. Schema given below;

```
CLASS B {
    PROPERTY name STRING
}

CLASS A {
    PROPERTY name STRING
    PROPERTY bLinkList LINKLIST B
}
```

I want to insert a record to Class B, insert a record to Class A and link new record of class B to the new record of class A. I want to do this in a transaction.

**Code:**

I'm using a server side function for doing this. Following is the code.

```
db.begin();

var bRid = db.command("INSERT INTO B (name) VALUES(\"Jack\") RETURN @rid");
db.command("INSERT INTO A (name) VALUES(\"Jack\")");
db.command("UPDATE A ADD bLinkList = " + bRid);

db.commit();
```

**Facts**

I'm using OrientDB Version : 2.0.3. My DB is a Document DB

**Observation**
1. With in a transaction, this does not work. For bLinkList in Class A, null is inserted
2. With out the transaction this works.

**Comment by GiuliaBrignoli** [comment]
Hi,

Try this function: 

db.begin();

var bRid = db.command("INSERT INTO B(name) VALUES(\"Jack\") RETURN @rid");
db.commit();

db.command("INSERT INTO A(name) VALUES(\"Jack\")");
db.commit();

db.command("UPDATE A SET bLinkList = ["+ bRid+"]");
db.commit();

You need to add "[]" in the UPDATE command, and add commit() for each query.

Bye, Giulia

**Comment by mmacfadden** [comment]
Hello,

We seem to be having the same issue.  One thing though, I don't think adding commit statements is the right answer, if you want this to be transactional where the whole thing succeeds or fails, wouldn't adding commit statement break the transactional nature of the example?  I am actually posting a related but slightly different issue that will reference this one.

**Comment by mmacfadden** [comment]
Here is another example:

```Java
ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:test");
db.activateOnCurrentThread();
db.create();

db.command(new OCommandSQL("CREATE class A")).execute();
db.command(new OCommandSQL("CREATE class B")).execute();
db.command(new OCommandSQL("CREATE Property B.child LINK A")).execute();

db.begin();
ODocument a = new ODocument("A");
a.field("id", "a1");
a.save();

ODocument b1 = new ODocument("B");
b1.field("id", "b1");
b1.field("child", a);
b1.save();

HashMap<String, Object> params = new HashMap<String, Object>();
params.put("a", a);
OCommandSQL updateCommand = new OCommandSQL("INSERT INTO B SET id = 'b2', child = :a");
db.command(updateCommand).execute(params);

db.commit();

List<ODocument> aResult = db.query(new OSQLSynchQuery<ODocument>("SELECT FROM A where id = 'a1'"));
ODocument aQueried = aResult.get(0);

// We see the correct A Document here
System.out.println(aQueried);

List<ODocument> b1Result = db.query(new OSQLSynchQuery<ODocument>("SELECT FROM B where id = 'b1'"));
ODocument b1Queried = b1Result.get(0);

// We see the correct A Document here
System.out.println(b1Queried.field("child"));

List<ODocument> b2Result = db.query(new OSQLSynchQuery<ODocument>("SELECT FROM B where id = 'b2'"));
ODocument b2Queried = b2Result.get(0);

// We see and invalid RID here (#9:-2)
System.out.println(b2Queried.field("child"));

db.close();
```
