### ISSUE TITLE
Select with group by wrongly group data in case of expand

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#4244]
Step for reproduce :
prepare data
```
create vertex V set name="one"
create vertex V set name="two"
create vertex V set name="three"

create edge E from (select from V where name="one") to  (select from V where name="two") set weight=1
create edge E from (select from V where name="one") to  (select from V where name="three") set weight=2
create edge E from (select from V where name="two") to  (select from V where name="one") set weight=3
```

execute a sum query:
```
select  sum(weight) , f.name as name from (
select weight, if(eval('out.name="one"'),out,in) as f  from (
select expand(bothE('E')) from V
)) group by name
```

from this i expect two results but i actually get only one.

**Comment by luigidellaquila** [comment]
@tglman out of curiosity, have you tried with UNWIND...?

2015-05-29 16:40 GMT+02:00 tglman <notifications@github.com>:

**Comment by tglman** [comment]
same problem also with the unwind

**Comment by luigidellaquila** [comment]
are you sure...? I spent some time analyzing this, and the results seem to be correct:

you have three edges, first two start from "one", the third ends to "one"
so for the first two if(eval()) operations, out() is returned, that is vertex "one";
for the third one, in() is returned, that is "one" itself

it the end, the result is correct. 
Please reopen if I'm wrong

**Comment by luigidellaquila** [comment]
are you sure...? I spent some time analyzing this, and the results seem to be correct:

you have three edges, first two start from "one", the third ends to "one"
so for the first two if(eval()) operations, out() is returned, that is vertex "one";
for the third one, in() is returned, that is "one" itself

it the end, the result is correct. 
Please reopen if I'm wrong
