### ISSUE TITLE
CREATE VERTEX with a specific value in a property throws NullPointerException

### ISSUE THREAD

**Issue by marcelooliveira** [orientechnologies/orientdb#4246]
We are trying to create vertices for a range of values in our FeedUser vertex. Strangely, some specific values in our FeedUser.UserId property make the OrientDB Studio
complain about a NullPointer exception during the create process, while other values are inserted without problem. The index is NOTUNIQUE, so the vertices should accept the same UserId property value in many inserts. Is it a known issue? Thanks in advance.

Steps to reproduce the issue:

CREATE VERTEX FeedUser SET UserId = 1207, LastActionDate = '2015-05-29 16:05:00'
^-- successfully inserts one vertex in the database with UserId = 1207

CREATE VERTEX FeedUser SET UserId = 12070, LastActionDate = '2015-05-29 16:05:00'
^-- fails with error: "com.orientechnologies.orient.core.index.OIndexException: Error during insertion of key in index --> java.lang.NullPointerException". Can't insert UserId=12070

We defined the FeedUser vertex with the following structure:

Properties:
=======
FeedId	INTEGER NOT NULL
FeedUserId	INTEGER NULL
LastActionDate	DATE NULL
UserId	INTEGER NULL

Indexes:
======
Name	Type 	Properties	Engine 	Actions
FeedUser.UserId	NOTUNIQUE_HASH_INDEX	["UserId"]	SBTREE

**Comment by lvca** [comment]
This problem seems old. Did you try with v2.1.2?

**Comment by marcelooliveira** [comment]
It's no longer an issue, thank you luca.
