### ISSUE TITLE
Inconsistent query results depending on order of RIDs in array

### ISSUE THREAD

**Issue by dcarr178** [orientechnologies/orientdb#4247]
I have encountered a bug both in orientdb-server v.2.0.5 and in v.2.0.10. It has to do with querying an edge depending on the order of vertices in an array. In the example below:

- Query 1 is correct. Vertex has the specified edge.
- Query 2 is correct. Vertex does not have an edge.
- Query 3 is correct. When querying multiple vertices via an array one has an edge and the other doesn't so one shows null values and the other one has populated values.
- Query 4 is wrong. The result set shows populated edges for both vertices even though one vertex has no edge! The only thing that changed in this query was the order of vertices in the array.

```
OrientDB console v.2.0.10 (build UNKNOWN@r${buildNumber}; 2015-03-12 22:59:10+0000) www.orientechnologies.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb {db=river}> select first(out('rProductChannelProduct')).SKU as SKU, first(out('rProductChannelProduct')).Brand as Brand, @rid from #19:244441

----+------+----+----------+----------
#   |@CLASS|SKU |Brand     |rid
----+------+----+----------+----------
0   |null  |1111|BodyGuardz|#19:244441
----+------+----+----------+----------

1 item(s) found. Query executed in 0.003 sec(s).
orientdb {db=river}> select first(out('rProductChannelProduct')).SKU as SKU, first(out('rProductChannelProduct')).Brand as Brand, @rid from #19:326589

----+------+----------
#   |@CLASS|rid
----+------+----------
0   |null  |#19:326589
----+------+----------

1 item(s) found. Query executed in 0.002 sec(s).
orientdb {db=river}> select first(out('rProductChannelProduct')).SKU as SKU, first(out('rProductChannelProduct')).Brand as Brand, @rid from [#19:326589, #19:244441]

----+------+----------+----+----------
#   |@CLASS|rid       |SKU |Brand
----+------+----------+----+----------
0   |null  |#19:326589|null|null
1   |null  |#19:244441|1111|BodyGuardz
----+------+----------+----+----------

2 item(s) found. Query executed in 0.003 sec(s).
orientdb {db=river}> select first(out('rProductChannelProduct')).SKU as SKU, first(out('rProductChannelProduct')).Brand as Brand, @rid from [#19:244441, #19:326589]

----+------+----+----------+----------
#   |@CLASS|SKU |Brand     |rid
----+------+----+----------+----------
0   |null  |1111|BodyGuardz|#19:244441
1   |null  |1111|BodyGuardz|#19:326589
----+------+----+----------+----------

2 item(s) found. Query executed in 0.002 sec(s).
orientdb {db=river}>
```

**Comment by dcarr178** [comment]
This still happens in v 2.0.12

**Comment by dcarr178** [comment]
I can reproduce (and side-step) this error only because there are two vertices involved. However, it's particularly troublesome because in the majority of cases my from statement is some sort of sub-select in which I have no idea which vertices will be selected, what order they will be selected in, or if the resulting data set will be correct or completely misleading.

**Comment by luigidellaquila** [comment]
Hi @dcarr178 
could you please provide a simple dataset (or a script to create it) to reproduce the problem?

Thanks

**Comment by dcarr178** [comment]
Here is a database backup you can restore: https://www.dropbox.com/s/9qrf9p35e15gr0p/zumint_prod-20150728120635.zip.gz?dl=0. It's 1.3 Gb compressed though - my apologies for the size. Reproduce the error by copying/pasting the commands I provided above.

**Comment by dcarr178** [comment]
Here is a script that easily reproduces the error on orientdb server v2.1.0:

create database remote:localhost/test root xxxxxxxx plocal
create class City extends V
create property City.Name string
create class State extends V
create property State.Name string
create class BelongsTo extends E
insert into City set Name = 'Los Angeles'
insert into City set Name = 'Washington D.C.'
insert into State set Name = 'California'
create edge BelongsTo from (select from City where Name = 'Los Angeles') to (select from State where Name = 'California')
select Name as CityName, first(out('BelongsTo')).Name as StateName from [#11:0]
select Name as CityName, first(out('BelongsTo')).Name as StateName from [#11:1]
select Name as CityName, first(out('BelongsTo')).Name as StateName from [#11:0,#11:1]
select Name as CityName, first(out('BelongsTo')).Name as StateName from [#11:1,#11:0]
select Name as CityName, first(out('BelongsTo')).Name as StateName from City
drop database remote:localhost/test xxxxxxxx orientriver

**Comment by dcarr178** [comment]
Notice that these queries give you the correct result:

```
orientdb {db=test}> select Name as CityName, first(out('BelongsTo')).Name as StateName from [#11:0]

----+------+-----------+----------
#   |@CLASS|CityName   |StateName
----+------+-----------+----------
0   |null  |Los Angeles|California
----+------+-----------+----------

1 item(s) found. Query executed in 0.004 sec(s).
orientdb {db=test}> select Name as CityName, first(out('BelongsTo')).Name as StateName from [#11:1]

----+------+---------------
#   |@CLASS|CityName
----+------+---------------
0   |null  |Washington D.C.
----+------+---------------

1 item(s) found. Query executed in 0.006 sec(s).
orientdb {db=test}> select Name as CityName, first(out('BelongsTo')).Name as StateName from [#11:1,#11:0]

----+------+---------------+----------
#   |@CLASS|CityName       |StateName
----+------+---------------+----------
0   |null  |Washington D.C.|null
1   |null  |Los Angeles    |California
----+------+---------------+----------

2 item(s) found. Query executed in 0.006 sec(s).

```

And these queries give you an incorrect result:

```
orientdb {db=test}> select Name as CityName, first(out('BelongsTo')).Name as StateName from [#11:0,#11:1]

----+------+---------------+----------
#   |@CLASS|CityName       |StateName
----+------+---------------+----------
0   |null  |Los Angeles    |California
1   |null  |Washington D.C.|California
----+------+---------------+----------

2 item(s) found. Query executed in 0.004 sec(s).
orientdb {db=test}> select Name as CityName, first(out('BelongsTo')).Name as StateName from City

----+------+---------------+----------
#   |@CLASS|CityName       |StateName
----+------+---------------+----------
0   |null  |Los Angeles    |California
1   |null  |Washington D.C.|California
----+------+---------------+----------

2 item(s) found. Query executed in 0.006 sec(s).

```

**Comment by timkitch** [comment]
My team is evaluating OrientDB as a potential replacement for our current database solution for our commercial product offering. We're on a very tight schedule to complete our investigation and settle on our DB stack. We're aware of some issues around things like hotAlignment and are willing to wait out fixes for that and deploy as single-node DB for the time being. However, issues like this one - which calls into question whether query results are reliable are show-stoppers for us. We were able to very quickly reproduce the above issue on our own and are very concerned about this to the point where we've started evaluating other options.

Wondering... Is the cause of this issue at least well-understood? Are there other known issues related to query result reliability? If so, is there a commitment to release fixes for these soon?

**Comment by dcarr178** [comment]
I don't know the internals of orientdb-provided functions but for what it's worth I believe this problem is isolated to the first() function. For example, when I changed all of my queries to use the last() function I saw no problems. Sheer luck and trial/error on my part though. Also since my application enforces a one-to-one relationship between these vertices, the first() and last() functions are equivalent in my use case.

**Comment by timkitch** [comment]
Thanks @dcarr178 Aside from this particular case, have you done other testing with OrientDB? if so, do you have any other feedback to offer?

**Comment by dcarr178** [comment]
I'd be happy to chat via phone or email. PM me at twitter @dcarr1781.

**Comment by timkitch** [comment]
@dcarr178 followed you on twitter. please follow me back and I'll be able to PM you there. thanks

**Comment by lvca** [comment]
I added these 2 test cases ´first()´ and ´last()´ and works: https://github.com/orientechnologies/orientdb/commit/5537a207baaaddadcc70fbe8a9678e23e7d0b7f7

**Comment by lvca** [comment]
I'm trying your use case now to see what's happened

**Comment by lvca** [comment]
Reproduced.

**Comment by lvca** [comment]
Thanks, fixed.

**Comment by smolinari** [comment]
Hey Luca. Glad you got this fixed. But, I'd like to offer a word (of support) from a bystander and someone who knows a little about quality management and also looking for a database like Tim. Having any results return incorrectly, to me and like Tim says, is a showstopper bug for any database, even if the type of query is rare. It simply is unacceptable behavior from a database. A total no-go. 

I am not sure if you can categorize issues on Github to match some priority scheme, but you should look into it (and create a catalog of issue types that fit into the categories, like "incorrect return of results = showstopper"). When you see a bug gets categorized as a showstopper, it needs fixing almost as fast as security issues (which are of course prio #1). I also believe fixes to showstoppers should also be hot fix releases. Everyone knows bugs happen. And proper reactions to them, when they are serious enough, would show Orient has a clear grip on produced poor quality. Any other kind of reaction, like a showstopper not being fixed for 3 months, gives a different impression, which needs to be avoided, as it absolutely kills "sales". 

I don't want to sound like I am hacking on your efforts. I most definitely want to support them, as I like the OrientDB product a lot. I am just not certain about its quality.

Scott

**Comment by lvca** [comment]
@smolinari unfortunately on GitHub there is no any priority concept. With clients we have a parallel issue tracker synchronized with GitHub that has the "priority", so it's much easier tracking them.

That said all the committers are doing their best to fix all the issues, but sometimes some issues are not managed with the importance they demand. If you take a look at the issue tracker of other DBMS you can see that happen also there, even with the most blazoned ones.

The good news is that the OrientDB team is every month larger and we already have improved the stability and code coverage. However since this is mainly an OS project with an active community, the role of users (like you all) is fundamental on making OrientDB every day more solid and fast.

**Comment by lvca** [comment]
By the way, the workaround for this issue was using [0] to get the first item:

    select Name as CityName, out('BelongsTo').Name[0] as StateName from City

**Comment by smolinari** [comment]
> The good news is that the OrientDB team is every month larger and we already have improved the stability and code coverage.

Yes, I have noticed this too. Great work!

Scott
