### ISSUE TITLE
Move clusters on different paths (volumes/partitions)

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4248]
We can move clusters on different volume/partition/directory by moving (at database down) files to the new path and creating symbolic links in place. However this cannot be done online and it's more a sort of hack. We could simply introduce a new OCluster.ATTRIBUTE to move it. I was thinking about:

```
ALTER CLUSTER invoice PATH /volume2/
```

**Comment by SDIPro** [comment]
We'd also need to be able to assign the cluster's path during class creation:
```CREATE CLASS ... CLUSTER MyClusterId CLUSTERPATH /SomeVol/SomeData```

What about when adding the class through an attribute during a call to ALTER CLASS ADDCLUSTER?

**Comment by SDIPro** [comment]
What happens if you have existing cluster data and then you call ALTER CLUSTER with the new PATH, will the cluster data be moved automatically?

**Comment by lvca** [comment]
Yes, the command will move the file elsewhere.

**Comment by laa** [comment]
Optional for 3.0
