### ISSUE TITLE
Error updating _allow field

### ISSUE THREAD

**Issue by alexberny** [orientechnologies/orientdb#4249]
I have encountered this error: com.orientechnologies.orient.core.exception.OValidationException: The field 'ORestricted._allow' has been declared as LINKSET of type 'OIdentity' but the value is the document #5:0 of class 'OUser' .
My class extends superclass ORestricted, the _allow filed is set right during field creation but i can add new user for field.

I have this error with Orient version 5.0.9 and 5.0.10.

**Comment by lvca** [comment]
Which OrientDB version?

**Comment by alexberny** [comment]
have this error with Orient version 5.0.9 and 5.0.10.

**Comment by luigidellaquila** [comment]
Hi Alessandro,

do you mean v 2.0.9 and 10

Thanks

Luigi


2015-10-03 17:29 GMT+02:00 Alessandro Bernardi <notifications@github.com>:

**Comment by alexberny** [comment]
Hi,
Yes v2.0.9 and 2.0.10.


Inviato da iPad
