### ISSUE TITLE
Double slash '//' causes problem in browse tab of Studio

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#4250]
Try in browse tab
```sql
select from v where url = "http://google.com"
```

Same problem appears if it is an UPDATE statement. 

Probably same issue as [#4210](https://github.com/orientechnologies/orientdb/issues/4210)

orientdb-community-2.1-rc3

**Comment by madobati** [comment]
A workaround could be:
select from v where url like "http:/%/www.google.com"

bye

**Comment by maggiolo00** [comment]
Fixed in 
https://github.com/orientechnologies/orientdb-studio/issues/250

**Comment by maggiolo00** [comment]
Fixed in 
https://github.com/orientechnologies/orientdb-studio/issues/250
