### ISSUE TITLE
Restart of Distributed Database Instance Deletes Database Directory When Other Databases are Offline

### ISSUE THREAD

**Issue by aliensurfer** [orientechnologies/orientdb#4252]
I was testing OrientDB as part of my analysis of the product for use in a project.  I downloaded v2.0.8 Enterprise and installed it on two servers.  When I eventually discovered that laptop installations refused to join the cluster due to the fact that they were on WiFi rather than wired ethernet, I created a 3 node cluster on WiFi instead.  The one server that had no WiFi was then on its own.  After testing  the solo instance for a few items on my checklist, I shutdown and started the database again with "dserver".  Upon restart, it attempted to pull a copy of the GratefulDeadConcerts database from one of the servers in the cluster.  It eventually timed out since the other members were not online.  I logged into the Workbench and saw that the database was not found.  I checked the file system and saw that OrientDB had deleted the "database" directory.  I restored the "database" directory from the OrientDB tar.gz file, and restarted OrientDB again.  It again deleted the "database" directory.  This protocol seems faulty.  An OrientDB instance that executes in distributed mode should not delete its copy prior to downloading a copy from another instance in the cluster.

**Comment by compensator** [comment]
I don't see a response to this.  IF the administrator is aware that a clustered OrientDB instance will be unable to connect to the other cluster members, the database directory can be backed up and the configuration can be altered to remove the other cluster members.  Obviously, there's an implicit assumption being made by OrientDB in distributed mode that the other cluster members are accessible at startup and this is improper.  I'm surprised that there has been no response to this.  I do see https://github.com/orientechnologies/orientdb/issues/4287 was created 5 days later.  Apparently, losing all of your data on the only active node in your cluster is not that important, despite the fact that it could potentially hold hours or days worth of data new data over the inactive cluster nodes.

**Comment by compensator** [comment]
@lvca How are these bugs triaged?  This one has no response.

**Comment by lvca** [comment]
Hi guys,
Sorry I lost this issue between the others. OrientDB never deletes a database, but moves it under `backup/` directory. However I think you guys are right: if no answer is received from other nodes, current database must be used.

**Comment by lvca** [comment]
Done. It's in 2.1-SNAPSHOT and "develop" branch.

**Comment by compensator** [comment]
So, when the other Distributed DB Nodes in the cluster do return online, how will all databases synchronize?  Should an administrator start only the 2nd Node, then wait until it is synchronized with the one that is running, then bring up the 3rd Node and wait until it is synchronized with the other two (also make decisions about starting the application that uses OrientDB that depends upon the Read Quorum count), and so on?

**Comment by compensator** [comment]
And thanks for the response!

**Comment by lvca** [comment]
As soon as a node is restarted, or it returns reachable, the synchronization is executed automatically. In next release we'll provide faster synchronization thanks to the incremental-backup.

**Comment by compensator** [comment]
I'll take that as a yes to the startup sequence then.  :)
