### ISSUE TITLE
SELECT syntax with = does not work for embeddedlist

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#4253]
orientdb-community-2.1-rc3

Something like
```SQL
SELECT FROM Item where mylist = 'listitem'
```
returns zero results where mylist is of type embeddedlist. Changing '=' to IN syntax works fine.

However, if mylist if of type embeddedset then both syntax work fine.

**Comment by luigidellaquila** [comment]
IMHO the problem is with the embeddedset. Equals operation of a collection against a string should always evaluate to false

**Comment by Ziink** [comment]
That might be so but it seems that 'equal to' performs better than 'in' according to 'explain'.

**Comment by luigidellaquila** [comment]
Thanks, that's a good catch, I'll check this, maybe also IN can be optimized as a consequence.

**Comment by luigidellaquila** [comment]
I checked this, there is no bug here.

Equals is not supposed to compare single items with a list.

I also checked the performance for the two operators, the IN has some more overhead because it has to scan the whole collection.

Thanks

Luigi
