### ISSUE TITLE
ORestricted indexing 

### ISSUE THREAD

**Issue by matuszeman** [orientechnologies/orientdb#4261]
There is a hook which implements ORestricted functionality: com.orientechnologies.orient.core.metadata.security.ORestrictedAccessHook.
ORestrictedAccessHook.onRecordBeforeRead SKIP the record if current user doesn't have access to this record.
Ideally, instead of records being skipped on evaluation only, this should work using indexes, as this might have huge impact on the performance.

Refs:
- https://groups.google.com/forum/#!topic/orient-database/f5zPfUEzeo4

**Comment by matuszeman** [comment]
Any feedback on this please?

**Comment by red-0ne** [comment]
We also make heavy use of the ORestricted class (almost all our classes extend it). We are very concerned with this issue too.
