### ISSUE TITLE
Understanding Orientdb as company and opensource contributor

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4263]
Hi,
sometimes It is really hard to understand what is the goal behind a new feature, milestone or even the whole project. It would be nice if we have one place where we can discuss about all these things. I don't mean a company blog.

What do you think?

**Comment by smolinari** [comment]
The have a google group for discussions.

https://groups.google.com/forum/#!forum/orient-database

Scott

**Comment by StarpTech** [comment]
thanks

**Comment by StarpTech** [comment]
But I don't mean a user community blog but rather what the company moved forward.

**Comment by smolinari** [comment]
Most companies don't say much about what happens internally. But they do have a blog. 

http://orientdb.com/blog/ 

Not much forward looking stuff in the blog, but there is info about the company, like their new president, who came over from MongoDB. It seems to me, they are trying to incorporate customer feedback into their releases. So a lot of what is planned can be seen in the Repo. But, what is visible doesn't extend past the current development branch.    

Scott

**Comment by StarpTech** [comment]
@smolinari thanks for the informationen.
