### ISSUE TITLE
Cannot select from index when class indexed on embeddedset field

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#4264]
May be related to [#4254](https://github.com/orientechnologies/orientdb/issues/4254)
orientdb-community-2.1-rc3

```sql
create class test extends v
create property test.embset embeddedset string
create index test.embset unique
create vertex test set embset = 'asdf'


select from index:test.embset where key = 'asdf'
select from index:test.embset where key = ['asdf']
```

Neither of the select statements return any result.

**Comment by maggiolo00** [comment]
hi @Ziink 
fixed in 2.1.x.
Will land in the next hotfix 

https://github.com/orientechnologies/orientdb/issues/4951
