### ISSUE TITLE
FIND REFERENCES: support for multiple RIDs

### ISSUE THREAD

**Issue by sinfex** [orientechnologies/orientdb#4265]
**FIND REFERENCES** should accept a list of Record IDs just like **SELECT** and **UPDATE** do (sadly **[DELETE](3177)** still does not allow this in 2.1-rc3, either):

> \> FIND REFERENCES [#1:2, #1:3]

> > Error: java.lang.IllegalArgumentException: Argument received '[#1:2, #1:3]' is not a RecordId in form of string.

Currently this is only possible with a subquery:

> \> FIND REFERENCES (SELECT FROM [#1:2, #1:3])

>

**Comment by lvca** [comment]
Since you can use the select this is not needed. By the way in 2.1-SNAPSHOT the delete works ;-)
