### ISSUE TITLE
FIND REFERENCES: parent classes

### ISSUE THREAD

**Issue by sinfex** [orientechnologies/orientdb#4266]
Should **FIND REFERENCES** support searching in parent (upper-level) classes?

If classes `V1 and V2 extend V` and `#1:2 is referenced by records of types V1 and V2`, *referredBy* returned by the following query appears to be empty:

> \> FIND REFERENCES #1:2 [V]

This, of course, works as expected:

> \> FIND REFERENCES #1:2 [V1,V2]

P.S: should such functionality be implemented, am I wrong to assume this should allow to search parent classes that happen to also be abstract?

**Comment by lvca** [comment]
find reference is not polymorphic, so check the exact class. So this isn't supported and you have to enlist all the classes
