### ISSUE TITLE
FIND REFERENCES as a sub-query

### ISSUE THREAD

**Issue by sinfex** [orientechnologies/orientdb#4267]
Is there a particular reason **FIND REFERENCES** cannot be used as a sub-query?

> \> SELECT FROM (FIND REFERENCES V)

> > Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <FROM> "FROM "" at line 1, column 8.

**Comment by lvca** [comment]
Do rather: 

    find references ( select from V )

**Comment by lvca** [comment]
Try also:
    select from ( select expand( referredBy ) from ( find references (select from V limit 1) ) ) where @class = 'HasCategory'
