### ISSUE TITLE
FIND REFERENCES: subquery + class filter

### ISSUE THREAD

**Issue by sinfex** [orientechnologies/orientdb#4268]
It would be great if **FIND REFERENCES** would allow to specify both a sub-query AND a class filter:

> \> FIND REFERENCES (SELECT FROM V) V

> > Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #30: Class list must be contained in []

I am not sure if there's even a workaround for this right now (without issuing several queries) as **FIND REFERENCES** results cannot be used in another query (#4267)

**Comment by lvca** [comment]
This is an example to use it with select:

    select from ( select expand( referredBy ) from ( find references (select from V limit 1) ) ) where @class = 'HasCategory'
