### ISSUE TITLE
Pressing Ctrl+C (SIGINT) while in console.sh borks terminal on Mac OSX

### ISSUE THREAD

**Issue by whitej125** [orientechnologies/orientdb#4271]
Similar experience to an old issue:
https://github.com/orientechnologies/orientdb/issues/705

Its a simple reproducer, in Terminal from Mac OSX... I run console.sh.  If I Ctrl+C (aka, SIGINT)... my terminal is left in one of two states:
- Bash terminal is no longer receiving input (we're just hung)
- Bash terminal receives input but is not echoing the commands back out to terminal (ie... I can type and execute commands, but can never see what I am typing)

Either way... it renders the session useless.  Pretty big annoyance as I explore the functionality here.

My environment:
- Mac OSX Yosemite
- OrientDB Community 2.0.10
- Java version 1.8.0_25

**Comment by sinfex** [comment]
If I might add, it's sad the console emulates readline support poorly as a whole.

Just FYI, I assume the workaround for Mac OS X users in this case is the same as Linux users (with yours truly among them): calling *stty* (typing "**stty echo**" blind and hitting Enter) to re-enable the terminal echo-back.

**Comment by whitej125** [comment]
Yep, stty echo did the trick.

**Comment by lvca** [comment]
I wasn't able to catch the abnormal termination of JVM to execute "stty echo" by console. Anyone has a better idea?
