### ISSUE TITLE
Classes lose custom fields after import / export operations

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#4272]
I use 
OrientDB Server v2.1-rc3 (build UNKNOWN@r${buildNumber}; 2015-05-22 16:53:13+0000) 

orientdb> **create database remote:localhost/test root password plocal**
Creating database [remote:localhost/test] using the storage type [plocal]...
Connecting to database [remote:localhost/test] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost/test

orientdb {db=test}> **create class testCust**

Class created successfully. Total classes in database now: 11

orientdb {db=test}> **alter class testCust custom myCustomField = tro-lo-lo**

Class updated successfully

orientdb {db=test}> **select customFields from (select expand(classes) from metadata:schema) where name = 'testCust'**

----+------+-------------------------
\#  | @ CLASS|customFields
----+------+-------------------------
0   |null  |{myCustomField=tro-lo-lo}
----+------+-------------------------

1 item(s) found. Query executed in 0.017 sec(s).

orientdb {db=test}> **export database D:/test**
Exporting current database to: database D:/test in GZipped JSON format ...

Started export of database 'test' to D:/test.json.gz...
Exporting database info...OK
Exporting clusters...OK (12 clusters)
Exporting schema...OK (11 classes)
Exporting records...
- Cluster 'internal' (id=0)...OK (records=3/3)
- Cluster 'index' (id=1)...OK (records=5/5)
- Cluster 'manindex' (id=2)...OK (records=1/1)
- Cluster 'default' (id=3)...OK (records=0/0)
- Cluster 'orole' (id=4)...OK (records=3/3)
- Cluster 'ouser' (id=5)...OK (records=3/3)
- Cluster 'ofunction' (id=6)...OK (records=0/0)
- Cluster 'oschedule' (id=7)...OK (records=0/0)
- Cluster 'orids' (id=8)...OK (records=0/0)
- Cluster 'v' (id=9)...OK (records=0/0)
- Cluster 'e' (id=10)...OK (records=0/0)
- Cluster 'testcust' (id=11)...OK (records=0/0)

Done. Exported 15 of total 15 records

Exporting index info...
- Index OUser.name...OK
- Index dictionary...OK
- Index ORole.name...OK
OK (3 indexes)
Exporting manual indexes content...
- Exporting index dictionary ...OK (entries=0)
OK (1 manual indexes)

Database export completed in 135ms

orientdb {db=test}> **create database remote:localhost/test2 root password plocal**

Creating database [remote:localhost/test2] using the storage type [plocal]...
Disconnecting from the database [test]...OK
Connecting to database [remote:localhost/test2] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost/test2
orientdb {db=test2}> **import database D:/test.json.gz**

Importing database database D:/test.json.gz...
Started import of database 'remote:localhost/test2' from D:/test.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class E was removed.
- Class V was removed.
- Class ORestricted was removed.
- Class OTriggered was removed.
- Class OSchedule was removed.
- Class ORIDs was removed.
- Class OFunction was removed.
Removed 7 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'oschedule'...OK, assigned id=7
- Creating cluster 'orids'...OK, assigned id=8
- Creating cluster 'v'...OK, assigned id=9
- Creating cluster 'e'...OK, assigned id=10
- Creating cluster 'testcust'...OK, assigned id=11
Rebuilding indexes of truncated clusters ...
Done 2 indexes were rebuilt.
Done. Imported 10 clusters
Importing database schema...OK (11 classes)

Importing records...

Started migration of links (-migrateLinks=true). Links are going to be updated according to new RIDs:
- Cluster orids... Completed migration of 0 records in current cluster
- Cluster e... Completed migration of 0 records in current cluster
- Cluster testcust... Completed migration of 0 records in current cluster
- Cluster ouser... Completed migration of 3 records in current cluster
- Cluster default... Completed migration of 0 records in current cluster
- Cluster oschedule... Completed migration of 0 records in current cluster
- Cluster orole... Completed migration of 3 records in current cluster
- Cluster v... Completed migration of 0 records in current cluster
- Cluster ofunction... Completed migration of 0 records in current cluster
Total links updated: 6

Done. Imported 7 records in 0,04 secs

Importing indexes ...
- Index 'OUser.name'...OK
- Index 'dictionary'...OK
- Index 'ORole.name'...OK
Done. Created 3 indexes.
Importing manual index entries...
- Index 'dictionary'...OK (0 entries)
Done. Imported 1 indexes.
Rebuild of stale indexes...
Stale indexes were rebuilt...
Deleting RID Mapping table...OK

Database import completed in 1521 ms

orientdb {db=test2}> **select customFields from (select expand(classes) from metadata:schema) where name = 'testCust'**

----+------
\#   |@ CLASS
----+------
0   |null
----+------

1 item(s) found. Query executed in 0.005 sec(s).

**Comment by tglman** [comment]
fixed, will be release with 2.1 GA, closing

**Comment by a-unite** [comment]
Will this be fixed in 2.0.x branch?
This will help not only with our current production database operations, but for upcoming migration to 2.1 version, as well.

**Comment by tglman** [comment]
ported also to 2.0.x branch will be out with 2.0.12

**Comment by a-unite** [comment]
Thank you, indeed!
