### ISSUE TITLE
Studio 2.1rc-3 Can not create index

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#4274]
Using 2.1rc-3 studio, trying to create an index via the studio UI the save button is greyed out regardless of the type and name being populated, which prevents from saving. 

![2015-06-02 10_37_48-mozilla firefox](https://cloud.githubusercontent.com/assets/484901/7938434/7355607e-0913-11e5-99c7-722863c642b8.png)

**Comment by StarpTech** [comment]
Try in another Browser. This is a bug. Or via SQL Statement. 
 - - 
Mobile

**Comment by dblaber** [comment]
Is there another bug to track this(is this a duplicate)? I use api to create it, just trying to make development team aware of the bug

**Comment by maggiolo00** [comment]
hi @dblaber 
see here
https://github.com/orientechnologies/orientdb-studio/issues/287
