### ISSUE TITLE
Notion of 'Push' when Class instances are added or removed.

### ISSUE THREAD

**Issue by amarjeet** [orientechnologies/orientdb#4278]
This is with reference to RethinkDB - http://rethinkdb.com that has a notion of a 'push', as mentioned on this page under the section *"Realtime feeds"* at RethingDB Realtime Feeds - http://rethinkdb.com/docs/guide/javascript/

Is there a parallel in *orientdb* as above? I do have a use case where a `Class` needs to be `Observed` for changes and rather than polling, would rather be notified via a `callback` or a `listener`. Having `Reactive Extensions` to this end would be even more desirable.

**Comment by smolinari** [comment]
Not sure if it is the same thing, but check out dynamic hooks.

http://orientdb.com/docs/last/Dynamic-Hooks.html

Scott

**Comment by lvca** [comment]
You can do this by using **Live Queries**: http://orientdb.com/docs/last/Live-Query.html

**Comment by amarjeet** [comment]
That is much more like it. Albeit **This feature is experimental and not covered by commercial support, use it at your own risk** warning right at the top, I am willing to try it and hope that it is stable in the future.

Thank you!

**Comment by smolinari** [comment]
Thanks @lvca. Now I also understand better what was meant/ wanted.

Scott

**Comment by lvca** [comment]
Yes, we'll make it stable in 2.2. The only thing is missing now is the re-registration of the live queries in case of connection lost.
