### ISSUE TITLE
Create index taking to long

### ISSUE THREAD

**Issue by RoCossa** [orientechnologies/orientdb#4283]
Hello,
We have a vertex with 88 milion records and when we try to create a not unique index it take 8 hours to finish. Is it normal?

**Comment by luigidellaquila** [comment]
Hi Rodrigo,

a fix was applied a few days ago on a single problem. Could you try it
against latest snapshot

Thanks


2015-06-03 20:32 GMT+02:00 Rodrigo Cossa <notifications@github.com>:

**Comment by lvca** [comment]
Close because no answer.
