### ISSUE TITLE
Distributed: check if local database is newer than the available in cluster

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4287]
In case "node1" starts as first node in distributed mode, and it has an old copy of a database (or even an empty database), the new joining node "node2" should check this and avoid to replace own copy with the older one.

**Comment by lvca** [comment]
There is no way to understand if a database is more updated than another one, also because the dates could be not synchronized.

Let's do a couple of examples:
(1) you have 5 nodes and you decide to stop the cluster to upgrade it (or for any other reason), just stop the application that work with the database first, and then stop all the nodes. They will have the same content and this problem never happens.

(2) A server crashes, then the others after a while. In this case the other servers will have the most recent database, so in this case it's up to the sysadm to start the most recent database first.

**Comment by lvca** [comment]
However, in the case a newer database joins the cluster, it's never deleted, but copied under `/backup` directory.

**Comment by jillray7** [comment]
@shlapkov @rickcole3 Do you guys have thoughts on the comments above related to this enhancement request?

**Comment by lvca** [comment]
This has been already implemented in 2.2.x.
