### ISSUE TITLE
Time zones

### ISSUE THREAD

**Issue by wayne-oscme** [orientechnologies/orientdb#4288]
Time zones are necessary to many business, research and healthcare applications.  The datetime type should have tz capability.

**Comment by lvca** [comment]
This is already supported. Search for "Timezone" in OrientDB documentation or just look at: http://orientdb.com/docs/last/SQL-Alter-Database.html.

**Comment by wayne-oscme** [comment]
Please reopen.  The link is to support for a database wide time zone.  But I see no support for datetime data different from the "default".  Which makes it database wide, and not a default in actuality.  Are tz aware datetimes just not available at all to java?  Not a java programmer, but I have to believe it has fully functional date/datetime/time types.

**Comment by smolinari** [comment]
I am also very interested in the best strategy to store datetimes accurately and use them in Orient. Like, how would the date() function be best applied when working with dates? I would have thought it for formatting date output, but the example in the docs shows comparison. So, is the function only for returning unix time? I am confused on this. 

Would I be correct in saying, we should always store datetime calculated to UTC? What about sysdate()? Can I store the database's time (so time exact time of insertion in the database) in a "record created" field with this function and also use the time zone for calculating to zulu/ UTC? The documentation is sparse in explaining how best to use these functions. 

Maybe this could actually be a nice blog post. :-) How to best store datetimes accurately and use them efficiently in OrientDB. 

Scott
