### ISSUE TITLE
Are there any good tips on OrientDB data modeling ?

### ISSUE THREAD

**Issue by kk00ss** [orientechnologies/orientdb#4290]
Hello, I've lightly went over the manual, and I saw no section about data modeling.
When should I add properties to a class and when it should be links to other objects ?
Class A 
{List<B>}
or
Class A
{List<Link<B>>
}
Would there be any difference ?
Let's say I want to incorporate 2 collections into an object, and most frequent query would be top 10 from both of them. How do I ensure that this happens with single IO at most, assuming I know OID for an object of class A ?

**Comment by smolinari** [comment]
>Let's say I want to incorporate 2 collections into an object,

Are you asking for the difference between an embedded or a linked document and their relationships?

http://orientdb.com/docs/last/Concepts.html#relationships

http://orientdb.com/docs/last/Concepts.html#embedded-relationships

http://orientdb.com/docs/last/Concepts.html#referenced-relationships

Scott

**Comment by kk00ss** [comment]
Not exactly, Let's say I've embedded two collections into my class - will they be stored with it's record always ? or are there some sort of overflow pages ?

**Comment by smolinari** [comment]
I am guessing that you are referring to the Java API then, which I am sorry, I have no real knowledge about. But, reading through these docs, I'd say, collections are stored directly in the record/ document. 

http://orientdb.com/docs/last/Object-2-Record-Java-Binding.html

Scott

**Comment by kk00ss** [comment]
Thanks
