### ISSUE TITLE
Create index button is inactive in 2.1rc3

### ISSUE THREAD

**Issue by kk00ss** [orientechnologies/orientdb#4291]
Steps:
Created new class
Added string field
Tried to create dictionary index
Button "Save" was inactive until I've selected index type = UNIQUE and SB-TREE.
Then it became active for other index types also.

**Comment by lvca** [comment]
Do you mean from Studio tool?

**Comment by kk00ss** [comment]
Yes

12 Июн 2015 г. 16:58 пользователь "Luca Garulli" <notifications@github.com>
написал:

**Comment by maggiolo00** [comment]
@kk00ss 
can you retry with 2.1-rc5?

**Comment by kk00ss** [comment]
Will do.
6 Июл 2015 г. 18:29 пользователь "Enrico Risa" <notifications@github.com>
написал:

**Comment by maggiolo00** [comment]
@kk00ss 
it is fixed here
https://github.com/orientechnologies/orientdb-studio/issues/287
