### ISSUE TITLE
Login error on plocal/embedded/2.0.10

### ISSUE THREAD

**Issue by acmeguy** [orientechnologies/orientdb#4298]
Hi,

I can no longer log-in if I update from 2.0.9 to 2.0.10.

I'm running plocal / embedded and trying to use the root access defined in the .xml config file.
It worked after I downgraded again.

Regards,
 -Stefan

**Comment by acmeguy** [comment]
I'm using an older version of the studio, should that matter?

**Comment by StarpTech** [comment]
I also updated from 2.0.9 to 2.0.10. How did you upgrade?

**Comment by luigidellaquila** [comment]
Hi Stefan,

that's quite strange, did you do a soft shutdown in 2.0.9 before migrating
the db?

Luigi


2015-06-05 1:51 GMT+02:00 Dustin <notifications@github.com>:
