### ISSUE TITLE
2.1-rc3: SQL query error

### ISSUE THREAD

**Issue by zhuobao** [orientechnologies/orientdb#4300]
on OpenBeer dataset:

**query 1: `select cla, count(*) as class_cnt from (select @class as cla from V)`**
result:
----+------+----+---------
\#   |@CLASS|cla |class_cnt
----+------+----+---------
0   |null  |Beer|7382     
----+------+----+---------

**query 2: `select cla, count(*) as class_cnt from (select @class as cla from V) group by 1`**
result:
----+------+----+---------
\#   |@CLASS|cla |class_cnt
----+------+----+---------
0   |null  |Beer|7382     
----+------+----+---------

**query 3: `select cla, count(*) as class_cnt from (select @class as cla from V) group by cla`**
result: 
----+------+---------+--------
\#   |@CLASS|class_cnt|cla     
----+------+---------+--------
0   |null  |0        |null    
1   |null  |11       |Category
2   |null  |141      |Style   
3   |null  |1394     |Brewery 
4   |null  |5836     |Beer    
----+------+---------+--------
So the **issues** are:
* The **query 3** result is **closer** to the correct answer, in which "null" should not be there, although these query 2 and query 3 should be equivalent.
* query 2 does not invoke error message
* query 1 gives result that not close to other versions of SQL

By the way, using explain can only see the **"unformated"** result statistics, but NOT how query works, **hope the `explain` function can be improved**.

**Comment by luigidellaquila** [comment]
query 1 is a valid query, but the result is not predictable. You would obtain the same result e.g. with MySQL ;-)

query 2 will be addressed in next releases

query 3 is obviously a bug (@lvca it's yours ;-) )

**Comment by lvca** [comment]
Fixed query3.
