### ISSUE TITLE
2.1-rc3: drop multiple inheriting class fails and error: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zhuobao** [orientechnologies/orientdb#4301]
OpenBeer dataset:
> create class cs1 extends style, category
> info class cs1      
but when I drop to drop it, error message threw out:

>drop class cs1
**Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.drop class cs1**
**Error: java.lang.ArrayIndexOutOfBoundsException**

**Comment by tglman** [comment]
Hi @zhuobao 
do you have the whole stack trace ?
