### ISSUE TITLE
2.1-rc3: gremlin in console not working properly

### ISSUE THREAD

**Issue by zhuobao** [orientechnologies/orientdb#4302]
orientdb> gremlin g=new OrientGraph("remote:localhost/OpenBeer", "admin", "admin")
[Started multi-line command. Type just 'end' to finish and execute]

\## *when I try to type "end", console always goes back to " the orientdb mode":*
orientdb> end

\## * then console throws error*
Error: com.orientechnologies.common.exception.OException: Database not selected. Use 'connect <database-name>' to connect to a database.

orientdb>

**Comment by lvca** [comment]
Gremlin command allows you to execute gremlin commands against an open database in console. "g" is created automatically for you by OrientDB console, so try using it in gremlin command after you opened the database with console.

**Comment by zhuobao** [comment]
Thank you. just that prompt still appears.
