### ISSUE TITLE
Property lost when updating vertex in an auto-merge mode

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4309]
We have the following example:
1) Thread 1 creates vertex 1
2) Thread 2 loades vertex 1 and sets a property p1 = v1.
3) Thread 1 sets vertex 1 property p2 = v2. It operates with a non-latest version of vertex 1, since it was changed by Thread 2.

Expected: vertex 1 with both properties p1 = v1, p2 = v2
Got: vertex 1 with property p2 = v2. Property p1 = v1 gets lost.

Unit test will be sent via e-mail.

**Comment by lvca** [comment]
partially fixed in 2.1-SNAPSHOT. The problem with remote is that changing the content is not supported, so the record on the client remain old. You must do a reload. With a reload all your tests pass.

**Comment by ylopotun** [comment]
Ok, but even if we do reload before setting the vertex property or creating an edge, we can't be 100% that some other thread didn't update the vertex just after we made the reload... How could we make sure we won't loose data in such case? Do we need to synchronize reload and next operation?

**Comment by ylopotun** [comment]
I guess I misunderstood your comment. So, no data is lost when saving it into the DB and we just have to reload to sync with it?

**Comment by lvca** [comment]
Exactly. Unfortunately the auto-merge strategy came lately and the binary protocol doesn't support resending the record content to the client at commit time. We should support this in the binary protocol.

**Comment by ylopotun** [comment]
I was still able to reproduce the issue with 2.1-SNAPSHOT in a unit test (sent via e-mail).

**Comment by lvca** [comment]
Reproduced and fixed. Thanks.

**Comment by ylopotun** [comment]
I’m still able to reproduce this issue after your today’s fix. Unit test sent via e-mail.

**Comment by lvca** [comment]
The reload must be done on client side. Try this:
```java
 private void dbClient2() {
    synchronized (LOCK) {
      OrientBaseGraph graph = new OrientGraph(CLIENT_ORIENT_URL_MAIN);
      OrientVertex parentV1 = null;
      OrientVertex parentV2 = null;
      int countPropValue = 0;
      try {
        for (int i = 0; i < NUM_OF_LOOP_ITERATIONS; i++) {
          pause();

          if (exceptionInThread != null)
            break;
          // Let's give it some time for asynchronous replication.
          sleep(500);
          countPropValue++;
          if (parentV1 == null) {
            parentV1 = graph.getVertex(parentV1Id);
          } else
            parentV1.reload();

          parentV1.setProperty("cnt", countPropValue);
          graph.commit();

          if (parentV2 == null) {
            parentV2 = graph.getVertex(parentV2Id);
          } else
            parentV2.reload();

          parentV2.setProperty("cnt", countPropValue);
          graph.commit();
        }
      } catch (Throwable e) {
        if (exceptionInThread == null) {
          exceptionInThread = e;
        }
      } finally {
        log.info("Shutting down");
        graph.shutdown();
        LOCK.notifyAll();
      }
    }
  }
```
