### ISSUE TITLE
Sub transactions commit/rollback outer ones with in-memory DB

### ISSUE THREAD

**Issue by mohamnag** [orientechnologies/orientdb#4311]
Following code should start a sub-transaction inside an outer transaction. 

```java
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientVertex;

/**
 * Created by mohamnag on 03/06/15.
 */
public class test {

    private static OrientGraphFactory graphFactory = new OrientGraphFactory("memory:testdb", "admin", "admin");

    public static void main(String[] args) {

        OrientGraph graph = graphFactory.getTx();

        graph.executeOutsideTx(noTx -> {
            noTx.createVertexType("test");
            return null;
        });

        OrientVertex vertex = graph.addVertex("class:test");

        //<<<<<< this is a call to another function which does somethings in a sub-transaction

        OrientGraph graph2 = graphFactory.getTx();

        OrientVertex vertex2 = graph2.addVertex("class:test");
        // do something with vertex2, set properties
        graph2.commit();

        //>>>>>> here we return to original function

        // now we continue own business in outer transaction
        vertex.setProperty("test", "value");

        graph.commit();
    }

}
```

This works as expected while using orientdb v2.0.10 as remote database and v2.0.8 as in-memory database, however when using v2.0.9 or 2.0.10 as in-memory database, following exception is thrown:

```
Exception in thread "main" java.lang.IllegalStateException: The vertex #11:-2 has been deleted
	at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:177)
	at test.main(test.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by laa** [comment]
It is not real bug, I will explain. When you commit new tx you automatically start other one.
So either do not use this feature and start txs manually or use pool inside of graph factory, pool allows to share txs between different graph instanses in this case your code will look like following https://gist.github.com/laa/58260f052527b6cee00b

**Comment by mohamnag** [comment]
thats funny, because I had another problem with using pools with in-memory db which was never solved: #3794 
the only solution I found there was NOT to use pooling when DB is an in memory db.

**Comment by laa** [comment]
I tried now and all is work.
Did you try my gist ?

**Comment by mohamnag** [comment]
I'm going to test it now, it may take a while for all the tests to run but I will post an update here as soon as I have the results

**Comment by laa** [comment]
The issue which you call issue, is not issue ))
In order to open data you should create it first.

So as first step add this line of code new OrientGraphNoTx(url);

and then after that merely use pool.

**Comment by mohamnag** [comment]
ok, using the pool is now working even without `new OrientGraphNoTx(url);` for creation of the db as similar to your code.
