### ISSUE TITLE
2.1rc2 cannot import public database

### ISSUE THREAD

**Issue by beebase** [orientechnologies/orientdb#4312]
![img1612](https://cloud.githubusercontent.com/assets/446089/8018973/51e07718-0c37-11e5-9289-71995479a30c.jpg)

![img1611](https://cloud.githubusercontent.com/assets/446089/8018972/31330abc-0c37-11e5-9a7a-0270d5f7d098.jpg)

**Comment by beebase** [comment]
did fresh install 2.1-rc3 ...working now.

**Comment by lvca** [comment]
Great, closing it.
