### ISSUE TITLE
GET XML response instead of JSON via http ?

### ISSUE THREAD

**Issue by nomi-ramzan** [orientechnologies/orientdb#4314]
Hi All ! 
I want to know is there any way to get XML response from orientDB instead of JSON response  ?
in case of NO How and Where can I write my code to change json -> xml ?

Thank you

**Comment by luigidellaquila** [comment]
Hi @nomi-ramzan 

OrientDB does not support XML out of the box, you have different ways to do this, one is writing a server plugin, see

http://orientdb.com/docs/last/Extend-Server.html

but the easiest one is probably writing a Java or Javascript function and use "response" object to send raw data (XML in your case) to the client, see http://orientdb.com/docs/last/Functions.html

If you need further information, please move this discussion on the community group https://groups.google.com/forum/#!forum/orient-database

Thanks

Luigi
