### ISSUE TITLE
Cannot create Class from Studio in 2.1-RC3

### ISSUE THREAD

**Issue by alexpmorris** [orientechnologies/orientdb#4315]
If I try and create a new class from the console (ie. create MyClass), it works fine.

If I try creating a new class from the Studio's Schema Page, it forces me to pick a SuperClass even if I don't want to set one, with the error:

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #28: Syntax error after EXTENDS for class MyClass. Expected the super-class name. Use CREATE CLASS <class> [EXTENDS <super-class> [,<super-class2>*] ] [CLUSTER <clusterId>*] [ABSTRACT] Command: CREATE CLASS MyClass extends ------------------------------------^

I tried checking the Abstract box as well, and it didn't make a difference.

**Comment by madobati** [comment]
I think it's a bug of "Studio Schema". I received the same error with same operation.
Super class should be optional in the create class command but if your class isn't child of another class,  you can extend it (in the step of creation) with super default  class "E" (Edge), "V" (Vertex) ..
ps. You can change the superclass after the creation step with: 
alter class XXXXX superclass XXXXX.

**Comment by maggiolo00** [comment]
@alexpmorris 
Can you retry with 2.1-rc5?

**Comment by alexpmorris** [comment]
Yes, I believe this issue is resolved!
