### ISSUE TITLE
error in delete command  from a index query(error also in log result )

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4318]
ver: 2.1.rc2
2 queries with 2 errors:
 first : delete from ( select expand(rid)  from index:d.a where key = #23:5 )

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT expand(rid) FROM index:dt.a WHERE key = #23:5

Error: java.lang.ClassCastException: com.orientechnologies.orient.core.id.ORecordId cannot be cast to com.orientechnologies.orient.core.record.ORecordAbstract

**Comment by publicocean0** [comment]
delete from ( select rid   from index:D.a where key = #23:5 )

Delete record(s) '1' in 0,001000 sec(s).



orientdb {db=docstore}> select rid   from index:D.a where key = #23:5

----+------+-----
#   |@CLASS|rid  
----+------+-----
0   |null  |#30:1
----+------+-----

1 item(s) found. Query executed in 0.001 sec(s).
orientdb {db=docstore}> select from #30:1

----+-----+----------------+--------+--------
#   |@RID |@CLASS          |d|a
----+-----+----------------+--------+--------
0   |#30:1|d|#28:0   |#23:5   
----+-----+----------------+--------+--------

1 item(s) found. Query executed in 0.001 sec(s).

**Comment by lvca** [comment]
Tried this against 2.1-SNAPSHOT and works:

    delete vertex from ( select expand(rid) from index:Beer.id where key = 12 )

**Comment by lvca** [comment]
Now works also with plain DELETE (+ UNSAFE if it's a vertex/edge)
