### ISSUE TITLE
Query parsing problem

### ISSUE THREAD

**Issue by ccasenove** [orientechnologies/orientdb#4319]
Hi,

Using 2.1.0-RC3, the parser is unable to interpret the following query:
**select from Person where name matches 'a'**
It fails with the error *com.orientechnologies.orient.core.sql.parser.ParseException: Encountered "" at line 1, column 26.*

However, this query is well parsed: **select from Person where name matches 'a.*'**

So the parsing fails depending on the content of the regular expression.

**Comment by luigidellaquila** [comment]
fixed in develop branch
