### ISSUE TITLE
ClassCastException when parsing query

### ISSUE THREAD

**Issue by ccasenove** [orientechnologies/orientdb#4320]
Hi,

Using 2.1.0-RC3, an exception occurred when parsing the following query:

**select from Person where name matches '(?i)(^\\Qname1\\E$)|(^\\Qname2\\E$)|(^\\Qname3\\E$)' and age=30**

--> *java.lang.ClassCastException: com.orientechnologies.orient.core.sql.filter.OSQLFilterItemField cannot be cast to com.orientechnologies.orient.core.sql.filter.OSQLFilterCondition*

If I remove the and operator, the parser does not complain:

**select from Person where name matches '(?i)(^\\Qname1\\E$)|(^\\Qname2\\E$)|(^\\Qname3\\E$)'**

--> *OK*

**Comment by luigidellaquila** [comment]
fixed in develop branch
