### ISSUE TITLE
Sharded Index

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4326]
OrientDB 2.x has some limitation on concurrency on indexes because locks. The easy trick to gain more speed, specially in insertion, is using X indexes, one per sub-class, and design the importer to use them. This is pretty complex for the new user (we're creating a new API to make this kind of things super easy). And another idea came in my mind: why don't just create a ShardedIndex implementation? In practice it would act as a wrapper of any existent index, but under the hood it creates X indexes, where X is configurable on creation and never modifiable (just drop and re-create the index if needed). 

The idea is simple: use a hash() function that for a given key, returns the underlying index to use, then delegate the call to the right sub-index. In this way we could use a logical index in multi-thread fashion.

**Comment by laa** [comment]
+1, it will increase time for range queries but point queries will be scalable on non-tx mt cases also not so much of work should be done. so definitely +1.

**Comment by lvca** [comment]
I pushed a working implementation into autosharding-index branch.

**Comment by lvca** [comment]
This is already in the code base. Users can start using it waiting for the support on distributed (v3.0 so far) to physically assign shards as cluster+index to nodes.

About the usage is:
```java
final OClass cls = db.getMetadata().getSchema().createClass("MultipleClustersIndexedAutoSharding8");
cls.createProperty("key", OType.LONG);
cls.createIndex("idx_createMultipleClustersIndexedAutoSharding8", OClass.INDEX_TYPE.UNIQUE.toString(), (OProgressListener) null, (ODocument) null, "AUTOSHARDING", new String[] { "key" });
```

**Comment by lvca** [comment]
Using autosharding index on a 8 core machine (with 8 clusters per class) gives barely +50% more throughput on insertion and the same performance on lookup.
