### ISSUE TITLE
2.1-rc3: SQL parse error using "CLUSTER" 

### ISSUE THREAD

**Issue by alexpmorris** [orientechnologies/orientdb#4328]
INSERT INTO cluster:chatmessages SET text = 'A chat message', datetime = Date(), user = 'studio'  <--  works! 

INSERT INTO chatmessages cluster chatmessages SET text = 'A chat message', datetime = Date(), user = 'studio' <-- works!  

INSERT INTO CLUSTER:chatmessages SET text = 'A chat message', datetime = Date(), user = 'studio'  <-- SHOULD work just like others, but FAILS with "Error on parsing command"

So, "cluster" and "Cluster" seem to work, but using the word "CLUSTER" does NOT.

**Comment by vensaadmin** [comment]
Just an FYI I ran into this same problem with 2.1-rc5

**Comment by luigidellaquila** [comment]
fixed in develop branch

**Comment by alexpmorris** [comment]
looking at this code, it appears "instanceof" should also be made case-insensitive in the same way as "cluster".  

The documentation seems to support that view as well: 

(from http://orientdb.com/docs/last/SQL-Where.html)

`record, string (as class name)	INSTANCEOF	Used to check if the record extends a class	@this instanceof 'Customer' or @class instanceof 'Provider'	1.0rc8`
