### ISSUE TITLE
distributed delete by http

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4329]
Delete from record by http protocol in distributed mode thru url (eg, http://<ip>:2480/document/pharos/19:85, set request method to delete), i got following error message in http response :
com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#19:85' not found
--> com.orientechnologies.orient.core.exception.ORecordNotFoundException: Record with rid #19:85 was not found in database Total Cost :  488 ms

Check on database, record was deleted successfully.

**Comment by henryzhao81** [comment]
Fixed.

**Comment by lvca** [comment]
Which version has this problem and which version fixed it?

**Comment by henryzhao81** [comment]
I fix the change in 2.0.11-SNAPSHOT, i am going to send pull request to you for review
