### ISSUE TITLE
Not able to find replication status of secondary server in Orient DB 1.7.6

### ISSUE THREAD

**Issue by SampathTele** [orientechnologies/orientdb#4330]
Luca,
We have configured two Orient DB servers in replication mode(Primary and secondary) in synchronous also, Now the issue how do I check the replication status of secondary server, i.e. I want check whether  all the records getting updated in secondary server when the commit transaction is performed with primary server. Is there any spacial commands are available to check the replication status of both servers.?? (or) Should I need to do any spacial configurations to check the replication status..?? 
Finally I want know replication status, Is there any possibility to know last committed transaction_ID .??Any suggestions are welcome.

**Comment by lvca** [comment]
Sorry version 1.7.6 is too old and supported only for clients. Please migrate to 2.0.x or even 2.1*

**Comment by SampathTele** [comment]
Luca,
Thanks for responding. Can you provide the procedure (or) commands to know the replication status of secondary servers in new versions(2.0.x or 2.1*). If you have any procedure links can you post here.

**Comment by nawazdhandala** [comment]
Any updates on this?

**Comment by lvca** [comment]
You can see if 2 nodes are connected by reading the logs. Also connecting with the console, you have the distributed configuration at connection time. With 2.1 and Enterprise Edition (FREE for development only) you have this in OrientDB Studio:

http://orientdb.com/docs/last/Server-Management.html

**Comment by nawazdhandala** [comment]
Thanks! That helped. :)
