### ISSUE TITLE
OSharedResourceAdaptive.acquireExclusiveLock() locks for twenty minutes or more (Orient 2.0.10)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4333]
(Note: We are running Orient 2.0.10 with com.orientechnologies.common.concur.lock package replaced with latest version). All Orient threads are locked indefinitely... stack trace below)

![screen shot 2015-06-09 at 8 32 29 pm](https://cloud.githubusercontent.com/assets/6212848/8066229/b84c8832-0ee6-11e5-81fa-e38a127174d8.png)

 google sync  [WAITING]
java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.tryLock(long, TimeUnit) ReentrantReadWriteLock.java:1115
com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.acquireExclusiveLock()

 OSharedResourceAdaptive.java:111
com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal.acquireExclusiveLock() OSharedResourceAdaptiveExternal.java:35
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OTransaction, Runnable) OAbstractPaginatedStorage.java:897
com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit() OTransactionOptimistic.java:488
com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(boolean) OTransactionOptimistic.java:147
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(boolean) ODatabaseDocumentTx.java:2427
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit() ODatabaseDocumentTx.java:2397
com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(boolean, boolean) OrientBaseGraph.java:1143
com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(boolean) OrientBaseGraph.java:1129
com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown() OrientBaseGraph.java:1122
...
java.lang.Thread.run() Thread.java:745

**Comment by laa** [comment]
Hi,
It is fixed in 2.1 we will back port it soon.
10 Июн 2015 г. 1:19 пользователь "Luca Garulli" <notifications@github.com>
написал:

Assigned #4333 <https://github.com/orientechnologies/orientdb/issues/4333>

**Comment by jamieb22** [comment]
Andrey

Can you please let me know which source files are affected?

I don't have the luxury of waiting for the backport. I'm happy to 
manually incorporate the patch into our code base.

Jamie

**Comment by jamieb22** [comment]
Andrey

I can't be sure but it seems to be a case that this has something to do 
with Orient's shutdown procedure. Perhaps, Orient doesn't handle 
interrupts very well? Or a deadlock occurs when the database is shutdown 
and operations are still being performed on the db.

Jamie

**Comment by laa** [comment]
It is not simple copy paste.
But I will start to backport tomorrow all issues related to multithreading.

**Comment by laa** [comment]
Fixed by backporting of deadlock fix from develop to 2.0.x
