### ISSUE TITLE
In memory DB is not closing correctly

### ISSUE THREAD

**Issue by rmchale** [orientechnologies/orientdb#4336]
I am trying to write some unit tests with an in-memory DB.  I cannot get the DB to properly re-open after what looks like a proper shutdown.  

```Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot create new storage 'test' because it is not closed
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:222)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:377)
	... 49 more```

Example code:
```
ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:test", false).create();
db.close()

db = new ODatabaseDocumentTx("memory:test", false).create();
db.close()
```

**Comment by lvca** [comment]
Have you tried to call db.drop() if you don't want the db anymore?

**Comment by rmchale** [comment]
Drop fixes this simple case, but I have a slightly more  complex one that does the same thing. I'll type it up and pass it along.

**Comment by stuz5000** [comment]
Was this resolved? It certainly looks like a bug (not a question) if, close is called and the subsequent error complains that the DB is not closed? I am also seeing this behavior.

@Ivca Is the intention of the API that drop (not close) should be called to put the ODatabaseDocumentTx into a closed state?
