### ISSUE TITLE
null ridbag for delete vertex 

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4337]
i do have following error for 2.1-rc3. any idea?
this happen for simple query 'delete vertex class'
java.lang.NullPointerException: Impossible to add a null identifiable in a ridbag

**Comment by laa** [comment]
Hi we are working on it right now.
Will fix it during couple of days .

**Comment by martingg88** [comment]
sure thanks.

**Comment by martingg88** [comment]
what is the method i can force to delete for now ?

**Comment by laa** [comment]
We are creating tool to fix error in data structure please wait couple of
days .

**Comment by martingg88** [comment]
thanks.

**Comment by maggiolo00** [comment]
hi @martingg88  do you have
the stack trace?

**Comment by martingg88** [comment]
sorry. i didn't keep the stack trace for this issue.

**Comment by laa** [comment]
Hi it is fixed in latest build but please feel free to reopen it if it will be reproduced.

**Comment by martingg88** [comment]
sure. thanks.
