### ISSUE TITLE
ParsingException when using more than one LET-Statement via binary protocol

### ISSUE THREAD

**Issue by Wutnudel** [orientechnologies/orientdb#4341]
I have the following query:

    SELECT score.@rid, $readBy
    FROM thread
    LET
        $score = first(out("isFor").out("isA")), 
        $readBy = (SELECT out as personRid from isMemberOf WHERE in = $parent.$current.@rid AND read=true)

This works perfectly fine in the studio but when i send it via the binary protocol (in my case using oriento) although it reches the server correctly throws a OCommandSQLParsingException mit Invalid keyword '@rid'

The problem doesn't occur if I remove either of the LET-statements

**Comment by Wutnudel** [comment]
Update: I've tried to further track down this problem. And it becomes even harder to understand. I had in my code queries that had more than one variable defined via a LET-statement. These queries worked and still work.
If, however, i add another argument to these LET-statements the queries suddenly throw the same error-message described in the initial post.

**Comment by lvca** [comment]
I think this is in oriento with \n. Could you please write your query in one line with oriento?

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
