### ISSUE TITLE
RID to String conversion

### ISSUE THREAD

**Issue by aleks-n** [orientechnologies/orientdb#4342]
Hi all, 

Could you please suggest a proper way to convert RID of existing Vertex to String? 
Getting following error message: 
"java.lang.IllegalArgumentException: Argument '?' is not a RecordId in form of string. Format must be: <cluster-id>:<cluster-position> [ONetworkProtocolHttpDb]". 

Code:

var cmdCreateRel = "create edge Child from ? to (select from Site where code='" + code +"')";
print("3:::cmdCreateRel: " + cmdCreateRel);
var cityRidAsString = "" + cities[ci].getRecord().field('@rid');
print("3:::c rid: " + cityRidAsString);
gdb.command("sql", cmdCreateRel, [cityRidAsString]);

Server console:

3:::
3:::cmdCreateRel: create edge Child from ? to (select from Site where code='County-0_City-99_Site-0')
3:::c rid: #15:2001

2015-06-10 09:19:15:309 SEVERE Internal server error:
java.lang.IllegalArgumentException: Argument '?' is not a RecordId in form of string. Format must be: <cluster-id>:<cluster-position> [ONetworkProtocolHttpDb]
# 

But following statement works in Studio:

create edge Child from #15:2001 to (select from Site where code='County-0_City-99_Site-0')

**Comment by luigidellaquila** [comment]
Hi @aleks-n 

which OrientDB version? Input parameters as query target are supported since 2.1

**Comment by aleks-n** [comment]
Hi, 

It is 2.0.10 Community Edition for Windows (orientdb-community-2.0.10.zip). And following test code works fine. 

for (var i = firstFloorNumber; i < runNum; i++){
	var floorName = "Floor-" + i;
	var floorCode = buildingCode + "_" + floorName;
	var cmdCreateFloor = "create vertex Floor set name=?, code=?";
	var floor = gdb.command("sql", cmdCreateFloor, [floorName, floorCode]);
}
