### ISSUE TITLE
Graph Editor id as zero issue

### ISSUE THREAD

**Issue by Kalatheeswaran** [orientechnologies/orientdb#4344]
When 0 is used as a value for a unique index, it is shown in the table structure but doesn't appear in the graph editor vertex when id is selected in the editor to be displayed. Instead the record id is shown.

**Comment by maggiolo00** [comment]
Which Version of OrientDB?

**Comment by Kalatheeswaran** [comment]
Hi @maggiolo00 
The OrientDB version is 2.0.9 and studio version is 2.0
![image](https://cloud.githubusercontent.com/assets/10212902/8105053/f50d4f74-100b-11e5-8367-0ec66706f91b.png)

**Comment by maggiolo00** [comment]
Thanks

**Comment by Kalatheeswaran** [comment]
You are welcome
