### ISSUE TITLE
query a particular value from a property with respect to other property from a linkset or linklist

### ISSUE THREAD

**Issue by Kalatheeswaran** [orientechnologies/orientdb#4348]
Hi,
This refers to support query projections for multiple properties from a linkset or linklist #1938 issue.

How to get the value of 'b' for a particular value of 'a' (say if a =1 then b = 10) from this linkset query Select roles.include('a','b') from user ?

Thanks

**Comment by micha-nerdlichter** [comment]
I don't know if I understand correctly what you want. Your "user" records have a "roles" property which is a linkset of a class with "a" and "b" properties, right? And now you want to select the b-values where a = 1? Just do
```sql
select roles[a=1].b from user
```
You don't need any include here.

**Comment by Kalatheeswaran** [comment]
Hi thanks for the reply. I solved it after some time after posting on this issue. Sorry for not updating it.

**Comment by lvca** [comment]
Thanks for the feedback, closing it.
