### ISSUE TITLE
Transaction commits event if edge isn't created

### ISSUE THREAD

**Issue by vslinko** [orientechnologies/orientdb#4349]
# Query example

```
BEGIN
LET credential = INSERT INTO Credential SET email = '123', password = '123'
LET order = SELECT FROM Order WHERE @rid = "#13:0"
LET edge = CREATE EDGE CredentialOrder FROM $credential TO $order
COMMIT
RETURN $credential
```

# Actual

If `$order` is empty because of invalid `@rid` then edge isn't created but credential is saved.

# Expected

If `$order` is empty then an error thrown and transaction rollbacked.

**Comment by lvca** [comment]
I can't do that in 2.0.11 because would change the behavior of this command. I'm pushing in 2.1-SNAPSHOT and I'm going to update documentation.

**Comment by vslinko** [comment]
@lvca could you say when approximately fix will be released? Thank you.

**Comment by lvca** [comment]
will be released in 1h or less
