### ISSUE TITLE
Error during insertion of key in index

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4350]
Hi,</BR>
After some time running this command(like 3/sec):</BR>
<code>UPDATE UserOnline SET UserId = 8951, ConnectionId = 'fb2f2eb5-c765-46d7-9941-4c3e924f45f82', UserName = 'Thiago Prestes2', LastAccess = '2015-06-11 12:47:48', OriginURL = 'student.ilang.com' UPSERT WHERE UserId = 8951</code></BR>
</BR>
Class:</BR>
<code>
CREATE CLASS UserOnline EXTENDS V</BR>
CREATE PROPERTY UserOnline.UserId INTEGER </BR>
CREATE PROPERTY UserOnline.UserName STRING </BR>
CREATE PROPERTY UserOnline.ConnectionId STRING </BR>
CREATE PROPERTY UserOnline.OriginURL STRING </BR>
CREATE PROPERTY UserOnline.LastAccess DATETIME </BR>

CREATE INDEX UserOnline.UserId ON UserOnline(UserId) UNIQUE</BR>
CREATE INDEX UserOnline.ConnectionId ON UserOnline(ConnectionId) UNIQUE</BR>
CREATE INDEX UserOnline.LastAccess ON UserOnline(LastAccess) NOTUNIQUE</BR>

CREATE CLASS Online EXTENDS E</BR>
</code></BR>
This error starts and after this, we can't even use the index in a SELECT.
<code>
com.orientechnologies.orient.core.index.OIndexException: Error during insertion of key in index
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Error during index update with key Thu Jun 11 11:41:44 BRT 2015 and value com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer@4623b46f
java.lang.NullPointerException: 
</code>

After this I need to DROP and Recreate the index.</BR>
</BR>
If You need I can reproduce it.</BR>
We are trying to get more info about this error.</BR>
</BR>
Thanks

**Comment by laa** [comment]
Hi, do you use 2.1-RC3 ? Could you rebuild index using this distribution https://www.dropbox.com/s/xs2w59sncv9ln4m/orientdb-community-2.1-SNAPSHOT-distribution.zip?dl=0 and try again ?

**Comment by thiagopm** [comment]
I'm using a 09/06 snapshot. I can try this other snapshot on monday, ok?

**Comment by thiagopm** [comment]
by the way, I recreated this index as Hash and is not happening the error.

**Comment by laa** [comment]
fixed in latest build.
