### ISSUE TITLE
Issues connecting to two databases (via java graph api) in same application

### ISSUE THREAD

**Issue by nmcintyre2014** [orientechnologies/orientdb#4351]
We're using the graph api with a schema.  We ran into this issue when we wanted to migrate our data from the old schema to the new schema.  To do that we wrote an application which connects to both databases, looped through the records in the source database (the one with the old schema), and built a record for the new database.  Incrementally, we commit the new records to the new database.  The underlying problem seems to be that when we read a vertex from the old database, the metadata from the new database is used.  So, if we ask for the class of the old vertex we don't get it's actual class.  We get the class it would be under the new schema (based on the cluster id from the old schema).  So, it seems like there is some global metadata attached to a connection and when there are two connections open, the second connection replaces the metadata for the first connection.

**Comment by nmcintyre2014** [comment]
I've seen in the 2.1 docs that you should do db.activateOnLocalThread() to manage multiple dbs on the same thread, but I see no such method on and OrientGraph object in v.2.0.10.  How do we do this in 2.0.10?

**Comment by nmcintyre2014** [comment]
As a more general question...  What's the recommended way to migrate data when a schema changes?  Can it be done without downtime?

**Comment by lvca** [comment]
Graph API are unchanged. The suggested way to do a migration is using 2 threads, where the first thread read and write on a queue the operation to migrate. The other thread unqueue the message and write to the 2nd database

**Comment by nmcintyre2014** [comment]
That approach should work for us.  Thanks.

**Comment by tglman** [comment]
so i'm closing this
