### ISSUE TITLE
Recommended approach for handling a vertex with many (millions) of edges

### ISSUE THREAD

**Issue by nmcintyre2014** [orientechnologies/orientdb#4352]
We have a case where we have many (potentially millions) of edges attached to a single graph vertex.  An example use case is that we want to be able to tag records.  To do that, we create a vertex representing the tag and link it to all records we want to tag.  The idea is that we could then traverse from the tag to get the entities with that tag.  The underlying problem is that once there are many edges associated with a vertex, operations on the vertex are very slow (even just simply trying to read a single property from the tag vertex).  Is there a recommended way to model this type of relationship in the graph db?

**Comment by laa** [comment]
Hm, it means that you are using presentation of edges embedded in document. Which kind of database do you use ?

**Comment by lvca** [comment]
@nmcintyre2014 are you running in distributed mode?

**Comment by nmcintyre2014** [comment]
We're currently not running in distributed mode, but we plan to if we need to scale beyond one node.  We're using 2.0.10 in vanilla graph mode.

**Comment by Ziink** [comment]
I would create an index on the edge.

Reading about RidBags, it seems like this kind of problems have been encountered before. Maybe instead of transitioning from one RidBag structure to another based on a threshold size, an index could automatically be used.
