### ISSUE TITLE
graph api and maps (embeddedmap, linkmap)

### ISSUE THREAD

**Issue by j-mi-jim** [orientechnologies/orientdb#4355]
Hi guys, 
I've got a problem with GraphApi (Vertex).

1/ create a vertex and put an hashmap into the properties

v = graph.createVertex(..)
v.property("map",hashmap);

2/ get the property v.get("map") gives an OrientElementIterable. So you can get the values but not the keys !

How to get the hashmap without use document api !?﻿

**Comment by lvca** [comment]
To check it if it's closed.

**Comment by lvca** [comment]
You can do `v.getRecord().field("map")`.
