### ISSUE TITLE
Studio authentication broken in Firefox

### ISSUE THREAD

**Issue by Wanderfalke** [orientechnologies/orientdb#4356]
OrientDB version: 
   v 2.0.10
Issue:
   After first successful login followed by logout (or just navigating to start page) in Firefox, I can create/delete database with any user/password combination.

**Comment by Robin479** [comment]
...because the relevant credentials are provided via `HTTP Basic Authentication`, which your browser blindly sends along every request regardless of any javascript/application level "logout" button.

**Comment by Wanderfalke** [comment]
I understand this. It defeats the whole purpose of having a logout functionality.

**Comment by maggiolo00** [comment]
@Wanderfalke 
logout call disconnect HTTP API of ODB to close the session.
