### ISSUE TITLE
DICTIONARY and DICTIONARY_HASH_INDEX  do not replace existing record

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#4357]
2.1rc3

From docs:
DICTIONARY, like UNIQUE but in case the key already exists replace the record with the new one

```sql
create class KeyValue
create property KeyValue.key string
create index KeyValue.key DICTIONARY

INSERT INTO KeyValue SET key = "sites", value = 'asdf'
INSERT INTO KeyValue SET key = "sites", value = 'asdf'
INSERT INTO KeyValue SET key = "sites", value = 'asdf'

select from KeyValue where key = 'sites'
select from KeyValue 
```

Although the first select statement gives the expected result, the second statement gives 3 results. There is no reason to retain old records.

**Comment by lvca** [comment]
The dictionary index just remembers the last value, but doesn't affect the existent records, so implicit delete is not the expected behavior.
