### ISSUE TITLE
[Question] Transform db to intial state

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4360]
Is it possible to transform the whole database to the intial state? Initial state is described as follows:

- All vertexes are only belongs to his class (no clusters)
- All edges are only belongs to his class (no clusters)
- All LINKS on the records are also getting this transformation

This simplifies heavily the process of migrations and especially the step to optimize (cluster selection, distr strategy...) orientdb from a dev state into a production system.

When this will not be supported in near future, does exist professional support for this use case?

**Comment by luigidellaquila** [comment]
Hi Dustin,

I'm not sure about what you exactly want to achieve. When you say "no clusters" do you mean only default cluster per single class? Or change the partitioning of the database on a distributed deployment? Or just let all vertices and edges be instances of V and E, without subclasses?
Anyway none of these features exists in OrientDB at this time (except the change of partitioning, that can be done off-line on the community edition or on running instances with Enterprise).
If you need enterprise support, Orient Technologies provides developer support (see http://orientdb.com/support/) or consulting. If you are interested in a quotation, please send me an email to info -- at -- orientdb.com, I'll be happy to help on this.

Thanks

Luigi
