### ISSUE TITLE
possible enhancement 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4362]
To extend hash function (or other util functions on a vector of items ) also for binary data.

For example i want calculate a hash code of a file saved with different chunks ....  :)

**Comment by lvca** [comment]
What do you mean with extend?

**Comment by publicocean0** [comment]
now hash function works with a string , it is possible to extends this function for workiing also with binary data. if i want elaborate Obyterecord , or ..return the size of a blob or hash of data ,,,, i can't. I have to load the data to dao .... but in some cases ... you have to elaborare data not for a final result but for deciding if you have to process or not the data.

**Comment by lvca** [comment]
No relevant anymore, closing it.
