### ISSUE TITLE
partial replacement of rids in a transaction

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4363]
2.1.rc2
using my test it seams to work partially.

<pre>
    List<ODocument> l=db.command(new OCommandSQL("select from #28:0")).execute();
      db.begin();
      ODocument d=new ODocument("d");
      d.save();
      for(int i=0;i<10;i++)  db.command(new OCommandSQL("update ? add huge_list = "+i)).execute(d);
db.commit();<- throws exception 
</pre>

**Comment by publicocean0** [comment]
in this block of code i found also another bug :

" update ? ..... is nit working also without transaction ... dont replace the parameter

**Comment by laa** [comment]
what kind of storage do you use remoter or embedded ?

**Comment by publicocean0** [comment]
remote

In that query ther are 2 bugs :
- the parameter i is not replaced also without transaction. In general the problem is in all the query using directly rid. 
- the temporaryly rids inside a transaction are replaced correctly is you use api save. But it seams there are misssing replacements when you use db.command()...

**Comment by publicocean0** [comment]
ah another little bug i found not so blocking anyway .... if you have a properrty name or a class name with a keyword name .... query throws exception (yesterday it happened with property "limit" for example ) I dont know if 2.1.rc3 was corrected.

**Comment by laa** [comment]
we do not support tx scope in sql commands right now but will be soon.
