### ISSUE TITLE
OObjectDatabaseTx browseAll() method returns inconsistant object versions

### ISSUE THREAD

**Issue by mael-morel** [orientechnologies/orientdb#4365]
OrientDb 2.0.10 (with community database)

Scenario : 
I save a bunch of new Departments objects in database. I fetch them with browseAll() and all is fine.

But if I update an object multiple times, when I fetch all of them with browseAll(), the edited one I receive is not the last version of it.

I add these two objects successively:

{
        "id": "#14:22",
        "version": "1",
        "name": "myName",
        "description": "myDescription",
        "active": true
    },
    {
        "id": "#14:23",
        "version": "1",
        "name": "myOtherObjectName",
        "description": "myOtherObjectDescription",
        "active": true
    }

I fetch them all is fine. Then I edit #14.22 three times in a row: 

{
        "id": "#14:22",
        "version": "4",
        "name": "myName4",
        "description": "myDescription that I edited 3 times now",
        "active": true
    }

All is fine when I fetch it with 
```
    OSQLSynchQuery<Department> query = new OSQLSynchQuery<>("select * from Department where name=myName4");
	List<Department> list = db().query(query);
```

But if I fetch all Departments objects with 
```
    List<Department> allDepartments = new ArrayList<>();
    Iterator<Department> it = new  OObjectDatabaseTx("myBase").browseClass(Department.class).iterator();
    while (it.hasNext()) {
			allDepartments.add(db().detachAll(it.next(), detached));
		}
		return allDepartments;
```

Then the object version is all messed up : I get version 1 to 4 at random. For example I can have this:
{
        "id": "#14:22",
        "version": "3",
        "name": "myName3",
        "description": "myDescription that I edited 2 times",
        "active": true
    },
{
"id": "#14:23",
"version": "1",
"name": "myOtherObjectName",
"description": "myOtherObjectDescription",
"active": true
}

**Comment by mael-morel** [comment]
We just found the issue : it was because of bad handling of the connection pool threads. It seems that every connection in the connection pool handle its own cache, and this cache is not refreshed when an other connection edit the same object in database. Still investigating

**Comment by lvca** [comment]
If you work with multiple clients concurrently, then you could have a old object: in case of concurrent modification exception, please reload the records.
