### ISSUE TITLE
Error in difference function - 2.1rc3

### ISSUE THREAD

**Issue by ranajit484** [orientechnologies/orientdb#4366]
Hi,
There seems to be an error in difference() function in the version 2.1rc3.

We are executing following query:
```
SELECT expand( $1 ) 
LET $2 = ( some query 1.... ),
$3 = (some query 2...)
$1 = difference( $2, $3 )
```
The output of $2 (some query 1) is:

![](https://sc-cdn.scaleengine.net/i/f08cf960dffde37fff52b3b159171ca5.png)

And the output of $3 (some query 2) is:

![](https://sc-cdn.scaleengine.net/i/3a3ac9a5b3f34d3335d191608c8c4d71.png)

Now the final output of above query should return an empty result set, which is working fine in the version 2.0.8.

But in the 2.1rc3 version it is returning result set as:

![](https://sc-cdn.scaleengine.net/i/a03a9b72915f5543195f63f9ef28402f.png)

This RC release has broken our application, is this RC supposed to break Backward compatibility?

**Comment by luigidellaquila** [comment]
Hi @ranajit484 

no, it is not our intention to break backward compatibility. This will be fixed before 2.1 GA

**Comment by luigidellaquila** [comment]
see also #3969

**Comment by luigidellaquila** [comment]
fixed in develop branch
