### ISSUE TITLE
Reader user can read users and roles

### ISSUE THREAD

**Issue by auterium** [orientechnologies/orientdb#4369]
As per documentation (http://orientdb.com/docs/last/Security.html), the "reader" user should have "...no access to internal information such as users and roles, themselves." On fresh installs of community 2.0.10 & 2.1 RC3 this is not true, as the reader user can query the OUsers class and read all users' data including the password property.

**Comment by maggiolo00** [comment]
AFAIK when you create a new database reader can only read records. If you go to the security panel in studio under roles you can see that reader role has access in read to the cluster.role so
I think the documentation is not updated.

**Comment by lvca** [comment]
Fixed, thanks.
