### ISSUE TITLE
Memory limits on big SELECT

### ISSUE THREAD

**Issue by wolkym** [orientechnologies/orientdb#4370]
I am hitting GC limits all the time on big requests, expecting `orientdb` to return millons of rows using `jdbc`. Unfortunately all memory is allocated and I cannot afford to devote more for db.  Is there any special settings to ensure that `orientdb` will work even if heap is depleted?

**Comment by maggiolo00** [comment]
Which Version  of orientdb do you use?

**Comment by cronacronis** [comment]
I have tried on `OrientDB 2.0.10 Community Edition` and `OrientDB 2.1-rc3 Community Edition` avaliable for  download from the website.
