### ISSUE TITLE
orientdb-enterprise OSGi bundle misses package import

### ISSUE THREAD

**Issue by uiterlix** [orientechnologies/orientdb#4371]
Version: 2.0.8-2.0.10

The orientdb-enterprise OSGi bundle misses the import for the com.orientechnologies.orient.core.storage package. This package is required for resolving the com.orientechnologies.orient.core.storage.ORecordDuplicatedException class. This results in a ClassNotFoundException being thrown instead of the ORecordDuplicatedException when violating a UNIQUE key index.

**Comment by lvca** [comment]
Could you provide us a Pull Request or even what to change in the descriptor?

**Comment by lvca** [comment]
We're releasing 2.1-rc4. If you can give it us soon we can include it on it ;-)

**Comment by uiterlix** [comment]
There's a PR waiting.

**Comment by lvca** [comment]
Commented the PR.

**Comment by uiterlix** [comment]
New PR waiting.

**Comment by lvca** [comment]
Thanks, merged.
