### ISSUE TITLE
Creating edge between non-vertex classes

### ISSUE THREAD

**Issue by AnthonyHebig** [orientechnologies/orientdb#4372]
--> from https://groups.google.com/forum/#!topic/orient-database/GbBuN22YIzo 

I'm working with OrientDb community version 2.1-rc3. (database type is "graph")

I've been doing some tests with OrientDbStudio (and you can easily reproduce these steps) :
- create a new class : Class1, no superClass
- create a new class : Class2, no superClass

- create a new record for Class1, let's say it has the following rid : #10:0
- create a new record for Class2, let's say it has the following rid : #11:0

- then you can do this : "create edge E from #10:0 to #11:0" and it works fine.

The creation of Edges between two classes that doesn't extend V should raise an error. (or if just one class does not extend V)

**Comment by smolinari** [comment]
Does "and it works fine" mean you can also query against edges created in this manner too? (I'd test myself, but I am indisposed ATM). Maybe this is a hidden gem of functionality! :smile: 

Scott

**Comment by AnthonySantnet** [comment]
yes, I've made some basic queries and I didn't notice anything odd. It also works with any class extending E.

**Comment by topofocus** [comment]
>>The creation of Edges between two classes that doesn't extend V should raise an error. (or if just one 
>>class does not extend V)

why?

I did the same. At the first glance it looks as the connection between a vertex and an edge ist simply a link through the in/out-property.  

If I understood some hints in the group right, than the border between Document and Graph-databases is not existing anymore. Thus every document should be able to have edges.

**Comment by luigidellaquila** [comment]
Hi guys,

please, don't do that, graph model is designed to be consistent and a lot of high level APIs (TinkerPop as first) rely on this consistency.
You can create these structures if you use Document API of course, but Graph API has to do all the checks and maintain the graph model consistent.
This problem will be fixed soon.

thanks

**Comment by smolinari** [comment]
Yes, this is in line with what you said to me here: 

https://groups.google.com/forum/#!topic/orient-database/qRfyE-4Vt84

Scott

**Comment by topofocus** [comment]
If this is the only intention, why are classes not automatically extended with an abstract class V ( unless present), if an edge is attached to it?

**Comment by AnthonyHebig** [comment]
it is also possible to create an Edge between two Edges :]

"create edge E from #12:0 to #12:1" where #12:0 and #12:1 are edges.

**Comment by lvca** [comment]
with last 2.1-SNAPSHOT release?

**Comment by AnthonyHebig** [comment]
no I'm still with 2.1-rc3

**Comment by emg110** [comment]
Dear friends, dear lvca : 
The type of graph in which edges can have edges with edges is actually called : "Hyper Graph".
Those edges who connect the edges only are called "Hyper Edges".
The hyper graph is a proven and widely used extension to original Graph theory and recent network theory to follow. If i may i would suggest to include (reinclude) the feature as an extra feature named HYPERGRAPH to be enabled or disabled per database in run time.
