### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4374]
Hi All,

Unfortunately, I got a new deadlock error.

I mailed you a thread dump.

I'm using last 2.1 SNAPSHOT.

Thank You

**Comment by laa** [comment]
Hi,
Which SNAPSHOT version do you use  (from which date) ?

Could you provide thread dump for this deadlock ?

**Comment by laa** [comment]
What emaild did you use ?

**Comment by thiagopm** [comment]
this SNAPSHOT is from 09/06. I sent to support@orientdb.com

**Comment by laa** [comment]
I see,
I am on it.
I think will fix it tomorrow.

**Comment by thiagopm** [comment]
Thank You.

**Comment by laa** [comment]
Fixed
