### ISSUE TITLE
How to make a HTTP Post request to a server side function (JavaScript) passing the parameters inside the request body?

### ISSUE THREAD

**Issue by marcelooliveira** [orientechnologies/orientdb#4375]
There is a scenario where we need to call a JavaScript server-side function we developed, and one of its parameters is a list of numbers which can be very long in some cases. According to the documentation (http://orientdb.com/docs/2.0/orientdb.wiki/OrientDB-REST.html#function) the parameters are passed in the URL of the HTTP Post request, but we're afraid we'll have to break the process into many requests due to URL length constraints. Is there a way to invoke a function in the way we are doing, but instead passing the parameters in the body of the HTTP request? That would cost only a single round trip to the server. Thanks in advance.

**Comment by lvca** [comment]
It's quite easy to support, let me see if we can do that quickly

**Comment by lvca** [comment]
Just in time to be in 2.1-rc4 ;-) You can now use it by passing a JSON as request payload. Example:
```json
{ "name": "Jay", "surname": "Miner" }
```
The mapping in this case will be not positional, but by parameter name.

**Comment by marcelooliveira** [comment]
Whoa, that was fast. Thank you very much, lvca!

**Comment by lvca** [comment]
;-)

**Comment by joaobarcia** [comment]
Hah, great. We were just looking for this. Thanks for the amazingly quick implementation (even if it was in the past)

**Comment by lvca** [comment]
;-)

**Comment by jfernandezrico** [comment]
Hello everyone. How can I access to he parameter desired (eg: name) within the function?
Thank you
