### ISSUE TITLE
1.7 - dangerous DELETE SQL bug can delete all records in cluster

### ISSUE THREAD

**Issue by qd01a** [orientechnologies/orientdb#4380]
delete from mycluster where #14:239   <--  returns error, correct
delete from mycluster where @rid=#14:239  <-- erases single record, correct

These should likely return an exception, but instead...

delete from mycluster #239   <-- BUG, DELETES ALL records in cluster!
delete from mycluster #14:239   <-- BUG, DELETES ALL records in cluster!

this also likely applies to later versions of OrientDB as well, though haven't tried yet.

**Comment by luigidellaquila** [comment]
Hi @qd01a 

thanks for reporting, this issue is present in old OrientDB versions, but it was fixed in 2.1

Luigi
