### ISSUE TITLE
Schema not validated on alter property or drop property/create property

### ISSUE THREAD

**Issue by fandji** [orientechnologies/orientdb#4382]
If i do the following sequence of sql commands, i would expect that after creating an edge and then altering the schema in a way that the created edge doesn't correspond to, that i do get a warning.
I could then remove the strictmode, update my data and try again. Or I could choose the actual behaviour, where the schema is only enforced on new data, changes.

```
create class v1 extends v

alter class v1 strictmode=true

create class v2 extends v

alter class v2 strictmode=true

create class e1 extends e

alter class e1 strictmode=true

create property v1.in_e1 linklist e1
create property v2.out_e1 linklist e1

create property e1.in link v1

create property e1.out link v2

create vertex v1

create vertex v2

create edge e1 from (select from v2) to (select from v1)

alter property e1.in linkedclass v2

drop property e1.in

create property e1.in link v1
```

**Comment by lvca** [comment]
Which version? Have you tried a recent one?

**Comment by fandji** [comment]
We tried on 2.0.10 and on 2.1-rc3

**Comment by tglman** [comment]
Hi @fandji, 

yes as today implementation we don't check persistent data on set of linked type, and a few other constraint.

We have in the plan to add this feature in a close future, but not for the 2.1, for now it's better that you double check your data when you are define a new constraint.

**Comment by fandji** [comment]
Hi @tglman 

Is it possible to add to the documentation which constraints aren't checked on update or creation, so schema migrations can be planned acordingly?

**Comment by tglman** [comment]
updated the documentation
