### ISSUE TITLE
2.1-rc4 vertex return wrong edges

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#4386]
I���m used latest 2.1-Snapshot and getEdges return wrong edges... 

```java
for (Edge edge : graph.getVertex("#12:287").getEdges(Direction.OUT)) {
	System.out.println(edge);
}
```
very strange output: 
```
e[#23:12334][#12:206-item->#13:2670]
e[#23:12336][#12:206-item->#13:2672]
e[#23:12345][#12:206-item->#13:2674]
e[#23:12359][#12:206-item->#13:2675]
e[#23:12361][#12:206-item->#13:2677]
e[#23:12375][#12:206-item->#13:2679]
e[#23:12382][#12:206-item->#13:2682]
e[#23:12397][#12:206-item->#13:2684]
e[#23:12411][#12:206-item->#13:2686]
e[#23:12420][#12:206-item->#13:2688]
e[#23:12433][#12:206-item->#13:2691]
e[#23:12442][#12:206-item->#13:2693]
e[#23:12456][#12:206-item->#13:2695]
e[#23:12472][#12:206-item->#13:2697]
e[#23:12478][#12:206-item->#13:2698]
```
must���t be from #12:287 ??? 

@laa has a link to that database

Regards
Valentin

**Comment by laa** [comment]
Fixed after running of ridbag repair tool.

**Comment by smolinari** [comment]
Out of curiosity and to possibly avoid the problem, but what caused the discrepancy to begin with?

Scott

**Comment by lvca** [comment]
Some releases was affected by this bug that under high concurrency scenario could create wrong links. Event if this has been already fixed, you could have a database with wrong links. If this is the case, running the `repair database --fix-ridbags` console command, fixes this problem once forever.

**Comment by smolinari** [comment]
Thanks for the explanation.

Scott
