### ISSUE TITLE
Use of SecureRandom can affect performance

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4387]
Orient Db's use of Secure Random can put a drag on performance, esp. if the machine runs out of entropy. On a test machine, secure random nextBytes() can be blocked for 20 seconds or more. 

![screen shot 2015-06-18 at 1 21 23 pm](https://cloud.githubusercontent.com/assets/6212848/8230138/9c2900a8-15bd-11e5-9d47-fa8d33315054.png)

 insert folder-4 [BLOCKED]
java.security.SecureRandom.nextBytes(byte[]) SecureRandom.java:455
java.util.UUID.randomUUID() UUID.java:145
com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OOperationUnitId.generateId() OOperationUnitId.java:33
com.orientechnologies.orient.core.tx.OTransactionRealAbstract.<init>(ODatabaseDocumentTx, int) OTransactionRealAbstract.java:86
com.orientechnologies.orient.core.tx.OTransactionOptimistic.<init>(ODatabaseDocumentTx) OTransactionOptimistic.java:111
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(OTransaction$TXTYPE) ODatabaseDocumentTx.java:2073
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin() ODatabaseDocumentTx.java:2043
com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.begin() OrientTransactionalGraph.java:185
com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OPartitionedDatabasePool, OrientConfigurableGraph$Settings) OrientTransactionalGraph.java:81
com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OPartitionedDatabasePool, OrientConfigurableGraph$Settings) OrientGraph.java:128
com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx() OrientGraphFactory.java:74
com.stimulus.archiva.database.blueprints.BluePrintDatabase.getGraph() BluePrintDatabase.java:120
com.stimulus.archiva.database.blueprints.BluePrintDatabase.getProperty(OrientElement, String) BluePrintDatabase.java:833
com.stimulus.archiva.database.blueprints.BluePrintVersionedItem$1.compute(Vertex) BluePrintVersionedItem.java:71
com.stimulus.archiva.database.blueprints.BluePrintVersionedItem$1.compute(Object) BluePrintVersionedItem.java:1
com.tinkerpop.pipes.filter.FilterFunctionPipe.processNextStart() FilterFunctionPipe.java:24
com.tinkerpop.pipes.AbstractPipe.next() AbstractPipe.java:89
com.tinkerpop.pipes.util.Pipeline.next() Pipeline.java:115
com.tinkerpop.pipes.util.PipeHelper.counter(Iterator) PipeHelper.java:107
com.tinkerpop.gremlin.java.GremlinPipeline.count() GremlinPipeline.java:1534
com.stimulus.archiva.database.blueprints.BluePrintVersionedItem.hasVersion(String) BluePrintVersionedItem.java:81
com.stimulus.archiva.domain.database.DatabaseService.isNewVersion(TreeItem, Blob) DatabaseService.java:448
com.stimulus.archiva.domain.database.DatabaseService.insertItem(Blob, Database$ItemType, DatabaseService$InsertAction) DatabaseService.java:376
com.stimulus.archiva.domain.database.DatabaseService.insertBlob(Blob, DatabaseService$InsertAction) DatabaseService.java:332
com.stimulus.archiva.domain.database.DatabaseService.insertBlob(Blob) DatabaseService.java:312
com.stimulus.orientdb.workout.Workout$2.run() Workout.java:116
java.lang.Thread.run() Thread.java:745
com.stimulus.util.BoundedExecutor$1.run() BoundedExecutor.java:27
java.lang.Thread.run() Thread.java:745

**Comment by carloprad** [comment]
are you using a bare metal machine, or a virtualized environment?

**Comment by jamieb22** [comment]
Bare metal. Look, its not a serious problem. Andrey said to post a bug report, even though it is not important.

**Comment by lvca** [comment]
Actually we use SecureRandom also on HTTP Connection to generate unique IDs. Please keep me posted on this.

**Comment by machak** [comment]
we've been running into same problems with UUID generation in our virtual layer, includes some benchmarks: https://issues.onehippo.com/browse/REPO-237

**Comment by machak** [comment]
in short: total time :+1: 
 30688 ms (/dev/random )
vs 
4014 ms when using ( -Djava.security.egd=file:///dev/urandom )

**Comment by machak** [comment]
dunno why thumb showed up ;-)

**Comment by lvca** [comment]
Found stuff about it: http://stackoverflow.com/questions/137212/how-to-solve-performance-problem-with-java-securerandom

**Comment by lvca** [comment]
@machak could you try running OrientDB with this setting? `-Djava.security.egd=file:/dev/./urandom`

**Comment by machak** [comment]
@lvca I tried and had no problems running it. My test data set was about 70000 vertex nodes and 200000 lightweight edges, with slightly better performance (I would need to run it few more times to get exact numbers).  
SHA1PRNG is used in case of -Djava.security.egd=file:/dev/./urandom, 
NativePRNG otherwise. 
NOTE: as mentioned in stackoverflow article, -Djava.security.egd=file:/dev/urandom does *not* work (at least on Linux, JDK 1.8.0_40-b25 64x.

**Comment by lvca** [comment]
So WDYT about put this "tricks" in tuning performance? or should we put this in server.sh?

**Comment by machak** [comment]
I would put it in tricks or even better in performance tuning. 
btw:  time reported is (average of 10 runs of total time spent):
urandom: 0,64% vs 
default: 2.68%. 
I was using https://github.com/RichardWarburton/honest-profiler/wiki to measure results

**Comment by lvca** [comment]
@laa WDYT about using this?

**Comment by laa** [comment]
We do not use this uid any more, so we can drop it.

**Comment by laa** [comment]
Sorry not for the all cases. Let me think how we can replace it.

**Comment by laa** [comment]
Fixed.
