### ISSUE TITLE
Create a place to announce all technical improvements of orientdb

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4390]
Hi 
during working with the community here I found out that it is really hard to track orientdb changes without to watch in all tickets. I often read answer like this:

"I'd suggest you to try OrientDB X.X-SNAPSHOT where we introduced many optimizations."

As a project leader I always want to stay up to date even when just a keyword performance has been improved. e.g https://github.com/orientechnologies/orientdb/issues/4299#issuecomment-112495696

I recommend to create a news feed or something like that where we can focus on technical changes.

**Comment by smolinari** [comment]
:+1: +1

Scott

**Comment by dehbmarques** [comment]
:+1:

**Comment by StarpTech** [comment]
Any updates?

**Comment by laa** [comment]
@StarpTech I believe we already have such one https://github.com/orientechnologies/orientdb-labs

**Comment by smolinari** [comment]
@laa 

Hey Andrey. Can anyone add an OEP? 

I'd have three. 

1. Exchange "Cluster" for "Shard" throughout all of ODB code and documentation.
2. Lucene Indexing Enhancements
3. True NoSQL support

Or should there be a suggestion made first and then the ODB team creates the OEPs? The OEP process itself isn't completely clear to me. Sorry.

Scott

**Comment by laa** [comment]
@smolinari you can not , but if issue which you propose will be found reasonable by one of the committers it will be added there. The OEP process itself is described in https://github.com/orientechnologies/orientdb-labs/blob/master/OEP_1.md

**Comment by smolinari** [comment]
Ok. Thanks. I saw the OEP 1, but didn't read in detail, as I thought it was just the proposal and not the final process. 

Can users/ the community create issues for OEP suggestions?

Scott

**Comment by laa** [comment]
@smolinari such issues are welcome​ !!!

**Comment by smolinari** [comment]
Ah! Great! Then I'll be putting the text together and will open the three suggestions I mentioned above. 

Scott

**Comment by santo-it** [comment]
Hi all,

Wondering if we can now close this ticket.   In addition to [OrientDB Labs](https://github.com/orientechnologies/orientdb-labs), and starting from OrientDB v. 2.2.15, we now have [Release Notes](https://github.com/orientechnologies/orientdb/wiki/OrientDB-2.2-Release-Notes). This specifically tries to answer the need that our community users and customers have to be able to track OrientDB changes more easily, without the need of searching and opening all closed tickets

Many Thanks,

**Comment by smolinari** [comment]
No problem from my side. Ticket can be closed. I am not the OP though. 

Scott

**Comment by santo-it** [comment]
Thanks @smolinari . Hi @StarpTech I am closing this now. Please feel free to comment/reopen if needed
