### ISSUE TITLE
ver=2.0.10, console and gremlin can not connect to server through proxy?

### ISSUE THREAD

**Issue by zhuobao** [orientechnologies/orientdb#4392]
I am working in a intranet environment, may need proxy to connect to the orientdb server instance. On a linux client PC, I tried with using and without proxy setting (export http_proxy=....), in both cases, console and gremlin console failed to connect to the server.

server and console versions are community-2.0.10

with proxy setting:
console connection attempt returned messages are:

orientdb> connect remote:10.94.67.243/GratefulDeadConcert admin admin

Disconnecting from the database [null]...OK
Connecting to database [remote:10.94.67.243/GratefulDeadConcert] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create a connection to remote server address(es): [10.94.67.243:2424]

without proxy setting:

orientdb> connect remote:10.94.67.243/GratefulDeadConcert admin admin

Connecting to database [remote:10.94.67.243/GratefulDeadConcert] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create a connection to remote server address(es): [10.94.67.243:2424]

My questions is can console and gremlin console connection using proxy? if yes, how to setup?

**Comment by lvca** [comment]
the connection is not HTTP, but binary. You can still use Studio through a proxy.
