### ISSUE TITLE
how to have a blacklist when traversing

### ISSUE THREAD

**Issue by rwnew2012** [orientechnologies/orientdb#4395]
I am using 2.0.9 version. when traversing the graph, is that possible to have a blacklist such that vertices in that blacklist won't be visited, either for filtering or to speed up traverse a little bit. I tried, e.g.

select ID from (traverse both(@rid!='#9:1') from #9:0 while $depth<=2 strategy breadth_first)

the vertex '#9:1' is not in the output, but the running time is similar to the case without blacklist. So how to both have blacklist and speed traverse running time. Thanks

**Comment by lvca** [comment]
Please could you post questions on: https://groups.google.com/forum/#!forum/orient-database

**Comment by rwnew2012** [comment]
Thanks, @Ivca, sorry about the spam. I did not know there is a community group.

**Comment by lvca** [comment]
No problem ;-)
