### ISSUE TITLE
Database import manual index error -- cant add key as CompositeIndex

### ISSUE THREAD

**Issue by barttlebeWinslow** [orientechnologies/orientdb#4397]
Hi Im new to Orient and need help.

I am importing an earlier backup gzip from 1.7 version of Orient to an empty database of a newer version of Orient (2.0.8) using ODabataseImport in my unit test and the import commands in the Orient console. All appears normal (clusters, classes, indexes) until my manual indexes are being imported--an exception is thrown in both cases:

< Impossible add as key of a CompositeIndex a value of type java.lang.String >

I've read earlier reports of server-side validation being a potential culprit so I disabled it but the issue persists.

Does anyone understand what is causing the exception (serialization during the export, a misconfiguration on the Orient server).  Any help greatly appreciated.

**Comment by lvca** [comment]
This is a question, but we rather use the Issue Tracker to track enhancements and bugs. The best place to ask for questions about OrientDB is the Community Group: https://groups.google.com/forum/#!forum/orient-database. Please could you create a new topic with your question on it? Thanks.
