### ISSUE TITLE
Strange query behaviour

### ISSUE THREAD

**Issue by Wanderfalke** [orientechnologies/orientdb#4398]
Following query:
```
select in.key as attribute_key from (select expand(outE('show_in_header')) from type_of_resource where key = 'article') where (sorting = 1 OR sorting = 0) order by position asc, sorting asc
```
does not actually do correct ordering.

Adding "position" to selected fields yields correct sorting:
```
select in.key as attribute_key, position from (select expand(outE('show_in_header')) from type_of_resource where key = 'article') where (sorting = 1 OR sorting = 0) order by position asc, sorting asc
```

**Comment by Ziink** [comment]
Probably not a bug. From the docs :

>ORDER BY is in accordance to the standard SQL syntax specifying fields with an optional ASC or DESC (default is ASCending). **If you are using a projection in your query, ensure the ORDER BY field is included in this projection.**

**Comment by lvca** [comment]
@Ziink You're right, it's not a bug, but the way OrientDB is woking. However I'd like to leave this issue open to support this feature to be more close to RDBMS world.

**Comment by luigidellaquila** [comment]
This is a duplicate of 

https://github.com/orientechnologies/orientdb/issues/3992

Please track the other issue

Closing, thanks

Luigi
