### ISSUE TITLE
How to start distributed servers without sync?

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4405]
Hi,Is there any way to start 3 distributed servers without synchronize?
Can I use autoDeploy = false?

We are copying the same DB to both 3 servers. But when we start, one of then send this request:

2015-06-19 16:29:52:666 WARNI [orientdb01]->[[orientdb21]] requesting deploy of
database 'ilang' on local server... [OHazelcastPlugin]

The problem is that it spends almost 3 hours, because our DB is 80GB.

Thanks in advance.

**Comment by lvca** [comment]
Yes, this is exactly the purpose of `autoDeploy` setting. If you set it = false the database is never asked to the cluster, but local copy is used.

**Comment by thiagopm** [comment]
I'm using, but getting a lot of errors ( conflicts,  timeout and querum 2 not reached)... Do you have any Idea where is my mistake? Here is my log.

https://s3.amazonaws.com/a-several/orient-server.log.0

**Comment by lvca** [comment]
Seems database are not aligned on all the servers. For example if you have 1 record more in the  database on server 01, the next createRecord will assign a RID higher on server 01, forcing a rollback. The solution is to align databases at the beginning, by hand (copy files before starting) or activate "autoDeploy:true" in cfg.

**Comment by thiagopm** [comment]
Lvca, ontem à noite, eu copiei o mesmo banco de dados para todos os servidores (3). Quando me virei no segundo servidor solicitou um deploy banco de dados que foi corretamente iniciado no primeiro servidor. Então eu me virei em terceiro servidor, que solicitou um banco de dados implantar também. Hoje de manhã apenas o segundo servidor foi implantado e ONLINE. Não posso virar o terceiro servidor quando o segundo está implantando? Você sabe se esta solução distribuída funciona bem em meu cenário (banco de dados maior do que 80GB e elevado número de atualização)?

**Comment by thiagopm** [comment]
Could "hotAlignment=true" be the problem?

**Comment by lvca** [comment]
Next release will support incremental backup (we're designing this feature right now to work on distributed), but for now you could copy the database manually and set `autoDeploy:false`. Question: are the servers on the same LAN? What's the fastest way to copy the database on all the nodes?

**Comment by thiagopm** [comment]
I'll try again. All server are in the same AWS region, but distinct  availability zone, for us it's the same LAN. I normally copy and paste (80GB/8 min), its faster than compress - copy - extract.

**Comment by thiagopm** [comment]
Ok, It's working now, but we got a lot of this WARN: 
<code>2015-06-22 13:53:22:721 WARNI Local node 'orientdb21' is not the master for cluster 'useronline' (it's 'orientdb21'). 
Switching to a valid cluster of the same class: 'useronline_orientdb21' [ODistributedStorage]</code>

Is it normal?

Right now one node is in deadlock. For this problem I'm opening an Issue.

Thank You
