### ISSUE TITLE
live query test failed in rc4

### ISSUE THREAD

**Issue by dongwq** [orientechnologies/orientdb#4410]
live query test failed in rc4, code as below:

https://gist.github.com/dongwq/6116eb9a2e0791637a50

**Comment by luigidellaquila** [comment]
Hi @dongwq 

to use LiveQuery you have to enabled it.
On a remote server, you just have to set the right flag in the orientdb-server-confg.xml file. On an embedded (or in-memory) server you have to manually register the live query hook:

```java
    OLiveCommandExecutorSQLFactory.init();
    ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:testLiveQuery");
    db.activateOnCurrentThread();
    db.registerHook(new OLiveQueryHook(db));
```

I'm updating the documentation right now

**Comment by luigidellaquila** [comment]
done, docs updated

**Comment by dongwq** [comment]
very well, Thanks.
