### ISSUE TITLE
expand exclude and rid absent

### ISSUE THREAD

**Issue by j-mi-jim** [orientechnologies/orientdb#4419]
i'm using 2.1-rc4.

When using expand (exclude) in a query, the rid is absent in the results
select expand(@this.exclude("fieldname")) from ClassName

ClassName extends V

**Comment by luigidellaquila** [comment]
fixed in develop branch.
ATTENTION: now records are returned with valid rid, so a doc.save() will remove excluded fields!!!

rid can be excluded too with the same syntax:

```select expand(@this.exclude("fieldname", "@rid")) from ClassName```
