### ISSUE TITLE
Be able to have orient participate in JTA transactions [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#442]
This is [Issue 442](http://code.google.com/p/orient/issues/detail?id=442) moved from a Google Code project.
Added by 2011-06-19T01:37:59.000Z by [cur...@stanfordcomputing.com](http://code.google.com/u/108311982134405103168/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v1.4.0
### Original description

```
It would be great to be able to use a JTA transaction manager to manage transactions in orientdb. This would let you start a transaction in one method and call many other methods that participate in the transaction but not having to pass the connection object around. Each method could create its own connection but still be in the transaction.
```

**Comment by anmoldeep0123** [comment]
https://github.com/selvarajchennappan/orientdbjca/tree/master/jca
