### ISSUE TITLE
[question] Best way to upgrade orientdb?

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4422]
With Import & Export I had a lot failures also reported as issues here.
Is it possible to do a drop in replacement with the db and what do I have to pay attention?

How do I upgrade orientdb without any troubles? Can I just overwritte all files ?

I don't find any good and precise documentation for this scenario. Every import and upgrade is scary for me. Please help. Thanks!

**Comment by maggiolo00** [comment]
hi @StarpTech 

Which are the version of OrientDB involved in the upgrate?

**Comment by StarpTech** [comment]
@maggiolo00 I'm talking about the general case not version specific.

**Comment by red-0ne** [comment]
You should have the directory referencing your database files outside orientdb directory. Same thing with the config file (you should specify the path of the config file when starting the db server). This way upgrades do not override your work.

**Comment by StarpTech** [comment]
I don't talking about what could be override. My question is how can I update my orientdb version in a proper way. Is it possible to replace all java files but db files untouched? My current solution is:

1. Export db as json, copy config file
2. Remove whole orientdb
3. Download new orientdb version, create db, import json, replace config file.
4. Start server

**Comment by red-0ne** [comment]
This is exactly what I am talking about. Keeping your db files untouched.

1 . Have an `orientdb-server-config.xml` somewhere outside orientdb directory (`/etc/orientdb/orientdb-server-config.xml`)
2 . Edit `/etc/orientdb/orientdb-server-config.xml` by adding (or replacing ?) the `server.database.path` property. It should point somewhere outside your orientdbdirectory:
```xml
<properties>
...
  <entry value="/var/lib/orientdb" name="server.database.path" />
</properties>
```
3 . Get your new orientdb as usual (remove old, download and extract). Personally I perfer updating using git:
```bash
cd /my/path/to/orientdb
git pull origin master
ant clean installg
```
4 . And finally start the server with your "old" config file:
```bash
CONFIG_FILE="/etc/orientdb/orientdb-server-config.xml" /my/path/to/orientdb/bin/server.sh
```
The update consists of steps 3 and 4 only.

**Comment by StarpTech** [comment]
@red-0ne thank you very much. I fear that the databases between each version are not binary compatible.)

**Comment by smolinari** [comment]
@red-0ne :+1: 

@lvca - This bit of information should be in the installation (and upgrade) section of the manual.

Scott
