### ISSUE TITLE
Deadlock (distributed environment) 2.1 rc4

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4423]
Hi,

I'm  starting an distributed environment (3 servers). After 15 min working, third server had a deadlock, after 5 min deadlock on the second server then on the first.

Here is the dumps:
https://s3.amazonaws.com/a-several/OrientDB_Distrbuted_deadlock.rar

Thank you

**Comment by lvca** [comment]
I cannot download the file (access denied)

**Comment by thiagopm** [comment]
Sorry, Try again please

**Comment by thiagopm** [comment]
Today our traffic is a bit higher... I tried again using a single instance and I got a deadlock again.
https://s3.amazonaws.com/a-several/OrientDB_SingleInstance_Deadlock.rar

**Comment by laa** [comment]
Hi, what distribution do you use, on my distribution, one of method calls actually pointing to   
this line of code (at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.remove(OSBTreeBonsaiLocal.java:518)):

try {

which obviously can not be true.
We had issue with rc4 distribution on one environment. Could you try this one: https://www.dropbox.com/s/xs2w59sncv9ln4m/orientdb-community-2.1-SNAPSHOT-distribution.zip?dl=0 .
It is the same rc4 but version name was not updated. If you do not have issues with this one I think we should update rc4 distribution.

**Comment by laa** [comment]
The same issue for other stack trace from dump:
at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.size(OSBTreeBonsaiLocal.java:485) 
it is actually 
atomicOperationsManager.acquireReadLock(this);
    try {

and of course try { can not be line of code on which stack trace goes down.

**Comment by thiagopm** [comment]
I upgraded our server to 16 cors cpu and 30GB.

I change our heapSize to 4GB and DiskCache to 20GB.

When I started with this snapshot, the thread number raised to 500 and I got another problem during 2 minutes:
<code> 2015-06-22 17:58:16:383 WARNI Reached maximum number of concurrent connections (
1002), reject incoming connection from /10.0.1.64:17440 [OServerNetworkListener]
</code>
https://s3.amazonaws.com/a-several/OrientDB_Reached+maximum+Connection.rar

Now It's working. 

Can I increase the max connection number?

**Comment by laa** [comment]
Yes, sure, I am closing bug and ask Luca, to recreate distribution because current is obviously broken one. About your question use following property network.maxConcurrentSessions

**Comment by thiagopm** [comment]
Thank you.

This problem happened again yesterday night for 20 min. suddenly the number of threads raises to 500 and stops to response.
<code>
2015-06-22 21:48:49:494 WARNI Reached maximum number of concurrent connections (1000), reject incoming connection from /10.0.1.64:33874 [OServerNetworkListener]
</code>

**Comment by laa** [comment]
Could you send latest thread dump then and reopen issue ?

**Comment by laa** [comment]
Or better to open one with correct title .

**Comment by thiagopm** [comment]
For sure.
Done
