### ISSUE TITLE
Query cache

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4424]
Many DBMS vendors have a query cache that can be tuned and could be very helpful in case:
- you have a lot of RAM
- the database is mostly read
- you execute the same query over and over again

References:
- **MySQL**: https://dev.mysql.com/doc/refman/5.0/en/query-cache-configuration.html

**Comment by StarpTech** [comment]
+1

**Comment by lvca** [comment]
The most important features are:
- usage of Weak reference to avoid stressing the GC
- configurable minimum threshold of execution time: has no sense caching all the queries, but just those that take > X ms
- configurable maximum resultset size: no sense to keep a huge resultset in RAM

**Comment by lvca** [comment]
This is already available in `2.2.x` branch.

**Comment by lvca** [comment]
Since we have no contract to don't update the returning resultset of a query, query results can be cached only if `setCacheableResult(true)` is called on request.

All the command executed from Binary Protocol and HTTP protocol have this flag set automatically. Why? Because the resultset is sent to the client and never modified on the server.

The query cache is used only on idempotent commands, like SELECT and TRAVERSE.

**Comment by StarpTech** [comment]
@lvca and how I can flush the cache from the binary/http protocol?

**Comment by lvca** [comment]
The query is automatically flushed as soon as you create/update/delete a record, so it's not needed. However I just realized that this command could be useful. Working to an easy solution.
