### ISSUE TITLE
Incorrect depth value in traverse query in a distributed mode

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4425]
create class V1 extends V

create class E1 extends E

create vertex V1

create vertex V1

create edge E1 from <1> to <2>

select *, $depth from (traverse in('E1') from <2>)

Result: depth value for both records = 0

Expected result: depth value for <1> = 1

Note that the issue is happening only in a distribution mode.

**Comment by lvca** [comment]
Fixed. Will follow test case
