### ISSUE TITLE
get field value in function(javascript)?

### ISSUE THREAD

**Issue by prefinnx** [orientechnologies/orientdb#4428]
It should be simple, but I can not find the related topic in the document or other tutorials.

I am writing function from OrientDB studio(V2.0.6, OSX) with _javascript_,  and can __not__ access the field value from the returning object of a select query, like;
```javascript
var g = orient.getGraph();
var r = g.command('sql','select * from e limit 2');
var r0 = r[0];
return r0.in;  // gives blank output
```
where however `return r0` gives the right output:
```
[
    {
        "@type": "d",
        "@rid": "#13:0",
        "@version": 3,
        "@class": "eat",
        "out": "#14:1",
        "in": "#12:0", 
        "@fieldTypes": "out=x,in=x"
    }
]
```
Can any one help to get the vertex rid in the filed 'in', so i can use it later in the following part of this function to do some more jobs?

**Comment by rogergajraj** [comment]
I having this exact problem right now. I tried a solution proposed by Luca on stackoverflow.com but it didn't work. see here: http://stackoverflow.com/questions/28360386/orientdb-accessing-query-result-data-in-server-side-function

Why did you close this issue? Did you find a solution? If so, what did you do?

**Comment by rogergajraj** [comment]
you can try r0.getProperty("in")
