### ISSUE TITLE
Exception: com.orienttechnologies..SchemaException (OrientDB 2.1-rc4)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4432]
Yourkit reports an com.orienttechnologies..SchemaException occurred internally. I am unsure whether this is a bug or not, but it seems to be a hard error.

Back traces

+------------------------------------------------------------------------------------------------------------------------------------------+-------------+
|                                                            Reverse Call Tree                                                             |    Count    |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------+
|  +---com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(String, int[], int, OClass[]) OSchemaShared.java:963  |  17  100 %  |
|    |                                                                                                                                     |             |
|    +---com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(String, int[], OClass[]) OSchemaShared.java:403       |             |
|      |                                                                                                                                   |             |
|      +---com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(String, OClass, int[]) OSchemaShared.java:388       |             |
|        |                                                                                                                                 |             |
|        +---com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(String, OClass) OSchemaProxy.java:100              |             |
|          |                                                                                                                               |             |
|          +---com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$7.call(OrientBaseGraph) OrientBaseGraph.java:1390                     |  10   59 %  |
|          |                                                                                                                               |             |
|          +---com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph) OrientBaseGraph.java:1297                     |   7   41 %  |
+------------------------------------------------------------------------------------------------------------------------------------------+-------------+

**Comment by jamieb22** [comment]
Not a bug.

**Comment by lvca** [comment]
@jamieb22, are you opening one issue per each exception that collects YourKit? OrientDB internally uses Exceptions, so this could be normal.

**Comment by jamieb22** [comment]
Yes, this is why I sent the questions directly to Andrey. I just wanted him to be aware of some of the internal exceptions that are occurring in case something important needed to be fixed before 2.1 release.
