### ISSUE TITLE
Exception: java.lang.NumberFormatException (OrientDB 2.1-rc4)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4433]
YourKit reports a NumberFormatException. I am unsure whether this is a bug or not but it seems to be a hard error.

+------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|                                                                  Reverse Call Tree                                                                   |   Count    |
+------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|  +---java.lang.Integer.parseInt(String, int) Integer.java:492                                                                                        |  6  100 %  |
|    |                                                                                                                                                 |            |
|    +---java.lang.Integer.parseInt(String) Integer.java:527                                                                                           |            |
|      |                                                                                                                                               |            |
|      +---com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.validateName(String) ODiskWriteAheadLog.java:752      |            |
|        |                                                                                                                                             |            |
|        +---com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$1.accept(File, String) ODiskWriteAheadLog.java:664  |            |
|          |                                                                                                                                           |            |
|          +---java.io.File.listFiles(FilenameFilter) File.java:1246                                                                                   |            |
+------------------------------------------------------------------------------------------------------------------------------------------------------+------------+

**Comment by laa** [comment]
It is not a bug we use parser of numbers to validate name pattern.
