### ISSUE TITLE
Exception: EOFException (OrientDB 2.1-rc4)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4434]
Yourkit reports an EOFException. I am unsure whether this is a bug or not. 

Back traces

+----------------------------------------------------------------------------------------------------------------------------+------------+
|                                                     Reverse Call Tree                                                      |   Count    |
+----------------------------------------------------------------------------------------------------------------------------+------------+
|  +---java.io.RandomAccessFile.readInt() RandomAccessFile.java:827                                                          |  1  100 %  |
|    |                                                                                                                       |            |
|    +---com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.readNextNameIdEntry() OWOWCache.java:995    |            |
|      |                                                                                                                     |            |
|      +---com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.readNameIdMap() OWOWCache.java:973        |            |
|        |                                                                                                                   |            |
|        +---com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.initNameIdMapping() OWOWCache.java:955  |            |
|          |                                                                                                                 |            |
|          +---com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.isOpen(String) OWOWCache.java:602     |            |
+----------------------------------------------------------------------------------------------------------------------------+------------+

**Comment by laa** [comment]
It is not a bug, we read mapping between file names and file IDs using file abstraction, so we can detect it only in this way. Good news is that we do it only during DB open.
