### ISSUE TITLE
Reached maximum number of concurrent connections

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4438]
Hi,

This problem happened sometimes.

Suddenly the number of threads raises up to 500 and stop to response.

<code>
2015-06-22 21:48:49:494 WARNI Reached maximum number of concurrent connections (1000), reject incoming connection from /10.0.1.64:33874 [OServerNetworkListener]
</code>

Here is the dump:
https://s3.amazonaws.com/a-several/OrientDB_Reached+maximum+Connection.rar

Thanks

**Comment by thiagopm** [comment]
Hi, it happened again and I got more info to you.

https://s3.amazonaws.com/a-several/OrientDB_Reached+maximum+Connection+2.rar

Thanks

**Comment by lvca** [comment]
If you run out of available connections, this means the client never closes them? What driver are you using?

**Comment by thiagopm** [comment]
I don't know. We are using OrientDB-NET.binary. 

At first moment, it's working well. We create the connection pool  (in our case 10 connections). The applications asks connections to the client, the connection is used and released normally... 

Suddenly, I think when the concurrent connections raises, seems that the server stops to respond, then the connections are not released and every new connection asked to the client results in a new connection opened.

**Comment by lvca** [comment]
Try to see with "netstat -a" how many sockets are open.

**Comment by thiagopm** [comment]
Now 14, but I when it happens are hundreds

**Comment by lvca** [comment]
Ok, so seems the driver doesn't manage tcp/ip connections properly, or you are not closing them.

**Comment by thiagopm** [comment]
In the driver, there is no limit to connections opened. We can change this code to have a limit.

In our application we always use " using () { } ", that calls the Dispose() method. It should to close the connection. And during most of the time does.

**Comment by tglman** [comment]
@thiagopm  yes if you can put a limit on the number of connection open will be cool, like you see this is required by the server, you can also recycle connection after Dispose to reduce "hand shacking " time and reduce latency.

**Comment by thiagopm** [comment]
OK.
When do you say to recycle connection, it's means reuse the opened connections or should we do something more? We are reusing connections in the pool, but our pool size was 10, then if we need more than 10 connection in the same time, every extra connections was been opened and closed. Now I increased our connection pool to 50.

**Comment by tglman** [comment]
I mean by recycle connection that after one thread finished to use that connection you don't need to close it but in can be used by another thread after that, by the way be aware that the connection should be used by only one thread each time.

**Comment by thiagopm** [comment]
Yes, it's exactly what the drivers connection pool does. As I said on last message we were recycling only 10 connections, now we increased to 50.

**Comment by thiagopm** [comment]
Yes, it's exactly what the drivers connection pool does. As I said on last message we were recycling only 10 connections, now we increased to 50.

**Comment by tglman** [comment]
Perfect, let me know if this solve your problems and if we can close the issue.

Did you solve the problem in your internal code or did you change the Driver code, will be really coll if we coyuld get a contribution on that.

**Comment by lvca** [comment]
Any news on this?

**Comment by thiagopm** [comment]
Hi Luca,
It does not happened again, we only increase MaxConnections to 20000. But last days our traffic is been flat, then is more difficult to say you that is ok.
I think you can close the bug, any news I tell you and reopen the bug.

sorry my late answer, I'm on vacation...

**Comment by lvca** [comment]
Ok, I'm closing it now. Enjoy your vacation ;-)
