### ISSUE TITLE
Object Saving Issue in 2.0.11

### ISSUE THREAD

**Issue by dshurt** [orientechnologies/orientdb#4440]
**Issue:**   When saving a entity with a composite entity the composite entity's 'rid'  is not map to parent object correctly which breaks the relationship.

**Version:** 2.0.11
**Operation Mode:** Embedded Orient DB in webapp using the OObjectDatabaseTx 

**Example:**

``` java
public class AttributeCode
{
    @OneToOne(orphanRemoval = true)
    private AttributeCodePk attributeCodePk;
...

}

public class AttributeCodePk
{
    private String attributeType;
    private String attributeCode;
....
}
```

Example use:

``` java
AttributeCode attributeCode = new AttributeCode();
AttributeCodePk attributeCodePk = new AttributeCodePk();
attributeCodePk.setAttributeType("A");
attributeCodePk.setAttributeCode("B");
attributeCode.setAttributeCodePk(attributeCodePk);
```

**To persist:**

``` java
OObjectDatabaseTx db = getConnection();
T t = null;
try {
   t = db.save(attributeCode);
} catch (Exception e) {
...(Error handling)
} finally {
   closeConnection(db);
}
```

**Results:**
select attributeCodePk from AttributeCode

returns

```
\#  | @CLASS | attributeCodePk
1233|null  |com.orientechnologies.orient.core.record.impl.ODocument|QXR0cmlidXRlQ29kZVBrQGF0dHJpYnV0ZVR5cGU6IlRFU1QtQ0FT
RS1UTVAiLGF0dHJpYnV0ZUNvZGU6IkEi  (This looks like a toString of the created entity?)
```

Trying to query the AttributeCode now fails because the RID is not correct.
AttributeCodePk is RID is stored fine just the relationship is stored incorrectly.

Expected Results:

``` sql
select attributeCodePk from AttributeCode
```

should be:

```
\#   | @CLASS | attributeCodePk
1233|null  |#14:1504  (RID)
```

1.7.10 puts in the rid in the relationship on save and works great.

**Comment by tglman** [comment]
I tried this in 2.0.x and 2.1-SNAPSHOT and i couldn't reproduce it, from the report seems that the linked object get embedded, can you double check it or post a full test case

**Comment by dshurt** [comment]
I check it again with 2.0.12 and 2.1-rc5 and I still have the same issue.  
I've trace through the code but no luck discovering the cause.  The embedded object appears to get saved it just doesn't get linked in the parent object.   The object appears to get serialized correctly to ODocument but, it's not saving correctly.  I tried saving the embedded object first and then adding it to the parent.   The parent still had a bad relationship.

**Comment by dshurt** [comment]
FYI:  I recently tried 2.1.25 and I found that this issue can be corrected by add "@Embedded" and corresponding "@Embeddable"  jpa annotations to have it correctly serialize the embedded object.  On 1.7.x it linked fine without the annotations but for 2.x it need them.   For other users what tipped me off to the solution was looking at https://github.com/orientechnologies/orientdb/blob/82bbe0c661868a4488e96fcac2cfbbedda372afb/object/src/main/java/com/orientechnologies/orient/object/serialization/OObjectSerializerHelper.java
