### ISSUE TITLE
Remote query: improve performance

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4442]
ODocument class remove the `buffer` (as byte[]) once the document has been fully unmarshalled. Well, this saves memory, but in case of remote protocol, the result is usually sent back to the client and since there is no `buffer` anymore, it must be re-marshalled just to be sent to the network.

So in case of call from network protocol, and the network protocol is the same as storage one, we could avoid removing the `buffer`.

So, since buffer could be never null, how can manage the case when the object has been completely unmarshalled? Probably we'd need another flag like `fullyUnmarshalled`.
### UPDATE

Look at the comments. After a debug session, by skipping the fetchplan processing did the job.
### UPDATE 2

The full unmarshall is still executed to generate the JSON, so we still need this enhancement.

**Comment by lvca** [comment]
By a quick debug session, remote commands like queries, were sub-optimized. The main culprit was the FetchPlan, that in order to retrieve the document's field names, executed a full-deserialize of record. This could be expensive, RAM consuming and last but not least, obliged a full re-marshall of the record to be sent to the client.

**Comment by lvca** [comment]
I have introduced a small optimization, where in case of default fetchplan, the entire process of applying the fetchplan is skipped.

**Comment by lvca** [comment]
So with this fix, the solution in original issue's description has no much sense anymore. Changing the text...

**Comment by tglman** [comment]
make sense

**Comment by lvca** [comment]
In 3.0 fetch plans have been replaced with advanced projections.
