### ISSUE TITLE
Unable to parse scientific notation in JSON file using ODocument.fromJSON method

### ISSUE THREAD

**Issue by mscarlett** [orientechnologies/orientdb#4445]
The ODocument.JSON method fails when parsing a JSON file which has numbers in scientific notation. Scientific numbers appear to be valid JSON according to http://www.json.org/. I encountered this issue using version 2.1-rc3 of the OrientDB core library.

The issue can be reproduced as follows:

    import com.orientechnologies.orient.core.record.impl.ODocument;

    public static void main(String[] args) {
        // Both of these result in OSerializationException causing the import to fail
        ODocument doc1 = new ODocument();
        doc1.fromJSON("{\"scientificnumber\" : 9e-06}");
        ODocument doc2 = new ODocument();
        doc2.fromJSON("{\"scientificnumber\" : 9E-06}");
        // None of these work either
        ODocument doc3 = new ODocument();
        doc3.fromJSON("{\"scientificnumber\" : 9e-6}");
        ODocument doc4 = new ODocument();
        doc4.fromJSON("{\"scientificnumber\" : 9E-6}");
        // This does not raise an exception but causes it to be parsed as a String
        ODocument doc5 = new ODocument();
        doc5.fromJSON("{\"scientificnumber\" : \"9E-06\"}");
    }

I would have expected scientific notation to get parsed as the BigDecimal data type.

**Comment by lvca** [comment]
This is still missing in OrientDB. Why BigDecimal and not double?

**Comment by mscarlett** [comment]
Double seems like a much more logical choice for the default. I only said BigDecimal due to wondering what the expected behavior is when the value is out of range.

**Comment by mscarlett** [comment]
It looks like this can be resolved by modifying ORecordSerializerJSON.getValue so that the portion of code that checks if the number has a decimal point also checks if the number is in scientific notation. The scientific notation can subsequently be parsed using the Double constructor.

The [current code](https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/serialization/serializer/record/string/ORecordSerializerJSON.java#L442) is as follows:

    if (c == null && !iFieldValue.isEmpty()) {
        // TRY TO AUTODETERMINE THE BEST TYPE
        if (ORecordId.isA(iFieldValue))
            iType = OType.LINK;
        else if (OStringSerializerHelper.contains(iFieldValue, '.')) {
            // DECIMAL FORMAT: DETERMINE IF DOUBLE OR FLOAT
            final Double v = new Double(OStringSerializerHelper.getStringContent(iFieldValue));

            if (canBeTrunkedToFloat(v))
                return v.floatValue();
            else
                return v;
        } else {
            final Long v = new Long(OStringSerializerHelper.getStringContent(iFieldValue));
            // INTEGER FORMAT: DETERMINE IF DOUBLE OR FLOAT

            if (canBeTrunkedToInt(v))
                return v.intValue();
            else
                return v;
        }
    }

Currently this code attempts to parse scientific notation as an integer then throws an exception when the Long constructor is called at the line "final Long v = new Long(OStringSerializerHelper.getStringContent(iFieldValue));". However we can modify OStringSerializerHelper.contains(iFieldValue, '.') to something like iFieldValue.matches(".*[\\.Ee].*") so that the presence of 'e' or 'E' results in decimal format. It works for the following test case:

    @Test
    public void testScientificNotation() {
        ODocument doc = new ODocument();
        doc.fromJSON("{'number': -9e-06}");
        Double number = doc.field("number");
        Assert.assertEquals(number, -9E-6);
    }

**Comment by lvca** [comment]
Thanks, merged.
