### ISSUE TITLE
backup database results in a zip file that cannot be opened by OSX

### ISSUE THREAD

**Issue by timothysoehnlin** [orientechnologies/orientdb#4449]
When performing a backup, 

    backup database /tmp/backup-nocompress.zip --compressionLevel=0

The backup generates and restores properly.

The problem I am having, is when I attempt to unzip the file so I can add compression after the backup, and I get the following error:

    unzip backup-nocompress.zip
    Archive:  backup-nocompress.zip  
    OrientDB Backup executed on Wed Jun 24 09:13:40 EDT 2015
    warning [backup-nocompress.zip]:  5005070011 extra bytes at beginning or within zipfile
       (attempting to process anyway)  
    error [backup-nocompress.zip]:  start of central directory not found;
      zipfile corrupt.
      (please check that you have transferred or created the zipfile in the
      appropriate BINARY mode and that you have compiled UnZip properly)

**Comment by lvca** [comment]
Which version?

**Comment by timothysoehnlin** [comment]
2.0.x not certain of the specific minor version

**Comment by lvca** [comment]
Already fixed in 2.1.
