### ISSUE TITLE
SQL problem with column named "date"

### ISSUE THREAD

**Issue by DanielHoffmann** [orientechnologies/orientdb#4450]
Hello I have been having some problems with SQLs with a column named "date". For example my Entity class below has a column with that name, the following SQL does not work, it returns 0 records:

`SELECT * FROM Entity WHERE date BETWEEN date('2015-06-01', 'yyyy-MM-dd') AND date('2015-06-03', 'yyyy-MM-dd')`

while this SQL works just fine

`SELECT * FROM (select * FROM Entity) WHERE date BETWEEN date('2015-06-01', 'yyyy-MM-dd') AND date('2015-06-03', 'yyyy-MM-dd')`

Yet they both have the same semantics.

I am using version 2.0.8 and I am not 100% sure, but I believe the first SQL did work on version 1.7.8

**Comment by luigidellaquila** [comment]
Hi @DanielHoffmann 

I tested it in both 2.0.13 and 2.1 snapshot and it seems to work fine.
(I also tried some schema variants, like defining indexes on "date" property)

Could you please confirm?

Thanks

**Comment by DanielHoffmann5A** [comment]
Hello @luigidellaquila I changed jobs and can no longer confirm the problem, but I redirected my co-worker to this issue. One side note is that I had a schema on the class `Entity`, on it the `date` attribute was set as not null, mandatory and of type date. I also had a unique index on this attribute.

**Comment by luigidellaquila** [comment]
Thanks, closing this in the meantime. In case I missed something please reopen
