### ISSUE TITLE
Regression of 2.0.11

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4453]
i have 2 version of odb 2.0.11-SNAPSHOT which build in Jun 10th. another is 2.0.11 which build yesterday.

Running on 2.0.11-SNAPSHOT, do load testing (20 concurrent request to insert data), all data insert correctly.

But if i run 2.0.11, run single thread sending request sequentially, looks ok. But if i sending concurrent requests, most of record saving failed, check on server log :
Error during insertion of key in index input : {"patchId":9990000016,"@class":"bodyAngle","_cid":293,"raw":"#278:1467","meanZ":0.3885992,"syncLog":"#189:72","meanY":0.1529076,"tzone":"0","time":"1434323024741","meanX":0.8929008,"value":-24.048149,"user":"#106:170"} Error during insertion of key in index 

And after this happen, no matter single thread or multi thread request, all failed

**Comment by laa** [comment]
Hi, what is log statement ?

**Comment by henryzhao81** [comment]
Just send you my test case, please give a try.

**Comment by henryzhao81** [comment]
what's the progress for this issue

**Comment by laa** [comment]
Hi, Henry
Sorry for delay. During database creation script I got:

orientdb {db=pharos}> create property event.metric LINK metric

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.create property event.metric LINK metric

Error: java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OType.METRIC

Could you provide fixed script ?

**Comment by laa** [comment]
Hi, Henry.
Do you have any update on this issue ?

**Comment by henryzhao81** [comment]
Hi Andrey, sorry about the late, i updated sql script just remove create
property event.metric. Please give a try. Thanks,

Henry,

2015-07-10 5:14 GMT-07:00 Andrey Lomakin <notifications@github.com>:

**Comment by laa** [comment]
Hi, Henry.
Any updates on this issue ?

**Comment by henryzhao81** [comment]
Hi Andrey, I send u a email yesterday with updated script, have u got it?

**Comment by henryzhao81** [comment]
I send u a email yesterday with updated script, not sure if got it or not. I will send it again anyway.

**Comment by laa** [comment]
Fixed.

**Comment by mattaylor** [comment]
Is this fix going to get back ported to 2.0x?

**Comment by laa** [comment]
that is 2.0.x we backported it to 2.1 and I assure you that design of 2.1 is more robust than 2.0. So I suggest to at least test your application on 2.1 version.
