### ISSUE TITLE
Autoupdate edges from lightweight, automigrate for consistency

### ISSUE THREAD

**Issue by iofjuupasli** [orientechnologies/orientdb#4454]
From http://orientdb.com/docs/last/Tutorial-Using-schema-with-graphs.html

> Unfortunately, the index tells us 0 entries are indexed. Why? We have already created the Owns relationships between "Luca" and "Ferrari Modena." In that case, OrientDB had already created a lightweight edge before we set the rule to force creation documents for Owns instances. So, you need to drop and recreate the edge.

Why it isn't handled by db? I think all updates to schemas shouldn't broke consistency. If it breaks, error should be displayed. e.g. trying restrict class of `in` for edge to `A`, when there is edge that have `B` in `in` - error should be displayed and nothing changed. But if all `in`s is `A` all edges should be converted to records.

Now changing schema is unpredictable, and painful

**Comment by lvca** [comment]
In OrientDB 2.1-rc4 and further you can execute:

```sql
OPTIMIZE DATABASE -lwedges
```

But there is no the opposite.

**Comment by iofjuupasli** [comment]
I can't find the docs for this command. Does it converts edges from lightweight to records?

**Comment by lvca** [comment]
Just updated in docs: http://orientdb.com/docs/last/SQL-Optimize-Database.html

**Comment by iw2rmb** [comment]
Is there a command to convert all lightweight edges to classic?

**Comment by lvca** [comment]
No relevant anymore, closing it.
