### ISSUE TITLE
ETL dbAutoCreate not working

### ISSUE THREAD

**Issue by Kalatheeswaran** [orientechnologies/orientdb#4456]
Hi,
I have the following JSON file for converting data from a csv to 'Account' class in the graph database 'test'. I want to use the dbAutoCreate property to create the database when I execute the ETL process. But it doesn't work and it shows 'the database is not configured on the server' error.

Thanks & Regards 
Kalatheeswaran
------------
CSV File
-----------
{
  "config": {"parallel":true},	
  "source": { "file": { "path": "C:/Users/kala/Desktop/graphCSV/Account.csv" } },
  "extractor": { "row": {} },
  "transformers": [
    { "csv": {} },
    { "vertex": { "class": "Account" } }
  ],
  "loader": {
    "orientdb": {
       "dbURL": "remote:localhost/test",
       "dbAutoCreate": true,
	   "dbType": "graph",
       "classes": [
		 {"name": "Account", "extends": "V"}
       ], 
	   "indexes": [
         {"class":"Account", "fields":["vid:integer"], "type":"UNIQUE" }
       ]
    }
  }
}

**Comment by lvca** [comment]
It can't auto create a database against a server, but only locally, using "plocal:" prefix.

**Comment by Kalatheeswaran** [comment]
Is there any way to autocreate against the server?
