### ISSUE TITLE
GUI > Graph: node cut by container div

### ISSUE THREAD

**Issue by damoiser** [orientechnologies/orientdb#4459]
Playing with the Graph tab on the GUI, I noticed that the printed graph was cut (I guess) when resizing the browser-window. I have enlarged the width of the window.

Attached example of the view.

![node_cutted](https://cloud.githubusercontent.com/assets/1612582/8356394/446aca3e-1b55-11e5-9f24-713ca8659be8.jpg)

I guess that the following DOM element has not updated the width: it appears smaller than the parent container. 

![dom_element](https://cloud.githubusercontent.com/assets/1612582/8356399/4b245a98-1b55-11e5-8475-ac3c43fe2002.jpg)

Running on a Mac OS X 10.10.3 - with Google Chrome Version 43.0.2357.124 (64-bit)

**Comment by maggiolo00** [comment]
hi @damoiser 
Fixed in 2.2.x
