### ISSUE TITLE
OAutomaticBackup - firstTime always shifted by one hour 

### ISSUE THREAD

**Issue by guglielmomoretti** [orientechnologies/orientdb#4460]
Hi,

I was experimenting the automatic backup feature of OrientDB, trying to setup the following schedule.

- Once a day
- At 16:03:00 

The rest of the configuration is as default in orientdb-server-config.xml:
The XML looks like the following:

```xml
<handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
         <parameters>
                 <parameter value="true" name="enabled"/>
                 <parameter value="1d" name="delay"/>
                 <parameter value="16:03:00" name="firstTime"/>
                 <parameter value="c:/backup" name="target.directory"/>
                 <parameter value="${DBNAME}-${DATE:yyyyMMddHHmmss}.zip" name="target.fileName"/>
                 <parameter value="9" name="compressionLevel"/>
                 <parameter value="1048576" name="bufferSize"/>
                 <parameter value="test" name="db.include"/>
                 <parameter value="" name="db.exclude"/>
         </parameters>
</handler>
```

When the server starts, the following line is printed out:

```
Automatic backup plugin installed and active: delay=86400000ms, firstTime=**Thu Jun 25 17:03:00 CEST 2015**, targetDirectory=c:/backup/ [OAutomaticBackup]
```

The date shown is not what i planned it to be.
Of course as a temporary workaround I can shift it by on hour.

Did i miss something or it can be considered as a bug?

**Comment by lvca** [comment]
OrientDB always get GMT time.

**Comment by guglielmomoretti** [comment]
Thanks @lvca , I couldn't find it on the docs

Regards
Guglielmo

**Comment by lvca** [comment]
You was right: I've just added a comment in docs about it.
