### ISSUE TITLE
ETL parallel execution error

### ISSUE THREAD

**Issue by Kalatheeswaran** [orientechnologies/orientdb#4464]
Hi,
I have two csv files A and B with B having a many to one relation with A. When I model this using a graph and execute the ETL process with the configuration parallel as true, I get the following errors: 
1) Error in pipeline execution, retry = 1/10 (exception=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #14:16 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v1 your=v0))

2) Exception in thread "OrientDB ETL pipeline-14" com.orientechnologies.orient.etl.OETLProcessHaltedException: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record B{vid:, ....}: found duplicated key '103' in index 'B.vid' previously assigned to the record #13:39 RID=#13:39

Please provide any help.

Thanks,
Kalatheeswaran

**Comment by Kalatheeswaran** [comment]
Please provide any suggestions

**Comment by lvca** [comment]
What version of OrientDB are you using?

**Comment by Kalatheeswaran** [comment]
Hi Luca,
Thanks for the response. 
I am using version 2.0.8

**Comment by Kalatheeswaran** [comment]
Hi 
I would like some response please

**Comment by lvca** [comment]
Can we have the source file where we can reproduce it? Also in PVT.

**Comment by Kalatheeswaran** [comment]
This is the source file code:
{
	"config" : {
		"parallel" : true
	},
	"source" : {
		"file" : {
			"path" : "PathToCSVFile"
		}
	},
	"extractor" : {
		"row" : {}

	},
	"transformers" : [{
			"csv" : {}

		}, {
			"vertex" : {
				"class" : "ClassB"
			}
		}, {
			"edge" : {
				"class" : "eB_A",
				"joinFieldName" : "aID",
				"lookup" : "ClassA.vid"
			}
		}
	],
	"loader" : {
		"orientdb" : {
			"dbURL" : "PathToDB",
			"dbUser" : "userName",
			"dbPassword" : "password",
			"dbType" : "graph",
			"classes" : [{
					"name" : "ClassA",
					"extends" : "V"
				}, {
					"name" : "ClassB",
					"extends" : "V"
				}, {
					"name" : "eB_A",
					"extends" : "E"
				}
			],
			"indexes" : [{
					"class" : "ClassB",
					"fields" : ["vid:integer"],
					"type" : "UNIQUE"
				}
			]
		}
	}
}

**Comment by lvca** [comment]
We fixed a problem in parallel in 2.1-rc6. Could you please use that?
