### ISSUE TITLE
SQL with subquery and unwind: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mbhulin** [orientechnologies/orientdb#4466]
This SQL statement works:
select in, Score as s1, in.outE('PROB_IS_AT').Score as s2 from PROB_IS_AT where out = #19:2 and in.@class = 'Object' unwind s2
Result:
 in | s1 |s2
#19:1 | 2 | 5
#19:1 | 2 | 5
#19:0 | 5 | 10 

These SQL statements result in a NullPointerException:
select  eval(s1 * s2) as cscore from (select in, Score as s1, in.outE('PROB_IS_AT').Score as s2 from PROB_IS_AT where out = #19:2 and in.@class = 'Object' unwind s2)

select in, Score as s1, in.outE('PROB_IS_AT').Score as s2, eval(s1 * s2) as cscore from PROB_IS_AT where out = #19:2 and in.@class = 'Object' unwind s2

PROB_IS_AT is an edge-class with Score as an integer field. Object is a vertex-class.

OrientDB version 2.1-rc4, SQL executed in Studio

**Comment by luigidellaquila** [comment]
Hi Martin,

I see you closed this issue, is it invalid or was it closed by mistake?

Thanks

Luigi

**Comment by mbhulin** [comment]
Hi Luigi,
the NullPointerException was my fault. The eval-function needs the expression as String. I forgot the quotes. Since I didn't find a possibility to delete an issue I closed it.
Kind regards
Martin
