### ISSUE TITLE
New function shortestPaths()

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4474]
shortestPaths(from, to, { labels: [ <label>*[,] ], maxDepth: <maximum-depth>, limit: <max> } )

We need a function that returns multiple shortest paths, ordered by shortness. `limit` is the maximum number of shortest paths you want to retrieve.

**Comment by Unduli** [comment]
My apologies in advance if not proper place but,

I'd also appreciate if Dijkstra function also allows you to specify mandatory vertices and/or subpaths.

**Comment by lvca** [comment]
@Unduli WDYT about creating a new issue with the detail of what you're looking for?

**Comment by jmdavid** [comment]
This is a must!  Is there a chance to have this function integrated before 2.2?  Is it too late for 2.1?

**Comment by voxadam** [comment]
I ran across this while digging through the issues database after a sleepless night (I blame @lvca for creating OrientDB in the first place).

Anyways, @Unduli's reply about an implementation of Dijkstra's algorithm in addition to shortestPaths() got me thinking. Would someone more familiar with the internal intricacies and implementation of OrientDB be willing to write up a draft of "best practices" for the implementing algorithms like the ones being talked about here for use in OrientDB?

Release quality documentation isn't necessary, I'd be more that willing to take even a rough sketch proof, expand, and generally get the addition into a state where it could be included in the official developer documentation.

**Comment by lvca** [comment]
@voxadam I hope you're blaming my name anymore :-) @luigidellaquila is working to the new pattern matching, probably he's the right guy to ask for this guide. Nice idea.

**Comment by gg4u** [comment]
Hi, testing shortestPath() (no ShortestPath**s**).

I obtained only one results linking between two vertexes; but there should be more paths of the same length.

I understood ShortestPath**s** will returned more paths ordered by shortness.
Does shortestPath return multiple paths of the same shortest length or just one and only result?

**Comment by pkoppstein** [comment]
As best I can tell, currently (e.g. In 2.1.7) there is no way to determine, in general, the edges corresponding to the shortest path that is found by any of the shortest-path builtins.  This seems to be a major oversight, but perhaps it can be remedied relatively easily, e.g. by adding a parameter so that the shortest path functions can be instructed to return vertices and edges.  (Alternatively, variant functions could be added, e.g. shortestRoute(s).)
