### ISSUE TITLE
Create Lucene Index returns error [bug]

### ISSUE THREAD

**Issue by stuk88** [orientechnologies/orientdb#4476]
The error returned is:
```java.lang.AbstractMethodError```

orientDB ver: 2.0.11
lucene plugin installed: orientdb-lucene-2.0-SNAPSHOT-dist

do I need to do anything more than just add the plugin?

**Comment by eugene-kamenev** [comment]
@stuk88 this worked for 2.1.RC3-RC4:
```
create index Tag.title on Tag (title) FULLTEXT ENGINE LUCENE METADATA {"analyzer":"org.apache.lucene.analysis.ru.RussianAnalyzer"}
```

**Comment by maggiolo00** [comment]
@stuk88 
try with 2.0.12

**Comment by maggiolo00** [comment]
@stuk88 
did you try with OrientDB >= 2.0.12 ?

**Comment by maggiolo00** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
