### ISSUE TITLE
Java create new function not working?

### ISSUE THREAD

**Issue by njeff3** [orientechnologies/orientdb#4479]
The following code is not working in v2.0.11 and v2.1-rc4. Trying in implement UPPPER and LOWER in SQL.DB running on FreeBSD 10 openjdk 1.8_45 client is win7 jdk 1.8_45

			OSQLEngine.getInstance().registerFunction( "upper",
                                          new OSQLFunctionAbstract( "upper",  1,  1 ){
				@Override
  				public String getSyntax() 
  				{
    				return "upper(<first>)";
  				}

				@Override
  				public Object execute( Object iThis,  OIdentifiable iCurrentRecord, Object icurrentResult, Object[] iParameters,  OCommandContext iContext ) 
  				{
    				if( iParameters[0] == null ) return null;

					String s = (String) iParameters[0];

					return s.toUpperCase();

  				}

				@Override
  				public boolean aggregateResults() 
  				{
    				return false;
  				}
				});

			String text = "j";

			List<ODocument> result = db.command(
  				new OSQLSynchQuery<ODocument>( "select * from Person where upper(lname) like UPPER('"+text+"%') order by lname" )
  			).execute();

			ListIterator<ODocument> it = result.listIterator();
			while( it.hasNext() )
			{
				ODocument person = (ODocument)it.next();
				System.out.println( (String)person.field( "lname" ) );
			}

the client errors:

     [java] Jun 27, 2015 10:26:52 PM com.orientechnologies.common.log.OLogManager log
     [java] INFO: OrientDB auto-config DISKCACHE=4,231MB (heap=1,796MB os=8,075MB disk=156,797MB)
     [java] UPPER - Exception: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #13: Error on parsing command at position #0: Error on parsing query
     [java] Query:  upper(lname) LIKE UPPER('j%') ORDER BY lname ASC
     [java] ------------------^

the server errors:

orient.core.exception.OQueryParsingException: Error on parsing query at position #23: Error on parsing command at position #0: Error on parsing query
Query:  lname LIKE UPPER('j%') ORDER BY lname ASC
----------------------------^ [ONetworkProtocolBinary]
2015-06-27 22:26:48:307 SEVER {db=meditdb} Sent run-time exception to the client /192.168.0.22:49843: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #13: Error on parsing command at position #0: Error on parsing query
Query:  upper(lname) LIKE UPPER('j%') ORDER BY lname ASC

**Comment by luigidellaquila** [comment]
Hi @njeff3 
Are you working in remote? How are you registering the function on the server side? If you are in remote, registering it only on the client is not enough

Luigi
