### ISSUE TITLE
SQL: new command to manage command cache

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4481]
This issue has been forked by #4424 to provide a command to control command cache.

**Comment by StarpTech** [comment]
Simple how mysql it does: https://dev.mysql.com/doc/refman/5.0/en/query-cache-in-select.html

```
SELECT SQL_CACHE id, name FROM customer;
SELECT SQL_NO_CACHE id, name FROM customer;
```
and when I understand correctly, you want to flush the cache after every create/update/delete statement? This would make sense in table based databases but in graph databases this would mean that every small change will flush the cache. (whether the query traversed the elements or not).

What do you think about this solution:

1. The default way is that all SELECT statements will be cached as soon as no idempotent query will be executed.

2. When you use the TRAVERSE command with the `SQL_CACHE` flag like:
`SELECT SQL_CACHE name, age FROM (traverse outE() from #13:0)` all traversed elements will  be marked with a unique key which represents the cache key so if you run the query twice the iterator can determine if the "path" belongs to the query above. If you execute a non-idempotent query the system will check if the records includes a "cache key" when yes the key will be deleted so the cache will be flushed immediately.

**Comment by lvca** [comment]
@StarpTech the solution (2) won't work, because maybe in your traversal you specified a condition and if you create/update a vertex/edge where the condition now matches the traversal, the command should be discarded.

**Comment by StarpTech** [comment]
@lvca  yes this case I forgot but how do you solve the problem that a graph path will be cached and that the cache won't be flushed after a arbitrary non-idempotent command on the whole db?

**Comment by lvca** [comment]
Evaluating if it's the case of evict the cache could be too expensive, so for now we have 2 strategies:
- evict_all, just evict all the results
- evict_percluster, where it consider the cluster touched to do eviction

So using "evict_all" is safer, because remove all the results, but reduce also the chance to use it. "evict_percluster" works well, but when you do traversal, so the target clusters are not recognized at query compile time, and some result could be old

**Comment by StarpTech** [comment]
Please do not make caching as default. This feature is great but could lead to unpredictable behaviour. I think it needs more investigation of the caching strategy.

**Comment by lvca** [comment]
Command Cache will be off by default, to activate it in 2.2 you have to set `-Dcommand.cache.enabled=true` at startup
