### ISSUE TITLE
Creating indexes from the Java API

### ISSUE THREAD

**Issue by wcraigtrader** [orientechnologies/orientdb#4482]
I've been using the Java API to create vertex indexes for our application, as follows:

	OrientGraphFactory factory = new OrientGraphFactory(dbpath, DBUSER, DBPASS);
	OrientGraphNoTx g = factory.getNoTx();

	OrientVertexType v = g.createVertexType( "vt", "V" );
    v.createProperty( "key", OType.STRING );
	v.createProperty( "uuid", OType.STRING );

	Parameter<?,?> UNIQUE_INDEX = new Parameter<String, String>("type", "UNIQUE");
	Parameter<?,?> indexclass = new Parameter<String, String>("class", "vt");
	g.createKeyIndex( "key", Vertex.class, indexclass, UNIQUE_INDEX  );
	g.createKeyIndex( "uuid", Vertex.class, indexclass, UNIQUE_INDEX );

This has worked great for us, but I have a few classes that need to use a case-insensitive index. Doing so from the Java API is undocumented, and the source has offered no insights.  I tried creating the index from SQL, as follows:

    create index vt.key on vt (key COLLATE CI) unique

This appears to work (the number of entries in the index match the number of vertices of that class), 
but when I query the index from the Java API I get no results.

    for (Vertex v : graph.getVertices(vt.key", uuid) ) {
        return (OrientVertex) v;
    }
        
Looking at the sources (OrientBaseGraph::createKeyIndex() and OCommandExecutorSQLCreateIndex::execute()) they appear to be creating completely different types of indexes (OPropertyIndexDefinition and OSimpleKeyIndexDefinition).

What do I have to do to create a key index that uses a case-insensitive collation?

**Comment by GiuliaBrignoli** [comment]
Hi.
try to replace this:
g.createKeyIndex( "key", Vertex.class, indexclass, UNIQUE_INDEX  );
with:
g.command(new OCommandSQL("create index vt.key on vt (key COLLATE CI) unique")).execute();

and try to use this loop:
for (Vertex v : g.getVertices() ) {
   System.out.println(v1.getProperty(“key”));
   System.out.println(v1.getProperty(“uuid”));
}
Regards,Giulia

**Comment by wcraigtrader** [comment]
@GiuliaBrignoli, I tried your approach, but as previously indicated, the underlying type of index is different.

My solution was to write these Java methods:

    /** Create a unique case-insensitive index for a Vertex */
    static public void create_vertex_ci_index( OrientBaseGraph g, String classname, String key ) {
        OPropertyIndexDefinition index = new OPropertyIndexDefinition( classname, key, OType.STRING );
        index.setCollate( "ci" );

        ODatabaseDocumentTx db = g.getRawGraph();
        OIndexManagerProxy im = db.getMetadata().getIndexManager();
        OSchemaProxy schema = db.getMetadata().getSchema();
        OClass cls = schema.getOrCreateClass(classname, schema.getClass("V") );
        String indexName = classname + "." + key;
        ODocument metadata = new ODocument();
        im.createIndex(indexName, "UNIQUE_HASH_INDEX", index, cls.getPolymorphicClusterIds(), null, metadata );
    }

    /** Create a unique index for a Vertex */
    static public void create_vertex_index( OrientBaseGraph g, String classname, String key ) {
        final Parameter<?,?> uniqueIndex = new Parameter<String, String>( "type", "UNIQUE_HASH_INDEX" );
        final Parameter<?,?> indexClass = new Parameter<String, String>( "class", classname );
        g.createKeyIndex( key, Vertex.class, indexClass, uniqueIndex );
    }

And I call them like this:

    create_vertex_ci_index( g, "vt", "key" );
    create_vertex_index( g, "vt", "uuid" );

Ideally, the OrientGraph createKeyIndex method should take another Parameter (say, 'collate') that could be used to set the collation on the index. I may submit a patch for that if I have time.

**Comment by maggiolo00** [comment]
Implemented by supporting a new Paramenter

```
new Parameter<String, String>("collate", "ci")
```
