### ISSUE TITLE
SQL Parser error

### ISSUE THREAD

**Issue by nadestin** [orientechnologies/orientdb#4486]
I believe that I hit a bug in the SQL parser. Here is how to reproduce it:
> create class ParserProblem
> create property ParserProblem.LinkFrom string
> create property ParserProblem.LinkTo string
Now:
> select from ParserProblem
0 item(s) found. Query executed in 0.0 sec(s). (OK)
> select LinkTo from ParserProblem
0 item(s) found. Query executed in 0.0 sec(s). (OK)
> select LinkFrom from ParserProblem
Error: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #5: Error on parsing query
Query:  from ParserProblem
----------^

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class 'FROM' was not found in current database
Oops!

I am running Community edition Version 2.0.11.
It seems that parser splits property name 'LinkFrom' into Link and From and then compains about wrong syntax. Interesting that statement:
> select LinkFrom, LinkTo from ParserProblem
works fine, but statement:
> select LinkTo, LinkFrom from ParserProblem
fails.

**Comment by luigidellaquila** [comment]
fixing it right now

**Comment by luigidellaquila** [comment]
fixed in develop and 2.0.x
