### ISSUE TITLE
Search by @rid makes full scan

### ISSUE THREAD

**Issue by vslinko** [orientechnologies/orientdb#4488]
Query `select from item where @rid = '#11:10000'` makes full scan:
![](https://api.monosnap.com/rpc/file/download?id=xXgw4vAr6XTfhlte3H9TqNS4102jlC)

Query `select from item where @rid = '#11:10000' limit 1` read all documents before:
![](https://api.monosnap.com/rpc/file/download?id=TXptNNRdeM5JhS52codMoFJNIE1D5y)

After I created index `create index Item.@rid UNIQUE` nothing changed:
![](https://api.monosnap.com/rpc/file/download?id=rXKmMDQm24xCUl7MfRLSJO212WoSA3)

**Comment by lvca** [comment]
Have you tried:
```sql
select from item where @rid = #11:10000
```

**Comment by vslinko** [comment]
Yes, it works, thank you :smile:
