### ISSUE TITLE
Hanging thread with ODatabaseDocumentTx

### ISSUE THREAD

**Issue by KadekM** [orientechnologies/orientdb#4492]
```
new ODatabaseDocumentTx(s"memory:test")
```

this line allocates thread in jvm, which I haven't found a way to manually terminate, other than quitting the process. This becomes issue, especially for scala programmers who are running sbt ~test (continuously tests are running as you modify file). The thread count increases and later you'll get OutOfMemoryException.

It is easily reproducible:
1. start sbt
2. display all threads
3. run `test` manually couple of times times (with only mentioned code in test)
4. display all threads

If you run the mentioned code in cycle `for 1 to 100` it will allocate only 1 thread, so to spot it it's needed to manually start test.

Is there some way we can force the thread to stop ? `drop` `release` `close` on db instance did not help. I have not investigated it any further.

Tested in 2.1-rc4

**Comment by lvca** [comment]
How can we reproduce it with a Java Test Case?

**Comment by laa** [comment]
Sorry I did testing of this issue and can not reproduce it on rc5. Could you try it ?

**Comment by KadekM** [comment]
As far as I know it happens in RC5, but I haven't tested it first-handed (YET). As soon as I have a bit more time I will look into it and repost issue. Hopefully I will be able to simulate it via javatest.

**Comment by laa** [comment]
If it will happen again could you send thread dump too ?
