### ISSUE TITLE
dijkstra function ignores <weightEdgeFieldName>

### ISSUE THREAD

**Issue by mbhulin** [orientechnologies/orientdb#4497]
Consider this simple graph: 
V has nodes #20:0, #20:1 and #20:2
E has these connections
from #20:0 to #20:2 with w1 = 3 and w2 = 3
from #20:0 to #20:1 with w1 = 1 and w2 = 1
from #20:1 to #20:2 with w1 = 1, no w2 field
The result of SELECT dijkstra(#20:0, #20:2, 'w1') is [#20:0, #20:1, #20:2] which is the expected result because the total weight 1 + 1 = 2 is less than the direct connection from #20:0 to #20:2 with weight 3.

The result of SELECT dijkstra(#20:0, #20:2, 'w2') is [#20:0, #20:1, #20:2] which is wrong because the only connection from #20:0 to #20:2 following edges with a w2-field is the direct connection. Hence the result should be [#20:0, #20:2]

**Comment by luigidellaquila** [comment]
Hi Martin,

in current implementation, if an edge does not have a valid value on the weight property, then 0 is assigned by default.
I think it could be a good idea adding another parameter to the function for one of the following:
* default weight, to be assigned when property does not exist or
* boolean flag to ignore edges where the property does not exist

WDYT

Luigi

**Comment by mbhulin** [comment]
Hi Luigi,
both suggested solutions can solve the problem. Personally I prefer the second one but of course you can get the same result with the first solution by setting the default value to Float.MAX_VALUE.

However I'm still not completely satisfied. An application might use different subclasses of E as edges with the same weight field. I suggest another parameter with the edge type. If this parameter is set only edges of this class are considered. Of course you could avoid this problem by different names for the edge classes e. g. distance1 and distance2 instead of distance. However such a work around might decrease readability.

I have reimplemented the dijkstra algorithm of OrientDB with few changes in my client program:
- additional parameter edgeType: only edges of this subtype of E are considered
- Only edges with the weight field are considered for the best path
- The output of my dijkstra function is not only the list of vertices but also the weight of the path and the list of edges. This is relevant if you may have more than one edge between two verteces e. g. two different streets between two cross points. Then you want to know which of the streets is on the optimal path.

Are you interested in my version? However the last change is not suitable for the dijkstra function in SQL because in SQL you only want to get one result (i. e. the list of vertices) not a structured result with a list of vertices, a list of edges and a float value. Perhaps OrientDB could offer a method
vertex.dijkstra (target, edgeType, weightField, direction, weightFieldMandatory)
which returns a structure with the vertex path, the edge path and the sum of weights on the optimal  path.

What is your opinion?

Thanks
Martin

**Comment by luigidellaquila** [comment]
Hi Martin,

yes, I'm very interested in this, maybe we could create another function (eg. dijkstra2) with your logic and leave the old one with the current implementation.

**Comment by mbhulin** [comment]
Hi Luigi,
in the documentation I found the possibility to create custom functions in Java and include them in OrientDB as plugins. I will send you the code of my plugin as e-mail attachment with coments where I changed the original code.

If OrientDB could offer a function dijkstra2 it would be very good for the tutorial and the statement: "With OrientDB you do not need to implement a lot of graph functions because they are already included in OrientDB." However you must be careful not to have an extra version for every user who asks for special functionality ending up in a bunch of functions dijkstra2, dijkstra3, dijkstra4, ...

**Comment by mbhulin** [comment]
Hi Luigi,
I provided a new version of the Dijkstra algorithm ``dijkstra2()`` which is quite similar to ``dijkstra()`` because it also returns the path as a list of vertices: see pull request #4694

**Comment by luigidellaquila** [comment]
Hi Martin,

Thanks a lot! We will review it in next days, now we are very close to
releasing 2.1 and we are all focused on that.

Thanks

Luigi


2015-08-05 10:54 GMT+02:00 Martin Hulin <notifications@github.com>:

**Comment by luigidellaquila** [comment]
Hi @mbhulin 

Thank you very much, we finally decided to merge A* and Dijkstra implementations in a single implementation.
I'm closing this issue 

Thanks

Luigi
