### ISSUE TITLE
SQL Engine accepts unclosed query

### ISSUE THREAD

**Issue by guglielmomoretti** [orientechnologies/orientdb#4499]
Sorry for posting again.

I'm still using OrientDB 2.0.11

```sql
select from (traverse loc,dev,code from (select from TransitsYear where year = 2016) where $depth >=3
```

As you can see the query misses the closed parentheses from the "traverse" statement.
No Errors are thrown and no results.

If I close the parentheses, then all it's working properly.

Regards,
Guglielmo

**Comment by lvca** [comment]
We fixed this in 2.1 with the new parser.
