### ISSUE TITLE
shortestPath does not work in 2.0.12

### ISSUE THREAD

**Issue by mkalus** [orientechnologies/orientdb#4501]
The following code worked in 2.0.10, but does not work on 2.0.12 any more:

    create vertex
    create vertex
    create edge from #9:0 to #9:1
    select shortestPath(#9:0,#9:1,OUT)

Produces correct list in 2.0.10, empty list in 2.0.12.

**Comment by StarpTech** [comment]
@luigidellaquila this ticket and some other leads me to the question does exists any unit tests for all changes to the parser or in general? The code coverage in orientdb is very considerable I use orientdb in production and I hear always something about parsing errors or issues but which works in the previous version and so on.

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

this particular problem is not related to the parser, but yes, there are thousands of unit tests in OrientDB test suite (~3000 as far as I can remember) and they increase daily.
Unfortunately unit tests cannot cover all the cases, so we will always have some regressions. This particular case is significant, there is a OSQLFunctionShortestPathTest that tests this but it does not cover this particular case.

Every time a user reports a problem, we add a new test case to the suite and then we fix the problem itself. 
One of the best contributions/pull requests we can have is a simple test case on a broken feature, so we strongly encourage anyone who want to contribute to provide meaningful test cases!

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed and added a new test on this specific use case (brach 2.0.x).
In develop branch this problem is not reproducible.

Thanks for reporting

**Comment by StarpTech** [comment]
Thanks for the precise answer.

**Comment by mkalus** [comment]
Thanks, too.
