### ISSUE TITLE
Group by modified datetime and count records

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4506]
OrientDb: 2.0.10
Studio

Is there a better way to `group by` all records by a datetime and count the records?

Don't works

```sql
select Created.format('yyyy-MM-dd') as cd from Node where SponsoredBy.Mid = '55965ccbd94706fc1e3f50c3' group by Created
```

But this works:

```sql
select count(*) from (select Created.format('yyyy-MM-dd') as cd from Node where SponsoredBy.Mid = '55965ccbd94706fc1e3f50c3') group by cd
```
Does exist any way without these extra step? I always think in big datasets.
These kind of querys can be optimized. What does make the new parser better?

**Comment by lvca** [comment]
Could you provide the explain output of the query:

    select Created.format('yyyy-MM-dd') as cd from Node where SponsoredBy.Mid = '55965ccbd94706fc1e3f50c3'
