### ISSUE TITLE
Can`t update datetime in studio

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4507]
Oriento: 2.0.11
![image](https://cloud.githubusercontent.com/assets/1764424/8500247/94637c0c-219a-11e5-97fa-2d69f794a7d4.png)

**Comment by StarpTech** [comment]
Simliar issue here https://github.com/orientechnologies/orientdb-studio/issues/34

**Comment by maggiolo00** [comment]
hi @StarpTech 
how can i reproduce it?

**Comment by StarpTech** [comment]
Look at the picture above. Try to pick up a date in the studio and save. You can see the error also in the picture at the bottom.
