### ISSUE TITLE
Cannot get the specific field in query result of stored function.

### ISSUE THREAD

**Issue by jakerass** [orientechnologies/orientdb#4512]
Hi,
how can I can I get the field value of the sql query result in stored function?
My code is:

```js
var mydb = orient.getGraph();
var id;
var results;
try{
results= mydb.command("sql","select defaultLabel from Concept");

}catch(err){
  return err;  
}

return results[0].defaultLabel;
```
This returns empty.
I also tried to write: `return results[0].field("defaultLabel");`
This causes error.

How can I get query result to use further in the function body?

**Comment by nagarajasr** [comment]
try this:

```sql
return results[0].getProperty("defaultLabel");
```

**Comment by jakerass** [comment]
Thank you , it works

**Comment by jakerass** [comment]
Excuse me, if the property is out edge,how to get it's id and other fields?

var mydb = orient.getGraph();
var id;
var results;
try{
results= mydb.command("sql","select defaultLabel from Concept");

}catch(err){
  return err;  
}

return results[0].getProperty("out_group").id; --- returns empty

**Comment by jakerass** [comment]
The following post answers my question:
http://stackoverflow.com/questions/30476862/accessing-connected-vertices-in-orientdb-javascript-functions
Thank you.
