### ISSUE TITLE
caps matter in insert into index command

### ISSUE THREAD

**Issue by arisAlexis** [orientechnologies/orientdb#4513]
CREATE INDEX Activities_en FULLTEXT ENGINE LUCENE String,String,String METADATA {"analyzer":"org.apache.lucene.analysis.en.EnglishAnalyzer"}

INSERT INTO INDEX:Activities_en (key,rid) VALUES("a","b","c"],#9:0)

this does not run and produces error 
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error
on parsing command at position #0: Encountered " ":" ": "" at line 1, column 18.

Was expecting one of:
    <SELECT> ...
    <FROM> ...
    <CONTENT> ...
    <RETURN> ...
    "(" ...
    "cluster" ...
    "(" ...

while

INSERT INTO index:Activities_en (key,rid) VALUES("a","b","c"],#9:0)

this runs OK. The documentation also has it with caps.

confirmed on 2.1-rc4

**Comment by maggiolo00** [comment]
@arisAlexis 
Why do you want to use manual index?

**Comment by arisAlexis** [comment]
hi,
https://groups.google.com/forum/#!topic/orient-database/murrnfw_aZQ

basically I want an index for each supported language. Otherwise I could use a different analyzer each time I want to index something (that's also manual) and stuff everything in the same index.

**Comment by maggiolo00** [comment]
Lucene manual has not really been tested. Usually goes along with the class

this works
```
INSERT INTO INDEX:Activities_en (key,rid) VALUES(["a","b","c"],#9:0)
```
it misses a [
but the retrivial has some problem

I will try to make it support with manual index

**Comment by arisAlexis** [comment]
I haven't noticed the missing bracket but the bug is still there with the caps. 
If there is a bug posting for lucene manual index please post it here so I can follow it thanks.

Would be great if someone could choose the analyzer during indexing.

orientdb {db=exchange}> INSERT INTO INDEX:Activities_en (key,rid) VALUES(["a","b
","c"],#9:0)

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error
on parsing command at position #0: Encountered " ":" ": "" at line 1, column 18.

Was expecting one of:
    <SELECT> ...
    <FROM> ...
    <CONTENT> ...
    <RETURN> ...
    "(" ...
    "cluster" ...
    "(" ...


orientdb {db=exchange}> INSERT INTO index:Activities_en (key,rid) VALUES(["a","b
","c"],#9:0)

Inserted record '{rid:#9:0,key:[3]}' in 0.069000 sec(s).

orientdb {db=exchange}>

**Comment by maggiolo00** [comment]
It is not really a bug, it is a missing feature. Lucene indexes are based on class.
there is an open issue about that
https://github.com/orientechnologies/orientdb-lucene/issues/27
You can follow the development there
