### ISSUE TITLE
traverse * from $variable always returns empty result set in batch mode

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#4514]
We get no result when calling `TRAVERSE * FROM $v` in batch mode.

Using this script
```sql
CREATE DATABASE remote:localhost/test root root memory

script sql;
LET v1 = CREATE VERTEX V SET name = 1;
LET v2 = CREATE VERTEX V SET name = 2;
CREATE EDGE E FROM $v1 TO $v2;
TRAVERSE * FROM $v1;
end;
```
We get
```
Server side script executed in 0.011000 sec(s). Value returned is: []
```
Even when wrapping the variable in a select
```sql
TRAVERSE  * FROM (SELECT FROM $v1);
```
We get an empty result set.

But when using
```sql
TRAVERSE * FROM (SELECT FROM V WHERE name = 1);
```
We get the correct values.

Using develop branch (f6ef462)

**Comment by lvca** [comment]
What release? Please always tell us the release to speed up issue management. Did you try with last 2.1-rc5?

**Comment by red-0ne** [comment]
Using develop branch (f6ef462). You probably read the issue from mail, because I updated it right after.
