### ISSUE TITLE
Unique graph index does not work with class hierarchies when using moveToClass

### ISSUE THREAD

**Issue by jbkielis** [orientechnologies/orientdb#4515]
Unique indexes do not always work when dealing with sub-classes.  For example, if you have the following schema:  
* Friend (base class) - has property uid (long) with unique index
* User (sub class of Friend)

In a multi-threaded environment, if you create a Friend and then convert the Friend to a User using moveToClass, you will often wind up with duplicate Users that have the same uid property.

**Comment by luigidellaquila** [comment]
which OrientDB version?

**Comment by jbkielis** [comment]
2.1-rc5.   Thanks.

**Comment by lvca** [comment]
@jbkielis Please could you try with 2.1.2?
