### ISSUE TITLE
Distributed: improve tx management

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4519]
Transactions that involve shaded data, like in issue #3928, can't create correctly undo information in case of rollback. By a quick analysis the solution would be:
- move collecting  of data to restore form the tx leader to each node. This would reduce also the size of the message to exchange
- each node is responsible to gather the backup data before the tx is executed
- such information should stay in memory (like distributed locks). In case the message of TX_COMPLETED is not received or the tx leader node goes down, the transaction is undo locally.

In this way we have a better management of TX with:
- tx can be rollbacked even if the leader dies
- smaller tx payload messages = higher throughput
- in sharding (#3928) each node is responsible to update own records

**Comment by compensator** [comment]
When you say that all information should remain in memory, what is the behavior in the case that all host servers lose power or all host servers are rebooted hard (virtual or physical)?

**Comment by lvca** [comment]
@compensator In the case a server is down, the transaction is rollbacked on next restart.

**Comment by lvca** [comment]
Already in v2.2.0-rc1.
