### ISSUE TITLE
Select query with "=" in where clause gives different results than "in" clause even if the subquery returns exactly one record

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb#4530]
OrientDB version 2.1-rc4

I have the following data model:
Device and Rack are Vertices
DevicePlacedInRack is an Edge having a property called OccupiedBayNums EmbeddedList Integer.

Device --> DevicePlacedInRack --> Rack

The following query incorrectly returns zero records:

```sql

select from DevicePlacedInRack where in = (select @rid from Rack where ID=404)


0 item(s) found. Query executed in 0.242 sec(s).

```

If the = is changed to in clause, the correct results are displayed:

```sql
select from DevicePlacedInRack where in in (select @rid from Rack where ID=404)
----+--------+------------------+---------------+-----+--------
#   |@RID    |@CLASS            |OccupiedBayNums|in   |out
----+--------+------------------+---------------+-----+--------
0   |#27:19  |DevicePlacedInRack|[1]            |#37:1|#17:30
1   |#27:22  |DevicePlacedInRack|[2]            |#37:1|#17:33
2   |#27:261 |DevicePlacedInRack|[3]            |#37:1|#17:353
3   |#27:301 |DevicePlacedInRack|null           |#37:1|#17:417
4   |#27:4038|DevicePlacedInRack|[1]            |#37:1|#17:6358
5   |#27:4098|DevicePlacedInRack|[2]            |#37:1|#17:6442
----+--------+------------------+---------------+-----+--------

6 item(s) found. Query executed in 0.23 sec(s).

```

Note that there is only one record of Rack having ID=404:

```sql
orientdb {db=SRIMS}> select @rid from Rack where ID=404

----+------+-----
#   |@CLASS|rid
----+------+-----
0   |null  |#37:1
----+------+-----

1 item(s) found. Query executed in 0.005 sec(s).

```

```sql
select in from DevicePlacedInRack where in=#37:1

----+------+-----
#   |@CLASS|in
----+------+-----
0   |null  |#37:1
1   |null  |#37:1
2   |null  |#37:1
3   |null  |#37:1
4   |null  |#37:1
5   |null  |#37:1
----+------+-----

```
I am using OrientDB version 2.1-rc4

**Comment by luigidellaquila** [comment]
Hi @nagarajasr 

this is the expected behavior in OrientDB: the result of a subquery is a collection, so the right operator to use is IN.
The same is for graph traversal functions, like out(), in(), both() and so on, so a query like

```SQL
SELECT FROM V WHERE out() = #12:0
```
will return no results; the right query would be 

```SQL
SELECT FROM V WHERE out() IN #12:0
```

**Comment by nagarajasr** [comment]
@luigidellaquila see #4542 i think there might be a certain use case where the sub-query should in fact return a record (OIdentifiable?) instead of a record-set (List<OIdentifiable>), when the sub-query is using an aggregate function. 
this behaviour causes inserts from sub-queries using an aggregate function to give incorrect results.
WDYT?
