### ISSUE TITLE
Add support for server side gremling functions

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#4532]
Add support for gremlin functions, as today there is the support for groovy functions but from that is not possible to use specific gremlin operator like 'g.V'.

**Comment by tglman** [comment]
The implementation of this will fix: https://github.com/orientechnologies/orientdb/issues/3906

**Comment by charbp** [comment]
Update? Two years later, Enterprise 2.2.19 bug still there, restarting the server can cause an application to fail if you are unaware of the bug.  Is this problem at least well documented in the Orient site, especially under starting the server or using functions?  One more important point, if you call a function before a manual query, the workaround of manually calling query (from browse window in studio for example) no longer works. You have to restart the server and not call any function before you've forced the gremlin to load with a manual query. 
I asked about in stackoverflow, which downvoted and said ask here:
https://stackoverflow.com/questions/43901337/orient-functions-dont-work-unless-your-run-a-manual-query-first
I asked about in google group, but no reply
https://groups.google.com/forum/#!topic/orient-database/Kcb2MEK2NW4

**Comment by maggiolo00** [comment]
@charbp 
Btw this is not the ticket for your issue. This is for support of gremlin language as a possible target for functions

**Comment by maggiolo00** [comment]
I will check your problem of manually call a function

**Comment by maggiolo00** [comment]
@charbp 

how can i reproduce it?

**Comment by charbp** [comment]
This was for #3906, but said this tix would fix as side effect I guess.  This for example, using studio, but also for an application. If you have a database with a function saved and you restart the database and call the function first (with a REST call, or pressing 'Execute' in studio, it will not work. You need to make a query in browse first, like g.v('#rid').  Then the function will work. If however, you try the function first, the manual fix will not work, you then have to restart the server, and again, manually force gremlin to load by calling a function.  The error you see in the console when the function fails, is .out is not a function. That's the clue that gremlin didn't load.  Again, weirdly, when you create a fail condition by trying a function with .out first, then trying to do g.v('#somerid').out doesn't work even in the browse window, and as stated, you need to restart server.  This was observed in Enterprise 2.2.19

**Comment by jake-miles** [comment]
Dealing with the same issue. I see it's still open. Was it fixed in the update listed above? Is there a workaround that will run the `g.v()` workaround automatically on server startup? Or is the best solution running that in console.sh in a script that starts the orient server?
