### ISSUE TITLE
property's attribute "MAX" works wrong with date

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#4533]
hi I use OrientDB Server v2.0.12
attribute MAX doesn't constrain maximum date, but it constrain minimal date
I think you have problem with character ">" or "<" in your code

orientdb {db=test}> create class test extends V
Class created successfully. Total classes in database now: 16

orientdb {db=test}> create property test.pdate DATE
Property created successfully with id=1

orientdb {db=test}> __alter property test.pdate max 2015-07-08__
Property updated successfully

orientdb {db=test}> insert into test set pdate = '2015-07-01'
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: E
rror on execution of command: sql.insert into test set pdate = '2015-07-01'

Error: com.orientechnologies.orient.core.exception.OValidationException: The fie
ld 'test.pdate' contains the date Wed Jul 01 00:00:00 EEST 2015 which is after t
he last acceptable date (2015-07-08)

orientdb {db=test}> insert into test set pdate = '2015-07-25'
Inserted record 'test#14:1{pdate:Sat Jul 25 00:00:00 EEST 2015} v1' in 0,002000
sec(s).

**Comment by tglman** [comment]
this is already fixed in 2.1 here the relative test: https://github.com/orientechnologies/orientdb/blob/develop/core/src/test/java/com/orientechnologies/orient/core/record/impl/ODocumentValidationTest.java#L377

in which version do you have this problem?

**Comment by tglman** [comment]
closing it, because it's actually fixed, we may need to backport it.

**Comment by tglman** [comment]
closing it, because it's actually fixed, we may need to backport it.
