### ISSUE TITLE
addTemporaryVertex() stores Vertex persistently

### ISSUE THREAD

**Issue by mbhulin** [orientechnologies/orientdb#4534]
public OrientVertex addTemporaryVertex(String iClassName, Object... prop)
(Blueprints Extension) Creates a temporary vertex setting the initial field values. The vertex is not saved and the transaction is not started. (see Javadoc)

However there seems to be no difference between addVertex() and addTemporaryVertex(). The following program prints equal results for the volatile and the persistent Vertex.
```Java

public static void main(String[] args) {
		OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/MyTestDB", "admin", "admin");
		OrientGraph db = factory.getTx();

		Vertex volatileV = db.addTemporaryVertex(null, "myAttr", 2);
		System.out.println(volatileV);
		Vertex persistentV = db.addVertex (null, "myAttr", 2000);
		System.out.println(persistentV);
		db.commit();
		
		Iterable <Vertex> vi = db.command(new OSQLSynchQuery("SELECT FROM V WHERE myAttr = 2 or myAttr = 2000")).execute();
		for (Vertex v: vi) {
			System.out.print(v);
			System.out.print(" ");
			System.out.println(v.getProperty("myAttr"));
		}
		db.shutdown();
		factory.close();
	}
```
And this is the output:
v[#-1:-2]
v[#-1:-3]
v[#9:24] 2
v[#9:25] 2000
Before the commit both vertices are volatile. After the commit both vertices are persistent but only the second one should be.

**Comment by lvca** [comment]
The problem is in `System.out.println(volatileV);`: when toString() is called, the RID is computed by saving the record. Try to avoid the print.
