### ISSUE TITLE
Inconsistent fetchplan behaviour in binary protocol

### ISSUE THREAD

**Issue by dehbmarques** [orientechnologies/orientdb#4536]
Hi,

This query ```select from #9:0 fetchplan out_*:-2``` in the studio returns the vertex and ignores the ```out``` edges.
In the binary protocol it doesn't work, always returns all edges.
Using node.js, when the vertex have lot of edges the serialization slows down a lot.

**Comment by dehbmarques** [comment]
I forgot the version: OrientDb Community 2.0.12

**Comment by luigidellaquila** [comment]
@tglman I assigned it to you, but I don't know if it's actually a matter of binary protocol, in case just redirect it to me ;-)

**Comment by tglman** [comment]
this is a known bug, due to the binary serialization that doesn't support optional field, this will be solved in 3.0

**Comment by dehbmarques** [comment]
Are there any workarounds while this is not fixed?

Now I'm doing this ```expand(@this.exclude('out_Edges1', 'out_Edges2'))``` in every query that have a lot of edges.

**Comment by lvca** [comment]
@dehbmarques You found the workaround ;-) The problem with fetchplan is that the same syntax is used for 2 different things:
- HTTP/JSON protocol
- Binary protocol

In binary protocol the fetch-plan pre-loads records in the client's cache, but there is no the concept of changing documents. So using include/exclude today remains the best solution.

**Comment by dehbmarques** [comment]
@lvca thanks for the reply. I will also try using the HTTP protocol for some queries.

**Comment by Amberos** [comment]
This was closed without a comment. Was it fixed, or closed because there's a workaround?
