### ISSUE TITLE
2.1-rc3 i was able to corrupt the database very easily through studio

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#4539]
I was allowed to rename a Vertex Class with a name of its parent. Then I was getting overflow error with reason 505 if I remember correctly when I tried to rename other classes. Now it is to the point that I cannot even load the database through studio although some queries work through Java..

Please let me know how can I find logs or dump the database to find what happened..

I cannot even connect to the database

Disconnecting from the database [null]...OK
Connecting to database [remote:localhost/xxxxx] with user 'admin'...
Error: com.orientechnologies.common.exception.OException: Error on creation of shared resource

Error: com.orientechnologies.orient.core.exception.OConfigurationException: Super class 'InnerText' was declared in class 'FactInnerText' but was not found in schema. Remove the dependency or create the class to continue.

**Comment by retrography** [comment]
The bug is still there. I'm trapped.

**Comment by luigidellaquila** [comment]
Hi @retrography 

when you say "I'm trapped", do you mean that you still cannot access your corrupted database? Do you need help in fixing it?

**Comment by retrography** [comment]
Yes I am locked out and can't log in. I will try downgrading to the last
version, fix the database and then upgrade again. Is there any other trick
I can try?

**Comment by luigidellaquila** [comment]
Hi @retrography 

I guess that's the only thing you can try. 
If it doesn't work, you can try to send us the DB and we will see if something can be done at low level (if it's really important data)
