### ISSUE TITLE
2.1-rc5: BUG Moving vertices to previously abstract class loses all vertices

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#4540]
I had vertices of class B  children of abstract parent A

I run the following commands:
```sql
ALTER CLASS A ABSTRACT FALSE
MOVE VERTEX (SELECT FROM B) TO CLASS:A
```

and I lost all of verticies...

**Comment by lvca** [comment]
Where all the vertices are gone? Can you see them in cluster counting?

**Comment by zifnab87** [comment]
Both clusters source and destination are 0, I will check again if they are in V, but certainly the move doesn't work as expected. I did it twice and I will import the database again to see what is exactly happening. Then I can provide the dump that I am using so you can find why this is happening

**Comment by zifnab87** [comment]
Yeap they are lost entirely! Even from V.  At the same time I get in the console
2015-07-11 00:07:44:203 WARNI ->0:0:0:0:0:0:0:1: Command not found: GET.sqlProfiler/xxxxx [ONetworkProtocolHttpDb]
2015-07-11 00:08:38:014 WARNI ->0:0:0:0:0:0:0:1: Command not found: GET.sqlProfiler/xxxxx [ONetworkProtocolHttpDb]

**Comment by zifnab87** [comment]
@lvca @prjhub I created a fresh new database with just two classes A (abstract) and B and I have added one row in B. When I make A concrete and I move B to A, this single record is lost:

Here is the dump
https://www.dropbox.com/s/403orf6719lteiy/problem.export.gz?dl=0

**Comment by zifnab87** [comment]
@lvca were you able to replicate this problem with the dump I provided? Thanks

**Comment by lvca** [comment]
This problem should be resolved with 2.1.2. @zifnab87  Any chance to retry it with 2.1.2?

**Comment by zifnab87** [comment]
I could try at 2.2-alpha sometime this week .. do you prefer the specific version?

**Comment by zifnab87** [comment]
@lvca I tried with 2.2-alpha and it is still there.

**Comment by zifnab87** [comment]
@lvca I was able to replicate the issue in 2.1.2-community as well

**Comment by lvca** [comment]
Found the problem: the command begins a TX, but no commit is called. Your vertices are still there and if you do `commit`you should see your changes. I'm fixing this to auto commit if the command begun a TX.
