### ISSUE TITLE
Add the ability to create a ordered property through sql

### ISSUE THREAD

**Issue by dehbmarques** [orientechnologies/orientdb#4541]
Hi,

Like we do using the JAVA API: ```person.createEdgeProperty(Direction.OUT, "Photos").setOrdered(true);```

**Comment by nagarajasr** [comment]
This is already supported, use this syntax:

```sql
create property out_Photos LINKBAG
alter property User.out_Photos custom ordered=true
```

give it a try and let me know how it goes

**Comment by dehbmarques** [comment]
The command worked, the property out_Photos became a ORecordLazyList.

But then I tried to create an edge and got this error:
```java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.ORecordLazyList cannot be cast to com.orientechnologies.orient.core.db.record.ridbag.ORidBag```

**Comment by lvca** [comment]
Try with:
```sql
create property out_Photos LINKLIST
alter property User.out_Photos custom ordered=true
```

**Comment by dehbmarques** [comment]
Thanks, it worked
