### ISSUE TITLE
Insert from select with an aggregate function not working

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4542]
Hi,

I'm trying to do an insert from select with an aggregate function, but with no success.

I tried this 3 options:

INSERT INTO MaxIDs FROM (SELECT 'Feed', Max(FeedId) FROM Feed)
[ERROR: Cannot find a command executor for the command request: sql.( SELECT 'Feed', Max(FeedId) FROM Feed)]

INSERT INTO MaxIDs SET TableName = 'Feed', MaxId = (select Max(FeedId) FROM Feed)
[The item is inserted, but not the value of the aggregate function]

CREATE VERTEX MaxIDs SET TableName = 'Feed', MaxId = (select Max(FeedId) FROM Feed)
[The item is inserted, but not the value of the aggregate function]

OBSERVATION:
select Max(FeedId) FROM Feed

returns:
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "Max": 1262695
        }
    ],
    "notification": "Query executed in 34.971 sec. Returned 1 record(s)"
}

Do you know any way to do it?

Thank You,Thiago

**Comment by nagarajasr** [comment]
What is the version of OrientDB?
seems to work for me in OrientDB-2.1-rc5:

```sql
insert into testclass set feed='Feed', maxid=(select max(ID) from Rack)

Inserted record 'testclass#65:5{feed:Feed,maxid:[1]} v1' in 0.447000 sec(s).

orientdb {db=SRIMS}> select from #65:5

----+-----+---------+----+-----
#   |@RID |@CLASS   |feed|maxid
----+-----+---------+----+-----
0   |#65:5|testclass|Feed|[1]
----+-----+---------+----+-----

1 item(s) found. Query executed in 0.01 sec(s).


```

**Comment by nagarajasr** [comment]
Ok, i think i know what's probably going on... what is the data type of maxid in your maxids class? 
in my example i had not defined maxid as a schemafull property. The subquery returns a "set", so the field maxid gets created as a list. when i explicitly created a property maxid of type integer, the insert fails to set the value correctly.

see #4530 where it is explained that sub-queries always return a set (though in this case, aggregate function returns exactly one row)

given this behaviour of sub-queries, i don't see any way to do what you want in a single sql statement.

**Comment by nagarajasr** [comment]
You may be able to use the below query as a workaround:

```sql
insert into MaxIDs select max(FeedID) as maxid, 'feed' as TableName from Feed
```sql

**Comment by lvca** [comment]
Try without parenthesis:

    INSERT INTO MaxIDs FROM SELECT 'Feed', Max(FeedId) FROM Feed

**Comment by thiagopm** [comment]
Hi @nagarajasr, we are using 2.1 rc4 and MaxID property is typed as integer.

This Worked:
INSERT INTO MaxIDs FROM SELECT 'Feed', Max(FeedId) FROM Feed

This not:
insert into MaxIDs select max(FeedID) as maxid, 'feed' as TableName from Feed

I think it's a bit strange, but my problem was solved with this workaroud.

Thanks a lot,
Thiago

**Comment by lvca** [comment]
@thiagopm the right syntax is `INSERT ... FROM <query>`

**Comment by thiagopm** [comment]
Yes @lvca...

It worked... 

Thank you
