### ISSUE TITLE
Node.js link from Doc "Introduction" page points to deprecated node library

### ISSUE THREAD

**Issue by newtmitch** [orientechnologies/orientdb#4543]
The "NodeJS" link on the intro page here: http://orientdb.com/docs/last/index.html points to Oriento, which is marked as deprecated, which then points to what appears to be the official Orient.js project on GitHub. Not sure if this is intentional.

**Comment by luigidellaquila** [comment]
Thanks for reporting, I just fixed it. Updated docs version will be available in short
