### ISSUE TITLE
Dijkstras() function and feature of including/excluding vertices/edges

### ISSUE THREAD

**Issue by Unduli** [orientechnologies/orientdb#4548]
Just like approved shortestPaths() function, a Dijkstras() (or cheapestPaths() ?) function that returns multiple number of cheapest paths specified with `limit` would be nice.

Beside that, an added feature to current shortestPath and Dijkstra functions allowing you to make some vertices/edges mandatory (including/excluding) preferably with option to specify as "in specified order" if needed would be nice. 

In a route planning scenario ( cheapest/shortest path from 
A -> B -> C -> D -> E or 
A -> B/C/D -> B/C/D -> B/C/D -> B/C/D -> E ) , that would be quite useful.

**Comment by luigidellaquila** [comment]
This is now possible in v 2.2 using `astar()` function.
I'm closing this issue

Thanks

Luigi
