### ISSUE TITLE
Use of ORecordAbstract.getDatabaseIfDefined() lead to unpredictable errors

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4549]
Guys,

There are several places where getDatabaseIfDefined() has been used and some of them might lead to unpredictable errors. For example:

1) Why ODocument.getSchemaClass() returns null if database was previously closed and not yet initialized?
2) Why OrientEdgeIterator.createGraphElement() creates nothing if db was not recieved from ODatabaseRecordThreadLocal.INSTANCE previously?

I understand that there might be some places where initialization of DB will be so heavy and quite redundant. But even in these cases some workaround might be used.

1) ODocument.toString() is trying to get immutableSchemaClass just to print schemaClass, but there is already String _className: so no need explicitly get ImmutableSchemaClass

Can you please review usage of getDatabaseIfDefined() and consider switching to getDatabase() in cases when **"some DB entity where requested and DB is required to provide proper response"**

**Comment by lvca** [comment]
@PhantomYdn About 2) you're right, I'm fixing it. About 1) ODocument could be used even without a database. That's the reason.

**Comment by PhantomYdn** [comment]
@lvca, but 1 without db doesn't make sense: it will return null and that null can lead to subsequent problems... so users have to call getDatabase() prior to this method to be sure, that NPE will not happen in their code.

**Comment by lvca** [comment]
We use ODocument for many purposes. For example we manage the distributed cfg between servers, but it's just JSON and it doesn't need db/class.

**Comment by PhantomYdn** [comment]
I see. If case when return null instead of class is OK for some conditions - I'm good. Thanks!

**Comment by lvca** [comment]
@PhantomYdn Thanks anyway for pointing on such things. Some OrientDB pieces are quite old and a rework could be needed ;-)
