### ISSUE TITLE
About DB integrity [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#455]
This is [Issue 455](http://code.google.com/p/orient/issues/detail?id=455) moved from a Google Code project.
Added by 2011-06-22T05:02:42.000Z by [evgs...@gmail.com](http://code.google.com/u/115102822297207204554/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v2.1

### Original description

    Hi Luca,
    I care about db integrity, escpecially about lost links.
    We can save any link (#x:y) to any place. OrientDB does not care if address exists now.
    It would be nice if OrientDB has mode which supports integrity.
    I offer to have one global index (references) which contains master and details links.
    Now before saving of record is necessary 
    1. Collect all links which records has
    2. Check if all are exist
    3. Update index:references for this record
    
    It is not necessary to care which field has link to master record. It is enough just to know that link exists
    
    Before record deleting we can check if index:references has links to this record
    
    Example 
    
    create class A;
    insert into A (f) values ('Rec1'); // #5:1
    insert into A (f) values ('Rec2'); // #5:2
    insert into A (f) values ('Rec3'); // #5:3
    
    create class B;
    insert into B (f,A) values (1,#5:1); // #6:1
    // Need to check if #5:1 exists
    // insert into index:references (key,rid) values (#5:1,#6:1)
    
    insert into B (f,A,A1) values (1,#5:1,#5:2); // #6:2
    // Need to check if #5:1 and #5:2 exist
    // insert into index:references (key,rid) values (#5:1,#6:2)
    // insert into index:references (key,rid) values (#5:2,#6:2)
    
    delete from A where f like &quot;Rec%&quot;
    // Collect RIDs of records which should be deleted (#5:1,#5:2,#5:3)
    // select from index:references where key in (#5:1,#5:2,#5:3)
    // now if selection from references does not contains any records we can realize deteting
    
    So it is possible to support DB integrity without schema.
    
    Evgeny 
    
    P.S.
    This is can be more complicated if remember that indexes do have links too.
    Also as I have read OrientDB will support version of records.

**Comment by lvca** [comment]
This is not needed anymore if you use graph api.

**Comment by PhantomYdn** [comment]
If somebody needed there is the following implementation of a hook for consistency support without graph api: https://github.com/OrienteerDW/Orienteer/blob/master/orienteer-core/src/main/java/org/orienteer/core/hook/ReferencesConsistencyHook.java

**Comment by smolinari** [comment]
Thanks Ilia @PhantomYdn. 

How would that work out on performance? 

Scott

**Comment by PhantomYdn** [comment]
Optimized, but still might be not ideal.
