### ISSUE TITLE
2.1rc5 BUG - I was able to rename an edge class "something UNSAFE"!

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#4553]
I was trying to rename an edge class from one name to a new one. It was telling me to use UNSAFE since this could break Verticies.. Even though I don't understand why this would be a problem.. So I did the same query with UNSAFE at the end ALTER CLASS <class> <attribute-name> <attribute-value> UNSAFE and it allowed me - I thought it worked but it added UNSAFE in the name of the class :/

I start wondering if I can trust this product ...
![image](https://cloud.githubusercontent.com/assets/526062/8635893/b9b7ed98-280d-11e5-8a17-88d93a970539.png)

```ALTER CLASS <class> <attribute-name> <attribute-value> UNSAFE```

Now I cannot rename it because class has an unexpected attribute UNSAFE :/
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position # 26: Unknown class's attribute 'UNSAFE'. Supported attributes are: [NAME, SHORTNAME, SUPERCLASS, SUPERCLASSES, OVERSIZE, STRICTMODE, ADDCLUSTER, REMOVECLUSTER, CUSTOM, ABSTRACT, CLUSTERSELECTION] Command: alter class ContainsEntity UNSAFE name ContainsEntity ----------------------------------^

**Comment by lvca** [comment]
Did you put UNSAFE in " or ' ?

**Comment by zifnab87** [comment]
The command was ```ALTER CLASS OldName NAME ContainsEntity UNSAFE```
according to ```ALTER CLASS <class> <attribute-name> <attribute-value> UNSAFE``` that I think I found somewhere. It could just be that there is no check about spaces in names for classes

**Comment by luigidellaquila** [comment]
Hi @zifnab87 
I need your help here, I'm trying to reproduce this problem from Studio, but it seems I can't.
Could you please add some details?

**Comment by luigidellaquila** [comment]
Ah, ok, I found out why. It was a regression, was fixed six days ago, see commit 26f0f55
There is also a test case on this.

Thanks
