### ISSUE TITLE
remove embeddedlist item by reference is broken - version 2.0.12

### ISSUE THREAD

**Issue by seeden** [orientechnologies/orientdb#4554]
Hi

I am not able to remove item from embeddedlist with defined schema.
If I will try to use for example:
```js
update #12:34 remove images {
        "@type": "document",
        "@class": "AlbumAImages",
        "size": 102250,
        "created": "2015-07-12 17:44:26",
        "type": "image/jpeg",
        "key": "car/#20:28/3ea19617aaae-e95a-1d84-2c52-75c315d0-3tv4zc516ef4kc70v2g320ci"
}
```
it will remove always remove first item from the list(it is wrong behavior)
I tried (without any success) those commands
```js
update #12:34 remove images 1
update #12:34 remove images.1
update #12:34 remove images[1]
```

Is there any other options or is this command broken?

orientdb version 2.0.12

**Comment by luigidellaquila** [comment]
Hi @seeden 

the right syntax is the following:

```sql
update #12:34 remove images = images[1]
```

or 

```sql
update #12:34 remove images = images[type="image/jpeg"]
```

**Comment by seeden** [comment]
Thanks @luigidellaquila for information. I guess that the good idea is to update oriendb documentation with small example for others developers

**Comment by luigidellaquila** [comment]
+1
reopening to update docs (of course any PR on docs will be very appreciated ;-) )

Thanks

**Comment by luigidellaquila** [comment]
docs updated
