### ISSUE TITLE
2.1rc5 - getIndices() and getIndex() return empty/null

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#4555]
I am trying to remove deprecated ```getVertexByKey``` method from my code but getIndex and getIndices are returning null...

I am using tinkerpop blueprints 2.6.0

```java
public class IndexRetrivalNewVsOld {
	public static void main(String args[]){
		OrientGraph graph = new OrientGraph(ConnectionStrings.dbConnection);
		Vertex v = graph.getVertexByKey("Entity.uuid", "e8d09fef-a7dd-47a0-9463-9f7b46cd6672");
		System.out.println("Vertex: " +v);
		Index<Vertex> index= graph.getIndex("Entity.uuid",Vertex.class);
		System.out.println("Entity.uuid: "+index);
		System.out.println(graph.getIndices());
		System.out.println(graph.getIndexedKeys(Vertex.class));
	}
}
```
```
Jul 12, 2015 2:06:43 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=7,419MB (heap=2,706MB os=12,173MB disk=33,720MB)
Vertex: v(Entity)[#12:2]
Entity.uuid: null
[]
[date, number, creator, created, real, text, uuid, hash, url, isOfTypeCount, username]
```

**Comment by luigidellaquila** [comment]
Hi @zifnab87 

did you manually create the index named "Entity.uuid"? It is not automatically created by the APIs.
You can check from Studio if it exists (and if other indexes are defined on V class)

**Comment by nagarajasr** [comment]
it is certainly strange by itself that the 2 APIs are returning inconsistent results

```java
System.out.println(graph.getIndices());
System.out.println(graph.getIndexedKeys(Vertex.class));
```

return different results.

**Comment by luigidellaquila** [comment]
yes, I agree, I'm adding a test case about it right now, but having the exact situation where the problem happens is always a help ;-)

**Comment by luigidellaquila** [comment]
Hi @zifnab87 

there is some confusion here (and TinkerPop is not helping a lot on this): getIndices() is an API of IndexableGraph, that is an interface intended for manual indexing (see Javadoc http://www.tinkerpop.com/docs/javadocs/blueprints/2.6.0/com/tinkerpop/blueprints/IndexableGraph.html)
This means that the list of indices returned by that method is contains only manual indices, created with 
graph.createIndex("indexName", Vertex.class).
This kind of indices is not automatically managed by the storage, that means that you have to explicitly put vertices or edges into them

On the other side getIndexedKeys() is an API of  KeyIndexableGraph (http://www.tinkerpop.com/docs/javadocs/blueprints/2.6.0/com/tinkerpop/blueprints/KeyIndexableGraph.html) that is intended for automatic indexing.

This is why you are having different results from the two calls.

**Comment by zifnab87** [comment]
@luigidellaquila I created those indices in Studio of course - assuming that Studio is creating them manually!
