### ISSUE TITLE
JMX Bean: OPair class is not serializable

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4557]
The new JMX Bean if used remotely provide this exception:
```
WARNING: Error getting attributes: error unmarshalling return; nested exception is: java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage WARNING: Error getting attributes: error unmarshalling return; nested exception is: java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: com.orientechnologies.common.util.OPair
```

Seems the class OPair is not serializable.

**Comment by laa** [comment]
We do not use OPair in storage JMX beans, but I think or OPair is used in profiler, does not it ?

**Comment by laa** [comment]
Yes, I found it com.orientechnologies.common.profiler.OAbstractProfiler#getMetadata .

**Comment by laa** [comment]
The only thing which we need is to implement serializable interface. Of course key and value should be serializable too ))
