### ISSUE TITLE
Expose configuration for plugins directory

### ISSUE THREAD

**Issue by jdillon** [orientechnologies/orientdb#4558]
ATM the `plugins` directory is hard coded to:

```
private void updatePlugins() {
    final File pluginsDirectory = new File(OSystemVariableResolver.resolveSystemVariables("${ORIENTDB_HOME}", ".") + "/plugins/");
```

I'd like to be able to define a property in the server configuration to specify the location of this instead.

Should help with embedding where the runtime environment is different from the shrink-wrap distribution.

**Comment by jdillon** [comment]
It would also be kinda nice if you could install a plugin from a URL, so we can embed a plugin into an OSGI bundle and then install it based on the resource url?  And avoid the entire plugins/ directory completely?

**Comment by lvca** [comment]
- Exposed Plugin Manager instance in OServer class
- new "plugin.loadAtStartup" to decide if load plugins at startup
- new "plugin.directory" settings to assign a different directory
