### ISSUE TITLE
Eval function does not pass field value to functions with multiple arguments

### ISSUE THREAD

**Issue by mourednik** [orientechnologies/orientdb#4559]
The following occurs with a document database, on 2.1-rc5.

```
create class test
insert into test(counter) values (1)

-- Correct results
select counter from test
-- result = 1
select min(counter, 2) from test
-- result = 1
select max(counter, 0) from test
-- result = 1
select eval('counter') from test
-- result = 1

-- Incorrect results when using the eval function with multiple argument functions
select eval('min(counter, 2)') from test
-- result = 2
select eval('max(counter, 0)') from test
-- result = 0
```

**Comment by nagarajasr** [comment]
wrong usage... don't quote the expression, use this and it works..

```sql
select eval(max(counter, 0)) from test
select eval(min(counter, 2)) from test
```

**Comment by mourednik** [comment]
That is the correct usage according to the documentation. Note that the following throws a NullPointerException. 
```
select eval(1 * 10) from test
```
But it works when quoted with single quotes.

Also this is broken.. 
```
select eval(max(counter, 0) * 10) from test
-- result = 1. Should be 10
```

**Comment by nagarajasr** [comment]
indeed, this seems to be an inconsistency that leads to incorrect results in certain cases. 
you may be able to use the below as a workaround:

select eval('10 * max') from (select max from (select max(counter,0) from test))

@lvca i still think this is a bug

**Comment by mourednik** [comment]
Unfortunately that workaround won't work in an UPDATE statement, which is where I need to do the evaluation.

**Comment by lvca** [comment]
This is a problem of visibility of variables. Try using `$current.max` instead of `max`

**Comment by obi1kenobi** [comment]
I would love to see this fixed soon -- it's possibly related to some of the issues I reported recently, like #6604 or #6606.
