### ISSUE TITLE
Calling print('something') from a javascript function has wrong output

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#4560]
The print function does not have the desired behaviour.  Here is what I get.
```
orientdb> create database remote:localhost/test root root memory

Creating database [remote:localhost/test] using the storage type [memory]...
Connecting to database [remote:localhost/test] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost/test
orientdb {db=test}> CREATE FUNCTION printSomething "print('Hello');" LANGUAGE Javascript

Function created successfully with id=#6:0

orientdb {db=test}> SELECT printSomething()

----+------
#   |@CLASS
----+------
0   |null
----+------

1 item(s) found. Query executed in 0.028 sec(s).
```

Using develop branch (48f7c7e)

**Comment by nagarajasr** [comment]
use java.System.out.println('hello, world') to print to stdout in a javascript function.

**Comment by red-0ne** [comment]
Is this how it is supposed to be used?
```
orientdb> create database remote:localhost/test root root memory

Creating database [remote:localhost/test] using the storage type [memory]...
Connecting to database [remote:localhost/test] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost/test
orientdb {db=test}> CREATE FUNCTION printSomething "java.System.out.println('hello, world')" LANGUAGE Javascript

Function created successfully with id=#6:0

orientdb {db=test}> SELECT printSomething()

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select printSomething()

Error: java.lang.RuntimeException: java.lang.ClassNotFoundException: java.System.out.println

Error: java.lang.ClassNotFoundException: java.System.out.println
```

**Comment by nagarajasr** [comment]
Sorry, my bad. the correct syntax is:

```java
java.lang.System.out.println("hello, world!");
```

**Comment by red-0ne** [comment]
Sorry but still no `hello, world!` printed. I get the same output as my original post:
```
----+------
#   |@CLASS
----+------
0   |null
----+------
```

**Comment by nagarajasr** [comment]
have you checked the server log?

**Comment by red-0ne** [comment]
Thank you! It is indeed printed in the server log. But shouldn't it be printed in console? Also, using simple `print('hello, world!')` outputs in server log.

**Comment by red-0ne** [comment]
So either the `print` function has to print output into console or this section of documentation has to be updated http://orientdb.com/docs/last/Dynamic-Hooks.html#class-level-hooks

**Comment by nagarajasr** [comment]
I am inclined to agree that indeed the documentation seems to suggest the 'print' command outputs to the orientDB console whereas in fact it outputs to the server's console
@red-0ne How about submitting a pull request to update the documentation?

**Comment by red-0ne** [comment]
Ok, I'll submit a PR

**Comment by nagarajasr** [comment]
merged, thanks!

**Comment by lvca** [comment]
Actually if you're connected with non-remote the output is in the console because it's the JVM where the JS is executed. But if it's executed on the server, the output will be on the server. If you want to return something in the console, ty returning it:

```
print('Hello!);
return "Hello!";
```
