### ISSUE TITLE
Fulltext Indexes are not involved in order by

### ISSUE THREAD

**Issue by AlessioDeAngelis** [orientechnologies/orientdb#4561]
Hello,
I noted that the fulltext indexes are not involved in order by. Infact the explain fields "indexIsUsedInOrderBy" and "fullySortedByIndex" are false when only the fulltext index is involved, resulting in slower queries.
This behaviour is shown by sbtree fulltext as well as by lucene one.
Thanks,
Alessio

**Comment by maggiolo00** [comment]
hi @AlessioDeAngelis 
can you provide some example?

**Comment by maggiolo00** [comment]
Hi @AlessioDeAngelis 
order by on fulltext index is not supported as the value in sbtree or lucene is
tokenized
