### ISSUE TITLE
groovy g.command not updating manual fulltext index

### ISSUE THREAD

**Issue by kstock** [orientechnologies/orientdb#4564]
I have noticed this in 2.0.12

When I try to update a manual fulltext index inside a server function using 
```
g=orient.getGraph()

g.command("sql", "insert into index:test (key, rid) VALUES (\"foo\", #9:1)")

g.command("sql", "insert into index:test (key, rid) VALUES (\"foo\", #9:2)")
```

only the first (key, rid) pair will end up in the index.

If I use the sql, 
```
insert into index:test (key, rid) VALUES ("foo", #9:1))
insert into index:test (key, rid) VALUES ("foo", #9:2))
```
then both end up in the index.

STEPS TO REPRODUCE
----

1) create database, populate a little bit 
```
//i used this in a groovy server-function for population
g=orient.getGraph()
(0..10).each{ g.addVertex(["uid":it])}
```
2) create a manual fulltext index
```
create index test fulltext string
```
3)  create a groovy server side function
```
g=orient.getGraph()
g.command("sql", "insert into index:test (key, rid) VALUES (\"foo\", #9:1)")
g.command("sql", "insert into index:test (key, rid) VALUES (\"foo\", #9:2)")
```

4) search the index
```
select from index:test where key = "foo"
```
I am only seeing 1 entry here

5) execute the sql 
`insert into index:test (key, rid) VALUES ("foo", #9:2)`

4) search the index
`select from index:test where key = "foo"`

I now see both entries

EXPECTED BEHAVIOR
----
I expect multiple calls to 
g.command("sql", "insert into index:test (key, rid) VALUES (\"foo\", rid)")
to have the same effect as multiple direct sql calls.

That is, the g.command form should update the index more than once.

**Comment by maggiolo00** [comment]
hi @kstock 
i've tried it with 2.0.14 and 2.1.2 and it is fixed.
