### ISSUE TITLE
Redundant version check

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4566]
Guys,

There are the following lines of code in OServerCommandPutDocument

```java
if (currentDocument.isDirty()) {
        currentDocument.getRecordVersion().copyFrom(doc.getRecordVersion());
        currentDocument.save();
      }
```

As a result, to avoid exceptions request must contain `@version`. I think it's redundant: especially in case of partial update... Keeping of version number on client side is quite strange requirement for this API.

P.S. I'm sure that the same logic might be for another REST APIs... Please review requirements for `@version` specification in REST API.

**Comment by lvca** [comment]
In case of `partialUpdateMode` I agree this has not much sense. About the rest, if you provide the version it should be checked. This allows the user to manage MVCC correctly.

**Comment by lvca** [comment]
I think this is more appropriate:

```java
 if (doc.getRecordVersion().isValid())
          // OVERWRITE THE VERSION
          currentDocument.getRecordVersion().copyFrom(doc.getRecordVersion());
```

**Comment by PhantomYdn** [comment]
This fix is also incorrect:( If version was not specified it's equal to 0. And 0 is a valid version number. But specifing @version: -1 every time is also redundant, isn't it?

**Comment by lvca** [comment]
If you don't set any "@version" field the last version is taken, because it's loaded from disk.

**Comment by PhantomYdn** [comment]
I meant something another. When you send PUT update by json and without '@version' - default version of a created ODocument from that JSON will be zero. And once 0 is a valid version number - OrientDB will fail to set version 0 to existing document.
It's tested and it's failing (if version was not set). I can't send a testcase: it's build on wicket - so it will be hard for to reproduce, but its logic is sime: send PUT update without version to existing document.

**Comment by lvca** [comment]
Fixed. Created also the test case: f5797fd9219d282d40ef73cd1ab485cde5c00f53
