### ISSUE TITLE
Index: parallel rebuild + no WAL

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4568]
We could rebuild indexes concurrently by reducing the startup time in case of database crash. Actually the index speed is about 20k recs/sec. Rebuilding multiple indexes I think we could reach also 100k recs/sec.

Furthermore with now the index rebuild uses the WAL, but has not so much sense: the index rebuild is not able to re-start from the point where it has been stopped. So disabling the WAL I saw peek of 50k recs/sec.

Parallel rebulding of indexes + no WAL we could reach 200k recs/sec.

This is fundamental because drastically reduce the recover time of a node when restarts.

**Comment by lvca** [comment]
Moved to 2.2.

**Comment by laa** [comment]
Moved to next version

**Comment by laa** [comment]
I do not think that parallel index rebuild will improve something , of course if we work in all in memory solution it will improve speed but  for solutions where almost all data are contained on disk it will generate so enormous disk random io traffic that  index rebuild will simply stuck. I will disable wal for such index rebuild and if you insist will create several index rebuild threads but imho I feel that it will be mistake for big data.

**Comment by lvca** [comment]
+1 to avoid parallel for now, the main point is to avoid WAL on index rebuild.

**Comment by laa** [comment]
Fixed

**Comment by lvca** [comment]
Great!
