### ISSUE TITLE
What's the Best way to create Idempotent script to DevOps?

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4570]
Hello,

We are trying to create a batch script to be used on our continuous integration (DevOps), but we 're having some problems because it should be idempotent. (we run the script every time our build runs)

We tried SQL batch command, but we didn't find how to do a conditional command like this:<br/>
teste.osql:
<code>
connect remote:localhost/ilang admin admin<br/>
if(exists(SELECT 1 FROM (select expand(classes) from metadata:schema) Where name = 'User'))<br/>
{<br/>
	create class User extends V<br/>
}
</code>

and running:<br/>
console.bat teste.osql

Thanks in advance,
Thiago

**Comment by lvca** [comment]
Look at: http://orientdb.com/docs/last/Console-Commands.html#batch-mode. You can do that by setting:
```
ignoreErrors true in console
```
to bypass errors.
