### ISSUE TITLE
Working with remote, blueprint methods should be consistent with transaction

### ISSUE THREAD

**Issue by fandji** [orientechnologies/orientdb#4571]
OrientDB 2.0.12

In the documentation, there is a part about transactions and breaking out of acid when working with remote. We assumed that when we don't explicitly execute commands, for example via graph.command, we are save to go.

As it is, this isn't the case. I tried to do some work with indexes, and had to found that internally, the index is backed by a remote query. As such, local changes aren't visible, and the functionality is greatly reduced.

What i would like to have is, that the blueprint methods are consistend with the transaction.

The least would be they are documented to behave otherwise, like it is done with the graph.command. Because else i have to investigated every operation i do with blueprint/gremlin if there is some hidden usage of the remote which isn't consistent with my transaction.

**Comment by lvca** [comment]
OrientDB works in this way with remote. Check the docs. However this enhancement will be addressed in 3.0.

**Comment by laa** [comment]
Assigned to @tglman that requires major remote storage refactoring

**Comment by lvca** [comment]
Already implemented in 3.0-M2
