### ISSUE TITLE
graph.getVertices("Customer.name", "Jay") should find indicies based on fields, not name

### ISSUE THREAD

**Issue by fandji** [orientechnologies/orientdb#4572]
OrientDB 2.0.12

The documentation about Using Indices doesn't specify that an Index must be named accordingly a specific naming schema, so that it is used by the query.

As an index contains the information, for which fields it is usable, the index should with this information. As such, a not so strict naming must be enforced for indicies.

**Comment by luigidellaquila** [comment]
Fixed in both 2.1.x and 2.2
