### ISSUE TITLE
graph.getVertices("Customer.name", "Jay") when no index falls back on V

### ISSUE THREAD

**Issue by fandji** [orientechnologies/orientdb#4573]
OrientDB 2.0.12
When doing a getVertices, for example graph.getVertices("Customer.name", "Jay"), and there is no index found, the provided ClassName is dismissed and the "equivalent" of graph.getVertices("name", "Jay") is executed.
The expectation ist, that only Vertices of the Class Customer are returned.

**Comment by maggiolo00** [comment]
hi @fandji 
has been fixed in 2.1.x and 2.2.x
https://github.com/orientechnologies/orientdb/issues/4973
