### ISSUE TITLE
Getting com.orientechnologies.orient.core.storage.ORecordDuplicatedException with version 2.0.12

### ISSUE THREAD

**Issue by Maheshkd** [orientechnologies/orientdb#4574]
We are getting following error  com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
--> com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #11:92518: found duplicated key '000002078505' in index 'INTERNALPERSON.Pplsoft_ID' previously assigned to the record #11:92517 RID=#11:92517 [ONetworkProtocolHttpDb]
2015-07-14 18:01:41:174 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
--> com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #19:2646: found duplicated key '503700' in index 'TEAM.Team_Id' previously assigned to the record #19:2645 RID=#19:2645 [ONetworkProtocolHttpDb]
2015-07-14 18:02:39:808 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
--> com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #11:92518: found duplicated key '000002078505' in index 'INTERNALPERSON.Pplsoft_ID' previously assigned to the record #11:92517 RID=#11:92517 [ONetworkProtocolHttpDb]
2015-07-14 18:17:58:527 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
--> com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #19:2646: found duplicated key '503700' in index 'TEAM.Team_Id' previously assigned to the record #19:2645 RID=#19:2645 [ONetworkProtocolHttpDb]
2015-07-14 18:17:59:902 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
--> com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #19:2646: found duplicated key '503700' in index 'TEAM.Team_Id' previously assigned to the record #19:2645 RID=#19:2645 [ONetworkProtocolHttpDb]
2015-07-14 18:18:01:227 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
--> com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #19:2646: found duplicated key '503700' in index 'TEAM.Team_Id' previously assigned to the record #19:2645 RID=#19:2645 [ONetworkProtocolHttpDb]

**Comment by lvca** [comment]
Do you know if the rebuilding of indexes has been interrupted?

**Comment by Maheshkd** [comment]
Not Sure Luca.  Yesterday Anurag discussed with you and restarted the databases and now when starting the HTTP real time updates we are getting this error.  Is there a way we can fix this without restarting the database or process.

Thanks,
Mahesh Damodaram
O:612.671.6018 M: 612.963.2914
Ameriprise Financial 707 2nd Avenue S, Minneapolis, MN 55474 | Routing: H12 Q29-A

Connect with us:
[Website]<http://www.ameriprise.com/>[Facebook]<http://www.facebook.com/ameriprise>[YouTube]<http://www.youtube.com/ameriprise>

[LOGO]<http://www.ameriprise.com/>

**Comment by lvca** [comment]
Try to execute this command on console connected to the master:

    rebuild index TEAM.Team_Id

**Comment by Maheshkd** [comment]
This seems to have resolved the issue for that flow now.

Thanks,
Mahesh Damodaram
O:612.671.6018 M: 612.963.2914
Ameriprise Financial 707 2nd Avenue S, Minneapolis, MN 55474 | Routing: H12 Q29-A

Connect with us:
[Website]<http://www.ameriprise.com/>[Facebook]<http://www.facebook.com/ameriprise>[YouTube]<http://www.youtube.com/ameriprise>

[LOGO]<http://www.ameriprise.com/>
