### ISSUE TITLE
Saner defaults for MAXDEPTH

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb#4577]
Currently the default value for maxDepth is set to -1 (or infinite). This can cause undesirable effect where any authenticated remote client can issue a traversal query (say via REST call) to walk the entire graph with a query like 'traverse any() from <somerid> limit -1'. This may in turn cause server overload and possible OOM errors.
Of course a rogue client could deliberately add MAXDEPTH -1 to the query and still cause the same effect. So to really prevent this from causing OOMs and overloading server, we should perhaps have some sort of maxdepth 'quota' that is configured at the user or role level. So only specific users who have the maxdepth unlimited privilege are allowed to walk the entire graph.

**Comment by lvca** [comment]
:+1:

**Comment by nagarajasr** [comment]
also to be handled in fetch plans in case of e.g., console command ``` 'load record <rid> *:-1' ``` this causes server side StackOverflowError. btw in case of this console command, the client never returns.

**Comment by lvca** [comment]
This could be implemented in the new query engine for v3.0.

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
