### ISSUE TITLE
sub-select with "not in" - unexpected behaviour

### ISSUE THREAD

**Issue by crmayer** [orientechnologies/orientdb#4579]
Run into problems formulating a more sophisticated query. Broke it finally down to:
 
Select from V where V.@rid not in (select @rid from V) limit 10
Query executed in 0.726 sec. Returned 10 record(s).

Is the assumption wrong that this query should return under any circumstances zero records ?
Or is the query somehow malformed?
Using OrientDB 2.0.12 Community Edition 

THNX

**Comment by luigidellaquila** [comment]
Hi @crmayer 

the right syntax is the following:
```sql
Select from V where @rid not in (select @rid from V) limit 10
```

in your query you are comparing the result of the subquery with the @rid of the field V of the class V

**Comment by crmayer** [comment]
Works (in terms that it doesn't return anything). So the difference is just in @rid vs. V.@rid. Still have to learn a lot - thought this to be semantically equivalent. 
Thank you.
(PS: we had a conference call today regarding consultancy ...  just to connect the dots)
