### ISSUE TITLE
Same issue on 2.1-SNAPHOST (https://github.com/orientechnologies/orientdb/issues/4453)

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4581]
Database cannot handle concurrent writing, only works on single thread writing.

**Comment by henryzhao81** [comment]
And this happened both on Http and Binary protocol

**Comment by laa** [comment]
Hi Henry,
Could you perform steps listed in https://github.com/orientechnologies/orientdb/issues/4527#issuecomment-122249935 ?

**Comment by laa** [comment]
Guys it is fixed long time ago I am closing this.
