### ISSUE TITLE
2.2-alpha - BUG: Deleting edge with missing vertices throws NullPointerException

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#4582]
Apparently I had a corrupt group of edges, that I was able to remove their `in` vertices.
The problem is that DELETE EDGE doesn't get rid of edges that have null start/end. For me the problem was in the destination vertices that I had removed them - I don't know what happens with missing starting vertices. 

So I don't know what is more favorable - a descriptive message or removing the edge regardless when it has missing start/end

**Comment by lvca** [comment]
I think removing the edge it's better managing this case. Do you have a complete log of this exception?

**Comment by zifnab87** [comment]
Sorry I was on vacation.. No I don't have a log of this exception since I cleaned up the data corruption

**Comment by lvca** [comment]
Ok, closing for now. In case you see the same error, please reopen it. THanks.
