### ISSUE TITLE
Fetch two vertices connected multi edges

### ISSUE THREAD

**Issue by nomi-ramzan** [orientechnologies/orientdb#4585]
I have this scenario

P(V)<--- S(E)----SL(V)
Here P and SL are vertices and S is edge. Now in result I want to fetch all attributes of P , S also with rids and selected attributes of SL. I was using fetchplan:in_S:2 but this is not working for me. I am using orientdb and orientJS(client).

right now my query is 
select @rid, @this.toJSON("fetchPlan:in_S:1") from P / #999:9

**Comment by nagarajasr** [comment]
try something like this:

```sql
select p.in_S.s_attributes, P.in('S').sl_attributes, p.p_attributes  from P
```

(where s_attributes refers to those attributes from S that you want to retrieve, and so on)

**Comment by nomi-ramzan** [comment]
Hi !
I am using your query ``` select p.in_S.cod, P.in('S').username, p.brand from P ``` But I am getting empty empty result. And sorry for late reply.
Thank you.

**Comment by nagarajasr** [comment]
oops... my bad.. should have been:

```sql
select in_S.cod, in('S').username, brand from P
```

**Comment by nomi-ramzan** [comment]
Thank you.

**Comment by nomi-ramzan** [comment]
This query working fine. but i am getting array only. like
My query is
``` select in_S.price, in_S.@rid, in('S').username, brand, title from P WHERE @rid = #29:0 ```
![capture](https://cloud.githubusercontent.com/assets/7391350/8918841/d43730d2-34cb-11e5-9a9c-c5c8c37517a1.JPG)
 Now how can i relate this data as row wise ?
like

Pid      title      username/seller    brand    price
1         abc       ahsan                  Apple    600
1         abc       ahsan                  Apple    1000

Thank you.

**Comment by nagarajasr** [comment]
use unwind: http://orientdb.com/docs/last/SQL-Query.html#unwind

**Comment by nomi-ramzan** [comment]
Amazing solution. Thank you.
But in orient docs this thing is missing how can I UNWIND if i have multi fields in my result
like
Query select in_S.price AS price,in_S.cod AS cod,in_S.@rid AS oid, in('S').username AS uname, brand, title from P UNWIND oid
Result
![image](https://cloud.githubusercontent.com/assets/7391350/8923866/bec10fe8-3507-11e5-9d5a-bc8ae892aac2.png)

**Comment by nagarajasr** [comment]
just list down all the fiels you want to unwind by, separated by commas like this:

```
select in_S.price AS price,in_S.cod AS cod,in_S.@rid AS oid, in('S').username AS uname, brand, title from P UNWIND oid, uname
```

**Comment by nomi-ramzan** [comment]
Thank you very much.
Best wishes 
Nauman

**Comment by nomi-ramzan** [comment]
Hi @nagarajasr 
Can you please tell me how can I apply ``` WHERE on in_S.status = 1 ```
Thank you

**Comment by nagarajasr** [comment]
this ought to work. UNWIND clause goes towards the end of the query, after any where clause but before limit clause. let me know if i have misunderstood.

```sql

select in_S.price AS price,in_S.cod AS cod,in_S.@rid AS oid, in('S').username AS uname, brand, title from P WHERE in_S.status = 1 UNWIND oid, uname

```

**Comment by nomi-ramzan** [comment]
Thank you.
