### ISSUE TITLE
[2.0.5][2.0.11][Durability] Unique Index does not find match for a select query

### ISSUE THREAD

**Issue by machinelearner** [orientechnologies/orientdb#4586]
Bumped into this mysterious issue in prod yesterday which caused many writes to be lost(atleast created that perception)

There is no easy way to reproduce this. 

Usage:
* We do not heavily rely on the auto-transaction in graph - Managed transactions
* SQL as the only means to interact with the graph
* Default distributed config
* Heavily use traversals

Following are the observations we had:
* This happens after a long run of events(looks like a symptom) - 100k vertices and nearly 300-400k edges.
* We had observed re-establishing socket/connections - Some of the forum threads/issue pages indicated the default behaviour of auto transaction to be true. That is fixed now.
* Read soon after a write does not return result - Query hits a Unique composite index with 3 fields
  * Force write again fails with unique criterion error which essentially means the index has this info
  * Queries beyond the force write return the result
  
 The above observation is applicable to the node the app connects to. If you query other nodes(which are not loaded by app requests) the result is consistent!

Currently a node restart forces sync and things get back to being ok.

Any help on this regard will be appreciated!

**Comment by lvca** [comment]
Could you check if the file "distributed-db-config.json" contained under your database diectory (`$ORIENTDB_HOME/databases/<yourdb>`) contains:

```
"readYourWrites": true,
```

??

**Comment by machinelearner** [comment]
this is turned on since one of our observation in previous versions was that, under high load, we were not getting right responses even from the node which performed the write.

**Comment by lvca** [comment]
Was you running in asynchronous mode?

**Comment by lvca** [comment]
@machinelearner Did you notice this problem again?

**Comment by machinelearner** [comment]
@lvca not this in particular, but i wouldnt conclude its fixed as there are hiccups even before getting to this state.

Currently, high load brings down the entire cluster with a possible split brain setup, it was beyond this point where in constant high load lead to the above issue.
I've sent a mail to you, still awaiting response.

**Comment by lvca** [comment]
Any news on this issue?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
