### ISSUE TITLE
Create UNIQUE_HASH_INDEX never ends

### ISSUE THREAD

**Issue by zafeirism** [orientechnologies/orientdb#4588]
I am using orient community 2.0.10 standalone and just faced the following issue regarding rebuilding/creating an index.

I have a class with 170k records and decided to do a rebuild index (through orient management portal). Rebuild failed with java out of bounds exception, so I went on droping and recreating the index (UNIQUE_HASH_INDEX). Recreation causes the process to run at 100% CPU and takes forever.

NOTE: Here is why I decided to rebuild the index: Server reached the maximum number of allowed connections and my services couldn't connect to it, so I tried to restart orient service. Restart never succeeded, so I killed the process and restarted it. However this might caused index corruption because when my services started talking again with orient server I got several exceptions "Orient.Client.API.Exceptions.OException: com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Error during index update with key #23:123882 and value true com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: atomic operation was rolled back by internal component". So I decided to rebuild all indexes but faced the issues mentioned earlier.

I can send the server logs if necessary.

(posted question for this issue also on google group [here](https://groups.google.com/forum/#!topic/orient-database/Qt5Bj_ReGS8)

**Comment by laa** [comment]
Hi,
Did you try to drop index and recreate it ?

**Comment by zafeirism** [comment]
Yes, after rebuild failed, I dropped the index and tried to recreate it but it never ends.

Just upgraded to version 2.0.12, but same results.

**Comment by zafeirism** [comment]
In server logs I see this error for a couple of vertices: https://gist.github.com/masimakopoulos/0c9483b9a0d8bba61fae

Indeed, when I try a select on any of these through orient web portal, I get  `com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Negative size was provided`

**Comment by laa** [comment]
Lets, do following.

Update to 2.0.12, then:
1. Perform export/import steps.
2. Open database in console.
3. run "repair database --fix-rid-bags" command.

Let me know what result you will get.

**Comment by zafeirism** [comment]
I followed the steps but got numerous errors (most of them `java.lang.NullPointerException`). 
Repair finished like this:
`Done! Fixed links: 35606, modified documents: 33184
Repair database complete (3626 errors)`

**Comment by laa** [comment]
You did export/import and ran repair database on imported DB, did not you ?

**Comment by zafeirism** [comment]
No, actually export failed (for a lot of vertices it couldn't fetch data). Most probably exported data wouldn't include corrupted vertices, so I tried a repair on the original db.

**Comment by zafeirism** [comment]
I just competed the repair step in the imported database as well. All seem good there, no errors, I even succeeded on creating the index I had dropped.

However, as I guessed earlier, there are missing vertices. All the corrupted ones didn't get exported, so only the clean ones are in the imported database, so everything succeeds there.

What can I do to ensure we have no data loss?

**Comment by laa** [comment]
Hi,
Unfortunatelly you will lost some vertexes. To avoid this case in future we do suggest to use 2.0-RC5, GA version, we redesigned data restore to avoid such cases during server crash.

**Comment by laa** [comment]
Actually you may try and report us is it true )).

**Comment by zafeirism** [comment]
Hi,
Thanks for the comments. I'm using 2.0.12 already, do you mean 2.1 GA? Also, do we have any clue of what caused this corruption and how I can prevent this in the future?

**Comment by laa** [comment]
oh it is quite internal staff I do suggest  you 2.1-RC5 instead, we will release GA during couple of fix.

**Comment by laa** [comment]
So to close issue, could you do following steps:
1. Do export/import ot 2.1-RC5.
2. Start the server
3. Perform any high load task which you have.
4. Crash server.
5. Check that data restore procedure is passed.
6. Provide us feedback and close issue if all is OK.

**Comment by laa** [comment]
any updates ?

**Comment by zafeirism** [comment]
No, I haven't followed the steps yet, I will keep you posted.

**Comment by laa** [comment]
Closed because of no reply.
