### ISSUE TITLE
lucene index overwrite io exception

### ISSUE THREAD

**Issue by arisAlexis** [orientechnologies/orientdb#4589]
running a test that does Drop class Tag; Create Class Tag extends V; Create property tagName STRING; CREATE INDEX Tag.tagName FULLTEXT ENGINE LUCENE;
INSERT into Tag content {"tagName": "leakage"};
INSERT into Tag content {"tagName": "water"};

then running the test for two times (running the code above), the second time always fails and the 3d,5th times etc always succeeds. 

error from server console is:

2015-07-16 13:53:23:693 SEVER {db=exchange} Sent run-time exception to the clien
t /127.0.0.1:53386: com.orientechnologies.orient.core.exception.OCommandExecutio
nException: No edge has been created because no target vertices [ONetworkProtoco
lBinary]Exception in thread "Thread-107"
2015-07-16 13:57:54:399 SEVER {db=exchange} Sent run-time exception to the clien
t /127.0.0.1:53504: com.orientechnologies.orient.core.exception.OCommandExecutio
nException: No edge has been created because no target vertices [ONetworkProtoco
lBinary]java.lang.RuntimeException: java.io.IOException: Cannot overwrite: C:\db
\orientdb-community-2.1-rc4\orientdb-community-2.1-rc4\databases\exchange\lucene
Indexes\Tag.tagName\_0.cfs
        at org.apache.lucene.search.ControlledRealTimeReopenThread.run(Controlle
dRealTimeReopenThread.java:247)
Caused by: java.io.IOException: Cannot overwrite: C:\db\orientdb-community-2.1-r
c4\orientdb-community-2.1-rc4\databases\exchange\luceneIndexes\Tag.tagName\_0.cf
s

**Comment by lvca** [comment]
Have you already tried with 2.1-rc5?

**Comment by arisAlexis** [comment]
I think it is only happening my program exits without doing a g.shutdown() so it is OK for now. thanks
