### ISSUE TITLE
"display raw record" throws exception on 2.1-rc5, 2.0.12 is ok

### ISSUE THREAD

**Issue by roman1720** [orientechnologies/orientdb#4596]
orientdb {db=GratefulDeadConcerts}> display raw record 1

Error: java.lang.ClassCastException: com.orientechnologies.orient.client.remote.OStorageRemoteThread cannot be cast to com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage

**Comment by nagarajasr** [comment]
i tried to reproduce the issue, i dont get the exception for ```display raw record 1``` however i receive the exact same exception when i give ```display raw record #37:1``` which is a valid record in my DB.

**Comment by roman1720** [comment]
http://orientdb.com/docs/last/Console-Command-Display-Raw-Record.html

Doc says "This command needs the relative position of the record in the result set."

1) orientdb {db=GratefulDeadConcerts}> select from V
2) display raw record 1 throws exception, on 2.0.12 not

**Comment by tglman** [comment]
fixed closing
