### ISSUE TITLE
ODatabaseDocumentTxPooled.getUser() sometimes is returning null under heavy load

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4600]
This issue quite hard to reproduce... Do you have ideas how it might happen if pool is open and db themself obtained without authentication error and etc.

**Comment by laa** [comment]
Do you use com.orientechnologies.orient.core.db.OPartitionedDatabasePool or com.orientechnologies.orient.core.db.document.ODatabaseDocumentPool ?

**Comment by PhantomYdn** [comment]
I use com.orientechnologies.orient.core.db.OPartitionedDatabasePoolFactory to get com.orientechnologies.orient.core.db.OPartitionedDatabasePool

**Comment by laa** [comment]
But ODatabaseDocumentTxPooled is not part of OPartitionedDatabasePool but part of com.orientechnologies.orient.core.db.document.ODatabaseDocumentPool which is deprecated.
Are you sure that you mean exactly ODatabaseDocumentTxPooled ? If so it means that somewhere in the program you use different pool implementation.

**Comment by PhantomYdn** [comment]
I definitely use new implementation. That was my mistake: wanted to refer to db from pool.

**Comment by laa** [comment]
Hi,
Is it the same issue as issue with "renaming of user" or different one ?

**Comment by laa** [comment]
Are you sure that it is not related too https://github.com/orientechnologies/orientdb/issues/5292 ?

**Comment by laa** [comment]
Closed because of no reply. Please free to reopen issue if you have information which I asked.
