### ISSUE TITLE
[Question] What happens in a backup process when the user does a write operation.

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4602]
I use the Automatic Backup handler. What does it mean in a technical view `The database is in read-only mode during backup operation`. How I will notify about this status? I use orientjs. Does exist any operation queues when the db is blocked ?

`
Backup does a consistent copy of database, all further write operations are locked waiting to finish it. The database is in read-only mode during backup operation. If you need an read/write database during backup setup a distributed cluster of nodes.
`
Source: http://orientdb.com/docs/2.0/orientdb.wiki/Backup-and-Restore.html

**Comment by lvca** [comment]
Unfortunately OrientDB doesn't push such events. I agree this could be useful, so this is an enhancement.

**Comment by StarpTech** [comment]
@lvca  Is it possible to backup my database in a none blocking way and automatic?

**Comment by lvca** [comment]
You can do that if you're running on Linux (see the docs) and you use CRON to execute the backup, not Automatic backup of OrientDB.

**Comment by StarpTech** [comment]
For a software which supports multiple OS this is a hard restriction. Is any feature planned which simplified the backup process ?

**Comment by laa** [comment]
Hi @StarpTech 
It is very old question but we have implemented in 2.2 version non blocking incremental backup feature. But unfortunately it is accessible only in enterprise version.

**Comment by StarpTech** [comment]
@laa thanks for the tip.
