### ISSUE TITLE
live query should also return the old and new index of the row in the result set

### ISSUE THREAD

**Issue by imdark** [orientechnologies/orientdb#4603]
this should be helpful when creating a sort query or a sorted paged query for example:

``` js
orientdb.select(
    'live select * from players order by score desc', { params: { table: "player" } }
  );
```

could return

<pre>
{ content: { '@type': 'd', '@class': 'players', name: 'Maxwell', score: 120 }, <b>newRowIndex:1, oldRowIndex:2</b>, type: 'd', cluster: 12, position: 41, version: 0 }
</pre>

**Comment by lvca** [comment]
I like it, :+1

**Comment by luigidellaquila** [comment]
Nice feature, but it will be quite expensive, because one of the following solutions has to be adopted:

1. keep the old result set in memory and re-sort it at record change

2. recalculate the whole query at every record change

**Comment by imdark** [comment]
Dont you recalculate the whole query at every record change any way to make sure the result still fits the query?, the older version of the code did this but it was a very naive implementaion I havent looked at the current one yet.

**Comment by luigidellaquila** [comment]
I have to check it, but in general it's not necessary. Think about a query like

```sql
SELECT FROM V WHERE name = 'foo'
```

when a new record is inserted, you only have to check if its name is 'foo' and in case send it to the client.
No need to completely recalculate the original query

**Comment by imdark** [comment]
If you have limit or an orderby or a group by you do

**Comment by luigidellaquila** [comment]
Yes, exactly. I will investigate it to see which is the best solution to achieve this

**Comment by imdark** [comment]
This code seems to do the job and in the case where the class new record has no class or it is not part of the query it does iterate over the result set otherwise it seems to ignore sorts and limits https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/sql/OCommandExecutorSQLLiveSelect.java
this is due to the fact that limits do no change the compiled filter in parselimit in OCommandExecutorSQLResultsetAbstract

**Comment by imdark** [comment]
Also the OCommandExecutorSQLLiveSelect implementation of matchesTarget seems somewhat inefficient, we can maintain a bloom filter of the ids and make it into a simple O(1) hash lookup

**Comment by luigidellaquila** [comment]
Hi @imdark 

I agree, this code can be optimized a lot (and improved in general).
It is in the roadmap for 2.2, so I'll start working on that as soon as 2.1 GA is released (in a few days)
