### ISSUE TITLE
Indexes not working when querying inside the cluster

### ISSUE THREAD

**Issue by lasitha1991** [orientechnologies/orientdb#4606]
I'm using document type database in Orientdb 2.0.3.

I have a class A which has an field attr1 and I have created NOTUNIQUE_HASH_INDEX index on that attr1.

Recently I have clustered class A into few clusters named  A_1, A_2, A_3 ... 

After that when I'm querying for a record in Class A I have noticed the following:

if I execute a query like this,
select from A where attr1 = #10:111 AND ...
          it uses the index on attr1 and do document reads around 1500 (which gives results pretty fast)

But if I execute a query like this,
select from cluster:A_1 where attr1 = #10:111 AND ... 
          it does not use the index on attr1 and do document reads around 14000 (which is the number of records in that cluster)

Note: I have rebuild the index also and still the result is same.

Is this a bug or a feature??

**Comment by smolinari** [comment]
Same post as here. 

https://groups.google.com/forum/#!topic/orient-database/iET3x8xoeWY

Scott

**Comment by lvca** [comment]
Indexes works at class level, not index level. We're working to a new spec to allow this, but right now this isn't supported, sorry. You could rather create multiple classes by using inheritance and in this case each class would have own index.

**Comment by smolinari** [comment]
You mean indexes work at class level and not at cluster level, correct?

Scott

**Comment by lasitha1991** [comment]
Thank you vary much for the Reply Lvca,

People would love to have that as an feature. So please try to implement that in the future.

Lasitha Weerasinghe

**Comment by smolinari** [comment]
@lvca -  mentioning you to (politely) get your attention to the question I asked above. I'm sorry, but I didn't understand your answer completely.  

Scott

**Comment by lvca** [comment]
@smolinari which part of the answer? How to use inheritance?

**Comment by Eric24** [comment]
@lvca: If I understand this right, are you saying that ODB won't/can't use an index on a clustered class (without the inheritance approach)? If so, I'd love to see an example of how inheritance would make this work.

**Comment by lasitha1991** [comment]
According to my understanding he is referring to something like this.

In my above mentioned scenario, instead of creating a cluster named as A_1, I have to create a new class A_1, inherited from class A.

Then the indexes I have created for Class A will be inherited to class A_1 also. (And even I can create specific indexes for the A_1 class also.)

So when I'm retrieving data I can query like "select from A_1 where ..." and this query will use the indexes created for class A and also for the Class A_1.

**Comment by smolinari** [comment]
@lvca - you said this. 

> Indexes works at class level, not index level. 

and I asked this 

> You mean indexes work at class level and not at cluster level, correct?

I am not sure what you meant with "index level", if that is what you meant to say.

Scott

**Comment by luigidellaquila** [comment]
Hi Scott,

yes, I guess it was just a typo ;-)
Indexes in OrientDB can be defined on classes, not on single clusters.
Eg. if you have a class called Person, with two clusters called "person_1"
and "person_2", you can define an index Person.name and all the records
contained in "person_1" and "person_2" will be indexed into that.
On the other side, there is no way to define an index directly on a
cluster, eg. on "person_1" only

Luigi


2015-07-22 6:43 GMT+02:00 Scott <notifications@github.com>:

**Comment by smolinari** [comment]
Thanks Luigi.
