### ISSUE TITLE
OSQLSynchQuery can be used only once.

### ISSUE THREAD

**Issue by TomekQl** [orientechnologies/orientdb#4607]
OSQLSynchQuery can be used only once. Next execution returns empty result.

Database: orientdb-community-2.0.3

In Maven's pom.xml:
orientdb-core and orientdb-client - version 2.0.3

Source code:
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentPool;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.record.impl.ODocument;
import com.orientechnologies.orient.core.sql.query.OSQLSynchQuery;
import java.util.List;

public class Bug {
    private final OSQLSynchQuery<ODocument> QEURY = new OSQLSynchQuery<>("SELECT * FROM Zgloszenia");

    public static void main(String[] args) {
        new Bug();
    }

    public Bug() {
        getResultSet(1);
        getResultSet(2);
        getResultSet(3);
    }

    private void getResultSet(int i) {
        ODatabaseDocumentTx db = ODatabaseDocumentPool.global().acquire("remote:127.0.0.1/Zgloszenia", "admin", "admin");

        List<ODocument> resultList;

        try {
            resultList = db.command(QEURY).execute();
            System.out.println(i + ": resultList is " + (resultList.isEmpty() ? "empty" : "not empty"));
        } finally {
            db.close();
        }
    }
}

return:
1: resultList is not empty
2: resultList is empty
3: resultList is empty

**Comment by lvca** [comment]
This isn't a bug, but a feature: http://orientdb.com/docs/last/Pagination.html#handle-it-by-hand. If you want to recycle the object call `.reset()` before reusing it.

**Comment by TomekQl** [comment]
Adding "QUERY.reset();" before reusing doesn't change output, but
"QEURY.resetPagination();" does.

Thanks:)
Kind regards
Tomek

**Comment by lvca** [comment]
You're right, that's the method.
