### ISSUE TITLE
EXPORT DATABASE doesn't support multi-inheritance

### ISSUE THREAD

**Issue by mjadczak-dx** [orientechnologies/orientdb#4614]
I've recently tried to use the EXPORT DATABASE command to set up a fixture schema to quickly set up and tear down a testing database. In my database, I make use of multi-inheritance, however it seems that the JSON format used only has a single field for the SuperClass, not an array field. This means only the first superclass is saved, and subsequently imported.

**Comment by lvca** [comment]
Fixed. Both old and new syntax with multiple classes is supported.
