### ISSUE TITLE
Edge returned when asked Vertex

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#4615]
Hi,
When asked a vertex, edge functions of the Java API (e.g., getEdge) return a result. This means that the Blueprint implementation of OrientDB is not compliant. For example, the Blueprint documentation states that getEdge(id) should return null if no edge is referenced by that id.

With OrientDB 2.1-rc4, the following very simple test case:

```java
OrientBaseGraph graph = ...;
Vertex v = graph.addVertex("class:TestVertex");
System.out.println(graph.getEdge(v.getId()));
System.out.println(graph.getEdgesOfClass("TestVertex").iterator().next());
```
displays:

```
e[#11:0][#-1:-1-TestVertex->#-1:-1]
v(TestVertex)[#11:0]
```

In addition, the same problem occurs with getVertex.

**Comment by lvca** [comment]
Could you execute this?

    System.out.println(graph.getEdge(v.getId()).getClass()); 
    System.out.println(graph.getEdgesOfClass("TestVertex").iterator().next().getClass());

**Comment by benjaminbillet** [comment]
Hi,
`System.out.println(graph.getEdge(v.getId()).getClass());` displays `class com.tinkerpop.blueprints.impls.orient.OrientEdge`. However, the second line throws a `ClassCastException: com.tinkerpop.blueprints.impls.orient.OrientVertex cannot be cast to com.tinkerpop.blueprints.Edge`

I runned the second line step by step. In the next() method of OrientElementIterator, the isEdgeType() test returns false:
```java
if (immutableClass.isEdgeType())
    currentElement = new OrientEdge(graph, currentDocument);
else
    currentElement = new OrientVertex(graph, currentDocument);
...
return (T) currentElement; // fails because currentElement is an OrientVertex and T is OrientEdge
```
Hope this helps.

**Comment by benjaminbillet** [comment]
Hi,
Any news regarding this issue?

**Comment by lvca** [comment]
Found the reason: This code:
```java
System.out.println(graph.getEdgesOfClass("TestVertex").iterator().next());
```

Should return the edges of class TestVertex, but such class has been used for Vertices, not Edges. So this usage is not correct, but the error handling is misleading. Fixing the error...

**Comment by benjaminbillet** [comment]
Ideally, `getEdgesOfClass(class)` should return an empty iterator or null if `class` is a vertex type. Nevertheless, this is a matter of personal preference/implementation effort and a clear error message is fine, if documented.

However, according to the Blueprint reference implementation (TinkerGraph), the getEdge usage is correct and must return null:

```java
Vertex v1 = graph1.addVertex("class:TestVertex");
System.out.println("ODB: " + graph1.getEdge(v1.getId()));
Vertex v2 = graph2.addVertex(1);
System.out.println("BP: " + graph2.getEdge(v2.getId()));
```
```
ODB: e[#11:0][#-1:-1-TestVertex->#-1:-1]
BP: null
```
The problem is the same if I use `getVertex` with an edge id.

**Comment by lvca** [comment]
Fixed and added some new test cases in GraphPolymorphicTest.java
