### ISSUE TITLE
Simplistic configuration not working due to `NullPointerException`s

### ISSUE THREAD

**Issue by g17** [orientechnologies/orientdb#4618]
I use OrientDB embedded for integration tests against a real OrientDB instance. The aim is to use a simplistic server configuration to leave out e.g. network configurations. But that throws `NullPointerException`s:

```
OServer server = OServerMain.create().startup(new OServerConfiguration()).activate();
...
server.shutdown();
```

That would basically work. But in the `OServer` class the configuration is checked like this in many places:

```
 if (configuration.network.sockets != null) {
        for (OServerSocketFactoryConfiguration f : configuration.network.sockets) {
                ...
```
That means when `configuration.network` is `null` the expression `configuration.network.sockets` throws a `NullPointerException`. Same for `protocols` and `listeners`.

The workaround so far is to create an empty network configuration that contains an empty socket, protocol and listener configuration.

The solution would be to introduce better `null` checks to skip over non existent configuration parts.

**Comment by compensator** [comment]
You want to run a server with zero configuration?

**Comment by g17** [comment]
@compensator Of course not in production. But in a basic integration test I needed a real `OServer` object. So my first approach was to create it with an empty configuration (meanwhile it is completely mocked). But that is not the point.

The thing is that the `OServer.startup()` method that takes an `OServerConfiguration` instance as parameter is exposed as public API via the [documentation](http://thydoc.com/orientdb/javadoc/server/com/orientechnologies/orient/server/OServer.html#startup-com.orientechnologies.orient.server.config.OServerConfiguration-).
So there are two options now in my opinion: either implementing a proper error handling responding to the user of the API something like "Hey, you are about to start a server instance without any configuration about exposed ports which makes no sense!". Or by making the `OServer.activate()` method more graceful instead which requires only minimal changes (see my pull request #4619 ).
In any case I would not expect `NullPointerException`s to be thrown anywhere!

**Comment by lvca** [comment]
Merged manually.
