### ISSUE TITLE
Studio automatically expands lightweight edges

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#4620]
Hi,
When lightweight edges are activated, Studio automatically expands the edges in the Graph editor (OrientDB 2.1rc4). In my opinion, this is not a good behavior given that a node with a lot of edges will overload/crash the browser (for instance, Firefox).

Here is a simple example:
```java
OrientBaseGraph graph = ...;
graph.setUseLightweightEdges(...);
Vertex v = graph.addVertex("class:TestVertex");
for(int i = 0; i < 100; i++)
{
	v.addEdge("Edge", graph.addVertex("class:TestVertex"));
}
```
With `graph.setUseLightweightEdges(false)`, displaying the vertex `v` gives the following result:
![with lightweight edges](http://benjaminbillet.fr/media/odb_studio_no_lighweight_edges.png)
With `graph.setUseLightweightEdges(true)`, displaying the vertex `v` gives the following result:
![with lightweight edges](http://benjaminbillet.fr/media/odb_studio_lighweight_edges.png)

**Comment by maggiolo00** [comment]
Fixed by this pull request
https://github.com/orientechnologies/orientdb-studio/pull/301
