### ISSUE TITLE
ORestricted and "onCreate.fields"/"onCreate.identityType" inheritance 

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4627]
Guys,

There is a cool feature in OrientDB: use of ORestricted and additional custom parameters to specify policy of security rules apply. I mean "onCreate.fields" and "onCreate.identityType".

But ORestrictedAccessHook is obtaining those parameters just from current class and if they are empty: it doesn't go deeper into super classes.
I think, it's not logical. If you do agree I can fix it and make a PR.

**Comment by lvca** [comment]
Seems reasonable. I'm waiting your PR ;-)

**Comment by PhantomYdn** [comment]
Please assign issue on me. Will have some time this week:)

**Comment by lvca** [comment]
@PhantomYdn did you have the chance to look at it?

**Comment by PhantomYdn** [comment]
Ohh... completely forgot to make a pull request and now my local branch for this feature are quite outdated. Will update in few days.

**Comment by PhantomYdn** [comment]
Can be easily implemented if PR #6207 will be merged. That PR contains methods for hierarchical taking custom values.

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
