### ISSUE TITLE
inV() and outV() with include() return nothing.

### ISSUE THREAD

**Issue by RobiFerentz** [orientechnologies/orientdb#4629]
While include() seems to work well with outE and inE functions, the same does not seem to hold for inV() and outV().

**Comment by luigidellaquila** [comment]
Hi @RobiFerentz 

could you provide a simple example to reproduce the problem?
The main difference is that outE() and inE() return a collection, while inV() and outV() return a single item.

**Comment by RobiFerentz** [comment]
I'm aware of the difference. However, it should still be possible the include fields of an inbound or outbound vertex of the edge you're querying the same way you do it vice versa.

Given a V1--->E1(with props)---->V2
A query of

    select *,inV('V2').include('name') from E1 where out = <some V1 rid> 

should give me not only the fields on E1, but the name property from V2 (inside a json object, as usual), but it does not.

**Comment by nagarajasr** [comment]
here is a possible workaround (#29:2 is an edge and ID is a property on the connected vertex):

```sql
select expand(@this.include('ID')) from (select expand(inv()) from #29:2)
```

**Comment by lvca** [comment]
The reason is that outV() and inV() returns a collection. The @nagarajasr solution should work.
