### ISSUE TITLE
EXISTS operator 

### ISSUE THREAD

**Issue by lilletech** [orientechnologies/orientdb#4630]
is there an exists comparator for sql syntax 
https://dev.mysql.com/doc/refman/5.0/en/exists-and-not-exists-subqueries.html

I'm using edges 

I have " Dataset (vertex )  <-> DatasetData(edge)  <-> Data (vertex)

there is index on property "stringValue" of the Data Vertex class.

i need to search any datasets that have a data  (where stringValue like "bond%" and his context.itemDef is "Name")  and a data (where stringValue like "james%" and his context.itemDef is "Forname") 

After reading responses from https://github.com/orientechnologies/orientdb/issues/4612 i cannot write sql conditions that contains a dot. (because it's not using indexes)

So i'm searching for exists clause. I don't see another solutions.

**Comment by j-mi-jim** [comment]
I've tried to contains but its not working with two contains.

SELECT FROM DatasetData WHERE 
out contains(SELECT FROM Data WHERE stringValue = "BOND"  and context.itemDefId="NAME") AND
 out contains(SELECT FROM Data WHERE stringValue = "JAMES" and context.itemDefId="FORNAME" ) 
GROUP BY in

**Comment by j-mi-jim** [comment]
Using in() method can help but i don't think that really it's the best request for performance. 
Waiting the version 3 of orientDB seems to be the solution.

Select  from DataSet where inE().out in(Select from Data where stringValue LUCENE "bond" and context.itemDefId="NAME" ) AND  inE().out in(Select from Data where stringValue LUCENE "JAMES" and context.itemDefId="FORNAME" )

**Comment by j-mi-jim** [comment]
Better request -> contrains subquery of data to the datasetdata with key of dataset !

Select from DataSet LET $dataOdId=@rid where inE().out in(Select from Data where stringValue LUCENE "BOND" and context.itemDefId="NAME" and outE("DatasetData").in=$dataOdId  ) AND 
inE().out in(Select from Data where stringValue LUCENE "GERTY" and context.itemDefId="FORNAME" and outE("DatasetData").in=$dataOdId  )

**Comment by turchinc** [comment]
did optimization for this use case make it into v3?  we are having a similar issue to #4612 where we cannot say something like:
`select Book where Author.name = xxx `
because the (existing) index does not get evaluated via the dot notation. and because of the number of objects subqueries are prohibitive.
