### ISSUE TITLE
queries make through the HTTP interface keep going when the connection dies

### ISSUE THREAD

**Issue by d1g1t4l** [orientechnologies/orientdb#4633]
This is how to reproduce it:

1. make a query that takes a few minutes to run via the web interface (browse tab)
1. run htop on the host, you will see one of the Java threads using ~50% cpu
1. kill the browser (the tcp connection will die too)
1. check htop again, the thread is still using ~50% cpu

I you repeat this process several times you can get an arbitrary number of threads into the busy state.

Is this the way things are supposed to work? It seems reasonable to expect that when the connection dies orientdb should stop the queries as it won't be able to report the result to the caller.

**Comment by lvca** [comment]
We already check the thread is interrupted. The solution here could be setting the thread to interrupted when a closed connection is found or EOF is reached.

**Comment by tglman** [comment]
add a check for interruption while buffering respone, now this case should not be possible.
