### ISSUE TITLE
Feature request: Embedding OrientDB (w/ OrientDB-Lucene) for iOS and Android

### ISSUE THREAD

**Issue by jrylan** [orientechnologies/orientdb#4634]
Couchbase has Couchbase Lite for iOS and Android which makes offline databases with syncing functionality a breeze. However, Couchbase doesn't have the graphing features or many of the other benefits of OrientDB, I believe supporting native embedded databases for iOS and Android would open OrientDB up to many opportunities like offline-enabled Point of Sale systems on tablet devices.

I understand since OrientDB is written in Java that supporting Android probably wouldn't be nearly as much of a hassle as support iOS. Perhaps a solution like [JS2ObjC](http://j2objc.org/) could be used to support an embedded database for iOS.

**Comment by swimmesberger** [comment]
Would also appreciate a android version - there is an unofficial port which removes the javax.management.* packages but it's REALLY outdated. Maybe it's possible to extract the javax.management.* stuff into a own package and therefore make it optional.

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
