### ISSUE TITLE
Extremely high number of discrepancies between documentation and OrientDB 2.1

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4636]
Let me list in this issue what I have found so far:

1) According to this: http://orientdb.com/docs/last/Functions.html#access-to-the-databases-from-functions orient object has methods getGraph(), getGraphNoTx() a long with getDatabase(). 

But in reality:

```java
public class OScriptOrientWrapper {
  protected final ODatabase db;

  public OScriptOrientWrapper() {
    this.db = null;
  }

  public OScriptOrientWrapper(final ODatabase db) {
    this.db = db;
  }

  public OScriptDocumentDatabaseWrapper getDatabase() {
    if (db == null)
      throw new OConfigurationException("No database instance found in context");

    if (db instanceof ODatabaseDocumentTx)
      return new OScriptDocumentDatabaseWrapper((ODatabaseDocumentTx) db);

    throw new OConfigurationException("No valid database instance found in context: " + db + ", class: " + db.getClass());
  }
}
```

2) There are mentioning of cool feature to save a json in db here: http://orientdb.com/docs/last/Functions.html#example

```javascript
var result = db.save({ "@class" : "OUser", name : "Luca", password : "Luc4", status: "ACTIVE", roles : role});
```

But in reality you should serialize to string prior to invocation of save.

3) Load doesn't work for rid as string. I saw something like:

```javascript
db.load("#5:0");
```
But in reality you have to wrap it to ORecordId

```javascript
 db.load(new com.orientechnologies.orient.core.id.ORecordId("#5:0"));
```

4) There is no mentioning of multiple super classes in documentation. Might be that's because 2.1 haven't been release yet?

**Comment by lvca** [comment]
1) This class is used and injected in place of Orient if graphdb module is installed (always by default): OScriptGraphOrientWrapper.
2) I have to check it, maybe Nashorn converts JS {} in different way? With Rhino such auto converson worked.
3) That was still missing, good point. Just implemented.
4) Yes, but it's in the pipeline.

**Comment by lvca** [comment]
Just checked and (2) works.

![image](https://cloud.githubusercontent.com/assets/312606/8857068/4a9f0ad4-316f-11e5-863c-bf6a614c934c.png)

**Comment by PhantomYdn** [comment]
2 doesn't work for me if it is in OFunction. Graph module is not included

**Comment by lvca** [comment]
What's the error?

**Comment by PhantomYdn** [comment]
No such method. But after serializing to string - it works perfectly. It seems rhino issue. Or additional method for json arg required in js host object.
