### ISSUE TITLE
named parameters with lucene  (api)

### ISSUE THREAD

**Issue by j-mi-jim** [orientechnologies/orientdb#4637]
use of parameters when query with lucene cause some probleme with operator lucene

OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>("select from Profile where name lucene :name)
Map<String,Object> params = new HashMap<String,Object>();
params.put("name", "OR");
params.put("name", "TOTO OR");

List<ODocument> result = database.command(query).execute(params); --> give query parser error.

how to do when you want to use the word not as an operator ?

the same request in the console doesn't give syntax error

**Comment by nagarajasr** [comment]
not sure about this, but have you tried placing single quotes around the reserved keyword 'or'

**Comment by maggiolo00** [comment]
@j-mi-jim 

AND, OR and NOT are reserved keywords in LUCENE
http://stackoverflow.com/questions/1311304/keyword-or-and-search-in-lucene
If you lowercase those three words you will not have problem
