### ISSUE TITLE
StringIndexOutOfBoundsException on query 'select * from' with missing argument in 2.0.13

### ISSUE THREAD

**Issue by jfrogit** [orientechnologies/orientdb#4639]
When executing the query `select * from` for any (or the example GreatfulDeadConcerts) database the unexpected runtime error `java.lang.StringIndexOutOfBoundsException: String index out of range: -1` occurs. 

For wrong query syntax the defined `OCommandSQLParsingException` with a error message which describes the parse error should be thrown as it is done for other query parse errors like this `com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #<column>  :  <details>`

**Comment by luigidellaquila** [comment]
Hi @jfrogit 

it should be already fixed in 2.1, could you please confirm?

**Comment by jfrogit** [comment]
Hi luigidellaquila,
now in version 2.1.2 the ```java.lang.StringIndexOutOfBoundsException``` no longer occurs. Instead the proposed ```com.orientechnologies.orient.core.sql.OCommandSQLParsingException``` is thrown. The error message is
```
Error on parsing command at position #0: Encountered " <FROM> "from "" at line 1, column 10.
Was expecting one of:
    <EOF>
    <TIMEOUT> ...
    <AS> ...
    <FETCHPLAN> ...
    <LOCK> ...
    <LET> ...
    <NOCACHE> ...
    <PARALLEL> ...
    <UNWIND> ...
    ";" ...
    "," ...
    <AS> ...
    "," ...
     [ONetworkProtocolHttpDb]
```
It is confusing to the reader and in my opinion needs further improvement.  
1. The double given from first   ```" <FROM> "```  and  second ```from ""```  irritates. Does have the parser recognized the given from in the query ```select * from``` as the from keyword in the SQL syntax or it is treated as an arbitrary argument? Just the "" after the second from gives a vague indication that there is something wrong with the from clause.
2. The list of expected syntax elements only list terminal symbols of the SQL syntax. This does not really catches the cause that an argument for the given ```from``` is missing. Mostly an identifier or  more precise a ```FromItem``` is expected as defined with the SQL syntax under http://orientdb.com/docs/last/SQL-Syntax.html 
```
    FromClause    :=    FromItem
    FromItem    :=    Rid
        |    <LBRACKET> Rid ( "," Rid )** <RBRACKET>
        |    Cluster
        |    IndexIdentifier
        |    <IDENTIFIER>
```

**Comment by luigidellaquila** [comment]
Hi @jfrogit 
I agree with you, the exception is right at this time but the error message is misleading.
Actually it's generated by JavaCC, so I have to check how much control I have on that, I'll see what I can do ;-)

**Comment by luigidellaquila** [comment]
Hi @jfrogit 

I'm closing this issue, error messages were improved a bit in many cases, but in general it is not possible to have better information in these cases

Thanks

Luigi
