### ISSUE TITLE
OStorageException: Thread was interrupted during flush

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4640]
Today i tried 2.0.13 database got error message : Thread was interrupted during flush when shutdown  database by execute sh shutdown.sh.  Then when i try to restart the database, it shows need rebuild index and all the index build failed. The issue blocking up to release new version of database.

**Comment by henryzhao81** [comment]
How to repoduce, use the database i send to you, execute following sql script, then shutdown, you will see the error. 

insert into user set name = 'loadtest', password = 'Passw0rd', status = 'ACTIVE', roles = [];

update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest';

insert into config set user = (select from user where name = 'loadtest'), name = 'loadtest';

insert into group set name = 'loadtest', token = 'loadtest', user = (select from user where name = 'loadtest'), config = (select from config limit 1), role = (select from orole where name = 'writer'), owner = (select from user where name = 'loadtest');

update config set group = (select from group where name = 'loadtest') where name = 'loadtest';
update user add shares = (select from group where name = 'loadtest') where name = 'loadtest';
update user set config = (select from config where name = 'loadtest') where name = 'loadtest';

insert into user set name = 'loadtest1', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest1';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest1';
insert into config set user = (select from user where name = 'loadtest1'), name = 'loadtest1';
update user set config = (select from config where name = 'loadtest1') where name = 'loadtest1';

insert into user set name = 'loadtest2', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest2';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest2';
insert into config set user = (select from user where name = 'loadtest2'), name = 'loadtest2';
update user set config = (select from config where name = 'loadtest2') where name = 'loadtest2';

insert into user set name = 'loadtest3', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest3';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest3';
insert into config set user = (select from user where name = 'loadtest3'), name = 'loadtest3';
update user set config = (select from config where name = 'loadtest3') where name = 'loadtest3';

insert into user set name = 'loadtest4', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest4';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest4';
insert into config set user = (select from user where name = 'loadtest4'), name = 'loadtest4';
update user set config = (select from config where name = 'loadtest4') where name = 'loadtest4';

insert into user set name = 'loadtest5', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest5';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest5';
insert into config set user = (select from user where name = 'loadtest5'), name = 'loadtest5';
update user set config = (select from config where name = 'loadtest5') where name = 'loadtest5';

insert into user set name = 'loadtest6', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest6';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest6';
insert into config set user = (select from user where name = 'loadtest6'), name = 'loadtest6';
update user set config = (select from config where name = 'loadtest6') where name = 'loadtest6';

insert into user set name = 'loadtest7', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest7';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest7';
insert into config set user = (select from user where name = 'loadtest7'), name = 'loadtest7';
update user set config = (select from config where name = 'loadtest7') where name = 'loadtest7';

insert into user set name = 'loadtest8', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest8';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest8';
insert into config set user = (select from user where name = 'loadtest8'), name = 'loadtest8';
update user set config = (select from config where name = 'loadtest8') where name = 'loadtest8';

insert into user set name = 'loadtest9', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest9';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest9';
insert into config set user = (select from user where name = 'loadtest9'), name = 'loadtest9';
update user set config = (select from config where name = 'loadtest9') where name = 'loadtest9';

insert into user set name = 'loadtest10', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest10';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest10';
insert into config set user = (select from user where name = 'loadtest10'), name = 'loadtest10';
update user set config = (select from config where name = 'loadtest10') where name = 'loadtest10';

insert into user set name = 'loadtest11', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest11';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest11';
insert into config set user = (select from user where name = 'loadtest11'), name = 'loadtest11';
update user set config = (select from config where name = 'loadtest11') where name = 'loadtest11';

insert into user set name = 'loadtest12', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest12';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest12';
insert into config set user = (select from user where name = 'loadtest12'), name = 'loadtest12';
update user set config = (select from config where name = 'loadtest12') where name = 'loadtest12';

insert into user set name = 'loadtest13', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest13';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest13';
insert into config set user = (select from user where name = 'loadtest13'), name = 'loadtest13';
update user set config = (select from config where name = 'loadtest13') where name = 'loadtest13';

insert into user set name = 'loadtest14', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest14';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest14';
insert into config set user = (select from user where name = 'loadtest14'), name = 'loadtest14';
update user set config = (select from config where name = 'loadtest14') where name = 'loadtest14';

insert into user set name = 'loadtest15', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest15';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest15';
insert into config set user = (select from user where name = 'loadtest15'), name = 'loadtest15';
update user set config = (select from config where name = 'loadtest15') where name = 'loadtest15';

insert into user set name = 'loadtest16', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest16';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest16';
insert into config set user = (select from user where name = 'loadtest16'), name = 'loadtest16';
update user set config = (select from config where name = 'loadtest16') where name = 'loadtest16';

insert into user set name = 'loadtest17', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest17';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest17';
insert into config set user = (select from user where name = 'loadtest17'), name = 'loadtest17';
update user set config = (select from config where name = 'loadtest17') where name = 'loadtest17';

insert into user set name = 'loadtest18', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest18';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest18';
insert into config set user = (select from user where name = 'loadtest18'), name = 'loadtest18';
update user set config = (select from config where name = 'loadtest18') where name = 'loadtest18';

insert into user set name = 'loadtest19', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest19';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest19';
insert into config set user = (select from user where name = 'loadtest19'), name = 'loadtest19';
update user set config = (select from config where name = 'loadtest19') where name = 'loadtest19';

insert into user set name = 'loadtest20', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest20';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest20';
insert into config set user = (select from user where name = 'loadtest20'), name = 'loadtest20';
update user set config = (select from config where name = 'loadtest20') where name = 'loadtest20';

insert into user set name = 'loadtest21', password = 'Passw0rd', status = 'ACTIVE', roles = [], group = [];
update user set roles = (select from orole where name = 'useradmin') where name = 'loadtest21';
update user add group = (select from group where name = 'loadtest') where name = 'loadtest121';
insert into config set user = (select from user where name = 'loadtest21'), name = 'loadtest21';
update user set config = (select from config where name = 'loadtest21') where name = 'loadtest21';

update group add memberUsers = (select from user where name = 'loadtest1') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest2') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest3') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest4') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest5') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest6') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest7') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest8') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest9') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest10') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest11') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest12') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest13') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest14') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest15') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest16') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest17') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest18') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest19') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest20') where name = 'loadtest';
update group add memberUsers = (select from user where name = 'loadtest21') where name = 'loadtest';


Please use the same package i give you last time lockTest.zip.bak, copy jars to releases/orientdb-community-2.0.13-SNAPSHOT/lib, copy files in config folder to releases/orientdb-community-2.0.13-SNAPSHOT/config.  unzip the database file pharos_med_dev.zip. Start database, execute the sql i gave to you in my previous email, and execute sh shutdown.sh. Exception will happen. Thanks,

**Comment by LucaSon90** [comment]
Thank You for the detailed informations, Your request is being processed.

**Comment by laa** [comment]
Hi Henry, fixed.
But as usual I DO suggest you to use 2.0-RC6 version which we release today because that is where "file close" bug is fixed.
