### ISSUE TITLE
Documentation for Server-side JavaScript API

### ISSUE THREAD

**Issue by vinerz** [orientechnologies/orientdb#4643]
Hello everyone! I am enjoying the world of OrientDB but I feel that the JavaScript API is lacking documentation or is very hard to find.

I am developing some server-side Functions for my DB using JS but sometimes I get stuck in how to use certain functions, which parameters send to it and what does it return.

I found a javadoc explaining the Java Methods mirrored to the JS objects but as I am not used to Java, I got really confused about how to use them. Something like the **orientjs** README.md, that is wonderfully documented and detailed, would be very helpful.

Thank you all for this great tool.
Vinicius

**Comment by dcarr178** [comment]
+ 1 

I have the same problem trying to utilize server-side functions in any meaningful way. So far I have created a handful of functions through sheer trial and error but development is horribly slow.

**Comment by optimuspaul** [comment]
+1 super disappointed with the lack on docs and consistency on the javascript API. What docs I could find on it seemed to be about something altogether different, or were severely lacking.

**Comment by Ndrou** [comment]
+1
We gave up to use them due to the lack of documentation, it's always a struggle when we have to use them.
