### ISSUE TITLE
ArrayIndexOutOfBound Exception when using binary protocol in Distributed mode with databases in format 1.7.x

### ISSUE THREAD

**Issue by shlapkov** [orientechnologies/orientdb#4644]
Issue is exactly the same as: https://github.com/orientechnologies/orientdb/issues/2953 after starting Server in distributed mode with large production database in 1.7.x format getting the following errors when trying retrieve data via remote connections:
jvm 1    | WARN  [ORecordSerializerBinary] Error deserializing record with id #50:1850 send this dat
a for debugging: cGxhdGZvcm0tSm9iUmVwb3J0QGlkOiIyNWMwNzNmNC1lMmVjLTRmMzgtYjFmOS0yZWM5Njc4NWJjZWQiLGp
vYklkOiIyMzUiLG5hbWU6IkNBU1MzNTUzIixvdXRwdXRGb3JtYXQ6InBkZiIsb3duZXI6InBic3Byb2MiLGNvbXBsZXRlZDoxMzM
xNTc3Mjg3NTA3dCxyZXBvcnRDb250ZW50czojNDA6MTg1MA==
jvm 1    | ERROR [OLazyRecordIterator] Error on iterating record collection
jvm 1    | com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving recor
d #50:1850 (cluster: platform-jobreport)
jvm 1    |      at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadReco
rd(ODatabaseDocumentTx.java:1640) ~[orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx
.java:88) ~[orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseD
ocumentTx.java:1452) ~[orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseD
ocumentTx.java:118) ~[orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:318) ~[or
ientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordI
terator.java:75) [orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordI
terator.java:38) [orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordS
erializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:698) [orientdb-core-2.0.12.jar:
2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordS
erializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569) [orientdb-core-2.0.12.jar:2.0
.12]
jvm 1    |      at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordS
erializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261) [orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordS
erializerBinary.toStream(ORecordSerializerBinary.java:104) [orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2
097) [orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:6
95) [orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtoco
lAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:417) [orientdb-server-2.0.12.jar:2.0.12
]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtoco
lAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:432) [orientdb-server-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtoco
lAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:136) [orientdb-server-2.0.12.jar:2.0
.12]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinar
y.command(ONetworkProtocolBinary.java:1230) [orientdb-server-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinar
y.executeRequest(ONetworkProtocolBinary.java:390) [orientdb-server-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtoco
lAbstract.execute(OBinaryNetworkProtocolAbstract.java:217) [orientdb-server-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69) [orientd
b-core-2.0.12.jar:2.0.12]
jvm 1    | Caused by: java.lang.ArrayIndexOutOfBoundsException: 112
jvm 1    |      at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordS
erializerBinary.fromStream(ORecordSerializerBinary.java:74) [orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.record.ORecordAbstract.fromStream(ORecordAbstra
ct.java:129) ~[orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.record.impl.ODocument.fromStream(ODocument.java
:1442) [orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.record.impl.ODocument.fromStream(ODocument.java
:76) [orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadReco
rd(ODatabaseDocumentTx.java:1625) ~[orientdb-core-2.0.12.jar:2.0.12]
jvm 1    |      ... 19 common frames omitted

Patch for the issue was sent to @lvca few days ago.

**Comment by lvca** [comment]
@tglman Any chance to look at the patch?

**Comment by tglman** [comment]
The patch included also other parts that are already in the 2.0.x branch, I'm rewriting the fix starting for that.

**Comment by lvca** [comment]
@tglman thanks.

**Comment by tglman** [comment]
i wrote the fix, the problem from the stack trace was that some lazy loading was happening while the record was serialized, this should not happen, with the fix i force that the lazy load disable while serializing, it's missed the test case

**Comment by jillray7** [comment]
@tglman Thanks! Please let us know when the test case is complete.

**Comment by shlapkov** [comment]
Commuted files in git hub: https://github.com/shlapkov/OrientIssues/blob/master/OLazyRecordIterator.java.patch

https://github.com/shlapkov/OrientIssues/blob/master/OLazyRecordIterator.java

It is actually workaround

the root cause for the issue poor design for network protocol:
 public ORecordAbstract fromStream(final byte[] iRecordBuffer) {
    _dirty = false;
    _contentChanged = false;
    if (ONetworkThreadLocalSerializer.getNetworkSerializer() != null) {
      ONetworkThreadLocalSerializer.getNetworkSerializer().fromStream(iRecordBuffer, this, null);
      _source = null;
    } else
      _source = iRecordBuffer;
    _size = iRecordBuffer != null ? iRecordBuffer.length : 0;
    _status = ORecordElement.STATUS.LOADED;

    invokeListenerEvent(ORecordListener.EVENT.UNMARSHALL);

    return this;
  }

**Comment by jillray7** [comment]
@tglman @lvca They provided a patch/workaround, however they want to be sure that an actual fix or modification in the network protocol is done, tested and released.

**Comment by tglman** [comment]
added also the test case that for avoid lazy load while serialization is happening

**Comment by lvca** [comment]
@tglman can we close it?

**Comment by jillray7** [comment]
@tglman @lvca @shlapkov provided a patch/workaround, however they want to be sure that an actual fix or modification in the network protocol is done, tested and released. Can the protocol design be modified so that the patch isn't required?

**Comment by tglman** [comment]
Hi all,
I did the fix and we can close it, the problem it's not related to the network protocol, but to the fact that lazy load was triggered while network serialization was happening, the provided patch was working on disabling the network serialization during the lazy load, but actually that lazy load should not happen in the first place, so that patch is not needed, thank you anyway for providing it, it gave us the right details for understand what was wrong.

Closing

**Comment by jillray7** [comment]
@shlapkov Thank you for your help with this issue. Let us know if you have further comments or requests.

**Comment by shlapkov** [comment]
yes fixed in 2.0.14-snapshot will confirm once new build 2.0.14 released.
