### ISSUE TITLE
Problems with SKIP clause

### ISSUE THREAD

**Issue by nidaca** [orientechnologies/orientdb#4647]
If we have the following simple test case:

- schema: a class Product with two fields, a float field 'price' and a datetime field 'prodDate'.

- queries:

SELECT FROM Product WHERE price = 20 ORDER BY prodDate SKIP 0 LIMIT 5
   * correct, returns me the products with rids >>> [#19:13, #19:157, #19:367, #19:498, #19:542]

SELECT FROM Product WHERE price = 20 ORDER BY prodDate SKIP 2 LIMIT 5
   * correct >>> [#19:367, #19:498, ... ]

SELECT @rid FROM (SELECT FROM Product WHERE price = 20 ORDER BY prodDate SKIP 0 LIMIT 5)
   * correct >>> [#19:13, #19:157, ... ]

SELECT @rid FROM (SELECT FROM Product WHERE price = 20 ORDER BY prodDate SKIP 2 LIMIT 5)
   * INCORRECT >>> [#19:13, #19:157, ... ]

Now if I add a NOTUNIQUE index on prodDate ...

SELECT @rid FROM (SELECT FROM Product WHERE price = 20 ORDER BY prodDate SKIP 2 LIMIT 5)
   * correct >>> [#19:367, #19:498, ... ]

Now add a NOTUNIQUE_HASH_INDEX on price (also the previous index enabled) ...

SELECT @rid FROM (SELECT FROM Product WHERE price = 20 ORDER BY prodDate SKIP 2 LIMIT 5)
   * again INCORRECT >>> [#19:13, #19:157, ... ]

You should check these problems guys, SKIP functionality is really important in production code. Thanks!

**Comment by nagarajasr** [comment]
@tg

**Comment by benjaminbillet** [comment]
Hi,
I don't know what exactly is happening inside the OrientDB code (I am not a contributor) and I'm not sure this is related to your problem, but you shouldn't use SKIP without providing a deterministic order (this is true for any SGBD: http://use-the-index-luke.com/sql/partial-results/fetch-next-page). 
The explanation is very simple: if two entries A and B have the same prodDate, it's not possible to decide whether A is before B or B is before A. Consequently, OrientDB will sort them randomly or will sort them based on implementation-specific criteria. This random behavior is probably messing with the SKIP execution. In addition, by specifying a NOT_UNIQUE index, you are forcing the non-determinism at index level, as this type of index is designed to manage several entries for the same value

You can convert your non-deterministic SKIP clause into a deterministic one by simply adding the @rid: 
```
SELECT @rid FROM (SELECT FROM Product WHERE price = 20 ORDER BY prodDate,@rid SKIP 2 LIMIT 5)
```
Does this modification improve your results? If not, there is probably a bug. In any case, SKIP shouldn't be allowed with NOT_UNIQUE indexes.

FYI, you can avoid SKIP by using the technique presented here: http://orientdb.com/docs/2.0/orientdb.wiki/Pagination.html (read the "Use the RID-LIMIT" section). If this technique suits your use cases, it will significantly improve the performance of your requests.

**Comment by nidaca** [comment]
@benjaminbillet : my test database has no products with the same prodDate, such that the theoretical concern presented in your comment doesn't apply to my test case. yes, I know the other pagination technique but I need also this approach and a I especially need a functional SKIP clause. 10x for your understanding ...

**Comment by nidaca** [comment]
@luigidellaquila, this is also a very annoying bug. I just made a change on my repo branch that loops through the same first nth resources from the database, over and over again, just because the skip doesn't work properly :|

**Comment by luigidellaquila** [comment]
Hi @nidaca 

This issue was fixed months ago, could you please confirm that the fix is also effective in your use case? 

Thanks

Luigi
