### ISSUE TITLE
A worrying statement by a contributor

### ISSUE THREAD

**Issue by ciscoheat** [orientechnologies/orientdb#4650]
I'm looking for a modern DB to use in a big upcoming project, and OrientDB seems really nice. However, I found a recent comment (June 2015) from the author of OrientDB's node.js driver on SO: http://stackoverflow.com/questions/28553942/what-factors-to-consider-when-choosing-a-multi-model-dbms-orientdb-vs-arangodb/28617795#comment49647000_28617795

> I can't give a lot of details because of NDA but we faced a long string of problems which were a direct result of how OrientDB is developed, rather than anything being wrong with it conceptually. To put it simply, it is not developed to the high standards that you'd expect from a database vendor, and while it claims a lot of features, a lot of those features are half baked or just don't work. We spent a lot of time and effort working on OrientDB for our clients, and in the end it disappointed all of them.

Seems like quite serious words from a big contributor, previously filled with mostly praise. It worries me, and I'd like to give you a chance to reply if you haven't seen it.

By doing that I'm adding another github issue to the already ~1000 open ones, which isn't a huge evaluation metric for me but still notable.

I hate bringing up things like this, and would never do unless I'm on the edge (nice graph joke eh) of choosing a very important piece of software that I will be using daily for years to come.

**Comment by nagarajasr** [comment]
@ciscoheat IMHO what would be really useful is if you could raise any *actual* issues that you face while evaluating the product yourself. as such this particular issue does not provide any specifics which the developers could investigate/ fix. that's not to say that your concerns are invalid, just that (in my opinion) raising a github issue might not be the best way for this matter

**Comment by ciscoheat** [comment]
Well, there should be plenty of issues, many of them probably hard to find in an evaluation, given that a long-time contributor posts such a statement. Hopefully OrientDB are also aware of them and can respond, so I don't have to find them *after* committing to the technology, leading to disappointment and wasted time. Gathering this kind of information is an important, time saving part of evaluation.

**Comment by compensator** [comment]
I can't respond on behalf of Orient nor Luca Garulli, but I am working on a contract where we have been evaluating the product and we came across this post as well.  We researched further and decided that it was not an issue.  I suggest that you research further as well.  I will submit this blog entry from Luca:

http://zion-city.blogspot.it/2015/06/5-wonderful-years-on-github-thanks-to.html?m=1

**Comment by compensator** [comment]
I will also clarify that I have not contributed a single line of code to OrientDB.

**Comment by ciscoheat** [comment]
Thank you, I appreciate and will consider your feedback.

**Comment by lvca** [comment]
I'm tagging this issue as question and closing it because other users provided enough information to answer it.
