### ISSUE TITLE
SQL comment throws OCommandExecutorNotFoundException in OrientDB Studio

### ISSUE THREAD

**Issue by isturlic** [orientechnologies/orientdb#4651]
Hi,

I'm using OrientDB 2.1 rc5.
When I enter the following in "Browse" tab of OrientDB Studio:

/* select from V */
select from E

or

-- select from V
select from E

it throws exception:
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException

I tried other combinations of comment characters but it always fails.

Ivan.

**Comment by maggiolo00** [comment]
@isturlic 
this is not a valid syntax
```
/ select from V / select from E
```

**Comment by isturlic** [comment]
That also doesn't work. What is the correct syntax?
If I press CTRL + / (Toggle comments) in Studio it makes comment like this:

/* this is some comment */

which throws exception.
![comment-exception](https://cloud.githubusercontent.com/assets/13510235/8911923/91022236-348f-11e5-89e6-1e53022d8381.png)

**Comment by luigidellaquila** [comment]
Hi @isturlic 
yes, it seems strange that Studio has a feature like commenting with CTRL + / and then it does not support it completely. The problem is that the query editor is a third party, opensource component, and the CTRL + / was not disabled (maybe we should).
Anyway, comments are not supported a this stage (they will be in short, probably), but you can highlight the portion of query you want to execute and then press CTRL + ENTER to execute only the highlighted part

**Comment by isturlic** [comment]
Ok. Thanks, Luigi.
I get it now. I hope comments will be supported soon. In the meantime, it is better to disable that option because it is misleading.

**Comment by oharlem** [comment]
+1

**Comment by luigidellaquila** [comment]
Fixed in 2.1.x and develop branches, now multi-line java style comments are supported, 
eg. /* comment */

The behavior is consistent with OrientDB studio editor ctrl+/

**Comment by pkoppstein** [comment]
The /* ... */ style comments are broken, e.g. in OrientDB console v.2.1.10;

```
$ cat comments.osql
/* single-line comment */

$ console.sh ~/orientdb/comments.osql
OrientDB console v.2.1.10 (build 2.1.x@r6ecbf4e08df982cb39691c634c132392b6fc00d2; 2016-01-27 03:35:54+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> /* single-line comment */

!Unrecognized command: '/* single-line comment */'
$ 
```

**Comment by smolinari** [comment]
@pkoppstein  This whole discussion is about Studio, not the console. 

If you think it is a problem, you should probably start a new issue. Though, to me. Writing comments in the console isn't really something I would think is necessary, is it?

Scott

**Comment by pkoppstein** [comment]
@smolinari - "console.sh" accepts pathnames for execution in batch mode.  These are essentially scripts, and every respectable scripting language I know of allows comments.  It's my impression that (in general) what is acceptable as an OSQL "script" in the Studio is (or should be) acceptable for "console.sh" and vice versa.

**Comment by smolinari** [comment]
Ok. Then start a new issue. :smile: 

Scott
