### ISSUE TITLE
How to stop the database connection gracefully for Tomcat

### ISSUE THREAD

**Issue by arisAlexis** [orientechnologies/orientdb#4652]
I am using Intellij 14 and Tomcat to deploy a webapp. This opens a connection to a remote:localhost OrientDB server when the InitialListener servlet is run. 
Even though I close the connection to the database I get this error:

27-Jul-2015 00:41:07.114 WARNING [RMI TCP Connection(7)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [exchange] appears to have started a thread named [OrientDB <- Asynch Client (/127.0.0.1:2424)] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

This stops the redeployment process. 

In my contextDestroyed I have put a .close() to the graphFactory,documentFactory and pool.

**Comment by lvca** [comment]
Could it be that the shutdown of thread is asynchronous and takes few ms? Please can you check that thread is not running after, let's say, 2 seconds of shutdown?

**Comment by waltron** [comment]
So is that the issue?  Async call on shutdown? as I get this too.
