### ISSUE TITLE
Why getRawGraph always return an ODatabaseDocumentTx object?

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#4653]
Hi,
Given an OrientGraphNoTx object, getRawGraph() returns an ODatabaseDocumentTx object. What does it mean? Should I explicitly commit my modifications?
```java
OrientGraphFactory factory = new OrientGraphFactory(...);
OrientGraphNoTx graph = return factory.getNoTx();
ODatabaseDocumentTx db = graph.getRawGraph(); // <-- why ODatabaseDocumentTx?
```

**Comment by maggiolo00** [comment]
@benjaminbillet 

ODatabaseDocumentTx is the underlying object that is used by the OrientGraphNoTx

**Comment by benjaminbillet** [comment]
Hi,
Thanks for your answer. I got confused, because I interpreted the "Tx" suffix as "something with transactions enabled", given that the "NoTx" suffix is used for classes which don't use transactions.

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 

got it, it can be misleading. Actually ODatabaseDocumentTx can be used for both transactional and non-transactional operations. Unlike OrientGraph, ODatabaseDocumentTx has explicit begin() method, and when you create a new instance of ODatabaseDocumentTx a transaction is not active by default.
