### ISSUE TITLE
Impossible to create OType.LINK edges when AutoScaleEdgeType is set to false (default)

### ISSUE THREAD

**Issue by skibaa** [orientechnologies/orientdb#4656]
The following commands were executed on an empty database. In console and in code it's easy to workaround with setAutoScaleEdgeType(true), but it is impossible to do that in Graph Editor in Studio.

``` groovy
import com.orientechnologies.orient.core.metadata.schema.OType
import com.tinkerpop.blueprints.Direction
g = new com.tinkerpop.blueprints.impls.orient.OrientGraph("remote:localhost/test")
g.setAutoStartTx(false)
g.commit()
g = new com.tinkerpop.blueprints.impls.orient.OrientGraph("remote:localhost/test")
g.setAutoStartTx(false)
g.commit()
parent = g.createVertexType('parent')
parent.setStrictMode(true)
parent.createEdgeProperty(Direction.IN, 'sonOf', OType.LINKLIST)
child = g.createVertexType('child')
child.setStrictMode(true)
child.createEdgeProperty(Direction.OUT, 'sonOf', OType.LINK)
parent1 = g.addVertex('class:parent')
child1 = g.addVertex('class:child')
g.commit()
child1.addEdge('sonOf', parent1)
```

java.lang.IllegalStateException: Type of field provided in schema 'LINK' can not be used for link creation.
    at com.tinkerpop.blueprints.impls.orient.OrientVertex.createLink(OrientVertex.java:146)
    at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:929)
    at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:802)
    at com.tinkerpop.blueprints.Vertex$addEdge.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
...

``` groovy
g.setAutoScaleEdgeType(true)
child1.addEdge('sonOf', parent1)
```

e[#14:0][#13:0-sonOf->#12:0]

**Comment by fc7** [comment]
This still happens in 2.2-beta2 ... Run console.sh on a file containing the following:

```sql
SET ECHO true;
CREATE DATABASE memory:test;
CREATE CLASS Person EXTENDS V;
CREATE PROPERTY Person.name STRING;
CREATE CLASS friendOf EXTENDS E;
CREATE PROPERTY Person.in_friendOf LINK Person;
CREATE PROPERTY Person.out_friendOf LINK Person;
INSERT INTO Person SET name="Anna";
INSERT INTO Person SET name="Maria";
CREATE EDGE friendOf FROM (SELECT FROM Person WHERE name="Anna") TO (SELECT FROM Person WHERE name="Maria");
```
and it will return this error:
```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.create EDGE friendOf FROM #17:0 TO #18:0
	Storage URL="memory:test"

Error: java.lang.IllegalStateException: Type of field provided in schema 'LINK' cannot be used for link creation.
```

By removing the condition ``iGraph.isAutoScaleEdgeType() && `` in  orientdb/graphdb/src/main/java/com/tinkerpop/blueprints/impls/orient/OrientVertex.java (line 133)
it works.

**Comment by fc7** [comment]
@lvca BTW there is another problem with ODocument#validateLink when creating edges in strict mode which pops up once the above problem is fixed. I will report it in a separate issue ... but to be able to reproduce it you need to fix this one first ;-)

**Comment by lvca** [comment]
The error is correct. Creating edges as LINK instead of a collection of links can be done only if `setAutoScaleEdgeType(true)`.
