### ISSUE TITLE
MATCHES broken in 2.1-rc5

### ISSUE THREAD

**Issue by iamlogiq** [orientechnologies/orientdb#4657]
using MATCHES in queries doesn't work...please help!

**Comment by luigidellaquila** [comment]
Hi @iamlogiq 

could you please post a query that does not work...?

Thanks

**Comment by iamlogiq** [comment]
@luigidellaquila 
ANY simple query doesn't work. 
SELECT FROM OUSER WHERE any() MATCHES '.*'
I saw the a previous issue regarding the same problem in 2.1-rc3... so I figured it was fixed by rc5 but i'm getting the EXACT issues described here: https://github.com/orientechnologies/orientdb/issues/4233#issuecomment-125182864

**Comment by nagarajasr** [comment]
which API are you using? it seems fine from the console...
(2.1-SNAPSHOT from a few days ago)

```
orientdb {db=testdb}> select from ouser where any() matches '.*'

----+----+------+------+-------------------------------------------------------------------------+------+-----
#   |@RID|@CLASS|name  |password                                                                 |status|roles
----+----+------+------+-------------------------------------------------------------------------+------+-----
0   |#5:0|OUser |admin |{SHA-256}8C6976E5B5410415BDE908BD4DEE15DFB167A9C83FC4BB8A81F6F2AB448A918|ACTIVE|[1]
1   |#5:1|OUser |reader|{SHA-256}3D0941964AA3EBDCB00CCEF58B1BB3999F898465E9886D5AEC7F31090A0FB30|ACTIVE|[1]
2   |#5:2|OUser |writer|{SHA-256}B93006774CBDD4B299389A03AC3D8C3A76B460D538795BC12718011A909FBA5|ACTIVE|[1]
3   |#5:3|OUser |nagu  |{SHA-256}7197108541068E4188923D18E3A3F789A8B155274CCA15FC816D9C4FD2EBFD0|ACTIVE|[3]
----+----+------+------+-------------------------------------------------------------------------+------+-----

4 item(s) found. Query executed in 0.033 sec(s).

```

**Comment by iamlogiq** [comment]
I tested it with orientjs plugin for node and I also tested it on the orientdb studio web explorer where I entered the query in the 'browse' page. Both of them returns an empty array every time. 
Please lest me know if I'm missing something

**Comment by iamlogiq** [comment]
I just tested it in the console and I get the same thing...empty response

**Comment by iamlogiq** [comment]
Ok I fixed the issue by going on db configuration page in the orientdb studio and changing strictSql to false! 

@luigidellaquila Am I suppose to keep strictSql to false? Is it recommended?

**Comment by nagarajasr** [comment]
in my case, strictSql is set to true, and yet i don't see the issue. 
actually, if you notice, RC5 was released before the issue 4233 was fixed, so you probably need to wait another day or 2 for the RC6 release (or you could build from source)

**Comment by luigidellaquila** [comment]
@iamlogiq @nagarajasr yes, I think it's the case. I fixed it 22 days ago, but the RC5 was released 25 days ago...

**Comment by iamlogiq** [comment]
@nagarajasr @luigidellaquila Thanks guys. For now I'll keep strictSql to false and wait for the next release.

**Comment by luigidellaquila** [comment]
Ok, thanks, let me know if it's fixed for you too
