### ISSUE TITLE
Feature request: Unix socket support 

### ISSUE THREAD

**Issue by tommys-place** [orientechnologies/orientdb#4659]
Hi, 

Do you have a plan to include unix socket support?
I think, it would be great for in-memory and dockerized versions with shared socket instead of linked containers.

I was playing with this option and created  unix socket factory for OrientDB which uses Java JNA.
Here's the working sample https://github.com/tommys-place/orientdb_unixsocket_driver with instructions how to install and use with OrientJS from NodeJS.

What do you think?!

**Comment by lvca** [comment]
@tommys-place nice contribution! What dependencies does it need?

**Comment by tommys-place** [comment]
Thx,

Only jna.jar lib, but it is already included in OrientDB lib. So, in IDE is enough to include jars from OrientDB/lib. THere is no additional libs.

**Comment by lvca** [comment]
@tommys-place So we could also support this in the core, right? WDYT about creating a Pull Request for "2.2.x" branch?

**Comment by tommys-place** [comment]
You can use it in the server mode. 

For Pull request, some parts are forks from other GitHub projects. Forks are listed under Credits at the end of Readme (all have Apache license) but reading terms and conditions for contributing at https://github.com/orientechnologies/orientdb/blob/master/CONTRIBUTING.md , maybe you will need clearance from them ?

**Comment by tommys-place** [comment]
Please see this link 
http://programmers.stackexchange.com/questions/56927/what-are-the-real-life-implications-for-an-apache-2-license

I was thinking, if those parts are under Apache 2.0, basically I can use it and modify it but have to keep their author names in code parts. So, possibly there is no problem?! I was not aware of possible license issue until I tried to made pull request.

**Comment by lvca** [comment]
Hi @tommys-place, if you can do the PR I can see the contributed files.

**Comment by tommys-place** [comment]
Hi,

It's done here... https://github.com/kohlschutter/junixsocket/issues/17 
I will wait him for review and comments before making pull request here.

Stay tuned :)

**Comment by lvca** [comment]
Cool, thanks.

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
