### ISSUE TITLE
REQUEST_TX_COMMIT returns same RIDs in created and updated record list

### ISSUE THREAD

**Issue by whatyouhide** [orientechnologies/orientdb#4660]
When I create a record in a `REQUEST_TX_COMMIT` operation and the record gets created with a version > 0, then the generated RID of the new record appears in both the "created" and "updated" list in the response.

For example, if I create a record like this:

```
{
  rid: #-1:-2,
  fields: {a: 1},
}
```

the response of `REQUEST_TX_COMMIT` will be something like:

```
1,      // count of created records
#-1:-2, // client rid
#9:0,   // server rid
1,      // count of updated records
#-1:-2, // server rid
1,      // version
...
```

/cc @tglman

**Comment by tglman** [comment]
to solve this, i need to update the protocol or unsure that the create has every time version 0 as result, i'll check the version force as first solution so it will avoid to change the binary protocol

**Comment by tglman** [comment]
with this commit:https://github.com/orientechnologies/orientdb/commit/def2c06b3aa05ad464a766aa8076bb6774c2c486  the version of new record will start from 0, so will no sent anymore an update as result of create, closing.

**Comment by whatyouhide** [comment]
Great @tglman, we'll get this in 2.1 right?

**Comment by tglman** [comment]
yes
