### ISSUE TITLE
ODatabaseDocumentTx and activateOnCurrentThread

### ISSUE THREAD

**Issue by crmayer** [orientechnologies/orientdb#4664]
Topic OrientDB and multi-threading
OrientDB Version: 2.0.13
Trying to comply with: https://orientdb.com/docs/last/Java-Multi-Threading.html
Problem:
cannot find method 
    *activateOnCurrentThread*
in
    public class *ODatabaseDocumentTx* extends OListenerManger<ODatabaseListener> implements ODatabaseDocumentInternal 

Am I on the wrong page?
Thank you

**Comment by luigidellaquila** [comment]
Hi @crmayer 

that docs page refers to 2.1 (it should be more explicit, I'm going to fix it).
In 2.0.13 you can use db.setCurrentDatabaseInThreadLocal() instead

**Comment by crmayer** [comment]
Thank you.
