### ISSUE TITLE
Fetchplan filters out record attributes when excluding Incoming and outgoing edges

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#4665]
Hi,

There's a lot of fetchplan issues opened at the moment already, but not sure which this one should relate to. Therefore I opened a new one. I am on **OrientDB 2.0.12** at the moment. Basically,

```sql
create class Test extends V
insert into Test content {"attr1": "value 1", "attr2": "value 2"}
```

and then

```sql
select @this.toJson('fetchPlan:in_*:-2 out_*:-2') from Test 
```

yields

```json
{"attr1":"value 1","attr2":"value 2"}
```

Where are `@rid`, `@version`, etc gone? Because doing

```sql
select @this.toJson() from Test 
```

gives you the full set

```json
{"@type":"d","@rid":"#90:0","@version":1,"@class":"Test","attr1":"value 1","attr2":"value 2"}
```

**Comment by nagarajasr** [comment]
use this if you want to fetch the rid and version in addition to the fetchPlan fields using toJSON()

```
select @this.toJson('rid,version,fetchPlan:in_*:-2 out_*:-2') from Test
```

**Comment by andreyvk** [comment]
That's neat. Thanks @nagarajasr

**Comment by nagarajasr** [comment]
@andreyvk if your issue is resolved would you mind closing this issue, IMO it is working as designed.

**Comment by andreyvk** [comment]
@nagarajasr: @Ivca added this as a milestone for the upcoming version. Besides, I don't think I have any rights to close issues on this project.

**Comment by tglman** [comment]
There is a way to solve it, i'm closing
