### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by compensator** [orientechnologies/orientdb#4671]
In many cases where the phrase "major than" is used in the new 2.1 documentation, the phrase "greater than" should be used instead.

**Comment by nagarajasr** [comment]
fixed in orientdb-docs repository following files:

Gephi.md
Key-Value-use-case.md
Network-Binary-Protocol.md
OrientDB-REST.md
Partitioned-Graphs.md

**Comment by lvca** [comment]
Thanks @compensator or the reporting and @nagarajasr for closing it.
