### ISSUE TITLE
ORIENTDB WORKBENCH -  ENTERPRISE EDITION - Not started if user enter incorrect port number.

### ISSUE THREAD

**Issue by shlapkov** [orientechnologies/orientdb#4677]
Issue related to: http://www.prjhub.com/#/issues/4842
Start server 2.0.13
Edit ORIENTDB WORKBENCH bat file as in: 4842
Start ORIENTDB WORKBENCH
Enter new server: localhost
Stop ORIENTDB WORKBENCH
Try to start again notice:

************************************************
*   ORIENTDB WORKBENCH -  ENTERPRISE EDITION   *
*                                              *
* Copyrights (c) 2014 Orient Technologies LTD  *
************************************************
* Version...: 2.0.3                            *
************************************************

To open the Web Console open your browser to the URL: http://152.144.22.157:2491 and use 'admin' as
user and password to log in, unless you already changed it.

Exception in thread "Timer-0" com.orientechnologies.orient.core.exception.OSerializationException: E
rror on unmarshalling JSON content '<html><body>This site is running <a href='http://www.TeamViewer.
com'>TeamViewer</a>.<br /><br />
   Free Port 80 for other applications in advanced settings.</body></html>': content must be between
 { }
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerialize
rJSON.unwrapSource(ORecordSerializerJSON.java:399)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerialize
rJSON.fromString(ORecordSerializerJSON.java:173)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerialize
rJSON.fromString(ORecordSerializerJSON.java:169)
        at com.orientechnologies.orient.core.record.ORecordAbstract.fromJSON(ORecordAbstract.java:17
1)
        at com.orientechnologies.orient.core.record.impl.ODocument.fromJSON(ODocument.java:1653)
        at com.orientechnologies.workbench.ORealtimeMetric.fetch(ORealtimeMetric.java:62)
        at com.orientechnologies.workbench.ORealtimeMetric.fetch(ORealtimeMetric.java:48)
        at com.orientechnologies.workbench.OWorkbenchRealtimeTask.run(OWorkbenchRealtimeTask.java:24
)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Error on client connection
java.lang.ExceptionInInitializerError
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Caused by: java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:397)
        at java.util.Timer.schedule(Timer.java:248)
        at com.orientechnologies.orient.core.Orient.scheduleTask(Orient.java:332)
        at com.orientechnologies.orient.server.OClientConnectionManager.<init>(OClientConnectionMana
ger.java:58)
        at com.orientechnologies.orient.server.OClientConnectionManager.<clinit>(OClientConnectionMa
nager.java:51)
        ... 1 more
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)

**Comment by lvca** [comment]
@shlapkov I don't understand the issue. Did you configure Workbench to work with TeamViewer?

**Comment by maggiolo00** [comment]
hi @shlapkov how can i reproduce this issue?

**Comment by jillray7** [comment]
@shlapkov Are you saying that you put the incorrect port (80) here? 

Server url: localhost:2480
Login/pass: root/root

**Comment by shlapkov** [comment]
Steps are in the ticket copy/paste one more time: 1. Start ORIENTDB WORKBENCH Enter new server: localhost 2. Stop ORIENTDB WORKBENCH 3. Try to start again.

**Comment by maggiolo00** [comment]
which port did you set for the new server at localhost?

**Comment by shlapkov** [comment]
no ports just "locahost" name "admin", password "admin" click "Test" you will see "Success" but it will never work after this. In fact second tie will not even start. We can't provided feature with such defects to our customers. Please run QA against UI before publish it.

**Comment by maggiolo00** [comment]
@shlapkov  the port is required and if you use the wrong port you should get connection refused

**Comment by maggiolo00** [comment]
I tried without setting the port and i got 'No Connection' in Test
and if i saved i got Server status offline with log connection refused

**Comment by jillray7** [comment]
@shlapkov Please provide us screenshots or whatever information you have to help us recreate the issue.

**Comment by shlapkov** [comment]
Please have look on file in: https://github.com/shlapkov/OrientIssues/tree/master/Workbench-issues
Step#1: https://github.com/shlapkov/OrientIssues/blob/master/Workbench-issues/WorkBenchIssue.PNG
Step#2: https://github.com/shlapkov/OrientIssues/blob/master/Workbench-issues/WorkBenchIssue-001.PNG
Step#3: https://github.com/shlapkov/OrientIssues/blob/master/Workbench-issues/WorkBenchIssue-003.PNG, https://github.com/shlapkov/OrientIssues/blob/master/Workbench-issues/WorkBenchIssue-004.PNG

Broken database: https://github.com/shlapkov/OrientIssues/tree/master/Workbench-issues/monitor

**Comment by maggiolo00** [comment]
Yeah that because you didn't set the port and it uses the http default that is 80. And i think you have
TeamViewer running on 80 on the same machine.

**Comment by jillray7** [comment]
@maggiolo00 @lvca @shlapkov understands that he should have put in the proper port. However, should user error result in a broken database? Should another check be built in? Is the only way to fix the database to revert to a backup?

**Comment by shlapkov** [comment]
at very least "Test" button should not show: https://github.com/shlapkov/OrientIssues/blob/master/Workbench-issues/WorkBenchIssue-001.PNG and allow save the connections

**Comment by jillray7** [comment]
@maggiolo00 @lvca Guys, what's your response to the two comments above?

**Comment by wolfwood18** [comment]
The problem is that @shlapkov has teamviewer on the port 80 and the test seems ok because when the connection is tested Workbench does a get to http://server:port/server to see if ODB is alive. And in his case the response is ok. We do not check the response it self. We will add another check to ensure that is ODB behind  that address

**Comment by jillray7** [comment]
thanks @wolfwood18 that makes sense to me. @shlapkov Does this satisfy your requirement for additional error checking?

**Comment by shlapkov** [comment]
Yes

**Comment by jillray7** [comment]
@shlapkov Thank you!

**Comment by shlapkov** [comment]
no problem

**Comment by jillray7** [comment]
@wolfwood18 Did you already build in the extra check for the OrientDB behind the port?

**Comment by maggiolo00** [comment]
the fix is done in 2.1 and backported in 2.0.x

**Comment by jillray7** [comment]
@maggiolo00 Fantastic! Thanks!
