### ISSUE TITLE
 two different results when I use different methods inserts the same record

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#4680]
Hi
I use OrientDB Server v2.0.13

#### insert into test set list = ["","center",""]
and
#### insert into test content {"list": ["","center",""]}

orientdb {db=test}> create class test extends V
Class created successfully. Total classes in database now: 12

orientdb {db=test}> create property test.list EMBEDDEDLIST
Property created successfully with id=1

orientdb {db=test}> alter property test.list linkedType  STRING
Property updated successfully

orientdb {db=test}> insert into test set list = ["","center",""]
Inserted record 'test#12:0{list:[3]} v1' in 0,009000 sec(s).

orientdb {db=test}> select list.size() from #12:0
----+------+----
\#   | @ CLASS|list
----+------+----
0   |null  |3
----+------+----
1 item(s) found. Query executed in 0.002 sec(s).

orientdb {db=test}> insert into test content {"list": ["","center",""]}
Inserted record 'test#12:1{list:[1]} v1' in 0,001000 sec(s).

orientdb {db=test}> select list.size() from #12:1
----+------+----
\#   | @ CLASS|list
----+------+----
0   |null  |1
----+------+----
1 item(s) found. Query executed in 0.001 sec(s).

In the first case the length of array = 3
and in the second case, the length of array = 1

__but if I insert null instead empty string results are the same__

orientdb {db=test}> insert into test set list = [null,"center",null]
Inserted record 'test#12:3{list:[3]} v1' in 0,003000 sec(s).

orientdb {db=test}> select list.size() from #12:3
----+------+----
\#   | @ CLASS|list
----+------+----
0   |null  |3
----+------+----
1 item(s) found. Query executed in 0.004 sec(s).

orientdb {db=test}> insert into test content {"list": [null,"center",null]}
Inserted record 'test#12:2{list:[3]} v1' in 0,003000 sec(s).

orientdb {db=test}> select list.size() from #12:2
----+------+----
\#   | @ CLASS|list
----+------+----
0   |null  |3
----+------+----
1 item(s) found. Query executed in 0.002 sec(s).

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

the problem seems to be at insert time, not at query time. It seems that the CONTENT does not take into consideration empty strings. It's definitely a bug, I'm investigating it.

Thanks

**Comment by luigidellaquila** [comment]
fixed in develop branch, back porting to 2.0.x

**Comment by luigidellaquila** [comment]
fixed also on branch 2.0.x
Closing
