### ISSUE TITLE
NPE utilizing date() function

### ISSUE THREAD

**Issue by kr8670** [orientechnologies/orientdb#4683]
I used to be able to do something like

    select date('2015-07-20', 'yyyy-MM-dd').format('dd.MM.yyyy')

With latest versions it NPE's apparently with result of date() function.
Not sure when this stopped working, but I have a snapshot from mid june where it still works.

**Comment by luigidellaquila** [comment]
Fixed in both 2.1.x branch (next 2.1.18) and develop (next 2.1.1) 

Closing, please reopen if you see any related problems

Thanks

Luigi
