### ISSUE TITLE
Want to setup the second clustured setup of orientDB in the same network

### ISSUE THREAD

**Issue by ManjunathMuniyapla** [orientechnologies/orientdb#4685]
Hi Guys, 

I have already one set of working orient DB Cluster setup, (say A, B & C) 
i want to have the second clustered orientDB setup in the same network. (say X, Y & Z)
while running the first node (X) of second setup in the distributed mode (from bin/dserver.sh) it is not asking for any node name , instead of that it is joining the pool of first Cluster and now my first Cluster has become the pool of (A, B, C & D).

Can you please help me in resolving this issue & help in setting up the second cluster of nodes (X, Y & Z)
I am using the OrientDB version 2.0.11

Thanks in Advance,
Manjunath

**Comment by luigidellaquila** [comment]
Hi Manjunath,

To do this you have to:
- edit /config/hazelcast.xml and change group name and password for the second group (to join a cluster, a node has to share the same group name and password)
- edit /config/orientdb-server-config.xml and remove "nodeName" parameter from OHazelcastPlugin handler, this will allow the server to ask you the node name again.

It's not actually an issue, but more a question/request for help. Please use OrientDB community mailing list for this kind of requests https://groups.google.com/forum/#!forum/orient-database

**Comment by luigidellaquila** [comment]
Hi Manjunath,

I just answered to this in the issue tracker, cutting-pasting the comment
here:

To do this you have to:

   - edit /config/hazelcast.xml and change group name and password for the
   second group (to join a cluster, a node has to share the same group name
   and password)
   - edit /config/orientdb-server-config.xml and remove "nodeName"
   parameter from OHazelcastPlugin handler, this will allow the server to ask
   you the node name again.

Thanks

Luigi


2015-07-30 13:17 GMT+02:00 ManjunathMuniyapla <notifications@github.com>:

**Comment by ManjunathMuniyapla** [comment]
Thanks a lot luigidellaquila. 
Let me try this
