### ISSUE TITLE
Studio "Graph" view should have option to change LIMIT

### ISSUE THREAD

**Issue by isturlic** [orientechnologies/orientdb#4687]
Hi,

When I'm working in Studio "Browse" page I have option to change limit from default 20 but if I run the query from "Graph" page, limit is 20 and there is no option to change it.
Workaround is to enter query in "Browse" tab and then select "Send to graph".
It would be nice to have global setting for LIMIT which would also persist page reload.

OrientDB 2.1. rc-5
OrientDB Studio 2.0

**Comment by maggiolo00** [comment]
hi @isturlic 
Implemented
