### ISSUE TITLE
Concurrent server access problem!

### ISSUE THREAD

**Issue by michaelph** [orientechnologies/orientdb#4688]
Hi all, we began to using Orientdb in our small software company to support graph operations in several domains. We were very excited with the performance and natural way to do things, but... After designing our database, create one custom function at server side and try to access via REST API, we had a concurrency problem.
Here is our scenario:
We created a custom dijkstra function, basically taking as a reference the one that come with the distribution in such a way that consider just some edges and not all of them. So we can gain some milliseconds. It Works! Then we created a command into the server to have RESTful access to our Dijkstra function .
First we access the server in a sequential manner, everything went right and fast.
Finally we try with some concurrent clients to access the server and the results were chaotic.
The official documentation mention that: "instances are not thread-safe, so you've to get an instance per thread and each database instance can be used only in one thread per time." Is this true even for read access? If yes it is a critical problem for us.  Is there a way to resolve this?
Thanks

**Comment by luigidellaquila** [comment]
Hi @michaelph 

concurrent usage of the same db connection on multiple threads should be avoided also for read operations. Could you please share some additional details about your use case? How many concurrent connections do you have? Also a full stack trace and the code of your function would help a lot.
In general, having a simple connection pool solves the problem.
Please let me know if you need further help, just please move this discussion on the official OrientDB community group (https://groups.google.com/forum/#!forum/orient-database), as it's not properly an issue

Thanks
