### ISSUE TITLE
Inline query only seems to operate on first result

### ISSUE THREAD

**Issue by neRok00** [orientechnologies/orientdb#4692]
Whilst working on a query here: http://stackoverflow.com/a/31737571/3800244, I tried the following WHERE clause on the query.

```
WHERE (SELECT expand(in('Child')) from #11:3) CONTAINSALL (@rid in $current.in_Child)
```

This inline query only seemed to check the first result in the CONTAINSALL expression, and I was getting incorrect results. By adding a LET clause and changing the WHERE clause to the one following, all records from inline query were properly compared in the CONTAINSALL expression, and I got the expected results.

```
LET $parents = (SELECT expand(in('Child')) from #11:3)
WHERE $parents CONTAINSALL (@rid in $current.in_Child)
```

**Comment by luigidellaquila** [comment]
This is fixed in v 3.0 with the new SQL executor

Closing, thanks

Luigi
