### ISSUE TITLE
Tinkerpop Frames Created Vertex @class = null in SQL Query

### ISSUE THREAD

**Issue by compensator** [orientechnologies/orientdb#4695]
Example Person object

```java
public interface Person extends VertexFrame
{
    @Property("id")
    public String getId();
    @Property("id")
    public void setId(String id);

    @Property("email")
    public String getEmail();
    @Property("email")
    public void setEmail(String email);

    @Property("firstName")
    public String getFirstName();
    @Property("firstName")
    public void setFirstName(String firstName);

    @Property("lastName")
    public String getLastName();
    @Property("lastName")
    public void setLastName(String lastName);

    @Property("dob")
    public String getDOB();
    @Property("dob")
    public void setDOB(String dob);
}
```

```java
    private static Person addPersonVertex(FramedTransactionalGraph<OrientTransactionalGraph> ftg, String firstName, String lastName, String email, String dob)
    {
        // Add null check and try/catch/ftg.rollback()  - Appending UUID recommended by Luca G. on
        // StackOverflow
        Person person = ftg.addVertex("class:Person," + UUID.randomUUID(), Person.class);

        if (null != person)
        {
            person.setFirstName(firstName);
            person.setLastName(lastName);
            person.setEmail(email);
            person.setEmail(dob);

            OrientVertex vPerson = (OrientVertex) person.asVertex();

            vPerson.save();

            ftg.commit();

            if (verbose)
                System.out.println("Created Vertex: " + vPerson.toString());
        }
        return person;
    }
```

Select * from Person shows @class is Person.

Select firstName from Person shows @class is null.

CREATE INDEX Person.firstName throws the following Exception:

com.orientechnologies.orient.core.index.OIndexException: Index with name : 'Person.firstName' cannot be created on class : 'Person' because field: 'firstName' is absent in class definition. 

Is this a bug or because of the recommendation to add UUID to the addVertex method call?

**Comment by compensator** [comment]
@lvca Any word on this one?  I regenerated the graph without the UUID in the class name, but it still returns a null for @class in the above stated SELECT statement.

**Comment by zifnab87** [comment]
I have a question why ```Select firstName from Person``` would return ```@class``` in any case?

**Comment by compensator** [comment]
The problem arose from a different direction.  I attempted to create an index on firstName and the database stated that Person doesn't have a "firstName" field.  Since I see @class and class when I execute a "select *", I decided to execute "select firstName".  The output in the console shows "null" for @class in the output along with the rid (without the cluster id).  I can't answer for why Orient decided to have the database return "rid, @class, property/field value", but they do, and it gave me a clue.  I'd two weeks ago that Tinkerpop Frames interfacing with OrientDB doesn't result in proper management of classes:  https://groups.google.com/forum/#!topic/orient-database/FMAb4sxnA_U

**Comment by compensator** [comment]
Since submitting this Issue, I recreated the database and reloaded data where UUID is not appended as such:  ```java ftg.addVertex("class:Person", Person.class);```

I still get:
```java
com.orientechnologies.orient.core.index.OIndexException: Index with name : 'Person.firstName' cannot be created on class : 'Person' because field: 'firstName' is absent in class definition. ```

**Comment by zifnab87** [comment]
@compensator it is not very clear to me but fields and properties are different. It could be that you need to have those in your schema.. do you have them there? It could be that schema has properties so you can just ignore what I said..

**Comment by compensator** [comment]
I'm evaluating and learning the product under a tight timeline, so at times, I throw in a test of a feature while waiting on a test to complete.  I therefore attempted this without thorough reading.  I just reviewed the documentation again and tested the following command:
```sql
CREATE INDEX PersonIndex ON Person (firstName, middleName, lastName, dob) FULLTEXT METADATA {ignoreNullValues : false}
```
I still receive the Exception stating that the field doesn't exist.  It is my current belief that since I created the objects using Tinkerpop Frames, OrientDB is not adding the Interface properties to the schema at the time of creation.  It would make sense that it adds the properties to the schema given the @Property annotation, but apparently not.

## Syntax
```sql
CREATE INDEX <name> [ON <class-name> (prop-names)] <type> [<key-type>]
             METADATA [{<json-metadata>}]
```
Where:

- **name** logical name of index. Can be **<code>&lt;class&gt;.&lt;property&gt;</code>** to create an automatic index bound to a schema property. In this case **class** is the class of the schema and **property**, is the property created into the class. Notice that in another case index name can't contain '.' symbol
- **class-name** name of class that automatic index created for. Class with such name must already exist in database
- **prop-names** comma-separated list of properties that this automatic index is created for. Property with such name must already exist in schema. If property belongs to one of the Map types (LINKMAP, EMBEDDEDMAP) you can specify will be keys or values used for index generation. Use "by key" or "by value" expressions for that, if nothing will be specified keys will be used during index creation.
- **type**, between 'unique', 'notunique' and 'fulltext'
- **key-type**, is the type of key (Optional). On automatic indexes is auto-determined by reading the target schema property where the index is created. If not specified for manual indexes, at run-time during the first insertion the type will be auto determined by reading the type of the class. In case of creation composite index it is a comma separated list of types.
- **metadata** is a json representing all the additional metadata as key/value

If "**ON**" and **key-type** sections both exist database validate types of specified properties. And if types of properties not equals to types specified in **key-type** list, exception will be thrown.

List of key types can be used for creation manual composite indexes, but such indexes don't have fully support yet.


## See also
- [SQL Drop Index](SQL-Drop-Index.md)
- [Indexes](Indexes.md)
- [SQL commands](SQL.md)

## Examples

### Examples of non-automatic index to store dates manually:
```sql
CREATE INDEX mostRecentRecords unique date
```

### Examples of automatic index bound to the property "id" of class "User":
```sql
CREATE PROPERTY User.id BINARY
CREATE INDEX User.id UNIQUE
```

### Examples of index for "thumbs" property of class "Movie".
```sql
CREATE INDEX thumbsAuthor ON Movie (thumbs) UNIQUE;
CREATE INDEX thumbsAuthor ON Movie (thumbs BY KEY) UNIQUE;
CREATE INDEX thumbsValue ON Movie (thumbs BY VALUE) UNIQUE;
```

### Composite index example:
```sql
CREATE PROPERTY Book.author STRING
CREATE PROPERTY Book.title STRING
CREATE PROPERTY Book.publicationYears EMBEDDEDLIST INTEGER
CREATE INDEX books ON Book (author, title, publicationYears) UNIQUE
```

**Comment by lvca** [comment]
@compensator As fa as I know this isn't supported. Even if it's straightforward, the synch of properties is still an open issue.

**Comment by compensator** [comment]
Yes.  I'll likely be implementing a reflection-based solution.
