### ISSUE TITLE
search index in EMBEDDEDLIST doesn't work

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#4697]
Hi
I use OrientDB Server v2.0.13

#### Although the result is

orientdb {db=test}> create class test extends V
Class created successfully. Total classes in database now: 13

orientdb {db=test}> create property test.list embeddedlist
Property created successfully with id=1

orientdb {db=test}> ALTER PROPERTY test.list LINKEDTYPE STRING
Property updated successfully

orientdb {db=test}> create index  test.list on test (list) unique
Creating index...
Created index successfully with 0 entries in 0,042000 sec(s).

orientdb {db=test}> insert into test set list = ['one','two']
Inserted record 'test#13:0{list:[2]} v1' in 0,010000 sec(s).

orientdb {db=test}> insert into test set list = ['three']
Inserted record 'test#13:1{list:[1]} v1' in 0,006000 sec(s).

orientdb {db=test}> select from index:test.list
----+------+-----+-----
\#   | @ CLASS|key  |rid
----+------+-----+-----
0   |null  |one  |#13:0
1   |null  |three|#13:1
2   |null  |two  |#13:0
----+------+-----+-----
3 item(s) found. Query executed in 0.014 sec(s).

orientdb {db=test}> select from index:test.list where key = 'one'
**0 item(s) found. Query executed in 0.002 sec(s).**

orientdb {db=test}> select from index:test.list where key = 'three'
**0 item(s) found. Query executed in 0.002 sec(s).**

**Comment by nagarajasr** [comment]
this works:

```sql

 select from (select from index:test.list) where key='one'

```

**Comment by Ivanov-Yuriy** [comment]
thank you
simple when field has type string, I can get index use single query

orientdb {db=test}> select from index:test.string where key = 'qwe'
----+------+----+-----
\#   | @ CLASS|key |rid
----+------+----+-----
0   |null  |qwe |#13:1
----+------+----+-----
1 item(s) found. Query executed in 0.002 sec(s).

**Comment by a-unite** [comment]
@nagarajasr, it is definitely should work since `select from index:test.list` works. 
I understand your message was for test purpose only, because there is no obvious reasons to use index for embedded lists then (except when full scan over index might take less IO operation comparing to 'natural' scan), I think. 
Notice that `notunique` index over embeddedlist field has the same problem.

**Comment by nagarajasr** [comment]
yes, i agree that there is an inconsistency in the behaviour between index on string property and index on embeddedlist, when using the special index:index_name query target.

while trying out a few queries related to this issue, i made some further observations which may be of help:

```sql
orientdb {db=t12db}> insert into test set list = ['one','two']

Inserted record 'test#11:0{list:[2]} v1' in 0.185000 sec(s).

orientdb {db=t12db}> insert into test set list = ['one','two']

Error: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record test{list:[2]}: found duplicated key 'two' in index 'test.list' previously assigned to the record #11:0 RID=#11:0

orientdb {db=t12db}> insert into test set list = ['one','two', 'three']

Error: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record test{list:[3]}: found duplicated key 'two' in index 'test.list' previously assigned to the record #11:0 RID=#11:0

orientdb {db=t12db}> insert into test set list = ['one']

Error: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record test{list:[1]}: found duplicated key 'one' in index 'test.list' previously assigned to the record #11:0 RID=#11:0

orientdb {db=t12db}> insert into test set list = ['two','one']

Error: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record test{list:[2]}: found duplicated key 'two' in index 'test.list' previously assigned to the record #11:0 RID=#11:0

```

i'm unclear what the behaviour of unique indexes should be in the case of embeddedlists. on the face of it is seems that the 3rd insert statement, with values ['one', 'two', 'three'] should be allowed, as it is technically 'not equal to' the list ['one', 'two']. likewise, the last insert statement with values ['two','one'] should also have been allowed as this is an embeddedlist, not an embeddedset (which is unordered).

**Comment by laa** [comment]
Hi, that is output from 2.2 version https://gist.github.com/laa/387557a542846d984af44b6eaf80428f .
According to this output, I tread bug as fixed.
