### ISSUE TITLE
help command should display extended useful help

### ISSUE THREAD

**Issue by krichter722** [orientechnologies/orientdb#4699]
Currently it's interpreted as syntax error which sometimes (e.g. for `help connect`) displays rudimentary usage information, but this way isn't very reliable.

experienced with 2.1-rc6

**Comment by lvca** [comment]
What kind of information you'd like to receive by `help` command?

**Comment by krichter722** [comment]
e.g. how to connect to a database. Currently, invoking `help` displays nothing but `* connect <url> <user> <password>                                       Connect to a database or a remote Server instance`. There's e.g. no info about modes, how to specify a port different from the default port in URL.

**Comment by lvca** [comment]
I agree we could improve the help by providing the information contained on the web site.

**Comment by lvca** [comment]
Added also `help -online <cmd>` to fetch online content i available/online.
