### ISSUE TITLE
console suggest connect command which isn't working

### ISSUE THREAD

**Issue by krichter722** [orientechnologies/orientdb#4700]
After `connect [URL] [user] [password]` to and empty installation of 2.1-rc6, `browse class clazz` fails with 

    Error: com.orientechnologies.common.exception.OException: Database not selected. Use 'connect <database-name>' to connect to a database.

Running `connect GreatfulDeadConcerts` fails with 

    !Wrong syntax. If you're using a file make sure all commands are delimited by semicolon (;) or a linefeed (\n)
    
     Expected: connect <url> <user> [<password>] 
    
    Where:
    
    * url            The url of the remote server or the database to connect to in the format '<mode>:<path>'
    * user           User name      
    * password       User password  
    
    !Unrecognized command: 'connect GreatfulDeadConcerts'

That doesn't make sense.

**Comment by nagarajasr** [comment]
console commands are documented here:
http://orientdb.com/docs/last/Console-Command-Connect.html

**Comment by m0v0nage** [comment]
It's great that there are docs that show how to actually use the `connect` command, but the description of the `connect` command returned by this error is misleading. It leads new users to believe that they can switch to a different database on the same remote by just passing the name of the database to the `connect` command
