### ISSUE TITLE
Disable 'root' user 

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#4706]
As a security measure, I would like to disable the 'root' user completely.
Before starting up orient service for the first time, I set only one user, not root, in the config file.
However, orient creates a root user anyway, with a random password.

I noticed the use of root password is used as constant SRV_ROOT_ADMIN in OServerConfiguration.java, which is only used in OServerShutdownMain.java and OServer.java.

in OServer.java, it is only used to check if it's the first time the service is run. We can simply choose a place and use a boolean config, something like 'isFirstTime'. Seems to clarify the behavior too, in my opinion anyway.

in OServrShutdownMain.java , it is used to connect to a server. We can simply get a user argument from command line, much like the other arguments (and use 'root' as default user).

WDYT?

**Comment by nagarajasr** [comment]
:+1:

**Comment by lvca** [comment]
:+1

**Comment by lvca** [comment]
Merged, thanks @matanshukry

**Comment by tglman** [comment]
reopening due to revert for failing tests.

**Comment by tglman** [comment]
fixed now closing

**Comment by matanshukry** [comment]
Hi, this is a bit confusing;
as far as I can tell, you create PR to revert this issue, merged it, and then reverted the issue that reverted the issue. I'm not sure about it though.

Anyway, what is the problem? if you fixed it, what was it?

**Comment by tglman** [comment]
Hi @matanshukry,

Now is merged, the problem was that in the test suite the are many test that rely on the root password written in the xml, i fixed them adding in the configuration the flag for not ask the password.
