### ISSUE TITLE
bug: cannot remove edge using studio

### ISSUE THREAD

**Issue by swamikevala** [orientechnologies/orientdb#4707]
steps to reproduce:
1. create a new database
2. add Person class (subclass of V), define some properties
3. add Organization class (subclass of V), define some properties
4. create edge (E) between them
5. Try to remove edge using visual graph editor

message is displayed:
WARNING: You are removing Edge in_ from #12:0 to #13:0 . Are you sure?

Press OK

Then the following error message appears:
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Class 'UNDEFINED' was not found

version 2.1 rc6 (Windows)

**Comment by danawoodman** [comment]
Same problem for me on Mac using Chrome

**Comment by karensargsyan** [comment]
I'v got the same problem, can't remove edit edge.
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Class 'UNDEFINED' was not found
