### ISSUE TITLE
delayed replica

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#4711]
Provide the ability to have a replica that does not apply changes immediately, but that works with a delay, buffering changes as they arrive and applying them after a given amount of time.
It is very useful in case of wrong operations executed on the master database.

Also add a layer to stop the execution of the replica operations at a given operation (eg. have the list of pending operations and choose where to stop)

**Comment by lvca** [comment]
:+1

**Comment by lvca** [comment]
Duplicated of #5983.
