### ISSUE TITLE
Bitwise Operators

### ISSUE THREAD

**Issue by gregaubert** [orientechnologies/orientdb#4714]
Hi,
It would be great to have support for bitwise operators.

In the [SQL parser syntax](https://orientdb.com/docs/last/SQL-Syntax.html) page it seems that there is plan for it already  : 

```
| <BIT_AND: "&">
| <BIT_OR: "|">
| <XOR: "^">
```

But I couldn't find any issues or information about it ? Are you planning to support it ?

**Comment by nethertek** [comment]
We would like to see bitwise operators implemented as well.

**Comment by luigidellaquila** [comment]
Hi guys, 

Yes, the new parser already supports the syntax, but the underlying executor still lacks some components.
They will be implemented right after 2.2

**Comment by gongdo** [comment]
It's unbelievable that it's still not supported.
I made a custom function myself like this:
```
var op = operator.toLowerCase();
if (op == "and" || op == "&") {
  return left & right;
} else if (op == "or" || op == "|") {
  return left | right;
} else if (op == "xor" || op == "^") {
  return left ^ right;
}
throw "Unsupported bitwise operator.";
```

SQL statement will be:
```
CREATE FUNCTION bitwise "var op = operator.toLowerCase();\nif (op == \"and\" || op == \"&\") {\n  return left & right;\n} else if (op == \"or\" || op == \"|\") {\n  return left | right;\n} else if (op == \"xor\" || op == \"^\") {\n  return left ^ right;\n}\nthrow \"Unsupported bitwise operator.\";" PARAMETERS [operator,left,right] IDEMPOTENT true LANGUAGE javascript
```

And usages are:
```
SELECT FROM Something WHERE bitwise('and', flags, 6) = 6
SELECT FROM Something WHERE bitwise('&', flags, 3) > 0
SELECT FROM Something WHERE bitwise('or', flags, 2) = 3
SELECT FROM Something WHERE bitwise('xor', flags, 1) = 2
```

It's inefficient obviously. Can I get another work-around maybe?

**Comment by luigidellaquila** [comment]
I know guys, it's in my TODO list, the parser is ready to support it, but the executor still doesn't.

**Comment by rdelangh** [comment]
@luigidellaquila 
hi Luigi, any news for this functionality ? Is there some version planned in which the functionality will be present ?
thx for all the good works!

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

it is scheduled for 3.0

Thanks

Luigi

**Comment by luigidellaquila** [comment]
It's already implemented in v 3.0.0 M2 and will be released with the GA

Docs here http://orientdb.com/docs/3.0.x/sql/SQL-Syntax.html

Thanks

Luigi

**Comment by grzegorz-aniol** [comment]
I think on 3.0.9 bitwise AND seems to doesn't work when the value is return from a function.

`select @rid,
	mode, 						/* mode = 42755 */
	octet2dec(mode),			/* 17901 */
	octet2dec(mode) & 0170000,  /* is 17901 but shoud be 16384 */
        $a,
        $b
from Stat 
    let $a = octet2dec(mode),
    $b = $a & 0170000
limit 10`


![image](https://user-images.githubusercontent.com/22835413/48543760-763feb00-e8c2-11e8-83e4-3f31301d8c7f.png)

**Comment by grzegorz-aniol** [comment]
Here is the body function. (x is argument)  
```
return parseInt(x, 8);
```

Anyway I did my workaround and I created by custom function that calculates bitwise AND.
