### ISSUE TITLE
2.1 Documentation: "clusters" command

### ISSUE THREAD

**Issue by hho** [orientechnologies/orientdb#4716]
I'm new to OrientDB and currently working through the "Getting Started" part of the manual. On the [Clusters-Page](http://orientdb.com/docs/2.1/Tutorial-Clusters.html) it says
> To view all clusters, from the console run the CLUSTERS command

But the console doesn't know about `CLUSTERS`:
> !Unrecognized command: 'CLUSTERS'

Instead, the command is available in lowercase (`clusters`).
The [2.0-Version of the tutorial](http://orientdb.com/docs/2.0/orientdb.wiki/Tutorial-Clusters.html) was correct.

**Comment by lvca** [comment]
Thanks, fixed. The command would be "list clusters". "clusters" was an old name now works as alias
