### ISSUE TITLE
Shortest Path issue with single-edged path

### ISSUE THREAD

**Issue by azukaar** [orientechnologies/orientdb#4723]
Hello ! 

**EDIT** : OK I figured the problem out, ShortestPath doesn't return any path with length of one, I think this is wrong (but it's only up to me to think that), but at least it should be better documented because it's really misleading.There is still a typo in the doc (see PS of this post).

So I have this request :
![capture2](https://cloud.githubusercontent.com/assets/7872597/9060460/669fb3ca-3ab4-11e5-8d1c-92cd6097f9ff.PNG)

But if you look at my schema in DB : 
![capture1](https://cloud.githubusercontent.com/assets/7872597/9060468/74705c7a-3ab4-11e5-967c-bc4634deed63.PNG)

You can clearly see something is wrong here.
Own is a property-less Edge, whereas Shared is not (Using defaut behavior on LightweightEdges, I guess only Own is Lightweight in this case).
That said, I tried to add a property to Own so it become a self-existing entry in DB, but it didn't seem to work neither.
![capture3](https://cloud.githubusercontent.com/assets/7872597/9060493/c9aec622-3ab4-11e5-8bc0-4e80805ba32b.PNG)

![capture4](https://cloud.githubusercontent.com/assets/7872597/9082730/15df42c2-3b66-11e5-93df-5eaced0a866f.PNG)

Is it me doing something wrong ?

P.S.  :  Also, there's a problem in the doc, it says "Returns the shortest path between two vertices. Direction can be OUT (default), IN or BOTH." But default value is BOTH not OUT (as stated 5 lines later in "direction, optional, is the direction of traversing. By default is "BOTH" (in+out).")

Thanks for help !

**Comment by azukaar** [comment]
Should I mention that ShortestPath IS able to find the actual shortest path : 
![capture4](https://cloud.githubusercontent.com/assets/7872597/9082409/163ace5a-3b64-11e5-9c6f-f5de0524dc5b.PNG)

**Comment by lvca** [comment]
By watching your graph there is something wrong. Seems shortestPath() doesn't use lightweight edges? Do you have a database to share that shows the problem? It would make this fix much faster.
