### ISSUE TITLE
2.1 -> 2.0 metadata backwards incompatible? 

### ISSUE THREAD

**Issue by ryan-stateless** [orientechnologies/orientdb#4724]
I have been adding custom metadata (properties prefixed by @) to my classes in 2.0.12
However, when I try to do so (via REST api) in 2.1, I receive the following error:

create property V.@some_property string

{
  "errors": [{
      "code": 500,
      "reason": 500,
      "content": "com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered \"\" at line 1, column 32.\u000aWas expecting one of:\u000a    "
      }
  ]
}

Is this a bug, or do I need to rewrite my application to track custom metadata in some other way?

**Comment by luigidellaquila** [comment]
Hi @ryan-stateless 

In latest stable version, properties that contain special characters have to be back-tick quotes, eg.

```
create property V.`@some_property` string
```

I'm closing this issue, please reopen if you need further clarifications

Thanks

Luigi
