### ISSUE TITLE
Query functions over collections [+using field aliases]

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#4725]
When running the following query:

`SELECT id, name, In(Friend).name as friend_name, In(Friend).name.append(" Test
") as friend_name_test FROM User where id=1`

The result is:

```
[{"@type":"d","@rid":"#-2:0","@version":0,"id":1,"name":"Don Kingsly","friend_name":["","Samantha Bensly"],"friend_name_test":"[, Samantha Bensly] Test","@fieldTypes":"id=l"}]
```

As you can see, the field 'friend_name_test' is a single value string, which is probably the collection .toString(), and concat "test". The intention, although, was to use .append() on every item in the collection.

Also, since on the subject, would be nice if I could refer to aliases fields, so that the query above would become:
`SELECT id, name, In(Friend).name as friend_name, friend_name.append(" Test") a
s friend_name_test FROM User where id=1`
(The result of this doesn't include any friend_name_test fields, I'm guessing since it doesn't recognize the friend_name).

In my opinion, any function over a collection should apply to each item in the collection.
If one wants to use the entire collection, he may use .toString() or .size(), and then what he wants.

Your opinions?

**Comment by matanshukry** [comment]
Took the initiative and started implementing it (hopefully I didn't do it for nothing, and it's not implemented yet and I just missed it).

When doing so, I found it was problematic, since you couldn't choose between applying the function to each item in a collection, or to the collection as a whole.

As a result, I added an .each() method. That way, the following query should work:
```SELECT id, name, In(Friend).name as friend_name, In(Friend).name.each().append(" Test ") as friend_name_test FROM user where id=1```

So, what do you guys think?

**Comment by lvca** [comment]
Not relevant anymore. Closing it.
