### ISSUE TITLE
Can't Set Array Value using SQL

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#4727]
Attempting to set the value of an array via SQL does not work.  We are currently using the Document API from Java.  

Given the following document: 
```javascript
{
    "someArray": [
        10,
        20,
        30
    ]
}
```
The following query returns successful, but does nothing

```sql
UPDATE model SET someArray[1] = 25
```

The expected result is:

```javascript
{
    someArray: [
        10,
        25,
        30
    ]
}
```

The current work around requires loading the entire array and treading it as a OTrackedList which can then be manipulated and then set back as an entirely new value for "someValue".  This is not practical for large arrays.  The above example was greatly simplified.  The actual use case involves larger arrays that have large objects as their values.

Also, if two users were editing the data such that each was attempting to edit a different value in the array, the approach of getting the whole array, modifying it, and setting it back would create an artificial conflict where none really occurs.  

This issue was first discussed in the group here:

https://groups.google.com/forum/#!topic/orient-database/YCSyS7sQKTo

**Comment by mmacfadden** [comment]
To add more information, we came across another use case that makes this feature more important.  If one has nested arrays, then the amount of data that needs to be loaded is even more, and the efficientcy drops rapidly with the current functionality.

```javascript
{
    "array": [
        [
           10,
           20,
           30
        ],
        [
           "A",
           "B",
           "C"
        ]
    ]
}
```

What we would like to do is to update the 20 to be a 25.  If this was just a JSON node I would do the following:

```javascript
doc[0][1] = 25
```

Our current workaround for the original use case above was something to the effect of:

```Java
String queryString = "SELECT array FROM model";
OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>(queryString);
List<ODocument> result = db.command(query).execute(params);

OTrackedList<Object> array = result.get(0).field(FIELD_DATA);
array.set(1, 25);

String updateString = "UPDATE model SET array = :value ";
OCommandSQL updateCommand = new OCommandSQL(updateString);
params.put("value", array);
db.command(updateCommand).execute(params);    
```

This worked.  However, this work around DOES NOT work with nested arrays.  The path to the nested array is "array[0]".  Therefore the code would wind up looking like this:

```Java
String queryString = "SELECT array[0] FROM model";
OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>(queryString);
List<ODocument> result = db.command(query).execute(params);

OTrackedList<Object> array = result.get(0).field(FIELD_DATA);
array.set(1, 25);

String updateString = "UPDATE model SET array[0] = :value ";
OCommandSQL updateCommand = new OCommandSQL(updateString);
params.put("value", array);
db.command(updateCommand).execute(params);    
```

We are now immediately back to needing to set a value in an array.  So not only do we need to load the entire nested array, modify it an set if back, but now we must also load the entire parent (enclosing array) to set the modified nested array in it.  If one has a data structure composed of nested arrays (which is common when dealing with certain multi-dimensional structures), then one would need to recursively load all the data up to object structure.

A document of three levels of nest arrays, would require loading the entire document to change just one integer value in one of the lowest levels of arrays.

If there is another temporary workaround, that would be great.  Otherwise, just wanted to add some weight to this request.

**Comment by mmacfadden** [comment]
I am working on a Pull Request for this feature.  Since I have not contributed to this project before, I have signed a CLA and have read the docs on contributing.  I will be starting a PR on the develop branch shortly.

**Comment by mmacfadden** [comment]
It turns out that that issue is not with the Query Parser or SQL.  The SQL and Query parser handles this just fine.  The issues is actually in the ODocument class, when setting the value of a field.

If you have  a document that looks like this:

```javascript
{
  "data": {
    "array": [
      1,
      2,
      3
    ]
  }
}
```
And the rough JAva Code

```java
ODocument doc = new ODocument(...) // From JSON Above.
int valueAtZero = doc.field("data.array[0]");
System.out.println(valueAtZero);
```

This will print the correct value of 1.  The ODocument.field(String) method correctly parses the fields including the array subscript.  However, the version of field that is used to set (ODocument.field(String, Object)) does not properly parse this.  This rough code does not work.

```java
ODocument doc = new ODocument(...) // From JSON Above.
doc.field("data.array[0]", 5);
int valueAtZero = doc.field("data.array[0]");
System.out.println(valueAtZero);
```

This will still print 1.  what's more, the document will now look like this.

```javascript
{
  "data": {
    "array": [
      1,
      2,
      3
    ],
    "array[0]": 5
  }
}
```

The document now contains a relatively orphaned child element.  The property with the name "array[0]" can't ever be accessed.  Doing doc.field("data.array[0]") will return the value in the array and not this errantly created field.  So there is a disconnect between how the "getter" version of the "field" parses array subscripts and how the "setter" version of the "field" method parses array subscripts.

I have created a gist that demonstrates the issue.

https://gist.github.com/mmacfadden/e0943c5cea2d8a30cf0c

I have a fix for this, that I will be submitting as a pull request.  Once this is fixed, it appears that the UPDATE SQL works as intended.  The relationship is that the updated statement will essentially fetch the ODocument based on the WHERE clause and then set the value of the field using the same "field" method above.  So the entire SQL and UPDATE feature works as it should, and then just gets tripped up by this issue at the last moment.

**Comment by mmacfadden** [comment]
Updated the pull request, to make keeping up with the upstream sane.

**Comment by lvca** [comment]
Merged, thanks.
