### ISSUE TITLE
Issue with 2.0.14-SNAPSHOT Client is not able to connect to server via remote connection to database in 1.7.x format.

### ISSUE THREAD

**Issue by shlapkov** [orientechnologies/orientdb#4729]
Issue with 2.0.14-SNAPSHOT Client is not able to connect to server via remote connection to database.
Steps to reproduce:
1. Build 2.0.x branch.
2. Copy database which was sent to Luca last week into: 2.0.x\distribution\target\orientdb-community-2.0.14-SNAPSHOT-distribution.dir\orientdb-community-2.0.14-SNAPSHOT\databases
3. start dserver.bat
4. start console.bat
5. connect remote:localhost:2424/spectrum admin admin
6. Notice nothing happens, no exceptions, nothing Orient just waiting for something screen shot bellow: 

https://github.com/shlapkov/OrientIssues/blob/master/2.0.14-SNAPSHOT/Waiting.PNG

**Comment by shlapkov** [comment]
Initially issue not specific to 1.7.x format you can reproduce it with any database.

**Comment by tglman** [comment]
Hi @shlapkov,
just tried last snapshot with your database and no problem to connect, can you just try to rebuild or get a new SNAPSHOT?

**Comment by jillray7** [comment]
@shlapkov please let us know if the suggestions above worked.

**Comment by shlapkov** [comment]
Yes after clean rebuild from 2.0.x branch I can't reproduce it today not sure what was the issue yesterday. I'll close the issue.

**Comment by jillray7** [comment]
@shlapkov Great! Thanks!
