### ISSUE TITLE
Vertex version incorrectly increased on the destination node in the distributed mode

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4737]
When running in the asynchronous distributed 2-node mode, if the create vertex and add edge operations are performed withing the same transaction, the vertex version on the destination node get incorrectly set to 2, while on the source node it's 1 - which is correct. This causes replication inconsistency.

Here is a unit test that demonstrates the issue:
https://github.com/orientechnologies/orientdb/pull/4738

**Comment by lvca** [comment]
Did you try with 2.0.14-SNAPSHOT or 2.1 GA ?

**Comment by ylopotun** [comment]
2.1.0 – latest version in the develop branch.

**Comment by lvca** [comment]
This must be the same problem as for #4734.

**Comment by ylopotun** [comment]
@lvca This one still seems to be an issue - if 2 operations are performed within the same transaction on the source node - the version is increased by 1. But on the destination node each of these 2 operations increases the version, so it gets increased by 2. You could check the attached unit test.
