### ISSUE TITLE
protocol version 31 is 30?

### ISSUE THREAD

**Issue by optimuspaul** [orientechnologies/orientdb#4739]
https://github.com/orientechnologies/orientdb/blob/master/enterprise/src/main/java/com/orientechnologies/orient/enterprise/channel/binary/OChannelBinaryProtocol.java#L134

**Comment by lvca** [comment]
That number has been left to 30 to avoid generating a new protocol version and let all the clients to upgrade.

In facts version 31 introduced experimental features that no driver has already implemented so far, so this is not a problem. Actually we're thinking to remove such API (direct usage of indexes).
