### ISSUE TITLE
[2.1-rc6] Can not create embedded lists with empty strings

### ISSUE THREAD

**Issue by ryan-stateless** [orientechnologies/orientdb#4740]
```create vertex V content {"test1" : [""], "test2": ["","",""]}```

```{"result":[{"@type":"d","@rid":"#9:0","@version":1,"@class":"V","test1":[],"test2":[]}]}```

I would expect orientdb not to mangle my data.

**Comment by luigidellaquila** [comment]
Thanks for reporting. 
This issue was present in RC versions but it was fixed in both 2.1.0 GA and 2.2.0-SNAPSHOT
