### ISSUE TITLE
OrientGraph creation failing with exception "Storage graph is not opened" 

### ISSUE THREAD

**Issue by hitesk** [orientechnologies/orientdb#4741]
Hi
I have a use-case where I need to create OrientGraph(In memory) for each service call. Graph creation works for few (3-4) initial use-cases but after that it fails for each request with exception:
"com.orientechnologies.orient.core.exception.OStorageException: Storage graph is not opened"
My code initializes graph like:
OrientGraph graph = new OrientGraph("memory:graph");
and closes the graph like:
graph.drop(); 
I have tried using OrientGraphFactory but that is also not helping out. Also I am confused about which function should be used to drop the graph (drop() or shutdown())? When i used shutdown(), my graph did not drop but it incrementally grew with each new service invocation

**Comment by hitesk** [comment]
Can you also suggest the best way to create/destroy graph instances for in-memory use-cases (Graph will have a max TTL of 5-10 seconds)

**Comment by hitesk** [comment]
I changed the graph creation line as below, so that it wont impact multi-threading issues.
OrientGraph graph = new OrientGraph("memory:" + UUID.randomUUID().toString())

Above mentioned change has improved the performance(requests are succeeding most of the time) but still some requests are failing with error message like:
Database 'memory:f14f30e4-b7c1-4c83-b77f-5183d225e949' is closed
Can somebody tell, why this happens?

**Comment by lvca** [comment]
Please could you post your code here?

**Comment by hitesk** [comment]
public class DocumentToGraphTransformer {
    
    private static final int MAX_RETRY_COUNT = 5;
    
    private static final Logger logger = Logger.getLogger(DocumentToGraphTransformer.class);
    
    private OrientGraphNoTx graph;

    public OrientGraphNoTx transform(Document doc) {
        populateGraph(doc);
        return graph;
    }
    
    private void populateGraph(Document doc) {
        int retryCount = 0;
        graph = new OrientGraphNoTx("memory:" + UUID.randomUUID().toString());
        GraphManager graphManager = new GraphManager(graph);
        try {
            graphManager.addVertexFromDocumentEntity(doc.getEntities());
            generateEdges(graphManager, doc);
        } catch ( ONeedRetryException | OTransactionException e) {
            logger.warn("Exception occurred while generating graph from Document. ", e);
            graph.drop();
            if (retryCount < MAX_RETRY_COUNT) {
                populateGraph(doc);
            }
        }
    }

private void generateEdges(GraphManager graphManager, Document doc) {

        Vertex sourceVertex = null;
        Vertex destinationVertex = null;
        for (Entity entity : doc.getEntities()) {

            sourceVertex = graphManager.getVertices(GraphQueryConstants.IDENTIFIER, entity.getIdentifier().toString())
                    .get(0);
            for (EntityReference entityReference : entity.getReferences()) {

                destinationVertex = graphManager.getVertices(GraphQueryConstants.IDENTIFIER,
                        entityReference.getIdentifier().toString()).get(0);
                
                // Store entities references as Graph edges
                graphManager.addEdge(sourceVertex, destinationVertex, entityReference.getName());
            }
        }

public void addVertexFromDocumentEntity(List<Entity> entityCollection) {
                Gson gson = new Gson();
                for (Entity entity : entityCollection) {
                    Vertex vertex = graph.addVertex(null);
                    // Convert each object to Json String before it is stored as property
                   vertex.setProperty(DocumentConstants.TYPE_NAME,
gson.toJson(entity.getEntityType().getName()));
                    
                    vertex.setProperty(GraphQueryConstants.IDENTIFIER, gson.toJson(entity.getIdentifier().toString()));
                    vertex.setProperty(DocumentConstants.ENTITY_DATA, gson.toJson(entity.asAnything()));
        }
}

**Comment by hitesk** [comment]
I have added the code snippet above.
My use-case is: I want to convert one data (input from one incoming service request) into graph structure and then to some operations(all get operations) over the graph and then drop the graph. So, initially , I need to do lots of insert/put operations and then perform only get operations. It does not have multi-thread usage.

**Comment by hitesk** [comment]
Can somebody please help?

**Comment by lvca** [comment]
The code is incomplete. I see also a `populateGraph(doc);` after the graph shutdown.
