### ISSUE TITLE
drop index {name} always returns "Index removed successfully" but I did not have any indexes in my DB

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#4743]
Hi, I use OrientDB Server v2.1.0
I did not have any indexes in my DB but 
query "drop index {name}" always returns "Index removed successfully"

it is a bit wrong as for me

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

The Index Manager API states it explicitly

```
  /**
   * Drop index with specified name. Do nothing if such index does not exists.
   * 
   * @param iIndexName
   *          the name of index to drop
   * @return this
   */
  @OApi(maturity = OApi.MATURITY.STABLE)
  OIndexManager dropIndex(final String iIndexName);
```

so it cannot be considered a bug. I'm adding line in the docs about this

Thanks

Luigi
