### ISSUE TITLE
Allow SQL UPDATE ADD/REMOVE by Position

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#4748]
We would like to be able to insert and remove elements within a list using SQL.  The situation arrises when a document contains a large list/array for which order is important.  A simplified example:

Suppose a document in class "data" exists:

``` javascript
{
   "id": "doc1"
   "colors: ['red', 'yellow', 'blue']
}
```

The user desires to insert the value 'orange' between 'yellow' and 'blue.  The resulting document should look like this:

``` javascript
{
   "id": "doc1"
   "colors": ['red', 'yellow', 'orange', 'blue']
}
```

The existing UPDATE ADD capability only adds elements to the end of the collection.  This is not sufficient if order matters.  At the moment, the only option is to query the document to get the entire colors array, Interact with the array as an OTrackedList, insert the element and set the array back.  In the above example it would be trivial to simply replace the array with the new value, containing 4 elements.  However if the array/list is very large this can be very inefficient.

What we would like to do is something like this:

``` sql
UPDATE data ADD colors[2] = 'orange' WHERE id = 'doc1'
```

or

``` sql
UPDATE data ADD colors = 'orange' AT 2 WHERE id = 'doc1'
```

It seems like the UPDATE REMOVE syntax supports this.  According to the latest docs:

``` sql
UPDATE Account REMOVE addresses = addresses[1]
```

Perhaps there is a way to do this already, but I have not seen it in the documentation.  I think this feature would be a nice addition and add parity to how remove works.

Note: combined with #4727 this would round out array / list support.

**Comment by TwinTailsX** [comment]
Would it be possible to also have:

`UPDATE Account REMOVE address = address[city = "Rome"]`

where `addresses` is a collection of embedded documents:

`{ addresses: [ { city: "Rome" } ] }` 
?

**Comment by mmacfadden** [comment]
The current query language enhancement that I have implemented looks like this:

```SQL
UPDATE <class> INSERT INTO <field> AT <index> <value>
```

For example:

```SQL
UPDATE test INSERT INTO aList AT 2 "a value"
```

I am now working on the remove syntax.

**Comment by mmacfadden** [comment]
I basically have a positional insert and delete working.  I am looking for feedback on the syntax.  I am now thinking about:

```SQL
UPDATE Foo INSERT 1 INTO aList AT 2
UPDATE Foo DELETE FROM aList AT 2
```

The main difference being that I moved the value between INSERT and INTO.  It seems to "read" better that way.

**Comment by smolinari** [comment]
From an SQL keyword and syntactic building perspective (which I am no expert about), the second solution seems better to me too.
```
UPDATE foo
INSERT 1
INTO aList
AT 2
WHERE bar = "baz";
```
What I am not so certain about is moving away from the already build in syntax of PUT and REMOVE for . Shouldn't it be
```
UPDATE foo
PUT 1
INTO aList
AT 2
WHERE bar = "baz";
```
or..
```
UPDATE foo 
REMOVE FROM aList
AT 2
WHERE bar = "baz";
```
? 

Scott

**Comment by mmacfadden** [comment]
Hi @smolinari,

There are a few things.

First, the PUT syntax right now only applies to EMBEDDEDSET.  You can not use PUT with an EMBEDDEDLIST.  Additionally, the put semantics (due to the set) doesn't allow duplicate entities in the collection.  

Also, from an english language perspective, the word PUT is not clear as to if I am "setting" the value at position 2 (a replace) or if I am inserting a new element and shifting everything after it to the left.  If I were to simply say "put 1 at index 2", it doesn't seem clear if I am replacing or inserting.  This is why I chose the word insert.

Additionally, the terms "INSERT INTO" and "DELETE FROM" are somewhat standard nomenclature for SQL Statements.

The last issue, which is probably least valid, is that the way the parser is currently built, each UPDATE statement has a type.  The type is determined by the keyword immediately following the word UPDATE.  So UPDATE PUT would be a "PUT" type and  UPDATE REMOVE would be a "REMOVE" type.  The code then branches off and does different things based on the type.  The current put and remove syntax have different grammars that follow them, it was significantly easier to introduce two new INSERT types, rather than reusing the existing keywords and then trying to determine which scenario we are in.

So I went with this approach for now, unless the community felts strongly about it, I didn't see that is was worth the effort, and in my opinion PUT is not a good "verb" for insert anyway.  I am open to discussion however.

**Comment by smolinari** [comment]
Ok. I understand your direction. What I am personally concerned about is less the better or worse choices of language compared to English, but more of keeping things standardized. It is one thing to be understood, it is another to be consistent.

It would be great to be understood and consistent. :smile: I think that leads to intuitiveness.

About

>the word PUT is not clear as to if I am "setting" the value at position 2 (a replace) or if I am inserting a new element and shifting everything after it to the left.

With INSERT, is that all that is happening? I also can't tell if it is an addition to the set or a change in value (how does theODB know?). Could this work?

```
UPDATE foo.aList
AT 2
VALUE 3
WHERE bar = "baz";
```
or

```
UPDATE foo
SET aList
AT 2
VALUE 3
WHERE bar = "baz";
```

Or something to that effect? Could you check the ODB gitter channel for me? I have another question, which isn't totally related to this discussion.

Scott

**Comment by mmacfadden** [comment]
I believe that INSERT implies a new element is being added and everything after is being shifted to the right.  Also keep in mind that the current syntax for setting an element in a list is:

```SQL
UPDATE foo SET aLIST[2] = "some value"
```

I also made an error in my initial comment.  UPDATE PUT applies only to EMBEDDEDMAP and LINKMAP.  The word PUT is most often associated with Map datastrutures in computer science.  I am not sure put makes sense for managing elements in a list.

**Comment by mmacfadden** [comment]
@smolinari I searched for you on the channel.  There are a couple questions.  Which one are you referring to?

**Comment by mmacfadden** [comment]
@luigidellaquila I have the implementation and testing roughly done.  I just need to finalize the Syntax and would like your opinion.
