### ISSUE TITLE
query "select @rid as @rid, name from ouser" returns error

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#4752]
##### when i use query "select from ouser", I receive RIDs in field "**@RID**"

orientdb {db=test}> select from ouser
----+----+------+------+-------------------------------------------------------------------------+------+-----
\#   | @RID| @ CLASS|name  |password                                                                 |status|roles
----+----+------+------+-------------------------------------------------------------------------+------+-----
0   |#5:0|OUser |admin |{SHA-256}8C6976E5B5410.....415BDE90|ACTIVE|[1]
1   |#5:1|OUser |reader|{SHA-256}3D0941964AA3EBDCB00CCE....D5AEC7F31090A0FB30|ACTIVE|[1]
2   |#5:2|OUser |writer|{SHA-256}B93006774CBDD4B299389A03...11A909FBA5|ACTIVE|[1]
----+----+------+------+-------------------------------------------------------------------------+------+-----
3 item(s) found. Query executed in 0.008 sec(s).

##### but if I use query with projections, I receive RIDs in field "**RID**"

orientdb {db=test}> select @rid, name from ouser
----+------+----+------
\#   | @ CLASS| **rid** |name
----+------+----+------
0   |null  |#5:0|admin
1   |null  |#5:1|reader
2   |null  |#5:2|writer
----+------+----+------
3 item(s) found. Query executed in 0.006 sec(s).

##### so I use override of the field to get a similar result

orientdb {db=test}> select @rid as @rid, name from ouser
----+----+------+------
\#   | @RID| @ CLASS|name
----+----+------+------
0   |#5:0|OUser |admin
1   |#5:1|OUser |reader
2   |#5:2|OUser |writer
----+----+------+------
3 item(s) found. Query executed in 0.005 sec(s).

##### the top code worked in version 2.0.13 but in version 2.1.0 the query "select @rid as @rid, name from ouser" returns error

orientdb {db=test}> select @rid as @rid, name from ouser

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <RECORD_ATTRIBUTE> "@
rid "" at line 1, column 16.
Was expecting one of:
    \<TO\> ...
    \<VALUES\> ...
    \<SET\> ...
    \<ADD\> ...
    \<PUT\> ...
    \<MERGE\> ...
    \<CONTENT\> ...
    \<REMOVE\> ...
    \<ORDER\> ...
    \<GROUP\> ...
    \<OFFSET\> ...
    \<RECORD\> ...
    \<LUCENE\> ...
    \<NEAR\> ...
    \<WITHIN\> ...   
    \<IN\> ...
    \<KEY\> ...
    \<IDENTIFIER\> ...
    \<IDENTIFIER\> ...
    \<IN\> ...
    \<SET\> ...
    \<PUT\> ...
    \<ADD\> ...
    \<REMOVE\> ...
    \<MERGE\> ...
    \<CONTENT\> ...
    \<ORDER\> ...
    \<KEY\> ...
    \<OFFSET\> ...
    \<GROUP\> ...
    \<VALUES\> ...
    \<RECORD\> ...
    \<TO\> ...
    \<LUCENE\> ...
    \<NEAR\> ...
    \<WITHIN\> ...
    "`" ...
    "`" ...
    "`" ...

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

@ field names are not valid aliases in 2.1, but it's actually quite easy to support.
@lvca shall we support it?

**Comment by a-unite** [comment]
What is rather interesting - it works in "old style" with 2.1 too, but only if your database was created in 2.0.X version. 
Does it mean that ODB has different logic for different file formats? If file structure changed for 2.1 - may new logic hurt our (just copied to new version, not imported) data files then?
Sorry for off-topic.

**Comment by luigidellaquila** [comment]
Hi @a-unite 

it was made for backward compatibility. Old databases maintain the old behavior (no strict SQL), while newly created dbs have strict validation enabled by default

**Comment by a-unite** [comment]
@luigidellaquila thank you!
I understand it is safe to move to 2.1 in production then, and re-import after all parser tests are settled. This issue with `@` sign is quite important for us now. I think, that if first query is still returns '@rid', then it is quite obvious, that you will need to have aliases with same name (`@` included) one day, i.e. for API consistency.  
Another way to solve this - is to use projections in every other query.

**Comment by Ivanov-Yuriy** [comment]
> Another way to solve this - is to use projections in every other query.

- or always return service field with sign "@" 
- or never return service field with sign "@"

not important, only the service field would have the same name always

**Comment by a-unite** [comment]
@Ivanov-Yuriy Sorry, my suggestion was kind of sarcastic, yours makes sense, while could raise compatibility issues (might be solved with another config parameter introduced, though).

@luigidellaquila, @lvca just curious - were there reasons, to strip `@` from system fields names in projection queries' results?

**Comment by gongdo** [comment]
I have similar question about this.
Assume a class A has several value properties(a to g) and LINK property(link).

I cannot get 'partial' document with `@rid` property(with `@` prefix):
`select @rid, @version, e, f, g, link.value as value from A`
`@` prefix will be stripped out, anything else is good enough.

But I can get partial document like this:
`select *, link.Value as value from A fetchplan a:-2 b:-2 c:-2 d:-2`
It doesn't strip the `@` sign, and works good.

So technically, there's no problem to make partial document as a result.
For now, I can go with second way. However it's uncomfortable and inefficient, I think.
Why don't you support both ways. Is there any cases that could be a problem

**Comment by a-unite** [comment]
As I understand presence of system field in server answer should tell us, that we have original object (with `@rid`, `@type` and other system fields in place) as result.
Absence of such special fields somehow indicates, that we have synthetic answer from the server (projection, in general, is synthetic set of fields).
As for me it should be clear from particular fields, though. E.g. conjunction of `@type`, `@rid` and `@version` fields, as it is formed now. While I, personally, will be glad to have special indicator\answer property, something like `@answerType`.

Anyway, we are going off track here.
Support of old behavior is essential for us. Improvements are very much welcomed.

**Comment by a-unite** [comment]
Dear @luigidellaquila, @lvca  haven't you come with any decision on original issue?

**Comment by Ivanov-Yuriy** [comment]
for me very important understand, this behaviour will stay the same and I must change my code or will you change this behaviour?
please answer me, thank you

**Comment by luigidellaquila** [comment]
@lvca I need your comment on this, there is no technical reason to allow or deny this behavior.
It's just a matter of consistency, shall we allow fields with @ in projections?

**Comment by a-unite** [comment]
Look guys, it was strange to have different results for projection and "natural" query before 2.1
Example from the initial issue looks weird:
`select @rid as @rid, name from ouser`
Now it is getting even more strange, when even `as @rid` doesn't work....

Why don't we return field names as is for new (strict) requests mode? I hope we should use that chance to add good sense to the syntax, not vice versa.

**Comment by a-unite** [comment]
Could you please tell if you are going to come or not with your verdict for this issue anytime soon?
Any answer will be accepted.
Our development cycle is stuck with this matter. Normally we use any workaround which have a common sense or logic behind it, but here situation is quite binary.

**Comment by smolinari** [comment]
The right solution is to do whatever it takes to be consistent. 

Scott

**Comment by a-unite** [comment]
Scott,
please, don't stop here. 
What solution do _you_ think is best for consistency?

**Comment by smolinari** [comment]
Hehe...unfortunately, I am not experienced enough with ODB to give specific suggestions. But, I know from my experience with quality management, being consistent is a core part of being professional. 

From my less experienced ODB perspective, the "@" is the problem. 

Scott

**Comment by a-unite** [comment]
Thanks. 

My thoughts:
1. Since `as @rid` was working before - it looks like there are no any dependencies on that kind of field presence in result set for ODB logic.
2. If one is asking for `@` property - we could return it as is, with `@` sign, no surprises.
3. It might be useful to provide some flag in database for next hot-fix version, to switch that behavior on.
4. This might be default behavior from version 2.2 (flag is `on` by default for all newly create databases)
5. Based on statistics, this flag could be omitted completely from version 2.3
6. Mention that in documentation and keep issues 4 and 5 for upcoming major releases.

Best regards,
Ata

**Comment by giastfader** [comment]
As a workaround, did you try to unset the strictSql property?
```
ALTER DATABASE custom strictSQL=false
````

**Comment by a-unite** [comment]
@giastfader, yes we did and this is how our production version works for now.
But I still hope we could switch to current (proper) query parser soon.

**Comment by luigidellaquila** [comment]
Hi guys, 

I just pushed a fix on branch 2.1.x, could you please verify that it completely fixes your use case?

Thanks

Luigi

ps. please comment but keep this issue open, I have to port the issue to develop

**Comment by smolinari** [comment]
Hey Luigi. 

Thanks for the quick fix. I call that great support. What should we expect to see?

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

just the fix for the original issue, so the same behavior you had in 2.0.
I'm also planning to return @ alias as is (without removing @), but I have to share it with the team and be sure that nothing breaks

Thanks

Luigi

**Comment by a-unite** [comment]
Hi, @luigidellaquila

Looks like it works as previous (`@rid as @rid`).
Thank you very much!

You could close this issue, though, I'm still wander if we need aliasing `@rid` -> `rid` at all.
Hope you will have chance to discuss and decide on this with team.
Will you open another issue, or we could track this one for the progress with it?

WBR, Ata
