### ISSUE TITLE
Validation exception: Exception during commit of active transaction 

### ISSUE THREAD

**Issue by huntde** [orientechnologies/orientdb#4755]
OrientDB 2.1.0. Reproducible simple test case attached.
Basically
a) create database
b) create class hierarchy
theRoot
  --> Nap
  --> Node
  --> LayoutElement
          --> property layoutNode otype.link to Node class
          --> property examples otype.linklist of Example class
  --> Example
          --> property "start" otype.link to Nap class
          --> property "end" otype.link to Nap class
c) create 2 nap instances and add them as the start and end fields of an instance of Example
d) add Example to the examples list of LayoutElement

Result is exception:
The field 'Example.start' has been declared as LINK of type 'Nap' but the value is the document #-1:-2 of class 'examples'

Full exception at then end as output from spock integration test.

Code:
	static void createBugTestData(String localOrRemote, String hostName, String databaseName
			, String userName, String password
			) throws Exception, IOException {

		String con = localOrRemote + ":" + hostName + "/" + databaseName;
		
		OrientGraphFactory factory = new OrientGraphFactory(con, userName, password).setupPool(1,10);
		OrientGraph graph = factory.getTx();			
		try {
			OSchema schema = factory.getDatabase().getMetadata().getSchema();
	
			graph.createVertexType("theRoot");
			graph.createVertexType("Nap", "theRoot");
			graph.createVertexType("Node", "theRoot");
			graph.createVertexType("LayoutElement", "theRoot");
			graph.createVertexType("Example", "theRoot");
			
			graph.getVertexType("Example").createProperty("start", OType.LINK, schema.getClass("Nap"));
			graph.getVertexType("Example").createProperty("end", OType.LINK, schema.getClass("Nap"));
			
			graph.getVertexType("LayoutElement").createProperty("layoutnode", OType.LINK, schema.getClass("Node"));
			graph.getVertexType("LayoutElement").createProperty("examples", OType.LINKLIST, schema.getClass("Example"));
			
			Map<String, Object> props = new HashMap<String, Object>();
	
			OrientVertex n1 = graph.addVertex("class:Nap");
			OrientVertex n2 = graph.addVertex("class:Nap");
	
			OrientVertex ex = graph.addVertex("class:Example");
			OrientVertex le1 = graph.addVertex("class:LayoutElement");
			props.clear();
			props.put("start", n1);
			props.put("end", n2);
			ex.setProperties(props);		
			ex.save();
			le1.addEdge("examples", ex);
			le1.save();
	
		} catch (Exception ex) {
			System.out.println("exception full ");
			ex.printStackTrace();
			throw ex;
		}
		finally {
			graph.shutdown();
		}
	}

Exception log:
Error |
2015-08-07 16:14:42,836 [main] ERROR db.OPartitionedDatabasePool$DatabaseDocumentTxPolled  - Exception during commit of active transaction.
Message: Error on transaction commit
    Line | Method
->> 2004 | commitEntry               in com.orientechnologies.orient.client.remote.OStorageRemote
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1110 | commit                    in     ''
|    445 | commit . . . . . . . . .  in com.orientechnologies.orient.client.remote.OStorageRemoteThread
|    475 | doCommit                  in com.orientechnologies.orient.core.tx.OTransactionOptimistic
|    147 | commit . . . . . . . . .  in     ''
|   2437 | commit                    in com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx
|   1082 | close . . . . . . . . . . in     ''
|    154 | close                     in com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled
|   1167 | shutdown . . . . . . . .  in com.tinkerpop.blueprints.impls.orient.OrientBaseGraph
|   1139 | shutdown                  in     ''
|   1132 | shutdown . . . . . . . .  in     ''
|    732 | createBugTestData         in com.bt.serviceDesign.utils.OrientUtils
|    148 | $spock_feature_1_4 . . .  in com.bt.service.design.ServiceDesignIntegrationSpec
|    138 | invokeMethod              in org.spockframework.util.ReflectionUtil
|    330 | invokeRaw . . . . . . . . in org.spockframework.runtime.BaseSpecRunner
|    311 | invoke                    in     ''
|    285 | invokeFeatureMethod . . . in     ''
|    256 | doRunIteration            in     ''
|    138 | invokeMethod . . . . . .  in org.spockframework.util.ReflectionUtil
|    330 | invokeRaw                 in org.spockframework.runtime.BaseSpecRunner
|    311 | invoke . . . . . . . . .  in     ''
|    223 | runIteration              in     ''
|    214 | initializeAndRunIteration in     ''
|    119 | runIterations             in org.spockframework.runtime.ParameterizedSpecRunner
|     43 | runParameterizedFeature . in     ''
|    198 | doRunFeature              in org.spockframework.runtime.BaseSpecRunner
|    138 | invokeMethod . . . . . .  in org.spockframework.util.ReflectionUtil
|    330 | invokeRaw                 in org.spockframework.runtime.BaseSpecRunner
|    311 | invoke . . . . . . . . .  in     ''
|    175 | runFeature                in     ''
|    152 | runFeatures . . . . . . . in     ''
|    112 | doRunSpec                 in     ''
|    138 | invokeMethod . . . . . .  in org.spockframework.util.ReflectionUtil
|    330 | invokeRaw                 in org.spockframework.runtime.BaseSpecRunner
|    311 | invoke . . . . . . . . .  in     ''
|     91 | runSpec                   in     ''
|     82 | run . . . . . . . . . . . in     ''
|     63 | run                       in org.spockframework.runtime.Sputnik
|    127 | runChild . . . . . . . .  in org.junit.runners.Suite
|     26 | runChild                  in     ''
|    238 | run . . . . . . . . . . . in org.junit.runners.ParentRunner$3
|     63 | schedule                  in org.junit.runners.ParentRunner$1
|    236 | runChildren . . . . . . . in org.junit.runners.ParentRunner
|     53 | access$000                in     ''
|    229 | evaluate . . . . . . . .  in org.junit.runners.ParentRunner$2
|    309 | run                       in org.junit.runners.ParentRunner
|    160 | run . . . . . . . . . . . in org.junit.runner.JUnitCore
|    138 | run                       in     ''
|    102 | doCall . . . . . . . . .  in _GrailsTest_groovy$_run_closure1
^     32 | doCall                    in TestApp$_run_closure1
Caused by OValidationException: The field 'Example.start' has been declared as LINK of type 'Nap' but the value is the document #-1:-2 of class 'examples'
->>  484 | validateLink              in com.orientechnologies.orient.core.record.impl.ODocument
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    275 | validateField             in     ''
|   1953 | validate . . . . . . . .  in     ''
|   2259 | save                      in com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx
|    118 | save . . . . . . . . . .  in     ''
|   1727 | save                      in com.orientechnologies.orient.core.record.impl.ODocument
|   1718 | save . . . . . . . . . .  in     ''
|     76 | save                      in     ''
|    674 | recursiveLinkSave . . . . in com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0
|    688 | writeOptimizedLink        in     ''
|    572 | writeSingleValue . . . .  in     ''
|    261 | serialize                 in     ''
|    105 | toStream . . . . . . . .  in com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary
|   2100 | toStream                  in com.orientechnologies.orient.core.record.impl.ODocument
|    695 | toStream . . . . . . . .  in     ''
|   1998 | commitEntry               in com.orientechnologies.orient.client.remote.OStorageRemote
|   1110 | commit . . . . . . . . .  in     ''
|    445 | commit                    in com.orientechnologies.orient.client.remote.OStorageRemoteThread
|    475 | doCommit . . . . . . . .  in com.orientechnologies.orient.core.tx.OTransactionOptimistic
|    147 | commit                    in     ''
|   2437 | commit . . . . . . . . .  in com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx
|   1082 | close                     in     ''
|    154 | close . . . . . . . . . . in com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled
|   1167 | shutdown                  in com.tinkerpop.blueprints.impls.orient.OrientBaseGraph
|   1139 | shutdown . . . . . . . .  in     ''
|   1132 | shutdown                  in     ''
|    732 | createBugTestData . . . . in com.bt.serviceDesign.utils.OrientUtils
|    148 | $spock_feature_1_4        in com.bt.service.design.ServiceDesignIntegrationSpec
|    138 | invokeMethod . . . . . .  in org.spockframework.util.ReflectionUtil
|    330 | invokeRaw                 in org.spockframework.runtime.BaseSpecRunner
|    311 | invoke . . . . . . . . .  in     ''
|    285 | invokeFeatureMethod       in     ''
|    256 | doRunIteration . . . . .  in     ''
|    138 | invokeMethod              in org.spockframework.util.ReflectionUtil
|    330 | invokeRaw . . . . . . . . in org.spockframework.runtime.BaseSpecRunner
|    311 | invoke                    in     ''
|    223 | runIteration . . . . . .  in     ''
|    214 | initializeAndRunIteration in     ''
|    119 | runIterations . . . . . . in org.spockframework.runtime.ParameterizedSpecRunner
|     43 | runParameterizedFeature   in     ''
|    198 | doRunFeature . . . . . .  in org.spockframework.runtime.BaseSpecRunner
|    138 | invokeMethod              in org.spockframework.util.ReflectionUtil
|    330 | invokeRaw . . . . . . . . in org.spockframework.runtime.BaseSpecRunner
|    311 | invoke                    in     ''
|    175 | runFeature . . . . . . .  in     ''
|    152 | runFeatures               in     ''
|    112 | doRunSpec . . . . . . . . in     ''
|    138 | invokeMethod              in org.spockframework.util.ReflectionUtil
|    330 | invokeRaw . . . . . . . . in org.spockframework.runtime.BaseSpecRunner
|    311 | invoke                    in     ''
|     91 | runSpec . . . . . . . . . in     ''
|     82 | run                       in     ''
|     63 | run . . . . . . . . . . . in org.spockframework.runtime.Sputnik
|    127 | runChild                  in org.junit.runners.Suite
|     26 | runChild . . . . . . . .  in     ''
|    238 | run                       in org.junit.runners.ParentRunner$3
|     63 | schedule . . . . . . . .  in org.junit.runners.ParentRunner$1
|    236 | runChildren               in org.junit.runners.ParentRunner
|     53 | access$000 . . . . . . .  in     ''
|    229 | evaluate                  in org.junit.runners.ParentRunner$2
|    309 | run . . . . . . . . . . . in org.junit.runners.ParentRunner
|    160 | run                       in org.junit.runner.JUnitCore
|    138 | run . . . . . . . . . . . in     ''
|    102 | doCall                    in _GrailsTest_groovy$_run_closure1
^     32 | doCall . . . . . . . . .  in TestApp$_run_closure1
|
thanks
Dan

**Comment by matanshukry** [comment]
I've tested the following scripts on 3 versions:
develop branch, 2.1.x branch (2.1.1 currently I believe) and 2.1.0 tag, all worked without an exception and data is as expected as well.

```
drop class Nap
drop class Node
drop class LayoutElement
drop class Example

create class Nap
create class Node
create class LayoutElement
create class Example
create property LayoutElement.layoutNode LINK Node
create property LayoutElement.examples LINKSET Example
create property Example.start LINK Nap
create property Example.end LINK Nap

insert into Nap (id) values (0)
insert into Nap (id) values (1)
insert into Example (start, end) values ((SELECT FROM Nap where id=0), (SELECT FROM Nap where id=1))
insert into LayoutElement (examples) VALUES ((SELECT FROM Example))

select examples[0].start.id, examples[0].end.id from layoutelement


----+------+--------+---------
#   |@CLASS|examples|examples2
----+------+--------+---------
0   |null  |0       |1        
----+------+--------+---------
```

**Comment by huntde** [comment]
thanks for the quick response.
However I need to build the database using the Java API.
Do you have the setup to prove the same using Java ?

cheers
Dan

**Comment by matanshukry** [comment]
I'm afraid not, only IDE.
Can you upload a quick project, dependencies included (maven, or anything that works with intellij) to github?

**Comment by huntde** [comment]
spurred on by your proof that it was Java related I added calls to create the edge types explicitly.
This worked.
			graph.createEdgeType("start");
			graph.createEdgeType("end");
			graph.createEdgeType("layoutnode");
			graph.createEdgeType("examples");

So in summary explicitly create the edge types even though the code will create them for you as part of the createProperty.
e.g.
  graph.createEdgeType("start");
  graph.getVertexType("Example").createProperty("start", OType.LINK, schema.getClass("Nap"));

thanks@matanshukry
Dan
