### ISSUE TITLE
[Parser] One space more or less break `find references` query

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4762]
:heavy_check_mark: `find references (select from Node where Email = 'julia@local')`
:x: `find references   (select from Node where Email = 'julia@local')` (one space more after references keyword)
:x: `find references(select from Node where Email = 'julia@local')` (no space after references keyword)

Exception:
- `× java.lang.IllegalStateException: Missing closed string character: ''', position: 63``
- ```com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.find references(select from Node where Email = 'julia@local')```

Tested env: 2.0.10, Studio.

**Comment by luigidellaquila** [comment]
Pushed a fix on develop branch. The fix will be available in 2.2 GA

Closing

Thanks!

Luigi
