### ISSUE TITLE
OPartitionedDatabasePool.close does not close the underlying storage

### ISSUE THREAD

**Issue by rayees** [orientechnologies/orientdb#4765]
When a plocal document db pool is created and closed, the underlying storage is not closed.

OPartitionedDatabasePoolFactory poolFactory = new OPartitionedDatabasePoolFactory();
OPartitionedDatabasePool pool = poolFactory.get("plocal:db_test", "testuser", "testuser");
pool.close();

Pool close stack trace.
	OPartitionedDatabasePool.close()
	OStorageAbstract.close();
	OStorageAbstract.close(false, false);
	OAbstractPaginatedStorage.doClose(force, onDelete)
		if (!force && !onDelete) ;

**Comment by laa** [comment]
Yes , that is normal, storage is closed during JVM shutdown. Database is treated as connection to the storage .

**Comment by rayees** [comment]
In case of applications that use multiple embedded plocal database instances and separate pools for each, JVM heap size of the application can grow quite big. By closing a pool (done with one database instance) if the storage also shuts down that would keep the memory usage low.
Meanwhile the application can still continue working with other pools/database instances.

Also having storage.close inside pool.close when actually it is not doing anything is a little confusing.

**Comment by laa** [comment]
Hi,
Storage is working on direct memory area, not heap and uses direct memory cache shared across all storages. So if one storage needs more memory and this memory is hold by storage which was not used for a long time memory will be freed from "idle" storage and will be used by "active" storage. Do you  have facts which contradicts to this explanation ?

**Comment by rayees** [comment]
Hi,
I am working with 300+ database instances and 10-20 loaded at a time. And hits outofmemory quite often.
While profiling, noticed the database storages are not getting unloaded.Also WAL threads kept running. Tried force close of storage which actually brought the memory usage down and also WAL threads were closed. This showed some improvements while profiling.

Was not aware of idle and active storage, off-heap cache. Can you please help me find documentation about embedded plocal databases, storages, off-heap cache and how all these work?
I can test again with these new learning and let you know in case I find anything contradicts.

**Comment by rayees** [comment]
Hi,

Tried writing a sample program that creates multiple plocal databases in a loop.

Code inside the loop :
          OPartitionedDatabasePool pool = poolFactory.get("plocal:db/" +        
         dbInstanceName, "admin", "admin");
		pool.setAutoCreate(true);
		ODatabaseDocumentTx db = pool.acquire();

                // Insert dummy data (1000 ODocument)
               db.close();
		pool.close();

The program continuously crashed with out of memory somewhere between 37 - 40th instance every time.

SEVERE: Error during WAL background flush
java.lang.OutOfMemoryError: Java heap space
	at com.orientechnologies.common.directmemory.OUnsafeMemoryJava7.get(OUnsafeMemoryJava7.java:30)
	at com.orientechnologies.common.directmemory.ODirectMemoryPointer.get(ODirectMemoryPointer.java:79)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment$FlushTask.commit(ODiskWriteAheadLog.java:194)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment$FlushTask.run(ODiskWriteAheadLog.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



Later I added below code after pool.close(), and the same program was able to create upto 500 instances without OOM. 

Collection<OStorage> storages = Orient.instance().getStorages();
		for (OStorage storage : storages) {
			if (!storage.isClosed() && storage.getName().equalsIgnoreCase(dbInstanceName)) {
				storage.close(true, false);
			}
		}

As expected next run had to do storage data restore 

Aug 16, 2015 1:38:43 AM com.orientechnologies.common.log.OLogManager log
WARNING: {db=inst0} segment file 'database.ocf' was not closed correctly last time
Aug 16, 2015 1:38:43 AM com.orientechnologies.common.log.OLogManager log
WARNING: {db=inst0} Storage inst0 was not closed properly. Will try to restore from write ahead log.
Aug 16, 2015 1:38:43 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=inst0} Looking for last checkpoint...
Aug 16, 2015 1:38:43 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=inst0} Found FUZZY checkpoint.
Aug 16, 2015 1:38:43 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=inst0} Data restore procedure from FUZZY checkpoint is started.
Aug 16, 2015 1:38:43 AM com.orientechnologies.common.log.OLogManager log
WARNING: {db=inst0} Record OFuzzyCheckpointStartRecord{lsn=OLogSequenceNumber{segment=0, position=2554430}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=OLogSequenceNumber{segment=0, position=1986465}} will be skipped during data restore.
Aug 16, 2015 1:38:43 AM com.orientechnologies.common.log.OLogManager log
WARNING: {db=inst0} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=OLogSequenceNumber{segment=0, position=2554470}} will be skipped during data restore.
Aug 16, 2015 1:38:43 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=inst0} Storage data restore was completed

All tests were run with VM settings - -Xmx32m -XX:-UseGCOverheadLimit.

Am I missing some configurations? Is force storage close a good idea?

**Comment by laa** [comment]
HI,
I have question is it correct that you allocated only 32 megabytes of heap,
recommended size is 512 megabytes.
Could you try tests with this option ?

**Comment by laa** [comment]
And about your question, closing of storage leads to performance
degradation, also because database instance does not know that storage is
closed it may lead to errors.

**Comment by raeesn** [comment]
I used low value (32MB) in the tests to get OOM early. 
With the recommended 512 the tests are running much better and went up to 500 instances without OOM. I was getting OOM in the application which is running on 2GB heap. Could be some other issue.

Thank you very much I am closing this thread.

FYI - The test printed below logs. 

    Aug 18, 2015 4:39:03 PM com.orientechnologies.common.log.OLogManager log
    INFO: -> Open server.sh (or server.bat on Windows) and change the following variables: 1)  MAXHEAP=-Xmx303M 2) MAXDISKCACHE=5839
    Aug 18, 2015 4:39:03 PM com.orientechnologies.common.log.OLogManager log
    INFO: Database 'inst190' uses 4,834MB/5,688MB of DISKCACHE memory, while Heap is not completely used (usedHeap=253MB maxHeap=455MB). To improve performance set maxHeap to 303MB and DISKCACHE to 5839MB
    Aug 18, 2015 4:39:03 PM com.orientechnologies.common.log.OLogManager log
    INFO: -> Open server.sh (or server.bat on Windows) and change the following variables: 1) MAXHEAP=-Xmx303M 2) MAXDISKCACHE=5839

**Comment by raeesn** [comment]
The service we are developing is expected to run 24/7 and would create around 200-300 DB instances (plocal document) to store some data snapshots received everyday. The heap size is 2GB. Each DB would be around 200MB size. The DB instances are written once and less likely to get loaded back.

Any recommendations on using multiple DB instances and to keep the service running 24/7 without any OOM? Or should I look for different options like single DB that stores all data or remote mode?

**Comment by raeesn** [comment]
With more data available. Can we reopen this issue?
https://groups.google.com/forum/#!topic/orient-database/SwGN5xAI1oM

**Comment by laa** [comment]
No, this issue is incorrect. Pool behaves as expected.

**Comment by raeesn** [comment]
The real concern was about storage not getting closed even after all connections and pool is closed. It is OK, I can raise another one.

**Comment by laa** [comment]
We already have issue related to this problem
https://github.com/orientechnologies/orientdb/issues/3055 .
