### ISSUE TITLE
information/documentation on experiences with properties on edges and lightweight mode

### ISSUE THREAD

**Issue by crmayer** [orientechnologies/orientdb#4770]
OrientDB 2.1.0 GA

Just want to share some specific experiences with properties on edges and lightweight mode that could not be found in the documentation.
Was tracking down a problem why some of an applications relations behaved lightweight, others, seemingly same, behaved heavyweight. This is the result.
Had some edges with MANDATORY in the create property, others with a ALTER PROPERTY ad posterum.

So, just having a specific properties in/out on a edge doesn't make it heavyweight.
Creating explicit properties in/out helps providing type safeness. Just in and out - nothing else.

CREATE PROPERTY DLogOwner.in   LINK DProcess;
CREATE PROPERTY DLogOwner.out  LINK DLogRoot;
// --- ALTER PROPERTY  DLogOwner.in   MANDATORY true;
// --- ALTER PROPERTY  DLogOwner.out  MANDATORY true;

But: ALTER PROPERTY with MANDATORY true will change it to heavyweight.

OTOH using MANDATORY in create property:
CREATE PROPERTY DLogOwner.in   LINK DProcess     MANDATORY true;
CREATE PROPERTY DLogOwner.out  LINK DLogRoot     MANDATORY true;

will be consumed without complaints at creation, but, according to "schema" inspector - mandatory is NOT BEING SET.

**Comment by lvca** [comment]
create property cannot receive multiple settings, so you have to call `ALTER PROPERTY` to set the mandatory.

For the rest the behavior is coherent: you can define a property in/out that could exists or not, so if doesn't exist, the edge will be lightweight.
