### ISSUE TITLE
Infinite loop in `OrientGraphFactory.getTx()` when server is unreachable.

### ISSUE THREAD

**Issue by bmcustodio** [orientechnologies/orientdb#4771]
In versions `2.0.14` and `2.1.0` of `com.orientechnologies:orientdb-graphdb`, `OrientGraphFactory.getTx()` seems to enter an infinite loop if the remote server is not reachable. This does not seem to happen in `2.0.13`. I used the following piece of code to reproduce the problem:

```java
OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/bmcustodio", "admin", "admin");
factory.setupPool(1, 20);
OrientGraph orientGraph = factory.getTx(); // (1)
```

The behaviour is the following:

* Using `2.0.13`, `(1)` throws an `OStorageException`, which can then be handled by the calling code. This, I would say, is the expected behaviour.
* Using `2.0.14`, `(1)` blocks forever (nothing seems to be logged).
* Using `2.1.0`, `(1)` blocks forever (it does log the exceptions).

I guess (I'm not at all familiar with OrientDB's codebase) that the problem may lie [here](https://github.com/orientechnologies/orientdb/blob/2.1.0/client/src/main/java/com/orientechnologies/orient/client/remote/OStorageRemote.java#L1919), as different values are returned from `getAvailableConnections` under the different versions. Can it be anything with new configuration parameters introduced recently that I may not be observing?

**Comment by lvca** [comment]
@tglman did you fix a similar issue a few days ago?

**Comment by tglman** [comment]
tes is fixed
