### ISSUE TITLE
Correct way for a node to leave a cluster

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4772]
We are running OrientDB in a distributed mode on a cluster of two servers: A and B.
Right now, if we want the node B to leave the cluster, we update its hazelcast.xml (remove node A ip address from there) and restart its DB.

When the DB gets restarted on node B, node A "understands" that node B left the cluster. But node B still thinks it's in the cluster with node A as per its config file databases/<dbname>/distributed-db-config.json
So, to make it "understand" it's not in the cluster anymore, we need to delete this file.

What I'd like to ask is maybe there is an easier way (or the API we could use) to make node B leave the cluster?
What would be your suggestion?

**Comment by lvca** [comment]
@ylopotun Actually this could be a nice new api that could be part of the new commands in console to have a finer control of the clusters. I was thinking about:
- `unjoin node <node-id> [<database>]` -> sends a command to un-join the cluster. If database is specified, the unjoin will be executed only on that database for that node
- `list nodes` -> display the active nodes + node info
- `synch database` -> already available, forces the sync of the database by fetching a new copy from the cluster
- `synch cluster <cluster-name>` -> already available, forces the sync of a cluster by fetching a new copy from the distributed cluster

**Comment by lvca** [comment]
Also a command to execute the rejoin:
- join node <node-id> <database>

But I'd need a better name than join/unjoin...

**Comment by ylopotun** [comment]
Such API would be very helpful, so if possible please consider adding it in the next release. Meanwhile, we'll use the described workaround. Do you think it's required to remove databases/db_name/distributed-db-config.json on the node we would like to leave the cluster? I thought, it should be enough to just update its hazelcast.xml, but looks like it still thinks it's in the cluster based on databases/db_name/distributed-db-config.json

**Comment by lvca** [comment]
Ok, implemented. New commands are:
```
HA REMOVE SERVER <server-name>
HA SYNC DATABASE
HA SYNC CLUSTER <cluster-name>
```

**Comment by lvca** [comment]
Updated also docs.
