### ISSUE TITLE
localCache entries are never getting cleared from memory in pLocal mode

### ISSUE THREAD

**Issue by shajigopal** [orientechnologies/orientdb#4781]
OrientDB version: 2.0.5

We are running OrientDB in pLocal mode as part of our webapp in tomcat.
We use timkerpop api's to access and traverse the graph. As we do that we see entries getting into the local cache. We see that these entries are never getting cleared even though there is no external references to the records apart from OrientGraph.
What would be the reason for these not getting cleared even after GC runs?

In the documentation, we see two configurations - cache.level1.size and cache.level2.size that can limit the cache entries. There is nothing in OGlobalConfiguration to set these values .How do we set these configurations?

**Comment by lvca** [comment]
How do you know they are not cleared? Have you tried 2.1.2 ?

**Comment by shajigopal** [comment]
No we are on 2.0.5 and cannot upgrade right now.

**Comment by laa** [comment]
Sorry but still how do you know that they are not cleared ?

**Comment by shajigopal** [comment]
Our performance team ran some tests and collected metrics using Eclipse MAT. The results were collected after 2 hours and 12 hours. We noticed that the "graph" object was holding on to a lot of object references.
In case you are interested I can send you a private mail with the results.

**Comment by laa** [comment]
Yes,
If you do not mind, but I think the most important is that, according to my
opinion, you use graph object in wrong way.
Seems you open it and keep open till application shutdown.
But you should use graph factory and pool instead.
You may consider graph object as a connection, you open it at the start of
the method and close at the end (by calling of shutdown method).
Acquiring of graph object instance using graph factory and pool is very
cheap.

Is my assumption about usage of graph object in your project correct ?

**Comment by shajigopal** [comment]
Luca,
     You are right we create the graph by calling  new OrientGraph() and we shut it down only during application shutdown. We will try using the graphFactory instead.

**Comment by laa** [comment]
Hi ,
I am Andrey ,
Any way I am looking forward for your feedback :-)

**Comment by laa** [comment]
Do not forget to setup pool in graph factory . It is very important .

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
