### ISSUE TITLE
Improve export & import performance

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4782]
Export and import was designed years ago when OrientDB wasn't capable to work in parallel like today. We'd need a huge rework on export:
- create a fixed number of threads executors, let's say = cores
- pass each cluster to each thread
- each thread is responsible to export current records
- the only synchronized part is the `file.out()`

For import it's more complex:
- one thread per cluster
- use one index per cluster for RID Mapping

**Comment by mamoit** [comment]
In `2.1.16` I'm getting an import speed of always less than ~300 records/sec, in a dual core machine with 15GB of RAM.
This is definitely an issue.

**Comment by lvca** [comment]
Are you using remote? I suggest you to use plocal if you can.
