### ISSUE TITLE
SQL INCREMENT does not work with dot notation properties (2.1)

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#4784]
In 2.1.  Assume we have a class "test" with the following data:

```javascript
{
  “map”: {
    “bar”: 1
  }
}
```
Executing the following SQL:
```sql
UPDATE test INCREMENT map.bar = 2
```
Results in the following error:
```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " "." ". "" at line 1, column 26. Was expecting: "=" ...
```

This can be replicated using studio and Java code.

**Comment by mmacfadden** [comment]
Here is a Gist / Unit Test that replicates the issue.  The issue appears to be in the parser.

https://gist.github.com/mmacfadden/162b60acf9593c13fa45

**Comment by mmacfadden** [comment]
Upon more research there is a work around for this.  After reviewing the parser.  The problem is that it is consuming just the first part of the identifier.  So if the identifier is "map.nestedCount" then the parser will just consume "map".  The next token it looks for is "=".  Instead it finds a ".".  this causes an error.

If we use a QUOTED_IDENFIER, which is normally to user reserved keywords, the UPDATE INCREMENT will work.

So this will work:

```SQL
UPDATE test INCREMENT `map.nestedCount` = 5
```

Where this will not:

```SQL
UPDATE test INCREMENT map.nestedCount = 5
```

The parser will consume the whole identifier.

**Comment by mmacfadden** [comment]
Upon more review of the parser I think I have found the issues.  I noticed that the "UPDATE SET" command supports the dot notation.  So I looked for differences.  This is the grammar for the UPDATE INCREMENT:
```
OUpdateIncrementItem UpdateIncrementItem():
{}
{
    (
	    jjtThis.left = Identifier() <EQ> jjtThis.right = Expression()
	)
	{ return jjtThis; }
}
```
It's just looking for a basic identifier, followed by equals, followed by an expression.  On the other hand the UPDATE SET looks like this
```
OUpdateItem UpdateItem():
{}
{
(
	jjtThis.left = Identifier()
	[ jjtThis.leftModifier = Modifier() ]
	(
	    <EQ> { jjtThis.operator = OUpdateItem.OPERATOR_EQ; }
	    |
	    <PLUSASSIGN> { jjtThis.operator = OUpdateItem.OPERATOR_PLUSASSIGN; }
        |
        <MINUSASSIGN> { jjtThis.operator = OUpdateItem.OPERATOR_MINUSASSIGN; }
        |
        <STARASSIGN> { jjtThis.operator = OUpdateItem.OPERATOR_STARASSIGN; }
        |
        <SLASHASSIGN> { jjtThis.operator = OUpdateItem.OPERATOR_SLASHASSIGN; }
	)
	jjtThis.right = Expression()
) { return jjtThis; }
}
```
This adds an optional Modifier() call. The call to modifier will consume the rest of the dot notation identifier.  Note that the modifier is a linked list, where it will consume each token and then link to the next modifier.  Regardless, this will consume the remaining tokens before looking for a operator (like "=").  So it looks like there is a difference between how SET and INCREMENT are being parse.

Using backticks "`" to quote the dot notation is required in the INCRMENT to allow the Identifier() call to consume the whole string, whereas the SET will consume the whole identifier due to the call to Modifiers().

**Comment by lvca** [comment]
Thanks for the PRs, merged and closed.
