### ISSUE TITLE
`DELETE EDGE` breaks transaction in `remote` connections.

### ISSUE THREAD

**Issue by ghost** [orientechnologies/orientdb#4786]
Using version `2.0.13` the `DELETE EDGE` command seems to break transactions in `remote` connections. Please have a look at the following example:

**Schema**

    CREATE CLASS Person EXTENDS V
    CREATE PROPERTY Person.name STRING
    ALTER PROPERTY Person.name MANDATORY TRUE
    ALTER PROPERTY Person.name NOTNULL TRUE
    CREATE INDEX PersonNameUnique ON Person(name) UNIQUE

    CREATE CLASS IsFriend EXTENDS E
    CREATE PROPERTY IsFriend.out LINK Person
    ALTER PROPERTY IsFriend.out MANDATORY TRUE
    CREATE PROPERTY IsFriend.in LINK Person
    ALTER PROPERTY IsFriend.in MANDATORY TRUE
    CREATE INDEX IsFriendInOutUnique ON IsFriend(in, out) UNIQUE

**Code**

    StringBuilder sb = new StringBuilder();

    sb.append("BEGIN;");

    // Create a couple of vertex and an edge between them.
    sb.append("LET p1 = CREATE VERTEX Person SET name = :name1;");
    sb.append("LET p2 = CREATE VERTEX Person SET name = :name2;");
    sb.append("CREATE EDGE IsFriend FROM $p1 TO $p2;");

    // Uncomment the following to trigger the reported behaviour.
    //sb.append("DELETE EDGE FROM $p1 TO $p2;");

    // This will cause 'ORecordDuplicatedException', but that's intended.
    sb.append("LET p3 = CREATE VERTEX Person SET name = :name2;");

    sb.append("COMMIT;");

    OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/testdb", "admin", "admin");
    OrientGraph orientGraph = null;
    OCommandScript script = new OCommandScript("sql", sb.toString());
    Map<String, String> p = ImmutableMap.of("name1", "Peter", "name2", "John");

    try {
      orientGraph = factory.getTx();
      orientGraph.command(script).execute(p);
    } catch (OException ex) {
      LOGGER.error(ex.getMessage(), ex);
    } finally {
      if (orientGraph != null) {
        orientGraph.shutdown();
      }
    }

When I leave the `DELETE EDGE...` line commented, a `SELECT FROM Person` query shows no records (as expected). However, truncating the classes and repeating the test with the line uncommented will end up leaving the two vertexes `p1` and `p2` in the database (altough the transaction was presumably rolled back). Logs say this

```
2015-08-13 14:55:31:194 CONFIG Remote client connected from: OClientConnection [id=5, source=/127.0.0.1:56508, since=1439474131194] [OClientConnectionManager]{db=testdb} Error during transaction commit, transaction will be rolled back (tx-
id=4)
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #12:2: found duplicated key 'John' in index 'PersonNameUnique' previously assigned to the record #12:1 RID=#12:1
```

What can be causing this behaviour?

**Comment by bmcustodio** [comment]
I forgot to mention that this example is totally contrived, as I could be using Tinkerpops for this particular use case. In the real-life use case I'm using `OCommandScript` to execute a batch, and that's how I noticed the problem.

**Comment by lvca** [comment]
This is the expected behaviour, look at: http://orientdb.com/docs/last/Transactions.html#breaking-of-acid-properties-when-using-remote-protocol-and-commands-sql-gremlin-js-etc. In v3.0 we will fix this by supporting transaction flushing to the server.
