### ISSUE TITLE
Cannot load database's configuration. The database seems to be corrupted.

### ISSUE THREAD

**Issue by paymansamadi** [orientechnologies/orientdb#4787]
The Orientdb server stopped working with "java.net.SocketException: Broken pipe" error. Tried to shutdown the server, didn't work. Run a new server instance but get following error when trying to connect to my database from console. From the web GUI, it's says bad user/pass. 

2015-08-13 10:56:39:375 SEVER {db=dev_database} Internal server error:
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/home/kapa/Database/orientdb-enterprise-2.1.0/databases/dev_database' with mode=rw
--> com.orientechnologies.orient.core.exception.OSerializationException: Cannot load database's configuration. The database seems to be corrupted.
--> com.orientechnologies.common.concur.lock.OLockException: File '/home/kapa/Database/orientdb-enterprise-2.1.0/databases/dev_database/database.ocf' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database.

**Comment by zhuobao** [comment]
version: community 2.1.0
system: linux
met the same issue, restart server does not work, does not work also when using console only (with out server running) to directly access plocal. The problem happened when use pyorient to perform concurrent batch jobs.

**Comment by luigidellaquila** [comment]
Hi @paymansamadi 

The log message is quite scary, but this message typically refers to a situation where you have a server running and you try to open the database from another process in plocal.
Could you please verify that you have no active OrientDB instances while accessing it in plocal (console or external processes) and that you open one plocal connection at a time?

**Comment by dejvas** [comment]
I get the same message, but after ./backup.sh plocal:... command. (orientdb community 2.1.3). Maybe the message "The database seems to be corrupted." is a bug because db isn't actually corrupted, but we have just another (working or broken) process running in plocal. Or the message com.orientechnologies.orient.core.exception.OSerializationException: Cannot load database's configuration. The database seems to be corrupted." is projected to be a feature?

Are you sure you covered well all of the possibilities when throwing OSerializationException?

**Comment by laa** [comment]
I am moving to 2.2.0-rc1 because that is the version starting from which we have high level exception concept.

**Comment by laa** [comment]
Hi @paymansamadi

That is harmless exception it warns that severall process access the same file, but nothing is broken at this moment.  I will provide more meaningful exception.

**Comment by laa** [comment]
Fixed
