### ISSUE TITLE
Database wouldnt startup

### ISSUE THREAD

**Issue by sajid2045** [orientechnologies/orientdb#4789]
I am running orientdb in a 3 node cluster. If I shutdown 1 cluster node and try to start it again, its stuck in the startup:

2015-08-14 14:36:55:977 WARNI Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /10.22.6.21:33124. If you are trying to shutdown the server, please kill the process [OServerNetworkListener]
2015-08-14 14:36:57:650 WARNI Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /10.22.6.23:39259. If you are trying to shutdown the server, please kill the process [OServerNetworkListener]

I gave it enough time but still it wouldn't be online. I have to delete all the data in $ORIENT_HOME/database/ & $ORIENT_HOME/backup and then it starts again. The behavior is random but goes wrong quite few times.

**Comment by luigidellaquila** [comment]
Hi @sajid2045 

could you please post the full logs for all the nodes?

Thanks

**Comment by sajid2045** [comment]
ummm...where do I attach files?

**Comment by luigidellaquila** [comment]
Hi @sajid2045 

could you please send them via email to support - at - orientdb.com

Thanks

**Comment by sajid2045** [comment]
sent

**Comment by laa** [comment]
Hi, is it possible for you open server in remote, not distributed mode ?

**Comment by flyingrobots** [comment]
We are seeing a similar issue. When we run in distributed mode and attempt to have new database host join up, the new host will randomly (and quite often) fail to fully come online.

In our experience, the stuck hosts usually stop producing output during the synchronization step when they are creating clusters for all of the classes in the database. There doesn't appear to be a recognizable pattern for these failures. If we run this experiment 3 times in a row, each failure will occur after creating a cluster for a different class, but they all will fail as they are trying to complete this step.

I would say that, based on our experience, distributed mode appears to be super broken right now (2.1.0) and is almost unusable since it is very rare to have a distributed replica come online successfully. If you have a cluster of size > 2, you are likely never going to have all instances come online successfully.

I can provide a more detailed explanation of our use case by providing logs and database files if you wish. Please let me know.

**Comment by sajid2045** [comment]
Hi , 

What do you mean ' remote, not distributed mode ' ? We are running on a 3 node cluster and the clients are thin client.

-Sajid.

**Comment by lvca** [comment]
@flyingrobots do you have any logs? About the logging without HZ Multicast, could you be more precise about the missing information ?

**Comment by sajid2045** [comment]
Hi Again, I now have a server that simply wouldn't join to the rest of the cluster after restart. I cleared the logs , database folder , backup folder but still no luck. I emailed the support with all the log with a full thread dump. 

Please let me know if you need more info but we need this issue to be resolved ASAP.

**Comment by lvca** [comment]
@sajid2045 In the `stackdump.txt` file you sent us I see (at the very end) the main thread is stuck on

```
"main" #1 prio=5 os_prio=0 tid=0x00007f77f400b800 nid=0x7b87 runnable [0x00007f77fd7fe000]
   java.lang.Thread.State: RUNNABLE
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabase(OHazelcastPlugin.java:908)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabases(OHazelcastPlugin.java:1350)
	- locked <0x00000000c01c5328> (a java.lang.Object)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:184)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:971)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:338)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
```

But OrientDB 2.1 on this line: `com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.java:908` there is no code:

https://github.com/orientechnologies/orientdb/blob/2.1.0/distributed/src/main/java/com/orientechnologies/orient/server/hazelcast/OHazelcastPlugin.java#L908

Please could you check in the classpath there are no jars of different releases?

**Comment by lvca** [comment]
Got it: this issue has been already fixed in 2.1.1-SNAPSHOT. We have scheduled a release for today.

**Comment by mamoit** [comment]
Sorry for reviving this, but I'm trying to migrate a db from a single node to a cluster (`2.1.16`), after the 1st node comes online with a copy of the database, it distributes it to the other nodes, but then they gets stuck `STARTING` and neither the studio nor the http api ever respond on the non-original nodes.
Any clues on what it may be? I can't seem to find any documentation on how to move from a single server to a distributed cluster.

**Comment by nsitanurag** [comment]
I am also observing the same issue. in version 2.1.16 where one server is copying data to 2 other nodes in a 3 node cluster.

**Comment by andreaiacono** [comment]
@mamoit you're right, I've just added it now here: http://orientdb.com/docs/last/Tutorial-Setup-a-distributed-database.html (it works also for 2.1 branch)
Have you followed these steps?

@nsitanurag are you coming from a standalone server as well?

**Comment by mamoit** [comment]
@andreaiacono Thanks for the doc :+1: it validated my course of action.
I could not unstuck the other nodes of `2.1.16` at all, so I just abandoned it and we are currently evaluating `2.2.0`.

**Comment by lvca** [comment]
@mamoit do you have the same problem with 2.2?

**Comment by mamoit** [comment]
@lvca No. Never happened with `2.2.0` and none of the snapshots that I've tried for the past monthish.

**Comment by lvca** [comment]
Cool, thanks for the feedback. I'm closing this issue.
