### ISSUE TITLE
Questions on Pattern Match in 2.2

### ISSUE THREAD

**Issue by wuxianliang** [orientechnologies/orientdb#4791]
Excited to read docs of Pattern Match. That is a graph database should be!
Questions are

(1) We need the quantity only sometimes but data, is calculation supported in "RETURN"? It should be clear in Documents.
```SQL
RETURN eval( a.count() / b.count() ).asFloat(2) // we want to calculate the probability sometimes.
```

(2) We use the probability in (1) as parameters, so is "LIVE MATCH" supported just like LIVE QUERY?
```SQL
LIVE MATCH {
    ...
}
RETURN eval( a / b ).asFloat(2) // we want to calculate the probability in real time.
```

(3) Examples need to be explained in JSON. "RETURN person, friend" this is unclear semantically.
```SQL
MATCH {
    class: Person, 
    as: person, 
    where: (name = 'John')
  }.both('Friend'){
    as: friend
  }
RETURN person, friend
```
return "all person whose name is John, together with their friends", in which form? 
person = {name: "John", friend: [ Tom, Jerry ]} 
or 
person = [{name: "John", friend: Tom } , {name: "John", friend: Jerry }]
 Can we use another forms we want? and how?

(4) Performance. Best Practices(suggestions). Robust(no offenses).
OrientDB SQL is a killer feature. MATCH will be the killer amongst killers. I definitely will use MATCH heavily with time series of stocks. Hope to see it a.s.a.p like LIVE QUERY, and robust forever.

(5) a little typo, search "pattenr", then fix it.

Keep going! Man.

**Comment by lvca** [comment]
@wuxianliang Thanks for the points, they are all interesting. Tomorrow @luigidellaquila will take a look at this issue and will provide you his point of view ;-)

**Comment by luigidellaquila** [comment]
Hi @wuxianliang 

all this makes definitely sense. In detail:

(1) right now it's not supported, but you can achieve the same with an outer select, eg.

```sql
select  eval( a.count() / b.count() ).asFloat(2) from (
    MATCH ...
    RETURN a, b 
)
```
It's not hard to implement anyway, I think it will be implemented before the final release of 2.2

(2) LIVE MATCH is not trivial, I'm afraid it won't be available in 2.2, but I'll what we can do...

(3) good point, docs are still a work in progress (they are not linked yet to the official documentation actually). Anyway, in your example the result will be the second one

(4) 
performance: the first implementation seems to be enough efficient, but I'm sure there is a lot of room for optimization, I expect a lot of improvement on this in next weeks/months

best practices: they will come with final release, my goal is to have a "smart" engine that can optimize the execution without particular suggestions. Of course, in the first release I'll introduce some "tips" for the engine, like explicitly defining the root node/s, I'm still defining the syntax, news will follow

robust: it's the main focus for all OrientDB team, we are paying a lot of attention to test coverage and we are improving a lot on this. Pattern matching will be no exception.
I have my test cases, but end user tests are the best to find bugs, so if you have a chance to try it, please report any problems. It's already available in 2.2.0-SNAPSHOT (https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.0-SNAPSHOT/) and in ```develop``` branch.

(5) got it, thanks :)

**Comment by wuxianliang** [comment]
@luigidellaquila Thank you very much, I am starting to try this feature.

**Comment by luigidellaquila** [comment]
Hi @wuxianliang 

FYI, I just implemented the support for expressions in RETURN block
