### ISSUE TITLE
Query performance question

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4792]
Hi Luca

I have a query performance question for you.

Given the following vertices and edges classes and relations

A -- vertices --> B -- devices --> C -- outputports --> D -- port --> E -- stream --> F -- record --> G (field name)
A -- vertices --> B -- devices --> C -- inputports --> D -- port --> E -- stream --> F -- record --> G (field name)

The field name of G can have one of 2 values: "LogicalSource" and "LogicalDestination"
The edge between C and D can be labelled either "outputports" or "inputports"
I want to query all instances of F attached to one specific instance of A.
The instances of F must go in one of 2 collections depending on the value of the field name in the G instance connected to F.

I've done a test with a setup where there are 2K instances of F (evenly distributed between LogicalSource and LogicalDestination)
I've tried a fair amount of ways to query (SQL calls, traverse and pipeline variants) to get the best performance. The best query I've found is the following. 
Do you have suggestions on a better query?

Thanks,
Daniel

       List<OrientVertex> logicalSources = new ArrayList<>();
       List<OrientVertex> logicalDestinations = new ArrayList<>();
       Map<String, List<OrientVertex>> grouped = new HashMap<>();
                   
       GremlinPipeline pipe = new GremlinPipeline();
       pipe.start(graph.getVertex(rootId)).out("vertices")
      .out("devices").out("outputports","inputports").in("port").in("streams").groupBy(grouped, new PipeFunction<OrientVertex, String>() {
         @Override
         public String compute(OrientVertex v) {
            Iterable<Edge> edges = v.getEdges(Direction.IN, "record");
            if (!edges.iterator().hasNext()) {
               return "";
            }
            
            Edge e = edges.iterator().next();
            Vertex t = e.getVertex(Direction.OUT);
            return t.getProperty("name");
        }
       }, new PipeFunction<OrientVertex, OrientVertex>() {
         @Override
         public OrientVertex compute(OrientVertex v) {
            return v;
         } 
       }).cap().next();
       
       logicalSources = grouped.get("LogicalSource");
       logicalDestinations = grouped.get("LogicalDestination");

I forgot to mention that the java code and the OrientDB and in the same VM (plocal connection).

**Comment by luigidellaquila** [comment]
Hi @ylopotun 

if you do not need filtering in the middle this is probably the best query you can write for this use case.
What is the performance of this query on your db?

**Comment by Daniel-Valliere** [comment]
In our system and with the test case I've done, the query populates 2 collections of equal size. I've run 3 different tests. One returning 2K records split in the 2 collections, one return 10K results and one returning 200K results. For each test, the same query is called 10 time in a row. I'm giving you the performance for the first call and the average of the 10 calls (as expected first calls is slower).

1k/1k collections: First call 586ms   Average of 10 calls: 250ms
5k/5k collections: First call 1081ms  Average of 10 calls: 472ms
100K/100K collections: First calls: 8009ms  Average of 10 calls: 6881 ms

FYI, if I change the schema and create an edge between A and F and the edge allows removing the filtering, the times are significantly better as expected.
1k/1k collections: First call 156ms   Average of 10 calls: 54ms
5k/5k collections: First call 338ms  Average of 10 calls: 135ms
100K/100K collections: First calls: 2129ms  Average of 10 calls: 1498 ms

Thanks for confirmation that the query as written above, given the restriction, is probably the best.

**Comment by luigidellaquila** [comment]
Thanks for the details @Daniel-Valliere 
I think I can close this, if you need further details or help please reopen
