### ISSUE TITLE
Protocol version 30 is not supported.

### ISSUE THREAD

**Issue by tellyarz** [orientechnologies/orientdb#4798]
Whenever I try to make a query through the php api, I get the error message "Protocol version 30 is not supported." I just got an enterprise version 2.1.0 edition. I noticed it only happens to the 2.1 version, does not have the problem with the 2.0 version.

**Comment by smolinari** [comment]
Are you using version 1.2.0 of the driver?

https://github.com/Ostico/PhpOrient/releases/tag/v1.2.0

Scott

**Comment by tellyarz** [comment]
no, I am using 1.1.9 just checked it.

**Comment by tellyarz** [comment]
Thanks smolinari, v1.2.0 fixed the problem
