### ISSUE TITLE
Create class when trying to insert into non-existing class

### ISSUE THREAD

**Issue by chrismichaels84** [orientechnologies/orientdb#4801]
We are working on a php library that normalizes graph database abstraction and provides a high-level query builder, schema builder, and models. It's called [spider](http://github.com/spider/spider). Right now, there are drivers for Neo4j, Gremlin Server (TP3), and (what my team uses) OrientDB.

The have run into an inconsistency between how orient handles creating records and the rest. You can see the discussion at spider/spider#41. 

Neo4j and Gremlin have no concept of Classes (which is one reason we chose Orient), but we have found that the following fails if the class "person" does not exist.

`INSERT INTO person CONTENT {name: 'michael'}`

In the others, where we take class to be label, the label is simply created if it doesn't already exist. This seems more graceful to me.

Is there a workaround that I'm missing, or is this the purposeful behavior? If so, what is the justification?

**Comment by smolinari** [comment]
I'd like to add that one of the beauties of NoSQL is to not be locked into SQLesqe issues with programming, namely things like schema versioning or needing any DDL. Anything ODB can offer to refrain from needing SQLesque stuff, would be a great advantage over any SQL database and would put it rightfully in a NoSQL basket (which it currently really isn't).

This "paradigm" of NoSQL is one of the calling cards of MongoDB, for instance. Yes, it means clearly, the schema must be regulated at application level, but a I feel a true document store, which also offers graph modeling and persistence (the huge step above MongoDB!!!!), should be able to offer this out of the box too. It would basically make persistence for the application a real no-brainer. To show what I mean, here is a great article on the subject of the issues with schema and SQL in code and how MongoDB avoids most of it. 

https://www.mongodb.com/blog/post/mongodb-vs-sql-day-1-2

Can ODB offer the best of both worlds? The natural feel of SQL to query data, but still have the flexibility of schemaless design? 

If ODB could get there, then wow. Just an incredible....Wow! :smile: 

Scott

**Comment by chrismichaels84** [comment]
I wouldn't want orient to become totally schemaless. I value the structure of classes and use them consistently in my applications. I would just like the option for something like:

`INSERT INTO person CONTENT {name: 'michael'} CREATE CLASS` which would create the class if person does not exist.

**Comment by smolinari** [comment]
Yes, and the same I think should be valid for inserting field data too. I'd actually say, when you have

`INSERT INTO person CONTENT {name: 'michael'}`

and the person class is missing. Then both the class and the field should be created automatically without failure. If I then also do 

UPDATE person SET first_name = 'michael' WHERE name = 'michael' `

Then ODB also just goes on and creates the new field `first_name` and adds the data.

Scott

**Comment by chrismichaels84** [comment]
I don't know what you mean by that. The properties are handled in a schemaless way, so inserting a property that doesn't exist is already supported. I wouldn't want a field to be created in the class unless I create it. How would you manage datatypes? What if `name` can be a string or a list? I think altering classes should be an explicit function.

**Comment by smolinari** [comment]
> How would you manage datatypes? 

Just like the schema, any data types are also managed in the application. What is stored in the field for the database is what is stored in the field from the application.

The whole concept is to avoid the need to create the schema with any DDL/DML commands. If I want to insert data, it just inserts the data, and the schema is allowed to be dynamic. It is a core attribute of MongoDB.  

As MongoDB puts it in their faq. 

 >In practice, it is common for the documents in a collection to have a largely homogeneous structure; however, this is not a requirement. MongoDB’s flexible schemas mean that schema migration and augmentation are very easy in practice, and you will rarely, if ever, need to write scripts that perform “alter table” type operations, which simplifies and facilitates iterative software development with MongoDB.

Scott

**Comment by chrismichaels84** [comment]
This is already supported. You don't need any schema inside a class in order for it to do what you want. if you `INSERT INTO person CONTENT {name: 'michael', birthday: 'february'}` and either name or birthday don't exist as a property, the information will still be added and you can query to your hearts content.

What makes Orient different (and special to me) is that you *can* enforce *optional* schema if you choose by adding properties to classes. For instance `CREATE PROPERTY person.name STRING` would add that property to the schema. Now `person` is schema-mixed. This is totally optional. You can also make that property required or close a class to inserting schemaless data, and there are use cases for that.

All that to say, what you are looking for is already supported, I think: automatic creation of properties when they don't exist. What isn't supported is the automatic creation of classes when they don't exist.

That said, if you would like to see schema handled differently, it's probably worth opening a separate issue and referring to this one.

**Comment by nagarajasr** [comment]
IMO to define a class without properties does not really serve much purpose other than as a 'marker' interface, and even then, leaving it to the DB client to define arbitrary classes while inserting data is quite pointless. also consider that automatic indexes can only be created on class properties. so i'd consider DB class design very important part of the overall application design. i'd consider that the core attributes of the domain model be represented in a schema-full model, with application specific fields allowed to be more flexible, in the schema-less portion of the DB model.

**Comment by chrismichaels84** [comment]
My use case may be an edge case, which is why I debated opening the issue at all, but I wanted to see if others had the same situation.

I am using orient in conjunction with other graph databases, which all have the concept of a label and no real concept of schema beyond that. Even then, a label is just a property that is given some significance in the query (as far as I can tell).

I am using class as analogous to label. 

In the others, creating a record *and labeling* it with a label that has not been created throws no exceptions. 

In orient, creating a record *inside* a class that doesn't exist, I get an exception.

Is there a better way to normalize this behavior?

**Comment by lvca** [comment]
@chrismichaels84 I understand you use case and it could be supported easily in OrientDB. This could be a setting at database level, something like:

    ALTER DATABASE SET autocreateclasses = true

WDYAT?

**Comment by smolinari** [comment]
:+1: 

Scott

**Comment by chrismichaels84** [comment]
That would be perfect. I appreciate all the work you all do.

**Comment by StarpTech** [comment]
+1

**Comment by a-unite** [comment]
Dear Luca,

I'm sure, that

ALTER DATABASE SET autocreateclasses = true


command will have to be applied explicitly to not brake existing use cases.

But what I actually wanted to ask:

INSERT INTO person CONTENT {name: 'michael'}

What should be this class's parent, if used in Graph database?
Is it vertex and direct subclass of V then?

With best regards,
Ata

**Comment by lvca** [comment]
it would have no parent. But if you'd do CREATE VERTEX it would create a Vertex class and with CREATE EDGE an Edge class.

**Comment by a-unite** [comment]
yeah, I'm sorry, it was a stupid question. used to always forget that non-vertex/edge classes are also possible in graphdb mode

**Comment by lvca** [comment]
Not relevant anymore, closing it.
