### ISSUE TITLE
index enhancement

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4802]
ciao,
Using orientdb in real programming i observed 2 cases in which it is difficult to write a good code.
1) you need to index nested property in a class. For example
A{int f , string s} , B{ A a, string c }

i want create a composite index  on class B { a.f , c} where a.f is a nested property. 
The just solution now is to write a manual index. 

2) pagination with index is not possible. 
yes you can use a parent select for filtering ... but if the result set is huge is not a good solution. Not in all cases you can organize logic and classes for creating indexes returning few data by  queries. This is the assunption justifying this post. 

I imagine that it might be simple to introduce a skip instruction in index ... when skip the first N element of index. it is very perfomant anyway. 
Another solution can be done. This would be the queen solution. It is very abstract and solve also all the perfomant problems with big data. 
Orientdb might introduce a cursor in its internals. When you use a nested select , orientdb returns

<pre>
- a cursor (not result set) 
-a class containing the compiled code for filtering (compiled filter) 
</pre>

So when the parent select is executed it callls the cursor , executes the child filter until it finds a item , then the parent filter is executed ...and so on. The root query passes the item filtered to stream.  Obviously the result set is resurned as a stream ... so server have no load internally and not problem of out of memory in any case. Engine processes just a item for every step. Pratically is a recursive research passing cursor and compiled filter.  
In this way you have a lot of advantages:
1) you scan the elements once
2) you keep in memory( in searching phase) just a element O(1)(and not all the entire result set as  before)
3) no problem with out of memory with huge result set
4) you can extend api for use cursor also by programming 
5) use a lot of nested select is no more a problem 
6) you can really use database also in enbedded systems with few memory (possible use in robotis?? where you have big database but little processors and memory)
7) probably you emprove time perfrmance for big research because elements are scanned just once.

**Comment by flyingrobots** [comment]
Cursors would be awesome, the current pagination technique is very limiting. Skip and limit don't really let you effectively "page" through data sets that are constantly changing.

**Comment by lvca** [comment]
Implemented cursor in v3.0
