### ISSUE TITLE
2026359840 in connections 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4803]
when i write a select where there is a condition as 

2026359840 in connections 

where connections is a embeedded Set of Long values 

it dont works

**Comment by lvca** [comment]
This could be a problem of conversions. Please could you post a test case or a sequence of SQL commands that reproduce it?

**Comment by publicocean0** [comment]
select from (select expand(rid) from index:A where key = 'prova' )  where 2026359840 in connections.

Yes i confirm .... the syntax dont permits to specify if 2026359840 is Long or Integer ... or ... so equals operator return false.

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

I just tested this and it seems to work fine on 2.2.11

Can you please confirm this?

Thanks

Luigi

**Comment by publicocean0** [comment]
yes now it works

**Comment by luigidellaquila** [comment]
Great, thank you very much!

Luigi

**Comment by publicocean0** [comment]
thanks to you :)
