### ISSUE TITLE
shutdown issue 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4805]
hi i found a problem with shutdown code introduced in orientdb. 
The shutdown in orientdb are not handled directly using java shutdown hook but with SignalHandler.
It gives more possibilities but gives also a side effect. The handlers is executed not following the right order in closing VM.
the right order is .... before VM call all hooks installed, deregistring other handlers, close classes destroying data before to exit ... and then the database connections are closed.
The connections to database might be closed in the ending , not in the beginning of shutdown.
Now it is possible the connections are closed before the VM is completing to destroy data in the VM. 
In my code now i have this problem .... a hook find the connection already closed in the while it want save status of server before to shutdown. 
the machine is closed calling CTRL+C.

**Comment by publicocean0** [comment]
this is a prototype of the class introducing priority ...
<pre>
public class PriorityShutdown implements Runnable {
	IdentityHashMap<Thread, Thread> currentHooks=new IdentityHashMap<Thread, Thread>() ;
	
	static class TBlock implements Comparable<TBlock>{
		final Thread thread;
		final int priority;
		public TBlock(Thread thread, int priority) {
			super();
			this.thread = thread;
			this.priority = priority;
		}
		@Override
		public int compareTo(TBlock o) {
			return priority-o.priority;
		}
		
		
	}
	
	PriorityQueue<TBlock> queue = new PriorityQueue<>();
	public PriorityShutdown() throws NoSuchFieldException, SecurityException, ClassNotFoundException, IllegalArgumentException, IllegalAccessException {
		super();
		
		 Field hooksField = Class.forName(
				    "java.lang.ApplicationShutdownHooks").getDeclaredField(
				    "hooks");
				  hooksField.setAccessible(true);
				  @SuppressWarnings("unchecked")
				IdentityHashMap<Thread, Thread>  tcurrentHooks = (IdentityHashMap<Thread, Thread>) hooksField
						    .get(null);
				  currentHooks.putAll(tcurrentHooks);
				  tcurrentHooks.clear();
				  Thread h=new Thread(this);
				  tcurrentHooks.put(h,h);
	    
	}
	 public void add(int p,Thread t){
		 queue.add(new TBlock(t,p));
		 
	 }
	 void runHooks() {
	        Collection<Thread> threads;
	        
	        synchronized(PriorityShutdown.class) {
	            threads = currentHooks.keySet();
	            
	        }

	        for (Thread hook : threads) {
	            hook.start();
	        }
	        for (Thread hook : threads) {
	            try {
	                hook.join();
	            } catch (InterruptedException x) { }
	        }
	    }

	@Override
	public void run() {
		while (!queue.isEmpty()){
			Thread  tt=queue.poll().thread;
			tt.start();
			try {
				tt.join();
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}  
		runHooks();
	}
	

}
</pre>

**Comment by publicocean0** [comment]
you can had a hook when the signal is notified .... so it is added in the end of the list ... or you can use this class with a very low priority....

**Comment by publicocean0** [comment]
in addition when you press CTRL+c in the starting or shutodown phase ... the server go in loop now.....

**Comment by laa** [comment]
you rely on class implementation internals it may cause problems on non Oracle JVM vendors. But we should fix this problem for sure.

**Comment by PhantomYdn** [comment]
@publicocean0 , if you manage life-cycle of your application I recommend to disable shutdown hooks in OrientDB and invoke that according to lifecycle of your app.

**Comment by publicocean0** [comment]
yes ... how is possible to disable the shutdown hooks in Orientdb, i saw it using signal handler hot sun java hook for shutdown.

**Comment by PhantomYdn** [comment]
You can find my code for embedding OrientDB into webapp here:

https://github.com/OrienteerDW/wicket-orientdb/blob/master/wicket-orientdb/src/main/java/ru/ydn/wicket/wicketorientdb/OrientDbWebApplication.java

Especially pay attantion to this:

```java
getApplicationListeners().add(new IApplicationListener() {
			
			
			@Override
			public void onAfterInitialized(Application application) {
				Orient.instance().startup();
				Orient.instance().removeShutdownHook();
			}
			@Override
			public void onBeforeDestroyed(Application application) {
				Orient.instance().shutdown();
			}
		});
```

**Comment by publicocean0** [comment]
thanks :)  i ll try to use this code

**Comment by publicocean0** [comment]
I tried it .... but the problem is not so simple as described. 
Even if i force to remove shutdownhook with 
Orient.instance().removeShutdownHook();
Orient on shutdown will execute the listeners that first at all remove threadlocal for db instance... all the layers above cant execute the call to database. 
So i investigated to orientdb listeners. The listeners are surely a good idea to handle transversally the database events from different points in the software. But there is a bug for my opinion. 
When the server start up , it registers the listeners in a specific orders... normally this order is so:
register listeners for 
1) add listeners for threadlocals
2) add custom listeners (in my case add code for saving data to db)

when server shutdowns the order might be reverse. 
1) execute custom listeners (before point 3) 
2) execute thread local listners...

But Orient class dont permit to reverse the order because the data structure is a Set not a Queue.
It execute the order as it is registered. so before it remove trhead local , then it try to save data giving exception :)

**Comment by PhantomYdn** [comment]
What version are you using? Something from your description were fixed in #3042.
For my product ([Orienteer](https://github.com/OrienteerDW/Orienteer)) OrientDB capabilities for embedding and external management of db lifecycle are working perfectly starting from 2.0.

**Comment by publicocean0** [comment]
Version is orientdb-community-2.1-rc2. My db is not embedded. The server there is just the client for connecting to remote orientdb.

**Comment by lvca** [comment]
@publicocean0 are you sure OrientDB didn't start the shutdown procedure while you're trying to save?

**Comment by publicocean0** [comment]
yes , i explained logically the problem above ... the cause of the problem and also a possible solution. 
Now I removed all default listeners and inserted a custom listener for saving, for now (im not in production)  it work, but it is a stub solution .... putting just a element in a list of listeners it has always the most priority. But obiously is not a soddifying solution , and i have a lot of side effects also in shutdown removing your listeners. 
The problem is cause the registration of listeners order is equal to class loading .... in shutdown you have to follow the reverse order else you destroy data structure , threads ,.... used by class above in the stack.

**Comment by publicocean0** [comment]
i found 

<pre>

    final Orient inst = Orient.instance();
    inst.registerListener(new OOrientListenerAbstract() {
      @Override
      public void onStartup() {
        if (INSTANCE == null)
          INSTANCE = new OExecutionThreadLocal();
      }

      @Override
      public void onShutdown() {
        INSTANCE = null;
      }
    });

</pre>
 why ? 

  public void onShutdown() {
        INSTANCE = null;
 }

instead  public void onShutdown() {
        if (INSTANCE != null) INSTANCE.remove();
 }

**Comment by laa** [comment]
I think we may implement our own priority queue of shutdown inside of our shutdown handler. So you may put your handlers there too.

**Comment by laa** [comment]
Fixed look at Javadoc com.orientechnologies.orient.core.shutdown.OShutdownHandler

**Comment by publicocean0** [comment]
I will check on webapp, but Threadlocals instances set by Orientdb Client are not traceble by the application.
When there is a http request, http server takes a Thread from pool and makes running it on the specific request, so in that thread when client orientdb dont find Threadlocal,  set  it. So it is  registered internally in that Thread by jvm. Executing many requests , http server uses all the threads of pools , so it set orientdb threadlocal in all the Threads of pool. The same Threads of pools are used also by other web applications. 
On shutdown tomcat close the application in another Thread (but it dont close threads of pools where there are the reference of old threadlocals), because it is not a request. You are in another phase.  The ufficial ThreadLocal.remove , is a api removing ThreadLocal just in the current executing Thread. For this reason I posted SafeThreadLocal because from every Thread/Context , you could remove ThreadLocals, knowing what are the Threadlocals instances references for every Thread. You can deducting it just when you are setting or using  ThreadLocal instance. 
SafeThreadLocal is not tested anyway. 
This is a problem not related to specific application but it is a memory leak present in all server container using a Thread Pool running orient client. Probably not all of http servers notify the memory leak. 
There is a old version of Tomcat deprecated attempting to removing memory leaks caused by ThreadLocal, I tried to use it for curiosity but it cleans 90% of them , not alls.  Anyway now they removed this behaviour by apache developers because it is considered not a correct way to solve the problem.

**Comment by laa** [comment]
Hi @publicocean0 
We are aware about memory leak with thread locals in case they are static.
That is why we use shutdown listeners with volatile thread local fields to clean them on engine shutdown. Your proposal with safe thread local relies on internal implementation of classes so we can not use it.

**Comment by publicocean0** [comment]
ok , so now if i understand correctly orientdb threadlocals are removed by engine on shutdown. No more Severe notifications. cool
