### ISSUE TITLE
Error in deleteOrfans 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4811]
the class Ti has

	@OneToMany(targetEntity = Conn.class,orphanRemoval=true,cascade={CascadeType.ALL})
    private Set<IConn> connections;
---------------------------------------------------------------------block of code------------------
OObjectDatabaseTx db = db();

		List<IConnection> list;
		try {
			//db.begin();
			do {
				list = db

				.command(new OCommandSQL("select  from ( select expand(rid)  from index:Con.n where key = " + n + " limit 100 )")).execute();
				for (ICon c : list) {
					Ti  t = ((Ti) ((Con ) c).getTi());
					t.getConns().remove(c);
					//db.delete(c);
					db.save(t);
				}
				//db.commit();
			} while (!list.isEmpty());
		} catch (Exception e) {
			db.rollback();
			e.printStackTrace();
		}
		return;

-------------------------------------------------------------------

error 

com.orientechnologies.orient.core.exception.ODatabaseException: Cannot delete null document
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:2321)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.deleteOrphans(OObjectDatabaseTx.java:828)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:443)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:380)

-----------------------------------
debug behaviour .... the deletion is not working in cascade way ... so then second loop 
it found the same items (  really less then before , why?? ) ... and then when it try to delete the second time the same con .... give exception

**Comment by tglman** [comment]
fixed,

closing
