### ISSUE TITLE
not correctly reading input in console.sh?

### ISSUE THREAD

**Issue by gg4u** [orientechnologies/orientdb#4812]
It is not really an issue, but maybe an improvement: sometimes it happens that the console.sh cause an issue in typing an input, and repeat the input for every keyword typed. So you can have misbehavior for erading a line, but actually it s not the interpreted cause the input typed does not correspond to what you read. 

As example, this is what 's happening; I ve just entered an input from history (up arrow in terminal), then new keystroke will appear in the middle of hte line.
Closing the console (cmd+'.') will halt the terminal window, and need to start over again.
<img width="565" alt="screen shot 2015-08-18 at 11 13 52 am" src="https://cloud.githubusercontent.com/assets/284214/9326431/009d36ce-459a-11e5-8b6e-ad293a345de5.png">

![Uploading Screen Shot 2015-08-18 at 11.20.57 AM.png…]()

**Comment by lvca** [comment]
You should use `INFO CLASS <class-name>`. Example: `info class OUser`
