### ISSUE TITLE
Improve SQL UPDATE syntax

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4814]
Today we have an ugly syntax for SQL UPDATE regarding collections, arrays and maps:

``` sql
// ARRAY AND COLLECTIONS
UPDATE #13:44 ADD books = #3454
UPDATE #13:44 REMOVE books = #3454

// MAPS
UPDATE #13:44 PUT books = 'new', #3454
UPDATE #13:44 REMOVE books = 'new'
```

We could rather add the support for this alternative syntax much easier to read:

``` sql
// ARRAY AND COLLECTIONS
UPDATE #13:44 SET books ADD #3454
UPDATE #13:44 SET books REMOVE #3454

// MAPS
UPDATE #13:44 SET books PUT 'new', #3454
UPDATE #13:44 SET books REMOVE 'new'
```

**Comment by nagarajasr** [comment]
is there also a possibility of allowing ADD and REMOVE operations in a single command? 
```
UPDATE #13:44 SET books ADD #34:54 REMOVE #34:22 
```

**Comment by lvca** [comment]
Yes, this is also supported with old syntax by using comma (,) to separate statements.

**Comment by lvca** [comment]
Already defined a syntax in v3.0
