### ISSUE TITLE
Question: how to model undirected graph in import, query for shortest paths, and optimize resources ?

### ISSUE THREAD

**Issue by gg4u** [orientechnologies/orientdb#4815]
Hi, my model is an undirected graph.
My question is about a best way to imported and create a schema, taking into account also traversal.
While reading tutorial, I've read that relationships will always be O(1) - :+1:  However, I wonder if redundancy of information can be avoided (e.g. avoid double insertion of edges A>B, B>A) and keep the size of db smaller for my purposes, so to optimize resources in production (RAM, costs).

The queries I'd like to run are: first neighbors of a vertex (undirected); clustering algorithms and shortest paths (undirected); links between a vertex and vertex neighbors in clusters; first neighbors against vertexes matched with full-text.
 
Will the order of nodes in import affect these queries?

As example, I could export my data in csv and will have table redundant edges (A>B, B>A); if double edges are removed, a table list like will be produced.
A (no edge)
B (no edge)
C, (> A, > B)

That means, given a dataset of millions of records, you will have huge clusters (in this example, C), pointing out to many many leaves, so the topology of the graph-db would result very different from my actual graph (smaller hubs, small-world).

I would like to ensure that:
1) order in import won't affect traversal and shortest paths
2) how to query the graph with undirected links
either:
3) if it is best to insert double links anyway:
(that is, should I *CREATE EDGE rel FROM #11:1 TO #11:2*  and also *CREATE EDGE rel FROM #11:2 TO #11:1* ?)

Finally, about size of db:
4) how much is the size of a link and vertex, to roughly estimate final size of db? Any link to estimate a machine required in production (AWS or alike) and minimal RAM? 
thank you

**Comment by luigidellaquila** [comment]
Ciao Luigi,

direct links are first class citizens in Document model, you can use them
in OrientDB without any problems.
This said, you have to keep in mind a couple of things, to be sure you will
not have problems:
1) traversing a link and traversing a lighweight edge is exactly the same
in terms of performance
2) links can be traversed only in one direction, if you need back traversal
you have to do a query (maybe on an index)
3) when you remove a linked document, the links will not be updated/removed
automatically, you have to manage it manually

The size of a link is the sum of the link property name (as a string) and
the link itself, that is a long plus a short (ten bytes in total). On disk
there are some optimizations, so it can be a little bit less in some cases.

In general, I suggest you to stay with regular edges, because the
advantages are typically more than the disadvantages.

To do an estimation of memory and disk, a document size is the sum of:
- ~50 bytes (envelope)
- byte array representation of field names (if you are working schemaless
mode, otherwise it's one or two bytes per field)
- byte array representation of field values
- +20% oversize (tunable, padding left for updates)

Luigi




2015-08-18 12:07 GMT+02:00 Luigi <notifications@github.com>:

**Comment by gg4u** [comment]
Hi @luigidellaquila my model is undirected weighted graph.

1) A typical query I will do, is to fetch the neighbors of a node; keep in mind they are undirected, so:
A-[rel]-B 
where B are neighbors of A
is the same as B-[re]-A
where A neighbors of B.

You pointed that:
     links can be traversed only in one direction, if you need back traversal
     you have to do a query (maybe on an index)

Could you please write a short example for the query above, enabling fetching first neighbors from A to B and viceversa if edges are arbitrarily directed?
It is not clear to me how would you use an index.

I understood links could be traversed backwards using both() notation.
http://orientdb.com/docs/2.0/orientdb.wiki/Tutorial-Working-with-graphs.html
E.g. Using cypher notation in another graph technology (neo): ()-[]-() is the same as ()->[]->() and viceversa. Does the both() notation in orient have same meaning?

2. Which are the side-effects to use an index for "backward" traversal and duplicate the links (from A to B and viceversa ?)
I wonder which is fastest (also for algorithms as djikstra) and which is compact in term of size on the db.

3. Is a weighted edge to be modeled as link instead of lightweight edge, because it has weight property, correct?

**Comment by luigidellaquila** [comment]
Hi Luigi,

both() operator has exactly the same meaning of ()-[]-()  for Neo.

Regarding the backward traversal of links, here is an example:
Suppose you have a record A with a "neighbor" attribute pointing to B

You can get neighbors of A doing

SELECT expand(neighbor) from A

to do the opposite (neighbors of B) you have to do

SELECT from MyClass where neighbor = B

In the first case you are traversing a physical link, so you do not need
indexes; in the second case you need an index on "neighbor" field to
optimize the query.

With an edge the queries would be just

SELECT expand(both("neighbor") from A
SELECT expand(both("neighbor") from B

and indexes would need at all.

A weighted edge is modeled as a document, so you will have

Document A -> EdgeDocument (with properties, eg. weight) -> Document B

Luigi




2015-08-25 10:57 GMT+02:00 Luigi <notifications@github.com>:

**Comment by gg4u** [comment]
Mmm thank you, it looks to me it is less complicated to replicate A and B, being all nodes in my db have neighbors of the same class.

Is there any example for using djkstra and allshortestpath() with a weighted graph in orient?
So basically, and EdgeDocument is just another node in the graph.. correct?

**Comment by gg4u** [comment]
Hi Luigi,
is an *edge with property* a class extending a vertex or extending an edge?

About a weighted graph connecting items from class "entity", to items of same class: 
could you provide which option would it be the best in terms of performance, keeping in mind I will do a traversal on both incoming and outcoming links?

**Otions 1#**
e.g. EdgeDocument should be an edge?
```
CREATE CLASS rel EXTENDS E
CREATE EDGE rel FROM ( SELECT FROM entity WHERE id = 50) TO ( SELECT FROM entity WHERE id = 70 ) **SET weight=100**
```

**Option 2#**
Or EdgeDocument should be a vertex:
```
CREATE CLASS rel EXTENDS V
CREATE VERTEX rel SET weight = 100
```
and use lightweight to link an entity A to B and viceversa:
```
CREATE EDGE link EXTENDS E
CREATE EDGE link FROM ( SELECT FROM entity WHERE id = 'A') TO ( SELECT FROM rel WHERE weight = 100 ) 
CREATE EDGE link FROM ( SELECT FROM rel WHERE weight = 100) TO ( SELECT FROM rel WHERE id='B' ) 
```

Could you clarify if I should put an index *to edge*s either *to the IDs (properties) of vertexes* connected by the link?
As example, assuming option 1# is more reasonable, since my model is undirected weighted graph, should I:
**Model #1**
a. set an index on IDs 
b. insert only incoming links, skipping redoundancy
e.g.
```
CREATE INDEX entity.id on entity (id) UNIQUE #using sb-tree here, correct? #I set an index on properties of a vertex
CREATE EDGE relationships FROM ( SELECT FROM entity WHERE id = 50) TO ( SELECT FROM entity WHERE id = 70 ) SET weight=100
SELECT expand(both(relationship) from entity where id = A #equivalent to SELECT expand(both(relationship) from entity where id = B
```

or should:
**Model #2**
```
CREATE EDGE relationships FROM ( SELECT FROM entity WHERE id = A) TO ( SELECT FROM entity WHERE id = B ) SET weight=100
```
and as well
```
CREATE EDGE relationships FROM ( SELECT FROM entity WHERE id = B) TO ( SELECT FROM entity WHERE id = A ) SET weight=100
```

?

**Comment by luigidellaquila** [comment]
Hi Luigi

an edge with properties is still an edge, so it will extend E.

From a pure performance point of view, using lightweight edges together
with EdgeDocument vertices is exactly the same of using regular edges with
properties.
Anyway, from a modeling point of view, option 1 is much better than option
2: the fact that you call "edge" a vertex is ugly per se.

About indexes, they make sense only to directly access root nodes, not for
traversal, so it depends a lot on what kind of queries you are planning to
execute. In general, I'd not put indexes on link properties for traversal,
but only on "domain" keys needed for filtering (attributes you use in the
WHERE clause of your queries)

Luigi




2015-08-26 16:21 GMT+02:00 Luigi <notifications@github.com>:
