### ISSUE TITLE
Cannot escape whitespace within Lucene query

### ISSUE THREAD

**Issue by deafmalice** [orientechnologies/orientdb#4819]
I have a few entries that contain spaces. With Lucene inserting a space separates queries. Suppose I have a few entries under class Person, with name attributes "Max Waterson", "Gerry Waterson", "Max Watson", "Cory Watney" and so on. 

If I do a query like 

    SELECT FROM Person WHERE name LUCENE "Max Wat*"

I get back all of the aforementioned entries. 

I know that in Lucene I can escape the space, thus making a query that will match entries containing spaces. But when I build a query like 

    SELECT FROM Person WHERE name LUCENE "Max\ Wat*"

I get a nice error message like ` com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 47. Encountered: " " (32), after : "\"Max\\" `. It looks like the SQL parser has some qualms with the backspace meant for Lucene. Can I escape the space in some other way?

**Comment by luigidellaquila** [comment]
Hi @deafmalice 
did you try with a double quote? eg.

```sql
SELECT FROM Person WHERE name LUCENE "Max\\ Wat*"
```

backslash is used to escape special characters (eg. \n, \t), this is why the parser is failing

**Comment by deafmalice** [comment]
@luigidellaquila, Do you mean double backslash or double quote? The examples in my post use double quotes. If I do the search with double backslashes, it returns nothing (I suspect it tries searching for the backslash as well).

**Comment by luigidellaquila** [comment]
sorry, I meant double slash...

**Comment by robfrank** [comment]
Hi, I will do some test with Lucene API. In the meanwhile can you tell me what, if configured,  analyzer are you using?

**Comment by gicuuu3** [comment]
The Full Text Lucene index is created with default settings(without specifying the analyser explicitly). According to the documentation, this means that the analyser used is the StandardAnalyser.

**Comment by robfrank** [comment]
Hi, the Standard analyzer tokenize on spaces, so spaces are not part of the text. 
You query can be written this way: "name:Max AND name:Wat*"
I will add more tests, but I think that in the query you can use the plain query syntax: https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

**Comment by robfrank** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
