### ISSUE TITLE
case sensitive issue for query filtering

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4827]
I have the following issue for field that is set to case-insensitive. 
1. select from property
   where out('locate').country[0] = 'cn'

return noting. here supposed return result as well. 
1. select from property
   where out('locate').country[0] = 'CN'

return result.

**Comment by nagarajasr** [comment]
use toLowerCase() method  and then apply the filter criteria like this:

```sql
select from property where out('locate').country[0].toLowerCase() = 'cn'
```

**Comment by martingg88** [comment]
so what is the purpose of following script since we have to manually use toLowerCase()  instead?

ALTER PROPERTY Employee.name COLLATE ci

**Comment by nagarajasr** [comment]
collate is for sorting

**Comment by martingg88** [comment]
can we treat the fields as case-insensitive if they are set to collate ci? i feel very trouble to manually care for case-sensitive query that involve fields that set to COLLATE ci.

**Comment by gongdo** [comment]
I think collate should affect both filtering and sorting.
Also it will be better if I can set collate option with scoping.
For example,
```
ALTER DATABASE collate ci    // for entire database
ALTER CLASS User collate ci  // for specific class only
ALTER PROPERTY User.name collate ci  // for specific property only
```
After alter collate, index rebuilding will be necessary, however, it'll be okay.

**Comment by martingg88** [comment]
+1. agreed collate should be applied to both filtering and sorting.

**Comment by smolinari** [comment]
I just found this older thread. 

https://github.com/orientechnologies/orientdb/issues/1842

It seems, the collate ci feature was actually added specifically for filtering. 

Scott

**Comment by martingg88** [comment]
yeap...but collate ci doesn't work for filtering and you can refer to given examples above. is it a bug?

**Comment by smolinari** [comment]
This is me going out on a proverbial limb, because I have no clue, but do you have an index on that field and was it created after the alter collation?

Scott

**Comment by martingg88** [comment]
i not sure about that.. do you think any you mention here will cause the issue?

**Comment by smolinari** [comment]
Well, not sure about this, but if the collation must be considered in the index, for the collation in the filter to work, but the index was created before the collation change was carried out, then the indexed data isn't collated properly and the filter will fail?

Scott

**Comment by martingg88** [comment]
don't think this issue is related to index. it doesn't work at all even i dropped the index. lolx

**Comment by smolinari** [comment]
Ok. That answers that question. Then it must be a bug?

Scott

**Comment by lvca** [comment]
@martingg88 Collate works on filtering. With this query:
    select from property where out('locate').country[0] = 'cn'

How did you set the collate?

**Comment by martingg88** [comment]
@lvca. It doesn't work at all .

here is how i set the collate. 

ALTER PROPERTY property.country collate ci

**Comment by petervavro** [comment]
I just got to the same issue. Could somebody tell me , will this be solved ? What is a workaround the moment please ?

**Comment by luigidellaquila** [comment]
Hi @petervavro 

This is not fixed yet unfortunately. 
As a work-around, you can use `.toLowerCase()` eg.
```
select from property where out('locate').country[0].toLowerCase() = 'cn'
```
Thanks

Luigi
