### ISSUE TITLE
add * support for .include() method.

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4828]
does .include support for \* in order to include all the fields from multiple crossing vertexes?

**Comment by nagarajasr** [comment]
sorry it is not clear what exactly you are looking for, if you want to include all fields, don't use .include() method

**Comment by mattaylor** [comment]
Then how do you suggest including a fully  expanded a reference to another doc aa part of a projection of the parent? Fetchplan?

**Comment by nagarajasr** [comment]
perhaps you need to use fetchPlan? have you already tried that and does it not meet your requirement?

**Comment by martingg88** [comment]
what is the simple and quick way to include all field for following query? It's quite irritating to specify each field in 'include' method at sometimes. 

select $creator[0].include(*) as creator from property 
let $creator = (SELECT expand(in('own')[@class='user']) from $current) )
where $place.country[0].toLowerCase() = 'gb'

**Comment by nagarajasr** [comment]
need more info on your schema and your actual requirement to help you. also in your query $place is not defined?

**Comment by martingg88** [comment]
I just updated the query. can you take a look. I just wana include all fields from property, creator and place into one row for each property record. any idea how to make "include" to cater for * that will automatically include all fields of each class instead of i manually specify field i want to include.

**Comment by nagarajasr** [comment]
does this work for you?

```sql

select expand(all) from (select @rid, unionall(@rid, $creator[0],$place[0]) as all from property 
	let $creator=in('own')[@class='user'], $place=out('locate')[@class='place'] ) unwind all

```

**Comment by martingg88** [comment]
Sorry. your query doesn't for me. thanks for your effort. 

what I expect the return result should be as follows: 

1. @rid @class     name   creator                                               place
     #3:1  property  shop   "user object include all user's fields"  "place object include all user's fields"

**Comment by martingg88** [comment]
that is weird lolx as if it only return @rid instead all the fields i expected to return. 

include("@rid", "first_name","last_name")

**Comment by red-0ne** [comment]
@martingg88, is it related to #3630 ?

**Comment by martingg88** [comment]
yes. hope they can solve this issue soon.

**Comment by lvca** [comment]
include/exclude already take wildcards

**Comment by cegprakash** [comment]
I tried
```select out('has_property').include(*) from User where id  = '6143545896216109'```

It doesn't include any field from the target vertex
Voting to reopen
