### ISSUE TITLE
OrientGraph java7 try-with-resources

### ISSUE THREAD

**Issue by zella** [orientechnologies/orientdb#4833]
For java7+ users would be nice to have try-with-resources statement:

```
try (OrientGraph graph  = factory.getTx()){
        ...
}
```

instead

```
OrientGraph graph = factory.getTx();
try {
 ...
} finally {
   graph.shutdown();
}
```

**Comment by rmuller** [comment]
+1

**Comment by tglman** [comment]
Hi all,

We implement the tinkerpop api 2.x that not implement AutoCloseable, the new version of tinkerpop 3.x it include AutoCloseable, so from 3.0 we are going to support it.

Regards
