### ISSUE TITLE
SQL Parsing failed when field name conflicts with some keyword

### ISSUE THREAD

**Issue by popduke** [orientechnologies/orientdb#4838]
After migrating to 2.1, the following insert command failed, it used to work in 2.0

```
INSERT INTO Department SET name = "ABC", desc = "This is ABC"
```

with following error in log:

```
Error on parsing command at position #0: Encountered " <DESC> "desc "" at line 1, column 43.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    "`" ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
```

looks like the field name 'desc' (for description) is miss-interpreted as the keyword DESC.
I have a tons of classes with the 'desc' field, and I'm using orientjs as client to issue commands. 
How can I quickly migrate our db to 2.1 without too many db/code changes? Any suggestion?

UPDATE:
I find turnoff 'strictSql' could make it behave as previous version, however I do think it should be a valid command even with strictSql turning on.

**Comment by luigidellaquila** [comment]
Hi @popduke 

you found the easy solution alone, disabling strictSql you are allowed to use reserved words as identifiers (class and property names).
The other solution is to quote field names using backtick, eg.

```sql
INSERT INTO Department SET name = "ABC", `desc` = "This is ABC"
```

**Comment by luigidellaquila** [comment]
leaving this open just to verify if it can be automated in OrientJS query builder

**Comment by aurelijusb** [comment]
Backtics does not work when using `AS`.
For example:
```
SELECT @rid AS to, traversedVertex(-2).@rid AS `from`
FROM(
  TRAVERSE out('Refer')
  FROM #19:340
  WHILE $depth < 10
)
```
Error:
```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Found 'AS' without alias 
```
But works  when renamed:
```
SELECT @rid AS to, traversedVertex(-2).@rid AS edgeFrom
FROM(
  TRAVERSE out('Refer')
  FROM #19:340
  WHILE $depth < 10
) 
```

**Comment by renatoathaydes** [comment]
It seems to also fail when the name of the field contains a `-`... if that's intentional, it would be better to completely disallow field names containing `-` (eg. `start-time`) instead of throwing a runtime error when a query is made on that field.

My query looks like this:

```
SELECT * FROM Person ORDER BY `a3-end-time` DESC
```

And the error:

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " "-" "- "" at line 1, column 34.|Was expecting one of:|    "`" ...|    "`" ...| 
```

**Comment by luigidellaquila** [comment]
Hi guys,

both problems seem to be related to the lower parsing level (part of the old executor), I think they can both be fixed

Thanks

Luigi

**Comment by lvca** [comment]
Fixed in 3.0

**Comment by lightjiao** [comment]
Hi @lvca ,
I need to create index on a field named `desc`. so, I create property first
`CREATE PROPERTY v_test.desc IF NOT EXISTS String`
and I get this error
`
{
    "errors": [
        {
            "code": 400,
            "reason": 400,
            "content": "Error parsing query:u000aCREATE PROPERTY v_instance_IMAGE.desc IF NOT EXISTS Stringu000a                                    ^u000aEncountered \"<DESC>\"desc \"\" at line 1, column 34.u000aWas expecting one of:u000a    <TO> ...u000a    <VALUE> ...u000a    <VALUES> ...u000a    <SET> ...u000a    <ADD> ...u000a    <PUT> ...u000a    <MERGE> ...u000a    <CONTENT> ...u000a    <REMOVE> ...u000a    <ORDER> ...u000a    <GROUP> ...u000a    <OFFSET> ...u000a    <RECORD> ...u000a    <CACHE> ...u000a    <LUCENE> ...u000a    <NEAR> ...u000a    <WITHIN> ...u000a    <MINDEPTH> ...u000a    <CLASS> ...u000a    <SUPERCLASS> ...u000a    <CLASSES> ...u000a    <SUPERCLASSES> ...u000a    <EXCEPTION> ...u000a    <PROFILE> ...u000a    <STORAGE> ...u000a    <ON> ...u000a    <OFF> ...u000a    <TRUNCATE> ...u000a    <FIND> ...u000a    <REFERENCES> ...u000a    <EXTENDS> ...u000a    <CLUSTERS> ...u000a    <ABSTRACT> ...u000a    <ALTER> ...u000a    <NAME> ...u000a    <SHORTNAME> ...u000a    <OVERSIZE> ...u000a    <STRICTMODE> ...u000a    <ADDCLUSTER> ...u000a    <REMOVECLUSTER> ...u000a    <CUSTOM> ...u000a    <CLUSTERSELECTION> ...u000a    <DESCRIPTION> ...u000a    <ENCRYPTION> ...u000a    <DROP> ...u000a    <PROPERTY> ...u000a    <FORCE> ...u000a    <METADATA> ...u000a    <INDEX> ...u000a    <COLLATE> ...u000a    <ENGINE> ...u000a    <REBUILD> ...u000a    <ID> ...u000a    <DATABASE> ...u000a    <OPTIMIZE> ...u000a    <LINK> ...u000a    <TYPE> ...u000a    <INVERSE> ...u000a    <EXPLAIN> ...u000a    <GRANT> ...u000a    <REVOKE> ...u000a    <READ> ...u000a    <EXECUTE> ...u000a    <ALL> ...u000a    <NONE> ...u000a    <FUNCTION> ...u000a    <PARAMETERS> ...u000a    <IDEMPOTENT> ...u000a    <LANGUAGE> ...u000a    <BEGIN> ...u000a    <COMMIT> ...u000a    <ROLLBACK> ...u000a    <IF> ...u000a    <ISOLATION> ...u000a    <SLEEP> ...u000a    <CONSOLE> ...u000a    <BLOB> ...u000a    <SHARED> ...u000a    <DEFAULT_> ...u000a    <SEQUENCE> ...u000a    <START> ...u000a    <OPTIONAL> ...u000a    <COUNT> ...u000a    <HA> ...u000a    <STATUS> ...u000a    <SERVER> ...u000a    <SYNC> ...u000a    <EXISTS> ...u000a    <RID> ...u000a    <RIDS> ...u000a    <MOVE> ...u000a    <IN> ...u000a    <KEY> ...u000a    <IDENTIFIER> ...u000a    <QUOTED_IDENTIFIER> ...u000a    u000du000au0009DB name=\"cmdb_org_1505924783\""
        }
    ]
}
`

Orientdb version : 2.2.24
OS : Centos 6.8
java version: 1.8

How can I create property named `desc` and create index on it.
Is there any other word has this problem?

**Comment by lightjiao** [comment]
```CREATE PROPERTY v_instance_IMAGE.`desc` IF NOT EXISTS String```
Could solve my problem.
BUT I hope this would write on the document[http://orientdb.com/docs/2.2.x/SQL-Create-Property.html](url)

**Comment by JLHwung** [comment]
@lightjiao Please check the [3.x documentation](http://orientdb.com/docs/3.0.x/sql/SQL-Syntax.html#identifiers) for quoted identifiers usage.

**Comment by lightjiao** [comment]
@JLHwung 👍
