### ISSUE TITLE
MERGE doesn't merge nested property.

### ISSUE THREAD

**Issue by gongdo** [orientechnologies/orientdb#4839]
I expected the MERGE operation works for nested property, but it didn't.

```
CREATE VERTEX something CONTENT { 'value': { 'a':1, 'b': { 'sub':'name' }, 'c':'ccc' } }
UPDATE #10:0 MERGE {'value': { 'b': { 'sub':'merged'} } }
SELECT value FROM #10:0

// the result will be
{ 'b': { 'sub':'merged'} }

// expected result is
{ 'a':1, 'b': { 'sub':'merged' }, 'c':'ccc' }
```

SET operation works however, I needed to make looong list for SET.

```
UPDATE #10:0 SET value.b.sub='merged', ...and all other properties...
```

Any chances to support nested MERGE operation?

**Comment by nagarajasr** [comment]
which version of OrientDB?

**Comment by gongdo** [comment]
Oops, I forgot to mention it. I'm using v2.1

**Comment by jeremyxia** [comment]
I have the same issue with Merge. Right now I use Set but it takes a lots of efforts and not efficient at all. Hopefully it could be solved asap.

**Comment by jeremyxia** [comment]
is there any update for MERGE operation? Thanks.

**Comment by hazzasym** [comment]
Hi, all
Is this the same issue with #5120 ? I got this problem in my development too and to fix this problem my work around is use "set" command for the embedded field that was not so much efficient.
How about progress for this issue and this will be resolve or done in next 2.2 release?
Thank you for great feature.
