### ISSUE TITLE
Issue with OUser.name index

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4843]
Guys,

There is the following problem:

Under unknown conditions, 2 users with the same name were created. It should be not possible because of UNIQUE index on OUser. But after attempt to delete extra user, it's not possible to login into DB: for every user/password there is message that there is no such user with specified username and password.

Can provide DB before extra user deletion and after.

**Comment by lvca** [comment]
Which release?

**Comment by PhantomYdn** [comment]
That happened in 2.1 rc5. Almost sure that it can happen on 2.1

**Comment by laa** [comment]
Hi sure, give me this db if possible

**Comment by laa** [comment]
Any updates on this issue ?

**Comment by laa** [comment]
Issue is closed because of no-reply, feel free to reopen issue if issue happen again and you will have information requested in this issue.
