### ISSUE TITLE
Studio web console auto hides error message too quickly when executing SQL statements

### ISSUE THREAD

**Issue by jillray7** [orientechnologies/orientdb#4854]
The Studio web console autohides error messages too quickly when executing SQL statements. It makes it difficult to read. Please allow users to choose whether they want autohide on or off. Perhaps set autohide to 0 if it's not wanted. If autohide is on, allow users to configure when it autohides. Ex. after 10 seconds.

**Comment by maggiolo00** [comment]
Hi @jillray7 

if you go over with mouse pointer the error message will stop hiding.
