### ISSUE TITLE
Feature request: Static properties for an Element

### ISSUE THREAD

**Issue by basdek** [orientechnologies/orientdb#4856]
Greetings.

I have quite some cases where I'd like to give an Element (in most cases that is a Vertex) a static property. I solve this by making a tight coupling between code & data (i.e. defining some data in the code with a reference to the name of the OrientDB class), which is not so flexible and suboptimal for various reasons.

The abbility to store Key Value pairs on a OrientVertexType / OrientEdgeType would be really valuable.

**Comment by luigidellaquila** [comment]
Hi Bas,

you can use CUSTOM attributes on classes, they are more or less like static
properties in Java,

see http://orientdb.com/docs/last/SQL-Alter-Class.html
see also OClass.getCustom(String) and OClass.setCustom(String, String)

Luigi


2015-08-25 13:12 GMT+02:00 Bas de Kwant <notifications@github.com>:

**Comment by basdek** [comment]
Wow, I had overlooked this. Thanks a lot!
