### ISSUE TITLE
OPartitionedDatabasePoolFactory returns a closed pool

### ISSUE THREAD

**Issue by raeesn** [orientechnologies/orientdb#4858]
Sample code : 

               OPartitionedDatabasePoolFactory poolFactory = new OPartitionedDatabasePoolFactory();
		OPartitionedDatabasePool pool = poolFactory.get("plocal:testdb", "administrator", "administrator");
		ODatabaseDocumentTx db = pool.acquire();
		db.close();
		pool.close();

After closing the pool, in the later stage of application; getting the pool from the same factory and trying to acquire a new connection reports "Pool is closed"

       java.lang.IllegalStateException: Pool is closed
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.checkForClose(OPartitionedDatabasePool.java:373)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:238)

The OPartitionedDatabasePoolFactory retains the pool instance and returns the same, which was closed, as PoolIdentity is same.

**Comment by lvca** [comment]
You should close the pool factory at the end of your application.

**Comment by laa** [comment]
Guys can not agree issue is still relevant.

**Comment by laa** [comment]
It is not needed usually to close pool at all, but if users closes it, we should do not use it any more.

**Comment by laa** [comment]
Fixed
