### ISSUE TITLE
Java driver : 2.1.0 hangs on startup

### ISSUE THREAD

**Issue by rjackson64840** [orientechnologies/orientdb#4861]
I migrated from 2.0.9 to see if parameters were allowed in the date() function but can't get the app to startup because OrientDB is hanging on the following line:

        OServerAdmin serverAdmin = new OServerAdmin(dbUrl).connect(username, password);

Debugging into it I see that it's hanging in the static initializer in OStorageAbstract, line 53:

      if (parentThreadGroup.equals(Orient.instance().getThreadGroup())) {

Sometimes if I debug into it I can get past the constructor (some kind of timing issue/race condition?), but then it locks up in serverAdmin.connect()

I'm on Windows 10, too, if that matters.

**Comment by lvca** [comment]
The hung JVM is the OrientDB server or your with the app?

**Comment by rjackson64840** [comment]
Hi Luca,

It's within my app while trying to connect to the server.

Russ



On Tue, 25 Aug 2015 20:43:20 -0500, Luca Garulli  
<notifications@github.com> wrote:

> The hung JVM is the OrientDB server or your with the app?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/orientechnologies/orientdb/issues/4861#issuecomment-134787295


-- 
Using Opera's revolutionary email client: http://www.opera.com/mail/

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by rjackson64840** [comment]
I went back to 2.0.9 and it's working again.

was hoping I could put something like this in my query:

... WHERE endDate <= date(:endDate, 'yyyy-MM-dd')

notice the :endDate parameter in the query



On Tue, 25 Aug 2015 22:26:16 -0500, Russ Jackson <rjackson@jscomm.net>  
wrote:

> Hi Luca,
>
> It's within my app while trying to connect to the server.
>
> Russ
>
>
>
> On Tue, 25 Aug 2015 20:43:20 -0500, Luca Garulli  
> <notifications@github.com> wrote:
>
>> The hung JVM is the OrientDB server or your with the app?
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/orientechnologies/orientdb/issues/4861#issuecomment-134787295
>
>


-- 
Using Opera's revolutionary email client: http://www.opera.com/mail/

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by rjackson64840** [comment]
Hi Luca,

I just stepped thru the 2.0.0 OServerAdmin construction process and wow,  
2.1.0 is quite a bit different.  What problems were trying to be solved by  
all the changes there?

Russ

On Tue, 25 Aug 2015 22:29:44 -0500, Russ Jackson <rjackson@jscomm.net>  
wrote:

> I went back to 2.0.9 and it's working again.
>
> was hoping I could put something like this in my query:
>
> ... WHERE endDate <= date(:endDate, 'yyyy-MM-dd')
>
> notice the :endDate parameter in the query
>
>
>
> On Tue, 25 Aug 2015 22:26:16 -0500, Russ Jackson <rjackson@jscomm.net>  
> wrote:
>
>> Hi Luca,
>>
>> It's within my app while trying to connect to the server.
>>
>> Russ
>>
>>
>>
>> On Tue, 25 Aug 2015 20:43:20 -0500, Luca Garulli  
>> <notifications@github.com> wrote:
>>
>>> The hung JVM is the OrientDB server or your with the app?
>>>
>>> ---
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/orientechnologies/orientdb/issues/4861#issuecomment-134787295
>>
>>
>
>


-- 
Using Opera's revolutionary email client: http://www.opera.com/mail/

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by laa** [comment]
Hi,
Could you do following:

1. Reproduce the situation when application hangs.
2. Please do not debug, but create thread dump.
3. Send thread dump to the support email and we will fix given issue.

**Comment by laa** [comment]
@rjackson64840 about your question why we need those changes, during OrientDB shutdown we interrupt all threads in OrientDB group (that is legacy code) as result background NIO operations may be interrupted too and as result it may lead to data corruption so we need to be sure that we do not run  storage data handling threads in OrientDB group.

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Comment by rjackson64840** [comment]
I recently tried with 2.1.5 and this is still happening.  Therefore I had to go back to 2.0.9.

Anyone there running on Windows 10?

Apologize, but I am not familiar with collecting thread dumps.  Please provide instructions if that's what you need.

**Comment by smolinari** [comment]
Hey @rjackson64840. What kind of application are you using ODB to back up? And what language are you programming in?

Scott

**Comment by rjackson64840** [comment]
It's a Java web application.  I connect to the DB via a servlet context listener.  

In the below:
  - dbUrl resolves to "remote/localhost"
  - type.name() = "document"
  - mode.name() = "plocal"

```java
private static void init(String uri, String dbName,
                  String username, String password,
                  OrientDBType type, OrientDBMode mode) throws IOException {
    String dbUrl = String.format("%s/%s", uri, dbName);

    // try to connect
    OServerAdmin serverAdmin = new OServerAdmin(dbUrl);
    serverAdmin = serverAdmin.connect(username, password);

    // create the db if it doesn't exist
    if (!serverAdmin.existsDatabase()) {
        serverAdmin = new OServerAdmin(uri).connect(username, password);
        serverAdmin.createDatabase(dbName, type.name(), mode.name()).close();
    }

    // set the connection factory
    OrientDBConnectionFactory factory = new OrientDBConnectionFactory(dbUrl, username, password);
    Orient.instance().registerThreadDatabaseFactory(factory);

    initSchema();
} // initialize()
```
Here is my connection factory class:
```java
public class OrientDBConnectionFactory implements ODatabaseThreadLocalFactory {

    private static final Logger LOG = LoggerFactory.getLogger(OrientDBConnectionFactory.class);

    private OPartitionedDatabasePool _pool;

    public OrientDBConnectionFactory(String dbUrl, String username, String password) {
        _pool = new OPartitionedDatabasePool(dbUrl, username, password);
        LOG.info("DB connection pool created for '%s'", dbUrl);
    } // constructor

    public ODatabaseDocumentInternal getThreadDatabase() {
        return _pool.acquire();
    } // getThreadDatabase()

} // class OrientDBConnectionFactory
```

**Comment by smolinari** [comment]
Ok. A web application. Not sure if you would be interested, but I have created a vagrant box for dev work for Graph databases. 

https://github.com/spider/spider-box 

It is more aimed at building for PHP apps, but it also has a Java environment. It would be cool to know, if it is possible (or what is missing) to develop in Java too. 

Also, what version of Java are you using? 

Scott
