### ISSUE TITLE
Can't create composite index on vertex using edge-derived properties

### ISSUE THREAD

**Issue by plt6356** [orientechnologies/orientdb#4862]
From an empty graph, I set up classes with this SQL:
```sql
CREATE CLASS color EXTENDS V
CREATE CLASS sofa EXTENDS V
CREATE CLASS colorof EXTENDS E
CREATE PROPERTY colorof.out LINK color
CREATE PROPERTY colorof.in LINK sofa UNIQUE
CREATE PROPERTY color.name STRING
CREATE PROPERTY sofa.name STRING
```

I then try to create a composite index, using properties linked to with edges with the "in_" prefix, as described in https://groups.google.com/forum/#!msg/orient-database/uaUvruu-GN8/zYdZ0DPhtD8J:

CREATE INDEX findbycolor ON sofa (in_colorof.name, name) UNIQUE

However, I get the error message:

OIndexException Index with name : 'findbycolor' cannot be created on class : 'sofa' because field: 'in_colorof.name' is absent in class definition.  com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex (OClassImpl.java:1706)

Am I writing the SQL command wrong, or is this a bug? Thanks

**Comment by lvca** [comment]
If you create an index against `in_colorof.name`, you should declare that property. However the dot (.) syntax is not accepted on linked fields at index creation. Whats's your goal?

**Comment by rationalism** [comment]
My goal is to do fast lookups on vertex of type sofa given both color name and sofa name. Eg. if there are 10,000 vertices of type color, and 100,000 vertices of type sofa for each vertex of type color (10,000 * 100,000 = 1,000,000,000 total vertices of type sofa), then doing a linear scan over either sofa name or color name would be quite slow. (The schema assumption is that, for any given vertex of type sofa, the pair (in_colorof.name, name) is unique, but both in_colorof.name and name by themselves are non-unique and might be shared by tens or hundreds of thousands of

**Comment by rationalism** [comment]
Sorry, that last comment should have ended with "thousands of vertices." Thanks

**Comment by plt6356** [comment]
(Comments above are from me - sorry, my phone was logged in with my old account)

**Comment by lvca** [comment]
Ok, so if you use Lightweight edges, you could index out/in collections:

```sql
