### ISSUE TITLE
Searching with 'OR' using Lucene

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#4871]
Hi there,

I think there's an issue searching multiple lucene indices at the same time with using an `OR` operator

Here's a test schema and some data:

```sql
create class Test extends V

create property Test.attr1 string
create index Test.attr1 on Test (attr1) fulltext engine lucene

create property Test.attr2 string
create index Test.attr2 on Test (attr2) fulltext engine lucene

insert into Test set attr1='foo', attr2='bar'

rebuild index Test.attr1
rebuild index Test.attr2
```

The following queries **do not work**:

```sql
select from Test where [attr1, attr2] lucene '(attr1:foo* OR attr2:foo*)'
select from Test where attr1 lucene 'foo*' OR attr2 lucene 'foo*'
```

There's a workaround suggested by @eugene-kamenev in one of the [Gitter](https://gitter.im/orientechnologies/orientdb) posts:

```sql
select from Test where @rid in (select from Test) or @rid in (select from Test)
```

but it seems to be slow (I tried it on 100+k records)

**Comment by maggiolo00** [comment]
@andreyvk have 

you can use one index.

```
create index Test.attr1 on Test (attr1,attr2) fulltext engine lucene
```
and then

```
select from Test where [attr1, attr2] lucene '(attr1:foo* OR attr2:foo*)'
```

**Comment by andreyvk** [comment]
@maggiolo00 Thanks for the tip! I will

However, does it still count as a problem or not? It looks like an issue to me or is it intended by design now for Orient 2.0+ ?

**Comment by maggiolo00** [comment]
@andreyvk 

if you have to indexes this will not work

```select from Test where [attr1, attr2] lucene '(attr1:foo* OR attr2:foo*)'```

but this should work

```select from Test where attr1 lucene 'foo*' OR attr2 lucene 'foo*'```

**Comment by lvca** [comment]
@maggiolo00 Is this working now?

**Comment by maggiolo00** [comment]
@lvca 
it is resolved with the new implementation of MemoryIndex.
As long as we remove the check in parsing, will work even without index.
But the implementation is in develop.
Should we backport it to 2.1.x?

**Comment by lvca** [comment]
How much work is to backport this entire feature? Is it applicable as hotfix?

**Comment by maggiolo00** [comment]
It would take a couple of hours, maybe less.
Il 21/set/2015 01:55, "Luca Garulli" <notifications@github.com> ha scritto:

**Comment by maggiolo00** [comment]
Back ported to 2.1.x
