### ISSUE TITLE
Automatically wrap all operations in tx if db flag is set to true.

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#4874]
According to users reports sometimes they experience complete indexes rebuild on server crash because of presence of non-tx operations it would be logical (and simple) to add db setting which will wrap all DB operations in single transaction and will prevent given behaviour.

**Comment by lvca** [comment]
:+1

**Comment by laa** [comment]
Optional for 3.0 will put back if we have time

**Comment by laa** [comment]
Implemented using micro txs
