### ISSUE TITLE
djikstra - java at 500+ CPU, no results

### ISSUE THREAD

**Issue by gg4u** [orientechnologies/orientdb#4875]
Hi, testing dijstra.
So far 4M nodes, about 30M links.
Graph is undirected weighted, and for each node A>B, I am also creating B>A (I will try to handle duplicates afterwards).

Model:
MyClass for Vertexes, property myclass.name 
MyLinks for Edges, property mylinks.proximity (weight, DESC ordered by importance).

ShortestPath() works, but dijkstra halts.
No result, CPU skyrocketing, server hanged.

Is it maybe an issue of indexes or am I missing something?
Also, how do I specify the custom 'weight' property? and sub-class of edges?

I am trying:
```Select dijkstra ((select from myclass where id = 10), (select from myclass where id = 100), 'proximity') from MyClass #Here myClass is of Vertexes, not Edges```

**Comment by lvca** [comment]
@gg4u We improved the shortestPath in 2.1, but dijstra() remained in the old version so I believe it's much slower. @luigidellaquila Could you take this task?

**Comment by luigidellaquila** [comment]
Hi @gg4u 

could you please try current develop branch (next 2.2.1)? We just replaced the old Dijkstra implementation with a new one, so the problem should be fixed

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, closing, please reopen if you see any other problems

Thanks

Luigi
