### ISSUE TITLE
LUCENE documentation is wrong Latitude = y; Longitude = x

### ISSUE THREAD

**Issue by MVdev1** [orientechnologies/orientdb#4881]
**Latitude = y (+- 90);  Longitude = x (+-180)**   See http://gis.stackexchange.com/questions/11626/does-y-mean-latitude-and-x-mean-longitude-in-every-gis-software

*I don't mean to be picky here but write this bug because it appears to me that there might be fundamental bugs due to the misunderstanding which appears in the documentation, error messages, etc.*

To me the SQL syntax is incorrect as well (see below).

Example of where x and y are transposed, making it confusing...

From https://github.com/orientechnologies/orientdb-lucene/wiki/Spatial-Index

   select from Class where [&lt;lat-field>,&lt;long-field>] NEAR [&lt;x>,&lt;y>]
   select *, $distance from Class where [<&lt;at-field>,&lt;long-field>,$spatial] NEAR [&lt;x>,&lt;y>,{"maxDistance": distance}]

**(shouldn't it be y,x?)**

Later on in the same document it says:

    select  from Class where [<lat field>,<long field>] WITHIN [ [ <lng1>, <lat1> ] , [ <lng2>, <lat2> ] ... ]

**Super confusing because here it says lat,long on one side and long, lat on the other side**

The error messages from the console seem to say the right thing although they don't always appear -- y range is +- 180 and x range is +- 90

Proposed resolution:

#1.  fix the documentation
#2.  change the code so that it's lat, long on both sides of the above query

**Comment by maggiolo00** [comment]
Hi @MVdev1 

yes it is not well documented and they are transposed.
it is a fix we have in roadmap.
http://orientdb.com/docs/2.1/Roadmap.html#release-22
It is more than a fix, we are rewriting that part to be more compliant with the standard WKT,GeoJson, Spatial Functions
as the current support is very limited and not well documented.

**Comment by maggiolo00** [comment]
The docs has been fixed
with correct order
https://github.com/orientechnologies/orientdb-docs/blob/master/Spatial-Index.md
