### ISSUE TITLE
new requirement:  add custom lucene analyzer by adding jar files to a directory

### ISSUE THREAD

**Issue by ninesunqian** [orientechnologies/orientdb#4882]

**Comment by martingg88** [comment]
any idea how to solve the following issue. 

try to index with following analyzer but class not found . 

{"analyzer":"org.apache.lucene.analysis.cn.smart.SmartChineseAnalyzer"}

try to install the plugin for org.apache.lucene.analysis.cn.smart.SmartChineseAnalyzer but have following error 

15-11-16 16:50:21:047 SEVER Plugin definition file ('plugin.json') is not found for dynamic plugin 'lucene-analy
rs-smartcn-4.7.0.jar' [OServerPluginManager]Error on installing dynamic plugin 'lucene-analyzers-smartcn-4.7.0.j
'

**Comment by maggiolo00** [comment]
hi @robfrank 

should be implemented this in 2.2.x right?

**Comment by robfrank** [comment]
lucene analyzee are fully configurable in 2.2.0: http://orientdb.com/docs/last/Full-Text-Index.html#analyzer
