### ISSUE TITLE
massive insert - Cannot find a command executor 

### ISSUE THREAD

**Issue by seeden** [orientechnologies/orientdb#4884]
Hi 
I am trying to tell orientdb about massive insert 

I can see this error:
```ssh
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.declare intent massiveinsert
```
I have tried:
DECLARE INTENT massiveinsert;
DECLARE INTENT "massiveinsert";
DECLARE INTENT massiveInsert;

I found that it is supported from your console.
My new question is. Is it possible somehow to call it with OrientJS(SQL) or from OrientDB studio?
Is it fixed to the current connection?

**Comment by lvca** [comment]
DECLARE INTENT is not a SQL command, but rather a Java API or a console command.

**Comment by truongsinh** [comment]
Really? That's it?
> DECLARE INTENT is not a SQL command, but rather a Java API or a console command.

and no document update?

And there is no answer to the question
>Is it possible somehow to call it with OrientJS(SQL) or from OrientDB studio?
Is it fixed to the current connection?
