### ISSUE TITLE
Problem using an edge with name 'match'

### ISSUE THREAD

**Issue by fabriziofortino** [orientechnologies/orientdb#4889]
I have some vertexes connected through edges with name 'match'. I don't have any problem to create them but when I try to execute the following:

```sql
select from match
```

I get the following exception

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <FROM> "from "" at line 1, column 8.
Was expecting one of:
    <NULL> ...
    "true" ...
    "false" ...
    "{" ...
    <NULL> ...
    "{" ...
    "true" ...
    "false" ...
    
Tested with the latest 2.2.0-SNAPSHOT.

**Comment by luigidellaquila** [comment]
Hi @fabriziofortino 

in 2.2 we are introducing a new query type, that is MATCH, so it has become a reserved word. 
You can quote it with backticks:

```sql
select from `match`
```

**Comment by fabriziofortino** [comment]
Thanks @luigidellaquila 

using back-ticks the query works but when I execute:

```sql
delete edge `match`
```

I get 
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Class '`MATCH`' was not found [ONetworkProtocolHttpDb]

**Comment by fabriziofortino** [comment]
As a workaround I tried to use the FROM / TO notation:

```sql
delete edge from #22:0 to #22:885
```

but it does not seem to work:

Delete record(s) '0' in 0.003000 sec(s).
