### ISSUE TITLE
INCREMENT throws sql.filter.OSQLFilterItemField cannot be cast to java.lang.Number

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#4892]
Using `INCREMENT` with the following expressions as values triggers `java.lang.ClassCastException: com.orientechnologies.orient.core.sql.filter.OSQLFilterItemField cannot be
cast to java.lang.Number`

```sql
LET counter = SELECT count(*) FROM MetadataValue;
UPDATE MetadataKey INCREMENT weight = FIRST($counter).count;
```

Same thing when using `IF`:
```sql
UPDATE MetadataKey INCREMENT weight = IF( eval('weight == 2147483647'), 0, 1 )
```

**Note** that replacing `INCREMENT` by `SET` makes the query succeed.

**Comment by lvca** [comment]
Reproduced.
