### ISSUE TITLE
failed to create class property in 2.1.0 with :OCommandSQLParsingException

### ISSUE THREAD

**Issue by hazzasym** [orientechnologies/orientdb#4893]
Hi, 

I Used Orientdb 2.0.7-2.0.10 in development with some class property contain ' - ' in property name like
"create property upload.content-type string"
and successfully created with no problem.

But, after I moved to Orientdb 2.1.0 when I try to create same property as before Orientdb throw this error

Error on parsing command at position #0: Encountered "" at line
 1, column 36.
Was expecting one of:

I try another solution with remove ' - ' from command to
"create property upload.contenttype string"
This time I success on create property.

So, In 2.1.0 can we create property with '-' ? or in version 2.1.0 '-' is a reserved word or illegal word?
Could someone clarify or explain the solution to me please.
Thank for helping.

**Comment by hazzasym** [comment]
May be this issue relate to #4768

**Comment by lvca** [comment]
http://orientdb.com/docs/last/Release-2.1.0.html#strict-sql-parser
