### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by deacix** [orientechnologies/orientdb#4894]
Hello Guys,

i have an issue:

I get this Error:

"java.net.SocketTimeoutException: Read timed out"

From Post request to:

/uploadSingleFile/dbname

in the OrientDB Studio..

Version is 2.1.0.

Can any help me?

**Comment by lvca** [comment]
Could you please provide more information?

**Comment by deacix** [comment]
Hi!
In the OrientDB Studio i try to upload a image file for a binary field. Over the OrientDB i got a 500 Response from the Database with this Error:

"java.net.SocketTimeoutException: Read timed out"

DB Version is: Version is 2.1.0

It is not possible to upload binary files over the OrientDB Studio and over the REST API.

If you like you can call me over the Skype. Username is: deacix

Thank you!

**Comment by rdelangh** [comment]
@maggiolo00 
hi Enrico, any news about this case ? I seem to encounter the same while using the REST API of ODB, sending a simple (but rather long duration) UPDATE statement. I get a timeout back in the client program.
Is there anything configurable on the server side, regarding the REST API timeouts ?

**Comment by maggiolo00** [comment]
@rdelangh 

this was due file uploading that is not supported in Rest API.

How can i reproduce your issue?

**Comment by rdelangh** [comment]
@maggiolo00 
hi Enrico, I seem to have found that it is possible to set the client-side timeout for the REST calls, did some tests with that, and could set the timeout to substantially longer as before. Got no more errors from timeouts anymore.
Thanks for your feedback, this issue can be closed.

brgds
Rob

**Comment by lvca** [comment]
Thanks, closing then.
