### ISSUE TITLE
SQL functions with parametrized links don't use indexes over HTTP (ClassCastException)

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4896]
Having a DB with classes foo (cluster 12) and bar (cluster 13), where foo contains a link to bar, you could have a query to get all foo documents which contain a link to a given bar document:

select from foo where bar = #13:1
Suppose there is an index (NOTUNIQUE_HASH_INDEX) on foo.bar to improve performance of this query. When you run the query above, the index is used as expected.

Then you create a function (getFoo) to run this query, parameterizing the value of bar:

select from foo where bar = :bar
When you run this query via the HTTP protocol (or directly in Studio) a ClassCastException is thrown and the index is not used:

{db=test} Error on using index foo.bar in query 'SELECT FROM foo WHERE bar = :bar'. Probably you need to rebuild indexes. Now executing query using cluster scan
java.lang.ClassCastException: java.lang.String cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable
This does not happen (i.e. no exception and the index is used) when calling the function via the binary interface:

select getFoo(#13:2)

Refer to issue https://github.com/orientechnologies/orientdb/issues/4895

**Comment by lvca** [comment]
This seems the same as or #4895?

**Comment by stuartking** [comment]
Correct, this is the same as #4895 which was closed however is still reproducible.
