### ISSUE TITLE
Cannot inspect results in Server side javascript function

### ISSUE THREAD

**Issue by optimuspaul** [orientechnologies/orientdb#4897]
I have the following example:

```
`var gdb = orient.getGraph();
try {
  var results = gdb.command("sql", 'select uid from eos_object where out(eos_fingerprint)[fingerprint] = "aaabbb"');
  print(JSON.stringify(results));
  return results[0];
} catch(e) {
  return {"status": "ERROR", "error": e.toString()};
}
```

The result I get is:
```
[
    {
        "@type": "d",
        "@rid": "#-2:0",
        "@version": 0,
        "uid": "270881a9-dc02-47d2-8539-5e58406dd120"
    }
]
```
What I see in the logs:
```
undefined
```

I would expect to see the same thing in the log as I do in the result.  The point I'm getting to is I'd like to inspect those results to construct additional queries and create edges to other objects based on the results on a query. It seems that the only place the result is actually available is outside of the scope of the function. Server Side Javascipt functions as they are are either completely useless, broken, or so badly documented and esoteric that they are implicitly useless.

**Comment by optimuspaul** [comment]
if I print `results` I get `[Ljava.lang.Object;@65f99957` so apparently it is a java object. Anyway we could get some docs on what the properties of that object are?  I can't seem to do any reflection on it from javascript.

**Comment by optimuspaul** [comment]
Ok, after what seemed like forever I figured something out... the individual results are `com.tinkerpop.blueprints.impls.orient.OrientVertex` still not sure what `results` is, but it acts sort of like an array. I hope this helps others that are in the boat I am in.... I also hope we can get things documented better.

**Comment by lvca** [comment]
Updated docs, thanks.
