### ISSUE TITLE
Traversal in WHERE stops working between connected vertices

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#4901]
Hi,

I am using `OrientDB 2.1.0 GA` I am not sure what to do here and how to debug this! 

I have an edge between two existing vertices and a query similar to the following (I cannot post original, sorry):

```sql
select
from MyClass
where outE('egde_class').inV()['attr'] = 'some_value'
```

This query used to give me results, but not anymore.  The funny thing is that if I do:

```sql
select expand(outE('egde_class').inV())
from MyClass
```

then it works fine (results are returned). Also the following will work correctly:

```sql
select 
from MyClass
where outE('egde_class').inV().length() > 0
```

To verify the problem I created two test classes, some vertices and edges between them.(see the following [GIST](https://gist.github.com/andreyvk/bf72e76a4286b2d2a69a)). The query for test classes *did* give me results (gist, line 14)! So, logic works.

1. Has anyone else encountered similar problem?
2. How can I debug this?
3. How can I fix this at the moment?

**Comment by andreyvk** [comment]
Moved to 2.1.1GA. Still the same.

**Comment by lvca** [comment]
Tried with 2.1.3-SNAPSHOT and seems to work:

![image](https://cloud.githubusercontent.com/assets/312606/9965777/ebeb8624-5e38-11e5-85b9-bf021c6d91e8.png)

**Comment by andreyvk** [comment]
@lvca it works in general, yes. Like I said, when I created test classes it **did** work, but it would not work in one particular case. I think there might have been some data corruption or smth. I dont know.

This happened to me twice already. The first time I counted it as my own fault, because I did not know OrientDB well enough. This second time, however, I was quite sure that something went wrong with the db. 

Unfortunately, I had to remove my development data and start again. So now everything works well and I cannot help with replicating the problem. It's ok to close the issue, i guess, but if I encounter that problem again I will let you know and we can re-open it. Cheers

**Comment by lvca** [comment]
@andreyvk, please reopen the issue if happens again. Thanks.

**Comment by andreyvk** [comment]
@lvca will do, thanks!

**Comment by lvca** [comment]
Use the IN, not equals, because when when you traverse with out/in/both you ends with having collections, so the IN always works.

**Comment by andreyvk** [comment]
@lvca Been struggling to understand why my approach didn't work all this time! Obviously your tip is what i was looking for. Checked it and it works! Thanks a lot again!
