### ISSUE TITLE
Is there a way to merge an EMBEDDED document property in an UPDATE statement?

### ISSUE THREAD

**Issue by alpeshgaglani** [orientechnologies/orientdb#4904]
I have a class with an embedded property that serves to hold semi-structured JSON data. There are several situations where I need to merge existing data with some new information. For example, I'm storing user information in an documentInfo property with the following JSON: {"@type":"d", title: "Hello World", subTitle: "For noobs", thumbnailUrl:"https://..."}. Our APIs our locked, so that I only get delta changes ( for eg. {title:"Hello World 2"}) that I then need to merge on update.
How can I achieve this? If I use the UPDATE #16:19 MERGE {"documentInfo":{"@type":"d","title":"Hello World 2"}}, the subtitle field gets overwritten!
I am using v2.0.
Thanks.

**Comment by lethalspam** [comment]
UPDATE - CONTENT: replaces the old record, eg.
UPDATE Record CONTENT {"name":"foo"}
after this statement execution, your record will only have one field, called "name"
UPDATE - MERGE: replaces the old record, eg.
UPDATE Record MERGE {"name":"foo"}
this statement will update the "name" attribute, but will leave untouched all the other attributes

**Comment by jeremyxia** [comment]
same issue with post #4839

**Comment by luigidellaquila** [comment]
@alpeshgaglani I'm closing this as duplicate, please refer to #4839 for tracking
