### ISSUE TITLE
INSERT INTO INDEX:dictionary SET rid=(SELECT @rid FROM...

### ISSUE THREAD

**Issue by simper66** [orientechnologies/orientdb#4909]
Hi,

Given a Vertex:

orientdb {db=xLocation}> select from root
0 |#16:0 |Root |0 |0 |ROOT|ROOT|false |false

I can put it in the dictionary this way:

orientdb {db=xLocation}> INSERT INTO INDEX:dictionary SET key='ROOT', rid='#16:0'
Inserted record '{rid:#16:0,key:ROOT}' in 0.003000 sec(s).

But with an inner SELECT it fails:

orientdb {db=xLocation}> INSERT INTO INDEX:dictionary SET key='ROOT', rid=(select @rid from root where name ='ROOT' limit 1)

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.insert INTO INDEX:dictionary SET key='ROOT', rid=(select @rid from root where name ='ROOT' limit 1)

Error: java.lang.ClassCastException: com.orientechnologies.orient.core.sql.OCommandSQL cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable

I suppose this is relative to all kind of indexes, not only for dictionary.

Is there any way of converting the "select @rid" to a valid rid/rids for the insert clause?

I don´t find a way. It would be great. Perhaps an enhancement?

Enviroment:

OrientDB: OrientDB 2.1.0 GA Community Edition
SO: Windows7
JDK: Jdk 1.8.0_45
OrientDB Configuration: No special configuration. The one out of the box.
Mode: Standalone. server.bat

**Comment by lvca** [comment]
This is not supported, but easy to do that. Working on it...

**Comment by tommasop** [comment]
The same could be done perhaps with @class ?

**Comment by lvca** [comment]
Not relevant anymore, closing it.
