### ISSUE TITLE
query error: error on parsing command at position #0: Encountered "" at line 1

### ISSUE THREAD

**Issue by rwnew2012** [orientechnologies/orientdb#4912]
when I run queries like

select from V where name not like 'orientdb'
it throws me error like 

"Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException": Error on parsing command at position \#:0 Encountered "" at line 1, column 27

**Comment by luigidellaquila** [comment]
Hi @rwnew2012 

`not like` operator is not supported by the query parser, the correct syntax is

```
select from V where not (name like 'orientdb')
```

I hope it helps

Thanks

Luigi
