### ISSUE TITLE
There isn't feedback in orient-server-log.0 while setting MAXDISKCACHE = -Xmx2048m

### ISSUE THREAD

**Issue by AlessandroRota** [orientechnologies/orientdb#4915]
Hi,

setting ``MAXDISKCACHE = "- Dstorage.diskCache.bufferSize = 2048"``  there isn't feedback in orient-server-log.0 while setting ``MAXDISKCACHE = -Xmx2048m`` there is feedback. 
Also setting ``MAXHEAP = -Xmx512m`` and ``MAXDISKCACHE = -Xmx1024m`` heap exceeds 512m.

**Comment by lvca** [comment]
It must be `-D` and not `- D`

**Comment by lvca** [comment]
It must be `-D` and not `- D`
