### ISSUE TITLE
Indexes are not used with parametized user defined sql functions

### ISSUE THREAD

**Issue by mattaylor** [orientechnologies/orientdb#4916]
Create a sql function 'func' with a 'name' parameter and body eg

`select from user where name = :name`

try explain this in the browser 
`explain select from func('testUser')`
and compare this to 
`explain select from user where name = 'testUser'`

big difference

**Comment by lvca** [comment]
Internally the call to the select in the function should call index. Try doing this:

```js
function func( name ){
  return orient.getGraph().command( "explain select from user where name = :name", [ name ] );
}


```

**Comment by stuartking** [comment]
This is captured in more detail in issue #4896

**Comment by lvca** [comment]
No answer after long time, closing.
