### ISSUE TITLE
Alias for "list databases"

### ISSUE THREAD

**Issue by warriorkitty** [orientechnologies/orientdb#4921]
I'm proposing an alias for a command "list databases". There are commands like "classes", "clusters", etc. and there is "list databases". It could also be "databases".

**Comment by lvca** [comment]
What do you mean?

**Comment by StarpTech** [comment]
@lvca a shorthand for `list databases`. `classses` and `clusters` implicit `list`

**Comment by warriorkitty** [comment]
@lvca writing "databases", instead of "list databases".

**Comment by warriorkitty** [comment]
Any update on this?

Actually, I would like to resolve this issue. Any suggestion? Where should I start looking? Concrete filename would be great! :dancers:

**Comment by lvca** [comment]
Not relevant anymore, closing it.
