### ISSUE TITLE
SELECT behaviour

### ISSUE THREAD

**Issue by iw2rmb** [orientechnologies/orientdb#4925]
When i do 'select from #rid' i get edges, but in prev version of odb there were vertexes.
How can I manage this behaviour?

**Comment by warriorkitty** [comment]
Hmm... I think it just depends what #rid is. You can select both vertices and edges with #rid. Go to the OrientDB Studio, select it from there and look what type it is. (You can do it from the console but the Studio is just really good for inspecting.)

**Comment by iw2rmb** [comment]
i mean edges that are linked to #rid (vertex) and i do select from vertex, not edge
in prev version there were rids of vertexes it connected with
now rids of edges that are connect

select both() from #vertex != select from #vertex
but in prev version it was

**Comment by lvca** [comment]
maybe because now lightweight edges are disabled by default? Look at the docs to see how to enable it.
