### ISSUE TITLE
IllegalArgumentException when create edge by json with null property

### ISSUE THREAD

**Issue by gongdo** [orientechnologies/orientdb#4926]
I'm using v2.1.
When I create an edge by JSON content with null property, it raises IllegalArgumentException.

```
create edge E FROM #10:0 TO #11:0 CONTENT {'a':1,'b':null}
```
    java.lang.IllegalArgumentException: Property value can not be null

**Comment by Simon-stc** [comment]
Had the same problem. The setting I found in https://github.com/orientechnologies/orientdb/issues/3365#issuecomment-70525870 fixed it.

    alter database custom standardElementConstraints=false

**Comment by gongdo** [comment]
The option doesn't explain much what it exactly is.
Is there any possible side effect if I set standardElementConstraints=false?

**Comment by Simon-stc** [comment]
Javadoc: [setStandardElementConstraints](http://orientdb.com/javadoc/latest/com/tinkerpop/blueprints/impls/orient/OrientConfigurableGraph.html#setStandardElementConstraints-boolean-)

    Changes the setting to apply the Blueprints standard constraints against elements.

Setting to false allows the use of null values and reserved keys like `id`, therefore switching to an other blueprints implementation could cause errors (see #2722).

**Comment by gongdo** [comment]
Looks better to keep the default setting and change json serializer settings.
Thanks @Simon-stc
