### ISSUE TITLE
performance for query with/without index. 

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4927]
As we know index will make the query faster, but i feel strange about the following issue. 

A. with composite index as follows: 

place.distance NOTUNIQUE  ["lat","lng"] SBTREE

explain select from place order by lat limit 1
- order will using 'lat' index for query

explain select from place order by lat, lng limit 1
- order will not work for composite index. 

B. how to apply alias projection field for order clause to care about performance issue. 

explain select  DISTANCE(lat, lng, 3.1333, 101.3833)  as distance from place order by distance limit 1
- this query will have slow performance because new projection field 'distance' will not be indexed beforehand, but it's created on the fly. 

C. spatial index is really provide poor performace. 

explain select   from place where DISTANCE(lat, lng, 3.1333, 101.3833) < 100000 limit 1
- perfomance better than spatial index query. 

explain select   from place where  [lat,lng,$spatial] NEAR [3.1333, 101.3833,{"maxDistance": 100000 }]  limit 1
-- poor perfomance.

**Comment by maggiolo00** [comment]
@martingg88  can you paste here the explain?

**Comment by martingg88** [comment]
@maggiolo00  i think any order clause that is created/aliased on fly will have huge performance degradation. 

example as here. 

select sum(total)  as total from class order by total. 

can you experience this issue at your end?

**Comment by martingg88** [comment]
hope there is a huge performance improvement for order clause. otherwise we found meaningless for this db.
