### ISSUE TITLE
How do I add an edge with a property field?

### ISSUE THREAD

**Issue by hatibt** [orientechnologies/orientdb#4929]
Hello Guys,

Using the Graph API, I am trying to create an Edge, with a mandatory property between 2 vertices. I can do it without the property, but cannot see how to do it with the property set.

I tried various ways but it still fails. There is no Edge constructor in the graph API, that takes a property or properties, as well as the two vertices and the edge name.

graph.addEdge(null, notificationOrientVertex, userOrientVertex, "notify").setProperty("created", System.currentTimeMillis())

fails with exception saying, notify edge, does not have mandatory property "created" 

I have set graph.setUseLightweightEdges(false), but still no joy.

How can I achieve this please

Regards

hatib

**Comment by lvca** [comment]
This is more a question than an issue. Please post in Community Group where more than 2k users can answer to your question:

https://groups.google.com/forum/#!forum/orient-database

**Comment by hatibt** [comment]
Ok will do,
Thanks
