### ISSUE TITLE
Unique index not working properly? Duplicate record, broken index after update query.

### ISSUE THREAD

**Issue by Simon-stc** [orientechnologies/orientdb#4930]
Since I am very new to Orientdb, I am not sure if this is a bug ot if I am missing something.

I noticed this while using the Orientjs client, so I converted all queries to plain SQL in order to run them in Studio.

Create classes etc. on an empty database:

    CREATE CLASS test_master EXTENDS V;
    CREATE PROPERTY test_master.name STRING;
    ALTER PROPERTY test_master.name MANDATORY true;

    CREATE CLASS test_slave EXTENDS V;
    CREATE PROPERTY test_slave.master_link link test_master;
    ALTER PROPERTY test_slave.master_link MANDATORY true;
    ALTER PROPERTY test_slave.master_link READONLY true;
    ALTER PROPERTY test_slave.master_link NOTNULL true;
    CREATE PROPERTY test_slave.slave_number SHORT;
    ALTER PROPERTY test_slave.slave_number MANDATORY true;

    CREATE INDEX unique_master_slave ON test_slave (master_link, slave_number) UNIQUE;

Create Vertices:

    CREATE VERTEX test_master SET name='Master 1';
    CREATE VERTEX test_slave SET master_link=#12:0, slave_number=1; 
    CREATE VERTEX test_slave SET master_link=#12:0, slave_number=2;
    CREATE VERTEX test_slave SET master_link=#12:0, slave_number=3;

Now when I update one record to a duplicate `slave_number`

    UPDATE #13:1 SET slave_number=1;
it fails with the following error

    com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #13:1: found duplicated key 'OCompositeKey{keys=[#12:0, 1]}' in index 'unique_master_slave' previously assigned to the record #13:0 RID=#13:0 [ONetworkProtocolHttpDb]

The record however was updated to the new value. 

    SELECT FROM [#13:0, #13:1]

    {
        "result": [
            {
                "@type": "d",
                "@rid": "#13:0",
                "@version": 1,
                "@class": "test_slave",
                "master_link": "#12:0",
                "slave_number": 1,
                "@fieldTypes": "master_link=x,slave_number=s"
            },
            {
                "@type": "d",
                "@rid": "#13:1",
                "@version": 2,
                "@class": "test_slave",
                "master_link": "#12:0",
                "slave_number": 1,
                "@fieldTypes": "master_link=x,slave_number=s"
            }
        ],
        "notification": "Query executed  in 0.056 sec. Returned 2 record(s)"
    }

If I try to rebuild the index

    REBUILD INDEX unique_master_slave

it fails

    com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [test_slave]
    --> com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #13:1: found duplicated key 'OCompositeKey{keys=[#12:0, 1]}' in index 'unique_master_slave' previously assigned to the record #13:0 RID=#13:0 [ONetworkProtocolHttpDb]

Should the update query not just fail with an error, without changing the record and breaking the index?

**Comment by lvca** [comment]
What release?

**Comment by Simon-stc** [comment]
Latest `2.1.1` as well as `2.1.0 (GA)`

**Comment by tglman** [comment]
written the relative test case and fixed, in both 2.1 and develop

**Comment by doppelrittberger** [comment]
Hi,

the issue seems not be solved completely. In my environment (OrientDB 2.1.2) only remote protocol works as expected, if I test against plocal or memory the documents still get updated on index exception.
