### ISSUE TITLE
Query using Graph.getVertices with label set to vertex name

### ISSUE THREAD

**Issue by hatibt** [orientechnologies/orientdb#4935]
Hello Guys,

A query using the following getVertices signature returns all vertices linked to the staring vertex if they all contain the same field.

eg given the foll Vertices and Edges

**User (V)**
userId
name
age
                                         

**livesAt(E)**

**Address(V)**
addressId
userId
street

I would expect the following **getVertices** method call, to return ONLY the User vertex, as it explicitly passes the "User" label.

graph.getVertices("User", Array("userId"), Array(userId))

However it returns all Vertex addresses with the same value for userId. It does not filter on the label. ie distinguish between User and Address.

Maybe this is not the way to model a graph DB, ie have a foreign key userId, in the address vertex.  But OrientDb is supposed to be a hybrid database. It would be useful to make use of the label argument as its already there.

Can this be done or am I missing something?

OrientDB version: orientdb-community-2.1.1

Regards

Hatib

**Comment by maggiolo00** [comment]
hi @hatibt  which api are you using?

where the userid is declared?
on V or Both in User/Address

**Comment by hatibt** [comment]
Hi 

I created User with userId as a primary key and Address with userId as a foreign key.  Like u would if u were using a relational database.

So userId is not a field on the V vertex.

Regards

**Comment by SDIPro** [comment]
Issue appears to have been fixed in 2.2.  Please re-open if this issue can be reproduced in 2.2.x.
