### ISSUE TITLE
[Question][Ops Friendly] Is it possible to change the log level of a remote server while the server is running

### ISSUE THREAD

**Issue by machinelearner** [orientechnologies/orientdb#4937]
Changing the log-level dynamically when the server is running without a restart will help debug and diagnose a lot of issues in a prod-esque environment where a restart is going to be costly with the baggage of data-exchange, some queries getting false results, all clients getting cluster shape updates etc. 

Or, am I missing something, is there already a way to do this?

**Comment by lvca** [comment]
Yes, execute a HTTP POST against the console:

    /server/log.console/FINEST

Or file:

    /server/log.file/FINEST
