### ISSUE TITLE
Creating Distributed Database System in AWS

### ISSUE THREAD

**Issue by tellyarz** [orientechnologies/orientdb#4943]
I have two AWS EC2 instance each running OrientDB Enterprise 2.1. I got an explanation on setting up a distributed database system on AWS on this link: http://orientdb.com/docs/2.1/Distributed-Configuration.html. I have managed to download hazelcast-cloud.jar (1.9.4.4) and included it in my lib folder for each of the OrientDB server instances. After executing the dserver.sh script I get the some exceptions shown in this link: http://d1y93r5b3uzcc6.cloudfront.net/exception.png

Below is my hazlecast.xml settings:

```xml
<hazelcast
	xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.0.xsd"
	xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<group>
		<name>orientdb</name>
		<password>orientdb</password>
	</group>
	<network>
		<port auto-increment="true">2434</port>
		<join>
			<multicast enabled="false">
				<multicast-group>235.1.1.1</multicast-group>
				<multicast-port>2434</multicast-port>
			</multicast>
            <aws enabled="true">
		        <access-key>xxxxxxx</access-key>
		        <secret-key>xxxxxxx</secret-key>
		        <region>us-east-1</region>   
		        <!--<security-group-name>hazelcast-sg</security-group-name>  
		        <tag-key>type</tag-key>                                  
		        <tag-value>hz-nodes</tag-value>-->                          
	      	</aws>
		</join>
	</network>
	<executor-service>
		<pool-size>16</pool-size>
	</executor-service>
</hazelcast>
```

Any help please?

**Comment by robfrank** [comment]
Can you try with hazelcast-cloud 3.3.5?

**Comment by tellyarz** [comment]
okay will try that and let you know the result

**Comment by tellyarz** [comment]
Thanks @robfrank corrected the last exception only that I am now getting a connection timeout and I notice one of the database.ocf file is locked by another process

**Comment by tellyarz** [comment]
Thanks @robfrank corrected the last exception only that I am now getting a connection timeout and I notice one of the database.ocf file is locked by another process

**Comment by tellyarz** [comment]
How do I solve the connection timeout issue

**Comment by robfrank** [comment]
Can you open another issue adding more details, please?

**Comment by tellyarz** [comment]
okay

**Comment by muthukumarkubendran** [comment]
@tellyarz  I'm also getting connection timeout issue now while try to setup distributed mode on AWS Ec2 instance. Please let me know how you solved this issue or have you opened a new issue if so share the issue number and I will track it down.
