### ISSUE TITLE
is default-distributed-db-config.json readed by dserver ? (enterprise edition, version 2.1.1)

### ISSUE THREAD

**Issue by BrunoSupiot** [orientechnologies/orientdb#4944]
I'm currently testing orientdb in cluster mode (dserver.sh).
I've tried to modify default-distributed-db-config.json, but it seems that orientdb does not read this file.
whatever the configuration content, it seems to have no effect on the distributed-config.json file deployed on the database.
Even if the json file is not well-formed, there is no error in the logs.
For example, a default-distributed-db-config.json with a unique character '{' seems to be OK for orientdb.

Is  the default-distributed-db-config.json reazly usefull for configuration (for example, for sharding) ?

Best regards

**Comment by mntkris** [comment]
(try to remove distributed-config.json from database directory, default-distributed-db-config.json should be read then)

**Comment by BrunoSupiot** [comment]
Thank you: it works fine!
However, there is a lack of documentation about this 'feature": on must remove the distributed-config.json from databases directory if the default-distributed-db-config.json is modified.

**Comment by lvca** [comment]
Docs updated. Thanks for the advice.
