### ISSUE TITLE
Named Parameter not working in Order By with an embedded map.

### ISSUE THREAD

**Issue by zig158** [orientechnologies/orientdb#4949]
I am having an issue somewhat similar to #4776. I am trying to use a named parameter in my order by to prevent sql injection. The query parser is ignoring my named parameter and is treating it as a literal. I am using version 2.1.1.

Here is an example of what my document looks like.
```
       {  
         "@rid":"19:0",
         "@version":3,
         "@class":"work",
         "created":1441258032,
         "modified":1441258203,
         "state":"#14:0",
         "properties":{  
            "count":"0",
            "testupdate":"1441258203385"
         }
      }
```

I have tried both of the following.
      SELECT * FROM Work ORDER BY properties[:obparms]
and
      SELECT * FROM Work ORDER BY properties :obparms
but this works perfectly
      SELECT * FROM Work ORDER BY properties['count']

My java code looks like this.
```
    try(OObjectDatabaseTx db = DBPool.getConnection()){
            Map<String,Object> parameters = new HashMap<String,Object>();
            parameters.put("obparms","count");
            String sql = "SELECT * FROM Work ORDER BY properties :obparms"
            return db.query(new OSQLSynchQuery<Work>(sql),parameters);
    }
```

**Comment by luigidellaquila** [comment]
Thanks for reporting, I'm checking this

**Comment by luigidellaquila** [comment]
fixed in branch 2.1.x, it will be released in 2.1.3 hotfix.
Porting to develop branch

**Comment by luigidellaquila** [comment]
this was already fixed in develop branch (2.2), added test case.
Please confirm that I can close this

**Comment by zig158** [comment]
It appears to be working correctly in commit 5eaefd7be62f12ce89b5e7640396425284b09790. Thank you for the fix.

**Comment by luigidellaquila** [comment]
Thanks!
Closing
