### ISSUE TITLE
Traverse using field filtering on a value containing a dot character (.) does not work

### ISSUE THREAD

**Issue by plgregoire** [orientechnologies/orientdb#4952]
In this situation : 
- VerticeA (#12:20598) is connected to VerticeB by an edge.
- VerticeB has a label property with a value containing a dot (.) : Label="a.b"

If you execute this query: 
Traverse in[Label="a.b"],out_E From #12:20598
VerticeB will not be in the results

However, if you remove the dot from the label value of VerticeB and execute this query:
Traverse in[Label="ab"],out_E From #12:20598
VerticeB will be returned in the results

Is this a bug?
If not, How can I escape the dot character in the query ?

Thank you

**Comment by plgregoire** [comment]
Hi,

I have tried this on the version 2.0.11 and on the version 2.1.x with the same result.
Could someone try it and tell me if there is a workaround that I can do in my queries or if it is a bug in the SQL engine ?

Thank you.

**Comment by luigidellaquila** [comment]
Hi @plgregoire 

It's quite strange, I'm checking it right now

**Comment by luigidellaquila** [comment]
Hi @plgregoire 
I fixed it in both develop and 2.1.x branches, you can build it from sources or wait for next snapshot/hotfix release

Thanks

**Comment by plgregoire** [comment]
Awesome !
I'll try it asap.

Thank you
