### ISSUE TITLE
dependency on sun.misc prevents orientdb-tools deployment in eclipse

### ISSUE THREAD

**Issue by b4mse** [orientechnologies/orientdb#4958]
sun.misc package is a required import in orientdb-tools. This makes deployment in eclipse environment fail. 
By making the import on sun.misc optional, the orientdb-tools may be used in eclipse without dependency problems. This change was already made on core/pom.xml but is missing in tools/pom.xml

I've created a pull-request with the necessarily change on branch 2.1.x  #4956. 

Thank you,
Adrian

**Comment by lvca** [comment]
Thanks, merged
