### ISSUE TITLE
hotaligmment question

### ISSUE THREAD

**Issue by BrunoSupiot** [orientechnologies/orientdb#4962]
In distributed mode, when hotalignment is set to true and a a node must be (re)started, it seems that the entire database is transfered to the node. Is my supposition true ? In this case, with a big database (for example: > 10 Teraytes), how long will take the transfer when a node is restarted ?

**Comment by lvca** [comment]
We're introducing incremental backups with OrientDB v2.2, so a restart of a node will be much faster.
