### ISSUE TITLE
Probable invalid name in property added from Studio; can not connect to database

### ISSUE THREAD

**Issue by AndreaPravato** [orientechnologies/orientdb#4964]
### Can not connect to database anymore
Hello, after creation of a database using studio (http://localhost:2480/studio/), I can not connect to the database anymore. I used Orientdb 2.1.1 community. 
I would like to fix the issue and be able to export and use again the database we have created. How could we proceed? 
When I try to connect, the situation is the following: 
- ----
### shell
"orientdb> **connect remote:localhost/NameOfDatabase root mypassword**

Connecting to database [remote:localhost/NameOfDatabase] with user 'root'...
Error: com.orientechnologies.common.exception.OException: Error on creation of shared resource

Error: com.orientechnologies.orient.core.exception.OSchemaException: Cannot add base class 'FF_DocumentVersion', because of parameter conflict: creationDate (type=DATETIME) vs creationDate (type=DATETIME)"

**Comment by AndreaPravato** [comment]
My boss at work downloaded the community version from Github, commented the control and recompiled; now we can connect to the database and export the database.

**Comment by AndreaPravato** [comment]
Probably a command line parameter could be introduced, to skip that kind of checks and retrieve the database in case a similar thing happens

**Comment by StarpTech** [comment]
@AndreaPravato I have the same issue. it is possible to publish your solution?

**Comment by tglman** [comment]
fixed long time ago, is a duplicate, closing
