### ISSUE TITLE
Slow Inserts when using OClass Parameter in createProperty method [v2.1.0] plocal

### ISSUE THREAD

**Issue by BryanWisdom** [orientechnologies/orientdb#4965]
Version: 2.1.0 (plocal connection for ODatabaseDocumentTx)

When creating a link on an OClass schema object, you can specify the "OClass" that the link will point at. Specifying this dramatically increases the insertion time (tested with LINKSET). When the "OClass" is not specified, insertion times go down a lot.

E.g.

``` Java
OClass logItem = schema.createClass("log_item");
logItem.createProperty("timestamp", OType.DATETIME);
logItem.createProperty("message", OType.STRING);

OClass log = schema.createClass("log");
log.createProperty("name", OType.STRING);
```

and the method that makes the difference

``` Java
log.createProperty("log_items", OType.LINKSET, logItem);
```

VS

``` Java
log.createProperty("log_items", OType.LINKSET);
```

Inserting some items...

``` Java
// log = Get the log...
ODocument logItem = new ODocument("log_item");
logItem.field("timestamp", new Date());
logItem.field("message", "Hello World");
logItem.save();


Set<OIdentifiable> logItems = log.field("log_items");
logItems.add(logItem.getIdentity());
log.save();
```

Inserting 1 "log" with 1000 "log items" On my machine:
WITH OClass param        => 38.8 seconds
WITHOUT OClass param => 1.5 seconds

**Comment by tglman** [comment]
Hi all,

this performance issue is already solved by this change: https://github.com/orientechnologies/orientdb/commit/11a78a425b314d4f8eb390965177a6453ab728a3#diff-217b3c77792b81e2cc6c9f16496940ebL448

closing.
