### ISSUE TITLE
Add Multiple IDs in a Transaction to a LinkSet

### ISSUE THREAD

**Issue by DonKanallie** [orientechnologies/orientdb#4968]
I'm trying to add IDs from a inserted column to another inserted column in a Transaction. I tried like this:

begin 
let doorOne = INSERT INTO doors SET color = green
let doorTwo = INSERT INTO doors SET color = blue
let car = INSERT INTO Cars SET doors = [$doorOne , $doorTwo]
commit retry 100
return $car
I get:

Unhandled rejection OrientDB.RequestError: The field 'Cars.doors' has been declared as LINKSET but the value is not a record or a record-id

I also tried to update it afterwards in the Transaction, but this won't work either (i think because the car is not created yet, so nothing to update) and i dont want to do it in two different calls, if there is a way to do it in one Transaction.

**Comment by lvca** [comment]
Use return:

    let doorOne = INSERT INTO doors SET color = green RETURN @rid

**Comment by DonKanallie** [comment]
Still Getting the Error: Unhandled rejection OrientDB.RequestError: The field 'Cars.doors' has been declared as LINKSET but the value is not a record or a record-id

**Comment by parimal-padture** [comment]
:+1:
