### ISSUE TITLE
OrientDB Query(NOT LIKE)

### ISSUE THREAD

**Issue by skonka** [orientechnologies/orientdb#4969]
which is the equivalent  query for "NOT LIKE" in orientDB
- for example: select from object where objId NOT LIKE '%AMP%'

retreive the records where objId doesnot contain string AMP

**Comment by neilsaviodsouza** [comment]
any workarounds for this?

**Comment by luigidellaquila** [comment]
Hi @neilsaviodsouza 

the workaround is 

```
select from object where NOT (objId LIKE '%AMP%')
```

Thanks

Luigi

**Comment by neilsaviodsouza** [comment]
Great, thanks.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
