### ISSUE TITLE
getVertices(String iKey, Object iValue) not working for Vertex types(OrientDB 2.1.2)

### ISSUE THREAD

**Issue by Asimovtech** [orientechnologies/orientdb#4973]
I'm creating a function to find records matching property and value of a vertex class, the following works

    public <T extends VertexEntity> T findVertexEntity(Class<T> klass, String property, Object value) throws EntityCreationException, EntityNotFoundException {
        Iterable<Vertex> vertices=tsg.getGraph().getVertices(klass.getSimpleName(), new String[]{property}, new Object[]{value});
        ...
But using this instead, causes my testcases to fail because vertices of different type that have same property, value get matched

    Iterable<Vertex> vertices=tsg.getGraph().getVertices(klass.getSimpleName()+"."+property, value);

**Comment by maggiolo00** [comment]
Fixed in 2.1.x and develop

**Comment by Asimovtech** [comment]
Thanks a lot for the quick response. Really appreciate it.
