### ISSUE TITLE
studio query editor improvement 

### ISSUE THREAD

**Issue by AndreaPravato** [orientechnologies/orientdb#4974]
In the query editor, where queries can be written and executed, text could be temporarily stored and then retrieved so that switching back and forth among the graph and the query editor section, or simply accidentally pressing back, won't result in inserted queries deletion

**Comment by TwinTailsX** [comment]
+1, recent query history seems to disappear when switching tabs too. (Any queries that were properly saved are still there though)

**Comment by lvca** [comment]
Not relevant anymore, closing it.
