### ISSUE TITLE
index on embeddedlist (array of objects)

### ISSUE THREAD

**Issue by seeden** [orientechnologies/orientdb#4976]
I am trying to create an index for field in the item of the embeddedlist.
Is it possible to do that somehow? 
I have just 100 000 records and when I use query like

```sql
select * from User where providers CONTAINS nameUID='facebook_12345' 
```

it took almost 10 seconds (because db must to scan each record). 
Is there any other option if the OrientDb do not support indexes on embedded list items?

field providers is array of objects

**Comment by seeden** [comment]
Is any ETA for this?

**Comment by publicocean0** [comment]
me too i m interested in this feature. Possibilities to index the properties

**Comment by publicocean0** [comment]
another general problem related to index is a seekeable file on orientdb . how can i see a block at offset Y in a big file with thousands of chunks?

**Comment by publicocean0** [comment]
there is also a logic  inconsistency in lucene definition. 
if in orientdb a class can be schemaless , for what reason i must configure the properties in lucene index? In the most cases , i can foresee what are the properties .

**Comment by maggiolo00** [comment]
@publicocean0 which inconsistency ?

Yes in Orientdb a class can be schemaless 
but in order to create an index the property has to be defined.

**Comment by publicocean0** [comment]
how can define a property if a class is schemaless for definition?

**Comment by smolinari** [comment]
@publicocean0 - currently ODB doesn't allow indexing on properties created without schema definitions. [See this discussion.](https://github.com/orientechnologies/orientdb/issues/6415#issuecomment-233283007)

[I've created a suggestion for this feature.](https://github.com/orientechnologies/orientdb/issues/6445)  

Scott

**Comment by seeden** [comment]
I am not more interested

**Comment by a-unite** [comment]
indexes for embedded lists\sets\maps is a long time waited feature
@maggiolo00 may you please reopen that is there are no other tickets related to the issue?

**Comment by maggiolo00** [comment]
@a-unite 
there was this older issue here. I think we can use that 

https://github.com/orientechnologies/orientdb/issues/5201

**Comment by a-unite** [comment]
Great, thanks!

**Comment by publicocean0** [comment]
I m still interested if you implement this feature for embedded object  above all using lucene
