### ISSUE TITLE
order vertex by edge doesn't work

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4977]
any idea why following can't get sorted?

select expand(inV()) from list
order by in.ctime desc

**Comment by luigidellaquila** [comment]
Hi @martingg88 

I'm not sure I get the point. In the subject you say that you want to sort by edge, but the query is sorting based on a vertex attribute (ctime, accessed via in. that points to the vertex)

**Comment by martingg88** [comment]
yes..it should be sort vertex attribute by through of query selection from edge target.

**Comment by luigidellaquila** [comment]
this happens because expand() operator changes the result set before the sorting operation, so sorting is made on expanded vertices, not on edges.
Try to change the query removing the "in.", it will work fine

```sql
select expand(inV()) from list
order by ctime desc
```

**Comment by martingg88** [comment]
thanks.

**Comment by martingg88** [comment]
do u have any idea where @act is show empty result where channel is the link type

select *, $act from following 
      let $act = (select * from activity where channel = $current.in)
      order by ctime desc

**Comment by luigidellaquila** [comment]
Hi @martingg88 

Just guessing, maybe you need a $parent somewhere:

```sql
select *, $act from following 
let $act = (select * from activity where channel = $parent.$current.in)
order by ctime desc
```

but please share some additional details about your domain, I have a feeling that this query can be written in a better way

**Comment by martingg88** [comment]
thanks. it's working now. I couldn't share with you that domain as it's still under developing at localhost. I wonder how you can optimize this query.

**Comment by luigidellaquila** [comment]
Hi @martingg88 

If you had edges, the query would just be this (supposing 'following' is an edge):

```sql
select *, inV() from following order by ctime desc
```

But I don't know if it's the case

Anyway, I'm closing this as an issue, we could continue our conversation about optimization on the mailing list, I'm sure it will be useful for the community
