### ISSUE TITLE
[Bug] Parsing class names wrapped in backquotes not work correctly (OrientDB 2.1.1)

### ISSUE THREAD

**Issue by ivmakk** [orientechnologies/orientdb#4980]
Example:
```CREATE CLASS Contains EXTENDS V```
Class created successfully.

```SELECT FROM `Contains` ``` or ```SELECT FROM Contains```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <FROM> "FROM "" at line 1, column 8.

Screening by backquote (`) worked good before v. 2.1.1, and also in this version was added fix for this issue: https://github.com/orientechnologies/orientdb/issues/4768, maybe the fix broke class screening?

**Comment by luigidellaquila** [comment]
Hi @ivmakk 

it seems to be already fixed, the backtick quoted version 
```
SELECT FROM `Contains`
```
works fine in 2.1.x branch, could you please confirm?

Thanks

**Comment by ivmakk** [comment]
Excuse me @luigidellaquila, my mistake, `SELECT` really works fine.
But ```CREATE EDGE `Contains` ``` not work.

How to recreate (in v2.1.1 & v2.1.2):

```
CREATE CLASS Contains EXTENDS E
Class created successfully. Total classes in database now: 12

CREATE VERTEX V
Created vertex 'V#9:0 v1' in 0.009000 sec(s).

CREATE VERTEX V
Created vertex 'V#9:1 v1' in 0.004000 sec(s).

CREATE EDGE `Contains` FROM #9:0 TO #9:1
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing 
command at position #0: Class '`CONTAINS`' was not found
```
After last step (```CREATE EDGE `Contains` ```) in v2.0.0 edge created successfully with message ```Created edge '[Contains#11:0{out:#9:0,in:#9:1} v1]' in 0.034000 sec(s).```

But in both last vesions (I checked it in v2.1.1 & v2.1.2): ```Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Class '`CONTAINS`' was not found```

Maybe edge can be created in some other way for avoiding incorrect parsing keywords?

**Comment by luigidellaquila** [comment]
Ah, ok, thanks for the details.
I can fix it quickly. 
If you need a quick work-around, you can try to disable strictSql (from Studio, DB tab, Configuration, bottom of the page), it should work as before (without backtick)


Thanks

**Comment by luigidellaquila** [comment]
fixed in branch 2.1.x, cherry-picking to develop

**Comment by luigidellaquila** [comment]
also fixed in develop branch.
Please confirm that it also solves your use case, so that I can close

**Comment by ivmakk** [comment]
> Please confirm that it also solves your use case, so that I can close

Ok, thank you, I think the fix will solve this bug

**Comment by luigidellaquila** [comment]
Perfect, thanks.

Closing
