### ISSUE TITLE
Create fulltext index in studio doesn`t show the Engine

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4983]
After creating an index via studio the field `Engine` is empty.
When I create an index via query

```
CREATE INDEX <name> [ON <class-name> (prop-names)] <type> [<key-type>]
```
the fulltext index is created correctly.

Orientdb: 2.0.10 -> 2.0.14

**Comment by maggiolo00** [comment]
hi @StarpTech 
is this happen only for fulltext?

If you refresh the page do you see it?

**Comment by StarpTech** [comment]
yes, only for fulltext and also the index is not correctly applied. I think it`s a simple problem of the query builder in the studio.

**Comment by maggiolo00** [comment]
Fixed
https://github.com/orientechnologies/orientdb-studio/commit/f4248b372cd421e0d51f8dbf96679655f1a55161
