### ISSUE TITLE
Provide a Reactive Streams API for 

### ISSUE THREAD

**Issue by sdeleuze** [orientechnologies/orientdb#4986]
Based on https://github.com/orientechnologies/orientdb/issues/1227 and https://github.com/KadekM/orientdb-scala-stream, it would be nice to provide a Reactive Streams API in OrientDB.

If you need more background about Reactive Streams and about what back pressure is, you should have a look to these very interesting slides: http://fr.slideshare.net/StphaneMaldini/intro-to-reactive-programming-52821416

FYI, MongoDB already provides a [RS based driver](http://mongodb.github.io/mongo-java-driver-reactivestreams/), and CouchBase a RxJava based one (and since RxJava 2 will be natively built with Reactive Streams ...).

**Comment by luigidellaquila** [comment]
Hi @sdeleuze 

Thanks a lot for the references, this fits very well with our LiveQuery implementation.
Not sure if we'll be able to put it in the roadmap for 2.2 (that is already very stuffed), but for sure it will be implemented

Thanks

Luigi

**Comment by davidduus** [comment]
+1

**Comment by joelhandwell** [comment]
Hello @luigidellaquila, was there progress?

**Comment by sdeleuze** [comment]
You can have a look to this [Understanding Reactive types](https://spring.io/blog/2016/04/19/understanding-reactive-types) I wrote to have more detail about how Reactive types differs from `CompletableFuture`, `Stream`, etc.

**Comment by luigidellaquila** [comment]
@joelhandwell I'm afraid it won't be in the first 2.2 GA, probably it will be implemented lately.

@sdeleuze thanks a lot for the reference!

Luigi

**Comment by lvca** [comment]
Implemented in v2.2 as Live Queries.
