### ISSUE TITLE
How to reduce memory footprint

### ISSUE THREAD

**Issue by seeden** [orientechnologies/orientdb#4987]
I would like to know how to setup max used memory for OrientDb (2.0.13).
I am using default configuration (-Xmx512)

I have one big collection with almost 1 000 000 records. 
When I try to create an new index. OrientDb will use 1.3GB Ram and it stay on this value after this operation.

Is there any option to  set memory limit for OrientDb with bigger accuracy.
Thank you

**Comment by lvca** [comment]
This is more a year than an issue. Please post in Community Group where more than 2k users can answer to your question:

https://groups.google.com/forum/#!forum/orient-database

Thanks.
