### ISSUE TITLE
compressionLevel option ignored when exporting database

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#4989]
OrientDB 2.1.2

Choosing different values for compressionLevel resulted in the same output file myDB.export.gz which I believe is compressed at level 9. Used the following command to export

```
sh /usr/orientdb/bin/console.sh "connect remote:localhost/myDB dbUser dbPassword;export database /home/z/db.exported/myDB.export -compressionLevel=0;" 1> /dev/null
```

**Comment by maggiolo00** [comment]
Hi @Ziink by default is compressed at level 1.

http://orientdb.com/docs/2.1/Console-Command-Export.html#syntax

**Comment by Ziink** [comment]
I was just guessing at the compression level. The main thing is that you can't get an uncompressed file if you specify compressionLevel=0

**Comment by maggiolo00** [comment]
However is ignored i just tested.
I m working on the fix.
Il 22/set/2015 19:53, "Ziink" <notifications@github.com> ha scritto:

**Comment by maggiolo00** [comment]
@Ziink 

so with -compressionLevel=0 you would like to have the plain file ?

The Daflater also supports compression level = 0 that means you will get a
.gz file without compression
http://docs.oracle.com/javase/6/docs/api/java/util/zip/Deflater.html#setLevel(int)

**Comment by Ziink** [comment]
To me plain file makes the most sense for zero compression. I'm using rsync to synchronize the exported file to another server.
