### ISSUE TITLE
Performance Improvement for graph queries

### ISSUE THREAD

**Issue by sajid2045** [orientechnologies/orientdb#4990]
We have a relationship like 
Topic[#26:664] <===subscribe====User====user-device==>Device

Now, the following query:
             select in('subscribe').deviceId,in('subscribe').out('user-device').deviceId from [#26:664]

returns 15,000 records. And takes about 4000 ms. Since the relationships are pre-calculated, I was hoping it to run faster. Is there anything that we can do to make it faster (adding index?) ??

Also, we are expecting this count to reach 50K + , what would be the best policy for fetch most efficiently?

**Comment by Bonizzi** [comment]
Hi @sajid2045 

We took the issue in charge and we are working on it. We will provide a feedback soon.

**Comment by Bonizzi** [comment]
Hi @sajid2045,

Yes, you have to add the index in the deviceId field.

**Comment by lvca** [comment]
You could also do this, but I don't think it make huge diference:

    select $sub.deviceId,$sub.out('user-device').deviceId 
    let $sub = in('subscribe')
    from #26:664

Could you please execute the "explain" of your query and report here the output?

**Comment by sajid2045** [comment]
Hi, 
I tried to run this, not sure if I am doing it right. See screenshot:
https://dl.dropboxusercontent.com/u/5968302/error.PNG

**Comment by sajid2045** [comment]
Hi, 
I tried to run this, not sure if I am doing it right. See screenshot:
https://dl.dropboxusercontent.com/u/5968302/error.PNG

**Comment by luigidellaquila** [comment]
Hi @sajid2045 
you have an error in your SQL, try to put LET statement after FROM, eg.

```sql
select ...
from #26:664
let $sub = ...
```

Luigi

**Comment by sajid2045** [comment]
Hi @luigidellaquila ,

You are right. However, I did copy the sql from the response above. Please find the analyze below:

https://dl.dropboxusercontent.com/u/5968302/analyze.PNG

**Comment by sajid2045** [comment]
Any update on this?

**Comment by luigidellaquila** [comment]
Hi @sajid2045 
it seems the analyzer is not giving us much info in this case, could you please try this? It will probably result in a better execution time

```sql
select deviceId, out('user-device').deviceId 
from (select  expand(in('subscribe')) from #26:664)
```

Please also post the result of the explain:

```sql
explain select deviceId, out('user-device').deviceId 
from (select  expand(in('subscribe')) from #26:664)
```

**Comment by luigidellaquila** [comment]
Hi @sajid2045 

Any news? Did you have a chance to try these queries? 

Thanks

Luigi

**Comment by sajid2045** [comment]
Hi Luigi,

Sorry for the delay. I got busy with other projects. 

However, as per our last conversation, I gave you the database dump so you could run the queries and suggest improvements ??

-Sajid.

**Comment by luigidellaquila** [comment]
Hi @sajid2045 

the best variant of your query I found is following:

```
select subscriptionId, out('user-device').deviceId from (
	select expand(in('subscribe')) as sub from #26:664
) limit -1
```

by the way, the result set is a little different: in this case you also maintain the relationship between subscription and device per single row.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @sajid2045 

did you have a chance to try this version of the query on a full dataset?

Thanks

Luigi

**Comment by sajid2045** [comment]
Hi Luigi,

Sorry I got busy with some other project and left orientdb running on
single mode node. I am planning to setup a full regression again for 2.2.5
very soon.

-Sajid.

**Comment by luigidellaquila** [comment]
Hi @sajid2045 

no problem, I just wanted to touch base to be sure that everything is proceeding correctly and we did not miss any important info.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @sajid2045 

just touching base to make sure that everything is OK on this issue.
Can I close it?

Thanks

Luigi

**Comment by sajid2045** [comment]
Hi Luigi,

I have been trying to install 2.1.6 and get it running. After that I'll
test it in the new cluster and let it know.

Regards,
Sajid.

**Comment by AlessandroRota** [comment]
Hi @sajid2045 ,
have you tested it ?

**Comment by luigidellaquila** [comment]
Hi @sajid2045 

I saw no comments on this issue for a long time, I suppose everything is ok.

I'm closing it, please reopen in case you need further help

Thanks

Luigi

**Comment by sajid2045** [comment]
Hi Luigi,

Sorry we just finished updating to the latest version on our staging environment and running the tests etc. I will re-open this one very soon as this query is taking upto 20 min now to execute..I am sure there is something very wrong with our config and we need to fix it.

-Sajid.

**Comment by sajid2045** [comment]
Now that we have the latest orientdb running , I am re-opening this issue as we will dig deeper on this

**Comment by sajid2045** [comment]
Here is the output after running it in Explain:

https://dl.dropboxusercontent.com/u/5968302/Explain.PNG

**Comment by sajid2045** [comment]
Here is the output after running it in Explain:

https://dl.dropboxusercontent.com/u/5968302/Explain.PNG

**Comment by sajid2045** [comment]
Note: The query executed exactly at the same time as the original query (40sec) to lookup 230,000 rows

**Comment by AlessandroRota** [comment]
Hi @sajid2045 , could you share your database so we can do some tests ?

**Comment by sajid2045** [comment]
https://dl.dropboxusercontent.com/u/5968302/subscription-service.gz

let me know when done so I can remove it

**Comment by maggiolo00** [comment]
hi @sajid2045 
do you have a backup instead of export?
Thanks
Enrico.

**Comment by AlessandroRota** [comment]
Hi @sajid2045 , what version are you using ?
Thanks.

**Comment by maggiolo00** [comment]
hi @sajid2045 

you can remove the link

**Comment by maggiolo00** [comment]
I've removed the link

**Comment by sajid2045** [comment]
Here is a export from the Console.sh

https://dl.dropboxusercontent.com/u/5968302/subscription-service.export.gz

Give it a few mins to upload first.

**Comment by sajid2045** [comment]
Why is this issue closed!! 
Did you manage to download ? 

https://www.dropbox.com/s/6yq3vbjec5by92t/subscription-service.export.gz?dl=0

**Comment by maggiolo00** [comment]
hi @sajid2045 

i've sent you an email about this issue. I've reopened it as a private issue.
Thanks
Enrico
