### ISSUE TITLE
OrientDB 2.1.2: intersect() does not work

### ISSUE THREAD

**Issue by doppelrittberger** [orientechnologies/orientdb#4991]
Hi,

I have the following data structure:

Client
    -> users: List<User>
User
    -> emailAddresses: List<EmailAddress>
EmailAddress:
    -> email: String

Now I want to detect, if an email address is already included in a client if I add a new user to the client (e.g. client contains user 1 and user 2, user 1 contains email "test@test.de", user 2 contains "test2@test.de", if I want to add user 3 containing also email "test@test.de" I want to reject in my code).
So far I realized my query this way (#18:2 is a client, #12:1 is the new user to add, I just expand all existing email addresses from the client and want to get the union to all new users email addresses):

SELECT expand($c) LET $a = (SELECT expand(emailAddresses) FROM (SELECT expand(users) FROM #18:2)), $b = (SELECT expand(emailAddresses) FROM #12:1), $c = intersect($a, $b)

The intersect() doesn´t work (at least in OrientDB 2.1.2) -> throws:

java.lang.ClassCastException: com.orientechnologies.orient.core.sql.query.OResultSet cannot be cast to com.orientechnologies.common.util.OSupportsContains

(Referring to https://groups.google.com/forum/embed/?place=forum/orient-database&theme=default&fragments=true&showsearch=true&showtabs=true&hideforumtitle=true&hidesubject=true&parenturl=http%3A%2F%2Forientdb.com%2Factive-user-community%2F#!topic/orient-database/1F9onWJLzu8)

**Comment by lvca** [comment]
This has been already fixed in 2.1.3.

**Comment by Rucchao** [comment]
Hi, Lucas,@lvca I also have an issue here, I can get an intersection between two lists, but it seems that I can not operate or access the result.

> Select $c
> Let $a=(SELECT PNO FROM (select ol.Product_no AS PNO,SUM(ol.Pcs) AS SUM from (select orderlines as ol from Orders unwind ol) GROUP BY ol.Product_no Order by SUM DESC) limit 25),
> 
> $b=(Select PNO FROM(Select Product_no as PNO, in().size() AS Group from Products where in().size()>0 order by Group DESC) limit 25), 
> 
> $c=intersect($a.PNO,$b.PNO) unwind $c

The result of $c have five items, but I can not get the size or each item by the index ($c.size()  or $c[0] or Pno in $c)

> $c
> 7a700633-9f2a-4a72-9707-4b58e14e8e4d
> 1b6413f1-49c7-4707-88e6-1979790637f1
> c1a47e21-de67-453a-8310-dbccd2d3a46d
> 3824bbd6-b650-43a6-8ba2-144504f6a606
> 695f928b-8103-4bcf-99ba-b0078c0a8828
>
