### ISSUE TITLE
OScheduler throw NPE when creating new OSchedule object.

### ISSUE THREAD

**Issue by lukaszkaleta** [orientechnologies/orientdb#4992]
Method which throws error is getFunctionSafe() .. document is null.

Probably super(doc) should be called in OScheduler constructor.

**Comment by lvca** [comment]
The OrientDB Scheduler framework has been deprecated because the lack of usage and features, it's already on our roadmap to improve it: https://github.com/orientechnologies/orientdb/issues/6125.
