### ISSUE TITLE
Order of operations doesn't work as expected

### ISSUE THREAD

**Issue by pawlrus** [orientechnologies/orientdb#4994]
I am running a query that's basically: `select from V where (foo is null or foo <> true) and #9:1 not in in("bar")`.
I expect to get back something, but instead I get nothing. In my testing, I did find that both `select from V where (foo is null or foo <> true) and (#9:1 not in in("bar"))` and `select from V where #9:1 not in in("bar") and (foo is null or foo <> true)` return the results I expected.

Eval might be similarly bugged: `eval('foo - bar + baz')` where `foo`, `bar`, and `baz` are all defined in the query returns foo - bar - baz instead of foo + baz - bar.

**Comment by luigidellaquila** [comment]
Hi @pawlrus 

I remember an old version of OrientDB had such kind of problems, could you please confirm that you are using latest stable?

**Comment by pawlrus** [comment]
It looks like I was experiencing these bugs on 2.0.12. I have another environment on 2.1.1 and the queries work as expected there. Whoops, sorry.
