### ISSUE TITLE
Best indexing strategy that includes a datetime field?

### ISSUE THREAD

**Issue by lethalspam** [orientechnologies/orientdb#4995]
I am trying to determine which indexing approach should I use considering I have a date field along with some other structured fields that I'd like to do full text search on. For my string fields, it would seem that a FULLTEXT_HASH_INDEX would be the most ideal index. I would normally do this as a composite index but I read that doing HASH_INDEX's would preclude me from doing date ranges searches. If that is true, would I, should I or could I do a composite index of the non-date fields and then do another index on the datetime field? A date range search would likely be one of our most popular searches. 

e.g. 

CREATE INDEX recordIndex ON Record (recordType, recordName, recordVersion) FULLTEXT_HASH_INDEX and also

CREATE INDEX Record.recordDare NOTUNIQUE

or should I just do 

CREATE INDEX recordIndex ON Record (recordDate, recordType, recordName, recordVersion) NOTUNIQUE

Table Definition: 

CREATE CLASS Record EXTENDS V

CREATE PROPERTY Record.recordType string

CREATE PROPERTY Record.recordName string

CREATE PROPERTY Record.recordVersion string

CREATE PROPERTY Record.recordDesc string

CREATE PROPERTY Record.recordDate datetime

CREATE PROPERTY Record.recordData EMBEDDED

**Comment by luigidellaquila** [comment]
Hi @lethalspam 

sorry for late reply, the best strategy in this case is defining a fulltext index with Lucene engine, that is in general the best index engine currently supported for strings, plus a regular NOTUNIQUE index for date fields

Thanks

Luigi

**Comment by lethalspam** [comment]
Thank you Luigi.  I will create the following. 

CREATE INDEX recordIndex ON Record (recordType, recordName, recordVersion) FULLTEXT ENGINE LUCENE
CREATE INDEX Record.recordDate NOTUNIQUE

  ~ Darrell
