### ISSUE TITLE
on delete edge getting incompatible type error and wrong record to be removed

### ISSUE THREAD

**Issue by yujinlim** [orientechnologies/orientdb#4997]
Hi,

I was trying to remove `#26:241` but somehow I'm getting incompatible type error and it was complaining about other edge that below to the same vertex.

```
delete edge #26:241

Error: com.orientechnologies.orient.core.exception.OValidationException: The field 'Profile.in_Follow' has been declared as LINKLIST but an incompatible type is used. Value: [Follow#26:283{out:#11:2,in:#13:1774,created_on:Tue Sep 22 07:28:40 UTC 2015} v2]
```

```
 in_Follow                     | LINKLIST    | null                          | false     | false    | false    |           |           | default  |
```

Notes, 
- the class is declared on strict mode
- it only happen on deletion
- `in_Follow` that have more than one link

**Comment by AndreaSpan** [comment]
Hi, 

I've got the same issue when trying to delete EDGE : 
```
DELETE EDGE FROM #15:0 TO #15:35 

throws : com.orientechnologies.orient.core.exception.OValidationException: The field 'Locations.out_Links' has been declared as LINKLIST but an incompatible type is used. Value: [Links#29:12{level:1,distance:17342.0,in:#15:2,out:#15:0} v6]
 ```

The deletion works only properly if the 'out_Links' Linklist contains more than 1 link after deletion.

**Comment by yujinlim** [comment]
I found that, apparently, if you declare the property `in_*` or `out_*` as `LINKBAG` it works fine. I'm not too sure if this helps.

**Comment by AndreaSpan** [comment]
Thanks for the trick! I took a look at the orientdb doc about LINKBAG type but I can't find it in studio.
Which version of orientdb are you using? 2.2 alpha? 
Actually i'm working on :  
 - Studio version : 2.1
 - OrientDB version : 2.1.2

**Comment by yujinlim** [comment]
@AndreaSpan I'm using the same version but I'm doing everything via console.

**Comment by tglman** [comment]
yes the `in_*` and `out_*` collection have to be typed as LINKBAG.
