### ISSUE TITLE
transaction enhancement

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5000]
In the recent versions now transactions work well, but there is still a problem when you have to put a additional SQL command inside the transaction block. 

psesudo stupid code for class A for showing the problem
db.begin()
a.code('X').
a.save();
OSQLCommand("update  A set y=true where code = ''X")
db.commit()

the modifications inside the transaction is not seen in the command execution.

It would be very important to  complete this work for having the possibility to solve complex BO.

**Comment by lvca** [comment]
If you are using "remote" protocol this is normal and documented. Is this the case?

**Comment by publicocean0** [comment]
yes :) for scalability reason i have a indipendent orientdb server . Mime was a suggestion for a future development.

**Comment by lvca** [comment]
ok, we already have an issue or that.

**Comment by publicocean0** [comment]
ah ok sorry :(  I forgot. :) I close this issue
