### ISSUE TITLE
Data wrongly separated over multiple cluster nodes in distributed environment

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5003]
I noticed in our database that after some restarts, data that was put in a specific cluster for a node, it wasn’t put back in the main cluster. For example (output of list clusters):
 
```
bde_fe_nl_country                            |  2185 |                   |              7 |
bde_fe_nl_country_test1-dev                  |  5049 |                   |            236 |
bde_fe_nl_country_test2-dev                  |  2728 |                   |              0 |
bde_fe_nl_country_test3-dev                  |  3764 |                   |              0 |
```
 
and

``` 
bde_fe_nl_cust                               |  2459 |                   |            121 |
bde_fe_nl_cust_test1-dev                     |  4486 |                   |            497 |
bde_fe_nl_cust_test2-dev                     |  2830 |                   |              0 |
bde_fe_nl_cust_test3-dev                     |  4149 |                   |              0 |
 ```

As we depend on queries like “select from cluster:bde_fe_nl_country”, this is most unwanted behavior for us.
 
Could this be a bug? Just to be clear, we do not create such testX-dev clusters ourselves, that are the names of the nodes.

**Comment by lvca** [comment]
@wouterv Wha do you mean with "it wasn’t put back in the main cluster" ? What represent the 2 numbers per cluster in your message?

**Comment by wouterv** [comment]
@lvca I'll try to be more clear.

What we have is a distributed setup with 3 servers: test1-dev, test2-dev, test3-dev (this is our test env, but we see the same happening on production).

What we did at some point is create a class/cluster "bde_fe_nl_cust" (and bde_fe_nl_country, and a LOT more), in which we start to insert data. We always only insert into "bde_fe_nl_cust".
But somehow, the data got scattered over 2 clusters: bde_fe_nl_cust, bde_fe_nl_cust_test1-dev. I'm just guessing that the fact that some data is in "bde_fe_nl_cust_test1-dev" is due to some logic in distribution, I don't know.
We never put any data in that cluster and it is qutie unwanted, because we rely on the fact that everything should be in cluster "bde_fe_nl_cust", because we sometimes use query with cluster: prefixes, which will now give use the wrong results:

```
orientdb {db=beeyond}> select count(*) from bde_fe_nl_cust 

----+------+-----
#   |@CLASS|count
----+------+-----
0   |null  |618  
----+------+-----

1 item(s) found. Query executed in 0.021 sec(s).
orientdb {db=beeyond}> select count(*) from cluster:bde_fe_nl_cust

----+------+-----
#   |@CLASS|count
----+------+-----
0   |null  |121  
----+------+-----

1 item(s) found. Query executed in 0.002 sec(s).

```

My guess is (speculating here) that this happened because we were tinkering with backups while these inserts happenend. The backing up caused a long freeze with db timeout messages. I would expect that this result would be temporary and it should be automatically corrected when the cluster is ok again, so that all data is moved to bde_fe_nl_cust.

**Comment by wouterv** [comment]
Probably because of this we are getting the following exception:

 com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'BDE_fe_nl_CUST' on server 'test1-dev'. ClusterStrategy=local

**Comment by lvca** [comment]
On creation, OrientDB uses the "master" cluster for a class. So if you have the `classbde_fe_nl_cust` that relies on:
- classbde_fe_nl_cust and
- classbde_fe_nl_cust_test1-dev

If you insert a new record of class "classbde_fe_nl_cust" against node "test1-dev", then the cluster "classbde_fe_nl_cust_test1-dev" is selected. This is to avoid conflict on insertion. So this is absolutely normal. You should rather execute queries against class, no cluster. 

Does it make sense?

**Comment by wouterv** [comment]
Not really, we use clusters for logical separation of data, now this gets in the way of that. 

Also see my last comment. Because of these clusters, we cannot insert data at all.

**Comment by wouterv** [comment]
What you are referring to is the "local" section of http://orientdb.com/docs/2.0/orientdb.wiki/Cluster-Selection.html.

For some of our classes we have our own cluster strategy, which will always put it in a specific cluster. It looks like the above did not happen for these classes. Are we in jeopardy of conflicts using such a strategy?

**Comment by lvca** [comment]
Running distributed the strategy is overwritten to support the "locality". This will be addressed soon with:
- the auto-sharing feature and
- by forwarding the request to the proper node owner of the cluster returned by custom strategy

So for now if you want to shard data with distributed cfg, then the client has to connect to the right server that "owns" the cluster where you want to insert.

**Comment by wouterv** [comment]
I'm not sure it is being overwritten (or overridden if that is what you mean). 

We are using a java client to connect to the remote db. In that client we have configured a custom strategy to insert the data into a specific cluster. I can see on our server that the data is being inserted and that no extra clusters per server where created for these classes. 
So I'm guessing locality isn't being used if you explicitly set a custom strategy?

We aren't sharding data over nodes, the data is available everywhere, which is ok for now.

**Comment by lvca** [comment]
The cluster strategy is overwritten in case of distributed, so if you have the following 3 clusters for the class A:
- A_usa
- A_europe
- A_asia

And you want to insert into A_asia, the client should be connected to A_asia, because its master cluster for A is A_asia.

**Comment by wouterv** [comment]
What we actually do is save objects via the objects API. Ike this:

```
db.save(attachedObject, getClusterForClass(entity));
```
where the method getClusterForClass adds a prefix.
So for example, the attachedObject is of instance EntityDef. The getClusterForClass returns someprefix_EntityDef.

So this is oblivious of the notion of distributed config. 

We also do not configure these kinds clusters in the distributed setup/nodes. 

But due to distributed setups, we also have the clusters
entitydef_test1-dev
entitydef_test2-dev
entitydef_test3-dev

but they are empty. If we create a new entitydef with a specific prefix as in the code above, it goes nicely into the cluster we want (someprefix_entitydef) and not in one of the test-dev clusters.

So it seems to me that the strategy isn't overridden in this case. Did we got lucky? Or is it just designed to work like this?

**Comment by lvca** [comment]
When  new record is created, the local cluster is taken. In your case seems the node that succeed on creating objects in that cluster is accidentally the master for that cluster. Could you please this in last dumped distributed cfg json?
