### ISSUE TITLE
Performing conversion from 1.7 to 2.1 EXPORT or IMPORT is dropping our UUID property...

### ISSUE THREAD

**Issue by jaschenk** [orientechnologies/orientdb#5007]
Performing conversion from 1.7 to 2.1 EXPORT or IMPORT is dropping our UUID property.  If you perform a query the field in each cluster is named '__uuid' and it's value all contain the character value of 'uuid'.  This appears to be a bug and a huge conversion issue, if uuid is not allowed by our schemata definitions.

Please advise,
Thanks,
Jeff

**Comment by luigidellaquila** [comment]
Hi @jaschenk 
I'm not sure I understand the problem, I tried to export your db from 1.7 and import it on 2.1 (from the backup you provided some days ago) and then I executed a simple SELECT on your main superclass. I still can see the correct "uuid" field with original values. 
What I exactly did was an 
```
export database
```

in v 1.7.11, plocal, and an

```
export database
```
on latest 2.1 stapshot, in plocal too.

Am I missing something (or just I did not get the point)? How can I reproduce it?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Sorry, I mean

```
import database
```
on 2.1 snapshot

**Comment by jaschenk** [comment]
Luigi,
The sequence is correct, but on my db, there is no uuid property.  Only a
property named __uuid which contains a value of 'uuid'.  Our data is gone!

Looking at json file all data is intact.

Please advise,
Thanks,
Jeff

**Comment by luigidellaquila** [comment]
Hi Jeff,

We can try in two ways:
1) you can try to build latest 2.1 snapshot from sources (branch 2.1.x, as far as I know this was not a known issue, but maybe it was someway fixed in last days) and launch the import on it. In case it's a problem I can build it locally and provide a binary version
2) if you could share your export I'd try the import locally and see if I can reproduce the problem

Thanks

Luigi

**Comment by jaschenk** [comment]
Luigi,

Attached is the output from the export, plus fixes to any classes named
containing a dot "." were replaced with "_".

The import was against a orientdb-enterprise-2.1.1 version.

Let me pull latest snapshot and build and see what I get on my ends as well.

I also attached a screen shot of what I see in studio.

Thanks,
Jeff

**Comment by jaschenk** [comment]
Luigi,

I have successfully imported our data with the uuid intact using the latest
downloaded zip from github which was the
orientdb-community-2.1.2 version.

Interesting this issue I had encountered was using
the orientdb-enterprise-2.1.1 version I pulled from the orientdb download
site.

All good proceeding.

Many thanks,
Jeff

**Comment by luigidellaquila** [comment]
Hi @jaschenk 

Perfect, thank you very much.
I'm closing this then

Luigi
