### ISSUE TITLE
Not able to generate schema's with reserved keywords, while these classes can be created from the console

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5010]
I am trying to see what happens if we upgrade from 2.0 to 2.1 and in our tests I create the error:

```
Caused by: com.orientechnologies.orient.core.exception.OSchemaException: Error creating schema: 'from' is a reserved keyword, it cannot be used as a property name
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addProperty(OClassImpl.java:2264) ~[orientdb-core-2.1.2.jar:2.1.2]
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createProperty(OClassImpl.java:775) ~[orientdb-core-2.1.2.jar:2.1.2]
	at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.generateSchema(OSchemaProxyObject.java:361) ~[orientdb-object-2.1.2.jar:2.1.2]
	at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.generateSchema(OSchemaProxyObject.java:271) ~[orientdb-object-2.1.2.jar:2.1.2]
```

But doing this from the console just works:

```
orientdb {db=beeyond}> create class foo 

Class created successfully. Total classes in database now: 905

orientdb {db=beeyond}> create property foo.from string

Property created successfully with id=1
orientdb {db=beeyond}> select `from` from foo


0 item(s) found. Query executed in 0.001 sec(s).
```

Looks to me like using reserved keywords should be ok, as we have the backtick notation. As we are using this from Object API, we would have to change all our classes not to use "from" as a class property (with getters and setters) anymore, which seems a bit overly restrictive to me.

**Comment by luigidellaquila** [comment]
Hi @wouterv 

for a quick migration you can just disable strictSql validation (http://orientdb.com/docs/last/Release-2.1.0.html), it will remove all the limitations of the new parsing policies

Thanks

Luigi

**Comment by wouterv** [comment]
@luigidellaquila that doesn't help, as the above error happens in code that doesn't check if strict is on or off in OClassImpl:

```
    private OProperty addProperty(String propertyName, OType type, OType linkedType, OClass linkedClass, boolean iCheckExistentRecords) {
        if(type == null) {
            throw new OSchemaException("Property type not defined.");
        } else if(propertyName != null && propertyName.length() != 0) {
            if(Character.isDigit(propertyName.charAt(0))) {
                throw new OSchemaException("Found invalid name for property \'" + propertyName + "\': it cannot start with numbers");
            } else if(reserved.contains(propertyName.toLowerCase())) {
                throw new OSchemaException("Error creating schema: \'" + propertyName + "\' is a reserved keyword, it cannot be used as a property name");
            }
```
the reserved set is simply filled with all reserved keywords further in OClassImpl:

```
    static {
        reserved.add("traverse");
        reserved.add("insert");
        reserved.add("update");
        reserved.add("delete");
        reserved.add("from");
        reserved.add("where");
        reserved.add("skip");
        reserved.add("limit");
        reserved.add("timeout");
    }
```

**Comment by luigidellaquila** [comment]
@wouterv you are right, it has to be fixed.
I can address it quickly, I'll give you a feedback in short

Thanks

**Comment by wouterv** [comment]
@luigidellaquila any updates? Can it be fixed in 2.1.3?

**Comment by wouterv** [comment]
@luigidellaquila ?

**Comment by luigidellaquila** [comment]
Hi @wouterv 

sorry, it took more than expected and it was not fixed in 2.1.3. I'm working on it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
@wouterv fixed in branch 2.1.x, I don't know why my tests were failing, I guess it was for other reasons. Now everything is green.

Sorry for not having it in 2.1.x, if it's important for you to have it in a stable release please let me know, I'll try to schedule another hotfix asap

Thanks

Luigi

**Comment by lvca** [comment]
I guess this is closed, right?

**Comment by wouterv** [comment]
Havent tested it yet. Will close when done.
Op 5 okt. 2015 6:49 PM schreef "Luca Garulli" <notifications@github.com>:

**Comment by wouterv** [comment]
Works.

**Comment by luigidellaquila** [comment]
Great, thank you very much

Luigi
