### ISSUE TITLE
Missing data from 1.7 EXPORT to 2.1.2 IMPORT dropping UUID property from some classes

### ISSUE THREAD

**Issue by jaschenk** [orientechnologies/orientdb#5013]
Related to original issue of just recent closed issue.  Where our UUID property which is inherited from our Base object of SkywardObject is not being correctly imported.  I have experienced this issue against the latest clone of the orientdb gihub respository.

Please advise,
Thanks,
Jeff

**Comment by luigidellaquila** [comment]
Hi Jeff,

just to understand, which branch did you clone? Was it 'develop', '2.0.x' or 'master'?

Thanks

Luigi

**Comment by jaschenk** [comment]
It was 'master'.  Please advise if I should pull a specific branch.  
Thanks,
Jeff

**Comment by luigidellaquila** [comment]
Please, try '2.1.x' (not '2.0.x' as I mentioned before), it's the candidate to be next stable.
Thanks
Luigi

**Comment by jaschenk** [comment]
Will do, as soon as I am out of meetings this morning.
Thanks,
Jeff

**Comment by jaschenk** [comment]
I have been successful in performing 1.7 export and a 2.1.3 Import, using the latest 2.1.x Branch in github which built orientdb-community-2.1.3-SNAPSHOT.
This fixed the UUID being missed in previous IMPORTS.

However, now when running integration tests, I see the following exception:

com.orientechnologies.orient.core.exception.OValidationException: The field 'SkywardObject.__uuid' does not match the regular expression '^[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{12}$'. Field value is: uuid, record: CommercialOperatorOrganization#13:0{airframes:[2],title:Jeff A.. Schenk,objState:ACTIVE,isARNManager:true,isOpsManager:true,setUpFinished:true,isPrivate:true,createdBy:#19:0,personnel:[1],about:null,organizationPhoneNumber:+1-123-456-7890,organizationEmail:jeff.schenk@skyward.io,organizationOwner:null,updatedBy:#19:0,updatedByDate:Tue Aug 11 17:14:09 PDT 2015,address:#64:0,startDate:Mon Jun 01 00:00:00 PDT 2015,createdByDate:Wed Jul 01 04:42:26 PDT 2015,isPersonalOrg:true,parts:[1],__uuid:uuid} v3
	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:258)
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2002)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2419)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2309)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.updateRecord(OBinaryNetworkProtocolAbstract.java:390)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.updateRecord(ONetworkProtocolBinary.java:1536)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:365)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)


This is from our SpringBoot SaaS which is an OrientBD client.  Using the build 2.1.3 JARs as well during build and Integration Tests Run.  
POM Dependencies used:
<orientdb.version>2.1.3-DEV</orientdb.version>
 <dependency>
            <groupId>orientdb</groupId>
            <artifactId>orientdb-core</artifactId>
            <version>${orientdb.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>orientdb</groupId>
            <artifactId>orientdb-client</artifactId>
            <version>${orientdb.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>orientdb</groupId>
            <artifactId>orientdb-enterprise</artifactId>
            <version>${orientdb.version}</version>
            <type>jar</type>
        </dependency>
        
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>4.2.0</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.concurrentlinkedhashmap</groupId>
            <artifactId>concurrentlinkedhashmap-lru</artifactId>
            <version>1.4.2</version>
            <scope>runtime</scope>
        </dependency>
The orientdb.version resolves to 2.1.3-DEV, whose artifacts were pushed to our local Nexus Maven Repo to be available for build.

It appears still something is looking for __UUID?

Please advise.

Thanks,
Jeff

**Comment by jaschenk** [comment]
This provides some info from ide.  Where person class has both a property uuid and __uuid.  This must have occurred during import.  Are there restrictions on the field name uuid?

<img width="348" alt="personalsohasa__uuidproperty" src="https://cloud.githubusercontent.com/assets/440314/10091331/cfd60f62-62ee-11e5-8d6c-57960d36aad9.png">
<img width="525" alt="personquerywithuuid" src="https://cloud.githubusercontent.com/assets/440314/10091330/cfd52e6c-62ee-11e5-91f3-d05028d02eca.png">
<img width="1047" alt="personschemawith__uuid" src="https://cloud.githubusercontent.com/assets/440314/10091332/cfe6b22c-62ee-11e5-9949-35f9f0f6ae27.png">

**Comment by jaschenk** [comment]
Since we have duplicate uuid's in the form of uuid and __uuid both appear to contain same data, and each property is mandatory and not nullable, this in turn caused the exception posted above in previous post.  So still issue with import, import our uuid and creating another property named __uuid containing same data.

Please advise as this is blocking our conversion path.

Many Thanks,
Jeff Schenk

**Comment by jaschenk** [comment]
I could perhaps drop the extra __uuid property during our migrations and schema checking prior to our app bootstrap, I might try that to get further along.

**Comment by luigidellaquila** [comment]
Hi Jeff,

I'm looking at this right now.
I still don't understand where this __uuid comes from, but if it's not in your domain you can just drop it.

I'll give you a feedback soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi Jeff,

still hard to reproduce, but I sent you a private email about this

Thanks

Luigi

**Comment by jaschenk** [comment]
Due to a bad legacy migration plan that was left in the code base caused the issue of missing uuid and __uuid properties.
