### ISSUE TITLE
Including a NOT in a query blows up

### ISSUE THREAD

**Issue by optimuspaul** [orientechnologies/orientdb#5014]
Is Not not supported any longer?  I was on 2.0.10 and found that Not didn't work with filtering based on edge properties. So I bumped up to 2.1.2 and now I get this error...

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException - Error on parsing command at position #0: Encountered " <NOT> "NOT "" at line 1, column 62.
Was expecting one of:
    <EOF> 
    <AND> ...
    <OR> ...
    <ORDER> ...
    <GROUP> ...
    <LIMIT> ...
    <SKIP2> ...
    <OFFSET> ...
    <TIMEOUT> ...
    <FETCHPLAN> ...
    <LOCK> ...
    <NOCACHE> ...
    <PARALLEL> ...
    <UNWIND> ...
    ";" ...
    <AND> ...
    <OR> ...
    <GROUP> ...
    <ORDER> ...
    <UNWIND> ...
    <SKIP2> ...
    <OFFSET> ...
    <LIMIT> ...
    <FETCHPLAN> ...
    <TIMEOUT> ...
    <LOCK> ...
    <PARALLEL> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
```

What has happened?

**Comment by lvca** [comment]
Sorry but... what's the query?

**Comment by optimuspaul** [comment]
Looks like this is related
https://github.com/orientechnologies/orientdb/issues/5009


My query is.. `SELECT * FROM cg_sps_application WHERE status = 'Production' NOT (inE('cg_sps_application_subscription')[organization] in 'sps:org:test-00000000-0000-0000-0000-000000000001')`

It blows up on the `NOT`, if I do the `ALTER DATABASE custom strictSQL=false` then it doesn't blow up, but still doesn't give me what I would expect for data. It appears we can't do a NOT on edge properties.

**Comment by optimuspaul** [comment]
export of the data...
https://gist.github.com/optimuspaul/c3702acc9f8af3a9cbc3

**Comment by lvca** [comment]
That query seems invalid. You should put an AND or OR after the first condition. Example:

    SELECT * FROM cg_sps_application
    WHERE status = 'Production'
    AND NOT ( inE('cg_sps_application_subscription')[organization] in 'sps:org:test-00000000-0000-0000-0000-000000000001' )
