### ISSUE TITLE
Can't create edges in ETL import if WAL is set to false, bug or feature?

### ISSUE THREAD

**Issue by d1g1t4l** [orientechnologies/orientdb#5015]
I am using the following ETL config:

```
{
    'source': { 'file': { 'path': '/home/user/test.csv' } },
    'extractor': { 'row': {} },
    'transformers': [
        { 'csv': { 'columnsOnFirstLine': true, 'columns': ['rid1:string', 'rid2:string'] } },
        { 'command': { 'command': 'CREATE EDGE xxxE FROM ${input.rid1} TO ${input.rid2}' } }
    ],
    'loader': {
        'orientdb': {
            'dbURL': 'plocal:/home/user/orientdb-community-2.1.2/_xxx',
            'dbType': 'graph',
            'dbAutoCreate': false,
            'dbAutoCreateProperties': true,
            'tx': false,
            'txUseLog': false,
            'wal': true, <------------------------------------ Script fails if 'wal' is set to false
            'useLightWeightEdges': true,
            'classes': [
                { 'name': 'IsFileOfFunE', 'extends': 'E' },
            ]
        }
    }
}
```

test.csv:

```
rid1,rid2
#12:0,#12:99
#12:1,#12:5
...
```

The import works correctly i.e. creates all the edges, when 'wal' is set to true but it fails when 'wal' is set to false. The error message says the cause is that WAL is disabled. It isn't evident to me why WAL needs to be enabled as I am creating edges and providing two RIDs i.e. no nested queries that might require an implicit transaction. Why is WAL required?

**Comment by robfrank** [comment]
Even if is a list of RID, WAL is stil necessary. Disabling WAL isn't a good practice. It is possible to disable it, but it is better to leave it switched on.

**Comment by grossvater** [comment]
@robfrank Please explain when it is a good practice. The documentation says:
"You could disable the journal (WAL) for some operations where reliability is not necessary"
From this I understand that there are scenarios where WAL may be disabled, but how could I know? I ask because I remember having the same problem during a delete using SQL.
