### ISSUE TITLE
Import database does not activate functions.

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#5016]
Version : orientdb-community-2.1.2

I had a database with a onBeforeCreate function. I exported the database, dropped database, created the database again, then imported the just exported data. Everything seemed to be imported fine but on creating new vertex, the onBeforeCreate function was not being called.

Had to execute the following sql command to get it working again.
```sql
alter class Item custom onBeforeCreate=onBeforeCreateItem
```

**Comment by lvca** [comment]
Do you have the exported database to try it locally?

**Comment by Ziink** [comment]
Emailed you the file. Please check your email.

Note: I tried export and import using a simple function on a fresh database and that worked fine. Might actually have something to do with the schema. Confirmed that the problem shows up in the file I sent you (in orientdb-community-2.1.3).

**Comment by lvca** [comment]
Tried with last v2.2 and works:

    database.command(new OCommandSQL("alter class V custom onBeforeCreate=onBeforeCreateItem")).execute();

export database
import database

The custom setting is there.
