### ISSUE TITLE
Problem with 2.1.(1/2) query against spatial index

### ISSUE THREAD

**Issue by ibeals** [orientechnologies/orientdb#5017]
I recently upgraded from 2.0.4 to 2.1.(1 and 2). In 2.0.4 a query against a value inside a defined bounding box would return vertexes within the box and on the border. Since upgrading, I am only able to return values that lie on the bounding box edges and nothing inside.

**Comment by lvca** [comment]
@maggiolo00 is this something you already addressed in any 2.1.x hotfix?

**Comment by maggiolo00** [comment]
@ibeals 
which is your query?
How can i replicate this issue?

**Comment by ibeals** [comment]
Sample query:
SELECT FROM Point WHERE [latitude, longitude] WITHIN [[42.26531323615103,-83.71986351411135],[42.29239784478525,-83.7662120858887]]

South-east lat/long by North-west for reference.

I encounter this issue when performing the above query. I have a simple vertex with latitude and longitude fields. I create a spatial index. One record with a lat/long value inside of the bounding box does not return with the above sample. Shift the bounding box edges far enough so that the vertex lat/long will lie on an edge of the box (maybe just outside) and it returns the vertex I initially queried for with the above select statement.

**Comment by maggiolo00** [comment]
@ibeals can you provide also one point that fails?

**Comment by maggiolo00** [comment]
@ibeals reproduced
i'm on it

**Comment by ibeals** [comment]
Awesome, you guys rock!

**Comment by maggiolo00** [comment]
@ibeals Fixed
Will be available in 2.1.4

**Comment by ibeals** [comment]
Thank you very much!
