### ISSUE TITLE
OrientDB 2.1.2: index constraints are not checked inside transactions

### ISSUE THREAD

**Issue by doppelrittberger** [orientechnologies/orientdb#5018]
Hi,

I have the following structure:
Class User
 -> String name
Then I define an index based on the name "UserClass.createIndex("byName", OClass.INDEX_TYPE.UNIQUE, "name"). If I now violate this constraint outside a transaction everything works as expected (ORecordDuplicatedException) but if I do the same inside a transaction it will not check/update the index until I commit. But I need to ensure that there are only unique named users inside the transaction. Other RDBMS work the same way, they also check uniqueness while beeing inside a transaction. 
Is there any way to achieve such an behaviour?

Thanks in advance

**Comment by lvca** [comment]
OrientDB uses an optimistic approach, so the check is executed at commit time. You could exec the TX and in case catch the exception and make decision (retry, cancel the operation, etc.)
