### ISSUE TITLE
studio visual bug when trying to create edge on the graph tab

### ISSUE THREAD

**Issue by gandesc** [orientechnologies/orientdb#5019]
When you try to create, visually, an edge between 2 nodes, but the creation wizard fails due to an error, the temporary (black) edge is still visible.

Steps:
1. Log into studio, and go to the graph tab
2. select from a class
3. click on a node, click the create link symbol, draw an edge
4. in  the wizard *select an incompatible edge type* so that the process will fail
5. finish the wizard

The black edge will remain on the canvas, and even "clear canvas" doesn't clear it.
![2015-09-25_1328](https://cloud.githubusercontent.com/assets/14071925/10098394/b43b3264-6389-11e5-94f6-8254681cecab.png)

**Comment by maggiolo00** [comment]
@gandesc 
Fixed in 2.2.x
