### ISSUE TITLE
OrientDB 2.1.2 freezes under heavy load (0,5GB of RAM is not enough)

### ISSUE THREAD

**Issue by micha-nerdlichter** [orientechnologies/orientdb#5022]
I have a rather complex select query working on a lucene index which takes between 0.4 and 0.8 seconds to run. In a test scenario I ran 30 of these queries in parallel through the binary protocol (php driver). CPU usage immediately raises on all 8 cores to >90% and the php driver times out with an "connection reset by peer" error.

The problem is that it takes >35 minutes (!) CPU-time for the CPU usage to drop again. If there are any new queries during this period (even very simple ones) the blockage goes on and Orientdb remains in a frozen state. Stopping the daemon is impossible, only kill -9 works.

So even if the queries get slowed down by the heavy CPU load and take 2 sec or longer, this would be 30x2=60 seconds and not 35 minutes. Why is this blocking all 8 cores for such a long time? With this problem a single user could DDOS the db just by sending a single query request every 2 seconds.

Although memory or swapping doesn't seem to be the problem here I tried to improve Memory and JVM settings as described in http://orientdb.com/docs/2.1/Performance-Tuning.html but this didn't help. Different versions of orientdb (2.1.2, 2.0.15, 1.7.8) show the same problem.

![image](https://cloud.githubusercontent.com/assets/8459594/10105000/d4a2947a-63ac-11e5-805f-18a78aec8dfc.png)

Stacktrace: http://justpaste.it/nz1d

**Comment by micha-nerdlichter** [comment]
Ah, and it doesn't make any differnce whether I use connection pooling or not.

**Comment by micha-nerdlichter** [comment]
> Stopping the daemon is impossible, only kill -9 works.

Might be related to OrientTokenHandler, see https://github.com/orientechnologies/orientdb/issues/5106

**Comment by lvca** [comment]
How many connections do you see from studio, server management panel? Could you please dump here the screenshot?

**Comment by lvca** [comment]
I see also you're using 1/2 GB of RAM. How much RAM do you have available?

**Comment by micha-nerdlichter** [comment]
Sorry it took me a while to switch to enterprise version to get the management panel running. The results here are quite strange: as soon as I launch a bunch of 30 queries in parallel, the panel shows CPU >90% and RAM 101% (how is this even possible?). In total there are 48GB RAM on the server and htop shows only 2.4GB usage for all running processes.

Then the connections gets closed and RAM drops to 87%, CPU to >90% and stays there for ever on all 8 cores until i kill -9 the server. The panel shows 197 active connections.

![image](https://cloud.githubusercontent.com/assets/8459594/10485632/8130596a-728b-11e5-9597-a743bd340792.png)

**Comment by micha-nerdlichter** [comment]
Ah, I realized the -Xmx is for all threads in total, so the default 512m is way too small. Setting it to 8g at least solved the >100% RAM problem. I always just tried smaller values like 2g as I thought this will be consumed by each thread. Now the java threads recover after a few minutes.

So the problem here seems to be that orientdb doesn't complain about too little memory, the server just silently dies and CPU stays on >90% for ever. If you don't have the enterprise edition with the management panel you never realize what is wrong.

It is quite possible that in this case the high memory consumption was caused by the lucene plugin as my queries are running on a lucene index.

**Comment by seeden** [comment]
I have same problem with RAM. If there is no available ram orientdb will silently die. (It will turn off without any running thread)

**Comment by smolinari** [comment]
Interesting information Micha. As a user of OrientDB, I appreciate your work at trying to get to the core of the problem. Hopefully Luca and team can find the cause and a resolution.

Scott

**Comment by lvca** [comment]
Hi guys,
As we provide "tip" to improve performance by setting heap & disk-cache, we could also alert users in case of critical usage of RAM.
