### ISSUE TITLE
Is there a way to mock the OrientDB connection objects

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#5027]
I am trying to do unit testing and I find it hard to mock OrientDB so that I expect specific data on specific calls. Also it seems that OrientDB is also not easy to inject without further wrappers. Any plans to provide an interface instead of a concrete classes?

Thanks,
Michail

**Comment by robfrank** [comment]
IMHO mocking an entire DB is quite difficult and, in my experience, a path to errors and a lot of pain. Orient is easily embeddable, and can works in memory. So my suggestion is to write tests against an in-memory db. 
If your persistence layer (DAO or REpository) is well separated from the business logic, you can mock at this level. Mock only what is under your control. So, write tests against an in-memory orient to verify queries and DAOs: this are more integration  tests than unit tests. Then test the business logic mocking the persistence layer, if you like it; or test the BU wit persistence attached to the in-memory Orient with fake data. 
I hope this could help. If so, please close the issue-

**Comment by zifnab87** [comment]
Thanks @robfrank This is what I am already doing using a memory database that has the same schema but since I am used to write more Unit Tests than integration tests (usually the first ones are more difficult to write and people avoid them) I was trying to see how OrientGraph could be mocked as we can do that with Microsoft's Entity Framework for example..It would help if all those classes involved provided interfaces and didn't have that many dependencies so we can have proxy objects doing those jobs. So I could do something that I would do with C#. graph.when(g => g.getVertices()).Returns(new List(){{ new Vertex(), new Vertex() ... }});

It seems that even Tinkerpop related classes cannot be mocked at all.. This is quite sad in general and I personally think it has to do with old/poor design that doesn't take unit testing into account

**Comment by robfrank** [comment]
Well, I understand your point, but I don't think there's a lack on design. Developing a datastore/dbms is a complete different story that dealing with high level applications.
I worked with other DBs (redis, postgres and even oracle) in the past: no one of that offers mock or stubs. Even Lucene, a library I know quite well, is not easy to mock: it is better to work with index in ram. 
As a rule of thumb, my suggestion is to mock only what you own. So, mock your persistence layer, your interfaces. Components outside of your domain should be tested by intergation tests. Orient offers to you the embeddability (in  java, at least), enjoy it.

**Comment by zifnab87** [comment]
Thank you @robfrank.I might create a mock utility wrapper for OrienGraph at some point, but first I will try using Mockito to at least mock Vertex.class and Edge.class. I know it is not going to be easy but I really would like to minimize the number of my integration tests
