### ISSUE TITLE
2.1.2 - FetchPlan selection

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5028]
**OrientJs**
OrientDb: 2.1.1

```
fetchPlan: 'References:-7 parent:1'
query: select @rid as rid, @class as class, Mid ....
```

```
{ '@type': 'd',
  rid:
   { '@type': 'd',
     '@class': 'Node',
     DisplayName: 'Dustin',
     Email: 'dustin@local',
     Active: false,
     Created: Tue Sep 29 2015 01:31:35 GMT+0200 (W. Europe Daylight Time),
     SponsoredBy:
      { '@type': 'd'
```

Although I just select `References` and `parent` field in the fetchPlan the other links are also fetched `rid`, `SponsoredBy`.

**Studio:**
the same query works in studio if you use `fetchPlan parent:1 References:-7`

**Comment by StarpTech** [comment]
Anybody? I want to upgrade to 2.1x Branch but this issue blocked me. Thanks!

**Comment by StarpTech** [comment]
@luigidellaquila @lvca a short answer or statement would be enough.

**Comment by lvca** [comment]
Have you tried with:

fetchPlan: 'References:-7 parent:1 SponsoredBy:-2'

**Comment by StarpTech** [comment]
I will try it but where is the difference?

**Comment by lvca** [comment]
Any news on this?
