### ISSUE TITLE
Better Authentication in Studio

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5029]
In Chrome and other Browsers the authentication system is very buggy.Sometimes I have to reload many times, sometimes it works immediately. As far I know Orient Studio uses Basic Authentication. It should be used a more powerful authentication system (session based).

**Comment by Conaws** [comment]
Seconded. Or at least say something in the getting started tutorial.  I was convinced this problem was due to changes I made to the password, only after reading this comment did I discover that the password was fine and I just needed to reload the browser.

**Comment by seeden** [comment]
+1

**Comment by maggiolo00** [comment]
+1

**Comment by StarpTech** [comment]
Any updates?

**Comment by maggiolo00** [comment]
Implemented in 3.0 with Session instead of Basic Authentication

https://github.com/orientechnologies/orientdb-studio/issues/424
