### ISSUE TITLE
Proxy Objects are not Serializable

### ISSUE THREAD

**Issue by crudbug** [orientechnologies/orientdb#5038]
I am using Object DB functionality to save Objects directly. Once I save the object in db, I am putting it in a distributed Hazelcast map. The object implements serializable, but returned proxy object is not serializable.

```java
public class Device implements Serializable {

    @Id
    private Object rid;
    @Version
    private Object version;

    private String deviceId;

    public Device() {
    }

   public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
}
```

```java
OObjectDatabaseTx db = OrientConfig.connect();
Device proxy = db.save(device);
hazelcastMap.put("id", proxy);   // error
```

```
java.io.NotSerializableException: com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler
```

I am facing the same issue when I am querying the db.

Question: db.save(instance) method should return the same instance not proxiedObject after saving to db ?

**Comment by dshurt** [comment]
I use orient db in a similar way.   db.save should return the proxied object so it's attached to the db and rid is correct.  You can just  call "Device device = db.detachAll(proxy, true);" to unwrap the proxy then put it into hazelcast.  You can also unwrap after querying if don't intend to update or delete the record(s).

**Comment by lvca** [comment]
@dshurt is right.
