### ISSUE TITLE
explain query doesn't work for version 2.1.1

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5039]
explain doesn't work if you have very complicated query. 

EXPLAIN SELECT EXPAND(UNIONALL($user)) FROM hotel  LET $user = (SELECT EXPAND(IN("list")[@class="user"]) FROM $current) WHERE (source = 196608 AND $user["@rid"] = #16:0)

**Comment by lvca** [comment]
What do you mean for doesn't work?

**Comment by martingg88** [comment]
i do have following error at studio .

The command has not been executed

**Comment by maggiolo00** [comment]
@martingg88 do you see some exception on the Sever?

**Comment by martingg88** [comment]
no...

**Comment by maggiolo00** [comment]
@martingg88 

can you run curl from terminal like this

```
curl -u admin:admin -d "EXPLAIN SELECT EXPAND(UNIONALL($user)) FROM hotel LET $user = (SELECT EXPAND(IN("list")[@class="user"]) FROM $current) WHERE (source = 196608 AND $user["@rid"] = #16:0)" http://localhost:2480/command/test/sql/-
```

just replace `test` with your database and change credential with yours
and paste the JSON here

**Comment by martingg88** [comment]
here is the bug. 
{
  "errors": [{
      "code": 500,
      "reason": 500,
      "content": "com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered \" \"=\" \"= \"\" at line 1, column 43.\u000d\u000aWas expecting one of:\u000d\u000a    <TO> ...\u000d\u000a    <VALUES> ...\u000d\u000a    <SET> ...\u000d\u000a    <ADD> ...\u000d\u000a    <PUT> ...\u000d\u000a    <MERGE> ...\u000d\u000a    <CONTENT> ...\u000d\u000a    <REMOVE> ...\u000d\u000a    <ORDER> ...\u000d\u000a    <GROUP> ...\u000d\u000a    <OFFSET> ...\u000d\u000a    <RECORD> ...\u000d\u000a    <LUCENE> ...\u000d\u000a    <NEAR> ...\u000d\u000a    <WITHIN> ...\u000d\u000a    <EXCEPTION> ...\u000d\u000a    <IN> ...\u000d\u000a    <KEY> ...\u000d\u000a    <IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <IDENTIFIER> ...\u000d\u000a    <IN> ...\u000d\u000a    <SET> ...\u000d\u000a    <PUT> ...\u000d\u000a    <ADD> ...\u000d\u000a    <REMOVE> ...\u000d\u000a    <MERGE> ...\u000d\u000a    <CONTENT> ...\u000d\u000a    <ORDER> ...\u000d\u000a    <KEY> ...\u000d\u000a    <OFFSET> ...\u000d\u000a    <GROUP> ...\u000d\u000a    <VALUES> ...\u000d\u000a    <RECORD> ...\u000d\u000a    <TO> ...\u000d\u000a    <LUCENE> ...\u000d\u000a    <NEAR> ...\u000d\u000a    <WITHIN> ...\u000d\u000a    <EXCEPTION> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    <QUOTED_IDENTIFIER> ...\u000d\u000a    "
      }
  ]
}

**Comment by lvca** [comment]
The @maggiolo00 command contained ". Try rather this:

    curl -u admin:admin -d "EXPLAIN SELECT EXPAND(UNIONALL($user)) FROM hotel LET $user = (SELECT EXPAND(IN('list')[@class='user']) FROM $current) WHERE (source = 196608 AND $user['@rid'] = #16:0)" http://localhost:2480/command/test/sql/-

**Comment by martingg88** [comment]
still the same issue.

**Comment by lvca** [comment]
without EXPLAIN the query is executed?

**Comment by martingg88** [comment]
yes it was executed without explain.

**Comment by luigidellaquila** [comment]
Hi @martingg88 

The parsing problem is already fixed. Just consider that in 2.2 the `EXPAND(UNIONALL($user))` is not allowed in a single query (you have to wrap it in a subquery) because it's an aggregate function.

I'm closing this issue. Please reopen if you see any related problems.

Thanks

Luigi
