### ISSUE TITLE
Problem with addEdge in OrientVertex class + graphAPI

### ISSUE THREAD

**Issue by amiricool** [orientechnologies/orientdb#5041]
When i create edges from vertex V1 to several other vertices, they are indeed created (for non-lightweight's type / document) but i can't access to all edges from V1.
The issue is still reproductible for both lightweight and document edges: the edge reference is not set in both vertices.

Example with lightweight :
query1:

select from (traverse in('linkedTo') from #54:59)

response1:
@rid | @version | @class | linkedTo(in) | linkedTo(out)
#54:59 | 2 |Person| #12:44 |

query2:

select from (traverse out('linkedTo') from #12:44)

response2: In the response of the query two i don't find the vertex with the @rid #54:59

Is this issue already known? I can provide steps for reproduction if necessary.

**Comment by maggiolo00** [comment]
hi @amiricool 
can you provide steps to reproduce it?

thanks

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
