### ISSUE TITLE
Make SQL CONTENT accept positional/named parameter

### ISSUE THREAD

**Issue by urugator** [orientechnologies/orientdb#5045]
Even though it's not something I could not live without, I think it would make sense to be able to do:

``` java
graph.command(new OCommandSQL("create vertex Scope CONTENT ?")).execute(jsonObject.toString());

graph.command(new OCommandSQL("create vertex Scope CONTENT :content")).execute(params);
```

**Comment by luigidellaquila** [comment]
Hi @urugator 

I have some doubts about this, passing a string parameter in that position would be equivalent to this

```sql
create vertex Scope CONTENT "{foo:'bar'}"
```

that is far different from 

```sql
create vertex Scope CONTENT {foo:'bar'}
```

I guess it can be implemented in a different way, eg.

```java
graph.command(new OCommandSQL("create vertex Scope CONTENT ?")).execute(jsonObject);
```
(I just removed the ```.toString()```) but we have to define what exactly ```jsonObject``` is (its type in particular)

Any thoughts?

Luigi

**Comment by urugator** [comment]
I didn't realize that, but wouldn't make more sense if the way how a parameter is represented in a query would be determined not only by it's type but also by it's context in query?

However, I think there are three options:

1) Choose one of the existing json object implementations.
- I would lean towards javax.json.JsonObject simply because it's standard, no dependencies needed.
- Json string needs to deserialized to json object, or unsupported json object implementation used by user must be converted into json object implementation supported by OrientDB. This might be unnecessary overhead if it's only purpose is to pass parameter (which is essentially just a string) to query.
- Most of the json object implementations implements Map interface, which is already used for named parameters, this might not be a problem if we support all other Json structures as parameters: JsonArray, JsonString, JsonNumber (that could be actually quite cool). 

2) Create simple string wrapper, whose type can by used to differentiate Json from String: 
OJsonParam jsonParam = OJsonParam.get(String json)
- It's kind of artificial 
- No json deserialization/conversion overhead
- Requires serialization when working with json object
- Probably easy to implement

3) Reuse some strucutre which is already used internally by Orient.
(I don't know how orient handles json internally)
