### ISSUE TITLE
Graph API should also accept String/ORecordId as an alternative to Vertex/Edge (feature request)

### ISSUE THREAD

**Issue by urugator** [orientechnologies/orientdb#5052]
Often only information needed or provided to perform some operation is an RID of Vertex/Edge.
However most of the Graph API methods accept only reference to Vertex/Edge.
There are two ways to obtain a reference to Vertex/Edge:
1) Fetching that reference by RID via Graph API, which is redundant and inefficient.
2) Creating Vertex/Edge reference manually: 
```java
Vertex v = new OrientVertex(graph, new ORecordId("11:0"));
```
This is quite verbose and can be done automatically.

Examples:
```java
vertex.addEdge("label", "12:0");
vertex.addEdge("label", new ORecordId("12:1"));

**Comment by zifnab87** [comment]
My guess is this is because OrientDB Graph API is using TinkerPop Vertex and TransactionalGraph implementations under the cover. TinkerPop Blueprints is for Graph databases what JDBC/ODBC became for relational databases.

**Comment by urugator** [comment]
OrientGraph as an implementation of TinkerPop 2 Graph API already extends that API  (for example OrientGraph.addVertex(Object id, Object ...prop)). The underlying implementation is not a limiting factor, because it works already with aforementioned manual Vertex/Edge creation.
So I think it's only about adding new signatures which will do the creation and delegate the call to an existing methods.

**Comment by zifnab87** [comment]
I understand your point. Though then we will have to use concrete implementations 

like OrientVertex vertex = new OrientVertex(...) instead of
Vertex vertex = ....

making the code really coupled to a specific graph technology. That is my opinion and as a disclaimer I am not in OrientDB team :)

**Comment by lvca** [comment]
This is already supported via `graph.getVertex(<value>)` where value can be:
- a vertex
- a rid
- a string representing a rid
- a document representing a vertex

**Comment by urugator** [comment]
I described that option as:

1) Fetching that reference by RID via Graph API, which is redundant and inefficient.

By definition Graph.getVertex(Object o) must return null if the record with that ID does not exist. This means there must be a DB lookup (+ rountrip in remote mode) performed, which is what I am trying to avoid.

**Comment by lvca** [comment]
Got it. I prefer to have a more clear signature than accepting a generic string or ORID to avoid users think they can put any document as parameter.
