### ISSUE TITLE
Find Vertex by type

### ISSUE THREAD

**Issue by dantodor** [orientechnologies/orientdb#5053]
Given Scala code of this kind:
val course1 = sg.addVertex("course", Map("name" -> "Course 1"))
Is there a way in which I can query for the vertexes of a certain type in the traversal ? I.E. instead of g.V() , g.V("some type") ?

**Comment by luigidellaquila** [comment]
Hi @dantodor 

you can try this in Gremlin:

```
g.V().has('@class', T.eq, "YourTypeName")
```

or just, in SQL

```sql
select from YourTypeName
```

**Comment by lvca** [comment]
From Blueprints you can use:

```java
graph.getVerticesOfClass("YourTypeName")
```
