### ISSUE TITLE
UNIQUE_HASH_INDEX not being updated locally in asynchronous replication.

### ISSUE THREAD

**Issue by ghost** [orientechnologies/orientdb#5058]
I have a three-node cluster (let's call the nodes `n1`, `n2` and `n3`) and a graph database set to use `executionMode` equal to `asynchronous`. I have the following schema in-place:

```
CREATE CLASS Thing EXTENDS V
CREATE PROPERTY Thing.uuid STRING
ALTER PROPERTY Thing.uuid MANDATORY TRUE
ALTER PROPERTY Thing.uuid NOTNULL TRUE
CREATE INDEX Thing.uuid UNIQUE_HASH_INDEX
```

Now, I issue the following to `n1` (using the console, but the same thing happens with the Java Graph API):

```
CREATE VERTEX Thing SET uuid = '2113de93-604a-4b98-a071-fec7a025f884'
```

If I `SELECT FROM Thing` now, all three nodes now report the existence of a `Thing` record with `uuid` equal to `2113de93-604a-4b98-a071-fec7a025f884` (as expected). However,

```
SELECT FROM INDEX:Thing.uuid WHERE key = '2113de93-604a-4b98-a071-fec7a025f884'
```

only returns the expected result in `n2` and `n3`. `n1` (the target node when writing) reports `0 item(s) found.`. The same thing happens on `n2` or `n3` if the `CREATE VERTEX` is issued to any of these nodes. It does not happen if `executionMode` is set to `undefined` or `synchronous`.

**Comment by bmcustodio** [comment]
@lvca where you aware of this?

**Comment by lvca** [comment]
What release are you using?

**Comment by bmcustodio** [comment]
@lvca This affects 2.1.2 and 2.1.3 (at least).

**Comment by lvca** [comment]
Please could you try 2.1.5?

**Comment by lvca** [comment]
Fixed long time ago.
