### ISSUE TITLE
Optimize index usage

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5059]
There are some common use case with indexes that are sub-optimal. Below the list:
- [x] propagate the `count()` to the index avoiding to count the entries by iterating them
- [x] `index.get()` creates a HashSet with the copy of the resultset. This is completely unnecessary and could be resolved by using `Collections.unmodifiableSet(values)`

**Comment by lvca** [comment]
@maggiolo00 please can you check now the `select count(*)` on Lucene is super fast?

**Comment by maggiolo00** [comment]
@lvca tesing now

**Comment by laa** [comment]
Result of this enhancement reveals core internal classes to remote client and those classes can not be properly serialized/deserialized. I will reimplement this feature.

**Comment by laa** [comment]
Sorry , my mistake
