### ISSUE TITLE
sysdate function returns string instead of date if params are defined

### ISSUE THREAD

**Issue by motih78** [orientechnologies/orientdb#5060]
Hi,

When calling the sysdate function without params, a property of type datetime is created with the default date format.

However - when providing a custom date format and / or timezone, the function returns a string. 
I would expect that the function will return date even when we pass params - this behavior is giving us a headache since the datatype in the database is not consistent. It should be datetime regardless if params are sent or not.

Thanks,
Moti.

**Comment by lvca** [comment]
Why are you using sysdate instead of date?

**Comment by motih78** [comment]
Hi,

I'm doing an insert via SQL and i want the current date to be used without me needing to specify the date as string from the outside.

Thanks,
Moti.

**Comment by lvca** [comment]
Ok, so why don't use `sysdate()` ?

**Comment by motih78** [comment]
Because i want it in UTC for example, or any other timezone, and i don't want the same format / timezone for all the tables in the DB (thus alter database dateformat "dd MMMM yyyy" is not an option)
Point is - a date function should return a single type - date and not date or string.

If format / timezone manipulation should be done outside of the scope of the function, then it should't receive params at all.

**Comment by lvca** [comment]
It makes no sense calling `sysdate()` with a format if you want the current date. The format or timezone don't change the "now" that is now no matters the format or timezone. About the returning type I could agree with you that could be confusing, but I prefer to document it better than remove this feature. Closing this issue.
