### ISSUE TITLE
OrientGraph.begin() does not increment TX nesting counter (2.1.x)

### ISSUE THREAD

**Issue by urugator** [orientechnologies/orientdb#5067]
Any additional call of OrientGraph.begin() is ignored when there is a currently running TX, instead of delegating a call to ODatabaseDocumentTx, to increment TX nesting counter, to support TX propagation.
However OrientGraph.rollback() and OrientGraph.commit() decrements the counter, making the behavior inconsistent.

Here is the problematic piece of code:
```java
// OrientTransactionalGraph.begin()
public void begin() {
  makeActive();

  final boolean txBegun = database.getTransaction().isActive();
  if (!txBegun) {
    database.begin();
    database.getTransaction().setUsingLog(settings.isUseLog());
  }
}
```

I think a decision needs to be made whether OrientGraph supports TX propagation the same way as ODatabaseDocumentTx, then make behavior consistent and provide better documentation.

**Comment by laa** [comment]
Duplication of https://github.com/orientechnologies/orientdb/issues/5693

**Comment by laa** [comment]
Fixed
