### ISSUE TITLE
Cannot change property type from DOUBLE to INTEGER

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5070]
Orientdb 2.0.14

Studio:

``` sql
ALTER PROPERTY Node.Points TYPE integer
```

**java.lang.IllegalArgumentException: Cannot change property type from DOUBLE to INTEGER**

```
POST http://127.0.0.1:2480/command/test/sql/-/20?format=rid,type,version,class,graph 500 (Internal Server Error)
```

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

does your database contain any data in Points property?

Thanks

**Comment by StarpTech** [comment]
Hi @luigidellaquila 
yes "integer" values default 0 or some others with small values under 100.

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

I'll check it, if the backporting is not too expensive I'll do it of course

Thanks

**Comment by StarpTech** [comment]
Thanks

**Comment by StarpTech** [comment]
@luigidellaquila any updates?
