### ISSUE TITLE
Cannot remove document from LINKSET/LINKLIST

### ISSUE THREAD

**Issue by Kikimora** [orientechnologies/orientdb#5073]
OrientDB 2.0.8

ORID of new records changes after transaction commit to reflect new persistent identifier assignment. This lead to very strange bug when I cannot remove records from ORecordLazySet. Reproducing this bug requires some luck since it depends on ORID hash code and triggers when it changes in way, that it maps to another HashMap bucket.

My temporary workaround is to call ODocument.reload before removing anything from LINKSET or LINKLIST. Reload recreate ORecordLazySet objects from scratch and repopulate internal map with correct ORID instances.

Test case below.

```
@Test
    public void oBug() {
        try (ODatabaseDocumentTx db = App.getMasterDatabase().acquire()) {
            db.begin();
            {
                ODocument parent = db.newInstance();
                ODocument child = db.newInstance();
                HashSet children = new HashSet();
                children.add(child);
                parent.field("children", children, OType.LINKSET);
                child.save();
                parent.save();
                ORID parentId = parent.getIdentity();
                ORID childId = child.getIdentity();
                int parentHashCode = parentId.hashCode();
                int childHashCode = childId.hashCode();
                db.commit();
                assertEquals(parentHashCode, parentId.hashCode());
                assertEquals(childHashCode, childId.hashCode());
            }
        }
    }
```

**Comment by tglman** [comment]
Hi @Kikimora,

This is on purpose, the id are not generated till the commit, this is how OrientDB works so this is an expected behavior.

Closing
