### ISSUE TITLE
Callback ignored in JSONP calls to the HTTP RESTful Endpoint

### ISSUE THREAD

**Issue by dej611** [orientechnologies/orientdb#5074]
Until version 2.1.2 of OrientDB I used to call the RESTful HTTP endpoint with JSONP requests with no problem:

```js
function callOrientDB(query){
  var credentials = 'reader:reader';
  var baseURL = 'http://localhost:2480/query/VehicleHistoryGraph/sql/';
  return $.ajax({
    type: 'GET',
    url: baseURL+encodeURIComponent(query),
    dataType: 'jsonp',
    contentType: 'application/json',
    headers: {
      Authorization: 'Basic '+btoa(credentials)
    },
  })
  .done(callback);
}
```

What the result used to be (until 2.1.2) is something like the following:
```js
jQuery17209145641725044698_1444301282307({"result":[ ... ] });
```

What is returning since upgrading to 2.1.3 is a pure JSON:
```js
{"result":[ ... ]}
```

Which of course upsets jQuery:
```
Uncaught SyntaxError: Unexpected token :
```

**Comment by dej611** [comment]
Just followed [the guide](https://github.com/orientechnologies/orientdb-docs/blob/18459ecc1770cf3347a94e8a2d0775184c7aa181/source/Web-Server.md#jsonp) to restore back the previous setting about JSONP in the webserver.

For who lands here from a search engine, here's the solution:
* Go to `orientdb-server-config.xml`
* Enable again the JSONP support by adding the following entry:  
  ```<entry value="true" name="network.http.jsonp"/>```
* Restart OrientDB et voilà

**Comment by luigidellaquila** [comment]
Hi @dej611 

Yes, the default was changed for security reasons.
I suppose I can close this issue

Thanks

Luigi

**Comment by Wirone** [comment]
I have OrientDB 2.1.6 installed (on Windows) and even if I add `<entry value="true" name="network.http.jsonp"/>` to `orientdb-server-config.xml` (I guess it should be in `<properties>` like other `<entry>s`) and restart server (actually I'm restarting system service), I don't get JSONP response.

I am requesting with Postman and I'm getting clear JSON response (`callback` parameter is in the request).

**Comment by maggiolo00** [comment]
hi @Wirone 

just tested in 2.1.6 with this config in orientdb-server-config.xml

```
<properties>
        <entry value="1" name="db.pool.min"/>
        <entry value="50" name="db.pool.max"/>
        <entry value="true" name="network.http.jsonp"/>
        <entry value="true" name="profiler.enabled"/>
        <entry value="info" name="log.console.level"/>
        <entry value="fine" name="log.file.level"/>
    </properties>
```

And it worked.

**Comment by dej611** [comment]
Just dropping here a new note. Since OrientDB 2.2.x the trick explained above doesn't work any more.

We've found another solution explained here: http://stackoverflow.com/questions/27612752/building-web-app-using-orientdb-javascript-api

For who lands here from a search engine, here's the solution - quoting from the linked page:

> Add this entry in config/orientdb-server-config.xml
> ```
> <parameter name="network.http.additionalResponseHeaders" value="Access-Control-Allow-Origin: * ;Access-Control-Allow-Credentials: true;Access-Control-Allow-Headers: Content-Type;Access-Control-Allow-Methods: POST, GET, DELETE, HEAD, OPTION" />
>```
>above
> ```
> <parameter value="utf-8" name="network.http.charset"/>
> ```
