### ISSUE TITLE
Receive Error: java.lang.OutOfMemoryError: Java heap space error

### ISSUE THREAD

**Issue by rakeshghodasara** [orientechnologies/orientdb#5077]
I get the error

Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessin

Error: java.lang.OutOfMemoryError: Java heap space

when running a query from console.  I have a 16 GB RAM Machine(AWS) and I have also changed the parameters for the memory allocation. these are 

Console.sh 
ORIENTDB_SETTINGS="-Djava.util.logging.config.file=\"$ORIENTDB_HOME/config/orientdb-client-log.properties\" -Djava.awt.headless=true"

SSL_OPTS="-Xmx2g -Dclient.ssl.enabled=false

server.sh
MAXHEAP=-Xmx2g
MAXDISKCACHE="-Dstorage.diskCache.bufferSize=8192"

**Comment by maggiolo00** [comment]
@rakeshghodasara  which query are you running?
did you get OOM in console process or server?

**Comment by rakeshghodasara** [comment]
I got the exception in the console process.  However the console process did continue to run.  only the query crashed.

**Comment by luigidellaquila** [comment]
Hi @rakeshghodasara 

the DISTINCT operation is memory bound, so OrientDB will try keep the resultset in memory.

You can avoid this by providing more RAM or by adding some constraints to the inner query, like a LIMIT.

We are working to move all the transaction management on a disk-backed structure, to completely solve this problem. This feature is in the roadmap for v 3.0, so in the short term I think you'll have to consider a work-around

Thanks

Luigi
