### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by bazo** [orientechnologies/orientdb#5079]
The error messages that orientdb throws are very cryptic
like com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #15

but why? what is wrong? how should i fix it?

or com.orientechnologies.orient.server.distributed.ODistributedException: Error on execution distributed CREATE_RECORD

this appears when a value would violate a duplicate index but also in some other cases

i have fortunately encountered only these 2 errors.

but what's wrong with DuplicateKeyException or WrongValue exception and some hints how to fix the error or what precisely went wrong, like all other databases.

Non meaningful error messages drastically reduce the developer experience and you should fix this asap

**Comment by laa** [comment]
Hi, it is fixed in 2.2 version together with incremental backup. now ODuplicatedKeyException, RecordNotFoundException, OConcurentModificationException and so on are never wrapped in cryptic exceptions any more.

**Comment by bazo** [comment]
cool, when is it gonna be out?
