### ISSUE TITLE
2.1.3: OCommandScript compatibility

### ISSUE THREAD

**Issue by dennwc** [orientechnologies/orientdb#5085]
Hi,
I'm currently working on native (binary) OrientDB driver for Golang ([orientgo](https://github.com/istreamdata/orientgo)) and have some problems with 2.1.3 version support.

Recent change in commit https://github.com/orientechnologies/orientdb/commit/25959255e96705ecf770960103ebf3463a36f54d breaks backward compatibility of `OCommandScript` serialization format. There is no good way to determine if server uses a newer version, as nor binary protocol version, nor binary serializer version have changed. The only way to determine that new format should be sent on wire is to put some ugly hooks to handshake, to parse OrientDB server version and then somehow replace serialization routine for one particular connection pool or catch binary representation of `OCommandScript` on wire and transform it accordingly.

Would you mind, to implement another version of `OCommandScript` which follows new logic, and has a class different from `s`?

Thanks!

**Comment by lvca** [comment]
This has been already fixed in 2.1.4-SNAPSHOT that will be released on monday. You can try the last snapshot online.

**Comment by dennwc** [comment]
Great! Thanks!
