### ISSUE TITLE
v2.1.3 won't start on Ubuntu 14.04

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#5086]
I just installed OrientDB 2.1.3 on Ubuntu 14.04 server, but after startign it and checking the status, it shows that the daemon is not running. 

On running `orientdb`, I get this error:

```
Error: Could not find or load main class com.orientechnologies.orient.graph.console.OGremlinConsole
```

**Comment by finid** [comment]
By the way, nothing was written to the installation log file.

**Comment by alexmm11** [comment]
i have orientdb-2.1.3 running on ubuntu 14.04 aws instance.
Check this out :
http://www.famvdploeg.com/blog/2013/01/setting-up-an-orientdb-server-on-ubuntu/

**Comment by luigidellaquila** [comment]
HI @finid 

This should be already fixed in latest stable, could you please confirm?

Thanks

Luigi

**Comment by lvca** [comment]
Closing because no answer after months. In case please reopen/comment this.
