### ISSUE TITLE
Select document based on condition on its field whose type is lists of EMBEDDED

### ISSUE THREAD

**Issue by yudho** [orientechnologies/orientdb#5092]
The documents can be created with these commands
````
INSERT INTO SalesOrder CONTENT {name:"salesorder1",lists:[{"name":"bag","price":2},{"name":"computer","price":8}]}
INSERT INTO SalesOrder CONTENT {name:"salesorder2",lists:[{"name":"shirt","price":20},{"name":"laptop","price":17}]}
````
What if I want to select sales orders whose lists contain an item with name = "laptop" ?
I tried to do
````
SELECT * FROM SalesOrder WHERE lists["name"] = "laptop"
````
and
````
SELECT * FROM SalesOrder WHERE lists[name] = "laptop"
````
and
````
SELECT * FROM SalesOrder WHERE lists[name = "laptop"]
````
and
````
SELECT * FROM SalesOrder WHERE lists["name'" = "laptop"]
````
and
````
SELECT * FROM SalesOrder WHERE lists.name = "laptop"
````

nothing works.

I know that
````
SELECT * FROM SalesOrder WHERE lists[1]['name'] = "laptop"  
````
works, however, that does not satisfy the requirement where I should be able to select document that contains an item in its list without knowing the position of the item in the array.

Am I doing it wrong or is this a missing feature?

**Comment by luigidellaquila** [comment]
Hi @yudho 

you have to have to use CONTAINS operator, because your "lists" are lists ;-)
eg.

SELECT * FROM SalesOrder WHERE lists["name"] contains "laptop"

**Comment by luigidellaquila** [comment]
BTW, this is not the best place to ask for questions, please use StackOverflow with tag ```orient-db``` instead

http://stackoverflow.com/questions/tagged/orient-db
