### ISSUE TITLE
Error on spatial index during import database command.

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientdb#5097]
Hi, thanks for your effort and great job with OrientDB, i really like the concept of OrientDB as database, but i'm facing a situation that's describes next:

I have an Address Class with latitude and longitude properties and a lucene spatial index, and all works fine.

Class scheme:
![seleccion_012](https://cloud.githubusercontent.com/assets/521303/10413414/8a81473e-6f6d-11e5-9264-73533ceeb336.jpg)

Class records:
![seleccion_011](https://cloud.githubusercontent.com/assets/521303/10413422/a3d39c64-6f6d-11e5-9cf2-74abec911829.jpg)

**The problem comes up at the moment to execute the database import to a new empty database.**

Console output:
![seleccion_013](https://cloud.githubusercontent.com/assets/521303/10413434/e4204e02-6f6d-11e5-9255-0951207c5318.jpg)

**Comment by alexmm11** [comment]
I forgot to mention, but this happens on 2.1.2 and 2.1.3 versions.

**Comment by alexmm11** [comment]
I tried the 2.1.12 version and this error still the same :(

**Comment by robfrank** [comment]
The error says that the index SPATIAL with algorithm SBTREE doesn't exists, and it is right, should be LUCENE algorithm. have you got some scripts to reproduce the problem? and some sample data?

**Comment by alexmm11** [comment]
Ok, this script creates a test database.

[SpatialIndexDBTest.osql.txt](https://github.com/orientechnologies/orientdb/files/159512/SpatialIndexDBTest.osql.txt)
 
The problem occurs when i try to import the database,  after of a new orientdb installation for example.

Note: I export the database from the browser.

**Comment by alexmm11** [comment]
Hi guys, something new? =)

**Comment by horaciosolorio** [comment]
I have same issue, any update ? please.

**Comment by robfrank** [comment]
On latest 2.1.13 I'm able to export and reimport without errors.

**Comment by martingg88** [comment]
we still have this error for version 2.1.14. Please double check . thanks

**Comment by alexmm11** [comment]
I just tried version 2.1.15 and this still happens

**Comment by robfrank** [comment]
I reopen the issue, but I need a very detailed report: db schema, sample data and operations sequence used to export and then reimport the db.

**Comment by alexmm11** [comment]
Ok, this is the sequence:

1.- Database creation
[SpatialIndexDBTest.osql.txt](https://github.com/orientechnologies/orientdb/files/213717/SpatialIndexDBTest.osql.txt)

 and here is the log:
![seleccion_052](https://cloud.githubusercontent.com/assets/521303/14439979/7ca7cdd8-fff3-11e5-88c0-2dbdd183a3c3.png)

2.- Export the database
![seleccion_053](https://cloud.githubusercontent.com/assets/521303/14440280/c757b72a-fff4-11e5-973f-67f43eedb869.png)

3.- Drop the database
![seleccion_054](https://cloud.githubusercontent.com/assets/521303/14440725/e0a201a2-fff6-11e5-9782-265903323bf8.png)

4.- Create and import the database
![seleccion_055](https://cloud.githubusercontent.com/assets/521303/14441041/70029784-fff8-11e5-98e9-91b4203f47c3.png)

![seleccion_056](https://cloud.githubusercontent.com/assets/521303/14441168/16e30480-fff9-11e5-868c-410c00f9f120.png)

**Comment by robfrank** [comment]
hi, I managed to replicate the problem. It is related to **remote** protocol.
We don't have a fix for that right now, I hop we will fix in th. The workaround is to import using **plocal**, but you need to switch off the server:
* switch off the server
* import the database using plocal:/path/to/the/database
* switch on the server
