### ISSUE TITLE
Error: Could not find or load main class com.orientechnologies.orient.graph.console.OGremlinConsole

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#5098]
After installing on Ubuntu 14.04, the server can start, but running the console `orientdb` generates this error:

```
Error: Could not find or load main class com.orientechnologies.orient.graph.console.OGremlinConsole
```

However, I can run the following and be connected:

```
sudo -u orientdb /opt/orientdb/bin/console.sh
```

What could be the cause of the error message?

**Comment by maggiolo00** [comment]
@finid which version of OrientDB?

**Comment by finid** [comment]
OrientDB 2.1.3

**Comment by maggiolo00** [comment]
@finid seems some path problem.
if you go directly in 
/opt/orientdb/bin 
and 
then ./console.sh?

**Comment by finid** [comment]
@maggiolo00, provided that's preceded with `sudo`, that works.

But is that the only and best way to enter the command line interface?

**Comment by sonyarouje** [comment]
I got the same issue when running from my Raspberrypi. To fix the issue.
Before copying the console.sh to /usr/bin/orientdb
1. Open bin/console.sh
2. Add a line at the top of file like ORIENTDB_HOME="path to Orientdb directory". In my case I added a line like ORIENTDB_HOME="/home/pi/orientdb"
3. Copy the file to /usr/bin/orientdb

**Comment by renanosf** [comment]
thank you very much @sonyarouje
it worked!!

**Comment by rokx** [comment]
@sonyarouje After 7 years your comment is still relevant. Thank you.
