### ISSUE TITLE
Retrieve @rid of document in onAfterCreate, onAfterUpdate, onAfterDelete hooks

### ISSUE THREAD

**Issue by tobiemh** [orientechnologies/orientdb#5099]
When implementing a custom function with one of the onAfterCreate / onAfterUpdate / onAfterDelete custom hooks, it is not possible to get the current rid of the document, but instead when calling `doc.field('@rid');` the value returned is #-2:0.

My understanding is that this is because the record has not yet been committed. If you do `doc.commit(); doc.field('@rid');` then the rid is returned successfully, however the record is now submitted.

Am I doing something wrong, and is there a better way of getting the document rid AFTER creating/updating/deleting? ... or would it be possible to implement an `onAfterCommit` hook which would be called when the record has ACTUALLY been created/updated/deleted to the database?

*I'm not sure whether calling `doc.commit();` in an onAfterCreate / onAfterUpdate / onAfterDelete hook affects transactions or not...*

***
OrientDB version: 2.1.3

**Comment by lvca** [comment]
You can implement `ODatabaseListener` interface to get, among others, the following events:

```java
  void onBeforeTxBegin(final ODatabase iDatabase);
  void onBeforeTxRollback(final ODatabase iDatabase);
  void onAfterTxRollback(final ODatabase iDatabase);
  void onBeforeTxCommit(final ODatabase iDatabase);
  void onAfterTxCommit(final ODatabase iDatabase);
```

**Comment by tobiemh** [comment]
Hey @lvca sorry I forgot to mention that I'm using the [dynamic hooks](http://orientdb.com/docs/2.1/Dynamic-Hooks.html).

Is this possible at all using javascript/groovy and dynamic hooks which extend the OTriggered class?

*p.s I'm using Node.js / HTTP to interact with OrientDB so Java isn't an option here*

Thanks
