### ISSUE TITLE
Possibility to RETURN both BEFORE + AFTER in RETURN statement

### ISSUE THREAD

**Issue by tobiemh** [orientechnologies/orientdb#5100]
Would it be feasible to implement functionality that would allow an sql query to return the content of a record both before and after a record is created/updated.

At the moment it's possible to use `RETURN BEFORE` to get the content of the record before any changes were implemented in the database, and to use `RETURN AFTER` to get the content of the record after changes were implemented in the database, however, it would be useful to be able to get both the original (as defined by OOriginalRecordsReturnHandler) and the updated (as defined by OUpdatedRecordsReturnHandler) values.

Perhaps this could be implemented using an sql statement such as `RETURN CHANGES`. This could return each changed object as a row with 2 columns (in addition to the `rid`, `version`, `class` columns):
- `before` column which would have the content of the record as it was before the changes.
- `after` column which would have the content of the record as it was after the changes.

This would be especially useful when using live queries, as currently it is not possible to get the content of the record before it was changed (will create a separate issue for live queries).

_There is similar functionality available in the NoSQL database [rethinkdb](https://rethinkdb.com/api/javascript/update/), where you can pass the `returnChanges` argument and the response will contain the changed values as an array._

---

OrientDB version: 2.1.3

**Comment by lvca** [comment]
@luigidellaquila WDYT?

**Comment by lvca** [comment]
Not relevant anymore, closing it.

**Comment by riker09** [comment]
Why is this not relevant anymore? Please elaborate. I was looking for exactly this feature. Has this been implemented in a different way (that is maybe not in the docs yet)?
