### ISSUE TITLE
Getting before and after values of record in live queries

### ISSUE THREAD

**Issue by tobiemh** [orientechnologies/orientdb#5101]
When using live queries it would be good if it were possible to get both the original record value as well as the updated record value, when listening for inserted / deleted / updated records.

When looking at similar databases which offer similar functionality; **DynamoDB** with live streams, and **RethinkDB** with change-feeds, it is possible to get the original values of the record as well as the updated values of the record.
- With DynamoDB you can specify NEW_AND_OLD_IMAGES which will cause live streams to contain the old and new values [more info available here](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html).
- With RethinkDB each change automatically contains the old and new values [more info available here](https://rethinkdb.com/api/javascript/changes/).

This is similar to the functionality proposed in issue #5100

---

OrientDB Version: 2.1.3

**Comment by lvca** [comment]
I think this is easy (we have tracked fields with old values) and cool feature. @luigidellaquila WDYT?

**Comment by luigidellaquila** [comment]
+1 I like it and it should be easy to implment

Thanks for the suggestion
