### ISSUE TITLE
2.1.2 - Java API translate Double type into Float type

### ISSUE THREAD

**Issue by motih78** [orientechnologies/orientdb#5103]
Hi,

When trying to insert a vertex with a property of java type Double via Java API (SQL prepared statement syntax) the property is saved as type FLOAT in the DB. This causes us problems in deserialization from the DB when we try to put FLOAT into Double

Also - if you execute the following command via the web UI "insert into Test (num) values (1.2)" the property is of type Double but when you execute "insert into Test (num) values (1.0)" the property is of type FLOAT - how come?

Seems like there is some kind of types issue here

**Comment by StarpTech** [comment]
Similiar issue here https://github.com/orientechnologies/orientdb/issues/5070
