### ISSUE TITLE
Cannot find a command executor for the command request error on Windows

### ISSUE THREAD

**Issue by tarkal** [orientechnologies/orientdb#5105]
I have an embedded version of OrientDB 2.1.2. When I execute the following SQL command on a Linux or OSX OS it works great:

    DELETE VERTEX Team WHERE @rid=16:1

I also tried the following variations just in case all with the same outcome:

    DELETE VERTEX Team WHERE @rid='16:1'
    DELETE VERTEX Team WHERE @rid=#16:1
    DELETE VERTEX Team WHERE @rid='#16:1'

However, if I run the exact same command(s) on a Windows OS I get the following error:

    Cannot find a command executor for the command request: sql.DELETE VERTEX Team WHERE @rid=16:1

All the other SQL queries seem to work on all the OS.

**Comment by lvca** [comment]
Seems you didn't include the `orientdb-graphdb.jar`.

**Comment by tarkal** [comment]
Nope I have it:

    <dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-graphdb</artifactId>
			<version>${orientdb-version}</version>

            <exclusions>
                <exclusion>
                    <groupId>commons-beanutils</groupId>
                    <artifactId>commons-beanutils-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-collections</groupId>
                    <artifactId>commons-collections</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>stax</groupId>
                    <artifactId>stax-api</artifactId>
                </exclusion>
            </exclusions>
    </dependency>

I have some exclusions as those dependencies are already declared in my project.

**Comment by tarkal** [comment]
Actually I have noticed this behaviour for several more queries:

    "Cannot find a command executor for the command request: sql.CREATE EDGE hasRole FROM (SELECT FROM Person WHERE @rid='15:18') TO (SELECT FROM Role WHERE @rid='16:0')"

**Comment by tarkal** [comment]
Ok so after further investigation it does not have anything to do with the OS! In my `pom.xml` I declare the following:

    
    <dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orientdb-server</artifactId>
        <version>${orientdb-version}</version>
    </dependency>
    
    <dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orientdb-core</artifactId>
        <version>${orientdb-version}</version>
    </dependency>
    
    <dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orientdb-graphdb</artifactId>
        <version>${orientdb-version}</version>
    </dependency>
    
    <dependency>
        <groupId>com.tinkerpop.blueprints</groupId>
        <artifactId>blueprints-core</artifactId>
        <version>2.5.0</version>
    </dependency>
    
    <dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orientdb-client</artifactId>
        <version>${orientdb-version}</version>
    </dependency>
    ...
    <orientdb-version>2.1.3</orientdb-version>

When I run it from the IDE everything works great. However when I package up the project using `maven-shade-plugin` I start getting these `Cannot find a command executor for the command request:` errors but only for a subset of queries. My guess is that something is being stripped out by shade during packaging that is causing this. Any ideas what I would be looking for specifically that might be causing this?

**Comment by maggiolo00** [comment]
@tarkal 
is the tips i gave you here

http://stackoverflow.com/questions/33129291/orientdb-cannot-find-a-command-executor-for-the-command-request-error/33129566#33129566

solved the issue?

**Comment by tarkal** [comment]
@maggiolo00 Yes it did thanks. I specifically had to add:

```
<transformer
                                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/com.orientechnologies.orient.core.sql.functions.OSQLFunctionFactory</resource>
                                </transformer>
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/com.orientechnologies.orient.core.sql.OCommandExecutorSQLFactory</resource>
                                </transformer>
```

You can go ahead and close this issue. Thanks for your help.

**Comment by maggiolo00** [comment]
Cool @tarkal  :D
