### ISSUE TITLE
delete edge with subquery does not work nor gives exception

### ISSUE THREAD

**Issue by b4mse** [orientechnologies/orientdb#5108]
on GratefulDeadConcerts database, orientdb version 2.1.3

I've tried the following actions in sequence:

SELECT FROM #11:5
DELETE EDGE FROM (SELECT FROM #11:5)
SELECT FROM #11:5

none of them issued an error. 

first returned as expected, edge #11:5
second returned:
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "value": 0
        }
    ],
    "notification": "Query executed in 0.019 sec. Returned 1 record(s)"
}

the third returned again the edge #11:5 which to me looks like the second statement did not work as I would have expected since there was no error message that would have implied it is not supported.

Please let me know if there is something else I can do to help reproducing/understanding the issue.

by the way, works fine with DELETE VERTEX variant.

**Comment by luigidellaquila** [comment]
Hi @mcculls 

In REMOVE EDGE syntax, the FROM indicates the starting point vertex of the edge you are trying to delete, so for example the following is valid:

```sql
DELETE EDGE FROM (SELECT FROM #9:1) TO (SELECT FROM #9:2) 
```

To do what you are trying to do, the right syntax is

```sql
DELETE EDGE E where @rid in (SELECT FROM #11:5)
```

I guess some docs improvement is needed here http://orientdb.com/docs/last/SQL-Delete-Edge.html , I'm doing it right now

Thanks

Luigi
