### ISSUE TITLE
Error 500 trying to create Vertex using REST API

### ISSUE THREAD

**Issue by silverfox1948** [orientechnologies/orientdb#5109]
I'm trying to create a Vertex using the Rest API. I've been able to successfully use the Rest API to create a database, and to create classes (but without extending the "V" object). However, when I try to create a Vertex using the "command" POST, I always get an error 500.

From Fiddler, here is my POST data: POST http://dbserver:2480/command/G4JTest-8587569988225882445/sql HTTP/1.1 Accept-Encoding: gzip,deflate Authorization: Basic cm9vdDpkYktpbmc= Host: dbserver:2480 Content-Length: 105 Expect: 100-continue Connection: Keep-Alive

{"command": "create class :classname extends V", "parameters": { "classname": "TestCreateVertexVertex"} }

Here's my response: HTTP/1.1 500 Internal Server Error Cache-Control: no-cache, no-store, max-age=0, must-revalidate Pragma: no-cache Date: Sun Oct 11 17:01:44 PDT 2015 Content-Type: application/json; charset=utf-8 Server: OrientDB Server v.2.1.2 (build UNKNOWN@r; 2015-09-09 21:41:27+0000) Connection: Keep-Alive Content-Length: 349

{ "errors": [{ "code": 500, "reason": 500, "content": "com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.{\"command\": \"create class :classname extends V\", \"parameters\": { \"classname\": \"TestCreateVertexVertex\"} }" } ] }

Can someone please explain what I'm doing incorrectly?

**Comment by maggiolo00** [comment]
@silverfox1948 

parameters are allowed since 2.2
see here 
http://orientdb.com/docs/2.1/OrientDB-REST.html#command

**Comment by silverfox1948** [comment]
Thank you. I thought I had that version - just poor memory on my part. I see that 2.2 is alpha, so I'll re-do my command.
