### ISSUE TITLE
Using a Set in distributed mode causes a "Cannot Route Command" exception

### ISSUE THREAD

**Issue by SDIPro** [orientechnologies/orientdb#5110]
In distributed mode, executing a query using a set, such as this:

SELECT name, set(roles.name) AS roles FROM OUser where name = 'user'

Causes this error:
com.orientechnologies.orient.core.exception.OStorageException: Cannot route COMMAND operation to the distributed node  --> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

Possibly caused by OEmbeddedRidBag::doDeserialization, the rid being calculated in from OLinkSerializer.INSTANCE.deserialize (within ObinaryProtocol) calculates an invalid offset of -2.

**Comment by mriehl** [comment]
We're also seeing this issue... it's a big pain point because doing traversals on a huge graph kind of relies on being able to get rid of duplicates to avoid a combinatorial explosion
