### ISSUE TITLE
Automatic backup not working

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#5112]
I enabled automatic backup on Ubuntu 14.04. Set it to backup at 16:00:00, with a delay of 1h.

Stopped and restarted the server, but so far it doesn't seem to have worked.

What else is required to make automatic backup work?

TIA

**Comment by finid** [comment]
Sorry, this should be closed. Automatic backup does work.

The backup folder was created were I wasn't expecting it - in the `bin` directory.

**Comment by smolinari** [comment]
@lvca - I am a bit confused. According to the docs, there is a setting of `backup` for a target directory. 

http://orientdb.com/docs/2.0/orientdb.wiki/Automatic-Backup.html

Is the setting actually set default to `/bin`? If yes, the docs are wrong. Also, is that setting supposed to be a relative path or an absolute path?

Or @finid - did you change that setting to `/bin` and forgot about it? :wink: 

Scott

**Comment by finid** [comment]
No, did not change anything but the time to start the backup and the delay. 

Here's the relevant section of the config file. Everything here are defaults. Notice the value for **target.directory**:

```
<handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter value="false" name="enabled"/>
                <parameter value="4h" name="delay"/>
                <parameter value="23:00:00" name="firstTime"/>
                <parameter value="backup" name="target.directory"/>
                <parameter value="${DBNAME}-${DATE:yyyyMMddHHmmss}.zip" name="target.fileName"/>
                <parameter value="9" name="compressionLevel"/>
                <parameter value="1048576" name="bufferSize"/>
                <parameter value="" name="db.include"/>
                <parameter value="" name="db.exclude"/>
            </parameters>
        </handler>
```

**Comment by lvca** [comment]
@maggiolo00 did you already fix this issue where the firstTime was wrongly interpreted as `hh:mm:ss` instead of `HH:mm:ss`

**Comment by maggiolo00** [comment]
@lvca 
i did not work this issue. But seems that a recent pull request fix firstTime .
https://github.com/orientechnologies/orientdb/pull/5042

**Comment by smolinari** [comment]
Just for my own sanity. Where does the backup end up getting stored? In the `/bin` directory or in the `/bin/backup` directory or in the `/backup` directory?

Scott

**Comment by lvca** [comment]
@smolinari the directory is relative to where OrientDB starts. I suggest to always use an absolute path to avoid such problems.

**Comment by smolinari** [comment]
So, /bin/backup?

Scott
