### ISSUE TITLE
Improve performance of parallel query

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5114]
In v2.2, queries are parallel, but having just 1 thread that computes the projections and fill the result could be the bottleneck when I/O is fast (like warm cache).

Move computation of projection in the parallel threads, paying attention to the synchronization of results against common structures.

**Comment by nanacoSai** [comment]
Hello, I think I met the same problem with Graph API at version 2.2.32( queries are parallel, but having just 1 thread that computes the projections and fill the result).  What can I do for it ?
