### ISSUE TITLE
2.1.2 - NullPointerException at com.tinkerpop.blueprints.impls.orient.OrientEdge.remove

### ISSUE THREAD

**Issue by motih78** [orientechnologies/orientdb#5122]
Hi,

Sometimes when trying to delete an edge via the java API, we get the following exception:

java.lang.NullPointerException: null
at com.tinkerpop.blueprints.impls.orient.OrientEdge.remove(OrientEdge.java:406) ~[com.orientechnologies.orientdb-graphdb-2.1.2.jar:2.1.2]

There is no problem deleting those edges via the web UI.

The use case is as follows:
Assume we have 2 vertices connected with an edge of class edgeCls
Within the same transaction we do the following:

v1.getVertices(Direction.OUT, edgeCls).asScala.foreach(_.remove)
v1.getEdges(Direction.OUT, edgeCls).asScala.foreach(_.remove)
v1.remove()

The removal of the edge after removing one of the vertices it is connecting seems to sometimes throw the above exception.

Is deletion of the edge after deleting one of the vertices it is connecting required at all?
Even if not, there seems to be some issue when trying to delete an edge which should be deleted, since sometimes it seems some leftovers are there since we get to the edge.remove() method.
I don't know if it is relevant, but we have the 'distributed' flag turned on and it happens in both single machine cluster or 3 machines cluster.

Thanks,
Moti.

**Comment by luigidellaquila** [comment]
Hi @motih78 

Just a couple of considerations and requests:
1) are you working in tx mode (you should)?
2) when you delete a vertex, all the connected edges are automatically removed, so removing them manually is absolutely not needed
3) any chance to have a full stack trace?
4) can you reproduce the same problem in non-distributed mode? (just to understand if it's a problem with distributed layer or with TinkerPop API implementation) 

Thanks

Luigi

**Comment by motih78** [comment]
Hi @luigidellaquila 

1. Yes - we work in tx mode
2. If that is indeed the case, then edge.remove() should not be invoked after deleting a vertex (but sometimes it is invoked - maybe this is why the NullPointerException is thrown - since there is no edge to remove)
3. I'll try to provide a full stacktrace
4. I can try - the issue is intermittent, so it might be problematic to reproduce in a timely manner. but since this happens before we commit the transaction - i would guess the problem is with the TinkerPop API implementation.

Thanks,
Moti.

**Comment by lvca** [comment]
Seems the edge has broken links to vertices. Are you sharing the same Graph or Database instance across threads? However I introduced an additional check to avoid NPE.
