### ISSUE TITLE
java.lang.NoSuchMethodError: com.sun.jna.Platform.isAIX()Z

### ISSUE THREAD

**Issue by campa** [orientechnologies/orientdb#5124]
Hi I'm using

* 2.1.4 orientdb
*  with JDK 1.7 Oracle 
* linux

and I'm having this blocking error:

    java.lang.NoSuchMethodError: com.sun.jna.Platform.isAIX()Z
    at com.orientechnologies.nio.OCLibraryFactory.<clinit>(OCLibraryFactory.java:35) ~[orientdb-core-2.1.4.jar:2.1.4]

Can anyone can suggest me what to do ? Or any workaround ?

**Comment by laa** [comment]
Do you use embedded version ?

чт, 15 Окт 2015, 15:34, Stefano E. Campanini <notifications@github.com>:

**Comment by campa** [comment]
On Sun, 18 Oct 2015 7:17 am Andrey Lomakin <notifications@
<notifications@github.com>github.com <notifications@github.com>> wrote:


>
> Do you use embedded version ?

Yes, I do.


>
> чт, 15 Окт 2015, 15:34, Stefano E. Campanini <notifications@github.com>:
>
> > Hi I'm using
> >
> > - 2.14 orientdb
> > - with JDK 1.7 Oracle
> > - linux
> >
> > and I'm having this blocking error:
> >
> > java.lang.NoSuchMethodError: com.sun.jna.Platform.isAIX()Z
> > at
com.orientechnologies.nio.OCLibraryFactory.<clinit>(OCLibraryFactory.java:35)
~[orientdb-core-2.1.4.jar:2.1.4]
> >
> > Can anyone can suggest me what to do ? Or any workaround ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https <https://github.com/orientechnologies/orientdb/issues/5124>://
<https://github.com/orientechnologies/orientdb/issues/5124>github.com
<https://github.com/orientechnologies/orientdb/issues/5124>/
<https://github.com/orientechnologies/orientdb/issues/5124>orientechnologies
<https://github.com/orientechnologies/orientdb/issues/5124>/
<https://github.com/orientechnologies/orientdb/issues/5124>orientdb
<https://github.com/orientechnologies/orientdb/issues/5124>/
<https://github.com/orientechnologies/orientdb/issues/5124>issues
<https://github.com/orientechnologies/orientdb/issues/5124>/5124
<https://github.com/orientechnologies/orientdb/issues/5124>>.
> >
>
> —
> Reply to this email directly or view
<https://github.com/orientechnologies/orientdb/issues/5124#issuecomment-148978702>
it on
<https://github.com/orientechnologies/orientdb/issues/5124#issuecomment-148978702>
GitHub
<https://github.com/orientechnologies/orientdb/issues/5124#issuecomment-148978702>.<img
src="
https://ci5.googleusercontent.com/proxy/Nf_2P6KTvzjA9CEEYt_tXe61ZzoJ25HNeBi4HpJjhYLLHgeKQ_RtEfAtyuIIR-dlNVp5F-SCOC-vEBWpCz0gClGwpL_rIMbkKLWwNdhw9-bRCPwTGW6o2R3kVUydiDnk4Te4cN3P_dA_XeWi7LoxjQn02yC6yQ=s0-d-e1-ft#https://github.com/notifications/beacon/ACrHPfYnQfo1Seqq66MOvHoPQHh0BcoJks5o8yFxgaJpZM4GPavi.gif
">

**Comment by laa** [comment]
Please use setting -Djna.nosys=true during next jvm start. You have outdated version of JNA in you linux distribution.

**Comment by campa** [comment]
I tried:

* I tried it ( -Djna.nosys=true ) before asking, but the error was not resolved. 
* I also tried result, also adding a JNA recent version, as an explicit dependency into my war
* I also tried  adding -Djna.disable.system.library=true and false 

Because of the early delivery, today we changed our persistence layer. 
So you can keep this issue closed.

**Comment by christtrc** [comment]
Use jna and jna-platform from https://github.com/java-native-access/jna with version 4.2.1. I can run orientdb in osgi environment.
