### ISSUE TITLE
eval() multiplication of an integer with a float behaves strangly

### ISSUE THREAD

**Issue by michael-go** [orientechnologies/orientdb#5125]
easy to reproduce (I tested it with 2.1.3):

```sql
SELECT eval("1 * 0.5") FROM V LIMIT 1
```
==> 0.5 as expected

however 
```sql
SELECT eval("1 * 0.4") FROM V LIMIT 1
```
===> 0 !

0 is given also when multiplying with practically any other float except 0.5.
1 is given when multiplying with any  1< float < 2 except 1.5 which gives correct result

the issue is not so serious as it works correctly when the integer is converted to a float (i.e. 1.0)

**Comment by luigidellaquila** [comment]
Hi @michael-go 

I just tried it in 2.1.3 final and it seems to work correctly. Could you please double-check that you are not adding blank spaces before or after the dot, eg.

```

**Comment by luigidellaquila** [comment]
btw, I tried it in Studio, are you doing the same?

**Comment by luigidellaquila** [comment]
Sorry, my fault, I had two Studio open and I tried it on 2.0 by mistake.
I could reproduce this issue, I'm on it

Thanks

Luigi

**Comment by michael-go** [comment]
Thanks for the quick response :stuck_out_tongue: 

it happens also on 2.1.4

**Comment by luigidellaquila** [comment]
Fixed in latest stable, closing

Thanks

Luigi
