### ISSUE TITLE
traverse context seams not OK

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5128]
<pre>traverse  f  from #39:0  while $current.c > 0
0 item(s) found. Traverse executed in 0.004 sec(s).

traverse  f  from #39:0  while c > 0         

----+-----+------+----+-----+-----
#   |@RID |@CLASS|c   |f | 
----+-----+------+----+-----+-----
0   |#39:0|p     |1   |#39:1 
1   |#39:1|p     |2   |#39:2
2   |#39:2|p     |3   |#39:3
3   |#39:3|p     |4   |null
----+-----+------+----+-----+-----

4 item(s) found. Traverse executed in 0.003 sec(s)

 select traversedElement(-1) from ( traverse f from #39:0 ) 

----+------+----------------
#   |@CLASS|traversedElement
----+------+----------------
0   |null  |#39:1           
1   |null  |#39:2           
2   |null  |#39:3           
3   |null  |#39:3           
----+------+----------------

</pre>

Why $current seams equals to null (maybe documentation is not updated)? Why traversedElement(-1) returns 4 elements , not one?

**Comment by lvca** [comment]
I think traverse doesn't define `$current` but only select does it. What's your goal?

**Comment by publicocean0** [comment]
i have a class p where f is the pointer to a another p document. 

I have to find the last pointed document p traversing from a initial document X. the last pointed document can have depth very higher (also a many thousands ). For this reason i m interested just in the last element not all the list
