### ISSUE TITLE
Upgrade Script

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#5130]
Any plans to provide an upgrade script to ease the process of upgrading an installation? I'm thinking about something similar to the backup script that ships with current releases.

Along the same lines, what is the recommended upgrade method now?

TIA,

**Comment by StarpTech** [comment]
https://github.com/orientechnologies/orientdb/issues/4422

**Comment by finid** [comment]
Thanks. We really do need a proper upgrade script.
