### ISSUE TITLE
Escaping backslash in embedded object causes it to be doubled 

### ISSUE THREAD

**Issue by Ziink** [orientechnologies/orientdb#5132]
orientdb-community-2.1.4 (and earlier too)

```sql
UPDATE V SET key = "test", value = {"f12":"test\\"} UPSERT WHERE key = "test"
```

This results in f12 being : test\\\\
The expected value is : test\

The following works fine though

```sql
update V set value.f12 = 'asdf\\' WHERE key = "test"
```

May be related to [Issue 4996](https://github.com/orientechnologies/orientdb/issues/4996)

**Comment by joaobarcia** [comment]
+1

**Comment by luigidellaquila** [comment]
Hi guys, 

It's fixed in 2.1.x and develop branches.
I'm closing this, please reopen in case of problems

thanks

Luigi

**Comment by joaobarcia** [comment]
Thanks!

**Comment by joaobarcia** [comment]
Hi Luigi,

How safe is it to use the develop branch on a prototype? Is there the possibility of severe blocking issues?

**Comment by luigidellaquila** [comment]
Hi @joaobarcia

2.1.x snapshots are stable enough for pre-production and of course for testing.
For production I'd wait the official hotfix release

Luigi

**Comment by lvca** [comment]
@joaobarcia For a prototype using the "develop" brings many advantages. In this case 2.2 is much faster than 2.1.x.

**Comment by joaobarcia** [comment]
Hi @luigidellaquila and @lvca . If I'm not mistaken, it seems the most recent snapshots are prior to the bug fix. We will wait until the next snapshots. Thanks
