### ISSUE TITLE
Clean all ambiguities in JSON and SQL parsers

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5134]
Today we have some ambiguities in JSON and SQL parsers where they auto convert things with different behavior that could cause headache to the end-users. For this reason we'd like to clean all this stuff in just one release: 3.0.

In order to stay compatible with old releases, we'll use what MySQL did: [the mysql modes](https://dev.mysql.com/doc/refman/5.0/en/sql-mode.html), barely a flag to decide which strictness to use. Below there is the list of single issues to fix:
- [ ] 
- [ ]

**Comment by giastfader** [comment]
@lvca there is a problem with the list of issues. GitHub does not show them

**Comment by lvca** [comment]
Not relevant anymore, closing it.
