### ISSUE TITLE
OrientDB Local cache makes GremlinPipeline returning stale data

### ISSUE THREAD

**Issue by Daniel-Valliere** [orientechnologies/orientdb#5135]
The OrientDB local cache cause problem with the validity of my gremlinpipeline execution.

Each Thread A and B uses their our instance of graph.

Thread A: Run a gremlinpipeline to get a number of vectors.
Thread B: Change the DB to add or delete some of the nodes traversed in the gremlinpipeline thus changing the number of vectors the gremlinpipeline should return.
Thread A: Rerun the gremlinpipeline and the number of vectors is identical (doesn't take into account the changes made by thread B)

I'm sure this is a well known pattern. The issues appears to be because the local cache of the graph used by thread A is not updated by the work done by thread B’s graph.
The only reasonable work around I have found is to clear the local cache on thread A before the gremlinpipeline execution (graph.getRawGraph().getLocalCache().clear();).

Is that the only thing we can do? Is there any negative impact on the rest of the application?

Thanks,
Daniel

**Comment by luigidellaquila** [comment]
Hi @Daniel-Valliere 

gremlinpipleline has a very aggressive caching policy, this leads to this problem. Using cache clean does not have any negative impact on the application, you can use it safely

Thanks

Luigi

**Comment by luigidellaquila** [comment]
I'm closing this, please reopen if you need further details.

Thanks

Luigi
