### ISSUE TITLE
possible enhancements for next releases 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5136]
<B>Partial match search enhancement</B>
Reference : http://orientdb.com/docs/2.1/Indexes.html

composite keys is a+b 
now it is possible to do :

<pre>
 SELECT FROM INDEX:books WHERE key = ['key1','key2']
SELECT FROM INDEX:books WHERE key = 'key1'
</pre>

it advice to add ( if it is possible , i didnt see the implementation)

<pre>
SELECT FROM INDEX:books WHERE key.a = 'key1' 
SELECT FROM INDEX:books WHERE key.b = 'key2'
</pre>

This evoid to add a second index it you want search for b and not for a.... :) 

 <B>DELETE ON CASCADE</B>

<pre>
delete from #10:21  cascade ['p1','p2']
</pre>

it permits to remove the node and the subnodes in properties p1 and p2

 <B>COPY</B>

<pre>
copy from #10:21 to <class>  cascade ['p1','p2']
</pre> 

 it permits to copy the node createning a new one makiing the same recursively for sub nodes for property p1 and p2, for the remaining is copying just the link

<B>ON FETCH </B>

<pre>
select .... on fetch ( delete|insert|..... commands)
</pre>

it permits to execute a nested command (removal , updating , insertion...) for every row found in the select. it permits to add a feature executing massive commands using few server resources on huge results . It adds indirectly powerfull also to batch script (just way to use use transaction with sql commands ) because you can filter modifications in a transaction permitting to change the effects based on server results and not only based non client parameters.

**Comment by publicocean0** [comment]
UNWIND command 
add @index internal parameter so you can use it for access directly to a long list by index in following  query 

before retrieve the index of the list .... then in a second query (second time ) you can access to element directly using select list[index] from ....

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

Thanks, I'll take them into consideration. Just two notes:

Partial match: current index implementation only allows partial match on index suffix (eg. first indexed attributes), so this feature will require an important refactoring of indexes structure

UNWIND: good point, any suggestion on how to manage indexes for multiple unwinds?

Thanks

Luigi

**Comment by publicocean0** [comment]
hi , 
considering a document with a billion of elements in a embedded list (rid pointers or strings or ...), and you want i-th element
in client side , if you execute select list[i] from .... you evoid in client side to load a huge list in memory. It is already possible now this query (i used a similar one for retrieving a file with many many chunks...)
in server side as you observed there would be a problem anyway because the embedded list, i image, is loaded entirely now : I didnt see the orientdb code but i think you load all the list in memory anyway ... before to return the element i-th. 
There are 2 improvements: 
1) you can introduce a header in the data blob: for embedded list the  structure could be so 
 - uint32 list size
- a internal list of uint32 where i-th element is the offset in the blob data for i-th element
In this way if you want access to element 10 , in 0(1) time, O(1) space you can execute 
  - read uint32 SIZE at 0th and position P at position 4x(1+10) 
 - read element at position  4X (1+SIZE)+P
2)        do not use List or Collection for reading the entire list but iterator,in this way also if you want   return a huge list you load in memory just a element for every step.
3) i described a list example, but in general you can use a similar structure also Map. 
in this case header could be 
   - uint32 map size
   - list of properties [ string, offset ]
for searching offset of property X, and retrieving  the element  there is a O(n) time , O(1) space (you could to reach to O(log (n))) time  if you save the properties as suffix tree for example).
For seeing as handling complex object (recursive structures...) you can observe my short library(https://github.com/publicocean0/bon) that i used in a project even if it is a different scope:  
it used similar concepts in nested way for any objecct type. 

4) I love orientdb and i used often it in the last years. Anyway i think there is a weak point in the server that for my opinion could be improved in the next releases: the client communication and storage use bytearray and not binarystream. Introducing it you could handle better memory space used in the queries either for server either for client.

**Comment by publicocean0** [comment]
<b>TRAVERSE WHERE ..... </b>

the trial response is "You can embed in a select for a where condition". Yes, but if the depth is very high? 
Using a select i will receive a list of a million of elements and inside i will filter consuming a huge amount of memory ,  instead using a where inside traverse ... i will filter the right records not using huge memory also in the case you have a high deph

**Comment by publicocean0** [comment]
<b>Index on sub node</b>
You have a class City(name,zipcode) and a class Zipcode(code,region) 
city.zipcode is a link to ZipCode instance. 

oClass.createIndex("City.zipcode",......, new String[] { "zipcode.code"});

the index map directly all the city having a subnode with zipcode.code = X

**Comment by publicocean0** [comment]
LUCENE INDEX ON EMBEDDED MAP
You have a class City(name,attributes)
where attributes is embedded map

oClass.createIndex("City.C",......, new String[] { "name","attributes"});

select from index:City.C where key LUCENE "name:Rome AND attribute.value:[3.0 TO * ]"

pratically if i find in the index schema a map .... when i insert the document in lucene index , orientdb added all the properties generated linearizing the map.
example 
{ car:{name:'Twingo'} ,year :2000} is converted to 
car.name
car.year

**Comment by publicocean0** [comment]
<b>Functional Lucene schema</b> 
schema of lucene cointains now myltiple fields : it is a array of strings.
in this strings are mapped the fieldname. 
The proposal is to consider that string a content of "eval" function.
in this way is possible to map in a key non only a fieldname , but also nested fieldnames or a modified fieldname. It could create a projection from a key to a changeable dataset

**Comment by publicocean0** [comment]
**A way for making sql commands transactional**
ipothesis 
1) db.begin
2) many classical crud instructions (now they are transactional in client)
3) when you add a command execution 
   a) you force client to send the server a special command for asking to open a virtual transaction mapped to that client. For semplicity i named that transaction X (it could be a number).
  b) you force client to send all the instrunctions  to server for executing them inside virtual transaction X 
 c) you execute command inside transaction X in the server.
d) return "continue/rollback" to client for restoring that savepoint. 
e) if there is a following roolback in the client , it send roolback transaction X to server. 


In this way when in the transaction there are no command instruction , all works as before. in the opposite case ... you add a more complex management.

**Comment by publicocean0** [comment]
Autosharding lucene indexes

A lot of products make already  it.

**Comment by publicocean0** [comment]
A problem difficult to solve with orientdb.

I want save file (also big file) in orientdb using chunks. The file can be seekable (so i can search the file offset of chunks )
for making it i might index chunks ( startOffset, endOffset). But here there are a lot of problems:

1) automatic index on a OrecordBytes now is not possible
2) even if 1) would be possible , how can make it transactional in client? maybe for solving it i might have also "A way for making sql commands transactional" before post.

**Comment by publicocean0** [comment]
**OStreamRecord** 

A new version of OByteRecord , passing data not using a byte array but using a Stream. This version is more scalable permitting to have thousands of parallel record read per seconds.In this way you can create big chunks but using few memory resources.

**Comment by publicocean0** [comment]
**autosharding/replication ORecordBytes cluster or hidden class for bytes?**

**Comment by publicocean0** [comment]
**transactional incremental operation.**

if you have a huge linked list ... for adding a element you have to load all the list in a transaction , and element and then commit. 

you can just update #10:10 add list = <element> without add the entire list. Anyway it can be executed just in command not transactional for now. Adding a specific command in client it would be skip this problem.

**Comment by publicocean0** [comment]
**Internal Cursor instead result table** 

I dont know exactly how works internals in orientdb, but i supposed (analizying in the past perfomance for memory space/velocity )  the result of a select is saved as table also when is passed to the parent select. 

It sucks a lot of memory and it is not very scalable.

in a future engine it is possible to model all as a Cursor keeping the state of search. 
When you pass a result select to a parent select you pass cursor nor a table. So in memory the space used is O(1) not O(n).
Eventually for get faster the access it is possible to wrap cursor using a cached cursor that use a fixed space in memory of the last X scanned row. 
In addition also when it is passed the result to client by socket... using cursor to pass a element for every step. For making it socket must handle stream, not a unique packet. 
Every sql internal operator receives as parameters just cursors , not table or list.

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

This is exactly what we are doing for 3.0 ;-)
Anyway, some operations still require memory to execute, eg. an ORDER BY is executed in memory. We are developing it in a way that can be enhanced with disk-backed structures, but I'm not 100% sure it will be available in the first GA

Thanks

Luigi

**Comment by publicocean0** [comment]
wondefull. You will solve one of 2 more important weak points in orientdb. It will emprove a lot the architecture. Considering anyway for my opinion to order in memory is not a good idea , because for definition a database has a space very bigger than a memory space. 
For my opinion you might use a index as lucene do for sorting (a sort of linked list) in every ordinable field. 
The second weak point is indexes. 
in a old test in orientdb , if you make a simple query also with fixed values in a huge class ... it compares every rows. It get pratically impossible to execute if the class is bigger than 100.000-1000.000 rows because the response time overcomes the maximum time for a response in the pragmatic use. For this reason or you offer a very good indexer (with comparators... as lucene) to use for huge classes or you introduce internal index making it in the cursor. 
If you for example test a similar query with 1000.0000 rows in postgress you receive response in fast time (in this time it is impossible to compare 1000.000 rows step by step ... so i m deducting it use a internal index for comparable colums)

**Comment by publicocean0** [comment]
There is a good book explaining very well topics above.
"Costruire sistemi di basi di dati" di antonio albano. Addison wesley. You can find algorithms for sorting and searching for attributes with variable length
