### ISSUE TITLE
includeSchema flag does not override excludeAll when exporting database

### ISSUE THREAD

**Issue by khogeland** [orientechnologies/orientdb#5138]
As per [the documentation](http://orientdb.com/docs/2.1/Console-Command-Export.html), `-includeSchema=true` should override `-excludeAll`

```
orientdb {db=test_export}> export database schema_test -excludeAll -includeSchema=true
Exporting current database to: database schema_test -excludeAll -includeSchema=true in GZipped JSON format ...

Started export of database 'test_export' to schema_test.json.gz...
Exporting schema...OK (14 classes)

Database export completed in 1ms
```
```
$ gzip -dc schema_test.json.gz | jq .
{
  "schema": {
    "classes": [],
    "version": 428
  }
}
```

Ran into this problem when trying to export only schema and functions, i.e. 
`export database foo -excludeAll -includeCluster=ofunction -includeClass=ofunction -includeSchema=true`

**Comment by tglman** [comment]
fixed in 2.1 and develop, closing
