### ISSUE TITLE
Question :- Get edges attributes from any vertex and map result 1-to-1 not duplicates. 

### ISSUE THREAD

**Issue by nomi-ramzan** [orientechnologies/orientdb#5140]
Hi !
I have this schema
```
vertexA <--- edgeC  --- vertexB 
```
Now i am starting from vertexA and i want to get count and some attributes of edgeC something like this.
```
SELECT in_edgeC.price AS price, in_edgeC.condition AS cond FROM [#30:136, #30:137]
 ```
Now i am getting two columns inside each column i have array of prices and conditions 
Now how can i map condition with price so that I can get which condition belongs to which price 

Here is my output 
![captur111e](https://cloud.githubusercontent.com/assets/7391350/10556551/f36489d6-7496-11e5-9521-ac62aa74c08d.PNG)

Even i tried UNWIND this function is creating duplication in my result.
```
I am using Orientjs client and right now i am running this query in orientDB studio
```

**Comment by luigidellaquila** [comment]
Hi @nomi-ramzan 

You can try this:

```sql
select x.price, x.condition from (
    SELECT in_edgeC as x FROM [#30:136, #30:137] unwind x
)
```

Please, post your questions on StackOverflow, with tag ```orient-db``` you will have more chances of a quick answer

Thanks

Luigi

**Comment by nomi-ramzan** [comment]
Hi @luigidellaquila Thank you for you answer. i tried your solution and I am getting this error 
``` java.lang.NullPointerException: Impossible to add a null identifiable in a ridbag ``` And next time i'll post my question on stackoverflow.

**Comment by luigidellaquila** [comment]
Hi @nomi-ramzan 

Can you provide a simple dataset (or a script to create it) to reproduce the problem? 
I think it's an easy fix

Thanks

Luigi
