### ISSUE TITLE
Default loglevels when downloading new distribution set to fine

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5141]
When downloading a new distribution the loglevels in the files orientdb-server-log.properties and orientdb-server-config.xml are set to fine.

IMHO they should be info.

**Comment by lsavio** [comment]
Thank you for reporting .. in case I still need to change the level can always act on the two files you mentioned and set different log levels (SEVERE (highest value), WARNING, INFO, CONFIG, FINE, FINER, FINEST ).

**Comment by tglman** [comment]
fixed will be out with the next hotfix, closing

**Comment by wouterv** [comment]
@tglman I found in orient-server.config.xml this line was also present:

        <entry value="fine" name="log.file.level"/>

Shouldn't that be changed as well?
