### ISSUE TITLE
sql group by drop duplicate keys.

### ISSUE THREAD

**Issue by nuwansa** [orientechnologies/orientdb#5144]
please see the following example. VERSION 2.1.4

        ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:test").create();
 
        // CREATE A NEW DOCUMENT AND FILL IT
        ODocument doc = new ODocument("Person");
        doc.field("name", "Luke");
        doc.field("surname", "Skywalker");
        doc.field("age", 10);
        doc.field("city", new ODocument("City").field("name", "Rome").field("country", "Italy"));

         // SAVE THE DOCUMENT
        doc.save();
        doc = new ODocument("Person");
        doc.field("surname", "Skywalker");
        doc.field("city", new ODocument("City").field("name", "Rome").field("country", "Italy"));
        doc.field("name", "Nuwan");
        doc.field("age", 20);
        doc.save();
        
         doc = new ODocument("Person");
        doc.field("surname", "Skywalker");
        doc.field("city", new ODocument("City").field("name", "Rome").field("country", "Italy"));
        doc.field("name", "Nuwan");
        doc.field("age", 21);
        doc.save();
        List<ODocument> persons  = db.query(new OSQLSynchQuery<ODocument>("select * from Person group by name"));
        for (ODocument p : persons) {
            System.out.println(p);
            
        }
        db.close();

im expecting 3 records here. but there's only  2 records. it seems group by drop the records with duplicate key. only last one in the result set if the records contain same value for the group by key.

**Comment by luigidellaquila** [comment]
Hi @nuwansa 

GROUP BY should be used together with aggregate operators (eg. sum() max() min()), so in your case the result is not predictable in general.
I see you closed this issue, did you solve your use case?

Thanks

Luigi

**Comment by nuwansa** [comment]
yes ,thanks  i have solved my issue.
