### ISSUE TITLE
Javascript In-Database Function Behavior Broken from 2.1.4-SNAPSHOT to 2.1.4.

### ISSUE THREAD

**Issue by sungchoiok** [orientechnologies/orientdb#5148]
I wrote some javascript database functions (the one that you create inside the Studio) in 2.1.4-SNAPSHOT. After upgrade to 2.1.4, the functions are all broken.

It basically boils down to this.

In the Snapshot, running:

    return {
      a: "a",
      b: "b"
    }
gives you back
`    [
        {
        "@type": "d",
        "@version": 0,
        "a": "a",
        "b": "b"
        }
    ]`

whereas in 2.1.4, running

    return {
      a: "a",
      b: "b"
    }

gives you
`[
"@type": "d",
"@version": 0,
"value": "[object Object]"
]`

which leads me to believe that some sort of serialization mechanism is not working properly.
This problem happens to all objects the function is attempting to `return`.

I do not remember what specific snapshot it was; I will find it if needed.

Thanks in advance.

**Comment by StarpTech** [comment]
Why closed?
