### ISSUE TITLE
Add commands to gather performance statistic of storage for designated session of queries

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5157]
It will be useful to diagnose root of performance problems if we will gather statistic from storage components for designated query session. Following format is proposed:

1.  PROFILE STORAGE ON 
2. query or set of queries
3. PROFILE STORAGE OFF

result of execution of last command should produce following information

1. Amount of disk cache hits.
2. Amount of pages accessed  during the session.
3. Average time of access of page which is placed on disk.

**Comment by laa** [comment]
Done, example of result is:
{
   "readSpeedFromCacheInMB":3921472,
   "readSpeedFromCacheInPages":61273,
   "readSpeedFromFileInPages":-1,
   "readSpeedFromFileInMegabytes":-64,
   "amountOfPagesReadFromCache":7,
    "writeSpeedInCacheInPages":93396,
    "writeSpeedInCacheInMB":5977344,
    "amountOfPagesWrittenToCache":5,
    "commitTimeAvg":15369,
    "cacheHits":55
}

**Comment by laa** [comment]
Assigned to @luigidellaquila

**Comment by luigidellaquila** [comment]
Added support for following statements in develop branch:

```
PROFILE STORAGE ON

PROFILE STORAGE OFF
```

Closing

**Comment by smolinari** [comment]
If this is a done deal, could it possibly be added to the 2.2 release?

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

it's in develop branch, so it will be released with 2.2 GA

Thanks

Luigi

**Comment by smolinari** [comment]
Cool! Just need to change the milestone on this issue then. :smile: 

Scott

**Comment by luigidellaquila** [comment]
ah, yes, right! Done :-)

Thanks

Luigi
