### ISSUE TITLE
SELECT in.size() FROM V displays nothing in Studio

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#5171]
Hi,
I would like to display the number of in/out edges using a query in Studio, and eventually sort by the number of edges. The documentation is not useful regarding this use case and, after googling a little bit, I simply tried "SELECT in.size() FROM V". However, there is no results returned. As you can see on the following screenshot, Studio says that there is 20 results but nothing is displayed.

![capture d ecran 2015-10-20 a 16 13 12](https://cloud.githubusercontent.com/assets/12053709/10609868/d6ee8962-7745-11e5-99ab-8818435e8d93.png)

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 

The right syntax is following:

```sql
select out().size() from V
```

you can also ask for additional info, eg.

```sql
select *, out().size() as numOfEdges from V order by numOfEdges DESC
```

Please, use StackOverflow for this kind of questions, you will have more chances to have a quick answer

Thanks

Luigi

**Comment by benjaminbillet** [comment]
Hi @luigidellaquila,
Thanks for your response. Actually, the request I tried was found on stackoverflow after googling my problem.
Anyway, the feedback given by Studio is an actual issue, according to the screenshot. If my request was invalid, I would have expected Studio to display an explicit error message or, at least, a syntax error.

**Comment by benjaminbillet** [comment]
Hi again,

I tried the request you gave me, and apparently there is not enough heap space to compute it (I use the default configuration for OrientDB 2.1.2). This is strange, because I can simply implement the request using Java code, without any memory problem, by simply browsing the set of nodes and updating a list of the k vertices that have the highest number of edges).

Finding the TOP-k vertices by number of edges shouldn't overload the server, especially knowing that I "only" have 123245 vertices and 191451 edges. Do you think this behavior is normal, or should I create a new ticket for this specific performance issue?

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 

the query with out.size() is correct, in the sense that in a schemaless database you could have an attribute called "out", and the fact that it does not exist in your vertices just returns null, so the size evaluates to null.

ORDER BY is a memory bound operation, this is why you are having this problem. 
In OrientDB 2.1.4 you will find an optimization that avoids this problem, but you have to add a LIMIT clause to your query, eg.

select *, out().size() as numOfEdges from V order by numOfEdges DESC LIMIT 10

Thanks

Luigi

**Comment by benjaminbillet** [comment]
Okay, I will try 2.1.4. Thanks.
