### ISSUE TITLE
Allow field names for manual index

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5185]
_From @Ziink on September 24, 2015 16:26_

Enhancement request.

If we can label the fields making up the key in a manual lucene index, it will make the search capability more versatile.

See [Issue 27](https://github.com/orientechnologies/orientdb-lucene/issues/27)

_Copied from original issue: orientechnologies/orientdb-lucene#72_

**Comment by robfrank** [comment]
Could you elaborate more your request? Maybe writing down  a pseudo-SQL or Java statement and expected results. Thanks

**Comment by Ziink** [comment]
Suggested use from @wouterv initial issue

```sql
create index index_name ('id','name') FULLTEXT ENGINE LUCENE STRING, STRING
```
Then be able to insert like
```
insert into index:index_name (id, name, rid) values (1, 'jeff', #45:0)
insert into index:index_name (id, name, rid) values (1, 'Luca', #45:0)
insert into index:index_name (id, name, rid) values (2, 'Luca', #45:1)
```
and then query stuff like
```
select * from index:index_name where [id, name] LUCENE "(id:1 OR name:Luca)"
```
