### ISSUE TITLE
Diverse Lucene options

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5186]
_From @smolinari on September 24, 2015 15:29_

I am throwing the rest into this one issue as I feel they are a bit more exotic. We can always pull then into their own issues later, should there be more interest. I believe a couple were already suggested too.
- fielded searching (e.g. title, author, contents)
- flexible faceting, highlighting, joins and result grouping
- sorting by any field
- allow simultaneous update and searching
- fast, memory-efficient and typo-tolerant suggesters

Scott

_Copied from original issue: orientechnologies/orientdb-lucene#71_

**Comment by robfrank** [comment]
- -fielded searching (e.g. title, author, contents)-: done
 - flexible faceting: thinking about it, maybe group by is enough? 
 - -highlighting-: done 
 - joins and result grouping: use SQL on structured fields
 - sorting by any field 
 - allow simultaneous update and searching: inserting and searching inside a transaction is in place
 - fast, memory-efficient and typo-tolerant suggesters: duplicated: https://github.com/orientechnologies/orientdb/issues/6591

**Comment by smolinari** [comment]
Thanks Rob! 

ODB still needs the indexing on non-schema data or allow schema detection in the background, so it seems like the system is no-sql. 😄 ODB cannot be considered a No-SQL database, if any non-schema data cannot be properly searched/ found quickly. 

Scott

**Comment by robfrank** [comment]
Actually, the indexing architecture relies on the schema.
About Fulltext/lucene, that is my field, indexes need the schema to handle different types in the proper way: an integer or a date need to be indexed in a special way to enable range queries. Even a simple text field needs attention: if the content is Chinese, you can't index it with a standard analyzer. Well, you can, but for sure it will be hard to find something.
So, sincerely, I can't think about a lucene index wihtout a schema.

**Comment by smolinari** [comment]
Yes, and why I suggested in other places to have the schema detected in the background. The schema types can be inferred for sure, at least for basic types, like integer, string and real numbers. Once the inferred type is given, the data can be indexed. This allows insertion of data into ODB without defining schema first too. This is what MongoDB allows and why they consider themselves No-SQL and can. 

Until that happens, ODB is NOT a No-SQL solution.

Scott
