### ISSUE TITLE
Allow users to configure different analyzer for query and indexing

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5190]
_From @robfrank on September 23, 2015 16:3_

Improve index definition allowing configuration of different analyzer for query and indexing:

```sql
CREATE INDEX City.name ON City (name) FULLTEXT ENGINE LUCENE METADATA
{"query_analyzer":"org.apache.lucene.analysis.en.EnglishAnalyzer",
"index_analyzer": ""org.apache.lucene.analysis.stantard.StandardAnalyzer"
}
```

_Copied from original issue: orientechnologies/orientdb-lucene#66_

**Comment by martingg88** [comment]
+1

**Comment by lvca** [comment]
@robfrank what's the status of this issue?

**Comment by robfrank** [comment]
sorry for late response, I'm working on it.

**Comment by robfrank** [comment]
issue implemented, docs ongoing

**Comment by martingg88** [comment]
for what scenario that we need this different configuration for index and query? can we have some examples?

**Comment by robfrank** [comment]
It is very common on search to have different level of analysis on documents and queries. 
Documents are larger than query, so a more deep analysis could be done. A query is usually composed of some words.

**Comment by martingg88** [comment]
can you give one simple example to support that fact and that will make me more understand how it work. thanks.
