### ISSUE TITLE
Support for Faceted Search 

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5200]
_From @maggiolo00 on January 9, 2015 18:19_

_Copied from original issue: orientechnologies/orientdb-lucene#38_

**Comment by robfrank** [comment]
_From @JeremyRylan on July 22, 2015 1:22_

Thank you very much for working on this! Are there any updates on when we can expect to use faceted search?

**Comment by rrmerugu** [comment]
what is the status of this ?

**Comment by rrmerugu** [comment]
According to the roadmap, https://orientdb.com/docs/last/Roadmap.html it appears that there is progress on this. But I'm not able to find documentation on how to implement faceted search ?

**Comment by rrmerugu** [comment]
@lvca  any update on this ?

**Comment by luigidellaquila** [comment]
Hi @rrmerugu 

I'm afraid it won't be available in the very short term (there are other priorities), but it's still in our intentions to implement it eventually

Thanks

Luigi

**Comment by azaroth42** [comment]
Pinging this thread. Lack of facets would be a showstopper for us, for sure.

**Comment by azaroth42** [comment]
Closed because it was done, or closed won't fix?
