### ISSUE TITLE
indexes characterization

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5204]
In relation to what you are indexing, you may want a well defined environment:

- dictionaries / spellcheckers
- analyzers
- characters set

**analyzers**

I'm working on this. So a possible json format for index metadata could be (for analysis configuration):
```json
{
"analyzer": "org.apache.lucene.analysis.en.EnglishAnalyzer",
  "index_analyzer": "org.apache.lucene.analysis.en.EnglishAnalyzer",
  "query_analyzer": "org.apache.lucene.analysis.standard.StandardAnalyzer",
  "name_index_analyzer": "org.apache.lucene.analysis.standard.StandardAnalyzer",
  "name_query_analyzer": "org.apache.lucene.analysis.core.KeywordAnalyzer",
  "description_index_analyzer": {
    "class": "org.apache.lucene.analysis.standard.StandardAnalyzer",
    "stopwords": [      "the",  "a", "at"]
  }
}
```

where 
* **analyzer** is the default analyzer.
* **index_analyzer** overrides the default for indexing
* **query_analyzer** overrides the default for query (query terms will be analyzerd with this analyzer)
* **name_index_analyzer** and **name_query_analyzer** override defaults for the field **name**
* **description_index_analyzer** overrides the default index analyzer for field  description providing a different set of stowords

An alternative could be: 
```json
{
  "analyzer": "org.apache.lucene.analysis.en.EnglishAnalyzer",
  "index_analyzer": {
    class: "org.apache.lucene.analysis.en.EnglishAnalyzer"
  }
  "query_analyzer": {
    class: "org.apache.lucene.analysis.standard.StandardAnalyzer"
  }
  "description_index_analyzer": {
    "class": "org.apache.lucene.analysis.standard.StandardAnalyzer",
    "stopwords": [
      "the",
      "a",
      "at"
    ]
  }
}
```

**Comment by robfrank** [comment]
I'm working on this. So a possible json format for index metadata could be (for analysis configuration):
```json
{
"analyzer": "org.apache.lucene.analysis.en.EnglishAnalyzer",
  "index_analyzer": "org.apache.lucene.analysis.en.EnglishAnalyzer",
  "query_analyzer": "org.apache.lucene.analysis.standard.StandardAnalyzer",
  "name_index_analyzer": "org.apache.lucene.analysis.standard.StandardAnalyzer",
  "name_query_analyzer": "org.apache.lucene.analysis.core.KeywordAnalyzer",
  "description_index_analyzer": {
    "class": "org.apache.lucene.analysis.standard.StandardAnalyzer",
    "stopwords": [      "the",  "a", "at"]
  }
}
```

where 
* **analyzer** is the default analyzer.
* **index_analyzer** overrides the default for indexing
* **query_analyzer** overrides the default for query (query terms will be analyzerd with this analyzer)
* **name_index_analyzer** and **name_query_analyzer** override defaults for the field **name**
* **description_index_analyzer** overrides the default index analyzer for field  description providing a different set of stowords

An alternative could be: 
```json
{
  "analyzer": "org.apache.lucene.analysis.en.EnglishAnalyzer",
  "index_analyzer": {
    class: "org.apache.lucene.analysis.en.EnglishAnalyzer"
  }
  "query_analyzer": {
    class: "org.apache.lucene.analysis.standard.StandardAnalyzer"
  }
  "description_index_analyzer": {
    "class": "org.apache.lucene.analysis.standard.StandardAnalyzer",
    "stopwords": [
      "the",
      "a",
      "at"
    ]
  }
}
```

**Comment by smolinari** [comment]
Could there be a way to include different files (CSV?) for stop word lists? 

Scott

**Comment by robfrank** [comment]
No, at the moment you can define them only in the JSON.
Loading from CSV seems reasonable, but what happens if the db is started on a node without that resource (in a distributed scenario). Maybe a better way is let the stopwords to live  in the db itself and allow to define them as a query:
```code
stopwords_query: "SELECT word from stopwords where lang= 'en'";
```
.

I'll update the doc in a few days, stay tuned, because finally implementation differs a bit from this issue.

**Comment by smolinari** [comment]
Yeah, a class with the stop words (in different languages i.e. different documents) could work too. 

Actually I like that idea better. :smile: 

Scott

**Comment by smolinari** [comment]
@robfrank - Where did you finally decide to store the stop word definitions?

Scott
