### ISSUE TITLE
[Orient DB 2.2.0-Beta] OCaseInsensitiveCollate is not working anymore

### ISSUE THREAD

**Issue by Alan47** [orientechnologies/orientdb#5208]
Hi,

we were running on Orient DB 2.1.2. for quite some time now and decided to upgrade to 2.2.0-beta. Everything is up and running and we experienced some performance improvements (which is nice), but OrientDB seems to ignore the OCaseInsensitiveCollate setting on vertex properties for some reason. There's no compile error or anything, just our search fields (which forward to orient db queries) are case sensitive all of a sudden, which is bad for the user experience in our application.

Has there been any change in the collation system between 2.1.2 and 2.2.0-beta?

**Comment by luigidellaquila** [comment]
Hi @Alan47 

Thanks for reporting, having users feedback on beta releases is critical to have a stable final.
There was no explicit change in this, so I guess it's a regression. It will be addressed ASAP.
It would be great if you could provide a simple test case to reproduce it.

Thanks

Luigi

**Comment by Alan47** [comment]
Hi,

thanks for the very fast reply, good to know that there's someone on "the other side" :)

Here's a concrete, stand-alone JUnit test case that shows the error:

    import static org.junit.Assert.*;
    
    import org.junit.Test;
    
    import com.orientechnologies.orient.core.collate.OCaseInsensitiveCollate;
    import com.orientechnologies.orient.core.metadata.schema.OType;
    import com.orientechnologies.orient.core.sql.OCommandSQL;
    import com.tinkerpop.blueprints.Vertex;
    import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
    import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
    import com.tinkerpop.blueprints.impls.orient.OrientVertexType;
    import com.tinkerpop.blueprints.impls.orient.OrientVertexType.OrientVertexProperty;
    
    public class CollationTest {
    
    	@Test
    	@SuppressWarnings("all")
    	public void run() {
    		// OrientGraphFactory factory = new OrientGraphFactory("plocal:" + testDirectory.getAbsolutePath());
    		OrientGraphFactory factory = new OrientGraphFactory("memory:CollationTest");
    		OrientGraphNoTx noTxGraph = factory.getNoTx();
    		// create graph schema
    
    		// This schema will be very simple:
    
    		// class Person {
    		// - firstName: OString (Collation: CI)
    		// - lastName: OString (Collation: none)
    		// }
    
    		OrientVertexType tPerson = noTxGraph.createVertexType("Person");
    		OrientVertexProperty pFirstName = tPerson.createProperty("firstName", OType.STRING);
    		pFirstName.setCollate(new OCaseInsensitiveCollate());
    		tPerson.createProperty("lastName", OType.STRING);
    
    		// now, insert a person
    		Vertex vPerson1 = noTxGraph.addVertex("class:Person");
    		vPerson1.setProperty("firstName", "John");
    		vPerson1.setProperty("lastName", "Doe");
    
    		// not sure if this is requried at all, but it does no harm
    		noTxGraph.commit();
    
    		// try to find it with a query on the first name that uses
    		// the wrong case (which should be ignored according to the schema)
    		String query = "SELECT FROM Person WHERE firstName LIKE 'jo%'";
    		Iterable<Vertex> vertices = (Iterable<Vertex>) noTxGraph.command(new OCommandSQL(query)).execute();
    		// count the size of the iterable
    		int size = 0;
    		for (Vertex vertex : vertices) {
    			size++;
    		}
    		// well, we expect our person to be in the result
    		assertEquals("Failed to find John Doe!", 1, size);
    	}
    
    }



The case above is working perfectly fine with OrientDB 2.1.2, but fails with 2.2.0-beta. The behaviour is consistenly reproducible.

**Comment by luigidellaquila** [comment]
Great! Thank you very much

Luigi

**Comment by Alan47** [comment]
You're welcome. Hopefully this little issue will be sorted out soon.

**Comment by luigidellaquila** [comment]
Hi @Alan47 

This issue was fixed months ago, v 2.2 GA does not have this problem.

I ran your test to double check and it passed correctly.

I'm closing this, please reopen if you still see similar problems.


Thanks

Luigi
