### ISSUE TITLE
really bad performance issue. 

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5211]
explain SELECT FROM media 
 LET $media = (SELECT config, $current.inE("upload").out as outVertex FROM #41:34638)
 WHERE config = $media[0].config AND $current.inE("upload").out = $media[0].outVertex

we have 44177 records for media class. 

the query above only have 14 records in total. 

here this poor performance after doing explain. 

{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 44177,
            "current": "#41:44176",
            "documentAnalyzedCompatibleClass": 44177,
            "parentQuery": [
                
            ],
            "recordReads": 44177,
            "fetchingFromTargetElapsed": 11760,
            "evaluated": 44177,
            "media": [
                {
                    "@type": "d",
                    "@rid": "#-2:44176",
                    "@version": 0,
                    "config": "thumbnail",
                    "outVertex": [
                        "#56:1250"
                    ],
                    "@fieldTypes": "outVertex=z"
                }
            ],
            "elapsed": 11760.945,
            "resultType": "collection",
            "resultSize": 14,
            "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,evaluated=l,media=z,elapsed=f"
        }
    ],
    "notification": "Query executed in 11.972 sec. Returned 1 record(s)"
}

**Comment by maggiolo00** [comment]
@martingg88 

Could you explain a little your domain ?

Is ` #41:34638` a media record?

**Comment by martingg88** [comment]
yes...#41:34638 it is media record.

query here is try to list out all of the medias that meet to config and out vertex from #41:34638 itself.

**Comment by martingg88** [comment]
any update?

**Comment by maggiolo00** [comment]
@martingg88 

can you explain your schema a little bit more so i can try to optimize your query?
From the explain i see that no indexes are used.

**Comment by martingg88** [comment]
let's close this issue pls. Thanks

**Comment by luigidellaquila** [comment]
Hi @martingg88 

do you mean that you found a solution for this?

Thanks

Luigi

**Comment by martingg88** [comment]
yes. try to use the many indexed for the query.

**Comment by luigidellaquila** [comment]
Ok, closing, thank you!

Luigi
