### ISSUE TITLE
strictSQL parser: "instanceof" doesn't work anymore

### ISSUE THREAD

**Issue by a-unite** [orientechnologies/orientdb#5212]
Easy to reproduce (on any DB with strictSQL=on) example:
`select from E WHERE @class instanceof 'E' `

returns 
>`com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: select from E WHERE @class instanceof 'E' Encountered "" at line 1, column 21. Was expecting one of:`

**Comment by a-unite** [comment]
Guys, hi!
I'm curious, is it complex issue?
It looks like this stop-word was just overlooked during parser rewrite stage.

**Comment by luigidellaquila** [comment]
Hi @a-unite 

This should be a trivial fix, I'm working on it right now. I'll let you know soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @a-unite 

I just pushed a fix on both 2.1.x and develop branches. The fix will be available in next hotfix release (2.1.6)
Closing, please reopen in case you find something wrong

Thanks

Luigi

**Comment by a-unite** [comment]
@luigidellaquila, thank you very much, it works now!

Just two minor questions:
1. as far as I know, current version is 2.1.4. Did you mean that it will come in 2.1.5 (next hotfix release), or I've missed something and 2.1.6 just approaching?
2. your commit title mentioned "SELECT with instanceof _single letter_ class name", but  I'm glad this works for any class names, indeed. Was it problem with `instanceof` itself, or with single letter named classes only?

**Comment by luigidellaquila** [comment]
Hi @a-unite 

2.1.5 was released yesterday, it contains the fix so I think you can upgrade

Thanks

Luigi

**Comment by a-unite** [comment]
Thank you very much, @luigidellaquila!
