### ISSUE TITLE
Cannot Check User Role

### ISSUE THREAD

**Issue by bennythomps** [orientechnologies/orientdb#5214]
I have access to a ODatabaseDocumentTx via current thread, but the list of roles is always just "passthrough". I saw in one other person's post, it's a security "feature" but I need to check if the user is an admin and I can only do that via roles.

**Comment by luigidellaquila** [comment]
Hi @bennythomps 

it's normal in remote, user role controls are managed only on the server side, to avoid a double check.
If you need all the roles, you have to execute a query, based on your current user.

Thanks

Luigi
