### ISSUE TITLE
"matches" does not work on standards

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#5217]
HI, I use OrientDB-2.1.4

I have one question, 
when I insert string "_hello beautiful world_" and then I want get this record using the query 
__select from test where str matches 'beautiful'__. //return 0
DB returns empty value to me.

and when I do query with full string, db returns my record.
__select from test where str matches 'hello beautiful world'__. //return 1

This behaviour matches the pattern ^beautiful$ and ^hello beautiful world$ respectively.

so is here behaviour bug or feature?

**Comment by PhantomYdn** [comment]
String.matches try to match whole string agains pattern. If you want  to check for partial match use `(.*)beautiful(.*)`. But in your case I recommend to use CONTAINSTEXT.
http://orientdb.com/docs/2.1/SQL-Where.html

**Comment by luigidellaquila** [comment]
Thanks @PhantomYdn 
exactly, this is the expected behavior, MATCHES tries to match the whole expression.
I can also suggest to use a Lucene fulltext index 

http://orientdb.com/docs/2.1/Full-Text-Index.html

it will give you excellent performance.
I'm closing this, please reopen if you need further info.

Thanks
Luigi

**Comment by Ivanov-Yuriy** [comment]
I deliberately made my example is very simple
I wanted to show it to you.

just, in other places this pattern returns coincidence
but OrientDB doesn't it, and it is confusing.

At the beginning I thought that it doesn't work at all

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

just to make things simple, OrientDB uses Java Pattern class to match patterns, so the expected behavior is exactly the same as the one you would have in Java.
Can I consider this closed or do you have any cases where it fails?

Thanks

Luigi

**Comment by Ivanov-Yuriy** [comment]
Thank you @luigidellaquila for your explanation.
the question is closed.
