### ISSUE TITLE
The way of orientdb and the need of better release notes.

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5220]
Is it possible to get a roundmap for what is the way of orientdb? Why we a have a 2.1.X serie or 3.0, 4.0 besides a 2.0.X serie ? What are the goals of these Versions? Why do you announce the 2.1.x as stable on orientdb.com if we have found lots of issue in the core? I don't understand the principle of orientdb. Please help me to understand. 

My tickets:
https://github.com/orientechnologies/orientdb/issues/5091
https://github.com/orientechnologies/orientdb/issues/5095
https://github.com/orientechnologies/orientdb/issues/5070
...

It is very hard to track all these changes. As a contributor I want to know where we will go. I use orientdb in production and for me it would be great what I have to do to be up to date and what are breaking changes. Look at this github project to see great release notes.

https://github.com/hapijs/hapi/issues/2186

**Comment by StarpTech** [comment]
@lvca @luigidellaquila

**Comment by dopgm** [comment]
+1

Considering to rollout OrientDB to production this year, but having great concerns due to a number of open issues and no clear future for the product. Roadmap paired with a reasonable versioning approach would help a lot.

**Comment by smolinari** [comment]
ODB has both a road map. 

Road map: http://orientdb.com/docs/2.1/Roadmap.html

Not completely sure what you mean with reasonable versioning approach, but ODB does follow semver. 

Versioning: https://github.com/orientechnologies/orientdb/releases

Semver: http://semver.org/

Scott

**Comment by santo-it** [comment]
Hi,

Thanks for your questions 

I believe @smolinari answered already most of them. I just wanted to add that from version 2.2.15 we started to publish again more detailed Release Notes

For version 2.2 you can find Release Notes in this page: https://github.com/orientechnologies/orientdb/wiki/OrientDB-2.2-Release-Notes

Release Notes are now linked from the Documentation as well (for version 2.2, the doc page is http://orientdb.com/docs/2.2.x/Release-Notes.html)

We hope this will help our Community users and Customers tracking changes and fixed bugs in a more easy way

Please let us know if you feel there's something else we can do to help you in this ticket

Many thanks,

**Comment by lvca** [comment]
I think we can close this issue.
