### ISSUE TITLE
Dynamic callbacks for ODocuments

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#5223]
Guys,

There are sometimes need in the following:

1) Associate with a document some callback which should be executed on some event: before/after create, before/after update, before/after read, before/after delete.
2) Associated callbacks should not be persisted in database
3) But these callbacks should be saved if document serialized locally: quite important for a webframeworks where you should be able to work with a document during several requests/responses to a server, but without actual storing of that document to DB.

In [Orienteer](https://github.com/OrienteerDW/Orienteer) I implemented the following approach: https://github.com/OrienteerDW/Orienteer/commit/0302738d64ebe40a040472b8a304399470a561d2  (please check testcase)
But I will be happy to see it in OrientDB themself.

So, what do you think?

**Comment by PhantomYdn** [comment]
Guys,

Any updates/thoughts about this?

**Comment by lvca** [comment]
This is out of scope of OrientDB where the callback can only be functions.
