### ISSUE TITLE
How to resolve Error on rebuilding the  index for clusters: [orole]?

### ISSUE THREAD

**Issue by santhipalla1** [orientechnologies/orientdb#5224]
Tried to import the database but at the time of creating indexes I'm getting error. 

2015-10-26 08:03:43:851 SEVER Internal server error:
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the
 index for clusters: [orole]
--> com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot
 index record #4:3: found duplicated key 'admin' in index 'ORole.name' previousl
y assigned to the record #4:0 RID=#4:0 [ONetworkProtocolHttpDb]
2015-10-26 08:11:22:729 WARNI ->0:0:0:0:0:0:0:1: Command not found: GET.sqlProfi
ler/MS_Glossary [ONetworkProtocolHttpDb]

**Comment by laa** [comment]
Did you import in newly created or existing database ?

**Comment by santhipalla1** [comment]
I had the same problem too. I have created a new database and tried to import.

Please help me.

**Comment by santhipalla1** [comment]
I solved it by dropping the OUser and ORole classes before importing the database into newly created database. It works.
