### ISSUE TITLE
Metadata for DB classes and properties

### ISSUE THREAD

**Issue by dennwc** [orientechnologies/orientdb#5230]
#### Idea
Allow to add some additional information to schema. It can be one string/binary field for each class and property of the class, that database just saves to schema. Objects of that class do not store anything new, it's just an additional meta-information for a whole class or property of that class.

The closest analog in Java is a `@Deprecated` annotation. So it's basically a tags for classes and fields.

Such information can be used for ORM mappers or for a client to store some information to make an extra decisions for a field (canonical name, conversion to native type, etc).

#### Examples:

- Comments on DB classes.

- Concrete type of EMBEDDED/EMBEDDEDMAP as described by client. Again, DB should not try to interpret the field.

- Name of the property/class in client's code, as it may have been changed to be used in DB.

- Can also describe a way to get a objects into a native client's map/array types.

- Other introspection purposes.

**Comment by dennwc** [comment]
Pinging @laa

**Comment by a-unite** [comment]
Hi @dennwc!
We are actively use CUSTOM attribute for this.
Look here: http://orientdb.com/docs/2.1/SQL-Alter-Class.html

**Comment by dennwc** [comment]
@a-unite That exactly what I've looked for. Thanks!
But how to get the attribute back from DB?

**Comment by smolinari** [comment]
Ooh.....that is cool. Thanks for pointing out that gem @a-unite. 

You can get all the metadata from a class with this query.
```
select expand(properties) from (
   select expand(classes) from metadata:schema
) where name = 'YourClassNameHere'
```
Would be cool to know how to query for just one property (like customFields) of the meta data.

Scott

**Comment by a-unite** [comment]
@dennwc, you are welcome!
@smolinari, you are almost there.

Here they are:

For class related customFields:
```
select customFields from (
    select expand(classes) from metadata:schema 
) where name="YourClassName"
```

and for properties customs respectively:
```
select customFields from (
  select expand(properties) from (
     select expand(classes) from metadata:schema 
  ) where name="YourClassName"
) where name="PropertyName"
```

**Comment by smolinari** [comment]
Thanks a-unite. Using Studio, the first query doesn't return any results. I actually tried it too, thinking it might work to get just the `customFields` field. The second query works and returns the `customFields` as a JSON object.

**Comment by dennwc** [comment]
Great! Again, thanks to everyone, I'll close the issue now.

**Comment by smolinari** [comment]
@lvca - what would be the proper process to add this valuable information to the docs? I'd be glad to put in a PR with the additions (and some more), but am not sure that is the right way or what branch to use. It seems the gh-pages branch isn't completed.

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

docs are on a separate project:
https://github.com/orientechnologies/orientdb-docs
you can just submit a pull request on master branch

Thanks a lot!

Luigi

**Comment by smolinari** [comment]
Thanks Luigi! PR coming soon!

Scott
