### ISSUE TITLE
Handle quorum better when synchonizing

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5237]
We noticed the following when restarting nodes in a distributed environment.

We have 3 servers, prod1, prod2 and prod3. It was automatically configured with readQuorum 1 and writeQuorum 2.

When one server goes down (say prod1), prod2 and prod3 continue working, because both quorums are reached.

However when we start prod1 up again, we cannot write until all syncing is done (takes up to 40 minutes!). This is because prod1 and 2 are SYNCHRONIZING and 3 is ONLINE.

I would say that when the server sees that 1 server is up and 2 are syncing, writeQuorum is ok, because we have one node that was uptodate, but is just helping prod1 to get back online.

This is very annoying for our users whenever we need to restart 1 server, while the other 2 are ok.

**Comment by lvca** [comment]
I confirm that to avoid any stop of writes you'd need 5 servers. We could support the fact that while nodes are synchronizing, if this setting is false (default):

```
  "failureAvailableNodesLessQuorum": false,
```

Then the quorum is downgraded.

**Comment by lvca** [comment]
Implemented. Now a node in SYNCHRONIZING status is not considered anymore in the quorum.

**Comment by wouterv** [comment]
It works like a charm. Thanks. But the fix might have induced prjhub issue #5731
