### ISSUE TITLE
Fix for count issue within transaction wasn't merged into develop and/or 2.1.x

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5238]
The following pull request was approved and merged into 2.0.x. But now we are moving to 2.1.x client, we are seeing the errors that made me create this fix.

I looked into the code, and the fix simply isn't there, so I believe @lvca forgot to merge the fix into develop and/or the 2.1.x branch.

See pull request: https://github.com/orientechnologies/orientdb/pull/3847
And issue: https://github.com/orientechnologies/orientdb/issues/3846

**Comment by wouterv** [comment]
Created pull request: #5242, please also merge into develop

**Comment by lvca** [comment]
Sorry, I forgot to port this to 2.1.x and develop.
