### ISSUE TITLE
Functions not available after an import into in memory database

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#5245]
We have run into an issue where custom functions (those inserted into the OFunction table, or through STUDIO) do not work after importing a database into an in memory storage database.

We created a database in studio, added a custom function (javascript).  Then we exported the database to a file "test1.gz", using the code below.

```Java
ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:test")
db.activateOnCurrentThread()
db.create()

File file = getClass.getResource("/test1.gz").getFile()
ODatabaseImport dbImport = new ODatabaseImport(db, file, CommandListener)
dbImport.importDatabase()
dbImport.close()
```

After the import all of the schema and data form the import are present in the database.  However attempting to run a query using on of the custom functions fails with an exception:

OCommandSQLParsingException("No function with name 'abs", available names are...")

It appears that the com.orientechnologies.orient.core.sql.OSQLEngine.getFunctionFactories() method lazily builds the FUNCTION_FACTORIES list and loads each.  Ultimately the XXX class will have an instance of OFunctionLibraryImpl which also has a load method, which executes the query "select from OFunction order by name".  The results get put in a map called "functions".  This happens when the in memory database is loaded.  Even though the import inserts records into the OFunction table.  The OMetadataDefault instance has already loaded the OFunctionLibraryImpl (at which point there were no functions.

We found that after the import we needed to call:

```java
db.getMetadata.reload()
```

After doing this, the functions were callable.  I think that the database import should probably do this automatically.

If you concur, I can create a pull request.

**Comment by lvca** [comment]
Thanks for the PR!

**Comment by lvca** [comment]
Back porting to 2.1.x...

**Comment by lvca** [comment]
Done, thank you again.

**Comment by mmacfadden** [comment]
you bet.  Not the most complicated PR ever!
