### ISSUE TITLE
random order in metadata:schema

### ISSUE THREAD

**Issue by micha-nerdlichter** [orientechnologies/orientdb#5247]
The query

``` sql
select expand(classes) from metadata:schema
```

returns the data in a different order every time it runs. Of course a

``` sql
select from (select expand(classes) from metadata:schema) order by name
```

fixes this on the first level, but how can I keep `properties` in order? I want a result that stays the same on every call so I can keep a schema.json in my git repo in order to track schema migrations.

**Comment by luigidellaquila** [comment]
Hi @micha-nerdlichter 

I don't know if/when this enhancement will be included in the roadmap, but for now you can try this work-around (a bit tricky, but it should do the job):

```sql
select from (
select expand($all)
let 
$withoutProps = (select from (select expand(classes) from metadata:schema ) where properties.size() = 0 ),
$withProps = (select *, list(properties) as properties from (
      select from (
        select from (select expand(classes) from metadata:schema )
        where properties.size() > 0 unwind properties
      ) 
	 order by properties.name asc
    ) group by name order by name
),
$all = unionAll($withoutProps, $withProps)
) order by name
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
In the meantime I'm adding a tentative release milestone for this at 3.1 (maybe it will be anticipated)

**Comment by micha-nerdlichter** [comment]
Thank you @luigidellaquila, ```unwind``` did the trick. I also tried a complex queries like yours with nested ```let``` and ```expand``` but with no luck. So
```sql
select from (
  select from (
    select expand(classes) from metadata:schema
  ) unwind properties order by properties.name
) order by name asc
```
does pretty much what I want.

**Comment by lvca** [comment]
Already available by using math_rand() function and ordering by it. Example:

```
select a, b, math_rand() as c from X order by c
```

**Comment by micha-nerdlichter** [comment]
No, I didn't want a random order! The problem *is* that metadata:schema is returned in a different order on every call, so it is difficult to do diffs on the schema.

**Comment by lvca** [comment]
That's different, sorry I should have read the body. This can be easily fixed by ordering class names and properties per class.

**Comment by micha-nerdlichter** [comment]
Exactly, it would be nice to have it in alphabetical order by default without the unwind and expand hussle;)
