### ISSUE TITLE
Very bad performance - need help troubleshooting

### ISSUE THREAD

**Issue by aag-tonesoft** [orientechnologies/orientdb#5250]
We are using the Graph API to maintain a Graph of phone handsets calling each other and their voice quality metrics as the calls traverse the network.  Our data model is about 16 vertex classes and 32 edge types.

**Comment by lvca** [comment]
@aag-tonesoft could we have more information about the bad performance? It's in query, insertion, update, delete, everything? Could you show the most slow operations?

**Comment by aag-tonesoft** [comment]
Inserts/updates are taking longer than expected.  We have a multi-threaded system collecting data, but have them filtered down to one thread because I was getting OConcurrentModification exceptions while added vertices and edges to the graph.  The delay in creating the edges and vertices is bearing itself out as a backlog of work and we quickly hit some tipping point where we can no longer keep up.  The basic jist is that we have a Call Vertex representing a call between two devices. We create edges between the call and a "bucket" of quality of the call.    There are generally 4 types of metrics we are collecting for a call, so we lookup or create a Call Vertex. We then look at the quality of the call, for metric A, lookup the bucket Vertex for metric A and create an edge from the call to the metric A bucket Vertex.  We repeat for metrics B,C, and D.  That represents a relationship of a call to the quality buckets, but our design needs to also know when the call occurred and for that point in time, what were the quality metrics. So, on a lot of edges we must maintain the time that the call occurred, the edges between the Call and metric bucket vertices. Additionally, there is a time tree of vertices to help us narrow down the calls that occurred during some time search.  The vertices in this tree looks like this Year -> Month -> Day -> Hour -> 5minIncrements -> Call -> [4 to 8 buckets].

The edges between [5minIncrement -> Call] and [Call -> Bucket] have a time stamps that I search on, and therefor there are quite possibly MANY edges between different 5MinIncrement Vertices pointing to a single Call Vertex AND MANY edges out of Call that single Vertex to the various buckets.  I think this insertion/update of vertices and edges is slow.  

What tools are available to monitor slow operations. I see that profiling is turned on be default in the db, but I don't know how to use it. When i tried to use the console to 'profile dump' it had some error.  

How can I give you a backup of our DB for you to look through.  I can give you a Gremline Pipeline in java to represent some of the queries we do.  in psuedocode, we're generally doing something like this: I call the Hour vertex TimeSegment and the 5minIncrement TimeSlices.  Let's assume I want a full hour of data, g.V(the hour I care about).out('TimeSegmentTimeSlice').out("TimeSliceCall").has(some indexed property segmenting the data for a customer).groupBy{call}{call.outE('CallQosBucket').has(time matching the hour that I want)}.cap

**Comment by aag-tonesoft** [comment]
@lvca When I update a property on the edge edge between Call and Bucket vertices, according to the documentation, the optimistic locking updates the version number of the Call and Bucket vertices, does the update to those vertices cascade to updating version numbers of other vertices it's connected to?

I'm too late in the dev cycle to implement the update/retry logic suggested to overcome the OConcurrentModificationException that might be thrown when updating vertices so I've added some code to batch updates through a single thread to work as fast as possible.  While that thread is working as fast as possible, the updates are taking 26-45 seconds and we're generating data MUCH MUCH faster than that. It's a losing battle. I need real help. I may have to report to the VP that this technology is not going to scale.

**Comment by lvca** [comment]
The version number is not updated in cascade, but involve only the records that are part of the change. I don't know very much about your use case, your database and your code. Since you already ended the development we're going to try to optimize your bottlenecks without breaking too much your code. 

I have a few questions: How do you update edges? Are you doing a batch of updates in one transaction? Or you rather have one tx per update? Why you update edges instead of creating them with the final value? The relevant code would be also useful. You can send private things to support at orientdb.com by specifying your client id. Thanks.

**Comment by aag-tonesoft** [comment]
I'll work on extracting some code for my slow updates. Is it possible to have a GoToMeeting to explain our use case and discuss optimizations?

In all honesty, I have a better design in my head as to a replacement data model but for now, I cannot eat the cost of the refactoring. 

We have vertices that represent data between two devices, Calls, handset A calls handset B. Often, we get traceroute information that the call traversed.  For this Call, we get 4 different metrics that i care to record.  Normally, when we get the call, I search in the Graph using gremlin for the vertex that matches the call. If I find it, I'll be adding edges to it. If it doesn't exist, I'll create it. It had indexed properties to help me find it and it has edges from a time tree to help me narrow down the search. For each of the 4 metrics, the value is normalized to some bucket, some finite range if values that virtually mean the same thing. Maybe the possible range is from 0-500, so I normalize the values into increments of 50.  So, I'll find a vertex that matches this normalized value and create an edge between it and the call. I'll do this same thing for the remaining there metrics. Additionally the call may have traversed some network hops to get from headset A to Handset B.  A -> hop1 -> hop2 -> B.  I call each pair of neighbors A::hop1, hop1::hop2, hop2::B NetworkSegments.  I search for our create vertices to represent the NetworkSegmenrs. The same metric vertices I attached to the Call vertex will be attached to each NetworkSegment vertex.  The edges (named CallDataBuckets) between Call and Metric or NetworkSegment and the Metric represent a 5 minute aggregation of all the traffic that passed through the devices. When creating or updating the CallDataBucket edges, I have some properties on it that are being updated, the count, metrics min, max, total, and average. 

Right now, for each transaction I try to collect ( based on system load ) and group a bunch of calls together in each transaction. 

Does this paint a picture of the data model? I can upload a backup of a sample db, please give instructions of how to send it.

**Comment by StarpTech** [comment]
Why closed?

**Comment by aag-tonesoft** [comment]
I must have done something incorrect to close it, the issue is definitely not closed, it's killing me right now.

**Comment by lvca** [comment]
@aag-tonesoft please could you send the backup (not export) to support at orientdb.com? Furthermore we'd need the most slower queries to understand how to optimize them. Usually if you use Gremlin, the first step is using SQL: most of the times is much faster.

**Comment by aag-tonesoft** [comment]
I sent an email to support with an explaination of our current problem, a stack trace and a java flight recording to demonstrate blocked threads, can you associate that email with this thread.  Any insight into the problem will help.

**Comment by jillray7** [comment]
@aag-tonesoft I see that you sent an email a while back to support. Were you assisted? Does this problem still exist? Please attach any additional information to this ticket if more support is needed.

**Comment by aag-tonesoft** [comment]
I got a response by nothing that truly solved my problem. Performance is not what I would expect, it degrades severely after enough data is inserted to the db. Our app is write heavy and after a few million edges it takes multiple seconds to write a string of graph nodes.

Amit



On Fri, May 20, 2016 at 1:17 PM -0700, "jillray7" <notifications@github.com<mailto:notifications@github.com>> wrote:


@aag-tonesoft<https://github.com/aag-tonesoft> I see that you sent an email a while back to support. Were you assisted? Does this problem still exist? Please attach any additional information to this ticket if more support is needed.

-

**Comment by lvca** [comment]
@aag-tonesoft Can I try to help on this? What's the piece of code that you use to write the edge? You could also close this and open a private issue if it's the case.

**Comment by aag-tonesoft** [comment]
closing issue, we're reworking our approach.
