### ISSUE TITLE
Monitoring system functionality

### ISSUE THREAD

**Issue by aag-tonesoft** [orientechnologies/orientdb#5251]
We ran into an issue where OrientDb appeared to still be running but was totally non-responsive. We normally launch the server as a java process and have a wrapper script watching for it to exit, if it exits, we restart it.  This is insufficient in this case.  The documentation suggests that there might be some jmx interface to help us monitor health.  Can you provide some assistance.

**Comment by pythianarceri** [comment]
The metrics instrumentation documentation could use some help, following the instructions to enable the JMX component doesn't seem to be enough to start collecting stats.

**Comment by laa** [comment]
we consider using JFR events + JMX in next versions.
