### ISSUE TITLE
Js Function - record.field(<property>) type information get lost

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5253]
2.1.5
Studio

```
record.field('IsActive') => "true" or "false" instead true or false
or
record.field('Total') => "0" instead 0
or
record.field('Name') => "Peter" correct but record.field('Name') === "Peter" equals false and
record.field('Name') == "Peter" equals true
```

Walkaround explicit type parsing with `parseFloat`, `parseInt`

This can lead to big issues in calculations.

**Comment by StarpTech** [comment]
@lvca @maggiolo00 any idea?

**Comment by maggiolo00** [comment]
@StarpTech 
where do you get this conversion?

I've run this example function and i do not get the conversion

```JAVASCRIPT
var db = orient.getDatabase();

var doc = {"@class" : "V" , "booleanValue" : true}

var result = db.save(doc);

return typeof result.field('booleanValue');
```

**Comment by StarpTech** [comment]
@machak 

For example string comparison:
```
var record = userNode[0].getRecord();
var recordCareerLevel = record.field('Position'); // Position = 'partner'

return recordCareerLevel === 'partner'; //false

return recordCareerLevel == 'partner'; //true
```

**Comment by StarpTech** [comment]
Another example:

```
@param includeInactive: <boolean>
function(includeInactive) {
return typeof evaluateSponsor;
}
```
Result:
```
[
    {
        "@type": "d",
        "@version": 0,
        "value": "string"
    }
]
```

**Comment by StarpTech** [comment]
@maggiolo00 yes it is an issue of how studio evaluate the parameters. They won't be parsed in the correct type.

**Comment by maggiolo00** [comment]
@StarpTech 

where do you call includeInactive(true)?

From studio ui?

**Comment by StarpTech** [comment]
yes from Studio there it works correctly but from the Functions administration section it doesnt works

**Comment by maggiolo00** [comment]
@StarpTech 

yes the functions administration uses the REST api with parameters in URL as you saw, so the http layer call the function with strings as it cannot knows the type, and the type conversion is up to you. 

http://orientdb.com/docs/last/Functions.html#create-your-first-function

**Comment by maggiolo00** [comment]
BTW in 2.1

parameters can be used also in body, so in studio we can use that api to have better control on type.
http://orientdb.com/docs/last/Functions.html#usage-via-http-rest

**Comment by StarpTech** [comment]
@maggiolo00 ok thanks for the tip.

**Comment by maggiolo00** [comment]
@StarpTech 

i will leave it opened, marked as enhancement to make use of 
parameters in body with post instead of url parameters

**Comment by StarpTech** [comment]
@maggiolo00 I would mark it as issue because your have to handle you paramaters in two different ways this cannot be a compromise. Another issue is my last post.

```
var record = userNode[0].getRecord();
var recordCareerLevel = record.field('Position'); // Position = 'partner'

return recordCareerLevel === 'partner'; //false

return recordCareerLevel == 'partner'; //true
```
