### ISSUE TITLE
set config via resource instead of File

### ISSUE THREAD

**Issue by fommil** [orientechnologies/orientdb#5255]
I'm wanting to create an embedded OrientDB in my desktop application, but the setup involves three files http://orientdb.com/docs/2.1/Embedded-Server.html --- can't you do this without requiring config files? I can do everything programmatically.

**Comment by fommil** [comment]
the docs are incomplete! :smile: reading the API it seems possible to pass in a configuration object directly.

**Comment by lvca** [comment]
Fixed in docs. Thanks.
