### ISSUE TITLE
consider using `optional` elements in the orientdb-graphdb pom.xml

### ISSUE THREAD

**Issue by fommil** [orientechnologies/orientdb#5256]
`orientdb-graphdb` basically pulls in the universe. It would be good if it only pulled in its required dependencies, and marked all the other dependencies (e.g. `groovy`!!) as `optional`.

Docs here https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by lvca** [comment]
I think we could set groovy, gremlin and rexster as optional. Anyone has objections?

**Comment by lvca** [comment]
Removed in develop branch.

**Comment by fommil** [comment]
:smile:
