### ISSUE TITLE
Setting up a "one to one" edge to vertexes of the same class not possible(?)

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#5261]
In working out this suggestion,

https://github.com/orientechnologies/orientdb/issues/5260

it seems it isn't possible to create an edge, which is unique among the same vertex class.

For instance, I have a `Person` vertex and I want to create a `MarriedTo` edge. There seems to be no way to create this monogamous relationship between two people (using standard edges)?  ODB allows more of such edges, despite a unique index on in and out.

Currently this is a question, as I am uncertain myself that it is true. If there is a way to create a one to one relationship to two vertexes from the same class, I'd be thankful for someone showing it to me. 

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

I think the only way you have to create such constraint is to define a hook on the edge class (http://orientdb.com/docs/last/Hook.html) and check both connected vertices on OnBeforeCreate event.
In case there is already an edge defined on one of the vertices, you just have to throw an OValidationException

Thanks

Luigi

**Comment by StarpTech** [comment]
Does exist hooks for the Binary Protocol?

**Comment by smolinari** [comment]
Yes, @StarpTech 's question is a good one, as we are also using the binary protocol. 

Scott

**Comment by luigidellaquila** [comment]
Hi guys,

hooks are defined at storage level, not on the communication layer, so you have to define them on the server side.

**Comment by luigidellaquila** [comment]
I'm marking this as an enhancement, as it seems to be an interesting topic.

**Comment by smolinari** [comment]
Correct me if I am wrong, but isn't it possible to create dynamic hooks through the communication layer?

http://orientdb.com/docs/last/Dynamic-Hooks.html

Though, to me, and in general, edge multiplicity and direction constraints should be an integral part of ODB's class creation commands, as noted in my suggestion.

Scott

**Comment by luigidellaquila** [comment]
Hi Scott,

yes, you can create dynamic hooks with simple SQL statements.

I agree with you on the fact that control over multiplicity should be an integral part of the schema definition, this is why I flagged it as an enhancement

Thanks

Luigi

**Comment by smolinari** [comment]
Ok. Great. Please flag my actual suggestion too please, if you could. 

https://github.com/orientechnologies/orientdb/issues/5260

Thanks! 

Scott
