### ISSUE TITLE
The use of the words "next hotfix" in the patch release milestones

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#5262]
Hi @lvca,

Just a little QA nitpicky item. Hotfixes are usually considered patches or fixes, which are done outside of the normal development process. For instance, if a user or customer had an issue that is determined to be a security issue or the bug causes major data loss, then you would create a hotfix to solve that problem and release it immediately as a patch or "hotfix" version. So, you would have maybe something like a "2.1.5 PL1", for instance, as a release. PL standing for "Patch Level". 

https://en.wikipedia.org/wiki/Hotfix

See also Gitflow workflow and the hotfixes branch. 

http://nvie.com/posts/a-successful-git-branching-model/

I am pretty sure you know all this.

I am bringing it up only because someone unknowing to ODB might misunderstand the importance or severity of issues marked with "next hotfix" (It looks like everything is a seriously bad bug). And, when you actually do have such a serious issue, which needs a real "hotfix", you are missing the capability to flag it properly from the bugs being fixed in the "normal" development process. 

Again, it is nitpicky, I know. 

Still, I hope I could help. :smile: 

Scott

**Comment by lvca** [comment]
Hi Scott, we're following the semantic version way: http://semver.org/.

**Comment by smolinari** [comment]
Sure, but there is no mention about the handling of "hotfixes" in semver. 

At best, one could call a hotfix a type of pre-release and handle it that way. One could denote the hotfix version with something like "-HF1", like 2.1.5-HF1. "HF" = hotfix.

Again, my point is, normally a "hotfix" is a quick important fix to resolve some severe bug or bugs. Denoting all patch versions of ODB with "next hotfix" portrays a severity, which isn't really there. It also takes away the ability to actually release a real "hotfix", when one is needed, because every patch version is a "hotfix" according to the versions in Github. It is sort of like "[The boy who cried Wolf](https://en.wikipedia.org/wiki/The_Boy_Who_Cried_Wolf)". :smile:

Scott

**Comment by smolinari** [comment]
I'll close this, as I don't think the current release terminology will be changed. 

Scott
