### ISSUE TITLE
How can I profile Graph API updates to the db?

### ISSUE THREAD

**Issue by aag-tonesoft** [orientechnologies/orientdb#5265]
We have some constant (in time) updates to the db, one every 30 seconds, that are getting very very very slow.  The thread doing the update to the graph model needs to find if vertices and edges exist and update or create new relationships.  For some reason the requests are getting very slow over time, how can I understand where the bottleneck is. There must be some logs or tools that can "profile" graph api updates.  The performance of the db updates is making us question if we can go into production with this database.

**Comment by StarpTech** [comment]
Hi aag-tonesoft this question is also very important for me.
At the moment you can 'explain'  your query to find some bottlenecks. In the enterprise Edition you can find a profiler it is free for development.

**Comment by maggiolo00** [comment]
@aag-tonesoft 

can you provide some code?
Are you using any index to finde vertices?

**Comment by aag-tonesoft** [comment]
@maggiolo00 that is easier said than done. Yes, we are using indexes to find vertices and edges. Some example of my updates that are slow are explained in issue #5572, does that give you some information. 

@StarpTech How do I find a query to explain.  I'm using the java graph API? 

I need some clear instructions or extra assistance on how to use the profiler to find out why the the updates are so slow.

**Comment by lvca** [comment]
@aag-tonesoft please use the Enterprise Edition (download it from the web site) and after a while you should see the most expensive queries. Also, if you have the SQL query, prefix it with EXPLAIN in studio to have profiling information.

**Comment by aag-tonesoft** [comment]
All operations are via java and using the Graph API for inserts and updates and gremlin for queries, they don't seem to show up, should they?
________________________________

**Comment by aag-tonesoft** [comment]
All operations are via java and using the Graph API for inserts and updates and gremlin for queries, they don't seem to show up, should they?

**Comment by aag-tonesoft** [comment]
Any help you can provide?

**Comment by lvca** [comment]
Ok, so could you provide such gremlin queries and your database?

**Comment by lvca** [comment]
No answer after long time, closing.
