### ISSUE TITLE
Studio doesn't work in Community Edition

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#5266]
Hi, 

I upgraded to 2.1.5 Community Edition on my dev server trying both the download and the clean install methods and with both, Studio kept ending up with a 404 (white blank page).

I then decided to try and download the Enterprise Edition and, lo and behold, Studio is working. I did nothing different in the steps to install the download version of the Community Edition, thus, I think  there might be an issue with it and Studio. I can't, however, deny I might have done something wrong during the upgrade/ installation either. If someone could check Studio in version 2.1.5 Community Edition, and confirm there is an issue, I would be greatful. 

Scott

**Comment by robfrank** [comment]
On 3 November 2015 at 07:45, Scott <notifications@github.com> wrote:

> Hi,
>
> I upgraded to 2.1.5 Community Edition on my dev server trying both the
> download and the clean install methods and with both, Studio kept ending up
> with a 404 (white blank page).
>
> I then decided to try and download the Enterprise Edition and, lo and
> behold, Studio is working. I did nothing different in the steps to install
> the download version of the Community Edition, thus, I think there might be
> an issue with it and Studio. I can't, however, deny I might have done
> something wrong during the upgrade/ installation either. If someone could
> check Studio in version 2.1.5 Community Edition, and confirm there is an
> issue, I would be greatful.
>
>
>
I tested a fresh installation of 2.1.5 and it works.
How did you upgraded?
Did you copy jars and studio to a previous installation?
Best regards,
RF

-- 

Roberto Franchini

Orient Technologies
http://orientdb.com

**Comment by smolinari** [comment]
I downloaded the precompiled files and just uploaded them to where ODB is on my server.

I also did the "git clone" and "ant clean install" and moved the files generated in the "distributed" folder to where ODB is on my server. 

Both attempts (installing with master and 2.1.5) failed to get Studio working again. Only when I used the Enterprise files, did Studio start working again.

Maybe it was just a fluke? I'll do some more attempts with the next version of Community, when it comes out. Now I am happy, and don't want to mess with my working system. LOL!

**Comment by robfrank** [comment]
If you really want to build by your own, use maven clean install -DskipTests.
Then pick your preferred flavour of package from distribution/target: it is a complete zip/tar.gz. You can even run the server from distributiom/target/orient.....dir

**Comment by smolinari** [comment]
Yeah, I noted the warning about ant being deprecated in the building process. I'm not a java dev, so all of this building stuff is new to me.:smile: I develop mainly in PHP. If I have the time, I'll do some playing around with maven too. I appreciate the help and suggestions. 

Scott
