### ISSUE TITLE
Add option to disable zipping before syncing a distributed databases

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5268]
Whenever we add/restart a node, the whole database is being zipped before sending. I understand this helps for databases that do not contain blobs, but our database consists of about 22GB blobs and 6GB data. What's worse, we already zip our blobs, so zipping the clusters that contain blobs takes a very long time, but hardly helps with minimizing the data transfer and thus it would be better not to zip those clusters (or all clusters) at all.

**Comment by lvca** [comment]
You can use `-Ddistributed.deployDbTaskCompression=0`
