### ISSUE TITLE
OrientDB indexes are not working properly with formatted params used in server functions

### ISSUE THREAD

**Issue by cjayawickrema** [orientechnologies/orientdb#5270]
OrientDB is throwing a java.lang.ClassCastException when a sever function (a query on indexed fields) is executed with formatted params. Following messages are seen with the exception. "Error on using index", "Probably you need to rebuild indexes. Now executing query using cluster scan

e.g.

db.query("SELECT FROM Employee WHERE department = ?", departmentRid);
where, Employee.department is indexed with NOT_UNIQUE_HASH_INDEX
When I removed the formatted params and injected them manually index worked out fine. e.g.

db.query("SELECT FROM Employee WHERE department = " + departmentRid);
Any reason why the first approach didn't work? I'd like to refrain from injecting the params manually.

Note that the both approaches gives me the correct result. The problem is that the index is not applied for the first approach.

I am using orientdb-community-2.1.0

**Comment by luigidellaquila** [comment]
Hi @cjayawickrema 

Both approaches are supposed to work the same way.
Two quick questions:
- what is "departmentRid" exactly? Could you post the full code to reproduce the issue?
- have you tried it with 2.1.5? We don't have any open issues about this case, so probably if a problem was present it's already fixed

Thanks

Luigi

**Comment by cjayawickrema** [comment]
departmenRid is an argument passed in from the function. It is basically a String. and Employee.department is a LINK to Department. 
But no I have not tried out 2.1.5 yet. Appreciate if you can confirm it. Note that it gives the correct result but throwing an error on the console - while skipping the index.

Alessandro Rota from Stackoverflow could recreate this issue. I am posting their screenshot. 

![image](https://cloud.githubusercontent.com/assets/9631525/10940274/816a2f18-832b-11e5-9c3f-7f51e70d6e89.png)
