### ISSUE TITLE
Creating databases / database not configured

### ISSUE THREAD

**Issue by theduke** [orientechnologies/orientdb#5275]
Just starting out with OrientDB and immediately ran into an issue.

In the console:

`create database plocal:test`

... (create classes, etc) (works fine)

```
list databases

* GrateFulDeadConcerts

=> new database is missing!

create database plocal:test

=> database already exists
```

Try to connect again:

`connect remote:localhost/test root root`

=> database is not configured on server

**Comment by lvca** [comment]
You can't create a database using plocal (=local) under the current directory and let the server scan the entire disk to find it. Rather create the database against the server with the url: `remote:localhost/test`

**Comment by theduke** [comment]
Alright, thanks.
The docs should really mention this!

**Comment by lvca** [comment]
Please help on improving docs. Which docs did you follow?

**Comment by theduke** [comment]
http://orientdb.com/docs/
