### ISSUE TITLE
Data Aggregation Question

### ISSUE THREAD

**Issue by cjohns38** [orientechnologies/orientdb#5280]
Is it possible to run a query and group the results as you go down the graph?  

Example: 
* Main vertex: city
* Secondary vertex: house 
* Tertiary vertex: person 

Is it possible to write a query where I specify the city, find all the houses in the city, and then output all the people in each house grouped by the house they are in? I know how to get the houses, I know how to crawl to the people, I'm not sure if I can somehow group that data together. 

{'House1':['John', 'Joe', 'Bobby'], 
 'House2':['Jill', Jane', Jeff'], 
}

**Comment by luigidellaquila** [comment]
Hi @cjohns38 

I suppose you have a graph domain, something like

City -hasHouse-> House -hasPeople-> People

The query should just be 

```sql
select name, out("hasPeople").name as people  from (
   select out("hasHouse") from city where name = 'yourCityName'
)
```

I hope I got it right, in case please post some additional details about your domain and I'll try to give you a more specific answer

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @cjohns38 

I saw no comments on this, I hope my answer solved your use case. I'm closing this, please reopen in case
