### ISSUE TITLE
Creating propertie in a big class

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#5281]
Hi Guys,

We are trying to create a new property in a class with 113M registers.

It has been taking 6 hour and didn't finish.

Lookin to the log seems that it's verifying each register:
"
2015-11-05 17:28:53:164 FINE  {db=ilang} Read record #47:34252198 v.4 size=131 bytes [OLocalPaginatedStorage]
2015-11-05 17:28:53:164 FINE  {db=ilang} Read record #47:34252199 v.4 size=131 bytes [OLocalPaginatedStorage]
2015-11-05 17:28:53:164 FINE  {db=ilang} Read record #47:34252200 v.4 size=131 bytes [OLocalPaginatedStorage]"

Is there anyway to do it ignoring existing registers?

Thanks,
Thiago

**Comment by thiagopm** [comment]
There is any problem if we use unsafe?

**Comment by lvca** [comment]
@thiagopm create property converts any schema-less property with that name in schema-full. That's why takes so much time (in v2.2 we improved this kind of operations and they take much less). If you know that the property you're willing to create doesn't exist in your documents, then UNSAFE is ok to use.

**Comment by smolinari** [comment]
Out of curiosity, if we had started with a schema-full schema and added a property with a database that has millions of records, would there still be this a noticeable delay in adding the property?

And asked from a different perspective, if we control schema on the application side, like is usual to do for any document store, would the addition of new properties be a lot simpler and faster for ODB?

Scott

**Comment by thiagopm** [comment]
Ok... Thanks Luca.

**Comment by smolinari** [comment]
@lvca - How about my questions?

Scott
