### ISSUE TITLE
Unknown email in parameters when downloading enterprise version

### ISSUE THREAD

**Issue by warriorkitty** [orientechnologies/orientdb#5282]
It's actually a minor bug.

1.) submit the form for downloading the enterprise version
2.) check your inbox and start downloading the enterprise version
3.) check in your URL inside your browser email = "unknown@unknown.com" **instead** of my provided email inside the download form

I don't know if the email is important to you but it's not the same as the email I provided inside the download form.

**Comment by luigidellaquila** [comment]
Hi @warriorkitty 

Thank you for reporting, it's not a blocker of course, but we will double-check
I'm closing this just because it's not strictly related to the product

Thanks

Luigi
