### ISSUE TITLE
pull-down menus on http://orientdb.com using Google Chrome on a mac

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5284]
Using the current version of Google Chrome for OS X (Version 46.0.2490.80 (64-bit)), it's not possible to make a selection from the pull-down menus at the top of the page on http://orientdb.com (main page and sub-pages).

There's no problem when using Safari.

**Comment by lvca** [comment]
Could you please attach a screenshot?

**Comment by pkoppstein** [comment]
> Could you please attach a screenshot?

Sorry, I've since upgraded to Version 46.0.2490.86.  However this upgrade or perhaps some change at orientdb.com resolves the problem.  Please feel to close the ticket.  Thanks!

While I have your attention - a quick question.  Running server.sh (community-2.1) and using the Grateful Dead database, when I click on Graph and enter a query such as "select * from v", a rather annoying graphical display appears.  It's annoying because (a) the circles jiggle around in a way that makes it difficult to arrange the graph usefully (there doesn't seem to be any "freeze this node" functionality) ; (b) the labels are useless; (c) there doesn't seem to be a way to do things interactively such as highlight edges with a certain label. Mouse-left does work, but the right-mouse just brings up the (Chrome) browser context menu.  

The last five sections of http://orientdb.com/docs/2.1/Graph-Editor.html are empty, so perhaps it's just a question of completing the documentation?

**Comment by lvca** [comment]
@pkoppstein in order to address the issue, could you please open a new one with your question?
