### ISSUE TITLE
Error deploying distributed databases when using symlinks

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#5285]
When using a symlink to the single database folder, the replication process does not work properly.
Database compression on the source node ends up in an infinite loop.

A possible work around is to use symlink for /databases folder instead of single symlink per database

**Comment by wouterv** [comment]
Fyi, we are using symlinks and indeed we symlink the databases folder only.

**Comment by lvca** [comment]
Ok, closing this issue with the solution.
