### ISSUE TITLE
Concurrent reads with LET subquery very slow

### ISSUE THREAD

**Issue by janjilek** [orientechnologies/orientdb#5286]
Hi, if i try to query 100 times in parallel this select: 

```sql
SELECT *, $product as product FROM Category LET product = (SELECT expand($parent.$current.IN('Belong')[@class = Product]) LIMIT 10) ORDER BY (priority desc)
```

It looks like, that queries are executed one by one, because i receive first response in 500ms, second in 1000ms and last in 50s.

I have index on priority column.

Any work around for this? 

Tested on:
OrientDB 2.1.5
4 cores
15GB of RAM

**Comment by luigidellaquila** [comment]
Hi @janjilek 

this is exactly the case, LET query is executed once per record in Category.
Maybe you can restructure your query as follows:

```sql
SELECT *, in("Belong")[0-9][@class = Product] as product FROM Category ORDER BY (priority desc)
```
Let me know if it works better

Thanks

Luigi

**Comment by janjilek** [comment]
Hi,
thank you, its much faster! Now i receive last request in 3 seconds. Can i order by vertex @rid somehow in the in("Belong")[0-9][@class = Product] query? 

So its better to avoid LET completely in the select? I am using this style everywhere.

Regards
Jan

**Comment by janjilek** [comment]
Sorry, so its not. It wasn't exactly the same query. I have change in("Belong")[0-9][@class = Product] to in("Belong")[@class = Product][0-9] and its againt 50s for the last one. So the bottleneck is definitelly filtering @class = Product.

Regards
Jan

**Comment by luigidellaquila** [comment]
Hi Jan,

Just to better understand, how many incoming edges to you have on each vertex?
LET operator in some cases is not very efficient, but simple traversal should be

Thanks

Luigi

**Comment by janjilek** [comment]
Category vertex has cca 10k edges to product vertex. But it will grow in the future and I expect maybe 100k for each category. Maybe better idea is to create special edge HasProduct instead of in('Belong')[@class = Product] to avoid filtering.

**Comment by luigidellaquila** [comment]
Yes, definitely, query performance depends on how many vertices/edges you have to analyze, and in this case you are doing filtering on millions of vertices probably

**Comment by luigidellaquila** [comment]
@janjilek I'm closing this as it's not properly an issue. Maybe we can continue this discussion on StackOverflow if needed, there the community is very active and can give a contribution from real life experience.

**Comment by janjilek** [comment]
Thank you!

Jan
