### ISSUE TITLE
Studio Javascript error - can't execute batch command

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5287]
Orientdb 2.1.5

```
begin
LET t0 = SELECT SUM(BinPoints) as Total FROM ( TRAVERSE References FROM #18:0 ) WHERE $depth = 1 AND BinaryQualified = false
LET t1 = SELECT SUM(BinPoints) as Total FROM ( TRAVERSE References FROM #18:0 ) WHERE $depth >= 2 AND $depth <= 3 AND BinaryQualified = false
LET t2 = SELECT SUM(BinPoints) as Total FROM ( TRAVERSE References FROM #18:0 ) WHERE $depth >= 4 AND $depth <= 5 AND BinaryQualified = false
LET t3 = SELECT SUM(BinPoints) as Total FROM ( TRAVERSE References FROM #18:0 ) WHERE $depth >= 6 AND $depth <= 7 AND BinaryQualified = false
commit retry 100
return [$t0,$t1,$t2,$t3]
```

![image](https://cloud.githubusercontent.com/assets/1764424/10999381/de667fa2-849b-11e5-8b6d-afd9890024f1.png)

**Comment by StarpTech** [comment]
During this error I also found this one with the same query https://github.com/orientechnologies/orientdb/issues/5288

**Comment by maggiolo00** [comment]
@StarpTech 

which is the response from the server when you run this batch using studio?

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
