### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5295]
for freebsd:
* fix bash path to /bin/sh on all script
* add rc run script

**Comment by erlanghacker** [comment]
oriented.sh and shutdown.sh obtain the running oriented process using

ps -ef  etc...

which means nothing on BSD unix.  I replace both occurrences with

ps -auxww  etc...

and they work fine thereafter

the latest download I  tried had users section as

<users>
<users/>

in the xml config file.   I added back the two missing lines and
it then worked fine

**Comment by lvca** [comment]
The `users` section is usually created at startup time if empty (auto-generated passwd (salted+hashed)). @robfrank about such commands, are they compatible on Linux as well? or can we just add IF blocks per os?

**Comment by robfrank** [comment]
@erlanghacker I tested this command on linux and mac osx:
ps aux 
does it works on bsd as well?
(note, without minus)

**Comment by erlanghacker** [comment]
on FreeBSD

root k3 $ ps aux | grep orientdb | grep java

orientdb 92737   0.0  2.8 2001956 116956  0- S    Sun08PM     9:12.36
/usr/local/openjdk8/bin/java -server -Xmx512m -Djna.nosys=true -XX:+H


(result on one l one of course)


on OpenBSD


-bash-4.3# ps aux | grep orientdb | grep -v grep

-bash-4.3# ps auxw | grep orientdb | grep -v grep

-bash-4.3# ps auxww | grep orientdb | grep -v grep

root     24761  7.0  6.2 1078008 63580 p0  I      3:01PM    0:06.27 java
-server -Xmx512m -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError
-Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9
-Dprofiler.enabled=true
-Djava.util.logging.config.file=/usr/local/sbin/orientdb/config/orientdb-server-log.properties
-Dorientdb.config.file=/usr/local/sbin/orientdb/config/orientdb-server-config.xml
-Dorientdb.www.path=/usr/local/sbin/orientdb/www
-Dorientdb.build.number=2.1.x@r; 2015-10-29 16:54:25+0000 -cp
/usr/local/sbin/orientdb/lib/orientdb-server-2.1.5.jar:/usr/local/sbin/orientdb/lib/*
com.orientechnologies.orient.server.OServerMain


only the last version worked




On Thu, Nov 12, 2015 at 1:55 PM, Roberto Franchini <notifications@github.com

**Comment by robfrank** [comment]
seems to work on linux and macosx too, I'll modify the script ,test and if all will be ok, push

**Comment by tglman** [comment]
@all

This fail on debian with:
```./gremlin.sh: 32: ./gremlin.sh: Syntax error: Bad for loop variable```

it get fixed if forced to `/bin/bash` (by default debian has /bin/dash)

**Comment by robfrank** [comment]
I just pushed a new gremlin.sh where I get rid of "bashisms" :
https://github.com/orientechnologies/orientdb/commit/9110a95aa722ad53fea687dad020e7b683e6b89a

**Comment by robfrank** [comment]
AFAIK all the scripts are now compatible with BSD.
