### ISSUE TITLE
Hash index being reported as SBTree

### ISSUE THREAD

**Issue by thejjmiller** [orientechnologies/orientdb#5297]
http://localhost:2480/database/{DbName} is returning Hash indexes as SBTree indexes. Is this an actual problem with Hash indexes are not being created problem is is it a problem with the GET API?

```JSON
{
    "name": "idx_test",
    "configuration": {
        "@type": "d",
        "@version": 0,
        "type": "NOTUNIQUE_HASH_INDEX",
        "name": "idx_test",
        "indexVersion": 2,
        "clusters": [],
        "mapRid": "#1:15",
        "algorithm": "SBTREE",
        "valueContainerAlgorithm": "SBTREEBONSAISET",
        "metadata": {
            "@type": "d",
            "@version": 0,
            "durableInNonTxMode": true,
            "trackMode": "FULL"
        }
    }
}
```

**Comment by maggiolo00** [comment]
hi @thejjmiller  
the index is created as Hash not sbtree. 
You can see it by type `NOTUNIQUE_HASH_INDEX`. 
I think is an issue of the api

**Comment by maggiolo00** [comment]
@thejjmiller 

tested in OrientDB 2.2.2 and the issue has been fixed

Thanks
