### ISSUE TITLE
select lock record doesn't work as documented

### ISSUE THREAD

**Issue by grossvater** [orientechnologies/orientdb#5301]
From console 1:

```
begin
select from v where @rid = #9:0 lock record
```

From console 2, the same sequence:

```
begin
select from v where @rid = #9:0 lock record
```

which I expected to block or fail somehow, but this doesn't happen, instead data is returned. I base my expectations on what the documentation says about lock clause in select:

> LOCK manage the locking strategy. By default is "default", that means release the lock > once the record is read, while "record" means to keep the record locked in exclusive > > mode in current transaction till the transaction has been finished by a commit or > rollback operation.

**Comment by maggiolo00** [comment]
@grossvater how did you connect with console?

**Comment by grossvater** [comment]
With remote connection.

**Comment by maggiolo00** [comment]
See here
http://orientdb.com/docs/2.1/Transactions.html#breaking-of-acid-properties-when-using-remote-protocol-and-commands-sql-gremlin-js-etc

**Comment by grossvater** [comment]
Thanks. I understand that `select lock record` doesn't work with remote connections. Anyway, I do not expect it to work with local connections either, because as far as I remember is not allowed to have concurrent local connection to the same database.

**Comment by maggiolo00** [comment]
@grossvater is not allowed to have two differente process/JVM 
opening the same plocal database. But in your app you can use it in plocal if you use JAVA and you can use `select lock record`

You can also use batch SQL to make a transaction that will run on the server
http://orientdb.com/docs/2.1/SQL-batch.html

**Comment by grossvater** [comment]
I know that I can open two connection from the same JVM, but is not my case. What I try to implement here is an exclusive lock, between two different JVM. Is this possible somehow?

**Comment by lvca** [comment]
You could use distributed locks to do that. Example:

```java
Lock lock = OServerMain.server().getDistributedManager().getLock("mydb.record.#9:0");
lock.lock();

try{
  // YOUR CODE
}finally{
  lock.unlock();
}
```

Unlock of locks is on your charge.

**Comment by grossvater** [comment]
Maybe I wasn't very clear, I would like to implement a lock between two clients over remote connections. I can't put the code guarded by the lock inside a server side function, because my logic has to be executed on a remote client. I could create a pair of server side function for lock / unlock and call them from the client, but still this has a problem: if the client crashes before releasing the lock, the lock will be held for ever.

**Comment by grossvater** [comment]
I don't understand why you closed the issue, since I think my initial statement is true. The documentation states something that works only in some contexts, and by reading the documentation about the feature doesn't let me know so.
