### ISSUE TITLE
Batch operator can't be used when deleting using subqueries

### ISSUE THREAD

**Issue by edamico** [orientechnologies/orientdb#5305]
Syntax error is throw when parsing this kind of queries:
DELETE edge e where @rid in (select from e where in.name = "whatever") BATCH 100

**Comment by maggiolo00** [comment]
hi @edamico 
Which version of OrientDB?

**Comment by edamico** [comment]
hi there,
I am using Orientdb 2.1.0 Community on Ubuntu 14.04.


Esteban D'Amico
S: estebandamico | G+: esteban@nan-labs.com
*NaN Labs*
Calle 48 Nº 818, piso 7, La Plata,  Buenos Aires, Argentina
www.nan-labs.com

2015-11-12 8:34 GMT-03:00 Enrico Risa <notifications@github.com>:

**Comment by maggiolo00** [comment]
hi @edamico 
if you remove BATCH ?

**Comment by edamico** [comment]
If I remove the batch it works perfectly!

Esteban D'Amico
S: estebandamico | G+: esteban@nan-labs.com
*NaN Labs*
Calle 48 Nº 818, piso 7, La Plata,  Buenos Aires, Argentina
www.nan-labs.com

2015-11-12 18:37 GMT-03:00 Enrico Risa <notifications@github.com>:
