### ISSUE TITLE
Class diagrams in Studio

### ISSUE THREAD

**Issue by warriorkitty** [orientechnologies/orientdb#5307]
Let's say that I've imported a big database and I have a lot of classes and a big hierarchy tree.
Is there a way I could see the hierarchy easily, something like UML diagram, in Studio?

**Comment by maggiolo00** [comment]
Hi @warriorkitty 

We did have a UML diagram in studio before, but we removed it for security reason because it used a third party service. 
We could implement it in studio using some javascript library like this

http://jointjs.com/demos/umlcd

**Comment by warriorkitty** [comment]
Well, that would be really great. Also, after looking at the library, I don't see the reason why I couldn't try to implement it myself and send a PR if I finish it.

Could you tell me some guidelines for this? I can't find Studio "entry" inside the source.

**Comment by maggiolo00** [comment]
hi @warriorkitty 

you can find the code here
https://github.com/orientechnologies/orientdb-studio

This is a javascript application (bower/grunt/angularjs)

If you are familiar with angular you can try.
You can see the old logic of the UML diagram in
UML.html and UMLController in configuration-controller.js

If you have problem you can ask me

**Comment by warriorkitty** [comment]
Thank you. I'll need some time but I'll try it. :)

**Comment by PhantomYdn** [comment]
There is a built in ability to view UML in [Orienteer](http://orienteer.org). Just check [demo](http://demo.orienteer.org/): select required classes and click "View UML". Service [PlantUML](http://plantuml.com/plantuml/) which can be installed locally as embedded.

**Comment by smolinari** [comment]
@PhantomYdn - looking at the demo, every record view ends in a null pointer exception. The demo is broken.

Scott

**Comment by PhantomYdn** [comment]
Thanks! Demo is open for everyone, so someone changed super-dashboard for all documents. Temporary fixed, but yea: it should not collapse with NPE.

**Comment by smolinari** [comment]
Thanks for the fix. An automated daily reset of the demo database might help avoid that, at least from one day to the next. 

Scott

**Comment by warriorkitty** [comment]
@PhantomYdn Looks great, thank you. I will re-check why it didn't work on my iPad (maybe I just need to clear the cache). Works great in Firefox.

@maggiolo00 I will close this issue for now and I will contact you again if I implement something similar in Studio.

**Comment by lvca** [comment]
I'd like to reopen it, so if @warriorkitty or somebody else want to contribute with such new component, it could go as enhancement under this issue. The basic rule for a component to be quickly accepted by OrientDB team is:
- don't include sw not compatible with Apache2 license
- don't add dependencies unless is very very necessary

**Comment by lvca** [comment]
Nobody worked on this. Not relevant anymore, closing it.

**Comment by PhantomYdn** [comment]
Hello,

We are in Orienteer (http://orienteer.org) are working on some solution for visual modeling of data models. Once our system is working on OrientDB: it can be used also for dedicated modeling as well.
Our module Orienteer-Architect can be found here: https://github.com/OrienteerBAP/Orienteer
Please find some screenshot below.
![orienteerarchitectschema](https://user-images.githubusercontent.com/1199285/28978194-b939c5a6-794d-11e7-9385-36eb7d5a0778.png)
