### ISSUE TITLE
notify user when vertex property is not saved

### ISSUE THREAD

**Issue by deelam** [orientechnologies/orientdb#5308]
Properties with a period are not saved to the graph and no warning/error is produced.  Executing the following code only saves 1 property, when I expect 2 properties to be saved.

```
    Vertex v = graph.addVertex(null);
    v.setProperty("prop1", "val1");
    v.setProperty("prop2.1", "val2");
```

Minimally, a warning should be logged so the user is aware of this.

In order to store property names with a period, I have to call v.setAllowChainedAccess(false) for each applicable vertex.  Is there a way to globally set this to false for all new vertices?

**Comment by lvca** [comment]
Not relevant, closing it.
