### ISSUE TITLE
Rewrite functionality of tracking of changes inside of atomic operation using RoaringBitmaps

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5309]
In order to track changes on pages inside of atomic operation we need some form of implementation of sparse bitset. Typically data structures proposed to be us as sparse bitset use very poor sequential performance for example to check whether n-bit is set we need to use algorithm with O(n) complexity which is unacceptable. Also we can not use plain byte array because it means that in order to change one page in page we need to consume 2 \* page_size bytes and store in WAL page_size bytes for single byte change. That is why we used augmented rb-tree for tracking of changes in one dimensional intervals but this data structure is very resource consuming in case of big transactions and also consumes more space than  RoaringBitmaps implementation.

For details of data structure look at http://arxiv.org/pdf/1402.6407v9.pdf .

**Comment by lvca** [comment]
+1

**Comment by laa** [comment]
Not needed any more
