### ISSUE TITLE
Why is Add Edge 3 times slower than add vertex

### ISSUE THREAD

**Issue by saritseal** [orientechnologies/orientdb#5312]
I am running a massive insert test case. 
My Usecase has Million vertices and equivalent edges. The average degree is 2.

My tests confirm ratio of adding an vertex : edge is almost 1:3

These are not light weight edges

Can some one please let me know why is it? Is this the normal behavior?

**Comment by smolinari** [comment]
I'd say, with my limited knowledge, that yes, it is normal behavior. The reason being, inserting a standard edge means the edge must be created and both vertexes that are linked by the edge must be updated too. So, each edge creation is a transaction of 3 database commands. 

Scott

**Comment by luigidellaquila** [comment]
Hi @saritseal 

the answer Scott gave is right, an edge creation is made of an insert and two updates, this is why it's 3 times slower. We are working to mitigate this problem in next releases.
