### ISSUE TITLE
Out of Memory error when number of edges / vertices are more than 50K in a single transaction

### ISSUE THREAD

**Issue by saritseal** [orientechnologies/orientdb#5313]
I have noticed the Database hangs and eventually throws out of memory error. I saw a post where it was mentioned the server will anticipate oom error and stop incoming transactions and will even roll back. I am using 2.2-alpha. Is this feature not implemented yet

Because of the OOM error the database becomes unusable and has to be restarted. 
As a practice I can limit the number of edge/vertex in a transaction but that is not a break proof. As the same issue may happen if multiple clients start pushing high number of transactions.

**Comment by maggiolo00** [comment]
hi @saritseal 

how much RAM did you give to OrientDB?

**Comment by smolinari** [comment]
@maggiolo00 , for my curiosity, how would one go about giving OrientDB (more) RAM?

Scott

**Comment by maggiolo00** [comment]
hi @smolinari 

in ./server.sh 

there are 2 parameters about memory that you can change

- Heap Memory
- Disk Cache (Off Heap)

By default i OrientDB server is configured with
-Xmx512 of Heap 
that  could be too low for handling 50k records in a single transaction

See here
http://orientdb.com/docs/2.1/Performance-Tuning.html#memory-settings

**Comment by smolinari** [comment]
:+1: Thanks @maggiolo00. 

Scott

**Comment by saritseal** [comment]
5GB

**Comment by saritseal** [comment]
The issue should not be solved by adding heap space. Since it is a server and will have to cater for different workloads from concurrent consumers it should implement a throttler.

**Comment by laa** [comment]
We consider to implement a throttler in future versions of ODB, but for now, we are going to keep tx log in memory.
