### ISSUE TITLE
problems working with eval()

### ISSUE THREAD

**Issue by pawlrus** [orientechnologies/orientdb#5315]
I had a query that was using eval() to do calculations inside of the query to sort the results that was something like 
```
select last(inE("SharedBy").dateShared) as dateShared, in().size() as edgecount, eval('edgecount * 100') as edgescore, eval('date() - dateShared') as datescore, eval('edgescore / datescore') as finalscore from V order by finalscore desc, datescore desc, edgescore desc
```
This was working in 2.0.x, but as of 2.1.x I only see edgecount and datescore returned and datescore is the value of `date()`. I've been able to get edgescore by using `eval('in("edgeTo").size() * 100)`, but `eval('date() - last(inE("SharedBy").dateShared)')` still returns the value of `date()`.

**Comment by lvca** [comment]
Try using `$current.dateShared` or use LET statement to create variables you can then refer with $<var>
