### ISSUE TITLE
Dynamic Hooks & Inheritance

### ISSUE THREAD

**Issue by devspacenine** [orientechnologies/orientdb#5316]
I think this is a mix of an issue and a feature request for 2.2. I'm still learning about how OrientDB works, so hopefully I'm just missing something in the documentation.

I have an abstract class, `BaseVertex`, that extends `V` and `OTriggered`, with 2 columns: `_created`, `_modified`.

```sql
CREATE CLASS BaseVertex Extends V, OTriggered ABSTRACT;

CREATE PROPERTY BaseVertex._created DATETIME;

CREATE PROPERTY BaseVertex._modified DATETIME;
```

I then create dynamic hooks for `onAfterCreate` and `onAfterUpdate` to change the values of the `_created` and `_modified` field.

```sql
CREATE FUNCTION updateCreated "doc.field('_created', new Date().getTime()); doc.save(); return;" LANGUAGE Javascript;

CREATE FUNCTION updateModified "doc.field('_modified', new Date().getTime()); doc.save().return;" LANGUAGE Javascript;

ALTER CLASS BaseVertex CUSTOM onAfterCreate=updateCreated;

ALTER CLASS BaseVertex CUSTOM onAfterUpdate=updateModified;
```

Next, I create a class, `Company`, that extends 'BaseVertex' and create a dynamic hook to alter some field after update.

```sql
CREATE CLASS Company EXTENDS BaseVertex;

CREATE FUNCTION testUpdate "doc.field('test', 'test'); doc.save(); return;" LANGUAGE Javascript;

ALTER CLASS Company CUSTOM onAfterUpdate=testUpdate;
```

Finally, I create a 'Company' vertex then update an arbitrary field a few seconds later.

```sql
CREATE VERTEX Company;

/* wait a few seconds */
UPDATE <someRID> SET name = 'Test Company';
```

**What I expect to happen**: A `Company` vertex is initially created with `_created` and `_modified` set to similar values. After updating the `Company` document, the `name` field is set to "Test Company", the `test` field is set to "test", and the `_modified` field is now a few seconds later than the `_created` field.

**What actually happens**: A `Company` vertex is initially create with `_created` and `_modified` set to similar values. After updating the `Company` document, the `name` field is set to "Test Company", the `test` field is set to "test", and the `_modified` field is unchanged.

It seems that the abstract class' *onAfterCreate* and *onAfterUpdate* hooks are only called if a child class does not have it's own *onAfterCreate* or *onAfterUpdate* hooks. If I were to add a *onAfterCreate* hook to the `Company` class, the base class' hooks would never be called.

**Comment by lvca** [comment]
I think if you override an hook, the base class hook is not called. You can call the base callback explicitly in the sub class hook. Example:

    updateModified (); doc.field('test', 'test'); doc.save(); return;

Furthermore why implementing an afterUpdate with an additional save() when you could implement just beforeUpdate and let to OrientDB to execute the final save?

**Comment by devspacenine** [comment]
Yes, its an easy problem to get around, but when you are working with a large team you can't expect everyone to know that there was a hook function on a parent class. A large project would be less error prone if subclasses' hooks appended to their parent's hooks.

As far as the `save()`, this isn't how my code is actually structured. I definitely don't have a hook for a created field. I would use a DEFAULT value. I was just trying to reproduce the issue at the most basic level, but I see the inefficiency there now.

**Comment by devspacenine** [comment]
On a side note: if we buy the enterprise edition, is there some extra documentation we could get to supplement the documentation that is publicly available? There is a lot missing in the open source documentation.

**Comment by lvca** [comment]
This is how works inheritance almost everywhere. If you redefine a method you redefine it and it's your responsibility calling super.<method>(). Furthermore if you had a chain of class what should be the order of calling? Sometimes you want to call the super method at the beginning, sometimes at the end, sometimes you don't want.

About the Enterprise Edition (EE), the documentation is the same, but you have a private channel (private chat, private issues, hot fix, etc) with OrientDB team.
