### ISSUE TITLE
create graph database through orientdb-server-config.xml

### ISSUE THREAD

**Issue by hsjjo** [orientechnologies/orientdb#5319]
I want to create graph type database with the start of the orientdb.

In orientdb-server-config.xml, I added the
<storage name="blahblah" path="memory:blahblah" userName="admin" userPassword="admin" loaded-at-startup="true"/>

But, the created database is always document type db.

Is there any way to create graph db through editting the xml file such as <storage name="" dbType="graph">

Thanks in advance.

**Comment by maggiolo00** [comment]
hi @hsjjo 

What version of OrientDB?

**Comment by hsjjo** [comment]
I'm using orientdb 2.1.5 version.

Thanks in advance.

**Comment by lvca** [comment]
How do you know the db is "document"?

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
