### ISSUE TITLE
Java NullPointerException in Profiler (Studio)

### ISSUE THREAD

**Issue by warriorkitty** [orientechnologies/orientdb#5320]
In Studio:
1.) create a new database
2.) go to Profiler link

You will get this:
![Screenshot](http://s10.postimg.org/aabv0ldmh/2015_11_14_1447529864_1366x768_scrot.png "Screenshot")

**Comment by maggiolo00** [comment]
@warriorkitty 

try to login with admin:admin

**Comment by warriorkitty** [comment]
It works with admin/admin.

**Comment by maggiolo00** [comment]
hi @warriorkitty 

from 2.1.8 it is fixed also with root:root

have you tried it?

**Comment by maggiolo00** [comment]
Fixed

https://github.com/orientechnologies/orientdb/issues/4932
