### ISSUE TITLE
Can't find split function inside ETL

### ISSUE THREAD

**Issue by warriorkitty** [orientechnologies/orientdb#5321]
I'm trying to import a MovieLens database with ETL. There is a solution provided here:

http://pizzaconnections.net/2015/03/27/148/

The line:

````{ "field": { "fieldName": "genresArray", "expression": "split(genres,'|')"} },````

can't find a function split (I'm getting an exception), even though I've created it through Studio. I've created both the JavaScript version and the SQL version.

I also tried ```eval()``` but without luck.

[#2573](https://github.com/orientechnologies/orientdb/issues/2573) Here I saw that you will implement a 'native' split function. Is it implemented maybe? I can't find it.

I think it's worth mentioning that I managed to call the created function inside Studio but not from "expression" ETL.

**Comment by lvca** [comment]
split is a method, so you can call it against a string. Try with:

    { "field": { "fieldName": "genresArray", "expression": "genres.split('|')"} },

**Comment by lvca** [comment]
Sorry, split() is on another branch for 2.2, so it's not supported so far.

**Comment by lvca** [comment]
Now split() method is on the develop branch.

**Comment by warriorkitty** [comment]
OK, great, thank you! :)
