### ISSUE TITLE
blueprints.orientdb.lightweightEdges is false by default

### ISSUE THREAD

**Issue by fommil** [orientechnologies/orientdb#5322]
docs say it should be true by default http://orientdb.com/docs/last/Graph-Database-Tinkerpop.html#using-indices

https://github.com/orientechnologies/orientdb/blob/master/graphdb/src/main/java/com/tinkerpop/blueprints/impls/orient/OrientConfigurableGraph.java#L35

**Comment by lvca** [comment]
Thanks, fixed.
