### ISSUE TITLE
@CLASS does not get populated when creating classes using java api

### ISSUE THREAD

**Issue by saritseal** [orientechnologies/orientdb#5323]
Hi,

I have created class using the class: attribute in the addVertex and addEdge. The classes gets created and can query the vertices and edges using the class from the console. However the  @CLASS column is not populated in the E and V class.

**Comment by saritseal** [comment]
If the class is created via sql then the @CLASS field gets populated

**Comment by lvca** [comment]
Could you please attach a screenshot of console session?

**Comment by saritseal** [comment]
Hi,

Do you want any more info?

Regards
Sarit

**Comment by lvca** [comment]
Could you please attach a screenshot of console session?
