### ISSUE TITLE
AddVertex and AddEdge hiding class name, cluster name and id

### ISSUE THREAD

**Issue by saritseal** [orientechnologies/orientdb#5327]
The api to add Vertex and edge has the parameter id. However it is not evident that you can pass the class name, cluster name and id

the documentation is : 

addEdge
id - Optional, can contains the Edge's class name by prefixing with "class:"

addVertex
id - Optional, can contains the Edge's class name by prefixing with "class:".

Another issue with the documentation is in the addVertex it states the class is the edge's class not the vertex's class

**Comment by lvca** [comment]
When you say "documentation", what do you mean?

**Comment by lvca** [comment]
@santo-it please can you check this on docs?
