### ISSUE TITLE
Drop database but preserve files on disk

### ISSUE THREAD

**Issue by grossvater** [orientechnologies/orientdb#5328]
There is a way to achieve this?

**Comment by laa** [comment]
What do you mean, database is files on the disk and nothing more.

**Comment by grossvater** [comment]
Detach, unregister, but do not delete, that's it, a way to tell the server forget about this database.

**Comment by smolinari** [comment]
How about just moving the related database files out of the source directory? Wouldn't that work?

Scott

**Comment by grossvater** [comment]
@smolinari I need to detach while the server is running

I'll try to explain my scenario:
- I have a relative big database (~20G) that I want to update
- since using remote connections proved to be slow and sometimes causes out of memory when the transaction is big, I decided to update the database via a local connection
- to achieve this, I need a way to tell the server to somehow release the database (drop is not working here since it deletes the files).
- stopping the server is also not an option, because the update must be "live", being part of the normal functioning, not a maintenance procedure
- besides that, I would like to keep the files in the same physical location during update, avoiding thus to copy / move 20G.

**Comment by smolinari** [comment]
Ah, ok. Now your requirements are a bit clearer.

What is is the current version of your database and to what new version do you want to upgrade to?

Usually, if the version numbers aren't too far apart, the update process is through a drop in process and is pretty quick to do. Theoretically, you could do it within seconds. However, you still have to stop the server for that time to do it. 

I think the only way you can hot-swap upgrade is with a distributed system, which means, you need extra nodes with the data, which means copying the data. 

I am not that experienced with ODB, so don't take my word for it either. Maybe @laa can also give you some tips.

Scott

**Comment by grossvater** [comment]
@smolinari update != upgrade, but update = massive delete, insert, update

I run community edition v2.1.5.

**Comment by grossvater** [comment]
Meanwhile I try myself to find an workaround by freezing the database, hard linking all the files into another (snapshot) directory, then drop the database. At the end of the process I expect to find the files intact into snapshot directory, but this doesn't happen, it seems that before dropping the database, the server truncates some files, which obviously affects the hard linked files.

The lines to be blamed seems to be inside `com.orientechnologies.orient.core.storage.cache.local`:

```
  private String doDeleteFile(int fileId) throws IOException {
    if (isOpen(fileId)) {
        truncateFile(fileId);
    }
    ...
 }
```

**Comment by smolinari** [comment]
Ah, yes. Sorry about that. Totally misunderstood. 

Have you tried doing the updates with batch?

http://orientdb.com/docs/2.1/SQL-batch.html

What was "slow" or rather, what is the timing you consider to be slow? What was it you did exactly?

Scott

**Comment by grossvater** [comment]
@smolinari Slow = hours I think
We didn't try with the batch because we apply some logic written in java during the update. Of course, theoretically, based on that logic we might try to generate sql statements to run in batch, but our code is not prepared for this yet:)

**Comment by nagarajasr** [comment]
i don't know if this would actually work, but you could try something like this.

looking through the code of ODatabaseHelper:

```java
  public static void freezeDatabase(final ODatabase database) throws IOException {
    database.activateOnCurrentThread();
    if (database.getURL().startsWith("remote")) {
      final OServerAdmin serverAdmin = new OServerAdmin(database.getURL());
      serverAdmin.connect("root", getServerRootPassword()).freezeDatabase("plocal");
      serverAdmin.close();
    } else {
      database.freeze();
    }
  }

```

it appears that it is possible to put the database from remote to plocal mode (but within the process space of the server). maybe you could try your massive update from within the server process itself?
it could be possible to write a server side function that wraps your massive update operation within a freeze/ release operation.

**Comment by grossvater** [comment]
@nagarajasr I thought about running the update from the server itself (this practically means embedding the server, doesn't it?) but I didn't go for this because:
- if something goes wrong with update, the server will be affected, since they are in the same JVM
- not scalable (multiple updates might occur on different databases on the same server)

The method described at [above](#issuecomment-157364553) seems to work, excepting the problem with files truncated.

Anyway, I feel this is a hack and I would like to adopt an "official" way to do it...

**Comment by lvca** [comment]
You could also create a [Server Plugin](http://orientdb.com/docs/last/Extend-Server.html) by implementing an interface and deploy the jar under `lib` folder of OrientDB distribution. From your plugin you are able to open the database using "plocal" and OrientDB Server will synchronize access from remote connection too.
