### ISSUE TITLE
Automatic Backup: move configuration to backup.json

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5329]

**Comment by lvca** [comment]
Missing only documentation.

**Comment by lvca** [comment]
Missing the documentation, but waiting for the docs refactoring by @smolinari.

**Comment by smolinari** [comment]
Oh, now you're putting pressure on me? LOL! Ok. No problem. I like pressure. :smile: 

Scott

**Comment by lvca** [comment]
:-)

**Comment by lvca** [comment]
Done: https://github.com/orientechnologies/orientdb-docs/blob/master/Automatic-Backup.md

**Comment by smolinari** [comment]
I've added the additions to the docs in the refactoring too.

Scott

**Comment by lvca** [comment]
Thanks.
