### ISSUE TITLE
index for in/out property in edge

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5334]
how to create index for in/out property that is auto created in any edge?

**Comment by nagarajasr** [comment]
you must explicitly declare the in and out schema full properties of the edge class and define indexes on it.

**Comment by martingg88** [comment]
can i define them (in/out) E parent class for all the edges?

**Comment by nagarajasr** [comment]
yes. however be careful if you are defining unique indexes. if you need to define two different types of edges between the same 2 vertices and the index is unique on (in,out) you will only be allowed to create one edge as the second edge will throw a unique constraint violation.

**Comment by martingg88** [comment]
how about this case. 

1. create non-unique index (in/out) for E parent class.
 
2. create unique index (in/out) for edge's sub-class in case i need that unique . 

the index at sub-class will overwrite any same index at E parent class?

**Comment by martingg88** [comment]
will have this warning message after create in/out properties at E parent class

2015-11-17 21:36:32:132 WARNI {db=hotel} Found property in/out against E [orientechnologies]

**Comment by lvca** [comment]
You cannot call a property `in/out`

**Comment by martingg88** [comment]
i dun have such warning if i create in/out index for sub-class
