### ISSUE TITLE
shutdown.sh must work with PID+signals

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5335]
Now the password are not in clear, we need to change shutdown.sh to send a signal to the server process in case no password is provided. So when the server.sh starts, a PID file must be written.

The current alternative to get the password as parameter must stay there too.

**Comment by robfrank** [comment]
Well, this will solve on *nix systems. How to deal on win? any idea?

**Comment by lvca** [comment]
Try to see Tomcat or other Java app how they do that.

**Comment by robfrank** [comment]
I fixed the shutdown on java side.
handling the pid is another story and it is feasible only on linux, IMHO.

**Comment by lvca** [comment]
I think the impl. must be reviewed.

**Comment by robfrank** [comment]
just pushed
server.sh saves the pid file in the orientdb home
shutdown.sh has two different behaviour
- shutdown.sh without params, check for pid file and if found it simply send a kill -15
- if params are passed, calls OshutdownMain

Params are no more positional:

shutdown.sh -h host -P 2424 -u root -p hello

or 

shutdown.sh --host host --ports 2424 --user root --password hello

default value are:
- host: localhost
- ports: 2424-2430
- user: root

**Comment by lvca** [comment]
Cool.
