### ISSUE TITLE
'from' property name  gives exception 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5337]
Hi, create property A.from Link B 

 Encountered " <FROM> "from "" at line 1, column 36.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <NULL> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...

I think thge problem is for all the keywords
In the while ... i ll change property name :)

**Comment by lvca** [comment]
Dot is not allowed in property names.

**Comment by nagarajasr** [comment]
seems to work for me...
```sql
create property A.from link B
```

i'm using orientdb-community-2.1.1.
@publicocean0 What version are you on?

**Comment by publicocean0** [comment]
my version is v2.1-rc2

**Comment by lvca** [comment]
@publicocean0 never use a RC when the stable is out ;-)

**Comment by publicocean0** [comment]
I confirmed , in 2.1.6 all is working
