### ISSUE TITLE
Create "zery copy" methods on OFile interface

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5343]
Now to read data from/write data to file we copy whole data content to byte array from direct memory pages that is really huge overhead taking in account size of page which is 64Kb. But FileChannel supports "zero copy" approach for such kind of cases, it is implemented using methods java.nio.channels.FileChannel#transferFrom and java.nio.channels.FileChannel#transferTo also according to documentation it supports DMA approach which makes execution of such operations (I mean write to/read from) much faster.

**Comment by lvca** [comment]
+100

**Comment by laa** [comment]
Usage of directbytebuffer pool is the best in such case. But we use Unsafe instead. I tried to compare performance of our wrapper of direct memory access and bytebuffer https://gist.github.com/laa/c2f8ef04d59e38ed2bb8 and 

And got following difference:
[Write         3.553797 ms, Read         5.295604 ms, Rand Read        20.823296 ms], Op/Sec(Millions)[Write   1406, Read    944, Rand Read    240]

[Write        19.108641 ms, Read        28.922183 ms, Rand Read       100.587527 ms], Op/Sec(Millions)[Write    261, Read    172, Rand Read     49]

Which makes direcmemorybuffer 5 times faster. Let's try and check how it will behave in reality.

**Comment by machak** [comment]
https://github.com/real-logic/Agrona is doing a lot in this area, might be worth checking, e.g.
http://insightfullogic.com/2015/Apr/18/agronas-threadsafe-offheap-buffers/

**Comment by laa** [comment]
Hi Luca ,
If you look at project requirement you will find that they need Oracle JDK
because they rely on internals of byte buffer implementation , it   not
possible for us. Also their claims that CAS operations are not allowed on
direct byte buffer are not completely true,  Java 9 supports cas operations
on byte buffers . Also at the moment we do not have needs to use cas
operations on direct memory and IMHO till Java 9 we will not need them.


вт, 5 Янв 2016, 8:22, marijan milicevic <notifications@github.com>:

> https://github.com/real-logic/Agrona is doing a lot in this area, might
> be worth checking, e.g.
> http://insightfullogic.com/2015/Apr/18/agronas-threadsafe-offheap-buffers/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5343#issuecomment-168914872>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by laa** [comment]
Fixed with good results.
