### ISSUE TITLE
Fetchplan on EmbeddedList doesn't work

### ISSUE THREAD

**Issue by AndreaSpan** [orientechnologies/orientdb#5344]
Hi, 

I have a class with a property of type EmbeddedList which contains 2 links properties .
When I'm trying to fetchplan on these property, it doesn't work.

Is fetchplan on EmbeddedList unsupported by orientdb? 

The query : 

`SELECT @this.toJSON('fetchPlan:myEmbeddedListProperty:2') FROM myClass`

The query doesn't send any error but doesn't expand my results.

Thanks!

**Comment by lolo88l** [comment]
Hi,

I have the same problem too... Someone found a solution ?

Thanks
