### ISSUE TITLE
OrientDB 2.1.5: composite key index not valid after delete

### ISSUE THREAD

**Issue by doppelrittberger** [orientechnologies/orientdb#5348]
Hi,

I have the following structure:

Class Client
- List<User> users

Class User
- Client client
- String name

Now I add an unique index onto the User class using a composite key "client"-"name" (CREATE INDEX users-client-name ON User (client, name) UNIQUE). Now I add data and sometimes I add users that do not have a client (resulting in a OCompositeKey{keys=[null, my-name]}). If I now drop the whole database (DELETE FROM Entity -> User and Client are subclasses of Entity), the index remains in a invalid state. All composite keys which have null as client (like OCompositeKey{keys=[null, my-name]})  remain in the index (SELECT FROM Index:users-client-name) and cause errors if I now re-create data. I would expect that the index is completely empty after deleting all instances.

Thanks in advance

**Comment by doppelrittberger** [comment]
One addition: it seems that there is a more general issue with composite keys since even if I change the users client from null to some existing client the index keeps the null-based-key (OCompositeKey{keys=[null, my-name]}), which is incorrect.

**Comment by taburet** [comment]
@doppelrittberger sorry for being so delayed on issue. I have tested nulls in composite keys on different versions and found that [`ignoreNullValues = false`](http://orientdb.com/docs/last/Indexes.html#indexes-and-null-values) index option fixes the problem. Please verify this resolves your problem, if it still actual.

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
