### ISSUE TITLE
Move basic graph concepts in Core module

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#5349]
OrientDB is a multi-model database, but in the Core module there is no concept of graph concepts, even though all the components are there to manage graph data.

Graph module is currently separated from Core just to avoid to constrain Core to all the dependencies required by TinkerPop.

We should move basic graph concepts in Core module, implement TinkerPop stack as a layer on top of them and rename current Graph module in TinkerPop2.

This way we will also be able to have two different TinkerPop implementations (2.x and 3) that rely on the same low level graph components.

**Comment by lvca** [comment]
:+1

**Comment by maggiolo00** [comment]
+1

**Comment by PhantomYdn** [comment]
-1
Graph support require >20Mb in WAR. It's heavily redundant if only document functionality is required.
Please do not get everything into core...

**Comment by lvca** [comment]
The idea is to move only the basic concepts, not Blueprints for this reason.

**Comment by lvca** [comment]
Done and available in v3.0-M2.
