### ISSUE TITLE
What are the best practices with refreshing the indexes we have a lucene index that supports search functionality and it seems the index needs to manually be rebuilt now to make sure its up to date.  Or is there something with the way we constructed it?

### ISSUE THREAD

**Issue by fcbits** [orientechnologies/orientdb#5350]

**Comment by maggiolo00** [comment]
hi @fcbits 


how did you create the lucene index?

You shouldn't rebuild it. It should remain updated.

**Comment by fcbits** [comment]
here is what it says in select expand(indexes) from metadata:indexmanager on this index.  [unless there is a better way to get this since one of my colleagues created it]
hopefully this is actually readable.

FulltextQuestionSearchText
1
{"@type":"d","@version":0,"className":"question","indexDefinitions":[{"@type":"d","@version":0,"className":"question","field":"searchText","keyType":"STRING","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"question","field":"categoriesText","keyType":"STRING","collate":"default","nullValuesIgnored":true},{"@type":"d","@version":0,"className":"question","field":"tagsText","keyType":"STRING","collate":"default","nullValuesIgnored":true}],"indClasses":["com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition","com.orientechnologies.orient.core.index.OPropertyIndexDefinition"],"nullValuesIgnored":true}
FULLTEXT
["question"]
LUCENE
SBTREEBONSAISET
com.orientechnologies.orient.core.index.OCompositeIndexDefinition

**Comment by barabaszsolt** [comment]
This is the index create command:
CREATE INDEX FulltextQuestionSearchText ON question (searchText,categoriesText,tagsText) FULLTEXT  ENGINE LUCENE;

We run the query in it:
SELECT * from question [searchText,categoriesText,tagsText] LUCENE "(searchText:' + filter + ' OR categoriesText:' + catName + ' OR tagsText: ' + tagName +')"

**Comment by maggiolo00** [comment]
hi @barabaszsolt 

how did you experience the problem. 
Can i reproduce it ?

**Comment by maggiolo00** [comment]
hi @barabaszsolt 

how can i reproduce it?

**Comment by barabaszsolt** [comment]
Hi, as you can see in the prev comment we are indexing questions text.
Simply sometimes we don't get results for specific words and after rebuilding the indexes, it works again the question search.

**Comment by maggiolo00** [comment]
hi @barabaszsolt 

is still happening with 2.1.16?

**Comment by barabaszsolt** [comment]
@maggiolo00 you can close this. We don't use LUCENE index anymore for question search.
