### ISSUE TITLE
sql select from two classes with lucene indices fails

### ISSUE THREAD

**Issue by arisAlexis** [orientechnologies/orientdb#5354]
this works:

SELECT FROM V WHERE (@class='Post' AND body lucene 'china') OR (@class='Question' AND title like '%usa%')

and this fails

SELECT FROM V WHERE (@class='Post' AND body lucene 'china') OR (@class='Question' AND title lucene 'usa')

with error
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Incompatible conditions found: body LUCENE 'china' title LUCENE 'usa' 

It may be related to #5332 

I am trying to do pagination here and that's the best I came up with. any other ideas welcome

**Comment by maggiolo00** [comment]
@arisAlexis yes it is be related with #5332

you could try to select from multiple targets

http://orientdb.com/docs/2.1/SQL.html#select-from-multiple-targets

```SQL
SELECT EXPAND( $c ) 
LET $a = ( SELECT FROM Post WHERE  body lucene 'china' ), 
$b = ( SELECT FROM Question where title lucene 'usa' ), 
$c = UNIONALL( $a, $b )
```

**Comment by arisAlexis** [comment]
yes it works thank you.
