### ISSUE TITLE
Problems with live queries

### ISSUE THREAD

**Issue by voondo** [orientechnologies/orientdb#5356]
(latest 2.2 snapshot)

I get this error when trying to unsubscribe from a livequery : `Cannot find a command executor for the command request: sql.live unsubscribe 1948327128`

And my listener don't receive any event...

Miss I something ?

**Comment by luigidellaquila** [comment]
HI @voondo 

this is a quite old issue, is it still valid? In 2.2 as far as i know the unsubscribe is correctly supported.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @voondo 

I'm closing this issue, it should be already fixed. Please reopen if you still see the problem

Thanks

Luigi
