### ISSUE TITLE
[develop] annoying dependancy to orientdb-client from orientdb-graphdb

### ISSUE THREAD

**Issue by nlavan** [orientechnologies/orientdb#5358]
In the following commit, 492e2da85681462a50aa3e2b82bc2bf52307ff65 , @lvca introduced a dependency from OrientConfigurableGraph (orientdb-graphdb) to the enum OStorageRemote.CONNECTION_STRATEGY (orientdb-client). 

for users who have a restricted set of artifacts included in their pom (by exemple only core and graphdb for plocal databases without server and without even connections to remote databases)

the problematic file is:
graphdb/src/main/java/com/tinkerpop/blueprints/impls/orient/OrientConfigurableGraph.java

This breaks the atomicity of the java packages.
Thanks for finding another way to use the enum.

**Comment by nlavan** [comment]
thanks for taking the ticket into account @lvca ! Is there another channel of communication for the develop branch or here is the place?

**Comment by luigidellaquila** [comment]
Hi @nlavan 

This is definitely the right place, we are evaluating this problem and we'll let you know soon

Thanks

Luigi

**Comment by lvca** [comment]
Done. Now it accepts a string to be completely decoupled.
