### ISSUE TITLE
Second level chained path functions ingore multiple class/labels parameters

### ISSUE THREAD

**Issue by a-unite** [orientechnologies/orientdb#5359]
Version 2.1.x

Examples for _"Tolkien-Arda"_ database:
`select outE().in.outE( ) from #11:2` gives us 6 edges of two classes (_LOVES_ and _BEGETS_).
The same amount of corresponding vetexes are returned for `select out().out() from #11:2`.

For `select outE().in.outE(`**`'LOVES'`**`) from #11:2` we have one edge,
for `select outE().in.outE(`**`'BEGETS'`**`) from #11:2` there are five edges.
Both results are right and this gives us 6 edges in total.

But for `select outE().in.outE(`**`'LOVES', 'BEGETS'`**`) from #11:2` we have only one edge of class _LOVES_, instead of 6 (this query is equivalent to `select outE().in.outE() from #11:2`).
While for `select outE().in.outE(`**`'BEGETS','LOVES'`**`) from #11:2` we have only five.

**Only the first parameter of deep chained path function is used for filtering.**

The same situation is with `.out([<label-1>][,<label-n>]*)`, `.in(out([<label-1>][,<label-n>]*)` and `.inE([<label-1>][,<label-n>]*)` chained functions.

**Comment by a-unite** [comment]
@luigidellaquila I hope this issue could also be fixed easily in parser, and not related to something fundamental.

**Comment by luigidellaquila** [comment]
Hi @a-unite 

I fixed it in 2.1.x branch, now I'm porting the fix to develop branch

Thanks

Luigi

**Comment by a-unite** [comment]
@luigidellaquila ,

Thank you very much!

Ata

**Comment by luigidellaquila** [comment]
Hi @a-unite 

I pushed fix and test cases on the active branches. 
I'm closing it, please reopen in case you experience other problems

Thanks

Luigi
