### ISSUE TITLE
Opening new database connection can be real slow

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5362]
We experience that whenenever we open a new connection to the database, this is really slow. It is especially a problem when multiple connections are being made at the same time, then it seems as if our app totally freezes.

I tried to find the problem within our code, but it turned out openDatabase was waiting for a long time, so I attached a profiler (yourkit) to the server to see what was happening whenever the slowness occurs and it looks like it is in the openDatabase code where it initializes schema information. As we have a lot of classes, it makes sense that this is the culprit. I'll attach screenshots from yourkit.

**Comment by wouterv** [comment]
![image](https://cloud.githubusercontent.com/assets/616997/11333973/07a32a62-91d2-11e5-8f44-4be3f22ee5ef.png)

![image](https://cloud.githubusercontent.com/assets/616997/11333980/1ae52b70-91d2-11e5-85d4-ac60a38d8e86.png)

![image](https://cloud.githubusercontent.com/assets/616997/11333990/2b00f23c-91d2-11e5-89ff-fc2dcbe9720b.png)

**Comment by laa** [comment]
Hi ,
Do not you try to use connection pool ?

On Mon, Nov 23, 2015, 12:05 Wouter de Vaal <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/616997/11333973/07a32a62-91d2-11e5-8f44-4be3f22ee5ef.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/616997/11333980/1ae52b70-91d2-11e5-85d4-ac60a38d8e86.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/616997/11333990/2b00f23c-91d2-11e5-89ff-fc2dcbe9720b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5362#issuecomment-158893076>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by wouterv** [comment]
Yes, but this still means that a fresh connection is slow when it retrieves it, i.e. when the pool is not full.

**Comment by laa** [comment]
Sorry I do not get it .
Do you mean when pool is empty ?
You may increase number of instances then , they are very lightweight ,
almost all information is shared between them .

On Mon, Nov 23, 2015, 14:01 luigidellaquila <notifications@github.com>
wrote:

> Assigned #5362 <https://github.com/orientechnologies/orientdb/issues/5362>
> to @laa <https://github.com/laa>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5362#event-471966590>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by wouterv** [comment]
How can it be than that when I profile orient server, I see the above slowness each time it opens a connection? 
IMHO opening a connection should be fast, and the only overhead should be network, now the orient server is the bottleneck, because it needs to fill a new OImmutableSchema instance for each connection opened. Shouldn't that be cached or something.

**Comment by laa** [comment]
It may be cached on client side if you would now before head that nothing
is changed on server side between old and new connection and client can not
know this.

But why setting of pool with high capacity can not solve your problem ?

On Mon, Nov 23, 2015 at 3:46 PM Wouter de Vaal <notifications@github.com>
wrote:

> How can it be than that when I profile orient server, I see the above
> slowness each time it opens a connection?
> IMHO opening a connection should be fast, and the only overhead should be
> network, now the orient server is the bottleneck, because it needs to fill
> a new OImmutableSchema instance for each connection opened. Shouldn't that
> be cached or something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5362#issuecomment-158936581>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by wouterv** [comment]
I will probably solve some of our issues yes, we are trying that out.

However I still believe getting a connection should be much faster and I ask if it can be looked into to make it snappy instead so very slow as it is now.

**Comment by lvca** [comment]
The problem was on the open in distributed storage that caused an invalidation of the schema, therefore the generation of immutable of schema every time. Fixed. Please let me know if you still see such slow downs on db.open(), otherwise please close it.

**Comment by wouterv** [comment]
I'm not seeing a commit attached to this issue, was it already pushed?

**Comment by lvca** [comment]
This is the fix: https://github.com/orientechnologies/orientdb/commit/4dc081f39942994940ed4aed600b0d9e0af0fdba

**Comment by lvca** [comment]
Tested and works. Closed the issue while I'm releasing 2.1.6.
