### ISSUE TITLE
Opening odb connection for the first time is extremely slow, it reloads the schema for every class with registering

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5365]
The first time an object db connection is opened, orient loops through all classes and registers them, which is fine, but with each registry, it reloads the schema (which is slow), making the first connection via odb extremely slow, it is so bad our application refuses to startup due to a timeout.

See screenshot in next comment.

**Comment by wouterv** [comment]
![image](https://cloud.githubusercontent.com/assets/616997/11340412/14bce338-91fe-11e5-8776-6461049088ff.png)

**Comment by wouterv** [comment]
Here's some more evidence, I enabled tracing and you see that indeed for each class it reloads the schema, which is very, very slow.

![image](https://cloud.githubusercontent.com/assets/616997/11340790/e7e041d2-91ff-11e5-8f99-acad652991fc.png)

**Comment by lvca** [comment]
After the first open everything is fast?

**Comment by wouterv** [comment]
Yep

**Comment by lvca** [comment]
I think it's normal considering the first open as startup time. Your application should become ready once it opened the database and execute some initial operations I guess.

**Comment by wouterv** [comment]
I don't agree. If you just look at the detail, it does an overkill of schema reloading, which is totally unnecessary and a big waste of time.

**Comment by wouterv** [comment]
Created a pull request for this: https://github.com/orientechnologies/orientdb/pull/5906
