### ISSUE TITLE
OCommandSQL.execute() with named JSON parameter

### ISSUE THREAD

**Issue by daniellawry** [orientechnologies/orientdb#5366]
I'm using the OrientDB Java API for an upsert in one of my service API calls. I have two code examples that I believe should do exactly the same thing, but one is throwing an exception.

In both code examples I'm using the OCommandSQL class with an OrientGraph and calling the "execute" method using a `Map<String, Object>`. When I use the JSON String as a named variable in the Map, the command fails. When I simply append the JSON string to the actual command, the command passes.

Example 1: Parameterizing the SQL command using a named JSON variable as a String in a `Map<String, Object>` - This method fails with the message "com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content ':user': content must be between { }"

```
	public void persistUsers(@Param("users") Set<IUser> users) {
		OrientGraph graph = getGraph();
		if (graph != null && users != null && !users.isEmpty()) {
			for (IUser user : users) {
				if (user.getId() != null) {
					String command = "UPDATE User CONTENT :user UPSERT WHERE id = :userId";
					Map<String, Object> queryParams = new HashMap<String, Object>();
					queryParams.put("user", JsonUtil.userToJson(user));
					queryParams.put("userId", user.getId().toString());
					graph.command(new OCommandSQL(command)).execute(queryParams);
				}
			}
			graph.shutdown();
		}
	}
```

Example 2: String appending the JSON string to the SQL command - This method succeeds and correctly inserts the User record

```
	public void persistUsers(@Param("users") Set<IUser> users) {
		OrientGraph graph = getGraph();
		if (graph != null && users != null && !users.isEmpty()) {
			for (IUser user : users) {
				if (user.getId() != null) {
					String command = "UPDATE User CONTENT " + JsonUtil.userToJson(user) + " UPSERT WHERE id = :userId";
					Map<String, Object> queryParams = new HashMap<String, Object>();
					queryParams.put("userId", user.getId().toString());
					graph.command(new OCommandSQL(command)).execute(queryParams);
				}
			}
			graph.shutdown();
		}
	}
```

Here is the value of JsonUtil.userToJson(user):

`{"@class":"User","email":"systemUser@test.com","encryptedPassword":"XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=","firstName":"Non-System","id":"16a147a4-4582-4073-af64-5b62150d6286","lastName":"User","username":"systemUser"}`

Is there something wrong with my use of the API or is this potentially an issue that needs correction?

Thanks

**Comment by daniellawry** [comment]
FYI, this was with OrientDB version 2.1.2

**Comment by urugator** [comment]
Related?
https://github.com/orientechnologies/orientdb/issues/5045
