### ISSUE TITLE
UPSERTing from the Java API

### ISSUE THREAD

**Issue by testark** [orientechnologies/orientdb#5367]
I have a three-node OrientDB cluster set-up using the default configuration, and I need to `UPSERT` a somewhat large number of vertices (~1000) from the Java API periodically. However, I notice that

```
orientGraph.command(COMMAND).execute(params)
```

takes a very long time (about 3 minutes for those 1000 vertices). I managed to cut this to 18 seconds by adding a `UNIQUE` index to the class and making a lookup + conditional insert, but this is more error-prone and still slow. Is there any other way I can achieve the same effect as `UPSERT` with a decent performance from the Java API?

**Comment by lazywizar** [comment]
Curious to know if you got any solutions for this.

Thanks

**Comment by testark** [comment]
@lazywizar the solution I ended up adopting was to replace OrientDB completely, as the distributed mode (which I was using) was everything but production-ready.
