### ISSUE TITLE
Suggestion: A MuleSoft Connector?

### ISSUE THREAD

**Issue by wargun02** [orientechnologies/orientdb#5369]
Just a suggestion, since OrientDB supports REST API, why not create a MuleSoft connector? Mule ESB is getting rather popular these days.

**Comment by tonedef71** [comment]
+1  Integrating commercially with **_MuleSoft_** would be boost promotion of **_OrientDB_** significantly, as **_MuleSoft_** is a big-time player now.  Right now, **_OrientDB_** is noticeably absent from the promoted set of integrated database technologies, as is **_Neo4J_**:

![image](https://cloud.githubusercontent.com/assets/3978924/24163131/0570d294-0e40-11e7-8045-fe3ad84e3ab0.png)

**Comment by lvca** [comment]
Not relevant anymore.
