### ISSUE TITLE
dserver.sh has wrong first line

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5370]
Since 2.1.6 somehow the dserver.sh file has been changed. 

Running it will give you the following error:
```
./dserver.sh: 5: ./dserver.sh: Bad substitution
```
Changing the first line back to 
```
#!/bin/bash
```
Fixes this.

**Comment by robfrank** [comment]
Could you tell OS version?

**Comment by wouterv** [comment]
Ubuntu 14.04
Op 24 nov. 2015 4:52 p.m. schreef "Roberto Franchini" <
notifications@github.com>:

**Comment by robfrank** [comment]
Can  you try this replacement for dserver.sh and tell me if it is working:

#!/bin/sh
${0%dserver.sh}server.sh -Ddistributed=true $*

(we want to be POSIX compliant, I've test this on ubuntu and mac osx)

**Comment by wouterv** [comment]
@robfrank Yes, that works!

**Comment by robfrank** [comment]
Ok, thank you very much. We are getting rid of any so called bash-ism to be posix compliant. This way our scripts will woks on any *nix systems, even the ones without a bash.
