### ISSUE TITLE
Parameter Replacement with Create Edge

### ISSUE THREAD

**Issue by daniellawry** [orientechnologies/orientdb#5371]
Version 2.1.2

It looks like parameter replacement isn't working for the "CREATE EDGE..." style OCommandSQL statements in the Java API.

To reproduce, create an `OCommandSQL` like "CREATE EDGE foo FROM ? TO ?" and call execute with two RIDs in the proper format (i.e. "#13:1" and "#14:2")

When executed, the `OCommandExecutorSQLCreateEdge.execute(...)` method tries to generate the `fromIds` and `toIds` variables by calling `OSQLEngine.parseRIDTarget(...)`. You can see that the iArgs map contains proper rid values (i.e. "#13:1" and "#14:2") but that the iTarget parameter passed to parseRIDTarget still shows the unevaluated "?".  That's causing the last else block being triggered, running the code `ids = Collections.singleton(new ORecordId(iTarget));` where iTarget = "?" which ends up throwing the following exception...

"Argument '?' is not a RecordId in form of string. Format must be: <cluster-id>:<cluster-position>"

Is parameter replacement for CREATE EDGE going to be supported in the future?  As a workaround, I can simply string append the actual RIDs into the query but I don't like the idea of handling SQL injection different ways for different queries.

**Comment by luigidellaquila** [comment]
Hi @daniellawry 

This should be already fixed in current 2.1.11, could you please confirm?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @daniellawry 

I'm closing this issue, please reopen if you experience any other problems

Thanks

Luigi
