### ISSUE TITLE
batch script problem  in java 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5372]
release 2.1.6
db.command(new OCommandScript("sql", sb.toString())).execute();

com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.delete  from A where @rid = #10:1

Copying the script ( sb.toString() content ) to console all is working. 

In addition the command inside batch was corrected because 

commit retry 100 is not more working event if documentation still tells about it  (it accepts just commit )

**Comment by maggiolo00** [comment]
@publicocean0 

are you in plocal or remote?

**Comment by publicocean0** [comment]
The exception is using remote client.

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

could you please post the full content of sb? Is it only the statement I see in the logs?

Thanks

Luigi

**Comment by publicocean0** [comment]
you are right the problem is not for every script inside. It is very strange.
i changed the script testing:
<pre>
       begin
	delete from #10:1
       commit 
</pre>		
is OK 

instead 	
<pre>
begin							
delete  from ( select from ( select expand(rid)  from index:A.b where key =  #20:3 ) ) 
commit 
</pre>
in console is OK but  remote client gives...
Cannot find a command executor for the command request ....

**Comment by publicocean0** [comment]
Making  a lot of tries if think i found the problem 
double space after delete gives error

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

This issue was fixed in v 2.2 GA with the support of new SQL parser for batch scripts.

Closing

Thanks

Luigi
