### ISSUE TITLE
Properties of the same type and name (even inhereted) are in conflict when trying to move a class (even inside the same hierarchy)

### ISSUE THREAD

**Issue by a-unite** [orientechnologies/orientdb#5373]
I'm not sure if this is a bug, but since version 2.1 we have definitely lost the feature we were used to use a lot during v1.x-2.0 times.

Here is a very basic use case: we have parent class with properties, child class and then grandchild class, inhereted from the child.
`create class ParentClass extends V abstract`
`create property ParentClass.RevNumberNine integer`
`create class ChildClass1 extends ParentClass`
`create class ChildClass2 extends ChildClass1`

Now, if we try to move grandchild up in hierarchy (making it sibling of the child),
`alter class ChildClass2 superclass ParentClass`

properties conflict arise, giving us a message:
>com.orientechnologies.orient.core.exception.OSchemaException: Cannot add base class 'ChildClass2', because of parameter conflict: RevNumberNine (type=INTEGER) vs RevNumberNine (type=INTEGER)

I believe that previous convention, when properties with exactly the same names and types were interchangeable,  had more sense, giving us (quite important) kind of schema's flexibility.

Could you please comment on this and made your honest verdict? Was there any reason to make it so strict or it is just coincendence?

**Comment by lvca** [comment]
The main problem here is the binary protocol that stores the property id, instead of the name. @tglman could explain better this problem and why this limitation.

**Comment by a-unite** [comment]
Luca, thank you very much for your prompt answer!

I remember and see now, that names of schema defined properties are not stored in data files anymore. This is great. 

On the other hand, because lookup for properties values works great from parent to children and accross the same name properties of different classes during select, I still hope there are some chances this feature could also be extended back to the previous "intelligent" way.

This kind of ODB's schema reasonable fluidity was and still is one of the killer features for us.

**Comment by a-unite** [comment]
Forgot to say, while this may help.

We've found the hack for one particular scenario, when you need to insert one more class (level) between, let's say, *ParentClass* and *ChildClass1*.

You have to make orphaned class (not inherited from any other), then make it parent for _ChildClass1_ and only then make itself child of _ParentClass_

`create class ChildClass0`
`alter class ChildClass1 superclass ChildClass0`
`alter class ChildClass0 superclass ParentClass`

Still, this is a hack and might be unsafe if there are real problems with implementation of class movements.

**Comment by a-unite** [comment]
Dear @tglman may we call this regression or bug now?
We are trying to switch to 2.1 in production, but still...

**Comment by tglman** [comment]
this is actually a bug, if the property have the same name and type shouldn't go in conflict.

**Comment by tglman** [comment]
fixed in 2.1, need to be ported to 2.2

**Comment by a-unite** [comment]
@tglman, thank you very much!

**Comment by tglman** [comment]
closing
