### ISSUE TITLE
Re-creating edges in OrientDB takes an increasing amount of time

### ISSUE THREAD

**Issue by testark** [orientechnologies/orientdb#5380]
I have a three-node setup of OrientDB setup using `synchronous` replication and I'm connecting to it using the `remote` storage (can't do it otherwise, really). I'm using OrientDB's latest version (`2.1.5`).

I am making an SQL batch from my Java application and executing it using

```
g.command(new OCommandScript(MY_BATCH)).execute();
```

To make things simple, let's assume this batch creates 750 edges (with properties) between an existing (fixed) number of vertices—something like this:

```
BEGIN;
CREATE EDGE MyEdge FROM #10:0 TO #10:1 SET uuid = '<some-uuid>';
CREATE EDGE MyEdge FROM #10:0 TO #10:2 SET uuid = '<some-uuid>';
...
CREATE EDGE MyEdge FROM #10:0 TO #10:750 SET uuid = '<some-uuid>';
COMMIT RETRY 10;
```

(The source vertex is always the same, and the target vertices differ but are the same among consecutive runs.)

Now, if I run this once it takes about, say, `750ms`. However, if I run it repeatedly it starts taking an increasing amount of time (`3s`, then `6s`, etc...).

Can anyone please shed some light on what can be causing this?

**Comment by laa** [comment]
Hi
You truncate cluster after retry I think ?

On Thu, Nov 26, 2015, 14:56 luigidellaquila <notifications@github.com>
wrote:

> Assigned #5380 <https://github.com/orientechnologies/orientdb/issues/5380>
> to @laa <https://github.com/laa>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5380#event-475559477>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by testark** [comment]
@laa if I truncate, the time remains "constant" (~`750ms` per run). If I don't truncate it, it takes an increasing amount of time, which is why I am reporting. Shouldn't the time taken without truncating be constant?

**Comment by laa** [comment]
Edges are presented as trees now. So time should increase logarithmically
if you fit all data in memory cache.
Is it your case ?

P.S. We are working on linked list solution so it will be constant in shor
feature.

On Thu, Nov 26, 2015 at 3:54 PM testark <notifications@github.com> wrote:

> @laa <https://github.com/laa> if I truncate, the time remains "constant"
> (~750ms per run). If I don't truncate it, it takes an increasing amount
> of time, which is why I am reporting. Shouldn't the time taken without
> truncating be constant?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5380#issuecomment-159921570>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by testark** [comment]
@laa I'm not entirely sure of what you mean by

> if you fit all data in memory cache

Could you please elaborate? I am using the Java Graph API to send this SQL batch as a `OCommandScript` to a remote OrientDB server. That's basically my use case.

**Comment by laa** [comment]
Whit is your database size and what is your cache size ?
You may find disk cache size in server log during server start.

On Thu, Nov 26, 2015 at 4:50 PM testark <notifications@github.com> wrote:

> @laa <https://github.com/laa> I'm not entirely sure of what you mean by
>
> if you fit all data in memory cache
>
> Could you please elaborate? I am using the Java Graph API to send this SQL
> batch as a OCommandScript to a remote OrientDB server. That's basically
> my use case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5380#issuecomment-159931533>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by testark** [comment]
I'm using a mostly stock OrientDB configuration and starting with an empty database. This is what I get during server start in the three nodes:

**Node 1**
```
2015-11-26 14:54:15:826 WARNI Not enough physical memory available for DISKCACHE: 1,840MB (heap=455MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]
2015-11-26 14:54:15:827 INFO  OrientDB config DISKCACHE=-664MB (heap=455MB os=1,840MB disk=39,836MB) [orientechnologies]
```

**Node 2**
```
2015-11-26 14:54:15:795 INFO  OrientDB auto-config DISKCACHE=5,320MB (heap=455MB os=7,823MB disk=39,864MB) [orientechnologies]
```

**Node 3**
```
2015-11-26 14:54:21:246 INFO  OrientDB auto-config DISKCACHE=5,320MB (heap=455MB os=7,823MB disk=36,847MB) [orientechnologies]
```

I have no idea why node 1 shows the `WARN`. All three nodes have the same amount of RAM (8GB) and free disk space (they are brand new test machines).

**Comment by laa** [comment]
Ah I see, you use distributed dabase , right ?
In such case now you may use only version of edges which are embedded into
document.

It means that at this version you will see performance degradation on
distributed deployment.
I suppose there are solutions to overcoem this
I assign this issue to @lvca, suppose he will help you.

On Thu, Nov 26, 2015 at 4:56 PM testark <notifications@github.com> wrote:

> I'm using a mostly stock OrientDB configuration and starting with an empty
> database. This is what I get during server start in the three nodes:
>
> *Node 1*
>
> 2015-11-26 14:54:15:826 WARNI Not enough physical memory available for DISKCACHE: 1,840MB (heap=455MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]
> 2015-11-26 14:54:15:827 INFO  OrientDB config DISKCACHE=-664MB (heap=455MB os=1,840MB disk=39,836MB) [orientechnologies]
>
> *Node 2*
>
> 2015-11-26 14:54:15:795 INFO  OrientDB auto-config DISKCACHE=5,320MB (heap=455MB os=7,823MB disk=39,864MB) [orientechnologies]
>
> *Node 3*
>
> 2015-11-26 14:54:21:246 INFO  OrientDB auto-config DISKCACHE=5,320MB (heap=455MB os=7,823MB disk=36,847MB) [orientechnologies]
>
> I have no idea why node 1 shows the WARN. All three nodes have the same
> amount of RAM (8GB) and free disk space (they are brand new test machines).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5380#issuecomment-159932797>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by testark** [comment]
> In such case now you may use only version of edges which are embedded into
document.

My edges have properties, which means they cannot be lightweight. Anywa, is there anything I can do to overcome this performace degradation?

**Comment by laa** [comment]
Luca is responsible for distributed part, so I think he will help you.

On Thu, Nov 26, 2015 at 5:04 PM testark <notifications@github.com> wrote:

> In such case now you may use only version of edges which are embedded into
> document.
>
> My edges have properties, which means they cannot be lightweight. Anywa,
> is there anything I can do to overcome this performace degradation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5380#issuecomment-159934047>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by lvca** [comment]
About the Node1, I've never seen a negative number in DISKCACHE:

    DISKCACHE=-664MB

Could you please share the server.sh of node1?

**Comment by testark** [comment]
@lvca It's the stock one: https://github.com/orientechnologies/orientdb/blob/2.1.5/server/script/server.sh. I didn't change anything.

**Comment by lvca** [comment]
This issue is the same of https://github.com/orientechnologies/orientdb/issues/2362. Unfortunately the support for distributed ridbag is scheduled for v3.0. @tglman WDYT to review this issue and provide an ETA?

**Comment by testark** [comment]
@lvca @laa At the moment, this is a major bottleneck in our solution. We do need a distributed setup and we're regularly creating this amount of edges. Isn't there really anything that can be done?

Unfortunately, as we're short on time, we may need to considering dropping Orient and replacing it by Titan or Neo4J if you can't really provide a solution soon, but I'd of course prefer to see this solved and keep Orient in our stack. :-(

**Comment by testark** [comment]
@lvca Any updates on this you could provide me with?
