### ISSUE TITLE
Page compression

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5383]
With 2Q cache we can not usa page compression because it can not be used as cache with variable amount of memory but with LIRS cache that is possible .

So I think we should consider how much faster we will be on huge databases with page compression enabled on LIRS cache. I thing we may try snappy for that because it is already boundled in our system or may be with something more efficient.

**Comment by lvca** [comment]
+1 for snappy, with pages (32k or 64k) should work very well.

**Comment by laa** [comment]
http://java-performance.info/performance-general-compression/ seems LZ4 even better , compression ration for 64k is 3.

**Comment by laa** [comment]
Moved in 3.0 because we moved parallel txs to 3.1 version.

**Comment by lvca** [comment]
Do you mean compression in RAM only, right?

**Comment by laa** [comment]
@lvca Exactly.

**Comment by laa** [comment]
After analysis, we found out that RAM compression will not add performance benefits we consider on disk compression instead to keep all storage on SSD.
