### ISSUE TITLE
move edge to new cluster

### ISSUE THREAD

**Issue by micha-nerdlichter** [orientechnologies/orientdb#5385]
How can I move edges to different clusters? There is no `MOVE EDGE`. I tried to use `MOVE VERTEX #20:1 TO CLUSTER:NewCluster` where `20:1` is my edge. It moved the edge, but connected Vertices are broken as they don't get their in and out fields updated.

I'm using orientdb 2.1.4

**Comment by luigidellaquila** [comment]
Hi @micha-nerdlichter 

there is no such feature right now, but it definitely makes a lot of sense.
I'm flagging it as an enhancement and scheduling it for v 2.2

In the meantime, I think you just have to delete and re-create the edges you want to move (that is what a MOVE EDGE would do and what MOVE VERTEX actually does right now)

Thanks

Luigi
