### ISSUE TITLE
Not able to create database by using OrientDB Studio/Console

### ISSUE THREAD

**Issue by vishnoiamit82** [orientechnologies/orientdb#5386]
I am new to Orient DB. Following user manual I have installed orient database. I am able to launch orientDB Studio however on clicking "Create New Database" Icon it is throwing following error. I am using Java 1.7.

{"errors":[{"code":505,"reason":505,"content":"java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"}]}

Any help is appreciated.

Thanks,
Amit

**Comment by lvca** [comment]
If you are using OrientDB v2.1.6, please install Java8.

**Comment by vishnoiamit82** [comment]
Thanks for your reply
Which version of orientdb is compatible With java 7?
On Saturday, November 28, 2015, Luca Garulli <notifications@github.com>
wrote:

> If you are using OrientDB v2.1.6, please install Java8.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5386#issuecomment-160190592>
> .
>


-- 
Amit Vishnoi

**Comment by lvca** [comment]
[v2.1.5](http://orientdb.com/download.php?email=unknown@unknown.com&file=orientdb-community-2.1.5.tar.gz&os=multi)
