### ISSUE TITLE
Studio - Browse Tab - Support comments in first and last query line

### ISSUE THREAD

**Issue by bodiam** [orientechnologies/orientdb#5387]
Hi all,

Would it be possible to support comments in the web console when executing queries? Right now it gives errors when putting a --, //, or # as a comment in the console and executing a query (though for the first two options, it is recognised as a comment).

**Comment by luigidellaquila** [comment]
Hi @bodiam 

do you mean from Studio? You can use Java multi-line comments: ```/* a comment */```

You can also highlight text and comment it with CTRL+/

**Comment by bodiam** [comment]
Yes, that's what I mean. I don't see it working...

![screen shot 2015-11-28 at 01 44 14](https://cloud.githubusercontent.com/assets/46468/11449351/8fccba3c-9571-11e5-822a-4ba760e21c61.png)

**Comment by luigidellaquila** [comment]
Ok, it seems to be a bug, I guess if you put the comment in the middle or at the end of the query it will work.
I'm flagging this as a bug

Thanks

Luigi

**Comment by bodiam** [comment]
Are there tests for this somewhere? I don't mind creating a pull request.

**Comment by luigidellaquila** [comment]
Hi @bodiam 

yes, you can find some tests in ```OConsoleDatabaseAppTest```

Thanks

Luigi

**Comment by SamHard** [comment]
Block comments seem to work fine in Studio with 2.2.11; however, line comments, "--", do not.  It would be nice to be able to use either, especially since the console is finicky about block comments, but has no issues with line comments.

**Comment by luigidellaquila** [comment]
Hi @SamHard 

the `--` is part of OrientDB grammar (see MATCH statement), so unfortunately it cannot be used for comments

Thanks

Luigi
