### ISSUE TITLE
Error accessing property of embeddedmap

### ISSUE THREAD

**Issue by alpeshgaglani** [orientechnologies/orientdb#5391]
Hi,
I'm using 2.1.6. I have an issue that occurs on our production ubuntu boxes. On those, accessing a property of an embeddedmap causes the following error:

```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query:
select states.1-15-0 from #23:4923
Encountered " <FLOATING_POINT_LITERAL> ".1 "" at line 1, column 20.
Was expecting one of:
    <EOF>
    <TIMEOUT> ...
    <AS> ...
    <FETCHPLAN> ...
    <LOCK> ...
    <LET> ...
    <NOCACHE> ...
    <PARALLEL> ...
    <UNWIND> ...
    ";" ...
    "," ...
    <AS> ...
    "," ...
```
The sql command: select states.1-15-0 from #23:4923. If I just run select states from #23:4923, it works fine and I get:
```
----+------+--------------------
#   |@CLASS|states
----+------+--------------------
0   |null  |{1-15-0={test=test}}
----+------+--------------------
```
This is the Java version on the servers.
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

Strangely, the same (select states.1-15-0 from #23:1) works just fine on my Windows development server.

Any clues what might be going on?

Thanks!

**Comment by luigidellaquila** [comment]
Hi @alpeshgaglani 

```1-15-0`` ` is not a valid identifier (property name) per se, if you want to use it in a query projection you have to quote it with back ticks:

```
select states.`1-15-0` from #23:1
```

It is strange that it is working on Windows, are you using the same OrientDB version?

Thanks

Luigi

**Comment by alpeshgaglani** [comment]
Thanks for the quick response! The backtick quotes works great. 
Inteterstingly, without the quotes, it has always worked on my windows server, and used to work since 2.1.0 even on our linux servers. My windows OrientDB version is 2.1.6 as well.
