### ISSUE TITLE
Case insensitive collation has no effect when using "like" clause

### ISSUE THREAD

**Issue by red-0ne** [orientechnologies/orientdb#5394]
Issuing a query with "like" doesn't respect collate: case insensitive
```sql
SELECT FROM OUser WHERE name LIKE 'Adm%'
```
returns no result, although
```sql
SELECT FROM OUser WHERE name = 'Admin'
```
and
```sql
SELECT FROM OUser WHERE name LIKE 'adm%'
```
are fine and returning the correct result.

OrientDB develop branch (f5ce925)

**Comment by luigidellaquila** [comment]
Hi @red-0ne 

I tried it on latest snapshot and it seems to be already fixed.
Probably it was fixed some months ago.

I'm closing it, please reopen in case you still see related problems 

Thanks

Luigi

**Comment by red-0ne** [comment]
This issue is indeed fixed.

Thank you
