### ISSUE TITLE
CREATE FUNCTION with PARAMETERS - bug in documentation or functionality?

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5395]
What is the correct syntax for creating an SQL function with a named parameter?

The documentation at http://orientdb.com/docs/2.1/SQL-Create-Function.html is not very clear about how the named parameter should be used in the function body.

I have tried numerous variants of the following:

`CREATE FUNCTION get "SELECT FROM Person WHERE name = ?" PARAMETERS [VAL] LANGUAGE SQL;`

The function is successfully defined, but cannot be successfully used.

Consider for example this transcript:

```
OrientDB console v.2.1.5 (build 2.1.x@r; 2015-10-29 16:54:25+0000) www.orientdb.com
...
orientdb {db=diner}> SELECT count(*) FROM Person WHERE name = "Bill"

----+------+-----
#   |@CLASS|count
----+------+-----
0   |null  |1    
----+------+-----

1 item(s) found. Query executed in 0.002 sec(s).

orientdb {db=diner}> CREATE FUNCTION get "SELECT FROM Person WHERE name = ?" PARAMETERS [VAL] LANGUAGE SQL;

Function created successfully with id=#6:34

orientdb {db=diner}> select get("Bill")

----+------+----
#   |@CLASS|get 
----+------+----
0   |null  |[0] 
----+------+----

```

Note: For JAVASCRIPT functions, the situation is different, because one can (for example) write:

```
CREATE FUNCTION get 'return orient.getDatabase().query("select count(*) from " + val)[0]' PARAMETERS [val] LANGUAGE JAVASCRIPT
```

Thanks!

**Comment by smolinari** [comment]
Maybe another reason to believe functions aren't supposed to be available using the console? :wink: :smiley: 

Scott

**Comment by pkoppstein** [comment]
@smolinari - Fortunately, your suggestion that the documentation on OrientDB-SQL is not to be taken seriously is at least in this case (i.e. in the case of http://orientdb.com/docs/2.1/SQL-Create-Function.html) simply refuted by the output of the console "help" command, which includes the line:
```
* create function <command-text>                                                       Create a stored function
```

**Comment by smolinari** [comment]
Ok. That would mean the docs are missing and the function is broken.

Scott

**Comment by pkoppstein** [comment]
By trial and error, I found that the key is the humble colon:

    CREATE FUNCTION get "SELECT FROM V WHERE name = :VAL" PARAMETERS [VAL] LANGUAGE SQL IDEMPOTENT TRUE;

So this is a documentation issue/bug.

Unfortunately, the result of calling get(_) is not quite the same as the result obtained calling SELECT directly.  Documentation about that, I believe, is also needed.

**Comment by MBharu** [comment]
Hello, Has this issue been resolved? Could someone kindly help with syntax/sample for writing a user-defined function in OrientDB using SQL language? Many thanks in advance.

**Comment by MBharu** [comment]
Also, kindly provide the syntax to drop/delete a user-defined function from console.
