### ISSUE TITLE
JS Batch Script "Invalid Return Statement" Error

### ISSUE THREAD

**Issue by sungchoiok** [orientechnologies/orientdb#5399]
On the Studio Query Configuration, set "Type" to "BATCH" and "Language" to "JAVASCRIPT".

Execute this query:

    return true;

I receive this error:
com.orientechnologies.orient.core.command.script.OCommandScriptException: ScriptManager: error <eval>:1:0 Invalid return statement return true; ^ in <eval> at line number 1 at column number 0. Function unknown: 1: >>> return true; 

However, other Javascript code executes fine, such as

    var t = 100;
    var db = orient.getGraph();

.

However, executing 

    var t = 100;
    var db = orient.getGraph();
    return true;

again yields error.

I apparently cannot `return` anything (of any Type) from Javascript Batch scripting. I am not sure if this is a bug or is a gap in my understanding.

Studio Version: 2.1
DB Version: 2.1.6 and 2.1.4

Thank you for your time.

**Comment by sungchoiok** [comment]
You marked it as a question so I suppose it's behaving the way it is supposed to be.

Then, how can I return any data from Javascript batch scripts?

**Comment by sungchoiok** [comment]
Ok, I figured it out...

Reference for anyone else, all you do is put the variable you want to return at the end of the query without the `return` keyword in front.

e.g.

    var g = orient.getGraph();
    var data = g.command("sql", "some query");
    data

**Comment by lvca** [comment]
Added this to the docs.
