### ISSUE TITLE
coalesce function returning document when expecting simple integer

### ISSUE THREAD

**Issue by daniellawry** [orientechnologies/orientdb#5400]
OrientDB version 2.1.2

I have a Vertex type called "ListModelVersion" with a property called "internalVersion" that is a simple integer.  I was trying to use the coalesce function to return the maximum internalVersion value or 0 for a set of Vertexes using the following query...

SELECT FROM ListModelVersion WHERE internalVersion >= COALESCE((SELECT MAX(internalVersion) FROM ListModelVersion WHERE vid = '489b2805-4899-4dc6-93e4-53b756bf5081'), 0) AND vid = '489b2805-4899-4dc6-93e4-53b756bf5081'

But this query was failing to find valid content that I was certain was in the database. I was expecting the coalesce function would return a simple integer value to compare against the internalVersion field but it turns out it returns document formatted JSON.  Here's an example of the output I received for just selecting the coalesce portion of the query

SELECT COALESCE((SELECT MAX(internalVersion) FROM ListModelVersion WHERE vid = '489b2805-4899-4dc6-93e4-53b756bf5081'), 0) FROM ListModelVersion WHERE vid = '489b2805-4899-4dc6-93e4-53b756bf5081'

returns...

{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "COALESCE": [
                {
                    "@type": "d",
                    "@rid": "#-2:0",
                    "@version": 0,
                    "MAX": 10000
                }
            ],
            "@fieldTypes": "COALESCE=z"
        }
    ],
    "notification": "Query executed in 0.058 sec. Returned 1 record(s)"
}

Based on looking at the output above, I can change my query by appending ".MAX[0]" to the COALESCE statement to do what I want, but it seems like that is a rather unintuitive and inelegant solution (see below)

SELECT FROM ListModelVersion WHERE internalVersion > COALESCE((SELECT MAX(internalVersion) FROM ListModelVersion WHERE vid = '489b2805-4899-4dc6-93e4-53b756bf5081'), 0).MAX[0] AND vid = '489b2805-4899-4dc6-93e4-53b756bf5081'

Is this the intended way COALESCE should behave or is this a bug?

**Comment by luigidellaquila** [comment]
Hi @daniellawry 

Sorry for the late reply. This is the expected behavior, as the subquery you are passing to the COALESCE() function returns documents.

You can try with a LET and a specific selection, eg. 
```
SELECT ...
LET $a = (SELECT)
...
WHERE internalVersion > COALESCE($a[0].max) 
...
```

Thanks

Luigi
