### ISSUE TITLE
orientdb with two db connection pools creates clusters in wrong database on open

### ISSUE THREAD

**Issue by zerovian** [orientechnologies/orientdb#5402]
orientdb 2.1.4

I have two databases.  I create one, setup a connection pool, register a bunch of classes, close that database connection.  Then create a different database, and setup a different connection pool, open the other one.  As soon as I setup the connection pool for the second database (which already exists), orientdb goes and registers all the classes from the first database's connection pool into the second database, and creates clusters for all of them.

Here is the stack.   At this point, simply creating a new database object forces registration of all the classes, but the entity manager is shared so it screws up the file system for the other database which isn't supposed to have these objects registered.

This used to work fine in 2.0.8

Thread [Plug-in of type: com.progress.isq.ipqos.plugin.FathomPlugIn] (Suspended (breakpoint at line 1121 in OSchemaShared))	
	owns: Class<T> (com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer) (id=160)	
	owns: OEntityManager  (id=108)	
	OSchemaShared.createClusters(String) line: 1121	
	OSchemaShared.createClass(String, int[], OClass...) line: 419	
	OSchemaShared.createClass(String, OClass, int[]) line: 400	
	OSchemaShared.createClass(String) line: 275	
	OSchemaProxy.createClass(String) line: 71	
	OObjectEntitySerializer.registerClass(Class<?>) line: 589	
	OObjectEntityClassHandler.registerEntityClass(String, Class<?>) line: 39	
	OObjectEntityClassHandler.registerEntityClass(Class<?>) line: 33	
	OEntityManager.setClassHandler(OEntityManagerClassHandler) line: 242	
	OObjectDatabaseTx.init() line: 839	
	OObjectDatabaseTx.<init>(ODatabaseDocumentTx) line: 110	

--- test code that proves the point----

		// extra squigglies are to make sure my variables dont' overlap
		{
			String db1Path = "plocal:c:\\temp\\test1";

			OObjectDatabaseTx db1 = new OObjectDatabaseTx(db1Path);
			db1.create();
			db1.close();

			OPartitionedDatabasePoolFactory pool1Factory = new OPartitionedDatabasePoolFactory(10);
			pool1Factory.setMaxPoolSize(10);
			OPartitionedDatabasePool pool1 = pool1Factory.get(db1Path, "admin", "admin");
			db1 = new OObjectDatabaseTx(pool1.acquire());

			// register classes
			db1.getEntityManager().registerEntityClass(TestEntity.class);
			db1.close();
		}

		{
			String db2Path = "plocal:c:\\temp\\test2";
			// create database 2
			OObjectDatabaseTx db2 = new OObjectDatabaseTx(db2Path);
			db2.create();
			db2.close();

			OPartitionedDatabasePoolFactory pool2Factory = new OPartitionedDatabasePoolFactory(10);
			pool2Factory.setMaxPoolSize(10);
			OPartitionedDatabasePool pool2 = pool2Factory.get(db2Path, "admin", "admin");
			db2 = new OObjectDatabaseTx(pool2.acquire());
			db2.close();
		}

		// at this point test2/testentity.cpm exists...it shouldn't

**Comment by laa** [comment]
Fixed.
