### ISSUE TITLE
Disable Validation Implications

### ISSUE THREAD

**Issue by lcappuccio** [orientechnologies/orientdb#5406]
Hi,

We're using an embedded-inmemory instance and to improve performance we are evaluating graph.setValidationEnabled(false).
First tests show a noticeable performance improvement but it is not clear what are the eventual implications when using this setting.

Thanks in advance,
Leonardo

**Comment by lvca** [comment]
If you remove validations the database constraints & types are not applied, but in case you respect them at application level, it's safe.
