### ISSUE TITLE
Index information not propagated to schema information on other node in java client

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5407]
Reproduction:

- Start a 2 (or 3) node cluster
- Connect to node 1 and 2 with separate jvm's using the Java API
- Using node 1 client connection, create an index on a class property
- Using node 2 call code db.getMetadata().getSchema().getClass("classname").getClassIndex("theindexname").
The result will return null.
Restarting the node 2 client and running it again will fix the problem, the index is found in the class meta data.

We are currently employing the following workaround to get around this issue (pretty ugly):

```
                try {
                    getDb().command(new OCommandSQL("select count(*) from `index:" + indexName + "`")).execute();
                    exists = true;
                } catch (OCommandExecutionException oee){
                    exists = false;
                }
```

**Comment by lvca** [comment]
This is a duplicated of this enhancement https://github.com/orientechnologies/orientdb/issues/3496.

**Comment by lvca** [comment]
This is not supported right now. I suggest to create the schema at startup. Is it possible for your use case?

**Comment by wouterv** [comment]
No it isn't. We update schema's on the fly. And this works fine except in this particular case.

**Comment by wouterv** [comment]
There is one vital piece information I forgot to mention:

We have a mechanism in place that records that schema update has taken place (a simple counter). Whenever a connection is taken from the pool, it checks the db schema version versus the number in memory. If it is behind, the schema information is reloaded like this:

```
db.getMetadata().getSchema().reload()
```
So this way we make sure class and property info is always up to date, but the reload apparently doesn't include the index info when running distributed.

**Comment by lvca** [comment]
With "Restarting the node 2 client and running it again will fix the problem, the index is found in the class meta data" do you mean a client that is connected to node2 with remote, right?

**Comment by wouterv** [comment]
Yes. So the index creation is initiated on a client that connects to node1 and when the client connected to node 2 reloads the schema, the index info isn't there (but the select hack works, so the index is available).

**Comment by lvca** [comment]
So even after reload of schema the index is not there? How do you reload the schema? You should reload metadata:

db.getMetadata().reload()

**Comment by wouterv** [comment]
Thanks! That was it, I didn't know index stuff was kept seperately from the schema
