### ISSUE TITLE
Edge creation progressively slows down during ETL (OrientDB 2.1.4)

### ISSUE THREAD

**Issue by balemayehu** [orientechnologies/orientdb#5408]
When using ETL process to import additional 4.9 million Edges on a single server graph database, the import process starts off around 400-600 vertices/sec, but then progressively gets slower and grinds to almost a halt when it gets to about a million edges inserted. JVM starts using up almost all of the physical memory available. I have tried changing the MAXHEAP and MAXDISKCACHE settings based on recommendation in log file (MAXHEAP=-Xmx387m, MAXDISKCACHE="-Dstorage.diskCache.bufferSize=1519"), but that didn't provide any significant difference. I have also tried changing the ETL query below to use rid instead of the sub selects, but that didn't help either.

Current Graph Info:
100k User Vertex
100k AssetType2 Vertex
5mil AssetType1 Vertex
2.5mil Friend Edges (between user vertices)
100k BelongTo Edges (between asset type 2 and user)
100k ActedOn Edges (between asset type 1 and asset type 2)
100k Created Edges (between user and asset type 1)

Machine info:
Linux x86_64
4GB Mem
30GB disk with 75% free space
2 core CPU 2.4GHZ

ETL json file:
{
"source": { "file": { "path": "edge.csv" } },
"extractor": { "csv": {"separator":" " }},
"transformers" : [
{"command":{"command":"create edge Created from (select from User where id = ${input.source_id}) to (select from AssetType1 where id = ${input.dest_id})",
"output": "edge"
}}
],
"loader" : {
"orientdb": {
"dbURL": "remote:localhost/mygraphdb",
"dbAutoCreate": false,
"dbUser": "admin",
"dbPassword": "*",
"dbType": "graph",
"batchCommit": 1000
}
}
}

Is this a configuration issue, a resource constraint issue, or a limitation with Edge creation? Why does the JVM start to eat up all the memory? Your feedback is greatly appreciated. Thanks.

**Comment by laa** [comment]
Hi,
1. What is your db size on disk.
2. Could you run iostat -dxk and send result to me ?


On Tue, Dec 1, 2015 at 7:58 PM balemayehu <notifications@github.com> wrote:

> When using ETL process to import additional 4.9 million Edges on a single
> server graph database, the import process starts off around 400-600
> vertices/sec, but then progressively gets slower and grinds to almost a
> halt when it gets to about a million edges inserted. JVM starts using up
> almost all of the physical memory available. I have tried changing the
> MAXHEAP and MAXDISKCACHE settings based on recommendation in log file
> (MAXHEAP=-Xmx387m, MAXDISKCACHE="-Dstorage.diskCache.bufferSize=1519"), but
> that didn't provide any significant difference. I have also tried changing
> the ETL query below to use rid instead of the sub selects, but that didn't
> help either.
>
> Current Graph Info:
> 100k User Vertex
> 100k AssetType2 Vertex
> 5mil AssetType1 Vertex
> 2.5mil Friend Edges (between user vertices)
> 100k BelongTo Edges (between asset type 2 and user)
> 100k ActedOn Edges (between asset type 1 and asset type 2)
> 100k Created Edges (between user and asset type 1)
>
> Machine info:
> Linux x86_64
> 4GB Mem
> 30GB disk with 75% free space
> 2 core CPU 2.4GHZ
>
> ETL json file:
> {
> "source": { "file": { "path": "edge.csv" } },
> "extractor": { "csv": {"separator":" " }},
> "transformers" : [
> {"command":{"command":"create edge Created from (select from User where id
> = ${input.source_id}) to (select from AssetType1 where id =
> ${input.dest_id})",
> "output": "edge"
> }}
> ],
> "loader" : {
> "orientdb": {
> "dbURL": "remote:localhost/mygraphdb",
> "dbAutoCreate": false,
> "dbUser": "admin",
> "dbPassword": "*",
> "dbType": "graph",
> "batchCommit": 1000
> }
> }
> }
>
> Is this a configuration issue, a resource constraint issue, or a
> limitation with Edge creation? Why does the JVM start to eat up all the
> memory? Your feedback is greatly appreciated. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5408>.
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by balemayehu** [comment]
Hi Andrey,

Below is the info you requested.

#du -sh orientdb-community-2.1.4/databases/mygraph/
5.0G orientdb-community-2.1.4/databases/mygraph/

#iostat -dxk
Linux 4.1.7-15.23.amzn1.x86_64 (*) 12/02/2015 _x86_64_ (2 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await  svctm  %util
xvda              0.00     1.59    0.86   15.01    51.88  1702.18   221.00     0.34   21.53   9.80  15.55

**Comment by balemayehu** [comment]
Has there been any progress with this issue? Have you been able to reproduce or have any insight into what might be going on?  Thanks.

**Comment by laa** [comment]
Hi, if this issue still actual please let us know otherwise we will close it.
