### ISSUE TITLE
DICTIONARY KEYS

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5409]
DICTIONARY KEYS is documented at http://orientdb.com/docs/2.0/orientdb.wiki/Console-Command-Dictionary-Keys.html but is no longer available in 2.1.7-SNAPSHOT.  Is that an oversight?
It would be useful to have it (again)!

**Comment by andrii0lomakin** [comment]
Dictionary index is deprecated because of functional problems implied from the definition of the dictionary.
