### ISSUE TITLE
ER: equivalent of SQLite's .version

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5410]
SQLite3 has the .version command:

```
sqlite> .version
SQLite 3.9.1 2015-10-16 17:31:12 767c1727fec4ce11b83f25b3f1bfcfe68a2c8b02
```

As best I've been able to determined, OrientDB console.sh does not have equivalent functionality.

I realize that the output of INFO is currently confined to information
about the connected database, but I can't see any harm in expanding
the scope of the INFO command.  One alternative to consider would be to add
a parameter to the DISPLAY command (e.g. DISPLAY VERSION).

**Comment by lvca** [comment]
The console shows the version at launch. Closing it.
