### ISSUE TITLE
Deleted property still appear 

### ISSUE THREAD

**Issue by phamptu** [orientechnologies/orientdb#5411]
After delete a property success, it still appear in response with "Select * from ".
I thing that mean delete operation have some problem. 

![screen shot 2015-12-02 at 4 36 29 pm](https://cloud.githubusercontent.com/assets/7067261/11527408/5f9314f6-9913-11e5-9cb8-c0354f06c9a8.png)

**Comment by luigidellaquila** [comment]
Hi @phamptu 

```drop property``` modifies the schema only, not data.
If you want to change data you have to execute an
```
UPDATE User REMOVE propertyName
```

Thanks

Luigi
