### ISSUE TITLE
Error when creating a database

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5412]
OrientdDB 2.1.6
This is the error I get on console  when I try to create a document database from studio as a root user

2015-12-02 13:25:20:514 WARNI ->127.0.0.1: Command not found: GET.sqlProfiler/SupplierPartCatalogueDB [ONetworkProtocolHttpDb]

2015-12-02 13:25:20:991 SEVER Internal server error:
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #8: Error on parsing command at position #0: Error on parsing query
Query:  _studio WHERE user.name = 'admin' AND type = 'GraphConfig'
-------------^
--> com.orientechnologies.orient.core.exception.OCommandExecutionException: Class '_STUDIO' was not found in current database [ONetworkProtocolHttpDb]

Nevertheless the database has been created, OK I believe....

**Comment by maggiolo00** [comment]
hi @healiseu 

which version of OrientDB?

**Comment by smolinari** [comment]
First line in the OP says "OrientdDB 2.1.6"

Scott

**Comment by healiseu** [comment]
I believe it has been fixed in OrientDB 2.1.9

**Comment by lvca** [comment]
Fixed long time ago.
