### ISSUE TITLE
OrientDB Studio - Schema Manager - Sort Columns

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5413]
This sorting feature I request, is really handy and useful for all of us working with the Schema Manager improving a lot on the visibility of schema attributes.

Thank you

**Comment by maggiolo00** [comment]
+1

**Comment by healiseu** [comment]
:+1:

**Comment by maggiolo00** [comment]
@healiseu 

i'm about to work on this
which columns do you think is needed to sort?

-className

**Comment by santo-it** [comment]
Hi @maggiolo00,

I'd say at least: name, superclass,def cluster, records

Please let's keep in mind this enhancement when implementing https://github.com/orientechnologies/orientdb-studio/issues/21

Ideally we can implement https://github.com/orientechnologies/orientdb-studio/issues/21 and then add support for the sort feature. But let's keep this in mind while we work on that ER 21

Thanks,
