### ISSUE TITLE
Cannot find function getGraph on 2.1.2

### ISSUE THREAD

**Issue by lgaquino** [orientechnologies/orientdb#5414]
(Running on version 2.1.2)

Hello, I have a JS function that runs fine in. Studio, but not in Eclipse. It returns the following problem:

```
EcmaError: TypeError: Cannot find function getGraph in object com.orientechnologies.orient.core.command.script.OScriptOrientWrapper@183058.
```

By running on eclipse I mean using:

```
dbGraph.getRawGraph().getMetadata().getFunctionLibrary().getFunction("fName").execute(params);
```

I've looked around other issues and discussions, and it seems people solved this by simply having that following handler in orientdb-server-config.xml. But that does nothing for me..

``` xml
        <handler class="com.orientechnologies.orient.graph.handler.OGraphServerHandler">
            <parameters>
                <parameter name="enabled" value="true"/>
                <parameter name="graph.pool.max" value="50"/>
            </parameters>
        </handler>
```

**What I did notice though**, was that returning the 'orient' object in studio, I get the _OScriptGraphOrientWrapper_ class. While doing the same on Eclipse gives me the _OScriptOrientWrapper_ class. And the latter doesn't have the getGraph() method.

How should I go around this?

Regards.

**Comment by luigidellaquila** [comment]
Hi @lgaquino 

I remember we fixed a similar issue some time ago. Any chance to try it with 2.1.6?

Thanks

Luigi

**Comment by lgaquino** [comment]
ok, I'll give it a try

**Comment by lgaquino** [comment]
Well, it's the same on 2.1.6 i'm afraid...
the Orient object refers to the **com.orientechnologies.orient.core.command.script.OScriptOrientWrapper** class on Eclipse.

Didn't change any config on the DB, by the way. Just transported my database file.

**Comment by luigidellaquila** [comment]
Ok, it must be a different problem, I'll check it.

Thanks

Luigi
