### ISSUE TITLE
ER: SCRIPT line continuation

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5417]
Currently (e.g. in 2.1.7-SNAPSHOT), the "SCRIPT SQL" command of console.sh
in effect regards the end-of-line as ";", but often one wants to be able to break
up a long command into separate lines.  This does not seem to be possible in OrientDB.

In other systems, the ability to break up long lines under similar circumstances
is made possible by defining a line continuation character.  There are of course
several other alternatives, each with its pros and cons, which I won't get into here
as the important thing is that OrientDB provide at least one such mechanism.

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

yes, it's in the roadmap and in our intentions to support it soon

**Comment by pkoppstein** [comment]
@luigidellaquila - Thanks for letting me know.

Is it listed at http://orientdb.com/docs/2.1/Roadmap.html ?

In my view, #5379 is far more important, and really essential to anyone who uses console.sh intensively.  Could it be added to the Roadmap?

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

I just update the roadmap for 3.0 adding it explicitly

https://github.com/orientechnologies/orientdb-docs/blob/master/Roadmap.md

Thanks

Luigi

**Comment by pkoppstein** [comment]
@luigidellaquila - Thanks for adding it, and thanks for letting me know.

Do you regard the failure of "console.sh FILENAME" to work in general as a bug?  (That is, using 2.1.7-SNAPSHOT and other versions, it seems to work only if the pwd is ORIENTDB_HOME or ORIENTDB_HOME/bin)

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

```
console.sh FILENAME
```

is supposed to work fine from the bash prompt, I saw the docs are misleading, as they report

```
orientdb> console.sh FILENAME
```
as if it had to be executed from within OrientDB console.

If it doesn't work it's definitely a bug

Thanks

Luigi

**Comment by pkoppstein** [comment]
@luigidellaquila - As I said, it doesn't work in general (because of the use of cd inside console.sh together with the use of $*).

Should I create a separate ISSUE for an Enhancement Request?

Meanwhile, an improvement in the documentation would be helpful (i.e., explain that an absolute path should, in general, be given).

Thanks.

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

Yes, thanks, a separate issue will help to better track the problem.
Could you please also report some details about your environment? eg. OS version, shell type (bash/sh) and so on

Thanks

Luigi
