### ISSUE TITLE
bug: console.sh < test.osql

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5419]
The console.sh script should be able to take input from a file without going into some kind of infinite loop, but using 2.1.7-SNAPSHOT, it does just that using redirection (console.sh < test.osql).  

(The contents of test.osql can be as simple as: set echo true;)

By the way, there is something wrong with the directions given on the page
http://orientdb.com/docs/2.1/Console-Commands.html

In particular the line:

orientdb> console.bat commands.txt

seems to indicate that "console.bat" (or "console.sh" in a non-Windows environment) is an OrientDB console command, which of course it isn't.

One might think that the line in question is meant to imply that one should enter "console.sh commands.txt" at the system prompt, but that does not work either (not surprisingly).

**Comment by robfrank** [comment]
From documentation, redirection isn't necessary: console.sh <full path to script> is enough.

I can't find:

orientdb> console.bat commands.txt

Can we close this?

**Comment by pkoppstein** [comment]
@robfrank wrote:
> Can we close this?

My answer is: absolutely not.

It would be easy for console.sh to support redirection, as it should. See the original description of the problem.  (The point is that STDIN need not be a file.)

Regarding the documentation -- yes, I believe that the "bug" in the 2.1 documentation has been fixed. (Thank you to the person who fixed it!)

**Comment by robfrank** [comment]
If you know how to fix it, a PR is welcome and it will be part of next releases.
Thank you for reporting.

**Comment by lvca** [comment]
Docs updated, closing it
