### ISSUE TITLE
OOfflineClusterException Message: Cannot read a record from the offline cluster

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5423]
If some record is available in an offline cluster and I try to fetch it using index, it gives OOfflineClusterException. Why should it access offline cluster, shouldn't it be normal record not found situation.

Original Source: http://stackoverflow.com/questions/34080078/oofflineclusterexception-message-cannot-read-a-record-from-the-offline-cluster

**Comment by mecp** [comment]
Thank you for the fix!
