### ISSUE TITLE
OrientDB Studio - Command Line History

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5425]
#### Use the up and down key's to scroll through previously typed SQL commands

I think this is a typical feature that one expects to find and indeed that works with OrientDB console but it is not functional when you browse at OrientDB Studio.

**Comment by luigidellaquila** [comment]
Hi @healiseu 

CLI and Studio are quite different in terms of usability. In CLI using arrow keys to move in the query history is the only way to do that efficiently, while in Studio you have
- clickable query history
- bookmarks
- highlight-and-run
Moreover, Studio Query Browser is a multi-line text panel, so arrow keys are used to move in the panel itself.

I don't think this feature can be implemented in Studio in a usable way, but maybe I'm missing something, could you please specify what you exactly mean?

Thanks

Luigi

**Comment by healiseu** [comment]
OK let me state it differently. I can see that ALL arrow keys are reserved for editing the command when you Browse at Studio. But you could have Ctrl+Up, Ctrl+Down or some other shortcut to scroll through previously typed SQL commands.

In many cases this is the QUICKEST way than using the other methods you suggested. Just think that you want to access the 3rd, 4th, 5th, etc recent command in history. You just click 3, 4, 5 times and you have it in front of you.

Hope that explains better my point.....

**Comment by luigidellaquila** [comment]
Hi @healiseu 

Yes, it makes sense, I'm marking it as an enhancement

Thanks

Luigi

**Comment by healiseu** [comment]
:+1:

**Comment by flintiii** [comment]
Greetings luigidellaquila,

Is there any way that I can help get the "Search in history" dialog box in the orientdb-community-2.1.12 web interface to work? When I type a word into it, for instance "select" it returns "Warning You are clearing history. Are you sure?" just as if you clicked on the trash can.

I can see that there has already been a report, which may not have been expressed very well.

I would be very happy to get guidance as to how to scroll through the web based history on 2.1.2 or  register this as a bug if it really is.

Sincerely,

Flint

**Comment by maggiolo00** [comment]
hi @flintiii 

The search happen while typing. There is no need for Enter.
I didn't notice this earlier but if you type Enter the popup shows. I will prevent this.

**Comment by flintiii** [comment]
Greetings Enrico,

Please let me know when you have a patch in, as I would be happy to test it.

Sincerely,

Paul Flint

**Comment by lvca** [comment]
I've already seen this in studio. Is this fixed?

**Comment by maggiolo00** [comment]
@lvca 

yes but i'm not sure yet about the keybinding.Now are Ctrl+Up, Ctrl+Down but @luigidellaquila point it out that on Mac

Ctrl+Up, Ctrl+Down are used in editor as Page Up/Down.

We should chose another keybinding. Any proposition?

**Comment by maggiolo00** [comment]
Pushed with Binding Alt + up/down
