### ISSUE TITLE
ER: console.sh FILENAME

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5428]
Currently (e.g. 2.1.7-SNAPSHOT), `console.sh FILENAME` cannot work in general, because it executes a "cd" and then uses "$*".  That is, the script effectively assumes that: either FILENAME is absolute, or that the script is executed from a suitable directory.

Usually, scripts such as console.sh are written so that, at the minimum, the script can be installed in one place (e.g. /usr/local/bin/) and the FILENAME can be in the pwd, wherever that may be.

The fix should be simple, but in the meantime, it would be very helpful if the documentation could explain that specifying an absolute pathname is one alternative.

p.s.  As @luigidellaquila pointed out at #5417, the documentation also needs to be fixed:

    ... I saw the docs are misleading, as they report

    orientdb> console.sh FILENAME

    as if it had to be executed from within OrientDB console.

**Comment by robfrank** [comment]
fixed:

https://github.com/orientechnologies/orientdb/commit/625667d4f6271fdc74fe1f527beaace3add507e0

The 'cd' to orient home was useless because all paths are prefixed with ORIENTDB_HOME 
documentation is fixed too.
