### ISSUE TITLE
in 2.2 alpha there is no implementation of "if" statement in batch mode

### ISSUE THREAD

**Issue by fr3ak666** [orientechnologies/orientdb#5430]
Hi, 
I was really relying on your "if" in batch mode but I've found out that it was introduced in 2.1.7(which was really hard to find unless you compiled it from sources).
Unfortunately in 2.2 alpha there is no "if" either.
Please add it.

Best regards

**Comment by luigidellaquila** [comment]
HI @fr3ak666 

2.2 alpha was released before "if" was implemented.

I suggest you to build it from sources, just checkout "develop" branch and run 

```
mvn clean install
```

As an alternative, you can wait for next RC1, it should be available in a few days

Thanks

Luigi
