### ISSUE TITLE
OrientDB Date time format is not compliant with ISO 8601

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5432]
"Representation of dates and times is an international standard covering the exchange of date and time-related data"

According to ISO 8601, 
Combined date and time in UTC: 2014-12-20T00:00:00

But in OrientDB, v2.1.6, the "T" character that separates data and time is causing an error
Error on conversion of date '2014-12-20T00:00:00' using the format: yyyy-MM-dd HH:mm:ss

Wouldn't be better to follow ISO 8601 and save user's time from applying conversion tricks ?

**Comment by smolinari** [comment]
Try adding the "T" like so. `"2014-12-20'T'00:00:00"` Just guessing on my part, but if the data formatting follows [java simple date formatting](http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html), [as the docs suggest](http://orientdb.com/docs/2.1/SQL-Alter-Database.html), then it might work.  

Scott

**Comment by healiseu** [comment]
Thanks for the suggestions, I am just saying that IT IS NOT COMPLIANT with ISO 8601, therefore you have to munge your data.

**Comment by smolinari** [comment]
Then that would mean Java has an issue with being compliant, not OrientDB, wouldn't it? 

Scott

**Comment by healiseu** [comment]
Hi Sott, this is correct, and it is rather UNFORTUNATE I am afraid that people that make standards do not take on account programming languages and communities.

http://stackoverflow.com/questions/2201925/converting-iso-8601-compliant-string-to-java-util-date

**Comment by red-0ne** [comment]
you can change the date time format in your database
```sql
ALTER DATABASE DATETIMEFORMAT yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
```
It's causing some issues in the studio, but queries should be ok.

**Comment by healiseu** [comment]
:+1:  I see, this is useful, thank you
