### ISSUE TITLE
Graph Editor - Out (Tail), In (Head) Links

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5436]
In Graph Editor, when you click on a Vertex you can see two arrow icons representing (Out) and (In) LINK sets, but  both arrows are pointing outwards. Conceptually this is contradicting with the definition of the edge as a vector with a Tail, i.e. (Out) link from Vertex A, and a Head, i.e. (In) link to Vertex B. 

Therefore in my opinion it is better to picture two arrows, one pointing inwards vertex, and the other pointing outwards vertex, to indicate the direction of edge and its connection with the vertex.

I am aware that you can navigate in both directions, but the graph is DIRECTED, therefore one expects to see Head(s) and Tail(s) at each Vertex.

**Comment by healiseu** [comment]
@maggiolo00 I have been using Graph Editor on OrientDB 2.2b but the two arrow icons on each node representing (Out) and (In) LINK sets are **STILL** pointing outwards. You may write Out and In instead or change the direction of one of the arrows. Otherwise it is really confusing when you click on them as you are not sure whether you are at the Head or at the Tail.

**Comment by smolinari** [comment]
:+1:  I agree. This threw me off on understanding the graph connectivity a lot looking at the graphs in the editor, when I began with ODB and I still find it quite irritating. 

Scott

**Comment by maggiolo00** [comment]
@healiseu  @smolinari 
implemented. It will be available in the next release.
