### ISSUE TITLE
Duplication Constrain on Edges

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5438]
Hi, I have noticed that it is possible to create the same edge multiple times. Although this might be an option, for example I can imagine a case where we want to monitor a navigation path  and measure how frequently we cross a certain edge, this is certainly NOT the standard way to model relational data.

To achieve referential integrity on a standard Many-to-Many relationship, duplicate instances of a JOIN table record ARE NOT allowed. In other words, it is most desirable, to provide a mechanism for referential integrity, something which is trivial to do in Microsoft Access, right click and check "Enforce Referential Integrity". I can imagine a similar check button with the description, "DUPLICATE INSTANCES" of the edge ARE NOT allowed.

This way, you save the user from the burden to write code for preventing ACCIDENTAL duplication on edges. Let us take the classic Supplier-Part-Catalog case, a duplicate entry in the catalog means that 
you are COUNTING WRONG how many parts are supplied by a specific Supplier or how many Suppliers manufacture a certain part. Somehow you have to exclude duplicate instances. Yes, I know you can do that with code, and commands, etc, etc, but it is causing an extra headache !!!

In fact every single data instance that is duplicated in the system is asking for trouble, and if that is possible, it must be prevented. It is like disease, prevent it, rather than cure it ;-)

**Comment by luigidellaquila** [comment]
Hi @healiseu 

this can be implemented with a unique index on `out` and `in` properties of the edge class. Probably this could be made more user friendly, adding some metadata to the edge class, I'll leave it open and mark it as an enhancement

Thanks

Luigi

**Comment by smolinari** [comment]
Have a look at this part of the documentation. 

http://orientdb.com/docs/last/Tutorial-Using-schema-with-graphs.html#using-in-and-out-constraints-on-edges

It describes how you can create certain constraints, so you can avoid duplicate edges - mainly the unique edge index.

There is also these discussions about edge control and better abstraction. 

https://github.com/orientechnologies/orientdb/issues/3820#issuecomment-151162243
https://groups.google.com/forum/#!topic/orient-database/sZ4GjSvEKtI

Scott

**Comment by healiseu** [comment]
:+1: Thank you

**Comment by luigidellaquila** [comment]
Hi @healiseu 

I saw you opened a more general issue about this here https://github.com/orientechnologies/orientdb/issues/5439
I suppose I can close this, right?

Thanks

Luigi
