### ISSUE TITLE
Constrains on Creation of Classes, Edges and INSTANCES !

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5439]
Hi, I am motivated from Luigi comment on [this issue](https://github.com/orientechnologies/orientdb/issues/5438) about duplicate Edges to open this new issue. 

Software engineers, architects, developers, administrators, and others design data models. It is critical to manage efficiently **relationship level integrity**. In most cases, it is better to apply such constrains early during the design of the model rather than dealing with them when the database system is in use or when someone is programming the user interface. It is very important to notice that although these metadata are added during the creation of classes and edges, constrains are related to the **creation of instances**.
##### For Classes

Instances may not be created (Abstract Classes)
Instances may not be deleted 
Instances may not be renamed
Duplicate instances are not allowed
Subsets (e.g. Employee type is a subset of Person)
Generally speaking, an instance can have many types, i.e. possess specific attributes from many types (Freebase model !)
##### For Edges

More specific constrains for Edges
- Multiplicity
  - Cardinality 
    - one only
    - zero or one
    - one or more
    - zero or more
  - Participation
    - total (all instances participate in a relationship
    - some (there are instances that are not associated, connected)
- Other
  - Symmetric
  - Singular Inverse
- Domain-Range
  - Source Class
  - Target Class
- Aggregation
  - Vertex A is dependent on Vertex B (Composition, weak entity type)
  - Vertex A is independent of Vertex B
##### For Value Types

Value types are created when you specify a datatype, e.g. birth date, or length of a table. 
- Single instance (i.e. each text, number, etc, is recorded ONCE)
- Appear only as Targets, i.e. on the Head (in) of an edge

This is part of the famous single instance handling on state of the art database management system, see AtomicDB and Sentences Associative DBMS.

I believe such enhancements will boost productivity with OrientDB and progressively will lead data modeling to a new age of information management.

**Comment by smolinari** [comment]
:+1: 

Scott

**Comment by eugene-kamenev** [comment]
+1, will watch for this

**Comment by smolinari** [comment]
Doing some research, thanks to  @healiseu, I came across an article that points out what "data structure semantics" is all about. I think, if a database can do all of these points, if a database can cover most of the data structure semantics, then it is the perfect database.

Below are the elements of semantic structures with an explanation and I've also noted how I think ODB covers them (or not):

**Optionality.** This rule determines whether a property may be valued or not (e.g., NULLS ALLOWED) or whether an entity can exist only in association with another entity. An example would be the every-employee-must-have-a-supervisor case cited above.

For null values, ODB has the `NOTNULL` property attribute.

*For relationship enforcement, I am not completely certain, if ODB has a way to enforce this.* 

**Cardinality.** This rule determines whether a property may be multivalued and, if so, how many values it may have. It also determines how many entities of a given type may be associated with how many entities of another given type, or how many entities may participate in a given role of a single association. An example might be that a year must have 12 months or that exactly two parents produce one child, but each parent could produce multiple children, and each child can be produced by a different pair of parents as long as one parent is a mother and the other is a father.

Multivalued Properties. I think this can be done with embedded records, lists, maps, etc.

*The relationship cardinality can also be done in ODB, but not to the fidelity of the examples listed.*

**Ordinality.** This rule asserts that data is meaningfully presented in a specific order. The order may imply chronology or order of significance. Although this could be achieved using an attribute such as sequence number or entry date and time, these are often artifices intended to enforce a natural dimension of the meaning of the data collection. Using ordered successions can trigger events based on the position of something in a list, such as a discount offer based on purchasing an item and getting a second of equal or lesser value at half price.

*Order can only be loosely controlled in ODB. I believe indexes can't be defined to be in a certain order.* 

**Exclusivity.** This rule asserts that if one property is present in an entity or if one entity type is present in an association, then another must be excluded. For instance, an order must be associated with either a sales rep or a distributor or a beverage shipment may consist in either cases of cans or bottles, but it must consist entirely in either cans or bottles — they can’t be mixed.

*Not sure this is possible at all with ODB. This is probably left up to business logic in the application*

**Dependency.** This rule asserts that an entity derives its identity from another entity and cannot meaningfully exist on its own. For instance, an order must have a customer; it cannot exist without one. This is different from the employee/supervisor case in that an employee can be transferred from one supervisor to another and still maintain the same meaning, but an order cannot be switched from one customer to another.

Typical master/ child dependency. This is possible with embedded relationships.

*Containment.* This rule asserts that an entity exists only in the context of another containing entity and cannot be transferred. If the containing entity is destroyed, then all its contents are destroyed. All contained entities must be accessed through the containing entity. For example, a shipping address exists only within the context of a customer.

Same as above. Embedded relationships cover containment.

*Roles.* This rule asserts that the meaning, and therefore the use, of an entity is determined by its context in association with another entity. For instance, an association of staffing might consist in a role with a cardinality of one, called supervisor, and another role with a cardinality of many called staff members, where both roles are filled by employee entities. This rule would ensure that an employee can be a supervisor or a staff member or both, and staffing associates one or more staff members with a supervisor. Note that in this case an exclusivity rule may stipulate that an employee cannot be a supervisor and staff member in the same staffing association and that an employee cannot be his/her own supervisor’s supervisor.

Roles can be achieved through edge constraints. 

**Recursion.** This rule permits entities of a given type to be contained within other entities of the same type. For instance, in a parts assembly, a part may comprise other parts and may also be a component of a higher order part. This particular sort of structure, called a “bill of materials” structure, is key for manufacturing applications.

Recursion is possible through edges pointing back to the same vertex. 

**Type hierarchies.** This rule enables an entity type to inherit the characteristics of another entity type as a subtype, which supports automatic aggregation among entities of different but related types and reporting at multiple levels of abstraction. For example, a car, a truck, and a motorcycle are all subtypes of motor vehicles, which is a subtype of vehicle. Another subtype of vehicle is pedal vehicle, which includes the subtypes bicycle, foot scooter, skateboard, and so forth. Thus, we can report on cars, motor vehicles, or vehicles.

I do believe class inheritance in ODB can cover type hierarchies. 

So, ODB is pretty good in covering the data semantic structures. I'd appreciate if one of the ODB team could confirm what I've said above. The sentences in italics are where I am not certain. 

Scott
