### ISSUE TITLE
Performance can be improved with adding simple caches for reflection calls in Object API

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5443]
When profiling I found out that several methods used in the Object API use a lot of reflection and that this can cause slowing down because a lot of these calls are slow.

This can be remedied by caching results of these calls. It can be cached for operations for which the result never changes, for instance the Fields of a Class, getting the annotations of a class, etc. 

I propose to implement this at key places in the Object API. I'm preparing a pull request with some simple changes that resulted in a 50% performance gain in some calls for us, especially when the caches have been warmed up.

**Comment by luigidellaquila** [comment]
Hi @wouterv 

It's definitely a good idea. I'm marking it as an enhancement.
A PR will be very appreciated

@tglman I'm assigning this issue to you in case support is needed.

Thanks

Luigi

**Comment by wouterv** [comment]
The PR is already created: #5444

**Comment by wouterv** [comment]
New PR after comments: #5462

**Comment by wouterv** [comment]
PR was merged into 2.1.x

**Comment by wouterv** [comment]
@luigidellaquila Shouldnt this get label 2.1.8?

**Comment by luigidellaquila** [comment]
Hi @wouterv 

Yes, definitely, I missed it because it was not flagged as 2.1.x

@tglman was it also ported to develop?

Thanks

Luigi

**Comment by tglman** [comment]
yes is also in develop.
