### ISSUE TITLE
Using maxdepth and while in v2.1.4 traversal

### ISSUE THREAD

**Issue by karbar09** [orientechnologies/orientdb#5445]
I am using orientdb v2.1.4
Is it possible to do an orientdb traversal from a target record with a while condition and a maxdepth parameter in either SQL or the Java API? For example:

```
traverse all() from TargetRecordID maxdepth 25 while @class <> 'some_edge_class'
```

**The orientdb parser seems to apply the maxdepth condition and ignores the while condition -- This seems to be a bug because the [orient db manual](http://orientdb.com/docs/2.1/SQL-Traverse.html) seems to allow this syntax.**

As a side note: I use the while condition because I have 10 different edge classes overall, but I wish to **do the traversal while excluding a subset (~3) of the edge classes**.

**Comment by pkoppstein** [comment]
Please note that using 2.1.7-SNAPSHOT's console.sh, a syntactically well-formed query of this type produces a parsing error:

    traverse all() from #9:147 maxdepth 25 while @class <> 'followed_by'
    Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException

**Comment by luigidellaquila** [comment]
Hi @karbar09 

WHILE and MAXDEPTH cannot be used together in a traverse query, so the parsing error is the expected behavior

Closing, thanks

Luigi
