### ISSUE TITLE
Silent failure when incorrectly querying for edges

### ISSUE THREAD

**Issue by lodrion** [orientechnologies/orientdb#5446]
SELECT EXPAND( inE(MyEdgeName) ) FROM #62:4 limit -1
does not fail, but instead returns ALL of incoming edges

quoting the name, on the other hand produces the correct results
SELECT EXPAND( inE("MyEdgeName") ) FROM #62:4 limit -1

**Comment by lvca** [comment]
`MyEdgeName` is replaced with the field with name `MyEdgeName`, but since it doesn't exist, it's null. inE(null) means get all the incoming edges, so it's correct.

**Comment by lodrion** [comment]
Is there any way to detect these cases (some kind of strict mode)? While this is technically correct, it can (and does) lead to hard to find bugs. 

The existing strict mode is a reverse of this -- it makes all fields required. What I want is requests for fields that are not in the schema to fail

**Comment by luigidellaquila** [comment]
Hi @lodrion 

I'm afraid there is no automatic way to check it. Strict mode checks schema only during insert/update operations.

Thanks

Luigi
