### ISSUE TITLE
Can I view my uni-directional links on the graph editor ?

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5447]
I fully understand that you have made graph editor especially for the GRAPH model with the edges, but I cannot see the reason why it can't be used to show the uni-directional links that one make on the DOCUMENT model ?

**Comment by maggiolo00** [comment]
hi @healiseu 

it is not possible. It has been designed for Graph Model.
We could leave this open as enhancement but with low priority

Thanks

**Comment by lvca** [comment]
+1, it would be nice to extend our uni-directional links to the graph model in a better way.
