### ISSUE TITLE
Error about changing cache size when starting 2.1.7 in embedded mode

### ISSUE THREAD

**Issue by mcculls** [orientechnologies/orientdb#5457]
When starting OrientDB 2.1.7 in embedded mode we now see this error logged:
```
ERROR com.orientechnologies.orient.core.config.OGlobalConfiguration$1 - Can not change cache size in runtime because storage engine plocal was not registered
```
This didn't happen in 2.1.6 and appears to be related to 9268493 which added a change-listener for the disk-cache configuration item. Unfortunately this change-listener appears to be triggered by OrientDB's `autoConfig` mechanism:
```
	at com.orientechnologies.orient.core.config.OGlobalConfiguration$1.change(OGlobalConfiguration.java:98)
	at com.orientechnologies.orient.core.config.OGlobalConfiguration.setValue(OGlobalConfiguration.java:812)
	at com.orientechnologies.orient.core.config.OGlobalConfiguration.autoConfigDiskCacheSize(OGlobalConfiguration.java:772)
	at com.orientechnologies.orient.core.config.OGlobalConfiguration.autoConfig(OGlobalConfiguration.java:737)
	at com.orientechnologies.orient.core.config.OGlobalConfiguration.<clinit>(OGlobalConfiguration.java:640)
	at com.orientechnologies.common.profiler.OProfilerStub.<init>(OProfilerStub.java:38)
	at com.orientechnologies.orient.core.Orient.startup(Orient.java:199)
	at com.orientechnologies.orient.core.Orient.<clinit>(Orient.java:87)
``` 
Since `OLocalPaginatedStorage` reads the value of `DISK_CACHE_SIZE` at initialization it seems odd to have `OGlobalConfiguration` log an error, especially when this is OrientDB itself auto-configuring the disk cache.

The simplest fix is to remove this error; I'm not sure it's actually that useful and setting the value before the 'plocal' storage is initialized will work because 'plocal' will read this setting when it initializes. The alternative would be to update the change-listener so it doesn't fire during the `autoConfig` phase.

**Comment by luigidellaquila** [comment]
Hi @mcculls 

this could be related to a fix we made on global configuration settings at runtime.

We are checking it and we'll let you know in short

Thanks

Luigi

**Comment by laa** [comment]
Hi it is log message with different level than needef fixed in 2.2 will
back port to 2.1 soon .

On Fri, Dec 11, 2015, 17:33 luigidellaquila <notifications@github.com>
wrote:

> Hi @mcculls <https://github.com/mcculls>
>
> this could be related to a fix we made on global configuration settings at
> runtime.
>
> We are checking it and we'll let you know in short
>
> Thanks
>
> Luigi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5457#issuecomment-163965356>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by laa** [comment]
Fixed.

**Comment by martingg88** [comment]
do you already publish this fix to repository?

**Comment by gfinger** [comment]
I've got the same error on 2.1.7. Went back to 2.1.6.

**Comment by laa** [comment]
It is fixed in 2.1.8 and detected in 2.1.7 no reason to reopen it.

чт, 24 Дек 2015, 5:19, Luca Garulli <notifications@github.com>:

> Reopened #5457 <https://github.com/orientechnologies/orientdb/issues/5457>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5457#event-499922679>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by lvca** [comment]
Ok, so I've assigned the milestone, so it's clear to everybody when it has been fixed.

**Comment by lvca** [comment]
Ok, so I've assigned the milestone, so it's clear to everybody when it has been fixed.
