### ISSUE TITLE
Add statistic which will fully explain command/query performance

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5458]
After https://github.com/orientechnologies/orientdb/issues/5157 we will have stastic how much pages are affected during handling of command in each thread. But to have complete understanding of  system performance in general following parameters should be gathered (some of them already implemented):

1.  Read speed of data in megabytes on cache level for the last second.
2. Read speed of data in pages on cache level for the last second.
3. Read speed of data on file system level in megabytes for the last second.
4. Read speed of data on file system level in pages for the last second.
5.  Write speed of data in megabytes on cache level for the last second.
6. Write speed of data in pages on cache level for the last second.
7. Write speed of data on file system level in megabytes for the last second.
8. Write speed of data on file system level in pages for the last second.
9. Read cache hit rate.
10. Atomic operation commit time in average for the last n operations (configurable, 1000 by default)

The same parameters will be gathered in issue #5157 .

**Comment by StarpTech** [comment]
@laa also network latency could play a big in role in such performance analyses.

**Comment by laa** [comment]
@StarpTech agree but that is remote storage, but this issue has storage local scope.

**Comment by laa** [comment]
Fixed.
