### ISSUE TITLE
Issue with building orientdb

### ISSUE THREAD

**Issue by akash3456** [orientechnologies/orientdb#5460]
I have an issue when i build orientdb with i run the  ant clean install

/home/akashpaul/orientdb/build.xml:133: The following error occurred while executing this line:
/home/akashpaul/orientdb/build.xml:21: The following error occurred while executing this line:
/home/akashpaul/orientdb/_base/base-build.xml:44: Compile failed; see the compiler error output for details.

build seems to fail, is this a stable version and would it compile on ubuntu 15.10?

**Comment by smolinari** [comment]
Try with maven. 

`mvn clean install`

Scott

**Comment by akash3456** [comment]
Build still failed

**Comment by luigidellaquila** [comment]
Hi @akash3456 

which branch are you trying to build? Could you please also specify which Java version you are using and post the build errors?

Thanks

Luigi

**Comment by akash3456** [comment]
the current github version as ive only just checked it out and attempting
to install it which is 2.1x.

**Comment by akash3456** [comment]
2.1.7 i think if that helps

**Comment by akash3456** [comment]
ok i am using java 7 and im getting the following as build errors: 

/home/akashpaul/orientdb/build.xml:133: The following error occurred while executing this line:
/home/akashpaul/orientdb/build.xml:21: The following error occurred while executing this line:
/home/akashpaul/orientdb/_base/base-build.xml:44: Compile failed; see the compiler error output for details.

**Comment by akash3456** [comment]
something is wrong with my java install as several syntax errors appear in the compilation files when i try to build the orientdb package

**Comment by smolinari** [comment]
I believe ODB needs Java 8, and if possible, Oracle Java 8.

Scott

**Comment by akash3456** [comment]
ok jdk 1.8 as well right?

**Comment by smolinari** [comment]
Yes.

Scott

**Comment by akash3456** [comment]
Sorrys what should the java_home variable contain? which path to jdk or to oracle java-8?

**Comment by smolinari** [comment]
I believe...

```
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export JRE_HOME=/usr/lib/jvm/java-8-oracle
```

Scott

**Comment by akash3456** [comment]
which files is it? bashrc right?

**Comment by smolinari** [comment]
Not sure what you mean. The above is all I use to install and run ODB. 

Scott

**Comment by akash3456** [comment]
i have installed java 8 and i still get : 

Buildfile: /home/akashpaul/orientdb/build.xml
BUILD FAILED
/home/akashpaul/orientdb/build.xml:16: Unable to write to /home/akashpaul/orientdb/build.number.

**Comment by smolinari** [comment]
Sounds like a permissions problem.

Scott

**Comment by akash3456** [comment]
on orientdb folder?

**Comment by akash3456** [comment]
ok run as root but i get the following : 

BUILD FAILED
/home/akashpaul/orientdb/build.xml:133: The following error occurred while executing this line:
/home/akashpaul/orientdb/build.xml:21: The following error occurred while executing this line:
/home/akashpaul/orientdb/_base/base-build.xml:44: Compile failed; see the compiler error output for details.

**Comment by smolinari** [comment]
I have no idea what could be wrong. Maybe you could try and download the precompiled version?

Scott

**Comment by akash3456** [comment]
is that available on orientdb website then?

**Comment by smolinari** [comment]
Yes. http://orientdb.com/download/

Scott

**Comment by akash3456** [comment]
ok thanks the service is up and running now.

**Comment by luigidellaquila** [comment]
Great, can I close this?

Thanks

Luigi

**Comment by akash3456** [comment]
Yes go ahead thanks for your help

**Comment by luigidellaquila** [comment]
Thanks, closing

Luigi
