### ISSUE TITLE
Exclusive Lock on Storage

### ISSUE THREAD

**Issue by testark** [orientechnologies/orientdb#5463]
I would like to ask whether [this](http://stackoverflow.com/questions/30044313/what-does-the-exclusive-lock-on-storage-for-orientdb-entail-exactly) is still true in the current versions of OrientDB.

Furthermore, @lvca pointed out that

> OrientDB 3.0 will be GA on July-August 2015.

I'd like to ask whether, four months past that period now, there can be any hope for such a release in the foreseeable future.

**Comment by smolinari** [comment]
Considering that quote was written in 2012, I wouldn't be too strict with Luca for his prediction at the time.

From the roadmap, 3.0 is supposed to be out April 2016, 

http://orientdb.com/docs/2.1/Roadmap.html

AFAIK, the locking is still the same for transactions and is still slated to be improved in 3.0. 

However, in 2.1.7, the team added a feature to allow updates to a graph to be done without the need of transactions for consistency.

http://orientdb.com/docs/2.1/Graph-Consistency.html

Not sure that is what you were looking for, but I would can imagine it is generally good to know. :smile:  

Scott

**Comment by testark** [comment]
@smolinari the quote was done in a comment on May 11, 2015. Apart from that, it's good to know that it has been added. Will check on this feature ASAP.

**Comment by smolinari** [comment]
Yeah, sorry about that. I misunderstood the date as May 2012, not May 12th. I bet it must be a Typo on Luca's part. That would also mean the roadmap needs updating too.

Scott.
