### ISSUE TITLE
orient sql doesnt allow escaped chars in lucene query string

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#5469]
this query

select from c1 where [a] LUCENE "+a:'abc\:xyz'"

throws com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 42.  Encountered: ":" (58), after : "\"(+a:\'abc\\"

According to lucene syntax, ':' could be escaped with backslash

**Comment by luigidellaquila** [comment]
Hi @vantonov1 

I think you have to quote the backslash inside the string:

```
select from c1 where [a] LUCENE "+a:'abc\\:xyz'"
```

Please let me know if it works

Thanks

Luigi

**Comment by vantonov1** [comment]
yes, that way it works, but looks awful

**Comment by luigidellaquila** [comment]
@vantonov1 

backslash character is used to quote following characters, eg. if you need to put a double quote in the string you can write
```
select from Foo where name = "foo \" bar"
```
Characters that can be encoded are:
- `\n` for newline
- `\t` for tab
- `\'` for single quote
- `\"` for double quote
- `\\` for backslash

As a general rule you can consider it the same as the standard quoting in Java.

As you can understand, if you allow backslash to be used alone, the string `"\n"` can be considered two characters (a backslash and a "n") or a newline, so it would be ambiguous.

This is the only reason why you have to quote the backslash.

**Comment by vantonov1** [comment]
Yes. But here is _lucene_ query, and Lucene also uses quotes. And in Java
string, it doubles.... Imho it would be better to pass all lucene queries
"as is" to lucene analyzer...

On Tue, Dec 15, 2015 at 5:17 PM, luigidellaquila <notifications@github.com>
wrote:

> @vantonov1 <https://github.com/vantonov1>
>
> backslash character is used to quote following characters, eg. if you need
> to put a double quote in the string you can write
>
> select from Foo where name = "foo \" bar"
>
> Characters that can be encoded are:
>
>    - \n for newline
>    - \t for tab
>    - \' for single quote
>    - \" for double quote
>    - \\ for backslash
>
> As a general rule you can consider it the same as the standard quoting in
> Java.
>
> As you can understand, if you allow backslash to be used alone, the string
> "\n" can be considered two characters (a backslash and a "n") or a
> newline, so it would be ambiguous.
>
> This is the only reason why you have to quote the backslash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5469#issuecomment-164777360>
> .
>



-- 



Valeri.
