### ISSUE TITLE
Request for bugfix-only release

### ISSUE THREAD

**Issue by Amberos** [orientechnologies/orientdb#5471]
We went into production with OrientDB two weeks ago and so far it's been a success. Of course, we did thorough testing up front, so our confidence was high. With roughly 50K transactions per day and ~800 users depending on stability, this is a good test for us before going "all in".

With that said, we did encounter a few bugs during testing (there are github issues for all these), but we found acceptable workarounds. 

As for the request: I think it would be a good idea to have a "bug fix only" major release to make OrientDB a really solid product. At this point, I feel robustness is much more important than new features.

For instance, we struggled a bit with various OOM situations as well as replication hangs, and we'd like to see those kinds of issues getting a fundamental fix to avoid unnecessary workarounds (partitioning of data, splitting up queries, avoid certain sort criteria, etc)

Overall, we're very happy. The ability to mix SQL/JDBC (for our reporting tool) with a document oriented store is exactly what we needed. Thanks to the team for an excellent product!

**Comment by StarpTech** [comment]
Feel the same. User with orientdb in production can not wait until a official release is deployed. I think the stability must be guaranteed by software tests and bug fixes should be provided instantly. yes, orientdb is great and the support team is fast and competent at the same time. Thanks!

**Comment by smolinari** [comment]
I've been following (and supporting where I can) OrientDB for a few months now. I came from being a "lurker" and fan of MongoDB. Despite my high interest in MongoDB, the fact it can't relate data easily was a constant nagging issue in the back of my head. I decided to start looking for alternatives and landed with ODB. ODB has a product, which is extremely attractive. It can cover a lot of use cases and does it relatively smartly too. 

The fast support from the dev team and the "hands on" CEO are both fantastic plus points for ODB too. 

And despite ODB's growing popularity, I also have to agree with @StarpTech and @Amberos, there are still some things holding ODB back from gaining even more success for its team and its customers.

These are the points in order of importance, from my perspective:

1. The general stability of the software. It is good for the basic DBMS chores, but when people start to take it for a real run, things often seem to "flake out" on them. I am not sure where it comes from to be honest, but that kind of customer frustration should be an exception. It should be quite rare, rarer than it is right now for sure. 
2. The abstraction of the SQL could be simpler. Some contributors are also supporting improvements in this area. Others have made suggestions, like in the handling of edge multiplicity and cardinality. Getting these things right in ODB isn't simple.
3. Documentation (which I am trying to help with in proofreading and organization). There also needs to be more examples. A general complaint. I see it too. Often, the team here have to help customers with their queries. I am not sure if it is a problem with documentation, general knowledge on the customer's part (which docs should help with) or with point 2. But the fact so many customers end up asking about how to best do queries and all the effort spent explaining it to them, should be a sign for a need for improvement. is definitely time better spent working on the software.

I am now a fan of ODB. It is a fantastic tool overall. It just needs the kind of polish that other DBMSes have. I am not sure a "bug fix only" point version is the solution either. When version 3 comes out, the same circumstances that caused the older versions to miss the polish will still be there. I can't see internally what is going on in the ODB business, but I'd venture to say, processes, policies and culture are what need changing/ improvements. They, in sum, are what produce the results. I hope Luca agrees and finds the missing keys to get ODB to that really top class product we all want to absolutely love. It isn't that far off!

Scott

**Comment by StarpTech** [comment]
@scott awesome well expressed in a nutshell.

**Comment by StarpTech** [comment]
Now it is still possible to convince people for orientdb but when nothing will be changed then I cant recommend odb anymore to customers or friends and this is sad. I hope we get it!

**Comment by Amberos** [comment]
@StarpTech I am confident in recommending OrientDB despite the flaws. All the competitors have flaws as well, and this is just a fact of life. MongoDB silently dropped data for us. That's inexcusable and the kind of flaw that makes me NOT recommend a product. I'm sure OrientDB can go corrupt like any other database, but I'm fairly sure it doesn't silently drop presumably replicated data.

Setting aside half a year or so to *only* improving robustness and documentation would raise the quality of this project tremendously. 

This is an open source project and people tend to prefer working on new and exciting stuff, which is always a challenge.

**Comment by smolinari** [comment]
> Setting aside half a year or so to only improving robustness and documentation would raise the quality of this project tremendously.

I can't deny this would help for the current version. In fact, it probably would. However, a company or an organisation (or an OSS project) shouldn't really be chasing after better quality. That is costly and doesn't give customers the basis to be able to trust the product 100%. 

What we need is quality in design and production, from the git go. 

Scott

**Comment by Amberos** [comment]
>  However, a company or an organisation (or an OSS project) shouldn't really be chasing after better quality

That may be true in general, but is it true for a *database* company? I think not.

**Comment by smolinari** [comment]
>  is it true for a database company?

It is true for any company. 

Going after and fixing the current ODB "product" quality in a "just a bug fix major release" is one business decision and it certainly can be made. Going after the reasons or sources for even having to make that decision is another. My concern is the latter business decision isn't going to be accounted for, when it is actually more much important than the former.

Scott

**Comment by Amberos** [comment]
That made no sense to me

**Comment by smolinari** [comment]
In other words, there are reasons why ODB doesn't have the quality it should. To fix the quality in a "bug fix only version", but at the same time ignore those reasons, would be a seriously wasteful undertaking. One should learn from one's own mistakes. 

Put another way, if the reasons for ODB not having the quality it should aren't analyzed and corrected, we'll be asking for a "bug fix only version" after version 3 is out too. 

Scott

**Comment by Amberos** [comment]
You misunderstood my intention with this issue. I have no idea what problems the project may or may not have. What I'm asking for is to do for OrientDb what Apple did with Snow Leopard. They invested a year focusing on quality only, not on new features. This created the foundation for a string of high quality osx releases. Now they did something similar with El Capitan.

**Comment by smolinari** [comment]
And Apple can afford to stick time and money in chasing quality. I find it interesting that that is even the case.

At any rate, it is better, smarter, less expensive, more efficient, easier to sell, etc. etc. when quality is designed and produced from the start. 

Again, I am not against concentration on improving the quality of the current product . I am against having to relive that same situation twice.

Scott

**Comment by smolinari** [comment]
Not completely on topic, but you might find it interesting.

https://www.linkedin.com/pulse/mongodb-32-now-powered-postgresql-john-de-goes

I like what John says in the comments. 

>the winning systems of tomorrow will combine the best characteristics of relational systems with the best characteristics of non- and post-relational systems, which is what we are seeing as PostgreSQL and other relational players gain better support for semi-structured data and horizontal scalability, even while NoSQL systems gain better data accessibility (N1QL, CQL) and the ability to perform joins.

The winning systems will have the best of relational, with the best of no-SQL and scalable too. 

Sounds like OrientDB, doesn't it? :wink:

Scott

**Comment by healiseu** [comment]
OrientDB is also a great product for learning how to work with Document, Graph databases with an excellent hands-on user experience. I am about to create a few blog posts demonstrating bidirectional linking with Document and lightweight edges with Graph databases. I have also taken a decision to release for free a Wolfram Language (Mathematica) API for OrientDB.

Regarding to production version, I think @Amberos is right, existing features of the system MUST BE TESTED to an extreme on real working environments and a bullet proof version has to be created. Most important is to test ACID compatibility and report on successful user cases.

**Comment by smolinari** [comment]
Looking forward to the blog posts @healiseu. Please make a note in the ODB Google group, when you publish any of them. 

And I think we all agree, any current version of ODB needs to be as bulletproof as possible. :+1: 

Scott
