### ISSUE TITLE
Error when using EMBEDDED LINKEDCLASS data type with INSERT, UPDATE Content

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5474]
Hi, I am using OrientDB community edition 2.1.6 and I have a problem using **EMBEDDED**, **EMBEDDEDSET**, etc data types and the INSERT CONTENT, UPDATE CONTENT sql commands when you add the attribute **LINKEDCLASS** on the embedded type property. Try the following code to reproduce it.

``` sql
create class Person
create property Person.nameFirst STRING
create property Person.nameLast STRING

create class Film
create property Film.title STRING
create property Film.actor EMBEDDED Person

insert into Film set title="Catch me if you can", actor={"nameFirst":"Leonardo","nameLast":"DiCaprio"}

insert into Film CONTENT {"actor":{"nameFirst":"Leonardo","nameLast":"DiCaprio"}}
```

The error occurs when the `INSERT into Film CONTENT` command is executed and the message is

`The field 'Film.actor' has been declared as EMBEDDED but an incompatible type is used. Value: {nameFirst=Leonardo, nameLast=DiCaprio}`

I believe my syntax for this INSERT command is correct, if not please help

**Comment by smolinari** [comment]
I believe the CONTENT operator is only for schema-less data (in JSON format). If you do 

`INSERT INTO Film CONTENT {"actor":{"nameFirst":"Leonardo","nameLast":"DiCaprio"}}`

without declaring the film.actor property, ODB will insert the record with no errors. The error is basically saying, you have a field called "Film.actor", but you aren't inserting it in a fashion I can understand for that field's schema, as I am looking for something that deals with the schema you have set up.

In fact, if you try and add the Film.actor field as schema after adding the schema-less version, ODB balks (correctly) with this error.

>com.orientechnologies.orient.core.exception.OSchemaException: The database contains some schema-less data in the property 'Film.actor' that is not compatible with the type EMBEDDED. Fix those records and change the schema again

Scott

**Comment by luigidellaquila** [comment]
Hi @healiseu 

the "actor" property in that case is parsed as a generic embedded map, this is why it does not match the schema.

To explicitly declare that it's a person, you have to declare that it's a document (`"@type":"d"`) and that its class is Person (`"@class":"Person"`)

```
insert into Film CONTENT {"actor":{"@type":"d", "@class":"Person", "nameFirst":"Leonardo","nameLast":"DiCaprio"}}
```

I think the engine can be enhanced to infer embedded types in this case, I'll leave it open and I'll mark it as an enhancement

Thanks

Luigi

**Comment by healiseu** [comment]
@smolinari  as a user I expect the CONTENT operator to be used in both schema-less and schema-full operation in the same way like the SET operator. And as I am writing this sentence there is a more official answer from @luigidellaquila that confirms this, thank you guys for your prompt response.

I do not know the internals for the differences between SET and CONTENT but obviously in the example I have described if this works
```SQL
INSERT INTO Film SET title="Catch me if you can", actor= {"nameFirst":"Leonardo","nameLast":"DiCaprio"}`
```
One expects that this will work too
```SQL
INSERT INTO Film CONTENT {"actor":{"nameFirst":"Leonardo","nameLast":"DiCaprio"}}
```
Therefore I think @luigidellaquila marked it correctly as an enhancement, to avoid any future frustration on the use of CONTENT with schema-full operations.

**Comment by smolinari** [comment]
I was just trying to come up with a plausible reason why it didn't work. Now I see it is possible to add the metadata into the query with CONTENT to make it work. Something I just learned myself and something I overlooked in the docs. 

@luigidellaquila - can this also be done with INSERT INTO () VALUES ()?

Scott

**Comment by healiseu** [comment]
Thank you Scott @smolinari and yes you are right, one should expect a consistent behavior in the use of SQL commands and other operations.

**Comment by luigidellaquila** [comment]
Hi @smolinari 

yes, it's possible with INSERT INTO as well. 

I don't know the exact reason why it does not infer the correct type, I'll check it and I'll let you know

Thanks

Luigi

**Comment by smolinari** [comment]
All this could be a good section for the "Insert" section in "SQL Reference" of the documentation too.

"The three ways to do inserts" (or however more there are.....LOL!)

Scott

**Comment by luigidellaquila** [comment]
@smolinari you are forgetting about CREATE VERTEX, CREATE EDGE and so on  ;-)

Luigi

**Comment by smolinari** [comment]
Ah yes! 

So we have....

INSERT INTO x SET y = 'ODB is great!'
INSERT INTO x CONTENT { "y" : "ODB is great!" }
INSERT INTO x (y) VALUES ('ODB is Great!')
CREATE VERTEX/EDGE x SET y = 'ODB is great!'
CREATE VERTEX/EDGE x CONTENT { "y" : "ODB is great!" }

Did I forget anything?

Is there a more in-depth explanation about how to use the JSON format, like how to include/ use the metadata?

Scott

**Comment by healiseu** [comment]
@smolinari and @luigidellaquila 
```sql
insert into Film (title,actor) VALUES ("Catch me if you can", {"nameFirst":"Jack","nameLast":"Brown"})
```
The field 'Film.actor' has been declared as EMBEDDED but an incompatible type is used. Value: {nameLast=Brown, nameFirst=Jack}

It looks like the only one that infers the correct type is the INSERT INTO set

**Comment by healiseu** [comment]
About the CREATE VERTEX/EDGE, etc..... and there is also the UPDATE ...... and... and...

In my opinion I would try to keep them separated, and have two major sections on the manual one for Graph databases and another for Document. It is also very misleading the fact that a lot of people when they talk about Graph databases they usually refer to property graph databases with bidirectional links that act as Uni-directional edges on the graph. But other type of graph databases based on direct links can be built.

Regarding to the many commands available and all these options you have, from the user point of view it creates confusion. You need more abstraction here. For example an
ADD, GET, UPD, DEL for Operation 
and
CLASS, PROPERTY, RECORD for Operands

I have started doing that in my Mathematica API for OrientDB and hopefully I will release it soon....

**Comment by smolinari** [comment]
> You need more abstraction here. 

Totally agree. :+1: 

Scott

**Comment by luigidellaquila** [comment]
Yes, I agree, doc pages for INSERT and CREATE are separated, but maybe having a high level explanation of concepts and two different sections of docs, one for document an one for graph, is a good idea

Luigi
