### ISSUE TITLE
REGRESSION in 2.1.8 hotfix - Filter by $depth does not work anymore

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5477]
```sql
select * from (traverse out('BroughtIntoRight', 'BroughtIntoLeft') from (select from Node WHERE Mid = '566f54dbfc35c33412723766' ) ) where $depth >= 0 and $depth <= 15
```
Result
```sql
[]
```

but this works:
```sql
SELECT * FROM (TRAVERSE out('BroughtIntoRight', 'BroughtIntoLeft') FROM (SELECT FROM Node WHERE Mid = '566f54dbfc35c33412723766' ) WHILE $depth <= 3 )
```

Works in 2.1.7

**Comment by StarpTech** [comment]
@luigidellaquila I need ASAP a hotfix this will crash our whole environment

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

It's already fixed, do you remember that comment where I told you I had to revert a fix? It was for this regression. 

2.1.8 will include the fix of course, but in the meantime I'll send you another snapshot.

Thanks

Luigi

**Comment by StarpTech** [comment]
HI @luigidellaquila yes I remember but you also said that I can ignore your hint about that circumstance .

**Comment by StarpTech** [comment]
@luigidellaquila any updates? I'm waiting for the snapshot build.

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

This is the candidate for 2.1.8

https://drive.google.com/open?id=0B46-XQEZNnG3bTJ4cVdNdWEyQUk

We are still going through our QA process, it will be officially released as soon as all the validation tests are completed

Thanks

Luigi
