### ISSUE TITLE
ER: select path() from (traverse ...)

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5479]
Currently (Version 2.1.8), there doesn't seem to be a way (or at least
there doesn't seem to be a documented way that works) to convert paths
(in the sense of $path) into a result-set.

By contrast:
- "select $path from (traverse ...)" gives string representations of the paths being traversed;
- "select expand(shortestPath) from shortestPath(...) ...." gives the path as a result set

Since both:
    'select $path from (traverse ...)' and
    'select traversedVertex(0,100) from (traverse ...)'

are supported, it would, I think, make sense to support: 'select
path() from (traverse ...)', where path() would be a list of the
vertices and edges in the path, so that one could expand(_) it.

NOTE: One might expect the following query to emit both the vertices
and edges along a path, but it only emits vertices:

```
select expand(traversedElement)
from (select traversedElement(0,10)
      from (traverse out(), inE() from #11:0 ) )
      where last(traversedElement) = #11:3
```

Is that a bug?  If `traversedElement(_,_)` is supposed to return all the
vertices and edges in each path in order, then this ER boils down to a
bug report together with an ER to the effect that there should be a
variant of or enhancement to traversedElement() that would obviate
the need to specify a bound.

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

yes, it makes sense. I'm marking it as an enhancement and as contributor friendly.

For you query, could you please try this:
```
select expand(traversedElement)
from (select traversedElement(0,10)
      from (traverse outE(), inV() from #11:0 ) )
      where last(traversedElement) = #11:3
```

**Comment by pkoppstein** [comment]
@luigidellaquilla - Thanks for reviewing the ER.

It is true that the query you mention returns both vertices and edges, but queries of that sort find too many paths.  In the present case, there is only one path from the start to the end vertex, but:

    select $path from (traverse outE(), inV() from #11:0) where traversedElement(-1) = #11:3;
    ----+------+-------------------------------------------------------------------------------------
    #   |@CLASS|$path                                                                                
    ----+------+-------------------------------------------------------------------------------------
    0   |null  |(#11:0).outE[0](#13:2).inV(#11:1).outE[0](#14:1).inV(#11:2).outE[1](#15:3)           
    1   |null  |(#11:0).outE[0](#13:2).inV(#11:1).outE[0](#14:1).inV(#11:2).outE[1](#15:3).inV(#11:3)
    ----+------+-------------------------------------------------------------------------------------

That is, the first result ends in an *edge*.  Since the query includes the condition `traversedElement(-1) = #11:3)`, this looks like a bug to me.

As I said, this ER might turn out to be a combination of a bug report and ER. If so, the bug seems quite serious to me, and hopefully it will get prioritized accordingly.

**Comment by lvca** [comment]
Not relevant anymore.
