### ISSUE TITLE
SErVER Can not change cache size in runtime because storage engine plocal was not registered

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5482]
any idea for following issue when start orientdb server for 2.1.7 version. 

SErVER Can not change cache size in runtime because storage engine plocal was not registered

**Comment by StarpTech** [comment]
@martingg88  This issue is fixed in 2.1.8

**Comment by martingg88** [comment]
fixed.

**Comment by martingg88** [comment]
hey..do u have any idea on following issue. it worked before but now it can't connect to database at all. 

Connecting to database [remote:localhost/voyage] with user 'root'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/var/lib/orientdb/voyage' with mode=rw

**Comment by StarpTech** [comment]
Correct access rights for the db files and orientdb?

**Comment by luigidellaquila** [comment]
Or trying to open a db created with a newer version of OrientDB?

**Comment by martingg88** [comment]
access right fro the database folder is absolute correct and it work before. 

@luigidellaquila the db is created before version 2.1.8 and have issue when open this database folder with 2.1.8 version. any idea how to solve this issue?

**Comment by martingg88** [comment]
here is the stack ..'


Connecting to database [remote:localhost/voyage] with user 'root'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/var/lib/orientdb/voyage' with mode=rw

Error: com.orientechnologies.common.concur.lock.OLockException: File '/var/lib/orientdb/voyage/internal.cpm' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database

**Comment by StarpTech** [comment]
@martingg88 Do you have open a orientdb console or another instance of orientdb?

**Comment by martingg88** [comment]
i hv reboot my server and open console to connect the database.

**Comment by StarpTech** [comment]
@martingg88 You have only one connection open to the db (via console) ?

**Comment by martingg88** [comment]
i dont' have any client connection to db yet.

**Comment by StarpTech** [comment]
ok then I don't know.

**Comment by StarpTech** [comment]
@martingg88 how do you open the db?

**Comment by martingg88** [comment]
i run the following in order but have that issue. 
1. ./console.sh
2. connect remote:localhost/voyage username password
3, db is locked

faint faint fain

**Comment by martingg88** [comment]
here is the log when i try to manual start the orientdb server. 

2015-12-18 08:36:59:763 WARNI {db=voyage} Storage 'voyage' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2015-12-18 08:36:59:763 INFO  {db=voyage} Looking for last checkpoint... [OLocalPaginatedStorage]
2015-12-18 08:36:59:778 INFO  {db=voyage} Found FUZZY checkpoint. [OLocalPaginatedStorage]
2015-12-18 08:36:59:780 INFO  {db=voyage} Data restore procedure from FUZZY checkpoint is started. [OLocalPaginatedStorage]
2015-12-18 08:36:59:783 WARNI {db=voyage} Non tx operation was used during data modification we will need index rebuild. [OLocalPaginatedStorage]
2015-12-18 08:36:59:784 WARNI {db=voyage} Record OFuzzyCheckpointStartRecord{lsn=OLogSequenceNumber{segment=0, position=63020707}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=OLogSequenceNumber{segment=0, position=62880838}} will be skipped during data restore. [OLocalPaginatedStorage]

**Comment by martingg88** [comment]
is there possible the server is locking for the db for recovering process while i'm try to connect db from console.sh?

**Comment by martingg88** [comment]
it's urgent please help for this issue otherwise our server will be down forever.

**Comment by StarpTech** [comment]
Yes, you cannot open a connection in console if your server is running.

**Comment by luigidellaquila** [comment]
Hi @martingg88 

does it open correctly with 2.1.7?

**Comment by martingg88** [comment]
yes it work for 2.1.7 and work for 2.1.8 few times then corrupted.

**Comment by luigidellaquila** [comment]
@martingg88 I tried to reproduce the problem locally, but without success.
How big is your db? Can you share it or something that allows me to reproduce it?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
just another thing: when you say that it works a few times, do you mean that if you stop and restart the server then it reconnetcts for a while?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
and again, how did you stop the db? If you hard killed the process, are you giving it time to do the full recovery?

**Comment by martingg88** [comment]
yes...the server try to hard kiled the orientdb process that cause my database corrupted. so what i should to to resolve this issue?

**Comment by luigidellaquila** [comment]
ah, so the server is killing OrientDB process? Did it happen once or is it happening every time you restart the server? This could be a matter of low memory.

Does the db recovery succeed? Could you please post the full console log?

Thanks

Luigi

**Comment by martingg88** [comment]
yes.. the server kill orientdb due to low memory. i don't think it run db recovery succeed. sorry i didn't keep the log. 
in case of db recovery fail and corrupt the db, what should i should do to recover the db

**Comment by martingg88** [comment]
in between what is the recommend memory needed to run this orientdb? 1024mb should be enough?

**Comment by martingg88** [comment]
any update on this?

**Comment by laa** [comment]
Hi @martingg88 ,

Let's do all steps one by one to recognize reason of your issue.
Do you use Linux/Windows/Mac OS ?

**Comment by martingg88** [comment]
yes...i'm using Linux centos 7 with 2 cores and 512mb RAM

**Comment by laa** [comment]
OK.
And if you right now open database you get exception that file is blocked,
do not you ?

Do you open this data database using server and remote: connection or
plocal: connection ?

On Tue, Dec 22, 2015 at 5:02 AM martingg88 <notifications@github.com> wrote:

> yes...i'm using Linux centos 7 with 2 cores and 512mb RAM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5482#issuecomment-166490072>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by martingg88** [comment]
i have not idea what cause the issue. The issue was gone after i restart my server few times.
Anyway, what is the recommended hardward specification to run your orientdb at linux server?

**Comment by laa** [comment]
Fixed in latest 2.1.x version
