### ISSUE TITLE
transaction commit no longer work for version 2.1.8

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5487]
here is the error stack

Error: com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit.

Error: java.lang.NullPointerException

**Comment by Jotschi** [comment]
@martingg88 Can you provide a full stack trace?

**Comment by martingg88** [comment]
i don't have the full stack now. it doesn't work with orientjs. can you try a simple sql transaction statement at you end?

**Comment by maseev** [comment]
It actually works if you run your query in the transaction by using the console.sh though. Not sure if it will work if I run a query from some Java code.

**Comment by luigidellaquila** [comment]
Hi @martingg88 

can you provide a simple test case to reproduce the problem?

Thanks

Luigi

**Comment by martingg88** [comment]
i will get back to you when i free as i'm stuck with the orientdb crash with my server.

**Comment by laa** [comment]
Hi @martingg88 ,
Could I ask you to create test, to resolve given issue ?

**Comment by martingg88** [comment]
please close this issue. I dun have this issue again.
