### ISSUE TITLE
ORecordSerializerBinary

### ISSUE THREAD

**Issue by tzsolti** [orientechnologies/orientdb#5488]
I'm using Orientdb 2.1.8 and found this error in my logs:

com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary - Error deserializing record with id #22:1 send this data for debugging: ABZvY19jaGFubmVsc20AAAFfaQAAAWCPAQAAAWaRAQAAAXaTAQAAAXmVAQAAAX+XAQAAAYKZAQAAAYabAQAAAYmfAQAAAY+dAQAAAZMwb3V0X2NoYW5uZWxfc3Vic2NyaXB0aW9uAAABlhYqb3V0X2NoYW5uZWxfYV9zZXJ2aWNlAAABpRYqb3V0X2NoYW5uZWxfY19zZXJ2aWNlAAABtBYiaW5fY29uZmlnX2NoYW5uZWwAAAHDFihvdXRfY2hhbm5lbF9hX2NvbmZpZwAAAkAWKG91dF9jaGFubmVsX2NfY29uZmlnAAACbRYqaW5fdG91Y2hwb2ludF9jaGFubmVsAAACwhZrAAAC7xRhX2N1cnJlbmN5AAAC9QcUY19jdXJyZW5jeQAAAvkHKmluX3Byb2R1Y3RfY2hhbm5lbF9pZAAAAv0WImluX2dzbG9nc19jaGFubmVsAAADDBYAAvjZ+u22VB5NYWdlbnRvLUFtYXpvbjIEcm8KZW5fdXMEbWEGc3QxBGRlCmRlX2RlBnN0MgRhbQEAAAABACIAAAAAAAAAAQEAAAABACMAAAAAAAAAAQEAAAABACQAAAAAAAAAAQEAAAAMACYAAAAAAAAADAAmAAAAAAAAAA0AJgAAAAAAAAAOACYAAAAAAAAADwAmAAAAAAAAABAAJgAAAAAAAAARACYAAAAAAAAAEgAmAAAAAAAAABMAJgAAAAAAAAAUACYAAAAAAAAAFQAmAAAAAAAAABYAJgAAAAAAAAAXAQAAAAQAJwAAAAAAAAAEACcAAAAAAAAABQAnAAAAAAAAAAYAJwAAAAAAAAAHAQAAAAgAKAAAAAAAAAAIACgAAAAAAAAACQAoAAAAAAAAAAoAKAAAAAAAAAALACgAAAAAAAAADAAoAAAAAAAAAA0AKAAAAAAAAAAOACgAAAAAAAAADwEAAAAEACkAAAAAAAAABAApAAAAAAAAAAUAKQAAAAAAAAAGACkAAAAAAAAAB4L7++22VAZyb24GZXVyAQAAAAEAKwAAAAAAAAAAAQAAAAIALQAAAAAAAAAAAC0AAAAAAAAAAg==

**Comment by tglman** [comment]
Hi @tzsolti 

Do you have some stack trace or additional error log? i checked that debug information and everything was fine.

Regars

**Comment by tzsolti** [comment]
Hi. No this is all I had in the logs.

**Comment by tglman** [comment]
Ok, if there are no other stack trace, should be all right, this log in 2.1.x is printed also in case of some managed exception like OConcurrentModificationException, the wrong printing is already solved in the last develop version.

I think we can close this issue.

**Comment by tzsolti** [comment]
Thanks for checking. I'm closing it.
