### ISSUE TITLE
how to use schemas unique to an instance?

### ISSUE THREAD

**Issue by fommil** [orientechnologies/orientdb#5490]
in my [dev branch of ENSIME](https://github.com/fommil/ensime-server/tree/graphpocalypse), I've swapped our backend from H2 to OrientDB and I think I have feature parity. However, when I run my integration tests (`sbt it:test`) I get a bunch of errors that look like this:

```
Caused by: com.orientechnologies.orient.core.exception.OSchemaException: Class FqnSymbol already exists in current database
    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:980) ~[orientdb-core-2.1.5.jar:2.1.5]
    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:415) ~[orientdb-core-2.1.5.jar:2.1.5]
    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:400) ~[orientdb-core-2.1.5.jar:2.1.5]
    at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:100) ~[orientdb-core-2.1.5.jar:2.1.5]
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$4.call(OrientBaseGraph.java:1299) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$4.call(OrientBaseGraph.java:1296) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1744) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1296) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1279) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1264) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
```

As part of the tests, I'm creating the same empty database over and over again, in independent directories, all using the same schema. It looks like there is no isolation of schemas in OrientDB, this is a big problem for our testing, how can I enforce a separate schema object for each database that I create?

**Comment by fommil** [comment]
documentation of `OSchemaShared` is "Shared schema class. It's shared by all the database instances that point to the same storage."

This is ambiguous, does this mean the same storage type, or the same storage type AND storage location. I would assume the intention was the latter, as without this support it is basically impossible to have more than one OrientDB in the same JVM.

**Comment by laa** [comment]
@luigidellaquila that is @tglman area, I bet he knows answer.

**Comment by fommil** [comment]
This problem seems to have gone away after I isolated my integration tests to run in independent JVMs. Also, there might have been some stale compiled jars so I did a great rebuild. It would be good to know if you have stress tests around this.

**Comment by tglman** [comment]
Hi @fommil, 

I think this can be a multi threading issue, orientdb require that each thread is binded to a single database at once, and as well each database "ODatabaseDocument" or "OrientGraph" instance should be used only by one thread.

from the error and the context it seems that some instance are associate to a thread that is using another database. 
Can be that the case ?

**Comment by fommil** [comment]
@tglman that's sounds like a pretty extreme limitation. Can you please point me at the documentation for the threading assumptions?

Would it be fair to say that OrientDB can be accessed from multiple threads, but those threads must never be used to access another OrientDB instance? I might be able to workaround that.

**Comment by fommil** [comment]
btw, what are you using for the automated tagging? I also have need of automating some github workflow and I encouraged some people to start https://github.com/Astrac/consierge as a way to do it (but its very alpha)

**Comment by tglman** [comment]
hi @fommil,

You can read more about multithreading here : http://orientdb.com/docs/last/Java-Multi-Threading.html

OrientDB can definetly used in MT, just need to create different instances of the ODatabase* or OrientGraph with the same paremeters.

**Comment by fommil** [comment]
right, I get it... thanks! `ODatabaseDocument` is a thread local. That's kinda sucky. Rule of thumb is to only access OrientDB from a dedicated thread pool and to never use that pool across instances.

**Comment by fommil** [comment]
I think this answers by report, it is a feature not a bug :smile:

**Comment by laa** [comment]
Hi Sam ,
Why do you think thread local nature of database instance is bad ?
It is designed to be used together with pool al light weight object and
don't add overhead .

On Mon, Dec 21, 2015, 15:44 Sam Halliday <notifications@github.com> wrote:

> right, I get it... thanks! ODatabaseDocument is a thread local. That's
> kinda sucky. Rule of thumb is to only access OrientDB from a dedicated
> thread pool and to never use that pool across instances.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5490#issuecomment-166308639>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by fommil** [comment]
@laa it's bad because it means that a dedicated thread pool must be assigned in the layer accessing the database, per database, to avoid cross-instance contamination. This goes against the Reactive Manifesto which attempts to minimise the number of threads created by applications (when every subsystem needs 10 threads, it really adds up and starts to severely affect performance).

It's not a big deal for my current use case, because I was going to have a dedicated pool anyway to retrofit our DB layer (which had its own pool), and ENSIME is a relatively small server.

However, it does complicate my testing.

**Comment by laa** [comment]
Hi Sam ,
You should not use dedicated thread pool per database , you may use
connection pool and all issues with database reconnection will be solved
even if you have several storages. You will have many to many mapping in
such case and no performance bottlenecks .

On Mon, Dec 21, 2015, 16:10 Sam Halliday <notifications@github.com> wrote:

> @laa <https://github.com/laa> it's bad because it means that a dedicated
> thread pool must be assigned in the layer accessing the database, per
> database, to avoid cross-instance contamination. This goes against the
> Reactive Manifesto which attempts to minimise the number of threads created
> by applications (when every subsystem needs 10 threads, it really adds up
> and starts to severely affect performance).
>
> It's not a big deal for my current use case, because I was going to have a
> dedicated pool anyway to retrofit our DB layer (which had its own pool),
> and ENSIME is a relatively small server.
>
> However, it does complicate my testing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5490#issuecomment-166313179>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by fommil** [comment]
@laa well I dispute your performance claims, as this is clearly not scalable for many databases (in my experience once there are 100+ threads in a JVM it tends to dramatically impact performance, so every subsystem that requires a dedicated pool is causing a problem), but it happens to work well for my current use case because I have less than 20 :smile:. Ideally there should be a general "IO" pool of threads that can be shared across subsystems and a general "CPU" pool also shared.

**Comment by laa** [comment]
Hi Sam ,
We do not need 100+  threads if we have 100+ URLs  or connections and we
use connection pool . That is what I am trying to write . Did you read
Javadoc of OPartitionedConnecrionPool ?

On Mon, Dec 21, 2015, 16:48 Sam Halliday <notifications@github.com> wrote:

> @laa <https://github.com/laa> well I dispute your performance claims, as
> this is clearly not scalable for many databases (in my experience once
> there are 100+ threads in a JVM it tends to dramatically impact
> performance, so every subsystem that requires a dedicated pool is causing a
> problem), but it happens to work well for my current use case because I
> have less than 20 [image: :smile:]. Ideally there should be a general
> "IO" pool of threads that can be shared across subsystems and a general
> "CPU" pool also shared.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5490#issuecomment-166322123>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by fommil** [comment]
@laa that's not what I mean. I mean 100+ threads in the entire system and any subcomponent (e.g. OrientDB) which needs dedicated thread pools is not good for the overall health of the system. These requirements all add up, hence, not scalable.

**Comment by laa** [comment]
Hi Sam ,
But why we need separated thread pool for OrientDB connection. I can not
get it.
Use the same thread pool as your app container for example . Many users use
such approach .

On Mon, Dec 21, 2015, 17:06 Sam Halliday <notifications@github.com> wrote:

> @laa <https://github.com/laa> that's not what I mean. I mean 100+ threads
> in the entire system and any subcomponent (e.g. OrientDB) which needs
> dedicated thread pools is not good for the overall health of the system.
> These requirements all add up, hence, not scalable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5490#issuecomment-166325449>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by fommil** [comment]
because i have multiple orientdb instances and that is not allowed.

**Comment by laa** [comment]
It is allowed.
Many our users do that without problems .
Seems we have some misunderstanding there .
You can not use 2 the same active/open database instances between 2 threads
. But you do not need separete thread pool . Use connection pool not thread
pool and it will solve all issues automatically .

On Mon, Dec 21, 2015, 17:36 Sam Halliday <notifications@github.com> wrote:

> because i have multiple orientdb instances and that is not allowed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5490#issuecomment-166332483>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by fommil** [comment]
that's exactly what I was doing and I got the errors above. It's also not what is written in your docs. There it is quite clear that the same thread cannot be used across multiple orientdb instances, because orientdb is putting thread locals into that thread, which are specific to the instance that first generates the local. Hence, a thread pool is required, per orientdb instance, to avoid contamination. And I've seen that contamination in my tests where we spawn up a database per test, so hundreds of databases.

**Comment by laa** [comment]
I see , so that bug , you definitely should not work with separated thread
pool .
Could you provide test case we will fix it, so next hot fix will not
contain given issue .

On Mon, Dec 21, 2015, 17:43 Sam Halliday <notifications@github.com> wrote:

> that's exactly what I was doing and I got the errors above. It's also not
> what is written in your docs. There it is quite clear that the same thread
> cannot be used across multiple orientdb instances, because orientdb is
> putting thread locals into that thread, which are specific to the instance
> that first generates the local. Hence, a thread pool is required, per
> orientdb instance, to avoid contamination. And I've seen that contamination
> in my tests where we spawn up a database per test, so hundreds of databases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5490#issuecomment-166333921>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by fommil** [comment]
@laa I can describe a test scenario for you, but it's been a long time since I've written Java code so it would be tricky for me to provide a unit test (my dev environment is all setup for Scala).

Create ~100 databases all backed by independent `plocal` in `/tmp` and put the same schema in each one (e.g. a class with an index). Eventually some schema class creation will fail with an exception.

Good to hear this is a bug and not a feature! :smile:

**Comment by tglman** [comment]
Hi @fommil,

Is this still an issue on your environment, can we close this ?

**Comment by fommil** [comment]
let's leave open for a little bit. I was working on other things but will be looking at this over the coming months as we got a Google Summer of Code to work on this.

**Comment by fommil** [comment]
have you applied any commits that might address this?

**Comment by tglman** [comment]
hi @fommil,

I think we have no issue to address, when you use orientdb each instance of ODatabaseDocument or OrientGraph it has to be used by only one thread and as well you cannot use many instance active on the same thread together.

If you have to do some operation cross database, or in general you have more database used by the same thread, you can do like this:
```
OrientGraphFactory factory = ... // the factory can stay in the application context and is thread safe.

//each operation:
OrientVertex ver;
try(OrientGraph graph: factory.getTx()){
     // do here the operation on the database.
     ver = graph.addVertex();
     graph.commit();
     ver.detach(); // This is needed only if you want use the vertex instance outside of this try block.
} 
 
```

in this way you should not have any concurrency problems.

bye

**Comment by tglman** [comment]
Hi, 

With an answer since long time, closing.

Regards
