### ISSUE TITLE
please improve documentation for schema

### ISSUE THREAD

**Issue by fommil** [orientechnologies/orientdb#5494]
This documents three modes for the schema http://orientdb.com/docs/2.1/Schema.html but doesn't say how to specify which mode to use.

**Comment by fommil** [comment]
answer `classSchema.setStrictMode(true)`

**Comment by fommil** [comment]
it's also quite difficult to work out how to add a schema entry for a link. For example in 

```
orderItem.createProperty("animal", OType.LINK, animal);
```

`animal` has not been defined anywhere.

**Comment by fommil** [comment]
I found https://groups.google.com/forum/#!topic/orient-database/Y0QJiXk7d1I to be very useful

**Comment by smolinari** [comment]
I am not at all knowledgeable about the ODB Java API, but the docs page you referenced is a "get your feet wet" to ODB's capabilities in the "Getting Started" part of ODB's docs. It definitely is not a complete reference. 

Here is the section of the docs, which goes into more details about the Java API and setting properties.

http://orientdb.com/docs/last/Java-Schema-Api.html#property

If it still isn't complete to your liking and if you want, you can contribute to improve the docs, by forking the docs here:

https://github.com/orientechnologies/orientdb-docs

and creating PRs with the improvements you'd like to see. You can also use Gitbook to preview any changes you make too. 

Scott

**Comment by fommil** [comment]
@smolinari thanks. As far as I can tell, these two chapters on Schema are identical.

**Comment by smolinari** [comment]
Ha! You are absolutely right. Hmm... then my post is totally useless, other than me looking a bit foolish. :blush: 

The Schema page under the "Getting Started" should be a lot less full of details. That, or the API page needs to be a lot more detailed. And, since you brought up the need for more detail, I'd say it is the latter?

Scott
