### ISSUE TITLE
Server process gets killed abruptly upon connecting

### ISSUE THREAD

**Issue by chandra-n** [orientechnologies/orientdb#5497]
Hey Guys,
                 Using OrientDB Server v2.1.2. This problem started to occur after a big document and associated properties creation script brought the server down a couple of times. Post these shutdowns, whenever I start the server process now, the server starts fine but as soon as I connect to the database from the console or studio, it shuts down as if a kill command was issued. Console debug of the server process attached. [server console debug.txt](https://github.com/orientechnologies/orientdb/files/68411/server.console.debug.txt)

I can see that the server tries to re-build the indexes of the database as soon as the connection is made and soon dies in this process. [orient-server.log.0.txt](https://github.com/orientechnologies/orientdb/files/68412/orient-server.log.0.txt)
Not sure what is going on. I have attached the server console log and the log.0 file from the /logs directory. Can you please help me?

Here is the script that brought the server down a couple of times in the first place. I tried executing this over
[script.txt](https://github.com/orientechnologies/orientdb/files/68419/script.txt)

 studio.

thanks
Chandra

**Comment by tglman** [comment]
Hi @chandra-n,

any chance to share the database ? 

Thank you

**Comment by chandra-n** [comment]
@tglman , any recommended way you have in mind to share the db? It is pretty large BTW.

**Comment by chandra-n** [comment]
@tglman , I was able to eventually bring the database up after repeated attempts. It was just one of those lucky instances when the re-indexing completed before hitting the termination sequence. I suspect that this could be OOM related, although I am clueless if the index re-building routine ended up eating up the memory or not. The DB seems to be working fine now, although I am frankly scared of running the script again. Here are my 2 cents, let me know what you think:

1. Executing a long running function (using JavaScript or not) can cause the server to run out of memory? If not, would you be able to quickly glance through my script and point out any glaring deficiencies?

2. After an ungraceful shutdown, to recover the database, significant amount of re-indexing happens that also tends to consume lot of memory often leading to OOM. 

thanks

**Comment by tglman** [comment]
hi @chandra-n,

Can we close this ?

bye

**Comment by chandra-n** [comment]
Yes, please do.

thanks
Chandra

**Comment by luigidellaquila** [comment]
Thank you very much, closing

Luigi
