### ISSUE TITLE
Version upgrade workflow

### ISSUE THREAD

**Issue by cory-p-oncota** [orientechnologies/orientdb#5499]
This lies somewhere in between an inquiry and an enhancement request, however, I couldn't find a similar conversation so I would like to start one.

What are other OrientDB production users' methods for upgrading between versions? Currently, I have the following deployment strategy.

1) The folder containing the data files is a secondary mount and, as such, static. My configuration always points here instead of the default directory.

2) I have a folder holding all configuration files. When upgrading, I remove the config directory and replace it with a symlink to this locked down directory.

3) This is the part I don't like. I end up downloading the build and then, due to URL redirects in the download, I have to push it up to the remote server via FTP. Is there a better method which doesn't require manually compiling?

And that would be my feature request. An automated workflow, preferably stored in the bin directory, which manages the downloading and replacement of your existing version with latest or a specified version, as well as a way to roll back.

Thoughts?

**Comment by smolinari** [comment]
I can't help you completely with your wish, but here is a bash script, which will install ODB automatically.

```
#!/usr/bin/env bash

echo "------------ INSTALL ORIENTDB START -----------"


### install orientdb

export ORIENT_VERSION="2.1.8"

export INSTALL_DIR="/home/vagrant"
export VAGRANT_DIR="/vagrant"
export BOOTSTRAP_DIR="/var/www/puphpet/files/exec-once"

# Download orient
wget -O $INSTALL_DIR/orientdb-community-$ORIENT_VERSION.tar.gz wget http://www.orientechnologies.com/download.php?file=orientdb-community-$ORIENT_VERSION.tar.gz
tar -xzf $INSTALL_DIR/orientdb-community-$ORIENT_VERSION.tar.gz -C $INSTALL_DIR/

### fix to make sure the orient install is also owned by root
chown -R root:root $INSTALL_DIR/orientdb-community-$ORIENT_VERSION

### update server.sh with correct user and path
sed -i '/ORIENTDB_DIR="YOUR_ORIENTDB_INSTALLATION_PATH"/ c\ORIENTDB_DIR="'$INSTALL_DIR'/orientdb-community-'$ORIENT_VERSION'"' $INSTALL_DIR/orientdb-community-$ORIENT_VERSION/bin/orientdb.sh
sed -i '/ORIENTDB_USER="USER_YOU_WANT_ORIENTDB_RUN_WITH"/ c\ORIENTDB_USER="root"' $INSTALL_DIR/orientdb-community-$ORIENT_VERSION/bin/orientdb.sh



### initial start of Orientdb to prime user data
sudo nohup $INSTALL_DIR/orientdb-community-$ORIENT_VERSION/bin/orientdb.sh start

sleep 15

### stop orientdb
sudo nohup $INSTALL_DIR/orientdb-community-$ORIENT_VERSION/bin/orientdb.sh stop

sleep 15

### set up the orientdb password for root
sed -i 's/password=".*" name="root"/password="root"  name="root"/' $INSTALL_DIR/orientdb-community-$ORIENT_VERSION/config/orientdb-server-config.xml

### restart of Orientdb
sudo nohup $INSTALL_DIR/orientdb-community-$ORIENT_VERSION/bin/orientdb.sh start

echo "------------ INSTALL ORIENTDB END ------------"

This doesn't set up ODB as a service though. This script is used in our development vagrant box. I wouldn't consider it the total answer to your suggestion. But, it should lead you to a solution on the server side for sure.

Scott
```

**Comment by cory-p-oncota** [comment]
Very helpful! The download was the biggest blocker for me. I have some of the service implementation automated already so I'll run through this and share by final workflow.
