### ISSUE TITLE
OCommandExecutorNotFoundException after upgrading to 2.1.8

### ISSUE THREAD

**Issue by cpoyraz** [orientechnologies/orientdb#5502]
My code was working properly before upgrading.. But I upgraded the server to 2.1.8 yesterday and my c# code gives that error..  What may cause of that?
![orientdb bug](https://cloud.githubusercontent.com/assets/467161/11954120/853ee504-a8ae-11e5-8033-b79e72a88873.png)

**Comment by maggiolo00** [comment]
hi @cpoyraz 

are you executing a batch script?

**Comment by cpoyraz** [comment]
No it is just a query that contains complex subqueries..  But I changed it with a simple one like "select from Creatures".. It gives the same error too.

**Comment by maggiolo00** [comment]
hi @cpoyraz 

how can i reproduce it?

**Comment by lvca** [comment]
No answer since a while, closing it for now. In case please reopen/comment it.
