### ISSUE TITLE
Change disk cache in the way which will allow to create non durable temporary data structures

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5504]
Current database architecture is oriented only on durable data structures, but we need family of data structures which will use disk cache capabilities but without durability support. 
Literally it means that: 
1. Disk cache have to be changed to support pages without valid LSN
2. Ability to add and remove temporary files on next restart or after TTL is passed should be added.

Following data structures should be added:
1. LinkedList
2. BTree
3. Linear Hash Map

**Comment by lvca** [comment]
:+1

**Comment by laa** [comment]
Moved to 3.1 sorry to much work for 3.0 ((

**Comment by laa** [comment]
duplication
