### ISSUE TITLE
Transactions don't work

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb#5506]
Hi there. I've just downloaded the latest version of OrientDB (2.1.8) and decided to test the transactions:

```
orientdb {db=testdb}> create class Person

Class created successfully. Total classes in database now: 11

orientdb {db=testdb}> create property Person.name STRING

Property created successfully with id=1

orientdb {db=testdb}> begin

Transaction 3 is running
orientdb {db=testdb tx=[0 entries]}> insert into Person (name) values ('John Doe')

Inserted record 'Person#18:0{name:John Doe} v1' in 0,006000 sec(s).

orientdb {db=testdb tx=[0 entries]}> rollback 

Transaction 3 has been rollbacked in 0ms
orientdb {db=testdb}> select from Person

----+-----+------+--------
#   |@RID |@CLASS|name    
----+-----+------+--------
0   |#18:0|Person|John Doe
----+-----+------+--------

1 item(s) found. Query executed in 0.002 sec(s).
orientdb {db=testdb}>
```

As you can see the changes I made (insert a record to the Person class) weren't rollbacked. The same case is true for the distributed mode. I can run a transaction on one node, add/delete some data and then call the rollback. As a result, rollback simply doesn't work. Even worse, in the distributed (as in the standalone) mode I can see the temporary data which doesn't get committed. Here's the detailed test case:

* from client 1 connected to the first node:
```
MacBook-Pro-Miron:bin mironaseev$ ./console.sh 

OrientDB console v.2.1.8 (build 2.1.x@r; 2015-12-17 11:51:38+0100) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> create database remote:localhost:2424/b4n-ctl root root plocal 

Creating database [remote:localhost:2424/b4n-ctl] using the storage type [plocal]...
Connecting to database [remote:localhost:2424/b4n-ctl] with user 'admin'...OK

DISTRIBUTED CONFIGURATION:
{
  "localName": "_hzInstance_1_orientdb",
  "localId": "3ffb890f-e57b-4efb-93e5-bd30de4fc908",
  "members": [
    {
      "id": "3ffb890f-e57b-4efb-93e5-bd30de4fc908",
      "name": "node1450857723470",
      "startedOn": "2015-12-23 14:33:54",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"192.168.88.44:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"192.168.88.44:2480"}],
      "databases": []
    }
  ]
}
Database created successfully.

Current database is: remote:localhost:2424/b4n-ctl
orientdb {db=b4n-ctl}> create class Person 

Class created successfully. Total classes in database now: 11

orientdb {db=b4n-ctl}> create property Person.name STRING

Property created successfully with id=1

orientdb {db=b4n-ctl}> begin

Transaction 1 is running
orientdb {db=b4n-ctl tx=[0 entries]}> insert into Person (name) values ('John Doe')

Inserted record 'Person#18:0{name:John Doe} v1' in 0,022000 sec(s).

orientdb {db=b4n-ctl tx=[0 entries]}> 
```
* from client 2 connected to the second node:
```
MacBook-Pro-Miron:bin mironaseev$ ./console.sh 

OrientDB console v.2.1.8 (build 2.1.x@r; 2015-12-17 11:51:38+0100) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> connect remote:localhost:2425/b4n-ctl root root 

Connecting to database [remote:localhost:2425/b4n-ctl] with user 'root'...OK

DISTRIBUTED CONFIGURATION:
{
  "localName": "_hzInstance_1_orientdb",
  "localId": "8e170a7a-71b4-4606-8b6c-37c81dfc232b",
  "members": [
    {
      "id": "8e170a7a-71b4-4606-8b6c-37c81dfc232b",
      "name": "node1450857870547",
      "startedOn": "2015-12-23 14:34:33",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"192.168.88.44:2425"},{"protocol":"ONetworkProtocolHttpDb","listen":"192.168.88.44:2481"}],
      "databases": []
    },
    {
      "id": "3ffb890f-e57b-4efb-93e5-bd30de4fc908",
      "name": "node1450857723470",
      "startedOn": "2015-12-23 14:33:54",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"192.168.88.44:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"192.168.88.44:2480"}],
      "databases": []
    }
  ]
}
orientdb {db=b4n-ctl}> select from Person 

----+-----+------+--------
#   |@RID |@CLASS|name    
----+-----+------+--------
0   |#18:0|Person|John Doe
----+-----+------+--------

1 item(s) found. Query executed in 0.012 sec(s).
orientdb {db=b4n-ctl}> 
```

Here are the steps I performed:
* Started the first node in the distributed mode (./dserver.sh)
* Connected to this node
* Created a database
* Started the second node in the distributed mode (./dserver.sh)
* Connected to the previously created database through the second node
* Created a class and a property for this class by using the first database connection (which is connected to the first node)
* Opened a transaction, performed a single insert by using the first database connection. Notice, no commit was performed
* Performed a select from the second database connection

**Comment by lvca** [comment]
When you use remote connection, the transaction isolation is broken. Take a look at:

http://orientdb.com/docs/2.1/Transactions.html#breaking-of-acid-properties-when-using-remote-protocol-and-commands-sql-gremlin-js-etc

What's your programming language? If it's Java, you could use plocal, otherwise it's better to use SQL Script to have TX isolation

**Comment by maseev** [comment]
Hold on a sec. I don't get it. I do have to use remote mode because I'm trying to connect to the remote OrientDB instance, right? Using the plocal memory storage is not my case, because my JVM application could reside on the remote server and establishes the remote connection.

**Comment by maseev** [comment]
So, how am I supposed to create an OrientDb cluster, connect to it by using some Java code and use transactions as well if transactions for some reasons don't work? That link you posted doesn't make a lot of sense to me, actually. It says:

```
Transactions are client-side only until the commit. This means that if you're using the "remote" protocol the server can't see local changes.
```

So, yes I do use remote connection to the database and yes I should have seen my changes only after the commit, but it doesn't work that way.

That's definitely an interesting part:
```
No Transaction

Default mode. Each operation is executed instantly.

Calls to begin(), commit() and rollback() have no effect.
```

Is there a way I can change this behavior with the terminal commands or something?

**Comment by maseev** [comment]
Just tried the same scenario from the Java code - works perfectly. It seems that transaction isolation is broken only if I connect to the database through the console.sh tool because by default transaction type is no transaction in contrary to Java API where optimistic transactions are used.
