### ISSUE TITLE
Incredibly slow ETL on remote orientdb server

### ISSUE THREAD

**Issue by cong-trinh** [orientechnologies/orientdb#5508]
The speed on the OrientDB server is incredibly slow for ETL.
We have a m3.lx out on AWS that is suppose  to be our OrientDB server but running the ETL against it through remote mode is incredibly slow. 
+ extracted 308 records (0 records/sec) - 308 records -> loaded 153 vertices (0 vertices/sec) Total time: 197545ms [0 warnings, 0 errors]

I turned up logging to FINE on the server and didnt see anything that stands out. Our ETL extract records and creates 7 node with 7 edge each max. Running it on plocal it jumps to ~800 vertices/sec. Having such a slow ETL and performance on a remote OrientDB would rule out OrientDB for us as we are looking to store ~100s of records within the DB and will be looking to set up cluster mode behind a load balancer. I am assuming that I am just missing something critical with the setup but most of it is the default settings for version 2.1.8.

Any help would be appreciated.

Is the ETL package actively being worked on? Is it worth writing our own ETL process?

**Comment by robfrank** [comment]
To better support you, it would be better if you can send the ETL json config and a sample csv with some data, maybe generated or anonymized if necessary. ETL works very well for first batch import, when you can use plocal without WAL.

**Comment by robfrank** [comment]
closing due to lack of infos
