### ISSUE TITLE
New EXPAND operator to extract Master/Details info  [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#551]
This is [Issue 551](http://code.google.com/p/orient/issues/detail?id=551) moved from a Google Code project.
Added by 2011-09-30T11:53:44.000Z by [r.ventag...@gmail.com](http://code.google.com/u/116388565395359186910/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, v2.0.0

### Original description

    When we have two classes linked togheter in a &quot;master / detail&quot; relationship it would be useful to have a new operator to extract Mater/Details info.
    
    For example, having:
    
    > load record #6:1
    --------------------------------------------------
    ODocument - Class: LemmaStem   id: #6:1   v.2
    --------------------------------------------------
                    stem : mangi            
                   lemma : Lemma#5:1{normalForm:mangiare,lexSymbol:mangiare_v,lexCat:V,lexFeatures:[2]} v0
            flexSuffixes : [#7:1, #7:2]        
    
    
    > load record #7:1
    --------------------------------------------------
    ODocument - Class: FlexSuffix   id: #7:1   v.0
    --------------------------------------------------
                  suffix : a                   
              morphFeats : [INDIC, PRES, THIRD, SING]
    
    
    > load record #7:2
    --------------------------------------------------
    ODocument - Class: FlexSuffix   id: #7:2   v.1
    --------------------------------------------------
                  suffix : amo                 
              morphFeats : [INDIC, CONGIUNT, PRES, FIRST, PLU]
    
    
    we would like to get a result similar to a master/detail JOIN in a RDBMS:
    *stem*         *normalForm*          *suffix*         *flexForm*
    mangi           mangiare                a               mangia
    mangi           mangiare                amo             mangiamo
    
    
    The proposal is to have a new EXPAND operator to achieve this result.
    
    Something like:
    SELECT stem, lemma.normalForm AS normalForm, EXPAND( flexSuffixes.suffix ) AS suffix, stem.append(suffix) AS flexForm FROM LemmaStem

**Comment by luigidellaquila** [comment]
implemented UNWIND operator, see http://orientdb.com/docs/last/SQL-Query.html#unwind
