### ISSUE TITLE
suggestion: Not to throw when no edges created.

### ISSUE THREAD

**Issue by gongdo** [orientechnologies/orientdb#5510]
Currently, `CREATE EDGE` throws an exception when `FROM` statement or `TO` statement were not found.

https://github.com/orientechnologies/orientdb/blob/ad7cbed6c7c5b3f920713d93bc8c98b219c200c8/graphdb/src/main/java/com/orientechnologies/orient/graph/sql/OCommandExecutorSQLCreateEdge.java#L213-L219

``` java
        if (edges.isEmpty()) {
          if (fromIds.isEmpty())
            throw new OCommandExecutionException("No edge has been created because no source vertices");
          else if (toIds.isEmpty())
            throw new OCommandExecutionException("No edge has been created because no target vertices");
          throw new OCommandExecutionException("No edge has been created between " + fromIds + " and " + toIds);
        }
```

Imagine you want to create possibly multiple edges from a RID to a sub-query.
The result of sub-query could be empty, it's not deterministic.
If you want to make sure that the edges will be created, than you should select-and-create in a transaction.
Why don't you let it go and just return a number of edges that actually created.
I think it's not only easier to handle it, but also give better performance.

**Comment by maggiolo00** [comment]
+1

**Comment by lvca** [comment]
Sometimes you need an exception if you expect that at least one edge has been created. This makes much easier to handle this case, so probably we should support both with an additional keyword

**Comment by gongdo** [comment]
@lvca, actually I consider creating a edge as updating about two vertices. So I feel like it's okay if no relationships were 'updated' unless I can count how many.
However, it's just how I feel about edges. Both(throw or swallow) cases are quite reasonable, the additional keyword would be great.

**Comment by luigidellaquila** [comment]
Hi guys, 

The general case is that you can create a set of edges from a set of vertices to another set of vertices.

By definition, sets can be empty, so it makes sense to just create no edges.

-1 to the idea of adding another keyword, the language is already too cluttered by keywords to manage corner cases, the statement will just return the number of edges that were created.

**Comment by ahlbejes** [comment]
+1
It is really the behavior I expected. It is a hassle to have to be sure both source and destination sets are not empty before executing the create edge command, or to have to handle the exception messages.
