### ISSUE TITLE
Lucene Spatial Module link is not working.

### ISSUE THREAD

**Issue by sushimb** [orientechnologies/orientdb#5512]
Lucene Spatial Module link is not working... 

http://central.maven.org/maven2/com/orientechnologies/orientdb-spatial/VERSION/orientdb-spatial-VERSION-dist.jar

http://orientdb.com/docs/last/Spatial-Module.html

Is there any alternate link to download the jar file of Spatial Module of OrientDB?

**Comment by robfrank** [comment]
VERSION is a placeholder, please fill it with the right value, maybe 2.2.0-beta? If you are using 2.1.x, spatial module is included.

**Comment by robfrank** [comment]
This is more a question than an issue. Please post it on StackOverflow http://stackoverflow.com/questions/tagged/orientdb
