### ISSUE TITLE
OrientDB JDBC driver with Apache Drill

### ISSUE THREAD

**Issue by objectsberg** [orientechnologies/orientdb#5514]
I'm trying to write a query that joins orientdb class with sql server table using Apache Drill.
Within the drill UI I've created a new JDBC storage mapped to OrientDb using the following config.:
{
  "type": "jdbc",
  "driver": "com.orientechnologies.orient.jdbc.OrientJdbcDriver",
  "url": "jdbc:orient:remote:127.0.0.1/GratefulDeadConcerts",
  "username": "root",
  "password": "admin",
  "enabled": true
}

it succeeded to create a connection but I couldn't select any class! it always says not found. 
while trying to solve it I've reached the MapR Drill ODBC Driver which has a utility called Drill Explorer browsing the orientDB connection return no database classes?

does anyone have faced this before, any suggestions?
Thanks

**Comment by robfrank** [comment]
Hi, the default user for GratefulDeadConcerts is admin/admin. May you try with this credentials?

**Comment by objectsberg** [comment]
Hi Roberto, Thank you for the suggestion, I've already tried that combination and it didn't work, that `s why I switched to the root account to eliminate any security hold-backs.

**Comment by objectsberg** [comment]
Should i consider it as not doable?

**Comment by robfrank** [comment]
@objectsberg  you define the connection to orient with root/admin, my suggestion is to use admin/admin. 
Moreover: is the orientDb server up and running? 

Can you connect via console or studio? 
Is the orientdb-jdbc jar in the the Drill classpath? 
Can you connect to the db via jdbc (you can tests with a bounch of java code lines)? 

But, please, modify your credentials to admin/admin instead of root/admin.

Last but not least: which version of orient server and jdbc driver are you using?

**Comment by objectsberg** [comment]
it seems like a [Drill bug](https://issues.apache.org/jira/browse/DRILL-3970)
its related to the null value at the getMetaData().getTables(...)...TABLE_SCHEM

TABLE_CAT, TABLE_SCHEM, TABLE_NAME, TABLE_TYPE, REMARKS
null, >>null<<, ORole, TABLE, null
   null, >>null<<, OSchedule, TABLE, null
   null, >>null<<, OIdentity, TABLE, null
   null, >>null<<, ORIDs, TABLE, null
   null, >>null<<, OFunction, TABLE, null

can I set a broad static schema name like dbo for instance?
cheers,

**Comment by robfrank** [comment]
Ok, I see the code. We set null for TABLE_SCHEM and TABLE_CAT. I'll investigate more to see if there are better values to use.

**Comment by robfrank** [comment]
I added values for TABLE_SCHEM and TABLE_CAT, as for other methods we use tbalename to fill this fields. I pushed on 2.1.x branch and develop, so it will be available on 2.1.10 and next 2.2.x release

**Comment by objectsberg** [comment]
Thanks Robert,

**Comment by robfrank** [comment]
Let me know if it works, and if other fix are needed.
