### ISSUE TITLE
Integration of Lucene Advance Search into Orientdb

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5515]
What are the steps and guideline you can provide to me if i wana contribute to integrate the following Lucene features:

SimilarityQueries and MoreLikeThis
1. https://lucene.apache.org/core/3_0_3/api/contrib-queries/org/apache/lucene/search/similar/MoreLikeThis.html
2. https://lucene.apache.org/core/2_9_4/api/contrib-queries/org/apache/lucene/search/similar/SimilarityQueries.html

**Comment by robfrank** [comment]
MoreLikeThis and Similarity are part of 3.0.x development plan
