### ISSUE TITLE
How can I use Chinese as name of class, field of vertex ?

### ISSUE THREAD

**Issue by gougousdu** [orientechnologies/orientdb#5516]
I am new to OrientDB. Now I want to create a db from an owl file. But I found that OrientDB does not support Chinese well. For example, firstly I added a class named "电影" (movie); then I query as follows,

select * from 电影

it will stop by lexical error. Seems the parser does not support Chinese letter. 
Then I add the unicode of Chinese into OrientSql.jjt as letters and re-jjtree the file to get a new parser, but this does not work. 

Will you please give me some suggestions ? Thanks and have a nice day.

**Comment by StarpTech** [comment]
Look at http://stackoverflow.com/questions/11911748/non-english-tokens-in-javacc In my opinion you shouldn't wait until this is updated. Use english names.

**Comment by luigidellaquila** [comment]
Hi @gougousdu 

Class names allow have to be valid identifiers (A-Z, a-z, 0-9, _) or they have to be quoted with back-ticks.
You can try the following, it should work:
```
select * from `电影`
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @gougousdu 

I tested it locally and it seems to work fine. I'm closing it, please reopen if you need further help

Thanks

Luigi
