### ISSUE TITLE
Error on database import (2.1.8)

### ISSUE THREAD

**Issue by christopherhex** [orientechnologies/orientdb#5517]
We are using OrientDB using Docker containers in two different environments (development & production). The docker build process also loads the database schema. 
We want to push an updated database schema (added one class of edges) to the production environment, while preserving the data. To minimize downtime I first wanted to test this locally before changing the production server.

I did a database export on the running production instance `export database <file-url>', and wanted to import this again on a test instance (with updated schema) using `import database <file-url> -merge=true -preserveClusterIDs=false` , but this gives the following error and no records are imported:

```
Importing database schema...ERROR (20 entries): com.orientechnologies.orient.core.exception.OSchemaException: 'Internal' schema modification methods can be used only inside of embedded database
```

Any ideas on how to solve this issue? 
Thanks!

**Comment by tglman** [comment]
hi @sparkycrisse 

I did a quick check for see if the import was using some internal api wrongly, and it doesn't seam so, can you tell me which version are you using and if you are running the import from remote or plocal.

will be really cool if you can get also a full stack trace.

bye

**Comment by tglman** [comment]
hi @sparkycrisse,

Any news about this ? did you try to do the same import with a newer version ?

**Comment by tglman** [comment]
hi @sparkycrisse,

We did some refactor on the import in 2.2.5 this should not happen anymore, closing.
