### ISSUE TITLE
Audit logs incomprehensible

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5520]
OrientDb: 2.1.8

I enabled auditing on our production server. I don't understand some logs. Why are negative rids listed? What is a change of `{"@type":"d","@version":0}`? See picture for more information.

Auditing configuration:
```
* , Create: yes, Read: no, Update: yes (Track changes: yes), Delete: yes, Polymorphic: yes
```

**Comment by StarpTech** [comment]
![audit_log](https://cloud.githubusercontent.com/assets/1764424/12011359/62c82254-acca-11e5-9a10-27b75110699f.PNG)

**Comment by maggiolo00** [comment]
hi @StarpTech 

you did you create records?

About update should show the difference in updating.

Which are the update operations involved?

**Comment by StarpTech** [comment]
@maggiolo00 I don't know this is the production server.

**Comment by maggiolo00** [comment]
ok @StarpTech 
i will try to reproduce it.

**Comment by StarpTech** [comment]
@maggiolo00 Should store the profiler a date or timestamp then I could recognize the relevant command.

**Comment by StarpTech** [comment]
@maggiolo00 does exists any tests for auditing? I can't find any.

**Comment by maggiolo00** [comment]
hi @StarpTech 

there are tests on Auditing. You can't find it because the agent is closed source. 
So you will not find it.

**Comment by StarpTech** [comment]
@maggiolo00 Why is it closed?

**Comment by maggiolo00** [comment]
Because it is part of the Enterprise Edition and not Community Edition

**Comment by maggiolo00** [comment]
@StarpTech 

it is fixed. Will be available in 2.1.9 hotfix
Thanks
Enrico

**Comment by maggiolo00** [comment]
hi @StarpTech 

OrientDB 2.1.9 has been release with this issue fixed

Thanks

**Comment by maggiolo00** [comment]
hi @StarpTech 

did you try it with 2.1.9?

thanks
Enrico
