### ISSUE TITLE
asDecimal() doesn't returns decimal.

### ISSUE THREAD

**Issue by gongdo** [orientechnologies/orientdb#5526]
I don't think the version matters but, I'm currently using 2.1.8.

```sql
select eval('0.17 * 41')
select eval('0.17 * 41').asDecimal()
```
Both results were `6.970000000000001`.
Shouldn't it be `6.97`?

**Comment by lvca** [comment]
`asDecimal()` has been called too late, the loss of precision is already made. Try one of those:

- `select "0.17".asDecimal() * 41`
- `select eval("0.17").asDecimal() * 41`
- `select eval( 'eval("0.17").asDecimal() * 41 ')`

**Comment by gongdo** [comment]
@lvca First and second fire OCommandSQLParsingException. (at least with v2.1.18) Only the last one works. I can go with this for now. Thanks.

Nested eval looks awkward, nevertheless, isn't `eval('0.17 * 41').asDecimal()` simple and predictable?
I think `asDecimal()` should convert any number as decimal, regardless precision of the number.

**Comment by lvca** [comment]
In `eval('0.17 * 41').asDecimal()` is called after the eval.
