### ISSUE TITLE
.asDate() function returns datetime value as is

### ISSUE THREAD

**Issue by a-unite** [orientechnologies/orientdb#5529]
Here is the case:
```CREATE VERTEX V SET testDateTime = DATE("2015-11-21 22:33:44")```
```select testDateTime.asDate() from V```

returns value for _testDateTime.asDate()_ as `2015-11-21 22:33:44`, not something like `2015-11-21` (or `2015-11-21 00:00:00` (I'm always wonder, why don't we use ISO 8601 default date and datetime formats, by the way))

The same happens if we use explicit schema for _testDateTime_ property (`create property v.testDateTime date` before any tests).

**Comment by luigidellaquila** [comment]
Hi @a-unite 

`asDate()` method is intended to transform strings into dates. To format dates, please use `.format()` instead:

```
select testDateTime.format('yyyy-MM-dd') from V
```

For further information you can refer to this page http://orientdb.com/docs/2.1/Managing-Dates.html

Thanks

Luigi

**Comment by a-unite** [comment]
Luigi, thank you. I'm aware of _format('')_ function.

The only question is that we have `.asDate()` and `asDateTime()` functions and I believe people expect that they will act accordingly. 
Since they do the same thing, shouldn't we remove `.asDate()` function completely then?

Regards,
Ata

**Comment by luigidellaquila** [comment]
Hi @a-unite 

I think they will both stay for backward compatibility, but I got your point.

Thanks

Luigi

**Comment by a-unite** [comment]
Sure, backward compatibility is important.
I think we should explain that it is the same function on the documentation page, then.

Could please you close this issue, if you think it is ok.

**Comment by luigidellaquila** [comment]
Yes, absolutely, I'm updating the docs.

Thanks

Luigi
