### ISSUE TITLE
Simple Java connection causes Mac Space switching

### ISSUE THREAD

**Issue by kruthar** [orientechnologies/orientdb#5531]
I'm seeing some pretty bizarre behaviour, not positive that the root cause is in OrientDB, but this is the only place I have ever seen it happen so I am  posting it here.

I am using OSX Yosemite 10.10.5 and Intellij 15.0.2 in fullscreen mode.

I have a very simple Maven project in Intellij to test this out on. Here is the pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.kruth.orientdb</groupId>
    <artifactId>orientdb-testing</artifactId>
    <version>0.1-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-client</artifactId>
            <version>2.1.8</version>
        </dependency>
    </dependencies>
</project>
```

and a simple Java class:

```
package com.kruth.orientdb;

import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;

/**
 * Created by kruthar on 12/29/15.
 */
public class OrientDBTesting {
    public static void main(String args[]) {
        ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:test");
    }
}
```

When I run the main method from Intellij, it runs (seemingly correct), but switches my screen to whatever my first Space is at the time. If Intellij fullscreen is the first Space then it switches to the second Space. This only happens if Intellij is in fullscreen. This also happens if I have a terminal window open in fullscreen (with iTerm) and run it on the commandline.

This is the output of running the main method, nothing seems wrong:

```
Dec 29, 2015 12:08:31 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=10,695MB (heap=3,641MB os=16,384MB disk=60,647MB)
```

Any thoughts?

**Comment by maggiolo00** [comment]
hi @kruthar 

seems strange. 
AFAIK OrientDB does not have this power yet :D
What happen if you comment the connection  line?

**Comment by kruthar** [comment]
When I comment it out, or even put something else in there like a println or something, things work as expected. Meaning the code executes, no Space switching.

**Comment by maggiolo00** [comment]
@kruthar 
i've tried it on Yosemite and IntelliJ 14 without Space switching

**Comment by kruthar** [comment]
I tested on Intellij 14.0.4 Community and Ultimate editions and still see the switching. I also tested on Intellij 15.0.2 Community Edition, same thing.

I updated my pom so I could build a jar:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.kruth.orientdb</groupId>
    <artifactId>orientdb-testing</artifactId>
    <version>0.1-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-client</artifactId>
            <version>2.1.8</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

Then built and ran the test class on the commandline:

```
mvn clean package
java -cp target/orientdb-testing-0.1-SNAPSHOT.jar com.kruth.orientdb.OrientDBTesting
```

When I run this in iTerm fullscreen, I see the same Space switching. When not in fullscreen things work properly and the Space does not switch. So it would seem that Intellij doesn't have anything to do with it.

I actually just found another instance of similar Space switching. If you are on a fullscreen window, then <kbd>&#8984;</kbd> + <kbd>tab</kbd> to Finder, which is always open, then it takes you to your first Space. Could this be related?

I understand that this is going to be hard to diagnose if you can't reproduce so I'll keep trying some things, but let me know if anything else comes to mind.

**Comment by kruthar** [comment]
Although the source application is different, this post identifies the issue having to do with forked processes switching the Space when in fullscreen: http://apple.stackexchange.com/questions/100069/when-terminal-forks-process-current-app-loses-focus.

When I add the argument as suggested by the fix the Space does not switch:

```
java -Djava.awt.headless=true -cp target/orientdb-testing-0.1-SNAPSHOT.jar com.kruth.orientdb.OrientDBTesting
```

So, eureka, I guess. It is still strange because I have never had this issue working with anything else. Is there something happening in OrientDB that makes it different from using other applications?

**Comment by luigidellaquila** [comment]
Hi @kruthar 

OrientDB is a quite complex piece of software, so it's hard to say what part of it can cause this behavior. We will find some time to investigate it, but it's definitely low priority, so no promise about the timing.

I'm closing this issue in the meantime, as it seems to be related to how OSX manages processes and there is a work-around

Thanks

Luigi
