### ISSUE TITLE
Inconsistent Result Behavior of SQL SELECT with Filter on EMBEDDEDLIST

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#5532]
There are three related issues, I will be posting.  This is the first, that started all of them.

I have a Class called "parent".  It has a single field called "subs" which is of type EMBEDDEDLIST and points to another class called "sub".  The "sub" class has two fields, "prop1" and "prop2".  A "parent" document would look something like this:

``` JSON
{
  "@type": "d",
  "@version": 0,
  "@class": "parent",
  "subs": [{
    "@type": "d",
    "@version": 0,
    "@class": "sub",
    "prop1": "A",
    "prop2": "X"
  },
  {
    "@type": "d",
    "@version": 0,
    "@class": "sub",
    "prop1": "B",
    "prop2": "X"
  }]
}
```

I then query the parent class to return just the "subs" field and use filters, that should return 0, 1, or 2 elements.  Here are the queries:

Query 1:  Matches no documents in subs.

``` SQL
SELECT subs[prop1 = '1'] FROM parent
```

Query 2:  Matches 1 documents in subs.

``` SQL
SELECT subs[prop1 = 'A'] FROM parent
```

Query 3:  Matches 2 documents in subs.

``` SQL
SELECT subs[prop2 = 'X'] FROM parent
```

All three queries will return a List containing a single ODocument with only the "subs" property populated.  However, the issue is that for Query 1 and Query 3 the "subs" field will be a HashSet, but for Query 2 the subs field will contain an ODocument.  Query 1 will result in an empty HashSet.  Query 2 will result in a HashSet with two elements.  In the case that the filter correspond to only 1 element.  The ODocument itself is returned.  I would have expected a consistent result type (e.g. a HashSet with 1 element).

In our actual use case, it is not known if the filter will match 0, 1, or multiple elements.  In all cases our method must return a collection.  The fact that the result is inconsistent leads to having to extract the element essentially as an Object, and then to "instance of".  In the case where the query returns an ODocument I need to the put it in a list to return.  This is very clunky.

Keep in mind that the type of the "subs" field is EMBEDDEDLIST.  I would expect the field to alway be a collection when queried, and not mysteriously changed into a single EMBEDDED document when the filter matches only one element.

Furthermore, I am not entirely sure why the result type is a HashSet.  If the "subs" field was an EMBEDDEDSET,  I could understand that.  But it is an EMBEDDEDLIST.  I would have expected it to come back as a subclass of java.util.List.

I have created a Gist that demonstrates the issue (and another):

https://gist.github.com/mmacfadden/54ab17d39743a2da8d22

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

It's an expected behavior that comes from an old implementation.

I really don't like it, so I'm open to discuss a change. I think we can think about it (together with other similar changes, to make the whole API more consistent) in 3.0, with a flag that enables the old behavior for backward compatibility. 

I'm flagging it as an enhancement in the meantime

Thanks

Luigi

**Comment by smolinari** [comment]
Hey Luigi,

How about a Github tag "API Consistency 3.0" and marking this and other suggestions, [like this one](https://github.com/orientechnologies/orientdb/issues/3820#issuecomment-151162243) with it?

Scott

**Comment by mmacfadden** [comment]
Great.  I have a work around for now.  So its ok for me to mark as a future enhancement.

**Comment by luigidellaquila** [comment]
Hi @smolinari 

why not, it seems a good idea, I'll discuss it with the team

Thanks

Luigi
