### ISSUE TITLE
ClassCastException from ODocument.field(String, OType) with EMBEDDEDLIST

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#5533]
There seems to be a small issue with the logic in the ODocument.field(String, OType) method.  This is related to issue #5532.  In that issue, one of the fields (named "subs") in a select query is sometimes coming back as a HashSet and some times as an ODocument.  We were trying to call document.field("subs", OType.EMBEDDEDLIST).  The "subs" field is defined as an EMBEDDEDLIST in the schema.

Note: All line numbers are relative to the develop branch.

In the ODocument.field(String, OType)  method, on or about line 891 the following line exists:

```Java
else if ((iFieldType == OType.EMBEDDEDLIST || iFieldType == OType.LINKLIST) && value instanceof Set)
        newValue = Collections.unmodifiableList((List<?>) ODocumentHelper.convertField(this, iFieldName, iFieldType, null, value));
```

The OType being passed in is indeed EMBEDDEDLIST.  So when the field was being returned as a HashSet, this evaluated to true and the set was converted to a list.  When the value returned was an ODocument instead, this check would evaluate to false.  Instead the branch on or about line 895 will be taken:

```Java
else
    newValue = OType.convert(value, iFieldType.getDefaultJavaType());
```

This calls the static OType.convert(final Object iValue, final Class<?> iTargetClass).  iValue will be an instance of ODocument.  iTargetClass will be List, the default java class for EMBEDDEDLIST.  The if logic in this method will bring us to OType line 415:

```Java
 else if (!(iValue instanceof Collection<?>) && Collection.class.isAssignableFrom(iTargetClass)) {
        final Set<Object> set = new HashSet<Object>();
        set.add(iValue);
        return set;

      }
```

Indeed iValue is not an instance of Collection and iTargetClass (List) isAssignableFrom Collection.  Essentially, this is saying, if iValue is not a collection, and the caller wants a collection do this.  Unfortunately, what is done is to put the single value in a HashSet and return it.

So the user has asked for an EMBEDDEDLIST, and would be expecting the result to be a subclass of java.util.List.  However they are going to wind up with a HashSet, which will likely cause a ClassCastException.  For example:

```Java
   List<Object> list3 = document.field("subs", OType.EMBEDDEDLIST);
```

It seems like the logic in the OType.convert method is to generic.  It essentially is saying if the caller asked for any type of collection, regardless of what it was, give them a HashSet.  However, there is no guarantee that what they asked for was a set.  It seems that since OrientDB supports EMBEDDED/LINKED Sets, Lists, and Maps, then this conversion should be sensitive to these three types, and not just assume any request for a collection can be handled with a Set.

The following Gist demonstrates the issue:

https://gist.github.com/mmacfadden/54ab17d39743a2da8d22

**Comment by tglman** [comment]
Hi @mmacfadden,

That problem is due to te fact that the orient sql if find  a list with an only element return it without the list around, you can work around that changing your query to "SELECT list(subs[prop1 = 'A']) as subs FROM parent" in thsi way you don't even need to specify the type on `document.field`

**Comment by mmacfadden** [comment]
Hi @tglman,

Thanks for the workaround.  That will solve my immediate problem.  

However, I think that there is still a bug here.  Taking my issue out of the picture, you are still left with the fact that if you have a single item and ask for an EMBEDDEDLIST, the current code will detect that you want a collection, and then return a  HashSet.  I still think this is a bug.

I actually am finishing up a PR, to fix the issue on its own right now.

**Comment by mmacfadden** [comment]
Hopefully, the PR I submitted will fix this issue.

**Comment by tglman** [comment]
@mmacfadden,

Merged your PR, closing
