### ISSUE TITLE
OrientDB RESTful API in Mathematica

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5542]
### Overview
The main function of this Mathematica package, `ODBapi`, is built on top of the [URLFetch][06] built-in function. [OrientDB RESTful HTTP API][07] commands are ported into Wolfram Language through [URLFetch][06] and then `ODBapi` commands are built with arguments that specify options with rules of the form `name -> value`. This package has also other utility functions especially implemented for OrientDB. `OrientDB Package` is part of the [DBAPI application project][08]. Visit the official page of the project for installation and testing instructions.

### Discussion
OrientDB is a multi-model, NoSQL, DBMS based on 16 years of research. Orient Technologies, the company that supports the product, has published more than 60 releases and there is constant and frequent adaptation to user demand and the latest technology available. OrientDB is Open Source and FREE for any purpose. Good news are that this **OrientDB Mathematica Package is also Open Source and Free**.

OrientDB is using an SQL-like programming language for managing data. We consider that this can be a turning point for innovation, adaptation, and extension of SQL language. Although SQL is widely used and familiar to many programmers, we argue that its use becomes complicated on graph data models. OrientDB SQL, i.e. **OSQL**, has been extended to cover operations on Graph Model, but with the cost of adding extra SQL commands. This level of detail can be hidden from the user, and a more abstracted language can be built to cover both the Graph Model and the underlying Document Model.

Moreover, normally SQL consists of a **Data Definition Language**, **Data Manipulation Language** and **Data Control Language**. In OrientDB there are 34 different commands divided into six categories. Four of them are related to the manipulation of data structure (Graph,Schema,Index,Database) and two of them concern operations (Create-Read-Update-Delete and Utility).

There is some analogy of **OSQL** with the `ODBapi` function of the `OrientDB Package`. We are overloading the function with multiple definitions that are derived from the use of optional and mandatory arguments. This differentation is based on the commands (Add, Del, Get, Update, Import/Export, Login/Logout) and the various data structures (Server, Database, Class-Vertex-Edge, Property, Record, Document, Value). See [ODBapi documentation page][09] for more information.

We argue that this effort to transform the OrientDB SQL set of commands to a function with parameters is a good start for a uniform, universal treatment of data language (**UDL**). Most important in such a design are: the parameter for the basic operation (**ADD, DEL, GET, UPD, LNK, IRT, LOG**), and the parameter for the type of construct e.g. **Database, Class, Property, Record, and Value**.

With that guideline in mind, SELECT becomes **GET**, INSERT and CREATE become **ADD**, TRUNCATE AND DELETE become **DEL**, UPDATE and ALTER become **UPD**. The current OrientDB package needs more programming effort to reach the state we described. But we foresee that it will be far more intuitive, user-friendly and easy to program than its SQL ancestor.

### Conclusion
Most of the functionality of [OrientDB HTTP-JSON API][07] is embedded in Mathematica.  The user is able to work with OrientDB database in the native Wolfram Language environment. The [DBAPI application project][08] in general combines fundamental bult-in data structures, [List][01], [Rule][02], [Association][03] and [Dataset][04] of the Wolfram Language with the native JSON permanent storage, retrieval  and manipulation mechanism of OrientDB database. The project is open source and free, therefore it can be downloaded from those interested in building [Mathematica application projects][05] and those interested in porting data from RESTful services and NoSQL databases into Mathematica.

[01]:http://reference.wolfram.com/language/ref/List.html
[02]:http://reference.wolfram.com/language/ref/Rule.html
[03]:http://reference.wolfram.com/language/ref/Association.html
[04]:http://reference.wolfram.com/language/ref/Dataset.html
[05]:http://reference.wolfram.com/workbench/index.jsp?topic=/com.wolfram.eclipse.help/html/tasks/applications/mathematicaapps.html
[06]:http://reference.wolfram.com/language/ref/URLFetch.html
[07]:http://orientdb.com/docs/2.1/OrientDB-REST.html
[08]:http://healis.eu/dbapi/
[09]:http://healis.eu/orientdb-package/#documentation-pages

**Comment by luigidellaquila** [comment]
Hi @healiseu 

Thank you very much, I'm closing this as it's not properly an issue.

Thanks

Luigi
