### ISSUE TITLE
Conditional execution script cant find if command executor java lib

### ISSUE THREAD

**Issue by cong-trinh** [orientechnologies/orientdb#5544]
Im trying to do conditional create vertex if not exist script command but it seems like the if command executor couldnt be found. 

        String cmd = "begin\n";
        cmd += "let record = create vertex Record set ruid = 'kingcongTestRecord'\n";
        cmd += "let fn = select from FirstName where firstName = 'kingcongTestFirstName'\n";
        cmd += "if ($fn is null) {'\n";
        cmd += "let fn = create vertex FirstName set firstName = 'kingcongTestFirstName'\n";
        cmd += "}'\n";
        cmd += "let edge = create edge HasFirstName from $record to fn\n";
        cmd += "commit retry 100\n";
        cmd += "return $edge";

        OIdentifiable edge = noTx.command(new OCommandScript("sql", cmd)).execute();

com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.if ($fn is null) {'

Im using version 2.1.8 
I took a peek inside in the core.sql and couldnt find an OCommandExecutorSQL* for the "IF" im wondering if im doing something wrong with my statement or the Java Client doesnt support conditional script yet.

Thanks!

**Comment by luigidellaquila** [comment]
Hi @cong-trinh 

it seems you have a quote after the open curly brace, I think that's the reason why it's not working, try to rewrite your script this way:

```
    String cmd = "begin\n";
    cmd += "let record = create vertex Record set ruid = 'kingcongTestRecord'\n";
    cmd += "let fn = select from FirstName where firstName = 'kingcongTestFirstName'\n";
    cmd += "if ($fn is null) {\n";
    cmd += "let fn = create vertex FirstName set firstName = 'kingcongTestFirstName'\n";
    cmd += "}\n";
    cmd += "let edge = create edge HasFirstName from $record to fn\n";
    cmd += "commit retry 100\n";
    cmd += "return $edge";

    OIdentifiable edge = noTx.command(new OCommandScript("sql", cmd)).execute();
```

Please let me know if it fixes the problem

BTW, right now the IF is not executed with a specific executor but it's managed by the command script executor itself (this will change in next releases)

Thanks

Luigi

**Comment by cong-trinh** [comment]
Thanks for getting back to me @luigidellaquila. The quotes was the problem. My mistake for overlooking the syntax. 

I fix the edge line and added the $fn

For those looking, ($fn is null) does not work and you will have to use ($fn.size() < 1) as I believe it returns a list.
