### ISSUE TITLE
Query doesn't use an index on linked record.

### ISSUE THREAD

**Issue by dmikov** [orientechnologies/orientdb#5546]
I have a graph of computers, employees and incidents connected with links (linklist) employees to computers, computers to incidents

Now I am trying to run a simple query (simplified even further for purposes of illustration) of finding employees with computers in certain department. The computer location is indexed, but following query does not see it or use it.

`select count(1) from Record_11_2  where 'Shoes' in computers.location`
Btw, coming from database world query below would be the understandable syntax, since location field is NOT a collection. In sql world even with one to many relationship the one below is what makes sense.
`select count(1) from Record_11_2  where computers.location = 'Shoes'`

Anyway both cases don't use indexes.

```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 10000000,
            "current": "#16:9999999",
            "documentAnalyzedCompatibleClass": 10000000,
            "recordReads": 10000000,
            "projectionElapsed": 11,
            "fetchingFromTargetElapsed": 132420,
            "evaluated": 10000000,
            "groupByElapsed": 0,
            "tips": [
                "Query 'SELECT count(1) FROM Record_11_2 WHERE 'Shoes' IN computers.location' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index"
            ],
            "elapsed": 132419.89,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,projectionElapsed=l,fetchingFromTargetElapsed=l,evaluated=l,groupByElapsed=l,elapsed=f"
        }
    ],
    "warnings": [
        "Query 'SELECT count(1) FROM Record_11_2 WHERE 'Shoes' IN computers.location' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index"
    ],
    "notification": "Query executed in 132.425 sec. Returned 1 record(s)"
}


{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 10000000,
            "current": "#16:9999999",
            "documentAnalyzedCompatibleClass": 10000000,
            "recordReads": 10000000,
            "projectionElapsed": 0,
            "fetchingFromTargetElapsed": 146164,
            "evaluated": 10000000,
            "groupByElapsed": 0,
            "tips": [
                "Query 'SELECT count(1) FROM Record_11_2 WHERE computers.location = 'Shoes'' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index"
            ],
            "elapsed": 146166,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,projectionElapsed=l,fetchingFromTargetElapsed=l,evaluated=l,groupByElapsed=l,elapsed=f"
        }
    ],
    "warnings": [
        "Query 'SELECT count(1) FROM Record_11_2 WHERE computers.location = 'Shoes'' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index"
    ],
    "notification": "Query executed in 146.17 sec. Returned 1 record(s)"
}
```

Now if I execute it directly on Computers, then it is able to see it.

`select count(1) from Record_11_1  where location = 'Shoes'`

``````
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 453348,
            "fullySortedByIndex": false,
            "documentAnalyzedCompatibleClass": 453348,
            "recordReads": 453348,
            "fetchingFromTargetElapsed": 2835,
            "indexIsUsedInOrderBy": false,
            "compositeIndexUsed": 1,
            "current": "#15:6290897",
            "involvedIndexes": [
                "Record_11_1.location"
            ],
            "projectionElapsed": 10,
            "limit": -1,
            "evaluated": 453348,
            "groupByElapsed": 0,
            "elapsed": 2910.994,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,compositeIndexUsed=l,current=x,involvedIndexes=e,projectionElapsed=l,evaluated=l,groupByElapsed=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 2.923 sec. Returned 1 record(s)"
}```

Still very slow, but you already have 2 tickets related to not counting index entries.
``````

**Comment by smolinari** [comment]
Try a "*" instead of "1". 

`select count(*) from Record_11_2 where computers.location = 'Shoes'`

Scott

**Comment by dmikov** [comment]
Why would it make any difference and why are you suggesting it? Did it helped you when it didn't use the index? Is there a documented feature of select affecting index usage?
And no it makes no difference.

**Comment by smolinari** [comment]
It was just a shot in the dark because of this thread. https://groups.google.com/forum/#!topic/orient-database/woKXcJxVF7U

Scott

**Comment by dmikov** [comment]
ok, I realized that count() by index has a bug, so to prevent spinning wheels, I tried the query.
`select from Record_11_2 where 'Shoes' in computers.location limit 10`
same result, no index used. I also want to point out that linked list is indeed of type Record_11_1 (where location field is indexed)
```{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 321,
            "current": "#16:320",
            "documentAnalyzedCompatibleClass": 321,
            "recordReads": 321,
            "fetchingFromTargetElapsed": 6,
            "evaluated": 321,
            "elapsed": 6.203366,
            "resultType": "collection",
            "resultSize": 10,
            "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,evaluated=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 0.011 sec. Returned 1 record(s)"
}```

**Comment by luigidellaquila** [comment]
Hi @dmikov 

the current index implementation allows chained index usage in case of links, so if you had an index on `Record.computer` and another on `Computer.location` then both indexes would be used to optimize the query.

In your case you have no indexes on `computers` so the executor won't be able to optimize it. Anyway, I'm not completely sure it would work for a collection (computers)

Thanks

Luigi

**Comment by dmikov** [comment]
I tried, it shows that it used indexes, but in reality it didn't still pulled 10 million records to find one.
`{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 10000000,
            "current": "#16:9999999",
            "documentAnalyzedCompatibleClass": 10000000,
            "recordReads": 10000000,
            "involvedIndexes": [
                "Record_11_1.location",
                "Record_11_2.computers"
            ],
            "limit": -1,
            "fetchingFromTargetElapsed": 116939,
            "evaluated": 10000000,
            "tips": [
                "Query 'SELECT FROM Record_11_2 WHERE 'Swimlane' IN computers.location' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index"
            ],
            "elapsed": 116939.81,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,involvedIndexes=e,fetchingFromTargetElapsed=l,evaluated=l,elapsed=f"
        }
    ],
    "warnings": [
        "Query 'SELECT FROM Record_11_2 WHERE 'Swimlane' IN computers.location' fetched more than 50000 records: to speed up the execution, create an index or change the query to use an existent index"
    ],
    "notification": "Query executed in 116.945 sec. Returned 1 record(s)"
}`

**Comment by dmikov** [comment]
So is it a no? You do not support indexes on linklist children?

**Comment by amcdnl** [comment]
any feedback @lvca

**Comment by luigidellaquila** [comment]
@dmikov no, right now we do not support this complexity. Probably it will be supported in next releases, but it's not officially in the roadmap

Thanks

Luigi
