### ISSUE TITLE
Can't insert nested Embedded Maps when schema property is defined

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#5547]
Given that we execute the following insert:

``` sql
CREATE class Test
INSERT INTO Test SET map1 = { 'map2': { 'key': 'value' } }
```

This results in a "raw" document that looks like this:

``` JSON
{
  "@type": "d",
  "@rid": "#16:3",
  "@version": 1,
  "@class": "Test",
  "map1": {
      "map2": {
          "key": "value"
      }
  }
}
```

Note that the "map1" field has been created as an EMBEDDEDMAP.  Within the "map1" map, there is another field named "map2".  This has also been created as an EMBEDDEDMAP.  This is as desired.

However, if we use schema to make the "map1" property an EMBEDDEDMAP when we create the class and then do the insert as such:

``` sql
CREATE class Test
CREATE property Test.map1 EMBEDDEDMAP
INSERT INTO Test SET map1 = { 'map2': { 'key': 'value' } }
```

Then the document that is created will look like this:

``` json
{
  "@type": "d",
  "@rid": "#16:0",
  "@version": 1,
  "@class": "Test",
  "map1": {
      "map2": {
          "@type": "d",
          "@version": 0,
          "key": "value"
      }
  }
}
```

As you can see "map2" is now an EMBEDDED (ODocument) instead of and EMBEDDEDMAP.  This seems like a bug.  Keep in mind, in the first case where the map1 property was not defined, "map1" was created as an EMBEDDEDMAP.  Why then when I define "map1" as an EMBEDDEDMAP in the schema, all of a sudden does "map2" now become a document instead of an map.

I have traced the issue to the OCommandExecutorSQLInsert class.  Specifically the "parse" method calls parseSetFields (line 158).  The OCommandExecutorSQLSetAware.parseSetFields method eventually calls the "convertValue" method.  On line 102 of OCommandExecutorSQLSetAware the "p != null" is true when the property ("map1") is defined.  The switch statement drops down to line 154 because "map1" is an EMBEDDEDMAP.  The code now loops through the map, and converts all of the maps in "map1" to ODocuments.  If the "map1" property was not defined, the the if statement on line 102 would have been false, and the entire code block would be skipped, leaving "map2" alone.

For the moment, the work around is to define the "map1" property as "ANY" instead of an EMBEDDEDMAP.  Doing this, I can still make the property mandatory, but I can't enforce the type, which should be a map.

I have created a unit test which demonstrates the issue:

https://gist.github.com/mmacfadden/af1fb4ef0f596a7bcc70

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

it seems to be a bug, I'll check it and I'll let you know

Thanks

Luigi

**Comment by mmacfadden** [comment]
Thanks.  If it turns out to be a bug in your opinion.  I could work on a fix.
