### ISSUE TITLE
Wrong Index used when querying for multiple fields (Composite Index)

### ISSUE THREAD

**Issue by nightrise** [orientechnologies/orientdb#5549]
Hi,

For a given class "Person" which has both an index on the field "age" and a composite index on the fields "age" and "kids_count", if I execute a query such as:

SELECT FROM Person WHERE age >= 18 AND kids_count > 0

The query executes only using the "age" index, not the "age_kids_count" index. I discovered this by using EXPLAIN on the query, and the "involvedIndexes" field always comes back with the "age" index.

If I drop the "age" index and only leave the "age_kids_count" index, then the query correctly uses the latter.

I'm currently using OrientDB 2.1.7.

**Comment by luigidellaquila** [comment]
Hi @nightrise 

a composite index can be used only if at most last condition is a range condition, eg. if your query were
```
SELECT FROM Person WHERE age = 18 AND kids_count > 0
```
it would use the composite index.

This is a normal behavior for tree-based indexes (not only for OrientDB)

Thanks

Luigi

**Comment by nightrise** [comment]
Hi Luigi,

Thanks for the answer, wasn't aware of that. Is there no way to do a double range query using a composite index then? If I set an index on kids_count and an index on age, would it use both indexes?

**Comment by nightrise** [comment]
Also, Luigi, in my above example, it did end up using the composite index for two range queries, but only when I dropped the other index. According to your explanation, wouldn't it just use no index?

**Comment by luigidellaquila** [comment]
Hi @nightrise 

there seems to be some other optimization involved here, I have to check it.
Anyway, in last case the index is being used only partially (only for "age")

Thanks

Luigi
