### ISSUE TITLE
GA dates for Orient DB 2.2

### ISSUE THREAD

**Issue by shajigopal** [orientechnologies/orientdb#5550]
Can you give us an approximate date when OrientDB 2.2 will be GA. We are waiting for the fix for issue #4941.

**Comment by mmacfadden** [comment]
Hi @shajigopal,

I will let the team answer for themselves.  However, you might find an answer to your question by monitoring this page:

http://orientdb.com/docs/last/Roadmap.html

It's been a few weeks since it was updated, probably because of the holidays.  It is updated fairly regularly.

**Comment by shajigopal** [comment]
Thank you @mmacfadden .

**Comment by lvca** [comment]
Docs updated.
