### ISSUE TITLE
HTTP API > Batch SQL > Prepared statements with parameters

### ISSUE THREAD

**Issue by mihai-stancu** [orientechnologies/orientdb#5552]
I've successfully used the [command](http://orientdb.com/docs/2.1/OrientDB-REST.html#command) functionality for running prepared statements with parameters as described in the documentation (worked with >= v2.2-alpha).

The [batch](http://orientdb.com/docs/2.1/OrientDB-REST.html#batch) functionality doesn't specify the possibility of using prepared statements with parameters. Is this possible? Is it a planned feature in a future release?

I've tested using 
```
{
    "transaction": true,
    "operations": [
        {
            "type" : "cmd",
            "language" : "sql",
            "command": "COMMAND1..."
            "parameters": {"param1": "value1", "param2": "value2"}
        },
        {
            "type" : "cmd",
            "language" : "sql",
            "command": "COMMAND2..."
            "parameters": {"param1": "value1", "param2": "value2"}
        },
    ]
}
```

But as expected (based on the documentation) it didn't work.

**Comment by mihai-stancu** [comment]
I checked `OServerCommandPostBatch` (in *develop*) and I see there is no code handling any *parameters* key within the *operation* item and no `.execute(params)` function call (as was the case with `OServerCommandPostCommand`).

So the answer is no -- for now, parameters are not currently supported via the HTTP API. I'll take a stab at implementing them by mimicking the `OServerCommandPostCommand`. Please let me know if this feature is in the works already.

**Comment by mihai-stancu** [comment]
I created a [branch](https://github.com/mihai-stancu/orientdb/tree/batch_prepared_statements_with_params) for my work but didn't PR yet, I'm trying to run the tests and failing.

I'm running `mvn -e -X clean test` on `develop` and I'm getting:

```
Results :

Failed tests: 
  OStoragePerformanceStatisticTest.testCacheHitCount:213->testMBeanCase:378 expected [true] but found [false]
  OStoragePerformanceStatisticTest.testCommitTime:177->testMBeanCase:340 expected [false] but found [true]
  OStoragePerformanceStatisticTest.testReadSpeedFromCache:46->testMBeanCase:340 expected [false] but found [true]
  OStoragePerformanceStatisticTest.testReadSpeedFromFile:79->testMBeanCase:340 expected [false] but found [true]
  OStoragePerformanceStatisticTest.testWriteSpeedToCache:112->testMBeanCase:340 expected [false] but found [true]
  OStoragePerformanceStatisticTest.testWriteSpeedToFile:145->testMBeanCase:340 expected [false] but found [true]
  JNADirectMemoryTest.testByte:78 »  

There is an incompatible JNA native libra...
  JNADirectMemoryTest.testBytesWithOffset:118 NoClassDefFound Could not initiali...
  JNADirectMemoryTest.testBytesWithoutOffset:94 NoClassDefFound Could not initia...
  JNADirectMemoryTest.testChar:65 NoClassDefFound Could not initialize class com...
  JNADirectMemoryTest.testCopyData:133 NoClassDefFound Could not initialize clas...
  JNADirectMemoryTest.testCopyDataOverlap:152 NoClassDefFound Could not initiali...
  JNADirectMemoryTest.testCopyDataOverlapInterval:171 NoClassDefFound Could not ...
  JNADirectMemoryTest.testInt:52 NoClassDefFound Could not initialize class com....
  JNADirectMemoryTest.testLong:38 NoClassDefFound Could not initialize class com...
```

I'm running on linux (Ubuntu 15.10), I didn't do much to setup my project (I'm not a Java dev) I just checked out develop and opened it with Jetbrains IDEA, the IDE asked if i wanted to download the necessary dependencies, I accepted...

**Comment by lvca** [comment]
@mihai-stancu  I think now compilation problem should be gone on develop branch. Your PR will be welcome ;-)

**Comment by mihai-stancu** [comment]
OK, running the tests now. I'll issue the PR soon (if nothing fails).

**Comment by mihai-stancu** [comment]
There still are some failing tests:

```
Failed tests: 
  OStoragePerformanceStatisticTest.testReadSpeedFromCache:45->testNoMBeanCase:271 expected [9765] but found [-1]
  OStoragePerformanceStatisticTest.testReadSpeedFromFile:79->testMBeanCase:378 expected [97656] but found [-1]
  OStoragePerformanceStatisticTest.testWriteSpeedToCache:112->testMBeanCase:340 expected [false] but found [true]
  OStoragePerformanceStatisticTest.testWriteSpeedToFile:145->testMBeanCase:340 expected [false] but found [true]
  JNADirectMemoryTest.testByte:78 »  

There is an incompatible JNA native libra...
  JNADirectMemoryTest.testBytesWithOffset:118 NoClassDefFound Could not initiali...
  JNADirectMemoryTest.testBytesWithoutOffset:94 NoClassDefFound Could not initia...
  JNADirectMemoryTest.testChar:65 NoClassDefFound Could not initialize class com...
  JNADirectMemoryTest.testCopyData:133 NoClassDefFound Could not initialize clas...
  JNADirectMemoryTest.testCopyDataOverlap:152 NoClassDefFound Could not initiali...
  JNADirectMemoryTest.testCopyDataOverlapInterval:171 NoClassDefFound Could not ...
  JNADirectMemoryTest.testInt:52 NoClassDefFound Could not initialize class com....
  JNADirectMemoryTest.testLong:38 NoClassDefFound Could not initialize class com...
```

N.B.: in one test-run the only failed test was `  JNADirectMemoryTest.testByte:78 »  `.

**Comment by lvca** [comment]
Are you using OpenJDK? Could you please use Oracle JDK?

**Comment by mihai-stancu** [comment]
Yes, openjdk is the default on ubuntu. I'll install oraclejdk.

On 07:07, Thu, Jan 7, 2016 Luca Garulli <notifications@github.com> wrote:

Are you using OpenJDK? Could you please use Oracle JDK?

**Comment by mihai-stancu** [comment]
After a rebase on develop, with Oracle JDK installed:

```
Failed tests: 
  OStoragePerformanceStatisticTest.testReadSpeedFromFile:79->testMBeanCase:378 expected [97656] but found [-1]
  OStoragePerformanceStatisticTest.testWriteSpeedToCache:112->testMBeanCase:340 expected [false] but found [true]
  OStoragePerformanceStatisticTest.testWriteSpeedToFile:145->testMBeanCase:340 expected [false] but found [true]
```

**Comment by mihai-stancu** [comment]
Sure, I'll try and write some tests for this feature.

**Comment by lvca** [comment]
Are you still working on it? Do you have anything to share?

**Comment by mihai-stancu** [comment]
Hi,

No, unfortunately I've been swamped and the unfamiliarity of the toolset
made pinpoint focused work hard to come by.

On 11:36, Mon, May 9, 2016 Luca Garulli <notifications@github.com> wrote:

> Are you still working on it? Do you have anything to share?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5552#issuecomment-217806953>
>
-- 
Mihai Stancu
http://mihai-stancu.ro
http://about.me/mihai.stancu

**Comment by octal-laurence** [comment]
this is sad, to many basic features are missing for easy developing
