### ISSUE TITLE
Packaging orientdb with lucene in one .jar file is not possible

### ISSUE THREAD

**Issue by EricSchreiner** [orientechnologies/orientdb#5553]
We are shipping our application in on .jar-file. Because of the structure of the plugins

d:\java\source\Applications\PicApport\lib\orientdb-lucene-2.1.8.jar\META-INF\services\com.orientechnologies.orient.core.index.OIndexFactory
d:\java\source\Applications\PicApport\lib\orientdb-lucene-2.1.8.jar\META-INF\services\com.orientechnologies.orient.core.sql.operator.OQueryOperatorFactory

it seems not to be possible to combine 
orientdb-core-2.1.8.jar and
orientdb-lucene-2.1.8.jar

in one .jar file. 

Is there a workaround?

**Comment by robfrank** [comment]
Hi Eric, can you explain with more details the problem? Which version of orient, what tool are you using to pack your app (maven, gradle, homemade). It is quite difficult to help you without details. 
Best regards,
RF

**Comment by robfrank** [comment]
What tool are you using to create the fat jar?
I found that the Maven shade plugin  offers more configurability options than others:
https://maven.apache.org/plugins/maven-shade-plugin/

**Comment by EricSchreiner** [comment]
hi @robfrank 
we are using ANT to create the .jar files. Again the problem is, that both of your *.jar-files*
*orientdb-core-2.1.8.jar* and *orientdb-lucene-2.1.8.jar*
contain the **same files** in the same directory with **different content**:
*orientdb-lucene-2.1.8.jar\META-INF\services\com.orientechnologies.orient.core.index.OIndexFactory
orientdb-lucene-2.1.8.jar\META-INF\services\com.orientechnologies.orient.core.sql.operator.OQueryOperatorFactory*
So it is not possible to combine them in one jar File. I don't think that Maven addresses this problem.

**Comment by maggiolo00** [comment]
hi @EricSchreiner 

with maven and shade you can merge resources files

https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html

**Comment by robfrank** [comment]
Hi, the maven shadep plugin provides resource transformers, and in particular the service resource transformer:

http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer

For ant, after some search, I found this:

https://github.com/pescuma/merge-jar-services

**Comment by EricSchreiner** [comment]
Hi @robfrank 
thanks, the https://github.com/pescuma/merge-jar-services
worked fine for me.
