### ISSUE TITLE
Change a classes default cluster ID via SQL command.

### ISSUE THREAD

**Issue by neRok00** [orientechnologies/orientdb#5557]
There does not appear to be a way to modify the `defaultClusterId` (as spelt in various places of the docs) via an SQL command. I have tried things such as `alter class Foo defaultClusterId=99` and `alter class Foo custom defaultClusterId=99`.

Similarly, it does not seem to be possible to set `clusterId` property. If `defaultClusterId` is always the first cluster id of the `clusterId` list (I'm not sure if it actually is...), then I guess the real issue here is being able to set the `clusterId` property. I tried various commands such as `alter class Foo custom clusterId=[99,12,13,14]`, which did not work.

Additionally, it would probably be good to have the ability to reorganise the clusterId list, as it would effect the order of clusters used by some of the different cluster selection strategies. I might want to do something like `alter class Foo custom clusterId=[99,14,12,13]`

PS - someone else asked this question previously on a mailing list. I will copy their email here.

[**How to modify the default cluster id for a class?**
Sally Ahn Thu, 12 Feb 2015 21:54:40 -0800](https://www.mail-archive.com/orient-database@googlegroups.com/msg08366.html)

> Hello,
> 
> I'm having trouble finding the right command to set the default cluster id 
> for a class.
> I created a Datacenter class, added 3 clusters to it (usa_datacenter, 
> asia_datacenter, europe_datacenter), and deleted the original default 
> datacenter cluster. So now, my Datacenter class does not have any default 
> cluster associated with it:
> 
> Class................: Datacenter
> Super class..........: V
> Default cluster......: null (id=-1)
> Supported cluster ids: [15, 16, 17]
> Cluster selection....: default
> orientdb {db=Test}> info class Datacenter
> 
> I would like to set the default cluster to be the "usa_datacenter".
> This doc 
> https://github.com/orientechnologies/orientdb/wiki/SQL-Create-Class#cluster-selection-strategy
>  mentions 
> a `defaultClusterId` property of a class, but the alter class 
> https://raw.githubusercontent.com/wiki/orientechnologies/orientdb/SQL-Alter-Class.md
>  command 
> does not list it as a supported attribute name.
> (As a side note, are class "properties" equivalent to "attributes" in this 
> context? If not, what is the distinction?)
> Can you please help?
> 
> Thanks,
> Sally

**Comment by smolinari** [comment]
What is the use case or problem are you trying to solve? 

Scott

**Comment by neRok-** [comment]
No issue, I'm just fiddling and thought it should be possible, but it turns out it isn't.

The email post I quoted is a valid use case though (IMO).

**Comment by smolinari** [comment]
Hmm.....well, a sort of workaround to Sally's use case is to intentionally name the first class Datacenter_USA, create the two other clusters, then rename the class. I don't believe renaming the class will rename the default cluster. Might be something to try out to see. :smile: 

After that, you can change cluster names at will too. I would presume they would have to be unique within the class, so, you can control cluster identification with the names. You don't need to mess with ids. 

As for positioning of clusters, you can control the position at cluster creation, though this isn't something I understand myself and the docs don't explain cluster positioning much either. Maybe one of the devs could explain a bit better what the position at cluster creation is all about?

And, seeing as how clusters are all about data distribution, I would think that the distribution strategy should be completely clear up front and shouldn't be messed with much, if at all, once any data has been distributed. Though, I am no expert. So I could be completely wrong too. 

Scott

**Comment by luigidellaquila** [comment]
Hi guys,

I'm flagging it as an enhancement

**Comment by tglman** [comment]
Hi,

Implemented in 3.0, closing

Regards
