### ISSUE TITLE
Prepend to a collection using UPDATE

### ISSUE THREAD

**Issue by Solido** [orientechnologies/orientdb#5559]
I can use UPDATE ADD to append to a collection field but what if I want to PREPEND to a collection to only get the last added element ?

`UPDATE entries PREPEND myCollection = value`

and then i can query

`SELECT myCollection[0] FROM entries`

to get sure to always query the last added element.

Is there a way to query for the last element of a collection in another way ?

Thank you for pieces of advice on this point.

Warmly,
Robert

**Comment by luigidellaquila** [comment]
Hi @Solido 

I flagged this an an enhancement, it will be added to the roadmap

Thanks

Luigi

**Comment by mmacfadden** [comment]
Hello @Solido and @luigidellaquila ,

I am wondering if this more generalized feature would solve your problem:

https://github.com/orientechnologies/orientdb/issues/4748

We want to be able to insert and remove at any position.  It seems like if you could do this, then you could PREPEND simply by inserting at position 0.

**Comment by Solido** [comment]
Hello @mmacfadden It looks we face the same requirement.

My proposal to use the keywork APPEND is there because it's a common pattern in array structure but my feelings about the OrientDB is that they is always a word for a pattern and if it's uncommon, like adding at position 3 then you can rely on a 'JAVAesque' notation to fill the gap.

The OriendDB community and devs can define what are the best expression for the solution(s) to keep with the current philosophy

I put there some suggestions based on your index idea and also a keyword approach.

## Working with INDEX
'UPDATE Account ADD addresses[2] = 'orange'
UPDATE Account ADD addresses.at(2) = 'orange'

UPDATE Account REMOVE addresses[2]
UPDATE Account REMOVE addresses.at(2)'

## Working with KEYWORD and common Pattern

The APPEND is a very simple and common pattern but it does not cover insert at position
I guess OrientDB should vote if they want to see this in the SQL language

'UPDATE Account **APPEND** addresses = 'orange'
UPDATE Account **ADD HEAD** addresses = 'orange'

UPDATE Account **POP** addresses // remove and return
UPDATE Account **REMOVE [HEAD/FIRST]** addresses 
UPDATE Account **REMOVE [TAIL/LAST]** addresses '

Also maybe we should merge the issue together as long as we talk about the KEYWORD approach !

Best regards

**Comment by mmacfadden** [comment]
Hi @Solido,

Thanks for the clarification.  One question.  In you last response, you mention "APPEND".  This is what the keyword "ADD" already does.  In you original post you were looking for "PREPEND".  PREPEND seems to be the same as "ADD HEAD" in your latest post.

Also, I somewhat like the idea of POP.  This is very normal.  Would you consider using POP (Remove last), PUSH (add at end), SHIFT (remove at beginning), and UNSHIFT (add at beginning) as keywords.  These are very common and only require one word (each) to handle all four cases.  Thoughts?

I am actually working on implementing some of this right now, and hope to have a pull request by early next week.

**Comment by Solido** [comment]
The *VERBS* you propose seems quite naturals !

Those features are really powerful and offers a lot of new ways to push OrientDB.
I hope to see more comments of users and devs to validate the grammar. Also I'm quite surprised that this has not been proposed previously. Thank you @mmacfadden

#### Add a value at the beginning of a collection, UNSHIFT instead of PREPEND
`UPDATE Account UNSHIFT fruits = 'orange'`

#### Remove the value at the beginning of a collection
`UPDATE Account SHIFT fruits`

#### Remove the last value
`UPDATE Account POP addresses`

#### Using index
`UPDATE Account ADD fruits[3] = 'orange'`
`UPDATE Account REMOVE fruits[4]`

**Comment by smolinari** [comment]
:+1: on more control over collections!

Scott

**Comment by Solido** [comment]
Is this on the roadmap ? clearly I miss this feature nearly every day even thinking about very badly patch just to be able to add an element on the head of a collection and not queue.

Please consider the numbers of real life use cases this solve !

Thanks !

**Comment by luigidellaquila** [comment]
Hi guys,

Little update on this. In V 3.0 we will have the following syntax:

```
UPDATE xxx SET field = value1 || value2
```

If value1 and value2 are collections, the result is the concatenation of the collections. If one is a collection and the other one is not, the result is prepending on appending, eg.

```
[1, 2, 3] || [4, 5] = [1, 2, 3, 4, 5]
[1, 2, 3] || [4] = [1, 2, 3, 4]
[1, 2, 3] || 4 = [1, 2, 3, 4]
1 || [2, 3, 4] = [1, 2, 3, 4]
```

For `null` values there is the following specific behavior
```
[1, 2, 3] || null = [1, 2, 3]
[1, 2, 3] || [null] = [1, 2, 3, null]
```

This feature is already implemented in `develop` branch, the `UPDATE ADD` syntax is not supported anymore.

We are about to release the first milestone (advanced alpha), it will happen in next few days.

Thanks

Luigi

**Comment by a-unite** [comment]
> the ` UPDATE ADD ` syntax is not supported anymore

Dear Luigi, does it mean UPDATE will have breaking back compatibility syntax with versions prior 3?
Hope I got it wrong, but how we should ADD values to the list field then?

Something like referencing the field's name in operation?
```
UPDATE xxx SET **field** = **field** || value2
```

**Comment by smolinari** [comment]
I don't mean to be picky, but are the double pipes/ bars "||", also known as the logical short circuiting "OR" in many programming languages, really a good/ intuitive choice for prepending/ appending collection values? 

What happened to [the suggestion from @mmacfadden](https://github.com/orientechnologies/orientdb/issues/4748 )?

That seems like the most "SQL like" way to go about it and it also allows for insertion of elements within the collection too. It also solves a-unite's question too. 😜 

Scott

**Comment by luigidellaquila** [comment]
Hi guys,

@a-unite yes, in 3.0 M1 the UPDATE ADD syntax will be removed, so it's not backward compatible, but the main goal of M1 is to gather users feedback, so if we have many requests to restore it, we will do it in the GA

@smolinari I understand, it was my concern as well, but:

1. PostgreSQL uses the same syntax: https://www.postgresql.org/docs/9.1/static/functions-array.html

2. an alternative could be to use `+`, but it would collide with string concatenation

3. about the suggestion from @mmacfadden, it could be an alternative but:
- it's more verbose 
- it's less flexible, think about `1 || [2, 3] || 4 || [5, 6]`, how would you do it?
- I don't like very much to have all these UPDATE ADD/PUT/INCREMENT alternatives when you can do everything with a much clearer UPDATE SET and the right operator, for this same reason I introduced `+=`, `-=`, `*=`, `/=`, `%=` operators

I hope it makes sense to you as well :)

Thanks

Luigi

**Comment by smolinari** [comment]
Yeah, I can understand your concerns and I'm also all for reduction of verbosity. However, less verbosity should also not mean a loss in intuitiveness. And, ODB isn't Postgres. 😉 

Could you also clarify the other operators and how they work or rather reference any docs explaining them? It would be better to have the full picture of all collection altering functionality, before offering any proper feedback. 😄 

Scott

**Comment by luigidellaquila** [comment]
Hi Scott, 

Sure! Here you can find all the info. 

https://github.com/orientechnologies/orientdb-docs/blob/docs_review_30/sql/SQL-Syntax.md

The documentation process is still in progress, but this page is quite complete

Thanks

Luigi

**Comment by smolinari** [comment]
Thanks. 

You said:

> for this same reason I introduced +=, -=, *=, /=, %= operators

These don't offer collection/ array element manipulation though, do they?

I also seem to think we are talking past each other. This suggestion requests prepending without knowledge of the actual collection. 

For instance, Postgres offers something like this for prepending:

UPDATE some_table SET some_field[0] = "some value"

For merging into an array:

UPDATE some_table SET some_field[2:3] = '{"some value", "some other value"}'

The only thing that is missing from Postgres is an append, without needing knowledge of the actual array. 

Whereas this might be possible (not sure, as I've never used Postgres to be honest): 

UPDATE some_table SET some_field[ array_length(some_field, 1) ] = "some value".

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

The `+=, -=, ... ` was about the UPDATE ADD, not about collections (my bad, it was a bit confusing probably).

For the rest:
```
UPDATE some_table SET some_field[0] = "some value"
```
IMHO this is a bit misleading, this expression should replace the first element, not prepend

```
SET some_field[2:3] = '{"some value", "some other value"}'
```
replacing two elements at once? I didn't consider this, but it definitely makes sense, now you should do
```
SET some_field[2] = "some value", some_field[3] = "some other value"
```
if it's about merging, then you can do
```
SET some_field = some_field[0..2] || ["some value", "some other value"] || some_field[2..some_field.size()]
```

Anyway, my general point is that I don't like very much the syntax
```
UPDATE X PUT a = b
```
it's practically unreadable. A better syntax would be
```
 UPDATE X PUT b into a
```
or something similar, I hope you got my point.

But it's not a standard syntax, it's more verbose and it's a breaking change anyway, so I preferred to use the syntax from a known SQL db that has native collections.

Thanks

Luigi

**Comment by smolinari** [comment]
> IMHO this is a bit misleading, this expression should replace the first element, not prepend

You are right. It is a replacement. 

>replacing two elements at once? I didn't consider this, but it definitely makes sense, now you should do

> SET some_field[2] = "some value", some_field[3] = "some other value"

Always aiming to help! 😄 

I am also gathering that the `field[<element>]` syntax for accessing collection/ array elements is also used in ODB? That wasn't clear to me either to be honest and is missing in the docs you linked to. 

Is this possible for appending? 

`SET some_field = some_field[some_field.size()] || ["some value", "some other value"]`

Or maybe this for prepending ( @a-unite 's question)?

`SET some_field = ["some value"] || some_field[0..some_field.size()]  


Also, out of curiosity. Are all collections/ arrays always only accessible through numbered indexes starting from 0?

Scott

**Comment by luigidellaquila** [comment]
Hi Scott,

Yes, that is syntactically correct. I don't know if the behavior is what you expect though: this
```
SET some_field = some_field[some_field.size()] || ["some value", "some other value"]
```
sets the field value to a new collection of three elements, where the first element is last element of last NULL (it would be last element of the old array, if you set `some_field.size()-1` ;-) )

About your last question, yes, collections are accessible through integer numbers, but you can use the same notation to access maps by key.

Thanks

Luigi

**Comment by smolinari** [comment]
Ok. How about this, now that I understand, I think.... LOL! 😄 

`SET some_field = some_field[0..some_field.size()] || ["some value", "some other value"]`

That should append, correct?

This would be much nicer, I think:

`SET some_field = append(some_field, "some value", "some other value")`

and 

`SET some_field = prepend(some_field, "some value", "some other value")`

Theoretically, we could even remove "some_field =".


😄 

Scott

**Comment by luigidellaquila** [comment]
Yes, that's correct, but you can do it much easier 😉 :

```
SET some_field = some_field || ["some value", "some other value"]
```

About the functions, I plan to add some of them for sure, to cover cases where the syntax is too ugly

Thanks

Luigi

**Comment by smolinari** [comment]
> Yes, that's correct, but you can do it much easier 😉 :

Oh Duh! LOL!

Ok. I think we (you and I) are on the same wave length. I hope everyone else could follow! 

Looking forward to what you come up with in terms of functions too!

Scott

**Comment by a-unite** [comment]
Luigi, thank you. So my guessing was right and this is `SET some_field = some_field || "some value"` the way for selfreference, not something like `= @value || "some value"`.
The only question - does this syntax mean we will be able to put value of another field as well?
Something like 
```
SET some_field = another_field || ["some value", "some other value"]
```

As for dropping compatibility - I'm sure deprecating ADD (as short version of the first snippet) syntax for v3 (but still supporting it till version 4, or 3.5) might be the right way for smooth adoption.

Regards,
Ata

**Comment by luigidellaquila** [comment]
Hi Ata,

Yes, you can also set the value on another field of course. 

Thank you for the feedback about deprecating vs. dropping, let's re-discuss it in next few weeks, after M1 is out.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi guys,

This is a pretty old issue and already resolved.
I'm closing it, please feel free to re-open if you need further info

Thanks

Luigi
