### ISSUE TITLE
JPA - Problem with register class

### ISSUE THREAD

**Issue by alboll** [orientechnologies/orientdb#5560]
Hey there,

I try to use orientDb with jpa. So far the most things work out. But I have one Pojo which is named "System". I tried both ways the register the entity (like http://orientdb.com/docs/2.1/JPA-Configuration.html) and used the complete package name of the class. But both times orientDb says:

com.orientechnologies.orient.core.exception.OSerializationException: Type system cannot be serialized because is not part of registered entities. To fix this error register this class

When I rename the class everything works fine. Is it forbidden to use a Pojo with the name "system"?

**Comment by tglman** [comment]
hi @alboll,

Yes orientdb use the class name as unique identifier so call a class 'System' is tricky because of `java.lang.System` i would say this is a limitation of the object database, so please just not use a class called 'System'
