### ISSUE TITLE
OriendDB Objects not getting droppped from memory

### ISSUE THREAD

**Issue by hitesk** [orientechnologies/orientdb#5562]
I have a use-case where I need to create OrientGraph(In memory) for each service call. At the end of service call, I drop the graph from code. But its not getting removed leading to gradual increase in service heap memory usage and service restart.
I guess, I am not dropping the graph properly. Appreciate your quick help.

**Comment by hitesk** [comment]
Code references:

public class DocumentTransformer {

    private static final int MAX_RETRY_COUNT = 3;

    private Message<?> message;
    private OrientGraphNoTx graph;
    private Multimap<String, Map<String, Object>> databaseRecords;
    private DocumentToGraphTransformer documentToGraphTransformer;

    protected Object transform(Message<?> message) throws Exception {
        this.message = message;
        this.databaseRecords = HashMultimap.create();
        this.documentToGraphTransformer = new DocumentToGraphTransformer();
        this.graphToDatabaseRecordsTransformer = new GraphToDatabaseRecordsTransformer();

        transformDocumentToDatabaseRecords();
        ........
        ........
    }

    private void transformDocumentToDatabaseRecords() {

        Document doc = getDocument();

        for (int retryCount = 0; retryCount < MAX_RETRY_COUNT; ++retryCount) {
            try {
                this.graph = documentToGraphTransformer.transform(doc);
                generateDatabaseRecordsForTable(tableName);
                break;

            } catch (Exception e) {
                if (retryCount < MAX_RETRY_COUNT) {
                     this.databaseRecords = HashMultimap.create();
                    continue;
                } else {
                    throw e;
                }
            } finally {
                finalizeTransformationOperation();
            }
        }
    }

    private void finalizeTransformationOperation(Metrics metrics, long startTime) {

        if (this.graph != null && !this.graph.isClosed()) {
            this.graph.drop();
        }
    }


public class DocumentToGraphTransformer {

    public OrientGraphNoTx transform(Document doc) {
       
        OrientGraphNoTx graph = new OrientGraphNoTx("memory:" + UUID.randomUUID().toString());
        populateGraph(doc, graph);
        return graph;
    }

    private void populateGraph(Document doc, OrientGraphNoTx graph) {

        GraphManager graphManager = new GraphManager(graph);

        try {
            graphManager.addVertexFromDocumentEntity(doc.getEntities());
            generateEdges(graphManager, doc);
        } catch (Exception e) {
            graph.drop();
            throw new DocumentTransformationException("Failed to transform document into OrientGraph", e);

        }
    }
    private void generateEdges(GraphManager graphManager, Document doc) throws InterruptedException {

        Vertex sourceVertex = null;
        Vertex destinationVertex = null;

        for (Entity entity : doc.getEntities()) {

            sourceVertex = graphManager.getVertices(GraphQueryConstants.IDENTIFIER, entity.getIdentifier().toString())
                    .get(0);

            for (EntityReference entityReference : entity.getReferences()) {
                destinationVertex = graphManager.getVertices(GraphQueryConstants.IDENTIFIER,
                        entityReference.getIdentifier().toString()).get(0);
                addEdge(sourceVertex, destinationVertex, entityReference.getName(), graphManager);
                addEdge(destinationVertex, sourceVertex, GraphQueryConstants.REVERSE_EDGE + entityReference.getName(),
                        graphManager);
            }
            graphManager.getGraph().commit();
        }
    }

    private void addEdge(Vertex sourceVertex, Vertex destinationVertex, String edgeValue, GraphManager graphManager){

        for (int retryCount = 0; retryCount < 3; ++retryCount) {

            try {
                graphManager.addEdge(sourceVertex, destinationVertex, edgeValue);
                graphManager.getGraph().commit();
                break;
            } catch (ONeedRetryException | OTransactionException e) {
                logger.warn("Exception occured while adding an edge:{" + edgeValue + "} with exception:{"
                        + e.getMessage() + "}. Retrying.");
                graphManager.getGraph().rollback();
                if (retryCount == MAX_RETRY_COUNT - 1) {
                    throw e;
                }
            }
        }
    }
}

**Comment by hitesk** [comment]
Please do let me know, if you need extra information

**Comment by hitesk** [comment]
We are facing issues in production. So request you to guide a bit faster. Thanks.

**Comment by lvca** [comment]
Could you please dump the open storages after the drop?

    Orient.instance().getStorages();

You can also try calling:

    Orient.instance().shutdownAllStorages();

**Comment by hitesk** [comment]
Thanks for quick look. I will do the dump of storage messages.

One question: Wont doing 'Orient.instance().shutdownAllStorages();' will also close other open storage instances used by other threads in multi-threaded environment?

**Comment by lvca** [comment]
Yes, so you can use `Orient.instance().getStorage("test").shutdown();`

**Comment by saritseal** [comment]
Hi,
You can use jung2 API
Regards
Sarit

**Comment by hitesk** [comment]
I have tried to dump open storage instances, but always I am getting count as either 0 or 1.
Sometimes its 2 or 3.
This is the change that I have made in dropGraph() function.

private void dropOrientGraph() {

        if (this.graph != null && !this.graph.isClosed()) {
            this.graph.drop();
        }
        if (Orient.instance() == null) {
            logger.info("Orient instance is null. Existing");
            return;
        }
        Collection<OStorage> storageCollection = Orient.instance().getStorages();
        if (storageCollection == null || storageCollection.size() == 0) {
            logger.info("Storage collection is either null or zero");
        }
        logger.info("Open OrientDB storage instance: " + storageCollection.size());
        for (OStorage storage : storageCollection) {
            logger.info("Storage Name: " + storage.getName());
            logger.info("Storage URL: " + storage.getURL());
            logger.info("Storage " + storage.countRecords());
        }
    }

**Comment by hitesk** [comment]
Is there something wrong with the way, I close/drop the graph().
When I tried to analyze the heap of the service, most of the host memory(almost 70%) is used by objects of class:
com.orientechnologies.common.profiler.OProfiler

**Comment by hitesk** [comment]
Hi Luca,
It will be really helpful if you can provide quick help.
Thanks
Hitesh

**Comment by lvca** [comment]
Are you using the Enterprise Edition? However, try to set `-Dprofiler.enabled=false` in the JVM to disable profiler.

**Comment by hitesk** [comment]
I have made this change and deployed it. Not seeing much improvement as of now. I am waiting for a day to get clear metric and heapdump. Then I will update with more details.

**Comment by hitesk** [comment]
Yes, we are using enterprise edition. Version - 2.0.5

**Comment by lvca** [comment]
Any news on this? Does that setting resolved the problem?

**Comment by lvca** [comment]
Closing because no answer. In case please reopen/comment it.

**Comment by hitesk** [comment]
Dprofiler change worked. Thanks for the help!

**Comment by lvca** [comment]
Cool, thanks for the feedback.
