### ISSUE TITLE
Opening Document Database in Windows with UNC path is not working

### ISSUE THREAD

**Issue by nadestin** [orientechnologies/orientdb#5563]
Version 2.1.8 GA. Following program in Windows gives an Exception:

```java
public class UNCTest
{
  public static void main(String[] args)
  {
    String url = "plocal:\\\\srv\\db\\Database";
    ODatabaseDocumentTx db = null;

    try
    {
      db = new ODatabaseDocumentTx(url).open("admin", "admin");
      System.out.println("Database is opened");
    }
    finally
    {
      if(db != null)
        db.close();
    }
  }
}
```
Changing URL to the Unix style "plocal://srv/db/Database" doesn't help.

It seems that special handling for Windows inside of the `loadStorage()` function comes too early.

**Comment by nadestin** [comment]
Following patch seems to solve the problem:

diff --git a/core/src/main/java/com/orientechnologies/orient/core/Orient.java b/core/src/main/java/com/orientechnologies/orient/core/Orient.java
old mode 100755
new mode 100644
index 8581548..cf00dac
--- a/core/src/main/java/com/orientechnologies/orient/core/Orient.java
+++ b/core/src/main/java/com/orientechnologies/orient/core/Orient.java
@@ -435,14 +435,6 @@
     if (iURL.endsWith("/"))
       iURL = iURL.substring(0, iURL.length() - 1);
 
-    if (isWindowsOS()) {
-      // WINDOWS ONLY: REMOVE DOUBLE SLASHES NOT AS PREFIX (WINDOWS PATH COULD NEED STARTING FOR "\\". EXAMPLE: "\\mydrive\db"). AT
-      // THIS LEVEL BACKSLASHES ARRIVES AS SLASHES
-      iURL = iURL.charAt(0) + iURL.substring(1).replace("//", "/");
-    } else
-      // REMOVE ANY //
-      iURL = iURL.replace("//", "/");
-
     // SEARCH FOR ENGINE
     int pos = iURL.indexOf(':');
     if (pos <= 0)
@@ -461,6 +453,15 @@
 
       // SEARCH FOR DB-NAME
       iURL = iURL.substring(pos + 1);
+
+      if (isWindowsOS()) {
+          // WINDOWS ONLY: REMOVE DOUBLE SLASHES NOT AS PREFIX (WINDOWS PATH COULD NEED STARTING FOR "\\". EXAMPLE: "\\mydrive\db"). AT
+          // THIS LEVEL BACKSLASHES ARRIVES AS SLASHES
+          iURL = iURL.charAt(0) + iURL.substring(1).replace("//", "/");
+        } else
+          // REMOVE ANY //
+          iURL = iURL.replace("//", "/");
+
       pos = iURL.indexOf('?');
 
       Map<String, String> parameters = null;

**Comment by nadestin** [comment]
Following patch seems to solve the problem.
Actually it simply moves few lines of code down to the proper place.

[orientdb-patch.zip](https://github.com/orientechnologies/orientdb/files/80934/orientdb-patch.zip)

**Comment by laa** [comment]
@nadestin agree with you , thank you for the patch.
