### ISSUE TITLE
Embedded distributed Orient server - add hooks for exception handling

### ISSUE THREAD

**Issue by ygoraly** [orientechnologies/orientdb#5565]
I am using Orient in embedded distributed mode, and would like to be able to handle exceptions.
I had to override OHazelcastPlugin.startup in order to change System.exit() calls, and don't have a solution for exceptions that happen after startup.
1) Add a callback/hook/configuration so an exception will be thrown instead of System.exit
2) Support listeners for distributed-related exceptions that happen after startup

**Comment by lvca** [comment]
The reason for System.exit() is to avoid a node starts if pre-conditions are not met. It's better to avoid starting the node that having a node where you think it's ok (who read the logs?) and it isn't.

What's your use case?

**Comment by ygoraly** [comment]
My use case is that the database is embedded inside a larger system (one of several Servlet contexes).
If there is a failure to start, or any other distributed exception, we would like to do our own exception handling (such as notify an admin or disable just that module while keeping the rest of the system running).
If we decide to shut down the system, it should be done in a controlled way, not by System.exit call of one of the libraries.
It will be very hard to impossible to get  a buy-in from the rest of the team if custom error handling is supported.

**Comment by lvca** [comment]
We already have this in v2.2:

      ENVIRONMENT_ALLOW_JVM_SHUTDOWN("environment.allowJVMShutdown", "Allows the shutdown of the JVM, if needed/requested",
      Boolean.class, true, true),

You can set this property to false to avoid shutting down the JVM in this case.
