### ISSUE TITLE
Performance degradation of UPDATE with LOCK RECORD in 2.1.x

### ISSUE THREAD

**Issue by kowalot** [orientechnologies/orientdb#5566]
One of the OrientDB internal tests  ConcurrentUpdatesTest:concurrentPessimisticSQLUpdates()
(After adding time measurement available here   https://gist.github.com/anonymous/305d33338c9f94c12b55   )

shows performance degradation of UPDATEs with pessimistic locking is much worse comparing to OrientDB 2.0.x

Below results on my test machine

v2.1.8
ConcurrentUpdatesTest.concurrentPessimisticSQLUpdates()
private final static int PESSIMISTIC_CYCLES = 10000;
private final static int THREADS            = 12;
Elapsed time [ms]:79284
Rate ops/sec:1513

v2.0.16
ConcurrentUpdatesTest.concurrentPessimisticSQLUpdates()
private final static int PESSIMISTIC_CYCLES = 10000;
private final static int THREADS            = 12;
Elapsed time [ms]:23581
Rate ops/sec:5088

v2.0.8
ConcurrentUpdatesTest.concurrentPessimisticSQLUpdates()
private final static int PESSIMISTIC_CYCLES = 10000;
private final static int THREADS            = 12;
Elapsed time [ms]:17488
Rate ops/sec:6861

**Comment by laa** [comment]
Well , let me check.
In reality in 2.0 version pessimistic lock implementation has bugs which leads to deadlocks in system probably pessimistic locks in reality provides much less speed up than we expected. I will try to improve   speed up if that is possible of course.

**Comment by laa** [comment]
That is results on my pc:
2.0.x version:
Rate ops/sec:33975

Before change: 
Rate ops/sec:25157

After change:
Rate ops/sec:31096

It is not the same as before , but I think something which we may live with.
Could run the same test on you pc on develop branch and publish numbers ?

I will push code in few minutes.

**Comment by laa** [comment]
Pushed

**Comment by kowalot** [comment]
Thanks Andrey! I will check it this weekend and let you know.

**Comment by kowalot** [comment]
I don't see any substantial improvement. I run the test against new code resulting
Rate ops/sec:1790
which is still far from 5000-6000 for older versions on my machine.

**Comment by laa** [comment]
Hi,
How did you run the code , using develop branch or latest snapshot  ?

On Sat, Feb 13, 2016, 15:09 Pawel Kowalski <notifications@github.com> wrote:

> I don't see any substantial improvement. I run the test against new code
> resulting
> Rate ops/sec:1790
> which is still far from 5000-6000 for older versions on my machine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5566#issuecomment-183662472>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by laa** [comment]
Also unfortunately previous design lead to issues  when system will be accedentally deadlocked https://github.com/orientechnologies/orientdb/issues/4090 (that is only one from many reported) so I do not think that we will revert to it. I will try to speed up system performance though.

**Comment by laa** [comment]
could you do following , profile lock test and send me profiling results, because on my pc as you can see performance almost the same 33975 vs 31096 .

**Comment by kowalot** [comment]
I tested develop branch.

**Comment by kowalot** [comment]
@laa you are right. It strikes me too why my results are lower by order of magnitude. 
Can you be more specific what should I test now? I got lost.

**Comment by laa** [comment]
I have taken your test and run it on develop branch. Could you do the same test using yourkit profiler for example and send me profiling results ?

**Comment by laa** [comment]
Got your snapshot, could you do the same for 2.0.x version so we will see the difference ?

**Comment by laa** [comment]
Hi, could you apply this patch to develop and check how much difference will you get ?https://drive.google.com/file/d/0B2oZq2xVp841OGZialRULVpIZFE/view?usp=sharing

**Comment by kowalot** [comment]
Unfortunately I didn't see noticeable gain after applying patch.
However I realized that we can talk about test under different storageType. Mainly I am talking about remote usage.
So I again conducted the test with different storage type which also can help us nail the problem down.

![image](https://cloud.githubusercontent.com/assets/3010480/13126101/724d5fc8-d5c9-11e5-9228-5622c32420fa.png)

I shared with you also three Yourkit profiler snapshots for each version (memory,plocal,remote).
As you see ratio between different storage types are different which may give you a clue where the problem is located. But also beside that, overall performance is worse then before.

**Comment by laa** [comment]
Sorry @kowalot (( , it is not record lock issue but remote connection issue all locking stuff happens on plocal side, there is can not be difference between remote and plocal. 
So I assign this to @tglman . I am really sorry but it is not my part.

**Comment by kowalot** [comment]
@laa I agree that the main problem is related to remote channel, but anyway 17k >> 12k, so I guess here is potential another issue.

**Comment by laa** [comment]
@kowalot new design was supposed to be slower.

**Comment by lvca** [comment]
@laa What do you mean?

**Comment by laa** [comment]
@lvca I mean that it uses more bigger call stack so by definition it will be slower. But I do not think that comparison is reasonable there. If feature has robustness issues does not matter how fast it is, we may operate with performance numbers only for correct solutions or improvements.

**Comment by laa** [comment]
but still bug raised by @kowalot detects some remote connection issues which should be investigated.

**Comment by tglman** [comment]
hi @all

did some check, cross version:
```
plocal:
2.0.x:34497
2.1.x:17383
develop:32660
``` 

```
remote:
2.0.x:18327
2.1.x:10511 
develop:13266
```

Don't look to the absolute numbers they changes following the machine, but for 2.0.x and 2.1.x the remote is ~50% slower of plocal on develop is ~65% slower, for develop i was already working on it. i'll see if i can find a way to improve general performance of the remote without break anything.

In general the remote performance follow the performance of the plocal, so i think is worth to investigate also the plocal implementation.

**Comment by laa** [comment]
Hi @tglman , 
Did you run the same test as Pawel ?
He experienced 75% slowdown on remote storage.

Also did you run server and client on the same machine ?
If so could you explain reason of such big slowdown even without presence of remote server placed on separate node ? What numbers of slowdown do you expect in case of LAN connection to remote server ?

**Comment by laa** [comment]
Also @tglman about slowdown numbers. In 2.1.x remote storage 1.65 times slower on connection to the same machine (17383 / 10511 = 1.653), on 2.2.x it is already (32660 / 13266 = 2.461) 2.46 times slower than plocal, or if compare numbers between versions in 2.2 remote is (2.46 / 1.65 = ) 1.49 times slower than in 2.1.x. 

So I have 3 questions:

 1. What justifies changes which provide such big slow down between versions ?
 2. Is it reasonable that simple data transfer on the same PC consumes more time than all procedures inside database ?
3. Could you share numbers of slowdown between between remote and plcoal in case of server is placed on another machine inside of LAN ?

**Comment by smolinari** [comment]
I'm very interested in this. Just commenting to mark for following better.

Scott

**Comment by laa** [comment]
@tglman It just stroke me that we need to manipulate by overhead which provides remote not by composite numbers. So I converted rec/s in average latency and calculated overhead of remote storage in average latency.

So I got following numbers (in microseconds on single record):
2.1.x: plocal - 57.5, remote - 95.1 , overhead on remote storage -  37.6 
2.2.x plocal - 30.61, remote 75.3 , overhead on remote storage - 44.69

Which actually gives us : 44.69/37.6 = 1.18.
So in reality remote storage is 18% slower on your tests.

But still my questions are:

1. Is it reasonable that simple data transfer on the same PC consumes more time than all procedures inside database?
2. Could you share numbers of slowdown between remote and plocal in case of server is placed on another machine inside of LAN ?
3. "for develop i was already working on it", what changes do you mean ?
4. Why on @kowalot side we have such bad numbers any way ?

**Comment by tglman** [comment]
Hi,

Let me explain the architecture of the remote database today:
The network layer as today is plugged at storage level at client side, and at server side use ODatabaseDocument api, this cause that sometime we do twice the same checks, and there is an historical reason for that: avoid to send the server invalid data, check in the server for security reasons.

as well the behviour of the server database is different, we have to do additional security check for guarantee that we are speaking with an authored client, and the server is a stateless environment (we clear the local cache for the session at each request.)

and yes obviously there is serialization and deserilization of the content/request, but that is quite cheap.

In the specific use case the client side cost of the a sql query is relatively low, we don't do check on it.

one my mistake, i thought that the default configuration of the test was plocal, instead is memory, so this are the number i get from plocal:
```
plocal:
2.0.x:23659
2.1.x:16810
develop:22152
```

reporting previus remote:
```
remote:
2.0.x:18327
2.1.x:10511 
develop:13266
```

Answering to question:
1. no is not, and actually is not true (my wrong measure), and actually the remote is not a simple transfer, and it cannot be because of security and different caching approach.
2. No number right now, just got localhost test, and i think is the best way to test pure implementation overhead, we need this test for latency and bandwidth check though.
3. In 2.2 i changed the authentication management that was a requirement for stabilize the live query, i'm working to make it as lightweigth as it was before, with additional security and scalability, i just merged some of the changes i was working on.
4. that can depends for different machine, or in network test.

bye

**Comment by kowalot** [comment]
@laa Could you please share my yourkit snapshots with @tglman ?
There are some basic information about my computer so all these things together may means something. All my tests are done on single machine (localhost loopback).

Generally it would be good to have some "smart" performance counters repository where we can compare numbers from each release. I am not talking about absolute numbers but some percentage/ relative numbers getting us an insight about impact of introduced changes.

Let me know if I can help somehow more by testing some patches.

**Comment by smolinari** [comment]
@lvca - another person asking for a bench marking suite/ results. :smile: 

Some links that relate:  
https://github.com/orientechnologies/orientdb/issues/1846
https://github.com/orientechnologies/orientdb/issues/5483

Scott

**Comment by laa** [comment]
@kowalot done

**Comment by tglman** [comment]
@kowalot 

one thing i noticed that was taking a lot of time was the compression/decompression, did you use it also in 2.0 ? did you tried to run the test without compression ?

**Comment by kowalot** [comment]
I did my tests on default configuration. I will let you know how it looks with/without compression.

**Comment by tglman** [comment]
hi @kowalot,

Any news about this ?
