### ISSUE TITLE
Edges of Graph - Out(), In() Links are inconsistent ?

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5571]
Hi,
assume we have created a Graph database, i.e. useLightweightEdges=false. Make a Many-To-Many relationship model for Parts, Suppliers and Catalogue. You create Part and Supplier Vertex Classes and Catalogue as an Edge Class. Populate with records and bridge the two classes with the Edge class.

* **`Supplier ----- OUT ----- Catalogue ----- IN ----- Part`**

Now if you execute
`select from Part`
You get among other fields  of Part  the IN_Catalogue Links, i.e. RIDs from Catalogue

and if you execute
`select from Supplier`
You get among other fields of Supplier the OUT_Catalogue Links, i.e. RIDs from Catalogue

So far, so good, but if you execute
`select out() from Supplier`
**You get  the RIDs of Part not the RIDs of Catalogue !!!**

and in the same way 
`select in() from Part`
**You get  the RIDs of Supplier not the RIDs of Catalogue !!!**

Isn't that confusing, inconsistent perhaps with what it is displayed from previous queries ?

Do notice also that in the case you set useLightweightEdges=false
this inconsistency is resolved immediately, because Edges are record-less and the links point directly from one Class to the other.

PS: I am preparing a full demo on this toy example and I will refer to this once I have it ready....

**Comment by smolinari** [comment]
If you consider an edge is the representation of the relationship between two vertexes, then it makes perfect sense to get the related parts to a supplier, when you ask for the relation between the two. 

[From the docs.](http://orientdb.com/docs/2.1/Tutorial-Working-with-graphs.html#querying-graphs)

>To cross edges, you can use special graph functions, such as:
>
>OUT() To retrieve the adjacent outgoing vertices
>IN() To retrieve the adjacent incoming vertices
>BOTH() To retrieve the adjacent incoming and outgoing vertices

Scott

**Comment by healiseu** [comment]
Yes, it makes perfect sense, but then, as I have already stated, my objection is on the output of 

>  __select from Supplier__ 

>  __select from Part__

where
* OUT displays the adjacent outgoing edges
* IN displays the adjacent incoming edges

**Comment by smolinari** [comment]
Yes, the selects shows you the links to the edges. What do you want to see? 

Scott

**Comment by healiseu** [comment]
@smolinari in my opinion, for the reason I have explained, this is an inconsistent use of OUT or IN and personally I am confused when I see this.

**Comment by smolinari** [comment]
As I understand ODB, the out(), in() and both() functions give you the related vertices. The links you see in the class select queries are what are needed for ODB to give you the proper related data. In graph database mode though, the links are abstracted away from you. In other words, you don't need to be concerned about them really, if you are working with graphs. 

In document mode, ODB lets you work with links as relationships to other documents (and why you can see the links in a select query). 

That is just my understanding. I could also be wrong. 

Scott

**Comment by healiseu** [comment]
Thank you @smolinari for the effort to explain. I am making a demo of graph and document databases  to illustrate these points. Then we can continue our discussion in both this and the other issue I have posted. I have been searching on the internet and I noticed that you can hardly find any good post illustrating and demonstrating these concepts among **Graph, Document and ASSOCIATIVE** databases, so I have decided to make my own to show the differences. Hope this will make a landmark for those researching in data modelling.

**Comment by a-unite** [comment]
@healiseu,

please, look at outE() ans inE() functions (http://orientdb.com/docs/2.1/SQL-Functions.html#outE)

I believe this is what you are looking for.

AU

**Comment by luigidellaquila** [comment]
Hi guys, 

Let me just add a little comment to this thread. The reason why we use out() and in() to return vertices instead of edges is the historical consistency with TinkerPop Gremlin API http://gremlindocs.spmallette.documentup.com/#out


Thanks

Luigi

**Comment by healiseu** [comment]
@luigidellaquila thanks this is a useful comment indeed. May I also add that in the case of Lightweighted Edges, i.e. there is not any Edge record, you do VIEW VERTICES on the browsing table of STUDIO. Therefore @lvca the statement I made about inconsistency in this issue DOES make sense.

In the browsing table of STUDIO when you view Lightweight EDGES with OUT or IN, i.e. OUT() or IN() you get vertices

In the browsing table of STUDIO when you view EDGES with OUT or IN, I expect OUT() and IN() AGAIN, you view edges NOT vertices !

**Comment by a-unite** [comment]
Dear @healiseu,

I think you mixed up with properties and functions.

For those functions to work (to know how vertex is connected) you defenitely need to store pointer (link infomation) in some kind of property (what you see as in and out properties).

What you see in Studio - are _properties_ needed for traversal functionality. For 'full type' connection (proper edges) - vertex points to that edges, which are pointing to the next vertex then. For lightweight edges (AKA links) edges are missed and vertex points (through _special kind of property) directly to another vertex instead.

What is important here - functions (ie IN('connection_class') or OUT('edge_label')) will work the same in both cases. 

According to your second question - I'm not sure it is easy to implement without adding extra layer of complexity, but in our framework - we just store 'human' titles for different edges perspectives as custom fields in edge classes. Although we show them in UI only, hiding all unnecessary details about ODB from users, it works well and helps with "verbal" connection labels a lot.

**Comment by healiseu** [comment]
@a-unite thank you for the effort to provide justification. For the discussion on this issue
> What is important here - functions (ie IN('connection_class') or OUT('edge_label')) will work the same in both cases.

Yes, I have already noticed that, both Lightweighted Edges and Edges with Records. OUT() and IN() functions behave consistently, i.e. they return VERTICES

Then you explain
> What you see in Studio - are properties needed for traversal functionality. For 'full type' connection (proper edges) - vertex points to that edges, which are pointing to the next vertex then. For lightweight edges (AKA links) edges are missed and vertex points (through _special kind of property) directly to another vertex instead.

Fine, but then you should make clear that this OUT and IN in the case of full type connection are outE() and inE() and in the case of lightweight edges are out() and in(). You use the same OUT and IN labels with different meaning behind. @lvca and @luigidellaquila this is exactly the reason I insist that this is inconsistent. 

By the way your naive user does not have a clue what this IN and OUT really means. Then if he turns to documentation for help he will find all these functions with IN and OUT and the most close to what is displayed is the in() and out() but these return vertices not edges.

OK this is my last effort to explain this from my point of view.

**Comment by healiseu** [comment]
@a-unite for the issue on whether it is possible to [assign different labels for edge or different labels for OUT, IN](https://github.com/orientechnologies/orientdb/issues/5568)

You wrote, 
>store 'human' titles for different edges perspectives as custom fields in edge classes. Although we show them in UI only, hiding all unnecessary details about ODB from users, it works well and helps with "verbal" connection labels a lot.

@lvca and @luigidellaquila I am not sure I understand what these 'human' titles are but would it be possible to add an extra pair for master-inverse and unhide this for the user.
