### ISSUE TITLE
Python driver

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5574]
Python is by most accounts one of the top 5 programming languages (and maybe **the** top "interpreted" programming language), in the world today

(see e.g. http://spectrum.ieee.org/computing/software/the-2015-top-ten-programming-languages
and http://pypl.github.io/PYPL.html)

but there is currently no "official" Python driver for OrientDB

(http://orientdb.com/docs/2.1/Programming-Language-Bindings.html)

Even worse, it seems that the previously-widely-used community-supported driver, pyorient, no longer works with OrientDB (see e.g. #4334 and (*)).  

Regarding the other bindings that are listed:
- All signs are that Compass has been moribund for some time.
- It's hard to say what the current status of the Bulbflow project is in relation to OrientDB 2.1, but Bulbflow seems to be a one-person project, and does not directly support OrientDB.

It seems to me that the best shot for Python support might be for someone at OrientTechnologies to help with pyorient maintenance in some way.  For many, a well-supported python driver is a _sine qua non_ for the use of OrientDB, either because they want it for themselves, or because they'll use its existence as a barometer of OrientDB's health and prospects.

Anyway, this is a plea for **an "Official Driver" for python**. 

(*) "As of today, the Orientdb that is downloaded by default from their site uses protocol v. 32, while pyorient uses protocol v. 28. I'd say it is unmaintaind to the point of unusability – jsbueno Nov 19 '15 at 12:38"

**Comment by lodrion** [comment]
We are using (our own fork of) https://github.com/mogui/pyorient it works with the newest protocol. I have no clue why orientdb's own fork has not been updated.

**Comment by pkoppstein** [comment]
@lodrion - "pip install pyorient" is still installing pyorient-1.4.4; to install pyorient-1.4.6a0: 

`pip install --pre --upgrade pyorient`

In any case, as previously mentioned, Python being what it is, it would be reassuring to know that there is an **official** Python binding somewhere (where hopefully "official" means "OrientTechnologies-supported").
