### ISSUE TITLE
Parser Code Generation Question

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#5575]
Hello,

I am not sure if the is an issue, or if I just don't know how the parser code generation works.  I wanted to make sure that the proper way to add a new production is to add it to the grammar file, let the parser generate a stub class and then edit it manually, and then check it in?  I tried just generating a new production similar to some of the other ones, and it didn't compile because it was missing class properties.

**Comment by mmacfadden** [comment]
Of note the code before I redid the generation looked like this:

```Java
/* Generated By:JJTree: Do not edit this line. OUpdateIncrementItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.Map;

public class OUpdateIncrementItem extends SimpleNode {
  protected OIdentifier left;
  protected OModifier   leftModifier;
  protected OExpression right;

  public OUpdateIncrementItem(int id) {
    super(id);
  }

  public OUpdateIncrementItem(OrientSql p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }


  public void toString(Map<Object, Object> params, StringBuilder builder) {
    left.toString(params, builder);
    if (leftModifier != null) {
      leftModifier.toString(params, builder);
    }
    builder.append(" = ");
    right.toString(params, builder);
  }
}
/* JavaCC - OriginalChecksum=94dd82febb904e4e31130bdcbbb48fe3 (do not edit this line) */
```

After, it looked like this:

```Java
/* Generated By:JJTree: Do not edit this line. OUpdateIncrementItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

public
class OUpdateIncrementItem extends SimpleNode {
  public OUpdateIncrementItem(int id) {
    super(id);
  }

  public OUpdateIncrementItem(OrientSql p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=94dd82febb904e4e31130bdcbbb48fe3 (do not edit this line) */
```

Both the properties and the to string method are missing.  I should not that I am just doing a mvn clean install and letting javacc run as part of the generate sources phase as defined in the pom file. Perhaps there is some goal I should be running directly?

**Comment by mmacfadden** [comment]
It also occurs to me, that perhaps the source files are being edited manually after generation.  So it seems that either I am not generating them right.  Or perhaps I need to add a new production and then modify it manually?

**Comment by mmacfadden** [comment]
I think I have figure this out.  My assumption is that when defining a new production, the javacc-jjtree plugin will create a stub class for you, which you can then add properties too.  If some one can just confirm that that is the right workflow, I think I am all set.

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

exactly, only the stubs are generated by the parser, then they are maintained manually, so you cannot delete and re-generate them

Thanks

Luigi
