### ISSUE TITLE
LinkMap Key misbehaving when contains "]"

### ISSUE THREAD

**Issue by guglielmomoretti** [orientechnologies/orientdb#5583]
Hello Orient Team,

We are using OrientDB V 2.1.7

We have a structure similar to the one described in [Time Series](http://orientdb.com/docs/2.1/Time-series-use-case.html).

We recently have had problems with the key of one of our linkmaps. it seems like the character "*]*" is not supported inside map's key.

We have a very "bad" key like [123_abc_#1239#1___'0571234'512354128|||] . 
We have no problem in adding it to the map, but we do have problems while retrieving its value.

A Simple 
```SQL
SELECT code["[123_abc_#1239#1___'0571234'512354128|||]"] from TransitsCode
```
Returns nothing:
![image](https://cloud.githubusercontent.com/assets/2829667/12236631/45924220-b87b-11e5-8fb7-9ffdc82294bc.png)

And also the count is wrong 
Actually, the returning count is as I would have run 
```SQL
SELECT from TransitsCode
```

If I try to insert in the map a key like [123_abc_#1239#1___'0571234'512354128||| (without the ending closed square bracket ) then the query works properly.

Any ideas? 
It seems like the closed square bracket breaks the SQL Parser.

Our workaround is to convert our map key to HEX to avoid this issue, but this increases dramatically the difficulty of writing queries by hand (in the studio, for instance). 

Regards

**Comment by luigidellaquila** [comment]
Hi @guglielmomoretti 

This issue was fixed in v 2.2.1

Closing

Thanks

Luigi
