### ISSUE TITLE
Connect on a non-default port via orientdb-console

### ISSUE THREAD

**Issue by efesaid** [orientechnologies/orientdb#5585]
I could not find port setting. Is it possible to connect remote server on non-default ports via orientdb-console?

**Comment by smolinari** [comment]
In the docs.

>If you would like the database server to listen at different ports or IP address, you can define these values in the configuration file `config/orientdb-server-config.xml`.

http://orientdb.com/docs/last/Tutorial-Run-the-server.html

Scott

**Comment by luigidellaquila** [comment]
Thanks a lot @smolinari 

@efesaid did you find all the answers you needed? Can I close this?

Thanks

Luigi

**Comment by efesaid** [comment]
@luigidellaquila No i did not.

@smolinari I already changed the default ports from the config file but i can not connect via orientdb-console to server.

For instance
orientdb> CONNECT remote:orientdb.example.com:**<remote-port>**/GratefulDeadConcerts admin

How can i specify non-default remote port in console command above?

**Comment by luigidellaquila** [comment]
Hi @efesaid 

just try

```
orientdb> connect remote:orientdb.example.com:2424/GratefulDeadConcerts admin admin
```

(or replace 2424 with your custom port)

Thanks

Luigi

**Comment by efesaid** [comment]
Thank you @luigidellaquila 

It will be better if you update the docs :)
