### ISSUE TITLE
Failed to create Class property results in property created.

### ISSUE THREAD

**Issue by guglielmomoretti** [orientechnologies/orientdb#5590]
Having the following snippet:

```SQL
CREATE CLASS Test
CREATE CLASS TestMap
CREATE PROPERTY Test.map LINKMAP String
```

Will result in the following exception on the last line:

**com.orientechnologies.orient.core.exception.OSchemaException: Linked type is not supported for type: LINKMAP**

This is because string is not a supported linked type. And this is correct.

After this, if I try to recreate the property using the correct type **TestMap**, i get this:

**com.orientechnologies.orient.core.exception.OCommandExecutionException: Property 'Test.map' already exists. Remove it before to retry.**

This is because the first creation of the **map** property on the class **Test** ( even if it raised the exception above) resulted in the creation of an "empty" map property.

The following screenshot demonstrates this behaviour:

![image](https://cloud.githubusercontent.com/assets/2829667/12259892/e886c166-b918-11e5-9a6d-2c0e6ca12466.png)

Regards

**Comment by lvca** [comment]
What release?

**Comment by guglielmomoretti** [comment]
Sorry,

OrientDB 2.1.7

**Comment by luigidellaquila** [comment]
Hi @guglielmomoretti 

`CREATE PROPERTY` on a LinkMap requires a class name (links point to records, not to strings), but you are passing `String`, that is a basic type, this is why it's failing

Maybe in previous versions it succeeded just for a lack of consistency check, but it does not make sense at the execution level.

Thanks

Luigi

**Comment by guglielmomoretti** [comment]
Hi @luigidellaquila 

I know that linkmap requires a class name, this was not the problem.

The problem is that regardless the fact that the statement

```SQL
CREATE PROPERTY Test.map LINKMAP String
```

raises an exception, the property "map" is created and linked to nothing, as shown in the image.

IMHO the property should never be created if the statement returns error.

Thanks

Guglielmo

**Comment by luigidellaquila** [comment]
Hi @guglielmomoretti 

I agree, I'll check it

Thanks

Luigi

**Comment by tglman** [comment]
Hi,

Reproduced and fixed

bye
