### ISSUE TITLE
Can't migrate database from DB 2.1.5 to 2.1.9

### ISSUE THREAD

**Issue by kalmusr** [orientechnologies/orientdb#5591]
I copied database files from 2.1.5 to 2.1.9 and when I tried to open it I received the following error:

2016-01-12 11:37:26:773 SEVER Internal server error:
com.orientechnologies.common.exception.OException: Error on creation of shared resource
--> com.orientechnologies.orient.core.exception.OSchemaException: Duplicate superclass:'OIdentity' [ONetworkProtocolHttpDb]

In DB version 2.1.7 there was no problem.

Info: I'm not sure if it is related to the problem, but analyzed the OIdentity class, which contains documents both for the REST API [OUser] and for the Binary API [ORole] (since we use both), so the user names are duplicated.

**Comment by lvca** [comment]
The problem is when the database was previously imported: a bug generated double entries, but in 2.1.9 this check prevent to have double classes. So I fixed this case when the database contains double super classes.
