### ISSUE TITLE
How to check the replication status

### ISSUE THREAD

**Issue by sumedh1919** [orientechnologies/orientdb#5593]
Hi @lvca 
I've setup replication between OrientDBs  of 2 servers using the hazelcast, and would like to know the procedure to check the replication status between them i.e., whether Replication is broken or not.

**Comment by lvca** [comment]
What do you mean the status? OrientDB cluster auto-repair in case of conflicts. What's the case you've seen that hasn't been recovered?

**Comment by sumedh1919** [comment]
I've setup orientDB replication, and would like to know the procedure to check whether the replication setup was successful or got broken?

An example would be in MySQL we've command called show slave status which confirms whether replication is in place or got broken. Similary, is there a way in orientDB as well?

**Comment by sumedh1919** [comment]
would like to know the procedure to check whether the replication setup is working fine or got broken?

An example would be in MySQL we've command called show slave status which confirms whether replication is in place or got broken. Similary, is there a way in orientDB as well?

**Comment by lvca** [comment]
You can know it by executing [`HA STATUS`](http://orientdb.com/docs/last/SQL-HA-Status.html) command. If a node has problems it's status is set to OFFLINE from other members of the cluster. You can have a readable or json output.
