### ISSUE TITLE
Datetime format issue

### ISSUE THREAD

**Issue by sebastiandev** [orientechnologies/orientdb#5595]
When defining a date format to include 'T' as separator for time with miliseconds

``` sql
ALTER DATABASE DATETIMEFORMAT "yyy-MM-dd'T'HH:mm:ss.SSSSSS"
ALTER DATABASE TIMEZONE "UTC"

CREATE PROPERTY V.creation DATETIME
```

When trying to create a record/vertex I get an Unparseable exception

``` sql
CREATE VERTEX V CONTENT {id: 'test', creation: "2015-01-14T12:00:00.000122UTC"}
```

> com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Error on conversion of date '2015-01-14T12:00:00.000122UTC' using the format: yyyy-MM-dd'T'HH:mm:ss.SSSSSS
>  --> java.text.ParseException: Unparseable date: "2015-01-14T12:00:00.000122UTC"

The error happens, both programatically and through studio

**Comment by smolinari** [comment]
Does this work? 

`ALTER DATABASE DATETIMEFORMAT yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`

Scott

**Comment by sebastiandev** [comment]
Oh, yes!, that worked..

interesting. So even though I set the timezone, i need to add it to the format.

Thanks

**Comment by sebastiandev** [comment]
OK, hold on. It does work when executed on Studio. But it doesnt work when executing the create as a command over the REST Api. 

> u'Error: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Error on conversion of date \'2015-01-02T12:00:00.001000UTC\' using the format: yyyy-MM-dd\'T\'HH:mm:ss.SSSSSS\'Z\'\r\n--> java.text.ParseException: Unparseable date: "2015-01-02T12:00:00.001000UTC"'

Not sure if that \r\n may be the cause, and no idea why is even there...
