### ISSUE TITLE
DELETE EDGE causing performance issues

### ISSUE THREAD

**Issue by zhbanton** [orientechnologies/orientdb#5596]
Hi,

We are experiencing significant performance issues when trying to delete a large number of edges at once.  When trying to execute these queries, ODB becomes basically unresponsive or crashes.  On our platform, users can follow other users (a follow is represented by an edge between two users) and when we deactivate a user, we want to clear all their followees/followers.  We have tried the following 3 commands, all of which have been varying degrees of bad:

`DELETE edge Follow FROM #{rid}`
`DELETE edge Follow TO #{rid}`

`DELETE edge Follow WHERE (out = #{rid} OR in = #{rid})`

`DELETE edge Follow FROM (SELECT from #{rid})`
`DELETE edge Follow TO (SELECT from #{rid})`

Any idea how to optimize this? We are using version 2.0.2

Thanks.

**Comment by zhbanton** [comment]
I'm sorry, we're actually running 2.1.5 on production, just 2.0.2 locally

**Comment by luigidellaquila** [comment]
Hi @zhbanton 

probably the performance impact does not depend on how you execute the query but on what happens under the hood.
I suggest you to split the transaction in multiple chunks using LIMIT 

Thanks

Luigi

**Comment by zhbanton** [comment]
Ok, thanks a lot.  I am able to get it working by running this command:

```DELETE edge Follow WHERE (out = #{rid}) limit 20")```

The way I assumed it should be done based on the documentation is by running:

```DELETE edge Follow to #{rid} limit 20```

but that yields the following error message:

```OCommandSQLParsingException: Error on parsing command at position #0: Class 'LIMIT was not found```

Am I mistaken about that syntax or is that a bug, possibly related to https://github.com/orientechnologies/orientdb/issues/4148?
