### ISSUE TITLE
How to fix illegal state in vertex field

### ISSUE THREAD

**Issue by mriehl** [orientechnologies/orientdb#5599]
I am trying to delete old data from a graph database.

The command I use is this:

```
orientdb {db=app}> delete vertex RG where (out('HF') is null or in('BT') is null or out('LIA') is null or out(LIA').size() = 0)
```

And it works most of the times but some vertices seem to be corrupt:
```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from `RG`  WHERE (out('HF') is null OR in('BT') is null OR out('LIA') is null OR out('LIA').size() = 0 )

Error: java.lang.IllegalStateException: Invalid content found in out_HF field
```

My issue is I can't seem to find a way to get rid of them. I can't remove the vertice since querying it causes an IllegalStateException. I reckon if I was able to somehow get a hold on the rid it would be possible to delete it, but I can't think of a way to get the rid.

Any pointers on how I can deal with the invalid content?

**Comment by mriehl** [comment]
Looking at the code, is there any reason to not delete the vertex when this exceptions occurs? This would allow for cleanup of the graph without breaking traversals.

**Comment by lvca** [comment]
You're right, that exception has no sense, the graph at that point is dirty: better to continue with delete than stop the world. Thank you.

**Comment by mriehl** [comment]
Cool thanks for the quick reply and fix!
