### ISSUE TITLE
Cannot use class named Like in v2.1.9

### ISSUE THREAD

**Issue by larryaasen** [orientechnologies/orientdb#5602]
I have an existing database created with v2.0.5 and when I upgrade it to v2.1.9 it does not all the Edge class named "Like". This worked fine in v2.0.5 and v2.0.17, but not in v2.1.9. Here is a simple example of the failure:
```
CREATE DATABASE remote:localhost/mydatabase root root plocal graph;
create class Like extends E;
SELECT FROM Like;
```

Error:
```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: 
select FROM Like
Encountered " <FROM> "FROM "" at line 1, column 8.
Was expecting one of:
    <NULL> ...
    "true" ...
    "false" ...
    "{" ...
    <NULL> ...
    "{" ...
    "true" ...
    "false" ...
```

Can you help me make this work?

Thanks,
Larry

**Comment by luigidellaquila** [comment]
Hi Larry,

In V. 2.1 we introduced a new parser that is stricter than the previous one.
`Like` is now a reserved word, so you have to quote it with back ticks:
```
SELECT FROM `Like`;
```

As an alternative, you can disable the new parser setting `strictSql` to false  (see http://orientdb.com/docs/last/Release-2.1.0.html#strict-sql-parser) but you will loose all the advantages of the new parser (better validation, parameter passing in subqueries and many others)

Thanks

Luigi

**Comment by larryaasen** [comment]
Thanks, will try that.
