### ISSUE TITLE
Selectively updating records through binary protocol, w/o using UPDATE statement

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#5606]
Hi guys,

Here's the issue that I was discussing with the creator or PhpOrient library (https://github.com/Ostico/PhpOrient/issues/62).

In short:
1. There's a way to update a record using a binary protocol 
2. If someone removes edges manually from the records and saves it, then edges are lost
3. The real problem is that some of our records will have millions of edges coming in and out (I'm not exaggerating as we will be nearing that scenario pretty soon). Pulling the whole record to update a few fields in it and then saving it back is a costly operation while using `UPDATE` statement is not at all convenient. 
4. To avoid the problem it would be really cool to pull a record w/o edges using a fetch plan, for example, and then save it back w/o losing any edge connections.

**Question**: is there any future plan to provision partial record updates in binary protocol? That should be fairly easy to implement as you have it already in HTTP protocol, is it not?

**Comment by tglman** [comment]
before 2.2 the serializer used for send data on the network in most cases was the same of the one used for write on the disc, since 2.2 this two concept start to be detached, so we can support on binary protocol the fetchplan in record and partial data send/update, probably the first implementation of this will land on 3.0 or 3.1

**Comment by andreyvk** [comment]
@tglman I see, thanks for the update!

**Comment by tglman** [comment]
Hi,

In 3.0 we designed a new network query API and relative SQL that support in a better way nesting, making the fetch-plan in the query obsolete, and at the same time everything is simpler and safer, going to close this as fixed.

Regards
