### ISSUE TITLE
Error while using operator BETWEEN with parentheses

### ISSUE THREAD

**Issue by habi4ek** [orientechnologies/orientdb#5607]
Hi, I use orient server 2.1.9

**insert into v1 content {"q":1,"qq":2,"qqq":6}**
Inserted record 'v1#11:3{q:1,qq:2,qqq:6} v1' in 0,001000 sec(s).

**insert into v1 content {"q":1,"qq":2,"qqq":6}**
Inserted record 'v1#11:3{q:1,qq:2,qqq:6} v1' in 0,001000 sec(s).

**insert into v1 content {"q":1,"qq":2,"qqq":6}**
Inserted record 'v1#11:3{q:1,qq:2,qqq:6} v1' in 0,001000 sec(s).

**select from v1 where qq between 1 AND 5**

----+-----+------+----+----+----
|@RID |@CLASS@RID|qq |q |qqq
----+-----+------+----+----+----
0 |#11:2|v1 |2 |1 |6
1 |#11:3|v1 |2 |1 |6
2 |#11:4|v1 |2 |1 |6
----+-----+------+----+----+----

**select from v1 where (q = 1 AND qqq = 6) AND qq between 1 AND 5**
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from v1 where (q = 1 AND qqq = 6) AND qq between 1 AND 5

**Lifehack**
this query will work if I insert the operator "BETWEEN" between parentheses

**select from v1 where (q = 1 AND qqq = 6) AND ( qq between 1 AND 5)**
----+-----+------+----+----+----
|@RID |@CLASS@RID|q |qq |qqq
----+-----+------+----+----+----
0 |#11:2|v1 |2 |1 |6
1 |#11:3|v1 |2 |1 |6
2 |#11:4|v1 |2 |1 |6
----+-----+------+----+----+----

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

Sorry, I cannot get the point, could you please add some details, like the error message and the stack traces? Does it happen on the INSERT operation?

Thanks

Luigi

**Comment by Ivanov-Yuriy** [comment]
Hi @luigidellaquila 
May be it was bug *github.com*

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

yes, thanks, now I have all the details.
It seems to be a problem in the low (legacy) part of the query parsing, I'll take a look at that ASAP

Thanks

Luigi
