### ISSUE TITLE
Selecting all vertices connected by and edge  to another specific list of vertices

### ISSUE THREAD

**Issue by shyamchandranmec** [orientechnologies/orientdb#5608]
select expand( in('BELONGS_TO') ) from
(select expand(out('follows'))  from User where @rid = #13:0 )

This query returns posts from all pages followed by a user
User ->(follows)->Page
Post->(belongs_to)Page

each post falls-into a category as well

I need to filter the same output based on multiple categories.
something like this

select expand( in('BELONGS_TO') AND OUT("FALLS_INTO") in ["#32:0","#32:1] ) from
(select expand(out('follows'))  from User where @rid = #13:0 )

**Comment by luigidellaquila** [comment]
Hi @shyamchandranmec 

just to understand, is the OUT_FALLS_INTO an attribute of the Page? 

Thanks

Luigi

**Comment by shyamchandranmec** [comment]
@luigidellaquila  nope.. "FALLS_INTO"  is an edge pointing out from the Post to the Category class. 32:0 and 32:1 are the id's of 2 Category vertices

**Comment by shyamchandranmec** [comment]
@luigidellaquila  I have edited the comment and changed  it to  out("falls_into")

**Comment by luigidellaquila** [comment]
Hi @shyamchandranmec 

I think the right query should be something like:

```

select expand(out('BELONGS_TO')) 
from (
    select expand(out('follows')) from User where @rid = #13:0 
) WHERE
OUT("FALLS_INTO") in [#32:0, #32:1] 
```

Thanks

Luigi

**Comment by shyamchandranmec** [comment]
@luigidellaquila 

Thanks ... I will try it out

**Comment by shyamchandranmec** [comment]
@luigidellaquila 
I tried this. This is giving zero results... Then I tried it with 'NOT IN'  [#32:0] instead of 'IN', then it was displaying the item which had an 'OUT' relationship to #32:0..

Any idea why its acting weird..

**Comment by luigidellaquila** [comment]
Hi @shyamchandranmec 

I don't know, just consider that I changed `in('BELONGS_TO')` into `out('BELONGS_TO')` because it makes sense based on your domain...

If you can share a simple dataset I'll try it and I'll try to give you some more info

Thanks

Luigi

**Comment by shyamchandranmec** [comment]
@luigidellaquila  I changed the   out('BELONGS_TO') to in('BELONGS_TO')..

How should I give the dataset? Should I give you the db dump?

**Comment by luigidellaquila** [comment]
Hi @shyamchandranmec 

yes, a db dump would be perfect

Thanks

Luigi

**Comment by shyamchandranmec** [comment]
Hi @luigidellaquila 
I have attached the file.
[dump.gz](https://github.com/orientechnologies/orientdb/files/99467/dump.gz)

**Comment by luigidellaquila** [comment]
Hi @shyamchandranmec 

I think the query you are looking for is the following:

```
select from (
    select expand(out('follows').in('BELONGS_TO')) from User where @rid = #13:0 
) WHERE OUT("FALLS_INTO") in [#24:1, #32:1] 
```
(probably you have different cluster IDs, because of the import/export)

Thanks

Luigi

**Comment by shyamchandranmec** [comment]
Hi @luigidellaquila 

This works. Thanks... I confused the edge id and the vertex id shown in the orientdb studio.  Now it works but I have a one more question.. Its returning 3 rows with same data... There are duplicate rows in the result.. Any idea why?

**Comment by luigidellaquila** [comment]
Hi @shyamchandranmec 

probably you have multiple paths between the user and the post. You can change your query this way to avoid duplicates:

```
select from (
    select expand(out('follows').in('BELONGS_TO').asSet()) from User where @rid = #13:0 
) WHERE OUT("FALLS_INTO") in [#24:1, #32:1]
```

I'm closing this issue, please reopen in case you have any other problems.

Thanks

Luigi

**Comment by shyamchandranmec** [comment]
@luigidellaquila 

Thanks for the help
