### ISSUE TITLE
Read performance, especially for aggregations are very slow.

### ISSUE THREAD

**Issue by dmikov** [orientechnologies/orientdb#5609]
The setup is as follows. 32GB of memory, SSD Disk and 10M records. Of very average length 8 fields.
The Orient runs with default parameters. WHich might be the issue 
`OrientDB auto-config DISKCACHE=30,138MB (heap=491MB os=32,677MB disk=311,169MB) [orientechnologies]`

The following query `select state, count(*) from Record_11_2 group by state` where state is even indexed runs 65 seconds.

```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 10000000,
            "current": "#16:9999999",
            "documentAnalyzedCompatibleClass": 10000000,
            "recordReads": 10000000,
            "projectionElapsed": 634,
            "fetchingFromTargetElapsed": 61351,
            "evaluated": 10000000,
            "groupByElapsed": 0,
            "elapsed": 61352.266,
            "resultType": "collection",
            "resultSize": 50,
            "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,projectionElapsed=l,fetchingFromTargetElapsed=l,evaluated=l,groupByElapsed=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 61.359 sec. Returned 1 record(s)"
}
```

By comparison the same query (actually with avg so as to avoid index counter, with count on indexed field it's less then half a second) with the same number of records in MS SQL runs 5 second from disk and 800ms when warm. That's a big difference. 
Also the same query on neo4j default settings takes 15 seconds, also unfortunately no index usage, but read/scan is much faster.
Is it related to OrientDB setup or is it something related to read and no caching performance? 
BTW the OrientDB consumes 3.4 GB which is exactly the size of data for that class, so why is it so slow?

**Comment by lvca** [comment]
@dmikov we improved this in v2.2.0-SNAPSHOT. Could you please try v2.2.0-SNAPSHOT with the very same use case?

**Comment by dmikov** [comment]
I will gladly try. Is database need to be reloaded? or just binary update?

**Comment by dmikov** [comment]
I downloaded and upgraded binaries. I did not reload data or create new database. The result is identical 59 seconds for the above query.

**Comment by lvca** [comment]
Is there any way we can get your database to run your query? Could you send to support -at- orientdb.com?
