### ISSUE TITLE
Question regarding document deletion and browseClass

### ISSUE THREAD

**Issue by bokyoungbin** [orientechnologies/orientdb#5612]
Hi!
I have a question regarding browseClass and deletions in Orient document database.
browseClass seems to find the document even after I have deleted it.

So if I have 

```
ODatabaseDocumentTx db;
for (ODocument doc : db.browseClass("Person")){
..
}
```

will throw me an Illegal Argument exception, which is ok.
However, when I save the document like the following

```
final ODocument document = new ODocument("Person");
                document.field("state", value); 
                document.save();
```

and delete like the following:

```
for (ODocument doc : db.browseClass("Person")){
       db.delete(doc);
}
```

and then browseClass the same thing again, which should give me an IllegalArgument exception just like the above,

```
for (ODocument doc : db.browseClass("Person")){
..
}
```

instead of throwing me the exception, it simply does not go into the for loop. 

My guesses are as follows:
1. browseClass is not the proper way of getting the document from the db, or I am using it wrong.
(I expected something like db.get("Person"), which there were none.)
2. Even after deletion, the fact that "Person" was previously saved, remains in the database somewhere, and browseClass does not throw an exception, it merely goes past the for loop.

I want my deletion to delete "person" properly so I do not have extra data that fills up space.
How do I perform this kind of deletion?

Thanks in advance!

**Comment by luigidellaquila** [comment]
Hi @bokyoungbin 

could you please post your code? My guess is that you are having problems because of how you are using transactions...

Thanks

Luigi

**Comment by bokyoungbin** [comment]
@Override
    public <I> boolean set(final Identifier identifier, final I value){
       try {
           for (ODocument doc: db.browseClass(identifier.toString())){
                if (doc.containsField("state")){
                    doc.field("state", value);
                    doc.save();
                    return true;
                }
            }
           final ODocument document = new ODocument(identifier.toString());
           document.field("state", value);
           document.save();
           return true;
        } catch (Exception e) {
            try{
                final ODocument document = new ODocument(identifier.toString());
                document.field("state", value);
                document.save(); 
                return true;
            } catch (Exception f){
                f.printStackTrace();
                return false;
            }
        }
    };

    @Override
    public <I> I get(final Identifier identifier){
        try{
            for (ODocument doc : db.browseClass(identifier.toString())){
                if (doc!=null){
                    return doc.field("state");
                } else{
                    return null;
                }
            }
            return null;

        } catch (Exception e){
            e.printStackTrace();
            return null;
        }
    };

    @Override
    public boolean delete(final Identifier identifier){
        try{
            for (ODocument doc : db.browseClass(identifier.toString())) {
                db.delete(doc);
                return true;
            }
            return false;

        } catch (Exception e){
            return false;
        }
    };

These are my get, set, delete codes.

Then I just use them like this:
orientdb.set(id1, value)
orientdb.get(id1)
orientdb.delete(id1)

**Comment by bokyoungbin** [comment]
@luigidellaquila Hi! I still can't seem to fix this issue. Is there something wrong with how I've used orientdb?
