### ISSUE TITLE
error in console for seeing a binary document

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5613]
version:last version
<pre>
select   from #3:229                 

0 item(s) found. Query executed in 0.0 sec(s).
</pre>

there are 2 errors:
 1)  0 items is wrong, because using java code the item exists
2)  impossible to see data or at least size of binary data

**Comment by publicocean0** [comment]
second attempt using console 
<pre>
orientdb {db=streamer}> begin

Transaction 4 is running
orientdb {db=streamer tx=[0 entries]}> delete from #3:229

Delete record(s) '0' in 0,002000 sec(s).

orientdb {db=streamer tx=[0 entries]}> delete from 33:133

Delete record(s) '1' in 0,003000 sec(s).

orientdb {db=streamer tx=[0 entries]}> commit

</pre>
second error Delete record(s) '0' in 0,002000 sec(s).

**Comment by publicocean0** [comment]
i m making a lot of test .... because begin , commit in java give a block of thread

**Comment by publicocean0** [comment]
test 1 : 
<pre>
js var a=db.command('select content,@rid from #33:137'); a[0].field('content'); end;
[Started multi-line command. Type just 'end' to finish and execute]

Client side script executed in 0,123000 sec(s). Value returned is: #3:233[0, 5, 100, 100, 100, 100, 100] v1
</pre>

**Comment by publicocean0** [comment]
<pre> js var a=db.command('select content,@rid from #33:137'); a[0]; end;
[Started multi-line command. Type just 'end' to finish and execute]

Client side script executed in 0,006000 sec(s). Value returned is: #-2:0{content:#3:233,rid:#33:137} v0
</pre>

**Comment by publicocean0** [comment]
<pre>
js var a=db.command('select from #3:137'); a.length; end;
[Started multi-line command. Type just 'end' to finish and execute]

Client side script executed in 0,011000 sec(s). Value returned is: 0


select from #3:137


0 item(s) found. Query executed in 0.002 sec(s).

</pre>

**Comment by publicocean0** [comment]
Considering that the tests confirms data exists , and in my java code there is just a simple transaction for deleting binary node and parent node , i will post another graver error 

the transaction is blocked in this case

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

could the problem be related to a front-end issue? Maybe the result is just not correctly displayed. What does the record contain?


Thanks

Luigi

**Comment by publicocean0** [comment]
no, above i showed the console result. The problem are with ORecordBytes ... thid kind of records. 
in the test above i proved that document exists : using js (calling directly java) i can see the document. Using console i can't find it.

**Comment by tglman** [comment]
hi,

Added a test case and fixed, in develop.

closing.
