### ISSUE TITLE
Cannot query vertex properties directly using OCommandGremlin.

### ISSUE THREAD

**Issue by peterkhan** [orientechnologies/orientdb#5616]
Im creating this bug for my post http://stackoverflow.com/questions/34890393/how-to-query-vertex-properties-directly-using-ocommandgremlin

I want to query for vertex and edge properties directly using OCommandGremlin.
When I executed the gremlin `g.v(vId).both.dedup.idx` I got NoSuchElementException because the parsed list from the response contains only null values. 
(Please see `Approach 2` mentioned in the stackoverflow post).

Code:

```
public void printConnections2(Long personId) {
Object vertexId = getNode(PERSON, personId).getId();

String oSql = "g.v(vId).both.dedup.idx";

Map<String, Object> params = new HashMap<String, Object>();
params.put("vId", vertexId);

OrientDynaElementIterable result = getGraph()
        .command(new OCommandGremlin(oSql)).execute(params);

Iterator<Object> iterator = result.iterator();

while (iterator.hasNext()) {
    Object obj = iterator.next(); // Exception here.
    System.out.println(obj);
}
```

}
 NoSuchElementException at iterator.next() call.

java.util.NoSuchElementException at com.tinkerpop.blueprints.impls.orient.OrientDynaElementIterator.next(OrientDynaElementIterator.java:57) ... more call trace...

When I debugged the code, I found out that responses with List of java objects are not handled. (I have written a detailed comment to the post with my observations)

Also, if there is only one vertex matching the query, then the result of the query is a Short not a list with one value.

**Comment by vineethpeterjose** [comment]
I am not able to query anything other than Orient Element, List of Orient Element or one object.

for example:
```
g.v(vId).both.dedup.path
g.v(vId).both.dedup.path{it.idx}
<< will add more examples later>>
```

Im stuck at this issue. Do you think the priority of this bug should be changed because only a very few set of gremlins are working with OCommandGremlin.
