### ISSUE TITLE
Java: implementing both graph and document APIs

### ISSUE THREAD

**Issue by ciroppina** [orientechnologies/orientdb#5617]
dear Sirs,

I wanna know how to (if possible) create Java classes which have both the behaviour of:
- Orient Document (transactions, queries, crud, traverse)
- Orient Graph (properties, fields, vertices, edges, links)

Could You kindly redirect me to the correct issue/discussion or code-examples?

best regs

**Comment by lvca** [comment]
This is more a question than an issue. Please post it on StackOverflow by using the “orientdb” tag:

http://stackoverflow.com/search?q=orientdb

Or in the Community Group where more than 3,000 users can answer to your question:

https://groups.google.com/forum/#!forum/orient-database

Thanks.
