### ISSUE TITLE
Query Pagination with Limit on Studio

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5618]
Hi,
perhaps this is repeated, what I would like to know is how I can change the default number of items displayed on the table of STUDIO-Browse. I know that I have to set the LIMIT first on pagination. But every time I execute a query 10 items are displayed only. Then I have to press again on 25, 50, 100, 1000... to browse the table with more items.

**Comment by maggiolo00** [comment]
hi @healiseu 

the default number of displayed items is 10.
you cannot change it permanently 
I will mark this as enhancement

**Comment by healiseu** [comment]
It would be great as it is causing a major hassle to repeat this all the time

**Comment by seeden** [comment]
+1

**Comment by pradeepg-telsiz** [comment]
+1
