### ISSUE TITLE
slow performance while importing the records into V schema in replication mode

### ISSUE THREAD

**Issue by sumedh1919** [orientechnologies/orientdb#5619]
@lvca ,

I've tried to restore/import the OrientDB (with V schema containing 1791 records) into the primary server of Replication setup keeping the secondary orientDB server in UP state and noticed that its consuming almost 2+ hours to update all those records in both primary and secondary servers (Here './dserver.sh' was been used to restart the OrientDB after restore/import operation).

However, I performed the same DB import into a non-replicated server and noticed that the records got imported in few minutes ~4-5minutes ( './server.sh' was been used to restart the OrientDB after restore/import operation).

OrientDB version: v1.7.6

**Comment by maggiolo00** [comment]
hi @sumedh1919 

have you tried with the latest stable 2.1.9?

**Comment by sumedh1919** [comment]
Hi @maggiolo00 
nope, I didn't try with that version.
Are there any known issues in 1.7.6 w.r.t import performance in replication mode?

**Comment by sumedh1919** [comment]
Sorry.. wasn't much clear with the process of replication in orientDB as result this case was seen.
In the primary server, we were shutting down the orientDb and importing the data then restarting it (without touching the OrientDB server state in the Secondary). 

Below step helped in overcoming the issue
1) shutdown the orientDB servers in both the servers(Pri and Sec) 
2) import data in primary 
3) restart servers in primary and then secondary
