### ISSUE TITLE
NullPointerException on DELETE EDGE

### ISSUE THREAD

**Issue by rajeshvaya** [orientechnologies/orientdb#5620]
## Description: 
Cannot delete records of an EDGE when the vertex referring to 'out' is deleted.

## Version
Community 2.1.0

## Steps: 
- Create a vertex record
- Create an edge from vertex class to edge class
- Delete the vertex record
- Try Deleting all records from edge class (`DELETE EDGE myEdgeClassName`)
(it will give the NullPointerException)

**Comment by maggiolo00** [comment]
hi @rajeshvaya 

Which version of  OrientDB?

what do  you mean when you say

Create an edge from vertex class to edge class?

**Comment by maggiolo00** [comment]
Can you provide SQL script

to reproduce it?

**Comment by rajeshvaya** [comment]
Hi @maggiolo00, the version is `community 2.1.0`. I am not able to reproduce the scenario again, not sure why. I will close the issue and open again once I have the reproduce script

Thanks and sorry for wasting your time.
