### ISSUE TITLE
bug in OSQL: select ... where s > 0

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5623]
Using console.sh of OrientDB 2.1, the first query below produces the expected result, but the second (using WHERE s > 0) does not:

```
> select @this, in(), in().size() as s from v

----+------+-----+----+----
#   |@CLASS|this |in  |s   
----+------+-----+----+----
0   |null  |#11:0|[0] |0   
1   |null  |#11:1|[1] |1   
2   |null  |#11:2|[1] |1   
3   |null  |#11:3|[1] |1   
4   |null  |#11:4|[1] |1   
5   |null  |#11:5|[1] |1   
6   |null  |#11:6|[1] |1   
----+------+-----+----+----
```

```
> select @this, in(), in().size() as s from v where s > 0
0 item(s) found. Query executed in 0.009 sec(s).
>
```

That is, no results are produced whereas it seems clear that the answer set should have six rows.

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

in current executor implementation, aliases are calculated after the WHERE condition, this is why it doesn't work. 
In current release you have to use a LET to do it
```
select @this, in(),  $s from v let $s = in().size() where $s > 0
```

We are working to address this issue in next releases, I'll mark it as an enhancement.

Thanks

Luigi

**Comment by pkoppstein** [comment]
@luigidellaquila - Thanks for the explanation and help.  I don't see the enhancement on the roadmap, but maybe that's because I'm not looking hard enough 8-)  

Meanwhile, please feel free to change the "Bug" to "ER" in the title of this issue.

**Comment by luigidellaquila** [comment]
Hi @pkoppstein 

It's not explicitly in the executor, but it will be part of "Distributed SQL Executor" ;-)

Thanks

Luigi

**Comment by healiseu** [comment]
:+1:
