### ISSUE TITLE
Graph Canvas Save Configuration

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5624]
Hi,
I am playing with your graph canvas, it seems there is a problem when I save the configuration. The configurable settings are lost when you switch to Browse mode and back again to Graph. Plus that you have to recreate the graph because it is erased.

One solution I found is to open another Web Browser tab (is that a new connection on the database?) but I am not sure  how updates are refreshed from one tab to the other. For example, I created an Edge class in one tab but I could not find it on the Graph Canvas that I was working on the other tab.

It would be great if configuration is saved permanently on the disk and loaded when the user is working with the Graph canvas on the specific database.

**Comment by maggiolo00** [comment]
hi @healiseu 

did you log with root?

**Comment by healiseu** [comment]
That is correct !

**Comment by maggiolo00** [comment]
@healiseu 

try to use admin user

**Comment by healiseu** [comment]
Yes it works for admin !
By the way I think you should change the default login name to admin instead of root

**Comment by healiseu** [comment]
But the graph is erased if you switch to Browse Mode !

**Comment by smolinari** [comment]
I can confirm the prior viewed graph is lost, when switching from graph canvas to other parts of Studio and back again. Would be nice, if it could stay the same rendered, until the next query is made to the graph viewer.

Scott

**Comment by maggiolo00** [comment]
@healiseu  @smolinari 
i will try to implement this for 2.2.2.
