### ISSUE TITLE
Result set of vertices with an empty collection of edges, vertices

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5625]
Hi,
this might be a simple question but I am confused, please help.....

I am using OrientDB 2.1.9 and I am experimenting with VehicleHistoryGraph database.
From Studio, Browse mode, set limit to 9 records only. Now I am entering this simple query

`select out() from Person`

The result set I am getting back is 9 records BUT only two have Bought a vehicle. The rest are displayed with empty collections []. This is no good, I am confused. I would expect to get back only those two vertices with collections of edges !

How do I get back these two persons that bought something  ?
I noticed also that there is this unwind operator in select. Is this useful in that case, can you make an example ?

**Comment by lvca** [comment]
This is more a question than an issue. Please post it on StackOverflow by using the “orientdb” tag:

http://stackoverflow.com/search?q=orientdb

Or in the Community Group where more than 3,000 users can answer to your question:

https://groups.google.com/forum/#!forum/orient-database

Thanks.

**Comment by healiseu** [comment]
o.k. @lvca it is done....
