### ISSUE TITLE
error in lucene query (NumberFormatException)

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5626]
<pre>
select expand(rid) from index:A.lucene1 where key LUCENE '(a:"ROME" and parent:"#38:9") and index:3'       

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select expand(rid) from index:A.lucene1 where key LUCENE 

Error: java.lang.NumberFormatException: For input string: "(a:"ROME" and parent:"#38:9") and index:3"

</pre>
same error if i replace 3 with [3 TO 3]

It seams the error is created when you create index with a numeric field

**Comment by robfrank** [comment]
may you send the schema and some sample data? and, of course, orientDb version.

**Comment by publicocean0** [comment]
version :last  , orientdb-community-2.1.9
document{index:LONG,name:STRING}
INDEX on name,index
A{index:5l,name:'prova'}
A{index:6l,name:'prova2'}

**Comment by robfrank** [comment]
Sorry, but what kind of index do you define? 
Do you define a Lucene full text index? 
Have you got a Osql script that creates the schema you are using? Or maybe a chunk of code. 
It's very hard to understand what you are doing.

**Comment by publicocean0** [comment]
create index A.lucene on A (index,name) FULLTEXT ENGINE LUCENE

**Comment by publicocean0** [comment]
I m not sure but i think there is not bug here. I think it as because a Long field was null.
