### ISSUE TITLE
How to increase maximum concurrent connections

### ISSUE THREAD

**Issue by thejjmiller** [orientechnologies/orientdb#5627]
Where do you configuration the maximum number of concurrent connections? This is probably only an issue in our Development environment where we have lots of developers that all run their own clients and each client has multiple connection pools of 10 connections. 

Also do you have any direction as to what kind of hardware requirements are required for more than 1000 connections?

Also is there any plan to clean up "Idle Connections", connections that were not explicitly closed by the client?

**Comment by tglman** [comment]
hi @thejjmiller 

you can set the maximum number for connection with this property: https://orientdb.com/docs/last/Configuration.html#network-maxconcurrentsessions

the cleaning of connection is already there and it happen every 5 seconds(can be set here:https://orientdb.com/docs/last/Configuration.html#server-channel-cleandelay), but we keep anyway the connection alive till the client is alive.

For the number of connection there is not are real hardware requirement, it matter much more the workload, but anyway you can count that you need at least 1MB of ram for each connection active.

Regards

**Comment by maggiolo00** [comment]
@thejjmiller 

does @tglman answer to your questions?

**Comment by thejjmiller** [comment]
Yes that was perfect thank you.
