### ISSUE TITLE
Declared Class on Property

### ISSUE THREAD

**Issue by thejjmiller** [orientechnologies/orientdb#5628]
It would be nice to be able to know which class a property is declared on. For instance when looking at a class in the Studio you can see the list of properties. This includes property from base classes however there is no way to know which properties came from base classes and which ones came from the current class. This is very useful when you have the same property names declared on multiple base classes.

**Comment by maggiolo00** [comment]
Hi @thejjmiller 
we have an old issue about that.
https://github.com/orientechnologies/orientdb-studio/issues/22
