### ISSUE TITLE
Illegal class names

### ISSUE THREAD

**Issue by sinfex** [orientechnologies/orientdb#5629]
From documentation on [CREATE CLASS](http://orientdb.com/docs/2.1/SQL-Create-Class.html):

> \<class> Defines the name of the class you want to create. **You must use a letter for the first character**, for all other characters you can use alphanumeric characters, underscores and dashes.

```
orientdb {db=test}> CREATE CLASS $
Class created successfully.

orientdb {db=test}> CREATE CLASS _
Class created successfully.
```

OrientDB version: 2.1.9-SNAPSHOT

**Comment by luigidellaquila** [comment]
Hi @sinfex 

`$` and `_` are considered valid characters for an identifier, so it's not a bug.
I'm updating the docs right now.

Thanks for reporting

Luigi

**Comment by sinfex** [comment]
@luigidellaquila out of curiosity, is it also fine if the class name starts with `$`?

**Comment by lvca** [comment]
No, $ is the prefix of variables.

**Comment by sinfex** [comment]
@lvca then how come `$` is a legal class name as demonstrated in the initial issue post and pointed out by @luigidellaquila?

**Comment by luigidellaquila** [comment]
Hi guys,

actually $ is a valid character for identifiers (and you can define variables in LET without $ if you want). 

Let's talk about this, I can change it in 2.2

Thanks

Luigi
