### ISSUE TITLE
Rest API returning always 401 even with good credentials

### ISSUE THREAD

**Issue by sebastiandev** [orientechnologies/orientdb#5630]
Docs specify this behaviour but it's certainly not right. 

When connecting to a database, for example if you get a 401 you dont know if its because of bad credentials or because the database doesnt exists. Therefore in the code one has to assume that the database may not exist and try to create it. But, if that wasnt the case, then we get the error:

> Database 'plocal:/opt/orientdb-community-2.1.5/databases/xxx' already exists.

Also, when requesting info of an unexisting database, I get 401 again.

> GET http://127.0.0.1:2480/database/somename
> 
> ``` javascript
> {
>   "errors": [{
>       "code": 401,
>       "reason": "Unauthorized",
>       "content": "401 Unauthorized."
>       }
>   ]
> }
> ```

I would go for descriptive errors, and make sure all response errors are json objects with the same format as the one above.

**Comment by ssslinppp** [comment]
how do you solve it ?

**Comment by maggiolo00** [comment]
Hi @ssslinppp 

did you try with the last stable 2.2.29 if you are getting this behaviour?

Thanks
