### ISSUE TITLE
Server throws OOM and crashes on heavy load

### ISSUE THREAD

**Issue by Ashendra** [orientechnologies/orientdb#5633]
I'm running orientdb standalone server on a machine with 64gb ram and 4g swap space. Database has more than 300 millions edges and around 70 million vertices.
I'm running the server with following jvm options
-XX:+UseG1GC -Xmx8g -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError  
-Dstorage.diskCache.bufferSize=30480
-Denvironment.dumpCfgAtStartup=true -Dindex.embeddedToSbtreeBonsaiThreshold=-1 
-Dnetwork.maxConcurrentSessions=10000

I am connecting remotely to the server using java apis. For creating connections using the OrientGraphFactory with min and max pool size as 100 and 200.
Each client performs insert/read/delete at around 10k qps(all combined). I have multiple such clients connecting to the server. 

When qps is over 50k, the orientdb server crashes with Out of Memory(OOM) exception. Sample error

There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 12288 bytes for committing reserved memory.

Though there is enough ram available during the time of crash.
Memory: 4k page, physical 66064704k(262280k free), swap 4194300k(4162808k free)

Please suggest how to fix this problem.

Attaching the heap dump files created after each crash. 

[hs_err_pid597.txt](https://github.com/orientechnologies/orientdb/files/102371/hs_err_pid597.txt)
[hs_err_pid31001.txt](https://github.com/orientechnologies/orientdb/files/102372/hs_err_pid31001.txt)
[hs_err_pid47978.txt](https://github.com/orientechnologies/orientdb/files/102373/hs_err_pid47978.txt)

**Comment by lvca** [comment]
Which version? Please always report the version.

**Comment by Ashendra** [comment]
Version 2.1.5.

**Comment by laa** [comment]
Hi
It is OS issue, could you try this one
http://www.theshell.guru/native-memory-allocation-mmap-failed-to-map-xx-bytes-for-committing-reserved-memory-jdk-1-8-centos-6-7/


On Mon, Jan 25, 2016 at 7:05 AM Ashendra <notifications@github.com> wrote:

> Version 2.1.5.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5633#issuecomment-174400743>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by machak** [comment]
his system is OS:PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"

uname:Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u4 x86_64
libc:glibc 2.13 NPTL 2.13 
rlimit: STACK 64000k, CORE 0k, NPROC 516030, NOFILE 500000, AS infinity
load average:8.75 8.18 5.08

**Comment by Ashendra** [comment]
This is not the issue I'm facing.  I posted wrong error dump. I have observed I am facing this issue, when I have -Dstorage.diskCache.bufferSize set to more than 16gb.

This was heap size of 8gb and concurrent sessions set to 3k. Also the 1mb used for each concurrent sessions is account from heap or non-heap memory?

Attaching the correct error dump. 
[hs_err_pid37074.txt](https://github.com/orientechnologies/orientdb/files/103733/hs_err_pid37074.txt)

**Comment by laa** [comment]
@Ashendra it is strange question, but which JVM do you have, it seems like you are using 32-bit JVM.

**Comment by Ashendra** [comment]
Using 64 bit JVM.

**Comment by dafixa** [comment]
Same issue here. This must be the fifth different OOM problem in orientdb I've had an am soon to give up on JVM based databases.

**Comment by Ashendra** [comment]
Well workaround in my case, was to add swap space, which deterioted the performance, but crash is being delayed.

**Comment by laa** [comment]
Hi ,
It means that your report that you have enough RAM is controversial.
Could you send how much memory is consumed by process before crash and what
server settings do you have .

вс, 14 февр. 2016, 16:13, Ashendra <notifications@github.com>:

> Well workaround in my case, was to add swap space, which deterioted the
> performance, but crash is being delayed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5633#issuecomment-183895823>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by laa** [comment]
@dafixa we have strategy which we are going to implement soon to fix OOM problem once and forever   https://github.com/orientechnologies/orientdb/issues/5720

**Comment by laa** [comment]
Closed because of no reply. Please free to reopen issue if you have information which I asked.
