### ISSUE TITLE
Select record with vertices connected by its edges.

### ISSUE THREAD

**Issue by shyamchandranmec** [orientechnologies/orientdb#5634]
I am trying to select a record of Comment class with other 2 vertices connected by 2 of its edges HAS_COMMENT and WROTE_COMMENT. I need these 2 vertices as a nested json in the Comment.

I tried this query. But this gives only the id of the record.

    select *, in('WROTE_COMMENT') AS author, in('HAS_COMMENT') AS post  from Comment
    
I need the expanded record details instead of their id.

Something like this.(But the below query doesn't work) But these 2 records should be a part of the record as a sub json. 

    select *, expand(in('WROTE_COMMENT')) AS author, expand(in('HAS_COMMENT')) AS post  from Comment

**Comment by smolinari** [comment]
Not sure this will help, but if you identify the fields, I believe you can get what you are looking for.

Something like:

`select *, in('WROTE_COMMENT').name AS author, in('HAS_COMMENT').title AS page  from Comment`

I am just guessing at the field names of course.

Also, the ODB team now wants only bugs or suggestions as issues here. So, in the future, please try to use the forum for such questions. https://groups.google.com/forum/#!forum/orient-database

Here is the news on moving questions to the forum (or Stackexchange). 

https://groups.google.com/forum/#!topic/orient-database/-1_gMci4hwo

Scott

**Comment by shyamchandranmec** [comment]
@smolinari  
Thanks for the quick response.   I will try it out.
Stack Exchange no one is answering thats why I ended up posting here. 
I will post my future questions in the google groups.

**Comment by shyamchandranmec** [comment]
@smolinari 
I am closing this issue. I will try what you suggested. If I face any problem I will ask the question in SO
