### ISSUE TITLE
API for creating indexes is broken

### ISSUE THREAD

**Issue by bodiam** [orientechnologies/orientdb#5635]
Hi all,

I'm trying to use the `createIndex` method on OClass, but the API design seems to be broken.

To start, there are 5 createIndex methods. However, two of them use enum INDEX_TYPE as the type of Index. That's fine. The other 3 are using a String.... ehh? INDEX_TYPE.toString() or something? This seems inconsistent.

The second thing, however, and that's much more, is that there's a method with varargs.

```
  OIndex<?> createIndex(String iName, String iType, OProgressListener iProgressListener, ODocument metadata, String algorithm,
      String... fields);

OIndex<?> createIndex(String iName, String iType, OProgressListener iProgressListener, ODocument metadata, String... fields);
```

If I now want to call the second method, how do I do that???

I'm trying the following:

```
asin.createIndex("processedIdx", OClass.INDEX_TYPE.NOTUNIQUE.toString(), null, metaData, "dateProcessed");
```

but that's not calling the second method, it's calling the first. Which then gives me an error:

`com.orientechnologies.orient.core.index.OIndexException: List of fields to index cannot be empty.`

But I specified the field. It's just calling the other method. So, the method signatures are wrong. They should be:

```
  OIndex<?> createIndex(String iName, String iType, OProgressListener iProgressListener, ODocument metadata, String algorithm,
      String field, String... fields);

OIndex<?> createIndex(String iName, String iType, OProgressListener iProgressListener, ODocument metadata, String field, String... fields);
```

And in the implementation, you should contact the field and the fields together. This way, there's always a minimum of one field.

**Comment by tglman** [comment]
Hi @bodiam,

you can call the correct api using:
```
asin.createIndex("processedIdx", OClass.INDEX_TYPE.NOTUNIQUE.toString(),null, metaData,new String[]{ "dateProcessed"});
```
we may force this way in future,

**Comment by bodiam** [comment]
Hi @tglman , I understand the workaround, but the API is just hard to use, and inconsistent, and improving it wouldn't break things, I guess. Also, my other point about the type vs String is still relevant, which also makes the API more inconsistent.
