### ISSUE TITLE
hotalignment issue

### ISSUE THREAD

**Issue by udishemer** [orientechnologies/orientdb#5636]
I think I have an issue with hotAlignment=true. I tried this on the 2.2 snapshot (alpha) version and it exists on 2.1.9 as well.
In general hotAlignment seems to work for me and when a node goes down and up again the data is synced as expected.

The problem scenario is:
Two nodes AAA and BBB. Node BBB goes down. I continue working on AAA and modify an object. Now AAA goes down.
The issue is that when the nodes come up they will never sync. The change does appear in AAA but not in BBB. This is not a conflict scenario as no change occurred in BBB.

I tried this with 3 nodes and got a similar issue.

**Comment by luigidellaquila** [comment]
Hi @udishemer 

I think this issue is not relevant anymore, as `hotAlignment` option was deprecated long time ago. Moreover, latest v 2.2.30 is far more stable than the 2.2 alpha, most of the problems were addressed in the hotfixes

Thanks

Luigi
