### ISSUE TITLE
(Core) Asynchronous write mode

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5638]
Today every insert/update/delete operation acts on 2 layers:
1. WAL (Journal)
1. Update Page in DISKCACHE

We could make operation (2) asynchronous and provide the ACK to the client right after (1). In case of crash, the WAL (1) will guarantee the db consistency.

The only problem is that further reads couldn't see changes, because they don't consider the WAL. So we could solve this problem by coupling the client's session to the last WAL LSN. In case of query, it will be waited until the LSN number has been flushed on disk.

Any feedback is welcome.

**Comment by laa** [comment]
Well Luca,
That  is first idea which we discussed.
real speed up is doubtful .

Because to read all Wal records which is applied to the page we have to go
through ALL Wal.  Which is obviously slow.
But this solution is already used by several distributions of databases.
They create index of Wal records  for each page.  But even with such index
implementation is long and final result  I mean how much slow down we have
on reads is doubtful .  That is why it is still not implemted.

I mean  all reads will not see final changes,  all which are run in
parallel threads.

On Mon, Jan 25, 2016, 16:48 Luca Garulli <notifications@github.com> wrote:

> Today every insert/update/delete operation acts on 2 layers:
> 1. WAL (Journal)
> 1. Update Page in DISKCACHE
>
> We could make operation (2) asynchronous and provide the ACK to the client
> right after (1). In case of crash, the WAL (1) will guarantee the db
> consistency.
>
> The only problem is that further reads couldn't see changes, because they
> don't consider the WAL. So we could solve this problem by coupling the
> client's session to the last WAL LSN. In case of query, it will be waited
> until the LSN number has been flushed on disk.
>
> Any feedback is welcome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5638>.
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by laa** [comment]
One more observation.
Last step,  applying of Wal changes to the pages is the most lightweight .
From all operations.  So we will see sped up but not dramatic,  also if
parallel  thread will not see commited changes that is real limitation for
parallel processing and I do not support half backed solutions.

On Mon, Jan 25, 2016, 17:42 Andrey Lomakin <lomakin.andrey@gmail.com> wrote:

> Well Luca,
> That  is first idea which we discussed.
> real speed up is doubtful .
>
> Because to read all Wal records which is applied to the page we have to go
> through ALL Wal.  Which is obviously slow.
> But this solution is already used by several distributions of databases.
> They create index of Wal records  for each page.  But even with such index
> implementation is long and final result  I mean how much slow down we have
> on reads is doubtful .  That is why it is still not implemted.
>
> I mean  all reads will not see final changes,  all which are run in
> parallel threads.
>
> On Mon, Jan 25, 2016, 16:48 Luca Garulli <notifications@github.com> wrote:
>
>> Today every insert/update/delete operation acts on 2 layers:
>> 1. WAL (Journal)
>> 1. Update Page in DISKCACHE
>>
>> We could make operation (2) asynchronous and provide the ACK to the
>> client right after (1). In case of crash, the WAL (1) will guarantee the db
>> consistency.
>>
>> The only problem is that further reads couldn't see changes, because they
>> don't consider the WAL. So we could solve this problem by coupling the
>> client's session to the last WAL LSN. In case of query, it will be waited
>> until the LSN number has been flushed on disk.
>>
>> Any feedback is welcome.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/orientechnologies/orientdb/issues/5638>.
>>
> --
> Best regards,
> Andrey Lomakin, R&D lead.
> OrientDB Ltd
>
> twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by laa** [comment]
I explain, any changes which are done in current thread will not be seen by any other threads. Even if they expect to see it , as for example in case of parallel load of writes, it merely becomes impossible. 
Also how do you want to integrate it with parallel txs solution ?

**Comment by lvca** [comment]
If you have a queue of operations (using Java Queues or Thread Executor with a queue, it's the same concept), all the writes would be in queue. There is no need to know other parallel writes, unless you need the RID. In that case it could be synchronous (like invoking a `future.get()`, but this is just a speculation on the underlying implementation).

**Comment by laa** [comment]
It is not question of RID that is question of state which you read from page, you may add 2 the same keys for different threads and validation of unique index will pass without problems. 

Also because for both threads page will be empty both threads will write 2 different records to the same page place and will get the same RID.

**Comment by lvca** [comment]
Who writes to the DISKCACHE is one thread only that read from the queue. Or it could be one thread per cluster (with TX would be different). All the operations that need a feedback will remain synchronous, so usage of RID, Unique Indexes, etc.

**Comment by laa** [comment]
Sorry I do not get it, lets suppose we have 2 users both of them create http query to add records in application, how questions of indexing of data (not only unique indexes any indexes, they all use common pages) and clusters will be solved ?
Do we have dedicated cluster for each user ?

Well let suppose that is true, and we have dedicated cluster  for each user (well I doubt it is possible but let suppose) , what about index then, tree will be broken.

What about queries which includes several clusters and write data based on queries results ? I explain what is SLA of writing changes to the disk ? There is no guarantee on it, how do you suppose to support B2B systems in such case ?

**Comment by laa** [comment]
Or you suppose that it will be subtype of operation ?
Well that is not common case, it is OK for me.
