### ISSUE TITLE
creating a java lucene index on multiple fields of document

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5647]
I created a lucene index  using console on different document fields . all ok, also the research. 

Now i done the same thing using java code but give exception "FULLTEXT indexes cannot be used as composite ones"

<pre>
  @Override
  public OIndexInternal<?> create(OIndexDefinition indexDefinition, String clusterIndexName, Set<String> clustersToIndex,
      boolean rebuild, OProgressListener progressListener, OStreamSerializer valueSerializer) {

    if (indexDefinition.getFields().size() > 1) {
      throw new OIndexException(type + " indexes cannot be used as composite ones.");
    }

    return super.create(indexDefinition, clusterIndexName, clustersToIndex, rebuild, progressListener, valueSerializer);
  }
</pre>

**Comment by publicocean0** [comment]
i have a software creating automatically all the indexes annotated ... just moment maybe i have to handle differently this case...

**Comment by publicocean0** [comment]
no same error also passing algorithm lucene.

**Comment by robfrank** [comment]
can you give the java code you are using to create index? It seems you are hitting the FULLTEXT index instead of the LUCENE one.

Documentation (http://orientdb.com/docs/last/Full-Text-Index.html) show java code for a single field
```code
OSchema schema = databaseDocumentTx.getMetadata().getSchema();
OClass oClass = schema.createClass("Foo");
oClass.createProperty("name", OType.STRING);
oClass.createIndex("City.name", "FULLTEXT", null, null, "LUCENE", new String[] { "name"});
```

**Comment by publicocean0** [comment]
yes but  last argument with   new String[] { "name","surname"}.
I tryed to change but now error is  Index with type FULLTEXT and algorithm LUCENE does not exist.

In debug i m in 
<pre>
 public static OIndexFactory getFactory(String indexType, String algorithm) {
    if (algorithm == null)
      algorithm = ODefaultIndexFactory.SBTREE_ALGORITHM;

    final Iterator<OIndexFactory> ite = getAllFactories();

    while (ite.hasNext()) {
      final OIndexFactory factory = ite.next();
      if (factory.getTypes().contains(indexType) && factory.getAlgorithms().contains(algorithm)) {
        return factory;
      }
    }

    throw new OIndexException("Index with type " + indexType + " and algorithm " + algorithm + " does not exist.");
  }
</pre>

The factories are :
[com.orientechnologies.orient.core.index.ODefaultIndexFactory@5e7854dc, com.orientechnologies.orient.core.index.hashindex.local.OHashIndexFactory@74705715]

**Comment by robfrank** [comment]
which version are you using?

**Comment by publicocean0** [comment]
Orientdb libs are 2.1.9

**Comment by publicocean0** [comment]
if you use a field with embedded map , also if you add it in lucene is not researcheble

**Comment by robfrank** [comment]
embedded maps or documents are stil not searchable, we know it. Are you running a standalone server? Or are you embedding into your own application? In the second case, did you add the dependency for orientdb-lucene? e.g: form maven add:
```code
 <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-lucene</artifactId>
            <version>2.1.9</version>
        </dependency>
```

**Comment by publicocean0** [comment]
cool , now it works :)
