### ISSUE TITLE
question for new batch functionality (if block) - exception 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5649]
orientdb version: 2.1.9
i tried to use in console with
script sql 
if block but it gives a exception
In documentation it is written available since 2.1.7
example 
<pre>
script sql                     
[Started multi-line command. Type just 'end' to finish and execute]
orientdb {db=a}> let a = select  from 33:700
orientdb {db=a}> if($a.size()>0) {         
orientdb {db=a}> return 1;
orientdb {db=a}> }
orientdb {db=a}> end

Error: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.if($a.size()>0) {;return 1;}
</pre>

**Comment by luigidellaquila** [comment]
HI @publicocean0 

this could be a problem with the console, could you please try it in Studio and let me know if it works? If it's the case, I think I can fix it easily

Thanks

Luigi

**Comment by publicocean0** [comment]
hi , in studio it works correctly.

**Comment by publicocean0** [comment]
This morning i saw same exception also from java code.

com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.if

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

I pushed a fix on branches 2.1.x and develop. The fix will be available in next hotfix release.

Thanks

Luigi
