### ISSUE TITLE
Suggestion - add database server version info on the "info" command 

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#5650]
Hi,

When using the console, it would be nice to be able to verify the database server's version number with the "info" command. Or is there another way to see the version?

See this discussion on GG for more info.

https://groups.google.com/forum/#!topic/orient-database/aXxfgI4Kp4Q

Scott

**Comment by maggiolo00** [comment]
+1

**Comment by tglman** [comment]
This is a good canditate for a new contributor
