### ISSUE TITLE
[2.1.9] ODocument save issue

### ISSUE THREAD

**Issue by autosoftteam** [orientechnologies/orientdb#5652]
Ihave problems with java Document API. We are using the version 2.1.9
Sometimes, randomly, I cannot save an ODocument into database (with or without transaction) without catching a specific exception from the database.
What can be the problem?

**Comment by maggiolo00** [comment]
hi @autosoftteam 

can you tell me some detail?

You can i reproduce this issue?

**Comment by autosoftteam** [comment]
`try { 
    ODocument od = attachedObject.toDocument(); 
    ORecord record = connection.save(od);       
    attachedObject.setOriginalRecord(record); 
    return attachedObject; 
} catch (Exception e) { 
    if(e instanceof OConcurrentModificationException) { 
       throw new ConcurrentModificationException(e); 
    } if(e instanceof ONeedRetryException) { throw e; } 
}`
connection is an instance of ODatabaseDocumentTx attachedObject is our entity bean that can be converted to a ODocument Object.

**Comment by maggiolo00** [comment]
So it does not save and 
ONeedRetryException
or
ConcurrentModificationException
are not thrown?

**Comment by autosoftteam** [comment]
yes exactly

**Comment by maggiolo00** [comment]
Can you log  Exception e ?
to check other exception?

**Comment by autosoftteam** [comment]
Yes, we log all the exceptions in the catch clause, but we can't see any exception in our logs.

**Comment by maggiolo00** [comment]
```
try { 
    ODocument od = attachedObject.toDocument(); 
    ORecord record = connection.save(od);       
    attachedObject.setOriginalRecord(record); 
    return attachedObject; 
} catch (Exception e) { 
    if(e instanceof OConcurrentModificationException) { 
       throw new ConcurrentModificationException(e); 
    } if(e instanceof ONeedRetryException) { throw e; } 
}
```

you are not logging Exception e if it's not 

OConcurrentModificationException or ONeedRetryException

**Comment by autosoftteam** [comment]
Sorry in the code snippet I omitted the not issue related code pieces,
actually the full catch code is:

```java
} catch (Exception e) { 
    log.error("Error saving object", e, null);
    if(e instanceof OConcurrentModificationException) { 
       throw new ConcurrentModificationException(e); 
    } if(e instanceof ONeedRetryException) { throw e; } 
}```

**Comment by maggiolo00** [comment]
are you able to log 

how ORecord record
looks like when it is not saved?

**Comment by autosoftteam** [comment]
Not the full object, only the Rid (but i've just changed it, to investigate better). The strange behavior is that the Rid is negative (#-1:-10) even if i'm not in a transaction, and doesn't throw any exception. If I'm in a transaction I can see correctly the negative rid before commit, but if appear the issue, it remain negative also after commit.

**Comment by maggiolo00** [comment]
if you are not in transaction the Rid should became persistent immediately
after save.
Can you do this  check? In no tX mode
add this to your code
```
ORecord record = connection.save(od); 
if(record.isTemporary()){
  log.info(connection.getTransaction().getStatus().toString())
}
```
Are you working in Multithread environment?

**Comment by autosoftteam** [comment]
Yes I'm working in Multithreaded environment, now I add the code snippet, but i need a bit time to reproduce the issue because seems appear randomly.

**Comment by maggiolo00** [comment]
Are you sharing the connection object between threads?

**Comment by autosoftteam** [comment]
I have a connection pool (OPartitionedDatabasePool) and for each thread i get a connection with the method acquire.

**Comment by maggiolo00** [comment]
Do you close the database after each requests?

**Comment by autosoftteam** [comment]
yes, after each operation we close it

**Comment by maggiolo00** [comment]
@autosoftteam 
can you provide me a test case in order to reproduce the issue?

**Comment by autosoftteam** [comment]
We are not able to reproduce the error directly. This issue happens randomly, there is no logical relation with the number of save operations.
If we try to save again the same record after a not performed save, usually there are no problem to save the record.
It's a very strange behaviour, in particular the fact that we cannot receive any exception from the database.

**Comment by maggiolo00** [comment]
I think that could be some problem with  tx state if you see that the Record id is temporary
You should investigate that. 
Are you developing a web service. Do you do the work behind an http request?

**Comment by autosoftteam** [comment]
Yes we developed a RESTful service.
We added your suggested piece of code in case of no tx for investigating better, but what we can do to invastigate also in tx?

**Comment by maggiolo00** [comment]
How do you handle transaction lifecycle?

**Comment by autosoftteam** [comment]
What do you mean for transaction lifecycle?

Below a snippet of code that show how we do in case of transactions:

`try { 
    connection.begin();
    ODocument od = attachedObject.toDocument(); 
    ORecord record = connection.save(od); //or other operations       
    attachedObject.setOriginalRecord(record); 
    
    //---other operations

    connection.commit(); 
} catch (Exception e) { 
    log.error("Error in tx", e);
    connection.rollback();
} finally {
    connection.close();
}
`

**Comment by maggiolo00** [comment]
Yes transaction handling like begin, commit rollback

**Comment by maggiolo00** [comment]
For now if you can keep track with the snippet i gave you the transaction status when the anomaly happens

**Comment by maggiolo00** [comment]
@autosoftteam 

which library do you use for RESTful service?

**Comment by autosoftteam** [comment]
I use CXF  for RESTful service

**Comment by autosoftteam** [comment]
When the issue has occurred, we always have clusterId = -1 and in the method `isTemporary()` i can see that it must be `clusterId != -1`. Has -1 on clusterId a particular meaning?

**Comment by maggiolo00** [comment]
@autosoftteam 

could you post the the clusterId/ record position and transaction status when the issues occurs?

**Comment by autosoftteam** [comment]
Cluster id is always -1 and record position is variable, the last is  #-1:-51, the transaction status is `INVALID`.

**Comment by maggiolo00** [comment]
@autosoftteam 

clusterId -1 mean thats the record is temporary
I have to find a way to reproduce this. 

How can i do that. Do yo think you can help me set up an environment to reproduce it?

**Comment by autosoftteam** [comment]
````java
public boolean isTemporary() {
    return clusterId != -1 && clusterPosition < CLUSTER_POS_INVALID;
  }
`
This is the method of the ORecordId class, if the clusterId is -1 it can't be temporary.

**Comment by maggiolo00** [comment]
@autosoftteam 

yes i meant that it is a candidate to be saved as new. The cluster id has not been assigned yet to that record.
Are you working in plocal or remote?

Do you share the db instance with other threads?

**Comment by autosoftteam** [comment]
We are working in remote, and the db instance is not shared, we share only the `OPartitionedDatabasePool`.
But I think we are near to the solution, as you said previously, could be a problem on the transaction lifecicle. In the last case that the issue has occurred, while executing a save without the transaction I obtain `#-1:-12` as Rid after the save, and the transaction object is `OTransactionOptimistic [id=20033, status=BEGUN, recEntries=11, idxEntries=0]`, the status is BEGUN, thus seems there is another transaction started on the same db instance. I must investigate on it. There is a way to set a timeout on the transaction?

**Comment by maggiolo00** [comment]
hi @autosoftteam 

There is no way to set timeout to transaction.

Have you resolved?

**Comment by autosoftteam** [comment]
How could be managed the transactions in case of database deadlock or if the connection to remote database server is not reachable?
We didn't resolve yet, we simply made a workaround checking the value of the Rid and retry the same operation many times (until the Rid become not temporary).

**Comment by maggiolo00** [comment]
@autosoftteam 

did you manage to solve this? 

Do you still need help?
