### ISSUE TITLE
NoSuchMethodError when deleting a vertex

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#5654]
Hi,

Working with both console and Studio I am getting this error when trying to delete a vertex with 

```
DELETE VERTEX #14:0
```
This is the error message.
```
java.lang.NoSuchMethodError: com.orientechnologies.orient.core.config.OStorageConfiguration.isTxRequiredForSQLGraphOperations()Z
```
Scott

**Comment by lvca** [comment]
Looks like you have different version of OrientDB in your classpath. Is this possible?

**Comment by smolinari** [comment]
Maybe.

Where can I find the classpath?

Scott

**Comment by lvca** [comment]
Check in the server's lib directory if you're running the server.

**Comment by smolinari** [comment]
Sorry, but you've completely lost me. I am not at all a Java buff. :blush: 

I'd say the server was running, because everything else in Studio seemed to be working. Just not the delete vertex command (from what I could tell).

If I should check anything more in particular, please be a bit more specific. 

Scott

**Comment by lvca** [comment]
NP. Go under $ORIENTDB_HOME/libs directory and check if you have multiple versions of OrientDB jars.

**Comment by smolinari** [comment]
Yup! That was the problem. Sorry for wasting your time. Stupid mistake on my part. 

Thanks!

Scott
