### ISSUE TITLE
SQL create/alter property attributes

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#5656]
Currently the only way to edit any property attributes is by using the `ALTER PROPERTY` command. That is, one can not specify attributes with the `CREATE PROPERTY` command.

Also, the `ALTER PROPERTY` statement seems to support only a single attribute. Would be nice if it could support more than a single attribute at a time.

**Comment by smolinari** [comment]
+1

Scott

**Comment by mpmlj** [comment]
+1

**Comment by mmacfadden** [comment]
@matanshukry Check out #5360.  It enables some of what you are asking for.  Supporting NOT NULL, MANDATORY, and READONLY.  I have an almost completed pull request for MAX, MIN, and DEFAULT as well.

**Comment by smolinari** [comment]
Why to go @mmacfadden :+1: 

Scott
