### ISSUE TITLE
Naming properties and capitalization

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#5658]
Hi,

I am wondering, should ODB property names be case sensitive? It doesn't look like case sensitivity is consistent, either insensitive, or sensitive. I'm going to assume the property names are insensitive in this issue. The steps below are on a local VM running Debian Wheezy.

With 2.1.9 and Studio, do the following steps:
1. Create a class extending V. In my test I have "MyClass".

`CREATE CLASS MyClass EXTENDS V`
1. Create a property with a capitalized letter. In my test I have "aField". 

`CREATE PROPERTY aField STRING`
1. Insert a record storing something to that property, but spelling the property name without the capitalization.

`INSERT INTO MyClass SET afield = "something"`

Expected return result:

A record with data stored under the new "aField" property (with capitalization).

Result:

A record with data stored in both the capitalized and uncapitalized properties (at least the return value leads me to believe this). 

![image](https://cloud.githubusercontent.com/assets/3314957/12694013/8bbe690c-c71e-11e5-84c2-f0c49c2dcc6a.png)
1. Select from the class again. 

The resulting record is now correct with data only under the capitalized property. 

![image](https://cloud.githubusercontent.com/assets/3314957/12694131/b21913a0-c722-11e5-803b-34eec577ba4a.png)

Ok. But, why the duplicated property in the return result? This also led me to believe property names are case insensitive. 

However......
1. Update the property value, spelling the property name incorrectly (no capitalized letters)
2. Select from the class

Expected result: an updated record, because we have case insensitivity, right? 

Result: nothing happens, despite the return value of step 6 being "1". 

![image](https://cloud.githubusercontent.com/assets/3314957/12694015/90df61de-c71e-11e5-8bed-873c8284a954.png)

If I do the update with the property name properly spelled, the property value is correctly updated. 

So, with an update, there is case sensitivity. 

To be honest, I don't know what is actually the issue, because I don't know what is right or wrong, case sensitivity or not. I hope one of the team can decipher an issue out of this, because generally, the behavior doesn't seem right. 

Please see this issue that got me started on this. 

https://github.com/orientechnologies/orientdb/issues/3629

Scott

p.s. there is nothing in the docs on case sensitivity that I could find. If I understand how things should bejhave and get expected results accordingly, then I'll add that proper behavior about case sensitivity in the docs.

**Comment by luigidellaquila** [comment]
Hi @smolinari 

property names are case sensitive, IMHO there is a bug in the return of the INSERT operation.

Thanks

Luigi

**Comment by smolinari** [comment]
Yes, that would make sense. Also have a look at the return result of updating a field with the property name spelled incorrectly. It should be "0" and not "1", shouldn't it?

Scott

**Comment by smolinari** [comment]
Is there any status on this bug? Just ran into it again.

It only happens, on the return result of the insert. 

Scott
