### ISSUE TITLE
Issue importing database into 2.1.9

### ISSUE THREAD

**Issue by sivan123** [orientechnologies/orientdb#5659]
Getting the following exception while trying to export from 2.1.2 and importing into 2.1.9. 
Importing database schema...Error on importing schema
com.orientechnologies.orient.core.exception.OSchemaException:  Class:'ORole' has
 already class:'OIdentity' as superclass
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addSuper
ClassInternal(OClassImpl.java:506)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addSuper
Class(OClassImpl.java:480)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.set(OCla
ssImpl.java:1549)

**Comment by tglman** [comment]
this is already fix in the 2.1.x branch, will be out with the next hotfix.
anyway you can workaround it checking before the export that the class ORole has only once OIdentity in the superclasses.

**Comment by sivan123** [comment]
Thank you very much.

**Comment by sivan123** [comment]
Don't think this is fixed. I tried 2.1.10 version. Getting the following error
Importing database schema...Error on importing schema
com.orientechnologies.orient.core.exception.OSchemaException: Class: 'OUser' alr
eady has the class 'OIdentity' as superclass
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addSuper
ClassInternal(OClassImpl.java:510)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addSuper
Class(OClassImpl.java:483)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.set(OCla
ssImpl.java:1553)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAlterClass.e
xecute(OCommandExecutorSQLAlterClass.java:141)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.exe
cute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.executeCommand(OAbstractPaginatedStorage.java:1547)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.command(OAbstractPaginatedStorage.java:1528)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract
.execute(OCommandRequestTextAbstract.java:67)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkP
rotocolBinary.command(ONetworkProtocolBinary.java:1323)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkP
rotocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNe
tworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:
77)
ERROR (62 entries): com.orientechnologies.orient.core.exception.OSchemaException
: Class: 'OUser' already has the class 'OIdentity' as superclass
Rebuild of stale indexes...
Start rebuild index ouser.name
Rebuild  of index ouser.name is completed.
Start rebuild index orole.name
Rebuild  of index orole.name is completed.
Stale indexes were rebuilt...
Deleting RID Mapping table...OK

Database import completed in 107418 ms
I see the schema has been built , but the records never got imported for any of the classes.

I haven't tried the work around you suggested to ensure class "ORole has only once OIdentity in the superclasses" before export. How do I do it? I cannot see a way to do this through the studio console..

**Comment by sivan123** [comment]
May be the fix only took care of ORole, while there was an issue on Ouser as well which did not got captured in the error log that I initially posted because the import never got to that point because of the issue with ORole?

**Comment by tglman** [comment]
hi @sivan123 

yes excatly ORole was hiding the problem on OUser, same fix also on OUser.

**Comment by sivan123** [comment]
@tglman Is this getting fixed in the next hotfix? Curious as it still remains in the 2.1.10 milestone.
Also how do I work around this issue?

**Comment by sivan123** [comment]
Hello @tglman  any luck on this? Would this be fixed in the next release? Or could you please provide a workaround?

**Comment by tglman** [comment]
hi @sivan123, yes this should be fixed in 2.1.10, here are the commits:
https://github.com/orientechnologies/orientdb/commit/8fa39d7d5c95005f32cdce639549ea94ab583a44
https://github.com/orientechnologies/orientdb/commit/80e2b291f186dd1e98b1ee4352c37db1a0d86f02

if you still have the problem can you send me an exported db so i can try to reproduce and fix it ?

in general the workaround is check your schema and look for a class with a duplicate superclass, and remove it.

**Comment by sivan123** [comment]
Hi @tglman , I am pretty sure that I faced the issue in 2.1.10 hence I reported it here. (2.1.9 had issues  with Orole, while that was fixed in 2.1.10, Ouser had an issue in 2.1.10 )
However I just tried 2.1.11 and I was able to successfully import the database. So looks like the issue was fixed in 2.1.11.

**Comment by tglman** [comment]
hi @sivan123 

great, can we close this issue ?

**Comment by sivan123** [comment]
Yes, please. Sorry for not getting back earlier.
