### ISSUE TITLE
Using partitioned graphs gives "restricted access" error on updating own edge

### ISSUE THREAD

**Issue by aheintz** [orientechnologies/orientdb#5660]
I'm trying to use partitioned graphs instead of multiple databases (since want to setup a distributed database) to separate customer data. According to the docs, partitioned graphs is the recommended way. 

However, I'm getting error when trying to create vertices and edges between them in the same transaction. Actually, I'm getting a "the resource has restricted access" even if I commit the transaction after creating the vertices and after that tries to add an edge between them. I'm using version 2.1.4.

I have updated the V and E and they both have "ORestricted" as superclass and created a user with "writer" Role using the following statement:
`INSERT INTO ouser SET name = "user", status = 'ACTIVE', password = "password", roles = ( select @rid from ORole where name='writer' )`

I have already created the vertex types "Test1" and "Test2" extending V and the Edge type "Edge1" extending E.

First unit test (which is what I am doing in my application):
```
    @Test
    public void testPartitionedGraphVertexEdgeInSameTx() throws Exception {
        String url = "remote:localhost/partitionedgraph";
        OPartitionedDatabasePool pool = new OPartitionedDatabasePool(url, 
                "user", "password", 10);


        OrientGraph graph = new OrientGraph(pool.acquire());
        graph.setRequireTransaction(true);
        Vertex v1, v2 = null;
        Edge e = null;
        try {
            v1 = graph.addVertex("class:Test1");
            v2 = graph.addVertex("class:Test2");
            e = graph.addEdge(null, v1, v2, "Edge1");
        } finally {
            graph.commit();
        }

        graph.shutdown();
        logger.debug("Edge created: " + e);
    }
```

Throws the exception
`com.orientechnologies.orient.core.exception.OSecurityException: Cannot update record #14:-4: the resource has restricted access`

Second unit test I created to try to work around this problem:
```
    @Test
    public void testPartitionedGraphVertexEdgeCommitBetween() throws Exception {
        String url = "remote:localhost/partitionedgraph";
        OPartitionedDatabasePool pool = new OPartitionedDatabasePool(url,
                "user", "password", 10);


        OrientGraph graph = new OrientGraph(pool.acquire());
        graph.setRequireTransaction(true);
        Vertex v1, v2 = null;
        Edge e = null;
        try {
            v1 = graph.addVertex("class:Test1");
            v2 = graph.addVertex("class:Test2");
        } finally {
            graph.commit();
        }
        try {
            e = graph.addEdge(null, v1, v2, "Edge1");
        } finally {
            graph.commit();
        }

        logger.debug("Edge created: " + e);
        graph.shutdown();
    }
```

Throws the exception 
`com.orientechnologies.orient.core.exception.OSecurityException: Cannot update record #13:16: the resource has restricted access`

I cannot see that I'm doing anything wrong here, at least not what I have found in the docs. This is a real showstopper for us. Assistance please!

**Comment by smolinari** [comment]
Hey @aheintz, 

I played around with this in Studio and it seems, if you add the superclass ORestricted to V or E, it causes things to mess up internally with ODB. I am getting the following error, when I try to use the database with the new user and with V and E extending ORestricted.

```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #5:0 (cluster: ouser)
 --> com.orientechnologies.orient.core.exception.OSecurityAccessException: User 'user' has no the permission to execute the operation 'Read' against the resource: ResourceGeneric [name=CLUSTER, legacyName=database.cluster].ouser
```

However, if the new classes are the only ones to extend ORestricted, then things seem to work correctly. 

So, I guess my suggestion is to not extend V and E with ORestricted, but rather only your custom classes should extend V, E and ORestricted.  

Like this:

`CREATE CLASS Test1 EXTENDS V, ORestricted`
`CREATE CLASS Test2 EXTENDS V, ORestricted`
`CREATE CLASS Edge1 EXTENDS E, ORestricted`

That should do the trick and get your tests passing.

Scott

**Comment by aheintz** [comment]
Thanks for you response! I tried your suggestion, but unfortunately it didn't work. I still get the same errors. I tried it in studio, and that works fine. I'm going to play around with the connection/transaction and see if I can get it working using the api.

**Comment by smolinari** [comment]
Sorry to hear that. I guess one of the ODB team will have to have a look at this.

Scott

**Comment by aheintz** [comment]
Well, it seems like the `addVertex` api method is broken. It still wasn't working when I created the vertices first and then closed the connection, opened a new and created the edge. 

Imho, my case should be identical with using the studio. However, to try to replicate the studio behaviour I changed from `addVertex` to run a SQL command, and voila. It works!

Both test cases works when I replace
```
v1 = graph.addVertex("class:Test1");
v2 = graph.addVertex("class:Test2");
```
with 
```
v1 = graph.command(new OCommandSQL("create vertex Test1")).execute();
v1 = graph.command(new OCommandSQL("create vertex Test2")).execute();
```

Thanks a lot @smolinari for putting me on the trail, now I'm not showstopped anymore which I'm very, very, very relieved about...! :+1: 

The tests provided should really work and the bug is still valid, though it's a bit of a relief that it's not the core server functionality that's not working, but somewhere in the api call stack.

**Comment by smolinari** [comment]
Glad you figured out a workaround. I am positive one of the ODB team will have a look at this and take any necessary action.

Scott

**Comment by tglman** [comment]
hi @smolinari, @aheintz,

I retried the test cases reported in 2.2.10, the first test run without problems, the second has a small issue with old data that can me solved with a simple reload.
here the example of the second test:
```
  @Test
  public void testPartitionedGraphVertexEdgeCommitBetween() throws Exception {
    String url = "remote:localhost/partitionedgraph";
    OPartitionedDatabasePool pool = new OPartitionedDatabasePool(url, "user", "password");

    OrientGraph graph = new OrientGraph(pool.acquire());
    graph.setRequireTransaction(true);
    OrientVertex v1, v2 = null;
    Edge e = null;
    try {
      v1 = graph.addVertex("class:Test1");
      
      v2 = graph.addVertex("class:Test2");
    } finally {
      graph.commit();
    }
    try {
      v1.reload();
      v2.reload();
      e = graph.addEdge(null, v1, v2, "Edge1");
    } finally {
      graph.commit();
    }

    graph.shutdown();
  }
```

So i consider this fixed, closing

**Comment by Amroaa** [comment]
reload the vertex using:

Vertex Vp = graph.getVertex(v1.getId());

also fix the problem
