### ISSUE TITLE
Studio and creating databases with a space in the name

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#5661]
Is it supposed to be possible to create database names with two words? 

If yes, it doesn't work with Studio.

If no, the system should error out better. 

Currently Studio goes about its business showing the new database (with a two word name), however, it is impossible to log into that database. 

Scott

**Comment by maggiolo00** [comment]
@smolinari 

the problem seems to be on Http Protocol, i'm checking

**Comment by maggiolo00** [comment]
Fixed in 2.1.x and develop

**Comment by smolinari** [comment]
Will the fix be in 2.1.10 or 11?

**Comment by maggiolo00** [comment]
hi @smolinari 

i think it will be available in 2.1.10

**Comment by smolinari** [comment]
Ok. Thanks. I'll test the fix, once the new version is out.

Scott

**Comment by smolinari** [comment]
I guess this didn't get into 2.1.10?

Scott

**Comment by maggiolo00** [comment]
hi @smolinari 
should be there. It not working?

I've made this test:

Created a db with  name

`test db`

and logged in

**Comment by smolinari** [comment]
I haven't tested yet. It was just missing as one of the fixes in the release. I guess because the milestone is missing in this issue?

Scott

**Comment by maggiolo00** [comment]
hi @smolinari 

yes i forgot the milestone :D

**Comment by smolinari** [comment]
Tested! Works like a charm now. Thanks!

Scott
