### ISSUE TITLE
Not able to run osql commands in Studio

### ISSUE THREAD

**Issue by CyborTronik** [orientechnologies/orientdb#5662]
Would like to have the ability to run OSql scripts in studio.
Or at least to have the possibility to run any kind of command like: create property/class... whatever.
For now seems studio is oriented in just creating through UI elements and to query.
It's pretty good for existing databases, but not for restoring/creating/moving dbs.

**Comment by smolinari** [comment]
You can run any SQL command in Studio to create, delete, update or read any part of a single database. You can also create and delete databases. 

Doing more from an administrative perspective is probably reserved for the Enterprise Edition. 

http://orientdb.com/orientdb-enterprise/

Scott
