### ISSUE TITLE
Preserve RecordId's during import

### ISSUE THREAD

**Issue by n0lf** [orientechnologies/orientdb#5663]
There is a flag -preserveClustIDs (see http://orientdb.com/docs/2.1/Console-Command-Import.html). It would be nice if we could also preserve all ids within a cluster.

**Comment by smolinari** [comment]
:+1: :+1: 

This would be imperative for us for our planned database migration processes and I thought it would be possible. It would also be needed that the id sequence should start after the last (highest number) imported id again. Could that also be possible?

Scott

**Comment by n0lf** [comment]
@smolinari  I know a workaround for this is to restore a backup instead of doing an import.

**Comment by smolinari** [comment]
Our intentions though aren't to backup data or restore it, but rather to migrate portions of a database  to a new database. 

Scott

**Comment by lvca** [comment]
This is not supported by design, sorry.
