### ISSUE TITLE
exception in number promotion or no existence of number type suffix for constants

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5664]
I was executing this command : 

update #34:86 set last = max(91,ifnull(last,0)) 

where last is a long field. 

this query gives a error 

Error: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

the error seams generated by 0 in ifnull or if .

Instead 

update #34:86 set last = max(91,last)  is working 

so i imagine that if consider 0 as integer and converting it to Long (argument of max) gives exception.

0l is not working, 0.asLong() is not working.

**Comment by publicocean0** [comment]
another related error in select 

 Error on execution of command: sql.select from #34:86 WHERE  last< 95 OR last is null

Error: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

**Comment by publicocean0** [comment]
it seams a general bug in all the sql parsing. Probably same error for float , double , short ..

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

I'm on it, I'll let you know soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

I just pushed a fix on 2.1.x branch. The fix will be released with next hotfix

Thanks

Luigi
