### ISSUE TITLE
critical   error : no delection executed

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5665]
v2.1.9-SNAPSHOT
<pre> 
delete from (select rid from  index:A.b_c where key =[#38:10,#33:96])

Delete record(s) '1' in 0,001000 sec(s).

select rid from   index:A.b_c where key =[#38:10,#33:96]                               

----+------+------
#   |@CLASS|rid   
----+------+------
0   |null  |#54:76
----+------+------

</pre>

**Comment by publicocean0** [comment]
script sql                                                                                                        
[Started multi-line command. Type just 'end' to finish and execute]
orientdb {db=a}> begin
orientdb {db=a}>  delete from (select rid from  index:index:A.b_c where key =[#38:10,#33:100])
orientdb {db=a}> commit 
orientdb {db=a}> end

Error: com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit.

Error: java.lang.IllegalArgumentException: Cluster segment #-2 does not exist in database 'a'

**Comment by publicocean0** [comment]
i found the problem.

There is a Class A with a trigger on delete.
a is a instance of A.
i call       delete  a       inside a transaction.
When orientdb enter in trigger 
 it calls a second js function as this
<pre>
db.begin()
try{
....
}catch(e){
db.rollback(); throw e;
}
</pre>
writing a lot of trancing log... i saw that after is called db.begin()... the Thread get blocked.

**Comment by publicocean0** [comment]
For now for evoiding the block of thread ... i m using in js

var txcount=db.transaction.amountOfNestedTxs() for understanding if i m in a transaction or not.

**Comment by laa** [comment]
Hi @publicocean0 is it possible to get example of database and/or full stack trace of exception to reproduce given issue ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
