### ISSUE TITLE
collection [] method broken in 2.1.9 for ranges

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#5666]
I've got these classes in my schema:

```
create class hour extends V
create class minute extends V
create class tdindex extends V

create property hour.hour integer
create property hour.minute linkmap minute

create property minute.index linkset tdindex

```

When I query single values from 'hour' linkmap I get different 'minute' records than when I query ranges:

```

orientdb {db=rawxp}> select expand(minute[29]) from hour where hour=7   

----+-------+------+-----
#   |@RID   |@CLASS|index
----+-------+------+-----
0   |#13:449|minute|[281]
----+-------+------+-----

1 item(s) found. Query executed in 0.002 sec(s).
orientdb {db=rawxp}> select expand(minute[30]) from hour where hour=7

----+-------+------+-----
#   |@RID   |@CLASS|index
----+-------+------+-----
0   |#13:450|minute|[289]
----+-------+------+-----

1 item(s) found. Query executed in 0.002 sec(s).
orientdb {db=rawxp}> select expand(minute[29-30]) from hour where hour=7

----+-------+------+-----
#   |@RID   |@CLASS|index
----+-------+------+-----
0   |#13:448|minute|[287]
1   |#13:451|minute|[283]
----+-------+------+-----

2 item(s) found. Query executed in 0.002 sec(s).
```

When I take a look at the records, #13:449 and #13:450 are the correct results that I'd expect for that last query.

Here's another query result:

```

orientdb {db=rawxp}> select expand(minute[29,30]) from hour where hour=7 

----+-------+------+-----
#   |@RID   |@CLASS|index
----+-------+------+-----
0   |#13:449|minute|[281]
1   |#13:450|minute|[289]
----+-------+------+-----

2 item(s) found. Query executed in 0.023 sec(s).
```

That looks correct, so the comma operator appears to work ok.

Here's a link to a copy of the database that exhibits this bug: [https://drive.google.com/folderview?id=0B7gmW6cqkVoHWnNVMnhLaGJkYzA&usp=sharing](url) (in both bz2 and gz compression).

**Comment by luigidellaquila** [comment]
Hi @8forty 

Thanks for reporting, I'll check it asap

Thanks

Luigi

**Comment by 8forty** [comment]
At the suggestion of Alessandro Rota, I tried quoting the range (e.g. ["29-30"]); that produced the same incorrect results.

**Comment by luigidellaquila** [comment]
Hi @8forty 

In v 3.0 we fixed all this with the new `x..y` (last excluded) and `x...y` (last included) range syntax, eg.

select expand(minute[29...30]) from hour where hour=7 

Thanks

Luigi
