### ISSUE TITLE
Question: Existence of a foreign key constraint 

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb#5667]
Hi

Just curious, Is there any way to provide some kind of foreign key constraints in OrientDB? Let's assume that I have to records where one of them points to the another. How can I make sure that a user can't delete the record which is referenced to? Without using FIND REFERENCE and stuff like that?

Thanks in advance.

**Comment by smolinari** [comment]
I think this is along the lines of the question I asked on GG, isn't it? 

https://groups.google.com/forum/#!topic/orient-database/sQuhTaRPZRc

You are also better off asking such questions on GG too, until you know you want to make a suggestion or you have an issue. Suggestions and issues are what should be reported here on Github.

Scott

**Comment by maseev** [comment]
Ok then.

**Comment by smolinari** [comment]
Yeah, the "please ask questions on the community sites" was requested just recently. 

https://groups.google.com/forum/#!topic/orient-database/-1_gMci4hwo

The answer to your question AFAIK is, it depends. The only method to create a master/detail or foreign key constraint in ODB is through embedding. if you want this across linked documents, you have to build the logic on the application side/ in the your own data.

Scott
