### ISSUE TITLE
Problems with - ALTER DATABASE DATE/TIME FORMAT

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5668]
Hi,
I am using OrientDB 2.1.9 and this is how to reproduce the error
On a fresh Graph database enter the following commands

```
create class MyDate
alter class MyDate superclass V
create property MyDate.dval Date
```

Check the DB configuration on date format : yyyy-MM-dd
Enter data

```
create vertex MyDate content {dval:"2010-01-29"}
create vertex MyDate content {dval:"2010-10-10"}
```

Records are created and displayed fine e.g. with a `select from MyDate` command

```
ALTER DATABASE DATEFORMAT "dd/MM/yyyy"
create vertex MyDate content {dval:"01/01/2001"}
```

No problem here you can try `select from MyDate` and you get all the records with yyyy-MM-dd format

Let's switch back with the following command

```
ALTER DATABASE DATEFORMAT yyyy-MM-dd
```

Command has been executed successfully (Green bar displayed)
Now let's try to enter a record

```
create vertex MyDate content {dval:"2002-02-02"}
```

Command executed successfully but see the dval value of the record that has been created 
**dval : 0002-01-01 00:00:00**

These problems may occur if you do not use quotes on the format, i.e. "yyyy-MM-dd"

PS: I have been confused on how to reproduce the mistake, but I clearly managed to get this strange date values when I did not use quotes on the date format.

**Comment by smolinari** [comment]
I can confirm this. Also if you use YYYY instead of yyyy, ODB accepts this and outputs the data with incorrect values.

Why is also time values being returned with a date field? 

Scott

**Comment by healiseu** [comment]
@lvca 
You may also add the following related bug..... If you use the command

```
ALTER DATABASE DATEFORMAT dd/MM/yyyy
```
**Notice that I have not used quotes**

Then you may enter dates
```
insert into Expires set expDate='14 / 6 / 2011'
```
**Notice the spacing**

But you **cannot** enter dates with a format like
```
insert into Expires set expDate='14/6/2011'
```
**No spacing here**
You will get an error
**Error on conversion of date '14/5/2010' using the format: dd / MM / yyyy**

The problem is solved if you ALWAYS use quoted values for altering database configuration keys, i.e.
```
ALTER DATABASE DATEFORMAT "dd/MM/yyyy"
```

**Comment by luigidellaquila** [comment]
Hi @healiseu 

This is a quite old issue, related to 2.1.x, anyway this is the expected behavior as `yyyy/MM/dd` is a valid expression (two divisions) but it just does not make any sense as a date format.

I'm closing this

Thanks

Luigi
