### ISSUE TITLE
Method not working in select expressions

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#5671]
Hi , I have a serious problem with 2.1.9 .
I guess there is a sql parsing  bug in this release, that returns some missing in functionalities 
for example : 
`select '1'.asLong() + 1  as newID from E
`
returns nothing in GratefulDeadConcerts DB .
or when i working  on Link .include() method nothing returns .
is there any idea ?

**Comment by saeedtabrizi** [comment]
Dear @luigidellaquila, @lvca  
i have a urgently question  : 
is this  `select '1'.asLong() + 1 as newID from E` true ? i'm confused now . the returns value is wrong or this code have problem ?
please help me .

**Comment by nagarajasr** [comment]
did you try using 'eval' function

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

It seems to be a bug, I'll check it asap

Thanks

Luigi

**Comment by saeedtabrizi** [comment]
Hi @luigidellaquila, @lvca  

In my case i have a Class that contains EmpID as string value type .
---------------Employee ---------------------------------
|_EmpID_|______Name__________|
|_'001'___|______'saeed'_________|
|_'002'___|______'ali'____________|
|_'003'___|______'majid'_________|
|_'004'___|______'ahmad'________|

I  want to query the largest string value. for example  `select max(EmpID) from Employee` must returns '004' value so this part is ok .
But i want to evaluate returned value as a long and increment it, then format to '000' style string .

Can i write `select max(EmpID).asLong()+1 from Employee` and this query returns '005' ? 
As i said the above query returns nothing actually . 

how can do that and when this bug would be fixed ? 

Thanks 
Saeed

**Comment by smolinari** [comment]
It sounds like you are trying to create an auto-increment for the ids . Is this correct? If it is, is there a reason why you just don't use a regular sequence?  

http://orientdb.com/docs/2.2/Sequences-and-auto-increment.html

Scott

**Comment by saeedtabrizi** [comment]
Hi @smolinari 
Thanks for your solution . 
the sequence is ideal for other case  except my problem  exactly . 
in the fact i have some user that needs to have separate sequence for generate new ID  . 
i tried to using sequences  but more complexity happened in my app that i leave this solution .
After all , i have a problem with sql function now really . 

Thanks
Saeed Tabrizi

**Comment by smolinari** [comment]
> in the fact i have some user that needs to have separate sequence for generate new ID

How many users? Are you running some sort of a multi-tenant system? 

Scott

**Comment by saeedtabrizi** [comment]
@smolinari 
Yes , we working to develop cloud services for our customers .

Saeed

**Comment by smolinari** [comment]
Ok. I've also been looking at the possibilities with ODB and multi-tenancy and we will be going with dedicated databases for bigger customers. On the other hand, smaller customers and the sandboxes and demo environments will be using a hybrid system, where we'll included multiple tenants per database. However, we will still be dedicating the classes to each customer, so sequences can be used. In other words, customer data will never "intermingle" with any other customer data in any single class.

Scott

**Comment by saeedtabrizi** [comment]
@smolinari Thanks for your guides . 
so recommended solution for bigger customer in cloud environment is separating the databases in OrientDB.
A painful issue in this solution is maintenance 

Thanks 
Saeed Tabrizi

**Comment by smolinari** [comment]
I am not sure what you mean. The maintenance is at server level, not at database level. Or do you mean schema updating as maintenance?

Scott

**Comment by saeedtabrizi** [comment]
actually database level maintenance like the schema updating , migration or etc operations .

**Comment by smolinari** [comment]
Yes. This is where I believe going "no sql" or rather schemaless wins out. If you you leave the schema at application level, you shouldn't need to worry about schema at the database level. I know there are also pros and cons to this, but it is how we are planning to make the database per tenant infrastructure work. Also, our "core" system will have very little in the form of its own schema. The rest will be customer defined schema, and also a reason why we need the separation.

Scott

**Comment by saeedtabrizi** [comment]
@smolinari 
Thanks for your guides and notes .

Saeed Tabrizi

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

There are two problems in this issue:
- the "1".asLong() that does not work
- the 1 + 1 in projections, that is not supported in current release

I consider this issue related to the first one, for the second one I'm afraid you have to wait for next releases (it's already tracked in the roadmap together with rewriting of the executor).

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

I just pushed a fix for the method invocation issue.
Now the following works fine:
```
select '1'.asLong() as newID from E 
```

The fix will be available in next 2.2.1

Thanks

Luigi
