### ISSUE TITLE
Java remote client runs out of memory

### ISSUE THREAD

**Issue by rohrl** [orientechnologies/orientdb#5677]
Hi,
I'm using OrientGraphNoTx to perform massive insertion of vertices and edges into remote graph database (connected via binary server connection).
It does not take long before the client JVM runs out of memory, even with very high Xmx settings (20g and more)
Database is empty at the beginning and has 2 indexes: guid (unique) and vtype.
Guid is used to fetch vertices when creating edges.

My client code is very simple standalone java program, the code is below:

```java
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Random;
import java.util.stream.IntStream;

import com.orientechnologies.orient.core.intent.OIntentMassiveInsert;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OSchemaProxy;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientBaseGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;

import static java.util.stream.Collectors.*;

public class OrientBenchmark
{
    static final long TOTAL_V = 1_000_000_000;
    static final int LOG_INTERVAL = 10_000;
    OrientGraphFactory factory;
    OrientGraphNoTx graph;
    Random random = new Random();
    int V, E;
    SimpleDateFormat sdf = new SimpleDateFormat("MMM dd,yyyy HH:mm");
    String guidPrefix = "guid" + String.valueOf(random.nextInt(10000)) + "_";

    public static void main(String[] args)
    {
        new OrientBenchmark().run();
    }

    private void run()
    {
        try
        {
            String url = "remote:localhost/db1";
            String username = "root";
            String password = "root";

            System.out.println("Connecting to db " + url + ", user: " + username);
            graph = setupDatabase(url, username, password);

            Vertex prev = null;

            for (int i = 0; i < TOTAL_V; i++)
            {
                String guid = guidPrefix + i;
                Vertex vertex = insertVertex(i, guid);
                insertEdges(vertex, prev);
                logStats(i);
                prev = vertex;          
             }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        finally
        {
            graph.shutdown();
            factory.close();
        }
    }

    private int insertEdges(Vertex vertex, Vertex prev)
    {
        // insert edge to previous
        if (prev != null)
        {
            addEdge(vertex, prev, "backward");
        }
        // insert random edges
        int deg = generateDegree();
        for (int j = 0; j < deg; j++)
        {
            int idx = random.nextInt(V);
            Vertex rand = graph.getVertices("guid", guidPrefix + idx).iterator().next();
            addEdge(vertex, rand, "label" + random.nextInt(10));
        }
        return deg;
    }

    private Vertex insertVertex(int i, String guid)
    {
        Vertex vertex = graph.addVertex(null);
        vertex.setProperty("guid", guid);
        vertex.setProperty("vtype", i % 2 == 0 ? "someType" : "otherType");
        vertex.setProperty("random100", String.valueOf(random.nextInt(100)));
        vertex.setProperty("random1000", String.valueOf(random.nextInt(1000)));
        V++;
        return vertex;
    }

    private void addEdge(Vertex a, Vertex b, String label)
    {
        graph.addEdge(null, a, b, label);
        E++;
    }

    private void logStats(int i)
    {
        if (i % LOG_INTERVAL == 0)
        {
            String date = sdf.format(new Date());

            long tic = System.currentTimeMillis();
            long v = graph.countVertices();
            long e = graph.countEdges();
            long tac = System.currentTimeMillis() - tic;

            System.out.println(stats(date, v, e));
        }
    }

    private int generateDegree()
    {
        float randX = 10.0f * random.nextFloat();
        int deg = (int) Math.round(Math.pow(10, randX) / 30_000_000.0f) / 5;
        return deg;
    }

    private OrientGraphNoTx setupDatabase(String url, String username, String password)
    {
        factory = new OrientGraphFactory(url, username, password);
        factory.setupPool(1, 10);
        OrientGraphNoTx graph = factory.getNoTx();

        graph.declareIntent(new OIntentMassiveInsert());

        return graph;
    }

    private static String stats(String date, long V, long E)
    {
        return String.format(Locale.ROOT, "%s \tV: %6d \tE: %7d \tV/E: %.2f \tV+E: %8d", date, (int) V, (int) E, (float) V / E, (int) (V + E));
    }

}
```

I'm pretty sure it's the OrientGraphNoTx graph object that's leaking memory.

Server is doing fine though.
I'm not using transactions and WAL is disabled.

**Comment by laa** [comment]
Hi,
Could you provide link to heap dump, without heap dump it is impossible to fix such issue.

**Comment by rohrl** [comment]
I executed a new run of code above. 
Attached you will find 2 "jmap -histo" outputs and client stdout output with final OOME. 
I can provide .hprof file from the crash, if you require it, but it's 1.3 gb.
Client lasted for around 10 minutes before crash.

Stdout:

**C:\Orient\mem-leak-code>java -cp ..\standalone\lib\*;. -Xms128m -Xmx1g -XX:+HeapDumpOnOutOfMemoryError OrientBenchmark**
Connecting to db remote:localhost/db1, user: root
Feb 04, 2016 11:58:49 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=15,040MB (heap=910MB os=17,999MB disk=35,427MB)
Feb 04,2016 11:58       V:   4727       E:   18309      V/E: 0.26       V+E:    23036
Feb 04,2016 11:59       V:  14727       E:   57220      V/E: 0.26       V+E:    71947
Feb 04,2016 12:00       V:  24727       E:   94301      V/E: 0.26       V+E:   119028
Feb 04,2016 12:01       V:  34727       E:  132269      V/E: 0.26       V+E:   166996
Feb 04,2016 12:02       V:  44727       E:  170134      V/E: 0.26       V+E:   214861
Feb 04,2016 12:03       V:  54727       E:  206442      V/E: 0.27       V+E:   261169
Feb 04,2016 12:04       V:  64727       E:  244775      V/E: 0.26       V+E:   309502
Feb 04,2016 12:05       V:  74727       E:  281664      V/E: 0.27       V+E:   356391
Feb 04,2016 12:06       V:  84727       E:  319431      V/E: 0.27       V+E:   404158
Feb 04,2016 12:06       V:  94727       E:  358092      V/E: 0.26       V+E:   452819
Feb 04,2016 12:07       V: 104727       E:  395706      V/E: 0.26       V+E:   500433
Feb 04,2016 12:09       V: 114727       E:  434578      V/E: 0.26       V+E:   549305
**java.lang.OutOfMemoryError: GC overhead limit exceeded**
Dumping heap to java_pid6056.hprof ...
Heap dump file created [1408112386 bytes in 10.733 secs]
com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #17:34174
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2044)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2568)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1764)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.addEdgeInternal(OrientGraphNoTx.java:241)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.addEdgeInternal(OrientGraphNoTx.java:136)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:695)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addEdge(OrientBaseGraph.java:729)
        at OrientBenchmark.addEdge(OrientBenchmark.java:99)
        at OrientBenchmark.insertEdges(OrientBenchmark.java:81)
        at OrientBenchmark.run(OrientBenchmark.java:52)
        at OrientBenchmark.main(OrientBenchmark.java:32)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:328)
        at java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:297)
        at com.orientechnologies.common.concur.resource.OResourcePool.returnResource(OResourcePool.java:129)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.release(ORemoteConnectionManager.java:121)
        at com.orientechnologies.orient.client.remote.OStorageRemote.endResponse(OStorageRemote.java:1639)
        at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:418)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.createRecord(OStorageRemoteThread.java:240)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1999)
        ... 13 more



JVisualVM graphs:
![jvisualvm](https://cloud.githubusercontent.com/assets/14173005/12804060/a3374792-cb43-11e5-865c-a3777aa6f89b.png)


[jmapAt1208.txt](https://github.com/orientechnologies/orientdb/files/116807/jmapAt1208.txt)
[jmapAt1200.txt](https://github.com/orientechnologies/orientdb/files/116806/jmapAt1200.txt)

**Comment by laa** [comment]
@rohrl that is not heap dump, you may create heap dump automatically in case of OOM by providing option  ```-XX:+HeapDumpOnOutOfMemoryError``` (this one will be very useful), or from command line calling ```jps``` to get pid, and then ```jmap -dump:format=b,file=mymemorydump.hprof <pid>```

**Comment by rohrl** [comment]
@laa I know, I wrote that I have full heap dump that is 1.3gb...
It was created in the same run with XX:+HeapDumpOnOutOfMemoryError.
Here's the link:
https://drive.google.com/file/d/0B7iZXYCcPHn3MF9tbjFXQ0ZvOTA/view?usp=sharing
In case you didn't notice, there are also 2 "jmap -histo" outputs at the end of my previous post that might be helpful.
Cheers

**Comment by tglman** [comment]
hi @rohrl,

I checked your code and i saw that you are building a kind of huge link list, knowing that Vertex keep bidirectional references you are actually keeping all the records in memory, i change a bit your code for clean up references in memory once a while.
here we go:
```
            for (int i = 0; i < TOTAL_V; i++)
            {
                String guid = guidPrefix + i;
                Vertex vertex = insertVertex(i, guid);
                insertEdges(vertex, prev);
                logStats(i);
                prev = vertex;
                if(i %1000 == 0)
                {
                  Object id = prev.getId();
                  prev = null;
                  graph.getRawGraph().getLocalCache().clear();
                  prev = graph.getVertex(id);
                }
             }
```

this was all the problem, closing.
