### ISSUE TITLE
poor performance for delete vertex

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5679]
what happen to your database? are you sure your database provide promised performance in the market? we feel really headache about this database as it always provide very poor performance. faint. 

The following query take about 16 seconds  to delete one record from 80000K records. 

delete vertex #56:86465

**Comment by smolinari** [comment]
Did it have a lot of edges connecting it?

Scott

**Comment by martingg88** [comment]
There are only 6 edges connected to it.

**Comment by smolinari** [comment]
Hmm...then I would also expect a better result. Which version are you on? 

I wish there would be a test database with a bit more data than the ones available for testing these kinds of things. Hint...hint...ODB team. :wink: 

Scott

**Comment by martingg88** [comment]
i'm using 2.1.8 version. hope ODB team can solve this issue.

**Comment by maggiolo00** [comment]
hi @martingg88 
can you share your dataset so i can reproduce the issue?

**Comment by martingg88** [comment]
sorry. we can't share this database. maybe we describe the database structure here that you can populate as many data as you can for testing. 

one entity (etc: car) can have following vertexes linked by edge
- one place in Place vertex 
- many photos (etc: 5 to 20 or more) in Media vertex. 

you can populate more data for car and its associations, and then you will have this slow issue for delete vertex for sure. 

Thank you.

**Comment by maggiolo00** [comment]
Where do you execute the query?

with Orientjs or Studio or Console?

**Comment by maggiolo00** [comment]
@martingg88 

can you post the results from
`select from #56:86465` ?

**Comment by martingg88** [comment]
I'm executing query at Studio. 

The result as follows: 

{
    "result": [
        {
            "@type": "d",
            "@rid": "#56:86465",
            "@version": 2,
            "@class": "thing",
            "website": "",
            "creator": "#16:3",
            "lowest_rate": 86,
            "amenity": {
                "property": [
                    
                ],
                "room": [
                    
                ]
            },
            "check_in": "02:00 PM",
            "rating": 4,
            "active": true,
            "description": "Ideally located in the prime touristic area of Trastevere, Grand Hotel Del Gianicolo promises a relaxing and wonderful visit. Offering a variety of facilities and services, the hotel provides all you need for a good night's sleep. Facilities like free Wi-Fi in all rooms, 24-hour front desk, facilities for disabled guests, express check-in/check-out, luggage storage are readily available for you to enjoy. Designed for comfort, selected guestrooms offer internet access – wireless (complimentary), whirlpool bathtub, non smoking rooms, air conditioning, heating to ensure a restful night. Enjoy the hotel's recreational facilities, including hot tub, outdoor pool, garden, before retiring to your room for a well-deserved rest. Grand Hotel Del Gianicolo combines warm hospitality with a lovely ambiance to make your stay in Rome unforgettable.",
            "source": 62592,
            "highest_rate": 0,
            "mtime": "2016-02-03T19:01:05+0000",
            "check_out": "12:00 AM",
            "price": 86,
            "name": "Grand Hotel Del Gianicolo",
            "ctime": "2016-02-03T19:01:05+0000",
            "currency": "USD",
            "payment": null,
            "category": "hotel",
            "policy": null,
            "in_list": [
                "#68:107903"
            ],
            "out_locate": [
                "#27:107903"
            ],
            "out_upload": [
                "#42:629725",
                "#42:629726",
                "#42:629727",
                "#42:629728",
                "#42:629729"
            ],
            "out_act": [
                "#48:107906"
            ],
            "@fieldTypes": "creator=x,lowest_rate=c,rating=d,highest_rate=c,mtime=t,price=c,ctime=t,in_list=g,out_locate=g,out_upload=g,out_act=g"
        }
    ],
    "notification": "Query executed in 0.206 sec. Returned 1 record(s)"
}

**Comment by maggiolo00** [comment]
@martingg88 

can you send me to e.risa@orientdb.com

the results of this query?


```
select expand(both()) from #56:86465
```

**Comment by martingg88** [comment]
The result will be as follows: 

1. one user record
2. one listing record
3. one activity record
4. one place record
5. many media (etc: photo) records

**Comment by laa** [comment]
Hi @maggiolo00 do we have tree support for ridbags in Node.js driver ?

**Comment by laa** [comment]
@martingg88 what is your HW environment ? Could you provide numbers ?

**Comment by maggiolo00** [comment]
@laa 
nope we do not have the tree support.

**Comment by martingg88** [comment]
I do have this issue at my localhost environment which supposed to have high-end performance. 
But I set 512MB memory for server.bat.

Intel core i7-3517u CPU @ 1.9GHz
12.GB RAM
64 bit

**Comment by laa** [comment]
I think this issue may be split on two issues , one is support of tree ridbag in Node.js and second is support of delayed deletion of vertexes with many edges.

**Comment by laa** [comment]
Well I think I should put it in 3.0 version.

**Comment by maggiolo00** [comment]
Tree ridbag support is here

https://github.com/orientechnologies/orientjs/issues/29

**Comment by laa** [comment]
Also issue about delayed removal of vertexes, which explains reason of current issue https://github.com/orientechnologies/orientdb/issues/5866

**Comment by laa** [comment]
I think once we fix both of them this one will be fixed automatically.

**Comment by martingg88** [comment]
where do you think 3.0 will be released?
