### ISSUE TITLE
Should not be able to create functions with the same name.

### ISSUE THREAD

**Issue by thejjmiller** [orientechnologies/orientdb#5682]
Currently you can create new functions with the same name. This should probably not be allowed and should fail on creation.

**Comment by thejjmiller** [comment]
#4751 This is a question that was posted about the same issue but looks like this was left as a question not as an defect.

**Comment by luigidellaquila** [comment]
Hi @thejjmiller 

We verified the issue, we are working on it.

In the meantime, as an easy work-around, you can define a UNIQUE index on OFunction.name class, it will prevent from creating two functions with the same name.

Thanks

Luigi

**Comment by thejjmiller** [comment]
Thank you. Very good work around.

**Comment by tglman** [comment]
Implemented the check plus some additiona missing api.

**Comment by luigidellaquila** [comment]
The fix will be released with 2.1.11

**Comment by tglman** [comment]
i haven't backport the fix to 2.1.x yet because i had to add new api to cover all the cases.

anyway the fix is to create an index at OFunctionLibrary, so very similar to the workaround.

**Comment by tglman** [comment]
closing was  fixed
