### ISSUE TITLE
Cross Data Center Replication

### ISSUE THREAD

**Issue by thejjmiller** [orientechnologies/orientdb#5683]
Can I get some help with how to setup a distributed cluster? 

Here is the type of environment we need:

3+ servers in Dallas with every document stored on a master node and a replicate stored on a slave node
3+ servers in Atlanta which is a online replicate of Dallas.

I have been unable to setup a clustered OrientDb environment. And its not clear to me how to specify which servers store the master documents and the replica documents.

**Comment by lvca** [comment]
@thejjmiller how many master servers in DC1 and DC2? Are you running on the cloud? If yes, which one?

**Comment by lvca** [comment]
No answer after a while, closing it.
