### ISSUE TITLE
Orientdb goes down once in a while

### ISSUE THREAD

**Issue by sivan123** [orientechnologies/orientdb#5684]
We are running version 2.1.2.
We see that the db goes down once in a while (around once or twice in a week), but does not throw any information on the logs. So unable to find what's causing this issue.
Last time this happened these were the last lines from the logs (orient-server.log)

2016-02-03 23:03:02:423 FINE  {db=AppDB} Read record #35:98 v.53 size=540 bytes [OLocalPaginatedStorage]
2016-02-03 23:03:02:673 FINE  [ONetworkProtocolHttpAbstract.execute] Requested: GET /listDatabases [ONetworkProtocolHttpDb

Another thing I noticed is that around 11 pm in the night for a couple of mins there is a lot of entries in the orient-server.log on a daily basis. Something like (FINE  {db=AppDB} Read record #52:5529460 v.1 size=315 bytes [OLocalPaginatedStorage])
What is this activity? Is there a built in scheduled db maintenance activity going on at this time? Could it be that the our normal application operations are clashing with this activity causing the db going down?

**Comment by sivan123** [comment]
Btw, I don't have the automatic back up enabled.

<handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter value="false" name="enabled"/>
                <parameter value="4h" name="delay"/>
                <parameter value="23:00:00" name="firstTime"/>
                <parameter value="backup" name="target.directory"/>
                <parameter value="${DBNAME}-${DATE:yyyyMMddHHmmss}.zip" name="target.fileName"/>
                <parameter value="9" name="compressionLevel"/>
                <parameter value="1048576" name="bufferSize"/>
                <parameter value="" name="db.include"/>
                <parameter value="" name="db.exclude"/>
            </parameters>
        </handler>

**Comment by laa** [comment]
@sivan123 Well do you have crash report files in bin, database or server root directory ?

**Comment by sivan123** [comment]
Hi @laa . Thanks for the quick response. Unfortunately I don't see any report as such in these directories. Also if you could help by what kind of file (file name/ extention) to look for I can quickly confirm.

**Comment by laa** [comment]
@sivan123 it should contain hs_err_pid in the file name.

**Comment by laa** [comment]
are you runing db on  linux ? may be you will also inspect error log ?

**Comment by laa** [comment]
Sometime linux kills process if there is no enough memory.

**Comment by sivan123** [comment]
@laa My bad. This runs in windows and is run by the windows task scheduler. Looks like the setting was 'on' to terminate the task if it runs for more than 3 days, that could have been the problem. Apologies, we could close this for now, I will let you know if it happens even after changing that setting.

**Comment by laa** [comment]
Cool: -)

On Thu, Feb 4, 2016, 17:48 Sivaprasad PS <notifications@github.com> wrote:

> @laa <https://github.com/laa> My bad. This runs in windows and is run by
> the windows task scheduler. Looks like the setting was 'on' to terminate
> the task if it runs for more than 3 days, that could have been the problem.
> Apologies, we could close this for now, I will let you know if it happens
> even after changing that setting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5684#issuecomment-179910124>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin
