### ISSUE TITLE
property of "server.database.path" is missing from 2.1.x

### ISSUE THREAD

**Issue by zhuobao** [orientechnologies/orientdb#5685]
The server.database.path is missing from version 2.1.x and the corresponding docs. is this property still working?

**Comment by maggiolo00** [comment]
hi @zhuobao 
yes it still works
It is not missing see here

http://orientdb.com/docs/2.1/DB-Server.html#change-the-server-s-database-directory

**Comment by zhuobao** [comment]
thx
