### ISSUE TITLE
lucune fulltext search not returning records

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5687]
I do have the record with name property as "Hampton Inn Yorkville"

The following lucene query not returning record. any idea?
select name from hotel where name lucene "Yorkville"

The following like query return the record. 
select name from hotel where name like "%Yorkville%"

**Comment by robfrank** [comment]
How do you define the lucene index on the given property? And which version of Orient are you using?

**Comment by martingg88** [comment]
sorry. it work again after i manually rebuild that index. faint..

**Comment by martingg88** [comment]
@robfrank what is the best solution to find similar phrase that are almost 80-90% close to each other?

**Comment by robfrank** [comment]
Hi, you can use all the trick Lucene gives to you to write a FT query:
https://lucene.apache.org/core/5_4_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description

For example you could use AND and OR, distance (the slop ~) or wild card. You can configure a different analyzer instead the StandardAnalyzer:
http://orientdb.com/docs/last/Full-Text-Index.html#analyzer
