### ISSUE TITLE
Try to create property with name 'id'

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#5688]
I try to create property with name 'Id'. 

Why the name is reserved?

фев 04, 2016 10:48:02 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=4 255MB (heap=1 803MB os=8 106MB disk=392 683MB)
Property: name (type=STRING)
Property: id (type=LONG)
фев 04, 2016 10:48:04 AM org.hibernate.datastore.ogm.orientdb.util.MemoryDBUtil prepareDb
SEVERE: Error
java.lang.IllegalArgumentException: Property key is reserved for all elements: id
        at com.tinkerpop.blueprints.util.ExceptionFactory.propertyKeyIdIsReserved(ExceptionFactory.java:44)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.validateProperty(OrientElement.java:579)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:196)
        at org.hibernate.datastore.ogm.orientdb.util.MemoryDBUtil.prepareDb(MemoryDBUtil.java:58)

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

It's a constraint in TinkerPop API (but not in OrientDB), you can disable it on the OrientGraph or on OrientGraphFactory setting `setStandardElementConstraints(false)`

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila 

Thank You very much!

**Comment by arunramkrish** [comment]
Hi @luigidellaquila
Why is this constraint applied even when we execute SQL command from console as part of CREATE EDGE command.
create edge myedge from <startrid> to <destrid> set id = 123 => this throws an error

Whereas, I am able to set id attribute as part of update, as in
update myedge set id = 123

**Comment by luigidellaquila** [comment]
Hi @arunramkrish 

CREATE EDGE command uses TinkerPop APIs under the hood, so it checks the constraint

Thanks

Luigi

**Comment by arunramkrish** [comment]
Hi @luigidellaquila 
Thanks a ton for your immediate response. In that case how do I set setStandardElementConstraints(false) for the console session?

thanks
K. Arun

**Comment by luigidellaquila** [comment]
Hi @arunramkrish 

you can just use this statement to change the DB settings:

```
alter database custom standardElementConstraints=false
```

Thanks

Luigi

**Comment by arunramkrish** [comment]
Thanks. Super.
I owe you back a documentation on northwind database in orientdb document
model and graph model - similar to one stated in www.sql2gremlin.com

thanks
K. Arun
