### ISSUE TITLE
Call function by JDBC

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#5691]
Now, JDBC not supports http://docs.oracle.com/javase/8/docs/api/java/sql/CallableStatement.html for call functions.

How I can call function of OrientDB by JDBC?

**Comment by schernolyas** [comment]
Hi @robfrank 

Have You progress?  Can I help You?

**Comment by robfrank** [comment]
Functions on orient return a single value, so you can use SELECT to call them:
```code
conn.createStatement()
        .execute("CREATE FUNCTION mySummer 'return a + b;'  PARAMETERS [a,b] IDEMPOTENT true LANGUAGE javascript ");

    ResultSet resultSet = conn.createStatement().executeQuery("SELECT  mySummer(1 ,1)");

```

do you really need Callable for your project or is it only a wish?

**Comment by schernolyas** [comment]
Hi @robfrank 

Calling function by "select" is enough for my current task.  I need return @rid of inserted record.  But .. support of Callable interface is right way because it is standart (part of JDBC)

**Comment by schernolyas** [comment]
migrated to native API
