### ISSUE TITLE
Transaction propagation is not working 

### ISSUE THREAD

**Issue by linus46** [orientechnologies/orientdb#5693]
```
function1(){
    OrientGraph db = factory.openDatabase() ; // which will give active graph on current thread
    db.begin();
    function2();
    // save some data 
    db.commit();
}
function2(){
    OrientGraph db = factory.openDatabase() ; // which will give active graph on current thread
    db.begin();
    // save some data 
    db.commit(); // this commit is saving the data into db 
}
```
here function2 commit is saving the data even though its part of function1 . 

sample code : 
https://gist.github.com/anonymous/54cd70a1e53d0381658a

**Comment by machak** [comment]
"factory.openDatabase() // which will give active graph on current thread"
Did you check this?
http://orientdb.com/docs/2.1/Transaction-propagation.html states:

The same instance of database should be used between methods.

**Comment by linus46** [comment]
yes , the db instances are same. inside openDatabase function i am checking for graph instance on thread 

        if(OrientGraph.getActiveGraph()==null || OrientGraph.getActiveGraph().isClosed())
        {
        	db = graphFactory.getTx();	
        }
        else {
        	db = (OrientGraph) OrientGraph.getActiveGraph();
        }

this will give same instance of database

**Comment by laa** [comment]
Fixed
