### ISSUE TITLE
Find References on link within an embedded object

### ISSUE THREAD

**Issue by AndreaSpan** [orientechnologies/orientdb#5694]
Hi, 

I'm using the "FIND REFERENCES [@rid]" orientdb query to find if an object is used before removing it. 

I'm facing a problem when the object is linked in a property of an embedded object, the "FIND REFERENCES" query doesn't catch this reference. 

Am I doing something wrong or is there a work around to get a similar query on embedded object? 

Thanks for you help, 

Andrea

**Comment by luigidellaquila** [comment]
Hi @AndreaSpan 

It seems to be a bug, I'll check it asap

Thanks

Luigi

**Comment by AndreaSpan** [comment]
Thank you for the quick answer Luigi !

**Comment by luigidellaquila** [comment]
Hi @AndreaSpan 

I just pushed a fix on 2.1.x branch, now I'm porting it to develop (2.2)

Thanks

Luigi

**Comment by a-unite** [comment]
Thank you, we needed this too.

**Comment by luigidellaquila** [comment]
Fixed in develop branch as well. Closing.
Please reopen if you see any other related problems

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @a-unite 

The fix will be released with 2.1.11, please let me know how urgent it is for you have the release, so that I can plan it

Thanks

Luigi

**Comment by a-unite** [comment]
Luigi, we are not using it directly, but need it sometimes during database refactoring (this is key future of our app) manual check up. 
So it is OK, and I will just postpone next "prophylaxsis" works till  2.1.11 release. 

Thank you very much!
