### ISSUE TITLE
error in conversion from Pojo to ODocument

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5695]
v2.1.9

Class A where there is a field x boolean 

A a = db.newInstance(A.class)
a.setX(false);
db.save(a);

the document saved in db has property x = null 
the problem seams just with false ==> null  and true ==> false

**Comment by tglman** [comment]
hi @publicocean0,

I've done this test case:

```
public class ObjectDatabaseTest {

public class SimpleWithBoolean {

  private boolean flagValue;

  public boolean isFlagValue() {
    return flagValue;
  }

  public void setFlagValue(boolean flagValue) {
    this.flagValue = flagValue;
  }

}

  private OObjectDatabaseTx db;

  @Before
  public void before() {
    db = new OObjectDatabaseTx("memory:plocal");
    db.create();
    db.getEntityManager().registerEntityClass(SimpleWithBoolean.class);
  }

  @After
  public void after() {
    db.drop();
  }

  @Test
  public void testSimpleBoolean() {
    SimpleWithBoolean val = db.newInstance(SimpleWithBoolean.class);
    val.setFlagValue(false);
    Object saved = db.save(val);
    ORID id = db.getIdentity(saved);

    db.getLocalCache().clear();
    SimpleWithBoolean val1 = db.load(id);
    assertEquals(false, val1.isFlagValue());
    ODocument rec = db.getUnderlying().load((ORID) id);

    assertEquals(false, rec.field("flagValue"));

  }

}
```

this pass with no problem, can you provide a failing test case ?

**Comment by publicocean0** [comment]
yes you are right.I posted above a wrong code for simplification. Sorry.  I was in transaction saving different entities. I will monitor if i see again but now I can t see again the error.Maybe it is a wrong issue. I close the issue because i can t tell you other info about this one. If i  see it again , i will notify here.
