### ISSUE TITLE
Distributed mode and linkset

### ISSUE THREAD

**Issue by luclanet** [orientechnologies/orientdb#5697]
Is there a bug on distributed mode and linkset?

I've tried to create this link

CREATE LINK status TYPE LINKSET FROM orders_status.id_order TO orders_list.id_order INVERSE

from a table orders_list and orders_status. It creates all links but nothing updates on insert/update, unless I recall the "create link" query.

I've tried also with SELECT and NOCACHE option. Nothing changed.

**Comment by lvca** [comment]
Could you try with RIDBAG type please?

**Comment by luclanet** [comment]
What do you mean? How I've to do that?

**Comment by smolinari** [comment]
Maybe use the LinkBag type?

http://orientdb.com/docs/2.1/Types.html

Scott

**Comment by luclanet** [comment]
No idea of what to do. Anyway another info:

Working with this SELECT

select * from orders_list WHERE status[type_status] not in 'ready'

The results are correct but not the status field that again gives error.

**Comment by lvca** [comment]
Which error? Please report it.

**Comment by lvca** [comment]
Closing after no response. In case the issue is still open, please reopen/comment this. Thanks.
