### ISSUE TITLE
Missing tutorial about test driven development.

### ISSUE THREAD

**Issue by urosjarc** [orientechnologies/orientdb#5706]
I would really like in tutorial some good instructions about how to
create best practice test driven development with orientdb, or how to make
unittesting on queryes / functions.

**Comment by schernolyas** [comment]
Hi!

I do same.  I can see my examples. I develop Hibernate OGM for OrientDB.

See https://github.com/schernolyas/hibernate-ogm/blob/OGM-855-OrientDB/orientdb/src/test/java/org/hibernate/datastore/ogm/orientdb/OrientDBSimpleTest.java

**Comment by lvca** [comment]
@schernolyas your Hibernate OGM plugin is cool! What's the status of it?

**Comment by urosjarc** [comment]
@schernolyas Not bad, it seems that you are quite knowable obout testing this things. Would you be so kind to add it in tutorial every thing that you have discover while dealing with orientdb in testing environment before some official tutorial is produced by authors. You will be in great help to all of us! :+1:

**Comment by schernolyas** [comment]
Hi @urosjarc 

All very simple.  Just create in-memory instance of OrientDB   and  welcome to OrientDB world.
For instance,, You can see my example.  I use the way for unit testing Hibernate OGM module.

**Comment by schernolyas** [comment]
HI @lvca 

Status is:
1) work in Java SE with one connection by JDBC
2) CRUD for simple entities (entites without associations) is realised
3) Schema generation is realised (current schema not verified yet)

Now I am working  on CRUD with associations (support @OneToMany annotations ans etc)

**Comment by lvca** [comment]
Nice roadmap. I think a lot of users would be happy using something more standard than OrientDB's Object API.

**Comment by schernolyas** [comment]
@lvca 

A lot of users use Hibernate in Java EE environment.  For it , OrientDB JDBC  API must be improved

**Comment by lvca** [comment]
I hope nobody would use OrientDB JDBC API when he develop an application with OrientDB. The JDBC driver was born to allow to connect to OrientDB from all the sw that support JDBC. But it's limited in features and performance.

**Comment by schernolyas** [comment]
@lvca 

Java world uses standards and based on standarts. And ... JDBC is standard and all DBMS providers must provide JDBC driver for own database even if native driver faster than jdbc driver. 

Otherwise  only DBMS provider will uses own product.

Problem with connection pool in Wildfly is example of it.

**Comment by schernolyas** [comment]
@lvca 

Please  read http://www.javaworld.com/article/2071834/build-ci-sdlc/pool-resources-using-apache-s-commons-pool-framework.html
