### ISSUE TITLE
Cannot open local storage with mode=rw

### ISSUE THREAD

**Issue by efesaid** [orientechnologies/orientdb#5707]
Hi all,

I am trying to connect to server with remote mode [as mentioned troubleshooting page](https://github.com/orientechnologies/orientdb-docs/blob/master/Troubleshooting.md#error-comorientechnologiesorientcoreexceptionostorageexception-cannot-open-local-storage-tmpdatabasesdemo-with-moderw) but no luck.

I am checking with `ps aux | grep -i orient` and `ps aux | grep -i server.sh ` if there is any other working instance but there is not.

I am stopping and starting server and then trying to connect via console or web but no luck. Still same error.

> Connecting to database [remote:xxx.xxx.xxx.xxx/ViaApi] with user 'admin'...
> Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb-community-2.1.8/databases/DemoDB' with mode=rw
> 
> Error: java.lang.NullPointerException

I am checking with `lsof +D /opt/orientdb-community-2.1.8/databases/DemoDB -t ` but i am getting only one PID.

Any idea?

Thanks.

**Comment by smolinari** [comment]
Check this out.

https://github.com/orientechnologies/orientdb-docs/blob/master/Troubleshooting.md#error-comorientechnologiesorientcoreexceptionostorageexception-cannot-open-local-storage-tmpdatabasesdemo-with-moderw

Scott

**Comment by laa** [comment]
Hi, could you provide full stack trace, not only exception itself.

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.

**Comment by nishantkumar1292** [comment]
I am also facing the same issue. 
`Caused by: com.orientechnologies.orient.core.exception.OStorageException: Can not open storage it is acquired by other process
	DB name="test"`
Is this issue still there or is it solved?

**Comment by laa** [comment]
@nishantkumar1292 two processes by design can not open the same database. But why you have it in ETL that is a good question. Could you open separate issue in ETL project?

**Comment by nishantkumar1292** [comment]
I have a Rails application which communicates with OrientDB and renders many views and logics. 
However I would like to do ETL on this database and for this I need to create json files and run data insertion. But I am getting the above error.
