### ISSUE TITLE
Database does not open (no upgrade was made)

### ISSUE THREAD

**Issue by misamanjarres** [orientechnologies/orientdb#5713]
Hello,

I am not able to open my database via console or studio and get the following error: 

```
Connecting to database [remote:localhost/DB] with user 'root'...
Error: com.orientechnologies.common.exception.OException: Error on creation of shared resource

Error: com.orientechnologies.orient.core.exception.OSchemaException: Cannot add base class 'Dining', because of parameter conflict: zip (type=INTEGER) vs zip (type=INTEGER)
```

This happened over night. I made no changes to the database nor to the server. I am unable to open the database to back it up or export it to adjust the json.

Thanks

**Comment by laa** [comment]
Hi,
Could you provide full stack trace ?

**Comment by tglman** [comment]
Hi @misamnjarres,

which version are you running with ? about the exception that you are seening we fixed something similar few hotfix ago, but it should not happen on database open.

**Comment by misamanjarres** [comment]
I had to fix the issue quickly so I rebuilt the database. I no longer have the tracebacks.
