### ISSUE TITLE
Inconsistent behavior when querying with explicit gremlin

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#5714]
With OrientDB 2.1.9 and a database that has some data (both vertices and edges, specifics are not relevant):

```
select * from V where count(gremlin('g.V.next()')) = 0
```

This returns no records.

```
select * from V where count(gremlin('g.V.next()')) > 0
```

This returns all the vertices in the database.

```
g.V.next()
```

In Studio, this returns one vertex.

```
select gremlin('g.V.next()')
```

This throws:

```
java.lang.IllegalArgumentException: Cannot determine the graph element type because the document class is null. Probably this is a projection, use the EXPAND() function
```

```
select count(gremlin('g.V.next()'))
```

This throws the same error as above.

```
select expand(gremlin('g.V.next()'))
```

This returns no records.

There are several problems here:
- The queries are internally inconsistent -- the count can't be both invalid and greater than 0.
- The perfectly valid `select gremlin(...)` query doesn't work when the gremlin query entered directly works fine.
- I'd expect `expand` to throw an error if the argument it's called with is invalid, not return no records and swallow the problem.

**Comment by obi1kenobi** [comment]
One more problem:
```
SELECT gremlin(current.both()) FROM V
```

Note the missing quotes around the body of the gremlin query. This causes a null-pointer exception, which suggests there is a bug in the parser.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I just checked it in latest stable and it seems to work fine.

I also pushed a fix for the NullPointer

Closing, thanks!

Luigi

**Comment by santo-it** [comment]
Fix is https://github.com/orientechnologies/orientdb/commit/bb536f5334e4c5c5cdf4e41fb4f6033c58b6318c. Noted in the [Release Notes](https://github.com/orientechnologies/orientdb/commit/bb536f5334e4c5c5cdf4e41fb4f6033c58b6318c)
