### ISSUE TITLE
Edge creation increments both the vertex version.

### ISSUE THREAD

**Issue by Ashendra** [orientechnologies/orientdb#5718]
Using orientdb 2.1.5
 
Connecting to orientdb server with java client, have set 
-DridBag.embeddedToSbtreeBonsaiThreshold=-1, both on client side as well as on the server side. But still at every edge creation or deletion the vertex version changes.

After debugging, what I have found, the client always sends both the vertex records with operation type ORecordOperation.UPDATED . On the server side, the version is not incremented only in case when the operation type is ORecordOperation.CREATED or the content of the record has not changed.

Client side code which add entries to the transaction

OrientVertex.java method addEdge, Lines - 971-982

    // OUT-VERTEX ---> IN-VERTEX/EDGE
    createLink(graph, outDocument, to, outFieldName);

    // IN-VERTEX ---> OUT-VERTEX/EDGE
    createLink(graph, inDocument, from, inFieldName);

    if (graph != null) {
      edge.save(iClusterName);
      inDocument.save();
      outDocument.save();
    }

Server Side code which increments the version 
OAbstractPaginatedStorage.java, method commitEntry, Lines 2443-2454

      case ORecordOperation.UPDATED: {
        final byte[] stream = rec.toStream();
        if (stream == null) {
          OLogManager.instance().warn(this, "Null serialization on committing updated record %s in transaction", rid);
          break;
        }

        rec.getRecordVersion().copyFrom(doUpdateRecord(rid, ORecordInternal.isContentChanged(rec), stream, rec.getRecordVersion(),
            ORecordInternal.getRecordType(rec), null, cluster).getResult());
        break;
      }

Part of code, which do not increment version on OperationType as ORecordOperation.CREATED
OAbstractPaginatedStorage.java, method commitEntry, Lines 2414-2443

     case ORecordOperation.CREATED: {
        // CHECK 2 TIMES TO ASSURE THAT IT'S A CREATE OR AN UPDATE BASED ON RECURSIVE TO-STREAM METHOD

        final byte[] stream = rec.toStream();
        if (stream == null) {
          OLogManager.instance().warn(this, "Null serialization on committing new record %s in transaction", rid);
          break;
        }
        final ORecordId oldRID = rid.isNew() ? rid.copy() : rid;

        if (rid.isNew()) {
          rid = rid.copy();
          rid.clusterId = cluster.getId();
          final OPhysicalPosition ppos;

          final byte recordType = ORecordInternal.getRecordType(rec);
          ppos = doCreateRecord(rid, stream, rec.getRecordVersion(), recordType, null, cluster, new OPhysicalPosition(recordType))
              .getResult();

          rid.clusterPosition = ppos.clusterPosition;
          rec.getRecordVersion().copyFrom(ppos.recordVersion);
          clientTx.updateIdentityAfterCommit(oldRID, rid);
        } else {
          // USE -2 AS VESION TO AVOID INCREMENTING THE VERSION
          rec.getRecordVersion().copyFrom(updateRecord(rid, ORecordInternal.isContentChanged(rec), stream, new OSimpleVersion(-2),
              ORecordInternal.getRecordType(rec), -1, null).getResult());
        }
        break;
      }

Further debugging,
The record is send from the client over the network with content changed as false.
But on the server side, when the records are being merged, the following piece of code, marks the _contentChanged to true, despite it has been sent false from the server.

OTransactionOptimisticProxy.java method begin Lines - 139- 164

      for (Entry<ORID, ORecordOperation> entry : tempEntries.entrySet()) {

        if (entry.getValue().type == ORecordOperation.UPDATED) {
          // SPECIAL CASE FOR UPDATE: WE NEED TO LOAD THE RECORD AND APPLY CHANGES TO GET WORKING HOOKS (LIKE INDEXES)

          final ORecord record = entry.getValue().record.getRecord();
          final ORecord loadedRecord = record.getIdentity().copy().getRecord();
          if (loadedRecord == null)
            throw new ORecordNotFoundException(record.getIdentity().toString());

          if (ORecordInternal.getRecordType(loadedRecord) == ODocument.RECORD_TYPE
              && ORecordInternal.getRecordType(loadedRecord) == ORecordInternal.getRecordType(record)) {
            ((ODocument) loadedRecord).merge((ODocument) record, false, false);
            ((ODocument) loadedRecord).setDirty();

            loadedRecord.getRecordVersion().copyFrom(record.getRecordVersion());
            entry.getValue().record = loadedRecord;

            // SAVE THE RECORD TO RETRIEVE THEM FOR THE NEW VERSIONS TO SEND BACK TO THE REQUESTER
            updatedRecords.put((ORecordId) entry.getKey(), entry.getValue().getRecord());

          }
        }

        addRecord(entry.getValue().getRecord(), entry.getValue().type, null);
      }

Internally if you see the statement in ((ODocument) loadedRecord).setDirty();, call super ORecordAbstract

      public ORecordAbstract setDirty() {
        if (!_dirty && _status != STATUS.UNMARSHALLING) {
          _dirty = true;
          _source = null;
        }
    
        _contentChanged = true;
        return this;
      }
which marks the contentChanged to true.

Because of this only the version is always incremented in case of an edge addition. I can contribute to fix this. But not sure what can be side effects of these.

Can someone look into this.

**Comment by Ashendra** [comment]
Commented the line 
    ((ODocument) loadedRecord).setDirty();

Build the sources again and now when I'm running the server. The version for the vertices are not incremented. All the test cases are passing as well. Is this correct solution.

**Comment by tglman** [comment]
hi @Ashendra,

Yes could be the correct solution, can you point me to the exact row that you changed ?

**Comment by Ashendra** [comment]
Diff patch 
diff --git a/server/src/main/java/com/orientechnologies/orient/server/tx/OTransactionOptimisticProxy.java b/server/src/main/java/com/orientechnologies/orient/server/tx/OTransactionO
index a71cf41..6b130cd 100755
   --- a/server/src/main/java/com/orientechnologies/orient/server/tx/OTransactionOptimisticProxy.java
+++ b/server/src/main/java/com/orientechnologies/orient/server/tx/OTransactionOptimisticProxy.java
@@ -19,10 +19,6 @@
  */
 package com.orientechnologies.orient.server.tx;
 
-import java.io.IOException;
-import java.util.*;
-import java.util.Map.Entry;
-
 import com.orientechnologies.common.exception.OException;
 import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
 import com.orientechnologies.orient.core.db.record.OIdentifiable;
@@ -49,6 +45,10 @@ import com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary;
 import com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryProtocol;
 import com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary;
 
+import java.io.IOException;
+import java.util.*;
+import java.util.Map.Entry;
+
 public class OTransactionOptimisticProxy extends OTransactionOptimistic {
   private final Map<ORID, ORecordOperation> tempEntries    = new LinkedHashMap<ORID, ORecordOperation>();
   private final Map<ORecordId, ORecord>     createdRecords = new HashMap<ORecordId, ORecord>();
@@ -149,7 +149,6 @@ public class OTransactionOptimisticProxy extends OTransactionOptimistic {
           if (ORecordInternal.getRecordType(loadedRecord) == ODocument.RECORD_TYPE
               && ORecordInternal.getRecordType(loadedRecord) == ORecordInternal.getRecordType(record)) {
             ((ODocument) loadedRecord).merge((ODocument) record, false, false);
-            ((ODocument) loadedRecord).setDirty();
 
             loadedRecord.getRecordVersion().copyFrom(record.getRecordVersion());
             entry.getValue().record = loadedRecord;

**Comment by tglman** [comment]
hi @Ashendra,

yes the setDirty was not completely correct, anyway what was needed is managed the dirty no changed flag, i fixed it and pushed, will be out with the next hotfix, thank you very much for the so detailed segnalation.

this was already fixed in 2.2
