### ISSUE TITLE
bug in lucene select

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5719]
version 2.10

<pre>
index: c.name_list  FULLTEXT    ["name","list"]     LUCENE 

insert into c set list = ['a','b'] 

select from index:c.name_list where key  LUCENE "list:b" 

----+------+----------------------------+-----
#   |@CLASS|key                         |rid  
----+------+----------------------------+-----
0   |null  |OCompositeKey{keys=[list:b]}|#56:1
----+------+----------------------------+-----

select from index:c.name_list where key  LUCENE "list:a" 
0 item(s) found. Query executed in 0.002 sec(s).

</pre>

It seams it add just last element. In lucene arrays are handled natevely adding many fields with same name as many elements

**Comment by smolinari** [comment]
Is it correct that a lucene index should be able to index lists?

I also just tried it with Studio and it doesn't work. I get. 

`com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot evaluate lucene condition without index configuration.`

With the index set on a property of an embedded list of strings.

Scott

**Comment by publicocean0** [comment]
Lucene is a index engine designed for indexing unstructured data. You can index what you want.
It is used above all for documental services. A general document contains a unstructured structure. It is this the reason of its success. So the answer is naturally yes. 
I saw that error mentioned by you. But it is another bug. It appear if you create a index using console. I skipped it using java or gui studio (not command)
In addition i tried today to give a look to lucene module for patching it, because in lucene to index a list requires 3 instructions, but i discovered that lucene manager class splits a list in many updates (i think many documents). I lose few time in the investigation, i will give a look in spare time, it seams it creates duplications in index.

**Comment by publicocean0** [comment]
Other bug found: CREATE INDEX Manual2 FULLTEXT ENGINE LUCENE gives NullPointerException

**Comment by publicocean0** [comment]
Other bug found : select expand(rid) from index:A.lucene where key LUCENE "producer:'#33:295'"

**Comment by robfrank** [comment]
verified with tests. see coomits
