### ISSUE TITLE
Infrastructure to avoid OOM in ODB

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5720]
Currently we have issues in 3 places.
1. SQL query (the top priority)
2. Client side transaction proxy
3. Collection of transaction changes inside of core.

The problem is that data which participates in processes listed above (with exception of first item) are not concentrated in single place. 

So following approach is proposed: 
1. Create LinkedList, Map, SortedMap implementations which will be referenced only through soft link. 
2. There will be two implementations, typical (heap based), which will be wrapped into soft link and disk cache based.
3. The same single reference queue will be associated with all soft links.
4. During processing of data, at every access to collections, value of  soft link and presence of links in reference queue will be checked (reference queue head is volatile which means read barrier which is typically free on many CPU architectures  so it should not affect system performance). If soft link is null or reference queue is not empty , exception is thrown and process is repeated with disk cache based collections.

It will allow us to absolutely safely with minimal performance overhead avoid OOM exception on any heap configuration.

If issue with sql  queries may be fixed after implementation of https://github.com/orientechnologies/orientdb/issues/5504 , for implementation of the same OOM free behaviour on tx side we need also implement  https://github.com/orientechnologies/orientdb/issues/4212 issue.

**Comment by luigidellaquila** [comment]
Having this kind of infrastructure is a must, so +100.
My only concern is about the relying on soft links and the double processing. Wouldn't it be better to have a single memory, similar to current off-heap cache, that is flushed to disk when memory is not enough? I guess these structures, like the disk cache, will only handle binary data (no POJOs), so the query executor will have to be adapted for this

**Comment by laa** [comment]
@luigidellaquila There is no 100% way to know when there is no enough heap in Java, we have tried many times without success.

**Comment by luigidellaquila** [comment]
@laa this is why I'd avoid using heap ;-)

**Comment by laa** [comment]
@luigidellaquila in such case all becomes much slower. We will use hash maps with additional overhead with serialization even for simple all in memory cases instead of direct references. Situations when we have OOM happens are not very often, so I think such approach is acceptable trade off. But how you estimate priority of this issue for 3.0 ?

**Comment by luigidellaquila** [comment]
Ok, it makes sense.
Probably having a full off-heap approach will make sense if we implement full binary queries, so that we work only on byte arrays and we never (de)serialize ODocuments

**Comment by luigidellaquila** [comment]
about the priority, IMHO it's very high, but again, it's just my feeling

**Comment by laa** [comment]
I think we will decrease consumption of memory in our core transaction using following mechanics.

1. After https://github.com/orientechnologies/orientdb/issues/7684 we will have recorded all items which we change during the transaction so we can lock them in order to prevent any deadlocks.
2. We will split our TX into two TXs not ideal but will work, in the first phase we will pre allocate RIDs for new records. Those transactions will be not reversible but durable. Unfortunately, we can not get those RIDs back we will keep them booked even after rollback.
2. We will lock all rids and all keys of indexes. Elements which are going to be locked will be presented as  keys <component name, (rid or key)>  .
3. We will write the content of OTransactionOptimistic into the WAL before doing any changes.
4. We will perform operations on components as we do now in our current transaction implementation But each component will have its own transaction so all component operations will be durable.
5. If transaction will be committed we will write commit record at the end of component operations or will write rollback record and will perform a business rollback. All operations will be rolled-back by undoing operations.  
6. Mechanics of restore/rollback of transactions after a crash should be changed accordingly.

This solution is not ideal but we can implement it very quickly and it will allow us to use key/record locking semantic which is vitally needed by distributed storage.

P.S. In future we plan to implement durable (without WAL) "append only" components with big data support. Because this flow will not be dramatically changed after implementation of those components that is a good step forward anyway.

**Comment by laa** [comment]
One small update we will write the content of OTransactionOptimistic into WAL not before we will start operations, but inside of components just before we will do an operation when we already have a current value of data to be updated. It will save us from a double reading of values for rollback operations.

**Comment by laa** [comment]
We also need to change our WAL truncation strategy.

**Comment by laa** [comment]
The one more difference between current transactions and component transactions would be that current component transactions will use in place updates with rollbacks during restore after a crash but current transactions use deferred updates strategy.
