### ISSUE TITLE
Java Client side local cache is not used, connecting over remote

### ISSUE THREAD

**Issue by Ashendra** [orientechnologies/orientdb#5721]
Using orientdb 2.1.5

Using the java client to connect to orientdb remote server. I observe that every operation is served by the server. The local cache is not used at all. I have explicitly tried enabling it from 

    -Dcache.local.enabled=true -Dstorage.diskCache.bufferSize=4096

But jmx beans says 0 bytes used , got the value from com.orientechnologies.orient.core.storage.cache.local.O2QCacheMXBean.UsedMemory

How do I enable it/or it this some bug?

**Comment by laa** [comment]
Hi, local cache is heap memory session scope cache it is not related to O2QCacheMXBean.
Which is server resident cache for disk cached data.

**Comment by Ashendra** [comment]
My understanding from http://orientdb.com/docs/2.0/orientdb.wiki/Caching.html was that, this would build a client side cache, which would be used to load record which are frequently used.

**Comment by laa** [comment]
It is 2.0 documentation. That is 2.1
