### ISSUE TITLE
Import database in memory and use it as graph

### ISSUE THREAD

**Issue by urosjarc** [orientechnologies/orientdb#5723]
This is full issue: http://stackoverflow.com/questions/35391496/orientdb-import-database-in-memory-and-use-it-as-graph

**Comment by maggiolo00** [comment]
hi @urosjarc 

do you have a simple database to reproduce it?

**Comment by maggiolo00** [comment]
hi @urosjarc 

have you solved the issue?

**Comment by urosjarc** [comment]
Yes... Thanx
