### ISSUE TITLE
OObjectDatabasePool deprecated - Registered POJO classes for aquired connection

### ISSUE THREAD

**Issue by randikaf** [orientechnologies/orientdb#5728]
I'm using orientdb 2.1.9. Since the OObjectDatabasePool has been deprecated and as mentioned in this issue: #4745, this can be overcome by calling the constructor as OObjectDatabaseTx(ODatabaseDocumentTx iDatabase). But then all registered classes using db.getEntityManager().registerEntityClasses(modelPackage) will not available for the new OObjectDatabaseTx . How can I register my domain classes for a pool which returns a connection with all registered classes when calls pool.aquire()?

**Comment by randikaf** [comment]
@tglman , @luigidellaquila This issue has been raised a month ago, appreciate if you or someone can comment on it?

**Comment by zerovian** [comment]
Use the updated pool type like this:

OPartitionedDatabasePoolFactory poolFactory = new OPartitionedDatabasePoolFactory(getPoolSize());
...
OPartitionedDatabasePool dbPool = poolFactory.get(getEmbeddedDBURI(), getUserName(), getPassword());

Then if you need object access fetch a connection from the pool and wrap it in the object database type like this:

ODatabaseDocumentTx docDb = dbPool.acquire();
OObjectDatabaseTx databaseConnection = new OObjectDatabaseTx(docDb);

Then just close() the OObjectDatabaseTx when you're done with it which will release the underlying ODatabaseDocumentTx back to the pool.

**Comment by maseev** [comment]
I've just run into the same problem. @zerovian your approach looks very expensive regarding creating a lot of objects under a heavy load. It will certainly trigger GC a lot as a result.
Is there any way I can create an object database connection pool without wrapping a ODocumentDatabaseTx connection?
