### ISSUE TITLE
Federated databases [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#573]
Now RID is unique per database. Its size is of 10 bytes and is composed by:
- clusterId = 2 bytes
- recordPosition = 8 bytes

Example: #10:232323

To support "federated database" systems (http://en.wikipedia.org/wiki/Federated_database_system) it would be nice prefixing the RID with the server name as a unique id.

Example:

`#London7:10:232323`

To identify the record inside the server called as "London7". Node names could reside in `orientdb-server-config.xml` as a parameter of `ODistributedServerManager` handler. 

Example:

``` xml
    <handler class="com.orientechnologies.orient.server.handler.distributed.ODistributedServerManager">
      <parameters>
        <parameter name="server.name" value="London7"/>
        ...
      </parameters>
    </handler>
```

Obviously a shorter name is better. you could also use numbers to reduce disk space, RAM and network traffic. Example:

`#7:10:232323`

In this case you could create a federated configuration with links among databases.

**Comment by cwaldron** [comment]
I saw in another thread that the cluster portion of the RID is going to be extend.  What will the eventual byte size of the cluster portion be when extended?

**Comment by lvca** [comment]
We're discussing to extend it from 2^15 to 2^31.

**Comment by smolinari** [comment]
So that would mean a single database could hold up to 2147483648 clusters? :sunglasses: 

Scott

**Comment by lvca** [comment]
Exactly, then we should see the impact on File System about having so many files.

**Comment by smolinari** [comment]
I would also imagine it depends on the file system? I don't think the number of files is an issue. More of a problem is the number of files opened at once. 

Does OrientDB recommend any certain file system and configuration?

Scott

**Comment by lvca** [comment]
If OS allows, OrientDB has no limitation on number of files opened. But we have to check on this use case.

**Comment by wouterv** [comment]
So #1930 makes a good chance of getting implemented?

**Comment by lvca** [comment]
Yes. It's scheduled for 2.2, this summer.

**Comment by wouterv** [comment]
If github had a "like" button, I would have clicked it

**Comment by smolinari** [comment]
It seems to the popular thing to do it post a :+1: 

@lvca , you missed my question about file systems and setting. Any recommendations for best performance?

Scott

**Comment by lvca** [comment]
@smolinari which question? Is in this issue?

**Comment by smolinari** [comment]
Does OrientDB recommend any certain file system and configuration for best performance?

I ask, because, for instance, MongoDB recommends XFS or EXT4. 

http://docs.mongodb.org/manual/administration/production-notes/#kernel-and-file-systems 

They also recommend to raise the ulimit value. 

http://docs.mongodb.org/manual/administration/production-notes/#recommended-configuration

Scott

**Comment by lvca** [comment]
We don't have a page like, but you can find some tuning information on: http://orientdb.com/docs/last/Performance-Tuning.html. Look also at the usage on ZFS: http://carloprad.blogspot.it/2014/03/orientdb-on-zfs-performance-analysis.html

**Comment by smolinari** [comment]
I saw both pages already. ZFS, unfortunately, isn't a standard filesystem for Linux. 

Is it a good idea to also turn off atime for an ODB node?

Scott

**Comment by jpstrikesback** [comment]
:+1:
Is this still on the roadmap for 2.2?

**Comment by lvca** [comment]
it's in 3.2 (Look at milestone field)

**Comment by jpstrikesback** [comment]
Ah indeed, thanks!
