### ISSUE TITLE
OrientDB2.1.x Chinese Document is upcoming!

### ISSUE THREAD

**Issue by BlueGemini** [orientechnologies/orientdb#5732]
I'm working on translating the orientdb 2.1.x docoment into Chinese.The docment git book url is https://www.gitbook.com/book/orientdb-cn/doc2-1-x/details.If you find some translation problems,you can send email to me.My email is 52lessismore@gmail.com.Welcom you to join us!

**Comment by lvca** [comment]
Page not found.

**Comment by smolinari** [comment]
https://orientdb-cn.gitbooks.io/doc2-1-x/content/

From someone who knows about how hard it is to translate (and do it well) and even though I don't speak Chinese, I can say, great work! Just hope you aren't using some automation, but doing it "the right way". :smile: :wink:  

Scott

**Comment by BlueGemini** [comment]
Network error? I'm sure that my colleague can open it. The url is gitbook
open url.

2016-02-16 15:23 GMT+08:00 Luca Garulli <notifications@github.com>:

**Comment by BlueGemini** [comment]
https://github.com/orientdb-cn/orientdb-docs

**Comment by lvca** [comment]
I can see it, that's great! As @smolinari said, did you use an automatic conversion tool?

**Comment by BlueGemini** [comment]
I'm working in Qunar. I'm trying to use orientDB in my system. I will never
use automatic conversion tool.

2016-02-16 16:59 GMT+08:00 Luca Garulli <notifications@github.com>:

**Comment by lvca** [comment]
@BlueGemini it would be nice having it under the official docs, maybe with a select box where you can choose between English or Chinese. I don't know how to do that with GitBook.

**Comment by lvca** [comment]
@BlueGemini The best would be having your docs under a branch of the official doc. WDYT?
