### ISSUE TITLE
probable bug in sql function

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5736]
Sorry maybe i dont understand correctly the way for passing parameters in a sql function 
but it seams a bug considering different attempts executed
language: sql
function test(a)
body : return $a;

select test(1)

it dont return anything.

body : return a; 
exception : so it implies $a is correct. 

body : return 1;
it returns correctly result.
I hope i submited a bug usefull to fix to loveable orientdb:)

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

It seems to work fine here (v.2.2). If there was a bug, it's already fixed.

Maybe the problem was due to the `$`

I defined the function with input param = `a` and with body `return a;`

Thanks

Luigi
