### ISSUE TITLE
factory exist() check is returning true if the username password is wrong.

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#5738]
Version: orientdb-community-2.1.9

When the username / password is wrong while creating a factory the factory object is returned. also the exists method returns true. Subsequent database operations on the factory is failing.

If the user name / password is wrong then the factory should not be returned or the exist should return false. or there should be some way of telling that the login operation failed. 

below is the code example code that fails to report bad user name or password:
```
OrientGraphFactory factory = new OrientGraphFactory("plocal:"c:/databasefiles/domain,"steve","wrongpass").setupPool(1, 1);
if(factory.exists()) {
  return factory;
}
```

below is the Workaround:
```
OrientGraphFactory factory = new OrientGraphFactory("plocal:"c:/databasefiles/domain,"steve","wrongpass").setupPool(1, 1);
if(factory.exists()) {
 try{
  OrientGraph graph=factory.getTx();
  graph.commit();
 } catch (Exception ex) {
   // user name password was not valid
    return null;
}
  return factory;
}
```

**Comment by tglman** [comment]
hi @smallik,

for check that a database exist in case of plocal/memory you don't actually need authentication, that why il not fail, it will return false in case the database not exist, for remote case you need authentication and you need a different api.

i don't think with the current api this is a wrong behaviour.

**Comment by smallik** [comment]
@tglman , thanks for checking on this issue.

I tested this code again and yes it returns false if the database is wrong, regardless if user name password is wrong or not. So you are correct. 

If this gets documented it will help others. 

Also if this is considered as a feature request it would be great. In my case I need it, as I am dependent on orientdb authentication and I am running in embedded mode. Maybe we can have a boolean parameter to the Factory method like isCheckForUsernamePassword. Or a similar approach. I am sure this feature will help projects that are totally dependent on orientdb authentication. Also I think depending on orientdb for authentication is a good path to take, given the features set of orientdb.
 
Note: we do have a workaround for this now as documented in this issue. and it solves the problem.

**Comment by tglman** [comment]
hi @smallik,

i added a comment on the javadoc, anyway we may review a bit the database manipulation api in future that include also this api, we will consider also this case.

closing for now.
