### ISSUE TITLE
Crash test was failed

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5739]
http://helios.orientdb.com/view/develop/job/orientdb-develop-crash-tests/lastCompletedBuild/com.orientechnologies$orientdb-server/testReport/com.orientechnologies.orient.core.storage.impl.local.paginated/LocalPaginatedStorageSmallCacheBigRecordsCrashRestoreIT/testDocumentCreation/

**Comment by robfrank** [comment]
Hi Andrey, I just pushed LocalPaginatedStorageSmallCacheBigRecordsCrashRestoreIT with few modification to be able to debug: single thread AND timeout is 1 minute.
The test fails on the first record compared. I added output to show the two documents stored on base and test DBs, and apart for the id, other fields are completely different. Let me know If I can do more to fix this tests. Thanks

**Comment by laa** [comment]
Hi Roberto,

We will take care of it.

**Comment by laa** [comment]
Fixed for now. But I will create set of issues for few specific tests for 3.0 version.
