### ISSUE TITLE
standard output was not restored in console process after CTRL+C

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5740]
i was in console blocked and i press CTRL+C for forcing the exit. 
process exit correctly , but then in terminal i can t see what i m writing. 
test is simple. Press CTRL+C in console. I use linux terminal.

**Comment by sinfex** [comment]
As a workaround, after killing the console run `stty echo` to re-enable terminal echo-back.

**Comment by publicocean0** [comment]
thanks for workaround :)
