### ISSUE TITLE
UNIQUE_HASH_INDEX uses SBTREE engine?

### ISSUE THREAD

**Issue by matt-dyer** [orientechnologies/orientdb#5741]
After creating a UNIQUE_HASH_INDEX, the expected engine type was HASHINDEX, however the engine type listed is SBTREE.  Is this just a labeling issue/bug, or is the actual engine used SBTREE?

Thanks!

**Comment by maggiolo00** [comment]
hi @matt-dyer 
it is just a labeling issue
The engine is HASHINDEX
https://github.com/orientechnologies/orientdb/issues/5297
