### ISSUE TITLE
Huge difference between create edge and update vertex property

### ISSUE THREAD

**Issue by Daniel-Valliere** [orientechnologies/orientdb#5744]
It seems that the amount of read an application does has a significant impact on the number of edges creation and deletion it can do per second.
In summary:
If an application performs read as fast as possible while deleting and creating edges, it performs 270K read per second and only 150 edges deletion + creation per second.
If an application restrict itself to only 17K read per second, it can perform about 1200 edges deletion + creation per second.

On the other hand, if the application performs read as fast as possible while updating a vertex property, it performs 300K read per second and 30K vertex update per second.

Is it expected to have such a poor edge creation/deletion performance compared to vertex update performance when high amount of reads are performed? Is there some configuration to make things better? We end up considering avoiding edge creation whenever possible to get better performance.

See below for details about the test application:
I have a java test program that creates a new plocal OrientDB, creates 10 vertex classes and 10 edge classes, create a number of vertices and edges and then spawn a number of test threads that all work on that database.
Each test thread loops and in each loops, they perform 10 db read and queue one db write task that gets executed by a single thread (all test threads use the same write thread since the write affects always the same vertex class; using multiple write thread changes nothing in performance).
Reads are simple. Nine of the queries only navigate one edge to get vertices (tinkerpop). One query hops 2 edges (gremlin).
The write is either 1) edge deletion + edge creation or 2) a simple vertex property update. 
I have performance measurements for 3 configurations:
1) the application just reads: performs about 330K reads per second which is very good.
2) the application do the "vertex update" DB write. Read drops to about 300K per seconds and, the write thread keeps up with the read thread (30K writes per second)
3) the application do the "delete edge + create edge" DB write: the read threads drops to 260K reads per second, not too bad, but the write thread lags behind with only 150 write per second.

Is it expected that the delete / create edge is 200 times slower that a single vertex update (150 / second vs 30K) when reads are performed at full speed?

Note that if I configure the operation to decrease the number of reads per second to about 17K / seconds, the "delete edge + create edge" performance increases to about 1200 per second which is still not keeping up with the reads (would need to reach 1700 per second).

Thanks,
Daniel

**Comment by lvca** [comment]
What OrientDB version? Please could you try using OrientDB v2.2.0-SNAPSHOT without transactions? You should see much better performance.

**Comment by Daniel-Valliere** [comment]
I've tried version 2.2.0-SNAPSHOT. Interesting differences.
- Creating the original vertices and edges is about 5 times faster (no read done at that time).
- When limiting read at 17K/second, the "deletion + creation edge" keeps up (at 1.7k write operations).
- When reading full throttle while doing "deletion + creation edge", the edge deletion creation drops from 150 to 50 per second when compared with 2.1.7.

The turning point is around about 40K read per second with 4k "deletion + creation". More reads will have writes lag behind.

All in all much better. Is there something else that can be suggested (apart from throttling the read?).

**Comment by lvca** [comment]
Are you using any transaction? Are you using OrientGraph or OrientGraphNoTx ?

**Comment by Daniel-Valliere** [comment]
I was using OrientGraph. Performance are better with NoTx graph but my understanding was that we should not use NoTx for sustained operations. NoTx was applicable only to schema changes or build insert operations while no other threads are reading/writing . Has that changed in 2.2?

**Comment by lvca** [comment]
Yes! Take a look at: http://orientdb.com/docs/2.1/Graph-Consistency.html.

**Comment by lvca** [comment]
What performance do you have with no tx graph?

**Comment by Daniel-Valliere** [comment]
With no tx graph, the turning point where writes starts to lag being is about 47k read per second and 4.7k "deletion + creation". So the NoTx gave about 15 to 20% better performance.

**Comment by lvca** [comment]
Another way to speedup concurrent requests is using multiple clusters per class. In v2.2 this is automatic: when a new class is created, the number of clusters is equals to the number of cores. In this way read and also writes can go in parallel with the minimum contention when you don't use TX.
