### ISSUE TITLE
Select with projection paramenter value as label

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#5745]
with as simple select:`select :par` the result field depends on the value, so for example if i run the query with as paramenter value `a` the result will be `{'a':'a'}` like i ran `select 'a'` what i expect instead is `{'par':'a'}`.

**Comment by luigidellaquila** [comment]
@tglman good catch! the obvious workaround is to use an alias:

```
select :par as par
```

**Comment by luigidellaquila** [comment]
This is fixed in v 3.0, now it returns `:par` as column name

Thanks

Luigi
