### ISSUE TITLE
problem using LET in console.sh batch mode

### ISSUE THREAD

**Issue by pkoppstein** [orientechnologies/orientdb#5747]
According to my reading of http://orientdb.com/docs/2.1/SQL-batch.html
one should be able to proceed as follows using console.sh:

````
$ console.sh
OrientDB console v.2.1.10

orientdb> connect plocal:/Users/peter/orientdb/databases/study admin admin
orientdb> select from student
----+-----+-------+-------+-----
#   |@RID |@CLASS |surname|Id   
----+-----+-------+-------+-----
0   |#11:0|student|Miller |11111
----+-----+-------+-------+-----

orientdb {db=study}> begin
orientdb {db=study tx=[0 entries]}> let a = insert into student (surname,Id) values('Xyzzy', '1') return @rid
```
But the "let" yields:

>  !Unrecognized command: 'let a = insert into student (surname,Id) values('Xyzzy', '1') return @rid'


Note that, by itself, the 'insert' works fine:
```
> insert into student (surname,Id) values('Xyzzy', '1') return @rid
Inserted record '#11:3' in 0.051000 sec(s).
```

**Comment by SamHard** [comment]
I've been having the same problem.  I can't find any way to run the "let" statement using console.sh.  I just get the same error as @pkoppstein above.  The same thing occurs with the "if" statement.  I thought maybe I needed to start a "script sql" session to allow multi-line batches, but when I type "end", I get an error:
~~~~
orientdb {db=Script1}> script sql
[Started multi-line command. Type just 'end' to finish and execute]
insert into V (name) values ("test 1");
end

Error: com.orientechnologies.orient.core.exception.OSecurityException: Language 'sql insert into v (name) values ("test 1")' is not allowed to be executed
~~~~

**Comment by luigidellaquila** [comment]
Hi @SamHard 

I fixed this issue a few days ago, the fix will be released with 2.2.11 in two or three days.
Do you mind trying it with latest snapshot (2.2.x branch) and let me know if it works fine in your case?

Thanks

Luigi

**Comment by SamHard** [comment]
I just installed the official release of 2.2.11, and this has been fixed.  Thanks!

**Comment by luigidellaquila** [comment]
Hi @SamHard 

Thank you for confirming. Closing

Luigi
