### ISSUE TITLE
Add OrientDB support in LinkBench

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5749]
https://www.facebook.com/notes/facebook-engineering/linkbench-a-database-benchmark-for-the-social-graph/10151391496443920/

**Comment by smolinari** [comment]
:+1: 

Scott

**Comment by laa** [comment]
Good feature but too much work let's finish on going work on YCSB first.

**Comment by smolinari** [comment]
I'd personally say, at least one working benchmark is necessary. YCSB is also good. 

Scott
