### ISSUE TITLE
Traversal not producing correct output.

### ISSUE THREAD

**Issue by digambarpatil123** [orientechnologies/orientdb#5750]
Hi All,

Can anybody tells me how to get all nodes as well as all edges properties in traversal.

For Example : If I run the following query 
select from (TRAVERSE in(), inE() FROM (SELECT FROM Example_Class WHERE @rid = #13:187));

Every time the result is changing. 

Requirement : Get All inordered nodes and edges from specific node (#13:187).

**Comment by luigidellaquila** [comment]
Hi @digambarpatil123 

If i got it right, the following should do the job:

```
TRAVERSE inE(), outV() FROM #13:187
```

Thanks

Luigi

**Comment by digambarpatil123** [comment]
Thanks @luigidellaquila 

But the thing is, I know the destination node and I want to traverse in order in all the possible way. Now its showing for only one path and some of the nodes are missing from the traversal.

**Comment by digambarpatil123** [comment]
If I execute select from (traverse in(), inE() from #13:187) sometimes its showing correct output but sometimes its not. Why the random behaviour.

**Comment by luigidellaquila** [comment]
Hi @digambarpatil123 

every node has both an in() and an inE(), the traversal does not guarantee that one is executed before the other, so you will have a random behavior here.

**Comment by digambarpatil123** [comment]
Thanks @luigidellaquila
