### ISSUE TITLE
Write binary property by JDBC not works

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#5753]
I store binary value by PreparedStatement.
Query works fine (without errors). Than I try to read the property, ResultSet returns null.

Version: 2.2.0-SNAPSHOT

Java code for inserting:
PreparedStatement pstmt = connection.prepareStatement( "insert into Bookmark  set  data=:data, isRead='N', isPrivate='F', isShared=0, id='f0faf232-8cbc-4b54-834b-9e1a2c2fcc75'");
pstmt.setBytes(0, (byte[]) value);
pstmt.executeUpdate();

Java code for selecting
Statement stmt = executionEngine.createStatement();
ResultSet rs = stmt.executeQuery( "select from Bookmark WHERE id = 'f0faf232-8cbc-4b54-834b-9e1a2c2fcc75'");
if ( rs.next() ) {
	ResultSetMetaData metadata = rs.getMetaData();
        for ( int i = 0; i < rs.getMetaData().getColumnCount(); i++ ) {
		int dbFieldNo = i + 1;
		String dbColumnName = metadata.getColumnName( dbFieldNo );
                 Object dbValue = rs.getObject( dbColumnName );
                  LOG.info( i + " dbColumnName " + dbColumnName + "; dbValue class:" + (dbValue!=null ? dbValue.getClass() : null) );
                  LOG.info( i + " dbColumnName " + dbColumnName + "; sql type:" + rs.getMetaData().getColumnTypeName(dbFieldNo));
 ____________________
I see in log file that dbValue class is null.
I try read filed "data" by method "getBlob". The method returns null too.
All other fields reads correctly.

**Comment by robfrank** [comment]
Hi can you give me some code to reproduce the scenario? thanks in advance

**Comment by schernolyas** [comment]
@robfrank 

I faced the bug during fix test in Hibernate OGM for OrientDB project. And  I can't send Java code to You.. But ... I think that wrire the code You can during 10 minutes.

I can send to you code for create schema.
1)  create class Bookmark extends V
2) create property Bookmark.data binary

Any questions welcome

**Comment by schernolyas** [comment]
@robfrank 

Have You any progress?  Can I help You?

**Comment by robfrank** [comment]
We have a test that retrieves a binary field (a pdf file) via JDBC. 

https://github.com/orientechnologies/orientdb/blob/develop/jdbc/src/test/java/com/orientechnologies/orient/jdbc/OrientJdbcBlobTest.java

Is your scenario similar? Maybe you can enrich this test with your scenario and submit a PR?

**Comment by schernolyas** [comment]
Hi @robfrank 

I see your link.   Thank You for your answer.
You wrire binary objtect by native API. But I do in by JDBC API.
The function not exists in your unit test.

If reading of binary objects works .... then writing not works. I renamed issue.

**Comment by robfrank** [comment]
hi, I've added the implementation for setBinaryStream in OrientJdbcPreparedStatement:

https://github.com/orientechnologies/orientdb/commit/b2da1f5418c8584a42b668d711cde18d549d6a56

This feature will be available on next 2.2.0 release, I think 2.2.0-rc1. I'll also back port to 2.1.x branch in a couple of hours, and so it will be available on next hotfix release, 2.1.12

**Comment by schernolyas** [comment]
Hi @robfrank !

A lot of thanks!  I will upgrade OrientDB`s version in pom.xml .

Can I  ask You to lead to fix one important problem? I mean my PR  5622. I ask You because Luca haven`t time for it. I can recreate pr if it is necessary. My pr fix problem with creating connection pool in WildFly.

**Comment by robfrank** [comment]
I'll take a look on the PR, eventually commenting there. In the meanwhile I close this issue.
