### ISSUE TITLE
error creating database with name starting with "f" in console

### ISSUE THREAD

**Issue by seriouslyEnter** [orientechnologies/orientdb#5755]
OrientDB v2.1.11 (fresh) on Windows10 64bit

error creating database with name starting with "f" in console
see screenshot

![unbenannt](https://cloud.githubusercontent.com/assets/5265238/13204752/0928dcc2-d8d8-11e5-9a59-c6051348329b.PNG)

**Comment by luigidellaquila** [comment]
Hi @seriouslyEnter 

The problem seems to be related to the `\f`, my feeling is that it's being interpreted as a form feed character. The problem does not happen on Linux/Mac because they use forward slash.

I'll let you know soon for a fix

Thanks

Luigi

**Comment by Robin479** [comment]
It might help to always use a forward slash regardless of the operating system, since the path is only ever interpreted by Java code.

**Comment by seriouslyEnter** [comment]
Will do.
Thanks
