### ISSUE TITLE
Integer field where clause doesn't work properly

### ISSUE THREAD

**Issue by arikalon** [orientechnologies/orientdb#5760]
I created a class with a long field, accountId
I inserted some records
when I try to query those records it doesn't work as I expect.
All records has the same accountId, 232330
I have total of 16 records.
The class name is edgebase

I tried the below queries:
select count(*) from edgebase where accountId = 232330
PROPERTIES
count
6 (expected 16)

select count(*) from edgebase where accountId = '232330'
PROPERTIES
count
6 (expected 16)

select count(*) from edgebase
count
16 (this is ok)

select count(*) from edgebase where accountId like '232330'
PROPERTIES
count
16 (this is the correct result, but why is it different from =)

select count(*), accountId from edgebase group by accountId
PROPERTIES
count accountId 
16    232330
(when using group by, the DB group all the rows with the same accountId)

Please help
using:
Studio version : 2.1
OrientDB version : 2.1.8

thanks

**Comment by maggiolo00** [comment]
hi @arikalon 

can you provide a script sql to populate the database and reproduce this issue?

**Comment by arikalon** [comment]
below is the DB dump.
once imported, you can run the above queries on edgebase class

[export.json.gz](https://github.com/orientechnologies/orientdb/files/142142/export.json.gz)

**Comment by arikalon** [comment]
some additional input ...
When I removed the index from edgebase class, the queries worked properly
Adding it back, brought back the problem

**Comment by maggiolo00** [comment]
ok @arikalon 

i'm checking it.

**Comment by maggiolo00** [comment]
hi @arikalon 

Which is the index?

EdgeBase.edgeKey?

**Comment by maggiolo00** [comment]
hi @arikalon 

I think you used a wrong index type for EdgeBase.edgeKey.

You used dictionary that has this exact behaviour

http://orientdb.com/docs/2.1/Indexes.html#index-types
You should use NOT_UNIQUE instead as you can have duplicates for the same

key [accountId,srcNode,destNode]

**Comment by arikalon** [comment]
I think it's really bad that choosing the wrong index type can lead to such a behavior

I'll check the NOT_UNIQUE index type
thanks

**Comment by maggiolo00** [comment]
hi @arikalon 

It is just a type of index (DICTIONARY) that act in this way. For the same key just replace the indexed document instead of give the duplicate exception. In your case you have duplicate keys so you should go with NOT_UNIQUE

**Comment by maggiolo00** [comment]
hi @arikalon 

did you solve with NOT_UNIQUE?

**Comment by arikalon** [comment]
yes, it did

Thanks for the help

**Comment by maggiolo00** [comment]
:+1:
