### ISSUE TITLE
Graph interface in blueprints-core

### ISSUE THREAD

**Issue by rmohta** [orientechnologies/orientdb#5761]
1. blueprint 3.x is now part of ASF. When will Orientdb start using blueprints 3.x? 

2. Can Graph interface in current blueprints be changed? For instance, if the interface could extend AutoCloseable?

_Other information_
- orientdb-graphdb: 2.1.10
- blueprints-core: 2.6.0

**Comment by maggiolo00** [comment]
hi @rmohta 

Tinkerpop blueprints 3.x official suppurt is schedule for OrientDB 3.0
http://orientdb.com/docs/2.1/Roadmap.html#release-3-0

Meanwhile you can check out this

https://github.com/mpollmeier/orientdb-gremlin

**Comment by rmohta** [comment]
Thanks.. will look into them
