### ISSUE TITLE
OrientDB Studio doesn't support comments in batch call

### ISSUE THREAD

**Issue by johansjob** [orientechnologies/orientdb#5762]
Comments are simply not supported when running a batchscript in OrientDB studio. 
Based on this stackoverflow question:
http://stackoverflow.com/questions/35503579/batch-with-comments-in-orientdb-studio/35519866#35519866

Very related to #4651

**Comment by luigidellaquila** [comment]
Hi @johansjob 

The problem is not in Studio, batch scripts do not support comments. We already have an implementation for this in 2.2, it just has to be enabled (it includes other things that change some backward compatibility)

Thanks

Luigi

**Comment by johansjob** [comment]
Yeah, that was my guess. Cool!

**Comment by Solido** [comment]
Any news on this ? 

Can be really great to be able to describe what a class do. 

In the form of comment in osql or better directly in Studio.

**Comment by luigidellaquila** [comment]
Hi @Solido 

I have good news indeed, comments in SQL are already supported by the new parser, but the old execution chain did not allow to add them in some specific places (eg. at the beginning of a script).
In v 3.0 we rewrote the executor and now we are switching all the execution flows to the new engine (the legacy engine will still be available for backward compatibility), next candidate for this is the REST interface. After that, Studio will allow to add comments in any place of the script. 

Comment syntax will be multiline java-like, eg. 

```
/*
this is a 
comment
*/
```

Thanks

Luigi

**Comment by lvca** [comment]
This has been already solved in 3.0-M2
