### ISSUE TITLE
Web interface places LIMIT 20 on DELETE VERTEX command

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#5767]
Repro, in the web interface:
- create more than 20 records of any vertex class, call it T
- run `DELETE VERTEX T`
- observe that the returned value of the deletion command is 20, and that the db still has vertices of type T
- increase the limit in the web interface to 20000
- observe that more than 20 records are now deleted

**Comment by maggiolo00** [comment]
hi @obi1kenobi 
Yes by default Studio uses limit 20 that is used as parameter in this http api
http://orientdb.com/docs/2.1/OrientDB-REST.html#command

This prevent eventual crashing due big results set. You can override it by setting the limit parameter or append a limit in your query.
```
DELETE VERTEX T limit -1
```

We can resolve this issue in case of delete in 2 ways

- Studio side : detect the delete and use -1 as limit
- Http Api : in case of delete command ignore the limit and use -1

**Comment by obi1kenobi** [comment]
I know about the implicit LIMIT 20 on queries in Studio -- sorry, I should have described why this is a problem better. The problem is that the LIMIT 20 applies to `DELETE VERTEX` but not to `DELETE`.

```
< create 22 records of type Deletion >
SELECT COUNT(*) FROM Deletion  // --> returns 22
DELETE FROM Deletion  // --> returns 22
```

So the problem is not that the limit is applied or not applied, but rather the lack of consistency between the use of the limit between the two delete commands.

**Comment by obi1kenobi** [comment]
Thoughts on this issue?

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I already worked on this... I just have to check if it was done on 2.1 or on 2.2, I'll do it in short.
Which version are you using?

Thanks

Luigi

**Comment by obi1kenobi** [comment]
I'm currently on 2.1.9 and 2.1.13, on different systems. I'd also appreciate if the bug is fixed in 2.2 though :)

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I can confirm that this behavior is still present in 2.1.x, but I cannot change it in a hotfix release for backward compatibility.
Anyway, I'm pushing a fix in develop branch (2.2), so it will definitely change in next releases.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Pushed to develop branch. Closing

Thanks

Luigi

**Comment by obi1kenobi** [comment]
Thanks Luigi!
