### ISSUE TITLE
Binary compatibility test is failing on 2.2.x 

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5770]

**Comment by lvca** [comment]
@laa is this already solved, right?

**Comment by laa** [comment]
Hi Lica,
Couple of days ago we added new  beta version, so after that ant based
versions were stopped to be source of demo database.
It means that binary compatibility test once again does not know how to
handle new build structure.
We should fix it till final 2.2.

On Wed, Feb 24, 2016 at 6:55 PM Luca Garulli <notifications@github.com>
wrote:

> @laa <https://github.com/laa> is this already solved, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5770#issuecomment-188351543>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin
