### ISSUE TITLE
OutOfMemoryError (Java heap space) when using binary protocol w/ connection pool

### ISSUE THREAD

**Issue by sinfex** [orientechnologies/orientdb#5774]
Just updated to 2.2.0-beta. Without the pooling option set, everything seems to be working fine.

```
const OrientJS = require('orientjs'),
    server = OrientJS({ host: 'localhost', port: 2424, pool: { max: 10 } }),
    DB = server.use({ name: 'test', username: 'admin', password: 'admin' });

DB.query('select from v');
```

> [OServer]java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid2544.hprof ...
Heap dump file created [12260579 bytes in 0.176 secs]

> Unhandled rejection OrientDB.RequestError: Java heap space
    at Operation.parseError (orientjs/lib/transport/binary/protocol33/operation.js:865:13)
    at Operation.consume (orientjs/lib/transport/binary/protocol33/operation.js:455:35)
    at Connection.process (orientjs/lib/transport/binary/connection.js:385:17)
    at Connection.handleSocketData (orientjs/lib/transport/binary/connection.js:286:17)

Tested with:

> OrientDB Server v2.2.0-beta
Build: develop@r4cbc24a66f17f023a2e59da300a29b91fdb5d1fa; 2016-02-22 17:46:44+0000

> OrientJS: latest master branch
OrientJS: latest 2.2.x branch

**Comment by maggiolo00** [comment]
hi @sinfex 

i'm checking it

**Comment by maggiolo00** [comment]
@sinfex 

did you try it with 2.2-rc1?

**Comment by sinfex** [comment]
@maggiolo00 no, haven't tried it with 2.2-rc1.
We're not using OrientDB anymore at this point, sorry I cannot test it.

**Comment by maggiolo00** [comment]
Ok @sinfex.
BTW tested with orientjs 2.2.0 and OrientDB 2.2.0 GA and works without problem
Thanks
