### ISSUE TITLE
error while removing property's attribute "linkedType"

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#5775]
Hi. my DB is 2.1.11

documentation is saying for linkedType
Use NULL to remove an existing value.

But database return error on this query.

**create property testNull.embList embeddedList**
Property created successfully with id=2

**alter property testNull.embList LINKEDtype STRING**
Property updated successfully

**alter property testNull.embList LINKEDtype null**
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.alter property testNull.embList LINKEDtype null
Error: java.lang.NullPointerException: Name is null

**alter property testNull.embList LINKEDtype NULL**
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.alter property testNull.embList LINKEDtype NULL
Error: java.lang.NullPointerException: Name is null

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

it seems to be a bug in the ALTER PROPERTY command, I'll check it ASAP

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

I'm working on it, but I found another little problem:

```
  @Test public void testRemoveLinkedType() {
    OSchema schema = db.getMetadata().getSchema();
    OClass classA = schema.createClass("TestRemoveLinkedType");
    OProperty prop = classA.createProperty("prop", OType.EMBEDDEDLIST, OType.ANY);

//    db.command(new OCommandSQL("alter property TestRemoveLinkedType.prop linkedtype null")).execute();
    db.command(new OCommandSQL("insert into TestRemoveLinkedType set prop = [4]")).execute();

    List<ODocument> result = db.query(new OSQLSynchQuery<ODocument>("select from TestRemoveLinkedType"));
    Assert.assertNotNull(result);
    Assert.assertEquals(result.size(), 1);
    Collection coll = result.get(0).field("prop");
    Assert.assertEquals(coll.size(), 1);
    Assert.assertEquals(coll.iterator().next(), 4);
  }
```

@tglman this is for you ;-)

Thanks

Luigi

**Comment by tglman** [comment]
fixed all the cases, closing
