### ISSUE TITLE
Replication fails on first update after I restart orientdb cluster 2.2.0-beta

### ISSUE THREAD

**Issue by normwai** [orientechnologies/orientdb#5776]
Replication fails on first update after I've restarted orientdb cluster.  All updates afterwards works fine.  The first update is lost.  I tested by updating via the http orientdb server.

Using orientdb-community-2.2.0-beta in Linux.

**Comment by lvca** [comment]
Please could you post the file `distributed-config.json` under your database directory?

**Comment by normwai** [comment]
{"@type":"d","@version":0,"version":3,"servers":{"@type":"d","@version":0,"nysobase0023":"master","nysobase0024":"replica","nysobase0025":"replica"},"clusters":{"@type":"d","
@version":0,"internal":{"@type":"d","@version":0},"index":{"@type":"d","@version":0},"*":{"@type":"d","@version":0,"replication":true,"servers":["nysobase0023","nysobase0024"
,"nysobase0025","<NEW_NODE>"]}},"replication":true,"resyncEvery":15,"autoDeploy":true,"hotAlignment":false,"executionMode":"asynchronous","readQuorum":1,"writeQuorum":1,"fail
ureAvailableNodesLessQuorum":false,"readYourWrites":true}

**Comment by lvca** [comment]
You have `writeQuorum` to 1, but in order to have consistency you should have the majority, so 2.

**Comment by normwai** [comment]
I've update writeQuorum to 2.  Deleted distributed-config.json.  Restarted.  Confirmed writeQuorum is now 2.  The same issue.  First update to database is not being replicated.

**Comment by lvca** [comment]
Do you have any log of the failure of first update in any of the 3 servers?

**Comment by normwai** [comment]
There is nothing logged.  I've tried upping log verbose from INFO to DEBUG, but nothing is logged.

**Comment by lvca** [comment]
How can I replicate this problem? Do you experiment the same problem with an empty db or just with yours?

**Comment by normwai** [comment]
Any database on cluster.  After I stop and restart all orientdbs in cluster.  I update any field for a record in database, for example GratefulDeadConcerts with the web interface.  The changed field doesn't show on a select on the other servers.

**Comment by lvca** [comment]
This has been fixed in v2.2.0-rc1 and v2.2.0-SNAPSHOT.
