### ISSUE TITLE
Support for Decimal Type

### ISSUE THREAD

**Issue by cguerin** [orientechnologies/orientdb#5778]
Can't seem to get Decimal type working ever with OrientDB JDBC driver.

**Comment by robfrank** [comment]
Hi, i'm investigating this issue. Which version of OrientDB are you using? Did it works in the past? May you add some code? (better form for sample code would be a failing test :) )

**Comment by robfrank** [comment]
I found the problem, thank you for your report. I'm working on it, I'll notify here when a solution will be available

**Comment by cguerin** [comment]
Super! 

I'm creating a system for aggregating flight logs and storing some units in terms of micro percentages, so the Decimal data type is very useful to me.

I must say I've been blown away by OrientDB, it truly rocks.

**Comment by robfrank** [comment]
I fixed on 2.1.x and develop branches:

https://github.com/orientechnologies/orientdb/commit/d977675d16350ef35b1858a272e52ac69c24b027

https://github.com/orientechnologies/orientdb/commit/f4ccd6b0c2e1e33dd9420915e3b4916f9fbebc30

I don't know which version are you using, but you can build from source and use the jar until we release next 2.1.13 or 2.2.0-rc1.
