### ISSUE TITLE
Cannot Create New Class Extending V in Studio

### ISSUE THREAD

**Issue by decafmainline** [orientechnologies/orientdb#5780]
Using OrientDB version 2.1.10 I get the following error message when creating a new Class that extends V through the Studio Browse tab. This is a fresh database with absolutely no changes made to it.

Command:
`create class SomeOtherClass extends V;`

Yields:
`com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #35: Super-class V; not exists Command: create class SomeOtherClass extends V; -------------------------------------------^ `

I issued the exact same command using the command line console and successfully created the Class.

**Comment by maggiolo00** [comment]
hi @decafmainline 

try to remove the semicolon ;

```
create class SomeOtherClass extends V
```

**Comment by decafmainline** [comment]
Interesting. That works. Does the Studio use ; for something other than a command separator out of curiosity?

**Comment by maggiolo00** [comment]
hi @decafmainline 

Studio uses HTTP api of OrientDB for single command

http://orientdb.com/docs/2.1/OrientDB-REST.html#command
In single command ; is not supported as command separator as it accept only one queriy

If you switch in batch mode you can use ; to separate queries

**Comment by decafmainline** [comment]
Gotcha. Good to know. Thanks for the quick reply and keep up the great work!
