### ISSUE TITLE
orientdb console bugs

### ISSUE THREAD

**Issue by eyurtsev** [orientechnologies/orientdb#5781]
the "browse class" command seems to be caching too much information and the cache is not invalidated correctly when the state of the database is updated by another client.

For example:

* if a 2nd client creates a schema, it does not appear in "browse class" without reconnecting to the server
* if a 2nd client updates the record, the first client still sees the old record information with "browse class"

OrientDB console v.2.1.9-SNAPSHOT (build 2.1.x@r; 2016-01-07 10:51:24+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

under ubuntu 14.04

**Comment by tglman** [comment]
hi @eyurtsev,

this are known issues, here the references: https://github.com/orientechnologies/orientdb/issues/3496 and https://github.com/orientechnologies/orientdb/issues/4546

I think we can mark this a duplicate.
