### ISSUE TITLE
orientdb console improvements

### ISSUE THREAD

**Issue by eyurtsev** [orientechnologies/orientdb#5782]
It'd be nice to add the following features to the console:
1. handle multi-line queries graciously --> once the query gets wrapped into a 2nd line all sort of funny behaviour appears :)
2. tab completion
3. delete to beginning of line / end of line

OrientDB console v.2.1.9-SNAPSHOT (build 2.1.x@r; 2016-01-07 10:51:24+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

ubuntu 14.04

**Comment by robfrank** [comment]
2. tab completion is in place

1. do you mean copy and paste long multiline queries?

3. so you mean something like shell CTRL-E/A and CRTL-W? Or?
