### ISSUE TITLE
v2.1.11 : LiveQuery issue with remote Connections

### ISSUE THREAD

**Issue by dechanaud** [orientechnologies/orientdb#5784]
I set up an embedded OrientDB Server 2.1.11 (OLiveQuery Plugin enabled via settings) with remote access enabled.

So I can access the created Databases (document) via : plocal or remote:localhost URL.
(I successfully created records with both connection URLs)

`OLiveQuery<ODocument> liveEventQuery = new OLiveQuery<ODocument>("LIVE SELECT FROM XXX", listener);
List<ODocument> result = clusterDb.query(liveEventQuery);`

If I used a remote connection URL, the query for a simple "LIVE SELECT From XXX" never returns (blocked but nothing in logs...)

Used Connection Pool
`connPool = new OPartitionedDatabasePool("remote:" + dbServerIp + "/dbName","writer", "writer", 20);`

If I used a plocal connection URL, the query "LIVE SELECT From XXX" returns immediately as expected.
Used Connection Pool
`connPool = new OPartitionedDatabasePool("plocal:" + dbPath,"writer", "writer", 20);`

Is there any restriction of using LiveQuery via a remote connection ?
Is a specific restriction as I use an embedded server ?

**Comment by luigidellaquila** [comment]
Hi @dechanaud 

There are no specific restrictions in using LiveQuery with remote connections or embedded server. 
LiveQuery is an experimental feature in v 2.1 (stable in 2.2) but many things were fixed from 2.1.1 to 2.1.11, could you please try with latest 2.1.11 and let me know if it solves the problem?

Thanks

Luigi

**Comment by dechanaud** [comment]
I made a typing error. I only used version 2.1.11. So this issue is present on 2.1.11 as well.

I renamed the tile of the issue to put the correct version on which I detected this issue.

**Comment by dookie2k3** [comment]
I have the same problem on v2.1.11 and on v2.2.0-beta. When I query a live query, thread got stuck in query line.

Thanks

**Comment by luigidellaquila** [comment]
Hi @dookie2k3 @dechanaud 

it should be already fixed on branch 2.1.x, I'm double-checking right now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, I can confirm, it's already fixed.

I'm closing this issue, please reopen if you see any other problems

Thanks

Luigi
