### ISSUE TITLE
v2.2.0-Beta: Many edges not visible from the OUT vertex

### ISSUE THREAD

**Issue by Daniel-Valliere** [orientechnologies/orientdb#5785]
This is done on v2.2.0-Beta.
I have 2 orientdb classes: DSRoot and DSTable.
Only one instance of DSRoot and about 200 instances of DSTable.
There's one edge (class 'rootTable') between the DSRoot vertex and each of the 200 vertices of DSTable.
When all vertices and edges are created, DSRoot vertex sees only 27 vertices of DSTable (getEdges/getVertices navigating 'rootTable' edge return only 27 instance) while each DSTable vertices can navigate the 'rootTable' edge to the DSRoot vertex.

Is this a known issue?

**Comment by luigidellaquila** [comment]
Hi @Daniel-Valliere 

could you please post some details about the schema? Do you have any indexes defined (DICTIONARY indexes by chance...)?
Can you please post a script to reproduce the problem?

Thanks

Luigi

**Comment by Daniel-Valliere** [comment]
It may take some time to find what script can reproduce the problem. Of course, a quick script I tried could not reproduce it.

DSRoot extends V
DBTable extends DSBaseEntity which extends V
None are abstract, they are using 8 clusters with Round-Robin algo.
At the moment, DSRoot has 1 record and DSTable has 460 and DSBaseEntity has 9213.
V has 12,545 and E has 22,045 records.

The DSRoot, DSTable and DSBaseEntity have no index. As far as I know, we are not using indexes anywhere. The web console shows only dictionary, OFunction.name, ORole.name and OUser.name in the indexes list. 

I'm still look for a repro script. Do you have other ideas that could help pinpoint the problem?

**Comment by Daniel-Valliere** [comment]
I have a junit test case that repro the problem. What is the best way to provide it to you?

**Comment by tglman** [comment]
hi @Daniel-Valliere 

you can create a gist and add the link here.

**Comment by luigidellaquila** [comment]
Hi @Daniel-Valliere 

Any chance to have the junit test? In the meantime we released v 2.2 beta2, maybe it's worth trying with that

Thanks

Luigi

**Comment by Daniel-Valliere** [comment]
The issues is related to the use of transactional graph.

See code and comment in https://gist.github.com/Daniel-Valliere/23e27344624cdfb003a70ec78ba82cdf

**Comment by luigidellaquila** [comment]
Hi @Daniel-Valliere 

Thank you very much, I could reproduce the issue with current snapshot.

We are working to a fix, I'll give you a feedback asap

Thanks

Luigi

**Comment by tglman** [comment]
hi @Daniel-Valliere,

Just fixed in develop, thank you for reporting, with so precise test case.
