### ISSUE TITLE
select max(localdate) from sitedata

### ISSUE THREAD

**Issue by Uditmittal** [orientechnologies/orientdb#5786]
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select max(localdate) from sitedata

Error: java.lang.ArrayIndexOutOfBoundsException

When i Upgrade my Orientdb from 2.0 to 2.1.11 then is will shown error Why 
when i execute this command on 2.0 it will work Fine !!!

**Comment by tglman** [comment]
hi @Uditmittal 

Do you have a full stack trace ?

**Comment by luigidellaquila** [comment]
Hi @Uditmittal 

even better, do you have a simple test case or sequence of commands to reproduce the problem?

Thanks

Luigi

**Comment by Uditmittal** [comment]
@tglman  Here is my Stack Trace 
Error deserializing record with id #14:289 send this data for debugging: ABBzaXRlZGF0YWUAAABfbQAAAGErAAAAe28AAACCcQAAAKxzAAAGhD0AAAaIdQAABot3AACE43kAAITzEG1ldGFkYXRhAACG0wkccHJvY2Vzc2VkX2RhdGUAAIfABwAaCgAcYmF... and so on...=[ORecordSerializerBinary]

@luigidellaquila  command is -- select max(localdate) from sitedata ;
 sorry we can't share our data...

Thanks 
Udit Mittal

**Comment by luigidellaquila** [comment]
Hi @Uditmittal 

it seems to be a problem in the binary serialization, please wait @tglman comments

Thanks

Luigi

**Comment by tglman** [comment]
hi @Uditmittal,

unfortunatly i need the full data for investigate the problem, it seems a serialization issue, is there any way that you can share that data ? you can send it only to us to support@orientdb.com.

the actual data i need is just the record that give the error and the database schema.

Thanks

Emanuele

**Comment by tglman** [comment]
Hi,

Waiting for a reply since a while, we fixed few issue on that part since this report, so i'm closing this, add more info if is still reproducible, we will reopen in case.

Regards
