### ISSUE TITLE
OGraphCommandExecutorSQLFactory does not consider 'autoStartTx' setting

### ISSUE THREAD

**Issue by Zeemee7** [orientechnologies/orientdb#5790]
When executing an `OCommand` with at least one of "DELETE VERTEX", "MOVE VERTEX", "CREATE EDGE" or "DELETE EDGE" statements, a transaction will automatically be started, regardless of the autoStartTx-Property.
For example, `OCommandExecutorSQLDeleteVertex.execute` calls `OGraphCommandExecutorSQLFactory.runInConfiguredTxMode` which in turn calls `OGraphCommandExecutorSQLFactory.getGraph` with the `autoStartTx` parameter set to true.
Why can't `getGraph` determine this flag from the settings?

**Comment by Zeemee7** [comment]
Sorry... from at least 2.1.6 up to 2.1.11.

**Comment by enRGi** [comment]
Is there some news on this issue?
