### ISSUE TITLE
OrientDB 2.2 Beta - Error on Alter Class Add Custom Properties

### ISSUE THREAD

**Issue by cvm1ll3** [orientechnologies/orientdb#5792]
This works in 2.2Alpha:
<code> ALTER CLASS Person CUSTOM onCreate.identityType=role</code>

It produces the error:
<code>com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: ALTER CLASS Person CUSTOM onCreate.identityType=role Encountered " "ALTER "" at line 1, column 1. Was expecting one of:   ... ... ... ... ... ... ... ... ... ... ... ... </code>

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

I guess you are referring to 2.2 beta (not alpha), right?
It must be the new strict parser...
Could you please try this and let me know if it fixes the problem?

```
ALTER CLASS Person CUSTOM `onCreate.identityType`=role
```

**Comment by cvm1ll3** [comment]
Hi @luigidellaquila,

Yes I'm on beta, just finished testing alpha. I tried single and double quotes and it still produces the same error.

**Comment by luigidellaquila** [comment]
ok, testing it now...

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

Ok, I found the problem and I have a fix for it. 
The new parser is more strict than the old one and only accepts a valid identifier as a custom property name. The `.` character is not allowed in identifiers, so it has to be back tick quoted (back tick is ``` ` ```, not single quote `'` or double quote `"`), so you will have to write the query this way

```
ALTER CLASS Person CUSTOM `onCreate.identityType`=role
```

I had to do a little fix and I'm running all the tests, if everything is OK I'll push it to develop branch in a few minutes

Thanks

Luigi

**Comment by cvm1ll3** [comment]
Hi @luigidellaquila 

Oh got it. Yes back tick works perfectly. Thank you so much!

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

I just pushed the fix to develop branch, you should build from sources or wait for next RC1 to have it.
Just pay attention to the fact that in 2.2 beta, before the fix, the parsing works fine with back ticks, but the result is not the expected one, if you query the schema with 

select from (
select expand(classes) from metadata:schema
) where name = 'Person'
you'll see that also the back ticks are wrongly stored in the property name, so in the end it won't work.

I'm closing this issue, please reopen if you experience any other problems

Thanks

Luigi

**Comment by cvm1ll3** [comment]
Hi @luigidellaquila 

Ok, will do thanks a lot!

**Comment by cvm1ll3** [comment]
Hi @luigidellaquila,

I just noticed now, the command <code>ALTER CLASS Person CUSTOM `onCreate.identityType`=role</code> says its successful but when I create a vertex, the OUser RID is in the _allow field rather than the ORole RID.
