### ISSUE TITLE
SET SERVER USER console command giving exception on 2.2.0 beta

### ISSUE THREAD

**Issue by metametametameta** [orientechnologies/orientdb#5794]
On starting the Orient server, the "root" server user was successfully created and the password was hashed using PBKDF2WithHmacSHA256 as is expected for 2.2

However, now I'm trying to add more server users via the console and I'm getting the following message:

> OrientDB console v.2.2.0-beta (build develop@r4cbc24a66f17f023a2e59da300a29b91fdb5d1fa; 2016-02-22 17:46:44+0000) www.orientdb.com
> Type 'help' to display all the supported commands.
> Installing extensions for GREMLIN language v.2.6.0
>  
> orientdb> set server user myuser myuser *
> Error on loading ..\config\orientdb-server-config.xml file: java.lang.IllegalArgumentException: **Algorithm '{PBKDF2WithHmacSHA1}' is not supported**
>  
> orientdb>

Part of the problem appears to be in OSecurityManager.java, where there seems to be some problem with the curly braces matching in createHash(final String iInput, final String iAlgorithm, final boolean iIncludeAlgorithm) method. 

In any case, why is console trying to use PBKDF2WithHmacSHA1? It should use PBKDF2WithHmacSHA256, correct?

I'm using Java 1.8.0_74 for both the server and the console.

**Comment by SDIPro** [comment]
Fixed in 2.2.1.
