### ISSUE TITLE
Enhancement on REST API to support chunked transfer-encoding

### ISSUE THREAD

**Issue by thirawato** [orientechnologies/orientdb#5796]
Just to propose an idea for REST API improvement for my case. I'm developing a middle-tier application sit between OrientDB and client in order to exchange data between them. However OrientDB's REST API currently requires 2 HTTP headers which one of them is 'Content-Length'. This causes my application has to read and store a whole bunch of client's request data for just to know a total length. 

I would need OrientDB to support [chunked transfer-encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) which is standardized in HTTP 1.1 for both incoming request and outgoing response.

**Comment by lvca** [comment]
This will be solved once we replace our HTTP layer with Jetty or something else.
