### ISSUE TITLE
mistake in expression computation

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5798]
<pre>
select max( 79 - value,0) from  33:310 ==>0

----+------+----------------
#   |@CLASS|max
----+------+----------------
0   |null  |0              
----+------+----------------

select max(( 79 - value),0) from  33:310 ==>20

----+------+----------------
#   |@CLASS|max
----+------+----------------
0   |null  |20              
----+------+----------------
</pre>

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

OrientDB 2.2.x does not officially support general expressions, the right way to do it is with and eval() function:

```
select max(eval("79 - value"), 0) from  33:310
```

V 3.0 supports full expression evaluation, the new SQL statement already supports it in develop branch

Thanks

Luigi
