### ISSUE TITLE
env variable not supported for a specific property

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#5799]
Orientdb verison: orientdb-community-2.1.9

The orientdb-server-config file property "orientdb.www.path" is not working with system variable. 
It needs the full path given like below.

`<entry` name="orientdb.www.path" value="C:/somepath/somefolder/orientdb-community-2.1.9/www/"/>

If we give env variable like below it wont work.
`<entry` name="orientdb.www.path" value="${MY_ENV_VARIABLE}/orientdb-community-2.1.9/www/"/>

This property is needed when for the web studio when running orientdb in embedded mode.
The work around for this is to provide the full path. This becomes a issue when setting up new environments.

**Comment by luigidellaquila** [comment]
Hi @smallik 

It's not currently supported, but I'm checking how easy it is to support it

Thanks

Luigi
