### ISSUE TITLE
No option to specify the superclass while creating a class from studio

### ISSUE THREAD

**Issue by sivan123** [orientechnologies/orientdb#5801]
Orient db version - 2.2. beta
![image](https://cloud.githubusercontent.com/assets/5057060/13544721/9c2f4d9a-e2b4-11e5-98ae-1370e1d98b43.png)

**Comment by maggiolo00** [comment]
hi @sivan123 

the issue has been reported in Studio here.
https://github.com/orientechnologies/orientdb-studio/issues/357

Thanks
