### ISSUE TITLE
Server : Test failure

### ISSUE THREAD

**Issue by alexist** [orientechnologies/orientdb#5805]
When buiding master 2.1.12 or origin/2.1.x, some tests fails on module "Server". 

[TestSuite.txt](https://github.com/orientechnologies/orientdb/files/161505/TestSuite.txt)

But when running the three failed test separately, there is no failure :  
mvn test -Dtest=HttpBatchTest,HttpConnectionTest

When all test are run, I think there is a conflict with a previous test.

Here is my environment :
Apache Maven 3.3.3
Java version: 1.8.0_72, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-79-generic", arch: "amd64", family: "unix"

**Comment by tglman** [comment]
Hi @alexist,

We are aware about that http tests that in some environment don't work properly, we are planning to rewrite them.

Thank you for reporting it anyway.

**Comment by tglman** [comment]
Hi,
This tests where fixed long ago, closing
