### ISSUE TITLE
Performance Distributed Benchmark

### ISSUE THREAD

**Issue by Ashendra** [orientechnologies/orientdb#5806]
Hi,

Orientdb version - 2.1.5 
I have been facing performance issues during the distributed setup. With a standalone setup the write qps achieved was 3500 transactions/sec. But with a 3 node setup, the qps reached combined was 120 transactions/sec.
The write quorum is 3, read quorum is 1.

Is it the expected behaviour or is there something that I' missing.

**Comment by Ashendra** [comment]
Any update on this. I have tweaked the number of nodes, but greater the number of nodes I add, lower is the qps achieved. How is the database then horizontally scalable?

**Comment by lvca** [comment]
Take a look at: http://orientdb.com/docs/last/Distributed-Configuration-Tuning.html

**Comment by lvca** [comment]
The only way to scale up with writes is to have sharding.
