### ISSUE TITLE
Beg for feature

### ISSUE THREAD

**Issue by cguerin** [orientechnologies/orientdb#5808]
If there's anyway to add the ability to save queries in the Graph Editor, would be much appreciated featue.

I know you can launch the Graph Editor from the Browser Editor, but... a tool to be able to save queries would save infinite amounts of time copying and pasting from text files every time I update something, like a drop-down menu or something like that.

When developing an ontology using it, its crazy the number of times I have to go back and forth between Schema, Browser and Graph to get a flavor of what's happening and each time... I lose the view.

**Comment by smolinari** [comment]
Here are a couple of related issues (for the ODB devs)
https://github.com/orientechnologies/orientdb/issues/4974
https://github.com/orientechnologies/orientdb/issues/5624

Scott

**Comment by maggiolo00** [comment]
+1

**Comment by maggiolo00** [comment]
@cguerin 

this has been implemented with https://github.com/orientechnologies/orientdb/issues/5425

You can navigate history in Graph with Alt + Up/Down
