### ISSUE TITLE
Can't order edges by size()

### ISSUE THREAD

**Issue by anber500** [orientechnologies/orientdb#5809]
I have a collection of Hash tags and I want to see which hash tags are being used the most.
I'm using the community edition of orientDB on Ubuntu 14.04.

I used the following sql command:

```
select from hashes let $c = in.size() order by $c desc
```

I get back a list of results but the size() is ignored.
I also have one of the results return a -1 on a known size of 45.

```
orientdb {db=myDatabase}> select from hashes let $c = in.size() order by $c desc

----+------+------+----------------------+---------
#   |@RID  |@CLASS|tag                   |in_hash  
----+------+------+----------------------+---------
0   |#17:0 |Hashes|startup               |[size=2] 
1   |#17:1 |Hashes|InternationalWomensDay|[size=-1]
2   |#17:2 |Hashes|InoarThermoliss       |[size=1] 
3   |#17:3 |Hashes|IKnowMyJoburg         |[size=1] 
4   |#17:4 |Hashes|MiddayShowWithVickie  |[size=16]
5   |#17:5 |Hashes|Jp                    |[size=1] 
6   |#17:6 |Hashes|Ongoing               |[size=1] 
7   |#17:7 |Hashes|NEMA                  |[size=1] 
8   |#17:8 |Hashes|LASEMA                |[size=1] 
9   |#17:9 |Hashes|Lekki                 |[size=1] 
10  |#17:10|Hashes|NigeriaSummit         |[size=14]
11  |#17:11|Hashes|Luce                  |[size=3] 
12  |#17:12|Hashes|BoFW                  |[size=3] 
13  |#17:13|Hashes|Iran                  |[size=9] 
14  |#17:14|Hashes|PFW                   |[size=24]
15  |#17:15|Hashes|fashion               |[size=3] 
16  |#17:16|Hashes|AW16                  |[size=6] 
17  |#17:17|Hashes|itsPHC                |[size=1] 
18  |#17:18|Hashes|Nigeria               |[size=16]
19  |#17:19|Hashes|essentials            |[size=1] 
----+------+------+----------------------+---------
LIMIT EXCEEDED: resultset contains more items not displayed (limit=20)

20 item(s) found. Query executed in 0.04 sec(s).
orientdb {db=myDatabase}> 
```

I tried various other methods but I still can't order by size.
Also, why is that one value -1? I know it should be 45.

**Comment by luigidellaquila** [comment]
Hi @anber500 

ORDER BY is currently supported only on projection fields, not on LET variables.
I flagged it as an enhancement, it will be implemented in next releases.

A possible work-around is to rewrite the query as follows:

```
select expand(rid) from (
   select @rid as rid, in().size() as size from hashes order by size desc
)
```

Thanks

Luigi

**Comment by anber500** [comment]
Enhancement? Great news. Looking forward to the "enhanced" release. 
Thanks for the pro tip. Loving your work.

**Comment by anber500** [comment]
@luigidellaquila 
Question: I'm sure it would make sense to veterans of orientDB but how on earth could I have figured that out by looking at the docs? Surely my misguided attempt at sorting should have been obvious by looking at the documentation. What did I miss?

I'm asking this because other people have had similar issues. If not a bug in orientDB, is it an omission in the docs or did I just miss that part?

**Comment by anber500** [comment]
I used the following sql command because it gives me the flexibility to be specific on the in edge that I'm interested in.

    select *, in_hash.size() as size from Hashes order by size desc

the problem is that it's very hard to debug. If I add the wrong name for the incoming edge, I don't get any errors telling me I made a mistake.

**Comment by luigidellaquila** [comment]
Hi @anber500 

I understand your concern, we are working hard to make our docs more structured and complete, but there is still a lot of room for improvements.

About your query, the problem is mainly in the schemaless model, where you can have different attributes on different records and there is no way to validate attribute names at parsing time. It's a common problem for document and graph databases.

Thanks

Luigi

**Comment by anber500** [comment]
I'm learning the ins and outs of graph databases. Knowledge is power and I'm more powerful today than yesterday. Thanks for the feedback.

**Comment by luigidellaquila** [comment]
Hi @lvca 

yes, it should be already supported

Thanks

Luigi
