### ISSUE TITLE
OrientDB 2.1.10 distributed mode: Autodeploy and Replication not happening!!

### ISSUE THREAD

**Issue by srthecodexpress** [orientechnologies/orientdb#5810]
Hi all,
I am testing OrientDB v2.1.10 in distributed mode in a 2 node configuration over 2 different machines.
Connection is happening flawlessly and the two nodes are up and running. However, Autodeploy and Replication is not happening. Given below are the configuration files:
The hazelcast plugin section of the orient-server-config.xml file:
`<handler class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
            <parameters>
                <parameter value="true" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/default-distributed-db-config.json" name="configuration.db.default"/>
                <parameter value="${ORIENTDB_HOME}/config/hazelcast.xml" name="configuration.hazelcast"/>
                <parameter value="node1457502380127" name="nodeName"/>
            </parameters>
</handler>
`
The default-distributed-db-config.json file:
`{
    "autoDeploy": true,
    "hotAlignment": false,
    "executionMode": "undefined",
    "readQuorum": 1,
    "writeQuorum": 2,
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "servers": {
        "*": "master"
    },
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "*": {
            "servers" : [ "<NEW_NODE>" ]
        }
    }
}
`
The hazelcast.xml file:
`<hazelcast
        xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.0.xsd"
        xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <group>
                <name>orientdb</name>
                <password>orientdb</password>
        </group>
        <network>
                <port auto-increment="true">2434</port>
                <join>
                        <multicast enabled="true">
                                <multicast-group>235.1.1.1</multicast-group>
                                <multicast-port>2434</multicast-port>
                        </multicast>
                </join>
        </network>
        <executor-service>
                <pool-size>16</pool-size>
        </executor-service>
</hazelcast>
`

- 

I first checked for Autodeploy using a database I created on the 1st node: testDistributedOrientConfig
On running the 2nd node after the 1st node there is no entry for testDistributedOrientConfig in the 2nd node's startup log. 
Hence, when I try to connect to it from the console of the 2nd node I get an error

orientdb> connect remote:localhost/testDistributedOrientConfig admin admin

Connecting to database [remote:localhost/testDistributedOrientConfig] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OConfigurationException: Database 'testDistributedOrientConfig' is not configured on server (home=/home/../orientdb-community-2.1.10/databases/)

- 

I checked the Replication on the default GratefulDeadConcerts database.
On connecting to the database using the console on the 1st node, i don't get the entry for 2nd node in the members' section in the distributed config

orientdb> connect remote:localhost/GratefulDeadConcerts admin admin       

Connecting to database [remote:localhost/GratefulDeadConcerts] with user 'admin'...OK

DISTRIBUTED CONFIGURATION:
{
  "localName": "_hzInstance_1_orientdb",
  "localId": "20b977ed-6e5a-4ae8-b41c-24bd977fb4d8",
  "members": [
    {
      "id": "20b977ed-6e5a-4ae8-b41c-24bd977fb4d8",
      "name": "node1457502380127",
      "startedOn": "2016-03-09 06:46:47",
      "status": "STARTING",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"192.168.1.5:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"192.168.1.5:2480"}],
      "databases": []
    }
  ]
}

orientdb {db=GratefulDeadConcerts}> 

Similarly, for connecting to the db using 2nd node's console

orientdb> connect remote:localhost/GratefulDeadConcerts admin admin

Connecting to database [remote:localhost/GratefulDeadConcerts] with user 'admin'...OK

DISTRIBUTED CONFIGURATION:
{
  "localName": "_hzInstance_1_orientdb",
  "localId": "9a64e3e4-2bb1-4304-a489-91cf913125e9",
  "members": [
    {
      "id": "9a64e3e4-2bb1-4304-a489-91cf913125e9",
      "name": "node1457502436582",
      "startedOn": "2016-03-09 06:48:03",
      "status": "STARTING",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"127.0.1.1:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"127.0.1.1:2480"}],
      "databases": []
    }
  ]
}
orientdb {db=GratefulDeadConcerts}> 

Hence, when I do an insert from the 2nd node, using:
orientdb {db=GratefulDeadConcerts}> create vertex V set node=2

Created vertex 'V#9:811{node:2} v1' in 0.012000 sec(s).

orientdb {db=GratefulDeadConcerts}> select from V where node=2  

----+------+------+----
#   |@RID  |@CLASS|node
----+------+------+----
0   |#9:811|V     |2   
----+------+------+----

1 item(s) found. Query executed in 0.064 sec(s).
I cannot find the same record at the 1st node:
orientdb {db=GratefulDeadConcerts}> select from V where node=2  

0 item(s) found. Query executed in 0.106 sec(s).

Kindly, shed some light on the issue(s). Any help is much appreciated.
Thanks.

**Comment by lvca** [comment]
This should be fixed in 2.2.0-rc1 and 2.2.0-SNAPSHOT.
