### ISSUE TITLE
Precision is not retained even data type is Decimal

### ISSUE THREAD

**Issue by thirawato** [orientechnologies/orientdb#5811]
The version I am using is 2.1.9.

I inserted data through REST API as below.
```
{
    "@class": "Test",
    "bigDecimal" : 1.00,
    "@fieldTypes": "bigDecimal=c"
  }
```

The response I receive was below. You will see the field bigDecimal has precision lost.
```
{
  "@type": "d",
  "@rid": "#14:5",
  "@version": 1,
  "@class": "Test",
  "bigDecimal": 1,
  "@fieldTypes": "bigDecimal=c"
}
```

**Comment by thirawato** [comment]
I have tested on 2.1.12. it has the same problem as well.

**Comment by thirawato** [comment]
Sorry. The problem is in the test tool, Postman. Please close this issue.

**Comment by luigidellaquila** [comment]
Hi @thirawato 

Ok, thank you very much, closing

Luigi
