### ISSUE TITLE
Missing quotes in in() / out() silently cause wrong output

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#5813]
```
CREATE CLASS Test EXTENDS V
CREATE PROPERTY Test.name String
CREATE VERTEX Test SET name='a'
CREATE VERTEX Test SET name='b'
CREATE CLASS TestEdge EXTENDS E
CREATE EDGE TestEdge FROM (SELECT FROM Test WHERE name='a') TO (SELECT FROM Test WHERE name='b')

# the following returns no records
SELECT expand(out('Nonexistent')) FROM Test WHERE name='a'

# note the missing quotes in the out()
# the following two queries return the same results
SELECT expand(out(Nonexistent)) FROM Test WHERE name='a'
SELECT expand(out()) FROM Test WHERE name='a'
```

The missing quotes should probably cause a parse error, but they are instead silently ignored.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I understand that sometimes it can be tricky, but that statement is a valid one: 'Nonexistent' could be a field name in current record, and its value could be a class name, so in a very corner case it could make sense. 
To make an example, suppose you have a record like
```
{
  @rid: #12:0,
  name: "a",
  Nonexistent: "Foo",
  out_Foo: #13:0
}
```
In this case, the query 
```
SELECT expand(out(Nonexistent)) FROM Test WHERE name='a'
```
would be equivalent (for that particular record) to
```
SELECT expand(out('Foo')) FROM Test WHERE name='a'
```

This is why we cannot throw a parsing exception in this case.

I hope it helps


Thanks

Luigi

**Comment by smolinari** [comment]
@luigidellaquila - You lost me there Luigi. LOL! :smile: I don't understand how both queries can be equivalent. I don't understand how the first one can even work, as "Nonexistent" is neither a collection nor a link. 

Scott

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

`Nonexistent` is evaluated to null, so `out(Nonexistent)` is evaluated as `out(null)`, that is the same as `out()`.
I hope it makes more sense this way...

Thanks

Luigi

**Comment by smolinari** [comment]
Sorry, not really. Because continuing the logic from your first post, `out()` doesn't seem like the same as `out('foo')` to me.

Let me play with this some later at home after work and see if I can understand what is going on.  

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

you are right, it's not the same in general, but in this case (if you only have "foo" edges) the result is the same ;-)

Luigi

**Comment by smolinari** [comment]
I was going to ask if we also had an `out_Bar` property, then it isn't the same. Now I think I got you. :smile: 

Scott

**Comment by obi1kenobi** [comment]
Can `null` be an invalid argument to `out()` such that `out(null)` fails?

**Comment by luigidellaquila** [comment]
well, it could, maybe we can add an option for that, but for backward compatibility we cannot change the default behavior

Thanks

Luigi
