### ISSUE TITLE
OETL randomly stucks

### ISSUE THREAD

**Issue by msusicky** [orientechnologies/orientdb#5815]
OrientDB 2.1.12, Windows 7 64b, JAVA 1.8
I have simple table accounts with 7 columns. I want to import this table to orientdb. I've created a script for oetl and if I run this script without parallel access, all will work.
But if I try to turn the paralelization on, it will often stuck randomly:

OrientDB etl v.2.1.12 (build 2.1.x@rb2f496fd6baa3b845b8f442c0ade5505249336cb; 2016-03-01 08:10:48+00
00) www.orientdb.com
BEGIN ETL PROCESSOR
[file] INFO Reading from file accounts_500k.csv with encoding UTF-8
Started parallel execution with 7 threads
+ extracted 3 504 rows (0 rows/sec) - 3 504 rows -> loaded 1 vertices (0 vertices/sec) Total time: 1
015ms [0 warnings, 0 errors]
+ extracted 8 696 rows (5 120 rows/sec) - 8 696 rows -> loaded 5 188 vertices (5 115 vertices/sec) T
otal time: 2029ms [0 warnings, 0 errors]
+ extracted 11 753 rows (2 970 rows/sec) - 11 753 rows -> loaded 8 245 vertices (2 970 vertices/sec)
 Total time: 3058ms [0 warnings, 0 errors]
+ extracted 11 753 rows (0 rows/sec) - 11 753 rows -> loaded 8 245 vertices (0 vertices/sec) Total t
ime: 4064ms [0 warnings, 0 errors]
+ extracted 11 753 rows (0 rows/sec) - 11 753 rows -> loaded 8 245 vertices (0 vertices/sec) Total t
ime: 5078ms [0 warnings, 0 errors]
+ extracted 11 753 rows (0 rows/sec) - 11 753 rows -> loaded 8 245 vertices (0 vertices/sec) Total t
ime: 6092ms [0 warnings, 0 errors]
+ extracted 11 753 rows (0 rows/sec) - 11 753 rows -> loaded 8 245 vertices (0 vertices/sec) Total t
ime: 7106ms [0 warnings, 0 errors]
+ extracted 11 753 rows (0 rows/sec) - 11 753 rows -> loaded 8 245 vertices (0 vertices/sec) Total t
ime: 8120ms [0 warnings, 0 errors]
+ extracted 11 753 rows (0 rows/sec) - 11 753 rows -> loaded 8 245 vertices (0 vertices/sec) Total t
ime: 9134ms [0 warnings, 0 errors]

**Comment by robfrank** [comment]
we have done some code improvement to avoid this kind od deadlock. Will be in 2.1.13

**Comment by msusicky** [comment]
Thanks for quick reply, but I tried it 5 times and it crashed two times :(
And one new NPE is here. I'm ready to fully cooperate with you, if you are interested, just send me a message.

d:\Prace\orientDB\orientdb-community-2.1.13\bin>oetl.bat account.json
OrientDB etl v.2.1.13 (build 2.1.x@r9bc1a54a4a62c4de555fc5360357f446f8d2bc84; 2016-03-14 17:00:05+00
00) www.orientdb.com
BEGIN ETL PROCESSOR
[file] INFO Reading from file accounts_500k.csv with encoding UTF-8
Started parallel execution with 7 threads
Exception in thread "OrientDB ETL pipeline-0" java.lang.NullPointerException
        at com.orientechnologies.orient.etl.transformer.OVertexTransformer.begin(OVertexTransformer.
java:53)
        at com.orientechnologies.orient.etl.OETLPipeline.begin(OETLPipeline.java:70)
        at com.orientechnologies.orient.etl.OETLProcessor$2.run(OETLProcessor.java:349)
        at java.lang.Thread.run(Thread.java:745)
+ extracted 3 502 rows (0 rows/sec) - 3 502 rows -> loaded 0 vertices (0 vertices/sec) Total time: 1
003ms [0 warnings, 0 errors]
+ extracted 8 799 rows (5 223 rows/sec) - 8 799 rows -> loaded 5 293 vertices (5 219 vertices/sec) T
otal time: 2017ms [0 warnings, 0 errors]
+ extracted 22 400 rows (13 413 rows/sec) - 22 400 rows -> loaded 18 907 vertices (13 426 vertices/s
ec) Total time: 3031ms [0 warnings, 0 errors]
+ extracted 38 995 rows (16 365 rows/sec) - 38 995 rows -> loaded 35 489 vertices (16 353 vertices/s
ec) Total time: 4045ms [0 warnings, 0 errors]
+ extracted 59 135 rows (19 861 rows/sec) - 59 135 rows -> loaded 55 628 vertices (19 860 vertices/s
ec) Total time: 5059ms [0 warnings, 0 errors]
+ extracted 84 117 rows (24 637 rows/sec) - 84 117 rows -> loaded 80 610 vertices (24 637 vertices/s
ec) Total time: 6073ms [0 warnings, 0 errors]
+ extracted 134 301 rows (49 491 rows/sec) - 134 301 rows -> loaded 130 795 vertices (49 492 vertice
s/sec) Total time: 7087ms [0 warnings, 0 errors]
+ extracted 135 601 rows (1 293 rows/sec) - 135 601 rows -> loaded 132 094 vertices (1 292 vertices/
sec) Total time: 8092ms [0 warnings, 0 errors]
+ extracted 135 601 rows (0 rows/sec) - 135 601 rows -> loaded 132 094 vertices (0 vertices/sec) Tot
al time: 9106ms [0 warnings, 0 errors]
+ extracted 135 601 rows (0 rows/sec) - 135 601 rows -> loaded 132 094 vertices (0 vertices/sec) Tot
al time: 10120ms [0 warnings, 0 errors]
+ extracted 135 601 rows (0 rows/sec) - 135 601 rows -> loaded 132 094 vertices (0 vertices/sec) Tot
al time: 11134ms [0 warnings, 0 errors]
+ extracted 135 601 rows (0 rows/sec) - 135 601 rows -> loaded 132 094 vertices (0 vertices/sec) Tot
al time: 12148ms [0 warnings, 0 errors]
+ extracted 135 601 rows (0 rows/sec) - 135 601 rows -> loaded 132 094 vertices (0 vertices/sec) Tot
al time: 13162ms [0 warnings, 0 errors]
+ extracted 135 601 rows (0 rows/sec) - 135 601 rows -> loaded 132 094 vertices (0 vertices/sec) Tot
al time: 14176ms [0 warnings, 0 errors]

**Comment by robfrank** [comment]
The best would be to have the configuration json and a data sample.

**Comment by msusicky** [comment]
Just for the record - config and sample was sent directly to Rob due to privacy reasons :)

**Comment by robfrank** [comment]
Hi, solution to this problem is more complex than expected. My suggestion is to run with parallel set at false. It takes a little bit longer, but on my tests it never locks.

**Comment by msusicky** [comment]
Thanks, I did it this way, but if you have 150M rows, it's a very long procedure :( So I will wait for this fix.

**Comment by sajeevpr** [comment]
Hello robfrank,
   When can we expect this to be fixed?

Regards,
Sajeev

**Comment by robfrank** [comment]
I managed to solve this problem on develop branch. At the moment I can't backport on 2.2.x, too much differences.
