### ISSUE TITLE
Stop OrientDB if -XX:MaxDirectMemorySize is not set

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5816]
Starting from v2.2, OrientDB uses direct buffers. This means it's fundamental the JVM can allocate a big amount of them. The new scripts set `-XX:MaxDirectMemorySize` to a high value, but in case was not set, OrientDB must exit with a clear error message to avoid run-time oddities.

**Comment by taburet** [comment]
Added the check on memory and plocal engines startup.

**Comment by taburet** [comment]
Code reworked, no stop, just warn.
