### ISSUE TITLE
include() stopped working with inline filtering

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#5819]
Hi,

It seems that SQL's `include()` method stopped working  after inline filtering (e.g. `[name='John'].include(...)`)  in version `2.1.12` or possibly any version newer than `2.1.8`, which I am using at the moment

**Test Schema**

```
create class Test extends V
create class linked_to extends E

#creates record #12:0
insert into Test content { "name": "John Doe" } 

#creates record #12:1
insert into Test content { "name": "Dohn Joe" } 

create edge linked_to from #12:0 to #12:1
```

**Queries**
```
#1 WORKS
select expand(out('linked_to').include('@rid')) from #12:0

#2 Does not work
select expand(out('linked_to')[@class='Test'].include('@rid')) from #12:0

#3 Does not work
select expand(outE('linked_to').inV()[@class='Test'].include('@rid')) from #12:0
```

While **no.1** works well, the other 2 stopped working (they do work in `2.1.8` though).

**Workaround**
```
select expand(@this.include('@rid')) from (
   select expand(outE('linked_to').inV()[@class='Test']) from #12:0
)
```

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

Thank you for reporting, I'm checking it right now

Luigi

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

I just pushed a fix on branch 2.1.x, the fix will be released next week with 2.1.13

Now I'm porting it to develop

Thanks

Luigi

**Comment by andreyvk** [comment]
Great! That was quick! ))

**Comment by luigidellaquila** [comment]
Pushed on develop branch as well

I'm closing it, please reopen if you see any other problems

Thanks

Luigi
