### ISSUE TITLE
Bug with sequnce

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#5820]
If sequnce 'hibernate_sequence' is not exist in database 
then query  "select sequence('hibernate_sequence').next()" returns 0.  But it must be a exception because the sequene not exists in database.

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

Thank you for reporting, I'm on it

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed in develop branch (2.2), the fix will be released with 2.2-beta2

Closing, thanks

Luigi
