### ISSUE TITLE
OrientGraph is strangely slower than OrientGraphNoTx when calling `getVertices` inside an Akka actor

### ISSUE THREAD

**Issue by natemurthy** [orientechnologies/orientdb#5822]
I'm looking into a performance characteristic I've observed when using transactional vs non-transactional instances of graphs inside an Akka actor. Here's what my actor looks when I'm using the transactional `OrientGraph`:

``` scala
class EventManager extends Actor {
  def receive = {
    case GetEvent(id) => getEventFromDb(id)
  }

  def getEventFromDb(id): Unit = {
    val origin = sender
    val factory = new OrientGraphFactory(dbUrl,user,paswd).setupPool(1,10)
    var graph: OrientGraph = null
    try { 
      graph = factory.getTx()
      val result = graph.getVertices("event_id",id) // id is unique so guaranteed to be 1 result
      origin ! result
    } finally {
      graph.shutdown()
      factory.close()
    }
  }
}
```

Here's how long it takes to process this:

```
2016-03-12 11:09:16,646 INFO  EventManager - +++++ entering actor ++++++
2016-03-12 11:09:17,601 INFO  orientechnologies - OrientDB auto-config DISKCACHE=9,035MB (heap=926MB os=12,010MB disk=24,689MB)
2016-03-12 11:09:26,749 ERROR application -  Ask timed out on EventManager [10000 ms]. Sender sent message of type "GetEvent"
2016-03-12 11:09:37,940 INFO  EventManager - event found
```

It took over **21 seconds** just to retrieve this single event record vertex from my graph database! And my database just has this one record stored in it! The `ask` I request of the actor times out after 10 seconds. But if I use the non-transactional graph (i.e. use `factory.getNoTx()`), my logs show me the retrieval time is much faster:

```
2016-03-12 11:43:20,489 INFO  EventManager - +++++ entering actor ++++++
2016-03-12 11:43:21,310 INFO  orientechnologies - OrientDB auto-config DISKCACHE=9,036MB (heap=926MB os=12,010MB disk=24,688MB)
2016-03-12 11:43:23,665 INFO  EventManager - event found
```

This query takes just **3 seconds**. What could possibly be going on here? I know that since I'm inside an actor there may be some thread pool configuration I could tweak (I'm using just the default Akka dispatcher - http://doc.akka.io/docs/akka/2.4/scala/dispatchers.html#Default_dispatcher). Understandably, there may be something Akka is doing that's slowing down the retrieval time of this operation that I can improve by doing something fancier with the executor in my app. But could there be something inefficient OrientDB is doing when running transactional graphs on top of this thread pool? This performance is just absolutely bizarre.

_Note: In practice I'd only create a graph factory once and re-use that for the duration of my application lifetime, but I wanted to also benchmark the time it takes setting up a connection to the DB as well as creating an instance of a graph._

**Comment by lvca** [comment]
I think you're not using the index here. Look at: http://orientdb.com/docs/last/Graph-Schema.html#indexes-as-constrains. You should do:

    val result = graph.getVertices("Event.event_id",id) // id is unique so guaranteed to be 1 result

If the class is called 'Event'.

**Comment by natemurthy** [comment]
I actually have an index on this field. This is what my schema looks like:

```
CREATE CLASS EventRecord EXTENDS V;
CREATE PROPERTY EventRecord.event_id STRING;
CREATE PROPERTY EventRecord.event_log STRING;
CREATE INDEX EventRecord.event_id UNIQUE;
```
