### ISSUE TITLE
OrientDB Workbench not picking up settings from hazelcast.xml

### ISSUE THREAD

**Issue by davidheryanto** [orientechnologies/orientdb#5823]
Hi, I'm testing the Workbench 2.1.6 from the OrientDB Enterprise 2.1.12. And I have a difficulty adding a cluster to be monitored. I'm using _multicast_ for discovering the nodes in the cluster.

The problem is I have multiple _multicast capable_ network interfaces and the workbench always picks up the wrong interface (and hence the wrong IP for my nodes).

For OrientDB server, I can configure which interfaces Hazelcast should listen to by adding

```
<interfaces enabled="true">
  <interface>10.120.30.*</interface>
</interfaces>
```

So for eg, I have 2 interfaces (`192.10.1.20` and `10.120.30.5`), by adding the config above, Hazelcast will pick up `10.120.30.5`

For the workbench, however, even after adding the setting for interfaces at `hazelcast.xml`, Hazelcast still pick up the wrong interface `192.10.1.20`. As a result, I cannot add the cluster to the workbench.

Using TCP/IP, or disabling the other multicast interface solves the problem. But I would prefer being able to use the default multicast setting and adding `<interfaces enabled="true"><interface> ...` to choose the interface Hazelcast should use in workbench.

**Comment by maggiolo00** [comment]
hi @davidheryanto 

Workbench does not read the hazelcast.xml. It is configured at runtime. We could add the interface configuration in the WB ui.

**Comment by davidheryanto** [comment]
Hi Risa. Yes, I think it would be great to be able to configure it from the UI (or at least add the option to use default hazelacast.xml or specify our own xml). Thanks

**Comment by santo-it** [comment]
Hi,

Workbench has been replaced by the tool Studio in v 2.2.

2.1 is expected to enter EOL in February 2017. If you are still using 2.1, please do consider upgrading to 2.2

I'm adding label Studio so that Product Management can have a chance to review this issue and see if this is still current in 2.2 and in case take action

Many Thanks,

**Comment by lvca** [comment]
Workbench is not part of OrientDB Enterprise distribution anymore.
