### ISSUE TITLE
I need to find better performance for a geolocation query

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5825]
the following query take about 20 seconds for more than 30k records. 
are you sure your database is really promised in market?

```
select @rid.in() AS rid,
distance(lat, lng, 3.0797, 101.5186) AS distance,
@rid.in().out("act")[@class="activity"].total[0] AS activity
from place
where @rid.in()[0].@class in ['user', 'hotel'] 
ORDER BY (distance ASC), (activity DESC)
limit 10
```

**Comment by luigidellaquila** [comment]
Hi @martingg88 

this query has to 
- browse all the `place` class
- traverse the in() relationship to filter based on @class (user, hotel)
- for each record
  - calculate a distance() function
  - traverse all the in() edges and for each corresponding vertex
     - traverse all the out("act")
     - filter by @class
- sort the results
- only after that, apply the limit

Depending on how many incoming and outgoing edges you have, this can lead to visiting a lot of paths.

I think it can be optimized a bit, eg. you can try

```
select $incoming AS rid,
distance(lat, lng, 3.0797, 101.5186) AS distance,
$incoming.out("act")[@class="activity"].total[0] AS activity
from place
let $incoming = in()
where $incoming[0].@class in ['user', 'hotel'] 
ORDER BY (distance ASC), (activity DESC)
limit 10
``` 
or even better, you can rewrite it to narrow the number of traversed relationships

thanks

Luigi

**Comment by martingg88** [comment]
Thanks for your effort. But it still take about more than 18 seconds to get only the 10 records. I think the order by alias property cause the huge performance issue. Here is the explain for your given SQL statement. 

{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "fullySortedByIndex": false,
            "documentReads": 46145,
            "incoming": [
                "#16:9"
            ],
            "current": "#34:1",
            "documentAnalyzedCompatibleClass": 46145,
            "recordReads": 46145,
            "fetchingFromTargetElapsed": 17770,
            "indexIsUsedInOrderBy": false,
            "orderByElapsed": 27,
            "evaluated": 46145,
            "elapsed": 17799.918,
            "resultType": "collection",
            "resultSize": 10,
            "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,orderByElapsed=l,evaluated=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 18.684 sec. Returned 1 record(s)"
}

**Comment by martingg88** [comment]
FYI. The following SQL statement without order clause will be more faster. 

select $incoming AS rid,
distance(lat, lng, 3.0797, 101.5186) AS distance,
$incoming.out("act")[@class="activity"].total[0] AS activity
from place
let $incoming = in()
where $incoming[0].@class in ['user', 'hotel'] 
limit 10

**Comment by luigidellaquila** [comment]
Hi @martingg88 

can you give me some more details about your domain? Maybe we can optimize the query a lot based on the graph topology:
- how many users/hotels do you have?
- how many places do you have?
- how many places are connected to hotels/users?
- can you think to limit the lat-lng to a bounding box? eg. `x1 < lat < x2` , this way you can define an index on [lat] and do indexed queries. 

In v 2.2 there is a geospatial engine that can help on this use case, but unfortunately it's not available in v.2.1

Thanks

Luigi

**Comment by martingg88** [comment]
how many users/hotels do you have?
more than 40K
how many places do you have?
more than 40k
how many places are connected to hotels/users?
more than 40k
can you think to limit the lat-lng to a bounding box? eg. x1 < lat < x2 , this way you can define an index on [lat] and do indexed queries.
Yes I didn't bounding query clause and it will help, but it will be very slow again if i add order clause by alias property like "distance".

**Comment by maggiolo00** [comment]
hi @martingg88 

if you want to sort by distance you can use the spatial index and do the near filtering

http://orientdb.com/docs/2.1/Spatial-Index.html

**Comment by martingg88** [comment]
I'm expect to have records that are sorting from near to far. what is your suggestion?

**Comment by maggiolo00** [comment]
hi @martingg88 

with near filter the records should be ordered by distance. You don't have to call distance function.

**Comment by martingg88** [comment]
The near filter is just for query the records in bounding area. we need the records to be displayed from near to much more far by using paging. do you understand my question?

**Comment by martingg88** [comment]
any update for this issue?

**Comment by smolinari** [comment]
Can someone please change the title to something like, "I need to find better performance for a geolocation query"? Thanks!

Scott
