### ISSUE TITLE
Improve locks

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5826]
I found something that eats my CPU to 100%:
```
while (!distributedCounter.isEmpty())
  ;
```
in OReadersWriterSpinLock.acquireWriteLock(), I didn't study the algorithm, but a Thread.sleep(1) would be necessary.

The reason for locks is that while a thread is waiting for another one, it frees the resources for something other

in this way the CPU is taken just to check if the condition is true

Or we could even better use a wait/notify mechanism, but not the `while(true);`.

**Comment by laa** [comment]
Hi  @lvca could you provide reference to test which caused you to create given issue ?

**Comment by lvca** [comment]
Sorry, I forgot the case, but my CPU as at 100% waiting.

**Comment by laa** [comment]
It is really hard to test in such case :-( . Well we will come up with something.

**Comment by laa** [comment]
I will provide small workaround for 2.2 version and complete fix will be in 3.0 to do not break release stability.

**Comment by laa** [comment]
Closed in favor of https://github.com/orientechnologies/orientdb/issues/6037
