### ISSUE TITLE
com.orientechnologies.common.concur.lock.OLockException. File 'internal.cpm' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database

### ISSUE THREAD

**Issue by chandra-n** [orientechnologies/orientdb#5827]
Guys
         Post an ungraceful shutdown of the server (owing to server unresponsiveness), once the server has been restarted, no connections are being entertained by the server. I see the error:

> Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb-community-2.1.12/databases/devOne' with mode=rw
> 
> Error: com.orientechnologies.common.concur.lock.OLockException: File '/opt/orientdb-community-2.1.12/databases/devOne/internal.cpm' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database

when I try to connect to the server from the console. 

lsof command to check for any locks on the file yields the below output:

> sudo lsof /opt/orientdb-community-2.1.12/databases/devOne/internal.cpm 
> COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
> java    2182 ec2-user   89uW  REG  202,1    66560 268452 /opt/orientdb-community-2.1.12/databases/devOne/internal.cpm
> java    2182 ec2-user  454uW  REG  202,1    66560 268452 /opt/orientdb-community-2.1.12/databases/devOne/internal.cpm
> java    2182 ec2-user  455uW  REG  202,1    66560 268452 /opt/orientdb-community-2.1.12/databases/devOne/internal.cpm

Process 2182 is nothing but the Orientdb server:

> 2182 ?        Sl     0:04 java -server -Xms256m -Xmx256m -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dprofiler.enabled=true -Dstorage.diskCache.bufferSize=620 -Djava.util.logging.config.file=/opt/orientdb-community-2.1.12/config/orientdb-server-log.properties -Dorientdb.config.file=/opt/orientdb-community-2.1.12/config/orientdb-server-config.xml -Dorientdb.www.path=/opt/orientdb-community-2.1.12/www -Dorientdb.build.number=2.1.x@rb2f496fd6baa3b845b8f442c0ade5505249336cb; 2016-03-01 08:10:48+0000 -cp /opt/orientdb-community-2.1.12/lib/orientdb-server-2.1.12.jar:/opt/orientdb-community-2.1.12/lib/* com.orientechnologies.orient.server.OServerMain

Can you please help me?

**Comment by maggiolo00** [comment]
hi @chandra-n 

seems that the process is still running and holding the locks to the database

try to run jps you should see two OServerMain.

**Comment by chandra-n** [comment]
Nope. Just one. Here you go:

> /opt/jdk/jdk1.8.0_60/bin/jps 
> 2182 OServerMain
> 1387 Apollo
> 2365 Jps

**Comment by laa** [comment]
Hi, that is OS issue. OS puts the process level lock and after process crash fails to clear it. We have encountered that in several users could you restart OS and try again ?

**Comment by chandra-n** [comment]
@laa,  
           I am afraid that did not work either. Here you go:

> [ec2-user@ip-172-31-62-18 ~]$ /opt/orientdb-community-2.1.12/bin/orientdb.sh status
> OrientDB server daemon is running with PID: 1389
> [ec2-user@ip-172-31-62-18 ~]$ /opt/orientdb-community-2.1.12/bin/console.sh 
> 
> OrientDB console v.2.1.12 (build 2.1.x@rb2f496fd6baa3b845b8f442c0ade5505249336cb; 2016-03-01 08:10:48+0000) www.orientdb.com
> Type 'help' to display all the supported commands.
> Installing extensions for GREMLIN language v.2.6.0
> 
> orientdb> connect remote:localhost/devOne admin xxxxxxxxxxx
> 
> Connecting to database [remote:localhost/devOne] with user 'admin'...
> Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb-community-2.1.12/databases/devOne' with mode=rw
> 
> Error: com.orientechnologies.orient.core.exception.OStorageException: Error during checkpoint creation for storage devOne
> 
> Error: java.io.FileNotFoundException: /opt/orientdb-community-2.1.12/databases/devOne/devOne.1641.wal (Permission denied)
> 
> orientdb> exit 
> 
> [ec2-user@ip-172-31-62-18 ~]$ /opt/orientdb-community-2.1.12/bin/orientdb.sh status
> OrientDB server daemon is running with PID: 1389
> [ec2-user@ip-172-31-62-18 ~]$ /opt/orientdb-community-2.1.12/bin/orientdb.sh stop
> Stopping OrientDB server daemon...
> Password: 
> [ec2-user@ip-172-31-62-18 ~]$ /opt/orientdb-community-2.1.12/bin/orientdb.sh status
> OrientDB server daemon is NOT running
> [ec2-user@ip-172-31-62-18 ~]$ sudo reboot now
> 
> Broadcast message from ec2-user@ip-172-31-62-18.ec2.internal
> 	(/dev/pts/0) at 12:51 ...
> 
> The system is going down for reboot NOW!
> [ec2-user@ip-172-31-62-18 ~]$ Connection to ec2-54-210-131-201.compute-1.amazonaws.com closed by remote host.
> Connection to ec2-54-210-131-201.compute-1.amazonaws.com closed.
> kokate@ghost:~$ ssh aws_1
> Last login: Mon Mar 14 12:50:23 2016 from 
> [ec2-user@ip-172-31-62-18 ~]$ /opt/orientdb-community-2.1.12/bin/orientdb.sh status
> OrientDB server daemon is NOT running
> [ec2-user@ip-172-31-62-18 ~]$ /opt/orientdb-community-2.1.12/bin/orientdb.sh start
> Starting OrientDB server daemon...
> Password: 
> [ec2-user@ip-172-31-62-18 ~]$ /opt/orientdb-community-2.1.12/bin/orientdb.sh status
> OrientDB server daemon is running with PID: 1381
> [ec2-user@ip-172-31-62-18 ~]$ /opt/orientdb-community-2.1.12/bin/console.sh 
> 
> OrientDB console v.2.1.12 (build 2.1.x@rb2f496fd6baa3b845b8f442c0ade5505249336cb; 2016-03-01 08:10:48+0000) www.orientdb.com
> Type 'help' to display all the supported commands.
> Installing extensions for GREMLIN language v.2.6.0
> 
> orientdb> connect remote:localhost/devOne admin xxxxxxxxxxx
> 
> Connecting to database [remote:localhost/devOne] with user 'admin'...
> Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb-community-2.1.12/databases/devOne' with mode=rw
> 
> Error: com.orientechnologies.orient.core.exception.OStorageException: Error during checkpoint creation for storage devOne
> 
> Error: java.io.FileNotFoundException: /opt/orientdb-community-2.1.12/databases/devOne/devOne.1641.wal (Permission denied)
> 
> orientdb> connect remote:localhost/devOne admin p@nd@g@chesuko
> 
> Disconnecting from the database [null]...OK
> Connecting to database [remote:localhost/devOne] with user 'admin'...
> Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb-community-2.1.12/databases/devOne' with mode=rw
> 
> Error: com.orientechnologies.common.concur.lock.OLockException: File '/opt/orientdb-community-2.1.12/databases/devOne/internal.cpm' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database
> 
> orientdb> exit
> 
> [ec2-user@ip-172-31-62-18 ~]$ sudo lsof /opt/orientdb-community-2.1.12/databases/devOne/internal.cpm
> COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
> java    1381 ec2-user   84uW  REG  202,1    66560 268452 /opt/orientdb-community-2.1.12/databases/devOne/internal.cpm
> java    1381 ec2-user  448uW  REG  202,1    66560 268452 /opt/orientdb-community-2.1.12/databases/devOne/internal.cpm
> [ec2-user@ip-172-31-62-18 ~]$ /opt/jdk/jdk1.8.0_60/bin/jps
> 1444 Jps
> 1381 OServerMain
> [ec2-user@ip-172-31-62-18 ~]$

**Comment by chandra-n** [comment]
Gents 
          I would really appreciate if you can help me with a temporary workaround to get the server up and running while you work towards a solution.

**Comment by laa** [comment]
@chandra-n well that is simple start server with property file.lock set to false

**Comment by chandra-n** [comment]
@laa I am sorry, did you mean a property within orientdb's config? As otherwise, the OS has got no locks on the internal.cpm file when the server is not running. When the server is started, it seems to lock the file out somehow and not allow access.

**Comment by laa** [comment]
@chandra-n that is because file metadata is broken. I think the most simplest fix is to copy all files to another location, delete current one and rename it  if you wish.

**Comment by chandra-n** [comment]
@laa that did not work either. Here is what I did:
Made a copy of the database folder, got rid of the original installation.
Rebooted the host.
Did a fresh installation of the server software (at the same location as earlier)
Ran the server once and shut it down.
Created the database folder copied previously in the databases folder.
Ran the server and tried connecting from the console.

> orientdb> connect remote:localhost/devOne admin
> Enter password: 
> 
> Connecting to database [remote:localhost/devOne] with user 'admin'...
> Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb-community-2.1.12/databases/devOne' with mode=rw
> 
> Error: com.orientechnologies.orient.core.exception.OStorageException: Error during checkpoint creation for storage devOne
> 
> Error: java.io.FileNotFoundException: /opt/orientdb-community-2.1.12/databases/devOne/devOne.1641.wal (Permission denied)
> 
> orientdb> 


What do you think is going on?

**Comment by laa** [comment]
@chandra-n are you using correct user to start server, because it looks like sever used do not have permissions to access db files.
what is result of `ls -l` on database directory ?

**Comment by chandra-n** [comment]
@laa Sorry about the delay in my response. Unfortunately, my situation was such that I could not wait for a resolution, I ended up importing a previous snapshot of the database file. Having said that, I am pretty certain that the user account used to start the server is the same as I have always been doing and I have never faced this issue. 

I just ran an ls -l on the affected database directory, all the files are owned by the orientdb user and group. Attached is the file listing.
[dbdir_listing.txt](https://github.com/orientechnologies/orientdb/files/178451/dbdir_listing.txt)

**Comment by laa** [comment]
@chandra-n sorry but I am sure that is OS exception. We only call single method which delegates to OS to acquire process locks on files. During process crash OS should release lock but it did  not do this which causes problems. To avoid this in future I would recommend you to use following property `file.lock=false` .

**Comment by chandra-n** [comment]
@laa, thanks a lot for your follow up. I will keep the property in mind. Are there any issues I should be wary of when I set file locking to false?

**Comment by laa** [comment]
You can not connect using plocal: from several JVMs also you can not connect to running server using plocal: the rest is OK :-)

**Comment by nishantkumar1292** [comment]
Hi @laa ... I was just performing a stress test on OrientDB server and ran the following command.
`./stresstester.sh -m remote -c 10000 -w crud:C1000000R1000000U1000000D1000000 --remote-ip localhost `

The database was droppped and the task did not execute till completion. Error log:
```
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open a connection to remote server: 127.0.0.1:2424/stress-test-db-20170728_114651
        DB name="stress-test-db-20170728_114651"
        at com.orientechnologies.orient.client.remote.OStorageRemote.getNetwork(OStorageRemote.java:2210)
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:224)
        at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperation(OStorageRemote.java:158)
        at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:553)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2206)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:241)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:171)
        ... 17 more
Caused by: com.orientechnologies.common.concur.lock.OLockException: No more resources available in pool (max=100). Requested resource: 127.0.0.1:2424/stress-test-db-20170728_114651
        at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:66)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionPool.acquire(ORemoteConnectionPool.java:98)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.acquire(ORemoteConnectionManager.java:101)
        at com.orientechnologies.orient.client.remote.OStorageRemote.getNetwork(OStorageRemote.java:2206)
        ... 23 more
- Workload in progress 24% [Creates: 99% - Scans: 0% - Reads: 0% - Updates: 0% - Deletes: 0%]
An error has occurred while running the stress test: null

Dropped database [remote:localhost:2424/stress-test-db-20170728_114651].
```

Any ideas... how I could resolve this?
