### ISSUE TITLE
Invalid JSON result on HTTP API request

### ISSUE THREAD

**Issue by IamKazuya** [orientechnologies/orientdb#5829]
Hello,

When i send a REST request on an index containing multiple results, the json returned contains the list of expected vertices, but, the json is not valid. So, using a REST tool requester return me a parse error.

Example of request : http://orientb.mydomain.com/index/mydb/server.name/toto*
JSON response format :
[
     {"key" : "value", ...}
     {"key" : "value", ...}
     {"key" : "value", ...}
]

as you can see, there is no comma separating the vertices.

Index is Fulltext / Lucene
Orientdb version : 2.1.12

Thank you for your help.

**Comment by luigidellaquila** [comment]
Hi @IamKazuya 

Thank you for reporting, I'm on it

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @IamKazuya 

I just pushed a fix for this problem,  you can find it in 2.1.x and develop branches.

The fix will be released with 2.1.14 and 2.2 beta2

Thanks

Luigi

**Comment by IamKazuya** [comment]
Oh, thank you so much for your reactivity !
