### ISSUE TITLE
Composite index issue

### ISSUE THREAD

**Issue by thierry-github** [orientechnologies/orientdb#5830]
using OrientDB 2.1.9

I have a record (E_Rel) with 3 fields :

- SrcID (long)
- RelID (long)
- VTgtDef (EmbeddedList of Long)

and an index on record 
CREATE INDEX RelTgtIDX ON E_Rel (SrcID , RelID , VTgtDef ) NOTUNIQUE

This query works as expected  :
select  from index:RelTgtIDX where  Key  = [6,572]

The result is (from studio view)
	
OCompositeKey{keys=[6, 572, 472]}
CompositeKey{keys=[6, 572, 472]}
OCompositeKey{keys=[6, 572, 472]}
OCompositeKey{keys=[6, 572, 472]}
OCompositeKey{keys=[6, 572, 472]}
OCompositeKey{keys=[6, 572, 472]}
OCompositeKey{keys=[6, 572, 472]}
OCompositeKey{keys=[6, 572, 472]}

but this one returns no results !
select  from index:RelTgtIDX where  Key  = [6,572,472]

Any idea ?

**Comment by tglman** [comment]
hi @thierry-github,

A Similar issue was fixed not so long ago, did you have chance to try the last hotfix 2.1.12 ?

**Comment by thierry-github** [comment]
hi @tglman 

just downloaded and try 2.1.13 version with the same issue

first query : 

select from index:data.SrcID_RelID_Tgt 

OCompositeKey{keys=[1, 1, 0]}
OCompositeKey{keys=[1, 1, 0]}
OCompositeKey{keys=[1, 1, 0]}
OCompositeKey{keys=[1, 1, 1]}
OCompositeKey{keys=[1, 1, 1]}
OCompositeKey{keys=[1, 1, 1]}
OCompositeKey{keys=[1, 1, 2]}
OCompositeKey{keys=[1, 1, 2]}
OCompositeKey{keys=[1, 1, 3]}

second query : 
select from index:data.SrcID_RelID_Tgt where key = [1,1]

OCompositeKey{keys=[1, 1, 0]}
OCompositeKey{keys=[1, 1, 0]}
OCompositeKey{keys=[1, 1, 0]}
OCompositeKey{keys=[1, 1, 1]}
OCompositeKey{keys=[1, 1, 1]}
OCompositeKey{keys=[1, 1, 1]}
OCompositeKey{keys=[1, 1, 2]}
OCompositeKey{keys=[1, 1, 2]}
OCompositeKey{keys=[1, 1, 3]}

third query : 
select from index:data.SrcID_RelID_Tgt where key = [1,1,3]

**Comment by thierry-github** [comment]
@tglman 

there is no result for the third query.

**Comment by luigidellaquila** [comment]
Hi @thierry-github 

quick update on this, if you try the following query, it will work fine:

```
 select from index:RelTgtIDX where Key = [6,572,[472]]
```

I'm working to rationalize the `SELECT FROM index:` syntax, IMHO the expected behavior is not clear and it requires a little formal definition.

I'll keep you posted

Thanks

Luigi

**Comment by thierry-github** [comment]
@luigidellaquila 

great ! that's what i was looking for. I've tried it and it works as expected.

Thanks

**Comment by luigidellaquila** [comment]
Perfect, Thanks!

Closing

Luigi

**Comment by luigidellaquila** [comment]
reopening, I have to check a couple of things

**Comment by luigidellaquila** [comment]
Ok, I also fixed the base case, now your original query will work fine.

The fix will be released with 2.1.14

Thanks

Luigi
