### ISSUE TITLE
exponential performance drop with OEntityManager.registerEntityClass after update to 2.1.12

### ISSUE THREAD

**Issue by zerovian** [orientechnologies/orientdb#5831]
orientdb 2.1.12 + 2.1.13

Performance of OEntityManager.registerEntityClass() has dropped dramatically after updating from 2.1.11 to 2.1.12.  

I have a newly created database and am registering about 30 classes using db.getEntityManager().registerEntityClass(<class>);

Prior to It used to take about 2 seconds to register all of them. After the update to 2.1.12, this now takes about 1 second for the first one, and each successive call gets slower and slower. 

It gets to the point where somewhere around the 20th class it never finishes.  This is much worse if there is already data in the database.

**Comment by zerovian** [comment]
[entityperformance.zip](https://github.com/orientechnologies/orientdb/files/174225/entityperformance.zip)

**Comment by zerovian** [comment]
Attached a zip file with a sample that shows the problem.  Run TestEntityLoad.main() This loads about 7 classes and creates a property and an index on that one property.  Each successive class takes longer than the previous.  The first takes about 130ms.  But the time it reaches the 7th class it takes almost 1 full second to register the class.  In my full codebase, by the time it hits the 30 it never finishes.

**Comment by zerovian** [comment]
I've tried with 2.1.16

None of these have any affect.
-Ddb.makeFullCheckpointOnSchemaChange=false
-Ddb.makeFullCheckpointOnIndexChange=false
-Dstorage.makeFullCheckpointAfterCreate=false
-Dstorage.makeFullCheckpointAfterClusterCreate=false

My CPU is pegged at 23% (4 core machine) while trying to register entities.  Never finishes.

**Comment by zerovian** [comment]
Screen grab from Yourkit image.  3 calls to registerEntities() 100,000 calls to OIndexManager.toStrim()

![image](https://cloud.githubusercontent.com/assets/3799244/14749872/ec44118e-088f-11e6-9c25-e788b68c6eda.png)

I can share full yourkit snapshot if that helps.

**Comment by tglman** [comment]
hi @zerovian,

Thank you for so precisely pin point the problem, I did a fix in the 2.1.x branch that should fix the problem.

It should go out with the next hotfix.

Regards.

**Comment by wouterv** [comment]
Lol, I was about to go fix this, because we had the same problem, so I checked out 2.1.x branch and I found the fix already there, thanks :+1: 
When can we expect the 2.1.17 hotfix?

**Comment by tglman** [comment]
so this should be fixed closing.
