### ISSUE TITLE
Manual index entries not persisted through a server restart

### ISSUE THREAD

**Issue by fpertl** [orientechnologies/orientdb#5832]
Create a manually created index:
`CREATE INDEX md5 UNIQUE_HASH_INDEX;` 
then manually population the index via inserts with keys and rids.
Then querying the index 
e.g.  `SELECT FROM INDEX:md5 WHERE key = '06700B2BD5AA941B9755B49C129BD66E'`
returns the stored rid as expected, but if the server is restarted, nothing is returned.
However 
`SELECT COUNT(*) FROM INDEX:md5 `
will return the correct count for the previous inserts...

The type of index does not seem to matter.

**Comment by laa** [comment]
Hi, what version do you use ?

**Comment by fpertl** [comment]
I'm using 2.1.10 community.

**Comment by taburet** [comment]
@fpertl I have investigated the issue and found that automatic key type detection behaviour is unreliable, we have decided to deprecate untyped indexes. As a workaround pease specify an index key type while creating the index, like this:

`CREATE INDEX md5 UNIQUE_HASH_INDEX STRING;`

**Comment by fpertl** [comment]
Thanks for resolving this :)
