### ISSUE TITLE
Strange behaviour in JS functions

### ISSUE THREAD

**Issue by warriorkitty** [orientechnologies/orientdb#5834]
Hi all! First of all, this is the first version of the algorithm, so I know things could get done little better. I'm implementing Pearson's correlation coefficient.

1. get all movies I rated
2. get all movies from other users
3. find intersections
4. calculate the similarity coefficient

Look at the line before `return movies`. If I execute queries directly, I get the list of movies for `userId = 1`.

```javascript
var gdb = orient.getGraph();

// get all movies from user
var movies = gdb.command( "sql", "select movieId, name from (select expand(out('Rate')) from User where userId = ?);", [ userId ] );

var allUsers = gdb.command( "sql", "select userId from User;" );

for(var i = 0; i < allUsers.length; ++i) {
  var user = allUsers[i];
  
  // get all movies user rated
  var movies = gdb.command( "sql", "select movieId, name from (select expand(out('Rate')) from User where userId = ?);", [ user.userId ] );
  
  // testing
  return movies;
}

```

When I return a user, I get:
```
[
    {
        "@type": "d",
        "@rid": "#-2:0",
        "@version": 0,
        "userId": 1
    }
]
```

My conclusion is that I cannot get the value `user.userId` from the top of the for loop. When I execute the SQL directly:

```sql
select movieId, name from (select expand(out('Rate')) from User where userId = 1);
```
I get the results:

```
1       Toy Story (1995)
266    Legends of the Fall (1994)
```

**Comment by luigidellaquila** [comment]
Hi @warriorkitty 

I think the user is an ODocument (a Java object), not a JS one, could you please try with
```
var movies = gdb.command( "sql", "select movieId, name from (select expand(out('Rate')) from User where userId = ?);", [ user.field("userId") ] );
```
and let me know if it works?

Thanks

Luigi

**Comment by warriorkitty** [comment]
I've tried returning the value:

```
return { userId: user.field("userId") };
```

Getting an error:

```
Error on parsing script at position #0: Error on execution of the script\nScript: getRecommendations\n------^\nTypeError: v(null)[#-2:0] has no such function \"field\" in <eval> at line number 13\nTypeError: v(null)[#-2:0] has no such function \"field\"
```

**Comment by luigidellaquila** [comment]
Ops, sorry, you are using the Graph API (not Document), so the query is returning a vertex.

This is the right syntax:
```
return { userId: user.getProperty("userId") };
```

Thanks

Luigi

**Comment by warriorkitty** [comment]
That works. You are awesome, as usual. Thank you.
