### ISSUE TITLE
Support for JSON body in POST requests to the /import/<database> endpoint

### ISSUE THREAD

**Issue by whatyouhide** [orientechnologies/orientdb#5837]
Right now, the `/import/<database>` endpoint accepts only `multipart/form-data` data. Since we're uploading a JSON document, it would make sense to accept an `application/json` body so that users can directly upload the exported JSON database.

Also, it seems like the `multipart/form-data` import is somehow broken. Much more information can be found in https://github.com/MyMedsAndMe/marco_polo/issues/25.

/cc @tglman

**Comment by tglman** [comment]
added the sopport

**Comment by whatyouhide** [comment]
@tglman I don't see any new commits here on GH; will this be part of an upcoming release of `2.2-beta`? If so, when can we expect the new release? Thanks so much :heart_decoration:!

**Comment by tglman** [comment]
hi @whatyouhide, 

I put the wrong id  in the commit sorry, here we go: https://github.com/orientechnologies/orientdb/commit/253e3cf7f3ac001fbb589a6e952bb038364d0faf

bye
