### ISSUE TITLE
Unable to start orientdb service on windows 8

### ISSUE THREAD

**Issue by kondareddy** [orientechnologies/orientdb#5840]
I have followed the instructions mentioned on below page and installed orientdb as a service but unable to start that.
http://orientdb.com/docs/2.1/Windows-Service.html

I am getting below exception
Windows could not start the OrientDB GraphEd X.X.X on Local Computer. For more information, review the System Event Log. If this is a non-Microsoft service, contact the service vendor, and refer to service-specific error code 4.

FYI - event log

 <Data Name="param1">OrientDB GraphEd X.X.X</Data> 
  <Data Name="param2">%%4</Data> 

Thanks for your help in advance.
Thanks
Konda Reddy.

**Comment by santo-it** [comment]
Hi,

Thanks for opening this issue. OrientDB 2.1 is EOL. I wonder if this is still happening with 2.2-GA or 3.0-snapshot?

I'll give this a try on Windows 10 as soon as it will be possible

Link to the 2.2. doc: http://orientdb.com/docs/2.2.x/Windows-Service.html

Many thanks,
