### ISSUE TITLE
Record locking is broken in 2.2 version

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5844]
After implementation of scan of pages inside of storage record locking functionality is broken.
In internal discussion we decided to introduce new keyword to lock records only if it is requested.

As @tglman correctly mentioned we already have lock record, so would be good to keep the same syntax add new keyword READ_LOCK RECORD.

I think to keep all project functionality working it should be done in 2.2 release.

**Comment by laa** [comment]
Assign it to @lvca according to internal conversation with him.

**Comment by lvca** [comment]
Assigned to @taburet

**Comment by laa** [comment]
@lvca cold you do no assign issues directly. We work as a team and during bug fixing phase very one takes issues in a pool. To assign an issue to us better to set "storage team" label.

**Comment by laa** [comment]
Well, I do not know  current SQL parser and @luigidellaquila will add this keyword much faster than me. Anyway, it is SQL, not storage feature. Assigned to @luigidellaquila

**Comment by luigidellaquila** [comment]
@laa are you sure it is an sql issue...? I can add the sql syntax of course, but what's the low level api to invoke? And does it work correctly?

**Comment by laa** [comment]
Hi @luigidellaquila , provide me means to detect the flag in SQL executor and I will do the rest in 1 hour.

**Comment by luigidellaquila** [comment]
Hi @laa 

it is already managed in the executor, see OCommandExecutorSQLSelect, row 550-560

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @laa 

I just pushed a fix that supports `SELECT ... LOCK SHARED` syntax. The executor part seems to be already there, but for sure it was never used, because the parsing layer has never supported it, so please take a look at OCommandExecutorSQLSelect, row 550-560 to make sure that everything is correct.

Thanks

Luigi
