### ISSUE TITLE
Projection query with non-existing field does not return an empty set of records ?

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5845]
Hi, 
perhaps this is a known issue, or maybe I am missing something here but could you please explain why  I am getting back records instead of an empty list when I issue an SQL command query of the form

`select  "XGDFGKWOERKTHJDERGGDH" from V`

If there is not any record with a "XGDFGKWOERKTHJDERGGDH" field then it should return 0 record(s) or an error, or perhaps a warning 

I am testing the latest OrientDB 2.1.13 community version.

PS: It is even worse when you analyze the HTTP response, if you pass the projection argument unquoted e.g.

`select  XGDFGKWOERKTHJDERGGDH from V`

**Comment by luigidellaquila** [comment]
Hi @healiseu 

that query is the same as
```
select "XGDFGKWOERKTHJDERGGDH" as XGDFGKWOERKTHJDERGGDH from V
```
so it just scans all the V class and for each row returns a record with a single value

{ XGDFGKWOERKTHJDERGGDH: "XGDFGKWOERKTHJDERGGDH"}

The second query returns empty records, one per existing vertex. They are empty because your vertices do not have an attribute called XGDFGKWOERKTHJDERGGDH.

This is the expected behavior, I know it can sound strange, but these are the small oddities of schemaless approach ;-)

Thanks

Luigi

**Comment by healiseu** [comment]
@Luigi, I am asking from the developer's (user) point of view. I can understand perhaps this and other oddities that arise from schemaless approach but wouldn't be better if you mark this as an exception and simply return back 0 records ? Isn't that making it harder for me as a developer to parse the result of your query.

It is not only that sounds strange, it contradicts programming logic. If there are no records with the field you are searching for then your counter is zero. Otherwise how would you count the number of records that were found to have this field value in your set ?

**Comment by a-unite** [comment]
Luigi,

I believe your explanation is have meaning and absolutely right.

But what I think @healiseu was asking for, was about another query:
`select XGDFGKWOERKTHJDERGGDH from V`
Notice that quotes are missed here, so we are talking about the XGDFGKWOERKTHJDERGGDH field, not string value.

@healiseu, suppose you have `Title` property in some of deep-nested sub-classes, while there are a lot of classes and records without it.
There are big chances, that the query `select Title from V limit 10` will return first 10 empty objects.
Meaningless, but the response is quite fast ;). 
To find out only real objects, you have to make something like 
`select Title from V where Title IS NOT NULL`.

@luigidellaquila, it is interesting, that 
`select count(AnyEvenWrongField) from V` is much slower than 
`select count(AnyEvenWrongField) from V where AnyEvenWrongField IS NOT NULL`

Regards, Ata

**Comment by a-unite** [comment]
By the way, I really hope that strict mode (schema-full) classes (and whole database, maybe) will become more usable some day. But it is the theme for another discussions.

**Comment by healiseu** [comment]
@a-unite thank you for your explanation, now it seems clear that I have trouble understanding your IS NOT NULL logic. Hopefully I will overcome this obstacle.

**Comment by luigidellaquila** [comment]
Hi all,

This is a quite old issue, and as far as I can see there are no pending points here. I just double-checked it with the new SQL executor in v 3.0 and it works as espected.

I'm closing this then

Thanks

Luigi
