### ISSUE TITLE
Java Graph api to serach vertex w.r.t property value

### ISSUE THREAD

**Issue by abhishekmishra17** [orientechnologies/orientdb#5847]
HI ,
In graph api Documentation I didn't get to search Vertex with respective to property value , but I can achieve that in console.

Select from myvertex  where propertyKey='test'

How can i achieve this with Java Graph Api

**Comment by luigidellaquila** [comment]
Hi @abhishekmishra17 

you can use 
```
graph.getVertices(iKey, iValue)
```
or
```
graph.getVertices(String className, String[] iKeys, Object[] iValues)
```

I hope it helps

Thanks

Luigi

**Comment by abhishekmishra17** [comment]
Thanks luigidellaquila,

Let me check that ,but it seems that it  only do  equal check ,what about if I want to performed >=,<= etc. operation

**Comment by luigidellaquila** [comment]
Hi @abhishekmishra17 

the API does not support range operations, to do that you have to execute a query:
```
g.command(new OSQLSynchQuery("Select from myvertex where propertyKey < 'test'")).execute();
```

Thanks

Luigi

**Comment by abhishekmishra17** [comment]
Hi Luigi,
This seems to be fit for my requirement.Thank's a  lot for your support.
