### ISSUE TITLE
Define query boundaries per user/role

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5848]
It would be useful to setup the query timeout and limit per user/role to avoid end-users can overload the server.

**Comment by lvca** [comment]
@tglman WDYT to store into the user custom settings? In this way a user could have, for example, its own `command.timeout=30000`? And in this way would work not only for the timeout, but for any other setting we decide to make also per user?

**Comment by santo-it** [comment]
Customer still interested on this. Leaving this open. Would be nice for our Engineering Team if they can cost this so we can provide an estimate. Thanks
