### ISSUE TITLE
Projection queries : @rid and rid fields 

### ISSUE THREAD

**Issue by healiseu** [orientechnologies/orientdb#5849]
When you have a projection query like this

``` JAVA
select @rid from DSS WHERE stype='DSS'

{{"result":[
{"@type":"d","@rid":"#-2:0","@version":0,"rid":"#55:1","@fieldTypes":"rid=x"}, 
{"@type":"d","@rid":"#-2:1","@version":0,"rid":"#56:1","@fieldTypes":"rid=x"}, 
{"@type":"d","@rid":"#-2:2","@version":0,"rid":"#57:1","@fieldTypes":"rid=x"}
]},
200}
```

If you parse the HTTP response you get back both **@rid** and **rid** fields.
I am not sure what is the purpose of these strange "@rid":"#-2:0" pairs but it is most confusing when you want to extract rid values. This is because you are querying for **@rid** field values and you are parsing **rid** values from the response. 

I believe these @rid should be hidden from the http response, otherwise it makes it harder to parse the response. If not, then it is more consistent to query for **rid**.

**Comment by luigidellaquila** [comment]
Hi @healiseu 

The temporary RID comes from how the query projections are elaborated: the executor creates a temporary ODocument for every row in the result set, setting the "rid" field with the actual value of the projection. 

When the ODocument is serialized to JSON, its temporary RID is serialized as well.

It's easier to understand if you do another kind of query, like

```
select name from Person group by name
```

In this case it's clear that you will have temporary RIDs (you are doing a GROUP BY, so every result does not correspond to a single record in the DB) and you are obtaining the "name" field for every result.

About the chance to remove temporary RIDs from the HTTP response, probably it makes sense, but maybe I'm missing some low level details in the protocol. Assigning to @tglman for further clarification

Thanks

Luigi

**Comment by healiseu** [comment]
@luigidellaquila,
thanks for your prompt reply, bear in mind also, that when you parse queries that includes @rid in projection the http response is different than those queries with projection that does not include @rid, like the one you wrote

`select name from Person`

In the first case you get back these temporary RID, in the second you don't !

**Comment by Blacktiger** [comment]
I just want to add that I ran into this today as well. It was not clear to me why this was happening until I found this issue. I was trying to a projection query to reduce the size of the results for a large query using the java api. So I expected to do get `document.getIdentity()`, but instead I need to do `document.field("rid", ORID.class)`.

**Comment by tglman** [comment]
hi @all,

The reason for that is as soon as you do a projection the document that contains the projection should not have "a valid id" otherwise you can use it to do an update, and that would lead to save the record with just the projected fields removing all the other fields, to overcome that we move the id in the "rid" field and set an invalid identifier to de document ( usually "#-2:x").

Since 3.0 we are changing the API so some of this behaviour will change, as the fact that query won't return directly ODocument as result.

Hope this help.

Regards

**Comment by tglman** [comment]
Hi,
Since 3.0 if you do a projection are not generated anymore negative rid, so this is fixed, closing
