### ISSUE TITLE
Nullpointer exception when looping through vertices

### ISSUE THREAD

**Issue by uiterlix** [orientechnologies/orientdb#5850]
Hi,

Occasionally we get the following NullPointer exception when looping through the result of a vertex.getVertices(direction, edge label). It's pretty hard to reproduce and I can currently only fix it by restarting my application. I'm not really sure if it's related but until now I've only encountered this issue whilst working with a clustered orient setup (3 nodes).

```
RuntimeException: Error while executing graph function. Cause: java.lang.NullPointerException, message: null, source: com.tinkerpop.blueprints.impls.orient.OrientVertexIterator.createGraphElement(OrientVertexIterator.java:68)
com.tinkerpop.blueprints.impls.orient.OrientVertexIterator.createGraphElement(OrientVertexIterator.java:37)
com.orientechnologies.orient.core.iterator.OLazyWrapperIterator.hasNext(OLazyWrapperIterator.java:93)
com.orientechnologies.common.collection.OMultiCollectionIterator.getNextPartial(OMultiCollectionIterator.java:235)
com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:73)
com.tinkerpop.blueprints.util.wrappers.partition.PartitionVertexIterable$1.hasNext(PartitionVertexIterable.java:36)
```

Looking at the code it tries to retrieve the ummutableClass for the document which returns null:
```
   final OrientVertex v;
    OImmutableClass immutableClass = ODocumentInternal.getImmutableSchemaClass(value);
    if (immutableClass.isVertexType()) { // line 68: NullPointerException
```

I'm running orientdb 2.1.12.

**Comment by uiterlix** [comment]
Some more background on when this happens. It actually happens after the first interactions with a entirely new database (distributed) and is solved after restarting our application. I've never seen it when using a non-distributed orientdb instance. After this restart it never seems to happen anymore. Maybe some local driver caching in combination with a new database ?

**Comment by luigidellaquila** [comment]
Hi @uiterlix 

Good point, the schema creation and reload could be an important factor here.

Thanks

Luigi

**Comment by lvca** [comment]
@uiterlix is this happening when you create the database when the cluster is running? Or the db was previously created?

**Comment by lvca** [comment]
Closing because no answer after months. In case please reopen/comment this.
