### ISSUE TITLE
Run Lucene Spanish Analyzer

### ISSUE THREAD

**Issue by jfernandezrico** [orientechnologies/orientdb#5852]
I'd like to run a spanish fulltext search on my "question" property within my "LimitedQuestion" class.
I added an index as follows, but I don't know if I need anything else:

`create index LimitedQuestion.question on LimitedQuestion(question) FULLTEXT ENGINE LUCENE METADATA 
{"analyzer":"org.apache.lucene.analysis.es.SpanishAnalyzer"}
`

I also tried next index creation but I'm not able to run it
`
create index CuestionLimita.cuestion_es on CuestionLimita (cuestion) FULLTEXT ENGINE LUCENE METADATA 
 {
          "index_analyzer": "org.apache.lucene.analysis.es.SpanishAnalyzer",
          "query_analyzer": "org.apache.lucene.analysis.standard.StandardAnalyzer",
          "name_index_analyzer": "org.apache.lucene.analysis.standard.StandardAnalyzer",
          "name_query_analyzer": "org.apache.lucene.analysis.core.KeywordAnalyzer"
          }
		  `	  

Do I need to add any kind of configuration to use lucene or is it already installed?
I wrote something inside a pom.xml but I don't where this file is.

Kind regards,

**Comment by robfrank** [comment]
which version are you using? the second is available only on 2.2.0-beta

**Comment by jfernandezrico** [comment]
Thank you for your quick response. I'm using 2.1.11. 
So in 2.2.0, will be there more functionality for lucene?
What I want to get the words with the same root word or word stem. For example, If I look for the word "living" I want to match texts with word "life".
Is it possible? How can I do it?

**Comment by robfrank** [comment]
I think the Spanish Analyzer is a stemming one, but it is better to check the Lucene's documentation about it:
https://lucene.apache.org/core/4_0_0/analyzers-common/org/apache/lucene/analysis/es/SpanishAnalyzer.html

It uses a StemFilter, so I guess it is capable of doing stemming on spanish words:

https://lucene.apache.org/core/4_0_0/analyzers-common/index.html?org/apache/lucene/analysis/es/SpanishAnalyzer.html

do some experiments/tests to tune your code to your needs :)

**Comment by jfernandezrico** [comment]
Ok. I'll try it. Thank you very much for your attention.
