### ISSUE TITLE
Database create does not successfully create a database on all nodes in a three node cluster.

### ISSUE THREAD

**Issue by uiterlix** [orientechnologies/orientdb#5853]
When creating a new database in a cluster that consists of three nodes, the database is successfully replicated to one of the 2 other nodes but not to the second. See attached what the web console displays for the node to which replication did not succeed. This is OrientDB version 2.1.12.
![schermafbeelding 2016-03-17 om 19 43 49](https://cloud.githubusercontent.com/assets/439695/13857632/028969b6-ec7b-11e5-9e66-5ae5e24ec3a5.png)

**Comment by uiterlix** [comment]
What is the suggested way of creating databases in a distributed setup ? It seems to be pretty fragile.

**Comment by lvca** [comment]
Fixed in 2.2.0-rc1.
