### ISSUE TITLE
skip not working when filtering edges by field

### ISSUE THREAD

**Issue by sebastiandev** [orientechnologies/orientdb#5854]
We have found a pretty serious issue when querying edges filtered by properties:

```select expand(bothE('Knows)[name='john']) from V skip 2 limit 10```

This absolutely ignores the skip and always returns the same 10. 

There is a solution which requires rewriting:

```select from (select expand(bothE('Knows')) from V) where name = 'john' skip 1 limit 10```

This seems to work fine, although is quite verbose.

**Comment by luigidellaquila** [comment]
Hi @sebastiandev 

Thanks for reporting, I'll check it ASAP. Which version? 2.1.13?

Thanks

Luigi

**Comment by sebastiandev** [comment]
2.2.0-SNAPSHOT

**Comment by luigidellaquila** [comment]
Hi @sebastiandev 

I just pushed a fix on branches 2.1.x and develop (2.2), the fix will be available in next 2.1.14 and 2.2 beta2

Thanks

Luigi

**Comment by sebastiandev** [comment]
that was fast! thanks!
