### ISSUE TITLE
Possible socket leak

### ISSUE THREAD

**Issue by arsalan-khan** [orientechnologies/orientdb#5858]
We saw the following issue on our standalone orientdb server which had been up and running for close to 1 day.
OrientDB Server v2.1.13 (build 2.1.x@r9bc1a54a4a62c4de555fc5360357f446f8d2bc84; 2016-03-14 17:00:05+0000)

Reached maximum number of concurrent connections (max=1000, current=1001), reject incoming connection from /127.0.0.1:34796 [OServerNetworkListener]

Looking at the output of netstat -a we saw close to 500 connections stuck in CLOSED_WAIT on port 2424. The server was stuck in this state for a few hours, which means it wasn't a transient issue caused by too many requests at one time. In order to recover from the state we had to restart the orientdb server.

**Comment by wv-jhatcher** [comment]
I am seeing this issue too.  I think it could be in OClientConnectionManager.java, the iterator.remove() is not actually removing from the connections Collection causing the OClientConnectionManager to report more connections than their really are.

**Comment by tglman** [comment]
Hi,

With 2.1.14 we fixed some issues on connection count, so this should be fixed, @wv-jhatcher  i doubled checked the iterator.remove() and it work correclty, thank you for checking that anyway.

**Comment by tglman** [comment]
since 2.1.16 we fixed some minor temporary leak on session management, closing thins.
