### ISSUE TITLE
worse query performance

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5859]
I do have 10 records for user class, but the following query take about 6 seconds. any ideas?
FYI "explain select from #16:5" is more faster than normal query as follows:

select from #16:5

{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "fetchingFromTargetElapsed": 1,
            "documentReads": 1,
            "current": "#16:5",
            "evaluated": 1,
            "recordReads": 1,
            "elapsed": 0.157567,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "fetchingFromTargetElapsed=l,documentReads=l,current=x,evaluated=l,recordReads=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 0.525 sec. Returned 1 record(s)"
}

**Comment by lvca** [comment]
This means record #16:5 has many links/edges, so the loading takes a lot of time. Could you check this?

**Comment by martingg88** [comment]
yes. what should I do to loading record itself only, not loading links/edges

**Comment by martingg88** [comment]
@lvca I found out another issue as follows: 

The following query will scan all records for non-existent record.
Thus it will have slow performance. 
However it will only scan related records for existent record.

select from indexvaluesdesc:list.in where out = #16:500000 limit 13

**Comment by lvca** [comment]
@martingg88 the query `select from #16:5` loads the entire record content. If you don't need some properties that could be expensive in terms of loading, use `exclude/include` function.

**Comment by martingg88** [comment]
can i use the fetchplan to exclude all of the out/in edge/link?

**Comment by martingg88** [comment]
I do have another poor query like stupid. hope you can help. 

1. the following take less a seconds. 

 select rid, rid.active as active  FROM index:hotel.category WHERE key LUCENE '\"hotel\"~2' SKIP 0 LIMIT 11

2. the following is most worst that have more than 35 seconds..

SELECT FROM (
 select rid, rid.active as active  FROM index:hotel.category WHERE key LUCENE '\"hotel\"~2' SKIP 0 LIMIT 11
) WHERE active = true  LIMIT 11

**Comment by luigidellaquila** [comment]
Hi @martingg88 

the difference of performance could be due to record unmarshalling.

What does that record contain? How big is that?

Thanks

Luigi

**Comment by martingg88** [comment]
It might have more than 50k records.
each record will have one link and many photo records. 

how to solve this issue?

**Comment by martingg88** [comment]
any update?

**Comment by luigidellaquila** [comment]
Hi @martingg88 

it's hard to give you a good suggestion here.
If it's a matter of unmarshalling, probably reducing the size of your records and keeping heavy content on linked structures will help you.

Thanks

Luigi

**Comment by martingg88** [comment]
oh my goodness. Your suggestion may imply we have to redo or restructure our database design again from very beginning and thus it will take most of our development time and effort. I thought your graph database is more powerful as you guys claimed on the official statement. is it still truth for the fact? 

Anyway, hope you guys really can put more effort and focus on performance wise. 

Many Thanks.

**Comment by smolinari** [comment]
@martingg88 - when you say "many photo records", how many is many and what is a photo record exactly? Is it actual photos, like binary data?

Scott

**Comment by martingg88** [comment]
it may consist 10 to 20 photos only. The data for the photo is very simple and it only includes of url, dimension and time.

**Comment by a-unite** [comment]
@luigidellaquila I believe this issue is not about unmarshalling, but about combined search with indexed field.

Kind of "join/lookup" effect you could find in RDBS. 
When you have number of statements in the query, something like this: 
`(A='a') AND (B='b') and (C LUCENE 'c')`, 
substatement `C LUCENE 'c'` will be executed first but then filtering `(A='a') AND (B='b')` in this, let's say, N/3 records result could take much more time, than if you will scan all records without indexes (actually it feels like  O(N^2) regression).
It is quite noticeable even on our production server, when and if indexed sub-statement returns more than few thousand hits for the table with 300 000 records. In this case (with explain command), you could find, that number of documents read is few times less for LUCENE featured combined statements query, while elapsed time could be few times more than for query with this index omitted.

Sorry I don't provide code here, but hope it is clear from explanation above.
@martingg88 I believe your index query returns quite big subset (looks like there are just few values|parameters possible in that property) and you hit the same issue we had recently.

**Comment by luigidellaquila** [comment]
Hi @martingg88 

Wait, before you refactor your application, why don't you spend one hour to obfuscate your db and send me a copy? I'm pretty sure that we are missing something, looking at the data and reproducing your problems will help a lot

Thanks

Luigi

**Comment by martingg88** [comment]
sorry i can't do that. the data is quite confidential for our client.

**Comment by martingg88** [comment]
FYI. Try to populate your database with following data. 

10 user vertex and each or some of them consist more than 100k edge. 

I'm sure you will have this issue.

**Comment by smolinari** [comment]
Sounds like a supernode problem.

Scott

**Comment by martingg88** [comment]
it's worth to note the following query for performance issue. 
1. The following query take about 20 seconds to get only 10 vertex from index (list.in). 
2. I wonder it take so long time to process because it try to scan all the vertex/document belonging to vertex whose RID is #16:5;
3. Have tried to add the fetchplan  (FETCHPLAN [*]in_*:-2 out_*:-2)) to the following query but it doesn't help at all.

I do have question here i doubt why orientdb have to scan all the records for  #16:5 even I just concern about the only 10 records from index entry. 

select from indexvaluesdesc:list.in where out = #16:5

**Comment by martingg88** [comment]
any update? when you guys think the performance issue can be fully solved?
