### ISSUE TITLE
Insufficient validation in OSchemaShared.checkClassNameIfValid() 

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#5861]
Validations made in methods OSchemaShared.checkClassNameIfValid() and OSchemaShared.checkFieldNameIfValid() are insufficient. Please make corresponding corrections.
For example: it's allowed to create class 'Test-Dashes', but then it's impossible to work with such class due to lot of runtime error in different places.
And my opinion, that validations for those methods should be inclusive, but not exclusive. I mean that methods are checking absence of some characters, but should check vise versa: that all present chars are valid. It seems that those operations are not frequent, so some regexp might be the perfect solution for that.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

we are doing some important improvements on this.
The final goal is to use back-tick quoting to allow all any character in class and field names, eg.

```
SELECT `a-b` as c FROM `foo-bar-baz`
```

This already works for queries in v.2.1, but the complete support of back-ticks in DDL statements will be released only in 2.2

Thanks

Luigi
