### ISSUE TITLE
Create builder to simplify index creation

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5864]

**Comment by laa** [comment]
Not actual any more

**Comment by laa** [comment]
Index Java API is not very clear and handy for the new user about the meaning of parameters in index creation methods. Also, those parameters are very verbose so it is recommended to create builder methods for indexes. It will be a small handy addition to Java API.

**Comment by tglman** [comment]
Hi,

Since 3.0 there was a plan to remove the manual index, so we could allow the create of the index only from the schema, that has a slimmer and more clear API.

Regards

**Comment by laa** [comment]
Hi, agree. But let's keep this issue open so we will not forget it.
