### ISSUE TITLE
Delayed delete of vertexes with many edges

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5866]
Now to delete vertex we need to:
1. Load all links/edges to other vertexes.
2. Remove link to the current vertex in all vertexes.
3. Remove current vertex.

What is proposed to do: 
1.  Add support to mark vertex to be soft deleted and ignore such vertex in query/command processing and iteration among vertexes. 
2.  Update all related vertexes in background thread.
3. During completion of task background thread will delete vertex itself.

**Comment by laa** [comment]
This issue related to https://github.com/orientechnologies/orientdb/issues/5679

**Comment by tglman** [comment]
Hi,

Just as a note before implement a delayed drop I would prefer do benchmark and toning of delete operations, delay the delete could actually break the transaction isolation.

Regards

**Comment by laa** [comment]
@tglman it will not because for us does not matter whether vertexes are physically deleted or soft deleted they will be logically deleted anyway. I mean only logical view matters.

**Comment by lvca** [comment]
Isn't more expensive to update all the vertices and then delete them? Where would you put the soft delete flag? In the cluster map file?

**Comment by tglman** [comment]
Hi, 

The issue I see is not on the vertices but on the edges, that if I do a lazy delete are left in the db linking on a vertex that do not exist for a while until delete. so if a do a `select from E where ...` they will match even after a transaction that should logically have deleted them.

bye

**Comment by lvca** [comment]
Also, what happens if the process is killed during this phase? At startup, a repair database should be executed.

**Comment by laa** [comment]
@tglman sure during fetch of edges we need to check the presence of softly deleted vertex. But as already supposed by @lvca it will be a flag in cluster position map, which means taking into account that cluster position map almost always cached in memory that we will have memory access overhead. We can double check that on benchmarks of course, but IMHO you will not see a huge difference. @lvca server crash should not affect background removal because all changes will be done in txs and even metadata of background scheduler will be part of this tx. Anyway, I do not like this idea a lot so first, let's run benchmark to be sure that it is really needed.

**Comment by laa** [comment]
Not actual
