### ISSUE TITLE
Convenience method to get the rid

### ISSUE THREAD

**Issue by sivan123** [orientechnologies/orientdb#5867]
Can we have a one consistent way getting the rid without the # in front?
Something like  doc.getRID(), vertex.getRID() ?

**Comment by luigidellaquila** [comment]
Hi @sivan123 

do you have a Java ODocument? You can do

```
doc.getIdentity().getClusterId(); //for the cluster ID
doc.getIdentity().getClusterPosition(); //for the cluster position 
```

The same applies to OrientVertex and OrientEdge

Thanks

Luigi

**Comment by sivan123** [comment]
Hi @luigidellaquila , as always, thank you for the quick reply.
That one does not return the one that I am looking for

Let's say 
String query = "select @rid,name,uid from User";
List<ODocument> result = db.query(new OSQLSynchQuery< ODocument>(query));

doc.getIdentity().getClusterId()+":"+doc.getIdentity().getClusterPosition() will give me -2:0

While what I am after is the @rid which is 12:0 from  ""User#12:0{uid:sivan123,name:Sivaprasad} v1" 
The way I currently get it is doc.field("rid").toString().split("\\{")[0].split("#")[1]  which works but is ugly.

**Comment by luigidellaquila** [comment]
Hi @sivan123 

If you retrieve a full record with 

```
select from User //no projections
```

you will have a regular persistent ODocument, so my solution will work fine.

If you do a projection (@rid, name, uid in your case), you will get a document with a temporary RID (#-2:0 in your case) 

You can do the following:
```
OIdentifiable docRid = doc.field("rid"));
String result = docRid.getClusterId()+":"+docRid.getClusterPosition();
```

Thanks

Luigi

**Comment by sivan123** [comment]
Thanks @luigidellaquila Oidentifiable does not seem to have the method getClusterId and getClusterPosition

http://orientdb.com/javadoc/latest/com/orientechnologies/orient/core/db/record/OIdentifiable.html

**Comment by luigidellaquila** [comment]
Ops, sorry, try this:

```
ORID docRid = doc.field("rid").getIdentity();
String result = docRid.getClusterId()+":"+docRid.getClusterPosition();
```

**Comment by sivan123** [comment]
ORID orid = ((ORID) doc.field("rid")).getIdentity();

java.lang.ClassCastException: com.orientechnologies.orient.core.record.impl.ODocument cannot be cast to com.orientechnologies.orient.core.id.ORID

Its fine.. I will stick to doc.field("rid").toString().split("\{")[0].split("#")[1]  for now.

**Comment by luigidellaquila** [comment]
ok (I have to stop writing code from mobile without trying it ;-) )

The right one is 

```
ORID orid = ((OIdentifiable) doc.field("rid")).getIdentity();
```

Thanks

Luigi
