### ISSUE TITLE
Unable to create a link in plocal document database. Same works in a remote document db

### ISSUE THREAD

**Issue by sukesh-soman** [orientechnologies/orientdb#5869]
Hello,

I see a strange difference in behavior when we try to create a link against a plocal & remote DB.

I ran the below commands on a database created as plocal and got the error mentioned below. If I create another db of type remote, it works just fine.

Am I missing something?

>    orientdb> create database plocal:mytestdb11 root root123 plocal
>     Creating database [plocal:mytestdb11] using the storage type [plocal]...
>     Database created successfully.
> 
> ```
> Current database is: plocal:mytestdb11
> orientdb {db=mytestdb11}> create class Post;
> 
> Class created successfully. Total classes in database now: 11
> orientdb {db=mytestdb11}> create property Post.id integer;
> Property created successfully with id=1
> 
> orientdb {db=mytestdb11}> create class comments;
> Class created successfully. Total classes in database now: 12
> 
> orientdb {db=mytestdb11}> create property comments.id integer;
> Property created successfully with id=1
> 
> orientdb {db=mytestdb11}> create property comments.postid integer;
> Property created successfully with id=2
> 
> _orientdb {db=mytestdb11}> create link commentsonpost from comments.postid to post.id;
> [
> 
> Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.create link commentsonpost from comments.postid to post.id
> 
> Error: java.util.UnknownFormatConversionException: Conversion = '%'_
> ```

**Comment by luigidellaquila** [comment]
Hi @sukesh-soman 

I'm checking it, I'll give you a feedback asap

Thanks

Luigi
