### ISSUE TITLE
Documentation for REQUEST_PUSH_DISTRIB_CONFIG

### ISSUE THREAD

**Issue by whatyouhide** [orientechnologies/orientdb#5871]
Documentation for the `REQUEST_PUSH_DISTRIB_CONFIG` is missing. I expected to find it alongside the [documentation for `REQUEST_PUSH_LIVE_QUERY`](http://orientdb.com/docs/last/Network-Binary-Protocol.html#request-push-live-query). Right now, the documentation only states that the operation byte for this operation is `80`, but nothing else.

**Comment by tglman** [comment]
hi,

just added a basic documentation: https://github.com/orientechnologies/orientdb-docs/commit/349c8050dcbe4756d8eff49255fbfe59d1aa0954

let me know if you need more information.
