### ISSUE TITLE
Remote OCommand update not reloading vertex (v2.1.x)

### ISSUE THREAD

**Issue by crbaptiste** [orientechnologies/orientdb#5872]
When an SQL Update command is run using the Graph API connected to a remote database, the update saves to the database but when the vertex is retrieved using getVertex(rid), a stale version is retrieved. **NOTE: This issue is not seen when running against a local database.**

This has been observed in v2.1.x.

Here is a example code to reproduce there error:

```
OrientGraph g = factory.getTx();  // Using remote OrientGraphFactory (ie. remote:localhost/testdb)
				
OrientVertex v = g.addVertex(null);
v.setProperties("Counter", 0);
g.commit();
		
System.out.println(v.getProperties() + ", version=" + v.getRecord().getVersion());
v = g.getVertex(v.getId());
		
String cmd = String.format("UPDATE %s SET Counter = 10", v.getId());
g.command(new OCommandSQL(cmd)).execute();
		
v = g.getVertex(v.getId());
//v.reload();
System.out.println(v.getProperties() + ", version=" + v.getRecord().getVersion());
						
factory.close();	
```

If run as is output looks like:

**{Counter=0, @rid=#9:29, @class=V}, version=1
{Counter=0, @rid=#9:29, @class=V}, version=1**

If you uncomment the //v.reload output looks like:

**{Counter=0, @rid=#9:30, @class=V}, version=1
{Counter=10, @rid=#9:30, @class=V}, version=2**

**Comment by luigidellaquila** [comment]
Hi @crbaptiste 

In current release it is a known limitation and the expected behavior.

Please check the docs here

http://orientdb.com/docs/last/Transactions.html

Thanks

Luigi

**Comment by crbaptiste** [comment]
I had already read that doc, but I missed that the OCommand happens outside the transaction. 

Is this something that future versions will remedy or a limitation that we just need to get used to?

**Comment by luigidellaquila** [comment]
Hi @crbaptiste 

We will implement server-side transactions in the future, so this problem will be eventually fixed, but in the short term I think you will have to deal with this limitation.

Thanks

Luigi

**Comment by crbaptiste** [comment]
Thanks for the clarification!
