### ISSUE TITLE
Delete Edge from empty subquery with bad performance

### ISSUE THREAD

**Issue by oliverfleetwood** [orientechnologies/orientdb#5874]
According to the documentation, edges from a subquery should be done as:

``` SQL
DELETE EDGE E WHERE @rid IN (SELECT FROM #11:0)
```

Now, if record 11:0 has been deleted or if the subquery returns empty results, orientdb will scan the entire edge class and you'll get a warning that the query returned a lot of records, which of course is bad for performance. Obviously, if the subquery is empty the command should just terminate. I'm using orientdb 2.1.13.

---

For DELETE Vertex this is not the case. 

``` SQL
DELETE VERTEX FROM (Select from DELETED_RECORD)
```

works like a charm. 

---

FYI, what we're trying to do here is to lock the record during delete which is actually a part of #3595 .

``` SQL
DELETE VERTEX FROM (Select from SOME_VERTEX LOCK RECORD)
```

``` SQL
DELETE EDGE E WHERE @rid IN (SELECT FROM SOME_EDGE LOCK RECORD)
```

**Comment by luigidellaquila** [comment]
Hi @oliverfleetwood 

I think it's worth implementing the following syntax:

```
DELETE EDGE #rid
```

I marked it as an enhancement, I'll work on it asap

Thanks

Luigi

**Comment by lvca** [comment]
@luigidellaquila is this already supported by 3.0?

**Comment by luigidellaquila** [comment]
Hi @lvca 

I have to check it, but in case we can implement it

Thanks

Luigi
