### ISSUE TITLE
Unable to set timezone "Europe/Rome"

### ISSUE THREAD

**Issue by fzwaard** [orientechnologies/orientdb#5876]
I'm using OrientDB community edition 2.1.11 on a Ubuntu 14.04 server

From Studio I tried
ALTER DATABASE TIMEZONE "Europe/Rome"
and
ALTER DATABASE TIMEZONE Europe/Rome
but both these commands set the timezone to GMT.

I tried also
ALTER DATABASE TIMEZONE GMT+1
and this works giving me GMT+1 (CET), but is not the same as "Europe/Rome" (CET/CEST).

**Comment by luigidellaquila** [comment]
Hi @fzwaard 

OrientDB timezone is a simple Java TimeZone (https://docs.oracle.com/javase/6/docs/api/java/util/TimeZone.html) so it's supposed to work even with timezone names.

Which JDK are you using?

Thanks

Luigi

**Comment by fzwaard** [comment]
Hi Luigi,

java -showversion
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

dpkg-query -l | grep -i java
ii  ca-certificates-java                 20130815ubuntu1                      all          Common CA certificates (JKS keystore)
ii  default-jre-headless                 2:1.7-51                             amd64        Standard Java or Java compatible Runtime (headless)
ii  java-common                          0.51                                 all          Base of all Java packages
ii  libjavascriptcoregtk-3.0-0:amd64     2.4.10-0ubuntu0.14.04.1              amd64        JavaScript engine library from WebKitGTK+
ii  openjdk-7-jre-headless:amd64         7u95-2.6.4-0ubuntu0.14.04.1          amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  tzdata-java                          2016b-0ubuntu0.14.04                 all          time zone and daylight-saving time data for use by java runtimes

Thank you

f

**Comment by AlessandroRota** [comment]
Hi, I see in the file
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx
at the line 1438 the following code
storage.getConfiguration().setTimeZone(TimeZone.getTimeZone(stringValue.toUpperCase()));

With the method toUpperCase() the timezone is changed to GMT while without toUpperCase() the timezone is converted correctly.

**Comment by fzwaard** [comment]
Hi Alessandro and Luigi,

thanks a lot. Since this patch is quite urgent for me (summer time is changing this saturday night), do you think that this will be implemented in OrientDB soon or should I try to download, patch and compile OrientDB as per the Source Code Installation in http://orientdb.com/docs/last/Tutorial-Installation.html?

What would be the best way to move my db from the previous version to the new version of OrientDB?

**Comment by luigidellaquila** [comment]
Hi @fzwaard 

I'm doing the fix right now, I'll give you an update in short

Thanks

Luigi

**Comment by fzwaard** [comment]
Hi @luigidellaquila 

thank you for this quick fix! I'm actually enjoying very much OrientDB.

Thanks again

f

**Comment by luigidellaquila** [comment]
Hi @fzwaard 

I just pushed a fix on branch 2.1.x, you can build from sources.
The fix will be released with 2.1.14.

Now I'm porting the fix on develop branch

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed on develop as well

Closing

Thanks!

Luigi

**Comment by fzwaard** [comment]
Hi,

I used this command to get the src to compile
`git clone https://github.com/orientechnologies/orientdb`
but the file 
`orientdb/core/src/main/java/com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java`
still needed to be corrected removing `.toUpperCase()`

Should I give another command to get the last hotfix with the correction? When will this new correction end up in the bin on web site?

**Comment by luigidellaquila** [comment]
Hi @fzwaard 

you have to do a

```
git checkout 2.1.x
```

to get the hotfix branch


Thanks

Luigi
