### ISSUE TITLE
[ OrientDB version 2.1.13 ] Regression on build. Maven build failed.

### ISSUE THREAD

**Issue by Ostico** [orientechnologies/orientdb#5879]
I tried to compile version **2.1.12** with maven and _it works_.

I tried again with maven on OrientDB v2.1.13 and it **do not compile**.

```
Build by download from github repository
wget -q -O /var/www/PhpOrient/ci/environment/orientdb-community-2.1.13.tar.gz https://github.com/orientechnologies/orientdb/archive/2.1.13.tar.gz
Extract package
Extract archive: orientdb-community-2.1.13.tar.gz
tar xf /var/www/PhpOrient/ci/environment/orientdb-community-2.1.13.tar.gz -C /var/www/PhpOrient/ci/environment
rm -rf /var/www/PhpOrient/ci/environment/orientdb-community-2.1.13.tar.gz
cd /var/www/PhpOrient/ci/environment/orientdb-2.1.13
Start Build: mvn clean install -DskipTests
[INFO]
Scanning for projects...

........
........


[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /var/www/PhpOrient/ci/environment/orientdb-2.1.13/core/src/main/java/com/orientechnologies/orient/core/index/OIndexChangesWrapper.java:[18,7] error: OIndexChangesWrapper is not abstract and does not override abstract method remove() in Iterator
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OrientDB .......................................... SUCCESS [50.851s]
[INFO] OrientDB Test Commons ............................. SUCCESS [55.369s]
[INFO] OrientDB Core ..................................... FAILURE [1:24.613s]
[INFO] OrientDB Enterprise ............................... SKIPPED
[INFO] OrientDB Client ................................... SKIPPED
[INFO] OrientDB Object ................................... SKIPPED
[INFO] OrientDB Server ................................... SKIPPED
[INFO] OrientDB Tools .................................... SKIPPED
[INFO] OrientDB GraphDB .................................. SKIPPED
[INFO] OrientDB Tests .................................... SKIPPED
[INFO] OrientDB Distributed Server ....................... SKIPPED
[INFO] OrientDB Lucene full text and spatial index ....... SKIPPED
[INFO] OrientDB JDBC Driver .............................. SKIPPED
[INFO] OrientDB ETL ...................................... SKIPPED
[INFO] OrientDB Community Distribution ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:12.889s
[INFO] Finished at: Wed Mar 23 22:57:03 UTC 2016
[INFO]
Final Memory: 31M/192M
[INFO]
------------------------------------------------------------------------
[ERROR]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project orientdb-core: Compilation failure
```

**Comment by smolinari** [comment]
It is just a guess, but what version of Java do you have?

Scott

**Comment by laa** [comment]
Hi,
Well it was my issue, it is already fixed in 2.1.14.

On Thu, Mar 24, 2016 at 6:47 AM Scott <notifications@github.com> wrote:

> It is just a guess, but what version of Java do you have?
>
> Scott
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5879#issuecomment-200662391>
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by smolinari** [comment]
What was the fix?

Scott

**Comment by laa** [comment]
Added implementation of method Iterator#remove() which in Java 8 has
default implementation :D .

On Thu, Mar 24, 2016 at 8:07 AM Scott <notifications@github.com> wrote:

> What was the fix?
>
> Scott
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5879#issuecomment-200691303>
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by Ostico** [comment]
Thank you @laa ,
the fix will be pushed to the 2.1.13 and forced the release tag on github?
Otherwise i will skip tests on that version.

**Comment by fzwaard** [comment]
I have the same problem with

[INFO] Building OrientDB Core 2.1.14-SNAPSHOT

got it today with
git clone https://github.com/orientechnologies/orientdb
cd orientdb
git checkout 2.1.x

Ubuntu 14.04 LTS
pache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_95, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-83-generic", arch: "amd64", family: "unix"

java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

javac -version
javac 1.7.0_95

mvn clean install -DskipTests
[INFO] Building OrientDB 2.1.14-SNAPSHOT
...
[ERROR] COMPILATION ERROR : 
[ERROR] /home/runmodel/git_orient/orientdb/core/src/main/java/com/orientechnologies/orient/core/index/OIndexChangesWrapper.java:[18,7] error: OIndexChangesWrapper is not abstract and does not override abstract method remove() in Iterator


I don't get this error on a different server but with the same procedure

Ubuntu 14.04 LTS
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: /usr/local/java/jdk1.8.0_77/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-24-generic", arch: "amd64", family: "unix"

different java though

java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

javac -version
javac 1.8.0_77

here it compile ok without tests (I still have some issues with tests).

**Comment by smolinari** [comment]
The second server has Java 8 and the reason why it works. 

http://stackoverflow.com/questions/5425130/java-iterator-implementation-compile-error-does-not-override-abstract-method-re

Scott

**Comment by fzwaard** [comment]
Thanks @smolinari !

So OrientDB can't be compiled with Java 7 anymore?

Should the section of http://orientdb.com/docs/last/Tutorial-Installation.html regarding Source Code Installation corrected adding the need for Java 8?
Moreover, there is a small mistake in the docs:
`git checkout develop` should go after `cd orientdb`.

f

**Comment by smolinari** [comment]
I believe it should work with Java 7, so what you are finding is a bug.

Scott

**Comment by santo-it** [comment]
Hi,

I think we can close this now? 2.1 is EOL. Please reopen if needed

Thanks,
