### ISSUE TITLE
Fetch plans are not honored for queries using OSQLSynchQuery [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#588]
This is [Issue 588](http://code.google.com/p/orient/issues/detail?id=588) moved from a Google Code project.
Added by 2011-10-26T15:04:28.000Z by [steven.t...@gmail.com](http://code.google.com/u/113135843088665186243/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

    When using OSQLSynchQuery over a remote connection (NetworkBinaryInterface), items that should be returned based on the specified fetch plan are not.  OSQLAsynchQuery works fine.
    
    It seems like the fetch plan is simply being ignored in this case.

**Comment by tglman** [comment]
fetch plan on sync query works since long time ago,

**Comment by lvca** [comment]
So close it?
