### ISSUE TITLE
instanceof operator has confusing behavior

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#5883]
Per the [docs](http://orientdb.com/docs/last/SQL-Where.html), `instanceof` expects a quoted class name:
```
@this instanceof 'Customer'
```

However, the following does not cause a parse failure and simply returns no results:
```
@this instanceof Customer
```

Even worse, no errors are raised even if the class `Customer` doesn't even exist in the schema. This appears to be a bug that makes it really easy to shoot oneself in the foot.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

As usual, in a schemaless database any syntactically valid expression is valid at parsing level.
The fact that it evaluates to null (Customer attribute is not present in current document) just makes the condition false.

I could force the `instanceof` to accept only strings, but it would mean removing support for complex expressions, eg.

```
@this instanceof ?
@this instanceof :foo
@this instanceof anyFunctionCallThatReturnsAClassName()
@this instanceof "foo" + "bar" // not fully supported now, but it will be in next releases
```

Sorry, I have to close this and mark it as invalid.

Thanks

Luigi

**Comment by obi1kenobi** [comment]
I didn't realize that complex expressions were allowed with that operator -- perhaps that could be mentioned in the docs?

Also, is `@this instanceof null` ever going to evaluate to true? If not, then two things could be possible:
- don't perform a table scan, which currently seems to be happening
- consider throwing an exception, because that's a semantically questionable query -- null is not a type.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

Good point, It's definitely a good optimization. 
We are rewriting part of the query executors, I'll take all this into consideration

Thanks!

Luigi
