### ISSUE TITLE
[2.2 beta] out() and in() not working with Edge class hierarchy

### ISSUE THREAD

**Issue by scrabb** [orientechnologies/orientdb#5884]
If you have a hierarchy of edge types and 2 vertices joined via the edge subclass then a select statement with out(super class) does not work.  This does however work in the 2.1 stream.

ie
edge type of Sibling
edge type of Brother with superclass as Sibling
2 vertices joined using Brother edge type
select out('Brother') from Person will return results
select out('Sibling') from Person returns nothing

**Comment by luigidellaquila** [comment]
Hi @scrabb 

This seems to be quite critical, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @scrabb 

I just pushed a fix and a test case on develop branch

Closing

Thanks!

Luigi

**Comment by scrabb** [comment]
Thanks for the fast response/fix.
