### ISSUE TITLE
Qlikview jdbc connection to Orientdb

### ISSUE THREAD

**Issue by Budapest123** [orientechnologies/orientdb#5888]
I try to test this connection but does not work properly, can anyone help?

1.Qli

kview 11 desktop edition is installed and working properly on WIN7 (32 bit)
2. Isntalled Orientdb-community-2.1.13 - (Server and studio is running well) - Java is installed jre1.8.0:73
(local machine install)
3. Set PATH, JAVA_HOME, CLASSPATH variables (CLASSPATH=C:\Program Files\Java\jre1.8.0_73\lib)
4. Installed and configured orient jdbc driver from TIQ Solutions - trial (orientdb-jdbc-2.1.13.jar) - driver classname: com.orientechnologies.orient.jdbc
5. Strart orientdb Server - ok /test orient studio - ok (port: 2480)
6. Start qlikview and press new script - jdbcconnect dll(32) is visible - see qlikview1.jpg then when I press connect I set the following data :jdbc:orient:localhost:2480/GratefulDeadConcerts, user root, pwd: my pwd -see qlikview2.jpg
7. I see the following in the script:  CUSTOM CONNECT O "Provider=JDBCConnector.dll;jdbc:orient:localhost:2480/GratefulDeadConcerts;XUserId=YKMPBZdNPDdIO;XPassword=bCDPSJVMSLZGXYEI;";
8. Press Select - Message from Qlikview - see qlikview3.jpg then I see the Create Select window but without tables/object of the GratefullDeadConcerts database - see qlikview4.jpg 

What is wrong? (I cant see the uploaded files....?)

Thanks.

**Comment by robfrank** [comment]
I try to guess your problem , since I'm not an expert of the tools you're mentioning and images (with screenshot, I think) are not available. My first suggestion is to use admin/admin as credential.
It seems that you're using credential for the SERVER administrator (root/PSW) rather than credentials for the database (gratefuldead) owner.

**Comment by Budapest123** [comment]
Thanks for your suggestion - probably you are right - I tried but does not help....(I cant upload my image files )png or jpg.. - dont know why?)

**Comment by chauhans85** [comment]
has this  been resolved  or you able to connect?
