### ISSUE TITLE
ORecordId cannot be passed using argument placefolder.

### ISSUE THREAD

**Issue by smil2k** [orientechnologies/orientdb#5890]
Hi,

I try to pass RIDs to the queries using the ? quoting, but orientdb parser cannot work with them.

This does not work:
docTemplate.command("create edge from ? to (select out() from ?)", from, to);

This works:
docTemplate.command("create edge from " + from + " to (select out() from " + to + ")");

Apparently, ORecordId gets the part with quotes, and fails to parse it.

ps.
using orientdb 2.1.8

**Comment by luigidellaquila** [comment]
Hi @smil2k 

could you please post a full example? What kind of objects are 'from' and 'to'?

Thanks

Luigi

**Comment by smil2k** [comment]
Hi,

from and to is a string. It is working fine with "select from ?". It seems create edge has a problem with it.

Cheers,

Tamas

**Comment by luigidellaquila** [comment]
Hi @smil2k 

If you pass strings, the query will be translated in something like:

```
create edge from "#12:0" to (select out() from "#12:1")
```

that is not correct.
If you are using Java, try to create a `new ORecordId(clusterId, clusterPosition);` and pass it to the query as a parameter, eg.
```
ORecordId from = new ORecordId(12, 0);
ORecordId to = new ORecordId(12, 1);
docTemplate.command("create edge from ? to (select out() from ?)", from, to);
```

Thanks

Luigi

**Comment by smil2k** [comment]
Hi,

Then why ("select from ?", "#13:1") is correct?
I think something is not consistent here.

Cheers,

Tamas

**Comment by luigidellaquila** [comment]
That's a good question, I'll check it

thanks

Luigi

**Comment by luigidellaquila** [comment]
@smil2k 

Are you sure that `("select from ?", "#13:1")` works fine? What API are you using?
AFAIK it never worked.

I'm doing a local test to double check it

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @smil2k 

I did a test in Java with a `select from ?` passing a string and it fails as well, so the behavior seems to be consistent.

Do you have a way to reproduce the problem?

Thanks

Luigi

**Comment by smil2k** [comment]
Hi,

I'm pretty sure, that this is not consistent:
String to, from;
delete edge from " + period.getRid() + " to "
                                + "(select flatten(out()[id = ?].@rid) from ?), 10L, from);

or

int period;
String from;
List<ODocument> doc = docTemplate.query(
                    new OSQLSynchQuery<ODocument>("select expand(out()[period=?]) from ?"), period, from);

**Comment by luigidellaquila** [comment]
Ok, I'm trying it now. Which version are you using? Do you have strictSql = false?

Thanks

Luigi

**Comment by smil2k** [comment]
Hi,

I just compiled the spring-data-orientdb, changed the version to 2.1.12.
I did not change any properties.

Cheers,

Tamas

**Comment by luigidellaquila** [comment]
Ah, got it, you are using Spring Data module, probably the difference is there.
I was doing my tests with plain ODatabaseDocumentTx API.

Do you have a working test to reproduce it?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, never mind, I managed to reproduce it in 2.1.x

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, now I have the full picture. It works on 2.1.x but not in 2.2.
Anyway it's not supposed to work, a string is not a valid target. 
I'm not changing this behavior in 2.1 only to avoid breaking backward compatibility between hotfix releases. In 2.2 it will not be allowed.

Thanks

Luigi

**Comment by smil2k** [comment]
Additionally it would be nicer to return with something like "string passed instead of recordid", because currently it is a number parse exception "#15" deep inside the engine.
