### ISSUE TITLE
how to connect orientdb cluster via mybatis

### ISSUE THREAD

**Issue by gaoxuesong** [orientechnologies/orientdb#5894]
how to connect orientdb cluster via mybatis. What is the orientdb cluster ip and port?

**Comment by gaoxuesong** [comment]
Config the **mybatis** enviroments property in **config.xml**, the code like:

    <environments default="development">
        <environment id="development">
        <transactionManager type="JDBC"/>
            <dataSource type="POOLED">
            <property name="driver" value="com.orientechnologies.orient.jdbc.OrientJdbcDriver"/>
            <property name="url" value="jdbc:orient:remote:10.18.203.114:2425/douban_all;jdbc:orient:remote:10.18.203.114:2426/douban_all" />
            <property name="username" value="admin"/>
            <property name="password" value="admin"/>
            </dataSource>
        </environment>
    </environments>

**Comment by lvca** [comment]
You just need to connect to one of the servers in the cluster (port 2424, the default one).

**Comment by Godbother** [comment]
i connected successfully but it return nullpointEx to me. is it can use the formal sql?
