### ISSUE TITLE
Teleporter page - can't see drivers item in combo

### ISSUE THREAD

**Issue by papageno66** [orientechnologies/orientdb#5900]
Hello, I'm using v2.2.0-beta of OrientDB Server and OrientDB Studio. 
I want to create a graph connecting to Oracle XE 11.2 using Teleporter.
Even if I copied ojdbc7.jar in myorientdbpath\lib I still can't see any item in 'driver' combo in teleporter page in 'Server management' window. as shown in following cropped image:
Am I missing some jar or some what?
Thanks
![teleporter](https://cloud.githubusercontent.com/assets/17472107/14113663/3d6b99f2-f5d4-11e5-9eaf-f2f1a1f51ffe.jpg)

**Comment by maggiolo00** [comment]
hi @papageno66 

can your OrientDB instance make http call or is it blocked? The drivers combo is populated by a Get request to http://orientdb.com/jdbc-drivers.json

**Comment by papageno66** [comment]
Hello @maggiolo00    ,
         my OrientDB instance is not blocked by a proxy. The berkeley.edu link written in json file seems to raise a 503 http error as you can see on following cropped image. Is it possible I can't see any item in combo even if  my local OrientDB  "lib" directory is filled with jar driver?

![teleporter](https://cloud.githubusercontent.com/assets/17472107/14170354/92936838-f72d-11e5-9359-154bc86e4cbe.jpg)

**Comment by lvca** [comment]
It looks like Berkley removed the jar. Could you find the same elsewhere and install it manually?

**Comment by papageno66** [comment]
Yes, googling ojdbc7-12.1.0.1.jar and choosing the first answer

http://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html

I've downloaded and copied  ojdbc7.jar, simplefan.jar, ucp.jar in local orientdb 'lib' directory.

Wondering if it's missing any dependecies...

When i open teleporter page in Studio, the console shows me the messages above:

2016-03-31 14:59:42:898 WARNI ->0:0:0:0:0:0:0:1: Command not found: GET.sso [ONe
tworkProtocolHttpDb]
2016-03-31 14:59:46:179 INFO  Profiler is recording metrics with configuration:
60,24 [OEnterpriseProfiler]
2016-03-31 15:00:09:652 SEVER Internal server error:
java.lang.NullPointerException [ONetworkProtocolHttpDb]

Still thinking it search drivers on web even they are on 'lib' folder, maybe in method ODriverConfigurator.readJsonFromUrl

**Comment by G4br13l3** [comment]
As it's solved I'm closing this issue.
Thanks,
Gabriele
