### ISSUE TITLE
Studio: Display of records with double value of "infinity" fails

### ISSUE THREAD

**Issue by gerdhub** [orientechnologies/orientdb#5902]
It is (of course) possible to store double values of "inifinity" as a property of a document. 
However, these documents cannot be displayed in studio and the relevant queries fail with 

> The command has not been executed

This relates to Version: 2.1.13

**Comment by gerdhub** [comment]
Is there any news on this issue?

**Comment by maggiolo00** [comment]
hi @gerdhub 

which query did you execute?

**Comment by gerdhub** [comment]
A simple select query, for example

select from token

where token is a class containing a double property. If in the resultset, there is a document with a value of "infinity" in the double property, the issue happens.
