### ISSUE TITLE
Insert a embedded inside another embedded

### ISSUE THREAD

**Issue by raphha** [orientechnologies/orientdb#5903]
I'm new on orientdb and I would like to know if is possible to insert a document with three levels of depth, using a embedded inside another embedded, like the example under. I've being searching for some examples like my data with no success.
Example:

	"p_partkey": 1,
	"p_name": "lace spring",
	"lineorder": [{
		"lo_revenue": 4282453,
		"lo_orderdate": 19920603,
		"customer": [{
			"c_nation": "JORDAN",
			"c_address": "uZaxFV8o9IGgayUEWtPU1Xmw",
			"c_mktsegment": "BUILDING|"
		}],
		"orderdate": [{
			"d_date": "June 3, 1992",
			"d_datekey": 19920603,
			"d_year": 1992
		}]},{
		"lo_revenue": 46868767,
		"lo_orderdate": 9987983,
		"customer": [{
			"c_nation": "BRAZIL",
			"c_address": "kjbnkjakjh",
			"c_mktsegment": "BUILDING|"
		}],
		"orderdate": [{
			"d_date": "June 6, 1994",
			"d_datekey": 19940606,
			"d_year": 1994
		}]}]

All examples I've found uses only one level of embedded documents.

**Comment by luigidellaquila** [comment]
Hi @raphha 

Yes, sure, just try the following in OrientDB Studio:

```
INSERT INTO V SET name ='foo', bar = {
	"p_partkey": 1,
	"p_name": "lace spring",
	"lineorder": [{
		"lo_revenue": 4282453,
		"lo_orderdate": 19920603,
		"customer": [{
			"c_nation": "JORDAN",
			"c_address": "uZaxFV8o9IGgayUEWtPU1Xmw",
			"c_mktsegment": "BUILDING|"
		}],
		"orderdate": [{
			"d_date": "June 3, 1992",
			"d_datekey": 19920603,
			"d_year": 1992
		}]
	}, {
		"lo_revenue": 46868767,
		"lo_orderdate": 9987983,
		"customer": [{
			"c_nation": "BRAZIL",
			"c_address": "kjbnkjakjh",
			"c_mktsegment": "BUILDING|"
		}],
		"orderdate": [{
			"d_date": "June 6, 1994",
			"d_datekey": 19940606,
			"d_year": 1994
		}]
	}]
}
```

There are not many examples about this (IMHO just because of excess of simplification) but it's a quite common use case.

Thanks

Luigi
