### ISSUE TITLE
duplicated property (in parent class) stops ODB of deleting a database

### ISSUE THREAD

**Issue by pabloa** [orientechnologies/orientdb#5904]
I tried to delete a database with a property I added in V called id_c. I tried to delete it and I got this error message:

{"errors":[{"code":500,"reason":500,"content":"com.orientechnologies.common.exception.OException: Error on creation of shared resource\r\n--> com.orientechnologies.orient.core.exception.OSchemaException: Cannot add base class 'ecgc', because of parameter conflict: id_c (type=STRING) vs id_c (type=STRING)"}]}

I cannot delete the database, at least with studio.

It happened with OriendDb version 2.1 on Ubuntu linux server with java 8.

**Comment by tglman** [comment]
hi,

This is already fixed in 2.1.x branch and develop, here is the commit: https://github.com/orientechnologies/orientdb/commit/e3299338025c9cf33f885672fe439c294fb287e6

will be out n 2.1.15 and 2.2 closing
