### ISSUE TITLE
NPE in ORecordSerializerBinaryV0

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#5905]
There is the following code in ORecordSerializerBinaryV0

``` @SuppressWarnings("unchecked")
  private int writeEmbeddedMap(BytesContainer bytes, Map<Object, Object> map) {
    final int[] pos = new int[map.size()];
    int i = 0;
    Entry<Object, Object> values[] = new Entry[map.size()];
    final int fullPos = OVarIntSerializer.write(bytes, map.size());
    for (Entry<Object, Object> entry : map.entrySet()) {
      // TODO:check skip of complex types
      // FIXME: changed to support only string key on map
      OType type = OType.STRING;
      writeOType(bytes, bytes.alloc(1), type);
      writeString(bytes, entry.getKey().toString());
      pos[i] = bytes.alloc(OIntegerSerializer.INT_SIZE + 1);
      values[i] = entry;
      i++;
    }
```

The problem is that some Maps can contains nulls as keys. So there will be NPE here: `entry.getKey().toString()`.

**Comment by tglman** [comment]
Hi @PhantomYdn 

I see your point, that's easy to fix, we have just to define how should be encoded the null value, maybe a good idea is put the size of the key = -1 to say that is null. i've to double check anyway if is coherent whit the rest of specification.

**Comment by tglman** [comment]
Hi @PhantomYdn 

I see your point, that's easy to fix, we have just to define how should be encoded the null value, maybe a good idea is put the size of the key = -1 to say that is null. i've to double check anyway if is coherent whit the rest of specification.

**Comment by PhantomYdn** [comment]
Yea - you can define as you wish: but during deserialization, I guess it should be transformed back to null. Right?
If it's not possible: I think that OrientDB should transform null into "" (empty string) key.

**Comment by tglman** [comment]
hi @PhantomYdn, 

Doing some internal discussion we decided to not support null keys on maps, also because this will bring issue for some API like HTTP/JSON or third party drivers.

so i just added the proper exception in case of add of a key null in map

closing

**Comment by PhantomYdn** [comment]
In this case, imho, value should be checked at the same place where other validations. And some frameworks might serialize even before save() and its strange just fall down with exception on this stage.

**Comment by tglman** [comment]
hi @PhantomYdn,

It make sense add some check also at validation stage, i'll reopen the issue at lower priority to keep track

**Comment by tglman** [comment]
hi @PhantomYdn,

double checking the fix i did the exception go up in any case of set of a null value on a tracked map, this for me is more than enough.

Closing
