### ISSUE TITLE
Infinite retries on ClassNotFoundException when deserializing server-side exception

### ISSUE THREAD

**Issue by Eijsinkdavid** [orientechnologies/orientdb#5918]
When the client makes a request to the server and the server sends a serialized exception that the client cannot deserialize, the client treats it as an io exception and will keep retrying.

**Details**
The method OChannelBinaryAsynchClient.createException attempts to reproduce an exception based on a classname. If this throws a ClassNotFoundException, the createException returns an OIOException.
This exception is interpreted by OStorageRemote.handleException as a network problem. it will retry the connection, which is probably succesful. Most of the methods in OStorageRemote will then simply retry the request in a do-while loop, which means it never stops.

Does it make sense to treat a ClassNotFoundException as an io problem?

**Comment by tglman** [comment]
Hi @Eijsinkdavid,

Thanks for the detailed report, i fixed and thrown a better exception that made the client scale the error up to the application.
