### ISSUE TITLE
LINK type constraints on lightweight edges

### ISSUE THREAD

**Issue by codelimner** [orientechnologies/orientdb#5921]
Is it possible to create LINK type constraints on a lightweight edge? I am running OrientDB 2.1.11, and I set my edges to be lightweight using the command 
`ALTER DATABASE CUSTOM useLightWeightEdges = TRUE`
The following is an example of what I would like to be able to do.

I first ran the following SQL commands 
`CREATE CLASS C1 EXTENDS V`
`CREATE CLASS C2 EXTENDS V`

`CREATE CLASS E1 EXTENDS E`
`CREATE PROPERTY E1.out LINK C1`
`CREATE PROPERTY E1.in LINK C1`

`CREATE VERTEX C1 set id="c11"`
`CREATE VERTEX C1 set id="c12`
`CREATE VERTEX C2 set id="c2`

After all that, now running 
`CREATE EDGE E1 FROM (SELECT FROM C1 WHERE "id" = "c11") TO (SELECT FROM C2 WHERE "id" = "c2")`
does not throw any exceptions, and creates the edge as requested. Is there any reason why a lightweight edge cannot enforce LINK type constraints? If I make E1 a "normal" edge then the constraint is enforced and I get thrown an `OValidationException` as I expected. Is creating a normal edge the only solution to my problem? Can lightweight edges also be configured to enforce such constraints? 

I should mention, when I type 
`INFO CLASS E1`
the LINK type constraint does show up on the output, which suggests to me that the constraint information for the lightweight edge is maintained by the database, even if not ultimately enforced. Thanks for any comments.

**Comment by smolinari** [comment]
Interesting. I'd say, you've found a bug, but I am also uncertain about how constraints are supposed to work. 

Referencing this issue to my suggestion too, since there are similar concerns. 

https://github.com/orientechnologies/orientdb/issues/5260

Scott

**Comment by nagarajasr** [comment]
lightweight edges cannot have properties set on them, because no record is ever created for the edge itself. lightweight edges work by linking the vertices directly. so in this case, you should add the constraint on the property of C1 and C2 classes.

**Comment by smolinari** [comment]
That is also what I thought at first, but you can create a lightweight edge and create the constraints on the edge (which seem like properties). If you follow what @codelimner explains, you will see no document is created under the E1 class.

Scott

**Comment by nagarajasr** [comment]
@smolinari i just tried these commands on orientdb-2.2.0beta and the database does not seem to respect the "useLightweightEdges=TRUE" setting. an edge record is in fact getting created:

```sql
orientdb {db=testdb}> select from V

----+-----+------+----+-------+-------
#   |@RID |@CLASS|id  |out_E1 |in_E1
----+-----+------+----+-------+-------
0   |#17:0|C1    |c11 |[#25:0]|null
1   |#18:0|C1    |c12 |null   |null
2   |#21:0|C2    |c2  |null   |[#25:0]
----+-----+------+----+-------+-------

3 item(s) found. Query executed in 0.006 sec(s).
orientdb {db=testdb}> select from E

----+-----+------+-----+-----
#   |@RID |@CLASS|out  |in
----+-----+------+-----+-----
0   |#25:0|E1    |#17:0|#21:0
----+-----+------+-----+-----

1 item(s) found. Query executed in 0.006 sec(s).
orientdb {db=testdb}>

```

i tried in OrientDB 2.1.7 and it works differently - no record is created for the edge.

in both versions, "info" command does not display the "useLightweightEdges" setting.

**Comment by smolinari** [comment]
That is interesting. And in 2.2 it seems you not only have an edge document, but the edge is created, despite the constraint, which is different behavior than with 2.1.X, which throws an error on standard edges. So, being it is called a constraint, I'd say that is another bug. Basically, setting a LINK constraint is useless. 

Scott

**Comment by nagarajasr** [comment]
actually my comment on "info" command in the previous comment was not completely correct. if i create a database through the console, and then set the "useLightweightEdges=TRUE", the info command does not display the setting. however if i disconnect from the console and relogin, the info command displays the setting correctly.

**Comment by codelimner** [comment]
Thanks @smolinari and @nagarajasr for the comments and additional information. 

I did some investigation on this looking into the source code for version 2.1.14 during the past couple of days. Essentially, all schema constraints (including LINK type) are completely ignored when the lightweightedges option for the db is set to "true". This is what @nagarajasr was implying I suppose, and you can observe this in the code by looking at the implementation of getType() method of the OrientEdge class. 

But you can't also set these constraints on the two endpoint vertex classes. I feel this is reasonable as it is an edge type constraint, and it would not make sense to set constraints on the vertex end points without the edge being involved in any way. 

So if my understanding is correct, this is more of a "not implemented now" thing (if it will ever be) rather than a bug. Part of the problem with implementing this seems to be that the constraint validation checks are done at a document level, and of course lightweight edges have no document by themselves. Validating a lightweight edge is really validating a property of another document (link property of either the out or in vertex), and may need a special case handling.

**Comment by smolinari** [comment]
@codelimner - cool that you are digging into the ODB code. 

From what I understand, the lightweight edge is always only found within the vertex data (out, in), plus some meta data about the edge class itself. There is no class with document storage created with lightweight edges. So, the constraints do have to be added to something, which is to me, must be meta data within the edge class. Was there anything in the code about this?

According to the docs, the constraints are very much possible, and to me, they should work the same, no matter what kind of edge is being used. Maybe @luigidellaquila can shed some more light on this.

Scott

**Comment by luigidellaquila** [comment]
Hi guys,

This seems to be a missing control in the validation. As you pointed out, the root cause for this is that schema checks are performed at document level, and in this case the edge is not a document.

I'll check if we can enforce basic schema validations on edge type at least, but I'm afraid more complex constraint checks (eg. unique edge between two vertices) will be harder to manage.

In the meantime I'm flagging this as an enhancement, I'll give you a feedback as soon as I can

Thanks

Luigi

**Comment by smolinari** [comment]
Thanks Luigi, 

I believe we are only looking for the constraint between two vertex classes being upheld properly. In other words (using this section of the docs for an example).

http://orientdb.com/docs/2.1/Tutorial-Using-schema-with-graphs.html#using-in-and-out-constraints-on-edges

The control should not only be the direction of the edge (a car can't own a person), but the fact that an "owns" edge can only be used between the "person" and "car" classes. If I would want to have multiple "owns" edges to other classes, then I wouldn't add the "owns.in" property. 

I hope that makes sense.

Scott
