### ISSUE TITLE
JDBC contract not supported

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#5922]
The issue linked with https://github.com/orientechnologies/orientdb/issues/5820 .
Orient JDBC driver MUST throw SQLException not OCommandExecutionException.
See javadoc for java.sql.Statement

**Comment by robfrank** [comment]
Could you please point me where JDBC throw OcommandEE? 
Or at least some lines of code where it happens. Thank you very much.

**Comment by schernolyas** [comment]
Hi @robfrank !
I try version 2.2.-beta2.

Incorrect example 
public static Number getSequence(Connection connection, String seqName) {
		Number nextValue = null;
		String query = String.format( "select sequence('%s').next()", seqName );
		try {
			Statement stmt = connection.createStatement();
			ResultSet rs = stmt.executeQuery( query );
			if ( rs.next() ) {
				nextValue = rs.getLong( "sequence" );
			}
		}
		catch (SQLException sqle) {
			throw log.cannotExecuteQuery( query, sqle );
		} catch (OCommandExecutionException oe) {
                        throw log.sequenceNotExists( seqName, oe );
                }
		return nextValue;
	}

Unfortunately, answer to your question is: see classes Statemet,ResultSet, PrepareStatement

P.S.  It is not critical for me. But ....it is JDBC contract

**Comment by robfrank** [comment]
Thx.  Will check and fix ASAP

**Comment by robfrank** [comment]
This commit
https://github.com/orientechnologies/orientdb/commit/934043fd762eb74dcecdbac5c11480573daecf50
should resolve the problem. 
I'll backport to 2.1.x branch. It will be available on next 2.2.0 (beta or rc version) and next 2.1.16 release.
