### ISSUE TITLE
Big disk fragmentation after data load

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5925]
After initial load of database, fragmentation of my disk was increased from 0 to 30% . We need to find reason of such big fragmentation and fix it. Otherwise it will cause noticeable degradation of full scan SQL queries.

**Comment by smolinari** [comment]
See this GG discussion too. https://groups.google.com/forum/#!topic/orient-database/yxzHDOVPtpo

Scott

**Comment by laa** [comment]
Not actual
