### ISSUE TITLE
Is this documentation correct?

### ISSUE THREAD

**Issue by bodiam** [orientechnologies/orientdb#5928]
From here:

http://orientdb.com/docs/2.1/Command-Cache.html

> By default, the command cache is disabled. To enable it, set command.timeout=true.

command.timeout=true? To enable command caching?

And then in the documentation below:

> command.cache.enabled	Enable command cache	Boolean	false

I find this documentation, or the parameter name, to be highly confusing. But is it correct?

**Comment by luigidellaquila** [comment]
Hi @bodiam 

Good point, it's definitely wrong! The right setting is `command.cache.enabled=true`

I'm fixing the docs page right now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Docs sources fixed, the fix will be in the official docs in short

Thanks

Luigi
