### ISSUE TITLE
Error while connecting to database from the web interface

### ISSUE THREAD

**Issue by sukhitha4** [orientechnologies/orientdb#5929]
Version: 2.1.15
The web ui has totally messed up. But REST API does work. 

![capture](https://cloud.githubusercontent.com/assets/7057974/14255592/5ea8ce9a-fab2-11e5-8ec8-66e87ab03de1.PNG)

Following warning was the only log (With FINER level)

2016-04-04 21:59:34:860 WARNI ->0:0:0:0:0:0:0:1: Command not found: GET.sqlProfiler/GratefulDeadConcerts [ONetworkProtocolHttpDb]

**Comment by maggiolo00** [comment]
hi @suki300me 

are you with Chrome?

can you try Incognito session?

Which version of OrientDB where you using before?

**Comment by suki300me** [comment]
Yep. I'm on chrome. Tried with incognito and cleared cache. Still no luck

**Comment by suki300me** [comment]
Ok I had a root around. It does work on Firefox. So this could be browser compatibility issue. I'm on the latest chrome: Version 49.0.2623.110 m

**Comment by maggiolo00** [comment]
You could you try to clear the local storage

for localhost:2480 if you are in localhost

chrome://settings/cookies#cont

**Comment by suki300me** [comment]
Yep I have already cleared all the cookies. But still didn't work
