### ISSUE TITLE
Use an atomic rename for the backup file, instead of just opening and writing

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#5931]
I'm running OrientDB 2.1.9 configured with the backup plugin. I noticed that when backing up, the database simply opens its intended backup file and keeps writing data to it until finished. This is bad because it would leave the backup file corrupted in the event of a database crash mid-backup, but I wouldn't be able to notice since the file exists in its expected location.

A suggested solution is to do what other databases do -- write the backup to a separate file, say `<intended_backup_filename>.tmp` and when done writing the file, perform an _atomic rename_ operation to change the name of the file from the `.tmp` one to the final filename.

This is a non-breaking change, since externally the behavior will be the same -- the backup file will have the same name and be in the same location. However, we will be guaranteed that any `.zip` files in the backup directory are valid backups and not corrupted.

**Comment by obi1kenobi** [comment]
Is there a planned milestone for this?

**Comment by laa** [comment]
That is enhancement so I put it in 3.0 version

**Comment by taburet** [comment]
Implemented, closing.

**Comment by obi1kenobi** [comment]
The code in the linked diff doesn't actually perform an atomic rename operation -- the `ATOMIC_MOVE` option isn't set in the `Files.move()` method: https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#move(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...)

**Comment by taburet** [comment]
@obi1kenobi thank you for the observation, reopening. Usually, if the file system supports atomic renames, regular renames are also atomic. Anyway, for the sake of strictness I will pass `ATOMIC_MOVE` and then fallback to regular move if the move can't be done atomically. WDYT?

**Comment by taburet** [comment]
`ATOMIC_MOVE` is now used to move files, closing.

**Comment by obi1kenobi** [comment]
Looks great, thank you! It might also be good to log an error to inform the user that atomic moves are not supported by their system -- I definitely would like to know if that were the case for my database.

**Comment by taburet** [comment]
@obi1kenobi ok, I will add a warning to the log.

**Comment by taburet** [comment]
Warning added: https://github.com/orientechnologies/orientdb/commit/2c5c1e3504dce38721741792dff8fc39d61a2ae1

**Comment by obi1kenobi** [comment]
Looks great, thank you!
