### ISSUE TITLE
Multi-property index yields zero results in SELECT

### ISSUE THREAD

**Issue by jlowenz** [orientechnologies/orientdb#5932]
I just discovered what looks like a significant bug with multi-property indices. In short, a select completely fails (i.e. finds zero results, **NO EXCEPTION** or message) if one tries to filter by some combination of the properties in the index.

For example, I have the following values in a class `str_prop`:

```txt
----+-----+--------+----+-----
#   |@RID |@CLASS  |attr|value
----+-----+--------+----+-----
0   |#12:0|str_prop|name|Bob  
1   |#12:1|str_prop|name|Rob  
2   |#12:2|str_prop|name|Tom  
3   |#12:3|str_prop|name|Jon  
4   |#12:4|str_prop|name|Mike 
5   |#12:5|str_prop|name|Lee  
6   |#12:6|str_prop|name|Don  
7   |#12:7|str_prop|name|Ron  
8   |#12:8|str_prop|name|Luke 
----+-----+--------+----+-----
```

with the following index:

```txt
INDEXES (1 altogether)
-------------------------------+----------------+
 NAME                          | PROPERTIES     |
-------------------------------+----------------+
 str_prop.val_attr_version     | value (+)      |
                               | attr (+)       |
                               | version        |
-------------------------------+----------------+
```

and the following queries return 0 results:

```sql
select from str_prop where value="Bob";
select from str_prop where value="Bob" and attr="name";
select from str_prop where value="Bob" and attr="name" and version is null;
```

This continues to fail even if I attempt to rebuild the index.
I have created a minimal working example (SQL script) to reproduce it. Using OrientDB version 2.1.13. 

[create_schema.txt](https://github.com/orientechnologies/orientdb/files/203393/create_schema.txt)

**Comment by luigidellaquila** [comment]
Hi @jlowenz 

by default OrientDB indexes ignore null values (ie. in your case, records with version=null are not indexed).

To fix the problem, you have to change your index definitions as follow:

```
create index str_prop.val_attr_version on str_prop (value,attr,version) notunique METADATA { ignoreNullValues : false };
create index int_prop.val_attr_version on int_prop (value,attr,version) notunique METADATA { ignoreNullValues : false };
```

We are discussing if it's the case to set this as a default in next releases 

Thanks

Luigi

**Comment by jlowenz** [comment]
Ok, @luigidellaquila . I'm still not sure I agree with that behavior for the first two queries, which don't directly involve the null value. I understand that the records implicitly contain a null value, but I think this argues very strongly against the current default of ignoring null values. If I have records with null and not null values, I expect to get back all relevant results, especially when only querying the other properties (whether or not there is an index attached). IMHO, indices should _only_ affect performance, not semantic meaning - that should be reserved for the constraints on properties and relationships. 

I see the section in the documentation that mentions this METADATA parameter, but it seems like the default of ignoring nulls is not following the principle of "least surprise." I was quite surprised. Good to know I can fix my indices for the moment though.

**Comment by luigidellaquila** [comment]
Hi @jlowenz 

I agree with you 100% and I'm pretty sure we will change the defaults in short

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @jlowenz 

We changed this default il v 2.2. Actually we made two changes:

1. all the indexes are now created with ignoreNullValues=false
2. if an index has ignoreNullValues=true, then it's not used for partial match, to avoid the problem you originally reported

Thanks

Luigi
