### ISSUE TITLE
Where condition with nested parenthesis fails

### ISSUE THREAD

**Issue by janjilek** [orientechnologies/orientdb#5939]
Hi,
i have following select 

SELECT FROM Gift WHERE status = 300 AND ((date >= date("1970-01-01 00:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC") AND date < date("2016-04-05 16:09:40.901", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")) OR date IS NULL)

When a try to execute it, I receive this exeption:
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #195: Error on parsing command at position #0: Error on parsing query Query: status = 300 AND ((date >= date("1970-01-01 00:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC") AND date < date("2016-04-05 16:09:40.901", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")) OR date IS NULL) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^
 --> com.orientechnologies.orient.core.exception.OSerializationException: Found invalid ) character at position 65 of text date("2016-04-05 16:09:40.901", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")). Ensure it is opened and closed correctly.

When i remove all parenthesis, everything works just fine.

Its not possible to create more complicated where conditions?

OrientDB: 2.1.11, 2.1.13

Regards
Jan

**Comment by janjilek** [comment]
Some workaround? I have bug on production and its impossible to solve it without more complicated where statement :-( 

Thanks

**Comment by luigidellaquila** [comment]
Hi @janjilek 

I'm taking a look at this. Probably the problem can be easily fixed, but I'm also seeing if I can give you a quick work-around

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @janjilek 

You are running your query on an old db, aren't you?

You have two alternatives here:
- enable strictSql (Studio -> db -> configuration -> there is a flag at the bottom of the page)
- add a blank space between the two closed parentheses:

```
SELECT FROM Gift WHERE status = 300 AND ((date >= date("1970-01-01 00:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC") AND date < date("2016-04-05 16:09:40.901", "yyyy-MM-dd HH:mm:ss.SSS", "UTC") ) OR date IS NULL)

instead of 

SELECT FROM Gift WHERE status = 300 AND ((date >= date("1970-01-01 00:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC") AND date < date("2016-04-05 16:09:40.901", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")) OR date IS NULL)
```

I hope it helps

Thanks

Luigi

**Comment by janjilek** [comment]
Hi,
yes,  I am using old one. I cannot migrate it, because I have a lot of parsing errors on the new one, so it will take some time to migrate it. I will try it with the space and let you know in few minutes. 

Thanks 
Jan

**Comment by janjilek** [comment]
So, when I try to execute it with space on old db, I receive:
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #219: Invalid keyword 'NOTIFICATIONDATE' Command: SELECT FROM Gift WHERE status = 300 AND ((notificationDate >= date("1970-01-01 00:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC") AND notificationDate < date("2016-04-06 10:10:41.971", "yyyy-MM-dd HH:mm:ss.SSS", "UTC") ) notificationDate IS NULL) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^

On the new db, I receive this:
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: SELECT FROM Gift WHERE status = 300 AND ((notificationDate >= date("1970-01-01 00:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC") AND notificationDate < date("2016-04-06 10:10:41.971", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")) notificationDate IS NULL) Encountered "" at line 1, column 41. Was expecting one of:

So not working on stringSQL and nonStrictSQL

Regards
Jan

**Comment by janjilek** [comment]
Sorry for my previous comment, that i deleted. Both of your solutions works ;-)

Thanks for fast reply!
Jan

**Comment by luigidellaquila** [comment]
No problem, I saw that (just a typo ;-) )
Happy to see it worked :)

Closing, thanks!

Luigi
