### ISSUE TITLE
count intersections always return 1

### ISSUE THREAD

**Issue by madnoodlesmlin** [orientechnologies/orientdb#5940]
Hi,

I was trying to count common vertices between two vertices. Say A and B both follow C,D. count = 2.
I tried query like "select count(*) from (select intersect(out('Follow').user_id) from Users where user_id in [1,2])". and it returns "[{"@type"=>"d", "@version"=>0, "count"=>1, "@fieldTypes"=>"count=l"}, {"@type"=>"d", "@version"=>0, "count"=>1, "@fieldTypes"=>"count=l"}]"
When I tried just "select intersect(out('Follow').user_id) from Users where user_id in [1,2]", it returned 20 results.

**Comment by luigidellaquila** [comment]
Hi @madnoodlesmlin 

It's not a bug, the result set of the inner query is made of a single document (that contains two user_ids), so the result of the outer query is correct (1)

You have two alternatives to do what you want to obtain:

the complex one:
```
select count(*) from (
    select expand(user_id) from (
        select intersect(out('Follow').user_id) as user_id from Users where user_id in [1,2]
    )
)
```

the easy one

```
        select intersect(out('Follow').user_id).size() from Users where user_id in [1,2]
```

I hope it helps

Thanks

Luigi
