### ISSUE TITLE
[web] Impossible to download previous version of OriendDB

### ISSUE THREAD

**Issue by janjilek** [orientechnologies/orientdb#5942]
When I try to download previous version, the download starts, but after receiving 4-5MB, it stops and its not possible to continue with download. 

Do you have some download mirror? 

I tried 2.1.7 - 2.1.10
Regads
Jan

**Comment by luigidellaquila** [comment]
Hi @janjilek 

I just tried to download previous versions from my machine and it seems to work fine.
Do you have problems with a specific version? Or is it a general problem? There are no download mirrors, but you can checkout the tag you need from GitHub and build from sources, it's pretty straight forward:

```
git clone <the repo>
git checkout tags/<the tag>
mvn clean install
```

Thanks

Luigi

**Comment by janjilek** [comment]
Thank you, i will try to build it from sources. I live in Germany and I can download only last 3 versions (2.1.13 - 2.1.15), the rest always stops after 4-5MB. But in general download its really slow (maybe 20 minutes).

Jan

**Comment by luigidellaquila** [comment]
That's quite strange... our servers are in Germany...

Luigi

**Comment by luigidellaquila** [comment]
Ok, just forgot to mention this:

http://central.maven.org/maven2/com/orientechnologies/orientdb-community/

I think it will be more useful

Thanks

Luigi

**Comment by janjilek** [comment]
Thank you! The link works perfect! Downloaded in 3 seconds :-) Maybe you should add  the link to the download page. 

Thanks
Jan

**Comment by luigidellaquila** [comment]
Yes, I think I'll do it ;-)

Thanks

Luigi
