### ISSUE TITLE
OutOfMemoryError: Java Heap Space when selecting vertices with many edges, edge count (size) extremely slow

### ISSUE THREAD

**Issue by gerdhub** [orientechnologies/orientdb#5945]
I have a database with a class of 788,164 Vertices (@class: token), connected by 41,404,179 Edges (@class: tokenLnk) with other Vertex classes. The Edges have a composite index on in + out.

In Studio, selecting those vertices by 

`select * from token limit 10`

takes between 20.419 sec and 53.822 sec, displaying edge counts between 100 and 100000 Edges / Vertex.

A query of

`select * from token`

sometimes gives a "java.lang.OutOfMemoryError: Java heap space"

The query 

`select count(distinct(out)) from tokenLnk`

takes a couple of minutes, resulting in count = 327755

The query

`select count(*) from file let $count = out('tokenLnk').size() where content is not null and content.trim() <> '' and $count = 0`

takes 819.882 sec. to complete, although indices are used for the content field.

Is there any possibility to speed this up?

I'm using the new version 2.1.15.

**Comment by gerdhub** [comment]
@luigidellaquila With reference to the java.lang.OutOfMemoryError: Java heap space in Studio, I have two heap dumps of the problem which I can send, each about 500 MB. I have tried to increase max heap size up to 2G without success.

**Comment by gerdhub** [comment]
Is there any news on this issue?

**Comment by laa** [comment]
That is duplication of https://github.com/orientechnologies/orientdb/issues/5504 , please track this issue instead.
