### ISSUE TITLE
Orientdb 2.2 Beta: Cannot update new ORole with inheritedRole writer when writer has record level access

### ISSUE THREAD

**Issue by cvm1ll3** [orientechnologies/orientdb#5946]
I set record level access to default ORole admin, reader and writer. Only admin rid is in _allow, then I add all other ORole rids in _allowRead.

I created another ORole vertex (say admin2) where inheritedRole is writer (rid #4:2). When I update admin2 vertex it says this error:

<code>com.orientechnologies.orient.core.exception.OSecurityException: Cannot update record #4:2: the resource has restricted access</code>

I'm only updating the admin2 ORole vertex and not the writer ORole. This worked in OrientDB 2.2 Alpha.

**Comment by tglman** [comment]
hi @cvm1ll3,

Can you post the full stack trace here ? 
In some cases is correct that a writer is not allowed to update roles, to avoid role escalation.

Regards

**Comment by cvm1ll3** [comment]
Hi @tglman,

Is this the full stack trace?

<code>
{
    "errors": [
        {
            "code": 400,
            "reason": "Bad request",
            "content": "Error on parsing script at position #2: Error on execution of the script\nScript: SETUP_createAlias\n-------^\r\n\tStorage URL=\"plocal:/Users/altermedia/Desktop/CamilleDocs/OrientDB/orientdb/distribution/target/orientdb-community-2.2.0-SNAPSHOT.dir/orientdb-community-2.2.0-SNAPSHOT/databases/StudioSuiteSnapshot001\"\ncom.orientechnologies.orient.core.exception.OSecurityException: Cannot update record #4:2: the resource has restricted access\r\n\tStorage URL=\"plocal:/Users/altermedia/Desktop/CamilleDocs/OrientDB/orientdb/distribution/target/orientdb-community-2.2.0-SNAPSHOT.dir/orientdb-community-2.2.0-SNAPSHOT/databases/StudioSuiteSnapshot001\" in <eval> at line number 2789 at column number 2\ncom.orientechnologies.orient.core.exception.OSecurityException: Cannot update record #4:2: the resource has restricted access\r\n\tStorage URL=\"plocal:/Users/altermedia/Desktop/CamilleDocs/OrientDB/orientdb/distribution/target/orientdb-community-2.2.0-SNAPSHOT.dir/orientdb-community-2.2.0-SNAPSHOT/databases/StudioSuiteSnapshot001\"\nCannot update record #4:2: the resource has restricted access\r\n\tStorage URL=\"plocal:/Users/altermedia/Desktop/CamilleDocs/OrientDB/orientdb/distribution/target/orientdb-community-2.2.0-SNAPSHOT.dir/orientdb-community-2.2.0-SNAPSHOT/databases/StudioSuiteSnapshot001\""
        }
    ]
}
</code>

I can update an ORole vertex before using a role with inherited writer role #4:2. The error seems to be that the writer role is also being updated even if its just an inherited role? Thanks.

**Comment by cvm1ll3** [comment]
HI @tglman,

any updates on the error? I just tested it again in the recent sources and rc1 and it still produces the same error. Thanks.

**Comment by tglman** [comment]
Hi @cvm1ll3,

I haven't been able to write a precise test case to reproduce the problem, that's the main reason why is not fixed, if you can provide a simple test case, will be really easier to fix.

Regards

**Comment by tglman** [comment]
Hi @cvm1ll3,

I haven't been able to write a precise test case to reproduce the problem, that's the main reason why is not fixed, if you can provide a simple test case, will be really easier to fix.

Regards

**Comment by voondo** [comment]
Same issue here. I will try to provide a test case.

**Comment by voondo** [comment]
maybe not related but I get this kind of exceptions when I delete a vertex : 
```
com.orientechnologies.orient.core.metadata.security.ORestrictedAccessHook.onRecordBeforeUpdate(com/orientechnologies/orient/core/metadata/security/ORestrictedAccessHook.java:91)
com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(com/orientechnologies/orient/core/hook/ODocumentHookAbstract.java:257)
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java:1052)
com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(com/orientechnologies/orient/core/tx/OTransactionOptimistic.java:423)
com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(com/orientechnologies/orient/core/tx/OTransactionOptimistic.java:370)
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java:2529)
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java:99)
com.orientechnologies.orient.core.record.impl.ODocument.save(com/orientechnologies/orient/core/record/impl/ODocument.java:1794)
com.orientechnologies.orient.core.record.impl.ODocument.save(com/orientechnologies/orient/core/record/impl/ODocument.java:1785)
com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.removeInverseEdge(com/tinkerpop/blueprints/impls/orient/OrientBaseGraph.java:2161)
com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.removeEdges(com/tinkerpop/blueprints/impls/orient/OrientBaseGraph.java:2064)
com.tinkerpop.blueprints.impls.orient.OrientGraph.removeEdgesInternal(com/tinkerpop/blueprints/impls/orient/OrientGraph.java:440)
com.tinkerpop.blueprints.impls.orient.OrientVertex.remove(com/tinkerpop/blueprints/impls/orient/OrientVertex.java:499)
```

The strange thing is that the vertex is deleted despite the error (which is ok because the user is in _allow).

**Comment by tglman** [comment]
hi @voondo,

for your case the error is due to a linked record that may not be allowed to update, when you use graph a remove of a vertex means an update of all the linked vertices, it can be possible that one of the lined vertex is not allowed to be modified by the current user.

If you are doing a notTx operation is normal that the removed vertex is actually removed because there is no tx to rollback, a stale reference is left in this case in the record that has caused the exception.

we usually suggest to use tx on most of the cases to avoid stale references.

Bye
