### ISSUE TITLE
FullCheckPoint Listener

### ISSUE THREAD

**Issue by maggiolo00** [orientechnologies/orientdb#5947]
Provide a way to register a listener on checkpoint.

Useful for external indexing system like Lucene.

**Comment by smolinari** [comment]
@taburet - just for my curiosity.....do you work for OrientDB?

Scott

**Comment by taburet** [comment]
@smolinari yes, I do, for about a month.

**Comment by smolinari** [comment]
Cool! Congrats. Glad to see the team growing! That is theoretically a good sign for us "customers". :smile: 

Scott

**Comment by taburet** [comment]
OIndexEngine#flush for each engine is now called on OAbstractPaginatedStorage#synch.
