### ISSUE TITLE
Update is not working with 2.1.15 

### ISSUE THREAD

**Issue by Pradnya-Paranjape** [orientechnologies/orientdb#5950]
Hi,

I was using version 2.1.8 and recently updated it to version 2.1.15 but the following query stopped working.

vehicle is a column of type "EMBEDDED" in user table.
update user set user.vehicle[name='bmw'].color = 'red' where user.vehicle contains (name='bmw')

This query does not work with version 2.1.15

vehicle object is in the db in the following format.
[{
name : 'bmw', color:'red'
}, {
name : 'audi' , color : 'blue'
}]

Could somebody please guide me with this. What changes should i do to make this working with one single query.

Thanks,
Pradnya

**Comment by luigidellaquila** [comment]
Hi @Pradnya-Paranjape 

I'll take a look at this asap

Thanks

Luigi

**Comment by Pradnya-Paranjape** [comment]
Thanks Luigi. Awaiting your reply.

**Comment by StarpTech** [comment]
Try updating like this works:

```sql
update Customer set EmbeddedTest.a = 5 where EmbeddedTest.a = 3
```

@Pradnya-Paranjape try:

```
update user set vehicle.color = 'red' where user.vehicle name='bmw'
```

**Comment by Pradnya-Paranjape** [comment]
Hi @StarpTech ,

This does not seem to work for me.

```
Table structure:
---> User Table
settings (EMBEDDED) is a column in user table which contains the following
   { "contact": [
        "38476893458",
        "9857398558"
    ],
    "vehicle": [
        {
            "color": "red",
            "name": 'audi'
        },
        {
            "name": "blue",
            "name": "bmw"
        },
   ]}
```

i tried using the query like this 

`update user set settings.vehicle.color = 'purple' where settings.vehicle.name = 'audi'`

Please let me know if i am doing something wrong here.

Thanks,
Pradnya

**Comment by StarpTech** [comment]
@Pradnya-Paranjape your verhicle is an array you can't access directly by dot notation.

**Comment by G4br13l3** [comment]
Hi @Pradnya-Paranjape,

@StarpTech is right, you can't access an array through the dot notation.
In fact there is no way to update a specific object nested in a collection without iterating on it.

I'm closing this issue as no more relevant. Feel free to comment if you have further doubts.

Thanks.
