### ISSUE TITLE
Question about insert and create vertex.

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientdb#5953]
Hi guys!

Is there something wrong if i use "insert" instead "create vertex" for a class that extends from V?

**Comment by luigidellaquila** [comment]
Hi @alexmm11 

No, absolutely nothing wrong, the underlying operations are exactly the same apart from the check of the class hierarchy (when you use CREATE VERTEX OrientDB checks that the class is a subclass of V)

Thanks

Luigi
