### ISSUE TITLE
Hash index creation

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientdb#5954]
When i create a unique_hash_index, everything appears be ok

![seleccion_050](https://cloud.githubusercontent.com/assets/521303/14373865/15aebad8-fd14-11e5-9ef0-91c1a5a2120b.png)

But in the schema, looks a sbtree  at engine field.

![seleccion_051](https://cloud.githubusercontent.com/assets/521303/14373909/c279f82c-fd14-11e5-9d49-c6030816617d.png)

Is this normal or a bug?

**Comment by maggiolo00** [comment]
hi @alexmm11 

the index is correctly created as unique hash index
but it is a known issue of the metadata api
see here
https://github.com/orientechnologies/orientdb/issues/5297
