### ISSUE TITLE
Synchronous WAL only writes

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#5956]
Let's try to make following changes.

This idea was discussed long time ago but after the last discussion with @taburet I wanted to write it down.

Let's change commit of atomic operation in following way:
1. When we make changes in data files we write changes only to WAL and do not apply them to data files.
2. We keep changes in WAL till either WAL cache will not be completely filled or some time interval (1s. by default) is passed but we introduce several additional concepts:
3. Background thread which will continuously run in the background and inspect WAL cache. This thread will read changes from WAL cache and put them into write cache.
4. Because we do not have complete page data we introduce the concept of a partial page, a page which does not contain all data and will load them upon request to cache. Such pages will be created if  background thread will not find pages related to WAL data mentioned above.
5. Small index inside of WAL which shows which page changes are not moved to write cache.
6. Every time when we read page we check WAL index and if there are still data not moved to write cache we apply those changes from WAL to the page (that is fast because they are contained in WAL cache).

Such approach will not speed up write operations on data which are not cached by the cache (or in other words rarely used) but will provide noticeable speed up for data which are frequently used.

**Comment by lvca** [comment]
This looks like the same of my issue: https://github.com/orientechnologies/orientdb/issues/5638.

**Comment by lvca** [comment]
Could you please explain why "will provide noticeable speed up for data which are frequently used"?

**Comment by laa** [comment]
@lvca It is not the same. The big difference is that this issue safe for synchronous writes, but the issue which you link is not safe. Because any mix of reading and writing data from different threads of the same data will crash not only data consistency, but data structure itself.

**Comment by laa** [comment]
@lvca for rare data, we have the following workflow:
1. Read from the disk.
2. Process data which we read.
3. Read from the  R cache
4. Write to the W cache.

For frequently used data:

1. Read from the R cache.
2. Process data which we read.
3. Read from the  R cache
4. Write to the W cache.

In both cases, we omit the last operation from operation set. But apparently read from the disk is much longer than read from the cache. So there will be minor speed improvement for not cached data.

**Comment by laa** [comment]
Also, target of this issue is not performance but changes which avoid for data crash in case of OOM.

**Comment by laa** [comment]
Not actual
