### ISSUE TITLE
mail.send issue

### ISSUE THREAD

**Issue by shaantheadmin** [orientechnologies/orientdb#5964]
Trying to send email from Orientdb using js function. kindly help on this issue..

As per the documentation followed the steps:[mail.send wiki](https://github.com/orientechnologies/orientdb-docs/blob/88909d85dd1b6f35bc58370671dab216931e1918/Mail-Plugin.md)

**Server Version:** 2.0.12
**Configuration:** orientdb-server-config.xml file updated as per the document.

**Plugin loading status:** 2016-04-11 01:02:28:827 INFO  Installing Mail plugin, loaded 1 profile(s): [default] [OMailPlugin]

Created js function with name: testemail
**Js Code:**
mail.send({
      profile : "default",
      to: "shaantheadmin@gmail.com",
      subject: "The EMail plugin works",
      message : "Sending email from OrientDB Server is so powerful to build real web applications!"
    });

*_Error: *_
Erroronparsingscriptatposition#0: ErroronexecutionofthescriptScript: testemail------^sun.org.mozilla.javascript.EcmaError: ReferenceError: "mail"isnotdefined.(<Unknownsource>#2)in<Unknownsource>atlinenumber2ReferenceError: "mail"isnotdefined.(<Unknownsource>#2)

**Comment by maggiolo00** [comment]
hi @shaantheadmin 

Did you try with the latest version of ODB 2.1.15?
let me check.

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
