### ISSUE TITLE
Orientdb is down I need for help for production settings.

### ISSUE THREAD

**Issue by coldfuzz** [orientechnologies/orientdb#5965]
Hi;
Orientdb is down and It enters swap after some time. I need for help to check production settings and migrate db to enterprice edition. You can see the properties at following.

- ENVIRONMENT
  + environment.dumpCfgAtStartup = true
  + environment.concurrent = true
  + environment.allowJVMShutdown = true
- SCRIPT
  + script.pool.maxSize = 20
- MEMORY
  + memory.useUnsafe = false
  + memory.directMemory.safeMode = false
  + memory.directMemory.trackMode = false
  + memory.directMemory.onlyAlignedMemoryAccess = false
- JVM
  + jvm.gc.delayForOptimize = 600
- STORAGE
  + storage.diskCache.pinnedPages = 20
  + storage.diskCache.bufferSize = 8192
  + storage.diskCache.writeCachePart = 15
  + storage.diskCache.writeCachePageTTL = 86400
  + storage.diskCache.writeCachePageFlushInterval = 25
  + storage.diskCache.writeCacheFlushInactivityInterval = 60000
  + storage.diskCache.writeCacheFlushLockTimeout = -1
  + storage.diskCache.diskFreeSpaceLimit = 100
  + storage.diskCache.diskFreeSpaceCheckInterval = 5
  + storage.diskCache.diskFreeSpaceCheckIntervalInPages = 4096
  + storage.diskCache.keepState = true
  + storage.configuration.syncOnUpdate = false
  + storage.compressionMethod = nothing
  + storage.useWAL = true
  + storage.wal.syncOnPageFlush = false
  + storage.wal.cacheSize = 3000
  + storage.wal.maxSegmentSize = 128
  + storage.wal.maxSize = 4096
  + storage.wal.commitTimeout = 1000
  + storage.wal.shutdownTimeout = 10000
  + storage.wal.fuzzyCheckpointInterval = 300
  + storage.wal.reportAfterOperationsDuringRestore = 10000
  + storage.wal.restore.batchSize = 50000
  + storage.wal.readCacheSize = 1000
  + storage.wal.fuzzyCheckpointShutdownWait = 600
  + storage.wal.fullCheckpointShutdownTimeout = 600
  + storage.wal.path = null
  + storage.makeFullCheckpointAfterCreate = true
  + storage.makeFullCheckpointAfterOpen = true
  + storage.makeFullCheckpointAfterClusterCreate = true
  + storage.diskCache.pageSize = 64
  + storage.lowestFreeListBound = 16
  + storage.cluster.usecrc32 = false
  + storage.lockTimeout = 0
  + storage.record.lockTimeout = 2000
  + storage.useTombstones = false
- RECORD
  + record.downsizing.enabled = true
- OBJECT
  + object.saveOnlyDirty = false
- DB
  + db.pool.min = 1
  + db.pool.max = 50
  + db.pool.idleTimeout = 0
  + db.pool.idleCheckDelay = 0
  + db.mvcc.throwfast = false
  + db.validation = true
- NONTX
  + nonTX.recordUpdate.synch = false
  + nonTX.clusters.sync.immediately = manindex
- TX
  + tx.trackAtomicOperations = false
- INDEX
  + index.embeddedToSbtreeBonsaiThreshold = 40
  + index.sbtreeBonsaiToEmbeddedThreshold = -1
- HASHTABLE
  + hashTable.slitBucketsBuffer.length = 1500
- INDEX
  + index.auto.synchronousAutoRebuild = true
  + index.auto.lazyUpdates = 10000
  + index.flushAfterCreate = true
  + index.manual.lazyUpdates = 1
  + index.durableInNonTxMode = false
  + index.txMode = FULL
  + index.cursor.prefetchSize = 500000
- SBTREE
  + sbtree.maxDepth = 64
  + sbtree.maxKeySize = 10240
  + sbtree.maxEmbeddedValueSize = 40960
- SBTREEBONSAI
  + sbtreebonsai.bucketSize = 2
  + sbtreebonsai.linkBagCache.size = 100000
  + sbtreebonsai.linkBagCache.evictionSize = 1000
  + sbtreebonsai.freeSpaceReuseTrigger = 0.5
- RIDBAG
  + ridBag.embeddedDefaultSize = 4
  + ridBag.embeddedToSbtreeBonsaiThreshold = -1
  + ridBag.sbtreeBonsaiToEmbeddedToThreshold = -1
- COLLECTIONS
  + collections.preferSBTreeSet = false
- FILE
  + file.trackFileClose = false
  + file.lock = true
  + file.deleteDelay = 10
  + file.deleteRetry = 50
- JNA
  + jna.disable.system.library = true
- NETWORK
  + network.maxConcurrentSessions = 1000
  + network.socketBufferSize = 32768
  + network.lockTimeout = 15000
  + network.socketTimeout = 15000
  + network.requestTimeout = 3600000
  + network.retry = 5
  + network.retryDelay = 500
  + network.binary.loadBalancing.enabled = false
  + network.binary.loadBalancing.timeout = 2000
  + network.binary.maxLength = 32736
  + network.binary.readResponse.maxTimes = 20
  + network.binary.debug = false
  + network.http.maxLength = 1000000
  + network.http.charset = utf-8
  + network.http.jsonResponseError = true
  + network.http.jsonp = false
- OAUTH2
  + oauth2.secretkey = 
- NETWORK
  + network.http.sessionExpireTimeout = 300
  + network.http.useToken = false
  + network.token.secretyKey = 
  + network.token.encriptionAlgorithm = HmacSHA256
  + network.token.expireTimeout = 60
- PROFILER
  + profiler.enabled = true
  + profiler.config = null
  + profiler.autoDump.interval = 0
  + profiler.maxValues = 200
- LOG
  + log.console.level = info
  + log.file.level = fine
- COMMAND
  + command.timeout = 0
- QUERY
  + query.scanThresholdTip = 50000
  + query.limitThresholdTip = 10000
- SQL
  + sql.graphConsistencyMode = tx
- CLIENT
  + client.channel.maxPool = 100
  + client.connectionPool.waitTimeout = 5000
  + client.channel.dbReleaseWaitTimeout = 10000
  + client.ssl.enabled = false
  + client.ssl.keyStore = null
  + client.ssl.keyStorePass = null
  + client.ssl.trustStore = null
  + client.ssl.trustStorePass = null
  + client.session.tokenBased = false
- SERVER
  + server.channel.cleanDelay = 5000
  + server.cache.staticFile = false
  + server.log.dumpClientExceptionLevel = FINE
  + server.log.dumpClientExceptionFullStackTrace = false
- DISTRIBUTED
  + distributed.crudTaskTimeout = 3000
  + distributed.commandTaskTimeout = 10000
  + distributed.commandLongTaskTimeout = 86400000
  + distributed.deployDbTaskTimeout = 1200000
  + distributed.deployChunkTaskTimeout = 15000
  + distributed.deployDbTaskCompression = 7
  + distributed.queueTimeout = 5000
  + distributed.asynchQueueSize = 0
  + distributed.asynchResponsesTimeout = 15000
  + distributed.purgeResponsesTimerDelay = 15000
  + distributed.queueMaxSize = 10000
  + distributed.backupDirectory = ../backup/databases
  + distributed.concurrentTxMaxAutoRetry = 10
  + distributed.concurrentTxAutoRetryDelay = 100
- DB
  + db.makeFullCheckpointOnIndexChange = true
  + db.makeFullCheckpointOnSchemaChange = true
  + db.document.serializer = ORecordSerializerBinary
- LAZYSET
  + lazyset.workOnStream = true
- DB
  + db.mvcc = true
  + db.use.distributedVersion = false
- MVRBTREE
  + mvrbtree.timeout = 0
  + mvrbtree.nodePageSize = 256
  + mvrbtree.loadFactor = 0.7
  + mvrbtree.optimizeThreshold = 100000
  + mvrbtree.entryPoints = 64
  + mvrbtree.optimizeEntryPointsFactor = 1.0
  + mvrbtree.entryKeysInMemory = false
  + mvrbtree.entryValuesInMemory = false
  + mvrbtree.ridBinaryThreshold = -1
  + mvrbtree.ridNodePageSize = 64
  + mvrbtree.ridNodeSaveMemory = false
- TX
  + tx.commit.synch = false
  + tx.autoRetry = 1
  + tx.log.fileType = classic
  + tx.log.synch = false
  + tx.useLog = false
- INDEX
  + index.auto.rebuildAfterNotSoftClose = true
- CLIENT
  + client.channel.minPool = 1
- STORAGE
  + storage.keepOpen = false
- CACHE
  + cache.local.enabled = false

**Comment by smolinari** [comment]
Hi Coldfuzz,

To help you, the ODB team will probably also need the hardware specs of your server and the type of operating system you are using. 

Scott

**Comment by coldfuzz** [comment]
Hi you can find hardware specs at following.
Disk
Filesystem            Size  Used Avail Use% Mounted on
astnod14:/vol/ASLPAFPODB01
                      200G   81G  120G  41% /mnt/data

Server : Red Hat Enterprise Linux Server release 6.6 (Santiago)

Memory : MemTotal:       12190636 kB
MemFree:         8760832 kB

CPU 

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 26
model name      : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
stepping        : 4
microcode       : 1808
cpu MHz         : 2000.000
cache size      : 15360 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt hypervisor lahf_lm ida arat epb pln pts dts
bogomips        : 4000.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 26
model name      : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
stepping        : 4
microcode       : 1808
cpu MHz         : 2000.000
cache size      : 15360 KB
physical id     : 2
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt hypervisor lahf_lm ida arat epb pln pts dts
bogomips        : 4000.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 26
model name      : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
stepping        : 4
microcode       : 1808
cpu MHz         : 2000.000
cache size      : 15360 KB
physical id     : 4
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt hypervisor lahf_lm ida arat epb pln pts dts
bogomips        : 4000.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 26
model name      : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
stepping        : 4
microcode       : 1808
cpu MHz         : 2000.000
cache size      : 15360 KB
physical id     : 6
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt hypervisor lahf_lm ida arat epb pln pts dts
bogomips        : 4000.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual

**Comment by laa** [comment]
Hi @coldfuzz 
Could you provide what is  your system memory consumption without OrientDB is running ?
What is  your heap size ?

**Comment by coldfuzz** [comment]
Hi @laa 
Total memory of server is 12GB and I send you current memory consumption. As I know orientdb uses off-heap and I set it to 1GB. You can find machine details at following.

                  -Dstorage.diskCache.bufferSize=8192"

# ORIENTDB memory options, default to 512 of heap.

if [ -z "$ORIENTDB_OPTS_MEMORY" ] ; then
    ORIENTDB_OPTS_MEMORY="-Xms1024m -Xmx1024m"
fi

 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                          
60431 root      20   0 11.7g 8.5g  15m S  3.0 73.5  27:20.92 java                                                                                                                             
    1 root      20   0 26016 1812 1448 S  0.0  0.0   0:01.83 init                                                                                                                             
    2 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kthreadd                                                                                                                         
    3 root      RT   0     0    0    0 S  0.0  0.0   0:00.22 migration/0                                                                                                                      
    4 root      20   0     0    0    0 S  0.0  0.0   0:00.44 ksoftirqd/0                                                                                                                      
    5 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/0                                                                                                                        
    6 root      RT   0     0    0    0 S  0.0  0.0   0:00.38 watchdog/0                                                                                                                       
    7 root      RT   0     0    0    0 S  0.0  0.0   0:00.23 migration/1                                                                                                                      
    8 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/1                                                                                                                        
    9 root      20   0     0    0    0 S  0.0  0.0   0:00.72 ksoftirqd/1                                                                                                                      
   10 root      RT   0     0    0    0 S  0.0  0.0   0:00.32 watchdog/1                                                                                                                       
   11 root      RT   0     0    0    0 S  0.0  0.0   0:00.21 migration/2                                                                                                                      
   12 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/2                                                                                                                        
   13 root      20   0     0    0    0 S  0.0  0.0   0:00.32 ksoftirqd/2                                                                                                                      
   14 root      RT   0     0    0    0 S  0.0  0.0   0:00.32 watchdog/2                                                                                                                       
   15 root      RT   0     0    0    0 S  0.0  0.0   0:00.21 migration/3                                                                                                                      
   16 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/3                                                                                                                        
   17 root      20   0     0    0    0 S  0.0  0.0   0:00.63 ksoftirqd/3                                                                                                                      
   18 root      RT   0     0    0    0 S  0.0  0.0   0:00.32 watchdog/3                                                                                                                       
   19 root      20   0     0    0    0 S  0.0  0.0   0:09.21 events/0                                                                                                                         
   20 root      20   0     0    0    0 S  0.0  0.0   0:07.78 events/1                                                                                                                         
   21 root      20   0     0    0    0 S  0.0  0.0   0:09.47 events/2                                                                                                                         
   22 root      20   0     0    0    0 S  0.0  0.0   0:12.57 events/3                                                                                                                         
   23 root      20   0     0    0    0 S  0.0  0.0   0:00.00 cgroup                                                                                                                           
   24 root      20   0     0    0    0 S  0.0  0.0   0:00.00 khelper                                                                                                                          
   25 root      20   0     0    0    0 S  0.0  0.0   0:00.00 netns                                                                                                                            
   26 root      20   0     0    0    0 S  0.0  0.0   0:00.00 async/mgr                                                                                                                        
   27 root      20   0     0    0    0 S  0.0  0.0   0:00.00 pm                                                                                                                               
   28 root      20   0     0    0    0 S  0.0  0.0   0:00.96 sync_supers                                                                                                                      
   29 root      20   0     0    0    0 S  0.0  0.0   0:01.34 bdi-default                                                                                                                      
   30 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kintegrityd/0                                                                                                                    
   31 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kintegrityd/1                                                                                                                    
   32 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kintegrityd/2                                                                                                                    
   33 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kintegrityd/3                                                                                                                    
   34 root      20   0     0    0    0 S  0.0  0.0   0:00.31 kblockd/0

**Comment by coldfuzz** [comment]
Hi @laa 
Total memory of server is 12GB and I send you current memory consumption. As I know orientdb uses off-heap and I set it to 1GB. You can find machine details at following.

                  -Dstorage.diskCache.bufferSize=8192"

# ORIENTDB memory options, default to 512 of heap.

if [ -z "$ORIENTDB_OPTS_MEMORY" ] ; then
    ORIENTDB_OPTS_MEMORY="-Xms1024m -Xmx1024m"
fi

 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                          
60431 root      20   0 11.7g 8.5g  15m S  3.0 73.5  27:20.92 java                                                                                                                             
    1 root      20   0 26016 1812 1448 S  0.0  0.0   0:01.83 init                                                                                                                             
    2 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kthreadd                                                                                                                         
    3 root      RT   0     0    0    0 S  0.0  0.0   0:00.22 migration/0                                                                                                                      
    4 root      20   0     0    0    0 S  0.0  0.0   0:00.44 ksoftirqd/0                                                                                                                      
    5 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/0                                                                                                                        
    6 root      RT   0     0    0    0 S  0.0  0.0   0:00.38 watchdog/0                                                                                                                       
    7 root      RT   0     0    0    0 S  0.0  0.0   0:00.23 migration/1                                                                                                                      
    8 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/1                                                                                                                        
    9 root      20   0     0    0    0 S  0.0  0.0   0:00.72 ksoftirqd/1                                                                                                                      
   10 root      RT   0     0    0    0 S  0.0  0.0   0:00.32 watchdog/1                                                                                                                       
   11 root      RT   0     0    0    0 S  0.0  0.0   0:00.21 migration/2                                                                                                                      
   12 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/2                                                                                                                        
   13 root      20   0     0    0    0 S  0.0  0.0   0:00.32 ksoftirqd/2                                                                                                                      
   14 root      RT   0     0    0    0 S  0.0  0.0   0:00.32 watchdog/2                                                                                                                       
   15 root      RT   0     0    0    0 S  0.0  0.0   0:00.21 migration/3                                                                                                                      
   16 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 stopper/3                                                                                                                        
   17 root      20   0     0    0    0 S  0.0  0.0   0:00.63 ksoftirqd/3                                                                                                                      
   18 root      RT   0     0    0    0 S  0.0  0.0   0:00.32 watchdog/3                                                                                                                       
   19 root      20   0     0    0    0 S  0.0  0.0   0:09.21 events/0                                                                                                                         
   20 root      20   0     0    0    0 S  0.0  0.0   0:07.78 events/1                                                                                                                         
   21 root      20   0     0    0    0 S  0.0  0.0   0:09.47 events/2                                                                                                                         
   22 root      20   0     0    0    0 S  0.0  0.0   0:12.57 events/3                                                                                                                         
   23 root      20   0     0    0    0 S  0.0  0.0   0:00.00 cgroup                                                                                                                           
   24 root      20   0     0    0    0 S  0.0  0.0   0:00.00 khelper                                                                                                                          
   25 root      20   0     0    0    0 S  0.0  0.0   0:00.00 netns                                                                                                                            
   26 root      20   0     0    0    0 S  0.0  0.0   0:00.00 async/mgr                                                                                                                        
   27 root      20   0     0    0    0 S  0.0  0.0   0:00.00 pm                                                                                                                               
   28 root      20   0     0    0    0 S  0.0  0.0   0:00.96 sync_supers                                                                                                                      
   29 root      20   0     0    0    0 S  0.0  0.0   0:01.34 bdi-default                                                                                                                      
   30 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kintegrityd/0                                                                                                                    
   31 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kintegrityd/1                                                                                                                    
   32 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kintegrityd/2                                                                                                                    
   33 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kintegrityd/3                                                                                                                    
   34 root      20   0     0    0    0 S  0.0  0.0   0:00.31 kblockd/0

**Comment by laa** [comment]
Hi @coldfuzz ,
Let me know if I got you correctly, you set disk buffer size to be 8192 megabytes or 8 G, also your heap size is 1 G, which gives 9 G plus wal cache size , you have server with 12 G of memory which equals to consumption of 75% of memory. 
That is exactly (well console output has bad formatting) what is shown as result of console output.

That is may be reason why OS put part of the files on swap.

Did I understand correctly data which you provided to me ?

**Comment by coldfuzz** [comment]
Yes you understand correctly. But I dont understand wal cache size size what is it and how we can configure this and what is your advice for our production settings ?
Best Regards.

**Comment by coldfuzz** [comment]
Hi @laa  can you reply my message.

**Comment by laa** [comment]
HI @coldfuzz , wal cache size is very small it consist of 3 000 pages of 64 kB each , which gives in sum 
about 187 Mb of memory. 
In general the bigger disk cache you have the better, so I would suggest to do following steps:
1.  Decrease linux swap policy ,   I suppose it is placed under `/etc/sysctl.conf` and probably you may be able to get current level of at `/proc/sys/vm/swappiness` . I think `vm.swappiness = 10`  is good value for this case.
2. If you still  see that server RAM is still swapped I suggest you to decrease size of disk cache on 1 Gb.

**Comment by laa** [comment]
Closed because of no reply
