### ISSUE TITLE
How to I get Enterprice Edition

### ISSUE THREAD

**Issue by coldfuzz** [orientechnologies/orientdb#5966]
Hi;
How can I download enterprice edition.

**Comment by smolinari** [comment]
You can download the software here: http://orientdb.com/download-orientdb-enterprise/

And you can contact them about purchasing the full Enterprise version with support here: enquiries@orientdb.com

Here is the web site: http://orientdb.com/orientdb-enterprise/

Scott

**Comment by smolinari** [comment]
Oh, and I am certain you'll get a response from them in the next couple hours at the latest here too.

Scott

**Comment by coldfuzz** [comment]
Hi Scott;
I have support for enterprise edition :)

**Comment by smolinari** [comment]
Ah. Great. Hope the team get to you soon then. Does the download link help?

Scott

**Comment by coldfuzz** [comment]
Hi;
There is a link for download for enterprise edition for development. I can these enterprise edition for also production.

**Comment by smolinari** [comment]
I am not sure myself how the Enterprise version is "controlled" or if the developer version is reduced in functionality. I believe you can use it, if you have the Enterprise license in a live system. Then again, ODB should have given you directions on how to use the Enterprise license/ version and how to get the proper software too. I can't imagine they didn't do that. 

Scott

**Comment by lvca** [comment]
Hi,
The Enterprise Edition (EE) link you receive is a full working EE and can be used only in development. If you use it in production, it's a violation of the license. To use OrientDB production, you can use the Community Edition for FREE, or you can buy the Enterprise Edition (write to info -at- orientdb.com for a quote).

**Comment by coldfuzz** [comment]
Hi Luca;
We have a license for enterprise edition. I just tried to understand orientdb enterprise edition for development also okey for production.

**Comment by luigidellaquila** [comment]
Hi @coldfuzz 

The EE version you download from the website is the official one, so it's definitely OK for production.

For Enterprise support please use PrjHub (your account is already active), you will have priority access and private issue tracker

Thanks

Luigi
