### ISSUE TITLE
Full text index not used to speed up query, causing poor performance

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#5969]
Using OrientDB 2.1.13:

```
CREATE CLASS Abs ABSTRACT
CREATE PROPERTY Abs.name String
CREATE INDEX Abs.name FULLTEXT
CREATE CLASS Ext EXTENDS Abs

INSERT INTO Ext SET name = 'abc'
INSERT INTO Ext SET name = 'def'
INSERT INTO Ext SET name = 'xyz'

// no index used (involvedIndexes does not exist in the returned data)
EXPLAIN SELECT * FROM Ext WHERE name = 'xyz'

// index found (Abs.name) but seems to not be used regardless (3 records and documents read)
// performance on larger datasets is consistent with a table scan
EXPLAIN SELECT * FROM Abs WHERE name = 'xyz'

DROP INDEX Abs.name
CREATE INDEX Abs.name UNIQUE

// index Abs.name used, 1 record and document read in both cases
EXPLAIN SELECT * FROM Ext WHERE name = 'xyz'
EXPLAIN SELECT * FROM Abs WHERE name = 'xyz'
```

This makes `FULLTEXT` indexes actively harmful -- they slow down insert performance without helping speed up query performance.

**Comment by codelimner** [comment]
Try using `name CONTAINSTEXT 'xyz'` instead of `name = 'xyz'` in your query when indexing using fulltext. Your example uses the index fine for me in version 2.1.11 using `CONTAINSTEXT`.

**Comment by obi1kenobi** [comment]
Thanks for the suggestions, I appreciate that you are trying to help. However, `CONTAINSTEXT` creates a fundamentally different query than the `name = 'xyz'` one. Note how the `CONTAINSTEXT` query's results are always a superset of the other query's results, but not vice versa -- making this still a serious bug.

**Comment by laa** [comment]
Assigned to @maggiolo00 , seems like he missed this conversation.

**Comment by maggiolo00** [comment]
Hi @obi1kenobi 

Native fulltext does not support operator = because it will give you wrong results.

From your example

```
INSERT INTO Ext SET name = 'xyz'
INSERT INTO Ext SET name = 'xyza'
```
If the fulltext were used in this case
```
SELECT * FROM Ext WHERE name = 'xyz'
```
it would give you 2 results back which is wrong.
If you want to use the fulltext and + operator you should create two indexes one for exact match, one for fullText Match with ContainsText.

**Comment by obi1kenobi** [comment]
Hi @maggiolo00,

That is not the result I am expecting -- I would like only 1 result in that case. However, the fulltext index is sufficient because it's broader, which means it can be used to avoid the full table scan, narrow the possible result set down to those two records, and then only scan them two instead of the tens of thousands of records in the table.

This is very similar to the idea of trigram indexes in many other databases -- just because the index at hand doesn't immediately answer the query by itself, that doesn't mean it can't be useful to trim down the set of rows that have to be checked.

Also, note that `EXPLAIN SELECT * FROM Abs WHERE name = 'xyz'` says that the index was found and used, when the performance suggests it was not used. This sounds like a bug regardless of the above discussion.

**Comment by maggiolo00** [comment]
@obi1kenobi 

yes it is wrong that is why the full text index is not used with = operator.

We do not support now that concept.

You can manually do that. It is not the best solution but you can do with only one index.

```
SELECT * FROM Abs WHERE name CONTAINSTEXT 'xyz' && name = 'xyz'
```

**Comment by obi1kenobi** [comment]
Thanks for the help -- I ended up switching to a non-FULLTEXT index.

I think that the EXPLAIN SELECT bug is worth fixing though, because it claims an index was used when that's not the case.
