### ISSUE TITLE
Graph Returns Different Versions of Vertex to Web Application

### ISSUE THREAD

**Issue by emhohensee** [orientechnologies/orientdb#5975]
I'm writing a Java web app and I have a page that allows a user to update the properties and add/remove edges from a vertex. 

When I make updates to properties, I save them with code that calls:

```
OrientGraph graph = MyGraphFactorySingleton.getInstance().getGraphInstance();
OrientVertex vertex = graph.getVertex(id);
try {
    for (Map.Entry<String, Object> e : changedProperties.entrySet()) {
          vertex.setProperty(e.getKey(), e.getValue());
    }
}
graph.commit();
return vertex;
```

**This works perfectly and updates the values in the database**, incrementing the version as expected. The issue however, is that when I refresh the page after properties/edges have been changed, it sometimes displays an old version of the vertex with the properties/edges it had at that point. I thought it might be browser caching to I have turned off all HTTP caching and storing. Then I noticed that each time the page refreshes, I can see in my application logs that is really is pulling an old version of the vertex because the `@version`  and properties sometimes change when I refresh. I'm pulling the vertex to view with: 

```
public OrientVertex getVertexByID(String id) {
    OrientGraph graph = MyGraphFactorySingleton.getInstance().getGraphInstance();
    return graph.getVertex(id);
}
```

I think the old vertices must be being cached somewhere and the web app is somehow pulling back cached versions instead of going back to the database each call. Is there a way I can prevent this from happening?

**Comment by luigidellaquila** [comment]
Hi @decafmainline 

a couple of questions for you:
- is there a reason why you are not invoking graph.shutdown() at the end of the method? (you should imho)
- are you connecting in plocal or remote?

Thanks

Luigi

**Comment by decafmainline** [comment]
Hi @luigidellaquila,

I am invoking shutdown at the end in the finally block. Forgot to include it. Here is the full function:

```
   public OrientVertex updateVertex(String id, Map<String, Object> properties) {

        OrientGraph graph = TridentGraphFactorySingleton.getInstance().getGraphInstance();
        OrientVertex vertex = graph.getVertex(id);

        try {
            logger.info("Updating properties " + properties.toString());

            for (Map.Entry<String, Object> e : properties.entrySet()) {
                logger.info("Setting {} to {}", e.getKey(), e.getValue().toString());
                vertex.setProperty(e.getKey(), e.getValue());
                logger.info("Property {} value now {}", e.getKey(), vertex.getProperty(e.getKey()));
            }
            graph.commit();
            return vertex;
        }
        catch (Exception e) {
            logger.error("Unable to update properties on vertex {}", vertex.getId().toString());
            logger.error(e);
            graph.rollback();
        }
        finally {
            graph.shutdown();
        }
        return vertex;
    }
```
This is a remote connection. Thanks!

**Comment by maggiolo00** [comment]
What about this?

```
public OrientVertex getVertexByID(String id) {
    OrientGraph graph = MyGraphFactorySingleton.getInstance().getGraphInstance();
    return graph.getVertex(id);
}
```

Do you call the shutdown after read ?

**Comment by decafmainline** [comment]
I don't. I didn't know that I needed to for a read operation. Should I be calling the read from a try/catch/finally block and shutting down the graph?

**Comment by maggiolo00** [comment]
which operation do you do on the returned OrientVertex?

**Comment by maggiolo00** [comment]
Yes after after you get a Graph from the factory
 you should always shutdown it at the end

**Comment by decafmainline** [comment]
I use this function all over. I update, add, and remove properties as well as create edges with the OrientVertex object that's returned. I'm adding the `graph.shutdown()` now and testing. It makes since that this could cause what I'm seeing.

**Comment by decafmainline** [comment]
I added the shutdown so now the function looks like this:
```
    public OrientVertex getVertexByID(String id) {

        OrientGraph graph = TridentGraphFactorySingleton.getInstance().getGraphInstance();
        try {
            OrientVertex vertex = graph.getVertex(id);
            logger.info("Found vertex {} by ID", vertex.getId());
            return vertex;
        }
        catch (Exception e) {
            graph.rollback();
        }
        finally {
            graph.shutdown();
        }
        return null;
    }
```

Now I am getting an `java.lang.IllegalArgumentException: Class is null` when I call `vertex.getId()` on the returned vertex. I'm checking that the vertex is not null first, and I can see the RID in my logs within the transaction at the database layer. I don't need to have a transaction open to call `getId()`, do I?

**Comment by maggiolo00** [comment]
hi @decafmainline 

That is why i wanted to know what do you do with the returned vertex. The graph should be open when you work with OrientVertex/Edge. When you have finished, you can close it.

**Comment by maggiolo00** [comment]
Btw which framework are you using for the Web App?

**Comment by decafmainline** [comment]
I'm using Spark Java. So, I guess I don't understand what "work" means. Whenever I add, remove, or update properties, or do anything to an edge, I work inside a transaction try/catch block like in the `updateVertex` function I posted. Does calling `getId()` or `getProperties()` or `getType()` mean I'm "doing work" to the vertex? Shouldn't I be able to read static information from the vertex without opening a transaction?

**Comment by decafmainline** [comment]
Do I need to use detach/attach even if I'm not making changes to the vertex? The example listed [here](http://orientdb.com/new-detach-attach-methods-graph-api/) shows `setProperty()` being called. I only need to read information from the OrientVertex object in this case.

**Comment by maggiolo00** [comment]
In this case you should detach the OrientVertex/Edge#detach.

**Comment by decafmainline** [comment]
What happens if I detach a vertex and then don't reattach it? I'm only using it to get information for the web page in this case so there will be no changes and no reason to reattach and save it.

**Comment by decafmainline** [comment]
I modified my function to detach the vertices and added a function to reattach whenever I'm done querying the vertex. I'm still seeing the same `java.lang.IllegalArgumentException: Class is null` error as before though. Any advice? Thanks for your help.

**Comment by decafmainline** [comment]
I've fixed all the issues I was having with attach and detach and I can now query the detached vertices for properties and edges. My original problem still exists and is now worse in that sometimes it shows different edges for the same @version in addition to changing versions on refresh.

**Comment by eugene-kamenev** [comment]
@decafmainline
The very simple solution is to use web-filter to open and close graph at different request processing stages. Or simply just add the check -> if graph is opened and you didnt closed it, close it explicitly after request processing.
