### ISSUE TITLE
Error on unmarshalling JSON content when creating an edge

### ISSUE THREAD

**Issue by SimonShapiro** [orientechnologies/orientdb#5978]
I set up this piece of JSON to use with http API at /batch/db:

`{"transaction":true,
"operations":[
{"type":"c",
"record":{
  "@class":"cef_CONSISTSOF_cef",  
  "out":"#12:37847",
  "in":"#12:37641"}}
]}`

In response I get the following:

`{
  "errors": [
    {
      "code": 500,
      "reason": 500,
      "content": "com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content '{\"transaction\":true,\"operations\":[{\"type\":\"c\",\"record\":{\"@class': content must be between { }"
    }
  ]
}`

Any ideas on what I have done wrong?

**Comment by StarpTech** [comment]
@SimonShapiro How looks your transaction?

**Comment by SimonShapiro** [comment]
It is in the message above

`{"transaction":true, "operations":[ {"type":"c", "record":{ "@class":"cef_CONSISTSOF_cef", "out":"#12:37847", "in":"#12:37641"}} ]}`

**Comment by SimonShapiro** [comment]
I have managed to use this json in a REST client.  So the problem must be in the way I have set up the http call in node.

**Comment by SimonShapiro** [comment]
There were two problems.  The first was that my content-length setting was corrupt.  The second is that using this json only the edge is created and it does NOT link to the vertexes.  In order to achieve the correct linking I had to use:

` {
									type: "cmd",
									language: "sql",
									command: "CREATE EDGE cef_CONSISTSOF_cef FROM ${e.from} TO ${e.to}"
								}`
