### ISSUE TITLE
Question about batch mode.

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientdb#5979]
Hi, is it possible to set 2 or more variables after the word "to" at edge creation?

script sql
begin
let user  = create vertex User content { "name": "Alex" }
let vert1 = create vertex Thing content { "name": "Thing1" }
let vert2 = create vertex Thing content { "name": "Thing2" }
let edg  = create edge IsOwner  from $user to $vert1,$vert2,...
commit retry 100
end

**Comment by StarpTech** [comment]
@alexmm11 

I think this is possible:

```sql
script sql
begin
let user = create vertex User content { "name": "Alex" }
let vert1 = create vertex Thing content { "name": "Thing1" }
let vert2 = create vertex Thing content { "name": "Thing2" }
let edg = create edge IsOwner from $user to [$vert1.@rid, $vert2.@rid]
commit retry 100
end
```

Accroding to the documentation you can give an array of RIDS.
http://orientdb.com/docs/2.1/SQL-Create-Edge.html

**Comment by alexmm11** [comment]
Nope, it is not, i got error :(

**Comment by luigidellaquila** [comment]
Hi @alexmm11 

you can try

```
script sql
begin
let user = create vertex User content { "name": "Alex" }
let vert1 = create vertex Thing content { "name": "Thing1" }
let vert2 = create vertex Thing content { "name": "Thing2" }
let edg = create edge IsOwner from $user to (select list($vert1.@rid, $vert2.@rid) )
commit retry 100
end
```

but I'm afraid it won't work in a transaction (temporary RIDs for newly created vertices)

Thanks

Luigi
