### ISSUE TITLE
Live Query not working as expected

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#5981]
Version: 2.1.9

The Issue: 

when I do a live query like this "live select from Test" then I would expect all changes to this class be notified.

But when I say "live select firstname from Test", where first name is a field in class test then I would expect that it notify only when first name changes.

I am not sure if this is a bug or a unavailable feature at this time. Because the documentation does not talk about this case.

**Comment by smallik** [comment]
Wow! that was rocket speed!!!

**Comment by smallik** [comment]
please include #5982 in the fix. as it is similar. and might require changing the same code.

**Comment by luigidellaquila** [comment]
Hi @smallik 

actually LiveQuery was not implemented to manage the distinct in this case, but I think it makes a lot of sense.

I'll take a look at that asap and I think I'll be able to release this fix before 2.2 GA.
In 2.1 LiveQuery is considered experimental, so I think backporting the fix and changing this behavior is not a big problem

Thanks

Luigi
