### ISSUE TITLE
Live Query view or loaded not working

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#5982]
Version: 2.1.9

Issue:

live query works for Delete, update and create of rows. it is not working for view or when a row is loaded.

I created a live query "live select from Test".
after that, from the webstudio, I tried to update, add and delete rows. live query works fine for all these cases.

but its not notifying when I do a select. with or without predicate.

I think this is a bug because in the OrientDB code below we have four status. and LOADED is not working as expected.

  public static final byte  LOADED           = 0;
  public static final byte  UPDATED          = 1;
  public static final byte  DELETED          = 2;
  public static final byte  CREATED          = 3;

**Comment by luigidellaquila** [comment]
Hi @smallik 

Live query is not intended as an auditing feature, it just notifies changes that happen in the database, so the LOADED operation was deliberately ignored.

BTW, I think returning all the read records would have a huge impact on query performance in general.

I'm sorry, I have to close this issue

Thanks

Luigi
