### ISSUE TITLE
Commit should not be possible after graph.shutdown()

### ISSUE THREAD

**Issue by fc7** [orientechnologies/orientdb#5986]
With 2.2.0-beta2 it appears that by default any OrientGraphFactory is initiated with a pool, which was not the case in 2.1.x. This behavior causes some breaks in our unit tests. When graph.shutdown() is called, OrientDB attempts to close its underlying database, but when the database in an instance of OPartitionedDatabasePool and the acquireCount before the close is larger than 1, the database remains open. Thus it is possible to have the seemingly paradoxical situation of doing first `graph.shutdown(true)` followed by `graph.commit()` without the latter throwing the expected ODatabaseException. 

If you run [this unit test](https://github.com/CompartAG/orientdb-tryouts/blob/master/src/test/java/com/compart/tec/GraphShutdownTest.java) with 2.1.15 it will succeed, but if you update `${orientdb.version}` to 2.2.0-beta2 in the pom, it will fail.

**Comment by tglman** [comment]
fixed in the last develop
