### ISSUE TITLE
Distributed: delta-sync doesn't take in consideration schema/clusters changes

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5989]
Right now if any change happen to clusters/schema, they are not realigned to the node that ask for a delta-sync.

**Comment by lvca** [comment]
My idea is to:
- after the delta-sync, ask for metadata like 1) database structure, 2) schema records, 3) indexes and 4) sequences
- parse database structure, and foreach new cluster, create it. For each dropped cluster, drop it
- overwrite the schema locally

**Comment by lvca** [comment]
For 2.2 I'd prefer to avoid supporting this because after a deeper analysis, it requires more time to develop and test it properly. So in v2.2 if any cluster or indexes has been added or removed, the delta-synch falls back on full replica. It's already in develop branch. I'm going to leave this open to be developed in v3.0

**Comment by smolinari** [comment]
I am not confused, just a little disappointed this can't make 2.2. LOL! :smile: 

Scott

**Comment by lvca** [comment]
I know, me too :-)

**Comment by lvca** [comment]
Closed long time ago.

**Comment by smolinari** [comment]
Do your changes mean this issue will be resolved in 3.0 now?

Scott
