### ISSUE TITLE
server.bat does not set ORIENTDB_HOME environment variable

### ISSUE THREAD

**Issue by Mikkk42** [orientechnologies/orientdb#5990]
On a Windows 10 Pro 64 Bit machine, server.bat script does not set ORIENTDB_HOME variable. No difference whether the script was started with Administrator rights or not.
Machine has latest Java SDK installed.

**Comment by robfrank** [comment]
Which version of ODB? Does the server start or you get an error message? thanks

**Comment by Mikkk42** [comment]
ODB Community Edition 2.1.15
The server does not start. Error message is "The ORIENTDB_HOME environment variable is not defined correctly".

I found that this is a resulting error of java not being part of PATH environment variable. After adding the java.exe containing folder to the PATH variable it worked.
