### ISSUE TITLE
Storage of LINKMAPs has a different behavior in 2.2.0-beta2

### ISSUE THREAD

**Issue by fc7** [orientechnologies/orientdb#5996]
The following unit test:
https://github.com/CompartAG/orientdb-tryouts/blob/master/src/test/java/com/compart/tec/LinkmapTest.java
exemplifies a change in behavior in version 2.2 in how LINKMAPs are stored.

The test succeeds in 2.1.15, but if you change the version to 2.2.0-beta2 in the pom.xml, it will fail.

It seems that in 2.2 the commit (on line 39) leads to a mutation of the `Map<String, OrientVertex>` into a `Map<String, ODocument>`. 

Is this intentional? If yes, how should this be solved?

**Comment by tglman** [comment]
Thank you for the report, we are checking it

**Comment by tglman** [comment]
Hi @fc7,

By tinkerpop specification the only way to link vertex is doing a relationship, adding the verteices with a linked map inside a property is not a graph guaranteed api, and is interpreted by orient as links to documents.

also in 2.1.x this behaviour would happen only in the method that created the record, but not if you reload the record from the db afterwards.

**Comment by fc7** [comment]
@tglman thanks for your analysis. We will modify our implementation so that it works in 2.1 and 2.2
