### ISSUE TITLE
Distributed: delta-sync should scan the database if journal is not available

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5999]
Reading the journal makes delta-sync a super fast operation. However, if the journal is not available because wiped out, the delta-sync should scan the entire database looking for changed pages. This operation is more expensive, but always less expensive than transfer the entire database over the network.

Taking that scanning the pages to read the header checking for pages with LSN > X costs Y, transferring the entire database over the network would cost, at least, Y \* 1000.

**Comment by laa** [comment]
Let's discuss it but I suppose this solution is quite time-consuming it may take hours while we scan all page and during this scan because of concurrency reasons DB will be in read-only mode for hours. I think the usage of operation log is much better solution.

**Comment by laa** [comment]
Probably I will provide a more efficient solution. May be not but according to practice typically it allows to find diffs in binary content very quickly. It is based on usage of Merkle Tree. In nutshell every leaf of the tree is a hash code of content of the page, then each parent node is a hash code of leaf nodes. And each parent node above is a hash code of child nodes, and so on till the root. Typically it allows to update this hash tree in very quick manner and provide very fast lookup of changes.

**Comment by laa** [comment]
I had a chat with @tglman and we agreed that operation log should be a primary solution and Merkle Tree may be used as a possible optimisation in future.
