### ISSUE TITLE
Batch inserter for graph database

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#6001]
Following approach seems to be the best one for batch insertions:
1. Create logical/inheap presentation of our disk data structures such as clusters and indexes.
2. Add data by batches in heap presentation.
3. Once memory will be full put all gathered data directly to the files avoiding all database layers.

This approach may work only in data structures which are append only at least if we split them by partitions and if for cluster we have solution for that. What about indexes ?

Good approach which we may use for indexes is creation of LSM tree based indexes. They by design are partitioned on several partitions and first partition which may be called active because all data modifications are done in this partition is placed only in memory, than this partition is flushed to disk and new in memory partition is created.

**Comment by laa** [comment]
LSM trees are used in Cassandra, HBase, BigTable, LevelDB (from Google), InfluxDB and so on.

**Comment by saeedtabrizi** [comment]
@laa based on [this **benchmark report**](https://github.com/wiredtiger/wiredtiger/wiki/Btree-vs-LSM) , i think the **LSM tree** implementation is a most **valuable step to grow up orientdb** .

**Comment by laa** [comment]
will remove it for now from backlog because we have a suspicion that the rest of issues in backlog will allow fixing this one automatically will back to it once current backlog will be finished.
