### ISSUE TITLE
How to restart web studio without restarting database

### ISSUE THREAD

**Issue by janjilek** [orientechnologies/orientdb#6004]
Hello,
I have problem on my production server. Web studio crashes time to time and sends only ERR_EMPTY_RESPONSE. Is there some way, how to restart studio without restarting db?
I am using OrientDB v 2.1.8

Thank you
Jan

**Comment by maggiolo00** [comment]
hi @janjilek 

how can i replicate this?

You cannot restart Web Studio. It is a javascript/html app only.

**Comment by janjilek** [comment]
hard to say, it crashes after some months (1-3) and writes nothing in the logs. Only solution is to restart db. But for do that, i have to disconnect all the users (we have only 1 db intance).

**Comment by janjilek** [comment]
It's just sending empty response or ERR_CONNECTION_RESET.

**Comment by maggiolo00** [comment]
That's strange.

You can try to move ouy the studio-*.zip from the plugins folder and and move in again. 
This will force to reload the plugin

**Comment by janjilek** [comment]
I changed it and now i can see error in log.  WARNI Reached maximum number of concurrent connections (max=1000, current=1061), reject incoming connection from /x.x.x.x:52597. It looks like, that is not killing connections. My api has 50 connections, don't know, from where is the rest.

**Comment by janjilek** [comment]
So it's maybe a bug in NodeJS driver

**Comment by maggiolo00** [comment]
Can you post your connection code with OrientJS ?

**Comment by janjilek** [comment]
So i restarted api and it released all the connections, so now studio works without restart of the db. But i think, that it should show some popup and not reset connection.

**Comment by maggiolo00** [comment]
You can check the opened connection in Studio -> Server Management from the Home Page then Connections

**Comment by janjilek** [comment]
I can see a lot of opened connection (maybe 100)  from 120 with this signature:
Session ID	Client	Address	Database	User	Total Requests	Command Info	Command Detail	Last Command On	Last Command Info	Last Command Detail	Last Execution Time	Total Working Time	Connected Since	Protocol	Client ID	Driver
9759	/x.x.x.x:53628	-	-	0	-	-	1970-01-01 00:00:00	-	-	0	0	2016-04-20 09:57:59	binary	-

**Comment by janjilek** [comment]
My code is basically only my own pool with 20 opened connections. On the beggining I open 20 connections and then I use round robin to use the connection. When the connection is not used more than x minutes I close it and open new one on request. So maybe I have bug there. But i can see only 20 connections from orientjs driver, the rest is like in the prev post

**Comment by maggiolo00** [comment]
How do you open a connection with orientjs?

**Comment by janjilek** [comment]
let server = OrientDB(config);
let db = server.use({
        name: 'name',
        password: 'password',
        username: 'username'
});
let connection = db.open();

**Comment by maggiolo00** [comment]
when you are done with the connection
do you close the db and the server?

**Comment by janjilek** [comment]
I close only db. Server is singleton instance.

**Comment by maggiolo00** [comment]
hi @janjilek 

seems strange if you have one server instance you should have fixed connections to the database.

**Comment by janjilek** [comment]
Really no idea. But I change for a connection pool and it's working fine.

**Comment by maggiolo00** [comment]
@janjilek 

do you still need help on this?

**Comment by maggiolo00** [comment]
hi @janjilek 

i'm closing this since seems that you have solved it. In case not please reopen it.
Thanks
