### ISSUE TITLE
How to save a document / image in OrientDB

### ISSUE THREAD

**Issue by jfernandezrico** [orientechnologies/orientdb#6007]
Hello,

I'm trying to add a file in a vertex BINARY property but I get next error:

`{
  "errors": [
    {
      "code": 500,
      "reason": 500,
      "content": "com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content for record: \"@class\":\"Ofertas\",\"@version\":0,\"@rid\":\"#-1:-1\",\"nombre\":\"ddd\",\"imagen\":null,\"fecha_fin\":null,\"descripcion\":null,\"pruebas\":null,\"fecha_inicio\":null,\"{{ header }}\":\"$file\"\r\n--> java.lang.IllegalArgumentException: Invalid field name '{{ header }}'. Character ' ' is invalid"
    }
  ]
}`

**Comment by maggiolo00** [comment]
hi @jfernandezrico 

are you uploading file with http api?

**Comment by jfernandezrico** [comment]
I'm uploading the file through Orientdb studio

![image](https://cloud.githubusercontent.com/assets/17267831/14699213/3216ac8a-0796-11e6-9bc7-79e2ae7f0e0d.png)

**Comment by jcwright77** [comment]
similar issue. In 2.2 add binary field and upload image in studio. Creates record with image:null, and the image file is not actually uploaded.
