### ISSUE TITLE
Bellman Ford pathfinding

### ISSUE THREAD

**Issue by lastnod** [orientechnologies/orientdb#6009]
A star doesn't do negative pathfinding.
It's possible to implement Bellman Ford pathfinding ?

**Comment by lvca** [comment]
I think this is stuff for @saeedtabrizi :-)

**Comment by saeedtabrizi** [comment]
Hi @lvca and @lastnod 
Yes it's my favor @lvca :)
@lastnod  it was another kind of path-finding algorithm absolutely  .
I'm planned on Lazy Theta Star now but i promise to implement **negative weight** path-finding algorithms **asap** . 

Thanks 
Saeed
