### ISSUE TITLE
OdocumentDatabaseTx.getMetadata().getSequenceLibrary().getSequenceNames() returns null

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#6010]
Database scheme has sequences and method OrientJdbcConnection.getMetadata().getSequenceLibrary().getSequenceCount() returns correct count.
But OrientJdbcConnection.getMetadata().getSequenceLibrary().getSequenceNames() returns null.

I think it is bug!

**Comment by robfrank** [comment]
I'm sorry, but I can't find such a method called getSequenceLibrary() on DatabaseMetaData https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html

Do you have a snippet of code to share with me?

**Comment by schernolyas** [comment]
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.index.OIndex;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.sequence.OSequenceLibrary;
import com.orientechnologies.orient.jdbc.OrientJdbcConnection;

OrientJdbcConnection connection = (OrientJdbcConnection) provider.getConnection();
ODatabaseDocumentTx db = connection.getDatabase();
if ( db.getMetadata().getSequenceLibrary().getSequenceCount() > 0 ) {
				OSequenceLibrary sequenceLibrary = db.getMetadata().getSequenceLibrary();
				log.infof( "sequence count: %d ", sequenceLibrary.getSequenceCount() );
				log.infof( "sequences : %s ", sequenceLibrary.getSequenceNames() );
                                sequenceLibrary.dropSequence(OrientDBConstant.HIBERNATE_SEQUENCE);
				/*
				 * for (String sequenceName : sequenceLibrary.) { sequenceLibrary.dropSequence(sequenceName); }
				 */
			}

I think, You see class com.orientechnologies.orient.core.metadata.sequence.OSequenceLibrary

**Comment by robfrank** [comment]
Ok, I found the problem, I'm on it, but it is on Orient native api, not on JDBC client. I wonder why are you using JDBC client to connect and then the native API to operate with ODB? It's weird,  but perhaps it is right for you.

**Comment by schernolyas** [comment]
Hi @robfrank 

I tried clear in-memory db in HIbernate OGM uit test and found NPE.
