### ISSUE TITLE
New Database Api for 3.0

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#6011]
We need a review of the current API for improve:
- Simplicity to acquire and completely release the database instances in a consistent way with both graph and document concept
- New Simpler Query API that allow Streamed/Pagined Results

**Comment by lvca** [comment]
I wish also to remove the thread locality, so the same ODatabase* instance can be used by multiple threads.

**Comment by laa** [comment]
Well guys are your sure that removing of thread locality will not break everything ?
For example local caches they have to be thread local. 

Also what is bad in thread locality concept ? IMHO thread locality is good , our problems because of _thread local variables_ not because of thread locality. 

Thread locality makes our database much faster than MT solutions,alos thread locality is trend in many approaches to speed up MT data structures.

**Comment by smolinari** [comment]
What does MT stand for?

Scott

**Comment by laa** [comment]
@smolinari Mutli threading

**Comment by tglman** [comment]
Hi,

I Agree we still need a concept of per "thread session", that keep localcache, transaction, current open user, and a few other bits, but we should limitate the use of thread local.

**Comment by Solido** [comment]
Can we have a sneakpeak of the API somewhere ?

**Comment by luigidellaquila** [comment]
Hi @Solido 

we are writing the docs right now, they will be available this or next week.
In the meantime (definitely incomplete):

https://github.com/orientechnologies/orientdb-docs/blob/master/Java-MultiModel-API.md
https://github.com/orientechnologies/orientdb-docs/blob/master/Java-Query-API.md

Thanks

Luigi

**Comment by tglman** [comment]
Hi Solido,

We are working now on the first packaging and testing procedures for the M1, if you want some really early stage info here:http://orientdb.com/javadoc/latest/ there are the javadocs of the development version, a couple of interesting info class are: http://orientdb.com/javadoc/latest/com/orientechnologies/orient/core/db/OrientDB.html and http://orientdb.com/javadoc/latest/com/orientechnologies/orient/core/db/document/ODatabaseDocument.html#query-java.lang.String-java.util.Map-

**Comment by Solido** [comment]
@tglman @lvca  Thank for the documentation,

Model is much easier to understand ! with current version even after months it's still difficult to have a clear comprehension, having ThinkerPop outside will help a lot.
I hope to get my hands on it ASAP ;)

ps: some typo on Java Query Api 'surnanme' & 'Streamin API'

**Comment by luigidellaquila** [comment]
Thank you @Solido, I'll fix the docs asap.

Just to make it clear, TinkerPop 2.6 and TinkerPop 3 will still be available, but as separate modules

Thanks

Luigi
