### ISSUE TITLE
Indexes are not applyed when bracketed statement exists in query

### ISSUE THREAD

**Issue by facelessTT** [orientechnologies/orientdb#6014]
Hello,
My OrientDB version : 2.1.13
Here is a query: "select from classname where (prop1 = 'a' or prop2 = 'a') and prop3 = 'b'"

I have notunique indexes classname.prop1 and classname.prop2, but they are not used for this query. 
When I doing "select from classname where (prop1 = 'a' or prop2 = 'a')" both indexes are used.

workaround is use "select from (select from classname where (prop1 = 'a' or prop2 = 'a')) where prop3 = 'b'"
but I'm not sure it will work correctly with large amount of data for inner clause and limit\offset applyed.

Or am I doing it wrong? Is there other way to create correct index for bracketed statement?

sorry for my english.

**Comment by luigidellaquila** [comment]
Hi @facelessTT 

Current query execution plan is not smart enough to optimize that query (this is why we are rewriting it). Anyway, the second alternative is definitely OK. You can also try 

```
select from classname where (prop1 = 'a' and prop3 = 'b') or (prop2 = 'a' and prop3 = 'b')
```

This should be correctly optimized and it will be easier to apply skip/limit

Thanks

Luigi

**Comment by facelessTT** [comment]
problem is in most cases its not only "and prop3='b'".... 

> select from classname where (prop1 = 'a' or prop2 = 'a') and prop3='b' and prop4 in [somenotsmallarray] and (prop5='c' or prop6='d')
