### ISSUE TITLE
Unable to export schema only from DB in linux

### ISSUE THREAD

**Issue by rishi3195** [orientechnologies/orientdb#6015]
[orient@apl10613waapp01 logs]$ cd ../../orientdb-community-2.1.8/bin
[orient@apl10613waapp01 bin]$ ./console.sh

OrientDB console v.2.1.8 (build 2.1.x@r; 2015-12-17 11:51:38+0100) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> connect remote:localhost/smart ***** *****

Connecting to database [remote:localhost/smart] with user '*****'...OK
orientdb {db=smart}> export database schemaonly.gz -excludeAll -includeSchema=TRUE
Exporting current database to: database schemaonly.gz -excludeAll -includeSchema=TRUE in GZipped JSON format ...

Started export of database 'smart' to schemaonly.gz...
Exporting schema...OK (41 classes)

Database export completed in 0ms
orientdb {db=smart}> exit

[orient@apl10613waapp01 bin]$ gunzip schemaonly

[orient@apl10613waapp01 bin]$ less schemaonly

{"schema":{"version":1,"classes":[]}}
schemaonly (END)

**Comment by tglman** [comment]
hi @rishi3195,

I fixed this in 2.1.17, so please use the last hotfix, 2.1.19 and everything should be fine.
