### ISSUE TITLE
problem launch server

### ISSUE THREAD

**Issue by lastnod** [orientechnologies/orientdb#6017]
i have this issue when i try to launch the server. As you can see i have the last version of java sdk.
Maybe i do it wrong !

message says : impossible to find or load main classe com.orientechnolo........

![image](https://cloud.githubusercontent.com/assets/8791187/14721301/003082de-0806-11e6-90cd-3265b2ec8e1b.png)

**Comment by maggiolo00** [comment]
hi @lastnod 

seems that you are on Windows. Why don't you use server.bat?

**Comment by lastnod** [comment]
work with .bat
