### ISSUE TITLE
Problem with strict SQL parser - wrapping in parenthesis break the query

### ISSUE THREAD

**Issue by janjilek** [orientechnologies/orientdb#6023]
Hello,
I would like to migrate to strict SQL, but it's not possible, because query builder in OrientJS driver is generating extra parethnesis around order by. When I try to execute SELECT FROM Gift ORDER BY (scheduleDate DESC, @rid DESC) it throws error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: SELECT FROM Gift ORDER BY (scheduleDate DESC, @rid DESC) Encountered " "," ", "" at line 1, column 45. Was expecting one of: ")" ... ")" ...

This parenthesis error happens also in other cases (more complicated where, etc). Why ODB so much care about parenthesis? If I wrap query to x parenthesis it should be still valid query. 

Thank you

**Comment by luigidellaquila** [comment]
Hi @janjilek 

parentheses are OK in the WHERE condition, but in the ORDER BY they do not make sense at all (there is no precedence apart from the order of fields there), this is why this case is not supported.

In the WHERE condition, anyway, with strictSql parentheses are managed much much better than before ;-)

Thanks

Luigi

**Comment by janjilek** [comment]
Ok, but the issue in OrientJS query builder is still there. We can close this one.

**Comment by luigidellaquila** [comment]
Yes, closing.
For reference: https://github.com/orientechnologies/orientjs/issues/170

Thanks

Luigi
