### ISSUE TITLE
Use WebGL for scalability

### ISSUE THREAD

**Issue by lastnod** [orientechnologies/orientdb#6024]
SVG has bad rendering scalability. 
To display 100 000 vertices you should use WebGL rendering 
This project is great you should see it if you don't already have [https://github.com/jacomyal/sigma.js/](https://github.com/jacomyal/sigma.js/)

**Comment by StarpTech** [comment]
@lastnod What is the use case why do you need to display 100 000 vertices ?

**Comment by lastnod** [comment]
i have a products it count 30 000 Vertices wich are linked to activities 50 000 each product and activity have Price K€ i want to have to have the sum of my price by product lvl and activity lvl :D and it's just for products and activities i do it for risks, ressources too :)

**Comment by StarpTech** [comment]
@lastnod you can fire an SUM() query but you don't need to visualize all of your vertices :)

**Comment by maggiolo00** [comment]
@lastnod 

i doubt you can reach 100 000 vertices even with Sigma.

https://github.com/Linkurious/linkurious.js/wiki/Performance

Btw, that is not the scope of the Graph Editor in Studio
