### ISSUE TITLE
updating query results in real time

### ISSUE THREAD

**Issue by lastnod** [orientechnologies/orientdb#6027]
Add as an option to update query results in real time. When you do a query you have a result but if someone does a transaction which has an impact on the result you don't see it. with something like a hook or socket IO that could be "cool"

**Comment by luigidellaquila** [comment]
Hi @lastnod 

are you referring to something similare to LiveQuery?
http://orientdb.com/docs/2.1/Live-Query.html

Thanks

Luigi
