### ISSUE TITLE
Persistently locked vertex

### ISSUE THREAD

**Issue by lukeasrodgers** [orientechnologies/orientdb#6032]
We have a few vertices that are in a persistently locked state, by which I mean whenever we try to add or remove and edge to/from them, we get a `com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException` error.

Changing fields on the vertex works fine. Edges are not being added/removed to the vertex by any other process, as far as I can tell.

This has happened a few times now. The only way we've been able to fix it is to restart orientdb.

We are running one orientdb node in distributed mode.
- ruby driver over HTTP
- version 2.1.5 community

Thanks

**Comment by lvca** [comment]
@andreaiacono this looks like another issue you're looking at, right?

**Comment by lvca** [comment]
Fixed long time ago in 2.2.x.
