### ISSUE TITLE
Gremlin-OrientDB API: Not hitting index.

### ISSUE THREAD

**Issue by jCalamari** [orientechnologies/orientdb#6034]
Hi folks,

I created a property and index on V class which looks as follows: 
Property:

`
Name: some_property
Type: STRING
Mandatory: true
`

Index:
`
name: V.some_property
type: UNIQUE
Properties: ["some_property"]
Engine: SBTREE
`

I am quering underlying in-memory graph database with gremlin API as folllows:

`g.V.has(Key[String]("some_property"), "some_value")`

And I got this warning: 

`
WARNING: {db=in-memory} scanning through all vertices without using an index for Traversal [OrientGraphStep(vertex,[some_property.eq(some_value)])]
`

What am I doing wrong and why the traversal is not hitting the index?

OrientDB version: 2.1.10
Gremlin: 3.1.1-incubating.1

**Comment by kstock** [comment]
I think if you do

```g.getVertices("V.some_property", "some_value")._()```

you can start a gremlin traversal using your index.

Look at the "Using Indices" section of 
http://orientdb.com/docs/2.1/Graph-Database-Tinkerpop.html

**Comment by jCalamari** [comment]
@kstock Thanks. However this is not tinkerpop/gremlin API, is it?

Would you know how to do it with Tinkerpop/Gremlin API?

**Comment by jCalamari** [comment]
Well, I think I've found the reason.

https://github.com/mpollmeier/orientdb-gremlin

> The main area that need some more work is index lookups - currently it does find the right index for a simple case, e.g. g.V.hasLabel("myLabel").has("someKey", "someValue").

**Comment by lvca** [comment]
Implemented by @maggiolo00 in 3.0-m2
