### ISSUE TITLE
Speed up post processing of records/vertexes 

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#6035]
After some profiling we found out that post processing of records and vertices takes are lot of resources in layer above the storage, to improve such situation following steps are proposed:
- [x] Remove calls of com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx#checkOpeness method because this task is already performed on storage layer.
- [x] Split map of hash hooks on 4 arrays related to read/update/delete/create record operations. Add additional argument to the com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx#registerHook(com.orientechnologies.orient.core.hook.ORecordHook, com.orientechnologies.orient.core.hook.ORecordHook.HOOK_POSITION) which will indicate do we need to put records into com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx#inHook to avoid double processing of record by the same hook .
- [ ] Migrate disk cache lock to Java 8 stamped lock.
- [ ] Migrate page lock to Java 8 stamped lock.
- [ ] Add TinyLFU thread-local page buffers to avoid big CAS overhead for frequently accessed pages.
- [ ] all vertices and edges should not load underlying records during loading of vertex/edge instance but will do that on demand, it will save many resources during execution of graph oriented functions.
- [x] Keep all pages changed in atomic operation till commit, it will save one cache roundtrip.

**Comment by lvca** [comment]
👍  Wow, can't wait for all of these thing to be done!

**Comment by lvca** [comment]
Put it in the roadmap for v3.0: https://github.com/orientechnologies/orientdb/issues/6005.

**Comment by tglman** [comment]
hi @laa,

i've a few points: 

be aware that ODatabaseDocumentTx#checkOpeness does a different behaviur of the storage check ( the ODatabaseDocumentTx can be closed with the storage open) so the check can be removed only if is in internal API.

for the hooks the today API has only an onTrigger method without a specific operation, so it's hard to determinte what hook implementation implement what(read/update/delete), we should have differente interface one for each operation, i'll try to check as well if with the latest distributed i can do a refactor to make hooks lighter. Another point on the hook, we cannot skip the call of it with the inHooks, it can create some inconsistence on the call, and anyway do we rellay needs all this hooks ?

All the rest.. Amazing !!

**Comment by tglman** [comment]
hi @laa,

i've a few points: 

be aware that ODatabaseDocumentTx#checkOpeness does a different behaviur of the storage check ( the ODatabaseDocumentTx can be closed with the storage open) so the check can be removed only if is in internal API.

for the hooks the today API has only an onTrigger method without a specific operation, so it's hard to determinte what hook implementation implement what(read/update/delete), we should have differente interface one for each operation, i'll try to check as well if with the latest distributed i can do a refactor to make hooks lighter. Another point on the hook, we cannot skip the call of it with the inHooks, it can create some inconsistence on the call, and anyway do we rellay needs all this hooks ?

All the rest.. Amazing !!

**Comment by taburet** [comment]
For now just I have relaxed the ODatabaseDocumentTx#checkOpeness to check only the status of itself, so if we will not fall into storage operations the storage closeness will be undetected, tests pass. Anyway, this not gives that huge boost to performance compared to commenting out the lock in storage's isClosed. @laa said he is going to implement a new kind of the highly performant lock to fix this. Maybe there is no point in eliminating the checkOpeness at all since the current measured boost is within statistical error margin, but the new lock type will speed up the whole system.

Regarding the hooks, I already started to implement hooks scoping, currently there are five scopes – create, read, update, delete, any (cause we have ORecordHook.TYPE.ANY, should we delete it?). Every hook returns an array of scopes it is interested in, the default is {SCOPE.ANY}. I plan to fine-tune the hooks so each will report the minimal possible set of scopes, this mostly will boost the read operations cause most of the hooks are interested in create, update and delete scopes.

I think there is a very little chance we may avoid the inHooks check, since if at least one of the hooks in the scope decides to make the inHooks check there is no point in trying to avoid the check for other hooks in the same scope. Chances that the inHooks check is not required by all hooks in the scope are not that high as you understand. We may try to sort out the hooks into additional more limited scopes, unique scope for each ORecordHook.TYPE to put it to extreme, but that will raise the complexity of hooks management.

WDYT, guys?

**Comment by tglman** [comment]
hi @taburet,

It make sense split by scopes, anyway be aware that the hook api is a public api, so we cannot change the behavior straight, we should provide a deprecated complatible api for all the old implementations.

**Comment by taburet** [comment]
@laa @tglman do you know the reason behind the existence of `ORecordHook.TYPE#ANY`? It never used in our code base, moreover `ODocumentHookAbstract#onTrigger` throws if `ANY` passed to it. Seem like it should be deprecated at least.

**Comment by laa** [comment]
@tglman I do not think that problem in amount of hooks called (empty methods are removed by JIT) I think there are 2 problems:

1. Conversion to set and iteration by linked list.
2. Constant insert/remove/contains of inHook.

@taburet 

> I think there is a very little chance we may avoid the inHooks check,

Well I am sure :-) that we do it at least for reads.

> Retested the relaxed ODatabaseDocumentTx#checkOpeness in clean environment – it gives measurable boost.

Curious to see numbers.

>  do you know the reason behind the existence of ORecordHook.TYPE#ANY

Nobody knows, it was created by @lvca ages ago.  I propose to discuss that in #dev chat.

**Comment by tglman** [comment]
well @laa hooks are not empty  :( OUserTrigger,OFunctionTrigger,OSchedulerTrigger, ecc check the class( in the hiearchy, and optimized with immutable schema) of the document at each call ...

**Comment by laa** [comment]
@tglman  `OSchedulerTrigger`

```
public RESULT onRecordBeforeRead(final ODocument iDocument) {
    return RESULT.RECORD_NOT_CHANGED;
  }
```

The for after read hook:
```
 public void onRecordAfterRead(final ODocument iDocument) {
  }
```

**Comment by tglman** [comment]
`OSchedulerTrigger extends ODocumentHookAbstract `

```
  public OSchedulerTrigger(ODatabaseDocument database) {
    super(database);
    setIncludeClasses(OScheduler.CLASSNAME);
  }
```

here it check every call: https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/hook/ODocumentHookAbstract.java#L212 befor call "on*"

**Comment by ben-manes** [comment]
Many of your remaining items cover concurrency in regards to caching. For example using thread local to avoid CAS overhead on reads or synchronizing a weak hashmap. You can achieve near lock-free performance using a [write-ahead log approach](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html) instead. That allows [Caffeine](https://github.com/ben-manes/caffeine) to implement policies like size, expiration, and reference collection in O(1) time with low overhead. You might also consider using that library avoid the implementation work involved.

I'm sure aware of the hazards of soft references and I'd strongly advise minimizing the use of them.

**Comment by laa** [comment]
HI @ben-manes , I pleased of your interest in our product.

I think we should try the approach with striped buffers and WAL updates, but I prefer to keep all performance critical parts under our control.  

P.S. We are still interested in TinyLFU as policy for our global disk cache but will send you trace later.

**Comment by ben-manes** [comment]
Sure, that's not a problem. Mostly I was trying to point out that you might be over complicating the concurrency side, which the buffering approach makes much simpler for complex cases.

**Comment by laa** [comment]
Fixed, we got abut 20% speed improvement on traversal and read of vertexes

**Comment by ben-manes** [comment]
Can you point me to your code? Curious and would like to glance through it.
