### ISSUE TITLE
Add "test" suffix to allow maven surefire to execute tests

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#6038]
Some test classes lack the Test suffix on their name, as **OLocalHashTableWAL**.
Maven surefire, which execute tests in the CI env, discovers tests to be executed using a pattern:

_By default, the Surefire Plugin will automatically include all test classes with the following wildcard patterns:

"**/Test*.java" - includes all of its subdirectories and all Java filenames that start with "Test".
"**/*Test.java" - includes all of its subdirectories and all Java filenames that end with "Test".
"**/*TestCase.java" - includes all of its subdirectories and all Java filenames that end with "TestCase".
If the test classes do not follow any of these naming conventions, then configure Surefire Plugin and specify the tests you want to include._ 

Please fix tests that are not executed.

**Comment by robfrank** [comment]
Andrey, test classes should be renamed with Test suffix, e.g.: SBTreeTestBigValues should be renamed to SBTreeTestBigValuesTest to let maven execute it

**Comment by laa** [comment]
@robfrank I remember , but I need to fix them first.

**Comment by robfrank** [comment]
yes, but this way you fix them only on your PC and they're still not running on CI.

**Comment by laa** [comment]
I I've not fixed them yet.

чт, 28 апр. 2016, 12:04 Roberto Franchini <notifications@github.com>:

> yes, but this way you fix them only on your PC and they're still not
> running on CI.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/6038#issuecomment-215359308>
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by robfrank** [comment]
Sorry Andrey, why this issue is postponed to 3.0.x? 
These tests aren't running on CI AND, launched under an IDE, they fail.
If they are useless we can disable or drop. 
I'm in the process of migrating core to Junit, and this is blocking, because to be sure to do all right I need working tests.
Let me know if I can convert them, rename and disable and let you do the work, thanks.

**Comment by laa** [comment]
@robfrank you can "can convert them, rename and disable"  once we will not have critical issues we will take this one.

**Comment by robfrank** [comment]
thanks

**Comment by laa** [comment]
Fixed
