### ISSUE TITLE
In buffer WAL compaction

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#6043]
Now we merely put data in WAL buffer and then flush those raw data to disk.
I propose to add following step to WAL flush task.

During WAL flush we inspect all committed entries and merge them if they related to single page.
It will decrease amount of data on disk because typically page modifications follow temporal locality.

**Comment by tglman** [comment]
Some compaction already happen, because we use : OWALPageChangesPortion

One thing i would like to add is the skip of records for pages that have no change, as today we add a log as soon as we read a page during the atomic operation.

**Comment by laa** [comment]
@tglman 
>today we add a log as soon as we read a page during the atomic operation
 
That is not true, we add log record only we change page , but not when we read it.

**Comment by laa** [comment]
@tglman you are right, we put empty versions, I will create separate issue for that.

**Comment by laa** [comment]
Not actual
