### ISSUE TITLE
Question: Alter property from String to EmbbedSet incl. data conversion

### ISSUE THREAD

**Issue by Cowby** [orientechnologies/orientdb#6048]
Hi everybody,

I'm relatively new to the orientdb cosmos (coming with a strong SQL Background) and facing a problem for which I can't find an elegant solution so any advice would be welcome. 
I'm using orientdb 2.1.15 (update to 2.1.16 will take place in the next days) and I want to change the type from a predefined scheme property (initiated by a former colleague) from String to EmbbedSet. I can't delete the property because in the productive part there has been added a lot of data to that property.
Due to the fact that this isn't implemented at the moment I know that I need to create a second property, move the existing data from the changing property there, delete it and recreate it with the new type to replay the data in EmbbedSet. But how will I achieve the conversion from the String data to the EmbbedSet (in JSON flavor) to be able to replay it? The String doesn't have any structure to be converted, so it is in the end just one tag in the json.

Can anybody give me a short advice? Thanks and regards,

Cowby

**Comment by tglman** [comment]
hi @Cowby,

I suppose you can create a new property of type embedded set, and write a procedure in java(or any other language that you use), that read the field, do the conversion, fill the new field, remove the old one.
this can be done  in java:
```
ODatabaseDocument db = ...
List<ODocument> res = db.query(new OSQLSynchQuery("select from TheClass ");
for(ODocument doc: res) {
      if(doc.containsField("stringField")){
           doc.filed("listField", yourConvertFunction(doc.field("stringField"));
           doc.removeField("stringField");
           db.save(doc);
      }
}
```

**Comment by tglman** [comment]
hi @Cowby 

did this solved your problem can we close this ?

Regards.

**Comment by Cowby** [comment]
Hi @tglman sorry for my delay. Of course that did the trick, but to be honest i achieved that solution before your answer. The purpose of the question was to get a more SQL specific solution and avoid the creation of a special script. But I think you can close this here.
