### ISSUE TITLE
[Auditing Log] Error on resolving property: command

### ISSUE THREAD

**Issue by imainetti** [orientechnologies/orientdb#6051]
As specified in the docs [http://orientdb.com/docs/last/Auditing.html#customize-the-message](http://orientdb.com/docs/last/Auditing.html#customize-the-message) the modifier `${command}` doesn't seem to work.

When triggered, in the server log I get the following:

`INFO  {db=GratefulDeadConcerts} [OVariableParser.resolveVariables] Error on resolving property: command [orientechnologies]
`

![screenshot from 2016-04-27 09-44-45](https://cloud.githubusercontent.com/assets/13220180/14845146/acf9f356-0c5c-11e6-8caf-7a4426b7b8fc.png)

![screenshot from 2016-04-27 09-44-33](https://cloud.githubusercontent.com/assets/13220180/14845147/acfa757e-0c5c-11e6-896a-6a36d1f4395a.png)

**Comment by maggiolo00** [comment]
hi @imainetti 

Hi @imainetti 

It is not a bug. ${command} is available if you do command auditing.
Not class auditing

**Comment by imainetti** [comment]
thank you for the clarification. I'm closing this.
