### ISSUE TITLE
remove data of specific class

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#6053]
Hello, everyone. 

I have situation where I need remove some data belong to class. Is it possible delete all the data belong to specific class from DB and filesystem and delete such class from DB scheme? 
Also how to prevent restoring data belong to such class from wal file's if I delete class from DB? 

Regards,
Valentin.

**Comment by luigidellaquila** [comment]
Hi @valenpo 

A simple DROP CLASS will do the job
http://orientdb.com/docs/last/SQL-Drop-Class.html

Data in WAL are removed periodically, you can force it with a freeze/release, but it works only from console or on a plocal db

Thanks

Luigi

**Comment by valenpo** [comment]
Hi @luigidellaquila 
Thanks for a quick response! I'll follow you instruction. 

Do you have suggestion how to freeze/release wal files of plocal from JAVA API?

Regards,
Valentin.

**Comment by luigidellaquila** [comment]
Hi @valenpo 

There is a `ODatabaseDocumentTx.freeze()` and a `ODatabaseDocumentTx.release()` ;-)

Thanks

Luigi

**Comment by valenpo** [comment]
``
OrientVertexType statType =     graph.getVertexType(type.getClassName());
if (statType != null) {
graph.dropVertexType(type.getClassName());
  graph.getRawGraph().freeze();
  graph.getRawGraph().release();
}
``
