### ISSUE TITLE
Graph shutdown

### ISSUE THREAD

**Issue by stfanbrg** [orientechnologies/orientdb#6055]
Hello,

I am starting with orientDB and I want to delete all vertices in my data base; I am using  Graph API.
I have a method to addData vertices and edges . I have a method to printData in the text console .
I have a dropData methode to remove vertices and edges.
AddData and printData work find. I can used them when I want but after a call to dropData (data are droped, cheked with studio), I cannot used again addData,  printData or dropData, I have this error ==>

Database 'plocal:C:/orientdb-community/orientdb-community-2.1.16/databases/Test' is closed

I call a new graph at the beggining of each method from the factory  (myGraphTx = myFactory.getTx()) and  I used graph.shutdown() at the end of  each method.

what I didn't understand to have this error .

thanks for your help.

**Comment by stfanbrg** [comment]
more informations

Before to call DropDatabase I called myServerAdmin.existsDatabase() ...so if I removed this step, my problem disapears ...any suggestion to understand ?

**Comment by luigidellaquila** [comment]
Hi @stfanbrg 

Can you post some code? My feeling is that you are dropping the db and it's not correctly recreated. 

Thanks

Luigi

**Comment by stfanbrg** [comment]
on click button call = 
`    if (isConnected()) {

      try {
        //if (odbConnection.isDataBaseExists()) {


        try {
          if (odb != null) {
            odb.dropData();
            println("data deleted");
          }
        } catch (Exception exception) {
          LOGGER.log(Level.SEVERE, "MyGui error", exception);
        }
        //}
      } catch (Exception exception) {
        LOGGER.log(Level.SEVERE, "MyGui error", exception);
      }
    }`

DropData of the odb object ask for a graph from the factory  and delete the vertices (edges are automatically deleted ...)
the graph is shutdown with shutdown().

`public void dropData() {
    //TODO régler le problème de database fermée sur OrientGraphBase avec une première utilisation. le code est mis en commentaire 
    setGraph();
    
    for (Vertex v : myGraph.getVertices()) {
      myGraph.removeVertex(v);
    }
    
    shutdownGraphWithComit();
  }`
