### ISSUE TITLE
corrupt edge data

### ISSUE THREAD

**Issue by lukeasrodgers** [orientechnologies/orientdb#6057]
We are running orientdb version 2.1.5 community, ruby driver over HTTP, and appear to have some corrupt edge data in our database, concerning a "Follow" edge between "CpUser" vertices. `[user_ids]` here is a single-element array with one CpUser user_id value.

See the attached screenshot.

You'll notice a few oddities:

* the first two queries that I believe *should* report essentially the same results have a discrepancy
* when I query the `out_Follow` values for the given vertex, one of the results has a value for the `out` field that does not match the vertex in question (rid `#11:81821`).

The corrupt data is preventing some queries from running correctly for this vertex (we get a `NullPointerException` message in the response body).

![screen shot 2016-04-27 at 1 27 36 pm](https://cloud.githubusercontent.com/assets/816444/14866767/3aa80662-0c93-11e6-807b-d1d5c3303a2d.png)

**Comment by StarpTech** [comment]
@lukeasrodgers it is possible to update to 2.1.16 I remember on a simliar issue some many versions before.

**Comment by laa** [comment]
@tglman Could you check whether that is exception which is already fixed ?

**Comment by tglman** [comment]
Hi @lukeasrodgers,

Yes this should be already fixed, can you confirm also on your side ?

Bye

**Comment by lukeasrodgers** [comment]
@tglman I won't be able to confirm any time soon because we don't have an upgrade planned, but feel free to close this issue, and thanks for looking into it.

**Comment by tglman** [comment]
ok, closing, if you reproduce it again comment it we  will reopen
