### ISSUE TITLE
ClassNotFoundException: com.orientechnologies.orient.core.db.graph.OGraphDatabase

### ISSUE THREAD

**Issue by hughjfchen** [orientechnologies/orientdb#6060]
Where is this class? I can't find this class in all orientdb jars. The only database class is com/orientechnologies/orient/core/db/ODatabase.class in the core jar. Should I use this class in core jar instead?

**Comment by luigidellaquila** [comment]
Hi @hughjfchen 

That class no longer exists since maybe v 1.6... What version of OrientDB are you using?
Could you please report the list of orientdb jar files you have in the classpath? My feeling is that you have something wrong there

Thanks

Luigi

**Comment by hughjfchen** [comment]
I'd check 2.1.16 and 2.2.0 beta2 and none of them contains such a class. I think you're right. It no longer exists for a while. Problem is how can I use graph API in java without this class? The only way I can think of is via blueprints API,however,it may lack of some orientdb specific features. Can you give me some tips who to proceed?

**Comment by luigidellaquila** [comment]
Hi @hughjfchen 

I think you can start from here

http://orientdb.com/docs/last/Graph-Database-Tinkerpop.html#getting-started-with-blueprints

Please let me know if you need further help

Thanks

Luigi
