### ISSUE TITLE
(Feature)Property with type 'embedded' cannot be a primary key

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#6061]
Now OrientDB not supports unique indexes for propries with type 'embedded'.
The feature needs for support annotation @EmbeddedId.

See https://en.wikibooks.org/wiki/Java_Persistence/Identity_and_Sequencing#Embedded_Id

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

I'm not sure it's structurally possible, I marked it as an enhancement, we will see if we can do this in 3.0

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila 

Ok. It feature needs for JPA.
