### ISSUE TITLE
Size method doesn't work with intersect function.

### ISSUE THREAD

**Issue by apurvagupta** [orientechnologies/orientdb#6062]
Hi,
 
I am using 2.1.16 orientdb version. There if I use intersect function  with size() to aggregate  it doesn't work.
Even though intersect returns the data but intersect size always returns 0. It was working fine in orientdb version 2.0.14. Now we are trying to upgrade and facing this problem.

**example:**
SELECT expand(r) FROM ( SELECT @rid as r, intersect($allowed, $direct).size() as intersect FROM Resource LET $allowed = ( traverse out('Belongs') FROM ( SELECT FROM Subject WHERE id='Joe' ) ), $direct = in("Can").asSet() WHERE (_domainId='fileName' and _appId='app1') OR (_domainId='fileName2' and _appId='app1') ) WHERE intersect > 0;

Here even though intersect function returns records but size it always returning 0.

**Comment by luigidellaquila** [comment]
Hi @apurvagupta 

it seems to be a regression, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @apurvagupta 

In current stable, intersect() function returns an iterator, that does not have a size() method.

To make it work you can just change the query using 
```
 intersect($allowed, $direct).asList().size()
```

Thanks

Luigi

**Comment by apurvagupta** [comment]
Thanks @luigidellaquila :)
