### ISSUE TITLE
[PROPOSAL] - adding IF EXIST , IF NOT EXIST , TTL keywords to sql syntax 

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#6063]
In some case of database migration , we need to check if there is some property in the class , class , cluster , record , index or function and then execute a sql statement. 
If you add some keywords to orientdb like the **IF EXIST** or **IF NOT EXIST** the programmers can write more efficient and simple database migration procedures .
**TTL** keyword would be useful in Time To Live for entire of record , index  or even some property of a document .
Welcome to your comments

Saeed

**Comment by saeedtabrizi** [comment]
Hi @lvca 
As i see in https://github.com/orientechnologies/orientdb/issues/1110 this issue is open .
i prefer to use TTL keyword with the suggested  syntax .

Thanks
Saeed Tabrizi

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

Happy to help :-)

For the TTL we have no specific plans, but I'll talk to the team about it, maybe we can include it in 3.0

Thanks

Luigi

**Comment by lvca** [comment]
This is already in v3.0-m2.

**Comment by MoayadP** [comment]
@lvca 
Hey, please i still can't find any documentation about TTL in orientdb 3.0- , can u tell me about it please
thanks,
Moayad

**Comment by tarunwadhwa13** [comment]
Same here !! Checked the orientdb documentation for 3.0 but couldn't find any info regarding TTL option !!
