### ISSUE TITLE
OrientDB Update runs into JVM memory issue 'Cannot allocate memory'

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb#6065]
From: http://stackoverflow.com/questions/36915278/orientdb-update-runs-into-jvm-memory-issue-cannot-allocate-memory

---

**Issue**: I just updated my OrientDB (2.0.12) to the latest Version (2.1.16). So I just took the complete folder to test it without my custom settings. Then I tried to start the new version and I got 'Cannot allocate memory'.

---

**How to fix**: Autodetect memory size (feature request)

---

**Fix issue**: 
`if [ -z "$ORIENTDB_OPTS_MEMORY" ] ; then
    ORIENTDB_OPTS_MEMORY="-Xms128m -Xmx256m"
fi` in server.sh

---

**Error Log**:
`
# 
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 357957632 bytes for committing reserved memory.
# Possible reasons:
# The system is out of physical RAM or swap space
# In 32 bit mode, the process size limit was hit
# Possible solutions:
# Reduce memory load on the system
# Increase physical memory or swap space
# Check if swap backing store is full
# Use 64 bit Java on a 64 bit OS
# Decrease Java heap size (-Xmx/-Xms)
# Decrease number of Java threads
# Decrease Java thread stack sizes (-Xss)
# Set larger code cache with -XX:ReservedCodeCacheSize=
# This output file may be truncated or incomplete.
# 
# Out of Memory Error (os_linux.cpp:2827), pid=2840, tid=139969367787264
# 
# JRE version:  (7.0_95) (build )
# Java VM: OpenJDK 64-Bit Server VM (24.95-b01 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.4
# Distribution: Ubuntu 15.10, package 7u95-2.6.4-0ubuntu0.15.10.2
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
# 

---------------  T H R E A D  ---------------

Current thread (0x00007f4d2000c800):  JavaThread "Unknown thread" [_thread_in_vm, id=2844, stack(0x00007f4d28624000,0x00007f4d28725000)]

Stack: [0x00007f4d28624000,0x00007f4d28725000],  sp=0x00007f4d28723510,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x9948f3]
V  [libjvm.so+0x48a9df]
V  [libjvm.so+0x80143b]
V  [libjvm.so+0x7fb82e]
V  [libjvm.so+0x991314]
V  [libjvm.so+0x578372]
V  [libjvm.so+0x937779]
V  [libjvm.so+0x578f12]
V  [libjvm.so+0x5673fd]
V  [libjvm.so+0x95f127]
V  [libjvm.so+0x95f466]
V  [libjvm.so+0x5b574f]
V  [libjvm.so+0x94312f]
V  [libjvm.so+0x626f69]  JNI_CreateJavaVM+0x69
C  [libjli.so+0x2b8e]

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )

Other Threads:

=>0x00007f4d2000c800 (exited) JavaThread "Unknown thread" [_thread_in_vm, id=2844, stack(0x00007f4d28624000,0x00007f4d28725000)]

VM state:not at safepoint (not fully initialized)

VM Mutex/Monitor currently owned by a thread: None

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Internal exceptions (0 events):
No events

Events (0 events):
No events

Dynamic libraries:
00400000-00401000 r-xp 00000000 fd:01 262863                             /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
00600000-00601000 r--p 00000000 fd:01 262863                             /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
00601000-00602000 rw-p 00001000 fd:01 262863                             /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
017dd000-017fe000 rw-p 00000000 00:00 0                                  [heap]
d5a00000-e04a0000 rw-p 00000000 00:00 0 
f5a00000-100000000 rw-p 00000000 00:00 0 
7f4d1d000000-7f4d1d270000 rwxp 00000000 00:00 0 
7f4d1d270000-7f4d20027000 rw-p 00000000 00:00 0 
7f4d20027000-7f4d24000000 ---p 00000000 00:00 0 
7f4d2504e000-7f4d250a4000 rw-p 00000000 00:00 0 
7f4d250a4000-7f4d251a1000 rw-p 00000000 00:00 0 
7f4d251a1000-7f4d251a2000 rw-p 00000000 00:00 0 
7f4d251a2000-7f4d251aa000 r-xp 00000000 fd:01 270817                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libzip.so
7f4d251aa000-7f4d253a9000 ---p 00008000 fd:01 270817                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libzip.so
7f4d253a9000-7f4d253aa000 r--p 00007000 fd:01 270817                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libzip.so
7f4d253aa000-7f4d253ab000 rw-p 00008000 fd:01 270817                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libzip.so
7f4d253ab000-7f4d253b7000 r-xp 00000000 fd:01 1180629                    /lib/x86_64-linux-gnu/libnss_files-2.21.so
7f4d253b7000-7f4d255b6000 ---p 0000c000 fd:01 1180629                    /lib/x86_64-linux-gnu/libnss_files-2.21.so
7f4d255b6000-7f4d255b7000 r--p 0000b000 fd:01 1180629                    /lib/x86_64-linux-gnu/libnss_files-2.21.so
7f4d255b7000-7f4d255b8000 rw-p 0000c000 fd:01 1180629                    /lib/x86_64-linux-gnu/libnss_files-2.21.so
7f4d255b8000-7f4d255c3000 r-xp 00000000 fd:01 1180664                    /lib/x86_64-linux-gnu/libnss_nis-2.21.so
7f4d255c3000-7f4d257c2000 ---p 0000b000 fd:01 1180664                    /lib/x86_64-linux-gnu/libnss_nis-2.21.so
7f4d257c2000-7f4d257c3000 r--p 0000a000 fd:01 1180664                    /lib/x86_64-linux-gnu/libnss_nis-2.21.so
7f4d257c3000-7f4d257c4000 rw-p 0000b000 fd:01 1180664                    /lib/x86_64-linux-gnu/libnss_nis-2.21.so
7f4d257c4000-7f4d257db000 r-xp 00000000 fd:01 1180646                    /lib/x86_64-linux-gnu/libnsl-2.21.so
7f4d257db000-7f4d259da000 ---p 00017000 fd:01 1180646                    /lib/x86_64-linux-gnu/libnsl-2.21.so
7f4d259da000-7f4d259db000 r--p 00016000 fd:01 1180646                    /lib/x86_64-linux-gnu/libnsl-2.21.so
7f4d259db000-7f4d259dc000 rw-p 00017000 fd:01 1180646                    /lib/x86_64-linux-gnu/libnsl-2.21.so
7f4d259dc000-7f4d259de000 rw-p 00000000 00:00 0 
7f4d259de000-7f4d259e6000 r-xp 00000000 fd:01 1180630                    /lib/x86_64-linux-gnu/libnss_compat-2.21.so
7f4d259e6000-7f4d25be5000 ---p 00008000 fd:01 1180630                    /lib/x86_64-linux-gnu/libnss_compat-2.21.so
7f4d25be5000-7f4d25be6000 r--p 00007000 fd:01 1180630                    /lib/x86_64-linux-gnu/libnss_compat-2.21.so
7f4d25be6000-7f4d25be7000 rw-p 00008000 fd:01 1180630                    /lib/x86_64-linux-gnu/libnss_compat-2.21.so
7f4d25be7000-7f4d25c13000 r-xp 00000000 fd:01 270803                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libjava.so
7f4d25c13000-7f4d25e12000 ---p 0002c000 fd:01 270803                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libjava.so
7f4d25e12000-7f4d25e13000 r--p 0002b000 fd:01 270803                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libjava.so
7f4d25e13000-7f4d25e15000 rw-p 0002c000 fd:01 270803                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libjava.so
7f4d25e15000-7f4d25e24000 r-xp 00000000 fd:01 270804                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libverify.so
7f4d25e24000-7f4d26023000 ---p 0000f000 fd:01 270804                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libverify.so
7f4d26023000-7f4d26025000 r--p 0000e000 fd:01 270804                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libverify.so
7f4d26025000-7f4d26026000 rw-p 00010000 fd:01 270804                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libverify.so
7f4d26026000-7f4d2602d000 r-xp 00000000 fd:01 1180625                    /lib/x86_64-linux-gnu/librt-2.21.so
7f4d2602d000-7f4d2622c000 ---p 00007000 fd:01 1180625                    /lib/x86_64-linux-gnu/librt-2.21.so
7f4d2622c000-7f4d2622d000 r--p 00006000 fd:01 1180625                    /lib/x86_64-linux-gnu/librt-2.21.so
7f4d2622d000-7f4d2622e000 rw-p 00007000 fd:01 1180625                    /lib/x86_64-linux-gnu/librt-2.21.so
7f4d2622e000-7f4d26244000 r-xp 00000000 fd:01 1180651                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4d26244000-7f4d26443000 ---p 00016000 fd:01 1180651                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4d26443000-7f4d26444000 r--p 00015000 fd:01 1180651                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4d26444000-7f4d26445000 rw-p 00016000 fd:01 1180651                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4d26445000-7f4d2654c000 r-xp 00000000 fd:01 1180688                    /lib/x86_64-linux-gnu/libm-2.21.so
7f4d2654c000-7f4d2674b000 ---p 00107000 fd:01 1180688                    /lib/x86_64-linux-gnu/libm-2.21.so
7f4d2674b000-7f4d2674c000 r--p 00106000 fd:01 1180688                    /lib/x86_64-linux-gnu/libm-2.21.so
7f4d2674c000-7f4d2674d000 rw-p 00107000 fd:01 1180688                    /lib/x86_64-linux-gnu/libm-2.21.so
7f4d2674d000-7f4d268c0000 r-xp 00000000 fd:01 1050900                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f4d268c0000-7f4d26abf000 ---p 00173000 fd:01 1050900                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f4d26abf000-7f4d26ac9000 r--p 00172000 fd:01 1050900                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f4d26ac9000-7f4d26acb000 rw-p 0017c000 fd:01 1050900                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f4d26acb000-7f4d26acf000 rw-p 00000000 00:00 0 
7f4d26acf000-7f4d27620000 r-xp 00000000 fd:01 270815                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
7f4d27620000-7f4d2781f000 ---p 00b51000 fd:01 270815                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
7f4d2781f000-7f4d278b0000 r--p 00b50000 fd:01 270815                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
7f4d278b0000-7f4d278d3000 rw-p 00be1000 fd:01 270815                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
7f4d278d3000-7f4d278fe000 rw-p 00000000 00:00 0 
7f4d278fe000-7f4d27917000 r-xp 00000000 fd:01 1180090                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f4d27917000-7f4d27b16000 ---p 00019000 fd:01 1180090                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f4d27b16000-7f4d27b17000 r--p 00018000 fd:01 1180090                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f4d27b17000-7f4d27b18000 rw-p 00019000 fd:01 1180090                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f4d27b18000-7f4d27b30000 r-xp 00000000 fd:01 1180626                    /lib/x86_64-linux-gnu/libpthread-2.21.so
7f4d27b30000-7f4d27d30000 ---p 00018000 fd:01 1180626                    /lib/x86_64-linux-gnu/libpthread-2.21.so
7f4d27d30000-7f4d27d31000 r--p 00018000 fd:01 1180626                    /lib/x86_64-linux-gnu/libpthread-2.21.so
7f4d27d31000-7f4d27d32000 rw-p 00019000 fd:01 1180626                    /lib/x86_64-linux-gnu/libpthread-2.21.so
7f4d27d32000-7f4d27d36000 rw-p 00000000 00:00 0 
7f4d27d36000-7f4d27d39000 r-xp 00000000 fd:01 1180661                    /lib/x86_64-linux-gnu/libdl-2.21.so
7f4d27d39000-7f4d27f38000 ---p 00003000 fd:01 1180661                    /lib/x86_64-linux-gnu/libdl-2.21.so
7f4d27f38000-7f4d27f39000 r--p 00002000 fd:01 1180661                    /lib/x86_64-linux-gnu/libdl-2.21.so
7f4d27f39000-7f4d27f3a000 rw-p 00003000 fd:01 1180661                    /lib/x86_64-linux-gnu/libdl-2.21.so
7f4d27f3a000-7f4d280fa000 r-xp 00000000 fd:01 1180689                    /lib/x86_64-linux-gnu/libc-2.21.so
7f4d280fa000-7f4d282fa000 ---p 001c0000 fd:01 1180689                    /lib/x86_64-linux-gnu/libc-2.21.so
7f4d282fa000-7f4d282fe000 r--p 001c0000 fd:01 1180689                    /lib/x86_64-linux-gnu/libc-2.21.so
7f4d282fe000-7f4d28300000 rw-p 001c4000 fd:01 1180689                    /lib/x86_64-linux-gnu/libc-2.21.so
7f4d28300000-7f4d28304000 rw-p 00000000 00:00 0 
7f4d28304000-7f4d28311000 r-xp 00000000 fd:01 270830                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/jli/libjli.so
7f4d28311000-7f4d28510000 ---p 0000d000 fd:01 270830                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/jli/libjli.so
7f4d28510000-7f4d28511000 r--p 0000c000 fd:01 270830                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/jli/libjli.so
7f4d28511000-7f4d28512000 rw-p 0000d000 fd:01 270830                     /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/jli/libjli.so
7f4d28512000-7f4d28536000 r-xp 00000000 fd:01 1180654                    /lib/x86_64-linux-gnu/ld-2.21.so
7f4d2855c000-7f4d28566000 rw-p 00000000 00:00 0 
7f4d28566000-7f4d2861c000 rw-p 00000000 00:00 0 
7f4d2861c000-7f4d28624000 rw-s 00000000 fd:01 917604                     /tmp/hsperfdata_root/2840
7f4d28624000-7f4d28627000 ---p 00000000 00:00 0 
7f4d28627000-7f4d2872a000 rw-p 00000000 00:00 0                          [stack:2844]
7f4d2872f000-7f4d28732000 rw-p 00000000 00:00 0 
7f4d28732000-7f4d28733000 r--p 00000000 00:00 0 
7f4d28733000-7f4d28735000 rw-p 00000000 00:00 0 
7f4d28735000-7f4d28736000 r--p 00023000 fd:01 1180654                    /lib/x86_64-linux-gnu/ld-2.21.so
7f4d28736000-7f4d28737000 rw-p 00024000 fd:01 1180654                    /lib/x86_64-linux-gnu/ld-2.21.so
7f4d28737000-7f4d28738000 rw-p 00000000 00:00 0 
7fff96603000-7fff96624000 rw-p 00000000 00:00 0                          [stack]
7fff9664c000-7fff9664e000 r-xp 00000000 00:00 0                          [vdso]
7fff9664e000-7fff96650000 r--p 00000000 00:00 0                          [vvar]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

VM Arguments:
jvm_args: -Xms512m -Xmx512m -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dprofiler.enabled=true -Djava.util.logging.config.file=/home/ubuntu/orientdb-community-2.1.16/config/orientdb-server-log.properties -Dorientdb.config.file=/home/ubuntu/orientdb-community-2.1.16/config/orientdb-server-config.xml -Dorientdb.www.path=/home/ubuntu/orientdb-community-2.1.16/www -Dorientdb.build.number=2.1.x@r13efec7610a3eceb539db5ebfb31dea2534aa819; 2016-04-19 10:56:07+0000 
java_command: com.orientechnologies.orient.server.OServerMain
Launcher Type: SUN_STANDARD

Environment Variables:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
SHELL=/bin/bash

Signal Handlers:
SIGSEGV: [libjvm.so+0x995450], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGBUS: [libjvm.so+0x995450], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGFPE: [libjvm.so+0x7fc6a0], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGPIPE: [libjvm.so+0x7fc6a0], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGXFSZ: [libjvm.so+0x7fc6a0], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGILL: [libjvm.so+0x7fc6a0], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGUSR1: SIG_DFL, sa_mask[0]=0x00000000, sa_flags=0x00000000
SIGUSR2: [libjvm.so+0x7fc520], sa_mask[0]=0x00000000, sa_flags=0x10000004
SIGHUP: SIG_DFL, sa_mask[0]=0x00000000, sa_flags=0x00000000
SIGINT: SIG_DFL, sa_mask[0]=0x00000000, sa_flags=0x00000000
SIGTERM: SIG_DFL, sa_mask[0]=0x00000000, sa_flags=0x00000000
SIGQUIT: SIG_DFL, sa_mask[0]=0x00000000, sa_flags=0x00000000
SIGTRAP: SIG_DFL, sa_mask[0]=0x00000000, sa_flags=0x00000000

---------------  S Y S T E M  ---------------

OS:Ubuntu 15.10 (wily)
uname:Linux 3.16.0-28-generic #37-Ubuntu SMP Mon Dec 8 17:15:28 UTC 2014 x86_64
libc:glibc 2.21 NPTL 2.21 
rlimit: STACK 8192k, CORE 0k, NPROC 1870, NOFILE 65536, AS infinity
load average:0.00 0.01 0.05

/proc/meminfo:
MemTotal:         501324 kB
MemFree:           45920 kB
MemAvailable:     287044 kB
Buffers:           30884 kB
Cached:           218904 kB
SwapCached:            0 kB
Active:           282244 kB
Inactive:         119768 kB
Active(anon):     163100 kB
Inactive(anon):     8684 kB
Active(file):     119144 kB
Inactive(file):   111084 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               116 kB
Writeback:             0 kB
AnonPages:        152268 kB
Mapped:            62612 kB
Shmem:             19544 kB
Slab:              32376 kB
SReclaimable:      21456 kB
SUnreclaim:        10920 kB
KernelStack:        1920 kB
PageTables:         7732 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      250660 kB
Committed_AS:     895944 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        7828 kB
VmallocChunk:   34359725820 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       36856 kB
DirectMap2M:      487424 kB
DirectMap1G:           0 kB

CPU:total 1 (1 cores per cpu, 1 threads per core) family 6 model 62 stepping 4, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, aes, erms, tsc

/proc/cpuinfo:
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 62
model name  : Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz
stepping    : 4
microcode   : 0x1
cpu MHz     : 2399.998
cache size  : 15360 KB
physical id : 0
siblings    : 1
core id     : 0
cpu cores   : 1
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm arat xsaveopt vnmi ept fsgsbase tsc_adjust smep erms
bogomips    : 4799.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

Memory: 4k page, physical 501324k(45920k free), swap 0k(0k free)

vm_info: OpenJDK 64-Bit Server VM (24.95-b01) for linux-amd64 JRE (1.7.0_95-b00), built on Mar 24 2016 06:07:15 by "buildd" with gcc 5.2.1 20151010

time: Thu Apr 28 16:56:00 2016
elapsed time: 0 seconds
`

---

I already tried to add the memory thing `<entry name="memory.chunk.size" value="‭20971520‬"/>` to `orientdb-server-config.xml`. But that didn't change anything.

**Comment by laa** [comment]
Problem is solved, look at link above , but we may auto detect amount of memory in sh script.

**Comment by kwoxer** [comment]
As I did not get this issue anymore. I think it's fixed. You can close here :)
