### ISSUE TITLE
Is the default value of "server.log.dumpClientExceptionLevel" correctly?

### ISSUE THREAD

**Issue by zhaohng** [orientechnologies/orientdb#6066]
On the Server Management website,the default value of "server.log.dumpClientExceptionLevel" is "rO0ABXNyABdqYXZhLnV0aWwubG9nZ2luZy5MZXZlbI6IcRNRczaSAgADSQAFdmFsdWVMAARuYW1ldAASTGphdmEvbGFuZy9TdHJpbmc7TAAScmVzb3VyY2VCdW5kbGVOYW1lcQB+AAF4cAAAAfR0AARGSU5FdAAic3VuLnV0aWwubG9nZ2luZy5yZXNvdXJjZXMubG9nZ2luZw==".
I truely don't know what does this mean.
The descripiton says "Logs client exceptions. Use any level supported by Java java.util.logging.Level class: OFF, FINE, CONFIG, INFO, WARNING, SEVERE".

**Comment by tglman** [comment]
Hi @zhaohng,

Yes the value is correct, is displayed like that because is storead in the configuration as a java object, but yes we can change it as a string value so will be more clear what it means.

**Comment by tglman** [comment]
made the change to the configuration:https://github.com/orientechnologies/orientdb/commit/490e0da1a36d99cafa83dff1a4c889690b22e2ed  closing
