### ISSUE TITLE
Using indices effectively Through Tinkerpop/Gremlin

### ISSUE THREAD

**Issue by Asimovtech** [orientechnologies/orientdb#6068]
Our small database(approx 92 MB) is starting to run slower.

I'm currently using the Graph API to run queries on OrientDB. I have a few questions about indexing. 
1. Do I have to setup the gremlin index just once? Or do I have to do it each time I run a query.
2. Here's how I run a query, will this method use the gremlin indices effectively? 
   
   public <T> T query(String query, HashMap<String, Object> params) {
       OGremlinHelper.global().create();
       OCommandGremlin command=new OCommandGremlin(query);
       T result=this.getGraph().getRawGraph().command(command).execute(params);
       OGremlinHelper.global().destroy();
       return result;
   }
3. We have subclasses of V and E. would a query like `g.V('<class-name'')` hit the index? If not whats the right way to access subclasses through the index.
4. Are gremlin indexes stable to use in production? I saw an issue about gremlin indices not being deleted properly. If there are issues, whats a safe way to use the database? Is there a way to export/import just the data into a new database so that if we have issues with indices, we can roll back?
5. Worst case scenario: Can we switch over to the Document API for queries and expect better performance and stability?

Please let me know, the issue is getting urgent for us here to solve.

**Comment by lvca** [comment]
Can you post here your slow query?

**Comment by Asimovtech** [comment]
I haven't implemented indexing yet, since I'm not sure what is the right approach, and I"m a little scared that if I do it wrong, I'll lose data. But here is one of the queries we run.

Here's the one that runs slow: `g.V(1).out('UserActivity').order({it.b.getProperty('date') <=> it.a.getProperty('date')}).filter({it.date < start})"`

I assume this is because of the number of edges since its the maximum for this class. I don't think its because of the query.

**Comment by lvca** [comment]
Look at: http://orientdb.com/docs/last/Performance-Tuning-Graph.html#use-indexes-to-lookup-vertices-by-an-id. However, if you use OrientDB SQL you can have far better performance.
