### ISSUE TITLE
Upgrade Lucene to 5.5.0

### ISSUE THREAD

**Issue by maggiolo00** [orientechnologies/orientdb#6069]
On 2.2.x series we can at least upgrade to 5.5.x because Lucene 6.x requires Java8

**Comment by robfrank** [comment]
core done, spatial to do

**Comment by smolinari** [comment]
Cool! Though, wouldn't this advance be reason to have at least a minor version release to 2.3.0?

Scott

**Comment by smolinari** [comment]
@robfrank - Do I understand correctly that Lucene 6.2.0 is now going to be in 2.2.11? Are there any new features that can be taken advantage of directly? This is a pretty cool update from what I understand of Lucene's newer versions.

Scott

**Comment by robfrank** [comment]
no, I'm sorry. We are migrating to 6.2.0 on 3.0.x (develop brach). Even if it could be safe to migrare lucene, such a big version change on a maintenance branch could not be done.

**Comment by smolinari** [comment]
Ahh! :+1: Ok. That makes perfect sense. :smile: 

Thanks for the explanation.

Scott
