### ISSUE TITLE
JSON escaping not supported 

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#6073]
The issue linked with [https://github.com/orientechnologies/orientdb/issues/5911](url). The bug occurs in version 2.2.0-beta2.

IInsert query not parsed.
insert into Book
mark content {"data":"eLuLeqkmovJI1a7WR2OTvVAbLowD\/N4WEHJ6\/2UMmTQNeNSeSE87fZvMvfFStfLYpA0PFGmZ\/m+QmyJ4PPdVm63qoSAW+\/cY1DvmrJ2H4fYhkjasKzUmcOuxhiPUpzYfZXXfAGk0AgqX3fOZ8XkBeoe
KyhFpJDojxcMtG9BO8WjGgpDizD0WgqkSY7hoQZ+PV2Vig7fDn3MnRDGZZLPyyWaSL3J+5DWPdALaQfN+eAhacvqJnnHDPf2yV5Xc8RpqXVUyEPGig60=","isRead":"N","id":"bcf92040-8813-488c-92a7-422cff70dafa","
isPrivate":"F","isShared":0}

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

This issue is already fixed in develop branch, the fix will be released with next 2.2 RC1 (in a very few days hopefully)

Thanks

Luigi
