### ISSUE TITLE
Request for SQL command to delete all edges of class no matter the connection

### ISSUE THREAD

**Issue by seriouslyEnter** [orientechnologies/orientdb#6074]
Beceause I want to drop an edge class I am looking for a way to delete all edges of a class, no matter the connection.

Since this step has to be taken by everyone who wants to drop an edge class to keep data consistency, I expect there is/should be a way to do this within one query.

**Comment by luigidellaquila** [comment]
Hi @seriouslyEnter 

I don't know if I got it right, but did you try this?

```
DELETE EDGE MyEdgeClass

DELETE EDGE MyEdgeClass WHERE foo = 'bar'
```

Thanks

Luigi

**Comment by seriouslyEnter** [comment]
I could not reproduce my Error Message.
The Command does Work.
DELETE EDGE MyEdgeClass

But 
I did try it in console and browser before, with no success and Error Message.
By now I have changed from version 2.1.13 to 2.1.16 with export/import.
And everything works. Maybe it was a symptom of another problem?!
But all good now.
