### ISSUE TITLE
Error on creating a class

### ISSUE THREAD

**Issue by AlessandroRota** [orientechnologies/orientdb#6075]
From Studio with version 2.2-beta2 from IDE when I create a new class it can't extend no class.

![schema](https://cloud.githubusercontent.com/assets/12543436/14952212/e7eadee8-105e-11e6-8fe2-4a45083a2d9a.png)

**Comment by maggiolo00** [comment]
hi @AlessandroRota 

Should be solved in 2.2-rc1, can you confirm this ?

**Comment by AlessandroRota** [comment]
Yes, it is solved.
Thanks.
