### ISSUE TITLE
Distributed database breaks down after removing node

### ISSUE THREAD

**Issue by mamoit** [orientechnologies/orientdb#6076]
Running `2.2-beta`
After I remove a node (kill it) from a distributed setup that is using Hazelcast in AWS, the distributed setup (trying not to use the word cluster here) still tries to communicate with the removed node which still appears in the `clusters>*>servers` of that database.
Is there a way to impose a timeout to purge a node after it has been unresponsive for a predetermined amount of time? Or what is the correct way to scale down a cluster?

**Comment by luigidellaquila** [comment]
Hi @mamoit 

I think it's a bug in the first beta, could you please try the beta2 or even better latest snapshot from here?

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.0-SNAPSHOT/

Thanks

Luigi

**Comment by mamoit** [comment]
Giving `20160502` a spin.

**Comment by mamoit** [comment]
After dropping one of the nodes, the cluster recovers correctly in `20160502`'s snapshot.
Thank you.

**Comment by luigidellaquila** [comment]
Excellent, thanks for the feedback!

Luigi
