### ISSUE TITLE
Insert with UUID funcition use java serialization

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#6079]
in case you of an insert like `insert into V set id = UUID()` the  result of UUID is a object that is serialized using java serialization instead of a string.

**Comment by maggiolo00** [comment]
Possible workaround meanwhile

```
insert into V set id = format("%s",uuid())
```

**Comment by tglman** [comment]
Hi,

this is fixed with the new query engine in 3.0.0. closing
