### ISSUE TITLE
HTTP GET distributed/database/<db> 405 

### ISSUE THREAD

**Issue by mamoit** [orientechnologies/orientdb#6082]
On snapshot `20160502` if I try to curl the endpoint described [here](http://orientdb.com/docs/2.2/Distributed-Runtime.html#database-configuration), it returns a `405`.
```
{
   "errors" : [
      {
         "content" : "Command not found: distributed/database/dbnamehere",
         "code" : 405,
         "reason" : 405
      }
   ]
}
```

**Comment by luigidellaquila** [comment]
Hi @mamoit 

That's available only in EE, I think the problem is there

Thanks

Luigi

**Comment by mamoit** [comment]
I should have read the `NOTE: available only in Enteprise Edition` at the begin of the page.
Thanks and sorry for spamming with this RTFM question.

**Comment by luigidellaquila** [comment]
No problem ;-)
Feel free to ask if you need more help

Luigi

**Comment by mamoit** [comment]
Will do :smile:
