### ISSUE TITLE
Problems with the method getFunction.

### ISSUE THREAD

**Issue by AlessandroRota** [orientechnologies/orientdb#6086]
I'm using the following instructions on version 2.1.0 (client and server) or previous versions

```
OFunction sum=db.getMetadata().getFunctionLibrary().getFunction("sum");
String code=sum.getCode();
```

I get the code of the function sum, while if I use the same instructions on version 2.1.1 ( client and server) or higher , I get a NullPointerException and if I use 

`db.getMetadata().getFunctionLibrary().getFunctionNames();`

I get an empty list.

**Comment by maggiolo00** [comment]
hi @AlessandroRota 

what happen if you do 

```
db.getMetadata().reload();
```

?

**Comment by AlessandroRota** [comment]
Yes, it works.
Thanks.
