### ISSUE TITLE
OClassTrigger doesn't take into account multiple superclasses

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#6092]
OrientDB supports multi super-classes.
But code of OClassTrigger was not changed to support that. Snippet:

``` java
while (fieldName == null || fieldName.length() == 0) {
        if (superClz == null || superClz.getName().equals(CLASSNAME))
          break;
        fieldName = superClz.getCustom(attr);
        superClz = superClz.getSuperClass();
      }
```

Btw, it will be helpfull to have some utility class for caching results of culculations till next schema update. 
For example OClassTrigger is trying to find proper field on every call instead of caching previously obtained results obtained from schema in a cache.

**Comment by tglman** [comment]
commented on the pull request.
