### ISSUE TITLE
Rebuild index in embedded mode stuck in loop

### ISSUE THREAD

**Issue by nsitanurag** [orientechnologies/orientdb#6094]
```
orientdb {db=hola}> rebuild index contact_link.linkIndex;


Rebuilding index(es)...
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'contact_link.linkIndex' not found

orientdb {db=hola}> rebuild index linkIndex;


Rebuilding index(es)...
```

This was the command which was given, however index keep rebuilding again and again and this is the third time it is in progress despite command was given two times only.

2016-05-06 06:27:19:474 INFO  {db=hola} - Rebuilding index hola.linkIndex (estimated 67,251,242 items)... [OIndexRebuildOutputListener]May 06, 2016 6:27:19 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} - Rebuilding index hola.linkIndex (estimated 67,251,242 items)...

2016-05-06 06:27:29:475 INFO  {db=hola} --> 0.28% progress, 185,825 indexed so far (18,582 items/sec) [OIndexRebuildOutputListener]May 06, 2016 6:27:29 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} --> 0.28% progress, 185,825 indexed so far (18,582 items/sec)

2016-05-06 08:09:42:274 INFO  {db=hola} --> 99.89% progress, 67,175,248 indexed so far (7,961 items/sec) [OIndexRebuildOutputListener]May 06, 2016 8:09:42 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} --> 99.89% progress, 67,175,248 indexed so far (7,961 items/sec)

2016-05-06 08:09:50:590 INFO  {db=hola} --> OK, indexed 67,251,242 items in 6,151,116 ms [OIndexRebuildOutputListener]May 06, 2016 8:09:50 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} --> OK, indexed 67,251,242 items in 6,151,116 ms

2016-05-06 08:09:51:321 INFO  {db=hola} - Rebuilding index hola.linkIndex (estimated 67,251,242 items)... [OIndexRebuildOutputListener]May 06, 2016 8:09:51 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} - Rebuilding index hola.linkIndex (estimated 67,251,242 items)...

2016-05-06 08:10:01:322 INFO  {db=hola} --> 0.24% progress, 163,249 indexed so far (16,324 items/sec) [OIndexRebuildOutputListener]May 06, 2016 8:10:01 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} --> 0.24% progress, 163,249 indexed so far (16,324 items/sec)

2016-05-06 09:48:22:765 INFO  {db=hola} --> 99.91% progress, 67,191,295 indexed so far (6,497 items/sec) [OIndexRebuildOutputListener]May 06, 2016 9:48:22 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} --> 99.91% progress, 67,191,295 indexed so far (6,497 items/sec)

2016-05-06 09:48:30:767 INFO  {db=hola} --> OK, indexed 67,251,242 items in 5,919,446 ms [OIndexRebuildOutputListener]May 06, 2016 9:48:30 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} --> OK, indexed 67,251,242 items in 5,919,446 ms

2016-05-06 09:48:31:473 INFO  {db=hola} - Rebuilding index hola.linkIndex (estimated 67,251,242 items)... [OIndexRebuildOutputListener]May 06, 2016 9:48:31 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} - Rebuilding index hola.linkIndex (estimated 67,251,242 items)...

2016-05-06 09:48:41:474 INFO  {db=hola} --> 0.26% progress, 171,570 indexed so far (17,157 items/sec) [OIndexRebuildOutputListener]May 06, 2016 9:48:41 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} --> 0.26% progress, 171,570 indexed so far (17,157 items/sec)

2016-05-06 09:48:51:475 INFO  {db=hola} --> 0.50% progress, 337,755 indexed so far (16,618 items/sec) [OIndexRebuildOutputListener]May 06, 2016 9:48:51 AM com.orientechnologies.common.log.OLogManager log
INFO: {db=hola} --> 0.50% progress, 337,755 indexed so far (16,618 items/sec)

**Why it is getting below exception on executing first command ?
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'contact_link.linkIndex' not found**

**Comment by laa** [comment]
@nsitanurag Could you make following steps:

1. Close database and copy whole directory in a separate folder.
2. Open it and try to reproduce the issue.
3. If that is reproducible send me a copy of the database.
4. Even if the issue is gone put a word in this ticket about a result.

**Comment by nsitanurag** [comment]
Closing the database while index rebuild is in loop may corrupt it or not?

**Comment by laa** [comment]
@nsitanurag so it is still running, right ? Do you have YourKit to profile it ?

**Comment by nsitanurag** [comment]
yeah, it is still running. Can you point me to a tutorial link for profiling?

**Comment by laa** [comment]
You need it in local mode (you need agent to run in remote mode). Is it possible to set it on the server ?

**Comment by nsitanurag** [comment]
Not possible right now as we are doing one time migration of data in embedded mode.

**Comment by laa** [comment]
@nsitanurag then we do not have a choice but stop it and do not touch it. Please send me DB  as is without opening at. It is very important do not open it. We will look at this issue next week. So workaround for you:

1. Stop database.
2. Open the copy of it (please send me an unmodified copy of the database) and wait till restore process will be done. 
3. Drop problematic index and recreate one.

**Comment by nsitanurag** [comment]
Sorry, I can not share the copy of database since it contains sensitive data. Thanks for your help.  However, steps to reproduce are:-
1. you can create an index on link(edge) having some records.
create index linkIndex on contact_link (out, in) unique;
2. try rebuilding index in embedded mode by giving incorrect command as mentioned above:-
rebuild index contact_link.linkIndex;
3. Then fire the correct command:-
rebuild index linkIndex;

This will stuck in loop forever.

**Comment by laa** [comment]
@nsitanurag well, thank you I think that is enough information.

**Comment by taburet** [comment]
Hi @nsitanurag! I'm unable to reproduce the issue using following commands:

```
create database plocal:/tmp/test-db;
create class P extends V;
create property P.name string;
create class C extends E;
create property C.in link;
create property C.out link;
create vertex P set name='name 1';
create vertex P set name='name 2';
create vertex P set name='name 3';
create vertex P set name='name 4';
create vertex P set name='name 5';
create edge C from (select from P where name='name 1') to (select from P where name='name 2');
create edge C from (select from P where name='name 1') to (select from P where name='name 3');
create edge C from (select from P where name='name 1') to (select from P where name='name 4');
create edge C from (select from P where name='name 1') to (select from P where name='name 5');
create edge C from (select from P where name='name 2') to (select from P where name='name 5');
create index linkIndex on C (out, in) unique;
rebuild index C.linkIndex;
rebuild index linkIndex;
```

Could you please try to execute the commands on your side? BTW, which orientdb version do you use and under what OS you run the orientdb console? I have a feeling that the problem may be in the console IO interaction between JVM and OS rather in the rebuild index command.

Regarding your question about the exception, the exception is thrown because there is no such index named `contact_link.linkIndex`, while creating it you gave it the name `linkIndex`. Indexes are not automatically scoped to the class they are created for, but there is a special shortcut syntax `CREATE INDEX person.name UNIQUE` that creates the index named `person.name` for the `name` attribute of the `person` class.

**Comment by nsitanurag** [comment]
I am using the latest orientdb version i.e. 2.1.16. and OS is Debian GNU/Linux 6.0.10 (squeeze)

Your assumption is correct sometimes even if I give correct command, rebuild index gets stuck in loop. So the problem is in console IO interaction between JVM and OS. What can be solution for this?

**Comment by taburet** [comment]
Sorry @nsitanurag, ran out of ideas how to narrow down this problem. Do you get the same executed twice behaviour with other commands? Do you run the console on your local machine or you SSHing to remote one and run the console on it?

**Comment by nsitanurag** [comment]
Yes this twice behaviour is with other commands as well such as create index. I run orient db console by SSHing to remote server.

**Comment by taburet** [comment]
I have created [a special 2.1.16 build](https://drive.google.com/file/d/0B9L-XIp8ztKNWkxKeXVkQXlzSjg/view?usp=sharing) with a more detailed logging about the state of the console and command execution. Please download it and install on the server, run the console from this build, reproduce the "executed twice" behaviour and send me the console output. Thank you.

**Comment by taburet** [comment]
Console prompt support is reworked now as a result of https://github.com/orientechnologies/orientdb/issues/3003 , this also may fix your problem. Please test on the latest 2.1.x or develop branches. If you wish, I may create a binary distribution.

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
