### ISSUE TITLE
ODB client takes time to connect after loosing the connection once.

### ISSUE THREAD

**Issue by apurvagupta** [orientechnologies/orientdb#6095]
Hi, 

I am using orientdb version 2.1.16 with cluster setup of 3 nodes. I was trying some failover scenarios.
And observed that if once the whole cluster(All 3 nodes) goes down after that if your start server again, Client take lot of time to connect again without restarting client. If I restart client it connect instantly. 

Is it a expected behavior?

**Comment by maggiolo00** [comment]
hi @apurvagupta 

are you using Java client?

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.

**Comment by apurvagupta** [comment]
Sorry for late response, Ya I was using java client.
