### ISSUE TITLE
SQLQuery Issue

### ISSUE THREAD

**Issue by eswaras** [orientechnologies/orientdb#6096]
HI Team,
when I am trying to execute a wrong Query .It given exception but didn't rollback. please check once .
String query = "INSERT INTO SuperMarket (Item,Code,Quantity) VALUES('banana',12.33,50)";
graph.command(new OCommandSQL(query).execute());
but actual  query is graph.command(new OCommandSQL(query)).execute();
for more clarity please look into Google groups  POST  is "Insertion Exception " 

version is orientdb-community-2.2.0-SNAPSHOT_1

**Comment by lvca** [comment]
Are you connected with remote or plocal?

**Comment by eswaras** [comment]
Hi lvca,
I have tried both remote and local .same issue is getting

**Comment by lvca** [comment]
That os graph? Please can you provide the relevant code that does this insertion in transaction?

**Comment by eswaras** [comment]
Please find the below code

OrientGraphFactory factory = new OrientGraphFactory("remote:172.31.66.190/2480/ORDBS", "", "");
		OrientGraph graph = factory.getTx();
			
		try {
			
		String query1 = "INSERT INTO delears (Name,ID,Address) VALUES ('eswarareddy',21,'kadapa')";
		graph.command(new OCommandSQL(query1).execute());
		graph.commit();
		graph.shutdown();
		

	}
		catch(Exception e){
			System.out.println(e);
			graph.rollback();
		}
		finally {
			graph.shutdown();
		}

**Comment by lvca** [comment]
Ok, with plocal you're in the TX scope, while with remote the SQL commands are executed in the server, so out of TX scope (http://orientdb.com/docs/last/Transactions.html#breaking-of-acid-properties-when-using-remote-protocol-and-commands-sql-gremlin-js-etc)

**Comment by lvca** [comment]
This is resolved with OrientDB v3.0.
