### ISSUE TITLE
OrientDB – Graph Visualization related questions?

### ISSUE THREAD

**Issue by rladha** [orientechnologies/orientdb#6098]
OrientDB Version: 2.2.0-beta2

Hello Everyone,

Use case we are working on, is giving user access to Graph Visualization and hide the complexity of the query via Javascript function. Ex:

SQL: SELECT FROM COUNTRY WHERE NAME=’CANADA’
Function: SELECT findCountry(‘CANADA’)
Now, users are asking questions if there is a way to adjust the look n feel of the graph visualization.

I am looking for your suggestions as an advice or point to some kind of document?
1. Most of our data is in hierarchy format – Is it possible instead of circles, we display data in org-chart format or pure right to left?
2. Also, instead of circle can we use another other shape? i.e. rectangle or triangle? Depend on the class.
3. Possible to word-wrap the label in the circle?
4. Possible to show multiple properties in the circle? i.e. ID + Name
5. Possible to change the Stroke colour based on the property in the class ex: If the City is also the capital then can the stroke color to RED and size to 5 but keep the fill color same as other cities?
6. Any way to undo on the Graph tool? Ex: if we are doing drill down from 1 > 2 > 3 > 4 and undo 4 and back to number 3?

Really appreciate your thoughts.

regards

**Comment by luigidellaquila** [comment]
Hi @rladha 

Unfortunately the answer is no for all the questions, Studio Graph visualization is a very basic tool and provides only simple interactions. Anyway, the project is FOSS (source here https://github.com/orientechnologies/orientdb-studio) and the graph view is a plain D3 view, so if you need to expand it with custom functionalities you can start from there. Of course any pull request will be very appreciated and we will be happy to help you if you need hints.

In the meantime, I'm flagging this issue as an enhancement, maybe these things will be implemented in next releases.

Thanks

Luigi

**Comment by rladha** [comment]
Thanks Luigi! 

Will you be able to give a quick jump start with as to which file shall I make changes too or create a wrapper around it or to some examples? I am not expert in Javascript but can navigate myself without any issue.

Thanks!

**Comment by rladha** [comment]
Hello Maggiolo00,

I am looking for some hint to modify the UI - any guidance will be really appreciated!

Thanks

Rahim
