### ISSUE TITLE
very slow SELECT when vertex include quite populated embedded set

### ISSUE THREAD

**Issue by karel-un** [orientechnologies/orientdb#6101]
System: OrientDB v 2.1.16, Python 3.4, pyorient, Gentoo kernel 4.5.1, i5-6400, 16GB RAM, 2TB HDD

Consider class with one embeddedset property:

CREATE VERTEX TestClass
CREATE PROPERTY TestClass.Name string
CREATE INDEX TestClass.Name unique
CREATE PROPERTY numbers embeddedset integer

When creating new vertex of TestClass, numbers are populated by 65000 items (say 1..65000). Then after I do simple select from TestClass by name:

SELECT FROM TestClass WHERE Name = 'somename'

query takes about 1.7 seconds to complete, which is extremly slow. But when I exclude embedded set from result:

SELECT expand(@this.exclude('numbers')) FROM TestClass WHERE Name = 'somename'

query takes about 0.01 seconds, which looks ok.

Is there any reason, why is simple select returning vertex with populate embeddedset soo slow ?

**Comment by luigidellaquila** [comment]
Hi @karel-un 

It seems to be a problem of record encoding/decoding. Could you please try to execute the same query on OrientDB Studio with an EXPLAIN? It will give you information about OrientDB internal performance for that query

Thanks

Luigi

**Comment by karel-un** [comment]
Hi @luigidellaquila 

From console everything looks fine, but exactly the same ```SELECT FROM TestClass WHERE name = 'somename'``` via pyorient is slow. ```EXPLAIN``` doesnt get through pyorient, so I cant provide pyorient ```EXPLAIN``` result here. On [pyorient page](https://github.com/mogui/pyorient) there is mentioned that pyorient uses OrientDB binary protocol. Could this be a problem or should I repost issue on pyorient project ?

Thanks

Karel

```
orientdb {db=test}> select from TestClass where name = 'somename'                                 

----+-----+---------+--------+-------
#   |@RID |@CLASS   |name    |numbers
----+-----+---------+--------+-------
0   |#11:0|TestClass|somename|[64999]
----+-----+---------+--------+-------

1 item(s) found. Query executed in 0.004 sec(s).
orientdb {db=test}> select expand(@this.exclude('numbers')) from TestClass where name = 'somename'

----+-----+---------+--------
#   |@RID |@CLASS   |name    
----+-----+---------+--------
0   |#11:0|TestClass|somename
----+-----+---------+--------

1 item(s) found. Query executed in 0.014 sec(s).
orientdb {db=test}> select expand(@this) from TestClass where name = 'somename'                   

----+-----+---------+--------+-------
#   |@RID |@CLASS   |name    |numbers
----+-----+---------+--------+-------
0   |#11:0|TestClass|somename|[64999]
----+-----+---------+--------+-------

1 item(s) found. Query executed in 0.012 sec(s).
orientdb {db=test}> explain select from TestClass where name = 'somename'

Profiled command '{documentReads:1,fullySortedByIndex:false,compositeIndexUsed:1,current:#11:0,documentAnalyzedCompatibleClass:1,recordReads:1,involvedIndexes:[1],limit:-1,fetchingFromTargetElapsed:0,indexIsUsedInOrderBy:false,evaluated:1,elapsed:1.294433,resultType:collection,resultSize:1}' in 0,003000 sec(s):
{"@type":"d","@version":0,"documentReads":1,"fullySortedByIndex":false,"compositeIndexUsed":1,"current":"#11:0","documentAnalyzedCompatibleClass":1,"recordReads":1,"involvedIndexes":["TestClass.name"],"limit":-1,"fetchingFromTargetElapsed":0,"indexIsUsedInOrderBy":false,"evaluated":1,"elapsed":1.294433,"resultType":"collection","resultSize":1,"@fieldTypes":"documentReads=l,compositeIndexUsed=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,involvedIndexes=e,fetchingFromTargetElapsed=l,evaluated=l,elapsed=f"}
```

**Comment by luigidellaquila** [comment]
Hi @karel-un 

Yes, both pyorient and the console use the binary protocol, so the problem is not there. The only difference here is on the driver, so I suspect the problem is there

Thanks

Luigi

**Comment by karel-un** [comment]
Issue moved to pyorient:

[https://github.com/mogui/pyorient/issues/191](https://github.com/mogui/pyorient/issues/191)

Thanks for help

Karel
