### ISSUE TITLE
Distributed: support configurable higher level of isolation

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6102]
Today while a transaction runs distributed, there could be dirty reads during the propagation of a transaction commit or rollback. It would be nice having a configurable setting to avoid this making all the reads perfectly consistent.

**Comment by Eric24** [comment]
Just a quick note: I'm not sure exactly what you have in mind, but it would be ideal if this setting could be selected on a per-connection or per-request basis. If that's not easily done for this time around, at least a per-database or per-class basis would be better than a global setting.

PS - In my particular case, the client is orientjs.
