### ISSUE TITLE
Performance bottleneck when migrating large (in million) number of records into fresh installation of orientdb

### ISSUE THREAD

**Issue by nsitanurag** [orientechnologies/orientdb#6103]
I am getting serious performance issues when migrating large number of nodes along with edges from another database (cassandra in my case) to orientdb.

Till 80 Mn of nodes and 100 MN of edges, speed was quite good at 1million per hour but now it has reduced drastically to 1 million in 16 hour. What can be the issue?

I am using standalone instance of orientdb with tomcat in embedded mode and doing noTX mode document level api inserts using OMassiveInsert intent.

**Comment by lvca** [comment]
How do you manage edges with document APIs? Do you have lightweight edges only? Do you have any index? If yes, how many properties are indexed and what kind of index? Please give us more information about your use case.

**Comment by laa** [comment]
HI that will be fixed in 3.0 by providing new data structures for big data support.

**Comment by nsitanurag** [comment]
Hi Ivca,

I don't have lightweight edges. My edge has both in and out link. Yes I have one index each for node and edge. Node index is on primarykey unque_hash_index and edge index is on out,in unique. Please let me know if any more info is required?

**Comment by nsitanurag** [comment]
@lvca , waiting for your reply.

**Comment by nsitanurag** [comment]
After using SBTREE index as well, performance is still as bad as it was earlier.

Performance Statistics   2016-05-10 08:42:00 - 2016-05-10 08:43:00
Tag                                                  Avg(ms)         Min         Max     Std Dev       Count
insert.contact                                         607.0           0       12164      1286.1        7430
load.contact                                            39.0           0        2358       105.0        2424
read.contact.by.index                              232.9           0       11904       818.5       10327
save.contact                                            29.8           0       11022       224.2        9889

**Comment by lvca** [comment]
Could you please post the responsible of the slow operation that caused the "read.contact.by.index" stats to be 232.9 as average?

**Comment by nsitanurag** [comment]
Followed up on mail. There was some issue with how I was initializing the embedded server. Hence, closing this bug.
