### ISSUE TITLE
Read performance of SELECT query is very slow when retrieving vertices from remote database (OrientDB 2.1.4)

### ISSUE THREAD

**Issue by natemurthy** [orientechnologies/orientdb#6109]
I have a very small instance of OrientDB running on an EC2 t2.medium in the us-west-2b region/zone. The database has only 1853 vertices and 529 edges. Of those vertices, I have 1712 of a particular class which make up a good majority of the records in the database. Here's what the schema of this vertex class looks like:

```
CREATE CLASS EventRecord EXTENDS V;
CREATE PROPERTY EventRecord.event_id STRING;
CREATE PROPERTY EventRecord.as_json STRING;
CREATE PROPERTY EventRecord.datetime_start_utc DATETIME;
CREATE PROPERTY EventRecord.datetime_end_utc DATETIME;
CREATE INDEX EventRecord.event_id UNIQUE;
CREATE INDEX EventRecord.datetime_start_utc NOTUNIQUE;
CREATE INDEX EventRecord.datetime_end_utc NOTUNIQUE;
```

The indexes are created using the SBTREE engine. Now when I try to fetch the 1712 records from OrientDB using this query:

```
orientdb {db=mydatabase}> SELECT * FROM EventRecord limit LIMIT 2000
...
1712 item(s) found. Query executed in 5.168 sec(s)
```

It takes anywhere from 4-10 seconds to complete and return a result set. When I place the EXPLAIN command in front of my query I see:

```
orientdb {db=mydatabase}> EXPLAIN SELECT * FROM EventRecord LIMIT 2000

Profiled command '{documentReads:1712,current:#32:2348,documentAnalyzedCompatibleClass:1712,recordReads:1712,fetchingFromTargetElapsed:14,evaluated:1712,elapsed:13.639927,resultType:collection,resultSize:1712}' in 0.070000 sec(s):
{
    "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,evaluated=l,elapsed=f",
    "@type": "d",
    "@version": 0,
    "current": "#32:2348",
    "documentAnalyzedCompatibleClass": 1712,
    "documentReads": 1712,
    "elapsed": 13.639927,
    "evaluated": 1712,
    "fetchingFromTargetElapsed": 14,
    "recordReads": 1712,
    "resultSize": 1712,
    "resultType": "collection"
}
```

The profiled `elapsed` time of `13.639927` is particularly worrisome and is cause of concern. I've seen this vary at different times from 9-15 seconds. We normally see speeds that our 100x faster on our single-instance RDBMS servers running on the same EC2 instance. What's going on here? Is there something on the database that we need to tune in order to achieve faster read performance?

In regards to slow query times, I've found some other issues that are still open that may be related to what I'm observing:
https://github.com/orientechnologies/orientdb/issues/3041
https://github.com/orientechnologies/orientdb/issues/3059
https://github.com/orientechnologies/orientdb/issues/3470
https://github.com/orientechnologies/orientdb/issues/5609
https://github.com/orientechnologies/orientdb/issues/6101

**Comment by natemurthy** [comment]
Quick followup:

My ops team and I saw OrientDB take up significant CPU load on our machine:

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
17892 db      20   0 3007244 767820   6272 S 124.2 19.0   6866:32 java

$ ps ax | grep orientdb
17892 java /opt/dgms/orientdb-community-2.1.4/lib/orientdb-server-2.1.4.jar
```

We restart the OrientDB JVM process and are now seeing retrieval times about half of what I reported above. This is an improvement, but still unacceptable for our perf requirements.

**Comment by lvca** [comment]
Could you please try with 2.2.0-rc1 if you have the same time?

**Comment by laa** [comment]
@natemurthy could you try the same query for embedded database , what are results ?

**Comment by natemurthy** [comment]
@lvca Per the recommendation of our Ops team, we upgraded our remote OrientDB server to 2.1.16 -- the latest stable release for production (instead of 2.2.0-rc1). Here's what we see now (with a few more records that were added over night):
```
select * from EventRecord limit 2000
...
Query executed in 5.19 sec. Returned 1806 record(s)
```
And the profiler shows:
```
Profiled command '{documentReads:1806,current:#32:2452,documentAnalyzedCompatibleClass:1806,recordReads:1806,fetchingFromTargetElapsed:23, 
evaluated:1806,elapsed:23.711111,resultType:collection,resultSize:1806}' in 0.077000 sec(s):                                               
{
    "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,evaluated=l,elapsed=f",
    "@type": "d",
    "@version": 0,
    "current": "#32:2452",
    "documentAnalyzedCompatibleClass": 1806,
    "documentReads": 1806,
    "elapsed": 23.711111,
    "evaluated": 1806,
    "fetchingFromTargetElapsed": 23,
    "recordReads": 1806,
    "resultSize": 1806,
    "resultType": "collection"
}
Which is still unacceptable from out point of view. Perhaps there are some parameters we need to tune or configure on our OrientDB server?

```
@laa It would be bit a of a stretch for us to try this out in an embedded database. Let me try to refactor some things and see if I can benchmark this. We do have a significant amount of business logic that calls OrientDB (e.g. via javascript Functions in the OrientDB server and HTTP API) in a remote fashion, so I may need to get a few folks on my team coordinated to try refactoring these APIs around a service that runs OrientDB in an embedded fashion.

**Comment by natemurthy** [comment]
@lvca @laa Do you observe this slowness in the enterprise edition? Is this a limitation of the community edition server?

**Comment by laa** [comment]
Hi , 

I am on vacation  now so @taburet is responsible for this issue .
I would propose to collect following  information :
1. Statistic of memory usage for orientdb server , swap and RAM.
2. Profiling of orientdb server using any profiler which you have jmc (java mission control) for example. It is free and supports console mode .
3. Statistic of disc usage .
4. Statistic of disk cache usage.

@taburet will reach you out and provide more detailed information once he will have available time slot .
Meanwhile could you provide information about version of OS which you use.

**Comment by natemurthy** [comment]
@taburet Working with my ops guy to get those data. We're using Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64). OrientDB on this machine is configured with:
`OrientDB auto-config DISKCACHE=1,024MB (heap=880MB os=3,952MB disk=12,677MB)`

**Comment by taburet** [comment]
Actually the `elapsed` and `fetchingFromTargetElapsed` are measured in milliseconds, not seconds. Query time of 14ms is quite acceptable, on my machine it also takes about 15ms to fetch 2000 records from local database. So the rest is networking/serializing/deserializing time.

Please try to run the same queries directly on the server machine, using the `remote:` connection from the OrientDB console running on the server. If this will show query execution time comparable to the results above, that is definitely a problem on OrientDB side. If timing improves that is networking/connectivity issue on unknown side :)

**Comment by natemurthy** [comment]
@taburet Ok gotcha. I'll try running these queries locally on the server machine and see what performance I get.

**Comment by natemurthy** [comment]
@taburet Here's what I see when I directly query the records on the machine running our OrientDB server:
```
orientdb {db=mydatabase}> select * from EventRecord limit 2000
...
1802 item(s) found. Query executed in 0.281 sec(s).
```
Observed slowness must certainly be a result of serializing this large result set over our networks.
