### ISSUE TITLE
OrientDB UI Issue - public jira for orientDB to report OrientDB issue

### ISSUE THREAD

**Issue by Manjiri0410** [orientechnologies/orientdb#6110]
When query is submitted to retrieve link results, some vertices are displayed with solid color and border. But few vertices are displayed with washed color and dashed border. The washed color gets changed to solid color after a click on that bubble. 

Is there any way to get all bubbles with solid color and border? Below is the image attached for reference. The version of OrientDB used is 2.1.

![vertice formatting](https://cloud.githubusercontent.com/assets/19280129/15137835/ae133aac-16a9-11e6-8139-54e0c374aae4.png)

**Comment by Manjiri0410** [comment]
Hi, Any updates on this?

**Comment by Manjiri0410** [comment]
What is the meaning of Question label? Do you need any more information / details?

**Comment by maggiolo00** [comment]
@Manjiri0410 

that means that the vertex is not loaded yet. But studio holds  only the @rid
