### ISSUE TITLE
OrientDB - Corrupt display after continuous use of OrientDB Studio.

### ISSUE THREAD

**Issue by Manjiri0410** [orientechnologies/orientdb#6111]
After using OrientDB Studio for more than 15 mins, the UI starts behaving weird. Few of the vertices get disappeared from the graph. This behavior is not predictable always. But it is observed that it normally happens after continuous use of the OrientDB Studio. The version of studio used is 2.1. The images are attached below to explain the issue.

![orientdb ui issue](https://cloud.githubusercontent.com/assets/19280129/15138159/b3e957de-16ab-11e6-906e-61b48a6fbeaf.png)

**Comment by maggiolo00** [comment]
How can i reproduce this?

**Comment by Manjiri0410** [comment]
We encountered if when we used it continuously for half an hour. This cannot be consistently reproduced. Please try using studio continuously and it might get reproduced.

**Comment by maggiolo00** [comment]
hi @Manjiri0410 

i will try to replicate it

**Comment by Manjiri0410** [comment]
Thanks.

**Comment by maggiolo00** [comment]
@Manjiri0410 

what happen if you clear the canvas?

**Comment by maggiolo00** [comment]
@Manjiri0410 

can you try with 2.2.10?

From 2.2.8 the graph editor has been improved a lot. 
I think it will fix this. Please re-open if you still experience this.
