### ISSUE TITLE
OrientDB - UI Issue - Properties layer on the left hand side is not scrollable

### ISSUE THREAD

**Issue by Manjiri0410** [orientechnologies/orientdb#6112]
It is observed that the properties layer on the left hand side does not scroll if there are more number of properties. Hence user cannot see more than a certain number of properties even if they exist as they are out of the page view. Also the text displayed in the property-value pairs is not wrapped, thus making it difficult to read.

**Comment by Manjiri0410** [comment]
When is 2.2.1 planned for release?

**Comment by maggiolo00** [comment]
hi @Manjiri0410 

actually we can solve this soon in 2.1.x and 2.2.x

**Comment by Manjiri0410** [comment]
Thanks for this. I can get to know the ETA?

**Comment by maggiolo00** [comment]
hi @Manjiri0410 
this has been fixed in develop branch of orientdb-studio. It will be available in 2.2.1 that will be released the next week
