### ISSUE TITLE
How to change distributed node roles online

### ISSUE THREAD

**Issue by mamoit** [orientechnologies/orientdb#6113]
Running version `2.2.0-rc1`.
How can I change a node's role online? i.e. from master to replica.
I can change the distributed-config.json in one node but it does not replicate to the others.
Ideally I would like to have something like:
```json
(...)
servers": {
    "master-*": "master"
    "replica-*": "replica"
}
(...)
```
but the servers entry does not accept regexes.

**Comment by mamoit** [comment]
After opening this issue I noticed that in the enterprise edition of OrientDB there is the option to change the role of a node online (through the WebUI).
But there is no enterprise edition of `2.2.0-rc1` available for testing, and the `enterprise/build.xml` is not present in the respective tag.
Will there be one?

**Comment by lvca** [comment]
This is supported in Enterprise Edition that will be out for 2.2.0 GA. In Community Edition you cannot change the role at runtime, but you have to restart the entire cluster.

**Comment by mamoit** [comment]
Thanks for the information.
Looking forward to try out 2.2.0 GA.
Will keep in touch about the E.E. :smile:
