### ISSUE TITLE
Database Alias to point to database (and make possible to point to other when it is updated).

### ISSUE THREAD

**Issue by pabloa** [orientechnologies/orientdb#6115]
I have a batch import that uses the existing database. BUT if the schema changed, I want to rename the new database, create a new one and proceed with the data import.

I believe it would be helpful to use a database alias (like a soft link) pointing to a database. By using some SQL command like ALTER DATABASE ALIAS my_alias_db TO my_new_db user should be able to point the alias to other database.

Existing connections will still point to the previous db but when new connections using the alias arrives they will use the new db.

**Comment by rdelangh** [comment]
@lvca , @pabloa 
hello Luca, I am also very interested in this feature (rename of a database); is this somewhere in the pipeline of an upcoming release?
