### ISSUE TITLE
Etl programs are not working for document databases.

### ISSUE THREAD

**Issue by lucevers** [orientechnologies/orientdb#6117]
The Error message is only generated if a document database is used!
  

Error MSG:
"Cannot check the existence of a remote server database. Please use the console or the OServerAdmin class."

To allow multiple access to the same database , then use Remote Mode!
But if Remote Mode is used then the Error MSG above is the problem!

Info and tests:
-------------------
https://groups.google.com/forum/#!topic/orient-database/JHjCL7grdRk

**Comment by robfrank** [comment]
The ETL tool is unable to check the existence of a db in remote mode. 
What you can do? Create the db on the remote server, for example using studio (the web console) on http://localhost:2480. To create a new DB you need to provide "root" credentials (server administration credentials). After that, put to false the property:  "dbAutoCreate": true.
Should be enough.

**Comment by lucevers** [comment]
No the same Error:
    Cannot check the **existance **of a database in a remote server!
    
    
I'm using 2 server (distributed config)

{
  "config":{ "log": "debug" },
  "source": { "file": { "path": "./test.csv" } },
  "extractor": { "csv": {} },
  "loader": {
    "orientdb": {
       "dbURL": "remote:195.13.20.204/pops admin admin",
       "dbType": "document",
       "class": "test",
       "dbAutoCreate": false,
       "classes": [{"name": "test"}],
       "indexes": [{"class":"test", "fields":["zip:STRING"], "type":"NOTUNIQUE" }]
    }
  }
}

Database test and class test were configured with studio, like all the tests.
It seems that de program cannot check the configured databases.

**Comment by robfrank** [comment]
there's still an error on the url, since user and password should be configured as json props:

```
....
"dbURL": "remote:195.13.20.204/pops",
      "dbUser": "admin",
      "dbPassword": "admin",
....
```

**Comment by robfrank** [comment]
hi, I added the capability to manage remote databases on develop branch, it will be part of 2.2.0.  documentation for the loader will be updated in a couple of hour: http://orientdb.com/docs/last/Loader.html#orientdb-loader

The same for snapshots distribution packages: https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.0-SNAPSHOT/

**Comment by lucevers** [comment]
After changing the usernam/password, I still have the same problem:

{
  "config":{ "log": "debug" },
  "source": { "file": { "path": "./nps2.csv" } },
  "extractor": { "row": {} },
  "loader": {
    "orientdb": {
       "dbURL": "remote:195.13.20.204/pops",
       "dbUser": "admin",
      "dbPassword": "admin",
       "dbType": "document",
       "class": "nps",
       "dbAutoCreate": false,
       "classes": [{"name": "nps"}]
    }
  }
}

Caused by: java.lang.UnsupportedOperationException: Cannot check the existance of a database in a remote server. Please use the console or the OServerAdmin class
