### ISSUE TITLE
.

### ISSUE THREAD

**Issue by lucevers** [orientechnologies/orientdb#6118]

**Comment by maggiolo00** [comment]
hi @lucevers 

can you explain this issue?

**Comment by smolinari** [comment]
I would have just closed it. Or asked for him to follow the contribution rules. You guys are way too nice. LOL! :smile: 

Scott

**Comment by luigidellaquila** [comment]
@smolinari we always try to be  ;-)

Luigi

**Comment by smolinari** [comment]
@luigidellaquila - Yes. I know. And actually appreciate it myself too! :smile: 

Scott
