### ISSUE TITLE
Links that was created by 'create link' not updateable

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#6123]
1) OrientDB release: 2.2.0.-rc1
2) Steps:
Domain has two entities "Customer" and "Address". Entity "Customer" has property "addresses" that contains links to customer's addresses. I create the  property by command:
CREATE LINK addresses TYPE LINKSET FROM Address.customer_bk TO Customer.bk INVERSE.
The command create property "addresses" with correct link.
After it, I create new Address with same value of property "customer_bk".  In theory, value of property "addresses" must contains two links. But ... value not changed.

3) default setting
4) expected behavior: After insert new "Address" with same value of "customer_bk", Link would be updated

**Comment by smolinari** [comment]
Can you follow the issue reporting rules please? 

http://orientdb.com/docs/last/Report-an-issue.html

Scott

**Comment by schernolyas** [comment]
updated

**Comment by smolinari** [comment]
This might interest you. 

https://groups.google.com/forum/#!msg/orient-database/GTzHlEVrrcM/xuPCf2d7BwAJ

In other words, it is up to you to make sure any links are set properly. Links are also only unidirectional. 

It seems you want an n:n relationship between Addresses and Customers. In this situation, you are probably better off just creating embedded relationships. It isn't often that customers share addresses. 

Or, use edges. ODB takes care of edge (referential) integrity only.

Scott

**Comment by schernolyas** [comment]
Hi @smolinari 

I think  that using edges for create link between vertexes is more preferable in common case.

Thank You for advice!
