### ISSUE TITLE
Error in LiveQuery for clusters

### ISSUE THREAD

**Issue by vitalytravin** [orientechnologies/orientdb#6124]
I use LiveQery for select cluster (live select from cluster:Cluster1), but an error in Exception in thread "LiveQueryQueueThread" java.lang.IllegalStateException: Current database instance (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@1afaccf7) is not active on current thread
I watched OCommandExecutorSQLLiveSelect:
public void onLiveResult(final ORecordOperation iOp) {

    final OIdentifiable value = iOp.getRecord();

    if (!matchesTarget(value)) { 
      return;
    }
    if (!matchesFilters(value)) {
      return;
    }
    if (!checkSecurity(value)) {
      return;
    }
    
    final OCommandResultListener listener = request.getResultListener();
    if (listener instanceof OLiveResultListener) {
      execInSeparateDatabase(new OCallable() {
        @Override
        public Object call(Object iArgument) {
          execDb.activateOnCurrentThread();
          ((OLiveResultListener) listener).onLiveResult(token, iOp);
          return null;
        }
      });
    }
  }

if (!matchesTarget(value)) - **It requires the installation of an activateOnCurrentThread() (for execDb.getClusterNameById(value.getIdentity().getClusterId())**, **But this is below** -

 public Object call(Object iArgument) {
          execDb.activateOnCurrentThread();
          ((OLiveResultListener) listener).onLiveResult(token, iOp);
          return null;
        }

**Comment by luigidellaquila** [comment]
Hi @vitalytravin 

Which OrientDB version are you using?

Thanks

Luigi

**Comment by vitalytravin** [comment]
Hi luigidellaquila

2.1.15

**Comment by vitalytravin** [comment]
Error in OCommandExecutorSQLLiveSelect

if (this.parsedTarget.getTargetClusters() != null) {
      final String clusterName = execDb.getClusterNameById(value.getIdentity().getClusterId());**<- always returns lowerCase**
      if (clusterName != null) {
        for (String cluster : parsedTarget.getTargetClusters().keySet()) {;**<- always returns UpperCase**
          if (clusterName.equals(cluster)) {**<- always returns false**
            return true;
          }
        }
      }
    }

**Comment by luigidellaquila** [comment]
Hi @vitalytravin 

Thank you for the accurate pointer, I'm fixing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed on both 2.1.x (next 2.1.8) and 2.2 (next 2.2 GA) 

Thanks

Luigi
