### ISSUE TITLE
Fix to the Scheduler to get it working with the new CronExpression module

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6125]
We have a scheduler that has been donated by the community but it's not working and the code is not compliant with last OrientDB changes. This makes it unusable. 

We have to work on it to make it working and tested.

**Comment by lvca** [comment]
It's still missing the documentation.

**Comment by PhantomYdn** [comment]
@lvca I have few questions regarding you implementation:

1) Am I right that it will support cluster?
2) Why are you decided to use your own implementation? There are several implementation of schedulers. But btw I do recommend to take a look on Cron4J
3) Am I right that it will be possible to schedule task by creation corresponding ODocument and not going through API?
4) Will implementation have support of progress status and probably messages from a task? It's especially interesting for long running taks.

**Comment by lvca** [comment]
1) yes, it already in HA
2) I didn't write it, I used the Lucene one (Apache2, no deps). Cron4J is not Apache2 and hence removed from the code base long time ago
3) yes, thanks to the OSchedulerTrigger
4) no progress for now, but it will support logging in the new OSystem database (the server's database introduced in v2.2)

**Comment by lvca** [comment]
Documentation updated.
