### ISSUE TITLE
Database became corrupted if there is no space to keep database journal on disk

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#6127]
Related exception is - ERROR [ODiskWriteAheadLog$LogSegment$FlushTask] Error during WAL background flush java.io.IOException: No space left on device at java.io.RandomAccessFile.writeBytes(Native Method) ~[na:1.8.0_45] at java.io.RandomAccessFile.write(RandomAccessFile.java:512) ~[na:1.8.0_45] at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment$FlushTask.flushPage(ODiskWriteAheadLog.java:232)

**Comment by taburet** [comment]
Fixed on 2.1.x and develop branches. Added a check for low disk space after a WAL flush and on WAL initialization.
