### ISSUE TITLE
Error in executing a query about 'Traverse' statement by JDBC 

### ISSUE THREAD

**Issue by gyfrozen** [orientechnologies/orientdb#6128]
Version of orientdb-jdbc : 2.0.4 & 2.1.16

when I execute the code below:
`ResultSet rs = statement.executeQuery("traverse OUT('someR') from (select from tableA where xxid = 'xxxxx') WHILE $depth <= 1");`
Two documents are expected to be returned to me. However, the returned result set contains 2 rows, one of which is an object of ODocument, and the other is an object of ORecordId which just contains '@rid'. What's more, it will cause a ClassCastException when using rs.next() to move the cursor forward the second row because com.orientechnologies.orient.core.id.ORecordId cannot be cast to com.orientechnologies.orient.core.record.impl.ODocument.

**Comment by lvca** [comment]
The query is not correct: you should use EXPAND:

```java
ResultSet rs = statement.executeQuery("traverse expand( OUT('someR') ) from (select from tableA where xxid = 'xxxxx') WHILE $depth <= 1");
```
