### ISSUE TITLE
Datetime/date problems when a subclass redefine a field

### ISSUE THREAD

**Issue by voondo** [orientechnologies/orientdb#6132]
(commit c5a54b0fd80f9c2ef8ae79a51b3c470182e68a67 branch develop)

Not a big issue but I spent two hours to struggle with it : if you have two classes defining each a field with the same name (e.g.  'created_at'), the first of type `Datetime` and the second of type `Date` whose the class inherits the first you will have a weird behavior and only when using a tx graph (expected behavior with a non tx graph): 

Class A : `[created_at (type=DATETIME)]`
Class B superclass A : `[created_at (type=DATE)]`

```
OrientGraph> vertex_b.record.toJSON
=> "{"@type":"d","@rid":"#45:0","@version":1,"@class":"B","created_at":"2016-05-13 00:00:00","_allow":["#5:0"],"_allowRead":["#5:3","#4:2"],"_allowUpdate":["#4:2"],"@fieldTypes":"created_at=t,_allow=n,_allowRead=n,_allowUpdate=n"}"
OrientGraph>)> commit
=> nil
OrientGraph>)> vertex_b.record.reload.toJSON
=> "{"@type":"d","@rid":"#45:0","@version":2,"@class":"B","created_at":"1970-01-01 00:00:16","_allow":["#5:0"],"_allowRead":["#5:3","#4:2"],"_allowUpdate":["#4:2"],"@fieldTypes":"created_at=t,_allow=n,_allowRead=n,_allowUpdate=n"}"
```

Note the 1970-01-01 00:00:16 (!)

**Comment by maggiolo00** [comment]
hi @voondo 

how do you create vertexes? Which api do you use?

**Comment by luigidellaquila** [comment]
IMHO this should not be allowed, a property can have only one type in the class hierarchy, if a property is of type X in the superclass, it has to be of type X also in the subclasses and if you try to change it on a subclass, the system should throw an exception

**Comment by voondo** [comment]
@maggiolo00 I use the Java API
@luigidellaquila I agree, it was a mistake from my side but It was hard to debug with the current behavior.

**Comment by tglman** [comment]
Hi @voondo,

there are check that not allow to create two times a property with the same name and different type in the hiearchy, which version do you use and from which api did you create the property ?

Regards

**Comment by tglman** [comment]
Hi @voondo,

there are check that not allow to create two times a property with the same name and different type in the hiearchy, which version do you use and from which api did you create the property ?

Regards

**Comment by voondo** [comment]
Hi @tglman, I use the current develop branch with the Graph Java API (i.e `OrientVertexType.createProperty`)
