### ISSUE TITLE
Etl programs are not working for document databases.

### ISSUE THREAD

**Issue by lucevers** [orientechnologies/orientdb#6134]
Cannot check the *existance *of a database in a remote server!

I'm using 2 server (distributed config)

{
"config":{ "log": "debug" },
"source": { "file": { "path": "./test.csv" } },
"extractor": { "csv": {} },
"loader": {
"orientdb": {
"dbURL": "remote:195.13.20.204/pops admin admin",
"dbType": "document",
"class": "test",
"dbAutoCreate": false,
"classes": [{"name": "test"}],
"indexes": [{"class":"test", "fields":["zip:STRING"], "type":"NOTUNIQUE" }]
}
}
}

Database test and class test were configured with studio, like all the tests.
It seems that de program cannot check the configured databases.

there's still an error on the url, since user and password should be configured as json props:

....
"dbURL": "remote:195.13.20.204/pops",
      "dbUser": "admin",
      "dbPassword": "admin",
....

After changing the usernam/password, I still have the same problem:

{
"config":{ "log": "debug" },
"source": { "file": { "path": "./nps2.csv" } },
"extractor": { "row": {} },
"loader": {
"orientdb": {
"dbURL": "remote:195.13.20.204/pops",
"dbUser": "admin",
"dbPassword": "admin",
"dbType": "document",
"class": "nps",
"dbAutoCreate": false,
"classes": [{"name": "nps"}]
}
}
}

Caused by: java.lang.UnsupportedOperationException: Cannot check the existance of a database in a remote server. Please use the console or the OServerAdmin class.

**Comment by robfrank** [comment]
Which version are you using? On 2.2.x I've implemented the check and create even for remote db.

**Comment by lucevers** [comment]
Version:
orientdb-community-2.1.16

**Comment by lucevers** [comment]
Installed new Orientdb version 2.2.0

Now I have another problem: Unable to manage remote db without server admin credentials.
See also #6164

**Comment by robfrank** [comment]
To create a new db on a remote orient it is supposed to use the server admin credentials. There's not other way. If the database is present, you don't need them and ETL works fine.

**Comment by lucevers** [comment]
Does this means that I don't need to send:

"dbUser": "admin",
"dbPassword": "admin"

?

**Comment by lucevers** [comment]
So In my case the database + the class is already present.The ETL tool only needs to load the data.

**Comment by lucevers** [comment]
Did some made a sample test with ETL and a document database?

**Comment by robfrank** [comment]
I think you are missing a the csv extractor.
ETL  doc: http://orientdb.com/docs/last/ETL-Introduction.html
CSV: http://orientdb.com/docs/last/Extractor.html#csv-extractor
Some examples: http://orientdb.com/docs/last/Import-from-CSV-to-a-Graph.html

**Comment by Alexettels** [comment]
Hi, How was this resolved? I'm getting an error message saying : 
`unable to manage remote db without server admin credentials`

**Comment by robfrank** [comment]
You need to provide the server's  user name and password:

http://orientdb.com/docs/last/Loader.html#orientdb-loader
