### ISSUE TITLE
Query returns old copy of data (v2.1.12)

### ISSUE THREAD

**Issue by vlasni** [orientechnologies/orientdb#6135]
Using community edition v2.1.12 and experiencing caching issues. 
While adding NOCACHE to SQL statements fixes some cases, since we are using graph api I don't see how can I set something like NOCACHE when doing i.e. vertex.getEdges(....). 
Any help?

Update:
The workaround I've found so far is to do:
`graphDb.getRawGraph().getLocalCache().invalidate();` whenever I need to get a connection to DB.

Is this the correct practice?

**Comment by maggiolo00** [comment]
Hi @vlasni 
Do you use plocal or remote connection?

**Comment by vlasni** [comment]
Hi Enrico,
I use remote connection as follows:
`
		graphFactory = new OrientGraphFactory(dbUrl, dbUser, dbPassword).setupPool(dbMinPool, dbMaxPool);
		graphDb = graphFactory.getTx();
`
dbUrl has the value set as: remote:server/dbName

Thanks

**Comment by lvca** [comment]
Working in remote you could have old data on the client. You could force the reloading of the vertex (and therefore its edges) with:

    vertex.reload();

**Comment by vlasni** [comment]
Hi Luca,
So, if I understand correctly, the advice is to always perform `vertex.reload()` when working in remote?
Will give it a try and post the updates.

Thanks

**Comment by lvca** [comment]
If you need to have last updated data, yes. Instead with updates, you could execute the update, and in case your version is old, you get a OConcurrentModificationException to manage avoiding to call .reload() everytime.

**Comment by vlasni** [comment]
I may be wrong, but it looks like I shouldn't have old data in my scenario:

```
	public final List<Vertex> findAllVertices() throws ModelHelperWithoutDbException {
		List<Vertex> result = new ArrayList<Vertex>();
		
		StringBuilder sb = new StringBuilder();
		sb.append("select from ");
		sb.append(type.getSimpleName());
		sb.append(" where deleted=false");
		sb.append(" NOCACHE");

		Iterable<Vertex> it = getDB().command(new OCommandSQL(sb.toString())).execute();
		if (it.iterator().hasNext()) {
			for (Vertex vertex : it) {
			       //the line below is the one I've just added as suggested
				((OrientVertex)vertex).reload();
				result.add(vertex);
			}
		}

		return result;
	}

```

I understand that since I've just queried DB with NOCACHE, then vertices should all contain fresh data. Or am I missing something?

**Comment by lvca** [comment]
You're right with plocal connection, but with remote the SQL is interpreted in the server, so that statement will not use the server cache, but you could have something cached at the client side (we have 2 caches). So instead of reload() the vertices (that is +1 operation per vertex), invalidating the client's cache is still the best option.

**Comment by vlasni** [comment]
Thanks Luca, so I will keep invalidating client's cache.

Best,
Adrian
