### ISSUE TITLE
Is there a way to tell schema that the property is of length N

### ISSUE THREAD

**Issue by warriorkitty** [orientechnologies/orientdb#6141]
```
ALTER PROPERTY SomeClass.someProperty MAX 11
ALTER PROPERTY SomeClass.someProperty MIN 11
```

Is there a way to do this in one command? I can't find it in the docs.

**Comment by lvca** [comment]
No sorry, you have to execute 2 commands, or a SQL BATCH with both of them inside.

**Comment by warriorkitty** [comment]
I've tried to implement the EXACTLY which just calls setMax and setMin in OPropertyImpl (and defined it in OProperty interface), for fun.

Do you want me to write tests and create a pull request so you can check it out?

**Comment by lvca** [comment]
Why not ;-)
