### ISSUE TITLE
OrientDB Studio UI issue - Property does not get displayed 

### ISSUE THREAD

**Issue by Manjiri0410** [orientechnologies/orientdb#6146]
## Expected behavior and actual behavior

When we make any configuration changes to see the property value on the bubble, the configuration gets saved. But when we log out and log in again, though the configuration is saved, the property is not displayed on the bubble unless and until we click on the bubble and open configuration panel. Ideally, the property should get displayed on the bubble instead of id on its own when graph is displayed.    
## Steps to reproduce the problem
- Change the configuration to display any property on the bubble and save the configuration. 
- Log out and log in again. 
- Check if the required property is displayed on the bubble. 
### OrientDB Studio Version
- [ ] v2.1.0 
### Operating System
- [ ] Linux
### Java Version
- [ ] 8

**Comment by maggiolo00** [comment]
hi @Manjiri0410 

did you use the user `root` to log in?

Can you try again with the db user  `admin`

**Comment by Manjiri0410** [comment]
Hi,

Yes...We use admin user to login to OrientDB Studio.

**Comment by maggiolo00** [comment]
@Manjiri0410 

did you try with the latest version 2.2.10?

**Comment by maggiolo00** [comment]
@Manjiri0410 

any updates?

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
