### ISSUE TITLE
Lucene doesn't create index on string fields with MAX constraint

### ISSUE THREAD

**Issue by laszlothewiz** [orientechnologies/orientdb#6149]
## Expected behavior and actual behavior
**Expected:** Lucene should create an index on all fields regardless of what constraints are on them, OR throw an error if it can't create it for some reason

**Actual:** Lucene works properly when no constraints are given for a field. When, for example MAX, constraint is added to a string field then it fails to create indexes and throws no errors

## Steps to reproduce the problem
In an empty database:

    CREATE CLASS test
    CREATE PROPERTY test.field1 STRING
    CREATE PROPERTY test.field2 STRING
    ALTER PROPERTY test.field2 MAX 8
    CREATE PROPERTY test.field3 STRING
    CREATE PROPERTY test.field4 STRING
    INSERT INTO test CONTENT {"field1":"One", "field2":"Two", "field3":"Three", "field4":"Four"}
    INSERT INTO test CONTENT {"field1":"Five", "field2":"Six", "field3":"Seven", "field4":"Eight"}

    CREATE INDEX test.field1 on test(field1) fulltext engine lucene
    SELECT count(*) FROM index:test.field1

**Result:** count=2 which is correct

    CREATE INDEX test.field2 on test(field2) fulltext engine lucene
    SELECT count(*) FROM index:test.field2

**Result:** count=0 which is incorrect!

### Runninng Mode
Standard Windows install running server at default port accessed via Studio in browser

### Misc
Single computer setup. 

### OrientDB Version
v2.1.16

### Operating System
Windows 7 x64

### Java Version
Java 8 Update 91

**Comment by maggiolo00** [comment]
hi @laszlothewiz 

just tested on orientdb 2.1.16 using your script with studio and it worked.

You are using it in embedded mode right?

If you try it in server mode does it work?

**Comment by laszlothewiz** [comment]
I'm not sure what the embedded or server mode means. I selected the option that made sense to me out of the 3 choices.

I downloaded the Windows installation and running it without any configuration change. Using the Studio in my browser.

**Comment by robfrank** [comment]
Even for me it works fine on studio.

**Comment by laszlothewiz** [comment]
Sorry. Somehow my installation must have gotten corrupt. It was doing it each time for me.
