### ISSUE TITLE
Corrupt state of distributed cluster when frozen db gets a write and then is released.

### ISSUE THREAD

**Issue by fortu-nato** [orientechnologies/orientdb#6150]
## Expected behavior and actual behavior

In a distributed cluster with 2 nodes (node A and node B) when node A is frozen and receives a write the client gets an error and B does not get a write; so far so good. When A is released the write goes through!!! but B gets no write, thus the cluster is in a corrupted state. 
Expected behavior is: after A issues an error to the client, the write should never go through.
## Steps to reproduce the problem

With 2.1.16. 
Setup a cluster with two nodes. Freeze db in node A. Issue a create vertex command on A. Release db in A. Issue a select for that vertex in A -> you get it back. Issue a select for that vertex in B -> you do not get it back and will never get it back.
If node A is restarted then the faulty vertex is removed.
The cluster is setup with default configs that ship with distribution.

In the logs for A (named ntl1) I get this:

> 2016-05-17 13:12:21:179 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=1) [ODistributedWorker]
> 2016-05-17 13:12:22:184 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=2) [ODistributedWorker]
> 2016-05-17 13:12:23:189 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=3) [ODistributedWorker]
> 2016-05-17 13:12:24:193 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=4) [ODistributedWorker]
> 2016-05-17 13:12:25:197 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=5) [ODistributedWorker]
> 2016-05-17 13:12:26:200 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=6) [ODistributedWorker]
> 2016-05-17 13:12:27:185 WARNI [ntl1] timeout (6004ms) on waiting for synchronous responses from nodes=[ntl1, ntl2] responsesSoFar=[ntl2] request=id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 [OHazelcastDistributedDatabase]
> 2016-05-17 13:12:27:185 WARNI [ntl1] detected 1 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0) [ODistributedResponseManager]
> 2016-05-17 13:12:27:186 WARNI [ntl1] Quorum 2 not reached for request (id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0). Elapsed=6018ms No server in conflict. Received: {ntl1=waiting-for-response, ntl2=#14:1164 v.1} [ODistributedResponseManager]
> 2016-05-17 13:12:27:187 WARNI [ntl1] sending undo message (record_delete(#14:1164 delayed=false)) for request (id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0) to server ntl2 [ODistributedResponseManager]
> 2016-05-17 13:12:27:204 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=7) [ODistributedWorker]
> 2016-05-17 13:12:28:208 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=8) [ODistributedWorker]

then just the last line over and over until the database is released: 

> 2016-05-17 13:40:26:055 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=1680) [ODistributedWorker]
> 2016-05-17 13:40:27:059 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=1681) [ODistributedWorker]
> 2016-05-17 13:40:28:065 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=1682) [ODistributedWorker]
> 2016-05-17 13:40:29:069 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=1683) [ODistributedWorker]
> 2016-05-17 13:40:30:074 INFO  [ntl1] Database is frozen, waiting and retrying. Request id=5 from=ntl1 task=record_create(#14:-1 v.0) user=#5:0 (retry=1684) [ODistributedWorker]
> 2016-05-17 13:40:30:456 INFO  {db=testdb} Releasing database 'plocal:/blahblah/databases/testdb' [ONetworkProtocolBinary]
> 2016-05-17 13:40:30:457 INFO  [ntl1] received updated status ntl1.testdb=ONLINE [OHazelcastPlugin]
> 2016-05-17 13:40:31:121 INFO  [ntl1] Request id=5 from=ntl1 task=record_create(#14:1164 v.0) user=#5:0 succeed after retry=1685 [ODistributedWorker]

So it looks like a rollback is issued to the other nodes but the rollback never happens in the local one.
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote
### Misc
- [x] I have a distributed setup with multiple servers. How many? 2
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [x] v2.1.x - Please specify last number: 16
- [ ] v2.2.x - Please specify last number: 
### Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by fortu-nato** [comment]
Hi Luca, 
do you have more info about this? 
With this bug and [this one](https://github.com/orientechnologies/orientdb/issues/6151) it feels very risky to distribute our db.

**Comment by lvca** [comment]
Please upgrade to v2.2.0 (GA) where we already fixed similar bugs.

**Comment by fortu-nato** [comment]
This is not resolved in 2.2.0.

**Comment by lvca** [comment]
@andreaiacono like the other issue. The user @fortu-nato tried with 2.2 and this problem persists. Could you write a test case for it please?

**Comment by fortu-nato** [comment]
Hi! 
when is the "next hotfix"?

**Comment by G4br13l3** [comment]
Hi @fortu-nato,

did you try last hotfix? Is this issue still relevant?

Thanks.

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
