### ISSUE TITLE
Different @version for same entity in different nodes of distributed cluster when one of them is temporarily frozen.

### ISSUE THREAD

**Issue by fortu-nato** [orientechnologies/orientdb#6151]
## Expected behavior and actual behavior

In a distributed cluster with 2 nodes (node A and node B) when node A is frozen and B receives a create command which goes ahead in B; so far so good. However, when A is released the write goes through BUT the version of the created entity A is higher than that of the one in B. The longer the freeze is the higher the version of the entity in A. This entity will never be able to be updated from A or B because of concurrent modification errors.
Expected behavior is: after A is released the write goes through and the versions in both nodes are the same.
## Steps to reproduce the problem

With 2.1.16. 
Setup a cluster with two nodes. Freeze db in node A. Issue a create vertex command on B. Release db in A. Issue a select for that vertex in B -> you get it with a @version=1. Issue a select for that vertex in A -> you get it with @version>1.
Restarting nodes first A then B results in entity in B set to same higher @version as A.
Restarting B and then A sets entity in A to same lower @version as B.
The cluster is setup with default configs that ship with distribution.
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote
### Misc
- [x] I have a distributed setup with multiple servers. How many?  2
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [x] v2.1.x - Please specify last number: 16
- [ ] v2.2.x - Please specify last number: 
### Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by lvca** [comment]
Please use v2.2.0 (GA) where we fixed similar problems.

**Comment by fortu-nato** [comment]
This is not resolved in 2.2.0.

**Comment by lvca** [comment]
@andreaiacono we already have the test case `OneNodeFrozenTest` that is similar to this. Could you please verify the versions on it and trying also the create vertex command?

**Comment by lvca** [comment]
This issue should be solved long time ago with 2.2.x. In case you still have a problem with a more recent version, please comment this. thanks.
