### ISSUE TITLE
Multiple issues with OrientDB 2.2.0 in embedded mode

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#6157]
Let me use this issue for resolving some issues related running OrientDB in embedded mode which is required for [Orienteer](https://github.com/OrienteerDW/Orienteer).

1) Server is not properly shutting down. Probably something missing please advise. But in log of [wicket-orientdb](https://github.com/OrienteerDW/wicket-orientdb) testing it's pretty common to see: https://gist.github.com/PhantomYdn/449304e41750e48d5aa672967f13d38d
As you can see server is not shutting down after test and next time port is still occupied. With 2.1.17 the same codebase was perfectly fine.
2) Ambiguous logs: there are much bigger amount of INFO logs than before. 
3) Is there a way to avoid creation of OServer database? 

Code of wicket-orientdb libary with attempt to adopt 2.2.0 is here: https://github.com/OrienteerDW/wicket-orientdb/tree/future
Actually all tests are failing for unknown reason like:

```
java.lang.AssertionError: Impossible to serialize invalid link #17:-1
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:861)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:883)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serializeValue(ORecordSerializerBinaryV0.java:746)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:384)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:99)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2319)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:652)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1988)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:246)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:176)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2529)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:99)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1817)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1808)
        at ru.ydn.wicket.wicketorientdb.TestDataInstallator.installData(TestDataInstallator.java:35)
        at ru.ydn.wicket.wicketorientdb.AbstractDataInstallator.onAfterInitialized(AbstractDataInstallator.java:23)
```
On OrientDB 2.1.17 everything was find

**Comment by PhantomYdn** [comment]
4) There is the following code: 
```java
for(ODocument doc : db.browseClass("MyClass)) {
Object obj = doc.field("myfield");
}
```
In 2.1.17 `obj` was of a type ODocument, but in 2.2.0 it's ORecordId. If it's lazy loading: is there some useful methods to "discharge laziness"?

**Comment by PhantomYdn** [comment]
5) Hooks are working not as expected. 
There is the following hook:
```java
public class TestHook extends ODocumentHookAbstract {
	
	public TestHook(ODatabaseDocument database) {
		super(database);
		setIncludeClasses("TestHooks");
	}
	
	@Override
	public void onRecordAfterRead(ODocument iDocument) {
		iDocument.field("name", "HOOK");
	}
	@Override
	public DISTRIBUTED_EXECUTION_MODE getDistributedExecutionMode() {
		return DISTRIBUTED_EXECUTION_MODE.SOURCE_NODE;
	}
}
```

And the following testcase is failing:

```java
@Test
	public void testInstallingHooks()
	{
		ODatabaseDocument db = wicket.getTester().getDatabase();
		OClass clazz = db.getMetadata().getSchema().getClass("TestHooks");
		assertNotNull(clazz);
		List<ODocument> ret = db.query(new OSQLSynchQuery<ODocument>("select from TestHooks"));
		assertTrue(ret.size()>0);
		ODocument doc = ret.get(0);
		assertEquals("HOOK", doc.field("name"));
	}
```

Hook registered properly. 
P.S. It's old wicket-orientdb compatibility test: https://github.com/OrienteerDW/wicket-orientdb/blob/master/wicket-orientdb/src/test/java/ru/ydn/wicket/wicketorientdb/TestHook.java which were fine before jumping to 2.2.0

**Comment by tglman** [comment]
@PhantomYdn,

Thank you for remporting this, very usefull, we will look at it ASAP

**Comment by tglman** [comment]
hi @PhantomYdn, 

the first issue has been fixed in develop, still have to check the hook.

bye

**Comment by tglman** [comment]
I run the hook test on the current develop and is green, so i'm closing this.

Bye

**Comment by PhantomYdn** [comment]
I'm sorry, but could not agree with you. Every single mentioned issue is still there... Let me summarize:

1) It seems that shutdown is looking better: at least port is closing. But there are still a lot of messages about closing of resources and number of messages are growing from test to test. So it seems that those resources are not being released. Example: https://gist.github.com/PhantomYdn/8d87560d9b5564c7ea0ba24316fceaa9
2) Still lots of logs in INFO debug level
3) Question about OServer is still open. This feature seems to be not logically compatible well with embedded behavior. 
4-5) Exactly these 2 testcases are failing...

```
Failed tests:   testCreationInHook(ru.ydn.wicket.wicketorientdb.orientdb.TestInAppOrientDBCompatibility): Impossible to serialize invalid link #-1:-1
  testInstallingHooks(ru.ydn.wicket.wicketorientdb.OrientDBSettingsTest): expected:<[HOOK]> but was:<[SAVED]>
```

**Comment by tglman** [comment]
Hi @PhantomYdn,

Sorry i missed some of the points, checking also them, about testInstallingHooks where TestHooks is actually installed ? i miss that part in your code.

**Comment by PhantomYdn** [comment]
@tglman , Yes - there is such point...
Hooks in wicket-orientdb registered in OrientDBSettings class and then activated per new ODatabaseDocument instance. Exact code here: https://github.com/OrienteerBAP/wicket-orientdb/blob/master/wicket-orientdb/src/main/java/ru/ydn/wicket/wicketorientdb/OrientDbWebApplication.java#L111-L118

For testing purposes corresponding hook registered here: https://github.com/OrienteerBAP/wicket-orientdb/blob/master/wicket-orientdb/src/test/java/ru/ydn/wicket/wicketorientdb/OrientDbTestWebApplication.java#L49

**Comment by tglman** [comment]
Hi @PhantomYdn,

Perfect I'll check the flow, and i'll try to fix it.

1) i should have fixed the leaking resources, i still have to add a proper test case.
2) the info log should be much less now.
3) OServer database i'll let you know

4-5) investigating and for `testCreationInHook` i saw that using:
```
			@Override
			public RESULT onRecordBeforeCreate(ODocument iDocument) {
				ODocument mirror = new ODocument(classB);
				mirror.field("name", iDocument.field("name"));
				iDocument.field("mirror", mirror);
				mirror.save();
				return RESULT.RECORD_CHANGED;
			}
```
the test pass, i'm trying to work on a fix that not need this, but it's taking me a while because the possibility of strange loops.

bye

**Comment by PhantomYdn** [comment]
@tglman, it seems that in 2.2.0 you have to call doc.save() on all related documents which are being created in Hook. But in real life: that's not what expected. For example, someone will want to add some reference to newly created document only if that document will be then stored/saved. Why? Because user might whant that change that value during modification and before save. 
Code I'm talking about:

```java
 @Override
            public void onRecordAfterRead(ODocument doc) {
                  doc.field("field", new ODocument("MyClass"));
                  ///doc.save();
             }
```

In this case document will have "something" in field "field", but that something might be redefined after read. So if doc.save() will be uncommented - it will work incorrectly.

**Comment by tglman** [comment]
Hi @PhantomYdn,

I just fixed the problem with the hook save, still have to sort out the read hook.
I'm afraid that for the OSystem database we don't have an option to disable it, in long term is going to store the credential for the server users plus other configurations.

Bye.

**Comment by PhantomYdn** [comment]
Hi @tglman , thank you!

Regarding OServer: I really hope that OUser and ORole for a specific database will remain within database themself, because they often has been used on app level. Can I assume that?

**Comment by tglman** [comment]
hi @PhantomYdn,

Yes the base behaviour is going to be the same, only the 'server users' the one that were stored in orientdb-server-config.xml are going to move in th OSystem database.

Bye

**Comment by tglman** [comment]
hi @PhantomYdn,

all the point should be done by now, let me know  you have any more issue or we can close this.

bye

**Comment by PhantomYdn** [comment]
@tglman , thank you!
It's strange, but I can't confirm that testInstallingHooks(...) is working. It's failing for me with the same message... Should I change something in test itself? Will try analyze your changes - probably something should be changed in hooks registration...

**Comment by tglman** [comment]
hi @PhantomYdn 

I just run your project and i got: 
```
[INFO] wicket-orientdb-parent ............................. SUCCESS [  2.181 s]
[INFO] wicket-orientdb .................................... SUCCESS [ 39.694 s]
[INFO] wicket-orientdb-demo ............................... SUCCESS [  8.839 s]
```
can you retry now, i posted here just after the push, maybe the snapshot where not update.

Regards.

**Comment by PhantomYdn** [comment]
Hi, @tglman,

Thank you! 2.2.1-SNAPSHOT works for me now:)
Next step is to move [Orienteer](http://orienteer.org) themself - the probably will bring more bugs, but let close this one and track that separatly.

**Comment by lvca** [comment]
Hey guys, this is not correct. Now the scan execute double reads! Why scanning records should invoke the hooks BEFORE_READ and AFTER_READ? It should be invoked only on the matching records, not against all of them.

**Comment by tglman** [comment]
Hi @lvca,

In case of scan the hooks are called only for the matched records.
