### ISSUE TITLE
SQL queries executor should consider @class WHERE clauses while resolving indexes

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6162]
For queries like `select from V where @class='Person' and name='foobar'` no Person indexes are considered while searching for applicable indexes. We should try narrow down the possible document class and examine its indexes while executing the query.

**Comment by smolinari** [comment]
Hey Sergey. In general and for my knowledge, (and after reading this page: http://orientdb.com/docs/2.1/Indexes.html) if I run a query on an indexed property (but not using the index in the query), will ODB still use that index automatically? Or do I have to actually always query the index to get a faster result? I know that may sound like a stupid question, but I truly am uncertain.

Scott

**Comment by taburet** [comment]
ODB will try to use the best index possible if you use queries like `select from SpecificClassHere where...`. This issue is applicable only if you use queries with no specific class specified and later filters by the class in `where` clause using `@class`. So, the answer is yes, ODB will use the index on indexed properties, there is no need to specify the concrete index.

**Comment by smolinari** [comment]
Yeah, sorry for sidetracking the issue. It just reminded me of my uncertainty on index usage. Thanks for answering. 

And if I may ask one more question, if ODB does use the (best) index, what purpose is there in querying the index directly? I mean, if I have a query, and it only projects for the fields in the index, then I should get a direct response from the index, without ODB digging for data in the actual records, correct? 

Scott

**Comment by taburet** [comment]
Yes, you are right. If you want to squeeze all the performance possible from ODB, you may query the index directly, that will not load the actual records, just return the RIDs of them. You may even try to populate indexes manually, if you see benefits from doing so :)

**Comment by smolinari** [comment]
Right. Though, I don't understand the choice. If ODB can use an index and it could possibly reply to the query directly from the index (i.e. the projected fields requested are the same fields in the index), then the user shouldn't really need any separate queries on the index. Right? ODB could simply return the index(ed) query result (without any record lookups).

But, as I understand it, the user would still need to do a separate query to get a pure index (and faster) result. To me, that means added complexity on the user's end. 

Maybe I should write up a suggestion? ODB has a query optimizer, doesn't it? I would imagine returning a pure index result could be a part of it. :smile:

Scott

**Comment by taburet** [comment]
Scott, let me check the source code, maybe projected properties are already handled the way you described. I'm just a man, I don't know everything ;)

**Comment by taburet** [comment]
Have traced the `select name from Foo where name='bar'` query with index on `Foo.name`. The record is fully loaded even if we have all the data on hands just from the index call. Scott, feel free to open an issue describing all your thoughts, wishes and pains on the subject :D

**Comment by smolinari** [comment]
Thank Sergey. I've created an issue with the suggestion. Sorry again for hijacking this issue.

Scott
