### ISSUE TITLE
source record is not a vertex

### ISSUE THREAD

**Issue by amyth** [orientechnologies/orientdb#6163]
## Expected behavior and actual behavior
I am using the `script sql` command in the console to run a batch query that `selects` a `Person` vertex then `selects` an `Email` vertex and then creates an edge `HAS` from person to email. When I run the command I get the following error.

```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.create edge has from $user to $email

Error: java.lang.IllegalArgumentException: source record is not a vertex
```

## Steps to reproduce the problem
```
orientdb {db=test}> script sql
[Started multi-line command. Type just 'end' to finish and execute]
orientdb {db=test}> begin
orientdb {db=test}> let user = select from person where uid = '12345'
orientdb {db=test}> let email = select from email where email = 'amyth@gmail.com'
orientdb {db=test}> let edge = create edge has from $user to $email
orientdb {db=test}> commit
orientdb {db=test}> return $edge
orientdb {db=test}> end
```
## Important Questions
As far as I know both `Person` and `Email` are vertexes in the database. The data and schema was inserted using a `.graphml` database exported from neo4j. What is source record here ? the person ?
Why is it not being treated as a vertex ? Another thing I would like to point out is for the same records if I directly create an edge using the records' `rid`'s, the edge between the vertexes are successfully created.

### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [x] v2.1.17 - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [x] 7
- [ ] 8

**Comment by maggiolo00** [comment]
Can you check in the schema if Person has V as superclass ?

**Comment by amyth** [comment]
![Vertex](http://www.techstricks.com/wp-content/uploads/2016/05/Screen-Shot-2016-05-19-at-9.57.18-pm.png)

Just checked. Both `Email` and `Person` has `V` as their superclass.

**Comment by maggiolo00** [comment]
@amyth 

i think the problem is the $user  variable. It is used in ODB in the context of the batch script to track the current user.

Try to use `$person` and tell me if it works

**Comment by amyth** [comment]
I see. If I change the variable name to person, I get the following error:
```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.create edge has from $person to $email

Error: java.lang.ClassCastException: java.lang.Integer cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable
```
![Error](http://www.techstricks.com/wp-content/uploads/2016/05/Screen-Shot-2016-05-19-at-10.26.15-pm.png)

**Comment by maggiolo00** [comment]
@amyth 

that is because $email is from update.

try with select on email or use

```
let $email= update  email set email = 'e@gmail.com' return after @this where email = 'e@gmail.com' 
```

**Comment by amyth** [comment]
@maggiolo00 Yes absolutely. Though I used the following (with upsert) as i needed  `create or update`.
```
let email = update email set email = 'xa@x.com' upsert return after @this where email = 'xa@x.com'
```

Thanks so much for your quick responses and help.
