### ISSUE TITLE
OrientDB 2.2.0 ETL 

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6164]
## Expected behavior and actual behavior
ETL with dbUser/dbPassword  returned:
"ERROR please provide server administrator credentials", 
 oetl.sh ended after listing several java errors.

added serverUser/Password (keeping dbUser/Pwd) to json file - then OK

## Steps to reproduce the problem
run oetl.sh w/someconfig.json

## Important Questions
Has this changed from 2.1.17?

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ *] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ *] v2.2.x - Please specify last number: 0 

### Operating System
- [ *] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ *] 8

**Comment by robfrank** [comment]
As stated in the documentation (http://orientdb.com/docs/last/Loader.html#orientdb-loader) if you want ETL to create a db on a remote server you must provide server admin credential AND database credentials. If the db was created (by studio or console) before, you need to provide only db credential.
The ability to create a database on remote db is present only from 2.2.0.

**Comment by rmanzar** [comment]
I added serverUser and serverPassword and it worked. I have placed posts.csv file in the \bin directory where oetl.bat exists. 

The content of the posts.csv is below

id,title
10,NoSQL movement
20,New OrientDB

And my JSON file content is. 

{
  "source": { "file": { "path": "posts.csv" } },
  "extractor": { "csv": {"separator": ",", "nullValue": "NULL"} },
  "transformers": [
    { "vertex": { "class": "Post" } }
  ],
  "loader": {
    "orientdb": {
       "dbURL": "remote:localhost/soft",
	   "serverUser": "root",
	   "serverPassword": "DBROOTPASSWORD",	   
	   "dbUser": "admin",
	   "dbPassword": "admin",	   	   
       "dbType": "graph",
       "classes": [
         {"name": "Post", "extends": "V"},
         {"name": "Comment", "extends": "V"},
         {"name": "HasComments", "extends": "E"}
       ], "indexes": [
         {"class":"Post", "fields":["id:integer"], "type":"UNIQUE" }
       ]
    }
  }
}
