### ISSUE TITLE
[suggestion] Have the query optimizer use indexes fully i.e. covered queries. 

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#6167]
Hi,

Continuing from this (albeit hijacked) [discussion](https://github.com/orientechnologies/orientdb/issues/6162#issuecomment-220315074). (Thanks @taburet für your patience) I'd like to suggest the following.

It would be a simplification for the user and an optimization of the querying system in ODB, if a query that can be returned by an index (covered query), only use the index. In other words, if an index has the fields to cover a projection, then ODB shouldn't fetch any records. It should just return the results directly from the index. This would speed up such queries. 

This also simplifies the system for the user, as the user must no longer create special queries against an index to get a faster query result. ODB would do this automatically. 

It boils down to a simple rule. 

> ODB should return _any_ query as fast as it can. :smile: 

I am coming from MongoDB and Mongo does this. There are no specific queries on indexes. MongoDB just does its best to be as fast as it can with whatever it has to work with, indexes there or not.

One other interesting feature in MongoDB is index intersecting. 

https://docs.mongodb.com/manual/core/index-intersection/

I am just throwing this in as a possible bonus feature. :smile:

Scott

**Comment by lvca** [comment]
Supported in v3.0-m2.
