### ISSUE TITLE
the orientdb server performance

### ISSUE THREAD

**Issue by NLPScott** [orientechnologies/orientdb#6168]
## Expected behavior and actual behavior
   I use orientdb 2.1.16，and when I start the orientdb server, the cpu will be very high , and I set the -XMX=5120M -XMS=5120M，the count of node is about 13K，but query search is frequent

### Runninng Mode

- [ ] Remote

### Misc
- [ ] I'm using the Community Edition

### OrientDB Version
- [ ] v2.1.x - Please specify last number: 

### Operating System
- [ ] Linux

### Java Version
- [ ] 7

**Comment by taburet** [comment]
Do you run queries when CPU usage is high? Or it's just high on idling?

**Comment by NLPScott** [comment]
@taburet  no queries the cpu is low , when run the queries the cpu is very high

**Comment by taburet** [comment]
That is a normal situation, I think. Usually, if database consumes a lot of CPU on queries this means it is not disk IO bounded. Could you please measure a number of queries executed per second to confirm that there is no problem.

**Comment by NLPScott** [comment]
@taburet  my pc configuration : processor is 24,the total mem is 32G,the number of node is 12K,when I run the queries (I will seach each node in random),the cpu is  1000%

**Comment by NLPScott** [comment]
@taburet  should I set the  ORIENTDB_OPTS_MEMORY="-Xms5120m -Xmx5120m"   MAXDISKCACHE="-Dstorage.diskCache.bufferSize=8192"

**Comment by taburet** [comment]
Under nodes you mean nodes of the distributed server or vertexes in the database?

**Comment by NLPScott** [comment]
@taburet  no distributed server, only a single server

**Comment by NLPScott** [comment]
@taburet  the node is vertex

**Comment by taburet** [comment]
I suggest you to measure the number of queries executed per second and inspect your indexes if there are any. Your memory settings are really high, so all the data sits in the caches. You must be able squeeze all the possible performance from database under this configuration and performance needs CPU power to run the queries as fast as possible. But CPU power may be wasted if you have no indexes.

BTW, do you run the queries in parallel? Is it really 1000% CPU usage or just 100%? 1000% of CPU means there are 10 cores used at 100%.

**Comment by NLPScott** [comment]
@taburet  oh ,I will set the Index,and record the qps, I run the queries in parallel,and the mem is 18%

**Comment by taburet** [comment]
Feel free to provide the query examples and I will suggest the indexes it may benefit from.

**Comment by NLPScott** [comment]
@laa  what do you think of this performance?

**Comment by taburet** [comment]
Closed because of no reply.
