### ISSUE TITLE
console: export schema but no import schema

### ISSUE THREAD

**Issue by mamoit** [orientechnologies/orientdb#6172]
## Expected behavior and actual behavior
There is a console command `export schema`, but there is no `import schema` available.

## Steps to reproduce the problem
1. `export schema` in one database
2. try to import it in another fresh one, but how?

## Important Questions
What's the answer to life, the universe, and everything?

### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [x] I have a distributed setup with multiple servers. How many? 3
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 0

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by lvca** [comment]
It's always the `import database` command that check what there is available in the exported file. If you exported only the schema, then only the schema will be imported.
