### ISSUE TITLE
JDBC prepared statement returns NullPointerException

### ISSUE THREAD

**Issue by nadewor** [orientechnologies/orientdb#6175]
## Expected behavior and actual behavior
Calling a prepared statement via jdbc interface returns NullPointerException

Exception in thread "main" java.lang.NullPointerException
	at com.orientechnologies.orient.jdbc.OrientJdbcResultSetMetaData.getColumnType(OrientJdbcResultSetMetaData.java:192)
	at TestOrientdb.main(TestOrientdb.java:42)

A prepared statement should work without problems via jdbc interface.

## Steps to reproduce the problem
Using the default database:

	      OrientJdbcConnection conn = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:" + dbUrl, info); 
		  
	      //create and execute statement 
	      String stmtStr = "SELECT FROM V WHERE song_type like ?";
	      
	      
	      PreparedStatement stmt = conn.prepareStatement(stmtStr);
	      stmt.setString(1, "original");
	      
	      ResultSet rs = stmt.executeQuery();
	      
	      int type = rs.getMetaData().getColumnType(1);

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ X] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X ] v2.2.x - Please specify last number: 0

### Operating System
- [ ] Linux
- [X ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ X] 8

**Comment by robfrank** [comment]
Try this:
```
String stmtStr = "SELECT FROM V WHERE song_type like '?' ";
```

**Comment by nadewor** [comment]
I tried statement String stmtStr = "SELECT FROM V WHERE song_type like ?"; doesn't work too. 
stmt.setString(0, "'original'");

For this statement it returns java.sql.SQLException: No current record

I also tried with an int an it doesn't work too:
	      String stmtStr = "SELECT FROM V WHERE performances = ?";
	      PreparedStatement stmt = conn.prepareStatement(stmtStr);
	      stmt.setInt(0, 1);

For this statement it returns a NullPointerException.

**Comment by robfrank** [comment]
Did use quotes? 
```sql
SELECT FROM V WHERE song_type like '?'
```

**Comment by robfrank** [comment]
Your code works fine if you wrap the ? with sigle quotes, as stated on previous comment:  
```sql
SELECT FROM V WHERE song_type like '?'
```

You're querying the GratefulDeadConcerts,  that is mainly schema less, so the line
```java
 int type = rs.getMetaData().getColumnType(1);
```
can't get any result because, internally, it relies on db metadata.

**Comment by nadewor** [comment]
But the same happens if I query the VehicleHistoryGraph db. I have a question: If  I have a query doesn't return any result, why getColumnCount() throws an exception? Is it not possible to read the meta data another way?

I have this problem by using BIRT and orientdb via jdbc driver. In BIRT you can create some filter parameters which are applied as prepared statements on the data set. Since this parameters are set dynamically by user BIRT cannot create a schema at the time of data set definition because of SqlException. With the sqlite db this use case works without problems.

**Comment by robfrank** [comment]
which version please?

**Comment by nadewor** [comment]
Orientdb version 2.2.0 
BIRT version 4.5.0

**Comment by robfrank** [comment]
The implementation respect the javadoc form JDBC specs:
```
  * @return the description of a <code>ResultSet</code> object's columns or
     *         <code>null</code> if the driver cannot return a
     *         <code>ResultSetMetaData</code> object
```
I this case the ResultSet will be null, and so the metadata. Note that even if a PreparedStatement is used, The driver can't precompute the ResultSet metadata

**Comment by nadewor** [comment]
Which method do you refer to with the last comment? ResultSetMetaData.getColumnCount()?

**Comment by robfrank** [comment]
No, sorry, is the javadoc from ResutlSet.getMetadata:
```
 /**
     * Retrieves the  number, types and properties of
     * this <code>ResultSet</code> object's columns.
     *
     * @return the description of this <code>ResultSet</code> object's columns
     * @exception SQLException if a database access error occurs or this method is
     *            called on a closed result set
     */
    ResultSetMetaData getMetaData() throws SQLException;
```
The problem is that at the JDBC level we don't have all the info about the documents retrieved from Orient. And even if you work with plain OrientDB API what you get  as a query result is a list od ODocuments, nothing more. On 3.0 we are working  to overcome this,  providing more metadata about the documents set returned by the database.

**Comment by Mzed-man** [comment]
Check if you have included the mysql-jdbc-connector or the connector to your database library into your project.
