### ISSUE TITLE
orientdb-server-2.2.0.jar appears to lack server.config package

### ISSUE THREAD

**Issue by lgaquino** [orientechnologies/orientdb#6176]
Hello all,
I have a project that used to store a graph on v2.1.6. It was all fine and working. But when I updated to v2.20, I got an error on the OServer.startup() method, with the following message:

> The type com.orientechnologies.orient.server.config.OServerConfiguration cannot be resolved. It is indirectly referenced from required .class files

I access the DB with PLOCAL, and passing a config file. Here's the code I use to configure and connect to the DB:

`            this.dataPath = dataPath;
            final String path = "plocal:" + dataPath + dbName;
            server = OServerMain.create();
            InputStream dbConfigFile = Thread.currentThread().getContextClassLoader().getResourceAsStream(CONFIG);
            server.startup(dbConfigFile);
            server.activate();
            OrientGraphFactory factory = new OrientGraphFactory(path).setupPool(1, 10);
            return factory.getTx();`

The message above appears on the '_server.startup(dbConfigFile);_' bit.
What I did notice was that the **startup()** uses classes that are on the **com.orientechnologies.orient.server.config** package. And that is no longer in the orientdb-server-2.2.0.jar

Am I missing something? Should I change the way I start the OServer?

Specs:
the DB is not distributed, accessed via plocal, on windows, and not enterprise. Using java 7.

Thanks in advance!

**Comment by lvca** [comment]
That class has been moved under the `tools` package. So please include also `orientdb-tools-*.jar`
