### ISSUE TITLE
orient.load not returning JSON

### ISSUE THREAD

**Issue by anywhichway** [orientechnologies/orientdb#6180]
## Expected behavior and actual behavior

It appears `orient.load' is not returning JSON when called from a trigger written in Javascript:
`
var children = doc.field("children");
children.forEach(function(childid) {
  var child = orient.getDatabase().load(childid);
   print(child);
});
 `
prints: Person#12:4{children:null,name:Tyler,parents:[1]} v2
expected: {@class:"Person", @id:"12:4", @version:2, children:null,name:Tyler,parents:[1]}

The documentation for Functions says: "Method that loads a record from the record ID, it returns the record informations in JSON format."

## Steps to reproduce the problem

see code above, when loading objects from ids stored in arrays which represent links

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

Unsure, just installed and ran from command line.

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ v2.2.17] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ x] 8

**Comment by lvca** [comment]
That method returns the record. If you want the JSON you can call:

    var child = orient.getDatabase().load(childid);
    print( child.toJSON() );

In which page did you find that wrong description?

**Comment by anywhichway** [comment]
Ivca here is the page: http://orientdb.com/docs/last/Javascript-Driver.htmlhttp://orientdb.com/docs/last/Javascript-Driver.html

Is the documentation correct or incorrect?

If it is incorrect, is it supposed to be a string? If so, I will simply write a parser ... pretty trivial given the apparent the string format.

**Comment by lvca** [comment]
That why the confusion: that page (by the way it would need to be cleared) is for the JS driver in the browser. We don't have a page with the API to call from function. I'm going to create a new issue for that. In the meanwhile please look at this class to see the API:

https://github.com/orientechnologies/orientdb/blob/2fecb73699ce7d3d81cf378cf5dcfbb5cf6261b0/core/src/main/java/com/orientechnologies/orient/core/command/script/OScriptDocumentDatabaseWrapper.java

**Comment by lvca** [comment]
Done: https://github.com/orientechnologies/orientdb/issues/6182
