### ISSUE TITLE
replication issue while running multiple instances/environments

### ISSUE THREAD

**Issue by skonka** [orientechnologies/orientdb#6186]
## Expected behavior and actual behavior
Hi - I am using orient db 2.1.2 CE on Linux and JDK 1.7. I tried to set-up two parallel environments in our QA region. Calling them QA-SIT and QA-UAT. Each of the environments has 3 nodes and run in distributed remote mode. I have same database name[ods], using one for SIT and another for UAT. Unfortunately they are distributed on same 3 physical servers and are using same faceless-id. What I noticed is, the QA-UAT and QA-SIT are getting messed up and I saw same data replicated on both of them.

## Steps to reproduce the problem

Start all 3 instances in QA-SIT in distributed mode. When I start the 2nd node(on 2nd server), the 1st node writes to /tmp/orientdb/backup_ods.zip(on 1st server) and copies to 2nd server as /tmp/orientdb/install_ods.zip, the 2nd node reads this and replicates. This works fine when I run just QA-SIT. Same happens for QA-UAT environment also (since I used same faceless id, the 1st node overrides and creates its own /tmp/orientdb/backup_ods.zip). 

Now I had to recycle 2nd node of QA-SIT(it picks up /tmp/orientdb/backup_ods.zip that QA-UAT has written) and copies as /tmp/orientdb/install_ods.zip and start replicating across other nodes. After this, all 6 nodes will have same data.

## Important Questions
Is there a way I can override the /tmp/orientdb/ property (I searched all through your source code, but was not able to find except in backup.sh and that too it is /tmp/orientdb/backup, used if I enable backup)

## Workaround
I had to name db different as ods-sit and ods-uat and made it work. But is there a way I can maintain same db names but just override the paths.

**Comment by lvca** [comment]
You can use a different path by setting the JVM setting `java.io.tmpdir`. Example:

    java ... -Djava.io.tmpdir=/myfolder/server1

OrientDB will create the temporary database under the folder `/myfolder/server1/orientdb`
