### ISSUE TITLE
Group By, Order by with limit

### ISSUE THREAD

**Issue by lalitlogical** [orientechnologies/orientdb#6191]
## Expected behavior and actual behavior

Expected behavior: We should get sorted data according to order by then group by for a specific limit.
actual behavior: We are getting group by data in sorting order but which is not correct for us.
## Steps to reproduce the problem

Actually, We have users and posts tables which contain data according to user column (link type). We need posts which group by users and sorted by the distance. Posts contain latitude and longitude field which is using for calculating distance from current logged in user. 

So when we fetch data from below query.

SELECT @rid, distance(latitude, longitude, SOME_latitude, SOME_longitude) as distance, created_at FROM posts LET $user = user WHERE GROUP BY $user ORDER BY distance ASC LIMIT 20 SKIP 0;

We are getting the grouped post according to users in sorted order. But in result post does not have small distance for that  @user.

Let us understand by below example.

USER1            USER2        USER3
post (3 m)        post (1m)     post (5 m)
post (2 m)       post (0.5 m)  post (2m)
post (1m)

**Actual Result**
USER2(with post (1m)), USER1(with post (2m)), USER3(with post(5m))

**Expected Result**
USER2(with post (1m)), USER1(with post (2m)), USER3(with post(2m))
### Runninng Mode
- [ ] Remote
### Misc
- [ ] I'm using the Community Edition
### OrientDB Version
- [ ] v2.1.x - Please specify last number: 1
- [ ] v2.2.x - Please specify last number: 0
### Operating System
- [ ] Linux 
- [ ] MacOSX
### Java Version
- [ ] 6
- [ ] 7
- [ ] 8

**Comment by luigidellaquila** [comment]
Hi @lalitlogical 

I'm struggling a little bit to understand your example, any chance to have an SQL script to reproduce the problem?

(btw, I guess the WHERE in the query is a typo...)

Thanks

Luigi

**Comment by lalitlogical** [comment]
Hi @luigidellaquila 

We have created Document Type Database in OrientDB. We are making a project with NodeJs + oriendb + oriento.

Basically, we have two tables as Users and Posts. Users can have many posts with posts table. Post table has a link type column of the owner( user's @rid). The post can be sorted by the distance. So we need posts as group by the user with distance in descending order.

When we are executing the query, we are getting the posts  as correct descending order with group by the user. But when we fetch other posts for any specific user, that contains the small distance posts than we got previously from the first query.

So I think **may be** there is a problem with group by with order by. So we are getting large distance post for a user which also contains the small distance posts.

Let me know for same if you can help.

We are getting two slow response for a query which may have not any record for that condition. In past, we have to run the sub-queries with the help of LET, but it is taking approx 16 secs for 1000 records. We are currently in development phase. So it is not acceptable in any way.

We are very disappointed with the speed/performance of OrientDb. Maybe we have not proper documentation which demonstrates some example for same to optimise our queries.

**Comment by luigidellaquila** [comment]
Hi @lalitlogical 

I think the problem is related to the fact that ordering and grouping on aliases is not supported in current release.
I suggest you to use a subquery for that, eg.

```
select from (
   SELECT @rid, distance(latitude, longitude, SOME_latitude, SOME_longitude) as distance, created_at, user FROM posts
) GROUP BY user ORDER BY distance ASC LIMIT 20 SKIP 0
```

Thanks

Luigi
