### ISSUE TITLE
toJSON object @<key> not accessable

### ISSUE THREAD

**Issue by anywhichway** [orientechnologies/orientdb#6195]
## Expected behavior and actual behavior

Inside an onBeforeChange Hook:

`var  className = doc.field('@class'),
      json = doc.toJSON();
      className===json["@class"] 
      // expect true; however fails and print shows json["@class"] as undefined
`
## Steps to reproduce the problem

create a Hook with the above code
attach the Hook to a class definition
change a document of type class

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ 17] v2.1.x - Please specify last number: 
- [] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [ x] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ x] 8

**Comment by maggiolo00** [comment]
hi @anywhichway 

```
doc.toJSON()
```
Converts the document into String not into a javascript object.

http://orientdb.com/javadoc/latest/com/orientechnologies/orient/core/record/ORecordAbstract.html#toJSON--

 So if you want to use it in that way you should do

```
print(JSON.parse(json)['@class']);
```

**Comment by anywhichway** [comment]
;-( ... 8 years programming in JavaScript and you would think I would know this! Sorry to waste your time.
