### ISSUE TITLE
orient.getDatabase().query() does not return Array with forEach method

### ISSUE THREAD

**Issue by anywhichway** [orientechnologies/orientdb#6196]
## Expected behavior and actual behavior

```
var a = orient.getDatabase().query("<some select>");
// expect the below to work
a.forEach(function(item) {

});
// however only this works
for(var i=0;i<a.length;i++) {

}

```
## Steps to reproduce the problem

put code similar to the above in an onBeforeUpdate hook

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [17 ] v2.1.x - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [ x] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x ] 8

**Comment by anywhichway** [comment]
If this is an enhancement, what is it that query is returning? A key-mapped Object or an Array without the forEach method? If it is an Array, what other methods are either missing or available?

**Comment by luigidellaquila** [comment]
Hi @anywhichway 

I hope I got it right, the code is in a JS function, is it correct?
The returned object is a Java array, not a JS one, this is why the forEach() does not work.

Thanks

Luigi

**Comment by anywhichway** [comment]
Thanks! Obviously an enhancement then. Of course, it would be ideal if all JavaScript returned JavaScript ... but I am sure there are lots of other things to focus on. Knowing this will help elsewhere.
