### ISSUE TITLE
Error creating database from Studio v2.2.0

### ISSUE THREAD

**Issue by anywhichway** [orientechnologies/orientdb#6197]
## Expected behavior and actual behavior

Expected: Try to create a new database from Studio succeeds.
Actual: 

```
{"errors":[{"code":500,"reason":500,"content":"com.orientechnologies.common.io.OIOException: You cannot access outside the file size (0 bytes). You have requested portion 0-4 bytes. File: File: database.ocf os-size=1024, stored=0"}]}
```

Also getting this in console:

```
        Storage URL="plocal:C:/Users/Simon/OrientDB/orientdb-community-2.2.0/databases/OSystem" [OSystemUserAuthenticator]
2016-05-23 20:23:23:393 SEVER isAuthorized() Exception: Cannot open local storage 'C:/Users/Simon/OrientDB/orientdb-community-2.2.0/databases/OSystem' with mode=rw
        Storage URL="plocal:C:/Users/Simon/OrientDB/orientdb-community-2.2.0/databases/OSystem" [OSystemUserAuthenticator]
```

## Steps to reproduce the problem

Try to create a database from the Studio

### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ 0] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [ x] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ x] 8 64 bit u92

**Comment by anywhichway** [comment]
I uninstalled and re-installed OrientDb. The issue went away. It may have been cause by the old studio being open when I originally installed v2. The attempt to access the now non-existent database from the old version may have got things confused.

**Comment by chunkiat82** [comment]
I still have this issue with a docker image 2.2.9
