### ISSUE TITLE
orientdb configuration

### ISSUE THREAD

**Issue by NLPScott** [orientechnologies/orientdb#6199]
## Expected behavior and actual behavior

 I set the db.pool.min and db.pool.max in the orientdb-server-config.xml , 

    <properties>
        <entry value="10" name="db.pool.min"/>
        <entry value="30" name="db.pool.max"/>
        <entry name="client.channel.minPool" value="50"/>
        <entry name="client.channel.maxPool" value="300"/>
        <entry value="true" name="profiler.enabled"/>
        <entry value="info" name="log.console.level"/>
        <entry value="fine" name="log.file.level"/>
    </properties>
,but I can't get db.pool.min =10 and db.pool.max =30 from OGlobalConfiguration.dumpConfiguration(System.out)

this is my OGlobalConfiguration.dumpConfiguration(System.out) result:
OrientDB 2.1.13 configuration dump:
- ENVIRONMENT
  + environment.dumpCfgAtStartup = false
  + environment.concurrent = true
  + environment.allowJVMShutdown = true
- SCRIPT
  + script.pool.maxSize = 20
- MEMORY
  + memory.useUnsafe = true
  + memory.directMemory.safeMode = true
  + memory.directMemory.trackMode = false
  + memory.directMemory.onlyAlignedMemoryAccess = true
- JVM
  + jvm.gc.delayForOptimize = 600
- STORAGE
  + storage.diskCache.pinnedPages = 20
  + storage.diskCache.bufferSize = 7445
  + storage.diskCache.writeCachePart = 15
  + storage.diskCache.writeCachePageTTL = 86400
  + storage.diskCache.writeCachePageFlushInterval = 25
  + storage.diskCache.writeCacheFlushInactivityInterval = 60000
  + storage.diskCache.writeCacheFlushLockTimeout = -1
  + storage.diskCache.diskFreeSpaceLimit = 100
  + storage.diskCache.diskFreeSpaceCheckInterval = 5
  + storage.diskCache.diskFreeSpaceCheckIntervalInPages = 4096
  + storage.diskCache.keepState = true
  + storage.configuration.syncOnUpdate = true
  + storage.compressionMethod = nothing
  + storage.useWAL = true
  + storage.wal.syncOnPageFlush = true
  + storage.wal.cacheSize = 3000
  + storage.wal.maxSegmentSize = 128
  + storage.wal.maxSize = 4096
  + storage.wal.commitTimeout = 1000
  + storage.wal.shutdownTimeout = 10000
  + storage.wal.fuzzyCheckpointInterval = 300
  + storage.wal.reportAfterOperationsDuringRestore = 10000
  + storage.wal.restore.batchSize = 50000
  + storage.wal.readCacheSize = 1000
  + storage.wal.fuzzyCheckpointShutdownWait = 600
  + storage.wal.fullCheckpointShutdownTimeout = 600
  + storage.wal.path = null
  + storage.makeFullCheckpointAfterCreate = true
  + storage.makeFullCheckpointAfterOpen = true
  + storage.makeFullCheckpointAfterClusterCreate = true
  + storage.diskCache.pageSize = 64
  + storage.lowestFreeListBound = 16
  + storage.cluster.usecrc32 = false
  + storage.lockTimeout = 0
  + storage.record.lockTimeout = 2000
  + storage.useTombstones = false
- RECORD
  + record.downsizing.enabled = true
- OBJECT
  + object.saveOnlyDirty = false
- DB
  + db.pool.min = 1
  + db.pool.max = 100
  + db.pool.idleTimeout = 0
  + db.pool.idleCheckDelay = 0
  + db.mvcc.throwfast = false
  + db.validation = true
- NONTX
  + nonTX.recordUpdate.synch = false
  + nonTX.clusters.sync.immediately = manindex
- TX
  + tx.trackAtomicOperations = false
- INDEX
  + index.embeddedToSbtreeBonsaiThreshold = 40
  + index.sbtreeBonsaiToEmbeddedThreshold = -1
- HASHTABLE
  + hashTable.slitBucketsBuffer.length = 1500
- INDEX
  + index.auto.synchronousAutoRebuild = true
  + index.auto.lazyUpdates = 10000
  + index.flushAfterCreate = true
  + index.manual.lazyUpdates = 1
  + index.durableInNonTxMode = false
  + index.txMode = FULL
  + index.cursor.prefetchSize = 500000
- SBTREE
  + sbtree.maxDepth = 64
  + sbtree.maxKeySize = 10240
  + sbtree.maxEmbeddedValueSize = 40960
- SBTREEBONSAI
  + sbtreebonsai.bucketSize = 2
  + sbtreebonsai.linkBagCache.size = 100000
  + sbtreebonsai.linkBagCache.evictionSize = 1000
  + sbtreebonsai.freeSpaceReuseTrigger = 0.5
- RIDBAG
  + ridBag.embeddedDefaultSize = 4
  + ridBag.embeddedToSbtreeBonsaiThreshold = 40
  + ridBag.sbtreeBonsaiToEmbeddedToThreshold = -1
- COLLECTIONS
  + collections.preferSBTreeSet = false
- FILE
  + file.trackFileClose = false
  + file.lock = true
  + file.deleteDelay = 10
  + file.deleteRetry = 50
- JNA
  + jna.disable.system.library = true
- NETWORK
  + network.maxConcurrentSessions = 1000
  + network.socketBufferSize = 32768
  + network.lockTimeout = 45000
  + network.socketTimeout = 60000
  + network.requestTimeout = 3600000
  + network.retry = 5
  + network.retryDelay = 500
  + network.binary.loadBalancing.enabled = false
  + network.binary.loadBalancing.timeout = 2000
  + network.binary.maxLength = 32736
  + network.binary.readResponse.maxTimes = 20
  + network.binary.debug = false
  + network.http.maxLength = 1000000
  + network.http.charset = utf-8
  + network.http.jsonResponseError = true
  + network.http.jsonp = false
- OAUTH2
  + oauth2.secretkey = 
- NETWORK
  + network.http.sessionExpireTimeout = 300
  + network.http.useToken = false
  + network.token.secretyKey = 
  + network.token.encriptionAlgorithm = HmacSHA256
  + network.token.expireTimeout = 60
- PROFILER
  + profiler.enabled = false
  + profiler.config = null
  + profiler.autoDump.interval = 0
  + profiler.maxValues = 200
- LOG
  + log.console.level = info
  + log.file.level = fine
- COMMAND
  + command.timeout = 0
- QUERY
  + query.scanThresholdTip = 50000
  + query.limitThresholdTip = 10000
- SQL
  + sql.graphConsistencyMode = tx
- CLIENT
  + client.channel.maxPool = 100
  + client.connectionPool.waitTimeout = 5000
  + client.channel.dbReleaseWaitTimeout = 10000
  + client.ssl.enabled = false
  + client.ssl.keyStore = null
  + client.ssl.keyStorePass = null
  + client.ssl.trustStore = null
  + client.ssl.trustStorePass = null
  + client.session.tokenBased = false
- SERVER
  + server.channel.cleanDelay = 5000
  + server.cache.staticFile = false
  + server.log.dumpClientExceptionLevel = FINE
  + server.log.dumpClientExceptionFullStackTrace = false
- DISTRIBUTED
  + distributed.crudTaskTimeout = 3000
  + distributed.commandTaskTimeout = 10000
  + distributed.commandLongTaskTimeout = 86400000
  + distributed.deployDbTaskTimeout = 1200000
  + distributed.deployChunkTaskTimeout = 15000
  + distributed.deployDbTaskCompression = 7
  + distributed.queueTimeout = 5000
  + distributed.asynchQueueSize = 0
  + distributed.asynchResponsesTimeout = 15000
  + distributed.purgeResponsesTimerDelay = 15000
  + distributed.queueMaxSize = 10000
  + distributed.backupDirectory = ../backup/databases
  + distributed.concurrentTxMaxAutoRetry = 10
  + distributed.concurrentTxAutoRetryDelay = 100
- DB
  + db.makeFullCheckpointOnIndexChange = true
  + db.makeFullCheckpointOnSchemaChange = true
  + db.document.serializer = ORecordSerializerBinary
- LAZYSET
  + lazyset.workOnStream = true
- DB
  + db.mvcc = true
  + db.use.distributedVersion = false
- MVRBTREE
  + mvrbtree.timeout = 0
  + mvrbtree.nodePageSize = 256
  + mvrbtree.loadFactor = 0.7
  + mvrbtree.optimizeThreshold = 100000
  + mvrbtree.entryPoints = 64
  + mvrbtree.optimizeEntryPointsFactor = 1.0
  + mvrbtree.entryKeysInMemory = false
  + mvrbtree.entryValuesInMemory = false
  + mvrbtree.ridBinaryThreshold = -1
  + mvrbtree.ridNodePageSize = 64
  + mvrbtree.ridNodeSaveMemory = false
- TX
  + tx.commit.synch = false
  + tx.autoRetry = 1
  + tx.log.fileType = classic
  + tx.log.synch = false
  + tx.useLog = true
- INDEX
  + index.auto.rebuildAfterNotSoftClose = true
- CLIENT
  + client.channel.minPool = 1
- STORAGE
  + storage.keepOpen = true
- CACHE
  + cache.local.enabled = true

In the orientdb-server-config.xml , 
 I set  <entry value="10" name="db.pool.min"/>
        <entry value="30" name="db.pool.max"/>
        <entry name="client.channel.minPool" value="50"/>
        <entry name="client.channel.maxPool" value="300"/>
but In the client,I get 
     client.channel.minPool = 1
     client.channel.maxPool = 100
     db.pool.min = 1
    db.pool.max = 100

### Runninng Mode
- [ ] Remote

### Misc
- [ ] I'm using the Community Edition

### OrientDB Version
- [ ] v2.1.13 - Please specify last number: 

### Operating System
- [ ] Linux

### Java Version
- [ ] 7

**Comment by lvca** [comment]
When do you call `OGlobalConfiguration.dumpConfiguration(System.out)`? Remember that the server's settings are applied on server startup, so you should wait the server is started.
