### ISSUE TITLE
com.orientechnologies.common.io.OIOException: Found unknown session

### ISSUE THREAD

**Issue by skonka** [orientechnologies/orientdb#6206]
version 2.1.16 EE, JDK 8, Linux

Hi - I was evaluating 2.1.16 EE (earlier was using 2.1.1 CE). Continuously seeing below error in the logs

Error executing request
com.orientechnologies.common.io.OIOException: Found unknown session 1500
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:240)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:214)

How do I fix this?

Following is the extract of params I have overridden in server.sh

#JAVA_OPTS_SCRIPT="-Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9"

JAVA_OPTS_SCRIPT="-Duser.timezone=America/Chicago -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=$LOG_DIR  -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dstorage.keepOpen=false -Denvironment.dumpCfgAtStartup=true"

# ORIENTDB memory options, default to 512 of heap.
ORIENTDB_OPTS_MEMORY="-Xms512m -Xmx8192m"

if [ -z "$ORIENTDB_OPTS_MEMORY" ] ; then
    ORIENTDB_OPTS_MEMORY="-Xms512m -Xmx512m"
fi

#ORIENTDB MAXIMUM DISKCACHE IN MB, EXAMPLE, ENTER -Dstorage.diskCache.bufferSize=8192 FOR 8GB
MAXDISKCACHE="-Dstorage.diskCache.bufferSize=32768"

exec "$JAVA" $JAVA_OPTS $ORIENTDB_OPTS_MEMORY $JAVA_OPTS_SCRIPT $ORIENTDB_SETTINGS $MAXDISKCACHE \
    -Djava.util.logging.config.file="$LOG_FILE" \
    -Dorientdb.config.file="$CONFIG_FILE" -Ddistributed.backupDirectory="" \
    -Dorientdb.www.path="$WWW_PATH" \
    -Dorientdb.build.number="2.1.x@r13efec7610a3eceb539db5ebfb31dea2534aa819; 2016-04-19 10:56:07+0000" \
    -cp "$ORIENTDB_HOME/lib/orientdb-server-2.1.16.jar:$ORIENTDB_HOME/lib/*" \
    $* com.orientechnologies.orient.server.OServerMain

**Comment by tglman** [comment]
hi @skonka,

This is not a bug, it happen with normal operation like a session expire or a temporary disconnect, it's handled whit an automatic reconnect by the orient client, no action needed, i actually removed the log from the next hotfix.

Bye
