### ISSUE TITLE
Automatic bug reports

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#6211]
1. Create a new setting like logExceptionsMax =1000. <=0 means no logging
2. We can use the OSystem database on the server for them
3. The OrientDB server should write the exception that wraps at HTTP and Binary protocol level
4. Since we don't have capped clusters, the insert should check if the size() > logExceptionsMax, then stop to add new log reports.
5. Studio should have a form where you can browse inside this class and send the one or more exceptions in some way.
6. The file could be a zipped export of the records (we can use database export with the includeClass=ThatClass)
7. The best would be attaching the file to an open issue

**Comment by taburet** [comment]
I think, there also should be a really annoying notification or indication about new exceptions, so it will be easier to send them to us than just ignoring them :D
