### ISSUE TITLE
SQL: create user doesn't work

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6216]
The command:

    create user TestUser identified by password ROLE ['reader','writer']

Is transformed in

    INSERT INTO OUser SET name='TestUser',password='password',status='ACTIVE',roles=(SELECT FROM ORole WHERE name IN [''reader'', ''writer''])

**Comment by luigidellaquila** [comment]
Fixed in develop branch (2.2.1)

Thanks

Luigi
