### ISSUE TITLE
How can I tell from an ORID, if the document behind was deleted

### ISSUE THREAD

**Issue by kerner1000** [orientechnologies/orientdb#6221]
Hi,
I tried the following without success.

<pre>
@Test
public final void testDelete01() {
	ORID o1 = new ODocument("d1").save().getIdentity();
	db.delete(o1);
	assertFalse(o1.isPersistent());
	assertFalse(o1.isValid());
}
</pre>

**Comment by lvca** [comment]
You have 2 asserts and you don't tell if you received any exception or simple one assert was the problem. Also please always tell the OrientDB version you're using. 

Why just don't using the Issue Template?

**Comment by kerner1000** [comment]
Hi lvca,
Both asserts fail, since both `isPresent()` and `isValid()` return true.
OrientDB version is 2.1.26.
Thanks!

**Comment by luigidellaquila** [comment]
Hi @kerner1000 

`isPresent()` and `isValid()` make assumptions on the RID values (eg. positive cluster ID and cluster position). When you delete a record, the ORID object you have is not changed, so it remains with the old values (you could also re-instantiate it manually with `new ORecordId(10, 50)` and it would be considered a valid and present record id).

To know if it was deleted, you have to do a `db.getRecord(rid)` and see the result.

If it returns OTransactionRealAbstract.DELETED_RECORD then the record was deleted in current transaction.

If it returns null then the record does not exist (anymore)

Thanks

Luigi

**Comment by kerner1000** [comment]
Hi @luigidellaquila
I test now if it was deleted by checking for `db.load(orid) == null`
many thanks for your explanations!
