### ISSUE TITLE
Orient DB 2.1.17 thread frozen on FileDispatcherImpl.pread0

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6226]
Yourkit stack trace below:

message threading-2 <--- Frozen for at least 1h 56m 56 sec
sun.nio.ch.FileDispatcherImpl.pread0(FileDescriptor, long, int, long) FileDispatcherImpl.java (native)
sun.nio.ch.FileDispatcherImpl.pread(FileDescriptor, long, int, long) FileDispatcherImpl.java:52
sun.nio.ch.IOUtil.readIntoNativeBuffer(FileDescriptor, ByteBuffer, long, NativeDispatcher) IOUtil.java:220
sun.nio.ch.IOUtil.read(FileDescriptor, ByteBuffer, long, NativeDispatcher) IOUtil.java:197
sun.nio.ch.FileChannelImpl.readInternal(ByteBuffer, long) FileChannelImpl.java:740
sun.nio.ch.FileChannelImpl.read(ByteBuffer, long) FileChannelImpl.java:726
com.orientechnologies.orient.core.storage.fs.OFileClassic.read(long, byte[], int, int) OFileClassic.java:140
com.orientechnologies.orient.core.storage.cache.local.OWOWCache.cacheFileContent(long, int, long, boolean) OWOWCache.java:1192
com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(long, long, boolean) OWOWCache.java:554
com.orientechnologies.orient.core.storage.cache.local.O2QCache.updateCache(long, long, boolean, OWriteCache) O2QCache.java:838
com.orientechnologies.orient.core.storage.cache.local.O2QCache.doLoad(long, long, boolean, boolean, OWriteCache) O2QCache.java:399
com.orientechnologies.orient.core.storage.cache.local.O2QCache.load(long, long, boolean, OWriteCache) O2QCache.java:362
com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(OAtomicOperation, long, long, boolean) ODurableComponent.java:131
com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(long) OPaginatedCluster.java:507
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OCluster, ORecordId) OAbstractPaginatedStorage.java:2076
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OCluster, ORecordId) OAbstractPaginatedStorage.java:1804
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(ORecordId, String, boolean, ORecordCallback) OAbstractPaginatedStorage.java:782
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(OStorage, ORecordId, String, boolean, ORecordVersion) ODatabaseDocumentTx.java:3114
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ORecordId, ORecord, ORecordVersion, String, boolean, boolean, boolean, OStorage$LOCKING_STRATEGY, ODatabaseDocumentTx$RecordReader) ODatabaseDocumentTx.java:1823
com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(ORID, ORecord, String, boolean) OTransactionNoTx.java:104
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ORID) ODatabaseDocumentTx.java:1567
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ORID) ODatabaseDocumentTx.java:121
com.orientechnologies.orient.core.id.ORecordId.getRecord() ORecordId.java:324
com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next() OrientElementIterator.java:62
com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next() OrientElementIterator.java:35
..
java.util.concurrent.Executors$RunnableAdapter.call() Executors.java:511
java.util.concurrent.FutureTask.runAndReset() FutureTask.java:308
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor$ScheduledFutureTask) ScheduledThreadPoolExecutor.java:180
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() ScheduledThreadPoolExecutor.java:294
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1142
java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:617
java.lang.Thread.run() Thread.java:745

**Comment by taburet** [comment]
Seem like there is a bug in certain JVM versions that may cause this issue. What JVM do you use?

**Comment by laa** [comment]
Hi @jamieb22 ,
Could you provide us with version of operation system and JVM so I will send you instructions how to setup tool which will gather diagnostic information for us.

**Comment by jamieb22** [comment]
Linux usa-f 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
We are using an embedded version of Orient. I hope the above helps!

**Comment by laa** [comment]
@jamieb22 If this situation happens again, could you do not restart the server but reach me through Skype so that we will investigate server state?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
