### ISSUE TITLE
OGlobalConfiguration.autoConfigDiskCacheSize throws NumberFormatException 

### ISSUE THREAD

**Issue by torfranz** [orientechnologies/orientdb#6227]
## Expected behavior and actual behavior
I use OrientDB v2.2.0 with the IKVM (.NET based) JAVA runtime and get NumberFormatException in function OGlobalConfiguration.autoConfigDiskCacheSize during the call `DISK_CACHE_SIZE.setValue(diskCacheInMB);` in the `if (maxDirectMemory == -1) `code path

diskCacheInMB is a long value and is derived from `jvmMaxMemory = Runtime.getRuntime().maxMemory(); `
The IKVM runtime returns long.MAX_VALUE for `Runtime.getRuntime().maxMemory();` which makes diskCacheInMB still out of range for integer values and finally causes the exception.

The expected behaviour would be that any long value is considered valid and is handled correctly.

## Steps to reproduce the problem
Due to the complexity to setup the IKVM environment the easiest to reproduce would be to replace the call `final long jvmMaxMemory = Runtime.getRuntime().maxMemory();` in OGlobalConfiguration.autoConfigDiskCacheSize with `final long jvmMaxMemory = Long.MAX_VALUE;`

### Runninng Mode
- [X] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.0 - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version (IKVM Runtime)
- [ ] 6
- [ ] 7
- [X] 8

**Comment by taburet** [comment]
Thank you very much for such a detailed bug report, I will fix it within next few days.

**Comment by taburet** [comment]
Fixed on develop branch. Heap memory size is capped to 2GB now for the purpose of disk cache auto configuration, if JVM reports unlimited heap size.
