### ISSUE TITLE
HTTP API to Create new Schema Class from JSON

### ISSUE THREAD

**Issue by lucafrosini** [orientechnologies/orientdb#6228]
## Expected behavior and actual behavior
I'm going to try to create new VertexType in Java.
As input I have the json representation of Vertex schema.
Unfortunately I didn't find a way to use json definition directly in Java, so I decided to use HTTP API.
With the following code the class MyVertex is created but has no parameters and the superclass is not set.

## Steps to reproduce the problem

```java
String className = "MyVertex";
String classDefinition = 
"{ \"class\": "
	+ "{ "
		+ "\"name\": \""+ className +"\","
		+ "\"superClass\": \"V\","
		+ "\"alias\": null,"
		+ "\"abstract\": false,"
		+ "\"properties\": ["
			+ "{"
				+ " \"name\": \"myProperty\","
				+ "\"type\": \"STRING\","
				+ "\"mandatory\": false,"
				+ "\"notNull\": false"
			+ "} "
		+ "]"
	+ "}"
+ "}";
		
URL postURL = new URL("http://localhost:2480/class/TestDB/"+className);
HttpURLConnection connection = (HttpURLConnection) postURL.openConnection();

String authString = "admin:admin";
byte[] authEncBytes = Base64.encode(authString.getBytes());
String authStringEnc = new String(authEncBytes);
connection.setRequestProperty("Authorization", "Basic " + authStringEnc);

connection.setRequestMethod(HTTPMethods.POST.toString());
connection.setDoOutput(true);

OutputStream outputStream = connection.getOutputStream();
try(BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(outputStream))){
	writer.append(classDefinition);
}
		
```

## Important Questions

Can you help me to understand why the schema is not created as expected?
Is it possible to pass a JSON representation directly to Java API?

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 2.2.0

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [x] 7
- [ ] 8

**Comment by lvca** [comment]
This is the doc for the POST/Class: http://orientdb.com/docs/last/OrientDB-REST.html#post---class. As you can see this syntax is not supported. Since you are using Java, why don't just using the Java API?

**Comment by lucafrosini** [comment]
Ok, now I understand.
I'm building a service using OrientDB as backend. In my service, I need to serialize and de-serialize the schema representation. I thought that the JSON schema got form GET method could be used as input in POST.

Do you have any suggestion do do it quickly or I have to create a JSON parser?

Thank in advance

**Comment by lvca** [comment]
Sure, use the POST command/ with create property + alter property commands.

**Comment by lucafrosini** [comment]
thanks again
