### ISSUE TITLE
Insufficient documentation for creating a document database

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#6232]
The following page does not have enough information about creating a document database and causes beginners (and experienced users) a lot of frustration:

[http://orientdb.com/docs/last/Document-API-Database.html](http://orientdb.com/docs/last/Document-API-Database.html)

- How do you create a database with a different admin account?
- If you don't specific a different admin account, what is the default username and password? I know it's "admin" "admin" but this is not in the documentation.  The example shows:
`db.open("admin", "admin_passwd");` but this will not work as the default password is actually "admin".
- How do you drop a database?  I know it's `db.drop()` but this is not in the documentation.
- The first code example has a typo:
`ODatabaseDocumentTx db = new ODatabaseDocumentTX("plocal:/tmp/test");` but TX should be Tx

**Comment by luigidellaquila** [comment]
Hi @odbuser2 

Thanks for reporting, I just updated the docs

https://github.com/orientechnologies/orientdb-docs/blob/master/Document-API-Database.md

I'm building the official documentation now

Thanks

Luigi
