### ISSUE TITLE
OCommandExecutorNotFoundException while using unionall

### ISSUE THREAD

**Issue by amyth** [orientechnologies/orientdb#6233]
## Expected behavior and actual behavior
I am trying to make a simple query with `unionall` function but I get the following error.

```
Error: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.unionall($a, $b)
	Storage URL="plocal:/tmp/db/konnect"
```

## Steps to reproduce the problem
```
orientdb {db=konnect}> begin
orientdb {db=konnect}> let $a = select from person where out("has").email in "user1@gmail.com"
orientdb {db=konnect}> let $b = select from person where out("has").email in "user2@gmail.com"
orientdb {db=konnect}> let $c = unionall($a, $b)
orientdb {db=konnect}> commit
```

### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.0 - Please specify last number: 

### Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [x] 7
- [ ] 8

**Comment by luigidellaquila** [comment]
Hi @amyth 

Try this:

```
orientdb {db=konnect}> begin
orientdb {db=konnect}> let $a = select from person where out("has").email in "user1@gmail.com"
orientdb {db=konnect}> let $b = select from person where out("has").email in "user2@gmail.com"
orientdb {db=konnect}> let $c = SELECT unionall($a, $b)
orientdb {db=konnect}> commit
```

Thanks

Luigi

**Comment by amyth** [comment]
@luigidellaquila Thanks so much for the response. It works absolutely fine if I use it with select. That was so dumb of me.
