### ISSUE TITLE
Server side warning when unsubscribing from live query

### ISSUE THREAD

**Issue by torfranz** [orientechnologies/orientdb#6235]
## Expected behavior and actual behavior
Unsubscribing from a live query outputs a warning in the server side console, like

> 2016-05-31 16:50:29:911 WARNI {db=GratefulDeadConcerts} Error on unsubscribing client [Class]

Expectation is to not get a warning. Btw, why is **WARNI** ouput instead of **WARNING** (typo?)

## Steps to reproduce the problem
- Connect to GratefulDeadConcerts db from OrientDB studio
- run `live select from V` (note the returned token)
- run `live unsubscribe -2077293922` (actually provide the token from previous step)
- check the server console output, the warning should be visible.

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.0 - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by luigidellaquila** [comment]
Hi @torfranz 

I just fixed it in develop branch, the fix will be available in 2.2.1.

The "WARNI" was due to the log configuration, you can change it from the /config folder if you want.

Anyway, please consider that Studio does not support live queries.

Thanks

Luigi
