### ISSUE TITLE
OrientDB cannot open a local database inside a folder containing commas

### ISSUE THREAD

**Issue by nuixkeith** [orientechnologies/orientdb#6239]
## Expected behavior and actual behavior
If I try to open a local OrientDB database in a path such as the following I should be able to do so, since the graph DB name itself does not contain a comma (only a folder in the path does):

C:/my, path/Stores/Graph Database/graphf28b0f4ca68f41cc88cbb40af2458c5f

If I try to do this OrientDB throws the following exception:

Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'plocal:C:/my, path/Stores/Graph Database/graphf28b0f4ca68f41cc88cbb40af2458c5f'
 
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database: C:/my, path/Stores/Graph Database/graphf28b0f4ca68f41cc88cbb40af2458c5f. Current location is: C:\Program Files\Nuix\Nuix 7.0\.
 
Caused by: java.lang.IllegalArgumentException: Invalid character in storage name: graphf28b0f4ca68f41cc88cbb40af2458c5f

This is coming from line 87 of OStorageAbstract.

## Steps to reproduce the problem

Try to open or create a case with a 'url' that points to a path containing a comma such as:

plocal:C:/my, path/Stores/Graph Database/graphf28b0f4ca68f41cc88cbb40af2458c5f

## Important Questions

Is there a work-around to get the connection working?  

### Runninng Mode
- [X ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [X ] v2.1.x - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X ] 8

**Comment by lvca** [comment]
Sorry, this is not supported. However, you could encode any special characters like comma. Can't you just rename your path?

**Comment by david-sitsky** [comment]
What are the supported encoding/decoding methods?  The code had mentions of using backslash encodings but the exception raised in the code (line 87 of OStorageAbstract) didn't seem to do any in that area?

Due to the way this component is used in a product, sometimes the path is not under our control.

**Comment by lvca** [comment]
I don't know if there is a std for this, but you could have something like -comma- to encode commas. Example:

    C:/my-comma- path/Stores/Graph Database/graphf28b0f4ca68f41cc88cbb40af2458c5f

**Comment by nuixkeith** [comment]
Our customers want to put graph DBs into their existing valid file paths alongside other data and telling them to restructure their entire file system is something we would rather not do.

Is it not possible to add in support for escaping commas inside the file path? I understand you have a restriction on database names not having commas, but on line 87 of OStorageAbstract it is checking the entire file path (on line 87 name is the entire file path) instead of the database name (this.name contains only the database name).

**Comment by laa** [comment]
Hi guys, we will fix it.

**Comment by nuixkeith** [comment]
Great, thanks for that

**Comment by taburet** [comment]
Fixed on 2.1.x and develop branches. Added tests to verify OStorageAbstract allows commas in paths but not in the names.
