### ISSUE TITLE
False duplicate record exception when using Graph API

### ISSUE THREAD

**Issue by clepelli** [orientechnologies/orientdb#6243]
## Expected behavior and actual behavior
I want to create two vertices connected by an edge in one transaction. The vertex class has an index on a field named "label". I should be able to set up the indexed property "label" (with different values) just before the commit of the transaction but an ODuplicateRecordException is triggered in this case.

I have been impacted by this issue when migrating to v2.2.0, because of the new default setting for indices "ignoreNullValues", explained in [this doc](https://github.com/orientechnologies/orientdb-docs/blob/master/Release-2.2.0.md)
I am now setting ignoreNullValues to true on index creation as a temporary workaround.

## Steps to reproduce the problem
1) Transaction begins
2) Create the 2 vertices with addVertex(myClass).
3) Call firstVertex.addEdge(edgeName, secondVertex)
4) Set up the labels : 
firstVertex.setProperty(label, "firstLabel");
secondVertex.setProperty(label, "secondLabel");
5) Commit

### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by taburet** [comment]
There are two bugs affecting the expected behaviour in this issue, the one with null values mishandling while updating indexes, the other one is split in the separate #6271 issue. Will work on the first one under this issue.

**Comment by taburet** [comment]
Fixed on 2.1.x, 2.2.x and develop branches.
