### ISSUE TITLE
Can't get rid of MaxDirectMemorySize warning

### ISSUE THREAD

**Issue by vlasni** [orientechnologies/orientdb#6244]
# This started to happen with community v2.2.0
When deploying web app to tomcat 8, I started to see the warnings below, even when the values are apparently correctly set in configuration:
```
02-Jun-2016 10:29:36.370 INFO [localhost-startStop-3] com.orientechnologies.common.log.OLogManager.log OrientDB auto-config DISKCACHE=1,877MB (heap=1,877MB direct=1,877MB os=7,982MB), assuming maximum direct memory size equals to maximum JVM heap size
02-Jun-2016 10:29:36.399 WARNING [localhost-startStop-3] com.orientechnologies.common.log.OLogManager.log MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=7982m option when you start the JVM.
02-Jun-2016 10:29:36.402 WARNING [localhost-startStop-3] com.orientechnologies.common.log.OLogManager.log MBean with name com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean has already registered. Probably your system was not shutdown correctly or you have several running applications which use OrientDB engine inside
02-Jun-2016 10:29:36.403 WARNING [localhost-startStop-3] com.orientechnologies.common.log.OLogManager.log MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=7982m option when you start the JVM.
02-Jun-2016 10:29:36.416 WARNING [localhost-startStop-3] com.orientechnologies.common.log.OLogManager.log MBean with name com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean has already registered. Probably your system was not shutdown correctly or you have several running applications which use OrientDB engine inside
02-Jun-2016 10:29:36.475 INFO [localhost-startStop-3] com.orientechnologies.common.log.OLogManager.log Registered the new available server 'dev.vlasni.com:2424'
```

## server.sh
`JAVA_OPTS_SCRIPT="-Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -XX:+AggressiveOpts -XX:CompileThreshold=200"
`
`ORIENTDB_OPTS_MEMORY="-Xms768m -Xmx768m"`
`MAXDISKCACHE="-Dstorage.diskCache.bufferSize=5376"`

Is there something I am missing in configuration that produces these warnings? 
Any help would be greatly appreciated.

### Runninng Mode
- [ ] Remote

### OrientDB Version
- [ ] v2.2.0

### Operating System
- [ ] Linux

### Java Version
- [ ] 8

Thanks

**Comment by taburet** [comment]
Please attach to the JVM instance using YourKit or VisualVM and inspect the actual JVM arguments. I suspect they some how got lost during JVM startup.

**Comment by vlasni** [comment]
@taburet 
I haven't found a moment to provide what you're asking. In the meantime, please check the output of HTOP command:

![selection_031](https://cloud.githubusercontent.com/assets/19346364/15761829/b87dc94a-28f0-11e6-8191-32f4bb404351.png)

As you can see there, it is reporting to be using -XX:MaxDirectMemorySize=7982m (I changed the value in config in order to see if the issue was misconfiguration).
Is this useful?

**Comment by vlasni** [comment]
@taburet 
You are right: the logs I see are from tomcat web app.
Thanks for your assistance, I don't mind you closing this one if these warnings can be safely ignored.

Adrian
