### ISSUE TITLE
Command Cache: enhancements

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6247]
From the webinar: Can we enable command cache for selective queries? Also can we explicitly query the DB if command cache is enabled ?

**Comment by lvca** [comment]
@luigidellaquila can we query the database with `metadata` to know this?

**Comment by luigidellaquila** [comment]
I think the question was not related to getting info from the db, but just to enable command cache selectively and/or bypass it.
Anyway, in v3.0 the command cache has to be re-written

Thanks

Luigi
