### ISSUE TITLE
add natural langage processing

### ISSUE THREAD

**Issue by lastnod** [orientechnologies/orientdb#6253]
## Expected behavior and actual behavior

the possibility to do queries with natural langage
there is a lot of library to do natural langage processing
[https://en.wikipedia.org/wiki/List_of_natural_language_processing_toolkits](https://en.wikipedia.org/wiki/List_of_natural_language_processing_toolkits)

**Comment by smolinari** [comment]
Can you explain how your suggestion would be more beneficial than the current SQL solution? Can you give some examples of how natural language can work better or be more efficient for the developer? What is the problem trying to be solved? Are there any other databases doing this?

Scott

**Comment by lvca** [comment]
Not relevant, closing it.
