### ISSUE TITLE
Help on solving query

### ISSUE THREAD

**Issue by adrian-gomez-ar** [orientechnologies/orientdb#6254]
I have a graph as depicted below:

![tarjetas1 1](https://cloud.githubusercontent.com/assets/19346364/15779183/31b2969e-2971-11e6-8898-42113672891a.png)

1) a Consumer can have "isClientOf" edges to 0..N Customer
2) a Consumer can have "isClientOf" edges to 0..1 Vendor.
3) a Consumer can have "installs" edges to 0..N Installation.

Note: if a Consumer does not have "isClientOf" Customer, then it will always have "isClientOf" Vendor.

What I need to do is:
Count Consumers that have "isClientOf" for a given Vendor and do not have "isClientOf" for a given Customer and do not have "installs".

The query I came up with is:

```
select count(*) from (
  select expand($diff)
  let
  $cons = (select @rid as consId from Consumer where deleted=false),
  $cust = (select distinct(consId) as consId from (
              select expand($c) as consId
              let
              $a = (select inE('isClientOf').outV()[deleted=false] as consId from #37:19 unwind consId ),
              $b = (select distinct(out) as consId from installs where active=true and out.deleted=false),
              $c = unionall($a, $b)
          )
        ),
  $diff = difference($cons, $cust)
)

```

The query above is not working properly, probably related to #5294.
So, the workaround I found is:

```
select count(*) from (
  select expand($diff)
  let
  $cons = (select @rid as consId from Consumer where deleted=false),
  $cust = (select distinct(consId) as consId from (
              select expand($c) as consId
              let
              $a = (select inE('isClientOf').outV()[deleted=false] as consId from #37:19 unwind consId ),
              $b = (select distinct(out) as consId from installs where active=true and out.deleted=false),
              $c = unionall($a, $b)
          )
        ),
  $diff = (select from $cons where consId not in (select from $cust))
)

```

Although the result of this query is correct, it's extremely slow (takes 80 secs).

I was trying a different approach to get those Consumer with "isClientOf" Vendor as follows:

`select inE('isClientOf').outV()[deleted=false] as consId from #33:1 unwind consId`

but it takes forever and haven't been able to get it to run.

Some stats:
- Consumer: 165k records
- Customer: 40 records
- Vendor: 2 records
- isClientOf: 165k records

So, I'd really appreciate any help/tips on addressing such a query as it has become a bottleneck to us.
Thanks in advance.
### Runninng Mode
- [ ] Remote
### OrientDB Version
- [ ] v2.2.0
### Operating System
- [ ] Linux
### Java Version
- [ ] 8

**Comment by vlasni** [comment]
Update:
Tried a different approach as follows:

```
select count(*) as count from ( 
	select expand($res) 
	let 
	$vl = (select expand(inE('isClientOf').outV()[deleted=false]) from #33:1), 
	$cust = (select expand(inE('isClientOf').outV()[deleted=false]) from #37:19), 
	$inst = (select expand(out) from installs where active=true and out.deleted=false), 
	$diff = (select from $vl where @rid not in($cust)), 
	$res = (select from $diff where @rid not in($inst))
) 

```
This one performs better than the former one but still it is really slow: it takes 24 secs

**Comment by smolinari** [comment]
I am no expert, so I'll ask a question. Is the "isClientOf" the same edge class both for Customers and Vendors? If yes, how can that relationship be the same one and yet resolve to show differences efficiently? 

Scott

**Comment by vlasni** [comment]
@smolinari 
sorry for the delay.
the object model is: 
- Customer extends Business
- Vendor extends Business
- Business extends AbstractPojo
- AbstractPojo extends V

so, to answer your question: a Business can be a Customer or a Vendor, but not both. The isClientOf edge actually targets Business.
Sorry for the confusion

**Comment by luigidellaquila** [comment]
Hi @vlasni 

you can try the following
```
select in('isClientOf')[
    deleted = false 
    and outE("installs")[active=true].size() = 0 
].size() from <VENDOR_RID>
where not ( in('isClientOf') contains <CUSTOMER_RID> )
```
but your query forces you to traverse all the graph, so I'm afraid it won't be light fast, especially at the first executions with cold cache. The NOT operations are quite expensive in general, and your query mostly relies on them

Thanks

Luigi

**Comment by smolinari** [comment]
Hehe...sorry, but I am still confused. From your image of your graph, you have a "Consumer", yet you don't mention that above in your model. 

Also, in your query, you use expand. If you only need to count results, you shouldn't need to expand them. I believe expand only pulls in the fields of those vertices.

http://orientdb.com/docs/master/SQL-Functions.html#expand   

Check out the count example below, maybe it might give you an idea of how to get what you want. 

```
  select sum($a[0].count,$b[0].count) 
    let $a = (select count(*) from e), 
        $b = (select count(*) from v)
```

Again, I am not the most experienced with ODB, so take what I say with a grain of salt.

Scott
