### ISSUE TITLE
Distributed Auto-Sharding (DHT)

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6256]
After implemented the Autosharded index (#4326), what is missing to work distributed as DHT is:
- [x] Let to the `SYNC CLUSTER` command to copy also the index files related to the cluster
- [ ] Support a new cfg for class like: `{"classes":{"*":{"copies":2}}}` to declare the number of copies to keep per cluster/partition
- [ ] Improve the auto-rebalance of the clusters to always assure the declared number of copies per cluster/partition
- [ ] Support auto-sharding on the client side by letting the client to send the requests directly to the interested server.
- [ ] Very Nice to Have: don't block write operations against a cluster during the copy/move
- [ ] API to expose to the new SQL Engine to use the sharding properly
- [ ] Stateful connections between nodes, for distributed query execution. The new SQL Engine has to send partial execution plans to multiple nodes and iterate the results page by page

**Comment by mmacfadden** [comment]
+1
