### ISSUE TITLE
[ OrientDB v2.2.0 ] Record Create no more honors Class value

### ISSUE THREAD

**Issue by Ostico** [orientechnologies/orientdb#6258]
When a CREATE CLASS command is issued, the command returns an INT ( the cluster ID ):
```python
            cluster_id = client.command( "create class my_class extends V" )[0]
            assert cluster_id != 0
            assert cluster_id == 11
```
After i send a record create:
```python
    rec = { '@my_class': { 'alloggio': 'casa', 'lavoro': 'ufficio', 'vacanza': 'mare' } }
    rec_position = client.record_create( cluster_id, rec )

#; OrientDB log
#; -----------------

# Reading byte (1 byte)... [OChannelBinaryServer]
# Read byte: 31 [OChannelBinaryServer]
# Reading int (4 bytes)... [OChannelBinaryServer]
# Read int: 9 [OChannelBinaryServer]


# Reading short (2 bytes)... [OChannelBinaryServer]
# Read short: 11 [OChannelBinaryServer]


# Reading chunk of bytes. Reading chunk length as int (4 bytes)... [OChannelBinaryServer]
# Read chunk lenght: 56 [OChannelBinaryServer]


# Reading 56 bytes... [OChannelBinaryServer]
# Read 56 bytes: my_class@lavoro:"ufficio",alloggio:"casa",vacanza:"mare"


# [OChannelBinaryServer]
# Reading byte (1 byte)... [OChannelBinaryServer]
# Read byte: 100 [OChannelBinaryServer]
# Reading byte (1 byte)... [OChannelBinaryServer]
# Read byte: 0 [OChannelBinaryServer]
# Writing byte (1 byte): 0 [OChannelBinaryServer]
# Writing int (4 bytes): 9 [OChannelBinaryServer]
# Writing short (2 bytes): 11 [OChannelBinaryServer]
# Writing long (8 bytes): 0 [OChannelBinaryServer]
# Writing int (4 bytes): 1 [OChannelBinaryServer]
# Writing int (4 bytes): 0 [OChannelBinaryServer]
```
From the console i found the wrong class inside OrientDB:

```
orientdb {db=test_commands}> select * from V;
+----+-----+------+-------+--------+-------+
|#   |@RID |@CLASS|lavoro |alloggio|vacanza|
+----+-----+------+-------+--------+-------+
|0   |#11:0|V     |ufficio|casa    |mare   |
+----+-----+------+-------+--------+-------+

orientdb {db=test_commands}> list classes;


CLASSES
+----+-----------+-------------+---------------------------------------------------------+-----+
|#   |NAME       |SUPER-CLASSES|CLUSTERS                                                 |COUNT|
+----+-----------+-------------+---------------------------------------------------------+-----+
|0   |E          |             |e(13),e_1(14),e_2(15),e_3(16)                            |    0|
|1   |my_class   |[V]          |my_class(17),my_class_1(18),my_class_2(19),my_class_3(20)|    1|
|2   |OFunction  |             |ofunction(6)                                             |    0|
|3   |OIdentity  |             |-                                                        |    0|
|4   |ORestricted|             |-                                                        |    0|
|5   |ORole      |[OIdentity]  |orole(4)                                                 |    3|
|6   |OSchedule  |             |oschedule(8)                                             |    0|
|7   |OSequence  |             |osequence(7)                                             |    0|
|8   |OTriggered |             |-                                                        |    0|
|9   |OUser      |[OIdentity]  |ouser(5)                                                 |    3|
|10  |V          |             |v(9),v_1(10),v_2(11),v_3(12)                             |    1|
+----+-----------+-------------+---------------------------------------------------------+-----+
|    |TOTAL      |             |                                                         |    8|
+----+-----------+-------------+---------------------------------------------------------+-----+
```

So, ```create class my_class extends V``` does not return the right ClusterID, it return 11 instead the right number.

Seems that Cluster ID in this new version is sharded and not unique and does not agree to the class ID. There is a way to know exactly the Cluster ID of the new created class?

**Comment by smolinari** [comment]
This probably has something to do with the new "cluster per core" technology added in 2.2. 

>By default, OrientDB creates one cluster for each Class. Starting from v2.2, OrientDB automatically creates multiple clusters per each class (the number of clusters created is equals to the number of CPU's cores available on the server) to improve using of parallelism.

http://orientdb.com/docs/2.1/Tutorial-Clusters.html#understanding-clusters

As a possible short term workaround, you can also turn this off with 

`ALTER DATABASE MINIMUMCLUSTERS 1`

Scott

**Comment by lvca** [comment]
@Ostico the `CREATE CLASS` command always returned the total classes in database. Probably before 2.2 it worked because, as @smolinari suggested, the classes/clusters number were always the same by default.

**Comment by smolinari** [comment]
@lvca - The issue is, however, the returned cluster number of the "My_Class" cluster is now a "parent cluster" (for a lack of a better name) under "V", which is cluster "11" or "v_2". Whereas the `CREATE CLASS` should return either one or all of the new clusters numbers for "My_Class" (i.e. 17, 18, 19 or 20). 

I'd say this is a bug, wouldn't you?

Scott

**Comment by lvca** [comment]
The CREATE CLASS command historically always returned the number of all the classes present in the database. I know, it's worthless as information.

**Comment by smolinari** [comment]
Hehe...so it was just a coincidence, that the total number was also the number of the last cluster created too. Oh boy. If people used that return data for any kind of logic, I can see them now having real issues. 

Scott

**Comment by Ostico** [comment]
Tnx @lvca , now it's clear.
So for my question, there is a way to know exactly the Cluster ID of the new created class?

I need to know how to access to a record with CRUD methods.

**Comment by lvca** [comment]
A class could have multiple clusters (in v2.2 this is the new default), so maybe you're interested to get the list of clusters, right? You have this information in the schema.

Question: why do you need the cluster id for CRUD operation? Usually CRUD works with classes, not cluster. If you just specify the class, it's the OrientDB server that assigns the right cluster automatically.

**Comment by Ostico** [comment]
For example, when i create a new class and i want add a record inside this class by the *record_create* method i need the cluster ID:
http://orientdb.com/docs/2.1/Network-Binary-Protocol.html#request-record-create 

This means that i must query for the new schema structure ( reload ) **search for the class name** and use a random cluster from the list ( suppose we have 4 cluster for the new class ) and put the new record inside.

But, the schema structure does not preserve the class name ( only the first one has the same name **test** ):
```python
#> create class test extends V;
#....
for t in client.db_reload():
    print( t )

# 'ofunction': 6
# 'manindex': 2
# 'internal': 0
# 'osequence': 7
# 'index': 1
# 'default': 3
# 'oschedule': 8
# 'ouser': 5
# 'orole': 4
# 'e': 13
# 'e_1': 14
# 'e_2': 15
# 'e_3': 16
# 'v': 9
# 'v_1': 10
# 'v_2': 11
# 'v_3': 12
# 'test': 17
# 'test_1': 18
# 'test_2': 19
# 'test_3': 20
```

**Comment by lvca** [comment]
You can pass the `cluster-id` only if you want to force it, otherwise use always -1. The docs are not clear about it, trying to improve them. Anyway in 95% of the cases let to the OrientDB server to pick the right cluster ;-)

**Comment by Ostico** [comment]
I can not use -1 as cluster-id because i must address the record to the right class, this is an example:
```php
        $client->command( "create class Test extends V" );
```
The created cluster-ids are  [ 17, 18, 19, 20 ] but i don't know them because the previous command returns 11
````
CLASSES
+----+-----------+-------------+-----------------------------------------+-----+
|#   |NAME       |SUPER-CLASSES|CLUSTERS                                 |COUNT|
+----+-----------+-------------+-----------------------------------------+-----+
|0   |E          |             |e(13),e_1(14),e_2(15),e_3(16)            |    0|
|1   |OFunction  |             |ofunction(6)                             |    0|
|2   |OIdentity  |             |-                                        |    0|
|3   |ORestricted|             |-                                        |    0|
|4   |ORole      |[OIdentity]  |orole(4)                                 |    3|
|5   |OSchedule  |             |oschedule(8)                             |    0|
|6   |OSequence  |             |osequence(7)                             |    0|
|7   |OTriggered |             |-                                        |    0|
|8   |OUser      |[OIdentity]  |ouser(5)                                 |    3|
|9   |Test       |[V]          |test(17),test_1(18),test_2(19),test_3(20)|    0|
|10  |V          |             |v(9),v_1(10),v_2(11),v_3(12)             |    1|
+----+-----------+-------------+-----------------------------------------+-----+
|    |TOTAL      |             |                                         |    7|
+----+-----------+-------------+-----------------------------------------+-----+
```
```php
        // i don't know the cluster-id so i can not insert the record
        $rec = ( new Record() )->setOData( [] )->setRid( new ID( ??? ) );
        $record = $client->recordCreate( $rec );
```

I think that this new functionality brokes the intent of the record create/update/insert methods.

I think that the right behaviour should be that create class command should return the list of the new created cluster IDs for the class.

The names of the class also, ```|9   |Test       |[V]          |test(17),test_1(18),test_2(19),test_3(20)|    0|``` should not be postfixed by _x but should maintain the same name and are referenced as list.
Having different names makes impossible to check the cluster names.
```
|9   |Test       |[V]          | [ 17, 18, 19, 20 ] |    0|
```

**Comment by lvca** [comment]
You should create the record with the @class inside, so OrientDB can assign the right cluster at the server side. This is fundamental also for the HA: the cluster is specified by the server.

So forget about the cluster Id (use -1) and insert this record:

"@class":"V",name:"jay",surname:"Miner"

You will see the record is created in one of the available clusters under "V" class.

**Comment by rdelangh** [comment]
"Why inserting a record explicitly into one specific cluster?"

Two mail goals we have for using such practice, are:
- have clusters created by ourselves, during which we give them a name that reflects some range-criterium of the records in it; for example: a clustername in which a date is a substring of the name ("mycluster_20160801"), can indicate a particular date-range for its records ("20160801" = Aug-1 2016); when we then want to query for records we know to be in that date-range, we can select directly from that single cluster knowing its name
- we want a fast and 'economic' method to cleanup old records, without having to perform a costly "DELETE ... WHERE <date-criterium>"; our goal is to "DROP CLUSTER clustername_with_daterange" to get rid very quickly of all records of a particular daterange for which that cluster was created

Why would this impact the HA ? 
I understood (cfr http://orientdb.com/docs/last/Distributed-Sharding.html) that we can specify on which servers a new cluster must be replicated, no ? If true, then we can implement our own logic of replication of clusters among the servers, during their creation. Eg : a new cluster on server A1 in datacenter A and on server B2 in datacenter B ; and so on (kind of round-robin between datacenters)

**Comment by smolinari** [comment]
Can't you use plain old classes for the two main goals you have? Instead of the word "cluster" add "class" and ODB does exactly what you want.

Scott
