### ISSUE TITLE
OObjectLazyList.listIterator() should return customized ListIterator

### ISSUE THREAD

**Issue by scg03** [orientechnologies/orientdb#6265]
## Expected behavior and actual behavior

OObjectLazyList list;
// load a non-empty list from the db;
assert list.listIterator().next() !=null;

## Important Questions

OObjectLazyList.listIterator() should return a customized ListIterator rather than the one defined in ArrayList.

### Runninng Mode
Embedded, using PLOCAL access mode

### OrientDB Version
v2.1.15

### Operating System
Linux

### Java Version
8

**Comment by luigidellaquila** [comment]
Hi @scg03 

What's the reason for this request? Is there a specific need behind it?

Thanks

Luigi

**Comment by scg03** [comment]
Hi,

Never mind. I modified my code to use List.iterator() instead of
List.listIterator().
Previously when using List.listIterator(), the Iterator.next() failed to
load data from the database.

Thanks,
Chenguang

**Comment by luigidellaquila** [comment]
OK thanks @scg03 

Closing

Luigi
