### ISSUE TITLE
Import using java api does not preserve rids

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#6266]
## Steps to reproduce the problem

I have the following code:

OCommandOutputListener listener = new OCommandOutputListener() {
				public void onMessage(String iText) {
					System.out.println(iText);	
				}				
			};
			
ODatabaseImport importing = new ODatabaseImport(db, "tdan.gz", listener);
importing.setPreserveRids(true);
importing.setPreserveClusterIDs(true);
importing.importDatabase();
importing.close();

## Expected behavior and actual behavior
It seems like the following lines have no effect
importing.setPreserveRids(true);
importing.setPreserveClusterIDs(true);
I would expect the rids to stay the same as in the origional db from which i did the export

### Runninng Mode
Remote

### Misc
single db

### OrientDB Version
2.1.17

### Operating System
Linux

### Java Version
8

**Comment by tglman** [comment]
hi @temilmg,

The option for preserve rids has been removed in more recent version, because is not possible force rid with plocal structure.

closing because impossible to fix.
