### ISSUE TITLE
storage.diskCache.bufferSize does not take effect?

### ISSUE THREAD

**Issue by quantonganh** [orientechnologies/orientdb#6270]
## Expected behavior and actual behavior

The upstart script:

```
script
exec /usr/bin/java -server -Xms384m -Xmx384m -XX:PermSize=128m -XX:MaxPermSize=128m -Dstorage.diskCache.bufferSize=1024 \
    -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled \
    -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError \
    -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 \
    -Djava.util.logging.config.file=/etc/orientdb/logging.properties \
    -Dorientdb.config.file=/etc/orientdb/config.xml \
    -Dorientdb.www.path=/usr/local/orientdb-community-2.1.5/www \
    -Dorientdb.build.number="salt@2.1.5" \
    -cp "/usr/local/orientdb-community-2.1.5/2.1.5/lib/orientdb-server-2.1.5.jar:/usr/local/orientdb-community-2.1.5/lib/*" \
    com.orientechnologies.orient.server.OServerMain
end script
```

Expected behavior: `storage.diskCache.bufferSize` should take effect instead of calling [autoConfigDiskCacheSize](https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/config/OGlobalConfiguration.java#L774).

## Steps to reproduce the problem

Install OrientDB 2.1.5 on a VM with 2GB memory.

## Important Questions

Due to this: https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/config/OGlobalConfiguration.java#L784

`diskCacheInMB`  is always < 0 if `osMemory`  <= 2GB.
So, we got this warning so often:

>Not enough physical memory available for DISKCACHE: 2,001MB (heap=592MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB

The question is: why `-Dstorage.diskCache.bufferSize` does not take effect?

```
orientdb-upstart:  + storage.diskCache.bufferSize = 1024
```

I set it to 1GB but for some reasons: https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/config/OGlobalConfiguration.java#L759

`System.getProperty(DISK_CACHE_SIZE.key) == null` and `autoConfigDiskCacheSize` was called.

### Runninng Mode
- [x ] Embedded, using PLOCAL access mode

### OrientDB Version
- [x ] v2.1.5

### Operating System
- [x ] Linux

### Java Version
- [x ] 7

**Comment by laa** [comment]
Tested on 2.2.x , all is fixed.
