### ISSUE TITLE
Associated vertices considered new, not updated, by ODirtyManager while adding edge

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6271]
For some reason `ODirtyManager` thinks associated vertices are new, not updated, while connecting them with the edge using graph API. As a result vertices got reinserted into indexes/storage, screwing changes commit to unique ones.

I will create a branch with the attached test case in a few minutes.

**Comment by taburet** [comment]
Added issue-6271 branch containing the test case.

**Comment by tglman** [comment]
fixed and merged in develop, closing
