### ISSUE TITLE
Syntax enhancement to PUT JSON data to a MAP property (embedded or link)

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientdb#6273]
Both of the following syntax options work (the first completely replaces the content of the Samples EMBEDDEDMAP property with the supplied JSON data, while the second adds a new item):
`update #23:0 set content {"Samples":{"00":{"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}}}
`

`update #23:0 put Samples = "00", {"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}`

The following syntax fails (the intent is to add a new item to the Samples EMBEDDEDMAP property):
`update #23:0 put content {"Samples":{"00":{"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}}}
`

Would it not make sense to support the failing syntax? It seems much more consistent with the corresponding set (for complete property replacement).

Also, using the working PUT (second example above), how would you add more than one new item at a time? How to do this using the failing syntax would be obvious. In fact, it is supported as expected by the SET syntax.

Runninng Mode: Embedded, using PLOCAL access mode, executing SQL in Studio

OrientDB Version: 2.2.0 on Linux (CentOS)

Java Version:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by Eric24** [comment]
Strange things happening... Yesterday, I was able to execute this statement (in Studio):

`update #23:0 set content {"Samples":{"00":{"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}}}`

But today, it fails (the parser complains about not expecting "update in column 1"). I can still execute the "put" version just fine. Is there something wrong with this syntax?

The only difference I'm aware of between yesterday and today is that I downloaded the GeoSpatial add-on jar file and restarted the server (which appears to have worked as expected). Could that somehow affect this?

**Comment by mmacfadden** [comment]
@Eric24 Hello.  would the following query work for you:

```update #23:0 set content.Samples = {"00":{"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}}```

Or something to that effect?  This should add a new entry to the map?  Full disclosure, I haven't tried this exact query, but we do something like it quite often.

**Comment by Eric24** [comment]
So yes, this works ('content' not needed here), and it works with one or multiple items:
`update #23:0 set Samples = {"01":{"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}}`
But this does not (I originally thought it did, but I can not make any version of it work again, so I must have been mistaken):
`update #23:0 set content {"Samples":{"01":{"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}}}`
The idea of the latter is that it allows several individual properties can be set at once as part of a JSON object, rather than using itemized property lists.

But more importantly, this does not work:
`update #23:0 put Samples = {"01":{"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}}`
Nor does this:
`update #23:0 put content {"Samples":{"01":{"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}}}`

This is the only syntax I can find that works with put:
`update #23:0 put Samples = "00", {"@type":"d", "@class":"VSample", "Count": 1, "Scale": 0, "Sum16": 12345}`
And it doesn't allow multiple items to be put at once.
