### ISSUE TITLE
Error message in orientdb studo

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#6275]
![orientdbstudiobug2](https://cloud.githubusercontent.com/assets/3005511/15930129/7a4b18e2-2e51-11e6-8758-f041f77aa280.png)

## Expected behavior and actual behavior
Error message must not get so big that you cant close the dialog. 
To continue you need to refresh the browser and then you loose the queries you were working on.

## Steps to reproduce the problem
I forgot to report this bug a couple of weeks ago when i encountered it, so I cant remember the query that triggered it, but i did take a screenshot at the time. See attached file.
Maybe limit the dialog dimensions and add scroll or better yet remove all the error tags displayed.

### Runninng Mode
studio

### OrientDB Version
- v2.1.17 

### Operating System
-  Linux

-### Java Version
- 8

**Comment by maggiolo00** [comment]
hi @temilmg 
we did fix this in 2.2.x. Let me check if can back port it.

**Comment by temilmg** [comment]
Its really just a minor issue which rarely happens, so its not a big deal for me if you cant back port it.

**Comment by maggiolo00** [comment]
You can use the browser zoom when it happens :D

**Comment by temilmg** [comment]
Yes good idea, thank you!

**Comment by maggiolo00** [comment]
@temilmg 
Fixed in 2.2.x
