### ISSUE TITLE
Can not CREATE / ALTER / DROP SEQUENCE in OCommandScript

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#6278]
## Expected behavior and actual behavior
A statement such as ```CREATE SEQUENCE mySeq TYPE ORDERED``` should be able to be executed but instead throws an exception:

```
Invalid script:Encountered " <CREATE> "CREATE "" at line 1, column 1.
Was expecting one of:
    <IF> ...
    ";" ...
    <IF> ...
```

The issue here is actually with the parser.  The parseScript method defined in the Grammar contains the following:

```
(
        LOOKAHEAD(StatementSemicolon())
        last = StatementSemicolon() {result.add(last);}
        |
        last = IfStatement() {result.add(last);}
        |
        <SEMICOLON>
    )*
```

The key here is the StatementSemicolon() call in the LOOKAHEAD which is defined as follows:

```
OStatement StatementSemicolon():
{OStatement result = null;}
{
    result = StatementInternal()
    <SEMICOLON>
    {return result;}
}
```

The issue is that StatementInternal has entries for CreateClassStatement(), CreatePropertyStatement(), etc.  But CreateSequenceStatement() does not exist in the grammar.  This means that a CREATE SEQUENCE statement can never be valid in a script.

I then noticed that the work "SEQUENCE" is not even a token defined in the grammar.  This seemed odd to me since I can run the following:

```
db.command(new OCommandSQL("CREATE SEQUENCE didSeq TYPE ORDERED;")).execute();
```

So the "SEQUENCE" is being parsed.  Upon investigation of the ```OCommandExecutorSQLCreateSequence.parse(...)``` method, I noticed that it appears to be skipping the "preParse" step.  In most all other Executors the top of the parse method looks like this:

```Java
   String queryText = textRequest.getText();
    String originalQuery = queryText;
    try {
      queryText = preParse(queryText, iRequest);
      textRequest.setText(queryText);
```

This engages the new parser.  However this step was skipped for the Create Sequence Executor.  So essentially when running a OCommandSQL, the parser is never used, so the sequence works.  But this fails when processing a OCommandScript since the Parser is invoked.  This also applies for ALTERing and DROPing a sequence.  Using a sequence is fine since that is treated as a function. 

The CREATE / ALTER / DELETE SEQUENCE syntax needs be added to the parser.

## Steps to reproduce the problem

```Java
db.command(new OCommandScript("CREATE SEQUENCE didSeq TYPE ORDERED;")).execute();
```

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [X] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [X] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

Thank you for pointing it out, I'm fixing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

I just pushed a fix on develop branch, it will be released with 2.2.1

Thanks

Luigi

**Comment by mmacfadden** [comment]
@luigidellaquila Great thanks!  I hope my detailed investigations on these types of issues are helpful.  I am also willing to help fix the issues after you guys confirm that I have it right!

**Comment by luigidellaquila** [comment]
@mmacfadden they are indeed :-)

Thanks

Luigi
