### ISSUE TITLE
OrientDB Backup/Recovery/Data Purging script and documentation

### ISSUE THREAD

**Issue by liuchuan-ncs** [orientechnologies/orientdb#6279]
Hi,

I'd request for documentation/script for OrientDB backup/recovery/purging. This is required in the operational environment as part of customer's requirement. Thanks!

**Comment by lvca** [comment]
To purge data, you could always use the OrientDB SCHEDULER. Look at this example: http://orientdb.com/docs/last/Scheduler.html#1-create-a-function
