### ISSUE TITLE
.OConcurrentModificationException: Cannot UPDATE the record #0:1 because the version is not the latest. 

### ISSUE THREAD

**Issue by Vannav** [orientechnologies/orientdb#6280]
## Expected behavior and actual behavior

Creating a new class in Orient Studio does fail [Screenshot](http://i.imgur.com/JB7wn1F.png)

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 

### Operating System
- [x] Linux (Server)
- [ ] MacOSX
- [x] Windows (Client)
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by maggiolo00** [comment]
hi @Vannav 
with 2.2.0 GA?

Is the db old or freshly created?

**Comment by Vannav** [comment]
Hi @maggiolo00 
yep, 2.2.0 from maven repository and its a old db

**Comment by maggiolo00** [comment]
hi @Vannav 

do you do schema modification in concurrency?

**Comment by maggiolo00** [comment]
Sorry closed by mistake :D

**Comment by Vannav** [comment]
Nothing is running concurrently right now. I just wanted to test if studio works because I'm failing on the same exception with either on `dropProperty` or `createProperty`

               if( documentClass.existsProperty( propertyName ) )
               {
                  documentClass.dropProperty( propertyName );

                 // Adding this to force reload of schema
                  db.reload();
                  documentClass = schema.getClass( className );
               }

               OProperty property = documentClass.createProperty( propertyName,
                     propertyType );

**Comment by maggiolo00** [comment]
Do you have a test case to reproduce this issue?

**Comment by Vannav** [comment]
I think a testcase wouldn't suffice. I tried it now on a fresh db and works as expected. I think the old db didn't survive the upgrade to 2.2

**Comment by luigidellaquila** [comment]
Hi @Vannav 

Does that db contain sensitive data? Is there any chance to have it for debugging?

Thanks

Luigi

**Comment by Vannav** [comment]
Hi @luigidellaquila

unfortunately it has alot sensitive data. I'm going to migrate it to a fresh database and report back.

Thanks for your input guys and keep up the good work!

**Comment by luigidellaquila** [comment]
Hi @Vannav 

Ok, no problem, thank you anyway.

Luigi

**Comment by tglman** [comment]
hi @Vannav,

Any news on this issue ? where you able to replicate it with a more recent version of orient?

Bye

**Comment by Vannav** [comment]
Hi @tglman,

this issue does not occur anymore and I didn't investigate further.

Greetings

**Comment by tglman** [comment]
Ok, thank you, closing this.
