### ISSUE TITLE
SELECT query WHERE clause

### ISSUE THREAD

**Issue by codelimner** [orientechnologies/orientdb#6281]
## Expected behavior and actual behavior

Select query behaves differently when filtering with " WHERE A = B" compared to " WHERE B = A".
## Steps to reproduce the problem

1) Start OrientDB console (2.2.1-Snapshot from develop)
2) Connect to GratefulDeadConcerts
3) Then run the following query:
orientdb {db=GratefulDeadConcerts}> SELECT name FROM V WHERE "song"=type AND OUT("sung_by").name="Beach_Boys"

+----+------------------+
|#   |name              |
+----+------------------+
|0   |OKIE FROM MUSKOGEE|
|1   |HELP ME RHONDA    |
|2   |RIOT IN CELL BLOCK|
+----+------------------+

3 item(s) found. Query executed in 0.05 sec(s).

4) Now run the following query:
orientdb {db=GratefulDeadConcerts}> SELECT name FROM V WHERE "song"=type AND "Beach_Boys"=OUT("sung_by").name

0 item(s) found. Query executed in 0.048 sec(s).
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ X] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ X] v2.2.x - Please specify last number: 
  OrientDB console v.2.2.1-SNAPSHOT (build develop@r3f4b9c490e67ffe2c0c2030930517509c647a334; 2016-06-07 14:02:16+1000) www.orientdb.com
### Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows
- [ X] Other Unix (FreeBSD 10.3)
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [ X] 8 (OpenJDK)

**Comment by luigidellaquila** [comment]
Hi @codelimner 

Probably it's a problem in the current query execution layer. I don't know if it can be easily fixed in the short term, we have in our roadmap a complete rewrite of the engine.

Thanks

Luigi
