### ISSUE TITLE
Error on execution of Gremlin Script

### ISSUE THREAD

**Issue by dperez6392** [orientechnologies/orientdb#6285]
## Expected behavior and actual behavior
Trying to execute a gremlin script with chained `getProperty('string')` 
(e.g. `it.getProperty('string1').getProperty('string2')`)

**Expected Behavior** 
The first `getProperty('string1')` call would usually return another `GroovyObject` in which you could call `getProperty` again.

**Actual Behavior**
The first `getProperty('string1')` call returns an `ODocument` containing the actual orient record. The consecutive `getProperty('string2')` call then throws a `groovy.lang.MissingMethodException` because `ODocument` does not contain a `getProperty` method that accepts a String.

## Steps to reproduce the problem
1. Create a Vertex in Orient with some fields (with nested fields) to filter on.
2. Search for the Vertex with a filter such as:
_g.V('id', '12345').filter{ it.getProperty('field').getProperty('nestedField').size() > 0 }_
3. You should get the following exception:
`groovy.lang.MissingMethodException: No signature of method: com.orientechnologies.orient.core.record.impl.ODocument.getProperty() is applicable for argument types: (java.lang.String) values: [nestedField]`

## Important Questions
We are upgrading from OrientDB 2.1.12 to 2.1.19 and the chained getProperty calls would work just fine prior to the upgrade. Now it seems like it returns an `ODocument` instead of a `GroovyObject`. 

If this is correct, is this a bug or new functionality?
Thanks!

### Storage Type
- [X] PLOCAL

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [X] v2.1.x - Please specify last number: 9 
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by luigidellaquila** [comment]
Hi @dperez6392 

Probably the result of `it.getProperty('field')` is not a vertex (and instance of V). Which class is it?

You can fix this problem in two ways:
- declare the class of that document as a subclass of V
- change you gremlin using `.field("fieldName")` instead of `.getProperty("fieldName")`

Thanks

Luigi

**Comment by dperez6392** [comment]
Hey Luigi,

Thanks for responding so quickly! I've tested both of your suggestions and both fixed the issue.

The main object's class extends V, but the field that is returned when calling the first `getProperty` method is an embedded class that does not extend anything. Would you happen to know what changed from OrientDB 2.1.12 that would cause this to happen?

Thanks!

Danny

**Comment by luigidellaquila** [comment]
Hi @dperez6392 

actually it was a bug fix, in previous versions getProperty() encapsulated the result in an edge when the result was an edge, and in a vertex in all the other cases, even when the result document was not a vertex. Now it properly returns a document in that case.

Thanks

Luigi

**Comment by dperez6392** [comment]
Thanks for the help!
