### ISSUE TITLE
Heavy Lag while manipulating lots of vertexes  with Graph Editor

### ISSUE THREAD

**Issue by jiezg** [orientechnologies/orientdb#6289]
## Expected behavior and actual behavior
Expect:Smooth operation on Graph Editor.
Actual:Heavy Lag while manipulating vertex  with Graph Editor(Studio 2.2).

## Steps to reproduce the problem
Add vertex 500 more times.

### Runninng Mode
- [X] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.0 - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by maggiolo00** [comment]
@jiezg 

The Graph editor is not supposed to work with a lot of nodes.  The limit should be around 1k nodes

**Comment by maggiolo00** [comment]
@jiezg 

There is some improvement in Graph Editor starting from 2.2.8. 
But again the Graph Editor is not supposed to work with too many vertexes/edges.

**Comment by jiezg** [comment]
Thank U ！

在 2016-09-23 18:30:48，"Enrico Risa" <notifications@github.com> 写道：


@jiezg

There is some improvement in Graph Editor starting from 2.2.8.
But again the Graph Editor is not supposed to work with too many vertexes/edges.
