### ISSUE TITLE
Using OrientDB in learning of Graph Theory

### ISSUE THREAD

**Issue by stokito** [orientechnologies/orientdb#6294]
I'm learning [Graph theory](https://www.coursera.org/learn/teoriya-grafov/) course on Coursera and needed a tool to work with graphs.
It would be great to use OrientDB visualizer for all task on the course.
But unfortunately it lacks for some needed functionality like oriented graphs.

So my proposition is to create some kind of learning tool. It would be great for marketing, because if students learns graph with OrientDB then they will use it at work ;-)

I'm looking for some enthusiast who would like to pass a course with me and try to use OrientDB Visualizer for all problem sets and gather some kind of usage data.
Anyone is interested?

**Comment by stokito** [comment]
My first comment!

**Comment by smolinari** [comment]
> But unfortunately it lacks for some needed functionality like oriented graphs.

I believe you can create an oriented graph (as I understand the concept) by defining the links implicitly and by creating an additional UNIQUE index constraint. I believe the explanation about a car owner and his relationship to his car only being owned by him depicts the start of an oriented graph? <= it is a question more than a statement. :smile: 

http://orientdb.com/docs/2.2/Tutorial-Using-schema-with-graphs.html

Scott
