### ISSUE TITLE
Error Creating Abstract Class That Extends V In Version 2.2.0

### ISSUE THREAD

**Issue by decafmainline** [orientechnologies/orientdb#6296]
## Expected behavior and actual behavior
Expected behavior is to create an abstract class that extends V. I can create a class that is abstract, or a class that extends V, but not both. This is part of a setup script and worked perfectly in version 2.1.x.

Produces the error:

```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
create CLASS SomeClassV ABSTRACT EXTENDS V
                                       ^
Encountered " <EXTENDS> "EXTENDS "" at line 1, column 33.
Was expecting one of:
    <EOF> 
    ";" ...
    
        Storage URL="plocal:/opt/orientdb-community-2.2.0/databases/my-database"
        Storage URL="plocal:/opt/orientdb-community-2.2.0/databases/my-database"
```
The error message shows plocal as the connection mode, even though I am using remote.

## Steps to reproduce the problem
sudo ./console.sh
CONNECT remote:localhost/my-database database-user database-password
CREATE CLASS SomeClassV ABSTRACT EXTENDS V;

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ x] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ x] v2.2.x - Please specify last number: 2.2.0

### Operating System
- [ ] Linux
- [x ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ x] 8

**Comment by decafmainline** [comment]
Produces the error:

```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
create CLASS SomeClassV ABSTRACT EXTENDS V
                                       ^
Encountered " <EXTENDS> "EXTENDS "" at line 1, column 33.
Was expecting one of:
    <EOF> 
    ";" ...
    
        Storage URL="plocal:/opt/orientdb-community-2.2.0/databases/my-database"
        Storage URL="plocal:/opt/orientdb-community-2.2.0/databases/my-database"
```
The error message shows plocal as the connection mode, even though I am using remote.

**Comment by luigidellaquila** [comment]
Hi @decafmainline 

In v 2.2 also DDL commands are parsed with the new strict grammar, so you have to respect the order of keywords (see syntax here http://orientdb.com/docs/last/SQL-Create-Class.html)

The correct statement is
```
CREATE CLASS SomeClassV EXTENDS V ABSTRACT;
```

Thanks

Luigi
