### ISSUE TITLE
Pagination retrieves duplicates and other weirdness.

### ISSUE THREAD

**Issue by stuz5000** [orientechnologies/orientdb#6298]
## Expected behavior and actual behavior

The documented pagination method (behaves in very surprising ways).
http://orientdb.com/docs/2.1/Pagination.html

Implementing this method (see below), I get:
- duplicated documents in the result
- record sets shorter than the page size, followed by longer pages
- a infinite series of results, with no apparent way to know when to stop.

Actual behavior: see link below.

Expected behavior: a pagination method should return all results matching a query exactly once, in chunks of N results, and then stop.

As far as I can tell, this is the only way to both:
- iterate over all records in the DB without causing them to all be loaded into the memory of the client
- not take over the flow of execute on the client (as happens for async query)

(NB. it would be nice if queries returned iterators instead of lists, so that large queries could straightforwardly be processed.)
## Steps to reproduce the problem

(scala) test case here (uses Java API only)

http://stackoverflow.com/questions/37731791/orientdb-automatic-pagination-returning-duplicate-result-short-pages-and-an-in

Using client 2.1.19
### Runninng Mode
- [  ] Embedded, using PLOCAL access mode
- [ X] Embedded, using MEMORY access mode
- [ ] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 
### Operating System
- [X ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [ X] 8

**Comment by a-zacharenkov** [comment]
Would be nice to have some info on the progress of this issue, I am working with querying for a big amount of elements and tried using this way of pagination and it seems to be causing the same issue. I guess I'll try SKIP-LIMIT instead, but this would be nicer if it has a better performance.
