### ISSUE TITLE
Incorrect work of sequence in 2.2.2 version

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#6300]
## Expected behavior and actual behavior

Version 2.2.0 returns **11**.  Version 2.2.2. returns **10**.

## Steps to reproduce the problem
1) Create sequence by command:
CREATE SEQUENCE song_sequence_name TYPE ORDERED START 1 INCREMENT 10

2) Get next value by command: 
select sequence('song_sequence_name').next()

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [X] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ X] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

I found the problem and I'm on it, the fix should be simple

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

Fixed in both develop and 2.2.x branches. The fix will be released with v 2.2.3

Thanks

Luigi
