### ISSUE TITLE
broken uuid() function

### ISSUE THREAD

**Issue by mcaramma** [orientechnologies/orientdb#6302]
The batch code below behave in a very inconsistent way, raising 2 critical problems:

1. It may raise java.lang.NumberFormatException when it shouldn't ....  just try to execute the code several times and it will fail at some point.
2. But even worse, when it doesn't fail it generate identical UUIDs!!!

The following image shows both issues in one place:

![uuid](https://cloud.githubusercontent.com/assets/7320843/16065003/01a1a23c-3296-11e6-96f5-40d95838c75e.png)

Copy & paste batch code:
```
/* do not include <drop class> commands the first time */
drop class User;
drop class Model;
drop class Record;

create class Record abstract;
create property Record._id string;
create property Record._txn string;
alter property Record._id default uuid();
alter property Record._id readonly true;

create class User extends Record clusters 1;
create class Model extends Record clusters 1;

insert into Model set name = 'ModelA';
insert into User set name = 'bob';
```

### Runninng Mode
- [X] Remote (storage: PLOCAL / dbtype: DOCUMENT)

### Misc
- [X] I'm using the Enterprise Edition

### OrientDB Version
- [X] v2.2.2

### Operating System
- [X] Linux

### Java Version
- [X] 8

java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**Comment by luigidellaquila** [comment]
Hi @mcaramma 

The uuid() expression is evaluated during the ALTER PROPERTY statement, so the value is cached.

Please try this
```
alter property Record._id default "uuid()";
```

This should fix your problem.

In V. 3.0 we will add some syntax to let default functions be evaluated at record creation.

Thanks

Luigi

**Comment by mcaramma** [comment]
Hi Luigi,

thanks, that worked with v2.2.2 but doesn't work with previous versions, I tried with v2.1.19 and "uuid()" is not evaluated at record creation.

SQL-Alter-Property documentation example for version 2.2.x and 2.1.x include this code
```
orientdb> ALTER PROPERTY Client.id DEFAULT uuid() READONLY
orientdb> ALTER PROPERTY Client.id READONLY TRUE
```
I guess it should be fixed to something like this .... only for v2.2.x
```
orientdb> ALTER PROPERTY Client.id DEFAULT "uuid()"
orientdb> ALTER PROPERTY Client.id READONLY TRUE
```

**Comment by luigidellaquila** [comment]
Yes, good point, I'll update the docs

Thanks

Luigi
