### ISSUE TITLE
Optimize index changes sent by the remote client

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6304]
Apply index changes interpretation strategies developed as a result of #6243 to index changes before they sent to the server by the remote client. That should lower the amount of data sent by the client in certain cases.

**Comment by tglman** [comment]
hi @taburet,

yes Index changes in case of client are tracked only for in Tx lookup, they should not be sent to the server at all, only manual index tracking should be sent, we need to clean up a bit and track in a better way the two different tracking on the client, will be addresses with some refactors in 3.0

**Comment by laa** [comment]
Hi @tglman , if you already have plans for that , I will reassign issue

**Comment by tglman** [comment]
Hi, 

As today implementations the index changes are send back and forward from the server, because we still have support for manual index, as soon we remove the support for manual index index changes can be removed from network.

Regards

**Comment by lvca** [comment]
Can we at least check that if there are no manual index used we skip this?
