### ISSUE TITLE
Unable to create new users in distributed setup

### ISSUE THREAD

**Issue by justinkillen** [orientechnologies/orientdb#6307]
## Expected behavior and actual behavior
The "create user" command doesn't work in a distributed setup in version 2.2.2

Any time I use it, I get a distributed operation exception (screenshot: https://www.dropbox.com/s/nd9m52i8dbk7r4t/Screenshot%202016-06-15%2010.51.13.png?dl=0)

It seems that the entry is created in both servers, just with a different password hash which collides. Screenshot of user creation process (redacted) https://www.dropbox.com/s/r4oywkc5gqj6lsj/Screenshot%202016-06-15%2012.26.04.png?dl=0 and https://www.dropbox.com/s/2poi06z9mxxqr26/Screenshot%202016-06-15%2012.26.43.png?dl=0

Strangely, if I run the command on devgro1, I can login using the credentials on the OTHER server (devgro2), but not on the server I ran the command on.

To add to the confusion, I can't use the old method of inserting into OUser either, as it seems the password encryption hook doesn't get run: https://www.dropbox.com/s/ruxes4vkop4kigb/Screenshot%202016-06-15%2012.19.30.png?dl=0

This doesn't seem to work either:
INSERT INTO OUser SET name = 'grl_loader_app', password = '{PBKDF2WithHmacSHA1}D3F6F762A910E692041EA6E08F9C2B7D59C4943111B84809:2E294F86AC8EC6FEF1B909C2881EBAB6800F59A3AFA4BC61:65536', status = 'ACTIVE', roles = (SELECT FROM ORole WHERE name = 'writer')

And UPDATE OUser causes the same conflicting update as the CREATE USER

## Steps to reproduce the problem
see above

## Important Questions
How can I work around this?

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote

### Misc
- [X] I have a distributed setup with multiple servers. How many? 2, "writeQuorum": "majority"
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 2.2.2

### Operating System
- [X] Linux  CentOS 7.1
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [X] 7
- [ ] 8

**Comment by justinkillen** [comment]
Can someone confirm if this is working for other people or if it's broken for everybody?  I'm facing a deployment soon and I need to know if we will be able to deploy this version of if we'll need to go with a 2.1.x version.

**Comment by justinkillen** [comment]
Can I get this escalated to the next 2.2.x milestone?  It really makes the 2.2.x branch unusable in any kind of large scale installation

**Comment by lvca** [comment]
Have you tried with 2.2.5?

**Comment by justinkillen** [comment]
I've looked through the resolved issues for 2.2.3, 2.2.4 and 2.2.5 and I didn't see anything seemingly related to this.  No, I have not tested specifically against 2.2.5

**Comment by lvca** [comment]
We fixed many issue with replication. Could you retest your app with 2.2.5?

**Comment by lvca** [comment]
Closing because no answer after a while. In case please reopen/comment this.
