### ISSUE TITLE
Console unable to list server users unless started from a specific directory

### ISSUE THREAD

**Issue by phillipross** [orientechnologies/orientdb#6308]
## Expected behavior and actual behavior

When console utility is started outside of ORIENT_DIR/bin directory, the `list server users` command throws the following error:

```
Error: com.orientechnologies.orient.core.exception.OConfigurationException: Cannot access to file ../config/orientdb-server-config.xml
```
## Steps to reproduce the problem
- Place ORIENT_DIR/bin in the path and invoke the utility from a location OUTSIDE of the bin directory.
- Invoke `list server users` command, and the error is shown.

Even after connecting to the local server via the remote protocol (`connect remote:localhost root <root-password>`) the error still occurs.
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number:   2.2.0 and 2.2.2
### Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows
- [X] Other Unix > Illumos (SmartOS & OmniOS)
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by MarkusNetz** [comment]
This is still a problem in Orientdb 3.1.0, 3.1.2, 3.1.6, 3.1.10 and 3.1.12.
I have written about it here https://discourse.orientdb.org/t/console-sh-locally-from-custom-pwd-not-able-to-acces-config-file/1471

The discourse page is about two things:
1) keeping everything except log and database dir in $ORIENTDB_HOME and the start console.sh from outside $ORIENTDB_HOME when console.sh is in your bash PATH.
2) Putting config-files in /etc dir and databases and logs outside of $ORIENTDB_HOME.
Then go to $ORIENTDB_HOME/bin and start console.sh (as usual) and try to "list server users;" or "set server user user pass * ;". Both statements will fail to access file "../config/orientdb-server-config.xml"

My workaround for this is to put a symlink in $ORIENTB_HOME/config that points to /etc/orient/orientdb-server-config.xml
Does not seem to be possible to adjust "console.sh" script to point out correct config path. This is easily done in server.sh
