### ISSUE TITLE
Unsupported backup against remote storage locks database on writes

### ISSUE THREAD

**Issue by zella** [orientechnologies/orientdb#6309]
## Expected behavior and actual behavior

I'm running embedded server http://orientdb.com/docs/2.2/Embedded-Server.html . So my java app connects in plocal mode.

When I run `bin/backup.sh remote:/test USER PASS ../backup.zip` message shows:
Error: java.lang.UnsupportedOperationException: backup is not supported against remote storage...

And database became locked on writes infinitely

It'should't freeze in this case.

## Steps to reproduce the problem

run `./backup.sh remote:/DBNAME USER PASS ../backup.zip` against remote storage and try to write in db

### Runninng Mode
- [ x] Remote (embedded server)

### OrientDB Version
- [ x] v2.2.2 - Please specify last number: 

### Operating System
- [ x] MacOSX

### Java Version
- [ x] 8

**Comment by mindnuts** [comment]
Same issue was encountered by us while using Orientdb in server mode (Orientdb Version 2.1.16). The database was frozen and it was not "Released" by the backup script. I had to manually login to the console and release it.

**Comment by laa** [comment]
Hi @mindnuts you are right. I am not muster of linux scritps. But @tglman  (initial author of the script) may fix it to release database after error.

**Comment by tglman** [comment]
Hi,

Were missing some checks in case of failure, fixed, closing.

**Comment by jastifin** [comment]
Don't you have the same problem of database left frozen when using the "lvm" mode: if **lvcreate** fails for some reason the backup -script exists and the "release database" command will not be invoked.
