### ISSUE TITLE
documentation for network.binary.maxLength has bytes instead of kB

### ISSUE THREAD

**Issue by grexe** [orientechnologies/orientdb#6310]
Since I can remember, at least in v2.x, the [documentation on the network configuration](http://orientdb.com/docs/2.2/Configuration.html) setting for `network.binary.maxLength` is wrongly stating:

```
TCP/IP max content length (in bytes) of BINARY requests.
```

But from the log, you can see that the size is actually in kB.
Please clarify and correct the docs accordingly.

**Comment by tglman** [comment]
Thank you for reporting this, update the documentation closing
