### ISSUE TITLE
Add docs for extended syntax of CREATE PROPERTY

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#6313]
missing docs after PR https://github.com/orientechnologies/orientdb/pull/6292

**Comment by luigidellaquila** [comment]
Done, closing

**Comment by smolinari** [comment]
Here? http://orientdb.com/docs/last/SQL-Create-Property.html

I guess the changes haven't been deployed to the server? :smile: 

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

exactly, the CI/CD tool is still running for the docs, it will be on-line in short.
In the meantime:

https://github.com/orientechnologies/orientdb-docs/blob/master/SQL-Create-Property.md

Thanks!

Luigi

**Comment by smolinari** [comment]
Don't mean to be too critical, but there is a small mistake in the example (two withs).

>Create the property name of the string type in the class User, mandatory, **with** with minimum and maximum length (since V2.2.3):

I learned something too. I didn't realize I could restrict field lengths in ODB too. Cool! :+1: :smile: 

Scott

**Comment by luigidellaquila** [comment]
Thank a lot Scott 😄 
A double check is always needed, especially when things to dot have to pass a compile/build process ;-)

Luigi
