### ISSUE TITLE
hotAlignment Setting

### ISSUE THREAD

**Issue by davidheryanto** [orientechnologies/orientdb#6315]
Is the recommended setting for hotAlignment should be `true` or `false`?

Here, it is suggested to keep it false
http://orientdb.com/docs/2.0/orientdb.wiki/Distributed-Architecture.html
![capture](https://cloud.githubusercontent.com/assets/5300554/16144065/48e79fca-34a3-11e6-8155-c4145f1443d3.PNG)

Whereas on this page, it says the default is true
http://orientdb.com/docs/2.0/orientdb.wiki/Distributed-Configuration.html
![capture](https://cloud.githubusercontent.com/assets/5300554/16144093/7d72f4c4-34a3-11e6-84df-62e2c84a5afb.PNG)

Also, suppose I have a distributed configuration: node1 and node2 and `hotAlignment:false`. Then node2 goes down, then I update/add a node on node1 while node2 is down.

When node2 is finally up again, will it sync with node1 (add/update the new node)? 
Or I need `hotAlignment:true` for it to happen.

Thanks.

---

### Misc
- [x] I have a distributed setup with multiple servers. How many? 2

### OrientDB Version
- [x] v2.2.2

**Comment by lvca** [comment]
You're reading old docs (2.0) for 2.2.2. hotAlignment is not supported anymore. Look at: http://orientdb.com/docs/last/Release-2.2.0.html#distributed

**Comment by eduardnegru** [comment]
In the documentation for 3.0.x version, the "hotAlignment" property is still present in the documentation [1], [2]. Was the property reintroduced or there is an inconsistency in the documentation?

[1] http://orientdb.com/docs/3.0.x/distributed/Replication.html
[2] http://orientdb.com/docs/3.0.x/distributed/Distributed-Sharding.html
