### ISSUE TITLE
document ORole.PERMISSION_EXECUTE

### ISSUE THREAD

**Issue by mcaramma** [orientechnologies/orientdb#6317]
Please add missing documentation for the new 'execute' permission in v2.2.2.

**Comment by lvca** [comment]
@SDIPro Please could you also check if EXECUTE is correctly supported in the whole codebase?

**Comment by PhantomYdn** [comment]
It's not yet supported. Documentation missing. Some code also missing. For example: https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/metadata/security/ORestrictedOperation.java  (Yes - it's for OTriggered, but in any case)
