### ISSUE TITLE
Create index blocks database

### ISSUE THREAD

**Issue by lucevers** [orientechnologies/orientdb#6319]
## Steps to reproduce the problem

1) Create class
2) create index on all the fields and the database blocks.

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x ] Remote

### Misc
- [ x] I have a distributed setup with multiple servers. How many? 2 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x ] v2.2.x - Please specify last number: 

### Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ x] 8

1) Create a new class with 5 properties.
**Blocking command:
2) create index inps_20160618 on nps_20160618 (ip,nbr,date,aic,stat) NOTUNIQUE METADATA {ignoreNullValues : false}**

This actions are no problem in OrientDB 2.2.0  but in OrientDB 2.2.2 the OrientWebsite blocks also interrupt don't help!
If I stop the browser and check on the index page I see that the index is created but it seems that
the process is running in loop after this action.

Rem: There is no data in de database! Only a new database with a new class and properties.

**Comment by lucevers** [comment]
Test via Rest command:  same problem!

**Comment by lucevers** [comment]
After some manual test I found that de cluster was not working as before, the created class was not present in the second servers. 
So the problem is not the index command but the cluster!
I started again the second server from start, with the default database.
Sync with the other server was oke. 
Creating a class in Server1 -> Server2 was synced so the class was also available in Server2.

Started again the rest program, creating class , properties and index was oke now.
But when the program started with loading data is got the error:
   **com.orienttechnologies.orient.server.distributed.ODistributedException: Quaorum (3) cannot reached because it is a major than available nodes (2) !**

Seems not a stable cluster , if I shut down and startup a node the other node sends messages like:
"Node is not online yet (status=STARTING), blocking command until it is online.
But the other node was online , the error messages never stopped. Shut down the Orient on the two servers and startup again solved the problem. But data inserting is not possible because of the Quorum problem.

I returned to OrientDB 2.2.0 and all problems are gone!

**Comment by lvca** [comment]
@lucevers Please update to the last 2.2.2 version. Can you also provide the full exception about the quorum?

**Comment by lucevers** [comment]
Sorry, I forgot to specify the last number= 2
 Not stable cluster: orientdb-community-2.2.2
       stable cluster: orientdb-community-2.2.0

**Comment by lvca** [comment]
Do you mean this problem has been introduced after 2.2.0?

**Comment by lucevers** [comment]
We were running version 2.2.0 , so I made an update by copy the databases to the new version 2.2.2.
After starting up version 2.2.2,  I could not load new data ! (see above)

**Comment by lucevers** [comment]
I tested community version 2.2.3 , this version still has the error "Quorum (3) cannot be reached because it is major than available nodes (2) [ONetworkProtocolHttpdb]
You can find the same error on stackoverflow for version: OrientDB 2.1.9 GA.

http://stackoverflow.com/questions/35015565/orientdb-clustered-mode-not-working-quorum-not-reached-etc

If I build up the whole database (no copy but config from start) , then I can write to the database.
If I do a database export from version 2.2.0 and try an import via the console I got:

"Cannot execute distributed update record #0:0 because no nodes are availabel.
Strange messages because I'm connected with the database for the import!

**_Conclusion:_**
      Database versions 2.2.0 / 2.2.2  / 2.2.3 are not compatible!
      Very bad for production.

**Comment by lvca** [comment]
Are you executing an import while the database is distributed?

**Comment by lucevers** [comment]
Are you executing an import while the database is distributed?
Yes, there are 2 nodes.

**Comment by lvca** [comment]
Ok, then please try importing the database before to run distributed.

**Comment by lucevers** [comment]
See also above:

Misc

[ x] I have a distributed setup with multiple servers. How many? 2

**Comment by lucevers** [comment]
Importing database before to run distributed.
Oke, I'll test with next release.
