### ISSUE TITLE
Inconsistent ODatabase API

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#6321]
## Important Questions

There is the following description of ODatabase.command()

```
Execute a command against the database. A command can be a SQL statement or a Procedure. If the OStorage used is remote (OStorageRemote) then the command will be executed remotely and the result returned back to the calling client.
```

But in fact code of that method is the following:

```java
public OCommandRequest command(final OCommandRequest iCommand) {
    checkSecurity(ORule.ResourceGeneric.COMMAND, ORole.PERMISSION_READ);
    checkIfActive();

    final OCommandRequestInternal command = (OCommandRequestInternal) iCommand;

    try {
      command.reset();
      return command;

    } catch (Exception e) {
      throw new ODatabaseException("Error on command execution", e);
    }
  }
```

As you can see there is NO actual execution of a command.
I do understand that it's possible to do like this: `db.command(command).execute(args)`, but it looks inconsistent with query(). Btw, it will be good to have the same signature as query: I mean to have ability to specify arguments to be passed to command.

Imho it will be more safe to change just JavaDoc, because I guess there are tons of code which have execute() afterwards.

What do you think?

### OrientDB Version
v2.1.19

**Comment by lvca** [comment]
This was already discussed internally and will be changed in v3.0 for sure.

**Comment by tglman** [comment]
hi @PhantomYdn 

the discussion is happening here: https://github.com/orientechnologies/orientdb-labs/issues/5 feel free to join gracefully.

I'll close this, is kind of duplicate
