### ISSUE TITLE
LiveQuery dies when server is stopped and restarted

### ISSUE THREAD

**Issue by torfranz** [orientechnologies/orientdb#6324]
## Expected behavior and actual behavior
I have a client running a LiveQuery. Everything is fine, modifications are notified through the provided callback interface.
For testing purposes I stop the server and restart it. Non LiveQuery related db functionality will be reattached and works, but the still open LiveQuery will no longer receive notifications.

## Steps to reproduce the problem

Follow description above

## Important Questions

- Is there a mechanism to react to the server shutdown at client side in order to recreate the LiveQuery?
- Why isn't the onError callback being called, I would've assumed that this scenario should trigger the callback.
- How is the correct way to handle the server shutdown/restart scenario for open LiveQuerys?

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.2 - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by luigidellaquila** [comment]
Hi @torfranz 

this is a known issue in current release, we are fixing it and the fix will be released in short

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @torfranz 

Sorry for the wrong info. The bug I referred to was due to `client` stopping and restarting, so this is a different problem.

Currently the client automatically reconnects to a server, but it does not keep track of the live queries it executed, so there is no way to automatically re-execute them.

I'm marking it as an enhancement as it's not part of current design, but probably we will be able to find a solution in the near future

Thanks

Luigi

**Comment by torfranz** [comment]
It would be nice if a client could actually react to this situation. 

For the moment it would be enough to get informed when the server dies, so all pending LiveQueries could be recreated once the server is back. 

I know that there is an internal exception being raised when the server dies, so it should be possible to provide an event where the client could subscribe to and handle this situation. 

Getting this all automatically when the client reconnects would be even better of course :-)

**Comment by tglman** [comment]
hi @torfranz,

The listener has the `onError` method that should be call in case of error, there was i small issue there that i've fixed, so now you should get called on server shutdown crash

**Comment by torfranz** [comment]
Hi @tglman,
I verified with v2.2.7 that onError of live query listener is called now in case of a server shutdown.
