### ISSUE TITLE
Request for a new command 'SIZE'

### ISSUE THREAD

**Issue by mcaramma** [orientechnologies/orientdb#6326]
I think it would be very useful to have a command that can be used to get real resources storage size, where resource may be one of: database, class, cluster, index, record.

The command should compute correctly the size in both single and clustered node setup with replication. Separating stored records size from "tombstone" would be also something nice to have.

I couldn't find anything in the current documentation to do that, so maybe there is already a way to do it .... in that case please add the missing documentation.

Thanks

**Comment by lvca** [comment]
@luigidellaquila can we extend the new `metadata` to include such information?

**Comment by luigidellaquila** [comment]
Already available in v 3.0 with 

SELECT FROM metadata:storage

Closing, thanks

Luigi
