### ISSUE TITLE
OrientDB cannot open a local database inside a folder containing dollar signs

### ISSUE THREAD

**Issue by nuixkeith** [orientechnologies/orientdb#6327]
## Expected behavior and actual behavior

If I try to open a local OrientDB database in a path such as the following I should be able to do so.

C:/my$path/Stores/Graph Database/graphf28b0f4ca68f41cc88cbb40af2458c5f

Instead in OIOUtils.getPathFromDatabaseName it replaces the valid dollar symbol to a forward slash which gets recognized as a path separator and it throws the following exception:

Location passed in WAL does not exist, or IO error was happened. DB cannot work in durable mode in such case
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:674)
	at ODiskWriteAheadLog.java:616
	at OLocalPaginatedStorage.java:292
	at OAbstractPaginatedStorage.java:276
	at OLocalPaginatedStorage.java:113
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:383)

## Steps to reproduce the problem

Create a path with a folder containing a dollar symbol.

## Important Questions

Can you change the logic of using a dollar sign as a replacement character to a much less likely character combination like a high range unicode char wrapping a dollar sign.

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [x ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ x] 7
- [ x] 8

**Comment by lvca** [comment]
The dollar sign is used for sub-folder, and there is no way to encode it right now.
