### ISSUE TITLE
NullPointerException when creating instance of OserverAdmin using the url of a server that is down

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#6329]
I have an integration test with an assumption on the status of a server (if the server is down the test is not executed).

The test worked fine using OrientDB 2.2.2 and before, but throws a NullPointerException when using OrientDB 2.2.3.

Stacktrace:

```
java.lang.NullPointerException
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.release(ORemoteConnectionManager.java:115)
	at com.orientechnologies.orient.client.remote.OServerAdmin.networkAdminOperation(OServerAdmin.java:699)
	at com.orientechnologies.orient.client.remote.OServerAdmin.connect(OServerAdmin.java:90)
```

In your code:

`com.orientechnologies.orient.client.remote.ORemoteConnectionManager.release(OChannelBinaryAsynchClient)`

You should assert that the connection passed as argument is not null.

### OrientDB Version
- [ ] v2.2.x - Please specify last number: 3

### Java Version
- [ ] 8

**Comment by tglman** [comment]
hi @diegomtassis,

Yes i did a small refactor and i missed this, check, a check of null is enough, i put it there, closing

**Comment by diegomtassis** [comment]
I don't know what git flow you're using, but don't forget to backport it to 2.2.x.
