### ISSUE TITLE
integrate and update JCA adapter for proper JEE support

### ISSUE THREAD

**Issue by grexe** [orientechnologies/orientdb#6330]
Currently we struggle integrating OrientDB as a datasource in Wildfly (or any JEE server).
Through the help of [this StackOverflow thread](http://stackoverflow.com/questions/35779181/issues-configuring-orientdb-as-a-datasource-in-wildfly), we were pointed to this project:
https://ops4j1.jira.com/wiki/display/ORIENT/JCA+Resource+Adapter

Looks very nice, but sadly comes bundled with an outdated version of OrientDB.
Could you please integrate this driver in the main source base and update it to the latest version?

Or I could try to bring it up to date and submit a pull request...

**Comment by lvca** [comment]
Hi @grexe could you please update it to 2.2.3 and send a PR?

**Comment by schernolyas** [comment]
Hi @grexe !

I see that your issue linked with mine [https://github.com/orientechnologies/orientdb/pull/5622](url).  I got exception then I try to create datasource at WildFly 9.

Please, try to create datasource to OrientDB in WildFly 10.  May be ... problem is fixed by OrientDB team

**Comment by lvca** [comment]
@robfrank could you please take a look at this project and if it's still relevant propose to the author to embrace it under the OrientDB umbrella so we can update it on regular base?

**Comment by robfrank** [comment]
@lvca : The project seems abandoned, last commit was done 2 years ago,the code refers to OrientDB 2.0.x 
I don't think it is usable.

**Comment by lvca** [comment]
Do you think it's compatible with OrientDB v2.2 with just changing the pom?

**Comment by robfrank** [comment]
For sure, we can do that. But test it inside a JEE container it's another thing, IMHO.
