### ISSUE TITLE
Caught I/O errors from localhost, trying to reconnect (error: java.io.InvalidClassException: com.orientechnologies.orient.core.exception.OCoreException: local class incompatible)

### ISSUE THREAD

**Issue by srthecodexpress** [orientechnologies/orientdb#6331]
## Expected behavior and actual behavior
Moved to orientdb v2.2.2 to counter issue(s) #6219 & #6234. Running the same code as in #6219 & #6234 to insert dbpedia data as a linked data graph in orientDB.
While I am not getting the issue as in #6234, after insertion of some 20k more vertices and similar no. of edges from the point i got the #6234 issue, i get this issue. Kindly refer to the jpeg attached to get the full error stack.
While the program is running, as you can see from the jpeg, its losing connection again & again from the OrientDB server at localhost, and as such further inserts are not happening.

![screenshot from 2016-06-21 15 50 51](https://cloud.githubusercontent.com/assets/14372749/16227229/17dd8f66-37cd-11e6-8cac-7cca52f6c8f2.png)

## Steps to reproduce the problem
- Steps to reproduce the problem are mentioned in the comments of #6234, as i am running the same code.

### Running Mode
- Remote, on the same machine.

### OrientDB Version
- v2.2.2

### Operating System
- Linux, Ubuntu 14.04 

### Java Version
- Java 8

This has been very frustrating. After 2 months, 3 bugs filed, I am still not able to upload a simple real-world graph to OrientDB.

**Comment by luigidellaquila** [comment]
Hi @srthecodexpress 

From the logs it seems you are using different versions of Java client vs. server, could you please check this and in case align both to the same version?

Thanks

Luigi

**Comment by srthecodexpress** [comment]
Ok @luigidellaquila I'll check it and get back to you.
Thanks
Sitanshu.

**Comment by srthecodexpress** [comment]
@luigidellaquila I checked that. Both java versions are the same. To make sure, i re-ran the same code again with same java versions and i am getting same issue. Kindly check.

Thanks
Sitanshu.

**Comment by luigidellaquila** [comment]
Hi @srthecodexpress 

ops, sorry, my fault, wrote too quick... I meant OrientDB version, not Java version... could you please check it? 

Thanks

Luigi

**Comment by srthecodexpress** [comment]
Hi @luigidellaquila 
Oops, yes, the OrientDB version in the client program was different, my mistake.
I fixed that and re-ran the code. Now, this issue is not happening!!
However, I am getting the exception of the issue #6234 for 4 nodes.
Here are the caught exceptions entries that were there in the log.

**016-06-23 16:48:06.142 INFO  org.formcept.knowledge.base.graph.FCOrientGraph: {:message "Exception at insertion of node: http://dbpedia.org/resource/Communist_Party_of_Malaya/Marxist%E2%80%93Leninist\n. Exception message: Cannot put key value entry in index\r\n\tDB name=\"LinkedDataStore\"\r\n\tDB name=\"LinkedDataStore\""}
2016-06-23 16:48:09.263 INFO  org.formcept.knowledge.base.graph.FCOrientGraph: {:message "Exception at insertion of node: http://dbpedia.org/resource/Communist_Party_%E2%80%93_Red_Star\n. Exception message: Cannot put key value entry in index\r\n\tDB name=\"LinkedDataStore\"\r\n\tDB name=\"LinkedDataStore\""}
2016-06-23 16:48:10.531 INFO  org.formcept.knowledge.base.graph.FCOrientGraph: {:message "Exception at insertion of node: http://dbpedia.org/resource/Communist_Party_of_Nepal_(Janamukhi)\n. Exception message: Cannot put key value entry in index\r\n\tDB name=\"LinkedDataStore\"\r\n\tDB name=\"LinkedDataStore\""}
2016-06-23 16:48:11.842 INFO  org.formcept.knowledge.base.graph.FCOrientGraph: {:message "Exception at insertion of node: http://dbpedia.org/resource/Communist_Party_of_Malaya/Revolutionary_Faction\n. Exception message: Cannot put key value entry in index\r\n\tDB name=\"LinkedDataStore\"\r\n\tDB name=\"LinkedDataStore\""}**

Since its only 4 nodes till now, that is not such a big problem for us. We are proceeding with the ETL.
But FYI, #6234 seems not to be fully resolved yet. The URIs are there for your testing and validation.
Should I re-open the #6234 issue? Because, it will be a problem for us if the number of such exceptions rise as we still have a lot of dbpedia data still left to upload. The program is still running.  
I'll go ahead and close this issue.

Thanks

Sitanshu.

**Comment by luigidellaquila** [comment]
Hi @srthecodexpress 

Thank you for the update, I'm re-opening issue #6234 for you, for a double check

Thanks

Luigi
