### ISSUE TITLE
Migrate non-tx index updates to atomic operations manager

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6332]
Currently we use two separate methods of updating indexes in tx and non-tx mode. In the non-tx one data and index updates are not grouped into one atomic task, this results in various glitches while mixing tx and non-tx code.

This should be fixed by unifying both methods, so both the tx path and the non-tx path use atomic operations.

**Comment by tglman** [comment]
Hi,
Completely agree on that, checking the code i've already a kind of idea how to do this, the first thing IMHO we should do is move the index tracking logic outside the hooks, and have it diretly in the execute[Save/Delete]Record or even directly inside the storage, and at that point we can easily wrap everything in an otomic operation.

as well will be good to use the dirty manager for get all the record changed and update all together inside an atomic operation at the moment of the save, in a similar way the transaction does, this will make much safer the graph operations.

**Comment by laa** [comment]
@tglman it is already fixed in cheap way. We are on testing stage.

**Comment by laa** [comment]
Fixed.
