### ISSUE TITLE
Default value by function triggered after a replication

### ISSUE THREAD

**Issue by Pro-Vizion** [orientechnologies/orientdb#6334]
## Expected behavior and actual behavior
When a document is updated on a Node, the value changes are replicated to the other nodes.
In our case we have a property declared with a function used to define in an abstract class its default value when a document insert has occured 

`ALTER PROPERTY _sys.myid DEFAULT "uuid()"`

Since 2.2.2 (even 2.2.3) the function uuid of our example, is triggered during an update (on the other nodes only) after replication

myid is then different on nodeb compared to nodea (which you'll be ok, it is quite a mess for an id)

## Steps to reproduce the problem
Declare a function that define a default value for one of your properties. And check an update with a second node replication.

### Runninng Mode
- [X] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote

### Misc
- [X] I have a distributed setup with multiple servers. How many? 2
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 3

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by Pro-Vizion** [comment]
Also, note that if you precise : 

`ALTER PROPERTY _sys.myid READONLY TRUE`

and if you do an UPDATE on a document : 

you have this error : 

`com.orientechnologies.orient.core.exception.OValidationException: The field '_sys.myid' is immutable and cannot be altered. Field value is: ca425a92-6fe3-4500-a091-ed728cb28897 DB name="XXX"`

whats funny is that : 
- despite this message, the property myid was changed on nodea.
- the other properties asked to be changed in the UPDATE were not changed
- no property was changed on the other nodes

regards

**Comment by tglman** [comment]
Hi @Pro-Vizion,

Yes we changed a bit the evaluation of default value for fix some indexes problem, it can happen that now in some context it happen too early, this feature come in from the community and probably we didn't evaluate well the impact of this on distributed environments, we will try to figure out when is the correct evaluation time and fix it, in any case this is a problem only for random/dynamic based default value functions.

**Comment by Pro-Vizion** [comment]
Hi, any news on this?

**Comment by tglman** [comment]
hi @Pro-Vizion,

This has been just fixed will be released with 2.2.6 at the end of this week.

Regards

**Comment by tglman** [comment]
this was fixed a while ago and released, i'm going to close this, please reopen if you still have problems.
