### ISSUE TITLE
create new vertex with LINK LIST is throwing error 

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#6337]
## Expected behavior and actual behavior

When we create a new vertex (of type 'employee') that has a property 'subordinate' of type link list or type 'employee' it throws the following error.

"has been declared as LINKLIST but has null record (probable a deleted record?)"

the created vertex has two properties, one is 'name' which is a string type and another is 'subordinates' of type LINK LIST of type employee.

## Steps to reproduce the problem

Vertex v=graph.addVertex("class:employee");
v.setProperty("name", "nathan");

## Important Questions
this a bug.
When the property subordinates was created we set the below properties to avoid this issue, but it did not work.
p.setMandatory(false);
p.setNotNull(false);

 
### Runninng Mode
- Embedded, using PLOCAL access mode

### OrientDB Version
orientdb-community-2.1.9

### Operating System
Windows

### Java Version
- 8

**Comment by tglman** [comment]
hi @smallik,

Not sure i got your problem, i did this tow test cases and they go without problem:
```java
@Test
  public void testLinkSetProperty() {
    OrientVertexType type = graph.createVertexType("Test");
    type.createProperty("name", OType.STRING);
    type.createProperty("sub", OType.LINKSET, type);
    OrientVertex vertex = graph.addVertex("class:Test");
    vertex.setProperty("name", "name");
    vertex.save();
    assertEquals(vertex.getProperty("name"), "name");

  }

  @Test
  public void testLinkSetPropertyTwo() {
    OrientVertexType type = graph.createVertexType("Test");
    type.createProperty("name", OType.STRING);
    type.createProperty("sub", OType.LINKSET, type);
    OrientVertex vertex = graph.addVertex("class:Test");
    OrientVertex vertex1 = graph.addVertex("class:Test");
    vertex.setProperty("name", "name");
    Set<OrientVertex> arrays = new HashSet<OrientVertex>();
    arrays.add(vertex1);
    vertex.setProperty("sub", arrays);
    vertex.save();
    assertEquals(vertex.getProperty("name"), "name");
    Iterable<OrientVertex> set = vertex.getProperty("sub");
    assertEquals(set.iterator().next().getIdentity(), vertex1.getIdentity());

  }
```

**Comment by smallik** [comment]
The error will be thrown only when you commit.
Please try that.

**Comment by smallik** [comment]
Sorry, this is not an issue. I was looking at the wrong code.
