### ISSUE TITLE
ODatabaseDocumentTx query doesnot return relevant object type

### ISSUE THREAD

**Issue by rishabh-jain** [orientechnologies/orientdb#6338]
## Expected behavior and actual behavior

ODatabaseDocumentTx query(new OSQLSynchQuery<T>(queryString) must return List<T>, but this returns OConcurrentResultset<T1>, where type of T1 is always ODocument.
## Steps to reproduce the problem

ODatabaseDocumentTx _db = dbPool.acquire();

String queryString = "select @rid from testTable where id = 1";

List<ORID> oridList = _db.query(new OSQLSynchQuery<ORID>(queryString));

"oridList" should be of type ORID, instead comes out to be ODocument; which makes it difficult to use the relevant method.
### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 0
### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by lvca** [comment]
The result is always a document. In your case, it will contain a property "rid".
