### ISSUE TITLE
put a ArrayList to a property of Vertex

### ISSUE THREAD

**Issue by NLPScott** [orientechnologies/orientdb#6340]
## Expected behavior and actual behavior

I want put a ArrayList to the property of nickname,but I couldn't deal it.
OrientVertexType pvertexType = graph.createVertexType("Entity");
		pvertexType.createProperty("nickname", OType.LINKLIST,pvertexType);

Vertex vertex = graph.addVertex("class:Entity");
ArrayList<String> testList = new ArrayList<String>();
								testList.add("a");
ver.setProperty("nickname", testList);

Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode

### OrientDB Version
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Windows

### Java Version
- [ ] 7

**Comment by luigidellaquila** [comment]
Hi @NLPScott 

You should use the following instead:

```
pvertexType.createProperty("nickname", OType.EMBEDDEDLIST);
```

Thanks

Luigi

**Comment by NLPScott** [comment]
thank you very much @luigidellaquila
