### ISSUE TITLE
Studio always draws standard edge first time

### ISSUE THREAD

**Issue by tenephor** [orientechnologies/orientdb#6341]
## Expected behavior and actual behavior
When drawing a lightweight edge between vertexes in the "Graph" panel of studio, the edge arrow should be dashed. Instead, it is solid.

## Steps to reproduce the problem
1. Create a vertex class
2. Create an edge class with no constraints
3. Create two vertexes
4. Go into Graph panel in Studio, run a query to show the vertexes
5. Draw an edge between the two vertexes, select "use lightweight edge"
6. See that the drawn edge is solid.
7. Click "clear canvas"
8. Run the same query
9. See that the edge is drawn dashed.

### Runninng Mode
- [ x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x ] 8

**Comment by maggiolo00** [comment]
@tenephor 

lightweight there is misleading i will remove that. Even if you click on that checkbox the edge will be heavyweight because that is the default configuration for edge creation.

**Comment by maggiolo00** [comment]
Removed in the develop Branch
