### ISSUE TITLE
embedded contains any key

### ISSUE THREAD

**Issue by facelessTT** [orientechnologies/orientdb#6342]
## Steps to reproduce the problem

I have a table with embedded map field and NOTUNIQUE_HASH_INDEX...

now I am runnning next queries:

```
select from testTable where restrictionsMap containskey 'blah1' 
select from testTable where restrictionsMap.keys() in ['blah1', 'blah2'] 
```
## Expected behavior and actual behavior

Expecting: both queries will use index
Actual: first does, and second one does not.

If I'm doing something wrong, is there any way to speed up 'map contains any key' queries?
### Runninng Mode
- [x ] Embedded, using PLOCAL access mode
### OrientDB Version
- [ x] v2.1.x - Please specify last number: 2.1.13
### Operating System
- [ x] Linux

Thank you!!!!

**Comment by luigidellaquila** [comment]
Hi @facelessTT 

The second query cannot use an index because the comparison is made on an expression (`restrictionsMap.keys()`) not on an indexed field.

For the second query, the syntax is not properly correct, you should do
```
select from testTable where restrictionsMap.keys() contains 'blah1' or restrictionsMap.keys() 'blah2'
```


Thanks

Luigi

**Comment by facelessTT** [comment]
This looks like possible workaround, but my target is to make this query work fast....

`select from testTable where restictionsMap.keys() in (select list(restriction) from..... )`
Which is one of situations I would use it. In fact it would be handy in many other situations.
It would be great if there will be 'contains any key' operator that uses Indexes. 

Anyway, Thank you!

**Comment by luigidellaquila** [comment]
Hi @facelessTT 

I'm marking it as an enhancement, it will be taken into consideration in next releases

Thanks

Luigi

**Comment by lvca** [comment]
No need for such optimization because the first query works and it's the right way to do that.

**Comment by saeedtabrizi** [comment]
Hi @lvca I have similar query to `select from testTable where restrictionsMap containskey 'blah1'` .
What do you think about the clear and prettier to have the following query to avoid the multiple `OR ` statements in sql query :
`select from testTable where restrictionsMap containskey in ['blah1','blah2','blah3']` . 
Thanks 
Saeed Tabrizi
