### ISSUE TITLE
About new lucene spatial plugin.

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientdb#6343]
## Important Question
Hi guys, i have lucene spatial index in my current legacy orientdb version (2.1.19), so to upgrade the last version (2.2.3) i need near type searches, but in the docs not seems include that function only ST_Within and ST_DWithin, so how can i perform a query that return a list with all near points from one point and a specific max-distance using the new lucene spatial plugin?

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 3

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by maggiolo00** [comment]
hi @alexmm11 

you can use ST_DWithin to achieve that.

**Comment by alexmm11** [comment]
Ok, i just tried to make a test, but i couldn't even create a location property for my class.

I got this error:

![alex skynet -opt-orientdb-bin_088](https://cloud.githubusercontent.com/assets/521303/16342228/a2817f76-39f6-11e6-812a-625dc9c8c92c.png)

**NOTE:** I already have the orientdb-spatial-2.2.3-dist.jar in orientdb-community-2.2.3/lib/

**Comment by maggiolo00** [comment]
hi @alexmm11 

seems you have a typo on embedded type
`embbedded`

**Comment by alexmm11** [comment]
But the example in documentation is this:

![seleccion_089](https://cloud.githubusercontent.com/assets/521303/16343118/05f5cc48-39fb-11e6-9bdb-9fec97ecc2e4.png)

http://orientdb.com/docs/2.2/Spatial-Index.html

Which is the right way then?

**Comment by maggiolo00** [comment]
hi @alexmm11 

you did write

```SQL
create property Place.location embbeded OPoint
```
instead of 
```SQL
create property Place.location embedded OPoint
```

**Comment by alexmm11** [comment]
Yea sorry you are right!

**Comment by alexmm11** [comment]
@maggiolo00  Thanks for your support!

Now i have this class named Place:

![seleccion_090](https://cloud.githubusercontent.com/assets/521303/16345235/768c5642-3a06-11e6-9fbe-091485edba17.png)

I need a list of all near locations to coordinates -99.649966, 19.288085  and a max-distance to 2 km for example.

I tried this query:

```
select from Place where ST_DWithin("POINT (-99.649966 19.288085)", "POINT (-99.649966 19.288085)", 2.0) as distance
```

But i got this error :(

![seleccion_091](https://cloud.githubusercontent.com/assets/521303/16345577/459817fe-3a08-11e6-87ea-ae84405d7c7b.png)

What am i doing wrong?

**Comment by maggiolo00** [comment]
hi @alexmm11 

the syntax is here
http://orientdb.com/docs/2.2/Spatial-Index.html#stdwithin

This should work
```SQL
select from Place where ST_DWithin(location, "POINT (-99.649966 19.288085)",2.0) = true
```

**Comment by alexmm11** [comment]
Hi @maggiolo00 thanks!

Yes that query works but there is something wrong with it. The spatial index seems not working.

Let me explain:

1. The spatial index is in my Place class:
![seleccion_092](https://cloud.githubusercontent.com/assets/521303/16392113/d2290426-3c6f-11e6-96e8-ca5a5e8b6b4f.png)

2. The location of places and the search point are those below:
![seleccion_093](https://cloud.githubusercontent.com/assets/521303/16392545/155a444c-3c72-11e6-9f34-4605786a5735.png)

3. The query always returns the same result, even places that are to more than 2 kilometers away or if i change de search point the result is always the same:
![seleccion_094](https://cloud.githubusercontent.com/assets/521303/16392782/3fdf6890-3c73-11e6-8a20-07baa8f22c4f.png)

4. And the explain command displays that no index is used in the query:
![seleccion_095](https://cloud.githubusercontent.com/assets/521303/16392930/0660e958-3c74-11e6-9d62-dd8931d21e8f.png)

The near method in orientdb 2.1.19 works pretty fine, always returns only the places within the max-distance and sorted by distance.

I did something wrong?

**Comment by maggiolo00** [comment]
hi @alexmm11 

can you provide an example dataset?

**Comment by alexmm11** [comment]
Hi @maggiolo00 

Yes: [SpatialIndexTest.zip](https://github.com/orientechnologies/orientdb/files/337651/SpatialIndexTest.zip)

**Comment by alexmm11** [comment]
Hi, some news?

**Comment by maggiolo00** [comment]
hi @alexmm11 

the problem is that the new module is using 

this Spatial Reference system and units are degrees 
http://spatialreference.org/ref/epsg/wgs-84/

If you insert in PostGis the same data and execute

select ST_Distance(ST_GeomFromText('POINT(-99.642128 19.290116)'),ST_GeomFromText('POINT(-99.647820 19.271112)')) 

you will get the same result back. 

I will add this function to allow to do that.

http://postgis.net/docs/manual-1.5/ST_Distance_Sphere.html

**Comment by maggiolo00** [comment]
hi @alexmm11 
Function ST_Distance_Sphere implemented. I'm adding the doc now. It will be available in the next release of the plugin 2.2.4 
Thanks 
Enrico

**Comment by maggiolo00** [comment]
@alexmm11 
Your query then would be something like this

```
select from Place where ST_Distance_Sphere(location, ST_GeomFromText("POINT (-99.638808 19.286951)")) < 1000
```
where 1000 is expressed in meters

Thanks

**Comment by alexmm11** [comment]
Hi @maggiolo00 
Nice! I have some questions:
This query returns sorted results or any order? Or i have to use order by asc or desc?
Is the distance returned?

**Comment by maggiolo00** [comment]
@alexmm11 
sorted by distance. from the nearest to the furthest.
I've updated also the docs.
https://github.com/orientechnologies/orientdb-docs/blob/2.2.x/Spatial-Index.md

Thanks

**Comment by alexmm11** [comment]
Ok @maggiolo00 thanks!
