### ISSUE TITLE
Distributed Cluster Issue (Orientdb 2.1.16):  error: file with name 'file_xxx-yyy-zzz.irs' does not exist in storage

### ISSUE THREAD

**Issue by mohilkhare** [orientechnologies/orientdb#6345]
We were running cluster of 3 nodes and it was stable for while, until we exceeded disk space on one of the cluster nodes and decided to restart orientdb on all 3 after cleaning up disk space on that cluster node. After that we started seeing this error on all 3 nodes. I think after disk space exceeded on one node, some of the vertices went into bad state. Is it a known issue ? And how to recover such cluster ?

**Comment by laa** [comment]
@mohilkhare could you send full stack trave of error ?

**Comment by laa** [comment]
Was stack trace the same on single node and on the rest of nodes ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
