### ISSUE TITLE
DELETE EDGE in the SQL batch occurres wired warning log.

### ISSUE THREAD

**Issue by gongdo** [orientechnologies/orientdb#6347]
## Expected behavior and actual behavior
**Expected**
Executes a transaction that contains `DELETE EDGE X TO {something}`. And it works without any warnings nor problems.

**Actual**
It works anyway, but a warning occurred like this:
> WARNI {db=test} Auto transaction starting is turned off for the graph, but already started transaction is left open.Commit it manually or consider disabling auto transactions while creating the graph or its factory. [OrientGraph]

## Steps to reproduce the problem

```
/* turn off the SQL Graph transaction */
ALTER DATABASE custom txRequiredForSQLGraphOperations=false;

/* prepare some items. */
CREATE CLASS Foo EXTENDS V;
CREATE CLASS Bar EXTENDS V;
CREATE CLASS Goes EXTENDS E;

CREATE VERTEX Foo SET name='Foo';  /* it produces #21:0 */
CREATE VERTEX Bar SET name='Bar';  /* it produces #25:0 */
CREATE EDGE Goes FROM #25:0 TO #21:0;
/* now #25:0 is connected to #21:0 via `Goes` edge. */

/* run following commands as a single batch in the Studio */
BEGIN;
LET $bar = CREATE VERTEX Bar SET name=uuid();
/* delete all previous `Goes` edge to the #21:0 */
DELETE EDGE Goes TO #21:0;
CREATE EDGE Goes FROM $bar TO #21:0;
COMMIT;
SELECT FROM $bar;
```

Something wired one is, when I set `txRequiredForSQLGraphOperations=true`, then the warning occurs twice. Both `DELETE EDGE` and `CREATE EDGE`.

## Important Questions
I've never seen those behavior until 2.1.x.
It looks like the `CREATE EDGE` and/or `DELETE EDGE` commands break the transaction into separated transactions.
What this warning exactly means?
Is there any limited sql commands in the batch operation?

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote

### Misc
I'm using single, local Community Edition.

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by maggiolo00** [comment]
Hi @gongdo it was only a bug in logging.
I've fixed here
https://github.com/orientechnologies/orientdb/commit/f7bd2d52ec808616610bf15bcdb431766c8cec1b

It will be available in 2.2.4
Thanks
Enrico
