### ISSUE TITLE
Feature Request: Support for check constraints

### ISSUE THREAD

**Issue by francisco1844** [orientechnologies/orientdb#6349]
New feature request.

To support check constraints. Example from a RDBMS (Postgresql)
- At table creation
  CREATE TABLE products (
  product_no integer,
  name text,
  price numeric CHECK (price > 0)
  );
- After table exists
  ALTER TABLE distributors ADD CONSTRAINT zipchk CHECK (char_length(zipcode) = 5);
  ALTER TABLE distributors ADD CONSTRAINT zipchk CHECK (lower(name) = name);

I am new to OrientDB so not sure of the correct OrientDB syntax.. for one I have not seen a way to create properties when one create a class so the example above for create may not apply.. Or perhaps may need to be placed on create properties.

**Comment by smolinari** [comment]
Not sure, but I believe this could be done using a function with `DEFAULT`.

http://orientdb.com/docs/2.2/SQL-Alter-Property.html
http://orientdb.com/docs/2.2/Functions-Creation.html

So, for your first example, you'd have something like

`CREATE PROPERTY products.price DOUBLE`
`ALTER PROPERTY products.price DEFAULT checkPrice()`

Then make a Javascript function, which would check the price and return an error, if it is wrong. 

As for creating properties with the class, this isn't possible with ODB, unfortunately. See https://github.com/orientechnologies/orientdb/issues/5751

Scott

**Comment by francisco1844** [comment]
@smolinari sorry was not clear (just changed subject to include the words feature request). What I would like, in some future,  is to have the same functionality, and syntax, as I have in a RDBMs. Even if we start with the simplest of checks like: min, max, lower / upper. Some of the constraints likely already can be done, but with a different syntax.

There are many features in OrientDB available that someone coming from a RDBMs like myself would not even know to look for. I think having the SQL syntax with all the power of OrientDB behind makes it easier for a broader audience to get up to speed..

**Comment by francisco1844** [comment]
@smolinari  totally agree on wanting #5751 
We need to hash out details, but it would be nice when we have it. That was one of the things that I found missing. If anything I think that is far more needed that this.. so this likely should be a low priority task.. Although it is basically adding new syntax to something that I believe already exists. See #5360

**Comment by mmacfadden** [comment]
@francisco1844 Is the main requirement, in your opinion, to have the ability to add constraints to specific fields in a class, such that the constraint can be any arbitrary expression?  There are a couple things in my mind.

1) Are the constraints added to the properties, or to the Class (e.g. Table)?  You some what mix the two above in your example.
2) Are the constraints allowed to other fields in the same row / object on INSERT or UPDATE.  Meaning can I say something like CHECK (min > 0 AND min < max).  Where min and max are fields in the document.
3) When are the evaluated.  So say I have this:

```
CREATE CLASS test (
foo: Integer,
bar: Integer CHECK (bar > foo)
)
```

And then say I do:
```
INSERT INTO test SET foo = 10, bar = 20
```
This should pass.  But now I do:
```
UPDATE TEST SET foo = 30
```
The constraint is on the bar property, which I am not modifying.  But clearly modifying foo to be larger than bar violates bar's constraint.  So it seems like all constraints on all fields would need to be checked whenever any part of the object changes (unless we build some dependency graph between constraints and fields)?

Thoughts?

**Comment by francisco1844** [comment]
@mmacfadden  in the RDBMs world a check constraint can be pretty much anything that evaluates to true. Would be nice to, eventually, have that level of flexibility.

My suggestion for ODB would be to start with whatever is easiest, such as min, max and anything else that is already supported with a different syntax. That would be phase 1.Then evaluate if it would be possible, without a lot of work, to have  any expression. I am most familiar with Postgresql, but I believe the check constraint is either part of the standard or at least a very common construct used in RDBMs.

**Comment by smolinari** [comment]
I guess this suggestion would be a matter of making something similar to what `DEFAULT` already does, but with the ability to add more than one default (not sure if that isn't already possible now, to be honest).

Scott

**Comment by mmacfadden** [comment]
@smolinari, I am not sure that this is really related to default at all.  Default is supposed to result the default value for a property.  Eg.  A class Order, with a property of named orderDate of type Date.  If you set the DEFAULT as such:

```ALTER PROPERTY Order.orderDate = sysdate()```

Then when you insert into the Order class, if you do not supply an orderDate property, the order day will get set to the evaluation of the DEFAULT expression, which in this case would be sysdate().

This, I think, is entirely different from what is being asked for here.  Here we want to evaluate a function when a value IS supplied, whereas DEFAULT is evaluated when a value is NOT provided.  Also, typically DEFAULT is only applied when INSERTing, but not UPDATEing.  A check constraint is evaluated for both.

**Comment by smolinari** [comment]
Yeah. You are right. Nevermind. :smile: 

Scott

**Comment by smolinari** [comment]
Ok. Thought about this more. I was on the wrong track, but in the right area. LOL! 

This suggestion is like making a dynamic trigger, which triggers on `onBeforeUpdate` and `onBeforeInsert`, but with the same function. 

So, instead of having to make OTriggered a parent class and writing out the two property alterations with the two triggers to the same function, a user could just write `CHECK` with the function and ODB does the work of adding the triggers and parent class in the background.

Does that make more sense?

Scott

**Comment by mmacfadden** [comment]
@smolinari, conceptually I think you are more on the right track.  I am not sure if we would actually use the OTriggered directly as they are, or if we need something new.  What I mean is that, I don't know if this is just syntax updates, or if we actually need some new functionality on the server.  We COULD just make it syntax sugar for setting triggers.  However, then the check constraint might show up in a list of triggers, or might be something that you could remove independently (e.g. remove the insert trigger but leave the update trigger).  I also think that if you looked at the meta data for the property you would want to see the constraint there, rather than it being a property on the parent.

So in concept, I think you are correct.  And, one could some what implement such a check constraint now using Triggers as you point out (which is a great work around by the way), but I think there is still some design to be done!!!

**Comment by smolinari** [comment]
Sure thing. I agree it might not be a wise decision to just make `CHECK` syntactic sugar over OTriggered and the added custom attributes. I'd even go so far as to say, the custom attribute thing isn't really good syntactically either. I mean, "CUSTOM" to create a "TRIGGER"? Hmm.....

Anyhow. This is going to be real fun for 3.0. I hope you will continue to help with 3.0 too.

Scott

**Comment by lvca** [comment]
I like this enhancement, :+1
