### ISSUE TITLE
Add support of group by multiple fields

### ISSUE THREAD

**Issue by Koc** [orientechnologies/orientdb#6350]

**Comment by luigidellaquila** [comment]
Hi @Koc 

You can already do it, eg.
```
SELECT name, surname, count(*) FROM V GROUP BY name, surname
```

Thanks

Luigi

**Comment by Koc** [comment]
http://orientdb.com/docs/master/Commands.html

> GROUP BY Designates field on which to group the result-set. In the current release, you can only group on one field.

Docs looks like outdated
