### ISSUE TITLE
Distributed : Wrong user/password to [connect] to the remote OrientDB Server instance

### ISSUE THREAD

**Issue by mindnuts** [orientechnologies/orientdb#6351]
## Expected behavior and actual behavior

Expected is all the nodes in the cluster are able to talk to each other and propagate any SCHEMA / DATA changes. 

Actual behavior, In my tests on 2.2.3 i am having same issues as reported in #6104. Nodes see each other but the second node onwards they are always in the "startup" mode and the schema is never received by them.
## Steps to reproduce the problem

Run 2+ nodes in cluster mode with multicast disabled and TCP-IP joining. Run first node with no database and create a fresh database. Run the second node. It should join the cluster and receive Schema and any updates
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x ] Remote
### Misc
- [ x] I have a distributed setup with multiple servers. How many? 3
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ x] v2.2.x - Please specify last number: 2.2.3
### Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [ x] 8

Edit: Adding logs from both the nodes
Core-01 Log: https://gist.github.com/mindnuts/b69226ed2a9f3cb81d88841e90895c30
Core-02 Log: https://gist.github.com/mindnuts/f9d51220997ee8460b9bd81ef768ad84

**Comment by lvca** [comment]
@mindnuts do you have any logs of the 2 servers? Have you also tried to create the database before to start the server1?

**Comment by mindnuts** [comment]
@lvca Added logs from both the nodes. I am now trying to use already created db. Will report here.

**Comment by mindnuts** [comment]
@lvca Tried with a pre created DB but the results are same. The node core-02 never reaches "Online" stage as there is error:

from core-02
```2016-06-27 13:47:00:548 INFO  Starting distributed server 'core-02' (hzID=-1)... [OHazelcastPlugin][core-02] Error on starting distributed plugin
com.orientechnologies.orient.core.exception.OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance```

from core-01
```+--------+--------+--------------------------------+-----+---------+---------------+---------------+-------------------------+
|Name    |Status  |Databases                       |Conns|StartedOn|Binary         |HTTP           |UsedMemory               |
+--------+--------+--------------------------------+-----+---------+---------------+---------------+-------------------------+
|core-02 |STARTING|                                |0    |13:46:49 |172.18.0.5:2424|172.18.0.5:2480|62.95MB/491.00MB (12.82%)|
|core-01*|ONLINE  |DbStorage=ONLINE (MASTER)|0    |13:46:18 |172.18.0.5:2424|172.18.0.5:2480|64.60MB/491.00MB (13.16%)|
+--------+--------+--------------------------------+-----+---------+---------------+---------------+-------------------------+
```

**Comment by lvca** [comment]
That could be only a problem with logs. Did you check node core-02 is online? Just login on core-02 node with studio and execute any query .

**Comment by mindnuts** [comment]
@lvca I did check both the Database servers using Studio. The first node has the DB precreated and i am able to run queries against it:
![6b11f0ce5be563a10f70de5fd7618995](https://cloud.githubusercontent.com/assets/8411896/16411822/ab7e467e-3d46-11e6-8e9a-bfb9b4c3e69e.png)

On the second joiner node, there is no DB configured:
![d4179a02a9fed324425959c13f55bc3b](https://cloud.githubusercontent.com/assets/8411896/16411848/caa31fc0-3d46-11e6-8519-51caedb91853.png)

**Comment by lvca** [comment]
Ok,so the problem seems to rely in the security: 

```
from core-02 2016-06-27 13:47:00:548 INFO Starting distributed server 'core-02' (hzID=-1)... [OHazelcastPlugin][core-02] Error on starting distributed plugin com.orientechnologies.orient.core.exception.OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance
```

Could you please check the root's password of both nodes if they are set (try logging on both nodes with root user).

**Comment by mindnuts** [comment]
@lvca Both the nodes are using the same Docker image created using the same configuration. For the latest test i started with brand new VM and started "Core-01" with DB precreated. Then i started the second node with no DB.  I am able to login to the "Core-01" DB instance with the default root/root credentials. However, i am not able to login to the second DB node "Core-02". 

I went inside "Core-02" container and this is what is added(guest user, root user remains as is) to the orientdb-server-config.xml file:

```
<user resources="*" password="root" name="root"/>
        <user resources="connect,server.listDatabases,server.dblist" password="{PBKDF2WithHmacSHA256}BCA704D4CCC0EB49C590A87682FCBAB70D2EC3A569FE88A0:327103661141E6981A99947B27B87590AC74BD505D86E716:65536" name="guest"/>
```

When i checked inside "Core-01" i found the same configuration for users root and guest.

**Comment by mindnuts** [comment]
@lvca I was trying to debug it more. Looking at the errors i could see that there could be an issue in connectivity.

Log from the Cluster leader(Core-02), there is socket bound to address 172.18.0.5:5701
```
2016-06-28 12:16:31:394 INFO  [172.17.8.102]:5701 [orientdb] [3.6.3] Established socket connection between /172.18.0.5:5701 and /172.17.8.101:42098 [TcpIpConnectionManager]
2016-06-28 12:16:37:396 WARNI [core-02] Added new node id=Member [172.17.8.101]:5701 name=ext:fc4f55b6-5f8d-49b5-b2f7-2e63fb53041d [OHazelcastPlugin]
2016-06-28 12:16:37:397 INFO  [172.17.8.102]:5701 [orientdb] [3.6.3] 

```

On the Joiner (Core-01) there is the error in the log
```
2016-06-28 12:16:31:401 INFO  [172.17.8.101]:5701 [orientdb] [3.6.3] Established socket connection between /172.18.0.3:42098 and /172.17.8.102:5701 [TcpIpConnectionManager]
2016-06-28 12:16:37:398 WARNI [172.17.8.101]:5701 [orientdb] [3.6.3] Ignoring received partition table, startup is not completed yet. Sender: Address[172.17.8.102]:5701 [InternalPartitionService]
2016-06-28 12:16:37:408 INFO  [172.17.8.101]:5701 [orientdb] [3.6.3] 

Members [2] {
	Member [172.17.8.102]:5701
	Member [172.17.8.101]:5701 this
}
 [ClusterService]
2016-06-28 12:16:39:429 INFO  [172.17.8.101]:5701 [orientdb] [3.6.3] Address[172.17.8.101]:5701 is STARTED [LifecycleService]
2016-06-28 12:16:39:433 INFO  Starting distributed server 'core-01' (hzID=-1)... [OHazelcastPlugin][core-01] Error on starting distributed plugin
java.net.NoRouteToHostException: No route to host
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.orientechnologies.orient.client.binary.OChannelBinaryClientAbstract.<init>(OChannelBinaryClientAbstract.java:68)
	at com.orientechnologies.orient.client.binary.OChannelBinarySynchClient.<init>(OChannelBinarySynchClient.java:32)
	at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.connect(ORemoteServerChannel.java:143)
	at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.<init>(ORemoteServerChannel.java:68)
	at com.orientechnologies.orient.server.distributed.ORemoteServerController.<init>(ORemoteServerController.java:35)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.getRemoteServer(ODistributedAbstractPlugin.java:672)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:208)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1182)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:389)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Exception in thread "main" com.orientechnologies.orient.server.distributed.ODistributedStartupException: Error on starting distributed plugin
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:241)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1182)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:389)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

```

The local network 172.18.0.x is not accessible outside of the container. Could this be the issue?

**Comment by lvca** [comment]
It looks like the problem. What's your setting in orientdb-server-config.xml?

**Comment by mindnuts** [comment]
@lvca Here you go (orientdb-server-config.xml):
https://gist.github.com/mindnuts/3321a18f5cadf0cbbc63bf0204c7ed93

**Comment by lvca** [comment]
Instead of "0.0.0.0", could you bind the interface that is visible?

**Comment by mindnuts** [comment]
@lvca I am not able to make Orientdb listen on the Machine IP of the VM
```
docker run --name orientdb -v /opt/orientdb:/orientdb/databases -p 2424:2424 -p 2480:2480 -e "COREOS_PRIVATE_IPV4=${COREOS_PRIVATE_IPV4}" -p 5701:5701 -e "ORIENTDB_NODE_NAME=core-01" localhost:5000/orientdb:cluster  dserver.sh -Dhazelcast.ip=${COREOS_PRIVATE_IPV4}
```

My Orientdb-server-config
```xml
<listener protocol="binary" ip-address="172.17.8.101" port-range="2424-2430" socket="default"/>
<listener protocol="http" ip-address="172.17.8.101" port-range="2480-2490" socket="default">
```

**Comment by lvca** [comment]
@mindnuts I think this is a configuration problem with docker. Let me involve @robfrank on this.

**Comment by mindnuts** [comment]
@lvca I just ran the tests with 2.1.19 version and it worked. I am able to create a cluster and the changes are replicated correctly. Not sure why it would not work with 2.2.3 or 2.2.2 for that matter.

**Comment by lvca** [comment]
Could you please try with last 2.2.x branch?

**Comment by mindnuts** [comment]
@lvca I did try with 2.2.3 http://mkt.orientdb.com/CE-223-linux

**Comment by lvca** [comment]
Yesterday I fixed an issue could impact on this. Can you try with last 2.2.x branch or wait until next week when we will release 2.2.4.

**Comment by robfrank** [comment]
@mindnuts if run more than one container, you should map the ports only on one container, so  -p 2424:2424 -p 2480:2480 should  be passed only to the first container.

**Comment by mindnuts** [comment]
@robfrank But i am running 3 containers on 3 different "hosts".

**Comment by robfrank** [comment]
Let me recap. 
You have three different docker-machines (VMs or bare-metal), and each machine runs a single docker container with OrientDB inside configured to export ports (-p 2480....). 
Only the first container has the db provided under a volume, and others orientDB are not able to connect to each other. 
Is it right?

**Comment by mindnuts** [comment]
@robfrank  Please see the image below:
![image](https://cloud.githubusercontent.com/assets/8411896/16655465/15b6cd3a-4478-11e6-88dd-a44059bfc4a6.png)

What you wrote is true. The discovery works correctly, in the sense that a new node starting up is found by the first node, but then the hot deployment fails and the newer node never receives the Schema.

**Comment by robfrank** [comment]
Ok, it's exactly what I had in mind. I never tried such a topology, it could takes me sometime. I guess problems are arising from the network layer, but I'm not sure. Stay tuned

**Comment by mindnuts** [comment]
@robfrank Sorry to bug you, but any progress?

**Comment by lvca** [comment]
@mindnuts Is this issue still valid with 2.2.21?

**Comment by mindnuts** [comment]
@lvca I have not tried it with the latest release. Is there any cloudformation stack i could spin on ec2 to check it out quickly?

**Comment by robfrank** [comment]
I've deployed containers using compose and kubernetes. I didn't experience these problems.
