### ISSUE TITLE
Distributed: auto remove a node from the configuration after configurable seconds

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6352]
This feature will keep also a backward compatibility with 2.1 when a node was removed from the cluster. Once a node is removed from the cluster and it comes back, a full backup is needed.

**Comment by lvca** [comment]
Done. This is the setting:

    DISTRIBUTED_AUTO_REMOVE_OFFLINE_SERVERS("distributed.autoRemoveOfflineServers",
      "This is the amount of time (in ms) to automatically remove a server from the distributed configuration after a while it's OFFLINE. -1 = never, 0 = immediately, >0 the actual time to wait",
      Long.class, -1),

Set it to 0 if you want immediate removal (like in <v2.2) or set a timeout. By default -1 means the node remains in the configuration until you expressly remove it with `HA REMOVE SERVER <server>` command.

**Comment by smolinari** [comment]
@lvca 

This is the amount of time (in ms) the server has to be OFFLINE, before it is automatically removed from the distributed configuration.

Is that better?

Scott

**Comment by lvca** [comment]
You're right: updated, thanks
