### ISSUE TITLE
Querying a previously abstract class returns an empty result set

### ISSUE THREAD

**Issue by SDIPro** [orientechnologies/orientdb#6353]
Tested against 2.2.4-snapshot

Simple to reproduce:
```
create class Test abstract
alter class Test abstract false
insert into Test set Name = "Jill"
```
The record will be created, and you can retrieve the record by RID fine.

However, "select from Test" will return nothing.

**Comment by luigidellaquila** [comment]
Hi @SDIPro 

Fixed in 2.2.x and develop branches

Thanks!

Luigi
