### ISSUE TITLE
Leverage OriendDB inheritance within Ferma OGM

### ISSUE THREAD

**Issue by giulio-quaresima** [orientechnologies/orientdb#6358]
Dear Team members,
first of all I am very sorry for my poor english.

## Expected behavior

I am in my very first try in the "NoSQL" world. As I come from Hibernate / JPA experience, I would like to use the Ferma OGM framework on top of OrientDB Graph. So I have wrote some interfaces annotated with `com.syncleus.ferma.annotations.*` annotations and I have registered them within a `types` collection, calling `new com.syncleus.ferma.DelegatingFramedTransactionalGraph<OrientGraph>(orientGraph, true, types)` and finally I added some vertices from every type in `types`, calling `addFramedVertex(type)` method.
I expected to find in the Schema a new OrientDB Class for each Class contained in `types` collection.

## Actual behaviour

But when I explored the Schema with Studio, I didn't see any new classes, but instead all vertices I added saved as `V` class, having the type information stored as 'ferma_type' property. 
As I read [here](http://wiki.syncleus.com/index.php/Ferma:Type_Resolution#Custom_Type_Key), this seems the default expected behaviour of Ferma, with the only opportunity to change the property name.

## Important Questions

So can I leverage the wonderful multiple inheritance mechanism of OrientDB with Ferma OGM classes? As a second chance, are there any way to use POJOs (as I always did in JPA) **on top of the GRAPH API** so one can automatically reflect the Java classes structure in actual OrientDB classes?

Thank you
Giulio Quaresima

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by tglman** [comment]
hi @giulio-quaresima,

We have no problem on this kind of management on orientdb side, and we have some specific api that would allow this case, did you try to ask the same question on the Ferma issue tracker? We have no control on Ferma code, but we are more than happy to contribute to it.

Regards

**Comment by giulio-quaresima** [comment]
Thank you. It seems that Ferma issue tracker doesn't work these days, and the project doesn't seem very active as well. Maybe I will do the job using directly the Graph API and writing some mapping between it and my domain model.

**Comment by giulio-quaresima** [comment]
I resolved the issue using the wonderful Frames API and its annotation
`@TypeField ("@class")`
in my domain supertype.
Thanks

**Comment by lvca** [comment]
Cool, I didn't know you could do that. @giulio-quaresima would you like to write a blog post about FERMA and OrientDB, making the life of future developers with FERMA easier?

**Comment by giulio-quaresima** [comment]
Yes, I'd like very much to contribute! But to do the job I used **Frames**, not Ferma. With Ferma I didn' succeed: i tried with 
`new PolymorphicTypeResolver(reflectionCache, "@class")`
but I got 
`java.lang.IllegalStateException: The class V cannot be found`.
Browsing the source code, it is clear that Ferma, with such configuration, when you call `addFramedVertex(MyDomainEntity.class)`, first create the Vertex in the graph, and then call `vertex.getProperty("@class")` to check if the property already exists (expecting not with newly created Vertices), but the `@class` property already contains "V", as for any newly created vertex in OrientDB, and `Class.forName("V")` doesn't work, obviously. 
Incredibily, in the [Ferma: Comparing the Alternatives](http://wiki.syncleus.com/index.php/Ferma:Comparing_the_Alternatives#Feature_Breakdown) page it is stated that Frames doesn't let "customize the way type information is stored in the graph". On the contrary, Frames support such a customization, through `@TypeField` and `@TypeValue` annotations, and as I can see it addresses also the particular behaviour of OrientDB's `@class` property: with Ferma, as I showed above, it doesn't work, and, also, `PolymorphicTypeResolver` let to customize the property name only, leaving the property value bounded to the full qualified name of the class.
With Ferma I encountered other limitations, too. For example, I wonder how I could simply manage embedded properties (another plus of your multi-model architecture), while with Frames it's easy to do with the great flexibility provided by the `@JavaHandler` annotation. Probably it's possible with Ferma too, with concrete classes extending VertexFrame, but it seems more cumbersome.
In general, Frames appears better designed, with a more declarative approach and much more flexibility, and it's also better documented: too sad that Frames has been discarded from Tinkerpop 3!

**Comment by lvca** [comment]
What about a blog post with Frames? :-)

**Comment by giulio-quaresima** [comment]
OK, I will do it gladly, after I have tested some other Frames functionalities. Would you give me the instructions to post to the blog?

**Comment by lvca** [comment]
You could write it in a Google Docs. The best place to write it is DZone or even on our web site.

**Comment by rajendrag** [comment]
There is a way to workaround this with Ferma, you can use 
`fg.addFramedVertex("class:YourLabel", new DefaultClassInitializer<>(Something.class));`. 
This will create the vertex with @class `YourLabel` and another property `ferma_type` as well.
