### ISSUE TITLE
Distributed: Introduce DC quorum

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6359]
Even if some users has a multi-dc setting with OrientDB, there is no specific setting for Cross Data Center (DC) replication. Waiting for 3.1 with an optimized transport between DC, a nice feature to have is considering the quorum at DC level.

## Problem

In this example 3 DCs, with 3 nodes each:

    dc1[s11,s12,s13], dc2[s21,s22,s23], dc3[s31,s32,s33]

If a client is connected to the server s11 (dc1), with writeQuorum = majority, then the answer is given to the client as soon as 5 servers (9/2+1) replied. In the worst case scenario only 2 DCs could respond. 

## Solution

Introduce the new `localWriteQuorum` quorum type and allow the data center definition with a `writeQuorum` setting on it. In case this is 'majority', the client has to wait for 2 nodes on each DC before to give the answer to the user. Example:

```json
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "localDataCenter",
  "readYourWrites": true,
  "dataCenters": {
    "rome": {
      "writeQuorum": "majority",
      "servers": [
        "europe-0",
        "europe-1",
        "europe-2"
      ]
    },
    "denver": {
      "writeQuorum": "majority",
      "servers": [
        "usa-0",
        "usa-1",
        "usa-2"
      ]
    }
  },
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": [
        "<NEW_NODE>"
      ]
    }
  }
}
```

**Comment by luigidellaquila** [comment]
Hi @lvca 

are there any docs on how it works?

Thanks

Luigi

**Comment by lvca** [comment]
it's everything in the Distributed Architecture (Google Docs) shared internally months ago. I'm updating the documentation with such content right now.

**Comment by luigidellaquila** [comment]
Great, thanks!!!

Luigi

**Comment by lvca** [comment]
Here we go: http://orientdb.com/docs/2.2.x/Data-Centers.html

**Comment by RAndrews137** [comment]
Much appreciated   :)
