### ISSUE TITLE
Setup process is not intuitive

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb#6361]
## Expected behavior and actual behavior

For some reasons the password already contains a phantom asterisk symbol from the beginning. When I ran `server.sh` script for the first time I got distracted by a new email message from the browser window. 

When I got back to the terminal, I saw that the password field already contained a symbol. So I thought that I'd already started typing my password for a root user. So I just finished typing the rest of the password (i.e oot in my case) and called it a day. 

When I got back to a server the next day and tried to authenticate, I realized that my password didn't match. After some time I figure out that first symbol wasn't part of my password and the real password for the root user is `oot` not `root` as I thought before:

<img width="1261" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3434800/16443347/8218b9ec-3e02-11e6-8d61-db7badea1cc7.png">

Another thing that blew my mind was the fact that OrientDB can generate a new password for the `root` user if you hit an Enter key. The problem is OrientDB doesn't print this password anywhere. Even in `orientdb-server-config` the root's password is in encoded format:

<img width="1230" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/3434800/16443348/824db976-3e02-11e6-8acb-8c835736f637.png">

In the end, the whole setup process wasn't as smooth as I expected.
### Runninng Mode
- [x] Remote
### OrientDB Version
- [x] v2.2.x - Please specify last number: 3
### Operating System
- [x] MacOSX
### Java Version
- [x] 8

**Comment by lvca** [comment]
When the server asks for the password, you didn't press any button and you can see the `*`, right? If you insert "root", the password is taken. The first `*` is to protect by showing any digits.

About the auto-generated password, we should print it.

**Comment by maseev** [comment]
> When the server asks for the password, you didn't press any button and you can see the *, right?

That's right.

> If you insert "root", the password is taken. The first * is to protect by showing any digits.

What digits? Have you ever seen how the terminal accepts passwords in Linux-based OS or OS X? You don't even see what you're typing. From the security point of view, this approach is even better because nobody will be able to say how many symbols your password consists of by looking at your screen over your shoulder.

**Comment by lvca** [comment]
Showing the `*` in place of the characters is a good compromise for the user that shows the console is reading the password. Like when you enter your password in any web forms.

**Comment by maseev** [comment]
Well, at least, there shouldn't be a starting `*` symbol because it's very misleading. It looks like I already typed a symbol.

**Comment by lvca** [comment]
This is a limitation with the way the password protection is managed via console. I'm closing this issue because not really relevant.
