### ISSUE TITLE
How to show two query results next to each other

### ISSUE THREAD

**Issue by yogamurthy** [orientechnologies/orientdb#6363]
Query1:

select expand(out('fieldName here')) from BillerAcct where blAccountNumber = '123456789'

Query2:

select * from BillerAcct where blAccountNumber = '123456789'

Now i want to  show the results of query 2 next to query 1.

What i have tried so far,

 1) select *,expand(out('fieldName here')) from BillerAcct where blAccountNumber = '123456789' --star not working in this method

2) select expand($a).append(expand($b))
let
$a= (select expand(out()) from BillerAcct where blAccountNumber = '9919225127801' ),
$b=(select * from BillerAcct where blAccountNumber = '9919225127801' ) 

it only shows only one rsult set

3) document Merge is not working either.

Any help or insights will be greatly appreciated

**Comment by luigidellaquila** [comment]
Hi @yogamurthy 

what you need here is `unionAll()` function:
```
select expand(unionAll($a, $b))
let
$a = (select ...),
$b = (select ...) 
```
I hope it helps

Thanks

Luigi
