### ISSUE TITLE
error creating abstract class in studio (wrong order in syntax)

### ISSUE THREAD

**Issue by norpan** [orientechnologies/orientdb#6365]
## Expected behavior and actual behavior
Creating an abstract class in studio gives an error:
Error parsing query: CREATE CLASS APA ABSTRACT extends E ^ Encountered " <EXTENDS> "extends "" at line 1, column 28. Was expecting one of: <EOF> ";" ... 
 DB name="test"

It seems that the syntax should be "CREATE CLASS APA extends E ABSTRACT" instead.

## Steps to reproduce the problem
Go into Schema
Choose "New class"
Class name "APA"
Extend E
Check "Abstract"
Click "Save"

### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number:
- [x] v2.2.x - Please specify last number: 3

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by maggiolo00** [comment]
Hi @norpan 
Fixed
