### ISSUE TITLE
Support of RDF / SPARQL

### ISSUE THREAD

**Issue by smith64fx** [orientechnologies/orientdb#6366]
Hey guys,
I'm very grateful for this awesome open source project!

Right now I'm desperately looking for a triplestore, where I can import the [wikidata](https://www.wikidata.org/wiki/Wikidata:Database_download/de) dump.

My Team and me want to create a social network based on semantic technology. For this we need a scalable solution. Unfortunately almost every RDF triplestore is commercial and the license for 1 machine is about 10.000$ / year -.-

Is there any workaround to use RDF and SPARQL in OrientDB?

**Comment by smolinari** [comment]
To the question, is it possible to store wikipedia data as a graph within ODB? The answer is...absolutely. However, you won't be able to query the data with SPARQL (which you already knew). You can, however, use ODB's own SQL-like query language to query for your data. ODB's query language, due to the nature of ODB, is actually more capable than SPARQL and thus, ODB can do more for you in general.

This little (and cool) example shows the possibilities.

http://gog.orientdb.com/index.html?utm_source=site&utm_medium=website&utm_campaign=Game+of+Graphs

Scott

**Comment by lvca** [comment]
We support SPARQL through the TinkerPop layer ;-)

**Comment by smolinari** [comment]
Hmm...interesting. But wouldn't it be much better just to use ODB's SQL? I mean, using SPARQL though a compiler to Gremlin is to me, at best, like a workaround. I'd personally never contemplate building an application over that many "abstractions". 

Or does SPARQL bring some sort of major advantage with it, that can't be done with ODB's own SQL? I'll admit, I am not knowledgeable about SPARQL at all. 

Scott

**Comment by lvca** [comment]
I'm not a fan of SPARQL either, but if you feel comfortable with it, there is a way. Anyway for performance reasons, I suggest to always use OrientDB SQL.

**Comment by andrzejmartyna** [comment]
@smolinari, one major advantage of SPARQL is that it is a standard, like SQL is.
Of course it is not so well known and accepted like SQL.
But IMHO standard, if crafted well, can bring benefits that specific implementations cannot provide.
Enough to say... without SQL being a standard RDBMS would not be so popular and so mature today. Without HTTP and TCP/IP being standards we would not have Internet today.

**Comment by lvca** [comment]
@andrzejmartyna The best would be providing a SPARQL parser that translates to OrientDB SQL, so all the optimizations would be already there. Also, it would be nice providing an importer for OWL and the support of other "semantic" technologies, but unless we find a sponsor or a partner for it, it cannot be done in the short-medium term. Sorry.

**Comment by andrzejmartyna** [comment]
@lvca, thanks for fast answer. Yes, it would be awesome to have these functions.
But IMHO it is not a must. Semantic technologies still need a few years (or more) to "stabilize".
More important is to provide quality, stable technologies to make it possible to go to production more and more frequently.
Meanwhile we should observe standardization efforts of W3C and acceptance of SPARQL in IT.
Best regards!
