### ISSUE TITLE
Database is closed error

### ISSUE THREAD

**Issue by ghatwala** [orientechnologies/orientdb#6368]
## Expected behavior and actual behavior
Getting below errors ..
Running com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest
Tests run: 5, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.303 sec <<< FAILURE! - in com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest
testDeleteVertexFromSubquery2(com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest)  Time elapsed: 0.047 sec  <<< ERROR!
com.orientechnologies.orient.core.exception.ODatabaseException: 
Database is closed
	DB name="OCommandExecutorSQLDeleteVertexTest"
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest.testDeleteVertexFromSubquery2(OCommandExecutorSQLDeleteVertexTest.java:114)

testDeleteVertexBatch(com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest)  Time elapsed: 0.102 sec  <<< ERROR!
com.orientechnologies.orient.core.exception.ODatabaseException: 
Database is closed
	DB name="OCommandExecutorSQLDeleteVertexTest"
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest.testDeleteVertexBatch(OCommandExecutorSQLDeleteVertexTest.java:74)

testDeleteVertexLimit(com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest)  Time elapsed: 0.057 sec  <<< ERROR!
com.orientechnologies.orient.core.exception.ODatabaseException: 
Database is closed
	DB name="OCommandExecutorSQLDeleteVertexTest"
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest.testDeleteVertexLimit(OCommandExecutorSQLDeleteVertexTest.java:59)

testDeleteVertexFromSubquery(com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest)  Time elapsed: 0.049 sec  <<< ERROR!
com.orientechnologies.orient.core.exception.ODatabaseException: 
Database is closed
	DB name="OCommandExecutorSQLDeleteVertexTest"
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertexTest.testDeleteVertexFromSubquery(OCommandExecutorSQLDeleteVertexTest.java:101)

## Steps to reproduce the problem

# mvn clean install

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ ] 8

**Comment by tglman** [comment]
hi @ghatwala, 

is this related to : https://github.com/orientechnologies/orientdb/issues/6210 ?

We are working on ppc64 architectures now, we will let you know as soon we can get some appropriate result.

Regards

**Comment by ghatwala** [comment]
hi @tglman  , 

Yes , it is related , appears to me that the database is getting prematurely before access to it.
Any comments on this ? ,  I am just curious to know that testing the database works perfectly on "x86" arch but fails on ppc64le . 

How could the database testing be  dependent on "arch" type ?

**Comment by tglman** [comment]
hi @ghatwala,

As far as i know now the ppc64 architecture is supported correctly, can we close this ?

Regards

**Comment by ghatwala** [comment]
hi @tglman - yes sure , please close this ticket.
