### ISSUE TITLE
Datetime field not working properly in Studio

### ISSUE THREAD

**Issue by norpan** [orientechnologies/orientdb#6369]
## Expected behavior and actual behavior

When entering a date in the date picker and then entering a time in the time picker, the date field is cleared and vice versa.
<img width="867" alt="skarmavbild 2016-06-30 kl 10 12 24" src="https://cloud.githubusercontent.com/assets/1681354/16489039/e210b788-3ed3-11e6-9eaa-6191eb394b36.png">
Works fine in Chrome.
## Steps to reproduce the problem

Add a datetime property
press "new record"
enter date
enter time
Safari version 9.1.1 (11601.6.17)
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 3
### Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by santo-it** [comment]
Hi,

Thanks for creating this issue

I am experiencing problems also in Windows 10, using Chrome Version 55.0 (when creating/editing a record from the Schema panel or adding a datetime property to an edge or vertex from the Graph Editor)
