### ISSUE TITLE
Automatic conversion between embedded rid bag and bonsai rid bag is broken in the tx mode

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6371]
Seem like there is a special update handling logic applied in the tx mode to lower the overhead on remote commit, as a side effect the conversion is broken.  `com.orientechnologies.orient.test.database.auto.ORidBagTest#testFromEmbeddedToSBTreeAndBack` will be disabled.

**Comment by taburet** [comment]
After discussion with Andrey we have decided to modify the test to support only upgrades to bonsai rid bag version, since downgrades are disabled by default.

**Comment by lvca** [comment]
What happens if a database goes distributed? Are the non embedded ridbag transformed in embedded again? This is because distributed bonsai ridbags are not supported yet.

**Comment by laa** [comment]
@lvca embedded ridbag never converted we never supported that Sergey opened that bug by mistake not functionality but test was incorrect.

**Comment by laa** [comment]
OK I will close it then
