### ISSUE TITLE
RIDs of documents referenced from the deeply nested embedded documents/collections are not stored properly in the tx mode

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6372]
Following test cases will be disabled:
`com.orientechnologies.orient.test.database.auto.ORidBagTest#testDocumentHelper`
`com.orientechnologies.orient.test.database.auto.ORidBagTest#testJsonSerialization`

**Comment by tglman** [comment]
I enabled the tests and seems to go without problem in both 2.2.x and 3.0.

Closing

**Comment by laa** [comment]
That is not true , test pass only because now we do not start TX for each document save. But problem inside of transaction (see issue description) still remains.
