### ISSUE TITLE
Inconsistency between OValidationException and OSecurityException while validating user password

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6373]
In tx mode, on `remote` storage the OSecurityException is thrown, on `plocal` the OValidationException. `com.orientechnologies.orient.test.database.auto.SchemaTest#checkErrorOnUserNoPasswd` will be modified to accept both exceptions, but we have to choose only one in the future.

**Comment by lvca** [comment]
I think it should raise only `OSecurityException`. Validation is for document validation.

**Comment by lvca** [comment]
@taburet can you change the code to just raise `OSecurityException` ?

**Comment by taburet** [comment]
@lvca rechecked the status of the issue, `remote` and `plocal` are now consistent in throwing `OValidationException` on both 2.2.x and develop branches. Is that acceptable?
