### ISSUE TITLE
SQL 'like' keyword and indexes

### ISSUE THREAD

**Issue by lucevers** [orientechnologies/orientdb#6375]
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x ] Remote

### Misc
- [ x] I have a distributed setup with multiple servers. How many? 2
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x ] v2.2.x - Please specify last number: 

### Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x ] 8

surname **like** 'Sky%'

We see that using the 'like' keyword, when properties are indexed with Lucene, will cause a very slow performance. 
In the documentation is explained the you need to use the lucene keyword and commands.
Right but now my question is:

 Which type of  index can be used together with the SQL 'LIKE' keyword'?

**Comment by luigidellaquila** [comment]
Hi @lucevers 

Current index implementations do not support LIKE evaluation, so I'm afraid for your use case you have to use LUCENE keyword and a lucene index

Thanks

Luigi

**Comment by lucevers** [comment]
oke, thanks!
