### ISSUE TITLE
[ OrientDB version >= 2.1.12 ] Token based authentication behaviour

### ISSUE THREAD

**Issue by Ostico** [orientechnologies/orientdb#6381]
Can you explain better how this kind of authentication works now?

Token authentication still not working or the behaviour is changed. 

I provided a payload for this here:
https://github.com/orientechnologies/orientdb/issues/6259
but i think that this could be a change in the behaviour more than a bug.

Php and Python drivers are not working with this functionality. 
They works with OrientDB versions < 2.1.12, so i think that something is changed.

This is the old behaviour, can you check if it is still valid?
https://github.com/Ostico/PhpOrient#persistent-connections--session-token-

Tnx

**Comment by tglman** [comment]
Hi @Ostico,

As soon as i got some time i'll try to run them with the relative tests

Regards

**Comment by Ostico** [comment]
Tnx @tglman :)

**Comment by lvca** [comment]
@tglman any news about that?

**Comment by tglman** [comment]
hi All,

I work with Ostico a while ago and fixed a few of this issues, I think also this was fixed, going to close.

Pleas @Ostico reopen if you still have problems.

Regards
