### ISSUE TITLE
Orientdb UI

### ISSUE THREAD

**Issue by magician27** [orientechnologies/orientdb#6382]
## Expected behavior and actual behavior
When i enter a query in UI , it used to keep a history of previously ran queries on that view , i dont see orientdb doing this anymore on 2.2.3 . why did you guys remove this feature ? its pretty annoying when i query something , click on record to check something and when im back i just lose that previous view . thanks

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X ] Remote

### Misc
- [ X] I have a distributed setup with multiple servers. How many? 3
- [X ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 3

### Operating System
- [ ] Linux
- [ ] MacOSX
- [ X ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ X ] 8

**Comment by maggiolo00** [comment]
hi @magician27 we did not remove that feature.
Which user did you use?

**Comment by magician27** [comment]
just the custom user that i created, i set user as admin password as admin .   i query something , then from results i click one of the rids  to see content of record , after i click back on browse button and i lose that query history

**Comment by maggiolo00** [comment]
@magician27 

are you with chrome?

What happen if you try it with a incognito session?

**Comment by magician27** [comment]
yes i am using chrome. same is happening in incognito mode as well. if i click on record then click again on browse to enter another query , everything dissapears

**Comment by maggiolo00** [comment]
@magician27 

we did not remove that feature. Probably you have the LocalStorage full. Since 2.2.11 that will be released soon, You should see a
button that you can use for clearing the LocalStorage in case it's full.
Thanks
