### ISSUE TITLE
Error on query date

### ISSUE THREAD

**Issue by joetaras** [orientechnologies/orientdb#6389]
## Expected behavior and actual behavior
I've this table with these fields:

MyTable
code STRING
fromDate DATE
toDate DATE
The content of this table is the following:

'ABC', '2016-05-01 00:00:00', '2016-05-31 00:00:00'
'DEF', '1900-01-01 00:00:00', '2099-01-01 00:00:00'
'GHI', '1900-01-01 00:00:00', '2099-01-01 00:00:00'

If I try to write this query:

SELECT FROM MyTable WHERE fromDate <= '2016-05-01'

or alternatively

SELECT FROM MyTable WHERE fromDate <= DATE('2016-05-01', 'yyyy-MM-dd')
The result is the following:

'DEF', '1900-01-01 00:00:00', '2099-01-01 00:00:00'
'GHI', '1900-01-01 00:00:00', '2099-01-01 00:00:00'

N.B. If I try to change the factor (as follow):

SELECT FROM MyTable WHERE '2016-05-01' >= fromDate

or alternatively

SELECT FROM MyTable WHERE DATE('2016-05-01', 'yyyy-MM-dd') >= fromDate

it works fine

## Steps to reproduce the problem

1. Create a table like this:

MyTable
code STRING
fromDate DATE
toDate DATE

2. Populate the table as follow:

INSERT INTO MyTable values ('ABC', '2016-05-01 00:00:00', '2016-05-31 00:00:00')
INSERT INTO MyTable values ('DEF', '1900-01-01 00:00:00', '2099-01-01 00:00:00')
INSERT INTO MyTable values ('GHI', '1900-01-01 00:00:00', '2099-01-01 00:00:00')

3. Write a query as follow:

SELECT FROM MyTable WHERE fromDate <= '2016-05-01'
or alternatively

SELECT FROM MyTable WHERE fromDate <= DATE('2016-05-01', 'yyyy-MM-dd')

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] From Studio

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.0 - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by luigidellaquila** [comment]
Hi @joetaras 

Thank you for reporting, I'll check it asap

Thanks

Luigi

**Comment by joetaras** [comment]
Thank you @luigidellaquila for your quick response.

**Comment by luigidellaquila** [comment]
Hi @joetaras 

I just fixed this issue, the fix is on branch 2.2.x and will be released in a few days with 2.2.5

Thanks

Luigi
