### ISSUE TITLE
Prepared statements with positional parameter at FROM clause 

### ISSUE THREAD

**Issue by attilapiros** [orientechnologies/orientdb#6390]
## Expected behavior and actual behavior

I would like to use prepared statements where after the FROM keyword positional parameter is given to bind to schema name right before query/command execution. 

For supporting such a flexible queries, as I see, quoted schema names should be made equal with unquoted schema names.

Example:

```
OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>("select from ?");
List<ODocument> result = database.command(query).execute("Profile");
```

Currently it queries the schema "Profile" and not Profile.
## Steps to reproduce the problem

Use the code example above.
### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [x] Embedded, using MEMORY access mode
- [x] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 
### Operating System
- [x] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by luigidellaquila** [comment]
Hi @pirosa 

Right now it's not supported, but it's not hard to do.
I'll take a look at it asap

Thanks

Luigi

**Comment by hg-jt** [comment]
@luigidellaquila: I also encountered this issue w/the docker image of Orient 2.2.6 using named parameters. Is there a workaround for this issue (e.g. in @pirosa's example, can the string value be wrapped in a subclass of SimpleNode?)
