### ISSUE TITLE
Improve speed of operations during incremental backup

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#6397]
During an incremental backup, we prevent to truncate WAL to write missed operations in the archive.
But as a result, WAL becomes huge and threads start to try to make full checkpoint before any action which will lead to performance slowdown. To prevent such situation, we should avoid making full checkpoints only because WAL file is too big but still should put DB in read only mode if there is no enough space to write data on disk.

**Comment by lvca** [comment]
:+1
