### ISSUE TITLE
NPE in OEmbeddedRidBag if OIntentMassiveInsert is declared

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6398]
Orientdb v2.2.3

OIntentMassiveInsert switches off validation. 
ODocument.validate(), besides all, deserialize fields and clears _source in  checkForFields() (that is unclear and error prone)
During commit,  if validation is switched off, _source remains filled with temporary ids in ORidBag's (so commit depends on validation). Ids are converted to persistent, but not in _source - no serialization
This invalid binary is written to storage
During deserialization, OEmbeddedRidBag cant get record with temporary RID, and fails in addEntry()

Bug is hard to catch, because ODocument.toString() fill fields - if breakpoint is set too early, everything works

Code to reproduce

```
       final ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:default").open("admin", "admin");
        final OrientGraph graph = new OrientGraph(db, false);
        graph.setUseLightweightEdges(true);
        final OrientVertexType c1 = graph.createVertexType("C1");
        c1.createProperty("p1", OType.INTEGER);
        graph.createEdgeType("parent");
        ODatabaseRecordThreadLocal.INSTANCE.get().declareIntent(new OIntentMassiveInsert());
        graph.begin();
        final OrientVertex first = graph.addVertex("class:C1");
        first.setProperty("p1", -1);
        for (int i = 0; i < 10; i++) {
            final OrientVertex v = graph.addVertex("class:C1");
            v.setProperty("p1", i);
            first.addEdge("parent", v);
            //this search fills _source
            db.command(new OSQLSynchQuery<>("SELECT from V where p1='" + i + "'")).execute();
        }
        graph.commit();
        //here NPE will be thrown
        final Iterable<Edge> edges = first.getEdges(Direction.BOTH);`
```

**Comment by tglman** [comment]
hi @vantonov1,

The problems was not the disable of the validation itself but the disable of some automatic conversion with it, i fixed this on develop and i've ready a fix for 2.2.x will be out with 2.2.5
I'll close this when i merge the fix in 2.2.x

**Comment by vantonov1** [comment]
Hello

To be precise, stack looks like that:

ORecordInternal.clearSource()
ORecordSerializerBinaryV0.deserialize()
ORecordSerializerBinary.fromStream()
ODocument.deserializeFields()
ODocument.checkForFields()
ODocument.validate()

If validation swithed off, _source is not cleared

**Comment by vantonov1** [comment]
My opinion is, that rec._source should be cleared explicitly in OAbstractPaginatedStorage.commitEntry()

**Comment by tglman** [comment]
hi @vantonov1,

The error it actually happen before, the null pointer is just a symptom, i already fixed it anyway :)

**Comment by vantonov1** [comment]
The error is happens on commit. The root problem - old serialized rec._source with temporary RID's is written to storage. This happens because on commit rec._source is not cleared. Usually, it is cleared by ODocument.validate() as a side effect, when it check fields. But it is only eventually - no validation, no serialization

Playing with side effects of some autoconvertions etc you can fix it for now, but IMHO commitEntry() should not depend on that and always do serialization - it means it should explicitly clear _source before calling rec.toStream()

**Comment by tglman** [comment]
hi @vantonov1,

I see your point, let me explain:

Temporary rid are the links used for keep the reference in the transaction for the new records before they are made persistent, in the commit method all the the temporary rids should be tracked down and replaced with persistent one, so in the _source, should never be written a temporary rid. the autoconvertion before allow us to replace the basic structure with structures that allow tracking.

Hope this help to understand the problem in a better way.

Regards/

**Comment by vantonov1** [comment]
Yes, I got it.

Autoconvertion works in the example above. Problem is, that converted persistent RIDs are not written to storage - serialization of fields just not called, because _source is present, so it looks like document already serialized.

So, to use conversion results _source should be cleaned. Now it is done only as a side effect of validation, IMHO you should do it explicitly

**Comment by tglman** [comment]
hi @vantonov1,

I've done a final fix to avoid to serialize the data during the query for record in tx, this should solve the problem completely in a clean way.

Regards
