### ISSUE TITLE
missing OSGi dependency in orientdb-tools package

### ISSUE THREAD

**Issue by grexe** [orientechnologies/orientdb#6406]
When trying to compile an OSGi application with the latest OrientDB 2.2.4 version, I get this error from the bnd tool:
```
Bundle : com.orientechnologies:orientdb-graphdb:jar:2.2.4 has unresolved package dependencies:
[WARNING]     com.orientechnologies.orient.stresstest
[WARNING]     com.orientechnologies.orient.stresstest.workload
```
Startup of the application fails with the same error.

The two classes are part of the `orientdb-tools` package and seem to be only needed for testing, but the `orientdb-graphdb` POM includes a dependency to `orientdb-tools` that is not in testing scope, so it ends up being referenced by the bundle, but the `orientdb-tools` module does not export those classes:
```
<osgi.export>
            com.orientechnologies.orient.console.*,
            com.orientechnologies.orient.server.config.*
</osgi.export>
```
So the bundle definition of `orientdb-tools` misses the package `com.orientechnologies.orient.stresstest` which also breaks `orientdb-graphdb` because it (incorrectly?) includes a dependency to it in default scope.

**Comment by grexe** [comment]
thanks for accepting the merge request @laa - should I close this issue or is it awaiting testing?

**Comment by laa** [comment]
No please do not, I will move changes to develop branch too. Thank you for patch.
