### ISSUE TITLE
In OrientDB 2.2 "ALTER PROPERTY" doesnt accept multiple attributes

### ISSUE THREAD

**Issue by karel-un** [orientechnologies/orientdb#6411]
## Expected behavior and actual behavior

In OrientDB 2.1 this was possible:

```
ALTER PROPERTY someclass.name MANDATORY TRUE NOTNULL TRUE
```

But in OrientDB 2.2 same command ends with error message:

```
Encountered " <IDENTIFIER> "NOTNULL "" at line 1, column 46.
Was expecting one of:
    <EOF> 
    ";" ...

        DB name="somedb"
        DB name="somedb"
```
## Steps to reproduce the problem

See behaviour.
### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 3
### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by mmacfadden** [comment]
I will let the Orient Team speak up here, but I suspect this is the new parser.  There is some related infromation buried in here #6292

**Comment by luigidellaquila** [comment]
Hi @karel-un 

As @mmacfadden pointed out, the syntax is changed a bit in 2.2.x (because of language consistency).
Could you please check the docs here https://github.com/orientechnologies/orientdb-docs/blob/2.2.x/SQL-Create-Property.md just merged with master branch, it was out of date...) and try with following syntax?

```
ALTER PROPERTY someclass.name (MANDATORY , NOTNULL TRUE)
```

**Comment by karel-un** [comment]
Parenthesis dont work either (updated to OrientDB 2.2.4):
```
 ALTER PROPERTY someclass.name (MANDATORY, NOTNULL TRUE);               

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
alter PROPERTY someclass.name (MANDATORY, NOTNULL TRUE)
    ^
Encountered " <ALTER> "alter "" at line 1, column 1.
Was expecting one of:
```
Same result with added "TRUE" after "MANDATORY".

BTW parser shows wrong place of error and gives wrong error message (points to "ALTER", which is obviously ok).

... spent about hour last evening splitting "ALTER PROPERTY" commands ;)

**Comment by luigidellaquila** [comment]
Ah, sorry @karel-un 

Sorry, my bad, the link I shared was about CREATE PROPERTY, not ALTER PROPERTY.

That syntax is not supported in the new parser yet, if you really need it you can disable it (http://orientdb.com/docs/2.1/Release-2.1.0.html#strict-sql-parser) to fall back to the old behavior, but I suggest you to stay with the new one, that in general is more stable.

Anyway, I'll see if that syntax can be implemented

Thanks

Luigi

**Comment by karel-un** [comment]
Ok, "CREATE PROPERTY" works with multiple attributes. I guess it will take not much effort to reimplement it in "ALTER PROPERTY" too.

Should I leave issue open until feature implemented ?

**Comment by luigidellaquila** [comment]
Hi @karel-un 

Yes please, leave it open, I'll try to fix it asap

Thanks

Luigi

**Comment by mmacfadden** [comment]
I had this on my list of things todo.  I know @smolinari was interested in this as well.

**Comment by smolinari** [comment]
I was only concerned for consistency's sake. :smile: Thanks for thinking about me though. I appreciate it.

Scott

**Comment by mmacfadden** [comment]
As soon as we get #6316 taken care of, I can perhaps take a look at this.

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

sorry, I completely missed it... I'm checking it now

Thanks

Luigi

**Comment by mmacfadden** [comment]
@luigidellaquila, No worries, I just didn't want to tackle this until that was merged since they would likely collide!  I'll take a look at this one, next.

**Comment by zipang** [comment]
So, i've installed OrientDB v2.2.13 and i'm following the course on Udemy 'Getting started with OrientDB'
And this example doesn't work : 

```
orientdb {db=test}> ALTER PROPERTY Person.gender REGEXP [M|F]

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
alter PROPERTY Person.gender REGEXP [M|F]
    ^
Encountered " <ALTER> "alter "" at line 1, column 1.
Was expecting one of:
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    <RETURN> ...
    <PROFILE> ...
    <FIND> ...
    <REBUILD> ...
    <OPTIMIZE> ...
    <GRANT> ...
    <REVOKE> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ...
    <IF> ...
    <SLEEP> ...
    <CONSOLE> ...
```

It is in the documentation of the 2.2.x : http://orientdb.com/docs/2.2.x/SQL-Alter-Property.html

And it doesn't work either with parenthesis.

**Comment by zipang** [comment]
Ok.
So in fact the error message is very _very_ misleading because it worked with the following syntax : 

```
ALTER PROPERTY Person.gender REGEXP "[M|F]"
```

**Comment by karolmie1** [comment]
Following query does not work: 
`CREATE PROPERTY Account.Gender STRING (MANDATORY TRUE, MAX 20, REGEXP "[M|F]")`

This is part of this issue, right?
