### ISSUE TITLE
Using the uuid() function returns a Base64 encoding of the values

### ISSUE THREAD

**Issue by SDIPro** [orientechnologies/orientdb#6413]
Try "select from uuid()" or "insert into MyClass set id = uuid()".

Example output:
rO0ABXNyAA5qYXZhLnV0aWwuVVVJRLyZA/eYbYUvAgACSgAMbGVhc3RTaWdCaXRzSgALbW9zdFNpZ0JpdHN4cJpm1EvTXgNZ0mPyN9jlR8c=

Tested on 2.2.4.

**Comment by maggiolo00** [comment]
hi @SDIPro 
this is the explanation of this issue.

https://github.com/orientechnologies/orientdb/issues/6079

Possible Workaround

```SQL
insert into MyClass set uuid = format("%s",uuid())
```
