### ISSUE TITLE
Create Index on a field that has unique values.

### ISSUE THREAD

**Issue by dhirender-tyagi** [orientechnologies/orientdb#6415]
I am using orientdb v2.2.3 and java version "1.8.0_91"

I am new to orientdb

I import data from mysql using ETL. And successfully imported that. But when i create index on a field of a class that unique values of each vertex it show m error like 

"com.orientechnologies.orient.core.index.OIndexException: Index with name 'xxx' cannot be created on class 'xxx1' because the field 'xy' is absent in class definition DB name="cc"" 

But it the field/property is already present in the class.

So can anyone let me know how can i create the same index?

**Comment by luigidellaquila** [comment]
HI @dhirender-tyagi 

are you sure the field is present in the schema (not only on the records)?

Could you please try to do the following:
```
create property xxx1.xxx STRING // or whatever type the property is...
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Another important thing: how are you creating the index? From Studio or from SQL? In case could you please post the SQL statements you are using?

Thanks

Luigi

**Comment by dhirender-tyagi** [comment]
yes i can see the records as company_id exist in attached file "property_exist"
But when i create index it gives error as in attached file "error_index"


![property_exist](https://cloud.githubusercontent.com/assets/9677491/16906492/7749981e-4cd6-11e6-9599-519304349011.png)
![error_index](https://cloud.githubusercontent.com/assets/9677491/16906493/7e5f0a30-4cd6-11e6-9e72-d725efe9491d.png)


create property xxx1.xxx STRING // or whatever type the property is...

**Comment by luigidellaquila** [comment]
Hi @dhirender-tyagi 

These screenshots show that the property exists in data, but it may be schemaless. To create an index you also need the property to exist in the schema.
Could you please execute the following query and post the result?

```
SELECT FROM (SELECT expand(classes) FROM metadata:schema) WHERE name = 'Company_details'
```

Thanks

Luigi

**Comment by smolinari** [comment]
Is there a plan to be able to add schemaless data to an index in the future? This cripples ODB in terms of being true NoSQL. Or can we get an index going on schemaless data with Lucene? Although, that would be sort of a workaround, if you ask me. 

Scott

**Comment by dhirender-tyagi** [comment]
Hi @luigidellaquila ,

query : 
SELECT FROM (SELECT expand(classes) FROM metadata:schema) WHERE name = 'Company_details'

respose :
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "name": "Company_details",
            "shortName": null,
            "description": null,
            "defaultClusterId": 37,
            "clusterIds": [
                37,
                38,
                39,
                40
            ],
            "clusterSelection": "round-robin",
            "overSize": 0,
            "strictMode": false,
            "abstract": false,
            "properties": [
                
            ],
            "superClass": "V",
            "superClasses": [
                "V"
            ],
            "customFields": null,
            "@fieldTypes": "overSize=f,properties=e"
        }
    ],
    "notification": "Query executed in 0.453 sec. Returned 1 record(s)"
}

**Comment by dhirender-tyagi** [comment]
And as I said I imported from my-sql using ETL. I don't know how to create schema if i import data from my-sql using ETL

**Comment by luigidellaquila** [comment]
Ok, so you have "schemaless" property in the dataset, but you do not have a property in the schema.

Try the following:

```
CREATE PROPERTY Company_details.company_id INTEGER

CREATE INDEX Company_details.company_id  on  Company_details (company_id) UNIQUE 
```

In case the property is not an integer, just replace the `INTEGER` with the right type

Thanks

Luigi

**Comment by luigidellaquila** [comment]
@smolinari actually with low level APIs you can already do that, but higher level layers do a check and do not allow you to go deeper if you don't have a property, so technically speaking it's quite easy to implement

Thanks

Luigi

**Comment by dhirender-tyagi** [comment]
Hello @luigidellaquila

I run this:
CREATE PROPERTY Company_details.company_id INTEGER

it creates a property

then 

CREATE INDEX Company_details.company_id  on  Company_details (company_id) UNIQUE 

And it show the error:

com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #44:1: found duplicated key '1' in index 'Company_details.ccompany_id' previously assigned to the record #44:0 DB name="sampleCRM"INDEX=Ccompany_details.company_id RID=#44:0

**Comment by maggiolo00** [comment]
@dhirender-tyagi 

that is normal. You didn't have the index while populating the data. Now the index unique cannot be created because the key '1' is duplicated

**Comment by dhirender-tyagi** [comment]
hi @lucfranken ,

Thanks It works for me.

**Comment by smolinari** [comment]
@luigidellaquila - easy to implement for us users? Or for ODB? :smile: 

Scott

**Comment by luigidellaquila** [comment]
Hi Scott,

Easy for us as an enhancement of course ;-)

Thanks

Luigi
