### ISSUE TITLE
Enhancement - UUID/GUID Data Type

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/orientdb#6416]
## Expected behavior and actual behavior

Expected:  During Class property creation, able to select UUID/GUID option
Actual:  UUID/GUID is not an available option
## Steps to reproduce the problem

Attempt to create a new property on a class
## Important Questions

A trend in database software is to natively support UUID/GUID properties such as SQL Server and Oracle.  Though it is possible to store a UUID as a string, it would be better as a supported type.  This would improve readability and also operation.  For example, 32 char vs. 36 char UUID should perform correct equals comparison.  String comparison will not work.  A new supported data type should be able to handle either case.
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [X] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 4
### Operating System
- [ ] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by jcwright77** [comment]
I'd like this too, but it is possible to create a uuid class with constraints and specify that as the type I believe.

**Comment by cwaldron** [comment]
Is this enhancement on any milestone roadmap?  If so, which one.  Thanks.
