### ISSUE TITLE
Cannot run commands on console 

### ISSUE THREAD

**Issue by magician27** [orientechnologies/orientdb#6424]
## Expected behavior and actual behavior

cant run any commands on console , getting error below

## Steps to reproduce the problem
orientdb> connect remote:172.25.1.1/database/mydb root admin

Disconnecting from the database [null]...OK
Connecting to database [remote:172.25.1.1/database/mydb ] with user 'root'...OK

CONFIGURED SERVERS
+----+-----+------+-----------+-------------------+-----------------+-----------------+---------------+---------------+---------+
|#   |Name |Status|Connections|StartedOn          |Binary           |HTTP             |UsedMemory     |FreeMemory     |MaxMemory|
+----+-----+------+-----------+-------------------+-----------------+-----------------+---------------+---------------+---------+
|0   |NODE1|ONLINE|10         |2016-07-15 01:35:15|172.25.1.12424|172.25.1.1:2480|1.61GB (27.34%)|4.29GB (72.66%)|5.90GB   |
+----+-----+------+-----------+-------------------+-----------------+-----------------+---------------+---------------+---------+
orientdb {db=mydb}> list databases

Not connected to the Server instance. You've to connect to the Server using server's credentials (look at orientdb-*server-config.xml file)

orientdb {db=mydb}>

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ X] Remote

### Misc
- [ 6] I have a distributed setup with multiple servers. How many? 
- [X ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [4 ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [X ] Other, name?  CENTOS

### Java Version
- [ ] 6
- [ ] 7
- [X ] 8

**Comment by luigidellaquila** [comment]
Hi @magician27 

you are using the wrong URL, please omit "database":

```
connect remote:172.25.1.1/mydb root admin
```

Thanks

Luigi
