### ISSUE TITLE
Delete edge error: Cannot update record  the resource has restricted access

### ISSUE THREAD

**Issue by vipuusepp** [orientechnologies/orientdb#6425]
When deleting edge before creating  got error 
DELETE EDGE EdgeName FROM #8:1 to #9:1
CREATE EDGE EdgeName FROM #8:1 to #9:1 SET _allow =#4:1
"code": 500,
            "reason": 500,
            "content": "com.orientechnologies.orient.core.exception.OSecurityException: Cannot update record #10:1: the resource has restricted access

Error appeared after migrate from 2.1.0 to 2.2.4 
Workaround:
No error when I get the Edge rid, and delete it after the new edge is created
var g = orient.getGraph();
 var q = 'select FROM edgeName  WHERE in = #9:1 AND out =  #8:1'
 var cDel = g.command("sql", q, []);
 if (cDel.length) {
       existingEdgeRid = cDel[0].getRecord().field("@rid").toString();
 }
CREATE EDGE EdgeName FROM #8:1 to #9:1 SET _allow =#4:1
DELETE EDGE existingEdgeRid 

and some case no error when  javascript 
var q = 'DELETE EDGE EdgeName FROM #8:1 to #9:1'
var cDelrid = g.command("sql", q);
g.commit();
var q = 'CREATE EDGE EdgeName FROM #8:1 to #9:1 SET _allow =#4:1'
var createdrid = g.command("sql", q);
g.commit();

Error appears also when trying delete all edges with sql  
DELETE EDGE EdgeName 
the error appears but eventually the edge is been deleted anyway, but the process has been broken.
No errors with root user
### OrientDB Version
- [x] v2.2.4 
### Java Version
- [x] 8

**Comment by luigidellaquila** [comment]
Hi @vipuusepp 

which user are you using to do these operations? Did you change the user/role permissions on your DB?

Any chance to have a working DB where to reproduce the error? Probably it depends on your schema and user/role configuration

Thanks

Luigi

**Comment by lvca** [comment]
Could you please provide more information about the way you delete the record and the security settings?

**Comment by vipuusepp** [comment]
Hi

**Comment by G4br13l3** [comment]
Hi @vipuusepp,

could you provide us more info in order to reproduce the bug?

Thanks.

**Comment by vipuusepp** [comment]
Hi

**Comment by SDIPro** [comment]
No response from customer.  Closing.
