### ISSUE TITLE
Cannot create edge when _allow is subquery

### ISSUE THREAD

**Issue by vipuusepp** [orientechnologies/orientdb#6431]
## Expected behavior and actual behavior

adding new edge with current user plus testuser
CREATE EDGE edgename FROM #61:1 to #21:1 SET _allow = (select from orole where name = "testuser")

but got error
java.lang.ClassCastException: com.orientechnologies.orient.core.sql.OCommandSQL cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable
## Steps to reproduce the problem

user have orole
{"database.cluster.internal":15,"database.cluster.orole":15,"database":2,"database.function":15,"database.schema":15,"database.cluster.ouser":15,"database.systemclusters":15,"database.command":15,"database.cluster":15,"database.class":15,"database.hook.record":15,"database.query":15}
V and E is oRestricted 
This error appeared after migration from 2.1 to 2.2.4
No errors on older version and no errors with root user.

when I try 
CREATE VERTEX Vertexname SET someproperty = "x",  _allow = (select from orole where name = "testuser")
there is no problem current user and extra testuser is been added into vertex _allow property

when I try 
CREATE EDGE edgename FROM #61:1 to #21:1 SET _allow = [#4:3]
then only testuser #4:3 been added to edge, but not current user who should added always.

Probably its related with issue #6425
### OrientDB Version
- [x] v2.2.4:

**Comment by luigidellaquila** [comment]
Hi @vipuusepp 

Thank you for reporting, this seems to be a regression, I'll try to take a look at it asap

Thanks

Luigi
