### ISSUE TITLE
Cannot save configuration on UI of related Nodes

### ISSUE THREAD

**Issue by sagarmaniar** [orientechnologies/orientdb#6436]
## Expected behavior and actual behavior
The property should be displayed on all the nodes when the configurations are saved.
The current behavior is even after saving configuration the UI still displays rid's for other related nodes for the same type.

## Steps to reproduce the problem

Input 2 different class contact and firm that extend V
Create a class account that extends E
Create relationship between such that  contact -- [account] --> firm

Then write a select query
select * from contact

Double click on any contact node to see the related firms.

select the property of firm and save configuration.

### Runninng Mode
 Embedded, using PLOCAL access mode

### OrientDB Version

- [x] v2.2.x - Please specify last number: 4

### Operating System
- [x] Windows

### Java Version
- [x] 8

**Comment by maggiolo00** [comment]
Are you logged with root user?

**Comment by sagarmaniar** [comment]
yes i am logged in by username:admin and pass: admin

**Comment by sagarmaniar** [comment]
@maggiolo00 could you suggest a temporary work around for this feature?

**Comment by maggiolo00** [comment]
Do you have a screenshot?

**Comment by sagarmaniar** [comment]
![image](https://cloud.githubusercontent.com/assets/15523754/16960657/7620c9c0-4db8-11e6-9932-e505c419a7e6.png)

**Comment by sagarmaniar** [comment]
@maggiolo00 the above is the screen shot. Check the surrounding nodes. You could see the rids, on the bubble and only one has changed as the name (shown in settings on left pane).

**Comment by maggiolo00** [comment]
@sagarmaniar 

the dashed circle means that the node data is not loaded yet. Studio cannot display the property name because it does not have the data yet. If you click over the node it is lazy loaded and the property should be populated. This will change in the next version 2.2.6 with a major improvement of the graph rendering

**Comment by sagarmaniar** [comment]
@maggiolo00 What is the expected release date for 2.2.6 version?

**Comment by sagarmaniar** [comment]
@maggiolo00 Thanks! Just the last question.. So in the next release the properties will be populated without having to click on individual nodes. Am I right?

**Comment by maggiolo00** [comment]
Yes

**Comment by sagarmaniar** [comment]
@maggiolo00 2.2.6 version which is released today also has the same problem mentioned above in terms of graph rendering. Could you please help me out with it. Thanks!

**Comment by maggiolo00** [comment]
@sagarmaniar 
this feature has been delayed to 2.2.7

**Comment by lvca** [comment]
Is this already fixed? Can we close it?

**Comment by sagarmaniar** [comment]
@lvca yes please close this

**Comment by lvca** [comment]
Cool, thanks.
