### ISSUE TITLE
Not able to create  SPATIAL ENGINE LUCENE Index

### ISSUE THREAD

**Issue by dhirender-tyagi** [orientechnologies/orientdb#6440]
I am using orientdb v2.2.3 and java version "1.8.0_91"

I want to create index on longitude and latitude to get nearest locations. So I use this query to create index.

CREATE INDEX Lead_address.l_lon ON Lead_address(latitude,longitude) SPATIAL ENGINE LUCENE

But I got the error:

'com.orientechnologies.orient.core.index.OIndexException: Index with type SPATIAL and algorithm LUCENE does not exist. DB name="XXX"'

**Comment by maggiolo00** [comment]
hi @dhirender-tyagi 

From OrientDB 2.2.0 the spatial module has been moved here. It is not bundle with the Community Edition.

http://orientdb.com/docs/2.2/Spatial-Index.html

**Comment by dhirender-tyagi** [comment]
Below link is given on the link page.

http://central.maven.org/maven2/com/orientechnologies/orientdb-spatial/2.2.3/orientdb-spatial-VERSION-dist.jar

or 

wget  http://central.maven.org/maven2/com/orientechnologies/orientdb-spatial/v2.2.3/orientdb-spatial-VERSION-dist.jar


But it gives 404 not found

**Comment by dhirender-tyagi** [comment]
hi @maggiolo00 ,

Now I am using enterprise version 2.2.4.

I am still facing the same error.

**Comment by maggiolo00** [comment]
hi @dhirender-tyagi 

try 

```SQL
CREATE INDEX Lead_address.l_lon ON Lead_address(latitude,longitude) SPATIAL ENGINE LUCENE METADATA {ignoreNullValues: true}
```

**Comment by dhirender-tyagi** [comment]
com.orientechnologies.orient.core.index.OIndexException: Cannot create the index 'Lead_address.l_lon' DB name="sample_crm" --> com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index DB name="sample_crm" --> java.lang.NullPointerException

**Comment by maggiolo00** [comment]
is the same? 
Can you send me a simple dataset that repruduce this?

**Comment by dhirender-tyagi** [comment]
{
    "result": [
        {
            "@type": "d",
            "@rid": "#65:471",
            "@version": 1,
            "@class": "Lead_address",
            "lead_address_id": 1890,
            "street": "Building No 8, Tower-B, 4th Floor, Dlf Cyber City, Dlf Phase II, Sector 25",
            "city": "Gurgaon",
            "zip_code": "122002",
            "state": "5082",
            "country": "1101",
            "county": null,
            "longitude": "77.09141799999998",
            "latitude": "28.495498",
            "house": null,
            "@fieldTypes": "lead_address_id=l"
        }
    ],
    "notification": "Query executed in 0.166 sec. Returned 1 record(s)"
}

**Comment by maggiolo00** [comment]
hi @dhirender-tyagi 

i see that longitude and latitude are string. That should be the problem.
store them as Double. How do insert those values?

**Comment by dhirender-tyagi** [comment]
Hi @maggiolo00 

I port data from mysql using ETL. So there data in varchar format. So can you tell me that can I change varchar to Long at ETL process or have to write a script?..

**Comment by maggiolo00** [comment]
@dhirender-tyagi 

you can use this SQL to convert them

```SQL
create property Lead_address.lat double
create property Lead_address.lon double
update Lead_address set lat = latitude , lon = longitude
```
and then drop latitude and longitude properties

or if you create the schema before the ETL i think it will work

**Comment by dhirender-tyagi** [comment]
Hi @maggiolo00 

I updated the value of latitude and longitude to 0.0 where it was null or '', by

update Lead_address merge {"latitude":"0.0"} where latitude=''
update Lead_address merge {"langitude":"0.0"} where langitude=''

then :

create property Lead_address.lat double
create property Lead_address.lon double

then:

update Lead_address set lat = latitude , lon = longitude

but it gives me error : 

java.lang.NumberFormatException: For input string: "http://www.cogebi.com"
