### ISSUE TITLE
How should I do can reduced hard disk spaces, I don’t want to delete all the records .

### ISSUE THREAD

**Issue by EdgarSunJinTao** [orientechnologies/orientdb#6441]
Hi~
Here I have a questions about the orientdb. My hard disk is full, When I delete a lot of records from databases, I lose very small amount of disk space. 
Examples:
Delete from MacBook where time<’……’
As you can see ,I delete 132204577 records from Class MacBook. But the hard disk space is  not reduced.
How should I do can reduced hard disk spaces, I don’t want to delete all the records .

### Runninng Mode
- [ 1] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ 1] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [1 ] v2.1.x - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [1 ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ 1] 7
- [ ] 8

**Comment by laa** [comment]
Hi @EdgarSunJinTao 
Could you export data to json and then from json, it will compact your database

**Comment by lvca** [comment]
This is more a question than an issue. Please post it on StackOverflow http://stackoverflow.com/questions/tagged/orientdb
