### ISSUE TITLE
Test case failures/errors on Ubuntu-ppc64le v/s Ubuntu-x86_64

### ISSUE THREAD

**Issue by ghatwala** [orientechnologies/orientdb#6442]
## Expected behavior and actual behavior
This is related to #6210 , however this issue ticket is raised as i have more debug information which may help in resolving the test case failure issues.

I have cross-verified the test cases on Ubuntu  ( ppc64le and x86_64 ) , with below environments
On X86_64
```
root@hj-ibmibm1492:~/amit/debug_orientdb# mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 9-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-9-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-22-generic", arch: "amd64", family: "unix"
```
And ibm java version as below
```
root@hj-ibmibm1492:/opt/ibm/java-x86_64-80# java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr3-20160428_01(SR3))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20160427_301573 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR3_20160427_1620_B301573
JIT  - tr.r14.java.green_20160329_114288
GC   - R28_Java8_SR3_20160427_1620_B301573_CMPRSS
J9CL - 20160427_301573)
JCL - 20160421_01 based on Oracle jdk8u91-b14

```
and on ppc64le
```
root@pts00449-vm1:~/amit/orientdb# mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0, vendor: IBM Corporation
Java home: /opt/ibm/java-ppc64le-80/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-22-generic", arch: "ppc64le", family: "unix"

```
and java version as below

```
root@pts00449-vm1:~/amit/orientdb# java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxl6480sr3-20160428_01(SR3))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux ppc64le-64 Compressed References 20160427_301573 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR3_20160427_1620_B301573
JIT  - tr.r14.java.green_20160329_114288
GC   - R28_Java8_SR3_20160427_1620_B301573_CMPRSS
J9CL - 20160427_301573)
JCL - 20160421_01 based on Oracle jdk8u91-b14

```

## Steps to reproduce the problem
Steps used are as below on ppc64le 
```
git clone https://github.com/orientechnologies/orientdb.git
cd orientdb/
git checkout 2.2.4
 mvn -e -X clean install > debug_ppc64le.txt 2>&1
```
with last line difference on x86_64
```
mvn -e -X clean install > debug_x86_64.txt 2>&1

```
## Important Questions
I am attaching both the above debug logs captured on x86 and ppc64le
My observation of the failed test cases are as below
1. The jenkins CI engine run by orientDB  ( http://helios.orientdb.com/view/develop/job/orientdb-develop-ibm-jdk8/ ) run on x86_64 with ibm - jdk installed on it strangely passes all the test cases , however the same doesn't happen on our local x86 vm .Let me know if possible the configure/builds steps for these x86 jenkins jobs so that i can cross-verify the same steps on our local x86 vm

2. The test cases failing as as below
Results :

Failed tests: 
  TestBatchRemoteResultSet.runBatchQuery:59
Tests in error: 
  OCommandExecutorSQLDeleteVertexTest.testDeleteVertexBatch:87 » ODatabase Datab...
  OCommandExecutorSQLDeleteVertexTest.testDeleteVertexFromSubquery:114 » ODatabase
  OCommandExecutorSQLDeleteVertexTest.testDeleteVertexFromSubquery2:127 » ODatabase
  OCommandExecutorSQLDeleteVertexTest.testDeleteVertexLimit:72 » ODatabase Datab...
  SimplePropertyLinkTest.testSimplePropertyLink:36 ClassCast java.lang.String in...

In above , the ones having errors in test case : " OCommandExecutorSQLDeleteVertexTest " , here the tests are in errors due to database closed  , which occurs primarily due to "GraphShutdown" test case executed before this
Running com.orientechnologies.orient.graph.GraphShutdownTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.107 sec - in com.orientechnologies.orient.graph.GraphShutdownTest

This "GraphShutdown" test case is performed at the end , when i looked up the jenkins url : http://helios.orientdb.com/view/develop/job/orientdb-develop-ibm-jdk8/

Also individually the test case  run using below is passing
```
 mvn test -Dtest=OCommandExecutorSQLDeleteVertexTest
Results :

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.312 s
[INFO] Finished at: 2016-07-20T14:52:13+05:30
[INFO] Final Memory: 16M/32M
[INFO] ------------------------------------------------------------------------

```
Which proves that during the integrated test case execution , we have test case errors.
Also similarly , other test case error - "SimplePropertyLinkTest " is passing individually.
```
Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.122 s
[INFO] Finished at: 2016-07-20T14:54:54+05:30
[INFO] Final Memory: 16M/31M
[INFO] ------------------------------------------------------------------------

```

Also for this : "TestBatchRemoteResultSet"

```
root@pts00449-vm1:~/amit/orientdb/graphdb# mvn test -Dtest=TestBatchRemoteResultSet
Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.070 s
[INFO] Finished at: 2016-07-20T14:57:53+05:30
[INFO] Final Memory: 17M/33M
[INFO] ------------------------------------------------------------------------

```

So integrated test cases suite is failing when run using 
```
mvn clean install
```

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 2.2.4

### Operating System
- [ ] Linux ( Selected - Ubuntu ) 
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ ] 8 ( Selected ) 

Attached the debug logs for both x86 and ppc64le
[debug_ppc64le.txt](https://github.com/orientechnologies/orientdb/files/373269/debug_ppc64le.txt)
[debug_x86.txt](https://github.com/orientechnologies/orientdb/files/373268/debug_x86.txt)

Hope this will be helpful in pointing to the root cause of test suites failures. I feel integration of test cases is the culprit as individual test cases executed successfully.

Regards,
Amit

**Comment by tglman** [comment]
Hi,

We have been able to fix the build on PPC a while ago, going to close this.

Bye

**Comment by ghatwala** [comment]
hi @tglman : all good so far .
