### ISSUE TITLE
Not able to get teleporter

### ISSUE THREAD

**Issue by dhirender-tyagi** [orientechnologies/orientdb#6443]
Hi,

I have download the Enterprise version of Orientdb for development. I want to use teleporter but I am not able get teleporter from anywhere can you suggest m from where i can get teleporter and how can i synch my my-sqldb with orientdb.

**Comment by G4br13l3** [comment]
Hi dhirender-tyagi,

which version of orientdb Enterprise did you install?

**Comment by dhirender-tyagi** [comment]
orientdb-enterprise-2.1.16

**Comment by G4br13l3** [comment]
Teleporter is directly integrated in orientdb EE since 2.2.x, so you have to download a more recent version.
Let me know if you have any issue doing that.

Thanks

**Comment by G4br13l3** [comment]
I'm closing this issue, please reopen it if you need additional info.
