### ISSUE TITLE
ETL: IllegalArgumentException: Property value can not be null

### ISSUE THREAD

**Issue by ritesh0919** [orientechnologies/orientdb#6444]
Hi,

I am facing the below error:
Error in Pipeline execution: java.lang.IllegalArgumentException: Property value can not be null

I am using orientdb ETL tool migrate a mapping table from a RDBMS to edge. This edge has got some properties and whenever there is a null as property value (of this edge), I see the above error.

I even altered the database to set standardElementConstraints as false. But looks like it is of no affect. I am on orientdb community 2.2.0.

Any help will be appreciated.

Regards,
Ritesh

**Comment by robfrank** [comment]
If you are using the CSV extractor, you can configure the nullValue:

http://orientdb.com/docs/master/Extractor.html#csv-extractor

If this didn't solve your problem, please add more details: configuration, sample data.
Thanks in advance.

**Comment by robfrank** [comment]
no response for long time. Feel free to reopen the issue

**Comment by ritesh0919** [comment]
Sorry for the delay. This problem was solved setting

```
ALTER DATABASE custom standardElementConstraints=false'
```

Hope this is the right way to solve this issue. Got the reference from:
http://stackoverflow.com/questions/33695643/what-does-set-standardelementconstraints-false-do
