### ISSUE TITLE
Incorrect behaviour during incremental restore in distributed environment

### ISSUE THREAD

**Issue by G4br13l3** [orientechnologies/orientdb#6446]
In a distributed scenario the incremental backup works fine, but incremental restore, performed through the 'create database remote:localhost/dbname root root plocal graph -restore=backup-path' command, affects only the local node where the restore command is executed.

Let's suppose we have 3 nodes and we execute an incremental restore on node1. If we execute an incremental restore on node1 a new fresh database is created on all the 3 nodes, but only on node1 the binary changes are applied to the new database just built.
This implies an inconsistent behaviour because we obtain the database correctly restored on node1 but an empty database on node2 and node 3. At this moment you can overcome this inconsistency by executing a shutdown on all the nodes of the cluster not involved in the restore procedure (node2 and node3 in our example), so once restarted they will get the full database from node1.

**Comment by lvca** [comment]
The right solution would be deleting the database automatically from other nodes before the restore and after the restore, the database would be synchronized to other nodes anyway.
