### ISSUE TITLE
[ Question / Bug ] Type identifier for Lucene Geometry objects conflicts with the OrientDB Classes name.

### ISSUE THREAD

**Issue by Ostico** [orientechnologies/orientdb#6448]
Please refer to that issue opened in the PyOrient repository:

https://github.com/mogui/pyorient/issues/203

Ambiguity on the @ class sign leads to a bad decoded output. 

Is this a desired behaviour or a bug? I need to know this to be sure before to patch and upgrade the drivers to handle these new Data Types.

Anyway the Class name is not returned in the output and i suppose this is a bug that should be fixed.

**Comment by maggiolo00** [comment]
Hi @Ostico 

The new Spatial Plugin does not use new data types. It stores data in embedded document where the class represent the geometry type `OPoint`.

**Comment by Ostico** [comment]
Hi @maggiolo00 ,
anyway i think that there is a bug in the raw output for the CSVSerialization. Please check this issue on the [pyorient](mogui/pyorient#203) driver.

**Comment by maggiolo00** [comment]
@Ostico are you able to dump the raw output of the CSVSerialization from ODB?

**Comment by Ostico** [comment]
Yes @maggiolo00 , i already dumped the output, please read my response to the issue in the link i posted above

**Comment by Ostico** [comment]
Any update? This is needed to support spatials coordinates.

**Comment by maggiolo00** [comment]
@Ostico i've made this test

https://gist.github.com/maggiolo00/2fd8429cee0723f4113abd772049ae10

The record with 'Foo' name dumped in csv is

```
entity@name:"Foo",location:(OPoint@coordinates:[12.4684635d,41.8914114d]),out_:%AQAAAAEADQAAAAAAAAAAAAAAAAAAAAAAAA==;
```
which seems fine.

But the print(res5[0].location) of 

```
select from Entity
``
is
```
{'o_class': 'OPoint', 'coordinates': '[12.4684635d,41.8914114d]),out_', '%AQAAAAEADQAAAAAAAAAAAAAAAAAAAAAAAA==;': None}
```
that seems that the embedded object (location) field, that has class 'OPoint' contains the field `out` which is wrong.

**Comment by maggiolo00** [comment]
The strange thing is that if i use this query

```
select location,in() as in,out() as out from Entity
```
i get in print

```
{{'location': {'[],out': [<pyorient.otypes.OrientRecordLink object at 0x10f034690>], 'o_class': 'OPoint', 'coordinates': '[12.4684635d,41.8914114d]),in'}},'version':0,'rid':'#-2:0'}
```

with

```
select in() as in,out() as out ,location from Entity
```

seems fine

```
{{'out': [<pyorient.otypes.OrientRecordLink object at 0x110c65690>], 'location': {'o_class': 'OPoint', 'coordinates': '[12.4684635d,41.8914114d])'}, 'in': []},'version':0,'rid':'#-2:0'}
```

**Comment by maggiolo00** [comment]
@Ostico 
any updates. Do you still need help on this?
