### ISSUE TITLE
Feature Suggestion: Reusing old RIDs

### ISSUE THREAD

**Issue by Dacnomanie** [orientechnologies/orientdb#6450]
RIDs are never recycled and this leads to lots of disk space usage.

Perhaps there could be a system index for each cluster with all orphaned RIDs (so OrientDB doesn't have to loop through all records to find if a previous one is empty) and new records would use any available spots, if none are available, create record as per normal.

**Comment by laa** [comment]
Hi. I think that your problem is not reused RIDs, but " lots of disk space usage". Is it correct. If you wish this problem to be fixed please vote on https://github.com/orientechnologies/orientdb-labs/issues/7 . One of its  goals "Reuse space which is used to store rid of delete record" .

**Comment by Dacnomanie** [comment]
Wouldn't it be more efficient to reuse the RIDs? Especially with pagination?

**Comment by laa** [comment]
It leads to the case when you fetch records which are already removed. I sent stale link or have such one in application and all the sudden it appears again , we have received a lot of complaints from users when once made rids reusable.

**Comment by Dacnomanie** [comment]
Alrighty, I'll go vote on the other thread you linked.
