### ISSUE TITLE
Bug in file CronExpression.java

### ISSUE THREAD

**Issue by AppChecker** [orientechnologies/orientdb#6451]
Hello!

Function findNextWhiteSpace always returns the last position of given string.

File [server/src/main/java/com/orientechnologies/orient/server/schedule/CronExpression.java, line 949](https://github.com/orientechnologies/orientdb/blob/8d729f377c97c1a0ee4addf0a7046d855ec6b519/server/src/main/java/com/orientechnologies/orient/server/schedule/CronExpression.java#L949)

Expression (s.charAt(i) != ' ' || s.charAt(i) != '\t') is always true.

- if s.charAt(i) is space -> expression s.charAt(i) != '\t' is true -> (s.charAt(i) != ' ' || s.charAt(i) != '\t') is true
- if s.charAt(i) is tabulation -> expression s.charAt(i) != ' ' is true -> (s.charAt(i) != ' ' || s.charAt(i) != '\t') is true
- if s.charAt(i) is other symbol -> expression s.charAt(i) != ' ' is true -> (s.charAt(i) != ' ' || s.charAt(i) != '\t') is true

Example - https://ideone.com/wol0jb

This possible defect found by [AppChecker](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by lvca** [comment]
That class is old and not present after v2.0
