### ISSUE TITLE
Bad link on releases page

### ISSUE THREAD

**Issue by justinkillen** [orientechnologies/orientdb#6454]
On the releases page https://github.com/orientechnologies/orientdb/releases, the link for release 2.2.3 is wrong - https://github.com/orientechnologies/orientdb/issues?q=milestone%3A%222.2.2.3%22+is%3Aclosed  it refers to version 2.2.2.3 (non-existant).  It should be https://github.com/orientechnologies/orientdb/issues?q=milestone%3A%222.2.3%22+is%3Aclosed

**Comment by luigidellaquila** [comment]
Fixed, thanks!

Luigi
