### ISSUE TITLE
getVertices(String label, String[] iKey, Object[] iValue) returns empty iterator if null values involved

### ISSUE THREAD

**Issue by pmeisen** [orientechnologies/orientdb#6455]
## OrientDB Version, operating system, or hardware.
- v2.2.4 (using remote connection to server, utilizing:
   - orientdb-client-2.2.4.jar, 
   - orientdb-core-2.2.4.jar, 
   - orientdb-graphdb-2.2.4.jar, 
   - gremlin-java-2.6.0.jar, 
   - blueprints-core-2.6.0.jar, 
   - pipes-2.6.0.jar

## Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
getVertices(String label, String[] iKey, Object[] iValue) does not return all indexed columns, expects to retrieve all the vertices fulfilling the criterion.

## Steps to reproduce the problem
1. create a vertex type having one index column
2. add a new vertex, having a null value for the indexed column
3. use getVertices(String label, String[] iKey, Object[] iValue) with "myType", new String[] {"myIdx"}, and new Object[null] -> no vertices are returned
4. use getVerticesOfClass(String iClassName) returns the null-index vertex, but filtering has to be done manually (not really a solution)
5. make sure there is no index used with any null values and getVertices(String label, String[] iKey, Object[] iValue) works fine. 

Nevertheless, the documentation states, that since 2.2 the database should handle null values in indexes, which does not seem to be the case. Any ideas?!

## Related Problem (?)
I also recognized that the method getVertices(String label, String[] iKey, Object[] iValue) only returns one vertex instead of all matching vertices (using a partial matching index). 

    // the following code only returns exactly one vertex, (vertices iterable)
    vertices = graph.getVertices(clazz, 
           properties.keySet().toArray(new String[properties.size()]),
           properties.values().toArray(new Object[properties.size()]));

    // the following code returns all the vertices correctly, (vertices iterable)
    final GraphQuery query = graph.query().has("@class", clazz);
    properties.forEach(query::has);
    vertices = query.vertices();

**Comment by luigidellaquila** [comment]
Hi @pmeisen 

I think this issue is related to 

https://github.com/orientechnologies/orientdb/issues/6745

that is already fixed. I'm checking it, I'll give you a feedback soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @pmeisen 

I just tried this on 2.2.11 and it seems to work fine:

```
  @Test public void testIndexWithNull() {
    OrientGraph g = new OrientGraph(URL, "admin", "admin");
    try {
      OrientVertexType clazz = g.createVertexType("testIndexWithNull");
      clazz.createProperty("name", OType.STRING);
      clazz.createIndex("testIndexWithNull.name", OClass.INDEX_TYPE.NOTUNIQUE, "name");

      OrientVertex v = g.addVertex("class:testIndexWithNull");
      v.setProperty("name", "foo");
      v.save();

      v = g.addVertex("class:testIndexWithNull");
      v.setProperty("surname", "bar");
      v.save();

      g.commit();

      Iterable<Vertex> x = g.getVertices("testIndexWithNull", new String[] { "name" }, new Object[] { null });
      Iterator<Vertex> iterator = x.iterator();
      Assert.assertTrue(iterator.hasNext());
      Vertex vertex = iterator.next();
      Assert.assertEquals("bar", vertex.getProperty("surname"));
      Assert.assertFalse(iterator.hasNext());
    } finally {
      g.shutdown();
    }
  }
```

Maybe it's already fixed or am I just missing something?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @pmeisen 

Ok I double checked, it's seems it's already fixed

Closing, thanks!

Luigi
