### ISSUE TITLE
manual index bug

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6457]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ x ] - .rc1[ ] .beta2[ ] .beta1[ ]
## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
  
  INSERT INTO INDEX:Manual (key, rid) VALUES(['Enrico', 'Rome'], #5:0)

orientdb> SELECT FROM INDEX:Manual WHERE key LUCENE "Enrico"

if want search for prop 1 and not for prop2 how to do?

 select from index:Manual34 where  [prop1, prop2] LUCENE "(prop1:foo AND prop2:bar)"          

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: 'Key' field is required for queries against indexes

it seams there is no way for finding a specific property of schema

**Comment by maggiolo00** [comment]
did you try?
select from index:Manual34 where key LUCENE "(prop1:foo AND prop2:bar)"

**Comment by maggiolo00** [comment]
@publicocean0 

sorry was't documented on multiple fields in manual index. Since it's manual and there aren't properties the engine generates the name k1,k2,k3..kN


select from index:Manual34 where key LUCENE "(k1:foo AND k2:bar)"
See
LuceneManualIndex test

**Comment by maggiolo00** [comment]
@publicocean0  the exception that you get is at parsing time because the key is mandatory in index: syntax

**Comment by publicocean0** [comment]
CREATE INDEX Manual11 FULLTEXT ENGINE LUCENE long , long ,long ,long
insert into index:Manual11 (key, rid) values([1,2,3,4],#30:3)

Inserted record '{rid:#30:3,key:[4]}' in 0,455000 sec(s).
select from index:Manual11 where key LUCENE "(k0:1)"             

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from index:Manual11 where key LUCENE "(k0:1)"


Error: java.lang.NumberFormatException: For input string: "(k0:1)"

**Comment by publicocean0** [comment]
CREATE INDEX Manual13  FULLTEXT ENGINE LUCENE string , string , string , string  


Creating index...
Created index successfully with 0 entries in 0,337000 sec(s).


Index created successfully
 insert into index:Manual13 (key, rid) values(['a','b','c','d'],#30:3)   

Inserted record '{rid:#30:3,key:[4]}' in 0,327000 sec(s).



 select from index:Manual13 where key LUCENE "k0:'a'"


0 item(s) found. Query executed in 0.227 sec(s).

**Comment by maggiolo00** [comment]
@publicocean0 

the first one is type problem With lucene we support strings or list of strings

the second one you are not taking in account the analyzer.

a is a stop word that is removed in indexing phase.

```sql
insert into index:Manual13 (key, rid) values(['Test','b','c','d'],#30:3)
```

```sql
select from index:Manual13 where key LUCENE "k0:Test"
```

**Comment by maggiolo00** [comment]
@publicocean0  
is it working ?

**Comment by publicocean0** [comment]
orientdb {db=streamer}> select from index:Manual13 where key LUCENE "k0:Test"

Error: java.lang.NoClassDefFoundError: com/orientechnologies/orient/core/serialization/OBase64Utils

Error: java.lang.ClassNotFoundException: com.orientechnologies.orient.core.serialization.OBase64Utils

**Comment by publicocean0** [comment]
reading in the  log 
Error: java.lang.NumberFormatException: For input string: "(k0:1)"

so it is trying to parsing as number  "(k0:1)"

**Comment by maggiolo00** [comment]
@publicocean0 

tested without problem in 2.2.5 plocal and remote with the index created 

in this way 

```
CREATE INDEX Manual13 FULLTEXT ENGINE LUCENE string , string , string , string
```

**Comment by publicocean0** [comment]
i have 2.2.6.

i will try to recompile....

**Comment by maggiolo00** [comment]
Btw  you get this

`Error: java.lang.NumberFormatException: For input string: "(k0:1)"```

from the query engine. This is an integration problem. 
Because the fields are long and the param is a string.

**Comment by publicocean0** [comment]
same error after recompilation boh

**Comment by publicocean0** [comment]
in log 

WARNI Token signature failure: AAAAAAhzdHJlYW1lcgAABQAAAAAAAAAAAAABVh4r5w4AACQAF09SZWNvcmRTZXJpYWxpemVyQmluYXJ5AA1PcmllbnREQiBKYXZhAA4yLjIuNi1TTkFQU0hPVJs+oZJ3Dc147tdHD4Lk0gcFSxNh1ZeQ1srMOyDPYJzd [OTokenHandlerImpl]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:174)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:290)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:227)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by publicocean0** [comment]
ah ok this is beacuase the server web is up

**Comment by publicocean0** [comment]
ok now it works in 2.6 ... a problem with console. restarting console it works. 

It remains the problems with key for number.

**Comment by maggiolo00** [comment]
@publicocean0 
that is the sql engine check with types. Let me check if can do something about it

**Comment by publicocean0** [comment]
ok it is not urgent , i passed to another task in the while, fortunately i have a pile of task to do :)

**Comment by publicocean0** [comment]
A similar problem is also in automatic lucene. I have a property long but when i make query no field is found

**Comment by maggiolo00** [comment]
hi @publicocean0 

i guess, the code is the same. 
We did integrate and test the text indexing of lucene. 
The number handling was left out. We should extend the query parser of lucene in order to support numeric ranges.

**Comment by maggiolo00** [comment]
@publicocean0 
For numbers you should use native indexing.

**Comment by publicocean0** [comment]
Impossible , my query in index needs to create a expression with indexed fields.
