### ISSUE TITLE
ddb.getRecordByUserObject(ref, false) is disappeared

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6458]
## OrientDB Version, operating system, or hardware.

- v2.2.6 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

where can i find the old subroutine?

**Comment by publicocean0** [comment]
OObjectSerializerHelper.getObjectID(db, ref) ??

**Comment by publicocean0** [comment]
sorry solved

**Comment by lvca** [comment]
@publicocean0 it's better to write to the Community Group or StackOverflow than open an issue for any question ;-)
