### ISSUE TITLE
Methods can not be used on value literals

### ISSUE THREAD

**Issue by DanielRuthardt** [orientechnologies/orientdb#6461]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[X] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[X] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Expected the following SQL query to return 1930:

SELECT '1930-1950'.LEFT(4)

The SQL query doesn't trigger an error nor does it return anything however.
It seems that all other methods are affected as well, not only string methods being called on string values. The documentation states that the methods can be called on VALUE(s), nit necessarily properties. When making the value a property, the methods work fine though:

SELECT period.LEFT(4) FROM (SELECT '1930-1950' AS period)

This workaround doesn't seem performant though.

## Steps to reproduce the problem

SELECT '1930-1950'.LEFT(4)

**Comment by DanielRuthardt** [comment]
It seems that as long as the value isn't a value literal, methods work fine as well. So the following two workarounds also do the trick, where as the second one seems to be the more performant and thus preferred one:

SELECT SET('1930-1950')[0].LEFT(4)
SELECT IFNULL('1930-1950', '').LEFT(4)
...

It seems that as long the value literal is converted to a "real" value using a function, a sub-query or anything the like, methods can be used again. I assume that this issue also exists for non-string value literals and their corresponding methods and that the same tricks can be used.

**Comment by luigidellaquila** [comment]
Hi @DanielRuthardt 

Which version are you working with?
AFAIK it works correctly on latest stable (2.2.5)

Thanks

Luigi

**Comment by DanielRuthardt** [comment]
Hi @luigidellaquila ,

I was indeed using 2.1.x.
I did upgrade to 2.2.5 and the issue is now solved.

Greets,
Daniel
