### ISSUE TITLE
server doesn't shut down on windows

### ISSUE THREAD

**Issue by seriouslyEnter** [orientechnologies/orientdb#6462]
## OrientDB Version, operating system, or hardware.
- v2.2.5,  Windows download

OrientDB Server v2.2.5 (build 2.2.x@r393af9c5a3e4a4408440a9376283a26d2d3d3c7b; 2016-07-20 06:03:46+0000)

## Operating System
- [x ] Windows 10 64x

## Steps to reproduce the problem

1. download
2. unpack
3. start: server.bat -> server starts
4. set password

expected
5. stop: shutdown.bat -> server shuts down !

actual
5. stop: shutdown.bat -> server doesn't shutdown.
`Message: SEVER Authentication error of remote client /127.0.0.1:50532: shutdown is aborted. [ONetworkProtocolBinary] `

repeated on Linux with no issues only Windows!

**Comment by seriouslyEnter** [comment]
behaviour started with version 2.2.0
and was documented!
[http://orientdb.com/docs/2.2.x/Tutorial-Run-the-server.html](http://orientdb.com/docs/2.2.x/Tutorial-Run-the-server.html)
I guess it was added as part of the new security features:
changelog: [https://github.com/orientechnologies/orientdb-docs/blob/master/Release-2.2.0.md](https://github.com/orientechnologies/orientdb-docs/blob/master/Release-2.2.0.md)

**Comment by robfrank** [comment]
As stated on documentation, you need to provide the server 's root user password to the script: http://orientdb.com/docs/2.2.x/Tutorial-Run-the-server.html#stop-the-server
