### ISSUE TITLE
Index with type SPATIAL and algorithm LUCENE does not exist

### ISSUE THREAD

**Issue by iamlogiq** [orientechnologies/orientdb#6464]
## OrientDB Version, operating system, or hardware.
V2.2.5

## Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Create a Spacial Lucene index
## Steps to reproduce the problem
Created a graph database using pLocal
Created a model named Geolocation with 2 properties named latitude and longitude of type double
entered command in orientdb studio: 

> CREATE INDEX GeoLocation.latitude_longitude ON GeoLocation(latitude,longitude) SPATIAL ENGINE LUCENE

I keep getting this error: **Index with type SPATIAL and algorithm LUCENE does not exist.**

**Comment by maggiolo00** [comment]
hi @iamlogiq 

The spatial extension is a separate module. See the install instructions here
http://orientdb.com/docs/2.2/Spatial-Index.html

Thanks

**Comment by iamlogiq** [comment]
@maggiolo00 Thank you! It used to be included in previous version be default but i guess that changed. Thanks for the link!
