### ISSUE TITLE
Links are not showing on graph user interface

### ISSUE THREAD

**Issue by dhirender-tyagi** [orientechnologies/orientdb#6466]
Hi,

I am using v2.2.3 of orientdb.

I am using ETL to port data from relational databases and I created the links using ETL I am able to see the link column and also able to query with that link. But when I see in graph UI it show 2 unrelated entities. I think I should show some relation between two linked vertex or class.

**Comment by maggiolo00** [comment]
@dhirender-tyagi 

can you post your a screenshot of your results set with the links?

**Comment by dhirender-tyagi** [comment]
Hi,

Please see the link "dir_ind". But in graph it don't show any relation.

![data_screen](https://cloud.githubusercontent.com/assets/9677491/17137367/77077f64-5358-11e6-9223-b1084c08127a.png)
![graph_screen](https://cloud.githubusercontent.com/assets/9677491/17137370/7b18a4b6-5358-11e6-8994-55556927c6e1.png)

**Comment by maggiolo00** [comment]
@dhirender-tyagi 

Graph rendering works only with Graph Domain (Vertex / Edges).  Does not render link/ linkset
