### ISSUE TITLE
locked indefinitely on com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire()

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6469]
orient DB 2.1.19
Windows 7 Professional SP1
Intel i5-4460 @ 3.20GHZ 8GB RAM

Multiple traces locked indefinitely on com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire() semaphore
See attached TXT file containing stack traces

**Comment by laa** [comment]
@jamieb22 are you sure that it is the same threads, but not the case when several threads are waiting for long time because of small connection pool size ?

**Comment by jamieb22** [comment]
i'll ask Valentin (since he is our resident Orient DB guru).  How would one increase the connection pool size via the API?

**Comment by jamieb22** [comment]
May I also make a suggestion Andrey? I suggest to use Amazon CDN service for Orient DB downloads. Orient DB updates take more than 28 minutes for me to download from your website.

**Comment by laa** [comment]
Hi @jamieb22 , according to thread dump which you sent 338 threads are waiting in a pool. 
According to code which you sent  your pool size is 80. could you change pool size to 400 and then check whether the same situation appears.

**Comment by laa** [comment]
Hi @jamieb22 any updates ?

**Comment by laa** [comment]
Well I close the issue. Please reopen it if it happens again.
