### ISSUE TITLE
date field gets interpreted as datetime

### ISSUE THREAD

**Issue by eyurtsev** [orientechnologies/orientdb#6470]
## OrientDB Version, operating system, or hardware.

- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[X] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

'Date' fields get interpreted as 'Datetimes' instead of 'Date'

## Steps to reproduce the problem

```
CREATE CLASS V1 EXTENDS V
CREATE PROPERTY V1.x Date
CREATE VERTEX V1 SET x='2016-01-01'
SELECT x.type() from V1
```

Should return 'date' not 'datetime'

**Comment by obi1kenobi** [comment]
Confirmed on 2.1.16 as well.

**Comment by luigidellaquila** [comment]
Hi guys,

All date objects (date and datetime) are physically stored as java.util.Date, so the returned type for the single value is the same, regardless of how it was defined in the schema.

If you want to have info from the schema, you have to use the following statement:

```
select properties[name = 'x'].type from (select expand(classes) from metadata:schema) where name = 'V1'
```

You will get a code for each type, the encoding is defined here

http://orientdb.com/docs/2.2.x/Types.html

Thanks

Luigi

**Comment by obi1kenobi** [comment]
What you propose sounds more like a workaround than a fix. OrientDB has access to the schema, so why not return the correct value in the first place rather than force the client to make extra queries and reinterpret its received value?

@lvca also seems to think this is a bug in OrientDB, rather than expected behavior as you @luigidellaquila seem to suggest.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

it's not a bug, `type()` is method that is invoked on the result of `x` and `x` is a normal java.util.Date object. I really don't think that we can change ODocument.field() method to return a specified (non java standard) value for date and datetime, so I'm afraid we will have to deal with it.

Thanks

Luigi
