### ISSUE TITLE
Using a Lucene index in a Match SQL command

### ISSUE THREAD

**Issue by jmyslik** [orientechnologies/orientdb#6473]
I am using OrientDB v2.2.3 community edition on a Windows 10 machine.

I'd like to use a Lucene index in the context of a Match SQL Command:

match {class: Person, as: person, where: (name lucene 'smith')}<-AliasOf-{as: aliasname} return person.name, aliasname.name

When I run this command OrientDB throws the following exception: 

java.lang.IndexOutOfBoundsException: Index:0, Size:0

Whereas when I run the command: 

select name, in('AliasOf').name from Person where name lucene 'smith'

Orient DB returns the list of alias without throwing an exception.

Can you use a lucene index in a match command?

**Comment by luigidellaquila** [comment]
Hi @jmyslik 

There should be no difference between SELECT and MATCH, so I guess it's a bug.
I'm checking it, I'll let you know soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, I found the problem and I'm fixing it.

Thanks

Luigi

**Comment by jmyslik** [comment]
Thanks Luigi. Since I'm new to OrientDB, I'd appreciate if you'd tell me how to apply the fix once you're done.

**Comment by luigidellaquila** [comment]
Hi @jmyslik 

I pushed the fix on branch 2.2.x, it will be available in next 2.2.7 (probably released next week).

If you want to try it now, you can build from source (http://orientdb.com/docs/last/Tutorial-Installation.html#source-code-installation) or wait for next snapshot on Sonatype
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.7-SNAPSHOT/ that is a full distribution. The snapshots are generated many times a day, just make sure that the version you download is recent enough con contain the fix

Thanks

Luigi
