### ISSUE TITLE
Check on parallel query to find corner cases

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6475]
We could start by running all the test cases with auto parallel = true.

**Comment by lvca** [comment]
In this way the SQL engine will use multiple threads to execute the query, but only if:
- a scan is executed, so no parallel for indexes
- the class has multiple clusters
- the target class has at least 300,000 records (configurable)

**Comment by luigidellaquila** [comment]
Reopening, deadlock can happen with parallel queries

**Comment by lvca** [comment]
@luigidellaquila is the new SQL engine multi-threads in the meaning that it can scan by using multiple threads?
