### ISSUE TITLE
running docker with -Ddistributed=true throws error with databasis of type 'memory'

### ISSUE THREAD

**Issue by anber500** [orientechnologies/orientdb#6477]
orientdb docker image:latest - v2.2.4

When running the docker container for orientdb with -Ddistributed=true, unit tests that create databases of type 'memory', can't connect to database or remove the databases.

orientdb throws the following error:
java.lang.StackOverflowError

This happens when connecting to the created database via the browser, console.sh or through code.

## Steps to reproduce the problem
1) Create a docker container with a similar command like this:

docker run -d --name minion --net=host -p 2424:2424 -p 2480:2480 -p 2434:2434 -p 5701:5701 -e ORIENTDB_NODE_NAME=minion -v /home/**user**/orient-config:/orientdb/config -v /home/**user**/databases:/orientdb/databases  -e ORIENTDB_ROOT_PASSWORD=**password** orientdb:latest /orientdb/bin/server.sh  -Ddistributed=true

replace bold values with your own!

2) in a unit test, attempt to create a database with name 'unittest' of type '**memory**'.

3) attempt to remove the database 'unittest'

Observe:
orientdb returns with error:

> java.lang.StackOverflowError

If docker image is created without **-Ddistributed=true**, the database can be created and removed without any errors.

**Comment by robfrank** [comment]
memory database is not supported in distributed setup. We will update the docs:

http://orientdb.com/docs/last/Distributed-Architecture.html#limitations
