### ISSUE TITLE
Cannot set network.http.useToken to true

### ISSUE THREAD

**Issue by deacix** [orientechnologies/orientdb#6478]
## OrientDB Version, operating system, or hardware.
- v2.2.5 [x]

## Operating System
- [x] Linux
- [x] MacOSX

## Expected behavior and actual behavior

Trying to use oAuth2 Token for HTTP Rest API.

## Steps to reproduce the problem

Cannot set network.http.useToken to true over xml config:

<properties>
        ...
        <entry value="true" name="network.http.useToken"/>
      ...
    </properties>

and -Dnetwork.http.useToken=true

to use OrientTokenHandler.

<handler class="com.orientechnologies.orient.server.token.OrientTokenHandler">

The handler throws an NullPoint Exception because network.http.useToken has as default false and no tokenHandler is available.

com/orientechnologies/orient/server/network/protocol/http/command/post/OServerCommandPostAuthToken.java
```
private void init() {

    if (tokenHandler == null && OGlobalConfiguration.NETWORK_HTTP_USE_TOKEN.getValueAsBoolean()) {
      tokenHandler = server.getTokenHandler();
    }
  }
```
Works only in embedded mode with this:

`OGlobalConfiguration.NETWORK_HTTP_USE_TOKEN.setValue("true");`

**Comment by tglman** [comment]
hi @deacix,

I fixed the case, will be out with 2.2.7, closing.

**Comment by deacix** [comment]
hey! Thanks!

**Comment by deacix** [comment]
But this is not full fix. It is not possible to set network.http.useToken to true over xml config.

**Comment by tglman** [comment]
hi @deacix,

I double checked also that case, setting in the properties this 
`<entry name="network.http.useToken" value="true"/>`
the token is enabled 

Regards.

**Comment by deacix** [comment]
ok thanks!
