### ISSUE TITLE
HTTP Rest API is not supporting 'X-Requested-With': 'XMLHttpRequest'

### ISSUE THREAD

**Issue by deacix** [orientechnologies/orientdb#6479]
## OrientDB Version, operating system, or hardware.
- v2.2.5 
## Operating System
- [x ] Linux
- [x ] MacOSX
## Expected behavior and actual behavior

Please add support for 'X-Requested-With': 'XMLHttpRequest' in the OrientDB Rest API.
## Steps to reproduce the problem

After ajax request to the rest api with not valid credentials and headers:
'X-Requested-With': 'XMLHttpRequest'
 response is comming back with "www-authenticate" header. The browser open automatically athentication popup. Very wrong to work with ajax.

**Comment by lvca** [comment]
Do you mean in the 'Access-Control-Allow-Headers' header?

**Comment by deacix** [comment]
Hi! Not i main the rest api server have to support X-Requested-With header:

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Requested-With

for better integration for Web Apps. I am currently working on an AngularJS 2 App with direct using the REST API from OrientDB. 

You have to add a check for the 'X-Requested-With': 'XMLHttpRequest' in this places:

com.orientechnologies.orient.server.security.ODefaultServerSecurity#getAuthenticationHeader
and here 
com.orientechnologies.orient.server.security.OSecurityAuthenticatorAbstract#getAuthenticationHeader

and avoid to send the "www-authenticate" header if you have header 
'X-Requested-With': 'XMLHttpRequest'
in the client request.

**Comment by lvca** [comment]
What should OrientDB send if the client is not authenticated?

**Comment by deacix** [comment]
Request Headers:
GET /class/smsc/Customer/ HTTP/1.1
Host: localhost:2480
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,ru;q=0.2

Response Headers:
HTTP/1.1 401 Unauthorized
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
date: Thu Jul 28 16:31:10 CEST 2016
content-type: application/json; charset=utf-8
server: OrientDB Server v.2.2.5
connection: close
access-control-allow-origin: *
access-control-allow-credentials: true
x-frame-options: DENY
www-authenticate: Basic realm="OrientDB db-smsc"
set-cookie: OSESSIONID=-; Path=/; HttpOnly
content-length: 129

Also the response is not gziped.. Very wrong? 

Response:

{
  "errors": [
    {
      "code": 401,
      "reason": "Unauthorized",
      "content": "401 Unauthorized."
    }
  ]
}

**Comment by lvca** [comment]
@deacix WDYT about a Pull Request after you tested it?
