### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientdb#6482]
On the page: http://orientdb.com/docs/last/Indexes.html

1) The example code under "Alternatively, you can look a public up through the field publicationYear:" does not pertain to the stated example.

2) Direct insertion for composite indexes is not yet supported in OrientDB. This is no longer true. This syntax is supported since at least 2.2 GA: INSERT INTO INDEX:test (key,rid) values (['test','success'],#1:0)

**Comment by smolinari** [comment]
Hope the PR is ok. :smile: 

Scott
