### ISSUE TITLE
Feature Suggestion - Block Index

### ISSUE THREAD

**Issue by jacksenk** [orientechnologies/orientdb#6483]
An index which would help save disk space and be efficient when searching for things in ranges.

Each index entry would have a start and end value, and a value.

i.e.:

0-100 | 101 - 200 | 201 - 300 |
@21:0 | @21:17     |   @98:7

So rather than making an index entry for all values 0 - 100 pointing to the same record, using this block index style one could just search for '75' and it'd return @21:0 because it is within the range

Use case:
IP blocks to country database
IPs would be grouped together in their respective blocks with a record to their related country, rather than making an index entry for each IP, you'd use this block index

**Comment by lvca** [comment]
This is out of scope of OrientDB. You could implement this manually by using OrientDB to store ranges and create functions that use them.
