### ISSUE TITLE
Creating a sequence using the API and the example in the docs throws NPE

### ISSUE THREAD

**Issue by odysseaspenta** [orientechnologies/orientdb#6484]
## OrientDB Version, operating system, or hardware.
- v2.2.5

## Operating System
- [X] Linux

## Expected behavior and actual behavior
When using the example from the documentation that describes how to create a sequence using the API, a NullPointerException is generated. The example looks like:
```
OSequenceLibrary sequenceLibrary = database.getMetadata().getSequenceLibrary();
OSequence seq = sequenceLibrary.createSequence("idseq", SEQUENCE_TYPE.ORDERED, new OSequence.CreateParams().setStart(0));
```
The issue is on line 98 of OSequence class. The code expects the increment parameter to be set but the example doesn't set a value which causes an NPE. Setting a default value of 1 for the increment should take care of the issue.
```
  protected void initSequence(OSequence.CreateParams params) {
    setStart(params.start);
    setIncrement(params.increment);
    setValue(params.start);

    setSequenceType();
  }
```
and the stack trace is:
```
java.lang.NullPointerException
	at com.orientechnologies.orient.core.metadata.sequence.OSequence.initSequence(OSequence.java:98)
	at com.orientechnologies.orient.core.metadata.sequence.OSequence.<init>(OSequence.java:92)
	at com.orientechnologies.orient.core.metadata.sequence.OSequenceOrdered.<init>(OSequenceOrdered.java:25)
	at com.orientechnologies.orient.core.metadata.sequence.OSequenceHelper.createSequence(OSequenceHelper.java:16)
	at com.orientechnologies.orient.core.metadata.sequence.OSequenceLibraryImpl.createSequence(OSequenceLibraryImpl.java:77)
	at com.orientechnologies.orient.core.metadata.sequence.OSequenceLibraryProxy.createSequence(OSequenceLibraryProxy.java:36)
	at 
```
It was fixed in our code by initializing the increment parameter in addition to the starting value first.

**Comment by luigidellaquila** [comment]
Hi @odysseaspenta 

I'm on it

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @odysseaspenta 

I just pushed a fix on both 2.2.x and develop

Thanks

Luigi

**Comment by smolinari** [comment]
Could it be feasible to allow the client to select the starting point of the increment? 

Scott

**Comment by luigidellaquila** [comment]
Hi Scott,

The config has a setStart() method for this ;-)

Thanks

Luigi

**Comment by smolinari** [comment]
Ah, sorry. I missed that above. 

And nevermind. In SQL there is a START parameter. So I am happy. :smile: :+1: 

http://orientdb.com/docs/2.2/SQL-Create-Sequence.html

> START - Defines the initial value of the sequence.

Scott
