### ISSUE TITLE
"No nodes configured for partition" on record.delete() after upgrading to 2.2.5

### ISSUE THREAD

**Issue by fredfortier** [orientechnologies/orientdb#6493]
## OrientDB Version, operating system, or hardware.
- v2.2.5
## Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

I am using OrientDB in embedded distributed mode with only one node. Currently, the reason for using the distributed mode is to connect with plocal and remote concurrently.

In the Hazelcast config, I am using tcp/ip instead of multicast. All other config parameters are basically the default distributed config.

I am using a document database primarily through the Java Object API.

My issue is that I get the error below when trying to delete a record. The record does delete successfully but the database always return the error. I can reproduce the error both using the Java API and in the Studio.
com.orientechnologies.orient.server.distributed.ODistributedException: No nodes configured for partition 'kwcn.[results]' request: id=0.7 task=record_delete(#71:7)

I was using the exact same code without getting the error prior to upgrading from 2.1.6 to 2.2.5.
## Steps to reproduce the problem
- Initialize the server (in embedded mode)
- Obtain and delete a record like this
  `
              ODocument record = db.getRecordByUserObject(currentResults, false);
              record.delete();
  `
- Alternatively, issue a DELETE command in the Studio app

**Comment by lvca** [comment]
What's your distributed cfg? Please copy and paste the one found under the database directory (not the default under config)

**Comment by fredfortier** [comment]
Here is the entire config folder that I am using at runtime: [orient db config folder](https://www.dropbox.com/s/1mmbfckr9mwf3dz/config-2.2.x.tar.gz?dl=0)
