### ISSUE TITLE
strategy advice: distribution/replication means each server get full (#TB !) copy of dbase ?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6497]
## OrientDB Version, operating system, or hardware.
- **v2.2.5**

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Our dbase is growing into several TB filesystem size. We have 6 identical servers, spread over 2 datacenters, 3 servers per datacenter.
When I want redundancy, and distribution of workload, among these 6 servers, what is the best strategy?
I want to avoid that the full database size gets copied, and synchronised, between all 6 servers. What I think would be more beneficial, is that clusters are spread accross the 6 servers, with for example 3 copies of each cluster (2 in same DC, 1 in alternate DC).
Is that a good strategy to achieve maximum performance (parallel workloads) and space optimisation ?
If so, how to configure OrientDB for this ?

**Comment by lvca** [comment]
If you have data-centers, the Enterprise Edition is suggested, because it supports them: http://orientdb.com/docs/last/Data-Centers.html. In this way you can keep the writeQuorum to the majority IN the data centers, rather than all the servers that in your case is 6 and N/2+1 = 4 servers (as majority).

If you have TB of database and it's growing, maybe sharding is a better strategy. What kind of workload do you have? Mostly read than write? How many read/write per second do you want to achieve? Are you using graph, document or mixed API?

**Comment by rdelangh** [comment]
Someone commencted indeed in another topic that different classes can be created for the same data, with then a specific class per range of that data (eg all records for a same day in the same class, records for other day in another class, etc)

This is an interesting suggestion, but the mechanism of OrientDB for distributed processing is described with entire databases, which get copied entirely between the servers that participate in the distributed config for such database. I am hesitating to believe that this mechanism of replicating entire databases is scalable for truely BIG databases (multiple TBs, and more).

I analysed the documentation about the sharding, where the per-database config file can specify on which servers specific clusters should be replicated/distributed. That seems a very applicable way of working which I would like to test, but : we want to keep the ease of working to cleanup old records from the class , by simply doing a DROP CLUSTER of one entire cluster, which therefor needs to be created with some date-range criteria (all data of a same date or date+hour reside in the same cluster). This implies that we will need to create **many** clusters, we will of course use some naming convention. And these clusters will need to be created for several (nearly all) of our classes.

So, referring to the documented config file for sharding, "distributed-db-config.json", there will need to be all these **many** clusters included in the config file, each one (of the cluster names) with a specification of which servers must hold that cluster.
-> can this config file contain cluster-name patterns ? For example, I could specify all clusters whose name is ending on a particular digit (10 possible combinations) in the config file, such as 

"clustername_*_5": { "servers": [ "serverA", "serverB", "serverC" ] }, 
"clustername_*_6": { "servers": [ "serverD", "serverE", "serverF" ] },
...

**Comment by smolinari** [comment]
You could also theoretically set the database to one cluster per class with

ALTER DATABASE MINIMUMCLUSTERS 1

And then add your "time based" clusters to the class manually yourself. 

@lvca - It would also be cool, if the clusters per class setting would be at class level. That would offer the best flexibility.

Scott

**Comment by rdelangh** [comment]
Scott, thx for this info, it sounds something we will need to set indeed in order to be sure we can make the clusters (per class) ourselves (with convenient filenames, and applicable sharding-config).
And yes it would be ideal if we can set this on a per-class level, instead of one setting for the entire database.

Remains the question if the interpretation of the sharding-config file supports cluster-name patterns, like I described above. I guess so (altough not sure) because the template contains the asterisk:

...
  "clusters": {
    "internal": {
    },
    **"*"**: {
      "servers": ["<NEW_NODE>"]
    }
  }

**Comment by rdelangh** [comment]
I was studying in detail the 'sharding' configs of OrientDB, and found this remark under the "Cluster Locality" section of "http://orientdb.com/docs/last/Distributed-Sharding.html" : 

OrientDB automatically creates a new cluster per each class as soon as a node joins the distributed cluster. These cluster names have the node name as suffix: <class>_<node>.  ...This also means that in distributed mode you can't select the cluster selection strategy, because "local" strategy is always injected to all the cluster automatically. ...

Does this mean that, in distributed mode, I cannot create clusters myself and give them a naming-convention which allows my INSERT or SELECT statement to specify one particular cluster only ?

**Comment by smolinari** [comment]
Being you can rename clusters, I don't think there is an issue with what you want to do. The section of the docs you referred to is simply the standard operation of ODB. And, as of 2.2.0, ODB creates multiple clusters per class. So, you'll have to make ammends for that.

On a side note, reading the docs (again).....

The whole distribution part of ODB needs an overhaul from a terminology standpoint. Cluster is simply the wrong word. It should be "shard". When ODB creates a class, it creates multiple shards. That is how it should read. 

And currently, [according to the limitations](http://orientdb.com/docs/last/Distributed-Sharding.html), sharding is a user-land responsibility.  

The "mix-up" of the term cluster with shard is even evident in the limitations section.

> Selecting the right shard (cluster) is up to the application. 

Hopefully this will be addressed in 3.0 too. I am crossing my fingers. :smile: 

Scott

**Comment by lvca** [comment]
That's right, the cluster is like a shard. In v2.2 we don't use the server name as suffix anymore, but if you want a cluster (shard) is stick to a server, you can use the "owner" tag in the json configuration.

**Comment by smolinari** [comment]
@lvca - does that mean the docs needs some additional work? There is no mention of an "owner" tag, nor how such a tag can be used to shard with. At least I couldn't find anything.

Scott

**Comment by lvca** [comment]
This was already documented: http://orientdb.com/docs/2.2/Distributed-Architecture.html#static-owner. I've just added it also in the http://orientdb.com/docs/2.2/Distributed-Configuration.html.

**Comment by smolinari** [comment]
Would using the static owner then mean high availability is no longer possible? 

Scott

**Comment by lvca** [comment]
If the owner server is down, no new records can be created on that cluster. However, usually the cluster is selected by OrientDB, not the user. In this cases, OrientDB will simply select another available cluster.

But in the case you want to write to the cluster "Log_15_08_2016" and it's not available, I think it's right an error is provided.

**Comment by smolinari** [comment]
Ok. I get it. So, in the case where a user wants to be selective of clusters, then they will be giving up HA to get that ability. If they aren't specific about the cluster, ODB will carry on happily, despite a node dropping offline, and HA is still upheld.

Yes, I'd say an error on writes to distinctly targeted clusters, when the node with the owning cluster is down, would be a good idea, if it isn't already the case. :smile: 

Scott

**Comment by rdelangh** [comment]
Is this confirmed ?
"So, in the case where a user wants to be selective of clusters, then they will be giving up HA to get that ability" because every cluster has only a **single** 'owner' server ?

We need to be selective of the clusters in which we insert some records and from which we query records, in order to
1) have control over the replication-level of the big database, to avoid that the full database size gets copied, and synchronised, between all servers which are part of a distributed setup. Instead we want that clusters are spread accross all the servers, but with for example 3 copies of each cluster (2 in same DC, 1 in alternate DC)
2) take backups (or restores) selectively on a per-cluster basis (old clusters do not change anymore, so do not need backups anymore; backups needed only of clusters with 'recent' data)

**Comment by smolinari** [comment]
That is what I am trying to get at. The mix between ODB controlling clusters and the user controlling clusters isn't totally clear to me. What are the advantages and disadvantages? 

Scott

**Comment by rdelangh** [comment]
Even more : if there is a concept required of 'owning' server for each cluster in a distributed setup, then what is the advantage of having your clusters distributed over multiple servers ? The mechanisms behind this concept are not very clear to me, how they would still allow to 
1) distribute queries that span a single cluster, to be distributed over multiple servers (each one doing part of the work of the query)
2) keep the clusters accessible in all cases (HA) for INSERT as well as SELECT

**Comment by lvca** [comment]
Hi guys,

If you don't specify the owner, OrientDB will take care to reassign it to an available server from the `servers` list. So this is the default and fail over works. But if you want a server is the sticky owner, it's your choice.

**Comment by rdelangh** [comment]
@lvca 
We have 6 servers, and I want to avoid that the entire multie-TB database gets replicated on each and every server (too much traffic). 
Therefor I think of defining data-clusters upfront with a naming convention, that I can use in the "distributed-db-config.json" file to assign alternating (round-robin alike) sets of 3 servernames per cluster-name patterns:
For example, for clusters that will be assigned to a class "classXX", all the clusters that have names ending on "_0" 

...
"classXX_cl*_0": { "servers": [ "serverA", "serverB", "serverC" ] },
"classXX_cl*_1": { "servers": [ "serverB", "serverC", "serverD" ] },
"classXX_cl*_2": { "servers": [ "serverC", "serverD", "serverE" ] },
"classXX_cl*_3": { "servers": [ "serverD", "serverE", "serverF" ] },
"classXX_cl*_4": { "servers": [ "serverE", "serverF", "serverA" ] },
"classXX_cl*_5": { "servers": [ "serverF", "serverA", "serverB" ] },
...

With the 6 servers, I can thus make 6 such groups of clusters that each have 3 servers assigned.

To identify in which cluster we will store our time-based records (they all carry some date/time attribute), that last digit of the cluster-name can be determined from the hour in the record, modulo 6 : 24 hours in a day, hence 6 possible results from MODULO(hour,6)

I am thinking of creating clusters for each class, per day, and per MODULO(hour,6) : for example (for Aug-19 2016):

classXX_cl20160819_0 , classXX_cl20160819_1, classXX_cl20160819_2, classXX_cl20160819_3, classXX_cl20160819_4 and classXX_cl20160819_5

I will then use a INSERT INTO classXX_cl20160819_1 statement to store all records with date 20160819 and hour 01am, 07am, 1pm, 7pm

So far so good.

The only thing I don't know how to realize, is how to connect client programs via the RESP-API to this OrientDB setup, in a way that the clients can reach all data:

- with a connection to "serverA", all clusters with names ending on "*_0", "*_4" and "*_5" can be accessed
- with a connection to "serverD", all clusters with names ending on "*_1", "*_2" and "*_3" can be accessed

Right ?

So each client should make 2 connections in order to be able to access all of the clusters ?

What if for example "serverA" fails? To which server shall the client then connect ?

**Comment by smolinari** [comment]
This is where I was also heading here. 
https://groups.google.com/forum/#!topic/orient-database/lBDvEonG32I

Scott

**Comment by lvca** [comment]
@rdelangh your design looks good to me and actually most of it will be automatic with OrientDB v3.0 and auto-sharding ;-)

About the connection, don't worry: whatever server you're connected, OrientDB will forward the command to the right ones to retrieve the data you requested. So you can be connected to any node and if the cluster/record is not on the local server, a map-reduce request will be sent to the involved servers. It's all hidden to you, you just write SQL.

**Comment by smolinari** [comment]
>About the connection, don't worry: whatever server you're connected, OrientDB will forward the command to the right ones to retrieve the data you requested. So you can be connected to any node and if the cluster/record is not on the local server, a map-reduce request will be sent to the involved servers. It's all hidden to you, you just write SQL.

Ahh..that is the piece of the puzzle that was missing in my mind. :+1: 

Scott

**Comment by rdelangh** [comment]
indeed, this connectivity subject is looking good ;-)

Luca, about "your design looks good to me and actually most of it will be automatic with OrientDB v3.0 and auto-sharding ;-)" , can you please provide more details about the "most of it" ?

**Comment by lvca** [comment]
With OrientDB 3.0 we are working to the auto-sharding where you configure the number of partitions (clusters) and the replica factor, then OrientDB moves clusters between nodes for you automatically by guaranteeing the configured replica factor. By default the sharding algorithm is a Murmur Hash against the field you declare as sharded-index, but you could provide your own strategy.

**Comment by smolinari** [comment]
Ohh....that sounds really good @lvca! :heart_eyes: 

However, please, please, please do also change the terminology in 3.0 by changing clusters to shards, so the replication, sharding and server clustering (what a cluster should be) all make absolutely perfect sense! :smile: I know that most likely means a lot of reworking of code and documentation, but it will also mean a whole lot less confusion for users, especially now that ODB will be doing sharding on its own. That will be so cool! :heart_eyes: I'll also volunteer to help with the docs, if you make the change. That is how important I think it is for 3.0's success. 

Scott

**Comment by lvca** [comment]
I don't know if shard is the right word: https://en.wikipedia.org/wiki/Shard_(database_architecture). Maybe partition?

**Comment by rdelangh** [comment]
@lvca 
This wiki also defines "Beyond partitioning, sharding thus splits large partitionable tables across the servers, while smaller tables are replicated as complete units."
Is this ("smaller tables are replicated as complete units") the case in ODB ? If not, then the term 'partitioning' will indeed be more applicable, no ?

**Comment by rdelangh** [comment]
@lvca 
Can you please give any estimation about when this functionality will be implemented, i.e. when you're announced version 3.0 will be made available to us ?
What part of my 'design' ideas can I already implement with the currently available version 2.2.7 ?

**Comment by smolinari** [comment]
@lvca 

In that definition you linked to, it says...

>A database shard is a horizontal **partition** of data in a database or search engine. Each individual **partition** is referred to as a shard or database shard.

and 

> Horizontal partitioning is a database design principle whereby rows of a database table are held separately...
>Each partition forms part of a shard, which may in turn be located on a separate database server or physical location.

Partition and shard seem to be pretty much the same thing, but it seems a partition can be part of a shard. 

And then you have this about the horizontal partion:

Horizontal partitioning splits one or more tables by row, usually within a single instance of a schema and a database server.

And then this: 

>Sharding goes beyond this (horizontal partitioning): it partitions the problematic table(s) in the same way, but it does this across potentially multiple instances of the schema. The obvious advantage would be that search load for the large partitioned table can now be split across multiple servers (logical or physical), not just multiple indexes on the same logical server.

So a partition is within a single server and thus, wouldn't be a proper term.  Shard is the correct term. :smile: 

Scott

**Comment by rdelangh** [comment]
@smolinari 
Scott, I basically agree that 'sharding' sounds most applicable, but the only remark in the wiki that is leaves room for confusion is "smaller tables are replicated as complete units" . When we ignore that remark, 'sharding' is indeed best term.

**Comment by smolinari** [comment]
Why ignore it? In fact, this is how ODB should work. If and only if a class reaches specific thresholds, then ODB would start to split it up into shards. If there is a cluster of servers and a configuration for HA, ODB should be replicating the class, as a whole, automatically and/or according to preconfigured settings. 

Think of it, splitting up a class too early does nothing for ODB or the user. It is only when accessing  or manipulating data within the class starts to degrade, does it make sense to split the class up into shards. Obviously, the decision to split up the class into shards needs to be made way before problems arise. But, there is really no reason to split the data in a class up (vertically or horizontally partition it) into shards beforehand. 

The last piece of the missing puzzle for me is a system to rebalance shards. For instance, what happens, if a new set of nodes is added to the system? ODB would have to redistribute the data among the shards evenly/ properly. Right?

The last possible feature to cover is the control over the locality of data. This would be a reason, from a user-land standpoint, to shard early, as in before sharding is needed from a performance perspective. So, if shards are determined by the user to be located in different servers or server clusters in different data centers, that is then a configuration setting.  This would need to be redefinable at any time too and would need that sharding redistribution system in ODB I just mentioned.

One last note, while I am warm. I personally think the shard (cluster) per core thing that ODB does now, should also be rethought in 3.0. A user with 24 cores servers doesn't need his classes split up into 24 shards until really late in the game. It would be overkill early on and with the limit on the number of shards, quickly debilitating too. ODB shouldn't rely on the user knowing he or she can change the shards per core setting. This needs to be something that simply runs in the background. If a class is getting hit too hard per server or rather access to data could start to degrade, at that point should ODB start to attempt to vertically shard or horizontally shard. If fact, if ODB could do this well, it would be another feather in its cap to put it above the rest. :smiley:     

Scott
