### ISSUE TITLE
set JAVA_OPTS_SCRIPT only if it has not been set before

### ISSUE THREAD

**Issue by vishu18** [orientechnologies/orientdb#6504]
## OrientDB Version, operating system, or hardware.
OrientDB 2.2.6

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
In the packaged server.sh for OrientDB 2.2.6  under orientdb-community-2.2.6/bin, the 
variable JAVA_OPTS_SCRIPT is explicitly set. This makes it hard to remove options like  -XX:+HeapDumpOnOutOfMemoryError unless one edits the server.sh directly. 
Is it possible to set this variable only if it has not been previously set.

**Comment by robfrank** [comment]
done here
https://github.com/orientechnologies/orientdb/commit/f0767dc8ea6793fef7a5a640bf7c6decbbcead86

will be included on 2.2.7

**Comment by cmassi** [comment]
You have added the condition  if [ -z "$JAVA_OPTS_SCRIPT" ]  which is going to check if JAVA_OPTS_SCRIPT is empty, and set the usual value.
This is fine, but in server.sh script (2.2.7) the original line JAVA_OPTS_SCRIPT="....-XX:+HeapDumpOnOutOfMemoryError....", has not been removed, and so will overwrite any CLI setttings
The original line is after WWW_PATH, before the new if statement, so you will never set JAVA_OPTS_SCRIPT using the new if statement, and still have to edit server.sh to remove the original line.
Please remove the original line with JAVA_OPTS_SCRIPT, and keep the new if [ -z "$JAVA_OPTS_SCRIPT" ], as requested .
With Oracle java 8 you can use "jcmd OServerMain VM.command_line" to verify command line settings, and run a quick test with: JAVA_OPTS_SCRIPT="-Dnone" ./server.sh

**Comment by robfrank** [comment]
Your're right, I'm sorry. 
Fixed here: https://github.com/orientechnologies/orientdb/commit/4f4f62c1c10b94dce0a7acad3cdac05dde25fb3c

will be inside 2.2.8

**Comment by ginojohn** [comment]
Is it possible to include this change in the v2.1.x release
