### ISSUE TITLE
ETL: Unable to migrate data with quotes, ampersand etc. 

### ISSUE THREAD

**Issue by ritesh0919** [orientechnologies/orientdb#6506]
## OrientDB Version, operating system, or hardware.

OrientDB 2.2.0 Community
## Operating System
- [x] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

While migrating data from RDBMS to OrientDB, we are using the oetl. The table in concern is a mapping table (many to many) and hence we are using "transformer" -> "command" - CREATE EDGE selecting vertices as "FROM" and "TO". Along with this, we use "SET" to set variable properties of the edge. In one of the columns in RDBMS table, there are data like quotes, ampersand etc. While running the migration scripts, it fails but the same command works in Orient Studio. 

We tried using merge in transformer and then setting the attributes using "edge" -> "edgeFields", however the behaviour was the same. 

How do we import such kind of data? Is there any method available in oetl, which will encode these data?

**Comment by robfrank** [comment]
Sorry for the delay. Could you attach to the issue a sample data file and a configuration file? Are you using the jdbc source or are you loading from csv?

**Comment by ritesh0919** [comment]
Hi,

This is from a JDBC source (Oracle). The oracle table has a column which contains apostrophe in the data eg: "Ritesh's request". When we try to migrate this data, the etl process fails complaining about this apostrophe. 

Here is a sample JSON file:

```
{
  "extractor" : {
    "jdbc": {
      "driver": "$sourceDbDriver",
      "url": "$sourceDbURL",
      "userName": "$sourceDbUsername",
      "userPassword": "$sourceDbPassword",
      "query": "SELECT * FROM USER_RESOURCE "
    }
  },
  "transformers" : [
    { "command" : { "command" : "CREATE EDGE HAS_ADMIN FROM
        (SELECT FROM RESOURCE WHERE ID = ={eval('$input.RESOURCE_ID')})
        TO
        (SELECT FROM PERSONS WHERE ID = ={eval('$input.USER_ID')})
        SET
        RESOURCE_TYPE = ={eval('$input.RESOURCE_TYPE_ENUM')},
        GRANT_REASON = '={eval('$input.GRANT_REASON')}',
        LAST_UPD_DT = '={eval('$input.LAST_UPD_DT')}',
        LAST_UPD_USER_ID = ={eval('$input.LAST_UPD_USER_ID')},
      "
      }
    }
  ],
  "loader" : {
    "orientdb": {
      "dbURL": "$destDbURL",
      "dbUser": "$destDbUsername",
      "dbPassword": "$destDbPassword",
      "serverUser": "$destDbUsername",
      "serverPassword": "$destDbPassword",
      "dbAutoCreate": false,
      "dbAutoCreateProperties": false,
      "dbAutoDropIfExists": false,
      "tx": false,
      "batchCommit": 1000,
      "dbType": "graph",
      "wal": false,
      "useLightweightEdges" : false
    }
  }
}   

```
In the above JSON file, GRANT_REASON fails. 

Let me know if any further information is needed.

**Comment by robfrank** [comment]
Ok, I was able to replicate the problem. Your text contains a single quote, so when the command is parsed it generates something like this:
```
GRANT_REASON = 'the string as a single quote ' and this part isn't read'
```
Try this:

```
GRANT_REASON = \"={eval('$input.GRANT_REASON')}\"
```

**Comment by ritesh0919** [comment]
Sure. I will try this. Basically, only difference is we need to use an escaped double quotes (instread of single quotes0 surrounding the eval for GRANT_REASON. Thanks

There is one other issue, if you see the LAST_UPDATE_DT, which is a date and can be null. Having said that, we can either get null or a valid date. If we put a single quote surrounding eval, null value gets inserted as a string and NOT a NULL. If we do not put that quote then valid date get errored out because there are no quotes for it. 
Let me know if this can be addressed in this issue or I open a new issue.
