### ISSUE TITLE
why ORecordBytes cluster 3 is invisible? how to copy a chunk ?

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6508]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[x ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
insert into ??? select from #3:33
insert into cluster:3 select from 3:30

Error: com.orientechnologies.orient.core.exception.OStorageException: Cluster 3 does not exist in database 

in addition how is possible in distributed mode to save a file(multiple chunks) in serverA , another file in serverB?

**Comment by tglman** [comment]
hi  @publicocean0,

as today the  ORecordBytes use the `dafault` that usually is 3,  since 2.2 you can define as well a specific cluster for that using `db.addBlobCluster("clusterName")`

Hope it help

**Comment by publicocean0** [comment]
yes i know considering you want copy a chunk using console or remote command (so you have no data transfer to client). How to do? 
not having class , i dont know how to copy. 

i tried 

insert into cluster:3 select from 3:30 

for copying in the same cluster 3 the chunk 3.30. 

Error: com.orientechnologies.orient.core.exception.OStorageException: Cluster 3 does not exist in database
