### ISSUE TITLE
question wrapper  for embedded object

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6509]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[x ] - .rc1[ ] .beta2[ ] .beta1[ ]
## Operating System
- [ x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

var con=db.command("select $d.a as a, $d.b as b  from #58:10 let d= data[0]");
con[0].a; undefined
con[0].get('a') undefined

con[0].a is maybe undefined because is cast to wrongly to OIdentifiable 
## Steps to reproduce the problem

error seams there 

<pre>
public Object command(final String iText, final Object... iParameters) {
    Object res = database.command(new OCommandSQL(iText)).execute(convertParameters(iParameters));
    if (res instanceof List) {
      ------> final List<OIdentifiable> list = (List<OIdentifiable>) res;
   --->   return list.toArray(new OIdentifiable[list.size()]);
    }
    return res;
  }
</pre>

**Comment by publicocean0** [comment]
i m investigating on my own ... 
computing ....

**Comment by publicocean0** [comment]
i found the answer. It could be added for documentation also embedded map is converted in ODocument , not in Map.

**Comment by lvca** [comment]
Where do you suggest to add it in the docs?

**Comment by publicocean0** [comment]
Maybe in java api section it could be add other examples with these cases showing as to use embedded map,lists with batch script/js for helping a rapid develpment and to clear better the possibilities offered. 
ciao
