### ISSUE TITLE
Lucene search does not use configured analyzer in query parser

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6510]
v 2.2.3

Default analyzer configured on Lucene index is used when indexing, but is not applied to search key. Analyzer is passed to MultiFieldQueryParser in OQueryBuilderImpl.getQueryParser(), but is not used while parsing query in queryParser.parse(key). The diffrerence is that there is no stemming etc on key

It is really hard to understand what happens in Lucene code, but this quick fix for OQueryBuilderImpl.getQueryParser() works (I use one field per index, so for me it is ok):
````
      if (fields != null && fields.length == 1) {
        queryParser = new QueryParser(fields[0], analyzer);
        queryParser.setAllowLeadingWildcard(allowLeadingWildcard);
        queryParser.setLowercaseExpandedTerms(lowercaseExpandedTerms);
        return queryParser.createBooleanQuery(fields[0], key, BooleanClause.Occur.MUST);
      } else 
       queryParser = new MultiFieldQueryParser(fields, analyzer);
```

**Comment by robfrank** [comment]
I'm sorry, but I can't include your code. I don't understand what it is supposed to solve. I appreciate your effort, but I need more details: some sample data and queries with expected result  would be better. 
The best would be a test and a PR.

**Comment by vantonov1** [comment]
`
        {
            final ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:default").open("admin", "admin");
            final OrientGraphNoTx graph = new OrientGraphNoTx(db);
            final OrientVertexType c1 = graph.createVertexType("C1");
            c1.createProperty("p1", OType.STRING);
            final ODocument metadata = new ODocument();
            metadata.field("default", "org.apache.lucene.analysis.en.EnglishAnalyzer");
            c1.createIndex("p1", "FULLTEXT", null, metadata, "LUCENE", new String[]{"p1"});
        }
        {
            final ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:default").open("admin", "admin");
            final OrientGraph graph = new OrientGraph(db);
            final OrientVertex result = graph.addVertex("class:C1");
            result.setProperty("p1", "testing");
            graph.commit();
        }
        {
            final ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:default").open("admin", "admin");
            final Iterable search = db.command(new OSQLSynchQuery<>("SELECT from C1 WHERE p1 LUCENE \"tested*\"")).execute();
            assert search != null && search.iterator().hasNext();
        }
`

You can check easily - stay in analyzer, it will not be called during queryParser.parse(key). It seems to be bug in Lucene. Problem is, that I dont have full patch - my quick fix will not work if index is created on several fields

**Comment by robfrank** [comment]
I think you made a mistake on the query. You are  for "tested\*" but you want the englishAnalyzer to be invoked. I stripped out the \*, so the query is stemmed and lucene is able to found the document that contains _testing_

` @Test
  public void rname() throws Exception {

    final ODatabaseDocumentTx db = new ODatabaseDocumentTx("memory:default").create();
    db.close();
    db.open("admin", "admin");

    final OrientGraphNoTx graph = new OrientGraphNoTx(db);
    final OrientVertexType c1 = graph.createVertexType("C1");
    c1.createProperty("p1", OType.STRING);

    final ODocument metadata = new ODocument();
    metadata.field("default", "org.apache.lucene.analysis.en.EnglishAnalyzer");
    c1.createIndex("p1", "FULLTEXT", null, metadata, "LUCENE", new String[] { "p1" });

    final OrientVertex result = graph.addVertex("class:C1");
    result.setProperty("p1", "testing");
    graph.commit();

    final Iterable search = db.command(new OSQLSynchQuery<ODocument>("SELECT from C1 WHERE p1 LUCENE \"tested\"")).execute();

    assertThat(search).hasSize(1);
  }`

**Comment by vantonov1** [comment]
So if user enters tes, I should search for tes*, but if tested - exactly for tested to find testing... Well, anyway it is about Lucene, not Orient.

Thanks!
