### ISSUE TITLE
Creating an Edge between Vertices with content.

### ISSUE THREAD

**Issue by jCalamari** [orientechnologies/orientdb#6512]
v2.1.17, Ubuntu

Is there a way to create and edge with denormalised properties from vertices using SQL?

Something like:

`create edge from 1 to (select from v) set property = $v.property`

So property from current vertex is assigned to the edge.

Thanks!

**Comment by luigidellaquila** [comment]
Hi @jCalamari 

I'm afraid this is not supported right now. I'm flagging it as an enhancement, we will take it into consideration for the roadmap.

In the meantime I suggest you to do it with a custom JS function

Thanks

Luigi
