### ISSUE TITLE
Equal query not working

### ISSUE THREAD

**Issue by vsmori** [orientechnologies/orientdb#6513]
## Expected behavior and actual behavior

select urlName from User where urlName like 'Nkj-Fm20%';
RESULT> returns one row

select * from User where urlName = 'Nkj-Fm20';
RESULT> returns no row

**Comment by lvca** [comment]
Hi, version 2.0.12 is very old. Have you already tried with v2.2.6 if works?

**Comment by vsmori** [comment]
I'm a newbie, can you please share a quick upgrade how to?

**Comment by lvca** [comment]
Look for "Upgrade" in the documentation .

**Comment by lvca** [comment]
Sure: http://orientdb.com/docs/2.2/Upgrade.html
