### ISSUE TITLE
Only one wal file is created for few databases with the storage.wal.path setting

### ISSUE THREAD

**Issue by antonzherdev** [orientechnologies/orientdb#6515]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .6[X] .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I have 3 OrientDb database and as suggested I set the storage.wal.path setting in order to store the wal file on a separate disk. It looks like after this all 3 databases started to use only one wal file. 3 wmr files have been created + OSystem.wmr.

```
[ec2-user@ip-172-31-8-182 wal]$ ls -l
total 100
-rw-rw-r-- 1 ec2-user ec2-user 65536 Aug  2 22:20 authdb.0.wal
-rw-rw-r-- 1 ec2-user ec2-user    40 Aug  2 22:20 authdb.wmr
drwxrwxr-x 2 ec2-user ec2-user  4096 Aug  2 22:03 backup
-rw-rw-r-- 1 ec2-user ec2-user    40 Aug  2 22:20 dsldb.wmr
drwx------ 2 root     root     16384 Aug  2 03:56 lost+found
-rw-rw-r-- 1 ec2-user ec2-user    40 Aug  2 22:20 OSystem.wmr
-rw-rw-r-- 1 ec2-user ec2-user    40 Aug  2 22:20 wdb.wmr
```
I would expect to have a wal file per database.

## Steps to reproduce the problem
Have few databases and set the storage.wal.path setting to a directory.

**Comment by laa** [comment]
Fixed. Will be in next 2.2 hotfix.
