### ISSUE TITLE
performance very slow and error com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token

### ISSUE THREAD

**Issue by kumarkshiva** [orientechnologies/orientdb#6516]
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
	Storage URL="plocal:C:/IntelliSURF/bin/orientdb-community-2.2.0/databases/isc"
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:268)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request

**Comment by tglman** [comment]
hi  @robfrank,

Are you running in distributed or stendalone server ?

Regards

**Comment by kumarkshiva** [comment]
Hi,
We are running as standalone.

**Comment by tglman** [comment]
Hi @kumarkshiva,

This message is due to some invalid session usually when you reboot the server, it has been fixed already in the hotfix 2.2.5, anyway we suggest to update to the last hotfix.

Regards

**Comment by tglman** [comment]
hi @kumarkshiva,

This kind of stack are printed in 2.0.0 when the server is reasterd, because the sessions are not there anymore, this is already fixed in 2.2.5, and an additional fix (also in distributed) is coming in 2.2.7, so can you upgrade to the next hotfix ?

Regards

**Comment by tglman** [comment]
hi @kumarkshiva,

Did you have chance to check the last hotfix ? is it solved for you?

**Comment by tglman** [comment]
hi,

most of this problem where fixed in  2.2.9 and 2.2.10, closing this.

Bye
