### ISSUE TITLE
OSQLMethodSubString doesnt check for field value length, throwing StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6520]
v2.2.3

Yes, String.substring() is so stupid to throw StringIndexOutOfBoundsException, but should you repeat 20-years old bugs? How can I use substring() method, if it will fail on short strings?

**Comment by luigidellaquila** [comment]
Good point :)
I'm fixing it right now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @vantonov1 

I just pushed a fix on both 2.2.x and develop. The fix will be released with 2.2.7

Thanks

Luigi
