### ISSUE TITLE
SELECT doesnt not use index for OR clause not on the main level

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6521]
v 2.2.3

SELECT ... WHERE f2=y or f3=z is OK

SELECT ... WHERE f1=x and (f2=y or f3=z) will not use index for f2 and f3 - why?

**Comment by luigidellaquila** [comment]
Hi @vantonov1 

It's a known limitation, we are working on it for next versions

Thanks

Luigi

**Comment by lvca** [comment]
@luigidellaquila is this already supported in 3.0?

**Comment by luigidellaquila** [comment]
Yes, it's already supported since v 3.0 M1

Closing, thanks

Luigi
