### ISSUE TITLE
Handle LIKE 'xyz%' as a special case and use index

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6522]
v 2.2.3

now LIKE always disables index (even for fulltext indexed fields), substring() disables index, so search for prefix (very common case) is always scanning

Could you check if LIKE is used as a startWith(), search for xyz and when scan only filtered records?

**Comment by luigidellaquila** [comment]
Hi @vantonov1 

It's not possible in general (eg. for hash indexes), but in some cases it can be done IMHO. 
I'm flagging this as an enhancement, let's see if we can manage to do it

Thanks

Luigi

**Comment by vantonov1** [comment]
IMHO it is OK to mark it as not supported in hash indexes - select another index is not a problem, but scanning is a worst case

**Comment by cegprakash** [comment]
I created my model using

```
class User(Node):
    email = String(unique=True)
    password = String()

graph.create_all(Node.registry)
client.command('CREATE INDEX emailIndex ON User(email) FULLTEXT')

```
and tried to run
`Select * from User where email LIKE "%xyz%"`
from orient studio.

I get the results regardless I create the index or not. What should I do to get the power of full text indexing?
