### ISSUE TITLE
bug rollback not found in batch (no more ,before working )

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6523]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[x ] .beta2[ ] .beta1[ ]

## Operating System
- [ x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
in batch script a old script is no more working . 
"rollback" identified is not found ???

**Comment by publicocean0** [comment]
to remove in old scripts? it is necessary to alert developers in documentation

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

This must be a bug, I'm checking it

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

I just pushed a fix on 2.2.x and develop

Thanks

Luigi
