### ISSUE TITLE
lucene index give a strange error in schema

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6524]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]
## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

i have a complex class where i have to create a lucene index. 
when programming code try to define index .... it gives
error "
Composite key cannot contain more than one collection item"

lucene permits to search in collections as you want.

**Comment by robfrank** [comment]
please, include some code, SQL snippet, any support to help.

**Comment by publicocean0** [comment]
Orient db 2.6

**Comment by publicocean0** [comment]
Create a class a with property 1 as list , property 2 as map , and other properties as you want. Now try to index at least first 2 fields

**Comment by maggiolo00** [comment]
@publicocean0 

i know lucene can index a lot of stuff, but this isn't plain lucene. We have to deal with the OrientDB Engine integration. And OrientDB does not support that kind of index, so neither the index with lucene

**Comment by publicocean0** [comment]
ok it would be better if you add this limitation in documentation for developers

**Comment by lvca** [comment]
@maggiolo00 do you think we can mark this as enhancement or documentation?

**Comment by publicocean0** [comment]
hi, for my opinion it would be important to emprove the lucene module because a nosql database as orientdb might be targetted to search unstructured data (ODocument contains unstructured data by definition). 
It general i think to emprove lucene engine for searching all data types supported by ODocument could give a more stable and coherent solution for developers. Lucene api permits to do it with few rows of code. So it is very fast to do.  There is just a problem that i saw for doing it but probably it not so difficult to change . Lucene engine use  very abstract and general ADT as  keys container: a multimap. Orientdb instead use a List not properly adapt to support all data types.
