### ISSUE TITLE
Problem. High CPU usage after connection re-acquired after automatic backups

### ISSUE THREAD

**Issue by mikayeln** [orientechnologies/orientdb#6526]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .19[x] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

We have a large mutithreaded java ee application running on Wildfly 8. We are using Orient 2.1.19.
After couple of automatic backups our log files contain a lot of messages like following.

   11:07:57,739 WARNING [com.orientechnologies.orient.client.remote.OStorageRemote] (default task-104) Caught I/O errors from Not connected (local socket=?), trying to reconnect (error: java.io.EOFException)
    11:07:57,747 WARNING [com.orientechnologies.orient.client.remote.OStorageRemote] (default task-104) Connection re-acquired transparently after 6ms and 1 retries to server '127.0.0.1:2424/vis_demo': no errors will be thrown at application level

Also CPU usage is very high and all threads named "OrientDB <- Asynch Client (/127.0.0.1:2424)" recreated. At some point  we can see (usinf VisualVM) hundreds of such threads.

**Comment by mikayeln** [comment]
Investigations show that setting db.setProperty(ORemoteConnectionManager.PARAM_MAX_POOL, 1000); affects the situation. Warnings appear after much more backups.

**Comment by mikayeln** [comment]
Any ideas?

**Comment by mikayeln** [comment]
Any updates?

**Comment by lvca** [comment]
It could be a problem we already resolve in v2.2.x. Are you scheduling an upgrade?

**Comment by tglman** [comment]
hi @mikayeln,

we fixed a few issue recently on disconnection, some of this disconnections where triggerred by distributed configuration update, that is triggered also in case of backup, so this case should definitly fixed in 2.2.10.

Let me know if i can close this.

**Comment by lvca** [comment]
hi @mikayeln, any news on this?

**Comment by mikayeln** [comment]
hi @lvca, @tglman.

We've just swithched to 2.2.10. I'll monitor the situaion and let you know.

Thanks.

**Comment by tglman** [comment]
hi @mikayeln,

Any news on this issue ?

Bye

**Comment by tglman** [comment]
This should be fixed,

I'm closing, reopen if you still have problems.
