### ISSUE TITLE
2.2.6 Default password with * can't blank or assign with out first character

### ISSUE THREAD

**Issue by apaichon** [orientechnologies/orientdb#6529]
## OrientDB Version, operating system, or hardware.
- v2.2.6 community

## Operating System
- [* ] Linux
- [*] MacOSX

## Expected behavior and actual behavior
Should to set blank password or assign by ourself.

![image](https://cloud.githubusercontent.com/assets/3946685/17435003/0960e698-5b38-11e6-9340-e59b74294f82.png)

## Steps to reproduce the problem
I just start orientdb but it start with * can't set blank same as v.2.1.5 that I've used.
I try setup 2 times.
 1. default with * but can't access to GracefulDeadConcert with user : admin , password: admin
 2. set password but can't access to.
I try to create new database and use password from configuration it doesn't work.
  <user resources="*" password="{PBKDF2WithHmacSHA1}36D4824A8D49C7C224DF45A4CA6E17F9BF93E4610C96D6ED:9CC42E794AE1D0DAF712EBF651C3966B94FC07CB7294FEB7:65536" name="root"/>
      
Please help

**Comment by robfrank** [comment]
which java version are you using to start orientDB?

**Comment by apaichon** [comment]
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

**Comment by robfrank** [comment]
the _problem_ is related to he fact that on Java7 the `PBKDF2WithHmacSHA256` has algorithm is not supported, please refer to doc:

http://orientdb.com/docs/2.2.x/Release-2.2.0.html

since Java7 is EOL, my suggestion is to run OrientDB with Java8. Note that the official Docker image of OrientDb is built using openJDK 8.
