### ISSUE TITLE
Provide lifecycle hooks for clients for server shutdown/reconnects

### ISSUE THREAD

**Issue by torfranz** [orientechnologies/orientdb#6531]
## OrientDB Version, operating system, or hardware.
- v2.2.3
## Operating System
- [X ] Windows
## Expected behavior and actual behavior

In my client application I have live queries running. 

In case the remote server goes down there seems to be no way to get informed about it. My client would in such a case sit there waiting for live query changes but none will ever arrive after the server is up again. 

It would be great to have a chance in the client code to get informed about shutdowns and reconnects of the server in order to react accordingly (e.g. recreate live queries)

See also related #6324

**Comment by tglman** [comment]
hi @torfranz,

I commented the other issue, let me know if that is ok.

**Comment by torfranz** [comment]
Hi @tglman,
I closed the other issue, but would like to keep this open as I would assume it still makes a lot of sense to have lifecycle hooks for server shutdowns/reconnects. The live query is only an example for what these might be used. Although for live queries I now know when the server dies, I still would miss the moment when the server reconnects to restart stopped live queries.
