### ISSUE TITLE
NUMERIC index bug for long type

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6534]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[x ] .beta2[ ] .beta1[ ]
## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

<pre>
select from ( select expand(rid) from index:A.lucene where key LUCENE ' sequence:[22 TO *] '  limit 11 )
ref | sequence | 
#4:22 | 10 
#4:22 | 11 
#4:22 | 12 
</pre>

**Comment by publicocean0** [comment]
select from r

+----+-----+------+----+----+
|#   |@RID |@CLASS|b   |a   |
+----+-----+------+----+----+
|0   |#60:0|r     |100 |    |
|1   |#60:1|r     |10  |    |
|2   |#60:2|r     |    |10  |
+----+-----+------+----+----+

3 item(s) found. Query executed in 0.002 sec(s).
 select from r where [a,b] lucene "a:>3"


0 item(s) found. Query executed in 0.004 sec(s).
 select from r where [a,b] lucene "a:[3 TO *]"
0 item(s) found. Query executed in 0.004 sec(s).

**Comment by publicocean0** [comment]
a is integer, b is long 
no one is working

**Comment by robfrank** [comment]
Why don't use SQL instead of lucene indexes?

**Comment by publicocean0** [comment]
because my class has a billion of rows

**Comment by maggiolo00** [comment]
@publicocean0 

long/integer type are not supported . That means that if you run range query with lucene syntax it will not work since there is not logic in the integration between OrientDB and Lucene to handle range query.

**Comment by publicocean0** [comment]
it is better to write in documentation this important limitation. In orientdb 3.0 will be available?

**Comment by maggiolo00** [comment]
@publicocean0  we can mark this as enhancement. 

It shouldn't be hard to support it

**Comment by publicocean0** [comment]
surely it requires  10 minutes

2016-08-10 12:27 GMT+02:00 Enrico Risa <notifications@github.com>:

**Comment by robfrank** [comment]
We support range queries over numeric fields and date/datetime fields starting from version 2.2.14. 
It didn't take us only 10 minutes to develop the support for ranges. Documentation will be updated shortly: http://orientdb.com/docs/2.2.x/Full-Text-Index.html
