### ISSUE TITLE
Prepared statement with named parameter at EXPAND function not returning the expected results

### ISSUE THREAD

**Issue by C-PS** [orientechnologies/orientdb#6535]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[x] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I am using OrientDB 2.2.6 (plocal)
I tried to execute a statement like 'SELECT EXPAND(out("Test_EClass")[Field1 = :param]) FROM Test_VClass'
where:
 - Test_VClass is a class extending 'V'
 - Test_EClass is a class extending 'E'
 - Field1 is a field of the target Vertex of the 'Test_EClass' 

But no data were returned even though there should be some data returned by the query.
I tried to execute the same statement by replacing the named parameter with an actual value and the correct results were returned by the query.

## Steps to reproduce the problem
Execute the following java code:

    Map<String, String> params = new HashMap<>();
    params.put("param", "some_value");
    String selectQuery = "SELECT EXPAND(out(\"Test_EClass\")[Field1 = :param]) FROM Test_VClass";
    Iterable<Vertex> results = connection.command(new OSQLSynchQuery<>(selectQuery)).execute(params);

**Comment by luigidellaquila** [comment]
Hi @C-PS 

it seems to be a bug, I'll check it asap and let you know

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @C-PS 

I have this test case, and it passes correctly:

```
  @Test public void testExpandParam() {
    OSchemaProxy schema = database.getMetadata().getSchema();
    OClass v = schema.getClass("V");
    OClass e = schema.getClass("E");
    final OClass clsv = schema.createClass("testExpandParam_V", v);
    final OClass clse = schema.createClass("testExpandParam_E", e);
    database.command(new OCommandSQL("CREATE VERTEX testExpandParam_V set name = \"foo\"")).execute();
    database.command(new OCommandSQL("CREATE VERTEX testExpandParam_V set name = \"bar\"")).execute();
    database.command(new OCommandSQL(
        "CREATE EDGE testExpandParam_E from (select from testExpandParam_V  where name = \"foo\") to (select from testExpandParam_V  where name = \"bar\")"))
        .execute();

    List<OIdentifiable> result = database
        .query(new OSQLSynchQuery<OIdentifiable>("select expand(out('testExpandParam_E')[name = 'bar']) from testExpandParam_V"));
    Assert.assertEquals(result.size(), 1);
    Assert.assertEquals(((ODocument) result.get(0).getRecord()).field("name"), "bar");
    Map<String, String> params = new HashMap<String, String>();
    params.put("param", "bar");
    result = database
        .command(new OSQLSynchQuery<OIdentifiable>("select expand(out('testExpandParam_E')[name = :param]) from testExpandParam_V")).execute(params);
    Assert.assertEquals(result.size(), 1);
    Assert.assertEquals(((ODocument) result.get(0).getRecord()).field("name"), "bar");
  }
```

Are you sure you have strictSql=true in your db?
http://orientdb.com/docs/2.1/Release-2.1.0.html#strict-sql-parser

Thanks

Luigi

**Comment by C-PS** [comment]
Hi Luigi,
Thanks for the quick reply.
You are right. The 'strictSql' was not enabled. Once I enabled it the query was executed correctly.
