### ISSUE TITLE
restore database gives error UnsupportedOperationException

### ISSUE THREAD

**Issue by MustafaAdam** [orientechnologies/orientdb#6536]
I'm following this less than precise tutorial[ Data Mining The City](http://datamining.city/2015/09/16/loading-the-dmc-databases/)

1. I've create the database from the studio and it shows in my databases folder as "soufun_db".
2. I downloaded the soufun.zip file into the directory "db" that I created in the orientdb folder 
3. Then I connect to the"soufun_db" database from the console
`      CONNECT remote:localhost/soufun_db admin admin
`
6. Then I run my restore database command
`     "RESTORE DATABASE /home/mustafa/Desktop/orientdb-community-2.1.0/db/soufun.zip
`
8. Output is:
```
     "Restoring database database /home/.../soufun.zip
       Error: java.lang.UnsupportedOperationException: restore"
```

**Comment by maggiolo00** [comment]
hi @MustafaAdam 

remote restore is not supported  you should use 

plocal connection
