### ISSUE TITLE
Case Sensitivity in Console Batch Commands

### ISSUE THREAD

**Issue by DevolvingSpud** [orientechnologies/orientdb#6538]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ] 2.26 [X]
## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

Documentation indicates that items in console commands are case insensitive; this is not the case.

Example: 
CONNECT remote:localhost root root; <-- This works
CONNECT REMOTE:localhost root root; <-- This does not

Likewise

CREATE DATABASE remote:localhost/databases/person-test root root plocal; <-- This works
CREATE DATABASE remote:localhost/databases/person-test root root PLOCAL; <-- This does not

See http://orientdb.com/docs/master/Console-Command-Create-Database.html for incorrect documentation.
## Steps to reproduce the problem

Using bare orientdb docker instance for 2.2.6, running

./console.sh /tmp/create_names_table.txt

where create_names_table.txt is:
SET echo TRUE;

CONNECT REMOTE:localhost root root;

CREATE DATABASE REMOTE:localhost/databases/person-test root root PLOCAL;

CREATE CLASS Person EXTENDS V;

CREATE PROPERTY Person.guid STRING;
CREATE PROPERTY Person.firstName STRING;
CREATE PROPERTY Person.middleInitial STRING;
CREATE PROPERTY Person.lastName STRING;
CREATE PROPERTY Person.gender STRING;
CREATE PROPERTY Person.birthday DATE;
CREATE PROPERTY Person.country STRING;

**Comment by lvca** [comment]
In console commands are case insensitive, but not their arguments. Which part of the docs are confusing?

**Comment by DevolvingSpud** [comment]
The part that shows all the options in uppercase, like:

<mode> Defines the mode you want to use in connecting to the database. It can be PLOCAL or REMOTE.
<path> Defines the path to the database.

**Comment by lvca** [comment]
Updated the documentation. Thanks.
