### ISSUE TITLE
[Question] Retrieve score in a query using a Lucene Index

### ISSUE THREAD

**Issue by estefaniaotero** [orientechnologies/orientdb#6539]
## OrientDB Version, operating system, or hardware.
- v2.2.6

## Operating System
- [x] Linux
- [x] Windows

I'm just starting with OrientDB, doing some testing, my question:

Is there any possibility to display the Lucene score for each result node doing a query? I do an "explain" of the select query, and I can see an score (don't know if it is a Lucene score or not), but it belongs to the last node of the query (current column).

![image](https://cloud.githubusercontent.com/assets/5947847/17516170/27ec4136-5e3d-11e6-8a9e-151c93f27bed.png)

It would we great to display the Lucene score, similarity value with the query terms it's important in some cases.

**Comment by maggiolo00** [comment]
hi @estefaniaotero 

try 

```
select *, $score ...
```

**Comment by maggiolo00** [comment]
@estefaniaotero 

did you try?

**Comment by estefaniaotero** [comment]
I tried, and it worked! thanks!

Documentation doesn't explain this kind of things (at least I didn't find it).
Thank you for the answer.

**Comment by lvca** [comment]
@maggiolo00 could you please update the documentation?

**Comment by lvca** [comment]
Thanks
