### ISSUE TITLE
Orient 2.1.12: changing log level just for Orient libraries.

### ISSUE THREAD

**Issue by jCalamari** [orientechnologies/orientdb#6546]
Hi folks,

I would like to change log level in tests just for OrientDB classes from `INFO` to `WARN`.
According to http://orientdb.com/docs/2.1/Logging.html changing log level can be achieved by setting this system property:

`-Dlog.console.level=WARNING"`

This changes log level for all libraries using java logging. Is there a way just to change OrientDB logging?

**Comment by lvca** [comment]
Sure, change the .properties file by replacing INFo with WARNING: http://orientdb.com/docs/last/Logging.html#configuration-file
