### ISSUE TITLE
Out of direct memory

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6549]
v2.2.6
Linux
Back traces
This happens despite the fact that we have over 4GB allocated to direct memory in Java startup params

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|                                                                                   Name                                                                                   |   Count    |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|  +---java.nio.Bits.reserveMemory(long, int) Bits.java:693                                                                                                                |  1  100 %  |
|    |                                                                                                                                                                     |            |
|    +---java.nio.ByteBuffer.allocateDirect(int) ByteBuffer.java:311                                                                                                       |            |
|      |                                                                                                                                                                   |            |
|      +---com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool$BufferHolder) OByteBufferPool.java:309                                 |            |
|        |                                                                                                                                                                 |            |
|        +---com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(boolean) OByteBufferPool.java:260                                                     |            |
|          |                                                                                                                                                               |            |
|          +---com.orientechnologies.orient.core.storage.cache.local.OWOWCache.cacheFileContent(int, long, int, boolean, OModifiableBoolean) OWOWCache.java:1253           |            |
|            |                                                                                                                                                             |            |
|            +---com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(long, long, int, boolean, OModifiableBoolean) OWOWCache.java:658                     |            |
|              |                                                                                                                                                           |            |
|              +---com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.restoreQueueWithPageLoad(OWriteCache, LRUList, DataInputStream) O2QCache.java:803   |            |
|                |                                                                                                                                                         |            |
|                +---com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.restoreQueue(OWriteCache, LRUList, DataInputStream, boolean) O2QCache.java:708    |            |
|                  |                                                                                                                                                       |            |
|                  +---com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(OWriteCache) O2QCache.java:672                                   |            |
|                    |                                                                                                                                                     |            |
|                    +---com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(String, String, Map) OAbstractPaginatedStorage.java:232       |            |
|                      |                                                                                                                                                   |            |
|                      +---com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(String, String) ODatabaseDocumentTx.java:251                             |            |
|                        |                                                                                                                                                 |            |
|                        +---com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate() OrientBaseGraph.java:1904                                                |            |
|                          |                                                                                                                                               |            |
|                          +---com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(String, String, String) OrientBaseGraph.java:161                               |            |
|                            |                                                                                                                                             |            |
|                            +---com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(String, String, String, boolean) OrientTransactionalGraph.java:103  |            |
|                              |                                                                                                                                           |            |
|                              +---com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(String, String, String) OrientTransactionalGraph.java:99          |            |
|                                |                                                                                                                                         |            |
|                                +---com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(String) OrientGraph.java:76                                                  |            |
|                                  |                                                                                                                                       |            |
|                                  +---com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.mergeSameItems(String) BluePrintDatabaseUtil.java:113                |            |
|                                    |                                                                                                                                     |            |
|                                    +---com.stimulus.archiva.database.blueprints.BluePrintDatabase.connect() BluePrintDatabase.java:84                                    |            |
|                                      |                                                                                                                                   |            |
|                                      +---com.stimulus.archiva.database.DatabaseService.startup() DatabaseService.java:307                                                |            |
|                                        |                                                                                                                                 |            |
|                                        +---com.stimulus.archiva.domain.Services$ServiceStartup.run() Services.java:169                                                   |            |
|                                          |                                                                                                                               |            |
|                                          +---java.lang.Thread.run() Thread.java:745                                                                                      |            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+

Generated by YourKit Java Profiler 2014 build 14124 August 11, 2016 04:41:16 PM

**Comment by laa** [comment]
Hi @jamieb22 it starts me to think that you did not set direct memory settings accordingly and all issues on your side caused by this. Did  you set -XX:MaxDirectMemory parameter http://andreylomakin.blogspot.com/2016/05/do-not-forget-to-set-xxmaxdirectmemory.html as we suggested to 512 GB ? .

**Comment by laa** [comment]
It does not mean that DB will consume all 512 GB , actuall amount of consumed memory depends on disk cache size.

**Comment by jamieb22** [comment]
I am running Orient on a machine with 32GB of RAM available. 6192GB is allocated to Java heap, Permgen should be around 256MB, the rest is available for direct memory allocation. We are running:

root@mailarchiva-usa-f:/opt/mailarchiva/jre64/bin# ./java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

I've tried various combinations of adding and removing -XX:MaxDirectMemorySize=512G and -Dstorage.diskCache.bufferSize=512 to/from Java startup parameters and it makes no difference. Orient always is running out of virtual memory no matter what we do.

**Comment by BruceMu** [comment]
I also encountered this problem. After read the code,i find if write is too fast, the speed of page release is far behind.  If we set 2GB direct memory,it is allocated when the db's first page created; But if the 2GB memory is exhausted,and page release is too slow,there is no page can be reused to write, it will try to apply another 2GB direct memory, and this always cause exception;
`
          if (bfh.index < bufferIndex) {
            //we have to request page only from buffer with calculated index otherwise we may use memory already allocated
            //to other page

            final int requestedPages = bfh.requested.get();
            //wait till all pending memory requests which use this buffer will be fulfilled
            if (requestedPages < maxPagesPerSingleArea) {
              try {
                bfh.filled.await();
              } catch (InterruptedException e) {
                throw OException
                    .wrapException(new OInterruptedException("Wait of new preallocated memory area was interrupted"), e);
              }
            }

            final BufferHolder nbfh = new BufferHolder(bufferIndex);
            if (lastPreallocatedArea.compareAndSet(bfh, nbfh)) {
              bfh = nbfh;
              allocateBuffer(bfh); // here !!!!
            } else {
              assert nbfh.index == bufferIndex;
              continue;
            }
          }`

**Comment by laa** [comment]
Hi @BruceMu which exception do  you mean ? Did you try to set  -XX:MaxDirectMemory to 512 GB ? What is your disk cache size what is your RAM size ?

**Comment by laa** [comment]
@jamieb22 could you do following. Could you:

1. Set  -XX:MaxDirectMemorySize to 512g
2. Connect to JMX on the server side.
3. Open com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean bean.
4. Send us value of property allocatedMemoryInGB.

**Comment by laa** [comment]
@BruceMu if you do the same I will really appreciate.

**Comment by jamieb22** [comment]
I think the server is stabilized by setting the following start up options:
-Dstorage.diskCache.bufferSize=32 and -XX:MaxDirectMemorySize=512g. 
It doesn't seem to be running out of virtual memory any longer, though its only been running for 12 hours or so. The result of your MBean test is shown below. If I've set a maximum disk cache size of 32MB, how can it be that there is a total of 192MB of direct memory allocated? Presumably, you have other components allocating direct memory?
OverflowBufferCount = 0;
AllocatedMemoryInGB = 0.19;
AllocatedMemoryInMB = 192;
AllocatedMemory = 201326592;
BuffersInThePool = 2127;
AllocatedBufferCount = 2561;
BufferSize = 65536;

**Comment by jamieb22** [comment]
Sorry, I just seen your instruction not to change disk size cache. Unfortunately, this value was set before you had sent the email. I should be able to try out the setting over the weekend, as this is a production server.

**Comment by jamieb22** [comment]
Ok. I decided to just go ahead and restart without -Dstorage.diskCache.bufferSize=32 option. 
Immediately, after starting the server, I see:

#mbean = com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean:
AllocatedBufferCount = 55707;
OverflowBufferCount = 0;
BuffersInThePool = 2;
AllocatedMemoryInMB = 4096;
AllocatedMemoryInGB = 4.0;
BufferSize = 65536;
AllocatedMemory = 4294967296;

4G is a huge cache. Don't you think that your base Orient install should be set to use less? I'll keep an eye on the direct mem allocation through out the day.

**Comment by laa** [comment]
Hi, it seems like all your database was put in memory to increase the speed of query processing. As we discussed you always may limit disk cache size by setting of the system property ```storage.diskCache.bufferSize```  in megabytes.

**Comment by jamieb22** [comment]
Andrey...we are going to modify our source code as below. setFlag() method will be called on startup. If we don't set our own variable, the default value applied will be 64. Is this ok?

	private void setFlag() {
		String cacheSize = System.getProperty("graphdb.cache.size");
		if (cacheSize!=null && !cacheSize.isEmpty())
			System.setProperty("storage.diskCache.bufferSize", cacheSize);
		else
			System.setProperty("storage.diskCache.bufferSize", "64");
	}

**Comment by laa** [comment]
Please note that access time of single page from SSD is 10 ms and from HDD 50 ms. So the time of write for single vertex will be about 20 ms at best on SSD or 50 op/s. In general, I do suggest to keep at list 20% of the database in disk cache or even more.  But if the speed of 50 op/s is good enough for you , you use small disk cache size.

**Comment by laa** [comment]
Closed according to feedback.

**Comment by jamieb22** [comment]
Andrey I suggest to reopen this case. I am still seeing OME on several despite having -XX:MaxDirectMemory=512 GB. One server has 32GB of RAM. I have 6GB allocated to heap, and still OME. 

Back traces

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|                                                                                                                 Name                                                                                                                  |   Count    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|  +---java.util.HashMap.resize() HashMap.java:703                                                                                                                                                                                      |  1  100 %  |
|    |                                                                                                                                                                                                                                  |            |
|    +---java.util.HashSet.add(Object) HashSet.java:219                                                                                                                                                                                 |            |
|      |                                                                                                                                                                                                                                |            |
|      +---com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.deserializeFromByteBufferObject(ByteBuffer, OWALChanges, int) OStreamSerializerSBTreeIndexRIDContainer.java:274   |            |
|        |                                                                                                                                                                                                                              |            |
|        +---com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.deserializeFromByteBufferObject(ByteBuffer, OWALChanges, int) OStreamSerializerSBTreeIndexRIDContainer.java:43  |            |
|          |                                                                                                                                                                                                                            |            |
|          +---com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(OBinarySerializer, int) ODurablePage.java:167                                                               |            |
|            |                                                                                                                                                                                                                          |            |
|            +---com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket.getEntry(int) OHashIndexBucket.java:141                                                                                                       |            |
|              |                                                                                                                                                                                                                        |            |
|              +---com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket.find(Object, long) OHashIndexBucket.java:93                                                                                                 |            |
|                |                                                                                                                                                                                                                      |            |
|                +---com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable20.get(Object) OLocalHashTable20.java:364                                                                                                   |            |
|                  |                                                                                                                                                                                                                    |            |
|                  +---com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.get(Object) OHashTableIndexEngine.java:145                                                                                                  |            |
|                    |                                                                                                                                                                                                                  |            |
|                    +---com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(int, Object) OAbstractPaginatedStorage.java:1913                                                                |            |
|                      |                                                                                                                                                                                                                |            |
|                      +---com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(int, Object) OAbstractPaginatedStorage.java:1895                                                                |            |
|                        |                                                                                                                                                                                                              |            |
|                        +---com.orientechnologies.orient.core.index.OIndexMultiValues.put(Object, OIdentifiable) OIndexMultiValues.java:139                                                                                            |            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+

Generated by YourKit Java Profiler 2014 build 14114 16 Aug 2016 2:18:32 PM

**Comment by laa** [comment]
@jamieb22 from your stack trace there is no signs of the presence of direct memory manipulation methods. Do you mean OOM as OutOfMemoryException of java heap ?

**Comment by laa** [comment]
Could you provide heap dump of this OOM ?

**Comment by jamieb22** [comment]
<img width="1368" alt="screen shot 2016-08-16 at 2 23 58 pm" src="https://cloud.githubusercontent.com/assets/6212848/17698702/dafa4a6e-63bc-11e6-891a-7ded092980c6.png">

**Comment by laa** [comment]
@jamieb22 it seems like the same issue as you already posted https://github.com/orientechnologies/orientdb/issues/6547 I will provide API soon. If you have heap dump will be cool to analyse it too.

**Comment by jamieb22** [comment]
I can't find the heap dump. How is OME the same issue as negative cluster one?

**Comment by jamieb22** [comment]
I wish you guys could see what chaos these upgrade issues are causing. Data being be lost. It is a total nightmare.
