### ISSUE TITLE
illegal monitor state

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6550]
## OrientDB Version, operating system, or hardware.
v2.2.6
Linux
Back traces
IllegalMonitorState Exception Orient DB
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|                                                                                  Name                                                                                   |   Count    |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|  +---java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryReleaseShared(int) ReentrantReadWriteLock.java:428                                                       |  4  100 %  |
|    |                                                                                                                                                                    |            |
|    +---java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock() ReentrantReadWriteLock.java:881                                                              |            |
|      |                                                                                                                                                                  |            |
|      +---com.orientechnologies.orient.core.storage.cache.OCachePointer.releaseSharedLock() OCachePointer.java:238                                                       |            |
|        |                                                                                                                                                                |            |
|        +---com.orientechnologies.orient.core.storage.cache.OCacheEntry.releaseSharedLock() OCacheEntry.java:89                                                          |            |
|          |                                                                                                                                                              |            |
|          +---com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.firstKey() OSBTreeBonsaiLocal.java:920                                       |            |
|            |                                                                                                                                                            |            |
|            +---com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.init() OSBTreeRidBag.java:501                             |            |
|              |                                                                                                                                                          |            |
|              +---com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.<init>(OSBTreeRidBag, int) OSBTreeRidBag.java:435       |            |
|                |                                                                                                                                                        |            |
|                +---com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.rawIterator() OSBTreeRidBag.java:558                                         |            |
|                  |                                                                                                                                                      |            |
|                  +---com.orientechnologies.orient.core.db.record.ridbag.ORidBag.rawIterator() ORidBag.java:161                                                          |            |
|                    |                                                                                                                                                    |            |
|                    +---com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex, Direction, String[]) OrientVertex.java:854                             |            |
|                      |                                                                                                                                                  |            |
|                      +---com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(Direction, String[]) OrientVertex.java:782                                         |            |
|                        |                                                                                                                                                |            |
|                        +---com.tinkerpop.blueprints.util.DefaultVertexQuery$DefaultVertexQueryIterable.<init>(DefaultVertexQuery, boolean) DefaultVertexQuery.java:110  |            |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+

Generated by YourKit Java Profiler 2014 build 14124 August 11, 2016 04:53:09 PM

**Comment by laa** [comment]
Closed according to feedback.
