### ISSUE TITLE
Unable to shutdown windows service

### ISSUE THREAD

**Issue by sitty** [orientechnologies/orientdb#6552]
## OrientDB Version, operating system, or hardware.

OrientDB Community 2.2.6
## Operating System

Windows 7

I installed OrientDB as a windows service based on the [instructions](http://orientdb.com/docs/last/Windows-Service.html). I can start the service fine but I'm unable to stop the service from windows services console or the prunmgr console. When I try to stop the service I see the following in the orient-server.log.
2016-08-11 11:28:13:815 INFO  Received shutdown command from the remote client /127.0.0.1:55730 [ONetworkProtocolBinary]
2016-08-11 11:28:13:830 SEVER Authentication error of remote client /127.0.0.1:55730: shutdown is aborted. [ONetworkProtocolBinary]

I'm able to shutdown the process by running the shutdown.bat.

**Comment by sagarmaniar** [comment]
@robfrank @lvca  any update on the issue..? thanks!

**Comment by robfrank** [comment]
When you run the shutdown.bat manually, do you provide the OrientDB server's password?
I don't have a windows box/VM where to test, but configuring the shutdown of service proving the password can be a solution

**Comment by sitty** [comment]
Yes when I use shutdown.bat I use -p password param. I tried passing the same argument for shutdown in the service but it doesnt seem to be working.

**Comment by sagarmaniar** [comment]
@robfrank @lvca should this be marked as bug? Any resolution to this?

**Comment by marek-stoj** [comment]
Per the Apache Commons Deamon documentation (https://commons.apache.org/proper/commons-daemon/procrun.html) you can use the StopParams argument when installing the service. Something along these lines worked for me:

`OrientDBGraph.exe //IS ... --StopClass=com.orientechnologies.orient.server.OServerShutdownMain --StopParams=-p ++StopParams=password ...`

**Comment by likemusic** [comment]
Pull request to fix this issue - https://github.com/orientechnologies/orientdb-docs/pull/304
