### ISSUE TITLE
high number of CPUs triggers multi-gigabyte memory usage by OLockManager

### ISSUE THREAD

**Issue by zerovian** [orientechnologies/orientdb#6553]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .17[X] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [X ] Other, name? 
IBM AIX, Solaris

## Expected behavior and actual behavior

When creating a database with a very high number of CPUs (Solaris T5, 1024 cores) OrientDB consumes almost 2GB of memory to create a database.

The algorithm to size the hash tables baed on the concurrency level configured through OGlobalConfiguration breaks when there are a large number of CPUs.  Due to how the algorithm allocates the array OReadersWritesSpinLock combined with how OThreadCountersHashTable allocates hash table sizes based; the hash tables get sized absolutely massively and chew up gigabytes of memory for a simple database creation.

This ends up with a concurrency level in ONewLockManager of 1024 cores...which ends up sizing the ReaderswritersSpinLock array in this class to 16384.  This chews up about 1.8 GB of memory which is absurd.

Algorithms need to be capped to something a bit more reasonable.  There's no way a single database should ever default to needing 2GB just to create a database.

Perhaps set a max value on the concurrency level to something more reasonable like 16.

## Steps to reproduce the problem

Either find a machine with 1024 cores and create a database (nothing special, just new empty database), or set -Denvinronment.concurrency.level=1024 to simulate this.

See screenshot dump from AIX box with 1024 cores where the memory consumed simply for house keeping of locks consumes massive amounts of memory.

**Comment by laa** [comment]
@zerovian sorry which version do you use OThreadCountersHashTable is not used in latest releases ?

**Comment by zerovian** [comment]
This is from 2.1.17 which is fairly recent. I haven't checked 2.2 stream since we're not on that version yet.

**Comment by zerovian** [comment]
Also affects 2.0.7 (customer ran into it).

**Comment by zerovian** [comment]
Also, there's a typo in oglobal configuration

property name is incorrectly spelled:

envinronment.concurrency.level

**Comment by laa** [comment]
Hi @zerovian I introduced new parameter ```environment.lockManager.concurrency.level``` could you set it to 2048 and check results ?

**Comment by zerovian** [comment]
What branch?

**Comment by laa** [comment]
@zerovian 2.2.x

**Comment by zerovian** [comment]
I grabbed August 22 build from here:
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.8-SNAPSHOT/
orientdb-community-2.2.8-20160822.152237-18.zip	Mon Aug 22 15:22:49 UTC 2016	38986615	


Both with and without that system argument.  This is embedded so I don't really want to allocate 16Gb of RAM to the database server.

Things started fine on my desktop.  I don't have an actual 1024 core machine to test this.

Aug 22, 2016 3:20:53 PM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=16272m option when you start the JVM.
Aug 22, 2016 3:20:53 PM com.orientechnologies.common.log.OLogManager log
WARNING: The configured memory chunk size (2147483647 bytes) is larger than the configured maximum cache size (402653184 bytes). That may cause overallocation of a memory which will be wasted, please tune the configuration up. Use the storage.diskCache.bufferSize OrientDB option to raise the cache memory size or memory.chunk.size OrientDB option to lower memory chunk size.
Aug 22, 2016 3:20:53 PM com.orientechnologies.common.log.OLogManager log
INFO: Lowering memory chunk size from 2,147,483,647B to 402,653,184B.

**Comment by laa** [comment]
@zerovian I think that is build do not contain latest changes we need a couple of days to propagate them. 
It is quite simple to make I build from source code just run ```mvn clean package -DskipTests```

**Comment by laa** [comment]
@zerovian so we should wait on test on 1024 machine or I can close the issue ?

**Comment by zerovian** [comment]
Leave this open for now.  I'm trying to see if we can get the customer to test it.

**Comment by laa** [comment]
Half of the month passed ))  I will close issue please reopen it if it will be reproduced.

**Comment by zerovian** [comment]
sorry for delay. customer took a while to get back to us before confirming they are willing to test with updated version.  will reopen if they run into problems with current branch.
