### ISSUE TITLE
strategy advice requested: one huge database, or multiple smaller dbases

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6554]
## OrientDB Version, operating system, or hardware.
- v2.2.5
## Operating System
- Linux (Ubuntu)
## Expected behavior and actual behavior

Some category of our data gets loaded nearly continuously into one class.
From this 'input' class, different selections and transformations are run to obtain new subsets of the data original, which is then stored in other classes.
The total of our data will grow to 10, 15 or maybe 20 TB

-> is it advised to split this data into different databases (eg the original data in one dbase, the selected subsets in other databases), and -if so- can a query be run to retrieve records from a class in one database and store the resulting records into a class in another database (like traditional database 'links') ?

-> or is it advised to store ALL the data in one huge, single database ?

**Comment by smolinari** [comment]
If you are going to be querying the data, you'll want it all in one database. AFAIK, there is no way to query across ODB databases. 

If you are worried about mixing up data between, say, your clients, you should think about partitioning through the [permissions system](http://orientdb.com/docs/2.1/Database-Security.html).

[This article is rather old](http://orientdb.com/docs/2.1/Partitioned-Graphs.html), but it also gives you sort of an idea what can be done using permissions to partition data in an ODB database. 

Scott
