### ISSUE TITLE
OSystem database is always created on disk, even if default db type is "memory"

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6555]
v 2.2.3

I use "memory" type for tests, but with v2.2 it creates databases folder right in the src, looks ugly

**Comment by SDIPro** [comment]
Hi @vantonov1,

The OSystem database is used internally for many things.  I'm not quite sure what you mean by "right in the src".  We may soon provide a configuration option to specify where its stored, if that would be helpful.  But we really can't remove the OSystem database.

**Comment by vantonov1** [comment]
Hi!

I have unit tests, working with memory:default database. I'm not asking to get ride of OSystem, but now it is created as plocal:OSystem, not memory:OSystem.

Configuring where it is stored is great, but it would be enough just to copy options from the default db
