### ISSUE TITLE
Upgrade Policy Proposal

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6556]
Andrey asked me to propose an Orient DB Upgrade Policy. Below is for comment. In the past, we have found Orient DB upgrades to be problematic. Backwards compatibility is often broken and often information goes missing between upgrades. At the forefront of this upgrade policy is to ensure the sanctity of data and ease of transition from between versions.

**Orient DB Upgrade Policy**

A version number must be assigned to all discreet data and index structures. 
The version numbers associated with data and indexes must always be accessible via an API. 

Major Version Changes 

Data and index binary format changes may occur in major updates (e.g. v4 -> v5).
Any major version update must have an automatic upgrade API call available that will upgrade the database from any prior major release
A startup option must be available to start Orient DB such that it will automatically detect the version of database and upgrade it from any previous major release.
API changes between major releases do not need to be backwards and forwards compatible.
The build process must run automated tests to verify that data and indexes from prior major versions can be upgraded and used successfully 

Minor Version Changes

Data and index binary format changes may not occur in minor updates (e.g. v4.1 -> v4.2)
Any minor release must be able to read data and indexes of any other minor release of same version (e.g. v4.2 -> v4.1 or v4.1 -> v4.2) without any conversion procedure
API changes between minor releases must be backwards compatible.
The build process must run automated tests to verify that new minor release can read data and indexes from a prior minor release, and vice versa.

Revision Changes

Data and index binary format changes may not occur in revision releases (e.g. 4.1.1 -> v4.1.2)
Any revision must be able to read data and indexes of any other revision of same minor and major version (e.g. 4.1.2 -> 4.1.1 and 4.1.1 -> 4.1.2) without any conversion procedure
API changes between revision changes must be backwards and forwards compatible.
The build process must run automated tests to verify that new revision release can read data and indexes from a prior revision release, and vice versa.

**Comment by jamieb22** [comment]
I would also add that software and hardware requirements should not change between minor and revision changes, only major version updates.

**Comment by smolinari** [comment]
I'd like to suggest that there also be the possibility for allowing for minor data or index binary format changes (what about schema changes?) within minor version changes. If this is necessary, then there should be a clear upgrade process identified at the time of release i.e. there is either an automatic script that carries out the necessary changes in the background at system startup or there are manual steps clearly noted as an annex to the release notes. This same requirement for an upgrade automation or documented steps must be the same for major versions too. 

The main concern is to avoid user pain through binary missmatching of versions. The user simply shouldn't find out the upgrade failed, because of a lack of knowledge or upgrade automation. 

I also think defintions are needed as to what would be considered data or index binary format (and I'd add schematic format) changes, both minor or major. 

Scott

**Comment by jamieb22** [comment]
Scott. You are looking at it from the perspective of a single install of Orient DB running on one server. Sure, in this scenario, it is easy for a sys admin to run an upgrade script or even export to JSON and then back again. However, the reality is that Orient DB may be embedded in a cell phone app or client app, installed on hundreds of devices. In this case, it is darn impossible to perform a manual upgrade. It is for this reason there must always be an automatic upgrade path available.

I also disagree that schema changes should be allowed between minor and revision releases. The reason being: 1)  the product would need to undergo thorough testing between releases (if history is to judge, an unlikely event) 2) you would have to implement both upgrade and downgrade scripts (since any minor and revision should be able to read the same database). 

To give a concrete example of the problems faced by users of Orient DB: we recently took the plunge and upgraded Orient from 2.1.19 to 2.2.6. Upon upgrading, we encountered several errors (1) Orient cannot work with indexes created by 2.1.19 ( "RecordId cannot support negative cluster id. Found: -659 (#6547)"). Apparently, the indexes need to be dropped, but there is no way to detect the version of an index via API call (break rule: A version number must be assigned to all discreet data and index structures) or drop an index via the API. (2) Many of the deployments were receiving out of memory due to the fact that hardware requirements had changed from 2.1.19 to 2.2.6 because the Orient cache is more aggressive and requires more RAM (break rule: requirements change between minor releases). Our choice was then to try to downgrade Orient back to 2.1.19. We attempted to do this but Orient v2.1.19 couldn't read a database created by 2.2.6 (due to inability to deserialize an Enum). We frequently encounter situations like this and frankly it is a major source of concern. 

The Orient DB team appears to be currently focused solely on the paradigm of one database installed on one server, where that the sys admin has all the time in the day to perform complex upgrade procedures like export data manually to JSON format, and back again. Mature databases need a more seamless approach to upgrades and downgrades. 

This is not something is unique to Orient DB. Most modern successful databases work like this. For instance, we have been upgrading Mysql on our web app server for more than 12 years. Never once during that period have we had to run any upgrade script or have we lost any data due to an upgrade. Their upgrades are seamless. Why shouldn't Orient DB be held to the same standard? 

I'll admit that it does require an important shift in philosophy. Upgradability is absolutely core to objective of data preservation. Data cannot be preserved over time, if the software that manages it constantly breaks compatibility.

**Comment by jamieb22** [comment]
I'd have to add that upgradability is a prerequisite for durability. A change in mindset is needed. Please refer to the attached graphic.
![orientdbshift](https://cloud.githubusercontent.com/assets/6212848/17625702/4038af26-60aa-11e6-8f7e-b7d53e49af0e.png)

**Comment by smolinari** [comment]
Ok. Agreed. In embedded mode, there needs to be an automated upgrade path. I must admit, I didn't consider that scenario.

Still, if a vendor is using ODB in an embedded way, the responsibility of upgrading ODB is on the vendor. In other words, they "release" the version of ODB compatible with their application, both from a data and application integrity perspective. Obviously, knowledge of compatibility is key in this scenario and this policy will most definitely offer peace of mind for such vendors.

> 1) the product would need to undergo thorough testing between releases

Minor version releases also get beta and RC testing. 

> 2) you would have to implement both upgrade and downgrade scripts (since any minor and revision should be able to read the same database). 

As defined in semver, any changes being made must be backwards compatible. If they are not, they must wait for a major version change. Can we agree on that? This also helps define what type of changes or additions to binary or schema format means and where it fits into the policy.  

As for your diagram. 100% :+1: I think the community has been wanting this for the past year or so. Stop with features, get back to stabilizing the core. That includes strong driver support too. I do believe this is being baked into 3.0. :smile: 

Scott

**Comment by jamieb22** [comment]
Scott. Minor releases should be forward and backwards compatible. If I upgrade to v2.2 and it doesn't work, I should be able to downgrade to v2.1.

**Comment by smolinari** [comment]
> minor releases should be forward and backwards compatible.

That is what I said. So we agree. 

Scott

**Comment by jamieb22** [comment]
Scott. You wrote "As defined in semver, any changes being made in a minor version must be backwards compatible. If they are not, they must wait for a major version change." This statement appears to be different to what I am proposing: (1) I am proposing that all minor releases are both backwards and forwards compatible (if I right understand, you are suggesting backwards only) yes? (2) by adding the "if they are not" qualification, you are imply that there is still the option for subsequent minor releases not to offer backwards compatibility with prior releases. In my proposal, it is mandatory for both forward and backwards compatibility to be offered for all minor releases. 

Lets all acknowledge, that ensuring compatibility between releases is hard, potentially time consuming and often not much fun work. However, its just one of those things that has to be done in order to make Orient a useful and successful database.

**Comment by jamieb22** [comment]
Scott, I'd also like to add that automatic upgrades are not just useful for the embedded scenario (though the embedded case is an important one). Much like Orient DB, Mysql database is offered as  standalone product. When the Mysql engine is updated, there is typically not need to manually run any upgrade, further data can be retrieved and written data without any problems and there is no data loss.

**Comment by smolinari** [comment]
> if I right understand, you are suggesting backwards only

My understanding of backwards compatibility is that if you upgrade to a new minor version, the changes that are made will still work if you go back to the old version. You don't need to downgrade. You just reinstall the old software and everything still works properly. If however, any changes aren't backwards compatible, according to your policy definition, it must be pushed through in a major release. 

Or!

We could also suggest that a downgrade path (automation) must be made available, if a change is introduced within a minor version and it is not backwards compatible. However, that waters down the policy a bit. I am not to keen on the idea of downgrade automation. 

The only thing I was understanding from your initial post and was not agreeing with is that no changes could be made in a minor release. You said, 

> Data and index binary format changes _may not occur in minor updates_

That is too tight. I am suggestion that if changes are made, they can be, as long as they are backwards compatible.

And I agree. Automated upgrades (and if necessary downgrades) are the best solution for everyone. 

Scott

**Comment by jamieb22** [comment]
> My understanding of backwards compatibility is that if you upgrade to a new minor version, the changes that are made will still work if you go back to the old version.

In my mind, backwards compatibility means that a new minor version will be able to work with a database created by prior minor version. Forwards compatibility means that a prior minor release can work with a database created by newer minor releases. 

If I right understand, what you are wanting is the ability to make data and index binary format changes between minor releases, so long as they do not break backwards and forwards compatibility? In principle, I am ok with this, but in practice i wonder how to are going to ensure this over time. For instance in the example I gave earlier, if you downgrade Orient from 2.2.6 to 2.1.19, the database wont start due to a deserialisation issue. This type of issue is a frequent occurrence with Orient DB. Allowing format changes between releases, increases the probability of incompatibilities arising.

**Comment by jamieb22** [comment]
We had at one point commissioned Orient, to develop an automatic upgrade procedure. However, the upgrade procedure has since been surreptitiously removed in v2.2. Why might I ask was it removed? Is upgradeability not a priority for the Orient team? Can we please have a formal upgrade policy in place, posted on the Orient wiki, and strictly adhered to by the Orient DB developers and testers.

**Comment by smolinari** [comment]
When developing, a developer or development team is always looking forward. So, if they make a minor version and it includes changes in any form, that version should still work with the older data or code. That is backwards compatibility. In other words, if a user upgrades and finds out too much is going wrong with new features, he or she should still be able to use the older software with the same data or code and everything will still work. The only thing they are losing is the new functionality introduced in the minor version.  How this swapping between versions is made possible is up to the developers too. In other words, if they decide to make changes that aren't directly compatible, but offer upgrade and downgrade paths to the end user, then that is also acceptable. I think that is what you are looking for and I agree. 

The issues you ran into sound like clear BC breaks. They also describe a breaking of the Semver rules. That definitely shouldn't happen, if the ODB team takes Semver seriously.

I don't have a lot invested in ODB myself, yet. However, I personally see versions 1 and 2 as beta versions the whole time. If you look at them that way, then you can appreciate the BC breaks. However, as a paying customer, I would consider them an absolute no-go. 

To me, version 3 will be the first "real" version of ODB.  And I am sure, with our help, they'll stick to Semver besser too. :smile:

Scott

**Comment by jamieb22** [comment]
Scott. If Orient DB is in beta, why doesnt it have a BETA attached to the version? This product is supposedly to be production ready, but its not.

**Comment by smolinari** [comment]
ODB isn't in beta. Though they are developing it as if it were a beta, but with live systems depending on it. That is why all the conflict arises. That is the problem you have too. 

I personally consider it beta. Like I said, I don't have any large investment put into the software currently, i.e. no live system running it, so I don't have the same issues with it. I can see it as a beta. 

I am going to, however, be expecting version 3.0 and beyond to be different and properly following semver.

Scott

**Comment by jamieb22** [comment]
Scott. I wouldn't count on it. We have been using Orient from since the beginning. Its been a rough ride to say the least. There needs to be a big change of culture for Orient to be relied upon. If you take a look at that diagram I posted, it is what needs to happen in a nutshell.

**Comment by lvca** [comment]
Hey @jamieb22 if you look at the issues we worked in the past months, you will find that our priorities are on durability and reliability first, then all the rest.

Of course when we announce a new release we put the attention on what's new and we just mention the number of bugs fixed. But if you go on GitHub you can see by yourself how the effort is spent.

The entire team (and many external contributors) are working hard to make OrientDB the perfect database, but this is a long path. OrientDB is quite complex and has more features than any other NoSQL database. Anyway, I think every issue you found is fixed in short time, even if you don't have a support contract, right?

Unfortunately some piece of OrientDB is "legacy" and has to be replaced. That's why in release 3.0, for example, we will have a new SQL engine with a strict syntax, a deterministic and documented behavior and a query planner.

The new SQL engine will fix tons of existent issues with SQL. For this reason, please don't count it as "developing again new features instead of fixing bugs". I definitely prefer having something designed from scratch after years of experience than continuing patching the existent one.

**Comment by smolinari** [comment]
I think what we expect is simply for Semver to be followed to the tee with 3.0. For instance, if you end up finding that it will be necessary to change binary formatting or internal schema, which generally will break BC and there is no possible upgrade/downgrade path, then that version can't be called 3.1 or a patch version. It must be 4.0. 

There will also have to be a generous beta and RC testing phase for 3.0 too, which also follows Semver. i.e. in the RC phase, there must be a feature freeze. After the beta phase, any new features have to then be slated for 3.1. In other words, only bug fixes are allowed after the beta phase is over. 

Scott

**Comment by jamieb22** [comment]
Luca, look I do appreciate the strides that you guys are taking, but I have to say that from a user's point of view that Orient DB loses data from one release to the next. We have Orient DB embedded in our product and is deployed at many sites. Every single one of those sites has lost their entire database at least once or twice. It is a fact. The durability problem is a serious problem in Orient DB, and it continues to this day.

**Comment by lvca** [comment]
What do you mean with loose data? Records disappears? Server crashes? Are you using 2.2?

Also, when you wrote "Many of the deployments were receiving out of memory due to the fact that hardware requirements had changed from 2.1.19 to 2.2.6 because the Orient cache is more aggressive and requires more RAM", what's changed in RAM requirements that justified to stay with 2.1?

**Comment by jamieb22** [comment]
Luca. Yes, we frequently experience data loss between upgrades and server crashes. I've reported some of the issues already, and will continue to do so.

**Comment by lvca** [comment]
How did you have data loss on server crashes with OrientDB v2.2.x?
