### ISSUE TITLE
any() not working

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#6558]
## OrientDB Version, operating system, or hardware.
- v2.1.11
## Operating System
- [ ] Windows
## Expected behavior and actual behavior

care_home is a class that has attribute census. census attribute is a list of class census.
census has day and count as attributes.

select census[any().format('yyyy')='2015'],phone from care_home where name='kelvert center'

is giving string index out of range error.

but the below query works fine.

select census[day.format('yyyy')='2015'],phone from care_home where name='kelvert center'
## Steps to reproduce the problem

select census[any().format('yyyy')='2015'],phone from care_home where name='kelvert center'

**Comment by luigidellaquila** [comment]
Hi @smallik 

This problem is already fixed in 2.2, any chance to update?

Thanks

Luigi

**Comment by smallik** [comment]
I just tried with 2.2.7 and its still happening.

**Comment by smallik** [comment]
select census,phone from (select census from care_home where name='kelvert center' unwind census)  where census.any().format('yyyy')='2015'

This also is failing with parse error.

**Comment by luigidellaquila** [comment]
Hi @smallik 

Ok, I'm checking it

Thanks

Luigi

**Comment by smallik** [comment]
any update?

**Comment by smallik** [comment]
Can we mark this as a bug?

**Comment by luigidellaquila** [comment]
Hi @smallik 

Sure, I'm marking it as a bug.
I tried to fix it, but it's more complex than expected.
I'll keep you posted

Thanks

Luigi

**Comment by smallik** [comment]
Once this is done I can help with testing.

**Comment by smallik** [comment]
any update on this bug?
