### ISSUE TITLE
Console connect fails after close

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#6559]
## OrientDB Version, operating system, or hardware.
- v2.2.7
## Operating System
- [x] Linux
- [x] MacOSX
- [x] Windows
- [x] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

Attempting to connect to a working plocal database in the console should succeed after attempting to connect to a non-existent database and general has strange behavior.
## Steps to reproduce the problem

Note that this is a specific example that demonstrates the issue but there are other combinations of using open and close in the console which result in similar behavior.

```
$ ./console.sh
orientdb> create database plocal:test admin admin
orientdb> close
```

Connect fails after creating the database.  This fails b/c the string should be plocal:test/db b/c db is the default database name (or wal/wrl file name).

```
orientdb> connect database plocal:test admin admin

Connecting to remote Server instance [plocal:test] with user 'admin'...

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot connect to the remote server/database 'remote:plocal:test/'

Error: com.orientechnologies.common.io.OIOException: Error on connecting to plocal:test

Error: java.lang.NumberFormatException: For input string: "test"

orientdb> close
orientdb> exit
$ ./console.sh
```

Connect succeeds after exiting and starting the console and using the correct string

```
orientdb> connect plocal:test/db admin admin
Connecting to database [plocal:test/db] with user 'admin'...OK
orientdb> close
```

Connect fails after close (to a different db name called "db2")

```
orientdb> connect plocal:test/db2 admin admin

Connecting to database [plocal:test/db2] with user 'admin'...

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage 'test/db2' with mode=rw
    DB name="db2"
Error: com.orientechnologies.orient.core.exception.OStorageException: Can not open storage it is acquired by other process
    DB name="db2"

orientdb> close
orientdb> exit
$ ./console.sh
```

Connect succeeds using db name "db2" after exiting starting the console again!  It creates a new wal/wlr file called db2.

```
orientdb> connect plocal:test/db2 admin admin

Connecting to database [plocal:test/db2] with user 'admin'...OK
```

**Comment by tglman** [comment]
hi @odbuser2,

can you try to use for connect this:
` connect database plocal:./test admin admin`

we are aware of some trouble with path parsing so specifing it with "./dbName" make sure that is reading it correctly.

**Comment by saeedtabrizi** [comment]
Same problem for connect to remote via `connect REMOTE:127.0.0.1/Test_DB root root` command .
