### ISSUE TITLE
how to clear the custom fields

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6562]
Hi.
I started use OrientDB 2.2.6
but I can't clear custom fields

for it I use command "alter class myClass custom clear" 

this command worked in OrientDB 2.1.19

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

It seems to be a regression, I'll fix it in short 

Thanks

Luigi

**Comment by Ivanov-Yuriy** [comment]
command "custom clear" works in properties
"alter property test.myProp custom clear" // OK

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

I just pushed a fix on 2.2.x 

Thanks

Luigi
