### ISSUE TITLE
different behavior between classes and properties when I create/edit custom fields

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6563]
## OrientDB Version, operating system, or hardware.
- v2.2.6 

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
custom fields in classes
{"myField":"someValue"}
names of custom fields don't contain sign ` (backquote)

custom fields in properties
{"**`**myField2**`**":"someValue2"}
names of custom fields contain sign ` (backquote)

## Steps to reproduce the problem
create class test
create property test.pTest string
alter class test custom \`myField\`='someValue'
alter property test.pTest custom \`myField2\`='someValue2'
select from ( select expand(classes) from metadata:schema) where name = 'test'

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

it's definitely a bug, the back-tick quotes have to be removed.
I'll fix it ASAP

Thanks for reporting

Luigi

**Comment by Ivanov-Yuriy** [comment]
Hi @luigidellaquila 
I noticed another thing in properties
I can run the next query (without the back-tick quotes), and it won't be mistake
alter property test.pTest custom myField2='someValue2' //ok
but in classes this query returns mistake
alter property test custom myField1='someValue2' //error

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

Please check the syntax of your last statement, it should be `alter class` and not `alter property` ;-)

**Comment by luigidellaquila** [comment]
Anyway, I just pushed a fix on 2.2.x, it will be released with 2.2.8

Closing, thanks!

Luigi

**Comment by Ivanov-Yuriy** [comment]
> Please check the syntax of your last statement, it should be alter class and not alter property ;-)

Yeah, my fault
