### ISSUE TITLE
createDefaultUsers=False breaks creating databases from console

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#6564]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .7[x]

## Operating System
- [x] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

`security.json` specifies:
```
"server": {
    "createDefaultUsers": false
}
```

Expected behavior:
```
orientdb> create database remote:localhost:2424/test_db <user> <password> memory graph
```
successfully creates a database on the remote OrientDB server.

Actual
```
orientdb> create database remote:localhost:2424/test_db <user> <password> memory graph

Creating database [remote:localhost:2424/test_db] using the storage type [memory]...
Connecting to database [remote:localhost:2424/test_db] with user 'admin'...

Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'test_db'
        DB name="test_db"
        DB name="test_db"
```

## Steps to reproduce the problem

Edit the default `security.json` to set `createDefaultUsers` to `true` and restart the server. Run the above command in the OrientDB console to try to create a new database, and observe it not working.

**Comment by SDIPro** [comment]
The console "create database" command has been updated in 2.2.8-snapshot and develop to connect to the newly created database using the same server credentials (instead of assuming the admin/admin credentials are available) used to create the database.

**Comment by obi1kenobi** [comment]
Thanks!
