### ISSUE TITLE
ETL does not seem to follow config rules

### ISSUE THREAD

**Issue by pdilyard** [orientechnologies/orientdb#6566]
OrientDB version: 2.1.x

## Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I have the following configuration set, as the language driver I am using does not support SBTree RidBags:
```xml
<properties>
  <entry name="ridBag.embeddedToSbtreeBonsaiThreshold" value="1000000000" />
</properties>
```
This works fine, except I need to migrate data in a reliable and efficient manner to Orient. I tried using the ETL functionality, but it doesn't seem to follow this configuration rule. The insertions it makes use SBTree RidBags.

**Comment by robfrank** [comment]
Are you using ETL in plocal or remote? If you use it in plocal, the config file isn't read.

**Comment by pdilyard** [comment]
I think it was plocal. Would the config file have been read if I switched to remote?

**Comment by robfrank** [comment]
Switching to remote means start OrientDB as a standalone server  and point the ETL to the server via **remote:** protocol. The load time will be higher than in plocal, due to the fact network is used.
