### ISSUE TITLE
Error on reading server configuration from file

### ISSUE THREAD

**Issue by quantonganh** [orientechnologies/orientdb#6567]
## OrientDB Version, operating system, or hardware.
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux

## Expected behavior and actual behavior

The configuration file is managed by Salt:

```
ls -l /etc/orientdb/config.xml
-r--r----- 1 root orientdb 5110 Aug 16 03:39 /etc/orientdb/config.xml
```

It works fine in 2.1.x but we got the following error in 2.2.x when starting:

```
Aug 16 03:43:00 trusty orientdb-upstart: Error on reading server configuration from file: /etc/orientdb/config.xml
Aug 16 03:43:00 trusty orientdb-upstart: java.io.IOException: javax.xml.bind.UnmarshalException
Aug 16 03:43:00 trusty orientdb-upstart: - with linked exception:
Aug 16 03:43:00 trusty orientdb-upstart: [java.io.FileNotFoundException: /etc/orientdb/config.xml (Permission denied)]
Aug 16 03:43:00 trusty orientdb-upstart:        at com.orientechnologies.orient.server.config.OServerConfigurationLoaderXml.load(OServerConfigurationLoaderXml.java:112)
Aug 16 03:43:00 trusty orientdb-upstart:        at com.orientechnologies.orient.server.config.OServerConfigurationManager.<init>(OServerConfigurationManager.java:51)
Aug 16 03:43:00 trusty orientdb-upstart:        at com.orientechnologies.orient.server.OServer.startup(OServer.java:254)
Aug 16 03:43:00 trusty orientdb-upstart:        at com.orientechnologies.orient.server.OServer.startup(OServer.java:245)
Aug 16 03:43:00 trusty orientdb-upstart:        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Aug 16 03:43:00 trusty orientdb-upstart: Caused by: javax.xml.bind.UnmarshalException
```

There are 2 things here:

1. The error message should be changed to "Error on writing..." because as you can see, `orientdb` user has permission to read the configuration file.

2. Why the user that the server running as needs write permission on the configuration file? If I change the owner to `orientdb` and the permission to 640 then it can be started and I saw that there are some changes in the configuration file:

- remove the storages block
- swap the position of name and value: `<entry value="1073741824" name="memory.chunk.size"/>`
- add `<isAfterFirstTime>true</isAfterFirstTime>`

## Steps to reproduce the problem

- change permission of the configuration file to 440
- and the owner to root:orientdb

The point here is don't let the service change its own config file.

**Comment by bclermont** [comment]
orientdb need to write it's own config file? that is kind of insecure as an attacker can inject some logic and replace some path from `/where/it/safe/` to `/var/lib/somewhereitmustnotwriteto` and break something, next time it restart

**Comment by lvca** [comment]
This is true the first time OrientDB runs. You can change permissions after the first run if you're worried about it, or you can provide a config file already created to avoid it. Or again, you can avoid using server's users and rely on LDAP.

**Comment by bclermont** [comment]
Insecure by design

**Comment by lvca** [comment]
What's your proposal?
