### ISSUE TITLE
Find a way to collect JVM crash dumps (hs_err_pid) from Jenkins

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6568]
There are many random  `The forked VM terminated without properly saying goodbye. VM crash or System.exit called?` which cannot be reproduced locally. We have to find some way to collect JVM crash dumps to ease the debugging pains.

**Comment by cmassi** [comment]
Can OnError option help to collect hs_err files ? 

e.g: in exec line of server.sh can add
-XX:ErrorFile=$ORIENTDB_HOME/log/hs_err_pid%p.log -XX:OnError="cat $ORIENTDB_HOME/log/hs_err_pid%p.log | mail support@any.com" \

See also https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/clopts001.html

**Comment by taburet** [comment]
Thank you for the idea. I will try to append the crash dumps to the stdout.

**Comment by lvca** [comment]
@taburet is this already implemented? Can I close this?

**Comment by taburet** [comment]
@lvca it's not implemented, but seems like the root cause was in the faulty disk drive(s) on the test server, which are replaced now. I doubt JVM can provide crash dumps after such sever failures, that's why we were unable to find them on disks.
