### ISSUE TITLE
OSerializationException when using longs on the HTTP API

### ISSUE THREAD

**Issue by BartTK** [orientechnologies/orientdb#6569]
## OrientDB Version, operating system, or hardware.
- v2.2.7

## Operating System
-  Linux

## Expected behavior and actual behavior
Using the HTTP API, I want to add a document that contains a long property. When I post the new document, the server fails to parse the long.

Document to add: 
{
	"@class" : "User",
	...
	"passwordStartDate" : 15966242479729082368,
	...
}

Server response: 
"errors": [
    {
      "code": 500,
      "reason": 500,
      "content": "com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content for record: \"@class\" : \"User\",...\u000a\u0009\"passwordStartDate\" : 15966242479729082368,\u000a\u0009\..." : []\u000d\u000a--> java.lang.NumberFormatException: For input string: \"15966242479729082368\""
    }
  ]

## Steps to reproduce the problem
Post a document containing a large long value using the HTTP API.

**Comment by maggiolo00** [comment]
@BartTK 

was the field passwordStartDate declared in schema?

**Comment by BartTK** [comment]
Yes, it was declared as a 'long'.

Met vriendelijke groet,
  Bart Kerkhoff

2016-09-13 10:09 GMT+02:00 Enrico Risa <notifications@github.com>:

**Comment by BartTK** [comment]
And now the problem is clear to me. The value in my example doesn't fit within the 'long' type. It originated from from a 64-bit unsigned integer while Orients long is a 64-bit signed integer.

**Comment by maggiolo00** [comment]
@BartTK 

you did use http or OrientJS?

**Comment by BartTK** [comment]
I was filling the database from a C++ application using the HTTP API.

**Comment by tglman** [comment]
hi @BartTK,

Do you have a schema defined on that class ?

Bye

**Comment by BartTK** [comment]
Yes, a schema was defined and the field was declared as a 'long'. 
But as stated in the comment above; this is not a bug but a user error. The value giving the exception is outside the range of an OrientDB long. My application works with unsigned 64 bit integers, while the longs in OrientDB are signed and thus have a smaller positive range.
