### ISSUE TITLE
cannot change the abstract class attribute

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6572]
## OrientDB Version, operating system, or hardware.
- v2.2.6
## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

when I create class without the abstract class attribute, I cannot change this attribute later
if I create abstract class, I can change this attribute
## Steps to reproduce the problem

create class test
alter class test abstract true // error com.orientechnologies.orient.core.exception.ODatabaseException: Impossible to remove the last cluster of class 'test' drop the class instead DB name="my_test_db"

create class test2 abstract
alter class test2 abstract false // OK

**Comment by tglman** [comment]
hi @Ivanov-Yuriy,

this is made on porpouse, because change the class to abstract means drop data, we could improve the check and give a more meaningfull error, we will check if possible.

The case abstract to "fisical" does not compromise any data, so can be done without problem.

Regards

**Comment by tglman** [comment]
hi @Ivanov-Yuriy,

We did some small changes in the recent hotfix to check if there is data associated to the class when is set abstract, so now will fail only if there is data, so create + alter will work.

Can you please double check in your case ?

Bye

**Comment by Ivanov-Yuriy** [comment]
hi @tglman 
Thank you, so I wait next hotfix.
By the way when is it released?

**Comment by tglman** [comment]
Hi @Ivanov-Yuriy,

Acually the fix is not yet released, will be released in 2.2.13 next week.

Bye

**Comment by tglman** [comment]
hi @Ivanov-Yuriy 

This has been released any chance to check it ?

Regards

**Comment by tglman** [comment]
this as fixed and released a while ago, closing
