### ISSUE TITLE
Backup in remote mode doesn't work!

### ISSUE THREAD

**Issue by Bonizzi** [orientechnologies/orientdb#6579]
## OrientDB Version, operating system, or hardware.
- [x] v2.2.7 Enterprise

## Operating System
- [x] Windows

## Expected behavior and actual behavior
Backup with remote connection should work, as in according to the documentation: http://orientdb.com/docs/last/Console-Command-Backup.html

## Steps to reproduce the problem
I run the console and execute the command but doesn't work:

![issue](https://cloud.githubusercontent.com/assets/13778147/17741643/37364130-649d-11e6-8f33-7c794613ef34.png)

**Comment by tglman** [comment]
hi @Bonizzi,

this is expected, for the backup to work you need to connect in plocal.

regards.

**Comment by Bonizzi** [comment]
Hi @tglman, there is a way to do it in console or just via studio?

**Comment by tglman** [comment]
hi @Bonizzi,

The only backup you can do on a community edition with server running is the "Scheduled Backup", from studio and console you can do an export instead.

Regards
