### ISSUE TITLE
OrientGraph getIndices does not work

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6584]
## OrientDB Version, operating system, or hardware.
- v2.2.8 SNAPSHOT
## Operating System
- [ X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behaviour and actual behaviour

I would expect these methods to work equivalently, but they don't. 

The method graph.getRawGraph().getMetadata().getIndexManager().getIndexes() returns an iterator with more than one item

```
Collection<? extends OIndex> c = graph.getRawGraph().getMetadata().getIndexManager().getIndexes();
for (OIndex i : c) {
        if (i.getType()!=null && i.getType().toLowerCase().contains("hash") && i.getVersion()<2) {
            graph.dropIndex(i.getName());
        }
}
```

The method graph.getIndices().iterator() returns zero items

```
Iterator<Index<? extends Element>> indices = graph.getIndices().iterator();
while (indices.hasNext()) {
        OIndex i = (OIndex)indices.next();
        if (i.getType()!=null && i.getType().toLowerCase().contains("hash") && i.getVersion()<2) {
            graph.dropIndex(i.getName());
        }
}
```
## Steps to reproduce the problem

See above

**Comment by maggiolo00** [comment]
@jamieb22 

Seems that the API graph.getIndices().iterator()  loads only manual indexes. 
Let me check for a fix

Thanks

**Comment by maggiolo00** [comment]
@jamieb22 

Seems that the OrientIndex that handle indexes works only with manual indexes. So i guess you should use the underlying  API 

```
graph.getRawGraph().getMetadata().getIndexManager().getIndexes();
```

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
