### ISSUE TITLE
Duplicate records while using unique indexes in distributed setup

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6585]
After some investigation of prjhub#7417 it seems like the problem is in distributed storage. [This test case](https://gist.github.com/taburet/79d4f944c38ac8d96989f40f1a0d43c7) passes successfully on all storages except distributed (3-node setup). This test does concurrent inserts on random nodes with high probability of conflicts on unique indexes.

At some point a conflict is reported by throwing `ODistributedConfigurationChangedException`. After that moment [the duplicate records](https://gist.github.com/taburet/53899dfa5cd21fe033c623a06a4a37cd) start to appear on the nodes. If the inserts go into a single node in this 3-node setup, everything is fine.

Duplicate records seem to appear on two nodes only, on the third node a record is stored under different RID, but contains the same data as on the other two nodes. Maybe this is just a coincidence.

**Comment by lvca** [comment]
Forwarded to @taburet.
