### ISSUE TITLE
Improve Documentation for Use of Indices with OrientBaseGraph.getVertices()

### ISSUE THREAD

**Issue by jjszucs** [orientechnologies/orientdb#6589]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ] [X] 2.2.3

## Operating System
- [X] Linux
- [X] MacOSX
- [X] Windows
- [X] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

In order for OrientBaseGraph.getVeritices() to use indices to execute the query, both the vertex type and the property key must be specified. If only the property key (and not the vertex type) is specified, the index is not used and performance is severely reduced.

The example at http://orientdb.com/docs/last/Performance-Tuning-Graph.html#use-indexes-to-lookup-vertices-by-an-id correctly demonstrates this, but the documentation (both for performance tuning the graph API and for the OrientBaseGraph.getVertices()) should explicitly state this crucial consideration.

## Steps to reproduce the problem

See discussion between myself and Luca Garulli at https://groups.google.com/forum/#!topic/orient-database/iPU0QlY1yl4.

**Comment by lvca** [comment]
Updated docs by adding multiple references to it.
