### ISSUE TITLE
Support cluster selection for DELETE commands

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#6590]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ X] .17[ X] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[X ] .15[ X] .14[ X] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[X ] .beta2[ X] .beta1[X ]

All Versions!
## Operating System
- [X] Linux
- [X] MacOSX
- [x] Windows
- [X] Other Unix
- [X] Other, name? 
## Expected behavior and actual behavior

With regard to the  [Distribution strategy](http://orientdb.com/docs/2.0/orientdb.wiki/Tutorial-Clusters.html) of orientdb it must be possible to select a cluster to avoid a scan through all irrelevant clusters.

Expected sql support:

``` sql
DELETE EDGE <class> CLUSTER <cluster>|[<cluster>,...] WHERE <where>
```
## Steps to reproduce the problem

throws an exception:

``` sql
DELETE EDGE <class> CLUSTER <cluster>|[<cluster>,...] WHERE <where>
```

**Comment by smolinari** [comment]
Hey Dustin,

Doesn't the simpler command `DROP CLUSTER <cluster-name>|<cluster-id>` work?

Scott

**Comment by StarpTech** [comment]
Hi @smolinari I think yes but it has nothing to do with it. I want to remove a record from a specific cluster.

**Comment by smolinari** [comment]
Oh boy. Sorry about that. Don't know what I was thinking......

Scott

**Comment by lvca** [comment]
@StarpTech you can always delete edges by using rids. This is fast and is executed only by the servers that have the record:

```sql
DELETE EDGE #13:4343
```

or

```sql
DELETE EDGE [#13:4343, #134:434, #32:965976]
```

**Comment by lvca** [comment]
Implemented in 2.2.x and develop branches.

**Comment by StarpTech** [comment]
Hi @lvca thank you but can you port it to the 2.1.x series? You know my issues to switch to the 2.2.x series. thank you.

**Comment by vipuusepp** [comment]
DELETE EDGE edgename
not working when E is orestricted subclass
issue  #6425
