### ISSUE TITLE
Lucene index is empty (not reindexed) if deleted

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6592]
v 2.2.7

I was checking different configurations for Lucene and just deleted folder with Lucene jndex. On start, it was recreated, but not reindexed

**Comment by maggiolo00** [comment]
did you use
```
drop index ...
```
to delete the index?

**Comment by vantonov1** [comment]
no, I just deleted folder in explorer

**Comment by maggiolo00** [comment]
@vantonov1 
You should use

```
drop index ..
```
command that takes care of deleting the folder and the index from the metadata.

**Comment by vantonov1** [comment]
I'm not going to drop index. It is expected that index (linked to a field) would be restored on startup. Just consider "no files" as "broken index"

Imagine, that I store indexes on a different  disk for performance reason. Now, that new cool SSD crashed. I expect index to be recreated when storage is replaced



I checked the same situation with other type of indexes - Orient just failed to start with exception


com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:51)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3270)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1198)
	at com.orientechnologies.orient.server.OServer.loadStorages(OServer.java:1061)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:380)
	at com.firstlinesoftware.orient.server.services.impl.repo.OrientWrapper.startup(OrientWrapper.java:130)

**Comment by robfrank** [comment]
IMHO it is not a good idea to consider a "missing dir" as a condition to rebuild the index . Imagine if you have a big database, 100M documents, with a Lucene index defined over a text field. It can takes a lot of time to re-create the index. I think it is better to manually do that, dropping and create it again.

**Comment by vantonov1** [comment]
What I have now is an empty index - that situation called "integrity fail", index doesnt match table

May be it is a good idea to start indexing in background

With Orient own (non-Lucene) index types, the situation is even worse - Im unable to load storage after some files missing

**Comment by robfrank** [comment]
Are you randomly deleting files and folders?

**Comment by vantonov1** [comment]
No really randomly, just files for one class :). But even randomly. DB must be able to load storage and let me save all info still available. It have to be the most reliant part of infrastructure, it is really bad to get "unable to load storage" exception because one class couldnt be loaded

Concerning index - Orient restores broken indexes. Restores = deletes and recreates again, I dont see any reason why Lucene index should be treated another way. Yes, it is time-consuming, db could spend some time restoring failed state, thats ok

**Comment by robfrank** [comment]
Hi, I mark this as an enhancement for 3.1.

**Comment by vantonov1** [comment]
Hi!

Great! Just one more thing to consider - if index info could be recreated, it would be fine to store index on a different location (for example local SDD). Now Lucene indexes are stored in a subfolder (which could be soft link), could you create subfolder for other indexes as well?..

**Comment by robfrank** [comment]
Could you open a new issue with a more detailed description? This tips written on a comment will be lost in time, like tears in rain.

**Comment by vantonov1** [comment]
#6682
