### ISSUE TITLE
Can I build index concurrently ?

### ISSUE THREAD

**Issue by BruceMu** [orientechnologies/orientdb#6593]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

Is there any way to improve performance for batch insert, with index building at the same time;
For every type or class of vertex, there is many clusters. So if i use multi-thread to insert vertex,and assign different clusters to different thread, there may be no lock block ,but index building seems can't be concurrent , batch insert thread is always blocked when building index;

**Comment by lvca** [comment]
You can use the new AUTOSHARDED INDEX with v2.2: http://orientdb.com/docs/last/Auto-Sharding-Index.html. The maximum of performance (and zero contention) would be having X threads, where X is the number of clusters. By default it's the number of cores on your pc, but you could try using 2 * cores by setting it at the beginning. Example: `ALTER DATABASE MINIMUMCLUSTERS 16`.

Then you should compute the thread id as `threadId=Murmur3_hash(key) % x` and put the record in the queue of the thread `threadId` to be processed.

**Comment by BruceMu** [comment]
Is there a java api used to rebuild index after vertices/edges are wrote;

**Comment by lvca** [comment]
Sure, get the Index manager where you can find methods to work with indexes: `OIndexManager idxMgr = graph.getRawGraph().getMetadata().getIndexManager()`
