### ISSUE TITLE
The NPE exception is thrown when inserting record

### ISSUE THREAD

**Issue by anatse** [orientechnologies/orientdb#6597]
## OrientDB Version, operating system, or hardware.
- v2.2.7

## Operating System
- Windows

## Expected behavior and actual behavior
The NPE exception is thrown when I try to insert record in database  
## Steps to reproduce the problem
**Schema script:**
```
create class CodeWithName;
create property CodeWithName.code string;
create property CodeWithName.name string;
alter property CodeWithName.code mandatory true;
alter property CodeWithName.name mandatory true;

create class Address;
create property Address.city embedded CodeWithName;
create property Address.street embedded CodeWithName;
create property Address.building embedded CodeWithName;
alter property Address.city mandatory true;
alter property Address.street mandatory true;
alter property Address.building mandatory true;

create class Pharmacy EXTENDS V;
create property Pharmacy.name STRING;
create property  Pharmacy.address embedded Address;
create property  Pharmacy.chiefPhone STRING;
alter property Pharmacy.name MANDATORY TRUE;
alter property Pharmacy.address MANDATORY TRUE;
```

**NullPointerException occurred when trying to execute insert** 
`insert into Pharmacy(name, address) values ('Pharmacy', {"@type":"d", "@class": "Address",  "city": {"@type":"d", "@class":"CodeWithName", "code":"1", "name": "New-York"}, "street": {"@type":"d", "@class":"CodeWithName", "code":"10", "name": "24"}, "building": {"@type":"d", "@class":"CodeWithName", "code":"100", "name": "100"}})`

**In log only**: SEVER Internal server error:
java.lang.NullPointerException [ONetworkProtocolHttpDb]

**Comment by maggiolo00** [comment]
@anatse 

i did try with 2.2.7 without problem.

How can i reproduce that.

**Comment by anatse** [comment]
Oh sorry, I miss one important thing - index
CREATE INDEX UxPharmacyAddress ON Pharmacy(address) UNIQUE;

**Comment by maggiolo00** [comment]
@anatse 

Indexes on embedded objects are not supported yet

http://orientdb.com/docs/last/Roadmap.html#release-30

**Comment by maggiolo00** [comment]
@anatse 
please follow this issues for this enhancement
https://github.com/orientechnologies/orientdb/issues/5201
