### ISSUE TITLE
Escaping double quotes

### ISSUE THREAD

**Issue by dbradicich** [orientechnologies/orientdb#6599]
I have a query as so 'contentExpression(@this, :param1) == true' and passing in params such as 'A == "B"' i see an exception stating error parsing 'contentExpression(@this, "A == \"B\"") == true'

Is there some additional escaping i need to do for double quotes to be handled in the param ?

**Comment by dbradicich** [comment]
note this is with orient 2.2.6

**Comment by luigidellaquila** [comment]
Hi @dbradicich 

No, it seems to be correct on your side. The problem seems to be a bug in the parser. We are addressing many of these issues right now, I'll keep you posted

Thanks

Luigi
