### ISSUE TITLE
Sharding, unexpected clusters

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#6608]
## OrientDB Version, operating system, or hardware.

OrientDB docker image 2.2.7

I'm testing sharding as explained [in the documentation](http://orientdb.com/docs/2.2/Distributed-Sharding.html) but I don't get the results I expect.

These are the steps I take:
- I create and run 2 containers using the official docker image: castor and pollux.
- I connect, using the studio, to the node "castor" and I create a db called "mythology".
- I create via the studio a class named "character".
- I add an instance of the character class called "Achilles", still in node castor.
- In a different tab in the browser, I connect to the node "pollux" using the studio.
- I add an instance of the character class called "Odysseus".

Now, if using the studio (connected to the node castor) I do "select from character", this is what I get:

```
@rid @version @class name
#26:0 1 character Achilles
#26:1 1 character Odysseus
```

And then I connect to the node "castor" using the console and I execute "clusters", what I get (I omit the parts that are not meaningful here):

```
CLUSTERS (collections)
+----+-----------+----+---------+-----------------+-----+
|#   |NAME       |  ID|CLASS    |CONFLICT-STRATEGY|COUNT|
+----+-----------+----+---------+-----------------+-----+
|4   |character  |  26|character|                 |    2|
|5   |character_1|  27|character|                 |    0|
|6   |character_2|  28|character|                 |    0|
|7   |character_3|  29|character|                 |    0|
|8   |default    |   3|         |                 |    0|
+----+-----------+----+---------+-----------------+-----+
|    |TOTAL      |    |         |                 |   12|
+----+-----------+----+---------+-----------------+-----+
```

The documentation says

> OrientDB automatically creates a new cluster per each class as soon as node joins the distributed cluster. These cluster names have the node name as suffix: <class>_<node>.

, that's why I was expecting 2 clusters, one named character_castor, containing one record, and another one called character_pollux containing the other record.

What am I missing?

**Comment by diegomtassis** [comment]
This is odd.

Right after what I described in the ticket, I tried to add another record via the studio connected to the "castor" node.

I executed 
`insert into character set name = 'Ajax'`
and I got as response an exception saying that castor was not anymore the owner of the cluster character_1.

I tried to add it in the studio connected to node pollux and it worked. Then I came again to the studio connected to castor, tried to add a new character and worked.

After all, I execute "clusters" in the console and this is the result:

```
CLUSTERS (collections)                                                                                    
+----+-----------+----+---------+-----------------+-----+------------+-------------+--------------------+ 
|#   |NAME       |  ID|CLASS    |CONFLICT-STRATEGY|COUNT|OWNER_SERVER|OTHER_SERVERS|AUTO_DEPLOY_NEW_NODE| 
+----+-----------+----+---------+-----------------+-----+------------+-------------+--------------------+ 
|4   |character  |  26|character|                 |    2|   pollux   |  [castor]   |        true        | 
|5   |character_1|  27|character|                 |    1|   pollux   |  [castor]   |        true        | 
|6   |character_2|  28|character|                 |    1|   castor   |  [pollux]   |        true        | 
|7   |character_3|  29|character|                 |    0|   castor   |  [pollux]   |        true        | 
+----+-----------+----+---------+-----------------+-----+------------+-------------+--------------------+ 
|    |TOTAL      |    |         |                 |   14|            |             |                    | 
+----+-----------+----+---------+-----------------+-----+------------+-------------+--------------------+ 
```

**Comment by lvca** [comment]
The documentation is old, we have to update it. Cluster names have no the node name as the prefix. Also, they are not pre-created when a node joins, but only if necessary. In recent 2.2.x we fixed the problem of lazy creation of the cluster the first time you execute a write operation against a node without any ownership.

**Comment by lvca** [comment]
Docs updated.
