### ISSUE TITLE
How to remove specific lightweight edge?

### ISSUE THREAD

**Issue by bpromasmb** [orientechnologies/orientdb#6609]
## OrientDB Version, operating system, or hardware.
- v1.7.8

## Operating System
- Windows 7

*[I have opened this same issue as a [question](http://stackoverflow.com/questions/39152163/orientdb-how-to-remove-specific-lightweight-edge) on StackOverflow. I am simply posting here for more visibility. I hope you don't mind.]*

I am using ruby on rails' gem [oriented](https://github.com/ruprict/oriented), which allows you to use the Java API to interface with Orient's database.

Say I have three vertices `v0 (rid #10:0)`, `v1 (rid #10:1)` and `v2 (rid #10:2)`, and then I add edges connecting them like so:

    connection = Oriented.connection
    graph = connection.graph

    v0 = graph.getVertex("#10:0")
    v1 = graph.getVertex("#10:1")
    v2 = graph.getVertex("#10:2")

    graph.addEdge(nil, v0, v1, 'owns')
    graph.addEdge(nil, v0, v2, 'owns')

So now my database looks like this:

    rid   | in_owns | out_owns
    ------|---------|-------------
    #10:0 |         | #10:1, #10:2
    #10:1 | #10:0   |
    #10:2 | #10:0   |

And now I would like to remove the edge between #10:0 and #10:1, preferably using Java's API to do it, which oriented seems to support (couldn't find a way to run SQL queries inside a transaction)

**Comment by lvca** [comment]
Already answered on SO.
