### ISSUE TITLE
SQL batch unusable in a distributed multi-master setup 

### ISSUE THREAD

**Issue by dhart-alldigital** [orientechnologies/orientdb#6610]
## OrientDB Version, operating system, or hardware.
- v2.1.*
- v2.2.6/7/8
- Tried both community and enterprise editions
- Using remote connections
- Testing this out using 3 AWS EC2 instances, with OrientDB running within docker containers on each host, using Hazelcast's Amazon discovery plugin.

## Operating System
- [X] Linux

## Expected behavior
When executing sql batch statements, either via studio, console or the java graph api (OCommandScript), the executed statements should be successful and replicated to all other instances within the cluster.

### 1st scenario
Running a 3 instance cluster, all master, with write quorum set to `majority`, a simple create vertex followed by create edge fail with the message:
```
com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #31:1 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v2 your=v1) DB name="profiles"
```
What is strange here is that record #31:1 was at v2 in all instances before the above sql was executed.  I don't understand why it thinks it is at v1?

### 2nd scenario
Running a 3 instance cluster, all master, with write quorum set to `all`, the same simple create vertex followed by create edge exhibits the exact same behavior as in the 1st scenario.

### 3rd scenario
Running a 3 instance cluster, all master, with write quorum set to `1`, the same simple create vertex followed by create edge runs successful.  No errors are reported in the logs.  When querying the instances, the server where the command was executed contains the new records, but does not exist in the other 2 masters.

### 4th scenario
Running a 3 instance cluster, 1 master with 2 replicas, the same simple create vertex followed by create edge runs successful, and is replicated to the other instances.

**Comment by dhart-alldigital** [comment]
Any feedback on this, or any other info you need from me?  We use sql batch as part of automated incremental database updates when we roll out new features.  This is a blocker for us moving to production.

**Comment by dhart-alldigital** [comment]
Any comment @lvca?

**Comment by lvca** [comment]
@dhart-alldigital A script with what you execute would be helpful here.

**Comment by dhart-alldigital** [comment]
@lvca I've been trying all morning to replicate this with a fresh db using a script to no avail, so instead debugged further with our existing database. 

I started tearing away at our own database class by class to see if it was data related.  After deleting almost everything I ended up with but just 2 vertices and 1 edge remaining.  When I ran a sql batch to create a new vertex and edge (in the distributed setup) it still fails, but if I delete and remove all the properties of the vertex schema definition that represents the existing class that I'm trying to add an edge to the sql batch query starts running successfully for a short while, but then after a few seconds it starts failing again with the same original message, the deleted and removed properties all reappear, and an _auto repairing completed_ message is output to the log of the node I'm running the sql batch query against.

Note that after I removed all the properties and values of the vertex mentioned above I did check on my running nodes to see if the changes had replicated.  The changes were present on all nodes, so I've no idea how the replicated changes are being reverted.

As I said above, I'm having trouble reproducing this by script with a fresh database, but I can send you over an export of the trimmed down database I'm using where I can reproduce it reliably.  Let me know where to send it.

**Comment by lvca** [comment]
@dhart-alldigital if you have a test case I can run against an empty or your database it would be awesome. You can send your compressed DB to support --at- orientdb.com if <10MB, otherwise please host it in some cloud and send the link.

**Comment by lvca** [comment]
Thanks for your attachments. It was a bug with the database created in non-distributed mode (like yours). Fixed in 2.2.x branch (and develop branch too). It will be released in the release 2.2.10.

**Comment by robfrank** [comment]
Next version will be 2.2.11.

**Comment by lvca** [comment]
You're right, modified the comment.
