### ISSUE TITLE
Automatic backup with export mode

### ISSUE THREAD

**Issue by vishu18** [orientechnologies/orientdb#6611]
## OrientDB Version, operating system, or hardware.
OrientDB 2.2.7
We are using the automatic backup feature in the export mode with the following configuration
{
  "enabled": true,
  "mode": "EXPORT",
  "exportOptions": "",
  "delay": "1h",
  "targetDirectory": "/backup",
  "targetFileName": "${DBNAME}-${DATE:yyyyMMddHHmmss}",
  "dbInclude": "mydb",
  "compressionLevel": 9,
  "bufferSize": 1048576
}
We are running OrientDB in a multi-master node setup.
 Since we are using the export mode, my understanding is that an individual node should not be halted during the backup operation and all write operations directed to the cluster should progress without any issue. Is this correct?

**Comment by lvca** [comment]
Correct

**Comment by lvca** [comment]
Please use StackOverflow with tag "orientdb" next time for questions. Thanks.
