### ISSUE TITLE
Out of Memory Error (heap)

### ISSUE THREAD

**Issue by davidbprice** [orientechnologies/orientdb#6612]
## OrientDB Version, operating system, or hardware.
- v2.2.8, v2.2.2

## Operating System
- [X ] Windows
using orientjs driver from nodejs.

I get java heap error when calling db.update(..).set(..) when the data passed in the set object is fairly large. It works twice then fails on the third call. I am closing the db and the server after each call to make sure resources are freed, but I'm guessing some sort of caching is going in orient that isn't getting cleared? (Total guess).  

what I want to update is in a reasonably deep json object  attra.attrb[idx].attrc.attrd[idx1]...
Is there a way that I can specify that type of depth in the set object so I could update only the little bit of data that is actually different? The examples in the orientjs documentation are very simple so do not provide much help.

Is there a setting of some kind that can be set to mitigate this problem.  Just using a larger heap seems like it won't solve the problem just let me do a few more updates before failure.

update: It also sometimes gets this error instead. java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by bsw11** [comment]
Luca,   this is the first time we have run into a problem since we started  with Odb. We are almost ready to demo. 
Please advise or help on this.

**Comment by bsw11** [comment]
I realized that you might not know who this is.   It's Barry Weingart from FlowTAC.

**Comment by lvca** [comment]
Hi Barry,
1. How much Heap are you allocating for OrientDB server?
2. How big is your JSON in KB?
3. Could you provide a memory dump of the OrientDB server when is running in out of memory or even better before that? You can use YourKit or Oracle VisualVM (free) with the memory analyzer plugin

**Comment by bsw11** [comment]
Will have to wait till David gets going to  get that info.  Where is the setting for heap size?

**Comment by bsw11** [comment]
Ok upping the heap from 512 to 3gb seems to work. It's obvious that we have done little tuning. As in 0. It would have been helpful to mention the heap size increase on the crash log and that it's in server. Bat.  Though I don't think it should crash no matter what
