### ISSUE TITLE
Different behavior in REST responses when using IdGraph

### ISSUE THREAD

**Issue by mikeazo** [orientechnologies/orientdb#6616]
## OrientDB Version, operating system, or hardware.

v2.2.8
## Operating System

Linux
## Expected behavior and actual behavior

I'm using the REST api to interact with OrientDB Server. When using a normal graph, everything works as I would expect. When I try wrapping a graph in _IdGraph_, the results returned from the server are different. I would expect them to be the same just with the ID specified.
## Steps to reproduce the problem
1. Start the orient server
2. Create a test database: `curl -X POST http://root:password@localhost:2480/database/test/plocal`
3. Use IdGraph to add a vertex to it: `curl -H "Content-Type: application/json" -X POST -d '{"command":"g=new IdGraph(g); g.addVertex(\"abc-123\");"}' http://root:password@localhost:2480/command/test/gremlin`  
   This returns the result:`{"result":[{"@type":"d","@version":0,"value":"v[abc-123]"}]}`
4. Now add a vertex without IdGraph: `curl -H "Content-Type: application/json" -X POST -d '{"command":"g.addVertex();"}' http://root:password@localhost:2480/command/test/gremlin`  
   This returns the result:`{"result":[{"@type":"d","@rid":"#10:0","@version":1,"@class":"V"}]}`  
   This is the behavior I would expect when using _IdGraph_.

If I add properties to the vertex, then retrieve the vertex after wrapping in _IdGraph_, I don't see those properties, I only see _"value":"v[abc-123]"_. On the other hand, without _IdGraph_, I do see the properties.

Similarly, if I remove the vertex just added without IdGraph, then run `g.V` without IdGraph, I get: `{"result":[{"@type":"d","@rid":"#9:0","@version":1,"@class":"V","__id":"abc-123"}]}`, whereas, with IdGraph (so I'm running `g = new IdGraph(g); g.V`) I get: `{"result":[{"@type":"d","@version":0,"value":"v[abc-123]"}]}`

**Comment by mikeazo** [comment]
I don't know if this is related to #2087 or not.

**Comment by lvca** [comment]
Are the properties in the vertices if you query the database with console or studio? It could be just something about how the vertex is dumped when you create it. Did you check it?

**Comment by mikeazo** [comment]
@lvca It is not just happening on creation. It happens any time I create/retrieve after wrapping in _IdGraph_. I had not tested the console. From the console, this is what I get. My graph _test_ has one vertex, which I created using the IdGraph wrapper.

```
gremlin> g = new OrientGraph("remote:localhost/test")
==>orientgraph[remote:localhost/test]
gremlin> g.v('#9:0')                                 
==>v[#9:0]
gremlin> g.v('#9:0').map
==>{__id=abc-123}
gremlin> ig = new IdGraph(g)                         
==>idgraph[orientgraph[remote:localhost/test]]
gremlin> ig.v('abc-123')                             
==>v[abc-123]
gremlin> ig.v('abc-123').map
==>{}
```

So the behavior looks the same, which is good. 

On the other hand, these are the results from the REST api for retrieving that specific vertex

```
$ curl -H "Content-Type: application/json" -X POST -d '{"command":"g.v(\"#9:0\");"}' http://root:password@localhost:2480/command/test/gremlin | python -m json.tool
{
    "result": [
        {
            "@class": "V",
            "@rid": "#9:0",
            "@type": "d",
            "@version": 1,
            "__id": "abc-123"
        }
    ]
}

$ curl -H "Content-Type: application/json" -X POST -d '{"command":"ig = new IdGraph(g); ig.v(\"abc-123\");"}' http://root:password@localhost:2480/command/test/gremlin | python -m json.tool
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "value": "v[abc-123]"
        }
    ]
}
```

Is there a way to run gremlin in studio? Or alternatively, is there a way to wrap with _IdGraph_ before doing an sql query? I am less familiar with studio and the sql syntax.

**Comment by mikeazo** [comment]
I also tried using pyorient and connecting to OrientDB over the binary interface. Here are my results.

```python
>>> import pyorient
>>> client = pyorient.OrientDB("localhost", 2424)
>>> client.db_open('test', 'root', 'password')
[<pyorient.otypes.OrientCluster object at 0x7f679968cf10>, <pyorient.otypes.OrientCluster object at 0x7f679968cf50>, <pyorient.otypes.OrientCluster object at 0x7f679968cf90>, <pyorient.otypes.OrientCluster object at 0x7f679968cfd0>, <pyorient.otypes.OrientCluster object at 0x7f6799696050>, <pyorient.otypes.OrientCluster object at 0x7f6799696090>, <pyorient.otypes.OrientCluster object at 0x7f67996960d0>, <pyorient.otypes.OrientCluster object at 0x7f6799696110>, <pyorient.otypes.OrientCluster object at 0x7f6799696150>, <pyorient.otypes.OrientCluster object at 0x7f6799696190>, <pyorient.otypes.OrientCluster object at 0x7f67996961d0>, <pyorient.otypes.OrientCluster object at 0x7f6799696210>, <pyorient.otypes.OrientCluster object at 0x7f6799696250>, <pyorient.otypes.OrientCluster object at 0x7f6799696290>, <pyorient.otypes.OrientCluster object at 0x7f67996962d0>]
>>> print client.gremlin('g.V')[0]
{'@V':{'__id': 'abc-123'},'version':1,'rid':'#9:0'}
>>> print client.gremlin('ig = new IdGraph(g); ig.V')
[None]
>>> print client.gremlin('ig = new IdGraph(g); ig.V')[0]
None
```

**Comment by mikeazo** [comment]
I added another vertex to the DB I was working with. Then queried for all vertices again.

Here is the output of using pyorient:

```python
>>> client.gremlin('g.V')
[<pyorient.otypes.OrientRecord object at 0x7fcb51468d50>, <pyorient.otypes.OrientRecord object at 0x7fcb51468d10>]
>>> for v in client.gremlin('g.V'):
...   print v
... 
{'@V':{'__id': 'abc-123'},'version':1,'rid':'#9:0'}
{'@V':{'__id': 'def-456'},'version':1,'rid':'#9:1'}
>>> client.gremlin('ig = new IdGraph(g); ig.V;')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "env/local/lib/python2.7/site-packages/pyorient/orient.py", line 407, in gremlin
    .prepare(( QUERY_GREMLIN, ) + args).send().fetch_response()
  File "env/local/lib/python2.7/site-packages/pyorient/messages/commands.py", line 149, in fetch_response
    return self._read_sync()
  File "env/local/lib/python2.7/site-packages/pyorient/messages/commands.py", line 202, in _read_sync
    res.append( self._read_record() )
  File "env/local/lib/python2.7/site-packages/pyorient/messages/base.py", line 462, in _read_record
    raise PyOrientNullRecordException('NULL Record', [])
pyorient.exceptions.PyOrientNullRecordException: NULL Record
>>> 
```

On the server I had two messages in the console:
```
2016-08-29 09:27:55:871 WARNI {db=test} Cannot serialize record: v[abc-123] [ONetworkProtocolBinary]
2016-08-29 09:27:55:871 WARNI {db=test} Cannot serialize record: v[def-456] [ONetworkProtocolBinary]
```

On the other hand, when using REST, I get:

```
$curl -H "Content-Type: application/json" -X POST -d '{"command":"g.V;"}' http://root:password@localhost:2480/command/test/gremlin | python -m json.tool
{
    "result": [
        {
            "@class": "V",
            "@rid": "#9:0",
            "@type": "d",
            "@version": 1,
            "__id": "abc-123"
        },
        {
            "@class": "V",
            "@rid": "#9:1",
            "@type": "d",
            "@version": 1,
            "__id": "def-456"
        }
    ]
}
$ curl -H "Content-Type: application/json" -X POST -d '{"command":"g = new IdGraph(g);g.V;"}' http://root:password@localhost:2480/command/test/gremlin | python -m json.tool
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "value": [
                "v[abc-123]",
                "v[def-456]"
            ]
        }
    ]
}
```

So for some reason, when I have more than one record returned, I get a serialization error when using the binary interface.

**Comment by lvca** [comment]
Got it: in case when vertices (and edges) are returned, the toString() is done instead of expanding the object because the IdGraph can return IdVertex and IdEdge. Unfortunately we can't add an `instanceof IdVertex` because the server is not linked to the graph one.

Any chance to return v.getBaseVertex() instead?

**Comment by mikeazo** [comment]
So _getBaseVertex_ gets me this:

```
$ curl -H "Content-Type: application/json" -X POST -d '{"command":"g = new IdGraph(g);g.v(\"abc-123\").getBaseVertex();"}' http://root:password@localhost:2480/command/test/gremlin | python -m json.tool
{
    "result": [
        {
            "@class": "V",
            "@rid": "#9:0",
            "@type": "d",
            "@version": 1,
            "__id": "abc-123"
        }
    ]
}
```

So, it allows me to do my querying, etc on the _IdGraph_, but then any results I get back would have be in the base graph. I'd have to think about it some more to figure out how useful that would be in my app.

**Comment by mikeazo** [comment]
Also, I don't know how much of a difference it makes, but when I use Rexster instead of Orient server, everything works as expected. I don't know if there is something different being done in Rexster server that could be done here to make it work.

**Comment by mikeazo** [comment]
@lvca Any suggestions on how to handle edges in this case? I can call _getBaseEdge_ to get the base edge record, but this has the real id's of the in vertex and the out vertex, instead of the custom id's I've chosen. It would be a pain (but feasible) to then lookup both vertices to get the proper mapping. I'm hoping there is something easier I can do, but maybe not.

For vertices it was fairly easy since vertices have an `__id` property on them. I hadn't realized that edges do not store the custom id for the in and out vertices.
