### ISSUE TITLE
select from E,V not working in Studio

### ISSUE THREAD

**Issue by kindofwhat** [orientechnologies/orientdb#6617]
## OrientDB Version, operating system, or hardware.
- v2.2.8
## Operating System
- [x] MacOSX

## Expected behavior and actual behavior
Should display results, but displays 

`Error parsing query: select from E,V ^ Encountered " "," ", "" at line 1, column 14. Was expecting one of: <EOF> <WHERE> ... <ORDER> ... <GROUP> ... <LIMIT> ... <SKIP2> ... <OFFSET> ... <TIMEOUT> ... <FETCHPLAN> ... <LOCK> ... <LET> ... <NOCACHE> ... <PARALLEL> ... <UNWIND> ... ";" ... <LET> ... <WHERE> ... <GROUP> ... <ORDER> ... <UNWIND> ... <SKIP2> ... <OFFSET> ... <LIMIT> ... <FETCHPLAN> ... <TIMEOUT> ... <LOCK> ... <PARALLEL> ... <NOCACHE> ... <NOCACHE> ... DB name="GratefulDeadConcerts"
`

## Steps to reproduce the problem
Log in to OrientDB Studio, Standard DB, execute query

**Comment by maggiolo00** [comment]
You cannot select from multiple target in this way.
you should use unionall
See here
http://orientdb.com/docs/2.1/SQL.html#select-from-multiple-targets

**Comment by kindofwhat** [comment]
sorry, completely missread the info
