### ISSUE TITLE
Definiing a new Class with alias in Studio gives an error message

### ISSUE THREAD

**Issue by kindofwhat** [orientechnologies/orientdb#6618]
## OrientDB Version, operating system, or hardware.
- v2.2.8
## Operating System
- [* ] MacOSX

## Expected behavior and actual behavior
Adding a new class, alias filled, in "Schema" is successful but still creates an error

`
{"errors":[{"code":500,"reason":500,"content":"java.lang.IllegalArgumentException: Class 'test' is already present in schema"}]}
`

## Steps to reproduce the problem
See above, sometimes happens only the second time a new class is created

**Comment by maggiolo00** [comment]
@kindofwhat 

So you are creating a class that does exist right?

**Comment by maggiolo00** [comment]
@kindofwhat 

i was unable to reproduce it can you help me on that?

Thanks

**Comment by kindofwhat** [comment]
Hi, sorry for my late response.

I just tried it again, and I cannot reproduce the problem anymore. 

Sorry for the fuss, maybe best thing would be to close this issue. If I can reproduce it again, I will write it down more specifically
