### ISSUE TITLE
Upgrading OrientDB from v2.1.16 to v2.2

### ISSUE THREAD

**Issue by gavin-meyers** [orientechnologies/orientdb#6620]
## Context
In our last meeting with Luigi, he recommended that we upgrade to v2.2 to solve problems related to :

1. Hazelcast memory consumption
2. Query Performance issues
3. Cluster issues with v2.1.16. {Node coming out of cluster randomly, and no response from any other nodes thereafter, even though their health is fine}.

## Ask from Cisco Engg

We would like to upgrade to v2.2 provided the below condition is met.

* We would not like to make any code changes in our codebase, when the upgrade is done, due to any new feature or query changes in the new version. Our existing queries should work fine, as is.

**Comment by maggiolo00** [comment]
Reopened in Support Platform
