### ISSUE TITLE
Possible corrupted database after crashing on DELETE EDGE query

### ISSUE THREAD

**Issue by EricLin2004** [orientechnologies/orientdb#6631]
## OrientDB Version, operating system, or hardware.
- v2.1.11

## Operating System
- [x] MacOSX

## Steps to reproduce the problem
OrientDB crashed (out of memory in logs) due to a large DELETE EDGE query I had going to clean up some edges. Now I'm getting nullPointerException errors in console while trying to access some vertexes:
<img width="923" alt="screen shot 2016-08-29 at 10 54 42 am" src="https://cloud.githubusercontent.com/assets/3770894/18061443/9207c79e-6dd7-11e6-9ca5-07de9becfbe4.png">

and, for some reason, when I use subqueries I get an odd error now.

This query works fine:
```
SELECT expand(out('profile').out('contact')) 
FROM User WHERE email='lorem@ipsum'
```

This query does not:
```
SELECT FROM (
  SELECT expand(out('profile').out('contact')) 
  FROM User WHERE email='lorem@ipsum'
)
```

gives me this error:
<img width="924" alt="screen shot 2016-08-29 at 10 55 54 am" src="https://cloud.githubusercontent.com/assets/3770894/18061429/88e373de-6dd7-11e6-9c28-89ed92f7989f.png">

Tried to use `repair database --fix-graph` but I get `Error: java.lang.NullPointerException`

I've tried to go through and manually update vertexes affected but I keep getting NullPointerExceptions.

Any ideas on how to proceed other than reverting to a prior state? (which is a possibility)

**Comment by lvca** [comment]
Hey @EricLin2004, WDYT about migrating to v2.2.x?

**Comment by EricLin2004** [comment]
Yeah I just started looking at that this morning, think that would help, @lvca ?

**Comment by lvca** [comment]
We fixed hundreds of issues in v2.2, so probably by just upgrading this is gone, otherwise we can look at it on a recent code base, so we can fix it quickly.

**Comment by EricLin2004** [comment]
Sounds good, let me try that first then before we look into anything else.

Thanks for the quick response @lvca ! I'll post an update once it's done.

**Comment by EricLin2004** [comment]
So I've upgraded to v2.2.8, I no longer get errors when looking at the same vertexes as before.

However, I feel like there are probably still some edges pointing to empty vertexes?

I tried to run

`repair database --fix-graph`

but I get:

```
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #24:5118 (cluster: person)
	DB name="lorem"
	DB name="lorem"

Error: java.lang.OutOfMemoryError: Java heap space
```

**Comment by lvca** [comment]
Can we have your database in private, so we can look at what is wrong with record #24:5118? In case please send it to support - at-- orientdb.com. Thanks.

**Comment by EricLin2004** [comment]
Hey @lvca , I unfortunately wasn't given the go ahead to release the db so we're going to revert to a stable state of the db.

Looking into the orientdb logs some more though, I found the point where the issues started arising and it seemed like this error may have been the root cause:

<img width="1163" alt="screen shot 2016-08-31 at 11 04 24 am" src="https://cloud.githubusercontent.com/assets/3770894/18140672/6741f59e-6f6b-11e6-8558-76ca7328b38d.png">

Any information you can shed on how that error came to be would be helpful.
Thanks!

**Comment by lvca** [comment]
It looks like there is no space on the hard drive/ssd, that's why. Could you please check it?

**Comment by EricLin2004** [comment]
Yeah, I understand that was probably the issue, the VM we were running ran out of space... But is that enough to corrupt the database?

**Comment by lvca** [comment]
@laa do you have any idea why the check for the free space didn't work for @EricLin2004 ?

**Comment by laa** [comment]
@EricLin2004 could you send distribution of free space on your system now ?

**Comment by EricLin2004** [comment]
Sorry, @laa , not exactly sure what you're looking for, can you elaborate? Either here or you can contact me at eric@axiomzen.co as well.

**Comment by laa** [comment]
@EricLin2004 what I mean is following. What is free space available on all your devices, what are devices are used by OrientDB ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
