### ISSUE TITLE
skip/limit does not work for aggregation

### ISSUE THREAD

**Issue by facelessTT** [orientechnologies/orientdb#6634]
## OrientDB Version, operating system, or hardware.
2.2.7

## Operating System
- [ x] Linux

## Steps to reproduce the problem

limit does not work for aggregation
....
select list(id) from sometable where somefield = 'a' order by generated desc limit 2

expecting: only two elements will fit in result;
actual: all elements fit

**Comment by luigidellaquila** [comment]
Hi @facelessTT 

In your query, the LIMIT is applied to the result set, not to the list. 
The result set will always return a single record, so LIMIT 2 does not make much sense.
To limit the list size, you have to use a subquery:

```
select list(id) from (select id from sometable where somefield = 'a' order by generated desc limit 2)
```

I hope it helps

Thanks

Luigi
