### ISSUE TITLE
java.lang.NegativeArraySizeException thrown on vertices that were in orientdb recently

### ISSUE THREAD

**Issue by krl22785** [orientechnologies/orientdb#6638]
## OrientDB Version, operating system, or hardware.

v2.2
## Operating System

Linux
## Expected behavior and actual behavior

What is the likely cause of a java.lang.NegativeArraySizeException when querying a vertex in the following manner: 

select \* from #14:838

I am querying a few vertices directly and all of sudden I am getting this exception.  I suspect some of my data might be corrupted but wanted to see if you could provide some guidance here.  

Just a few days prior, these vertices were available.  I also realized that this exception is being thrown for a batch of vertices with sequential @RIDs.  Its about 100+ vertices.  

Any guidance?

**Comment by luigidellaquila** [comment]
Hi @krl22785 

How can I reproduce this issue? Do you have a database or a test case that I can use? 
(server logs - if any - will help as well)

Thanks

Luigi

**Comment by krl22785** [comment]
Hey @luigidellaquila 

I am not sure how to help you reproduce it.  Each time I try to query a batch of elements that are in a range, I get this exception.  When I look at the logs, I see this: 

2016-09-06 14:58:21:816 SEVER Internal server error:
java.lang.NegativeArraySizeException [ONetworkProtocolHttpDb]
2016-09-06 15:29:28:051 SEVER Internal server error:
java.lang.NegativeArraySizeException [ONetworkProtocolHttpDb]
2016-09-06 18:30:08:314 SEVER Internal server error:
java.lang.NegativeArraySizeException [ONetworkProtocolHttpDb]
2016-09-06 18:30:30:526 SEVER Internal server error:

**Comment by luigidellaquila** [comment]
Hi @krl22785 

Do you think it's possible to privately share your db? The query you are reporting is quite common, so the problem should be in the data

Thanks

Luigi

**Comment by krl22785** [comment]
I don't think I can share but this is what I have in my logs.  After a hard reboot, the logs threw this message.  This is data we already had in our database.  Should I reconsider restarting the database again?  

It appears each time I query for the records that had an "Error on retrieving..." message, it throws this java.lang.NegativeArraySizeException.  

Any guidance? 

$ANSI{green {db=DATABASE}} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:14809 (cluster: classA)
$ANSI{green {db=DATABASE}} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:14810 (cluster: classA)
$ANSI{green {db=DATABASE}} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:14811 (cluster: classA)

**Comment by laa** [comment]
@krl22785 what concrete version of 2.2 do you use could you specify ?

**Comment by krl22785** [comment]
@luigidellaquila  we are using orientdb 2.2.4

**Comment by laa** [comment]
@krl22785 that is what you should not to do in any case, 2.2.4 contains critical issue which may damage data. Please upgrade to latest one.

**Comment by krl22785** [comment]
@laa @luigidellaquila is that for both the community and enterprise versions?

**Comment by lvca** [comment]
@krl22785 did you upgrade and resolved this problem?

**Comment by yeoedward** [comment]
@lvca We tried upgrading and migrating an export of the data from before this error occurred but were unable to because of #6759. Do you think they could be related? i.e. some silent corruption already took place before, and only shows up during the import?

**Comment by yeoedward** [comment]
@lvca Incremental restore in 2.2.4 also does not work on our database backup: #6774. Not sure if all these import/export and backup/restore problems are related to data corruption?
