### ISSUE TITLE
Docker Command Example Is Missing a Dash

### ISSUE THREAD

**Issue by jjszucs** [orientechnologies/orientdb#6642]
## OrientDB Version, operating system, or hardware.
- v2.2.3

## Operating System
- [X] Linux
- [X] MacOSX
- [X] Windows
- [X] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

On the OrientDB installation page, the Docker command example is missing a dash before the "name" parameter. It should be "--name" not "-name."

## Steps to reproduce the problem

As documented:
```
$ docker run -d –name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=root orientdb:latest
docker: Error parsing reference: "–name" is not a valid repository/tag.
See 'docker run --help'.
```

Corrected:
```
$ docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=root orientdb:latest
[docker downloads, installs, and runs OrientDB properly]
```

**Comment by jjszucs** [comment]
I will fix this myself, now that I have figured out where the docs are on GitHub.

**Comment by robfrank** [comment]
done
