### ISSUE TITLE
deleting property's attribute "regexp"  does not work

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6648]
## OrientDB Version, operating system, or hardware.
- v2.2.8

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
attribute should be deleted when I use command:
**alter property test.prop regexp null**

## Steps to reproduce the problem

orientdb {db=test}> **create class test extends V**
Class created successfully. Total classes in database now: 12.

orientdb {db=test}> **create property test.prop string**
Property created successfully with id=1.

orientdb {db=test}> **alter property test.prop regexp '[a-z]'**
Property updated successfully.

orientdb {db=test}> **select expand(properties)  from ( select expand(classes) from metadata:schema) where name = 'test'**

+----+----+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+------+
|#   |name|type|globalId|mandatory|readonly|notNull|defaultValue|min |max |customFields|collate|description|regexp|
+----+----+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+------+
|0   |prop|7   |23      |false    |false   |false  |            |    |    |            |default|           **|[a-z]** |
+----+----+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+------+
1 item(s) found. Query executed in 0.004 sec(s).

orientdb {db=test}> **alter property test.prop regexp null**
Property updated successfully.

orientdb {db=test}> **select expand(properties)  from ( select expand(classes) from metadata:schema) where name = 'test'**
+----+----+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+------+
|#   |name|type|globalId|mandatory|readonly|notNull|defaultValue|min |max |customFields|collate|description|regexp|
+----+----+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+------+
|0   |prop|7   |23      |false    |false   |false  |            |    |    |            |default|           |**[a-z]** |
+----+----+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+------+
1 item(s) found. Query executed in 0.003 sec(s).

**Comment by smolinari** [comment]
Could it be, that it should only be "regex" and not "regexp"?

@luigidellaquila - the documentation is ambiguous, because the examples have "REGEXP", but the table with the supported attributes has "REGEX".

Scott

**Comment by Ivanov-Yuriy** [comment]
attribute with name "REGEX" does not work

orientdb {db=test}> **create property test.prop2 string**
Property created successfully with id=2.

orientdb {db=test}> **alter property test.prop2 regex '[a-z]'**
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command: Unknown property attribute 'REGEX'. Supported
ibutes are: [LINKEDTYPE, LINKEDCLASS, MIN, MAX, MANDATORY, NAME, NOTNULL, REGEXP, TYPE, CUSTOM, READONLY, COLLATE, DEFAULT, DESCRIPTION]
Command: ALTER PROPERTY test.prop2 regex '[a-z]'
---------------------------------^
        DB name="test"

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

I just pushed a fix on 2.2.x, it will be in next 2.2.11

Thanks

Luigi
