### ISSUE TITLE
Database created with Java 1.8 cannot be opened with java 1.7

### ISSUE THREAD

**Issue by nadestin** [orientechnologies/orientdb#6650]
## OrientDB Version, operating system, or hardware.
- v2.2.x

## Operating System
- [*] Linux
- [*] MacOSX
- [*] Windows
- [*] Other Unix
- [*] Other, name?  any

## Expected behavior and actual behavior
Expected:
Database created with same version of the OrientDB should open without problem with any supported JRE.

Actual:
If Database is created using Java 1.8 then Passwords in the OUser Table will be hashed using  algorithm 
PBKDF2_SHA256_ALGORITHM. This Algorithm is not supported by Java 1.7. 
As result this database cannot be opened by any application running under Java 1.7 JRE.

Either 2.2 should not be supported with Java 1.7 or default hash algorithm should be changed back to the PBKDF2_ALGORITHM which works on all supported platforms.

## Steps to reproduce the problem
1. Set JAVA_HOME to point to JRE/JDK 1.8.
2. Start OrientDb console and create new database: "create database plocal:mydbpath"
3. Exit from the console.
4. Set JAVA_HOME to point to JRE/JDK 1.7.
5. Start OrientDB console and try to open datase: "connect plocal:mydbpath admin admin"
6. You will get an Exception:
Connecting to database [plocal:c:/temp/db/test8] with user 'admin'...
2016-09-02 12:52:56:803 SEVER {db=mydbpath} The password hash algorithm is not supported: PBKDF2WithHmacSHA256 [OSecurityManager]
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'mydbpath'
        DB name="mydbpath"

**Comment by lvca** [comment]
@nadestin usually users don't go back to a previous Java version. Why you did it? Anyway, you could export your database and reimport it in one created with Java7.

Or you can change the configuration at database creation: `-Dsecurity.userPasswordDefaultAlgorithm=X` where X is the algorithm you want to use. By default we use `PBKDF2WithHmacSHA256` because it's much more secure than `PBKDF2WithHmacSHA1`, but you can wire PBKDF2WithHmacSHA256 so you don't have this problem anymore.

**Comment by nadestin** [comment]
I have already found workaround. The problem is that that Database created with Java 8 is not compatible with Java 7 and it is not even mentioned in the documentation.
Since Schema operations are painfully slow on OrientDB, we distribute empty database with our application and when end user happens to have Java 1.7 installed we got a problem.

You should have mentioned in the Documentation that if Database needs to be compatible to 1.7 and 1.8 at the same time, then Global configuration should be adjusted before opening/creating database like this:
OGlobalConfiguration.SECURITY_USER_PASSWORD_DEFAULT_ALGORITHM
    .setValue(OSecurityManager.PBKDF2_ALGORITHM);

I belive that can save hours of debugging to other users. I cannot change the manual, could you do it, please.
