### ISSUE TITLE
OPartitionedDatabasePool doesn't allow to use load balancing

### ISSUE THREAD

**Issue by syzdykov** [orientechnologies/orientdb#6652]
## OrientDB Version, operating system, or hardware.
- v2.2 
## Operating System
- MacOSX
## Expected behavior and actual behavior

OPartitionedDatabasePool doesn't allow to use load balancing. I can set property OStorageRemote.PARAM_CONNECTION_STRATEGY  to ODatabaseDocumentTx object after getting from pool, but it will not affect on load balancing behaviour.
When I have several database nodes and using OPartitionedDatabasePool all requests are serviced only by one node.
Expected behavior: we need a way to set PARAM_CONNECTION_STRATEGY when we use OPartitionedDatabasePool

**Comment by laa** [comment]
That is remote storage responsibility, not pool responsibility. Assigned to @tglman .

**Comment by tglman** [comment]
Hi,

We included the `setProperty` on the pool since the 2.2.6 so this is actually already fixed.

Regards
