### ISSUE TITLE
custom field is saved wrong when I am writing string with backslash and apostrophe

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6655]
## OrientDB Version, operating system, or hardware.
- v2.2.8

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I expect string without backslash
the same behaviour when I save property's custom attributes

## Steps to reproduce the problem
orientdb {db=testdb}> **create class test extends V**
Class created successfully. Total classes in database now: 11.

orientdb {db=testdb}> **alter class test custom `cField`='a\'sd'**
Class updated successfully.

orientdb {db=testdb}> **select customFields.cField from ( select expand(classes) from metadata:schema) where name = 'test'**
+----+------------+
|#   |customFields|
+----+------------+
|0   |**a\'sd**       |
+----+------------+
1 item(s) found. Query executed in 0.004 sec(s).

**Comment by lvca** [comment]
@Ivanov-Yuriy Which version? 2.6.8 doesn't exist yet :-)

**Comment by Ivanov-Yuriy** [comment]
2.2.8  :)
sorry, my fault

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

I just pushed a fix on 2.2.x. The fix will be released with next 2.2.11

Thanks

Luigi
