### ISSUE TITLE
expand function fail

### ISSUE THREAD

**Issue by rafikalid** [orientechnologies/orientdb#6656]
## OrientDB Version, operating system, or hardware.

Orient version: 2.2.8 (last)
## Operating System
- Windows 10
## query

```
select
  expand($a2)
from
  wfolder
let
    $a=out('RFolderContainsItem'),
    $a2=(
      select
        *,
        $io2 as owner,
        $c2 as comments
      from
        $a
      let
        $io=in('RUserOwnFolderItem'),
        $io2=(select fullName, @rid.asString() as _id from $io),
        $c=inE('RUserCommentVignette'),
        $c2=(
          select date, value, @rid.asString() as _id, $o2 as owner from $c
          let $o=out,
          $o2=(select fullName, @rid.asString() as _id from $o)
        )
      )
where @rid=?
```
## Expected behavior and actual behavior

must return wanted fields

when i replace `expand($a2)` by `$a2.exclude('@rid')` it works perfectly, but without returning the @rid :/
of curse when i just use `@$a2` it returns the ids without any other information

**Comment by rafikalid** [comment]
when i use `expand` it returns inappropriate fields (last inserted one)

**Comment by luigidellaquila** [comment]
Hi @rafikalid 

Is it possible to have a running test that shows the problem or a db where to replicate it?

Thanks

Luigi

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
