### ISSUE TITLE
java.lang.IllegalArgumentException: Cluster segment #-2 does not exist in database

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6663]
## OrientDB Version, operating system, or hardware.

- v2.2.8

## Operating System
 Linux

## Steps to reproduce the problem

begin
delete from (select content from  33:740)
commit 

but if i do

delete from (select content from  33:740)

works.

**Comment by laa** [comment]
@publicocean0 could you provide more details, specifically  I am interested in full stack trace of the exception.

**Comment by publicocean0** [comment]
in the server log i see Internal server error:
java.lang.IllegalArgumentException: Cluster segment #-2 does not exist in database

**Comment by laa** [comment]
Is it reproducible ? Could you send us database so we may do the same ?

**Comment by publicocean0** [comment]
hi , the entire database is not possible. i will see if i can find additional infos for helping you

**Comment by publicocean0** [comment]
found new infos.


 select @rid from (select data[0].link from #36:628)
```
+----+-----+
|#   |rid  |
+----+-----+
|0   |#-2:0|
+----+-----+
```

where data is a embedded object

**Comment by laa** [comment]
It looks like data serialization issue, @tglman could you look on it ?

**Comment by publicocean0** [comment]
script is executed in server side

**Comment by tglman** [comment]
hi @laa, @publicocean0 

this is normal because the inner query produce a projection that has negative rids, you should instead do: `select @rid from (select expand(data[0].link) from #36:628)`

for the original problem the solution is `delete from (select content.@rid from 33:740)`

Regards

**Comment by tglman** [comment]
hi @laa, @publicocean0 

this is normal because the inner query produce a projection that has negative rids, you should instead do: `select @rid from (select expand(data[0].link) from #36:628)`

for the original problem the solution is `delete from (select content.@rid from 33:740)`

Regards

**Comment by publicocean0** [comment]
i consider it solved. Thanks
