### ISSUE TITLE
Batch script from console fails

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientdb#6665]
## OrientDB Version, operating system, or hardware.
- v2.2.8

## Operating System
- [x] Linux - ubuntu 14.04
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

- Expected: Run the sql script from console
- Actual: Get error

## Steps to reproduce the problem

1.- Go to the console: $ORIENTDB_HOME/bin/console.sh
2.- Connect to a database: connect remote:host/databaseName user pass
3.- Try to execute a sql scritp: script sql .... whatever

Example, in my case this is happening:
![seleccion_133](https://cloud.githubusercontent.com/assets/521303/18305794/bd481368-74ae-11e6-9c51-3c536dcb8a17.png)

And my config:
![seleccion_134](https://cloud.githubusercontent.com/assets/521303/18306270/ae545bf8-74b0-11e6-8620-74a968a8265c.png)

And this works in 2.1.x versions, here it is the example that i found:
http://stackoverflow.com/questions/27149179/how-do-i-execute-an-orient-db-batch-script

**Comment by luigidellaquila** [comment]
Hi @alexmm11 

I just pushed a fix on 2.2.x and develop

Thanks

Luigi
