### ISSUE TITLE
Spurious "Database is closed" errors

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#6668]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[x] .15[x] .14[x] .13[x] .12[x] .11[x] .10[x] .9[x] .8[x] .7[x] .6[x] .5[x] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .8[x] .rc1[ ] .beta2[ ] .beta1[ ]
## Operating System
- [x] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

Quite frequently, OrientDB will refuse to execute a command on an otherwise-active connection to a database with an error saying `Database '<storage_type>:<db_name>' is closed` even though the network connection was not interrupted (e.g. the database is on the local machine) and the client code did not attempt to close the database. This unfortunate bug has existed at least as early as 2.1.5 (when I started using OrientDB) and still exists in 2.2.8 today.

The types of commands that cause this vary -- SQL queries, database imports/exports, and so on. Here is a stack trace captured from such an error from a database import operation that occurs as part of our test suite:

```
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'memory:test_db' is closed
    DB name="test_db"
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:3041)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:805)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:103)
    at com.orientechnologies.orient.core.db.tool.ODatabaseImport.removeDefaultNonSecurityClasses(ODatabaseImport.java:626)
    at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:396)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.importDatabase(ONetworkProtocolBinary.java:2916)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:635)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:320)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:196)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

Given the non-deterministic nature of the error, and the fact that multiple completely unrelated command types that cause it, I believe this may be some kind of race condition.
## Steps to reproduce the problem

This failure happens non-deterministically, and I have not been able to consistently reproduce it. However, it happens reasonably frequently when the database is under load, and should be reproducible with no more than an hour or two of random load testing using the newest `pyorient` version.

**Comment by tglman** [comment]
hi @obi1kenobi,

The reason of this could be that the session is expired or the underline database has been dropped and eventually ricreated.

Regards

**Comment by obi1kenobi** [comment]
The database does not get dropped in my workload, so it must be the session as you mention. Is there a way to refresh the session and prevent it from expiring? Alternatively, is there a way to control the session length via some configuration options?

**Comment by natemurthy** [comment]
I have also experienced this problem using OrientDB 2.2.8 and as early as OrientDB 2.1.4 when using the `orientdb-graphdb` Java client.

**Comment by natemurthy** [comment]
Here's another related ticket: https://github.com/orientechnologies/orientdb/issues/6526

**Comment by lvca** [comment]
@obi1kenobi do you see this bug also in 2.2.10? @tglman could be related to the expiration of the token bug @SDIPro encountered 2 days ago?

**Comment by obi1kenobi** [comment]
Unfortunately I only see this bug on my company's servers, and seldom locally, so I won't be able to answer that until we've had a chance to upgrade. The next upgrade will probably be around when 2.2.11 is released.

**Comment by obi1kenobi** [comment]
With 2.2.12, this bug (or maybe a related one) is surfacing as pyorient errors like this one: `PyOrientConnectionException('Server seems to have went down',)` raised from here:
https://github.com/mogui/pyorient/blob/b67bf94636590bdd23fc7e67fdaeb2e155db7e36/pyorient/orient.py#L147

**Comment by tglman** [comment]
hi @obi1kenobi,

Did you have chance to upgrate to a more recent version? we fixed few connection related issues.

Regards

**Comment by tglman** [comment]
hi @obi1kenobi,

Ok, i'll close this then.

Regards
