### ISSUE TITLE
linkeset does not save correct order of records

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6669]
## OrientDB Version, operating system, or hardware.
- v2.2.8

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
order of records must be the same as I was writing in the database

## Steps to reproduce the problem
orientdb {db=test}> **create class test extends V**
Class created successfully. Total classes in database now: 12.

orientdb {db=test}> **create property test.ts linkset**
Property created successfully with id=1.

orientdb {db=test}> **insert into test set ts= [#5:0,#5:3,#5:1]**
Inserted record 'test#21:0{ts:[3]} v1' in 0,002000 sec(s).

orientdb {db=test}> **select from #21:0**
+----+-----+------+----------------+
|#   |@RID |@CLASS|ts              |
+----+-----+------+----------------+
|0   |#21:0|test  |**[#5:3,#5:1,#5:0]**|
+----+-----+------+----------------+
1 item(s) found. Query executed in 0.002 sec(s).

**Comment by StarpTech** [comment]
I had the same issue. The statement by orientdb is that the order is not garantiert.

**Comment by Ivanov-Yuriy** [comment]
it is not good...
the array always has to guarantee right order

**Comment by StarpTech** [comment]
@Ivanov-Yuriy  exactly.

**Comment by smolinari** [comment]
> the array always has to guarantee right order

Why? I am not saying you are wrong, but a bit of good explanation about the reasoning might help the ODB team understand your problem with the different ordering of the links.

Scott

**Comment by StarpTech** [comment]
Correct me: A set does not guarantee the order by definition. Its no array data structure.

**Comment by maggiolo00** [comment]
@Ivanov-Yuriy 

Link Set does not guarantee order.
You should use Link List

See here
http://orientdb.com/docs/2.2/Concepts.html#1n-and-nn-referenced-relationships

**Comment by Ivanov-Yuriy** [comment]
Ok.
I understand why you did that,
but as for me if set had my order, it would be very well
because now
I have to create EMBEDDEDLIST with properties order and link instead only LINKESET
