### ISSUE TITLE
error when I try create record with "CONTENT" style and property type:EMBEDDEDLIST linkedtype:DECIMAL

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6670]
## OrientDB Version, operating system, or hardware.
- v2.2.8

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Steps to reproduce the problem
orientdb {db=test}> **create class test extends V**
Class created successfully. Total classes in database now: 12.

orientdb {db=test}> **create property test.ed embeddedlist decimal**
Property created successfully with id=1.

orientdb {db=test}> **insert into test set ed= [5,null,5]**
Inserted record 'test#22:1{ed:[3]} v1' in 0,002000 sec(s).

orientdb {db=test}> **insert into test CONTENT {"ed": [5,null,5]}**
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #23:-1
        DB name="test"
        DB name="test"
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #23
        DB name="test"
Error: java.lang.ClassCastException

orientdb {db=test}> **create property test.ef embeddedlist float**
Property created successfully with id=3.

orientdb {db=test}> **insert into test CONTENT {"ef": [5,null,5]}**
Inserted record 'test#22:2{ef:[3]} v1' in 0,002000 sec(s).

**Comment by Ivanov-Yuriy** [comment]
the same behaviour with properties date and datetime

orientdb {db=test}> **create property test.edate embeddedlist date**
Property created successfully with id=4.

orientdb {db=test}> **insert into test CONTENT {"edate": ["2016-05-01"]}**
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #22:-1
        DB name="test"
        DB name="test"
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #22
        DB name="test"
Error: java.lang.ClassCastException

orientdb {db=test}> **create property test.edt embeddedlist datetime**
Property created successfully with id=5.

orientdb {db=test}> **insert into test CONTENT {"edt": ["2016-05-01 12:30:30"]}**
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #23:-1
        DB name="test"
        DB name="test"
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #23
        DB name="test"
Error: java.lang.ClassCastException

**Comment by luigidellaquila** [comment]
Hi @Ivanov-Yuriy 

I just pushed a fix on 2.2.x branch (thanks @tglman). The fix will be available in 2.2.12

Thanks

Luigi
