### ISSUE TITLE
distributed setup does not find new nodes from other subnets in non-multicast, "tcp-ip" based method

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6671]
## OrientDB Version, operating system, or hardware.
- v2.2.7

## Operating System
- [x] Linux

## Expected behavior and actual behavior
Still struggling with my first attempt to get 6 servers working together, which are installed in 2 different subnets.
The default "hazelcast.xml" comes with "multicast" based discovery of other server nodes, a mechanism which works only in a single subnet.
So I browsed for docs about Hazelcast configs, and found that another method can be configured, the "tcp-ip" way of specifying explicitly IP-addresses of other nodes.
Dunnow if OrientDB supports this alternative, so I gave it a try (in "hazelcast.xml") on a server node in a remote subnet with IP 10.49.69.62 :
```
 <network>
                <port auto-increment="true">2434</port>
                <join>
                        <multicast enabled="false">
                                <multicast-group>235.1.1.1</multicast-group>
                                <multicast-port>2434</multicast-port>
                        </multicast>
                        <tcp-ip enabled="true">
                            <required-member>10.49.69.62</required-member>
                            <member>10.49.69.62</member>
                            <members> 10.49.69.190,10.49.69.189,10.49.69.188, 10.49.69.60,10.49.69.61,10.49.69.62 </members>
                        </tcp-ip>
                </join>
        </network>
```
Have this server started (with "dserver.sh"), but it does not seem to connect to any of the already running nodes 10.49.69.188-190

-> does ODB support this method to connect with servers in another subnet (multicast won't work)?
-> is this the correct config ?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Yes, OrientDB supports tcp-ip for node discovery and the configuration and it seems to be correct. Typically I don't use `<required-member>`, but I don't know if that can be the problem

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila  thx for the reply. I found that an example on the web without "<required-member>" and just a list of "<member>" items , so implemented that on the extra node in the remote subnet.
I saw in its logs that it correctly attempted now a connection with one of the running nodes in the local subnet. But on that 'local' node the logs mentioned that it rejected such connection attempts, because there the "hazelcast.xml" did contain the "multicast" method only.

So I distributed on all nodes that "hazelcast.xml" which has the "multicast" method disabled, and the "tcp-ip" method enabled. Now the connections are accepted fine, and new nodes join happily.

This is the "hazelcast.xml" section for the joining : 

                <join>
                        <multicast enabled="false">
                                <multicast-group>235.1.1.1</multicast-group>
                                <multicast-port>2434</multicast-port>
                        </multicast>
                        <tcp-ip enabled="true">
                                <member>10.49.69.190</member>
                                <member>10.49.69.189</member>
                                <member>10.49.69.188</member>
                                <member>10.49.69.60</member>
                                <member>10.49.69.61</member>
                                <member>10.49.69.62</member>
                        </tcp-ip>
                </join>

**Comment by luigidellaquila** [comment]
Ah, sure, I didn't get that the other nodes had a different configuration, that's the key to make it work.

Thanks for the clarification, I'm closing this issue then

Thanks

Luigi
