### ISSUE TITLE
Deleting raw records

### ISSUE THREAD

**Issue by sowee15** [orientechnologies/orientdb#6672]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[x] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I created a raw record using the TX_COMMIT operation of the remote protocol. I can successfully load the record back using the LOAD_RECORD operation. Now I am trying to delete this record in a transaction, remotely. To do so, I am using a SQL batch.

In the batch, I tried:
delete from <rid> -> does not work
delete from <cluster> where @rid = <rid> -> does not work
truncate record <rid> -> works

Why would the delete not work? My problem is that I need to delete multiple raw records and I  think I can't do that in a SQL batch using truncate record. But I could using the delete command, if it worked.

How can I delete multiple raw records in a SQL batch? Thanks.

**Comment by luigidellaquila** [comment]
Hi @sowee15 

This issue is already fixed, I just added this test case to 2.2.x branch and it works fine

```java
	@Test public void testBinaryClusterDelete() {
		database.command(new OCommandSQL("create blob cluster binarycluster")).execute();
		database.reload();
		OBlob bytes = new ORecordBytes(new byte[] { 1, 2, 3 });
		database.save(bytes, "binarycluster");

		List<OIdentifiable> result = database.query(new OSQLSynchQuery<OIdentifiable>("select from cluster:binarycluster"));

		Assert.assertEquals(result.size(), 1);
		ORID rid = result.get(0).getIdentity();

		database.command(new OCommandSQL("delete from "+rid)).execute();

		result = database.query(new OSQLSynchQuery<OIdentifiable>("select from cluster:binarycluster"));

		Assert.assertEquals(result.size(), 0);
	}
```

So you can just use

```sql
DELETE FROM <rid>
```
Thanks

Luigi
