### ISSUE TITLE
java.lang.NegativeArraySizeException [ONetworkProtocolHttpDb] After Restarting OrientDB

### ISSUE THREAD

**Issue by krl22785** [orientechnologies/orientdb#6673]
Following up on my message from last week.  After restarting our database, I received the following messages during restarting our database:

$ANSI{green {db=DATABASE}} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:14809 (cluster: classA)

$ANSI{green {db=DATABASE}} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:14810 (cluster: classA)

$ANSI{green {db=DATABASE}} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:14811 (cluster: classA)

It appears some data is either lost or not indexed properly because I see the following exception when I try to query one of those records skipped: 

2016-09-06 14:58:21:816 SEVER Internal server error:
java.lang.NegativeArraySizeException [ONetworkProtocolHttpDb]

2016-09-06 15:29:28:051 SEVER Internal server error:
java.lang.NegativeArraySizeException [ONetworkProtocolHttpDb]

2016-09-06 18:30:08:314 SEVER Internal server error:
java.lang.NegativeArraySizeException [ONetworkProtocolHttpDb]

Also, when I try to query for a specific element based on the index value, I get the wrong vertex: 

Here is example: 

SQL Query: 
select from VERTEXCLASS where attribute = "valueA"

I get a vertex with attribute equal to something completely different and with a different @RID from the original vertex. 

result: 
attribute= "valueZ"

**Comment by laa** [comment]
Hi, @krl22785 which message do you mean ? What version do you use ?

**Comment by krl22785** [comment]
I am using Orientdb-Enterprise 2.2.4.

**Comment by krl22785** [comment]
@laa you commented that this version has critical issues.  Can you elaborate?

**Comment by laa** [comment]
Hi @krl22785 , sorry I can not elaborate more because a bug is quite technical. In general, during regular work of database data may be corrupted,  to fix such data corruption I recommend you to export data in JSON and then import them back.

**Comment by lvca** [comment]
@laa was this a bug of 2.2.4 and we fixed in further releases, right? Is this what you mean?

**Comment by laa** [comment]
@lvca Hi Luca, you are right. You should migrate to latest 2.2.x version, which is 2.2.1

**Comment by yeoedward** [comment]
@laa Can you please post links to any issue trackers/pull requests related to this critical issue in 2.2.4? Some more context would be very helpful.

**Comment by laa** [comment]
@yeoedward Sure. https://github.com/orientechnologies/orientdb/issues/6234 .

**Comment by laa** [comment]
closing issue because it is already fixed
