### ISSUE TITLE
Choosing between Python and Java for orientDB load

### ISSUE THREAD

**Issue by rmanzar** [orientechnologies/orientdb#6674]
I have to write an ETL process (fairly complex) and I am new to both Java and Python but Python looked simpler and shorter learning curve, I need some pros and cons of choosing between Java and Python for writing ETL for loading data in OrientDB. I would appreciate a quick response on this.
Thanks
Rashid

**Comment by luigidellaquila** [comment]
Hi @rmanzar 

IMHO the first thing you have to take into consideration is your/your team language skills. If you are more confident with Python then you can go with it.
Anyway, with Java you will have at least one big advantage: you can use OrientDB in embedded mode, having ~10x performance. For and ETL this can be important, especially if it's a one-shot import.
In general, the Java API is the native OrientDB API, so you can expect it to be more polished

Thanks

Luigi

**Comment by rmanzar** [comment]
Thanks Luigi, I see your point. Rashid

**Comment by anber500** [comment]
With python you are severely limited. There are not many Python friendly options out there.

The two I have tried are **pyorient**, which doesn't work with distributed databases (and who know what else), and the **Bulbflow** project which is a mess. The switch over from TinkerPop 2 to TinkerPop 3 has make support blueprints limited and in most cases the support is simply not there. If you start looking at Rexter, you'll quickly start looking for an alternative DB's to use instead.

Most Python libraries also haven't seen any updates in the last 2 years. Except for pyorient which is the best option, but doesn't work for all use cases.

Getting support for Python is really difficult.

If you are starting out, best go with an option like Java. You'll get better support from OrientDB if you do.

**Comment by StarpTech** [comment]
@anber500
As long as orientdb don't overhaul the binary protocol by a industrie standard I can only recommend orientjs but also the most active driver has lots of limitations. I really hope that this will be planned for the next version so implementing new clients will be an easy way.

**Comment by rmanzar** [comment]
Thank you so much for the detailed answer and limitation, I have decide to stick with java.
