### ISSUE TITLE
Every Lucene index starts thread 

### ISSUE THREAD

**Issue by antonzherdev** [orientechnologies/orientdb#6675]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .8[X] .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [X] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behaviour
Every lucene index will create a thread during startup. It's very expensive and takes time. If I have many indexes I will have giant amount of threads. If I have one index per tenant it's too expensive. I have currently 700. These threads are not working almost all time but consumes resources. 

I would expect that I have control on how many threads are created. 

It happens due to ControlledRealTimeReopenThread (which inherits Thread) is used in OLuceneIndexEngineAbstract. 

Additionally all indexes are loaded on startup. I suppose it would be better to do it lazily and keep indexes in memory which are in use only and release others.

## Steps to reproduce the problem
Create few lucene indexes

**Comment by maggiolo00** [comment]
hi @antonzherdev 

that ControlledRealTimeReopenThread thread is needed for a fast near realtime indexing. We will try to replace it with something less expensive since for OrientDB 3.0 we will use Lucene >= 6.1 that should not contain anymore ControlledRealTimeReopenThread

**Comment by antonzherdev** [comment]
Hi @maggiolo00,

Yes, I understand the reason why it's there but for thread consumes memory for the stack and it's system memory and I cannot limit the consumption and the service can be killed by OS. I can reduce the stack size but not too much. These threads are almost always in sleep, this means that it's a wasted memory. 

Additionally creating of these threads taking time during initialisation of database. In my case it can take up to a minute to startup only due to these indexes.

So it would be nice if you could consider to change it in OrientDB 3.0 and get rid of the threads.

Thanks!
