### ISSUE TITLE
But with linkmap after DB migration

### ISSUE THREAD

**Issue by hadson19** [orientechnologies/orientdb#6676]
After import database the links on Linkmap property (type also linkmap) become null.

So
before
  {"4gc":"#54:3"}
   Under vertex #54:3 we have correct record.

after:

   {"4gc":null}

Both machine has version 2.2.4.

**Comment by maggiolo00** [comment]
@hadson19 

how did you migrate the db?

From which version?

**Comment by lvca** [comment]
Could it possible that record `#54:3` didn't exist?

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
