### ISSUE TITLE
Cannot index record #62:0: found duplicated key 'null' in index 'v_user.ID' previously assigned to the record #57:0

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6681]
## OrientDB Version, operating system, or hardware.
- v2.2.9

## Operating System
- [ X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

This error never happened in prior versions of Orient. To my knowledge, we have not inserted duplicate key and I'm not clear on how the key we are trying to insert is 'null'. This error occurs on the line:
	Vertex vertex = graph.addVertex(type.getObjectClassNameId());

2016-09-11 18:44:54 s.c.s.a.c.e.ExchangeClientConnection [ERROR] failed to write tree:Cannot index record #62:0: found duplicated key 'null' in index 'v_user.ID' previously assigned to the record #57:0
	DB name="archiva$smpl"
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #62:0: found duplicated key 'null' in index 'v_user.ID' previously assigned to the record #57:0
	DB name="archiva$smpl"
	at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:64)
	at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:34)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:905)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:737)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:711)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:1520)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1484)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:566)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2733)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2703)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:175)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabase.addVertex(BluePrintDatabase.java:35

**Comment by jamieb22** [comment]
I see now, Orient is rejecting the creation of the null record. Should we be calling graph.addTemporaryVertex(..) instead?

**Comment by vtliem** [comment]
The same issue here!
In document: 
> Indexes by default ignore null values. For such reason queries against NULL value that use indexes return no entries.

So I create a class `GroupChatSession` with `linkid` field for group chat session which has reference.
Old orientdb (2.1.x) had no issue but when I updated to OrientDB 2.2.8 (and now 2.2.9), when I create new group chat session ( without reference), a `ORecordDuplicatedException` is raised.
How to ignore  `null` key as before?

**Comment by laa** [comment]
@jamieb22 the reason is that by default null values are indexed so for you index you need to set ignoreNullValues to true for this index.

**Comment by jamieb22** [comment]
How does one set this ignoreNullValues  value since we are using auto indexes?

**Comment by jamieb22** [comment]
Why was this default value changed?

**Comment by valenpo** [comment]
So, if a class has a predefined indexed fields ID, EMAIL, NAME and all of indexes are uniq, when I try to create the new vertex I need to know all those values (ID, EMAIL, NAME)???

``
Vertex vertex = graph.addVertex("class:user", "EMAIL", "some@email.com");
graph.commit();
``

Because some times you know only one off all values that should be indexes. Is it possible to insert only one value? And how to specify ignoreNullValues? 

Regards.

**Comment by valenpo** [comment]
Is it possible to update NULL property like this for lower case

``
OrientVertexType .getProperty(fieldName).setCollate(new OCaseInsensitiveCollate());
``

**Comment by laa** [comment]
Hi, @valenpo , about your case. You need to know them before committing  of data. If that is not your case, could you show me how you did you create index and I will show you how to add this parameter.

**Comment by valenpo** [comment]
Hi, @laa, thanks for response. 

I'm already use such method when create the scheme and it solve a problem. 

``
for (OIndex<?> oIndex : graph.getVertexType(type.getClassName()).getIndexes()) {
	oIndex.getDefinition().setNullValuesIgnored(true);
}
``

Thanks

**Comment by laa** [comment]
@valenpo cool ))

**Comment by benjaminbillet** [comment]
Hi,
Is this problem solved in 2.2.10? I still have the issue, even with the trick given by @valenpo 


For testing purpose, here is a java snippet. It creates a single vertex type with a single property and tries to create three nodes (two of them, without the property). It crashes with OrientDB 2.2.10:

```
OrientGraphNoTx graph = ...

OrientVertexType type = graph.createVertexType("Test");
OProperty property = type.createProperty("aProperty", OType.STRING)
		.setMandatory(false)
		.setReadonly(false)
		.setNotNull(false);

List<Parameter<String, String>> parameters = Arrays.asList(
		new Parameter<>("type", OClass.INDEX_TYPE.UNIQUE.name()),
		new Parameter<>("class", type.getName()));

graph.createKeyIndex(property.getName(), Vertex.class, parameters.toArray(new Parameter[0]));

for (OIndex<?> oIndex : graph.getVertexType(type.getName()).getIndexes()) {
	oIndex.getDefinition().setNullValuesIgnored(true);
}

graph.addVertex("class:" + type.getName());
graph.addVertex("class:" + type.getName(), "aProperty", "aString");
graph.addVertex("class:" + type.getName());
```

`Exception in thread "main" com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Test: found duplicated key 'null' in index 'Test.aProperty' previously assigned to the record #17:0`

Am I missing something?

**Comment by laa** [comment]
@benjaminbillet I suppose that depends on how you use an index. The way which works on 100% is a creation of an index with metadata which I provided above.

**Comment by benjaminbillet** [comment]
@laa Thanks for your response, but I'm not sure to understand what you mean by "creation of an index with metadata which I provided above". Which message are you referring to? 

What is the best solution to create a key index with ignoreNullValues using the Java API, given that the indexed property is defined as optional (see the java code in my previous message)? I tried the solution given by @valenpo, but it didn't work. So maybe I'm missing something.

As a workaround, I decided to use a non-unique index instead of a unique index. But, in my opinion, this is not a good long-term solution. Given that this issue is closed, I would like to know in which future version the fix will be released. I saw that robfrank modified the milestone to 2.2.10, but I still have the problem with 2.2.10.

Thanks

**Comment by laa** [comment]
Hi @benjaminbillet , even if you work from Java I think the best option still to issue SQL command to create an index and provide ignoreNullValues metadata. As in the last example http://orientdb.com/docs/last/SQL-Create-Index.html

**Comment by benjaminbillet** [comment]
Hi @laa, 
Ok, it's clear now. I will use this as a solution. 

However, in terms of API, I think the best way to do this would be to have a Parameter for "ignoreNullValues", e.g.:
```java
Parameter[] parameters = new Parameter[] {
        new Parameter<>("ignoreNullValues", "true"),
        new Parameter<>("type", OClass.INDEX_TYPE.UNIQUE.name ()),
        new Parameter<>("class", "SomeType")
}
graph.createKeyIndex("someProperty", Vertex.class, parameters);
```
Blueprints specifically introduced the [Parameter ](http://www.tinkerpop.com/docs/javadocs/blueprints/2.5.0/com/tinkerpop/blueprints/Parameter.html) class for the purpose of setting implementation-specific parameters. 

Do you want me to create a new issue for this? It could be considered as a future enhancement.

**Comment by laa** [comment]
@benjaminbillet Yes I agree )) Could you create issue for that ?

**Comment by benjaminbillet** [comment]
@laa Done #6746.
Thanks a lot.
