### ISSUE TITLE
Console.bat error creating database

### ISSUE THREAD

**Issue by AubryLegrand** [orientechnologies/orientdb#6683]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[x] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Hi, I have this error when i try to create a new database with console.bat

`Error: java.lang.NoSuchMethodError: com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILcom/orientechnologies/orient/core/storage/cache/OReadCache;)V`

The command : `CREATE DATABASE plocal:../databases/sys root Password plocal DOCUMENT`

Version used : 2.2.9

Thanks

**Comment by AubryLegrand** [comment]
I found the problem, i had some jar in "plugins" folder since 2.2 version. I deleted them and it solves the issue.

**Comment by maggiolo00** [comment]
@AubryLegrand 

cool!
