### ISSUE TITLE
HA: allow overriding OLocalClusterStrategy

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6689]
Today, when OrientDB runs in HA mode, the cluster strategy is always overwritten to be `OLocalClusterStrategy`, but it would be nice having a way to inject a custom strategy.

**Comment by smolinari** [comment]
If you touch this code, you could theoretically also start to refactor "cluster" for "shard" for 3.0 too, right? 

`OLocalShardStrategy`

:stuck_out_tongue_winking_eye:

I know, I know. It is a lot of work......but still. :smile: 

Scott

**Comment by lvca** [comment]
Fixed. Now the strategy used remains also in distributed. The only thing that changes when running in distributed is the cluster Ids of the class: they are filtered by local cluster ids only.
