### ISSUE TITLE
insert ... from select error

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6693]
## OrientDB Version, operating system, or hardware.

- v2.2.8

## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
problem for copying chunks (the select bottom is a example)

 insert into cluster:3 from (select from cluster:3 limit 3)

Error: com.orientechnologies.orient.core.exception.OStorageException: Cluster 3 does not exist in database

why doesnt exist?

**Comment by laa** [comment]
Hi @publicocean0 , information which is contained inside of issue is not very useful. We have neither full stack trace, nor steps to reproduce an issue, nor data to reproduce the problem. Could you provide some of this information?

**Comment by publicocean0** [comment]
error is executing console or orientdb ide. i can t see any stack in output. The error is reproducible executing simply the query above

**Comment by laa** [comment]
@publicocean0 do you work with database using remote connection ?

**Comment by publicocean0** [comment]
yes

**Comment by laa** [comment]
@publicocean0 could  you check server log files and find full stack trace of exception which you mention ?

**Comment by publicocean0** [comment]
no error is produced in log. It is a application error not a exception.

**Comment by laa** [comment]
@publicocean0 I have more questions by cluster "3" do you mean a name of the cluster or cluster Id ?

**Comment by laa** [comment]
```insert into cluster: ``` command supports only cluster name. @luigidellaquila could you suggest how to resolve given issue ?

**Comment by publicocean0** [comment]
yes :) i m open to your suggestions

**Comment by luigidellaquila** [comment]
Checking it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi guys, 

It was a bug, more or less. The cluster ID was just not supported (the parser supposed to always find a cluster name).
I just fixed it, the fix is in 2.2.x branch and it will be released with 2.2.11

Thanks

Luigi
