### ISSUE TITLE
Classes lose custom fields after import / export operations

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6695]
Hi guys
I wrote to you about this bug before [https://github.com/orientechnologies/orientdb/issues/4272](https://github.com/orientechnologies/orientdb/issues/4272)
and it does not work again
## OrientDB Version, operating system, or hardware.
- v2.2.9 

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
custom fields in classes should remain in their places
## Steps to reproduce the problem
orientdb> **create database plocal:../databases/dbt admin admin**
Creating database [plocal:../databases/dbt] using the storage type [plocal]...
Database created successfully.

orientdb {db=dbt}> **create class test extends V**
Class created successfully. Total classes in database now: 11.

orientdb {db=dbt}> **create property test.st string**
Property created successfully with id=1.

orientdb {db=dbt}> **alter class test custom `custom`='абвгд'**
Class updated successfully.

orientdb {db=dbt}> **alter class test custom `custom1`=123**
Class updated successfully.

orientdb {db=dbt}> **alter property test.st custom `customP`=123**
Property updated successfully.

orientdb {db=dbt}> **alter property test.st custom `customP1`='абвг'**
Property updated successfully.

orientdb {db=dbt}> **select customFields  from ( select expand(classes) from metadata:schema) where name = 'test'**
+----+---------------------------+
|#   |customFields               |
+----+---------------------------+
|0   |{custom=абвг, custom1=123}|
+----+---------------------------+
1 item(s) found. Query executed in 0.01 sec(s).

orientdb {db=dbt}> **select properties[0].customFields  from ( select expand(classes) from metadata:schema) where name = 'test'**
+----+----------------------------+
|#   |properties                  |
+----+----------------------------+
|0   |{customP=123, customP1=абвг}|
+----+----------------------------+
1 item(s) found. Query executed in 0.003 sec(s).

orientdb {db=dbt}> **EXPORT DATABASE D:/test**
Exporting current database to: DATABASE D:/test in GZipped JSON format ...
Started export of database 'dbt' to D:/test.json.gz...
Exporting database info...OK
Exporting clusters...OK (21 clusters)
Exporting schema...OK (11 classes)
Exporting records...
- Cluster 'internal' (id=0)...OK (records=3/3)
- Cluster 'index' (id=1)...OK (records=0/0)
- Cluster 'manindex' (id=2)...OK (records=0/0)
- Cluster 'default' (id=3)...OK (records=0/0)
- Cluster 'orole' (id=4)...OK (records=3/3)
- Cluster 'ouser' (id=5)...OK (records=3/3)
- Cluster 'ofunction' (id=6)...OK (records=0/0)
- Cluster 'osequence' (id=7)...OK (records=0/0)
- Cluster 'oschedule' (id=8)...OK (records=0/0)
- Cluster 'v' (id=9)...OK (records=0/0)
- Cluster 'v_1' (id=10)...OK (records=0/0)
- Cluster 'v_2' (id=11)...OK (records=0/0)
- Cluster 'v_3' (id=12)...OK (records=0/0)
- Cluster 'e' (id=13)...OK (records=0/0)
- Cluster 'e_1' (id=14)...OK (records=0/0)
- Cluster 'e_2' (id=15)...OK (records=0/0)
- Cluster 'e_3' (id=16)...OK (records=0/0)
- Cluster 'test' (id=17)...OK (records=0/0)
- Cluster 'test_1' (id=18)...OK (records=0/0)
- Cluster 'test_2' (id=19)...OK (records=0/0)
- Cluster 'test_3' (id=20)...OK (records=0/0)
Done. Exported 9 of total 9 records

Exporting index info...
- Index OUser.name...OK
- Index dictionary...OK
- Index ORole.name...OK
- Index OFunction.name...OK
OK (4 indexes)
Exporting manual indexes content...
- Exporting index dictionary ...OK (entries=0)
OK (1 manual indexes)
Database export completed in 101ms

orientdb> **create database plocal:../databases/dbt2 admin admin**
Creating database [plocal:../databases/dbt2] using the storage type [plocal]...
Database created successfully.
Current database is: plocal:../databases/dbt2

orientdb {db=dbt2}> **IMPORT DATABASE D:/test.json.gz**

Importing database DATABASE D:/test.json.gz...
Started import of database 'plocal:../databases/dbt2' from D:/test.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class E was removed.
- Class V was removed.
- Class OTriggered was removed.
- Class ORestricted was removed.
- Class OSequence was removed.
- Class OSchedule was removed.
- Class OFunction was removed.
Removed 7 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'osequence'...OK, assigned id=7
- Creating cluster 'oschedule'...OK, assigned id=8
- Creating cluster 'v'...OK, assigned id=9
- Creating cluster 'v_1'...OK, assigned id=10
- Creating cluster 'v_2'...OK, assigned id=11
- Creating cluster 'v_3'...OK, assigned id=12
- Creating cluster 'e'...OK, assigned id=13
- Creating cluster 'e_1'...OK, assigned id=14
- Creating cluster 'e_2'...OK, assigned id=15
- Creating cluster 'e_3'...OK, assigned id=16
- Creating cluster 'test'...OK, assigned id=17
- Creating cluster 'test_1'...OK, assigned id=18
- Creating cluster 'test_2'...OK, assigned id=19
- Creating cluster 'test_3'...OK, assigned id=20
Rebuilding indexes of truncated clusters ...
- Cluster content was updated: rebuilding index 'ORole.name'... Index ORole.name was successfully rebuilt.
- Cluster content was updated: rebuilding index 'OUser.name'... Index OUser.name was successfully rebuilt.
Done 2 indexes were rebuilt.
Done. Imported 19 clusters
Importing database schema...OK (11 classes)
Importing records...
Started migration of links (-migrateLinks=true). Links are going to be updated according to new RIDs:
- Cluster test... Completed migration of 0 records in current cluster
- Cluster e... Completed migration of 0 records in current cluster
- Cluster v_2... Completed migration of 0 records in current cluster
- Cluster ouser... Completed migration of 3 records in current cluster
- Cluster v_1... Completed migration of 0 records in current cluster
- Cluster v_3... Completed migration of 0 records in current cluster
- Cluster osequence... Completed migration of 0 records in current cluster
- Cluster test_3... Completed migration of 0 records in current cluster
- Cluster default... Completed migration of 0 records in current cluster
- Cluster test_2... Completed migration of 0 records in current cluster
- Cluster test_1... Completed migration of 0 records in current cluster
- Cluster orole... Completed migration of 3 records in current cluster
- Cluster oschedule... Completed migration of 0 records in current cluster
- Cluster v... Completed migration of 0 records in current cluster
- Cluster e_1... Completed migration of 0 records in current cluster
- Cluster e_3... Completed migration of 0 records in current cluster
- Cluster e_2... Completed migration of 0 records in current cluster
- Cluster ofunction... Completed migration of 0 records in current cluster
Total links updated: 6
Done. Imported 7 records in 0,07 secs
Importing indexes ...
- Index 'OUser.name'...OK
- Index 'dictionary'...OK
- Index 'ORole.name'...OK
- Index 'OFunction.name'...OK
Done. Created 4 indexes.
Importing manual index entries...
- Index 'dictionary'...OK (0 entries)
Done. Imported 1 indexes.
Rebuild of stale indexes...
Stale indexes were rebuilt...
Deleting RID Mapping table...OK
Database import completed in 664 ms

orientdb {db=dbt2}> **select customFields  from ( select expand(classes) from metadata:schema) where name = 'test'**
+----+
|#   |
+----+
|0   |
+----+
1 item(s) found. Query executed in 0.017 sec(s).

orientdb {db=dbt2}> **select properties[0].customFields  from ( select expand(classes) from metadata:schema) where name = 'test'**
+----+----------------------------+
|#   |properties                  |
+----+----------------------------+
|0   |{customP1=абвг, customP=123}|
+----+----------------------------+
1 item(s) found. Query executed in 0.044 sec(s).

**Comment by tglman** [comment]
hi @Ivanov-Yuriy,

I just reviewd and fixed some issue on the import this week, the fix should be released in 2.2.10 tomorrow.

Bye

**Comment by Ivanov-Yuriy** [comment]
hi @tglman 
it is great, thanks

**Comment by tglman** [comment]
Hi @Ivanov-Yuriy,

2.2.10 has been released, let me know if we can closed this.

Bye

**Comment by Ivanov-Yuriy** [comment]
everything works great, thanks

**Comment by a-unite** [comment]
Dear @tglman,

could you please backport this fix to 2.1.x version as well (symptoms are very same there)?

Thanks in advance,
Ata

**Comment by tglman** [comment]
hi @a-unite,

we release a 2.1.24 few days ago that have this fix. 

Regards

**Comment by a-unite** [comment]
Dear @tglman,

thanks! I've missed the announcement, have found new version just yesterday. 

Will try, thanks!

**Comment by a-unite** [comment]
Confirm it was fixed in 2.1.24 too. 
`Importing database schema` stage of database import seems to be very busy (had to wait for ages), but it works!

Thank you very much!
