### ISSUE TITLE
java.lang.IllegalArgumentException: Type error. The class bucket_ACR_0 does not extend class 'E' and therefore cannot be considered an Edge

### ISSUE THREAD

**Issue by smil2k** [orientechnologies/orientdb#6699]
## OrientDB Version, operating system, or hardware.
- v2.2.10
## Expected behavior and actual behavior

Graph editor does not work properly in case lightweight edges are used.
Clicking on "next edge" gives internal error:
java.lang.IllegalArgumentException: Type error. The class bucket_ACR_0 does not extend class 'E' and therefore cannot be considered an Edge
## Steps to reproduce the problem

cannot navigate.

I think this is a regression in 2.2.10, it seemed to work at least in 2.2.7

**Comment by maggiolo00** [comment]
@smil2k 

what is the "next edge"?

How can i reproduce it?

**Comment by smil2k** [comment]
0) Set lightweightEdges=true
1) Create two vertices and create edge between them 
2) Go to graph
3) sekect * from V1
4) click on V and click on incoming or outgoing edge

Then you get this error.

**Comment by maggiolo00** [comment]
@smil2k 
thanks
