### ISSUE TITLE
different behaviour between EMBEDDEDLIST with linkedtype and EMBEDDEDLIST with linked class

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6700]
## OrientDB Version, operating system, or hardware.
- v2.2.10 

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I expect that EMBEDDEDLIST with linkedclass will be save with null instead object like in EMBEDDEDLIST with linkedtype

## Steps to reproduce the problem
orientdb {db=test}> **create class test extends V**
Class created successfully. Total classes in database now: 11.

orientdb {db=test}> **create property test.et embeddedlist string**
Property created successfully with id=1.

orientdb {db=test}> **create property test.ec embeddedlist V**
Property created successfully with id=2.

orientdb {db=test}> **select expand(properties)  from ( select expand(classes) from metadata:schema) where name = 'test'**
+----+----+----+--------+---------+--------+-------+------------+----+----+----------+------------+-------+-----------+-----------+
|#   |name|type|globalId|mandatory|readonly|notNull|defaultValue|min |max |linkedType|customFields|collate|description|linkedClass|
+----+----+----+--------+---------+--------+-------+------------+----+----+----------+------------+-------+-----------+-----------+
|0   |et  |10  |23      |false    |false   |false  |            |    |    |7         |            |default|           |           |
|1   |ec  |10  |24      |false    |false   |false  |            |    |    |          |            |default|           |V          |
+----+----+----+--------+---------+--------+-------+------------+----+----+----------+------------+-------+-----------+-----------+
2 item(s) found. Query executed in 0.005 sec(s).

orientdb {db=test}> **insert into test set et=[null,'string']**
Inserted record 'test#17:0{et:[2]} v1' in 0,013000 sec(s).

orientdb {db=test}> **insert into test set ec=[null,{"@class":"V","@type":"d"}]**
Error: com.orientechnologies.orient.core.exception.OValidationException: The field 'test.ec' has been declared as EMBEDDEDLIST but an incompatible typ
e is used. Value: null DB name="test"

**Comment by tglman** [comment]
hi @Ivanov-Yuriy,

I added the test cases of for the support of null values in embedded collections and fixed, should be released for the 2.2.11.

closing this.
