### ISSUE TITLE
shutdown of 400GB dbase  hangs

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6705]
## OrientDB Version, operating system, or hardware.
- v2.2.7

## Operating System
- [x] Linux

# Expected behavior and actual behavior
A single-node ODB server is not stopping, when using the gracefull "shutdown.sh" script.

This is a separate thread for the issue started in #6657; this new issue is strictly relating to the shutdown problems. Please see that issue #6657 for the previous communications about the subject.

**Comment by robfrank** [comment]
First of all, as reference, the doc about shutdown:

http://orientdb.com/docs/last/Tutorial-Run-the-server.html#stop-the-server

If you run the shutdown script on the server where OrientDB is running, without parameters, it will send a kill signal and the waits for the process to finish:

```
echo "pid file detected, killing process"
    kill -15 `cat "$ORIENTDB_PID"` >/dev/null 2>&1
    echo "waiting for OrientDB server to shutdown"
    while ps -p `cat $ORIENTDB_PID` > /dev/null; do sleep 1; done
    rm "$ORIENTDB_PID"
```

You can stop the server passing parameters to the script, as stated in the documentation:

```
 ./shutdown.sh -h odb1.mydomain.com -P 2424-2430 -u root -p ROOT_PASSWORD
```

You need to provide the server root username and its password. This will not wait for the server to shutdown. This way you can better understand what the server is doing if it still stays online.

**Comment by laa** [comment]
Hi @rdelangh  @robfrank is right, we recommend you to stop the server by passing parameters to the script.
If that solve the issue, and you have time to investigate the case when kill command hangs the database I will be glad to fix that problem too. If this approach does not work, please keep a database in the frozen state and we will gather additional information to identify an issue.
