### ISSUE TITLE
Would be convenient if 'Live Unsubscribe' supported a parameter

### ISSUE THREAD

**Issue by SDIPro** [orientechnologies/orientdb#6706]
This is just a convenience request, but it would be useful if `live unsubscribe ?` were supported with a parameter.

This causes the following error:
error unsubscribing token ?: java.lang.NumberFormatException - For input string: "?" [OCommandExecutorSQLLiveUnsubscribe]

**Comment by luigidellaquila** [comment]
Hi @SDIPro 

It's not hard to support, I'll work on it asap

Thanks

Luigi
