### ISSUE TITLE
worrying connection problem in orientdb 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6708]
## OrientDB Version, operating system, or hardware.
2.2.8

## Operating System
- [ x] Linux

## Expected behavior and actual behavior
 in my application i have multiple.... log error

`com.orientechnologies.common.log.OLogManager.log Caught I/O errors, trying to reconnect (error: Stream closed)
com.orientechnologies.common.log.OLogManager.log Caught I/O errors, trying to reconnect (error: Connection reset)

`

the application continue to work but it is very slow. 

How can understand what are those "Caught I/O errors" ?

it seams a problem related with high number of  requests ... but i dont understand any more

**Comment by publicocean0** [comment]
first observation : 
every call to database give this log notification
com.orientechnologies.common.log.OLogManager.log Caught I/O errors, trying to reconnect  ...

**Comment by publicocean0** [comment]
searching similar error in google i saw ... maybe it is not a problem from client but from server. 
Maybe server close connection.why?

**Comment by publicocean0** [comment]
just moment i m investigating in my old persistent manager class.... i will tell ...

**Comment by publicocean0** [comment]
my old persistent manager is using ODatabaseDocumentPool.global()
i saw it is now deprecated.

1) i replaced ODatabaseDocumentPool. with OPartitionedDatabasePool
2) now error there is a error in unset ODatabaseRecordThreadLocal. I found the reason OPartitionedDatabasePool remove it when i close connection But OrientdbObject use proxied object so you can call the connection also after the dao completed the retrieval operation.

**Comment by publicocean0** [comment]
sorry , this time was a problem in my transaction manager. No bug in orientddb

**Comment by lvca** [comment]
Cool, thank you for reporting it.
