### ISSUE TITLE
Use "root" as variable name (LET clause)

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#6709]
## OrientDB Version, operating system, or hardware.
v2.2.10
## Operating System
Mac OS X

## The problem
SELECT expand($x) LET $x = (SELECT FROM Event)
=> OK

SELECT expand($root) LET $root = (SELECT FROM Event)
=> No result found, but no error message

Is "root" a reserved keyword?

**Comment by maggiolo00** [comment]
hi @benjaminbillet 

seems that $root is a reserved context variable like those one

http://orientdb.com/docs/2.1/SQL-Where.html#variables

I think it's not listed there because it is used internally

**Comment by lvca** [comment]
@maggiolo00 could you please update the docs?

**Comment by benjaminbillet** [comment]
Thanks for your response. 
However, in addition of the documentation update, I think that an explicit error should be triggered when a reserved internal variables is used in a query. Currently, it fails silently with a "0 result(s) found" message, which makes it very difficult to understand.

**Comment by lvca** [comment]
+1 to raise an error.

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 

I just added it to the docs:

https://github.com/orientechnologies/orientdb-docs/blob/2.2.x/SQL-Where.md

now I'm adding a check on the LET clause, to make sure that it throws a parsing exception if reserved words are used

Thanks

Luigi

**Comment by benjaminbillet** [comment]
That's perfect @luigidellaquila, thanks a lot.

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 

I just pushed a fix that does parse-time validation.
I'm closing this, please reopen if you see any related problems

Thanks

Luigi
