### ISSUE TITLE
OSQL:  Can you please add sort method

### ISSUE THREAD

**Issue by mtolhuisen** [orientechnologies/orientdb#6715]
## OrientDB Version, operating system, or hardware.
- 2.1.20
  ## Operating System
- [ ] Windows
## Expected behavior and actual behavior

select out('edgename') from VertexClass
results in a list of vertices which are connected to VertexClass.
Unfortunately this list is not sorted, instead of the expected @rid order

Can you implement a method which sorts the list, using one ore more properties, in ascending or descending order?
e.g.
select out('edgename').sort('property1',asc|desc,'property2',asc|desc,...'propertyX',asc|desc) from VertexClass

**Comment by luigidellaquila** [comment]
Hi @mtolhuisen 

I'm marking this as an enhancement, it will be implemented in next releases.
I'm also adding a "contributor friendly" label, as it's definitely easy to implement, so new contributors can try to provide a PR

Thanks

Luigi

**Comment by TrangPham** [comment]
Hi @luigidellaquila 

I'd like to take a crack at implementing this. From the documentation it seems like I will have to implement a SQL Method similar to: OSQLMethodRemove.java

In this case it seems that OMultiValue (http://orientdb.com/javadoc/2.2.x/com/orientechnologies/common/collection/OMultiValue.html) Should be modified to have a sort function and then the OSQLMethodSort would call this on the OMultiValue. Could you point me to repo that the OMultiValue class lives in?

Please correct me if I am wrong. 

Thanks!

**Comment by luigidellaquila** [comment]
Hi @TrangPham 

That would be awesome, thank you!
OMultiValue is in the Core module, in the main repo https://github.com/orientechnologies/orientdb

As a reference, you can have a look at this method
https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/orient/core/sql/method/misc/OSQLMethodAsList.java

and you can refer to this to see how to register it: https://github.com/orientechnologies/orientdb/blob/9847c4359eab6476b403a1777c5f97d7f6e02957/core/src/main/java/com/orientechnologies/orient/core/sql/method/ODefaultSQLMethodFactory.java

Thanks

Luigi
