### ISSUE TITLE
Suggestion: Compression for the binary protocol

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#6716]
Hi,

I was monitoring the network traffic between my clients and the standalone database, and I noticed that: (i) most of the traffic is regular text, and (ii) there is a lot of duplicate strings (especially when I combine MATCH requests and fetch plans). 

It would be interesting to have an option for compressing the data output. For example, I simply tried to compress my network dump using deflate (zip), and the obtained file is ~2.5x smaller. Probably there is a tradeoff to find between network usage and CPU consumption.

**Comment by StarpTech** [comment]
+1 a common compression algorithm is snappy. 
e.g https://github.com/xerial/snappy-java

**Comment by lvca** [comment]
This could be a good idea. At connect time, the client has to communicate to the server if compression is supported.

**Comment by tglman** [comment]
hi,

Yes can be done, we will keep this in mind when we do the evolution for 3.0, thank you for the suggestion.

bye

**Comment by benjaminbillet** [comment]
Perfect, thanks you.

**Comment by lvca** [comment]
@tglman could you please add this information during the handshaking, so we can implement this later in 3.0.x without changing the binary protocol?

**Comment by tglman** [comment]
Hi,

As today handshaking data from the client include:
```
short             protocolVersion;
String            driverName;
String            driverVersion;
byte              encoding;
byte              errorEncoding;
```

The `encoding field was thought for the evolution like use varint on network serialization or compression.

So already done.

**Comment by lvca** [comment]
cool.
