### ISSUE TITLE
Pull or Push a database when autodeploy is false

### ISSUE THREAD

**Issue by Pro-Vizion** [orientechnologies/orientdb#6717]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Hi, is there a command to manually deploy a database from/to a node ?

for example : 
`pull database "mydatabase " from "nodea"`
>> this command would deploy a given database on the current node from the given node

`push database "mydatabase " to "nodea"`
>> this command would deploy a given database from the current node to the given node.

**Comment by lvca** [comment]
This is not available, marked as an enhancement. However you could try to create a database on the server and then execute `HA SYNC DATABASE`, but I'm not sure this works.
