### ISSUE TITLE
WARNI Receiving invalid LiveQuery token: 1857716960 [OStorageRemoteAsynchEventListener]

### ISSUE THREAD

**Issue by dominioon** [orientechnologies/orientdb#6718]
## OrientDB Version, operating system, or hardware.
- [X] v2.2.10 

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Expected behaviour
The application prints only lines like this:
`Got live update ORecordOperation [record=#17:0{entry:0} v1, type=CREATE]
`

### Actual behaviour
For every live update also a similar line is logged as warning:
`WARNI Receiving invalid LiveQuery token: 1857716960 [OStorageRemoteAsynchEventListener]
`
## Steps to reproduce the problem
Launch the com.Main class from the attached example. The code starts a server at localhost, connects as root, creates a new database, a new (so-called application) user and a test table. Then it connects with the application user, starts live select and inserts some data to the table.
The bug is related to the fact that 2 connections were made to the database - one with root user, another with the application user. Only application user should receive live updates, as it ran the live select, but the root user also receives live updates. As it does not have live query listener set up, it will log a warning.

[orientTest.zip](https://github.com/orientechnologies/orientdb/files/482328/orientTest.zip)

**Comment by luigidellaquila** [comment]
Hi @dominioon 

The problem seems to be related to the way the client binds user sessions to network connections. We will check it ASAP

Thanks

Luigi

**Comment by tglman** [comment]
hi @dominioon,

This is not critical an the message can be ignored, in any case i just fixed it, Thanks for your precise test it was really helpful.

Bye

**Comment by dominioon** [comment]
hi @tglman,
You're welcome and thanks for the quick fix! Yes, it was just a warning, but it was spamming logs and caused suspicions.
