### ISSUE TITLE
After changing the DB, records from the old one are fetched

### ISSUE THREAD

**Issue by kerner1000** [orientechnologies/orientdb#6720]
OrientDB v. 2.1.16

Operation System Linux

I use the following code to manage OrientDB databases within my application. When I switch db nevertheless, I see in my FXTable the properties from the old Database. 

As far as I can tell from the code and the logs, all database instances are closed.

https://gist.github.com/kerner1000/fc18d8d51c9b018b576f15d774aab879#file-databaseproviderimpl-java

**Comment by tglman** [comment]
hi @kerner1000,

Checking your class i see that the db instance is kept in the database provider instance, this means that there is chance that the instance acquired for one thread is used by another thread.

I know that the thread pool is single thread, but with statefull context is possible that ininOnDb is called by another thread and remain in the context.

i wound suggest to refacto a bit and not keep the db in the contex but just in the execution scope, something like:
```
	    exe.submit(() -> {
                ODatabaseDocument db =initOnDB();
		try {
		    c.accept(db);
		} finally {
		    finishOnDB(db);
		}
})
```

The only reason possible for see data of a different db is that the thread is still bound to the other db, so be sure when you switch the database that only the new database is active in the current thread.

Bye

**Comment by kerner1000** [comment]
Hi @tglman 

many thanks for helping out! I highly appreciate it.
I keep an instance of the database for JUnit testing purposes. 
I need to access the db directly during testing. One reason is, that Unit tests executed not in the "test-thread" will show strange behavior such as not failing on an exception.

I was wondering, if it was such a good idea to keep the db instance in a thread-local, static variable? For my feeling it causes a lot of confusion.
Dont get me wrong, I am just wondering what was the reason for this design decision.

I will have again a look at the db instance scope.

A workaround I am thinking of right now is to trigger the Pool-shutdown-hook manually when switching the db/pool.

Could you give me a hint how to do that?

Many thanks again!

**Comment by laa** [comment]
Hi @kerner1000 , you may use OPartitionedDatabasePool to acquire/shutdown instances inside of test methods. In general keeping of long living instances is not good idea.

**Comment by kerner1000** [comment]
Hi  @laa 
Again thanks for helping out! I solved the problem (and a few others) by following @tglman suggestion to make the db instance method-local. For testing purposes I implemented a class that executes the db stuff in the same thread, so the whole thing is now also well testable.
