### ISSUE TITLE
MATCH and fetch plan performance issue

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#6722]
## OrientDB Version, operating system, or hardware.

v2.2.10, MacOSX
## Expected behavior and actual behavior

It looks like my fetch plans have no effect with MATCH requests.

If I understand correctly the documentation (http://orientdb.com/docs/master/Fetching-Strategies.html), the standalone DB should fetch the linked nodes (including their content) and sends them back to the client, such as the client doesn't have to communicate with the DB while browsing the result set. 

If I simply access the id field (OrientVertex#getId), it's fast. However, when accessing properties, the time is significantly increased.

``` javascript
OrientVertex root = graph.addVertex("class:TypeA");
graph.commit();

for (int i = 0; i < 2; i++) {
    OrientVertex v = graph.addVertex("class:TypeB");
    root.addEdge("AtoB", v);
}
for (int i = 0; i < 2; i++) {
    OrientVertex v = graph.addVertex("class:TypeC");
    root.addEdge("AtoC", v);
}
graph.commit();


int nbRuns = 5000;
long time, delta;

String query = "SELECT FROM (MATCH {class: TypeA, as: _root, where: (@rid = '" + root.getId() + "')}.out('AtoB') {as: _root_AtoB}, {as: _root}.out('AtoC') {as: _root_AtoC} RETURN $paths) FETCHPLAN *:-1";

time = System.nanoTime();
for (int i = 0; i < nbRuns; i++) {
    Iterable<OrientVertex> rows = graph.command(new OCommandSQL(query)).execute();
    for (OrientVertex row : rows) {
        row.getId(); // only fetch the id, which is included in the record
    }
}
delta = System.nanoTime() - time;
System.out.println((double) delta / 1000000000d);
// average time on my machine: 5 seconds (+/- 1)

time = System.nanoTime();
for (int i = 0; i < nbRuns; i++) {
    Iterable<OrientVertex> rows = graph.command(new OCommandSQL(query)).execute();
    for (OrientVertex row : rows) {
        row.getProperty("_root"); // fetch the _root property, which
    }
}
delta = System.nanoTime() - time;
System.out.println((double) delta / 1000000000d);
// average time on my machine: 30 seconds (+/- 3)
```

I tried several configuration for the fetch plan (originally *:1, but it gives the same results than *:-1). I also tried to use OCommandSQL#setFetchPlan.

If I run the request in Studio and display the raw results, I can see that the fetching is done correctly: all the linked data is included. **Maybe the problem is from client side?**

In addition, it looks like the time is not linear to the number of loops (you can set the nbRuns variable in the test code provided above):
- 1000 runs: 2 seconds
- 2000 runs: 6 seconds
- 3000 runs: 12 seconds
- 4000 runs: 19 seconds
- 5000 runs: 30 seconds
- 10000 runs: 150 seconds

PS: I'm sorry for posting so much issues since yesterday, but I'm actively working with the database.

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 

Are you running in remote or plocal?
The fact that the query time is non linear is quite strange, we'll investigate it

Thanks

Luigi

**Comment by benjaminbillet** [comment]
Hi,
I am running in remote. Feel free to run my test code to be sure my problem is reproducible. I will test with other types of request.
Thanks

**Comment by benjaminbillet** [comment]
BTW, I forgot to mention that the results I obtained are the same with and without the fetch plan clause.

**Comment by benjaminbillet** [comment]
After some testing, regular requests does not have the problem, e.g.:

`SELECT FROM TypeA FETCHPLAN *:-1`

`SELECT $a LET $a = (SELECT FROM TypeA), $b = (SELECT FROM TypeB), $c = UNIONALL($a, $b) FETCHPLAN *:-1`

Maybe it's related to MATCH requests?

**Comment by luigidellaquila** [comment]
Thank you for the detailed information. Yes, it could be someway related to the MATCH statement, I'll investigate it

Thanks

Luigi
