### ISSUE TITLE
Is "-Dstorage.useWAL=false" available on on distributed transaction?

### ISSUE THREAD

**Issue by KazuYamaguchi** [orientechnologies/orientdb#6723]
We are runing Multi-master replication on 2 of our servers.
We have use "-Dstorage.useWAL = false" in the VM arguments.

After a while, we got this error message on only one of two servers:

```java
Error on distributed transaction commit
com.orientechnologies.orient.core.exception.OStorageException: WAL mode is not active. Transactions are not supported in given mode
```

Is "-Dstorage.useWAL=false" available on distributed transaction commit?

**Comment by lvca** [comment]
Disabling the WAL is always a bad practice, because in case of crash your database could be not consistent or even worse, corrupted. You can disable it for initial massive insertion, but for the operational day-2-day please re-enable it.
