### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by william76** [orientechnologies/orientdb#6724]
On the page [Javascript API](http://orientdb.com/docs/last/Javascript-Driver.html) in the documentation, the link to [oriented-api.js](https://github.com/nuvolabase/orientdb/blob/master/server/src/site/js/orientdb-api.js) is a dead link resulting in a trip to the 404 not found page.

**Comment by lvca** [comment]
You're right. That JS API has been deprecated and then removed long time ago. Just updated the docs with:

### This API has been deprecated, please use HTTP calls from the browser by using the [HTTP RESTful protocol](OrientDB-REST.md).
------------

Will be online in max 1h.

**Comment by william76** [comment]
Just following up...

The link you gave to [HTTP RESTful protocol](https://github.com/orientechnologies/orientdb/issues/OrientDB-REST.md) is still coming back with a 404 notfound...

**Comment by lvca** [comment]
Sorry, this is the link: http://orientdb.com/docs/last/OrientDB-REST.html
