### ISSUE TITLE
Question:  Delete vertex syntax in SQL strings

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/orientdb#6730]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[x] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Use delete sql syntax for classes that don't extend V or do extend V

## Steps to reproduce the problem
Create a class that doesn't extend V and one that does.  Delete vertex syntax is required for classes that extend V.  What is the benefit of this requirement?  In Orient Spring Data, the deleteByXYZ methods will fail unless annotated when deleting vertices due to the syntax differences. Not sure why it shouldn't be legal to use regular delete on a class that happens to extend V.

**Comment by luigidellaquila** [comment]
Hi @RAndrews137 

This is mainly for historical reasons. The DELETE VERTEX is implemented in the graph module, that has all the components to manage (and cascade delete) connected edges, while simple DELETE is implemented in the core module, that does not know anything about edges, so it would leave dangling pointers (ie. inconsistent graph).

For sure, DELETE VERTEX could be safely used to delete a non-vertex element without any problems. 
In V. 3.0 we are trying to unify the core APIs to also include graph components, so probably we will also review the DELETE commands.

Thanks

Luigi

**Comment by RAndrews137** [comment]
Thanks for the quick response @luigidellaquila.   That makes sense.  Looking forward to 3.x  :)
