### ISSUE TITLE
Live query stops working after timeout

### ISSUE THREAD

**Issue by dominioon** [orientechnologies/orientdb#6731]
## OrientDB Version, operating system, or hardware.
-  [X] v2.2.10

## Operating System
- [X] Linux

### Expected behavior
All inserts are captured by the onLiveResult() callback.

### Actual behavior
Only the 1st insert is captured, already the 2nd one will end up in onError() callback, and prints `LIVE QUERY ERROR`. The database tries to recover itself later ( `com.orientechnologies.orient.client.remote.OStorageRemote    I Caught Network I/O errors on localhost:2424/testDb, trying an automatic reconnection... (error: Connection reset)
` ), but the onLiveResult() is not called for the particular entity, and the update is lost.

## Steps to reproduce the problem
Launch the com.Main class from the attached example. The code creates db, starts live updater and will insert rows to the table being monitored. Between inserts the code waits 63 minutes.

[liveQueryTimeout.zip](https://github.com/orientechnologies/orientdb/files/485388/liveQueryTimeout.zip)

**Comment by maggiolo00** [comment]
@dominioon 

you should increase the token expire timeout. By default it's 60 mins

http://orientdb.com/docs/2.2/Configuration.html#networktokenexpiretimeout

**Comment by dominioon** [comment]
@maggiolo00
I think Live Query should then send heartbeats to keep the connection alive by itself, or the connection timeout should be set to infinity by default. Imagine a situation when a live query is used to get informed about changes made to a table once in a month or a year.

**Comment by tglman** [comment]
hi @dominioon,

The live query where designed to run inside the application, getting notifications while your application run, checking your code (from the other issue) it seems you are writing a kind of microservice for only get notification, i agree with you that in a case like that is needed an heartbeat, anyway insert an heartbeat like the one you mention is unlackely going to happen in a hotfix, because it require a bit of redesign, that is going to happen anyway in the next major.

for now i would suggest run a query once a while, for example a simple `select from V limit 1` runned every 10 minutes can keep the session alive.

hope this help.

Bye

**Comment by dominioon** [comment]
hi @tglman,

In the real application Im using live query to keep another inmemory copy (similar to a simple hashmap) in sync. The data structure there is more optimized for realtime usage than querying every time and parsing JSON. There are many tables being monitored in that way. One of these tables is updated at least every second, so  onLiveResult() callback for _that_ listener is called regularly. But it does not help, probably its related to the connection pooling and not all connections in the pool have such regular heartbeats (just a wild guess).
But when I increased network.token.expireTimeout from 1 hour to 1 year no more anomalies occur, and so far so good. So thanks alot for the hint!

**Comment by tglman** [comment]
hi @dominioon,

Thank you, if this solve your problem i'll close this, we have anyway on the schedule the review of this interactions in 3.0, so no issue to keep track needed.

Bye

**Comment by dominioon** [comment]
@tglman, at least some insistent warning should be added to the Live Query documentation that timeout must be increased to ensure it working properly.
