### ISSUE TITLE
Two  automatic backups config

### ISSUE THREAD

**Issue by asiqq23** [orientechnologies/orientdb#6736]
OrientDB v. 2.2.10

Operation System Linux

Hi,

I try to configure two independand automatic backups? Is it even possible to do?

I added two handlers in server config like this:

` <handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter value="true" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/automatic-backup.json" name="config"/>
            </parameters>
        </handler>
        <handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter value="true" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/automatic-backup-incremental.json" name="config2"/>
            </parameters>
        </handler>
`

When I try to start server i get the exception

> Automatic Backup plugin installed and active: delay=600000ms, firstTime=Sat Sep 24 09:50:00 GMT 2016, targetDirectory=/orientdb/backup/ [OAutomaticBackup]Exception in thread "main" java.lang.IllegalStateException: Plugin 'automaticBackup' already registered
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerPlugin(OServerPluginManager.java:133)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1195)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:391)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

**Comment by maggiolo00** [comment]
Hi @asiqq23 
it's not possible. The plugin is one and can be registered one time.
