### ISSUE TITLE
Incorrect count when using indexes on classes and sub classes

### ISSUE THREAD

**Issue by scrabb** [orientechnologies/orientdb#6737]
## OrientDB Version, operating system, or hardware.
2.2.10

Related to #5846

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x ] Windows
- [ ] Other Unix
- [ ] Other, name? 

In the following scenario

class of Car
subclass of Ford and Toyota

Car has boolean property isTaxed
build a non unique hash index for Car.isTaxed, Ford.isTaxed and Toyota.isTaxed

I would then expect
select count(*) from Car where isTaxed=true

to have a different value to 

select count(*) from Ford where isTaxed=true

and 

select count(*) from Toyota where isTaxed=true

however all variations return the count from Car.

Using explain does show that all variations only use the Car.isTaxed index rather than the other more specific indexes so i presume this is why the count is wrong.

**Comment by luigidellaquila** [comment]
Hi @scrabb 

I just pushed a fix on 2.2.x branch. The fix will be released with 2.2.11

Thanks

Luigi
