### ISSUE TITLE
Using Eclipse Neon, error importing OrientDB eclipse formatting profile

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#6738]
## OrientDB Version, operating system, or hardware.
- v2.2

## Operating System
- Windows

## Expected behavior and actual behavior
Using Eclipse Neon, error importing eclipse formatting profile:
https://github.com/orientechnologies/orientdb/blob/master/_base/ide/eclipse-formatter.xml

See scan:
![error-importing-formatting-profile](https://cloud.githubusercontent.com/assets/5831026/18787963/59e526f4-81a5-11e6-8fe0-6bc93e68e5d9.jpg)

**Comment by diegomtassis** [comment]
If I fix all the instances of that error (some, but not too many) then I get a new one: "Problems reading profiles from XML The element type "meta" must be terminated by the matching end-tag "</meta>".

I tried to fix all of them manually, and I think I did, but the error still shows up.

Is it a known Eclipse Neon bug? I didn't have any problem importing the other formatting profiles that I use.

**Comment by lvca** [comment]
That settings are untouched since log time ago and they works for the previous version of Eclipse and also from IntelliJ.

**Comment by diegomtassis** [comment]
I've tried using an Eclipse Mars fresh installation and I get the same error.

**Comment by diegomtassis** [comment]
I closed the ticket unintentionally (and then reopened).

I've tested the profile with fresh installations of the 3 last eclipse versions (Neon, Mars and Luna) and I get the same error.

This is how I proceed:
* Donwload the file (286 kb).
* In eclipse Preferences->Java->Code Style->Formatter, I click on the option "Import" and select the file.
* The error shows up.

**Comment by diegomtassis** [comment]
Problem sol
