### ISSUE TITLE
Support for arrays in index selections

### ISSUE THREAD

**Issue by kaYcee** [orientechnologies/orientdb#6741]
## OrientDB Version, operating system, or hardware.
- 2.2.10
## Operating System
- [ X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

During our development we were using the nifty feature of filtering an index selection, i.e. using an array as filter criterion for index range selections. After reviewing the code we found out that this feature seems not to be functional (anymore?). 

In particular, we have a composite index set up on "type", "date" and "rid" for one of our classes. A typical call would look as follows:

`
SELECT EXPAND(rid) FROM INDEX:Multiplexed.sensor_timestamp_id WHERE KEY BETWEEN [["tapcount","motion"], "2016-08-27T09:29:00.856Z, [#29:18,#29:9,#29:0]"] AND [["tapcount","motion"], sysdate(), [#29:18,#29:9,#29:0] )
`

The expected behavior would be to return all records with type in ["tapcount","motion"], the linked rids in [#29:18,#29:9,#29:0] and their timestamps from end of August until today.

Although OrientDB Studio is not complaining with regards to the syntax, the engine seems to be just focusing on the first element from each parameter, i.e.
`
SELECT EXPAND(rid) FROM INDEX:Multiplexed.sensor_timestamp_id WHERE KEY BETWEEN ["tapcount", "2016-08-27T09:29:00.856Z, #29:18] AND ["tapcount", sysdate(), #29:18] )
`
which of course returns only a subset of the expected records.

Is this the intended behavior or has the index selection be designed to support arrays and has just ceased working?

**Comment by MRechtien** [comment]
Looks like I have a potentially related problem (OrientDB 2.2.11) when using a select query with 
```SQL 
IN [*array-elements*]
``` 
conditions on schema-less vertexes, e.g.:
```SQL 
select from V where r_name IN ['Name942', 'Name943']
```
As soon as the "IN" operator is used, the index seems not to hit anymore, is this correct?
Greetings, Markus
