### ISSUE TITLE
Wrong search result if the property was defined in schema

### ISSUE THREAD

**Issue by tanhv90** [orientechnologies/orientdb#6742]
## OrientDB Version, operating system, or hardware.
- v2.2.7
- v2.2.10

I tested on this 2 versions only.

## Operating System
- [x] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I created a class node item with 2 properties id and flag

> **id:** type STRING, index: UNIQUE
> **flag:** type DECIMAL, it can be set by 1, 0, or null value. 

I use the query below to get all item which has flag is 1

> select from item where **flag = 1**

This query returns nothing.
And seem that this issue only occurs if **flag** was defined in schema before feeding data.

**NOTE**:
But with the below query, it works like a charm
> select from item where **1 = flag**

I attached my test database used for reproduce this issue at [here](https://drive.google.com/file/d/0B-9uJbevAJq9UjZRMWRKMkYwWE0/view)

**Comment by luigidellaquila** [comment]
Hi @tanhv90 

The problem seems to be related to the DECIMAL type and the conversion from INTEGER, I'm checking it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, got the problem. The items in your db have a flag that is a decimal = `1.0`.

The following query works fine

```
select from item where flag = decimal('1.0')
```

but of course it's not a solution.
I'm implementing a fix for this, I'll keep you posted

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @tanhv90 

I just pushed a fix in 2.2.x branch, the fix will be released with 2.2.11

Thanks

Luigi

**Comment by tanhv90** [comment]
Hi @luigidellaquila 

Thank you so much for your prompt support.

Best regards,
Tan
