### ISSUE TITLE
Documentation for OClass::getInvolvedIndexes(String...) is wrong

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb#6743]
[Here](https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/metadata/schema/OClass.java#L380), have a look.

**Comment by luigidellaquila** [comment]
Hi @maseev 

Good catch, thank you for reporting!

Just pushed a fix

Thanks!

Luigi
