### ISSUE TITLE
NULL value was NOT indexed as documented

### ISSUE THREAD

**Issue by tanhv90** [orientechnologies/orientdb#6745]
## OrientDB Version, operating system, or hardware.
- v2.2.10

## Operating System
- [x] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I created a class node item with 2 properties id and flag

> **id:** type STRING, index: UNIQUE
> **flag:** type DECIMAL, it can be set by 1, 0, or null value. Index: NOTUNIQUE

I see that NULL value in **flag** was not indexed.
> select count(*) from item
It returns 38589

Count number of item was indexed by **flag**

> select count(*) from index:item.flag
It returns 34217

And the number of null values in flag is:
> select count(*) from item where flag is null
It returns 4372

I attached my test database at [here](https://drive.google.com/open?id=0B-9uJbevAJq9UjZRMWRKMkYwWE0)

**Comment by laa** [comment]
Hi @tanhv90 , I  can not open your file could you upload it again ?

**Comment by tanhv90** [comment]
Hi @laa, 
It's [here](https://drive.google.com/open?id=0B-9uJbevAJq9YVJwekVla3VPYTA). Please help recheck.

**Comment by laa** [comment]
@tanhv90 sorry , no luck. Could you use zip algorithm for example ?

**Comment by tanhv90** [comment]
@laa 
>  sorry , no luck. Could you use zip algorithm for example ?

I use OrientDB Studio to export this database. I don't know why you can't open it.

BTW, I uploaded new file with zip algorithm for you. Please try [this](https://drive.google.com/open?id=0B-9uJbevAJq9emRmai1jWVE0dUE)

**Comment by laa** [comment]
@tanhv90 do you send me exported version ? Could you send raw binary version ?

**Comment by tanhv90** [comment]
@laa
> Could you send raw binary version ?
Sure. It's [here](https://drive.google.com/open?id=0B-9uJbevAJq9bGFwbVVkc0ROT1E)

**Comment by laa** [comment]
Hi @tanhv90 null values were indexed but count of items was incorrect. I fixed it.

**Comment by tanhv90** [comment]
Hi @laa

Thanks for your hard work.
It means that the query
> select from index:item.flag where key is null

will work correctly right now. Right?

**Comment by laa** [comment]
in new build from 2.2.x yes.

**Comment by tanhv90** [comment]
Thank you!

**Comment by tanhv90** [comment]
Hi @laa 

I have tested this issue in 2.2.11. 
This query works fine.
> select count(*) from index:item.flag

But the following query still returns nothing.
> select from index:item.flag where key is null

Please help recheck!

**Comment by tanhv90** [comment]
Hi @laa 

I see that just a count(*) query works now.

> select distinct(key) from index:item.flag
Just returns `0` and `1`

> select from index:item.flag
Just returns 34234 records (only return for key = 0 and key = 1)

So I think this fix not covered all cases.

**Comment by luigidellaquila** [comment]
Hi @tanhv90 

it seems to be a different problem, could you please open a separate issue, I'll check it asap

Thanks

Luigi

**Comment by tanhv90** [comment]
Hi @luigidellaquila 

Please help check #6777 

Thanks,
Tan

**Comment by luigidellaquila** [comment]
Thanks!

Luigi
