### ISSUE TITLE
ignoreNullValues has no effect if defined through getDefinition().setNullValuesIgnored() the Java API

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#6746]
## OrientDB Version, operating system, or hardware.
v2.2.10, MacOS X

## The problem
This issue is based on the discussion #6681. Andrey Lomakin (@laa) asked me to create a new issue for this.

Here is a java snippet that creates a single vertex type with a single property and tries to create three nodes (two of them without the property). It crashes with a "found duplicated key 'null'" error, even when ignoreNullValues is set.

```java
OrientGraphNoTx graph = ...

OrientVertexType type = graph.createVertexType("Test");
OProperty property = type.createProperty("aProperty", OType.STRING)
		.setMandatory(false)
		.setReadonly(false)
		.setNotNull(false);

// create the index Test.aProperty
List<Parameter<String, String>> parameters = Arrays.asList(
		new Parameter<>("type", OClass.INDEX_TYPE.UNIQUE.name()),
		new Parameter<>("class", type.getName()));
graph.createKeyIndex(property.getName(), Vertex.class, parameters.toArray(new Parameter[0]));

// set ignore null values
for (OIndex<?> oIndex : graph.getVertexType(type.getName()).getIndexes()) {
	oIndex.getDefinition().setNullValuesIgnored(true);
}

// create vertices
graph.addVertex("class:" + type.getName());
graph.addVertex("class:" + type.getName(), "aProperty", "aString");
graph.addVertex("class:" + type.getName());
```

`Exception in thread "main" com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Test: found duplicated key 'null' in index 'Test.aProperty' previously assigned to the record #17:0`

## Potential Improvements
Anyway, `getDefinition().setNullValuesIgnored()` is not a very practical way to set ignoreNullValues. In terms of API, I think the best way to do this would be to have a Parameter for "ignoreNullValues", e.g.:
```java
Parameter[] parameters = new Parameter[] {
        new Parameter<>("ignoreNullValues", "true"),
        new Parameter<>("type", OClass.INDEX_TYPE.UNIQUE.name ()),
        new Parameter<>("class", "SomeType")
}
graph.createKeyIndex("someProperty", Vertex.class, parameters);
```
Blueprints specifically introduced the [Parameter ](http://www.tinkerpop.com/docs/javadocs/blueprints/2.5.0/com/tinkerpop/blueprints/Parameter.html) class for the purpose of setting implementation-specific parameters.

**Comment by laa** [comment]
Hi @benjaminbillet you got me wrong. Changing of OIndexDefenition is an unreliable way to change index parameters. Instead of that, I agreed that it is useful to support Parameter for  "ignoreNullValues". I close this issue as invalid and create new one https://github.com/orientechnologies/orientdb/issues/6747 .

**Comment by benjaminbillet** [comment]
Oops, my bad. Sorry for the inconvenience.

**Comment by laa** [comment]
))
