### ISSUE TITLE
LIMIT SKIP & ORDER BY - Paging Issue

### ISSUE THREAD

**Issue by ruituraj** [orientechnologies/orientdb#6748]
## OrientDB Version, operating system, or hardware.
- 2.2.6
## Operating System
- [ ] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
`select mid, path, sz, created FROM (select * from Media ORDER BY created DESC LIMIT 20 SKIP 1)` should skip the first record but it returns all the results.

This query `‘select * from Media ORDER BY created DESC LIMIT 20 SKIP 1’` skips the first record and returns remaining records, which I intend to do.

when I combine it like this `‘select mid, path, created FROM (select * from Media ORDER BY created DESC LIMIT 20 SKIP 1)’` it **doesn’t** skip the records. I would expect it to get details for only filtered records but returns details for all

The issue is caused by 'ORDER BY' & 'LIMIT-SKIP' interaction.

**Comment by luigidellaquila** [comment]
Hi @ruituraj 

Thank you for reporting, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @ruituraj 

I just pushed a fix on 2.2.x branch. It will be released with 2.2.11

Thanks

Luigi

**Comment by ruituraj** [comment]
Awesome, thanks Luigi!

**Comment by ruituraj** [comment]
@luigidellaquila is this fix released with 2.2.11?

**Comment by luigidellaquila** [comment]
Hi @ruituraj 

Yes, it is

Thanks

Luigi

**Comment by ruituraj** [comment]
Thanks!
