### ISSUE TITLE
Allow returning @depth from MATCH

### ISSUE THREAD

**Issue by lodrion** [orientechnologies/orientdb#6750]
`MATCH` provides much better syntax than `TRAVERSE,` but does not allow capturing `@depth` context variable. 

It would be very convenient to have the ability to return `@depth` from `MATCH` as well, so that it would be a proper superset of `TRAVERSE`

Thanks

**Comment by luigidellaquila** [comment]
Hi @lodrion 

Unfortunately there is no such option for now, but I think it would be really useful.
I'm flagging it as an enhancement, I'll work on it as soon as I can

Thanks

Luigi

**Comment by lvca** [comment]
@luigidellaquila is this already supported in 3.0?

**Comment by luigidellaquila** [comment]
Not yet, please keep it open

Thanks

Luigi
