### ISSUE TITLE
Making 1st query fast

### ISSUE THREAD

**Issue by yon86** [orientechnologies/orientdb#6754]
## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

when I use orientdb with the c# binary driver my 1st request is always really slow like 20 sec...is there a way to make sure the connection is always open from oriendb server...even if there are no requests for a  while the next request will take a long time as well. I appreciate all the help. thank you

**Comment by lvca** [comment]
Could you provide us the output of your query with the `EXPLAIN` prefix? Please run it twice and write here both results.

**Comment by yon86** [comment]
its not the query that's the issue...the query might be anything from a simple select to a complex query but if the server is not active then the query that comes 1st will always be slow....I hope this explains the issue. Thank you

**Comment by lvca** [comment]
Can you execute a test query at the beginning, so you have everything set up for the run-time queries? Even this: `select from V limit 1`

**Comment by anber500** [comment]
We use Python and have observed the same behavior. This is especially problematic on databases with millions of records. Once the first query runs, everything seem to run smoothly. This phenomenon is usually observed when connecting to read nodes that have not been accessed in a while.

This can also be witnessed when opening the studio. The login takes up to 20 seconds but after that it seems to respond at an acceptable speed. 

I have had witnessed massive slowdowns while the database is rebuilding it's indexes but that's to be expected. I don't know if it's related.

Is there a caching setting that could affect this?

**Comment by lvca** [comment]
We improved our SCAN operation. Anyway, in order to cache data, just run a query at application startup, so all the data you need is in RAM.
