### ISSUE TITLE
Can not sign OrientDB's Contributor License Agreement

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#6761]
I'd like to contribute to the OrientDB base code with some small improvements I have done to the Object API, but I can not sign the contributor license agreement.

I fill out the CLAHub form but when I submit the form I get a server error (it's not a validation error).

![error-clahub](https://cloud.githubusercontent.com/assets/5831026/18987177/bdb08f56-8700-11e6-9050-705a5b232dc3.jpg)
).

**Comment by lvca** [comment]
Hi @diegomtassis, it looks like CLAhub has problems on these days. Forget it for now, are you able to send the PR?

**Comment by diegomtassis** [comment]
https://github.com/orientechnologies/orientdb/pull/6769
