### ISSUE TITLE
uuid() function not working if used in a property of an abstract class

### ISSUE THREAD

**Issue by Pro-Vizion** [orientechnologies/orientdb#6771]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[X] - .rc1[ ] .beta2[ ] .beta1[ ] 

## Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

if a new document is inserted, all the previous documents are getting the new generated id

**Comment by luigidellaquila** [comment]
Hi @Pro-Vizion 

I'm not sure I got the point, could you please post an SQL script to reproduce the problem?

Thanks

Luigi

**Comment by Pro-Vizion** [comment]
Hi,

to reproduce : 
```
CREATE CLASS _test ABSTRACT
CREATE PROPERTY _test.id string
ALTER PROPERTY _test.id default uuid()
CREATE CLASS test EXTENDS _test
CREATE PROPERTY test.name string
```

Now, if we insert a record : 
`INSERT INTO test (name) VALUES ("Pascal")`
![odb_bug1](https://cloud.githubusercontent.com/assets/19283770/19067804/0d496322-8a20-11e6-9909-3a3570c766c7.png)

and another one : 
`INSERT INTO test (name) VALUES ("Aubry")`
![odb_bug2](https://cloud.githubusercontent.com/assets/19283770/19067826/1a3abe46-8a20-11e6-8e98-6e1fd0036b82.png)

Both, have the same uuid.

**Comment by luigidellaquila** [comment]
Hi @Pro-Vizion 

If you execute 
```
ALTER PROPERTY _test.id default uuid()
```
the `uuid()` function is executed during the ALTER PROPERTY statement execution and its value is saved as default value, so the result is what you are obtaining.

To do what you need, you can do the following:
```
ALTER PROPERTY _test.id default "uuid()"
```
(see the quotes around `uuid()`)

Unfortunately this use case is not as easy as it seems, you can find a detailed description of this behavior here: 
https://github.com/orientechnologies/orientdb/issues/6333#issuecomment-230101894

I'm closing this, as the main problem will be tracked on the linked issue

Thanks

Luigi

**Comment by smolinari** [comment]
@luigidellaquila - As a workaround, could this also be solved with a dynamic hook, that calls the UUID function at record creation?

Scott
