### ISSUE TITLE
Distributed orientDB node becomes unreachable for unknown reasons 

### ISSUE THREAD

**Issue by syzdykov** [orientechnologies/orientdb#6772]
## OrientDB Version, operating system, or hardware.
- v2.2 SNAPSHOT[x]
## Operating System
- [x] Linux
## Expected behavior and actual behavior

In our system we have two distributed database nodes. Periodically we faces with issue when one of nodes become unreachable for unknown reasons. I can see process of this node, but when I try to connect via console, it stucks on connecting. In orientDB logs I saw "out of memory" error messages and increased heap in server.sh

> ORIENTDB_OPTS_MEMORY="-Xms512m -Xmx4g -Dstorage.diskCache.bufferSize=8000"

but it seems this hasn't helped us.
Our database size is 2.3GB and I have no idea how it can produce out of memory errors.
Here is crashed node logs:
https://www.dropbox.com/s/605xsy93msygjzb/crashed-orient-log.txt?dl=0

Here is stacktrace of crashed node (it was unreachable from console when I got this stacktrace):
https://www.dropbox.com/s/5nmge3mswgxbsb9/crashed_node_stacktrace.txt?dl=0

**Comment by lvca** [comment]
How much available RAM do you have before to start OrientDB? Please remember that the sum of `-Xmx4g` and `-Dstorage.diskCache.bufferSize=8000` must be minor of the available RAM.

**Comment by syzdykov** [comment]
About 15Gb

**Comment by syzdykov** [comment]
@lvca What do you think about available RAM?
What can be the reason of our problem and how we can to fix it?

**Comment by lvca** [comment]
@syzdykov is this issue still present with a recent 2.2.x?

**Comment by lvca** [comment]
Closing this issue, because of no response after a while. In case this issue is still valid, please comment this. Thanks.
