### ISSUE TITLE
MATCH Syntax - Support GROUP BY and ORDER BY

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#6775]
Hi,

It seems that ORDER BY is not supported by the MATCH syntax. This is an enhancement request to support it

Thanks,

**Comment by luigidellaquila** [comment]
Hi @santo-it 

it's in my TODO list for 3.0 ;-)

Thanks

Luigi

**Comment by santo-it** [comment]
and group by as well. thanks

**Comment by santo-it** [comment]
order by : added in 3.0.0-m2, commit https://github.com/orientechnologies/orientdb/commit/49f10bf67a38c24751bb777c4703bda128b8c14b - duplicate of issue https://github.com/orientechnologies/orientdb/issues/7021

**Comment by luigidellaquila** [comment]
Thank you for pointing it out @santo-it !
In next few days I'll also support GROUP BY and aggregate functions

Thanks

Luigi

**Comment by lvca** [comment]
@luigidellaquila is GROUP BY already implemented?

**Comment by luigidellaquila** [comment]
No, not yet, it will be in the GA

**Comment by santo-it** [comment]
hey @luigidellaquila 

thanks for implementing order by

this order by and match is not working for me, as a fyi - perhaps because this is a more complex scenario:

MATCH {class: Customers, as: c, where: (OrderedId=1)}--{class: Locations, as: loc}--{class: Customers, as: otherCustomers, where: (OrderedId<>1)} 
RETURN otherCustomers.OrderedId, loc.Name, loc.Type
ORDER BY otherCustomers.OrderedId ASC

thanks,

**Comment by luigidellaquila** [comment]
Hi @santo-it ,

Checking it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, got the problem. With the MATCH statement, the ORDER BY is calculated on the final result, so at that stage it doesn't have all the info to re-calculate `otherCustomers.OrderedId`.

If you write the query this way it will work:

```
MATCH {class: Customers, as: c, where: (OrderedId=1)}--{class: Locations, as: loc}--{class: Customers, as: otherCustomers, where: (OrderedId<>1)} 
RETURN otherCustomers.OrderedId, loc.Name, loc.Type
ORDER BY `otherCustomers.OrderedId` ASC
```

But I guess it can be fixed, please leave this open

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Just pushed a fix for this bug plus the support of GROUP BY and aggregate projections.

Closing, thanks

Luigi
