### ISSUE TITLE
Wrong search result when querying data from INDEX

### ISSUE THREAD

**Issue by tanhv90** [orientechnologies/orientdb#6777]
This issue related with #6745 
## OrientDB Version, operating system, or hardware.
- v2.2.11
## Operating System
- [x] Windows
## Expected behavior and actual behavior

Hi @luigidellaquila 
As per your request, I create a new issue here. Please help recheck.

I have a schema **item** as below

> **id:** type STRING, index: UNIQUE
> **flag:** type DECIMAL, it can be set by 1, 0, or null value. Index: NOTUNIQUE

When trying to query from index:item.flag, I found that:

Select all keys from the index:

> select distinct(key) from index:item.flag
> Just returns 0 and 1 (null key doesn't exist)

And

> select from index:item.flag
> Just returns 34234 records (only return for key = 0 and key = 1)

But the count(*) returns correctly result

> select count(*) from index:item.flag
> It returns 38596

Please find database used for testing [here](https://drive.google.com/open?id=0B-9uJbevAJq9bGFwbVVkc0ROT1E)

Thanks.

**Comment by luigidellaquila** [comment]
Hi @tanhv90 

Thank you for reporting, I'm checking it

Luigi

**Comment by tanhv90** [comment]
One yes passed so fast. Any update on this issue @luigidellaquila , @laa

**Comment by luigidellaquila** [comment]
Sorry @tanhv90 

It seems it fell through the cracks, I'll try to check it asap. In the meantime, did you try it with latest stable (2.2.30)? We fixed a bunch of problems in the meantime

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @tanhv90 

I just pushed a fix that resolves the problem of the index query.

There is still a problem with the `SELECT distinct(key)` (it still does not return null keys), I'm checking it as well

Thanks

Luigi
