### ISSUE TITLE
select via REST API returns max 1000 records (documents)

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6778]
## OrientDB Version, operating system, or hardware.
- v2.2.10

## Operating System
- [x] Linux

## Expected behavior and actual behavior
Running a SELECT query via REST API to 'slurp' many records from a class, seems not possible to let it return more than 1000 records per query despite different values of the "limit" argument in the query.

-> can this limit be raised ?

**Comment by maggiolo00** [comment]
@rdelangh 

which API did you use?

**Comment by rdelangh** [comment]
@maggiolo00 from Perl, using the CPAN modules REST::Client, sending JSON batches to the HTTP API of ODB

**Comment by maggiolo00** [comment]
yeah i mean which rest api do you use  Command API?

http://orientdb.com/docs/2.2/OrientDB-REST.html#command

**Comment by rdelangh** [comment]
@maggiolo00 
We use the HTTP API.
But, oops ! My fault, I go via own modules to compose the JSON query for a SELECT, and there I hard-coded the 1000 limit myself :-( 
Still usefull to know if via this mechanism, there is any (and if so, which) limit set on the number of records that can be returned from a single SELECT through the HTTP API?

**Comment by maggiolo00** [comment]
you can  limit in the query

```
select form <class> limit <limit>
```

or you can 

use the limit in the protocol

http://orientdb.com/docs/2.2/OrientDB-REST.html#command

**Comment by maggiolo00** [comment]
There is no limit on the number of records
