### ISSUE TITLE
WAL mode changed to false, causes fail on batch commit

### ISSUE THREAD

**Issue by sps90** [orientechnologies/orientdb#6781]
## OrientDB Version, operating system, or hardware.
- v2.2.4
- java version 1.8.0_101
## Operating System
- [ ] Linux
- [ ] MacOSX
- [x ] Windows
- [ ] Other Unix
- [ ] Other, name? 

I am working on defining schema for loading data in batches from pyorient ogm.
As per performance tuning documentation, i have changed the value of storage.useWAL=false in <properties> tag in orientdb-server-config.xml, but the following error occurs 
_**"pyorient.exceptions.PyOrientCommandException: com.orientechnologies.orient.core.
exception.OStorageException - WAL mode is not active. Transactions are not supported in given mode"**_

![image](https://cloud.githubusercontent.com/assets/11362115/19082137/af2044a4-8a11-11e6-9798-d95117a29613.png)

Any help is appreciated!

**Comment by lvca** [comment]
Are you doing a first importing? Otherwise, it's not suggested removing the journal to guarantee consistency.

Batches are using transactions, that's why they require the WAL to be enabled.

**Comment by sps90** [comment]
Yes, it's still the first batch of objects that I am importing to the database.

**Comment by lvca** [comment]
I suggest you to create TX (like batches) with about 5k records with WAL enabled and see how it's going. Please use last 2.2.11.

**Comment by lvca** [comment]
I'm sorry it's the only way from Python. If you want to go faster, use a Java client (OrientDB ETL or your Java app) with PLOCAL connection.
