### ISSUE TITLE
Saving JSON data with embedded objects fails

### ISSUE THREAD

**Issue by borov333** [orientechnologies/orientdb#6782]
## Operating System
- [X] Linux
- [X] MacOSX

## Expected behavior and actual behavior
Expected to save serialized JSON classes with embedded classes when they one-to-one have the same structure as classes in orientdb, but it doesn't work. Per Luigi's request, I'm pasting the issue here from the google groups. Just for the reference, my original question can be found here: https://groups.google.com/forum/#!topic/orient-database/hFhYyE5da-A

I'm working on the application, which will need to store different objects of complex structure (objects inside of objects). For example, Person object may have Address object, Contacts, and may need to link to some other objects, etc. Sometimes these objects may go few levels deep. I created the class with an embedded class and it all works good when I run query in the console. I have to use these extra fields ("@type":"d", "@class":"Address") in the embedded object in order for the query to understand the embedded object.

Here is example of a working query:
```
insert into Account (company, website, address) values ('Seller 0', 'http://www.seller0.com', {"@type":"d", "@class":"Address", "street":"1234 Sunset Dr.", "city":"Santa Monica", "state":"CA", "zip":"90046"})
```
The problem I"m running into, is that I will need to do this functionality dynamically in Java and I have modeled my java classes to be exact as the classes in the database, which makes sense to me and would save a lot of time. However, when I serialize my Java object into JSON and create ODocument object from this JSON, on save() the database is not taking it. Here is example of one simple serialized java object:
```
json = 
{
    "account": "#25:0",
    "meta": {
        "created": "2016-10-03T21:10:21.77-07:00",
        "ip": "0:0:0:0:0:0:0:1",
        "contentType": "application/x-www-form-urlencoded",
        "userAgent": "PostmanRuntime/2.5.2"
    },
    "data": "firstName=Jessica&lastName=Smith"
}
```
When I use this logic it fails:
```
**ODocument d = new ODocument("RawLead").fromJSON(json);
d.save();**            
```
I get Java error: `**Error: Error during saving of record with rid #-1:-1**`

For the above JSON I have the following "RawLead" class with embedded "LeadMetadata" class:
```
CLASS 'RawLead'
PROPERTIES
+----+-------+--------+-----------------+---------+--------+--------+----+----+-------+-------+

|#   |NAME   |TYPE    |LINKED-TYPE/CLASS|MANDATORY|READONLY|NOT-NULL|MIN |MAX |COLLATE|DEFAULT|
+----+-------+--------+-----------------+---------+--------+--------+----+----+-------+-------+
|0   |data   |STRING  |                 |true     |false   |true    |    |    |default|       |
|1   |meta   |EMBEDDED|LeadMetadata     |true     |false   |true    |    |    |default|       |
|2   |account|LINK    |Account          |true     |false   |true    |    |    |default|       |
+----+-------+--------+-----------------+---------+--------+--------+----+----+-------+-------+

CLASS 'LeadMetadata'
PROPERTIES

+----+-----------+--------+-----------------+---------+--------+--------+----+----+-------+---------+
|#   |NAME       |TYPE    |LINKED-TYPE/CLASS|MANDATORY|READONLY|NOT-NULL|MIN |MAX |COLLATE|DEFAULT  |
+----+-----------+--------+-----------------+---------+--------+--------+----+----+-------+---------+
|0   |created    |DATETIME|                 |false    |true    |false   |    |    |default|sysdate()|
|1   |ip         |STRING  |                 |true     |false   |true    |7   |40  |default|         |
|2   |userAgent  |STRING  |                 |true     |false   |true    |1   |100 |default|         |
|3   |contentType|STRING  |                 |true     |false   |true    |4   |50  |default|         |
+----+-----------+--------+-----------------+---------+--------+--------+----+----+-------+---------+
```
I assume it's because I don't have the magic fields ("@type":"d", "@class":"Meta") in my JSON. If this is correct, I need an advise on how to go around it or maybe there is a different and more straight forward way of doing it? I was hopping that I can simply serialize my exact Java objects into JSON format then create ODocument and simply save it in the database. That would be so awesome.

Let me know if you need any additional info or if you want me to try anything. Thanks.

**Comment by luigidellaquila** [comment]
Hi @borov333 

I just pushed a fix on 2.2.x, the fix will be released in 2.2.12

Thanks

Luigi

**Comment by borov333** [comment]
Great - thanks, looking forward!

**Comment by borov333** [comment]
@luigidellaquila 

Do you know when the 2.2.12 will be available? I have so many logic elements depend on this bug fix.

Thanks.

**Comment by luigidellaquila** [comment]
Hi @borov333 

I hope we'll be able to do it this week

Thanks

Luigi

**Comment by borov333** [comment]
Luigi,

I just upgraded to v 2.2.12 and executed my tests to create a document using fromJson(...), but it seems to me that the bug is still there. Look at these 2 tests below:

This one is a plain JSON as it is generated by the Gson parser. All fields are identical to the class structure. It just sadly fails.
```
Raw Lead JSON:
{
    "account": "#25:0",
    "meta": {
        "created": "2016-10-21T20:49:54.943Z",
        "categoryId": 1,
        "source": "AAA",
        "subSource": "sub-aaa",
        "ip": "0.0.0.1",
        "contentType": "application/x-www-form-urlencoded",
        "userAgent": "Mozilla - Firefox"
    },
    "data": "categoryId=2&firstName=Mike&lastName=Smith"
}
Error: Error during saving of record with rid #-1:-1
	DB name="Customers"
```

This one has `"@type":"d", "@class":"RawLead"` for the outer class and ` "@type":"d", "@class":"RawLeadMeta"` for the inner class added. Only with these magic I can create document from JSON directly.
```
Raw Lead JSON:
{
    "@type":"d", "@class":"RawLead",
    "account": "#25:0",
    "meta": {
        "@type":"d", "@class":"RawLeadMeta",
        "created": "2016-10-21T20:49:54.943Z",
        "categoryId": 1,
        "source": "AAA",
        "subSource": "sub-aaa",
        "ip": "0.0.0.1",
        "contentType": "application/x-www-form-urlencoded",
        "userAgent": "Mozilla - Firefox"
    },
    "data": "categoryId=2&firstName=Mike&lastName=Smith"
}
Raw lead saved
```

Here is my java logic:

```
        try (ODatabaseDocumentTx db = DbPool.getConnection()) {
            String json = Json.toJson(lead);
            System.out.println("Raw Lead JSON:\n"+ json);
            
            ODocument d = new ODocument("RawLead").fromJSON(json);
            try {
                d.save();
                System.out.println("Raw lead saved");
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        }
```

Here are the 2 participating classes:

```
orientdb {db=Customers}> info class RawLead
CLASS 'RawLead'
Records..............: 4
Super classes........: [V]
Default cluster......: rawlead (id=57)
Supported clusters...: rawlead(57), rawlead_1(58), rawlead_2(59), rawlead_3(60)
Cluster selection....: round-robin
Oversize.............: 0.0

PROPERTIES
+----+----------+--------+-----------------+---------+--------+--------+----+----+-------+-------+
|#   |NAME      |TYPE    |LINKED-TYPE/CLASS|MANDATORY|READONLY|NOT-NULL|MIN |MAX |COLLATE|DEFAULT|
+----+----------+--------+-----------------+---------+--------+--------+----+----+-------+-------+
|0   |statusNote|STRING  |                 |false    |false   |false   |    |    |default|       |
|1   |data      |STRING  |                 |true     |false   |true    |    |    |default|       |
|2   |meta      |EMBEDDED|RawLeadMeta      |true     |false   |true    |    |    |default|       |
|3   |account   |LINK    |Account          |true     |false   |true    |    |    |default|       |
|4   |status    |STRING  |                 |false    |false   |false   |    |    |default|NEW    |
+----+----------+--------+-----------------+---------+--------+--------+----+----+-------+-------+
orientdb {db=Customers}> info class RawLeadMeta
CLASS 'RawLeadMeta'
Records..............: 0
Super classes........: [V]
Default cluster......: rawleadmeta (id=53)
Supported clusters...: rawleadmeta(53), rawleadmeta_1(54), rawleadmeta_2(55), rawleadmeta_3(56)
Cluster selection....: round-robin
Oversize.............: 0.0

PROPERTIES
+----+-----------+--------+-----------------+---------+--------+--------+----+----+-------+---------+
|#   |NAME       |TYPE    |LINKED-TYPE/CLASS|MANDATORY|READONLY|NOT-NULL|MIN |MAX |COLLATE|DEFAULT  |
+----+-----------+--------+-----------------+---------+--------+--------+----+----+-------+---------+
|0   |subSource  |STRING  |                 |false    |false   |false   |    |    |default|         |
|1   |created    |DATETIME|                 |false    |true    |false   |    |    |default|sysdate()|
|2   |ip         |STRING  |                 |true     |false   |true    |7   |45  |default|         |
|3   |userAgent  |STRING  |                 |true     |false   |true    |1   |256 |default|         |
|4   |source     |STRING  |                 |false    |false   |false   |    |    |default|         |
|5   |categoryId |INTEGER |                 |false    |false   |false   |    |    |default|0        |
|6   |contentType|STRING  |                 |true     |false   |true    |4   |50  |default|         |
+----+-----------+--------+-----------------+---------+--------+--------+----+----+-------+---------+
```

Let me know if I can get you any other info. Really hope that this bug can be fixed ASAP as I have my project stalled on it.

Thanks,

**Comment by borov333** [comment]
Hi guys, are you looking at it and will re-open this issue or shall I re-submit it as a new issue? Thanks.

**Comment by luigidellaquila** [comment]
Hi @borov333 

I'm reopening this for a check

Thanks

Luigi

**Comment by borov333** [comment]
Let me know if I can run any additional tests on my end to help you speedup and narrow down the bug.

Also just curious, I'm the only one trying to create documents this way directly from JSON? Seems to me that this is one of the most viable features and advantages of OrientDB, but I didn't see others complaining.

**Comment by borov333** [comment]
Hi @luigidellaquila, can you please look into this bug. We really stalled in the project here.

Thanks.

**Comment by luigidellaquila** [comment]
Hi @borov333 

@tglman is checking it

Thanks

Luigi

**Comment by tglman** [comment]
hi @borov333,

I think your finding are correct, and there is actually a reason behind it. so as you said:
"This one has "@type":"d", "@class":"RawLead" for the outer class and "@type":"d", "@class":"RawLeadMeta" for the inner class added. Only with these magic I can create document from JSON directly."

This is correct you need to specify a class with "@class" if you don't do so, orient should give you an error in the same way if you specify a class that is not the same of the one specified in the schema.

Silent automatic conversion cannot be done because would mean hide a mistake in the application logic.

one thing that can come to your help is:
` ODocument d = new ODocument("RawLead").fromJSON(json, "noMap");`
the "noMap" is a setting for our json parser to force it to create ODocument from "{}" json block instead of Map, without need to specify `"@type":"d"`

for inject the `@class` field you can try to play with the Gson Type adepter: https://google.github.io/gson/apidocs/com/google/gson/TypeAdapterFactory.html  


Another suggestion, in case of updated is better to use the merge for case like your:
```
ODocument d = new ODocument("RawLead").fromJSON(json);
ODocument fromDb = db.load(d.getIdentity());
fromDb.merge(d);
db.save(fromDb);
```

hope this help.

**Comment by borov333** [comment]
Hi @luigidellaquila and @tglman,
 
Wow! I didn't expect that behavior by design. I was able to traverse the JSON tree and insert the @class along with @type properties for every object - took me some time to do the logic so that it's dynamic for different json structures.

I can understand that for the internal mechanics you may need to have these 2 magic fields in for every object and perhaps its really not a big deal when you construct a ODocument object manually once in code. 

I don't want to push my thinking forward as you're more experienced and better understand how the DB shall function internally, but wanted to share my thoughts, since I just went through this use case and perhaps other users may have similar needs.

We have many Classes where each represents a specific data structure (all have multiple tiers of embedded objects and some are embedded lists). For example an AutoInsuranceLead, which has structure like in the picture below: 

![autoinsurance](https://cloud.githubusercontent.com/assets/22382033/19794609/57f64a50-9c88-11e6-843f-9b1f80bd04cb.png)

Now, imagine that there are literally hundreds of objects to represent different types of leads for different verticals. 

Our users will submit data via and API in exact JSON structure as we defined in our database. What would really be nice is to simply take that JSON and save it in the database (since we know which class the JSON is for in each API call). If database can't understand it's structure or one of the embedded objects is not what it shall be it is perfectly fine for the database to through an exception with a message. However, because of the magic fields, we had to create a custom logic to get the actual class schema from the database (extra db call). Then, traverse the given JSON and match each node with a class name from the schema for each embedded object just to inject the proper @class field. 

First, this logic is complex, second it is unnecessary and third we're doing something that could be done inside of the database itself since all info is available in the schema for each class. 

Again, maybe most OrientDB users don't have similar use cases and it's not needed or if there's a better way to achieve the same functionality please share.

Thanks for your help and explanation on how db is working internally.

**Comment by smolinari** [comment]
This sounds like a weakness in your API and not the database. Not even MongoDB will do what you are asking for, or rather, not in that manner. I might be going out on a limb here, but it sounds like you are confounding the NoSQL concept a bit. I don't mean to be insulting. Please don't take it that way. 😄 I'll try to explain myself, but will probably fail, as I often do. LOL! In the end, I think we are both looking for similar things from ODB.

You wrote

>  in exact JSON structure as we defined in our database

ODB's internal structure or schema isn't defined through JSON, nor is it determinable out of JSON. In other words, if you send JSON to ODB, ODB simply stores that data as it is and expects you and your application to keep up the the data structures, aka the schema. ODB, as you have found out, won't bother with those structures in JSON objects and them meeting any schema definitions. That is the way any schemaless design is actually supposed to work. The schema is in the application. That is also how MongoDB works and was primarily designed to do. [It is also something I am asking for here too.](https://github.com/orientechnologies/orientdb-labs/issues/13) 

Someone from ODB please correct me if I am wrong in my assumption above. 

I am not sure if you realize this, but if you do store data through JSON objects in ODB, and avoid schema definitions (because they aren't enforced anyway), that data isn't indexable at all either. You will have a doozy of a time doing queries on that data, namely, if it gets anywhere near big, you will be screwed. This is something I personally find a shame. To me, it means ODB must take the "schemaless" out of their marketing, because storing schemaless data in ODB and be able to query on it simply isn't going to work at all. 

I'd suggest looking for ways to abstract the data structures in your application better. 

One other idea is to use GraphQL as your API. This, from what I take of your use case, might simplify (by giving you that abstraction) to simplify your API. Just an idea. It sounds like you've already invested a ton of work already. I hope I am not disappointing you.

Scott

**Comment by tglman** [comment]
hi @borov333,

Can we consider this solved for you ?

Bye

**Comment by borov333** [comment]
Hi @smolinari,

I appreciate you taking your time to explain the details and raising concerns. I believe I may've confused you in few of my earlier statements which led you to believe that we're storing the data based on the JSON format in schema-less way. It is actually the complete opposite. We are not using schema-less design in any parts of our application (at least for now we haven't had a need for it).

All classes are created in a complete schema-full manner. In fact, almost all properties have further constraints, which are referenced in the internal data validation,  and indexes placed on the most commonly queried properties. 

What I really meant by "Our users will submit data via and API in exact JSON structure as we defined in our database", is that we use JSON only as a means of inserting the data into well structured schema-full classes. We derive the JSON format from the classes structure. We then give our users specs on what data and structure we expect to get via API and asking them to send it to us in the JSON format. 

This way, we can quickly save the data utilizing fromJson(...) method of an ODocument object. It works fine, because we receive the data for so many classes and we don't have to code each class separately to just insert its data. With such flexibility, we can always update the data structure or add new classes into the database. All that we'll have to do is to simply update the specs for our users and all without touching the line of code.

The only caveat I ran in was that we need to inject @class into each JSON object in order to create ODocument using fromJson(...) method. This seems to be a short coming of the database, since the class structure is already known to the database and it could simply take the JSON string in the fromJson(...) method and parse it by referencing the given class name and its schema. If it runs into issues with the structure it can through an exception, but if not, it can build the class by referencing the internal class schema. 

We succeeded to code this outside to just inject @class into each object inside of the JSON structure and then we use fromJson(...) method to successfully store the data. But, it would be nice if db could do it internally, just take the JSON string and if it is correctly structure as defined in the Class store it.

Again, maybe our use case is too specific for us and there is no real need for others. Just sharing my thoughts here :)

**Comment by borov333** [comment]
Hi @tglman,

Yes, please close this issue. Thanks.

**Comment by smolinari** [comment]
@borov333 - maybe it is my misunderstanding with how the fromJson() method works. If it actually takes the defined schema into account, then my whole premise was wrong (and why I asked for correction). I am not a Java dev. 😄 

One thing does still leave an open question for me. 

You said

>it can build the class by referencing the internal class schema. 

Can you explain that a bit more? Are you expecting ODB to build schema from the JSON?

Scott

**Comment by borov333** [comment]
Gladly @smolinari, 

> it can build the class by referencing the internal class schema

I think I typed it too fast :) Should be instead "it (the database) can create a class data (vertex) by referencing the internal class schema. Here is a simple example:

Class Person has property contact (embedded class) and vehicles (embedded list). I can ask our users to simply send us a JSON like this:
```
{
    "contact": {
        "firstName": "Mike",
        "lastName": "Stivenson",
        "email": "stivenson@yahoo.com"
    },
    "vehicles": [
        {
            "year": 2015,
            "make": "Toyota",
            "model": "Prius",
            "subModel": "LX"
        }
    ]
}
```

If the JSON is in the correct structure as the class person expects, which designed in a complete schema-full way, then I'd expect OrientDB to take this JSON and create the class data (vertex). If the JSON has something that is not defined by the Class Person schema, through an exception. 

I hope you can see how simple it would be to use the fromJson(...) method and give it the JSON string in the format which represents the Class's properties structure. This way we can have many different classes defined in different formats and as long as we know the class's name we can drop the JSON string and viola - we got a new record inserted into schema-full class. We can create and change classes in the OrientDB without needing to touch the code again - full flexibility. Instead, we had to create a custom logic which must retrieve the class's schema from the db first, then traverse both the given JSON and the schema object to find a right class name from the schema for each embedded object and insert it as @class into each JSON object. All that effort just because we can't use fromJson(...) method without the @class magic field.

So, in the end we achieve the same result we aimed at but now our JSON must look like this in order for fromJson(...) to even work:

```
{
    "@type": "d",
    "@class": "Person",
    "contact": {
        "@type": "d",
        "@class": "Contact",
        "firstName": "Mike",
        "lastName": "Stivenson",
        "email": "stivenson@yahoo.com"
    },
    "vehicles": [
        {
            "@type": "d",
            "@class": "Vehicle",
            "year": 2015,
            "make": "Toyota",
            "model": "Prius",
            "subModel": "LX"
        }
    ]
}
```

The reason I originally raised this question is because we doing all this logic just to inject @class fields into the JSON and we reference Class's schema for it to be dynamic. The thing is, OrientDB already has the schema for each class and it knows the class name for each of the embedded objects (assuming they are defined) and therefore it could theoretically perform this action internally during the un-marshaling process when processing the given JSON in fromJson(...) method. That would be less buggy than our custom code and make things simple.

Maybe there's a good reason why it's not working this way that internal developers can share? Or maybe it can be implemented in the future releases?

**Comment by borov333** [comment]
That's right. To find out which class does a JSON belongs to we require user to send a special category id in the API call, which is internally mapped to a class name. We use that category id for other validation purposes, such as permissions check, etc. prior to even saving the JSON. 

So, when we get to the point of saving the record we already know the class name and simply doing this: 
```
save(String className, String json) {
    ....
    ODocument d = new ODocument(className).fromJSON(json);
    d.save();
}
```

Your suggestion to embed "person" right into the JSON structure is also great and flexible. A developer can just grab the first JSON object and use it's name for the class name and further select the JSON's sub-structure as the actual class structure to pass into fromJSON(...) method. Or, even better, would be nice to have the fromJSON2(...) method which would use the first JSON object as the class name if the class name is not provided in `new ODocument()` constructor, but that's even more to ask for :)

Now do you see how helpful would it be for us to avoid going through the extra custom JSON and Class Schema traversing logic for @class field injection into the given JSON?

**Comment by smolinari** [comment]
Sure. Your request is a similar to my OEP I linked to above. I'm just coming at it from a different angle. The basic premise is, the schema metadata should be in the background and ODB should be taking care of it automatically. That is what makes a NoSQL database NoSQL. LOL!  

If I may ask, why can't the API use class names directly? Why the need for the conversion from cat ids?

Also, how and when do relationships enter your scenario?

Scott

**Comment by borov333** [comment]
We debated for sometime internally if we need the conversion from id to a class name. Ideally we don't need to use the conversion and can reference the class names directly that's true. The reasoning behind was not to expose the internal structure to external users. 

Our clients need to indicate what data they submitting. If we tell them to use the class name (inside or outside of JSON), what if we decide to rename the class internally? In that case we'll have to inform all users to use the new name and for some it'll require to reprogram API on their end. IDs allow us to provide that layer of indirection. That's pretty much the only reason for the conversion.

Regarding the "how and when do relationships enter your scenario", can you please explain what do you mean?

**Comment by smolinari** [comment]
Currently we're talking about storing documents, but nothing about storing relationships between the documents. In the diagram you posted above about the lead, you have a number of relationships. Some could be embedded, like the address, but what about the rest? Or are they all embedded?

Scott

**Comment by borov333** [comment]
O, I see. Yes, all of them are embedded. They simply define the structure of the document for at least for this use case. We did however brainstormed about a possibility to create a real graph from different parts of the incoming documents, but at this time we don't have the need for it yet.

**Comment by smolinari** [comment]
Interesting you took OrientDB for your use case. MongoDB sounds like a much better fit from a document storage perspective. But certainly, if you intend to use relationships later, OrientDB is a great choice too. I came from wanting to use MongoDB in my "dream" project to OrientDB and I am still sticking with them. I think Version 3 will be a breakthrough, as they have gained a lot of experience over the few years with the first two version. They now know, where to tighten the screws to get ODB to be a main player. I would even say, it will blow past Neo4J and even could fight with MongoDB, should they get the quality, performance and intuitiveness of the APIs down pat, which is what they are heading for from what I can tell. The only thing I wish for more is the NoSQL model be better supported with self-determining schema and indexing (as explained in my OEP). If they get that done too, ODB will represent one of the most and modern multi-model databases on the market. I can't wait! 😄  

Scott

**Comment by borov333** [comment]
I like the approach OrientDB took by combining graph and document databases in one. I think it's smart and can solve real business problems more efficiently. We used MySQL for years and recently used Redis for speed and caching, but once we started to operate in multi million records space things with MySQL started to degrade. Of course we could invest more in re-architecting certain logic and get faster servers, but it just didn't feel right. From my analysis we can dramatically benefit with graphs in some parts of the system and with documents in the other. We get a lot of data in JSON format and before we had to just drop it into tables and later process them in code. With OrientDB I really like the idea of schema and schema-less concepts and it seems like a perfect fit for our use cases.

Again, I'm personally really fresh to graphs and documents databases, I'm coming from the relational world and there is obviously a learning curve. But, so far what Orient does feels right and simple enough to get up to speed. I feel their vision and simplicity approach. Those are primary reasons for us to select them. We working on this new project and from ground up decided to architect it with graph and documents db. So far Orient really seems as the right choice we made. They do have few kinks here and there that should be ironed down, but I love the fact that the guys are responsive. The fact that they are on top of the issue and question boards really gives us confidence that we're going with the right team.

I'm really looking forward to 3.0. Hope it won't be hard to migrate though.

**Comment by smolinari** [comment]
Interesting. Was MySQL sharding not a possible solution? 

And yes. The ODB team do have their hearts in the right place. If 3.0 turns out like I think it will and more people like us can support them monetarily too, I think OrientDB will become a more prominent player in the DB industry. 

Scott
