### ISSUE TITLE
Remove old nodes from distributed-config.json

### ISSUE THREAD

**Issue by wazmataz** [orientechnologies/orientdb#6784]
## OrientDB Version, operating system, or hardware.
- v2.2.8

## Operating System
- Linux

Is there a way to remove old nodes from the generated distributed-config.json? We were running a cluster of 5 nodes, removed one of them so there were 4, then created a new node so there were 5 again. Our distributed-config.json however shows 6 nodes (see below) which we believe leads to the following error message:
`Quorum (6) cannot be reached because it is major than available nodes (5)`

## default-distributed-db-config.json
`{
    "autoDeploy": true,
    "hotAlignment": false,
    "readQuorum": 1,
    "writeQuorum": "all",
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "*": {
            "servers" : [ "<NEW_NODE>" ]
        }
    }
}`

## Extract from distributed-config.json

`"servers":["node1475586666338","node1475586559914","node1475239781645","node1475586428481","node1475586275508","node1475676408418","<NEW_NODE>"]`

**Comment by lvca** [comment]
Yes, `HA REMOVE SERVER <server-name>`. It's a new command introduced in 2.2.9.

**Comment by wazmataz** [comment]
Is there a way this can be automated and / or is there an alternative?

It may be my understanding but I'm wondering how this would work in a production system. If a node was to disappear from a cluster it wouldn't be possible to write to the database, because of the below error (presumably because of the writeQuorum of all), until we manually ran the command you mention. Perhaps we could change the write Quorum to the number of nodes we have but wouldn't we have the same issue if a node was to go down?

`Quorum (5) cannot be reached because it is major than available nodes (4)`

**Comment by lvca** [comment]
If your configuration is elastic, I suggest you to setup this:

`-Ddistributed.autoRemoveOfflineServers=0`

-------
"This is the amount of time (in ms) the server has to be OFFLINE, before it is automatically removed from the distributed configuration. -1 = never, 0 = immediately, >0 the actual time to wait".
-------

Default is -1.
