### ISSUE TITLE
Write with reader instead of root produces unexpected behavior

### ISSUE THREAD

**Issue by avachen1** [orientechnologies/orientdb#6791]
## OrientDB Version, operating system, or hardware.
- v2.2.4
## Operating System
- Linux
## Expected behavior and actual behavior

Writing to OrientDB with reader produces an error but still writes the data. Expected to not write any date using reader role.
## Steps to reproduce the problem

Write to OrientDB with reader role.

**Comment by SDIPro** [comment]
Tested against 2.2.11 and works correctly.

If you can reproduce against the latest release, please provide what steps you used or a simple test.
