### ISSUE TITLE
Journaling appears not to work when killing one node in a cluster of two

### ISSUE THREAD

**Issue by cjmunro** [orientechnologies/orientdb#6799]
## OrientDB Version, operating system, or hardware.
2.2.11

## Operating System
- [ ] Windows

## Expected behavior and actual behavior
When running a cluster of two nodes and killing one of them, then adding a vertex, the addition should be journaled, and synchronized when the other one comes back up.

## Steps to reproduce the problem
Download the community edition 
Follow the instructions here to set up a cluster with two nodes on the same machine (copy the directory) http://orientdb.com/docs/last/Tutorial-Working-with-distributed-graph-database.html
Start up both using dserver.bat
Connect to localhost/GratefulDeadConcert via the console (connect remote:localhost/GratefulDeadConcert username password)
Kill one node and then try adding a vertex CREATE VERTEX V SET node=2
Error message results
Error: com.orientechnologies.orient.core.exception.ODatabaseException
h rid #13:102
        DB name="GratefulDeadConcerts"
        DB name="GratefulDeadConcerts"

Error: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum (2) cannot be reached because it is major than available nodes (1)

I can't see the exact config files used in the example in the link above, so I may be missing something

**Comment by maggiolo00** [comment]
Hi @cjmunro 

that is the expected behaviour. By default the write quorum configuration is majority (n/2 +1 ). 
If you set up a cluster with 2 nodes the write quorum would be 2. If one node is down you cannot write.
See here

http://orientdb.com/docs/last/Distributed-Configuration.html

**Comment by cjmunro** [comment]
OK, thanks, the example I was following must have been 3 nodes at least for this to work

**Comment by maggiolo00** [comment]
You can use 2 nodes but you have to manually set the write quorum to 1 in the distributed configuration.
