### ISSUE TITLE
request for enhancement: do not make backup copy per default of dbase when node joins group

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6803]
## OrientDB Version, operating system, or hardware.
- v2.2.*

## Operating System
- [x] Linux

## Expected behavior and actual behavior
When an extra server node joins a group, it makes per default a copy of any database directory under its "databases/" towards a ZIPped file in "/tmp/orientdb".
Altough the idea of keeping a backup of previous situation is nice, the method is inefficient and likely impossible to work in case of huge databases (for OrientDB, we're talking about "big" databases, right ? Not something of a few GB which fits entirely in RAM nowadays).

It's not my habit to critisize any working mechanism without suggesting any alternative, but I can't do exactly that (suggesting alternative methods) due to my lack of knowledge of the ODB internals. I would suggest to document more explicitly that the user him/herself must make sure that any previous contents of "databases/" is preserved via the means available in his/her particular infrastructure (thinking about filesystem snapshots, as an example).

**Comment by lvca** [comment]
This is already supported: set at empty the backup directory and OrientDB will skip the creation of the backup:

```
-Ddistributed.backupDirectory=""
```

Or set this in the orientdb-server-config.xml file in the last section.

**Comment by rdelangh** [comment]
@lvca sorry but I added this option to the server startup command line options (in "bin/server.sh") for the 2nd node (who tries to join the group), but in its logs I see that it still does some backup : 

...
2016-10-13 17:59:24:053 INFO  [10.49.69.189]:2434 [cdrcontrols] [3.6.5] Established socket connection between /10.49.69.189:54829 and /10.49.69.190:2434 [TcpIpConnectionManager]
...
2016-10-13 17:59:32:353 WARNI [orient2]->[[orient1]] Requesting deploy of database 'navi' on local server... [OHazelcastPlugin]
2016-10-13 18:07:00:246 INFO  [orient2]<-[orient1] Copying remote database 'navi' to: /tmp/orientdb/install_navi.zip [OHazelcastPlugin]
...

Is this a backup? Or is this the location ("/tmp/orientdb/install_navi.zip") on the 2nd node (STARTING) to which the copy of the database "navi" from the 1st node (ONLINE) is collected before installing this copy into the final directory "/opt/orientdb/databases/" of the 2nd node ?

**Comment by rdelangh** [comment]
@lvca 
hi Luca, I notice that this issue has been closed but without an answer on my last question: despite that extra option in the command line for disabling the backup copy, such a backup copy is still made by a new node when it attempts to join a group.
-> can you please confirm that this option is the right one?
-> in which server version has this been properly implemented/corrected? I have now version 2.2.15, is it correctly implemented in this version?

**Comment by lvca** [comment]
@rdelangh the log you've see is when the backup is zipped to be transferred. `-Ddistributed.backupDirectory=""` should do the job. In case you can still see a backup please comment this issue again. Thanks.
