### ISSUE TITLE
liveQuery not working with 2.2.* - same code works fine in 2.1.*

### ISSUE THREAD

**Issue by jterrero** [orientechnologies/orientdb#6813]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ x] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Using liveQuery with nodejs. I used the very simple test case provided in the live query documentation

## Steps to reproduce the problem
```
config = require('../config/database');
var OrientDB = require('orientjs');
var server = OrientDB(config.database);
var db = server.use(config.credentials);


console.log('start')
db.liveQuery("live select from Users")
.on('live-insert', function(data){
    console.log(data)
})
.on('live-update', function(data){
    console.log(data)
})
.on('live-delete', function(data){
    console.log(data)
})
console.log('callback end')
```

I run the above code and then insert or update  a record into the Users class in orientdb.

When i update or insert, with 2.2 as the backend, I get nothing.

However, same exact code under 2.1 works fine, i will get a callback with the results below;
```json

{ content:
   { '@type': 'd',
     '@class': 'Users',
     username: 'johnd',
     first_name: 'John',
     last_name: 'Doe',
     email: 'johnd@missingpeople.com',
     phone: '2019825156',
     password: 'abc123',
     is_active: true },
  type: 'd',
  cluster: 12,
  position: 86,
  version: 0 }
```

The orient side update syntax is

`update Users set first_name = 'John' where last_name = 'Doe'`

the above syntax should trigger the liveQuery callback and it's not unless i downgrade to 2.1.x

**Comment by maggiolo00** [comment]
hi @jterrero 

can you try to add this to the config
`useToken : true`
http://orientdb.com/docs/last/OrientJS-Server.html#using-tokens

It should solve it.

**Comment by jterrero** [comment]
hi maggiolo00, 

That worked perfect. Thank you. 

I must have overlooked at the release notes. I did not find anything when i viewed the changes from 2.1 to 2.2

Thank you, this issue may be closed

**Comment by maggiolo00** [comment]
I've updated  the docs. It will be available in a couple of hours here
http://orientdb.com/docs/last/OrientJS-Query-Live-Query.html

Thanks
