### ISSUE TITLE
Method "executeQuery" from Statement not works.

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#6818]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]
v2.2.11

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Code "ResultSet rs = stmt.executeQuery( query.toString() );" returns ResultSet with data. But the code throws exception and  log message;
WARNING: Error deserializing record to get field-names, send this data for debugging: ABRIeXBvdGhlc2lzOQAAABw3AAAAHTUAAAAlAAIOTlAgIT0gUBQxMjM0NTY3ODkw

Request for executing:
select from Hypothesis WHERE id='1234567890'

## Steps to reproduce the problem
Store entity and try select the entity by JDBC

**Comment by schernolyas** [comment]
query for inserting:
insert into Hypothesis content {"pos":1,"description":"NP != P","id":"1234567890"};

**Comment by robfrank** [comment]
Hi, as you can see in the commit above, I added a specific test to JDBC for INSERT CONTENT:
```
    Statement insert = conn.createStatement();
    insert.execute("INSERT INTO Article CONTENT {'uuid':'1234567',  'title':'title', 'content':'content'} ");

    Statement stmt = conn.createStatement();

    assertThat(stmt.execute("SELECT uuid,date, title, content FROM Article WHERE uuid = 1234567")).isTrue();

    ResultSet rs = stmt.getResultSet();
    assertThat(rs).isNotNull();

    assertThat(rs.getFetchSize()).isEqualTo(1);

    assertThat(rs.getLong("uuid")).isEqualTo(1234567);

```

Are you using OrientDB via JDBC in remote? (A standalone server?) Can you provide some lines of code (a test) that I can try on my side or even a more detailed stack trace if you have one?
THX in advance

**Comment by schernolyas** [comment]
Hi @robfrank !

Yes, You are right! I try to use JDBC in remote with standalone server.

About stack trace .... I see "Error deserializing record to get field-names, send this data for debugging" string in log. Also I get NPE at Java site. I insert entity by query:
insert into Hypothesis content {"pos":1,"description":"NP != P","id":"1234567890"};
I get same error then I execute my query by Native OrientDB API.
I guess that is problem of JSON Parser.

**Comment by robfrank** [comment]
Just for a check, are client and server version aligned? 2.2.11 for each one?

**Comment by schernolyas** [comment]
Yes, of course!

**Comment by schernolyas** [comment]
@robfrank 
it is part of stack trace.
java.lang.NullPointerException
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getFieldNames(ORecordSerializerBinaryV0.java:319)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.getFieldNames(ORecordSerializerBinary.java:112)
        at com.orientechnologies.orient.core.record.impl.ODocument.fieldNames(ODocument.java:737)
        at com.orientechnologies.orient.core.record.impl.ODocument.toMap(ODocument.java:675)
        at org.hibernate.ogm.datastore.orientdb.dialect.impl.OrientDBEntityQueries.findEntity(OrientDBEntityQueries.java:87)

**Comment by schernolyas** [comment]
[org.hibernate.ogm.datastore.orientdb.utils.OrientDbCRUDTest-output.txt](https://github.com/orientechnologies/orientdb/files/533628/org.hibernate.ogm.datastore.orientdb.utils.OrientDbCRUDTest-output.txt)

**Comment by robfrank** [comment]
From the stack trace, hibernate OGM seems to use OrientDB core API, not JDBC, to retrieve the entity:
```
java.lang.NullPointerException
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getFieldNames(ORecordSerializerBinaryV0.java:319)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.getFieldNames(ORecordSerializerBinary.java:112)
	at com.orientechnologies.orient.core.record.impl.ODocument.fieldNames(ODocument.java:737)
	at com.orientechnologies.orient.core.record.impl.ODocument.toMap(ODocument.java:675)
```

 Digging more, I see that you are using **\ogm\hibernate-ogm-core\5.1.0-SNAPSHOT**. IMHO a SNAPSHOT is too dangerous. Maybe a 5.1.0 or 5.2.0 would be better, but I'm not an expert of hibernate OMG and I didn't know ho it works internally

**Comment by schernolyas** [comment]
Yes, You right. But .... 
Can You explain ... what is problem with com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getFieldNames(ORecordSerializerBinaryV0.java:319)?

**Comment by robfrank** [comment]
I'm doing some triage to understand where the problem could be. Can you point me to the source of OGM/OrientDB, thx

**Comment by schernolyas** [comment]
@robfrank  I am not commit the changes.  I can send link to code that works witn in-memory database and old version of OrientDB.
Also, I can say, that new code changes from old only version of OrientDB and mode (was 'memory', new 'remote')
The link to old version is: https://github.com/schernolyas/hibernate-ogm/blob/core_tests3/orientdb/src/main/java/org/hibernate/ogm/datastore/orientdb/dialect/impl/OrientDBEntityQueries.java

**Comment by schernolyas** [comment]
Version of OrientDB was 2.2.3

**Comment by tglman** [comment]
hi all,

This stack trace look very similar to the one on this issue : https://github.com/orientechnologies/orientdb/issues/6800 

I solved it in the last develop few days ago.

**Comment by schernolyas** [comment]
Hi OrientDB team!
When I can get release 2.2.12 ?

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

2.2.12 is available for download

Thanks

Luigi
