### ISSUE TITLE
documentation of substring() is incorrect

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6820]
## OrientDB Version, operating system, or hardware.
all

The documentation about 'substring' in all versions about Methods (http://orientdb.com/docs/master/SQL-Methods.html) is incorrect : 

It now says : 

Returns a substring of the original cutting from 'begin' and getting 'length' characters. 'begin' starts from 0 to string length - 1.

The second parameter of this function, is not the length of the substring to be returned, but the end-position of the original string.

SELECT 'abcdef'.substring(2,2) FROM ...
returns nothing whereas according to the documentation this should be 'cd'

SELECT 'abcdef'.substring(2,3) FROM ...
returns 'c' whereas according to the documentation this should be 'cde'

SELECT 'abcdef'.substring(2,4) FROM ...
returns 'cd' whereas according to the documentation this should be 'cdef'

**Comment by maggiolo00** [comment]
@rdelangh 

yes you are right. The second parameter is the endIndex of the original one.
I will update the docs

Thanks

**Comment by maggiolo00** [comment]
@rdelangh 

i've updated the docs [here](https://github.com/orientechnologies/orientdb-docs/blob/2.2.x/SQL-Methods.md#substring)

It should be online in a couple of hours

Thanks
Enrico
