### ISSUE TITLE
With ALTER CLASS, certain property values are case-sensitive

### ISSUE THREAD

**Issue by SamHard** [orientechnologies/orientdb#6821]
## OrientDB Version, operating system, or hardware.
- v2.2.11

## Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
With the command "ALTER CLASS <ClassName> STRICTMODE <value>", the value (true/false) must lower case.  However most other ALTER CLASS/PROPERTY commands that accept a Boolean are okay with either upper- or lowercase.  STRICTMODE should not be the only property that requires a case-sensitive value.  The documentation shows examples of both upper- and lower-case being used in various places (TRUE/true/FALSE/false).

## Steps to reproduce the problem
Setup:
```
CREATE CLASS Account EXTENDS V;
CREATE PROPERTY Account.Name STRING;
ALTER  PROPERTY Account.Name MANDATORY TRUE;
```
Then, run this:
`ALTER CLASS Account STRICTMODE TRUE;`
You'll get this output:
```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
alter CLASS Account STRICTMODE FALSE
    ^
Encountered " <ALTER> "alter "" at line 1, column 1.
Was expecting one of: ...
```
It turns out that the problem is resolved by changing "TRUE" to "true".

**Comment by luigidellaquila** [comment]
Hi @SamHard 

I just pushed a fix in 2.2.x branch. The fix will be released with 2.2.13

Thanks

Luigi
