### ISSUE TITLE
Graph Editor update problem

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6822]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[11 ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
        DB name="XXX" [ONetworkProtocolHttpDb]
2016-10-17 20:54:33:694 SEVER Internal server error:
com.orientechnologies.orient.server.network.protocol.http.OHttpRequestException: Syntax error: document/<database>/<record-id>[/fetchPlan] [ONetworkProtocolHttpDb]

## Steps to reproduce the problem
Click on a vertex and then click Pensil-symbol and change a property and save.
Click again to see the result. You will see no change in the left panel as you receive the above internal error from the server, and "Error on parsing query Query: undefined-----^ DB name..." as a red error message at the bottom of the Graph Editor screen.

**Comment by maggiolo00** [comment]
@austx 

let me check

**Comment by maggiolo00** [comment]
@austx 
fixed. It will be available in 2.2.13

Thanks
Enrico

**Comment by austx** [comment]
2.2.13-SNAPSHOT   acknowledged.
