### ISSUE TITLE
(big) index rebuild goes dramatically slow

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6824]
## OrientDB Version, operating system, or hardware.
- v2.2.11
## Operating System
- [x] Linux
## Expected behavior and actual behavior

ok, I admit, this is really getting a BIG database : 
- one class "mds_csv_cf14" currently has about 380M records (docs) in it
- the index file "idx_mds_csv_cf14_2.sbt" was about 10GB size, now rebuilding
- this index is defined on 2 properties: "ENV" (string) and "START_DATETIME" (datetime),  NOTUNIQUE

The rebuilding goes terribly slow, in my opinion : 
- started it yesterday 2PM
- now, nearly 22hrs later, it is at 23%
- meanwhile, the database is idle (no connections from client programs, no lookups, no inserts)
- the server host is virtually idle (3-5% busy), 128GB RAM is used for 95GB by kernel cache (which is good), disk I/O goes super (6 striped disks, each absorbing 30MB/sec data, service times are <0.5msec/IO)

Is this progress normal ?

The logs:
...
2016-10-18 11:27:57:133 INFO  {db=cdrarch} --> 23.07% progress, 87,615,147 indexed so far (2,982 items/sec) [OIndexRebuildOutputListener]

**Comment by taburet** [comment]
Unfortunately, tree-based indexes are slow on insertion of large amounts of data, the more data is inserted the more insertion speed drops. If you don't need range queries on that index, you may try to replace it with [hash index](http://orientdb.com/docs/2.2.x/Hash-Index.html) or [autosharding hash index](http://orientdb.com/docs/2.2.x/Auto-Sharding-Index.html), that should improve indexing/query time significantly.

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.

**Comment by rdelangh** [comment]
@laa, @taburet 
I have opted to split our single, massive class which contains data for a full year, into smaller classes that contain data for a week only per class.
The very lengthy index (re-)builds should go much faster consequently.
Will keep an eye on it tough...
