### ISSUE TITLE
backup runs dramatically slow, purely single-threaded

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6827]
## OrientDB Version, operating system, or hardware.
- v2.2.11
## Operating System
- [x] Linux
## Expected behavior and actual behavior

The "bin/backup.sh" script spawns a Java program for the backups, but this latter process runs on a single CPU core only, not by any means making use of a multi-core architecture. As a result, taking backup of a 30 GB database runs for many hours (> 4), the bottleneck is a 100% saturated, single core.

Can this be rewritten to run multi-threaded somehow ?

**Comment by lvca** [comment]
The backup, as opposite to the export, is an I/O bound procedure. The Java application just freeze the database and copy the directory in another place zipped. Have you tried to reduce the compression?

**Comment by rdelangh** [comment]
@lvca 
The script "backup.sh" has no support for any additional parameters that might change compression level. Probably this is a usefull command-line option to be added to the script and its documentation.
Then you should of course also add this support for a different compression level in the Java program launched by "console.sh" ("backup.sh" launches "console.sh"). And I noticed that in the current version, the "libz" library is used to perform the compression, I don't know if in this library there is any support for multithreading, otherwise it is the Java program itself who should attempt to run the backup (or at least its compression) in a multithreaded way.

**Comment by lvca** [comment]
That's a good idea. I've just created this enhancement: https://github.com/orientechnologies/orientdb/issues/6829.

**Comment by laa** [comment]
Close this one as duplication then
