### ISSUE TITLE
orientdb does not support systemd startup notification

### ISSUE THREAD

**Issue by LStuker** [orientechnologies/orientdb#6831]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]
## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behaviors and actual behavior

For systemd orientdb is active when the startup command is executed and not when it is ready for accepting connections. When you run a dependent service which is dependent on orientdb, it is properly that this service fails as orientdb is not yet to accept connections.

If orientdb would support systemd notification, it could notify systemd of the current status.

> systemd-notify may be called by daemon scripts to notify the init system about status changes. It can be used to send arbitrary information, encoded in an environment-block-like list of strings. Most importantly, it can be used for start-up completion notification.

https://www.freedesktop.org/software/systemd/man/systemd-notify.html
https://www.freedesktop.org/software/systemd/man/sd_notify.html
## Steps to reproduce the problem

Use systemd example file of development branch

**Comment by robfrank** [comment]
Orientdb can be started in many different (bash, docker, systemd) ways and it is written in Java. I will explore the way of integrating with systemd more deeply and keep you posted on this issue.

**Comment by LStuker** [comment]
Hi Roberto, thank you very much for your feedback.
My quick research showed that there are some lib for java which implements systemd notification, but my Java knowledge is a bit rusty. For sure the implementation should not impact the portability of oriented.

https://github.com/faljse/SDNotify
https://gist.github.com/hanikesn/568882f96d543758e7b2

**Comment by robfrank** [comment]
Sorry for our delay, we will not implement this feature. Note that we should run on many different OS (linux/win/bsd) with or without systemd. Adding such a dependency and management will increase complexity.
