### ISSUE TITLE
Error parsing query: insert into cluster:my_cluster_name (properties,...) FROM SELECT ...

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6833]
## OrientDB Version, operating system, or hardware.
- v2.2.12-20161019.051435-38

## Operating System
- [x] Linux

## Expected behavior and actual behavior

In console, I try the following query, but get an "Error parsing query:" : 
```
INSERT INTO CLUSTER:cl_cdr_af_20160626_p0 ( @class, PRT_DATE, ...)
FROM SELECT 'cdr_af_20160626', START_DATETIME, ... FROM mds_csv_cf12 WHERE ...
                                          ^
Encountered " "(" "( "" at line 1, column 43
```

The [documentation ](http://orientdb.com/docs/2.2.x/SQL-Insert.html) allows the syntax as above.

-> please advise

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

That docs page is a bit misleading (I think it's not correctly formatted). This syntax is not currently supported: you can do

```
INSERT INTO cluster:A (x, y) values ('a', 'b')
```
or 
```
INSERT INTO cluster:A from (select from ...)
```
but not a mix of the two.

The alternative is to use aliases in the SELECT, eg.

```
INSERT INTO cluster:A from (select 'a' as x, 'b' as y from ...)
```


Thanks

Luigi
