### ISSUE TITLE
unwind does not work on sub-properties

### ISSUE THREAD

**Issue by dominioon** [orientechnologies/orientdb#6835]
## OrientDB Version, operating system, or hardware.
-  [x] v2.2.11

## Operating System
- [X] Linux

## Expected behavior
```
select person.name, person.friends.name as friendName from Foo unwind person.friends

name | friendName
---- | --------
Foo1 | Bar1
Foo1 | Bar2
Foo2 | Bar2
Foo2 | Bar3
```
## Actual behaviour
```
Error parsing query:
select person.name, person.friends.name as friendName from Foo unwind person.friends
                                                                            ^
Encountered " "." ". "" at line 1, column 77.

```

## Steps to reproduce the problem
```
create class Foo
insert into Foo content {"person": {"name":"Foo1", "friends": [{name:"Bar1"},{name:"Bar2"}]}}
insert into Foo content {"person": {"name":"Foo2", "friends": [{name:"Bar2"},{name:"Bar3"}]}}
```

Also tried to use expand(), but the result is completely unexpected (is it another bug?):
```
select person.name, expand(person.friends.name) as friendName from Foo

@version | value
-------- | --------
0        | Bar1
0        | Bar2
0        | Bar2
0        | Bar3
```
As you see, `person.name` is completely missing and alias `friendName` is ignored, too.

**Comment by luigidellaquila** [comment]
Hi @dominioon 

The expand() function cannot be combined with other projections, you should use the UNWIND instead. Could you please try the following statement:

```
select person.name, person.friends.name as friendName from Foo UNWIND friendName
```

Thanks

Luigi

**Comment by dominioon** [comment]
Hi @luigidellaquila,
Yes, that query returns expected value for that particular query, thanks for the hint. But it seems to be illogical that the result property needs to be unwound, not the collection. Imagine the following data model:

```
insert into Foo content {"person": {"name":"Foo1", "friends": [{name:"Bar1","age":1},{name:"Bar2","age":2}]}}
insert into Foo content {"person": {"name":"Foo2", "friends": [{name:"Bar2","age":3},{name:"Bar3","age":4}]}}
```

Which query should I use to get the following result?:
```
name | friendName | friendAge
---- | ---------- | --------
Foo1 | Bar1       | 1
Foo1 | Bar2       | 2
Foo2 | Bar2       | 3
Foo2 | Bar3       | 4
```
The following query will return 8 rows (Cartesian product) instead of 4:
`select person.name, person.friends.name as friendName, person.friends.age as friendAge from Foo UNWIND friendName,friendAge`

**Comment by luigidellaquila** [comment]
hi @dominioon 

You can use the following:

```
SELECT name, friend.name as friendName, friend.age as friendAge  from (
   SELECT person.name as name, person.friends as friend from Foo unwind friend
)
```

I hope it helps

Thanks

Luigi

**Comment by dominioon** [comment]
hi @luigidellaquila, 
yes, it works as expected, thanks! Maybe its wise to add such sub-property example to UNWIND documentation and also point out that it works only with aliases?

**Comment by luigidellaquila** [comment]
Hi @dominioon 

Good point, I'll do it

Thanks

Luigi
