### ISSUE TITLE
Internal server error: java.lang.IllegalArgumentException: Script pool for database  is not configured

### ISSUE THREAD

**Issue by stasbamiza** [orientechnologies/orientdb#6838]
## OrientDB Version, operating system, or hardware.
- 2.2.11
## Operating System
- [ ] Windows
## Expected behavior and actual behavior

Executed without errors
## Steps to reproduce the problem

I create OrientDB function on JavaScript,
`var boxTypeRid = doc.field('@rid');
boxTypeRid = String(boxTypeRid);
var functionName = boxTypeRid.replace(/#/g, '');
functionName = functionName.replace(/:/g, '_');
functionName = 'DashboardBoxTypeFunction_' + functionName;

db.executeCommand('DELETE FROM OFunction WHERE name = "'+ functionName +'"');

code = doc.field('code');

if (code != '') {
  code = code.replace(/'/g, "\'");
  code = code.replace(/"/g, '\"');
  db.executeCommand('CREATE FUNCTION '+ functionName +' "'+ code +'" IDEMPOTENT true LANGUAGE JavaScript');
  db.executeCommand('UPDATE DashboardBoxType SET onAfterUpdate = "'+ functionName +'" WHERE @rid = '+ boxTypeRid);
  print('Update');
}`

Function fully completed and after this I get error in console:
**Internal server error: java.lang.IllegalArgumentException: Script pool for database MyDatabase  is not configured**
For example, If function name is _DeleteMePlese_ and this function exist I get error. If this function are not exsit - function complete successfully without errors.

**Comment by luigidellaquila** [comment]
Hi @stas0 

I think the error message is not reporting the exact problem.
Could you please try to do the following:
- add a `db.commit()` after the `db.executeCommand('DELETE FROM...`
- surround the function body with a try/catch block and see if it's throwing another exception

Thanks

Luigi

**Comment by stas0** [comment]
@luigidellaquila  I add try/cath for delete and commit, in console I see the same error
