### ISSUE TITLE
Studio database name capital letters only

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6840]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ 12] - .rc1[ ] .beta2[ ] .beta1[ ]
## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

In the upper right corner of the Studio screen the database name only shows in CAPITALS. If the database name is, e.g. Base9 it will appear as BASE9. It may lead to confusion.
## Steps to reproduce the problem

Build a database named bASE4 and see how it looks when you get (auto) logged in as admin.

**Comment by austx** [comment]
2.2.13-SNAPSHOT   still not fixed

**Comment by maggiolo00** [comment]
@austx 
the fix wasn't included in snapshot but it's in the 2.2.13 GA

Thanks
