### ISSUE TITLE
Empty string DEFAULT property value is not applied

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#6844]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .8[x] .rc1[ ] .beta2[ ] .beta1[ ]
## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

Expected: using `ALTER PROPERTY` to set the default value of a string field to `''` (empty-string) applies correctly. New vertices of that type have empty-string as a default value on that field.

Actual: the `ALTER PROPERTY` with empty-string has no effect. New vertices of that type do not have a default value on that field, and the field does not exist unless explicitly created.
## Steps to reproduce the problem

```
CREATE CLASS Base
CREATE PROPERTY Base.foo String
ALTER PROPERTY Base.foo DEFAULT ''

CREATE CLASS Bar EXTENDS V, Base
CREATE PROPERTY Bar.name String

CREATE VERTEX Bar SET name='bar'
// returns:
// @rid = #13:0, @version = 1, @class = Bar, name = 'bar', and no value for the property "foo"
```

Running the following query on a database created with 2.1.16 and another database with 2.2.8 hints at what the problem is:

```
select properties['defaultValue'] from (select * from (select expand(classes) from #0:1) unwind properties) where properties['name']='foo'
```

On the database originally created with 2.1.16, but running under 2.2.8, the result is `''` (empty-string), and the entire key-value pair inside `properties` is `"defaultValue":"''"`. On the database created in 2.2.8, the result is `null`, and the key-value pair is `"defaultValue":""`.

**Comment by igasparetto** [comment]
Is this still a valid bug?

**Comment by obi1kenobi** [comment]
Yes, just reproduced it on 2.2.30:
```
select * from (select expand(properties) from (select expand(classes) from #0:1)) where name = 'foo'
```
The above query shows that `defaultValue` is set to null, even though we set it to empty string instead.
