### ISSUE TITLE
Escaped char doesn't work for create edge

### ISSUE THREAD

**Issue by oger-p** [orientechnologies/orientdb#6846]
## OrientDB Version, operating system, or hardware.
- v2.2 SNAPSHOT[x]

## Operating System
- [x] Linux

## Expected behavior and actual behavior

The escaped '\"' works for a normal query but for a create edge query it doesn't work

## Steps to reproduce the problem

The query that works : 
`'SELECT FROM Expression WHERE libelle = "\"Plaine \"\"le Devez\"\"\""' `

The query that doesn't work :
`CREATE EDGE Identifie FROM (SELECT FROM Expression WHERE libelle = "\"Plaine \"\"le Devez\"\"\"") to (SELECT FROM Etab WHERE id = "54886802")`

Thanks in advance

**Comment by luigidellaquila** [comment]
Hi @oger-p 

I just pushed a fix for this in 2.2.x branch. The fix will be released with 2.2.13

Thanks

Luigi
