### ISSUE TITLE
Operator INSTANCEOF doesn't work in MATCH where clause after traverse

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#6850]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .8[x] .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Expected: in MATCH where clauses in the second traversal step and beyond, `A instanceof B` returns true if the class A is an instance of B.

Actual: `A instanceof B` always evaluates to false, even when `A = B` would evaluate to true.

## Steps to reproduce the problem
Setup:
```
CREATE CLASS V1 EXTENDS V
CREATE PROPERTY V1.name String

CREATE CLASS V2 EXTENDS V
CREATE PROPERTY V2.callsign String

CREATE VERTEX V1 SET name = 'foo'
CREATE VERTEX V2 SET callsign = 'bar'

CREATE EDGE E FROM (SELECT FROM V1 WHERE name = 'foo') TO (SELECT FROM V2 WHERE callsign = 'bar')

// the following returns the two added vertices, as expected
MATCH {
    class: V1,
    as: origin
}.out('E') {
    where: (@class = 'V2')
    as: endpoint
} RETURN $matches
```

However, none of the following queries return anything:
```
MATCH {
    class: V1,
    as: origin
}.out('E') {
    where: (@class instanceof 'V2'),
    as: endpoint
} RETURN $matches

MATCH {
    class: V1,
    as: origin
}.out('E') {
    where: (@class instanceof 'V'),
    as: endpoint
} RETURN $matches

MATCH {
    class: V1,
    as: origin
}.out('E') {
    where: ($currentMatch instanceof 'V2'),
    as: endpoint
} RETURN $matches

MATCH {
    class: V1,
    as: origin
}.out('E') {
    where: ($currentMatch instanceof 'V'),
    as: endpoint
} RETURN $matches
```

In the initial step of MATCH, the operator partially works:
```
// this returns the two vertices, as expected
MATCH {
    class: V1,
    where: (@class instanceof 'V'),
    as: origin
}.out('E') {
    as: endpoint
} RETURN $matches

// however, this query still returns no results
MATCH {
    class: V1,
    where: ($currentMatch instanceof 'V'),
    as: origin
}.out('E') {
    as: endpoint
} RETURN $matches

// this query also returns no results
MATCH {
    class: V1,
    where: ($currentMatch.@class instanceof 'V'),
    as: origin
}.out('E') {
    as: endpoint
} RETURN $matches
```

Possibly related to #6830.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I just pushed a fix in 2.2.x. It will be released with 2.2.13

Thanks

Luigi
