### ISSUE TITLE
DROP, SELECT or DESC of a class returns Java error

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6854]
## OrientDB Version, operating system, or hardware.
- v2.2.13-20161027.133116-9
## Operating System
- [x] Linux

Had a class "files_loaded" before, did a rename of it (ALTER CLASS files_loaded name files_loaded1) a few days ago;
meanwhile upgraded ODB to the listed v2.2.13 snapshot release;
now want to cleanup this old class, but get errors:

```
> desc files_loaded1
CLASS 'files_loaded1'
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
Error: java.lang.NullPointerException

> select * from files_loaded1
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select * from files_loaded1
        DB name="cdrarch"
        DB name="cdrarch"
Error: java.lang.NullPointerException

> drop class files_loaded1
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.drop class files_loaded1
        DB name="cdrarch"
        DB name="cdrarch"
Error: java.lang.NullPointerException
```

No errors appear in the logfile.
=> what's going on ? How to get more details about the status of this class ? I can now drop it, but imagine this is about a class that I would still need, then how can this situation be corrected ? There is nothing in the docs about such a situation...

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Can you (privately) share a copy of the db? This kind of errors is always hard to reproduce and the logs don't say much

Thanks

Luigi

**Comment by rdelangh** [comment]
hi Luigi, sorry that will be at least technically impossible: the db is 680 GB size ...

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

are you a Java developer? Any chance for you to launch OrientDB in debug inside Eclipse/IntelliJ and add an exception breakpoint?

It's not too hard:
```
git clone git@github.com:orientechnologies/orientdb.git
git checkout 2.2.x
mvn clean install
```
then import the sources in IntelliJ as a Maven project and create a launcher with the following parameters:

Main class: `com.orientechnologies.orient.server.OServerMain`
VM options: `-server -Xmx2G -Dprofiler.enabled=false -Djava.awt.headless=true -Dcache.level2.enabled=false -Dcache.level1.enabled=false -Dindex.auto.rebuildAfterNotSoftClose=false -Drhino.opt.level=9 -DORIENTDB_HOME=<PathToOrietDB> -Dorientdb.config.file=${ORIENTDB_HOME}/config/orientdb-server-config.xml -Dorientdb.www.path=<PathToOrietDB>/www` (replace `<PathToOrietDB>` with your actual path of course
Working directory: same as `<PathToOrientDB>`

Just launch it in debug and you add an exception breakpoint.

The alternative is for me to guess where it's happening and add a printStackTrace() to make it log the full stack, but it's a bit like gambling...

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
hi Luigi,
sorry but not a Java developer... 
And a second problem is that from these servers, the company firewall policy does not allow direct connectivity to github. Is it possible to download a kind of bundle of files , extract them on our server, and then run what you tell me to do for identifying this issue?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I created a snapshot that should dump that exception (I hope I got the right point to catch it...)

You can download it from here:

https://drive.google.com/a/orientdb.com/file/d/0B46-XQEZNnG3QWdGeHJubTNfNWc/view?usp=sharing

Please, make sure you use it on a backup (at least not on the production DB), as it's a snapshot and did not go through a proper QA process

Thanks

Luigi

**Comment by rdelangh** [comment]
meanwhile, database cannot be opened anymore after running with 2.2.13* snapshots, see #6884

Waiting for that issue to be resolved first ...

**Comment by rdelangh** [comment]
@laa, @lvca , @luigidellaquila 
gentlemen,
can someone please help me out with this ? It seems (cfr #6884) that the files for this class "files_loaded1" got corrupted, so that now the database does not startup any more !
This is seriously getting urgent now ...

In the "databases/cdrarch" directory, I see many files for this class: 
files_loaded1.cpm , files_loaded1_48.cpm , files_loaded1_48.pcl , ... , files_loaded1_94.cpm , files_loaded1_94.pcl

The startup of the database server complains that it is missing a file "files_loaded1.pcl".

-> do I remove all files "files_loaded1*" so that the engine forgets about this class?
-> do I 'touch' a file "files_loaded1.pcl" ?
-> without the server runnable, can I 'fix' somewhere a file which refers to this corrupted class "files_loaded1" ?
??

**Comment by rdelangh** [comment]
From #6884 : 

server startup error messages:
```
...
Error: com.orientechnologies.orient.core.exception.OStorageException: File with name files_loaded1.pcl does not exist in storage cdrarch
        DB name="cdrarch"
```

**Comment by rdelangh** [comment]
this issue has been resolved via the latest build from Andrey (cfr #6884), build nr 2.2.x@ra3e56d7c76285480f40161c9dd2d1ea29473953f; 2016-
11-15 08:47:42+0000

**Comment by lvca** [comment]
Cool, closing it.

**Comment by laa** [comment]
already closed but synchronisation with PrjHub failed
