### ISSUE TITLE
performance question for SQL query

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6855]
## OrientDB Version, operating system, or hardware.
- v2.2.13-20161027.133116-9
## Operating System
- [x] Linux
- I have a class "cdr_af_20161016" with about 70 STRING properties defined, plus a single DATETIME property named "PRT_DATE"; there is almost 21M documents in this class
- a unique index "idx_cdr_af_20161016_0" is defined on [ENV,FILENAME,RECORD_NUMBER,PRT_DATE]
- a LUCENE index "idx_cdr_af_20161016_2" with metadata {"allowLeadingWildcard": true} is defined on [CALLING_NUMBER,CALLED_NUMBER,CONNECTED_NUMBER]

When I run a counting query that only considers ENV and PRT_DATE, is goes very slow, using index "idx_cdr_af_20161016_0" : 

```
SELECT count(*) AS count  FROM cdr_af_20161016 WHERE ENV='prod' AND PRT_DATE BETWEEN '2016-10-20 00:00:00.000' AND '2016-10-21 00:00:00.000'  
```

-> 20941621 records, 1127 secs elapsed !!

Explain plan:

```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 20941621,
            "fullySortedByIndex": false,
            "documentAnalyzedCompatibleClass": 20941621,
            "recordReads": 20941621,
            "fetchingFromTargetElapsed": 1125809,
            "indexIsUsedInOrderBy": false,
            "compositeIndexUsed": 1,
            "current": "#840:3512803",
            "involvedIndexes": [
                "idx_cdr_af_20161016_0"
            ],
            "projectionElapsed": 270,
            "limit": -1,
            "evaluated": 20941621,
            "groupByElapsed": 0,
            "user": "#5:0",
            "elapsed": 1127001.1,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,compositeIndexUsed=l,current=x,involvedIndexes=e,projectionElapsed=l,evaluated=l,groupByElapsed=l,user=x,elapsed=f"
        }
    ],
    "notification": "Query executed in 1127.533 sec. Returned 1 record(s)"
}
```

Another query, targeting to benefit from Lucene index "idx_cdr_af_20161016_2", goes slow as well but less-slow than the previous query:

```
SELECT count(*) AS count  FROM cdr_af_20161016 WHERE (CALLING_NUMBER LUCENE '*123*') AND OUTPUTTYPE = '14'  AND ENV='prod' AND PRT_DATE BETWEEN '2016-10-20 00:00:00.000' AND '2016-10-21 00:00:00.000'  
```

-> 305488  records, 262 secs elapsed !!

The explain plan of this latter query:

```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 305488,
            "fullySortedByIndex": false,
            "documentAnalyzedCompatibleClass": 305488,
            "recordReads": 305488,
            "fetchingFromTargetElapsed": 261022,
            "indexIsUsedInOrderBy": false,
            "score": 0.57735026,
            "current": "#838:3612316",
            "totalHits": 305488,
            "idx_cdr_af_20161016_2_totalHits": 305488,
            "_memoryIndex": "CALLING_NUMBER:\n\t'[33 38 38 39 31 35 33 38 65 65 65 65 65 65 65 65]':1: [(0)]\n\tterms=1, positions=1\ncdr_af_20161016.CALLING_NUMBER:\n\t'[33 38 38 39 31 35 33 38 65 65 65 65 65 65 65 65]':1: [(0)]\n\tterms=1, positions=1\n\nfields=2, terms=2, positions=2",
            "involvedIndexes": [
                "idx_cdr_af_20161016_2"
            ],
            "projectionElapsed": 5,
            "limit": -1,
            "evaluated": 305488,
            "groupByElapsed": 0,
            "user": "#5:0",
            "elapsed": 262209.66,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,score=f,current=x,involvedIndexes=e,projectionElapsed=l,evaluated=l,groupByElapsed=l,user=x,elapsed=f"
        }
    ],
    "notification": "Query executed in 262.711 sec. Returned 1 record(s)"
}
```

=> what am I doing wrong ? These kind of queries run in a traditional, relational database in a few seconds only ...

To stay positive : a query with Lucene index, avoid the leading wildcard, goes fast : 

```
SELECT count(*) AS count  FROM cdr_af_20161016 WHERE (CALLING_NUMBER LUCENE '123*') AND OUTPUTTYPE = '14'  AND ENV='prod' AND PRT_DATE BETWEEN '2016-10-20 00:00:00.000' AND '2016-10-21 00:00:00.000'
```

-> 19843  records found, 3 secs elapsed

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I think your query is using the index only for the first key (`ENV`). The index is returning 20941621 records that are scanned one by one, this is why the query is so slow.

I suggest you to define the index differently, eg.
`[ENV,PRT_DATE,FILENAME,RECORD_NUMBER]`
this way the engine will be able to use it for the complete range query on ENV,PRT_DATE.

As a general rule, partial match is allowed only on tree-based indexes on a prefix of the index key, eg. if you have an index on [A, B, C], you can use it for queries on [A], [A,B], [A,B,C], but not on [A, C].

The second query is faster because in that case the LUCENE index is used, and it returns a bit fewer records

I hope it helps

Thanks

Luigi

**Comment by rdelangh** [comment]
hi @luigidellaquila , 
I recreated that index as you suggested:
```
create index idx_cdr_af_20161016_0 on cdr_af_20161016(ENV,PRT_DATE,FILENAME,RECORD_NUMBER) UNIQUE
```

then re-ran my query:
```
SELECT count(*) AS count  FROM cdr_af_20161016 WHERE ENV='prod' AND PRT_DATE BETWEEN '2016-10-20 00:00:00.000' AND '2016-10-21 00:00:00.000'
```
-> 4502773  records counted, in 137 secs ...

Is this as good as it can be with OrientDB ? Over 2mins to count 4.5M records ...

Explain plan:
```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 4502773,
            "fullySortedByIndex": false,
            "documentAnalyzedCompatibleClass": 4502773,
            "recordReads": 4502773,
            "fetchingFromTargetElapsed": 136415,
            "indexIsUsedInOrderBy": false,
            "compositeIndexUsed": 1,
            "current": "#839:2400099",
            "involvedIndexes": [
                "idx_cdr_af_20161016_0"
            ],
            "projectionElapsed": 239,
            "limit": -1,
            "evaluated": 4502773,
            "groupByElapsed": 0,
            "user": "#5:0",
            "elapsed": 136663.89,
            "resultType": "collection",
            "resultSize": 1,
            "@fieldTypes": "documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,compositeIndexUsed=l,current=x,involvedIndexes=e,projectionElapsed=l,evaluated=l,groupByElapsed=l,user=x,elapsed=f"
        }
    ],
    "notification": "Query executed in 137.232 sec. Returned 1 record(s)"
}
```

**Comment by luigidellaquila** [comment]
well, actually the count should be performed using the index only, not browsing the records.
Maybe there is a bug in the implementation of the BETWEEN operation?

Could you please try the following?

```
SELECT count(*) AS count  FROM cdr_af_20161016 WHERE ENV='prod' AND PRT_DATE >= '2016-10-20 00:00:00.000' AND PRT_DATE < '2016-10-21 00:00:00.000'
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Or it's just a matter of type conversion together with indexes, it's worth trying to use the date() function do to explicit conversions:

http://orientdb.com/docs/2.2.x/SQL-Functions.html#date

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
no change:
```
... WHERE ENV='prod' AND PRT_DATE>='2016-10-20 00:00:00.000' AND PRT_DATE<'2016-10-21 00:00:00.000'
```
returns the correct count after 122 secs (which is bad !)

```
... WHERE ENV='prod' AND PRT_DATE>=DATE('2016-10-20 00:00:00.000') AND PRT_DATE<DATE('2016-10-21 00:00:00.000')
```
returns the correct count after 106secs (which is bad !)

```
... WHERE ENV='prod' AND PRT_DATE BETWEEN DATE('2016-10-20 00:00:00.000') AND DATE('2016-10-21 00:00:00.000')
```
returns the correct count after 117 secs (which is bad !)

**Comment by rdelangh** [comment]
meanwhile, database cannot be opened anymore after running with 2.2.13* snapshots, see #6884

Waiting for that issue to be resolved first ...

**Comment by rdelangh** [comment]
@luigidellaquila 
Database is usable again, issue #6884 is resolved.
-> can you please re-continue your investigations for these performance issues with dates in the WHERE clause?
