### ISSUE TITLE
Requests like "SELECT {items: $allVertices} ..." returns objets with null fields

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#6856]
## OrientDB Version, operating system, or hardware.
v2.2.12, MacOS Sierra

## Expected behavior and actual behavior
Requests involving "maps", such as `SELECT {items: $allVertices} AS items LET $allVertices = (SELECT FROM V)` returns no results.

For example: 
```
> SELECT {'items': $allVertices} AS items LET $allVertices = (SELECT FROM V)
+----+------------+
|#   |items       |
+----+------------+
|0   |{items=null}|
+----+------------+

> SELECT {'ids': $allVertices.@rid, 'outCount': $allVertices.out('E').size()} AS items LET $allVertices = (SELECT FROM V)

+----+-------------------------+
|#   |items                    |
+----+-------------------------+
|0   |{outCount=null, ids=null}|
+----+-------------------------+

1 item(s) found. Query executed in 0.005 sec(s).
```

Of course, I have data in my base, and I can see that $allVertices contains the valid results of the subquery.

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 

That syntax is not supported in v 2.2.
It will be in v 3.0

Thanks

Luigi

**Comment by benjaminbillet** [comment]
@luigidellaquila Hi, tglman suggested this syntax to solve another problem I had (https://github.com/orientechnologies/orientdb/issues/6852), so I assumed that it was supported. Sorry.

**Comment by luigidellaquila** [comment]
Ah, got it :)

It's supported only for the RETURN statement in batch scripts, eg you can do

```
LET $allVertices = (SELECT FROM V);
RETURN {'items': $allVertices}
```

Thanks

Luigi
