### ISSUE TITLE
createDefaultUsers=False breaks creating databases from Studio

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#6857]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .12[x] .rc1[ ] .beta2[ ] .beta1[ ]
## Operating System
- [x] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

`security.json` specifies:

```
"server": {
    "createDefaultUsers": false
}
```

Expected behavior: using Studio to create a new database should succeed and log me into the new database.
Actual behavior: Studio creates the new database, then gets disconnected with an authentication error. Using the developer tools in my browser, I can see that Studio attempted to use `admin/admin` as the credentials to log me into the new database, which failed since `security.json` prohibits default users.

This is the same problem as #6564 except in Studio rather than the console.
## Steps to reproduce the problem

Edit the default `security.json` to set `createDefaultUsers` to `true` and restart the server. Try to create a new database from Studio, and observe it not working as described above.

**Comment by maggiolo00** [comment]
@obi1kenobi 

in case you don't create the default users Studio cannot guess valid credentials. 
Do you suggest to use root credentials?

**Comment by obi1kenobi** [comment]
Yes, of course. Three reasons this makes sense:
- it's currently guessing invalid credentials and hurting the user experience;
- using the provided root credentials is what the OrientDB console does when you create a new database;
- it's consistent with the existing behavior -- the existing behavior was to log the user in as an admin, and the root credentials have admin-level access to the database.

**Comment by maggiolo00** [comment]
@obi1kenobi 

yes the thing is that by logging with root you don't get some feature like graph config saving and other stuff associated with the db user.

**Comment by obi1kenobi** [comment]
While that may be true, it is still infinitely preferable to what I get now -- a series of errors that break the entire web interface until I refresh and manually log in. Try it for yourself and you'll see how annoying it is.

If the user wants graph config saving and the other bells and whistles, they can create a db user and then log in again with that user. In the case where the user explicitly disabled default user creation, there is no way the current behavior is not a bug.

**Comment by obi1kenobi** [comment]
Fantastic, thank you!
