### ISSUE TITLE
Indexing on parent class attribute goes through all parent's records not just child class records

### ISSUE THREAD

**Issue by vlasni** [orientechnologies/orientdb#6858]
## OrientDB Version, operating system, or hardware.
- v2.2.12
## Operating System
- Linux
## Expected behavior and actual behavior

If there is a class hierarchy modeled as vertices such as:
`Customer extends AbstractPojo extends V`
and there is an attribute `AbstractPojo.deleted boolean`
and there is an index on this attribute, when querying `select name from Customer where deleted=false` I would expect that ODB is able to just limit the vertices to those of class `Customer`.
What I am experiencing is that ODB is not limiting records by `Customer` but working on all records from `AbstractPojo`.

There are 37 records for `Customer` and there are 4.5 million records for `AbstractPojo`.
Executing the query below:

```
select @rid as customerId, name, status, statusDate, targetSex, adultsOnly, validationClass, in_manages.outV()[0].name as manager 
from Customer 
where deleted=false 
order by name ASC
```

takes 168.148 seconds. Here is the explain from Studio:

```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 4596038,
            "fullySortedByIndex": false,
            "documentAnalyzedCompatibleClass": 36,
            "recordReads": 4596038,
            "fetchingFromTargetElapsed": 167483,
            "indexIsUsedInOrderBy": false,
            "compositeIndexUsed": 1,
            "current": "#118:1896000",
            "involvedIndexes": [
                "AbstractPOJO.deleted"
            ],
            "limit": -1,
            "orderByElapsed": 0,
            "evaluated": 36,
            "elapsed": 167938.31,
            "resultType": "collection",
            "resultSize": 36,
            "@fieldTypes": "documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,compositeIndexUsed=l,current=x,involvedIndexes=e,orderByElapsed=l,evaluated=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 168.148 sec. Returned 1 record(s)"
}
```

If I change the query to:

```
select @rid as customerId, name, status, statusDate, targetSex, adultsOnly, validationClass, in_manages.outV()[0].name as manager 
from Customer 
order by name ASC
```

(note that the WHERE clause that uses `AbstractPojo.deleted` index was removed)

it takes 0.202 sec:

```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "fullySortedByIndex": false,
            "documentReads": 37,
            "current": "#37:52",
            "documentAnalyzedCompatibleClass": 37,
            "recordReads": 37,
            "fetchingFromTargetElapsed": 3,
            "indexIsUsedInOrderBy": false,
            "orderByElapsed": 1,
            "evaluated": 37,
            "elapsed": 4.165171,
            "resultType": "collection",
            "resultSize": 37,
            "@fieldTypes": "documentReads=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,orderByElapsed=l,evaluated=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 0.202 sec. Returned 1 record(s)"
}
```

Is this a bug or is there something I am missing on how to have an index such as this one?
In our model everything is an `AbstractPojo`. 
Thanks in advance

**Comment by luigidellaquila** [comment]
Hi @vlasni 

the 2.2 query executor does not take into consideration statistics regarding class sizes when choosing the execution plan, it just gives priority to indexes, this is why you are having this performance.

As a work-around, you can rewrite the query as follows

```
select @rid as customerId, name, status, statusDate, targetSex, adultsOnly, validationClass, in_manages.outV()[0].name as manager 
from (select from Customer)
where deleted=false 
order by name ASC
```

or just define another index on Customer.deleted, that should have priority in the execution plan

Thanks

Luigi

**Comment by vlasni** [comment]
Hi @luigidellaquila ,
I went through creating an index on `XXXX.deleted` for every child of `AbstractPojo` and removed the index on `AbstractPojo.deleted`.
It performs as expected now.

Thank ky very much.
Adrian

**Comment by luigidellaquila** [comment]
Great, happy to know it worked fine.

I'm closing this issue

Thanks!

Luigi
