### ISSUE TITLE
OrientDB version not shown anywhere in Studio

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6863]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ 12] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Perhaps consider display version some place in Studio?

**Comment by maggiolo00** [comment]
@austx 

you can find the ODB version in user menu when logged in a database.

There is a drop down menu (top-right corner) and then click about.
