### ISSUE TITLE
Get edges by multiple properties and class.

### ISSUE THREAD

**Issue by Raycoms** [orientechnologies/orientdb#6864]
Retrieving the vertices of a specific class with specific properties works using g.getVertices("MyClass",new String[] {"key1","key2"}, new Object[] {"value1","value2"}); 

but for the edges there isn't a similar method.

**Comment by karolmie1** [comment]
Looks more like stackoverflow question.
As far as I know there is no such native method, you have to create query string manually.

`SELECT EDGE WHERE x=:x, y=:y, x=:z`

And then: 

`graph.command(query).execute<Any>(queryParams)`
