### ISSUE TITLE
Drop database with Lucene index complains

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6865]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[12] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
One would expect database to be dropped with no complaints.

2016-10-31 13:59:33:534 SEVER {db=pAB} Cannot delete storage directory with path /srv/OrientDB2.2.x/pAB because directory is not empty. Files: [/srv/OrientDB2.2.x/pAB/luceneIndexes] [OLocalPaginatedStorage]

## Steps to reproduce the problem
Install Lucene Spatial, wget  http://central.maven.org/maven2/com/orientechnologies...
Add records in class containing property with EMBEDDED OPoint.
Drop database from Studio.

An empty directory is left: /srv/OrientDB2.2.x/pAB/luceneIndexes/

**Comment by maggiolo00** [comment]
@austx 

Fixed it will be available in 2.2.13

Thanks
