### ISSUE TITLE
Cannot download large CSV file via Studio in Chrome

### ISSUE THREAD

**Issue by dominioon** [orientechnologies/orientdb#6868]
## OrientDB Version, operating system, or hardware.
-  [x] v2.2.11
-  [x] v2.2.12

## Operating System
- [X] Linux
- [X] Windows

## Expected behavior and actual behavior
Query result with any size can be downloaded in Chrome.

## Steps to reproduce the problem
Set Content type to CSV under Query configuration in Studio. Run a query returning couple of hundred thousand rows. When the query finishes, Chrome displays 
```
download
Failed - Network error
```

It is possibly the same issue described here: http://stackoverflow.com/questions/19414116/chrome-cannot-export-to-csv-if-there-are-too-many-rows

**Comment by maggiolo00** [comment]
hi @dominioon 

do you get some exception in the Server log?

Thanks

**Comment by dominioon** [comment]
hi @maggiolo00 
No, nothing in the Server logs. Even the green "The command has been executed" message was displayed for a second on the screen.
The issue is purely inside browser.

**Comment by fabriziofortino** [comment]
Hi noticed the same issue on Chrome. Firefox seems to work OK.
