### ISSUE TITLE
request update to concurrentlinkedhashmap 1.4.2

### ISSUE THREAD

**Issue by zerovian** [orientechnologies/orientdb#6869]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[12] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ x] Other, name? 
All (especially solaris(

## Expected behavior and actual behavior

This is a request to update to update to concurrentlinkedhashmap library to 1.4.2.  Currently OrientDB 2.1.12 ships with 1.4.1.  This version has a bug in it that consumes large amounts of memory when high CPU count.

Here is link to bug:
https://github.com/ben-manes/concurrentlinkedhashmap/issues/43

This class is used by OProfilerStub.

Also, please consider completely disabling the profiler and not allocating any objects for it when profiler.enabled is set to false so avoid using any memory allocated by concurrentlinkedhashmap implementation.

**Comment by lvca** [comment]
@taburet  Is this related to our recent tracking of huge memory consumed by using this library? Can we use 1.4.2?

**Comment by taburet** [comment]
@lvca yes, that is exactly the same issue. I will check the possibility of using 1.4.2.

**Comment by zerovian** [comment]
/bump

Any update on this?  I see current 2.2.x is still using the buggy version.

**Comment by luigidellaquila** [comment]
Hi @zerovian 

I'm upgrading it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @zerovian 

I just pushed a fix on 2.2.x, now I'm doing the same for develop (3.0.0)

Thanks

Luigi
