### ISSUE TITLE
ODocument.toMap() not copy all fields

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#6871]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]12

## Operating System
- [ ] Linux
- [ ] MacOSX
- [ x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

```
aa [main] 12:34:51,599 DEBUG org.hibernate.ogm.datastore.orientdb.dialect.impl.ODocumentListTupleIterator: tuple json: {"@type":"d","@rid":"#25:0","@ve
rsion":1,"@class":"Customer","bKey":1,"createdDate":"2016-11-02 00:00:00","blocked":"N","name":"test","status":"VIP","@fieldTypes":"bKey=l,createdDate=
t"}
aa [main] 12:34:51,599 DEBUG org.hibernate.ogm.datastore.orientdb.dialect.impl.ODocumentListTupleIterator: tuple map: {bKey=1, createdDate=Wed Nov 02 0
0:00:00 MSK 2016, @rid=#25:0, @class=Customer, blocked=N, name=test, status=VIP}
```

Method toJSON copy to JSON all fields, but method toMap not copy '@version' field

**Comment by tglman** [comment]
hi @schernolyas,

This is on purpose, the toMap just extract the values of the document, to get the other information you need to use the ODocument api, `doc.getVersion()` ,`doc.getIdentity()` and `doc.getSchemaClass() | doc.getClassName()`, hope this help

Bye

**Comment by schernolyas** [comment]
Hi @tglman !

I think that it is not logical .... But if it is feature ...
