### ISSUE TITLE
Records inserted multiple times under heavy load and IO errors.

### ISSUE THREAD

**Issue by dominioon** [orientechnologies/orientdb#6874]
## OrientDB Version, operating system, or hardware.
-  [x] v2.2.11
-  [x] v2.2.12

## Operating System
- [X] Linux

## Expected behavior
There are exactly 2 million records in the db and the following query will not return any records: `select * from (select name, count(name) as c from LiveTable group by name) where c != 2`. Also Inmemory records count is 2M.
## Actual behavior
Live updaters soon crash on both (sometimes on only one) nodes, `Caught Network I/O errors on 127.0.0.1:2424/testDb, trying an automatic reconnection... (error: Timeout on reading response) [OStorageRemote]`. Usually there are 2,000,002 records in the db when the loop finishes, some tests ended with 2,000,001 records. The above-mentioned select returns data like this:
```
name       | c
---------- | ----
Name_41415 | 3
Name_2734  | 3
```
Also, as the live queries crashed, the inmemory copy has much less than 2M records, eg 35740 on one and 46738 on another node.
## Steps to reproduce the problem
Run the attached program in a 2-node environment (change NODE_1 and NODE_2 placeholders in the hazelcast.xml file first). Both nodes will try to insert 1M records, so there should be 1M different entries, 2 copies of each. But some records are entered 3 times. Seems that one extra from every node where the IO error occurred.

[orient_6874.zip](https://github.com/orientechnologies/orientdb/files/568410/orient_6874.zip)

**Comment by lvca** [comment]
Hi @dominioon, could you please try with the version in 2.2.x branch?

**Comment by dominioon** [comment]
Hi @lvca,
tried, but unfortunately the problem still extist: 2,000,002 records added and both live updaters died, one of them usually having a bit longer stacktrace:
```
Caught Network I/O errors on 127.0.0.1:2424/testDb, trying an automatic reconnection... (error: Timeout on reading response) [OStorageRemote]com.orientechnologies.common.concur.lock.OInterruptedException: Thread interrupted while waiting for request
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:256)
	at com.orientechnologies.orient.client.binary.OAsynchChannelServiceThread.execute(OAsynchChannelServiceThread.java:54)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2173)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:244)
	... 2 more
```
Another error message seen: `Caught Network I/O errors on 127.0.0.1:2424/testDb, trying an automatic reconnection... (error: Timeout on reading response) [OStorageRemote]`

PS, the machines may have a bit different performance. Technically both are Intel® Core™ i5-3570 CPU @ 3.40GHz × 4, but one has Ubuntu 14, another Ubuntu 16, and that last one seem to finish the inserts always before the other one.

**Comment by lvca** [comment]
@luigidellaquila and @tglman any idea about this?
