### ISSUE TITLE
Can' delete record by JavaScript function

### ISSUE THREAD

**Issue by stas0** [orientechnologies/orientdb#6876]
## OrientDB Version, operating system, or hardware.
- 2..1[ ] .0[ ]

## Operating System
- [ 8.1] Windows

Hi.

I test my function where I create fake function and then delete it.
```javascript
try {
	db.executeCommand('CREATE FUNCTION deleteMe "print(\'hello\')" LANGUAGE JavaScript');
  	db.commit();
	db.executeCommand('DELETE FROM OFunction WHERE name = "deleteMe"');
  	db.commit();
} catch(ex) {
	print(ex);
}
```

This function throw error
`Internal server error:
java.lang.IllegalArgumentException: Script pool for database 'myDataBase' is not configured`

It is happend when I create/delete any record

**Comment by tglman** [comment]
I found the reason of this and fixed.

Closing
