### ISSUE TITLE
astar function

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6878]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ 12] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
SELECT astar(#38:2159,#36:185, 'Score') FROM V 
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: No function with name 'astar', available names are : [date,encod...

## Steps to reproduce the problem
SELECT astar(#source,#dest 'xxx') FROM V

**Comment by luigidellaquila** [comment]
Mmm... it's quite strange, I think `astar` function is not properly configured in the function factory.
It should be an easy fix, I'll keep you posted

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @austx 

I just pushed a fix on 2.2.x branch. The fix will be released with 2.2.13

Thanks

Luigi

**Comment by austx** [comment]
2.2.13-SNAPSHOT.

astar() never returns.

**Comment by luigidellaquila** [comment]
It's related to #6911
I'll work on this asap, but my feeling is that it's just a long running execution because of supernodes.
I'll keep you posted

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed in 2.2.14, closing

Thanks

Luigi
