### ISSUE TITLE
traverse in a graph with a restricted cluser throws a security exception rendering traverse unusable

### ISSUE THREAD

**Issue by everycs** [orientechnologies/orientdb#6879]
## OrientDB Version, operating system, or hardware.
- v2.1 SNAPSHOT[ ] - .9[X]
- v2.2 SNAPSHOT[ ] - .12[X]

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
i have a vertex class called "product" - read to everyone
product has a derrived class "product_secret" - read to only administrators

and there is another vertex class "manufacturing". There are links from product to manufacturing.

Note that the edge class is not role restricted.

now if i am a normal user, I cannot do:
- traverse: will always fail with com.orientechnologies.orient.core.exception.OSecurityAccessException: User 'xxx' has no the permission to execute the operation 'Read' against the resource: ResourceGeneric [name=CLUSTER, legacyName=database.cluster].product_secret
-select without a where condition. Note that if i have a where condition, this will return correct record, empty set if i do a where @class='product_secret'.

Just one restricted cluster in the graph makes the whole graph unusable for me.

The expected behavior would be just to just exclude vertices that are restricted and also paths that include restricted vertices

## Steps to reproduce the problem
create class product extends V
create class product_secret extends product
create class manufacturing extends V
create class intermediate extends E
alter class OIdentity superclass V
UPDATE ORole PUT rules = "database.class.product_secret", 0 WHERE name = "reader"
UPDATE ORole PUT rules = "database.cluster.product_secret", 0 WHERE name = "reader"

insert into product set name = 'bananas'
insert into manufacturing set name = 'banana growing'
insert into product_secret set name = 'apples'
insert into manufacturing set name = 'apple growing'
create edge intermediate from (select from product where name = 'bananas') to (select from manufacturing where name = 'banana growing')
create edge intermediate from (select from product where name = 'apples') to (select from manufacturing where name = 'apple growing')

after this, login as reader and do
select from product -->  i would expect bananas
or select expand(in('intermediate')) from manufacturing--> i would expect bananas

**Comment by everycs** [comment]
Gents, any workaround here?

**Comment by luigidellaquila** [comment]
Hi @everycs 

Unfortunately there is no work-around available (apart from disabling security, but I don't think it's an option), but I think I can fix it in next few days

Thanks

Luigi

**Comment by everycs** [comment]
Fantastic. Luigi, is there an advantage of using the resource level security vs the record level security? Because I just tried that and it would work.
