### ISSUE TITLE
How to reset root password

### ISSUE THREAD

**Issue by nayansri** [orientechnologies/orientdb#6881]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I am unable to reset root password.

## Steps to reproduce the problem
I have forgot the root password which I set in the very beginning of setup now I don't know how to reset it.

**Comment by santo-it** [comment]
Hi,

Please could you check if this helps you:
http://orientdb.com/docs/last/Server-Security.html#restoring-the-servers-user-root

Thanks,

**Comment by santo-it** [comment]
Hi @nayansri, just checking if my message was useful. Were you able to reset the root password?

Thanks,

**Comment by nayansri** [comment]
Thanks @santo-it, was disconnected since last few days. It really helped and sorry for creating an issue for such an easy task.

**Comment by santo-it** [comment]
Thanks to you @nayansri - not a problem: we are glad to help

Regards,

**Comment by agborkowski** [comment]
i installed from homebrew oriendb

im removed tag from config file like manual says:
```
 Loading configuration from: /usr/local/opt/orientdb/libexec/config/orientdb-server-config.xml.
```
![screen shot 2018-09-14 at 16 08 56](https://user-images.githubusercontent.com/170557/45555318-c7871c00-b838-11e8-97a8-ceb90760feb3.png)


im restart the server w/o any ask me about new password ?

![screen shot 2018-09-14 at 16 10 20](https://user-images.githubusercontent.com/170557/45555329-cf46c080-b838-11e8-95bc-33d5674cb446.png)

**Comment by luigidellaquila** [comment]
Hi

please try to add the following at the end of the config file

<isAfterFirstTime>false</isAfterFirstTime>

Thanks

Luigi

Il giorno ven 14 set 2018 alle ore 16:11 AgBorkowski <
notifications@github.com> ha scritto:

**Comment by agborkowski** [comment]
its didn't help i removed linie with admin password and server starts ask about new password

**Comment by adubey8** [comment]
> Hi,
> 
> Please could you check if this helps you:
> http://orientdb.com/docs/last/Server-Security.html#restoring-the-servers-user-root
> 
> Thanks,

that link is broken, please update.
