### ISSUE TITLE
Multiple open graph DBs cause conflicts

### ISSUE THREAD

**Issue by nuixkeith** [orientechnologies/orientdb#6882]
## OrientDB Version, operating system, or hardware.
2.2.8 & v2.2.12
## Operating System
- [ x] Windows

## Expected behavior and actual behavior
When opening up two graph databases at the same time I was expecting the state of vertices/edges to remain separate.  I first noticed a problem when trying to migrate a subset of data from one graph DB to another.

## Steps to reproduce the problem

Open either a set of local or in-memory graph databases. In the first graph DB add 2 vertices and an edge between the vertices.  Then in another graph database add a vertex.  Now the state of objects from the first graph will be 'confused'.  If you have vertexA from the first graph and call vertexA.getGraph().getRawGraph() you will get back the second graph.  In some situations calling getProperties can return null, or throw an Exception on method calls that previously worked before touching the other graph database.

I've just copied across my test file, but it hopefully shows the issues 

[TestOrientIssue.zip](https://github.com/orientechnologies/orientdb/files/574535/TestOrientIssue.zip)

**Comment by maggiolo00** [comment]
@nuixkeith 

The implementation of OrientGraph make use of ThreadLocal. That is why instances are "confused"
If you want to use multiple graph instances in one thread you should activate them when needed by using
the API OrientBaseGraph#makeActive

**Comment by lvca** [comment]
In v3.0 (still pre-alpha) we already get rid of Thread Local, so everything is easier.

**Comment by nuixkeith** [comment]
I've been able to put these calls into our wrapper classes and it all seems to be working.  Hopefully we can look at upgrading to V3 some time next year.

Thanks,

Keith
