### ISSUE TITLE
Batch query with return statement does not work with select

### ISSUE THREAD

**Issue by p-sagar** [orientechnologies/orientdb#6883]
## OrientDB Version, operating system, or hardware.
- v2.2.3,  Orientjs node.js driver (v2.2.2)

## Operating System
- [] Windows

## Expected behavior and actual behavior
While trying to execute batch query with select statement embedded in return statement, exception "Cannot find a command executor"  get thrown.
Expected result should be expanded records in result

## Steps to reproduce the problem
1. Try  following batch query with any two records:
begin;
let first = select from #43:22;
let second= select from #110:10;
commit retry 100;
return (SELECT $first as first , $second as second)

2. On execution following error occurs:
{
            "code": 500,
            "reason": 500,
            "content": "com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.(SELECT $first AS first, $second AS second)
        }

**Comment by luigidellaquila** [comment]
Hi @p-sagar 

This is not supported in v 2.2 (it will be in 3.0), but you have two alternatives to achieve the same result:

1. if that is last statement in the script, you can just replace
   ```
   return (SELECT $first as first , $second as second)
   ```
   with
   ```
   SELECT $first as first , $second as second
   ```
   the result will be the same

2. in all the other cases, you can use a LET statement to assign the result to a variable and then return it:

   ```
   LET $a = SELECT $first as first , $second as second;
   RETURN $a
   ```

Thanks

Luigi

**Comment by lvca** [comment]
@luigidellaquila is this already supported in 3.0?

**Comment by luigidellaquila** [comment]
Yes, it is. Closing

Luigi
