### ISSUE TITLE
Auto-Increment field

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6887]
It would be nice supporting the sequence transparently by defining a property as AUTOINCREMENT, like with RDBMS.

Example:

```
ALTER PROPERTY User.id AUTOINCREMENT 1
```

In this case a new sequence `User.id` is created. Every time a new document/vertex/edge is created, the value of `id` will be `sequence.next()`.

**Comment by prakashpandey** [comment]
Is sequence.next() thread safe?

**Comment by lvca** [comment]
Yes.

**Comment by vovagp** [comment]
+1 for AUTOINCREMENT or DEFAULT sequence().next()

**Comment by luigidellaquila** [comment]
Hi all

This is already supported in v 2.2, the syntax is as follows:

```
CREATE SEQUENCE seq type ordered;

CREATE CLASS Foo;
CREATE PROPERTY Foo.id INTEGER;
ALTER PROPERTY Foo.id default "sequence('seq').next()"
```

Thanks

Luigi
