### ISSUE TITLE
Rename(d) Property remains in V

### ISSUE THREAD

**Issue by ghost** [orientechnologies/orientdb#6888]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[12 ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and 
New/renamed property is expected to show immediately under its new name.

##actual behavior
renamed a property of a class XXX extends V from Studio, is not reflected in console.sh until you log off and on again. After rename it still appears under its old name if you select from V.

## Steps to reproduce the problem
Create class with some properties. Then rename one.

**Comment by luigidellaquila** [comment]
Hi @austx 

I think it's due to some schema caching in the console. PUSH messages to clients when schema changes are not available yet, but we are implementing them.

I'm assigning this issue to @tglman as he should be in charge of this

Thanks

Luigi

**Comment by austx** [comment]
![image](https://cloud.githubusercontent.com/assets/19469944/20099142/46654376-a5b7-11e6-88d3-97c3e3cc135f.png)

After restarting server.sh the "old" name(Score) still remains. (new EScore).
