### ISSUE TITLE
NullPointerException on MATCH with no in/out/both() and multiple traversals

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#6890]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .13 SNAPSHOT (2.2.x branch) [x] .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Expected: for unrelated classes `A` and `B`, the following query should return the cross product of elements of each type, `A x B`:

```
MATCH {
    class: A,
    as: obj_a
}, { 
    class: B,
    as: obj_b
} RETURN $matches
```

Actual: the query causes a `NullPointerException` in the server.

## Steps to reproduce the problem

See above query. This works on every schema I've tried, so I doubt the exact schema matters.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I'm checking it 

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I just pushed a fix on 2.2.x, it will be released with 2.2.13.

Thank you very much for reporting, MATCH statement is a new addition and this kind of reports are crucial to make it more stable every day

Thanks

Luigi

**Comment by smolinari** [comment]
Agreed. It is nice to see someone digging in and not throwing in the towel at the first sign of problems.

Scott

**Comment by obi1kenobi** [comment]
Thanks for looking into it! I'm glad it was a relatively straightforward fix.

I definitely can't throw in the towel now -- I built most of a GraphQL-based querying system on top of OrientDB, as I mentioned in #6788, and that's how I keep uncovering the bugs in MATCH I've been reporting :) I'm looking forward to having the last few bugs ironed out (the traversals from an optional location in #6788 is the big one right now) before I can work to open-source my GraphQL system.
