### ISSUE TITLE
why unique index of vertex does not take effect?

### ISSUE THREAD

**Issue by youzp** [orientechnologies/orientdb#6891]
## OrientDB Version, operating system, or hardware.
version: 2.2.12

## Operating System
- [*] Linux--CentOS 7

## Expected behavior and actual behavior
The vertex with unique index field "name" should not be created duplicate, howerver, two identical vertices appear,
why?

## Steps to reproduce the problem
OrientGraphFactory factory = new OrientGraphFactory(uri).setupPool(1,10);
OrientGraphNoTx graph = factory.getNoTx();
OrientVertexType vertex = graph.createVertexType("testVertex");
vertex.createProperty("name", OType.STRING)
                        .setMandatory(true)  
                        .setNotNull(true);
vertex.createIndex("nameIdx",OClass.INDEX_TYPE.UNIQUE,"name");

Vertex test1= graph.addVertex("class:testVertex", "name", "test");
Vertex test2= graph.addVertex("class:testVertex", "name", "test");

**Comment by taburet** [comment]
Hi! Tried the provided test case on plocal and remote storages, the test fails with ORecordDuplicatedException, as expected. Please provide more information on the issue.

**Comment by youzp** [comment]
@taburet   so sorry, mistakes in my code, now things are quite normal.

**Comment by taburet** [comment]
@youzp not a problem, we all make mistakes ;)
