### ISSUE TITLE
How to create an undirected edge and how to avoid creating a duplicate directed edges?

### ISSUE THREAD

**Issue by youzp** [orientechnologies/orientdb#6892]
## OrientDB Version, operating system, or hardware.
- v2.2.12 SNAPSHOT

## Operating System
- [*] Linux---CentOS 7 

## Expected behavior and actual behavior
1. Much discussion about the problems of undirected edges, but cannot find any effective example, anyone can provide one example?
2.how to avoid creating a duplicate directed edges with the same edge property?

**Comment by luigidellaquila** [comment]
Hi @youzp 

The Property Graph db model does not provide undirected edges support. Even TinkerPop standard requires edges to have a direction.
Anyway, it's not a big problem in general, as you can traverse edges in both directions and just ignore the edge direction, using the `both()` operator

Thanks

Luigi
