### ISSUE TITLE
Update vertices and edge using orientDB studio

### ISSUE THREAD

**Issue by botekchristophe** [orientechnologies/orientdb#6894]
## OrientDB Version, operating system, or hardware.
- v2.1.23

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

I expect the command done on OrientDB UI to be propagated to the same cache as command performed by Java API. But instead sometimes, the data between what we see using Java API and and OrientDB studio are not consistent with each other.

## Steps to reproduce the problem

I removed an edge between two vertices using OrientDB studio:

- Go to Browse page
- Fetch one of my two vertices using SQL request
- Click on its rid
- On the right hand side of the page, remove its edge. ( rid of this edge was #26:42)
- Then I created an edge (using the graph page) of the same type between this vertex and an other vertex. At the begining I had V1 -edge1-> V2 and at the end  V1 -edge2 -> V3.

I also have a scala/java app that connect to this database which also work on these vertex. What I expected was to find V3 linked to V1 with edge2 but instead I had my application trying to Fetch edge1 which doesnt exist anymore.

Error thrown by my app :

com.orientechnologies.common.log.OLogManager log
WARNING: Record (#26:42) is null

I encountered this by simply trying to Fetch V1 (this worked) and then by trying to find vertices connected to V1 using edge with Direction.OUT and with label "belongsTo" which was the type of my edges 1 and 2.

scala code : 

`val vertices = orientGraph.getVertices(MyClass.index, value)`
 `val vertex: ScalaVertex = vertices.headOption.getOrElse {`
      `throw VertexNotFoundException(MyClass.index, value)`
` }`
 `vertex.getVertices(Direction.OUT, "belongsTo")`

the last line is failing with the error seen above.

Apparently, a quick work around was to restart orientDB. Not really good for production...

**Comment by maggiolo00** [comment]
@botekchristophe 

are you in remote or plocal connection?

**Comment by lvca** [comment]
No answer, closing it.
