### ISSUE TITLE
"select from ?" no longer works with OSQLAsynchQuery when upgrading to 2.2.12

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#6896]
## OrientDB Version, operating system, or hardware.
- v2.2.12

## Operating System
- [x] Linux

## Expected behavior and actual behavior
After upgrading to 2.2.12 from 2.1.17 Async query with positional parameter using java api does not work with a query like: 

String query = "select @rid,* from ?";

## Steps to reproduce the problem

String query = "select @rid,* from ?";
graph.command(new OSQLAsynchQuery<Vertex>(query,
				new OCommandResultListener() {
                                      @Override
					public boolean result(Object iRecord) {
                                        }
	
					@Override
					public void end() {

					}

					@Override
					public Object getResult() {
						// TODO Auto-generated method stub
						return null;
					}
The new method Object getResult() in the interface OCommandResultListener breaks the existing code. I am not sure what it should be used for?

After fixing the interface most of my queries work but "select from ?" doesn't work. Is it no longer allowed to do this kind of query or is it a regression bug?
here is the stack trace:

com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: sql.select @rid,* from ?
	DB name="mxi2"
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:271)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:193)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:204)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1136)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:49)

**Comment by maggiolo00** [comment]
hi @temilmg 

do you see some exception on OrientDB logs?

**Comment by temilmg** [comment]
No, all I get is the above stack-trace when running my code

**Comment by temilmg** [comment]
Upgrading from 2.1.17 to 2.2.13 is still giving me problems, its turning out to be not that straight forward.
In my java code im using something like the following
select from out('userrole').@rid, out('userrole').name, name, email from muser
out('userrole').@rid used to return an array of rids now i just get an array with null! 
It works fine in studio, just not when using the java api!
Has something fundamentally changed with respect to using rids? Are we advised not to use rids as keys and generate our own?
This is only a problem when using OSQLAsynchQuery and OSQLNonblockingQuery queries.
It works fine when using the following type of query: database.command(new OCommandSQL(query)).execute()

**Comment by luigidellaquila** [comment]
Hi @temilmg 

what are you passing to the query as a parameter? a RID, an OClass or a String?

Thanks

Luigi

**Comment by temilmg** [comment]
Hi, I am passing in a String
Thanks for looking into this

**Comment by luigidellaquila** [comment]
Ok, this explains everything. A string is not a valid target, eg. if you do the following:

```
db.query(new OSQLSynchQuery("select @rid,* from ?"), "Foo");
```
you will obtain the following
```
SELECT FROM "Foo"
```
that is not a valid statement of course (or at least it's not what you need).

I think the best thing to do here is support the following:

```
OClass clazz = db.getMetadata().getSchema().getClass("Foo");
db.query(new OSQLSynchQuery("select @rid,* from ?"), clazz);
```

Please let me know your thoughts, it's not hard to implement 

Thanks

Luigi

**Comment by temilmg** [comment]
No, maybe I didn't explain it correctly my parameter is a string e.g.  "#14:0"
and it used to work in 2.1.17
Somewhere i read that I would get the best performance if i did queries like: select from #14:0
So I have used code like: select from ? and then provided rids in the form of strings as parameters
Also I am not using OSQLSynchQuery but OSQLASynchQuery (with the fix of #6267 and hopefully #6946 im trying to move to non blocking queries, but its the same problem)

As for my comment a day ago about "out('userrole').@rid used to return an array of rids but now returns an array with null " should I create a separate issue?

**Comment by luigidellaquila** [comment]
Ah, ok got it, you have to pass it as a RID, eg.

```
db.query(new OSQLSynchQuery("select @rid,* from ?"), new ORecordId("#12:0"));
```

It worked in previous versions, but it's not a correct behavior, because a string is not a RID...

Thanks

Luigi

**Comment by temilmg** [comment]
Ok, fair enough! 
Thanks

**Comment by luigidellaquila** [comment]
Closing then ;-)

Thanks!

Luigi
