### ISSUE TITLE
Embedded attribute's numbers reset to 0, while storing record through binary protocol

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#6898]
### Linux

---

Hi guys,

There's been a strange issue, while using **binary protocol** through PhpOrient library (see link below). Basically, after record's been saved it's embedded attribute's internal numeric values (in my case `double`) are reset to 0. @Ostico, the owner of the PhpOrient, is saying that issue happens to him from both the library and console/Studio (he was using OrientDB v2.2.5), while to me it happens only through the library. 

This issue on PhpOrient describes the problem in full: https://github.com/Ostico/PhpOrient/issues/84

Could you please help resolve this? The problem does not allow us to move on from 2.1 to 2.2

**Comment by tglman** [comment]
hi @andreyvk,

It Look like an issue we fixed recently in the query engine, i'm going to check this.

this may explain the fact that with the console in 2.2.5 fail and in 2.2.12 doesn't.

Bye

**Comment by tglman** [comment]
Hi @andreyvk,

As i said in the other issue this is just fixed in our side and will be released in 2.2.13, closing.

Bye
