### ISSUE TITLE
Bug in Graph visualization

### ISSUE THREAD

**Issue by Bonizzi** [orientechnologies/orientdb#6900]
## OrientDB Version, operating system, or hardware.
- v.2.2.12 

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
If I create a two edge and both have the same source vertex and the same destionation vertex, I expect to see in the Graph editor two edge instead of one.

![image](https://cloud.githubusercontent.com/assets/13778147/20175532/87289b96-a743-11e6-9bf3-8d703c004d1e.png)

![image](https://cloud.githubusercontent.com/assets/13778147/20175563/b7761b34-a743-11e6-8f54-9089373ea1bb.png)

## Steps to reproduce the problem
Create two edges between two vertexes, both edges must have the same source vertex and the same destination vertex.

Thx

**Comment by maggiolo00** [comment]
Thanks @Bonizzi 

let me check
