### ISSUE TITLE
How to insert vertex and edges in different processes?

### ISSUE THREAD

**Issue by youzp** [orientechnologies/orientdb#6902]
## OrientDB Version, operating system, or hardware.
- v2.2.12
## Operating System
- Linux
## Expected behavior and actual behavior
My work scenario, the vertex in an HDFS file and the edges in other HDFS files.
I write the vertex file with a process and write the edge file with other process,
how to insert the edges in code under this circumstances.

## Steps to reproduce the problem
// How to connect two vertex in other process?
orientGraph.addVertex("class:VertexTest", "id", 100, "name", "test_1")
orientGraph.addVertex("class:VertexTest", "id", 101, "name", "test_2")
orientGraph.addVertex("class:VertexTest", "id", 102, "name", "test_3")
// Edges
The edge file content is "id_src, id_dst, edge_property"

**Comment by youzp** [comment]
The edge file content is "id_src, id_dst, edge_property"

**Comment by msjbear** [comment]
I get stucked on the same problem. I have a vertex file and edges file separately, but I do not know how to import the edges link to the corresponding vertex
the vertex file format is (id,name,job)
samples:
3L, rxin, student
7L, jgonzal, postdoc
5L, franklin, prof
2L, istoica, prof

the edge file format is (src_id,dst_id,relation)
samples:
3L, 7L, collab
5L, 3L, advisor
2L, 5L, colleague
5L, 7L, pi

**Comment by luigidellaquila** [comment]
Hi guys, 

You have to load the two vertices based on the key and then create the edge, eg.

```
Vertex v1 = graph.getVertexByKey("YourVertexClass.vertexIdProperty", value1);
Vertex v2 = graph.getVertexByKey("YourVertexClass.vertexIdProperty", value2);
v1.addEdge("YourEdgeClass", v2);
```

I hope it helps

Thanks

Luigi

**Comment by youzp** [comment]
@luigidellaquila 
hi, the function getVertexByKey has been deprecated in version 2.2.12, and the Vertex v1/v2 symbol cannot be resolved.Are there any other alternatives that could be used?

**Comment by youzp** [comment]
@luigidellaquila 
hi, Luigi
I found the function getVertexByKey was deprecated before version 2.2.12, and now i was worried about his performance, is there any other way to improve the performance of insertion?
<pre><code>
graph.declareIntent(new OIntentMassiveInsert)
graph.getRawGraph.set(ODatabase.ATTRIBUTES.MINIMUMCLUSTERS, 10)
graph.getRawGraph.getLocalCache.setEnable(false)
graph.getRawGraph.setValidationEnabled(false)
Vertex v1 = graph.getVertexByKey("YourVertexClass.vertexIdProperty", value1);
Vertex v2 = graph.getVertexByKey("YourVertexClass.vertexIdProperty", value2);
v1.addEdge("YourEdgeClass", v2);
graph.declareIntent(null)
</pre></code>

**Comment by luigidellaquila** [comment]
Hi @youzp 

sorry, my bad,  `getVertexByKey()` was replaced by  `graph.getVertices(string, obj)`.

How big is your graph? If it's not enormous you can use the batch import (http://orientdb.com/docs/2.2/Graph-Batch-Insert.html). It's very very efficient but it has some limitations

Thanks

Luigi
