### ISSUE TITLE
Improve example database GratefulDeadConcerts or create new DemoDB

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#6905]
## OrientDB Version, operating system, or hardware.
- v2.2.12

## Operating System

- any

--

Hi,

Please let's invest some time to improve the included example database GratefulDeadConcerts or consider to add another one

In particular, in GratefulDeadConcerts there are no Vertex classes defined: it is important that we have defined vertex classes so that new users can get familiarity with this concept

Let's then make sure we well document some queries on the example database on the documentation - which we should always use and refer to, when explaining new things (including inheritance and other concepts)

The example database should allow new users to test our many features in an easy and intuitive way

If the example database is loaded via graphML, and this creates issues with the classes, we can consider loading it via a json file or find another method

Thanks,

---

- [x] Generate Data Model
- [x] Integrate into 3.0 build
- [x] Update Documentation
- [x] Post build QA / Integration tests
- [ ] Include saved queries into the DB (bookmarks)

**Comment by lvca** [comment]
We already provide a better default database in 3.0 ;-)

**Comment by santo-it** [comment]
Open Tasks:
 
- [ ] Complete Doc
- [ ] Integration Tests

**Comment by santo-it** [comment]
Documentation and integration tests: done. Integration tests can be improved in the future with more asserts.

Closing!
