### ISSUE TITLE
Commit automatically open transaction when changing AutoStartTx mode in TransactionalGraph

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#6906]
## OrientDB Version, operating system, or hardware.
- v2.2.12

## Expected behavior and actual behavior

In `com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.setAutoStartTx(boolean)`, when invoked passing false as parameter (that is disabling AutoStart), this warning is printed if a transaction is already open.

> "Auto transaction starting is turned off for the graph, but already started transaction is left open. Commit it manually or consider disabling auto transactions while creating the graph or its factory."

I would expect the open transaction to be committed automatically, exactly the same as the java standard [jdbc connection](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setAutoCommit(boolean)) does:

> NOTE: If this method is called during a transaction and the auto-commit mode is changed, the transaction is committed.

Furthermore, the mentioned warning is impossible to be avoided. When AutoStart is enabled, a manual commit is always followed by opening implicitly a new transaction.

`com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.ensureTransaction()`

**Comment by tglman** [comment]
hi @diegomtassis,

I made a fix to invalidate transaction in case of no changes were done, and not display the warning, this should solve the problem.

It will be released in 2.2.13

Regards

**Comment by diegomtassis** [comment]
Please look at my comments in the new code.

**Comment by tglman** [comment]
hi @diegomtassis 

Thanks for the review, i fixed the condition, it's been released already in 2.2.13, i'm closing this.

Bye
