### ISSUE TITLE
Match limit apparently not working.  Match() exceeding depth 2 never returns? 

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6907]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ 12] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

16GB RAM, Intel i7, Kubuntu 14.04.
server.sh: 
 OrientDB auto-config DISKCACHE=8,315MB (heap=5,461MB direct=524,288MB os=15,824MB) [orientechnologies]

## Expected behavior
match {as:P, class:HumanProtein} -InteractWith- {as:I, while:($depth<2)} return $elements limit 50
returns 50 elements.

##Actual behavior
match {as:P, class:HumanProtein} -InteractWith- {as:I, while:($depth<=2)} return $elements limit 50
This match (<=2) runs forever. 
Studio/console.sh resulting log-message: _(and limit of 50 seems to have been forgotten!)_

2016-11-12 14:48:12:662 INFO  {db=HumanPPI2} [TIP] Query 'SELECT FROM HumanProtein' returned a result set with more than 10000 records. Check if you really need all these records, or reduce the resultset by using a LIMIT to improve both performance and used RAM [OProfilerStub]

SELECT/TRAVERSE makes sense, but MATCH behaves strange. See below.

## Steps to reproduce the problem
The export database in question is available for download. 18000+ human proteins and 7.805 million edges with property. Data are very real indeed. Will share export file(approx 329M) if requested.

Also try with varying parameters:
match {as:P, class:HumanProtein} -InteractWith- {as:I, while:($depth<2)} return P,I,P.ProteinName as ProteinName,I.ProteinName as InteractingWith,I.GOtermName as GOtermName limit 50

SELECT @rid,$depth,ProteinName,GOtermName FROM (TRAVERSE out("InteractWith") FROM #37:307 WHILE $depth <= 4) limit 50
returns nice sensible data. 
Running MATCH while $depth exceeding 2 seems to get stuck.

**Comment by luigidellaquila** [comment]
Hi @austx 

Thank you for reporting, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @austx 

I just pushed a fix for this on branch 2.2.x. The fix will be released in v 2.2.13

Thanks

Luigi
