### ISSUE TITLE
Replica holds clusters owners ?

### ISSUE THREAD

**Issue by wq1101** [orientechnologies/orientdb#6908]
## OrientDB Version, operating system, or hardware.
- OrientDB console v.2.2.12-SNAPSHOT (build 2.2.x@r2a76ee1efc4487d9dc5f43e1ddc2fba1c5a0167c; 2016-10-20 13:55:08+0000)

## Operating System
- Oracle Linux 6.5

## Expected behavior and actual behavior
# ** 3 nodes with "config/default-distributed-db-config.json" as below:**
{
  "autoDeploy": true,
  "hotAlignment": false,
  "readQuorum": 1,
  "writeQuorum": 1,
  "executionMode": "asynchronous",
  "readYourWrites": false,
  "servers" : {
    "govnet01": "master",
    "govnet02": "master",
    "*"       : "replica"
  },
  "clusters": {
    "internal": {   },
    "index"   : {   },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}

# ** Expected that govnet01 & govnet02 hold clusters owners, and govnet03 holds clusters copies.  Connecting OrientDB, find 3 nodes : govnet01 holds copies, govnet02 & govnet03 hold owners.**
orientdb> connect remote:t1s1/test_g3 root password

Connecting to database [remote:t1s1/test_g3] with user 'root'...OK

CONFIGURED SERVERS
+----+--------+------+-----------+-------------------+------------------+------------------+-----------------+-----------------+---------+
|#   |Name    |Status|Connections|StartedOn          |Binary            |HTTP              |UsedMemory       |FreeMemory       |MaxMemory|
+----+--------+------+-----------+-------------------+------------------+------------------+-----------------+-----------------+---------+
|0   |govnet03|ONLINE|6          |2016-11-14 13:56:51|192.168.3.203:2424|192.168.3.203:2480|369.28MB (36.54%)|641.22MB (63.46%)|1010.50MB|
|1   |govnet01|ONLINE|17         |2016-11-14 14:23:00|192.168.3.201:2424|192.168.3.201:2480|847.29MB (84.64%)|153.71MB (15.36%)|1001.00MB|
|2   |govnet02|ONLINE|11         |2016-11-14 13:56:54|192.168.3.202:2424|192.168.3.202:2480|576.88MB (56.92%)|436.62MB (43.08%)|1013.50MB|
+----+--------+------+-----------+-------------------+------------------+------------------+-----------------+-----------------+---------+

orientdb {db=test_g3}> ha status -db -output=text

Executed '

CLUSTER CONFIGURATION (LEGEND: X = Owner, o = Copy)
+--------------------+----+-----------+----------+--------+--------+--------+
|                    |    |           |          | MASTER | MASTER |REPLICA |
|                    |    |           |          | ONLINE | ONLINE | ONLINE |
+--------------------+----+-----------+----------+--------+--------+--------+
|CLUSTER             |  id|writeQuorum|readQuorum|govnet01|govnet02|govnet03|
+--------------------+----+-----------+----------+--------+--------+--------+
|*                   |    |     1     |    1     |   X    |   o    |   o    |
|_studio             |  58|     1     |    1     |   o    |   X    |   o    |
|_studio_10          |  68|     1     |    1     |   o    |   o    |   X    |
|_studio_11          |  69|     1     |    1     |   o    |   o    |   X    |
|_studio_12          |  70|     1     |    1     |   o    |   o    |   X    |
|_studio_13          |  71|     1     |    1     |   o    |   o    |   X    |
|_studio_17          |  75|     1     |    1     |   o    |   X    |   o    |
|_studio_18          |  76|     1     |    1     |   o    |   X    |   o    |
|_studio_19          |  77|     1     |    1     |   o    |   X    |   o    |
|_studio_20          |  78|     1     |    1     |   o    |   o    |   X    |
|_studio_21          |  79|     1     |    1     |   o    |   o    |   X    |
|_studio_22          |  80|     1     |    1     |   o    |   o    |   X    |
|_studio_23          |  81|     1     |    1     |   o    |   o    |   X    |
|_studio_3           |  61|     1     |    1     |   o    |   X    |   o    |
|_studio_4           |  62|     1     |    1     |   o    |   X    |   o    |
|_studio_5           |  63|     1     |    1     |   o    |   X    |   o    |
|_studio_6           |  64|     1     |    1     |   o    |   X    |   o    |
|e                   |  33|     1     |    1     |   o    |   o    |   X    |
|e_0                 |  57|     1     |    1     |   o    |   X    |   o    |
|e_1                 |  34|     1     |    1     |   o    |   X    |   o    |
|e_10                |  43|     1     |    1     |   o    |   X    |   o    |
|e_11                |  44|     1     |    1     |   o    |   X    |   o    |
|e_12                |  45|     1     |    1     |   o    |   X    |   o    |
|e_17                |  50|     1     |    1     |   o    |   o    |   X    |
|e_18                |  51|     1     |    1     |   o    |   o    |   X    |
|e_19                |  52|     1     |    1     |   o    |   o    |   X    |
|e_20                |  53|     1     |    1     |   o    |   X    |   o    |
|e_21                |  54|     1     |    1     |   o    |   X    |   o    |
|e_22                |  55|     1     |    1     |   o    |   X    |   o    |
|e_23                |  56|     1     |    1     |   o    |   X    |   o    |
|e_24                | 316|     1     |    1     |   o    |   o    |   X    |
|e_6                 |  39|     1     |    1     |   o    |   o    |   X    |
|e_8                 |  41|     1     |    1     |   o    |   o    |   X    |
|e_9                 |  42|     1     |    1     |   o    |   o    |   X    |
|index               |   1|     1     |    1     |        |        |        |
|internal            |   0|     1     |    1     |        |        |        |
|ofunction_0         | 310|     1     |    1     |   o    |   o    |   X    |
|ofunction_1         | 311|     1     |    1     |   o    |   X    |   o    |
|orole_0             | 302|     1     |    1     |   o    |   o    |   X    |
|orole_1             | 303|     1     |    1     |   o    |   X    |   o    |
|oschedule_0         | 319|     1     |    1     |   o    |   o    |   X    |
|oschedule_1         | 320|     1     |    1     |   o    |   X    |   o    |
|osequence_0         | 317|     1     |    1     |   o    |   o    |   X    |
|osequence_1         | 318|     1     |    1     |   o    |   X    |   o    |
|ouser_0             | 325|     1     |    1     |   o    |   o    |   X    |
|ouser_1             | 326|     1     |    1     |   o    |   X    |   o    |
|tb_object1_0        | 304|     1     |    1     |   o    |   o    |   X    |
|tb_object1_1        | 155|     1     |    1     |   o    |   o    |   X    |
|tb_object1_15       | 169|     1     |    1     |   o    |   o    |   X    |
|tb_object1_16       | 170|     1     |    1     |   o    |   o    |   X    |
|tb_object1_2        | 156|     1     |    1     |   o    |   o    |   X    |
|tb_object1_20       | 174|     1     |    1     |   o    |   X    |   o    |
|tb_object1_21       | 175|     1     |    1     |   o    |   o    |   X    |
|tb_object1_22       | 176|     1     |    1     |   o    |   X    |   o    |
|tb_object1_23       | 177|     1     |    1     |   o    |   X    |   o    |
|tb_object1_24       | 305|     1     |    1     |   o    |   X    |   o    |
|tb_object1_3        | 157|     1     |    1     |   o    |   o    |   X    |
|tb_object1_4        | 158|     1     |    1     |   o    |   o    |   X    |
|tb_object1_5        | 159|     1     |    1     |   o    |   o    |   X    |
|tb_object1_6        | 160|     1     |    1     |   o    |   X    |   o    |
|tb_object1_7        | 161|     1     |    1     |   o    |   X    |   o    |
|tb_object1_8        | 162|     1     |    1     |   o    |   X    |   o    |
|tb_object1_9        | 163|     1     |    1     |   o    |   X    |   o    |
|tb_object2          | 226|     1     |    1     |   o    |   X    |   o    |
|tb_object2_0        | 323|     1     |    1     |   o    |   o    |   X    |
|tb_object2_1        | 227|     1     |    1     |   o    |   o    |   X    |
|tb_object2_10       | 236|     1     |    1     |   o    |   o    |   X    |
|tb_object2_11       | 237|     1     |    1     |   o    |   o    |   X    |
|tb_object2_12       | 238|     1     |    1     |   o    |   X    |   o    |
|tb_object2_13       | 239|     1     |    1     |   o    |   X    |   o    |
|tb_object2_2        | 228|     1     |    1     |   o    |   o    |   X    |
|tb_object2_20       | 246|     1     |    1     |   o    |   X    |   o    |
|tb_object2_24       | 324|     1     |    1     |   o    |   X    |   o    |
|tb_object2_3        | 229|     1     |    1     |   o    |   o    |   X    |
|tb_object2_4        | 230|     1     |    1     |   o    |   o    |   X    |
|tb_object2_5        | 231|     1     |    1     |   o    |   X    |   o    |
|tb_object2_6        | 232|     1     |    1     |   o    |   X    |   o    |
|tb_object2_7        | 233|     1     |    1     |   o    |   o    |   X    |
|tb_object2_8        | 234|     1     |    1     |   o    |   o    |   X    |
|tb_object2_9        | 235|     1     |    1     |   o    |   X    |   o    |
|tb_object_0         | 308|     1     |    1     |   o    |   o    |   X    |
|tb_object_1         | 275|     1     |    1     |   o    |   o    |   X    |
|tb_object_16        | 290|     1     |    1     |   o    |   X    |   o    |
|tb_object_17        | 291|     1     |    1     |   o    |   X    |   o    |
|tb_object_2         | 276|     1     |    1     |   o    |   o    |   X    |
|tb_object_20        | 294|     1     |    1     |   o    |   X    |   o    |
|tb_object_21        | 295|     1     |    1     |   o    |   o    |   X    |
|tb_object_22        | 296|     1     |    1     |   o    |   o    |   X    |
|tb_object_23        | 297|     1     |    1     |   o    |   X    |   o    |
|tb_object_24        | 309|     1     |    1     |   o    |   X    |   o    |
|tb_object_3         | 277|     1     |    1     |   o    |   o    |   X    |
|tb_object_4         | 278|     1     |    1     |   o    |   X    |   o    |
|tb_object_5         | 279|     1     |    1     |   o    |   X    |   o    |
|tb_object_6         | 280|     1     |    1     |   o    |   X    |   o    |
|tb_object_7         | 281|     1     |    1     |   o    |   o    |   X    |
|tb_object_8         | 282|     1     |    1     |   o    |   o    |   X    |
|tb_object_9         | 283|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity    |  82|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity2_0 | 312|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity2_12| 262|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity2_13| 263|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity2_14| 264|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity2_15| 265|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity2_16| 266|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity2_17| 267|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity2_18| 268|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity2_19| 269|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity2_20| 270|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity2_21| 271|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity2_22| 272|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity2_23| 273|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity2_24| 313|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity2_3 | 253|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity2_4 | 254|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity2_5 | 255|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity_0  | 314|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity_1  |  83|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity_14 |  96|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity_15 |  97|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity_16 |  98|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity_17 |  99|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity_18 | 100|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity_19 | 101|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity_2  |  84|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity_24 | 315|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity_4  |  86|     1     |    1     |   o    |   o    |   X    |
|tb_object_entity_5  |  87|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity_6  |  88|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity_7  |  89|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity_8  |  90|     1     |    1     |   o    |   X    |   o    |
|tb_object_entity_9  |  91|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka1_0  | 321|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka1_1  | 179|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka1_11 | 189|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka1_12 | 190|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka1_2  | 180|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka1_20 | 198|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka1_21 | 199|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka1_22 | 200|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka1_23 | 201|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka1_24 | 322|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka1_3  | 181|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka1_4  | 182|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka1_5  | 183|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka1_6  | 184|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka1_7  | 185|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka1_8  | 186|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka1_9  | 187|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka2_0  | 298|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka2_1  | 203|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka2_10 | 212|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka2_11 | 213|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka2_12 | 214|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka2_13 | 215|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka2_14 | 216|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka2_15 | 217|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka2_16 | 218|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka2_17 | 219|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka2_18 | 220|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka2_19 | 221|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka2_2  | 204|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka2_24 | 299|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka2_3  | 205|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka2_4  | 206|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka2_8  | 210|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_0   | 306|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_1   | 107|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_10  | 116|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_12  | 118|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka_13  | 119|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka_14  | 120|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka_15  | 121|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka_16  | 122|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_17  | 123|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_18  | 124|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka_19  | 125|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka_2   | 108|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_20  | 126|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_21  | 127|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_22  | 128|     1     |    1     |   o    |   o    |   X    |
|tb_object_linka_23  | 129|     1     |    1     |   o    |   X    |   o    |
|tb_object_linka_24  | 307|     1     |    1     |   o    |   X    |   o    |
|tb_object_linkb_0   | 300|     1     |    1     |   o    |   o    |   X    |
|tb_object_linkb_1   | 131|     1     |    1     |   o    |   o    |   X    |
|tb_object_linkb_10  | 140|     1     |    1     |   o    |   o    |   X    |
|tb_object_linkb_11  | 141|     1     |    1     |   o    |   o    |   X    |
|tb_object_linkb_12  | 142|     1     |    1     |   o    |   o    |   X    |
|tb_object_linkb_13  | 143|     1     |    1     |   o    |   X    |   o    |
|tb_object_linkb_14  | 144|     1     |    1     |   o    |   X    |   o    |
|tb_object_linkb_15  | 145|     1     |    1     |   o    |   X    |   o    |
|tb_object_linkb_16  | 146|     1     |    1     |   o    |   X    |   o    |
|tb_object_linkb_17  | 147|     1     |    1     |   o    |   X    |   o    |
|tb_object_linkb_18  | 148|     1     |    1     |   o    |   X    |   o    |
|tb_object_linkb_19  | 149|     1     |    1     |   o    |   X    |   o    |
|tb_object_linkb_2   | 132|     1     |    1     |   o    |   o    |   X    |
|tb_object_linkb_22  | 152|     1     |    1     |   o    |   o    |   X    |
|tb_object_linkb_23  | 153|     1     |    1     |   o    |   o    |   X    |
|tb_object_linkb_24  | 301|     1     |    1     |   o    |   X    |   o    |
|tb_object_linkb_3   | 133|     1     |    1     |   o    |   o    |   X    |
|tb_object_links     | 329|     1     |    1     |   o    |   X    |   o    |
|tb_object_links_10  | 339|     1     |    1     |   o    |   o    |   X    |
|tb_object_links_11  | 340|     1     |    1     |   o    |   o    |   X    |
|tb_object_links_12  | 341|     1     |    1     |   o    |   X    |   o    |
|tb_object_links_13  | 342|     1     |    1     |   o    |   o    |   X    |
|tb_object_links_16  | 345|     1     |    1     |   o    |   o    |   X    |
|tb_object_links_17  | 346|     1     |    1     |   o    |   o    |   X    |
|tb_object_links_20  | 349|     1     |    1     |   o    |   X    |   o    |
|tb_object_links_21  | 350|     1     |    1     |   o    |   o    |   X    |
|tb_object_links_22  | 351|     1     |    1     |   o    |   o    |   X    |
|tb_object_links_23  | 352|     1     |    1     |   o    |   o    |   X    |
|tb_object_links_5   | 334|     1     |    1     |   o    |   X    |   o    |
|tb_object_links_6   | 335|     1     |    1     |   o    |   X    |   o    |
|tb_object_links_7   | 336|     1     |    1     |   o    |   X    |   o    |
|tb_object_links_8   | 337|     1     |    1     |   o    |   X    |   o    |
|tb_object_links_9   | 338|     1     |    1     |   o    |   X    |   o    |
|v                   |   9|     1     |    1     |   o    |   o    |   X    |
|v_0                 | 327|     1     |    1     |   o    |   o    |   X    |
|v_10                |  19|     1     |    1     |   o    |   X    |   o    |
|v_11                |  20|     1     |    1     |   o    |   X    |   o    |
|v_12                |  21|     1     |    1     |   o    |   X    |   o    |
|v_13                |  22|     1     |    1     |   o    |   X    |   o    |
|v_14                |  23|     1     |    1     |   o    |   X    |   o    |
|v_15                |  24|     1     |    1     |   o    |   X    |   o    |
|v_16                |  25|     1     |    1     |   o    |   X    |   o    |
|v_17                |  26|     1     |    1     |   o    |   o    |   X    |
|v_24                | 328|     1     |    1     |   o    |   X    |   o    |
|v_3                 |  12|     1     |    1     |   o    |   o    |   X    |
|v_5                 |  14|     1     |    1     |   o    |   o    |   X    |
|v_6                 |  15|     1     |    1     |   o    |   o    |   X    |
|v_7                 |  16|     1     |    1     |   o    |   o    |   X    |
|v_8                 |  17|     1     |    1     |   o    |   o    |   X    |
|v_9                 |  18|     1     |    1     |   o    |   o    |   X    |
+--------------------+----+-----------+----------+--------+--------+--------+
' in 0.017000 sec(s).

**Comment by lvca** [comment]
Thanks for reporting it. Fixed in 2.2.x branch.
