### ISSUE TITLE
Port backup.sh and stresstester.sh to windows

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#6909]
## OrientDB Version, operating system, or hardware.
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Windows

Port backup.sh and stresstester.sh to windows

**Comment by santo-it** [comment]
I can work on this

**Comment by lvca** [comment]
@santo-it any news on this?
