### ISSUE TITLE
How  to query graph data via JDBC?

### ISSUE THREAD

**Issue by youzp** [orientechnologies/orientdb#6912]
## OrientDB Version, operating system, or hardware.
- v2.2.12

## Operating System
- Linux

## Expected behavior and actual behavior
Error prompt is this way, and how to get the graph vertex data?
**Exception in thread "main" java.lang.ClassCastException: com.orientechnologies.orient.jdbc.OrientJdbcResultSet cannot be cast to com.tinkerpop.blueprints.impls.orient.OrientVertex**
## Steps to reproduce the problem
```
Class.forName("com.orientechnologies.orient.jdbc.OrientJdbcDriver");

Properties info = new Properties();
info.put("user", "orientdb");
info.put("password", "orientdb");
info.put("db.usePool", "true");
info.put("db.pool.min", "1");
info.put("db.pool.max", "10");

Connection conn = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:remote:localhost/mydb", info);
Statement stmt = conn.createStatement();
ResultSet rs = stmt.executeQuery("SELECT expand(both(enemy)) FROM v2000 WHERE id=1");

while (rs.next()) {
	OrientVertex vetex = (OrientVertex) rs; // error here
	int id = vetex.getProperty("id");
	System.out.println("id is " + id);
}
```

**Comment by robfrank** [comment]
The JDBC api can't return native objects because it is plain old JDBC.
Usually, the JDBC driver is used inside legacy applications to avoid use of native objects. 
If you need native objects, you should use the native API.

**Comment by youzp** [comment]
@robfrank ok,thank you so much! The native API works properly.
```
final Object result = 
graph
.command(new OCommandSQL(
		"SELECT expand(both(enemy)) FROM v2000 WHERE id=1"))
.execute();

if (result instanceof OrientDynaElementIterable) {
	OrientDynaElementIterable it = (OrientDynaElementIterable) result;
	for (Object obj : it) {
		OrientVertex vertex = (OrientVertex) obj;
		int id = vertex.getProperty("id");
		System.out.println("id=" + id);
	}
}
```
