### ISSUE TITLE
Is it possible to get records without meta-information? Exclude: @type, @version, etc...

### ISSUE THREAD

**Issue by rcdiaz** [orientechnologies/orientdb#6913]
Can I get records without this parameters?

"@type": "d",
"@rid": "#21:2",
"@version": 1,
"@class": "EHR",
  notification": "Query executed in 0.066 sec. Returned 3 record(s)"

I have tried with:
select expand(@this.exclude('@type','@rid','@version','@class')) from v

But only omits rid and class:

`select * from pueblo
{
    "result": [
        {
            "@type": "d",
            "@rid": "#67:0",
            "@version": 1,
            "@class": "pueblo",
            "name": "malagon"
        },
        {
            "@type": "d",
            "@rid": "#68:0",
            "@version": 1,
            "@class": "pueblo",
            "name": "pozuelo"
        },
        {
            "@type": "d",
            "@rid": "#69:0",
            "@version": 1,
            "@class": "pueblo",
            "name": "valenzuela"
        }
    ],
    "notification": "Query executed in 0.038 sec. Returned 3 record(s)"
}

select expand(@this.exclude('@type','@rid','@version','@class')) from pueblo
{
    "result": [
        {
            "@type": "d",
            "@version": 1,
            "name": "malagon"
        },
        {
            "@type": "d",
            "@version": 1,
            "name": "pozuelo"
        },
        {
            "@type": "d",
            "@version": 1,
            "name": "valenzuela"
        }
    ],
    "notification": "Query executed in 0.039 sec. Returned 3 record(s)"
}`

**Comment by rcdiaz** [comment]
help

**Comment by tglman** [comment]
hi @rcdiaz,

No is not possible to get out record without metadata, this are needed to reassociate the persistent data in case of update.

Bye

**Comment by StarpTech** [comment]
HI @tglman whats in the case of temporary rids? You dont need them for anyhting.

**Comment by tglman** [comment]
hi All,

Temporary rids are used in many places to reassociate references and define an unique identifier for each item of result of a projection query, as today the data structures of a projection query are the same of a persistent result set. This cannot be changed right now.

In any case we may evolve with new api that not require this in formation in case of projections, but nothing possible yet.

**Comment by rcdiaz** [comment]
Hi @tglman 

Would not it be possible to create this structure and retrieve
only the value field without meta information?

"@type": "d",
"@rid": "#67:0",
"@version": 1,
"@class": "pueblo",
"value": {
    "name" : "malagon",
    "country": "Spain"
}

I am trying with the json function but I have the same problem:
it's adding metainformation so I'm not worth it, I have to retrieve the information as it is, but I've encapsulated it in the value property

select value from prueba
`{"status":{"otherDetails":{"items":[{"items":[{"name":{"value":"Administrative Gender","class":"DV_TEXT"},"ehrId":"2d903575-be12-4334-b1dc-35e3126830ca"}`

select value.toJson() from prueba
{"**@type":"d","@version":0**,"{"status":{"otherDetails":{"items":[{"items":[{"name":{"value":"Administrative Gender","class":"DV_TEXT"},"ehrId":"2d903575-be12-4334-b1dc-35e3126830ca"}
- mostrar texto citado -

**Comment by tglman** [comment]
hi @rcdiaz,

The result set of a query in orient is a document, you cannot remove the metadata from it.

Regards

**Comment by luigidellaquila** [comment]
Quick update on this, in V 3.0 projections won't have record metadata anymore. See http://orientdb.com/docs/3.0.x/sql/SQL-Projections.html

Thanks

Luigi
