### ISSUE TITLE
Remove old nodes from distributed-config.json not working with autoRemoveOfflineServers

### ISSUE THREAD

**Issue by tomasaftalion** [orientechnologies/orientdb#6915]
Version: 2.2.0
OS: Linux 16.04

Hi, I've been reading isues #6784 and #6862 but can't seem to get it to work either by adding 

`<entry value="0" name="distributed.autoRemoveOfflineServers"/>`

to <properties></properties> within orientdb-server-config.xml or by including directly the flag

`-Ddistributed.autoRemoveOfflineServers=0`

to dserver.sh.

I'm working within aws, using hazelcast and I am able to get two instances to sync.  However, when I terminate one instance and continue to write to the other I first get this error:

```
2016-11-16 00:51:20:072 WARNI [node1479257038726] timeout (6001ms) on waiting for synchronous responses from nodes=[node1479257251864, node1479257038726] responsesSoFar=[node1479257038726] request=(id=0.8 task=record_create(#56:1 v.0) user=#5:0) [ODistributedDatabaseImpl]
2016-11-16 00:51:20:072 WARNI [node1479257038726] Detected 1 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=0.8 task=record_create(#56:1 v.0) user=#5:0) [ODistributedResponseManager]
2016-11-16 00:51:20:076 SEVER Internal server error:
com.orientechnologies.orient.server.distributed.task.ODistributedOperationException: Quorum 2 not reached for request (id=0.8 task=record_create(#56:1 v.0) user=#5:0). Elapsed=6002ms No server in conflict. Received: 
 - node1479257251864: waiting-for-response
 - node1479257038726: #56:1 v.1
	Storage URL="plocal:/home/ubuntu/orientdb/databases/GratefulDeadConcerts" [ONetworkProtocolHttpDb]
```
and later this one:

```
2016-11-16 00:53:28:383 SEVER Internal server error:
com.orientechnologies.orient.server.distributed.ODistributedException: Quorum (2) cannot be reached because it is major than available nodes (1) [ONetworkProtocolHttpDb]
```

The intended behaviour is that as soon one instance becomes unavailable I should be able to continue writing to the other. The autoRemoveOfflineServers flag is not working because the distributed-config.json file still has the terminated instance. Only hack that I've found to make this work is to force the write quorum to 2 rather than majority but it is not ideal. What other configuration flag setting should I include or what am I missing?

**Comment by lvca** [comment]
Please upgrade to 2.2.13.

**Comment by tomasaftalion** [comment]
switched 2.2.13 but the problem persists. Still getting

`Quorum (2) cannot be reached because it is major than available nodes (1)`

checked distributed-config.json and it still contains the terminated node, it wasn't automatically updated.

**Comment by lvca** [comment]
Set `  "newNodeStrategy": "dynamic",` in your `distributed-config.json` file under all the database's directories. Example:

```json
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}

```

**Comment by lvca** [comment]
In v2.3 dynamic will be the default, but we cannot change the default behaviour in an hot-fix, sorry.

**Comment by tomasaftalion** [comment]
No problem! thank you, worked.

**Comment by lvca** [comment]
Cool, thanks.
