### ISSUE TITLE
OStorageException: Error on creation of shared resource NullPointerException: Name is null

### ISSUE THREAD

**Issue by aligin** [orientechnologies/orientdb#6917]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[x] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [x] Other, name? - Docker

## Expected behavior and actual behavior
The database can't be opened.
## Steps to reproduce the problem
I'm not sure how to reproduce the problem. I describe my guesswork.
I've created a sequence that is used to generate uniq Ids for my entities. At some point orient started to log errors on sequence.next() (null.next() error). After these when I shutdown the orient. I can't connect to this database. 

The error log says
```
2016-11-16 07:39:50:870 SEVER Internal server error:
com.orientechnologies.orient.core.exception.OStorageException: Error on creation of shared resource
        DB name="test_rsm_service"
--> java.lang.NullPointerException: Name is null [ONetworkProtocolHttpDb]
```
The problem is that I can't even delete database got making import/export.

I used v.2.2.2. For the sequence error problem I've found 	a similar issue #6842 that is closed in 2.2.13 that is potential solve issue in future. But the database not opening now.
[test_rsm_service.zip](https://github.com/orientechnologies/orientdb/files/594051/test_rsm_service.zip)

**Comment by laa** [comment]
@luigidellaquila this storage exception is thrown outside of storage and misleading  that is bug with squence not with storage. NPE happens there com.orientechnologies.orient.core.metadata.sequence.OSequence#getSequenceType(com.orientechnologies.orient.core.record.impl.ODocument) .
The first thing which we need is normal logging of exceptions. I mean presence  of full stack trace @maggiolo00 , is it possible to do ? 
I am providing workaround for this but and assign it to @lvca for final fix.

**Comment by laa** [comment]
@aligin could you try this build https://drive.google.com/file/d/0B2oZq2xVp841V3lDYmNJSUpRb1U/view?usp=sharing and open database ?

**Comment by aligin** [comment]
Hello @laa. Yes, the database now opens.

**Comment by laa** [comment]
@aligin Cool I will reassing to @lvca for final fix

**Comment by lvca** [comment]
What's the remaining issue?

**Comment by laa** [comment]
This behaviour 
"I've created a sequence that is used to generate unique Ids for my entities. At some point orient started to log errors on sequence.next() (null.next() error). " caused presence of broken sequences in database.  Now we just ignore them on database open, but I suppose that sequence data should not be broken.
