### ISSUE TITLE
Orientdb distributed setup not working when one node goes down

### ISSUE THREAD

**Issue by prakashpandey** [orientechnologies/orientdb#6918]
## Operating System
- [x] Linux 

## I have **two node** in **Orientdb** **distributed** mode named "**server1**" at port "2424" and "**server2**" at port "2425". 

**I am running them as "dserver.sh".** both running as shown below : 

```
`+--------+--------+-------------------------------------------+-----+---------+--------------------+--------------------+-------------------------+
|Name    |Status  |Databases                                  |Conns|StartedOn|Binary              |HTTP                |UsedMemory               |
+--------+--------+-------------------------------------------+-----+---------+--------------------+--------------------+-------------------------+
|server1*|STARTING|GratefulDeadConcerts=SYNCHRONIZING (MASTER)|1    |12:39:58 |150.129.180.157:2424|150.129.180.157:2480|27.59MB/491.50MB (5.61%) |
|server2 |ONLINE  |GratefulDeadConcerts=ONLINE (MASTER)       |2    |12:25:20 |150.129.180.157:2425|150.129.180.157:2481|64.33MB/480.50MB (13.39%)|
+--------+--------+-------------------------------------------+-----+---------+--------------------+--------------------+-------------------------+
`
```
**When both are "online" insertion, replication and everything is working. But when I am making "Server1 at port 2424" offline by force closing (for testing), default behavior should be** ,
**It should connect to "Server2" automatically and start inserting data there.**

But I am getting the following error : 

```
java.sql.SQLException: Error while executing command
	at com.orientechnologies.orient.jdbc.OrientJdbcPreparedStatement.executeCommand(OrientJdbcPreparedStatement.java:118)
	at com.orientechnologies.orient.jdbc.OrientJdbcStatement.execute(OrientJdbcStatement.java:112)
	at com.orientechnologies.orient.jdbc.OrientJdbcPreparedStatement.execute(OrientJdbcPreparedStatement.java:204)
	at GraphDatabase.Serv
GraphDatabase.Services.Edge.createOrUpdateEdge(Edge.java:35)
	at GraphDatabase.Controller.Brain.execute(Brain.java:50)
	at GraphDatabase.DataSource.DataSource.execute(DataSource.java:47)
	at GraphDatabase.DataSource.DataSource.run(DataSource.java:19)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


**Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum (2) cannot be reached because it is major than available nodes (1)**
	at sun.reflect.GeneratedConstructorAccessor3.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:437)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:388)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:270)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:162)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2167)
	at com.orientechnologies.orient.client.remote.OStorageRemote$27.execute(OStorageRemote.java:1160)
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:196)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:235)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:193)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:204)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1136)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.jdbc.OrientJdbcPreparedStatement.executeCommand(OrientJdbcPreparedStatement.java:116)
	
```

**I am connecting to the remote database as following** 

```
Connection conn = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:remote:"  + IP+ ":" + "2424" + ";" + IP + ":" + "2425" + "/"
						+ appName, info);
```

**What I want to achieve :** 
- Set up a distributed database
- If one server(node) goes down, it should automatically switch to other  

How can I achieve this?

Thanks ..!

**Comment by voondo** [comment]
You have to look at `distributed.autoRemoveOfflineServers` (default -1) https://orientdb.com/docs/last/Configuration.html#distributedautoremoveofflineservers

**Comment by prakashpandey** [comment]
**I tried by giving**  `distributed.autoRemoveOfflineServers = 0`.

Below is my database connection code :

`distributed.autoRemoveOfflineServers = 0`


`Properties info = new Properties();
				info.put("user", "root");
				info.put("password", "pcp");
				info.put("distributed.autoRemoveOfflineServers", "0");
				Connection conn = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:remote:"  + UserflowConstant.ip + ":" + UserflowConstant.port + ";" + UserflowConstant.ip + ":" + UserflowConstant.port2 + "/"
						+ appName, info);

				System.out.println(" Database Connection  instance returned for : " + appName  + " for thread ID : " + Thread.currentThread().getId());

				return conn;`

**But getting this error :** 

`Quorum (2) cannot be reached because it is major than available nodes (1)`

**Comment by lvca** [comment]
You can't use that setting through JDBC, but you have to put it in `orientdb-server-config.xml` file, in the last section.

Starting from OrientDB 2.2.13 (GA, not SNAPSHOT) you can also set this in your `distributed-config.json` file this setting: `"newNodeStrategy": "dynamic"`. This is the whole file:


```json
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

**Comment by prakashpandey** [comment]
**By `distributed-config.json`  do you mean  `config/default-distributed-db-config.json` because there is no such file  `distributed-config.json` in my `conf` directory.**

**If yes then  "newNodeStrategy": "dynamic"`` din't worked**.

Here is my default-distributed-db-config.json for both servers (server1 and server2)

server1

```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

Server2

```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

Got same error : 

```
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum (2) cannot be reached because it is major than available nodes (1)
	at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
```

**Comment by prakashpandey** [comment]
Here is few more things I tested :

- Set up a distributed node server (**Server1 & Server2**)
- Connect to database as follows (Server1 IP first, then Server2)

```
Connection conn = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:remote:"  + ip + ":" + port + ";" + ip + ":" +port2 + "/"
                        + appName, info);
```

- Keep Server1 offline and run your program

- Got the same error

```
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum (2) cannot be reached because it is major than available nodes (1)
    at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
```

default-distributed-db-config.json is same on both server and it's 

```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

This is very simple use case and I think this should at-least work

**Comment by lvca** [comment]
Once the cluster is running the distributed cfg is the one stored in each database's folder. Please set that `  "newNodeStrategy": "dynamic"` in all of them.

**Comment by lvca** [comment]
In v2.3 dynamic will be the default, but we cannot change the default behaviour in an hot-fix, sorry.

**Comment by prakashpandey** [comment]
Dear Luca, 
thanks for your prompt reply.

I did what you said, `"newNodeStrategy": "dynamic"` on both server **but got same error**

```
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum (2) cannot be reached because it is major than available nodes (1)
    at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
```

**distributed-config.json file of my database on both server :** 

`{"@type":"d","@version":0,"autoDeploy":true,"readQuorum":1,"writeQuorum":"majority","executionMode":"undefined","readYourWrites":true,"newNodeStrategy":"dynamic","servers":{"@type":"d","@version":0,"*":"master","server1":"MASTER","server2":"MASTER"},"clusters":{"@type":"d","@version":0,"internal":{"@type":"d","@version":0},"*":{"@type":"d","@version":0,"servers":["server1","server2","<NEW_NODE>"]},"e":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"e_1":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"ofunction_0":{"@type":"d","@version":0,"servers":["server1","server2","<NEW_NODE>"]},"oschedule_0":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"orole_0":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"v_1":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"v_2":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"ouser_0":{"@type":"d","@version":0,"servers":["server1","server2","<NEW_NODE>"]},"osequence_0":{"@type":"d","@version":0,"servers":["server1","server2","<NEW_NODE>"]},"_studio":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"_studio_3":{"@type":"d","@version":0,"servers":["server1","server2","<NEW_NODE>"]},"_studio_2":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"ouser":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"ofunction":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]},"osequence":{"@type":"d","@version":0,"servers":["server2","server1","<NEW_NODE>"]}},"version":23}`

**Comment by prakashpandey** [comment]
One more thing I want to ask

- I put my first server down (for testing), and run my application
- connected to db as  follows

```
Connection conn = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:remote:"  + ip + ":" + port + ";" + ip + ":" +port2 + "/"
                        + appName, info);
```


What it should ideally do is : connect to `IP+PORT2` as `IP+PORT1` is offline.

**But I is giving same error**

```
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum (2) cannot be reached because it is major than available nodes (1)
    at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
```

**Note** : vale of `"newNodeStrategy": "dynamic"` in `distributed-config.json`

**Comment by lvca** [comment]
Ok, with the old configuration both servers are registered. Please remove both servers from the "servers" configuration:

`"servers": []`

**Comment by prakashpandey** [comment]
I did "servers": []

distributed-config.json file of server 2 : 

`{"@type":"d","@version":0,"autoDeploy":true,"readQuorum":1,"writeQuorum":"majority","executionMode":"undefined","readYourWrites":true,"newNodeStrategy":"dynamic","servers":{"@type":"d","@version":0,"*":"master","server1":"MASTER","server2":"MASTER"},"clusters":{"@type":"d","@version":0,"internal":{"@type":"d","@version":0},"*":{"@type":"d","@version":0,"servers":[]},"e":{"@type":"d","@version":0,"servers":[]},"e_1":{"@type":"d","@version":0,"servers":[]},"ofunction_0":{"@type":"d","@version":0,"servers":[]},"oschedule_0":{"@type":"d","@version":0,"servers":[]},"orole_0":{"@type":"d","@version":0,"servers":[]},"v_1":{"@type":"d","@version":0,"servers":[]},"v_2":{"@type":"d","@version":0,"servers":[]},"ouser_0":{"@type":"d","@version":0,"servers":[]},"osequence_0":{"@type":"d","@version":0,"servers":[]},"_studio":{"@type":"d","@version":0,"servers":[]},"_studio_3":{"@type":"d","@version":0,"servers":[]},"_studio_2":{"@type":"d","@version":0,"servers":[]},"ouser":{"@type":"d","@version":0,"servers":[]},"ofunction":{"@type":"d","@version":0,"servers":[]},"osequence":{"@type":"d","@version":0,"servers":[]}},"version":20}`

**didn't work , gave same error**

I think when distributed server is starting, its overwriting these `distributed-config.json` files.

I **request** you to please release **some hotfix.**

**Or**

Any other **way** I can **achieve** this :

- Set up a distributed database
- If one server(node) goes down, it should automatically switch to other

Thanks..!

**Comment by lvca** [comment]
When you stop the cluster, are you 100% sure you set `"servers": []` in all `distributed-config.json` files of all the databases directories of all the servers?

What really matter is the first server that starts, you could even change it on the first server only (the file in the database directories) and then start the other servers. The other servers just download the configuration from the first node.

**Comment by prakashpandey** [comment]
Ok ..! I will try it with a fresh installation.

and will shortly report back..!

Do you want me to make
 `"servers":{"@type":"d","@version":0,"*":"master","server1":"MASTER","server2":"MASTER"}` 
also blank i.e
"servers":{}

**Comment by prakashpandey** [comment]
Dear Luca,

**It worked** :+1 (when one node goes down it shift to other): 

But here are few issues I got during my Testing of Orientdb v2.2.13 : 

I have two servers `server1 & server2`

1. When `server1 `went down it shifted to `server2`  **but when `server1` came online I got the following message and exception on console**

```
Orientdb shutting down
Exception in thread "main" java.lang.NullPointerException
	at test.Services.App.preparedStatement(VertexService.java:129)
```
2. Writing **speed** at `server2 ` is **slower** than writing speed at `server1 `

**Comment by tanhv90** [comment]
Hi @prakashpandey 

Seem that your configuration is wrong.
>   "writeQuorum": "majority"

It means that OrientDB need N/2 + 1 servers alive in case you want to write something to DB.
with N is number of servers. In your case it is: 2/2 + 1 = 2 servers.

Please refer to [this link](http://orientdb.com/docs/2.2/Distributed-Configuration.html#default-distributed-db-configjson) for more detail information.

Hope this help.
Thanks.

**Comment by prakashpandey** [comment]
Hi Tan Ho,

I tried with 3 Nodes `server1, server2, server3` all running in distributed mode.

When `server1 `went down and came back **got same exception**

My writeQuorum is default (majority)

3/3 + 1 = 2 (**`server2, server3 are alive`**)

- when server1 went offline, other 2 server worked well
- but when server1 came back online , got same exception 

```
Exception in thread "main" java.lang.NullPointerException
    at test.Services.App.preparedStatement(VertexService.java:129)
```

**Comment by lvca** [comment]
Hi, VertexService is your class, so the NPE is on your code. Could you please share it with me?

**Comment by prakashpandey** [comment]
I solved it.

I think it take some time to switch between servers(when one server goes down)
**Null pointer exception was because it take some time to switch between servers and if you hit server between switching** you get this exception,

```
Schema is not created and cannot be loaded
	DB name="TestDb"
```

**I solved it by making thread sleep for some time and than everything executed well.**

The only problem I am facing now is : 

When it switch from Server1 to Server2 speed of writing is slower than that in Server1 (both have same configuration as they are copy of each other).

**Comment by lvca** [comment]
@prakashpandey About the speed, what's the difference? Where the client and servers are located in the network?

**Comment by eduardnegru** [comment]
> Dear Luca,
> 
> **It worked** :+1 (when one node goes down it shift to other successfully):
> 
> **But here are few issues I got during my Testing of Orientdb v2.2.13**
> 
> I have two servers `server1 & server2`
> 
>     * When `server1`went down it shifted to `server2`  **but when `server1` came online I got the following message and exception on console**
> 
> 
> ```
> Orientdb shutting down
> Exception in thread "main" java.lang.NullPointerException
>     at test.Services.App.preparedStatement(VertexService.java:129)
> ```
> 
>     * Writing **speed** at `server2` is **slower** than writing speed at `server1`
> 
> 
> Note : **both** nodes have **same configuration** as `server2`is copy of `server1`

Can you tell us the solution? Did you change only the servers list to empty list or did you change the server object as well? Did you change distributed.autoRemoveOfflineServers?
