### ISSUE TITLE
Difference between ODatabaseDocument.load(ORID orid) and ORID.getRecord()

### ISSUE THREAD

**Issue by kerner1000** [orientechnologies/orientdb#6919]
OrientDB v. 2.1.16

Operation System Linux

I was wondering what is the difference between 
`db.load(someORID)`
and
`someORID.getRecord()`

**Comment by tglman** [comment]
hi @kerner1000,

No much difference, the only thing is the `rid.getRecord()` rely on thread local.

here how is actually implemented the `rid.getRecord()` https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/orient/core/id/ORecordId.java#L329

I would suggest to use most of the time db.load so in long term we can remove the thread local from the orient architecture.

**Comment by kerner1000** [comment]
Many thanks for the fast reply!

> I would suggest to use most of the time db.load so in long term we can remove the thread local from the orient architecture.

That would be good! The thread local db instance was not the best design decision I think. Anyways great work, thanks a lot!
