### ISSUE TITLE
percentile() returns same result for all percentages

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6920]
## OrientDB Version, operating system, or hardware.

- v2.2 SNAPSHOT[13 ] 

## Operating System
- [x ] Linux

## Expected behavior 
sensible data!
## Actual behavior
select percentile(samples,nn) from whatever
## Steps to reproduce the problem
Insert 255, 168, 125, 11102, 59, 120, 500, 2, 98, 25 these values into some class
as floats, and run select percentile(samples,90) from "whatever".
 
even try 50 or any value - percentile returns the same value, 11102.0!

By the way, median() does it correctly, i.e. returns 122.5

**Comment by luigidellaquila** [comment]
Hi @austx 

Ok, I got the problem, the quantiles have to be passed in a range 0-1, eg.

select percentile(samples, 0.9) from whatever

The docs are definitely flawed, I'm sorry about that, I'm updating them

Thanks

Luigi
