### ISSUE TITLE
Adding new spatial reference system native support in lucene Engine for OrientDB

### ISSUE THREAD

**Issue by parle-g** [orientechnologies/orientdb#6921]
##
I am working on an Open Source GIS project and new to Spatial Reference systems and would like to discuss something on the same.

As we know the new Lucene Plugin for OrientDB (version 2.2) is enhanced with Support of Complex Geometry like line, polygon etc.
I am exploring on adding a new spatial reference system native support for storage and retrieval of spatial data in lucene Plugin for OrientDB.

Currently Lucene Engine supports well known WSG_84 reference system.
I would like to add a native support for a new SRS(Spatial Reference System) i.e. EPSG:27700 and other. i don't want to go with SRS conversions using external library like proj4.

As per my analysis for the support added in Lucene for WSG_84. I found datum configuration parameters in PlanetModel class file like :

    WGS84_MEAN = 6371009.0;
    WGS84_POLAR = 6356752.314245;
    WGS84_EQUATORIAL = 6378137.0;
    PlanetModel WGS84 = new PlanetModel (1.0011188180710464, 0.9977622562211103);

which are used in Mathematical evaluations for calculating Flattering of earth, North Pole, South Pole geographical reference Points etc.

I am suspecting this configuration are specific to WSG_84 Spatial reference system only. Is my understanding correct?
And similarly, there will be new set of configuration needs to be defined for other reference system to achieve a native support in the DB storage and retrieval of GeoSpatial Data.
Or WSG_84 is a base reference system for all the other Reference Systems and conversion has to happen?

Any suggestion will be very helpful. 
Thanks in Advance.

Regards,
vikram

**Comment by maggiolo00** [comment]
Hi @parle-g 

Thanks for your interest. 
I was looking for other SRS support in lucene-spatial but i didn't find any documentation or example. 

Under the hood lucene spatial uses this two library 

https://github.com/locationtech/spatial4j
https://sourceforge.net/projects/jts-topo-suite/

Did you find anything on lucene side ?
