### ISSUE TITLE
Studio always suggests root login

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6924]
## OrientDB Version, operating system, or hardware.
All versions

## Operating System
- [x ] Linux

## Expected behavior and actual behavior
Suggest either empty(w/drop-down), or admin as default

## Steps to reproduce the problem
fire up studio.

**Comment by maggiolo00** [comment]
@austx 

that is probably the browser that fill the form with root login

**Comment by prakashpandey** [comment]
clear your auto save password for orientdb

**Comment by austx** [comment]
Yes, of course. Thanks!
