### ISSUE TITLE
Datetime UTC format

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientdb#6925]
## OrientDB Version, operating system, or hardware.
OrientDB 2.2.13 community edition

## Operating System
- [x] Linux - Ubuntu 16.04
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I'm trying to store ISO 8601 Dates in this format:  
2016-11-16T15:30:25.000Z -0800 
2016-12-13T12:40:15.000Z -0800

I changed the datetime format for the database: 
```sql
ALTER DATABASE DATETIMEFORMAT "yyyy-MM-dd'T'HH:mm:ss.SSS'Z' Z"
```
But when new datetime is stored like this: 
```sql
create vertex Evento content { crea: '2016-11-16T15:30:25.000Z -0800' }
```
The time zone stored always is -0600 instead -0800, i know that -0600 is my timezone, but is it posible store datetimes whith other time zones?

**Comment by obi1kenobi** [comment]
As an aside, note that your dates are not in proper ISO 8601 form and are actually ambiguous on which time zone they have -- the Z at the end in ISO 8601 indicates "zulu" time, i.e. +0000, which contradicts the -0800 after it.

**Comment by tglman** [comment]
hi @alexmm11,

The `DATETIMEFORMAT` set only the way you are going to give the date to the database, and how is going to print them out, in case you give a date with as different timezone is converted to the database timezone and stored with that, there is no way to store a date with a different timezone, anyway you can convert the date to a different timezone in your application.

Bye

**Comment by tglman** [comment]
hi @alexmm11,

Can i close this ? the answer is simple orient don't store dates with timezones.

Regards

**Comment by alexmm11** [comment]
Hi @tglman 

Yes, thanks for the answer.
