### ISSUE TITLE
Errors with Importing and Exporting

### ISSUE THREAD

**Issue by TheAdamGalloway** [orientechnologies/orientdb#6927]
I'm not sure how to label the issues that I'm having, since I'm unsure whether they are bugs or I'm simply doing something wrong. Though it seems that no matter what I try, I am unable to import/restore a database from my local machine to a remote server.

All I am trying to do is import a database that I have locally for use on the server.
The first thing I tried was doing a simple 'export database {filename}', with a corresponding import on the remote server. It all went well until I ran the 'list classes' command, which showed that none of the classes from the original database had been imported whatsoever. I closed the database and opened it in OrientDB Studio, which confirmed that none of the classes had been imported. I went back to the console to connect to the database, but was then greeted with a 'com.orientechnologies.orient.core.exception.OSecurityAccessException' exception. I also tried connecting to the database using the root user, but to no avail.

I ended up dropping the database using the OrientDB studio, but noticed the directory was still present in /databases. I then went and created another database under a different name, as to avoid any collisions. I tried backing up my local database and restoring on the server, again no luck.

I have tried this almost 10+ times now, and each time I seem to be getting another error, such as invalid pointer exceptions. The worst part is that the import typically doesn't report any errors until I close the database and open it again. The server is just failing silently, so I have no idea what to do.

I have tried experimenting with different permissions on the databases directory (777), but this doesn't seem to help.

All I seem to have is errors with OrientDB, it is constantly making me unsure about it's readiness for a production application.

Version 2.2.0 (on server) - Linux
Version 2.2.10 (on local machine) - Windows

**Comment by tglman** [comment]
hi @TheAdamGalloway,

We fixed few bugs on this topics you should setup on the server the last stable verision of orientdb, that currently is 2.2.13.

Hope it helps.

**Comment by TheAdamGalloway** [comment]
Hey @tglman,

I was thinking of updating but decided not to because of the issues with migrating the current databases. If I update now, will I have any issues with the current databases?

Thanks

**Comment by tglman** [comment]
Hi @TheAdamGalloway,

Between hotfixes we guarantee disc and API compatibiilty, so you should not have any issue.

Regards

**Comment by TheAdamGalloway** [comment]
@tglman 

Thanks. Will I have to manually import and export, or can I just copy over the config and database directories?

**Comment by TheAdamGalloway** [comment]
Update: I have upgraded to Orient 2.2.13, but I am **still** getting 401 unauthorised errors after doing a fresh restore of the database. Everything is imported correctly, and I can log in successfully through the console, but not through the console.

**Comment by tglman** [comment]
hi @TheAdamGalloway,

Do you have problem with studio or the console ?

Bye

**Comment by TheAdamGalloway** [comment]
@tglman I was having problems with the Studio, and with remote access using the console. I changed the permissions on the database directory to 777, and it started working, so it must be a permissions error on my part.  I've sorted it now, though no idea why the permissions are like that.

**Comment by tglman** [comment]
hi @TheAdamGalloway,

Anyway the import was it ok? can we close this ?

**Comment by TheAdamGalloway** [comment]
@tglman Yeah, fine in the end, I'll close it.
