### ISSUE TITLE
Create edge from an existing to a new vertex in the same transaction

### ISSUE THREAD

**Issue by borov333** [orientechnologies/orientdb#6929]
## OrientDB Version, operating system, or hardware.
- v2.2.12

## Operating System
- [X] Linux
- [X] MacOSX

## Expected behavior and actual behavior
This is a feature request based on the google goop discussion https://groups.google.com/forum/#!topic/orient-database/DE8gF1-7MwE.

When I create a new vertex (document) I want to be able to create an edge from an existing document to the newly created one - all in a single transaction. Apparently, OrientDB can't create an edge to the new document in the same transaction because the RID for the new document is in a temporary state. The only way I can do it is to create a document first and then create an edge, two transactions. This introduces a risk of creating a document but never creating an edge to it.

## Steps to reproduce the problem
Here is a simple version of the code:

```
ODatabaseDocumentTx db = DbPool.getConnection();
String existingRid = "#111:1";

try {
    db.begin();

    // create transaction record
    ODocument doc = new ODocument("TransactionDirectPost");
    ODocument transaction = doc.save();
    String transactionRid = transaction.getIdentity().toString();

    // change data state to sold
    String sql = "update ? set metaInternal.dataState = ?";
    db.command(new OCommandSQL(sql)).execute(new ORecordId(existingRid), "SOLD");

    // create an edge
    sql = "create edge SentDirectPost from ? to ?";
    db.command(new OCommandSQL(sql)).execute(new ORecordId(existingRid), new ORecordId(transactionRid));

    db.commit();
} catch (Exception e) {
    db.rollback();
} finally {
    db.close();
}
```

Error I'm getting:
`Cannot read record #-1:-2 since the position is invalid in database 'Customers'`

In the above code, we need to execute 3 commands as part of one transaction: create new document, update a property of another document and create an edge from an existing document to the newly created. The first 2 are fine, but the edge creation fails with the complaint about the RID. It seems that the edge can't be created in the transaction for the temporary RID of the just created document.

Intuitively, I feel that if the edge creation is the last command that must be executed when transaction is committed on the server's end, it shall use temporary RID and map it internally to the permanent (since at the time of the 3rd command the created document must have the permanent RID already) and be able to create an edge.

**Comment by laa** [comment]
@borov333 do you use remote storage , do not you ?

**Comment by borov333** [comment]
Yes, I do use remote.

**Comment by tglman** [comment]
hi @borov333,

In remote sql operation are run outside the transaction, so you need to use java api for create the vertex.

here the documentation about it : http://orientdb.com/docs/last/Transactions.html#breaking-of-acid-properties-when-using-remote-protocol-and-commands-sql-gremlin-js-etc

Regerds

**Comment by lvca** [comment]
Closing because invalid.
