### ISSUE TITLE
Verbose SQL CREATE EDGE(console.sh)

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#6930]
## OrientDB Version, operating system, or hardware.
- v2.2.13

## Operating System
- [ x] Linux

## Expected behavior and 
Created edge <whatever> ...

##Actual behavior
console.sh running osql-script which shows like in "debug mode".
Created edge 'com.orientechnologies.orient.core.sql.query.OBasicResultSet@111d' in 0.003000 sec(s).

## Steps to reproduce the problem
run a script by console.sh that creates an edge like; create edge <whatever> from (select ..) to (select ..)

**Comment by maggiolo00** [comment]
Hi @austx 

fixed, it will be available in 2.2.14
