### ISSUE TITLE
Distribution means each master server get full copy of database?

### ISSUE THREAD

**Issue by youzp** [orientechnologies/orientdb#6936]
## OrientDB Version, operating system, or hardware.
- v2.2.12

## Operating System
- [ *] Linux

## Expected behavior and actual behavior
My orientdb distributed system has five machines, all of which are master, which are inserted about 300 thousand vertices, and find that the size of the database for each machine is almost the same，why？It is worth knowing just why this is so, do distribution of orientdb only mean each master server get full copy of database? or my configuration error？
I think it should be like HDFS, the size of each data block is fixed, there are three copies of each data block.There are 5 machines in a distributed machine that represent 60% of the total size of graph data in each machine.

## Steps to reproduce the problem
(1)default-distributed-db-config.json
```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "asynchronous",
  "readYourWrites": true,
  "servers": {
    "orientdb1": "master",
    "orientdb2":"master",
    "orientdb3":"master",
    "orientdb4":"master",
    "orientdb5":"master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["orientdb1","orientdb2","orientdb3","orientdb4","orientdb5"]
    }
  }
}
```

(2) hazelcast.xml
```
<hazelcast
		xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.3.xsd"
		xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<group>
		<name>jdorientdb</name>
		<password>jdorientdb</password>
	</group>
	<properties>
		<property name="hazelcast.mancenter.enabled">false</property>
		<property name="hazelcast.memcache.enabled">false</property>
		<property name="hazelcast.rest.enabled">false</property>
		<property name="hazelcast.wait.seconds.before.join">5</property>
		<property name="hazelcast.operation.thread.count">1</property>
		<property name="hazelcast.operation.generic.thread.count">1</property>
		<property name="hazelcast.client.event.thread.count">1</property>
		<property name="hazelcast.event.thread.count">1</property>
	</properties>
	<network>
		<port auto-increment="true">2434</port>
		<join>
			<multicast enabled="false">
				<multicast-group>235.1.1.1</multicast-group>
				<multicast-port>2434</multicast-port>
			</multicast>
			 <tcp-ip enabled="true">
        			<member>orientdb1:2434</member>
        			<member>orientdb2:2434</member>
        			<member>orientdb3:2434</member>
				<member>orientdb4:2434</member>
				<member>orientdb5:2434</member>
      			</tcp-ip>			
		</join>
	</network>
	<executor-service>
		<pool-size>16</pool-size>
	</executor-service>
</hazelcast>
```

**Comment by weixliu** [comment]
I think you are right, I found that all the machine have same databases,

Document from Official:
Auto-Sharding is not supported in the common meaning of Distributed Hash Table (DHT). Selecting the right shard (cluster) is up to the application. This will be addressed by next releases

http://orientdb.com/docs/2.2.x/Distributed-Sharding.html

**Comment by youzp** [comment]
@weixliu thanks!

My application scene is a lot of write operations and a small amount of read operation, in this case, should be configured into a cluster inside a server?
for example?
"clustername_1": { "servers": ["serverA"] }, 
"clustername_2": { "servers": ["serverB"] },
"clustername_3": { "servers": ["serverC"] },
"clustername_4": { "servers": ["serverD"] }

**Comment by weixliu** [comment]
According to the #6497 I think it's OK, but the client should response for writing to the right cluster(shard).

I think they mean reading operation do not need connect to the right cluster, the ODB  is able to find the cluster have the right data.

**Comment by lvca** [comment]
@weixliu it's correct.
