### ISSUE TITLE
Migrate RID bag cache to OClosableLinkedContainer or similar tech

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6937]
RID bag cache is now a global instance under the hood, not per-database as before, as a result threads contention is potentially raised. OClosableLinkedContainer offers caching facilities with good multi-thread performance.

**Comment by lvca** [comment]
@taburet Milestone?

**Comment by taburet** [comment]
@lvca assigned 2.3

**Comment by laa** [comment]
Moved to 3.1 because it will require a lot of resources to implement but the outcome is questionable.
