### ISSUE TITLE
JOIN different edge fields in same row

### ISSUE THREAD

**Issue by DThink** [orientechnologies/orientdb#6939]
hi, i use orientDB 2.2.13 version and i not understand how to do a join different edge fields in one same row.
an example. i have a NewFollow edge with this fields

![cutmypic](https://cloud.githubusercontent.com/assets/18085313/20560772/5bf34948-b17b-11e6-9704-8cbed4b4cb88.png)

i try to use this code to make a join

```
SELECT $a as FromUser, $b as ToUser FROM NewFollow
let $a = (SELECT expand(out) FROM $current),
    $b = (SELECT expand(in) FROM $current)
```
but the result is this

![cutmypic 1](https://cloud.githubusercontent.com/assets/18085313/20560870/cf8ee182-b17b-11e6-9e74-d173de43edbc.png)

/---------------------------------------------------------------------------------

i try also with this code

```
SELECT expand($c) FROM NewFollow
let $a = (SELECT expand(out) FROM $current),
    $b = (SELECT expand(in) FROM $current),
    $c = UNIONALL($a, $b)
```

but the results are in different rows

![cutmypic 2](https://cloud.githubusercontent.com/assets/18085313/20561002/73fac470-b17c-11e6-9241-7a80e861a880.png)

/------------------------------------------------------------------------------------------------------

if i try to use different expand in same select i have a error

`SELECT expand(out), expand(in) FROM NewFollow`

**Projection not allowed with FLATTEN() and EXPAND() operators DB name="MyApp"**

//------------------------------------------------------------------------------------------------

yes  in this case i can add any fields one by one. but i not want use this method because i have other different edges with differents in and out fields and is important to can expand any result dynamically. how can i fix this problem?

**Comment by luigidellaquila** [comment]
Hi @DThink 

Try this:
```
select out.* as outPrefix_, in.* as inPrefix_ from NewFollow
```
I hope it helps

Thanks

Luigi

**Comment by DThink** [comment]
thanks, so simple :)
