### ISSUE TITLE
 How to set the specified cluster name for a class via native API

### ISSUE THREAD

**Issue by youzp** [orientechnologies/orientdb#6940]
## OrientDB Version, operating system, or hardware.
- v2.2.12

## Operating System
- [ *] Linux

## Expected behavior and actual behavior
A class with four clusters, I need to set the specified cluster name. Displays an error when the number of clusters is set to zero.
**com.orientechnologies.orient.core.exception.OSchemaException: Impossible to associate a cluster to an abstract class class**
```
OrientVertexType vertex = graph.createVertexType("TestVertex", 0);
vertex.addCluster("clustername_1");
vertex.addCluster("clustername_2");
vertex.addCluster("clustername_3");
vertex.addCluster("clustername_4");
```

When the number of clusters is set greater than 0, the cluster name is a combination of class name and number.How to set four specified cluster name for a class?

**Comment by tglman** [comment]
hi @youzp,

the erro say that you cannot associate a cluster to the class because is abstract, it means that you crelated the vertex class as abstract, and for be able to add clusters the class should not be abstract, as well the minimun cluster should be at least 1, here is a working example:
```
    graph.setAutoStartTx(false);
    OrientVertexType vertex = graph.createVertexType("TestVertex", 1);
    vertex.addCluster("clustername_1");
    vertex.addCluster("clustername_2");
    vertex.addCluster("clustername_3");
    vertex.addCluster("clustername_4");
```

Bye

**Comment by youzp** [comment]
hi， @tglman 
`OrientVertexType vertex = graph.createVertexType("TestVertex", 1);`
There will be a default cluster name “testvertex”
This will have 5 cluster names
“testvertex”、"clustername_1"、"clustername_2"、"clustername_3"、"clustername_4"
  ```
 vertex.addCluster("clustername_1");
 vertex.addCluster("clustername_2");
 vertex.addCluster("clustername_3");
 vertex.addCluster("clustername_4");
```

**Comment by tglman** [comment]
hi @youzp,

I see now your use case, you can drop the first created ridbag affter you added the others, i thin that is the cleanest way.

otherwise as workaround you can use the document api, Ex:
```
    OrientGraph grap = ...
    grap.setAutoStartTx(false);
    ODatabaseDocument rawDb = grap.getRawGraph();
    int clusters[] = new int[4];
    clusters[0] = rawDb.addCluster("clustername_1");
    clusters[1] = rawDb.addCluster("clustername_2");
    clusters[2] = rawDb.addCluster("clustername_3");
    clusters[3] = rawDb.addCluster("clustername_4");
    rawDb.getMetadata().getSchema().createClass("ClassName", clusters, rawDb.getMetadata().getSchema().getClass("V"));
```
