### ISSUE TITLE
query on Composite index using java api

### ISSUE THREAD

**Issue by BruceMu** [orientechnologies/orientdb#6941]
## OrientDB Version, operating system, or hardware.
Using OrientDB 2.1.12

## Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

I create a composite btree index like : 

``` java
final String srcInxName = edgeType.name() + "." + START_VERTEX_ID;
edgeClz.createIndex(srcInxName, OClass.INDEX_TYPE.NOTUNIQUE.toString(),
                    null, null, new String[]{START_VERTEX_ID, END_VERTEX_ID});
```

and insert three records,  then query like : 

```java
OIndex<?> index = getDocumentDataBase().getMetadata().getIndexManager()
                  .getIndex(type + "." + START_VERTEX_ID);
Object obj = index.get(new OCompositeKey(vertexId.getId()));
indexValue =  (Collection) obj;
Object result = getDocumentDataBase().command(
        new OSQLSynchQuery<>("SELECT FROM INDEX:" + type + "." + START_VERTEX_ID + " WHERE key = " + vertexId.getId()))
        .execute();
```

but the first query by java return one result; and the sql-like query return 2 results as expected.

what's the problem ?

**Comment by maggiolo00** [comment]
@BruceMu 

do you use remote connection?

**Comment by maggiolo00** [comment]
@BruceMu 

in case of Partial Composite match you should use this API

```JAVA
OCompositeKey iKey = new OCompositeKey(vertexId.getId());
OIndexCursor curstor = index.iterateEntriesBetween(iKey, true, iKey, true, true);
```

**Comment by BruceMu** [comment]
I use plocal orientdb.

**Comment by BruceMu** [comment]
So if I used sql-like query , it will call the 'iterateEntriesBetween(...)' method at last ?

**Comment by maggiolo00** [comment]
@BruceMu 
yes `iterateEntriesBetween` will be called

**Comment by maggiolo00** [comment]
@BruceMu 

did you try the api 

```
OIndexCursor curstor = index.iterateEntriesBetween(iKey, true, iKey, true, true);
```

Did that work for you?

Thanks

**Comment by BruceMu** [comment]
I used sql-like query in my application at last, thanks for you suggestion, I will try it later.
