### ISSUE TITLE
Can't parse valid JSON in SQL requests

### ISSUE THREAD

**Issue by haiflive** [orientechnologies/orientdb#6947]
## OrientDB Version, operating system, or hardware.
- [x] orientdb-enterprise-2.2.12

## Operating System
- [x] Linux (Ubuntu 14.04.3 LTS)

Tested in studio and PhpOrient

## Expected behavior and actual behavior
I try migrate data from mysql to orientdb and take some bugs parsing JSON in SQL commands.
I think that it's valid requests, but db can not parsing data.

### the first bug
```
INSERT INTO `DealComplex` (deals)
VALUES (
[{
"goods":[{
    "GoodsDescription":" \" coma-->,<-- coma  \" ",
"@class":"Goods","@type":"d"}
],
"@class":"Deal","@type":"d"}
]
)
```
only paste comma inside `\" \"`
db return error:

> Map found but entries are not defined as <key>:<value> DB name="dt"

### the second bug:
again comma, but some other behavior
```
INSERT INTO `DealComplex` (contract)
VALUES ({
    "ContractSubject":" \" \/ \u0443, ",
"@class":"Contract","@type":"d"}
)
```
add comma after this combination `\" \/`
strings variations: `\" \u0443 \/ \u0443,` `\u0443 \" \u0443 \/ \u0443,`

DB return error:

> com.orientechnologies.orient.core.exception.OCommandExecutionException: expression item 'у' cannot be resolved because current record is NULL DB name="dt"

### the third bug (or not)
MySQL store empty(not null) date in the follow format `0000-00-00`
and when execute sql
`INSERT INTO c_document (PI_RegID) VALUES ('0000-00-00')`
I took error that it's wrong format:

> Error on conversion of date '0000-00-00' using the format: yyyy-MM-dd DB name="dt"

I think that it's can be valid format.

**Comment by luigidellaquila** [comment]
Hi @haiflive 

I just pushed a fix on branch 2.2.x, the fix will be released with 2.2.14

About the third case, it's not properly an issue, it's just a different behavior of OrientDB compared to MySQL. If you want to pass null dates in OrientDB, you just have to pass `null`. If it's a recurring case, you can write a very simple js function to do the conversion.

Thanks

Luigi
