### ISSUE TITLE
Feature: OrientGraph that supports AutoCloseable

### ISSUE THREAD

**Issue by davidheryanto** [orientechnologies/orientdb#6949]
## OrientDB Version
- v2.2.x

If my understanding is correct, we should treat `OrientGraph` instance just like database connection instance right? i.e. when we want to do operations on the database we get a connection, then after we finish we should close the connection (to prevent memory leak and stale connection).

Currently for most JDBC connections I can use such pattern:
```java 
try (Connection connection = dataSource.getConnection) {
  // Do operation
} catch (Exception e) {
  // Handle exception
}
```
This will *automatically close* the connection once I finished with the operations.

I cannot do the same thing with OrientGraph because it does not implement `Closeable` or `AutoCloseable`. (I realize, however, `ODatabaseDocumentTx` does implement `AutoCloseable`).

Is it better if `OrientGraph` implements `AutoCloseable`, so client code can be cleaner (as opposed to using try...catch...finally) and graph connection can be closed more reliably?

**Comment by zella** [comment]
Same as #4833

**Comment by tglman** [comment]
Hi all,

We implement the tinkerpop api 2.x that not implement AutoCloseable, the new version of tinkerpop 3.x it include AutoCloseable, so from 3.0 we are going to support it.

Regards

**Comment by tglman** [comment]
Hi,

I confirm orientdb 3.0 support Thinkerpop 3.0, earlier versions not support it by specification, so we don't support it.

I'm going to close this

Kind Regards
