### ISSUE TITLE
Feature request: evaluate json in insert/update

### ISSUE THREAD

**Issue by vovagp** [orientechnologies/orientdb#6950]
Query 
```
update #rid content {"hello":"(select from className where condition)"}
```
fails with
```
Argument '(select from className where condition)' is not a RecordId in form of string
```
while SET (of course) working right. Maybe add to BNF parser option like CONTENTSET / MERGESET?

It may not be a popular feature :)

**Comment by luigidellaquila** [comment]
Hi @vovagp 

The correct syntax would be 

```
update #rid content {"hello":(select from className where condition)}
```

(without the quotes around the statement), but I'm afraid it won't work in 2.2.

In v 3.0 we are doing a lot of changes, and the query will be evaluated as a normal expression, so it will be supported

Thanks

Luigi

**Comment by lvca** [comment]
Already supported in 3.0-m2.
