### ISSUE TITLE
Feature request: Queries with timezone

### ISSUE THREAD

**Issue by Edelf** [orientechnologies/orientdb#6951]
It would be nice if orientDB could convert EPOCH to Dates based on an Timezone argument.

My scenario: 
I need to query orientDB to retrieve data aggregated by day. E.g.:

`
SELECT OCCURRENCE, COUNT(1) AS TOTAL FROM
(
    SELECT MY_DATE.asDate().format('yyyy-MM-dd').asDate().asLong() AS OCCURRENCE
    FROM MY_TABLE 
    WHERE MY_DATE >= ? AND MY_DATE <= ?
) 
GROUP BY OCCURRENCE
`

However I need to perform this aggregation based on my client timezone (web browser).

Ideally it would be something similar to this:

SELECT MY_DATE.asDate('Europe/London')

**Comment by Solido** [comment]
Completely in with java8 OffsetTime as return for Property
