### ISSUE TITLE
Edge endpoint types are not validated in upgraded database

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#6952]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .13[x] .12[x] .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

[EDIT] See below posts, I had a bug and this repro is incorrect.

OrientDB 2.1.16 (and perhaps some earlier and later versions) have a bug where edge endpoint types are not validated. For example:
```
create database plocal:/test_edge_schema <user> <password> plocal graph

create class Foo extends V
create class Bar extends V
create class Foo_Bar extends E
create property Foo_Bar.out Link Foo
create property Foo_Bar.in Link Bar

create vertex Foo set name = 'foo1'
create vertex Foo set name = 'foo2'
create vertex Bar set name = 'bar'

create edge Foo_Bar from (select from Foo where name = 'foo1') to (select from Bar)
// succeeds with no errors

create edge Foo_Bar from (select from Bar) to (select from Foo where name = 'foo2')
// also succeeds, even though the types are clearly not a match
```

Note that in the above example, the second created edge goes `Bar -> Foo`, even though the schema explicitly states that only `Foo -> Bar` directions are allowed, making this a bug. Even though this bug by itself appears to be fixed in OrientDB 2.2.12, upgrading from OrientDB 2.1.16 to OrientDB 2.2.12 causes the upgraded databases to still have this problem.

## Expected behavior and actual behavior
Expected:
- Upgrading a database from OrientDB 2.1.16 to OrientDB 2.2.12 should mean that the schema is properly checked when creating edges.
- OrientDB 2.2.12 should scan the database for schema inconsistencies and report any that are found. This could be done as part of startup, or as a separate tool.
- The OrientDB maintainers should note in a **highly visible location** that such a bug was found and fixed, and appropriate steps that users can take to ensure data integrity.

Actual:
None of the above three things appear to have happened.

## Steps to reproduce the problem
- Use the above script on OrientDB 2.1.16.
- Upgrade to OrientDB 2.2.12, preserving the original database files.
- Open the original database in OrientDB, and note that the illegal edge is still present, there are no warnings, and further illegal edges can still be created in violation of the schema.
- Furthermore, note that no highly visible warnings were issued to OrientDB users about this serious bug, and no steps to mitigate it were posted.

**Comment by obi1kenobi** [comment]
Furthermore, it appears that neither `BACKUP DATABASE / RESTORE DATABASE` nor `EXPORT DATABASE / IMPORT DATABASE` fix the problem -- the newly created database is always corrupted and allows creation of edges that violate the schema.

**Comment by obi1kenobi** [comment]
Apologies for the confusion -- this bug is still present, but the above code and setup does not reproduce it (I made a mistake in my setup). I am working to get a proper reproduction.

Notably, the bug definitely only happens when upgrading between different versions of OrientDB. I'm just not sure which versions cause the problem.

**Comment by obi1kenobi** [comment]
I am unfortunately unable to come up with a reproduction of the issue, and I am unable to share the exact database data we have, due to its proprietary nature. However, I did check that the schema data in `select * from #0:1` is identical between a database that exhibits this bug (and has been consistently upgraded from version to version starting with ~2.1.5) and a database that does not exhibit this bug.

**Comment by obi1kenobi** [comment]
Using OrientDB 2.2.13's source code, I stepped through the addition of the offending edge that was incorrectly passing validation, and discovered that OrientDB thinks that validation is disabled for the database: `isValidationEnabled()` returns `False`.

This is highly suspicious because of two reasons:
- This is not a configuration property that I or my company have ever changed, and the default (according to docs) is supposed to be `True`.
- [The docs](https://orientdb.com/docs/last/SQL-Alter-Database.html) say that this setting should not be persistent, and a server restart should set it back to the default `True`. However, in my case, server restarts do not do so, and validation remains disabled.

I am also unable to find a way to re-enable validation on our server, and would appreciate some help on that as well.

**Comment by obi1kenobi** [comment]
Furthermore, following the steps described [in the docs](http://orientdb.com/docs/last/Configuration.html#dbvalidation) to set the `db.validation` property to `true` in the config file had no effect.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

It's quite strange and probably hard to reproduce, but we'll try to find the reason.
In the meantime, you can force`db.validation=true` on the whole server, eg. in the config.xml:

```
<properties>
...
        <entry name="db.validation" value="true"/>
... 
```

Please let me know if it solves the problem

Thanks

Luigi

**Comment by obi1kenobi** [comment]
Hi @luigidellaquila, that is how I set `db.validation` as I mentioned in my last post, but it didn't change anything. However, `ALTER DATABASE validation true` seems to have helped for now, although it only addressed the symptom and not the underlying problem.
