### ISSUE TITLE
user password is not settable

### ISSUE THREAD

**Issue by DThink** [orientechnologies/orientdb#6955]
hi, i have a Ouser Class that is a extension of the OIdentity class and Vertex class. when i use this sql query to create a new user

`CREATE VERTEX OUser SET created=Date(), updated=Date(), email="francesco@gmail.com", name="francesco", password="9000000", status = "ACTIVE", roles = [#4:1]`

the result is this

```
{
    "result": [
        {
            "@type": "d",
            "@rid": "#5:17",
            "@version": 1,
            "@class": "OUser",
            "created": "2016-11-30 18:09:18",
            "updated": "2016-11-30 18:09:18",
            "email": "caterina@gmail.com",
            "name": "caterina",
            **"password"**: "{PBKDF2WithHmacSHA256}058FEE6A68571DD8956DE5D58B9A28A285C6A0294D6AC0C1:C6561C9CCAFBACE843649F682EBEE2141D90B4C872E9422D:65536",
            "status": "ACTIVE",
            "roles": [
                "#4:1"
            ],
            "@fieldTypes": "created=t,updated=t,roles=n"
        }
    ],
    "notification": "Query executed in 0.178 sec. Returned 1 record(s)"
}
```

is clared that the password is not mine but It was automatically setted. the problem persist also if i try to update the password, the operation succeed but again with random password. how can i solve this problem?
my orientDB version is 2.2.13 and i execute all operations with root user

**Comment by maggiolo00** [comment]
@DThink 
if you use the class OUser OrientDB automatically hash the password on create.
See here
http://orientdb.com/docs/2.2/Database-Security.html
and here
http://orientdb.com/docs/2.2/Database-Security.html#password-management

**Comment by DThink** [comment]
ok thanks
