### ISSUE TITLE
DROP CLASS IF EXISTS throws error on nonexistent class

### ISSUE THREAD

**Issue by maratius1** [orientechnologies/orientdb#6957]
## OrientDB Version, operating system, or hardware.
OrientDB Server v2.2.13 (build 2.2.x@r90d7caa1e4af3fad86594e592c64dc1202558ab1; 2016-11-15 12:04:05+0000)

## Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
_Expected:_ no action.
_Actual:_ error:
Error: java.lang.IllegalArgumentException: Class 'NonExistentClass' not found in database

## Steps to reproduce the problem
Try to DROP nonexistent class.

Command:
DROP CLASS NonExistentClass IF EXISTS

See issue #3597.

"CREATE CLASS ExistentClass IF NOT EXISTS" works as expected - does nothing and generates no error.

**Comment by luigidellaquila** [comment]
Hi @maratius1 

Thank you for reporting, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @maratius1 

I just checked it in v 2.2.14 from Studio and it seems to work fine. Probably it was fixed in latest release.

I'm closing this, please reopen if you still have a way to reproduce it.
