### ISSUE TITLE
St_intersect and similar function causing issue

### ISSUE THREAD

**Issue by rishi3195** [orientechnologies/orientdb#6966]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ Y] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows-yes
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behaviour
-Expected--True or False
Actual- Exception

## Steps to reproduce the problem
[Polygon_spatial_error.docx](https://github.com/orientechnologies/orientdb/files/630514/Polygon_spatial_error.docx)

**Comment by maggiolo00** [comment]
@rishi3195 

The link with the steps to reproduce the problem gives me 404.
Can you please update the issue?

Thanks

**Comment by rishi3195** [comment]
[PlatformDB_Spatial_issues.docx](https://github.com/orientechnologies/orientdb/files/630751/PlatformDB_Spatial_issues.docx)
Uploaded it again....

**Comment by maggiolo00** [comment]
hi @rishi3195 

what is Platform DB?

which version of ODB do you use 2.1.rc3?

**Comment by rishi3195** [comment]
Please ignore last doc and refer this one...
[Polygon_spatial_error.docx](https://github.com/orientechnologies/orientdb/files/630804/Polygon_spatial_error.docx)

**Comment by maggiolo00** [comment]
@rishi3195 

you should rewrite the query in this way

```SQL
select ST_Intersects($a[0],$b[0]) 
let a=(select expand(SHAPE) from PolygonWSG where @rid = '#417:0'), 
b=(select expand(SHAPE) from PolygonWSG where @rid = '#417:0')
```

**Comment by maggiolo00** [comment]
You should use let when you want to use a select as input parameter for a function

**Comment by rishi3195** [comment]
thanks.. this is working..
but I still couldn't get whats the error in the format I have used?

Moreover, its working in case of non -spatial data

**Comment by maggiolo00** [comment]
The parser complains because you cannot use directly sub select as input parameter
