### ISSUE TITLE
Lucene Spatial Index Studio UI Option

### ISSUE THREAD

**Issue by rishi3195** [orientechnologies/orientdb#6968]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[Yes ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows -Yes
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
1. Expected- Should be able to create Lucene Spatial Index. Actual- Error
2. Expected- In UI, Spatial Index should be an option, Actual - No Such option Avaliable
[spatial_index.docx](https://github.com/orientechnologies/orientdb/files/631005/spatial_index.docx)

**Comment by maggiolo00** [comment]
@rishi3195 

you have some problem with classpath. Please check your ODB dependencies

**Comment by rishi3195** [comment]
Can you please list the third party lib required?

I am using plug-in orientdb-spatial-2.2.0-dist.jar

**Comment by maggiolo00** [comment]
Which version of ODB?

**Comment by rishi3195** [comment]
2.2.0 snapshot

**Comment by maggiolo00** [comment]
Why do you use 2.2.0 snapshot?

Please try with OrientDB 2.2.13 

and the 2.2.13 Spatial plugin.

https://oss.sonatype.org/content/repositories/releases/com/orientechnologies/orientdb-spatial/2.2.13

**Comment by rishi3195** [comment]
is something is missing in 2.2.0 snapshot?

**Comment by maggiolo00** [comment]
@rishi3195 

i cannot say since the 2.2.0 snapshot has been in develop for quite a while 
 could be that some api are missing and are required for the Spatial Plugin

**Comment by rishi3195** [comment]
still option in UI is missing

**Comment by rishi3195** [comment]
@maggiolo00 
any updates?

**Comment by maggiolo00** [comment]
@rishi3195 

yes the option in the UI is missing because, the spatial index is optional and it's not released with OrientDB Distribution. I will mark this as enhancement 
and add the option if the module is installed.

Thanks
