### ISSUE TITLE
Schema default value does not create an attribute automatically, if null

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#6978]
## OrientDB Version, operating system, or hardware.
- v2.2.13

## Operating System
- Linux

Hi guys,

I think it's an arguable issue, but logically it seems that current schema behavior for`null` default values has a problem.

Consider the following:

```
create class Test extends V

create property Test.myString string
alter property Test.myString default null

create property Test.myDate datetime
alter property Test.myDate default null
```

Then run `insert into Test content {}`

From my perspective what should happen is:
1. A `Test` record is created
2. Attributes `myString` and `myDate` must be present, but set to `null` from the very beginning.

What actually happens: the attributes `myString` and `myDate` are not created. Is that an expected behavior?

Concrete example that causes an issue at this point:

I am using PhpOrient project. If I am referencing a record's attribute (e.g.  `$rec["myDate"]`) and that attribute does not exist, an error is thrown. So while from the schema point of view I am expecting to have an attribute created for me automatically, what happens instead is that I am still forced to check whether attribute exists first and only then I can use it. Other libraries and their users might be experiencing the same effect.

Please let me know what you think.

**Comment by lvca** [comment]
Setting the default value to NULL means to disable the default value. OrientDB doesn't support NULL as default value, sorry.

**Comment by andreyvk** [comment]
@lvca thanks for the explanation! I see now
