### ISSUE TITLE
Backup with non-tx operation could create an invalid copy of non indexed elements

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6979]
This could happen because the indexing is done at DB level, while the backup is at storage level. By testing in HA configuration, the backup could copy records before they are indexed, restoring the database on another server with broken indexes.

**Comment by taburet** [comment]
Fixed in 2.2.x and develop. Now freeze operations lock all keys of all indexes for reading as a first step, this prevents splitting of non-tx cluster updates with associated index updates.

**Comment by laa** [comment]
To fix this bug we need to extract index manager into database code. Because of big refactoring it is moved to 3.0 version

**Comment by taburet** [comment]
Created a separate feature issue #7239 with more details.

**Comment by taburet** [comment]
Micro-transactions merged into develop, backups and all the stuff involving storage freezing are "atomic" now.
