### ISSUE TITLE
Error on "delete batch 1000"

### ISSUE THREAD

**Issue by wq1101** [orientechnologies/orientdb#6985]
## OrientDB Version, operating system, or hardware.
- v2.2.13 SNAPSHOT[* ] 

## Operating System
- [ *] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Run "delete edge tb_edge1 where tag like '%thread-6%' batch 1000",  while responding as below:
2016-12-09 11:35:42:300 SEVER Internal server error:
Error parsing query:
select from tb_edge1 WHERE   tag LIKE '%thread-6%' BATCH 1000
                                                       ^
Encountered " <BATCH> "BATCH "" at line 1, column 52.
Was expecting one of:
    <EOF> 
    <AND> ...
    <OR> ...
    <ORDER> ...
    <GROUP> ...
    <LIMIT> ...

**Comment by smolinari** [comment]
BATCH isn't part of ODB's DELETE command. 

http://orientdb.com/docs/2.2.x/SQL-Delete.html

Scott

**Comment by wq1101** [comment]
http://orientdb.com/docs/2.2.x/SQL-Delete-Edge.html

**Comment by wq1101** [comment]
Run "delete edge tb_edge1 where tag like '%thread-6%' batch 1000"

Quote:
http://orientdb.com/docs/2.2.x/SQL-Delete-Edge.html

**Comment by smolinari** [comment]
Upps. I stand corrected. 

One would think the BATCH keyword would be available for all mutating queries. Hmm......

Scott

**Comment by luigidellaquila** [comment]
Hi @wq1101 

The SELECT statement does not support BATCH, you can use SKIP/LIMIT if you need pagination

Thanks

Luigi

**Comment by smolinari** [comment]
@luigidellaquila - the select seems to be part of the error message??? The command he is running is a "delete edge".

`delete edge tb_edge1 where tag like '%thread-6%' batch 1000`

I am now sort of confused too.

Scott

**Comment by luigidellaquila** [comment]
Ouch, sorry, I misunderstood it...

I think I got the problem, I'll work on it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
OK, fixed in branch 2.2.x, the fix will be released with 2.2.15

Thanks

Luigi
