### ISSUE TITLE
Schema-based default datetime value with sysdate() throws ClassCastException, if attribute is not specified explicitly

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#6988]
## OrientDB Version, operating system, or hardware.
- v2.2.13

## Operating System
- Linux

Hi,

Seems like there's a problem with setting a default date through the schema. Consider the following:

```
create class Test2 extends V

create property Test2.myUuid string
alter property Test2.myUuid default uuid()

create property Test2.myDate datetime
alter property Test2.myDate default sysdate()
```

Running `insert into Test2 content { }` will throw a `ClassCastException` (no idea why). However, `insert into Test2 content { "myDate": "2016-01-01" }` works very well.

This one might somehow also be related to issue #6978

**Comment by tglman** [comment]
hi @andreyvk,

I fixed this problem, be aware anyway that for generate the date on record creation you should alter the property in this way : `alter property Test2.myDate default "sysdate()"` otherwise the function is evaluated at the moment of the alter.

bye

**Comment by andreyvk** [comment]
@tglman, hi

I have a couple of questions, because it seems that I will need to redo a bunch of defaults on my schema now, and the schema is quite large.

1. While `sysdate()` requires double quotes to get executed properly, why doesnt `uuid()` require it? 
2. Also, should I get a habit of using double quotes for these function calls in schema at all times now? 
3. Is this double quote thing only 2.2.x specific or can I also apply it on 2.1.x? At the moment I am heavily testing Orient 2.2 so we can update our production (currently 2.1). If I do schema change now with double quotes everywhere, will it affect stuff on 2.1?

**Comment by tglman** [comment]
hi @andreyvk,

1) yes sorry any function if inserted without quote is run on alter time, so also uuid()
2) yes
3) with quote is portable betheen 2.2.x and 2.1.x

Bye
