### ISSUE TITLE
read timed out when i try to upload a file

### ISSUE THREAD

**Issue by DThink** [orientechnologies/orientdb#6989]
hi, when i try to upload a small image (png of 200kb) file in my database after 5-6 seconds i receive this error

**2016-12-09 18:07:08:410 SEVER Internal server error:
java.net.SocketTimeoutException: Read timed out [ONetworkProtocolHttpDb]**

by the client side i use this function to upload a image

```
var fd = new FormData();
fd.append("file", params.image);
    
 return $http({
       url: server + '/uploadSingleFile/' + database,
       method: 'POST',
       data: fd,
       timeout: 20000,
       headers: { 
            'Authorization': 'Basic ' + token,
             'Content-Type': undefined
       },
       transformRequest: angular.identity
 });
```

my orientDB version is the 2.2.13.
i see also that not exist a documentation regard the uploading of files. the binary data section explain only how to save a file after receiving it. for example i discover the uploadSingleFile function only in the orientdbstudio script file but i not see documentation regard this. 
i have also doubt regard the file uploading through the server side function. in my app I make extensive use of server functions and sometimes i must use certain of this function for create a objects with a binary data fields. thanks in advance

**Comment by lvca** [comment]
Sorry, but the OrientDB HTTP server doesn't support upload multi-part. Using Jetty as HTTP server is in our roadmap, but it's for v4.0 sorry.
