### ISSUE TITLE
Apache Commons Configuration error

### ISSUE THREAD

**Issue by vsspt** [orientechnologies/orientdb#6990]
## OrientDB Version, operating system, or hardware.
- v2.2.12, v2.2.13

## OrientDB JDBC driver 
- v2.2.12, v2.2.13

## Operating System
- [x ] Windows 8

## JVM
- 1.8.0_101-b13

## Frameworks/Libs
- Spring 4.3.2
- Apache Commons Configuration 1.10
- Spring Modules Jakarta Commons 0.8

## Expected behavior and actual behavior
Using OrientDB JDBC driver to connect to an Embedded OrientDB database that is used as a Database Properties using Apache Commons Configuration.

When using OrientDB v2.12/v2.13, the following error is raised:
```
Caused by: java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:464)
	at java.util.Properties.setProperty(Properties.java:166)
	at org.apache.commons.configuration.ConfigurationConverter.getProperties(ConfigurationConverter.java:116)
	at org.springmodules.commons.configuration.CommonsConfigurationFactoryBean.getObject(CommonsConfigurationFactoryBean.java:57)
```

## Steps to reproduce the problem
1. Create a Database Properties Configuration using Apache Commons Configuration 1.10

I've created a test project that can be used to verify the problem, it can be downloaded [here](https://meocloud.pt/link/16130de9-7ca5-4c3e-a7c6-1dd73e629e5a/OrientDB-v12_13_Bug.zip/).

In order to use it, the OrientDB PLocal path must be changed in the file: 
```
src\test\resources\testContext.xml
```

- Changing the OrientDB version on the maven pom.xml to version 2.2.11, the test is executed with success.
- Changing the OrientDB version to 2.2.12 or 2.2.13, the mentioned error is raised.

**Comment by robfrank** [comment]
Thank you very much for your very detailed  report! 

The temporary solution is to use an alias for the dstinct query:
```
 final StringBuilder query = new StringBuilder("SELECT DISTINCT(" + keyColumn + ") AS " + keyColumn + " FROM " + table);

```
We improved the way the JDBC driver maps documents retrieved from OrientDB, this is a regression error.

**Comment by vsspt** [comment]
Roberto,

Thank you very much for you quick response, the workaround works perfectly.

**Comment by robfrank** [comment]
Due to the way the Driver maps metadata, types and other infos from the list of documents returned by OrientDB, the right way is to always define aliases when aggregate functions or distinct clause are used. There's, at the moment, no other way to deal with it.
