### ISSUE TITLE
No active nodes found to execute command

### ISSUE THREAD

**Issue by wq1101** [orientechnologies/orientdb#6991]
## OrientDB Version, operating system, or hardware.
- v2.2.13 SNAPSHOT[*]

## Operating System
- [*] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Delete millions vertices, responding errors as :
com.orientechnologies.orient.server.distributed.ODistributedException: No active nodes found to execute command: sql.delete vertex tb_object_entity where db_cluster='1' [ONetworkProtocolHttpDb]

After web, console.sh, Java API(OrientGraph & OrientGraphNoTx) have recorded these errors, vertices had been deleted eventually. Any method to avoid this error exception and assure deletion accomplishing?

**Comment by lvca** [comment]
Fixed in v2.2.x.
