### ISSUE TITLE
Restart node does not work for EE

### ISSUE THREAD

**Issue by madama** [orientechnologies/orientdb#6995]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[x] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
From web console, if a node is restarted the status goes in "AGENT NOT FOUND", maybe it work only for CE and not for EE

## Steps to reproduce the problem
Click on restart node

**Comment by maggiolo00** [comment]
hi @madama 

the Restart it's only for EE. Does it work when the node goes online again?

**Comment by santo-it** [comment]
Hi @madama ,

Where do you click to restart the node?
Please could you test this with version 2.2.18?

Thanks,
