### ISSUE TITLE
OrientDB vanishes slashes from File Path

### ISSUE THREAD

**Issue by vsspt** [orientechnologies/orientdb#6996]
## OrientDB Version, operating system, or hardware.
v2.2.13

## Operating System
- [x ] Windows 8

## JVM
- 1.8.0_101-b13

## Frameworks/Libs
- Spring 4.3.2 

## Expected behavior and actual behavior
When inserting a file path on a OrientDB table, the file path is not stored correctly, as the slashes are being removed.

## Steps to reproduce the problem
This was verified on a Spring application, but can easily be reproduced with OrientDB studio, executing the following DDL / DML instructions:

1. CREATE CLASS V13_TEST
2. CREATE PROPERTY V13_TEST.FILE STRING
3. INSERT INTO V13_TEST(FILE) VALUES('C:\\\\DIR1\\\\DIR2')

Instead of storing the value 'C:\DIR1\DIR2', OrientDB is storing 'C:DIR1DIR2'.

**Comment by tglman** [comment]
hi @vsspt,

You should use escaping with double slashes :`INSERT INTO V13_TEST(FILE) VALUES('C:\\DIR1\\DIR2')`

Bye

**Comment by vsspt** [comment]
@tglman, it seems that github also needs escaping on slashes, as in the steps to reproduce the problem i included the double slashes, but github shows it as one (and looking at your response, i suppose you used double slashes, but only one is showing).

I've updated the steps to use quadruple slashes, so it shows double slashes, as i intended in the first place.

**Please execute the steps, using the correct double slashes, and you will verify the error i reported.**

**Comment by tglman** [comment]
hi @vsspt,

I just tried it and it insert the record correctly for me, are you sure that you don't have anything else that remove the double slashes, i'm running it from  firefox on linux, it may be that your browser is doing some additional escaping remove.

bye

**Comment by vsspt** [comment]
Hi @tglman,

I'm using IE 11.09.

Nevertheless, that's not the issue, as this is happening for me in a Spring application.
I just used the IE example, as i verified it had the same issue, and it was faster to use is a test.

I will create a simple test case demonstrating the error, it should be easier for you to use it in order to replicate the problem.

I will do it today, and provide a link for download as soon as its completed.

**Comment by vsspt** [comment]
@tglman , please donload this test project here: https://meocloud.pt/link/ff285b0d-add4-4690-9a59-d6bedf10cadf/2-2-13-Bug-2.zip/

In order to use the project, you will need to change the plocal url in the file: srt\test\testContext.xml.
In the POM file you can change the OrientDB JDBC driver version.

Basically, this is a simple Spring application that:

1. Updates a table field using "C:\\Folder1\\Folder2".
2. Retrieves the inserted value, and compares it with "C:\Folder1\Folder2"

**When using version <= 2.2.12**:

1. - Value is corrected inserted as "C:\Folder1\Folder2"
2. - The retrieved value is equal, so the test passes.

**When using version = 2.2.13**:

1. - Value is incorrectly inserted as "C:Folder1 older2"
2. - The retrieved value is not equal, so the test fails.

The test database details are:

- name = test
- user = admin
- password = admin

**Comment by tglman** [comment]
hi @vsspt,

I just tried your test with 2.2.14, and seems to work correctly, it may be that we had some regrassion that has bean already fixed, cna you try  2.2.14, it was released yesterday

Regards

**Comment by vsspt** [comment]
Works as expected, thank you.
