### ISSUE TITLE
If a Lucene index exists, Parser defaults to Lucene ---- even when the selected index is not Lucene

### ISSUE THREAD

**Issue by lasagnaman** [orientechnologies/orientdb#6997]
Except where specified, we are using com.tinkerpop.blueprints.impls.orient.OrientBaseGraph and associated APIs.
 
We have a vertex class called Foo, with a single property "value". We have two indexes called Foo.value, and Foo.value_fulltext_lucene. The first is an SBTREE UNIQUE index, and the latter is a LUCENE FULLTEXT index; both have the keyproperty "value". We make a call to OrientBaseGraph.getVertices(final String iKey, Object iValue), with parameters iKey = "Foo.value" and iValue = "blahblah / foobar". (This vertex exists in the DB and can be verified through OrientDB Studio.) The result is unexpected:
 
Exception in thread "main" com.orientechnologies.orient.core.index.OIndexEngineException: Error parsing lucene query
<…snip…>
Caused by: com.orientechnologies.orient.core.sql.parser.ParseException: Cannot parse 'blahblah / foobar': Lexical error at line 1, column 36.  Encountered: <EOF> after : "/ foobar"
 
It seems like the query value is being treated as a Lucene query, and the parser breaks down because the Lucene regex doesn't have a closing / character. If I properly escape the / character, then nothing "breaks", but it's still being parsed as a Lucene query and returns hundreds of records (instead of the single match). But I don't want to be using a Lucene query here! Any ideas? Is there maybe some setting for the "default index" or "default query parser" on the DB itself?
 
* If I query a Vertex class/index that does NOT have a Lucene index (e.g. has only the SBTREE UNIQUE index Bar.value) then the query works as expected. In this case, / is not treated as a special Lucene character, it returns a single vertex, etc.
* The same (broken) behavior happens if I use OrientBaseGraph.getVertices(final String label, final String[] iKey, Object[] iValue).

**Comment by luigidellaquila** [comment]
Hi @lasagnaman 

I just pushed a fix for this on 2.2.x branch. The fix will be released with 2.2.14

Thanks

Luigi
