### ISSUE TITLE
Lucene Spatial Index files not closed after database.drop() in 2.1.5 and 2.1.7 and 2.2.13

### ISSUE THREAD

**Issue by EricSchreiner** [orientechnologies/orientdb#6998]
## OrientDB Version, operating system, or hardware.
- v2.2.13
- v2.1.5 and v2.1.7 

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
see #5304 (problem still exists)
## Steps to reproduce the problem
it seems that the test only fails if you insert data and query the data (see below).
If you set INSERTCOUNT to 0 it will work
if you set INSERTCOUNT to 100 and remove the three lines for the select it will also work
```java
@Test
  public void testDeleteLuceneIndex1() {

    String dbName="plocal:./playground/db/db.2.2.13";

    int INSERTCOUNT=100; // @maggiolo00 set cont to 0 and the test will not fail anymore

    ODatabaseDocumentTx db = new ODatabaseDocumentTx(dbName);

    db.create();
    OClass test = db.getMetadata().getSchema().createClass("test");
    test.createProperty("name", OType.STRING);
    test.createProperty("latitude", OType.DOUBLE).setMandatory(false);
    test.createProperty("longitude", OType.DOUBLE).setMandatory(false);
    db.command(new OCommandSQL("create index test.name on test (name) FULLTEXT ENGINE LUCENE")).execute();
    db.command(new OCommandSQL("create index test.ll on test (latitude,longitude) SPATIAL ENGINE LUCENE")).execute();
    db.close();

    OPartitionedDatabasePool dbPool = new OPartitionedDatabasePool(dbName, "admin", "admin");

    db=dbPool.acquire();
    fillDb(db,INSERTCOUNT);
    db.close();

    db=dbPool.acquire();
    // @maggiolo00 Remove the next three lines and the test will not fail anymore
    OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>("select from test where [latitude,longitude] WITHIN [[50.0,8.0],[51.0,9.0]]");
    List<ODocument> result =db.command(query).execute();
    Assert.assertEquals(INSERTCOUNT, result.size());
    db.close();

    db=dbPool.acquire();
    db.drop();

    File dbFolder = new File("./playground/db/db.2.2.13");
    Assert.assertEquals(false, dbFolder.exists());

    File dbFolderRoot = new File("./playground/db");
    dbFolderRoot.delete();
    Assert.assertEquals(false, dbFolderRoot.exists());
  }


  private void fillDb(ODatabaseDocumentTx db, int count ) {
    for(int i=0;i<count;i++) {
      ODocument doc = new ODocument("test");
      doc.field("name", "Test"+i);
      doc.field("latitude", 50.0+(i*0.000001));
      doc.field("longitude", 8.0+(i*0.000001));
      db.save(doc);
    }
    OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>("select * from test");
    List<ODocument> result =db.command(query).execute();
    Assert.assertEquals(count, result.size()); 
  }
```

**Comment by robfrank** [comment]
The error on this test is to drop the database using a db instance from the pool. The pool keeps active connections to the db, so close the pool and instantiate a new db to drop it.

Take a look at the test now:
https://github.com/orientechnologies/orientdb-spatial/blob/2.2.x/src/test/java/com/orientechnologies/spatial/LuceneSpatialDropTest.java

Please run the test written in this way to confirm that now it works fine

**Comment by EricSchreiner** [comment]
@robfrank: Sorry but your test has a bug. dbName is not a valid Filename. If you change line 68 from
File dbFolder = new File(dbName);
to
File dbFolder = new File("./target/databases/LuceneSpatialDropTest");
Your Test will fail

**Comment by EricSchreiner** [comment]
Hi @robfrank any news on this (Please note that the problem seems to exist only under Windows)

**Comment by robfrank** [comment]
We are investigating. I'm working to setup  a windows VM to be more independent on tests.

**Comment by lvca** [comment]
@robfrank Any news on this?

**Comment by robfrank** [comment]
We were able to reproduce the problem, but unable to find a fix. The same test on Lucene (not spatial) index works fine. It seems related to how windows lock files and how we handle Lucene's IndexReader. It is very hard to find a solution at the moment
