### ISSUE TITLE
Nodes auto-removal from the cluster does not work for one case

### ISSUE THREAD

**Issue by pavlop-asg** [orientechnologies/orientdb#7000]
## OrientDB Version, operating system, or hardware.
v2.2.13

## Operating System
- Windows

## Expected behavior and actual behavior
Use case: We want to have only two nodes in a cluster and be able to handle fault tolerance (be able to read and write when one node is down) and have full consistency (write to all nodes). At this case, we can sacrifice the split brain syndrome. As I understand from the documentation I can use the following distributed configuration:
```json
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "all",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

Plus I need to specify the following OrientDB config property `distributed.autoRemoveOfflineServers=0`.

Issue: Elastic removal of the nodes from the cluster does not work all the time. 

## Steps to reproduce the problem
The use case: We have node A and B, we stop A and then B. If after we start only A - we will get an exception during any write operation that quorum is 2, but available only 1 node (which means that node B was not removed from the cluster). But when we start only node B - everything is OK, the cluster size is 1 and we can write.

**Comment by lvca** [comment]
This feature is fully supported with 2.2.x, not 2.1.x. Are there any reason why you cannot upgrade?

**Comment by pavlop-asg** [comment]
Sorry, there was a type, we use v2.2.13

**Comment by lvca** [comment]
@pavlop-asg fine. We already fixed this problem in last 2.2.x branch. Could you try it? By the way, now the `distributed.autoRemoveOfflineServers` setting is 0 by default.

**Comment by pavlop-asg** [comment]
I have tested it with the latest v2.2.13. 
BTW, without `istributed.autoRemoveOfflineServers=0` nodes do not get removed from the cluster, as I see from the source code it is still `-1`:
```java
DISTRIBUTED_AUTO_REMOVE_OFFLINE_SERVERS("distributed.autoRemoveOfflineServers",
      "This is the amount of time (in ms) the server has to be OFFLINE, before it is automatically removed from the distributed configuration. -1 = never, 0 = immediately, >0 the actual time to wait",
      Long.class, -1, true),
```

**Comment by pavlop-asg** [comment]
Is this issue going to be resolved in the next hotfix? Just want to clarify the expectation, because we have a release very soon and it is critical for us.

**Comment by lvca** [comment]
Hi @pavlop-asg we fixed this issue in 2.2.x branch. Any chance to test it? Tomorrow we will release it as 2.2.14 GA.

**Comment by pavlop-asg** [comment]
Thank you, I will test it tomorrow.

**Comment by pavlop-asg** [comment]
I have tested 2.2.14 version and the bug is still here.

**Comment by lvca** [comment]
Could you please post the new logs about all the servers?

**Comment by lvca** [comment]
Closed because no response.
