### ISSUE TITLE
"batch" can't be used as property name

### ISSUE THREAD

**Issue by tbertels** [orientechnologies/orientdb#7001]
## OrientDB Version, operating system, or hardware.
- 2.2.13

## Operating System
- [ ] Windows

## Expected behavior and actual behavior
Creating a boolean property named "batch".

Result:
`Error parsing query: CREATE PROPERTY Instance.batch BOOLEAN  Encountered " <BATCH> "batch "" at line 1, column 26. Was expecting one of: <TO> ... <VALUE> ... <VALUES> ... <SET> (...)`

## Steps to reproduce the problem
`CREATE PROPERTY Instance.batch BOOLEAN`

It doesn't work either with
`ALTER PROPERTY Instance.batchtemp NAME batch`:

`Error parsing query: alter property Instance.batchtemp name batch ^ Encountered " <ALTER> "alter "" at line 1, column 1. Was expecting one of: <SELECT> ... <TRAVERSE> ..`

**Comment by luigidellaquila** [comment]
Hi @tbertels 

I'll check it asap (I don't remember if it's explicitly defined as a reserved word or if it's just a bug).
In the meantime, as a work-around, you can just back-tick quote it:

```
CREATE PROPERTY Instance.`batch` BOOLEAN
```

Thanks

Luigi

**Comment by tbertels** [comment]
Thanks! It works great.

**Comment by tbertels** [comment]
Shouldn't it be added to the reserved words section of http://orientdb.com/docs/2.2/SQL-Syntax.html?

**Comment by lvca** [comment]
Absolutely. @luigidellaquila this is for you.

**Comment by luigidellaquila** [comment]
Docs fixed, they will be on-line in short

Thanks

Luigi
