### ISSUE TITLE
OrientDB looses data when we restart cluster after some nodes crashed v2.2.13

### ISSUE THREAD

**Issue by pavlop-asg** [orientechnologies/orientdb#7002]
## OrientDB Version, operating system, or hardware.
- v2.2.13

## Operating System
- Windows

## Expected behavior and actual behavior
There is an example. We have node A and B, we write a value "1" to a document when node A and B are up. We shut down node B and write value "2", after we shut down node A as well. When we start node B and after node A - cluster will have old value "1" instead of "2", looks like there is some bug when OrientDB merges the records. NOTE: when we start node A and after node B - everything works as expected.

## Steps to reproduce the problem
Start two nodes with the following distributed configuration:
```json
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": 1,
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "static",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

This issue is applicable for other configurations as well, for example:
- When we have 3 nodes and use write quorum "majority" and read quorum 1.
- When we have 3 nodes and use write and read quorum as "majority".
- When we have read quorum 1 and write quorum "all" plus "newNodeStrategy": "dynamic" and distributed.autoRemoveOfflineServers=0.

**Comment by lvca** [comment]
We introduced in v2.2.14 the information about last operation timestamp, so now this error should be fixed. Could you please confirm it?

**Comment by lvca** [comment]
Closed because no response.
