### ISSUE TITLE
OrientGraphFactory.close() does not completely close the storage

### ISSUE THREAD

**Issue by rohrl** [orientechnologies/orientdb#7008]
## OrientDB Version, operating system, or hardware.
- OrientDB 2.2.12

## Operating System
- any

## Actual behavior
We're accessing the graph database using single OrientGraphFactory and OrientGraph instances obtained from the factory. My understanding after reading the docs is that the factory is a heavy object and should be single per physical database. Therefore I'd assume that when done with the database, I call OrientGraphFactory.close() and the storage should be properly closed. However, it seems that Orient does not release all resources at this point, because db files remain blocked even after the call to close().

To work around it we had to forcefully close the storage using following code:
`Orient.instance()
              .getStorages()
              .stream()
              .filter(s -> !s.isClosed())
              .filter(s -> s.getURL().equals(url))
              .forEach(s -> {
                  log.info("Forcefully closing Orient storage: " + s.getURL());
                  s.close(true, false);
              });`
which ensures all file handles are released.

So it seems like Orient is internally managing the storages independently of calls to OrientGraphFactory.close() and delays releasing all resources until Orient.instance().shutdown().

## Steps to reproduce the problem
Open any local database using OrientGraphFactory, then close the factory, then try to remove the database files from filesystem before global Orient instance is shutdown.

## Expected behavior
Wouldn't it be simpler if the storage was fully closed at OrientGraphFactory.close(). This would also require OrientGraphFactory class to make sure there's never more than one instance of it per physical database (so they don't close each others storage), which makes perfect sense.
It would be good to enforce this pattern of usage instead of managing the storages behind the scenes.

**Comment by tglman** [comment]
hi @rohrl,

This is a know issue of the current internal architecture of 2.x, we already reviewed the architecture in 3.0 and resolved all this cases, to ensure that all storage are close in 2.x  you need to call `Orient.instance().shutdown()`.

Hope this help

**Comment by rohrl** [comment]
Can you provide some updated estimate on the release date of 3.0 ?
On the roadmap it's already overdue

**Comment by lvca** [comment]
I've just update the roadmap: https://github.com/orientechnologies/orientdb-docs/blob/2.2.x/Roadmap.md
