### ISSUE TITLE
Feature Request: Update schema-less class with properties

### ISSUE THREAD

**Issue by kaYcee** [orientechnologies/orientdb#7009]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[X ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
During our prototyping phase we used schema-less classes to quickly collect data. Now we would like to apply a schema on a particular class with millions of collected records. Unfortunately, the database would not allow that. Our current workaround is to use a swap-mechanism by using a new property, copying the values over to it, getting rid of the old one and renaming the new property to the old name. This is very time consuming. I understand that there might be records with a wrong property type - in which case the database should deny the property creation. But otherwise, it should be possible. Is there a better way right now to achieve this?

**Comment by smolinari** [comment]
@kaYcee - did you find a solution?

Scott

**Comment by kaYcee** [comment]
@smolinari Yes by using the schema manager in OrientDB Studio (Schema -> class -> Properties). There you can apply a schema later on as long as the data stored in the class fulfills the schema requirements (ie. correct data type stored already). Otherwise it will ask you to fix it manually before applying the schema definition

**Comment by smolinari** [comment]
Ah. Ok. Thanks for the reply and solution.

Scott
