### ISSUE TITLE
IndexManager is not properly synchronized

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#7010]
The `OIndexManagerShared` is not properly synchronized. During some of the distributed tests, if a thread is executing the following code, some of the record is not indexed. Why?:

```
database.reload();
```

Because it closes the index manager and reload all the index but many methods don't acquire a lock to access to the index list. So can happen that the index manager is reloading while the trigger is looking for an index and it can't find it. For this reason some of the records are not indexed. 

The solution is to provide an immutable version of index manager and set it with a CAS, like we do with the schema.

**Comment by tglman** [comment]
hi @lvca,

As far as I remember you fixed something similar not long time ago, is it that right ?

Regards
