### ISSUE TITLE
Embedded graph: java.lang.OutOfMemoryError: Direct buffer memory - right way to hack?

### ISSUE THREAD

**Issue by giulio-quaresima** [orientechnologies/orientdb#7012]
## OrientDB Version
- [x] 2.2.12 embedded

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Java Version
- [x] 8.x

## Expected behavior and actual behavior
I use an embedded version of OrientDB, using `new OrientGraphFactory("plocal:" + physicalPath);`. The embedding application is a webapp, a WAR which I deploy in a running Tomcat. 
The `OrientGraphFactory` is managed by a Spring bean which has a `destroy()` method (called during the undeploy phase) with the following body:

```
...
orientGraphFactory.close();
Orient.instance().shutdown();
...
```

if I redeploy the webapp, overwriting the WAR, I get the following error:

```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:693)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:342)
	at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:262)
...

```

To avoid this error, I added the following "hack" to the destroy method:

```
orientGraphFactory.close();
OByteBufferPool oByteBufferPool = OByteBufferPool.instance();
Orient.instance().shutdown();
Field poolField = OByteBufferPool.class.getDeclaredField("pool");
poolField.setAccessible(true);
@SuppressWarnings("unchecked")
ConcurrentLinkedQueue<ByteBuffer> pool = (ConcurrentLinkedQueue<ByteBuffer>) poolField.get(oByteBufferPool);
for (ByteBuffer byteBuffer : pool)
{
	try
	{
		if (byteBuffer.isDirect())
		{
			if (byteBuffer instanceof DirectBuffer)
			{
				DirectBuffer directBuffer = (DirectBuffer) byteBuffer;
				Cleaner cleaner = discover(directBuffer, 16);
				if (cleaner != null)
				{
					logger.info("Invoking Cleaner.clean()... ");
					cleaner.clean();
					logger.info("done!");
				}
				else
				{
					logger.warn("Cleaner is null!");
				}
			}
			else
			{
				logger.warn("Not an instance of DirectBuffer");
			}
		}
		else
		{
			logger.warn("No direct buffer");
		}
	}
	catch (Exception e)
	{
		logger.error(e.getMessage(), e);
	}
}

...

Cleaner discover(DirectBuffer directBuffer, int maxDepth)
	{
		if (maxDepth > 0)
		{
			Cleaner cleaner = directBuffer.cleaner();
			if (cleaner == null)
			{
				Object attachment = directBuffer.attachment();
				if (attachment instanceof DirectBuffer)
				{
					cleaner = discover((DirectBuffer) attachment, maxDepth - 1);
				}
			}
			return cleaner;
		}
		return null;
	}

```

Using this trick, I am able to redeploy the webapp without incurring on the OOME, but I wonder if this "solution" is correct or if it can be dangerous in some respect.
Thank you.
Giulio

**Comment by laa** [comment]
HI @giulio-quaresima ,
Did you try just to call shutdown ?

**Comment by giulio-quaresima** [comment]
Yes, as you can read from the provided code, I tried to call only Orient.instance().shutdown(); but I get `java.lang.OutOfMemoryError: Direct buffer memory` at the first redeploy of the war. Instead, with the "hack" I can redeploy several tmes without incurring in any problem.

**Comment by robfrank** [comment]
As redeploy of war do you mean an hot deploy of the new war?  For the sake of the issue,  could you try a cold redeploy,  switching off tomcat and restart it?

**Comment by giulio-quaresima** [comment]
Yes, I mean a hot deploy, i.e. copying the new war in the /webapp dir (Tomcat Host is configured with `autoDeploy="true"`). And yes, I tried the cold redeploy, and it works (obviously: when you stop & start Tomcat the VM also is restarted). The problem occurs when the webapp is reloaded but the Java VM remains alive.
 
I have to state that I work with a Tomcat instance which I don't have control on, so I can't add the recommended `-XX:MaxDirectMemorySize=512g`, nor I can restart Tomcat at will. So my problem is to have my webapp redeployable without incurring in the leak, and I wonder if my hack is correct or it can determine problems such as data corruption and/or data loss: my data are by no means "big", the whole graph consist in a few thousands of vertices and edges.

**Comment by robfrank** [comment]
Ok, I don't know a lot about the internals of the direct buffer, but IMHO the hot redeploy of a WAR on tomcat (on servlet container in general) is a bad practice to be avoided. On JVM prior to 1.8 it will exhaust the permSpace after a couple of deploys, and on JVM after 1.8, where there isn't a  permeSpace I don't know which kind of dragons an hot deploy can wake up. 
My 2cents.

**Comment by giulio-quaresima** [comment]
Thank you, I already know the problems with redeploy and PermGen leaks, I already stated that I have not direct control on the Tomcat instance, so I am forced to redeploy, and I asked a different question to anyone who knows "a lot about the internals of the direct buffer".

**Comment by taburet** [comment]
Hi @giulio-quaresima, please try to add manual `Orient.instance().closeAllStorages()` call to `destroy()` method.

**Comment by giulio-quaresima** [comment]
I tried. Same exception:
```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:693)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:342)
```

**Comment by taburet** [comment]
Sorry, got the problem, figuring how to fix it.

**Comment by taburet** [comment]
BTW, your solution is partially correct. If the code from the old WAR will never be executed, everything will be fine. If there is some kind of a WAR restart possible (not familiar with WAR tech), OrientDB byte buffer pool will be screwed up.

**Comment by taburet** [comment]
There is a cleaner solution. You may move the OrientDB jars out of the WAR to the Tomcat libs, so it will be shared across WAR boundaries, but this requires the control over the Tomcat instance which you probably don't have.

**Comment by giulio-quaresima** [comment]
I may have the chance to add all my dependencies in the common class loader, and I can try in the local dev env for sure, but as my experience, sharing the libraries across contexts can cause classloading conflicts and is a secure cause of other memory leaks.

**Comment by taburet** [comment]
@giulio-quaresima just pushed the fix to 2.2.x branch, it will be included in 2.2.14 release. If you can't wait, build the distribution from the source code and test is it really works for you. Just call the `Orient.instance().shutdown()` from `destroy`.

**Comment by giulio-quaresima** [comment]
Very thank you, I will wait for the 2.2.14 release to be available as Maven dependency, then I'll try it immediatily.

**Comment by taburet** [comment]
@giulio-quaresima 2.2.14 released today, please update and verify.

**Comment by giulio-quaresima** [comment]
Now it works perfectly, I redeployed 5 times without any error. Great job!
