### ISSUE TITLE
Inserting a vertex or an edge with a property of type double by using SET doesn't work

### ISSUE THREAD

**Issue by tbertels** [orientechnologies/orientdb#7013]
## OrientDB Version, operating system, or hardware.
v. 2.2.13

## Operating System
- [ ] Windows

## Expected behavior and actual behavior
Error:
`java.lang.IllegalArgumentException: Property value can not be null`

## Steps to reproduce the problem
`CREATE EDGE E FROM #21:20 TO #21:22 SET factor = 1e-06`
Error:
`java.lang.IllegalArgumentException: Property value can not be null`

`CREATE VERTEX V SET factor = 1e-06`
-> factor has no value

With the json syntax, it works:
```
CREATE VERTEX V CONTENT { "factor" : 1E-06 }
CREATE EDGE E FROM #21:20 TO #21:22  CONTENT {  "factor" : 1E-06 }
```

Note that this means that [OrientDB-NET.binary](https://github.com/orientechnologies/OrientDB-NET.binary) doesn't work either since it doesn't use the json syntax.

**Comment by luigidellaquila** [comment]
Hi @tbertels 

Fixed in branch 2.2.x, the fix will be released with 2.2.15.

It was a general problem related to parsing of numbers in scientific notation, not limited to CREATE EDGE

Thanks

Luigi
