### ISSUE TITLE
It's imposible to create a new record with the `BINARY` property

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb#7017]
## OrientDB Version, operating system, or hardware.
- v2.2.13

## Operating System
- [X] Linux

## Expected behavior and actual behavior
It's literally impossible to create a new record which contains a `BINARY` property. When I try to create a new record through OrientStudio I see the following message in the OrientDB log:
```
2016-12-17 22:40:22:806 SEVER Internal server error:
com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content for record: "@class":"FileHolder","@version":0,"@rid":"#-1:-1","file":null,"{{ header  }}":"$file"
	DB name="test"
--> java.lang.IllegalArgumentException: Invalid field name '{{ header  }}'. Character ' ' is invalid [ONetworkProtocolHttpDb]
2016-12-17 22:40:32:416 SEVER Internal server error:
java.net.SocketTimeoutException: Read timed out [ONetworkProtocolHttpDb]
```

## Steps to reproduce the problem
1. Create a new class
2. Create a property and choose the type `BINARY`
3. Add a new record and don't forget to specify the file for the created earlier property

This [ticket](https://github.com/orientechnologies/orientdb/issues/6989) is probably related.

**Comment by maggiolo00** [comment]
hi @maseev 

yes it's related and it's an old HTTP issue of ODB, that does not support well Multipart Request

**Comment by maggiolo00** [comment]
@maseev 

i'm going to remove the upload form since it will not be supported soon. We have in our Roadmap the replacement of the HTTP server.

**Comment by maseev** [comment]
@maggiolo00 OK.

**Comment by maggiolo00** [comment]
@maseev 
I will close this since it's duplicate 

Thanks
