### ISSUE TITLE
I coundn't use ORDER BY in MATCH sentence.

### ISSUE THREAD

**Issue by areumchoi** [orientechnologies/orientdb#7021]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [v ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
In SELECT sentence, I can use ORDER BY, but I can't use ORDER BY in MATCH sentence.
Isn't Match sentence equal with Select?

**Comment by luigidellaquila** [comment]
Hi @areumchoi 

Currently the MATCH syntax does not include the ORDER BY operator (we will add it in 3.0.x), but you can work around it with an outer SELECT:
```
SELECT FROM (
   MATCH ... RETURN ...
) ORDER BY foo, bar
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @areumchoi 

I just pushed a fix for this on develop branch. This will be officially released with v 3.0 M2

Thanks

Luigi
