### ISSUE TITLE
Spatial POJO Binding

### ISSUE THREAD

**Issue by rishi3195** [orientechnologies/orientdb#7023]
What should be data type for Spatial type column in POJO Binding class?
Please share with a sample POJO bound with spatial column bound with Orient class
V2.2
@maggiolo00.. can you please respond

**Comment by maggiolo00** [comment]
Hi @rishi3195 

Do you mean Binding with Object API?

**Comment by rishi3195** [comment]
No.. not Object API..but Document API

**Comment by maggiolo00** [comment]
In the Document API the spatial type is treated as Embedded Document.
So it is a ODocument type 
see here
https://github.com/orientechnologies/orientdb/issues/7026

**Comment by rishi3195** [comment]
@maggiolo00 
I was looking for POJO class specification

e.g

public class City{
String name;
//how to define location for OPoint,OLineString,OPolygon
Embedded location;
//also pls share sample getter and setter 


}
