### ISSUE TITLE
security,  authorize only the use of functions

### ISSUE THREAD

**Issue by DThink** [orientechnologies/orientdb#7028]
hi, i want authorize my users to use only a server side javascript function but when i try to call a function i received constantly the 401 unauthorized message. i can connect with success a user but i cant call the functions. My security permissions is this

![permissions](https://cloud.githubusercontent.com/assets/18085313/21355855/e7191520-c6cf-11e6-82a7-0c6ec2ff8b64.jpg)

my goal is that any user can communicate with my database only through the server functions. how do I do this without an error?

**Comment by lvca** [comment]
What are doing the functions? If a function interacts with the database, they you need more privileges.

**Comment by lvca** [comment]
No answer, closing it.
