### ISSUE TITLE
IMPORT DATABASE  -format=graphson decode slashes in edge labels

### ISSUE THREAD

**Issue by kuzeko** [orientechnologies/orientdb#7029]
## OrientDB Version, operating system, or hardware.
- [x] v2.2.13  

## Operating System
- [x] Linux
- [x] MacOSX

### Actual
When loading edges with slashes those are stored ``urlencoded``.
When retrieving them they are still encoded.
Inserting an edge with label `type/something` is stored as 'type%2Fsomething'
and when searching for it by equality on the edge label, no edge is retrieved. 

### Expected
Slashes should be stored as is and not  ``urlencoded``.

## Steps to reproduce the problem

`IMPORT DATABASE data.json -format=graphson ;`

[data.json.txt](https://github.com/orientechnologies/orientdb/files/664365/data.json.txt)

**NOTE:** this is a followup to  https://github.com/orientechnologies/orientdb/issues/6577

**Comment by lvca** [comment]
Closing this because the issue #6577 is still open and this is now a duplicate.
