### ISSUE TITLE
UPDATE from SELECT using LET does not work

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7031]
## OrientDB Version, operating system, or hardware.
- v2.2.14-SNAPSHOT-20161118.121331-4

## Operating System
- [X] Linux

## Expected behavior and actual behavior
Trying to port this traditional SQL statement to OrientDB:
```
UPDATE myTable SET mycolumnX = mycolumnX + 1 WHERE mycolumnY = 'abc' AND mycolumnZ = 'def'
```
This exact SQL statement gives failure "invalid keyword +" , very likely referring to "mycolumnX = mycolumnX + 1"

Searched the web, found a tiny bit of references to the LET command in ODB, and attempted to use this inside a transaction:
```
UPDATE myTable  SET mycolumnX  = $oldvalue[0].mycolumnX  WHERE mycolumnY = 'abc' AND mycolumnZ = 'def' let oldvalue = (SELECT mycolumnX  + 1 AS mycolumnX  FROM myTable   WHERE mycolumnY = 'abc' AND mycolumnZ = 'def' )
```

Sending this as the following JSON string:
```
{ "transaction": true, "operations": [ {"type": "script", "language": "sql", "script": "UPDATE myTable  SET mycolumnX   = $oldvalue[0].mycolumnX   WHERE mycolumnY = 'abc' AND mycolumnZ = 'def' let oldvalue = (SELECT mycolumnX   + 1 AS mycolumnX   FROM myTable  WHERE mycolumnY = 'abc' AND mycolumnZ = 'def' )" } ] }
```

but this fails also with
```
Invalid script:Encountered " <UPDATE> "UPDATE "" at line 1, column 1. Was expecting one of:  <IF> ...  ";" ...   <IF> ...  
```

Please guide me how this update can be achieved in ODB.

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I'm afraid it's not supported in current 2.2.x
The only way you have to achieve this is using a batch script, eg.

```
let oldvalue = (SELECT mycolumnX  + 1 AS mycolumnX  FROM myTable   WHERE mycolumnY = 'abc' AND mycolumnZ = 'def' );
UPDATE myTable  SET mycolumnX  = $oldvalue[0].mycolumnX  WHERE mycolumnY = 'abc' AND mycolumnZ = 'def';
```

**Comment by rdelangh** [comment]
@luigidellaquila 
hi Luigi, coming back on this question: your suggestion seems costly for the database, because you require it to perform twice the lookup of the record with the same WHERE clause: first time to get the old values of its properties, then again to update that same record with new values for its properties.

Please refer to my new issue #7142 where I try to store the @rid of the record from the first query, to use this rid to in the UPDATE statement.
