### ISSUE TITLE
NPE if OFunction name is empty

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7033]
## OrientDB Version, operating system, or hardware.

- v2.1.19
- v2.2 - only sources checked - issue exists

## Expected behavior and actual behavior

OFunction.name property defined without "notNull" flag:
https://github.com/orientechnologies/orientdb/blob/862dd179ca269d1f9207e2d401f825dd56682c28/core/src/main/java/com/orientechnologies/orient/core/metadata/function/OFunctionLibraryImpl.java#L121-L127

But that throws NullPointerException here if for some reason user didn't specify name.
https://github.com/orientechnologies/orientdb/blob/862dd179ca269d1f9207e2d401f825dd56682c28/core/src/main/java/com/orientechnologies/orient/core/metadata/function/OFunctionLibraryImpl.java#L80

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I just canged it and added a constraint for that

Thanks

Luigi
