### ISSUE TITLE
java.lang.IllegalArgumentException: Vertex id can not be null

### ISSUE THREAD

**Issue by thirawato** [orientechnologies/orientdb#7039]
## OrientDB Version, operating system, or hardware.
- v2.2.13
## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
In version 2.2.0 and older, I can query for edge in Graph Editor. The Graph Editor can shows the edge with its in & out vertices. After upgrade to version 2.2.13, the Graph Editor pops up the error, java.lang.IllegalArgumentException: Vertex id can not be null and does not show anything on panel.
## Steps to reproduce the problem
To execute `SELECT FROM E`

**Comment by thirawato** [comment]
2.2.14 has the same problem.

**Comment by maggiolo00** [comment]
hi @thirawato 

do you have a dataset to reproduce the problem?

**Comment by thirawato** [comment]
hi @maggiolo00 

I have sent you the data.

**Comment by maggiolo00** [comment]
hi @thirawato 

in your dataset  the edge with recorid #22:0 has no in/out property. That is why you get
`Vertex id can not be null``
How did you create that edge?

**Comment by maggiolo00** [comment]
I've removed that record and i do not get the exception anymore, but still i'm not able to see the result. I will provide a fix for this.

Thanks

**Comment by thirawato** [comment]
Hi @maggiolo00 

I don't know what I did on record id #22:0.

However I can simulate the case with below script.
create edge gw_test from #12:2 to #12:4 set scope='test'
update gw_test remove in
update gw_test remove out

**Comment by maggiolo00** [comment]
Ok you shouldn't do that. You are removing the connection with vertex in/out

**Comment by maggiolo00** [comment]
Btw i've fixed the visualization issue.
Thanks for reporting
