### ISSUE TITLE
Support tags on edges

### ISSUE THREAD

**Issue by aoighost** [orientechnologies/orientdb#7040]
Tags on edges would come in useful, especially in situations where you have an increment of the number of times something has been called you want to relate between two objects. An example of a database that already has this is GCHQ's Gaffer, and it would be useful in OrientDB as well.

**Comment by santo-it** [comment]
Hi @aoighost,

Many thanks for opening this issue. I'm not sure I understand exactly what you are asking. Please could you describe with more details what you mean for "tags", and how would you use them?

So in OrientDB right now Edges can have a Class, so you can aggregate similar "types" of relationships into a specific Class, and properties

I have tried to check this page http://gchq.github.io/Gaffer/uk/gov/gchq/gaffer/data/element/Edge.html but I couldn't find anything about tags. Perhaps you have a link where I can read more?

Thanks!

**Comment by santo-it** [comment]
Hi @aoighost,

Thanks again for opening this issue. Just a quick followup to ask if you had a chance to read my last message

Thanks,

**Comment by santo-it** [comment]
Closing due to lack of feedback. Please reopen in case. Thanks
