### ISSUE TITLE
sun.nio.ch import in artifact orientdb-core

### ISSUE THREAD

**Issue by sakno** [orientechnologies/orientdb#7042]
Hi! I'm using Apache Karaf 4.x as OSGi container with embedded OrientDB. After upgrading from _2.2.13_ to _2.2.14_ now I have the classloader issue associated with package `sun.nio.ch`. This package is declared in `Import-Package` section inside of artifact `orientdb-core-2.2.14` as non-optional. Artifact `orientdb-core-2.2.13` doesn't have this declaration. 

Upgrading was important for me due to issue #4439. Of course, I can solve classloading issue using `bootdelegation` concept of Karaf/Felix but this makes my solution unportable to non-Oracle JVM like IBM J9.

Here is the commit 056b4bc30abe1a48b6e1a5f518b7652fbb984c4c with the import of `sun.nio.ch` package.

**Comment by taburet** [comment]
Hi @sakno, I will mark the import as optional.

**Comment by taburet** [comment]
Marked as optional in 2.2.x and develop branches. Please use boot delegation or build from 2.2.x sources as a temporary workaround until 2.2.15 will be released.

**Comment by sakno** [comment]
Thanks for information. I'm worried about potential NoClassDefFoundError when running on JVM from other vendors. Will it work when `sun.nio.ch` not presented in class loader?

**Comment by taburet** [comment]
All accesses to `sun.nio.ch` are guarded by a silencing try-catch, so there shouldn't be any problems. 2.2.x successfully builds on IBM JDK and passes the tests on IBM JVM on our CI server.

**Comment by laa** [comment]
@sakno could you confirm ?

**Comment by sakno** [comment]
Confirmed
