### ISSUE TITLE
TRAVERSE command diffrent result between MAXDEPTH 1 and  $depth <= 1

### ISSUE THREAD

**Issue by cuijinyi** [orientechnologies/orientdb#7043]
## OrientDB Version, operating system, or hardware.
- v2.2 enterprise trial

## Operating System
- [ ] Windows

## Expected behavior and actual behavior
Schema 
Telephones -> Call -> Telephones
     [V]               [E]         SAME [V]

orientdb {db=Tele}>EXPLAIN TRAVERSE both("Call") FROM #24:198467  MAXDEPTH 1 LIMIT 5000;

Profiled command '{path:,stack:[0],depth:0,elapsed:20.131079,resultType:collection,resultSize:724}' in 1.553000 sec(s):
{"@type":"d","@version":0,"path":"","stack":[],"depth":0,"elapsed":20.131079,"resultType":"collection","resultSize":724,"@fieldTypes":"stack=u,elapsed=f"}

orientdb {db=Tele}> EXPLAIN TRAVERSE both("Call") FROM #24:198467  WHILE $depth <= 1 LIMIT 5000;

Profiled command '{path:,stack:[0],depth:0,elapsed:31.49982,resultType:collection,resultSize:2}' in 0.032000 sec(s):
{"@type":"d","@version":0,"path":"","stack":[],"depth":0,"elapsed":31.49982,"resultType":"collection","resultSize":2,"@fieldTypes":"stack=u,elapsed=f"}

I think it's the same result, but return diffrent record count

And this command raise error

orientdb {db=Tele}> TRAVERSE both("Call") FROM #24:198467 MAXDEPTH 2  WHILE $depth <= 3 LIMIT 5000;

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command: Found unexpected keyword 'WHILE' while it was expected '[LIMIT, SKIP, OFFSET, TIMEOUT, MAXDEPTH, STRATEGY]'. Use TRAVERSE <field>* FROM <target> [MAXDEPTH <max-depth>] [WHILE <condition>] [STRATEGY <strategy>]
Command: TRAVERSE both("Call") FROM #24:198467 MAXDEPTH 2 WHILE $depth <= 3  LIMIT 5000

In the docs 2.2.x
TRAVERSE <[class.]field>|*|any()|all()
         [FROM <target>]
         [MAXDEPTH <number>]
         WHILE <condition>
         [LIMIT <max-records>]
         [STRATEGY <strategy>]

**Comment by luigidellaquila** [comment]
Hi @cuijinyi 

The difference between `WHILE` and `MAXDEPTH` is that the first one has to evaluate also the step N+1 (in your case the condition is simple, but in other cases, with complex conditions, the only way to proceed is to reach step N+1 and check that it evaluates to false), while the second one reliably stops at level N, so the second one gives better performance.
In general, if you can, I suggest to use MAXDEPTH.

For the last error, the docs are wrong, you cannot mix both MAXDEPTH and WHILE condition, I'm fixing them

Thanks

Luigi

**Comment by lvca** [comment]
@luigidellaquila since it's not the first time users ask this question, could you please update the docs with that? Thanks.

**Comment by luigidellaquila** [comment]
good point @lvca , doing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Done!

**Comment by cuijinyi** [comment]
As you say, even WHILE evaluate also the step N+1, MAXDEPTH  reliably stops at level N, the result of MAXDEPTH 2 and WHILE $depth<=2 should be same. but the result is NOT the same, why?

**Comment by luigidellaquila** [comment]
uhm, I see... it seems the MAXDEPTH does not remove duplicates from the result-set.
It seems to be a bug, I'm checking it

Thanks

Luigi
