### ISSUE TITLE
Class exists but can't display by INFO CLASS

### ISSUE THREAD

**Issue by cuijinyi** [orientechnologies/orientdb#7044]
## OrientDB Version, operating system, or hardware.
- v2.2 Enterprise trial

## Operating System
- [x] Windows

## Expected behavior and actual behavior
```
orientdb {db=TELE09}> SELECT FROM BLACK_LIST;

+----+-----+----------+----------+-----------+
|#   |@RID |@CLASS    |BLACK_TYPE|in_Black_to|
+----+-----+----------+----------+-----------+
|0   |#29:0|BLACK_LIST|BAD MAN   |[#33:0]    |
+----+-----+----------+----------+-----------+

1 item(s) found. Query executed in 0.001 sec(s).
orientdb {db=TELE09}> INFO CLASS BLACK_LIST;

! Class 'BLACK_LIST' does not exist in the database 'TELE09'
orientdb {db=TELE09}> INFO CLASS V

CLASS 'V'

Records..............: 0
Default cluster......: v (id=9)
Supported clusters...: v(9), v_1(10), v_2(11), v_3(12)
Cluster selection....: round-robin
Oversize.............: 0.0
Subclasses.........: TELE_NUMBER
```

## Steps to reproduce the problem
Create Calss in Stuido , and Console can SELECT but CAN'T INFO CLASS
After create any new Class in Console , INFO CLASS WILL WORK

**Comment by lvca** [comment]
This is a known limitation of current remote protocol: the schema updates are not sent via push messages to the clients, so you have to reload the schema in console with 'reload schema' command.
