### ISSUE TITLE
OConcurrentModificationException when try to increment a sequence

### ISSUE THREAD

**Issue by leosimoesp** [orientechnologies/orientdb#7046]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]
- 2.2.14 [X]
## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Increment a sequence using the document API. The actual behavior causes 
I've tried increase the SEQUENCE_MAX_RETRY value but without succcess.
OConcurrentModificationException. Do I need change the MVCC config ? 

Follow the exception:

com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #7:19 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v32343 your=v30008) DB

## Steps to reproduce the problem

- Use remote connection with get pool acquire
- Transaction block to save a list of documents (begin/commit)
- Try catch block to retry transaction when OConcurrentModificationException occurs.

**Comment by lvca** [comment]
Could you try to execute the command at the server side by using a SQL BATCH?

**Comment by leosimoesp** [comment]
Should I execute it directly in console by script command ?

**Comment by lvca** [comment]
You can do that in your application. What driver are you using?

**Comment by leosimoesp** [comment]
The last one 2.2.14.
If I remove the unique indexes everything works. When I use a property key UNIQUE then throws:

com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #7:19 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v37013 your=v37012) DB name="" DB name="" 

Where #7:19 is the sequence.

 select * from #7:19;

+----+-----+---------+-----+----+-----+-------+----------------------------+
|#   |@RID |@CLASS   |start|incr|value|type   |name                        |
+----+-----+---------+-----+----+-----+-------+----------------------------+
|0   |#7:19|OSequence|1    |1   |67019|ORDERED|itemImportacaoPendenciaIDSeq|
+----+-----+---------+-----+----+-----+-------+----------------------------+

How to solve this ?

**Comment by lvca** [comment]
Can you catch the exception, reload the sequence and retry again? This is normal with OrientDB, because we don't have locks and everything is optimistic.

**Comment by lvca** [comment]
Closing this issue, because of no response after a while. In case this issue is still valid, please comment this. Thanks.
