### ISSUE TITLE
ALTER SEQUENCE <seq> START  NOT WORKING 

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#7048]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [ ] Linux 

## Expected behavior and actual behavior
select from OSequence should show something like this
0   |#7:1|OSequence|100  |1   |100  |ORDERED|pidseq|
the result is that start is set to 0

## Steps to reproduce the problem
create sequence pidseq ordered
alter sequence pidseq start 100 increment 1

**Comment by luigidellaquila** [comment]
Hi @austx 

Fixed in branch 2.2.x, the fix will be released with 2.2.15

Thanks

Luigi
