### ISSUE TITLE
Documentation: discrepancy in the authentication doc

### ISSUE THREAD

**Issue by jbilcke** [orientechnologies/orientdb#7049]
Hi,
there is a small contradiction in the documentation, on this page: http://orientdb.com/docs/2.2/Security-Config.html

In the chapter ODefaultPasswordAuthenticator it is written:

> Each user object must contain "user" and "resource" properties.

However the example given a few lines below uses "username", not "user":

```Here's an example of the "users" property:
     "users" :
     [
         { "username" : "someuser", "resources" : "*" }
     ]
```

**Comment by SDIPro** [comment]
Good find.  Corrected.
