### ISSUE TITLE
Lucene indexes still unreliable

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7051]
## OrientDB Version, operating system, or hardware.
- v2.2.14 SNAPSHOT-20161222.152236-78

## Operating System
- [x] Linux

## Expected behavior and actual behavior
1) LUCENE FULLTEXT index created on property FILENAME of class "cdr_eno_20161225"
2) some 10000's of records (documents) loaded, index remains very usable
3) during extra loading, quite intense from different loading programs, the server engine starts to slow down dramatically, leading to timeout errors on the client programs; loading gets aborted in such cases
4) apparently this somehow breaks the Lucene indexes (the files containing these indexes get corrupt, I guess), because lookups on FILENAME start to take 10's of minutes instead of split second
5) did a rebuild of this index (not drop, followed by create), but this does not fix the index:
```
SELECT FILENAME, nr FROM (select FILENAME,count(*) AS nr FROM cdr_eno_20161225 GROUP BY FILENAME ) ORDER BY nr DESC
 FILENAME     nr
MDCA10MCR201612291808.276388.eno.RRC.20161229183002.PROD_R4.eno.data     21410
MDCA20MCR201612291911.277904.eno.RRC.20161229193002.PROD_R4.eno.data     21279
MDCA10MCR201612291748.275980.eno.RRC.20161229181502.PROD_R4.eno.data     21260
MDCA10MCR201612291758.276118.eno.RRC.20161229181502.PROD_R4.eno.data     21227
MDCA20MCR201612291921.278131.eno.RRC.20161229194501.PROD_R4.eno.data     21155
MSTR10MCR201612291803.276253.eno.RRC.20161229181502.PROD_R4.eno.data     21138
MDCA30MCR201612291921.278194.eno.RRC.20161229194501.PROD_R4.eno.data     21101
MDCA30MCR201612291911.277941.eno.RRC.20161229193002.PROD_R4.eno.data     21025
MDCA10MCR201612291818.276748.eno.RRC.20161229184502.PROD_R4.eno.data     21014
MDMA10MCR201612291750.275868.eno.RRC.20161229180001.PROD_R4.eno.data     21011 
...

select count(*) from cdr_eno_20161225
20274235 

select count(*) from cdr_eno_20161225 WHERE FILENAME LUCENE 'MDCA30MCR201612290040.271512.eno.RRC.20161229004501.PROD_R4.eno.data'
20274235 
```

So there are many different FILENAME properties, of which the most occuring one appears 21410 times. However searching with the Lucene index, it seems that ALL the documents have one single particular FILENAME value?!

So I did a DROP of the index, the a new CREATE:
```
...
2016-12-31 15:18:30:334 INFO  {db=mobile} --> OK, indexed 20,274,235 items in 398,696 ms [OIndexRebuildOutputListener]

select count(*) from cdr_eno_20161225 WHERE FILENAME LUCENE 'MDCA30MCR201612290040.271512.eno.RRC.20161229004501.PROD_R4.eno.data'
20274235 
```

-> NOT FIXED !!

**Comment by robfrank** [comment]
Can you post how you define the index? The default analyzer is the standrdAnalyzer. to understand how the SA tokenize your FILENAMEs, try this code:

```
 @Test
  public void name() throws Exception {


    String text= "MDMA10MCR201612291750.275868.eno.RRC.20161229180001.PROD_R4.eno.data";
    StandardAnalyzer analyzer = new StandardAnalyzer();

    TokenStream stream  = analyzer.tokenStream(null, new StringReader(text));
    stream.reset();
    while (stream.incrementToken()) {
      System.out.println(stream.getAttribute(CharTermAttribute.class).toString());
    }
  }
```

that gives::
```
mdma10mcr201612291750.275868
eno.rrc
20161229180001
prod_r4
eno.data
```

So, when you search for **MDMA10MCR201612291750.275868.eno.RRC.20161229180001.PROD_R4.eno.data**, the query parser analyze and tokenize with the SA, producing 5 tokens. The token **prod_r4** will match a lot of documents...

You should understand WHAT you want to search. Maybe you can use an exact match  or change the analyzer to a KeyworsAnalyzer.

let's try with the exact match:
```
select count(*) from cdr_eno_20161225 WHERE FILENAME LUCENE ' "MDCA30MCR201612290040.271512.eno.RRC.20161229004501.PROD_R4.eno.data" '
20274235 
```

**Comment by rdelangh** [comment]
meanwhile the logs show the familiar error again about Lucene indexes:

```
[OIndexRebuildOutputListener]$ANSI{green {db=cdrarch}} Error on flushing Lucene index
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.flush(OLuceneIndexEngineAbstract.java:282)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:2261)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:197)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1912)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:277)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2574)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2520)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
        at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:622)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

**Comment by robfrank** [comment]
Familiar why?  Was there a previous bug?

**Comment by robfrank** [comment]
Can you try with 2.2.14?

**Comment by rdelangh** [comment]
@robfrank 
1) familiar, because we got such errors since 2.1.x versions, then it did not occur for several 2.2.14 snapshot versions, now it occurs again in this snapshot (v2.2.14 SNAPSHOT-20161222.152236-78)
2) we are running with v2.2.14 SNAPSHOT-20161222.152236-78 ; what do you mean "with 2.2.14" ? Is there any other version of 2.2.14 that would be more stable than a snapshot version ?

**Comment by rdelangh** [comment]
@robfrank 
regarding the index: we want to be able to search on property FILENAME using exact matches, but also partial matches (part of the FILENAME string given).

So we defined a FULLTEXT LUCENE index as described above:
```
CREATE INDEX idx_cdr_eno_20161225_1 ON cdr_eno_20161225(FILENAME) FULLTEXT ENGINE LUCENE
```

The test to do an exact match : 
```
select count(*) from cdr_eno_20161225 WHERE FILENAME LUCENE ' "MDCA30MCR201612290040.271512.eno.RRC.20161229004501.PROD_R4.eno.data" '
-> 0
```

**Comment by robfrank** [comment]
1- 2.2.14 was released just before xmas: http://orientdb.com/download/ 
Can you try with stable version? About snapshots, they are published every day only if tests are all green, but they aren't verified by the QA process, so my suggestion is to don't rely on snapshots for production deployments.

2- I wrote this simple test to replicate your case:
```
  @Test
  public void shouldFetchOneDocumentWithExactMatchOnLuceneIndex() throws Exception {

    db.command(new OCommandSQL("CREATE CLASS CDR")).execute();
    db.command(new OCommandSQL("CREATE PROPERTY  CDR.filename STRING")).execute();
    db.command(new OCommandSQL("CREATE INDEX cdr.filename ON cdr(filename) FULLTEXT ENGINE LUCENE")).execute();
    db.command(new OCommandSQL("INSERT into cdr(filename) values('MDCA10MCR201612291808.276388.eno.RRC.20161229183002.PROD_R4.eno.data') ")).execute();
    db.command(new OCommandSQL("INSERT into cdr(filename) values('MDCA20MCR201612291911.277904.eno.RRC.20161229193002.PROD_R4.eno.data ') ")).execute();

    List<ODocument> res = db.query(new OSQLSynchQuery<ODocument>(
        "select count(*) from cdr WHERE FILENAME LUCENE ' \"MDCA30MCR201612290040.271512.eno.RRC.20161229004501.PROD_R4.eno.data\" '"));

    Assertions.assertThat(res).hasSize(1);
  }

```

The test is green. If you can send me a subset of your data, the schema and some sample queries, it can be helpful.

As for _ 'partial matches (part of the FILENAME string given)"_, please bear in mind that Lucene doesn't work as a **LIKE**: it tokenizes the text while indexing AND it tokenizes even the query. Matches are done on tokens, not on the whole text.

**Comment by rdelangh** [comment]
@robfrank 
thanks for your feedbacks!
We need only to do searches on the STRING property with regular (pattern) expressions. The documentation is vague about which types of indexes will correctly (and highly performant) support the wildcard characters in queries with regular expressions.

Secondly, we need also to be able to use leading wildcards in the patterns, such as "%somePartialPattern%"

-> where do I find sufficient documentation about what and how OrientDB supports such queries?
-> which type of index is most usefull ?

**Comment by robfrank** [comment]
Silly question: did you check the docs? http://orientdb.com/docs/2.2.x/Full-Text-Index.html

About wildcards: http://orientdb.com/docs/2.2.x/Full-Text-Index.html#allow-leading-wildcard

There are also links to official lucene documentation. 

If you don't know a lot about how and inverted index works, the WP page is a good intro 

https://en.wikipedia.org/wiki/Inverted_index

https://en.wikipedia.org/wiki/Search_engine_indexing

**Comment by rdelangh** [comment]
@robfrank 
maybe not so silly question, because the documentation about the Lucene indexes does not describe that it would de-compose any string into substrings like you suggest above, using e.g. dot (".") as separator character to define substrings.
I therefor also do not find how I can stop this decomposing of a long string into substrings ('words').

We do not need such "'full text" indexing to find substrings based on a given set of separator characters. We just want to be able to search on any substring of a long string.

The documentation about non-Lucene Full Text indexes does describe this split into substrings (words) and which characters are used for that. I will try to specify an empty set of separator characters, to disable this decomposition of a long string property.
Also, that documentation about non-Lucene Full Text indexes does not describe if and how I might be able to use leading wildcard chars in the search patterns.

-> can you please point me to other documentation where I might find more such details ?

**Comment by robfrank** [comment]
For internal details on how lucene works, links to official documentations are provided. 
If you want to use the Lucene FT index, you need to understand how an inverted index works. There's no other way. 
From 1000ft, lucene's  purpose is to work like a  book's index. In a book's index you find words or simple concepts and the pages where to find them:

word or concept--> pages
high availability 10,40,328
graph 40,200,340

the same happens with your entries, but using the standard analyzer the filename is split into its sub parts.
You can use a plain Lucene query syntax. So, if you are looking for a file name that MUST  contains each term:
```
WHERE FILENAME LUCENE ' "+MDCA30MCR201612290040  AND +20161229004501" '
20274235 
```
With wildcards: 
```
WHERE FILENAME LUCENE ' "+MDCA30MCR201612* AND +20161229004501" '
20274235 

```
Please refer to the linked query parser documentation on Lucene's site for the right syntax and behaviors. 
My suggestion is to use Lucene based FT index because are more performant: you need to to some test to understand the lucene's query syntax and maybe try other analyzers.

**Comment by rdelangh** [comment]
A plain SBT index does not support the wildcard char '%' for a "LIKE" operation.

Rebuilding my queries using the parts (words) of a FILENAME value is also not so wise, since the rules to define the 'words' are part of the Lucene default config, and I don't want to replicate these rules in my programs (to avoid unnecessary dependency on changing rules).

I do not find anything in the Lucene documentation about their standardAnalyzer that would allow me to disable the splitting of FILENAME values into substrings/words.
We are not programming in Java, but the documentation about writing your own analyzer is based on the assumption that the programming language used is Java.

So I revert to an attempt to use the OrientDB FULLTEXT indexing, because there is documentation about metadata parameters which seem to allow that I disable splitting of FILENAME values into substrings for the indexing:
```
create index idx_cdr_eno_20161218_2 on cdr_eno_20161218(FILENAME) FULLTEXT METADATA { "indexRadix": true, "separatorChars" : "", "stopWords": [] }
```

I launched this "create index", but it runs horribly slow:
```
...

2017-01-03 12:44:29:569 INFO  {db=mobile} --> 0.89% progress, 847,022 indexed so far (361 items/sec) [OIndexRebuildOutputListener]
2017-01-03 12:44:39:578 INFO  {db=mobile} --> 0.90% progress, 850,433 indexed so far (341 items/sec) [OIndexRebuildOutputListener]
```
(about 82M items are to be indexed...)
-> what's wrong with the options that am I using? Any alternatives?
-> is Lucene the only prescribed strategy? Is it absolutely necessary to write a different analyzer?

**Comment by rdelangh** [comment]
- Obviously I had to kill this super-slow index creation.
- started a new one, now with "indexRadix: false" : 
```
create index idx_cdr_eno_20161218_2 on cdr_eno_20161218(FILENAME) FULLTEXT METADATA { "indexRadix": false, "ignoreChars": "", "separatorChars" : "", "stopWords": [] }
```
This runs at acceptable speed:
```

2017-01-04 13:40:50:558 INFO  {db=mobile} - Rebuilding index mobile.idx_cdr_eno_20161218_2 (estimated 94,698,606 items)... [OIndexRebuildOutputListener]
2017-01-04 13:41:00:548 INFO  {db=mobile} --> 0.21% progress, 200,488 indexed so far (20,048 items/sec) [OIndexRebuildOutputListener]
2017-01-04 13:41:10:551 INFO  {db=mobile} --> 0.39% progress, 370,391 indexed so far (16,990 items/sec) [OIndexRebuildOutputListener]
2017-01-04 13:41:20:550 INFO  {db=mobile} --> 0.57% progress, 537,085 indexed so far (16,669 items/sec) [OIndexRebuildOutputListener]
...
```

**Comment by rdelangh** [comment]
Ok, this index has been created, but now how can I use it with full benefit?

Eg
```
select count(*) from cdr_eno_20161218 WHERE FILENAME = 'MDCA20MCR201612211058.275964.eno.RRC.20161221111501.PROD_R4.eno.data'
```
takes ages ( > 10mins) so think that no index gets used.
The class has about 95M records, the query is expected to count some 5K records:

```
select count(*) from INDEX:idx_cdr_eno_20161218_2 WHERE key = 'MDCA20MCR201612211058.275964.eno.RRC.20161221111501.PROD_R4.eno.data'
```
-> count=5156 (0.026 secs)

=> Which wildcards can be used with that (non-Lucene) FULLTEXT index? 
=> which operator can be used, such as "LIKE" ?

**Comment by rdelangh** [comment]
found this similar, old (2012) thread, wondering if it ever got a solution:
https://groups.google.com/forum/#!topic/orient-database/O-_79DsLTt8

**Comment by robfrank** [comment]
The documentation about FT indexes is lacking a query example.
Please try this:
```
select count(*) from cdr_eno_20161218 WHERE FILENAME  CONTAINSTEXT "MDCA20MCR201612211058.275964.eno.RRC.20161221111501.PROD_R4.eno.data"
```

But, for sure, it will be slower than lucene.

About Lucene, you usually don't need to write your own analyzer, Lucene comes with a lot of analyzers. 
My suggestion is to switch to Lucene, even with the StandardAnalyzer. 

I enriched my test case: the first uses only the stantard, the second allows the use of leading wilcards (slower!!!!)

```
 @Test
  public void shouldFetchOneDocumentWithExactMatchOnLuceneIndexStandardAnalyzer() throws Exception {

    db.command(new OCommandSQL("CREATE CLASS CDR")).execute();
    db.command(new OCommandSQL("CREATE PROPERTY  CDR.filename STRING")).execute();
    db.command(new OCommandSQL(
        "CREATE INDEX cdr.filename ON cdr(filename) FULLTEXT ENGINE LUCENE ")).execute();
    db.command(new OCommandSQL(
        "INSERT into cdr(filename) values('MDCA10MCR201612291808.276388.eno.RRC.20161229183002.PROD_R4.eno.data') ")).execute();
    db.command(new OCommandSQL(
        "INSERT into cdr(filename) values('MDCA20MCR201612291911.277904.eno.RRC.20161229193002.PROD_R4.eno.data') ")).execute();

    //partial match
    List<ODocument> res = db.query(new OSQLSynchQuery<ODocument>(
        "select from cdr WHERE filename LUCENE ' RRC.20161229193002.PROD_R4.eno.data '"));

    Assertions.assertThat(res).hasSize(2);

    //exact match
    res = db.query(new OSQLSynchQuery<ODocument>(
        "select from cdr WHERE filename LUCENE ' \"MDCA20MCR201612291911.277904.eno.RRC.20161229193002.PROD_R4.eno.data\" '"));

    Assertions.assertThat(res).hasSize(1);

    //wildcard
    res = db.query(new OSQLSynchQuery<ODocument>(
        "select from cdr WHERE filename LUCENE ' MDCA* '"));

    Assertions.assertThat(res).hasSize(2);
  }

  @Test
  public void shouldFetchOneDocumentWithExactMatchOnLuceneIndexKeyWordAnalyzer() throws Exception {

    db.command(new OCommandSQL("CREATE CLASS CDR")).execute();
    db.command(new OCommandSQL("CREATE PROPERTY CDR.filename STRING")).execute();
    db.command(new OCommandSQL(
        "CREATE INDEX cdr.filename ON cdr(filename) FULLTEXT ENGINE LUCENE metadata { 'allowLeadingWildcard': true}")).execute();
    db.command(new OCommandSQL(
        "INSERT into cdr(filename) values('MDCA10MCR201612291808.276388.eno.RRC.20161229183002.PROD_R4.eno.data') ")).execute();
    db.command(new OCommandSQL(
        "INSERT into cdr(filename) values('MDCA20MCR201612291911.277904.eno.RRC.20161229193002.PROD_R4.eno.data') ")).execute();

    //partial match
    List<ODocument> res = db.query(new OSQLSynchQuery<ODocument>(
        "select from cdr WHERE filename LUCENE ' RRC.20161229193002.PROD_R4.eno.data '"));

    Assertions.assertThat(res).hasSize(2);

    //exact match
    res = db.query(new OSQLSynchQuery<ODocument>(
        "select from cdr WHERE filename LUCENE ' \"MDCA20MCR201612291911.277904.eno.RRC.20161229193002.PROD_R4.eno.data\" '"));

    Assertions.assertThat(res).hasSize(1);

    //wildcard
    res = db.query(new OSQLSynchQuery<ODocument>(
        "select from cdr WHERE filename LUCENE ' MDCA* '"));

    //leadind wildcard
    res = db.query(new OSQLSynchQuery<ODocument>(
        "select from cdr WHERE filename LUCENE ' *20MCR2016122* '"));

    Assertions.assertThat(res).hasSize(1);
  }

```

**Comment by rdelangh** [comment]
@robfrank 
ok, thanks for your examples, because I found the trick:
```
select count(*) FROM cdr_eno_20170101 WHERE FILENAME LUCENE ' "MDCA10MCR201701031232.273248.eno.RRC.20170103124501.PROD_R4.eno.data" '
```
returns the correct result (count = 20350), whereas

```
select count(*) FROM cdr_eno_20170101 WHERE FILENAME LUCENE 'MDCA10MCR201701031232.273248.eno.RRC.20170103124501.PROD_R4.eno.data'
```
counts ALL the records from the class (49M) and that's not what we want.

-> syntax is clear now, but please add more clear examples in the documentation.

**Comment by robfrank** [comment]
Usually people uses Lucene over plain text. Your case is "special", I understand that it seems weird that lucene tokenize your entries on punctuation. But it enables to a wide range of queries, for example using proximity or operators like +, - etc. As far as I understand you are storing CDR (https://en.wikipedia.org/wiki/Charging_data_record). Can you share more infos about your use case? 
May I close the issue?

**Comment by rdelangh** [comment]
@robfrank 
1) yes, thanks a lot, this issue can be closed
2) our use case is indeed the storing of telecom CDR record (several 10's M /day) together with low-level network probing data; then to count the two sets of records separately, and compare the counts to assure all CDRs have properly been generated. So there is continuous loading of many records, then quite some aggregations of records must be done, with parallel counting of what has already been aggregated; users must browse the results, and inspect individual records. Our dbase is now 1.6TB, expected to become approx 5-10TB, running on 6 servers in 2 datacenters.
