### ISSUE TITLE
Parameter fromInclusive is ignored for iterateEntriesMajor function inside transaction

### ISSUE THREAD

**Issue by antonzherdev** [orientechnologies/orientdb#7052]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .13[X] .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Steps to reproduce the problem
In a transaction save some data which will affect an index.
Try to the index iterate it with `idx.iterateEntriesMajor(key, false, true)` using the same value as for the saved record as a key.

## Expected behavior and actual behavior
As a result the saved item will be included in the selection ignoring the fact that the second parameter (fromInclusive) is false. 
It should not be included since the key is the same.

The problem happens due to the code in OIndexTxAwareMultiValue:
```
 public PureTxBetweenIndexForwardCursor(Object fromKey, boolean fromInclusive, Object toKey, boolean toInclusive,
        OTransactionIndexChanges indexChanges) {
      this.indexChanges = indexChanges;

      fromKey = enhanceFromCompositeKeyBetweenAsc(fromKey, fromInclusive);
      toKey = enhanceToCompositeKeyBetweenAsc(toKey, toInclusive);

      if (toInclusive)
        firstKey = indexChanges.getCeilingKey(fromKey);
      else
        firstKey = indexChanges.getHigherKey(fromKey);

      if (fromInclusive)
        lastKey = indexChanges.getFloorKey(toKey);
      else
        lastKey = indexChanges.getLowerKey(toKey);

      nextKey = firstKey;
    }
```
toInclusive and fromInclusive should be swapped with each other because here toInclusive is applied to fromKey and fromInclusive to toKey. I suppose it should be vice versa. 

The same problem is for PureTxBetweenIndexBackwardCursor.

**Comment by laa** [comment]
Fixed
