### ISSUE TITLE
is it possible to interrupt/abort a long running command ("create index...") ?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7054]
## OrientDB Version, operating system, or hardware.
- v2.2.14 SNAPSHOT-20161222.152236-78

## Operating System
- [x] Linux

## Expected behavior and actual behavior
Via "console.sh", a "create index..." command was launched which is running dramatically slow, and is expected to run for a few more days ...
```
...
2017-01-03 14:27:54:223 INFO  {db=mobile} --> 2.95% progress, 2,789,842 indexed so far (233 items/sec) [OIndexRebuildOutputListener]
2017-01-03 14:28:04:201 INFO  {db=mobile} --> 2.95% progress, 2,793,091 indexed so far (324 items/sec) [OIndexRebuildOutputListener]
...
```

The "console.sh" session has been exited, but the "create index" job continues to run in the server, seeing the server logs (see above).

-> is it possible to send some kind of a command to the server to
1) identify which jobs it is currently busy with
2) kill one of such jobs

**Comment by maggiolo00** [comment]
If you go to Studio -> Servers Management -> Monitor icon -> Monitoring Tab

You can check all the connections, you should see the one with
create index command and should be able to kill it

**Comment by rdelangh** [comment]
"This feature is available in OrientDB Enterprise Edition" (only)...

**Comment by maggiolo00** [comment]
@rdelangh 

Connections monitoring is available in community. Just click on the monitoring tab

![screen shot 2017-01-03 at 14 49 53](https://cloud.githubusercontent.com/assets/98812/21609660/fb232b56-d1c3-11e6-91b0-5131bab6a04a.png)

**Comment by rdelangh** [comment]
@maggiolo00 
Enrico, sorry for my too brief reply, but what I meant is that the "Server Management" option is returning me a page that says "This feature is available in OrientDB Enterprise Edition"; there is nowhere a "monitoring" tab, or any tab whatsoever.

**Comment by maggiolo00** [comment]
Did you click on the left sidebar the Monitor icon ?

**Comment by rdelangh** [comment]
@maggiolo00 
In the left bar of the "Server Management" page:
- the first icon "stats" is highlighted, shows a page on the right side titled "Dashboard", with the text "This feature is available in OrientDB Enterprise Edition. To download OrientDB Enterprise Edition click here."
- the next icons are all greyed out, if I hover my cursor over them, the URLs seems to get be to "http://ourserver:2480/studio/index.html#/dashboard/general", http://ourserver:2480/studio/index.html#/dashboard/cluster, http://ourserver:2480/studio/index.html#/dashboard/backup, http://ourserver:2480/studio/index.html#/dashboard/profiler, http://ourserver:2480/studio/index.html#/dashboard/security, http://ourserver:2480/studio/index.html#/dashboard/teleporter, http://ourserver:2480/studio/index.html#/dashboard/alerts
- no "monitoring" option anywhere

**Comment by maggiolo00** [comment]
Yeah you should find the monitoring tab under

"http://ourserver:2480/studio/index.html#/dashboard/general

**Comment by maggiolo00** [comment]
Can you post a screenshot of this?

**Comment by maggiolo00** [comment]
Mine was the one i attacched here from the community editions

**Comment by rdelangh** [comment]
@maggiolo00 
ok, found it ;-) under the "general" icon.
Thanks !
Maybe the "studio" web interface, and which functionalities are provided, might be documented in a bit more extend...
