### ISSUE TITLE
Cannot set the root password

### ISSUE THREAD

**Issue by retorquere** [orientechnologies/orientdb#7055]
## OrientDB Version, operating system, or hardware.

- v2.2.14, installed via macos homebrew

## Operating System
- [x] MacOSX

## Expected behavior and actual behavior

After first start I expected to be asked for the root password, but I was not.

## Steps to reproduce the problem

`$ /usr/local/Cellar/orientdb/2.2.14/bin/orientdb start`

(orientdb starts but doesn't ask for a password)

`$ /usr/local/Cellar/orientdb/2.2.14/bin/orientdb stop`

1. edit `/usr/local/Cellar/orientdb/2.2.14/libexec/config/orientdb-server-config.xml`
2. remove the `<user>` entries
3. set `isAfterFirstTime` to `false`
4. `$ /usr/local/Cellar/orientdb/2.2.14/bin/orientdb start`
5. not asked for password

**Comment by robfrank** [comment]
Sorry, the doc is incomplete.
So, redo points 1 to 3, then  /usr/local/Cellar/orientdb/2.2.14/libexec/bin/server.sh, it sould ask for the password. I'll fix the doc ASAP

**Comment by retorquere** [comment]
Will test as soon as I can, we're balls to the wall on a project until the end of next week.

**Comment by keithpjolley** [comment]
Docs still broken for brew installations. Was able to set a root password by:

- `brew services stop orientdb`
- deleting the `root` and `isAfterFirstTime` entries in `libexec//config/orientdb-server-config.xml`
- running `libexec/bin/server.sh` which then asked for and updated the root password
- ^C out of `server.sh`
- `brew services start orientdb`
- `orientdb-console`
