### ISSUE TITLE
NullPointerException in waitDistribuedIsOnline() for 2.2.14

### ISSUE THREAD

**Issue by dgilling** [orientechnologies/orientdb#7062]
## OrientDB Version, operating system, or hardware.
2.2.14

- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [X ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

When using 2.2.14, get a null ptr exception in waitDistribuedIsOnline():

```
odb-master_1   | Error executing request
odb-master_1   | java.lang.NullPointerException
odb-master_1   | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.waitDistribuedIsOnline(ONetworkProtocolBinary.java:449)
odb-master_1   | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeOperationalRequest(ONetworkProtocolBinary.java:420)
odb-master_1   | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:303)
odb-master_1   | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:197)
odb-master_1   | 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

With basic config:
```
{
  "autoDeploy": true,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": 2,
  "readYourWrites": true,
  "newNodeStrategy": "static",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "index": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

If I downgrade to 2.2.13 problem goes away. Seems to be a lot of changes in waitDistribuedIsOnline() for 2.2.14 release in commit: https://github.com/orientechnologies/orientdb/commit/4e731190dd2a6ad8ba1f89d05cbf4cc77edc99ea#diff-2d0549cc3c4950165888be0e16104d5f 
 
## Steps to reproduce the problem
Bring up cluster in distributed mode. Seems to work fine for a min or so. Then error starts appearing.

**Comment by lvca** [comment]
By your log is hard to understand where the NPE happened. Please could you try with last 2.2.x?

**Comment by dgilling** [comment]
tried with 2.2.14...the latest as stated.

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
