### ISSUE TITLE
datetime arithmetic not supported ?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7063]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [x] Linux

## Expected behavior and actual behavior
Need to be able to select DATETIME properties from a class, and add 1 hour to each such value. How?

When the property is named "PRT_DATE", a typical SQL statement would be:
```
SELECT prt_date + 1/24 FROM sometable
```
(where numbers of days can be added/subtracted from DATE columns)

Can't find anything in the docs or on the web about such arithmetic in OrientDB.

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

You can get the date time in milliseconds and operate on that, it's a bit low level but it works fine.
See following example:

```
select eval(' ( 1000 * 60 * 60 * 24 ) + sysdate().asLong()  ').asDate() as a
```

Please PAY A LOT OF ATTENTION to the spaces between parentheses, operands and operators, because the eval() is very very sensitive to that

Thanks

Luigi
