### ISSUE TITLE
Default DateTime does NOT work when using Studio GUI to create Vertex.

### ISSUE THREAD

**Issue by petermo13** [orientechnologies/orientdb#7064]
## OrientDB Version, operating system, or hardware.
- v2.2.13

## Operating System
- [x] Windows

## Expected behavior and actual behavior
Given these Properties for the V Vertex Class:
CREATE PROPERTY V.namespace STRING;
CREATE PROPERTY V.name STRING (NOTNULL TRUE);
CREATE PROPERTY V.description STRING;
CREATE PROPERTY V.creationDT Datetime (DEFAULT sysdate());

When i use command line to create the Vertex, the default creationDT field works fine as expected.
CREATE VERTEX V SET name='Test';
However, When using studio GUI to create a Vertex, the default creationDT field datetime is blank or null.

## Steps to reproduce the problem
Create a property to support default datetime.
Use Studio GUI to create a Vertex.
The default datetime field is blank.
Why?

**Comment by maggiolo00** [comment]
hi @petermo13 

the default value is calculated by the OrientDB server. Once you save the vertex you should get back the
field populated

**Comment by petermo13** [comment]
so What i'm trying to say is that it does NOT generate the default datetime value.
So i think this is a Bug.
![nodefaultdatetime](https://cloud.githubusercontent.com/assets/5331719/21776940/15db447a-d65a-11e6-891d-7cea6aff2ce5.PNG)

**Comment by maggiolo00** [comment]
hi @petermo13 

i think the problem is that since the field is in the schema studio display it with the value of null
And that value is sent to the server and overwrite the default value config.
In the new Vertex ui if you remove completely the field before saving you should the the field populated

**Comment by maggiolo00** [comment]
Hi can mark this as enhancement and if the field is configured with a default value and not edited
will be removed from the post request
WDYT?

**Comment by petermo13** [comment]
Yes, that would be perfect.
Thank you very much.
If a Field has a Default Value, and the GUI Field is Left as Blank, it should use the Default Value.
Thanks
