### ISSUE TITLE
Cannot setDescription while creating class schema

### ISSUE THREAD

**Issue by lucafrosini** [orientechnologies/orientdb#7065]
## OrientDB Version, operating system, or hardware.
 - v2.2.14

## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

While creating my classes schema I set the description but I get null if I try to read the description later on.

## Steps to reproduce the problem

`oClass.setDescription("My Description");`

Debugging OrientDB code seems that you use the wrong command in **OClassImpl** row 694 and 698

`final String cmd = String.format("alter class `%s` description %s", name, shortName);`

**shortName** should be **iDescription**

**Comment by lucafrosini** [comment]
I just tested that if I try to alter the class using Studio and reading with java I get the description.

**Comment by tglman** [comment]
hi @lucafrosini,

Thank you for investigating so deep, feel free to do a pull request on 2.2.x branch with the fix, in any case we are going to look into this soon.

Bye

**Comment by lucafrosini** [comment]
I just created the pull request #7067

**Comment by tglman** [comment]
merged the pr, closing

Thank you for checking and fixing this.

Bye

**Comment by lucafrosini** [comment]
thank you

**Comment by lucafrosini** [comment]
Sorry but the bug is not fixed. 

The patch I proposed does not work because while invoking
oClass.setDescription("This is my test class");

This is translated in the following command

alter class `MyClass` description This is my test class 

I think that ` are missing in the following command (rows 703 and 707).
        final String cmd = String.format("alter class `%s` description %s", name, iDescription);

**Comment by tglman** [comment]
hi,

Used query parameters instead of formatting, re-closing

Bye

**Comment by lucafrosini** [comment]
Sorry @tglman but the bug still occur with a different exception

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
alter class `MyClass` description ?
    ^
Encountered " <ALTER> "alter "" at line 1, column 1.
Was expecting one of:
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    <RETURN> ...
    <PROFILE> ...
    <FIND> ...
    <REBUILD> ...
    <OPTIMIZE> ...
    <GRANT> ...
    <REVOKE> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ...
    <IF> ...
    <SLEEP> ...
    <CONSOLE> ...
    
	DB name="gcube"
	DB name="gcube"

**Comment by tglman** [comment]
hi @lucafrosini,

We did a couple of other fix that we release a week ago, feel free to check it, this time i'll wait your feedback to close it.

Regards

**Comment by lucafrosini** [comment]
I upgraded to 2.2.18 version both server and clients.

Unfortunately I'm still getting an error.

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
alter class `Embedded` description ?
    ^
Encountered " <ALTER> "alter "" at line 1, column 1.
Was expecting one of:
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    <RETURN> ...
    <PROFILE> ...
    <FIND> ...
    <REBUILD> ...
    <OPTIMIZE> ...
    <GRANT> ...
    <REVOKE> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ...
    <IF> ...
    <SLEEP> ...
    <CONSOLE> ...
    
	DB name="mydb"
	DB name="mydb"
```

**Comment by lucafrosini** [comment]
It seems working now

**Comment by lucafrosini** [comment]
This bug seems reappeared in version 3.0.13.

I opened another bug see #8730


```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
alter class `MyClass` description ?
    ^
Encountered " <ALTER> "alter "" at line 1, column 1.
Was expecting one of:
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    <RETURN> ...
    <FIND> ...
    <REBUILD> ...
    <OPTIMIZE> ...
    <GRANT> ...
    <REVOKE> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ...
    <IF> ...
    <SLEEP> ...
    <CONSOLE> ...
    <MOVE> ...
    <SELECT> ...
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <FIND> ...
    <INSERT> ...
    <MOVE> ...

```

**Comment by lucafrosini** [comment]
Any news about this?
I'm still experiencing. I'm using OrientDB 3.1.2

**Comment by lucafrosini** [comment]
Sorry, I commented on the old bug. I'm going to comment on the new one. See #8730
