### ISSUE TITLE
syntax for SELECT FROM (set of RIDs from index) is unclear

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7066]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [x] Linux

The documentation about SELECT (http://orientdb.com/docs/2.2.x/SQL-Query.html) describes that the 'object to query from' can be a list of record-IDs: "This can be a class, cluster, single Record ID, set of Record ID's, ..."

However this does not work when working with a list of record-IDs that's obtained from a query from an index:

This query
```
SELECT FROM INDEX:idx_cdr_af_20170101_2 WHERE key LUCENE ' *1234* '
```
produces a table with properties from the index:
```
@version  |   key   |   rid
0   |   *1234*   |   #1137:405533 
...
```

So this is not a set of Record-IDs.

So, I select only the "rid" : 
```
SELECT rid FROM INDEX:idx_cdr_af_20170101_2 WHERE key LUCENE ' *1234* '
```
produces a table with properties from the index:
```
rid
#1137:405533 
...
```

Using this set of RecordIDs as 'object to query from' does not consider the elements as RecordIDs, but as simple strings : 
```
SELECT * FROM (SELECT rid FROM INDEX:idx_cdr_af_20170101_2 WHERE key LUCENE ' *1234* ')
```
produces a table with rid strings:
```
rid
#1137:405533 
...
```

Another attempt to get hold of the actual properties of the records themselves, is via the "expand()" method (http://orientdb.com/docs/2.2.x/SQL-Functions.html#expand):
-     When used on a collection field, it unwinds the collection in the field and use it as result.
-     When used on a link (RID) field, it expands the document pointed by that link.
Since version 2.1 the preferred operator to unwind collections is UNWIND.

Further, the two examples provided for "expand" are identical, and thus do not explain the use cases.

The only use case documented (http://orientdb.com/docs/2.1/SQL.html#select-from-multiple-targets) for "expand", is when it is expanding a variable that is the "unionAll()" of two other variables from subqueries. But clearly this assumes that the subqueries yield entire documents, and not a set of record-IDs:

This query works:
```
select expand($b)
   let a1 = (SELECT FROM cdr_af_20170101 WHERE CALLING_NUMBER LUCENE ' *1234* ' ),
   a2 = (SELECT FROM cdr_af_20170101 WHERE CALLED_NUMBER LUCENE ' *1234* ' ),
   b = unionAll($a1, $a2)
```
(it returns the complete documents contents)

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

The result of a SELECT FROM INDEX is a bit different than a SELECT FROM CLASS, I'm adding a note in the docs.

Also about the examples for expand() function, I already changed it a bit to make it clearer

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila thx for the feedback. 
About the query from an index:

I hoped a query from an index is returning RIDs that I can "unionAll()" and/or "insertSect()" from different subqueries in a "let ..." block, to produce a set of RIDs. This goes quickly, since no properties of the actual document are collected yet.
That combined set of RIDs would then be used in a single "expand()" to get the properties of the actual records/documents.
-> is that possible ?

**Comment by luigidellaquila** [comment]
@rdelangh maybe something like this is an acceptable work-around:

```
select expand(unionAll($a.x, $b.x)) 
let $a = (select set(rid) as x from index:ouser.name where key = 'admin'),
$b = (select set(rid) as x from index:ouser.name where key = 'reader')
```

thanks

Luigi
