### ISSUE TITLE
backup script disregards web dashboard credentials

### ISSUE THREAD

**Issue by rmoog** [orientechnologies/orientdb#7076]
## OrientDB Version, operating system, or hardware.
2.2.8
## Operating System
Linux
## Expected behavior and actual behavior
Web dashboard and backup script should accept the same credentials. root user works only for the web dashboard.
## Steps to reproduce the problem
1. Set root password.
2. Login via dashboard - works.
3. Make sure you have a database to backup.
4. Backup DB - Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: somedatabase

**Comment by tglman** [comment]
hi @rmoog,

The user and password depends on the connection url, if you are using "plocal" to connect the database, it means you are not using the server but opening the database in embedded mode, and this do not support server authentication and the relative server user "root".

Hope this help.

Regards
