### ISSUE TITLE
cannot open database for backup

### ISSUE THREAD

**Issue by rmoog** [orientechnologies/orientdb#7077]
## OrientDB Version, operating system, or hardware.
2.2.8
## Operating System
Linux
## Expected behavior and actual behavior
Backup script should either work or complain the credentials aren't right.
What happens is that even when there's NOTHING using the database we want to backup, the script complains that there is something using the database.
## Steps to reproduce the problem
Just set up a database and try to backup.

**Comment by tglman** [comment]
hi @rmoog,

If you are using the "plocal" url while a instance of the server is running it will complain because the database is used by the server and cannot be open by the script.

Hope this help.

Regards

**Comment by tglman** [comment]
hi @rmoog,

Did we answer to your issue? can we close this ?

Bye

**Comment by tglman** [comment]
Hi,

No replay since a while, closing.

Regards
