### ISSUE TITLE
Enhancement Request: Orientdb direct memory log

### ISSUE THREAD

**Issue by cmassi** [orientechnologies/orientdb#7078]
For tuning and troubleshooting purposes, it would be useful to have in orientdb server a new property, to enable logging of current usage for direct buffers, and current direct memory allocation, without using jmx beans .

Because this log is related to memory, the format of each output line, could be similar to the jvm gc.log , which is, for the default ParallelGC collector: 

    [event(reason) [area_of_interest: before -> after(current_capacity)], [...], secs ] [user|sys|real time]

The server could trace [DirectBuffers:..] [DirectMemory:...] for each INFO event, like a new ByteBuffer.allocateDirect() or a new memory.chunk allocation.

There could be WARN too, for events which customers might grab from log, e.g: when you are low on resources

**Comment by taburet** [comment]
Implemented, closing. More details: http://orientdb.com/docs/3.0.x/troubleshooting/Direct-Memory-Tracing.html
