### ISSUE TITLE
Wrong placing of `-Xmx` option  in console.sh

### ISSUE THREAD

**Issue by kuzeko** [orientechnologies/orientdb#7084]
[The setting of the `-Xmx` option in the `SSL_OPTS` inside `console.sh`](https://github.com/orientechnologies/orientdb/blob/master/graphdb/script/console.sh#L41) is  problematic:
[because this is overriding any other option set in the `JAVA_OPTS` variable](http://stackoverflow.com/questions/22095305/java-daemons-launched-with-multiple-xmx-option-hadoop)

p.s
Also, could you just stick with reserving the `ORIENTDB_OPTS_MEMORY` or any `ORIENTDB_OPTS` variable in all your `.sh` scripts for the user to set.
I've found an incoherent use of those variables, which range from `ORIENTDB_OPTS_MEMORY`,  `JAVA_OPTIONS` and `JAVA_OPTS`, depending on the script among `console.sh`, `server.sh` and `gremlin.sh`.
Thanks

**Comment by robfrank** [comment]
Thank you for this issues, we need a cleanup of the scripts. 
If you want, feel free to provide a PR on the develop branch.

**Comment by cmassi** [comment]
Current console.sh is: <br>

#JAVA_OPTS=-Xmx1024m <br>
SSL_OPTS="-Xmx512m -Dclient.ssl.enabled=false "<br>
exec "$JAVA" -client $JAVA_OPTS $ORIENTDB_SETTINGS $SSL_OPTS \ <br>

I suppose that a simple fix would be:

JAVA_OPTS=-Xmx512m <br>
SSL_OPTS="-Dclient.ssl.enabled=false " <br>
exec "$JAVA" -client $JAVA_OPTS $ORIENTDB_SETTINGS $SSL_OPTS \ <br>

**Comment by kuzeko** [comment]
@cmassi not really, one should at lease check whether `$JAVA_OPTS` is already set before overwriting

**Comment by robfrank** [comment]
memory settings split on dedicated variable
