### ISSUE TITLE
thread local leak?

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7085]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [ X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

```
logs/catalina.2017-01-13.log:13-Jan-2017 20:25:01.776 SEVERE [localhost-startStop-2] org.apache.catalina.loader.Web
appClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [c
om.orientechnologies.common.concur.lock.OReadersWriterSpinLock.InitOModifiableInteger] (value [com.orientechnologie
s.common.concur.lock.OReadersWriterSpinLock$InitOModifiableInteger@562538c9]) and a value of type [com.orientechnol
ogies.common.types.OModifiableInteger] (value [0]) but failed to remove it when the web application was stopped. Th
reads are going to be renewed over time to try and avoid a probable memory leak.
logs/catalina.2017-01-13.log:13-Jan-2017 20:25:01.776 SEVERE [localhost-startStop
```

**Comment by taburet** [comment]
@jamieb22 do you have a call to `Orient.instance().shutdown()` on application unloading?

**Comment by jamieb22** [comment]
Yes we do...

@Override
	public void destroy(  ) {
		log.debug("shutdown orient");
		Orient.instance().shutdown();
	}

**Comment by taburet** [comment]
@jamieb22 JFYI, I have tried to run some very basic webapp, problem confirmed, working on it now.

**Comment by taburet** [comment]
Unfortunately, it's impossible to fix this thread locals "leak" w/o involving hacks. That's how the JVM works. More information here: https://wiki.apache.org/tomcat/MemoryLeakProtection#threadLocalPseudoLeak

Tomcat has a long history fighting this kind of "leaks", they finally gave up and decided to print a warning and refresh the suspicious threads in the pool over the time. In fact, discovered another kind of a JVM leak while working on the issue – `com.sun.jmx.mbeanserver.MXBeanIntrospector#mbeanInfoMap`. It's cleaned on a bean registration, but not on the bean removal, even after you deregistered the bean in a clean way there is still a reference to the bean class that may live for some time. Good thing that it's cleaned on a new bean registration, after application restart it will register new beans and this process will expunge the old ones.

Anyway, fixed related shutdown hook and signal handler leaks to ease the life of GC and facilitate the unloading of the app's class loader and its classes.
