### ISSUE TITLE
OrientDb Pagination Issue

### ISSUE THREAD

**Issue by thanveeraqtharah** [orientechnologies/orientdb#7086]
## OrientDB Version, operating system, or hardware.
- v2.1 SNAPSHOT[ ] - .9[ ]

## Operating System
- [ ] Windows

## Expected behavior and actual behavior
Im using orientDb(version 2.1.9). When I try to implement pagination , it throws me the below error
Encountered " <LIMIT> "LIMIT "" at line 1, column 158.
Was expecting one of:
    <TO> ...
    <VALUES> ...

**Comment by luigidellaquila** [comment]
Hi @thanveeraqtharah 

I strongly suggest you to upgrade to v 2.2, as 2.1 is currently supported only for enterprise users.
Anyway, please post your full query, maybe there is a way to work around it

Thanks

Luigi

**Comment by thanveeraqtharah** [comment]
Thank you for your reply.  Im using 

		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-server</artifactId>
			<version>2.1.9</version>
		</dependency>

and below  is the query

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: 
Select from _222d768ec2ac4241b574678fea02cd83 where meta.appId='0eb92c64078949c8bbc16daeaa0f4267' and meta.sourceId='222d768ec2ac4241b574678fea02cd83' and LIMIT 5;
Encountered " <LIMIT> "LIMIT "" at line 1, column 156.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...

**Comment by luigidellaquila** [comment]
Ok, got it, you just have to remote an "AND" ;-)

```
Select from _222d768ec2ac4241b574678fea02cd83 where meta.appId='0eb92c64078949c8bbc16daeaa0f4267' and meta.sourceId='222d768ec2ac4241b574678fea02cd83'  LIMIT 5
```

Thanks

Luigi

**Comment by thanveeraqtharah** [comment]
thank you :)
