### ISSUE TITLE
SEVERE: finalize: readers != 0

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7087]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [ X] Linux

## Expected behavior and actual behavior

17-Jan-2017 07:40:32.774 SEVERE [Finalizer] null.null OCachePointer.finalize: readers != 0
17-Jan-2017 07:40:32.775 SEVERE [Finalizer] com.orientechnologies.common.log.OLogManager.log OCachePointer.finalize
: readers != 0

**Comment by laa** [comment]
@jamieb22 Does it happen in server after OOM ?

**Comment by jamieb22** [comment]
It appears to happen soon after startup

```
com.stimulus.archiva.domain.logging.FixedWindowAppenderSettings$ExtendedFixedWindowRollingPolicy@44cec2f4 - Will use zip compression
04:24:04,031 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[null] - Active log file name: /var/log/mailarchiva/sel/debug/trash.log
04:24:04,031 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[null] - File property is set to [/var/log/mailarchiva/sel/debug/trash.log]

18-Jan-2017 04:24:04.245 SEVERE [Finalizer] com.orientechnologies.common.log.OLogManager.log OCachePointer.finalize: readers != 0
18-Jan-2017 04:24:04.245 SEVERE [Finalizer] com.orientechnologies.common.log.OLogManager.log OCachePointer.finalize: readers != 0
18-Jan-2017 04:24:04.245 SEVERE [Finalizer] com.orientechnologies.common.log.OLogManager.log OCachePointer.finalize: readers != 0
18-Jan-2017 04:24:04.246 SEVERE [Finalizer] com.orientechnologies.common.log.OLogManager.log OCachePointer.finalize: readers != 0
18-Jan-2017 04:24:04.246 SEVERE [Finalizer] com.orientechnologies.common.log.OLogManager.log OCachePointer.finalize: readers != 0
18-Jan-2017 04:24:04.246 SEVERE [Finalizer] com.orientechnologies.common.log.OLogManager.log OCachePointer.finalize: readers != 0
```

**Comment by taburet** [comment]
@jamieb22 could you please [enable the leak detection](https://orientdb.com/docs/2.2/Leak-Detector.html)? If the database size is small and `readers != 0` messages are consistent, please share the database and I will analyse what is happening.

**Comment by taburet** [comment]
Seems like YourKit is trying to load third-party classes using the wrong class loader. Why do you need to use YourKit?

**Comment by laa** [comment]
@jamieb22 could you set us database or switch on memory leak detector ?

**Comment by jamieb22** [comment]
I am going to close. The error is not appearing in the logs after change cache size.

**Comment by laa** [comment]
@jamieb22 what about OOM was it gone ?

**Comment by jamieb22** [comment]
I don't want to close OOM issue yet, but, for the past day, the server has been running ok. no restarts needed.
