### ISSUE TITLE
Doubts in the orientdb manual

### ISSUE THREAD

**Issue by NicholasQu** [orientechnologies/orientdb#7092]
While i was reading the orientdb manual chapter "clusters -> Undstanding Clusters" , i find some statements are ambiguous
<http://orientdb.com/docs/last/Tutorial-Clusters.html>

By default, OrientDB creates one cluster for each Class. Starting from v2.2, OrientDB automatically creates multiple clusters per each class (the number of clusters created is equals to the number of CPU's cores available on the server) to improve using of parallelism. 

> All records of a class are stored in the same cluster, which has the same name as the class.

You can create up to 32,767 (or, 215 - 1) clusters in a database. Understanding the concepts of classes and clusters allows you to take advantage of the power of clusters in designing new databases.

so, are all records of a class stored in the same cluster or different clusters via strategy like random, balanced on earth? 
Please clarify that, thanks.

**Comment by smolinari** [comment]
I think that sentence should read:

> All records of a class are stored in the same clusters, which have the same or similar name as the class, when used with the default setup.

Or something to that effect.

Scott

**Comment by NicholasQu** [comment]
I agree with your "when" condition appended at the end, which makes sense. However, "similar name" is not quite reasonable. @smolinari

**Comment by smolinari** [comment]
Why not? The standard naming is the name of the class plus "_x", where "x" is a number. So for instance (as of version 2.2), if you have a 4 core system and a class called "myClass", ODB will automatically create 4 clusters called "myClass_1","myClass_2","myClass_3","myClass_4". Here is my Docker containerized ODB with two cores allotted showing a test database with a test class. 

![image](https://cloud.githubusercontent.com/assets/3314957/22054278/0f040518-dd55-11e6-877a-0bf8374585d1.png)

Scott

**Comment by NicholasQu** [comment]
Sorry, i got the wrong direction from you previous post, it's true then, thanks for your detailed explanations.

**Comment by NicholasQu** [comment]
@smolinari 
I suspect your dream ODB character in this scenario is just like what elasticsearch does, isn't it?
You just need to set the sharding number of one index, need not to care about how it balance among clusters.

**Comment by smolinari** [comment]
Yeah, sort of. How ElasticSearch works is a bit different to ODB, but yes. the inner workings of the parallelization capabilities within ODB shouldn't be a userland concern and those innerworkings most definitely shouldn't raise concerns about possible trade-offs for the user to have to consider. At least not at the level of classes and clusters. 

Scott
