### ISSUE TITLE
count does not work with limit

### ISSUE THREAD

**Issue by karolmie1** [orientechnologies/orientdb#7094]
## OrientDB Version, operating system, or hardware.
- v2.2 SNAPSHOT

## Operating System
- Linux

## Expected behavior and actual behavior
This is probably strange use case. I want to use limit and count in the same query - i want to get exact number of vertices that the query would return.

Example query: 
select count(*) from User where login< 'leonard' order by login desc limit 2
in my case it returns 4, when it should return maximum 2.

**Comment by luigidellaquila** [comment]
Hi @karolmie1 

In this query, the LIMIT is applied to the final result set, ie. you will have at most two records in the final result set.
If you want to know how many users have login < 'leonard' you have to use a subquery:

```sql
select count(*) from (
   select from User where login< 'leonard' limit 2
)
```

I didn't get the ORDER BY there... what's its goal? 

Thanks

Luigi

**Comment by karolmie1** [comment]
Ok, I thought I found a bug, sorry to bother you then.

Purpose was more or less to do something like that: http://stackoverflow.com/questions/41721349/sql-get-at-least-n-elements-before-key-in-one-query
