### ISSUE TITLE
Gremlin Query does not run in a Function

### ISSUE THREAD

**Issue by ashkumar** [orientechnologies/orientdb#7096]
## OrientDB Version, operating system, or hardware.

- v2.2.13

## Operating System
- [ ] Linux
- [X ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I have a Gremlin pipeline as such

<pre><code>
g.v('41:0').outE('AE_Cat_SubCat').inV().transform{[id:it.id, text:it.text]}.gather
</code></pre>

This produces the following output in Gremlin console
[{id=#46:0, text=Physics}, {id=#45:0, text=General Science}, {id=#47:0, text=Sports}]

However, I created a function in the OrientDB web console and used the following code
<pre><code>
def mydb = orient.getGraph();
def queryOutput, results;
try{
  def query = "g.v(\'${CategoryId}\').outE(\'AE_Cat_SubCat\').inV().transform{[\'id\':it.id, \'text\':it.text]}.gather";
  println query
  queryOutput = mydb.command('gremlin', query);
  println queryOutput

  
}catch(err){
  return err;  
}
return queryOutput;
</code></pre>

And I get the following result

[
    {
        "@type": "d",
        "@version": 0,
        "value": [
            null,
            null,
            null
        ]
    }
]

Output in the console is 
g.v('41:0').outE('AE_Cat_SubCat').inV().transform{['id':it.id, 'text':it.text]}.gather
[null, null, null]

Please note the the Gremlin query and transform is identical. I have tried with and without the quotes in the transform also.

However, if we remove the transform step, now I get the expected result but a bit too verbose for practical use.

<pre><code>
def mydb = orient.getGraph();
def queryOutput, results;
try{
  def query = "g.v(\'${CategoryId}\').outE(\'AE_Cat_SubCat\').inV().gather";
  println query
  queryOutput = mydb.command('gremlin', query);
  println queryOutput

  
}catch(err){
  return err;  
}
return queryOutput;
</code></pre>

Gives me back
[
    {
        "@type": "d",
        "@rid": "#46:0",
        "@version": 2,
        "@class": "A_SubCategory",
        "text": "Physics",
        "in_AE_Cat_SubCat": [
            "#53:0"
        ],
        "@fieldTypes": "in_AE_Cat_SubCat=g"
    },
    {
        "@type": "d",
        "@rid": "#45:0",
        "@version": 2,
        "@class": "A_SubCategory",
        "text": "General Science",
        "in_AE_Cat_SubCat": [
            "#54:0"
        ],
        "@fieldTypes": "in_AE_Cat_SubCat=g"
    },
    {
        "@type": "d",
        "@rid": "#47:0",
        "@version": 5,
        "@class": "A_SubCategory",
        "out_AE_SubCat_Question": [
            "#73:0",
            "#74:0",
            "#75:0"
        ],
        "text": "Sports",
        "in_AE_Cat_SubCat": [
            "#55:0"
        ],
        "@fieldTypes": "out_AE_SubCat_Question=g,in_AE_Cat_SubCat=g"
    }
]

## Steps to reproduce the problem

I suspect the transform stage of the pipeline does not work in Functions.  You can try to apply any type of transform and it will likely fail.

Is there a better way to accomplish what I need?  I am merely trying to clean up the output such that we get only the data that the front end would need and be interested in.

Thanks

**Comment by maggiolo00** [comment]
hi @ashkumar 
let me check

**Comment by maggiolo00** [comment]
hi @ashkumar 
Fixed. It will be available in the next release 2.2.17
Thanks
