### ISSUE TITLE
Insert select different effects in studio and in java query

### ISSUE THREAD

**Issue by karolmie1** [orientechnologies/orientdb#7098]
## OrientDB Version, operating system, or hardware.
- [x] v2.2.10
## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

In orient db I performed this query: 
`insert into User set login = 'pc', password =  'pc', hasPermission = ( SELECT @rid FROM Permission WHERE type = 'USER' )`
It works ok - user has permissions. The same query though in java code:
`insert into User set login = :key, password = :pass, hasPermission = ( SELECT @rid FROM Permission WHERE type = 'USER' )`

This new user has proper login and password, but no permissions! And the query is exactly the same!

It works for me if I do it 100% java api:
```
override fun createUser(login: String, password: String, permissions: Set<Permissions>): UserIdentity {
        return autoclose(database.tx) { graph ->
            val user: Vertex = graph.addVertex("class:User", mapOf(
                "login" to login,
                "password" to BCrypt.hashpw(password, BCrypt.gensalt())
            ))
            graph.getPermissions(permissions).forEach {
                graph.addEdge(null, user, it, "hasPermission")
            }
            return@autoclose userBuilder.build(user);
        }
    }
```

## Steps to reproduce the problem

I can link the repo I'm working in, but its really not minimal example, and building it is 2 step process.

**Comment by luigidellaquila** [comment]
Hi @karolmie1 

If you could provide a link to the repo and instructions to build and lanuch it, it would help a lot

Thanks

Luigi

**Comment by karolmie1** [comment]
Ok, I've reproduced it again: 
https://bitbucket.org/kmierzej/fragaria-server/branch/7098-orientdb-bug-reproduction#diff

can be tested without webapp using wget:
wget -O- --post-data='{"login": "sweeney", "password": "todd", "permissions": ["USER"] }' --header=Content-Type:application/json http://localhost:8080/api/admin/user
result can be checked in orient db studio: http://localhost:2480/studio/index.html#/
database: 'fragaria', user: 'admin', password: 'admin'

how to start application: 
1. clone repository, checkout branch 7098-orientdb-bug-reproduction
2. run ./gradlew run

You can easily tell where is the method in question, everything can be cleanly seen in diff.

If you want to click through application, you can run a webapp (not necessary)
1. clone https://bitbucket.org/kmierzej/fragaria-webapp
1.5: Some npm global installs might be necessary, but I don't remember which unfortunately
2. run npm install, or yarn (much quicker)
3. run npm run server, or yarn server
4. go to localhost:3000

Any comments on my code are greatly appreciated btw.

**Comment by luigidellaquila** [comment]
Hi @karolmie1 

The real problem here is in the SQL statement: that way you are not creating an edge, you are just adding a link property. 
You should do the following instead:

```
insert into User set login = :key, password = :pass;
create edge hasPermission from (select from User where login = :key) to ( SELECT @rid FROM Permission WHERE type = 'USER' )
```

Thanks

Luigi

**Comment by karolmie1** [comment]
Hi @luigidellaquila 
Yeah, I mean that is what I did in the end. The only reason I created this issue is that when I run this query in orientdb studio it produces the edges, while the same query executed through java code does not produce them. This seems baffling to me. Why result is different?

insert into User set login = 'pc', password = 'pc', hasPermission = ( SELECT @rid FROM Permission WHERE type = 'USER' )

This one produces edges in orientdb studio, while it should not, according to you.

Apart from that, this query was base on one you can find in the docs: http://orientdb.com/docs/2.2/SQL-Insert.html

> Inserts using SELECT sub-queries
> 
> orientdb> INSERT INTO Diver SET name = 'Luca', buddy = (SELECT FROM Diver 
>           WHERE name = 'Marko')

**Comment by karolmie1** [comment]
I will test with v2.2.16 and see if problem persists.

**Comment by karolmie1** [comment]
v2.2.17 creates property with other vertex id instead of edge. Better than nothing i guess.
