### ISSUE TITLE
Unable to tap Orientdb metrics even after enabling JMX

### ISSUE THREAD

**Issue by uguessmyid** [orientechnologies/orientdb#7101]
Hi,
We have enabled JMX on Orientdb by
JMX SERVER, TO TURN ON SET THE 'ENABLED' PARAMETER TO 'true'
handler class="com.orientechnologies.orient.server.handler.OJMXPlugin"
parameters
parameter name="enabled" value="true" /
parameter name="profilerManaged" value="true" /
/parameters
/handler
in orientdb-server-config.xml

Yet we are unable to tap orientdb metrics.
We can tap metrics by using the HTTP port only right?

Hope you can give us some instructions on how to connect and tap the metrics

**Comment by laa** [comment]
@uguessmyid what metrics you were going to access?

**Comment by laa** [comment]
Hi @uguessmyid what kind of metrics you were going to access ?

**Comment by uguessmyid** [comment]
Hi @laa , Thank you. The Issue has been resolved.

**Comment by pythianarceri** [comment]
@uguessmyid i was wondering how did you resolve the issue
