### ISSUE TITLE
A* SQL function returns paths of increasing length for consecutive, identical queries

### ISSUE THREAD

**Issue by martineutinger** [orientechnologies/orientdb#7103]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
When sending the same query (e.g. 'SELECT astar(#23:19965, #23:19187, 'length')') more than once, only the first result is correct. The consecutive results are longer and longer paths until it seems to either plateau or return no path at all. 

So e.g. the shortest path contains 5 nodes.
The first query would return the 5 nodes. The second would return 10. Then 17. And then it returns 21 for every query past that point.

## Steps to reproduce the problem
- Start the server, or connect to a local database. 
- Send a query like 'SELECT astar(#23:19965, #23:19187, 'length')' multiple times WITHOUT restarting the server in between each query.

## Possible solutions
The problem seems to be, that in com.orientechnologies.orient.graph.sql.functions.OSQLFunctionAstar
'PriorityQueue<OrientVertex> open' and 'Set<OrientVertex> closedSet' are carried over from the last execution of the algorithm.
It seems like ...
... either .clear() should be called for 'open' and 'closedSet' before each execution
... or a new instance of OSQLFunctionAstar should be created, every time the function is executed.

## Misc
This is not the case with Dijkstra's algorithm, because a new instance of A* is created each time.

**Comment by saeedtabrizi** [comment]
Hi @martineutinger  , @luigidellaquila  
yes i detect some bugs in the astar function too . i check it asap .

**Comment by luigidellaquila** [comment]
Thank you @saeedtabrizi, I'll check it as well

Thanks!

Luigi

**Comment by saeedtabrizi** [comment]
Hi @martineutinger , @luigidellaquila 
I fix some bugs (reported bug) and more test to `astar` function now . i will push it asap .

**Comment by luigidellaquila** [comment]
Great, thank you very much @saeedtabrizi !

Looking forward to the pr!

Thanks

Luigi

**Comment by saeedtabrizi** [comment]
@luigidellaquila the bugs fixed now .

**Comment by martineutinger** [comment]
Thank you @saeedtabrizi.

So does that mean the single-astar-instance-per-server is by design?

**Comment by saeedtabrizi** [comment]
Dear @martineutinger , Short answer is **Yes** in the current version . but i planned to add and implement some useful and more efficient path finding functions like the **Block A*** , **Hybrid A*** , **CH** , **CRP** for OrientDB asap  .
As we know path-finding algorithms is so useful to Robotic  , Intelligence Traffic Management, Routing for the smart vehicle systems and some similar applications.

![screenshot from 2017-01-28 12-47-17](https://cloud.githubusercontent.com/assets/10245423/22395589/30702eb0-e558-11e6-8a22-c15cde36e29d.png)

I'm glad if i hear from @lvca , @luigidellaquila and i create an issue for proposal  path-finding .

**Comment by lvca** [comment]
+100!

**Comment by luigidellaquila** [comment]
Hi @martineutinger 

I just pushed a fix for this. Thank you very much @saeedtabrizi for the contribution!

Luigi

**Comment by saeedtabrizi** [comment]
@luigidellaquila Thanks to solve the root of problem .

**Comment by santo-it** [comment]
Noted in the [Release Notes](https://github.com/orientechnologies/orientdb/wiki/OrientDB-2.2-Release-Notes)
