### ISSUE TITLE
[Question] Is there any plan to support  R services in OrientDB .

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#7106]
As we know in the the data scientists need to R  in analytic tool box . 
is there any plan to support R Language scripting in the OrientDB ?

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

Right now we have no specific plans to support R as a scripting language `inside` OrientDB, maybe we will work on this after 3.0 final, but we will hardly have time to do it before.
If you need R integration, you can take a look at this third party plugin: https://github.com/retrography/OrientR

Thanks

Luigi

**Comment by saeedtabrizi** [comment]
Hi @luigidellaquila 

Thanks and god bless you .  

Saeed
