### ISSUE TITLE
Error on flushing Lucene index

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7108]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [x] Linux

## Expected behavior and actual behavior
After index rebuild, the message appears (was told to be resolved in 2.2.14):

```
Error on flushing Lucene index
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.flush(OLuceneIndexEngineAbstract.java:282)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:2261)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.run(OIndexManagerShared.java:527)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by maggiolo00** [comment]
hi @rdelangh 
seems a different exception in terms of stacktrace
let me check

Where did you get this exception? On which server?
It should be

**Comment by rdelangh** [comment]
@maggiolo00 
I got the exception in the logs of the single server that is running. The server has been started with the stand-alone mode (i.e. not distributed).

**Comment by maggiolo00** [comment]
@rdelangh 

when do you get this exception?

by manually running 

```rebuild index  ```

?

**Comment by rdelangh** [comment]
@maggiolo00 
I have not launched the index rebuild manually, this was done automatically by the server startup (after a sudden death).

**Comment by robfrank** [comment]
So what happen was:
- server running smoothly for a while, with lucene indexes
- server crashes due to: reason unknown
- server restarted: it rebuilds indexes
- after OR during rebuild of Lucene's indexes, the server logs the excetion

Please confirm my doubts: 
- reason of crash
- when and where the server logs the stacktrace

Thanks a lot

**Comment by rdelangh** [comment]
@robfrank 

- reason of crash : the O/S crashed (paniced), not the OrientDB server process only
- no stacktrace from the process, since O/S was gone suddenly

After the reboot, the ODB server process was started, which started the index rebuilds. At the end of these rebuilds (when all of these indexes were rebuilt) the log messages were spawned .

**Comment by rdelangh** [comment]
@robfrank 
it happens also still when I manually create a new index:
```
...
2017-01-26 22:51:57:966 INFO  {db=cdrarch} --> 99.94% progress, 29,089,070 indexed so far (58,281 items/sec) [OIndexRebuildOutputListener]
2017-01-26 22:51:58:711 INFO  {db=cdrarch} --> OK, indexed 27,012,134 items in 994,128 ms [OIndexRebuildOutputListener]$ANSI{green {db=cdrarch}} Error on flushing Lucene index
java.lang.NullPointerException
$ANSI{green {db=cdrarch}} Error on flushing Lucene index
java.lang.NullPointerException
```

**Comment by maggiolo00** [comment]
Hi @rdelangh 

do you still need help on this or it has been resolved?

Thanks

**Comment by maggiolo00** [comment]
Hi @rdelangh 

any news about this issue?

Thanks

**Comment by rdelangh** [comment]
hi @maggiolo00 
That issue seems not to occur anymore with the versions which I run now (2.2.18, and recently 2.2.23)

-> can be closed.

**Comment by lvca** [comment]
Cool, closing it.
