### ISSUE TITLE
Load balancing not working with ROUND_ROBIN_CONNECT strategy

### ISSUE THREAD

**Issue by cowboy4mhell** [orientechnologies/orientdb#7110]
## OrientDB Version, operating system, or hardware.
v2.2.14

## Operating System
Linux

## Expected behavior and actual behavior
I have tried the steps given in Load Balancing section of http://orientdb.com/docs/2.2/Distributed-Configuration.html

`final OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/demo");
factory.setConnectionStrategy(OStorageRemote.CONNECTION_STRATEGY.ROUND_ROBIN_CONNECT.toString());
OrientGraphNoTx graph = factory.getNoTx();`

Requests are going only one of the nodes though I have provides multiple orientdb nodes in the remote server url. Load balancing is not happening. 

I tried to use a work around. I use the below code, as the connection strategy at Pool level is being used while creating connection, but still the same issue

`OPartitionedDatabasePool pool = new OPartitionedDatabasePool(url, userid, pass);
        pool.setProperty(PARAM_CONNECTION_STRATEGY.toLowerCase(),
            OStorageRemote.CONNECTION_STRATEGY.ROUND_ROBIN_CONNECT.toString());
OrientGraphFactory factory = new OrientGraphFactory(url, userid, pass, pool);`

## Steps to reproduce the problem

Debug the method OStorageRemote.getNextAvailableServerURL. This always returns the same node irrespective of the strategy being used for Load balancing.

**Comment by cowboy4mhell** [comment]
@lvca @tglman We are evaluating OrientDb. The use case is rule engine. We are using `traverse out()` in sql. Getting around 1000 qps on a 6 core machine. Memory settings are 4 GB heap, 7 GB of disk cache. And the data is much less than 1 GB.

We have a requirement of 3k qps. If we can use Round Robin for connections, then we can scale out horizontally. If you can fix this issue or provide a work for load balancing, we can go ahead with OrientDb.

**Comment by tglman** [comment]
Hi @cowboy4mhell,

I'm checking this.

Bye

**Comment by tglman** [comment]
hi @cowboy4mhell,

From what you say it seems that you are looking for the `ROUND_ROBIN_REQUEST` setting instead of `ROUND_ROBIN_CONNECT`, the difference  is that `ROUND_ROBIN_CONNECT` choose a server each new session is created (that in your case is limitated by the pool) instead `ROUND_ROBIN_REQUEST` each time you execute an remote operation (like a query).

Hope this help.

Regards

**Comment by cowboy4mhell** [comment]
hi @tglman 

I am looking for ROUND_ROBIN_CONNECT only. When the pool is initialised, db connections are made. For ex: with default pool settings, 4 partitions with min pool size of 2, there will be 8 db connections made. When db is opened, a session is created for that db. And then when network connection is made for the db, the url to be used is computed from the list of server urls. But for this computation, OStorageRemote uses the serverURLIndex in the session. To start with, this index is always -1 and so we end up connecting to the 1st url in the server list. 

I have made some changes in the client and tested. For ROUND_ROBIN_CONNECT, the serverURLIndex should be maintained in the OStorageRemote and not in the session. I can make changes an raise a pull request, if you want to see the change.

**Comment by tglman** [comment]
hi @cowboy4mhell,

It seems you are pretty forward in the investigation so yes if you can do a pull request this will speedup a lot the fix.

Regards

**Comment by devsprint** [comment]
are there any plans regarding fixing this issue?

**Comment by razvanjuravle** [comment]
Taking a look on the source code I discovered that using
  factory.setProperty("connectionStrategy", StorageRemote.CONNECTION_STRATEGY.ROUND_ROBIN_CONNECT.toString()); instead using the normal way as in the docs, managed to do the work, but from three master instances in a cluster only two are getting the load , the third doesn't receive any query. Hope it for the moment helps someone.

**Comment by tglman** [comment]
hi @cowboy4mhell, @razvanjuravle

I got that some time the value `setConnectionStrategy` was not managed well, i fixed that, it will be released 2.219, closing.
