### ISSUE TITLE
OrientDB User Details

### ISSUE THREAD

**Issue by spalempati** [orientechnologies/orientdb#7111]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[X ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [X ] Other, Ubuntu 

## Expected behavior and actual behavior
We are trying to produce a user report with the below details
User name, Status, Role name, Creation date and expiration date. 
User name and status are very much straight forward from ouser table. For role name we are able to pull the detials from orientdb studio but is there a way to get it from the command line?
Also we can't find any creation date or expiration date of a user in the orientDB. Do you have those fields at user level or do you have a plan to introduce those fields in the future?
## Steps to reproduce the problem
select name,status,roles from ouser  --> This output doesn't show the exact role name which appears in orole.

**Comment by lvca** [comment]
Try:

```
select name, status from ouser unwind roles
```

To activate a field `creation date` you could create it with default value = `date()`, but the expiration is not supported yet. Would you like to create an issue as enhancement to have them in a next release?
