### ISSUE TITLE
Possible race condition with Live Queries and initial values

### ISSUE THREAD

**Issue by mclark-newvistas** [orientechnologies/orientdb#7113]
## OrientDB Version, operating system, or hardware.

Latest, anything after release of #1227 (live queries)

### Actual

Live queries send changes to original data, which requires a separate query for the original data, introducing potential for race conditions. As a result one would subscribe to the live query, then query the database, then write client code to resolve any updates that came in while the initial dataset was returning. (#5101 could make resolving these changes somewhat easier).

### Expected

Either of:
- Documented explanation (at https://orientdb.com/docs/last/Live-Query.html - you might already have it somewhere I can't find it) of why race conditions are not possible given a certain query sequence/method (ie, changefeed then initial or initial then changefeed), so I can do them in the correct order.
- Operate as RethinkDB, which provides an option to "include initial values" with the changefeed - see https://www.rethinkdb.com/docs/changefeeds/javascript/#including-initial-values. This provides confidence that the database has resolved any "updates while query in progress" issues internally, or delayed updates while querying, whatever works.

**Comment by luigidellaquila** [comment]
Hi @mclark-newvistas 

As a first step we will update the docs with some information about this.
Basically, you should do the live query first and then the normal query, checking record versions to get the last version.

The "include initial values" option is not currently in the roadmap, but we can definitely consider it, so I'm flagging this issue as an enhancement

Thanks

Luigi

**Comment by mclark-newvistas** [comment]
Thank you - so for now it's "write client code to resolve, but with version numbers it should be pretty easy". Since I'd wrap it, this seems reasonable :).
