### ISSUE TITLE
SELECT expand(classes) FROM metadata:schema not returning all classes

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/orientdb#7114]
## OrientDB Version, operating system, or hardware.
Studio version : 2.2
OrientDB version : 2.2.15
Mac Book Pro

## Operating System
- [x] MacOSX

## Expected behavior and actual behavior

`SELECT expand(classes) FROM metadata:schema`

is returning about 20 classes but I have over 100. What is more strange is that I can see all classes in the Schema Manager page.

## Steps to reproduce the problem

Just run `SELECT expand(classes) FROM metadata:schema`

**Comment by igasparetto** [comment]
It works at ODB v: 2.2.13.

The problem is at 2.2.15.

**Comment by luigidellaquila** [comment]
Hi @igasparetto
Probably it's just a problem with Studio settings, by default it returns the first 20 elements if not differently configured. Maybe in v 2.2.13 you changed this default.

Please try to add a `LIMIT -1` to your query
```
SELECT expand(classes) FROM metadata:schema LIMIT -1
```

Thanks

Luigi

**Comment by igasparetto** [comment]
Grazie Luigi!

Indeed it was.

Case closed.

**Comment by luigidellaquila** [comment]
Closing then, thanks!

Luigi
