### ISSUE TITLE
ignoreErrors in JavaApi

### ISSUE THREAD

**Issue by dekan-kob** [orientechnologies/orientdb#7115]
I can to execute the following command in the console:
orientdb> set ignoreErrors true

But I have exception if to execute his in JavaApi using OCommandSQL..
```
db.command(new OCommandSQL("SET ignoreErrors true")).execute();
Caused by: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.SET ignoreErrors true
```

If I set the value of the property in the code, it doesn't work
```
db.setProperty("ignoreErrors", true);
db.command(new OCommandSQL("CREATE SEQUENCE test_seq TYPE ORDERED")).execute();
Caused by: com.orientechnologies.orient.core.exception.OSequenceException: Sequence 'TEST_SEQ' already exists
```

How to enable ignoreErrors in JavaAPI or sql code.

PS: I use embedded orient db. version 2.2.14.

**Comment by luigidellaquila** [comment]
Hi @dekan-kob 

`ignoreErrors` is a setting of OrientDB console, it's not available in the Java API.

If your goal is to create sequences only if they exist, I'm afraid you have to check it at application level

Thanks

Luigi
