### ISSUE TITLE
Call to uuid() returns base64 encoded Java object name

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#7116]
## OrientDB Version, operating system, or hardware.
v2.2.15

## Operating System
Linux

It seems that a call to `uuid()` returns a base64 encoded java object name. 

For instance,
`select uuid()` returns smth like `rO0ABXNyAA5qYXZhLnV0aWwuVVVJRLyZA/eYbYUvAgACSgAMbGVhc3RTaWdCaXRzSgALbW9zdFNpZ0JpdHN4cImuHII+7ojuLqk+WyT1Rw0=`. 

When decoded it gives `srjava.util.UUIDm/JleastSigBitsJmostSigBitsxp>.>[$G`

**Comment by maggiolo00** [comment]
hi @andreyvk 

i've checked and it's a bug. You can workaround it now with

```sql
select format("%s",uuid())
```

**Comment by andreyvk** [comment]
@maggiolo00 Thanks! Looking forward for the fix

**Comment by lvca** [comment]
@maggiolo00 What's the bug? Can anybody from the team fix it?

**Comment by maggiolo00** [comment]
@lvca 
IMHO the bug here it's that the uuid function returns the Java Objects

```
select uuid()
```

Is this the expected behaviour ?

**Comment by tglman** [comment]
Hi,

Yes this for me is definitely a bug, uuid() shoud return a string with the base64 rapresentation of the 16 bytes of the UUID, not a java object, an alternative solution could be just return a `byte[16]`.

Regards

**Comment by lvca** [comment]
Returning the string representation is the right thing to do from SQL.

**Comment by lvca** [comment]
Fixed in both 2.2.x and develop

**Comment by santo-it** [comment]
Noted in the [Release Notes](https://github.com/orientechnologies/orientdb/wiki/OrientDB-2.2-Release-Notes)
