### ISSUE TITLE
[Question] Arent multiple indices used to query data?

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#7124]
## OrientDB Version, operating system, or hardware.
v2.1.19

## Operating System
Linux

I was optimizing some queries today for 2.1.19. I used the **Explain** button from the Studio. We have several indices on that class of records. However, the studio always returned one element in the **involvedIndexes** column. Is that normal?

For instance, query contains `where status='blah' and externalId='foobar'`. The explanation shows **involvedIndexes** to be `["MyClass.status"]`. Shouldnt this be `["MyClass.status", "MyClass.externalId"]`?

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

The query optimizer in v2.1 can use only a single index at once, so it's the expected behavior

Thanks

Luigi

**Comment by smolinari** [comment]
Will this be improved in 3.0? Or does 2.2 possibly use multiple indices already?

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

in v 2.2 multiple indexes are already used for OR conditions, but not for AND conditions.
In V 3.0 there are further improvements, but there is no guarantee that two indexes are used for an AND condition, because in some cases it's more expensive than using only one.

Thanks

Luigi

**Comment by andreyvk** [comment]
I see. I just want to ask if this is a common practice for databases? Should I be using composite indexes then?

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

Some databases support index merge, some others don't. I strongly suggest you to use composite indexes

Thanks

Luigi

**Comment by andreyvk** [comment]
I have tried a composite index now. Seems even slower than using a single index. What i did was

`create index MyClass.status_externalId on MyClass (status, externalId) notunique`

Then I did 2 queries:

```
select from MyClass where @rid in (
    select rid from index:MyClass.status_externalId where key=["blah", "foobar"]
)

select from MyClass where status='blah' and externalId='foobar'
```

The second query was still faster than the fist one. Am I doing smth wrong with the index query? Btw, overall in the system queries are more complex. We are often searching on names and other attributes on top of "simple" indexes.

**Comment by luigidellaquila** [comment]
The second one should be OK. For the first one, I'd  change it as follows:

select expand(rid) from (
    select rid from index:MyClass.status_externalId where key=["blah", "foobar"]
)

Both are supposed to be very fast (according to result-set size of course)

Thanks

Luigi

**Comment by andreyvk** [comment]
The `expand(rid)` did the trick. Thanks! Now I need to think how to incorporate all that into a complex query :(

**Comment by smolinari** [comment]
Hey Luigi, 

I hope 3.0's new SQL engine will remove such ambiguities between `@rid` and `expand(rid)` too. 😄 

Scott
