### ISSUE TITLE
Fixes in JDBC DatabaseMetaData

### ISSUE THREAD

**Issue by dprutean** [orientechnologies/orientdb#7126]
We try to use the JDBC.DatabaseMetaData to discover database structure. For this we call getSchemas() getTables() getColumns() getIndexes(), etc.
After getSchemas() we receive an error 'The database instance is not set in the current thread'. Could you please set this directly in the JDBC driver ? Since we pass in the JDBC URL the database name, I think the driver should take care about it.
If we succeed to fix all this methods we will have a database design tool compatible with OrientDb ( the tool is dbschema.com ).

**Comment by robfrank** [comment]
Which orientDB version?

**Comment by dprutean** [comment]
Database and drivers 2.2.15, latest from the website. 

    On Thursday, January 26, 2017 6:02 PM, Roberto Franchini <notifications@github.com> wrote:
 

 Which orientDB version?—

**Comment by robfrank** [comment]
Ok, I guess you pass the resultSet and or the connection from one thread to another, e.g. from "backend thread" to the view. I'm improving this kind of use, I'll notify you when I've got something ready

**Comment by robfrank** [comment]
I've  done some improvement on thread safety. You can download the latest 2.2.16-SNAPSHOT jar and try it instead of the 2.2.15 you have.
I hope it could work fine. Let me know please

**Comment by dprutean** [comment]
Could you please paste here an URL to this file ? Not sure where to download it, thank you. 

    On Saturday, January 28, 2017 3:54 PM, Roberto Franchini <notifications@github.com> wrote:
 

 I've done some improvement on thread safety. You can download the latest 2.2.16-SNAPSHOT jar and try it instead of the 2.2.15 you have.
I hope it could work fine. Let me know please—

**Comment by robfrank** [comment]
Here's a valid link: https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-jdbc/2.2.16-SNAPSHOT/orientdb-jdbc-2.2.16-20170130.172309-22-all.jar

**Comment by robfrank** [comment]
@dprutean did you have time to test the SNAPSHOT?

**Comment by dprutean** [comment]
We still get this error in one place, but generally looks better. Now we have problems when calling DatabaseMetaData.getTables(). Always got 'TABLE' where the table name should be.Please check also getColumns(), getIndexes(), getImportedKeys(), getExportedKeys()Based on this information we may build a diagram out of schema.We used this script in OrientDb: create class Person extends V;create property Person.birthday date;
 create class Book extends V; create property Book.translation embeddedmap;
 create class Relation extends E; create property Relation.from date;
 create class Appear extends E; create property Appear.chapter embeddedlist integer
 insert into Person (last, first, birthday) values ('Vimes', 'Samuel', '1962-04-03'); insert into Person (last, first, birthday) values ('Ramkin', 'Sybil', '1969-09-06');
 insert into Book (name, translation) values ('Guards! Guards!', {'de':'Wachen! Wachen!', 'fr' : 'Au Guet!'} );
 create edge Relation from #11:0 to #11:1 set type='Married', from='1993-01-01';
create edge Appear from #11:0 to #13:0 set chapter={1,2,3,4,5,6}; 

    On Monday, January 30, 2017 10:45 AM, Roberto Franchini <notifications@github.com> wrote:
 

 Here's a valid link: https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-jdbc/2.2.16-SNAPSHOT/orientdb-jdbc-2.2.16-20170130.172309-22-all.jar—

**Comment by robfrank** [comment]
> We still get this error in one place, but generally looks better

which place? 

About the rest, I'll check all the calls. Note that some of these calls sometimes are hard to map to the inner OrientDB data model. I guess you had the same kind of problem with other noSQLs

**Comment by robfrank** [comment]
Could you share with me a snippet of code that shows errors and wrong metadata?
Because in my tests the TABLE_NAME attribute is filled with the class name in OrientDB.
Thanks in advance

**Comment by robfrank** [comment]
I just updated columns and indexes metadata mapping.  
please refer to the latest available snapshot:

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-jdbc/2.2.17-SNAPSHOT/

**Comment by dprutean** [comment]
For some reason I had to download again the latest version of OrientDb. Now I got an connection exception which I list below

Few more remarks beside this:
- Please use a default configuration with 250M or so, not 4G. I want to test your product, the notebook where I test has only 4G, I get memory exceptions, have to edit server.bat. Even there are few memory settings, MaxDirectMemorySize and HeapSize, which makes the stuff more confusing. It would be better to have a single global memory setting or at least put the first parameter in the file the most important setting. Make the product robust to run for the first time, when it will go in production each team will check how to increase the memory.

- Name your sample database 'SampleDb' or so, not 'GracefulDeadConcerts'. Is hard to remember this name and not intuitive.

com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:458)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:393)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:275)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1862)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1897)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1836)
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:336)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:263)
	at com.orientechnologies.orient.jdbc.OrientJdbcConnection.<init>(OrientJdbcConnection.java:80)
	at com.orientechnologies.orient.jdbc.OrientJdbcDriver.connect(OrientJdbcDriver.java:62)
	at com.wisecoders.dbs.rdbms.connect.a.a.d.r(SourceFile:57)
	at com.wisecoders.dbs.rdbms.connect.a.a.d.a(SourceFile:86)
	at com.wisecoders.dbs.rdbms.RdbImport.listSchemas(SourceFile:126)
	at com.wisecoders.dbs.layout.ui.editors.n.a(SourceFile:46)
	at com.wisecoders.dbs.layout.ui.editors.n.doInBackground(SourceFile:18)
	...

**Comment by robfrank** [comment]
Which versions are you using? 
I guess:
- OrientDb server 2.2.16
- OrientDB JDBC 2.2.17-SNAPSHOT

About demo database, we are working on a new demo db for 3.0.x, that is still in development. We don't know yet if the new demo db will be backported to  2.2.x
