### ISSUE TITLE
ETL speed issue

### ISSUE THREAD

**Issue by Dmirijs-Ozernovs** [orientechnologies/orientdb#7127]
## OrientDB Version
- v2.2.11
## Operating System
- Windows 7 Pro 64bit
## Hardware
- Laptop with i7-4510U, 8GB, SSD

I'm trying to import two csv files into an empty database. First I've used a small csv files (about 1000 vertices and 2000 edges) and the ETL process was done in few seconds. Now I'm running the same json on the bigger files (4 mio vertices and 10 mio edges), had no problems with importing vertices but the edges import is extremely slow (very similar to [https://github.com/orientechnologies/orientdb/issues/5508](url) )

My speed results:
**extracted 537 records (0 records/sec) - 537 records -> loaded 36 vertices (0 vertices/sec) Total time: 2155503ms [0 warnings, 0 errors]**

ETL command: _oetl.bat payment_big.json payment_big_create.json_
Below are my json files and the headers of the csv files (in xlsx format):

_payment_big.json_
`{
    "config": {
        "log": "info",
        "fileDirectory": "G:\orientdb-community-2.2.11\emp\datasets\\",
        "fileName": "pmts_big.csv"
    }
}`

_payment_big_create.json_
`{

    "begin": [
        { "let": { "name": "$filePath",
                   "expression": "$fileDirectory.append($fileName )"
                 }
        },
    ],

    "config": { "log": "info"},
    "source": { "file": { "path": "$filePath" } },
    "extractor": { "csv": { "ignoreEmptyLines": true,
                            "nullValue": "N/A"
                          }
                 },

    "transformers": [
            { "merge":  { "joinFieldName": "payer", "lookup": "client.name" } },
            { "edge":   { "class":         "transactions",
                          "joinFieldName": "receiver", "lookup": "client.name",
                          "direction":     "out",
                          "edgeFields": { "AmountEUR": "${input.AmountEUR}", "industry": "${input.TransIndustry}" },
                          "unresolvedLinkAction": "NOTHING"
                        }
            },
            { "field": { "fieldNames": ["payer", "receiver"], "operation": "remove" } }
        ],

    "loader": {
        "orientdb": {
            "dbURL": "remote:localhost/test_big",
	          "serverUser":"admin",
            "serverPassword":"admin",
            "dbType": "graph",
            "batchCommit": 1000,
            "useLightweightEdges": false,
            "classes": [
                { "name": "transactions",   "extends", "E" }
            ],
            "indexes": []
        }
    }
}
`

[example.xlsx](https://github.com/orientechnologies/orientdb/files/735416/example.xlsx)

**Comment by robfrank** [comment]
If this is a one-shot import, my suggestion is to use plocal access working embedded, then switch on the server.

**Comment by Dmirijs-Ozernovs** [comment]
Yes, this is one time import.
I have done this with plocal instead of remote - same result.
Added "parallel" - get three times more rows per tick but still very few vertices per second.

Maybe the problem with the index in the already imported vertices?

**Comment by Dmirijs-Ozernovs** [comment]
I have solved the problem by adding index to the joining field.
Get speed on the big file 10000 vertices/s for vertex import and 1500 vertices/s for edge import.
