### ISSUE TITLE
Unexpected behavior for creation/query of kebab-case property keys.

### ISSUE THREAD

**Issue by shooit** [orientechnologies/orientdb#7128]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .14[x]

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Background: I am writing a Clojure wrapper for OrientDB.  Clojure makes frequent use of kebab-case names.

I can create a vertex with a property in kebab-case
v1 = graph.addVertex(null, "string-key", "value")

But on query, the key must be escaped in backticks

graph.getVertices("string-key", "value") => empty collection
graph.getVertices("`string-key`", "value") => collection containing v1
graph.getVertices("string-key", null) => collection containing v1

I would expect the create and query interfaces to behave the same.  Either throwing an error when you try to create a property key that needs to be escaped, or handling the escaping on query.

## Steps to reproduce the problem
See above.

**Comment by tglman** [comment]
hi @shooit,

Thank you for reporting this, anyway the 2.1.x is out of support, so i would suggest you to plan a migration to 2.2.x, we will get this fixed in 2.2.x.

Regards

**Comment by shooit** [comment]
Oops, I am actually on 2.2.14.  The checkbox options confused me.  Thanks!

**Comment by tglman** [comment]
hi @shooit,

Gotcha, just fixed and pushed.

here is the commit: https://github.com/orientechnologies/orientdb/commit/7b0e11de9c0d6c0278523fbd2349e6ee26b77ed5 (just wrong issue id, but i cannot change it anymore ;( )

**Comment by shooit** [comment]
Thank you!

**Comment by santo-it** [comment]
Hi @shooit , thanks again for opening this issue

The fix has been noted in the [Release Notes](https://github.com/orientechnologies/orientdb/wiki/OrientDB-2.2-Release-Notes) page. You may want to test a [2.2.16-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.16-SNAPSHOT/) or wait for the official 2.2.16 release

I'm closing this now. In case you still experience problems, please let us know

Thanks,
