### ISSUE TITLE
Transaction lock should have record level but not storage level granularity  [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#713]
This is [Issue 713](http://code.google.com/p/orient/issues/detail?id=713) moved from a Google Code project.
Added by 2012-02-12T14:36:05.000Z by [lomakin....@gmail.com](http://code.google.com/u/110615750300902819680/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Release, uateam

### Original description

    OrientDB release - SVN r4821
    
    Currently during transaction commit exclusive storage lock is used, but such wide lock is unnecessary, it is enough to lock only records involved in transaction. 
    Row locks should use two different lock strategies.
    If transaction isolation level is READ_UNCOMMITTED - read locks should be used, for READ_COMMITTED isolation level - write locks should be used.
    Default isolation level will be READ_UNCOMMITTED.

**Comment by lvca** [comment]
Moved to 3.0

**Comment by laa** [comment]
not needed we have another issue for that case
