### ISSUE TITLE
Rollback of remote transaction is not work!

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#7133]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]
-v3.0 SNAPSHOT[ x] 
## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I try to rollback transaction in 'in-memory' database. State of transaction is:
[main] 07:51:18,184 DEBUG org.hibernate.ogm.datastore.orientdb.transaction.impl.OrientDBLocalTransactionCoordinator: transaction info: OTransactionOptimistic [id=2, status=BEGUN, recEntries=1, idxEntries=1]
Then I execute same code for 'rremote' database I get next string in log:
[main] 07:54:38,332 DEBUG org.hibernate.ogm.datastore.orientdb.transaction.impl.OrientDBLocalTransactionCoordinator: transaction info: OTransactionOptimistic [id=2, status=BEGUN, recEntries=0, idxEntries=0]
## Steps to reproduce the problem
public static void main(String[] args) {
        ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost/trtest").
                open("admin", "admin");
        db.getMetadata().reload();
        System.out.println(db.getMetadata().getFunctionLibrary().getFunctionNames());
        db.begin(OTransaction.TXTYPE.OPTIMISTIC);        
        OFunction func = db.getMetadata().getFunctionLibrary().getFunction("executeQuery".toUpperCase());
        HashMap<Object,Object> funcArgs = new HashMap<>();
        funcArgs.put("insertQuery", "insert into Poem content {\"name\":\"Wazaaaaa2\",\"id\":\"84d33e4f-7f43-4181-9a69-ebeb9e628ccc\"};");
        func.execute(funcArgs);
        System.out.println(db.getTransaction().toString());
        db.rollback(true);
        //db.commit(true);

        db.close();
    }
Code of function is:
return orient.getDatabase().command(insertQuery);

Result of execution of the Java example is rollback not work and You can see new record.

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

This is an expected behavior in 2.2.x, see http://orientdb.com/docs/2.2.x/Transactions.html#isolation

This will change in 3.0, as we are introducing remote transactions

Thanks

Luigi

**Comment by lvca** [comment]
Actually @schernolyas is trying 3.0

**Comment by luigidellaquila** [comment]
ouch, I didn't notice the flag... sorry, switching labels again

Luigi

**Comment by schernolyas** [comment]
Hi @lvca !

Okey.  I will test the feature

**Comment by tglman** [comment]
hi,

Yes is missing a bit, fixing it.

Regards

**Comment by tglman** [comment]
implemented, closing

**Comment by schernolyas** [comment]
HI @tglman !

Not work!

**Comment by schernolyas** [comment]
@tglman , before annoncing .... check your code!

**Comment by schernolyas** [comment]
@tglman  see to state of sesion:
2.OTransactionOptimistic [id=1, status=BEGUN, recEntries=0, idxEntries=0]

no changes in transaction :-(

**Comment by tglman** [comment]
Well before announcing i've done a basic test case : https://github.com/orientechnologies/orientdb/blob/14217affcf08b20eb58b76ca6d967ce883770371/server/src/test/java/com/orientechnologies/orient/server/tx/RemoteTransactionSupportTest.java#L77

the tests creates 2 records one before the transaction and one inside the transaction, change them in tx, with a server side query and count the result of changes, after rollback the transaction and check with a server side query that it actually have only the value before tx, and it works.

I'm going to add some tests on the status client side to see if there are problem in there.

Regards

**Comment by tglman** [comment]
Hi,

I included a test case also with the check of the status: https://github.com/orientechnologies/orientdb/blob/af71491e4e5daf2acf51c287e07ea3a8aa740ada/server/src/test/java/com/orientechnologies/orient/server/tx/RemoteTransactionSupportTest.java#L100 and all seems fine i run it and double checked the status server side and was fine also that, anyway that was covered by the unit tests on server side operations: https://github.com/orientechnologies/orientdb/blob/14217affcf08b20eb58b76ca6d967ce883770371/server/src/test/java/com/orientechnologies/orient/server/OConnetionExecutorTransactionTest.java#L244

So i'm not sure yet where is the problem, Regards

**Comment by schernolyas** [comment]
Hi @tglman !

Today, I get sources and retest. Problem not fixed!

**Comment by schernolyas** [comment]
@tglman I can send project for testing ... if you want

**Comment by tglman** [comment]
hi @schernolyas,

That will be really helpful.

Regards

**Comment by schernolyas** [comment]
Hi @tglman 

It is maven project. Command: mvn exec:java -Dexec.mainClass="ru.schernolyas.odocumenttest.App"

[odocumenttest.zip](https://github.com/orientechnologies/orientdb/files/840332/odocumenttest.zip)

**Comment by tglman** [comment]
hi @schernolyas,

I did run the test cases and did some fixes about it, more will come anyway, and I'm not sure if everything will land in the M1, for example we where thinking to deprecate the "execute" of the functions, in favour of execution by sql statement (ex: `select myFunc(:arg)` ), another important topic about this is that the command executed with the old `command(new OCommandSQL("...")).execute()` not support the transaction, and they may never support it, this method is going to be deprecated in the final, so use instead `db.command("...")`

Hope this help

**Comment by schernolyas** [comment]
Hi @tglman !

Do you mean this http://orientdb.com/docs/master/Java-Query-API.html ?

**Comment by schernolyas** [comment]
if yes .... @tglman  I will correct my example and check.

**Comment by tglman** [comment]
hi @schernolyas,

yes and have a look also to this: http://orientdb.com/docs/docs_review_30/java/Document-Database.html is our working in progress review of the documentation

**Comment by schernolyas** [comment]
Hi @tglman !

A lot of thanks!!!! I will analyse the article and test.

**Comment by schernolyas** [comment]
Hi @tglman !!!!

A lot of thanks!!!!! I test rollback of remote transaction.  It works correctly!!!!

**Comment by lvca** [comment]
@schernolyas thanks for helping us to fix this.

**Comment by schernolyas** [comment]
Hi @lvca !

No problem! Please fix problem with @RID during transaction :-)
