### ISSUE TITLE
OServerPlugin/OServerPluginAbstract before and after client events not triggered for HTTP connections

### ISSUE THREAD

**Issue by hanksieM** [orientechnologies/orientdb#7136]
## OrientDB Version, operating system, or hardware.
- v2.2.11

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
On binary connections these events are called for user actions,  eg: "select from", but when using the studio the http connection does not trigger any events.

## Steps to reproduce the problem
Followed the guide here http://orientdb.com/docs/2.2.x/Extend-Server.html and implemented all methods with simple log message statements.  Registered as-per guide in server.xml copied jar to lib/

**Comment by lvca** [comment]
That API is called only from binary protocol for binary connections. @tglman for v3.0 did you already think to any work here to be more coherent with API and protocols?

**Comment by lvca** [comment]
The way to intercept all the requests is to extend the class `ONetworkProtocolHttpDb` by defining your own. Example:

```
public class YourHttpProtocol extends ONetworkProtocolHttpDb {
  protected void beforeExecution() throws InterruptedException {
    return;
  }

  protected void afterExecution() throws InterruptedException {
    return;
  }
}
```

And then register it under `orientdb-server-config.xml` file:

```
<protocols>
  <protocol name="binary" implementation="com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary"/>
  <protocol name="http" implementation="your.protocol.impl.YourHttpProtocol"/>
</protocols>
```

**Comment by tglman** [comment]
hi,

We haven't modified anything in 3.0 in terms of plugin architecture, and there are not explicit plan on it.

Regards
