### ISSUE TITLE
how find RID with max(somefield) from group of documents?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7137]
## OrientDB Version, operating system, or hardware.
- v2.2.15

## Operating System
- [x] Linux

I don't find anything in the documentation that I can use for the following search:
- in our very big database, there is groups of related records based on combination of 8 properties
- each such group can contain from 2 till 40 related records with the same 8 properties
- for each such group, I need to identify the RID which contains the max value for one of the properties

For example, let say we search groups of records with same properties P1 and P2.
From any such group, I need to find the RID of the record that has the max value of property P3 among its fellows in the same group, so with same P1 and P2.

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I didn't try it, but it should work:

```
SELECT P1, P2, P3, @rid from V where [P1, P2, P3] IN (
  SELECT P1, P2, max(P3) as P3 from V GROUP BY P1, P2
)
```

The only problem here is that you could have multiple records with the same P1, P2, P3...

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Did this solve your problem? Can I close this issue?

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
sorry did not have possibility to try that one, please bare with me some more days.

**Comment by luigidellaquila** [comment]
No problem ;-)

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Any news on this? Is this issue still relevant?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I'm closing this issue, please feel free to re-open if you have an update

Thanks

Luigi
