### ISSUE TITLE
ALTER DATABASE MINIMUMCLUSTERS should be MAXIMUMCLUSTERS

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb#7139]
Hi,

Being that the command `ALTER DATABASE MINIMUMCLUSTERS` controls the maximum number of clusters ODB can create for each class, it would make more sense to label it

`MAXIMUM CLUSTERS`

Or is my thinking wrong?

Scott

**Comment by luigidellaquila** [comment]
Hi Scott,

Well, I think it's a matter of points of view, MINIMUMCLUSTERS refers to the fact that when you create a new class the DB automatically creates a minimum number of clusters for you, but then they can grow up, eg. if you start multiple nodes in distributed.

Luigi

**Comment by smolinari** [comment]
Hmm.....then both aren't really the best choice for the label, but I guess with that perspective, `MINIMUMCLUSTERS` is ok. 

Maybe something like `INITIALCLUSTERS` makes more sense?

Scott

**Comment by luigidellaquila** [comment]
yes, `INITIALCLUSTERS` makes definitely sense, maybe we can add it and deprecate `MINIMUMCLUSTERS` in 3.0 (and keep it for backward compatibility).
@lvca wdyt?

Luigi

**Comment by smolinari** [comment]
Oh, one other thing. Is there a global database server setting that can be set, instead of just a per database setting? In other words, the global setting would be the default, should a new database be created and if the user wants something different per database, they can override the default with `ALTER DATABASE INITIALCLUSTERS`? And that way, ODB can set the default to 8 or 16 (avoiding this issue here) and if there are less cores, the clusters=cores calculation is taken, and if the user sets the setting herself on a database, then that is the override. 

Did that make any sense? LOL! 😄 

Scott

**Comment by lvca** [comment]
The global setting is `class.minimumClusters`

**Comment by smolinari** [comment]
Ah. Cool. Thanks Luca.

Scott
