### ISSUE TITLE
Arrays are resetted if a link is insert

### ISSUE THREAD

**Issue by topofocus** [orientechnologies/orientdb#7141]
## OrientDB Version, operating system, or hardware.
- v2.2 5 - 15
## Operating System
- [x ] Linux

If an array is inserted in schemaless mode, its contents are erased if a single "RID" is added
## Steps to reproduce the problem
insert into property set property = [ 'a', 'b', 3 ]
--> #26:0
update #26:0 add property = 'k'
-->["a","b",3,"k"]
update #26:0 add property = #25:0
-->[ #25:0 ]
expected
-->["a","b",3,"k",#25:0]

further an additional 

update #26:0 add property = 'k'

does not modify the array

**Comment by luigidellaquila** [comment]
Hi @topofocus 

the problem seems to be in the JSON serialization, the record is correctly updated but when you retrieve it from HTTP (eg. from Studio) you get a wrong collection value.
If you use it from a binary driver (eg. Java) it should work fine

I'm trying to see how to fix it

Thanks

Luigi
