### ISSUE TITLE
select @rid into variable, cannot use that rid-value to SELECT from

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7142]
## Expected behavior  
Want to find a record and one of its properties, then update that same record and set a new value for this property using a calculation from the old value found.

I was thinking that this would work, testing with a SELECT instead of the UPDATE:
```
SELECT $returnedRecord[0].rid AS oldrid, $returnedRecord[0].CALL_DURATION AS oldduration, * FROM $returnedRecord[0].rid 
let returnedRecord = (
   select @rid AS rid, CALL_DURATION from myClass 
   WHERE keyfield1=keyvalue1 AND keyfield2=keyvalue2 AND ...
)
```
This does not return anything.

The subquery itself returns the record that we are looking for:
```
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "rid": "#105:9",
            "CALL_DURATION": "000112",
            "@fieldTypes": "rid=x"
        }
    ],
    "notification": "Query executed in 0.088 sec. Returned 1 record(s)"
}
```

**Comment by oger-p** [comment]
Hello,

I think you have a wrong syntax,

Can you try : 

```
SELECT $returnedRecord.rid[0] AS oldrid, $returnedRecord.CALL_DURATION[0] AS oldduration, $returnedRecord
let returnedRecord = (
   select @rid AS rid, CALL_DURATION from myClass 
   WHERE keyfield1=keyvalue1 AND keyfield2=keyvalue2 AND ...
)
```


Hope it helps.

**Comment by rdelangh** [comment]
@oger-p 

starting from this subquery: 
```
select @rid as rid, CALLDURATION from cdr_eno_20170122 WHERE ENV='prod' AND ORIGTERMMSCID='000A6B' AND CALLTRANSACTIONTYPE='01' AND SERVEDIMSI='202010901472521'
```
I get the following record as result:
```
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "rid": "#493:18631672",
            "CALLDURATION": "00023",
            "@fieldTypes": "rid=x"
        }
    ],
    "notification": "Query executed in 0.105 sec. Returned 1 record(s)"
}
```
none of the following combinations work to use the "rid" from that record as the @rid that I want to update (I run SELECT iso UPDATE, just for testing first that we retrieve the proper record via the 'rid' from the subquery):
```
SELECT * FROM $var[0].rid
let var = (select @rid as rid, CALLDURATION from cdr_eno_20170122 WHERE ENV='prod' AND ORIGTERMMSCID='000A6B' AND CALLTRANSACTIONTYPE='01' AND SERVEDIMSI='202010901472521')
```
gives no results
```
SELECT * FROM $var.rid[0]
let var = (select @rid as rid, CALLDURATION from myClass WHERE keyfield1='keyvalue1' AND keyfield2='keyvalue2')
```
gives no results

**Comment by oger-p** [comment]
You didn't do what i wrote.
You mustn't do : 

`SELECT * FROM $var.rid[0]`

but : 

`SELECT $var.rid[0]`

**Comment by rdelangh** [comment]
The result of that is the RID from the subquery:
```
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:2",
            "@version": 0,
            "$var": "#493:18631672",
            "@fieldTypes": "$var=x"
        }
    ],
    "notification": "Query executed in 0.104 sec. Returned 1 record(s)"
}
```

**Comment by oger-p** [comment]
I don't understand.

if your subquery :
`Select @rid as rid, CALLDURATION from cdr_eno_20170122 WHERE ENV='prod' AND ORIGTERMMSCID='000A6B' AND CALLTRANSACTIONTYPE='01' AND SERVEDIMSI='202010901472521'`

return this : 

```
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "rid": "#493:18631672",
            "CALLDURATION": "00023",
            "@fieldTypes": "rid=x"
        }
    ],
    "notification": "Query executed in 0.105 sec. Returned 1 record(s)"
}
```

then the querry :

```
SELECT $var.rid[0] AS oldrid, $var.CALL_DURATION[0] AS oldduration, $var
let var = (
select @rid as rid, CALLDURATION from cdr_eno_20170122 WHERE ENV='prod' AND ORIGTERMMSCID='000A6B' AND CALLTRANSACTIONTYPE='01' AND SERVEDIMSI='202010901472521'
)
```

must return :

```
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:2",
            "@version": 0,
            "oldrid": "#493:1863167",
            "oldduration": "00023",
            "$returnedRecord": [
                {
                    "@type": "d",
                    "@rid": "#-2:0",
                    "@version": 0,
                    "rid": "#493:1863167",
                    "CALL_DURATION": "00023",
                    "@fieldTypes": "rid=x"
                }
            ],
            "@fieldTypes": "oldrid=x,$returnedRecord=z"
        }
    ],
    "notification": "Query executed in 0.076 sec. Returned 1 record(s)"
}
```

Is it what you want?

**Comment by rdelangh** [comment]
noop  ;-)
The goal is (see initial post) to use the @rid that comes out of the subquery, in an UPDATE statement which makes use of the variable that collected that @rid from the subquery:

```
UPDATE $var[0].rid SET somefield = newvalue
LET var = (subquery)
```

**Comment by oger-p** [comment]
Oh ok. Sorry then...
I don't think it works... It's maybe a bug.

**Comment by rdelangh** [comment]
hi ODB-gurus,
any feedback on this question, please?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

The problem here is that the target (`FROM $returnedRecord[0].rid`) is evaluated before the LET statement, this is why it doesn't work.

I suggest you to use a batch script for this

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
hi Luigi, I found a working script method, after several days of trial-and-error to find the correct syntax.
Better (again...) documentation would have helped a lot.
Thx for your feedbacks anyhow.

Issue can be closed.

**Comment by luigidellaquila** [comment]
Great, closing.
In this case, IMHO also a more explicative execution planner would help. I hope in 3.0 it will be much easier to figure out this kind of scenarios

Thanks

Luigi

**Comment by nagaraja-upadyaya** [comment]
Hi @rdelangh or Luigi ,  

I have a similar requirement and facing performance issues in Orient DB while executing Gremlin, SELECT or Update statements against a vertex whose property value is equal to property value of an incoming vertex. Basically, I am porting an application from Neo4j to Orient DB.  In Neo4j, we used MATCH statement with SET clause which was easy and executes in seconds.  But in in Orient DB I am running Memory, CPU and response time issues.

If possible, please share sample for the same or help me in finding a solution to this problem in Orient DB.

Thank you in advance :)

Best Regards,
Nagaraj
