### ISSUE TITLE
OProperty Constraints are not enforced on OrientElement

### ISSUE THREAD

**Issue by shooit** [orientechnologies/orientdb#7143]
## Expected behavior  
I am trying to set property constraints on elements in the graph.  The constraints should throw an error when they are not followed.

## Actual behavior  
Property constraints are ignored, and elements can be created that do not follow the constraints.

## Steps to reproduce  

`
public class OrientPropertyTest {

    private String randomLocation() {
        return "memory:test" + new Random().nextInt();
    }

    @Test(expected=OValidationException.class)
    public void testPropertyMax() {
        String location = randomLocation();
        OrientGraphNoTx graphNoTx = new OrientGraphNoTx(location);
        OrientVertexType testType = graphNoTx.createVertexType("Test");
        OProperty prop = testType.createProperty("name", OType.STRING).setMax("3");
        graphNoTx.shutdown();

        Assert.assertEquals(prop.getMax(), "3"); //this one passes

        OrientGraph graph = new OrientGraph(location);
        try {
            graph.addVertex("class:Test", "name", "Sam");
            graph.addVertex("class:Test", "name", "Henry"); //this should throw an exception
            graph.commit();
        } finally {
            graph.drop();
        }
    }

    @Test(expected=OValidationException.class)
    public void testPropertyMin() {
        String location = randomLocation();
        OrientGraphNoTx graphNoTx = new OrientGraphNoTx(location);
        OrientVertexType testType = graphNoTx.createVertexType("Test");
        OProperty prop = testType.createProperty("name", OType.STRING).setMin("4");
        graphNoTx.shutdown();

        Assert.assertEquals(prop.getMin(), "4"); //this one passes

        OrientGraph graph = new OrientGraph(location);
        try {
            graph.addVertex("class:Test", "name", "Sam"); //this should throw an exception
            graph.addVertex("class:Test", "name", "Henry");

            graph.commit();

        } finally {
            graph.drop();
        }
    }

    @Test(expected=OValidationException.class)
    public void testPropertyRegexp() {
        String location = randomLocation();
        OrientGraphNoTx graphNoTx = new OrientGraphNoTx(location);
        OrientVertexType testType = graphNoTx.createVertexType("Test");
        OProperty prop = testType.createProperty("gender", OType.STRING).setRegexp("[M|F]");
        graphNoTx.shutdown();

        Assert.assertEquals(prop.getRegexp(), "[M|F]"); //this one passes

        OrientGraph graph = new OrientGraph(location);
        try {
            graph.addVertex("class:Test", "gender", "A"); //this should throw an exception
            graph.addVertex("class:Test", "gender", "M");

            graph.commit();

        } finally {
            graph.drop();
        }
    }
}
`

**Comment by lvca** [comment]
@shooit why did you close it?

**Comment by shooit** [comment]
Bug in the rest code was causing the failure.

**Comment by lvca** [comment]
Ok, thanks.
