### ISSUE TITLE
EXPLAIN first runs the possibly bad query, then informs that it was a bad query

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7147]
### OrientDB Version: all

When prefixing an SQL query statement with EXPLAIN, it seems that the query is first executed, and after that the information is displayed how the query was executed (like if an index was used or not).

This misses the goal of EXPLAIN a bit, I think: when we are not sure if a certain query is correctly composed in order to obtain best performance (like being sure that a/the good index is used), we do not want that potentially bad query to be executed first before being informed that is was badly composed: a bad query can
- take an awful lot of time (hours!)
- kill the server engine(s) with Out-Of-Memory situations

-> is there no way to display **upfront** the analysis of ODB engine, about how the query **would** be performed?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I agree 100% with this argument, the EXPLAIN in current version (2.2.x) is just a way to have stats on how the query **was** executed.
In v 3.0 we completely changed this approach, now the EXPLAIN returns the execution plan of the query in a structured and descriptive way, ie. all the basic steps that the query performs to calculate the result (fetch from cluster or from index, filter, calculate projections, aggregate, unwind and so on)

This is already implemented in develop branch, but I'll keep this issue open, flagged as an enhancement, until 3.0 is officially released (or at least until this feature is available in an official milestone)

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
super! Eager to hear when a first, stable version of 3.0 is available to work with...

**Comment by saeedtabrizi** [comment]
@luigidellaquila that's a good news .

**Comment by luigidellaquila** [comment]
Hi guys,

I think I can close this issue, as this feature is already implemented in OrientDB 3.0M1, see:

http://orientdb.com/docs/3.0.x/sql/SQL-Explain.html

http://orientdb.com/docs/3.0.x/sql/SQL-Profile.html


Thanks!

Luigi
