### ISSUE TITLE
avoid using zip file to replicate a database to new server node

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7148]
### OrientDB Version: all

(spin-off from #6666)
When a new server node tries to join an existing group of servers, a copy of the databases is taken, via a zip file under "/tmp/orientdb" ; such ZIP file, in case of truely "big" databases, will consequently also be huge.
-> implement a possibility to avoid that the database copy is taken via such ZIP file

**Comment by lvca** [comment]
The zip works in streaming, so it's very efficient. In the case of huge database you absolutely want it's zipped to transfer a fraction of the data.
