### ISSUE TITLE
drop of large class gives Error during saving of record with rid #0:1

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7152]
### OS: Ubuntu-16 

- Started ODB on a single server, with the "dserver.sh" script, no 2nd server node is active so it runs entirely standalone.
- opened "console.sh" connection to our dbase
- dropped a small class "tmp1" with 8827 records, no problem
- dropped a tiny class "rob_test" with 1 record, no problem
- dropped a big class "mds_std_icx" with 350125677 records, fails with
```

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #0:1
        DB name="cdrarch"
        DB name="cdrarch"

Error: com.orientechnologies.orient.core.exception.OStorageException: Error in data flush background thread, please restart database and send full stack trace inside of bug report
        DB name="cdrarch"

Error: java.lang.NullPointerException
```

Server has 128GB RAM.
Parameters in "server.sh" are:  -Xms1G -Xmx10G  -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dstorage.openFiles.limit=1024 -Denvironment.dumpCfgAtStartup=true -Dstorage.diskCache.bufferSize=32000 -Dmemory.chunk.size=33554432

**Comment by rdelangh** [comment]
After a shutdown and restart of the server, the database seems in a mess:

- before that "drop class mds_std_icx" attempt, the output from the "classes" command showed this class with its clusters:
```
|81  |350125677|         |mds_st...|mds_std_icx(393),mds_std_icx_1(394),mds_std_icx_2(395),mds_std_icx_3(396),mds_std_icx_4(397),mds_std_icx_5(398)...
```

- but after that error, the shutdown and the restart, the output from the "classes" command now shows a messy list of clusters for this class "mds_std_icx":
```
|81  |164344526|         |mds_st...|null(393),null(394),null(395),null(396),null(397),null(398),null(399),null(400),null(401),null(402),null(403),n...
```

**Comment by laa** [comment]
@rdelangh could you provide full stack trace from server log not only NPE exception itself ?

**Comment by laa** [comment]
@rdelangh if we would not actively discuss another issue I would think that you forget about me )) Could you provide additional information about that issue ?

**Comment by rdelangh** [comment]
@laa ;-)
- I dropped succesfully another big class of 380M documents, no error
- when I try to drop this class "mds_std_icx", the error messages are:
From "console.sh" : 
```
orientdb {db=cdrarch}> drop class mds_std_icx

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #0:1
        DB name="cdrarch"
        DB name="cdrarch"

Error: com.orientechnologies.orient.core.exception.OStorageException: Error in data flush background thread, please restart database and send full stack trace inside of bug report
        DB name="cdrarch"

Error: java.lang.NullPointerException
```

In server logs:
```
 [OHazelcastPlugin]Error during fuzzy checkpoint
java.lang.NullPointerException
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.release(OClosableLinkedContainer.java:300)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$PeriodicalFuzzyCheckpointTask.run(OWOWCache.java:1784)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Note: this single server was started with "dserver.sh", altough no other servers have joined its 'group'

**Comment by laa** [comment]
Fixed @rdelangh could you try to build latest 2.2.x branch and check it ?

**Comment by rdelangh** [comment]
ok, I installed snapshot version "orientdb-community-2.2.17-20170213.153756-17", and no more problems to drop these classes.

thx !
(issue can be closed)
