### ISSUE TITLE
huge files default.pcl

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7153]
### OrientDB Version: 2.2.x

I noticed that in each of our big database directories, a file "default.pcl" exists which has a huge size:

```
databases$ du -sh *
7.2M    GratefulDeadConcerts
2.2M    OSystem
638G    cdrarch
548G    mobile
24G     navi
databases$ ls -lh */default.pcl
-rw-rw-r-- 1 orientdb orientdb  65K Jun 13  2016 GratefulDeadConcerts/default.pcl
-rw-rw-r-- 1 orientdb orientdb  65K Jun 15  2016 OSystem/default.pcl
-rw-rw-r-- 1 orientdb orientdb  85G Feb  5 00:16 cdrarch/default.pcl
-rw-rw-r-- 1 orientdb orientdb 201G Feb  5 00:03 mobile/default.pcl
-rw-r--r-- 1 orientdb orientdb 129K Nov 24 11:42 navi/default.pcl
```

For the case of "mobile", that file is almost half of the total size of the database directory!

**Comment by laa** [comment]
@lvca could you assign to storage team otherwise issues are lost. @rdelangh how much records are contained in default cluster? Could you open database in embedded mode and call following code:

```
OStorage storage = database.getStorage();
OCluster cluster = storage.getClusterByName("default");
System.out.println(((OPaginatedCluster)cluster).getRecordsSize());
```

**Comment by rdelangh** [comment]
@laa
- number of records in "default.pcl":
```
orientdb {db=cdrarch}> select count(*) FROM CLUSTER:default
+----+--------+
|#   |count   |
+----+--------+
|0   |36330580|
+----+--------+
orientdb {db=mobile}> select count(*) FROM CLUSTER:default
+----+--------+
|#   |count   |
+----+--------+
|0   |94423344|
+----+--------+
```
- how is a database opened in 'embedded mode' ? Mind you that we are not coding with Java

Some of the contents of these clusters are:
```
orientdb {db=cdrarch}> select * FROM CLUSTER:default LIMIT 5
+----+----+--------+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+
|#   |@RID|name    |type|globalId|mandatory|readonly|notNull|defaultValue|min |max |customFields|collate|description|
+----+----+--------+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+
|0   |#3:0|PRT_DATE|19  |196     |true     |false   |false  |            |    |    |            |default|           |
|1   |#3:1|QC      |7   |197     |true     |false   |false  |            |    |    |            |default|           |
|2   |#3:2|UNIQ_KEY|7   |198     |true     |false   |false  |            |    |    |            |default|           |
|3   |#3:3|CDR_NR  |1   |199     |true     |false   |false  |            |    |    |            |default|           |
|4   |#3:4|XDR_NR  |1   |200     |true     |false   |false  |            |    |    |            |default|           |
+----+----+--------+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+
orientdb {db=mobile}> select * FROM CLUSTER:default LIMIT 5
+----+----+-------------+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+
|#   |@RID|name         |type|globalId|mandatory|readonly|notNull|defaultValue|min |max |customFields|collate|description|
+----+----+-------------+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+
|0   |#3:0|ENV          |7   |23      |true     |false   |false  |            |    |    |            |default|           |
|1   |#3:1|PRT_DATE     |6   |24      |true     |false   |false  |            |    |    |            |default|           |
|2   |#3:2|FILENAME     |7   |25      |true     |false   |false  |            |    |    |            |default|           |
|3   |#3:3|RECORDTYPE   |7   |26      |true     |false   |false  |            |    |    |            |default|           |
|4   |#3:4|RECORDVERSION|7   |27      |true     |false   |false  |            |    |    |            |default|           |
+----+----+-------------+----+--------+---------+--------+-------+------------+----+----+------------+-------+-----------+
```
This looks like definitions of the properties of the classes.

**Comment by laa** [comment]
@rdelangh how much indexes and classes do you have? We suppose that we have an issue with metadata management which we write again and again in default cluster but to identify which metadata we solve repeatedly we need to read records from default cluster we can not read them all obviously so that we will read several records above a limit of the amount of classes and indexes.

**Comment by rdelangh** [comment]
@laa 
- in dbase "cdrarch", there are 39 classes with 135 indexes in total, referring to some 630M records
- in dbase "mobile", there are 24 classes with 25 indexes in total, referring to some 825M records

If that issues can be resolved (= writing less of such metadata in the "default" clusters), then what remains is : how can the current cluster files "default.pcl" be reduced in size? At this moment, they represent a huge part of the total database size.

**Comment by laa** [comment]
@rdelangh could you make then ```select * from cluster:default limit  500``` for each database and send the result to me? About your question it depends on metadata are stored but I suppose that is possible.

**Comment by rdelangh** [comment]
@laa 
1) the requested SELECT is in the attached file "default-pcl.txt" for both dbases "cdrarch" resp "mobile"
[default-pcl.txt](https://github.com/orientechnologies/orientdb/files/763250/default-pcl.txt)
2) can you pls describe how we could reduce the size of the "default.pcl" files/cluster?

**Comment by laa** [comment]
@rdelangh could you make also following request select * from cluster:internal limit 500.
Also could you answer question, how many times did you rebuild indexes from crash on this database ?

**Comment by laa** [comment]
@rdelangh issue which you have that somewhere in the system at some circumstances index definitions by mistake are stored inside of defalut cluster. One of idea is that is done during a system crash. But to check it I suggest you to do following. Truncate defalut cluster (it is absolutely safe) then run a system during a week and check what is cluster size before and after system crash and how cluster size changes during normal execution. Could you truncate cluster now ?

**Comment by laa** [comment]
@rdelangh if cluster grows during normal execution, not after crash , then I will send you build with small patch which will track reason of addition of records in this cluster. Using this approach we resolve this issue once and forever.

**Comment by rdelangh** [comment]
@laa thx for the feedback, mostly appreciated!
Please confirm that I can run a "TRUNCATE CLUSTER default" while the server is busy inserting new records. I am scared to make our big dbases corrupted...

**Comment by laa** [comment]
@rdelangh if you do not store documents with classes, truncation of a defalut cluster is not a problem. This is not durable operation, I mean if you crush server default cluster may be corrupted but you have garbage in a cluster so that should not be a problem for you.

**Comment by laa** [comment]
@rdelangh hold on for second

**Comment by laa** [comment]
@rdelangh better to do following do not truncate those records for a while, I will create you patch which is based on 2.2.x which you should use to replace current distribution

**Comment by laa** [comment]
I will put check there if you try to store data to default cluster exception will be thrown and full path from the start of the query till the moment when it will be stored to default cluster will be logged.  Will be able to track such exceptions ?

**Comment by laa** [comment]
reassigned to @tglman because it is schema management issue, not storage related issue

**Comment by rdelangh** [comment]
@laa, @tglman 
ok, I will wait for that patch; please confirm then in which exact snapshot it will be contained.

**Comment by laa** [comment]
@rdelangh Here you are https://drive.google.com/file/d/0B2oZq2xVp841Z08xeWxOR0hCcDA/view?usp=sharing , replace the server and run your tests  for a while to check that  nothing is writing to defautl cluster.

**Comment by laa** [comment]
moved issue to @tglman

**Comment by rdelangh** [comment]
@laa 
hi Andrey, about to give this a try: is that patch included in the snapshot 2.2.17 of  Feb-13 , "orientdb-community-2.2.17-20170213.153756-17.tar.gz" ?
Or shall I use a more recent snapshot version?

**Comment by laa** [comment]
Hi @rdelangh , we can not include such patch in an update, because in such case for some uses cases it will be  impossible to work with database so it present as separate build.

**Comment by rdelangh** [comment]
@laa ok, I get your point.
Since this is a big (!), live database, will there be any risk on corruption when that exception is happening when something gets written in the "default" cluster?
Just trying to assess our risk of running with that specially patched version.

**Comment by rdelangh** [comment]
and: I click on that link to "drive.google.com", but nothing gets displayed from that page... Is that link still valid?

**Comment by laa** [comment]
@rdelangh if an exception happens all data modification will be reverted to an initial state the so risk is minimal.  The dink should be valid I checked it.

**Comment by rdelangh** [comment]
@laa the build that you dropped at Google is not working on UNIX because the shell scripts (such as "bin/server.sh") does contain Carriage-Return (CR) characters at the end of each line, instead of a plain Linefeed (LF) character.
This is the DOS-style of line-ends (CRLF), which breaks shell scripts. It should be the UNIX-style of line-end (LF only).
-> can you please make a new build with your patch to capture writes to the default clusters?

**Comment by laa** [comment]
@rdelangh I can not do that because I have windows @tglman could you make such build I suppose that is not a complex thing

**Comment by tglman** [comment]
hi @rdelangh,

Just to recup a bit, the default cluster is the cluster where the documents without a class are saved, historically we had some issue mainly in 2.0.x and 2.1.x that in some cases some garbage data was going to be saved in the default cluster, so if in your software you never save documents without a class all the data in the default.cpl is actually garbage and it can be thrown away, but just to be sure is that the case we are sending you this distribution:https://drive.google.com/file/d/0B5nXSvhRheGUb2xJYWtHdHlQM2M/view?usp=sharing that is the 2.2.17 with this additional commit:https://github.com/orientechnologies/orientdb/commit/912e78354b9fc6e59a96a59dd34d2f9880eaa567 that log in the console all the attempt to save or update a record in the default cluster with log level Error, so if you run your system with this distribution you can monitor any operation on the default cluster and be sure that there is no application data in there.

I opted for a log instead of the exception as early proposed to not create any application error in case of default cluster operation were done.

If you have a test environment I would soggest to do this test before in there, it can happen that you get some verbose logging.

As well as soon as you deploy this distribution you need to check the log closely, and after a bit report to us the logs you got.

After this double check we can guide you to drop the data in the default cluster.

Regards

**Comment by rdelangh** [comment]
hi @tglman 
sorry but we never managed to give this special distribution with the commit "912e783" a try, and meanwhile we had to upgrade to version 2.2.18 because we hit crucial problems with 2.2.17
Can I please ask you to build a similar distribution from 2.2.18 with that same change for the logging in the console of the attempts to save or update a record in the default cluster ?

I can not do the check with a separate test environment, because the activity and the input files can only be loaded once (i.e. in production environment).
But I can limit the number of files that get presented to the database, so any impact from the extra logging (if any) from your change can be kept under control.

**Comment by tglman** [comment]
hi @rdelangh,

2.2.18 is not yet released so i guess you are using the last 2.2.x branch,here it is the patched version of the 2.2.x branch https://drive.google.com/a/orientdb.com/file/d/0B5nXSvhRheGUeFd0MjR5TDJCa3M/view?usp=sharing

Regards

**Comment by rdelangh** [comment]
hi @tglman 
surely we are running 2.2.18 : 
OrientDB 2.2.18-SNAPSHOT (build UNKNOWN@rf31f2e10de758cbdef4cee27451b4065b94d9ce2)

-> ok, I will use that patched version from you, thanks a lot!

**Comment by tglman** [comment]
hi @rdelangh,

Did you updated to the last version, is the problem fixed for you ?

Regards

**Comment by rdelangh** [comment]
@tglman 
I have split our two databases now on one physical server for each database;
- on the server running dbase "mobile", OrientDB software version 2.2.23 is running, and the file "mobile/default.pcl" has still a very large size:
```
-rw-rw-r-- 1 orientdb orientdb 263131235328 Jul  4 14:59 ./mobile/default.pcl
```
- on the server running dbase "cdrarch", OrientDB software version 2.2.18 snapshot of 2017-03-04 is running, and the file "cdrarch/default.pcl" has size:
```
-rw-rw-r-- 1 orientdb orientdb 116460684288 Jul  2 03:35 databases/cdrarch/default.pcl
```

So in summary it looks like this issue has not disappeared yet.

**Comment by laa** [comment]
@rdelangh did you use patched version on a server? Have you seen any messages into the log?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

This problem was due to a bug in the management of schema properties, so that some metadata ended up in the default cluster.

It was fixed in v 2.2.29 or 30

As a side note, in V 3.0 it won't be possible to save records in the default cluster implicitly. The default cluster is still there, but to use it you explicitly have to do an `INSERT INTO cluster:default` or a `doc.save("default")`

Thanks

Luigi

**Comment by rdelangh** [comment]
hello @luigidellaquila 
many thanks for the follow-up of this old issue !
We will upgrade now to v2.2.30, so avoid that issue in the future.

**Comment by rdelangh** [comment]
@luigidellaquila 
in one of the instances, we run already v2.2.30, but its "default.pcl" file is about 92GB size (...) but it has not changed anymore since we upgraded to v2.2.30
-> can we remove, or truncate that file without any harm (while the server is brought down) ?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Yes, it should be safe, a `TRUNCATE CLUSTER default` should do the trick.

Of course, I strongly suggest you to do a backup before you do this kind of operations

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
did that:
```
orientdb {db=mobile}> TRUNCATE CLUSTER default
Truncated
Error: java.util.IllegalFormatConversionException: d != java.lang.Boolean
```
Despite this error message (clash with some cluster-naming convention?), the file seems truncated indeed:
```
$ ls -l default.pcl
-rw-rw-r-- 1 orientdb orientdb 66560 Nov 21 19:02 default.pcl
```
(maybe you could fix this cosmetic bug)

**Comment by rdelangh** [comment]
And now, no new connection to the database is possible anymore:
```
orientdb> CONNECT remote:localhost/mobile admin ourpwd
Connecting to database [remote:localhost/mobile] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on creation of shared resource
        DB name="mobile"
        DB name="mobile"
Error: java.lang.NullPointerException
orientdb> desc cdr_eno_20171119
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Database 'null' is closed
```
So I reverted the database to its backup snapshot (= situation before the truncate of cluster "default"), and restarted the dbase again.
-> this TRUNCATE seems not so safe after all ... Any other option ?

**Comment by laa** [comment]
@rdelangh TRUNCATE is definitely unsafe, please do not use it. Use bulk delete instead.

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I guess the only other option is a plain DELETE. 

Thanks

Luigi

**Comment by rdelangh** [comment]
even a plain DELETE is not safe:
```
Connecting to database [remote:localhost/cdrarch] with user 'admin'...OK
orientdb {db=cdrarch}> select count(*) from CLUSTER:default
+----+--------+
|#   |count   |
+----+--------+
|0   |93840647|
+----+--------+
1 item(s) found. Query executed in 0.005 sec(s).
orientdb {db=cdrarch}> delete from CLUSTER:default limit 1000
Delete record(s) '1000' in 0.274000 sec(s).
orientdb {db=cdrarch}> select count(*) from CLUSTER:default
+----+--------+
|#   |count   |
+----+--------+
|0   |93839647|
+----+--------+
1 item(s) found. Query executed in 0.004 sec(s).
orientdb {db=cdrarch}> delete from CLUSTER:default limit 10000
Delete record(s) '10000' in 0.687000 sec(s).
Error: java.lang.NullPointerException
...
```
-> I hope that, with a restart of the dbase, this error gets resolved... :-(

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

This makes me think that in the default cluster you have something else that you actually need, but it's really hard to say what...

**Comment by rdelangh** [comment]
@luigidellaquila , @laa 
That 'something else' seems to be related to client connections, because after I did those DELETEs and got the errors, no new client connection could be established anymore. I had to stop and restart the server to get this situation resolved, now it is possible again to connect to the database.
-> can the contents of this default cluster be inspected to identify unexpected data?

**Comment by luigidellaquila** [comment]
let's say that *all* the data in the default cluster is unexpected...
The point is to understand what it exactly is. If it's hundreds of records, then it's easy to do it manually, but when it's more than 90GB it gets pretty hard. 
You can try to write a script to check the record structure, eg. all the different "types" of records based on their attribute names, maybe you will find something significant

Thanks

Luigi

**Comment by rdelangh** [comment]
dunnow if this was a cause, but I can no longer open that database:
1) the server starts, I have configured following parameters:
```
java -d64 -server -Xms18G -Xmn5G -Xmx28G -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=64m -XX:CompressedClassSpaceSize=12m -XX:-UseAdaptiveSizePolicy -XX:+UseCompressedOops -Djna.nosys=true -XX:MaxDirectMemorySize=512g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dstorage.openFiles.limit=1024 -Denvironment.dumpCfgAtStartup=true -Dquery.parallelAuto=true -Dquery.parallelMinimumRecords=10000 -Dquery.parallelResultQueueSize=200000 -Dstorage.wal.maxSize=51200 -XX:+PrintGCID -XX:+PrintGCDetails -XX:+PrintTenuringDistribution -XX:+UseParallelOldGC -XX:+PrintGCApplicationStoppedTime -Xloggc:/log/gc.log -Dstorage.diskCache.bufferSize=64000 -Dmemory.chunk.size=33554432 -Djava.util.logging.manager=com.orientechnologies.common.log.OLogManager$ShutdownLogManager -Djava.util.logging.config.file=/opt/orientdb/orientdb-community-2.2.31-SNAPSHOT/config/orientdb-server-log.properties -Dorientdb.config.file=/opt/orientdb/orientdb-community-2.2.31-SNAPSHOT/config/orientdb-server-config.xml -Dorientdb.www.path=/opt/orientdb/orientdb-community-2.2.31-SNAPSHOT/www -Dorientdb.build.number=branches/2-2-x.15993v/workspace/distribution@r97f1131baee11213c40e5f55b150416d31ff7412; 2017-11-20 16:40:56+0000 -cp /opt/orientdb/orientdb-community-2.2.31-SNAPSHOT/lib/orientdb-server-2.2.31-SNAPSHOT.jar:/opt/orientdb/orientdb-community-2.2.31-SNAPSHOT/lib/*:/opt/orientdb/orientdb-community-2.2.31-SNAPSHOT/plugins/* com.orientechnologies.orient.server.OServerMain
```
2) from the client console, I attempt to connect, but this fails:
```
orientdb> CONNECT remote:localhost/cdrarch admin ourpwd
Disconnecting from the database [null]...OK
Connecting to database [remote:localhost/cdrarch] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on creation of shared resource
        DB name="cdrarch"
        DB name="cdrarch"
Error: java.lang.NullPointerException
```
3) the operating system is not out of resources:
```
$ vmstat 4

procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  0  32932 38943464 140008 9271872    0    0    70    44    0    0  3  0 97  0  0
 0  0  32932 38943176 140008 9271880    0    0     0     0  185  412  0  0 100  0  0
 0  0  32932 38943144 140008 9271912    0    0     0   707  749 1299  0  0 100  0  0
```
4) the ODB server process has following stats:
```
$ /usr/lib/jvm/jdk1.8.0_92/bin/jstat -gc -h10 39712 10s
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
655360.0 655360.0  0.0   655344.7 3932160.0 466354.2 13631488.0  272995.3  27648.0 26806.3 3328.0 3046.6      1    0.513   0      0.000    0.513
655360.0 655360.0  0.0   655344.7 3932160.0 466354.2 13631488.0  272995.3  27648.0 26806.3 3328.0 3046.6      1    0.513   0      0.000    0.513
655360.0 655360.0  0.0   655344.7 3932160.0 472907.8 13631488.0  272995.3  27648.0 26806.3 3328.0 3046.6      1    0.513   0      0.000    0.513
655360.0 655360.0  0.0   655344.7 3932160.0 472907.8 13631488.0  272995.3  27648.0 26806.3 3328.0 3046.6      1    0.513   0      0.000    0.513
```
5) the database is currently about 5.3TB size, of which Lucene indexes occupy some 820GB

-> is this because of tuning of parameters is needed?
-> or has the dbase gone corrupted after these DELETEs from the "default" cluster as you suggested?

**Comment by rdelangh** [comment]
by the way, running v2.2.31

**Comment by rdelangh** [comment]
We have the same symptom on another database, also running now since yesterday on version 2.2.31

1) via "console.sh", we cannot open the dbase:
```
orientdb> CONNECT remote:localhost/mobile admin Exupita5
Connecting to database [remote:localhost/mobile] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on creation of shared resource
        DB name="mobile"
Error: java.lang.NullPointerException
```
2) but client programs can make connections to the database via the REST API, and load data into the database
3) I tried using " console.sh" from older versions (2.2.30, 2.2.27, ...) but via this way it is never possible to open the database
-> what is wrong ? Where to look for clues?

**Comment by rdelangh** [comment]
Also connections via the web API are NOT possible

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I'd like to do a check, I have the feeling that something in the schema is pointing to the default cluster. Could you please run the following query and post the result?

```
select from metadata:schema
```

I guess for that NullPointerException you are not seeing any stack trace, but if I'm wrong please copy it here, it would help a lot

Thanks

Luigi

**Comment by rdelangh** [comment]
hi @luigidellaquila 
I would very much like to run that command, but how ? From the "console.sh" or the web API, it is not possible to open a connection...

**Comment by luigidellaquila** [comment]
Do you still have the original DB? The information will be the same

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
we have only one copy of this multi-TB database. Is it not possible to start such a suspected database in a sort of recovery mode, when maybe not all functionality is available, but at least inspection can be done to find the reason why we have such problem?
Also, can there be more verbose information obtained about why that connection is rejected? Somehow the database server must encounter a condition in one of its checks, which makes it abort that connection attempt. Can't that be displayed/logged by the server?

**Comment by rdelangh** [comment]
Other remark, the database were we first did a TRUNCATE of the default cluster, was put back to a backup-version from right before that TRUNCATE.
So that database was started again without any changes in the default cluster.
However also that database gives problems that we cannot connect to it via console.sh (the error as given above), however we **can** connect to it via REST API and the web GUI.

**Comment by laa** [comment]
Hi, could you run the following when you start the console?

1. Add following parameters to the console sh `-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n`
2. When the console is started run 'jps' to find pid of the console app.
3. Run 'jdb -attach <pid>'
4. Execute 'catch java.lang.NullPointerException' inside jdb
5. Connect to the database in the console
6. Once NPE is thrown please execute 'where' inside the jdb and send us stack trace.

**Comment by rdelangh** [comment]
hello @laa , thanks for your feedback!

I did what you described, and but got no exception caught for the NullPointerException, so I tried with the "ODatabaseException" : 
```
$ jdb -attach 10.49.69.189:8000
Set uncaught java.lang.Throwable
Set deferred uncaught java.lang.Throwable
Initializing jdb ...
> catch java.lang.NullPointerException
Set all java.lang.NullPointerException
> where
No thread specified.

> catch com.orientechnologies.orient.core.exception.ODatabaseException
Set all com.orientechnologies.orient.core.exception.ODatabaseException
>
Exception occurred: com.orientechnologies.orient.core.exception.ODatabaseException (to be caught at: com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(), line=2,031 bci=214)"thread=main", com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(), line=451 bci=136

main[1] where
  [1] com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException (OChannelBinaryAsynchClient.java:451)
  [2] com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus (OChannelBinaryAsynchClient.java:400)
  [3] com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse (OChannelBinaryAsynchClient.java:283)
  [4] com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse (OChannelBinaryAsynchClient.java:167)
  [5] com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase (OStorageRemote.java:2,009)
  [6] com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase (OStorageRemote.java:2,044)
  [7] com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase (OStorageRemote.java:1,983)
  [8] com.orientechnologies.orient.client.remote.OStorageRemote.open (OStorageRemote.java:364)
  [9] com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open (ODatabaseDocumentTx.java:259)
  [10] com.orientechnologies.orient.console.OConsoleDatabaseApp.connect (OConsoleDatabaseApp.java:234)
  [11] sun.reflect.NativeMethodAccessorImpl.invoke0 (native method)
  [12] sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
  [13] sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
  [14] java.lang.reflect.Method.invoke (Method.java:498)
  [15] com.orientechnologies.common.console.OConsoleApplication.execute (OConsoleApplication.java:405)
  [16] com.orientechnologies.common.console.OConsoleApplication.executeCommands (OConsoleApplication.java:260)
  [17] com.orientechnologies.common.console.OConsoleApplication.run (OConsoleApplication.java:131)
  [18] com.orientechnologies.orient.graph.console.OGremlinConsole.main (OGremlinConsole.java:72)
main[1]
```

**Comment by laa** [comment]
@rdelangh I see so that is server issue then. Could you repeat the same steps but on the server side?

**Comment by laa** [comment]
@rdelangh btw do you see any NPE in server log?

**Comment by rdelangh** [comment]
@laa, ok I will stop the server and add these same options to its startup command, then perform same action; this will take approx 30 mins until the server has completed its attempt to open that large dbase...

**Comment by rdelangh** [comment]
1) launched the server with "debug" option, which makes it opening port 1044 for the debugger
2) started the debugger on that port:
```
$ jdb -attach  10.49.69.189:1044
Set uncaught java.lang.Throwable
Set deferred uncaught java.lang.Throwable
Initializing jdb ...
> catch java.lang.NullPointerException
Set all java.lang.NullPointerException
>
```
3) started the "console.sh" and invoked the CONNECT command:
```
$ /opt/orientdb/orientdb-community-2.2.31-SNAPSHOT/bin/console.sh
orientdb> CONNECT remote:localhost/cdrarch admin ourpwd
Connecting to database [remote:localhost/cdrarch] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create a connection to remote server address(es): [127.0.0.1:2424]
        DB name="cdrarch"
```
4) In the JDB:
```
Exception occurred: java.lang.NullPointerException (to be caught at: com.orientechnologies.orient.core.metadata.schema.OSchemaShared.fromStream(), line=778 bci=880)"thread=OrientDB (/127.0.0.1:2424) <- BinaryClient (/127.0.0.1:37350)", com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.fromStream(), line=1,107 bci=6

OrientDB (/127.0.0.1:2424) <- BinaryClient (/127.0.0.1:37350)[1] where
  [1] com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.fromStream (OPropertyImpl.java:1,107)
  [2] com.orientechnologies.orient.core.metadata.schema.OClassImpl.fromStream (OClassImpl.java:955)
  [3] com.orientechnologies.orient.core.metadata.schema.OSchemaShared.fromStream (OSchemaShared.java:716)
  [4] com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload (ODocumentWrapperNoClass.java:74)
  [5] com.orientechnologies.orient.core.metadata.schema.OSchemaShared.load (OSchemaShared.java:858)
  [6] com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call (OMetadataDefault.java:172)
  [7] com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call (OMetadataDefault.java:167)
  [8] com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource (OSharedContainerImpl.java:62)
  [9] com.orientechnologies.orient.core.storage.OStorageAbstract.getResource (OStorageAbstract.java:143)
  [10] com.orientechnologies.orient.core.metadata.OMetadataDefault.init (OMetadataDefault.java:167)
  [11] com.orientechnologies.orient.core.metadata.OMetadataDefault.load (OMetadataDefault.java:89)
  [12] com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen (ODatabaseDocumentTx.java:3,224)
  [13] com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open (ODatabaseDocumentTx.java:271)
  [14] com.orientechnologies.orient.server.OServer.openDatabase (OServer.java:977)
  [15] com.orientechnologies.orient.server.OServer.openDatabase (OServer.java:947)
  [16] com.orientechnologies.orient.server.OServer.openDatabase (OServer.java:938)
  [17] com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase (ONetworkProtocolBinary.java:914)
  [18] com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest (ONetworkProtocolBinary.java:248)
  [19] com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute (ONetworkProtocolBinary.java:213)
  [20] com.orientechnologies.common.thread.OSoftThread.run (OSoftThread.java:82)
OrientDB (/127.0.0.1:2424) <- BinaryClient (/127.0.0.1:37350)[1]
```

**Comment by laa** [comment]
@tglman could you look at the last message?

**Comment by rdelangh** [comment]
@laa 
in the server logs, I see only these messages from during the startup:
```
...

2017-11-24 11:59:34:677 INFO  {db=OSystem} Storage 'plocal:/opt/orientdb/databases/OSystem' is opened under OrientDB distribution : 2.2.31-SNAPSHOT (build 97f1131baee11213c40e5f55b150416d31ff7412, branch branches/2-2-x.15993v/workspace/core) [OLocalPaginatedStorage]
2017-11-24 12:05:17:943 WARNI {db=cdrarch} Page 189 is broken in WAL segment 189 and will be truncated [OLogSegmentV2]
2017-11-24 12:05:17:944 SEVER {db=cdrarch} Last 1 pages in WAL segment cdrarch.234651.wal are broken and will be truncate, some data will be lost after restore. [OLogSegmentV2]
2017-11-24 12:26:14:417 INFO  {db=cdrarch} Storage 'plocal:/opt/orientdb/databases/cdrarch' is opened under OrientDB distribution : 2.2.31-SNAPSHOT (build 97f1131baee11213c40e5f55b150416d31ff7412, branch branches/2-2-x.15993v/workspace/core) [OLocalPaginatedStorage]Listening for transport dt_socket at address: 1044
```
Please note that WAL segment related message. Maybe irrelevant.

Those are the last messages in the logfile. No NPE message.

**Comment by tglman** [comment]
Hi @rdelangh, 

I just made a change on 2.2.x for fix the issue that you have with the schema. The problem seems that some properties got externalized to the default cluster, I made sure that everytime the properties are stored as embedded inside the schema, so as soon 2.2.31 is released, you can upgrade, do some operation on the schema to make sure everything get embedded, and try again to delete the default cluster.

Bye

**Comment by rdelangh** [comment]
hi @tglman 
thank you for this feedback, and fix, mostly appreciated!
In the current state of our database, we can not open it (see previous posts above). How do you suggest we get it fixed without opening it (since that is failing)?
