### ISSUE TITLE
Implements new Lucene functions instead of LUCENE operator

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#7155]
Move away from LUCENE operator to functions, as for SPATIAL indexes:
- simple search: **SEARCH_CLASS**(Lucene query, metadata): will perform the query on the single index defined on the given class. If more than one index exists it will throw an error. Metadata could be provided to configure the query parser
```sql
SELECT FROM SONG WHERE SEARCH_CLASS('good') = true
```

- search on a field: **SEARCH_FIELDS**(fieldNames, query, metadata): if more than an index is defined, use the field name to force the use of a specific index: 
```sql
SELECT FROM SONG WHERE SEARCH_FIELDS(['title,lyrics'],'+title:good +lyrics:life') = true
```
- search on a specific index: **SEARCH_INDEX**(indexName, query, metadata): same of the above, but using index name as the qualifier
```sql
SELECT FROM SONG WHERE SEARCH_INDEX('Song.title_lyrics','+title:good +lyrics:life') = true
```

The metadata parameter is a JSON document that allows configuring the query parser's behavior overriding index configuration.

```json
{
"default": "org.apache.lucene.analysis.standard.StandardAnalyzer",
"query": "org.apache.lucene.analysis.standard.StandardAnalyzer",
"name_query": "org.apache.lucene.analysis.core.KeywordAnalyzer",
 "lowercaseExpandedTerms": false,
 "allowLeadingWildcard": true
}

```

**Comment by smolinari** [comment]
Is the "== true" really necessary? Couldn't that be a default? And if I want the negated search, I could add "== false"? 

Like so: 

`SELECT FROM SONG WHERE SEARCH_CLASS('good') AND SEARCH_CLASS('bad`) == false`

That would be the same as:

`SELECT FROM SONG WHERE SEARCH_CLASS('good') == true AND SEARCH_CLASS('bad`) == false`

I hope I am making a correct assumption that "== false" is even possible. 😄 

Also, how about when I need to search one field for multiple words? How would a query look then?

Scott

**Comment by robfrank** [comment]
Documentation updated, closing

**Comment by smolinari** [comment]
I still think the `= true` is unnecessary. 😄

Scott

**Comment by robfrank** [comment]
It's not my duty, but the SQL parser needs it. MAaybe @luigidellaquila  can answer in more detailed way.

**Comment by luigidellaquila** [comment]
@smolinari the `= true` is there just because the parser for now only accepts binary conditions (eg, `<expression> <comparisonOperator> <expression>`) but I plan to remove this limitation soon

Thanks

Luigi
