### ISSUE TITLE
Should be able to access Studio when starting orientdb from official docker image

### ISSUE THREAD

**Issue by homdoq** [orientechnologies/orientdb#7158]
## Expected behavior  
Running official orientdb:2.2.2 docker image should always allow access to Studio  

## Actual behavior  
When mounting a local volume to /orientdb/config, the Studio cannot be reached.
(Tried using Safari, Netscape, and Chrome)

Note that Studio _can_ be reached even when mounting local volumes to /orientdb/databases and/or /orientdb/backup

Note that mounting to /orientdb/config works, i.e. a fresh config file is created on the local file system.

## Steps to reproduce  
docker run -d -p 2480:2480 -v <path to config dir>:/orientdb/config -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb:2.2.2  

(same with orientdb:latest, of course)

**Comment by smolinari** [comment]
Your missing the port to ODB itself. 

`-p 2424:2424 -p 2480:2480`

According to the ODB/Docker docs, this is the command you need. 

`docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb`

The volume, theoretically, shouldn't make any difference, if the config is properly set up.

Scott

**Comment by homdoq** [comment]
I left out the 2424 port forwarding (as well as the name) in the issue since I didn't think it was relevant to the issue. And of course I agree that, _theoretically_, it should not make a difference if the volume is mapped or not. With this issue, I want to report, that _actually_ it seems to make a difference.

These are the actual commands I used:

docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -v <my path from root>/orientdb/databases:/orientdb/databases -v <my path from root>/orientdb/backup:/orientdb/backup -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb:2.2.2

docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -v <my path from root>/orientdb/config:/orientdb/config -v <my path from root>/orientdb/databases:/orientdb/databases -v <my path from root>/orientdb/backup:/orientdb/backup -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb:2.2.2

The first one lets me connect to Studio via http://localhost:2480, the second does not.

**Comment by homdoq** [comment]
I should clarify: I leave the local directories empty before spinning up the container, so the config is created by the server when it starts up.

**Comment by smolinari** [comment]
When I get home, I'll test it out.

Scott

**Comment by smolinari** [comment]
I can confirm adding the config volume kills Studio.

Scott

**Comment by maggiolo00** [comment]
@smolinari 

does the console works?

**Comment by homdoq** [comment]
I can 'docker exec -ti oriented sh' and run console.sh in the container.
This is not a blocking issue, I just thought it's weird and wanted to let you know.

**Comment by homdoq** [comment]
It just occurred to me that I had tried the setup last November, and although I am not absolutely certain I used Studio, it is highly likely I did.
So probably an update in docker or Mac OS X may be at fault here?

**Comment by smolinari** [comment]
I am using Windows 10 Pro and Docker for Windows btw. I need to check on the console (again, when I get home).

Scott

**Comment by homdoq** [comment]
I just tried the following steps:

1 - run the container without mapping config but mapping backup (and databases)
2 - open a shell on the container and cp -R the config directory to backup (mounted from local)
3 - exit the shell, stop and remove the container
4 - cp -R the config from local backup to local config directory
5 - run the container mapping all three volumes

I am now able to access Studio.

I noted that when I map an empty config directory, the server only creates an orientdb-server-config.xml, which is significantly smaller than the one found on the image; also none of the other files (found in the config directory on the image) are created by the server when it sees an empty config directory (as is the case when I map a local directory the first time).

This is a suitable workaround for me to bootstrap the environment.

**Comment by smolinari** [comment]
Hmmm...now that I think about it. The config file is probably burned into the container image, which means creating a volume overrides that file, i.e. the file is then missing on startup. The solution is a docker file, which copies the config locally, then creates the volume and to run the file. 

Scott

**Comment by robfrank** [comment]
If a config volume is provides, it should be filled witha valid configuration set.
Read carefully the doc of the container:
https://hub.docker.com/_/orientdb/

```
The docker image contains an OrientDB installation with basic configuration. If you need to provide your own config folder to override the one included in the OrientDB container, simply attach a persistent volume for configuration folder. Providing a configuration folder enables integration with software configuration tools such as Ansible, Chef or Puppet.```

If you take a standalone orientdb and delete the content of the config direcotry, once started it will dump a minimal conf. So, providing to the container an empty config folder IS THE SAME as deleting it.

**Comment by smolinari** [comment]
Yup, this is normal operation then. 😄 

Scott

**Comment by homdoq** [comment]
I was clear about only getting a minimal config.
What surprised me was that that prevented me from using Studio.
Maybe you could add that bit to the container info?

**Comment by robfrank** [comment]
The minimal configuration of OrientDB doesn't enable http. The behavior is not related to the container, but to orientDB itself. If a config folder is provided as volume, it should be filled with a valid configuration file set.
