### ISSUE TITLE
Document specifics of storage.encryptionKey (e.g. length)

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#7159]
## Expected behavior  
Using [this guide](http://orientdb.com/docs/2.1/Database-Encryption.html), I expected a new, encrypted database is created when I typed the required commands.  

## Actual behavior  
However, it generates the following error:
```
Creating database [plocal:/opt/orientdb/databases/encrypter] using the storage type [plocal]...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'encrypter'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #0:-1
	DB name="encrypter"

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #0
	DB name="encrypter"

Error: java.lang.NullPointerException
```

## Steps to reproduce  
1.  Launch the OrientDB console
2. Set the encryption key using `CONFIG SET storage.encryptionKey <key-here>`
3. Create the database using `create database plocal:/opt/orientdb/databases/encrypter root root  plocal document -encryption=aes`

**Comment by maggiolo00** [comment]
hi @finid 

i was not able reproduce it with the following step
From Console : 

```
CONFIG SET storage.encryptionKey T1JJRU5UREJfSVNfQ09PTA==
```

and

```
create database plocal:/tmp/db/encrypted-db root root plocal document -encryption=aes
```

**Comment by finid** [comment]
@maggiolo00 the only difference between what I did and yours is that the encryption key you used **T1JJRU5UREJfSVNfQ09PTA==** is the same as that used in [the guide](http://orientdb.com/docs/2.1/Database-Encryption.html).

So the follow-up question is what is the guideline for the encryption key, because I don't think it's advisable to use the same encryption key for all OrientDB databases.

**Comment by finid** [comment]
@lvca I think we need a guidance on what the length of an encryption key has to be.

So far, it seems that the length has to be 24 characters and the last 2 characters have to be **==**. Otherwise creating the database would fail with the error given in the original post.
