### ISSUE TITLE
Regarding <storages> and <users> property in `config/orientdb-server-config.xml`

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#7162]
### OS: Ubuntu 16.04

In the configuration file there are two elements that I'm trying to figure out how best to configure. In a default installation, they appear as:

```
<storages>
</storages>
<users>
</users>
```

What goes into `<storages>`, and regarding `<users>`, what users are pertinent here? Operating system users or OrientDB users?

**Comment by maggiolo00** [comment]
hi @finid 

usually you don't to edit that part.

users are OrientDB server users.
like root,guest. (created at first startup of OrientDB)

storages are external database that the orientdb server can manage.

By default orientdb store the databases in ${ORIENTDB_HOME}/databases

but you can plug other databases on other paths with that configuration

**Comment by finid** [comment]
Thanks, @maggiolo00. This issue is closed.
