### ISSUE TITLE
NULL values are not visible in query with GROUP BY

### ISSUE THREAD

**Issue by wojtala6** [orientechnologies/orientdb#7166]
## Expected behavior  
NULL values  should be visible in query with GROUP BY.

## Actual behavior  
NULL values are not visible in query with GROUP BY.

## Steps to reproduce  
When I run query select * from GenericClassName where propertyName IS NULL , I'm getting results. But when I run query SELECT propertyName FROM GenericClassName GROUP BY propertyName I don't have NULL group. propertyName is STRING.

**Comment by luigidellaquila** [comment]
Hi @wojtala6 

I just pushed a fix for this on 2.2.x branch, the fix will be released with 2.2.20

Thanks

Luigi
