### ISSUE TITLE
Access OrientDB Studio via HTTPS

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#7168]
### OS: Ubuntu 16.04 
This is just a question about accessing OrientDB Studio via HTTPS.
All the docs I've looked only provides information on how to access OrientDB Studio insecurely via HTTP. Has anybody configured access to it via HTTPS that they can share?

**Comment by maggiolo00** [comment]
hi @finid 

the OrientDB web server does not support https. But you can proxy it behind a ngnix/apache https connection

**Comment by maggiolo00** [comment]
You can for example use this proxy pass

```
  ServerName www.test.com
  ProxyPass /mystudio/ http://internalip:2480/  connectiontimeout=300 timeout=300 Keepalive=On
  ProxyPassReverse /mystudio/ http://internalip:2480/
```

and then access to studio with this url

```
https://www.test.com/mystudio/studio/index.html#/
```

**Comment by maggiolo00** [comment]
@finid 

if you need to expose directly the OrienetDB server i recall now that there is this guide to use SSL

http://orientdb.com/docs/2.2/Using-SSL-with-OrientDB.html

**Comment by finid** [comment]
Thanks, @maggiolo00. This may now be closed.
