### ISSUE TITLE
Console scripts: consider to increase -Xmx512m as on server script

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7169]
### OS: Linux

In addition, I think we should also document such settings somewhere - explaining things as to a user that does not have any java background - giving them main concepts and guidelines for them to be able to understand the meaning of such settings, and change them, if appropriate

**Comment by robfrank** [comment]
Increased default size to 1024m
Heap size can be configured with a variable now 
```sh
export ORIENTDB_OPTS_MEMORY="-Xmx2048m "
console.sh
```
