### ISSUE TITLE
ORecordNotFoundException missing RID

### ISSUE THREAD

**Issue by Solido** [orientechnologies/orientdb#7170]
## Expected behavior  
When asking for a forged RID that doesn't exist OrientDB throw an ORecordNotFoundException.
The error message is well formed : 
The record with id '#999:999' was not found
	DB name="dbname"
Even if non existent the ORID getRid() should be populated to permit other service to properly handle the event 

## Actual behavior  
getRid() is null but the message contains the forged RID

## Steps to reproduce  
OrientBaseGraph.getVertex("999:999") 

## Notes
This behavior only occurs if the Cluster doesn't exist.
If the cluster exist but not the entity RID then no exception is thrown and a null object is returned.

**Comment by Solido** [comment]
Any comment on this ? is this expected or can a OImmutableRecordId do the trick ?
Thanks !

**Comment by tglman** [comment]
Hi,

I think there is a but in the copy of the exceptions in some case, i'm going to fix it

Regards

**Comment by tglman** [comment]
tested and fixed, closing.
