### ISSUE TITLE
OrientDB timezone serialization

### ISSUE THREAD

**Issue by tan31989** [orientechnologies/orientdb#7175]
### Expected behavior 
Giving my local system's timezone specific datetime
Orientdb config:
`ALTER DATABASE TIMEZONE UTC`

```java
OObjectDatabaseTx activeTxn = new OObjectDatabaseTx(this.txn.acquire());
List<Workflow> dbList = activeTxn.query(new OSQLSynchQuery<Workflow>(sqlCommand));
dbList.getTimeToRun() // Giving my local system's timezone specific datetime
```

### Actual behavior 
Should give UTC based datetime
```java
dbList.getTimeToRun() // Give UTC based datetime
```

**Comment by tglman** [comment]
hi @tan31989,

The TimeZone setting is mostly used for formatting dates to string and similar tasks, we usually keep the date[time] informations using java.util.Date that is agnostic to the timezone. so I'm not sure what is the type of your "getTimeToRun()" so it all depends on that.

It's usually suggested to keep the database timezone the same of the VM timezone, otherwise it can be quite confusing, you can do that booting the server as ex: "./server.sh -Duser.timezone=UTC" or with the same setting on your VM in case of embeedded.

Hope this help

Regards

**Comment by tan31989** [comment]
Hi @tglman ,

The getTimeToRun is java String and that said, there are other java Date fields, that were also getting date from java orientdb library, with timezone related to system's timezone.

I guess, when ORM jar of orientdb, returns, it should be applying the db timezone to the value obtained from DB. Meaning,

> 
> [Database (timezone UTC)]
                    |
> [Orient Jar (get date using system and also get the timezone from Database Config) convert to timezone]
                    |
> [Java application, get's in the timezone which the Database is setup]

**Comment by tglman** [comment]
hi @tan31989,

If the getTimeToRun is a String OrientDB do not control it's format, for the other Date fields i guess they are java.util.Date so they do not contain any timezone information.

So the timezone is actually used exclusively when a date is translate from java.util.Date to String, this can happen is you save/extract date in string format but you define a schema type date.

Can you explain a bit more how you are using OrientDB ? what is the schema of your application ? if the getTimeToRun is managed as string orient does not do any conversion on it.

Regards

Regards

**Comment by tan31989** [comment]
@tglman  Apologies for delay in reply.

The `getTimeToRun` method is returning a `Date`.
But, if the date is saved in UTC format, the retrieval was applying `IST` in my case.

Whereas the DB has `ALTER DATABASE TIMEZONE UTC`. 
This then lead to us manually converting all the given Date's to UTC when we pick it from DB

**Comment by tglman** [comment]
hi @tan31989,

The java.util.Date represent an instant without TimeZone, so any TimeZone related operation outside the orientdb context/api depends on the JVM TimeZone or by a specific API TimeZone.

Like you said is better to keep all environments set with the same TimeZones or convert  the date to and from a specific TimeZone when you interact with the database.

Can we close this ?

Regards

**Comment by tan31989** [comment]
@tglman 

I agree that java.util.Date represents an instant without TimeZone and in case of anything outside of orientdb context/api, we should use our own logic for JVM TimeZone.

But, in this specific case, 
> i believe orientdb api should have used the DB configured Timezone and should have returned the datetime using the same and not JVM's !

Thanks for the reply.

If you think, that orientdb will still use java.util.Date rather than a TimeZone based util, then please do close this. 

Right now, we had to hack our bits to convert the orientdb's returned datetime to our predefined TimeZone even thought the DB is configured for that TimeZone.

Regards.
