### ISSUE TITLE
In OrientDB-JBDC query SQL Keywords like "select", "count" should not be case sensitive

### ISSUE THREAD

**Issue by py563** [orientechnologies/orientdb#7176]
## Expected behavior  
In Java, while testing orientdb connections with jdbc on GratefulDeadConcerts this:
     ResultSet rs = stmt.executeQuery("SELECT Count(*) FROM V");
     int noofelements = rs.getInt(1);
Should return 809, as it does in OrientDB Studio:
     SELECT Count(*) FROM V ==> it gives 809

## Actual behavior  
In Java it returns 0;
It works **ONLY with all lowercases**: 
     ResultSet rs = stmt.executeQuery("select count(*) from V");
     int noofelements = rs.getInt(1); // this gets the expected 809

## Steps to reproduce  
1. Create a plain java project in Ecilipse, add neccesary jars or all to buildpath.
2. Create a simple Java class which tries to esthablish jdbc connection either with orientdb running on localhost or with remote server. 
3. In executeQuery paste above code/query.

> It is not documented to be case sensitive or I may be missing it in documenation. I can share the whole ecilipse project. We were doing a demo trail in organization to use orientdb got this error, was not expecting it was issue so i took time to raise a issue. If it is indeed mentioned in documentation please ignore and close the issue

Thanks
Prajwal

**Comment by robfrank** [comment]
Thank you very much for the report. I was able to reproduce the issue on 2.2.18-SNAPSHOT, it seems problem on mapping field names to columns of result set. 
I'm on it

**Comment by robfrank** [comment]
fixed on 2.2.x. will be included on 2.2.18. in the meanwhile you can use a snapshot package:

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-jdbc/2.2.18-SNAPSHOT/

**Comment by py563** [comment]
Thanks
