### ISSUE TITLE
[Feature Request] Alloy single quoted aliases for enabled strictSQL mode

### ISSUE THREAD

**Issue by Fraternel** [orientechnologies/orientdb#7177]
When the strictSQL is disabled (so the old query parser) we can use more "complex" aliases like `field AS 'My-Alias'`. Is is conceivable to add this functionality in enabled strictSQL mode?

**Comment by luigidellaquila** [comment]
Hi @Fraternel 

You can use back-tick quoting, eg.
```
SELECT `My-Alias` from `My-Class`
```

Thanks

Luigi

**Comment by Fraternel** [comment]
Thanks you (again) Luigi it works perfectly! Perhaps I missed this explanation in documentation.
