### ISSUE TITLE
Python API SELECT with no limit

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#7179]
## Expected behavior  
select from Foo should return default 20 records.

## Actual behavior  
select from Foo tries to return all records

## Steps to reproduce  
records = client.command("select from Foo")
[TIP] Query 'SELECT FROM Foo' returned a result set with more than 10000 records. Check if you really need all ...
Cannot serialize record: .....

**Comment by prajwalyashasvi** [comment]
Tried PyOrient for a day, I am assuming you are referring to it, when you said python. I always thought limit is by default 20 in only orientdb studio, but for all other type of calls you get all elements unless you specify limit. PyOrient does support Limit or `select from foo limit 20` would do it. 

sorry if i gave a wrong answer, i am learning and using orientdb from a week or so.

**Comment by smolinari** [comment]
In general, the ODB APIs allow you to get up to 10K records. Above that you get the warning as you did. So yes, use the LIMIT clause, if you want less records and/ or to avoid the error message. 

Scott

**Comment by smolinari** [comment]
@luigidellaquila - is my statement correct, because I am also reading this in the "limits" section of the docs. 

> Queries can return a maximum of 2 Billion rows, no matter the number of the properties per record

Scott

**Comment by austx** [comment]
Limit of 20 is imposed in console and studio. I made the assumption this was by default built-in to the PyOrient API.
Thanks anyway.

**Comment by santo-it** [comment]
Hi @austx , glad this is solved.  Let us know if you have any other questions or find issues

Many thanks,
