### ISSUE TITLE
OMetadata SYSTEM_CLUSTER collection is incomplete?

### ISSUE THREAD

**Issue by rnagy90** [orientechnologies/orientdb#7182]
### OS: Win 8 + Linux  

Maybe it's a bug maybe it's not, but the OMetadata#Set<String> SYSTEM_CLUSTER  contains the system class names as lower case.
There shouldn't be more class names? I found that when i create a new database, it automatically creates the OSequence, V, E and _studio classes.

I have one more question. I've just found out the JDBC driver call check this Set to get the table types with OClass#getName() without '.toLowerCase()'.
/* I'm going to fix it and update the test cases in my fork, because i need it now for my project and you can merge it if you want :). */
I am not sure, but the OPaginatedCluster constructor already checks the class name with the SYSTEM_CLUSTER.contains(name) and maybe it also has an incorrect result potential. (I didn't check the call hierarchy, it's just a guess)

**Comment by tglman** [comment]
hi @rnagy90,

I sorted out that, closing.

Regards

**Comment by rnagy90** [comment]
hi @tglman!

Thank you for the fix, i'm going to test it.
