### ISSUE TITLE
creating Database during open

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#7184]
## Expected behavior  
trying to open a database that is non existent using factory.
OrientGraphFactory factory=new OrientGraphFactory("plocal:C:/GO/ArtiE/server/domains/mydb");
		ODatabaseDocumentTx doctx = factory.getDatabase(false, false);
it should not create a database as the first parameter is false.

## Actual behavior  

its creati the database mydb 

## Steps to reproduce  

		OServer server=null;
		try {
			server = OServerMain.create();
			server.startup(new File("C:/GO/ArtiE/server/config/orientdb-server-config.xml"));
			server.activate();

OrientGraphFactory factory=new OrientGraphFactory("plocal:C:/GO/ArtiE/server/domains/mydb");
ODatabaseDocumentTx doctx = factory.getDatabase(false, false);

			server.shutdown();
			Orient.instance().shutdown();
		} catch (Exception e) {
			e.printStackTrace();
			server.shutdown();
			Orient.instance().shutdown();
		}

**Comment by tglman** [comment]
hi @smallik,

By default the OrientGraphFactory create a pool of graph and for do that it create the database by default, to avoid this behaviour you should not let the factory create the pool on new, so you can change your code like this: 
```
		OServer server=null;
		try {
			server = OServerMain.create();
			server.startup(new File("C:/GO/ArtiE/server/config/orientdb-server-config.xml"));
			server.activate();

                       OrientGraphFactory factory=new OrientGraphFactory("plocal:C:/GO/ArtiE/server/domains/mydb","admin","admin",false); //The last flag force to not create the pool and the database
                       ODatabaseDocumentTx doctx = factory.getDatabase(false, false);
                       factory.setupPool(1,20); //to recreate the pool after the database was created.

			server.shutdown();
			Orient.instance().shutdown();
		} catch (Exception e) {
			e.printStackTrace();
			server.shutdown();
			Orient.instance().shutdown();
		}
```

Hope this help.
Regards

**Comment by smallik** [comment]
I tested and the issues is still happening.

I understand that the pool must be created after the database is created 
but this method is not working as per documentation. we need to either change the method signature or fix the method functionality. 

the getDatabase(false,false) factory method is creating a new database if the database not found.

pleas mark this as a bug.

Note:We can do a factory.exists() check to workaround this.
