### ISSUE TITLE
POJO field named `version` 

### ISSUE THREAD

**Issue by sbespalov** [orientechnologies/orientdb#7185]
### OS: Ubuntu 16.04 

Hi
I have an POJO with field named `version`, and I don't want it to be an OrientDB entity version, just one of POJO fields with some provided value. 

I noticed that for some reason `version` field do not store its value in the database, it simply remains empty.

So is `version` field name valid? or it some kind of reserved word?

```
public class ArtifactEntry
        extends GenericEntity
        implements Serializable
{

    private String storageId;
    private String repositoryId;
    private ArtifactCoordinates artifactCoordinates;

   //getters and setters below
   ...
}

public class MavenArtifactCoordinates extends AbstractArtifactCoordinates
{
    private String groupId;
    private String artifactId;
    private String version;
    private String classifier;
    private String extension;

   //getters and setters below
   ...
}
```

**Comment by sbespalov** [comment]
@tglman, can you please tell, can I have POJO field named `version`?

**Comment by sbespalov** [comment]
Seems that we was able to resolve this issue by ourselves.
The problem was that we has a class which contains two `version` fields in hierarchy, one of them was declared using `@OVersion` annotation and other was just skipped with `OObjectEntitySerializer`. 

@tglman I am not sure is this a bug or an feature, but I believe that such situations can be detected by `OObjectEntitySerializer` and reported with some kind of `Exteption`.

**Comment by tglman** [comment]
hi @sbespalov,

I got your point, yes it could be better throw an exeption in case some of this cases are detected, i'll leave this open as note and target in a future version

Regards
