### ISSUE TITLE
db.close() not allowed after db.detatchAll(antibodies,true)

### ISSUE THREAD

**Issue by austx** [orientechnologies/orientdb#7187]
## Expected behavior  
select some items and return to a Grails server page or view(gsp) and closing the database connection before returning.(see below)

## Actual behavior  
**Using this concept in IntelliJ/Grails, Controller and Services**

*** dbObjectConnectionService ...
public OObjectDatabaseTx getDatabase(String url, String userName, String password) {
   OObjectDatabaseTx db = new OObjectDatabaseTx(url).open(userName, password)
    ODatabaseRecordThreadLocal.INSTANCE.set(db.getUnderlying())
    return db
}

*** Service...
def db = dbObjectConnectionService.getDatabase("remote:localhost/CytBase", "admin", "admin")
db.getEntityManager().registerEntityClass(Panel.class)
List<Panel> antibodies = db.query(
        new OSQLSynchQuery<Panel>("select from Panel where channeltype != 'N/A' order by channeltype"))

_**the next two lines do not give the expected outcome, namely to close the database connection and still be able to utilize the List antibodies.**_

antibodies = db.detatchAll(antibodies,true)
db.close()

antibodies

*** Controller...
def index() {

    [antibodies: panelService.getPanelData()]
}

To utilize the 'antibodies' list in a drop down makes it impossible to close the database.

## Steps to reproduce  
antibodies = db.detatchAll(antibodies,true)
db.close()

_renders stack trace:_
URI
/panel/index
Class
groovy.lang.MissingMethodException
Message
null
Caused by
No signature of method: com.orientechnologies.orient.object.db.OObjectDatabaseTx.detachAll() is applicable for argument types: (java.util.ArrayList) values: [[no.cytbase.data.Panel(153Eu_pSTAT1_Y701, Eu153Di, Intracellular phosphorylation), ...]] Possible solutions: detachAll(java.lang.Object, boolean), detach(java.lang.Object), detach(java.lang.Object), detach(java.lang.Object, boolean)

**Comment by tglman** [comment]
hi @austx,

The error still sound strange to me, like the error says it exists a method with signature `detachAll(java.lang.Object, boolean) ` and it complain because the parameter is not ArrayList, but it should be ok, because everything is Object, I'm trying to reproduce it locally but i don't have much experience with grais, I'll come you back with some example as quick as i can, in any case i think we need to investigate a bit on the java-grails intragraion.

Regards

**Comment by austx** [comment]
hi tglman,

to me this is all about being able to close the database after fetching data into map antibodies.
The detachAll(antibodies,true) does not complain, the problem appears if db.close() is used. 
Not sure I understood this all together, but can't keep increasing the number of open database connections. Thanks!

**Comment by tglman** [comment]
hi @austx,

Yes i got the overall problem i just wrote an "example" test case to reproduce your problem in java, and I figured out the we have some problem with the detach all, but anyway i was able to write a test case that actually works, here it is: 
```
package com.orientechnologies.orient.object.db;

import com.orientechnologies.orient.core.db.document.ODatabaseDocument;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.db.object.ODatabaseObject;
import com.orientechnologies.orient.core.sql.query.OSQLSynchQuery;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;

/**
 * Created by tglman on 24/02/17.
 */
public class TestObject {

  public static class Some {
    private String name;
    private String surname;

    public Some() {
    }

    public Some(String name, String surname) {
      this.name = name;
      this.surname = surname;
    }

    public String getName() {
      return name;
    }

    public void setName(String name) {
      this.name = name;
    }

    public String getSurname() {
      return surname;
    }

    public void setSurname(String surname) {
      this.surname = surname;
    }

    @Override
    public String toString() {
      return "Some{" + "name='" + getName() + '\'' + ", surname='" + getSurname() + '\'' + '}';
    }
  }

  @Test
  public void simpleDetachTest() {
    OObjectDatabaseTx databaseObject = new OObjectDatabaseTx("memory:test");
    databaseObject.create();
    databaseObject.getEntityManager().registerEntityClass(Some.class);
    databaseObject.save(new Some("a-name", "a-surname"));

    List<Some> val = databaseObject.query(new OSQLSynchQuery<Some>("select from Some"));
    List<Some> val1 = new ArrayList<Some>();
    for (Some some : val) {
      val1.add((Some) databaseObject.detach(some, true));
    }
    databaseObject.close();

    System.out.println(val1.toString());
    assertEquals(val1.size(), 1);
    assertEquals(val1.get(0).getName(), "a-name");
    assertEquals(val1.get(0).getSurname(), "a-surname");
  }

}
```

As you see in the example i didn't do the detachAll but i iterate on the result and detached them one by one, filling another list, this work fine, i'm going to dig a bit and make as well the datachAll work properly but i hope this can unblock you for now.

Regards

**Comment by stiancor** [comment]
I've tested @austx case. Not all fields in Panel from the database existed in the POJO Panel. This included a link to a some other data element. In essence this means that this operation will fail if the POJO does not have all the fields and links defined on it.

This resulted in a NullPointerException in `OObjectEntitySerializer.getField(fieldName, selfClass)` on line 140 [https://github.com/orientechnologies/orientdb/blob/master/object/src/main/java/com/orientechnologies/orient/object/enhancement/OObjectProxyMethodHandler.java](url)

I think the most reasonable approach here would be to only set the fields that exist in the POJO and ignore the rest.

**Comment by austx** [comment]
Thanks stiancor!

one example to illustrate this is. I had to include in_... and out_... edges as String in actual domain classes.

**Comment by tglman** [comment]
hi all,

Sorry for the late replay, so checking this again I got the right way to do this, there is no way, to make orientdb iterate to all the results and detach them for you before the query is returned, so you have to iterate over them and call detachAll, the detach is not enough because it detach only the first level and not the nested documents, so getting again your example, this is the final:

```
  @Test
  public void simpleDetachTest() {
    OObjectDatabaseTx databaseObject = new OObjectDatabaseTx("memory:test");
    databaseObject.create();
    databaseObject.getEntityManager().registerEntityClass(Some.class);
    databaseObject.save(new Some("a-name", "a-surname"));

    List<Some> val = databaseObject.query(new OSQLSynchQuery<Some>("select from Some"));
    List<Some> val1 = new ArrayList<Some>();
    for (Some some : val) {
      val1.add((Some) databaseObject.detachAll(some, true));
    }
    databaseObject.close();

    System.out.println(val1.toString());
    assertEquals(val1.size(), 1);
    assertEquals(val1.get(0).getName(), "a-name");
    assertEquals(val1.get(0).getSurname(), "a-surname");
  }
```

Let me know if doing in this way solve the problem.

Regards

**Comment by austx** [comment]
I have a feeling we are talking past each other. I can't see any mention of the real problem here. If a new edge is created the detach renders a nullpointerexception. Please have a closer look at stiancor answer.

**Comment by stiancor** [comment]
I don't know OrientDB well at all, so my apologies if I'm missing something here, or if we are talking past each other.  However, it seems to me that we might be talking about two separate issues here?

I was going through @austx code, and found that the NullPointerException he got was related to setting the values on his POJO class called Panel. It seems that after saving, and then querying he suddenly got more fields from the query that did not originally exist in the Panel class. One of these fields are out_UtilizedIn where the code I refered to earlier would fail unless one defined getters and setters on the Panel class.  My suggestion was to ignore trying to set fields on POJOs if the class did not have a setter to do so.

**Comment by austx** [comment]
This seems to be nothing short of a misconception when mixing Graph and Object API.. After some advice from Luca, I decided to close this issue. Writing a Helper function worked just fine. Thanks.

**Comment by lvca** [comment]
Cool.
