### ISSUE TITLE
API request : request multiple IDs

### ISSUE THREAD

**Issue by Solido** [orientechnologies/orientdb#7189]
### OrientDB Version: All

When requesting for one ID I user getElement, when requesting many IDs I should create an SQL statement. Is there a proper way to avoid this ?

Else would a method like this be beneficial in my case ?
OrientBaseGraph -> Iterable<OrientElement> getElement(Set<Object> ids)

Since you're hard at work on 3.0 I guess it's the best time to ask about API stuff.

Regards

**Comment by luigidellaquila** [comment]
Hi @Solido 

We can consider a new `getElements(ORID rids...)` in 3.0.
@tglman wdyt?

Thanks

Luigi

**Comment by tglman** [comment]
hi,

Not against it, but anyway:
```
    List<ORID> ids = null;
    List<ORecord> records = ids.stream().map((id) -> (ORecord) db.load(id)).collect(Collectors.toList());
```
so for me is not a strong requirement yet, same thing can be done with the graph api, regards

**Comment by Solido** [comment]
Hi, thank you for the quick answsers,

ff my DB is on another machine on the network will your method simply let the connection open and ask for the OElement at each iteration ? Or is there a way to have all my OElements back in one batch call ? (thus avoiding network back & forth)

My main question is performance wise when you have a huge set of known OIdentifiables not only expressivity of the API. 

Thx !

**Comment by luigidellaquila** [comment]
Hi @Solido 

Right now the only alternative you have is to do a query:

```
db.query(new OSQLSynchQuery("select from ?"), rids)
```

Thanks

Luigi

**Comment by lvca** [comment]
Using the query does the job, closing it.
