### ISSUE TITLE
Exception acquiring database connection from an interrupted thread

### ISSUE THREAD

**Issue by dukeyin** [orientechnologies/orientdb#7192]
## Expected behavior  
Calling `com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire()` returns normally when the pool is not exhausted.

## Actual behavior  
If the current thread is in the interrupted status (flag not cleared), it's not possible to acquire a connection to the database, even though the pool is not exhausted.  Calling `com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire()` throws an exception:

```
com.orientechnologies.common.concur.lock.OInterruptedException: Acquiring of new connection was interrupted
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:198)
...
Caused by: java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
    at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:196)
```

https://github.com/orientechnologies/orientdb/blob/2.2.15/core/src/main/java/com/orientechnologies/orient/core/db/OPartitionedDatabasePool.java#L196

## Steps to reproduce  
Interrupt the thread that will call OPartitionedDatabasePool.acquire(), then call it.

Is it intentional that OPartitionedDatabasePool can't be used if the current thread is in the interrupted state?

**Comment by laa** [comment]
Hi @dukeyin , I do not think that it is a bug. I mean what other means will developer have to stop thread if pool is exhausted and no connection is acquired ?

**Comment by dukeyin** [comment]
The pool is **not** exhausted, which I've added explicitly to the report.

The report is that OrientDB does not check the interrupted status of the current thread before using `java.util.concurrent.Semaphore`.  That is why I asked "Is it intentional that OPartitionedDatabasePool can't be used if the current thread is in the interrupted state?"  If it is not intentional, it requires code changes.

OrientDB current code looks like this:
```
try {
  if (connectionsCounter != null)
    connectionsCounter.acquire(); // this will fail for reasons unrelated to the connection pool
} catch (InterruptedException ie) {
  throw OException.wrapException(new OInterruptedException("Acquiring of new connection was interrupted"), ie);
}
```

I'd expect it should look something like this, with checking and restoring of the interrupted flag:
```
boolean interrupted = Thread.interrupted(); // clears the interrupted flag
try {
  if (connectionsCounter != null)
    connectionsCounter.acquire(); // this no longer fails for reasons unrelated to the connection pool
} catch (InterruptedException ie) {
  throw OException.wrapException(new OInterruptedException("Acquiring of new connection was interrupted"), ie);
} finally {
  if (interrupted) {
    Thread.currentThread().interrupt(); // restores the interrupted flag
  }
}
```

**Comment by laa** [comment]
@dukeyin now I see your point and agree with you I will push fix soon.

**Comment by laa** [comment]
@dukeyin sorry it was evening, now I am looked at your code and can not agree with the proposal. I do not think that we should clear the interrupted flag in a pool before we start to wait for other connections.  If user wants to interrupt thread I do not think that should be any reason to force thread to wait for indefinite amount of time.

**Comment by laa** [comment]
Close issue because of no reply.
