### ISSUE TITLE
Cannot see backups in Studio Backup Management 

### ISSUE THREAD

**Issue by diaconescur** [orientechnologies/orientdb#7195]
## Expected behavior  
Open Studio Backup Management and see in the calendar the full backups already performed from the same place.

## Actual behavior  
The calendar is empty although the folder specified in the "Directory" has backup folders performed by the systems.

## Steps to reproduce  
1.install orientdb-enterprise-2.2.16 
2. load data
3. start server (bin/server.sh)
3. configure full backup ( Studio->BackupManagement )
4. check the backup has been performed 
5. open Studio->BackupManagement 

![image](https://cloud.githubusercontent.com/assets/12912432/23269987/fb0bcac4-f9fa-11e6-9950-95d60b30e400.png)
![image](https://cloud.githubusercontent.com/assets/12912432/23270003/08a23fec-f9fb-11e6-96bf-c085be442f95.png)

**Comment by maggiolo00** [comment]
hi @diaconescur 

Do you use Chrome? 
can you check if you see some JS error

**Comment by maggiolo00** [comment]
Do you use firefox?, i'm having the same trouble with it
With Chrome/Opera i do not have problem

**Comment by diaconescur** [comment]
Thank you for your answer. I was using Mozilla Firefox 50.1.0.
On Chrome the events are correctly displayed.

**Comment by santo-it** [comment]
reopening to have a chance to understand root cause and in case fix it

**Comment by diaconescur** [comment]
[MozillaConsole.txt](https://github.com/orientechnologies/orientdb/files/798742/MozillaConsole.txt)
Hello,
pleaser find attached the console output from Mozilla.
Thank you for you help
PS. I am also trying to load a full backup performed on one server (*_full.ibu file) on another (simulate a node crash and recovery using a stored backup). 
Should this be possible with Studio (right now  I can only see the backups performed on the current node, excepting the one I had just copied from another server)? Where could I find some information related to this problem?

**Comment by maggiolo00** [comment]
hi @diaconescur 

it's not a problem. 
There restore is supported only on the current node as it holds the backups and the metadata of backups.

If you want to restore on another server you can copy the backups and then create a db from
the incremental backup

http://orientdb.com/docs/2.2/Incremental-Backup-And-Restore.html

**Comment by diaconescur** [comment]
Thank you for the hint,  it worked.
Have a nice day,

**Comment by maggiolo00** [comment]
Fixed, 
It wil be available in 2.2.18

Thanks
