### ISSUE TITLE
CLUSTER STATUS command returns java.lang.IllegalStateException

### ISSUE THREAD

**Issue by juriskrumins** [orientechnologies/orientdb#7196]
## Expected behavior  
Some cluster status info  

## Actual behavior  
orientdb {db=db}> CLUSTER STATUS

Error: java.lang.IllegalStateException: You must be connected to a remote server to get the cluster status

orientdb {db=db}>

## Steps to reproduce  
1. Connect DB
2. Run CLUSTER STATUS

**Comment by maggiolo00** [comment]
hi @juriskrumins 

how did you connect to the server?

**Comment by juriskrumins** [comment]
Hi @maggiolo00 
By running ./connect.sh and issuing connect remote:localhost/<dbname> <root_user> <root_passwor>. I've also tried 127.0.0.1 IP instead of locahost and node's IP, including other cluster's nodes IPs.

**Comment by maggiolo00** [comment]
hi @juriskrumins 

try to not select a database. It should connect to the server as root.

```
connect remote:localhost <root_user> <root_passwor>
```

**Comment by juriskrumins** [comment]
Excellent. Worked for me. Thanks a log @maggiolo00.
