### ISSUE TITLE
how catch exceptions in an SQL script?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7198]
## Expected behavior  
I want to write some SQL script like this:
```
begin;
any_preceeding_changes;
let new_rid = INSERT INTO blabla ... RETURN @RID ;
if ( not duplicate_record_error) { 
proceed_with_other_actions_using_the_new_rid; 
commit;
};
```

-> how can I capture in such SQL script, the fact that the INSERT generated an error against a UNIQUE index key for trying to insert a duplicate record?
-> in case that insert failed, the any_preceeding_changes must be rolled back; how to achieve that? Mind you that ODB seems not to have an 'else' part for the 'if' statements.

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Right now there is no TRY/CATCH option, so the script just fails.
I think we can add something like this in v 3.0, I'll take it into consideration

Thanks

Luigi
