### ISSUE TITLE
SQL script: Invalid script:Encountered " <LET> "let ""

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7199]
### OS: Ubuntu 16  

Trying to launch this SQL script, both in console (with the preceeding line "script sql") or via the REST-API as a JSON string (I left out the actual property names and values, because the error occurs in all cases/classes:

```
begin;
let var1 = INSERT INTO classname (<listofproperties>) VALUES (<listofvalues>) RETURN @RID;
commit;
```
This returns:
```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Invalid script:Encountered " <LET> "let "" at line 1, column 8.
Was expecting one of:
    <IF> ...
    ";" ...
    <IF> ...

        DB name="mobile"
        DB name="mobile"
```

**Comment by rdelangh** [comment]
I found it ...

One of the properties, "DURATION" is declared of type INTEGER.
During the INSERT, I assign a value of (without the quotes) 0000000900 (just a integer value, prefixed with leading zero's as filler characters).

I found that the ODB parser considers this to be an octal value of there are preceeding zeroes... And hence the digit "9" is invalid.

Changing this value to 0000000700 makes the script succeed as expected.

So : 
- once more, nowhere in the documentation is anything described regarding such leading zeroes, that they make the parser assume that the rest of the digits are to be interpreted as an octal value (so only the digits 0..7 are acceptable)
- the parser is nowhere indicating the correct cause of the -assumed- invalid syntax regarding that -assumed- octal value

-> can this octal interpretation please be documented?
-> can this error message please be corrected?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Ok, I could never understand it from the original issue :-D

I already have a TODO for this: https://github.com/orientechnologies/orientdb-docs/blob/master/SQL-Syntax.md#numbers

Thanks

Luigi
