### ISSUE TITLE
Command Result: can't extract record information after executing a command

### ISSUE THREAD

**Issue by snarlynarwhal** [orientechnologies/orientdb#7203]
## Expected behavior  
When creating a server function within OrientDB Studio, I use the database.executeCommand method. If I return the result, I get:
```
{
  "result": [
    {
      "@type": "d",
      "@rid": "#41:1",
      "@version": 1,
      "@class": "AccountGrain",
      "Username": "John_Doe",
      "Password": "$2a$10$td1u3MG8Bi6wvvr3pJvwK.EKHiGClENXNc/MpwHJjNtjLZHlN7hzG",
      "Email": "Fake@gmail.com",
      "GrainId": "0ee72306-9cdb-401f-8d60-c9e5e3af8230"
    }
  ]
}
```

I expected to be able to access the found records data like so: result.Username or result["Username"]

## Actual Behavior
Instead, if I return result.Username or result["Username"] I get nothing. How do extract data out of the result?

## Steps to Reproduce
1.  Call query or executeCommand and attempt to extract the record's data.

**Comment by luigidellaquila** [comment]
Hi @snarlynarwhal 

Could you please report the exact statement you are using?

Thanks

Luigi

**Comment by snarlynarwhal** [comment]
I couldn't find an example in the documentation so I executed the command like so:
```
var result = db.executeCommand("select...");
```

Then returned `result` and `result[0]` which both gave the same result (mentioned above). However, calling `result.Username` or `result[0].Username returned nothing.`

**Comment by maggiolo00** [comment]
hi @snarlynarwhal 

the result of the db.command should be a list of ODocument (Java) that is not compatible with JSObject. You should use the api `.field` in order to the the field value

`result[0].field("Username")`

**Comment by snarlynarwhal** [comment]
Ahhh, I see - thank you very much!
