### ISSUE TITLE
OrientDB Function converts JSON to object weird

### ISSUE THREAD

**Issue by snarlynarwhal** [orientechnologies/orientdb#7204]
## Expected behavior  
I posted JSON to a server function and wanted to insert that JSON in the database using the content method: INSERT INTO class CONTENT <json goes here> expecting JSON.stringify(object) to convert it to json.

## Actual behavior  
Instead, JSON.stringify(object) returned undefined for some reason. The object itself worked properly: calling object.property did return that property's value. I ended up having to write a helper function that took in the json object and copied its properties into a new object:

```
var object = {};
json.forEach(function(key){
  object[key] = json[key];
});
return object;
```

For some reason, the new object could be stringified properly.

## Steps to reproduce  

1. Post JSON to a server function, call JSON.stringify on the object.

**Comment by maggiolo00** [comment]
hi @snarlynarwhal 

that should be caused by the type of object being a LinkedHashMap
and  JSON.stringify(object)  is not able to stringify it, while works if converted to an actual JSObject.

**Comment by snarlynarwhal** [comment]
Ahhh, I understand - makes sense! I thought the JSON automagically got converted to a JSObject. Might want to mention this in the documentation (it may have just missed it) for other people that might expect the same behavior. Thanks for the speedy reply!

**Comment by lvca** [comment]
Hey @santo-it could you please review our docs with functions according to this issue? Thanks.
