### ISSUE TITLE
Problem with persisting data using spark-orientdb-connector 

### ISSUE THREAD

**Issue by swarooppallapothu** [orientechnologies/orientdb#7207]
## Expected behavior  
-> Persist spark Dataset to orient db

## Actual behavior  
-> While saving Dataset to orient db getting connection problems. For reading it is working as expected (Not getting any connection problems)

## Steps to reproduce  
Following is the code for persisting data.
        Test test = new Test();
        test.setName("abc");
        Encoder<Test> testEncoder = Encoders.bean(Test.class);

        Dataset tableDataset = sqlContext.createDataset(Collections.singletonList(test),
                testEncoder
        );
        tableDataset.show();
        tableDataset.write().format("org.apache.spark.orientdb.documents")
                .option("dburl", "jdbc:orient:REMOTE:localhost/TESTDB")
                .option("user", "root")
                .option("password", "root")
                .option("class", "Test")
                .option("dbtable", "test")
                .mode(SaveMode.Overwrite).save();

**Comment by swarooppallapothu** [comment]
What about scala?

is it implemented for scala?. If yes i will use scala.

**Comment by robfrank** [comment]
AFAIK these connectors are ONLY for scala. Don't know if they works with java.
this one: https://github.com/orientechnologies/spark-orientdb is more updated/active
