### ISSUE TITLE
What's best column type for big text

### ISSUE THREAD

**Issue by hosseinGanjyar** [orientechnologies/orientdb#7208]
### OS: Windows 8.1

I have using ETL for insert data from SqlServer to orientDb. Beacause I've big text in my database (>50,000 bytes), I used "string" format for column in my orientDb databasem, but get error in insert time:
"**_key size is more than allowed,... current size 60172, allowed 10240_**".
- Why [Your Document](http://orientdb.com/docs/2.2/Types.html) Hasn't any sample of Supported Types, for example '**custom**' type?! :(
### ETL:
```
{
  "config": {
    log : "debug"
  },
  "extractor" : {
    "jdbc": { "driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
              "url": "jdbc:sqlserver://*********;databaseName=my_db_sql_server;",
              "userName": "**",
              "userPassword": "****",
              "query": "select * from my_table" 
            }
  },
  "transformers" : [
    {"vertex": { "class": "node_1"}}
  ],
   "loader" : {
    "orientdb": {
      "dbURL": "plocal:D:/orientdb/databases/my_db",
      dbUser: "****",
      dbPassword: "****",
      "dbAutoCreate": true,
      "tx": false,
      "batchCommit": 1000,
      "wal" : false,
      "dbType": "graph",
        "indexes": [
            {"class":"node_1", "fields":["my_text:string"], "type":"FULLTEXT" },
            ...
       ]
    }
  }
}
```

**Comment by saeedtabrizi** [comment]
Hi @hosseinGanjyar , what about indexing for indexing about my_text column . 
I guess you don't need to use sbtree indexing for the big index key in real world such as decreasing the performance .  
I promote to using the lucene index engine for full text indexing that have better perfomance in your case .

**Comment by maggiolo00** [comment]
hi @hosseinGanjyar 

@saeedtabrizi  is right. If you need a big text indexing you should use LUCENE index. The native full text uses under the hood the SB-Tree index, that is not advised for your use case.
