### ISSUE TITLE
OrientDB web Studio not working on IE 11

### ISSUE THREAD

**Issue by rishi3195** [orientechnologies/orientdb#7209]
## Expected behavior  
Normal behaviour of webstudion

## Steps to reproduce  
I have downloaded 2.2.17 and executing via bin/server.bat. console working fine but webstudio is displaying only interrupt. Attached screenshot

![interrupt_screenshot](https://cloud.githubusercontent.com/assets/16130042/23502852/5b57f3d0-ff5f-11e6-90de-7091fb320e9b.png)

**Comment by maggiolo00** [comment]
hi @rishi3195 

does it work with Chrome?

**Comment by rishi3195** [comment]
I don't have chrome on my machine as its not allowed.

**Comment by maggiolo00** [comment]
On my box works with Chrome/Fireforx/Opera.
Let me check with IE

**Comment by maggiolo00** [comment]
Are you able to show me the log of the JS console?

**Comment by rishi3195** [comment]
I am using IE11.
What is JS console?

**Comment by maggiolo00** [comment]
The Javascript Console. I don't know if IE has it
I will check it
Thanks

**Comment by rishi3195** [comment]
![js_console](https://cloud.githubusercontent.com/assets/16130042/23503401/a2886e86-ff61-11e6-880c-08aa536c8243.png)

**Comment by maggiolo00** [comment]
hi @rishi3195 

do you have Microsoft Edge? We did test it there and it works

**Comment by rishi3195** [comment]
cant use any other browser or variant.. its strictly IE11

**Comment by santo-it** [comment]
Hi @rishi3195 , thanks for opening this

We have reproduced the issue and we will work to solve it. We'll keep you updated
