### ISSUE TITLE
Setting a config property does not work, either from console ore from orientdb-server-config.xml

### ISSUE THREAD

**Issue by diaconescur** [orientechnologies/orientdb#7210]
## Expected behavior  
Change a config property (tx.useLog to false) from console or from orientdb-server-config.xml file.
![image](https://cloud.githubusercontent.com/assets/12912432/23513142/b64a485e-ff6b-11e6-8bc6-672bb202a245.png)

After the console.sh is restarted, the "config" command should show the updated property.

## Actual behavior  
The property is shown to the previous value (true), after the console.sh is restarted.

## Steps to reproduce  
console.sh
config set tx.useLog false
config
exit
console.sh
config

**Comment by maggiolo00** [comment]
hi @diaconescur 

the config you are setting from the console are relative to the console process (local), since from the console you can open an embedded database.

if you want to change config of remote database you should connect to the server
`connect remote:localhost root root`
 and then issue the command `config set`

```
tx.useLog
```
cannot be changed at runtime

**Comment by diaconescur** [comment]
Hello,
The same happens.
 console.sh
connect remote:164.61.90.196/KeyProvider root ****
config set tx.useLog false
exit
![image](https://cloud.githubusercontent.com/assets/12912432/24444220/5373b70c-146e-11e7-87af-5fb76778fdff.png)

Now I connect again:
 console.sh
connect remote:164.61.90.196/KeyProvider root ****
config
![image](https://cloud.githubusercontent.com/assets/12912432/24444254/69c4e3c8-146e-11e7-8677-a34bd50b0ec8.png)

And the changed config lost it's value (it is reseted to true).
Thank you

**Comment by maggiolo00** [comment]
hi @diaconescur 

in order to change the configu you should connect to the server, not a specific database.

```
connect remote:164.61.90.*** root ****
```

without `/myDb`

**Comment by diaconescur** [comment]
Hello,
Done that and I get the following error:

**orientdb {server=remote:164.61.90.***/}> config set tx.useLog false
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot set the configuration value: tx.useLog
Error: com.orientechnologies.orient.core.exception.OConfigurationException: Property 'tx.useLog' cannot be changed at runtime. Change the setting at startup**

Thank you.

**Comment by kunkun2858** [comment]
Hi, I have meet the same problem with orientdb-2.2.15. I use the debug and find that the propreties I set in orientdb-server-config.xml has been add to the 'value' field.
![Uploading 70608114708.png…]()
Is it effect?
