### ISSUE TITLE
ReadOnly Constraint Prevents Editing of Nodes from Web Studio UI

### ISSUE THREAD

**Issue by petermo13** [orientechnologies/orientdb#7211]
### OrientDB Version: <version here>  
Studio version : 2.2
OrientDB version : 2.2.13
### Java Version: <version here>  
java version "1.8.0_121"
### OS: <os here>  
Windows 7
## Expected behavior  
Edit Node Values & Commit

## Actual behavior  
Looks like it works, but it does not after refresh of screen.

## Steps to reproduce  
CREATE PROPERTY V.creationDT Datetime (DEFAULT sysdate(), READONLY TRUE);

# Create a subclass of V
CREATE CLASS Group EXTENDS V;
CREATE PROPERTY Group.groupName STRING;
CREATE PROPERTY Group.description STRING;

# Create and Edit a Node of Group using the "Graph" Tab from Web Studio using the GUI
It will look like it works at first.
Remove the Node from the screen, or simply clear the Canvas.
Click the "Browse" Tab and then come back to the "Graph" Tab.
select from v;
You will notice the data has not changed, and no error message was given.

if you try to edit the node from the "Browse" tab, it will throw an error saying that since creationDT field was set to readonly, we cannot edit any other fields, which is a problem.
![readonlyerror](https://cloud.githubusercontent.com/assets/5331719/23518606/419956b0-ff31-11e6-9e5f-280a06d02841.PNG)

That is also another bug i think.

Thanks

**Comment by maggiolo00** [comment]
hi @petermo13 

i did reproduce it. Seems that it's a problem of the http layer.
I will let you know

Thanks

**Comment by tglman** [comment]
Hi,

Fixed closing.
