### ISSUE TITLE
Match: search by edge and no vertex class: Class not found: null

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7214]
## Expected behavior  

Allow searches when no vertex class is specified (but only edge class)

## Actual behavior  

An error is returned:

on 2.2.: `com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot calculate this pattern (maybe a circular dependency on $matched conditions)`

on 3.0: `com.orientechnologies.orient.core.exception.OCommandExecutionException: Class not found: null`

## Steps to reproduce  

demodb

```
#works 
match {class: Orders, as: n}-HasCustomer->{class: Customers, as: m} return $pathelements

#works 
match {class: Orders, as: n}-HasCustomer->{as: m} return $pathelements

#works 
match {as: n}-HasCustomer->{class: Customers, as: m} return $pathelements

#does not work 
match {as: n}-HasCustomer->{as: m} return $pathelements
```

**Comment by luigidellaquila** [comment]
Hi @santo-it 

With lightweight edges it's just impossible to efficiently implement it. 
(This is one of the reasons why I really would like to see lightweight edges deprecated...).
I can work around this just considering that elements in curly braces are vertices (implicit `class:V`), but in the typical case it won't be efficient

Thanks

Luigi

**Comment by santo-it** [comment]
This is the workaround:

```
MATCH {as: sv}.outE(){class: HasVisited, as: e}.inV(){as: ev} 
RETURN $pathelements
LIMIT 50
```

So it is possible to easily search by edge class (without specifying the class of starting and ending vertices). Just the form outE(){class: ClassName}inV() has to be used, instead of -ClassName-
