### ISSUE TITLE
what is .include() for and what should it do?

### ISSUE THREAD

**Issue by UltraMarco** [orientechnologies/orientdb#7218]
## Expected behavior  
I thought `SELECT @this.include(nome) FROM Persona` should behave similar to `SELECT nome FROM Persona` and give something like:  
  
```
 {  
     "result": [  
         {  
             "@type": "d",  
             "@rid": "#-2:0",  
             "@version": 0,  
             "nome": "Marco"  
         },  
         {  
             "@type": "d",  
             "@rid": "#-2:1",  
             "@version": 0,  
             "nome": "Luigi"  
         }  
     ]  
 }
```

## Actual behavior  
The value of "nome" field becomes the key in new records, making impossible to .include() @rid and other LINK fields, as ":" is not allowed in field names.

```
 {
     "result": [
         {
             "@type": "d",
             "@rid": "#-2:0",
             "@version": 0,
             "this": {
                 "@type": "d",
                 "@version": 0,
                 "Marco": null
             }
         },
         {
             "@type": "d",
             "@rid": "#-2:1",
             "@version": 0,
             "this": {
                 "@type": "d",
                 "@version": 0,
                 "Luigi": null
             }
         }  
     ]  
 }
```

## Steps to reproduce  
CREATE CLASS Persona  
CREATE PROPERTY Persona.nome STRING
INSERT INTO Persona (nome) VALUES ('Marco'), ('Luigi')
SELECT @this.include(nome) FROM Persona

**Comment by maggiolo00** [comment]
hi @UltraMarco 

from the example in the docs, you should use strings instead of identifiers.

http://orientdb.com/docs/2.2/SQL-Methods.html

```
SELECT @this.include('nome') FROM Persona
```
Hope it helps
