### ISSUE TITLE
is it possible to rename an existing database?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7221]
## Expected behavior  
Is there any way to change the name of a existing database?

**Comment by marigonda** [comment]
I'm also interested on this issue...

**Comment by laa** [comment]
Hi you can rename embedded database if you rename all WAL files (they have the same name as name of database) and rename database folder

**Comment by marigonda** [comment]
It worked!  (I had just to rename two files, .wmr and .wal, and the database directory - in both servers cause they are clustered....) Thanks!

**Comment by laa** [comment]
Cool ))

**Comment by triketora** [comment]
Where are the .wmr and .wal files located?

**Comment by laa** [comment]
@triketora inside your database folder.
