### ISSUE TITLE
Unexpected behavior of "class:" clause when used with "while:" or "optional: true"

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#7225]
## Expected behavior  
In a MATCH query, a `class: Bar` clause should be evaluated after any `while: ...` or `optional: true` clauses, and should behave indistinguishably from a `where: (@this instanceof Bar)` clause. This is consistent with the specification of `MATCH` and `instanceof` in the docs. Two concrete situations:
- If a MATCH step is marked optional, and a particular traversal finds no vertex for that MATCH step, the `class: ...` clause should be ignored (exactly as the `where:` clause is ignored) and the result should contain `null` for that MATCH step.
- In a MATCH step with `while: ...`, the `while:` is resolved before the `class:` clause -- some number of iterations are performed as the `while:` directs, and then the resulting vertices are tested for conformance with the `class:` clause.

## Actual behavior  
`class: Bar` does not behave the same way as `where: (@this instanceof Bar)`. Specifically:
- Inside an optional MATCH step, in some cases `class: Bar` causes empty results to be returned, whereas `where: (@this instanceof Bar)` returns results with `null` for the optional step.
- In MATCH steps with `while:` clauses, `class: Bar` causes the `while:` traversal to stop at the first vertex which is not a subclass of `Bar`, whereas `where: (@this instanceof Bar)` iterates fully and simply does not return non-`Bar` vertices in the end. In other words, with a `while:` depth of 4, for a set of vertices connected as: `Bar -> Bar -> Foo -> Bar`, using `class:` will only return the first two `Bar`s whereas using the `where:` approach will return all three `Bar`s.

## Steps to reproduce  
Setup:
```
CREATE CLASS Base EXTENDS V
CREATE CLASS Foo EXTENDS Base
CREATE CLASS Bar EXTENDS Base

CREATE VERTEX Foo SET name = 'foo1'
CREATE VERTEX Foo SET name = 'foo2'
CREATE VERTEX Foo SET name = 'foo3'
CREATE VERTEX Bar SET name = 'bar1'
CREATE VERTEX Bar SET name = 'bar2'
CREATE VERTEX Bar SET name = 'bar3'

CREATE EDGE E FROM (SELECT FROM Foo WHERE name = 'foo1') TO (SELECT FROM Bar WHERE name = 'bar2')
CREATE EDGE E FROM (SELECT FROM Foo WHERE name = 'foo2') TO (SELECT FROM Bar WHERE name = 'bar3')
CREATE EDGE E FROM (SELECT FROM Bar WHERE name = 'bar1') TO (SELECT FROM Foo WHERE name = 'foo2')
CREATE EDGE E FROM (SELECT FROM Bar WHERE name = 'bar2') TO (SELECT FROM Foo WHERE name = 'foo3')
```

`Foo` vertices are only connected to `Bar` vertices, and vice versa. Edges always go from number `i` to `i+1`.

### Unintuitive `optional: true` behavior with `class:`
The following query returns one row with `end` set to `null`, as expected (the last edge is Bar to Bar, which doesn't exist):
```
MATCH {
    class: Foo,
    where: (name = 'foo1'),
    as: start
}.out('E') {
    where: (name = 'bar2'),
    as: mid
}.out('E') {
    optional: true,
    where: (@this INSTANCEOF Bar)
    as: end
}
RETURN $matches
```

However, using `class:` instead of the `where:` returns no rows:
```
MATCH {
    class: Foo,
    where: (name = 'foo1'),
    as: start
}.out('E') {
    where: (name = 'bar2'),
    as: mid
}.out('E') {
    class: Bar,
    optional: true,
    as: end
}
RETURN $matches
```

### Unintuitive `while:` behavior with `class:`
The following query returns two rows, as expected (one with `start = mid` and one with `mid` two hops away from `start`):
```
MATCH {
    class: Foo,
    where: (name = 'foo1'),
    as: start
}.out('E') {
    while: ($depth < 4),
    where: (@this INSTANCEOF Foo),
    as: mid
}
RETURN $matches
```

However, using `class:` instead of the `where:` returns only one row, the one with `start = mid`:
```
MATCH {
    class: Foo,
    where: (name = 'foo1'),
    as: start
}.out('E') {
    class: Foo,
    while: ($depth < 4),
    as: mid
}
RETURN $matches
```

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

Thank you very much for reporting, I'll try to take it a look asap. If you have a repro, for sure it will help

Thanks

Luigi

**Comment by obi1kenobi** [comment]
Updated the top post with a repro. Thanks for looking into it!

**Comment by obi1kenobi** [comment]
Hey @luigidellaquila, just checking in to see if you were able to find something here! As always, let me know if I can help with anything :)

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

Sorry, I still had no chance to look into it (a bit of trouble for the release of 3.0 M1...) I'll try to do it in next few days

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I just pushed a fix for the first case. I'm still analyzing the second one, but I think it should not be hard to fix

Thanks

Luigi

**Comment by obi1kenobi** [comment]
Hi @luigidellaquila, thanks for looking into this!

I was looking at your commit that fixed the first case, and I noticed you replaced the `if (filter == null || filter.matchesFilters(startingPoint, ctx)) {` with a more thorough check in the `depth == 1` case. The `else` case just below has that same line, so shouldn't that one be replaced in a similar fashion? Otherwise, it seems like we might be able to hit the same bug in different circumstances.

**Comment by luigidellaquila** [comment]
yes, probably you are right, but that part also impacts the deep traversal, that is your second case.

I'll let you know soon about the final fix

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I just pushed a fix and a test case for this issue

Closing, thanks!

Luigi

**Comment by obi1kenobi** [comment]
Great, thank you! Looking forward to the next release!
