### ISSUE TITLE
heap size tunings are ignored in v2.2.18

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7226]
## Expected behavior  

The script "bin/server.sh" contains customisations for the heap sizes:
```
more bin/server.sh
...
if [ -z "$ORIENTDB_OPTS_MEMORY" ] ; then
    ORIENTDB_OPTS_MEMORY="-Xms1G -Xmx10G"
fi
...
exec "$JAVA" $JAVA_OPTS \
    $ORIENTDB_OPTS_MEMORY \
    $JAVA_OPTS_SCRIPT \
    $ORIENTDB_SETTINGS \
```

However the program seems to ignore these settings and uses 4G for both parameters:
```
java -server -Xms4G -Xmx4G -Djna.nosys=true ...
```

This causes OOM situation while trying to replicate databases to a 2nd node in a group (cfr #6666)

**Comment by robfrank** [comment]
You should export ORIENTDB_OPTS_MEMORY with your settings before run the script:
```
export ORIENTDB_OPTS_MEMORY="-Xms4G -Xmx4G"
server.sh
```

**Comment by robfrank** [comment]
To override internal heap settings, please export  ORIENTDB_OPTS_MEMORY before run server.sh:
```
export ORIENTDB_OPTS_MEMORY="-Xms4G -Xmx4G"
./server.sh
```

Moreover, check your env, I guess the variable is exported with 4G as vaules and it overrides your customization of the script.

**Comment by rdelangh** [comment]
I noticed that the overriden heap settings are ignored only when starting the server in distributed more:

Exactly the same server script, but started in standalone mode:
```
java -server -Xms4G -Xmx12G -Djna.nosys=true ...
```

When started in distributed mode:
```
java -server -Xms4G -Xmx4G -Djna.nosys=true ...
```

**Comment by robfrank** [comment]
This is strange, the scripts are identical, apart from memory settings and the distributed flag set to true
. Did you export your override before running the server?

**Comment by rdelangh** [comment]
No, I did not export the override. When launching the server in standalone mode, the changed settings are considered (cfr the options on the command line).

When I export the env variable, then indeed the server process starts with the changed heap settings:
```
java -server -Xms4G -Xmx12G -Djna.nosys=true ...
```

-> please fix this incorrect behaviour.

**Comment by robfrank** [comment]
The right way to provide an override to the script is to export custom settings BEFORE running it. If you provide additional JVM's arguments to the script, the MAYBE will override the ones defined in the script, but it is not guaranteed by the JVM itself.  I tested the export with server.sh and dserver.sh and it works with both. LGTM.

**Comment by rdelangh** [comment]
@robfrank 
1) thanks, setting the environment variables OUTSIDE "server.sh" works
2) unfortunately, like in many parts of the documentation: the documentation does not reflect (clearly) the behaviour of the OrientDB server process: http://orientdb.com/docs/2.2.x/Configuration.html says explicitly "You can pass settings via command line when the JVM is launched. This is typically stored inside server.sh"

-> this prescribed way in the documentation does not work
-> please bring the documentation in line with the server behaviour

**Comment by robfrank** [comment]
Usually providing overrides on the command line works: you will see heap setting two times in your process (ps aux). Usually, the JVM picks the last one (the last wins), but this behavior of the JVM is undocumented and can change, or it can be different among different JVMs (e.g.: openjdk vs IBM). 
So:
```
server.sh -Xmx20G
```
SHOULD works. You will see in the process list (ps aux):
```
java -server -Xms4G -Xmx12G -Djna.nosys=true ... A LOT OF OPTIONS ... -Xmx10G ...
```
So, understand wich option is in place could be hard.
I'm going to review the docs about scripts during this week. 
If you want, you can fork the docs (or edit directly on line) and submit a PR.
