### ISSUE TITLE
Can't connect third node to the cluster of 2 other.

### ISSUE THREAD

**Issue by juriskrumins** [orientechnologies/orientdb#7227]
## Expected behavior  
After starting OrientDB service on third node it should be a a cluster member.

## Actual behavior  
It's not a member of cluster  

## Steps to reproduce  
service orientdb stop
service orientdb start
Check orient-server.log.0 logs and use CLUSTER STATUS command on currently running cluster.

**Comment by rdelangh** [comment]
at least you managed to get a 2nd node working together with the 1st node... My servers still don't manage to make a 2-node cluster... See #6666 (warning: long saga)

**Comment by lvca** [comment]
Hi @juriskrumins, please use 2.2.x, not 2.1.x. In case of problems, also please send the logs.

**Comment by lvca** [comment]
@rdelangh any news on this?

**Comment by lvca** [comment]
Closing because no response. In case please comment this issue. Thanks.
