### ISSUE TITLE
OrientGraphFactory : calling both getTx and getNoTx forces transactional behavior

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#7232]
## Expected behavior  
Calling OrientGraphFactory.getTx should not interfere with the usage of the graph retrieved using OrientGraphFactory.getNoTx.

## Actual behavior  
Calling getTx() even if getNoTx()'s graph is used causes an info message concerning transactions.  Upon further investigation, if the graph from getNoTx() is used, it will not actually be transactionless if getTx() had been called.  You can write via the getNoTx(), rollback the graph from getTx() and all changes made are lost.

Either this is a bug or the the factory should prevent the usage of both transactional and non-transactional graphs.  If it is not a bug, how are you supposed to perform non-transactional statements while using a transactional graph (e.g. for auditing purposes)?

## Steps to reproduce  
```
    @Test
    public void testNoTx() {
        OrientGraphFactory oGF = new OrientGraphFactory("plocal:test1");
        OrientGraphNoTx noTx = oGF.getNoTx();
        //This does not cause an info message
        noTx.createVertexType("Test");
    }
    @Test
    public void testTxAndNoTx() {
        OrientGraphFactory oGF = new OrientGraphFactory("plocal:test2");
        OrientGraph     tx   = oGF.getTx();
        OrientGraphNoTx noTx = oGF.getNoTx();
        //Causes info message "Requested command 'create vertex type 'Test' as 
        //subclass of 'V'' must be executed outside active transaction: the 
        //transaction will be committed and reopen right after it. To avoid this 
        //behavior execute it outside a transaction"
        //Due to the call to oGF.getTx()
        noTx.createVertexType("Test");
    }
    @Test
    public void writeOutsideOfTransaction() {
        OrientGraphFactory oGF = new OrientGraphFactory("plocal:test3");
        OrientGraph     graph     = oGF.getTx();
        OrientGraphNoTx graphNoTx = oGF.getNoTx();
        
        graph.createVertexType("Car");
        OrientVertex v = graph.addVertex("class:Car", "name", "Mustang");
        
        System.out.format("before commit : %s %s %n", v, v.getProperty("name"));
        graph.commit();
        System.out.format("after commit  : %s %s %n", v, v.getProperty("name"));
        
        //Do something non-transactional (e.g. change the name of Mustang to Corvette)
        graphNoTx.getVertices("name","Mustang").iterator().next().setProperty("name", "Corvette");
        
        //Commit the transaction (should only have Car name=Corvette)
        graph.rollback();
        
        //But it doesn't
        v.reload();
        //Will print Mustang even though it had been changed to Corvette non-transactionally
        System.out.format("after reload  : %s %s %n", v, v.getProperty("name"));
        System.out.format("Corvette exists? %s%n",   graph.getVertices("name","Corvette").iterator().hasNext());
    }
```

**Comment by tglman** [comment]
hi @odbuser2,

As today the OrientGraphFactory if there is a database open on the current thread when you call getTx() or getNoTx() it return the database active on the current thread.
to be sure that you use two distinct database instance make sure that you have only one active on the current thread.
like:
```
        OrientGraphFactory oGF = new OrientGraphFactory("plocal:test3");
        OrientGraph     graph     = oGF.getTx();
        // do staff on tx.
        graph.shutdown();
        OrientGraphNoTx graphNoTx = oGF.getNoTx();
        // do staff on noTx.
        graphNoTx.shutdown();
```

we have already received the same feedback from other users and in future (major)version we are going to remove this behaviour, but this will not change in the 2.x version, because of compatibility reasons.

Regards

**Comment by odbuser2** [comment]
Ok, maybe the javadoc could be updated to clarify this.

**Comment by tglman** [comment]
hi @odbuser2,

Yes, thank you for the suggestion, anyway in 3.0 we are removing this behaviour, doing what you expect, can we close this issue?

Regards

**Comment by tglman** [comment]
Hi,

Closing, I guess we already gave all the answers, feel free to reopen if you have some doubts.

Regards
