### ISSUE TITLE
When querying in range less than any value greater than max int (2147483647), integer rolls over to negative and returns zero values

### ISSUE THREAD

**Issue by matt24smith** [orientechnologies/orientdb#7234]
## Expected behavior  
OrientDB should either return my results using max int value or display an error that value is too large.

## Actual behavior  
OrientDB takes a long time to query, then returns with 0 items found

## Steps to reproduce  
Query database with a range specified on integer property with a range value greater than 2147483647. 
Example:
SELECT * FROM logs WHERE time >= 50000 AND time <=3000000000 LIMIT -1

>0 item(s) found. Query executed in 492.468 sec(s).

Note that the query time can be sped up by using a smaller dataset or using a limit. With our large dataset, this takes a very long time to compute despite being indexed.

**Comment by luigidellaquila** [comment]
Hi @matt24smith 

Thank you for reporting, I just pushed a fix on 2.2.x branch, the fix will be released with 2.2.18

Thanks

Luigi
