### ISSUE TITLE
OPartitionedDatabasePool when loaded with more than 20 threads returns same db connection with hashcode

### ISSUE THREAD

**Issue by likesh1980** [orientechnologies/orientdb#7235]
## Expected behavior  
We were expecting when we use the pool.acquire method from OPartitionedDatabasePool class, it should provide a unique db connection and hashcode to be used in a multithreaded spring boot application which currently uses the orientdb spring data modules. But it seems like when number of users are more than 20 accessing the same we are getting the same db connection and hashcode which causes the following error:

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: The current database instance (com.
orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled@6ba64c61) is not active on the current thread (Thread[qtp1159114532-15,5,main]). Curr
ent active database is: com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled@7ad45a17

## Actual behavior  
We should be getting a distinct db connection from the connection pool and the above error should not be happening.

## Steps to reproduce  
Using Jmeter if we run a load test to send more than 200 requests then this can be reproduced. We need to make sure jmeter thread count should be more than 20 or so. Here as shown below if you see thread number 15 and 17 both are getting the same database connection object 1099787001, which in turn makes one of the thread error out as shown above.

2017-03-14 16:05:45.936 DEBUG 31797 [qtp1159114532-15] --- .s.d.o.c.c.AbstractOrientDatabaseFactory : use existing db 1099787001
2017-03-14 16:05:45.936 DEBUG 31797 [qtp1159114532-17] --- o.s.d.o.c.core.OrientTransactionManager  : beginning transaction, db.hashCode() = 1099787001

**Comment by laa** [comment]
Hi, I have created following code https://gist.github.com/laa/9f52156237fa5200012f9fc99fc07224 . This code creates 200 threads each of threads creates separate connection and wait till all thread does not acquire 200 connections. All connections are stored in ConcurrentHashMap, and it is checked that there are no duplications of connections in other threads. Then all connections are removed. This cycle is repeated 1000 times (also I have run the same test 1 000 000 times too). As a result, I have got following output https://gist.github.com/laa/692e7c1418ce89998f125a0749640b1a as you can see test did not detect any duplications of connections.  I do not think that we have described the bug in a connection pool. Do you have any objections?

**Comment by likesh1980** [comment]
Hi, Thanks a lot for responding to my issue. I really appreciate this. The issue does not surround around the db object not returned, but the issue surrounds when the same db object is returned to 2 threads at same time, then one thread errors out when trying to do the db operations. I will try to modify your junit test case and send you a sample program or so, which you can test it out. FYI, I am using your spring data project from orient db with spring boot and it submits the requests to rest controller and rest controller in turn uses the repository from spring data with shared connection pool to do the updates. This is the time when same db connection object is returned to both threads it errors out as the last thread which gets the object works fine, but earlier threads error out. Please hold on for a week or so and I will build a sample project and send to you for testing purpose using orient db spring data module. Thanks, Likesh

**Comment by likesh1980** [comment]
Please download the spring data module from orientdb github location @ https://github.com/orientechnologies/spring-data-orientdb/tree/2.2.x and startup the /spring-boot-orientdb-hello/src/main/java/org/springframework/boot/orientdb/hello/HelloApplication.java. This should start the restcontroller using orientdb spring data module and youc an chnage th epom file to use 2.2.17 version to make sure you are using latest orientdb. Once you started the HelloApplication, please find my attached jmeter test file where I am submitting a get request to its rest URI http://localhost:8080/persons/findByAge?age=25 with 20 threads each submitting 1000 request. You will find some times the threads will fail with the following exception:

java.lang.IllegalStateException: The current database instance (com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled@3cb96009) is not active on the current thread (Thread[http-nio-8080-exec-10,5,main]). Current active database is: com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled@512c8fb5

Please find the Jmeter file which you can execute:

[OrientDBPersonServiceTest.zip](https://github.com/orientechnologies/orientdb/files/877463/OrientDBPersonServiceTest.zip)

Just FYI, the same issue someone raised in Spring Data Orient DB module as well as follows:

https://github.com/orientechnologies/spring-data-orientdb/issues/68

**Comment by likesh1980** [comment]
Just a further update I did some testing with the junit java file provided and found that OPartitionedDatabasePool is returning same db object, if you search for the hashcode value for 1878153924 inside the test_results_from_junit.txt file, then you can see it is being assigned to multiple threads from pool at same time, sample examples are as follows (initially the object was assigned to thread 18 and then it went to thread 144 which means later point if any request will come to thread 18 then it will error out):

19:59:23.462 [pool-2-thread-18] DEBUG c.o.o.c.db.OPartitionedDatabasePool - db object returned is: 1878153924

19:59:23.588 [pool-2-thread-18] DEBUG c.o.o.c.db.OPartitionedDatabasePool - db object returned is: 1878153924

19:59:23.588 [pool-2-thread-144] DEBUG c.o.o.c.db.OPartitionedDatabasePool - db object returned is: 1878153924

19:59:23.619 [pool-2-thread-144] DEBUG c.o.o.c.db.OPartitionedDatabasePool - db object returned is: 1878153924
19:59:23.728 [pool-2-thread-144] DEBUG c.o.o.c.db.OPartitionedDatabasePool - db object returned is: 1878153924

19:59:23.728 [pool-2-thread-144] DEBUG c.o.o.c.db.OPartitionedDatabasePool - db object returned is: 1878153924

Please find the attached files where in OPartitionedDatabasePool acquire method I added some additional logging statements to see what is being returned to the junit program. And also please find the junit java program where I made connection pool to have 2000 max connection pools and also the test result file where you can search for duplicate db hashcodes.

Any help you can provide to get this fixed is really appreciated as our company is thinking about purchasing enterprise license in coming year if all goes good in our prototypes.

Regards,
Likesh

[orientdb_springdata_issues.zip](https://github.com/orientechnologies/orientdb/files/877591/orientdb_springdata_issues.zip)

**Comment by laa** [comment]
Assigned to @robfrank as he does most of development activity in ODB spring-data module.

**Comment by likesh1980** [comment]
Thanks a lot @laa (Andrey). I really appreciate your help on this and I will wait to see what @robfrank (Roberto) finds out as if needed I can easily demonstrate this, but with the Jmeter file I provided, it is very easy to reproduce. But still if you want me to demonstrate, I can do that in a web meeting or so.

**Comment by likesh1980** [comment]
Hello @laa and/or @robfrank, please advise if any updates on this issues as this is a driving factor for us to decide whether to use orientdb or not.

**Comment by likesh1980** [comment]
I closed by mistake. Hence reopening and hoping some response from @laa and/or @robfrank, please advise if any updates on this issues as this is a driving factor for us to decide whether to use orientdb or not.

**Comment by robfrank** [comment]
Hi, I used the Jmeter configuration and your Junit test. 
Jmeter works fine, no exceptions are raised inside the spring-boot application.
About the Juni test, it doesn't fail, and looking at the code if the same db is assigned to different threads at the same time it should fail, isn't it?

**Comment by robfrank** [comment]
could you check with latest 2.2.21?

**Comment by likesh1980** [comment]
Hi @robfrank I will try with 2.2.21 but if you have some time I can replicate this in front of you with Jmeter code as well. The issue is that it works fine for some time with a Java application and after that all requests fails with the same error message, somehow I have a feeling the validation does not look correct and all requests started failing.

**Comment by likesh1980** [comment]
Hi @robfrank, I added some logging and if you see using spring data it is getting the same database object (db.hashCode() = 121375752) in 2 threads if you see thread number 15 and 18 from pool (qtp85445963-18 and qtp85445963-15), where as the pool should be providing different  db objects, so I think this is an issue with pool code in orientdb if you agree based on log below.

2017-06-15 13:30:53.147 DEBUG 12665 [qtp85445963-15] --- .s.d.o.c.c.AbstractOrientDatabaseFactory : After opening database: qtp85445963-15: 121375752
2017-06-15 13:30:53.147 DEBUG 12665 [qtp85445963-18] --- o.s.d.o.c.core.OrientTransactionManager  : beginning transaction, db.hashCode() = 121375752
2017-06-15 13:30:53.147 DEBUG 12665 [qtp85445963-15] --- o.s.d.o.c.core.OrientTransactionManager  : beginning transaction, db.hashCode() = 121375752
2017-06-15 13:30:53.151 DEBUG 12665 [qtp85445963-18] --- .m.m.a.ExceptionHandlerExceptionResolver : Resolving exception from handler [public org.springframework.boot.orientdb.cds.data.Status org.springframework.boot.orientdb.cds.rest.TicketController.createTicket(org.springframework.boot.orientdb.cds.data.Ticket)]: java.lang.IllegalStateException: The current database instance (com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled@4215ead1) is not active on the current thread (Thread[qtp85445963-18,5,main]). Current active database is: com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled@b8410f7

**Comment by robfrank** [comment]
wich version of OrientDB spring  data?

**Comment by likesh1980** [comment]
Hi @robfrank , I am using 0.14-SNAPSHOT version of orientdb spring data. If you want I can take the latest version or so.

**Comment by robfrank** [comment]
I released 0.14, if you prefer a stable version

**Comment by likesh1980** [comment]
Thanks @robfrank . I will try with that and update what I find and if the issue is fixed.

**Comment by robfrank** [comment]
closing. Feel free to reopen the issue
