### ISSUE TITLE
Lucene indexes silently get corrupted

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7237]
## Expected behavior  
While testing a true big database, it happens often that I encounter an OOM situation with the OrientDB engine. This seems to cause corrupted Lucene indexes, without any trace of them being corrupted except for suspicious unfound data when we query such index explicitly with "SELECT FROM index:<someindexname> ...". 
When I rebuild the suspected Lucene indexes, the records that we are searching for are now properly found. 

-> how can a corrupted Lucene be detected ?

**Comment by rdelangh** [comment]
hi gurus,
has anyone some feedback on this, please?
We hit an OOM again, and some Lucene indexes have become silently corrupted again: they still exist, I can SELECT from them, but they do not return all expected results unless after I rebuild them.

**Comment by maggiolo00** [comment]
hi @rdelangh 

did you shutdown the server with kill after OOM?

**Comment by rdelangh** [comment]
@maggiolo00 
yes, that is the only way to stop the process after such situation, since the "shutdown" script can trigger the shutdown of the ODB server process only till the point where it tries to close the databases. At that point, it hangs and becomes totally unresponsive. Only a kill can stop the process.

**Comment by maggiolo00** [comment]
@rdelangh 

the main problem is that lucene indexes are not yet backed by WAL. Once killed if the server does not trigger the rebuilding, you should manually invoke it.

**Comment by rdelangh** [comment]
@maggiolo00 
Enrico, is there no possibility at all to check the consistency of a Lucene index, prior to launching blindly their rebuilding (rebuilding in our case takes approx 1 hour per index, I have MANY indexes!!) ?

**Comment by maggiolo00** [comment]
@rdelangh 

how many indexes do you have? 
Let me check but i think there is not way to check this

**Comment by rdelangh** [comment]
@maggiolo00 
in one database, there are 104 indexes; in a second database, there are 220 indexes
Each of these indexes refers to approx 100-140M documents.

So rebuilding all of these indexes is unfeasable. We really need a way to find out if an index has become inconsistent or not, so that we can reduce the number of index rebuilds.

**Comment by maggiolo00** [comment]
@rdelangh 
are they all lucene indexes?

**Comment by rdelangh** [comment]
2/3 of these indexes are Lucene. So, way too many to start a default rebuild of all of them.

**Comment by rdelangh** [comment]
hi @maggiolo00 
you mentioned before that Lucene is not WAL protected, but it should maintain consistency during an OOM situation, like this article suggests:
https://dzone.com/articles/exploring-transactional-0

-> is the description from this article applicable to our situations?

**Comment by maggiolo00** [comment]
hi @rdelangh 

the problem is that yes it is transactional in the sense that the index does not get corrupted.
But we integrated it with the lifecycle of OrientDB and we use NTR for more performance in indexing.
What is missing is what the link says

> Lucene does not implement a transaction log itself, but it's easy to build that layer out on top

We should implement this on top of OrientDB WAL to ensure that a single operation 
insert + index update  is backed by WAL. This is true for native indexing but not for Lucene implementation. 

We are investigating this integration
