### ISSUE TITLE
NullPointerException when execute query on lucene index

### ISSUE THREAD

**Issue by gammaliu** [orientechnologies/orientdb#7238]
## Expected behavior  
1) I have created a lucene index through:
`create index lucene_index fulltext engine lucene string`
2) and I have insert some key-value pair into this index:
`insert into index:lucene_index (key,rid) values ("Lucene Index Test" , #11:11)`
3) but when I try to query this index without where clause, exception returned:
`select from index:lucene_index`
console traceback is:
`
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from index:lucene_index
        DB name="ConsoleDemo"
        DB name="ConsoleDemo"
Error: java.lang.NullPointerException
`

## Actual behavior  
return all index (key,value) pair

**Comment by maggiolo00** [comment]
hi @gammaliu 

this is a known issues. Lucene Index does not support the cursor on the index.
There is this open issue to handle a better error message instead of NPE

https://github.com/orientechnologies/orientdb/issues/7156

Thanks
