### ISSUE TITLE
Micro-transactions

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#7239]
At this moment, consistency of non-tx operations is provided by index key locking. This mechanism is an alien from the storage layer perspective. It may lead to deadlocks if the layer bounds crossed multiple times during an operation, the order of such crossings must be carefully controlled. It may lead to data inconsistency since the storage layer is not developed with index key locking in mind, see #6979.

The obvious solution is to use existing transaction facilities to wrap all non-tx operations into implicit transactions. We have tried this, but it didn't play well with the distributed layer due its implementation peculiarities which are hard to fix at this point.

We may solve this by introducing another kind of transactions in between the database layer and the storage layer. So the current non-tx interaction `client -(key locking, direct calls)-> database -(direct calls)-> storage -(binary tx)-> data` will become `client -(direct calls)-> database -(micro tx)-> storage -(binary tx)-> data`.

In the future the current tx interaction `client -(regular tx)-> database -(direct calls)-> storage -(binary tx)-> data` may be transformed into `client -(client tx)-> database -(micro tx)-> storage -(binary tx)-> data` using this mechanism.

The main concern is keeping the compatibility with the current hooks runtime implementation. This hugely complicates things, hooks may modify and replace the records being passed to the database, create the new ones and delete the existing ones. They must be orchestrated in the right order, so it's impossible just to strip out the current implementation from the hooks.

It's still an open question should a single-record operation form an atomic unit that includes all related hooks operations or not. The first approach leads to a new full-fledged transaction runtime in parallel to the existing one. The second approach leads to an implementation highly coupled to the database layer since the hooks are managed on it, and they must be invoked during the micro-tx commit that occurs on the storage layer.

**Comment by luigidellaquila** [comment]
If this is the decision, probably it's worth completely reviewing hooks API in v 3.0, otherwise it will be practically unusable at user level...

**Comment by taburet** [comment]
Implemented, finally :) @luigidellaquila nested operations, for example from hooks, form a single atomic unit.

**Comment by luigidellaquila** [comment]
@taburet out of curiosity, how hard would it be implementing graph operations (edge/vertex creation and removal) as micro-tx?

Thanks

Luigi

**Comment by taburet** [comment]
@luigidellaquila it should be relatively easy, mostly it's just a question of providing the internal storage functionality to the outside world.

**Comment by laa** [comment]
>  mostly it's just a question of providing the internal storage functionality to the outside world

Which I quite against of.

**Comment by luigidellaquila** [comment]
well, another solution would be to move graph concepts down to the storage, but I don't know if it can be considered a better option or if it's easy to do...

**Comment by taburet** [comment]
BTW, I doubt there will be any significant performance advantages comparing to regular transactions. Are regular transactions suitable for this task?

**Comment by luigidellaquila** [comment]
Yes, absolutely! This was my initial proposal, but it was evaluated as too expensive...
@lvca WDYT?

Luigi

**Comment by lvca** [comment]
We only need addEdge and removeEdge operations. Since we're a multi-model and we want to be rock-solid, it's something we could think about it. WDYT?

**Comment by luigidellaquila** [comment]
+1
In v 3.0 all the logic for edge management is in OEdge* classes (SQL layer and all the rest rely on it), so adding a begin()/commit() is quite easy. We can do some tests and see how it performs. 

Luigi

**Comment by lvca** [comment]
I like this idea. And having this operation in the storage allows us to improve/change things easily in the future too.

**Comment by lvca** [comment]
@laa and @taburet WDYT?

**Comment by laa** [comment]
@lvca it is normal tx I don not mind, never thought that usage of no tx graph is justified. But in such case we will have big overhead on distributed side, will not we?

**Comment by lvca** [comment]
No, on distributed side would be the same. By the way, we still have the problem with embedded ridbags there...
