### ISSUE TITLE
Couldn't insert record in replicated setup 

### ISSUE THREAD

**Issue by easy2coderep** [orientechnologies/orientdb#7241]
## Expected behavior  
The insert operation should be performed and the new row should get sync with replicated orientdb   

## Actual behavior  
 Have orientdb in distributed setup, both are running. However when performing the insert query using com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex() and then followed by commit(). However the insert is not happening, forget about the sync. I even tried to perform basic insert query from Web GUI and still could not perform the insert  

## Steps to reproduce  
Install the orientDB in replicated mode in two server and with 1 table. Then insert the rows.  

Initially it was working fine, but as the number of rows grows , we started getting the below exceptions 

> 
> at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
> 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
> Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=742155 from=elektra task=tx userName=). Elapsed=5ms Servers in timeout/conflict are:
>  - elektra: [#20:7016702 v.1280766]
> Received: {natchios=[#20:6500105 v.1098681], elektra=[#20:7016702 v.1280766]}
> 	at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:585)
> 	at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:349)
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:358)
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:192)
> 	... 10 more
> 
> 
> com.orientechnologies.orient.server.distributed.ODistributedException: Error on executing distributed request (id=742164 from=elektra task=tx userName=) against database 'webnmsdb.[default]' to nodes [natchios, elektra]
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:195)
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:354)
> 	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:914)
> 	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488)
> 	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
> 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2433)
> 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2403)
> 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1092)
> 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:394)
> 	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
> 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
> Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=742164 from=elektra task=tx userName=). Elapsed=6ms Servers in timeout/conflict are:
>  - natchios: [#20:6500106 v.1098682]
> Received: {natchios=[#20:6500106 v.1098682], elektra=[#20:7016703 v.1280767]}
> 	at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:585)
> 	at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:349)
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:358)
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:192)
> 	... 10 more

The above logs are in our server.

The below exception I see when performing the manual insert from the WebGUI

> com.orientechnologies.orient.server.distributed.ODistributedException: Error on executing distributed request (id=771825 from=elektra task=record_create(#20:-1 v.0) userName=) against database 'webnmsdb.[managedobject]' to nodes [elektra, natchios]
>  --> com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=771825 from=elektra task=record_create(#20:-1 v.0) userName=). Elapsed=5ms Servers in timeout/conflict are: - natchios: #20:6506046 v.1104756 Received: {natchios=#20:6506046 v.1104756, elektra=#20:7022695 v.1287063}

**Comment by lvca** [comment]
@easy2coderep please don't use OrientDB 2.0.12. It's not supported anymore. Use rather the last 2.2.x.
