### ISSUE TITLE
db create exists error (http api) return content not a json

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#7244]
## Expected behavior  
I expected it to return something that could be decoded into a json like all the other error returns i've encountered so far 

## Actual behavior  

but I got just a string. is this expected behaviour? why is the db create error different than all the others
    Database 'plocal:/home/creisle/applications/orientdb-community-2.2.17/databases/test' already exists.

## Steps to reproduce  
start up orientdb server and sent post request to create the test database
http://10.9.202.242:2480/database/test/plocal/graph

send it again to get the error

**Comment by maggiolo00** [comment]
hi @creisle 

thanks for this issue.  It's not an expected behaviour. 
Let me work on a fix
Thanks

**Comment by maggiolo00** [comment]
hi @creisle 

i've fixed this. 
It will be available on OrientDB 2.2.18

Thanks
