### ISSUE TITLE
Possible Regression from 2.2.16 to 2.2.17: Stored Function Mandatory Property Validation

### ISSUE THREAD

**Issue by sungeunchoi-kr** [orientechnologies/orientdb#7248]
## Expected behavior  
In Stored Function, creating a vertex with only some (that is, not all) of its `mandatory` fields set should not throw an OValidationException as long as its mandatory fields are "eventually" filled before the `db.commit()` time.

An example:
Let vertex "TestVertex" have two mandatory fields "mandatory_1" and "mandatory_2".
_In versions up until 2.2.16_, the below Stored Function code created a vertex properly:
```
  var db = orient.getGraph();
  // "mandatory_2" is not immediately set, but is "eventually" set before the commit time.
  var created = db.command('sql', 'create vertex TestVertex set mandatory_1="foo"');
  created.setProperty('mandatory_2', 'bar');
  db.commit();
```

## Actual behavior  
However, in version 2.2.17, the following exception is thrown on line 3.
`com.orientechnologies.orient.core.exception.OValidationException: The field 'TestVertex.mandatory_2' is mandatory, but not found on record: TestVertex{mandatory_1:foo}\r\n\tDB name=\"test\"` 

## Steps to reproduce 
```
create class TestVertex extends V
create property TestVertex.mandatory_1 string
alter property TestVertex.mandatory_1 mandatory true
create property TestVertex.mandatory_2 string
alter property TestVertex.mandatory_2 mandatory true
create property TestVertex.foo string

create function transaction_partial_mandatory_test "try {
  var db = orient.getGraph();
  var created = db.command('sql', 'create vertex TestVertex set mandatory_1=\"foo\"');
  created.setProperty('mandatory_2', 'bar');
  db.commit();
} catch(e) {
  e.printStackTrace();
  db.rollback();
  return(e.toString());
}" language javascript

select transaction_partial_mandatory_test() 
```

I have run the above setup on brand-new installations of 2.2.16 and 2.2.17; it works on 2.2.16 but does not work on 2.2.17.

**Comment by tglman** [comment]
hi @sungeunchoi-kr,

We fixed the validation flow and now when you save a document should be valid since the first save, the sql of "create vertex " already save the record in the transaction, so it have to be valid to be saved.

The today behaviour is the correct one.

Regards
