### ISSUE TITLE
Error impossible to run OrientDB in Docker with HypriotOS based on Debian Jessie

### ISSUE THREAD

**Issue by gdeverlant** [orientechnologies/orientdb#7250]
## Expected behavior  
OrientDB should run as expected with the Docker initialization

## Actual behavior  
Error executing the container's initialization 

## Steps to reproduce  
Dockerfile content

[http://pastebin.com/d0kBUmNV](http://pastebin.com/d0kBUmNV)

================================
Modified server.sh file
================================
[http://pastebin.com/g9FXAjYM](http://pastebin.com/g9FXAjYM)

================================
SSH'ed via Putty on the board
================================

docker build -t orientdb-arm .

`Sending build context to Docker daemon 17.41 kB
Step 1/18 : FROM maxleiko/armhf-alpine-java
 ---> 9b18cd7bd290
Step 2/18 : MAINTAINER OrientDB LTD (info@orientdb.com)
 ---> Using cache
 ---> d64612524c91
Step 3/18 : ARG ORIENTDB_DOWNLOAD_SERVER
 ---> Using cache
 ---> 532d08e634d1
Step 4/18 : ENV ORIENTDB_VERSION 2.2.17
 ---> Using cache
 ---> e32c3e5cf7b1
Step 5/18 : ENV ORIENTDB_DOWNLOAD_MD5 3be5c561fbee52ca6ba12f1637f206fc
 ---> Using cache
 ---> 9bac7c4f1724
Step 6/18 : ENV ORIENTDB_DOWNLOAD_SHA1 e43104e7dafb301a232212d2300922a086f7aedf
 ---> Using cache
 ---> 1427aeca8613
Step 7/18 : ENV ORIENTDB_DOWNLOAD_URL ${ORIENTDB_DOWNLOAD_SERVER:-http://central.maven.org/maven2/com/orientechnologies}/orientdb-community/$ORIENTDB_VERSION/orientdb-community-$ORIENTDB_VERSION.tar.gz
 ---> Using cache
 ---> d915d8287147
Step 8/18 : RUN apk add --update tar curl     && rm -rf /var/cache/apk/*
 ---> Using cache
 ---> 6f7562640382
Step 9/18 : RUN mkdir /orientdb &&   wget  $ORIENTDB_DOWNLOAD_URL   && echo "$ORIENTDB_DOWNLOAD_MD5 *orientdb-community-$ORIENTDB_VERSION.tar.gz" | md5sum -c -   && echo "$ORIENTDB_DOWNLOAD_SHA1 *orientdb-community-$ORIENTDB_VERSION.tar.gz" | sha1sum -c -   && tar -xvzf orientdb-community-$ORIENTDB_VERSION.tar.gz -C /orientdb --strip-components=1   && rm orientdb-community-$ORIENTDB_VERSION.tar.gz   && rm -rf /orientdb/databases/*
 ---> Using cache
 ---> 5cca92510578
Step 10/18 : ENV PATH /orientdb/bin:$PATH
 ---> Using cache
 ---> f6a08bee3bbb
Step 11/18 : VOLUME /orientdb/backup /orientdb/databases /orientdb/config
 ---> Using cache
 ---> fd107995e7ba
Step 12/18 : COPY server.sh /orientdb/bin/server.sh
 ---> Using cache
 ---> e6643451de70
Step 13/18 : RUN chmod 777 /orientdb/bin/server.sh
 ---> Using cache
 ---> d962d8e16c22
Step 14/18 : WORKDIR /orientdb
 ---> Using cache
 ---> 6515998f77bf
Step 15/18 : EXPOSE 2424
 ---> Using cache
 ---> 6506c7906daf
Step 16/18 : EXPOSE 2480
 ---> Using cache
 ---> d8339b06047e
Step 17/18 : CMD server.sh
 ---> Using cache
 ---> 6b0611300f38
Step 18/18 : HEALTHCHECK CMD curl --fail http://localhost:2480/ || exit 1
 ---> Using cache
 ---> d44058810a7f
Successfully built d44058810a7f

================================
Running the Docker container via SHELL
================================

`docker run --name orientdb -d -p 2480:2480 -p 2424:2424  orientdb-arm`

================================
Checking container LOGS
================================
`./server.sh: line 1: ﻿#!/bin/sh: No such file or directory
           .                                          
          .`        `                                 
          ,      `:.                                  
         `,`    ,:`                                   
         .,.   :,,                                    
         .,,  ,,,                                     
    .    .,.:::::  ````                                 :::::::::     :::::::::   
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
           ,,:` `,,.                                  
          ,,,    .,`                                  
         ,,.     `,                                          GRAPH DATABASE  
       ``        `.                                                          
                 ``                                          orientdb.com
                 `                                    
Invalid maximum direct memory size: -XX:MaxDirectMemorySize=512g
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

**Comment by tglman** [comment]
hi, 

seems that the architecture that you use does not support big memories, you got this in the log :
```
Invalid maximum direct memory size: -XX:MaxDirectMemorySize=512g
The specified size exceeds the maximum representable size.
```
this setting is in the server.sh reduce it till it fit the size of your environment.

Regards

**Comment by gdeverlant** [comment]
If you check inside of my modified server.sh file I've added the following:

`if [ -z "$ORIENTDB_OPTS_MEMORY" ] ; then
    ORIENTDB_OPTS_MEMORY="-Xms128m -Xmx256m"
fi`

It doesn't change anything.

What else do you suggest?

**Comment by tglman** [comment]
hi @gdeverlant 
can you add to the options also: `-XX:MaxDirectMemorySize=2g`

Regards

**Comment by gdeverlant** [comment]
This is working with -XX:MaxDirectMemorySize=256m
