### ISSUE TITLE
how to rename an index?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7254]
## Expected behavior  
I have some BIG indexes, and some of them I want to rename. I do not find any documentation about renaming an index. 
The alternative (a DROP of the index, the CREATE the new named index) is not attractive because of the high number of records in our classes, index creation takes 2 hours and blocks a lot of activity in the server...

**Comment by maggiolo00** [comment]
hi @rdelangh 

there is not way to change the index name. The `alter` on index is not supported. The only way is to drop and re create it

**Comment by rdelangh** [comment]
hi, any new feedback on this, please? Is it planned to make the ALTER command on indexes supported, e.g. to change the name of an index?

**Comment by laa** [comment]
Hi @rdelangh , but what is the point to rename index? If you plan to use manual indexes so we plan to deprecate them soon, but the name of the automatic index is not so important.

**Comment by rdelangh** [comment]
hi @laa 
we have automated the creation of new classes and their indexes, and therefor their names should adhere a convention which is reflected in the automation program.
What do you mean by "manual indexes will be deprecated soon" ?? 
What is the future strategy for OrientDB indexes?

**Comment by rdelangh** [comment]
@laa 
given my previous comment, can you please confirm that it can be foreseen in a next snapshot release, to support the ALTER command on indexes for changing their name?
