### ISSUE TITLE
3.0.0-445-snapshot - change in behavior or bug - empty edge class takes precedence over vertex class

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7256]
### OS:  wind 10 

demodb v 0.75

consider this query

MATCH {class: Customers, as: customer, where: (OrderedId=1)}--{Class: Services} 
RETURN $pathelements

in words:  find all services connected to customer with OrderedId=1,  regardless of the edge class

## Expected behavior  

all services connected to customer with OrderedId=1, (regardless of the edge class) are returned

this is what I get in 2.2.17 (correct):

![new_bug_1_2217](https://cloud.githubusercontent.com/assets/14923389/24177938/0a7fa416-0ea6-11e7-9c96-00f45aed40be.PNG)

## Actual behavior  

this is what i get in 3.0-snapshot, it seems that empty edge class -- takes precedence over services class

![new_bug_1_3000](https://cloud.githubusercontent.com/assets/14923389/24178011/9aaf3718-0ea6-11e7-961b-03694662cab7.PNG)

thanks,

**Comment by luigidellaquila** [comment]
Hi @santo-it 

It seems to be a bug, I'll check it

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed in develop branch 

Thanks!

Luigi
