### ISSUE TITLE
 Failed to update an entity: Cannot UPDATE the record #7:1 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v2 your=v1)

### ISSUE THREAD

**Issue by linxd** [orientechnologies/orientdb#7258]
## Expected behavior  

sucessful add record

## Actual behavior  
org.openhie.openempi.ApplicationException: Failed to update an entity: Cannot UPDATE the record #7:1 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v2 your=v1)

**Comment by nsharmacovs** [comment]
We too faced this issue and tried to set the java varibable  -DridBag.embeddedToSbtreeBonsaiThreshold = Integer.MAX\_VALUE  in dserver.sh but encountered   errors on server startup  .http://orientdb.com/docs/2.1/Concurrency.html .We are using orientdb 2.2.17 in distributed mode .

**Comment by maggiolo00** [comment]
hi @linxd 

are you from Java API?

**Comment by linxd** [comment]
maybe ,I can't know well , I just know openempi 3.x use orientdb as an embeded database for storing entity data.

在 2017-03-28 23:06:00，"Enrico Risa" <notifications@github.com> 写道：


hi @linxd

are you from Java API?

**Comment by linxd** [comment]
maybe ,I can't know well , I just know openempi 3.x use orientdb as an embeded database for storing entity data. 




--

此致
easy

莫愁前路无知己，天下谁人不识君。

在 2017-03-28 23:06:00，"Enrico Risa" <notifications@github.com> 写道：


hi @linxd

are you from Java API?
