### ISSUE TITLE
vertex version increment when ridBag.embeddedToSbtreeBonsaiThreshold set to -1

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#7259]
## Expected behavior  

expected the version numbers on a give vertex to not change when adding edges if the config option was set. As described in the documentation here http://orientdb.com/docs/2.2/SQL-Delete.html (see Controlling Vertex Version Increments section)

## Actual behavior  

version number incremented on the associated vertices when an edge was added/deleted

## Steps to reproduce  

I added the following line to my config file orientdb-community-2.2.17/config/orientdb-server-config.xml

    <entry value="-1" name="ridBag.embeddedToSbtreeBonsaiThreshold"/>

I then verified this was being set by going into the console and checking the value after typing config. It showed what I expected, -1

Next I tested created two vertices

    @rid  @version 
    #10:1  1 
    #9:1    1

then I created an edge between them

    create edge from #10:1 to #9:1 

but listing the vertices again I see the following

    @rid  @version 
    #10:1  2 
    #9:1    2

Am I interpreting the documentation wrong? I expected changes to edges not to affect the node version numbers

**Comment by maggiolo00** [comment]
hi @creisle 

that should be for the first time that requires to initialize the collection 

do the version change if you re-execute this ?

```
create edge from #10:1 to #9:1 
```

**Comment by creisle** [comment]
no it doesn't. I think perhaps I misunderstood how this worked. So does this mean that the node version will continue to increment as edges are added/update/removed unless it is a "multiple" edge or another edge between the same two nodes? Am I getting that right? because the versions still increment if I create a third node and add edges to it

If so that wasn't what I understood from the docs 

PS I got the link wrong above its seems. should have been http://orientdb.com/docs/2.2/SQL-Delete-Edge.html

**Comment by maggiolo00** [comment]
Hi @creisle 

as long as the bonsai tree structure is created in the records involved, the version is not updated.
But if you create an edge between 2 records where for that type of relationship the tree is not yet created then the version is incremented

You can find more about RidBags here

http://orientdb.com/docs/2.2/RidBag.html

I guess the docs it's a bit unclear about that. 
I will mark this as documentation 

Thanks
