### ISSUE TITLE
Intersect Function Error and a performance question

### ISSUE THREAD

**Issue by ozgursucu** [orientechnologies/orientdb#7262]
### OS: OS X Yosemite

I am trying the GratefulDeadConcerts database that is coming with OrientDB installation and I came up with a problem. When I write a simple query that intersects followed_by relations between two songs there is no problem (select intersect(in('followed_by')) from [9:2,9:4]) but when I want to intersect three of them with this query --> select intersect(in('followed_by')) from [9:2,9:4,9:6] OrientDB throws exception: java.lang.ClassCastException:java.util.HashSet cannot be cast to java.util.Iterator. I think It is a bug.

Another question is for the performance of intersections. Consider Catalog system. I want to fetch Catalogs with Brand Samsung which belongs to Accessories category but There may be thousands of Catalogs with Brand Samsung and millions of catalogs belongs to Accessories category. What would be the correct model to be able search and find results and can intersection function be considered for these cases? I tried intersect function with two vertexes having million edges but the elapsed time was too long (about 30 seconds)

Thanks in advance.

**Comment by ozgursucu** [comment]
Any answers?

**Comment by luigidellaquila** [comment]
Hi @ozgursucu 

Sorry, I still had no chance to check it (but I'd say the ClassCastEx is a bug)

I'll let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @ozgursucu 

I just pushed a fix on 2.2.x branch. The fix will be released with 2.2.18, scheduled for next Wednesday

Thanks

Luigi

**Comment by ozgursucu** [comment]
Thanks @luigidellaquila.
And what about the performance?

**Comment by ozgursucu** [comment]
Any answers about the performance?

**Comment by luigidellaquila** [comment]
Hi @ozgursucu 

As a rule of thumb, the performance depends on how many records you have to fetch, so I suggest you to start from the vertex that has less connected edges and then evaluate the other side of the relationship.
In this case you should start from the brand and then filter based on the other side of the relationship.

When you have a vertex that is in the middle or two supernodes this is particularly expensive, unfortunately there is no silver bullet to fix it.

Thanks

Luigi

**Comment by ozgursucu** [comment]
Hi @luigidellaquila 
Does intersect function simply compare the rids? Then would select intersect(in('catalogLink')) from [12:0,18:9,15:0] where 12:0 have 100000 catalogLink, 18:9 10000 catalogLink, 15:0 20000 catalogLink be a slow query?

**Comment by luigidellaquila** [comment]
Yes it does, I'll double-check it, but it should be efficient enough to avoid deep comparing the docs

Thanks

Luigi

**Comment by ozgursucu** [comment]
Hi @luigidellaquila 
Did you have any chance to check the efficiency?

**Comment by luigidellaquila** [comment]
Hi @ozgursucu 

I checked the function, it does not perform deep compare, but it works on iterators that can come from previous steps, so in some cases they can trigger record deserialization. 
So I cannot guarantee 100% that it always works on RIDs

Thanks

Luigi

**Comment by ozgursucu** [comment]
Hi @luigidellaquila 
How can it be possible to prevent record deserialization so that it just works on RIDs and avoid deep comparison?

**Comment by ozgursucu** [comment]
Hi @luigidellaquila 
Would you please answer the last question above?

**Comment by luigidellaquila** [comment]
Hi @ozgursucu 

I'm afraid there is not a final answer for this, it depends a lot on internal behaviors, so you don't have much control on that...

Luigi
