### ISSUE TITLE
Memory leak and very low performance for import

### ISSUE THREAD

**Issue by oger-p** [orientechnologies/orientdb#7263]
### OS: Red Hat Enterprise Linux Server release 5.8 (Tikanga)
I'm using oriendb since 6 month and i have some problems/issues.

Setup 
-
- I have 20M Verticles / 40M Edges in Mysql and Elasticsearch.

- I have done a multithread script to import all the data in OrientDB.

- My server for OrientDB : 16CPU, 32GB RAM

- My server for the script import : 8CPU, 16GB RAM

- I'm using python and the driver pyorient

Process
-
- I had to separate the vertex and the edge import because it was impossible to do it with the batch import (lots of concurrency problems)

- the RAM used on the server never stop increasing (I had to change OrientDB server three times to be able to import the whole database)

[![enter image description here][1]][1]

- I'm seeing that the import is very slow : more than 2 days to import the entire database.

Questions
-

- How can i increase the performance? (i'm already doing bulk and multithread)

- How can I fix the increasing RAM (memory leek) because i can't let it like this.Everytime my server start to swap after hours of importing... ?

StackOverflow issue
- 
[here](http://stackoverflow.com/questions/42971193/orientdb-importation-performance-with-lots-of-data)

Thanks

  [1]: https://i.stack.imgur.com/meFkB.png

**Comment by laa** [comment]
Hi @oger-p, that is a quite small number of data. 

Could send me configuration which you use on a server side?

I mean following:

1.  Java settings.
2.  The final size of the database on disk.
3. The server settings. The last one you can retrieve using http://orientdb.com/docs/2.2/Console-Command-Config.html . You should execute this command once you login on a remote server in a console application.

**Comment by oger-p** [comment]
1/ Java settings

        /opt/OrientDB/jre1.8.0_111/bin/java -server -Dcom.sun.management.jmxremote.port=3333 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false     -server     -Xms24g -Xmx24g -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9     -Djava.util.logging.config.file=/opt/OrientDB/orientdb-community-2.2.17/config/orientdb-server-log.properties -Dorientdb.config.file=/opt/OrientDB/orientdb-community-2.2.17/config/    orientdb-server-config.xml -Dorientdb.www.path=/opt/OrientDB/orientdb-community-2.2.17/www -Dorientdb.build.number=2.2.x@rd9bace82ea8437117fd48114fc255e791056014b; 2017-02-16     17:20:27+0000 -cp /opt/OrientDB/orientdb-community-2.2.17/lib/orientdb-server-2.2.17.jar:/opt/OrientDB/orientdb-community-2.2.17/lib/*:/opt/OrientDB/orientdb-community-2.2.17/plugins/* com.orientechnologies.orient.server.OServerMain

4/ The final size of the database on disk.

        $ du -hs ~/OrientDB/orientdb-community-2.2.17/databases/*
        29G /opt/OrientDB/orientdb-community-2.2.17/databases/Delphes
        4,0K    /opt/OrientDB/orientdb-community-2.2.17/databases/GamesOfThrones
        27M /opt/OrientDB/orientdb-community-2.2.17/databases/GratefulDeadConcerts
        4,0K    /opt/OrientDB/orientdb-community-2.2.17/databases/OpenBeer
        20M /opt/OrientDB/orientdb-community-2.2.17/databases/OSystem
        22M /opt/OrientDB/orientdb-community-2.2.17/databases/test

3/ The server settings.

        $ cat /etc/*release*
        Red Hat Enterprise Linux Server release 5.8 (Tikanga)

        $ uname -a
        Linux foo.local 2.6.18-308.16.1.el5 #1 SMP Tue Sep 18 07:21:07 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux

        $ JAVA_HOME=/opt/OrientDB/jre1.8.0_111/ bin/console.sh

        OrientDB console v.2.2.17 (build 2.2.x@rd9bace82ea8437117fd48114fc255e791056014b; 2017-02-16 17:20:27+0000) www.orientdb.com
        Type 'help' to display all the supported commands.
        Installing extensions for GREMLIN language v.2.6.0

        orientdb> CONFIG

        LOCAL SERVER CONFIGURATION
        +----+----------------------------------------------+------------------------------------------------------------------------------------------------+
        |#   |NAME                                          |VALUE                                                                                           |
        +----+----------------------------------------------+------------------------------------------------------------------------------------------------+
        |0   |environment.dumpCfgAtStartup                  |false                                                                                           |
        |1   |environment.concurrent                        |true                                                                                            |
        |2   |environment.lockManager.concurrency.level     |128                                                                                             |
        |3   |environment.allowJVMShutdown                  |true                                                                                            |
        |4   |script.pool.maxSize                           |20                                                                                              |
        |5   |memory.useUnsafe                              |true                                                                                            |
        |6   |memory.chunk.size                             |2147483647                                                                                      |
        |7   |memory.directMemory.safeMode                  |true                                                                                            |
        |8   |memory.directMemory.trackMode                 |false                                                                                           |
        |9   |memory.directMemory.onlyAlignedMemoryAccess   |true                                                                                            |
        |10  |jvm.gc.delayForOptimize                       |600                                                                                             |
        |11  |storage.openFiles.limit                       |512                                                                                             |
        |12  |storage.componentsLock.cache                  |10000                                                                                           |
        |13  |storage.diskCache.pinnedPages                 |20                                                                                              |
        |14  |storage.diskCache.bufferSize                  |4096                                                                                            |
        |15  |storage.diskCache.writeCachePart              |15                                                                                              |
        |16  |storage.diskCache.writeCachePageTTL           |86400                                                                                           |
        |17  |storage.diskCache.writeCachePageFlushInterval |25                                                                                              |
        |18  |storage.diskCache.writeCacheFlushInactivity...|60000                                                                                           |
        |19  |storage.diskCache.writeCacheFlushLockTimeout  |-1                                                                                              |
        |20  |storage.diskCache.diskFreeSpaceCheckInterval  |5                                                                                               |
        |21  |storage.diskCache.diskFreeSpaceCheckInterva...|2048                                                                                            |
        |22  |storage.diskCache.keepState                   |true                                                                                            |
        |23  |storage.configuration.syncOnUpdate            |true                                                                                            |
        |24  |storage.compressionMethod                     |nothing                                                                                         |
        |25  |storage.encryptionMethod                      |nothing                                                                                         |
        |26  |storage.encryptionKey                         |                                                                                                |
        |27  |storage.makeFullCheckpointAfterCreate         |false                                                                                           |
        |28  |storage.makeFullCheckpointAfterOpen           |true                                                                                            |
        |29  |storage.makeFullCheckpointAfterClusterCreate  |true                                                                                            |
        |30  |storage.trackChangedRecordsInWAL              |false                                                                                           |
        |31  |storage.useWAL                                |true                                                                                            |
        |32  |storage.wal.syncOnPageFlush                   |true                                                                                            |
        |33  |storage.wal.cacheSize                         |3000                                                                                            |
        |34  |storage.wal.fileAutoCloseInterval             |10                                                                                              |
        |35  |storage.wal.maxSegmentSize                    |128                                                                                             |
        |36  |storage.wal.maxSize                           |4096                                                                                            |
        |37  |storage.wal.commitTimeout                     |1000                                                                                            |
        |38  |storage.wal.shutdownTimeout                   |10000                                                                                           |
        |39  |storage.wal.fuzzyCheckpointInterval           |300                                                                                             |
        |40  |storage.wal.reportAfterOperationsDuringRestore|10000                                                                                           |
        |41  |storage.wal.restore.batchSize                 |1000                                                                                            |
        |42  |storage.wal.readCacheSize                     |1000                                                                                            |
        |43  |storage.wal.fuzzyCheckpointShutdownWait       |600                                                                                             |
        |44  |storage.wal.fullCheckpointShutdownTimeout     |600                                                                                             |
        |45  |storage.wal.path                              |                                                                                                |
        |46  |storage.diskCache.pageSize                    |64                                                                                              |
        |47  |storage.diskCache.diskFreeSpaceLimit          |256                                                                                             |
        |48  |storage.lowestFreeListBound                   |16                                                                                              |
        |49  |storage.lockTimeout                           |0                                                                                               |
        |50  |storage.record.lockTimeout                    |2000                                                                                            |
        |51  |storage.useTombstones                         |false                                                                                           |
        |52  |record.downsizing.enabled                     |true                                                                                            |
        |53  |object.saveOnlyDirty                          |false                                                                                           |
        |54  |db.pool.min                                   |1                                                                                               |
        |55  |db.pool.max                                   |100                                                                                             |
        |56  |db.pool.idleTimeout                           |0                                                                                               |
        |57  |db.pool.idleCheckDelay                        |0                                                                                               |
        |58  |db.mvcc.throwfast                             |false                                                                                           |
        |59  |db.validation                                 |true                                                                                            |
        |60  |nonTX.recordUpdate.synch                      |false                                                                                           |
        |61  |nonTX.clusters.sync.immediately               |manindex                                                                                        |
        |62  |tx.trackAtomicOperations                      |false                                                                                           |
        |63  |tx.pageCacheSize                              |12                                                                                              |
        |64  |index.embeddedToSbtreeBonsaiThreshold         |40                                                                                              |
        |65  |index.sbtreeBonsaiToEmbeddedThreshold         |-1                                                                                              |
        |66  |hashTable.slitBucketsBuffer.length            |1500                                                                                            |
        |67  |index.auto.synchronousAutoRebuild             |true                                                                                            |
        |68  |index.auto.lazyUpdates                        |10000                                                                                           |
        |69  |index.flushAfterCreate                        |true                                                                                            |
        |70  |index.manual.lazyUpdates                      |1                                                                                               |
        |71  |index.durableInNonTxMode                      |true                                                                                            |
        |72  |index.ignoreNullValuesDefault                 |false                                                                                           |
        |73  |index.txMode                                  |FULL                                                                                            |
        |74  |index.cursor.prefetchSize                     |500000                                                                                          |
        |75  |sbtree.maxDepth                               |64                                                                                              |
        |76  |sbtree.maxKeySize                             |10240                                                                                           |
        |77  |sbtree.maxEmbeddedValueSize                   |40960                                                                                           |
        |78  |sbtreebonsai.bucketSize                       |2                                                                                               |
        |79  |sbtreebonsai.linkBagCache.size                |100000                                                                                          |
        |80  |sbtreebonsai.linkBagCache.evictionSize        |1000                                                                                            |
        |81  |sbtreebonsai.freeSpaceReuseTrigger            |0.5                                                                                             |
        |82  |ridBag.embeddedDefaultSize                    |4                                                                                               |
        |83  |ridBag.embeddedToSbtreeBonsaiThreshold        |40                                                                                              |
        |84  |ridBag.sbtreeBonsaiToEmbeddedToThreshold      |-1                                                                                              |
        |85  |collections.preferSBTreeSet                   |false                                                                                           |
        |86  |file.trackFileClose                           |false                                                                                           |
        |87  |file.lock                                     |true                                                                                            |
        |88  |file.deleteDelay                              |10                                                                                              |
        |89  |file.deleteRetry                              |50                                                                                              |
        |90  |security.userPasswordSaltIterations           |65536                                                                                           |
        |91  |security.userPasswordSaltCacheSize            |500                                                                                             |
        |92  |security.userPasswordDefaultAlgorithm         |PBKDF2WithHmacSHA256                                                                            |
        |93  |network.maxConcurrentSessions                 |1000                                                                                            |
        |94  |network.socketBufferSize                      |0                                                                                               |
        |95  |network.lockTimeout                           |15000                                                                                           |
        |96  |network.socketTimeout                         |15000                                                                                           |
        |97  |network.requestTimeout                        |3600000                                                                                         |
        |98  |network.retry                                 |5                                                                                               |
        |99  |network.retryDelay                            |500                                                                                             |
        |100 |network.binary.loadBalancing.enabled          |false                                                                                           |
        |101 |network.binary.loadBalancing.timeout          |2000                                                                                            |
        |102 |network.binary.maxLength                      |16384                                                                                           |
        |103 |network.binary.readResponse.maxTimes          |20                                                                                              |
        |104 |network.binary.debug                          |false                                                                                           |
        |105 |network.http.installDefaultCommands           |true                                                                                            |
        |106 |network.http.serverInfo                       |OrientDB Server v.2.2.17 (build 2.2.x@rd9bace82ea8437117fd48114fc255e791056014b; 2017-02-16 1...|
        |107 |network.http.maxLength                        |1000000                                                                                         |
        |108 |network.http.streaming                        |false                                                                                           |
        |109 |network.http.charset                          |utf-8                                                                                           |
        |110 |network.http.jsonResponseError                |true                                                                                            |
        |111 |network.http.jsonp                            |false                                                                                           |
        |112 |network.http.sessionExpireTimeout             |300                                                                                             |
        |113 |network.http.useToken                         |false                                                                                           |
        |114 |network.token.secretKey                       |                                                                                                |
        |115 |network.token.encryptionAlgorithm             |HmacSHA256                                                                                      |
        |116 |network.token.expireTimeout                   |60                                                                                              |
        |117 |profiler.enabled                              |false                                                                                           |
        |118 |profiler.config                               |                                                                                                |
        |119 |profiler.autoDump.interval                    |0                                                                                               |
        |120 |profiler.maxValues                            |200                                                                                             |
        |121 |profiler.memoryCheckInterval                  |120000                                                                                          |
        |122 |sequence.maxRetry                             |100                                                                                             |
        |123 |sequence.retryDelay                           |200                                                                                             |
        |124 |storageProfiler.intervalBetweenSnapshots      |100                                                                                             |
        |125 |storageProfiler.cleanUpInterval               |5000                                                                                            |
        |126 |log.console.level                             |info                                                                                            |
        |127 |log.file.level                                |info                                                                                            |
        |128 |class.minimumClusters                         |0                                                                                               |
        |129 |log.console.ansi                              |auto                                                                                            |
        |130 |cache.local.impl                              |com.orientechnologies.orient.core.cache.ORecordCacheWeakRefs                                    |
        |131 |command.timeout                               |0                                                                                               |
        |132 |command.cache.enabled                         |false                                                                                           |
        |133 |command.cache.evictStrategy                   |PER_CLUSTER                                                                                     |
        |134 |command.cache.minExecutionTime                |10                                                                                              |
        |135 |command.cache.maxResultsetSize                |500                                                                                             |
        |136 |query.parallelAuto                            |false                                                                                           |
        |137 |query.parallelMinimumRecords                  |300000                                                                                          |
        |138 |query.parallelResultQueueSize                 |20000                                                                                           |
        |139 |query.scanPrefetchPages                       |20                                                                                              |
        |140 |query.scanBatchSize                           |1000                                                                                            |
        |141 |query.scanThresholdTip                        |50000                                                                                           |
        |142 |query.limitThresholdTip                       |10000                                                                                           |
        |143 |query.live.support                            |true                                                                                            |
        |144 |statement.cacheSize                           |100                                                                                             |
        |145 |sql.graphConsistencyMode                      |tx                                                                                              |
        |146 |client.channel.maxPool                        |100                                                                                             |
        |147 |client.connectionPool.waitTimeout             |5000                                                                                            |
        |148 |client.channel.dbReleaseWaitTimeout           |10000                                                                                           |
        |149 |client.ssl.enabled                            |false                                                                                           |
        |150 |client.ssl.keyStore                           |                                                                                                |
        |151 |client.ssl.keyStorePass                       |                                                                                                |
        |152 |client.ssl.trustStore                         |                                                                                                |
        |153 |client.ssl.trustStorePass                     |                                                                                                |
        |154 |server.openAllDatabasesAtStartup              |false                                                                                           |
        |155 |server.channel.cleanDelay                     |5000                                                                                            |
        |156 |server.cache.staticFile                       |false                                                                                           |
        |157 |server.log.dumpClientExceptionLevel           |FINE                                                                                            |
        |158 |server.log.dumpClientExceptionFullStackTrace  |false                                                                                           |
        |159 |distributed.crudTaskTimeout                   |10000                                                                                           |
        |160 |distributed.maxStartupDelay                   |10000                                                                                           |
        |161 |distributed.commandTaskTimeout                |120000                                                                                          |
        |162 |distributed.commandQuickTaskTimeout           |5000                                                                                            |
        |163 |distributed.commandLongTaskTimeout            |86400000                                                                                        |
        |164 |distributed.deployDbTaskTimeout               |1200000                                                                                         |
        |165 |distributed.deployChunkTaskTimeout            |15000                                                                                           |
        |166 |distributed.deployDbTaskCompression           |7                                                                                               |
        |167 |distributed.asynchQueueSize                   |0                                                                                               |
        |168 |distributed.asynchResponsesTimeout            |15000                                                                                           |
        |169 |distributed.purgeResponsesTimerDelay          |15000                                                                                           |
        |170 |distributed.conflictResolverRepairerChain     |majority,content,version                                                                        |
        |171 |distributed.conflictResolverRepairerCheckEvery|5000                                                                                            |
        |172 |distributed.conflictResolverRepairerBatch     |100                                                                                             |
        |173 |distributed.txAliveTimeout                    |30000                                                                                           |
        |174 |distributed.requestChannels                   |1                                                                                               |
        |175 |distributed.responseChannels                  |1                                                                                               |
        |176 |distributed.heartbeatTimeout                  |10000                                                                                           |
        |177 |distributed.checkHealthCanOfflineServer       |false                                                                                           |
        |178 |distributed.checkHealthEvery                  |10000                                                                                           |
        |179 |distributed.autoRemoveOfflineServers          |0                                                                                               |
        |180 |distributed.publishNodeStatusEvery            |5000                                                                                            |
        |181 |distributed.localQueueSize                    |10000                                                                                           |
        |182 |distributed.dbWorkerThreads                   |8                                                                                               |
        |183 |distributed.queueMaxSize                      |10000                                                                                           |
        |184 |distributed.backupDirectory                   |../backup/databases                                                                             |
        |185 |distributed.backupTryIncrementalFirst         |true                                                                                            |
        |186 |distributed.concurrentTxMaxAutoRetry          |10                                                                                              |
        |187 |distributed.atomicLockTimeout                 |300                                                                                             |
        |188 |distributed.concurrentTxAutoRetryDelay        |100                                                                                             |
        |189 |db.document.serializer                        |ORecordSerializerBinary                                                                         |
        |190 |client.krb5.config                            |                                                                                                |
        |191 |client.krb5.ccname                            |                                                                                                |
        |192 |client.krb5.ktname                            |                                                                                                |
        |193 |client.credentialinterceptor                  |                                                                                                |
        |194 |client.ci.keyalgorithm                        |AES                                                                                             |
        |195 |client.ci.ciphertransform                     |AES/CBC/PKCS5Padding                                                                            |
        |196 |client.ci.keystore.file                       |                                                                                                |
        |197 |client.ci.keystore.password                   |                                                                                                |
        |198 |security.createDefaultUsers                   |true                                                                                            |
        |199 |server.security.file                          |                                                                                                |
        |200 |jna.disable.system.library                    |true                                                                                            |
        |201 |distributed.queueTimeout                      |500000                                                                                          |
        |202 |db.makeFullCheckpointOnIndexChange            |true                                                                                            |
        |203 |db.makeFullCheckpointOnSchemaChange           |true                                                                                            |
        |204 |client.session.tokenBased                     |true                                                                                            |
        |205 |oauth2.secretkey                              |                                                                                                |
        |206 |storage.cluster.usecrc32                      |false                                                                                           |
        |207 |lazyset.workOnStream                          |true                                                                                            |
        |208 |db.mvcc                                       |true                                                                                            |
        |209 |db.use.distributedVersion                     |false                                                                                           |
        |210 |mvrbtree.timeout                              |0                                                                                               |
        |211 |mvrbtree.nodePageSize                         |256                                                                                             |
        |212 |mvrbtree.loadFactor                           |0.7                                                                                             |
        |213 |mvrbtree.optimizeThreshold                    |100000                                                                                          |
        |214 |mvrbtree.entryPoints                          |64                                                                                              |
        |215 |mvrbtree.optimizeEntryPointsFactor            |1.0                                                                                             |
        |216 |mvrbtree.entryKeysInMemory                    |false                                                                                           |
        |217 |mvrbtree.entryValuesInMemory                  |false                                                                                           |
        |218 |mvrbtree.ridBinaryThreshold                   |-1                                                                                              |
        |219 |mvrbtree.ridNodePageSize                      |64                                                                                              |
        |220 |mvrbtree.ridNodeSaveMemory                    |false                                                                                           |
        |221 |tx.commit.synch                               |false                                                                                           |
        |222 |tx.autoRetry                                  |1                                                                                               |
        |223 |tx.log.fileType                               |classic                                                                                         |
        |224 |tx.log.synch                                  |false                                                                                           |
        |225 |tx.useLog                                     |true                                                                                            |
        |226 |index.auto.rebuildAfterNotSoftClose           |true                                                                                            |
        |227 |client.channel.minPool                        |1                                                                                               |
        |228 |storage.keepOpen                              |true                                                                                            |
        |229 |cache.local.enabled                           |true                                                                                            |
        +----+----------------------------------------------+------------------------------------------------------------------------------------------------+

        orientdb>

**Comment by laa** [comment]
@oger-p you sent me "local" configuration, but you should see "REMOTE SERVER CONFIGURATION"  in the command output. Could you login into the server http://orientdb.com/docs/2.2/Console-Command-Connect.html and execute the same command after that.

**Comment by oger-p** [comment]
@laa I have the same thing even if i'm connected : 
$ orientdb-community-2.2.17$ JAVA_HOME=/opt/OrientDB/jre1.8.0_111/ bin/console.sh

    OrientDB console v.2.2.17 (build 2.2.x@rd9bace82ea8437117fd48114fc255e791056014b; 2017-02-16 17:20:27+0000) www.orientdb.com
    Type 'help' to display all the supported commands.
    Installing extensions for GREMLIN language v.2.6.0

    orientdb> CONNECT REMOTE:127.0.0.1/Delphes root root

    Connecting to database [REMOTE:127.0.0.1/Delphes] with user 'root'...OK
    orientdb {db=Delphes}> CONFIG

    LOCAL SERVER CONFIGURATION
    +----+----------------------------------------------+------------------------------------------------------------------------------------------------+
    |#   |NAME                                          |VALUE                                                                                           |
    +----+----------------------------------------------+------------------------------------------------------------------------------------------------+
    |0   |environment.dumpCfgAtStartup                  |false                                                                                           |
    |1   |environment.concurrent                        |true                                                                                            |
    |2   |environment.lockManager.concurrency.level     |128                                                                                             |
    |3   |environment.allowJVMShutdown                  |true                                                                                            |
    |4   |script.pool.maxSize                           |20                                                                                              |
    |5   |memory.useUnsafe                              |true                                                                                            |
    |6   |memory.chunk.size                             |2147483647                                                                                      |
    |7   |memory.directMemory.safeMode                  |true                                     
    ....

**Comment by laa** [comment]
Hi @oger-p I see. I think first your mistake is that  you set -Xms24g  we do not use Jave heap memory, much instead we use direct memory, but when you assign 24g nothing left for direct memory. So I ask you to lower heap memory to 4g and repeat the import.

**Comment by oger-p** [comment]
Hi,
Ok, I'll do it and i'll update this topic when it's done !
Thanks

**Comment by oger-p** [comment]
Hello, @laa ,

So i did the import again with 1M Vertex / 20M Edge (first part of my dataset)

Here is the result : 

- 22minutes for 1M Vertex
- 14 hours for 20M Edges

The graph of the memory (you can see it doesn't go down after the end of the import (3/25 00:00) : 

![capture d ecran_2017-03-27_09-31-44](https://cloud.githubusercontent.com/assets/16560108/24345418/59a73a58-12d0-11e7-8a8f-6bfb47c2d124.png)

**Comment by laa** [comment]
@oger-p memory consumption will not go down after insertion because it is kept in disk cache to further next request in a quick manner. Do not think that we have a memory leak here because memory consumption becomes stable after some time. About insertion speed of edges, you may consider usage of lightweight edges   http://orientdb.com/docs/2.2/Lightweight-Edges.html if that is OK for  you.

**Comment by oger-p** [comment]
@laa,

I can't use lightweight edges.

I agree with you for the stable memory but it's just because the import was finished. What happen if I continue to import and arrive at 48/48GB of memory?

I'll try a new full import and keep you updated.

Thanks

**Comment by laa** [comment]
@oger-p it depends on your value of disk cache size. Because you use the default value, I suppose memory consumption will grow till about 2 GB will be left free for OS. 

Could you meanwhile give me the code which you use for data import or outline your algorithm using pseudocode?

**Comment by oger-p** [comment]
Ok i keep you updated with the next import.

I'm using swallow (https://github.com/pagesjaunes/swallow).
I have separated the importation of Edge and Vertex.
Edge import was not working with batch because of the concurrency.

Vertex:
=
Configuration
-
- 1 processor
- 15 writters
- orientdb batch

Process
-
One example : 
- I do a loop on values : 
`results.append('UPDATE Expression SET libelle = "{0}" UPSERT WHERE libelle = "{0}"'.format(value))
`
- I insert every 2500 command with a batch 

Edge
=
Configuration
-
- 5 processor
- 10 writters
- orientdb command

Process
-
One example :
- I do a loop on values : 
`results.append( 'CREATE EDGE Facultatif FROM (SELECT FROM Regle WHERE id = "{0}") to (SELECT FROM Ontologie WHERE id = "{1}") set type = {2}'.format( regle_id, regle_ontologie_id, regle_ontologie_type))
`
- I insert every iteration

**Comment by laa** [comment]
@oger-p do you have any index for Regle.id and Ontologie.id fields ?

**Comment by oger-p** [comment]
@laa, yes : 
```
session_orientdb.command("CREATE INDEX indexOntologie ON Ontologie (id) UNIQUE")
session_orientdb.command("CREATE INDEX indexRegle ON Regle (id) UNIQUE")
```

**Comment by laa** [comment]
Could you add following settings to the server -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:<file-path> and send me content of GC log file ?

**Comment by oger-p** [comment]
Did you forget something after -Xloggc?

I send it to you after the full import? partial import?

**Comment by laa** [comment]
I suppose that partial import is enough. I have fixed command line settings above.

**Comment by oger-p** [comment]
Ok, i send it to you when it's done.
Thanks

**Comment by oger-p** [comment]
hello @laa,

Here is the result of the import : 
=

Starting time 
-
- 15h20

Time for importation
-
- 20 minutes for all Vertex
- 13 hours for all Edges

The memory graph
-
![capture d ecran_2017-03-28_09-24-58](https://cloud.githubusercontent.com/assets/16560108/24393579/efb8573e-1398-11e7-817f-9ec56f38ccee.png)

The GCFile
-
- [gc.log.gz](https://github.com/orientechnologies/orientdb/files/874817/gc.log.gz)

**Comment by laa** [comment]
Hi @oger-p . I checked GC seems all is OK. 

But your throughput is very low, though, we never experienced such small throughput )).

Is it possible for you to create a script which imports from OrientDB to OrientDB and send me this script with a partially imported database which you created and step by step instructions how to run it?

I want to repeat your steps on my side. 
To check why throughput numbers are small.

WDYT ?

**Comment by oger-p** [comment]
Hello,

I think the memory problem is fixed.
I let the low performance issue at the moment. My script import all the database successfuly  and it will be a one shot import so it's not the priority to focus on this import.

Thank you for your time ! 

(I'll keep you updated if needed)

**Comment by laa** [comment]
cool @oger-p , I close issue then. Please do not hesitate to contact us if you have new ones.
