### ISSUE TITLE
3.0.0-snapshot-459, CI index on multiple properties

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7264]
### OS: win 10

ci index on multiple properties seems to not work
it works well on a single property

it woks on 2.2.17 (on single and multiple properties)

**Comment by luigidellaquila** [comment]
Hi @santo-it 

how are you creating the index?

Thanks

Luigi

**Comment by santo-it** [comment]
Issue7264() in OGitHubIssuesIT.java

**Comment by luigidellaquila** [comment]
Fixed in develop branch

Thanks!

Luigi
