### ISSUE TITLE
3.0.0-snapshot - new demodb, reduce used space

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7265]
Currently around 100mb

Biggest file:

- WAL file --> disable wal during odb-demodb ingration, if possible
- OFunction.name.hib --> how to reduce this?

**Comment by laa** [comment]
Hi @santo-it , I also thought about it. I think we may minimize file size by truncation of it on close. that seems to be safe thing.

**Comment by santo-it** [comment]
ok, all if you feel there are too many indices, we may also consider to drop some. which ones you feel are redundant?

thanks,

**Comment by robfrank** [comment]
@santo-it , maybe some of the lucene indexes can be dropped?

**Comment by robfrank** [comment]
@laa is it possbile to truncate it via SQL command on console? We create/load the demodb using an OSQL script file.

**Comment by lvca** [comment]
What's the status of this? Can I close it?

**Comment by santo-it** [comment]
Hi,

I'm not personally aware of updates. Currently waiting on the Storage Team. Not ready to be closed yet.

Thanks,

**Comment by laa** [comment]
fixed
