### ISSUE TITLE
Unable to `list server users` from OrientDB console

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#7267]
## Expected behavior  
If I access the OrientDB console using `sudo /opt/orientdb/bin/console.sh` and execute `list server users` at the console, I expect to see the list of users returned, like this:

```
SERVER USERS

- 'root', permissions: *
- 'guest', permissions: connect,server.listDatabases,server.dblist
```
 
## Actual behavior  
Instead, I get the following error:

 ```
Error: com.orientechnologies.orient.core.exception.OConfigurationException: Cannot access to file ../config/orientdb-server-config.xml
``` 
I thought it was a file permission issue, but it's not, because if I take the following steps to launch the console, everything works as expected:

1. cd /opt/orientdb/bin

2. sudo ./console.sh

3. execute the command

## Steps to reproduce  
1. type `sudo  /opt/orientdb/bin/console.sh` 

2. then type `list server users` at the console

**Comment by oger-p** [comment]
Hello @finid ,

I think it's normal due to the error "../config/orientdb-server-config.xml".
-> You must be on the /opt/orientdb/bin directory to do this command.

Hope it helps

**Comment by santo-it** [comment]
Hi,

Thanks for opening this issue. This happens because

`../config/orientdb-server-config.xml`

is hardcoded in `setServerUser`, `dropServerUser` and `listServerUsers` in `OConsoleDatabaseApp.java`.

I believe a way to solve this could be to use 

`Orient.ORIENTDB_HOME + "/config/orientdb-server-config.xml"`

instead.

I'll check internally

**Comment by clouds56** [comment]
Any update? I think it's not a big change.

**Comment by bioinfornatics** [comment]
A simple 
```
sudo sed -i '/^PRGDIR/a cd "${PRGDIR}"' "${ORIENTDB_HOME}"/bin/console.sh
```

fix it
