### ISSUE TITLE
Unable to perform Import when running in distributed mode

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/orientdb#7268]
## Expected behavior  
Schema and data imported successfully  

## Actual behavior  
Received following error message:

Non merge mode (-merge=false): removing all default non security classesError on database import happened just before line 0, column 1
com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record has no id. It is probably new or still transient
 

## Steps to reproduce  

1. Perform an export for database 1
2. Create destination database
3. Configure destination to run in distributed mode
4. Attempt to run import for the export file obtained in step 1
5. Will receive error message listed under Actual Behavior

Please note, the same export file and same database will successfully import if NOT running in distributed mode.  There is something very specific about running in a distributed environment that causes the issue.  What is the correct approach to run an import into a distributed setup?

**Comment by santo-it** [comment]
Hi,

Thanks for opening this issue. Right now the approach is: re-import in single mode and, after import has been completed, restart in distributed mode. There's a documentation bug open to make this more clear: https://github.com/orientechnologies/orientdb-docs/issues/267

Ideally in the future import will work (directly) also on distributed

Tagging as enhancement. Let us know if you feel we can help more

Thanks,

**Comment by RAndrews137** [comment]
@santo-it   Thanks for replying.  We don't always have control of the destination environment to bring down nodes to do an import.  Do you have any ETA on when it might it might be added as an enhancement?  Do you know what is causing the exception?

**Comment by dalegarv** [comment]
This is Dale from ADP.  We also have the need for our code to create databases on the fly, which requires that we perform a schema import using the Java API.  Of course there's no way we can do this by stopping and starting the database server.

**Comment by lvca** [comment]
Hi guys, you could:
1. create the database while in HA
2. all the nodes will take the database as empty
3. stop replication on all the nodes through SQL command. Example: `HA STOP REPLICATION server2 -dropDatabase`
4. repeat 3 for all the servers but one, so only one server will have the database ONLINE
5. import the database on the online server only
6. set ONLINE the other servers with `HA START REPLICATION server 2 mode FULL`
7. repeat 6 for all the other nodes

**Comment by lvca** [comment]
@RAndrews137 did it work?

**Comment by RAndrews137** [comment]
Hi @lvca,  we have not had a chance to test your suggestion and probably will not have a need to.  Overall, I still suggest having a means to import into an HA cluster with no changes.  Since this is not an active issue for us, perhaps this can be classified as an Enhancement.  Thanks  :)

**Comment by padutilleul** [comment]
Hello,

We are encountering the same problem on OrientDb 2.2.28 Community edition.

We tried running the command `HA STOP REPLICATION orientdb-dev2 -dropDatabase`

But only got the following error :
`Error: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.ha STOP REPLICATION orientdb-dev2 -dropDatabase`

**Comment by mmacfadden** [comment]
@lvca and @tglman this is becoming important to us as well. We will be starting to run in distributed mode in a multi-tenant scenario where each customer has their own database. We definitely need to be able to create and import database in distributed mode without impacting availability of the database. We don't have the option of doing into single mode, or stopping replication cluster wide.

**Comment by tglman** [comment]
Hi,

This is fixed in 3.0.0, now is possible to import a database in distributed, also tests for the case are included.

Closing this
