### ISSUE TITLE
3.0.0-snapshot-459 - shortestpath

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7269]
Hi,

It seems that the shortestpath function is not working in 3.0. Has something changed?

SELECT expand(path) FROM (
  SELECT shortestPath($from, $to) AS path 
  LET $from = (SELECT FROM Profiles WHERE Name='Santo' and Surname='OrientDB'), $to = (SELECT FROM Countries WHERE Name='United States') 
  UNWIND path
)

--> No function with name 'shortestpath', available names are : 

works as expected in 2.2.17

this is related to the demo queries I am creating for the new demodb

Thanks,

**Comment by luigidellaquila** [comment]
That's quite strange, let me check it...

**Comment by luigidellaquila** [comment]
Fixed in develop branch. Keeping this open because I also have to do some work on A* and Dijkstra functions (we need them in core since me implemented the new MultiModel API)

**Comment by luigidellaquila** [comment]
Ok, all the graph functions are now in Core module.

Closing, thanks!

Luigi
