### ISSUE TITLE
Moved 3GB

### ISSUE THREAD

**Issue by notsonotso** [orientechnologies/orientdb#7270]
Just a quick note that we recently moved a ~3GB mongodb db to orientdb with great success, after having experienced several occurrences of data loss on mongodb. 

Thanks for making orientdb.

**Comment by lvca** [comment]
@notsonotso Thanks for sharing that. What kind of application are you developing? We're curious about your use case ;-)

**Comment by notsonotso** [comment]
antifraud software

**Comment by luigidellaquila** [comment]
Hi @notsonotso 

Thank you very much for this info, I'm closing this ticket.
If you need help on OrientDB please feel free to ask

Thanks

Luigi
