### ISSUE TITLE
Query returns incorrect results

### ISSUE THREAD

**Issue by alpeshgaglani** [orientechnologies/orientdb#7271]
OrientDB Version: 2.2.17

Our database returns wrong results for the following query:
select expand($courses) from Activity let courses = (select from $current.in_ContainsActivity.out) where id = 809
The query returns a record with the class "Course", and id = 67

However, if you follow the in_ContainsActivity.out link from Activity where id = 809, the record that should be returned has id = 54

I've uploaded an export of our test database where this issue occurs:
https://drive.google.com/file/d/0B_TS9oS4-Fi2UDh4b0VxbU1NbHc/view?usp=sharing

**Comment by alpeshgaglani** [comment]
Any updates on this issue? It's really hurting us right now.

**Comment by luigidellaquila** [comment]
Hi @alpeshgaglani 

I'm not sure I got the point of your query... That `$current` refers to records in the subquery, not in the parent query. The right syntax should be:
```
select expand($courses) from Activity let courses = (select from $parent.$current.in_ContainsActivity.out) where id = 809
```
But why should you use that? Can't you just do

```
select expand(in_ContainsActivity.out) from Activity where id = 809
```

or even better

```
select expand(in("ContainsActivity")) from Activity where id = 809
```

Thanks

Luigi

**Comment by alpeshgaglani** [comment]
Thanks @luigidellaquila for the response. Our understanding was that in this particular case, $current refers to the current record set in the top level query. Interestingly, this used match exactly with our understanding up until 2.1.x! We have to use projection because we are doing further sub queries. I had just posted the simplified query to help debugging :)
:+1: for your help!

**Comment by luigidellaquila** [comment]
HI @alpeshgaglani 

Just to give you all the info, $current variable refers to the current record in current (sub) query. If you want to access the parent query context you can use $parent variable, eg. $parent.$current refers to the current record in parent query. You can also use it at multiple levels, eg. $parent.$parent.$current.

I guess I can close this issue, please reopen if you need further help

Thanks

Luigi
