### ISSUE TITLE
3.0.0-snapshot-464 - Preserve order of fields in OResult 

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7272]
Hi,

It seems that if field.@Rid as Field_RID, is included, the order is not preserved.
Wondering if an additional fix can resolve this. 

Eg, for this query:

MATCH {Class: Profiles, as: profile, where: (Name='Santo' AND Surname='OrientDB')}-HasFriend-{Class: Profiles, as: friend} 
RETURN friend.@Rid as Friend_RID, friend.Name as Friend_Name, friend.Surname as Friend_Surname 

This is the result:

![github_issue](https://cloud.githubusercontent.com/assets/14923389/24335187/f867cade-1278-11e7-9af6-b043eb99f634.PNG)

expected order: 

 Friend_RID,   Friend_Name,  Friend_Surname 

Thanks,

**Comment by luigidellaquila** [comment]
Good catch @santo-it 

I just pushed a fix on develop branch

Thanks!

Luigi

**Comment by luigidellaquila** [comment]
Sorry, it seems that this fix breaks a test case. 
I'm reverting it for now and reopening the issue. 

Luigi

**Comment by luigidellaquila** [comment]
Hi @santo-it 

This is already fixed in 3.0.0M2

Closing, thanks!

Luigi
