### ISSUE TITLE
Support for remote SET/LIST/DELETE SERVER USER commands

### ISSUE THREAD

**Issue by dalegarv** [orientechnologies/orientdb#7276]
## Expected behavior  
Running the server user commands in the console after establishing a remote connection should run against the remote server.

## Actual behavior  
Running the server user commands in the console after establishing a remote connection are running against the local server.

## Steps to reproduce  
1) Start the console.sh
2) connect to a remote server
3) run any of the set/list/delete server user commands

**Comment by SDIPro** [comment]
Hi @dalegarv.  Unfortunately, those console commands aren't designed to be used with remote.  They actually only affect the local copy of orientdb-server-config.xml where the console is running.

If I were you, I'd open a separate issue as a feature request.

Thanks,
-Colin

**Comment by lvca** [comment]
Those commands were designed to work locally only.
