### ISSUE TITLE
Error on conversion of date '2017-03-26 02:00:00.000' using the format: yyyy-MM-dd HH:mm:ss

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7277]
## Expected behavior  
When storing a DATETIME of value 2017-03-26 02:00:00.000 AM , the exact switch-over from Wintertime to Summertime, it should be allowed.
Of course any DATETIME value between [2017-03-26 02:00:00.001 .. 2017-03-26 03:00:00.000] should then be denied.

## Actual behavior  
2017-03-26 02:00:00.000 AM is denied with the error message from the title.

The ODB server process has been started with the environment variable "TZ" set to value "MET".

-> timezone of database is now set to "Europe/Brussels"
-> setting timezone of database to "UTC" will of course accept the DATETIME value of 2017-03-26 02:00:00.000, but will eventually (when Summertime is switching back to Wintertime) be presented with duplicate timestamps like 2017-10-29 02:30:00.000 because the programs themselves are not running with UTC (but instead with MET)

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Thank you for reporting, we'll check it. 
In the meantime I can tell you that OrientDB just uses Java DataFormat to format strings to datetime, so everything that is allowed in Java is also allowed in OrientDB. You can find the docs here: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

Thanks

Luigi

**Comment by lvca** [comment]
The formats are different. Please change the OrientDB datetime so support ms:

`ALTER DATABASE datetime "yyyy-MM-dd HH:mm:ss.SSS"`

**Comment by rdelangh** [comment]
hi @lvca , can you please tell me how I can view the current setting of the "datetime" format?

**Comment by lvca** [comment]
You can see the current settings also in studio.

**Comment by rdelangh** [comment]
@lvca , in Studio, under Servers Management, the only accessible option I have is to view the "Global Cfg" but there is no option whose name is containing "datetime"; the option "Server Cfg" is not accessible to me.

In console, I can run the "config" command, but none of the listed options contains something like "datetime"...

**Comment by rdelangh** [comment]
hi Luca,
can we have an update, please? Where do we find the "datetime" setting of the database?

**Comment by robfrank** [comment]
YOu can see the datetime format on db-->configuration. On localhost: http://localhost:2480/studio/index.html#/database/GratefulDeadConcerts/db/configuration

**Comment by rdelangh** [comment]
hi @robfrank , thank you, because now I see that the correct name of this parameter is not "datetime", but rather "datetimeformat"
-> I have changed this setting via "console.sh" : 
```
orientdb {db=mobile}> alter database datetimeformat "yyyy-MM-dd HH:mm:ss.SSS"
Database updated successfully.
```

-> is there any reason that the web interface shows this parameter, and only a very few others, whereas the CLI method via "console.sh" with the command "config" shows an entire bunch of different parameters which do not correspond with what's display via the web interface?

**Comment by robfrank** [comment]
About different names for info on console  and on studio, the console itself uses custom labels for parameters. I will talk with other  members of the team if it is better to use same names
