### ISSUE TITLE
Hibernate dependency is LGPL

### ISSUE THREAD

**Issue by christinedraper** [orientechnologies/orientdb#7278]
## Expected behavior  
No copy-left dependencies.  

## Actual behavior  

This hibernate-jpa-2.0-api  1.0.0.Final dependency: in graph-orientdb:

https://github.com/orientechnologies/orientdb/blob/master/object/pom.xml#L77-L80

is LGPL.

## Steps to reproduce  

https://mvnrepository.com/artifact/org.hibernate.javax.persistence/hibernate-jpa-2.0-api/1.0.0.Final

**Comment by tglman** [comment]
hi @christinedraper,

Thank you for checking this, anyway the hibernate-jpa api is released as "Eclipse Distribution License" (here is the pom http://repo1.maven.org/maven2/org/hibernate/javax/persistence/hibernate-jpa-2.0-api/1.0.1.Final/hibernate-jpa-2.0-api-1.0.1.Final.pom) that is compatible with the Apache License, you can check it here: https://www.apache.org/legal/resolved.html#category-a


We got audited by third party so I was pretty confident it was al right ;), anyway I double checked.

I'm closing this.

Regards

**Comment by christinedraper** [comment]
It would be OK if you were using 1.0.1, but you are using 1.0.0.

            <groupId>org.hibernate.javax.persistence</groupId>
            <artifactId>hibernate-jpa-2.0-api</artifactId>
            <version>1.0.0.Final</version>
            <type>jar</type>

https://mvnrepository.com/artifact/org.hibernate.javax.persistence/hibernate-jpa-2.0-api/1.0.0.Final

**Comment by tglman** [comment]
hi @christinedraper,

I see your point, the 1.0.0.Final it does not include the license files inside the source jars and in the pom.xml refer to a license.txt file that I cannot find anywhere on the maven repository, i'll update our dependency to 1.0.1.Final, just to be sure everything is correct.

**Comment by christinedraper** [comment]
Thanks!
