### ISSUE TITLE
Error on ALTER DATABASE DATETIMEFORMAT (CHARACTER_LITERAL)

### ISSUE THREAD

**Issue by F-hertz** [orientechnologies/orientdb#7280]
### OS: Ubuntu

Hello, i m getting this error when trying to set datetimeformat :

orientdb {db=DATATEST}> ALTER DATABASE DATETIMEFORMAT yyyy-MM-dd'T'HH:mm:ss'Z'

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
alter DATABASE DATETIMEFORMAT yyyy-MM-dd'T'HH:mm:ss'Z'
                                          ^
Encountered " <CHARACTER_LITERAL> "\'T\' "" at line 1, column 41.
Was expecting one of:
    <EOF> 
    ";" ...
    
	DB name="DATATEST"
	DB name="DATATEST"

**Comment by luigidellaquila** [comment]
Hi @F-hertz 

Please try to quote the format string:

```
ALTER DATABASE DATETIMEFORMAT "yyyy-MM-dd'T'HH:mm:ss'Z'"
```

Thanks

Luigi

**Comment by F-hertz** [comment]
Thanks it works.

**Comment by luigidellaquila** [comment]
Great, closing then

Thanks

Luigi
