### ISSUE TITLE
OLocalRecordCache allows temporary  @RID dublication

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#7282]
## Expected behavior  
 OLocalRecordCache must controll dubles. 

## Actual behavior  
Rows from log.
```
[main] 08:25:36,430 DEBUG org.hibernate.ogm.datastore.orientdb.dialect.impl.OrientDBAssociationQueries: findRelationship: queryBuilder: SELECT FROM Pizza_Product WHERE pizzas_bKey=2  AND products_id='1c2a404e-c9ea-485e-b2b4-1b0c9d5e288a' 
[main] 08:25:36,431 DEBUG org.hibernate.ogm.datastore.orientdb.utils.NativeQueryUtil: NonIdempotentQuery: loaded document: {"@type":"d",**"@rid":"#29:-20"**,"@version":0,"@class":"Pizza_Product","products_id":"1c2a404e-c9ea-485e-b2b4-1b0c9d5e288a","pizzas_bKey":2,"@fieldTypes":"pizzas_bKey=l"}
[main] 08:25:36,432 DEBUG org.hibernate.ogm.datastore.orientdb.utils.NativeQueryUtil: NonIdempotentQuery: loaded document: {"@type":"d",**"@rid":"#29:-20"**,"@version":0,"@class":"Pizza_Product","products_id":"1c2a404e-c9ea-485e-b2b4-1b0c9d5e288a","pizzas_bKey":2,"@fieldTypes":"pizzas_bKey=l"}
[main] 08:25:36,433 DEBUG org.hibernate.ogm.datastore.orientdb.utils.NativeQueryUtil: load documents: 2
[main] 08:25:36,433 DEBUG org.hibernate.ogm.datastore.orientdb.dialect.impl.OrientDBAssociationQueries: findRelationship: found: 2
```
Query returns two documents with same @rid.

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

Is this problem deterministic? Is there a specific way to reproduce it?

Thanks

Luigi

**Comment by lvca** [comment]
Hi @schernolyas, closing this issue because no information to reproduce it. In case please comment it and we will be happy to reopen it. Thanks.

**Comment by schernolyas** [comment]
Hi @lvca and @luigidellaquila !

The issue linked with other my issues for OrientDB 3.0.0-SNAPSHOT.
I guess that OrientDB 3.0.0-SNAPSHOT not conttoll local cache.
Steps to reproduce is simple.
1) open transaction
2) inset two objects with save class
3) look to problem ...

But  I not watch reproduce the bug in last commits. Now other problem: OrientDB 3.0.0-SNAPSHOT returns row with defferent id (incorrect search result).

**Comment by laa** [comment]
@schernolyas what do you mean "OrientDB 3.0.0-SNAPSHOT returns row with different id (incorrect search result)"

**Comment by schernolyas** [comment]
Hi @laa 

Hm ... I mean scenario :
1) open new transaction
2) add Person with id="a"
3) execute query: select from Pesron where id="b"
4) show result and see Person with id="a"

Please  fix it. It blocked me in Hibernate OGM migration

**Comment by laa** [comment]
@schernolyas how do you perform this operation by using SQL or Java commands?  Will it be possible for you to write small or not so small )) unit test to reproduce the problem ? I ask you because we have plenty such tests which you described and all of them are passed.

**Comment by schernolyas** [comment]
Hi @laa 

I use [the class](https://github.com/schernolyas/hibernate-ogm/blob/ogm-855-migration-orientdb3-dev1/orientdb/src/main/java/org/hibernate/ogm/datastore/orientdb/utils/NativeQueryUtil.java) for execute queries.

**Comment by schernolyas** [comment]
Also ... @laa What do I provide aditional information ?

**Comment by schernolyas** [comment]
HI @laa !
I am not reproduce the problem. May be .... it is self-fixed bug.  I am goinh to close it.
