### ISSUE TITLE
incorrect result of function 'count'

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#7283]
## Expected behavior  
query "select count(@rid) as c from Customer where bKey=1"  must returns one.

## Actual behavior  
query "select count(@rid) as c from Customer where bKey=1"  must returns zero.
query  "select  from Customer where bKey=1" returns correct list of documents.

## Steps to reproduce  
execute query

**Comment by schernolyas** [comment]
Hi @luigidellaquila !

May be it helps to You. My module executes these queries during transaction. 

I assume that function 'count' count committed objects only.  but ...

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

Thank you very much, it's definitely a valuable information! In V 3.0 the executor also considers documents created in current tx, so probably the issue is related to this. I'll let you know soon

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila !

Okey. I migrate my integration module from OrientDB 2.2 to OrientDB 3.0. And  I have about 250 tests. 
I will send to You information about bugs in release 3.0

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

Thank you very much, very appreciated, early feedback on 3.0 is critical to reach a good level of stability on the GA

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

I just tried it on latest snapshot and it seems to work fine. I tried it on `demodb` with the following query:

```
select count(@rid) as c from Countries where Id = 1
```

Do you have a specific dataset to reproduce the problem? Or maybe it's just already fixed?

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila !

Did you check it in transacton?  Hibernate OGM do everything in transaction. 

But  okey. I will update my snapshot of OrientDB and recheck.

Self-fixed bugs ... is cool!

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

I doubt it's self fixed 😆 maybe we did some changes in last few days that also impacted this. Develop branch is very active, so you can expect things to be fixed over night.

I didn't try it in tx, I'm doing it now. I'll let you know soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, I tried it in tx, no luck on reproducing the issue unfortunately.
If you could reproduce it with plain Java or SQL it would help a lot on fixing

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila !

I see that you need additional information about the bug. 
How I can set DEBUG logging level for OrientDB?

**Comment by schernolyas** [comment]
P.S. I start OrientDB  as in-memory database.

**Comment by schernolyas** [comment]
Hi @luigidellaquila !

I rechecked. My last commit is commit cd19bceed19598c1681cef4bf8dd3554aac35028
I see that function 'count' fine.

self-fixed bug :)

**Comment by luigidellaquila** [comment]
Great!!! I like self-fixing bugs 😄
