### ISSUE TITLE
Cannot import or connect to database in Studio - HTTP Auth

### ISSUE THREAD

**Issue by dannykopping** [orientechnologies/orientdb#7285]
### OS: Alphine 3.5.2

(I'm using the Docker image)

## Expected behavior  
Attempt to create or import a database, using admin/admin as user/pass as instructed in docs.

## Actual behavior  
Presented with HTTP auth which I cannot get past.

**Comment by Solido** [comment]
Did you configure the DOCKER ENV with the root password ?
ORIENTDB_ROOT_PASSWORD=yourpass

**Comment by dannykopping** [comment]
I did, yes.

I tried with and without it set.

**Comment by maggiolo00** [comment]
hi @dannykopping 

did you try to use the root user?

**Comment by dannykopping** [comment]
Hey, yes i did

**Comment by maggiolo00** [comment]
Do you still have problem with root user?

**Comment by dannykopping** [comment]
Yes i do

**Comment by maggiolo00** [comment]
hi @dannykopping 

are you able to connect with console?
