### ISSUE TITLE
DICTIONARY index: is there a way to remove old versions of records?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7286]
## Expected behavior  
I have a class with a DICTIONARY index, in which I many times add new values for existing records; the behaviour of a DICTIONARY index is that it creates each time a new record, with the new value. This is as expected.
Because the intensity that we have to do this, the class contains now zillions (=360M) of records with old versions.

-> is there any way to cleanup this class (= remove records with old version)?
-> is there a global setting (or per class) that can limit how many versions of each record should be preserved? Which mechanism would kick in to remove older versions?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I don't know if I got your use case right, but the purpose of DICTIONARY index is to be used as a manual index, not as a class index.
If you need an automatic index I suggest you to use a normal NOTUNIQUE index on a property.

What do you mean when you say ` is there a global setting (or per class) that can limit how many versions of each record should be preserved`? Indexes only keep a reference to documents, they do not contain full documents, so this should never happen...

Thanks

Luigi

**Comment by rdelangh** [comment]
hi Luigi,

can you please define "manual index" ? I do nowhere in the docs find any description of that term. The DICTIONARY index is listed in the docs about HASH indexes, http://orientdb.com/docs/master/Hash-Index.html
In that page, with very little description about the different types of HASH indexes, nowhere any restriction is documented where DICTIONARY (or other hash indexes) can be used and where it cannot be used...

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

A manual index is an index that is not automatically maintained by OrientDB, ie. OrientDB does not update it when you insert/update/delete records in classes.

When you declare an automatic index, you define it on a class and some fields. When you add a new record to that class, OrientDB automatically indexes that record.

When you define a manual index, you do not specify any classes or properties for it. To put data into the index you have to manually do it through java API  or via SQL (`INSERT INTO index:foo ... `)

There are some mentions in the docs here http://orientdb.com/docs/2.2.x/Indexes.html#create-a-manual-index-in-java and here http://orientdb.com/docs/2.2.x/Key-Value-use-case.html but I agree with you that it will need a separate section

I hope it helps

Thanks

Luigi

**Comment by rdelangh** [comment]
grr, this is one more potential way that I hoped to use, which appears unusable for my requirement:
see #6790, where I describe how I want to have a functionality in the style of traditional databases' MERGE statement:

```
IF (record exists according to some key fields) THEN
   UPDATE some but not necessary all of its fields
ELSE
   INSERT a new record with all of its fields' values
ENDIF
```

I hoped that the DICTIONARY hash index would have allowed me to simply INSERT again records, which -if they would appear to exist already according to the index value- would simply add a new copy of the record with a new version as if it is an update of the existing record.

But hell no...

Are there any blocking internals to make such DICTIONARY hash indexes also supported as 'automatic' indexes, just like all others?

**Comment by rdelangh** [comment]
I can assume that you will answer that I should use a 'script'ed way to SELECT-then-UPDATE-or-INSERT the records, but mind you that such scripted way is then executed for single records only.

What we need is the possibility to bulk-MERGE or (if DICTIONARY hash index would be automatic) bulk-INSERT the outcome of a subquery, like in:
```
INSERT INTO someclass FROM
   SELECT ... FROM ...
```

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Maybe an UPDATE UPSERT will do the trick? Eg.

```
UPDATE Foo UPSERT SET id="foo", name="bar" WHERE id = "foo"
```

This will first search for a record with id = "foo" and in case it will create it. In both cases it will set name = "bar".
Also make sure to define a unique index on the `id`

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Sorry, wrong syntax, the right one is:

```
UPDATE Foo SET id="foo", name="bar" UPSERT WHERE id = "foo"
```

Thanks

Luigi

**Comment by rdelangh** [comment]
hi @luigidellaquila 
as described above, what you suggest is to use methods that work only for single records, of which the property-values are known to the invoking program so that it (= the invoking program) can specify these property-values in a WHERE-clause.

Our use case is that we need to UPDATE-or-INSERT a bunch of records that come from a SELECT subquery which returns some 100's or 1000's of records, pls see my previous comment

**Comment by luigidellaquila** [comment]
Uhm... ok, got it.
I think there is no SQL based solution for this, maybe you can consider using a JS function or a piece of embedded Java...

Thanks

Luigi

**Comment by rdelangh** [comment]
Javascript is an option, but where can we find substantial documentation about how to work against ODB from a JS function, for such bulk-actions ?

**Comment by rdelangh** [comment]
Can we see somewhere such Javascript-based examples, or a tutorial of some kind in the documentation?

**Comment by lvca** [comment]
The doc team is already working on it. The new docs should be ready in about one week.
