### ISSUE TITLE
Incorrect return value when formatting a list of dates

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#7289]
### OS: Linux

Setup:
```
CREATE CLASS Foo EXTENDS V
CREATE CLASS Bar EXTENDS V
CREATE PROPERTY Bar.event_date DATETIME

CREATE VERTEX Foo SET name = 'foo'
CREATE VERTEX Bar SET name = 'bar1', event_date = '2016-01-01 00:00:01'
CREATE VERTEX Bar SET name = 'bar2', event_date = '2016-01-02 00:00:02'

CREATE EDGE E FROM (SELECT * FROM Foo) TO (SELECT * FROM Bar)
```

## Expected behavior  
Consider the following two queries:
```
SELECT name AS foo_name, out('E').name AS bar_names, out('E').event_date AS bar_dates FROM Foo

SELECT name AS foo_name, out('E').name AS bar_names, out('E').event_date.format("YYYY-MM-DD'T'HH:mm:ssX") AS bar_dates FROM Foo
```
The `bar_dates` field should be a list of two elements in both queries:
- In the first query, it should be a list of datetime objects (represented as strings in Studio: `["2016-01-02 00:00:02","2016-01-01 00:00:01"]`).
- In the second query, it should be a list of ISO-8601 formatted datetime strings: `["2016-01-02T00:00:02Z","2016-01-01T00:00:01Z"]`.

## Actual behavior  
First query output for `bar_dates`: `["2016-01-02 00:00:02","2016-01-01 00:00:01"]`
Second query output for `bar_dates`: `YYYY-MM-DD'T'HH:mm:ssX`

## Steps to reproduce  
See the setup and queries above.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I just pushed a fix on 2.2.x branch.

Thanks!

Luigi

**Comment by obi1kenobi** [comment]
Hey @luigidellaquila, just a quick-up question -- this will work for both Date and Datetime OrientDB field types, right? 

Thank you!

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

Yes, it will ;-)

Thanks

Luigi
