### ISSUE TITLE
orientDb unable to get outgoing edges.

### ISSUE THREAD

**Issue by Raycoms** [orientechnologies/orientdb#7292]
### OrientDB Version: <version here>  
    compile group: 'com.orientechnologies', name: 'orientdb-graphdb', version: '2.2.11'
### Java Version: <version here>  
1.8
### OS: <os here>  
Linux/Windows

## Expected behavior  
vertex1.getEdges(Direction.OUT, relationshipId) returns the given relationship

## Actual behavior  
vertex1.getEdges(Direction.OUT, relationshipId) returns empty

## Steps to reproduce  
Fill Database with some nodes and edges.
Take one note and execute the method on it and require the outgoing edge.
Returns empty list for me.

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

This is a very basic operation, it's quite unlikely that it doesn't work in general.
Can you please post a script to reproduce it? Which value are you passing as `relationshipId`?

Thanks

Luigi

**Comment by Raycoms** [comment]
I tested vertex2.getEdges(Direction.IN, relationshipId) and it worked great.
I took the relationship I received, searched for an outgoing node and found vertex1.
It just didn't work the other way around.

Whole code of the project regarding orientDB:

https://github.com/Raycoms/thesis/blob/master/src/main/java/main/java/com/bag/server/database/OrientDBDatabaseAccess.java

It would be great if there was a method "graph.getEdge(startVertex, endVertex, type)"

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

From your code, I see the following:

```
final String relationshipId = "class:" + relationshipStorage.getId();
```

For edges, you don't have to prefix class names with "class:" (it's needed for addVertex() though), probably this is the reason why it doesn't work. Just try to replace it with the following:

```
final String relationshipId = relationshipStorage.getId();
```

Please let me know if it fixes the problem

Thanks

Luigi

**Comment by Raycoms** [comment]
I already tried that. I even added both versions in it.
Strangely, I got the correct return for the "IN" case when prefixing "class:" .

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

I could not manage to find anything strange in the code. It would be great if you could isolate the problem in a small test case.

Thanks

Luigi

**Comment by Raycoms** [comment]
I am working on my thesis this week. I might be able to get something isolated in the next 2 weeks.

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

Did you have a chance to review this? Does this issue still make sense?

Thanks

Luigi

**Comment by Raycoms** [comment]
Still happening, we have build the work around I wrote.
Will have to publish a paper soon so I unfortunately don't have the time to
further investigate this.

2017-05-02 10:20 GMT-03:00 luigidellaquila <notifications@github.com>:

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

Does this issue still happen in latest version? Do you have any updates?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

I'm closing this issue (no response for a long time), please feel free to re-open if it's still relevant

Thanks

Luigi
