### ISSUE TITLE
Performance of insert Edge

### ISSUE THREAD

**Issue by DienNM** [orientechnologies/orientdb#7293]
### OS:Ubuntu 14.04  

Hi team,
I am using OrientDB as a graph database. I try to insert/update property of Edges between Vertexes.
With 500 pairs (vertex-vertex), it took about ~6 second to insert / update the weight of Edge. 

Is it reasonable? There are 100K vertex in my database and I am trying to create their relation.

Thanks.

**Comment by luigidellaquila** [comment]
Hi @DienNM 

How are you doing the insert? SQL, Java API or something else?
You can do much better using the right API...

Thanks

Luigi

**Comment by DienNM** [comment]
Hi Luigi,

I use Java API. my code looks like below. I need to update TIMES in the Edge

`OrientGraphNoTx txGraph = factory.getNoTx()...

OrientVertex vertex1 = txGraph.getVertex(rid1);
OrientVertex vertex2 = txGraph.getVertex(rid2);

Iterable<Edge> edges = vertex1.getEdges(vertex2, Direction.BOTH, EdgeName.Buy2GetherInvoice.getText());
boolean connected = false;
Edge edge = null;
for (Edge e : edges) {
    connected = true;
    edge = e;
    break;
}
if (!connected) {
    edge = txGraph.addEdge(null, vertex1, vertex2, EdgeName.Buy2GetherInvoice.getText());
    edge.setProperty(ProductBuyTogether.F_TIMES, 1L);
    return edge;
}
long currentTimes = edge.getProperty(ProductBuyTogether.F_TIMES);
edge.setProperty(ProductBuyTogether.F_TIMES, currentTimes + times);
`


Thanks,
Dien

**Comment by luigidellaquila** [comment]
Ok, first of all you can try changing 

```
OrientGraphNoTx txGraph = factory.getNoTx()...
```

with 
```
OrientGraph txGraph = factory.getTx();
```

and do a `txGraph.commit()` after each edge is completed, eg. after

```
long currentTimes = edge.getProperty(ProductBuyTogether.F_TIMES);
edge.setProperty(ProductBuyTogether.F_TIMES, currentTimes + times);
txGraph.commit();
```

This will save you a lot of network operations if you are in remote.

You can also do this in batches, eg. 500 edges per commit, you will save even more resources

I hope it helps

Thanks

Luigi

**Comment by DienNM** [comment]
Thanks Luigi, let me try and update later

**Comment by luigidellaquila** [comment]
Ah, if you have a chance to connect in `plocal` insetad of `remote` you will have 10x for free ;-)

Thanks

Luigi

**Comment by DienNM** [comment]
Hi Luigi,
I used OrientGraph txGraph = factory.getTx(); and I got a bit faster. 
I am trying to connect in plocal but not success. I use console.sh to create plocaldb. 

> connect plocal:/path_to_database/dbname
> Database created successfully.

> connect plocal:/path_to_database/dbname root my_password
 
But I do not know which account should be used to login. I tried with root but not success:
`Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'dbname'`

I am a newbie with this, hope to see your help

Thanks

**Comment by DienNM** [comment]
I can connect now. It is really fast.
And the last question :), I insert ~20 million edges of ~30K vertex (1 file). It is getting slow when I import frequency files. from 500 edges took < 500ms, now 500 took 2000ms. Is it reasonable?

I always commit and shutdown OrientGraph to avoid leak memory
`public void returnGraphTx(OrientBaseGraph graph) {
        try {
            graph.commit();
            graph.getRawGraph().getLocalCache().clear();
            graph.shutdown();
        } catch (Exception e) {
            logger.error("Error occured during return graph: {}", e);
        }
    }`

**Comment by luigidellaquila** [comment]
Hi @DienNM 

Probably the performance degradation is due to the `for` loop to check if the edge exists. When vertices become bigger (a lot of edges), the loop takes more time. 
Probably you can work around this as follows:
- define `out` and `in` properties on the edge class
- define an index on these properties
- instead of doing a `for` loop, just execute a query as follows

```java
db.query(new OSQLSyncQuery("SELECT FROM TheEdgeClass where out = ? AND in = ? limi 1"), vertex1.getId(), vertex2.getId());
```

If the query returns any results, it means that the edge exists, otherwise it doesn't.

In general, you can avoid the `graph.getRawGraph().getLocalCache().clear();`

I hope it helps

Thanks

Luigi

**Comment by DienNM** [comment]
Thanks @luigidellaquila 
It's really fast, only ~300ms per 500 edges.

I appreciate your help.
