### ISSUE TITLE
Graph Editor - data is undefined

### ISSUE THREAD

**Issue by karolmie1** [orientechnologies/orientdb#7297]
## Expected behavior  
Graph is shown

## Actual behavior  

```
Error: data is undefined
GraphService<.add@http://localhost:2480/studio/main.js:183923:9
$scope.query/</<@http://localhost:2480/studio/main.js:190566:9
timeout/timeoutId<@http://localhost:2480/studio/main.js:171125:28
completeOutstandingRequest@http://localhost:2480/studio/main.js:157299:7
Browser/self.defer/timeoutId<@http://localhost:2480/studio/main.js:157578:7
ZoneDelegate.prototype.invokeTask@http://localhost:2480/studio/main.js:242353:21
NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@http://localhost:2480/studio/main.js:50216:28
ZoneDelegate.prototype.invokeTask@http://localhost:2480/studio/main.js:242352:21
Zone.prototype.runTask@http://localhost:2480/studio/main.js:242242:28
ZoneTask/this.invoke@http://localhost:2480/studio/main.js:242423:28
scheduleTask/data.args[0]@http://localhost:2480/studio/main.js:243240:13
```

Even thought response returned data: (excerpt here)
`{"result":[{"@type":"d","@rid":"#17:0","@version":4,"@class":"DatabaseVersion","version":4,"@fieldTypes":"version=s"}, {"@type":"d","@rid":"#21:0","@version":2,"@class":"Permission","type":"ADMIN","in_hasPermission":["#29:0"],"@fieldTypes":"in_hasPermission=g"}, {"@type":"d","@rid":"#22:0","@version":6,"@class":"Permission","type":"USER","in_hasPermission":["#30:0","#31:0","#32:0","#29:1","#30:1"],"@fieldTypes":"in_hasPermission=g"}, {"@type":"d","@rid":"#25:0","@version":3,"@class":"User","login":"admin","email":"admin@gmail.com","fullName":"Admin - konto funkcyjne","password":"$2a$10$IiHx7qdwFQJzWFWrqUlK2uAkI0DjVC.o.6sYBUGG7j15u1E7h2hbe","out_hasPermission":["#29:0","#30:0"],"@fieldTypes":"out_hasPermission=g"}, `

This happened somewhere between 2.2.10 and 2.2.17 (Unfortunately due to my setup I cannot try out the versions between to try to pinpoint the issue - it stopped working for me after update from 2.2.10).

The problem happens on firefox. 

On chrome I encounter: 

```
main.js:165374 TypeError: Cannot read property 'edges' of undefined
    at core_1.Class.constructor.add (http://localhost:2480/studio/main.js:183923:94)
    at http://localhost:2480/studio/main.js:190566:22
    at http://localhost:2480/studio/main.js:171125:31
    at completeOutstandingRequest (http://localhost:2480/studio/main.js:157299:10)
    at http://localhost:2480/studio/main.js:157578:7
    at ZoneDelegate.invokeTask (http://localhost:2480/studio/main.js:242353:35)
    at Object.onInvokeTask (http://localhost:2480/studio/main.js:50216:37)
    at ZoneDelegate.invokeTask (http://localhost:2480/studio/main.js:242352:40)
    at Zone.runTask (http://localhost:2480/studio/main.js:242242:47)
    at ZoneTask.invoke (http://localhost:2480/studio/main.js:242423:33)
    at data.args.(anonymous function) (http://localhost:2480/studio/main.js:243240:25)
``` 

Errors happen in this function: 

```
add: function (db, user, data) {
        this.init(db, user);
        this.databases[db][user].data.edges = this.databases[db][user].data.edges.concat(data.edges);
        this.databases[db][user].data.vertices = this.databases[db][user].data.vertices.concat(data.vertices);
    },
```

## Steps to reproduce  
1. git clone https://bitbucket.org/kmierzej/fragaria-server
2. ./gradlew run
3. http://localhost:8081/orient/studio/
4. go to graph editor, and write down random query, for example: SELECT * FROM V

**Comment by maggiolo00** [comment]
hi @karolmie1 

i tried to reproduce it, but i got this on `./gradlew run`

```
:compileKotlin UP-TO-DATE
:compileJava NO-SOURCE
:copyMainKotlinClasses UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:copyAgent UP-TO-DATE
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find pl.eightandcounting.fragaria:fragaria-webapp:0.5.0.
     Searched in the following locations:
         file:/Users/enricorisa/.m2/repository/pl/eightandcounting/fragaria/fragaria-webapp/0.5.0/fragaria-webapp-0.5.0.pom
         file:/Users/enricorisa/.m2/repository/pl/eightandcounting/fragaria/fragaria-webapp/0.5.0/fragaria-webapp-0.5.0.jar
         https://jcenter.bintray.com/pl/eightandcounting/fragaria/fragaria-webapp/0.5.0/fragaria-webapp-0.5.0.pom
         https://jcenter.bintray.com/pl/eightandcounting/fragaria/fragaria-webapp/0.5.0/fragaria-webapp-0.5.0.jar
         http://dl.bintray.com/kotlin/kotlin-eap-1.1/pl/eightandcounting/fragaria/fragaria-webapp/0.5.0/fragaria-webapp-0.5.0.pom
         http://dl.bintray.com/kotlin/kotlin-eap-1.1/pl/eightandcounting/fragaria/fragaria-webapp/0.5.0/fragaria-webapp-0.5.0.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by karolmie1** [comment]
Just comment out the dependency in build.gradle:
   // runtime group: 'pl.eightandcounting.fragaria', name: 'fragaria-webapp', version: '0.5.0'

You won't have an access to the app, but orient will work all right.

**Comment by maggiolo00** [comment]
Ok @karolmie1 
Thanks

**Comment by karolmie1** [comment]
I am terribly sorry, you probably have to remove http2 connectors in config.yml to not have to setup keystore and all that stuff, I will branch you this in a minute, so you won't have to do this.

**Comment by maggiolo00** [comment]
@karolmie1 

Thanks

**Comment by maggiolo00** [comment]
hi @karolmie1 

i see that you do not use the GraphHandler in your configuration, like the default one
https://github.com/orientechnologies/orientdb/blob/2.2.x/graphdb/config/orientdb-server-config.xml

Maybe you don't need it, but around 2.2.10 i think, we introduced an option 
in the api that gives back the JSON in Graph Format using the GraphAPI  and Studio uses it.
I think that is the problem. If you activate the GraphHandler, it should work again.

Let me know if it helps 
Thanks

**Comment by karolmie1** [comment]
Yup, that was it. Thanks!
