### ISSUE TITLE
`dserver.sh` or `server.sh` when setting up a cluster?

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#7298]
### OS: Ubuntu 16.04

When setting up an OrientDB cluster (distributed mode), is there any need to edit the `server.sh` file? I'm asking, because I thought the server file to edit when setting up a cluster is `dserver.sh`. And I got a bit confused with this paragraph from [this page](http://orientdb.com/docs/last/Tutorial-Setup-a-distributed-database.html)

> NOTE: When you run in distributed mode, OrientDB needs more RAM. The minimum is 2GB of heap, but we suggest to use at least 4GB of heap memory. To change the heap modify the Java memory settings in the file **bin/server.sh** (or server.bat on Windows).

**Comment by luigidellaquila** [comment]
Hi @finid 

I think it's just a typo in the docs, when you launch dserver.sh there is no need to edit server.sh

I'll fix the docs

Thanks

Luigi

**Comment by finid** [comment]
Thank you @luigidellaquila. Consider this closed.
