### ISSUE TITLE
Possible support for RETURN vertex.*

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7300]
### OS: any

Hi,

ER to improve, if possible, RETURN clause of MATCH syntax

Suppose you return a friend vertex. You can write: RETURN friend.Name, friend.Surname, but you can't simply write friend.* to get all properties, e.g.

MATCH .... RETURN friend.*

The workaround is to expand:

SELECT expand(friend) FROM (MATCH ... RETURN friend)

Compare 1st and 2nd query - first one is short and easy

Thanks,

**Comment by luigidellaquila** [comment]
Hi Santo,

WDYT about supporting a simple `RETURN expand(friend)`?
It's more consistent with the rest of the grammar

Thanks

Luigi

**Comment by santo-it** [comment]
Hi @luigidellaquila,

Okay for me. This is going to be useful and easy to use.

Thanks,
