### ISSUE TITLE
Downloaded v2.2.17, but running v2.2.16

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#7301]
## Expected behavior  
After unzipping a `orientdb-community-2.2.17.tar.gz` file, expected the directory to be named  `orientdb-community-2.2.17`. 

## Actual behavior  
However, the directory is named `orientdb-community-2.2.16`  

## Steps to reproduce  
1. Download the latest by executing this command:
```
wget http://mkt.orientdb.com/CE-2216-multiOS -O orientdb-community-2.2.17.tar.gz
```
2. Unzip the file using:
```
unzip orientdb-community-2.2.17.tar.gz
```

3. An `ls -l` shows:

```
total 42796
drwxr-xr-x 10 root root     4096 Feb  2 07:06 orientdb-community-2.2.16
-rw-r--r--  1 root root 43816497 Apr  4 18:53 orientdb-community-2.2.17.tar.gz
```

4. If I continue and run the console, it shows that I'm indeed running v2.2.16:
```
OrientDB console v.2.2.16 (build UNKNOWN@r98dbf8a2b8d43e4af09f1b12fa7ae9dfdbd23f26; 2017-02-02 07:01:26+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> 
```

**Comment by santo-it** [comment]
Hi @finid ,

Thanks for opening this issue

Where did you get that

```
wget http://mkt.orientdb.com/CE-2216-multiOS -O orientdb-community-2.2.17.tar.gz
```

The correct one is:

```
wget http://mkt.orientdb.com/CE-2217-multiOS -O orientdb-community-2.2.17.zip
```

With the command you are using you are basically downloading 2.2.16 writing it (with the -O option of wget) to a file that has name "orientdb-community-2.2.17.tar.gz" - but the file you download is the 2.2.16 (whatever name you use with the -O option)

I double checked the guide and it seems it has the correct command

```
wget http://mkt.orientdb.com/CE-2217-multiOS -O orientdb-community-2.2.17.zip
```

But perhaps somewhere it is wrong. If you me know, I'll fix it

Many thanks,

**Comment by finid** [comment]
That's my error then. Please close this, and thank you.
