### ISSUE TITLE
Listing databases on a replica member of a cluster

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#7302]
### OS: Ubuntu 16.04

**This is just a question:**

After creating a 3-node cluster (2 masters, 1 replica), all seems to work as expected. However, when I log into the replica's console, connect to the instance and `list databases`, the output only contains a new database that I created. **GratefulDeadConcerts** is missing, though I can see it under the `databases` folder.

If I perform the same action on a master node, I can see all the databases. 

So the question is, is that normal for a replica node? If not, what could be the cause?

**Comment by lvca** [comment]
If you try to execute a query on the replica server, then the database compares in the list?

**Comment by finid** [comment]
I can execute a query on the database and get the expected results, but this problem has been solved by restarting OrientDB. Now all is well. I'm operating on a RAM-starved system so that seems to be the cause of the problems I'm having.

By the way, where can one find the meaning of all the parameters that go in the `default-distributed-db-config.json` file? Not all are defined [in this guide](http://orientdb.com/docs/last/Distributed-Configuration.html).

Upgrading RAM shortly.
