### ISSUE TITLE
com.orientechnologies.orient.core.exception.OStorageException:

### ISSUE THREAD

**Issue by sathishsoundar1389** [orientechnologies/orientdb#7303]
## Expected behavior  
Run without error

## Actual behavior  
getting below exception 
com.orientechnologies.orient.core.exception.OStorageException: File with name XXXX.sbc does not exist in storage YYYYY
	DB name="YYYYY"

sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	java.lang.reflect.Constructor.newInstance(Unknown Source)
	com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:431)
	com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:382)
	com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:264)
	com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:152)
	com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2117)
	com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2112)
	com.orientechnologies.orient.client.remote.OSBTreeBonsaiRemote$3.execute(OSBTreeBonsaiRemote.java:227)
	com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:168)
	com.orientechnologies.orient.client.remote.OSBTreeBonsaiRemote.firstKey(OSBTreeBonsaiRemote.java:219)
	com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.init(OSBTreeRidBag.java:501)
	com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.<init>(OSBTreeRidBag.java:435)
	com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.rawIterator(OSBTreeRidBag.java:558)
	com.orientechnologies.orient.core.db.record.ridbag.ORidBag.rawIterator(ORidBag.java:161)
	com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:854)
	com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:782)

Note: We don't have *.sbc files in our db. Not sure from where it is reffered

## Steps to reproduce  
<add here>

**Comment by laa** [comment]
@sathishsoundar1389 do you use distributed storage ?

**Comment by sathishsoundar1389** [comment]
Yes. i am distributed system and we have made master replication using hazlecast plugin. Apart from this , there seem to be a lot of issues between multi replication environments. When not distributed everything seems to be fine. Is there a instability of orient db with respect to distributed env ?

**Comment by laa** [comment]
@sathishsoundar1389 I am part of a core team. I suppose your issue is caused by incorrect settings in distributed environment. Could you publish them?  I suppose @lvca (he is working on distributed part) will provide more information for you.

**Comment by sathishsoundar1389** [comment]
hazlecast.xml

<?xml version="1.0" encoding="UTF-8"?>


<hazelcast
		xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.3.xsd"
		xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<group>
		<name>orientdb</name>
		<password>orientdb</password>
	</group>
	<properties>
		<property name="hazelcast.phone.home.enabled">false</property>
		<property name="hazelcast.mancenter.enabled">false</property>
		<property name="hazelcast.memcache.enabled">false</property>
		<property name="hazelcast.rest.enabled">false</property>
		<property name="hazelcast.wait.seconds.before.join">5</property>
		<property name="hazelcast.operation.thread.count">1</property>
		<property name="hazelcast.operation.generic.thread.count">1</property>
		<property name="hazelcast.client.event.thread.count">1</property>
		<property name="hazelcast.event.thread.count">1</property>
		<property name="hazelcast.heartbeat.interval.seconds">5</property>
		<property name="hazelcast.max.no.heartbeat.seconds">30</property>
		<property name="hazelcast.icmp.enabled">true</property>
		<property name="hazelcast.icmp.timeout">5000</property>
		<property name="hazelcast.icmp.ttl">3</property>
		<property name="hazelcast.merge.next.run.delay.seconds">15</property>
	</properties>
	<network>
		<port auto-increment="true">2434</port>
		<join>
			<multicast enabled="false">
				<multicast-group>235.1.1.1</multicast-group>
				<multicast-port>2434</multicast-port>
			</multicast>
			<tcp-ip enabled="true">		
			<member>XXXXX:2434</member>
			<member>YYYYY:2434</member>			
			<member>ZZZZZ:2434</member>
			</tcp-ip>
		</join>
	</network>
	<executor-service>
		<pool-size>16</pool-size>
	</executor-service>
</hazelcast>



[config.zip](https://github.com/orientechnologies/orientdb/files/895788/config.zip)

**Comment by sathishsoundar1389** [comment]
i have attached two files and copy pasted contents of hazlecast.xml

**Comment by sathishsoundar1389** [comment]
Can i get some comments plz.

**Comment by sathishsoundar1389** [comment]
Can some one help us on this  or this is a existing issue with orient db. If so please let us know ,which will helpful for us to decision on enterprise edition purchase

**Comment by sathishsoundar1389** [comment]
any updates plz??
