### ISSUE TITLE
Is it possible to support "CREATE PROPERTY XXX.XXX <TYPE> [DEFAULT <XXX>]"?

### ISSUE THREAD

**Issue by HuangKBAaron** [orientechnologies/orientdb#7304]
## Expected behavior  
SQL schema supports CREATE PROPERTY with DEFAULT expression than an extra 'ALTER PROPERTY'

## Actual behavior  
Only 'ALTER PROPERTY' can set default expression

## Steps to reproduce  
n/a

**Comment by luigidellaquila** [comment]
Hi @HuangKBAaron 

It's already supported:

create property ClassName.propertyName string (default "the default value")

See the docs here: http://orientdb.com/docs/2.2.x/SQL-Create-Property.html

Thanks

Luigi

**Comment by HuangKBAaron** [comment]
@luigidellaquila 'DEFAULT' key word doesn't see in the link you provide. It looks like a bug of document.

**Comment by HuangKBAaron** [comment]
great! many thx.
