### ISSUE TITLE
Is it possible to add edge support of REQUEST_RECORD_[CREATE/UPDATE/DELETE]? 

### ISSUE THREAD

**Issue by HuangKBAaron** [orientechnologies/orientdb#7305]
## Expected behavior  
If edge was supported in REQUEST_RECORD_[CREATE/UPDATE/DELETE], it could be included to the transaction.
One could create EDGE by some thing like (python) '{"@e_from_to": {"FROM":"@v_from", "TO": "@v_to"; "a_property":"a_value"} }'.

## Actual behavior  
Right now, if need creation of edge in a transaction, all other creations have to fall back to a huge development or execution time consuming sql-like script.

## Steps to reproduce  
n/a

**Comment by tglman** [comment]
hi @HuangKBAaron,

That at protocol level will be supported in 3.0, so yes as soon as we release the 3.0 final and the python driver catch up this will be supported.

Regards

**Comment by HuangKBAaron** [comment]
@tglman , very nice!
