### ISSUE TITLE
inconsisitency when three nodes are distributed

### ISSUE THREAD

**Issue by sathishsoundar1389** [orientechnologies/orientdb#7310]
## Expected behavior  
Work fine  

## Actual behavior  
They always seems to be some kind of inconsistency when three nodes are distributed , but this does not occur with two nodes are distributed. Please let me know is this expected 

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @sathishsoundar1389 

It is not expected of course, but we need more information about this problem. What kind of inconsistencies are you having?

Thanks

Luigi

**Comment by sathishsoundar1389** [comment]
1) When ever third node connects , master data replication fails attimes
2) There seem to be error as below

m.orientechnologies.orient.core.exception.OStorageException: File with name XXXX.sbc does not exist in db name
3) Cluster health error at times
4) distributed lock at timeswhich fetching connecting b/w nodes among itself

**Comment by santo-it** [comment]
Hi @sathishsoundar1389,

Thanks for opening this issue. We released version 2.2.18 recently, please could you try to repeat the issue with this version? We have included a couple of fix in it related to distributed.

If you can repeat it, please do send us log and configuration files from all involved nodes. Please also describe the steps you performed to repeat the problem, so we can correlate this with the info in the logs.

Many thanks for your cooperation,

**Comment by lvca** [comment]
We fixed all these problems in recent 2.2.x, please use 2.2.21 or major.
