### ISSUE TITLE
`default-distributed-db-config.json` parameters

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#7311]
### OrientDB Version: 2.2.17

Documentation bug?

Where can one find the meaning of all the parameters that go in the `default-distributed-db-config.json` file? Not all are defined [in this guide](http://orientdb.com/docs/last/Distributed-Configuration.html).

**Comment by lvca** [comment]
@finid which settings you need and it's not documented?

**Comment by finid** [comment]
It's easy to guess, but the following is not in that link I gave and also not in the default file: `replicate`. I saw it on a question on Stackoverflow and somewhere else. 

Although not in that link, too, `hotAlignment` is well-documented in other parts of the official documentation. From what I've read about it, I think it should be in the the default file.

```

**Comment by lvca** [comment]
`replicate` is not a setting and `hotAlignment` was deprecated in 2.2.
