### ISSUE TITLE
UPSERT is also a feature to REQUEST_RECORD_UPDATE?

### ISSUE THREAD

**Issue by HuangKBAaron** [orientechnologies/orientdb#7326]
## Expected behavior  
without UPSERT, the solution would be always complicated. BTW, I am using pyorient. not sure it supports to update a vertex with 'UPSERT' feature.

**Comment by luigidellaquila** [comment]
Hi @HuangKBAaron 

Currently REQUEST_RECORD_UPDATE does not support UPSERT. I'm leaving this open and flagged as an enhancement, we will consider it in next releases

Thanks

Luigi

**Comment by tglman** [comment]
hi,

There is no plan to support this in short term in the binary protocol, in the same way that we don't provide a Java API to do upsert, I'll forward this issue to a late version just to keep track in case of feature development on upsert.

Regards
