### ISSUE TITLE
Console - case insensitive lead to database lost with Studio

### ISSUE THREAD

**Issue by StarCmd** [orientechnologies/orientdb#7327]
## Expected behavior  
Studio (orientDB server ?) should not be confused by using Upper or Lower case within the console.

## Actual behavior  
while working in lowercase within Console, the Studio home page update it's database list with a case sensitive name of the same database. Deleting the lower case one, also delete the upper case one.

## Steps to reproduce  

1. Studio : Create a new TEST database (uppercase)
2. Console : connect remote:localhost/test admin admin
3. Console : orientdb {db=test}> import database somedata.json
4. Check database folders : GratefulDeadConcerts, OSystem, TEST
5. Studio : dropdown databases list = TEST, test, GratefullDeadConcerts
6. Studio : select "test" then the Trashcan icon (Drop the selected database)
7. Studio : dropdown databases list = TEST, GratefullDeadConcerts
8. Check database folders : GratefulDeadConcerts, OSystem

**Comment by maggiolo00** [comment]
It's not related to studio i think it's a storage issue

Only from console

```
create database remote:localhost/TEST root root plocal
connect remote:localhost/test admin admin 
disconnect
connect remote:localhost root root     
list databases 
```
I get

```
Found 3 databases:

* test (plocal)
* TEST (plocal)
* GratefulDeadConcerts (plocal)
```

Forwarding to Storage Team

**Comment by maggiolo00** [comment]
Hi @StarCmd 
it has be fixed by this
https://github.com/orientechnologies/orientdb/issues/7358

Thanks
