### ISSUE TITLE
Could not connect to new Database 2.2.18

### ISSUE THREAD

**Issue by easy2coderep** [orientechnologies/orientdb#7332]
## Expected behavior 
The user should be able to connect to the existing Database with below options

1.  connect plocal:../databases/testsdb admin admin [ also tried with root/root]
2.   connect remote:localhost/testdb root root

## Actual behavior  
However when tried the 1st option I am getting the below error.
Connecting to database [plocal:../databases/testdb] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '../databases/webnmsdb' with mode=rw
	DB name="testdb"

Error: com.orientechnologies.orient.core.exception.OStorageException: Can not open storage it is acquired by other process
	DB name="testdb"

## Steps to reproduce  
Created new Database and then add some data.
Then try connecting the database

**Comment by maggiolo00** [comment]
hi @easy2coderep 
how did you create a database?

do you have a server running?

If you do you should connect with the 2 option

**Comment by easy2coderep** [comment]
I have created as 
orientdb> connect remote:localhost root root
Connecting to remote Server instance [remote:localhost] with user 'root'...OK
orientdb {server=remote:localhost/}> create database PLOCAL://home/sysadmin/Downloads/orientdb-community-2.2.18/databases/testdb      

Creating database [PLOCAL://home/sysadmin/Downloads/orientdb-community-2.2.18/databases/testdb] using the storage type [PLOCAL]...
Database created successfully.
Current database is: PLOCAL://home/sysadmin/Downloads/orientdb-community-2.2.18/databases/testdb

Yes, the server is running and I am able to connect with 2nd option. But not with 1st one.

**Comment by lvca** [comment]
If the server is running, it locks the database, so you can't use (1).
