### ISSUE TITLE
Studio does not preserve saved graph configuration

### ISSUE THREAD

**Issue by lorlik** [orientechnologies/orientdb#7338]
## Expected behavior  
When I configure and save settings for how a graph should be displayed I expect those settings to persist and anytime I go to the graph to use icons and node names that I configured.

## Actual behavior  
Even within the same browser session graph settings are not preserved. If I switch to Schema view and return to the graph all my settings are reset to defaults.

## Steps to reproduce  
1. Modify default settings in Graph view. 
2. Navigate to Schema view. 
3. Return to Graph view

**Comment by maggiolo00** [comment]
hi @lorlik 

did you login with `root` ?

**Comment by lorlik** [comment]
@maggiolo00 , I did login with root. Does it not save configuration for root account?

**Comment by maggiolo00** [comment]
hi @lorlik 

yes it's a known issue. see here

https://github.com/orientechnologies/orientdb-studio/issues/326

try with a database user like `admin`

**Comment by maggiolo00** [comment]
hi @lorlik 

did you try with `admin` ?

**Comment by S-Azimi** [comment]
For me, the physics On/Off is not working. I'm changing it Off but it not work and physics is still enable!!
