### ISSUE TITLE
Why is there no stress tester for windows?

### ISSUE THREAD

**Issue by lorlik** [orientechnologies/orientdb#7340]
In bin directory there's a stresstester.sh script which allows to do a stress test on the DB. Why is there no .bat equivalent to do a stress test on windows machine?

**Comment by austx** [comment]
May be it's because M$ never came up with an operating system.

**Comment by lvca** [comment]
@austx :-)
@lorlik you're right, the windows version of the script is missing. @santo-it can you work in it?

**Comment by lvca** [comment]
Duplicated of https://github.com/orientechnologies/orientdb/issues/6909.
