### ISSUE TITLE
shutdown/close do not release file locks

### ISSUE THREAD

**Issue by fommil** [orientechnologies/orientdb#7342]
## Expected behavior  

I need some way of blocking on a close / shutdown where OrientDB releases all its references to the resources. This is so that I can clean up after myself in CI.

## Actual behavior  

OrientDB holds locks on various files, meaning I can't clean them up, and therefore my disk grows and grows.

## Steps to reproduce  

Run the integration tests in https://github.com/ensime/ensime-server/pull/1747 a few times and you'll fill up your disk.

**Comment by laa** [comment]
Hi @fommil .
Which methods do you call to release files. OrientGraph#shutdwon ?

This will not work in such case. You should treat OrientGraph as a connection to the database, not as the database instance.  To release locks of files you should use com.orientechnologies.orient.core.storage.OStorage#close(boolean, boolean) method. Hope it helps.

**Comment by fommil** [comment]
how do I obtain an `OStorage` instance when all I have is an `OrientGraphFactory`?

**Comment by fommil** [comment]
we call `.close()` on this, btw. And when we finish with any `OrientBaseGraph`, we call `.shutdown()` on it.

**Comment by fommil** [comment]
aaah, would this work? `db.getDatabase.getStorage.close()`

**Comment by laa** [comment]
No this will not ))

**Comment by laa** [comment]
you need to specify arguments close(true, false)

**Comment by laa** [comment]
Did it work ?

**Comment by fommil** [comment]
yes, it did, thanks!
