### ISSUE TITLE
Exceptions on shutdown in 3.0

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#7344]
Seems like databases are closed too early before the actual storage shutdown, or shutdown is being called twice, or there are multiple uncoordinated instances. Unit tests and CI tests are affected, logs on Jenkins are spammed with `NoSuchFileException` and similar exceptions.

**Comment by taburet** [comment]
Seems like all the exceptions related to shutdown hooks are fixed now. But there are several tests with incorrect database/storage life-time management, like `OrientGraphFactoryEncryptionTest` and `OETLEdgeTransformerTest`, database/storage directories are deleted before the actual storage shutdown from the shutdown hooks. For now we can live with them, that is not critical.

@tglman AFAIU, `OrientShutdownHook` and `OrientDBEmbedded#shutdownThread` have no specific ordering now, Java doesn't provide any guarantees about ordering of shutdown hooks, they may even run concurrently. My main concern is about `OShutdownCallListenersHandler`, it calls plenty of other `OOrientShutdownListener`s which cleanup internal state. This seems dangerous to me since apparently the internals may be cleaned out before the storage shutdown, so the storage may not be able to shutdown in a correct way. WDYT?

**Comment by laa** [comment]
@taburet @tglman for that reason (absence of an order of shutdown hooks) internal implementation of shutdown hooks was created. It is single shutdown hook which calls other hooks according to their priority. Is this implementation still alive?

**Comment by tglman** [comment]
Hi,

I fixed the fact that if an "OrientDBInternal" instance is already closed it not get closed twice, and the logic is behind a synchronize, so only the first one will actually close the storages relative to that instance. for the OrientShutdownHook instances and OOrientShutdownListeners I would prefer review them with the target of refactor them to make the OrientDB context contain all peaces it needs so on close of the OrientDB context everything is cleaned and there is no left-over till shutdown.

If this refactor is to big to get it done for 3.0.x we can consider to temporarily remove the jvm shutdown hook from OrientDBInternal and register it as OShutdownHandler.

Regards

**Comment by tglman** [comment]
Hi,

I moved the shoutdown logic from the jvm listener to OShutdownHandler, this should be fixed, closing.

Regards
