### ISSUE TITLE
ALTER DATABASE DATEFORMAT not working from JAVA 

### ISSUE THREAD

**Issue by razvanjuravle** [orientechnologies/orientdb#7346]
## Expected behavior  
The date format should be chaned on db server after the Java call.

## Actual behavior  
I tried the following command from Java with both Tx and noTx and plocal in order to change the database date format:

  graph.command(new OCommandSQL("ALTER DATABASE DATEFORMAT \"dd-mm-yyyy\" "));

## Steps to reproduce  
connect with either plocal or remote and try to alter the database from java as above. It seems that the format is not changes altought if running the same alter sql from studio it works as expected.

**Comment by luigidellaquila** [comment]
Two little, but significant mistakes here:

```
graph.command(new OCommandSQL("ALTER DATABASE DATEFORMAT "dd-MM-yyyy" ")).execute();
```

1. `mm` stands for minutes, you need `MM` (uppercase)
2. `.execute()` at the end was missing, it's a very common mistake, I do it very often as well ;-)

Thanks

Luigi

**Comment by razvanjuravle** [comment]
Thanks a lot, Luigi!
