### ISSUE TITLE
Obfuscate or Encrypt Passwords with OrientDB 2.1.x

### ISSUE THREAD

**Issue by fredfortier** [orientechnologies/orientdb#7348]
## Expected behavior  
I'd like the passwords in the <users> element of the orientdb-server-config.xml to be obfuscated (ideally encrypted). The 2.1 documentation: http://orientdb.com/docs/2.1.x/Server-Security.html shows this example:
`    <users>
        <user name="root" password="{SHA-256}55F95B91628EF3E679628ACB23AE" resources="*" />
        <user name="guest" password="guest" resources="connect,server.listDatabases,server.dblist" />
    </users>`
 
What confuses me is this note: "Beginning with version 2.2, OrientDB hashes the passwords using PBKDF2WithHmacSHA256 algorithm if it's running on Java 8 or major, otherwise PBKDF2WithHmacSHA1 with a configurable SALT." Does this mean that passwords can only be obfuscated starting at version 2.2, or did you just add a new hashing algorithm? If the latter, in the example above, do I simply replace {SHA-256} by {SHA-1}? Or can I use {SHA-256} too? Is there way to actually encrypt the password (as opposed to just a hash)?

## Actual behavior  
Passwords are in the clear.

**Comment by fredfortier** [comment]
I've answered my own question. I am able to obfuscate the password at least with SHA-1 which is good enough for me at the moment.

**Comment by smolinari** [comment]
If you follow these steps, you can also reset the password and it should be encrypted.

**Restoring the Server's User root**

- Open the config/orientdb-server-config.xml file and remove the "root" user entry
- Remove the tag <isAfterFirstTime>true</isAfterFirstTime> at the end of the file
- On next restart of the server, a new root password is asked again

Scott

**Comment by fredfortier** [comment]
I spoke too fast. Somehow, my application was still able to connect to the database after changing the password. However, I am not able to connect to the Studio app.

In my orientdb-server-config.xml file, I replaced this entry:
`<user resources="*" password="admin" name="admin"/>`
By:
`<user resources="*" password="{SHA-1}d033e22ae348aeb5660fc2140aec35850c4da997" name="admin"/>`

Since the password is the same, I'd expect Studio to continue to authorize the admin / admin user. However, it no longer does.

**Comment by fredfortier** [comment]
@smolinari the OrientDB server is embedded into a web application, so I do not have the ability to answer prompts, at least not easily. Ideally, I'm looking for the ability to generate the SHA-1 or SHA-256 hash myself, then paste them in the <users> tag. I've generated the SHA-1 hash above using this: www.sha1-online.com. Please let me know if I am just fundamentally misunderstanding something or refer me to documentation as appropriate.

**Comment by smolinari** [comment]
There are two admin users. The super admin, which is the password in the config to gain access to the server itself and then the admin user for the database administration. To change the database admin password from "admin", you have to change the user in the OUser class like this:

update OUser set password = 'some-new-password' where name = 'admin'

Scott

**Comment by fredfortier** [comment]
Ok thanks. Is there any good way to restore the root password (to a new encrypted password) without answering a prompt at startup?

**Comment by smolinari** [comment]
I believe you can create a SHA256 hash and insert it into the `orient-server-config.xml` file like so:

<user resources="*" password="{SHA256}9F86D081884C7D659A2FEAA0C55AD015A3BF4F1B2B0B822CD15D6C15B0F00A08" name="root"/>

No guarantee it will work though. Let me know, if it does. I'd try it out myself, but I am using the Docker container version and it doesn't have a text editor. I could probably sed it in, but I'm too lazy to figure out the right command. LOL!

Scott

**Comment by fredfortier** [comment]
It does not work for me. I found this issue which seems to be a duplicate: https://github.com/orientechnologies/orientdb/issues/5078, which seems to acknowledge the issue and recommend upgrading to 2.2. Is this not working in 2.1?

My root password is "password". I created a SHA-256 hash. I used the OrientDB helper function to generate the hash just in case there is something unusual about it.
`<user resources="*" password="{SHA-256}5E884898DA28047151D0E56F8DC6292773603D0D6AABBDD62A11EF721D1542D8" name="root"/>`
When I switch the value back to "password", it starts working again.

**Comment by smolinari** [comment]
I believe the ability to control the hash type (i.e. with {SHA-256}) was added in 2.2. Sorry, I didn't realize you were using 2.1. No chance of upgrading?

Scott

**Comment by smolinari** [comment]
If you can also use the console, you have this available: 

http://orientdb.com/docs/last/Console-Command-Set-Server-User.html
http://orientdb.com/docs/last/Console-Command-Drop-Server-User.html
http://orientdb.com/docs/last/Console-Command-List-Server-Users.html

Scott

**Comment by fredfortier** [comment]
I had some problems upgrading to 2.2 so I aborted the project for the time being. I plan to revisit this but obfuscating the password is an immediate issue. Can you confirm that it is not possible to obfuscate passwords with 2.1?

**Comment by smolinari** [comment]
I'm about 90% sure changing the password can only be done with the deletion, then restarting the server in Version 2.1.X. All other features came in 2.2.

Scott

**Comment by fredfortier** [comment]
Ok thanks. Just to be completely sure, my immediate need to change the root password but to encrypt it. The problem which I am trying to solve is having clear text passwords in orient-server-config.xml. Can you confirm that password encryption cannot be done in 2.1 (even through the deletion method)?

**Comment by smolinari** [comment]
I think @luigidellaquila can probably better ensure when root user password encryption was possible. Hopefully he can chime in.

Scott

**Comment by luigidellaquila** [comment]
Thank you for the pointer @smolinari 

Let me assign it to @SDIPro for a check

Thanks!

Luigi
