### ISSUE TITLE
Calling functions in another database

### ISSUE THREAD

**Issue by danciui** [orientechnologies/orientdb#7350]
###OrientDB Version: 
orientdb-community-2.2.17

###Java Version: 
Java 8 Update 91

###OS version
OS: Mac Os Sierra 10.12.3

## Expected behavior  
More of an enhancement: I would like to have a FunctionLibrary database that contains a bunch of functions. Then in database1 i would call FunctionLibrary.myFunction() and it would work. This functionality is present in most big transactional database systems. 

## Actual behavior  
Currently it doesn't appear that I can call functions across databases.

**Comment by luigidellaquila** [comment]
Hi @danciui 

I see it quite hard to implement out of the box. There is a proposal for cross-database queries, that probably will also cover this case, but it's not in the roadmap for next release.

Anyway, I'll mark this as an enhancement

Thanks

Luigi

**Comment by smolinari** [comment]
👍 for me on this idea! 😄 

Scott
