### ISSUE TITLE
HA SYNC DATABASE needs 2 more params

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#7355]
I'd like having in the SQL syntax these 2 options:

`HA SYNC DATABASE [-force] [-full]`

- `-force` to force a sync even if current database is newer
- `-full` to execute a full backup, no matter if delta backup is possible

**Comment by luigidellaquila** [comment]
Done in 2.2.x. Porting now on 3.0

**Comment by luigidellaquila** [comment]
Ported to 3.0 as well. Closing

Thanks

Luigi
