### ISSUE TITLE
Defining COLLATE throw OCommandSQLParsingException

### ISSUE THREAD

**Issue by Solido** [orientechnologies/orientdb#7357]
## Expected behavior  
Add a STRING PROPERTY and define CI or CS like in 2.2  
CREATE PROPERTY `Entity`.`name` STRING (MANDATORY TRUE, COLLATE CI, NOTNULL)

## Actual behavior  
All COLLATE break the execution with :
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Invalid attribute definition: ' COLLATE CI'

idem for COLLATE 'ci' with quotes -> Invalid attribute definition: ' COLLATE 'CI''

I guess that CS doesn't exist anymore and than CI is not recognized.
 
## Steps to reproduce  
console.sh yourscript.osql

**Comment by luigidellaquila** [comment]
Hi @Solido 

Thanks for reporting, I'll fix it asap

Luigi

**Comment by Solido** [comment]
Thx @luigidellaquila 

This is blocking for further ODB 3 integration tests

Regards

**Comment by luigidellaquila** [comment]
Working on it now

**Comment by luigidellaquila** [comment]
Hi @Solido 

The correct syntax is with quotes:
```
CREATE PROPERTY Entity.name STRING (MANDATORY TRUE, COLLATE "ci", NOTNULL)
```

but I couldn't manage to reproduce a OCommandSQLParsingException. Do you have any hint on how to do it?

I also verified that with the new SQL executor the collate does not work correctly (ie. it just works as if there were no collate), I'm working to fix it

Thanks

Luigi

**Comment by Solido** [comment]
I've tried other entries 
CREATE PROPERTY `Person`.`firstname` STRING (MANDATORY TRUE, COLLATE "ci", NOTNULL)
with double quote but still get 

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Invalid attribute definition: ' COLLATE "CI"'

Those are copy / paste of my code and error if it help

**Comment by luigidellaquila** [comment]
Hi @Solido 

I downloaded a fresh 3.0 M1 from the website, created a script as follows (createprop.osql):


```
create database memory:test root root memory;
Create class Person
CREATE PROPERTY Person.firstname STRING (MANDATORY TRUE, COLLATE "ci", NOTNULL);
```
And launched it as follow:

```
MacBook-Pro-4:bin luigidellaquila$ ./console.sh ~/temp/createprop.osql 

OrientDB console v.3.0.0m1 (build 63b896d280caa08f511517a6e35978d214ffea47) https://www.orientdb.com
Type 'help' to display all the supported commands.
Creating database [memory:test] using the storage type [memory]...
Database created successfully.

Current database is: memory:test
Class created successfully.

Property created successfully.
```
 
Am I missing something?

Thanks

Luigi

**Comment by Solido** [comment]
Hi @luigidellaquila 

Sorry for the delay, needed some times to goes back to 3.0.

I got some more news, I found the mistake and it's completely my fault. 
Launching V3 script from the 2.2 script path so the error.

Good news is that I can move forward to the migration test.

Problem is my script is several hundred lines and when it fails I've no idea of the line.
It was the case with 'CI' and now I've

`Impossible to create an index without specify the key type or the associated property`

Can I suggest to have a more explicit log else it can be very difficult to migrate since SQL is know much more strict.

I'm really sorry for your time of this false case.

**Comment by luigidellaquila** [comment]
Hi @Solido 

Absolutely no problem, I just pushed a fix to add some additional info to that error message, at least it will help you to indentify the wrong queries

I'm closing this issue, please feel free to reopen if needed

Thanks

Luigi
