### ISSUE TITLE
Match issue

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7361]
## Expected behavior  
Get the query result quickly!  

## Actual behavior  
Get the query result so slowly.

## Steps to reproduce  
1.  The SQL as follows:
 select m.memberId,phone.phone,phoneMark.mark,count(1) from 
(MATCH {class: member,as: m, where: (memberId = 1370237)}.out('HasPhone'){as: phone}.both("CallTo"){as: result}.out('HasPhoneMark'){class: PhoneMark,as:phoneMark} 
RETURN m,phone,result,phoneMark) group by phone.phone,phoneMark.mark
2. When memberId exists, the below sql is very quick!
2. However when memberId does not exist and the memberId >= max(memberId), the sql is very slow!

**Comment by KishoDai** [comment]
If changed the sql to below , the sql is also very quick, I think the issue is related to parse match statement.
(MATCH {class: member,as: m, where: (memberId = 1370237)}.out('HasPhone'){as: phone}.both("CallTo"){as: result}.out('HasPhoneMark'){as:phoneMark}

**Comment by luigidellaquila** [comment]
Hi @KishoDai 

do you have a dataset to reproduce the problem?

Thanks

Luigi

**Comment by KishoDai** [comment]
Yes, I have a huge dataset which is our real data.

**Comment by KishoDai** [comment]
Hi Luigi, 
      Added more. 
      The count of Member(V) is about 1,500,000.
      The count of Phone(V) is about 40,000,000.
      The count of PhoneMark(V) is about 16.
      The count of HasPhone(E) is about 1,200,000.
      The count of CallTo(E) is about 60,000,000.
      The count of HasPhoneMark(E) is about 2,000,000.

Thanks
Kisho

**Comment by KishoDai** [comment]
Hi Luigi,
    One more clue.
    When executed the below SQL, the console gives the tip: "2017-04-25 09:25:31:627 INFO  [TIP] Query 'SELECT FROM ApplyInfo' returned a result set with more than 10000 records. Check if you really need all these records, or reduce the resultset by using a LIMIT to improve both performance and used RAM [OEnterpriseProfiler]"
    select m.memberId,phone.phone count(1) from (MATCH {class: member,as: m, where: (memberId = 1370237111)}.out('HasPhone'){as: phone}.both("CallTo"){as: result}.out('HasApply'){class: ApplyInfo,as:applyInfo}  RETURN m,phone,result) group by phone.phone

    Looks like it starts from ApplyInfo which have more than 400,000 data.
Thanks
Kisho

**Comment by NicholasQu** [comment]
Clarify more things here: ( I'm in the same team with KishoDai )

1. OrientDB seems to handle the MATCH statement at the point of "`estimateRootEntries()`" in a wrong way. 
Just as above example, if the first {} block with a non-existent where condition, which returns null transparently, the estimation will choose the last {} block as the root entry, which contains millions of records,  then the warning of "`returned a result set with more than 10000 records...`" came out, as a result this match will run a very long time.

2. If I removed the "class:" declaration in the last {} block, the estimation couldn't infer the exact Class of last Vertex, then the sql will be executed successfully with null result in a very short time.

`However, I can't confirm it will work always, if the edge have strict in/out LINK class definition, will the estimation infer the exact class and still choose the last {} block as root entry?`

3. Another try to avoid long running besides above 2nd point, is splitting the statement with `comma`， seems the estimation will choose the first {} block `sometimes`, this may not work in most cases. I've not found out the basic logic.

> MATCH {class: member,as: m, where: (memberId = `12345689 not exist id`)}.out('HasPhone'){as: phone}.both("CallTo"){as: result}.out('HasPhoneMark'){class: PhoneMark,as:phoneMark}
RETURN m,phone,result,phoneMark

CHANGE TO
> MATCH 
{class: member,as: m, where: (memberId = `12345689 not exist id`)},
{as:m}.out('HasPhone'){as: phone},
{as:phone}.both("CallTo"){as: result},
{as:result}.out('HasPhoneMark'){class: PhoneMark,as:phoneMark}
RETURN m,phone,result,phoneMark

This change ever worked,  but it was stucked while I tried just now.

**Comment by luigidellaquila** [comment]
Hi @NicholasQu 

Thank you very much for the detailed explanation.

1 and 2 make a lot of sense, probably the problem is only on the index estimation. I'll start from that to find a fix. Your work-around should cover 100% of the cases, so I'd say it's safe to use it.

3 is not a deterministic option, because the order the pattern is evaluated may changed based on JVM implementation (random order of elements in Set instances at the low level)

Thanks

Luigi

**Comment by jpstrikesback** [comment]
Any further work here? We were wondering why MATCH was taking super long on empty result sets and implemented the workaround in #2 above with success.

**Comment by luigidellaquila** [comment]
Hi @jpstrikesback 

For now I have no news about this, sorry, but I'll keep you updated as soon as something changes

Thanks

Luigi
