### ISSUE TITLE
SQL REMOVE of a field fails when followed by additional SQL synatx

### ISSUE THREAD

**Issue by SafwanHak** [orientechnologies/orientdb#7362]
## Actual behavior  
Database error that syntax is invalid.

## Steps to reproduce  
Found a bug as we translate our mongo code to Orient.  Look at fieldX, it's just a field that we want to remove, not an array.. if it's the last instruction in SQL before the WHERE it works, if it's followed by any other SQL syntax it'll fail. 

this query will work 
update Test ADD names="abc" SET AGE=1 remove names = "blah4", fieldX where @rid=#29:7

this query will break because fieldX is followed by an additional SQL syntax
update Test ADD names="abc" remove names = "blah4", fieldX SET AGE=1 where @rid=#29:7

**Comment by luigidellaquila** [comment]
Hi @SafwanHak 

This could be a parsing problem, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @SafwanHak 

I just pushed a fix on 2.2.x branch. The fix will be released in next few days with 2.2.19

Thanks

Luigi
