### ISSUE TITLE
Error in studio while editing embedded map of an edge

### ISSUE THREAD

**Issue by Solido** [orientechnologies/orientdb#7365]
## Expected behavior  
Edit and Save an **Edge** property in Studio should not raise an error.

## Actual behavior  
When saving the modification of an embedded property in studio an error pop with
OConcurrentModification ... because the version is not the latest ...

Value is updated on save but red flag is raised

## Steps to reproduce  
Edit an embedded map of an **edge**, not a Vertex in studio then save.

**Comment by maggiolo00** [comment]
hi @Solido 

do you edit the edge from the Graph Editor in the Edit Edge popup?

**Comment by maggiolo00** [comment]
Hi @Solido 

i was not able to reproduce it with 2.2.18. 
How can i reproduce it?

**Comment by Solido** [comment]
Got it every time.
Try to create and edge with an empty embedded map while editing the input is 
{

}

Add any entry and save, exception is throw

**Comment by maggiolo00** [comment]
hi @Solido 

which version of OrientDB 2.2.18?

Do you have in create or in update this error?

In Graph Editor ?

**Comment by Solido** [comment]
Well as is the description of the bug. 2.2.18 editing an edge that contains Embedded Map, edit the input text field. It can be empty or with previous data. Adding a key or modify, save -> red. Happen every time even after I rebuild the DB.

**Comment by Shanery** [comment]
I'm getting the same error but on editing a vertex.

It happens on the default editor (not graph). When you click on a rid (eg. #21:0) and start editing, saving an embedded creates this error.
