### ISSUE TITLE
plocal: Connections with read-only access [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#737]
This is [Issue 737](http://code.google.com/p/orient/issues/detail?id=737) moved from a Google Code project.
Added by 2012-03-04T17:12:23.000Z by [jli...@gmail.com](http://code.google.com/u/112408971689577117545/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v2.0
### Original description

```
Provide the option to create read-only access for security and potential performance improvement in read-only mode. This may also provide the capability of concurrent access (one rw, others read-only) to local embedded databases.
```

**Comment by j3st3rDev** [comment]
Is there some news on that? 
"This may also provide the capability of concurrent access (one rw, others read-only) to local embedded databases."
This feature would be great, I'd love to do something like this. I this could solve a lot of problems in my architecture.

**Comment by rohrl** [comment]
+1

**Comment by lvca** [comment]
Not relevant anymore, closing.
