### ISSUE TITLE
OrientDB3.0.0m1 Graph UI rendering issue

### ISSUE THREAD

**Issue by NicholasQu** [orientechnologies/orientdb#7372]
## Expected behavior  
I installed 3.0.0m1 via docker images from hub.docker.io, then start docker, from the studio front page, import existing `GamesOfThrones` and logged in.

In the Graph tab page, one simple search like "select * from Event", the graph ui is not rendered.
From the browser debug console, the js error throws out.

Is the cloud databases are out of date and incompatible with 3.0.0? Or something else?

> main.js:165528 TypeError: Cannot read property 'data' of undefined
>     at main.js:191560
>     at processQueue (main.js:168024)
>     at main.js:168040
>     at Scope.$eval (main.js:169331)
>     at Scope.$digest (main.js:169145)
>     at Scope.$apply (main.js:169439)
>     at done (main.js:163420)
>     at completeRequest (main.js:163629)
>     at XMLHttpRequest.requestLoaded (main.js:163557)
>     at XMLHttpRequest.wrapFn [as _onload] (main.js:247150)
>     at ZoneDelegate.invokeTask (main.js:246561)
>     at Object.onInvokeTask (main.js:50584)
>     at ZoneDelegate.invokeTask (main.js:246560)
>     at Zone.runTask (main.js:246450)
>     at XMLHttpRequest.ZoneTask.invoke (main.js:246631)
> 
> TypeError: Cannot read property '0' of undefined
>     at Object.push (main.js:197196)
>     at main.js:191571
>     at processQueue (main.js:168024)
>     at main.js:168040
>     at Scope.$eval (main.js:169331)
>     at Scope.$digest (main.js:169145)
>     at Scope.$apply (main.js:169439)
>     at done (main.js:163420)
>     at completeRequest (main.js:163629)
>     at XMLHttpRequest.requestLoaded (main.js:163557)
>     at XMLHttpRequest.wrapFn [as _onload] (main.js:247150)
>     at ZoneDelegate.invokeTask (main.js:246561)
>     at Object.onInvokeTask (main.js:50584)
>     at ZoneDelegate.invokeTask (main.js:246560)
>     at Zone.runTask (main.js:246450)
> 
>

**Comment by maggiolo00** [comment]
Hi @NicholasQu 

thanks for your feedback. Let me check

**Comment by karolmie1** [comment]
This might be the same problem (same error): https://github.com/orientechnologies/orientdb/issues/7297

**Comment by NicholasQu** [comment]
I can't check the similarity with @karolmie1 mentioned, if they are same, someone can help to close it.
