### ISSUE TITLE
question about EdgeProp using oetl.sh and json

### ISSUE THREAD

**Issue by danciui** [orientechnologies/orientdb#7374]
OrientDB Version: 
orientdb-community-2.2.18

Java Version: Java 8 Update 91
OS: Mac Os Sierra 10.12.3

Expected behavior
Being able to add properties on edges via json etl. 

Actual behavior
I'm using oetl.sh with JSON to load data on an OrientDB remote server. I currently have to add the properties on all the edges. In this example I would like edge @rid = #25:0 to have two properties "name"= "Built" and "kind"="RedEdge".  edge @rid= #26:0 also has to have two properties "name" = "Built" and "kind"="BlueEdge".  I can't find any documentation on how to do this via the son etl, so I am putting all the properties on all the edges in a dictionary. This is very cumbersome. 
![p1](https://cloud.githubusercontent.com/assets/15330145/25485830/e0e41b6e-2b24-11e7-9e0a-46e4906ae4da.png)

[Archive 5.zip](https://github.com/orientechnologies/orientdb/files/960227/Archive.5.zip)

**Comment by robfrank** [comment]
can you share the ETL configuration file and a sample of your dataset?
Did you check the doc section about transformers? http://orientdb.com/docs/last/Transformer.html

**Comment by danciui** [comment]
I shared both the configuration and the dataset in Archive 5 above. There is minimal documentation about how to use the edgefields
