### ISSUE TITLE
Trouble with order of params in graph.getVertices when using index

### ISSUE THREAD

**Issue by karolmie1** [orientechnologies/orientdb#7375]
## Expected behavior  

I perform a query for Tasks. Task is created as:

```
CREATE CLASS Task extends V
CREATE PROPERTY Task.projectId STRING (MANDATORY TRUE, NOTNULL, MAX 20)
CREATE PROPERTY Task.seq SHORT ( MANDATORY TRUE, NOTNULL, MIN 0)

CREATE INDEX TaskPK ON Task (projectId, seq) UNIQUE
```

I performed a query in "wrong" (not index) order (yeah, I don't intend for it to stay this way)

`graph.getVertices(Task.CLASS, arrayOf(Task.SEQ, Task.PROJECT_ID), arrayOf(taskId.seq, taskId.projectId))`

OrientDb decides to use index here anyway. That would not be a problem, except that the order or keys is switched. This causes orientdb to try to cast taskId to String, and projectId to Short. That obviously causes the error.

Querry works perfectly after changing the order of parameters.
`graph.getVertices(Task.CLASS, arrayOf(Task.SEQ, Task.PROJECT_ID), arrayOf(taskId.projectId, taskId.seq))`

In my original code, I will switch the order of Ikeys to correspond to Index, so that is not a problem for me in the slightest. I just wanted to share with you this oddity.

This would be bad if both of my parameters were of type string - then It would cause strange querry results, and would make the problem hard to pinpoint. I would better have an exception instead of this weird result.

Problem is here:
 
```
      Set<OIndex<?>> indexes = clazz.getInvolvedIndexes(Arrays.asList(iKey)); //finds index correctly
      Iterator<OIndex<?>> iterator = indexes.iterator();  // iterate over it randomly, not caring about order of parameters
      while (iterator.hasNext()) {
...
          List<Object> keys = Arrays.asList(convertKeys(idx, iValue)); //and cast (the place that originally have thrown the error)
...

```

## Steps to reproduce  
I will branch out my project if anyone finds this worth investigating.

**Comment by luigidellaquila** [comment]
Hi @karolmie1 

Thank you very much for reporting, I just pushed a fix for this on branch 2.2.x

Thanks

Luigi
