### ISSUE TITLE
Can't save CSV from studio 

### ISSUE THREAD

**Issue by william76** [orientechnologies/orientdb#7376]
## Expected behavior  
I'd like to save output from a query into a CSV file.  I changed the "Content Type" in the pulldown to "CSV" in Studio to run a query hopeful that it will save the output to a CSV file... 

## Actual behavior  
I get an error message on the bottom of the screen that indicates "The command has not been executed".  I don't see any useful messages in the console log of the server.

![screen shot 2017-04-27 at 11 05 28 am](https://cloud.githubusercontent.com/assets/263654/25495414/3d45034a-2b3a-11e7-9aff-5b993d2be79c.png)

## Steps to reproduce  
Create a simple database.
Click the wrench icon next to the "Explain" button on the Browse tab. 
Change Content Type to CSV
Execute a query, such as SELECT FROM V
Observer error message.

**Comment by maggiolo00** [comment]
Hi @william76 

thanks for reporting this issue. Let me check

**Comment by maggiolo00** [comment]
Hi @william76 

i've provided a fix. It will be available in 2.2.20

Thanks

**Comment by william76** [comment]
Thank you very much!
