### ISSUE TITLE
Property default boolean value

### ISSUE THREAD

**Issue by Solido** [orientechnologies/orientdb#7377]
## Expected behavior  
Can create a default boolean property with default value to TRUE

## Actual behavior  
Engine accept all default value, boolean, with quote, force mandatory but none of them set a default value

<img width="674" alt="screen shot 2017-04-28 at 02 10 45" src="https://cloud.githubusercontent.com/assets/1295961/25509304/3299ae5e-2bb8-11e7-8a66-31ca6edbf55e.png">

Since I asked for a NOTNULL I check and get this result. Notice there's not DEFAULT VALUE

<img width="1254" alt="screen shot 2017-04-28 at 02 12 06" src="https://cloud.githubusercontent.com/assets/1295961/25509303/329852b6-2bb8-11e7-92b5-8bd478cc2a7d.png">

More Fun, I create 04 which is MANDATORY hence the star near the field name but it can be NULL and I get a GREEN ... which is not working. Opposite to previous bug I posted where I get a Red with update done. Is this a Browser Cache problem ?

<img width="1173" alt="screen shot 2017-04-28 at 02 17 14" src="https://cloud.githubusercontent.com/assets/1295961/25509449/6b0775f4-2bb9-11e7-88ac-a3a6d3753c1a.png">

I did not experience such difficulties with previous version and I'm not sure what is wrong and where.

Can you provide me a default SQL command to set a DEFAULT to TRUE ? notice I'm using default with Sysdate() and it works.

**Comment by maggiolo00** [comment]
Hi @Solido 

did you insert record with Studio or SQL?

**Comment by Solido** [comment]
For the screenshot it was using Studio but data are inserted using Graph Api. Point is that I can get default date not Boolean. Can you confirm this behavior ?

**Comment by maggiolo00** [comment]
Hi @Solido 


In Studio the problem is in the UI that set the field to `null`.

In Graph API i did this test and works well

```java
@Test
  public void testDefaultValueBoolean() {
    OrientGraph graph = new OrientGraph("memory:testDefaultValue");
    try {
      graph.executeOutsideTx(iGraph -> {
        OrientVertexType foo = iGraph.createVertexType("Foo");
        foo.createProperty("boolean", OType.BOOLEAN).setDefaultValue("true");
        return null;
      });
      
      OrientVertex vertex = graph.addVertex("class:Foo");

      graph.commit();

      Assert.assertEquals(true, vertex.getProperty("boolean"));

    } finally {
      graph.drop();
    }
  }
```

Do you have a test to reproduce it with Graph API?

Thanks

**Comment by Solido** [comment]
Thx @maggiolo00 .I do not create the schema using the graph API, I insert data using it.
Schema is created using an .osql script the same that I quoted on the first post. I'll trying again without using the UI.

**Comment by maggiolo00** [comment]
@Solido 
let me know

**Comment by igasparetto** [comment]
I have a similar issue here.

In V2.x, when running a SELECT FROM MyVertex, a BOOLEAN attribute would be returned FALSE if it is not set to TRUE, even if I didn't specifically set the attribute to FALSE and the attribute doesn't have a default value.

IMHO, a BOOLEAN IS FALSE unless it is set to TRUE!

Luckily, we have great class inheritance structure and we could run a single query to fix all vertices and edges.

**Comment by igasparetto** [comment]
These are the queries we run here for the attribute "deleted"

```
ALTER PROPERTY MySuperClass.deleted DEFAULT FALSE
UPDATE MySuperClass SET deleted = false WHERE deleted != true
```

**Comment by igasparetto** [comment]
Please see video:
https://youtu.be/Jkhny3myKhY
