### ISSUE TITLE
[Question] About #Clusters# modelling 

### ISSUE THREAD

**Issue by NicholasQu** [orientechnologies/orientdb#7378]
I‘m always cautious of how to setup clusters in the better way, while I saw the statement in the official document in chapter "[Clusters](http://orientdb.com/docs/last/Clusters.html)" , more confusions come to me。

> Use the cluster "Today" to group all the records created today.

This scenario basically faces to hot-spot data, I surely can fill today's hot data into `Today ` cluster, but tomorrow how should I remove the out-of-date records out of `Today` cluster, and fill in tomorrow's latest records? It should not be an easy job.

I don't think orientdb has a good performance in the delete and update operations, anyone has the best practice in this case?

Thanks for discussion.

**Comment by lvca** [comment]
@NicholasQu you could have a cluster per day, like "2017-04-29" and fill it with your data. Dropping a cluster is a super fast operation when you don't have indexes on it.

**Comment by NicholasQu** [comment]
@lvca As you said, dropping a cluster really is fast, but if I need to move those data in this cluster to backup in another historical cluster, how should I do to be fast?

**Comment by lvca** [comment]
Why do you need to move data between clusters? Can you have multiple clusters per class>

**Comment by NicholasQu** [comment]
I just deleted last comments, just got your point, your answer is replacing "Today" with a specific date like '2017-04-29', then need not to move data. It's clear for now , thanks.

**Comment by lvca** [comment]
Cool, happy coding with OrientDB.
