### ISSUE TITLE
Prepared statement - keyword as parameter name - parse failure

### ISSUE THREAD

**Issue by karolmie1** [orientechnologies/orientdb#7379]
### OrientDB Version: 2.2.18

While performing this query i receive parsing exception:
`val query = "SELECT FROM X WHERE date > :from AND date < :to"`

On the other hand this one is perfectly fine
`val query = "SELECT FROM X WHERE date > :frm AND date < :to"`

That means I cannot use keywords as parameter names in prepared statements, though ":" in front of parameter name should remove ambiguity from grammar.

Don't know if you consider this a bug or not. Feel free to close.

Parsing code looks pretty low-level, so I gave up investigating further.

**Comment by luigidellaquila** [comment]
Hi @karolmie1 

It's a known limitation, but I think I can patch it.
I'll give you a feedback soon

Thanks

Luigi

**Comment by karolmie1** [comment]
No need to make it top priority :) If it is known then it's good for me.

Sorry if I've created a duplicate, I try my best to find existing issue first.

**Comment by luigidellaquila** [comment]
Hi @karolmie1 

I pushed a little fix to support specifically `:from`. To support other keywords they have to be mapped one by one. I'll do it in next releases, in the meantime I'm closing this

Thanks for reporting!

Luigi
