### ISSUE TITLE
how to convert hex string to decimal representation?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7380]
### OrientDB Version: 2.2.18 

Say that we have a string like '10', which is a hex representation of the decimal value 16

What function/method exists to get such a conversion from a hex string to a decimal value, such as

SELECT '10'.Hex_to_Int()

-> expected to return 16

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I'm afraid there is no such function right now, but it's not hard to do.
Let me flag it as an enhancement, I'll try to add it asas.

In the meantime, you can define a custom js function for this

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Little update here, there is no such function yet, but in v 3.0 you can just represent numbers in hex notation:

```
SELECT 0x10
```
