### ISSUE TITLE
Error querying linklist RIDs after commit

### ISSUE THREAD

**Issue by cvm1ll3** [orientechnologies/orientdb#7383]
## Expected behavior  
```
[
    {
        "@type": "d",
        "@rid": "#-2:0",
        "@version": 0,
        "rid": "#129:44",
        "birthday": "1985-01-01 00:00:00",
        "firstName": "Christopher",
        "gender": "M",
        "prefix": "Mr.",
        "phonesRID": [
            #148:0,
            #148:1
        ],
       ...
    }
]
```
## Actual behavior  
```
[
    {
        "@type": "d",
        "@rid": "#-2:0",
        "@version": 0,
        "rid": "#129:44",
        "birthday": "1985-01-01 00:00:00",
        "firstName": "Christopher",
        "gender": "M",
        "prefix": "Mr.",
        "phonesRID": [
            null,
            null
        ],
       ...
    }
]
```

## Steps to reproduce  
Created a vertex in Contacts Class with property phones type linklist
After querying vertex, all linklist property rids are null

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

Could you please post a specific code snippet and some additional details?
Are you in a single tx? Are you creating all the vertices/documents in the same tx?

Thanks

Luigi

**Comment by cvm1ll3** [comment]
H

**Comment by cvm1ll3** [comment]
Hi @luigidellaquila 

Yes all vertices were created in a single tx:

CREATE CONTACT FUNCTION:
<code>
/* create contact vertex */
passJSON = {};
passJSON.class   = "Contacts";
passJSON.cluster = "CLUSTER Contacts_DIVISION" +newContactJSON.division;
passJSON.content = contactJSON;
newContact       = MISC_createVertex(passJSON);

/* create phone vertex */
passJSON = {};
passJSON.class   = "Phones";
passJSON.cluster = "CLUSTER Phones_DIVISION" +json.division;
passJSON.content = phonesJSON;
newProperty = MISC_createVertex(passJSON);

/* add phone rid to contact vertex phone linklist property */
passJSON = {};
passJSON.parentRID = newContact.id;
passJSON.property  = "phones";
passJSON.linkRID   = newProperty.id;
MISC_addToLinklist(passJSON);

gdb.commit();

/* call query contact info */
execSQL = "SELECT @rid," + contacts + ", " +
                   "phones.include(" + phones + "), " +
                   "FROM CLUSTER:Contacts_DIVISION".concat(json.division)) + " WHERE @rid = ?";
query = gdb.command("sql", execSQL, [newContact.id]);

return query;
</code>

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

What is MISC_createVertex? Is it another custom function? Could you post that code as well?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Thank you, I'm trying it, I'll let you know soon

Luigi

**Comment by luigidellaquila** [comment]
Just last question: how are you invoking the original function? From SQL or from a REST service?

Thanks

Luigi

**Comment by cvm1ll3** [comment]
Right now I'm just testing directly on the original function in studio, the older version I'm using before I invoke it from studio and REST. 

Thanks so much @luigidellaquila

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

In the end I managed to reproduce the problem and provide a fix.
I just pushed it on branch 2.2.x, it will be released with next 2.2.20

Thanks for your help!

Luigi

**Comment by cvm1ll3** [comment]
@luigidellaquila Thank you so much!

**Comment by cvm1ll3** [comment]
@luigidellaquila I found this same error in 2.2.29s and tried it again on 2.2.30 although this time, the linklists are working properly, its not working for link, its just giving me a temporary RID. Please see example result below, field externalAccountingRID is type link: 

Expected Result:

<code>
{
        "@type": "d",
        "@version": 0,
        "rid": "#131:17",
        "externalAccountingRID": "#142:10",
        "metadata": {
            "@type": "d",
            "@version": 0,
            "@class": "Log",
            "createdBy": "camille@studiosuite.com",
            "createdDateTime": "2017-11-20 20:30:06",
            "modifiedBy": null,
            "modifiedDateTime": null,
            "@fieldTypes": "createdDateTime=t"
        },
        "notes": "Contractors notes",
        "description": "Contractors desc",
        "isDefault": false,
        "sortNumber": "5",
        "name": "Contractors14",
        "parentCategory": "People",
        "parentCategoryRID": "#131:2"
}
</code>

Actual Result:

Expected Result:

<code>
{
        "@type": "d",
        "@version": 0,
        "rid": "#131:17",
        "externalAccountingRID": "#142:-10",
        "metadata": {
            "@type": "d",
            "@version": 0,
            "@class": "Log",
            "createdBy": "camille@studiosuite.com",
            "createdDateTime": "2017-11-20 20:30:06",
            "modifiedBy": null,
            "modifiedDateTime": null,
            "@fieldTypes": "createdDateTime=t"
        },
        "notes": "Contractors notes",
        "description": "Contractors desc",
        "isDefault": false,
        "sortNumber": "5",
        "name": "Contractors14",
        "parentCategory": "People",
        "parentCategoryRID": "#131:2"
}
</code>

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

Let me re-open it, I'll check it asap

Thanks

Luigi

**Comment by cvm1ll3** [comment]
@luigidellaquila Thank you so much!

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

Any chance to have a test case to reproduce the problem?
My specific test cases seem to pass, so I guess I'm missing some details...

Thanks

Luigi

**Comment by cvm1ll3** [comment]
Hi @luigidellaquila,

This time its happening for Type LINK, LinkLists works fine:

<code>
/* create category parent vertex */
passJSON = {};
passJSON.class   = "Category";
passJSON.cluster = "CLUSTER Category_DIVISION" +newCategoryJSON.division;
passJSON.content = newCategoryJSON.category;
newCategory      = MISC_createVertex(passJSON);

/* create external accounting vertex */
passJSON = {};
passJSON.class   = "ExternalAccounting";
passJSON.cluster = "CLUSTER ExternalAccounting_DIVISION" +extAcctJSON.division;
passJSON.content = extAcctJSON.content;
extAcctRID       = MISC_createVertex(passJSON);

/* update parent vertex to add link rid */
passJSON = {};
passJSON.class   = "Category";
passJSON.cluster = "CLUSTER:Category_DIVISION" +extAcctJSON.division;
passJSON.rid        = newCategoryRID;
passJSON.content = {};
passJSON.content.externalAccounting = extAcctRID;
MISC_updateVertex(passJSON);

gdb.commit();

/* call query category info */
execSQL = "SELECT @rid," + category + ", " +
              "externalAccounting.include(" + externalAccounting + ") " +
          "FROM " + MISC_reformatClusterName("CLUSTER:Category_DIVISION".concat(json.division)) + " WHERE @rid = ?";
query   = gdb.command("sql", execSQL, [json.rid]);

return query;

</code>

The commit doesn't work on LINKs.
The query returns the RID of externalAcccounting as temporary RID and include doesn't work since its saying the RID is undefined. If you call the query separately after the function runs, the query will return a properly committed RID.

Hope this helps. Thank you!

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

Got it, thank you very much, let me try to reproduce it

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

Could you please paste the code of `MISC_updateVertex`?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
I don't have very clear how those code snippets are related. Are they executed in sequence?
I see you do `gdb.commit();` but you never define `gdb`... And what is `json` in `query   = gdb.command("sql", execSQL, [json.rid]);`?

Thanks

Luigi

**Comment by cvm1ll3** [comment]
Hi @luigidellaquila,

MISC_UpdateVertex JSON parameter:

```
{
  "cluster" : "Category_DIVISION_10",
  "content": {
     "externalAccountingRID" : "<extAcctRID>"
  },
  "rid" : "<CategoryRID>"
}

```
MISC_UpdateVertex Code:

```
gdb       = orient.getGraph();
execSQL   = "UPDATE " + json.cluster + " MERGE " + JSON.stringify(json.content) + " WHERE @rid = " + json.rid;
  updVertex = gdb.command("sql", execSQL, [json.rid]);

```

Yes the blocks of code are executed in sequence and I define gdb at the beginning of the function like this:

`gdb = orient.getGraph();`

The query function is separate that I call after I commit with the following JSON parameter:

```
{
  "rid" : "<CategoryRID>",
  "division": <DivisionRID>
}

```

**Comment by luigidellaquila** [comment]
Hi @cvm1ll3 

Great, thank you very much, I'll try to check it today

Thanks

Luigi

**Comment by alexsixgill** [comment]
Hi - any news on this issue?
