### ISSUE TITLE
How to Create Partial Indexes

### ISSUE THREAD

**Issue by amirmhzadeh** [orientechnologies/orientdb#7384]
### OS: centOS06

Hi, 

I am wondering how I can create a partial index based on the values of optional properties. Specifically, I am wondering how I can enforce uniqueness based on a property that may or may not exist. Or _enforce uniqueness based on a property that holds a certain or null value_. Basically, I am looking for something like this: 

```sql
CREATE INDEX access_log_client_ip_ix ON access_log (client_ip)
    WHERE (client_ip > inet '192.168.100.0' AND client_ip < inet '192.168.100.255');
```

OR

```sql
CREATE TABLE tests (
    subject text,
    target text,
    success boolean,
    ...
);

CREATE UNIQUE INDEX tests_success_constraint ON tests (subject, target)
    WHERE NOT success;

```

Thanks!

**Comment by smolinari** [comment]
Did you see this? https://orientdb.com/docs/2.1/Indexes.html#indexes-and-null-values

Scott

**Comment by amirmhzadeh** [comment]
Hey Scott, 

Thank you for your response. Yes! I read that section. However I would like to create a partial index. That section only describes selecting from an index.

Imagine we have a class A with 2 attributes B and C. We want to enforce a unique constraint on B only when C is null. Postgres (see https://www.postgresql.org/docs/8.0/static/indexes-partial.html) allows you to do this. We would like to do something similar in orientdb but have not found a way to do so. 

Something like"

```sql
CREATE INDEX B_partial ON A (B) WHERE C = 'X'
```

Is there a way to do this? If not could it be a feature request?

**Comment by smolinari** [comment]
Yeah, sounds like a feature request.

Scott
