### ISSUE TITLE
SQL query with IN behaves in the same way as CONTAINS but does not use index.

### ISSUE THREAD

**Issue by SafwanHak** [orientechnologies/orientdb#7386]
## Expected behavior  
an EMBEDDEDLIST field can be queried with 
tagged_users in "3333", should use the index whereas tagged_users contains "3333" works.

## Actual behavior  
does not use the index.  either fix disallow the syntax "in" on embedded list or have it use the index.

## Steps to reproduce  
Create embeddedList field. add a non unique index on it.
run query "EXPLAIN select from table where embeddedField in "3333", it fails.
run query "EXPLAIN select from table where embeddedField in "3333", it works.

**Comment by tglman** [comment]
Hi,

As far as I know  this is fixed in 3.0

Regards

**Comment by luigidellaquila** [comment]
This issue is no longer valid. In V 3.0 IN and CONTAINS have different (and correct) behaviors

Closing

Thanks

Luigi
