### ISSUE TITLE
MATCH Query not using index.

### ISSUE THREAD

**Issue by SafwanHak** [orientechnologies/orientdb#7387]
## Expected behavior  
should show that it used the unique index for _id.

## Actual behavior  
no index used to fetch the starting vertex.

## Steps to reproduce  
create a unique index on field _id on a schema (ex. channel). run the following query.

EXPLAIN MATCH {class: Channel, where: (_id="5904764211d82a05b0b5c7a8")}.outE("e_PERMISSIONS"){as: relationship} return relationship

the explain shows that no index was used.

**Comment by luigidellaquila** [comment]
Hi @SafwanHak 

I guess the problem here is only in the EXPLAIN, probably it's just not reporting that the index is being used.
The use case is quite simple, so I guess the index is correctly used

I'll check it for a fix

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @SafwanHak 

I just pushed a fix for this issue on branch 2.2.x, the fix will be released with 2.2.20

Thanks

Luigi

**Comment by SafwanHak** [comment]
Thanks. do you have a date for 2.2.20 release?

Safwan

**Comment by luigidellaquila** [comment]
Hi @SafwanHak 

I don't have a specific date, but I'd say it will be out in very few days. In the meantime you can find the SNAPSHOT here

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.0-SNAPSHOT/

Thanks

Luigi

**Comment by SafwanHak** [comment]
you mean.
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.20-SNAPSHOT/,
not 3.0, right?

Safwan

**Comment by luigidellaquila** [comment]
Oh yes, sorry, I pushed the fix on both branches...

Luigi

**Comment by SafwanHak** [comment]
Grazie Mille.
