### ISSUE TITLE
Log is filled with memory leak warnings

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7388]
### Java Version: 1.8

After execution of test, https://slack-files.com/T04EMG7AY-F57929QRW-2ee6e8b0ef log is filled with warnings ```2017-05-03 04:16:38:598 SEVER OCachePointer.finalize: readers != 0 [OCachePointer]```

**Comment by laa** [comment]
@lvca could you provide more details how did you reproduce the issue ?

**Comment by laa** [comment]
Fixed

**Comment by careerscale** [comment]
@laa  anything applicable for 3.0? sorry being greedy for 3.0 stuff. :)

**Comment by careerscale** [comment]
sorry, I see 3.0 commit too

**Comment by careerscale** [comment]
sorry, I see 3.0 commit too
