### ISSUE TITLE
Native memory leak because of usage direct byte buffer during WAL flush

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7390]
## Expected behavior  
If a disk cache is full and we perform data modification operations, direct memory consumption should not grow anymore.

## Actual behavior  
Direct memory consumption is increasing without any limits.

## Steps to reproduce  
Create a database which can not be fully cached on disk, start to modify records are placed inside of a database, or you also can rebuild index several times.

**Comment by mrprescott** [comment]
@lvca Any reason to believe this was introduced in 2.2.19, or if it might have been older?

**Comment by laa** [comment]
I suppose it was since 1.9 version or so.

**Comment by anber500** [comment]
This fix might have solved all our issues we've had over the last year with OrientDB. OrientDB has been exceptionally unstable for us. We have had regular instabilities and have not been able to run OrientDB for any time longer than a week without having to restart the nodes.

I have been running a new snapshot of OrientDB and it's been running really well. For the first time in months I've not had to restart any of our servers over a weekend. This is a really good fix and seem to be working really well.

I'll give feedback if anything changes.
