### ISSUE TITLE
Fetching error

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#7393]
## Expected behavior  
Fetch record without throwing errors

## Actual behavior  
 
WARNING: Error deserializing record to get field-names, send this data for debugging: ABhEYXRhX1Byb2ZpbGVtAAABJxRfY3JlYXRlZEJ5AAABNwc9AAABTjsAAAFpWwAAAXF3AAABdmEAAAGRVwAAAZlxAAABzHUAAAkWXwAACSJPAAAJYlEAAAljTQAACX8KaW1hZ2UAAAmOCmMAAAmQSwAACkAIX21pZAAACk8HUwAACnSJAQAACpAUX3B1Ymxpc2hlZAAACpgAGl9jcmVhdGVkX2Vwb2MAAAqZAz8AAAqfcwAACqcQX2NyZWF0ZWQAAAqzBlUAAAq5ZQAACrsaX3VwZGF0ZWRfZXBvYwAACsMDFF91cGRhdGVkQnkAAArJBxBfdXBkYXRlZAAACtMGiwEAAArZjQEAAArkjwEAAArlkQEAAArmkwEAAArnBnJpZAAACxUNAAQXBwpzaXRlMQcKc2l0ZTIsdGhlcmVzZUBtZWRpYXhwcmVzcy5kazRJbnNwaXJhdGlvbiB0aWwgYmVseXNuaW5nPw5MdW1pbmV4CDg3MDA0aHR0cDovL3d3dy5sdW1pbmV4LmRrL2hqZW0OTHVtaW5leAIHBnVybAAAAaQHTi9wcm9maWwvMTQ5MzgxNzk0MS1hZHktTHVtaW5leF9sb2dvLnBuZ5AdPGgzPjxiciAvPkxlZGVyIGR1IGVmdGVyIG55IGluc3BpcmF0aW9uIHRpbCBiZWx5c25pbmcgdGlsIGRpdCBrb21tZW5kZSBwcm9qZWt0PzxiciAvPjxiciAvPjwvaDM+CjxwPkZvcnQmYWVsaWc7bCBvcyBvbSBkaW5lIGlkZWVyIG9nIGJlaG92LiBLb20gZm9yYmkgdm9yZXMgbnllIHNob3dyb29tIG9nIGxhZCBvcyBpbnNwaXJlcmUgZGlnLiBIZXIgcyZhZWxpZzt0dGVyIHZpIGZva3VzIHAmYXJpbmc7ICZhZWxpZztuZHJpbmdlcm5lIGFmIGRlbiBueWUgc3RhbmRhcmQgRFMxMjY0LTEgb2cgZnJlbXZpc2VyIGx5c3MmYWVsaWc7dG5pbmcgaSBmb3Jza2VsbGlnZSBydW0uIDxiciAvPjxiciAvPkxVTUlORVggbCZvc2xhc2g7c2VyIHN0b3JlIHNvbSBzbSZhcmluZzsgYmVseXNuaW5nc3Byb2pla3RlciBzYW1tZW4gbWVkIGRpZy4gVm9yZXMgcHJvZHVrdHNvcnRpbWVudCBzcCZhZWxpZztuZGVyIGJyZWR0LCBmcmEgZGV0IHZlbGtlbmR0ZSBMSU5JQSBza2lubmVzeXN0ZW0gZnJhIFJJREkgdGlsIGluZHVzdHJpZW4gZWxsZXIgYnV0aWtrZW4sIHRpbCB2b3JlcyB1bmlra2UgcHJvZHVrdHNlcmllciBpIGFya2l0ZWt0b25pc2sgYmVseXNuaW5nIGZyYSBMaWdodG5ldCBieSBMVU1JTkVYIHRpbCBhZG1pbmlzdHJhdGlvbmVuIGVsbGVyIHNrb2xlbiBvZyB0aWwgdWR2ZW5kaWcga3ZhbGl0ZXRzYmVseXNuaW5nIGZyYSBDYXJpYm9uaS9GaXZlUCBwJmFyaW5nOyBwYXJrZXJpbmdzcGxhZHNlbiBvZyB2ZWQgaW5kZ2FuZ2VuLiBWaSBoYXIgdWR2YWxndCB2b3JlcyBsZXZlcmFuZCZvc2xhc2g7cmVyIG4mb3NsYXNoO2plIG9nIGtlbmRldGVnbmV0IHZlZCBkZW0gYWxsZSBlciBwcm9mZXNzaW9uYWxpc21lLCBoJm9zbGFzaDtqIGt2YWxpdGV0IG9nIHByb2R1a3Rpb24gaSBFdXJvcGEuJm5ic3A7PGJyIC8+PGJyIC8+PHN0cm9uZz48YSBocmVmPSJodHRwOi8vbHVtaW5leC5kay9oamVtL3JlZmVyZW5jZXIvP3V0bV9zb3VyY2U9QnlnZ2VyaS1hcmtpdGVrdHVyJmFtcDt1dG1fbWVkaXVtPVBhcnRuZXJwcm9maWwiIHRhcmdldD0iX2JsYW5rIiByZWw9Im5vb3BlbmVyIG5vcmVmZXJyZXIiPlNlIGV0IHVkdmFsZyBhZiB2b3JlcyBwcm9kdWt0ZXIgaSBwcmFrc2lzIGhlci48L2E+IDwvc3Ryb25nPjxiciAvPjxiciAvPkxVTUlORVggZXIgdG90YWx1ZGJ5ZGVyIGFmIGJlbHlzbmluZ3NsJm9zbGFzaDtzbmluZ2VyIG1lZCBha3Rpdml0ZXRlciByZXR0ZXQgbW9kIGRldCBwcm9mZXNzaW9uZWxsZSBtYXJrZWQuIFZpIGhhciBzdCZhZWxpZztya2Uga29tcGV0ZW5jZXIgaW5kZW4gZm9yIHRvdGFsciZhcmluZztkZ2l2bmluZywgcGxhbmwmYWVsaWc7Z25pbmcsIHByb2pla3RlcmluZyBzYW10IGxldmVyaW5nIGFmIGJlbHlzbmluZ3NhbmwmYWVsaWc7Zy4gTmV0b3Agcm9sbGVuIHNvbSByJmFyaW5nO2RnaXZuaW5ncy0gb2cgc2FtYXJiZWpkc3BhcnRuZXIsIGVyIHYmYWVsaWc7c2VudGxpZyBmb3Igb3MuIDxiciAvPjxiciAvPk1hbmdlICZhcmluZztycyBlcmZhcmluZyBtZWQgZXRhYmxlcmluZyBhZiBiZWx5c25pbmcsIGRlciB0YWdlciBoZW5zeW4gdGlsIGVuZXJnaS0gb2cgbWlsaiZvc2xhc2g7a3JhdiwgZGVzaWduJm9zbGFzaDtuc2tlciwga29tZm9ydCBvZyBpbmRla2xpbWEsIGFya2l0ZWt0dXIgb2cgaWtrZSBtaW5kc3QsIGh2b3JkYW4gbHlzZXQgc2thbCBiZW55dHRlcyBvZyBhZiBodmVtLCBnJm9zbGFzaDtyIExVTUlORVggdGlsIGVuIHYmYWVsaWc7cmRpZnVsZCBzYW1hcmJlamRzcGFydG5lciBvZyBzcGVjaWFsaXNlcmV0IHImYXJpbmc7ZGdpdmVyLiA8YnIgLz48YnIgLz5MVU1JTkVYIC0gdmkgc2VyIHRpbmdlbmUgaSBkZXQgcmlndGlnZSBseXMuPGJyIC8+PGJyIC8+PGJyIC8+PC9wPhZMdW1pbmV4IEEvU348cD5WciZvc2xhc2g7bmRpbmd2ZWogNzxiciAvPjg3MDAgSG9yc2VucyA8YnIgLz43NiAyNiA2NyAwMDwvcD4AAhcHMDUyMTQ4M2RjNzliYWMyMWVjM2E1MzRlZRxjdmVAbHVtaW5leC5kawAX3AI8cD5Ib3MgTFVNSU5FWCBBL1MgdmlsIHZpIHNrYWJlIGlubm92YXRpdmUgb2cgbGFuZ3NpZ3RlZGUgYmVseXNuaW5nc2wmb3NsYXNoO3NuaW5nZXIsIGRlciB0YWdlciB1ZGdhbmdzcHVua3QgaSBkZSBlbmtlbHRlIGJlaG92IGhvcyB2b3JlcyBrdW5kZXIgb2cgYnJ1Z2VyZS48L3A+CjxwPiZuYnNwOzwvcD4cVnLDuG5kaW5ndmVqIDdINTBhMWMwNzEtN2E4ZS00Y2Q0LWJlNmEtZWYyYmEzMjhkYTVhAhcHMDUyMTQ4NTRjNzliYWMyMWVjM2E1MzU0ZQ5Ib3JzZW5zAe7D3YPnVg5MdW1pbmV4Fjc2IDI2IDY3IDAw7sPdg+dWABcOTHVtaW5leMC2o7b6VhJhaEBteGkuZGvAtqO2+lYUcHJvZmlsXzEuMAAAAAIHBnVybAAACvIHRC9wcm9maWwvMTQ5MzkwMDIyNC0yb2otbHVtaW5leC5qcGdSsgQ= 
liveapp_1   | May 04, 2017 12:17:35 PM com.orientechnologies.common.log.OLogManager log
liveapp_1   | SEVERE: Fetching error on record #41:281
liveapp_1   | com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#0:1' was not found
liveapp_1   | 	DB name="mxi"
liveapp_1   | 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:1790)
liveapp_1   | 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:102)
liveapp_1   | 	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:262)
liveapp_1   | 	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:253)
liveapp_1   | 	at com.orientechnologies.orient.core.record.impl.ODocument.reload(ODocument.java:647)
liveapp_1   | 	at com.orientechnologies.orient.core.type.ODocumentWrapper.reload(ODocumentWrapper.java:91)
liveapp_1   | 	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:73)
liveapp_1   | 	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.reload(OSchemaShared.java:553)
liveapp_1   | 	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.reload(OSchemaProxy.java:182)
liveapp_1   | 	at com.orientechnologies.orient.core.metadata.OMetadataDefault.reload(OMetadataDefault.java:272)
liveapp_1   | 	at com.orientechnologies.orient.core.record.impl.ODocument.getGlobalPropertyById(ODocument.java:2206)
liveapp_1   | 	at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getGlobalPropertyById(ODocumentInternal.java:64)
liveapp_1   | 	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getFieldNames(ORecordSerializerBinaryV0.java:315)
liveapp_1   | 	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.getFieldNames(ORecordSerializerBinary.java:112)
liveapp_1   | 	at com.orientechnologies.orient.core.record.impl.ODocument.fieldNames(ODocument.java:737)
liveapp_1   | 	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:290)
liveapp_1   | 	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:76)
liveapp_1   | 	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:353)
liveapp_1   | 	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:672)
liveapp_1   | 	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:191)

## Steps to reproduce  
Not sure it just happens some times after a while of running.
It doesn't happen to all, just some of the records.
When it starts to happen on some records I have to restart the client before the records work again.

Is there some kind of workaround for this problem?

**Comment by tglman** [comment]
hi @temilmg,

From what I see in the exception while you try to serialize the record to JSON the database try to load some metainformation from the server to be able to read correctly the informations in the record, but is not able to, the reason why is not able to could be some connection problem or something related like an expired session, do you have any additional error in the log ? is it in the server log some error ?

Frankly is the first time I see this error, so I don't a workarond yet.

Regards

**Comment by temilmg** [comment]
There are no errors in the orientdb server log. I only get these fetch errors (SEVERE: Fetching error on record) in the client.
I have a different program that connects to the orient server where I did get an exception when creating a property but I am thinking that shouldn't affect the other client!?

com.orientechnologies.orient.core.exception.OSchemaException: The database contains some schema-less data in the property 'Data_Profile.image' that is not compatible with the type EMBEDDEDMAP. Fix those records and change the schema again
sysms_1     | 	DB name="mxi"
sysms_1     | 	DB name="mxi"
sysms_1     | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sysms_1     | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sysms_1     | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
sysms_1     | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
sysms_1     | 	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:442)
sysms_1     | 	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:393)
sysms_1     | 	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:275)
sysms_1     | 	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
sysms_1     | 	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2225)
sysms_1     | 	at com.orientechnologies.orient.client.remote.OStorageRemote$27.execute(OStorageRemote.java:1200)
sysms_1     | 	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:198)
sysms_1     | 	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:243)
sysms_1     | 	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:195)
sysms_1     | 	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:206)
sysms_1     | 	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1176)
sysms_1     | 	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
sysms_1     | 	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addProperty(OClassImpl.java:2609)
sysms_1     | 	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createProperty(OClassImpl.java:827)
sysms_1     | 	at com.orientechnologies.orient.core.metadata.schema.OClassAbstractDelegate.createProperty(OClassAbstractDelegate.java:165)
sysms_1     | 	at com.tinkerpop.blueprints.impls.orient.OrientElementType.access$201(OrientElementType.java:35)
sysms_1     | 	at com.tinkerpop.blueprints.impls.orient.OrientElementType$3.call(OrientElementType.java:70)
sysms_1     | 	at com.tinkerpop.blueprints.impls.orient.OrientElementType$3.call(OrientElementType.java:67)
sysms_1     | 	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1817)
sysms_1     | 	at com.tinkerpop.blueprints.impls.orient.OrientElementType.createProperty(OrientElementType.java:67)
sysms_1     | 	at com.tinkerpop.blueprints.impls.orient.OrientVertexType.createProperty(OrientVertexType.java:119)

**Comment by tglman** [comment]
hi @temilmg,

From the exception you posted I see you tried to create a property "image" at class "Data_Profile" of type EMBEDDEDMAP but in the database there are record that have a field image that contain a value that is not an EMBEDDEDMAP.

To figure out what are this records you can ran ` select from Data_Profile where image.type() <> 'EMBEDDEDMAP' ` 

Anyway I think this is not directly related to the first problem, another reason for the original problem could be that you are trying to serialize the record to JSON after you close the database instance, without "detach" the record before the close, so the metadata to serialize the record is not yet loaded and create this problem.

Hope this help

bye

**Comment by temilmg** [comment]
Sorry didnt follow up on this!
I am using a remote database and I am using non blocking queries like the one in the documentation (see below) In the result callback i try to turn the record into a json document.

ODocument doc = (ODocument)iRecord;
String json = doc.toJSON("rid"); <------ problem

For some reason if there are in_ and out_ fields in the record the toJSON method starts to ask the db server for the related records i guess!  When using the toJSON in the nonblocking result method it seems like it causes the fething error.

My work around (probably far from ideal is to remove the in_ and out_ fields before calling toJSON on the record)

I actually dont want the full object tree if that is what it is trying to get! I just want what is contained in the record (I dont want the related vertices). In my opinion ideally toJSON should not try to get more data than what is already in the record unless i tell it to get more, maybe some people will disagree:-) 


Future future = database.command(
   new OSQLNonBlockingQuery<Object>(
      "SELECT FROM Animal WHERE name = 'Gipsy'",
      new CommandResultListener(){
         resultCount = 0;
         @Override
         public boolean result(Object iRecord){
            // ENTER YOUR CODE HERE

            System.out.print("callback "+resultCount+" invoked");
            return resultCount > 20 ? false: true;
         }

         @Override
         public void end(){}
      }
   )
).execute();
