### ISSUE TITLE
Sequence Property Default Value Not Lazily Evaluated

### ISSUE THREAD

**Issue by TropicalPenguin** [orientechnologies/orientdb#7399]
## Expected behavior  

Trying to specify a class property's default value as the next item in a created sequence.
Expect each new instance to get a different value.

## Actual behavior  

Two problems. The ALTER PROPERTY under **Steps to reproduce** gives a NullPointerException.

If I change the string delimiter in the sequence() call, the 'ALTER PROPERTY' succeeds, but each new sequenceditem gets the same id.

## Steps to reproduce  
Create a new database, then run the following SQL:

```
CREATE CLASS sequenceditem EXTENDS V
CREATE SEQUENCE item_ids TYPE ORDERED START -1
CREATE PROPERTY sequenceditem.id Long
ALTER PROPERTY sequenceditem.id DEFAULT sequence("item_ids").next()
```

**Comment by luigidellaquila** [comment]
Hi @TropicalPenguin 

The SQL executor evaluates the DEFAULT expression when it executes the ALTER PROPERTY statement, then it caches the result and uses it for each insert.

To avoid this, you can write the expression as a string:

```
ALTER PROPERTY sequenceditem.id DEFAULT 'sequence("item_ids").next()'
```
The string will be evaluated at each INSERT, so you will have what you need

Thanks

Luigi

ps. this is an old behavior, in next versions we will refactor it. The intention is to have two different syntaxes one for DEFAULT VALUE (evaluated once) and one for DEFAULT EXPRESSION (lazy evaluation)

Thanks

Luigi
