### ISSUE TITLE
Strange working SQL GET query for fields with type OType.DATE

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#7403]
### OS: Ubuntu 16.04
Case: strange working SQL GET query for fields with type OType.DATE.

## Expected behavior  
When we executing SQL query for getting documents from OrientDB like "SELECT FROM ${MyClass} WHERE ${MyField}='${MyDate}'" in OrientDB version 2.1.19 all works fine.

## Actual behavior  
When we executing that SQL query in OrientDB version 2.2.19 its don't work!
For getting documents with fields type OType.DATE we must use SQL query like:  "SELECT FROM ${MyClass} WHERE ${MyField} LIKE '${MyDate}'".

For other OrientDB types all works fine.

## Steps to reproduce  
Execute SQL query for get documents from OClass with property type OType.DATE.
SQL query like this: "SELECT FROM ${MyClass} WHERE ${MyField}='${MyDate}'"

## Example
SELECT FROM TestClass WHERE dateField='2017-05-09'

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

It seems to be a bug, checking it

Thanks

Luigi

**Comment by WeaxMe** [comment]
Hi @luigidellaquila, thanks for feedback.

Vitaliy

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

I just pushed a fix for this to branch 2.2.x, the fix will be released with 2.2.20

Thanks

Luigi
