### ISSUE TITLE
Non expected behaviour when sending result of a query to the graph vizualisation

### ISSUE THREAD

**Issue by gnumarco** [orientechnologies/orientdb#7404]
## Expected behaviour  
That the SQL passed to the graph visualization behaves exactly like in the Browser tab, e.g. that when a filter is put on an attribute of an edge, it is actually taken into account in the graph visualisation, which is not the case up to now.

## Actual behavior  
When executing the following query in the Browser: 

SELECT from Is_Manager_Of LET $Pers2 = out.PersNum, where $Pers2 = 76786 and valid_to.asDate() >= date("2017-01-01 00:00:00")

7 nodes and 6 edges are returned (one central node and 6 neighbouring nodes with their respective connecting edges) which is fine.

When clicking on "send to graph", then a second edge appears between the central node and one of the neighbouring node, just because indeed, these two nodes have two linking edges which differ in the "valid_to" date, and this is precisely what I want to filter out.
More generally, it seems that the filtering by "valid_to" value is just bypassed.

## Steps to reproduce  
create a graph with 2 nodes connected by 2 edges. The edges have to have an attribute of type Date with different value.

Run the query above adapting to your graph and trying to return only one of the two edges depending on the date property. It will work in the SQL browser but it will be ignored by the graph visualization.

**Comment by luigidellaquila** [comment]
Hi @gnumarco 

I just pushed a fix on both 2.2.x and develop branches, the fix will be available in next 2.2.20

Thanks

Luigi
