### ISSUE TITLE
Randomly losing indexes on 2.2

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#7410]
### OS: Ubuntu 14.04

Hi guys,

I've written abt this before and there's also an old closed issue that wasnt resolved. We've closed the issue that time. But now im back! ))

We are still unable to move to 2.2 from 2.1, because we indexes are randomly lost. That causes all sorts of hell during system operations. I've done a series of tests before and it seems that most of the time:

1. Index is lost when insertion/update happens through PhpOrient library
2. There seems to be no exception thrown even if I set log level to the FINEST

I **can** reproduce the issue, but i **can't** build a test case, because with a test case it works just fine. However, we can show you (preferably over Skype) that issue is there all the time, because there's a certain way to reproduce this on our system.

Rebuilding all indexes now and then is not an option (too long).

We really (and i mean **REALLY**) need your help on this one. My partner was trying to contact you on this issue a few times already, but getting no replies from the support side (what happened there btw?) ! Whether it's for a separate payment or not (we dont care really), we need to get this resolved and make a move to 2.2. Is there anyone live that we can be put in contact with (skype/phone)?

**Comment by laa** [comment]
Hi @andreyvk . 

I think we should resolve it. I  (according to your name)  suppose that you speak Russian, is it correct?  In such case, I can not schedule a call with you today (it can be done on Monday though), but I can chat with you today. Is it ok for you? Or you prefer Skype meeting? I think the most important thing now is to reproduce the issue using your code. I can download your code and follow your steps to reproduce the issue. Please note that I am not (and nobody in our team) is PHP developer, but I do not think that it will be a show stopper. Looking forward to your answer.

**Comment by andreyvk** [comment]
Hi @laa,

Yes, i do speak Russian and Monday is perfect! Can i have your Skype id so I can add you for now? What time you are available on Mon? I'm available through the day or night, because this is too important now.

Unfortunately, setting up our system is not a once step process and also there's no project that you can download, because it's a private one. I'll see if i can prepare a test server instead.

What I was actually thinking is a Skype screen sharing session (at least for the first time). Reproducing this on my local VM is straightforward. Identifying the problem as to why it happens - that's the main problem. 

Plz tell me what you think.

**Comment by laa** [comment]
Hi @andreyvk , I think 12:00 AM at Monday will be OK for me. My skype account is lomakin_andrey . Is it possible for you to send me disk image of your VM? I can then reproduce it on my side too.

**Comment by andreyvk** [comment]
@laa 12:00AM? you mean Mon midnight? Or do you mean Mon noon? Which timezone? 

Our DB is under NDA, of course. I need to discuss this possibility (sending VM) with my partner first. Image is quite large too. Let me see what we can do to make it easier for you. Meanwhile I'll add you to my skype contacts list. Thanks!

**Comment by laa** [comment]
Oh Sorry PM )) , GMT + 2. You can give us ssh connection to your VM as an alternative solution. Anyway I would need some means to check what is going underneath of server.

**Comment by andreyvk** [comment]
@laa, got it. 12 noon GMT+2

Like i said we should be able to set you up for our test server. I'll let you know as soon as possible

**Comment by andreyvk** [comment]
Hi @laa,

I'll provide you access to our server test server. We'll set up the environment and get it ready to replicate, when we are online together. I'll be sending an email to your gmail account (found on GitHub) with details. 

Again, thank you very much for this. This is very important to us :)

**Comment by laa** [comment]
@andreyvk As we agreed I sent you a screenshot of the method in Java debugger which process update request http://i.imgur.com/qnskh9e.png it is clearly seen there that version is -1 and debug log of all data are read from binary request during processing of this ... request (sorry for tautology) https://gist.github.com/laa/8f7d372554f07a8e75743d7da6987307 . I am closing issue from our side.

**Comment by andreyvk** [comment]
@laa I've already created a GitHub issue on PhpOrient project. Thank you very much for your time! Do hope that PhpOrient project creator will be able to attend to this the soonest.

**Comment by andreyvk** [comment]
@laa The issue seems to be fixed now with latest PhpOrient 1.2.6. Thank you very much again for your help!
