### ISSUE TITLE
Frontend forgets unfinished statements when switching tabs. LocalStorage to the rescue.

### ISSUE THREAD

**Issue by grindhold** [orientechnologies/orientdb#7413]
## Expected behavior  
The frontend should store statements that have not been executed but begun in the localStorage and retrieve them when one re-enters the according tab.

## Actual behavior  
I often switch between the "Graph" and  "Browse" tabs when developing queries. Whenever I switch, orientdb forgets the queries I have been coding.

## Steps to reproduce  
1. Log in to your orient db web frontend (and select a database)
2. Go to "Browse" tab
3. Write " SELECT FROM UnfinishedStatements WHERE"
4. Switch to "Graph" tab
5. Write " SELECT FROM UnfinishedStatements WHERE -- oops i forgot someth…"
6. Switch to "Browse" tab again
7. *poof* … Query gone.

**Comment by maggiolo00** [comment]
Hi @grindhold 
thanks for this issue. I will mark this as enhancement. It make sense to store also the current editing query in the local storage

Thanks
