### ISSUE TITLE
SQL Select returns wrong result if field ordered by is not in the selected fields.

### ISSUE THREAD

**Issue by SafwanHak** [orientechnologies/orientdb#7416]
## Expected behavior  
data returns in the order by

## Actual behavior  
returns ordered by @rid

## Steps to reproduce  
Hi guys,

I've been tracking a bug for a couple of hours and it seems that the SQL returns the wrong result if the field ordered by is not in the selected fields, had my head scratching for sometime. see the 2 queries below.. they are almost the same except the first one returns created_dt.

the first query is fetching data ordered by created_dt and has the same field returned, the result is correct.

SELECT user_box_id,_id, name, created_dt FROM MyTable WHERE ( user_id = "5916dd9c11d82a0369450424") ORDER BY created_dt desc LIMIT 5

In the following query, the result does not have created_dt and the order by is wrong. I've analyzed the data and it's ordering by the @rid. #213:3, #213:4, #213:5, #214:3, #214:4, when the field is missing.

SELECT user_box_id,_id, name FROM MyTable WHERE ( user_id = "5916dd9c11d82a0369450424") ORDER BY created_dt desc LIMIT 5

I haven't been doing SQL for sometime but I don't believe the field must be returned for an order by to work as that's the filtering after the fetch and not prior.  If I'm wrong on this, I prefer an error from the database to be honest than misleading result.

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @SafwanHak 

This is one of the known limitations in v 2.2 that is already fixed in 3.0.
Unfortunately there is no way to fix it in current stable, the only work-around is to declare the sorting properties in the projection

Thanks

Luigi
