### ISSUE TITLE
Please make it clear in Studio that Type of query is BATCH or COMMAND

### ISSUE THREAD

**Issue by SafwanHak** [orientechnologies/orientdb#7419]
### OS: Centos  

Suggestion: please change the green RUN button in Studio to display when it's in batch mode, so it's clear we need to switch to command.  

FYI, few weeks ago, I didn't know why the batch syntax that I wrote wasn't working, it wasn't clear that I had to configure the settings, only when Luigi pointed it out it became clear.  I suggest a review of the approach.  Maybe it would be simpler to say if the selection/query starts with BEGIN then run as batch and forget the option completely.

if not, another suggestion is to have a an arrow next to RUN so we can easily switch without the config. let me know if it's not clear.

Thanks

**Comment by maggiolo00** [comment]
Hi @SafwanHak 

thanks for the suggestions.

I would prefer using some label on the button

`Run Query`
`Run Script`

along with your last option of quick switch between them

**Comment by SafwanHak** [comment]
That works.

Thanks Enrico,
Safwan

**Comment by lvca** [comment]
👍
