### ISSUE TITLE
Allow property values to be null when creating an edge

### ISSUE THREAD

**Issue by amirmhzadeh** [orientechnologies/orientdb#7420]
### OS: centOS 06

Seems like orientDB intentionally does not allow for properly values to be null when creating an edge.

``` java
in OrientElement.java: 

    if (settings.isStandardElementConstraints() && null == value)
          throw ExceptionFactory.propertyValueCanNotBeNull();
```

This issue was pointed out before in [issue #3365](https://github.com/orientechnologies/orientdb/issues/3365). Some workarounds have been suggested in this original ticket.  Not sending the property at all or altering the standardElementConstraints are as such:
 ```SQl
alter database custom standardElementConstraints=false
```

However, the first workaround is not an optimal solution for us (i.e. not sending the property at all).

We preferably do not want to alter the "standardElementConstraints" as it requires us to do this for every test db and make it part of the server connection. We are also worries about the possible side effects of altering the "standardElementConstraints". 

It would be great if a feature could be added to allow us to turn off the null constraint without having to set "standardElementConstraints" and turn off all blueprint checks.

**Comment by luigidellaquila** [comment]
Hi @amirmhzadeh 

Unfortunately that constraint is part of Apache TinkerPop standard, so as long as you use TP the only way to disable it is to set `standardElementConstraints` to false.

In V 3.0 we will have a core multi-model API with graph capabilities that does not have this limitation, but in 2.2 there is no alternative unfortunately.

Thanks

Luigi
