### ISSUE TITLE
Can't save CSV from studio - may be reopen #7376

### ISSUE THREAD

**Issue by ghost** [orientechnologies/orientdb#7422]
## Expected behavior  
SELECT FROM WHATEVER LIMIT -1

## Actual behavior  
SELECT ... LIMIT 8000
renders "download Failed - Network error"

## Steps to reproduce  
Limit 8000+

**Comment by austx** [comment]
This is obviously a bug - can someone please have a look?

**Comment by maggiolo00** [comment]
hi @austx 

let me check it

Thanks

**Comment by maggiolo00** [comment]
Hi @austx 

i was not able to reproduce it with `Limit 8000+`

Do you have any exception on the server?
