### ISSUE TITLE
Possible NPE when switching from 2.2.19 to 2.2.20

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7427]
## Expected behavior  
There is the following SQL:
```sql
select sum(myField.size()) as count from ClassA 
```
"myField" is LINKSET/LINKLIST.
If this field is empty for all documents of ClassA this SQL should return 0

## Actual behavior  
Starting 2.2.20 this SQL began return "null" which might lead to NPE in consuming code.

Please let me know if starting 2.2.20 it's expected behavior.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I just pushed a fix on 2.2.x. The fix will be released with 2.2.21

Thanks

Luigi
