### ISSUE TITLE
Transaction management issues with  gremlin api in orient 3.0, roll back doesn't work

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7429]
## Expected behavior  
test case should pass. data should not get saved.  

## Actual behavior  
data doesnt get saved at all.

## Steps to reproduce  
https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/resources/testSchema.sql

https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/java/com/orientdb/samples/test/OrientDbTest.java

**Comment by maggiolo00** [comment]
Hi @careerscale 

for inline properties you should use this syntax

```java
Vertex userVertex = graph.addVertex(T.label, "User", "name", "Tony", "status", 1l);
```

see here

http://tinkerpop.apache.org/docs/current/reference/#_the_graph_structure

**Comment by maggiolo00** [comment]
I tried to run your test and the data got saved in `V` instead of `User`.
The Object[].. params should be multiple of two and contains the couple

`T.label , "Class"` so the vertex is saved with in the right class

**Comment by careerscale** [comment]
Thank you @maggiolo00 
Yes, it worked that way, but I see my original problem of transaction not able to save multiple vertices of same type.

**Comment by careerscale** [comment]
test method, testWithTransactionRollback() was supposed to rollback the data right?  as you may see in  the console, exception about mandatory field is printed, and I was expecting a transaction rollback to get triggerred and revert other data (User and Bonus vertices) be rolled back.

**Comment by maggiolo00** [comment]
hi @careerscale 

if i execute `performTransactionWithRollBack` instead of `performTransaction` no vertices/edges are written in the database

**Comment by maggiolo00** [comment]
maybe you are referring to the OrientDbTest.java test

**Comment by careerscale** [comment]
Updated this test code (OrientDbTransactionTest.java) with 2 different scenarios (one for each bug). can you please check and let me know if you are able to reproduce it?

**Comment by maggiolo00** [comment]
Hi @careerscale 

yes i was able to reproduce it.
I've checked and seems that there now the TP3 implementation does not implement auto start of the transaction. If manually begin the tx like this

```JAVA
OrientGraph graph = factory.getTx();
graph.begin();
```

`createUserTransactionWithRollbackTest` passes

but still `createUserTransactionTest` does not pass because if the duplicate id and the tx fails

**Comment by careerscale** [comment]
@maggiolo00 , the core part of this bug was about transaction rollback so this issue (7429) is good to be closed. thanks for the clarificatons

**Comment by lvca** [comment]
Cool, thanks.

**Comment by lvca** [comment]
@maggiolo00 do you want to open a new bug for the TP3 auto-tx?

**Comment by careerscale** [comment]
cant we use 7430? for that purpose?

**Comment by maggiolo00** [comment]
Hi @careerscale 

it's better to track it to another issue. I think that 7430 is related to sequence and not
tx management.

**Comment by careerscale** [comment]
yes, makes sense.
