### ISSUE TITLE
Multiple vertices of same class do not get saved in single transaction - with sequence

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7430]
## Expected behavior  
Multiple vertices are not being saved, test case  creates multiple Vertices (of User and Bonus types)  in a single transaction but what gets saved is only one per type.  We had same problem with orientdb-graphdb api earlier and as per the suggestion moved to gremlin, but here too I seem to have problem.

my db schema definition defines a sequence for these vertex types so I would expect that to auto generate multiple ids as needed within the same transaction.  I think I am not looking for something complex here, this is a simple requirement and should be working fine.

Unit test attached with sandbox code

I would expect the test case to pass.

## Actual behavior  
test fails

## Steps to reproduce  
db schema:
https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/resources/testSchema.sql

test case
https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/java/com/orientdb/samples/test/OrientDbTransactionTest.java

**Comment by maggiolo00** [comment]
It should be the same as 
https://github.com/orientechnologies/orientdb/issues/7429
If you check on `V` you will find the data. Use `T.label , "class"`  in order to save in the right 
class

Thanks

**Comment by careerscale** [comment]
@maggiolo00, I made a mistake in giving correct unit test code, updated the class information. it is  OrientDbTest.java

**Comment by careerscale** [comment]
I am depending on sequence to generate the id and there seems to be an issue around how sequence is generated in OrientDB. 

If we look at the script, as per @luigidellaquila  suggestion earlier, I am using the auto increment feature  (see the bolded text below)
# select expand(classes) from metadata:schema
ALTER DATABASE DATETIMEFORMAT "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" 

# Master data
CREATE CLASS BV EXTENDS V;
CREATE PROPERTY BV.createdDate DATETIME (MANDATORY TRUE, default sysdate("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
CREATE PROPERTY BV.updatedDate DATETIME (MANDATORY FALSE); 
# we can make updatedDate mandatory later.

CREATE CLASS BE EXTENDS E;
CREATE PROPERTY BE.createdDate DATETIME (MANDATORY TRUE, default sysdate("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
CREATE PROPERTY BE.updatedDate DATETIME (MANDATORY FALSE);
# we can make updatedDate mandatory later.

CREATE CLASS User EXTENDS BV;
CREATE SEQUENCE userIdSequence TYPE ORDERED;
CREATE PROPERTY User.name STRING (MANDATORY TRUE, MIN 3, MAX 50);
**CREATE PROPERTY User.id LONG (MANDATORY TRUE, default "sequence('userIdSequence').next()");**
CREATE PROPERTY User.status INTEGER (MANDATORY TRUE);
CREATE INDEX USER_ID_INDEX ON User (id BY VALUE) UNIQUE;

CREATE CLASS Bonus EXTENDS BV;
CREATE SEQUENCE bonusIdSequence TYPE ORDERED;
CREATE PROPERTY Bonus.name STRING (MANDATORY TRUE, MIN 3, MAX 50);
**CREATE PROPERTY Bonus.id LONG (MANDATORY TRUE, default "sequence('bonusIdSequence').next()");**
CREATE PROPERTY Bonus.volume LONG (MANDATORY TRUE);
CREATE INDEX BONUS_ID_INDEX ON Bonus (id BY VALUE) UNIQUE;
CREATE CLASS HAS EXTENDS BE;

**Comment by careerscale** [comment]
@maggiolo00 , is this something we can discuss through phone or chat?

**Comment by maggiolo00** [comment]
Hi @careerscale 

i was able to reproduce it. I'm working on a fix

Thanks

**Comment by careerscale** [comment]
Thank you @careerscale

**Comment by maggiolo00** [comment]
Hi @careerscale 

I've provided a fix to Sequence.

**Comment by careerscale** [comment]
Excellent, thank you. Will check with next snapshot once it is built

**Comment by careerscale** [comment]
It worked earlier but looks like not working again, is there any change? @maggiolo00

**Comment by maggiolo00** [comment]
hi @careerscale 

i've provided also a test case for regression, seems strange.
Which error do you get?

is the test case always the same?

**Comment by careerscale** [comment]
I think it is to do with other changes and the stability of the build itself,  we are using graph.getRawDatabase().newVertex(..) to create new vertex in many places (we are moving to pure TP 3.0 one as soon as possible), this was working fine and started breaking from yesterday's snapshot.

**Comment by careerscale** [comment]
no i think I dont have  a unit test for this approach yet, I want to move to using TP 3.0 though.

**Comment by careerscale** [comment]
looks good with latest snapshot. yesterday's snapshot was bad one
