### ISSUE TITLE
Help on query using indexing of Edge

### ISSUE THREAD

**Issue by DienNM** [orientechnologies/orientdb#7433]
### OS: Ubuntu  

I do the query to get top of edges from given rid.
Product is vertex, Relation is Edge. "times" is a property of Relation that tracks the weight of relationship of 2 products.

I want to get top 10 of links with highest time. I do index on "times":
CREATE PROPERTY Relation.times LONG
CREATE INDEX Relation.times NOTUNIQUE_HASH_INDEX.

I did the query:
Select expand(bothE("Relation")) from Product where @rid = '#70:04' Order by times DESC limit 10.

I got the warning: "fetched more than 50000"  to speed up the execution, create an index or change the query to use an existent index.

I still have the result but it is slow. I thought it should apply Indexing in my case.

**Comment by luigidellaquila** [comment]
Hi @DienNM 

How many edges does that vertex have?
Could you please try the following and see if it performs better?

```
Select expand(bothE("Relation")) from #70:4 Order by times DESC limit 10
```

Thanks

Luigi

**Comment by DienNM** [comment]
Thank you Luigi.

It works!
