### ISSUE TITLE
Inline LinkList of Batch Variables in Vertex Creation

### ISSUE THREAD

**Issue by TropicalPenguin** [orientechnologies/orientdb#7435]
## Expected behavior

Expect to be able to specify a LINKLIST inline in the SET clause of CREATE VERTEX, when this LINKLIST is composed by evaluating batch variables.

## Actual behavior  

I get the following OValidationException when I try to define the LinkList inline, rather than defining a batch variable to contain it.

`pyorient.exceptions.PyOrientCommandException: com.orientechnologies.orient.core.exception.OValidationException - The field 'bar.foos' has been declared as LINKLIST but the value is not a record or a record-id`

## Steps to reproduce  

Given this setup:

```
CREATE CLASS foo EXTENDS V
CREATE CLASS bar EXTENDS V
CREATE PROPERTY bar.foos LinkList foo
```

This batch **does not** work:
```
BEGIN
LET a = CREATE VERTEX foo
LET b = CREATE VERTEX foo
LET c = CREATE VERTEX foo
CREATE VERTEX bar SET foos=[$a,$b,$c]
COMMIT
```

Whereas this one **does**:

```
BEGIN
LET a = CREATE VERTEX foo
LET b = CREATE VERTEX foo
LET c = CREATE VERTEX foo
LET foos = [$a,$b,$c]
CREATE VERTEX bar SET foos=$foos
COMMIT
```

**Comment by luigidellaquila** [comment]
Hi @TropicalPenguin 

I just pushed a fix for this in 2.2.x, the fix will be released with 2.2.21

Thanks

Luigi
