### ISSUE TITLE
Updating a LINKLIST property using the document API sometimes doesn't work in distributed mode.

### ISSUE THREAD

**Issue by dalegarv** [orientechnologies/orientdb#7437]
## Expected behavior  
Updating a LINKLIST should always work.  

## Actual behavior  
Sometimes the update works, but sometimes it doesn't. 

## Steps to reproduce  
Retrieve an ODocument that has a LINKLIST value and try to update it with another LINKLIST in a distributed environment.  Repeatedly run the exact same test case and occasionally the update doesn't work.  It seems to be some kind of timing problem.

The workaround we're forced to use is to create a new ODocument for the save rather than using the existing ODocument returned from the database.

**Comment by maggiolo00** [comment]
Hi @dalegarv 

do you get some exception?

**Comment by dalegarv** [comment]
Hi @maggiolo00, no exception was thrown when the update didn't happen.

**Comment by tglman** [comment]
Hi,

This issue was fixed in 2.2.34.

Closing
