### ISSUE TITLE
OrientDB 3.0  delete doesnt work in a transaction

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7438]
## Expected behavior  
Delete should work within a transaction scope (when  graph.begin() is used).

## Actual behavior  

Test case fails, delete doesn't work with graph.begin(), works without it.

## Steps to reproduce  

run the schema
https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/resources/testSchema.sql

https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/java/com/orientdb/samples/test/OrientDbDeleteTransactionTest.java

test method deleteUsers should pass

**Comment by maggiolo00** [comment]
Hi @careerscale 

thanks for the test, let me check it

**Comment by careerscale** [comment]
Thanks @maggiolo00

**Comment by tglman** [comment]
hi @careerscale,

we checked reproduced and we are working on a fix, the fix is going to land in 1/2 days.

Regards

**Comment by careerscale** [comment]
Thanks,

the current snapshot is not stable, so once it is, will be able to validate it.

**Comment by careerscale** [comment]
I think we are good with it. can be closed.

**Comment by tglman** [comment]
Hi @careerscale,

Thank you to let us know.

Regards
