### ISSUE TITLE
DepthFirstTraverseStep.java minor typo in explain plan 

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7440]
## Expected behavior  
There shouldnt be any typo.

## Actual behavior  
First is misspelt as FRIST in DepthFirstTraverseStep.java 

    result.append("+ DEPTH-FRIST TRAVERSE \n");

## Steps to reproduce  

DepthFirstTraverseStep.java

**Comment by luigidellaquila** [comment]
Thank you very much @careerscale, I just fixed the typo

Luigi
