### ISSUE TITLE
Relational data import into graph database

### ISSUE THREAD

**Issue by zhangshusheng** [orientechnologies/orientdb#7441]
## Expected behavior  
Import relational data into graph database.
The data is generated by BigBench. It has 23 tables and only 1 GB.

## Actual behavior  
The speed of import is too slow. Sometimes, importing a table needs several days.
Why is this happening?

## Steps to reproduce  
 The content of one import configuration .json file  as follows : 

{
  "source": { "file": { "path": "/opt/data/csv/customer.csv" } },
  "extractor": { "csv": {} },
  "transformers": [
    { "vertex": { "class": "customer"} }
  ],
  "loader": {
    "orientdb": {
       "dbURL": "plocal:/opt/orientdb/databases/graphbigbench",
       "dbType": "graph",
       "classes": [
         {"name": "customer", "extends": "V"},
         {"name": "web_sales", "extends": "V"},
		 {"name": "customer_address", "extends": "V"},
		 {"name": "customer_demographics", "extends": "V"},
		 {"name": "household_demographics", "extends": "V"},
		 {"name": "product_reviews", "extends": "V"},
		 {"name": "store_returns", "extends": "V"},
		 {"name": "web_clickstreams", "extends": "V"},
		 {"name": "store_sales", "extends": "V"},
		 {"name": "web_returns", "extends": "V"},
		 {"name": "web_page", "extends": "V"},
		 {"name": "web_purchase", "extends": "E"},
		 {"name": "live", "extends": "E"},
		 {"name": "person_stastics", "extends": "E"},
		 {"name": "house_stastics", "extends": "E"},
		 {"name": "customer_review", "extends": "E"},
		 {"name": "store_customer_return", "extends": "E"},
		 {"name": "customer_click", "extends": "E"},
		 {"name": "customer_purchase", "extends": "E"},
		 {"name": "web_customer_return", "extends": "E"},
		 {"name": "customer_browse", "extends": "E"}
       ]
    }
  }
}

Other file is similar. 
What is the problem ? Looking forward to your help .

**Comment by lvca** [comment]
Have you tried using Teleporter in the OrientDB Enterprise Edition trial?

**Comment by zhangshusheng** [comment]
Hi Ivca,
I use the OrientDB Community Edition. Is there any solution?
And is Enterprise Edition free?

**Comment by lvca** [comment]
You can use Teleporter by downloading the Enterprise Edition trial for FREE and use it for 45 days to complete the importing, then once the database has been imported you can use the Community Edition that is Apache 2 (FREE).

**Comment by lvca** [comment]
Do you mean with the ETL?

**Comment by zhangshusheng** [comment]
Yes, importing database with the ETL is too slow, as the above problem I mentioned.
What is the cause? Is the relationship between tables is too complex that creating one class(vertices) needs other linked class(edges) ?
