### ISSUE TITLE
OrientDB 3.0 Impossible to read a chunk of length:309751660 max allowed chunk length:16777216 

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7442]
## Expected behavior  
Application should work normally

## Actual behavior  
Exception in thread "Thread-15" com.orientechnologies.common.io.OIOException: Impossible to read a chunk of length:309751660 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings 
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readBytes(OChannelBinary.java:161)
	at com.orientechnologies.orient.client.remote.OStorageRemotePushThread.run(OStorageRemotePushThread.java:41)

## Steps to reproduce  
Adding db constraints broke this. I cant share the original script, but just followed http://orientdb.com/docs/2.0/orientdb.wiki/Tutorial-Using-schema-with-graphs.html and added out and in for all edges I have defined in my product and also added unique  constraint for all edges.

**Comment by careerscale** [comment]
When I started getting this exception, I was not able to make it work (even when I worked with schema that worked before). Even tried to delete  the orientdb folder and extracted the snapshot copy of (may 22nd), but with no luck.

I could make it(my previous schema and  work with May 23rd snapshot zip file ([downloading fresh](https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.0-SNAPSHOT/orientdb-community-3.0.0-20170523.113815-568.zip) and extracting the)

**Comment by careerscale** [comment]
Looks like it is nothing to do with schema changes I have done, but something broke with the snapshot libraries.

**Comment by careerscale** [comment]
@tglman

Should we increase NETWORK_BINARY_MAX_CONTENT_LENGTH value?

**Comment by tglman** [comment]
hi @careerscale,

we did some changes on the binary protocol in the last couple of days so the client and the server snapshots should be both updated, the error you are getting means that the client and the server are not aligned increase the NETWORK_BINARY_MAX_CONTENT_LENGTH it wont fix it. we had some issues last couple of builds and we are working on stabilize them right now.

Regards

**Comment by careerscale** [comment]
Hi @tglman 

Thanks for the clarification, btw is the current build supposed to work if the client and core libraries are same as that of  orientdb server in my  project dependencies? I thought that is the case for me.

**Comment by tglman** [comment]
hi @careerscale,

Yes if the client and server are from the same snapshot have to work otherwise there is a bug, anyway yesterday we had some issue on our build so I'm not sure if the snapshot pushed online was perfect, anyway today want back to normal so you shuldn't have any problem with last snapshot.

Regards

**Comment by careerscale** [comment]
Ok, how do I use a specific snaphsot version? I want stick to a working version all the time to avoid loss of productivity by my team

I get this error:
[ERROR] Failed to execute goal on project mlm-data: Could not resolve dependencies for project com.calliduscloud.mlm:mlm-data:jar:1.0-SNAPSHOT: Could not find artifact com.orientechnologies:orientdb-gremlin:jar:3.0.0-20170524.114316-570 in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

**Comment by careerscale** [comment]
build looks fine today, now I want to lock to this version for my team.

**Comment by careerscale** [comment]
Looks good, so closing this issue

**Comment by tglman** [comment]
hi @careerscale,

good to know that now it works, if you need you to lock SNAPSHOTS you can follow this: http://www.mojohaus.org/versions-maven-plugin/examples/lock-snapshots.html.

Regards
