### ISSUE TITLE
SQL LIKE Operator not performing correctly.

### ISSUE THREAD

**Issue by Kent767** [orientechnologies/orientdb#7445]
## Expected behavior  
LIKE Operator should return all vertices which match the search pattern.

## Actual behavior  
It seems the LIKE operator only supports up to 2 % characters, which is inconsistent with normal SQL Like behavior.

## Steps to reproduce  
Create a Vertex with property Code = "Test"

select from V where Code like '%Test%' -- returns as expected
select from V where Code like '%Te%t%' -- does not return expected results

**Comment by Kent767** [comment]
Confirmed that this is also an issue in Version 3.0

**Comment by luigidellaquila** [comment]
Hi @Kent767 

LIKE operator is implemented to only consider wildcards at the beginning or at the end.
You can use MATCHES instead, passing a regular expression (Java syntax - https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html), eg.

```
select from V where Code MATCHES '.*Te.*t.*' 
```

In the meantime I'm marking this as an enhancement, probably we will extend the behavior of LIKE operator in the future

I hope it helps

Thanks

Luigi
