### ISSUE TITLE
Index key locking is broken on mutable keys

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#7448]
Some index keys, like ORIDs and OCompositeKeys containing ORIDs, may be mutated during the record insertion. As a result, key locking for such keys is not reliable. We already have the fix for that – micro transactions in `micro-tx` branch, but the locking order should be changed. First, we must lock the clusters, then update the record identities and then lock the indexes.

Micro transactions must be backported to 2.2.x with the fix mentioned above.

**Comment by lvca** [comment]
Can't you just copy the ORID?

**Comment by tglman** [comment]
hi All,

I've been playing with rid generation and remote tx in the last couple of days, we have some issue there with the changing rid and as well the cluster selection and hooks management.

The only embedded tx follow a different flow so my plan is remove this different flow and fix all rid mutation related issues.

Regards

**Comment by taburet** [comment]
The problem is that we lock wrong keys, copying wont help here. If we insert a record, which contains a "temporary" rid as a value, we lock this temporary rid-key and the corresponding index, after that we convert the rid into a persistent one. That's ok in most cases since the index is wholly locked as a component, but for auto-sharded indexes we may lock the wrong shard corresponding to the old rid value and this will lead to data inconsistency.

In `micro-tx` branch there are no more key locks, so obviously there is no such problem any more.

**Comment by taburet** [comment]
With new micro-transactions RIDs are assigned before the index locking takes place, so there is no such problem anymore.
