### ISSUE TITLE
NPE while trying to create vertex with no properties set

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7450]
## Expected behavior  
we should be able to create vertex without properties, as per logic, our application will feed properties later, but getting null pointer.

Same result from console and browser too.

## Actual behavior  
Throws up nullpointer

## Steps to reproduce  
CREATE CLASS Person EXTENDS V;
CREATE PROPERTY Person.name String (default "test");
### This fails
CREATE VERTEX Person; 

### This one works though
CREATE VERTEX Person SET name="Luca";

**Comment by careerscale** [comment]
Please check the edge too.

**Comment by luigidellaquila** [comment]
Hi @careerscale 

Thank you for the report, checking now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @careerscale 

I just pushed a fix for this on develop branch

Thanks

Luigi
