### ISSUE TITLE
Orient 3.0 - Unique index on edge is not working as expected

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7453]
## Expected behavior  
The constraint like this one below
create property LIVES_IN.out LINK User;
create property LIVES_IN.in LINK Address;
create index UNIQUE_LIVES_IN on LIVES_IN(out,in) unique;

should ensure something like this

Luca LIVES_IN London
Luca LIVES_IN Rome
Luigi LIVES_IN Rome   

work fine, and when we get same relation twice

say another 
Luca LIVES_IN London 

it should break

## Actual behavior  
it breaks right at 3rd line
Luigi LIVES_IN Rome   
## Steps to reproduce  
https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/java/com/orientdb/samples/test/OrientDBInvalidTxCounterTest.java
and check createUser_gremlin() method, run it.

**Comment by careerscale** [comment]
any update on this one?

**Comment by tglman** [comment]
hi @careerscale,

I just pushed this commit: https://github.com/orientechnologies/orientdb/commit/5af5f029261084e36fb1ad0be1093be4306c49a7 that fix this issue, the today snapshot should have this problem fixed.

Closing this.

Regards

**Comment by careerscale** [comment]
@tglman 
is this issue
https://github.com/orientechnologies/orientdb/issues/7470 because of the 7453?

**Comment by maggiolo00** [comment]
Hi @careerscale 

nope it's not related. I'm working on a fix.
