### ISSUE TITLE
Limit Password Attempts on User Login

### ISSUE THREAD

**Issue by RyanTopps** [orientechnologies/orientdb#7454]
## Expected behavior  
I want to see if there is way for the database to limit login attempts per ip to prevent brute force attacks.

## Actual behavior  
I can see no way to implement this without having a separate host or process to handle the blocking of repetitive login queries.

## Steps to reproduce  
Just use any api and you can brute force through connection attempts.

**Comment by luigidellaquila** [comment]
Hi @RyanTopps 

In ehe Community Edition there is no such feature. In the EE you can rely on Kerberos authentication, so Kerberos can manage it for you, but it's not a built-in feature of OrientDB security system.

I'm flagging it as an enhancement, maybe we will develop it in the future

Thanks

Luigi
