### ISSUE TITLE
How to do spanish characters insensitive search ?

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#7456]
## Expected behavior  
I am having class with columns containing names of cities in Colombia, one of them is "Cáqueza".
![screen shot 2017-05-27 at 12 48 53](https://cloud.githubusercontent.com/assets/4742672/26523359/b2aa348a-42db-11e7-87b9-016fb781aab1.png)

I would like to get this record when I search for "Caqueza" e.g. :
select * from Place WHERE name="Caqueza"

Does somebody has an idea how can be this done, please ?

**Comment by robfrank** [comment]
I think that the only way could be to define a Lucene full text index on the property, maybe using a SpanishAnalyzer, and the query it:

```sql
CREATE index Place.name ON Person(name) FULLTEXT ENGINE LUCENE METADATA{
 "default": "org.apache.lucene.analysis.es.SpanishAnalyzer"
}
```

and then query with:

```sql
SELECT from Place where name LUCENE "Caqueza" 
```

It should be tested, because I don't know if the Spanish analyzer does that. Maybe not. 

reference documentations about full text support on OrientDB:
http://orientdb.com/docs/last/Full-Text-Index.html

About spanish analyzer:
https://lucene.apache.org/core/5_3_2/analyzers-common/org/apache/lucene/analysis/es/SpanishAnalyzer.html

**Comment by imainetti** [comment]
It seems to work

```
orientdb {db=github7456}> select from Place where name LUCENE "Bogota"                                                                                        

+----+-----+------+------+
|#   |@RID |@CLASS|name  |
+----+-----+------+------+
|0   |#18:0|Place |Bogotá|
+----+-----+------+------+

1 item(s) found. Query executed in 0.097 sec(s).
```

**Comment by petervavro** [comment]
Works perfectly, great job ! Thank you so much !

**Comment by petervavro** [comment]
I am sorry but I have encountered some issue with this solution. I am having Colombian departments in the table. When I am searching for "Valle del Cauca" I am also getting other department with name "Cauca" in order "Cauca","Valle del Cauca". How can I get more precise results ?

**Comment by robfrank** [comment]
the Lucene index works this way. It indexes terms, so it tokenizes your phrase and index each term. 
You can use the full Lucene's query syntax on such an index. At the links you can found more infos:

https://lucene.apache.org/core/5_3_2/queryparser/org/apache/lucene/queryparser/classic/QueryParser.html

http://www.lucenetutorial.com/lucene-query-syntax.html
