### ISSUE TITLE
Class superclasses does not preserve order

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7460]
### OS: ubuntu

There are 3 classes:

1. ClassA
2. ClassB
3. ClassC

Lets create one more class with the following order of super classes:
ClassA, ClassC, ClassB

## Expected behavior  
Expected that order will be preserved

## Actual behavior  
Order break and become: ClassA, ClassB, ClassC

I do understand that order doesn't influence db schema features, but this feature will help for external usage when, for example, it's needed to know "main" super class.
And it seems that fix is extremely easy. Root cause is there: https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/orient/core/metadata/schema/OSchemaShared.java#L745
Just change it to ArrayList (uniqness checked during schema modifications) or LinkedHashSet

**Comment by PhantomYdn** [comment]
@tglman, please consider applying changes. It actually affects and "legacy" behavior: if one more super class was added - it can surprisingly used as main super-class.

**Comment by tglman** [comment]
hi @PhantomYdn,

Used linkedhashset in 2.2.x, removed in 3.x.

Closing this.

Regards
