### ISSUE TITLE
WHERE ANY() TRAVERSE(... Error parsing query

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#7461]
## Expected behavior  
Running : 
SELECT * FROM `Service` WHERE ANY() TRAVERSE(0, 3) ( ANY().toUpperCase().indexOf('danger') > -1 )

Where Service table exists and has 2 * vertex.

## Actual behavior  
Getting : 
<img width="1180" alt="screen shot 2017-05-30 at 15 43 34" src="https://cloud.githubusercontent.com/assets/4742672/26604092/cc49d6be-454e-11e7-8b02-830aa30e670e.png">
Or:
<img width="617" alt="screen shot 2017-05-30 at 15 44 07" src="https://cloud.githubusercontent.com/assets/4742672/26604131/f4f7f1a4-454e-11e7-9ff7-24e10e57a9e7.png">

Why am I getting this error ? Thanks

**Comment by luigidellaquila** [comment]
Hi @petervavro 

Please, DON'T DO THAT!!! The `traverse()` operator is deprecated in v 2.2 and the new parser does not support it (See http://orientdb.com/docs/2.2.x/SQL-Traverse.html#deprecated-traverse-operator). You can still use it setting `stringSql=false` in the db configuration, but it's highly discouraged.

Thanks

Luigi

**Comment by petervavro** [comment]
Thank you. What does replace this operator, please ?

**Comment by luigidellaquila** [comment]
You have many alternatives, eg. you can use a `MATCH` statement with a `while` condition, see 

http://orientdb.com/docs/2.2.x/SQL-Match.html

Thanks

Luigi

**Comment by petervavro** [comment]
Thank you !
