### ISSUE TITLE
Orient 3.0 - Using functions

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7462]
## Expected behavior  
function should work fine, not sure If I am doing anything wrong.  I wanted to place my logic into a function and use it. 

Do the "save" supposed to validate the code for function and throw error or is that something that should happen only on executing it?

## Actual behavior  
Error observed.
![function error](https://cloud.githubusercontent.com/assets/342691/26609648/277aa0a6-4557-11e7-9475-009fdec9b440.PNG)

 

## Steps to reproduce  

```
LET $p = (MATCH {class:Person, as:m, where:(id= $participantId)},{as:m} RETURN m);
SELECT  (EXPAND($p.m));
```

Error is 
`{
    "errors": [
        {
            "reason": 500,
            "code": 500,
            "content": "com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.(MATCH {class: Person, as: m, where: (id = $participantId)}, {as: m} RETURN m)\r\n\tDB name=\"mlm\""
        }
    ]
}`

Attached the screenshot.

**Comment by luigidellaquila** [comment]
Hi @careerscale 

Let me check it. I'm not sure that SQL functions support batch scripts, but probably the problem is only in the parentheses around the MATCH statement, probably the following will work fine:

```
LET $p = MATCH {class:Person, as:m, where:(id= $participantId)},{as:m} RETURN m;
SELECT  (EXPAND($p.m));
```

**Comment by careerscale** [comment]
Hi @luigidellaquila ,

thanks. that made it better. still errors out.

setting up person


```
orientdb {db=mlm}> create class Person extends V;

Class created successfully.

orientdb {db=mlm}> CREATE Property Person.id integer;

Property created successfully.

orientdb {db=mlm}>
```
Function looks  like

```
LET $p = MATCH {class:Person, as:m, where:(id= $participantId)},{as:m} RETURN m;
SELECT  (EXPAND($p.m));
```



now it says `{
    "errors": [
        {
            "reason": 500,
            "code": 500,
            "content": "java.lang.IllegalArgumentException: Field name is empty"
        }
    ]
}`

**Comment by luigidellaquila** [comment]
Hi @careerscale 

Here is the correct syntax for the function body:

```
LET $a = MATCH {class:Person, as:m, where:(id = :participantId)} RETURN m;
select expand($a.m);
```

Please note the `:participantId` for the input parameter and the fact that I removed the parentheses around `expand()`

Thanks

Luigi

**Comment by careerscale** [comment]
Thanks @luigidellaquila
