### ISSUE TITLE
Orient 3.0 - Question on traversal query or gremlin api traversal

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7463]
## Question  

We have lot of traversal and updating along with traversal and with some business logic around it.   We are trying to write queries with MATCH and TRAVERSE and updating the data, but we  are running into issues either with our limited knowledge (of few weeks of orientdb)  or that there could be snapshot issues.

Other option i am thinking is to leverage on vertex and edges and the apis around it to traverse and update the data as needed.

Which one is better and recommended? should we write queries or manipulate the graph objects directly?

(Assuming embedded db with clustering is used).

**Comment by careerscale** [comment]
@luigidellaquila , @lvca  could you please suggest on this?

**Comment by luigidellaquila** [comment]
Hi @careerscale 

If you are running embedded, the APIs will give you the advantage of being much more flexible.
You can also work with a mix of SQL and APIs, eg fetch the root vertices with SQL and then do the traversal using the APIs.

On the other hand, if you are working with a remote connection, the SQL will be much more efficient as the APIs will have to do multiple remote calls to do simple traversals, so in this case I'd suggest to go with SQL

Thanks

Luigi

**Comment by careerscale** [comment]
Thanks @luigidellaquila,  yes, we are going with this approach.
