### ISSUE TITLE
JSON-standard exponential notation not accepted by OrientDB

### ISSUE THREAD

**Issue by kived** [orientechnologies/orientdb#7468]
## Expected behavior  
OrientDB accepts values in exponential notation.

## Actual behavior  
Values in exponential notation are either ignored or cause an error, further details in next section.

## Steps to reproduce  
All tests performed in Studio or with pyorient using query strings.

`create vertex dummy set a=1e-100`
result: record created, a is `null`

`create vertex dummy set a=[1e-100]`
result: record created, a is `["_NOT_PARSED_"]`

`create vertex dummy set a={"value": 1e-100}`
result: record NOT created, error: `com.orientechnologies.orient.core.exception.OCommandExecutionException: expression item '1e-100' cannot be resolved because current record is NULL`

My primary concern is with the third test above, and how I noticed the issue. This exponential notation is part of the JSON standard, and is produced by the JSON tools I tested (JSON.stringify() in Chrome, json.dumps() in Python). This means that I cannot easily create a record in OrientDB with a map which contains very large or small floating-point numbers.

**Comment by luigidellaquila** [comment]
Hi @kived 

Exponential notation is not supported in v 2.1 (btw, please migrate to 2.2, it's much more stable).
The support for this will be available in v 3.0 and it's already in the 3.0M1.
Just consider that floating point numbers are represented as java Float numbers, so 1e-100 will be rounded to zero. If you want double precision numbers you have to add a D at the end, eg.

create vertex dummy set a=1e-100D

Thanks

Luigi
