### ISSUE TITLE
OrientDB 3.0 issue with latest snapshot - com.orientechnologies.orient.core.exception.OConcurrentCreateException: Cannot create the record #17:0 because the assigned RID was #17:1 instead  DB name="testdb"  DB name="testdb"

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7470]
## Expected behavior  
Should be able to retrieve and build edges with existing data.

## Actual behavior  
throws this error and fails. Resulting in application failing. 
com.orientechnologies.orient.core.exception.OConcurrentCreateException: Cannot create the record #17:0 because the assigned RID was #17:1 instead
 DB name="testdb"
 DB name="testdb"

## Steps to reproduce  
create a db
https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/resources/testdb.sql

run the tests.
https://github.com/careerscale/orientdb-demo/blob/1d34326456df2f249a216044f147df4d5101579f/orientdb-java-sample/src/test/java/com/orientdb/samples/test/EmployeeCascadeTest.java

Run again  this test `testDbTransactionOperations_Working`

This fails.

we are blocked with this and any quick help will unblock our team. 

Thanks.
Harinath

**Comment by careerscale** [comment]
@maggiolo00  @lvca  can you please prioritize this one and I am available for any additional informaiton.

**Comment by maggiolo00** [comment]
Hi @careerscale 

let me check it

Thanks

**Comment by maggiolo00** [comment]
Hi @careerscale 

i've tested it and i got no exception.

Which exception did you get?

**Comment by careerscale** [comment]
`com.orientechnologies.orient.core.exception.OConcurrentCreateException: Cannot create the record #17:0 because the assigned RID was #17:1 instead DB name="testdb" DB name="testdb"`

and nothing much, but result is it doesn't work. it doesnt create data.

**Comment by maggiolo00** [comment]
ok i got it on the second round

**Comment by careerscale** [comment]
correct. you got it

**Comment by careerscale** [comment]
@maggiolo00  is this going to be trivial fix or will it take longer time?

**Comment by maggiolo00** [comment]
hi @careerscale 

i'm running tests now for the fix. I will keep you updated

**Comment by careerscale** [comment]
Thank you @maggiolo00

**Comment by maggiolo00** [comment]
Hi @careerscale 

i've provided a fix with a test case in develop. 
Your test case now passes
Thanks

**Comment by careerscale** [comment]
This worked fine but there is no snapshot yet

**Comment by luigidellaquila** [comment]
Hi @careerscale 

The snapshot is not being generated because we have a couple of failing tests.
We are working to fix them, so the snapshot will likely be available in a few hours

Thanks

Luigi
