### ISSUE TITLE
New SQL HA UPDATE SERVER to change server role at run-time

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#7471]
This command is needed in case the cluster topology need to be changed by modifying the server role from MASTER to REPLICA and vice-versa. This command could also change other setting of the server, so the proposed syntax is:

`HA SET ROLE <server> = <MASTER|REPLICA>`

**Comment by santo-it** [comment]
Implemented in v.2.2.22 Enterprise. 
Closing.
