### ISSUE TITLE
Orient 3.0 - Question on id generation

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7475]
## Question

Looks like latest change in Orient 3.0 clean up some of the client side stuff. 

Earlier this used to work.

(all vertices and edges in our model have id as auto generated from sequences).
Create vertex `a`, 

create vertex `b`

look up vertex `a` by its id 
and add edge `b` to `a`
commit.
But today it stopped working, it looks like  `a` has to be committed before it can be looked up.  We are OK with it, but just wanted to be sure that this is intended to be.

**Comment by luigidellaquila** [comment]
Hi @careerscale 

Could you please post the code snippet or the SQL script you are using for this?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @careerscale 

Any additional info on this? Is this issue still relevant?

Thanks

Luigi

**Comment by careerscale** [comment]
@luigidellaquila , yes it is a question still valid, not a sql query but java code query.

**Comment by luigidellaquila** [comment]
Hi @careerscale 

Could you please post the code snippet you use to create and look up the vertices?

Thanks

Luigi

**Comment by tglman** [comment]
hi @careerscale,

Just as additional info, the Vertexes instances cannot be moved across thread and if you want to refer to the same vertex from another thread you need to use the Identity ( `OrientVertex.getIdentity()` ) and reload the vertex from the graph in the other thread, as well the identity for new record can be used in a different scope than the transaction only after the transaction is committed, following isolation rules.

Regards

**Comment by careerscale** [comment]
Hi @tglman , I get that,  can you please explain the "across threads" comment?  I assume everything that I am doing is happening in a single thread. We are using spring for injecting our dao classes and we are sharing across the graph object for multiple private methods and managing the graph in single place (to create/commit/rollback/close etc).

**Comment by tglman** [comment]
hi @careerscale,

If you are not doing any multithread operation you should be safe, and yes with the usual spring based architecture you don't move instances from a thread to another at all, so it's safe.

Regard

**Comment by careerscale** [comment]
@tglman , thanks for the information. I think I am good here.
