### ISSUE TITLE
 ONeedRetryException : Cannot UPDATE the record #7:3 because the version is not the latest.

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7477]
## Expected behavior  
Application should work fine all the time.

## Actual behavior  
randomly we run into this issue, not sure what is causing it.  work around we are using now is to restart the db and application. Otherwise we are struck actually. 

com.mycompany.myapp.service.internal.AbstractBaseService - ONeedRetryException : Cannot UPDATE the record #7:3 because the version is not the latest. P
robably you are updating an old record or it has been modified by another user (db=v18 your=v17)
        DB name="dbName"
        DB name="dbName"

Another one is  here
`om.orientechnologies.orient.core.exception.OSerializationException: Found null entry in ridbag with rid=#142:-3
        DB name="mlm"
        at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.serialize(OEmbeddedRidBag.java:424)
        at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:269)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serializeValue(ORecordSerializerBinaryV0.java:761)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:383)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:111)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:3553)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1274)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:545)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:110)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2593)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.close(ODatabaseDocumentEmbedded.java:271)
        at com.orientechnologies.orient.server.OClientConnection.close(OClientConnection.java:72)
        at com.orientechnologies.orient.server.OClientConnectionManager.disconnect(OClientConnectionManager.java:337)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeClose(OConnectionBinaryExecutor.java:136)
        at com.orientechnologies.orient.client.remote.message.OCloseRequest.execute(OCloseRequest.java:47)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:252)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:176)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
$ANSI{green {db=mlm}} Exception during commit of active transaction`

		

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @careerscale 

Thank you for reporting, I'm forwarding it to the storage team for a check

Thanks

Luigi

**Comment by taburet** [comment]
Hi @careerscale, regarding the first issue, it's pretty normal to receive such kind of exceptions in a concurrent environment since OrientDB uses MVCC. The common pattern of handling of such situations is to catch ONeedRetryException, reload the record/document from the database, reapply the changes to it and try to save it again.  If you sure you are not updating the same record from two different threads/connections and handling the ONeedRetryException/OConcurrentModificationException correctly, please elaborate more on your usage scenario.

Regarding the second issue, please provide the log file(s), there must be more information from where this null entry is came from.

**Comment by careerscale** [comment]
There was no concurrency and for regular use (developer was running a flow in order and ran into this), this might be unexpected right? I am running the DB and the application in same computer with no concurrency..

will try to reproduce the issues with unit test and come back. I found unit tests helped for easier resolution.

**Comment by ozgursucu** [comment]
Hi @taburet 
I am also facing this issues in orientdb 2.2.21 whereas in 2.2.19 everything was fine.

**Comment by laa** [comment]
Hi @ozgursucu . Are you able to reproduce this issue on your side?

**Comment by ozgursucu** [comment]
Hi @laa 
I tried to upgrade orientdb from 2.2.19 to 2.2.21 and there was not any changes expect the client version.Although I set ridBagEmbedded system property to Integer.MAX_VALUE and there is nothing related to concurrency I got exceptions regarding the edge creation in my transaction.

**Comment by laa** [comment]
@ozgursucu that is because you started to use embedded ridbag anywhere instead of the separate data structure so now every time you when creating edge you also update underlying documents of related vertexes. if you start to use a separate data structure for ridbag support this exception will be gone.

**Comment by ozgursucu** [comment]
@laa I have already been using the ridBag property (<entry name=“ridBag.embeddedToSbtreeBonsaiThreshold” value=“2147483647" />) and it is suggested in this document (https://orientdb.com/docs/2.2/RidBag.html) for distributed environments. What is the difference between 2.2.19 and 2.2.21?

**Comment by laa** [comment]
@ozgursucu I am trying to clarify an issue. So both in 2.2.19 and 2.2.21 you set a value of property ridBag.embeddedToSbtreeBonsaiThreshold  to 2147483647. Is it correct? Also in both cases, you are sure that all operations were performed in a single thread? Is my understanding correct?

**Comment by ozgursucu** [comment]
@laa yes it is totally correct

**Comment by laa** [comment]
I see.  Thank you. More questions )). Is this exception thrown in distributed mode or in standalone mode?

**Comment by ozgursucu** [comment]
Distributed mode.

**Comment by laa** [comment]
@ozgursucu could you try the same in standalone mode? I am asking because we need to separate modules which cause this problem.

**Comment by ozgursucu** [comment]
Ok. I will try and let you know.

**Comment by ozgursucu** [comment]
Hi @laa In standalone mode everything is fine.

**Comment by laa** [comment]
Thank you, @ozgursucu  will assign an issue to distributed team so they will check protocol and fix it.

**Comment by laa** [comment]
@careerscale I am not sure if you work in the same team with @ozgursucu or not. If you able to reproduce this issue on the standalone server please let us know. Would be cool also if you provide a test so we will be able to reproduce it too.

**Comment by ozgursucu** [comment]
@laa We are not in the same team with @careerscale.  Note that I am using ROUND_ROBIN_CONNECT remote connection strategy. Today I also sometimes faced a problem about this exception even if there is single process in the db and i simply delete vertexes.
<img width="1130" alt="screen shot 2017-06-16 at 09 23 48" src="https://user-images.githubusercontent.com/15319587/27214727-8bcdc6c4-5276-11e7-81e2-e5bca2280bc3.png">

**Comment by ozgursucu** [comment]
And I also see that There are replication problems and the system does not replicate the vertexes to the other server.

**Comment by lvca** [comment]
@ozgursucu the replication part in 3.0 wasn't updated with last things from 2.2.x. We're doing this right now and it will be part of 3.0-M2 that we will release in 2 weeks.

**Comment by ozgursucu** [comment]
@lvca The problems that I reported comes from 2.2.21.

**Comment by lvca** [comment]
@ozgursucu we fixed an issue on delete vertex in current 2.2.x branch. It will be out next week as 2.2.22, but it would be awesome if you could already test this by using latest 2.2.22-SNAPSHOT.

**Comment by ozgursucu** [comment]
@lvca  and what about the concurrent modification exception when adding edges?

**Comment by KishoDai** [comment]
I also encountered the same issue in distributed mode.

**Comment by careerscale** [comment]
I think this is reproduceble with stand alone mode too. we see this issue.  with time crunch bit hard to reproduce in stand alone unit tests,

**Comment by ozgursucu** [comment]
Hi @laa  Any progress about this issues?

**Comment by KishoDai** [comment]
Any progress about this issue?

**Comment by lvca** [comment]
Hi guys, this case must be managed by using a catch/retry strategy, like described in the docs; https://orientdb.com/docs/2.2/Java-Multi-Threading.html#multi-version-concurrency-control.

**Comment by careerscale** [comment]
I haven't seen this recently with 3.0. so may be good for me.  If I run into specific isues will come back

**Comment by ozgursucu** [comment]
Hi @lvca As I said before there is anything related to multithreading. I have single thread managing transactions and I encountered this problem in 2.2.21. Is 2.2.22 usable right now? I want to try with 2.2.22.

**Comment by careerscale** [comment]
@lvca  @ozgursucu  I think I see this issue with 3.0 snapshots too.  It was more obvious with distributed mode but  saw in stand alone mode too.  FYI.

I think I have a private ticket to track it anyway.

**Comment by laa** [comment]
@careerscale private ticket will make tracking only worse if you do not have some sensitive information of course. If you completely sure that you have got CME in standalone mode I will add some logging to discover the problem. But CME was implemented in version 0.1 I suppose and never changed since there so I have big doubts that problem in the standalone version. Anyway, let see.

**Comment by ozgursucu** [comment]
Any updates?

**Comment by luigidellaquila** [comment]
Hi @careerscale @ozgursucu 

is this issue related to the fixes we delivered in last few days? 
Do you still see this problem?

Thanks

Luigi

**Comment by careerscale** [comment]
@luigidellaquila , with 3.0 looks like I don't have issue. let me close this ticket
