### ISSUE TITLE
Support for SPDY protocol [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#748]
This is [Issue 748](http://code.google.com/p/orient/issues/detail?id=748) moved from a Google Code project.
Added by 2012-03-12T20:12:44.000Z by [l.garu...@gmail.com](http://code.google.com/u/111607061083712272202/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v1.5

### Original description

    http://dev.chromium.org/spdy/spdy-whitepaper

**Comment by StanAccy** [comment]
Given that Google is dropping support for this (in favor of HTTP2) is this support needed?

**Comment by lvca** [comment]
You're right, this is remained old. Closing it...
