### ISSUE TITLE
OrientDB Bidirectional Edges

### ISSUE THREAD

**Issue by MessCo** [orientechnologies/orientdb#7483]
Is there a way to create bidirectional relationship in orientdb using ETL? 
For example:
(ProteinA)<-[PPI]->(ProteinB)
If not how can I create two unidirectional edges in both directions in my Json file?
For example:
(ProteinA)-[PPI]->(ProteinB)
(ProteinA)<-[PPI]-(ProteinB)

**Comment by robfrank** [comment]
Edges are always bi-directional inside OrientDB. A vertex has in and out edges, is up to you how to model the relationships.
