### ISSUE TITLE
OIndexException when trying to use index partially

### ISSUE THREAD

**Issue by karolmie1** [orientechnologies/orientdb#7484]
## Scenario:

```
CREATE CLASS User extends V
CREATE PROPERTY User.login STRING (MANDATORY TRUE, NOTNULL)
CREATE PROPERTY User.permissions EMBEDDEDSET STRING (MANDATORY TRUE, NOTNULL)
CREATE INDEX User_Login_Perm on User(login, permissions) UNIQUE

// not entirely sure if a few vertices needed to reproduce. If not getting an error, please insert one or 2.

graph.getVertices("User", ["login"], ["admin"])
```
Result:

> ! com.orientechnologies.orient.core.index.OIndexException: Impossible add as key of a CompositeIndex a value of type class java.lang.String
> ! DB name="fragaria"
> ! at com.orientechnologies.orient.core.index.OCompositeCollate.transform(OCompositeCollate.java:62)
> ! at com.orientechnologies.orient.core.index.OIndexAbstract.getCollatingValue(OIndexAbstract.java:945)
> ! at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:47)
> ! at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:40)
> ! at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:58)
> ! at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:262)
> ! at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:40)
> ! at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertices(OrientBaseGraph.java:907)

**Comment by karolmie1** [comment]
By the way, I have other index: ` CREATE INDEX User.login UNIQUE_HASH_INDEX`

I try to circumvent the problem above, by using this index directly: `graph.getIndex("User.login", Vertex::class.java)`, but this return null.

After debugging I've found, that index is found, but it has metadata = null, and that causes the function to return null.

**Comment by laa** [comment]
Fixed
