### ISSUE TITLE
different (incorrect) behaviour of "eval" when sent via REST versus plain CLI

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7485]
## Expected behavior  
The sql 
```SELECT 10 AS p1, eval("10 + 1") AS p2``` 
should return p1=10 and p2=11

## Actual behavior  
1) when sent via web-GUI, the results are correct:
```
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:1",
            "@version": 0,
            "p1": 10,
            "p2": 11
        }
    ],
    "notification": "Query executed in 0.042 sec. Returned 1 record(s)"
}
```
2) when sent via the console.sh, the results are correct:
```
orientdb {db=mobile}>  SELECT 10 AS p1, eval("10 + 1") AS p2
+----+----+----+
|#   |p1  |p2  |
+----+----+----+
|0   |10  |11  |
+----+----+----+
```
3) when sent via the REST-API (from Perl) the results are WRONG:
```
$x = "select 10 AS p1, eval(\"10 + 1\") AS p2" ;
$sql_encoded = $x;
$sql_encoded =~ s/([^A-Za-z0-9\+-])/sprintf("%%%02X", ord($1))/seg;
$dbh->GET("/query/mobile/sql/". $sql_encoded ."/5000000", $self->{'httpHeaders'});
$results = $dbh->responseContent();
print $results ;
-> {"result":[{"@type":"d","@rid":"#-2:1","@version":0,"p1":10,"p2":10}]}
```
The encoded SQL string is correct, because when I reverse the encoding, I get exactly the same original SQL statement again:
```
$y = $sql_encoded ;
map { $c = chr(hex($_)); $y =~ s/%$_/$c/g } (qw(09 0A 20 22 25 27 28 29 2C 2E 3D 5F 7C)) ;
print $y ;
-> select 10 AS p1, eval("10 + 1") AS p2
```

I cannot try to reproduce this with Java, but I leave that exercise to the Java gurus.

**Comment by rdelangh** [comment]
hello gurus,

any feedback on this issue, please ?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

sorry, I still had no chance to try it out, but I suspect that the problem is in the parsing of the script by the HTTP layer.

I'll try to give it a try today and let you know

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

in your regex you are also leaving the `+` signs unencoded. The + is considered as a blank space in an HTTP URL, so you have to encode it as well, eg. change the script as follows:

```
$sql_encoded =~ s/([^A-Za-z0-9\-])/sprintf("%%%02X", ord($1))/seg;
```

I'm pretty sure that OrientDB behavior is correct, as it's just using Java URLDecoder do decode the URL, that is a standard API...

Thanks

Luigi
