### ISSUE TITLE
ETL extractor is not parsing csv file properly

### ISSUE THREAD

**Issue by easy2coderep** [orientechnologies/orientdb#7493]
## Expected behavior  
The csv data should be parsed as it is available while importing from csv.  

## Actual behavior  
The data available in the CSV is not parsed as it is, and it been modified. The below data I am facing issue with
1. When the data is number is started with 0 , eg. 02323, 008898, 0887373 . initial 0 is been truncated
2. When the data is of format 10-0-110-253.xx.yy.zz_Index1, the CSV read it as date 
[csv] DEBUG document={name:Thu Mar 20 00:00:00 IST 10,xxxxxx,xxxxx}

To add my json configuration
 "source":{"file": { "path": "/temp/config/data.csv" } },
        "extractor": { "csv": {} },
        "transformers": [
        { "vertex": { "class": "MyObject" } } 
],

## Steps to reproduce  
Create a CSV and have the data as below 

00232442
023424
04454
10-0-110-253.ee.ee.ee.
10-0-10-253

**Comment by robfrank** [comment]
The CSV extractor tries to guess the type of the column, so a number like 00010 is mapped to an INTEGER. to overcome this problem, define the type of the columns:

```json
{ "csv": 
    {  "predefinedFormat": "DEFAULT",
       "nullValue" : "N/A",
       "dateFormat" : "dd-MM-yyyy",
       "dateTimeFormat" : "dd-MM-yyyy HH:mm",
       "columns": ["name:string","createdAt:date","updatedAt:dateTime"]
    }
}
```

The example is taken directly from the documentation
http://orientdb.com/docs/last/Extractor.html#csv-extractor

**Comment by easy2coderep** [comment]
Thank you robfrank.
Also could you please let me know if there is any option to ignore duplicate entries and continue with CSV import ?

**Comment by robfrank** [comment]
If you are mapping to Vertexes, the vertex transformer could be configured to skip duplicates: http://orientdb.com/docs/last/Transformer.html#vertex-transformer

Read carefullly the documentation.

**Comment by easy2coderep** [comment]
I did went thro the documentation, but couldn't get any input when searched with duplicate word. 
Thank you for the help.
