### ISSUE TITLE
Orient DB Pagination along with Filtering specific key issue.

### ISSUE THREAD

**Issue by thanveeraqtharah** [orientechnologies/orientdb#7495]
## Expected behavior  
I want to query records based on a specific  searchvalue within the document field and also want to implement pagination in the same query. Below is the query  

```
select from <DOCUMENTNAME> let $tmp = (select from (select expand(<FIELDNAME>) from <DOCUMENTNAME>  ) where any() like '%<SEARCHVALUE>%' ) where <FIELDNAME> in $tmp.value SKIP <records-to-skip> LIMIT <max-records>
```
 
The above query return no result set. Is it  because that skip and limit does not work on temporary  variable?

Feedback will be appreciated as I am new to orientDB. Thank you 

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @thanveeraqtharah 

Could you please post a valid query and a script to create a sample schema/db?
It's really hard to help you knowing nothing about the domain and the query you are trying to do...

Thanks

Luigi

**Comment by thanveeraqtharah** [comment]
Sorry  I had posted the valid query , guess because I had used angle bracket within the query, it skipped the value. and below is the query.

select from DOCUMENTNAME let $tmp = (select from (select expand(FIELDNAME) from DOCUMENTNAME  ) where any() like '%SEARCHVALUE%' ) where FIELDNAME in $tmp.value SKIP 495 LIMIT 5

**Comment by luigidellaquila** [comment]
Ah, got it ;-)

Little hint, you can use Markdown syntax here, it helps a lot for code snippets: https://guides.github.com/features/mastering-markdown/

First of all: why v 2.1.19? It's not supported anymore and last 2.2.21 is much more performant and stable.
The query you posted seems to be correct, the problem could be in the `any()` expression (maybe an old bug?) or somewhere else. Did you try to execute the single sub-select statements and see what they return?

Thanks

Luigi

**Comment by thanveeraqtharah** [comment]
Thank you for the  suggesting Markdown syntax  as well for the newer stable version info. Definitely I ll take that into consideration.
When I tried to use 2.2.21 , i.e 
artifactId :  orientdb-server
version : 2.2.21
the below exception was thrown 
Exception in thread "main" java.lang.NoClassDefFoundError: com/orientechnologies/orient/core/security/OSecuritySystem

Now coming back to query part, if  I use the same query without SKIP and LIMIT i.e 
select from DOCUMENTNAME let $tmp = (select from (select expand(FIELDNAME) from DOCUMENTNAME  ) where any() like '%SEARCHVALUE%' ) where FIELDNAME in $tmp.value 

Its returns filtered query as expected. But when I try to implement pagination on it. It doesnt return any result set. So  its not them problem is in any() expression. So what might be the problem?

**Comment by luigidellaquila** [comment]
It's a good question, it's really hard to tell without a db to reproduce the problem.
You can try to narrow the scope of the problem adding a simple LIMIT 1, then a simple SKIP 1 and see if it still returns no records.

Any chance to have a screenshot or a dump of the query result without the skip/limit?

Thanks

Luigi

**Comment by thanveeraqtharah** [comment]
1.First of all, I wana thank you for your support and immediate responses, impressive. :-) 
I got to know what was happening . As it was huge data and as SKIP and LIMIT way is slower, because OrientDB repeats the query and just skips the first X records from the result. and it was returning zero records because there was no records containing the searchvalue in the given skip and limit.

There is other way for pagination which is RID-LIMIT , but since im new to OrientDb, I am not sure what this RID represent. I mean earlier for SKIP value i used to give skipvalue =(pageno-1)*pagesize . Where pageno is nothing but on which page filter should be applied and pagesize is nothing but LIMIT value.

Can you please help me with this that my pagination will be faster.

2. For filtering with searchvalue, I am using "  any() like '%"+searchvalue+"%' ". I want to implement ignorecase of searchvalue. i.e the searchvalue shouldnt  be case sensitive. Can u help with this too ?

Thank you :)

**Comment by luigidellaquila** [comment]
Hi @thanveeraqtharah 

The only other alternative for pagination (apart the two you mentioned above) is using another filter by a property (eg. an ID or a sequence number), index it and then do a range query on it.

About the case insensitive search, IMHO the best thing you can do is using a Lucene index: http://orientdb.com/docs/2.2.x/Full-Text-Index.html

Thanks

Luigi

**Comment by thanveeraqtharah** [comment]
Ok I will give you the clear picture of db.
 1.There is Document By Name "ds_records".
 2. This Document has 3 fields namely 'appid','sourceid' and 'records'
 and I am saving the data to the above Document as shown below
 
 private void saveRecords(String documentName,List`<Map`<String, String>`>' records, String appId, String sourceId) {
		
		for(Map`<String, String>` record : records){
			// create a document and save in db
			ODocument doc = new ODocument(documentName);
			doc.field("appid", appId);
			doc.field("sourceid", sourceId);
			doc.field("records", record);
			// SAVE THE DOCUMENT
			doc.save();
		}
		
	}
	
	where records field will save Map'<String,String>`.
	
	So I want to filter all the records based on the searchvalue , which is inside records field i.e searchvalue in other words will be map value. How to create a index for the above db structure. And what about clusters?. Will that improve the search performance too? . Sorry as I am new to OrientDb, Im  not able get what you have said i.e "another filter by a property (eg. an ID or a sequence number), index it and then do a range query on it."
	
	Feedback will be appriciated.
	
	Thanks
