### ISSUE TITLE
Error on addVertex with mandatory fields

### ISSUE THREAD

**Issue by hanksieM** [orientechnologies/orientdb#7496]
## Expected behavior  
call to framedGraph.addVertex returns an empty instance that mandatory fields can then be populated prior to a commit.

## Actual behavior  
the call framedGraph.addVertex( class) attempts to save the instance but fails due to missing mandatory fields.

## Steps to reproduce  
Upgrading a Play application that uses Java (not Scala) from Orientdb-2.2.15 to orientdb-2-2-21 and I'm having a problem with addVertex.  The error I get is in the main application but when running unit tests where each test starts OrinetDB as an embedded server using an in-memory "testDb".

Here's the wrapper code for the update :

OrientGraphConnectionHandlerIF connPool;
        
 @Inject
 public GraphTransactionManager(OrientGraphConnectionHandlerIF connHandler) {
            connPool = connHandler;
 }

        public T runWithCommit(withGraphConnection<T> runnable) {
               
                FramedGraph<OrientGraph> graph = connPool.getFrameGraph();
              T result = null;
                try {
                   result = runnable.run(graph);
                   graph.getBaseGraph().commit();
          } catch(Exception e) {
                  graph.getBaseGraph().rollback();
                        Logger.error(String.format("Error in graph transaction manager while running with commit: "), e);
           throw e;
           } finally {
                     graph.getBaseGraph().shutdown();
                }       
                return result;
          
        }

And here's lambda code that fails (arrHandler is an instance of the above where the Template T is an array).  I've commented the line 71 and 74 mentioned in the stack trace shown later:

    @Override
   public DeletionDTO createDeletionFromInstance(String instanceId, DeletionDTO deletionDTO) throws Exception {

        return handler.runWithCommit((graph) -> {                                                          //this is line 71

            // create and map the initial values
           DeletionGraph deletionGraph = graph.addVertex( "class:DeletionGraph", DeletionGraph.class);    // this is line 74

            //set the status and ID (this will overwrite anything set in the DTO)
           deletionGraph.setUniqueIdentifier( deletionGraph.generateUniqueIdentifier() );
           deletionGraph.setDeletionStage( DeletionStatus.NEW_UNCOMMITTED.getStatus());

            //get the mandatory fields
           deletionGraph.setUniqueIdentifier( deletionGraph.getUniqueIdentifier());
           deletionGraph.setDeletionType( deletionDTO.getDeletionType().toString());
           deletionGraph.setDeletionApprovalDate( deletionDTO.getDeletionApprovalDate());
           deletionGraph.setDDFReference( deletionDTO.getDDFReference());
           deletionGraph.setDeletionDescription( deletionDTO.getDeletionDescription());

            //add the actors
           deletionGraph.setCreatedBy(createActor(deletionDTO.getCreatedBy(), graph));

            //assign the asset instance edge/adjacency
           Iterable<AssetInstanceGraph> foundAssetInstances = graph.getVertices( "AssetInstance." + UNIQUE_IDENTIFIER, instanceId, AssetInstanceGraph.class);
           AssetInstanceGraph assetInstance = foundAssetInstances.iterator().hasNext() ? foundAssetInstances.iterator().next() : null;
           deletionGraph.setDeletionFor( assetInstance );

            return new DeletionDTO(deletionGraph);
       });
   }

The stack trace appears to show the record being saved at line 74 when running with OrientDb 2.2.15 it did not. 

DB name="testdb"
        at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:229)
    at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2047)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2733)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:102)
 at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805)
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796)
    at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:333)
     at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:315)
     at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:571)
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:503)
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:75)
     at com.tinkerpop.frames.FramedGraph.addVertex(FramedGraph.java:242)
     at com.tinkerpop.frames.FramedGraph.addVertex(FramedGraph.java:258)
     at services.implementations.deletionservice.DeletionServiceImpl.lambda$createDeletionFromInstance$3(DeletionServiceImpl.java:74)
        at modules.database.graph.connection.GraphTransactionManager.runWithCommit(GraphTransactionManager.java:31)
     at services.implementations.deletionservice.DeletionServiceImpl.createDeletionFromInstance(DeletionServiceImpl.java:71)
```

**Comment by ggeremy** [comment]
Hello,

I was upgrading from 2.2.13 to 2.2.21 and I had a problem with addVertex(id).
The class has mandatory properties. And now I can't create an "empty" vertex.

`Caused by: com.orientechnologies.orient.core.exception.OValidationException: The field 'MyClass.myMandatoryField' is mandatory, but not found on record: MyClass
	DB name="MY_DB"
	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:229)
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2047)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2733)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:102)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:333)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:315)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:571)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:503)
`

**Comment by hanksieM** [comment]
I think we have a bug here - I'm just waiting to hear from the developers/orientdb.com

**Comment by ggeremy** [comment]
My code works well with OrientDB 2.2.14, 2.2.15 and 2.2.16.
But not working with 2.2.17 
It may help for investigation

**Comment by ggeremy** [comment]
I think I've found the problem.

In 2.2.16, in ODatabaseDocumentTx, the save method checked if there was a transaction before doc.validate() call.

In 2.2.17, doc.validate() is always called, transaction or not...

Hope I'm right ;-)

**Comment by tglman** [comment]
hi @ggeremy,

Yes your analysis is right and is done on purpose, because is correct to validate the data at the moment of the save also in case of TX, for your case of mandatory fields you have two solutions:

add the vertex with parameters:
```
Vertex vt =graph.addVertext("class:MyVtx", "mandatory","mandatoryValue");
```
or use the temporary vertext that is not saved till save
```
Vertex vt =graph.addTemporaryVertex("class:MyVtx");
// sets the properties
vt.save();
```

Hope it helps

**Comment by ggeremy** [comment]
hi @tglman,

It helped ;-)
But I have the same problem with Edge with mandatory fields.
I use frames 2.6.0 to add edge to vertex. 

Any tips to bypass the save process ?

Thanks

**Comment by tglman** [comment]
hi @ggeremy,

I'm not an expert of Frames, I checked but I couldn't find anything that could help on frames, you may evolve it adding temporary vertex support to frames.

Regards

**Comment by kevmegforest** [comment]
There's no way to bypass anything since that implementation is unworkable with any tinkerpop2 implementation (which is abstracting OrientDB). It would be preferable to keep the validation only at commit in the 2.2.x version range. I have the same problem using an other library (Ferma from syncleus)

Here are the related issues or commits that made the changes.

https://github.com/orientechnologies/orientdb/commit/96685c5f02b2f770d09a672885c2c738fdd75a9d
https://github.com/orientechnologies/orientdb/issues/7144
https://github.com/orientechnologies/orientdb/issues/7145

**Comment by tglman** [comment]
hi @kevmegforest,

I understand your point, anyway keeping the check only in commit time will make the behaviour of the save in noTx database not the same of the save in Tx databases, that is a problem as well, probably is better propose some change downstream, to make everything more coherent.

**Comment by kevmegforest** [comment]
hi @tglman 

tinkerpop2 has been discontinued. There is no way to make a change downstream. Since it's OrientDB that has made the change which has broken the support for blueprints based software during it's 2.2.x support, I support that this change be made for the next major release (2.3.x or 3.x). Here's a patch that would work and pass all current tests.

```diff --git a/core/src/main/java/com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java b/core/src/main/java/com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java
index 861c1fb0bd..6e5ab3320f 100755
--- a/core/src/main/java/com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java
+++ b/core/src/main/java/com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java
@@ -2733,12 +2733,15 @@ public class ODatabaseDocumentTx extends OListenerManger<ODatabaseListener> impl
 
     ODocument doc = (ODocument) iRecord;
     ODocumentInternal.checkClass(doc, this);
-    // IN TX THE VALIDATION MAY BE RUN TWICE BUT IS CORRECT BECAUSE OF DIFFERENT RECORD STATUS
-    try {
-      doc.validate();
-    } catch (OValidationException ex) {
-      doc.undo();
-      throw ex;
+    // EXECUTE VALIDATION ONLY IF NOT IN TX
+    if (!getTransaction().isActive() || getTransaction().getStatus() == OTransaction.TXSTATUS.COMMITTING)
+    {
+      try {
+        doc.validate();
+      } catch (OValidationException ex) {
+        doc.undo();
+        throw ex;
+      }
     }
     ODocumentInternal.convertAllMultiValuesToTrackedVersions(doc);
 
```
