### ISSUE TITLE
Password format to reproduce the hash

### ISSUE THREAD

**Issue by tommasop** [orientechnologies/orientdb#7499]
I'd like to know how to check for a correct login matching the hashed password.

What is the actual saving format and what does each colon separated part means?

{used_algorithm}first_part:second_part:third_part

From what I can find online the third_part seems to be the number of iterations? Or the salt?

Can you share some insights please?

**Comment by tglman** [comment]
hi @tommasop,

well it depends on the algorithm, in case of `SHA-256` you just get `{algorithm}value`, in case of `PBKDF2WithHmacSHA1` and `PBKDF2WithHmacSHA256`  is `{algorithm}hash:salt:iterations`.

Hope this help.

Bye

is : {userd_algorithm}

**Comment by tglman** [comment]
forgetting a bit of more detail:

in case of `{algorithm}hash:salt:iterations`   
`hash` is the hexadecimal version of bytes
`salt` is the hexadecimal version of bytes
`iterations` is just the string version of the number of the iterations.

Bye

**Comment by tommasop** [comment]
Perfect! thanks
