### ISSUE TITLE
Performance inconsistency between equivalent MATCH queries

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#7501]
## Expected behavior  
The following two queries should have equivalent performance, since the `BETWEEN` operator, per the docs, is defined as a `<=` comparison plus a `>=` comparison. When a (non-hashed) index covers the `Foo.name` field, the index should be used for both queries.

```
MATCH {
    class: Foo,
    where: (name >= 'a' AND name <= 'z'),
    as: foo
} RETURN foo.name AS name
```

```
MATCH {
    class: Foo,
    where: (name BETWEEN 'a' AND 'z'),
    as: foo
} RETURN foo.name AS name
```

## Actual behavior  
When `Foo` has tens of thousands of entries, and with a non-hashed index covering `Foo.name`, the first query takes ~30-40s to run, whereas the second query runs in ~0.1-0.2s. My best guess is that the first query fails to use the index, but the second query uses the index. However, I am unable to confirm this, as `EXPLAIN MATCH` does not return information on which indexes were used.

Furthermore, this is inconsistent behavior even relative to the performance of the equivalent `SELECT` queries:
```
SELECT name FROM Foo WHERE name >= 'a' AND name <= 'z'
SELECT name FROM Foo WHERE name BETWEEN 'a' AND 'z'
```
Both of the above queries run in ~0.1-0.2s, just as the faster of the two MATCH queries. `EXPLAIN` also shows they both use the index.

## Steps to reproduce  
My schema looks like this:
```
CREATE CLASS AbstractBase EXTENDS V ABSTRACT
CREATE PROPERTY AbstractBase.name String
CREATE INDEX AbstractBase.name NOTUNIQUE

CREATE CLASS Foo EXTENDS AbstractBase
```

I also have tens of thousands of `Foo` vertices in my database.

**Comment by obi1kenobi** [comment]
It also appears that the fact that the index is on a superclass is important. The problem goes away if the index is defined on `Foo.name` instead of `AbstractBase.name`.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

Thank you very much for reporting, I'll check it and let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I just pushed a fix for this. The fix will be released in a few hours with 2.2.22

Thanks

Luigi

**Comment by santo-it** [comment]
Commit https://github.com/orientechnologies/orientdb/commit/e0a4578d014e8c856fe037bdeb9b1adac5fca1b8 - Noted in the Release Notes.

**Comment by obi1kenobi** [comment]
Sounds great, thank you!
