### ISSUE TITLE
Batching Multiple SELECTs without unionall()

### ISSUE THREAD

**Issue by TropicalPenguin** [orientechnologies/orientdb#7504]
## Expected behavior  
I would like to retrieve records from multiple selects independently, while avoiding round-trips.

unionall(), as suggested in #5429, gives a single heterogeneous collection of records. Rather than client-side logic to separate these, it would be nice to avoid the union in the first place.

The RETURN SELECT suggested in the documentation comes close, allowing for multiple homogeneous collections; but only collections of links, I can't figure out how to get full records. 

## Actual behavior  

`RETURN (SELECT $ayes,$bees,$cees)`, as below, returns links.

With expand(), it's posible to get records, but only for one SELECT. I guess I'm really looking for something like:

`RETURN (SELECT expand($ayes),expand($bees),expand($cees))`

## Steps to reproduce  
Given the following setup:
```
CREATE CLASS a EXTENDS V
CREATE CLASS b EXTENDS V
CREATE CLASS c EXTENDS V
```

I try the following:
```
BEGIN
CREATE VERTEX a
CREATE VERTEX a
CREATE VERTEX a
CREATE VERTEX a
CREATE VERTEX b
CREATE VERTEX b
CREATE VERTEX b
CREATE VERTEX c
CREATE VERTEX c
LET ayes = SELECT FROM a
LET bees = SELECT FROM b
LET cees = SELECT FROM c
COMMIT
RETURN (SELECT $ayes,$bees,$cees)
```

**Comment by luigidellaquila** [comment]
Hi @TropicalPenguin 

Unfortunately for now there is no support for multiple expand() in the same query. The resultSet is a single collection of documents, so it's pretty hard to do it in v 2.2.

Thanks

Luigi
