### ISSUE TITLE
OrientDB 3.0 - Multiple edges update in single transaction is missing out 1 change from commit

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7505]
## Expected behavior  
Within a single transaction, I  should be able to update multiple edges as needed.

## Actual behavior  
Looks like at least 1 record is not being updated correctly.

## Steps to reproduce  
https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/java/com/orientdb/samples/test/MultipleEdgeUpdatesTest.java

**Comment by maggiolo00** [comment]
Hi @careerscale 

i do not understand this update

```
graph.executeSql("Update PART_OF set status=1 where out.id=" + edge.value("id"), params);
```
You are updating an edge by filtering on the `out.id` with the `id` of the edge.
Both Country and PART_OF id are generated by sequence. 

How can they match?

**Comment by careerscale** [comment]
@maggiolo00  agreed, It was wrong in my unit test.  it  supposed to be ` graph.executeSql("Update PART_OF set status=1 where out.id=" + edge.outVertex().value("id"), params);`

test case passes with it, but  Let me recheck with code and come back to you.,

Thanks for pointing it out.

**Comment by maggiolo00** [comment]
Ok @careerscale 

 Thanks

**Comment by careerscale** [comment]
@maggiolo00 ,

I still need to reproduce this problem with unit test, its been bothering my team since couple of weeks. some weird behavior about why one edge doens't get saved. 

trying to get exact replica into demo project with spring boot in place. will come back

**Comment by maggiolo00** [comment]
Thanks @careerscale

**Comment by lvca** [comment]
@tglman do you have an opinion about this?

**Comment by tglman** [comment]
hi @careerscale, 

On this do you have news ? fixing the test cases seems to have fixed the problem isn't ?

Regards

**Comment by careerscale** [comment]
@tglman ,  my team member says he still sees this issue. will come back on wednesday.

**Comment by maggiolo00** [comment]
hi @careerscale 

do you have news on this issue?


Thanks

**Comment by careerscale** [comment]
@maggiolo00, not really. I think I will close this ticket and open when if I see this issue.
