### ISSUE TITLE
Impossible to select field in Chinese

### ISSUE THREAD

**Issue by oger-p** [orientechnologies/orientdb#7506]
## OrientDB Version, operating system, or hardware.
- v2.2.17
## Operating System
- Linux

## Expected behavior  

`Select 地點 From Town`

Return the field 地點 from the Vertex Town

## Actual behavior  

`Select 地點 From Town`

com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 8. Encountered: "\u5730" (22320), after : ""

## Steps to reproduce  

`Create a Vertex Town`
`Create a field named 地點 for the Vertex Town`
`Select 地點 From Town`

**Comment by luigidellaquila** [comment]
Hi @oger-p 

This seems to be a problem with the parser, I'll check it asap

Thanks

Luigi

**Comment by gzliudan** [comment]
Is there a plan in which version to fix this bug？

**Comment by luigidellaquila** [comment]
Actually I don't know if this can be considered a bug. Without back-tick, the only accepted characters are `A-Za-z0-9_$`, the purpose of the back-tick is exactly to allow any other character for identifiers. I guess we can just close this issue, unless you need further help...

Thanks

Luigi

**Comment by gzliudan** [comment]
After run below command:
CREATE EDGE `包含` FROM #26:0 TO #22:0
the edge name becomes %E5%8C%85%E5%90%AB in database, the right one should be 包含

**Comment by luigidellaquila** [comment]
Ok, the problem here seems to be at a lower level. Let me check it...

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @oger-p 

I just checked it, unfortunately this is a limitation of the schema in v 2.2, I cannot change it without breaking everything.
Good news is that this is already fixed in v 3.0, that will be RC in two or three weeks

Thanks

Luigi

**Comment by zchenack** [comment]
When Chinese used, I even cannot create a vertex named in Chinese.
com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 28.  Encountered: "\u821e"
UTF-8 is used by default in the python source file.
