### ISSUE TITLE
Cascading FETCHPLAN from LETs through RETURN [SELECT]

### ISSUE THREAD

**Issue by TropicalPenguin** [orientechnologies/orientdb#7508]
## Expected behavior  

When one or more LET variables represent SELECT(s) with fetch plan(s), I expect these fetch plans to be respected as these variables are referred to in the batch RETURN statement.

This is over the binary protocol.

_Note: All four cases under 'Steps to reproduce' use a single fetch plan, but I also suspect varying fetch plans - per-SELECT - should work too._

## Actual behavior  

In the simplest case (numbered '1', below, under 'Steps to reproduce'), the cache contains two items, respecting the FETCHPLAN.

The next three cases (2, 3, 4) all result in empty caches. In case 2, the `RETURN (SELECT ...)` seems to interrupt it. In case 3, the line `LET _ayes = SELECT $ayes.size() as size`.

Case 4 might be a combination of both...

## Steps to reproduce  

Given the following setup:
```
CREATE CLASS a EXTENDS V
CREATE CLASS b EXTENDS V
CREATE CLASS ab EXTENDS E
```

This batch returns the correct record, with two items in the cache, as expected:

1. Working case:

```sql
BEGIN
LET a = CREATE VERTEX a
LET b = CREATE VERTEX b
CREATE EDGE ab FROM $a TO $b
LET ayes = SELECT FROM a FETCHPLAN *:-1
LET bees = SELECT FROM b FETCHPLAN *:-1
COMMIT
RETURN $ayes
```

The following three batches return the correct record, but with **empty** caches, I suspect erroneously:

2:
```sql
BEGIN
LET a = CREATE VERTEX a
LET b = CREATE VERTEX b
CREATE EDGE ab FROM $a TO $b
LET ayes = SELECT FROM a FETCHPLAN *:-1
LET bees = SELECT FROM b FETCHPLAN *:-1
COMMIT
RETURN (SELECT $ayes)
```

and 3:

```sql
BEGIN
LET a = CREATE VERTEX a
LET b = CREATE VERTEX b
CREATE EDGE ab FROM $a TO $b
LET ayes = SELECT FROM a FETCHPLAN *:-1
LET bees = SELECT FROM b FETCHPLAN *:-1
LET _ayes = SELECT $ayes.size() as size
COMMIT
RETURN $ayes
```

and 4. This was the batch where I first encountered the problem. This returns the correct records but an empty cache. The two previous cases isolate two possible reasons this fails:

```sql
BEGIN
LET a = CREATE VERTEX a
LET b = CREATE VERTEX b
CREATE EDGE ab FROM $a TO $b
LET ayes = SELECT FROM a FETCHPLAN *:-1
LET bees = SELECT FROM b FETCHPLAN *:-1
LET _ayes = SELECT $ayes.size() as size
LET _bees = SELECT $bees.size() as size
COMMIT
RETURN (SELECT expand(unionall($_ayes,$ayes,$_bees,$bees)))
```

**Comment by TropicalPenguin** [comment]
Interestingly, removing the fetch plan from the second select also results in an empty cache, which suggests there may be problems using different fetch plans per-select:

```
BEGIN
LET a = CREATE VERTEX a
LET b = CREATE VERTEX b
CREATE EDGE ab FROM $a TO $b
LET ayes = SELECT FROM a FETCHPLAN *:-1
LET bees = SELECT FROM b
COMMIT
RETURN $ayes
```

**Comment by luigidellaquila** [comment]
Hi @TropicalPenguin 

Fetchplan in batch scripts are not fully supported, I suggest you to apply them to the RETURN statement, eg.

```
BEGIN
LET a = CREATE VERTEX a
LET b = CREATE VERTEX b
CREATE EDGE ab FROM $a TO $b
LET ayes = SELECT FROM a FETCHPLAN *:-1
LET bees = SELECT FROM b FETCHPLAN *:-1
LET _ayes = SELECT $ayes.size() as size
LET _bees = SELECT $bees.size() as size
COMMIT
SELECT expand(unionall($_ayes,$ayes,$_bees,$bees)) FETCHPLAN *:-1
```

Thanks

Luigi

**Comment by TropicalPenguin** [comment]
Thanks for the response @luigidellaquila, I've adjusted https://github.com/mogui/pyorient/commit/4adc3b004a064923b2002b60c83d20e47b0a7c2a to take account of this.

Could this be taken as a (I guess low priority) feature request, though? Without this, the RETURN fetch plan must always be the most permissive of all individual SELECT's desired fetch plan(s).

**Comment by luigidellaquila** [comment]
Hi @TropicalPenguin 

Ok, I'm reopening and marking as a feature request, but I cannot give you an ETA for this...

Thanks

Luigi

**Comment by lvca** [comment]
In 3.0 we removed fetchplans in favor of the more flexible projections.
