### ISSUE TITLE
HA: Improve Java client policy

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#7509]
The auto-reconnect feature of the Java driver is cool, but we need some behavior to be configurable:
- A client could start with one or a list of servers and it could be stick on them
- HA & DC: In case of DC configuration, could be nice a constraint where the client can connect only to another server on the same DC

New settings to specify as OGlobalConfiguration. In v3.0 and major this could be specified also per database.

```
NETWORK_BINARY_AUTO_RECONNECT_STRATEGY("network.binary.autoReconnectStrategy",
      "Strategy to use in case of reconnection", String.class, "auto", true),
```

The available values will be: `auto|disabled|sameserver|list{<server>}|samedc|dc:{<dcname>}`.

Examples:

- `auto` (the default) -> select a server from the same DC (if any), then from any other DCs
- `disabled` -> never reconnects once the connection is lost
- `sameserver` -> will try to reconnect only to the current server
- `list{europe1:2424,europe2:2424,usa3}` -> will try to reconnect only to the servers in the list between curly braces
- `samedc` -> will try to reconnect to another server in the same DC
- `dc{asia}` -> will try to reconnect only to a server in a specific DC(s)

**Comment by RAndrews137** [comment]
Looks good @lvca.  Yes, this enhancement would greatly help in Production environments.

**Comment by tglman** [comment]
hi,

Finished the implementation for same-dc and auto in 2.2.x the property is called `network.retry.strategy`.

Regards

**Comment by tglman** [comment]
Hi,

The implementation is not yet ported to 3.x because it will be completely different.

Regards

**Comment by RAndrews137** [comment]
Thanks.  So what are the possible values for network.retry.strategy?

**Comment by tglman** [comment]
hi @RAndrews137,

two possible strategies today:
- "auto" -> select a server from the same DC (if any), then from any other DCs
- "same-dc" -> will try to reconnect to another server in the same DC if none will fail.

**Comment by RAndrews137** [comment]
Perfect @tglman :)

**Comment by lvca** [comment]
In the docs (https://github.com/orientechnologies/orientdb-docs/blob/2.2.x/Data-Centers.md#client-reconnection), soon online.

**Comment by santo-it** [comment]
Hi @RAndrews137,

Thanks for your patience. One question: can we close this one now? The enhancement has been implemented in 2.2.25, and a public issue has been opened by us so that we can port the fixes into 3.0 (Issue #7618)  

If you have any follow-up questions on this, you can open a private issue.

Many thanks,

**Comment by RAndrews137** [comment]
We tested this last Friday and it worked well.  We can close the issue.  Thanks  :)

**Comment by luigidellaquila** [comment]
Great, closing then.

Thanks

Luigi
