### ISSUE TITLE
Problem in projection and filtering in EmbeddedMap property.

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#7511]
## Expected behavior  
 I defined  an **embeded map** in **User** class and i want to project some map values after query on values . 

`select LinkedAccounts.values() from `User` where LinkedAccounts.values() contains (Provider = "google") and LinkedAccounts.keys() contains "google::0923887327kjhdsf783kjhf7"`

returns some values and its ok 

but `select LinkedAccounts.values()[IsDefault = true] from `User` where LinkedAccounts.values() contains (Provider = "google") and LinkedAccounts.keys() contains "google::0923887327kjhdsf783kjhf7"` returns a bracket only.

I test it by **embedded list** and it's ok . (same as documentation)
I test it by **embedded set** and it's not ok . 
I test it by **embedded map** and it's not ok . 

Is it right or there is a problem here . 

## Actual behavior  
Project and filter on `LinkedAccounts.values() ` with `LinkedAccounts.values()[IsDefault = true] ` syntax .

I attached some pictures to describe better .
![image](https://user-images.githubusercontent.com/10245423/27518756-485399a4-59fc-11e7-9dbd-8967262ed179.png)

and  compare to 

![image](https://user-images.githubusercontent.com/10245423/27518764-87ab0948-59fc-11e7-9b2a-1e9feec5009b.png)

Thanks 
Saeed Tabrizi

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

The syntax seems to be correct, so I'd say it's a bug.
Let me do a couple of tests, I'll be back to you asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

I just pushed a fix that should solve the problem. 
The fix will be released with 2.2.23

Thanks

Luigi

**Comment by saeedtabrizi** [comment]
Hi @luigidellaquila 
It's so really super fast reaction as i expected. 
Thanks 

Saeed Tabrizi
