### ISSUE TITLE
Live select from multi classes

### ISSUE THREAD

**Issue by a-zacharenkov** [orientechnologies/orientdb#7515]
## Expected behavior  
I am live subscribing from Java controller to database. I looked up online and it didn't say anything about restrictions of LIVE select, so this may be one? as per docs (https://orientdb.com/docs/2.2/SQL.html), I used the select from multi targets, specifying the classes of vertices I'm interested in just like this : 

`live SELECT EXPAND( $c ) LET $a = ( SELECT FROM Person), $b = ( SELECT FROM Address), $c = UNIONALL( $a, $b )`

## Actual behavior  
On an update of any of these vertices - I get the following exception:

`
Error executing live query subscriber.
java.lang.NullPointerException
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.m
atchesTarget(OCommandExecutorSQLLiveSelect.java:184)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.o
nLiveResult(OCommandExecutorSQLLiveSelect.java:110)
        at com.orientechnologies.orient.core.query.live.OLiveQueryQueueThread.ru
n(OLiveQueryQueueThread.java:69)
`

## Steps to reproduce  
Live query a multi vertex selection and update any of the classes properties

**Comment by luigidellaquila** [comment]
Hi @a-zacharenkov 

You are right, this is a restriction of live queries. 

Right now you can do live queries only on a single target (eg. `SELECT FROM AClass WHERE...`).
Another important limitation is that live queries don't work for aggregate queries and for ORDER BY

Thanks

Luigi
