### ISSUE TITLE
@rid in result from query is "#-2.0"

### ISSUE THREAD

**Issue by RubenVermeulen** [orientechnologies/orientdb#7521]
## Expected behavior  
**#1**: SELECT username FROM User WHERE username = "Bob"
 ```
"result": [
        {
            "@type": "d",
            "@rid": "#11:1",
            "@version": 0,
            "username": "Bob",
            "@fieldTypes": "rid=x"
        }
    ]
```
**#2**: SELECT @rid, username FROM User WHERE username = "Bob"
"result": [
        {
            "@type": "d",
            "@rid": "#11:1",
            "@version": 0,
            "rid": "#11:1",
           "username":"Bob"
            "@fieldTypes": "rid=x"
        }
    ]
```
## Actual behavior  
**#1**: SELECT username FROM User WHERE username = "Bob"
 ```
"result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "rid": "#11:1",
            "username": "Bob",
            "@fieldTypes": "rid=x"
        }
    ]
```
**#2**: SELECT @rid, username FROM User WHERE username = "Bob"
"result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "rid": "#120:3750",
            "rid": "#11:1",
            "@fieldTypes": "rid=x"
        }
    ]
```
## Steps to reproduce  
See queries above.

**Comment by luigidellaquila** [comment]
Hi @RubenVermeulen 

This is a legacy behavior that unfortunately cannot be changed in v 2.2.

If you want to include/exclude fields from JSON you can use fetch plans: http://orientdb.com/docs/2.2.x/Fetching-Strategies.html

In v 3.0 it's already fixed.

Thanks

Luigi
