### ISSUE TITLE
incomplete documentation about INSERT ... RETURN ... syntax

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7522]
The 2.2.x documentation about the INSERT statement, describes incomplete syntax possibilities for the RETURN part:

RETURN Defines an expression to return instead of the number of inserted records. You can use any valid SQL expression. The most common use-cases,
    @rid Returns the Record ID of the new record.
    @this Returns the entire new record.

"The most common use-cases" phrase does not say what else is possible, for example is it possible to let the INSERT ... RETURN statement return the number of records which have been inserted ?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

The goal of that RETURN is to return any projections based on the inserted record (the equivalent of `x, y` in a `SELECT x, y FROM...`), but that's not very used and afaik there are some issues there, so I discourage you to use any other keywords apart from @rid and @this 

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
hi Luigi, thx for the reply.
1) can you please make sure the documentation about this RETURN in the INSERT, is made complete? It is very confusing now, suggesting that more (but not mentioning which) options are possible
2) if INSERT cannot return the number of records which have been inserted, that is very inconvenient inside scripts: in our case, I want to INSERT records into one class, from a SELECT from another class (INSERT INTO class1 FROM SELECT FROM class2 WHERE ...); depending if there were such records INSERTed, they should be deleted from that other class. For that, I need to get an indication that the SELECT FROM class2 did find anything. If the INSERT will not tell me this, then I must run the SELECT twice: one to know if it would find anything in class2, and then another time as part of the INSERT statement...
-> can this be added to the INSERT statement in a next (hopefully very soon) subrelease, please ?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Sure, I left this issue open just to remember to update the docs.

About the enhancement, an  `INSERT INTO.. FROM SELECT..` will return a single record with a "value" property that indicates how many records were inserted. Is it enough for your use case?

Thanks

Luigi

**Comment by rdelangh** [comment]
for my use case, that would be fine indeed, but I can imagine there are other cases, where for example it would be necessary to have the RIDs returned of the newly inserted records.
So maybe it is better to support a few RETURN ... keywords (like COUNT, @RID, etc)

**Comment by luigidellaquila** [comment]
Try this ;-)

```
insert into AnotherClass RETURN @rid from select from YourClass
```

Thanks

Luigi

**Comment by rdelangh** [comment]
ok:
```
let rows = insert into class1 return @RID from select  from class2 WHERE ... ; select $rows.size();
+----+----+
|#   |$rows|
+----+----+
|0   |1   |
+----+----+
```

-> this can be used in my scripts.

thx!

**Comment by luigidellaquila** [comment]
Fixed docs, closing

Thanks!

Luigi
