### ISSUE TITLE
[FEATURE] IF [NOT] EXISTS for Sequence , Index , Cluster , DB , User , Role , Function in orient db Sql syntax

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#7529]
Hi 
As we already discussed in https://github.com/orientechnologies/orientdb/issues/3597 a pretty feature added to **Class** and **Property** , **Create** and **Drop** commands and many useful in database schema **migration** .
I want to recommend following syntax for the rest of sql commands in ODB next version release :

- [x] CREATE IF NOT EXISTS  SEQUENCE ....
- [x] DROP IF  EXISTS  SEQUENCE ....

- [x] CREATE IF NOT EXISTS  INDEX ....
- [x] DROP IF  EXISTS  INDEX ....

- [x] CREATE IF NOT EXISTS  CLUSTER ....
- [x] DROP IF  EXISTS  CLUSTER ....

- [ ] CREATE IF NOT EXISTS  FUNCTION ....
- [ ] DROP IF  EXISTS  FUNCTION ....

- [ ] CREATE IF NOT EXISTS  DB ....
- [ ] DROP IF  EXISTS  DB ....

- [ ] CREATE IF NOT EXISTS  USER ....
- [ ] DROP IF  EXISTS  USER ....

- [ ] CREATE IF NOT EXISTS  ROLE ....
- [ ] DROP IF  EXISTS  ROLE ....

Welcome to all comments .

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

Thank you for opening this ticket, it will help track the progress.
For some statements (eg. CREATE/DROP CLASS/PROPERTY) an "if exists/not exists" options is already available. For all the rest it makes a lot of sense to add this option.

I'm marking this as an enhancement, I'll work on it as soon as I can

Thanks

Luigi

**Comment by lightjiao** [comment]
+10086

**Comment by lpil** [comment]
HI all! Is there a way of getting something like `CREATE INDEX IF NOT EXISTS` with the current OrientDB featureset?

**Comment by luigidellaquila** [comment]
Hi @lpil 

No, it's not available yet, but we will implement it soon in v 3.0.x

Thanks

Luigi

**Comment by lpil** [comment]
Thank you.

Is it possible to emulate it using the database scripting functionality and reflection perhaps?

Cheers,
Louis

**Comment by luigidellaquila** [comment]
In this case, the easiest think you can do is to just execute the CREATE INDEX as a separate REST call and manage the error. 

Anyway, I think I can implement the `CREATE INDEX IF NOT EXISTS` in short, I'll see what I can do 

Thanks

Luigi

**Comment by lpil** [comment]
That's great, thanks for the help :)

**Comment by luigidellaquila** [comment]
Hi @lpil 

I just pushed a little enhancement to develp branch, now you can do

```
CREATE INDEX indexname IF NOT EXISTS ...
```

The snapshot will be available in a few minutes

Thanks

Luigi

**Comment by saeedtabrizi** [comment]
Hi @luigidellaquila 
May i know which commands now support IF [NOT] EXISTS mechanism in ODB v3? 
Thanks.

**Comment by cegprakash** [comment]
Will 'CREATE INDEX IF NOT EXISTS' be supported in 2.2.x?

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

V 2.2 is only having hotfix upgrades, we are not adding new features (apart from very specific requests from paying customers).

I strongly suggest you to go with v 3.0, you will have a lot of advantages

Thanks

Luigi

**Comment by feiYH** [comment]
Hi,

Could you update the 3.0.X documentation regarding this functionality ?
Ex : https://orientdb.com/docs/3.0.x/sql/SQL-Create-Index.html

Regards,
Yoan

**Comment by luigidellaquila** [comment]
Hi @feiYH 

Doing it now, thank you for pointing it out

Thanks

Luigi

**Comment by arcilli** [comment]
So if you want to check if a database exists from a script, what should be the approach on that?
Thanks
