### ISSUE TITLE
Cost estimate

### ISSUE THREAD

**Issue by zhangshusheng** [orientechnologies/orientdb#7533]
## Quetion
Is there a cost estimation model in OrientDB ? 
Does it make sense to estimate cost in OrientDB or other NoSQL databases ?

Thanks.

**Comment by careerscale** [comment]
@zhangshusheng  what is this question about? anything specific to orientdb or you are talking about cost estimation model in general? OrientDB is a general purpose graph db, and if you are talking about specific domain stuff, I think you need to implement your own logic.  it depends on what the logic you have. If you are dealing with lots of traversals, go with Graph and In general Orient is really cool. I like it.

I am not from OrientDB team btw.

**Comment by zhangshusheng** [comment]
Hi, @careerscale .
I mean that is there a cost estimation module in OrientDB, which like the cost estimation model in Postgresql for query optimization. Does it need optimization to traversal query on graph data? So, is the cost estimation necessary?

This is just my guess, I just started studying grpah database.
Thanks.
