### ISSUE TITLE
Error on restore of cluster from file during replace cluster

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#7539]
## Steps to reproduce  
Run distributed test TestShardingManualSync

**Comment by taburet** [comment]
This specific issue if fixed. But in general cluster replication is broken, the only file being replicated is *.pcl; *.cpm and related index files are ignored. See OSyncClusterTask#execute for details.

**Comment by tglman** [comment]
hi,

this is all fixed now. closing.
