### ISSUE TITLE
Block execution of database if data corruption on disk is detected

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7540]
We implemented a feature which allows detecting whether data are broken on disk by checking them using CRC32 code. But it this moment we by default put the warning message in a log, and that is it. It will take a while till user notices this message. Data structures may be damaged even more till warning will be noticed. There is no point to run the database with corrupted data structures. We should use the same approach which we use to switch database in read-only mode when space on a disk is exhausted to switch in in read-only mode when data corruption on disk is detected.

**Comment by lvca** [comment]
I like this. And if you could provide a listener for such event, running in HA could automatically re-deploy the corrupted database to the server.

**Comment by laa** [comment]
@lvca this tool is used to indicate that HW is broken we detect not damage of records because of bugs in database but damage of records because of damage of HW.  I can not have a link by hand but Redis guys added similar functionality to their database and found that quite a lot of servers have problems with HW.  So our main intention is to sort out bug reports which were caused by issues in HW. Anyway, functionality will be implemented exactly using the listener so you can use it too to replace DB. But probably because HW is broken, DB will be broken soon again and there is no point to replace it.

**Comment by lvca** [comment]
Fine for me.

**Comment by laa** [comment]
fixed
