### ISSUE TITLE
Incompatible changes in 2.2.23 related to security

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7549]
### OS: ubuntu 

There are big changes in 2.2.23 related to security. Yes - it's pretty inconvenient to have such big changes in minor version, but it might be OK if you can support previous logic for the following case:

REST call for `/query/db/sql/select from $user`. Previously it worked perfectly under reader/reader and reader/reader.
Also let me mention that there is related problem: #4906 . It's really strange to deny for a user access for his own OUser/document.

P.S. To work around I have to provide READ access to SYSTEM_CLUSTERS.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

This change is related to a security issue, we fixed a vulnerability that was strictly related to bypassing permissions with some SQL queries.

For sure that fix cannot be reverted, but we can see if this specific case (that does not seem to affect security) can be explicitly supported

Thanks

Luigi

**Comment by PhantomYdn** [comment]
Yes - please check. Otherwise, I'm sure that everybody who used OUser in their coding have to use provide READ access to SYSTEM_CLUSTERS to everyone who should be able to read just his OUser document.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I just pushed a fix on 2.2.x, could you please check if it covers your case?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I'm closing this issue, please reopen if you see any related problems

Thanks

Luigi
