### ISSUE TITLE
WebSphere: Transaction Timeout During Node Synchronization

### ISSUE THREAD

**Issue by fredfortier** [orientechnologies/orientdb#7551]
## Expected behavior  
Two applications with an embedded OrientDB server restart every night, ten minutes apart. The first node should startup successfully. The second node should then synchronize. 

## Actual behavior  
A transaction timeout occurs during synchronization.  
javax.transaction.TransactionRolledbackException: Transaction is ended due to timeout

I'm trying to get more info from our customer. Any pointer would be appreciated.

**Comment by maggiolo00** [comment]
Hi @fredfortier 

which is the timeout settings?
