### ISSUE TITLE
In Studio, graph page freezes on a query returning 20 records, while browse returns the result without any issue

### ISSUE THREAD

**Issue by adepase** [orientechnologies/orientdb#7556]
### OrientDB Version: orientdb-teleporter-community-2.2.23
OrientDB Server v2.2.23 (build 1318ca2)
Databases directory: C:\orientdb-teleporter-community-2.2.23\databases [OServer]
OrientDB auto-config DISKCACHE=1.024MB (heap=910MB direct=1.024MB os=8.122MB)
  
## Expected behavior  
I expected the same result from browse and graph studio pages starting from the same query:
SELECT shortestPath(#18:122, #19:1504, 'OUT', 'hypernym') as path from synset unwind path

## Actual behavior  
I got a result (20 records in 0.37 seconds) from browse page while the graph page freezes, I think because the log says: "Query 'SELECT shortestPath(#18:122, #19:1504, 'OUT', 'hypernym') AS path FROM synset UNWIND path' returned a result set with more than 10000 records. Check if you really need all these records, or reduce the resultset by using a LIMIT to improve both performance and used RAM [OProfilerStub]"
I started again the server to check if the message log appears also when running the query from the browse page, but it doesn't happen, it's just an issue for the graph page.

## Steps to reproduce  
Run the same query from the browse page and from the graph page

**Comment by adepase** [comment]
Further information:  selecting the "Explain" button instead of the "Run" button in the browse page results in the same log message (and freeze) as in the graph page.

**Comment by maggiolo00** [comment]
Hi @adepase 

Freeze do you mean that you see the loading spinner ?

Which is the count of the shortest path?

**Comment by adepase** [comment]
Exactly, I see the loading spinner (several minutes vs 0.37 seconds)
The count is 20, as I said in the issue.
Alessandro


2017-07-17 15:05 GMT+02:00 Enrico Risa <notifications@github.com>:

**Comment by maggiolo00** [comment]
Hi @adepase 

you should rewrite your query.

```
SELECT shortestPath(#18:122, #19:1504, 'OUT', 'hypernym') AS path UNWIND path
```
you were using `From synset`. By doing so the engine will call shortestPath function for each records in `sysnet` class.

**Comment by adepase** [comment]
Ok, thank you.
The graph is no more freezing and I suppose the browse page returned 20
rows because it uses a predefined limit.
Understood.
But is there a way to see vertex (and maybe edges) in the graph page? This
way it returns nothing.
Thank you in advance.
Alessandro


2017-07-17 15:14 GMT+02:00 Enrico Risa <notifications@github.com>:

**Comment by maggiolo00** [comment]
hi @adepase 

can you try ?

```
SELECT expand(shortestPath(#18:122, #19:1504, 'OUT', 'hypernym')) 
```


Thanks

**Comment by adepase** [comment]
Interesting enough, the graph page has also a predefined limit of 20,
however: this resolve my specific issues, but doesn't explain the
 different behaviour (I don't mind, at least not in this case, just telling
for you to improve your system).
Alessandro

2017-07-17 15:20 GMT+02:00 Alessandro Depase <alessandro.depase@gmail.com>:

**Comment by adepase** [comment]
It works. Thank you so much.
Alessandro



2017-07-17 15:23 GMT+02:00 Enrico Risa <notifications@github.com>:

**Comment by maggiolo00** [comment]
hi @adepase 

about the different behaviour is that the graph page uses a different endpoint with a custom graph
format as result set.

**Comment by adepase** [comment]
Thank you again. Very fast and efficient :)
Kind Regards
Alessandro


2017-07-17 15:25 GMT+02:00 Enrico Risa <notifications@github.com>:
