### ISSUE TITLE
Strange working SQL GET query for fields with OType.DATE in prepared statement

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#7557]
### OS: Ubuntu 16.04  
Case:  strange working SQL GET query for fields with type OType.DATE when using prepared statement.
## Expected behavior
When use prepared statements with java type Date and OrientDB DATE, DATETIME all works fine, but prepared statements for OrientDB DATE don't work correctly.
### OType.DATE
`Map<String, Object> params = new HashMap<>();`
`params.put("date", new SimpleDateFormat("yyyy-MM-dd").parse("2017-07-06"));`
`db.query(new OSQLSynchQuery<List<ODocument>>("SELECT FROM Class WHERE date = :date"), params);`
Document with field `date` and value `2017-07-06` is already exists, but query returns empty list.

### OType.DATETIME
`Map<String, Object> params = new HashMap<>();`
`params.put("datetime", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse("2017-01-03 11:03:21"));`
`db.query(new OSQLSynchQuery<List<ODocument>>("SELECT FROM Class WHERE datetime = :datetime"), params);`
Document with field `datetime` and value `2017-01-03 11:03:21` is already exists and query returns list with document.
All works fine.

### Date in String
If  convert date and date time to string and use prepared statements all works fine.

Date format in OrientDB for OType.DATE: "yyyy-MM-dd"
Date format in OrientDB for OType.DATE: "yyyy-MM-dd HH:mm:ss"
Tests with OrientDB version 2.2.22 and 2.2.23.

## Steps to reproduce  
Read before.

Thanks,
Vitaliy

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

Just a couple of questions to better understand the problem?

- do you have a schemaful class? How do you create the schema?
- how do you populate the db?

Haing a db that has the problem or a script to create it would help a lot

Thanks

Luigi

**Comment by WeaxMe** [comment]
Hi @luigidellaquila 
I was create test for this case.
[https://github.com/WeaxMe/orienteer-test/blob/master/orientdb-test-data-query/src/test/java/com/weaxme/test/query/TestPreparedStatement.java](url)
Answer for you questions:
- I use schema less class

Thanks for feedback,
Vitaliy

**Comment by luigidellaquila** [comment]
Great, thank you very much @WeaxMe, I'll check it today

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

I just pushed a fix for this on branch 2.2.x. The fix will be available in v 2.2.24

Thanks

Luigi
