### ISSUE TITLE
SELECT statement doesn't allow to use rid as static field

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7559]
### OS: linux 

The following queries are valid from OrientDB point of view:

```sql
select 10 as ID, name from MyClass
select name from MyClass where link = #5:0
```

but at the same time the following query is not valid

```sql
select #5:0 as link, name from MyClass
```

It looks pretty inconsistent with OrientDB capabilities. Any chance to fix?

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I just tried it on latest 2.2.x and it seems to work fine. Am I missing something? Maybe you have a particular schema defined or something like that?

Thanks

Luigi

**Comment by PhantomYdn** [comment]
Have you tried that through OrientDB console, Java API or serverside javascript?
In my case I used Java API.

**Comment by luigidellaquila** [comment]
No, I tried from Studio only. I'll try it from Java

Thanks!

Luigi

**Comment by PhantomYdn** [comment]
It seems that a problem is on my side. I have used copy-paste from Word document and character # in word is not the same as simple #. After reentering - everything is fine. Thank you for validation! I stuck previously without your comment that it should work:)

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I tried this

```
  @Test
  public void testLink() {

    String className = "testLink";

    db.command(new OCommandSQL("create class " + className)).execute();
    db.command(new OCommandSQL("insert into " + className + " set name = 'foo'")).execute();

    List<ODocument> results = db.query(new OSQLSynchQuery<ODocument>("select #5:0 as link, name from " + className));
    Assert.assertEquals(results.size(), 1);
    ODocument doc = results.get(0);
    Assert.assertEquals(doc.field("name"), "foo");
    Assert.assertNotNull(doc.field("link"));
  }
```

but with no success, it seems to pass... any idea?

Thanks

Luigi
