### ISSUE TITLE
FR: support of negative numbers in left(), right()

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7560]
Currently the following queries work perfectly:

```sql
select name.left(2) from OUser
select name.right(2) from OUser
```

But what if I need everything except last X characters? Expected that the following queries will work, but that didn't

```sql
select name.left(-2) from OUser
select name.right(-2) from OUser
```

Moreover (and that's a bug, I think)  the following query doesn't work as expected

```sql
select name.substring(0, eval("name.length()-3") ) from OUser
```

Previous queries with minus just fail with exception, but this one works, but instead of string without last 3 characters it return whole string.

And even more over! The following queries just doesn't work as expected.

```sql
select 2+2 as plus from OUser //Should either throw exception or return 4 in column plus
select (2+2) as plus from OUser //Should either throw exception or return 4 in column plus
select eval(2+2) as plus from OUser  //Failing with NullPointerException
select eval("2+2") as plus from OUser //No column plus at all - should fail or evaluate
```

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

The enhancement should not be too complex, I'll try to do it as soon as I can.

About the other bugs reported, what I can say is that:

- math operations like `2+2` are not supported as simple projections in v 2.2, but they already work fine in v3.0M1
- eval() function accepts strings, so `eval(2+2)` is not valid (but I agree with you that it should not throw NPE)
- eval function is very sensitive to spaces, probably `eval("2 + 2")` will work fine
- in general, `eval()` will be deprecated in v 3.0 as there is no need for that anymore

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila , thank you for considering enhancement!

I understand regarding spaces. But is that expected behavior or some enhancements are expected?
