### ISSUE TITLE
OrientDB graph editor settings saved with admin user not reflected for other user 

### ISSUE THREAD

**Issue by sridharnampalli** [orientechnologies/orientdb#7564]
## Expected behavior  
graph editor settings changes saved with admin user , to display name of the node properties value instead of @rid  , graph diplay the changes with admin user after refresh and re-login  , but with other user it does not have the same feature

## Actual behavior  
it display @rid value for node names   

## Steps to reproduce  
login with admin user and make the setting changes , save , run the graph editor to reflect the changes  , login with different user and changes will not reflect

**Comment by maggiolo00** [comment]
hi @sridharnampalli 

that is how it works. Each user has it's own configuration.

**Comment by sridharnampalli** [comment]
Hi @maggiolo00  , but other then admin user the configuration changes are not retained /saved  once we refresh the browser / re-login again with different user other then admin 

so how to save the  configurations for non admin users

**Comment by maggiolo00** [comment]
with which users did you test it?

**Comment by sridharnampalli** [comment]
Hi @maggiolo00  , i have tested with user1 with write permissions and user2  with read permissions  , but for both i not able to restore the configuration changes 

please let me know other than admin user , can we restore the configuration changes on graph editor 
if so please share the steps /screenshots
