### ISSUE TITLE
Performance problem with MATCH command when there is no matching record exists

### ISSUE THREAD

**Issue by mehdizarepour** [orientechnologies/orientdb#7573]
## Steps to reproduce  

I have these vertex classes in my database: `Company`, `Product`, `Consumer`

For example I have one company (`A`) that has 30 products and every products used by 500 consumers, also there is another company (`B`) that has 30 products and every products used by 500 consumers.

I want to select common consumers between these companies:

Query 1:

```sql
MATCH { class: Company, as: company, where: (name = "A") }
.out("CompanyHasProducts") { as: product }
.out("ProductHasConsumers") { as: consumer },
{ class: Company, where: (name = "B") }
.out("CompanyHasProducts")
.out("ProductHasConsumers") { as: consumer }
RETURN consumer LIMIT 3
```

Query 2:

```sql
MATCH { class: Company, as: company, where: (name = "A") }
.out("CompanyHasProducts") { as: product }
.out("ProductHasConsumers") { as: consumer }
.in("ProductHasConsumers")
.in("CompanyHasProducts") { where: (name = "B") }
RETURN consumer LIMIT 3
```

## Expected/Actual behavior  

In normal scenarios these queries are very fast (~0.02s), but in the following scenarios they took ~18 seconds to complete:

- When there is no common consumers exists
- When the number of common consumers are less than the `LIMIT` value

Thanks

**Comment by luigidellaquila** [comment]
Hi @mehdizarepour 

The problem here is that there is no way to optimize the search, you only have filtering information at the extremes (the companies) and you have to scan the whole DB to check if records exist.

You can expect some optimizations on the execution in next releases, but only in terms of traversal speed and, because there is no algorithm optimization that can be done in this scenario

Thanks

Luigi

**Comment by mehdizarepour** [comment]
Hi @luigidellaquila
​
> The problem here is that there is no way to optimize the search, you only have filtering information at the extremes (the companies) and you have to scan the whole DB to check if records exist.
​
In my scenario, I can only filter the company name and limit the output to get common consumers between two companies.
​
Also, I can use `SELECT` command and `intersect()` to avoid this issue (traversing all records) but it's not very efficient in the large datasets.
​
What do you suggest for this scenario? (just give me a hint)
​
> You can expect some optimizations on the execution in next releases, but only in terms of traversal speed, because there is no algorithm optimization that can be done in this scenario
​
I have also checked a similar old issue and I have found your comment (https://github.com/orientechnologies/orientdb/issues/6826#issuecomment-255711201), it seems that you had found a solution, but can it be implemented?
​
Also, if it helps, I can give you my dataset.
​
Thanks
