### ISSUE TITLE
ODB2.2.20 OOM errors

### ISSUE THREAD

**Issue by pinakdeshpande** [orientechnologies/orientdb#7577]
## Expected behavior  
OrientDB should work perfectly and should never run into memory leak issue

## Actual behavior  
Orient DB 2.2.20 fails with either `GC Overhead limit exceeded error` or `java.lang.OutOfMemoryError: Java heap space` needing to restart the DB on our PROD env 2-3 times a day after the upgrade done from ODB V2.1.16 couple of days back.

Here is the ODB config
`/bin/java -server -Xms2G -Xmx2G -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dstorage.diskCache.bufferSize=26624 -Djava.util.logging.config.file=/opt/orientdb/config/orientdb-server-log.properties -Dorientdb.config.file=/opt/orientdb/config/orientdb-server-config.xml -Dorientdb.www.path=/opt/orientdb/www -Dorientdb.build.number=2.2.x@r76ab59e72943d0ba196188ed100c882be4315139; 2017-05-11 13:55:56+0000 -cp /opt/orientdb/lib/orientdb-server-2.2.20.jar:/opt/orientdb/lib/*:/opt/orientdb/plugins/* com.orientechnologies.orient.server.OServerMain`

## Steps to reproduce  
Steps are same as mentioned in issue #7576.

**Comment by robfrank** [comment]
Can you try with latest 2.2.24 to confirm the problem? Thanks.

**Comment by pinakdeshpande** [comment]
I will upgrade and let you know

**Comment by lvca** [comment]
@pinakdeshpande any news on this?

**Comment by pinakdeshpande** [comment]
@lvca 
We upgraded to the latest version 2.2.24 last week and after that also we were getting OOM but it was caused by GC Overhead Limit Exceeded error, we tried to multiple options to make the server stable. 
But after upgrade we are not getting OOM caused by "Java Heap Space"
You can find detailed steps we followed and latest configs...etc in other issue which I reported #7576.

**Comment by lvca** [comment]
Thanks, so I'm closing this.
