### ISSUE TITLE
[PROPOSAL,FEATURE] Synonym for document properties in next ODB. 

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#7579]
Hi , 
As i requested in https://github.com/orientechnologies/orientdb/issues/7530 the **synonym's** capability is a real need  for modern and **operational database** .
So after i see the new syntax of nested properties for projection in ODB 3.0.0 , i just to say a new feature recommend that i named to **Synonym to Values** .

So i describe it by an example : 
**Scenario :**

We have a  `Person` class :
```
 Person : {Name : String , Age : Integer , Parent: Link, FatherName : Synonym, , GrandFatherName : Synonym} .
```

And we have 4 records that stored in database like the following lines :
```

 1- #12:0 , {Name:"john",Age:30,FatherName: "james" }  // synonym can be literal or any type
 2- #12:1 , {Name:"jack",Age:30,Parent:#12:0,FatherName: #12:0.Name} // FatherName linked and represent the Name in  #12:0 that represents "john" .
 3- #12:2 , {Name:"bill",Age:30,Parent: #12:1,FatherName: #12:1.Name,GrandFatherName:#12:0.Name}
// FatherName linked and represent the Name in  #12:1 that represents "jack" and GrandFatherName linked and represents the Name in  #12:0 .

4- #12:2 , {
Name:"bill",Age:30,Parent: #12:1,FatherName: #12:1.Name,GrandFather:#12:0.{Name,Age}  
}

```

As you can see , just a **dot "."** after `Record ID` represents a property path that have a synonym to any other values .

**Goals :**

1. The first goal is an harmonized linking to conceptual dependent data across the database rows .
2. The second goal is to create a view record that all or partially using the synonym values and user can not be modify original data.
3. And the last goal  , decrease complexity of data queries and their costs .
    

Welcome to all comments .
Thanks 
Saeed Tabrizi.

**Comment by smolinari** [comment]
It looks to me like you are trying to build edges within the synonyms. Why can't you just have a "Father-Son" edge? An edge would be much simpler logically and is traversable to any depth. What if you need a users GreatGreatGreatGrandfather? The synonym idea doesn't scale well in terms of depth in your example. 

[Looking at the description of a Synonym](https://en.wikipedia.org/wiki/Synonym_(database)), it looks like its purpose is a totally different one too. 

Scott

**Comment by saeedtabrizi** [comment]
@smolinari  thanks for your good comment .
My proposal is very simple and basically  that must be revision to be finalize .
But about the your comment , i would to say , my proposed synonym syntax did not related to graph features and very simple for fast traversing between the properties . 
for GreatGreatGreatGrandfather we can use the following syntax :

```
#12:0 , {Name:"bill",Age:90,FatherName: "Jack".Name}

#12:1 , {Name:"bill",Age:60,Parent: #12:0,FatherName: #12:1.Name,GrandFatherName:#12:1.Name}

#12:2 , {Name:"bill",Age:40,Parent: #12:1,FatherName: #12:2.Name,GrandFatherName:#12:2.Name}
```
For the solving the traversing problem we can have following  synatxes :

```
#12:3 , {Name:"bill",Age:40,Parent: #12:2,FatherName: 
#12:3.Name,GreatGreatGreatGrandfather:#12:2.Parent.Parent.Name}
```

Or

```
#12:3 , {Name:"bill",Age:40,Parent: #12:2,FatherName: 
#12:3.Name,GreatGreatGreatGrandfather:#12:2.Parent{...}.Name} // Traverse Parent to acheive null and max depth .
```
Or 

```
#12:3 , {Name:"bill",Age:40,Parent: #12:2,FatherName: 
#12:3.Name,GreatGreatGreatGrandfather:#12:2.Parent{2}.Name} // Traverse Parent to and 2 level depth .
```
However we can have a rule for synonyms syntax  that can be represents like a `Link` rule .

Saeed Tabrizi

**Comment by smolinari** [comment]
I still see no practical reason for Synonyms through your example. In fact, it is sort of putting database logic in the data, which is a no-no. Having such links in the data would also require ODB to scan over and compile any data retrieved to then translate the  "links" to the proper data and that would obviously be bad for performance. 

I can see Synonyms used for the purpose of aliasing. But, that is about it.

Scott
