### ISSUE TITLE
User is allowed to create a map with keys of any type, while only String keys are supported

### ISSUE THREAD

**Issue by arkolesnik** [orientechnologies/orientdb#7582]
## Expected behavior  
User of the library should not be allowed to use non-string keys in maps.

## Actual behavior  
User can create Map with <Integer, Integer> types and successfully save the document with this property. Then in attempt to use this document, it turns out keys are cast to String type without any notification. 

## Steps to reproduce  
Create HashMap<Integer, Integer>, fill it in with appropriate data, assign it to ODocument property by method public ODocument field(final String iFieldName, Object iPropertyValue) and save the document. Get this property by it's name - all keys were cast to String type from Integer.

**Comment by lvca** [comment]
Can @tglman update the docs?
