### ISSUE TITLE
slow Lucene lookups

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7587]
### OrientDB Version: 2.2.23

Queries straight from Lucene indexes, should complete in a few seconds, not 10's of minutes:
The following SQL query is very typical in our context, where we need to search in a class of a full week of records, for certain substrings in one particular property of type STRING.
So I have created Lucene indexes on such properties, one Lucene index per property. 
The SQL query is then:
```
SELECT unionAll($var_cdr_af_called_0.x, $var_cdr_af_called_1.x, $var_cdr_af_called_2.x) AS x LET 
              var_cdr_af_called_0 = (SELECT set(rid) AS x FROM INDEX:idx_cdr_af_20170625_3 WHERE key LUCENE ' *32336667* '), 
              var_cdr_af_called_1 = (SELECT set(rid) AS x FROM INDEX:idx_cdr_af_20170625_3 WHERE key LUCENE ' *32325727* '), 
              var_cdr_af_called_2 = (SELECT set(rid) AS x FROM INDEX:idx_cdr_af_20170625_3 WHERE key LUCENE ' *22724801* ')
```
This finds some 161000 records, but the time it takes is 1837 seconds!

The index itself contains some 73M entries, according to a rebuilt output:
```
orientdb {db=cdrarch}> rebuild index idx_cdr_af_20170625_3
Rebuilding index(es)...
Rebuilt index(es). Found 73585585 link(s) in 1622.822021 sec(s).
```

From this result-set, I must normally perform an extra "expand()" on these RIDs so that I can apply further actions on the properties of these records, such as further filtering, or "GROUP BY" aggregations. 
So to be explicit : I am not yet counting the time to do such "expand" on the records. The time that I mention, is only to scan the indexes and return me the RIDs.

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Lucene is not designed to perform queries with wildcards both on the left and the right of a string (eg. `' *32336667* '`), this is why you have a very poor performance.

Currently there is no index that can manage this kind of query

Thanks

Luigi

**Comment by robfrank** [comment]
moreover, you are hitting the same index threee times. Why don't try to collapse the three lucene queries on a single one using AND and OR?

https://lucene.apache.org/core/6_6_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Boolean_operators

**Comment by rdelangh** [comment]
@lvca : is there a development going on to allow wildcard searches via a non-Lucene index, such as is possible in traditional, relational databases with the 'LIKE' operator?

@robfrank : indeed, I am reworking my program so that it builds more compact SQL queries, but the problem seems to lay in what Luca mentioned: no index in OrientDB currently allows efficiently to search on substring wild wildcard operators... :-(

**Comment by rdelangh** [comment]
@lvca : more specifically, I am hoping that one day the 'LIKE' operator will allow to use leading and trailing wildcard operator such as 
```
... WHERE someproperty LIKE '*abc*'
```

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

There are no plans for that currently. Please consider that also relational databases have huge problems on this, eg. the only solution that Oracle provides is text indexes (http://www.dba-oracle.com/t_context_index.htm) that are not updated automatically (they require manual/scheduled sync) and are only suitable for tables that are read only or where you can tolerate inaccurate results

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
sorry to counterdict you, but we intensively use Oracle for our programs, and we have ordinary indexes on the VARCHAR columns which allow us to run very efficiently queries with leading wildcard operator.
Maybe you are confusing with the concept of Lucene indexing a large piece of text like a true 'document'. We have simple, one-word strings, in which we need to search for substrings.

**Comment by luigidellaquila** [comment]
@rdelangh ok, got your point, the problem here is that we don't have a limitation on the keys (like VARCHAR max size) so we have to find a general solution that scales with large text and for now there is no such option.

If we find a suitable algorithm we will be happy to consider it, but for now we are not actively experimenting on this

Thanks

Luigi

**Comment by robfrank** [comment]
can you test with a single lucene query using OR instead of 3 queries?

**Comment by rdelangh** [comment]
@robfrank , yes did that: same results almost, since in my example the first 2 queries return just a few records after 8-10 seconds runtime per query; it is the 3rd query which on its own is running for some 30 mins.
```
SELECT set(rid) AS x FROM INDEX:idx_cdr_af_20170625_3 WHERE key LUCENE ' *22724801* '
```
takes 1832 seconds, returns a single property 'x' consisting of 161K RIDs.

What I did experiment also, was doing a simple "count(*)" on the result-set.
This way, that 3rd query is not running 30 mins, but only 24 seconds!
```
SELECT count(*) FROM INDEX:idx_cdr_af_20170625_3 WHERE key LUCENE ' *22724801* '
``` 
takes 24 seconds, finding 161K records.

So the delay comes not dramatically from traversing the Lucene index, as this last timing proofs. The difference is that in reality I can not only run a "count(*)" on the resultset, but I need to capture the RIDs from the indexes, from where I need to perform an extra, very expensive "expand" to obtain the properties of the records, so that I can further filter or aggregate on such properties...

**Comment by publicocean0** [comment]
maybe is a problem in memory usage .... count use just a value ... instead reading all rows load all in memory .

**Comment by rdelangh** [comment]
hi @publicocean0 , I can confirm that the machine is not running into physical memory shortage, nor swapping. So there is some 10's of GB spare RAM that might be used more optimally.
Regarding CPU: I have noticed many times that ODB is hardly using the muliple cores present in the machine, the overall CPU-usage is below 5%. Maybe adding more parallelism (multi-threading) in the server code might help as well.
