### ISSUE TITLE
is it possible to compose "CREATE EDGE AEdge FROM (#65:0) TO (#23:1,#26:1,#29:0,#36:0,#53:0,#41:0)"

### ISSUE THREAD

**Issue by HuangKBAaron** [orientechnologies/orientdb#7588]
## Expected behavior  
expect to compose something like this:
CREATE EDGE AEdge FROM (#65:0) TO (#23:1,#26:1,#29:0,#36:0,#53:0,#41:0)

## Actual behavior  
report error.

## Steps to reproduce  
n/a

**Comment by luigidellaquila** [comment]
Hi @HuangKBAaron 

You have to use square brackets to define collections:

```
CREATE EDGE AEdge FROM #65:0 TO [#23:1,#26:1,#29:0,#36:0,#53:0,#41:0]
```

Thanks

Luigi

**Comment by HuangKBAaron** [comment]
copied from the doc:
CREATE EDGE <class> [CLUSTER <cluster>] FROM <rid>|(<query>)|[<rid>]* TO <rid>|(<query>)|[<rid>]*
                    [SET <field> = <expression>[,]*]|CONTENT {<JSON>}
                    [RETRY <retry> [WAIT <pauseBetweenRetriesInMs]] [BATCH <batch-size>]

the "[<rid>]*" is confusing, it might be better as "[<rid>,*]" ?

**Comment by luigidellaquila** [comment]
Yes, definitely, I'm updating the docs

Thanks

Luigi
