### ISSUE TITLE
teleporter - 2.2.25-snapshot - build failure on windows 10 64bit

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7592]
![gabri](https://user-images.githubusercontent.com/14923389/28715093-be76cf76-7396-11e7-841a-202a9da3ccbb.PNG)

**Comment by G4br13l3** [comment]
Fixed. Working to make all tests green also in teleporter-3.0. 

Thanks, 
Gabriele

**Comment by G4br13l3** [comment]
Updated develop branch too, now all the tests are green on windows. 

Thanks, 

Gabriele
