### ISSUE TITLE
question about 3.0 release

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7594]
i d like to know about new features in 3.0 version. In particular way i m interested in :
1)  it is possible to index using lucene a class containing  many properties (included long ,integer,float)? it is possible also to index embedded map properties when you save unstructured data on the fly? 
2)  it is possible to handle a transaction also when you put inside sql insert/update commands? 
3) it is possible to read/save a stream of data without to split it in chunks?
4) I saw you mentionaed multitenant using cluster. but with your solution how to do when you use a distributed server ? Class A_tenant1 , A_tenant2 will be distribuded automatically in different nodes?

**Comment by robfrank** [comment]
1.: yes, it is possible, and suggested as best practice, to create a single multi-field index over a class

take a look at the doc of 3.0.x serie: http://orientdb.com/docs/3.0.x/indexing/Full-Text-Index.html#lucene-fulltext-index

It is even possible to index embedded list or maps, but the field(s) must be declared in the schema.

**Comment by tglman** [comment]
hi @publicocean0 

2) Yes in 3.0 sql is supported inside the transaction in remote.
3) The new query engine is designed in a streaming way, so for sure you have streaming read, for write the transaction is still whole in memory.
4) Is not fully defined yet.

You can already try the new feature mentioned before in 3.0.0-m2 that was released few days ago, any feedback on the new API and functionality is more than welcome.

Reagard

**Comment by smolinari** [comment]
What about this one?

>  it is possible also to index embedded map properties when you save unstructured data on the fly?

Scott

**Comment by publicocean0** [comment]
Very interesting.... it seams a lot of interesting changes in orientdb :)

**Comment by careerscale** [comment]
@robfrank, @luigidellaquila , is there an example of how to achieve  indexing of embedded map attributes?  including defining the schema etc? In my case, we are using 3.0 maps. It is map because I don't know the attributes upfront but I know the type of data, it will be a great help if it is possible to index this attributes and use them in queries without worrying about whether it is a map for convenience or not.

**Comment by luigidellaquila** [comment]
Hi @careerscale 

Support for embedded attribute indexing is not available yet on 3.0, we will add it in next few weeks and for sure before the GA.

About the schema, embedded maps by definition have no schema, but if you want to have constraints on embedded documents you can use plain classes, eg.

```
CREATE CLASS MyEmbeddedClassLevel2
CREATE PROPERTY MyEmbeddedClassLevel2.name STRING 

CREATE CLASS MyEmbeddedClassLevel1
CREATE PROPERTY MyEmbeddedClassLevel1.name STRING
CREATE PROPERTY MyEmbeddedClassLevel1.innerDoc EMBEDDED MyEmbeddedClassLevel2

CREATE CLASS TheRootClass
CREATE PROPERTY TheRootClass.docLevel1 EMBEDDED MyEmbeddedClassLevel1
```

I hope it helps

Thanks

Luigi

**Comment by smolinari** [comment]
@luigidellaquila 

Will ODB ever have indexing on non-schema data? 

Scott

**Comment by publicocean0** [comment]
If i can give a suggestion, lucene dont ask a schema for searching .... schema is a over structure present in dbms.

**Comment by publicocean0** [comment]
sorry but i gave a loot at http://orientdb.com/docs/3.0.x/java/Binary-Data.html in relation to point 3)
**The new query engine is designed in a streaming way.)**
it seams i cant save a long blob not loading all in memory without to split it in chunks.

**Comment by publicocean0** [comment]
com.orientechnologies.orient.core.index.OIndexException: Composite key cannot contain more than one collection item
when i add a linkedlist in lucene search . in lucene document.addField('a',1), document.addField('a',2)  is automaticaly a list ... because in lucene property is  multivalue for definition

**Comment by publicocean0** [comment]
error present in index.algorithm ... "LUCENE" labels is not more accepted in 3.0 but in documentation is still present. It seams to work using SBTREE

**Comment by publicocean0** [comment]
when i execute indexes command on lucene index 
|36  |D.lucene                                  |FULLTEXT  |      0|D                |       |                |
it is correct no fields is shown ? (3 defined)?

**Comment by smolinari** [comment]
You should probably start a new issue for that. 

Scott

**Comment by publicocean0** [comment]
i did

**Comment by publicocean0** [comment]
all javascript scripts dont works now , added new bug

**Comment by publicocean0** [comment]
the problem related to mapping array and maps in index is because in the orientdb model for mapping **index row** might be updated : **now key-value but a abstract and generic model might be instead key-values(like lucene)**

**Comment by publicocean0** [comment]
all batch scripts dont works , added new bug

**Comment by tglman** [comment]
hi @publicocean0,

About the streaming feature on the query engine a record or a result of a query is an unit that cannot be split in orient today, we add some code for splitting blobs but not much more work has been done on it in 3.0, so far we have to consider a record as a "unit".

Bye

**Comment by publicocean0** [comment]
About the streaming i mean another thing: i create a pseudo code maybe is more clear what i meant:
now is  
b =new OrecordBytes(buffer). where buffer is byte[] type
with new engine it could be more scalable 
b=new OrecordBytes()
b.write(buffer1)
.....(in memory just the current buffer)
b.write(buffer2)
....
In this way in the client and also in the server the ram used for trasffering is always space limited. Considering the case you have many users trasferring files...huge files... you might split file in fine grane (thousands/million of chunks)for permitting high concurrency. 
With outputstream strategy  you have no necessary to split the blob in many chunks. 
In addition I measured the perfomance of streming a long file in real time... using chunks there is a overhead that get lower the bandtwidth. Instead if the you read the file in a unique stream of data the bandwidth could be better.

**Comment by publicocean0** [comment]
Lucene is very important in orientdb because it permits to make searchers in times comparable with traditional dbms. Without lucene over 1 million of rows times get prohibitive
