### ISSUE TITLE
Support of native languages in SQL under IBM Java

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7595]
### OS: ubuntu/alpine(docker)

We have the following SQL:

```sql
select from ReportFact where reportItem.name = "Выручка по проектам"
```

As you can see, this query contains text on native language (russian).
On the same database dump this SQL works perfectly on Oracle JDK and Open JDK, but it returns empty collection under IBM JDK. If change field "name" from russian to some english word (for example "test") - it become working. So the issue is in support of native languages. At the same time IBM JDK works with native languages.

P.S. Due to non related issue with open jdk (not related to OrientDB at all), we wanted temporally switch to IBM Java, but this issue looks even more worst rather than original one.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I did as follows:

- created a docker image with 3.0.0M2 (Dockerfile):

```
FROM ibmjava:jre-alpine

# Override the orientdb download location with e.g.:
#   docker build -t mine --build-arg ORIENTDB_DOWNLOAD_SERVER=http://repo1.maven.org/maven2/com/orientechnologies/ .
ARG ORIENTDB_DOWNLOAD_SERVER

ENV ORIENTDB_VERSION 3.0.0m2

ENV ORIENTDB_DOWNLOAD_URL ${ORIENTDB_DOWNLOAD_SERVER:-http://central.maven.org/maven2/com/orientechnologies}/orientdb-community-gremlin/$ORIENTDB_VERSION/orientdb-community-gremlin-$ORIENTDB_VERSION.tar.gz

RUN apk add --update tar curl \
    && rm -rf /var/cache/apk/*

#download distribution tar, untar and delete databases
RUN mkdir /orientdb && \
  wget  $ORIENTDB_DOWNLOAD_URL \
  && tar -xvzf orientdb-community-gremlin-$ORIENTDB_VERSION.tar.gz -C /orientdb --strip-components=1 \
  && rm orientdb-community-gremlin-$ORIENTDB_VERSION.tar.gz \
  && rm -rf /orientdb/databases/*


ENV PATH /orientdb/bin:$PATH

VOLUME ["/orientdb/backup", "/orientdb/databases", "/orientdb/config"]

WORKDIR /orientdb

#OrientDb binary
EXPOSE 2424

#OrientDb http
EXPOSE 2480

# Default command start the server
CMD ["server.sh"]
```

- launched this from Studio:

```
create class ReportFact;
insert into ReportFact set reportItem = {name : "Выручка по проектам"};
select from ReportFact where reportItem.name = "Выручка по проектам";
```

Everything seems to work fine, do you have any other hints on how to reproduce?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
ops... sorry, wrong release... testing with 2.2.x

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Uhm, same with 2.2.24, here is the dockerfile:

```
FROM ibmjava:jre-alpine

# Override the orientdb download location with e.g.:
#   docker build -t mine --build-arg ORIENTDB_DOWNLOAD_SERVER=http://repo1.maven.org/maven2/com/orientechnologies/ .
ARG ORIENTDB_DOWNLOAD_SERVER

ENV ORIENTDB_VERSION 2.2.24

ENV ORIENTDB_DOWNLOAD_URL ${ORIENTDB_DOWNLOAD_SERVER:-http://central.maven.org/maven2/com/orientechnologies}/orientdb-community/$ORIENTDB_VERSION/orientdb-community-$ORIENTDB_VERSION.tar.gz

RUN apk add --update tar curl \
    && rm -rf /var/cache/apk/*

#download distribution tar, untar and delete databases
RUN mkdir /orientdb && \
  wget  $ORIENTDB_DOWNLOAD_URL \
  && tar -xvzf orientdb-community-$ORIENTDB_VERSION.tar.gz -C /orientdb --strip-components=1 \
  && rm orientdb-community-$ORIENTDB_VERSION.tar.gz \
  && rm -rf /orientdb/databases/*


ENV PATH /orientdb/bin:$PATH

VOLUME ["/orientdb/backup", "/orientdb/databases", "/orientdb/config"]

WORKDIR /orientdb

#OrientDb binary
EXPOSE 2424

#OrientDb http
EXPOSE 2480

# Default command start the server
CMD ["server.sh"]
```

Any thoughts?

Thanks

Luigi

**Comment by PhantomYdn** [comment]
Few comments:

In my case simplified schema is the following:
Class: ReportFact
     Property: reportItem LINK to ReportItem 
Class: ReportItem
    Property: name STRING

I used Java API. And just checked the following: in both JDK String which is going into OrientDB code is the same.

Also my db was created under OpenJDK - not sure that it has sense.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

Any chance to have a simple test case to reproduce?

Thanks

Luigi

**Comment by PhantomYdn** [comment]
Sure - will provide as soon as created and validated

**Comment by PhantomYdn** [comment]
It's becoming even more interesting:

Script:
```javascript
var db = orient.getDatabase();
db.commit();
db.command("create class TestName if not exists");
db.command("create property TestName.name if not exists STRING");
db.command("insert into TestName (name) values ('Тест 1')");
db.query("select from TestName where name = 'Тест 1'")
```

If execute it under IBM Java it will return 1 record, but with question marks (through REST API):

```javascript
{"@type":"d","@rid":"#137:0","@version":1,"@class":"TestName","name":"???? 1"}
```

Now lets try to execute the same code but under Open JDK:

```javascript
{"@type":"d","@rid":"#137:2","@version":1,"@class":"TestName","name":"\u0422\u0435\u0441\u0442 2"}
```

Trying to repeat testcase purely through OrientDB REST.

**Comment by PhantomYdn** [comment]
Testing through purely REST interface (2480 port).
Client: http://yet-another-rest-client.com/

JDK: Open JDK
URL: http://localhost:2480/document/Orienteer
Method: POST
Payload: { "@class" : "TestName", "name" : "Это тест" }
Result:
```javascript
{
  "@type": "d",
  "@rid": "#137:4",
  "@version": 1,
  "@class": "TestName",
  "name": "Это тест"
}
```

Now lets switch to IBM JDK

JDK: IBM JDK
URL: http://localhost:2480/document/Orienteer
Method: POST
Payload: { "@class" : "TestName", "name" : "Это тест2" }
Result:
```javascript
{
  "@type": "d",
  "@rid": "#137:5",
  "@version": 1,
  "@class": "TestName",
  "name": "������ ��������2"
}
```

At least I'm sure that problem is not in our software (http://orienteer.org) :)

**Comment by PhantomYdn** [comment]
![orientdb_ibmjdk](https://user-images.githubusercontent.com/1199285/28822318-7dd3e728-76c1-11e7-86aa-7092feb279c5.png)

**Comment by PhantomYdn** [comment]
Explicit specifying `-Dos.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8` helped with the issue. Not sure, but it seems that this dependency in OrientDB on system encoding within IBM JDK should be somehow fixed. What do you think?

**Comment by robfrank** [comment]
just generated an image for 2.2.26 based on alpine/ibm. repeated your test, all work fine.
I didn't use the system properties you propose. 

![yarc](https://user-images.githubusercontent.com/413587/29770364-000a816a-8bef-11e7-9d4b-1f11b4823870.jpeg)

The jdk version is:

java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr4fp10-20170727_01(SR4 FP10))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20170722_357405 (JIT enabled, AOT enabled)
J9VM - R28_20170722_0201_B357405
JIT  - tr.r14.java_20170722_357405
GC   - R28_20170722_0201_B357405_CMPRSS
J9CL - 20170722_357405)
JCL - 20170726_01 based on Oracle jdk8u144-b01

Please:
- check you jdk version: if older than mine, regenarate your image with docker build --pull
- use the latest orientdb (2.2.26)

**Comment by PhantomYdn** [comment]
@robfrank , point not in orientdb image, but in using OrientDB in a separate image as embedded library. Dockerfile can be found here: https://github.com/OrienteerBAP/Orienteer/blob/master/Dockerfile_ibmjdk  
I can assume that set of bash scripts and etc. from OrientDB can setup required environment. But in case of embedded library it behave as I explained previously.

**Comment by robfrank** [comment]
I'm sorry, but I'm a little bit confused. 
If you use OrientDB as an embedded library, within a completely custom image, IMHO is up to you to provide the right parameters to the JVM. 
Sorry, but I can't get the point: what should be our action? what should provide?

**Comment by PhantomYdn** [comment]
@robfrank, this particular case shows that OrientDB has dependency for encoding which are taken from environment. I think that in case of OrientDB this kind of dependencies is quite dangerous and un-manageable. So I see two options: either document them and make consistent across JVMs or get rid of such dependencies. Imho, second option is better.

**Comment by robfrank** [comment]
The only flag related to encoding set by the server.sh script is
```
-Dfile.encoding=UTF8
```

This flag must be passed to the JVM from the CLI, a syste.setProperty has no effect at all, please read this:

https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding

So, AFAIK, there's nothing we can do inside the java code to overcome the problem when orientDB is used embedded.

**Comment by PhantomYdn** [comment]
But -Dfile.encoding=UTF8 didn't help for IBM JDK. Only explicitly those flags mentioned below. Bug in JVM from your perspective?

**Comment by robfrank** [comment]
Really don't know. 
But, look at this: https://helios.orientdb.com/job/2.2.x/job/orientdb-2.2.x-ibm-jdk8/488/testReport/com.orientechnologies.lucene.test/LuceneIssuesTest/testGh_issue7513/

We have a job that runs test on a docker slave with IBM Jdk.

The failing test is:

```java
  @Test
  public void testGh_issue7513() throws Exception {

    InputStream stream = ClassLoader.getSystemResourceAsStream("testGh_7513.osql");

    db.command(new OCommandScript("sql", getScriptFromStream(stream))).execute();

    List<ODocument> documents = db
        .query(new OSQLSynchQuery<Object>("select rid from index:Item.content where key lucene 'Харько~0.2' limit 3 "));

    Assertions.assertThat(documents).hasSize(3);

```

So, seems that the problem with encoding is present at a lower level, other than on HTTP.

**Comment by robfrank** [comment]
Adding -Dfile.encoding=UTF-8 let the build be green:

https://helios.orientdb.com/job/2.2.x/job/orientdb-2.2.x-ibm-jdk8/489/
