### ISSUE TITLE
Delete command with RETURN COUNT statement throws Error parsing query

### ISSUE THREAD

**Issue by SolidSnakeBA** [orientechnologies/orientdb#7598]
## Expected behavior  
`delete from Contact return COUNT where name = 'Bob'` should return number of deleted records (command without `return COUNT` works) 

## Actual behavior  
Returns error `Error parsing query: delete from Contact return COUNT where name = 'Bob' ^ Encountered " <COUNT> "COUNT "" at line 1, column 28. Was expecting: <BEFORE> ... DB name="amc"`

## Steps to reproduce  
`delete from Contact return COUNT where name = 'Bob'`

Not sure if [documantation](http://orientdb.com/docs/last/SQL-Delete.html) is outdated or it is a bug

**Comment by lvca** [comment]
@luigidellaquila it looks like you forgot to add COUNT in the new parser.

**Comment by luigidellaquila** [comment]
Yep, it seems so, I'll fix it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed on 2.2.x branch, the fix will be released with 2.2.26

Thanks

Luigi
