### ISSUE TITLE
howto: SELECT FROM class1 WHERE (multiple-columns) IN (SELECT multiple-columns FROM class2)  ?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7599]
### OrientDB Version: 2.2.25

I need the following:
- from "class1", select some properties based on criteria
- from "class2", select the documents that have the same properties equal to the values of the properties from the first query

In classic databases:
```
SELECT * FROM class2 WHERE (a, b, c) IN (SELECT d, e, f FROM class1 WHERE somecriteria)
```

How can this be done with OrientDB?

A multi-property index exists in "class2" on these 3 properties "a", "b" and "c" ; so I would be tempted to run something like
```
SELECT expand(@rid) FROM index:idx_class2 
WHERE key IN (SELECT d, e, f FROM class1 WHERE somecriteria)
```
but this is rejected with a quite meaningless syntax error message
```
Error: java.lang.ClassCastException: com.orientechnologies.orient.core.sql.query.OSQLSynchQuery cannot be cast to java.util.List
```
Even more confusing:
```
SELECT expand(@rid) FROM index:idx_class2 
LET keys = (SELECT d, e, f FROM class1 WHERE somecriteria) 
WHERE key IN [ $keys ]
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Operator IN not supported yet.
        DB name="mobile"
        DB name="mobile"
```
However, according to http://orientdb.com/docs/2.2.x/SQL-Where.html#operators, the "IN" operator is a documented, hence supported (?) operator.

**Comment by rdelangh** [comment]
hi @luigidellaquila , can I get any feedback on this topic, please?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

If I'm not wrong it's not supported for now (you can try with square brackets, but I doubt it will work) but I still have to check

Thanks

Luigi

**Comment by rdelangh** [comment]
@luigidellaquila 
the problem we have, is that OrientDB does not support a MERGE statement : 
- i have records in one class, say "class1", that need to migrate (with some extra values or properties) towards another class say "class2"
- it is possible that such destination records in "class2" do already exist; in that case, we need to MERGE the records from "class1" with the already existing records in "class2"
- this must be done not for some very few samples, but for many 10000's of records, so bulk actions are highly desired

When this is not possible (sigh), then we must go through a cumbersome alternative:
- first identify the existing records in "class2" that we would otherwise MERGE with
- this means that we must identify first the records in "class1" that we would like to migrate towards "class2", and we do this with our specific criteria to select them from "class1":
```
SELECT FROM class1 WHERE criteria1
```
- from these records of "class1", certain properties have been copied into the new records that we might already have in "class2" ; say these are properties with names P1, P2 and P3 ; I would therefor hope that ODB supports a syntax where I can select the records in "class2" based on the values of 3 properties in the records found in "class1":
```
SELECT FROM class2 WHERE (P1, P2, P3) IN (SELECT P1, P2, P3 FROM class1 WHERE criteria1)
```
- if that would be supported, then I can use the RIDs from that last statement (= the record-IDs in "class2") to delete those records from "class2"
```
DELETE FROM (SELECT @rid FROM class2 WHERE (P1, P2, P3) IN (SELECT P1, P2, P3 FROM class1 WHERE criteria1))
```
- all this, because no MERGE exists in the ODB syntax, because after I assured with the DELETE that no conflict can happen anymore with records already existing in "class2", I would finally do an INSERT of the to-be-migrated records from "class1" into "class2" : 
```
INSERT INTO class2 FROM SELECT P1, P2, P3, ... FROM class1 WHERE criteria1
```

Terribly inefficient, because this would need to happen each time over again, when the records in "class1" would need to be merged again with those in "class1" ...
Not a few records, but in the course of a day it would be some millions of records.

-> any suggestions for an alternate, efficient way of obtaining this with ODB are highly welcome !

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

little update here, I just checked it in 3.0 and it works fine with square brackets

Thanks

Luigi

**Comment by rdelangh** [comment]
hi @luigidellaquila , thanks for your follow-up.
When checking the website of OrientDB releases, mid December-2017 the Release-Candidate for version 3.0 was presented, with the remark that it is still not considered as a "stable release". More: "but please wait for the GA (coming in next few weeks) " 
-> can you please give a hint of how many of such "next few weeks" we might be expecting a stable release 3 ? Many required features are announced in v3 ...
