### ISSUE TITLE
Feature Request: Preceding and Following

### ISSUE THREAD

**Issue by DEVOPSIO21** [orientechnologies/orientdb#7600]
## Expected behavior  
Function to call preceding and following row of select results. 

The use case is for analytical functions. 

The syntax would be something like the following. 

```sql
select 
	name,
	age as Current_Age,
	preceding(age) as Preceding_age,
	following(age) as Following_age
from members
``` 

The results would give the preceding or following row results of a particular property, based on the current row.

## Expected Results

---
#### **No `Order by`**
| name | Current_Age | Preceding_age | Following_Age |
| -------- | -------- | -------- | -------- |
|   John   |   36   | `null`     | 30  |
|   Albert   |   30   |  36    | 19 |
|   Erick   |   19   |  30    | 25 |
|   Elizabeth   |   25   |   19   | 16  |
|   Janet   |  16    |   30   | `null`  |

----
#### **Results, ordering by age ascending - `order by age asc`**
| name | Current_Age | Preceding_age | Following_Age |
| -------- | -------- | -------- | -------- |
|   Janet   |  16    | `null`     |19 |
|   Erick   |   19   |  16    |  25  |
|   Elizabeth   |   25   |  19    | 30  |
|   Albert   |   30   |  25    |  36 |
|   John   |    36  |  30     | `null`  |

----
#### **Results, ordering by age descending - `order by age desc`**
| name | Current_Age | Preceding_age | Following_Age |
| -------- | -------- | -------- | -------- |
|   John   |    36  |  `null`     | 30  |
|   Albert   |   30   |  36    |  25 |
|   Elizabeth   |   25   |  30   | 19 |
|   Erick   |   19   |  25    |  16 |
|   Janet   |  16    | 19     |`null` |

**Comment by DEVOPSIO21** [comment]
Hi lvca / luigi. 

does it getting a label added mean this is potentially going into dev queue ?

**Comment by luigidellaquila** [comment]
Hi @DEVOPSIO21 

Yes, we are taking it into consideration. From a first analysis, adding this feature in v 2.2.x is quite complex, but probably in v 3.0 it will be easier

thanks

Luigi

**Comment by careerscale** [comment]
+1, this might help me too. so with 3.0?

**Comment by luigidellaquila** [comment]
Yes, I'd say we can work on it for 3.0

I'll follow up with some more ideas to define implementation details, if you have any specific requirements please let me know

Thanks

Luigi

**Comment by DEVOPSIO21** [comment]
Hi Luigi, 

Yes, I am sure it makes more sense for v3.0 +. Was not expecting it for 2.2 branch. 

This type of functionality will open up a easier path of being able to do MA (Moving Averages). Is there a way for me to see what's in the development queue / road map. I want to see what new `Features` are planned, it will help me put together some specific ideas related to this for your review.

I have a ton of Analytical functionality **Wish List** and do not want to overwhelm the OrientDB dev team with feature request. Instead, want to review what's already being planned and keep any further input from my side focused on the initial request. 

Thanks,

**Comment by DEVOPSIO21** [comment]
Hi Luigi, 

Has the dev team considered this any further ? This ties back to a recent question i opened up about moving averages.

**Comment by luigidellaquila** [comment]
Hi @DEVOPSIO21 

Sorry, for now we did not do any progress on this, I'll keep you updated as soon as we do

Thanks

Luigi
