### ISSUE TITLE
REQUEST_RECORD_UPDATE update-content=false ignored 

### ISSUE THREAD

**Issue by pvalsecc** [orientechnologies/orientdb#7603]
## Expected behavior  
When I call the binary (document) protocol (v36), the command REQUEST_RECORD_UPDATE with update-content=false, I was expecting two things:

* The version to remain the same.
* To have to mention only the linkbag and not the rest of the fields.

## Actual behavior  

Here is the message I've sent:
`0x2000000115000900000000000000000000000037000256086F75745F000000221608746F746F00000031010874757475000000320700010000000100110000000000000000540874757475000000016400`

Here is the answer I've got:
`0x00000001150000000200000000`

As you can see, the record version went from 1 to 2 and I had to repeat all the fields (otherwise, the record looses all its fields if I try to read it back).

## Steps to reproduce  

Create 2 documents of class V with a few fields, create a document of class E linking the 2 previous V documents. Update the 2 documents of class V with "in_" and "out_" linkbag fields (with or without repeating the other fields) that points to the edge and set the update-content option to false. You'll see that the version of the records are incremented.

**Comment by tglman** [comment]
hi @pvalsecc,

The flag `udpate-content=false` is used only for mark records where the only content changed was the LinkBag Tree (for embedded ridbag you need to send all content), you have to send the whole record anyway and have the LinkBag Tree changes inside the field of the LinkBag, The protocol do not support partial records so in any case you need to send all.

Just out of curiosity, are you implementing a client? you know the binary protocol is not really for end user purpose. 
Regards

**Comment by pvalsecc** [comment]
OK, I see, now. Thanks.

I'm working on an Erlang client library (mostly for fun). Actually, I'm working on a fork of https://github.com/tabinin/odi which has been left along for quite a long time and that is implementing a protocol too old for my needs.

You can find my fork there: https://github.com/pvalsecc/odi
