### ISSUE TITLE
Documentation for map() function

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/orientdb#7605]
I didn't know if this was the best place to raise this issue, but here we go:

https://orientdb.com/docs/2.1/SQL-Functions.html#map

I believe the documentation is incomplete. I found by accident that we can map an infinite number of keys to an infinite number of values

The query
`select map("a", 1, "b", 2, "c", 3)`

Returns the following object, but the doc is not clear.
`{"a":1,"b":2,"c":3}`

**Comment by luigidellaquila** [comment]
Hi @igasparetto 

Thank you very much, the docs are definitely not clear.
I'm fixing them

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Done, the docs will be re-generated in a few minutes

Thanks

Luigi
