### ISSUE TITLE
problem with new class ODatabaseDocumentRemote 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7607]
### OS: linux  

i m converting my project to 2.2.14 to 3.0.m2 ... i have a problem 
with a class
com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote 

is not convertible to com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx

 db = new OObjectDatabaseTx((ODatabaseDocumentTx)db); 

the exception is here 

pratically db is current active db connection in the thread and i want resuse it also for object db

It is part of a old litle framework ... having this problem now: it retrieve the current active connection if present else get a new one from pool. In this section it reuse the same connection

**Comment by tglman** [comment]
hi @publicocean0,

If you are not mixing object and document database I would suggest to use "OrientDBObject" that hide away the conversion, if you still need some way this conversion you should do instead `new OObjectDatabaseTx((ODatabaseDocumentInternal)db);` anyway this is using a kind of implementation detail, so let us know if this is a really use case that you need and we will try to provide a more ergonomic API for the case.

Thank you to try out the M2.

Regards

**Comment by publicocean0** [comment]
oh sorry I solved it
