### ISSUE TITLE
upsert failed on edge

### ISSUE THREAD

**Issue by HuangKBAaron** [orientechnologies/orientdb#7609]
## Expected behavior  
edge should link two vertexes.  

## Actual behavior  
there is a record of one edge and 2 vertexes created, but they are not linked together.
![image](https://user-images.githubusercontent.com/14175239/28994690-fd1b410a-7a06-11e7-951c-503ce53e1629.png)
there is an edge recorded.
![image](https://user-images.githubusercontent.com/14175239/28994695-1cf0b00a-7a07-11e7-95ce-e73e29bcfaf6.png)
the OUT color of the edge is different to the IN. 
Try with this creation script:
CREATE EDGE e_has_model FROM #21:0 TO #25:0
and then query e_has_model:
![image](https://user-images.githubusercontent.com/14175239/28994746-141b9624-7a08-11e7-811d-2ae431953684.png)

Also, the "CREATE VERTEX" returns an OrientRecordLink object, and the "UPDATE...UPSERT..RETURN AFTER.." returns an array with one OrientRecordLink in it. Verified it by return them from the Batch script:
`{'vol': '#17:0', 'model': ['#21:0']}`

Changed the Batch script to:
```
BEGIN;
LET vol=CREATE VERTEX v_volume SET f_year=2018,f_quantity=60,f_recorded='2017-08-05 16:27:56';
LET model=UPDATE v_model SET f_name='P1', f_recorded='2017-08-05 16:27:56' UPSERT RETURN AFTER @rid WHERE f_name='P1';
LET vol1 = SELECT FROM v_volume WHERE @rid=$vol;
UPDATE e_has_model SET OUT=$vol, IN=$model, f_recorded='2017-08-05 16:27:56' UPSERT WHERE OUT=$vol AND IN=$model;
COMMIT RETRY 100;
RETURN (SELECT $vol as vol, $vol1 as vol1);
```
it returns:
`{'vol': '#17:0', 'vol1': None}`
If change "LET vol1 = SELECT FROM v_volume WHERE @rid=$vol;" to "LET vol1 = SELECT FROM v_volume WHERE @rid in $vol;". It returns as expected (but in an array):
`{'vol': '#17:0', 'vol1': ['#17:0']}`

How try to figure out the edge issue by change batch script to:
```
BEGIN;
LET vol=CREATE VERTEX v_volume SET f_year=2018,f_quantity=60,f_recorded='2017-08-05 16:27:56';
LET model=UPDATE v_model SET f_name='P1', f_recorded='2017-08-05 16:27:56' UPSERT RETURN AFTER @rid WHERE f_name='P1';
LET vol1 = select from v_volume where @rid in $vol;
LET model1 = select from v_model where @rid in $model;
UPDATE e_has_model SET out=(select from v_volume where @rid in $vol), in=(select from v_model where @rid in $model), f_recorded='2017-08-05 16:27:56' UPSERT WHERE out IN (select from v_volume where @rid in $vol) AND in IN (select from v_model where @rid in $model);
COMMIT RETRY 100;
return (select $vol as vol, $model as model, $vol1 as vol1, $model1 as model1);
```
query by "select * from `e_has_model`", returned
![image](https://user-images.githubusercontent.com/14175239/29054593-aac216ca-7c29-11e7-8bb2-abcb54a49da1.png)
it is interesting that what in in/out is rid but not an array of rids, as observed above. 
Try to query from VERTEX with "select * from v_volume", returned
![image](https://user-images.githubusercontent.com/14175239/29054700-46bd80c8-7c2a-11e7-9f24-46d6499ead00.png)
no 'out' presented. Now I only got half of solution. 

### DB CREATION script:
```
CREATE CLASS v_volume EXTENDS V;
CREATE PROPERTY v_volume.f_quantity Decimal;
CREATE PROPERTY v_volume.f_recorded Datetime;
CREATE CLASS v_model EXTENDS V;
CREATE PROPERTY v_model.f_name STRING;
CREATE PROPERTY v_model.f_recorded Datetime;
CREATE CLASS e_has_model EXTENDS E;
CREATE PROPERTY e_has_model.f_recorded Datetime;
```

### Batch script：
```
BEGIN;
LET vol=CREATE VERTEX v_volume SET f_year=2018,f_quantity=60,f_recorded='2017-08-05 16:27:56';
LET model=UPDATE v_model SET f_name='P1', f_recorded='2017-08-05 16:27:56' UPSERT RETURN AFTER @rid WHERE f_name='P1';
UPDATE e_has_model SET OUT=$vol, IN=$model, f_recorded='2017-08-05 16:27:56' UPSERT WHERE OUT=$vol AND IN=$model;
COMMIT RETRY 100;
```

**Comment by HuangKBAaron** [comment]
p.s. The '@' with low-case 'rid' is misunderstood by github and reference to a github user.

**Comment by HuangKBAaron** [comment]
@luigidellaquila, do you mind to take a look?

**Comment by luigidellaquila** [comment]
Checking it now

**Comment by luigidellaquila** [comment]
Hi @HuangKBAaron 

I just checked your script, the problem here is that you are not creating an edge!!!
The right syntax to create an edge is `CREATE EDGE`, not `UPDATE...UPSERT`, the UPDATE works at document level and does not create the connections properly:

```
CREATE EDGE e_has_model FROM $vol TO $model SET f_recorded='2017-08-05 16:27:56' 
```

Right now there is no UPSERT defined for edges, so if you need it you have to find a work-around (eg. do a SELECT and check if the edge already exists)

Thanks

Luigi

**Comment by HuangKBAaron** [comment]
I am trying other scripts, and found some interesting facts. with the "update/upsert", "in/out" has to be "in/out", not "IN/OUT", server would treat "IN/OUT" as common properties of the edge, that is, not treat as "FROM/TO".

Another fact:
The following script MAKE 'update' and 'CREATE EDGE' the same result same as:
`UPDATE e_has_model SET in=$vol, in=$model[0], f_recorded='2017-08-05 16:27:56' UPSERT WHERE out in $vol AND in in $model;`
`CREATE EDGE FROM $vol TO $model[0];`

**Comment by HuangKBAaron** [comment]
@luigidellaquila,
got it. So is it possible to add it in next release? it quite useful feature.

**Comment by luigidellaquila** [comment]
Hi @HuangKBAaron 

Yes, we have an open issue for that, it will likely be in 3.0 GA

Thanks

Luigi

**Comment by HuangKBAaron** [comment]
thx your effort!
