### ISSUE TITLE
delete edge by a where cause failure

### ISSUE THREAD

**Issue by HuangKBAaron** [orientechnologies/orientdb#7611]
## Expected behavior  
The script should be passed. It passed on 2.2.20.
delete edge where @class like 'e_%'

## Actual behavior  
It failed with error message:
java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.ORecordLazyList cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable

## Steps to reproduce  
delete edge where @class like 'e_%'

**Comment by luigidellaquila** [comment]
Hi @HuangKBAaron 

Thank you for reporting, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @HuangKBAaron 

I tried to reproduce this issue, but with no success, can you provide a dataset where it fails?

Thanks

Luigi

**Comment by HuangKBAaron** [comment]
It was cause by misusing update/upsert to edge, after changed to "create edge", it won't repro. So close it now.
