### ISSUE TITLE
error in lucene index 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7612]
### OS: linux

there are 2 problems (one critical , one not critical) :
 
critical when i create index programmatically index is created but is not working
instead if i create using console it works

	oc.createIndex(n, o.name,null, d, o.algorithm(), o.fields());
where algorithm is LUCENE
          name is FULLTEXT
        fields are a,b,c

not critical : in the indexes command the table dont show fields when is lucene

**Comment by publicocean0** [comment]
problem with old javascript scripts
var a=db.command(....)
a.field('code') dotn works

**Comment by robfrank** [comment]
The test: 
https://github.com/orientechnologies/orientdb/blob/develop/lucene/src/test/java/com/orientechnologies/lucene/tests/OLuceneCreateJavaApiTest.java

uses the java api to create lucene index. Is your code similar?

about:
"problem with old javascript scripts var a=db.command(....) a.field('code') dotn works"

I don't understand what are you meaning.

**Comment by publicocean0** [comment]
about first question 
 OIndex<?> lucene = song.createIndex("Song.author_description", OClass.INDEX_TYPE.FULLTEXT.toString(), null, null, "LUCENE",
        new String[] { "author", "description" });

i see a different in the fourth parameter you pass null instread i pass document. I will try to remove d... 


about second question: it is not related with this problem : javascript api is changed but they was not compltetely committed. There also now a missing info about doc.identity ... not working in 3.x.

**Comment by robfrank** [comment]
"about second question: it is not related with this problem : javascript api is changed but they was not compltetely committed. There also now a missing info about doc.identity ... not working in 3.x." 

Please open another issue, I will not care about it, thanks

**Comment by publicocean0** [comment]
it seams all solved
