### ISSUE TITLE
lucene error if i create a index containing a linkedlist(even if in the schema)

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7614]
### Java Version: 8

 CREATE INDEX P.lucene ON Profile(code,list,list2,name) FULLTEXT ENGINE LUCENE
Composite key cannot contain more than one collection item

**Comment by publicocean0** [comment]
The problem related to mapping array and maps in index is because the orientdb model for mapping index row might be updated : now is key-value but a abstract and generic model might be instead key-values(like lucene). It permits to handle embedded object, array. In addition this solution emprove also performance ... because there are loops and preprocessing calculations in the old code (i had overviewed version 2.x) could be removed

**Comment by robfrank** [comment]
As the error message states, you can only have ONE list/map on a multi-field index. The API you are complaining about could be right or wrong, it depends on the POV. The index interface/infrastructure is general, not necessarily targeted to Lucene and its document model. For the time being, we are not planning to change this internal.

**Comment by robfrank** [comment]
This is more a question than an issue. Please post it on StackOverflow http://stackoverflow.com/questions/tagged/orientdb

**Comment by publicocean0** [comment]
there is th same error also if there is 1 list.

**Comment by robfrank** [comment]
Can you provide a test case? Some code I can try? Because we have tests on indexing list:

https://github.com/orientechnologies/orientdb/blob/develop/lucene/src/test/java/com/orientechnologies/lucene/tests/OLuceneListIndexingTest.java

What's wrong with this test? Or better: what are the differences with your code/schema?

**Comment by publicocean0** [comment]
CREATE INDEX P.lucene ON Profile(code,list,name) FULLTEXT ENGINE LUCENE

list is a list field

**Comment by robfrank** [comment]
So it's the same of our tests? Did you check the linked source? 
Can you provide the schema too? CREATE CLASS... CREATE PROPERTY..
