### ISSUE TITLE
Cannot connect to remote:/localhost/demodb with java API

### ISSUE THREAD

**Issue by BrunoSupiot** [orientechnologies/orientdb#7615]
## Expected behavior  
<Trying to connection to remote:localhost/demodb with Java interface on the localhost server>  

## Actual behavior  
<java.io.IOException: Timeout on reading response at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:249) at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:176) at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1274) at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1309) at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1254) at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:392) at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.internalOpen(ODatabaseDocumentRemote.java:144) at com.orientechnologies.orient.core.db.OrientDBRemote.open(OrientDBRemote.java:82) at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:209) at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:194) at >  

## Steps to reproduce  
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// try to connect with OrientDB 3.0 unified interface
		connectWithUnifiedInterface();
		}
	}

	/**
	 * connect with Orientdb 3.0 interface
	 */
	public static boolean connectWithUnifiedInterface() {
		try  {
		// connect to remote database engine
		OrientDB orientDb = new OrientDB("remote:localhost", "root", "root", 
                 OrientDBConfig.defaultConfig());

		// open a session on the database
		ODatabaseDocument session = orientDb.open("demodb", "admin", "admin");

		session.close();
		orientDb.close();

		// Runtime exception will be thrown if any problem has occured
		return true;
		} catch (Throwable ex) {
			ex.printStackTrace();
			return false;
		}
	}

**Comment by maggiolo00** [comment]
Hi @BrunoSupiot 

which version of OrientDB do you have in your `pom.xml` ?

**Comment by BrunoSupiot** [comment]
Hi.
Sorry,  I forgot to refresh gradle project under Eclipse, so the java libraries was already in the 3.0.0m1 version.
Thanks for your anwser
