### ISSUE TITLE
strange error in console after a previous error(error not removed by queue?)

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7616]
### Java Version: 8  
 
 select * from account

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot close query: 1502096601482_874

The reason is when you executed a previous query giving a exception. The error remains enqueed. For simulate bug you can execute before a wrong query. Then execute a correct query

**Comment by tglman** [comment]
Hi,

This should be already solved in the last snapshot with proper query close management in console, could let us know if you can still reproduce it.

Regards

**Comment by publicocean0** [comment]
ok now i passed in another activity ... i will test surelly after it ... so in the while maybe also other issues notified will be solved ,so i will do just final test.

**Comment by tglman** [comment]
Hi,

This is fixed and i released in the m2, closing.

Regards
