### ISSUE TITLE
batch scripts dont works now

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7617]
### Java Version: 8
```

let a = select from account

return $a


Error parsing query:

  ^
Encountered " <LET> "let "" at line 1, column 1.
Was expecting one of:
    <IF> ...
    <FOREACH> ...
    ";" ...
    <IF> ...
    

	Error Code="1" [ONetworkProtocolHttpDb]


```

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

I think most of your problems arise from a change of convention in 3.0.

Until v 2.2 batch scripts considered newline as a statement delimiter; it was a problem in general and an inconsistency compared to normal SQL queries, where newlines were just ignored.
Just add a `;` at the end of each statement, it should solve the problem.

For reference: http://orientdb.com/docs/3.0.x/release/3.0/SQL-Changes.html#changes-in-the-way-batch-script-commands-are-separated

Thanks

Luigi

**Comment by publicocean0** [comment]
let a = select from account ;  return $a ;
                                    ^
Encountered " <RETURN> "return "" at line 1, column 32.

**Comment by luigidellaquila** [comment]
Just tried it from Studio and it seems to work fine...

How are you testing it?

Thanks

Luigi

**Comment by publicocean0** [comment]
i m using studio too. 
2017-08-06 17:46:19:968 INFO  Loading configuration from: /data/orientdb/releases/orientdb-community-3.0.0m2/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2017-08-06 17:46:20:460 INFO  OrientDB Server v3.0.0m2 (build 4abea780acc12595bad8cbdcc61ff96980725c3b) is starting up... [OServer]

logs confirmed version running is 3

**Comment by publicocean0** [comment]
i m using linux maybe a problem with newline?

**Comment by luigidellaquila** [comment]
Silly question maybe, but did you set the execution mode to BATCH?

The problem should not be with the newline, most of us use Linux or Mac, so we should have found it before...

Thanks

Luigi

**Comment by publicocean0** [comment]
ops it was it ahahah i forgot to reset it after session expire. Ok it is sufficient add ;

**Comment by luigidellaquila** [comment]
😄 Excellent, thanks for the feedback!

Luigi
