### ISSUE TITLE
ODatabaseException when creating an index

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#7619]
### OS: Windows  

The following script crashes when it tries to create the index.

```
CREATE CLASS    Foo EXTENDS V;

CREATE CLASS    Bar EXTENDS E;
CREATE PROPERTY Bar.in   LINK Foo;

CREATE PROPERTY Foo.id STRING;

CREATE INDEX Foo.id NOTUNIQUE;

// CREATE INDEX FooIndexId ON Foo (id) NOTUNIQUE;

exit;
```

The following exception is thrown:

```
Creating index...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Impossible to create an index without specify the key type or the associated property: CREATE INDEX Foo.id NOTUNIQUE
	DB name="foo_integration"
```

Remarks:

- It works with OrientDB 2.2.25.
- The 2nd statement for creation of the index works.
- If the statements creating the edge are removed then the creation of the index works.

**Comment by tglman** [comment]
hi @diegomtassis,

since 3.0 we deprecated the association of the index by field name, now you need to specify the property when you create the index, in the way your comment create index does.

Regards

**Comment by diegomtassis** [comment]
Ok, but the change is not reflected in the documentation.
http://orientdb.com/docs/3.0.x/indexing/Indexes.html

**Comment by tglman** [comment]
hi @diegomtassis,

I updated the documentation removing the case, i'm closing this.

Regards
