### ISSUE TITLE
strange timeout in index query

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7621]
### OS: linux

 select from index:Cl.i_name where key = #23:17

Error: com.orientechnologies.common.io.OIOException: Read timed out

Error: java.net.SocketTimeoutException: Read timed out

after this error there is another bug notified 
 select from index:Cl.i_name where key = #23:14
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot close query: 1502119385137_980
	DB name="s"
	DB name="s"

every following execution of this query give same second exception

**Comment by tglman** [comment]
Hi @publicocean0,

I fixed the problem with the close query recently, the other error seems just a network issue or similar(server going down), could you try with the lastest 3.0 shanpshot ?

Regards

**Comment by tglman** [comment]
Hi, 

This should definitely be fixed in the RC, closing
