### ISSUE TITLE
Use unsigned int as index of page in disk cache instead of long

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7629]
Usage of unsigned int instead of long will allow to address files up to 64TB and will allow reducing space consumed by all types of indexes and increase database performance in general

**Comment by lvca** [comment]
Do you mean 64TB per page, index or database?

**Comment by laa** [comment]
Single size of file will be limited to 64TB

**Comment by lvca** [comment]
So in our case would be indexes and cluster files, right? In this case seems more than reasonable to me.

**Comment by lvca** [comment]
Also, we should be retro-compatible and work with previous binary format.

**Comment by laa** [comment]
Yes, that is why I created an issue, it will require quite of work to be backward compatible. Change itself is not so big.
