### ISSUE TITLE
Decrease value of storage.lowestFreeListBound property from 16 to 1

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7630]
If we decrease the value of this property we will be able to add up to 25% more records in a single page, which obviously will decrease the amount of space consumed by data and will increase database speed in general.

**Comment by lvca** [comment]
+1

**Comment by laa** [comment]
Even better to change free list in such way that it will track free pages with gradually decreased free sizes starting from 1k till 64 bytes.
