### ISSUE TITLE
Exception during load test on remote storage and noticeable slowdown

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7634]
### OrientDB Version: 3.0
We tried to reproduce issue https://github.com/orientechnologies/orientdb/issues/7610 and created following load test https://gist.github.com/laa/82a0fe264ecf8120458acbf769949da8 . On @taburet machine we get 

```
* embedded
2.2.x: 2260 qps
develop: 1320 qps

* remote
2.2.x: 850 qps
develop: 200 qps
```

So remote storage performance was decreased at 2.4 times. (on 2.2.x remote storage is 1.7 times slower on 3.0 remote storage is 4.3 times slower) we found the reason for the slowdown of embedded storage and fixed it. But the reason of slowdown of remote storage also should be fixed. 
Also when I tried to run the same load test on my machine after a while (load test was running already for about a minute I got https://gist.github.com/laa/2c8f6122ffbb855aa80bb0dd81558743) Which should be fixed too.

**Comment by tglman** [comment]
Hi,

I ran a few tests and I didn't notice any huge difference in performance between 2.2.x and develop, to notice that if you use an old version of the client against the new server it may work (but is not guaranteed to) with some minor failures that may cause a visible slow down, so please be sure that the server and the client are of the same version.

From my test I consider this closed.

Regards

**Comment by laa** [comment]
@tglman did you mean that you run tests provide in gist too. Is my understanding correct?

**Comment by tglman** [comment]
Hi, 

Yes I tried it and readapted also to try different api, seems all "in the right performance range".

Regards

**Comment by laa** [comment]
OK, it is already fixed then. Closing.
