### ISSUE TITLE
explain order of execution of a batch with multiple transactions

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7637]
## Expected behavior  
Via REST-API, I send a batch of some 300 individual SQL transactions to the server, as one long JSON string.
Each transaction is composed as
```
 {"type": "script", "language": "sql", "script": "begin; ... ; commit; " }
```
The JSON string is then composed as
```
{ "transaction": true, "operations": [ <comma-separated-list-of-transactions> ] }
```
I was expecting that the transactions in this JSON batch are executed in sequence, so that the first transaction is COMMITed before the next transaction is started.

## Actual behavior  
However, some of the transactions collide with each other: one transaction inserts a new record, a next transaction searches for that record and -if it exists- does an update of the existing record, or -if the record is not found- does an insert of the record.
What I encounter, is that such second transaction does NOT find the record which was inserted by the previous transaction of the same batch. So that second transaction attempts to insert the same record, but is blocked by a unique index key for that record.

I have the impression that other transactions in the same batch have been executed despite that one failing transaction (with the duplicate index key).

So this makes me wonder if the different transactions in a batch are executed independently (might explain the race-condition of these transactions that try both to act on the same record, both inserting), or in sequence (in this case there should not be a collision of the transactions which try both to act on the same record, first would insert, next would find it and hence update it without collision).

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

This is quite strange, the operations are supposed to be executed in the same order as they appear in the json.

I'll check it and let you know

Thanks

Luigi

**Comment by yocoman31** [comment]
Hi 

I have the same problem with OrientDB version 2.2.31 but not in the version 2.1.9. I have to update my app to V2.2.x and now my script crash because of the order of execution which is inverted
Someone know how to fix that ?

Thanks

Yoni
