### ISSUE TITLE
Add null keys support for MVRBTree indexes [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#764]
This is [Issue 764](http://code.google.com/p/orient/issues/detail?id=764) moved from a Google Code project.
Added by 2012-03-24T19:32:38.000Z by [lomakin....@gmail.com](http://code.google.com/u/110615750300902819680/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, v2.0, uateam
### Original description

```
Currently null keys are not allowed in indexes, but I found that newcomers , still use indexes with null keys, that is not big problem to use null marker value, but it will be more convenient to support null keys in simple and composite keys.

It can be implemented by using NullWrapper object  that will be less than any provided value, but will equals to itself.

Also “is null”  query in  SQL queries will be optimized..

NullWrapper could have a static INSTANCE to avoid to create multiple objects but just 1 per JVM
```

**Comment by TeamXceleratorDev** [comment]
So what is the recommended way to leverage an index where part of a composite key is NULL.  For example, select expand(rid) from INDEX:MHEntity.entityType_owner_id_status where key = [#23:4,NULL,'G3P8TYQ1E7EXQ02Z',#18:0].  This statement returns no rows though it should.  Passing "NULL" is OK for syntax, but doesn't yield correct results using 2.0.12.
