### ISSUE TITLE
api is changed doc.identity in doc.getProperty('@rid') or bug? 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7640]
### Java Version: 8

in javascript api `doc.identity` dont show rid 
do you confirm we have to use `doc.getProperty('@rid')` for migrations?

In addition there is a error compiling develop branch .... 

```
INFO] Reactor Summary:
[INFO] 
[INFO] OrientDB ........................................... SUCCESS [  1.653 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [  1.859 s]
[INFO] OrientDB Core ...................................... SUCCESS [ 17.773 s]
[INFO] OrientDB Client .................................... FAILURE [  2.739 s]
[INFO] OrientDB Object .................................... SKIPPED
[INFO] OrientDB Tools ..................................... SKIPPED
[INFO] OrientDB Server .................................... SKIPPED
[INFO] OrientDB GraphDB ................................... SKIPPED
[INFO] OrientDB Tests ..................................... SKIPPED
[INFO] OrientDB Distributed Server ........................ SKIPPED
[INFO] OrientDB Lucene full text index .................... SKIPPED
[INFO] OrientDB JDBC Driver ............................... SKIPPED
[INFO] OrientDB ETL ....................................... SKIPPED
[INFO] OrientDB Community Distribution .................... SKIPPED
[INFO] OrientDB Community Distribution Tinker Pop 2 ....... SKIPPED
[INFO] orientdb-crashtests ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.349 s
[INFO] Finished at: 2017-08-10T12:37:02+02:00
[INFO] Final Memory: 42M/771M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project orientdb-client: Could not resolve dependencies for project com.orientechnologies:orientdb-client:jar:3.0.0-SNAPSHOT: Could not find artifact com.orientechnologies:orientdb-core:jar:tests:3.0.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
```

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

If you have a document (an OElement), you have to use `doc.getIdentity()` 

If you have an OResult, you have to use  `doc.getIdentity().orElse(null)`

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Let me check the compile error, here in my machine everything seems to work fine, but maybe it's due to maven cache

Thanks

Luigi

**Comment by publicocean0** [comment]
yes i think there is a old test lib name in the pom before com.orientechnologies:orientdb-core:jar:tests-3.0.0-SNAPSHOT now maybe orientdb-test-commons-3.0.0-SNAPSHOT

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

could you please post the command you are using to build?

Thanks

Luigi

**Comment by publicocean0** [comment]
mvn clean install -Dmaven.test.skip=true

**Comment by luigidellaquila** [comment]
Could you please try to launch it once with

`mvn clean install`

and see if all the dependencies are correctly generated?

Thanks

Luigi

**Comment by publicocean0** [comment]
``INFO] OrientDB ........................................... SUCCESS [  2.445 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [  1.900 s]
[INFO] OrientDB Core ...................................... FAILURE [01:32 min]
[INFO] OrientDB Client .................................... SKIPPED
[INFO] OrientDB Object .................................... SKIPPED
[INFO] OrientDB Tools ..................................... SKIPPED
[INFO] OrientDB Server .................................... SKIPPED
[INFO] OrientDB GraphDB ................................... SKIPPED
[INFO] OrientDB Tests ..................................... SKIPPED
[INFO] OrientDB Distributed Server ........................ SKIPPED
[INFO] OrientDB Lucene full text index .................... SKIPPED
[INFO] OrientDB JDBC Driver ............................... SKIPPED
[INFO] OrientDB ETL ....................................... SKIPPED
[INFO] OrientDB Community Distribution .................... SKIPPED
[INFO] OrientDB Community Distribution Tinker Pop 2 ....... SKIPPED
[INFO] orientdb-crashtests ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:37 min
[INFO] Finished at: 2017-08-10T15:16:38+02:00
[INFO] Final Memory: 43M/806M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project orientdb-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /data/orientdb/orientdb/core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /data/orientdb/orientdb/core && /usr/lib/jvm/java-8-oracle/jre/bin/java -ea -Xmx3072m -XX:MaxDirectMemorySize=512g -Dstorage.diskCache.bufferSize=4096 -Dindex.flushAfterCreate=false -Dstorage.makeFullCheckpointAfterCreate=false -Dstorage.makeFullCheckpointAfterOpen=false -Dstorage.makeFullCheckpointAfterClusterCreate=false -Dstorage.wal.syncOnPageFlush=false -Dstorage.configuration.syncOnUpdate=false -Ddb.makeFullCheckpointOnIndexChange=false -Ddb.makeFullCheckpointOnSchemaChange=false -Dsecurity.userPasswordSaltIterations=10 -Dmemory.directMemory.trackMode=true '-Djava.util.logging.manager=com.orientechnologies.common.log.OLogManager$DebugLogManager' -Dstorage.diskCache.checksumMode=storeAndThrow -jar /data/orientdb/orientdb/core/target/surefire/surefirebooter6230854847980867490.jar /data/orientdb/orientdb/core/target/surefire 2017-08-10T15-15-06_250-jvmRun1 surefire7377329045383588516tmp surefire_08712049912749858275tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] com.orientechnologies.orient.core.index.UniqueIndexTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /data/orientdb/orientdb/core && /usr/lib/jvm/java-8-oracle/jre/bin/java -ea -Xmx3072m -XX:MaxDirectMemorySize=512g -Dstorage.diskCache.bufferSize=4096 -Dindex.flushAfterCreate=false -Dstorage.makeFullCheckpointAfterCreate=false -Dstorage.makeFullCheckpointAfterOpen=false -Dstorage.makeFullCheckpointAfterClusterCreate=false -Dstorage.wal.syncOnPageFlush=false -Dstorage.configuration.syncOnUpdate=false -Ddb.makeFullCheckpointOnIndexChange=false -Ddb.makeFullCheckpointOnSchemaChange=false -Dsecurity.userPasswordSaltIterations=10 -Dmemory.directMemory.trackMode=true '-Djava.util.logging.manager=com.orientechnologies.common.log.OLogManager$DebugLogManager' -Dstorage.diskCache.checksumMode=storeAndThrow -jar /data/orientdb/orientdb/core/target/surefire/surefirebooter6230854847980867490.jar /data/orientdb/orientdb/core/target/surefire 2017-08-10T15-15-06_250-jvmRun1 surefire7377329045383588516tmp surefire_08712049912749858275tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] com.orientechnologies.orient.core.index.UniqueIndexTest
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :orientdb-core
cristian@fenix:/data/orientdb/orientdb$

**Comment by publicocean0** [comment]
it seams another bug maybe it is pointing to a old jar test

**Comment by publicocean0** [comment]
git branch
  3.0.0m2
* develop
  master

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

Sorry, this issue fell through the cracks. Did you have a chance to try it again?
On all our machines we have no problems building...

Thanks

Luigi

**Comment by tglman** [comment]
Hi,

We have no problem building since a while, closing this
