### ISSUE TITLE
lucene can t search a link (even if in the schema)

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7643]
### Java Version: 8
```
 select from domain

+----+------+------+--------+--------------------------+----+
|#   |@RID  |@CLASS|identity|code                      |name|
+----+------+------+--------+--------------------------+----+
|0   |#35:4 |Domain|#23:17  |36P6Q9BQNA6RCAWR4DTJBCBFW |aaaa|
|1   |#35:5 |Domain|#23:17  |Z0X5DAYZ25L5C5URFEICYJ9C7 |aaaa|
|2   |#35:6 |Domain|#23:17  |D7QN8HYH5N31KUDAU329HK2YI |aaaa|
|3   |#35:7 |Domain|#23:17  |1ST1I6NWML5OO89O1T1X8Y212 |aaaa|
|4   |#35:8 |Domain|#23:17  |OQLDF3DJ090TSASNMNBBOAFA  |aaaa|
|5   |#35:9 |Domain|#23:17  |VJWGADYJR1KADNC447V3MJAGR |aaaa|
|6   |#35:10|Domain|#23:17  |11E6SJ51B8VS0Z74X4E0GAJBN4|aaaa|
+----+------+------+--------+--------------------------+----+

7 item(s) found. Query executed in 0.021 sec(s).
 select  from Domain WHERE SEARCH_CLASS('identity:"#23:17" ')=true 


0 item(s) found. Query executed in 0.002 sec(s).
```

**Comment by publicocean0** [comment]
in studio i have 

index 
Domain.lucene | FULLTEXT | Domain | [code,name,account,identity]
-- | -- | -- | --

**Comment by robfrank** [comment]
If you create a lucene index without specifying an analyzer, the default analyzer is the StandardAnalyzer. so the _#24:5_ will be tokenized stripping out # and : . if you really need to index a RID in lucene, configure the index to use the KeywordAnalyzer for that field:

http://orientdb.com/docs/3.0.x/indexing/Full-Text-Index.html#analyzer

**Comment by publicocean0** [comment]
i passed as metadata 
{
 "default": "org.apache.lucene.analysis.standard.StandardAnalyzer",
  "index": "org.apache.lucene.analysis.standard.StandardAnalyzer",
              
  "identity_index": "org.apache.lucene.analysis.core.KeywordAnalyzer",
  "account_index": "org.apache.lucene.analysis.core.KeywordAnalyzer"
}

no result

**Comment by publicocean0** [comment]
i found the configuration

**Comment by publicocean0** [comment]
{
"default": "org.apache.lucene.analysis.standard.StandardAnalyzer",
"index": "org.apache.lucene.analysis.standard.StandardAnalyzer",
"identity_query": "org.apache.lucene.analysis.core.KeywordAnalyzer",
"account_query": "org.apache.lucene.analysis.core.KeywordAnalyzer"
"identity_index": "org.apache.lucene.analysis.core.KeywordAnalyzer",
"account_index": "org.apache.lucene.analysis.core.KeywordAnalyzer"
}

**Comment by robfrank** [comment]
Yes, index analyzer and query analyzer should be the same. Bear in mind that Lucene analyze your text, it doesn't work as a LIKE operator. It works on terms. The index analyzer produces terms to be stored in the index, the query analyzer produces terms from your query and match that terms with the ones stored inside the index. 
May a I close the issue?

**Comment by publicocean0** [comment]
yes this is ok now. Thanks. I have a problem with linked list on any type but i posted another issue for that
