### ISSUE TITLE
function takes no string-variable as query-string

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7649]
## Expected behavior  
Writing a function "mergeCDR" like this:
```
var db = orient.getDatabase();
var sqlString = "select rid FROM index:".concat(indexName).concat(" WHERE key = [?,?,?,?] ");
return db.query(sqlString, imsi, charging_id, ggsn, phone_ip);
```
Is saved with no problem, executed with 5 parameters and completes with no error. I would expect a well-known RID to be returned.

## Actual behavior  
No errors, but also **no results**.

When I do **not** put the positional parameters to the query in a WHERE clause, then the function runs with no errors but (as expected) returns the 5 requested entries from the index:
```
var db = orient.getDatabase();
var sqlString = "select rid FROM index:".concat(indexName).concat(" LIMIT 5");
return db.query(sqlString);
```

When I rewrite the function like this:
```
var db = orient.getDatabase();
return db.query("select rid FROM index:myindexname WHERE key = [?,?,?,?] ", imsi, charging_id, ggsn, phone_ip);
```
then the well-known RID is properly returned.

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Try to pass the parameters as an array:

```
return db.query(sqlString, [imsi, charging_id, ggsn, phone_ip]);
```

Thanks

Luigi

**Comment by rdelangh** [comment]
hi @luigidellaquila , the documentation (http://orientdb.com/docs/2.0/orientdb.wiki/Functions.html#Server-Side_functions) is very inconsistent then:
- mostly that page mentions no square brackets around the parameters,
- in one example is writes indeed such square brackets around the parameters

-> can the documentation please be made more clear, and -above all- consistent?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I agree with you, that page requires some refactoring, we'll do it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
That page refers to 2.0 docs, in 3.0 we completely re-arranged the docs

Closing, thanks

Luigi
