### ISSUE TITLE
Reusue index sorting capabilities in ORDER BY clause processing [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#765]
This is [Issue 765](http://code.google.com/p/orient/issues/detail?id=765) moved from a Google Code project.
Added by 2012-03-25T08:07:32.000Z by [lomakin....@gmail.com](http://code.google.com/u/110615750300902819680/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, v1.3.0

### Original description

    If field in ORDER BY SQL expression is used in index that has been reused for query processing it is better do not sort by this field but just relay on fact that data already has been sorted by this field in index.
    
    This will allow to paginate data using &quot;>=&quot; operator and ORDER BY SQL expression.

**Comment by laa** [comment]
Guys never use approach "create index Channel.id unique" to create index this syntax deprecated years ago.  I will check data structure but reason seems that index was not created properly.

**Comment by a-unite** [comment]
> Guys never use approach "create index Channel.id unique" to create index this syntax deprecated years ago. 
This is not the first time I see this kind of advice.
Andrey, may you please explain it in more details?
Is it wrong syntax for automatic index? Does it mean that examples for automatic index creation in docs (http://orientdb.com/docs/last/Indexes.html) are obsolete?

Sorry for off-topic.

**Comment by lvca** [comment]
Deprecating an API doesn't mean it should be broken, so it's a bug anyway. @laa is checking if this is the problem.

**Comment by laa** [comment]
Yeah that is actually sql engine issue not storage level , but lets check it.

**Comment by laa** [comment]
I tried on 2.1-SNAPSHOT 
`orientdb {db=cnt}> explain select from channel where id between 3 and 304443 order by id limit 10

Profiled command '{documentReads:8,fullySortedByIndex:true,documentAnalyzedCompatibleClass:8,recordReads:8,fetchingFromTargetElapsed:1,indexIsUsedInOrderBy:true
,compositeIndexUsed:1,current:#11:9,involvedIndexes:[1],limit:10,evaluated:8,user:#5:0,elapsed:2.349393,resultType:collection,resultSize:8}' in 0.004000 sec(s):

{"@type":"d","@version":0,"documentReads":8,"fullySortedByIndex":true,"documentAnalyzedCompatibleClass":8,"recordReads":8,"fetchingFromTargetElapsed":1,"indexIs
UsedInOrderBy":true,"compositeIndexUsed":1,"current":"#11:9","involvedIndexes":["channel.id"],"limit":10,"evaluated":8,"user":"#5:0","elapsed":2.349393,"resultT
ype":"collection","resultSize":8,"@fieldTypes":"documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,compositeIndexUsed=l
,current=x,involvedIndexes=e,evaluated=l,user=x,elapsed=f"}`

So as you can see indexes are used. I close this issue as invalid.
