### ISSUE TITLE
 Cannot execute UPDATE PUT/ADD/INCREMENT 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7651]
### Java Version: 7

update ... add a = #4:3

give exception  Cannot execute with UPDATE PUT/ADD/INCREMENT new executor.

how can i add a item to a set/list? why i can use remove 1 element and not  insert 1 element ? It is a temporary bug?

for incrrement i can use :
update 48:24 set a = a+1  instead update 48:24 increment a = 1

**Comment by markk12** [comment]
i have the same problem. Passing from 2.x to 3.x ...
My scripts do not work anymore. In many cases, my db arrays contain 1000-10000 items, the idea of ​​passing the entire array each time to add only one item does not look so good.

**Comment by publicocean0** [comment]
cool :)

**Comment by publicocean0** [comment]
ops similar problem with put .... 
i tried with || dont works
i tried to search in that page sql syntax ... i dont found

**Comment by luigidellaquila** [comment]
Hi @publicocean0 

```UPDATE ... PUT foo = bar, baz``` 

is just syntax sugar for

```UPDATE ... SET foo.bar = baz``` 

So you can just use this form

Thanks

Luigi

**Comment by publicocean0** [comment]
ok thanks .... cool i like new syntax ahaha

**Comment by ebingeorgedct** [comment]
how can i use isSet()  in an update query. to add only if it does not exist in array
