### ISSUE TITLE
3.0-m2 - maxdepth seems not working

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7654]
### OrientDB Version: 3.0-m2

On demodb, try:

SELECT COUNT(*) 
FROM (
  TRAVERSE * FROM (
    SELECT FROM Profiles WHERE Name='Santo' and Surname='OrientDB'
  ) MAXDEPTH 1
)

SELECT COUNT(*) 
FROM (
  TRAVERSE * FROM (
    SELECT FROM Profiles WHERE Name='Santo' and Surname='OrientDB'
  ) MAXDEPTH 2
)

SELECT COUNT(*) 
FROM (
  TRAVERSE * FROM (
    SELECT FROM Profiles WHERE Name='Santo' and Surname='OrientDB'
  ) MAXDEPTH 3
)

The queries above all return 21303 as result. This is a regression

Thanks,

**Comment by luigidellaquila** [comment]
Hi @santo-it 

Reproduced, working to a fix

Thanks!

Luigi

**Comment by luigidellaquila** [comment]
Fixed on develop branch, closing

Thank you @santo-it !

Luigi
