### ISSUE TITLE
console: wrong dir name in open a plocal db

### ISSUE THREAD

**Issue by zlfsimon** [orientechnologies/orientdb#7655]
### OS: centos7

```
orientdb>

orientdb> CONNECT plocal:../databases/enterprise/ admin admin

Disconnecting from the database [null]...OK
Connecting to database [plocal:../databases/enterprise/] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '../database/enterprise' with mode=rw
        DB name="enterprise"

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'enterprise' because it does not exist in path: ../database/enterprise
        DB name="enterprise"

orientdb>   
```
I try to open a database by console, but the exception show the wrong "database" dir, it should be "database**s**"

BTW, I use 2.2.6-snapshot in centos 7 with jdk 8

**Comment by zlfsimon** [comment]
workaround solution: change database dir to database, but maybe it's a bug, pls check it, thx

**Comment by tglman** [comment]
Hi,

This is quite strange is quite common use case and I never saw this problem, this has been working fine for long time, probably some missconfiguration in the connection, closing this.

Regards
