### ISSUE TITLE
3.0.0-m2 - NPE on a query

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7661]
Hi,

Non blocking for me, but I think we should fix the NPE or return better error - FYI

on demodb:

**1.**
java.lang.NullPointerException:
SELECT count(*) FROM Orders GROUP BY OrderDate.format('yyyy')

**2.**
works as expected:
SELECT count(*), OrderDate.format('yyyy') as year FROM Orders GROUP BY year

**3.**
return strange recordsets:
SELECT count(*), OrderDate.format('yyyy') FROM Orders GROUP BY OrderDate.format('yyyy')

**4**
works as expected:
SELECT count(*), OrderDate.format('yyyy') as year FROM Orders GROUP BY OrderDate.format('yyyy')

**Comment by luigidellaquila** [comment]
Thanks @santo-it 

I'll check it asap

Luigi

**Comment by luigidellaquila** [comment]
Fixed on develop 

Closing, thanks!

Luigi
