### ISSUE TITLE
Escaping char '@' : Cannot execute query

### ISSUE THREAD

**Issue by acrive82** [orientechnologies/orientdb#7662]
### OS: Linux

I cannot execute the following statement:

```
def sqlString = "select * from FTW_USER where email = :email and password = :password"
def result = database.query(sqlString, [email: orientDBMessage.params.email, password: orientDBMessage.params.password])
       
```

## Expected behavior  
The query will be executed

## Actual behavior  
Parsing exception
017-08-16 12:30:39:522 SEVER Internal server error:
Error parsing query:
```
select * from FTW_USER where username = luigi@gmail.com and password = password;
                                                     ^
Encountered " "@" "@ "" at line 1, column 54.
Was expecting one of:
    <EOF> 
    <AND> ...
    <OR> ...
    <ORDER> ...
    <GROUP> ...

```

## Steps to reproduce  
Execute a query from Java API with a param that contain '@' char

**Comment by luigidellaquila** [comment]
Hi @acrive82 

Which API/driver are you using?

The resulting query should be

```
select * from FTW_USER where username = "luigi@gmail.com" and password = "password";
```

with quotes around the parameters, so we should check why they are not quoted in your case...

Do you have a test case to reproduce the problem?

Thanks

Luigi

**Comment by acrive82** [comment]
I'm using the 3.0.0m1.

With your suggestion it works!  

I ran into error by following the documentation of the method query():

```
Map&lt;String, Object&gt params = new HashMapMap&lt;&gt();
      params.put("name", "John");
      OResultSet rs = db.query("SELECT FROM V where name = :name", params);
      while(rs.hasNext()){
        OResult item = rs.next();
        ...
      }
   rs.close();
```
Thanks Luigi!
