### ISSUE TITLE
3.0.0-m2 - integer instead of floating point is returned

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7663]
Hi,

demodb, query:

SELECT
  count(*) as OrdersNumber,
  sum(Amount) AS TotalRevenuesFromOrders,
  min(Amount) as MinAmount,
  (sum(Amount)/count(*)) as AverageAmount,
  max(Amount) as MaxAmount
FROM Orders

AverageAmount should be floating point (an integer result is returned instead)

Thanks

**Comment by luigidellaquila** [comment]
Hi @santo-it 

Fixed on develop branch

Closing, thanks!

Luigi

**Comment by santo-it** [comment]
Thanks Luigi! 

I've added a test as part of the demodb integration tests.
