### ISSUE TITLE
OutOfMemory during transaction commit

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7670]
### OS: ubuntu

Quite interesting exception during simple transaction commit. Working memory: 2Gb - more than enough.
Please check gist for details: https://gist.github.com/PhantomYdn/7f5f7568294e11f2632938468a91425f

**Comment by tglman** [comment]
hi @PhantomYdn,

Can you reproduce this in a deterministic way ? In case yes could you get a memory dump so we can track what is in the memory that is creating GC Overhead ?

Regards

**Comment by PhantomYdn** [comment]
@tglman , unfortunatly no:( And even that time: JDK crashed without any heap-dump. Trying to setup taking memory dump in such cases, but not sure how quickly it might repeat.
