### ISSUE TITLE
"Error deserializing record to get field-names" with non-bundled gremlin client

### ISSUE THREAD

**Issue by jacques-** [orientechnologies/orientdb#7671]
### OS:  Fedora 26 x86_64

Not sure if this is a bug somewhere, or expected and I'm missing something.

I start the orientdb server with "server.sh" and load default config. I access "demodb" through the studio web application and everything seems to work 100%.

## Expected behavior  

Then start gremlin.sh that comes with orient, and get:
$ ./gremlin.sh 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.orientdb
gremlin> graph = OrientGraph.open("remote:localhost/demodb","root","root")
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
==>orientgraph[remote:localhost/demodb]
gremlin> g = graph.traversal()
==>graphtraversalsource[orientgraph[remote:localhost/demodb], standard]
gremlin> g.V().has('Name', 'Belgium')
==>v[#36:2]

All good.

## Actual behavior  

I'm building an app, so gradle pulls all the right libraries - but I get an error when doing the g.V().has in my app. So tried doing the same using a non-bundled gremlin-console and then I get the same issue - so will tackle from that use-case as I think it's simpler.

When I try with the non-bundled version I get:
$ gremlin.sh 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.orientdb
plugin activated: tinkerpop.neo4j
plugin activated: tinkerpop.tinkergraph
gremlin> graph = OrientGraph.open("remote:localhost/demodb","root","root")
==>orientgraph[remote:localhost/demodb]
gremlin> g = graph.traversal()
==>graphtraversalsource[orientgraph[remote:localhost/demodb], standard]
gremlin> g.V().has('Name', 'Belgium')
Aug 19, 2017 7:10:10 PM com.orientechnologies.common.log.OLogManager log
WARNING: Error deserializing record to get field-names, send this data for debugging: EkN1c3RvbWVycxIcb3V0X01hZGVSZXZpZXcW/////////////////////wEcpAMSpgMSpAM6qANQogNipgN4sAOIAa4DsAGqA9gBrAPYAagDgAKqA4ACpgOoAqgDqAIST3JkZXJlZElkA1IKUGhvbmUHFisxNjAwOTA3NDYyIm91dF9Jc0Zyb21Db3VudHJ5Fv////////////////////8BAqICChpvdXRfSGFzU3RheWVkFv////////////////////8BCsICLMQCLMYCLMgCLMoCLBhvdXRfSGFzRWF0ZW4W/////////////////////wEo4AJQ0gJS1AJS1gJS2AJS2gJS3AJS3gJS4AJS0gJU1AJU1gJU2AJU2gJU3AJU3gJU4AJU0gJW1AJW1gJWHG91dF9IYXNQcm9maWxlFv////////////////////8BAvICChxpbl9IYXNDdXN0b21lchb/////////////////////AQqOAzSKA06GA2iQA4ABigOaARxvdXRfSGFzVmlzaXRlZBb/////////////////////ApCIgIDAzMje+AEAgCAA 
441

So there must be some difference in the way standalone gremlin starts up or the libraries it loads?

## Steps to reproduce  

Do all steps as in expected behaviour - then download apache-tinkerpop-gremlin-console-3.2.5-bin.zip from tinkerpop website.

Unpack gremlin console and start it - then do:

gremlin> :install com.orientechnologies orientdb-gremlin 3.0.0m2
gremlin> :plugin use tinkerpop.orientdb
gremlin> graph = OrientGraph.open("remote:localhost/demodb","root","root")
gremlin> g = graph.traversal()
gremlin> g.V().has('Name', 'Belgium')

Then the error as above.

**Comment by maggiolo00** [comment]
hi @jacques- 

which version is the server when connecting with the non bundle version of Gremlin Console?

**Comment by jacques-** [comment]
Its exactly the same orientdb server - same instance in fact.

I've rebuilt the entire VM from scratch and exactly the same issue.

**Comment by maggiolo00** [comment]
Hi @jacques- 

i've done a quick check. Seems that there is a problem with libraries.
The problem seems to be the distribution `orientdb-community-tp3-3.0.0m2`
If you download the version with TP3 + Spatial should solve the issue

http://orientdb.com/orientdb-labs/

**Comment by jacques-** [comment]
That works thanks!
