### ISSUE TITLE
Convenience method to build a huge edge class

### ISSUE THREAD

**Issue by zlfsimon** [orientechnologies/orientdb#7672]
do we have some Convenience method to build a huge edge class?
In my case I create two huge vertexes, such as person [50000000] and company [10000000], now want to create edge officer  between two vertexes, it seems I must find two vertex RID firstly, then 
call

```
begin;
  CREATE EDGE E FROM #34:3349  TO #32:3349 CONTENT { "name": "Jay", 
          "surname": "Miner" };
  CREATE EDGE E FROM #41:10971 TO #33:3348 CONTENT { "name": "Jay", 
          "surname": "Miner" };
commit retry 100;
```
it's slow and inconvenience to create a graph. Is there some better method of it.

**Comment by tglman** [comment]
hi @zlfsimon,

You can use query in from and to  like for example:
` CREATE EDGE E FROM (SELECT FROM V WHERE name="abc")  TO (SELECT FROM V WHERE name="cde") CONTENT { "name": "Jay",   "surname": "Miner" };`

does this help?

Reagards

**Comment by zlfsimon** [comment]
oh, I consider this solution, but  it will have two sub query. For performance, maybe it's better to get all rid together, then call "create".  
I think the key issue: I can't point to RID when I insert into a vertex. It will be very easy if I can organize 'sql' by myself, so I can't ignore this boring ‘JOIN’ operation.  It's very useful for very huge data operation.
does orientdb has a such future?

**Comment by zlfsimon** [comment]
```
Stream<ODocument> stream = result.parallelStream();
		iterator = stream.iterator();
		System.out.println("spend "+(System.currentTimeMillis() - start)+ "ms to get result");
		start = System.currentTimeMillis();
		while (iterator.hasNext()) {
			ODocument document = iterator.next();
			
			OIdentifiable docRid = document.field("RID");
//			String rid = "#"+docRid.getIdentity().getClusterId()+":"+docRid.getIdentity().getClusterPosition();
//			
			
			String key = document.field("_key");
			KEY_RID_MAP.put(key, "");
			
		}
```
the below calling very solw, **so hard to use.** 
`OIdentifiable docRid = document.field("RID");`

**Comment by zlfsimon** [comment]
@tglman  any suggestion?

**Comment by tglman** [comment]
Hi,

I terms of performance have two subquery is not an issue , I'm not sure what you mean whit the snippet before, but I guess you are trying to collect the rids out of a query, and this is the way to do it, be aware that the `ODatabaseDocument` and `ODocument` api are not thread safe, so you should not use the `parallelStream()` java api.

Regards

**Comment by zlfsimon** [comment]
Hi,

I mean I have a vertex with id 1341341341,  I can insert this vertex like: 
`insert into verext (rid, .......) values (65:1341341341, ...............)`
then I can calculate the from and to  vertexs by their ids 
`create edge relarionship_xxx from 65:1341341341 to xxxx content {xxxxx}`

It's convenience for very  huge data set building.

**Comment by tglman** [comment]
hi @zlfsimon,

if you want to do multi operation you can use let variables in this way:
```
let $a = create vertex V set a="a";
let $b = create vertex V set a="b";
create edge from $a to $b set  a="c";
```

in the same way from java api you can get the return of the create vertex operation and use it as parameter of the create edge operation.

Hope this help.

**Comment by zlfsimon** [comment]
Hi @tglman 

Yes, it's a wonderful idea, but most of  data which storied in hbase or hive is organized by vertex and edge. each vertex collection or edge collection is very huge, most of them are morn then 50 million records, even 10 billion a collction. by your way, we have to operate some "join" actions, it's not convenience for us.

**Now we use ArangoDB, which support insert vertex by identified a "_key",  it's very nice**. For some reason, we want to change to orientdb, after some testing most feature is fine, but "create a edge" now block our decision.

Most RDMS also support this insert a record by identified a primary key 'id'. Any join action maybe very hard for a very huge data set. Seems orientdb not support "create vertex " by identified a rid, so my question is does orientdb will support this feature in next versions or it's hard to support this feature?  Any help we can get if we plan to develop it?

Best Regards

**Comment by lvca** [comment]
@zlfsimon What's the reason why you're looking for something different than ArangoDB?

@zlfsimon with a native graph database, like OrientDB and Neo4j, there are pointers to the data. This speeds up the traversal, especially with huge databases doesn't fit in RAM, but make the creation of the graph slower.

You could create a collection of long strings or numbers, and then store the IDs of the vertices and it would be super fast on creation, but then at run-time you'd have an expensive JOIN operation that could be O(logN). Is more important the insertion speed or traversal for your use case?

**Comment by zlfsimon** [comment]
Hi @lvca  both insertion and traversal speed are important for us, but the most important is traversal. I guess orientdb is need two rid to build an explicit "reference" relation for performance consideration, not use implicit "key" match in select, I think it's nice, but maybe it's more nice if we can point a rid on create a certex, and build a relation  also have an "explicit reference" by using these rids. 
As I know, seems we can use OGraphBatchInsert to point a id, and use these id in building an edge, but seems there's a bug  in OGraphBatchInsert  for only allow 'plocal' protocol.

**Comment by lvca** [comment]
@zlfsimon did you already open a bug for that?

**Comment by zlfsimon** [comment]
@lvca  yes, I want to open it if  can get more support from community, seems it's more like a feature. Thanks

**Comment by zlfsimon** [comment]
@tglman  @lvca  any feedback?

**Comment by zlfsimon** [comment]
it's hard to use and also can't get enough help, we have to recommend our customers give up this product

**Comment by tglman** [comment]
Hi @zlfsimon,

From your comments seems that what you are looking for is a way to create edges between vertex starting from something similar to what is called in relational databases "foreign key", as today we do not have a specific API to do fast creation of edges from that, but you can use the existing API or SQL that will solve the problem.

If enough users require this specific feature or some users are willing to sponsor it we may do it.

Regards
