### ISSUE TITLE
Boolean filter not returning zero when .size() is used

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/orientdb#7673]
When we filter over a boolean attribute and use .size() plus an alias, the alias is not returned if the filter doesn't find any matches:

`[completed=true].size() AS totalCompleted`

I was really expecting totalCompleted to be returned and to have an integer as value, starting from zero, of course. Instead it is not returned at all if there are no completed=true around.

Thanks

**Comment by lvca** [comment]
The methods are evaluated in chain, but as soon as the current value is null, the chain is interrupted. Try with this:
`
coalescence( [completed=true].size(), 0 ) AS totalCompleted
`

**Comment by igasparetto** [comment]
Thanks Luca,
I still think there is room for improvement. The DB should respond predictably, instead it puzzles me, like in this case.
Ivan

**Comment by lvca** [comment]
I don't know if in v3.0 this is changed. @luigidellaquila any thoughts about this?

**Comment by luigidellaquila** [comment]
Hi @igasparetto @lvca 

In v 3.0 it's already changed: if the original collection is not null, the filtering always returns a collection (perhaps empty), so the size() works fine.

In 2.2 the behavior is a bit more articulated, but I can check it and see if there is a bug here (sorry, I'm out of office in these days, but I'll give it a look as soon as I'm back)

Thanks

Luigi

**Comment by lvca** [comment]
So in v3.0 this is already fixed. Cool.
