### ISSUE TITLE
ODatabaseDocument.execute() does not allow comments

### ISSUE THREAD

**Issue by BrunoSupiot** [orientechnologies/orientdb#7675]
## Expected behavior  
SQL scripts must allow comments (with '--' or '//' at the beginning of the line   

## Actual behavior  
	Suppressed: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:

 ^
Encountered " "/" "/ "" at line 1, column 2.
Was expecting one of:
    <EOF> 
    <SELECT> ...
  

## Steps to reproduce  
ODatabaseDocument session;

//
// open the session on a remote db
//

String sql = "-- comment\n CREATE CLASS Sample EXTENDS V;";
// execute schema creation
OResultSet rs = session.execute( "sql", sqlCommand);

**Comment by luigidellaquila** [comment]
Hi @BrunoSupiot 

OrientDB accepts java-like multiline comments: `/* comment */`

Thanks

Luigi

**Comment by BrunoSupiot** [comment]
Thank you Luigi.
It works <ith java style comments.
However, this does not work inside the 'browse' section of the  OrientDb studio, when a multi-command is submitted
