### ISSUE TITLE
Test testCreateVertexByContent with CP-1251 encoding

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7679]
The test does not pass because SQL parser uses system encoding instead of DB encoding.
The same problem exists in several Lucene tests too.
I suppose DB encoding should be used by default.

**Comment by luigidellaquila** [comment]
Fixed in v 2.2.29 and 3.0

Luigi

**Comment by laa** [comment]
@luigidellaquila I am sorry but this test was not enabled, I will enable it and run tests again.

**Comment by luigidellaquila** [comment]
Oh, right, please let me know if there are other things to fix here

Thanks

Luigi

**Comment by laa** [comment]
All is OK closing the issue.

**Comment by luigidellaquila** [comment]
Great, thanks!

Luigi
