### ISSUE TITLE
LIMIT clause not working in DELETE EDGE syntax

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7680]
## Expected behavior  
LIMIT x limits the number of deleted records to x

## Actual behavior  
all records that match the delete query are removed

## Steps to reproduce  
- create vertex class1 and vertex class2
- create vertex a in class1 and vertex b in class2
- create edge class class3
- create x edges (e.g. 4) from a to b using class class3
- execute query

DELETE EDGE class3 FROM (SELECT FROM class1 WHERE your_primary_key) TO (SELECT FROM class2 WHERE your_primary_key) LIMIT 1;

In demoDB:

execute a few times the query:

CREATE EDGE HasVisited FROM (SELECT FROM Customers WHERE OrderedId=31) TO (SELECT FROM Castles WHERE Id=28);

execute the following query from the graph editor to see how many edges you have:

MATCH {class:Customers, WHERE:(OrderedId=31)}--{class:Castles, WHERE:(Id=28)}
return $pathelements

in my case,  I have 4 edges:

![edges](https://user-images.githubusercontent.com/14923389/29690164-2ce1b238-8926-11e7-975a-b27ed38591f7.PNG)

execute delete query - note the limit 1:

DELETE EDGE HasVisited FROM (SELECT FROM Customers WHERE OrderedId=31) TO (SELECT FROM Castles WHERE Id=28) LIMIT 1 

note the value = 4 in the image:

![edges2](https://user-images.githubusercontent.com/14923389/29690182-3f3bf254-8926-11e7-85f7-ee09e8ec17af.PNG)

execute again the match query to see how many edges there are --> no edges (should be 4-1 = 3)

Thanks,

**Comment by luigidellaquila** [comment]
Fixed on 2.2.x, the fix will be released with 2.2.27

Thanks

Luigi
