### ISSUE TITLE
Remove logging of ridbag changes from serialization context to transaction

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7684]
At this moment all operations on an embedded database are transactional, so there is no need to keep changes of rid bags in separate data structures. So we will remove double change management under TX.

This change will be implemented only for embedded storage. Remote storage will keep current mechanics of notification of changes. 

It makes things a bit inconvenient but makes transaction tracking more efficient.

**Comment by tglman** [comment]
hi,

As today remote and embedded use two different things for ridbag tracking already, in remote we simply serialize the changes inside the ridbag, in embedded we use a thread local where we keep stored the changes, I really would like to remove this thread local, and from the recent evolution of Tx and MicroTx probably is possible do the ridbag operation directly in the commit without the thread local, is it this they way it will be done ?

Regards

**Comment by laa** [comment]
@tglman, yes you are right.
