### ISSUE TITLE
Hash only indexes

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7686]
Create hash index which will contain only hash codes of the keys.  Hash codes will be generated using one of SHA algorithms. After the fetch of results, data will be additionally filtered by SQL engine. To minimize a risk of collisions one of SHA algorithms will be used.

**Comment by lvca** [comment]
When can we do this?

**Comment by laa** [comment]
Hi, I put it in backlog in instead of #5149. We started to create a backlog. The backlog is not more than 10 important issues which we are going to do next.  It does not mean that all of them will have to be implemented in next release. We are going to develop each feature in separate branch and test in a separate branch, running at the end CI, durability and binary compatibility tests. So you may release develop branch at any moment.  I can not tell you exact data. But it will be implemented in the list of next 10 features. You can find our backlog by searching by "sbacklog" label. Once the backlog is formed would be cool to keep is stable till all issues will not be implemented. 

So answering your question - we will implement it together with next 9 features which will be done in short future.

**Comment by tglman** [comment]
Hi @laa,

Just for info, how do you think to implement this? from my point of view a case like this can be implemented simply wrapping the current index implementations, adding hashing on put and filtering on get/iterate.

Regards

**Comment by laa** [comment]
@tglman I think the simplest approach is to replace key by SHA code. But it is too early to say will look in details once we start implementation.

**Comment by laa** [comment]
Not actual
