### ISSUE TITLE
3.0-snapshot - demodb - array item returned instead of string

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7688]
### OS: win 10 64bit

Hi,

I was working on the demodb integration tests and I found out that for this query:

Among Santo's Friends, find the top 3 Customers that placed the highest number of Orders:

```
SELECT 
  OrderedId as Customer_OrderedId, 
  in('HasCustomer').size() as NumberOfOrders, 
  out('HasProfile').Name as Friend_Name, 
  out('HasProfile').Surname as Friend_Surname 
FROM (
  SELECT expand(customer) 
  FROM (
    MATCH {Class: Profiles, as: profile, where: (Name='Santo' AND Surname='OrientDB')}-HasFriend-{Class: Profiles, as: friend}<-HasProfile-{class: Customers, as: customer} 
    RETURN customer
  )
) 
ORDER BY NumberOfOrders DESC 
LIMIT 3
```

Friend_Name and Surname_Name are returned as array items, instead of strings
I wonder if this is expected and why it doesn't return "Luigi" instead of "["Luigi"]"

Thanks,

**Comment by luigidellaquila** [comment]
Hi @santo-it 

This is an expected behavior: graph opeartors (`out()`, `in()` etc.) always return arrays, this is why you get an array in this case

Thanks

Luigi
