### ISSUE TITLE
Connect to OrientDB from Javascript

### ISSUE THREAD

**Issue by goncoal** [orientechnologies/orientdb#7689]
### Java Version: 1.8   

I am having trouble connecting to a database on OrientDB from javascript (Sublime Text 3) using orientdb-api.js.

My code in javascript is:

https://stackoverflow.com/questions/45691767/connect-to-orientdb-from-javascript

The error I have is: "Connect error: undefined" and "HTTP/1.1 401 Unauthorized" for queries.

All files are inside the "www" folder inside the "orientdb" folder.
I am not an expert. I need to retrieve the data here to create a graph with another javascript library.

Can you help me?

Thanks in advance.

**Comment by maggiolo00** [comment]
Hi @goncoal 

you should not use that library, since is no longer maintained. Use  directly  the REST API

https://orientdb.com/docs/2.2/OrientDB-REST.html

**Comment by maggiolo00** [comment]
hi @goncoal 

where you able to use REST API?

Thanks
