### ISSUE TITLE
Implicit commit of 2 first vertexes, connected by edges, when edge class is not set

### ISSUE THREAD

**Issue by arkolesnik** [orientechnologies/orientdb#7692]
## Expected behavior  
No vertex is commited before commit() method is called. 

## Actual behavior  
2 vertexes are shown as commited, all the other are commited after commit() method is called. (See attachments)

## Steps to reproduce  
1. Create custom vertex class: 
graphNoTx.createVertexType(VERTEX_CLASS);
2. Do NOT create class for edges.
3. Add some vertexes:  
Vertex vertex = graph.addVertex("class:" + VERTEX_CLASS); 
4. Connect them by edges: 
graph.addEdge(null, vertexes.get(i - 1), vertexes.get(i), EDGE_LABEL);
5. Do not perform commit. 
6. Try to select vertexes. 
7. Perform commit. 
8. Try to select vertexes again. 

<img width="391" alt="2_commited_vertexes" src="https://user-images.githubusercontent.com/4200801/29811378-e7bb252a-8cab-11e7-9827-c7b89dee4686.png">

<img width="399" alt="all_commited_vertexes" src="https://user-images.githubusercontent.com/4200801/29811382-ed8bfe8e-8cab-11e7-9c4b-71bf21a98fbc.png">

**Comment by laa** [comment]
Guys, I agree with @arkolesnik that is quite an opaque behavior. Let's add direct flag during edge and I suppose vertex creation too which will allow committing transactions if classes are not created. 

Otherwise, the transaction should be rolled back if the creation of classes is not allowed inside tx but not implicitly committed.

**Comment by luigidellaquila** [comment]
Hi guys,

I agree, I don't like it either. @maggiolo00 do we have any constraints on TP side about this?

Thanks

Luigi

**Comment by laa** [comment]
@luigidellaquila probably it is related to new core API too

**Comment by luigidellaquila** [comment]
Hi @laa 

I don't think so, the core API does not allow to modify the schema within a tx (it throws an exception). TinkerPop implementation explicitly checks if there is an active tx and in case commits and restarts it...
TP3 should be OK as well.

@arkolesnik can you confirm that it is TinkerPop2?

Thanks

Luigi

**Comment by arkolesnik** [comment]
Hi @luigidellaquila!
Yes, it was TinkerPop2

**Comment by luigidellaquila** [comment]
Ok, so it's an expected behavior.

I'm closing this then, thanks

Luigi
