### ISSUE TITLE
Different column order in OrientJdbcResultSet  and OrientJdbcResultSetMetaData 

### ISSUE THREAD

**Issue by LuchistiyPirozhok** [orientechnologies/orientdb#7693]
### Java Version: 8  

OrientJdbcResultSet `getObject(int column)` and OrientJdbcResultSetMetaData `getColumnLabel(int column)` returns columns in different order.

We trying to use faizod/orientdb-liquibase-plugin and because of this problem we get wrong mapping for DATABASECHANGELOG table:
```
@Override
    public Object mapRow(ResultSet rs, int rowNum) throws SQLException {
        ResultSetMetaData rsmd = rs.getMetaData();
        int columnCount = rsmd.getColumnCount();
        Map mapOfColValues = createColumnMap(columnCount);
        for (int i = 1; i <= columnCount; i++) {
            String key = getColumnKey(rsmd.getColumnLabel(i));
            //using OrientJdbcResultSet getObject(int column) method
            Object obj = getColumnValue(rs, i);
           //
            mapOfColValues.put(key, obj);
        }
        return mapOfColValues;
    }
```

**Comment by robfrank** [comment]
is this project?

https://github.com/faizod/orientdb-liquibase-plugin

some changes where from 2.2.13. Can you try with latest 2.2.26?

**Comment by LuchistiyPirozhok** [comment]
yes,

i tried it with 2.2.26 and got same issue.

btw i was able to avoid this by writing a custom mapper, that uses index only for keys

**Comment by robfrank** [comment]
Can you provide a simple test case to reproduce the problem?

**Comment by LuchistiyPirozhok** [comment]
I made an example https://github.com/LuchistiyPirozhok/orientdb-liquibase-test

It's almost 100% copy/paste from original project but mapping seems almost alright here.

But i got another problem(
If there is not TAG property in first row of DATABASECHANGELOG table, mapper skips it for other rows.

**Comment by robfrank** [comment]
I improved a test on getObject, but I'm unabe to replicate the problem of wrong order.

About the property. It is a well-known problem almost without a solution, maybe on 3.0 it works better. I guess the query performed is SELECT * FROM DATABASECHANGELOG: without the list of fields, the JDBC driver tries to gather the list from the first record of the result set.
To avoid this behaviour, it is better to write the query as SELECT TAG, AUTHOR... FROM DATABASECHANGELOG . I don't know if that query is under your control and you can generate it this way.

**Comment by robfrank** [comment]
May I close this issue?
