### ISSUE TITLE
[Question]How to set memory useage less than 1GB or less

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#7696]
### OrientDB Version: <version here>  
2.2.24
### Java Version: <version here>  
2.8
### OS: <os here>  
centos 6.9

## Expected behavior  
When Orientdb start, it use more than 1GB memory, Is there any way to reduce memory useage?
I expect orientdb storage 500000 vertices and 300000 egdes in graph mode, and I don't want orientdb use more than 1GB memory, is that possible?

## my start parameter and `top -c`
```
/usr/local/easyops/jdk/bin/java -d64 -server -Xms256m -Xmx512m -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Djava.util.logging.config.file=/usr/local/easyops/orientdb/config/orientdb-server-log.properties -Dorientdb.config.file=/usr/local/easyops/orientdb/config/orientdb-server-config.xml -Dorientdb.www.path=/usr/local/easyops/orientdb/www -Dorientdb.build.number=2.2.x@rd3309b6660d38e14390344a1fa98a43ade2e2073; 2017-07-20 15:46:56+0000 -cp /usr/local/easyops/orientdb/lib/orientdb-server-2.2.24.jar:/usr/local/easyops/orientdb/lib/*:/usr/local/easyops/orientdb/plugins/* -Djava.net.preferIPv4Stack=true com.orientechnologies.orient.server.OServerMain
```
```
   PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 28757 xxxxxxx   20   0 6049m 1.2g  15m S  0.3 14.7   0:05.13 /usr/local/xxxxxxx/jdk/bin/java -d64 -server -Xms256m -Xmx512m -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512g -Djava.awt.headless=true -Dfile.e
```

### My English is not very well, thanks reading.

**Comment by laa** [comment]
Hi @lightjiao just set -Dstorage.diskCache.bufferSize=312 and you should get this result

**Comment by lightjiao** [comment]
Thank you very much, it works.

I know the parameter ` [-Dstorage.diskCache.bufferSize`](http://orientdb.com/docs/2.2.x/Configuration.html#storagediskcachebuffersize)
The doc tell me it's about disk buffer, why it can change the memory useage?
and why 312?
I do not know much about JVM, could you tell me? or any document and paper can tell me ?

Thanks

**Comment by lightjiao** [comment]
@laa

**Comment by laa** [comment]
@lightjiao disk buffer is the main consumer of direct memory. Because you already consumed  512M by the heap, size of disk buffer should be less than 512M to add up till 1GB. Please note that JVM itself consumes some amount of memory. So 312 M seems good first approximation. You can try 450M at first and check what the real memory consumption is.
