### ISSUE TITLE
СlusterIds of not commited vertexes and edges become positive after select operation

### ISSUE THREAD

**Issue by arkolesnik** [orientechnologies/orientdb#7698]
## Expected behavior  
Select operation shouldn't change clusterIds of not commited records from negative to positive ones, as select is idempotent operation.

## Actual behavior  
ClusterIds of vertexes and edges stored in ArrayList remain negative before select and changed to positive just after it. See attachments.

## Steps to reproduce  
1.  Create instance of db:
OrientDB orientDB = new OrientDB(URL, OrientDBConfig.defaultConfig());
ODatabaseSession graph = orientDB.open(DB_NAME, DB_USERNAME, DB_PASSWORD);
2. Create classes for vertexes and edges: 
graph.createVertexClass(VERTEX_CLASS);
graph.createEdgeClass(EDGE_LABEL);
3. Add some vertexes and save them: 
OVertex vertex = graph.newVertex(VERTEX_CLASS);
vertex.save();
4. Connect them by edges:
newEdge(vertexes.get(i - 1), vertexes.get(i), EDGE_LABEL);
5. Put vertexes in some collection. 
6.  Perform select operation, for example:  
graph.query("select * from V where " + VERTEX_ID + " <= ? order by " + VERTEX_ID + " limit " + limit, lastId); 

<img width="923" alt="before_select" src="https://user-images.githubusercontent.com/4200801/29869300-217b61d2-8d8b-11e7-971d-5f5e167f665e.png">

<img width="923" alt="after_select" src="https://user-images.githubusercontent.com/4200801/29869315-2aea3c02-8d8b-11e7-8c84-7d99b3c1d800.png">

**Comment by tglman** [comment]
hi,

This is not a bug, is on purpose, at some point(that don't have to be specified to the user) we assign the clusterId to the record, in any case doing the `load` with an old rid should return the correct record with the rid updated.

Does it make sense ? Is there any problem that this update can create?

Regards

**Comment by arkolesnik** [comment]
Thank you Emanuele, understood. So I'll close this issue. Do we have something in documentation about this? If not, it would be better to have this point described.
