### ISSUE TITLE
Select vertexes whom don't have an edge of type

### ISSUE THREAD

**Issue by cuvelierm** [orientechnologies/orientdb#7699]
## Expected behavior  
Fetch all users whom have already placed an order

## Actual behavior  
No users are being fetched

## Steps to reproduce  

`SELECT * FROM user WHERE out('user_order') IS DEFINED`
Schema: 
Class: user extends V
Class: order extends V
Class: user_order extends E
I want to fetch all users who have an order, but do not need the orders themself in my select.

**Comment by luigidellaquila** [comment]
Hi @cuvelierm 

You can use `size()` operator instead:

SELECT * FROM user WHERE out('user_order').size() > 0

Thanks

Luigi

**Comment by cuvelierm** [comment]
Thank you so much, I had been trying to find a solution for days but didn't think of this really easy one. Thank you
