### ISSUE TITLE
Weird property type problem in orientdb or orientdb studio

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#7700]
## Expected behavior  

If i update my records with a new property 'test1' (I did not explicitly create it with orient studio) using the following query
update Data set test1={"test":"test"}

I can now see in studio when editing a record that it has the value {"test":"test"} with the type EMBEDDED

I now create a property 'test2' in ostudio with type EMBEDDED 
Then I want to copy data from property test1 to test2 (update Data set test2 = test1). but I get an errer! 
If I do the following query:
select test1.type() from Data then I see that the property type is in fact an EMBEDDEDMAP

1) I dont think orient studio should tell me the type is EMBEDDED when it is EMBEDDEDMAP
2) Cant EMBEDDEDMAP data be copied into EMBEDDED?

Using Java, the following also fails
v.setProperty("test2", new HashMap<>())
The field 'Data.test2' has been declared as EMBEDDED but an incompatible type is used. Value: {}

I though EMBEDDED was just more general than EMBEDDEDMAP and EMBEDDEDLIST
so it could contain both kind of data [] and {}, is that a wrong assumption?

**Comment by tglman** [comment]
hi @temilmg,

the issue is in the update that should be `update Data set test1={"test":"test", "@type":"d"}` that make sure that you created an embedded document instead of an embedded map. from here down everything should work properly, the assumption that `{}` is a document by default is wrong (as today) because it's a map.

Regards

**Comment by temilmg** [comment]
I think I understand now, thanks for explaining! 
So this is really just a minor bug in orient studio where it is showing the wrong type when editing a record (for a map its showing EMBEDDED instead of EMBEDDEDMAP)

**Comment by tglman** [comment]
hi @temilmg,

Yes we have a small issue in the EMBEDDEDMAP detection in studio due to not clear type declaring in the JSON serialization, we will put this in queue for a fix in the next versions.

Regards
