### ISSUE TITLE
Orientdb Studio: Index permissions

### ISSUE THREAD

**Issue by dinakarreddy** [orientechnologies/orientdb#7703]
## Expected behavior  
User should not be able to drop or recreate indexes if he has access to only `database`, `database.command` read resources

## Actual behavior  
User is able to drop and recreate indexes

## Steps to reproduce  
Create a new user with a role having database, database.command read resources

If we are dropping indexes with an user with insufficient permissions in distributed environment then only indexes in the node to which we are connected are getting deleted. But if user with correct permissions drops an index it gets dropped across all nodes.

**Comment by dinakarreddy** [comment]
@laa Can you please help us with the above issue? We are planning to use orientdb in prod and we are stuck on this as an user with restricted permissions can do query like `drop index` which is unwanted.

**Comment by laa** [comment]
@dinakarreddy sorry I am responsible for very low-level stuff, but my colleagues will help you.

**Comment by dinakarreddy** [comment]
Thank you @laa
