### ISSUE TITLE
Issue with query / column name retry

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#7708]
## Expected behavior  
query to execute

## Actual behavior  
Error parsing query

## Steps to reproduce  

create a table with column name retry and try the below query.

select * from artie_directory where name='test5' and retry = 'nothing' SKIP 0 LIMIT 20

**Comment by luigidellaquila** [comment]
Hi @smallik 

`retry` is a reserved keyword in OrientDB SQL, you have to back-tick quote it:

```
select * from artie_directory where name='test5' and `retry` = 'nothing' SKIP 0 LIMIT 20
```

I hope it helps

Thanks

Luigi

**Comment by smallik** [comment]
Thank. Where can I find all the list of reserved words?

**Comment by luigidellaquila** [comment]
Hi @smallik 

We recently added this page to the docs of 3.0

http://orientdb.com/docs/3.0.x/sql/SQL-Syntax.html

you can refer to this for now, but we will back-port it to 2.2.x

Thanks

Luigi
