### ISSUE TITLE
Vertexes are found after rollback, if graph.query() was called before

### ISSUE THREAD

**Issue by arkolesnik** [orientechnologies/orientdb#7710]
## Expected behavior  
When a transaction is rolled back, no vertexes is found. 

## Actual behavior  
Sometimes vertexes are found after rollback, if graph.query() was called before. 

## Steps to reproduce  
Test fails in a block after rollback (assertion error - expected number of records is 0, but found all the records added before). Seems that rollback of transactions doesn't work.
But if do not call the method performSelectOperations(...) (which contain graph.query(...) inside) before rollback block, everything works as expected. 
Try to comment line 158 or/and 167 - and the test will pass. 

Please find code example by link: 
https://github.com/arkolesnik/orientdb-automation-transactions/blob/newbranch/src/test/java/TransactionsTest.java

**Comment by tglman** [comment]
hi @arkolesnik,

This should be fixed in develop, with few other related issues opened recently, thanks for the good work of find out this problems.


Regards
