### ISSUE TITLE
Some edges are missing, if graph.query() was called before 

### ISSUE THREAD

**Issue by arkolesnik** [orientechnologies/orientdb#7712]
## Expected behavior  
All vertexes and edges are saved and can be viewed by select query. 

## Actual behavior  
Some edges OUT are not found while selecting. 

## Steps to reproduce  
Edges OUT are missing in some vertexes, even when they are saved before. The output in Studio is like this: 

<img width="915" alt="missing_edges" src="https://user-images.githubusercontent.com/4200801/30028939-c67ea48e-918f-11e7-8c97-9d76a5dc8d85.png">

If to comment line 149 (graph.query(...) call), everything works as expected: 

<img width="902" alt="all_edges" src="https://user-images.githubusercontent.com/4200801/30029124-8d504a36-9190-11e7-8ba0-68ea1e42653f.png">

Please find code example by link: 
https://github.com/arkolesnik/orientdb-automation-transactions/blob/missing_edges_branch/src/test/java/TransactionsTest.java

**Comment by tglman** [comment]
Hi, 

This should be fixed, closing.

Regards
