### ISSUE TITLE
Distributed changes are propagated in the wrong user context

### ISSUE THREAD

**Issue by KluSe** [orientechnologies/orientdb#7713]
## Expected behavior  
All changes to a database should be propagated to other nodes with the same user they were made with on the source node.

## Actual behavior  
After changing the user several times, changes to the database are propagated with the wrong context.

## Steps to reproduce  
Setup a distributed environment with the following database:

- create database remote:localhost/Foo root root plocal graph
- create class Bar extends ORestricted
- create class BarV extends V
- create property BarV.ID String
- alter class V superclass +ORestricted
- create class BarE extends E
- alter class E superclass +ORestricted
- create user baz identified by baz role writer

Open console, connect to database as root user, then try to alter the schema:
`alter class Bar superclass -ORestricted`

works as expected.

then close the console and execute the following command:
```
/srv/orientdb/bin/console.sh "CONNECT remote:localhost/Foo baz baz;
CREATE VERTEX BarV CONTENT {ID:'1'};
CREATE VERTEX BarV CONTENT {ID:'2'};
CREATE EDGE BarE FROM (SELECT FROM BarV WHERE ID='1') TO (SELECT FROM BarV WHERE ID='2');"
```

then open the console again, connect to database as root user, and try to alter the schema again:
`alter class Bar superclass +ORestricted`

this fails with:

> Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User 'baz' does not have permission to execute the operation 'Update' against the resource: ResourceGeneric [name=SCHEMA, legacyName=database.schema].null
> 	DB name="Foo"
> 	DB name="Foo"

The problem is not limited to schema updates - we have also observed similar exceptions during replication of inserts or updates for records that extend ORestricted, when the other user does not have permission to alter the record. This usually results in inconsistent data between the nodes and creates the impression of data loss, which currently prevents us from going live with this. A stacktrace for that looks as followed:

> 2017-09-04 13:52:36:399 SEVER Failed on user switching database. null [ODistributedWorker]
> 2017-09-04 13:52:36:402 SEVER Failed on user switching database. null [ODistributedWorker][b-OS-3] Error on distributed transaction commit
> com.orientechnologies.orient.core.exception.OSecurityException: Cannot update record #226:1: the resource has restricted access^M
>         DB name="b-OS"
>         at com.orientechnologies.orient.core.metadata.security.ORestrictedAccessHook.onRecordBeforeUpdate(ORestrictedAccessHook.java:100)
>         at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:248)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1144)
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:403)
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:345)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2758)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2638)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:102)
>         at com.orientechnologies.orient.server.distributed.impl.task.OUpdateRecordTask.executeRecordTask(OUpdateRecordTask.java:131)
>         at com.orientechnologies.orient.server.distributed.task.OAbstractRecordReplicatedTask.execute(OAbstractRecordReplicatedTask.java:105)
>         at com.orientechnologies.orient.server.distributed.impl.task.OTxTask.execute(OTxTask.java:124)
>         at com.orientechnologies.orient.server.distributed.impl.OSynchronizedTaskWrapper.execute(OSynchronizedTaskWrapper.java:70)
>         at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$1.call(ODistributedAbstractPlugin.java:600)
>         at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
>         at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeOnLocalNode(ODistributedAbstractPlugin.java:596)
>         at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:337)
>         at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:111)

I have attached the hazelcast.xml, orientdb-server-config.xml and default-distributed-db-config.json.

Regards,
KluSe

[default-distributed-db-config.json.txt](https://github.com/orientechnologies/orientdb/files/1275102/default-distributed-db-config.json.txt)
[hazelcast.xml.txt](https://github.com/orientechnologies/orientdb/files/1275104/hazelcast.xml.txt)
[orientdb-server-config.xml.txt](https://github.com/orientechnologies/orientdb/files/1275105/orientdb-server-config.xml.txt)

**Comment by SDIPro** [comment]
Hi @KluSe, thanks for the detailed information.  I'm looking into this now.

**Comment by KluSe** [comment]
Hi,

any news on this? Please let me know if there is something else we can do. We are approaching our release date and would like to know if we can make this work or if we need to look for a different approach.
