### ISSUE TITLE
[Question] is there any way to link recordes after CUD operations automatically  ? 

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#7718]
Hi 
When i use the `create link` command to link related data according to  [create link documentation ](https://orientdb.com/docs/2.2/SQL-Create-Link.html) everything is OK . but i need a feature to **link** or **unlink** records after **CUD** operations . it must be like an observer with a link pattern that i defined in create link command . 
Is there any way to save my **link pattern** in ODB and after **CUD** operations ODB apply the link pattern only on current record (just like a CUD trigger) ?

If the answer is **NO** :
We would have the following syntax in `create link` command:
`CREATE LINK <link> TYPE [<link-type>] FROM <source-class>.<source-property> TO <destination-class>.<destination-property> [INVERSE] [ON CREATE|UPDATE|DELETE|ALL]`

Thanks
Saeed Tabrizi

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

You can write a custom hook: http://orientdb.com/docs/2.2.x/Hook.html

It's not trivial, but it's powerful enough for what you need

Thanks

Luigi

**Comment by saeedtabrizi** [comment]
Hi @luigidellaquila 
Thanks for the best answer from you . 
We can close this issue now . 
Saeed
