### ISSUE TITLE
shutdown.sh take so long time about more than 1 hour

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7719]
## Expected behavior  
Can shutdown orientdb take a little time.
By the way, I have more than 40GB data.

## Actual behavior  
shutdown.sh take so long time about more than 1 hour

## Steps to reproduce  
<add here>

**Comment by laa** [comment]
@KishoDai how much RAM do you have? Could you send me several thread dumps which are done during the shutdown ? Please do not add them directly to the issue but add them as separate thread dumps.

**Comment by laa** [comment]
@KishoDai BTW why you do not use latest versions?

**Comment by KishoDai** [comment]
@laa 
   Hi, laa, Can you please tell me which latest enterprise version is OK?

**Comment by KishoDai** [comment]
@laa 
   I Have 64GB memory. And I arranged JVM heap 10GB, and disk cache 48GB.
  Sorry, I have killed orientdb, and have no record the dumps.

**Comment by laa** [comment]
@KishoDai I suggest you use 2.2.25 - 2.2.26 versions. 2.2.26 is better of course. Without additional thread dumps it is really hard to say what is going on and why you had such situation even on very intensive benchmarks ODB is closed during 15 min on your disk cache size. I will put the status of this issue as waiting for additional info. I f you have got this situation next time, please provide me several thread dumps during dunno 1 min interval. Once you provide this information I think we will be able to fix the issue if that still persists of course.

**Comment by KishoDai** [comment]
Hi @laa 
     OK, I will try to use Enterprise-2.2.26.

**Comment by laa** [comment]
@KishoDai did you have this issue?

**Comment by laa** [comment]
@KishoDai do you still have this issue? If so could you create thread dump at the moment when shutdown is frozen?

**Comment by laa** [comment]
@KishoDai did you have got this issue in the latest release?

**Comment by laa** [comment]
@KishoDai did you have got this issue in the latest release?

**Comment by KishoDai** [comment]
Hi @laa 
   Thank you.
    I have upgraded to enterprise-2.2.26, didn't encounter the issue recently.

**Comment by laa** [comment]
@KishoDai glad to hear that. I am closing issue for now. Please if you, unfortunately, will encounter this issue again, I do suggest you create several (well at least 3) thread dumps in 5 min interval and provide them as gists in this issue. But I crossed fingers and dream that it will never happen again.
