### ISSUE TITLE
link in one class

### ISSUE THREAD

**Issue by zhangshusheng** [orientechnologies/orientdb#7720]
## One question 
Two vertex that belong to one edge are in a same class.  Can be?
For example, a class about car routing infomation that has start and target atributes.  Can we build one edge from start to target (start and target in same class)?

**Comment by luigidellaquila** [comment]
Hi @zhangshusheng 

Yes, absolutely, there are no constraints about this. You can also have an edge that starts and ends from/to the same vertex

Thanks

Luigi

**Comment by zhangshusheng** [comment]
Hi @luigidellaquila
OK, I will try to build an edge .
Thank  you .

**Comment by luigidellaquila** [comment]
Hi @zhangshusheng 

I'm closing this ticket, please feel free to reopen if you need further info

Thanks

Luigi
