### ISSUE TITLE
Use JNA and  getDirectByteBuffer to avoid MaxDirectMemory limitations

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7723]
We use now byte buffers to leverage JVM intrinsics and support direct IO operations (to avoid usage of CPU and directly write data to file mitigating the CPU overhead if possible). But as result users bound to setup MaxDirectMemory setting every time when they start our application. It is proposed to use JNA [malloc](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Native.java#L2192)/[free](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Native.java#L2199)  and [getDirectByteBuffer](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Native.java#L2211)  methods. 

What pros of this change:

1. We were/are going to support smaller pages in our system alongside with big one to improve system performance. But because substantial work on allocator this change was delayed, unfortunately. Usage of malloc/free will allows us do not create our own allocator and will allow us to minimize memory used by the Java process (several users complained about that). As result amount of work which is needed to introduce support for small pages into the system will be decreased a lot.
2. It will unlock possibility to fix OOMs during big queries without introducing overhead on serialization/deserialization for most of the cases. Details of this approach will be discussed with @luigidellaquila today.
3. Users will not be bounded to setup MaxDirectMemory setting to work with our system which causes a lot of confusion.

Cons:
We will use one more library. But we already used JNA and that did not cause any problems. I set release version to 2.2.x to because we need to fix OOMs during big queries ASAP.

**Comment by taburet** [comment]
looks ok, minus one parameter in configuration is always good

**Comment by luigidellaquila** [comment]
It seems a bit complex to be implemented in 2.2.x, but let's discuss it

Thanks

Luigi

**Comment by tglman** [comment]
Hi,

Is it there any other option for alloc/free (maybe unsafe)? 

give back some memory when not used anymore for me is a definitely good point.

I agree that probably if we want some resultset persistence is better to solve this in 3.x

**Comment by laa** [comment]
@tglman we can use Unsafe but we can not use it to create DirectByteBuffers as result will waste time to copy data from one memory to other using CPU not direct memory copy mechanics during IO operations. Also Native.malloc according to the investigation of one of our famous competitors is 3 times faster than Unsafe )). http://mail.openjdk.java.net/pipermail/hotspot-dev/2015-February/017084.html . BTW we discussed with @luigidellaquila and agreed that it should be done in 2.2.x . It will be not persisted direct memory so it will be faster.

**Comment by laa** [comment]
Ok, seems like no body has big objections. I will set it as an enhancement for 2.2.x version.

**Comment by laa** [comment]
Fixed
