### ISSUE TITLE
OSecuritySystem : NoClassDefFoundError

### ISSUE THREAD

**Issue by thanveeraqtharah** [orientechnologies/orientdb#7726]
## Expected behavior  
Hi when I  used latest version of orientdb-server i.e (" 2.2.26" )  , the below exception was thrown
Exception in thread "main" java.lang.NoClassDefFoundError: com/orientechnologies/orient/core/security/OSecuritySystem.

Earlier I was using orientdb-server 2.1.9 version , there was no exception. But when I updated to  2.2.26 this exception was thrown . Solution would be appreciated.

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>

**Comment by maggiolo00** [comment]
Hi @thanveeraqtharah 

do you have the startup log?

Thanks

**Comment by maggiolo00** [comment]
hi @thanveeraqtharah 

any news about the logs?

**Comment by thanveeraqtharah** [comment]
It got fixed. Thank you :)
