### ISSUE TITLE
Does orientdb support chinese fulltext search?

### ISSUE THREAD

**Issue by gzliudan** [orientechnologies/orientdb#7727]
Does orientdb support chinese fulltext search?

**Comment by robfrank** [comment]
You can configure the indexes to use Chinese analyzer:

2.2.x:
http://orientdb.com/docs/last/Full-Text-Index.html#analyzer

3.0.x (m2):
http://orientdb.com/docs/3.0.x/indexing/Full-Text-Index.html#customize-analyzers

Official documentation:

http://lucene.apache.org/core/5_3_2/analyzers-common/index.html?org/apache/lucene/analysis/cjk/package-summary.html

Note:  OrientDB 2.2.x uses Lucene 5.3.2, OrientDB 3.0.x uses Lucene 6.x

**Comment by gzliudan** [comment]
When will 3.0 be released?

**Comment by robfrank** [comment]
If you are in an exploration phase, my personal suggestion is to use 3.0.0m2. 
3.0.0GA is planned for mid November.

**Comment by gzliudan** [comment]
org.apache.lucene.analysis.cjk is not good for chinese. The accuracy of IKAnalyzer is much better. By the way, IKAnalyzer can support custom dictionary.
