### ISSUE TITLE
Lucene Spatial ST_Buffer function

### ISSUE THREAD

**Issue by kornelik** [orientechnologies/orientdb#7729]
## Expected behavior  
ST_Buffer returns a geometry that represents all points whose distance from this Geometry is less than or equal to distance.
Syntax: ST_Buffer(geometry,distance [,config])
In which units is the distance measured? And what limits does this distance have.
## Actual behavior  
The distance is measured not in meters and kilometers.

**Comment by maggiolo00** [comment]
Hi @kornelik 

it should be degrees, since the only Spatial Reference System supported is 4326

https://orientdb.com/docs/2.2/Spatial-Index.html#spatial-reference-system
