### ISSUE TITLE
how to select the specific edge between both vertexs

### ISSUE THREAD

**Issue by flyrainkey** [orientechnologies/orientdb#7736]
## Expected behavior  
<add here>  

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>

**Comment by maggiolo00** [comment]
hi @flyrainkey 

do you have more details about this?
Thanks

**Comment by flyrainkey** [comment]
hi @maggiolo00 
Vertex v_Cookbook with name"A",Vertex v_Food with name "B" and Edge with label "e_CookWith".
I want to find out the edges that connect these two vertices ,to judge if the edge exist
**![image](https://user-images.githubusercontent.com/20534165/30313267-51e15fd6-97cf-11e7-9ea5-d65f2008d92d.png)**

**Comment by maggiolo00** [comment]
hi @flyrainkey 

with SQL or JAVA API?

**Comment by flyrainkey** [comment]
SQL  and I use Python API

**Comment by flyrainkey** [comment]
hi @maggiolo00 
SQL and I use Python API

**Comment by maggiolo00** [comment]
hi @flyrainkey 

you can use the match statement 

```
match { class : Cookbook , where : (name = 'A'), as : cook }
	.out('CookWith') { class : Food, where : (name = 'B') , as : food } 
return cook.name,food.name
```

**Comment by flyrainkey** [comment]
Thank you very much @maggiolo00 
`sql = "LET $good_cook = select from v_Cookbook WHERE name = '%s';" \
                      "LET $food0 = select from v_Food WHERE name = '%s';" \
                      "LET $food1 = select from v_Food WHERE name = '%s';" \
                      "create edge e_CookWith from $food0 to $good_cook;" \
                      "create edge e_CookWith from $food1 to $good_cook;" \
                      % (foods, food0, food1)  
                      client.batch(sql)`
I want to judge if  e_CookWith exist before create edge e_CookWith

**Comment by flyrainkey** [comment]
hi @maggiolo00 
How can I use your code insert into my code. if the edge exist I will not create edge ,else I will createedge

**Comment by flyrainkey** [comment]
hi @maggiolo00
How can I use your code insert into my code. if the edge exist I will not create edge ,else I will create edge

**Comment by maggiolo00** [comment]
hi @flyrainkey 

with batch you can do something like this


```
let $good_cook = select from v_Cookbook where name = 'A'
let $food0 = select from v_Food where name = 'B'
let $food_edge = ( select from (select expand(inE('e_CookWith'))  from $good_cook)  where out = $food0[0].@rid)
if($food_edge.size() = 0){
	let $food_edge= create edge e_CookWith from $food0 to $good_cook
}
select expand(unionAll($good_cook,$food_edge,$food0))
```

**Comment by flyrainkey** [comment]
Thank you very much @maggiolo00 
This method works. you help me a lot .  and I want to ask one more question. why orientdb  documentation don't have these content or examples. I don't know where can I search method to solve these problem like these. Do you have any good suggestions or documentation ?

**Comment by luigidellaquila** [comment]
Hi @flyrainkey 

OrientDB docs is under continuous development. We know it's far from being perfect, but we are committed to make it better every day. For now that's the main reference, so we cannot suggest any other resources

Thanks

Luigi
