### ISSUE TITLE
[Question] How can i update a embdded map by using old values without transaction .

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#7739]
Hi 
I have a question about the Updating and increment a counter field in a embedded map structure 
I can write the **Transation** to select old value and the increment it and then update normally , it's ok and is a normal way .
But i search about a **simple** syntax for it like the following lines :
 
`UPDATE TLSM PUT Stati = "Posts", {Count: Count + 1, At: 126637377} where ID = 1`

Can i have the following syntax in ODB ?

Thanks 
Saeed Tabrizi

**Comment by luigidellaquila** [comment]
Hi @saeedtabrizi 

I'm not sure I understand the exact purpose of this, but did you try the following?

```
UPDATE TLSM ADD Stati.Posts[At = 126637377].Count = 1 where ID = 1
```

Thanks

Luigi

**Comment by saeedtabrizi** [comment]
Hi @luigidellaquila 
It's ok for me . 

Thanks 
Saed Tabrizi
