### ISSUE TITLE
[QUESTION] ordb produces Record (<#rid>) is null [OrientEdgeIterator]

### ISSUE THREAD

**Issue by Bankde** [orientechnologies/orientdb#7740]
## Actual behavior  
We see ordb produced this log.
```WARNI {db=<db_name>} Record (<#rid>) is null [OrientEdgeIterator]```

We can't explicitly reproduce it.
Do you know what's the possible cause of this ?
Is there any action we should take ?

**Comment by luigidellaquila** [comment]
Hi @Bankde 

maybe you deleted a record that was pointed by other records...? This can happen if you work at document level (eg. you manually manage links) or if you do DELETE UNSAFE in graph mode

Thanks

Luigi

**Comment by Bankde** [comment]
What do you mean by manually manage links, UPDATE link in, out ?
We normally do delete link then create new one. Only queries update link I have found in our app are
```
asprintf(&sql,"update V set out_%s = out_%s where out_%s is not null", e_rn[i]->new_name, e_rn[i]->edge_name, e_rn[i]->edge_name);
asprintf(&sql,"update V set in_%s = in_%s where in_%s is not null", e_rn[i]->new_name, e_rn[i]->edge_name, e_rn[i]->edge_name);
```

By DELETE UNSAFE, if you refer to DELETE rid directly without using DELETE VERTEX and DELETE EDGE, I have gone through our code and we never do that.

Not sure if this will cause problem ? Looks unrelated to this issue to me.
```
asprintf(&sql,"alter class %s name %s UNSAFE", rn[i]->class_name, rn[i]->new_name);
```

**Comment by Bankde** [comment]
Also sometimes ordb produces error without rid
2017-09-14 03:05:07:463 WARNI {db=<db_name>} Record (null) is null [OrientEdgeIterator]

**Comment by Bankde** [comment]
I'm still not sure what is "manually manage links".
According to last answer, it seems like normal warning that ordb produces regularly and can be ignored.

Would like a last check. If I understand correctly, going to close this question.
Thanks.

**Comment by luigidellaquila** [comment]
Hi @Bankde 

You should never manage out/in links in vertices an edges with a manual UPDATE on the vertex. You should always use CREATE/DELETE EDGE to manage edges.

If you do a manual update of the properties, OrientDB won't manage the graph consistency for you

Thanks

Luigi

**Comment by Bankde** [comment]
Thank you.
I have gone through code and remove the code that we're uncertain out from the test. Yet the warning still happens.

Do you think concurrent transaction commit (that 1 of them will definitely fail from data already changed by another commit) will produce this warning ?

Both of the transaction consist of only
```
- UPDATE vertex attribute
- CREATE VERTEX
- CREATE EDGE
- DELETE EDGE
- SELECT VERTEX
```

We do have some queries that specify the rid like this
```
CREATE EDGE toDataContent from #37:48243 to $anotherVertexJustCreatedInSameBatch
```
Do you think inserting rid directly into query is ok ?

The rids in warning don't seem to match any of the rids in queries.
I have also tried to run a those query with several rids, it seems that a query alone doesn't seem to produce "rid is NULL" warning.

**Comment by luigidellaquila** [comment]
Hi @Bankde 

The warning happens just because probably you have some dirty links in the existing vertices, but OrientDB should be able to manage them transparently. I'd say you can live with it.

Using links in the queries is absolutely OK (and very good in terms of performance), as long as you use the statements listed above.

Thanks

Luigi

**Comment by Bankde** [comment]
That's very clear. Thank you so much.
