### ISSUE TITLE
After deleting a few properties OrientVertexType.existsProperty(name) is missbehaving

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#7742]
### OS: <linux>  

After deleting a few properties in ODB studio I can see in studio that the properties are gone.
But the app code does not agree 
orientVertexType.existsProperty(name) still say they exist.
When inspecting the class OClassImpl i can see it is hanging on to the deleted properties.

My code looks roughly like the following:
```
		graph.executeOutsideTx(new OCallable<Object, OrientBaseGraph>() {
            public Object call(OrientBaseGraph iArgument) {
            	try {
            		OrientVertexType ovtype = graph.getVertexType(dataStore);
            		if(ovtype != null) {
if(ovtype.existsProperty(name)) {...}else {...}
            		}
            	}
            	catch(OSchemaException ose) {
            		System.out.println("Error: .......");
            	}
                return null;
            }
        });	
```

Is this a bug or do I somehow need to refresh the OrientGraph? 
Restarting the server makes the problem go away but I would hate having to bounce the server every time!

**Comment by maggiolo00** [comment]
hi @temilmg 

do you have a `remote` connection or `plocal` one?

**Comment by temilmg** [comment]
I am using a remote connection

**Comment by maggiolo00** [comment]
hi @temilmg 

Unfortunately the schema is cached client side. If you change it from Java API, it will be aware of the change. If you change the schema from Studio for example, the client will not be aware of that. In 3.0 we will have probably push notification on schema, meanwhile you can force the schema reload with this api

```
graph.getRawGraph().getMetadata().getSchema().reload();
```

**Comment by temilmg** [comment]
Thank you Maggiolo00
