### ISSUE TITLE
CREATE EDGE vs UPDATE ... UPSERT -> look like as same but behavior is different

### ISSUE THREAD

**Issue by lanzay** [orientechnologies/orientdb#7746]
## Expected behavior  
Create right EDGE for traverse
UPDATE EDGE have NO "UPSERT" - it is not convenient

## Actual behavior  
create all items w/o error but not right created EDGE
1 to 3 - not right EDGE (look like all right)
How do it in one step?

## Steps to reproduce  
CREATE CLASS users IF NOT EXISTS EXTENDS V
CREATE CLASS e_frend IF NOT EXISTS EXTENDS E
UPDATE users CONTENT {"ID": 1, "Name":"Name1"} UPSERT WHERE ID = 1
UPDATE users CONTENT {"ID": 2, "Name":"Name2"} UPSERT WHERE ID = 2
UPDATE users CONTENT {"ID": 3, "Name":"Name3"} UPSERT WHERE ID = 3

CREATE EDGE e_frend FROM (SELECT FROM users WHERE ID = 1) TO (SELECT FROM users WHERE ID = 2)

UPDATE e_frend SET out = (SELECT FROM users WHERE ID = 1), in = (SELECT FROM users WHERE ID = 3) UPSERT WHERE out.ID = 1 and in.ID = 3

**Comment by luigidellaquila** [comment]
Hi @lanzay 

The UPDATE/UPSERT works at document level, so it doesn't create the connections from the vertices. Using it, you will have a broken graph. 
Unfortunately there is no CREATE EDGE with UPSERT yet, we have an open issue for this: https://github.com/orientechnologies/orientdb/issues/4436

Thanks

Luigi
