### ISSUE TITLE
Renaming a property doesn't work as a renaming

### ISSUE THREAD

**Issue by adepase** [orientechnologies/orientdb#7747]
## Expected behavior  
Renaming a property from Studio results in a renaming in every place (list of properties, graph editing, indexes, etc. etc.) in a consistent way

## Actual behavior  
Renaming a property results in creating a new property, with all the values of the previous property in the corresponding instances of the class, but without the removal of the previous property, nor with a replacement in indexes and with some other inconsistencies.
For example: I had a class with a property named id_lemma, with an index on it. I renamed it codLemma.
The index remained on id_lemma and, when going on the details of the class instances starting from the graph, I can see both fields (with the same values). If I try to administer the class starting from the schema and going into the properties, I can just see codLemma (not id_lemma), but I can clearly see the previous index still referencing id_lemma.
Queries referencing id_lemma work and are faster than those referencing codLemma (because of the index, I guess).
The overall behaviour is inconsistent.

## Steps to reproduce  
Studio->Schema->Select Vertex (i.e. arriving in the page: [myhost]/studio/index.html#/database/mrj/schema/editclass/[myClass], where [myClass] is the class name I'm going to administer). Rename a property (clicking on the blue button). Then see "Actual Behaviour"

**Comment by tglman** [comment]
Hi, 
We are aware of some of this issue, we are going to tackle one by one in the next versions, but we don't have a direct fix for this, I'll leave this open for keep track.

Regards

**Comment by adepase** [comment]
Ok, once understood not so difficult to manage, but nevertheless I'm
interested in its resolution too.
Thank you
Best regards
Alessandro


Il 18 Set 2017 4:07 PM, "tglman" <notifications@github.com> ha scritto:

Hi,
We are aware of some of this issue, we are going to tackle one by one in
the next versions, but we don't have a direct fix for this, I'll leave this
open for keep track.

Regards

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/orientechnologies/orientdb/issues/7747#issuecomment-330233602>,
or mute the thread
