### ISSUE TITLE
Question: When the record version hits the max int limit. Does it overflow and continue as normal or break?

### ISSUE THREAD

**Issue by RyanTopps** [orientechnologies/orientdb#7755]
OrientDB Version: 2.2
Java Version: 1.8
OS: Ubuntu 16.04

## Expected behavior  
The record version number overflows and starts over with no problems.

## Actual behavior  
Didn't reach limit yet, but might in a year. I need to know if this breaks the db or continues as normal. The only way it will break if there is not a special case of INT_MAX < 0.

## Steps to reproduce  
Overflow the @version in the record.

**Comment by laa** [comment]
@RyanTopps if you do not use distributed you will not experience any problems with that.

**Comment by laa** [comment]
@RyanTopps did I answer your question?

**Comment by RyanTopps** [comment]
Yes, for future reference if I switch to a distributed system, what kind of conflict resolution should I use?

**Comment by laa** [comment]
@tglman could you help on that?

**Comment by laa** [comment]
As for now, we do not plan to support version overflow,
