### ISSUE TITLE
Get vertex by rid is slow

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7758]
## Expected behavior  
get vertex by rid should be a O(1) operation, so I can get one vertex in N ms.

## Actual behavior  
try to get many vertexes by their rid one by one, some of them cause 1~5ms, some of them cause 10 or even 100 ms

## Steps to reproduce  
1. get record form Hbase and create vertex in OrientDB
2. cache this mapping Hbase' rowKey -> OrientDB' rid in redis
3. repeat 1 and 2 to create 2 hundred million vertexes
4. scan Hbase again to get the rowKey one by one
5. get the rid from redis base on the rowKey: this operation is fast, causes only 1 ms.
6. get vertex by rid, this is the issue describe above

**Comment by weickdev** [comment]
I find there are many Read operations blocked in system's IO queue when the fetching operation is slow:
![system_read_queue](https://user-images.githubusercontent.com/31640567/30634452-bb37050a-9e21-11e7-94bb-69200ad2a849.png)

**Comment by laa** [comment]
@weickdev Redis is in memory database ODB is disk-based database. They can not have the same performance. How much is your ODB size and how much is your size of disk cache?

**Comment by weickdev** [comment]
I have 2 classes Company and Person. The pcl files size are:
- Size of Company: 3.8G X 8
- Size of Person: 4.3G X 8
> 8 means I have 8 clusters, so there are 8 files for each class.

And the index files:
- Index size of Company: 8G
- Index size of Person: 17G

I cannot sure the disk cache. 
- When the ODB starting, it it print: `rientDB auto-config DISKCACHE=37,271MB (heap=3,925MB direct=40,960MB os=43,244MB)`
- In the config file, I add this:
` 
...
  <properties>
    <entry name="cache.size" value="51200" />
    <entry name="storage.keepOpen" value="true" />
  </properties>
  ...
`
following the doc: https://orientdb.com/docs/2.2/Configuration.html
- in the console, I run config command, I see the `storage.diskCache.bufferSize` is 4096

Is there some config wrong? @laa

**Comment by weickdev** [comment]
@laa I run below command in console to set the deskCache buffersize to 20G, it's default value is 4G
`config set storage.diskCache.bufferSize 20480`
 But it seems useless for the fetch speed. Is there anything I can do to speed up the fetch operation by rid.

**Comment by weickdev** [comment]
@laa I try to cache the mapping between Hbase's rowKey and ODB's rid, when I create edge, I use the rid directly instead of the search subquery, such as `CREATE EDGE E1 FROM #10:3 TO #11:4`
But the creating speed is slow too. It costs about 30ms or more to create one edge. It is horrible to create massive edges. So what do ODB do when creating edge? Is there anything I can do to improve the create efficiency？

**Comment by laa** [comment]
@weickdev your size of the database on disk is about 90 GB and your size of the disk cache is 37 GB, so only about 40% of data is cached in memory. If you make uniformly distributed random updates of disk data, you will inevitably work with the disk. In production, in reality, data will not be uniformly distributed, some data will be accessed much often than other ones. Frequently used data will be cached and as a result, will be accessed in no time. But if you want to have fast access to all data does not matter whether they are rarely accessed of frequently you need to have the amount of RAM at least as much as the size of the database on disk. We are working on decreasing the size of the database on disk and in memory.

**Comment by weickdev** [comment]
@laa Thanks for you replay, I will try to increase the RAM and check the data distribution. I will reply the result when I finish the test.

**Comment by zlfsimon** [comment]
@laa  I also have the same issue: https://github.com/orientechnologies/orientdb/issues/7672

**Comment by laa** [comment]
@zlfsimon that is not the same, this issue about fetching by key.

**Comment by weickdev** [comment]
@laa @zlfsimon I think there are some relations between the two issues. Because @zlfsimon cannot set the rid by himself, so he must search the vertex before creating edge. If fetching by key is slow, creating huge edges will cost a lot time.
> @zlfsimon that is not the same, this issue about fetching by key.

**Comment by weickdev** [comment]
@laa  I try to increate my RAM, the average fetching speed is 2~3ms/vertex. It is indeed faster than above, but I think it is not fast enough if there are huge fetching operations, such as huge creation of edges. On the other hand, my data may increase to TB, so I cannot cache all datas in RAM. So is there any other way to improve the fetching efficiency? Or any other way to improve the huge edges creation efficiency.

**Comment by laa** [comment]
@weickdev the other way to improve speed is very fast SSD, for example having of PCIE SSD should improve speed of operations.

**Comment by weickdev** [comment]
@laa SSD is a good choice as some scenarios. Is there any code optimizations can improve it. For example, I find in class OCommandExecutorSQLCreateEdge, it's always fetching the vertex before create the edge, even if I know the rid of the vertex. Can we just use the rid passed in the sql parameters to create the edge, instead of fetching the vertex and call the vertex' addEdge()?

**Comment by lvca** [comment]
@weickdev the "add edge" operation needs to load both vertices anyway in order to create the edge.

**Comment by weickdev** [comment]
@lvca so why I must load vertices if I can set the rid directly to the edge?

**Comment by laa** [comment]
@weickdev because information about edges reflected both in documents related to vertexes and documents related to edges. 

About your question related to code optimizations, we periodically do code optimizations by benchmarking and comparing different results.

**Comment by weickdev** [comment]
@laa Get it. I read the code again, and find it creates the link in vertex. Thanks for your help.
