### ISSUE TITLE
Hooks not aware of rollback

### ISSUE THREAD

**Issue by chandru-jsr** [orientechnologies/orientdb#7763]
## Expected behavior  
Insert operation invokes Hooks, similarly when rollback, it should invoke Hooks with previous value

## Actual behavior  
After insert, when rollback, Hooks are not invoked

## Steps to reproduce  
                Begin
                                Insert A
                                Update B
                                create edge with @invalid-rid(this fails)
                commit
No hooks executed, after rollback.

Also, Hooks are not transaction aware and executes per table/class.

Thanks
Chandru.

**Comment by maggiolo00** [comment]
hi @chandru-jsr 

which hook do you expect to be called on rollback?

Thanks

**Comment by chandru-jsr** [comment]
In the above example, When inserting into A, then hooks is triggered. But when rollback, the hooks is not triggered(lets say onRecordAfterDelete() event hook).
