### ISSUE TITLE
Very strange error with wrong OrientDB version number & node trying to get exclusive lock on the database

### ISSUE THREAD

**Issue by hanksieM** [orientechnologies/orientdb#7764]
## Expected behaviour  
version number on console and server log to be 2.2.26
node will join cluster and have the database online.

## Actual behavior  
we have 5 nodes,  4 upgrade correctly but one node will not and reports the version as 2.2.15 on the console and the server logs.  This node also will join the cluster but marks the database as unavailable and the logs show it could not get an exclusive lock on the database.  I can't get the logs off this system as it's commercially very sensitive.  but this is my hand copied/typed line:

WARNI  [60] Timeout(20001)ms on waiting for synchronous responses from nodes=[58] responsesSoFar=[] request=(id=4.0 task=exc_lock acquire resource=mydb) [ODistributedDatabaseImpl]
WARNI [60] -> [58] Server '60' cannot acquire distributed lock on resource 'mydb' (timeout=20000)...[ODistributedLockManagerRequester]
SERVER [60] Error on installing database 'mydb' on local node (error=com.orienttechnologies.common.concur.lock.OLockException: Servier '60' cannot acquire exclusive lock on resource 'mydb' (timeout=20000)) [OHazelcastPlugin]
INFO [60] Updated node status to 'ONLINE' [OHazelcastPlugin]
INFO [60] Distributed servers status (*=current @=lockManager[58]):

60 and 58 are our nodes,  60 is failing.

Tried,

a) checked the lib directory only has 2.2.26 versioned jars
b) cleared the node and rm -rf  the install directory. Then re-installing (we use ansible to copy the rpm we have built of Orientdb then the server xml is templated and ssl certs copied.)
c) cleared the node and rm -rf  the install directory. Then copied the install from a node that is working (reset the ssl certs and config)
d) remove java from the system and did b) 
e) compared the jars from this node to the others (which are working)

## Steps to reproduce  
?

**Comment by maggiolo00** [comment]
hi @hanksieM 

how did you upgrade the ` 4 ` nodes succesfully?

Did you shutdown the cluster?

**Comment by hanksieM** [comment]
Yes, all the nodes were closed and the processes killed if they failed to stop (we get that occasionally).  We suspect the problem is with an in-house plug-in including Orientdb classes in the pom.xml and marking the scope as "compile" and not "provided".  Just testing I'll edit/close this post if that is the fix.

**Comment by maggiolo00** [comment]
Ok @hanksieM 

let me know, thanks

**Comment by hanksieM** [comment]
thanks for your time @maggiolo00,  

I can confirm that the plugins were causing the problem,  We are still final checking and deploying but I will close this now.  

The error was in the Maven pom file having the scope wrong and dependencies on various bits of OrientDB were including the core as a third party dependency.  We can't explain why most nodes worked and some did not; but that's class path problems for you!
