### ISSUE TITLE
ODiskWriteAheadLog's read not working

### ISSUE THREAD

**Issue by chandru-jsr** [orientechnologies/orientdb#7767]
## Expected behavior  
In GratefulDeadConcerts Datavase - wal.read() should return record 

## Actual behavior  
wal.read() throws OWALPageBrokenException: WAL page with index 0 is broken

## Steps to reproduce  
My requirement is to read entries from WAL, transform and publish to Kafka topic(as my requirement doesn't fit with Hooks)

1. Downloaded orientDB and start the server.bat
2. Execute the below code,

import com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer;
import com.orientechnologies.orient.core.config.OGlobalConfiguration;
import com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache;
import com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage;
import com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog;

public class ReadWal {
    private static long calculateReadCacheMaxMemory(final long cacheSize) {
        return (long) (cacheSize * ((100 - OGlobalConfiguration.DISK_WRITE_CACHE_PART.getValueAsInteger()) / 100.0));
    }
    public static void main(String[] args) throws IOException {
        //OMemoryAndLocalPaginatedEnginesInitializer.INSTANCE.initialize();
        O2QCache readCache = new O2QCache(calculateReadCacheMaxMemory(OGlobalConfiguration.DISK_CACHE_SIZE.getValueAsLong() * 1024 * 1024),
                OGlobalConfiguration.DISK_CACHE_PAGE_SIZE.getValueAsInteger() * 1024, true,
                OGlobalConfiguration.DISK_CACHE_PINNED_PAGES.getValueAsInteger());
        OLocalPaginatedStorage localStore= new OLocalPaginatedStorage("GratefulDeadConcerts",
                "C:\\Users\\CS7277\\Downloads\\orientdb\\databases\\GratefulDeadConcerts",
                "read",0,readCache,new OClosableLinkedContainer(OGlobalConfiguration.OPEN_FILES_LIMIT.getValueAsInteger()));
        ODiskWriteAheadLog wal= new ODiskWriteAheadLog(localStore);
        System.out.println(wal.begin());// LSN{segment=0, position=16}
        System.out.println(wal.read(wal.begin()));

        System.out.println("Ends");
    }
}

3. wal.begin(); returns LSN{segment=0, position=16} but when wal.read(wal.begin()), it throws exception

**Note**: 
I did not edit any files under databases folder and also it is a fresh OrientDB downloaded without any commands passed in my local.

Thanks,
Chandru.

**Comment by laa** [comment]
@chandru-jsr I will check your case but I deferentially do not recommend you read entries from WAL they do not contain business information that is binary data about raw changes in WAL. WAL API is not public and never will be public it is only for private use.

**Comment by laa** [comment]
@chandru-jsr my observations:

1. You can not start the server and at the same time access database from other JVM.
2. I executed code which you provided here is my output:
LSN{segment=0, position=28}
com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OAtomicUnitStartRecord{lsn=LSN{segment=0, position=28}, isRollbackSupported=true}
Ends

I downloaded server and used distribution right from there.
Could you provide database which you used ?

**Comment by chandru-jsr** [comment]
Iaa, Thank for your response.

The database name is GratefulDeadConcerts, that i am pointing in my local to read WAL's.

I planned to read WAL files because OrientDB doc says , WAL is the Journal. https://orientdb.com/docs/2.2/Write-Ahead-Log.html

Per your recommendation, it is not good to read WAL directly. 

Some more question:
1. If WAL is not for external journal, then please recommend in what way can I send the atomic manipulations(any insert/delete/update happened under 1 transaction) to other system(like Kafka) which shall be at least eventually consistent?
2. If You suggest Hooks(which is robust), but it is unaware of transaction boundaries and rollbacks, which is known for per table updates. This was the issue which i raised already. to confirm my experiment (https://github.com/orientechnologies/orientdb/issues/7763) 
3. If you suggest LiveQuery, then if the consumer restart, the event triggered by LiveQuery between the restart will be lost. So I don't want to go LiveQuery.
3. Is there any in-build behavior with OrientDB that support "Live Robust Journal" which should also know the transaction boundaries and that can be accessed outside OrientDB.

If any of my above understanding is wrong, please correct me or suggest me the best approach.

Thanks,
Chandru.

**Comment by laa** [comment]
Hi, @chandru-jsr , that is a good question, we will discuss that with @luigidellaquila.  But unfortunately, I suppose we will not provide such means in short future.

**Comment by chandru-jsr** [comment]
Ok, Expected the response soon. Thanks.

**Comment by laa** [comment]
Fixed in 3.1
