### ISSUE TITLE
Cannot open a connection to remote server 

### ISSUE THREAD

**Issue by manjunathamm24** [orientechnologies/orientdb#7768]
orientdb> connect remote:localhost root root

Connecting to remote Server instance [remote:localhost] with user 'root'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot connect to the remote server/database 'remote:localhost/'

Error: com.orientechnologies.common.io.OIOException: Error on connecting to 127.0.0.1:2424

Error: java.net.ConnectException: Connection refused: connect

**Comment by luigidellaquila** [comment]
Hi @manjunathamm24 

Are you sure you have a server running? Could you please post the logs of the server (maybe it's running on a different port...)

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @manjunathamm24 

Any news here? Did you manage to make it work?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
OK, I'm closing this, please feel free to re-open if you have more info

Thanks

Luigi
