### ISSUE TITLE
Open-unused Connections and high number of requests

### ISSUE THREAD

**Issue by christianascone** [orientechnologies/orientdb#7769]
## Expected behavior  
I'm using [phpOrient](https://github.com/Ostico/PhpOrient) in order to connect with binary protocol.
I have two VMs, one with Orientdb installed and the other which makes connections (172.16.19.1 IP in images).

I expect my connections to be dropped when they're not used anymore or when the host with Orientdb is not reachable.
<img width="682" alt="screen shot 2017-09-25 at 00 20 38" src="https://user-images.githubusercontent.com/14952409/30802201-011fbdf6-a1e6-11e7-843d-cee9c3285ced.png">

## Actual behavior  
Currently I noticed that if my Orientdb's host become unreachable for the 2° VM, I still have open connections.
<img width="677" alt="screen shot 2017-09-25 at 00 35 32" src="https://user-images.githubusercontent.com/14952409/30802992-744121ec-a1e8-11e7-9696-bc29fb97c421.png">

I noticed this problem because, after some days of uptime, my OrientDB instance CPU usage reaches very high spikes which can be solved only with a service restart.

## Questions

1. Could these open connections lead to a leak resulting in CPU spikes?
2. Could CPU spikes also be caused by many TOT_REQS on a single connection?

Thank you in advance for your support

**Comment by lvca** [comment]
Are you closing the connections from your client?

**Comment by christianascone** [comment]
Hi @lvca, thank you for your reply.
Currently there are connections which are not closed, because some scripts never ends their execution, but I'm working on it in order to close them.
Besides the fact that it is the good way of using connections, do you think this could be the reason for high CPU usage after a few days of uptime?

I'm also trying to switch to the HTTP protocol. Could this solve my problem without manually closing connections?

**Comment by saeidalidadi** [comment]
I have this issue and my client is `node.js` that is connected by `orientjs` driver, also I have called `.close()` everywhere after my db queries, I also use `socket.io` which I call db methods inside it.
