### ISSUE TITLE
Can't restore the file backup by orientdb

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7770]
## Expected behavior  
Can restore the backup file by orientdb mannually.

## Actual behavior  
[jizhang.dai@iZbp11qmscpoodmtbwzbgsZ bin]$ sh console.sh

OrientDB console v.2.2.26 (build ae9fcb9c075e1d74560a336a96b57d3661234c7b) https://www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> create database plocal:/home/jizhang.dai/orientdb/orientdb-enterprise-2.2.26/databases/sns              

Creating database [plocal:/home/jizhang.dai/orientdb/orientdb-enterprise-2.2.26/databases/sns] using the storage type [plocal]...
Database created successfully.

Current database is: plocal:/home/jizhang.dai/orientdb/orientdb-enterprise-2.2.26/databases/sns
orientdb {db=sns}> connect plocal:/home/jizhang.dai/orientdb/orientdb-enterprise-2.2.26/databases/sns admin admin          

Disconnecting from the database [sns]...OK
Connecting to database [plocal:/home/jizhang.dai/orientdb/orientdb-enterprise-2.2.26/databases/sns] with user 'admin'...OK
orientdb {db=sns}>  restore database /home/jizhang.dai/orientdb/backup/sns-1505697105369/sns_2017-09-18-10-00-00_0_full.ibu

Restoring database 'database /home/jizhang.dai/orientdb/backup/sns-1505697105369/sns_2017-09-18-10-00-00_0_full.ibu' from full backup...
Database restored in 0.14 seconds
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/home/jizhang.dai/orientdb/orientdb-enterprise-2.2.26/databases/sns' with mode=rw
	DB name="sns"

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'sns' because it does not exist in path: /home/jizhang.dai/orientdb/orientdb-enterprise-2.2.26/databases/sns
	DB name="sns"

orientdb {db=sns}> 

## Steps to reproduce  
<add here>

**Comment by laa** [comment]
@KishoDai could you send me `sns_2017-09-18-10-00-00_0_full.ibu` file so I will repeat your steps?

**Comment by KishoDai** [comment]
Hi @laa 
    The file is very large about 10GB. How to send you?

**Comment by KishoDai** [comment]
Hi @laa 
    I tried it in my Local and encounted the same error. So you can test it in your local.

**Comment by laa** [comment]
@KishoDai what do you mean when writing that I can try on my Local?

**Comment by KishoDai** [comment]
@laa 
    You just backup up your database from your local by orientdb backup management and generated *.ibu file. Then restore the file in console

**Comment by laa** [comment]
@KishoDai sorry but I can not reproduce this exception, could you send me full stack trace exception from the console logs, so I will see root cause?

**Comment by laa** [comment]
@KishoDai how did you make a backup ?

**Comment by KishoDai** [comment]
Hi @laa 
   In orientdb studio-> backup management->

**Comment by KishoDai** [comment]
Hi @laa
     The above is all the losgs.

**Comment by laa** [comment]
@KishoDai ok I found reason anyway, for the backups created with the studio you should use the following command `CREATE DATABASE ./sns  --restore=<path to backup file>` . Backup which you generated is for enterprise database only and you should use a different command.

**Comment by KishoDai** [comment]
Hi @laa 
   Do it as what you said. But it just create database not restore it.

orientdb> CREATE DATABASE plocal:/home/kisho.dai/mnt/orientdb/orientdb-enterprise-2.2.26/databases/sns --restore=/home/kisho.dai/mnt/orientdb/orientdb-enterprise-2.2.26/backup/databases/sns/sns-1506348915203

Creating database [plocal:/home/kisho.dai/mnt/orientdb/orientdb-enterprise-2.2.26/databases/sns] using the storage type [plocal]...
Database created successfully.

Current database is: plocal:/home/kisho.dai/mnt/orientdb/orientdb-enterprise-2.2.26/databases/sns

**Comment by laa** [comment]
@KishoDai I do not see any problems, do you have any additional observations?

**Comment by KishoDai** [comment]
Hi @laa 
   Thank you. Now it OK.
   The commad is "create database remote:localhost/sns admin admin plocal graph -restore=/mnt/orientdb-enterprise-2.2.26/backup/databases/tmp"
