### ISSUE TITLE
Access Encrypted DB using OServerAdmin

### ISSUE THREAD

**Issue by frostarun** [orientechnologies/orientdb#7771]
## Expected behavior  
Need to Create and access encrypted DB using OServerAdmin . 

## Actual behavior  
Key is never being set also I don't know whether my DB is encrypted or not.

ERROR : Its saying you have set AES method , But there is no Key provided . Please set it in property while create/open database .
PS : I actually dunno where to set that property , So i have set it in OGlobalConfiguration. But the key it not set. 

## Steps to reproduce  
String remote2 = "remote:192.168.0.139:2424/sample_encrypt5";
OServerAdmin serverAdmin = new OServerAdmin(remote2);
OGlobalConfiguration.STORAGE_ENCRYPTION_KEY, "T1JJRU5UREJfSVNfQ09PTA==";
OGlobalConfiguration.STORAGE_ENCRYPTION_METHOD, "aes";
serverAdmin = serverAdmin.connect("root", "abcd");
boolean connected = serverAdmin.isConnected();
System.out.println("connected = " + connected);

**Comment by tglman** [comment]
hi @frostarun,

The encryption key must be configured on the server at the moment.

Regards

**Comment by frostarun** [comment]
Thanks for your quick reply. 
and Yes  , I configured that in orientdb-server-config.xml 

`<properties>
        <entry value="1" name="db.pool.min"/>
        <entry value="50" name="db.pool.max"/>
        <entry value="false" name="profiler.enabled"/>
	<entry value="aes" name="storage.encryptionMethod"/>
	<entry value="T1JJRU5UREJfSVNfQ09PTA==" name="storage.encryptionKey"/>
    </properties>`

But unfortunately everyone is able to access the DB using remote without key. 

According to your document you need to set the key in OGlobalConfiguration while accessing the DB or else it should not allow the user to access right ?

**Comment by tglman** [comment]
hi @frostarun,

if you run orientdb in embedded you don't have a server so you need to set OGlobalConfiguration.
Yes all the user of the db are allowed to access and if you want to add some limits you need to use the roles.
The purpose of the encryption is to not keep on the disc data in plain and not to handle access profiling and network encryption, this is done with user profiling and ssl/tls.

Regards

**Comment by frostarun** [comment]
@tglman I thought the same and did the same ( used SSL ) . Thank you very much for your reply .
