### ISSUE TITLE
Projection over fetchplan

### ISSUE THREAD

**Issue by mahmed8003** [orientechnologies/orientdb#7778]
OrientDB supports projection over fetchplan?

Scenario: User have link to device
```sql
SELECT * FROM (user-record-id) fetchplan device:1
```
Above command returns the complete device data 
```json
{
  "@type": "d",
  "@rid": "#34:0",
  "@version": 1,
  "@class": "Device",
  "name": {
    "@type": "d",
    "@version": 0,
    "@class": "DeviceName",
    "defaultNames": [
      "Bulb"
    ],
    "name": "Bulb",
    "nicknames": [
      
    ]
  },
  "type": "action.devices.types.LIGHT",
  "traits": [
    "action.devices.traits.OnOff",
    "action.devices.traits.Brightness"
  ],
  "deviceInfo": {
    "@type": "d",
    "@version": 0,
    "@class": "DeviceInfo",
    "manufacturer": "Google",
    "model": "B0-12",
    "hwVersion": "1.2.3",
    "swVersion": "1.0.0"
  },
  "willReportState": true,
  "createdAt": "2017-09-11 00:42:24",
  "updatedAt": "2017-09-11 00:42:24",
  "status": "ACTIVE",
  "hideFrom": [
    
  ],
  "owner": "#19:38",
  "@fieldTypes": "createdAt=t,updatedAt=t,hideFrom=n,owner=x"
}
```

But I am only interested in deviceInfo, Is there anyway to put projection on fetch plan?

**Comment by maggiolo00** [comment]
Hi @mahmed8003 

you can try this

```
SELECT * FROM (user-record-id) fetchplan device:-2 device.deviceInfo:1
```

by excluding `device` and including `device.deviceInfo`
Let me know if it helps

In OrientDB 3.0 (available from 3.0M2) we will have nested projections that are designed to provide a better solution for this cases.

https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections

Thanks

**Comment by mahmed8003** [comment]
I executed this query 
```sql
SELECT * FROM #22:4 fetchplan device:-2 device.deviceInfo:1
```

and it returns
```json
{
  "@type": "d",
  "@rid": "#34:0",
  "@version": 2,
  "@class": "Device",
  "deviceInfo": {
    "@type": "d",
    "@version": 0,
    "@class": "DeviceInfo"
  }
}
```
It is only returning metadata about record only. All the other fields ignored.

And nice to see nested-projections feature in DB.

Thanks

**Comment by maggiolo00** [comment]
hi @mahmed8003 

which version are you using?

**Comment by mahmed8003** [comment]
@maggiolo00 

Studio version : 2.2
OrientDB version : 2.2.26

**Comment by maggiolo00** [comment]
I tested on a sample db and it worked. Do you have a simple database where i can test it?

Thanks

**Comment by mahmed8003** [comment]
[SmartHome (2).gz](https://github.com/orientechnologies/orientdb/files/1351465/SmartHome.2.gz)

Please import this and perform this query
```sql
SELECT * FROM #22:4 fetchplan device:-2 device.deviceInfo:1
```

**Comment by maggiolo00** [comment]
@mahmed8003 

thanks i will give it a try

**Comment by maggiolo00** [comment]
Hi @mahmed8003 

in this case if you need `deviceInfo` you can simple use projections.

```SQL
select *,device.deviceInfo as deviceInfo from #22:4
```
Let me know

**Comment by mahmed8003** [comment]
Hi,
Yes for this case above query woking fine. 
But did you check this query
```sql
SELECT * FROM #22:4 fetchplan device:-2 device.deviceInfo:1
```
Is it working fine on your side? There are many other scenarios where I need projection over fetchplan

**Comment by maggiolo00** [comment]
Hi @mahmed8003  it's not working on my side. 

Generally speaking fetch plan are used for over fetch data to reduce latency.
Projections over fetch plan does not really cover all use case that's why in 3.0 we will have nested projections.

For example you cannot alias a fetch plan nor you cannot select more fields in the same fetch plan. 

My advice is to use normal projections to do that.

**Comment by mahmed8003** [comment]
Okay thanks you @maggiolo00 
I am closing this issue and going to test OrientDB 3.0 M2 for my usecase.
