### ISSUE TITLE
How to set lower Maximum Heap (-Xmx setting on JVM) 

### ISSUE THREAD

**Issue by Pakinwet** [orientechnologies/orientdb#7779]
## Questions
How to set lower Maximum Heap (-Xmx setting on JVM) 

WARNI
Not enough physical memory available for DISKCACHE: 2,000MB (heap=1,344MB direct=1,500MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [OMemoryAndLocalPaginatedEnginesInitializer] 

I'm configuring OrientDB to Use Less RAM in the server.sh file
<img width="1268" alt="screen shot 2560-09-28 at 7 04 37 pm" src="https://user-images.githubusercontent.com/9396436/30965554-f8f6060c-a47f-11e7-9a13-9c8a55aa5d65.png">

`free -m`

<img width="574" alt="screen shot 2560-09-28 at 7 09 48 pm" src="https://user-images.githubusercontent.com/9396436/30965766-b87716e2-a480-11e7-9a6a-1de5576f6eb4.png">

Thank you in advance for your support :)
Sorry my English is not so good :)

**Comment by maggiolo00** [comment]
hi @Pakinwet 

did you stil receive the warning if you set  `-Xmx=1512` ?

**Comment by Pakinwet** [comment]
hi @maggiolo00 :) 

I assign maximum 1512 mb to protect against memory overload.

**Comment by maggiolo00** [comment]
@Pakinwet 
Which is the issue then?

**Comment by Pakinwet** [comment]
@maggiolo00 :) 
I would like to clear warning. 

```
WARNI
Not enough physical memory available for DISKCACHE: 2,000MB (heap=1,344MB direct=1,500MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [OMemoryAndLocalPaginatedEnginesInitializer]
```
