### ISSUE TITLE
Connect to server with guest user doesn't work

### ISSUE THREAD

**Issue by ogubchenko** [orientechnologies/orientdb#7788]
## Expected behavior  
Connecting to remote Server instance [remote:localhost] with user 'guest'...OK

## Actual behavior  
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance

## Steps to reproduce  
To fix: edit the default `orientdb-server-config.xml` file from:
`<user resources="connect,server.listDatabases,server.dblist" password="" name="guest"/>
`

to:
`<user resources="server.connect,server.listDatabases,server.dblist" password="" name="guest"/>`

**Comment by tglman** [comment]
hi @ogubchenko,

This is done on purpose for security reasons, guest is for allow studio to list database on the UI, any other uses may be not corrects.

Regards
