### ISSUE TITLE
Vertex properties sequence is not the same as the order in which has been set

### ISSUE THREAD

**Issue by vaiju12p** [orientechnologies/orientdb#7789]
OrientDB API Version: 2.2.26  
Java Version: 1.8  
OS: centOS7

**Actual behavior**  
I am creating a vertex with the properties: Roll_no, Name, City using OrientDB java API. While creating the vertex I am Setting the setting properties in the order Roll_no, Name, City but at orientDB WebUI vertex properties are getting displayed as City Roll_no, Name.

**Expected behaviour:** 
Properties should be displayed in order as they are set in my case Roll_no, Name, City.

Please write if it is possible by setting something or it is the way orientDB work.

**Comment by luigidellaquila** [comment]
Hi @vaiju12p 

Sorry, it is not currently supported. 

Thanks

Luigi

**Comment by dk21212** [comment]
Hi, I have the same problem. Nothing new about this issue on the OrientDB 3.1.7?

**Comment by luigidellaquila** [comment]
Hi @dk21212 @vaiju12p 

I see this issue was closed (I closed it...?) without a content, my bad.
The problem here is that an OrientDB document (like a JSON or a map) does not guarantee the order of properties, so the behaviour you are seeing is expected

Thanks

Luigi

**Comment by dk21212** [comment]
I see.

Thanks
Danilo
