### ISSUE TITLE
EXISTS and COUNT(*) in WHERE errors

### ISSUE THREAD

**Issue by ParzivalSec** [orientechnologies/orientdb#7790]
## Expected behavior  
I was evaluating OrientDB for our companies use cases and encountered that a simple SQL Query such as 

"SELECT * FROM `Person` WHERE EXISTS (SELECT * FROM `Skills`)"

fails due to an error related to the EXISTS keyword. I have a similar issue with a query such as:

" SELECT name FROM `Person` WHERE (SELECT COUNT(*) FROM `Skills`) > 0"

I cannot find anything related to this in the Doc (which I really have read often now) and would like to get a statement on whether this is possible or not. And if not it would be great to get to know how the devs think we should handle such cases.

**Comment by luigidellaquila** [comment]
Hi @ParzivalSec 

you can use a LET, but it's not very efficient... 

```
SELECT FROM Person
LET $a = (SELECT FROM Skills)
WHERE $a.size() > 0
```

What is your use case? Do you need to traverse a relationship? I mean, are these skills related to a single person?

Probably your Person has a `skills` attributed and you can do something like:

```
SELECT FROM Person WHERE skills.size() > 0
```

or it has `HasSkills` edges and you can do

```
SELECT FROM Person WHERE out("HasSkills").size() > 0
```

Thanks

Luigi

**Comment by ParzivalSec** [comment]
Hey,

first of all thanks for the really fast response! :)
I was not aware of the .size() property the out/in collection have. But I think our use case will not be satisfied by that.
We need a way to check during graph traversal if a person has for example 2 of the 4 needed skills for a task. So I had to do a subquery to get the resultset of skills that are currently approved and check the count of this set against the one of the needed skills per task. Until know I tackled such cases checking whether the result set of the subquery EXISTS or not.

Thanks,
Lukas

**Comment by luigidellaquila** [comment]
Hi @ParzivalSec 

You can enrich the out()/in() operators with square brackets and additional conditions, eg.

```
SELECT FROM Person WHERE out("HasSkills")[name='Teamwork' OR name = 'Java'].size() > 0
```

This should be enough to solve your use case.

I hope it helps

Thanks

Luigi
