### ISSUE TITLE
SQL query CONTAINSVALUE don't working with EMBEDDED MAP

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#7793]
### OS: Ubuntu 16.04
Hi, 
I need to create filter by embedded map values, but something is wrong. 

## Expected behavior  
`SELECT FROM Test WHERE embedded_map CONTAINSVALUE {"name":"key_2", "id":"0"}`
must returns documents which contains embedded_map with given value.

## Actual behavior  
Query `SELECT FROM Test WHERE embedded_map CONTAINSVALUE {"name":"key_2", "id":"0"}`
don't return documents which contains embedded_map with given value.
But if we use query
`SELECT FROM Test WHERE  {"name":"key_2", "id":"0"} IN embedded_map.values()`
all works fine.

## Steps to reproduce  
`CREATE CLASS Test`
`CREATE PROPERTY Test.embedded_map EMBEDDEDMAP`
`CREATE PROPERTY Test.id INTEGER`
`INSERT INTO Test SET id = 0, embedded_map = {"key_2" :  {"name" : "key_2",  "id" : "0"}}`
`INSERT INTO Test SET id = 1, embedded_map = {"key_1" :  {"name" : "key_1", "id" : "1" }}`
`SELECT FROM Test WHERE embedded_map CONTAINSVALUE {"name":"key_2", "id":"0"} `

In last query expected that I get record with id = 0, but result is empty.

Query `SELECT FROM Test WHERE link_map CONTAINSVALUE #18:0` works fine with LINKMAP.

Thank you, 
Vitaliy.

**Comment by luigidellaquila** [comment]
HI @WeaxMe 

Thank you for reporting, I'll check it and let you know

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

I just pushed a fix on 2.2.x, it will be released with 2.2.30

Thanks

Luigi

**Comment by WeaxMe** [comment]
Thank you!
