### ISSUE TITLE
How to add new analysis for lucene?

### ISSUE THREAD

**Issue by gzliudan** [orientechnologies/orientdb#7798]
org.apache.lucene.analysis.cjk is not good for chinese. Many people think IKAnalyzer is much better, and it can support custom dictionary. How can we add new analyzer in OrientDB, if it can support lucene?

**Comment by maggiolo00** [comment]
hi @gzliudan 

is it available for Lucene the `IKAnalyzer` ?

If it's a custom lucene analyzer, you can just drop the jar in `$ORIENTDB_HOME/lib` directory and use it in the index creation

https://orientdb.com/docs/2.2/Full-Text-Index.html

**Comment by gzliudan** [comment]
The original IKAnalyzer only support lucene 4.x. A lot of people modify the source code to support lucene 6.x, such as:
https://github.com/sea-boat/IKAnalyzer-Mirror

**Comment by maggiolo00** [comment]
hi @gzliudan 

in 2.2.x we use lucene `5.x`. We will use lucene `6.x` in 3.0. 

You can try to build it and use it with 2.2.x. It could work

Let me know

Thanks

**Comment by maggiolo00** [comment]
hi @gzliudan 

did you have the chance to try it?

Thanks

**Comment by gzliudan** [comment]
I will try IKAnalyzer next week. This week I'm test orientdb. Could you tell me how to write pom.xml if I use java graph api to access orientdb enterprise version?

**Comment by maggiolo00** [comment]
hi @gzliudan 

is the same as community

```
<dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-graphdb</artifactId>
            <version>${version}</version>
</dependency>
```

**Comment by gzliudan** [comment]
No need to add below?
<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-graphdb</artifactId>
<version>2.2.27</version>
<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-server</artifactId>
<version>2.2.27</version>
<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-client</artifactId>
<version>2.2.27</version>
<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-lucene</artifactId>
<version>2.2.27</version>

**Comment by gzliudan** [comment]
No need to add below?

<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-graphdb</artifactId>
 <version>2.2.27</version>

<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-server</artifactId>
<version>2.2.27</version>

<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-client</artifactId>
<version>2.2.27</version>

<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-lucene</artifactId>
<version>2.2.27</version>

<groupId>com.tinkerpop.gremlin</groupId>
<artifactId>gremlin-java</artifactId>
<version>2.6.0</version>

<groupId>com.tinkerpop.blueprints</groupId>
<artifactId>blueprints-core</artifactId>
<version>2.6.0</version>

**Comment by maggiolo00** [comment]
@gzliudan 
are you using orientdb as embedded or as remote server?

**Comment by maggiolo00** [comment]
or both?

**Comment by gzliudan** [comment]
as remote server

**Comment by maggiolo00** [comment]
@gzliudan 
so this one should be enough 

```
<dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-graphdb</artifactId>
            <version>${version}</version>
</dependency>

```

**Comment by gzliudan** [comment]
thank you very much
