### ISSUE TITLE
query lucene index with special character not working

### ISSUE THREAD

**Issue by raph2129** [orientechnologies/orientdb#7801]
### OS: Windows 7

I have one table _Test_ with one column which contains the value _ABC{DEF}_: 
_| name       |
| ABC{DEF} |_

I create an index on test:
_CREATE INDEX Test.name ON Test(name) FULLTEXT ENGINE LUCENE METADATA {"allowLeadingWildcard": true,"analyzer":"org.apache.lucene.analysis.core.WhitespaceAnalyzer" }_ 

When i run this query:
_SELECT name FROM Test WHERE name LUCENE '*\\\\{*'_
It's ok the result is : _ABC{DEF}_

But when i run this query: 
_SELECT name FROM Test  WHERE name LUCENE '*ABC\\\\{*'_
It return 0 row, but i want the following result : _ABC{DEF}_

Someone can help me please ?

Regards,

Raphael

**Comment by maggiolo00** [comment]
Hi @raph2129 

i this is working for me

```
SELECT name FROM Test WHERE name LUCENE 'ABC\\{'
```

1 result

and this 0 result 

```
SELECT name FROM Test WHERE name LUCENE '\\{'
```

and it should make sense since i think with that analyzer `{` token is skipped

**Comment by raph2129** [comment]
Oups, i forgot the character '*' in my queries.
Queries are:
SELECT name FROM Test WHERE name LUCENE '\*\\\\{\*'
and
SELECT name FROM Test WHERE name LUCENE '\*ABC\\\\{\*'

**Comment by raph2129** [comment]
With WhiteSpaceAnalyzer the token `{` is not skipped because i have result when i search with '\*\\\\{\*'

**Comment by maggiolo00** [comment]
i do not have the results with 

```
SELECT * FROM Test WHERE name LUCENE '*\\{*'
```

**Comment by raph2129** [comment]
Have you enable `"allowLeadingWildcard": true` in your index ?

**Comment by maggiolo00** [comment]
yep

otherwise i would get an exception for using `*` at the beginning

**Comment by maggiolo00** [comment]
@raph2129 
ok let me check

**Comment by raph2129** [comment]
@maggiolo00 
Do you find something ?

**Comment by raph2129** [comment]
@maggiolo00  i'm really blocked because of that, do you have check ?

**Comment by maggiolo00** [comment]
Hi @raph2129 
just checked. The default analyzer is StandardAnalyzer  that applies also the lower case filtering on indexing and this configuration it is also reflected in the query parser by default. In your case
the `WhitespaceAnalyzer` does not apply the LowerCase filtering, so your queries need to be case sensitive. In order to do that you should change the configuration of your index and add

```
"lowercaseExpandedTerms": false 
```
Like this
```
CREATE INDEX Test.name ON Test(name) FULLTEXT ENGINE LUCENE METADATA {"allowLeadingWildcard": true,"default":"org.apache.lucene.analysis.core.WhitespaceAnalyzer","lowercaseExpandedTerms": false }
```

https://orientdb.com/docs/2.2/Full-Text-Index.html#disable-lower-case-on-terms

Thanks

**Comment by raph2129** [comment]
Thank you @maggiolo00, it working with this index just a problem with space, if i have 'ABC {CDE}' and 'CDE ABC' in values and i search '*ABC {CD*', it will return the 2 values 'ABC {CDE}' and 'CDE ABC'.

Or i want just the value 'ABC {CDE}' because i want all values which contains the phrase 'ABC {CD'.

You have an idea about the problem ? I try to escape the space but it doesnt work.

**Comment by raph2129** [comment]
@maggiolo00  
After some tests, it's not ok, because if i search _abc{_ or _ABC{_, it will not return the same result. Or i want the same result if i search _abc{_ or _ABC{._ The configuration `"lowercaseExpandedTerms": false ` disable the case on terms. It's possible when i do this two queries:
`SELECT name FROM Test WHERE name LUCENE 'ABC\\{'`
`SELECT name FROM Test WHERE name LUCENE 'abc\\{'`
to return the same result:
`ABC{DEF}`
??

Thank's for your reply.

Raphael

**Comment by raph2129** [comment]
@maggiolo00 

Do you an idea please ?

**Comment by raph2129** [comment]
@maggiolo00 :( ?

**Comment by maggiolo00** [comment]
Hi @raph2129 

you should find the right analyzer to do that. If it works with lucene it works also in orientdb since
orientdb is a wrapper on that.
I will check on this tomorrow

**Comment by raph2129** [comment]
Hi @maggiolo00 
I try a lot of analyzer but i don't find an analyzer which can do what i want.
I don't know if i need to develop a custom analyzer, but i hope no :)
Thanks for the check, i will wait your answer.

**Comment by raph2129** [comment]
Hi @maggiolo00 

Do you find something ?

**Comment by raph2129** [comment]
Hi @maggiolo00 
Any updates ?

**Comment by raph2129** [comment]
Hi @maggiolo00
Any updates ?

**Comment by raph2129** [comment]
up !

**Comment by harinath-callidus** [comment]
I know this is bit old thread, but is it possible that I can live with any specific analyzer that can support me  "hyphen" character (-)  as part of the text and treat it as normal instead of special meaning?

**Comment by luigidellaquila** [comment]
Hi @harinath-callidus 

The WhitespaceAnalyzer does it, but it also considers other characters (Eg. parentheses) as part of the text. 
If you need an analyzer that acts exactly as the standard analyzer apart from the hyphen, I'm afraid the only solution is to write a custom one

Thanks

Luigi
