### ISSUE TITLE
Question: Can set the execution mode of some classes is synchronous and other is asynchronous?

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7805]
## Expected behavior  
1. I have two servers,one is master, another is replica, I set the execution mode to asynchronous, so 
the insert/update is very fast.
2. Now I have an scenario, if I insert one record(op1), and then update the record(op2). Now the question
is if op1 does not sync to replica, looks like master will lock the record so that op2 have to wait until op1 sync to replica.

As above, I think if I can set some classes is asynchronous and other is synchronous, then it will be more fine.
## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>

**Comment by lvca** [comment]
Yes, you can specify this in the distributed-config.json configuration per cluster. So if a class X has 4 clusters X1, X2, X3 and X4, you have to put this in all the X* cluster configuration.
