### ISSUE TITLE
2 spaces between ALTER and PROPERTY leads to error

### ISSUE THREAD

**Issue by a14n** [orientechnologies/orientdb#7809]
## Expected behavior  
The ALTER command works.

## Actual behavior  
The folowing error occurs:

>com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.ALTER  PROPERTY Person.firstname COLLATE ci

## Steps to reproduce

Execute the following commands:

```
CREATE CLASS Person EXTENDS V
CREATE PROPERTY Person.firstname STRING
ALTER  PROPERTY Person.firstname COLLATE ci  -- note that there are 2 spaces after ALTER
```

**Comment by luigidellaquila** [comment]
Hi @a14n 

I just pushed a fix on 2.2.x branch, it will be released with 2.2.30

Thanks

Luigi
