### ISSUE TITLE
OETL process cannot accept some property keys for edges

### ISSUE THREAD

**Issue by Pierrotws** [orientechnologies/orientdb#7813]
### OS: docker official package  

OETL Process halt without error message when creating edge fields in the transformer phase. Changing the name of the field resolves the problem.

NOT WORKING file:
```json
    "edge" : {
        "class": "Event",
        "joinFieldName": "ip_dst",
        "lookup": "Host.ip",
        "direction": "in",
        "unresolvedLinkAction": "CREATE",
        "edgeFields": {
             "id": "${input.id}",
        }
    }
```

WORKING file:
```json
    "edge" : {
        "class": "Event",
        "joinFieldName": "ip_dst",
        "lookup": "Host.ip",
        "direction": "in",
        "unresolvedLinkAction": "CREATE",
        "edgeFields": {
             "e_id": "${input.id}",
        }
    }
```

**Comment by maggiolo00** [comment]
Hi @Pierrotws 

let me check

**Comment by maggiolo00** [comment]
are you with 2.2.29?

**Comment by maggiolo00** [comment]
@Pierrotws 

probably is related the the reserved key in the TinkerPop 2 Implementation where you cannot have a property with name id if the standard rules are applied.
See here in loader options.
https://orientdb.com/docs/2.2/Loader.html#orientdb-loader

**Comment by maggiolo00** [comment]
Hi @Pierrotws 

did you try to disable the option `standardELementConstraints` ?

**Comment by Pierrotws** [comment]
OK I understand, I will not use id as property.
