### ISSUE TITLE
Insert edge is blocked

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7816]
### OS: Linux

When I insert massive edges, if I insert them in one thread, it works well. But if I insert them in multi threads, the server will be blocked for a long time occasionally. The blocking time is as long as 5 minutes or even more longer. During the blocking time, there are many IO write operations. But I use SSD, so write operation should be finished quickly. If it cause by lock contention, it looks too long. Is there anything wrong?

**Comment by weickdev** [comment]
I find even if I insert them in one thread, it will be blocked occasionally too!

**Comment by laa** [comment]
@weickdev that is caused by the fact that your write cache is full and you do not have enough space to keep WAL on disk or more precisely you hit WAL size limit set in the configuration. New 3.0 version handles this configuration much better but in general pauses almost inevitable during high load at any database. In your current situation, I suggest you increase WAL size limit it will make pauses time rare or even less. For that case, you can use  "storage.wal.maxSize" that is a limit of WAL in megabytes.

**Comment by weickdev** [comment]
@laa if I  run `config set storage.wal.maxSize 40960` in console, does it work immediately？ Or should I set it in configure file and restart the server?

**Comment by weickdev** [comment]
@laa I try to run config set storage.wal.maxSize 512000 in console, but it doesn't work. The server is blocked when wal files are about 4096M, which is the default value of `storage.wal.path`

Then I set the orient-server-config.xml like this:
`
<properties>
        <entry value="1" name="db.pool.min"/>
        <entry value="50" name="db.pool.max"/>
        <entry value="false" name="profiler.enabled"/>
        <entry value="/data/dfs/dn/1/wal" name="storage.wal.path"/>
        <entry value="512000" name="storage.wal.maxSize"/>
    </properties>
`
but when I check the value on console, them aren't changed:
`
orientdb> config get storage.wal.path
Local configuration: storage.wal.path = null

orientdb> config get storage.wal.maxSize
Local configuration: storage.wal.maxSize = 4096
`
but when I run the server, the wal files have been written to /data/dfs/dn/1/wal. And the  'storage.wal.maxSize' works too.

**Comment by laa** [comment]
@weickdev it is a small bug in the console we aware of it, but did not have time to fix it.

**Comment by weickdev** [comment]
@laa When I shutdown the server, there are some file under wal file:
`dev.6138.wal  dev.wmr  OSystem.0.wal  OSystem.wmr`

If I change the wal path, should I copy there files to the new wal path?

**Comment by weickdev** [comment]
Does the `storage.wal.maxSize`  affect the edge inserting speed? After I increase the `storage.wal.maxSize`, the inserting speed slow down 1/3 after running a while.

**Comment by laa** [comment]
It should not. At least I do not see any connection.

**Comment by laa** [comment]
> When I shutdown the server, there are some file under wal file:
dev.6138.wal dev.wmr OSystem.0.wal OSystem.wmr
If I change the wal path, should I copy there files to the new wal path?

Yes, you should copy all WAL files.

**Comment by weickdev** [comment]
@laa Thanks for you replay. I change the `storage.wal.maxSize`, it works much better at beginning. But as the more RAM is consumed, the slower the edge is inserted. I try the 3.0 version, it works much better, the speed doesn't change too much in the entire inserting process. But right now, the 3.0 version is milestone version, so when the GA and RC version will be released? Because the 2.0 version's edge inserting is so slow that I can't use it in my project.

**Comment by laa** [comment]
@weickdev we have the plan to release RC in two months may be earlier.

**Comment by weickdev** [comment]
It's a good news. Is there a stable snapshot I can have a try? 
> we have the plan to release RC in two months may be earlier.

**Comment by laa** [comment]
@weickdev snapshot cannot be stable by definition )) but you can download the latest snapshot from the standard Maven repository. The source code is pretty stable we working on small issues and mostly distributed part.

**Comment by weickdev** [comment]
@laa OK, I am going to have a try. Hope you release 3.0 version as soon as possible :)
