### ISSUE TITLE
 OrientDB astar not working as expected

### ISSUE THREAD

**Issue by agarciaGIT** [orientechnologies/orientdb#7817]
## Expected behavior  
Running astar will return the cheapest path between two vertices 

## Actual behavior  
It returns a path irrelevant of the weight assigned to the edges

## Steps to reproduce  
I have a simple graph where two vertices are connected by two other vertices via 4 edges forming a diamond. V1 <-E1- VA -E2-> V2 and V1 <-E3- VB -E4-> V2. So there are two clear paths between V1 and V2 through E1, VA, E2 OR E3, VB, E4.

I have given all edges the property call 'weight' that is an Integer and assigned E1 & E2 a value of 100 each and E3 & E4 a values of 200 each.

So you would assume the "cheapest" path from V1 to V2 would be via VA (using edge E1 & E2). Yet the command select astar(V1, V2, 'weight', 'BOTH') returns a path via VB! Actually no matter the values or weight on the edges the path is the same.

That makes no sense to me since E1 + E2 = 200 and E3 + E4 = 400.

**Comment by luigidellaquila** [comment]
Hi @agarciaGIT 

Do you have a dataset to reproduce the problem?

Thanks

Luigi

**Comment by agarciaGIT** [comment]
You can close I see what is going on now. I did not take into account direction. So once I used the BOTH option it is working correctly.

Thanks,

AG

**Comment by luigidellaquila** [comment]
Great, closing then.

Thanks

Luigi
