### ISSUE TITLE
JMX profiling not working

### ISSUE THREAD

**Issue by vigneshsenapathy** [orientechnologies/orientdb#7819]
## Expected behavior  
Current/realtime metrics are not rendered 

## Actual behavior  
Current/realtime metrics are not rendered every 60 seconds if thats what you are setting the dump to be at

## Steps to reproduce  
1. start the server by passing in parameters : 
/orientdb/bin/server.sh -Xms2g -Xmx4g -Dorientdb.installCustomFormatter=false -Ddistributed=true -Denvironment.dumpCfgAtStartup=true -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false  -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9998 -Dprofiler.autoDump.reset=true -Dprofiler.autoDump.interval=60 -Dprofiler.enabled=true

2. Once the server started i checked jconsole and i didnt see the values getting updated. Also when i go to http://localhost:2480/profiler/realtime i got the following error : 
{"timestamp":"2017-10-13T14:45:01.366+0000","message":"->172.17.0.1: Command not found: GET.profiler/realtime","source":"com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpDb","source_host":"b2d7dc16bf84","level":"WARNING","line_number":0,"fields":{"class":"com.orientechnologies.common.log.OLogManager","method":"log"},"tags":["orientdb"]}

I get the default values which is like -1 and 1 and i dont get the real/profiled values which i am looking for. 

Please help me out with this as I am trying to get some metrics out of orientdb

I do a dump of the environment in the start. So the config gets displayed twice, one it says true and once it says false. I dont know why it displays more than once

- PROFILER
  + profiler.enabled = false
  + profiler.config = null
  + profiler.autoDump.interval = 60
  + profiler.autoDump.type = full
  + profiler.maxValues = 200
  + profiler.memoryCheckInterval = 120000

- PROFILER
  + profiler.enabled = true
  + profiler.config = null
  + profiler.autoDump.interval = 60
  + profiler.autoDump.type = full
  + profiler.maxValues = 200
  + profiler.memoryCheckInterval = 120000

**Comment by maggiolo00** [comment]
Hi @vigneshsenapathy 

did you have the EE edition? The profiler is active only in EE edition. See here

https://orientdb.com/docs/2.2/Profiler.html

**Comment by vigneshsenapathy** [comment]
@maggiolo00 : i dont have a EE edition. I am using the free edition and i am trying to get JMX information out, but when i try get the information out i have to something called start monitoring in jconsole to actually see the results. Is there anyway i can get the bean information without doing that. I am using JMX trans for pulling information

**Comment by maggiolo00** [comment]
Hi @vigneshsenapathy 

do you refer to `OPerformanceStatisticManagerMBean` ?

**Comment by vigneshsenapathy** [comment]
@maggiolo00 : yes. I have the xml as below:

<jmxtrans-agent>
    <queries>
        
        <query objectName="java.lang:type=OperatingSystem" attribute="SystemLoadAverage" resultAlias="os.systemLoadAverage"/>
        
        <query objectName="java.lang:type=Memory" attribute="HeapMemoryUsage" key="used"
               resultAlias="jvm.heapMemoryUsage.used"/>
        <query objectName="java.lang:type=Memory" attribute="HeapMemoryUsage" key="committed"
               resultAlias="jvm.heapMemoryUsage.committed"/>
        <query objectName="java.lang:type=Memory" attribute="NonHeapMemoryUsage" key="used"
               resultAlias="jvm.nonHeapMemoryUsage.used"/>
        <query objectName="java.lang:type=Memory" attribute="NonHeapMemoryUsage" key="committed"
               resultAlias="jvm.nonHeapMemoryUsage.committed"/>
        <query objectName="java.lang:type=ClassLoading" attribute="LoadedClassCount" resultAlias="jvm.loadedClasses"/>

        <query objectName="java.lang:type=Threading" attribute="ThreadCount" resultAlias="jvm.thread"/>
        
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="cacheHits"
        resultAlias="orientdb_cacheHits,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="commitTime"
        resultAlias="orientdb_commitTime,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="exclusiveWriteCacheSize"
        resultAlias="orientdb_exclusiveWriteCacheSize,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="fullCheckpointCount"
        resultAlias="orientdb_fullCheckpointCount,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="readCacheSize"
        resultAlias="orientdb_readCacheSize,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="readSpeedFromFile"
        resultAlias="orientdb_readSpeedFromFile,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="walCacheOverflowCount"
        resultAlias="orientdb_walCacheOverflowCount,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="walEndAOLogTime"
        resultAlias="orientdb_walEndAOLogTime,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="walFlushTime"
        resultAlias="orientdb_walFlushTime,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="walLogTime"
        resultAlias="orientdb_walLogTime,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="walSize"
        resultAlias="orientdb_walSize,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="walStartAOLogTime"
        resultAlias="orientdb_walStartAOLogTime,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="writeCacheFlushOperationTime"
        resultAlias="orientdb_writeCacheFlushOperationTime,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="writeCacheFuzzyCheckpointTime"
        resultAlias="orientdb_writeCacheFuzzyCheckpointTime,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="writeCacheOverflowCount"
        resultAlias="orientdb_writeCacheOverflowCount,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="writeCachePagesPerFlush"
        resultAlias="orientdb_writeCachePagesPerFlush,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="writeCacheSize"
        resultAlias="orientdb_writeCacheSize,dbname=%name%" />
        <query objectName="com.orientechnologies.orient.core.storage.impl.local.statistic:type=OPerformanceStatisticManagerMXBean,name=*,id=*"
        attributes="writeSpeedInCache"
        resultAlias="orientdb_writeSpeedInCache,dbname=%name%" />
    </queries>
    <outputWriter class="org.jmxtrans.agent.influxdb.InfluxDbOutputWriter">
        <url>http://testing:8080</url>
        <database>techops</database>
        <user>testnng</user>
        <password>testing</password>
     </outputWriter>
    <collectIntervalInSeconds>20</collectIntervalInSeconds>
</jmxtrans-agent>

**Comment by vigneshsenapathy** [comment]
@maggiolo00 : is it OPerformanceStatisticManagerMBean or OPerformanceStatisticManagerMXBean
