### ISSUE TITLE
System class OSchedule missing

### ISSUE THREAD

**Issue by jhagelback** [orientechnologies/orientdb#7822]
## Expected behavior  
Our database was first created in ODB 1.2, later imported into ODB 1.5.1
We have recently done a major upgrade where the database was exported from ODB 1.5.1 and imported in 2.2.27. 

We have managed to fix all issues, except that the OSchedule system class/cluster is missing (it was deleted in the import, and the exported file did not contain the cluster).

Is it possible to create a new OSchedule cluster/class in our database?

**Comment by maggiolo00** [comment]
Hi @jhagelback 

do you need the class `OSchedule` ?

**Comment by jhagelback** [comment]
Well, the database works without it but we can't add scheduled events to the database.

**Comment by maggiolo00** [comment]
Hi @jhagelback 

you can recreate the `OSchedule` class with this

```
create class OSchedule
create property OSchedule.name STRING 
alter property OSchedule.name mandatory TRUE
alter property OSchedule.name notnull TRUE
create property OSchedule.rule STRING 
alter property OSchedule.rule mandatory TRUE
alter property OSchedule.rule notnull TRUE
create property OSchedule.arguments EMBEDDEDMAP
create property OSchedule.status STRING 
create property OSchedule.function LINK OFunction 
alter property OSchedule.function mandatory TRUE
alter property OSchedule.function notnull TRUE
create property OSchedule.starttime DATETIME 
```

**Comment by jhagelback** [comment]
Thanks for the help. Managed to re-create it.
