### ISSUE TITLE
INSERT FROM 'class' (SELECT ...)

### ISSUE THREAD

**Issue by vsspt** [orientechnologies/orientdb#7824]
### Java Version: 1.8 

According to OrientDB manual, its possible to copy records from another class:

    insert into GermanyClient from ( select from Client where country = 'Germany' )

I'm trying to do this, but using aggregated fields in the select clause:

    INSERT INTO TABLE_TEST_PER_DAY FROM ( select DAY, COUNT(*) as NUMBER_OF_FILES FROM TABLE_TEST GROUP BY DAY )

Unfortunately, it seems this is not possible: 

    com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.(INSERT INTO TABLE_TEST_PER_DAY FROM ( select DAY, COUNT(*) as NUMBER_OF_FILES FROM TABLE_TEST GROUP BY DAY )) DB name="testDB"

Can you please confirm if this is possible on OrientDB SQL?

**Comment by vsspt** [comment]
On issue #[2288](https://github.com/orientechnologies/orientdb/issues/2288): SQL Insert into select, the proposed syntax is:

`insert into GermanyClient from select from Client where country = 'Germany'`

I've tested without the parenthesis, and it worked.

**Comment by luigidellaquila** [comment]
Hi @vsspt 

Exactly, the right syntax is without parenthesis. 
I just checked it on 2.2.29 and it works fine, I also double-checked the docs and they are correct as well (http://orientdb.com/docs/2.2.x/SQL-Insert.html) 

I think I can close this issue, please feel free to re-open if I missed something

Thanks

Luigi

**Comment by vsspt** [comment]
Luigi,

correct,the documentation on 2.2.X is correct.

My mistake was that i incorrectly consulted the 2.0 version, that hat the syntax with the parenthesis: http://orientdb.com/docs/2.0/orientdb.wiki/SQL-Insert.html
