### ISSUE TITLE
console query - does not recognize a property of a class

### ISSUE THREAD

**Issue by blogmaniak** [orientechnologies/orientdb#7830]
DATABASE PROPERTIES
+----+-----------------+-------------------+
|#   |NAME             |VALUE              |
+----+-----------------+-------------------+
|0   |Version          |18                 |
|1   |Conflict-Strategy|version            |
|2   |Date-Format      |yyyy-MM-dd         |
|3   |Datetime-Format  |yyyy-MM-dd HH:mm:ss|
|4   |Timezone         |America/Toronto    |
|5   |Locale-Country   |CA                 |
|6   |Locale-Language  |en                 |
|7   |Charset          |UTF-8              |
|8   |Schema-RID       |#0:1               |
|9   |Index-Manager-RID|#0:2               |
|10  |Dictionary-RID   |                   |
+----+-----------------+-------------------+

DATABASE CUSTOM PROPERTIES:
+----+-------------------------------+-----+
|#   |NAME                           |VALUE|
+----+-------------------------------+-----+
|0   |strictSql                      |true |
|1   |txRequiredForSQLGraphOperations|false|
|2   |validation                     |false|
+----+-------------------------------+-----+

## Expected behavior  
Expect to see the details of the company_name field which was imported using the csv file + json

## Actual behavior  
orientdb {db=EMSV2}> info property company.id          

PROPERTY 'company.id'

Type.................: STRING
Mandatory............: false
Not null.............: false
Read only............: false
Default value........: null
Minimum value........: null
Maximum value........: null
REGEXP...............: null
Collate..............: {ODefaultCollate : name = default}
Linked class.........: null
Linked type..........: null

INDEXES (1 altogether)
+----+----------+----------+
|#   |NAME      |PROPERTIES|
+----+----------+----------+
|0   |company.id|[id]      |
+----+----------+----------+
orientdb {db=EMSV2}> info property company.company_name

! Property 'company_name' does not exist in class 'company'

## Steps to reproduce  
CSV File:
id,company_name
08598837342672288235,Rolfson-Tillman
78498491688223221105,Zieme-Schimmel
97085486281119306031,Zulauf-Hessel
99128308905365686017,Mraz
41861150143522449808,OHara_Nitzsche
JSON File:
```
{
 "source": {
   "file": {
     "path": "/home/bhan/src/orientdb/datasets/company.csv"
   }
 },
 "extractor": {
   "csv": {}
 },
 "transformers": [
   {
     "vertex": {
       "class": "company"
     }
   }
 ],
 "loader": {
   "orientdb": {
     "dbURL": "plocal:/home/bhan/src/orientdb/databases/EMSV2",
     "dbType": "graph",
     "classes": [
       {
         "name": "company",
         "extends": "V"
       }
     ],
     "indexes": [
       {
         "class": "company",
         "fields": [
           "id:string"
         ],
         "type": "UNIQUE"
       }
     ]
   }
 }
}
```

**Comment by maggiolo00** [comment]
Hi @blogmaniak 

you should add the field in ETL configuration. Otherwise `company_name` will be a schemaless property and it's not in the schema. That's why you get `! Property 'company_name' does not exist in class 'company'`
 

```
"fields": [
           "id:string",
           "company_name:string" 
         ],
```


Thanks

**Comment by blogmaniak** [comment]
Excellent works
