### ISSUE TITLE
Importing Edges on the same class

### ISSUE THREAD

**Issue by blogmaniak** [orientechnologies/orientdb#7831]
### OS: <os here>  
As part of importing data using csv files, I am trying to create a parent-child relationship between two companies. Company is a class with multiple companies. 
## Expected behavior  
Create edge between two companies in company class.

## Actual behavior  
Forces me to create another vertex, which has the child/parent key values, which beats the purpose of creating an edge.

## Steps to reproduce  
[files.zip](https://github.com/orientechnologies/orientdb/files/1397164/files.zip)

**Comment by maggiolo00** [comment]
Hi @blogmaniak 

unfortunately this is not supported yet. I will mark this as enhancement for the next releases.

Thanks
