### ISSUE TITLE
cannot add edge records via GUI

### ISSUE THREAD

**Issue by blogmaniak** [orientechnologies/orientdb#7832]
### OS: ubuntu 14.04
![image](https://user-images.githubusercontent.com/4483580/31755083-35553ccc-b46a-11e7-8acd-80fdef969429.png)

## Expected behavior  
Should be able to add new edge records, as per available option on GUI.

## Actual behavior  
No way to add From Vertex - To Vertex (as per screenshot)

## Steps to reproduce  
select  new record option for a given edge on schema view

**Comment by maggiolo00** [comment]
Hi @blogmaniak 
Thanks for reporting this. It's a known issue. I will mark this as duplicate

https://github.com/orientechnologies/orientdb-studio/issues/439
