### ISSUE TITLE
running sql in console throws Error

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7833]
### OS: CentOS

When I run `truncate class xxx unsafe` in console, it always throws error:
`Truncated
Error: java.util.IllegalFormatConversionException: d != java.util.ArrayList`

After that, If I run other `select` command, it throws error:
`Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot close query: 1508409995119_32
	DB name="dev"
	DB name="dev"
`

**Comment by luigidellaquila** [comment]
hi @weickdev 

I just pushed a fix for this

Thanks

Luigi

**Comment by clouds56** [comment]
also for `CREATE CLUSTER schemaless ID 999;`
shows
```
Cluster created correctly with id #
Error: java.util.IllegalFormatConversionException: d != java.util.ArrayList
```
