### ISSUE TITLE
too many read block 

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7834]
### OS: CentOS 

When I insert datas, I find there are many IO read blocks, but there isn't any read and write data. 
<img width="1148" alt="3 0_read_block" src="https://user-images.githubusercontent.com/31640567/31798319-8674ecc2-b4f8-11e7-887c-8706d70fb210.png">
So why this happen, and how can I avoid it?

**Comment by weickdev** [comment]
@laa Is there any feedback about this issue?

**Comment by laa** [comment]
@weickdev right now we are busy by more critical issues once I have time I will look on this.
