### ISSUE TITLE
traverse error?

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7835]
### OS: CentOS

One of my data has two out edge as below:
<img width="916" alt="select_result" src="https://user-images.githubusercontent.com/31640567/31804442-07771b12-b51f-11e7-8fe0-e18ef722e444.png">

But if I traverse starting from it, I get below graph:
<img width="911" alt="graph_result" src="https://user-images.githubusercontent.com/31640567/31804453-14d331ce-b51f-11e7-827c-a1301e8f1faf.png">

As my understanding, it should look like below:
`#157:645786<-invest-#186:57556-invest->#141:350412`

**Comment by luigidellaquila** [comment]
Hi @weickdev 

I just tried it with latest snapshot and it seems to work fine, could you please a sample SQL script to reproduce the problem?

Thanks

Luigi

**Comment by weickdev** [comment]
Do you mean you need the sql I run? It is as below:
`traverse * from #xxxx:xxxx maxdepth 1`, but all the datas are 100+GB. By the way, I package the zip on develop brach, is this matter?

**Comment by luigidellaquila** [comment]
What I need is a small dataset to reproduce the problem, if you could isolate a small portion (or create a new one that has this problem) it would be awesome

Thanks

Luigi

**Comment by weickdev** [comment]
I try to create a new small dataset, but the small dataset works well. I can't make sure which part of datas cause this issue.

**Comment by weickdev** [comment]
I try this on V2.2.28, it has same issue!

**Comment by weickdev** [comment]
Hi @luigidellaquila Is there any feedback about this issue? Or anything I can do?

**Comment by luigidellaquila** [comment]
Hi @weickdev 

It's really hard for me to understand where the problem is, with my datasets this does not happen and you say it doesn't happen with your sample dataset either, so it seems the problem is in the original dataset... 

Could you please post the result of the following query:


```
SELECT FROM [#157:645786, #186:57556, #141:350412]
```

maybe we will find something there

Thanks

Luigi

**Comment by weickdev** [comment]
Hi @luigidellaquila 

The select result seems ok:
```
+----+---------+-------+----+--------+--------+---------+---------+---------+---------+---------+---------+---------+---------+--------------+------------------+-------------------------------------+
|#   |@RID     |@CLASS |city|province|industry|capital  |entity_ty|name     |business_|enterpris|utime    |ctime    |operation|_key          |in_invest         |out_invest                           |
+----+---------+-------+----+--------+--------+---------+---------+---------+---------+---------+---------+---------+---------+--------------+------------------+-------------------------------------+
|0   |#157:6...|Company|北京  |北京      |商务服务业   |100000...|Company  |xxxxxx...|存续（在营、...|其他有限责任公司 |2017-0...|2017-0...|1999-0...|793BD62EDC6...|[#219:289714,#2...|[#245:171381,#216:225630,#237:1714...|
|1   |#186:5...|Person |    |        |        |         |Person   |xxxxxx      |         |         |2017-0...|2017-0...|         |042151FAC7D...|                  |[#219:289714,#229:289804]            |
|2   |#141:3...|Company|广西桂林|广西      |有色金属矿采选业|100000...|Company  |xxxxxx...|存续（在营、...|有限责任公司...|2017-0...|2017-0...|2015-0...|41C7B74F4C7...|[#245:289784,#2...|                                     |
+----+---------+-------+----+--------+--------+---------+---------+---------+---------+---------+---------+---------+---------+--------------+------------------+-------------------------------------+
```
`xxxxxx``` is the name of the Company/Person.

**Comment by luigidellaquila** [comment]
Hi @weickdev 

From this result I cannot see if the edge (#186:57556) is contained in the out_/in_invest fields of both vertices. Could you please check it?

Thanks

Luigi

**Comment by weickdev** [comment]
I can't check it, it throws timeout error as below:
```
orientdb {db=dev}> select bothE('invest') from #157:645786

Error: com.orientechnologies.common.io.OIOException: Read timed out

Error: java.net.SocketTimeoutException: Read timed out
```

**Comment by weickdev** [comment]
@luigidellaquila 
I try the web studio again, it works well. As you guess, there is some mistake:

<img width="1257" alt="miss_vertex" src="https://user-images.githubusercontent.com/31640567/32085345-025c740e-ba94-11e7-808c-4f649cb3f3c1.png">

**Comment by luigidellaquila** [comment]
yes, I'd say your graph is "broken".
You can easily repair it with

```UPDATE #141:350412 ADD out_<TheEdgeClassName> = #186:57557```

just make sure to spell `out_TheEdgeClassName` in the right case.

This could have happened for many reasons, a good candidate is a bug we fixed in latest stable release

Thanks

Luigi

**Comment by weickdev** [comment]
@luigidellaquila I close the transaction when I insert edges, does this may cause this issue?

**Comment by luigidellaquila** [comment]
I doubt, connection close just does a commit if you are running in a transaction, otherwise it just closes.
BTW, are you running in a tx? How are you inserting data?

Thanks

Luigi

**Comment by weickdev** [comment]
@luigidellaquila 
No, I am running without tx, I insert data by 'OrientGraphNoTx', and set the OIntentMassiveInsert.

**Comment by luigidellaquila** [comment]
Uhm... ok, as I wrote before, we fixed a bug about this in 2.2.29, I'd say that can be the reason for this problem. 

In general, I suggest you to use transactional connections when manipulating graphs, they have better performance and are more consistent

Thanks

Luigi

**Comment by weickdev** [comment]
@luigidellaquila 
Because I have massive edges to insert, but the insert speed is too slow. I find some blogs said without tx and setting the  `OIntentMassiveInsert` will be faster. So I remve the tx. Do you have some advice about inserting massive edges?

BTW, will you fix this issue in 3.x?

**Comment by luigidellaquila** [comment]
Hi @weickdev 

The best advice I can give you for a massive insert is to work in embedded mode (ie. plocal). The massive insert intent does not give much advantage with graph import, as the big part of the elaboration is vertex lookup and save. 

The issue should be already fixed.

Thanks

Luigi

**Comment by weickdev** [comment]
Hi @luigidellaquila 

Right now, I am using plocal storage, connecting the database by DB address `remote:localhost/mydb`. So the client and the db server are on the same server. As you said, should I change the DB address to `plocal:xxxxx`?

**Comment by luigidellaquila** [comment]
If it's a one-shot batch import, then yes, using plocal:xxx will give you a big advantage.
Just consider that you cannot run both a plocal process and a server at the same time, so you have to stop the server, run the import and then restart it

Thanks

Luigi

**Comment by weickdev** [comment]
@luigidellaquila Thanks for you advice, I will try it!
