### ISSUE TITLE
Something wrong with delete from huge tables

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7839]
### OS: linux 

There is a table with huge amount of records. Need to delete some row by simple criteria. And there are no external processes which are working with the table on a moment of deletion

## Expected behavior  
All required rows should be deleted at once.

## Actual behavior  
Several runs of query required to accomplish deletion.

![image](https://user-images.githubusercontent.com/1199285/31853037-05ee5b48-b637-11e7-81b5-acacca3fdf88.png)

Any ideas of what's going on?

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

No idea, I'll check it ASAP

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I don't seem to be able to reproduce the problem, I think I need a couple more info:

- do you have a particular schema (Eg. indexes or other constraints) on that class?
- how long does the delete operation take? (could it be a matter of timeout?)
- are you working with Java embedded, remote, HTTP/REST or other?
- does the dataset have anything particular in terms of structure?

Thanks

Luigi

**Comment by PhantomYdn** [comment]
Hello, @luigidellaquila 

- Yes - there are indexes. But no error messages that something wrong with indexes during commit or db restart. 
- It's taking a while. At least 1 minute. But no messages/exceptions about that.
- I'm working through Java embedded + all calls are within transaction.
- No specific things.

Schemas:
![image](https://user-images.githubusercontent.com/1199285/31904073-0b62413a-b7df-11e7-9b96-e375713d758f.png)

![image](https://user-images.githubusercontent.com/1199285/31904216-7c8ade1c-b7df-11e7-8ac9-d75105aeab8b.png)
