### ISSUE TITLE
After removal of default cluster in OrientDB binary compatibility tests start to fail

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7840]
After removal of default cluster in OrientDB binary compatibility tests start to fail

**Comment by luigidellaquila** [comment]
Thank you @laa I'll check it ASAP. Actually the default cluster was not removed, I just inhibited OrientDB from saving records there implicitly (you can still explicitly save records in the default cluster). 

With this change, I also added a default blob cluster (blob clusters were implemented, but we forgot to create a specific default cluster for blobs, so blobs ended up in the "general" default cluster...), this could be a reason for test failures

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, i just pushed a fix, let's see the tests running

Luigi
