### ISSUE TITLE
error on starting distributed plugin java.lang.NullPointerException

### ISSUE THREAD

**Issue by madanmohan25** [orientechnologies/orientdb#7843]
## Expected behavior  
<replication>  

## Actual behavior  
<error on starting distributed plugin>  

## Steps to reproduce  
<add here>  

![capture](https://user-images.githubusercontent.com/6748647/31887175-f36ee6a6-b814-11e7-8e05-bd5c1b3f9db3.JPG)

**Comment by luigidellaquila** [comment]
Hi @madanmohan25 

OrientDB v 2.2.21 is quite old (latest stable is 2.2.29) could you please try to upgrade and check if the problem still exists?

Thanks

Luigi

**Comment by madanmohan25** [comment]
Hi @luigidellaquila 
I tried using the latest version v 2.2.29 still i face the same issue not sure why it occurs
![image](https://user-images.githubusercontent.com/6748647/31983309-5c32a3ec-b97a-11e7-96b5-9f99e5c5cbe9.png)

**Comment by lvca** [comment]
What's your distributed-config.xml file?

**Comment by eduardnegru** [comment]
The issue is still present in orientdb 3-0-23. I'm using default-distributed-db-config.json.
