### ISSUE TITLE
Lucene indexes become corrupted after some use (memory database)

### ISSUE THREAD

**Issue by aemitos** [orientechnologies/orientdb#7844]
## Expected behavior  
The indexes must persist.

## Actual behavior  
No response for queries using lucene indexes

## Steps to reproduce  
1 - Create a memory database;
2 - Insert 400k objects with a string property
3 - Create a lucene index for the string property
4 - After some use, the queries will not return any result using the lucene index.

I've solved the issue downgrading the system to OrientDB Server v2.2.22 that works fine for the issue described above.

**Comment by aemitos** [comment]
Nothing, it's just stopped to return results in the queries using lucene indexes.

**Comment by maggiolo00** [comment]
ok @aemitos 

let me check

**Comment by maggiolo00** [comment]
Hi @aemitos 

i've pushed a fix in 2.2.x branch. It will be available in the next version 2.2.30

Thanks
