### ISSUE TITLE
Error "You have reached maximum pool size for given partition" during databasePool.aquire()

### ISSUE THREAD

**Issue by EricSchreiner** [orientechnologies/orientdb#7845]
## Expected behavior  
<No Error>  

## Actual behavior  
<Unexpected Error>  

## Steps to reproduce  
<see description below>  

Hi @laa 

it's me again. After we are in production we receive more and more problem reports from our users which we cannot reproduce. We get the following error which should have been solved already a long time ago:

EXCEP@     at java.lang.Thread.run(Thread.java:745)
**EXCEP@ Caused by: java.lang.IllegalStateException: You have reached maximum pool size for given partition
EXCEP@     at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:244)**
EXCEP@     at de.contecon.picapport.db.PicApportDBService.getPooledDbInstance(Unknown Source)
EXCEP@     at de.contecon.picapport.db.PicApportDBService.getDbWrapper(Unknown Source)
EXCEP@     at de.contecon.picapport.server.servlet.PicApportJsonServlet.doCmdgetImageInfo(Unknown Source)

We us the **_"default"_** values for this.oPartitionedDatabasePool = new **_OPartitionedDatabasePool(dbName, USER_DEFAULT, PASSWORD_DEFAULT);_**
Which is recommended by your documentation.

The CPU used by our customer has 2 processors
Any recommendations from your side what we should do? It did not happen in 2.1.x. So far I cannot reproduce it here. Our Machines all have more than 2 processors

Her is more info about the environment:

VER  @ 19:23:45.993 PicApport Version 7.0 from 19.10.2017 loaded.
VER  @ 19:23:45.996 de.contecon.picapport.PicApport.Version=V7.0.3 19.10.2017
VER  @ 19:23:45.999 java.runtime.version: 1.8.0_102-b14
VER  @ 19:23:46.000 java.version: 1.8.0_102
VER  @ 19:23:46.000 java.vm.version: 25.102-b14
VER  @ 19:23:46.001 java.vm.vendor: Oracle Corporation
VER  @ 19:23:46.004 java.vm.name: Java HotSpot(TM) 64-Bit Server VM
VER  @ 19:23:46.004 java.specification.version: 1.8
VER  @ 19:23:46.004 java.vm.specification.version: 1.8
VER  @ 19:23:46.007 os.name: Linux
VER  @ 19:23:46.008 os.version: 4.4.0-97-generic
VER  @ 19:23:46.011 os.arch: amd64
MSG  @ 19:23:46.011 java.runtime totalMemory=2058mb maxMemory=2058mb freeMemory=2004mb processors=2
MSG  @ 19:23:46.028 java.runtime.argument: -Xms2048m
MSG  @ 19:23:46.029 java.runtime.argument: -Xmx2048m
MSG  @ 19:23:46.030 java.runtime.argument: -XX:MaxDirectMemorySize=2g

**Comment by laa** [comment]
@EricSchreiner most likely you have a leak in your usage of connections to the database. Could you check that if you acquire database instance, you always close it? Could you also create memory snapshot after you have encountered this exception and count amount of connections which you have at the moment? For that, you should count the amount of instance of `DatabaseDocumentTxPooled`  class.

**Comment by EricSchreiner** [comment]
Hi @laa,
thank you that's a starting point. I'll check

**Comment by EricSchreiner** [comment]
Hi @laa,
you where right. In rare circumstances we had a thread accessing the pool.aquire() and then reading a queue with blocking take()...... It seems that the problem did only occur on machines with 2 or less cpu cores.....

**Comment by laa** [comment]
Cool, soon we are going to remove any need for use of MaxDirectBuffer parameter at all. I suppose you will like that.

**Comment by EricSchreiner** [comment]
:-)

**Comment by cuongrep** [comment]
Excuse me! I have no idea if we have any advice about relationship **maxPartitionSize/maxPoolSize**.
> For example: 5/20 = 1/4

Many thank
