### ISSUE TITLE
Which version will I consider as Stable version  in 2.2.x ?

### ISSUE THREAD

**Issue by frostarun** [orientechnologies/orientdb#7846]
### OS: windows 2012 R2 

Which version from these releases should I consider as stable release from [here](https://github.com/orientechnologies/orientdb/wiki/OrientDB-2.2-Release-Notes#2229---october-5-2017) ?

**Comment by luigidellaquila** [comment]
Hi @frostarun 

The stable version is the first one listed in that page (excluding the DRAFT), so now it's 2.2.29

You can always find latest stable in the downloads page: http://www.orientdb.com/download
Thanks

Luigi

**Comment by frostarun** [comment]
Thanks a lot.
