### ISSUE TITLE
[Question]How to get related vertex as nested document?

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#7847]
### OS: centos

I hava a graph like this

a1 --[classmate]--> b1
a1 --[girlfriend]-- b1
a1 --[relation]--> b2
a1 --[relation]--> b2

I execute sql like this
```
SELECT *, out('classmate') as `classmate`, out('girlfriend') as `girlfriend`, out('relation') as `relation` from A fetchplan in_*:-2 out_*:-2 *:1
```
I expect get json like this
```
{
    "name": "a1",
    "classmate": [
        { "name": "b1" }
    ],
    "girlfriend": [
        { "name": "b1" }
    ]
}
```

But I get json like this
```
{
    "name": "a1",
    "classmate": [
        { "name": "b1" }
    ],
    "girlfriend": [
        "#11:22"
    ],
    "relation": [
        { "name" : "b2" },
        "#22:33"
    ]
}
```

Is there any way to  get the data struct I want?
Thank you.

**Comment by luigidellaquila** [comment]
Try to add the following to the fetchPlan

```girlfriend:1 relation:1```

Thanks

Luigi

**Comment by lightjiao** [comment]
Hi @luigidellaquila 
my fetchPlan was `in_*:-2 out_*:-2 *:1`
And I add `girlfriend:1 relation:1` to my fetchplan, It dosen't work

**Comment by lightjiao** [comment]
Hi @luigidellaquila 
This is a very serious problem for me, could you give me any suggestion ?
Thanks

**Comment by luigidellaquila** [comment]
Hi @lightjiao

Maybe I got it wrong and the correct one is `girlfriend:2 relation:2`

Could you please try?

Thanks

Luigi

**Comment by lightjiao** [comment]
@luigidellaquila Sorry, it doesn't work for me.
My fetchplan was `in_*:-2 out_*:-2 *:1 `girlfriend`:2 `relation`:2`.

I have two situation:
1:  I only need some fields of the related data, I use `out('relation').include('name')`
2: I need full related data, I fill the `rid` with foreach in memory  to solve my problem


Any other good way to get full related data? like
`select out('friend').include(all fields) as friend from v_Person`
