### ISSUE TITLE
Partial Match Query on Composite Index Fails

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientdb#7850]
## Expected behavior  
SELECT FROM INDEX:CompIndex WHERE key = ['XYZ'] should use the two-property composite index "CompIndex" to find all records where the first property is 'XYZ'.

## Actual behavior  
Exception: java.lang.UnsupportedOperationException: iterateEntriesBetween
Note that SELECT FROM INDEX:CompIndex WHERE key = ['XYZ', 'PDQ'] works fine.

## Steps to reproduce  
Create a composite index on any two (or more props), then run the SELECT as shown

PS - If I do a regular (i.e. non-INDEX:) SELECT with all props that make up a composite index included in the WHERE clause, the EXPLAIN output shows that the index is being used, but if I only include the first (or first few) props in the index, the EXPLAIN output does not reference any index. I was under the impression that a composite index would be "partially used" as long as the props referenced were the first (or first few) props in the index. Is that incorrect?

**Comment by luigidellaquila** [comment]
Hi @Eric24

What kind of index are you using? If that's a hash index, then that behavior is normal, you cannot do partial match on a hash index. 

Thanks

Luigi

**Comment by Eric24** [comment]
Yes, a hash index. Makes sense (I wasn't sure of each part of a compound key was hashed separately, but it sounds like the entire key is hashed all at once).
