### ISSUE TITLE
main.js error studio

### ISSUE THREAD

**Issue by marcoaleixo** [orientechnologies/orientdb#7851]
### Java Version: 
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

## Expected behavior  
Load studio site.

## Actual behavior  
![error](https://user-images.githubusercontent.com/19698739/32071704-d2714988-ba6e-11e7-8fb4-a435056afccd.png)

`Error on loading resource /studio/main.js` on console.

I'm using Chrome, but I have already tested Firefox and I can not test IE.

**Comment by maggiolo00** [comment]
Hi @marcoaleixo 

which version of Chrome?

**Comment by maggiolo00** [comment]
Is it happen with OrientDB 2.2.29?

**Comment by marcoaleixo** [comment]
Yes, 2.2.26
my chrome version is 62.0.3202.62

**Comment by marcoaleixo** [comment]
Well, I re downloaded Orientdb and everything is ok now.

**Comment by maggiolo00** [comment]
OK @marcoaleixo 

i'm closing this. Reopen if it happens again
Thanks
