### ISSUE TITLE
 pool.acquire lock  when concurrent

### ISSUE THREAD

**Issue by gflp123** [orientechnologies/orientdb#7852]
## Expected behavior  
OrientGraphFactory graphFactory = new OrientGraphFactory(url, userName, password).setLabelAsClassName(true).setupPool(20,50)

OrientGraph orientGraph=graphFactory .getNoTx();

orientGraph.executeSql(script)
## Actual behavior  
get graph from connection poop locker
## Steps to reproduce  
Using Jmeter if we run a load test to send more than 2000 requests then this can be reproduced.

**Comment by maggiolo00** [comment]
Hi @gflp123 

do you call the api `graph.close` when finished?

**Comment by gflp123** [comment]
call api graph.close solve it,
but
  GraphTraversal<Vertex, Vertex> accountTraversal = iRepository4OrientDB.getVertexsWrapper(GroupUserLabel.USER_LABEL).has("Id", userId)
                .outE(LoginLabel.EDGE_HAS_ACCOUNT)

gremlin lazy object is not used,
any suggest.
thanks

**Comment by maggiolo00** [comment]
Hi @gflp123 

what do you mean by `gremlin lazy object is not used` ?

Thanks

**Comment by gflp123** [comment]
Function across several layers, including multiple nodes and relationships, when to call graph.close, ,When all functions are not completed, call graph.close
,GraphTraversal<Vertex, Vertex> or Vertex not used.

how to use.
