### ISSUE TITLE
Serious issue: Duplicated column value where has the unique index

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7853]
## Expected behavior  
Can't insert the duplicate value in unique index

## Actual behavior  
The db has the duplicate column value where has the unique index

## Steps to reproduce  
I don't know why the duplicated column values are inserted, but it's true that it exits.

**Comment by laa** [comment]
Ho @KishoDai , you are right that is serious. But I have to ask  you several questions:

1.  Do you use distributed, embedded or single server database?
2.  Did you perform a backup - restore the database ?
3.  Did you perform the shutdown of a database during database load?
3. Do you use Java or third-party drivers?

**Comment by KishoDai** [comment]
Hi @laa 
   Thank you for your replay.
   1. It's distributed.
   2. Yes, did it before.
   3. Did not.
    4. Do not.

**Comment by laa** [comment]
Hi @KishoDai , thank you for such early response. Next question, do you work in transactional or noTx mode?

**Comment by KishoDai** [comment]
Hi @laa 
    In transaction mode. I use SQL batch with transaction.

**Comment by laa** [comment]
seems like an issue in distributed, assigned to @tglman

**Comment by KishoDai** [comment]
@laa @tglman 
     Any updates?

**Comment by tglman** [comment]
Hi @KishoDai,

We did a few fix in distributed recently that should solve also this problem, did you have chance to try some more recent hotfix ?

Regards
