### ISSUE TITLE
ODistributedRecordLockedException when saving multiple edges between 2 vertexes in a distributed environement

### ISSUE THREAD

**Issue by decebal** [orientechnologies/orientdb#7856]
## Expected behavior  
Store Vertex and Edges

## Actual behavior  
com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException - Timeout (597ms) on acquiring lock on record

## Steps to reproduce  
Easier to do:
- store 2 vertexes
- add an edge between them
- add a second edge between them of a different type
 
While wondering about for a week around ways to diagnose this, finally decided to downgrade to 2.2.28 and the problem was solved, I can continue to store my stuff in a distributed environment,

In my investigation, the closest issue was https://github.com/orientechnologies/orientdb/issues/5012 , but it's mentioned that the issue there was solved in 2.2.21.

Not an educated opinion, but I think https://github.com/orientechnologies/orientdb/commit/07c48dc9a9a74b227d7dbd98d280503d320e4067 to be the cause of this.

**Comment by tglman** [comment]
hi @decebal,

Can you try the 2.2.30, this problem should be fixed.

Regards
