### ISSUE TITLE
Max Cache limit Reached

### ISSUE THREAD

**Issue by rbaarathinms** [orientechnologies/orientdb#7859]
Hi,
    Max cache limit is reached (3000 vs. 3001), sync flush is performed.
    Our orient version is 2.2.20.
    Java version -- 8

Can you tell me what is the root cause for this warning..???

**Comment by laa** [comment]
It means that we can not keep all operations are logged in operation journal in memory and data will be flushed to disk. I will provide a more meaningful text of message soon.

**Comment by laa** [comment]
It is not critical warning at all. It means that because the cache is full some of the operations will suffer from higher latency than usual.

**Comment by rbaarathinms** [comment]
Ok thanks..

**Comment by rbaarathinms** [comment]
When will the cache becomes full..??? What is the data present inside this cache..?? Can u explain ..?

**Comment by laa** [comment]
Cache become full because it is full by data of database operation journal. This journal is needed to support database durability and in case of DB crash, data are relayed back to restore data consistency.

**Comment by laa** [comment]
@rbaarathinms did I answer your question? May we close the issue?

**Comment by rbaarathinms** [comment]
Yes you can close.. Thanks @laa ..
