### ISSUE TITLE
Print into the log list of all running queries at the time when OOM is thrown

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7861]
In 99% of cases, we have got OOM because of execution of query which fetches a lot of data into the RAM. Adding such functionality will allow us to quickly detect which query was caused a problem.

**Comment by luigidellaquila** [comment]
Hi @laa 
I can do the logging of the currently running queries, but we have to define the exact point where to catch OOM exceptions

Thanks

Luigi

**Comment by laa** [comment]
@luigidellaquila we do need that all our Threads in core or server use com.orientechnologies.common.util.OUncaughtExceptionHandler which will do all work.

**Comment by laa** [comment]
Fixed.
