### ISSUE TITLE
Nested includes

### ISSUE THREAD

**Issue by Neglexis** [orientechnologies/orientdb#7862]
Say I have the following query
`select username, out('user_team').include('name') as team from user where username = 'Neglexis'`

I currently get the expected result, where it's something along the lines of (very simplified representation though)
```
{
  username: 'Neglexis',
  team: [
    {
      name: 'Team1'
    },
    {
      name: 'Team2'
    }
  ]
}
```

Say these teams have links to previous tournaments, how would I go about getting the names of these linked tournaments?

I know I can do something like 
`select username, out('user_team').include('name') as team, out('user_team').out('team_tournament').include('name') as tournament from user where username = 'Neglexis'`

But this gives me 
```
{
  username: 'Neglexis',
  team: [
    {
      name: 'Team1'
    },
    {
      name: 'Team2'
    }
  ],
  tournament: [
    {
      name: 'Super Saturday'
    },
    {
      name: 'Lazy Sunday'
    },
    {
      name: 'Super Saturday'
    }
  ]
}
```

So if my 2 teams participated in the same tournament, I'm getting these as duplicates, but with no way of knowing which tournament belongs to which team.

Is there anyway to get the structure below?
```
{
  username: 'Neglexis',
  team: [
    {
      name: 'Team1',
      tournament: [
        {
          name: 'Super Saturday'
        },
        {
          name: 'Lazy Sunday'
        },
      ]
    },
    {
      name: 'Team2'
      tournament: [
        {
          name: 'Super Saturday'
        },
      ]
    }
  ],
}
```

EDIT: as stated by @luigidellaquila in [this comment](https://github.com/orientechnologies/orientdb/issues/2118#issuecomment-307416361), the new projection syntax allows this in v3, but was wondering if, with older syntax, this would already be possible in a 2.2.x version.

**Comment by luigidellaquila** [comment]
Hi @Neglexis 

Right now (in v 2.2) you cannot obtain this exact structure (in v 3.0 you will have nested projections, see http://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections), but probably a little refactoring of your query will give you something similar to what you need:



```
SELECT name, out('team_tournament').include('name') as tournament FROM (
   SELECT expand(out('user_team')) FROM user WHERE username = 'Neglexis'
)
```
I hope it helps

Thanks

Luigi

**Comment by Neglexis** [comment]
Yeah, I played around with V3.M2 yesterday, and the nested projections is exactly what we're looking for.

Guess we'll just patiently await the V3 release then!
