### ISSUE TITLE
Why the select statement  "select count(1) from Order" take so long time?

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7864]
## Expected behavior  
Can quick get the query result.

## Actual behavior  
The the select statement  "select count(1) from Order" take time about 50s.   The class Order has about 1200000 records.

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @KishoDai 

There is a hard-wired optimization for `select count(*) from X`, but it seems it doesn't apply when you do `count(1)`. 

My suggestion is to just use `count(*)` for now, hopefully we'll fix it in the near future.

Thanks

Luigi

**Comment by KishoDai** [comment]
@luigidellaquila 
      Got it. Thank you very much.
