### ISSUE TITLE
ORecord Not found Exception

### ISSUE THREAD

**Issue by shanmuga007** [orientechnologies/orientdb#7866]
## Expected behavior  
#45:0  

## Actual behavior  
ORecordNotFoundException #-2:0  

## Steps to reproduce  
select @rid from test where test_id = 1;
insert into test1 (field1) values (@rid of test object);  

com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#-2:0' was not found

Note : #-2:0 this is not my document Id.  Actual document id is #45:0.

while committing DB, am getting this exception.

Code : 
Am used LINKED CLASS.
			ODatabaseDocumentTx db = orientTemplate.getDB();
			db.activateOnCurrentThread();
			db.begin();
			ODocument doc = new ODocument(className);
			doc.fromJSON(json);
			doc.save();
			db.commit(); -- Here am getting exception

**Comment by luigidellaquila** [comment]
Hi @shanmuga007 

Could you please post a script to create your schema?

What is `className` in your case? "test" or "test1"?

Thanks

Luigi

**Comment by shanmuga007** [comment]
Hi,

After using EXPAND its working now. 

Thanks.

Please give support JOINS. 
i) INNER JOIN
ii) LEFT JOIN like etc...

**Comment by luigidellaquila** [comment]
Ok, happy to hear this.

About joins, I'm afraid you'll never see them supported in OrientDB. You should consider the graph API instead

Thanks

Luigi
