### ISSUE TITLE
Question: what is your merge policy

### ISSUE THREAD

**Issue by nlavan** [orientechnologies/orientdb#7868]
Hi all,

I see you have a `develop` branch that contains the commits for 3.0.0, and a `2.2.x` branch that contains all the commits you call hotfixes, and that will go to the next release of 2.2 (2.2.30 at the time of writing).

`develop` is more than 1600 commits behind 2.2.x, I mean, they diverged by more than 1600 commits. How are you going to merge the commits of 2.2 into develop? How do you know which commits should be ported to 3.0 and which are not related? When are you going to do it? at RC1 or later? 

I am asking this because even though 3.0 is said to be very different than 2.2, it still shares a lot of common code, and I am wondering how do you port the bug fixes done on 2.2 into 3.0 ?

Thanks in advance for the info.
Good continuation,

Niko

**Comment by luigidellaquila** [comment]
Hi @nlavan 

As you already pointed out, 2.2.x and develop branches diverged a lot, so it's almost impossible to merge the changes automatically. What we are doing now is cherry-pick changes from 2.2.x to develop as soon as we commit them (when it makes sense of course). In some cases even a cherry-pick is impossible, so we just re-apply the changes manually to develop

Thanks

Luigi
