### ISSUE TITLE
OPolygon manipulation in orientDB

### ISSUE THREAD

**Issue by gpatel123** [orientechnologies/orientdb#7872]
Hi all, I am new in OrientDB. I have save OPolygon successfully but retrieving or coordinates of polygon is going to tough for me. I have save coordinate in 'location' field. what will be the return type if I took it as below. 
return_type loc = v.getProperty("location");
or tell me any other way to do this.

**Comment by maggiolo00** [comment]
Hi @gpatel123 

were you able to get an `ODocument` with `v.getProperty("location")` ?

Thanks

**Comment by maggiolo00** [comment]
hi @gpatel123 

do you have news about this?

Thanks

**Comment by gpatel123** [comment]
Thanks @maggiolo00 
I had used ODocument and it is working fin.
