### ISSUE TITLE
Out of bounds exception when creating a vertex with a default value

### ISSUE THREAD

**Issue by bordig-f** [orientechnologies/orientdb#7873]
## Expected behavior 
When running the following script in the OrientDB console:
```
create sequence test_seq type ordered

create class test extends v
create property test.value string (notnull true, mandatory true)
alter property test.value default 'sequence("test_seq").next()'

export database db.json.gz
import database db.json.gz

create vertex test
```
I expected a vertex to be created...

## Actual behavior
... but an error gets thrown:
```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on reading parameters in: sequence(	est_seq\)
	DB name="test_bug3"

Error: java.lang.ArrayIndexOutOfBoundsException: 8
```

## Steps to reproduce
Run the script specified above.

**Comment by luigidellaquila** [comment]
Quick update on this issue, the problem seems to be in the import procedure.
As a work-around, you can re-execute the following command after import

```
alter property test.value default 'sequence("test_seq").next()'
```

It should fix the problem

Thanks

Luigi

**Comment by bordig-f** [comment]
The workaround does work on my machine, thank you for posting it !
