### ISSUE TITLE
Options for OBackupable.backup() method

### ISSUE THREAD

**Issue by kmhughes** [orientechnologies/orientdb#7874]
### OS: Linux  

I want to use the backup() method for a database in my code that embeds OrientDB.

The javadoc mentions a configuration map for backup options, it is the second argument.

The javadoc does not say what options there are. 

What are those options, what do they mean, and can they be placed in the javadoc?

**Comment by luigidellaquila** [comment]
Hi @kmhughes 

Currently there are no supported options, that API is like that just for backward compatibility, you can safely pass `null`.

I'm adding a note to the javadoc.

Thanks

Luigi
