### ISSUE TITLE
How to read ODocument using clusterNames

### ISSUE THREAD

**Issue by rbaarathinms** [orientechnologies/orientdb#7877]
Hi,
   Our orient version - 2.2.20
   Java version - jdk1.8.0_121
   We are trying to create many cluster names for a single OClass. Using some logic we split our data and put it into different cluster names. (i.e) We have a OClass(table) name Test, we physically create many cluster names say 5 (test-1, test-2, test-3, test-4, test-5). Each cluster can have n number of rows(ODocument or ORecord) and columns where some column must be indexed. It may be unique or non - unique. 
Now what we need is to get a ODocument from cluster 4 (i.e test-4). In Java API, is there any method available so that i can use to get ODocument  from required cluster specifying the OClass???

**Comment by laa** [comment]
@rbaarathinms cluterId is already encoded in document rid. So if I got you correctly there is nothing to do from your side to fetch the document from the specific cluster by rid.

**Comment by laa** [comment]
@rbaarathinms did I answer your question? Can we close issue?

**Comment by rbaarathinms** [comment]
We found some advantages while reading from orient database using cluster. In orientdb manual, they mentioned that suppose a class Customer relies on two cluster namely USA Customer(default cluster name) and Chinese Customer(containing all chinese customer). From the manual - (If you know the location of a customer you're looking for you can query the target cluster directly. This avoids scanning the other clusters and optimizes the query). Likewise I want to retrieve the data from orient using specific cluster name. Now tell me how can I proceed?? I want a method through Java API. Is there any method available..?
Refer the link below in case of doubt -- http://orientdb.com/docs/2.0/orientdb.wiki/Tutorial-Clusters.html

**Comment by laa** [comment]
@rbaarathinms what would like to do? Do you want to execute SQL query? Your intention unclear for me ))

**Comment by adithyank** [comment]
Without any cluster usage, We were using OIndex of particular class like given below

``` java
ODocument getDoc(String className, String fieldName, String valueOfKey)
{
      String indexName = className + "." + fieldName;
      OIndex index = database.getMetadata().getIndexManager().getIndex(indexName);
      ORecordId rid = index.get(valueOfKey);
      return rid.getRecord()
}
```

Now, we are doing our side code changes to store the documents in the individual clusters.
So, if we use the above code (without any cluster names), to retrieve the document from the index, will it be fast?? Or, is there any other method with which we can retrieve a document by giving its clusername?

By seeing the OrientDB documentation, we understood that if we dont supply clustername while reading the document, it will scan all clusters... We want to avoid scanning scanning of all clusters because we know the clustername for each key.

is it clear?

**Comment by laa** [comment]
@adithyank code which you provided will work with the same speed with one or several clusters because it never does cluster scan, it fetches single record from exact position of the exact cluster. So no scan by single or multiple clusters is needed.

**Comment by adithyank** [comment]
Super. This issue can be closed. Thanks @laa
