### ISSUE TITLE
Public CI for ppc64le available/ready for orientdb job deployments

### ISSUE THREAD

**Issue by ghatwala** [orientechnologies/orientdb#7878]
Hi Folks ,

We now have a public CI for IBM's powerpc64le (Jenkins based at this point) and wanted to understand if you would be interested in having us setup a build job there for orientdb there - it would give us a way to ensure that any changes that may need additional attention for Power are detected up front. Thanks! 

Regards,
Amit

**Comment by laa** [comment]
Hi @ghatwala we are really interested. Let's go forward and resolve any questions/issues here.

**Comment by ghatwala** [comment]
@laa  - Thanks for the quick response . I do have few questions as below...

1. Our Jenkins CI has support to deploy the job  
a. inside a docker container ( ppc64le based ) acting as slave node or
b. on a VM ( ppc64le based ) acting as slave node. 
let me know if any above deployment would suffice for orientdb

2. Any minimum system resource requirements - RAM / disk space ?

**Comment by laa** [comment]
@ghatwala about your questions:
1. I think that Docker since latest (2.2.30 build) and latest 3.0 which is M3 (we will release both) soon will be OK.   
2. I suppose that 4Gb of RAM with 512 Mb of the heap will be enough.

**Comment by laa** [comment]
@ghatwala sorry I just found out that we need 6GB of RAM and 2046 of the heap to run tests )).

**Comment by ghatwala** [comment]
@laa : thanks for the response . From our side, we are actively working on finalizing the access request form and documentation for this. Some additional information can be found at "http://osuosl.org/services/powerdev/"  for your reference.

**Comment by ghatwala** [comment]
@laa : thanks for the response . From our side, we are actively working on finalizing the access request form and documentation for this. Some additional information can be found at "http://osuosl.org/services/powerdev/"  for your reference.

**Comment by ghatwala** [comment]
Hi @laa , @luigidellaquila  - Just thought of checking here , wanted some updates on this ...

- Are you'll still using a "ppc64le" VM at OSU/OSL requested via this form - http://osuosl.org/services/powerdev/request_hosting/ ? 

- Did you'll manage to add this slave node to your CI server to ensure running ppc64le builds  ?

**Comment by ghatwala** [comment]
Any updates on above - @laa , @tglman ?

**Comment by laa** [comment]
Sorry not a priority right now
