### ISSUE TITLE
[Question]`IS DEFINED` syntax doesn't work when property is create?

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#7879]
## Expected behavior  
For example, I create property `age` on v_test, because I need create index on it.
And I execute the sql below
`select from v_test where age is not defined`
I expect orientdb  return record where the `age` is not exists , but orientdb return None record.

## Actual behavior  
I expect orientdb  return record where the `age` is not exists , but orientdb return None record.

## Steps to reproduce  
create a vertex class `v_test`
create a property `age` on `v_test`
create a record : `create vertex v_test content {name="jack"}`
execute sql: `select from v_test where age is not defined`

**Comment by lightjiao** [comment]
Here is the feature issue: https://github.com/orientechnologies/orientdb/issues/166

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

Thank you for reporting, I'll check it asap

Thanks

Luigi

**Comment by lightjiao** [comment]
Sorry @luigidellaquila 
I set `null` value to `age` in my code  :(
when a field's value was `null`, `IS DEFINED` and `IS NOT DEFINED` both can get the record, why?

**Comment by luigidellaquila** [comment]
HI @lightjiao 

it was a bug, I just pushed a fix on 2.2.x branch, the fix will be released with 2.2.31

Thanks

Luigi

**Comment by lightjiao** [comment]
@luigidellaquila 👍
