### ISSUE TITLE
[Question] Is it possible to see which command cause exception - OCommandExecutionException?

### ISSUE THREAD

**Issue by Miyazawa-Shi** [orientechnologies/orientdb#7884]
### OS: CentOS 7  

Hello,

I use pyorient API to load data from different sources to OrientDB. Sometimes there are inconsistencies in the source data and it couses exceptions like "No edge has been created because no source vertices". I execute a lot of commands in one transaction to easy rollback it when something goes wrong.

My question is: 
Is it possible to see which command cause the exception **OCommandExecutionException("No edge has been created because no source vertices")** or **OCommandExecutionException("No edge has been created because no target vertices")** - OCommandExecutorSQLCreateEdge.java? I mean the exact command e.g. "Create edge e from A to B". When I execute everything in one transaction it's impossible to handly catch which command caused the problem. Unfortunately the OCommandExecutionException say nothing more than those sentences.

Regards,
Miyazawa-Shi

**Comment by laa** [comment]
Hi @Miyazawa-Shi , that is already implemented in latest release 2.2.30, please wait for one day and we release it.

**Comment by Miyazawa-Shi** [comment]
Great message! Thank you so much :)

**Comment by laa** [comment]
so we released it, you can check it ))

**Comment by Miyazawa-Shi** [comment]
Now, I use the lastest release 2.2.30, but unfortunately I have the same message without details :( _com.orientechnologies.orient.core.exception.OCommandExecutionException: No edge has been created because no source vertices DB name="*****"_

When I run e.g. 100 commands in one transaction by pyorient api I have no idea which one cause the exception.

**Comment by laa** [comment]
Hi @luigidellaquila could you comment on that?

**Comment by luigidellaquila** [comment]
Hi @Miyazawa-Shi 

Let me double-check it, I think CREATE EDGE executor needs a little fix

Thanks

Luigi

**Comment by luigidellaquila** [comment]
HI @Miyazawa-Shi 

I just pushed a fix on 2.2.x, it will be released with 2.2.31

Thanks

Luigi
