### ISSUE TITLE
Select not returning out vertices

### ISSUE THREAD

**Issue by tomazk8** [orientechnologies/orientdb#7885]
## Expected behavior  
Select should return out vertices giving an source vertex id.

## Actual behavior  
Using SELECT to get the out vertices returns nothing, but TRAVERSE returns them. 

## Steps to reproduce  
I deleted the whole OrientDB installation and all of the databases and installed version 2.2.30. I have created the database from scratch, no extras, I just registered two classes, Person and Card, both derived from V. I added two vertices, Person (Name=Mike, @rid=25:0) and Card (UID=123, @rid=34:0) and one IdentifiesWith edge going from Person to the Card. When I run this query, I get nothing:
select out('IdentifiesWith') from V where @rid == #25:0
but if I run this query, it finds the card:
traverse out('IdentifiesWith') from #25:0

From the online documentation the select clause should return the result. I can reproduce this problem  every time and I have a database that I can share if needed.

Thank you and best regards
Tomaz

**Comment by luigidellaquila** [comment]
Hi @tomazk8 

I just tried it and it seems to work fine. 
Could you please try the following:

```
select expand(out('IdentifiesWith')) from V where @Rid == #25:0
```

Thanks

Luigi

**Comment by tomazk8** [comment]
Hi Luigi

Sorry, I made a mistake above. The Id of the Person is #33:0, not #25:0. But also in this case the select I wrote previously returns nothing. Your query on the other hand (but with @Rid == #33:0) does return the Card vertex.

I've ran my original query also in a test .NET Core application (using a OrientDB .NET client) and there I get an object back with #rid = #-2:0 and one of the fields holds the results. So it actually returns an object with results, and not the the results directly... or something in this direction?

Best regards
Tomaz

**Comment by luigidellaquila** [comment]
Hi @tomazk8 

Could you please post the results of 

```
SELECT FROM V
```

and

```
SELECT FROM E
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @tomazk8 

Yes, what happens here is that you get an object containing pointers to the out() vertices, ie. the RIDs of these vertices.
If you want their actual values, you have to do an expand():

```
select expand(out('IdentifiesWith')) from V where @Rid = #33:0
```

Thanks

Luigi

**Comment by tomazk8** [comment]
Hi Luigi

Ok, great. Thank you very much for your help.

Best regards
Tomaz
