### ISSUE TITLE
Check lightweight edges on vertex delete

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#7886]
## Expected behavior  
Vertices are correctly updated when a vertex linked with lightweight edges is removed

## Actual behavior  

Stale links

## Steps to reproduce  

Enable Lightweight Edges
CREATE CLASS SimpleV EXTENDS V
CREATE CLASS SimpleE EXTENDS E
INSERT INTO SimpleV CONTENT {"name":"A"}  // this is #25:0
INSERT INTO SimpleV CONTENT {"name":"B"}  // this is #25:1
CREATE EDGE SimpleE FROM #25:0 TO #25:1
SELECT FROM SimpleE  // empty result, provides that Lightweight Edge was used
DELETE VERTEX #25:1
SELECT FROM SimpleV  // returns #25:0, with OUT still showing link to #25:1

**Comment by Eric24** [comment]
Is this bug scheduled for a fix?

**Comment by luigidellaquila** [comment]
Hi @Eric24 

There is no fixed schedule, but for sure we will address it soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Just pushed a fix for this bug to 2.2.x branch. Porting it to 3.0

Thanks

Luigi
