### ISSUE TITLE
Cannot perform query in distributed node when vertex is in another cluster

### ISSUE THREAD

**Issue by gabrielmm1234** [orientechnologies/orientdb#7887]
## Expected behavior  
I wanted do perform a simple in a server called node1 to retrieve vertexes that are stored in node2. The query is: select from Parlamentar

The Parlamentar cluster is stored in node2 and I am running the query in node1 console. The distributed architecture is working fine. If i go to node2 console and perform the query it works.

## Actual behavior  
When I run the query the console in node1 show some errors: 

2017-11-15 20:39:40:026 WARNI Error deserializing record with id #21:745 send this data for debugging: ABZQYXJsYW1lbnRhcihvdXRfUmVhbGl6YVRyYW5zYWNhbwAAAIUWIlR4Tm9tZVBhcmxhbWVudGFyAAAAogcWSWRlQ2FkYXN0cm8AAAC0AyxOdW1DYXJ0ZWlyYVBhcmxhbWVudGFyAAAAtwEIU2dVRgAAALgHElNnUGFydGlkbwAAALsHAAAmR3xyAAAAcwAAAAAAAAAjAADgAP////8AAAAAIkFCRUwgTUVTUVVJVEEgSlIumuwVAgRSUgZERU0=  [ORecordSerializerNetwork]
2017-11-15 20:39:40:026 WARNI I/O Error on distributed channel (clientId=2 reqType=121 error=com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);) [ONetworkProtocolBinary]
2017-11-15 20:39:55:292 WARNI [node1]->[node2] Server 'node2' did not respond to the heartbeat message (db=CotasParlamentares, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]

In node2 the error is:

 [node2]->[node1] Error on sending message to distributed node (java.net.SocketException: Broken pipe) retrying (1/3) [ORemoteServerChannel]

## Steps to reproduce  
I have the database already filled. I start node1 using dserver.sh and then start node2 using dserver.sh. I connect to node1 using console.sh and perform the query mentioned above.

**Comment by luigidellaquila** [comment]
Hi @gabrielmm1234 

My first suggestion is to upgrade to 2.2.30 (latest stable), that has a lot of fixes compared to 2.2.17.

To better understand what's going on, I need a couple more info:
- is the DB supposed to be in full replica?
- is it correctly replicating? ie. when you start node2, do you see db replication in the logs?

If you are in full replica, what I can suggest is to stop node2, delete (or better move somewhere else) the DB from node2 and then start it again. 

Thanks

Luigi

**Comment by gabrielmm1234** [comment]
Hi @luigidellaquila  thanks a lot for your help!

No, I am using sharding. There are some vertexes in node1 and some vertexes in node2. What I need is to perform a query in node1 regarding vertexes stored in node2 (I want to test the performance in distributed mode).

I almost sure that it is correctly replicating. If if connect using the console.sh in node1 and perform a query regarding a vertex that is stored in node1 it works. The same happens for node 2.

I think I need to mention that, the first time I tried to do this, it worked! The query returned the correct result. But after that I tried to perform a query using 3 nodes, and then I saw this broken pipe error for the first time


I will try to upgrade to 2.2.30 (I did not want to upgrade because I have an ETL written in java already working in 2.2.17 version, and when I tried to upgrade in the past the ETL stopped working haha)

**Comment by luigidellaquila** [comment]
Hi @gabrielmm1234 

Could you please share the distributed-config.json files in your databases?

About the ETL, what kind of problem did you have in the migration?

Thanks

Luigi

**Comment by hossein-md** [comment]
I think one of my problem is here! (issue: #8234)
@gabrielmm1234, do you find the answer/solution?
Thanks

**Comment by gabrielmm1234** [comment]
Hi @hossein-md, I was doing this for my graduation project. However, the project changed a little and I've stopped researching :(

**Comment by saeedtabrizi** [comment]
Hi @luigidellaquila 
As i commented in #8234 issue ,  i have tested normally  . 
I guess there is misconfiguration problem for distribution mode here . 
Thanks .
