### ISSUE TITLE
Passwords stored in .orientdb_history file

### ISSUE THREAD

**Issue by FreeK** [orientechnologies/orientdb#7890]
## Expected behavior  
Passwords should **NOT** be stored in .orientdb_history

## Actual behavior  
Passwords are stored in plain text in .orientdb_history

## Steps to reproduce  
Connect to OrientDB via console:
`$ORIENTDB_HOME/bin/console.sh`

Connect to a database:
`orientdb> CONNECT plocal:../databases/GratefulDeadConcerts admin my_admin_password`

Quit the console and cat .orientdb_history file:
```orientdb@server:~ cat .orientdb_history
CONNECT plocal:../databases/GratefulDeadConcerts admin my_admin_password
exit
```

As this violates our security policy, we cannot use OrientDB.

**Comment by wangjunji** [comment]
I have the same problem.
Not only password, the encryption key is also stored in plain text in .orientdb_history by executing `config set storage.encryptionKey xxxxxxxxx` in `console.sh`
It may cause security issue. Please fix it ASAP

**Comment by luigidellaquila** [comment]
Hi @wangjunji @FreeK 

I added a `--disable-history` option to the console, so that you can disable that functionality if needed

Thanks

Luigi
