### ISSUE TITLE
user defined sql functions with arguments, doc example does not work.

### ISSUE THREAD

**Issue by jcwright77** [orientechnologies/orientdb#7891]
## Expected behavior  
function returns factorial  

## Actual behavior  
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Invalid script:Encountered "" at line 1, column 5.
Was expecting one of:

	DB name="testdb"
	DB name="testdb"

## Steps to reproduce  
create new db
connect via console

create function following example in 2.2 docs
> create function factorial "if (num === 0) return 1; else return num * factorial(num - 1)" PARAMETERS [num]  

call function

> select factorial(2)

In fact, I cannot seem to reference a parameter in a user defined sql function without encountering this error.  This happens whether I define the function and run it in Studio or the console.

**Comment by luigidellaquila** [comment]
Hi @jcwright77 

Thank you very much for reporting, I just fixed the docs, it missed a `LANGUAGE javascript` (by default it's SQL):

```
create function factorial "if (num === 0) return 1; else return num * factorial(num - 1)" PARAMETERS [num] LANGUAGE javascript
```

Thanks

Luigi
