### ISSUE TITLE
"Encountered " <CREATE> "create """ when trying to create a user with console.sh

### ISSUE THREAD

**Issue by anthony-o** [orientechnologies/orientdb#7898]
## Expected behavior  
In the `console.sh` I want to create a user with the following command:

```
CREATE USER myuser IDENTIFIED BY userpass ROLE admin
```

## Actual behavior  
I've got the following error:
```
	Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:

	     ^
	Encountered " <CREATE> "create "" at line 1, column 1.
	Was expecting one of:
	    <IF> ...
	    <FOREACH> ...
	    ";" ...
	    <IF> ...
	    
		DB name="db"
		Error Code="1"
		DB name="db"
```

## Steps to reproduce  
As explained [here](https://stackoverflow.com/q/47446065/535203), in terminal 1, run the following:

    docker run -it --name orientdb -p "2424:2424" -e ORIENTDB_ROOT_PASSWORD=rootpass orientdb:3.0.0m2

In terminal 2, run the following:

    docker run -it --rm --link orientdb:orientdb orientdb:3.0.0m2 /orientdb/bin/console.sh

Then create the db:

    CREATE DATABASE remote:orientdb/db root rootpass PLOCAL

And try to create the user:

    CREATE USER myuser IDENTIFIED BY userpass ROLE admin

**Comment by luigidellaquila** [comment]
Hi @anthony-o 

I just pushed a fix on develop branch, now it should work fine

Thanks

Luigi

**Comment by anthony-o** [comment]
@luigidellaquila , thank you very much.
Nevertheless, I'm now having another message when trying to create the user:
```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
create USER myuser IDENTIFIED BY userpass ROLE admin
     ^
Encountered " <CREATE> "create "" at line 1, column 1.
Was expecting one of:
    <LET> ...
    <EXPLAIN> ...
    
	DB name="db"
	Error Code="1"
	DB name="db"
```
Here is the OrientDB version I used `OrientDB Server is active v3.0.0-SNAPSHOT (build 50d83b81407462cd92fcc8c4c3413efa148f24db, branch branches/develop/workspace/core)`.

**Comment by luigidellaquila** [comment]
Hi @anthony-o 

How are you getting the snapshot? That version seems to be two days old...

If you are using maven, probably cleaning the cache will help, otherwise you can try this:

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.0-SNAPSHOT/orientdb-community-3.0.0-20171124.061803-992.tar.gz

Thanks

Luigi

**Comment by anthony-o** [comment]
I used `mvn dependency:get -Ddest=./ -DremoteRepositories=sonatype-nexus-snapshots::::https://oss.sonatype.org/content/repositories/snapshots -Dartifact=com.orientechnologies:orientdb-community-gremlin:3.0.0-SNPASHOT:tar.gz` to retrieve the version I tested, I will try `orientdb-community` instead, thank you.

**Comment by anthony-o** [comment]
I'm now running `v3.0.0-SNAPSHOT (build dfba28275fa4db515ef43342b5c3ade7b60d7984, branch branches/develop/workspace/core)` and facing that other issue:
```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
create USER my-user IDENTIFIED BY userpass ROLE admin
              ^
Encountered " "-" "- "" at line 1, column 16.
Was expecting:
    <IDENTIFIED> ...
    
	DB name="db"
	Error Code="1"
	DB name="db"
```
(I have a `-` in my user's name, this was working with console.sh v2.2.30 talking to a 3.0.0m2 version)

**Comment by anthony-o** [comment]
It worked with

    create USER `my-user` IDENTIFIED BY userpass ROLE admin

Thank you!

**Comment by luigidellaquila** [comment]
Oh yeah, the user name is an identifier, you have to quote it if you use non-alphanumeric characters

Thanks

Luigi
