### ISSUE TITLE
where can i get the 32 bit version?

### ISSUE THREAD

**Issue by el3ctron** [orientechnologies/orientdb#7899]
where can i get the last orientdb on 32 bit version?

**Comment by laa** [comment]
Hi, @el3ctron as we probably discussed with you on Twitter just remove `-d64` from the server.sh and decrease the value of the flag `-XX:MaxDirectMemorySize=512g`  to the `4g` or `3g`.

**Comment by luigidellaquila** [comment]
Hi @el3ctron 

Did this answer help? Can we consider this ticket resolved?

Thanks

Luigi

**Comment by el3ctron** [comment]
Hi i change the /opt/orientdb-community/bin/server.sh value to 4g and now appears

removing old pid file /opt/orientdb-community/bin/orient.pid
Invalid maximum direct memory size: -XX:MaxDirectMemorySize=4g
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

now i tried with 3g setup:
JAVA_OPTS_SCRIPT="-Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -Xmx1024M -XX:MaxDirectMemorySize=3g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9"

and server says:

removing old pid file /opt/orientdb-community/bin/orient.pid
Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
