### ISSUE TITLE
Error parsing query in group by operator

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#7902]
### OS: Ubuntu 16.04
Hello,
I have property EMBEDDEDMAP which contains locales string, example: `{"en":"Hello World"}`
I need to get documents which are sorted by EMBEDDEDMAP values.
## Expected behavior
`SELECT FROM Test ORDER BY COALESCE(map['en'], map.values()[0])`
- returns or en locale string or first string in map if en string is empty, but this throws exception.

## Actual behavior  
Throws exception:
`Error parsing query: select from Test order by coalesce(map['en'], map.values()[0]) ^ Encountered " "(" "( "" at line 1, column 35. Was expecting one of: <EOF> <LIMIT> ... <SKIP2> ... <OFFSET> ... <TIMEOUT> ... <ASC> ... <DESC> ... <FETCHPLAN> ... <LOCK> ... <NOCACHE> ... <PARALLEL> ... <UNWIND> ... "[" ... ";" ... "," ... "." ... "[" ... "." ... "." ... <DESC> ... <ASC> ... "," ... <UNWIND> ... <SKIP2> ... <OFFSET> ... <LIMIT> ... <FETCHPLAN> ... <TIMEOUT> ... <LOCK> ... <PARALLEL> ... <NOCACHE> ... DB name="test"`

## Steps to reproduce  

1. `CREATE CLASS Test`
2. `CREATE PROPERTY Test.id INTEGER`
3. `CREATE PROPERTY Test.map EMBEDDEDMAP STRING`
4. `INSERT INTO Test (id, map) VALUES(0, "{"en":"a", "uk":"b"}")`
5. `INSERT INTO Test (id, map) VALUES(1, "{"uk":"c"}")`
6. `SELECT FROM Test ORDER BY COALESCE(map['en'], map.values()[0])`
Last query must return sorted documents but it throws exception.

Thanks,
Vitaliy.

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

ORDER BY currently does not support generic expressions, you can only use identifiers and record attributes.

We will probably extend it in v 3.0 to be more generic

My advice here is to re-write the query as follows:

```
SELECT expand(rid) FROM (
   SELECT @rid as rid, COALESCE(map['en'], map.values()[0]) as x FROM Test ORDER BY x ASC
)
```

I hope it helps

Thanks

Luigi

**Comment by WeaxMe** [comment]
Thank you!
