### ISSUE TITLE
Does OrientDB support subqueries?

### ISSUE THREAD

**Issue by student1555** [orientechnologies/orientdb#7904]
## issue
Does OrientDB support subqueries?
eg.
select * from (select * from a) b  where ...

**Comment by luigidellaquila** [comment]
Hi @student1555 

Yes, OrientDB supports subqueries, but you cannot add aliases to them.

You can write your query as follows:

```
select * from (select * from a) where ...
```

I hope it helps

Thanks

Luigi

**Comment by student1555** [comment]
OK, Thank you, @luigidellaquila .
