### ISSUE TITLE
How to implement this query("from t1, t2") ?

### ISSUE THREAD

**Issue by shushengxing** [orientechnologies/orientdb#7912]
### OS: centos7 

SQL statement like :
select t1.c2 from t1, t2 where t1.c1=t2.c1
There are two tables in "from" statement and "t1.c1=t2.c1" constraint in "where" statement.
The query is fail. 
How to implement this query ?

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

In OrientDB you cannot do JOIN operations, this syntax is not supported.

A graph database is optimized to traverse physical relationships (ie. edges). For his kind of use cases you have to review your model and replace the foreign keys with edges, here you can find an exmaple: http://orientdb.com/docs/2.2.x/Tutorial-Working-with-graphs.html

Thanks

Luigi

**Comment by shushengxing** [comment]
OK, I see.
Thans, @luigidellaquila .
