### ISSUE TITLE
How to use "profiler" command in console ? 

### ISSUE THREAD

**Issue by Zhangjp0** [orientechnologies/orientdb#7913]
## Expected behavior  
console command : profiler on
For query operations, "profiler on" can display some information, as follows : 
readspeedfromfileinpages, amountofpagesreadfromfile, amountofpagesperoperation, recordreadpages, ...

## Actual behavior  
The above information can not be displayed. 
How to display these informations with "profiler" ?

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

Did you try to run `PROFILE DUMP` after the query execution?

Thanks

Luigi

**Comment by shushengxing** [comment]
Thanks, @luigidellaquila .
Yes. First, execute "profiler on" command; and execute one query; then execute "profiler dump", nothing to display in console interface. Does it save to a file ?

**Comment by luigidellaquila** [comment]
No, it should dump in the console itself. Maybe there is a bug, I'll check it asap

Thanks

Luigi

**Comment by shushengxing** [comment]
Thanks, @luigidellaquila .
Are there some related settings in configuration file ?

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

No, it's not a matter of configuration. I think I got the problem, the profiler is currently available only on a plocal connection, it's not supported in remote.

Thanks

Luigi

**Comment by shushengxing** [comment]
Thanks, @luigidellaquila .
But executing "connect plocal:/.../database-name  [user]  [password]", always have a mistake : "user or password not valid for database: ..". I guarantee that the user and password are correct, which is setted when creating database.
What's wrong ?

**Comment by luigidellaquila** [comment]
I guess you are pointing to the wrong directory.
Try `connect plocal:..databases/database-name [user] [password]`, and make sure that the server is stopped

Thanks

Luigi

**Comment by luigidellaquila** [comment]
sorry
```
connect plocal:../databases/database-name [user] [password]
```

**Comment by shushengxing** [comment]
Yes, the server is stopped, but it still doesn't work.
And, No matter the server is running or stopped when creating database, now it can't connect with "plocal". 
What should I do ?

Thanks, @luigidellaquila .

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

That's a basic feature, if it didn't work I'd have complains form at least one thousand users, so I tend to exclude it ;-)
 
Could you please try to connect with absolute path? Maybe it's just a problem with the db position. Ah, please connect with `admin` user, not with `root` (in embedded you have no root user)

Thanks

Luigi

**Comment by shushengxing** [comment]
Yes, "admin" user is right.
But "profiler dump" still doesn't show any information.

Thanks, @luigidellaquila .
