### ISSUE TITLE
OrientDB schema migration tool.

### ISSUE THREAD

**Issue by sbespalov** [orientechnologies/orientdb#7915]
### Java Version: 1.8

it's not actually an issue but a question. I was not able to find any Java tool for it.
I think it will be really helpful to make some references about Schema migration tools in official documentation.

UPD:
related [Stackoverflow question](https://stackoverflow.com/questions/47648289/orientdb-schema-migration-tool-for-java)

**Comment by luigidellaquila** [comment]
Hi @sbespalov 

Right now there is no specific support for schema migration in OrientDB, there were some attempts from the Community (see https://github.com/akhawaja/orientdb-schema-migration) but they have very basic functionality

Thanks

Luigi
