### ISSUE TITLE
Roles are not removed from user using Java Client

### ISSUE THREAD

**Issue by lucafrosini** [orientechnologies/orientdb#7918]
## Actual behavior  
Trying to remove a role from an user (using java api with remote protocol with ploacl storage) I don't get any exception but the role is not effectively removed.
Trying to remove a role from Studio it works.

I'm using a single instance.

## Steps to reproduce  

A created a class with name ReproduceRemoveRoleBug in the project available here:
https://github.com/lucafrosini/orientdb-bug-reports

**Comment by lucafrosini** [comment]
Mainly the code is this:

`
private void removeRoles() {
		OrientGraphFactory factory = new OrientGraphFactory(HOST + "/" + DB_NAME, ADMIN_USERNAME, ADMIN_PASSWORD).setupPool(1, 10);
		factory.setConnectionStrategy(OStorageRemote.CONNECTION_STRATEGY.ROUND_ROBIN_CONNECT.toString());
		
		OrientGraph orientGraph = factory.getTx();
		ODatabaseDocumentTx oDatabaseDocumentTx = orientGraph.getRawGraph();
		OSecurity oSecurity = oDatabaseDocumentTx.getMetadata().getSecurity();
		
		OUser myUser = oSecurity.getUser(USERNAME);
	
		for(String role : ROLES) {
			myUser.removeRole(role);
			myUser.save();
		}
		
		orientGraph.commit();
		orientGraph.shutdown();
		
		System.out.println("Roles removed from " + USERNAME);
		
}`

**Comment by lucafrosini** [comment]
Direct link to java class is here:

https://github.com/lucafrosini/orientdb-bug-reports/blob/master/src/main/java/org/gcube/orientdb/ReproduceRemoveRoleBug.java

**Comment by lucafrosini** [comment]
@lvca any interest on this?

**Comment by lvca** [comment]
@lucafrosini thanks for reporting it. @luigidellaquila any idea on it?

**Comment by luigidellaquila** [comment]
Hi @lvca 

No, I have to check it, I'll let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @lucafrosini 

I just pushed a fix on 2.2.x branch, it will be released with 2.2.32.

Now I'm porting it to develop (3.0)

Thanks

Luigi

**Comment by lucafrosini** [comment]
Thanks @luigidellaquila , 
I'll test it as soon as the 2.2.32 will be released to provide you feedback.
