### ISSUE TITLE
ORDER BY doen't work

### ISSUE THREAD

**Issue by dwor-kin** [orientechnologies/orientdb#7921]
### Java Version: 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

## Expected behavior  
SELECT FROM Person ORDER BY surname;
expected just list of content;

## Actual behavior  
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing

Error: java.lang.NoClassDefFoundError: Could not initialize class sun.text.normalizer.NormalizerImpl

**Comment by sblommers** [comment]
Something is wrong with your installation. Did you reboot your server after installing openjdk? Also try running it on Oracle JDK instead of openjdk if your problem remains; 
https://gist.github.com/rtfpessoa/17752cbf7156bdf32c59

**Comment by luigidellaquila** [comment]
Hi @dwor-kin 

The problem is definitely related to the server install or the JVM (sun.text.normalizer.NormalizerImpl is a standard Java class, in bundle with the jvm)

Thanks

Luigi
