### ISSUE TITLE
No function description bothV() in OrientDB Manual - version 2.2.x

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#7925]
### OrientDB Version: 2.2.30
No description of function `bothV()` in OrientDB Manual - version 2.2.x
I call function `bothV()` and it's works, but description of this function not exists in manual. 
[Link to Function Section](https://orientdb.com/docs/2.2/SQL-Functions.html)

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

Thank you very much for pointing it out, `bothV()` is a valid function indeed. I'll update the docs asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Added, thanks!

Luigi
