### ISSUE TITLE
Teleporter non existent in orientdb-community-tp2-3.0.0m2

### ISSUE THREAD

**Issue by johtor2** [orientechnologies/orientdb#7926]
## Expected behavior  
Teleporter should be present in bin catalog  

## Actual behavior  
Binaries are missing... not able to run teleporter

## Steps to reproduce  
Open bin catalog. oteleporter is missing.

Before we make any more investment in Teleporter we just would like to make sure that Teleporter will be included in version 3 of OrientDB.

**Comment by luigidellaquila** [comment]
Hi @johtor2 

We are releasing OrientDB V 3.0.0RC1, it should be available in a few days. I'll make sure that Teleporter is there

Thanks

Luigi

**Comment by johtor2** [comment]
Thank you Luigi!

//Johan

**Comment by johtor2** [comment]
Hi Lugi,

Is the code for Teleporter improved in some way in 3.0 or is it same code as in 2.2.31.

Thanks

Johan

**Comment by weickdev** [comment]
> We are releasing OrientDB V 3.0.0RC1, it should be available in a few days. I'll make sure that Teleporter is there

Will you release 3.0.0RC1 this week? @luigidellaquila

**Comment by luigidellaquila** [comment]
This is what we are trying to do ;-)

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @johtor2 

I just wanted to let you know that OrientDB v 3.0.0RC1 is available for download here:

http://orientdb.com/orientdb-labs/

We decided to keep the distribution as they were in M2, so the TP2 package is still without Teleporter. Anyway fixing it is trivial:

- Just download this: http://orientdb.com/download.php?file=orientdb-community-importers-3.0.0RC1.tar.gz
- unzip and take the teleporter jar file from `plugins` directory
- copy it in the `plugins` directory of your tp2 distribution

Then just restart and you should be OK 

Please consider that the final GA will have a slightly different packaging, so we will probably have only distributions with Teleporter (and all the other importers), so a bit less options but all with full features.

Thanks

Luigi

**Comment by johtor2** [comment]
@luigidellaquila 

Question: Any code changes in teleporter 3.0 compared to 2.2.31 ?

**Comment by luigidellaquila** [comment]
hi @johtor2 

There are just some adaptations to the new APIs, but it's 99% the same

Thanks

Luigi

**Comment by johtor2** [comment]
Hi @luigidellaquila  

Could you please make a quick regression test on Telporter + conf file. We are unable to make it work. I would be nice to have that feature working in 3.0.

Thanks

Johan
