### ISSUE TITLE
Source DB Tables not show any things

### ISSUE THREAD

**Issue by hosseinGanjyar** [orientechnologies/orientdb#7928]
## Expected behavior  
I wanted import many tables from a database, but when I'm in **Step 3: Filters (Advanced)** could not see any things(all tables) in **Source DB Tables**. And after next/back my page is not same before.

![screenshot](https://user-images.githubusercontent.com/16970989/33936787-fc7ae00a-e015-11e7-960d-c52eb04e81dd.jpg)

 **_Notice_**: I've got an error in console !

![screenshot](https://user-images.githubusercontent.com/16970989/33941090-9b537b14-e026-11e7-8d57-5b59b783e077.jpg)

**Comment by johtor2** [comment]
I have exactely same problem. Try to pull data from Oracle 12.1. Tried several versions of OrientDB including latest 2.2.31. Enterprise versions.... community and even 3.0 (seems not having Teleporter in binaries at all). Please look into this so that we can get forward with our plans for OrientDB.

**Comment by mixit** [comment]
Looks like this issue has been forgotten (or just ignored)

Cannot activate Teleporter - (one year later..  its January 6, 2019)
Just experienced similar issue on latest OrientDB  3.0.13 (docker version on windows - released 2 days ago)

In one year - not even one status update??
You know this in NOT working (how it can without the binaries?)
 AND not a word in the "documentation"?
 

drivers list is empty, 
{
  "errors": [
    {
      "reason": 405,
      "code": 405,
      "content": "Command not found: teleporter/drivers"
    }
  ]
}
