### ISSUE TITLE
Not able to use teleporter with configuration file

### ISSUE THREAD

**Issue by RedfieldAB** [orientechnologies/orientdb#7929]
## Expected behavior  
Be able to load data from Oracle database with conf file. Please not that i am able to load data without conf file. It is only when adding conf file i get the error.

## Actual behavior  

There seems to be no way to include a conf file to the command line:

C:\Users\togjj\Desktop\orientdb-community-importers-2.2.31\bin>oteleporter -jdriver oracle -jurl jdbc:oracle:thin:@<host>:1521:<db> -juser <user> -jpasswd <pwd> -ourl plocal:$ORIENTDB_HOME\databases\teleporter_test3 -v 1 -conf $ORIENTDB_HOME\migration_conf.json

Exception in thread "main" java.lang.NullPointerException
        at com.orientechnologies.teleporter.main.OTeleporter.execute(OTeleporter.java:254)
        at com.orientechnologies.teleporter.main.OTeleporter.main(OTeleporter.java:219)

This is the conf file:

{ 
	"edges": [{
        "har_sniklass": { 
        	"mapping": { "fromTable": "BCKP_H_ORGANISATION", 
			        "fromColumns": ["H_ORGANISATION_PK"], 
                        "toTable": "BCKP_H_SNI", 
                        "toColumns": ["H_SNI_PK"], 
                        "joinTable": { 
				"tableName":"BCKP_L_ORG_SNI_RELATION", 
					"fromColumns": ["H_SNI_PK"], 							"toColumns": ["H_SNI_FK"] 
				  }, 
					"direction": "direct" }, 								"properties": { 
					"KALLA_SKAPAD_AV": { 
						"type": "STRING", 
						"mandatory": true, 
						"readOnly": false, 
						"notNull": true 
						} 
			       } 
	                    } 
		   }] 
}

## Steps to reproduce  

1) Add conf file to the command and execute

2) You get the above error immediately

**Comment by johtor2** [comment]
#7821 - same problem reported
