### ISSUE TITLE
Error in orientdb independent transaction in multiple connection of the same pool

### ISSUE THREAD

**Issue by mdre** [orientechnologies/orientdb#7930]
## Expected behavior  
A commit in independent transactions of the same pool save the data related to each one.  

## Actual behavior  
A single commit save all data from all Tx

## Steps to reproduce  
`
OrientGraphFactory fact = new OrientGraphFactory("remote:localhost/Test", "root", "toor").setupPool(1, 10);

    OrientGraph t1 = fact.getTx();
    OrientGraph t2 = fact.getTx();

    t1.addVertex("class:Test", "text","transac 1");
    t2.addVertex("class:Test", "text","transac 2");

    t1.commit();

    t2.rollback();

    t1.shutdown();
    t2.shutdown();
`
At the end, both record are added to the database, but I want only t1. Why? I think the getTx() return an independent connection to the DB but it seems they are all linked.

**Comment by tglman** [comment]
hi @mdre,

OrientDB associate the graph instance to the thread, and it use that association, so you should not use multiple graph instances on the same thread, if you really need to use two instance in the same thread you can use `graph.makeActive()` API before do an operation on the specific graph instance.

Regards
Emanuele

**Comment by mdre** [comment]
Thank's @tglman.
I will see if I can fix this in some way. What I need is to have every window bounded to it's own tx() so I can commit/rollback any change in a simple way.

Sincerely
Marcelo

**Comment by mdre** [comment]
Thank's @tglman.
I will see if I can fix this in some way. What I need is to have every window bounded to it's own tx() so I can commit/rollback any change in a simple way.

Sincerely
Marcelo

**Comment by mdre** [comment]
Thank's @tglman.

It's not clear why exist the getTx(). The way it is implemented seems not useful. If I have a pool instance is in one thread, but the Tx depend on the thread so the pools is useless. 
I will see if I can fix this in some way. What I need is to have every window bounded to it's own tx() so I can commit/rollback any change in a simple way.
Sincerely
Marcelo

**Comment by tglman** [comment]
Hi @mdre,

The pool is useful for multithread, if you have just one thread doing the operation to the database it can use everytime the same session.

Regards
