### ISSUE TITLE
Orient DB doesn't appear to scale well on multitenant applications

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7931]
### Java Version: JRE 8 

OS: Darwin ervers.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

## Expected behavior  

One would expect to be able to open many Orient DB databases, all of which would use shared thread pools. 

## Actual behavior  

Orient DB seems to create two threads per database. Orient DB WAL Flush and Orient DB Cache Flush Task. Assuming each tenant in a multitenant application has its own Orient database, if there a 1000tenants, Orient DB consume 2000 threads, eventually the machine spends too much time context switching and it grinds to a halt.

**Comment by jamieb22** [comment]
![idle_threads](https://user-images.githubusercontent.com/6212848/34015934-bbd16678-e128-11e7-958a-3fe67aa3be92.png)

**Comment by jamieb22** [comment]
Most of the OrientDB threads are not working particularly hard. It would be nice to be able to specify a shared pool.

**Comment by lvca** [comment]
@laa WDYT about having only one thread with one queue for all the databases?

**Comment by laa** [comment]
@lvca this issue fixed months ago

**Comment by lvca** [comment]
@laa which version?

**Comment by laa** [comment]
I see it was fixed for single database only. My mistake. @jamieb22 very rarely closes issues or responds on comments so I supposed that is an old issue. Yes, we have this plans to merge thread pool executors for all databases in JVM for maybe 2 years already but did not have time on that. That is the first time when somebody complains about that so that is not a high priority. Will do in 3.0.x or 3.1 I suppose.

**Comment by lvca** [comment]
Let's keep it for 3.0.x. It makes total sense to me avoiding 1 thread per database. Also because concurrent flushes slow could really block everything, but with just one thread it would be smoother.

**Comment by jamieb22** [comment]
My apologies. The problem is my Github notifications are not being received, due to the fact that Github is on the SORBS spam database. I did send an email to Github notifying them of the issue. Furthermore, I often have problems responding to your requests, because as you know, Orient DB issues often arise during production. You ask me to apply an update or change a config.. its simply impossible to do so!

>Unfortunately, we can't control how SORBS classify our email servers. We've requested to be >delisted but that may take some time. I think the best step here would be to whitelist our servers.

Let me know if you need a hand retrieving all our IP addresses!

GitHub Support

    Our mail server is rejecting traffic from Github due to presence of Git hub in spam blocl lists.

**Comment by jamieb22** [comment]
I'll leave the issue opened until it is fixed.

**Comment by jamieb22** [comment]
Thank you! I would appreciate it if you would consider refactoring Orient DB's threading model.

**Comment by mmacfadden** [comment]
We have this same issue, where each customer has their own database. We wind up with a connection pool to each database.

**Comment by jamieb22** [comment]
Andrey, any progress on this issue? Does Orient DB 3.0 address it?

**Comment by lvca** [comment]
With last OrientDB v3.0.6 we improved the usage of multiple databases under the same server. Have you already tried it?

**Comment by jamieb22** [comment]
Andrey, that's good news. I am scared to try Orient DB 3.0.6 for fear of upgradability issues and/or data corruption and instability. Is this fear unfounded?
