### ISSUE TITLE
insert speed is not stable

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7932]
### OS: CentOS

I have 2 vertex classes, and 2 edge classes between them.
 If I insert edge1 first, then insert edge2. The insert speed of edge1 is fast, about 8000/s, but the insert speed of edge2 is slow, about 2000/s. 
If I change the insert order: insert edge2 first, then insert edge1. The speed of edge2 is fast about 8000/s, the insert speed of edge2 is slow, about 2000/s.
I have enough memory and disk. I try this on 2.2.29 and 2.2.31, and I get the same result. Is there any thing wrong?

**Comment by laa** [comment]
Hi, @weickdev that is because of WAL management. But all such issues will be fixed only in 3.x versions if any. We will release RC1 next week. Could you try it and then report whether the issue is gone.

**Comment by weickdev** [comment]
@laa OK, I am trying the 3.0.0.SNAPSHORT. But in this issue, I have close WAL by set `-Dstorage.useWAL=false`

**Comment by laa** [comment]
anyway, all performance issue will be targeted in 3.0. so I ask you to try 3.0 first.

**Comment by weickdev** [comment]
@laa the insert speed is stable in 3.0, thanks!
