### ISSUE TITLE
SQLUpdateTest.updateIncrement result of update and subsequent select are different

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7939]
In SQLUpdateTest#updateIncrement test values returned as result of update command are different than results returned by the subsequent select command. Despite the fact that not modification commands were executed.

Printed error is ` SQLUpdateTest.updateIncrement:341 expected [502.1] but found [502.0999]`

**Comment by luigidellaquila** [comment]
This could be a problem with number conversion (from fixed to floating point). I'll check it.
Anyway, UPDATE INCREMENT is deprecated, we have `+=` now

Thanks

Luigi
