### ISSUE TITLE
massive insert slow down if WAL is opened

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7942]
### OS: CentOS  

If I close the WAL, the edge inserting speed is 8000 items/s, and the speed is stable.
If I open the WAL, the edge inserting speed is 6000 items/s at beginning, but after a long time, the speed slow down to 3000 items/s. 
I have enough disk and memory, and I separate the directory of database and WAL.

**Comment by laa** [comment]
That is interesting to find the reason, I do not promise that we will analyze this issue at once. But we certainly do.
