### ISSUE TITLE
SQL command 'LIKE' runs super slow

### ISSUE THREAD

**Issue by blueAnger** [orientechnologies/orientdb#7943]
### OS: <CentOS 7>  

on the orientdb studio, I ran two SQL command, something like:

- select name from Company where name like 'example%' limit 300
- select name from Company where name >= 'example' and name < 'examplf' limit 300

Here's some background information:
1. The target class contains 3,496,495 records
2. there is a unique sbtree index of 'name' field
3. The 'limit' sub-command doesn't matters. If I remove it, the total result size is 121

## Expected behavior  
The two SQL command executions get the same resultset and cost basically same time. Hopefully all run fast. 
## Actual behavior  
They all get the same resultset. The difference is executing speed. The first one runs super slow, it took 24.426s. While the second one runs fast enough, only costs 0.034s

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

Thank you for pointing it out, this is already scheduled as an optimization. It will likely be released in next weeks

Thanks

Luigi
