### ISSUE TITLE
Can I only cache vertex data

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7945]
### OS: CentOS

I have 128G memory. It can cache all the Vertices, but can't cache all edges. When I insert massive edges, if the memroy is not enough, the insert speed is slow because of the slow select of vertex. 
At this time, there is many majflt and read operation of disk, I think the new inserted edges take the memory, and the vertices are kicked out from the cache.
I find the document said that:

> Graph Database, by default, caches the most used elements. For massive insertion is strongly suggested to disable cache to avoid to keep all the element in memory. Massive Insert Intent automatically sets it to false.

So I try the `declareIntent( new OIntentMassiveInsert() )` when I insert edges, but the result is the same.
So how can I only cache vertex when I insert massive edges?

**Comment by laa** [comment]
sorry but that is not supported for now
