### ISSUE TITLE
performance dropping significantly when adding 3rd node to cluster

### ISSUE THREAD

**Issue by margaritagk** [orientechnologies/orientdb#7953]
## Expected behavior  
We are running with a master/master configuration, currently on two nodes.  We expect that when adding a 3rd node, the performance will improve.

## Actual behavior  
When we add a 3rd node, the performance decreases substantially.
The application is processing a queue, we see the queue processing dropping to  2 messages/sec when adding a 3rd node.  The queue processing is ~60 messages/sec when using 2 nodes.

## Steps to reproduce  
<add here>

**Comment by lvca** [comment]
What distributed settings do you have? Please post here your `distributed-db-config.json` file content under your database directory.

**Comment by margaritagk** [comment]
Here is the file, it's the default one, for 2 nodes, as we are currently running with 2 nodes.

[orientDB_distributed-db-config.json.txt](https://github.com/orientechnologies/orientdb/files/1575945/orientDB_distributed-db-config.json.txt)

**Comment by lvca** [comment]
@margaritagk the config file looks good to me. With writeQuorum = majority the 3rd node is not required for the quorum, so performance should be pretty much the same. Of course, you have 1+ node to replicate, but if you schedule a round-robin policy on the client, you should benefit in speed by using the 3rd node.
