### ISSUE TITLE
[Question]Does `ORDER BY` syntax support function?

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#7954]
For example I have a large IP  table or something with version, and I need to sort then with special rule.

So is there any way to define a function for `ORDER BY` syntax?

**Comment by lightjiao** [comment]
I have a way to do this.
```
select *, ip_to_int(ip) as int_ip from v_ip order by int_ip
```
but .... this is too slow

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

Probably this is slow just because of the large number of records you are fetching.
How is `ip_to_int()` implemented? Is it a JS function?

Could you please also add some numbers? eg. how many records do you have? how long does it take?

Thanks

Luigi
