### ISSUE TITLE
SQL query statement about 'join to link'

### ISSUE THREAD

**Issue by shushengxing** [orientechnologies/orientdb#7956]
### OS: centOS7

JOIN in relational database :
select * from Employee A, City B where A.city = B.id  and B.name = 'Rome'
In OrientDB, it transforms to :
select * from Employee where city.name = 'Rome'

But, when I do this in this way, I can't query data. The database is 'Open beer database' mentioned in the learn documentation.

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

Could you please post the exact query that doesn't work on OpenBeer db? `Employee` and `City` are not in that schema...

Thanks

Luigi

**Comment by shushengxing** [comment]
Thanks.
The SQL statement is :
select * from Beer where brewery_id.name = 'Brouwerij Alken-Maes' ;
There is a link - HasBrewery, and has beers.brewery_id = breweries.id .
But, no data display.

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

the breweryId is just a numeric ID, the relationship is represented by the HasBrewery edge.

The right query is as follows:
```
select * from Beer where out("HasBrewery")[0].name = 'Brouwerij Alken-Maes' ;
```
Anyway, this query is not optimal, my suggestion is to replace it with the following one:

```
select expand(in("HasBrewery")) from Brewery where name = 'Brouwerij Alken-Maes' ;
```

As you can see, the result is the same, but the performance is about 10x better (and the DB is definitely small, with big databases you will have much more significant difference)

Thanks

Luigi

**Comment by shushengxing** [comment]
@luigidellaquila , I see.
Thanks very much .

**Comment by shushengxing** [comment]
Hi, @luigidellaquila .
I have a question now. The two SQL statement you mentioned above, one is out(), and another is in(). 
They all use the link "HasBrewery", why the second one has better performance?

Thanks.

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

The first query fetches all the beers (that are a lot), then for each beer it traverses the "HasBrewery" relationship and filters based on its name, so it loads a lot of vertices.

The second query just loads the breweries, that are much fewer, finds the right one and then fetches only the connected beers, this is why its performance is better

Thanks

Luigi

**Comment by shushengxing** [comment]
I see, this depends on the amount of beers' and breweries' data.
So, it should choose the class with less data.

Thanks very much, @luigidellaquila .

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

I guess I can close this issue, please feel free to re-open if you have any further doubts

Thanks

Luigi
