### ISSUE TITLE
executing same traverse SQL using graph api and document api gets different results

### ISSUE THREAD

**Issue by blueAnger** [orientechnologies/orientdb#7957]
### OS: <CentOS 7>  

I have two methods, one using graph api to execute a sql command and the second one using document api.

```java
public ExecutionResult graphQuery(String dbUrl, String sql, boolean displayResult, Object... args)
    {
        OrientGraphFactory factory = new OrientGraphFactory(dbUrl, "admin", "admin").setupPool(1, 40);
        OrientGraphNoTx graphNoTx = factory.getNoTx();
        long start = System.currentTimeMillis();
        OrientDynaElementIterable iterable = graphNoTx.command(new OCommandSQL(sql)).execute(args);
        LOGGER.info("sql: {}", sql);
        long time = System.currentTimeMillis() - start;
        LOGGER.info("time: {}", time);
        List<Map<String, Object>> resultList = displayResult ? new ArrayList<>() : null;
        long cnt = 0L;
        for (Object obj : iterable)
        {
            OrientElement element = (OrientElement) obj;
            Map<String, Object> properties = element.getProperties();
//            LOGGER.info("properties: {}", properties);
            if(displayResult) resultList.add(properties);
            ++cnt;
        }
        graphNoTx.shutdown();
        factory.close();
        LOGGER.info("total: {}", cnt);
        return new ExecutionResult<>(time, 0, "success", cnt, resultList);
    }
``` 

```java
public ExecutionResult documentQuery(String url, String db, String sql, Object... args)
    {
        OrientDB orientDB = new OrientDB(url, OrientDBConfig.defaultConfig());
        ODatabaseSession session = orientDB.open(db, "admin", "admin");
        LOGGER.info("sql: {}", sql);
        long start = System.currentTimeMillis();
        OResultSet resultSet = session.query(sql, args);
        long time = System.currentTimeMillis() - start;
        LOGGER.info("time: {}", time);
        long cnt = 0L;
        while (resultSet.hasNext())
        {
//            LOGGER.info(resultSet.next().toJSON());
            resultSet.next();
            ++cnt;
        }
        LOGGER.info("total: {}", cnt);
        session.close();
        orientDB.close();
        return new ExecutionResult<>(time, 0, "success", cnt, null);
    }
```

FYI, I use spring boot and there are some encapsulations, but to get things straight, I show the code as above.

When I execute a sql such as: 

```
traverse * from (select from Company where name = 'example') maxdepth 11
```

the problem is, when the 'maxdepth' is a small integer like 1 or 2 or 3, the two methods get the same resultset. But when it comes to bigger integer such as 11 or 12, they don't get same resultsets. For example, the first method returns 21019 records while the second method returns only 15340 records.

I also try the sql through orientdb-self-provided web page and ${ORIENTDB_HOME}/bin/console.sh, it turns out the second method documentQuery() returns the right resultset.

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

in the first case you are using the legacy SQL API, in the second case you are using the new one.

Actually the queries are executed on the same layer (the graph DB delegates to the document DB for query execution), but you are using two different query executors.

The fact that the second query returns the correct result is good, it means that the new executor is already more robust than the old one.

The new Document API also has support for graph concepts (you will find `newVertex()`, `newEdge()` and other graph methods on ODatabaseSession), my advice is to rely on that interface for your future development.

As an alternative, you can use OrientDB Gremlin distribution, that has TinkerPop3 support and relies on the new SQL executor.

Thanks

Luigi

**Comment by blueAnger** [comment]
Hi @luigidellaquila 
Thanks for your explanation. Glad to see document-oriented and graph-oriented operations in the one interface. Nice work.
