### ISSUE TITLE
The method close() from ODatabaseImportRemote.java is empty/not implemented.

### ISSUE THREAD

**Issue by acuciureanu** [orientechnologies/orientdb#7959]
Noticed that the method close() from ODatabaseImportRemote.java is not implemented.

https://github.com/orientechnologies/orientdb/blob/afba2a82a1e6cafa13e2c02006e74d17c5bd551b/client/src/main/java/com/orientechnologies/orient/client/remote/ODatabaseImportRemote.java#L53

This close() method is called by the method importDatabase() from OConsoleDatabaseApp.java 

https://github.com/orientechnologies/orientdb/blob/57343fc311daecd1d081c688d4df7260a926b8ba/tools/src/main/java/com/orientechnologies/orient/console/OConsoleDatabaseApp.java#L2110

**Comment by tglman** [comment]
Hi @acuciureanu,

I think this is done to guarantee the same API structure of remote and embedded importer, but yes probably there is no meaning to call that from the console, thanks for reporting this.

Regards
