### ISSUE TITLE
Why cannot the OrientDB be resolved to my app?

### ISSUE THREAD

**Issue by zxnblake** [orientechnologies/orientdb#7960]
### OS: windows

I am trying the user guide provided in the documentation for v3.0. After I added the dependency of orientdb-client to my pom.xml, and copied the code to my class:
        OrientDB orient = new OrientDB("remote:localhost", OrientDBConfig.defaultConfig());
The OrientDB cannot be resolved in my first app class. I checked the orientdb-client-3.0.0m2.jar, and cannot find the OrientDB class at all. 

Anyone can help?

**Comment by maggiolo00** [comment]
Hi @zxnblake 

The class OrientDB is in the core. You should include orientdb-core as well

Thanks

**Comment by luigidellaquila** [comment]
Hi @zxnblake 

Are you using maven or another dependency manager? Or are you adding the JAR files manually?
In this latter case, you also have to add at least orientdb-core.jar, but probably you will also need other JAR files 

Thanks

Luigi

**Comment by zxnblake** [comment]
Thank you 2, @maggiolo00 and @luigidellaquila : 
Yes, I'm using maven dependency. Of course I added the orientdb-core to my pom file, as follows.
    <dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orientdb-client</artifactId>
        <version>3.0.0m2</version>
    </dependency>
    <dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orientdb-core</artifactId>
        <version>3.0.0m2</version>
    </dependency>
But when I open the pom.xml file within the orientdb-core-3.0.0m2.jar, it is empty! I think that's probably why I cannot import the class from the orientdb-core-3.0.0m2.jar. Can you give some instructions?

**Comment by zxnblake** [comment]
To update: 
I changed my repository and re-added the dependency, and then the issue is gone.
