### ISSUE TITLE
Truncate

### ISSUE THREAD

**Issue by bobinka** [orientechnologies/orientdb#7961]
## Expected behavior  
![normal](https://user-images.githubusercontent.com/34740749/34254731-3b1eca1a-e66f-11e7-8199-d06ccf4b6ab1.png)

## Actual behavior  
Requests made on the WebStudio clip data up to 10 characters. A query executed in the console.sh produces the correct data. In the backup file obtained through exporting the database in WebStudio, the data is also truncated. What configuration can be responsible for this behavior?
![fail](https://user-images.githubusercontent.com/34740749/34254735-40cb1d24-e66f-11e7-9756-3454fc4ab2a4.png)

**Comment by luigidellaquila** [comment]
Hi @bobinka 

A couple of things:

- could you please upgrade to 2.2.31 and try it? 2.2.19 is quite old...
- any chance to have your dataset to test it?

Thanks

Luigi

**Comment by bobinka** [comment]
The database with third-party application. The reason was the plugin in orientdb-community-2.2.19/plugins. I removed it and got the correct result.

Thanks.

**Comment by luigidellaquila** [comment]
Great, I guess I can close this issue then

Thanks

Luigi
