### ISSUE TITLE
oriendb rest api

### ISSUE THREAD

**Issue by gusnips** [orientechnologies/orientdb#7963]
hey, just wanted you guys to know that I'm working on a rest driver
https://github.com/gusnips/node-oriendb-rest-api
it's working fine so far, no bugs
it also doesn`t depend on node, works in the browser or any browser-like enviroments/webviews, such as electron or react-native
I'm planning to change it to work on 3.0 as soon as it's stable

Just wanted to let you know, in case it interests you

**Comment by luigidellaquila** [comment]
Hi @gusnips 

Thank you very much for letting us know, it's definitely interesting.
Please let us know how it proceeds and if you need help on it.

Thanks

Luigi
