### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by doribd** [orientechnologies/orientdb#7964]
On the main page it seems that the license is Apache License 2, while in your license file it said 
differently. 
What is the exact license ?

**Comment by lvca** [comment]
What does say the license file?

**Comment by luigidellaquila** [comment]
Hi @doribd 

Could you please point us to the files/resources you are referring to? The license for OrientDB Community Edition is Apache 2.0

Thanks

Luigi

**Comment by doribd** [comment]
hi @luigidellaquila 

I looked for that once again, i can't see it now, please close this issue.

Regards,
Dor

**Comment by luigidellaquila** [comment]
Great, closing then

Thanks

Luigi
