### ISSUE TITLE
SQL query statement about case ?

### ISSUE THREAD

**Issue by shushengxing** [orientechnologies/orientdb#7965]
### OS: centos7

SQL statement in about
`select
count(case when c1 = 1 then 1 else NULL end) as id1,
count(case when c2 = 2 then 1 else NULL end) as id2
from table`

In OrientDB, How to handle the 'case when' statement ?

Thanks.

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

There is no equivalent in OrientDB, but you can do something similar with an IF statement, eg.

```
SELECT sum(id1) as id1, sum(id2) as  id2 FROM (
    SELECT if(eval(" c1 = 1 "), 1 , 0) as id1, if(eval(" c2 = 2 "), 1, 0)) as id2 
    FROM table
)
```

I hope it helps

Thanks

Luigi

**Comment by shushengxing** [comment]
Oh, I see. I will try.
Thank you, @luigidellaquila .

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

I'm closing this issue, please feel free to re-open if you need further info

Thanks

Luigi
