### ISSUE TITLE
can i filter my link field?

### ISSUE THREAD

**Issue by jhonny111s** [orientechnologies/orientdb#7967]
### OS: opensuse 

I have a class category and contain a products linkmap (Product) field, when i search categories need get products but filtering, only five records or only status = true, '@rid' = ··  etc

what happen if created another class CategoryProducts instead linkmap?

I try with:
 - all categories with only five products 
select products.values()[0-4] from category  fetchplan products:1 //don't works

**Comment by luigidellaquila** [comment]
Hi @jhonny111s 

I'm not sure I got exactly what you are trying to achieve. Could you please post a simple script to populate your domain and data model?

Thanks

Luigi

**Comment by jhonny111s** [comment]
this is my query to filter products: 
select $temp as products, name, image, categories.values(), pointSales.slug from Category
 Let $keys = products.values().@rid, $temp = (select * from product where @rid in ( $keys ) and status = true limit 5)
   where status = true fetchplan products:1 image:1

**Comment by jhonny111s** [comment]
i found this query
is the best way to make te query?

select products.values()[0-5][status=true] from Category fetchplan products:1

why doesn't work: products.values()[status=true] [0-5]

**Comment by luigidellaquila** [comment]
Hi @jhonny111s 

I'd say it's a bug, I'll try to check it as soon as I can

Thanks

Luigi
