### ISSUE TITLE
How can I get graph-like results of traverse and shortestPath?

### ISSUE THREAD

**Issue by blueAnger** [orientechnologies/orientdb#7968]
### OS: <CentOS 7>  

I tried two kind of APIs, as mentioned in [issue #7957](https://github.com/orientechnologies/orientdb/issues/7957).

I also tried to use 'select $path', as mentioned in [issue #7962](https://github.com/orientechnologies/orientdb/issues/7962). 

None of those helps.

The result of traverse is a iterator or iterable. And the elements within are all vertices. The edge information are in_* and out_* properties. So I have to iterate and pick up all these information? If so,  then the orientdb traverse is not helpful because technically I am doing graph traverse by myself. If not, how can I get the graph-like result(for example, edge-set array)?

The result of the shortestPath() are a list of vertices ids. So I guess I should iterate and load them by using ODatabaseSession.load(id) ??? Same question, how do I get the edge-set array? Maybe I could go through properties of every document and filter the edges I want as well as the direction, but what's the point of the 'edgeClassName' and 'direction' parameters of shortestPath()？

In my opinion, the results are not friendly. I will appreciate that if you can show me  an example.

Thanks.

**Comment by blueAnger** [comment]
# Update
I tried the following SQL in OrientDB 2.2.31:

```
select $path from (traverse inE(), outE(), outV(), inV() from (select from Person where name = 'Person2') maxdepth 10 strategy breadth_first)
```

it got something like:

```
{
"result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "$path": "(#22:0)"
        },
        {
            "@type": "d",
            "@rid": "#-2:1",
            "@version": 0,
            "$path": "(#22:0).outE[0](#28:0)"
        },
        {
            "@type": "d",
            "@rid": "#-2:2",
            "@version": 0,
            "$path": "(#22:0).outE[0](#28:0).inV(#20:0)"
        },
        {
            "@type": "d",
            "@rid": "#-2:3",
            "@version": 0,
            "$path": "(#22:0).outE[0](#28:0).inV(#20:0).outE[0](#25:0)"
        }
]
}
```

So, does it mean I should parse every single path string and load all vertices/edges through ODatabaseSession.load(rid)?

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

Please wait, we just realized that the $path option does not work properly in the RC1 and we are having a look at it. We also would like to do some changes to make it a bit easier to manipulate

Thanks

Luigi

**Comment by blueAnger** [comment]
Hi @luigidellaquila 
That's good to know. And, um... no pressure, but roughly how long will it takes?
Thanks

**Comment by luigidellaquila** [comment]
I'm working on it now, so it should be a matter of a few hours

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

I just pushed a fix on deveop branch. Now the $path variable returns a collection of RIDs, so you can expand it and manipulate it with SQL, without the need for string parsing.

Here is an example of things you can do with it (demodb as a reference):

```
SELECT from (
   SELECT expand(p) from (
       SELECT $path as p from (
            traverse bothE(), bothV() from #33:2 maxdepth 5
       ) ORDER BY $depth DESC limit 1
   ) 
) where @this instanceof "E"
```

Thanks

Luigi

**Comment by blueAnger** [comment]
Hi @luigidellaquila 
I just tried it and it's indeed much more easier to get the traverse result. That's amazing. Thanks for your work.

**Comment by blueAnger** [comment]
Hi @luigidellaquila 
I tried the following SQL: 

```
select expand(s) from (
	select shortestPath(#153:28622, #183:112464, null, null, {"maxDepth": 10}) as s
)
```

and couldn't get the edges information. It's all vertices.

The example you gave last week was:

```
SELECT from (
   SELECT expand(p) from (
       SELECT $path as p from (
            traverse bothE(), bothV() from #33:2 maxdepth 5
       ) ORDER BY $depth DESC limit 1
   ) 
) where @this instanceof "E"
```

I believe that's one way to do it. But is it the only way for now? Can I use the shortestPath() functions to get what I want? If so, could you give me an example how to use the shortestPath() function to get edges information? If not, please let me know.

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

Currently, shortestPath() function only returns vertices, but IMHO it makes a lot of sense to have an option to get edges instead. 

I'm keeping this issue open to track this enhancement, I'll try to work on it as soon as I can.
In the meantime, if you want to have a look at current implementation, you can check this: https://github.com/orientechnologies/orientdb/blob/043f11f2bd65327bf18a3f55926bd4d8fab7e960/core/src/main/java/com/orientechnologies/orient/core/sql/functions/graph/OSQLFunctionShortestPath.java
The code is not too complex

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

I merged your PR, now it should work fine

Thanks

Luigi
