### ISSUE TITLE
db.save() many Lucene FullText Index

### ISSUE THREAD

**Issue by hosseinGanjyar** [orientechnologies/orientdb#7969]
## Expected behavior  
I wrote a function javascript for insert data to vertex with  Lucene FullText, but when I want insert data get this error:

> {
>     "error": "com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index\r\n\tDB name=\"demodb\""
> }

```
var db = orient.getDatabase();

db.begin();
try {
    var res = db.save({ '@class': 'profiles', Bio: Bio, Birthday: Birthday, Email: Email, Id: Id, Name: Name, Surname: Surname })
    db.commit();
    return res;
}
catch (err) {
    db.rollback()
    response.send(500, 'error on insert operate', 'text/plain', err.toString());
}
```
Why not available any document for samples of Functions?

**Comment by maggiolo00** [comment]
Hi @hosseinGanjyar 

are you able to reproduce this with plain SQL?

if yes can you attach here the steps to reproduce this?

Thanks

**Comment by hosseinGanjyar** [comment]
Why plain SQL?

`Insert into profiles (key) values (value)`

**Comment by maggiolo00** [comment]
Hi @hosseinGanjyar 

can you post also the schema for the class profiles and how did you define the index?

Thanks

**Comment by hosseinGanjyar** [comment]
According to this issue https://github.com/orientechnologies/orientdb/issues/7848, I solved problem with install Java version 8... 🥇 
But why? I want using java v9 and using orient... this is bug...
