### ISSUE TITLE
EXPLAIN command parameter - 'elapsed'

### ISSUE THREAD

**Issue by shushengxing** [orientechnologies/orientdb#7970]
### OS: centos7

The 'Explain' command,  it has a parameter - 'elapsed'. 
What is the unit that this parameter displays? Is it time(ms)?
And how did this parameter come out?

Thanks.

**Comment by luigidellaquila** [comment]
Hi @shushengxing 

The "elapsed" is the total query execution time, in milliseconds

Thanks

Luigi

**Comment by shushengxing** [comment]
Thanks, @luigidellaquila .
Is the actual execution time of a query statement?

**Comment by luigidellaquila** [comment]
Yes, it is

Thanks

Luigi

**Comment by shushengxing** [comment]
OK.

Thanks.
