### ISSUE TITLE
Found unexpected keyword 'GO"' while it was expected '[=]'

### ISSUE THREAD

**Issue by hosseinGanjyar** [orientechnologies/orientdb#7973]
## Expected behavior  
insert with function (javascript)

## Actual behavior  
what is this error? why? 

> OrientDB.RequestError: Error on parsing command: Found unexpected keyword 'GO"' while it was expected '[=]'

**Comment by luigidellaquila** [comment]
Hi @hosseinGanjyar 

Any idea on how to reproduce it?

Thanks

Luigi

**Comment by hosseinGanjyar** [comment]
Oooooops!
You are developer of orientdb, question of me for solve problem?!!!!!
Although I solved. I sent data with persian characters and any symbol characters, then deleted any non english characters and sent.

**Comment by luigidellaquila** [comment]
Oh, I see, so it's a charset problem (it was really hard to me to understand it from the original message...).

Could you please describe the full procedure to get this error? With a reproducer I can try to fix it

Thanks

Luigi

**Comment by hosseinGanjyar** [comment]
@luigidellaquila please send me a mail for send all of things for u...
I will put result of fix for every body here.
thanks

**Comment by luigidellaquila** [comment]
Hi @hosseinGanjyar 

Thank you very much, please send it to l.dellaquila - at - orientdb.com

Thanks

Luigi
