### ISSUE TITLE
Fetching next pages of sql queries causes NPE when querying OrientDB in distributed mode

### ISSUE THREAD

**Issue by yishchuk** [orientechnologies/orientdb#7974]
### OS: Windows 10, CentOS 7.3  

When querying for documents against database running in distributed mode, it's impossible to get data from next pages - only the first one (first 100 records).

Looks like this is related to commit c3f4d75e4197845c1d6701485e64837c99d50293 which removed registering new queries in `activeQueries` map of ODatabaseDocumentAbstract - so new queries aren't registered anymore, but still being used by `executeQueryNextPage()' method of OConnectionBinaryExecutor class.

## Expected behavior  
Query should return all results

## Actual behavior  
Query returns first 100 rows, and then fails with NPE: 
`Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQueryNextPage(OConnectionBinaryExecutor.java:1212)
	at com.orientechnologies.orient.client.remote.message.OQueryNextPageRequest.execute(OQueryNextPageRequest.java:69)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:276)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:182)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
`

## Steps to reproduce  
Issue a document query which expects more than 100 results (e.g., `orientGraphFactory.getNoTx().database().query("select from V limit 1000").stream().forEach(System.out::println);`)

**Comment by tglman** [comment]
Hi @yishchuk,

Thanks for reporting this, checking it.

Regards

**Comment by yishchuk** [comment]
@tglman, commit 0702c0e doesn't cover the problem - the server must start in distributed configuration, so `ODatabaseDocumentDistributed` database object should be used, but in the test `ODatabaseDocumentRemote` is used.

**Comment by tglman** [comment]
Hi @yishchuk,

Yep the commit was solving a similar problem in case of expired session, that give the same error, anyway that will give a meaning full error also in distributed, I'm playing around the client right now to make sure that all the operation of a session stick to a specific server when they need the status there, and fail on the client instead of try to use a different server.

Anyway `ODatabaseDocumentDistributed` is used only if you run distributed in embedded or internally to the server so in the client you have everytime `ODatabaseDocumentRemote` also if you are connecting to a distributed server.

Regards

**Comment by tglman** [comment]
Hi @yishchuk,

I add that the query and transaction stick to the same session and server, here is the commit: https://github.com/orientechnologies/orientdb/commit/e6f78a3865d4e94d95e3b849fd5082d8407eada7 this error now should be fixed.

Regards

**Comment by yishchuk** [comment]
Hi @tglman,

This looks like this is only a part of the solution - empty methods `queryStarted` and `queryClosed` should also be removed from `ODatabaseDocumentDistributed` as they prevent storing current query in `activeQueries` map (in `ODatabaseDocumentAbstract`).

Thanks

**Comment by tglman** [comment]
Hi @yishchuk,

Thank you to point that out, let me double check

**Comment by tglman** [comment]
Hi @yishchuk,

I made sure that the query is register in distributed, so now you should not have problem anymore.

Regards

**Comment by yishchuk** [comment]
Thanks @tglman, it's working now.
