### ISSUE TITLE
Enhance .values() and .keys() to deal with an array of maps

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientdb#7976]
## Expected behavior  
.values() and .keys() should support extracting elements from an array of maps, not just a single map

This: `[{"1000":"#23:0","1001":"#24:0","1002":"#23:1"},{"1003":"#24:1","1004":"#23:2"}]`
Not just this: `{"1000":"#23:0","1001":"#24:0","1002":"#23:1"}`

## Actual behavior  
.values() and .keys() on a query result that returns an array of map projections returns nothing.

## Steps to reproduce  
A query like this:
`select expand(links['2017'].links['07'].links['15'].links['10'].links) from #12:3`

Returns the actual records contained in the last layer of "links". This works exactly as expected. And adding .values() or .keys() to this query results in just the values or keys in the map projection.

But a query like this (note the 10,11 in the second to last layer of "links"):
`select expand(links['2017'].links['07'].links['15'].links['10','11'].links) from #12:3`

Returns two rows of the last layer of "links" instead:
`{"1000":"#23:0","1001":"#24:0","1002":"#23:1"}`
`{"1003":"#24:1","1004":"#23:2"}`

Using unionAll or intersect (with or without UNWIND) results in this single record:
`[{"1000":"#23:0","1001":"#24:0","1002":"#23:1"},{"1003":"#24:1","1004":"#23:2"}]`

That's good, but adding .values() or .keys() to this query results in nothing.

**Comment by luigidellaquila** [comment]
Hi @Eric24 

I just pushed a fix on both 2.2.x and develop branches, now it should work fine

Thanks

Luigi

**Comment by Eric24** [comment]
Perfect! I'll try it out when I update to the next version.
