### ISSUE TITLE
[Question] How can I query to get OVertex using new Java Multi-Model API

### ISSUE THREAD

**Issue by blueAnger** [orientechnologies/orientdb#7977]
### OS: <CentOS 7>  

According to this [documentation](http://orientdb.com/docs/3.0.x/java/Java-MultiModel-API.html), the new Java Multi-Model API is expected to be used. The given example is:

```
ODatabaseDocument db;
...
OElement d = db.newInstance("DocClass");
d.setProperty("foo", "Bar");
d.save();

OVertex v1 = db.newVertex("VertexClass");
v1.setProperty("foo", "One");
v1.save();

OVertex v2 = db.newVertex("VertexClass");
v2.setProperty("foo", "Two");
v2.save();

v1.addEdge(v2, "EdgeClass").save();

db.commit();
```

Consider this, if I already have the vertices, now I just want to add new edges. For example, I batch insert the vertices, and now I want to batch insert the edges. So I suppose I should do something like:

```
ODatabaseSession session = new ODatabasePool(url, username, password).acquire();
OVertex from = some-way-to-get-from-overtex-according-to-some-criteria;
OVertex to = some-way-to-get-to-overtex-according-to-some-criteria;
OEdge edge = session.newEdge(from, to, "edgeClass");
edge.setProperty("name", "edge1");
edge.save();
session.commit();
```

I didn't see any method in ODatabaseSession or ODatabaseDocument interface to get what I want. I supposed the candidates are session.query() and session.load(), but what I get are OResult or ODocument.

The 2.x graph API has methods like getVertex(), getVertices() to execute a query to get vertex or vertices. But since 3.0, the older graph API is deprecated and not recommend to use. Meanwhile, the vertex and edge interfaces are changed.

So my question is how to get Overtex instance. Or is there another way to get what I want?  

Thanks.

**Comment by blueAnger** [comment]
OK, I think I figured it out by myself. 

```
OResultSet resultSet = session.query(sql);
OVertex from = null;
        if (resultSet.hasNext())
        {
            OResult result = resultSet.next();
            OElement element = result.toElement();
            Optional<OVertex> optional = element.asVertex();
            if(optional.isPresent()) 
                from = optional.get();
        }
```

If there's more convenient operation, please let me know.

Thanks.

**Comment by weickdev** [comment]
@blueAnger  You can try to get edge or vertex by 
`OResult.getEdge() or OResult.getVertex()`

**Comment by blueAnger** [comment]
@weickdev Okay, that's helpful. Thanks.
