### ISSUE TITLE
unable to create classes with classnames that contain whitespaces

### ISSUE THREAD

**Issue by vaishnaviprasad** [orientechnologies/orientdb#7978]
### OrientDB Version:
Studio version : 2.1
OrientDB version : 2.1.12

### Java Version:
 Version 8 update 121
### OS: 
 windows 7 pro 64 bit

## Steps to reproduce  

create class  emp address;

This generates an erroe such as this 

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Invalid keyword: ADDRESS;

I would like to create classes with class names that contain whitespaces as the API names contain whitespaces.
I do not want to add symbols to replace the white spaces .

Please let me know of a work around to solve this.

**Comment by luigidellaquila** [comment]
Hi @vaishnaviprasad 

OrientDB v 2.1 is no longer supported, and it does not allow white spaces in class names.
I strongly suggest you to use v 2.2, or even better v 3.0 RC1 that will be released as GA in very few weeks

Thanks

Luigi

**Comment by vaishnaviprasad** [comment]
Hi @luigidellaquila 
Thank you for the reply.
Does v 2.2 support whitespaces in classnames?



Please let me know of a work around to solve the issue if v2.2 doesnt support.

**Comment by luigidellaquila** [comment]
Hi @vaishnaviprasad 

In v 2.2 we added a back-tick syntax to allow special characters (eg. dots) in class names, but white spaces are still not supported.

V 3.0 has full support for it

Thanks

Luigi

**Comment by vaishnaviprasad** [comment]
Hey @luigidellaquila ,

I wanted to know about property names in a class.
I would like to have property names with white spaces  and /or special characters.
is this possible?


Thanks,
Vaish

**Comment by luigidellaquila** [comment]
Hi @vaishnaviprasad 

It's the same for property names, in v 2.2 you can use special characters like dots (using back-ticks), in v 3.0 you can use any character, even white spaces

Thanks

Luigi

**Comment by vaishnaviprasad** [comment]
Hi @luigidellaquila ,

How can I configure v2.2  so that white spaces are supported?

**Comment by luigidellaquila** [comment]
Hi @vaishnaviprasad 

Sorry, my last comment was not clear, in 2.2 you can use special characters but not white spaces, there is no way to configure it

Thanks

Luigi

**Comment by vaishnaviprasad** [comment]
Hi @luigidellaquila ,
When is v3 going to be out?

Thanks,
vaishnavi

**Comment by luigidellaquila** [comment]
There is no fixed date yet, but I'd say two or three weeks at most

Thanks

Luigi
