### ISSUE TITLE
[Question]`IS DEFINED` syntax cannot use in 3.0?

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#7979]
### OS: centos 6.8

login the demodb
execute the sql below
```select from v where id is defined```

## Expected behavior  
get the data where id is defined

## Actual behavior  
get an exception
```
{
  "errors": [
    {
      "reason": 501,
      "code": 501,
      "content": "java.lang.UnsupportedOperationException: TODO Implement IS DEFINED!!!"
    }
  ]
}
```

so, `IS DEFINED` syntax cannot use in 3.0? it's an import feature for me, and 2.2.x have it

**Comment by luigidellaquila** [comment]
Oh... definitely a TODO for the GA! I'm on it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

I just pushed a fix, now it should work fine

Thanks

Luigi

**Comment by lightjiao** [comment]
Thank you very much 👍 
And when this fix will be release ?

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

It will be in the final 3.0.0 GA release, it will be out before the end of January

Thanks

Luigi

**Comment by lightjiao** [comment]
I am very happy(?) to hear this 😄
