### ISSUE TITLE
OCommandExecutionException: Cannot invoke traversedVertex() against non traverse command

### ISSUE THREAD

**Issue by blueAnger** [orientechnologies/orientdb#7984]
### OS: <CentOS 7>  

I ran a SQL on OrientDB Studio,

```
SELECT traversedVertex(0, 100) from(
    traverse bothE(), bothV() from (select from Company where name = 'example') maxdepth 1 strategy breadth_first
)
```

## Expected behavior  
successfully returns traversed vertices

## Actual behavior  
It throwed an exception as follows

```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot invoke traversedVertex() against non traverse command
```

However, I tried the same SQL in 2.2.31 orientdb, it worked fine.

## Steps to reproduce  
just try a similar SQL in Orient Studio or through bin/console.sh

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

Thank you very much for reporting this, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

I just pushed a fix, now it should work fine

Thanks

Luigi
