### ISSUE TITLE
[question] Dose V3.0 can guarantee the unique in distributed mode?

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7988]
As the document says, in V2.2.x, ODB doesn't guarantee a key to be unique in Distributed Mode:

> Sharded Indexes are not supported yet, so creating a UNIQUE index against a sharded class doesn't guarantee a key to be unique. This will be addressed with Auto-sharding in the further releases.

do you fix this in V3.0?

http://orientdb.com/docs/3.0.x/distributed/Distributed-Architecture.html

**Comment by tglman** [comment]
Hi @weickdev,

Yes 3.0 guarantee unique index in distributed making the transaction with unique index changes inside use quorum all instead of majority.

Regards

**Comment by ccassar** [comment]
The documentation for 3.0 does not seem to reflect this:
https://orientdb.com/docs/3.0.x/distributed/Distributed-Sharding.html#limitation
Is this just an issue with documentation, or is there more?
