### ISSUE TITLE
Getting Error "Cannot open storage it is acquired by other process" while connecting to plocal

### ISSUE THREAD

**Issue by vigneshsenapathy** [orientechnologies/orientdb#7995]
## Expected behavior  
It should connect to the local storage.

## Actual behavior  
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open storage it is acquired by other process
## Steps to reproduce  
1. Do automatic back on the instance
2. I copied that zip file into a different docker image which has orientdb running
3. Run /orientdb/bin/console.sh "connect plocal:/orientdb/databases/testing root ${ORIENTDB_ROOT_PASSWORD}"
4. Ran the above command and got : Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open storage it is acquired by other process
5. Cannot connect to plocal in a distributed system. I have 2 nodes running and it doesnt allow me to even login

**Comment by laa** [comment]
Hi, this message means that you read database which is opened in another process you can not do that.

**Comment by vigneshsenapathy** [comment]
@laa : how can i connect to the localdatabase then? all i have is a java process connecting to the DB and i want to restore it when it is still connected. Is it possible to do that?

**Comment by eegiimgl** [comment]
This error `Cannot open storage it is acquired by other process` has been happening to me always for all version. Even i restarted orient instance. It seems after I restart db instance, then when I I am entering by not root admin user like `admin` as default created, i was successfully logged in via console.

**Comment by tglman** [comment]
Hi @vigneshsenapathy, @eegiimgl,

If you are connecting with plocal you get everytime exclusive access to the folder of the database and no-one else can access that folder till the previous process do not exit, so if you connect with console as plocal you cannot access the same database from the server (that use plocal) and on the same way if you have a server running you cannot access is databases with the console in plocal (just use remote).

Regards
