### ISSUE TITLE
Cannot restore DB using plocal

### ISSUE THREAD

**Issue by vigneshsenapathy** [orientechnologies/orientdb#7996]
## Expected behavior  
Should be able to restore  

## Actual behavior  
Not able to restore. getting error  

## Steps to reproduce  
1. Start a orientdb
2. Set up automatic backup
3. Get that file and try to restore that in a different environment which you just started up.
4. Command : /orientdb/bin/console.sh "connect plocal:/orientdb/databases/testing root ${ORIENTDB_ROOT_PASSWORD};RESTORE DATABASE /orientdb/testing.zip"  
When i run this i cant connect to to the DB using plocal and restore it. This is a blocker for me as i want a solution for restoring locally.

**Comment by laa** [comment]
he what do you mean by you cannot restore. Do you have any exception of what?

**Comment by vigneshsenapathy** [comment]
@laa : this is what i get when i run the above command

Connecting to database [plocal:/orientdb/databases/testing] with user 'root'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/orientdb/databases/testing' with mode=rw
	DB name="testing"

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open storage it is acquired by other process
	DB name="testing"

It cant connect to the local database to do restores. I thought restores in community edition is supposed to be done on the box and cannot be done remote

**Comment by laa** [comment]
it means that you open the same storage from two different processes you can not do that.

**Comment by vigneshsenapathy** [comment]
@laa : what is the way of restoring a DB then? can you let me know. I have to connect to the DB to do a restore.

**Comment by laa** [comment]
@vigneshsenapathy you should put your backup on a server and restore the database using the same command using a remote connection.

**Comment by vigneshsenapathy** [comment]
@laa : i have the back on a server and i have the community edition. It doesnt allow me to do remote connection. There should be a way to restore without running into this right?

**Comment by vigneshsenapathy** [comment]
@laa : any suggestion on how i can fix this?

**Comment by laa** [comment]
@vigneshsenapathy in such case the only way to do that is to create a database using a "plocal:" connection restore data locally and then copy the folder to the server.
