### ISSUE TITLE
UnsupportedOperationException: Execution of select in parentheses is not supported

### ISSUE THREAD

**Issue by blueAnger** [orientechnologies/orientdb#7997]
### OS: <CentOS 7>  

I ran a SQL in orientdb studio and bin/console.sh

```
select shortestPath(
  (select from table1 where name = 'exampleName'),
  (select from table2 where _key = 'exampleKey'),
  null,
  null,
  {'maxDepth':10}
)
```

## Expected behavior  
successfully returns the shortest path

## Actual behavior  
It throwed an exception as follows

```
Error: java.lang.UnsupportedOperationException: Execution of select in parentheses is not supported
```

FYI, it works fine in 2.2.31 orientdb
## Steps to reproduce  
just try the SQL in orientdb studio or through bin/console.sh

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

I just pushed a fix for this, it will be released with the 3.0.0 GA

Thanks

Luigi
