### ISSUE TITLE
count function doesn't work on DateTime

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7999]
### OS: CentOS

If I run sql `select count(*) from Person where name='hello'`, where name is a String, I can get the result. But if I run sql `select count(*) from Person where ctime='2018-01-12 15:33:12'`, where ctime is a DateTime, I can't get any result.

**Comment by luigidellaquila** [comment]
Hi @weickdev 

Probably the problem here is with milliseconds. I guess the `ctime` doesn't match the condition because it has milliseconds different from 000

Thanks

Luigi

**Comment by weickdev** [comment]
@luigidellaquila Yes, you are right. Now I can do it with:
```
select count(*) from Person where ctime.asString()='Fri Jan 12 16:22:36 CST 2018'
```
or
```
select count(*) from Person where ctime.asLong()>=1515745356000 and ctime.asLong()<1515745357000
```
Thanks!
