### ISSUE TITLE
CREATE EDGE ... CONTENT doesn't work

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#8000]
### OS: CentOS
 If create a edge use this sql:
```
CREATE EDGE invest1 FROM (SELECT FROM Person WHERE _key="5fdaac8bdd1bb190149926974433a3be") TO (SELECT FROM Company WHERE _key="680d0edb49b9792456c7a1045f446e19") CONTENT { "name": "Jay", "surname": "Miner" }
```
then the values are missing. Then I use this sql:
```
CREATE EDGE invest1 FROM (SELECT FROM Person WHERE _key="5fdaac8bdd1bb190149926974433a3be") TO (SELECT FROM Company WHERE _key="680d0edb49b9792456c7a1045f446e19") SET brand = 'fiat', name = 'wow'
```
It works well. Below is the select result of them.
```
+----+--------+-------+----------+----------+-----+----+
|#   |@RID    |@CLASS |out       |in        |brand|name|
+----+--------+-------+----------+----------+-----+----+
|0   |#66:5000|invest1|#30:123233|#28:193011|fiat |wow |
|1   |#67:5000|invest1|#30:123233|#28:193011|     |    |
+----+--------+-------+----------+----------+-----+----+
```

**Comment by luigidellaquila** [comment]
Hi @weickdev 

Which version? 3.0 RC1?

Thanks

Luigi

**Comment by weickdev** [comment]
@luigidellaquila Sorry I forgot the version. It is 3.0.0-SNAPSHOT

**Comment by weickdev** [comment]
@luigidellaquila I find the process logical in `UpdateContentStep` class, it only handles the ODocument. But  Vertex and Edge aren't ODocument. So I change it. It works well now, but I am not sure if it is right. [Please check it](https://github.com/weickdev/orientdb/commit/d7a5c96d99888240cec3e5297bf07731732c7e89), thanks.

**Comment by luigidellaquila** [comment]
Hi @weickdev 

Thank you very much, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @weickdev 

I did the fix on a slightly different way (actually, it made more sense to refactor it and use OElement instead of ODocument) and pushed it. Now it should be OK

Thanks

Luigi
