### ISSUE TITLE
DROP INDEX succeeds even with invalid index name

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#8007]
## Expected behavior  
The following command should either produce an error, or return a `value` of `0` since no index was dropped:
```
DROP INDEX DefinitelyDoesNotExist
```

## Actual behavior  
The above command returns `value: 1`, the same as if an index was actually dropped.

## Steps to reproduce  
Just run the above command.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I just pushed a fix, now the DROP INDEX statement returns zero if no indexes were dropped.

Thanks

Luigi
