### ISSUE TITLE
Custom cluster selection strategy is not working in distributed environment.

### ISSUE THREAD

**Issue by FelisChaus** [orientechnologies/orientdb#8010]
## Expected behavior  
On both single-node and multi-node configurations OrientDB has to: 
1. ALTER CLASS some_class CLUSTERSELECTION custom_strategy
   should alter the class and new cluster selection should be visible in console after
   execution INFO CLASS some_class command.
2. Corresponding getCluster(...) should be invoked on INSERT. 

## Actual behavior  
ALTER CLASS works as expected on both single-node and multi-node configurations.
getCluster() invokation performs only on single-node configuration where it works as expected.
On multi-node configuration the method is not called.

## Steps to reproduce  
Custom cluster selection strategy class created according to [Custom Cluster Selection Strategies](http://orientdb.com/docs/last/Cluster-Selection.html)

## Question
May be there are additional requirements for distributed environment omitted in documentation?

Thank you in advance.

**Comment by FelisChaus** [comment]
More than a month in a full silence. I told with your help desk. I told with your sales representative. Zero effect. Seems it is a time to raise a question inside company to throw out your enterprise licence and move to more appropriate solution. This database is too unstable both on production and support dimensions.

**Comment by tglman** [comment]
Hi @FelisChaus,

Sorry this slipped through the cracks, anyway this issue tracker is for community support, feel free to ask our support to get the access to the support tools for the clients.

Checking this now anyway.

Regards

**Comment by tglman** [comment]
Hi @FelisChaus,

Just as double check did you deploy the custom class for the selection strategy in all the nodes ?

Regards

**Comment by FelisChaus** [comment]
Hi,

yes, of course, on all nodes.

Regards

**Comment by tglman** [comment]
Hi @FelisChaus,

I tried to reproduce the problem anyway I couldn't, I'm not sure though if I understood your problem and if expect a different behavior, as today the cluster selection strategy (on OrientDB 2.2.33) it work correctly but it's called only one in the node that coordinate the transaction, is this what you expect ?

Regards

**Comment by FelisChaus** [comment]
Hi @tglman,

I moved to version 2.2.33, and yes, the cluster selection now is working. But now I am sustainable receiving the following exception:

com.orientechnologies.orient.server.distributed.ODistributedException: Error on creating cluster 'tenantdata_local' on distributed nodes: local and remote ids assigned are different

        final String tenantPrefix = "tenantdata";
        final int tenantId = 1001;
        ...
        String clusterNameMaster = tenantPrefix + "_local";
        String clusterNameTenant = tenantPrefix + "_" + tenantId;
        OSchemaProxy schema = db.getMetadata().getSchema();
        int id[] = new int[2];
        **id[0] = db.addCluster(clusterNameMaster);** // From this line of code.
        id[0] = db.addCluster(clusterNameTenant);
        OClass test = schema.createClass(tenantPrefix, id);

I tried different distributed-config.json configuration and was playing between 2 and 3 nodes and for now have no idea how to escape the situation.

Regards.

**Comment by tglman** [comment]
Hi @FelisChaus,

This should not happen with the last release, but if any case you are in this state from previous releases, you can keep the database on a node where you are confident has the right full data and let orientdb resync all the data doing the shutdown of the  other nodes and removing the database from that nodes before restart.

Regards
