### ISSUE TITLE
OScriptDatabaseWrapper is missing useful methods

### ISSUE THREAD

**Issue by metametametameta** [orientechnologies/orientdb#8018]
## Expected behavior  

When using server-side Javascript functions in 3.0 , there is an implicit variable called db (see https://github.com/orientechnologies/orientdb/blob/3.0.0RC1/core/src/test/resources/fixtures/scriptTest.js)

db is a an instance of the OScriptDatabaseWrapper class and appears to be the recommended way to interact with the db within a JavaScript server-side function. However, if you look at the old 2.x style class called OScriptDocumentDatabaseWrapper (deprecated in 3.0), you'll notice that the OScriptDatabaseWrapper  has fewer methods. For instance, I'm unable to called begin(), rollback(), and commit() on OScriptDatabaseWrapper. It makes sense to add these three methods (and other methods from the underlying database API that would be considered useful).

## Actual behavior  

OScriptDatabaseWrapper is missing useful methods - and provides only a subset of the underlying database API.

## Steps to reproduce  

See Javadoc for OScriptDatabaseWrapper and OScriptDocumentDatabaseWrapper   for comparison of the methods available.

**Comment by luigidellaquila** [comment]
+1 I'm flagging it as an enhancement, we'll work on it right after 3.0.0 (too late for to include it in the first GA)

Thanks

Luigi

**Comment by metametametameta** [comment]
Ok, thanks! We have a workaround for now. We happen to have a Java hook configured on the server. So I was able to add a static method to the hook class such as:

```java
public synchronized static void commit() {
  ODatabaseDocument g  = (ODatabaseDocument) ODatabaseRecordThreadLocal.instance().get();
  g.commit();
}
```

and was able to call it from the javascript function using

myPkg.HookClassName.commit();

The same trick could be applied to any missing method as a temporary workaround to the missing methods.

**Comment by metametametameta** [comment]
Exposing the .load(...) methods on OScriptDatabaseWrapper would also be important, otherwise there's no quick way to load an object based on its ORID within the Javascript. Running a query such as "select from rid" and doing a next() on the result set appears to be a lot slower than a direct db.load(...)
