### ISSUE TITLE
OSQLAsynchQuery and OSQLNonBlockingQuery not usable via 3.0 APIs

### ISSUE THREAD

**Issue by metametametameta** [orientechnologies/orientdb#8019]
## Expected behavior  

In 2.x, as described at http://orientdb.com/docs/last/Document-API-Documents.html, it's easy enough to use OSQLAsynchQuery  and OSQLNonBlockingQuery  by using the older db.command(...) API.

However, in 3.0 the older db.command(...) methods which take in command objects are deprecated. As far as I can tell, the multi-model APIs for issuing queries always take in strings, so it's not clear how to use OSQLAsynchQuery  and OSQLNonBlockingQuery  using the new 3.0 APIs.

## Actual behavior  

There seems to be no way to use OSQLAsynchQuery   and OSQLNonBlockingQuery   in 3.0 without resorting to deprecated methods. 

## Steps to reproduce  

See javadoc for Interface _ODatabase<T>_

**Comment by GaetanGiraud** [comment]
Any news on this one? 

While using the deprecated methods seem to be working, I would rather not rely on deprecated methods, as they are surely deprecated for a reason ....
