### ISSUE TITLE
SQL statements for database information [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#802]
My idea was to create a virtual database information schema which can be queried to get the information requested (such as the database size).

ML: https://groups.google.com/forum/?hl=en&fromgroups#!topic/orient-database/XsIX1Eu-D6w

**Comment by luigidellaquila** [comment]
Fixed in 3.0 with two new SQL targets:

```
SELECT FROM metadata:database

SELECT FROM metadata:storage
`

Closing, thanks

Luigi
