### ISSUE TITLE
Cannot get Vertex if we exclude edges, can improve performance.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8036]
### OS: Centos

Hi,

Assuming there is an OResult from a query.. this code should get a vertex

result.next().getVertex().get()

however, it only works if you select * from table.

if you Select *:{!out_*, !in_*} from table then getVertex will fail.  

Assuming that there is no bug here as it's required by the system for a proper Vertex, wouldn't it make sense to have a way to fetch an incomplete vertex in some cases when you are only dealing with updating records such as user information for example. it seems to me that fetching the edge links (even if we don't fetch the data for those edges) is an overhead.

Regards,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

A nested projection is indeed a projection, so it's not a vertex, this is why getVertex() is failing.

You could not work with partial data anyway, ie. you cannot modify and save a partial vertex, so it makes no sense in general to have it as a vertex.

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila,

It's quite tricky then.  Lets say that you have a user's record with a bunch of edges out and in (as you would expect from a user's record) and you want to simply update his name.  Isn't it fetching too much data for that simple action?  

I suppose SQL update wouldn't be any better as I guess it'll be doing the same behind the scene as well.  

It's alright I guess when it's embedded app. but when you have a remote connection, it seems like a lot of overhead.  Is it a concern at all?

Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

Doing it in SQL you will save all the network communication, so for sure it will be faster.

Unfortunately there is no work-around for now, if you want to update a vertex you have to load it fully

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila,

So SQL does the same behind the scene then.  I have been thinking about another approach but not sure if it's smart.  How about a plugin that is loaded by the database and would receive a REST request to execute the update? 

That should reduce the network traffic.  Would it behave in the same as an embedded app or there is an overhead? and then the only risk is if it affects database performance.

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

It would be exactly the same as for SQL, so no big advantage

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila 

Right. Problem is I got rid of all my SQL (except for selecting) to work with vertex (maybe I shouldn't have).  that's why I'm suggesting a plugin where I put my Java code.  Ok. The question that's lingering for me.

Is a plugin that executes code the same (or close) to embedded? 

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Yes, it is. A plug-in is at the exact same level of an embedded db connection

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Thanks for that.  I'll venture more into plugins at some point.

Thanks
