### ISSUE TITLE
3.0 different behavior saving records when using .save() and not.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8039]
### OS: Centos

Hi,

in a previous email, I mentioned that save() was required on a new record or the transaction will fail.  However, if we fetch an existing record, make changes  to it and not call save(), it'll commit other changes without exception. It seems that a new record will throw an exception but a pending record wouldn't.

        ORID theRid = new ORecordId("#29:34");
        OElement doc = db.load(theRid);
        OVertex safwan = doc.asVertex().get();

        safwan.setProperty("age", "59");  //change is lost

        ORID theRid2 = new ORecordId("#32:30");
        OElement doc2 = db.load(theRid2);
        OVertex petia = doc2.asVertex().get();

        petia.setProperty("age", "59"); //change is not lost
        petia.save();

Regards,
Safwan

**Comment by tglman** [comment]
Hi @ShakAttacked,

OrientDB new graph core API follow the pattern of the 2.x core API where to make persistent a change on a document (or vertex or edge) you have to call the save, this will make persistent the current element with all it's own linked graph of changes.

This is different to the Tinker Pop API that at each setProperty made the element persistent, so on 2.x the graph API where only Tinker Pop API that followed this logic, in 3.0 we have OrientDB Graph API that require save and Tinker Pop 3.x API that do not require save.

Let me know if i got right your question and answered to it.

Regards

**Comment by ShakAttacked** [comment]
Hi @tglman,

Not sure really.  I think the problem is that I mention a previous email to Luigi, so my description is not clear.  So here is the strange behavior.  (it's not a big problem, I just find the behavior inconsistent). 

In 3.0, if you create a new vertex and call commit(); an exception is thrown.  but if you fetch an existing vertex and make a change and commit(), it doesn't throw an exception.  

I think it would be nice to either throw an exception in both situations or not throw an exception.  Personally, I prefer to throw an exception so the programmer knows that he did something wrong.

I also have a feature suggestion that would need to be implemented to close the loop, a feature for programmers to revert the changes of one vertex/edge. #8043 

Hope this helps.
Safwan
