### ISSUE TITLE
3.0 getClass is failing when has a superclass

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8040]
### OS: Centos
  

Hi,

in the code below, subUser is null on 2nd run.  shouldn't getClass return regardless of the inheritance?

        OClass subUser = db.getClass("SubUser");
        if(subUser == null)
        {
            subUser = db.createClass("SubUser", "User");
        }

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

Is it in remote?

@tglman maybe it's a problem with push notifications? perhaps already fixed in the snapshot?

Luigi

**Comment by tglman** [comment]
Hi @ShakAttacked,

Yes this should be fixed with the push notifications in the  3.0.0 Final.

Regards

**Comment by ShakAttacked** [comment]
Hi @tglman,

Do you know when it was fixed? I either tested it on the snapshot from the 25th or the 30th of Jan.  I can check it on the snapshot build from the 30th again.

Thanks,
Safwan

**Comment by tglman** [comment]
Hi @ShakAttacked,

This should have been fixed for the 30th of December, so for sure it should be there the 30th of Jennuary

Regards

**Comment by ShakAttacked** [comment]
Hi @tglman 

I've just tested it again and I cannot reproduce it.  Maybe I found it before I moved to the snapshot on the 25th.

I'll close it.
