### ISSUE TITLE
Minor: 3.0 Performance for creating Schemas, properties, vertexes and indexes is very slow.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8042]
### OS: Centos

In 3.0 performance for creating is much slower during a database initialize procedure, what used to be a couple of seconds is now over a minute.  

In total I create: 
82 Vertexes
59 edges
127 Indexes.
hundreds of properties.

I have a wrapper around the code but essentially it's this repeated many times.

checks if class is not null and drops it using
db.getMetadata().getSchema().dropClass(name);

creates a class with 
  OClass result = db.getMetadata().getSchema().getOrCreateClass(name, 
  db.getMetadata().getSchema().getClass(inheritFrom));
  result.setStrictMode(true);

Create a property with this syntax after checking for existsProperty(var1)
oClass.createProperty(var1, var2);

the only exception is that create index is executed as SQL.  I'm not sure if there was limitations in earlier version.  I create indexes with "FULL TEXT ENGINE LUCENE", others wiht "SPATIAL ENGINE LUCENE METADATA", with  "UNIQUE" and "NOTUNIQUE"

Regards,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

I think it's related to a refactoring we made, so that schema/index changes are pushed to the client. This fixes a lot of problems with un-aligned schema, but of course it has some cost

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila,

Ok. It's really heavy but fortunately we only have to deal with that at reset of database in development.  On a similar topic, I see in 3.0 a way to create a schema without going through the metadata() but not for deleting.  It would be nice if there is a direct way from db instance.

Thanks,
Safwan
