### ISSUE TITLE
Question: is there a way to count edges in 3.0

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8045]
### OS: Centos 

Is there a way to count edges in 3.0 or do we still need to do it with SQL?  and if so, is the SQL code actually fetching the edges and counting them as well?

Thanks

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

If you need the total number of edges of a particular type, you can use OClass API:

```
OClass clazz = db.getClass("E"); //or any other class
class.count(); //also consider subclasses
class.count(boolean); //polymorphic or not, based on the flag
```

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila 

I meant a count start from a Vertex.  It would be great to have something like this, 

`v.edgeCount("FRIEND", Direction.OUT)`

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Ah, ok, got it.

You can do it at low level, eg. 

```
v.getProperty("out_FRIEND").size(); 
```

but it depends a lot on the underlying implementation.

Let me flag this as an enhancement, probably we will add something like this in next versions

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila 

This is good. I always forget that they are properties. Didn't think of that.  

Similarly, wasted 15 minutes the other day trying to figure out how to get the Class of an edge only to realize that getProperty("@class") gives it.

Thanks,
Safwan

**Comment by tglman** [comment]
Hi,

I think we have all the answers here, closing

Regards
