### ISSUE TITLE
3.0 Proper Syntax to create property with OPoint from Java

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8053]
### OS: Centos

In http://orientdb.com/docs/3.0.x/indexing/Spatial-Index.html there is sample code that shows how to create a property in SQL but not in Java.

neither OType, nor OClass in Java provides OPoint. what is the correct way to create a property in java? 

Thanks,
Safwan

**Comment by ShakAttacked** [comment]
Hi, 

Can anyone help with this?

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

You can find an example here

http://orientdb.com/docs/3.0.x/indexing/Spatial-Index.html#geometry-data-example

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila 

No. I'm looking to create the property in Java. not set it.  I'm looking for the proper syntax to createProperty. The only example in that link is for Legacy with 2 separate fields.

Thanks

**Comment by luigidellaquila** [comment]
Oh, got it, you just have to create the schema.

It should be just this:

```
OClass oPoint = db.getClass("OPoint");
OClass clazz = ...
clazz.createProperty("point", OType.EMBEDDED, oPoint)
```

Thanks

Luigi
