### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable

### ISSUE THREAD

**Issue by AlexPGithub** [orientechnologies/orientdb#8054]
## Expected behavior  
after executing the query in the bottom the graph view should continue beeing able to show "select * from Konto"

## Actual behavior  
after executing the query in the bottom the graph view in orientdb studio throws the error in the title when quering "select * from Konto"

## Steps to reproduce  

SCHEMA---------------------
vertex Konto
every: STRING, mandatory, not null
incby:DOUBLE, mandatory, not null
kontostand:DOUBLE, mandatory, not null
lastUpdated:DOUBLE, mandatory, not null
name: STRING, mandatory, not null
showDetails:BOOLEAN, mandatory, not null
vertexyEdge:STRING, mandatory, not null

edge listSuccesor
vertexEdge:STRING, mandatory, not null

---query------------------------
db.query(
"UPDATE #26:1 SET  kontostand =  100, name =  'Freuden des Lebens', every =  'month', incby =  100, showDetails =  false, vertexEdge =  'vertex', in_listSuccessor =  ['#61:0'], out_listSuccessor =  ['#62:0'], lastUpdated =  '2018-02-02T05:31:24.584Z'"
)

**Comment by luigidellaquila** [comment]
Duplicate, please see https://github.com/orientechnologies/orientdb-studio/issues/505

**Comment by AlexPGithub** [comment]
is there a way to delete this dublicate ?

**Comment by luigidellaquila** [comment]
Hi @AlexPGithub 

No problem, you can leave it as it is

Thanks

Luigi
