### ISSUE TITLE
3.0 Please Correct and clarify Documentation for Custom Commands.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8056]
### OS: Centos  

In http://orientdb.com/docs/3.0.x/plugins/Extend-Server.html#custom-commands, you should remove all the **"@Override"** as they are not needed.

The following of the documentation needs additional clarification. It should mention that **demo** is the name of the database. and should have the port.

`http://localhost/hello/demo/Luca`

maybe replace the above line with 

`http://localhost:2480/hello/{your database name}/Luca`

Regards,
Safwan

**Comment by luigidellaquila** [comment]
Fixed, thanks!

Luigi
