### ISSUE TITLE
Doc: 3.0 Simplify Extend-Server Documentation

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8057]
### OS: Centos  

Hi,

Suggestion to simplify documentation here. http://orientdb.com/docs/3.0.x/plugins/Extend-Server.html#debug-the-server

In the documentation for **"Debug the Server"**, I suggest you replace the Java syntax with

`/opt/orientdb/server.sh debug` instead as server.sh is maintained by your team and will always be more accurate than the documentation.

and I suggest you mention to connect to **port 1044** for debugging

Thanks,
Safwan

**Comment by tglman** [comment]
Hi @ShakAttacked,

Thanks to point this out, In any case our documentation is hosted here: https://github.com/orientechnologies/orientdb-docs/tree/develop you can do PR as in the normal project.

Regards

**Comment by ShakAttacked** [comment]
Cool. Thanks.
