### ISSUE TITLE
Dev. Slowdown: Hot Reload of Plugin is not working.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8061]
### OS: Centos

Hi,

As shown to @lvca, using         
`<entry name="plugin.hotReload" value="true"/>` will show that a plugin is being reloaded but the code executed will be the old code.

Debugging the code, it seems to me that the plugin is being reloaded properly but I suspect that the commands are not being reloaded.

the class is defined as 

`public class ServiceResource extends OServerCommandAuthenticatedDbAbstract`

and the following config.

```
<command implementation="com.bla.ServiceResource" pattern="POST|test/* GET|test2/*" stateful="false">
 <parameters>
 </parameters>
</command>
```
Also, note that because it's a server command. plugin.json does not have a class defined as part of its attributes.

Thanks,
Safwan

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila 

any updates on this? 

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

I'm on it, I'll give you a feedback asap

Luigi

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

It seems the plugin is correctly reloading, but the plugin itself is not responsible of registering the HTTP command (it's statically mapped in the XML).

What you can do is:

- remove the xml snippet to register the command
- register the command programmatically at the startup of the plugin:

```
final OServerNetworkListener listener = server.getListenerByProtocol(ONetworkProtocolHttpAbstract.class);
    if (listener == null)
      throw new OConfigurationException("HTTP listener not found");

    listener.registerStatelessCommand(new YourCommand());
```

If needed, you can also unregister commands as follows:


```
    listener.unregisterStatelessCommand(YourCommand.class);
```

I hope it helps

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila,

I'm not able to make it work still.  When you say, "startup of the plugin".  Do you mean in the constructor of a class that extends OServerPluginAbstract?  If so, the constructor is called the first time but not on subsequent updates.

I still define a handler in the xml for the plugin.  What am I missing?

Thanks,
Safwan
