### ISSUE TITLE
Copy cache.stt to fix "Cannot restore state of cache for storage placed under..."

### ISSUE THREAD

**Issue by kmhughes** [orientechnologies/orientdb#8065]
I was going from OrientDB 2.2.15 to 2.2.31.

This is using OpenJDK 1.8 under Linux. 

When openning the database as a plocal instance, I got the following stack trace:

Feb 04, 2018 2:38:26 PM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=instance}} Cannot restore state of cache for storage placed under /home/keith/smartspaces/hestia/controller/data/hestia/instance
com.orientechnologies.orient.core.exception.OLoadCacheStateException: Can not restore state of cache from file
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:665)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:303)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)

I have read that this issue is perhaps fixed in 3.0, but I am going to use 2.2.31 for now. If I have a database that I have closed, can I copy the cache.stt file from that closed database into my database so that I have some contents. I notice the cache on the closed database is only 380 bytes, it can't have too much in it.

Thanks!

**Comment by laa** [comment]
Hi @kmhughes, if you do not experience any problems, but just got this exception in the log. You can ignore it. It will not appear again.

**Comment by kmhughes** [comment]
Cool, thanks @laa I did notice I was still able to read data from the database, so it doesn't seem to be a major issue. I also wonder if my other issue I filed yesterday is why I see it every time since the cache save during shutdown is being interrupted.

**Comment by laa** [comment]
@kmhughes yes that is completely possible.
