### ISSUE TITLE
Blocking until orientDB shutdown for plocal is complete in OSGi.

### ISSUE THREAD

**Issue by kmhughes** [orientechnologies/orientdb#8066]
I am attempting to use OrientDB 2.2.31 inside of an OSGi container.

I am using a couple of plocal databases. When my OSGi container shuts down, I tend to get a stack trace because of an interrupted thread.

Feb 04, 2018 3:32:21 PM com.orientechnologies.common.log.OLogManager log
WARNING: -- error on shutdown storage
com.orientechnologies.orient.core.exception.OStorageException: Thread was interrupted during flush
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegment.flush(OLogSegment.java:691)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.flush(ODiskWriteAheadLog.java:404)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:2804)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:3478)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:545)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.shutdown(OStorageAbstract.java:222)
	at com.orientechnologies.orient.core.Orient.shutdownAllStorages(Orient.java:398)
	at com.orientechnologies.orient.core.Orient.access$500(Orient.java:56)
	at com.orientechnologies.orient.core.Orient$OShutdownEnginesHandler.shutdown(Orient.java:922)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:331)

Is there a way to block in the thread where I initiate the Orient.instance().shutdown() call until the full shutdown is complete. Is there a way to shutdown the storage where everything can flush and I won't get the thread interrupted exception? Or is the exception mostly harmless and I needn't worry about it?

**Comment by laa** [comment]
Hi @kmhughes you should worry about this exceptions. I will check it. We should not interrupt threads during a normal shutdown.

**Comment by kmhughes** [comment]
Many thanks. Please let me know if you need any more information.

**Comment by laa** [comment]
Support of OSGi is not a priority right now.

**Comment by kmhughes** [comment]
Understood on OSGi not being a priority. But are there any answers to the questions that I had, which would provide me a workaround?

Is there a way to block in the thread where I initiate the Orient.instance().shutdown() call until the full shutdown is complete. Is there a way to shutdown the storage where everything can flush and I won't get the thread interrupted exception?

**Comment by laa** [comment]
@kmhughes we separated all storage-related threads in another thread group. So they should not be interrupted on shutdown. Let me check this.

**Comment by kmhughes** [comment]
@laa, thanks! I did move one use of the database into your standard docker image, so OSGi is gone in that one case. But I still do have one plocal.

Now I need to take the docker-based DB and get it to become distributed in kubernetes, preferably with Istio.

**Comment by laa** [comment]
@kmhughes Inside of the thread which writes WAL data to the disk I have put following code:
```
  System.out.println("Sleep before flushing the data");
        try {
          Thread.sleep(10_000);
        } catch (InterruptedException interruptedException) {
          System.out.println("Sleep is interrupted");
        }
        System.out.println("Continue flush");
```

Then I wrote a simple test:
```
 @Test
  public void test() {
    try (OrientDB orientDB =
        new OrientDB("embedded:./target", null, null, OrientDBConfig.defaultConfig())) {
      orientDB.create("stest", ODatabaseType.PLOCAL);

      try (ODatabaseSession session = orientDB.open("stest", "admin", "admin")) {
        ODocument document = new ODocument("V");
        document.save();
      }
    }
  }
```

and I see the following output:
```
Jun 18, 2020 2:27:59 PM com.orientechnologies.common.log.OLogManager log
INFO: Storage 'plocal:C:\Users\lomak\Documents\Development\orientdb\tests\.\target/stest' is created under OrientDB distribution : 3.0.31 - Veloce (build , branch ${scmBranch})
Jun 18, 2020 2:28:00 PM com.orientechnologies.common.log.OLogManager log
INFO: - shutdown storage: stest...
Continue flush
Sleep before flushing the data
Continue flush
Sleep before flushing the data
Continue flush
Sleep before flushing the data
Continue flush
Sleep before flushing the data
Continue flush
Sleep before flushing the data
Continue flush
Sleep before flushing the data
Continue flush
Sleep before flushing the data
Continue flush
Sleep before flushing the data
Continue flush
```

And test passes successfully. 
So we can safely say that storage threads are not interrupted.

**Comment by kmhughes** [comment]
OK, many thanks! I will update to the latest version and see if the problem
goes away for me.
