### ISSUE TITLE
Question: Is there a way to have a hook that would execute after all is committed.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8068]
### OS: Centos  

Hi,

Are Java hooks functions/events executed within the transaction?  

Is there a way to execute code after the transaction is committed, for example.  Once all records are committed,  I would like to clear our own Redis cache.  Hooks seems like the best place to execute such code however, I would like to have the response of a successful transaction back to the user with as little delays.  Any suggestions?

Thanks,
Safwan Hak

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

Hooks are invoked within the transaction, so in a hook you have no information about the commit/rollback. On the other hand, you have ODatabaseListener interface that gives you information about commit/rollback, but no information about which operations were performed. What you need is a mix of the two.
You can do it manually, but it can be a bit tricky. My advice is to use LiveQuery:

```
db.live("SELECT FROM V", new OLiveQueryResultListener(){
 ...
});
```

I hope it helps

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Thanks @luigidellaquila 

I'll checkout live and see if it helps. I had a plan to look at it for the purpose of live Chat. I might have some more questions when I get there. 

Thanks for the advice,
Safwan

**Comment by ShakAttacked** [comment]
@luigidellaquila 

I have an idea but not sure if it'll work.  Would you appreicate a review to see if this approach would work. I was thinking for the Hook to create a new record in a "redis_instructions" table for example.  Then have my plugin register to listen on changes of "redis_instructions" and execute the commands and delete the instruction when done.

That should allow for these additional instructions to run outside the scope of the transaction, good for user.  But I have a couple of questions.  if I delete the instruction record, 

**1- will live listener receive that instruction or it only listens to new record changes?**

**2- And if this all sounds good.  What is the way to start a plugin with one instance of LIVE listener.  Do I need to call the command once so it starts listening? or can I have code that is executed as soon as the plugin starts with its own connection that will stay open?**  

I could do it without the plugin but I find it convenient to be so close to the database if possible.

Thanks,
Safwan

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila,

I'll be working on this later today. would like to get your opinion prior to starting.

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

1. yes, live listener receives different events for CREATE/UPDATE/DELETE (with the corresponding information, ie. for the delete you will receive the content of the deleted record)

2. The implementation should be more or less as follows:
```
public class YourPlugin extends OServerPluginAbstract {

    @Override
    public void config(OServer oServer, OServerParameterConfiguration[] iParams) {
        ODatabaseDocumentInternal database = oServer.openDatabase("foo");
        database.live("select from Foo", new YourListener());        
    }
}
```

Please check this as a reference: http://orientdb.com/docs/3.0.x/plugins/Extend-Server.html

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Thanks @luigidellaquila 

can we consider Live to be stable in 3.0? I remember there was some concern in 2.x. Also, could it ever be interrupted and needs to be restarted? 

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

Yes, it's stable in v 3.0
It can be interrupted if you are in remote, eg. if your connection goes down for any reason, but in embedded (eg. from inside a plugin) you should be safe

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila 

Great. I'll give it a try. Excited to see how this works. 

Thanks,
Safwan
