### ISSUE TITLE
Question: how can I find if a vertex is marked for delete?

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8073]
### OS: Centos

Hi,

Is there a property or flag on the Vertex object that would tell us if a delete() was called on it.  

Thanks,
Safwan

**Comment by tglman** [comment]
Hi @ShakAttacked,

As today there is no specifc API for do that, but if a vertex was deleted in the current transaction `db.load(vertex.getIdentity())` should return null, if you need to check if a different session deleted it `db.load(vertex.getIdentity(),null,true)` the third parameter of the load if `true` make the load skip the session cache.

Hope this help
Regards

**Comment by ShakAttacked** [comment]
Hi @tglman,

can we turn this into a feature request please. I think it would be beneficial to know.  For example, in a trigger, a record might get deleted but another might try to update it and while it doesn't seem to break at the moment, it would be good to be able to check if record is not deleted as to avoid additional code execution on the server.

Thanks,
Safwan

**Comment by tglman** [comment]
Hi,

Yes it may have meaning in future to have an API 'isDeleted' or 'exists' for check if a record with a specific ID still exists in the storage/current transaction.

Regards
