### ISSUE TITLE
Question: Can an EmbeddedMap hold ORID as key?

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8074]
### OS: Centos 

Hi @luigidellaquila,

I see that an EmbeddedList can hold ORIDs and I can do `'where contains #664:1'`
but when I created an EmbeddedMap with ORIDs as keys, I cannot do `'where containskey #664:1'`, it works if it's a string of course, but I think it should be stored as ORID.

Can keys be ORIDs for Maps?

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

For now, embedded maps can only have string keys (at least, the high level API does not allow you to use keys different from String).
As a work-around, you can use a string representation of the RID

Copying @tglman in case he has comments on the internals

Thanks

Luigi

**Comment by ShakAttacked** [comment]
@luigidellaquila 

One problem with RID is that when a record is not yet saved, it has an id such as **@650:-4** and so that won't work.  unless @tglman has a suggestion, I guess I would have to use my own id?  I was hoping to avoid using my own id.

Thanks,
Safwan

**Comment by tglman** [comment]
hi @ShakAttacked,

Maps support as key only String, any other value you use there will be converted as string, so as Luigi said if you put there a rid you will get a String representation, I thing if you have your own ID i would suggest to use that in there.

Regards

**Comment by tglman** [comment]
Hi @ShakAttacked,

Did we answer to your question? can we close this ?

Regards

**Comment by ShakAttacked** [comment]
Yes, Thank you!
