### ISSUE TITLE
OrientDB Studio phones home

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#8077]
## Expected behavior  
Studio should not connect to any other site other than localhost (no cross site)

## Actual behavior  
Studio "phones home" via the News section (at least).  This should not be allowed.  If the intent is actually to provide news from the Studio app, make it opt in.  If the intent is track the usage of the community edition, please only do this by monitoring your website (downloads) and general stats from repository services.  I pointed this out a similar issue when the console was using the 3rd party diagramming tool.  Although that was worse (b/c users were leaking their data models), this should be treated similarly and should not be allowed.

## Steps to reproduce  
Run ./server.sh
Open browser to localhost:2480/
First page displays a news section that is retrieved from orientdb.com

Here's the file that handles the news section:
`orientdb-studio/src/app/administration/newsbox/newsbox.component.ts`
I realize that it's only sending the standard request header and the path contains differentiates between community and ee, but it still shouldn't be done...

**Comment by luigidellaquila** [comment]
Hi @odbuser2 

I think we can add an option to disable this feature, I'm marking this ticket as an "enhancement"

Thanks

Luigi
