### ISSUE TITLE
Queries get's queued up and executes one after the other

### ISSUE THREAD

**Issue by royalpinto** [orientechnologies/orientdb#8079]
## Expected behavior  
I am executing 2 queries from OrientJS library from a single NodeJS process. Both queries start at the same time (one after the other immediately). The first query is bit huge and takes a while to get the result. The second query is really small and should not take a long time (When being executed alone, takes < 100ms), but get's completed only after the first one, hence takes a long time.

## Actual behavior  
It takes a long time to get the second (small) query to complete and completes only after the first query completes.
I have put below log statements to see if NodeJS process get's blocked but it doesn't get's blocked. 
```
setInterval(() => {
    console.log('PING');
}, 500);
```

It seems like, either OrientDB queues up all the queries and runs one after the other, or OrientJS queues it up.

## Steps to reproduce  
Here a code snippet which reproduces the issue. The sample outputs are given in the comments.
https://gist.github.com/royalpinto/43218842a80914b04c9067f5bd8dab1c

> Not sure if it is an issue with OrientJS or OrientDB

**Comment by maggiolo00** [comment]
Hi @royalpinto 

you can set up the pool of connection and use the token in order use different connections

```
const server = orientjs({
    host: SERVER_HOSTNAME,
    port: SERVER_PORT,
    username: SERVER_USERNAME,
    password: SERVER_PASSWORD,
    useToken : true,
    pool : {
        max : 10
    }
});
```

**Comment by royalpinto** [comment]
Thanks, @maggiolo00

I will try the connection pooling.

Is it that a single connection can execute only one query at a time? How would it work if all my connections from the pool are executing time-consuming queries and if want to execute a small query? Does it have to wait till one of the connection finishes current execution?

**Comment by maggiolo00** [comment]
Hi @royalpinto 

yes requests are queued per connections

**Comment by royalpinto** [comment]
Thanks, @maggiolo00 for the information.

closing the issue...
