### ISSUE TITLE
Cluster-Selection.html typo

### ISSUE THREAD

**Issue by brian-guggino** [orientechnologies/orientdb#8082]
## Expected behavior  
The document should be updated. After trying to implement my custom jar with a custom cluster selection - I checked out the source and diff'ed against my codebase and realized that the folder name was incorrect. I know it's a small issue but it would help reduce head-banging...

## Actual behavior 
In the document, 
WEB-INF/service should be WEB-INF/services

## Steps to reproduce  
Read https://orientdb.com/docs/2.2/Cluster-Selection.html
Compare to https://github.com/orientechnologies/orientdb/tree/develop/core/src/main/resources/META-INF/services

Notice the "s" ?

**Comment by luigidellaquila** [comment]
Fixed, thanks!

Luigi
