### ISSUE TITLE
HA REMOVE SERVER parsing error

### ISSUE THREAD

**Issue by captaintino** [orientechnologies/orientdb#8084]
## Expected behavior  
Remove server from OrientDB Cluster

## Actual behavior  
```
orientdb` {db=cmdb}> HA REMOVE SERVER ip-10-251-23-72

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
ha REMOVE SERVER ip-10-251-23-72
                   ^
Encountered " "-" "- "" at line 1, column 20.
Was expecting one of:
    <EOF>
    ";" ...

        DB name="cmdb"
        DB name="cmdb"
```

## Steps to reproduce  
Have a nodename with a dash in it.

Perhaps there is a way to escape this, but I could not find it.

**Comment by luigidellaquila** [comment]
Hi @captaintino 

Try adding back-tick quotes to the server name:

```
HA REMOVE SERVER `ip-10-251-23-72`
```

Thanks

Luigi

**Comment by captaintino** [comment]
Ah, that was what I was looking for. I tried single and double quotes but not backticks. Thanks!
