### ISSUE TITLE
Error parsing query with poorly named implementation

### ISSUE THREAD

**Issue by brian-guggino** [orientechnologies/orientdb#8085]
### About
Minor issue! 
When creating a custom collection strategy using instructions at 2.2/Cluster-Selection.html, I picked a bad name; "date-today", It is funny because "round-robin" works, so perhaps the parsing mechanism is picking up on keywords; "date" and/or "today". 

## Expected behavior  
Make statement in documentation about keywords, or improve parsing functionality.

## Actual behavior  
When activating the poorly named cluster selection implementation -> see below ->

orientdb {db=aerodrome}> ALTER CLASS messages CLUSTERSELECTION date-today

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
`alter CLASS messages CLUSTERSELECTION date-today
                                          ^
Encountered " "-" "- "" at line 1, column 43.
Was expecting one of:
    <EOF> 
    <UNSAFE> ...
    ";" ...
    <UNSAFE> ...`

## Steps to reproduce  
1) Create an implementation of OClusterSelectionStrategy, build and deploy into orientdb's "lib" folder. restart oreintdb service.

2) run orientdb/bin/console.sh, activate the database ->
orientdb> CONNECT remote:localhost/<db-name> <username> <password>

3) activate the poorly named cluster strategy ->
alter CLASS messages CLUSTERSELECTION date-today

**Comment by luigidellaquila** [comment]
Hi @brian-guggino 

The cluster selection is parsed as an identifier, so you use special characters (eg. `-`) you have to quote it with back-ticks:

```
alter CLASS messages CLUSTERSELECTION `date-today`
```

Thanks

Luigi
