### ISSUE TITLE
Custom OClusterSelectionStrategy does not appear in studio manager dropdown

### ISSUE THREAD

**Issue by brian-guggino** [orientechnologies/orientdb#8086]
## Expected behavior  
The name of the OClusterSelectionStrategy implementation should appear in the orientdb's schema manager (UI) 

## Actual behavior  
The dropdown in the UI contains a blank string. When deselecting it, and re-opening the drop down, the "name" does not appear. It would be nice if the system populated the dropdown with all the "name"s of the implementation of OClusterSelectionStrategy loaded. And error appears after some time - in the lower error "bar".

**See attached screen-shots:**
<img width="1088" alt="screen_shot_2018-02-07_at_9 53 08_am" src="https://user-images.githubusercontent.com/25620872/35992913-8f209c0c-0cc0-11e8-920a-5a9e0926f019.png">
![screen_shot_2018-02-08_at_9 14 42_am](https://user-images.githubusercontent.com/25620872/35992916-8f492cda-0cc0-11e8-9015-63343639d472.png)

## Steps to reproduce  
1) Follow direction for 2.2/Cluster-Selection.html, the "random" implementation will suffice.
2) deploy the jar into orientdb's lib folder, restart the orientdb service/server.
3) connect to the database ->
    CONNECT remote:localhost/<db-name> <username> <password>
4) activate the custom implementation ->
    ALTER CLASS messages CLUSTERSELECTION random 
     where "messages" is the class being altered.
5) verify the cluster selection is activated with "info class <class-name>
6) open the orient db UI, http://<host>:<port>/studio/index.html#/database/<db-name>/schema 
7) Find the altered class in the manager...

**Comment by luigidellaquila** [comment]
Hi @brian-guggino 

Right now the drop-down menu is hard-wired in the frontend, but I think we can extend this behavior and make it more consistent.

I'm checking it now

Thanks

Luigi

**Comment by maggiolo00** [comment]
Hi @brian-guggino 

i've just pushed a fix in 2.2.x and develop. It will be available in the next release 2.2.34
