### ISSUE TITLE
OClass addCluster throws UnsupportedOperationException

### ISSUE THREAD

**Issue by brian-guggino** [orientechnologies/orientdb#8087]
### About
I have implemented a custom class cluster selection strategy where a new cluster should be added to a class. As a first try, I chose to create clusters depending on time. A cluster name is handed off into the implementation of OClusterSelectionStrategy. If the cluster has not yet been created, the code attempts to add the cluster to the class. 

See -> 2.2/Cluster-Selection.html

## Expected behavior  
The OClass instance passed in should be able to accept a new cluster, by id or name. Make a statement in the documentation about how to programatically add a cluster to a class - or - improve code to handle adding clusters to class using this java interface (OClusterSelectionStrategy).

Using the console, one can issue command to ADDCLUSTER, then select that new cluster in the studio manager. This behavior is expected from the programmatic API when implementing  OClusterSelectionStrategy according to 2.2/Cluster-Selection.html

## Actual behavior  
The underlying OClass's class is OImmutableClass, and that throws an UnsupportedOperationException, using the debugger, one can step into it...

## Steps to reproduce  
1) create a java/maven project, use 2.2/Cluster-Selection.html as guide.
2) mvn clean package, copy jar to orientdb's "lib" folder.
3) restart orientdbs  service/server, add debug flag to server.sh command line option. (thank you for providing that) 
4) activate the OClusterSelectionStrategy implementation by name in console.
    CONNECT remote:localhost/<db-name> <username> <password>
    ALTER CLASS <class-name> CLUSTERSELECTION <OClusterSelectionStrategy.getName()>
5) Push data into the class-name...
6) use IDE to debug, observe UnsupportedOperationException being thrown when calling OClass.addCluster and addClusterById --- PORT 1044 to debug remote java application.

### Sample code
```
package com.orientechnologies.orient.core.metadata.schema.clusterselection;

import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;

import com.orientechnologies.common.log.OLogManager;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.clusterselection.OClusterSelectionStrategy;
import com.orientechnologies.orient.core.record.impl.ODocument;

public class DateSelectionStrategy implements OClusterSelectionStrategy {
	private String todaysClusterName = null;
	// ==================================================================
	// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	// TODO: REMOVE mm, mm is minutes, this will create a lot of clusters - good for debugging...
	// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	// ==================================================================
	final static String DATE_FORMAT = "yyyyMMddmm";
	final static String STRATAGY_NAME = "ijet"; 

	/**
	 * This static block is not necessary... the system log properties has a Console logger, so, if this
	 * code prints to STDOUT
	 */
	static {
		System.out.println("DateSelectionStrategy loaded by classloader...");
	}
	
	/**
	 * This returns today as a string in a specific format, tomorrow, this method will
	 * return a different string. It populates this classes "today" member.
	 * @return todays date in a day-like string of format - "messages_yyyyMMdd"
	 */
	private String getTodaysClusterName() {	
		SimpleDateFormat ft = new SimpleDateFormat(DATE_FORMAT);
	    return "messages_" + ft.format(new Date());
	}
	
	/**
	 * Implements OClusterSelectionStrategy method, dispatches to getClusterImpl
	 * @see getClusterImpl
	 */
	public int getCluster(OClass iClass, ODocument doc) {
		// an attempt to find if this code is being called - STDOUT should go to the logs?
		System.out.println("DateSelectionStrategy::getCluster called...");
		int id = getClusterImpl(iClass, doc);
		OLogManager.instance().debug(this, "Returning cluster id: " + id);
		return id;
	}
	
	/**
	 * As time goes by, each new day a new cluster is created.
	 * @param iClass - from interface
	 * @param doc - from interface
	 * @return cluster id for the current date based cluster
	 */
	private int getClusterImpl(OClass iClass, ODocument doc) {
		try {
			todaysClusterName = getTodaysClusterName();
			Collection<String> names = doc.getDatabase().getClusterNames();
			if (names.contains(todaysClusterName)) {
				OLogManager.instance().debug(this, "Today is still today: " + todaysClusterName);
				return doc.getDatabase().getClusterIdByName(todaysClusterName);
			}
			// iClass.addCluser(todaysClusterName) throws an UnsupportedException
			OLogManager.instance().debug(this, "Adding cluster: " + todaysClusterName);
			int id = doc.getDatabase().addCluster(todaysClusterName);
			// iClass.addClusterId(todaysClusterName) throws an UnsupportedException
			iClass.addClusterId(id);
			return id;
		}
		
		catch(Exception ex) {
			OLogManager.instance().error(this, "Error in getClusterImpl: " + ex.getMessage(), ex);
			ex.printStackTrace(System.out); 
			return iClass.getDefaultClusterId();
		}
	}

	/**
	 * When using ALTER to to load this OClusterSelectionStrategy, this is the name to use.
	 * @return static member @see STRATAGY_NAME
	 */
	public String getName() {
		return STRATAGY_NAME;
	}

	/**
	 * For forward compatibility with the interface.
	 * @param iClass
	 * @param selection
	 * @param doc
	 * @return the result of @see getCluster
	 */
	public int getCluster(OClass iClass, int[] selection, ODocument doc) {
		return getCluster(iClass, doc);
	}
}
```

**Comment by luigidellaquila** [comment]
Hi @brian-guggino 

You should be able to get an OClassImpl from the db as follows:

```
db.getMetadata().getSchema().getClass(iClass.getName());
```

but I don't know if manipulating the schema inside a cluster selection strategy is a safe operation. I'd suggest to make sure that the clusters are in place before you create the records

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @brian-guggino 

I'm closing this issue, please feel free to re-open if you need further help

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @brian-guggino 

I'm closing this issue, please feel free to re-open if you need further help

Thanks

Luigi
