### ISSUE TITLE
OrientDB in OSGi (Apache Karaf)

### ISSUE THREAD

**Issue by kmhughes** [orientechnologies/orientdb#8089]
I am using OrientDB 2.2.31 in Apache Karaf 4.1.3, an OSGi container.

Depending on my usage, I have some components using a plocal database and some components that are using a remote database. I am getting a stack trace when trying to create a  remote connection.

Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'remote' was not found. URL was: remote:localhost/hestia-central-control. Registered engines are: [memory, plocal]
        DB name="remote:localhost/hestia-central-control"
        at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:519)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:173)

It seems that the remote engine is contained in orientdb-client, but the SPI registration is not picking up that engine, but rather the engines presumably from orientdb-server.

I have looked at old posts and it seems that OSGi support for cases like this was punted by the OrientDB team. Has anyone made any kind of database connection work from one Karaf container, meaning the ability to choose local, memory, or remote? I would happily register the remote engine, but the Orient.instance().registerEngine() call is protected, which is unfortunate in this particular case.

Has anyone made OrientDB work in OSGi,or heard of anyone that made it work? I am trying to put orientdb on the boot classloader to see if that fixes my current issue, but this will not be a good permanent solution.

**Comment by kmhughes** [comment]
I have a solution for now.

I used the Gradle Shadow plugin to make a fat jar that merged all the services/ files. I then used the bnd tool to make the thing into an OSGi bundle. To properly make the whole thing work, I had to embed JNA into the bundle as well.

If anyone is interested, I will point you at the github repo that contains the gradle build file and also my Maven repo that contains the built jar.

It would be awesome if OrientDB allowed memory, remote, and plocal databases with the jars deployed by OrientDB.

**Comment by sakno** [comment]
In our project [SNAMP](https://github.com/bytex-solutions/snamp) we have wide experience to work with OrientDB in Apache Karaf 4.x. Moreover, we embed this database inside of our our OSGi application and it works correctly in the cluster as clustered embedded database. OrientDB libraries are valid OSGi bundles so they can be installed as bundles. To simplify installation of OrientDB into Apache Karaf as we created a KAR archive with correct set of database bundles. You can find XML description of such Karaf Feature [here](https://github.com/bytex-solutions/snamp/blob/master/features/platform-features/src/main/resources/features.xml#L18).

**Comment by kmhughes** [comment]
Cool, many thanks, I will take a look. I like the idea of the embedded database being part of a cluster, I think I will use that.

**Comment by sakno** [comment]
To do that, you need to initialize OrientDB properly in your code. Database uses Hazelcast IMDG for node discovery across the cluster. [Here](https://github.com/bytex-solutions/snamp/blob/master/infrastructure/internal-services/src/main/java/com/bytex/snamp/cluster/OrientDistributedEnvironment.java) you can find properly configured database plugin based on Hazelcast which allows to discover nodes and synchronize metadata between them. And [here](https://github.com/bytex-solutions/snamp/blob/master/infrastructure/internal-services/src/main/java/com/bytex/snamp/cluster/DatabaseNode.java) you can find proper programmatic configuration of embedded OrientDB which allows to work database in the cluster.

**Comment by kmhughes** [comment]
Awesome, many thanks for the pointers!
