### ISSUE TITLE
Create Edge failing when link attribute is null

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/orientdb#8091]
## Scenario
Edge MyEdge
- from: Link, V, not null
- to: Link, V, not null
- externalLink: Link, V, null

## Expected behavior  
CREATE EDGE MyEdge from (fromRid) to (toRid) set externalLink = null
Edge MyEdge is created

## Actual behavior  
Nullpoint exception

## Steps to reproduce  
Just run the query in Studio 

## Other
It works well for null link attributes in Vertex but it fails in Edge

**Comment by luigidellaquila** [comment]
Hi @igasparetto 

This is a standard setting for TinkerPop graphs, you can change this default with the following:

```
alter database custom standardElementConstraints = false
```

Thanks

Luigi
