### ISSUE TITLE
Misleading exception when Schema/Table is not defined in the database.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8093]
### OS: Centos

Hi,

If you attempt to createVertex with an undefined schema, it'll give a misleading exception.  This happens when the vertex is created inside of a Hook.
 
`java.lang.NullPointerException when createVertex is null.`

Syntax:
`OVertex indexVertex = database.newVertex(targetTable);`

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

Thank you very much, NullPointerException is definitely not the expected exception here, I replaced it with a more meaningful one

Thanks

Luigi
