### ISSUE TITLE
Hook onOpen/onClose are called all the time. 

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8094]
### OS: Centos

Hi, if I register a Hook from a Plugin, onOpen and onClose is called all the time.   create a class as below and when you create the Hook from code, it'll print open and close all the time.  The concern is that it's doing unnecessary open/close of connections that are creating Hooks over and over again.

```
public class BaseHook extends ODocumentHookAbstract implements ODatabaseLifecycleListener
{
...
    @Override
    public void onOpen(ODatabaseInternal oDatabaseInternal)
    {
        OLogManager.instance().info(this, (char) 27 + "[34m" + "onOpen:" + this.getClass().getName());
        oDatabaseInternal.registerHook(this);
    }

    @Override
    public void onClose(ODatabaseInternal oDatabaseInternal)
    {
        OLogManager.instance().info(this, (char) 27 + "[34m" + "onClose:" + this.getClass().getName());
        oDatabaseInternal.unregisterHook(this);
    }
}
```

Regards,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

My feeling is that these recurring logs are due to a background thread (eg. WAL flush) that is opening and closing database connections at regular intervals.
If it is the case, then it is normal and expected.

@tglman could you please double-check and confirm?

Thanks

Luigi

**Comment by laa** [comment]
@ShakAttacked could you log add thread name into the log so we will see which thread triggers those hooks?

**Comment by ShakAttacked** [comment]
Hi @laa, 

is this what you are looking for?

```
2018-02-13 15:30:11:812 INFO  {db=OSystem} onClose:org.touca.server.hooks.testHook Thread:OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:49028
2018-02-13 15:30:11:813 INFO  {db=OSystem} onClose:org.touca.server.hooks.testHook2 Thread:OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:49028

```

**Comment by tglman** [comment]
Hi @ShakAttacked,

The onOpen and onClose are called each time a session is open or is closed not on the storage open/close.

In any case if you use this for register and unregister hooks is correct because hooks need to be registered on each session.

Regards
