### ISSUE TITLE
Please expose getOriginalValue() at the Element class

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8095]
### OS: Centos

Hi,

While in transaction, it's not obvious how to get the old value once modified in the code (prior to transaction commit).  After discussion with @luigidellaquila , it seems the method is available but not exposed at Element.  Please expose the method here

`((ODocument) vertex.getRecord()).getOriginalValue(propertyName);`

into this.

`vertex.getOriginalValue(propertyName);`

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 


I'm marking it as an enhancement, IMHO it makes sense, we will discuss it internally.
Just a side note, the correct syntax is:

```
element.getOriginalValue(propertyName);
```

Thanks

Luigi
