### ISSUE TITLE
misleading error at start of the server.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8097]
### OS: Centos

As I'm reviewing this errors that show up in the log when starting the server with @luigidellaquila . we saw this error and  it seems that it's not an error but actually more of info.  the error message is misleading.  

`- error in log [OVariableParser.resolveVariables] Error on resolving property: distributed 
`
Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

It is not an error indeed, it's just the server that is starting in single-node mode.
IMHO it makes sense to change that message to something less scary, like "cannot resolve property"

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

I pushed a fix changing the error message, I think this can be closed

Thanks

Luigi
