### ISSUE TITLE
Crtical: LiveQuery is returning the wrong data (embedded)

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8098]
### OS: Centos

Hi,

I have a LiveQuery with "select from PersonIndex", it tells me that I only have 5 columns but when I query the database, I am missing 2 columns.  usersObjects and users are not coming back.  See result from "Studio" below.  However, I noticed that in LiveQuery the @version is **0** while in the database it's **1**.  So I think LiveQuery is receiving the wrong ORecord data.  I believe the root cause is Hooks doing multiple updates to a new record.

```
{
            "@type": "d",
            "@rid": "#661:60",
            "@version": 1,
            "@class": "PersonIndex",
            "name": "Bob4",
            "usersObject": {
                "23423423423424fa": {
                    "i": "23423423423424fa",
                    "n": "Bob4"
                },
                "Person": {
                    "i": "23423423423424fa",
                    "n": "Bob4"
                }
            },
            "users": [
                "#649:69"
            ],
            "person_id": "#649:69",
            "@fieldTypes": "users=z,person_id=x"
        }

```

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

I'm checking it, I'll let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

The problem with the version number should be already fixed.

I tried to reproduce the problem with the missing columns, but without success, do you have any hints on how to do it?

Thanks

Luigi
