### ISSUE TITLE
OJVMErrorException Encountered

### ISSUE THREAD

**Issue by ScoobyMax** [orientechnologies/orientdb#8099]
## Expected behavior  
client verification and error message

## Actual behavior  
DB error, need to restart
`2018-02-13 10:31:48,106 ERROR [com.ats.vis.rest.config.ResponseStatusProvider] (default task-41) [IP:192.168.154.1] [reg154] Internal server error: com.orientechnologies.orient.core.exception.OJVMErrorException: JVM error 'TokenMgrError : Lexical error at line 1, column 63.  Encountered: <EOF> after : "\'33344555"' occurred during data processing, storage is switched to 'read-only' mode. To prevent this exception please restart the JVM and check data consistency by calling of 'check database' command from database console.`

## Steps to reproduce  
try to execute request:
SELECT * FROM DataEntity_Main_Order WHERE CaseNumber='21314
http://prntscr.com/idxzgi

**Comment by laa** [comment]
Hi it is fixed in latest version just upgrade and all will work ))
