### ISSUE TITLE
Missing link to https://orientdb.com/orientdb-labs/ ?

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8102]
## Expected behavior  
How does one goes to https://orientdb.com/orientdb-labs/ ? The newly re-design web site provides no link?

## Steps to reproduce  
Go to th web site and you will see no link to Labs

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Thank you very much for reporting, we are fixing the problem now

Thanks

Luigi

**Comment by tglman** [comment]
hi @hrstoyanov,

This is now fixed, thanks for reporting.

Regards
