### ISSUE TITLE
index rebuilds after crash/OOM should go much faster

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8105]
## Expected behavior  
After the server died ungracefully (with OOM exceptions, for example), the indexes that are found to be inconsistent on disk are to be repaired via a rebuild. Now this happens index per index, which is taking many DAYS to complete in case of a truely BIG database (ours is now 2.7TB size).
There are plenty of server resources unused while ODB is rebuilding index per index. So what I would expect is that such index rebuilds are done in parallel for all (inconsistent) indexes of each class so that the data of each class must only be scanned once.

## Actual behavior  
- Each and every index is rebuild sequentially
- the documents for a same class is scanned multiple times if multiple indexes exist on that class

(underutilized) server resources while rebuilding is ongoing:
```
$ vmstat 4
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0      0 30487408  37104 1898148    0    0   596   148    1    3  4  3 93  0  0
 1  0      0 30489620  37104 1898180    0    0 16435  2212 7663 5952  5  2 93  0  0
 2  0      0 30484476  37104 1898180    0    0 16719  3268 7775 5824  4  2 94  0  0
 2  0      0 30485188  37104 1898180    0    0 16289     0 10169 3159  5  1 94  0  0
 2  0      0 30486364  37104 1898180    0    0 16504  1901 11058 5045  4  2 94  0  0
 2  0      0 30487052  37104 1898180    0    0 10798  1199 15308 4267  5  2 94  0  0
 2  0      0 30488128  37104 1898180    0    0 16365  1317 7376 5037  4  1 95  0  0
 1  0      0 30488048  37104 1898180    0    0 10616  1380 7195 4621  5  1 94  0  0
...
```

Index rebuilds started Feb-13 4PM:
```
2018-02-13 16:31:01:996 INFO  {db=cdrarch} - Rebuilding index cdrarch.idx_cdr_af_20170205_6 (estimated 686,825 items)... [OIndexRebuildOutputListener]
2018-02-13 16:31:26:048 INFO  {db=cdrarch} Rebuild of 'idx_cdr_af_20170205_6 index was successfully finished [OIndexManagerShared$RecreateIndexesTask]
...
```
and are still ongoing right now (Feb-16...). Needless to say that meanwhile the database is still unusable.

Different indexes of a same class are rebuilt sequentially, each one scanning all documents again of the class.

**Comment by lvca** [comment]
Assigned to @tglman, because he already designed a solution to go much faster then now.

**Comment by rdelangh** [comment]
wow @tglman , now you got me curious ! ;-)

**Comment by rdelangh** [comment]
here we are: indexes are restored, after 5 days:
```
...
2018-02-18 22:09:29:419 INFO  {db=cdrarch} 842 indexes were restored successfully, 0 errors [OIndexManagerShared$RecreateIndexesTask]
2018-02-18 22:09:29:639 INFO  {db=cdrarch} Indexes restore after crash was finished. [OIndexManagerShared]
```
@tglman , can you please share the mechanism by which these indexes rebuilds can be accelerated ?

**Comment by tglman** [comment]
Hi @rdelangh,

As today the rebuild of the index does just a simple browse of all the records and one by one does one get the key and put it in the index, for improve the speed of this there are multiple steps:

- Batch loading record to index
- Batch put of the keys (using a single atomic operation per multiple keys, the low level equivalent of a tx)
- Replace high level document API with low level access to the field key without using the ODocument class.
- Eventually turn off the WAL for the rebuild process

This steps will happen in a not to far future in a bit random order, they do not depend on each other.

Regards
