### ISSUE TITLE
Lucene composite index errors

### ISSUE THREAD

**Issue by misu200** [orientechnologies/orientdb#8107]
### OS: Ubuntu 16.04.3 LTS

Any [ or ] characters in a field from a Lucene composite index is crashing the 'check database' command from console:

Checking cluster persoana  for index Persoana.numeCanonic_dataNastere_adresa
cluster persoana (42) |*                   | 5%
Error: com.orientechnologies.orient.core.index.OIndexEngineException: Error parsing lucene query
        DB name="termene1051"

Error: com.orientechnologies.orient.core.sql.parser.ParseException: Cannot parse 'GHEORGHE V[DUVA': Encountered "<EOF>" at line 1, column 15.
Was expecting one of:
    "TO" ...
    <RANGE_QUOTED> ...
    <RANGE_GOOP> ...

**Comment by luigidellaquila** [comment]
Hi @misu200 

This is related to Lucene itself, not to OrientDB. 

Lucene query language uses square brackets for range conditions (see https://lucene.apache.org/core/2_9_4/queryparsersyntax.html), so if you want to search an actual square bracket you have to escape it

Thanks

Luigi
