### ISSUE TITLE
BYTE field behavior

### ISSUE THREAD

**Issue by futureglorydev** [orientechnologies/orientdb#8113]
## Expected behavior  
<add here>  
I have a field of type BYTE used as status field like 1,2,3 and etc.
In orientdb web studio I created a record with status = 1

http://joxi.ru/LmG9BWBuR0Gk7A
I expected to have this records returned with filter "where status = 1"

## Actual behavior  
I made a query like "select * from Class where status = 1" and got 0 records.
Simple select without filter returns me this
http://joxi.ru/823dBYBi60Y7WA

It works only if status value is like " status='1' " but 1 is not a string

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @futureglorydev 

Thank you for reporting, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @futureglorydev 

I just pushed a fix for this bug, the snapshot will be available in a few minutes

Thanks

Luigi

**Comment by futureglorydev** [comment]
Thanks!
