### ISSUE TITLE
The meterian batch at the bottom of the github page reports a zero score in security!

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#8116]
The meterian batch at the bottom of the github page reports a zero score in security
apparently because of the jackson databind and log4j libraries. Couldn't find another issue on this so maybe I am the first to worry about it... should I be worried!? 

https://www.meterian.io/projects.html?pid=29a79522-f62e-4d2e-910c-28ebdcebb111

**Comment by lvca** [comment]
Those libraries come with TinkerPop/Gremlin package and we can't update them for 2.2.x. If you're worried about that, you can use the plain OrientDB version without the support for TinkerPop.

**Comment by temilmg** [comment]
We will use the plain OrientDB
Thank you
