### ISSUE TITLE
Match query not working as expected in Orient-Net with 3.0.0 RC1

### ISSUE THREAD

**Issue by MattWherry** [orientechnologies/orientdb#8121]
### OrientDB Version: <version here>  
3.0.0 RC1

OrientDB-NET driver 0.1.12 (Windows and Linux)

### Java Version: <version here>  
openjdk:8-jdk-alpine
(Using Orient Server from the official 3.0.0 RC1 docker image)

### OS: <os here>  
Linux (Server), Both Linux and Windows (Client)

## Expected behavior  
In query:-
MATCH {class: URD, as: orig}.in("elaborates") {as: vtx, while: ($depth < 100),depthAlias:dp} RETURN dp,vtx.Key as Key,vtx.@class as class,vtx.Summary as Summary
 
dp field of result gives the traversal depth of the query

## Actual behavior  
In OrientDB Studio and REST API behaves as expected.
In OrientDB-Net (both Windows and Linux), returns a null for dp.

## Steps to reproduce  

Against any data with a path depth > 1, run the queries in the expected behaviour section using ODatabase.Query in the .NET driver - get the "Actual Behaviour".

Run the same queries in REST or Orient Studio - get the expected behaviour.

I'll try PyOrient after Lunch.

**Comment by luigidellaquila** [comment]
Hi @MattWherry 

I think the .NET driver is still using the legacy API that uses the old SQL executor. The `depthAlias` was implemented in the new one, this is why you are not seeing it.

The driver will be updated in the near future, so hopefully you will have this feature soon

Thanks

Luigi

**Comment by MattWherry** [comment]
That's great - thanks @luigidellaquila  - as everything is working fine through the REST API- I've written some python scripts to workaround for the moment.  I can delete them once the driver is updated :-)
