### ISSUE TITLE
Error parsing MATCH query with "class" and "while" clauses

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#8129]
## Expected behavior
Regardless of other `while` and `where` clauses, a MATCH statement's `class: Foo` clause should behave identically to a `where: (@this INSTANCEOF 'Foo')`.

For example, the following two queries should behave identically, without errors, and return the same rows (the only difference is below the `out('Quux_Quux')` part):
```
MATCH {
    class: Foo,
    as: Foo___1
}.out('Foo_Bar') {
    class: Bar,
    as: Bar___1
}.out('Bar_Quux') {
    as: Quux___1
}.out('Quux_Quux') {
    class: Special_Quux,
    while: ($depth < 5),
    where: (name = 'SQ1'),
    as: Special_Quux___1
} RETURN $matches
```
and
```
MATCH {
    class: Foo,
    as: Foo___1
}.out('Foo_Bar') {
    class: Bar,
    as: Bar___1
}.out('Bar_Quux') {
    as: Quux___1
}.out('Quux_Quux') {
    while: ($depth < 5),
    where: ((name = 'SQ1') and (@this INSTANCEOF 'Special_Quux')),
    as: Special_Quux___1
} RETURN $matches
```

## Actual behavior  
The first query produces a strange error:
```
Error on parsing query
Query: (select from null)
```

The second query runs correctly and returns the correct outputs.

## Steps to reproduce  
Here's a sample schema and data that exhibit this problem:
```
CREATE CLASS Foo EXTENDS V
CREATE CLASS Bar EXTENDS V
CREATE CLASS Quux EXTENDS V
CREATE CLASS Special_Quux EXTENDS Quux

CREATE CLASS Foo_Bar EXTENDS E
CREATE CLASS Bar_Quux EXTENDS E
CREATE CLASS Quux_Quux EXTENDS E

CREATE VERTEX Foo SET name = 'FooA'
CREATE VERTEX Foo SET name = 'FooB'
CREATE VERTEX Foo SET name = 'FooC'

CREATE VERTEX Bar SET name = 'BarA'
CREATE VERTEX Bar SET name = 'BarB'
CREATE VERTEX Bar SET name = 'BarC'

CREATE VERTEX Quux SET name = 'Q'
CREATE VERTEX Special_Quux SET name = 'SQ1'
CREATE VERTEX Special_Quux SET name = 'SQ2'

# Link up Foo -> Bar, matching up letters
CREATE EDGE Foo_Bar FROM (SELECT * FROM Foo WHERE name = 'FooA') TO (SELECT * FROM Bar WHERE name = 'BarA')
CREATE EDGE Foo_Bar FROM (SELECT * FROM Foo WHERE name = 'FooB') TO (SELECT * FROM Bar WHERE name = 'BarB')
CREATE EDGE Foo_Bar FROM (SELECT * FROM Foo WHERE name = 'FooC') TO (SELECT * FROM Bar WHERE name = 'BarC')

# Link up Bar "BarA" -> Quux "Q", other Bars -> Special_Quux "SQ2"
CREATE EDGE Bar_Quux FROM (SELECT * FROM Bar WHERE name = 'BarA') TO (SELECT * FROM Quux WHERE name = 'Q')
CREATE EDGE Bar_Quux FROM (SELECT * FROM Bar WHERE name = 'BarB') TO (SELECT * FROM Special_Quux WHERE name = 'SQ2')
CREATE EDGE Bar_Quux FROM (SELECT * FROM Bar WHERE name = 'BarC') TO (SELECT * FROM Special_Quux WHERE name = 'SQ2')

# Link Quux "Q" -> Special_Quux "SQ1"
CREATE EDGE Quux_Quux FROM (SELECT * FROM Quux WHERE name = 'Q') TO (SELECT * FROM Special_Quux WHERE name = 'SQ1')
```

The problematic query is similar to the one in issue #7823, but the symptoms are different (this time we get a parse error instead of no results) and that issue was closed and fixed in 2.2.30. In contrast, this issue is still present in 2.2.30.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

Thank you for reporting, I'm checking it now, I'll give you a feedback asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I just pushed a fix, now it should work fine.
The fix will be released with 2.2.33

Thanks

Luigi

**Comment by obi1kenobi** [comment]
Thanks for the speedy fix, @luigidellaquila -- much appreciated. 

I took a look at the fix and it looks good. However, I was a bit confused as to why only the `node.in` was looped over -- shouldn't edges in `node.out` be considered as well? Is it certain that all `PatternEdge` edges are `in` on one `PatternNode` and `out` on another, so we only have to iterate one side of the nodes?

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

Don't worry, that's very internal stuff, not related to edge out/in

Thanks

Luigi
