### ISSUE TITLE
url-encoding of class name only work on create vertex

### ISSUE THREAD

**Issue by ipnm0084** [orientechnologies/orientdb#8131]
### OS: <os here>  Windows

When orientdb create vertex, ``OCommandExecutorSQLCreateVertex#execute`` function is called.
In this class, ``OrientVertex`` instance is created, and register class name as url-encoded. (see: ```OrientVertex```'s constructor call ```OrientVertex#checkForClassInSchema```)
On the other hand, on selecting vertex, ```OCommandExecutorSQLSelect``` doesn't encode class name, then cannot find vertices assigned class name with special charactor. 

## Steps to reproduce  
> ```CREATE CLASS `Parent$Child` EXTENDS V ```  

create class named as 'Parent$Child'  
> ```CREATE VERTEX `Parent$Child` ```

create class and vertex named as url encoded name:'Parent%24Child' 
> ```SELECT * FROM `Parent$Child` ```

select class named as  'Parent$Child' ,then no result return

**Comment by luigidellaquila** [comment]
Hi @ipnm0084 

Yes, it's a known issue. Unfortunately TinkerPop tests rely on that convention, so we cannot change it in v 2.2.x

Good news is that the problem is already solved in v 3.0

Thanks

Luigi

**Comment by ipnm0084** [comment]
Hi @luigidellaquila 

Thank you for reply.
In 2.2.x, when using the TinkerPop interface, i will use it carefully. 
I feel relieved to hear that the problem is already solved in v 3.0.
I'm looking forward to the official release of v 3.0.
