### ISSUE TITLE
0rientdb was running out memory because of too many connectons but pool MAX is set 50?

### ISSUE THREAD

**Issue by hp1975** [orientechnologies/orientdb#8134]
## Expected behavior  
the orientdb server should remain healthy even there are many connections at client sides ;

## Actual behavior  
Problem is 0rientdb was running out memory because of too many connectons.
2018-02-22 10:50:24:239 WARNI Reached maximum number of concurrent connections (max=1000, current=1002), reject incoming connection from /10.70.223.110:56741 [OServerNetworkListener]

But the server config was using 

```
-             <parameters>
-                 <parameter value="true" name="enabled"/>
-                 <parameter value="50" name="graph.pool.max"/>
-             </parameters>

```
The max connection should not exceed 50, but 0rientdb log show it’s 1002, why?

## Steps to reproduce  
<add here>

**Comment by tglman** [comment]
Hi @hp1975,

The pool setting should be set in the client side, the 1000 limit is the limit of active session for a specific server, the setting of  pool on the server has no effect to you application, so you probably have some too big limit of pooling in your application or you don't use a pool and miss some database close.

Regards
