### ISSUE TITLE
Wrong exception on setDefaultClusterId

### ISSUE THREAD

**Issue by imarsv** [orientechnologies/orientdb#8140]
## Expected behavior  
Default cluster id changes.

## Actual behavior  
Receive exception when try to change default cluster id.
com.orientechnologies.orient.core.exception.OSchemaException: Cluster with id '33' do not exists

com.orientechnologies.orient.core.metadata.schema.OClassRemote
``
public void setDefaultClusterId(final int defaultClusterId) {
    final ODatabaseDocumentInternal database = getDatabase();
    String clusterName = database.getClusterNameById(defaultClusterId);
    if (clusterName != null)
        throw new OSchemaException("Cluster with id '" + defaultClusterId + "' do not exists");
``
It looks like wrong "clusterName" checking.

**Comment by luigidellaquila** [comment]
Hi @imarsv 

Thank you very much for reporting.
I just pushed a fix to develop branch, it will be released with the GA, hopefully in one week or so.

Thanks

Luigi
