### ISSUE TITLE
orientdb function is unusual

### ISSUE THREAD

**Issue by luotianran** [orientechnologies/orientdb#8149]
## Expected behavior  
execute a orientdb function , response code is 200, and have not errors

## Actual behavior  
{
    "errors": [
        {
            "code": 400,
            "reason": "Bad request",
            "content": "Error on parsing script at position #0: Error on execution of the script\nScript: phone\n------^\r\n\tDB name=\"sns\"\njava.lang.UnsupportedOperationException: Operation is not supported because may cause OOM exception\nOperation is not supported because may cause OOM exception"
        }
    ]
}

## Steps to reproduce  
execute orientdb function every time

**Comment by luotianran** [comment]
I select groovy to create a orientdb function

**Comment by luigidellaquila** [comment]
Hi @luotianran 

This should be already fixed, see https://github.com/orientechnologies/orientdb/issues/8135

If you have a chance to try the snapshot (https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.0-SNAPSHOT/), could you please confirm that it work fine?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @luotianran 

This fix was released a few weeks ago. I'm closing this issue, but please feel free to re-open if you need further help

Thanks

Luigi
