### ISSUE TITLE
Deep traversal doesn't appear to work as expected

### ISSUE THREAD

**Issue by MattWherry** [orientechnologies/orientdb#8151]
### OrientDB Version: <version here>  
3.0.0RC1

### Java Version: <version here>  
openjdk:8-jdk-alpine
(Using Orient Server from the official 3.0.0 RC1 docker image)

### OS: <os here>  
Linux (Server), Both Linux and Windows (Client)

## Expected behavior  
Query 1 result is;
1
2.1
1.1.1
1.1
1.1.1
2
2.1
1.1.1
1.1
1.1.1

Query 2 result is:
The counts of nodes in the result is:
Node  Count
1         1
2         1
1.1      2
2.1      2
1.1.1   4

## Actual behavior  
Query 1 result is:
1
2.1
1.1
1.1.1
2
2.1
1.1.1
1.1

i.e. doesn't seem to matching 1.1.1 via. the paths 1->2.1->1.1.1 or 2->1.1->1.1.1

Query 2 result is:
1         1
2         1
1.1      2
2.1      2
1.1.1   2
i.e. if consistent with query 1, is not matching 1.1.1 via. the paths 1->2.1->1.1.1 or 2->1.1->1.1.1

## Steps to reproduce  
I have an orient the following graph as follows.

1->1.1
2->2.1

2->1.1
1->2.1

1.1->1.1.1
2.1->1.1.1

I'm trying to run a query to present the graph structure rooted at 1 and 2 (as a depth first tree):
In accordance with the notes on #5804 and https://orientdb.com/docs/last/SQL-Match.html
I run the following a query to present the graph structure rooted at RISK (as a depth first tree):

query 1:
SELECT dp,vtx.ID FROM (MATCH {class: Risk, as: orig}.in("mitigates","implements") {as: vtx, while: ($depth < 100),depthAlias:dp, pathAlias:pth} RETURN dp,vtx, [orig.@rid] || pth as loc ORDER BY orig.@rid,loc.asString() desc)

I get the Actual Behaviour
I was expecting the Expected Behaviour

In case the query 1 is too complicated, I tried the query below:
query 2:
MATCH {class: Risk, as: orig}.in("mitigates","implements") {as: vtx, while: ($depth < 100)} RETURN vtx.ID

I get the Actual Behaviour
I was expecting the Expected Behaviour

For convenience - here are some orient queries to set up a test database to reproduce this:

#Setup
CREATE CLASS Thing EXTENDS V
CREATE PROPERTY Thing.ID STRING

CREATE CLASS RISK EXTENDS Thing
CREATE CLASS RISKCONTROL EXTENDS Thing
CREATE CLASS REQUIREMENT EXTENDS Thing

CREATE CLASS mitigates EXTENDS E

CREATE VERTEX RISK SET ID="1"
CREATE VERTEX RISK SET ID="2"

CREATE VERTEX RISKCONTROL SET ID="1.1"
CREATE VERTEX RISKCONTROL SET ID="2.1"

CREATE VERTEX REQUIREMENT SET ID="1.1.1"

CREATE EDGE mitigates FROM (SELECT FROM RISKCONTROL WHERE ID="1.1") TO (SELECT FROM RISK WHERE ID="1") 
CREATE EDGE mitigates FROM (SELECT FROM RISKCONTROL WHERE ID="2.1") TO (SELECT FROM RISK WHERE ID="2")

CREATE EDGE mitigates FROM (SELECT FROM RISKCONTROL WHERE ID="1.1") TO (SELECT FROM RISK WHERE ID="2") 
CREATE EDGE mitigates FROM (SELECT FROM RISKCONTROL WHERE ID="2.1") TO (SELECT FROM RISK WHERE ID="1")

CREATE EDGE implements FROM (SELECT FROM REQUIREMENT WHERE ID="1.1.1") TO (SELECT FROM RISKCONTROL WHERE ID="1.1")

CREATE EDGE implements FROM (SELECT FROM REQUIREMENT WHERE ID="1.1.1") TO (SELECT FROM RISKCONTROL WHERE ID="2.1")

#Query 1
SELECT dp,vtx.ID FROM (MATCH {class: Risk, as: orig}.in("mitigates","implements") {as: vtx, while: ($depth < 100),depthAlias:dp, pathAlias:pth} RETURN dp,vtx, [orig.@rid] || pth as loc ORDER BY orig.@rid,loc.asString() desc)
#Query 2
MATCH {class: Risk, as: orig}.in("mitigates","implements") {as: vtx, while: ($depth < 100)} RETURN vtx.ID

**Comment by luigidellaquila** [comment]
Hi @MattWherry 

Thank you for reporting, I'm checking it, I'll let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @MattWherry 

I just pushed a fix on develop branch, the snapshot will be available on Sonatype servers in a few minutes and the fix will be released with 3.0.0GA

Thanks

Luigi
