### ISSUE TITLE
Query and return objects via Object API

### ISSUE THREAD

**Issue by nordgreg** [orientechnologies/orientdb#8153]
## Expected behavior  
return list of objects or object

## Actual behavior  
java.lang.UnsupportedOperationException

## Steps to reproduce  

The docs are pretty thin on using the Object API in version 3.0.  Either that or i am missing something.  Is this the correct way to query via the Object API?  Or is this work still to be done for the final 3.0 release?

```java
// objects registered on startup via object api 
Customer customer = null;
try{
	ODatabaseObject db =getODatabaseObjectPool().acquire();
	Map<String, Object> params = new HashMap<>();
	params.put("refID",refID);
	List<Customer> result = (List<Customer>) db.query("select from Customer where refID = :refID",params);
	customer = result.get(0);
}catch (Exception e) {
	logger.error(e);
} finally {
	try{
		getOrientDBObject().close();
	} catch (Exception e){
		logger.error(e);
	}
}

return customer;
```

I tried this with OResultSet as well.

**Comment by lvca** [comment]
Where the exception `java.lang.UnsupportedOperationException` is thrown? Which part of your code, which method? Thanks.

**Comment by nordgreg** [comment]
the error is getting thrown in the try/catch, not in the finally.  the only error message that gets returned is java.lang.UnsupportedOperationException.  getMessage and getLocalizedMessage return null  

I also tested by removing the query to make sure it wasn't the pool.acquire.  so, it must be on the db.query

```java
        
        try{
          Payment payment = null;
          ODatabaseObject db =getODatabaseObjectPool().acquire();
          Map<String, Object> params = new HashMap<>();
          params.put("refID",refID);
          List<Customer> result = (List<Customer>) db.query("select from Customer where refID = :refID",params);
          if(!result.isEmpty()){
                logger.info("at least one result");
                payment = result.get(0);
          }else {
                logger.info("no result");
          }

        }catch (Exception e) {
            logger.error("catch");
            logger.error(e);
        } finally {
            try{
                getOrientDBObject().close();
            } catch (Exception e){
                logger.error("finally");
                logger.error(e);
            }
        }
```

**Comment by luigidellaquila** [comment]
Hi @nordgreg 

I'm working on this now, I'll give you a feedback asap.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @nordgreg 

I just pushed a fix for this problem, now you can use two different APIs on the Object database

the first one is just the plain SQL implementation, with normal result set (no POJOs returned):
```
OResultSet rs = db.query("select from ...", params);
while(rs.hasNext()){
  OResult item = rs.next();
  ...
}
rs.close();
```

The second one is the Object query API:
```
List<YourPojo> result = db.objectQuery("select from ...", params);
```

Please let me know if you experience any problems

Thanks

Luigi
