### ISSUE TITLE
Running `EXPORT` and then `IMPORT` doesn't preserve IDs

### ISSUE THREAD

**Issue by triketora** [orientechnologies/orientdb#8160]
## Expected behavior  
Running `EXPORT DATABASE` and then `IMPORT DATABASE` should preserve IDs. 

## Actual behavior  
Nearly all the IDs change.

## Steps to reproduce  
Run `EXPORT DATABASE`.
Run `IMPORT DATABASE` with `-preserveClusterIDs=true` flag.
Query all entries of some class on the original DB instance.
Query all entries of same class on newly imported DB instance.
Observe that the IDs don't match.

**Comment by futureglorydev** [comment]
Is it applicable for v3.0?

**Comment by laa** [comment]
@futureglorydev yes, in all versions only consistency of links is preserved. It may be changed in next versions. But for now, it will work as described in issue.

**Comment by futureglorydev** [comment]
@laa Thanks for notice
