### ISSUE TITLE
orientDB corrupting very often

### ISSUE THREAD

**Issue by Manish-Aman** [orientechnologies/orientdb#8164]
## Expected behavior  
<It should not fail after rebuild>  

## Actual behavior  
<It fails very often even after rebuild OrientDB>  

## Steps to reproduce  
<It happens anytime don't know exact steps to reproduce>  

OrientDB is very often failing in Production environment and we are unable to identify the root cause. Could you help me to find the root cause for failing and if possible can we get fix for this. Regards, Manish

**Comment by laa** [comment]
@Manish-Aman do you use 1.4.1 version? That is super old and quite fragile version. Please make export/import of data from/to JSON and use 2.2.32 version instead.

**Comment by Manish-Aman** [comment]
Hi thanks a lot. Is there any other option instead of upgrade?

**Comment by laa** [comment]
@Manish-Aman sorry no other options.

**Comment by triketora** [comment]
Be careful using EXPORT and IMPORT, all of my record IDs are wiped out whenever I do that. It is very baffling to me that basic database functionality like EXPORT and IMPORT doesn't preserve IDs (even with "preserveClusterIds") but here we are.
