### ISSUE TITLE
Please update official PhpOrient driver

### ISSUE THREAD

**Issue by spanyukov** [orientechnologies/orientdb#8165]
### OrientDB Version: 3.0
Here it is
https://github.com/orientechnologies/PhpOrient

I have orientdb 3.0 RC2 and I have recently found out that I cant use the db in development since offical driver is outdated. I`ve been using it for some period of time but now its to risky cuz too many unstable issues have happened

**Comment by lvca** [comment]
I'm sorry, but the PHP driver is not officially maintained. Anybody volunteer from the community to upgrade the protocol for PHP?

**Comment by futureglorydev** [comment]
@lvca  I found another way for a while. Is it possible to use orientdb studio rest api to communicate with the db without restrictions? (I haven`t found any yet)
I`ve tried to perform a query in the postman and got the result in json as if the query was performed in orientdb studio. I think it`s enough for start.
