### ISSUE TITLE
Batch Conditionals in v3.0.0-RC2 result in NullPointerException

### ISSUE THREAD

**Issue by pulzzejason** [orientechnologies/orientdb#8166]
### Java Version: 1.8.0_151
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)  
### OS: Ubuntu 16.04.3 LTS
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

## Expected behavior  
Using the Studio UI at port 2480 in BATCH mode:
`if (1 < 2) { return 'yes'; }`
Should return 'yes'

_Screenshot using OrientDB v2.2.15_
<img width="712" alt="OrientDB v2.2.15" src="https://user-images.githubusercontent.com/18404903/37626510-901b6240-2b8d-11e8-9d3d-a7c4644c8b24.png">

## Actual behavior  
Causes NullPointerException

_Screenshot using OrientDB v3.0.0RC2_
<img width="800" alt="OrientDB v3.0.0RC2" src="https://user-images.githubusercontent.com/18404903/37626518-94f3a1c4-2b8d-11e8-81a0-724fbeebdea2.png">

## Steps to reproduce  
Navigate to OrientDB UI, click on Browse, click the wrench for 'Query configuration', and change the type to BATCH.
Enter the following into the text field:
`if (1 < 2) { return 'yes'; }`

I hope that I am simply misunderstanding the new batch requirements.  I know that there were changes with regards to newline characters and semicolons.  I cannot seem to make this work using the HTTP API or the Studio UI.

**Comment by luigidellaquila** [comment]
Hi @pulzzejason 

Thank you very much for reporting, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @pulzzejason 

I just pushed a fix, it will be released with the GA

Thanks

Luigi
