### ISSUE TITLE
[QUESTION] Summing up embeddedmap item amounts in an embeddedlist with condition

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#8167]
Hi,

Supposedly there's a set of records where each record looks like the following:

```json
    {
        "total": 300,
        "items": [
           {
               "id": "item1",
               "amount": 100
           },
           {
               "id": "item2",
               "amount": 200
           },
        ]
    }
```

Is it possible to do a sum of all totals and items with id = "item1"?

So basically, smth like this (i know that query is ultimately incorrect, but just to show the idea):

```sql
    select sum(total) as total, sum(items(id="item1").amount) as item1Amount
    from MyRecord 
```

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

The right syntax is as follows (with square brackets):

```
select sum(total) as total, sum(items[id="item1"].amount) as item1Amount
    from MyRecord 
```

Thanks

Luigi

**Comment by andreyvk** [comment]
@luigidellaquila Thank you so much! This was extremely helpful and useful
