### ISSUE TITLE
Index not used to compute distinct()

### ISSUE THREAD

**Issue by georgiana-b** [orientechnologies/orientdb#8169]
### Java Version: 
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (IcedTea 3.7.0) (build 1.8.0_161-b12 suse-1.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.161-b12, mixed mode)
### OS: OpenSUSE Tumbleweed 20180314
Linux Kernel Version: 4.15.8-1-default  

## Expected behavior  
I have a `NOTUNIQUE_HASH_INDEX` called `Bid.xCountry`. I was expecting it to be used when I run:

```sql
SELECT distinct(xCountry) FROM Bid; 
```

## Actual behavior  
As you can see below the index exists but it is not used to compute `distinct` so the command ends up taking very long (4.76 seconds for 305612 vertices)

![country_index_not_used](https://user-images.githubusercontent.com/8862002/37778482-bb36a0e0-2df2-11e8-83f7-b2e87b525671.png)

## Steps to reproduce 

Create a `NOTUNIQUE_HASH_INDEX` for a field then run a `distinct()` on that field.

**Comment by georgiana-b** [comment]
For the record, I did try to access the values directly from the index as described [here](https://orientdb.com/docs/last/Indexes.html#querying-index-entries) but nothing is returned. It seems I can only fetch values by key from the index.

![cant_get_index_values](https://user-images.githubusercontent.com/8862002/37779146-58a0452e-2df4-11e8-9158-4fcec4938553.png)

**Comment by luigidellaquila** [comment]
Hi @georgiana-b 

The Hash index implementation does not have an iterator, so you cannot use it to iterate through its values. If you need this functionality, my suggestion is to use a normal NOTUNIQUE index.

The query engine right now does not use indexes to calculate DISTINCT. We will eventually support it in v 3.0, but probably it won't be ported to v 2.2.x

Thanks

Luigi

**Comment by georgiana-b** [comment]
Thank you, Luigi! 

I wanted to iterate through the index just to check if it would be faster. I tried it with a `NOTUNIQUE` index like you said and indeed it runs in 0.500 sec as opposed to almost 5 sec without the index:

![faster_with_the_index](https://user-images.githubusercontent.com/8862002/37781748-fccb7eca-2df9-11e8-81d1-d56754693f85.png)

However, I can't use this in my app because I need to filter by other fields of the class.
Anyway, I'm glad you're improving this in ODB 3. Looking forward!
