### ISSUE TITLE
Why OrientDB can not use indexes for searching with "like" operration? eg. select account from Account where account like '123%'. 

### ISSUE THREAD

**Issue by zhfneu** [orientechnologies/orientdb#8171]
## Expected behavior  
<add here>  

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
HI @zhfneu 

There is no technical blocker for this, it was just not implemented yet. 
Probably it will never be implemented in v 2.2, but we will definitely add support for it to v 3.0 in the short term

Thanks

Luigi
