### ISSUE TITLE
in cluster env, the st_within cannot work properly

### ISSUE THREAD

**Issue by hp1975** [orientechnologies/orientdb#8173]
## Expected behavior  
in cluster env, the st_within cannot work properly

## Actual behavior  
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on par
sing query at position #139: Error on parsing query
Query:  ST_WITHIN(geometry, 'POLYGON ((103.843980 1.387330, 103.843980 1.387630,
 103.811531 1.387630, 103.811531 1.387330, 103.843980 1.387330))') = true

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @hp1975 

Could you please provide a sample dataset (or an SQL script to create it) and a complete query to reproduce the problem?

Thanks

Luigi

**Comment by hp1975** [comment]
@luigidellaquila , below funciton actually throws exceptions: I think you can understand the context by this function.

Fail to commit, error: Quorum (2) cannot be reached on server 'node1522052613078' database 'isc-jmeter' because it is major than available nodes (1)


    private void createGraphNode(OrientIotObject iotObject)
            throws TopologyException {
        iotObject.verify();
        Map<String, Object> properties = readGraphNodePropertiesFromIotObject(
                iotObject);
        OrientGraph dbConnection = this.getDbConnection();
        assert dbConnection != null;
        try {
            OrientVertex node = dbConnection.addVertex("class:" + iotObject.getFormat());
            assert node != null;
            node.setProperties(properties);
            this.commit();
        } catch (Exception e) {
            this.rollback();
            String errorMsg = String.format(EXCEPTION_TMP, e.getMessage());
            LOGGER.error(errorMsg);
            throw e;
        }
    }

**Comment by luigidellaquila** [comment]
Hi @hp1975 

The exception you reported in the second post is completely different, it seems to be a problem with your distributed cluster (ie. not enough nodes available to reach the quorum...)

Luigi

**Comment by hp1975** [comment]
@luigidellaquila 
problem is solved by
1. install the spatial plugin
2. reinstall distributed orientdb
