### ISSUE TITLE
LUCENE operator not available from graph pattern MATCH statement

### ISSUE THREAD

**Issue by CyprienGottstein** [orientechnologies/orientdb#8176]
## Expected behavior  
I am trying to use `LUCENE` string pattern matching within graph pattern matching. The query looks like this :

`MATCH
{class: Alpha, as:a, where:( name = "helloworld ")} -SimpleLink-> {class:Beta, as:b, where:(domain LUCENE "*issues*")}
RETURN a`

## Actual behavior  
The OrientDB Server fails to execute the query and throws an UnsupportedOperationException. Here is the corresponding stacktrace taken from the OrientDB server console output.

> Exception `65F6AAFA` in storage `plocal:/opt/orientdb/databases/lucene_issue_db`: 2.2.30 (build 43d850df23c0fd1edca7279761c2238fdc6cc576, branch 2.2.x)
> com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.MATCH {class: Alpha, as:a, where:( name = "helloworld ")} -SimpleLink-> {class:Beta, as:b, where:(domain LUCENE "*issues*")} RETURN a
> 	DB name="lucene_issue_db"
> 	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3442)
> 	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3339)
> 	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.command(ODistributedStorage.java:259)
> 	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
> 	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
> 	at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
> 	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
> 	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
> 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
> Caused by: java.lang.UnsupportedOperationException: LUCENE operator cannot be evaluated in this context
> 	at com.orientechnologies.orient.core.sql.parser.OLuceneOperator.execute(OLuceneOperator.java:21)
> 	at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.evaluate(OBinaryCondition.java:36)
> 	at com.orientechnologies.orient.core.sql.parser.ONotBlock.evaluate(ONotBlock.java:31)
> 	at com.orientechnologies.orient.core.sql.parser.OAndBlock.evaluate(OAndBlock.java:32)
> 	at com.orientechnologies.orient.core.sql.parser.OOrBlock.evaluate(OOrBlock.java:33)
> 	at com.orientechnologies.orient.core.sql.parser.OAndBlock.evaluate(OAndBlock.java:32)
> 	at com.orientechnologies.orient.core.sql.parser.OWhereClause.matchesFilters(OWhereClause.java:40)
> 	at com.orientechnologies.orient.core.sql.parser.OMatchPathItemIterator.loadNextInternal(OMatchPathItemIterator.java:102)
> 	at com.orientechnologies.orient.core.sql.parser.OMatchPathItemIterator.loadNext(OMatchPathItemIterator.java:63)
> 	at com.orientechnologies.orient.core.sql.parser.OMatchPathItemIterator.<init>(OMatchPathItemIterator.java:54)
> 	at com.orientechnologies.orient.core.sql.parser.OMatchPathItem$1.iterator(OMatchPathItem.java:58)
> 	at com.orientechnologies.orient.core.sql.parser.OMatchStatement.processContext(OMatchStatement.java:632)
> 	at com.orientechnologies.orient.core.sql.parser.OMatchStatement.processContextFromCandidates(OMatchStatement.java:566)
> 	at com.orientechnologies.orient.core.sql.parser.OMatchStatement.calculateMatch(OMatchStatement.java:552)
> 	at com.orientechnologies.orient.core.sql.parser.OMatchStatement.execute(OMatchStatement.java:289)
> 	at com.orientechnologies.orient.core.sql.parser.OMatchStatement.execute(OMatchStatement.java:264)
> 	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:70)
> 	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3421)
> 	... 8 more

## Steps to reproduce  
I've joined a very simple database export which shows the issue. You just have to execute the OSQL query above to make it appear.
[lucene_issue_db.gz](https://github.com/orientechnologies/orientdb/files/1855115/lucene_issue_db.gz)

I don't know if this actually normal, but since there is no limitations warning in the documentation, i'm submitting this issue.

Best Regards,

Cyprien Gottstein.

**Comment by CyprienGottstein** [comment]
Hello, any news on this ?

**Comment by CyprienGottstein** [comment]
This issue is still active on OrientDB 3.0.3.

**Comment by maggiolo00** [comment]
Hi @CyprienGottstein 

did you try the lucene functions? The operator will be deprecated soon

https://orientdb.com/docs/3.0.x/indexing/Full-Text-Index.html

**Comment by CyprienGottstein** [comment]
Hi @maggiolo00 

I just tried the new lucene functions, thanks for highlighting that, I didn't saw properly the updates into the release notes, my bad.

Now, it seems to do the job, i'm just wondering about the result of some queries. With the exact same dataset available in the database above, if I run the following query :

`select * from Beta where SEARCH_INDEX("Beta.domain", "issues") = true`

It still returns me the record from beta, even though its domain attribute value is "https://github.com/orientechnologies/orientdb/issues/new". How does SEARCH_INDEX work exactly ? Is it just relaying the second parameters value to the Lucene engine and i should check Lucene documentation ?

Thanks again

**Comment by maggiolo00** [comment]
Hi @CyprienGottstein 

the first parameter is the the name of the index, and the second is the lucene query that should be passed on to the Lucene engine.

Do you get differente result with operator and function?

**Comment by CyprienGottstein** [comment]
Hi again @maggiolo00 

No I get the same result, its fine.

I understood why the query is working even though it shouldn't, the query I used to make the test induced me in error.

By default the standardAnalyzer (which I used for this index) doesn't tokenize url and the value "https://github.com/orientechnologies/orientdb/issues/new" is broken in several pieces using its punctuation.

Thus it returns true if try a contain with "issues" and it returns false if i try a contain with "issue". The behavior is fine, all i need now is  to check what is the best option (standardAnalyzer or urlAnalyzer) in our usecase.

Everything is fine for now.

**Comment by maggiolo00** [comment]
Ok @CyprienGottstein 

let me know if you need something on this

Thanks

**Comment by CyprienGottstein** [comment]
Hello @maggiolo00 

We did some tests on our side and we have a problem, we need to perform prefix search on URL like "give me every URL that starts with http://a/b/" and we didn't found the appropriate index for that purpose.

When i try query with Lucene DICTIONARY_HASH_INDEX index, even though i have cases where the answer is almost instantaneous, if i use EXPLAIN on my queries it shows well that no indexes are used.

This shows well that the response time can not be trusted, sometimes it is instantaneous because the data i'm asking for are the first on the system will read in an exhaustive manner (even though its already loaded in memory) and the default limit of OSQL will make the read exit as soon as possible thus ending the query. The same query, by just changing the value of the url, can go from 1 to 150 secs.

In theory, the Lucene Dictionary Index should match our use case but it doesn't seems like we can actually use it from OrientDB, and since the StandardAnalyzer pretty much screws us if we use Lucene FULLTEXT index, i don't see any other things.

Any tips about how to tackle this ?

**Comment by matanshukry** [comment]
@wolf4ood Actually, I can't get SEARCH_CLASS to work with the match command.
This works:
```
MATCH {class:Person, where:(userId = "matan"),as:thePerson} RETURN $elements
```

This doesn't:
```
MATCH {class:Person, where:(SEARCH_CLASS("matan")),as:thePerson} RETURN $elements
```
It results in:
```
orientdb {db=mydb}> Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
match {class:Person, where:(SEARCH_CLASS("matan")),as:thePerson} RETURN $elements
                                     ^
Encountered "" at line 1, column 27.
Was expecting one of:
    
	DB name="mydb"
	Error Code="1"
	DB name="mydb"
```

It possibly requires a different syntax?
