### ISSUE TITLE
ODatabaseException OrientDB Record Error

### ISSUE THREAD

**Issue by phfilly** [orientechnologies/orientdb#8177]
## Expected behavior  
Get an clean error-less run-through when running `REPAIR DATABASE --fix-graph -v` or `CHECK DATABASE`

## Actual behavior  

Getting an exception:
```
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #58:65894 (cluster: cluster_name_here)
	DB name="DBNAME"
	DB name="DBNAME"

Error: java.lang.ArrayIndexOutOfBoundsException
```
Which then limits me as I can't insert new data etc. I've followed these docs: https://orientdb.com/docs/last/Console-Command-Repair-Database.html

## Steps to reproduce  
Executing  `REPAIR DATABASE --fix-graph -v` or `CHECK DATABASE`

Any help or directions will be greatly appreciated.

**Comment by laa** [comment]
@phfilly could you send full stack trace?

**Comment by phfilly** [comment]
@laa not 100% sure but is this what you want? :)

```orientdb {db=DBNAME}> REPAIR DATABASE --fix-graph -v
Repair of graph 'remote:localhost/DBNAME' is started ...
Scanning 2021110 edges (skipEdges=0)...

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #58:65894 (cluster: cluster_name_here)
	DB name="DBNAME"

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #58:65894 (cluster: cluster_name_here)
	DB name="DBNAME"
	DB name="DBNAME"

Error: java.lang.ArrayIndexOutOfBoundsException```

**Comment by phfilly** [comment]
Any recommended steps to try and resolve this?

**Comment by laa** [comment]
Hi @phfilly , do you have any errors in the server log file, could you send them as a gist?
