### ISSUE TITLE
Start distributed orientdb is fail,even to use new installation package

### ISSUE THREAD

**Issue by zjm138238** [orientechnologies/orientdb#8181]
**OrientDB Version: 2.2.33
Java Version: 1.8
OS: Centos 6.9**

**Expected behavior**  
Start distributed orientdb is success,and the status of the database(GratefulDeadConcerts) should be always ONLINE but not NOT_AVAILABLE.

**Actual behavior**  
Start distributed orientdb is fail,the log shows that the status of the database(GratefulDeadConcerts) is changing  all the time.
![image](https://user-images.githubusercontent.com/19428981/38074586-c6370ca4-3361-11e8-863e-1c79ba58beae.png)
and when I try to write data to the database,it is wrong
![image](https://user-images.githubusercontent.com/19428981/38076050-02f184b2-3367-11e8-8efa-f54717624485.png)

**Steps to reproduce**  
1、download orientdb-community-importers-2.2.33.zip
2、unzip orientdb-community-importers-2.2.33.zip
3、set up the config/hazelcast.xml
`<network>
    <port auto-increment="false">2434</port>
    <join>
            <multicast enabled="false">
                    <multicast-group>235.1.1.1</multicast-group>
                    <multicast-port>2434</multicast-port>
            </multicast>
            <tcp-ip enabled="true">
                <member>10.0.21.4</member>
                <member>10.0.21.5</member>
                <member>10.0.21.6</member>
            </tcp-ip>
    </join>
</network>`
and there are three nodes,their node names are node1,node2 and node3.
4、execute bin/dserver.sh in 10.0.21.4 machine,and then execute bin/dserver.sh in 10.0.21.5 machine

how to solve the problem？thanks！

**Comment by tglman** [comment]
Hi @zjm138238,

This is a known issue, please update to 2.2.34, it should fix this problem.

Regards
