### ISSUE TITLE
OrientDB used as a Key Value DBMS ?

### ISSUE THREAD

**Issue by Zhangjp0** [orientechnologies/orientdb#8182]
### OS: centos7
 
How to use OrientDB as a Key Value DBMS ?   How to store data ?  What is Key and what is Value ?
And How to build index on its data ? 
Are there any cases about OrientDB as a Key Value DBMS ?

Thanks.

**Comment by cuijinyi** [comment]
见文档的 DataModleing 那章，对比：

Relational Model | Key/Value Model | OrientDB Key/Value Model
-- | -- | --
Table | Bucket | Class or Cluster
Row | Key/Value pair | Document
Column | not available | Document field or Vertex/Edge property
Relationship | not available | Link

**Comment by shushengxing** [comment]
我看过这些文档，想找一个完整的OrientDB用于Key Value数据库的例子，看一下其中的索引时怎么运用的。
您是否有这方面资料。

谢谢！
