### ISSUE TITLE
Error reporting in studio ui could be improved

### ISSUE THREAD

**Issue by brunson** [orientechnologies/orientdb#8183]
## Expected behavior  
When logging in to the studio web ui in a newly started container you're presented with a login form containing fields for username and password.  I would expect to enter the root username and password and get a valid connection.

## Actual behavior  
Entering the valid username and password results in a message "Invalid user name or password". But this is because there is no valid database to select.  I had to use developer tools in my browser to inspect the body of the 500 internal server error response from the server and see that it was returning a message in JSON to the effect of "The database undefined does not exist".

This led me to create a database, then I was able to connect.  However, it took me the better part of a day to confirm that it wasn't in fact an authentication error.

Could the error body be displayed to the user upon failure, rather than a generic authentication error?

## Steps to reproduce  
Follow the instructions in the documentation for starting a docker container, then use a browser to connect to port 2480 and attempt to log in to the studio ui.

**Comment by maggiolo00** [comment]
Hi @brunson 

Thanks for reporting this

Yes the database is mandatory for login.  The best way is prevent login if no database are selected.

I will mark this as enhancement
