### ISSUE TITLE
order by lucene properties

### ISSUE THREAD

**Issue by hosseinGanjyar** [orientechnologies/orientdb#8184]
### OS: win server

I have this problem with orientdb v2.2.31. I have vertex Users with properties **id (no index), name (lucene index), family(lucene index)**.

My quesry is :

> SELECT @rid, name , family FROM users
order by name asc
limit 10

This query is very slow (exc in ~17 seconds).
Do you best idea?
Thanks

**Comment by luigidellaquila** [comment]
Hi @hosseinGanjyar 

Why can't you use normal indexes? Are these columns too wide? (please consider that you can have lucene and non-lucene indexes on the same properties, OrientDB allows it).

If the strings you are storing are too wide for a normal index, maybe you can store the first characters (say the first few tens or hundreds) on another field, index it and do the ORDER BY on it

Thanks

Luigi
