### ISSUE TITLE
Config ridBag.embeddedToSbtreeBonsaiThreshold=2147483647 doesn't work.

### ISSUE THREAD

**Issue by royalpinto** [orientechnologies/orientdb#8185]
## Expected behavior  
Consider config value supplied ridBag.embeddedToSbtreeBonsaiThreshold= 2147483647

## Actual behavior  
In a distributed mode (2 nodes), it keeps throwing/flooding below error:

```bash
Mar 31 11:22:31 ctv-database-20180331 supervisord: profx com.orientechnologies.orient.core.exception.OAccessToSBtreeCollectionManagerIsProhibitedException: Access to the manager of RidBags which are based on B-Tree implementation is prohibited. Typically it means that you use database under distributed cluster configuration. Please check that following setting in your server configuration ridBag.embeddedToSbtreeBonsaiThreshold is set to 2147483647
```
We tried setting `ridBag.embeddedToSbtreeBonsaiThreshold=2147483647` as suggested in the error line. We also tried setting `ridBag.sbtreeBonsaiToEmbeddedToThreshold=2147483647` but no luck. We could see that these settings are getting applied at startup using the `-Denvironment.dumpCfgAtStartup=true` flag, but this error still repeats.

We use OrientJS driver to connect to the database from App.

What could be the issue ?

**Comment by tglman** [comment]
Hi @royalpinto,

This is solved in 2.2.33

Regards
