### ISSUE TITLE
OrientDB as a Key Value DBMS ?

### ISSUE THREAD

**Issue by shushengxing** [orientechnologies/orientdb#8186]
OrientDB Version: 2.2.30
Java Version: jdk1.8
OS: centos7

How to use OrientDB as a Key Value DBMS ? How to store data ? What is Key and what is Value ?
And How to build index on its data ?
Are there any cases about OrientDB as a Key Value DBMS ?

I look forward the help.
Thanks very much.

**Comment by tglman** [comment]
Hi,

duplicate of : https://github.com/orientechnologies/orientdb/issues/8182
