### ISSUE TITLE
Insecure HTTP download links on OrientDB website

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#8190]
When downloading OrientDB from the [following link](https://orientdb.com/download-previous/), the download links are all links to `bit.ly` but use HTTP instead of HTTPS. This means that, in principle, an attacker could intercept the request to e.g. `http://bit.ly/orientdb-ce-2-2-33` and produce a malicious executable instead of the user's desired OrientDB version.

This is made even more problematic by the fact that the link immediately downloads a file, and does not lead to a website where the user can notice the lack of an "HTTPS padlock" in their browser's address bar.

Since `bit.ly` supports HTTPS, I think all those links can be replaced with corresponding HTTPS links, for example: `https://bit.ly/orientdb-ce-2-2-33`.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

Thank you for pointing it out, I'll fix it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed, thanks!

Luigi
