### ISSUE TITLE
Optimize query execution

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#8193]
### OrientDB Version: 2.2.33

This is not an issue but a request for advice on how to optimize a document database in order to speed up the execution of  query.

I have a very simple model with 2 entities:

**Resource** entity, with the following fields:

- key, which is a business id (a String). It's unique.

- versions, which is a LinkList of version entities.

**Version** entity

- owner, which is a Link to its resource.

- number, an integer representing the version number.

I want to query all the versions of a Resource given its key. The query I came to is:
`select from Version where owner.key = "whatever"`

Which works, but when the amount of documents in the Resource class is high (let's say about 20k) the execution time is high, and this is a query we have to execute many times. I have tried to optimize the execution by adding an index on **Resource.key** but I have not seen any improvement.

Is there a way to tune the database in order to reduce the execution time for this query?

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

First of all, why did you go with a linklist approach instead of an edge?

With a graph from Version to Owner, you could do the query as follows:

```
SELECT expand(in("HasOwner")) from Owner where key = 'whatever'
```

and there would be no need on your side to maually maintain the link vs linklist structures aligned.

Anyway, you can optimize the query also with this model, please try the following:

```
SELECT expand(versions) from Resource where key = 'whatever'
```

Just make sure to have an index on `Resource.key`, it will make the query very fast

Thanks

Luigi

**Comment by diegomtassis** [comment]
Thanks by the answer Luigi.

Long story short, we have our own object layer API (a subset of JPA), which we first implemented using OrientDB object API (still in use in some of our projects), but then decided to create another implementation directly on top of OrientDB Document API.

When it comes to querying, our object layer API includes a very high level fluent API which creates an intermediate representation (based in the AST of an ANSI-SQL grammar), which then is compiled to different SQL dialects, OrientDB SQL among others.

Obviously our compiler does not make use of all OrientDB specific contructions, though we leverage some of them (this is a very long story).

The point is that our queries are not built manually, they are compiled from an intermediate representation (the AST), so when it comes to optimize, it is much easier for us to do it by adding indexes or changing the db schema than by changing the query.

Diego.

**Comment by diegomtassis** [comment]
Problem solved. I've managed to change a little bit the model so now I can query from _Resource_ and the index is used.
