### ISSUE TITLE
Cannot find the folder "bin" to run "dserver.sh"

### ISSUE THREAD

**Issue by LianaN** [orientechnologies/orientdb#8198]
### Java Version:
```
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
```
### OS: CentOS 7
 
I am installing a distributed version of OrientDB from source following these guidelines:
[https://orientdb.com/docs/3.0.x/admin/installation/Installation-from-Source.html](https://orientdb.com/docs/3.0.x/admin/installation/Installation-from-Source.html)  

After executing `mvn clean install`, I cannot find the folder `bin` in order to run `dserver.sh`. I found the script `dserver.sh` under the path `distributed->script`, but then I get the error:

```
./script/dserver.sh: line 50: cd: /home/centos/orientdb/distributed/bin: No such file or directory
./script/dserver.sh: line 114: /home/centos/orientdb/distributed/bin/orient.pid: No such file or directory
Error: Could not find or load main class com.orientechnologies.orient.server.OServerMain
```

**Comment by luigidellaquila** [comment]
Hi @LianaN 

After the build is executed, you will find the final distribution in the `/distribution/target/` folder

I hope it helps

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @LianaN 

I hope it was helpful, I'm closing this ticket for now, but feel free to re-open if you need further help

Thanks

Luigi
