### ISSUE TITLE
How can query a batch vertices by using a graphAPI ?

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#8199]
### Java Version: 1.8

We use graphAPI for getting vertices. We want a one batch API, and the execution result is same as the result of  executing the  “select from Code where codeId in ("1","2") ” . The result of the SQL is two vertices of "Code". The vertex's name is "Code", and have unique index called "codeId". 

We found the api like  "public Iterable<Vertex> getVertices(String label, String[] iKey, Object[] iValue) ",  but this function can't meet our requirements.

How can query a batch vertices by using a graphAPI ?
        
Thanks a lot!

**Comment by luigidellaquila** [comment]
Hi @KishoDai 

There is no direct way to do batch queries (eg. queries with IN conditions) with a native graph API, apart from using an SQL query as follows:

```
graph.command(new OCommandSQL("select from Code where codeId in ('1', '2')")).execute();
```

Thanks

Luigi

**Comment by KishoDai** [comment]
OK. Thanks!
