### ISSUE TITLE
Search Engine [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#82]
This is [Issue 82](http://code.google.com/p/orient/issues/detail?id=82) moved from a Google Code project.
Added by 2010-07-29T16:03:35.000Z by [l.garu...@gmail.com](http://code.google.com/u/111607061083712272202/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, v2.0.0

### Original description

    After the implementation of the Full Text index against class properties, it's relatively easy to provide a central &quot;Search Engine&quot; that index Orient documents following some configuration like:
    - classes/properties to index
    - custom StopWord list
    - custom events called at every indexing phase to better control the indexing with custom rules

**Comment by robfrank** [comment]
OLD STUFF. Lucene integrated,
