### ISSUE TITLE
OrientDB Indexing

### ISSUE THREAD

**Issue by ameerthehacker** [orientechnologies/orientdb#8202]
What is the best way that I can have a full text indexing on the data stored in orientDB

**Comment by luigidellaquila** [comment]
Hi @ameerthehacker 

We have LUCENE indexes for this, see https://orientdb.com/docs/2.2.x/Full-Text-Index.html

Thanks

Luigi

**Comment by ameerthehacker** [comment]
Thanks @luigidellaquila
