### ISSUE TITLE
Index in a property of a class is not used when querying on a direct super class

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#8205]
### OS: Windows, Linux

Index in a class is not used when querying on a direct super class.

This issue is related to these 2 other issues:
[Optimize query execution](https://github.com/orientechnologies/orientdb/issues/8193)
[use index defined on subclasses when querying the superclass](https://github.com/orientechnologies/orientdb/issues/3361)

The context is the object layer that we have.

In the 1st ticket I asked how to optimize the query to leverage the existing index. I closed the ticket because I managed to change the query, which improved the result time, but I've just realized that the index is still not being used.

There is a OClass called _Resource_, which is abstract, that represents a java interface with the same name.
There is a OClass called _DefaultResource_ that represents a java class with the same name. It inherits from _Resource_. This class has a property called _key_, and there is an index on this key.

Executing `select from Resource where key = 'whatever'` does not use the index.
Executing `select from DefaultResource where key = "whatever"` does use the index.

![explain](https://user-images.githubusercontent.com/5831026/38566835-fe8d5b76-3ce4-11e8-96f5-ec5ad2994bfd.jpg)
![indexes](https://user-images.githubusercontent.com/5831026/38566218-78bc9c6a-3ce3-11e8-910c-b2f28218340b.jpg)
![schema](https://user-images.githubusercontent.com/5831026/38566219-78d2f604-3ce3-11e8-93f1-95fc007e2136.jpg)

**Comment by Promotos** [comment]
I'm facing the same issue on my orientdb instance. Are there any updates or hints how to get the execution plan to use the index.
Thanks in advance
