### ISSUE TITLE
Change AES-ECB to AES-GCM

### ISSUE THREAD

**Issue by overheadhunter** [orientechnologies/orientdb#8207]
## Expected behavior  
When using encryption I expect the encryption to be effective.

## Actual behavior  
Encryption is using AES-ECB or even worse: DES-ECB. As @obi1kenobi and @compensator pointed out in issue #89, this is effectively the same as not encrypting at all.

---

I suggest dropping DES and changing AES-ECB to AES-GCM or some other secure mode of operation. I am happy to provide a pull request, if you help me understand [this interface](https://github.com/orientechnologies/orientdb/blob/2.2.33/core/src/main/java/com/orientechnologies/orient/core/encryption/OEncryption.java):
- Are the `byte[] content` passed to the encrypt/decrypt methods containing the whole file content of the `plocal` storage?
- Are there any random access characteristics that must be preserved during I/O?

**Comment by tglman** [comment]
Hi @overheadhunter,

Yes that interface is the interface that you have to implement, the byte[] correspond just to the record not to the whole file, be aware that the implementation for works need to be registered [here](https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/orient/core/encryption/OEncryptionFactory.java#L49) 

due to the fact that is record level there is no need of IO interaction. 

Regards

**Comment by overheadhunter** [comment]
I see, so one `byte[]` represents one single record. Is it allowed to return an array of a slightly larger size than passed to the encrypt function?

**Comment by tglman** [comment]
Hi @overheadhunter,

Yes is possible.

Regards

**Comment by overheadhunter** [comment]
@tglman What are your policies regarding pull requests and integrating them into the release roadmap? I strongly suggest scheduling this for the next hotfix release, as many applications may rely on OrientDB being suitable for storage of sensitive information.

**Comment by tglman** [comment]
Hi @overheadhunter,

We do not introduce new feature with hotfix, all the feature PR have to target the develop branch and will land in the next minor/major, there are some time exceptions with critical small changes often sponsored that with additional quality check we may include in the hotfix, but this is done every time on specific case.

regards

**Comment by overheadhunter** [comment]
Ok, I see. Is it too late for 3.0.0?

**Comment by tglman** [comment]
Hi @overheadhunter,

Internally the 3.0.0 is already closed, so probably yes.

Regards
