### ISSUE TITLE
WrtieQuorum in Distributed Mode

### ISSUE THREAD

**Issue by hossein-md** [orientechnologies/orientdb#8220]
### OS: <os here>  Linux
I saw the following config a lot:
```
{
  "autoDeploy": true,
  "hotAlignment": false,
  "readQuorum": 1,
  "writeQuorum": 2,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,
  "clusters": {
	"internal": {
	},
	"index": {
	},
	"client_0": {
  	"servers" : [ "europe", "usa" ]
	},
	"client_1": {
  	"servers" : [ "usa" ]
	},
	"client_2": {
  	"servers" : [ "asia", "europe", "usa" ]
	},
	"*": {
  	"servers" : [ "<NEW_NODE>" ]
	}
  }
}
```
My question is: How is it possible to have writeQuorum = 2 while the shard "client_1" is in just one node(usa)?

**Comment by careerscale** [comment]
@tglman  so this is same as what we are seeing in 3.0GA too.

**Comment by 33Fraise33** [comment]
interesting point, I think here majority would be better anyway as this changes dynamically with your servers. But no idea what happens if you have writequorum 2 there.
