### ISSUE TITLE
Add the possibility to automatically backup to s3

### ISSUE THREAD

**Issue by 33Fraise33** [orientechnologies/orientdb#8223]
### Feature request

Currently it is possible to let orientdb automatically backup the database on certain time intervals. I would like to plugin on that and at the end of the backup run an upload to amazon. Or even the possibility to run a custom script.

Currently I'm unable to achieve the same backup with the backup.sh script when my database is running.

**Comment by luigidellaquila** [comment]
Hi @33Fraise33 

This feature will be available out of the box with the Enterprise version. There will be an option for automatic upload to S3.

For now in the CE version there is no option to run custom scripts after backup execution, but I think we can consider it

Thanks

Luigi

**Comment by 33Fraise33** [comment]
I'm making an ansible script doing this for me but the problem is that issue #8228 prevents me from fully automating this.

**Comment by 33Fraise33** [comment]
For anyone interested I made a limited version of this working with distributed configurations in ansible.
Link: https://github.com/33Fraise33/orientdb-backup-s3

It would be nice to be able to plugin in the automatic backup provided by orient. This way the database doesn't have to be shutdown even though it gets locked.

**Comment by luigidellaquila** [comment]
Hi @33fraise33 

Thank you very much, for sure this will be useful for the community.

Do you need further help on this issue? Can we close it?

Thanks

Luigi

**Comment by 33Fraise33** [comment]
Yes thanks for the help. Will there be a new issue with the option for custom scripts at the automated backup ?
