### ISSUE TITLE
After combination of setEdge and select by rid index is broken down

### ISSUE THREAD

**Issue by sreznick** [orientechnologies/orientdb#8224]
## Expected behavior  
select by value that is exactly equal with just added should return corresponding vertex

## Actual behavior  
select by value using eqiuals operation does not find expected vertex. select using 'like' comparision finds it. And comenting out some seemingly irrelevant code lines changes behavior. Details are in comment lines of attached source.

## Steps to reproduce  
[Select2.java.txt](https://github.com/orientechnologies/orientdb/files/1928273/Select2.java.txt)

**Comment by laa** [comment]
Looks like tx visibility issue

**Comment by tglman** [comment]
Hi @sreznick,

Thank you for reporting this I could reproduce the problem and fix it.

Regards
