### ISSUE TITLE
How to create a new distributed database in OrientDB using Scala API?

### ISSUE THREAD

**Issue by LianaNapalkova** [orientechnologies/orientdb#8226]
OrientDB Version: 3.0
Java Version:
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode) 

I installed a distributed version of OrientDB on two instances and executed `./bin/dserver.sh` on both of them.

```
------------+
|Name               |Status|Databases             |Conns|StartedOn|Binary           |HTTP             |UsedMemory              |
+-------------------+------+----------------------+-----+---------+-----------------+-----------------+------------------------+
|123_slave(*)|ONLINE|demodb=ONLINE (MASTER)|4    |13:47:29 |192.168.0.17:2424|192.168.0.17:2480|506.22MB/3.83GB (12.90%)|
|123(@)      |ONLINE|demodb=ONLINE (MASTER)|0    |13:47:15 |192.168.0.14:2424|192.168.0.14:2480|424.32MB/3.83GB (10.81%)|
+-------------------+------+----------------------+-----+---------+-----------------+-----------------+------------------------+
```

Now I want to create a database using Scala API.  This is the way that I found in the documentation of OrientDB:

```
val uri: String = "plocal:target/database/GRAPH_1"
val graph: OrientGraph = new OrientGraph(uri)
```

In my case I have two instances. So, how should I specify the `uri` string?

**Comment by 33Fraise33** [comment]
Hello,

I'm not a scala expert but when you're running in distributed mode you will likely connect remotely. so that should be: 'remote:192.168.0.17/database/GRAPH_1'

**Comment by 33Fraise33** [comment]
Ok that's about as much as I could help you with my orient knowledge. I'll ping @luigidellaquila

**Comment by LianaNapalkova** [comment]
Ok, below I provide the code that does not actually create a database, but it expects that the database is already created. My question is how can I create the database from code:
val uri: String = "remote:172.20.61.57/database/ACCESO_GRAPH_TEST"
    val username: String = "root"
    val password: String = "123"
    val factory: OrientGraphFactory = new OrientGraphFactory(uri, username, password)
    val graph: OrientGraph = factory.getTx()

**Comment by luigidellaquila** [comment]
Hi @LianaNapalkova 

Please, try to remove the `database/` from the URL, it's not needed and probably it's creating the problem.
So just 

```
val uri: String = "remote:XXX.XX.XX.XX/GRAPH_TEST"
```

If it still fails, could you please the full logs of the client and the node you are connecting to?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @LianaNapalkova 

Did my suggestion help? Do you still need help on this issue?

Thanks

Luigi

**Comment by LianaN** [comment]
I will check it during this week and report the result.

**Comment by LianaN** [comment]
Hi @luigidellaquila,

I am testing now this code with OrientDb for docker. The uri is defined as follows:

`val uri: String = "remote:127.0.0.1/GRAPH_TEST"`

But I still cannot create the database GRAPH_TEST. I am getting the `java.lang.NullPointerException` error, because `graph` is null.

This is how I create oriented container.

```
  orientdb:
      image: orientdb:2.2.33
      container_name: orientdb
      command: server.sh
      ports:
        - "2424:2424"
        - "2480:2480"
      environment:
        - "ORIENTDB_ROOT_PASSWORD=123"
      restart: "no"
```
