### ISSUE TITLE
How to assign alias to DB?

### ISSUE THREAD

**Issue by LianaNapalkova** [orientechnologies/orientdb#8227]
OrientDB Version: 3.0
Java Version:
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

Is it possible to assign an Alias to a database in OrientDB at the moment of creating it?

`val graph: OrientGraph = new OrientGraph(uri,username,password)`

For example, I should create a new database each day, but I want each new database to have the same Alias.

**Comment by tglman** [comment]
Hi,

As today we have no such feature, anyway for the case of a new database each day, you could backup the db drop the existent and recreate a new one.

Hope this help, regards.
