### ISSUE TITLE
When running 'exit;' through a script in console this returns status code 1 (error)

### ISSUE THREAD

**Issue by 33Fraise33** [orientechnologies/orientdb#8228]
## Expected behavior  
When running `./console.sh test.txt` with the test.txt having contents: `exit;` (how you would exit after a script) this should return a clean exit code aka '0'.

## Actual behavior  
The actual return code is 1

## Steps to reproduce  
See expected behaviour. For me this was the following command: 
`docker run --rm -t -v /orientdb/databases:/orientdb/databases -v /orientdb/backup:/orientdb/bin/backup orient3temp /orientdb/bin/console.sh /orientdb/bin/backup/backup.txt` with backup.txt containing `exit;`

running `echo $?` afterwards shows me exit code 1.

**Comment by tglman** [comment]
Hi @33Fraise33,

I think this is an issue of the exit operation in batch mode (batch mode is when you run a script), you can work around it removing the exit command, in batch mode the console will exit as soon as all the script are executed.

Regarads

**Comment by 33Fraise33** [comment]
Hello, 

Thanks for the reply. This solved my issue indeed.
