### ISSUE TITLE
CIRCULAR REFERENCE:com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage

### ISSUE THREAD

**Issue by LianaNapalkova** [orientechnologies/orientdb#8229]
OrientDB Version: 3.0
Java Version:
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

I followed the [documentation of OrientDB 3.0.0](https://orientdb.com/docs/3.0.x/scala/Scala-Language.html) to create a new DB using Scala API:

```
val uri: String = "remote:XXX.XX.XX.XX/database/GRAPH_TEST"
val username: String = "root"
val password: String = "123"
val uri: String = "plocal:target/database/scala_sample"
val factory: OrientGraphFactory = new OrientGraphFactory(uri,username,password)
val graph: OrientGraph = factory.getTx()
```

But I get this error:

> [CIRCULAR REFERENCE:com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'GRAPH_TEST' because it does not exist in path: /root/opt/orientdb/databases/GRAPH_TEST]

**Comment by wallyatkins** [comment]
@LianaNapalkova do you recall what the resolution to this issue was?
