### ISSUE TITLE
NONUNIQUE (sorted) indices should be respected when performing range queries

### ISSUE THREAD

**Issue by lodrion** [orientechnologies/orientdb#8230]
## Expected behavior  
When a sorted index exists on a property, range queries on that property should use the index

## Actual behavior  
range query result in table scan

## Steps to reproduce  

```
create database remote:localhost/test_match <snip>
create class T extends V
create property T.indexed string
create index T.indexed NOTUNIQUE
create vertex T set indexed='0'
create vertex T set indexed='1'
create vertex T set indexed='2'
create vertex T set indexed='3'
create vertex T set indexed='4'
create vertex T set indexed='5'
create vertex T set indexed='6'
create vertex T set indexed='7'
create vertex T set indexed='8'
create vertex T set indexed='9'

EXPLAIN MATCH { class: T, where: (((indexed >= '0') AND (indexed <= '2'))), as: T___1} RETURN $matches

{"@type":"d","@version":0,"documentReads":10,"fullySortedByIndex":false,"compositeIndexUsed":1,"current":"#18:2","documentAnalyzedCompatibleClass":10,"recordReads":10,"involvedIndexes":["T.indexed"],"limit":-1,"fetchingFromTargetElapsed":5,"indexIsUsedInOrderBy":false,"matched":{"T___1":"#17:0"},"evaluated":10,"elapsed":19.67932,"resultType":"collection","resultSize":3,"@fieldTypes":"documentReads=l,compositeIndexUsed=l,current=x,documentAnalyzedCompatibleClass=l,recordReads=l,involvedIndexes=e,fetchingFromTargetElapsed=l,evaluated=l,elapsed=f"}
```
Notice `"recorReads": 10` all records were scanned

**Comment by luigidellaquila** [comment]
Hi @lodrion 

The SQL executor in v 2.2.x sometimes fails at using indexes in the most efficient way. 

If you try the following

```
EXPLAIN MATCH { class: T, where: (indexed >= '0' AND indexed <= '2'), as: T___1} RETURN $matches
```

you'll see that the index is used correctly.

The old query executor is hard to maintain, this kind of optimizations can take a lot of time an effort. For this reason, in v 3.0 we completely re-wrote the query execution planner and executor, so the problem no longer exists

Thanks

Luigi

**Comment by obi1kenobi** [comment]
The GraphQL compiler now rewrites these expressions using the `BETWEEN` operator, which seems to correctly detect and use the appropriate indexes. Here's the PR in case you are curious: https://github.com/kensho-technologies/graphql-compiler/pull/70
