### ISSUE TITLE
Logic of deleting WAL files.

### ISSUE THREAD

**Issue by bipulkarnani** [orientechnologies/orientdb#8232]
## Expected behavior  
WAL files should be present unless `storate.wal.maxSize` is reached and older WAL files are replaced by newer ones.   

## Actual behavior  
WAL files are getting deleted although `storage.wal.maxSize` is not reached and this is causing replication issue since if node in a cluster is down then when it comes back up, it throws the following error: `Requested database delta sync with LSN=LSN{segment=20, position=52} but not found
 in database` as WAL with that particular segment is deleted.

**Comment by laa** [comment]
That is correct behavior, also reaching of exactly maxSize will not change causing of this message.

**Comment by bipulkarnani** [comment]
Hi @laa ,

Thanks for the reply. If reaching of maxSize will not change cause of the issue, then how to avoid this error of `delta sync`?
