### ISSUE TITLE
.toJSON omits commas in object Arrays.

### ISSUE THREAD

**Issue by tolgaulas** [orientechnologies/orientdb#8236]
## Expected behavior  
toJSON on embedded properties should export compliant JSON. array of objects should be comma separated.
```
`[
    {
        "a": "b"
    },
    {
        "c": "d",
        "e": "f"
    },
    {
        "g": {
            "h": "i"
        }
    }
]
```

should export as is.`
## Actual behavior  
.toJSON don't insert commas in-between array elements
`[{"@type":"d","@version":0,"a":"b"}{"@type":"d","@version":0,"c":"d","e":"f"}{"@type":"d","@version":0,"g":{"h":"i"}}] `

## Steps to reproduce  
`insert into testclass content {"testcol":[{"a":"b"},{"c":"d","e":"f"},{"g":{"h":"i"}}]}`

`select testcol.toJSON()`

**Comment by luigidellaquila** [comment]
Hi @tolgaulas 

Thank you very much for reporting, I just pushed a fix, next hotfix release will solve this problem

Thanks

Luigi
