### ISSUE TITLE
After creation of sequence not login in to database is possible

### ISSUE THREAD

**Issue by Cowby** [orientechnologies/orientdb#8237]
## Expected behavior  
Able to login to a specific database

## Actual behavior  
During login attemt following error is fired: 

Connecting to database [remote:localhost/TestDB] with user 'root'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on creation of shared resource
        DB name="TestDB"
        DB name="TestDB"

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT FROM OSequence
        DB name="TestDB"

Error: java.lang.IllegalArgumentException: Cluster 36 is null

## Steps to reproduce  
Created a test sequence to work with the new functioniality on one of our test system: 
$ CREATE SEQUENCE idseq TYPE ORDERED;
$ UPDATE 11:0 SET TEST_SEQ = ideseq.next().prefix('Project-');
Functionality worked like a charm and expected.
After a restart during  the weekend the desired database isn't accesible anymore via any way (see above error messages). Any particular ideas how to fix it? Thanks for any ideas.

**Comment by tglman** [comment]
Hi @Cowby,

I would suggest to update to the last hotfix(currently 2.2.34) we fixed few issue on sequences after the 2.2.17.

Regards

**Comment by Cowby** [comment]
Thanks for the response @tglman. 
Would love to do that, but even when I just move the database to the new installed version (2.2.34), I'm not able to connect to the database. So my problem seems to be that the db where I tested the Sequence functionality is afterwards some kind of corrupted. The underlying problem is that there is no possibility to access the existing sources. Is there any kind of further disaster mode which I could use to access the stored data and scheme?

**Comment by Cowby** [comment]
Just attached a short screenshot of my problem. Tried to access the db direct via the console, used our working root credentials for that.
![20180425_screenorient_error](https://user-images.githubusercontent.com/8361972/39244022-a761e522-488f-11e8-9e4d-863252b26ec2.JPG)
