### ISSUE TITLE
Select Query With Sharding

### ISSUE THREAD

**Issue by hossein-md** [orientechnologies/orientdb#8238]
## Expected behavior  
<add here>  

I use this config:
```
{
  "autoDeploy": true, (Also I have tried false value)
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "static",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "class_01": {
      "servers": ["n01"]
    },
    "class_02": {
      "servers": ["n01","n02"]
    },
    "class_03": {
      "servers": ["n03"]
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```
Does anyone use something like this config and could use this query: `Select from Class` (not `Select from class_01 or Select from class_02 ...`)
As I read "[Read records](https://orientdb.com/docs/2.2.x/Distributed-Sharding.html#read-records)", it is possible to use `Select from Class`. But I can't use it.
Even if I run `Select from cluster:class_03` from n01 I won't have response (I will get error)
If I run `Select from cluster:class_01` from n01 I will get the result.
What should I do?
Thanks

**Comment by saeedtabrizi** [comment]
Hi @hossein-md 
This issue may be  related to read quorum value  issue . 
As you know R + W > N . 
So please set the  `"readQuorum": 1` to `"readQuorum": 2` or more and try to run query again . 
If you have success about it please say **SALAVAT** and let me know it . 
Thanks 
Saeed Tabrizi

**Comment by hossein-md** [comment]
Hi @saeedtabrizi 

I use this config:

```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "static",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "user_usa":{
         "servers" : [ "usa" ]
    },
    "user_eur":{
         "servers" : [ "eur", "usa" ]
    },
    "user_chi":{
         "servers" : [ "chi" ]
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```
I run my servers with “dserver.sh”
I create a table named Sharding
I run “console.sh” and connect to my server:
Connect remote:localhost/Sharding root myPass
My schema:

```
ALTER DATABASE MINIMUMCLUSTERS 3
create class User extends V
create property User.name string
create index User.name unique
alter cluster user name user_usa
alter cluster user_1 name user_eur
alter cluster user_2 name user_chi
```

After use “clusters” console.sh:
```
|18  |user_chi |  28|User     |    0|    chi     |             |       false        |
|19  |user_eur |  27|User     |    0|    eur     |    [usa]    |       false        |
|20  |user_usa |  26|User     |    0|    usa     |             |       false        |
```
I use this code to insert one record per server:
```
public void writeTest()
{
   OrientGraph orientGraph01=new OrientGraph("remote:usa_ip/Sharding");
   HashMap properties01=new HashMap();
   properties01.put("name","name01");
   orientGraph01.addVertex("class:" + "User", properties01);
   orientGraph01.commit();
   orientGraph01.shutdown();

   OrientGraph orientGraph02=new OrientGraph("remote:eur_ip/Sharding");
   HashMap properties02=new HashMap();
   properties02.put("name","name02");
   orientGraph02.addVertex("class:" + "User", properties02);
   orientGraph02.commit();
   orientGraph02.shutdown();

   OrientGraph orientGraph03=new   OrientGraph("remote:chi_ip/Sharding");
   HashMap properties03=new HashMap();
   properties03.put("name","name03");
   orientGraph03.addVertex("class:" + "User", properties03);
   orientGraph03.commit();
   orientGraph03.shutdown();

}
```
I connect to DB with “connect remote:localhost/Sharding admin admin”
When I run “select * from User” in “console.sh” the output of my “dserver.sh” is:
“dserver.sh” output: ( “usa” ):
[dserver.sh(usa)](https://gist.github.com/hossein-md/d6edb5bd43ae707547efa5b384f4768b)

“dserver.sh” output: ( “chi” ):
[dserver.sh(chi)](https://gist.github.com/hossein-md/7ad875a268f42adfd1470ac875853aac)

“dserver.sh” output (“eur”):
[dserver.sh(eur)](https://gist.github.com/hossein-md/e6f4802f95e2121e34b1354542e3e440)


“Console.sh” output:
```
Error: com.orientechnologies.orient.server.distributed.ODistributedException: No active nodes found to execute command: sql.select * from User
```

The console output appeared after all the server thrown an error (about 5 minutes)

And I use this code to connect to graph with java-api
```
void printTest()
{
   System.out.println("usa output:");
   OrientGraph graph_usa=new OrientGraph("remote:usa-ip/Sharding");
   for (Vertex vertex : graph_usa.getVerticesOfClass("User")) {
       System.out.println(vertex.toString());
   }
   System.out.println("eur output:");
   OrientGraph graph_eur=new OrientGraph("remote:eur-ip/Sharding");
   for (Vertex vertex : graph_eur.getVerticesOfClass("User")) {
       System.out.println(vertex.toString());
   }
   System.out.println("chi output:");
   OrientGraph graph_chi=new OrientGraph("remote:chi-ip/Sharding");
   for (Vertex vertex : graph_chi.getVerticesOfClass("User")) {
       System.out.println(vertex.toString());
   }
}
```

The output is:
```
usa output:
v(User)[#26:0]
v(User)[#27:0]
eur output:
v(User)[#27:0]
chi output:
v(User)[#28:0]
```
When I changed the readquorum from 1 to 2 ("readQuorum": 2) with the same scenario I have these outputs:

In my console.sh with “select * from User”

orientdb {db=Sharding}> select * from User

```
Error: com.orientechnologies.orient.server.distributed.ODistributedException: No active nodes found to execute command: sql.select * from User
```

In my dserver.sh nothing happened! (In this time no error occured)
And the output of my java code is:
[output](https://gist.github.com/hossein-md/3ea9427ab8ea75664464f79585a8c3cd)
Thanks

**Comment by saeedtabrizi** [comment]
Hi @hossein-md 

I guess you have trouble with  hazelcast configuration file . because your'e log message shows that did not appear any **active node** for dispatching the messages between nodes . 
did you bind other distribution nodes like the following  lines in the hazlelcast.xml file ?

```
<network>
		<port auto-increment="true">2436</port>
		<join>
			<multicast enabled="false">
				<multicast-group>235.1.1.1</multicast-group>
				<multicast-port>2434</multicast-port>

			</multicast>
			 <tcp-ip enabled="true">
				<member>localhost:2435</member>
				<member>localhost:2436</member>
				<member>localhost:2437</member>
				<member>localhost:2438</member>
			 </tcp-ip>
                </join>
	</network>
```
Please check it .

**Comment by saeedtabrizi** [comment]
@hossein-md OK , i will reproduce it asap.

**Comment by georgiana-b** [comment]
Hello @luigidellaquila! 

I'm afraid I still experience this problem with my snapshot of OrientDB `3.0.1`. 

I'm  trying to set up 2 nodes (`ro` and `boss`) each containing 2 clusters for the same class (`Bid`). We will have a big database and I'm trying to split the data so that we never have to run a query on the entire database at once. This is why I'm trying to have each node containing exclusively the data for a certain country and only run queries on a few nodes of the database at any time. 

None of the nodes should have all the clusters. So, in my test I ended up with a setup very similar to one in the issue:

```json

{
    "@type": "d",
    "@version": 0,
    "readYourWrites": true,
    "newNodeStrategy": "static",
    "servers": {
        "@type": "d",
        "@version": 0,
        "boss": "MASTER",
        "*": "master",
        "ro": "MASTER"
    },
    "autoDeploy": true,
    "readQuorum": 1,
    "executionMode": "undefined",
    "version": 15,
    "writeQuorum": "majority",
    "clusters": {
        "@type": "d",
        "@version": 0,
        "internal": {
            "@type": "d",
            "@version": 0
        },
        "boss_bid": {
            "@type": "d",
            "@version": 0,
            "owner": "boss",
            "servers": [
                "boss"
            ]
        },
        "boss_bid_2": {
            "@type": "d",
            "@version": 0,
            "owner": "boss",
            "servers": [
                "boss"
            ]
        },
        "ro_bid": {
            "@type": "d",
            "@version": 0,
            "owner": "ro",
            "servers": [
                "ro"
            ]
        },
        "ro_bid_2": {
            "@type": "d",
            "@version": 0,
            "owner": "ro",
            "servers": [
                "ro"
            ]
        },
        "*": {
            "@type": "d",
            "@version": 0,
            "servers": [
                "boss",
                "ro",
                "<NEW_NODE>"
            ]
        }
    }
}
```

I eliminated the automatically created clusters for brevity but you can find the full version [in this gist](https://gist.github.com/georgiana-b/1e2111eaed7b82d4da82f59a61f0746f).

CLUSTER CONFIGURATION [wQuorum: false] (LEGEND: X = Owner, o = Copy)
This configuration appears to work -> I get this in the logs:

```
CLUSTER CONFIGURATION [wQuorum: false] (LEGEND: X = Owner, o = Copy)
+----------+-----------+----------+------+-------------+
|          |           |          |MASTER|   MASTER    |
|          |           |          |ONLINE|NOT_AVAILABLE|
|          |           |          |static|   static    |
+----------+-----------+----------+------+-------------+
|CLUSTER   |writeQuorum|readQuorum|  ro  |    boss     |
+----------+-----------+----------+------+-------------+
|*         |     2     |    1     |  o   |      X      |
|_studio_1 |     2     |    1     |  X   |      o      |
|_studio_5 |     2     |    1     |  X   |      o      |
|_studio_6 |     2     |    1     |  X   |      o      |
|_studio_7 |     2     |    1     |  X   |      o      |
|boss_bid  |     2     |    1     |      |      X      |
|boss_bid_2|     2     |    1     |      |      X      |
|e_4       |     2     |    1     |  X   |      o      |
|e_5       |     2     |    1     |  X   |      o      |
|e_6       |     2     |    1     |  X   |      o      |
|e_7       |     2     |    1     |  X   |      o      |
|internal  |     2     |    1     |      |             |
|ro_bid    |     2     |    1     |  X   |             |
|ro_bid_2  |     2     |    1     |  X   |             |
|v_3       |     2     |    1     |  X   |      o      |
|v_5       |     2     |    1     |  X   |      o      |
|v_6       |     2     |    1     |  X   |      o      |
|v_7       |     2     |    1     |  X   |      o      |
+----------+-----------+----------+------+-------------+
```

Also when I insert records into one of the nodes they balance nicely among the 2 local clusters. I created 7 records, 5 in the `ro` node, 2 in the `boss` node. When I use `LIST CLUSTERS` I see them all:

```
CLUSTERS (collections)
+----+---------------+----+---------------+-----+
|#   |NAME           |  ID|CLASS          |COUNT|
+----+---------------+----+---------------+-----+
|15  |boss_bid       |  41|Bid            |    0|
|16  |boss_bids_2    |  66|Bid            |    2|
|56  |ro_bid         |  67|Bid            |    3|
|57  |ro_bid_2       |  68|Bid            |    2|
```

Both nodes are online and they recognize each other:

```
+-------+------+--------------------------------+-----+---------+---------------+---------------+------------------------+
|Name   |Status|Databases                       |Conns|StartedOn|Binary         |HTTP           |UsedMemory              |
+-------+------+--------------------------------+-----+---------+---------------+---------------+------------------------+
|boss(*)|ONLINE|elvis-production=ONLINE (MASTER)|3    |10:59:23 |172.19.0.2:2424|172.19.0.2:2480|457.58MB/3.83GB (11.66%)|
|ro(@)  |ONLINE|elvis-production=ONLINE (MASTER)|2    |10:59:14 |172.19.0.4:2424|172.19.0.4:2480|286.38MB/1.92GB (14.59%)|
+-------+------+--------------------------------+-----+---------+---------------+---------------+------------------------+

```

In OrientDB Studio they all appear in the count:

![all_bids_in_the_count](https://user-images.githubusercontent.com/8862002/42329024-79ee31c4-8078-11e8-98fa-b1d67d0ae2ad.png)


However, when I try to retrieve them by running a simple

```sql
SELECT * FROM Bid
```

I get the error: `java.lang.IllegalStateException: Cannot calculate projections without a previous source`

I get this error if I run this query in OrientDB Studio and in OrientDB console but the database server itself doesn't log anything.

**Comment by zufanka** [comment]
@luigidellaquila +1 ^

**Comment by luigidellaquila** [comment]
Hi all,

Sorry for the late answer, I'll try to check it ASAP and let you know

Thanks

Luigi

**Comment by luigidellaquila** [comment]
In the meantime, could you please post an EXPLAIN of the query on v 3.0.x?

Thanks

Luigi

**Comment by zufanka** [comment]
Hi @luigidellaquila ! Don't mean to be a pain, but our project is under quite some time pressure and would very much appreciate if you could find some time to assist @georgiana-b with the problems she is having.

**Comment by lunima618** [comment]
the version I'm using is 3.0.6. I have the same problem with you,Have you solved this problem?

**Comment by georgiana-b** [comment]
@lunima618  I didn't but apparently there have been some commits that attempted to solve this problem and I didn't try again since. Did the version you tried include orientechnologies/orientdb@843411f?

**Comment by lunima618** [comment]
@georgiana-b  hi,I read the documentation and said it supports shard mapreduce, but I found a problem with the query. I don't know if it's my configuration file problem or it's not currently supported. I looked at GitHub for a similar problem, but I didn't get a good solution.
