### ISSUE TITLE
AND gets no precedence over OR

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8240]
## Expected behavior  
A query-criterium in which I write the following expression
```
a AND b OR c AND d
```
should be evaluated as
```
(a AND b) OR (c AND d)
```
but it doesn't. It returns no error, but the results are wrong.

## Actual behavior  
I must add explicit parentheses around the AND parts:
```
(a AND b) OR (c AND d)
```
is required in my WHERE clause in order to get the correct results.

Isn't it common practice to give AND operators precedence over OR operators ?

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

Did you have a chance to try latest 2.2.34? Probably the problem is fixed already.
I tried the following simple script and the results are correct:

```
create class Node

insert into Node SET a = 1, b=2, c=3, d=4

select from Node WHERE a=1 AND b=2 OR c=3 AND d=4
select from Node WHERE a=8 AND b=2 OR c=3 AND d=4
select from Node WHERE a=1 AND b=8 OR c=3 AND d=4
select from Node WHERE a=8 AND b=8 OR c=3 AND d=4
select from Node WHERE a=1 AND b=2 OR c=8 AND d=4
select from Node WHERE a=8 AND b=2 OR c=8 AND d=4
select from Node WHERE a=1 AND b=8 OR c=8 AND d=4
select from Node WHERE a=8 AND b=8 OR c=8 AND d=4
select from Node WHERE a=1 AND b=2 OR c=3 AND d=8
select from Node WHERE a=8 AND b=2 OR c=3 AND d=8
select from Node WHERE a=1 AND b=8 OR c=3 AND d=8
select from Node WHERE a=8 AND b=8 OR c=3 AND d=8
select from Node WHERE a=1 AND b=2 OR c=8 AND d=8
select from Node WHERE a=8 AND b=2 OR c=8 AND d=8
select from Node WHERE a=1 AND b=8 OR c=8 AND d=8
select from Node WHERE a=8 AND b=8 OR c=8 AND d=8
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I could never manage to reproduce this issue, is it still relevant?

Thanks

Luigi

**Comment by rdelangh** [comment]
ok, we will upgrade to latest release, if this seem to have fixed the issue meanwhile.
thx Luigi !

**Comment by diegomtassis** [comment]
We are experiencing the same problem (using 2.2.36).

It does not happen always, it depends on the number of clauses in the query and even on the result of evaluating each sub condition.

I'm trying to reproduce in an IT some failing scenarios. I'll provide it here the moment I have it.

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

Thank you very much, having a reproduce will be a huge help.

As a general note, this kind of problem no longer exist in v 3.0, so my advice is to upgrade as soon as you have a chance

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

Thank you very much, I'll check it asap

Luigi

**Comment by rdelangh** [comment]
as for us, regarding the upgrade to v3.0 : we are blocked by issues about using multi-field Lucene indexes, cfr #8323

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

I managed to reproduce the issue, I'll try to fix it asap

Thanks

Luigi

**Comment by diegomtassis** [comment]
Thanks.
