### ISSUE TITLE
Error Parsing Match Query

### ISSUE THREAD

**Issue by miotechtaoliu** [orientechnologies/orientdb#8241]
### OS: ubuntu

I issued the same query but get a different result. One would generate a parsing error, other would succeed.

Query1: 

> MATCH {class: Node, as: node_1, where: (id in ['1'])}.bothE(){as: edge_1, where: (type in ['TYPE1'])}.bothV(){class: Node, as: node_2},
> {class: Node, as: node_3, where: (id in ['2'])}.bothE(){as: edge_2}.bothV(){class: Node, as: node_2} 
> RETURN node_1,node_2,edge_1,node_3,edge_2 LIMIT 100

Query2:

> MATCH {class: Node, as: node_1, where: (id in ['1'])}.bothE(){as: edge_1, where: (type in ['TYPE2'])}.bothV(){class: Node, as: node_2},
>{class: Node, as: node_2}.bothE(){as: edge_2}.bothV(){class: Node, as: node_3, where: (id in ['2'])} 
> RETURN node_1,node_2,edge_1,node_3,edge_2 LIMIT 100

## Expected behavior
Query1 and Query2 should return the same result. 

## Actual behavior  
Query 2 will succeed. But query1 will have a wired parsing error, **select from null**

## Steps to reproduce  
Any match query with two sentences. When the end node name not the same as the node name of the next query.

**Comment by luigidellaquila** [comment]
Hi @mioyingluffy 

Could you please provide a sample dataset to reproduce the problem?
It's not a parsing problem (I tried with a basic, empty dataset and the parsing works fine), so there must be something in the data structure

Thanks

Luigi

**Comment by mioyingluffy** [comment]
Since we have millions of node and millions of edges, it takes some time to find the small dataset to reproduce the bug.
