### ISSUE TITLE
high CPU usage on Orient DB 2.2.34

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#8250]
### CPU:  E5-2603 12 core 1.7GHZ

Java options:

-Dstorage.diskCache.bufferSize=20480
-Xmx6144m

Disk performance:

dd if=/dev/zero of=/tmp/output.img bs=8k count=256k
262144+0 records in
262144+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 5.30628 s, 405 MB/s

dd if=/dev/zero of=/tmp/output.img bs=8k count=256k
262144+0 records in
262144+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 5.17187 s, 415 MB/s

dd if=/dev/zero of=/tmp/output.img bs=8k count=256k
262144+0 records in
262144+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 7.86699 s, 273 MB/s

dd if=/dev/zero of=/tmp/output.img bs=8k count=256k
262144+0 records in
262144+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 8.84125 s, 243 MB/s

dd if=/dev/zero of=/tmp/output.img bs=8k count=256k
262144+0 records in
262144+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 8.62628 s, 249 MB/s

dd if=/dev/zero of=/tmp/output.img bs=8k count=256k
262144+0 records in
262144+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 8.68357 s, 247 MB/s

dd if=/dev/zero of=/tmp/output.img bs=8k count=256k
262144+0 records in
262144+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 5.24623 s, 409 MB/s

CPU stats

 lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    1
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz
Stepping:              1
CPU MHz:               1700.000
CPU max MHz:           1700.0000
CPU min MHz:           1200.0000
BogoMIPS:              3399.79
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0,2,4,6,8,10
NUMA node1 CPU(s):     1,3,5,7,9,11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts

## Expected behavior  

 On this particular machine ( running in a production environment), after performing a data sync with MS Exchange,  the size of an Orient DB database is **500MB**. At this level, we  still expect low CPU overhead. Is our expectation unrealistic?

## Actual behavior  

 When our software runs with the **500MB** database, 12 CPU cores are fully utilized at 95-100%. The application becomes unresponsive.

Further CPU profiling shows that Orient DB is the likely source of the issue. See attached shots.  Orient DB appears to be consuming a large amount of CPU resources. This is confirmed - after we shutdown our application, delete the Orient DB database, start the server. The server now starts uses an empty Orient DB database. CPU utilization drops to below 2%. 

We would like to know - what is the likely cause of this? how can we mitigate this problem?

![orient](https://user-images.githubusercontent.com/6212848/39529161-539c28de-4e26-11e8-8191-7e73bd9ca725.png)

![performanceshot](https://user-images.githubusercontent.com/6212848/39529189-5fcc73b6-4e26-11e8-96e8-57c482b7e790.png)

For more debugging information, refer to a 5 minute [Java Flight Record]( https://www.dropbox.com/s/m2ps9uzzuhaz7xj/recording.zip?dl=0) capture. This file can be opened using Java Mission Control (JMC.exe) in JDK 8 bin directory. If needed, the  [Orient DB database](https://www.dropbox.com/s/185eq2j0ey3z9r0/database.tar.gz?dl=0) in question is also available for download and perusal.

Thank you kindly for your consideration.

**Comment by jamieb22** [comment]
I should add: there are no unusual Orient related stack traces in the logs. The system seems to be doing work, albeit at a slow pace due to over utilized CPU resource.

**Comment by jamieb22** [comment]
Correction: 500MB database.

**Comment by luigidellaquila** [comment]
Hi @jamieb22 

From the thread dumps I see you have tens (perhaps hundreds) of worker threads executing queries on OrientDB, I'd say it's normal that they consume CPU resources...

Thanks

Luigi

**Comment by jamieb22** [comment]
We have around 96 threads. They are performing very simple operations. Performing simple lookups. I find it hard to believe its normal, especially since  Orient DB is only a small part of our app, yet it consumes the bulk of resources.

**Comment by valenpo** [comment]
Hi @luigidellaquila 

I downloaded jfr file, and clearly see some problems with locking. Could it be due to cache or IO? Because ODB used in our software with no computation. Just read values from already computed things. Also all our items on database are indexed, so we retrieve it by indexed values. And this easy operation take ~20% of all software computation. 

But in same time, we index all files, encrypt it, put with specific hierarchy to store. Where is have weight computation occurs. 

What will be you suggestion, because what I see from jfr ODB is bottle neck.

``
Stack Trace	Sample Count	Percentage(%)
com.orientechnologies.common.concur.lock.ODistributedCounter.updateCounter(long)	14,450	18.811
   com.orientechnologies.common.concur.lock.ODistributedCounter.increment()	9,844	12.815
   com.orientechnologies.common.concur.lock.ODistributedCounter.decrement()	4,603	5.992
`` 

Thanks

**Comment by laa** [comment]
@valenpo I will take a look at it next week.

**Comment by valenpo** [comment]
@laa thanks for response. 
We downloaded client DB on our side, and found that the index was not exist, so I think this is a cause of hight CPU.

And I think this case should be closed.

**Comment by laa** [comment]
@valenpo thank you for keeping us up to date.
