### ISSUE TITLE
Error using batch commands with Studio

### ISSUE THREAD

**Issue by DiarmaidEverycs** [orientechnologies/orientdb#8253]
### OrientDB Version: 
 2.2.30/2.2.34

### Java Version:
 openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)  
### OS: 
Ubuntu 16.04 LTS 

## Expected behavior  
When I run the following command:
`begin
let a = insert into class content {"blah": "blah1"}
let b = insert into class content {"blah": "blah2"}
let c = insert into class content {"blah": "blah3"}
commit retry 100
return [$a,$b,$c]`

I expect the output to look like this: https://lh3.googleusercontent.com/-tds3EmWKtps/WulXXobF0hI/AAAAAAAAAEU/EAA2zXCHh6c8PBkM_hUXlYge3koAcDLKQCLcBGAs/s1600/Cattura.PNG
Which is to say, I expect three objects back, with each having the property blah (and the actual values being blah1, blah2 and blah3.

## Actual behavior  
It throws an error:
`com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.begin let a = insert into class content {"blah": "blah1"} let b = insert into class content {"blah": "blah2"} let c = insert into class content {"blah": "blah3"} commit retry 100 return [$a,$b,$c] DB name="df"`

## Steps to reproduce  
Open up orientdb studio in Ubuntu and run the above code.

**Comment by maggiolo00** [comment]
Hi @DiarmaidEverycs 

did you activate the batch mode from the menu on the right with the wrench icon?

**Comment by luigidellaquila** [comment]
Hi @DiarmaidEverycs 

Did you try to add semicolons at the end of each statement? 

Thanks

Luigi

**Comment by DiarmaidEverycs** [comment]
Yes.

`begin;
        let a = insert into u_df_product content {"blah": "blah1" };
        let b = intest into u_df_product content {"blah": "blah2" };
        let c = insert into u_df_product content {"blah" : "blah3"};
        commit retry 100;
        return [$a, $b, $c];"`

Same error.

**Comment by DiarmaidEverycs** [comment]
Ugh, I had a misspelling `let b = intest into u_df_product` - this was a bad error message.
