### ISSUE TITLE
Create simplified version of SBTree

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#8260]
The current version of SBTree was oriented on the keeping of values of any size, but in reality, values are never exceeded a couple of kilobytes. So a lot of code contains unnecessary checks, repetitive of serializations of keys and values and creation of intermediate objects. All of this can be simplified without breaking of binary compatibility of the index.

**Comment by laa** [comment]
@tglman I suppose for such big entry size we need to create a separate tree for big entries.  What is the point to lose in performance if in many cases we do not need such support. 
Also, current tree version does not support big keys it only supports big values which are in our case always small because it is either rid or embedded rid bag.

**Comment by laa** [comment]
Sorry, I was not completely clear in issue description, will fix it in a moment.

**Comment by tglman** [comment]
Hi, 

I think more to put there a pointer to an "external" payload in case the key go over certain size, we do this already for the values (OSBTreeValuePage), so the key will be serialized in two possible way: "embedded+key" and "external+pointer" and an eventual OSBTreeKeyPage, this will allow to slowly support any size, and be optimized for small sizes.

Regards

**Comment by laa** [comment]
Hi,
I thought about the same in the past, but for the whole history of ODB, there were no requests to implement support for big entries. Also, such approach feels like the addition of reference of indirection, but it means that instead of in-page search we need to use in-tree search with a subsequent check of each key whether it is key or reference. IMHO that is quite of slowdown. But from another side, because we will decrease the size of pages that is good timing to introduce such support but it should be optional by providing metadata during index creation as we do to switch on/off support of null keys.
