### ISSUE TITLE
Improve speed of insertion of edges in TreeRidBag

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#8261]
Currently, TreeRidBag is implemented as a general component which can handle any type of entries.
As result:
1. When we insert new entree in a rid bag we first perform get operation, and then only insert.
2.  We use general serializers which decrease the speed of serialization/deserialization of items.

Once this change is completed IMHO we can get about 1.5 times speed upon insertion of edges for big ridbags for the in-memory case.

**Comment by tglman** [comment]
Hi @laa,

For ridbags tree i've few topics open:

- Support of ridbag tree in distributed, we may need to introduce an indirection or another similar solution
- Support of smaller rid serialization in ridbag trees 
- Support of smaller headers pointer in ridbag trees ( from 4 bytes to 2 bytes)
- Add vertex rid together with edge rid to speedup traversal
- Maybe even evaluate different implementations for keep relationships

Regards

**Comment by laa** [comment]
I suppose I agree with all but smaller rid serialization. We need to look deeper on this question. But I will reach you personally when this change will be started to be implemented.

**Comment by laa** [comment]
Sorry, I was not completely clear in issue description, will fix it in a moment.
