### ISSUE TITLE
OSQL Parser - Impossible to parse String exact match query with '(' character

### ISSUE THREAD

**Issue by CyprienGottstein** [orientechnologies/orientdb#8262]
## Expected behavior  
I am trying to perform a simple exact match String request using the character '(', it should return an empty result. 

## Actual behavior  
The client fails to parse the query and return a very strange error message.

**Query**
`DELETE VERTEX FROM myclass WHERE a_gentle_property = '('`
**Result**
`Class 'YCLASS' was not found DB name="osql_string_exact_match"`  

It becomes kind of amazing how you can manipulate the parser by adding the appropriate buffer characters after the '('
**Query**
`DELETE VERTEX FROM myclass WHERE a_gentle_property = '(of'`
**Result**
`Class 'LASS' was not found DB name="osql_string_exact_match"` 

And with a buffer large enough after the '(' you can make the request work (at least with no errors, even if this is not what you requested at first). The next query works fine.

**Query**
`DELETE VERTEX FROM myclass WHERE a_gentle_property = '(offset'`
**Result**
`Success !`
**Query**
`DELETE VERTEX FROM myclass WHERE a_gentle_property = '(offset '`
**Result**
`Success !`

But don't go too far away either, it will crash again
**Query**
`DELETE VERTEX FROM myclass WHERE a_gentle_property = '(offset offset'`
**Result**
`Class 'A_GENTLE_PROPERTY' was not found DB name="osql_string_exact_match"` 

Unfortunately i don't have stacktraces to give you, but i guess you have an hint to pinpoint the problem. 

## Steps to reproduce  
I've joined a very simple database export which shows the issue. You just have to execute the OSQL query above to make the problem appear.

This is composed by a single class, with a single property with an index onto the property. I don't know if the index changes anything, i hope it doesn't otherwise it would be very, very strange, i just wanted to be in the same condition than my own database.

[osql_string_exact_match.gz](https://github.com/orientechnologies/orientdb/files/2001683/osql_string_exact_match.gz)

Best regards,

Thanks in advance,

Cyprien Gottstein.

**Comment by luigidellaquila** [comment]
Hi @CyprienGottstein 

Thank you very much for the detailed explanation.

My quick advice is to consider a migration to v 3.0.0. This kind of problems was completely solved with the new SQL executor.

Anyway, I'll check it on v 2.2 asap, probably it's a problem in the old parser

Thanks

Luigi

**Comment by CyprienGottstein** [comment]
Hi @luigidellaquila 

Thank you for taking this in charge.

I feel like its still a bit early for us to go into a migration to v 3.0.0, but will be taken into consideration.

Looking forward for your news.

Cyprien.

**Comment by luigidellaquila** [comment]
Hi @CyprienGottstein 

I just pushed a patch for this specific case, the snapshot will be available in a few minutes.
It fixes that query, but it does not solve the parsing problem in absolute. Doig so is much more expensive and was already addressed with the new SQL layer in v 3.0, so I don't know if I can provide a complete fix in reasonable time

Thanks

Luigi

**Comment by CyprienGottstein** [comment]
@luigidellaquila 

Sorry, i'm not used to this. When you speak about a patch are you referring to this commit ? https://github.com/orientechnologies/orientdb/commit/35ea4680d73a8ced9880fd0771d0d143a12c0f57

Do i have to clone and compile the code myself ? or is there a place where i can retrieve a snapshot ?

Also, about the version 3.0.0, while i'm at it, will we be able to use the LUCENE operator inside a match statement ? To be honest its not the first time i encounter problems with the OSQL parser and we've had a lot of troubles with that. We managed to find workaround bu its really important to us to be able to use LUCENE into a match statement, otherwise we won't be able to scale.

Sorry for this offtopic question, i opened an issue 1 month ago but i had no answer.

Cyprien.

**Comment by luigidellaquila** [comment]
Hi @CyprienGottstein 

Sorry, I was a bit too quick in the answer ;-)
This is the commit that fixes the problem (my push failed and I didn't notice it, I actually pushed it a couple of hours ago)

https://github.com/orientechnologies/orientdb/commit/2f8eff74b6c01104b2e0f3e43ecf13aeae6d7fa0

and here you can find the snapshot

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.36-SNAPSHOT/

Thanks

Luigi
