### ISSUE TITLE
CREATE EDGE inserts a corrupted record

### ISSUE THREAD

**Issue by aligin** [orientechnologies/orientdb#8265]
## Brief
Some time ago we discovered a problem with dissapiared edges, after the investingation we found that when the query CREATE EGDE is executed the edge was created, but SELECT or TRAVERS queries did not show right results. REPAIR DATABASE --fix-graph delete those types of records. but it is not a problem solver.

## Expected behavior  
CREATE EDGE inserts a record, that is not broken.

## Actual behavior  
CREATE EDGE inserts a record, that is broken. In the OrientDB Studio this looks like:
![orientdb studio](https://user-images.githubusercontent.com/6080294/40103149-22d12680-58f5-11e8-9789-f41edf507432.png)

## Steps to reproduce  
Here is our dump: 
[Fixed_rsm_db.json.gz](https://github.com/orientechnologies/orientdb/files/2008033/Fixed_rsm_db.json.gz)

1. Download default version of OrientDB Community server.
2. Import database from the dump.
3. Make `CREATE EDGE BusinessServiceDependsOnApplicationService FROM 
(select from BusinessServiceGroup where id=15161)
TO
(select from ApplicationServiceGroup where id=15218)` request.
4. Make `select * from BusinessServiceGroup where Id = 15161` request and see the corruted record in `OUT BusinessServiceDependsOnApplicationService`.
5. Connect to database in the console. Make `REPAIR DATABASE --fix-graph` and see 

> + deleting corrupted edge BusinessServiceDependsOnApplicationService ....

**Comment by laa** [comment]
@aligin before version of 2.2.29 we had such problem https://github.com/orientechnologies/orientdb/issues/7786 . Are you sure that this issue is reproducible in the latest version (2.2.35) of ODB?

**Comment by aligin** [comment]
Yep, this image is from 2.2.35. I've rechect it right before the post.
