### ISSUE TITLE
Object API does not propagate save over Set fields

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#8272]
## Expected behavior  
A model where an entity is related to another entity by a one-to-many relationship implemented using a Set.
Scenario:
1. fooEntity is created.
2. barEntity is created.
3. barEntity is added to fooEntity.
4. fooEntity is saved.
5. An entity retrievedFoo is retrieved from the database using fooEntity.id
6. A property is set in retrievedBar (acessed via retrievedFoo). Both entity handlers are now dirty.
7. retrievedFoo is saved.

## Actual behavior  
If the first save and the latter retrieve/save are executed using different connections (typical scenario in a multi thread application) the save operation is not propagated, and retrievedBar **stays marked as dirty**.

## Steps to reproduce  
I've created an integration test reproducing it.
[PropagateSaveOnSetFieldIT](https://github.com/CompartAG/orientdb-tryouts/blob/bugs/object-api-does-not-propagate-save-on-sets/2.2.x/src/test/java/com/compart/tec/orientdb/object/PropagateSaveOnSetFieldIT.java)

3 scenarios:

- Master entity saved using a connection and later changes saved using the same connection. **It works**.
- Master entity saved using a connection and later changes saved using a different connection. **It fails**.
- same scenario than the former but the relationship is stored using a List instead of a Set. **It works**.

Something I have noticed while debugging is that when a single connection is used, when retrieved, the aggregate root's internal dirtyManager is not null (actually the root and the child share the same dirtyManager). In the scenario using different connections, when retrieved, **the dirtyManager in the root entity is null**.

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

I pushed a fix for this issue, it will be released with v 3.0.2

Thanks

Luigi

**Comment by diegomtassis** [comment]
Is it possible to backport the fix as well to 2.2.x?

**Comment by luigidellaquila** [comment]
Yes, I think so, let me check

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

I just cherry-picked and pushed the fix to 2.2.x

Thanks

Luigi

**Comment by diegomtassis** [comment]
Thanks @luigidellaquila.
