### ISSUE TITLE
Can not execute a query in "gremlin" using Orientdb v-3.0.0

### ISSUE THREAD

**Issue by f-hashemi** [orientechnologies/orientdb#8275]
## Expected behavior  
<add here> 
I want to execute a query such as "g.v('#21:0')" using orientdb studio version 3.0.0. But when I execute this command, I get this exception: 

`java.lang.IllegalArgumentException: Cannot find a script executor requester for language: gremlin`

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>

**Comment by maggiolo00** [comment]
Hi @f-hashemi  the default distribution does not contain Apache Tinkerpop 3 stack.
You should download the distribution with TP3

https://s3.us-east-2.amazonaws.com/orientdb3/releases/3.0.1/orientdb-tp3-3.0.1.tar.gz

Let me know if it helps

Thanks

**Comment by f-hashemi** [comment]
It works correctly. 
Thanks.

**Comment by PeterTheDBA** [comment]
Will there be a tp3 release for later subversion of 3.0?

**Comment by PeterTheDBA** [comment]
Disregard, found it with a little bit of URL hacking https://s3.us-east-2.amazonaws.com/orientdb3/releases/3.0.18/orientdb-tp3-3.0.18.tar.gz
