### ISSUE TITLE
Backup does not creation on a schedule (2.2.30 - 2.2.35)

### ISSUE THREAD

**Issue by ScoobyMax** [orientechnologies/orientdb#8276]
## Expected behavior  
Constant backup creation on a schedule

## Actual behavior  
Really creates several times, then does not try any longer
for example, the server was launched on May 14. The last backup was on May 17, there were no more attempts, there were no errors in the log

## Steps to reproduce  
/config/automatic-backup.json  
```
{
  "enabled": true,
  "mode": "FULL_BACKUP",
  "exportOptions": "",
  "delay": "24h",
  "firstTime": "03:15:00",
  "targetDirectory": "/opt/backup/orient",
  "targetFileName": "${DBNAME}-${DATE:yyyyMMdd}.zip",
  "compressionLevel": 9,
  "bufferSize": 1048576
}
```

**Comment by mikayeln** [comment]
We are also experiencing mentioned problem with auto backups.

**Comment by ScoobyMax** [comment]
try to check by adding task in backups.json
when problem exist it not started
When no problems its ok

I think it is some problem with sheduler

**Comment by maggiolo00** [comment]
Hi @ScoobyMax 

can you share also your `orientdb-server-config.xml`?

Thanks

**Comment by ScoobyMax** [comment]
[archive.zip](https://github.com/orientechnologies/orientdb/files/2052337/archive.zip)

**Comment by ScoobyMax** [comment]
Hi @maggiolo00 
Did you succeed in reproducing the problem?

**Comment by maggiolo00** [comment]
Hi  @ScoobyMax 

i was not able to reproduce. I did configure the automatic backup with a shorter time frame, like every 
5 minutes without problem.

Are you able to reproduce this with a shorter delay?

Thanks

**Comment by ScoobyMax** [comment]
I'm not sure that we can afford so much disk space, but we'll try

**Comment by ScoobyMax** [comment]
i check it on this config

`{
  "enabled": true,
  "mode": "FULL_BACKUP",
  "exportOptions": "",
  "delay": "4h",
  "firstTime": "22:00:00",
  "targetDirectory": "/opt/backup/orient",
  "targetFileName": "${DBNAME}-${DATE:yyyyMMdd}.zip",
  "compressionLevel": 9,
  "bufferSize": 1048576
}
`
it make only 1 backup on 22:00 
2018-06-06 22:40:17:196 INFO  Automatic Backup finished: 14 ok, 0 errors

after disabling backup, we are no longer satisfied with the request "select getConnections()[0]", it is part of our monitoring.

**Comment by ScoobyMax** [comment]
Got repro on 2.3.35  http://prntscr.com/k07itj received only the first execution and disabling of the schedule further

orientDB do not execute the request "select getConnections()[0]" either http://prntscr.com/k07j6t

**Comment by ScoobyMax** [comment]
did you succeed in reproducing the problem?

**Comment by ScoobyMax** [comment]
We share database for reprodusing. Did you succeed in reproducing the problem?
