### ISSUE TITLE
LOAD SCRIPT  screws up the path in Windows

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8284]
## Expected behavior  
>LOAD SCRIPT C:\temp\xxxxxx\recres\recres-webapp\src\main\odb\scripts\schema.sql 

should work as expected

## Actual behavior  
I see this instead:
```
ecres-webapp\src\main\odb\scripts\schema.sql...
ecres-webapp\src\main\odb\scripts\schema.sql'runcs\
```

which tells me that the LOAD SCRIPT command is trying to interpret the path and ```\r```, ```\p``` makes it bomb. This is scary! The console app **should never try to parse the path**, but accept is a provided by the user.

## Steps to reproduce  
One possible workaround is to force UNIX style paths. Then it works .. but cammon? 
What does not work is if one tries to wrap the path in "" or ''.

**Comment by markodjurovic** [comment]
@hrstoyanov Thank you for reporting this issue. Fix will be in v3.0.2
