### ISSUE TITLE
Documentation of SQL containsText operator wrong / outdated

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#8287]
## Expected behavior  

Regarding the containsText operator, [the documentation says](https://orientdb.com/docs/2.2.x/SQL-Where.html#conditional-operators):

> Current limitation is that **it must be the unique condition of a query**. When used against an indexed field, a lookup in the index will be performed with the text specified as key. When there is no index a simple Java indexOf will be performed. So the result set could be different if you have an index or not on that field

## Actual behavior  

In my tests the result of executing the following 2 queries is exactly the same:

`SELECT COUNT(*) FROM GrandPrixEntrance WHERE car.team.name = 'McLaren F1' AND car.name LIKE '%mp4%'`

`SELECT COUNT(*) FROM GrandPrixEntrance WHERE car.team.name = 'McLaren F1' AND car.name CONTAINSTEXT 'mp4'`

But according to the documentation, the 2nd query should not work.
Is the documentation wrong/outdated?

Note: There is **no index** in the property _car.name_.

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

I just pushed a fix for this on the docs. The new manual will be generated in a few hours

Thanks

Luigi
