### ISSUE TITLE
Question: how to find the names of custom clusters

### ISSUE THREAD

**Issue by diaconescur** [orientechnologies/orientdb#8290]
### Java Version: 1.8.0<version here>  
We are trying to implement custom cluster naming and selection. 
We were able to create clusters with custom names (OClass addCluster(String iClusterName);)
But when we try to read them and identify them by name, I find no function in the OClass class that can help me. 
I can get the list of cluster ids (  int[] getClusterIds();) but there is nothing that helps me link the id with the name.
Why allow custom claster naming if there is no way to further read them ? Am I missing something?
Also, is there a way to remove a cluster from a OClass object other than running the "DROP CLUSTER" command?

**Comment by markodjurovic** [comment]
Hi @diaconescur 
did you try with String getClusterNameById(int iClusterId); from ODatabase?
               
      vertexClass.addCluster("TestClusterName" + System.currentTimeMillis());
      int[] clusterIds = vertexClass.getClusterIds();
      for (int clusterId : clusterIds){
        String clusterName = db.getClusterNameById(clusterId);
        System.out.println("ClusterName: " + clusterName);
      }

should output something like

      ClusterName: testrecord
      ClusterName: testrecord_1
      ClusterName: testrecord_2
      ClusterName: testrecord_3
      ClusterName: testclustername1528803204678

**Comment by diaconescur** [comment]
Thank you for the answer. This way it works.
