### ISSUE TITLE
Query with "any()" seems not to work in OrientDB 3.0.1

### ISSUE THREAD

**Issue by castrv** [orientechnologies/orientdb#8302]
## Expected behavior  
In OrientDB 2.2.35 this query worked fine:

select from V where any() like '%Word%'

## Actual behavior  
In OrientDB 3.0.1 I get an error

"com.orientechnologies.orient.core.exception.OCommandExecutionException: Funciton not found: any DB name="Example_DB""

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @castrv 

I just pushed a fix for this issue, it will be released with v 3.0.2

Thanks

Luigi

**Comment by 5325833510** [comment]
Ty
