### ISSUE TITLE
Moving vertex from class seems to delete its edges in OrientDB 3.0.1

### ISSUE THREAD

**Issue by castrv** [orientechnologies/orientdb#8303]
## Expected behavior  

In OrientDB 2.2.35 this query worked fine:

MOVE VERTEX (SELECT FROM Uncompleted_Personal_Task WHERE @rid = #105:1) TO CLASS:Completed_Task

It moved the vertex into the Completed_Task class and it kept all its edges.

## Actual behavior  

In OrientDB 3.0.1 the same query moves the vertex into the Completed_Task class but all its edges disappear.

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @castrv 

I'm checking it now, I'll let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @castrv 

I just pushed a fix, it will be released with v 3.0.2

Thanks

Luigi
