### ISSUE TITLE
toJSON() method seems broken in 3.0.1

### ISSUE THREAD

**Issue by kahlkevin** [orientechnologies/orientdb#8304]
## Expected behavior  
Running `SELECT @this.toJSON('prettyPrint') FROM Hotels WHERE Id = 1` against `demodb` should return a valid JSON document.

## Actual behavior  
`null` result is returned.

## Steps to reproduce  

1. Attach to `demodb` database using Studio or Console.
2. Execute SQL query detailed above.
3. Note empty results.
4. Consult the 'Raw' tab in Studio and note `null` value in `result` object.

**Comment by luigidellaquila** [comment]
Hi @kahlkevin 

Thank you for reporting, I'm checking it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @kahlkevin 

I just pushed a fix, it will be released with 3.0.2

The snapshot will be available on Sonatype servers in a few minutes

Thanks

Luigi
