### ISSUE TITLE
performance！performance！performance！ What's the opinion of everyone   OrientDB vs ArangoDB vs Neo4j

### ISSUE THREAD

**Issue by cmdares** [orientechnologies/orientdb#8307]
recently pk OrientDB vs ArangoDB vs Neo4j
https://www.arangodb.com/2018/02/nosql-performance-benchmark-2018-mongodb-postgresql-orientdb-neo4j-arangodb/

Whether there is a promotion in orientdb 3.0.x ?

**Comment by sh0umik** [comment]
Any thoughts ?
