### ISSUE TITLE
Accessing Vertex Record through index makes OSQL delete statement fail within the same transaction

### ISSUE THREAD

**Issue by CyprienGottstein** [orientechnologies/orientdb#8311]
## Expected behavior  
OSQL statement working properly  

## Actual behavior  
OSQL statement is not executed, the transaction crashes with an error:

> com.orientechnologies.orient.core.exception.OSerializationException: 
> Cannot read transaction record from the network. Transaction aborted
> 	DB name="index-strange-behavior"
> 	DB name="index-strange-behavior"
> 	at com.mycompany.testing.StrangeIndexBehavior.testBehavior(StrangeIndexBehavior.java:38)
> Caused by: java.lang.NullPointerException

The OSQL statement is not executed, the records which i asked for suppression are still there.

## Steps to reproduce  
I've joined a very simple DB to help reproduce the problem :
[index-strange-behavior.gz](https://github.com/orientechnologies/orientdb/files/2079460/index-strange-behavior.gz)

Also, here is a snippet which works to make the problem appear :

```
@Test
    public void testBehavior() throws BackendClosedException {

        final OrientGraphFactory factory = new OrientGraphFactory("remote:127.0.0.1/index-strange-behavior", "root", "root").setupPool(5, 1000);
        OrientBaseGraph graph = factory.getTx();
        
        // First retrieve instance of myclass using myproperty_index
        
        final OIndexManager idxManager = graph.getRawGraph().getMetadata().getIndexManager();
        OIndex<?> idx = idxManager.getIndex("myproperty_index");
        
        final OIdentifiable projectionIdentifier = (OIdentifiable) idx.get("value_1");
        final OrientVertex vertex = graph.getVertex(projectionIdentifier);
        
        graph.command(new OCommandSQL("DELETE VERTEX FROM MyClass WHERE true")).execute();

        graph.commit();
        graph.shutdown();

    }
```

Now, i've noticed that the problem is solved if i "reset" the transaction by closing the current OrientBaseGraph object and open a second one to perform the OSQL Statement. Here is a working example :

```
@Test
    public void testBehaviorWorking() throws BackendClosedException {

        final OrientGraphFactory factory = new OrientGraphFactory("remote:127.0.0.1/index-strange-behavior", "root", "root").setupPool(5, 1000);
        OrientBaseGraph graph = factory.getTx();
        
        // First retrieve instance of myclass using myproperty_index
        
        final OIndexManager idxManager = graph.getRawGraph().getMetadata().getIndexManager();
        OIndex<?> idx = idxManager.getIndex("myproperty_index");
        
        final OIdentifiable projectionIdentifier = (OIdentifiable) idx.get("value_1");
        final OrientVertex vertex = graph.getVertex(projectionIdentifier);
        
        graph.shutdown();
        graph = factory.getTx();
        
        graph.command(new OCommandSQL("DELETE VERTEX FROM MyClass WHERE true")).execute();

        graph.commit();
        graph.shutdown();

    }
```

I hope you have enough information with that to solve the problem. OrientDB is running with default configuration. I just added "root"/"root" for the credentials.

Thanks in advance,

Best regards.

**Comment by luigidellaquila** [comment]
Hi @CyprienGottstein 

Thank you for reporting, I'm checking it now, I'll let you know as soon as I have news

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @CyprienGottstein 

I just pushed a fix for this problem, it will be released with v 3.0.3

Thanks

Luigi

**Comment by CyprienGottstein** [comment]
Thank you very much,

When do you expect to release the version 3.0.3 ?

Cyprien

**Comment by luigidellaquila** [comment]
Hi @CyprienGottstein 

I'd say one or two weeks.
If you want to try a snapshot, it will be available in a few minutes here https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.3-SNAPSHOT/

Thanks

Luigi

**Comment by CyprienGottstein** [comment]
Hi @luigidellaquila 

I'll probably give it a shot, we are quite in a hurry on our side, i'll keep you updated

Cyprien.

**Comment by CyprienGottstein** [comment]
Hi @luigidellaquila 

The fix is working, this exception disappeared from our test sequences, thank you again :)
