### ISSUE TITLE
Change master node

### ISSUE THREAD

**Issue by jhegman** [orientechnologies/orientdb#8312]
### OrientDB Version: 3.0.2  
I have a question that I can't seem to find in the documentation.  I start a distributed server on one machine (machine 1).  I then start another distributed server on a second machine (machine 2) and connect to the cluster. This works fine. If I then stop the server on machine 1 and try to create a class in Studio on machine 2 I get this error: Error on creating cluster 'test' on distributed nodes: local and remote ids assigned are different".

Is this normal behavior?  I guess my question is if I stop machine 1, should machine 2 then become the master node? Or does machine 1 have to always be running for other machines to connect.

**Comment by hossein-md** [comment]
Hi @jhegman 
You can set "newNodeStrategy": "dynamic"
When you want to remove one of your servers, `"readQuorum": 1`, `"writeQuorum": "majority"` and  `"newNodeStrategy": "static"` are important.
