### ISSUE TITLE
Batch execution of multiple SQL statements failed in version 3.0.2

### ISSUE THREAD

**Issue by ZhenYongFan** [orientechnologies/orientdb#8320]
## Expected behavior  
Batch execution of multiple SQL statements failed

## Actual behavior  
Implementation was successful in version 3.0.1

## Steps to reproduce  
create class Lover extends E;
create class Student extends E;
create class Teacher extends E;
create class Disciple extends E;
create class Skill extends E;

error:
Error parsing query: create class Lover extends E; create class Student extends E; ^ create class Teacher extends E; create class Disciple extends E; create class Skill extends E; Encountered " <CREATE> "create "" at line 2, column 1. Was expecting: <EOF> DB name="temo" Error Code="1"

**Comment by luigidellaquila** [comment]
Hi @ZhenYongFan 

How are you executing it? 
If it's from Studio, did you select BATCH mode?
If it's from Java API, did you use `db.execute()`?

Thanks

Luigi

**Comment by ZhenYongFan** [comment]
Thanks Luigi
I ran sql in Graph Editor. However, I didn't notice the batch mode among the tools options in the "Browse" page before,After set "Batch" mode,I can run multiple rows of sql in the Browse page , but I can't find  "batch" mode in the "Graph" page, so it is still not possible in the Graph Editor.
Thanks again.

**Comment by luigidellaquila** [comment]
Hi @ZhenYongFan 

You are right, the graph editor for now only supports single SQL statements (it's just intended for data display, not for complex scripting), so for now you have to use the BROWSE panel to execute scripts

Thanks

Luigi

**Comment by ZhenYongFan** [comment]
Hi @luigidellaquila 
  But in version 3.0.1,I can execute multiple SQL in graph editor.I suggest to keep this feature same with  the previous version。
  Thanks
ZhenyongFan

**Comment by luigidellaquila** [comment]
Hi @ZhenYongFan 

Actually that was a bug... all the statements were executed as scripts.
This can lead to wrong behaviors and to security flaws, so we fixed it. 
In case we can consider providing an explicit option in the Graph editor for script execution, but frankly speaking I don't see the added value for this. The graph editor is intended for graph display, not for script execution

Thanks

Luigi

**Comment by ZhenYongFan** [comment]
Hi @luigidellaquila 
You are right. The graph editor is mainly used to display graph. If you have time, please make the error message more friendly. I'm ashamed that I compared the 3.0.1's code and didn't find the code to change it.

Thanks
ZhenyongFan

**Comment by luigidellaquila** [comment]
Hi @ZhenYongFan 

I'll definitely try to do it.
Thank you very much for your feedback!

Luigi
