### ISSUE TITLE
Question about MATCH queries

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8321]
### OS: centos07

I am trying to create a query to match a node and then follow edges from that node while they have some attribute.

## Steps to reproduce  (simplified)

```
create vertex v content {"name": "a", "group": 1}
create vertex v content {"name": "b", "group": 1}
create vertex v content {"name": "c", "group": 1}
create vertex v content {"name": "d", "group": 1}
create vertex v content {"name": "e", "group": 2}
create edge e from <A RID> to <B RID>
create edge e from <B RID> to <C RID>
create edge e from <C RID> to <D RID>
create edge e from <C RID> to <E RID>
```
This ends up looking something like this

![image](https://user-images.githubusercontent.com/4342641/41257228-eaadcb6e-6d80-11e8-9cec-a3f12e507fc8.png)

I am probably just not understanding match queries fully, but I want a query to match 'a' and then follow and return 'b', 'c', and 'd', but not 'e'.

I tried

```
match {class: v, where: (name = 'a')}.out(){while: ($currentMatch.group = 1)} return $pathElements
```

But this only returns 'a'. Could you please help me understand what I am doing wrong?

**Comment by luigidellaquila** [comment]
Hi @creisle 

There must be a little problem with $currentMatch in WHILE conditions, I'll check it asap.
In the meantime, you can just omit it and the query will work fine:

```
match {class: v, where: (name = 'a')}.out(){while: (group = 1)} return $pathElements
```

I just would like to make sure that you got the exact meaning of WHILE condition (it can be a bit misleading is some cases): it applies to the origin node, ie. to the left node in the pattern, so to `a` at the first iteration, to `b` at the second iteration and so on. The result is that you will also obtain `e` in this case. If you want to exclude it, you also have to specify `where: (group = 1)`:

```
match {class: v, where: (name = 'a')}.out(){while: (group = 1), where: (group = 1)} return $pathElements
```

I hope it helps

Thanks

Luigi

**Comment by creisle** [comment]
Great thanks! That worked
