### ISSUE TITLE
docs of v3 on multi-field index searches are incomplete or unclear

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8323]
### OS: Ubuntu

After upgrading from version 2.x, our queries on multi-field Lucene indexes need to be rewritten with functions SEARCH_CLASS, SEARCH_INDEX, etc.
Our original query is like this:
```
SELECT set(rid) AS x 
FROM INDEX:idx_cdr_icx_20180610_2 
WHERE key LUCENE 
' CALLING_NUMBER:*14758182* AND PRT_DATE:[20180603000000 TO 20180611235959] '
```
The indexes on this class "cdr_icx_20180610" are defined as:
```
Name 	                Type 	        Properties 	                        Engine
idx_cdr_icx_20180610_0 	UNIQUE 	        ["ENV","PRT_DATE","FILENAME","RECORD_NUMBER"] 	SBTREE 	
idx_cdr_icx_20180610_1 	FULLTEXT 	["FILENAME"] 	                        LUCENE 	
idx_cdr_icx_20180610_2 	FULLTEXT 	["CALLING_NUMBER","PRT_DATE"] 	        LUCENE 	
idx_cdr_icx_20180610_3 	FULLTEXT 	["CALLED_NUMBER","PRT_DATE"] 	        LUCENE 	
idx_cdr_icx_20180610_4 	FULLTEXT 	["MGC8INCTRKGRPNAME","PRT_DATE"] 	LUCENE 	
idx_cdr_icx_20180610_5 	FULLTEXT 	["MGC8OUTTRKGRPNAME","PRT_DATE"] 	LUCENE 
```
Referring to OrientDB docs at "https://orientdb.com/docs/last/indexing/Full-Text-Index.html#querying-lucene-fulltext-indexes", I tried the following queries, but all produced some kind of a meaningless error message:

```
SELECT FROM cdr_icx_20180610 
WHERE 
SEARCH_FIELDS(
["CALLING_NUMBER", "PRT_DATE"], 
' CALLING_NUMBER:*14758182* PRT_DATE:[20180603000000 TO 20180611235959] ' 
) = true
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
Error: java.lang.IllegalArgumentException: too many indices matching given field name: CALLING_NUMBER,PRT_DATE
```
See above for the list of index definitions: only one single index is defined with these fields. So what does this error mean ? Documentation about the possible error messages would come very handy !

A different attempt:
```
SELECT FROM cdr_icx_20180610 
WHERE 
SEARCH_INDEX(
"idx_cdr_icx_20180610_2", 
' CALLING_NUMBER:*14758182* PRT_DATE:[20180603000000 TO 20180611235959] ') = true
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
Error: com.orientechnologies.lucene.exception.OLuceneIndexException: Error on get searcher from Lucene index
Error: java.lang.NullPointerException
```
Any documentation about this error message would also be very handy!

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

The second error (the NullPointerException) is definitely a bug and needs a fix.

About the first one, can you please share the basic schema to reproduce it?

Thanks

Luigi

**Comment by rdelangh** [comment]
hi @luigidellaquila 
basic schema:
- the definition of that index "idx_cdr_icx_20180610_2" (class "cdr_icx_20180610") is already list above
- all fields of the class are STRING, except field "PRT_DATE" which is of type DATETIME
Please tell me if you need more info.

**Comment by luigidellaquila** [comment]
Thank you very much, I'll check it and let you know

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I tried to reproduce the NPE but with no success, perhaps there is something specific in the index definitions?

About the first problem, the problem here is that Lucene in general uses an OR strategy on filtering, so `SEARCH_FIELDS(["CALLING_NUMBER", "PRT_DATE"], "...")` will try to use indexes defined on CALLING_NUMBER or on PRT_DATE. In this case it finds four indexes and does not know how to choose. 
I'll check if there is a solution for this, @maggiolo00 probably can help on this

Thanks

Luigi

**Comment by rdelangh** [comment]
hi @luigidellaquila 
1) SEARCH_FIELDS should have then a syntax where you can add a logical operator (AND in my case)
2) SEARCH_INDEX : I don't think we do anything exotic in the index definitions, foreach of the Lucene indexes, the following parameters are specified to the 'CREATE INDEX' command:
```
metadata {"allowLeadingWildcard": true, "closeAfterInterval": 86400000 }
```

**Comment by maggiolo00** [comment]
Hi @rdelangh 

In your case i think `SEARCH_INDEX` is the best approach.
let me try to reproduce the NPE exception.

Can you reproduce it in a deterministic way?

Thanks

**Comment by rdelangh** [comment]
@maggiolo00 
What you mean with "in a deterministic way" ?

**Comment by maggiolo00** [comment]
hi @rdelangh 

i mean if you repeat 10 times that query do you get the same exception every time?

**Comment by rdelangh** [comment]
update: 
- installed version 3.1.0 (build 3f270977d0f87d8fe9a5171aa439dc3295696b37)
- I have now only 2 Lucene indexes, of which only one being a multi-fields index ("idx_cdr_icx_20180610_2"):
```
> desc cdr_icx_20180610
...
INDEXES (3 altogether)
+----+----------------------+-------------------------------------------------------------------------------+
|#   |NAME                  |PROPERTIES                                                                     |
+----+----------------------+-------------------------------------------------------------------------------+
|0   |idx_cdr_icx_20180610_1|[FILENAME]                                                                     |
|1   |idx_cdr_icx_20180610_0|[ENV,PRT_DATE,FILENAME,RECORD_NUMBER]                                          |
|2   |idx_cdr_icx_20180610_2|[ENV,PRT_DATE,CALLING_NUMBER,CALLED_NUMBER,MGC8INCTRKGRPNAME,MGC8OUTTRKGRPNAME]|
```

New attempts:

Trying with SEARCH_CLASS:
```
orientdb {db=cdrarch}>  SELECT FROM cdr_icx_20180610 WHERE SEARCH_CLASS(' +CALLING_NUMBER:*14758182* +PRT_DATE:[20180603000000 TO 20180611235959] ') = true
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
Error: java.lang.IllegalArgumentException: too many full-text indices on given class: cdr_icx_20180610
```
-> this corresponds with the documentation, saying that SEARCH_CLASS should only be used when there is only one single Lucene index

Trying with SEARCH_FIELDS:
```
orientdb {db=cdrarch}> SELECT FROM cdr_icx_20180610 WHERE SEARCH_FIELDS(["ENV", "PRT_DATE", "CALLING_NUMBER"], ' +ENV:prod +PRT_DATE:[20180603000000 TO 20180611235959] +CALLING_NUMBER:*14758182* ') = true
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
Error: com.orientechnologies.lucene.exception.OLuceneIndexException: Error on get searcher from Lucene index
Error: java.lang.NullPointerException
```

Trying with SEARCH_INDEX:
```
orientdb {db=cdrarch}> SELECT FROM cdr_icx_20180610 WHERE SEARCH_INDEX("idx_cdr_icx_20180610_2", ' +ENV:prod +PRT_DATE:[20180603000000 TO 20180611235959] +CALLING_NUMBER:*14758182* ') = true
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
Error: com.orientechnologies.lucene.exception.OLuceneIndexException: Error on get searcher from Lucene index
Error: java.lang.NullPointerException
```

No help found in the documentation.
-> can someone send me any suggestions please of what is missing here ?

**Comment by rdelangh** [comment]
hi gurus,
can someone please provide some update on this issue with v3 LUCENE multi-field queries?
thx

**Comment by rdelangh** [comment]
hello gurus,
last post dates from 2 months ago. Is there any update that can be shared here, please ?

**Comment by rdelangh** [comment]
Easily reproducable:
create a class with 5 fields, create a single Lucene index (FULLTEXT) on all these 5 fields, add some records, then run a query with SEARCH_CLASS or SEARCH_INDEX as my examples above.
Always returns
```
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
Error: com.orientechnologies.lucene.exception.OLuceneIndexException: Error on get searcher from Lucene index
Error: java.lang.NullPointerException
```
(same with version 3.0.11)

**Comment by rdelangh** [comment]
Does anyone succeed in searching through multi-field Lucene indexes with a ODB version 3.0.x ?

**Comment by redsand** [comment]
any progress on this?
