### ISSUE TITLE
Inconsistent count function behavior in SELECT

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#8328]
## Expected behavior  
<add here>  
`SELECT count(*) FROM Test WHERE foo = 'bar1'` should return one row in a result set with the `count` field containing `0` as the value if no document meet the WHERE clause.

## Actual behavior  
The result set contains no rows.  This makes it complicated to get the counts for things that may or may not be zero. In one case I have to inspect a field in the first row of the result set, in the other case I have to check for no rows.

## Steps to reproduce  
1. `INSERT INTO Test SET foo = 'bar'`
2. `SELECT count(*) from Test WHERE foo='bar'` (returns a result set `[{count: 1}]`)
3. `INSERT INTO Test SET foo = 'bar1'` (returns a result set `[]`)

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

I recently fixed this issue (https://github.com/orientechnologies/orientdb/issues/8280) the fix will be released soon

Thanks

Luigi
