### ISSUE TITLE
Bad diagnostics in console - console tool does not fully ignore comment lines?

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8331]
## Expected behavior  
Some good diagnostics of where the issue is.

## Actual behavior  
 When you run the the attached script, you only get:
```java
Error: java.lang.IllegalStateException: Unexpected end of file
```
there is no line number or anything that could help find the issue! 

I have found such issues to be due to the fact that comment lines (such as ```-- Comment ```) are supposed to be  ignored,  but they are not. The console still interprets the content of the comment and fails. With a large schema script, this can kill a few hours of trial-and-error to find the issue! 

Here is the attached schema that bombs:
[schema.zip](https://github.com/orientechnologies/orientdb/files/2104377/schema.zip)

## Steps to reproduce  
run thew attaches schema file in console

**Comment by hrstoyanov** [comment]
By "trial-and-error", I discovered that the above schema file bombs  on line 104 where the comment reads:
```
--Cardholder's full name
```
The problem is ``` ` ``` in the comment, which should have been ignored, but it is not!

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

I just pushed a fix that solves this problem. It will be released with v 3.0.3

Thanks

Luigi

**Comment by hrstoyanov** [comment]
Thanks @luigidellaquila ,
Will try to confirm later today (maven snapshot not ready yet, it seems as of now)

Any idea when 3.0.3 will be pushed out?

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

v 3.0.3 will be officially released in one or two weeks

Thanks

Luigi

**Comment by hrstoyanov** [comment]
Thanks @luigidellaquila 
It seems that the fix works
