### ISSUE TITLE
Studio CSV Doesn't Populate File

### ISSUE THREAD

**Issue by akizze01** [orientechnologies/orientdb#8335]
## Expected behavior  
To run a query in Studio with the CSV option. When query runs and you open the file, it should be populated with the results

## Actual behavior  
The query runs, file is generated, but the workbook is blank. A green indicator pops up in Studio stating that "the command has been executed"

## Steps to reproduce  
SELECT X FROM *VERTEXNAME*  with content type of CSV in Orientdb Studio

**Comment by TariqAHassan** [comment]
Hi @wolf4ood ,

I am also having this issue.

**Comment by wolf4ood** [comment]
Hi @akizze01  @TariqAHassan 

i've just pushed a fix. It will be available in the next OrientDB  release

Thanks

**Comment by akshattandon** [comment]
@wolf4ood In which version of OrientDB this fix is available or expected to be available?
