### ISSUE TITLE
OrientDB 3.0.2 - Is it possible to display text inside vertices in Graph Editor?

### ISSUE THREAD

**Issue by castrv** [orientechnologies/orientdb#8339]

**Comment by maggiolo00** [comment]
Hi @castrv 

which kind of text?  You can display vertices properties

**Comment by castrv** [comment]
Hi,

I mean text label, as exemplified in the picture attached. It seemed possible in previous versions.
![screenshot from 2018-06-23 19-47-40](https://user-images.githubusercontent.com/38989249/41812637-a5d45754-771e-11e8-98cb-a40074840389.png)
