### ISSUE TITLE
Distributed query doesn't work in distributed configuration

### ISSUE THREAD

**Issue by HassounDev** [orientechnologies/orientdb#8345]
### OS: <Linux, Debian>  

I have a distributed configuration with 3 servers :

```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": 1,
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "customer_dsc": {
      "servers" : [ "dsc"]
    },
    "customer_dsp1": {
      "servers" : [ "dsp1" ]
    },
    "customer_dsp2": {
      "servers" : [ "dsp2"]
    },
    "phc_dsc": {
      "servers" : [ "dsc"]
    },
    "phc_dsp1": {
      "servers" : [ "dsp1" ]
    },
    "phc_dsp2": {
      "servers" : [ "dsp2"]
    },
    "*": {
      "servers" : [ "<NEW_NODE>" ]
    }
  }
}
```
I already used this conf in orientdb 2.2.x and i wanted to test it in Orientdb 3,
I added a new vertex named : customer in the cluster customer_dsc

`create vertex customer cluster customer_dsc set identifier ='id_1', name='name_1'`

so when i use this query `select from customer` i want to see

## Expected behavior  
|4   |#16:4|customer|id_1       |name_1 |

## Actual behavior  
but it throw an error 
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
  Error: java.lang.ArrayIndexOutOfBoundsException

## Steps to reproduce  

This query already worked in Orientdb 2.2.X

**Comment by hossein-md** [comment]
Hi @HassounDev 

Which version of 2.2.x works for you? I've tested 2.2.26, 2.2.30, 2.2.33 and 2.2.35 but only 2.2.26 and 2.2.30 work for me. 2.2.33 and 2.2.35 return an error as I mentioned in #8297.
Even in these versions, traverse doesn't work fine as I expected.

Thanks

**Comment by HassounDev** [comment]
i used 2.2.20 it works for i tried 3.x and 3.3.x its don't work, i don't know why
