### ISSUE TITLE
Custom Batch Insert

### ISSUE THREAD

**Issue by adler4566** [orientechnologies/orientdb#8348]
### OS: Linux  

In the documentation for the custom batch insert it is missing that the transactions must be disabled. If the transactions are not disabled some edges will point to the wrong vertices. This happens because of the post-manipulation of the vertexid from OrientDB.
For example, first I initialize the `ORecordID` objects:

    ORecordId ridVertex1 = new ORecordId(9L, 0L); // #9:0, the RID of Vertex1, that still does not exist
    ORecordId ridVertex2 = new ORecordId(9L, 1L); // #9:1, the RID of Vertex2, that still does not exist
    ORecordId ridVertex3 = new ORecordId(9L, 2L); // #9:2, the RID of Vertex3, that still does not exist

   ORecordId ridEdge1 = new ORecordId(10L, 0L); // #10:0, the RID of Edge1, that still does not exist
   ORecordId ridEdge2 = new ORecordId(10L, 1L); // #10:1, the RID of Edge2, that still does not exist

Now, OrientDB uses custom Id's for the vertices, so it will happen that for example `ridVertex1` will get the ID "#9:2" and `ridVertex2` will get the ID "9:0". This fault will cause that the references will get mixed up. The solution for this was to disable the transactions.

**Comment by luigidellaquila** [comment]
Hi @adler4566 

Good point, I'll add a note to the docs

Thanks

Luigi
