### ISSUE TITLE
Simple Query in JAVA API slower than OrientDB Studio

### ISSUE THREAD

**Issue by edmondboulet** [orientechnologies/orientdb#8349]
## Expected behavior  
Remove edge or Node whit the ID should have an execution time of 0.02 sec like the performance in OrientdDB Studio.

## Actual behavior  
But with the Java API tinkerpop.blueprints it takes one second ( or more ).

## Steps to reproduce  
Tried to execute this code, with a graph DB already loaded in my server with only 80 Records ( 40 Nodes and 40 Edges ).

`for(Vertex vertex : graph.getVertices()){
	graph.getRawGraph().command("DELETE VERTEX" + vertex.getId());	
}
`

or even this one :

`
for(Edge edge : graph.getEdges()){
	graph.removeEdge(edge);
	graph.commit();	
}
for(Vertex vertex : graph.getVertices()){
	graph.removeVertex(vertex);
	graph.commit();
}
`

It takes often more than 90 seconds for the all thing to process on an 80 Records graph.
The problem seems to come from the action it self not the fact that I'm fetching ID.
My server is the running on the same machine as my application and the same Query on OrientDB Studio takes 0.02 seconds by nodes.

Any Idea what my problem might be ?

Additional Notes : 
I am accessing the database through a OrientGraphFactory("remote:...");
Then getting a Tx  : OrientGraph graph = factory.getTx() only once at he start of the application.

**Comment by maggiolo00** [comment]
Hi @edmondboulet 

first of all if you are using OrientDB 3.0 we advice you to use the new MultiModel API.

https://orientdb.com/docs/3.0.x/java/Java-MultiModel-API.html

Coming to your question it's slower because with Studio you are executing a delete statement
that is entirely executed on the server.

With your code you are

- Fetching one by one from the network each vertices in the Graph.
- And for each you are executing a server side command to delete the vertex with the RecordID

If you want the same performance you should execute a command From Java with a single delete statement

I hope it helps

**Comment by edmondboulet** [comment]
Hi @maggiolo00 

Thanks for the answer I will look into the multi model API.
I should have precised that with the java application I have a 1+ second time execution **by node** which mean I have 90 seconds execution time for the whole program ( 80 Records ).
Which means that for the same command ( fist code sample ) the command DELETE VERTEX + ID have very different execution time in Java ( 1 sec ) and in Studio ( 0.02 sec ), also I did benchmark that the query time for the ID value was negligible.

I will try a different approach with the multi model API as you suggest. Will kup.
Thanks again.

**Comment by maggiolo00** [comment]
Hi @edmondboulet 

here it's a quick test that i did.

```JAVA
import com.orientechnologies.orient.core.db.ODatabaseSession;
import com.orientechnologies.orient.core.db.OrientDB;
import com.orientechnologies.orient.core.db.OrientDBConfig;
import com.orientechnologies.orient.core.record.OVertex;
import com.orientechnologies.orient.core.sql.executor.OResultSet;
import org.junit.Assert;
import org.junit.Test;

public class QTest {

  @Test
  public void test() {

    OrientDB context = new OrientDB("remote:localhost", OrientDBConfig.defaultConfig());

    ODatabaseSession session = context.open("testdb", "admin", "admin");

    try {
      populateDb(session);

      long start = System.currentTimeMillis();

      try (OResultSet resultSet = session.query("select from V")) {
        resultSet.stream().map(r -> r.toElement()).forEach(oElement -> {
          session.command("delete vertex ?", oElement.getIdentity()).close();
        });
      }

      System.out.println(System.currentTimeMillis() - start);
      Assert.assertEquals(0, session.countClass("V"));
    } finally {
      session.close();
      context.close();
    }

  }

  public void populateDb(ODatabaseSession session) {

    OVertex lastVertex = null;

    session.begin();

    for (int i = 0; i < 1000; i++) {

      OVertex oVertex = session.newVertex();
      if (lastVertex != null) {
        oVertex.addEdge(lastVertex);
      }
      session.save(oVertex);
      lastVertex = oVertex;
    }
    session.commit();
  }

}
```

It completes on my box in 2/3 ~ secs

**Comment by edmondboulet** [comment]
Yes Thank you @maggiolo00  !
I just tested it myself and it is indeed much more competitive.
And thank you for your code sample, it will be very useful for my benchmark.

**Comment by maggiolo00** [comment]
Hi @edmondboulet 

i'm gonna close this. If you have issues related to this, please reopen it or open another one

Thanks
