### ISSUE TITLE
OrientDB make an inconsistency graph.

### ISSUE THREAD

**Issue by hazzasym** [orientechnologies/orientdb#8351]
## Expected behavior  
Graph should maintain consistency between vertex , edge.

## Actual behavior  
OrientDB has a conflict link or missing metadata between vertex.  

## Steps to reproduce  
I don't know how can this happened. But I found it while i'm drill down to investigated some problem that happen to our application.

Let's see the query out put below.

Please note that the record 173:443 was created by our application and then create an edge to connect with 140:136.

select out() from #173:443        
+----+----------+
|#   |out       |
+----+----------+
|0   |[#140:136]|                       <------------ correct
+----+----------+

select outE() from #173:443
+----+----------+
|#   |outE      |
+----+----------+
|0   |[#182:595]|                      <------------ correct
+----+----------+

select from #182:595
+----+--------+--------+----+--------+--------+
|#   |@RID    |@CLASS  |type|out     |in      |
+----+--------+--------+----+--------+--------+
|0   |#182:595|HardLink|file|#173:443|#140:136|                 <------------ correct
+----+--------+--------+----+--------+--------+

select inE() from 140:136

+----+---------------------------------------------+
|#   |inE                                          |
+----+---------------------------------------------+
|0   |[#183:595,#184:595,#189:591,#190:591,#355:15]|         <---- ??? where is the edge 182:595
+----+---------------------------------------------+

This mean that when I'm trying to list items related with 140:136 by our application we never see it.

Do you have any idea to suggest us for this case?

If more informations require please tell me.

Thank you,

**Comment by luigidellaquila** [comment]
Hi @hazzasym 

This could be due to an old bug (fixed long time ago).
My suggestion here is to manually fix the graph as follows:

```
UPDATE  #140:136 ADD in_<theEdgeClassNameHere> = #182:595
```

Please make sure that the `in_*` field name is correct, before running the update try to run a

```
SELECT in_<theEdgeClassNameHere> FROM #140:136
```

and see if the edges are there

Thanks

Luigi

**Comment by hazzasym** [comment]
Thank you @luigidellaquila for your response, 

So do we need an upgrade for our OrientDB server to prevent this bug? Which OrientDB version do this issue has fixed in?

Just to make sure because this problem happened to me yesterday on OrientDB version 0.2.33.

Thanks,

**Comment by luigidellaquila** [comment]
Hi @hazzasym 

Not sure about the exact version, but my advice is to upgrade to 2.2.36 (latest stable), and if you have a chance, have a look at v 3.0.2 that contains a lot of improvements

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @hazzasym 

Did it help? Can we consider this ticket closed?

Thanks

Luigi

**Comment by hazzasym** [comment]
Ok, you can consider close this ticket now, then we would try to upgrade our OrientDB to newest version therefor if this problem occur again we can issue ticket further.

Thanks,

**Comment by luigidellaquila** [comment]
Great, closing then

Thanks

Luigi
