### ISSUE TITLE
toLowercase method compromises indexed searches

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#8353]
## Expected behavior  
select * from CarbonUser where name.toLowercase() == 'mary' 
![image](https://user-images.githubusercontent.com/3224592/41727706-48737b3a-7575-11e8-86ba-b19b594d7120.png)

## Actual behavior  
select * from CarbonUser where name.toLowercase() == 'mary' 
![image](https://user-images.githubusercontent.com/3224592/41727671-2e07b054-7575-11e8-9033-c43202a37d17.png)

## Steps to reproduce  
Just use the toLowercase method on indexed fields in search query

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

That's correct, OrientDB cannot use indexes in this case. 
But you have at least two alternatives:

- you can define case-insensitive indexes and then do the query without the `toLowercase()`, eg.

```
CREATE INDEX CarbonUser.name ON CarbonUser (name COLLATE ci) NOTUNIQUE
```

- you can use LUCENE indexes, that are case insensitive by default

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
I execute
 CREATE INDEX CarbonUser.name ON CarbonUser (name COLLATE ci) NOTUNIQUE

And now it works as expected. 
![image](https://user-images.githubusercontent.com/3224592/41767727-b0888158-760a-11e8-91ff-3ba33317c9e6.png)


But there is still one scenario where the behavior is case sensitive.
If you use the `any()` construct  the database still perform a case-sensitive research, ignoring the ci collate

`select * from CarbonUser where any() = 'MAry'`
![image](https://user-images.githubusercontent.com/3224592/41767684-9ef1035c-760a-11e8-9000-c815a1638b3c.png)

Have you any suggestion for this scenario?
Gianluca

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
thanks a lot. What about the performace using LUCENE insteadof NOTUNIQUE?

In my opinon the LUCENE index is useful when you try to search a word in a big text. So I thought to exclude it as I need to search on some Class fields, as name, surname userid

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

Lucene performance is very good, even with small text, so you can definitely consider it

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Thanks a lot @luigidellaquila

**Comment by gianluca-valentini** [comment]
Do you think that Lucene index is good also for Long fields?

In my case I need also to execute a query where lastExecutionTime (is a Long) > 100000
but, looking the Explain result, no index is involved during its execution.
Thanks
Gianluca

**Comment by maggiolo00** [comment]
Hi @gianluca-valentini 

if you need range queries you can use Lucene

```
https://orientdb.com/docs/2.2.x/Full-Text-Index.html#numeric-and-date-range-queries-from-2214
```

**Comment by gianluca-valentini** [comment]
Thanks a lot
