### ISSUE TITLE
Vertex created via java api not visualized in OrientDb Studio

### ISSUE THREAD

**Issue by marcelalburg** [orientechnologies/orientdb#8354]
## Expected behavior  
I use in Java the gremlin API like this:

```
import org.apache.tinkerpop.gremlin.orientdb.OrientGraph;

graph = OrientGraph.open(serverUrl, USERNAME, PASSWORD);
		
Vertex root = graph.addVertex("test");
root.property("name", "root");
root.property("url_de", "");
root.property("key", ROOT_KEY);

```

after this, i open the studio in the graph mode and enter

`select from V`

but i didn't see my Vertex. If i create a vertex inside the studio it works. When i click back to "Browse" and compare the both vertex i didn't see any difference.

But i would like to see my programmatically created vertex inside the studio too. 

Thanks
Marcel

**Comment by luigidellaquila** [comment]
Hi @marcelalburg 

Please try to add a `graph.commit()` at the end, this should solve the problem.

If you are using v 3.0, I strongly suggest you to have a look at the Multi-Model API https://orientdb.com/docs/3.0.x/java/Java-MultiModel-API.html


Thanks

Luigi

**Comment by marcelalburg** [comment]
Hello, 

thanks for you fast answer. I make already a commit.

I created an repo where you can see what i did/do and can reproduce it.

https://github.com/marcelalburg/orientdb3-embedded

After you check out this repo, you need to extract orientdb studio first with the command

`mvn generate-sources`

in your IDE, you should make a breakpoint here:

https://github.com/marcelalburg/orientdb3-embedded/blob/master/src/test/java/example/RemoteStoringTest.java#L172

and run it in debug mode. 

If you take a look inside the console, i printed out the studio link.

username: root, password: 123

I hope this helps.

**Comment by maggiolo00** [comment]
Hi @marcelalburg 

i've just run your test, and i was able to see vertices in Studio - Browse and Graph Editor

**Comment by marcelalburg** [comment]
This is strange. I didn't. I test this on two different desktop machines and in chrome and safari.

**Comment by maggiolo00** [comment]
Here it's what i see

<img width="959" alt="screen shot 2018-06-22 at 15 17 18" src="https://user-images.githubusercontent.com/98812/41778598-719e4f7a-762f-11e8-9da7-bcdb7c2195d7.png">

**Comment by maggiolo00** [comment]
Can you add on your test this

```
logger.info("Vertex count: {}",g.V().count().next());
```

I got count 2

**Comment by maggiolo00** [comment]
Maybe you have some kind of Error on Studio?

**Comment by marcelalburg** [comment]
Hello,

i add your line and see:

`15:26:29.176 [graph-microservice] [main] INFO  example.RemoteStoringTest - Vertex count: 2`

Even i tested this with IntelliJ IDEA now and it's not working :(

![bildschirmfoto 2018-06-22 um 15 28 23](https://user-images.githubusercontent.com/4396769/41779178-47322d04-7631-11e8-9c97-a49cd3593237.png)
![bildschirmfoto 2018-06-22 um 15 28 10](https://user-images.githubusercontent.com/4396769/41779184-4b91efce-7631-11e8-989d-7b23c13464c8.png)

**Comment by maggiolo00** [comment]
Hi @marcelalburg 

i've found the problem.

remove `orientdb-graphdb` and use

```
<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-server</artifactId>
			<version>3.0.2</version>
			<scope>test</scope>
		</dependency>
```

in your pom.xml. `orientdb-graphdb` is deprecated and it's old TP2 implementation

**Comment by marcelalburg** [comment]
Wow, thanks man for this awesome help. As a suggestion, feel free to put my integration test class to your examples. i guess a lot of people needs to ramp up an working remote embedded orientdb for their test. 

Thanks
