### ISSUE TITLE
3.0.3-SNAPSHOT serious regression

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8355]
### OS: Win 7  

The attached schema script used to work with 3.0.2, but __does nothing__ in 3.0.3-SNAPSHOT:
```
connect 'plocal:c:/temp/my.db' admin admin;
load script 'schema.sql'
```
I suspect this has something to do with the fix for #8325 

[schema.zip](https://github.com/orientechnologies/orientdb/files/2125720/schema.zip)

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Thank you for reporting, I'm fixing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

I just pushed a fix, it should solve the problems

Thanks

Luigi

**Comment by hrstoyanov** [comment]
Thius seems fixed, please close.
