### ISSUE TITLE
Alternative property name?

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8358]
### OrientDB Version: 3

It'd be nice, if one can give additional alternative names for ```in/out``` edge properties:
```
create class MyEdge extends E;
create property MyEdge.in.account LINK Account;
create property MyEdge.out.user LINK User; 
```

This way, we can still use in/out for standard graph stuff, but also, the much more informative: account and user.

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Do you mean aliases for properties? We can consider it in next releases, I'll flag it as an enhancement

Thanks

Luigi

**Comment by hrstoyanov** [comment]
Thanks @luigidellaquila , yes "aliases", if it sounds better. I am not sure what the best syntax would be, for example:
```
create property MyEdge.in/account LINK Account;
create property MyEdge.in|account LINK Account;
create property MyEdge.[in,account] LINK Account;
```

**Comment by PhantomYdn** [comment]
Not sure what actually meant under aliases here... If there is need to have limitation for specific type of edge you can use something like `create property MyVertext.in_account LINK Account`

**Comment by hrstoyanov** [comment]
My understanding is that in/out have special meaning, therfor we need
aliases?

/Hristo Stoyanov
