### ISSUE TITLE
CSV extractor always skipping the first line

### ISSUE THREAD

**Issue by Kevin-Darty** [orientechnologies/orientdb#8361]
The CSV extractor is not importing the first line when the option `columnsOnFirstLine` is set to `false`.

json:
```
...
  "extractor": {
    "csv": {
      "columnsOnFirstLine": false,
      "columns": [
        "Id:string"
      ]
    }
...
```
csv:
```
"a"
"b"
"c"
```
### Java Version: OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

## Expected behavior  
3 vertices with the "Id" property set to "a", "b", "c"

## Actual behavior  
**2** vertices with the "Id" property set to "b", "c", **no "a"**

## Steps to reproduce  
oetl.sh vertex.json

**Comment by Kevin-Darty** [comment]
For information: with the same csv, with `columnsOnFirstLine` set to `true` or `false`, the result is always the same:
```
extracted 2 rows (0 rows/sec) - 2 rows -> loaded 2 vertices (0 vertices/sec) Total time: 517ms [0 warnings, 0 errors]
```

**Comment by pengyunshan** [comment]
I have met the same situation,have u solve this problem?

**Comment by Kevin-Darty** [comment]
No clean solution here...

If you add a *fake* first line, it will be skipped. Therefore, the rest of the csv will be used.
For example, the 3 vertices a, b, and c will be loaded with the following csv:
```
"Fake first line to solve this issue"
"a"
"b"
"c"
```

**Comment by rubensr** [comment]
This problem also exists in the 3.0.x versions - here is a branch with a patch that I believe solves this: [github proj](https://github.com/rubensr/orientdb/tree/8361-csv_extractor_skipping_first_line)
