### ISSUE TITLE
Delete vertex from Match queries does not remove every records

### ISSUE THREAD

**Issue by CyprienGottstein** [orientechnologies/orientdb#8362]
### OS: Ubuntu 16.04 

Hello OrientDB team ! I have more work for you, i fear.

## Expected behavior  
Delete from OSQL statement removing the same items as the one listed from the single Match statement

## Actual behavior  
Only part of the items listed by the match statement are removed

## Steps to reproduce  
I've joined a very simple database with a minimalistic data set. You just need to import it and do the two queries right below to see the problem appear.

[delete_from_match.gz](https://github.com/orientechnologies/orientdb/files/2146135/delete_from_match.gz)

The following search query returns 8 records :

> SELECT * FROM ( 
> SELECT expand(alias_res) FROM (
> MATCH 
> {class:my_class, as:alias_res} -knows-> {as:alias_a},
> {class:my_class, as:alias_a} -knows-> {as:alias_res}
> RETURN DISTINCT alias_res ) )

If this query is nested within a **delete vertex from ()**, it will only delete 5 records out of the 8 previously returned:

> delete vertex from ( 
> SELECT * FROM ( 
> SELECT expand(alias_res) FROM (
> MATCH 
> {class:my_class, as:alias_res} -knows-> {as:alias_a},
> {class:my_class, as:alias_a} -knows-> {as:alias_res}
> RETURN DISTINCT alias_res ) ) )

 ) where static = false)

And if you check the whole **my_class* class content, the output of the delete statement did not lied, you will only find 7 records left (instead of 12) :

> SELECT * FROM my_class

I don't have any idea about the cause, but i can also tell you that the output sometimes differ depending on the context of execution. In my test suites this usually removes 6 records out of 8 and i've seen this query removes 7 records out of 8 one time, executing it from the studio. Quite strange.

Also, as indicated into the OrientDB versions, i've confirmed this bug on both OrientDB v3.0.2 and v3.0.3-Snapshot, I didn't checked this properly on version 2.2.x but since the problem encountered right now if because we are moving totally our code from OrientDB v2.2.x to v.3.0.x, i guess it works in v2.2.x.

Best Regards

**Comment by luigidellaquila** [comment]
Hi @CyprienGottstein 

This is not a bug, this behavior is a consequence of how OrientDB v 3.0 executes queries. The result set is streamed, that means that the query result is calculated record by record and passed to the outer queries.

In this case, the DELETE statement gets records one by one from the MATCH statement and it deletes them as soon as it receives them. When the first records are deleted, some of the later results of the MATCH statement no longer match the pattern, so they are not returned, this leads to this behavior.

The work-around for this situation is to force the SQL executor to run the whole MATCH statement and do the DELETE operations all together, only at the end.
You can do it with a batch script, as follows:

```
LET $a =  
  SELECT * FROM ( 
     SELECT expand(alias_res) FROM ( 
        MATCH 
           {class:my_class, as:alias_res} -knows-> {as:alias_a}, 
           {class:my_class, as:alias_a} -knows-> {as:alias_res} 
        RETURN DISTINCT alias_res 
     ) 
  );
  
DELETE VERTEX FROM (SELECT expand($a));
```

I hope it helps

Thanks

Luigi

**Comment by CyprienGottstein** [comment]
Hi @luigidellaquila ,

Well, i think i understand your choices about streaming the record from the queries and i understand the work-around, i've tried it and made it work, fine.

For some reason we have to store the whole objects in the select of **LET $a**.

Why can't we just store the **#rid** and use that to make the delete vertex statement ? It's even shown in the documentation https://orientdb.com/docs/3.0.x/sql/SQL-Delete-Vertex.html, the very first example shows a delete vertex with a rid, we should be able to do the same from a select. I don't know exactly how the **LET $a** proceed when it stores data in memory but i fear we store a lot of things which are not needed.

Now, we are not quite satisfied on our side with this work-around for an other very simple reason, there is a possible scenario where we need to delete 1 billion of vertices, this will take a huge amount of memory to store everything before doing the deletion and it may even make OrientDB crash. 

This is quite unlikely but we prefer to think ahead. Is there a simple way to have kind of an intermediary table/index (like you would have using a good old Oracle SQL) to store the results of those find and do the delete using this table ?

It would slow down a lot the system as we need to do a bunch of writes and such but at least it would spare the memory and we would be sure of the result.

At last, maybe i missed it but there should be a warning into the documentation to ensure people are aware of the streaming behavior and possible side effects.

Best Regards,

Cyprien.

**Comment by CyprienGottstein** [comment]
About the problem of delete vertex from ( ** subquery returning rid **), this is the OSQL script i tried :

> LET $a = select @rid from ( SELECT * FROM my_class) where static = false; DELETE VERTEX FROM (select expand($a));

And this is the output of the result :

> com.orientechnologies.orient.core.exception.OCommandExecutionException: Current element is not a vertex: {
> @rid: #121:102
> }
> 	DB name="ziggy-dev"
> 	DB name="ziggy-dev"
> 	at sun.reflect.GeneratedConstructorAccessor98.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:318)
> 	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:275)
> 	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:191)
> 	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153)
> 	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1812)
> 	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:226)
> 	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:285)
> 	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:214)
> 	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:239)
> 	at com.orientechnologies.orient.client.remote.OStorageRemote.execute(OStorageRemote.java:941)
> 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.execute(ODatabaseDocumentRemote.java:395)
> 	at censored()
> 	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
> 	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
> 	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:524)
> 	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
> 	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 	Suppressed: com.orientechnologies.orient.core.exception.OCommandExecutionException: Current element is not a vertex: {
> @rid: #121:102
> }
> 
> 	DB name="ziggy-dev"
> 		at com.orientechnologies.orient.core.sql.executor.CastToVertexStep$1.next(CastToVertexStep.java:49)
> 		at com.orientechnologies.orient.core.sql.executor.DeleteStep$1.next(DeleteStep.java:32)
> 		at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:53)
> 		at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:37)
> 		at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:46)
> 		at com.orientechnologies.orient.core.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:31)
> 		at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.doExecute(OScriptExecutionPlan.java:88)
> 		at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.fetchNext(OScriptExecutionPlan.java:49)
> 		at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:35)
> 		at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:29)
> 		at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:54)
> 		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:587)
> 		at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1156)
> 		at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:133)
> 		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:284)
> 		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:186)
> 		at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)

When i perform this very simple query :

> SELECT * FROM #121:102

It returns a record of class **my_class** which inherits from V and is shown into the **Vertex Classes** section of the Studio - Schema Tab.

**Comment by luigidellaquila** [comment]
Hi @CyprienGottstein 

This happens because the projection in the SELECT query is not a vertex. You can make it work though, please try the following:

```
LET $a = select @rid as r from ( SELECT * FROM my_class where static = false) ; 
delete vertex from (select expand($a.r));
```

I also moved the condition ` where static = false` in the inner query, so that OrientDB will be able to use indexes, if present.

About big result sets and disk-backed data structures, currently we do not support it, but we know the problem and we have a solution in the roadmap. It won't be in the very short term, but we will definitely implement it in the near future.

Thanks

Luigi

**Comment by CyprienGottstein** [comment]
Hi @luigidellaquila ,

Alright, it works. About the `where static = false` i'm showing you the tip of the iceberg, we have request much more complex than that, this clause is just a protection, but i'll keep it in mind, good to know.

Too bad for the disk-backed data structures, we will do our own custom solution for the time being.

Thanks for your time,

Cyprien.
