### ISSUE TITLE
Hash-Index over ORecordId field

### ISSUE THREAD

**Issue by adler4566** [orientechnologies/orientdb#8364]
### Java Version: 1.8   

Hello,
I created with the custom batch insert my graph. No I wanted to create a Hash-Index over the `out` and `in` field of an edge. Those fields are typically from the type `ORecordID`.

If I use the following statement for creation:
    `CREATE PROPERTY EdgeConnectClass.out ORecordId`

I get the following Exception:
    `Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing`
    `Error: java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OType.ORECORDID`

Is this generally unintended to create an index over this type, do I something wrong, or is this an uninspected behaviour?

Kind regards
Sedir Mohammed

**Comment by adler4566** [comment]
Oh ok, thank you very much! I didn't see this in the documentation, sorry.

**Comment by adler4566** [comment]
And what type I should use when I want to create a index over the `rid`?

**Comment by maggiolo00** [comment]
@adler4566 

Hash index is fine. Then you have to choose if you want it to be UNIQUE or NOT_UNIQUE
I hope it helps

**Comment by adler4566** [comment]
@maggiolo00 Sorry, I didn't formulate the question correct. If I want to create a Hash index over the `rid` of a record, how the property generation would work? For example I want to create an index over the `rid's` of the Vertex.class, how would be the correct syntax to create the property for the `rid's`?

**Comment by maggiolo00** [comment]
@adler4566 

`@rid` of records cannot be indexed . Only link/linklist/linkset properties to other records.

`@rid` of record are automatically generated  by the database and you can consider them as physical address. So loading records by rid is super fast and it does not need an index

For example consider this queries

```
select from #21:13
```

The execution will not browse all record matching that `@rid` but will load the record by it's position.

Check here for more info about RecordID

https://orientdb.com/docs/2.2.x/Tutorial-Record-ID.html

I hope it helps

**Comment by adler4566** [comment]
Oh ok, I understand. Thank you!
