### ISSUE TITLE
Long.MIN_VALUE is parsed incorrectly in a query

### ISSUE THREAD

**Issue by ErikShiken** [orientechnologies/orientdb#8365]
## Expected behavior  
Parse Long.MIN_VALUE correctly for a query

## Actual behavior  
Parser throws an exception

## Steps to reproduce  
Use a query that check the value of a property using Long.MIN_VALUE
For example:
SELECT FROM V WHERE hs_3apoint >= -9223372036854775808

It appears the '-' is parsed first and then the number. Since 9223372036854775807 is the max long value, a parsing exception occurs.

**Comment by luigidellaquila** [comment]
Hi @ErikShiken 

Thank you very much for reporting, I'm checking it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
hi @ErikShiken 

I just pushed a fix to develop branch (3.0.x), it will be released with v 3.0.4

Now I'm backporting it to v 2.2.x

Thanks

Luigi
