### ISSUE TITLE
3.0.3 Connection Pool throws OTokenSecurityException after an hour of inactivity

### ISSUE THREAD

**Issue by 2082041S** [orientechnologies/orientdb#8369]
## Expected behavior  
The token should be refreshed when the user triggers an action such as "commit" against the OrientGraph object after an hour of inactivity passes by. 

## Actual behavior  
After one hour of inactivity, triggering an action throws the following exception: "com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired". Immediate further actions against the OrientGraph object throw the same exception. Currently we are able to fix this issue by catching it and calling "graph.rollback()" followed by "graph.makeActive()". However, this is contrary to what we expected from Orient's behaviour. We were under the impression that this issue has been fixed in Orient 3.0.0 as noted by @tglman in the following issue: https://github.com/orientechnologies/orientdb/issues/8050 

## Steps to reproduce  
Wait 62 minutes and run "graph.getVertices()" or "graph.commit()" where graph is an OrientGraph object

**Comment by 2082041S** [comment]
Issue was fixed by upgrading to 3.0.3

**Comment by CanonTino** [comment]
> Issue was fixed by upgrading to 3.0.3

I'm using 3.0.10 version and I'm having the exact same problem. The problem has not been fixed.

**Comment by tglman** [comment]
Hi @CanonTino,

There was a problem with the session management that was fixed, anyway if there is inactivity for more then the session length (that by default is one hour), you will get this error anyway, the suggest solution in this cases is increase the session length.

bye
