### ISSUE TITLE
Create Edge between two vertexes located on different nodes using Sharding

### ISSUE THREAD

**Issue by HassounDev** [orientechnologies/orientdb#8372]
### OS: <Debian>  

I have this configuration with 3 nodes (usa, europe and china) and I have 6 clusters with 2 clusters in each node.

Because in every node I will have a vertex customer and an edge phc, so in every node I created my customer vertexes with phc edges.

```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "customer_usa": {
      "servers" : [ "usa"]
    },
    "customer_europe": {
      "servers" : [ "europe" ]
    },
    "customer_china": {
      "servers" : [ "china"]
    },
    "phc_usa": {
      "servers" : [ "usa"]
    },
    "phc_europe": {
      "servers" : [ "europe" ]
    },
    "phc_china": {
      "servers" : [ "china"]
    },
    "*": {
      "servers" : [ "<NEW_NODE>" ]
    }
  }
}
```
But when I want to create an edge from a vertex in usa node to a vertex in europe, node it throws an error :

```
Error: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=2.45 task=tx[3]{record_create(#20:0 v.0),record_update(#17:0 v.1),record_update(#16:0 v.2147483646 realV.-2)}). Elapsed=68ms. Servers in timeout/conflict are:
 - usa: TX[3]{#20:0 v.1,_non_local_cluster,1} Received:
 - usa: TX[3]{#20:0 v.1,_non_local_cluster,1}
 - china: TX[3]{#20:0 v.1,_non_local_cluster,_non_local_cluster}
 - europe: TX[3]{#20:0 v.1,2,-1}

```

But when i change   "writeQuorum": "majority", to   "writeQuorum": 1, it works but my database becomes not consistence...

**Comment by adler4566** [comment]
But if you store a record on a specific server-node, is the record really stored locally? So for example, if you store a record from class X on node china and `phc_china` owns this class X are you sure that this record is really stored on node china? Or is it stored on an other server node where the local cluster owns the class X?

**Comment by HassounDev** [comment]
When you store on a specific server-node the record is stored locally, i will give you an example. store a record on the node `china`  then shut down the node `china `; u won't get anymore the record that you stored.
