### ISSUE TITLE
Is orientdb 3.0.x production ready? The documentation says otherwise

### ISSUE THREAD

**Issue by RamAnvesh** [orientechnologies/orientdb#8377]
## Expected behaviour  
[Documentation](https://orientdb.com/docs/last/release/3.0/Upgrading-to-OrientDB-3.0.html) should say it is production ready as mentioned [here](https://orientdb.com/docs/last) (Says 3.0.x is GA)

## Actual behavior  
Documentation says not product ready

## Steps to reproduce  
See https://orientdb.com/docs/last/release/3.0/Upgrading-to-OrientDB-3.0.html

**Comment by luigidellaquila** [comment]
Hi @RamAnvesh 

Thank you very much for pointing it out. 

OrientDB v 3.0 is definitely production ready, the docs are outdated, I'm fixing them now

Thanks!

Luigi

**Comment by RamAnvesh** [comment]
Thanks a lot for the lightning fast response!

**Comment by luigidellaquila** [comment]
Done, the new docs will be available in a few hours

Thanks!

Luigi
