### ISSUE TITLE
Class Level Hook is not triggered

### ISSUE THREAD

**Issue by jonsalvas** [orientechnologies/orientdb#8385]
## Expected behavior  
According to https://orientdb.com/docs/2.2.x/Dynamic-Hooks.html#class-level-hooks it should be possible to create dynamic hooks on class level. When I execute the queries exactly as described in the doc and insert a new entry I expect the message "Invoice created: 100" to be shown in the server console.

## Actual behavior  
Although I executed the commands exactly like described in the doc, no message is shown.

## Steps to reproduce  
Go to https://orientdb.com/docs/2.2.x/Dynamic-Hooks.html#class-level-hooks and follow the steps described.
1. CREATE CLASS Invoice EXTENDS OTriggered
2. ALTER CLASS Invoice CUSTOM onAfterCreate=invoiceCreated
3. CREATE FUNCTION invoiceCreated "print('\\nInvoice created: ' + doc.field('number'));" LANGUAGE Javascript
4. INSERT INTO Invoice CONTENT { number: 100, notes: 'This is a test' }
5. --> no message "Invoice created: 100" in Log

**Comment by jonsalvas** [comment]
OK I just tested with 2.2.35 and it works perfectly. Is it possible that the documentation in https://orientdb.com/docs/3.0.x/internals/Dynamic-Hooks.html is deprecated and needs to be updated?

**Comment by dremekie** [comment]
@jonsalvas I'm seeing the same problem. Have you been able to get anywhere with this?

**Comment by jymcheong** [comment]
Try with quotes: ALTER CLASS Invoice CUSTOM onAfterCreate='invoiceCreated'

**Comment by fgnm** [comment]
Same here, and I get it worked with quotes, verified with `INFO CLASS Invoice`.
However the print function not works.
I've test it with Studio and I've got the following result:
```JSON
{
    "errors": [
        {
            "reason": "Bad request",
            "code": 400,
            "content": "Error on parsing script at position #0: Error on execution of the script\nScript: invoiceCreated\n------^\r\n\tDB name=\"testDB\"\nReferenceError: \"doc\" is not defined in <eval> at line number 2\nReferenceError: \"doc\" is not defined"
        }
    ]
}
```

It seems that `doc` object does not exists anymore, documentation must be update as soon as possible. Thank you.

**Comment by SameerChorge94** [comment]
Hi,
Similar issue faced with OrientDB standalone server 
`OrientDB version : 3.1.3`

Tried @jymcheong shared answer 
`ALTER CLASS Invoice CUSTOM onAfterCreate='invoiceCreated'`
it didn't worked for me 

it's returning below error while creating new records 
`orientechnologies.orient.core.db.record.OIdentifiable; cannot be cast to class java.lang.String ([Lcom.orientechnologies.orient.core.db.record.OIdentifiable; is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')`
