### ISSUE TITLE
Stress test does not support GINSERT

### ISSUE THREAD

**Issue by soujiro32167** [orientechnologies/orientdb#8386]
## Expected behavior  
`/orientdb/bin/stressterster.sh -m plocal -k true -c 8 -w GINSERT:V1000F10` Should run the stress test locally

## Actual behavior  
Workload 'GINSERT' is not configured. Use one of the following: [CRUD]

## Steps to reproduce  
1. `$ docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb:3.0.3-tp3`
2. In the container: `docker exec -it orientdb sh`
3. Add bash support `apk add -U bash`
4. `cd bin`
5. Copy the stresstester script  into the container: `wget https://raw.githubusercontent.com/orientechnologies/orientdb/3.0.x/graphdb/script/stresstester.sh && chmod +x stresstester.sh`
6. Run the script with GINSERT workload `./stressterster.sh -m plocal -k true -c 8 -w GINSERT:V1000F10`

**Comment by cloudloveseven** [comment]
you need a high version orient-graph.jar

**Comment by cloudloveseven** [comment]
put orient-graph-3.0.3.jar in /orientdb/lib
