### ISSUE TITLE
AVG() function on Double field does not work

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#8390]
## Expected behavior  
Let globalRiskScore a double field on CarbonUSer Vertex

SELECT avg(globalRiskScore) from CarbonUser 

give me the correct avg value

## Actual behavior  
the query does not work and don't give me the correct value

![image](https://user-images.githubusercontent.com/3224592/42523763-008f2dd8-846f-11e8-98a8-54555de9f1a0.png)

note that:
- globalRiskScore has always not null
- trying to use asLong() method (wrongly) the query will give me 0 (wrongly)

## Steps to reproduce  
Just Create some Vertices with double field and use the avg function on it

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

I just tried the following on latest 2.2 and it seems to work fine

```
create class foo
create property foo.val double
insert into foo set val = 10d
insert into foo set val = 20d
insert into foo set val = 40d

select avg(val) from foo
```

Any clue on how to reproduce the problem?

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
thanks for your answer. 

It works well on my OrientDB if I use a double without dot (just integer number).
But when I have decimal number (a real double i.e. 10,5) I have the reported error.

Have you any idea about it?
Thanks
Gianluca

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

I just tried with 1.4 and it still works fine. 
Do you have a script that reproduces the problem on a fresh db?

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
I created a brand new environment just for this issue.

While setting up it, I had this error trying to create the Lucene index on both text and number fields

![image](https://user-images.githubusercontent.com/3224592/42566310-7763d2c8-8506-11e8-8f54-11f5ce5a6227.png)

In our production environment we created Lucene indexes using java code

![image](https://user-images.githubusercontent.com/3224592/42566343-8f057260-8506-11e8-9083-79309db84716.png)

Could this be, in your opinion, the cause of the avg error on my env?
Why I can create LUCENE index using java, but this is not possible using the UI?

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
I understand the problem. I found some `NaN` values in the globalRiskScore field data.

Now i will fix my code to change this value, but I think that the UI should be able to manage it as NaN is a Double.

Thanks
Gianluca

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

Probably it's not the UI but the avg() function that cannot manage NaN correctly, I'll check it asap

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
thanks a lot.

Now I updated the `NaN ` values and now avg works fine :)
My next step is avg on percentile of that field! 
I hope to be able to execute it :)

Thanks
Gianluca

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
can you help me with another problem that I can not understand?

I'm executing a query with a `distinct` and `in` functions.

> select distinct(in('Account2Analysis')) as obj from Analysis where sDay between 451 and 478

where Account2Analysis is an Edge.
Query execution is very fast, thanks to your advice on LUCENE indexes.

![image](https://user-images.githubusercontent.com/3224592/43191009-977eb3a8-8ffa-11e8-9161-955096f0a068.png)


The problem comes out when I want to apply a sort. **The query is very very slow**!!!

> select distinct(in('Account2Analysis')) as obj from Analysis where sDay between 451 and 478 order by obj

![image](https://user-images.githubusercontent.com/3224592/43191564-b0979b7e-8ffb-11e8-9523-fceaeee04001.png)

you can help me figure out where I'm wrong?
Thanks a lot
Gianluca
