### ISSUE TITLE
Invalid WAL record type was passed class com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFileTruncatedWALRecord. Given record will be skipped. [OLocalPaginatedStorage]

### ISSUE THREAD

**Issue by niraj-cs** [orientechnologies/orientdb#8392]
## Expected behavior  
After truncating classes through script it shouldn't give issues at next restart of server.

## Actual behavior  
After truncating classes through script and restart of server, multiple logs of:
 _**SEVER {db=cs} Invalid WAL record type was passed class com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFileTruncatedWALRecord. Given record will be skipped. [OLocalPaginatedStorage]**_ are shown on console

## Steps to reproduce  

1.) 

Truncate your classes through following script

```
connect remote:localhost/xyz admin admin
js
var vertexClasses = db.query('select name from (select expand(classes) from metadata:schema) where superClasses in ["V", "E","Standard"]');

for( var i = 0; i < vertexClasses.length; i++ ){
  var className = vertexClasses[i].getRecord().field('name');
  db.command('TRUNCATE CLASS ' + className + ' UNSAFE');
}
end;
exit;

```
2.) Restart the server.

**Comment by laa** [comment]
Hi @niraj-cs , you do not restart server you kill the server, and the server tries to restore damaged data. You can not restore truncation of class that is inherently unsafe that is why you have the warning on restore phase of start of the server. I suggest you do not truncate class but remove data record by record. Also better do not kill server but perform a soft shutdown.
