### ISSUE TITLE
NOTUNIQUE indexes raise exception when inserting duplicate values.

### ISSUE THREAD

**Issue by hptvl** [orientechnologies/orientdb#8393]
### OS: Centos 
In my orientdb database,  I add a NOTUNIQUE index that is a combination of three (sourceIP, destinationIP, occurTime). Regarding to [OrientDB docs](https://orientdb.com/docs/2.2.x/Indexes.html):
`NOTUNIQUE These indexes allow duplicate keys.` As my understanding, it does allow inserting duplicate value of above combination but it does not. Do I misunderstand anything about this type of index?
My orientDB is setup  distributed mode.
## Expected behavior  
Allow inserting duplicate value of (sourceIP, destinationIP, occurTime) which is set NOTUNIQUE index.
## Actual behavior  
Throws exception  like "com.orientechnologies.orient.core.index.OIndexException: Found
duplicated key 'A' in index 'Alert (sourceIP, destinationIP, occurTime)' previously assigned to the
record #6:0        at ....

## Steps to reproduce  
Create an NOTUNIQUE index in vertex and insert duplicated value.

**Comment by mehdizarepour** [comment]
Hi @hptvl
It works fine! are you sure you didn't use a `UNIQUE` index?!

**Comment by hptvl** [comment]
@mehdizarepour, I don't think I use wrong index. Please check the attached screenshot with second index.
![nounique](https://user-images.githubusercontent.com/3870833/42744147-2078efae-8905-11e8-8a31-9f5cf2fc08d5.png)

**Comment by luigidellaquila** [comment]
Hi @hptvl 

This is pretty strange, we used NOTUNIQUE indexes everywhere for years, it never happened to me to see such problem. 

Do you have a way to reproduce the problem?

Thanks

Luigi

**Comment by hptvl** [comment]
@luigidellaquila:
In OrientDB design, I try to create a parent class, lets say "Event". Under Event class, there are three sub classes extend from Event including: Alert, IPS, WAF. In the Event, there is only 1 UNIQUE index for id and Alert has another index NOTUNIQUE which is mentioned above(a combination of 3 properties). 

In the java code, Alert, IPS, WAF events are inserted using transaction and massive insert mode.
`graph.addVertex("class:" + className, properties);`

That's all what I use OrientDB for. Till now, I removed that index for temporary solution.

**Comment by luigidellaquila** [comment]
Hi @hptvl 

Again, it's definitely not easy to reproduce, so if you could share a script or a DB that reproduces the problem, it would help a lot

Thanks

Luigi

**Comment by hptvl** [comment]
Hi @luigidellaquila 
Please check the attached file. Thank you for your kind support.
[pure-graphdb-20180420.gz](https://github.com/orientechnologies/orientdb/files/2200539/pure-graphdb-20180420.gz)

**Comment by luigidellaquila** [comment]
Hi @hptvl 

I checked the db you provided:

```
INDEXES
+----+--------------------------------------+---------------------+-------+---------+-------+------------+
|#   |NAME                                  |TYPE                 |RECORDS|CLASS    |COLLATE|FIELDS      |
+----+--------------------------------------+---------------------+-------+---------+-------+------------+
|0   |___exportImportRIDMap                 |DICTIONARY_HASH_INDEX|0      |         |default|            |
|1   |Alert.destinationIP_sourceIP_occurTime|UNIQUE               |0      |Alert    |       |            |
```

`Alert.destinationIP_sourceIP_occurTime` is UNIQUE...

Luigi

**Comment by hptvl** [comment]
@luigidellaquila 

Thanks so much.  It makes sense now.
