### ISSUE TITLE
Can we create OrientDB database with localeLanguage other than English?

### ISSUE THREAD

**Issue by shubhambondarde** [orientechnologies/orientdb#8394]
I want to create OrientDB database with different locallanguages.
What is the Java API for this?

**Comment by mehdizarepour** [comment]
Hi @shubhambondarde 
You can do it by [clusters](https://orientdb.com/docs/2.0/orientdb.wiki/Tutorial-Clusters.html).

**Comment by shubhambondarde** [comment]
Hi @mehdizarepour 

Thanks for the reply,
can you please tell, how should we define different languages per cluster?
What is the command or API we should use to use different languages?

**Comment by mehdizarepour** [comment]
@shubhambondarde Please read orientdb documents.
[CREATE CLUSTER](https://orientdb.com/docs/2.2.x/Console-Command-Create-Cluster.html)
[INSERT](https://orientdb.com/docs/2.2.x/Console-Command-Insert.html)
