### ISSUE TITLE
Can I upgrade the lucene version with OrientDB v2.2.x?

### ISSUE THREAD

**Issue by Leeingnyo** [orientechnologies/orientdb#8402]
* OrientDB Version: 2.2.36
* Java Version: 1.8
* OS: Ubuntu 16.04

Hi, I'm using OrientDB on my physical server now,
and I couldn't upgrade OrientDB to v.3.0.x because using version 3.0.x made my server CPU hotter, the heat of the server turned off the server.

I want to use full text index with lucene Korean analyzer, but [`analyzers-nori`](https://issues.apache.org/jira/browse/LUCENE-8231) is included at lucene [v7.4](https://lucene.apache.org/core/7_4_0/index.html).
In this situation, I would upgrade lucene only... or include a library.
Is there anything I can do for this?

Thank you.

p.s. I'm sorry but I'm not familiar with Java programming. (I'm using orientjs)

**Comment by luigidellaquila** [comment]
Hi @Leeingnyo 

I'm afraid you cannot upgrade Lucene out of the box, it wouldn't work property.

About the problems with 3.0, can you please share some more info? Maybe we can just fix it

Thanks

Luigi

**Comment by Leeingnyo** [comment]
Hi, @luigidellaquila 
Thanks to your answer.

I think my server machine is too old (7-years-old laptop) to stand OrientDB. With 2.2, the temperature of CPU was under 90°C when query sent. But with 3.0, the temperature was over 100°C and the server went off...
Never mind of this problem. I'm going to use cloud instance.

Again, thank you for answering. I'll close this issue.
Thanks.

Inyong Lee
