### ISSUE TITLE
OrientDB SQL DISTINCT function

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#8407]
### OrientDB Version: <version here>  
2.2.36

The [documentation says here](https://orientdb.com/docs/2.2.x/SQL.html#distinct):

> In SQL, DISTINCT is a keyword but in OrientDB it is a function, so if your query is:
> `SELECT DISTINCT name FROM City`
> 
> In OrientDB you would write:
> `SELECT DISTINCT(name) FROM City`
> 

But in SQL, let's take a look at the [grammar of ANSI-SQL-99](https://github.com/ronsavage/SQL/blob/master/sql-99.bnf) as example, the set quantifier applies to all the fields.
```
<query specification> ::= SELECT [ <set quantifier> ] <select list> <table expression>
<set quantifier> ::= DISTINCT | ALL
```

So in ANSI-SQL-99, `SELECT DISTINCT foo, bar FROM table` is a valid query.

What is the equivalent in OrientDB SQL?

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

In v 2.2 there is no equivalent to standard DISTINCT.
In v 3.0 the standard DISTINCT syntax is already supported

Thanks

Luigi

**Comment by diegomtassis** [comment]
Thanks @luigidellaquila

**Comment by civanescu** [comment]
The v 3.0 syntax for DISTINCT isn't working in pyorient. :|
