### ISSUE TITLE
Batch gremlin queries - OrientDB 3 with TP 3

### ISSUE THREAD

**Issue by sweetmangosweet** [orientechnologies/orientdb#8408]
## Expected behavior  
I'm using OrientDB 3, and I'd like to execute a series of gremlin queries outside of Gremlin Conosle. Specifically, I'd like to run Gremlin Recipe for [Centrality](http://tinkerpop.apache.org/docs/current/recipes/#centrality)

To achieve my goal, I'm trying to use Batch command from OrientDB 3 RESTful API. However, I receive this error whenever I set language to gremlin:

**"java.lang.IllegalArgumentException: Cannot find a command requester for type: gremlin"** 

![screen shot 2018-07-17 at 1 50 47 pm](https://user-images.githubusercontent.com/11001580/42845700-a387d402-89cb-11e8-95aa-672cf84905eb.png)

Is there any config file that should be modified in order to use Gremlin in HTTP API?

**Comment by yoavnativ** [comment]
Hi - I have the same issue, How can I send a batch of Gremlin commands via REST APIs?
