### ISSUE TITLE
INSERT ... RETURN @rid and @this and $current doesn't work

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8411]
## Expected behavior  
an inserted rid  

## Actual behavior  
null
and this code doesn't create record
```RETURN $current.name``` returns 'Spain', but without creating record in db.
Without RETURN works properly   

## Steps to reproduce  
``` 
insert into `DCountry`
set name = 'Spain', code = 'ES'
RETURN @rid
```

**Comment by luigidellaquila** [comment]
Hi @freeart 

I just pushed a fix for this problem, it will be released with v 3.0.5

Thanks

Luigi
