### ISSUE TITLE
Case-Insensitive comparison failed on outgoing Vertex's property having `COLLATE CI` with SQL query

### ISSUE THREAD

**Issue by dvssmgk** [orientechnologies/orientdb#8416]
## Expected behavior 

```
SELECT name, ceo, first(out("HEADQUARTERED_IN").name) as state FROM Company WHERE out("HEADQUARTERED_IN").name = "Washington"
```
With the `name` property on `State` Vertex class, having `COLLATE CI` for case-insensitive comparison, above SQL Query should return below results

![image](https://user-images.githubusercontent.com/8291693/42948706-b5fb4330-8b8d-11e8-8925-4c091acff9ba.png)

similar to the Graph Query (which works as expected)
```
MATCH {class: Company, as: company}.out("HEADQUARTERED_IN"){class: State, as: state, where: (name = "Washington")}
return company.name as name, company.ceo as ceo, state.name as state
```

## Actual behavior  
Instead of expected case-insensitive comparison, results were fetched matching the exact case as below from the SQL Query.

![image](https://user-images.githubusercontent.com/8291693/42949708-fae9b16e-8b8f-11e8-80b9-97045368a8f1.png)

But, while filtering directly on the `State` Vertex, results were fetched with expected case-insensitive comparison as seen below

```
SELECT name as state FROM State WHERE name = "Washington"
```

![image](https://user-images.githubusercontent.com/8291693/42950850-7dba566e-8b92-11e8-8284-c3e8d4601bf8.png)

## Steps to reproduce  
1. Create two Vertex classes `Company` and `State`
2. Create a case-insensitive property `name` on `State` Vertex
3. Create an Edge class `HEADQUARTERED_IN`
4. Insert below data
```
CREATE VERTEX Company CONTENT {name: "Amazon", ceo: "Jeff Bezos"}
CREATE VERTEX Company CONTENT {name: "Microsoft", ceo: "Satya Nadella"}
CREATE VERTEX State CONTENT {name: "Washington"}
CREATE VERTEX State CONTENT {name: "WASHINGTON"}
CREATE EDGE HEADQUARTERED_IN FROM (SELECT FROM Company where name = "Amazon") TO (SELECT FROM State where name = "Washington")
CREATE EDGE HEADQUARTERED_IN FROM (SELECT FROM Company where name = "Microsoft") TO (SELECT FROM State where name = "WASHINGTON")
```
5. Execute both the SQL and Graph queries mentioned above

**Comment by markodjurovic** [comment]
Hi @dvssmgk 

you can achieve desired behavior with slightly different query:

`select company:{*}, state.name from (match {class: Company, as: company} -HEADQUARTERED_IN-> {class: State, where: (name = "waShington"), as: state} return company, state)`
