### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8418]
Is OrientDB 3.0.x still milestones or is it "production ready??

![image](https://user-images.githubusercontent.com/5327044/42960400-8916e5ec-8b40-11e8-8705-c75cd155a177.png)

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Sorry, I missed it, thank you for pointing it out.
It's production ready of course, I'll fix it ASAP

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

I just pushed a fix, the new docs will be published in next few hours

Thanks

Luigi
