### ISSUE TITLE
Orientdb Edge class having property name starting with a number fails while fetching the edge

### ISSUE THREAD

**Issue by shubhambondarde** [orientechnologies/orientdb#8435]
## Expected behavior  
There should not be any error while fetching  the record containing attribute whose name is starting with a number, as orientdb is letting us create the attribute with name starting with number and also letting us insert the edge into the edge class.

## Actual behavior  
For **Remote** oriendb database, we created an edge class with name - "test".
We also created a property on that class with name - "2Test_Property"
The property created successfully. We also created Unique index on that property.
We tried to add the edge to this edge class and it successfully got created.
But while fetching the edge we are getting following error:

caused by: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
select rid from index:test.2Test_Property where key = ?
Encountered " <FLOATING_POINT_LITERAL> ".2 ""

**The same case is working properly in case of plocal mode.**  

## Steps to reproduce  
1. Create a remote orientdb database. 
2. Create a edge class and create a property whose name is starting with a number. 
3. Create index on that property. 
4. Insert a edge into the edge class 
5. Try to fetch the edge.

**Comment by luigidellaquila** [comment]
Hi @shubhambondarde 

Property names starting with numbers are allowed, but you have to back-tick quote them:

```
select rid from index:`test.2Test_Property` where key = ?
```

Thanks

Luigi

**Comment by shubhambondarde** [comment]
Hi @luigidellaquila 

We are getting edges by using OrientBaseGraph.getEdges(String iKey, Object iValue) API.
We are not using direct SQL query to get the edges.
Also, we are using same API in case of plocal mode and remote mode.
In plocal mode it works, but in remote mode it gives parsing error.

-Shubham Bondarde

**Comment by luigidellaquila** [comment]
Hi @shubhambondarde 

Thank you very much for the info, so the problem must be in the core.
I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @shubhambondarde 

I just pushed a fix for this problem, it should be released with v 2.2.37

Thanks

Luigi
