### ISSUE TITLE
Edge rid is not associated to the vertex in optimistic transaction. Leads to broken graph.

### ISSUE THREAD

**Issue by balalakshmin** [orientechnologies/orientdb#8438]
## Expected behavior  
```
String query = "$a = (select from A); $b = (create vertex B); $e = (create edge AB from $a to $b);"
db.begin(OTransaction.TXTYPE.OPTIMISTIC);
db.execute(query);
db.commit();
```
The above query should create a vertex of type B and an edge between A and B. 

## Actual behavior  
The above query creates the vertex and edge records. 
It forms proper association with the newly created vertex (@rid of the edge is added to $b in the above query) 
But **@rid of the edge is not added as OUT property to the existing vertex** ($a in above query). (The updated vertex is not committed).

But the below works:
```
begin; $a = (select from A); $b = (create vertex B); $e = (create edge AB from $a to $b); commit;
db.execute(query);
```
On debugging found that `_contentChanged` flag is reset to false while committing the transaction.

## Steps to reproduce  
Any case where an edge is created between an existing vertex and a new vertex. 
The edge @rid is not added to existing vertex

**Comment by userg** [comment]
On further debugging found that the flags are being reset in the following place
`ODatabaseDocumentRemote.java `
```
private void checkAndSendTransaction() {
    if (this.currentTx.isActive() && ((OTransactionOptimistic) this.currentTx).isChanged()) {
      if (((OTransactionOptimistic) this.getTransaction()).isAlreadyCleared())
        storage.reBeginTransaction(this, (OTransactionOptimistic) this.currentTx);
      else
        storage.beginTransaction(this, (OTransactionOptimistic) this.currentTx);
      ((OTransactionOptimistic) this.currentTx).resetChangesTracking();
    }
  }
```
The last line is resetting the flags which makes any updates within the optimistic transaction void.
Please let know if we are doing something wrong.

**Comment by userg** [comment]
Any updates on this?
