### ISSUE TITLE
8 node cluster cannot recover from short network disconnect

### ISSUE THREAD

**Issue by ygyg70** [orientechnologies/orientdb#8445]
## Expected behavior  
Cluster should be resilient to network disruptions

## Actual behavior  
After disconnecting a node for 10-15 sec and reconnect, most of the times the cluster never recovers and serves become unavailable .
If I wait for the cluster to broadcast a new topology, the cluster recovers once the disconnected node is connected again. This typically takes about 30 sec.
Each time I get different messages in the logs, there isn't any consistent pattern of failure.
Sometimes I get endless messages like this:
Node is not online yet (status=MERGING), blocking the command until it is online
Sometimes I get endless messages like this:
Server '{node_name}' cannot acquire distributed lock on resource '{db_name}' 

## Steps to reproduce  
Start a new cluster with 8 nodes
Disconnect network of one node for 5-15 sec
Reconnect the network

[default-distributed-db-config.json.txt](https://github.com/orientechnologies/orientdb/files/2251552/default-distributed-db-config.json.txt)

**Comment by cloudloveseven** [comment]
hi，juravler,I have the similar problem like you, I can not deal split brain network problem,server nodes go down 。

**Comment by ygyg70** [comment]
Definitely not a split brain thing for me. One left out of 8 with majority quorum.
With 3 nodes, 9 out of 10 times it worked for me when the disconnect is very short. One time the cluster got confused and never got back to functioning state.
I can see how inserting data into the disconnected node can make things even more unstable.
I am wondering whether this is not supported/discussed/tested or there are some undocumented ways to configure Orient/Hazelcast.
Hazelcast explicitly say on they deployment guide that a large cluster is as stable as the network, however I am not sure 8 nodes is a large cluster for them
Can't say whether the root of the issue is Hazelcast or Orient

**Comment by arpitaagarwal** [comment]
Hi @ygyg70
Can you please share the configuration which you are using to run 8 node cluster. I am struggling to make 3 node cluster work properly.
Are write operations concurrent on your database?

**Comment by ygyg70** [comment]
> 
> 
> Hi @ygyg70
> Can you please share the configuration which you are using to run 8 node cluster. I am struggling to make 3 node cluster work properly.
> Are write operations concurrent on your database?

Can you be more specific regarding "work properly"? 
With 8 nodes, I have issues around starting the cluster and simulating network disruptions, otherwise it is pretty stable. The application is multi-user, multi threaded, but the nature of the app is mostly reads.

**Comment by arpitaagarwal** [comment]
Mine is a write intensive application. OrientDB causes exceptions in concurrent write operations. 

I am using Orient 3.0.10 and facing same issue on concurrent write. I have created following setup -
2 node cluster
copied orientdb folder at 2 different locations and started ./dserver.sh file. Both nodes connected to each other through multicast
Using Person-FriendOf example code to write 10k Person-FriendOf-Person (vertex-edge-vertex). There are multiple threads writing same data each.
Person:name has unique index
It works well for 2 threads but as number of threads increases, it times out.
Getting following logs - Timeout (1244ms) on waiting for synchronous responses from nodes=[node2, node1] responsesSoFar=[node2] request=(id=1.105226 task=TxPhase1) [ODistributedDatabaseImpl]

Any clues?

**Comment by ygyg70** [comment]
This is definitely not the issue I was describing.
There are two things that come to my mind:
1) In the past it was recommended to use course grain transactions in distributed mode, not sure it is still valid on V3
2) Change the cluster propagation to be asyncronous
