### ISSUE TITLE
Unable to query by last element in embeddedmap

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#8451]
### OrientDB Version: 2.2.36

Hi,

I was wondering if i am doing smth wrong. We have a record with an attribute `history`, which is like an associative array. Below is the `history` attribute example:

```json 
{
    "123":
        {
            "referenceId":"123", 
            "paidTime":"2018-08-01 00:00:00"
        },
    "234":
        {
            "referenceId":"234", 
            "paidTime":"2018-08-08 00:00:00"
        }
}
```

I wanted to get all those records in which the **last** history's `paidTime` is in between certain date range. For instance,

```sql
select id, last(history), history.size() from MyClass
where history is not null and history.size() > 0 
and eval('last(history)').paidDate >= '2018-08-05 00:00:00' 
and eval('last(history)').paidDate <= '2018-08-1023:59:59'
```

or this

```sql
select id, last(history), history.size() from MyClass
where history is not null and history.size() > 0 
and last(history).paidDate >= '2018-08-05 00:00:00' 
and last(history).paidDate <= '2018-08-10 23:59:59'
```

Both the queries did not produce any results. Is there any way of doing that **w/o having to do a nested query**?

**Comment by luigidellaquila** [comment]
hi @andreyvk 

is `paidTime` a string or a DATETIME?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Great, thanks!

Luigi
