### ISSUE TITLE
Upgrade from 2.2.29 to 3.0.5 needs export and re-import?

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#8452]
I use OrientDB  2.2.29 in production for a 6 month，and we want to upgrade OrientDB to newest version 3.0
Do we need to stop the database、export and re-import data？

export and re-import means stop running for a long time，it is a bad affection on production.

My English is not very well, thanks reading.

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

Yes, for upgrades between major versions we always suggest to do an import/export.

Thanks

Luigi

**Comment by lightjiao** [comment]
thanks
