### ISSUE TITLE
Update 3.0 Rest API document

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#8453]
I use OrientDB 2.2.29 with Rest API in production, it works fine and has very good performance.

We have plan to upgrade our OrientDB to v3.0.x, we need to know if there is any change of Rest API .

[this official document](https://www.orientdb.com/docs/last/misc/OrientDB-REST.html) doesn't tells me any thing. 
- If there is nothing to change, please write on the document,
- if there is something different, please list on the document.

thank you to create OrientDB

My English is not very well, thanks reading.

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

There is no difference in the REST API, but there are some changes in the underlying components.
Probably it's worth checking the following:

https://orientdb.com/docs/3.0.x/release/3.0/SQL-Changes.html
https://orientdb.com/docs/3.0.x/release/3.0/API-Changes.html
https://orientdb.com/docs/3.0.x/release/3.0/Upgrading-to-OrientDB-3.0.html

Thanks

Luigi
