### ISSUE TITLE
Free up lucene resources after a search

### ISSUE THREAD

**Issue by rtm81** [orientechnologies/orientdb#8455]
## Expected behavior  
In my project i use orientdb 2.2.x and at the moment i can not change to 3.x.
There are several lucene fulltext indexes included to support the search use cases.
In some scenarios my customer triggers a database restore during the runtime of the application.

The database restore works like this:

            db.drop(); // drops current database
            db.create(); // creates a clean and fresh new one

            try (InputStream in = Files.newInputStream(backupPath)) {
                db.restore(in, null, null, listener);
            }

The search use case and the restore use case must work.

## Actual behavior  
This database restore fails, when there was some lucene searches before.
One lucene file (_0.cfs) can not be deleted by the db.drop().
I tried to delete the file in between, but somehow it was locked.

## Steps to reproduce  
[orientlucenebug.zip](https://github.com/orientechnologies/orientdb/files/2269312/orientlucenebug.zip)

If you execute the test provided in the orientlucenebug.zip, you will see that the test fails, because of the described problem.
The lucene file c:\temp\orientlucenebug\database\luceneIndexes\MyVertex.myProperty\_0.cfs is locked and can not be deleted.

I did an extended debug session with orientdb and lucene.
That is what i found out:
In method com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.searcher() there is

IndexSearcher searcher = searcherManager.acquire();

but this searcher is never released. 
With Lucene is is important to always release the acquired objects after usage to free the underlying resources.

I did a patch, that does the release in method
com.orientechnologies.lucene.collections.OLuceneResultSet.OLuceneResultSetIterator.hasNext()

[orientlucenebug-patch.zip](https://github.com/orientechnologies/orientdb/files/2269331/orientlucenebug-patch.zip)

I am not sure if this is the right place to fix the issue.
But i saw that there is something similar in the 3.x branch.
I could not use this code, because the method "engine.release(searcher)" is not present in the 2.2.x branch
see https://github.com/orientechnologies/orientdb/blob/3.0.5/lucene/src/main/java/com/orientechnologies/lucene/collections/OLuceneResultSet.java#L190

I can not migrate to the 3.x version at the moment and i would prefer an official fix in the 2.2.x branch.

**Comment by wolf4ood** [comment]
Hi @rtm81 

does  your patch resolve this issue?

**Comment by wolf4ood** [comment]
Hi @rtm81 

i've just pushed your fix in 2.2.x. All tests are passing

It will be available in the next release

Thanks

**Comment by letsbringachange** [comment]
we are facing similar issues with 3.0.21, where once the database is dropped, few indexes folders are not deleted in luceneIndexes folder. 

When the DB is created again, intermittently it results into error while creating the indexes left behind from previous drop.
