### ISSUE TITLE
Back quote behavior is different between 2.2.x and 3.0.x

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#8457]
## Expected behavior  
back quote character don't return in the result schema

## Actual behavior  
result schema have back quote character

## Steps to reproduce  
I have 3 sql need to execute
```sql
sqlA: select `name` from v_instance_app limit 1

execute result:
{
    "result": [
        {
            "`name`": "emm-nginx"
        }
    ]
}
```

```
sqlB: select `cluster` from v_instance_app limit 1

execute result:
{
    "result": [
        {
            "`cluster`": null
        }
    ]
}
```

```
sqlC: select cluster from v_instance_app limit 1

get a exception
{
  "errors": [
    {
      "reason": 400,
      "code": 400,
      "content": "Error parsing query:\u000aselect cluster from v_instance_app limit 1\u000a     ^\u000aEncountered \" <SELECT> \"select \"\" at line 1, column 1.\u000aWas expecting one of:\u000a    <LET> ...\u000a    <EXPLAIN> ...\u000a    \u000d\u000a\u0009DB name=\"cmdb_org_1028\"\u000d\u000a\u0009Error Code=\"1\""
    }
  ]
}
```

My question is:
- I use back quote in 2.2.x everywhere, should I trim the back quote?
- how can I get `cluster` schema with sql?

**Comment by lightjiao** [comment]
I use this sql to solve my problem
```sql
select `cluster` as `cluster` from v_instance_app limit 1
select @version as `@version` from v_instance_app limit 1
```

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

I'd say it's a bug, I'll check it asap

About the cluster schema, the following should help:

`select expand(classes) from metadata:schema`

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

I tested it on latest snapshot and it seems to be fixed already.
An upgrade should solve the problem

Thanks

Luigi
