### ISSUE TITLE
Filter on list contains null

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8460]
## Expected behavior  
expected the query to return all vertices

## Actual behavior  
the query returns nothing

## Steps to reproduce  
```
create vertex v set name = 'bob'
create vertex v set name = 'alice'
create edge e from <bob rid> to <alice rid>
select *, bothE().name as edgeNames from v where bothE().name contains null
```
When you do the selection without the where clause, edgeNames is a list of nulls. Is there a way to filter on that? I would like to check that the list contains a null

**Comment by markodjurovic** [comment]
Hi @creisle 
try with:
`select * from (select *, bothE().name as edgeName from foo unwind edgeName) where edgeName is null`

**Comment by markodjurovic** [comment]
@creisle 
with version 3.1 (right now it can be built from develop branch), "CONTAINS null" will also work

**Comment by creisle** [comment]
@markodjurovic awesome! thank you! That is great news :) (the first workaround wouldn't have worked for me since the subquery would have slowed things down too much)
