### ISSUE TITLE
Error when uploading file superior than 16MB

### ISSUE THREAD

**Issue by HZooly** [orientechnologies/orientdb#8465]
## Expected behavior  
File upload should be successful.

## Actual behavior  
Got an error about max chunk during file upload.
Error in Spring console : `Caused by: com.orientechnologies.common.io.OIOException: Impossible to write a chunk of length:35858399 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings`

It was working well with OrientDB 2.1.19, but not with 3.0.x now.

**Comment by markodjurovic** [comment]
Hi @HZooly 
NETWORK_BINARY_MAX_CONTENT_LENGTH default value is 16MB. It can be changed by setting java system property by name `network.binary.maxLength`.
It can be done by adding `-Dnetwork.binary.maxLength=65536` (this will extend it to 64MB e.g.) in startup script.
So for e.g. server.sh it can looks like

```
exec "$JAVA" $JAVA_OPTS \
    $ORIENTDB_OPTS_MEMORY \
    $JAVA_OPTS_SCRIPT \
    $ORIENTDB_SETTINGS \
    $DEBUG_OPTS \
    -Djava.util.logging.manager=com.orientechnologies.common.log.ShutdownLogManager \
    -Djava.util.logging.config.file="$ORIENTDB_LOG_CONF" \
    -Dorientdb.config.file="$CONFIG_FILE" \
    -Dorientdb.www.path="$ORIENTDB_WWW_PATH" \
    -Dorientdb.build.number="develop@r78560300dd72acf9e6a6b792f5704af1b2877e4a; 2018-09-21 08:14:35+0000" \
    -Dnetwork.binary.maxLength=65536 \
    -cp "$ORIENTDB_HOME/lib/orientdb-server-3.1.0-SNAPSHOT.jar:$ORIENTDB_HOME/lib/*:$ORIENTDB_HOME/plugins/*" \
    $ARGS com.orientechnologies.orient.server.OServerMain
```

or for windows startup script server.bat:

```
call %JAVA% -server %JAVA_OPTS% %MAXHEAP% %JAVA_OPTS_SCRIPT% %ORIENTDB_SETTINGS% %MAXDISKCACHE% -Djava.util.logging.manager=com.orientechnologies.common.log.ShutdownLogManager -Djava.util.logging.config.file="%LOG_FILE%" -Dnetwork.binary.maxLength=65536 -Dorientdb.config.file="%CONFIG_FILE%" -Dorientdb.www.path="%WWW_PATH%" -Dorientdb.build.number="develop@r78560300dd72acf9e6a6b792f5704af1b2877e4a; 2018-09-21 08:14:35+0000" -cp "%ORIENTDB_HOME%\lib\*;%ORIENTDB_HOME%\plugins\*" %CMD_LINE_ARGS% com.orientechnologies.orient.server.OServerMain
```

Please verify if this resolves your issue?
