### ISSUE TITLE
How to set LINKSET in transactions ?

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8468]
## Expected behavior  
Let's imagine situation here :

1. I need to create various Vertexes.
2. Then I need to create record in another table and I would like to set some links from previous operations into the field of LINKSET type.
e.g. :

```
begin;
LET aa = CREATE VERTEX TableA SET weekday = 0, active = true;
LET bb = CREATE VERTEX TableA SET weekday = 4, active = false;
LET cc = CREATE VERTEX TableB SET linkField = [$aa,$bb]
commit;
return $cc
```
The example is not working. It seems like it is not returning the values of variables.
How do I do this please ?

**Comment by petervavro** [comment]
Also I tried something like this :
```
begin;
LET aa = CREATE VERTEX TableA SET weekday = 0, active = true;
LET bb = CREATE VERTEX TableA SET weekday = 4, active = false;
LET ee = SELECT FROM [$aa,$bb]
LET cc = CREATE VERTEX TableB SET linkField = $ee
commit;
return $cc
```

This : SELECT FROM [$aa,$bb] does not work. How to get RIDs from variables ?

Thank you.

**Comment by luigidellaquila** [comment]
Hi @petervavro 

Please, try the following:

```

begin;
LET aa = CREATE VERTEX TableA SET weekday = 0, active = true;
LET bb = CREATE VERTEX TableA SET weekday = 4, active = false;
LET ee = list($aa) || list($bb);
LET cc = CREATE VERTEX TableB SET linkField = $ee;
commit;
return list($cc)
```

Thanks

Luigi

**Comment by petervavro** [comment]
Hi Luigi,

Thank you so so much for your help, and **Yes** it works perfectly. I am feeling ashamed that solution is that simple :) ... Could you please point me at a link in documentation where I can learn more about this ? Thank you

**Comment by luigidellaquila** [comment]
Hi @petervavro 

You can find some info here
https://orientdb.com/docs/3.0.x/sql/SQL-Syntax.html
and here
https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html

anyway, also your original query is supposed to work, so you can consider it a little bug

Thanks

Luigi

**Comment by petervavro** [comment]
Hi guys, why did you close this ? It looks like a bug , it does not work according to documentation , right ?

**Comment by luigidellaquila** [comment]
Hi @petervavro 

Actually the problem here is that CREATE VERTEX returns a result set, not a single record, so `[$aa,$bb]` is a list of collections, that is probably not what you want.

You have to use one of the following to make it work (that are definitely better than my previous suggestion):

```
begin;
LET aa = CREATE VERTEX V SET weekday = 0, active = true;
LET bb = CREATE VERTEX V SET weekday = 4, active = false;
LET cc = CREATE VERTEX V SET linkField = [$aa[0],$bb[0]];
commit;
return $cc
```

or

```
begin;
LET aa = CREATE VERTEX V SET weekday = 0, active = true;
LET bb = CREATE VERTEX V SET weekday = 4, active = false;
LET cc = CREATE VERTEX V SET linkField = $aa || $bb;
commit;
return $cc
```

Could you please point me the docs that report wrong info? Probably they are outdated and require a little fix

Thanks

Luigi
