### ISSUE TITLE
Python client for OrientDB 3.x

### ISSUE THREAD

**Issue by Froskekongen** [orientechnologies/orientdb#8470]
pyorient does not work with OrientDB 3.x

Are there plans to either update pyorient to support version 3.x or release another python client that supports version 3.x?

**Comment by OrientDBColin** [comment]
Hi @Froskekongen.  I've published several suggested work arounds in the Pyorient issues and have asked the author to update the driver to make it work with OrientDB 3.x.

I'll likely just update the code myself this week so you can use the Pyorient driver.

**Comment by Froskekongen** [comment]
@OrientDBColin: That's great! Is there a place to follow progress on this?

**Comment by wave-DmP** [comment]
I second this request!

**Comment by TariqAHassan** [comment]
@OrientDBColin 

Hi. 

Any update on this?

**Comment by benjaminturnbull** [comment]
Hi @OrientDBColin, I was just wondering if there is update on this? 
I'm looking to port a project to OrientDB and this is the only blocker.

**Comment by cegprakash** [comment]
I suggest you guys to try out Orient DB REST. It's the simplest way when
you scale to distributed DB when you have millions of nodes you don't have
to change any line of your backend code

**Comment by benjaminturnbull** [comment]
Do you mean writing a REST-based interface, or is there another library I've missed with my Google-fu? My backup plan is to use requests or similar, but figured that someone had wrapped REST into Python already. The code I have to move is Python-based already, so that's non-negotiable.

**Comment by benjaminturnbull** [comment]
Ah, I get what you mean. I was just hoping someone had wrapped the commands I need into an API. I guess I was hoping someone had done the lifting for me.

**Comment by cegprakash** [comment]
I had created a custom OGM in my Django project for Orient DB REST L.

I can give you tips to build one.

Create empty python classes named Node and Relationship. Extend your model
classes from there. (You don't have to specify the data type while creating
the models. Just use var)

Now write a separate code to create the vertices and edges using the sub
classes of Node and Relationship. You just have to use the class name here.
You don't need the properties at this point. This will migrate your DB.

Similarly for building queries, you can create helper functions which
returns the request json, from the class and a dictionary as parameters.
Here you can make use of the properties in a class and the dictionary to
create the json.

**Comment by aniketgambhire** [comment]
Build pyorient from source they had made some configuration file changes. Due to this you will able to connect python and orientdb successfully.
