### ISSUE TITLE
How to query after a FULLTEXT indexing?

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8475]
## Expected behavior  
Use the power of full text indexing

## Actual behavior  
I tried to run `Select * from User where email LIKE "%xyz%"` from orient studio.  I get the results regardless I create the index or not. 

## Steps to reproduce  

Create a model using pyorient and create a full text index on a String field

```
class User(Node):
    email = String(unique=True)
    password = String()

graph.create_all(Node.registry)
client.command('CREATE INDEX emailIndex ON User(email) FULLTEXT')
```
Run this in the console
`Select * from User where email LIKE "%xyz%"`

**Comment by markodjurovic** [comment]
Hi @cegprakash ,

To use lucene indexes with leading wildcard, index should be created with appropriate option: 
`create index User.email on User(email) FULLTEXT ENGINE LUCENE metadata {"allowLeadingWildcard": true}`

To query against such created index:
`SELECT FROM User WHERE SEARCH_CLASS('*xyz*') = true`

Notice: Lucene indexes with allowed leading wildcards querying are performance inferior compared to regular lucene indexes.
