### ISSUE TITLE
Upgrade from V2.2.26 to V3.0.6.

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/orientdb#8479]
We are trying to upgrade the DBs from V2.2.26 to V3.0.6.

We followed the following steps:

- Backup and download dev DB from Studio
- Stop OrientDB
- Rename orientdb folder to orientdb_2_2_26 (in the case we need to revert everything later)
- Install V3.0.6 at the same level as the old version
- Rename the new folder to orientdb so that the service start, browser URL and so on work accordingly.
- Navigate to orientdb/bin, run ./server.sh and type a new password for root
- In Studio, create the dev DB
- Sort "dev" DB security by adding a new "dev" user and removing root from the users list
- Upload the backup file to the server
- At the server, start console
- In console, connect to the dev db via plocal
- Run the import command - It seemed line everything went well
- We then updated the password in the application and let our CI (Bamboo) run the tests and deploy the code - now it failed.

30 tests failed.
Most of the errros say
OrientDB.RequestError Class 'UNDEFINED' was not found in database 'our_db_name' DB name="our_db_name"

Do you think we might have a problem with the import? Do we need to do something special?
Can it be a problem in OrienJS?

Where is that UNDEFINED coming from? We have simple strings used as name of the classes.

Thanks

**Comment by igasparetto** [comment]
You can close this ticket.
There are many small things that we are fixing and I will send various tickets over.
Thanks

**Comment by luigidellaquila** [comment]
Ok, closing then, thanks!

Luigi
