### ISSUE TITLE
Accessing node siblings (rightmost/leftmost cousin node) in trees stored in orientdb.

### ISSUE THREAD

**Issue by karlitos** [orientechnologies/orientdb#8480]
### OS: MacOS

Hello,

I search for an possibility to store and more importantly, manage trees - Directed, acyclic, graphs - and __orientdb__ seems to be very promising solution. It is Important to me to have an (instant) access to nodes __next__ siblings.

e.g.

```
    A
  /   \
 B     C
/  \  / \
D  E F  G
```
I would like to efficiently access F directly from E. The access among the direct siblings (D, E / F, G) can be done via 'ordered edges' .

I was thinking about two solutions:

1. _custom edges_ connecting two siblings, positioned next to each other which dies not have an direct common ancestor (E -cousin- G). But considering scenarios, where whole sub-trees could be repositioned just by changing the an edge between two nodes ... the complexity of re-establishing those "cousin links" would be probably huge.

2. efficient computing. Was already discussed [here](rightmost/leftmost cousin node in a d3 tree). Basically: efficient computing is possible, as long as the nodes depth (distance from root) is known.

Is there a way in which every node automatically tracks its' distance to the "root" ? What will be the most effective way of doing this ? Running _shortestPath_ between the Root and a given node and considering only outgoing edges _has_parent_

**Comment by luigidellaquila** [comment]
Hi @karlitos 

in the hypothesis that the edges are connected bottom-up, eg. `D --> B --> A`, you can calculate the depth as follows:

```
SELECT max($depth) as theNodeDepth FROM (
  TRAVERSE out("EdgeClassName") FROM (
    SELECT FROM VertexClass WHERE name = 'D'
  )
)
```

Then you can use that value to find siblings:

```
SELECT FROM (
  TRAVERSE in("EdgeClassName") FROM <the root>
) 
LET $theSiblingsDepth = (<the query for the max depth>)
WHERE $depth = $theSiblingsDepth[0].theNodeDepth
```

I didn't try the query, so there is a slight chance that it has some small syntax errors, but in principle it should work fine

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @karlitos 

The TRAVERSE is an efficient operation, actually the efficiency depends on how many vertices/edges you traverse, not on the traversal depth

**Comment by karlitos** [comment]
Many thanks, I will close the ticket for now.
