### ISSUE TITLE
`DROP PROPERTY` statement do not remove field values from DB

### ISSUE THREAD

**Issue by sbespalov** [orientechnologies/orientdb#8482]
### OrientDB Version: 
3.0.0

### Java Version:
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

### OS: Ubuntu 
16.04

## Expected behavior  
`DROP PROPERTY` statement should remove data(property/field values) from DB

## Actual behavior  
`DROP PROPERTY` statement do not remove data(property/field values) from DB

## Steps to reproduce  
```
CREATE CLASS Foo;
CREATE PROPERTY Foo.name STRING;
INSERT INTO Foo (name) VALUES ('foo name one');
DROP PROPERTY Foo.name;
SELECT * FROM Foo;
```

Select will return record with `Foo.name` property value
```

#165:0 | 1 | Foo | foo name one

```

**Comment by luigidellaquila** [comment]
Hi @sbespalov 

That's on purpose, see the docs: https://orientdb.com/docs/3.0.x/sql/SQL-Drop-Property.html

You can delete the property values as follows:

```
UPDATE YourClass REMOVE thePropertyName
```

Thanks

Luigi
