### ISSUE TITLE
Inverse links not working in OrientDB distributed mode

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#8486]
## Expected behavior  
1. Run OrientDB in distributed mode
2. Create inverse link 
3. Documents links on each other

## Actual behavior  
Inverse links not created

## Steps to reproduce  
1. Create class `A` with property `link1` which has a type `LINK`
2. Create class `B` with property `link2` which has a type `LINK`. Link to class `A`
3. Make property `A.link1` link to class `B`
4. Make properties inverse
5. Create document of class `B`
6. Create document of class `A` which field `link1` links to document from point 5
7. After point 6 document of class `B` must links to document of class `A` from point 6, but it doesn't.

Thanks,
Vitaliy

**Comment by luigidellaquila** [comment]
Hi @WeaxMe 

Could you please post a code snippet to reproduce the problem? I'm not sure I got what you mean exactly...

Thanks

Luigi

**Comment by WeaxMe** [comment]
Sorry, I take a mistake. Inverse properties is Orienteer specific thing. This is our problem. I already fixed it.

Thanks, 
Vitaliy
