### ISSUE TITLE
OrientDB parser rejects Lucene search with character-range in regexp

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8487]
## Expected behavior  
should be possible to search a Lucene index with some regular-expresion which specifies a range of characters:
```
SELECT * FROM myclass WHERE [indexedField] LUCENE ' indexedField:8001038[0-9] '
```

## Actual behavior  
OrientDB parser rejects this, with
```
Cannot parse ' indexedField:8001038[0-9] ': Encountered " "]" "] "" at line 1, column 90.
Was expecting one of:
    "TO" ...
    <RANGE_QUOTED> ...
    <RANGE_GOOP> ...
```

**Comment by rdelangh** [comment]
hi Luigi,

no, that syntax is not valid either, it is apparently only accepted for dates:
```
SELECT * FROM myclass WHERE [indexedField] LUCENE ' indexedField:8001038[0 TO 9] '
Caused by: com.orientechnologies.orient.core.sql.parser.ParseException: Cannot parse ' indexedField:8001038[0 TO 9] ': Input is not a valid date string: 0

```

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I tried it on a basic case and it seemed to work fine, can you please share some more context about your schema?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @rdelangh 

I did a couple of tests as follows:

First of all I created the schema
```
CREATE CLASS Foo;
CREATE PROPERTY Foo.name STRING;
CREATE INDEX Foo.name on Foo (name) FULLTEXT ENGINE LUCENE;
INSERT INTO Foo SET name = '8001';
INSERT INTO Foo SET name = '8002';
INSERT INTO Foo SET name = '8008';
```

then I tried a query silimar to your original one:

```
SELECT * FROM Foo WHERE [name] LUCENE 'name:800[0 TO 4]'
```

It parses correctly, but it returns no results (it must be the wrong way to do it probably, but I have to dig a bit into Lucene syntax to be sure).

Then I tried the following:

```
SELECT * FROM Foo WHERE [name] LUCENE 'name:[8000 TO 8004]'
```
and it returns two records, as expected.

I also tried the query with the wildcard, and it throws a parsing exception (Lucene throws it), so it does not seem to be a valid Lucene syntax

```
SELECT * FROM Foo WHERE [name] LUCENE 'name:800[0 TO 4]*'
```

I hope it helps

Thanks

Luigi
