### ISSUE TITLE
Index not work on query execution (using UI)

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#8491]
## Expected behavior  
Let lastEventTime a double field on Account Vertex.

**select count(*) as INACTIVE from `Account` where lastEventTime < 1534837606994**
give me the correct value without UI warning

## Actual behavior  
the query give me the correct value (**91421**) but takes too much time. The UI give me a warning suggesting me to use an existing index (that is already used)

![image](https://user-images.githubusercontent.com/3224592/44711188-10577a80-aaae-11e8-95a2-a888674d3c1a.png)

- lastEventTime is always not null.
- lastEventTime has FULLTEXT Lucene index 

![image](https://user-images.githubusercontent.com/3224592/44711410-9a074800-aaae-11e8-8ae2-4c6c43fc8344.png)

## Steps to reproduce  
Just Create some Vertices with double field and use the where contition on it.

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

Lucene indexes do not support range queries, you should use a tree index instead

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Thanks.

So LUCENE index is not recommended for numeric fields?

**Comment by luigidellaquila** [comment]
Lucene index is mainly designed for full text indexing. 
For numbers it's much better to use normal tree indexes, especially when you have to perform range queries

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Thanks a lot.

thank you for your clarity and availability

**Comment by luigidellaquila** [comment]
No problem ;-)
