### ISSUE TITLE
Posting an edge document using REST

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8493]
## Expected behavior  
I want to create a REST query similar to [Vertex creation](https://orientdb.com/docs/2.1.x/OrientDB-REST.html#post---document)  to create an Edge

## Actual behavior  
No documentation to specify invertex and outvertex

## Steps to reproduce  
No documentation on how to create a POST call for an edge using REST

**I do not want Raw queries** because raw queries are hard to maintain in a big code base.

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

Currently there is no such API to create edges, I'm afraid you will have to fall back to SQL

Thanks

Luigi

**Comment by cegprakash** [comment]
Can you reopen this as a feature request?

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

Sure, but it will hardly be implemented in v 2.2.x.
There is a chance that it will be in v 3.1, but I cannot guarantee it

Thanks

Luigi
