### ISSUE TITLE
Question  - embedded server - query HA STATUS using Java API

### ISSUE THREAD

**Issue by ygyg70** [orientechnologies/orientdb#8501]
## Expected behavior  
Be able to use the Java API to query cluster HA STATUS when running in embedded mode:
https://orientdb.com/docs/2.2.x/SQL-HA-Status.html  

## Actual behavior  
Could not  find in documentation.
When executing as a query get the following exception:
com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot execute non idempotent command

## Steps to reproduce  
This is a question

**Comment by markodjurovic** [comment]
Should be something like:

`OCommandSQL command = new OCommandSQL("HA STATUS -servers -servers");
ODatabaseRecordThreadLocal.instance().get().getStorage().command(command);`

**Comment by ygyg70** [comment]
Thanks! Tried and it works
(except the thread local returned null so I used this instead:
server.getSystemDatabase().openSystemDatabase().getStorage().command(command);
