### ISSUE TITLE
2nd Edge creation always fails, Atomicity does not work in such cases - Bulk query

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8503]
## Expected behavior  
The first two operations should get rollback if the 3rd query fails for batch transactions (coz it follows ACID according to the documentation)

## Actual behavior  
First and second queries did not get rollbacked even when the 3rd query returned 400

## Steps to reproduce  

I use this python code to do batch request.
```
def orientdb_post_batch(data):
    data.update({'transaction': True})

    url = "http://{}:{}/batch/{}".format(settings.ORIENT_DB_CONFIG['url'], "2480", settings.ORIENT_DB_CONFIG['database'])

    request = requests.post(url,
                            data=json.dumps(data),
                            auth=basic_auth)
    return request.json()
```

data looks like this
```
     "operations": [
                {
                    'type': 'c',
                    'record': params
                },

                {
                    "type": "cmd",
                    "language": "sql",
                    "command": "CREATE EDGE about FROM " + "(SELECT FROM Video where id='{}')".format(
                        params['id']) + " TO " + "(SELECT FROM Skills WHERE id = '{}')".format(data["category"]["id"])+" RETRY 5"
                },

                {
                    "type": "cmd",
                    "language": "sql",
                    "command": "CREATE EDGE has FROM " +"(SELECT FROM Users WHERE id = '{}')".format(user_id)+" TO " +"(SELECT FROM Video where id='{}')".format(
                        params['id'])+ "RETRY 5"
                },

            ]
```

Response json looks like this:

`{'errors': [{'reason': 400, 'code': 400, 'content': 'Class \'has\' was not found\r\n\tDB name="my_db"'}]}`

**Bug 1** : The first two operations executed successfully and did not get rolled back
**Bug 2**: Why did the edge creation fail in the first place? The edge schema is optional always whenever I create one edge. It should be the same case when I create two edges in a bulk query. ( I even tried swapping my edge creation queries. But the 2nd edge creation always fails)

**Comment by smolinari** [comment]
Are you sure you don't already have the `about` class already created and the `has` class isn't? Because, normally, as I understand ODB, in order to add edges to an edge class, you must define it first. 

`CREATE CLASS has EXTENDS E`

Why the first commands worked and didn't get rolled back, I have no idea. 

Scott

**Comment by cegprakash** [comment]
Yes I'm sure about that smolinari. I did remove all my edges from the schema to make sure of that. class creation is not compulsory for first edge. But it is for second edge.

**Comment by smolinari** [comment]
> class creation is not compulsory for first edge. But it is for second edge.

Are you sure about this? I highly doubt this is true.

> I did remove all my edges from the schema to make sure of that. 

You mean, you removed all edge classes from the database? 

Scott

**Comment by cegprakash** [comment]
I did Unsafe DROP command on all vertices and edges!
