### ISSUE TITLE
Alias doesn't work when used in outE / inE

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/orientdb#8505]
## Expected behavior  
select outE('AliasName') should return a value

## Actual behavior  
select outE('AliasName') doesn't return a value
select outE('ClassName') returns a value

It works in V2. We are migrating to V3 and we noticed this issue.

**Comment by luigidellaquila** [comment]
Hi @igasparetto 

I just pushed a fix for this problem, it will be released with v 3.0.7

Thanks

Luigi

**Comment by igasparetto** [comment]
Awesome!
Thanks
