### ISSUE TITLE
Can't set LINK field from select query in EMBEDDED

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8510]
## Expected behavior  
Has to insert a record into link field.  

## Actual behavior  
```com.orientechnologies.orient.core.exception.OValidationException: The field 'OStatus.author' has been declared as LINK but the value is not a record or a record-id DB name="nvd" Error Code="4"```

## Steps to reproduce  
```sql
CREATE CLASS TAuthors;
CREATE PROPERTY `TAuthors`.`code` STRING;

CREATE CLASS OStatus;
CREATE PROPERTY `OStatus`.`author` LINK `TAuthors`;
ALTER PROPERTY `OStatus`.`author` linkedClass "TAuthors";

CREATE CLASS TData;
CREATE PROPERTY `TData`.`status` EMBEDDEDLIST  `OStatus`;
ALTER PROPERTY `TData`.`status` linkedClass "OStatus";

update TData set status = [{
  "author": (select @rid from TAuthors where code = "123")
}]; #doesn't work

update TData set status = [{
  "author": "#1:1"
}]; #works fine
```

**Comment by luigidellaquila** [comment]
Hi @freeart 

The problem here is that the result of the subquery is a collection (not a single element). I think it's reasonable for OrientDB to do an automatic conversion when it's possible, I'm checking to see if I can easily fix it

Thanks

Luigi

**Comment by freeart** [comment]
Ok, thanks. I wrote about embedded type because for a simple class field as LINK this syntax works. A collection casts to a single element

**Comment by luigidellaquila** [comment]
Hi @freeart 

I pushed a fix for this today, but you have to change the query as follows (`SELECT FROM` instead of `SELECT @rid FROM`, otherwise the projection is not considered a valid record:

```
update TData set status = [{
  "author": (select from TAuthors where code = "123")
}]; 
```

Thanks

Luigi
