### ISSUE TITLE
[Question] Indexing list of/just embedded maps

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#8512]
### OrientDB Version: 3.0

Hi,

Unless im mistaken, there should be now a way to index embedded maps in 3.0?

E.g.

```
"item": {
    "id": "a"
},
"items": [
    {
        "id": "a"
    },
   {
        "id": "b"
    }
]
```

How to create an index on `item.id` or `items.id` ? I've tried a conventional way which didnt work for me: 

`create index MyClass.items.id on MyClass (items.id) notunique`
`create index MyClass.item.id on MyClass (item.id) notunique`

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

I'm afraid it's not supported yet...

Thanks

Luigi

**Comment by andreyvk** [comment]
@luigidellaquila , any roadmap on this?

**Comment by andreyvk** [comment]
@luigidellaquila , another question please. When defining a complex index consisting of 2 or more attributes, are there any restrictions on in which order all the indexes should be created so that fetch plan behaves correctly? Thing is that we are still on 2.2. Today I found out that complex indexes start working correctly in 3.0 only when I drop old ones, add complex indexes and then add back old indexes again.
