### ISSUE TITLE
Parameters binding 3.0.6 vs 3.1.0-develop returns different result

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8513]
## Expected behavior  
In 3.0.6 works fine with or w/o binding, but in **develop** branch returns wrong result (just duplicates) 

## Actual behavior  
<add here>  

## Steps to reproduce  
I'm using HTTP API in both cases at ```POST http://${host}:${port}/command/${db}/sql/25``` with ```body```to bind parameters

```sql
SELECT EXPAND($result) 
LET 
    $0 = (select @rid from `DDiagnose` where code = "A00"), 
    $1 = (select @rid from `DDiagnoseType` where code = "8"), 
    $2 = (select @rid from `DDiagnose` where code = "A01"), 
    $3 = (select @rid from `DDiagnoseType` where code = "2"), 
$result = UNIONALL($0,$1,$2,$3)
```  
returns **right** result
```#27:49```
```#29:3```
```#27:47```
```#29:2```
```sql
SELECT EXPAND($result) 
LET 
    $0 = (select @rid from `DDiagnose` where code = ?), 
    $1 = (select @rid from `DDiagnoseType` where code = ?), 
    $2 = (select @rid from `DDiagnose` where code = ?), 
    $3 = (select @rid from `DDiagnoseType` where code = ?), 
$result = UNIONALL($0,$1,$2,$3)
```
```json
{ parameters: ["A00", "8", "A01", "2"] }
```
returns **wrong** result

```#27:49```
```#29:3```
```#27:49``` &#x1F534;
```#29:3``` &#x1F534;

**Comment by luigidellaquila** [comment]
Hi @freeart 

Thank you very much for reporting, I'm checking it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @freeart 

I just pushed a fix to develop branch

Thanks!

Luigi
