### ISSUE TITLE
can Document be used as vetex?

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#8522]
## Expected behavior  
define domain object that can be used as document or Vertex, but no way to extend Vertex

**Comment by grimace** [comment]
In that case, it is not an ODocument,  does that matter, I'm still not sure.  I am writing Pojos with domain classes ( jar file ).  How do I extend 'V'?   I can't say
`public class DObject extends OVertex`  
because OVertex is an interface

I am coming at this from Mongo and like the idea of MultiModel but not sure if I use 

`ODocument`

and then Have my object contain a Vertex.  or if these are all fully integrated and I can have an
object be both a Document and a Vertex.

Does that make sense?

**Comment by grimace** [comment]
Also,
I have made classes (POJO) and added to database, but they show up as Generic classes and ( at that point ) I can not make them into graph elements.   As well, they do not show up on the graph screen.

If I then edit the Schema in the studio and make them extend `V`.  
`ALTER CLASS  MYClass SUPERCLASS +V`    
then they show up in the graph and I can add edges to them, but they are no longer Documents?

So, really, my question is:  What is the best practice?
Do I use documents to store detail data and then in the cases where I want connections ( graphs ). I connect those documents up to the graph side via embedded Vertexes?
Or do I use Vertexes and when I want detail data hooked up to those, I add links(?) to documents?
Or can a Vertex be used as a document when I want to add more data?
Also, can I perform that `ALTER`  command programmatically (  and is this a good idea )?

**Comment by luigidellaquila** [comment]
Hi @grimace 

I guess you are using OrientDB v 3.0 with the Java API.
You can just create the schema as follows:

```
db.createVertexClass("YourClassName");
```

and then create vertices:

```
OVertex v = db.newVertex("YourClassName");
v.save();
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Just to make it clear, a vertex (and an edge as well), is still a document, so you can use it the same way

Thanks

Luigi

**Comment by grimace** [comment]
so when do I use:
`            odb.newElement()
`
?

**Comment by grimace** [comment]
and also, when do I use?:
`odb.getEntityManager().registerEntityClasses("com.mycompany.domain.model");
`

because, when I do this, I can't seem to use those Classes as a Vertex.
I apologize for so many questions.  Just trying to get my head around this.

**Comment by luigidellaquila** [comment]
Hi @grimace 

`newElement()` is to create normal documents (you can also have documents that are not vertices).
`registerEntityClasses()` has to be invoked when you start the application

Thanks

Luigi
