### ISSUE TITLE
traverse * | out -> difference results regarding sorting

### ISSUE THREAD

**Issue by sharper89** [orientechnologies/orientdb#8533]
### OrientDB Version: <2.2.33>  

Hello,
i have found that there are differences in traversing the sorting of the results.

Query : "traverse * from RID"
Result: Vertex,Edge,Vertex, Edge, Vertex, Edge ....

If I now want to limit the result with _bothE_ and _out_, the result is no longer sorted and different for each query.

Query : "traverse bothE(), out('EStructurePhase'), out('EPhaseTag'), out('ETag'),in('EContributionPhase'), in('EContributionTag')  from RID"
Result: Vertex,Vertex,Vertex, Edge, Edge, Edge
Another Result: Edge,Edge,Vertex, Edge, Vertex, Vertex

How do I have to change the query to structure the result as above?
Thanks

**Comment by luigidellaquila** [comment]
Hi @sharper89 

By default the traversal strategy is DEPTH FIRST, so if you do `traverse *` you will always have an edge and then a vertex; on the other hand, if you mix out(), in() and bothE(), the sequence depends a lot on your graph structure, ie. out() and in() only return vertices, while bothE() only returns edges, and they will be evaluated in the order they appear in the query.

I hope it helps

Thanks

Luigi

**Comment by sharper89** [comment]
Hi Luigi,

thanks for your answer.
Your explanation is understandable but I need the same order as above. The reason is that I have written functions that put me a tree(parent-child) from the set of results. This function is fast because I need no further query to database except the traverse. This only works if the sorting is from top (first vertex) to bottom(last vertex). The result of the second query is still the same, but unfortunately not anymore sorted. If I look at both queries in the graph, the result is the same.
![structure_orient_db](https://user-images.githubusercontent.com/26001485/45535986-68a5b080-b800-11e8-84e3-ef6b0e6669d3.png)

Thanks

**Comment by luigidellaquila** [comment]
Hi @sharper89 

The problem in your query is only that `outE()`, that returns an edge but not the corresponding vertex (that will be returned later based on other traversals, probably), so the question is: why do you need edges but not the connected vertices? Is it really what you need?

Thanks

Luigi

**Comment by sharper89** [comment]
Hi Luigi,

i found a solution for me. This query returns a sorted result:

traverse outE('EStructurePhase'), inV('Phase'), inE('EContributionPhase'), outE('EPhaseTag'), outE('ETag'), inE('EContributionTag') from RID

Thanks
