### ISSUE TITLE
Update vertex does not return it - opposite as create

### ISSUE THREAD

**Issue by s-krawczyk** [orientechnologies/orientdb#8534]
## Expected behavior  
Update vertex should return it.

## Actual behavior  
Vertex is not returned

## Steps to reproduce  
Executing below query does not work:
begin;
LET $v1 = 'v1';
LET $v2 = 'v2';
LET $c = update Item SET Guid = $v1 UPSERT WHERE Guid = $v1; // here is $c when used in Create edge fails. If I change to create than it works
LET $a = select FROM Item WHERE Guid = $v1;
update Item SET Guid = $v2 UPSERT WHERE Guid = $v2;
LET $b = select FROM Item WHERe Guid = $v2;
Create edge PreviousItem UPSERT FROM $c TO $b; // when $c changed to $a it will work
commit;

**Comment by luigidellaquila** [comment]
Hi @s-krawczyk 

You can explicitly force the UPDATE statement to return the updated records, using `RETURN AFTER` syntax, see https://orientdb.com/docs/3.0.x/sql/SQL-Update.html

```
 update Item SET Guid = $v1 UPSERT RETURN AFTER WHERE Guid = $v
```

I hope it helps

Thanks

Luigi

**Comment by s-krawczyk** [comment]
Works! Thank you!

Pozdrawiam SK

pt., 14 wrz 2018, 07:55 użytkownik luigidellaquila <notifications@github.com>
napisał:
