### ISSUE TITLE
How to enforce unique constraint on a vertex parameter? - OrientDB REST

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8551]
### OrientDB Version: 2.2.36

There is no [documentation](https://orientdb.com/docs/2.2.x/OrientDB-REST.html) to enforce a unique constraint on a vertex parameter.

I tried 

`create class test UNIQUE ('id') extends V`

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

You can do it with an index:

```
CREATE CLASS Test EXTENDS V;
CREATE PROPERTY Test.id STRING;
CREATE INDEX Test.id on Test (it) UNIQUE;
```

I hope it helps

Thanks

Luigi
