### ISSUE TITLE
Updating standardElementConstraints throws JSONDecodeError - OrientDB REST

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8552]
## Expected behavior  
The script should run like a charm!

## Actual behavior  
The command `ALTER DATABASE CUSTOM standardElementConstraints=false` works perfectly on orient studio. But when I want to run the same using orientDB REST, I get JSONDecodeError

## Steps to reproduce  
I tried
```
"operations": [
        {
            'type': 'script',
            'language': 'sql',
            'script': ['ALTER DATABASE CUSTOM standardElementConstraints=false']
        }
    ]

```
I also tried to execute with type 'cmd'. But I get the same error

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

That is not valid json, you have to wrap it in curly braces:

```
{
   "operations": [
        {
            'type': 'script',
            'language': 'sql',
            'script': ['ALTER DATABASE CUSTOM standardElementConstraints=false']
        }
    ]
}
```

Thanks

Luigi

**Comment by cegprakash** [comment]
You just have to replace the single quotes to double quotes to make it a valid Json. I just copy pasted it from my python dictionary. Sorry about that. I eventually convert this to a Json before sending it to the orientDB.

**Comment by cegprakash** [comment]
Please reopen this. I pass the above given dictionary to this function in python.

```
def orientdb_post_batch(data, is_transaction = True):
    data.update({'transaction': is_transaction})

    url = "http://{}:{}/batch/{}".format(DB_CONFIG['url'], DB_CONFIG['port'], DB_CONFIG['database'])

    request = requests.post(url,
                            data=json.dumps(data),
                            auth=basic_auth)
    response = request.json()
    if "errors" in response:
        raise OrientDBException({"message": response['errors'][0]['content']})
    return response

```

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

I'm not a python guy, I'm not sure what's wrong here...
Anyway, I just tried it from Postman vs OrientDB v 2.2.37 and it seems to work fine... See the snapshot attached

<img width="864" alt="schermata 2018-09-24 alle 17 05 25" src="https://user-images.githubusercontent.com/459289/45960296-37a55700-c01c-11e8-8dee-d43b9106ab2c.png">

**Comment by cegprakash** [comment]
Hi the problem was in this line. `response = request.json()` For some reason json conversion was not working out for 204 response code

I replaced it with a hack for now.

```
 if request.status_code == 204:
        response = {}
    else:
        response = request.json()
```

You can close this issue now.
