### ISSUE TITLE
INSERT INTO Subquery Returns Empty Array

### ISSUE THREAD

**Issue by big213** [orientechnologies/orientdb#8555]
## Expected behavior  
`INSERT INTO` subquery returns the rid of the created record

## Actual behavior  
Appears to return `[]` instead.

## Steps to reproduce  
`CREATE VERTEX V SET foo = (INSERT INTO V SET bar = '1')`
`SELECT foo FROM #9:0`

**Comment by luigidellaquila** [comment]
Hi @big213 

I'm working on it, I'll let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @big213 

I just pushed a fix, it will be released with v 3.0.8

Thanks

Luigi
