### ISSUE TITLE
ODatabaseDocumentTx.command(OCommandRequest) seems to do nothing

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#8556]
### OS: Windows  

When I execute a command on a ODatabaseDocumentTx I don't get the expected result.

[This method](https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java#L742) implementation seems incorrect to me.
Shouldn't it execute the command as it is done in the query method only a few lines down?

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

That method is there since 2014, untouched, and is perhaps the most used API on OrientDB... 
Why do you think it's incorrect? What do you mean when you say that you don't get the expected result? Perhaps you just forgot to do an `.execute()` (I still forget it sometimes ;-) )

Thanks

Luigi

**Comment by diegomtassis** [comment]
Hi @luigidellaquila 

The [javadoc of the method (inherited from the interface)](https://github.com/orientechnologies/orientdb/blob/e8b4ff74132593cf84b85174d37c2c186e9def7b/core/src/main/java/com/orientechnologies/orient/core/db/ODatabase.java#L799) says:

```
  /**
   * Execute a command against the database. A command can be a SQL statement or a Procedure. If the OStorage used is remote
   * (OStorageRemote) then the command will be executed remotely and the result returned back to the calling client.
   *
   * @param iCommand Command request to execute.
   *
   * @return The same Command request received as parameter.
   */
```
I assumed the method to be analogue to ODatabaseDocumentTx.query(OQuery<?>, Object...), the only difference to be this one not returning a result value.

If it does not execute the command, then what is the responsibility of that method?

**Comment by luigidellaquila** [comment]
Ok, it makes sense, I'd say the javadoc can be changed to be more explicit on how to use the method. I'm chenging it now

Thanks

Luigi
