### ISSUE TITLE
in and out are swapped in 2nd level edges?

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8557]
### OrientDB Version: 2.2.36  

Vertices : User, Skill
Connecting edge : has_skill

Now I'm trying to fetch all the skills of all the users in this format
user1, [{'id' : 1, 'name' : 'dancing'}, {'id' : 2, 'name' : 'singing'}]

```
SELECT first_name, out_has_skill.in.include('id','name')  FROM User
```
After many trial and errors the above query gave the result that I expected. The problem is that  

> out_has_skill.in

 works but 

> out_has_skill.out

 does not. The edge is going out to skill but I get the results only if I use in. If I use out, I get user's data instead of skill. Also there is no documentation for queries like this. But I had to figure it out myself. Any chance these queries might be depreciated because it's not in documentation?

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

This is exactly how it's expected to work. It is standard convention for graph traversal, also in Gremlin (see https://github.com/tinkerpop/gremlin/wiki/basic-graph-traversals).

In general, you should avoid to use `out_*`/`in_*` attributes directly, you should use `out(), outE(), outV()` ecc methods instead. Anyway, the convention is exactly the same: `out()` is equivalent to `outE().inV()`

Thanks

Luigi
