### ISSUE TITLE
use jdbc connect orientdb,  why 'select *'  can result in reconnect timeout and 'select id'  is normal

### ISSUE THREAD

**Issue by pettyandydog** [orientechnologies/orientdb#8558]
## Actual behavior  
    use jdbc connect orient by java8, error sql:
   `select
         *,
         $path as path,
         $depth as depth
        from
        (
        TRAVERSE both()
        FROM
        (select from Person where emp_name='andy')
        WHILE $depth <=3
        )`

above sql will occur reconnect timeout， replace ‘select *’ to ‘select id’，this sql can normal execute，this is bug？ or i donot knowledge sql useful 

## Steps to reproduce  
<add here>

**Comment by markodjurovic** [comment]
Hi @pettyandydog 
can you reproduce it on `demodb`, demo database shipped with OrientDB binaries?
