### ISSUE TITLE
Fluent calls on OElement

### ISSUE THREAD

**Issue by mjoa** [orientechnologies/orientdb#8564]
## ~~Expected~~ Wished behavior  
Making the OElement interface support fluent calls.
```
session.newElement("MyElement")
    .setProperty("prop1", "val1")
    .setProperty("prop2", "val2")
    .save();
```
Nothing critical but would provide a more consistent feeling on the api. Creating an element from a JSON string takes the fluent approach from underlying ORecord interface.
```
session.newElement("MyElement")
    .fromJSON(json)
    .save();
```
Setting the property values directly doesn't allow fluent calls on OElement
```
OElement e = session.newElement("MyElement");
e.setProperty("prop1", "val1");
e.setProperty("prop2", "val2");
e.save();
```

**Comment by mmacfadden** [comment]
@mjoa I assume that you didn't intend each line in your example terminated with a `;`?
