### ISSUE TITLE
error upgrading from 2.X to 3.X: java.lang.UnsupportedOperationException: Cannot convert

### ISSUE THREAD

**Issue by adepase** [orientechnologies/orientdb#8565]
### Java Version: java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
## Expected behavior  
Until (at least) version 2.2.23
Directly from Studio->Browse, execute the following query:
```
select from (
   select list(son) as son, list(parent) as parent from (
      SELECT EXPAND( $c ) 
         LET $a = ( select null as son, @rid as parent from synset where lemmas lucene 'evento' and lang='it'), 
              $b = ( select @rid as son, null as parent from synset where lemmas lucene 'matrimonio' and lang='it' and verified is null ), 
              $c = UNIONALL( $a, $b )
     )
) unwind son, parent
```
Result:
```
parent | son
-- | --
#20:4496 | #17:6119
#19:961 | #17:6119
#20:4496 | #19:6118
....
```
## Actual behavior  
exactly same query, from Studio->Browse (db exported and imported, apparently without any issue):
Error:
java.lang.UnsupportedOperationException: Cannot convert {Synset_lemmas_totalHits=5, a=[{ son: null parent: #17:25795 } , { son: null parent: #20:39457 } ], current={ } , b=[{ son: #17:1520 parent: null } , { son: #20:14296 parent: null } , { son: #19:27075 parent: null } , { son: #17:841 parent: null } , { son: #20:39859 parent: null } ], totalHits=5} - class com.orientechnologies.orient.core.command.OBasicCommandContext to JSON

## Steps to reproduce  
See above. 

I cannot find any upgrade instruction about changes in the sql that could be impacted in the above query.
Please, help, I cannot upgrade in these conditions

**Comment by luigidellaquila** [comment]
Hi @adepase 

Thank you for reporting, I'm checking it.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
HI @adepase 

I don't seem to be able to reproduce the problem, any chance to have a DB to reproduce it?

Thanks

Luigi

**Comment by adepase** [comment]
[mrjReduced.gz](https://github.com/orientechnologies/orientdb/files/2435726/mrjReduced.gz)

Hi @luigidellaquila 
sure, I can send you a very reduced db, with the same issue: try the uploaded export, changing the  query to:
```
select from (
   select list(son) as son, list(parent) as parent from (
      SELECT EXPAND( $c ) 
         LET $a = ( select null as son, @rid as parent from synset where lemmas lucene 'animale' and lang='it'), 
              $b = ( select @rid as son, null as parent from synset where lemmas lucene 'gatto' and lang='it' and verified is null ), 
              $c = UNIONALL( $a, $b )
     )
) unwind son, parent
```

Same error.

Thank you
Alessandro
P.S.: looking at your nickname, if you're italian, I'm italian, let me know if you prefer speaking italian

**Comment by luigidellaquila** [comment]
Hi @adepase 

Thank you very much, I'm checking it.
Yes, I'm Italian, but please let's keep writing in English, the issues remain as a general referenece for the community

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @adepase 

I just pushed a fix, it will be released with v 3.0.9

Thanks

Luigi

**Comment by adepase** [comment]
Thank you, I'm waiting for it :)

**Comment by adepase** [comment]
I just read the release notes for v 3.0.9 and I cannot find this issue in the list: is this correct in that version or not? If not, when will it be the release version and date? 
Thank you
Alessandro

**Comment by luigidellaquila** [comment]
Hi @adepase 

Sorry, my fault, I forgot to flag the issue for the release, I'm updating the release notes now.
And yes, the fix is in the release

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Done

**Comment by adepase** [comment]
Thank you, I'll try it immediately

**Comment by adepase** [comment]
Well, not exactly immediately, but it works. ;-)
