### ISSUE TITLE
Occational failure : Low heap memory when using EXPAND, UNIONALL

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8578]
### OrientDB Version: 2.2.36

 Cannot execute query "SELECT EXPAND(UNIONALL((SELECT * FROM A), (SELECT * FROM B), (SELECT * FROM C), (SELECT * FROM D), (SELECT * FROM E), (SELECT * FROM F), (SELECT * FROM G), (SELECT * FROM H), (SELECT * FROM I), (SELECT * FROM J), (SELECT * FROM K), (SELECT * FROM L), (SELECT * FROM M), (SELECT * FROM N), (SELECT * FROM O)))": low heap memory

All my tables have a very small data (to populate the dropdown menus in a web page). But I get low heap memory error at times. What can I do to avoid it?

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

unionall() is a memory intensive operation in general. Moreover, in v 2.2 the result set is kept in memory before being sent to the client, so if it's big you will need enough heap to contain it.

My advice in general is to switch to v 3.0 that has streamed result sets (but still, unionAll() keeps results in memory, so the best option is to restructure your query)

Thanks

Luigi

**Comment by cegprakash** [comment]
Any suggestions to restructure my query?

**Comment by luigidellaquila** [comment]
What do you need exactly? iterate the whole DB?

**Comment by cegprakash** [comment]
I need to iterate 15 classes wholly

**Comment by luigidellaquila** [comment]
In v 2.2 the only thing I can suggest is to do multiple queries and use pagination (ie. SKIP/LIMIT) to avoid memory overload.
In v 3.0, you can easily iterate on huge classes, but there is no straight forward way to do a query on multiple classes, so you can do multiple queries or just create superclass for all these classes and do a query on it

Thanks

Luigi

**Comment by cegprakash** [comment]
I'll try the 2nd option and update here if the issue persists
