### ISSUE TITLE
EXPLAIN no return  'server execution time for query' in 3.0.8 ( like 'elapsed' metric in OrientDB 2.x)

### ISSUE THREAD

**Issue by misu200** [orientechnologies/orientdb#8579]
OrientDB Version: 3.0.8

The query execution time in OrientDB Studio(or console.sh w/remote mode) seems to be computed locally in browser and will roughly be 'server execution time for query' + 'network latency' (RTT)

Many times when working from my personal laptop against cloud hosted OrientDB instance means having network latency for hundreds milliseconds....and for a long time I thought OrientDB is really slow.

EXPLAIN doesn t return the 'elapsed' metric like in OrientDB 2.x

Is there any way to get the 'server execution time for query' in OrientDB?

Thanks

**Comment by luigidellaquila** [comment]
Hi @misu200 

In v 3.0, EXPLAIN does not execute the query, so it cannot compute the execution time.
Probably we can add some additional info to the JSON response of the normal query execution, let me check, I'll give you a feedback soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
hi @misu200 

I added a new attribute to the HTTP response for quesies: `elapsedMs`. It contains the actual execution time in milliseconds.
I pushed this change to 3.0.x branch, so it will be released with v 3.0.9.
For now, Studio still shows the old "complete" execution time (including the network round trip), but in the near future we will also change it to use the actual execution time. For now you can find the real value in the "raw" tab

Thanks

Luigi

**Comment by misu200** [comment]
Thanks a lot @luigidellaquila . 
Now one can easily test&optimize OrientDB queries more easy without worrying about network round trip.
