### ISSUE TITLE
Abnormal Index behavior : ORecordDuplicatedException 

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8580]
### OrientDB Version: 2.2.37

I have created an index using ```CREATE INDEX my_edge.id on my_edge (id) UNIQUE```

When I create an edge (**in a batch query**), I get
```'com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #108:2: found duplicated key \\'5752128403059799\\' in index \\'my_edge.id\\' previously assigned to the record #109:0\\r\\n\\tDB name="my_db" INDEX=my_edge.id RID=#109:0'}```

I am sure that the id does not exist in the database.

I have verified it by doing ```select * from my_edge``` and none of them have 5752128403059799 as their id.

Also trying this URL in browser ```xyz:2480/studio/index.html#/database/my_db/browse/edit/109:0``` throws 404

The query throws the same error for any ID.

Once I did ```DROP INDEX my_edge.id```, it starts working fine

This abnormal behavior exists for only few of the edge classes and I'm unable to find the reason yet. This behavior happens only during the batch query. When I run the query directly, it runs fine.

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

How can we reproduce the problem?

Thanks

Luigi

**Comment by cegprakash** [comment]
My bad. I'm creating multiple edges in a single query with same id. You can close this for now.

I'm using ```"CREATE EDGE my_edge FROM $v1 TO (SELECT FROM C where id in {0}) set id ='{1}', created_at=date('{2}'), updated_at=date('{3}')".format(list_of_ids, get_random_id(), time_now(), time_now())```
