### ISSUE TITLE
Potential Breaking Change in Database Pool Aquire Method in 3.X Logic

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#8581]
### OS: Linux  

I am not 100% sure if this is a bug or not.

In 2.x I believe that if  acquire() multiple times on a database pool with the same thread, the pool would return the same database instance.  In 3.x this seems to not be the case:

```
OrientDB odb = new OrientDB("memory", OrientDBConfig.defaultConfig())
odb.create("test", ODatabaseType.MEMORY)
  
ODatabasePool pool = new ODatabasePool(odb, "test", "admin", "admin")
  
ODatabaseSession db1 = pool.acquire()
ODatabaseSession db2 = pool.acquire()

if (db1 != db2) {
  System.out.println("not the same")
}
```

This will print "not the same".

In 2.x we had a lot of code the looked like this:

```
class Foo {
  private ODatabasePool pool;

  public void methodA() {
    ODatabaseDocument db = pool.aquire();

    // Command 1
    db.command(...);
    
    this.methodB();

    // Command 2
   db.command(...);
  }

  public void methodB() {
    ODatabaseDocument db = pool.aquire();
    db.command(...);
  }
```

In 2.x everything worked well, as the same db instance was returned in `methodA` and `methodB` when calling methodA() since it was all executed in the same thread.  In 3.0.8, we are getting the "database not active on the current thread" exception when executing Command 2 in `methodA`. This is because the call to `pool.acquire()` in `methodB` returns a new database and sets that database as active on the current thread. Therefore the db in `methodA` is no longer the active db on the current thread for Command 2.

First, is my analysis correct? Second, if so, was this an intentional change in the way the pool works, or is this a bug?

**Comment by mmacfadden** [comment]
@tglman @luigidellaquila Is there any more information you need from me on this one?  I could try to create a gist or something that is ready to run to show the inconsistency.

Or if you need me to debug a bit through the OrientDB code to see what might have changed, I could do that too.

Let me know if I can help since this is a blocker for us. Thanks for your assistance always.

**Comment by tglman** [comment]
Hi @mmacfadden,

Yes the new pool do not return the same instance in case of nested calls, this is a design choice the old design was creating some hard to fix issues, you can reproduce the nesting easily using a thread local in your application.

Regards

**Comment by mmacfadden** [comment]
@tglman Thanks for the clarification. I can update my code to handle the new design. It might be worth noting this change in the documentation for upgrading from 2.x to 3.x. This was causing some hard to figure out problems in our application code which assumed the old behaviors. It might be the same for other people. A short note in the upgrade section of the doc might save someone hours of debugging!

**Comment by mmacfadden** [comment]
Also this page here:

http://orientdb.com/docs/3.0.x/java/Transaction-propagation.html

Still says:


> Database  pool can be used, in such case all methods which asks for db connection in same thread will have the same the same database instance.
