### ISSUE TITLE
Advanced query help - 1 level hop using unwind and  exclude

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8584]
### OrientDB Version: 3.0.8

I have a User class which has multiple edges. 
Some of my edges are many to 1 and some of them are many to many (assuming edges go from User).

The following query fetches all the data I want but in a wrong fashion

```select first_name, edge_names, edges:{*} from (select first_name, outE().@class as edge_names, outE().inV() as edges from User where id = '7731344821679130') unwind edges```

The problem with this query is that
1) First name is duplicated for all the results
2) I want the data for each edge name in each row but I get all the edge names in each row duplicated for all the rows
3) I want to exclude some edges. For example I need to get all the 1 level hop with edge 'has_skill' but not 'following'

How do I fix this query in a way that I want? 

I want something like this
```
{
    "first_name" : "Prakash",
    "edges" : [
        edge_name : has_skill
        values : [
              {
              "name"  : "coding"
              },
              {
              "name"  : "running"
              }
        ]
    ]
}
```

**Comment by cegprakash** [comment]
hi I can't use outE("EdgeClassName") because I need all the edges except few edge classes. How can I achieve this?

Can you plz share an example of groupby and list together?

**Comment by luigidellaquila** [comment]
Hi @cegprakash 

You can do as follows: `outE()[@class <> "TheClassToExclude"]` 

Thanks

Luigi
