### ISSUE TITLE
Login to Studio always happens as "root"

### ISSUE THREAD

**Issue by rajgopalv** [orientechnologies/orientdb#8593]
## Expected behavior  
Login with userX should login as userX

## Actual behavior  
Logging in with ANY user in studio logs in as "root"

## Steps to reproduce  
http://recordit.co/sOZXYExNGX
I tried even clearing the site data using chrome developer tools.  > see attched image.. 
![image](https://user-images.githubusercontent.com/4376206/46759230-ab359e00-cc83-11e8-8595-d63e8ea1fe8e.png)

But this doesn't happen with incognito window..  O.o

**Comment by mmacfadden** [comment]
Does this happen all the time? For what it is worth, I tried to reproduce the error in Chrome on a Mac and could not get it to exhibit the same behavior.

**Comment by wolf4ood** [comment]
I was not able to reproduce it as well with Chrome and Mac.

**Comment by rajgopalv** [comment]
I upgraded to 3.0.9, and i'm not seeing it anymore. I'll keep an eye on this bug

**Comment by wolf4ood** [comment]
Thanks @rajgopalv 

let me know if it pops again
