### ISSUE TITLE
Add support for ELSE and ELSEIF (or ELSE IF) for SQL Batch Conditional Execution

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientdb#8597]
It would be very useful and a logical extension of the IF() SQL Batch Conditional construct to have support for ELSE and ELSEIF (or ELSE IF). Adding support for a SWITCH/CASE construct would also be worth considering.

**Comment by luigidellaquila** [comment]
Hi @Eric24 

IF/ELSE is already in the roadmap, I'm flagging this as an enhancement

Thanks

Luigi
