### ISSUE TITLE
In and Contains Problem

### ISSUE THREAD

**Issue by ttamatt** [orientechnologies/orientdb#8598]
### OS: Centos 6.8

When I used 'IN' keyword in 2.x version,  if A IN B while A and B have same values, for example A =[a,b,c]  B=[c], using  A IN B can successfully get returned value, seems it got the intersection of A and B sets.  But in 3.0.8, this situation doesn't return anything, while 'CONTAINS' keyword still only can be used when B is a subset of A, which means in 3.0.8, there is no way to get the intersection of two collection.

I don't know if I has got the point of 'IN' and 'CONTAINS', please give some hints.

Thanks,
Matt

**Comment by luigidellaquila** [comment]
Hi @ttamatt 

Using IN with multiple meanings, also as a CONTAINS or as an intersection, was not a bit misleading. Personally, I always considered it a bug.
In v 3.0 you have specific operators:

- A IN B: all the elements in A are contained in B
- A CONTAINS B: all the elements in B are contained in A
- A CONTAINSANY B: the intersection is not empty

 I hope it helps

Thanks

Luigi

**Comment by ttamatt** [comment]
It works well with  CONTAINSANY ,thanks a lot! 
But I just got a new problem with  'CONTAINS' with  map values situation.

Such as:
>select  *  from A where \`list\` CONTAINS  (\`name\`=' Jack');

And there is a record of A whose 'list' property is :
>[{"name":"Jack"}] 

But it returns nothing now.

**Comment by ttamatt** [comment]
Also I just found when  I used  CONTAINSANY, with STRING type works well, but with INT type, it failed.
For example:
>\`name\`  CONTAINSANY ["Jack","Rose"]
It works

>\`int\` CONTAINSANY [20,21]
It failed,returns nothing,

And values of both \`name\` and  \`int\`  are a single value , such as "Jack" and 20, not a collection.
Strangely, when I create a index of \`int\`, it works well.

**Comment by luigidellaquila** [comment]
Hi @ttamatt 

Could you please provide a script to reproduce the problem? I'll check it asap

Thanks

Luigi
