### ISSUE TITLE
CONTAINSANY problem 

### ISSUE THREAD

**Issue by ttamatt** [orientechnologies/orientdb#8603]
## Create test class
```
create class test
create property test.a string
create property test.b integer
```

## Create a record
```
insert into test (a,b) values ("Jack",10)
```

## Failed sql
```
select * from test where `a` CONTAINSANY ["Jack","abc"]
```
returned nothing

Strangely,if I create a index of a.
```
create INDEX test.a UNIQUE
```
sql will show the record.

And you've said  CONTAINSANY is used for intersection, so I wonder if STRING and ARRAY OF STRING such as "a" and ["a","b"] can return a intersection?

**Comment by luigidellaquila** [comment]
Hi @ttamatt 

I'd say the fact that it works with the index is just a side effect of some internal mechanism, if there is a bug to fix is that it should fail.

For this use case you have to use IN instead:

```
select * from test where `a` IN ["Jack","abc"]
```

Thanks

Luigi
