### ISSUE TITLE
CONTAINS(EMBEDDED LIST) problem

### ISSUE THREAD

**Issue by ttamatt** [orientechnologies/orientdb#8604]
## Create class test  with property dict
| Name |     Type     | Linked_Type |
|:----:|:------------:|-------------|
| dict | EMBEDDEDLIST | EMBEDDEDMAP |

## Create a record of test
```
insert into test (dict) values ("name":"Jack")
```

## Failed sql
```
select * from `test` where `dict` CONTAINS(`name` = "Jack")
```
returned nothing, but in 2.x, It showed results.

Thanks,
Matt

**Comment by luigidellaquila** [comment]
Hi @ttamatt 

I just pushed a fix for this problem, it will be released with v 3.0.10

Thanks

Luigi
