### ISSUE TITLE
LET usage issue with LUCENE index

### ISSUE THREAD

**Issue by misu200** [orientechnologies/orientdb#8605]
Almost a duplicate for #8572 ( the only difference is replacing the Hash index with a Lucene index in test )

OrientDB Version: 3.0.9
Java Version: java version "1.8.0_171"
OS: Windows 10 Home

I ve created the following simple database test:

```
create class A extends V;	
create property A.name  string;
create index A.nameLucene ON A (name) FULLTEXT ENGINE LUCENE;

create class B extends V;
create class X extends E;							
	  
let $a = create vertex A set name="Mike";
let $b = create vertex B;
create edge X from $a to $b;
```
The following query returns the expected non-empty result:
`select $t,$t.size(),* from A let $t=(select * from (select expand($parent.$parent.$current.out()))) where [name] LUCENE '(name:(+("Mike")))'`
Add " and $t.size()>0" at the end and the query will return empty although $t.size() is 1 in our case:

`select $t,$t.size(),* from A let $t=(select * from (select expand($parent.$parent.$current.out()))) where [name] LUCENE '(name:(+("Mike")))' AND $t.size()>0`

If i drop the index A.nameLucene the above query returns the expected non-empty result.

Thanks,
Mihai

**Comment by luigidellaquila** [comment]
Hi @misu200 

Thank you for reporting, I just pushed a fix for this problem, it will be released with v 3.0.10

Thanks

Luigi
