### ISSUE TITLE
CREATE EDGE EXCEPTION 

### ISSUE THREAD

**Issue by ttamatt** [orientechnologies/orientdb#8606]
### OS: Centos 6.8

 Create Edge Document:
<img width="913" alt="screen shot 2018-10-17 at 12 00 57 pm" src="https://user-images.githubusercontent.com/29082190/47061503-586c6100-d204-11e8-9412-b6671beb3778.png">

In 2.x the exception was successfully throwed, but in 3.0 it wasn't, when Creating Edge is failed, it will just returned nothing so that transaction can't rollback, please help me find reason.

Thanks,
Matt

**Comment by lightjiao** [comment]
Any response of this issue? @luigidellaquila

**Comment by luigidellaquila** [comment]
Hi guys,

In v 3.0 the behavior of CREATE EDGE is a bit different, ie. it just does not create any edges if the out/in vertices do not exist. 
This is more consistent with the normal SQL behavior, eg. if you run an UPDATE based on a condition that returns no records, it just does not update anything (it doesn't throw any exception, why should it...?)

The rationale of rolling back a tx when a vertex does not exist is not only an uncommon use case, but also the opposite of what you expect in general. The CREATE EDGE can be used with subqueries for the out and the in vertices, these subqueries can return zero, one or many results, this depends only on your application/data logic. 

My advice is to review your scripts, check the results of the statements and, in case, manually do a ROLLBACK

Thanks

Luigi
