### ISSUE TITLE
Import database with -merge=true but classes still removed

### ISSUE THREAD

**Issue by jymcheong** [orientechnologies/orientdb#8611]
## Expected behavior  
import database with -merge=true should not delete existing classes 

## Actual behavior  
![](https://www.dropbox.com/s/d4px6b9x8q3uffp/Screenshot%202018-10-18%2021.49.57.png?raw=1)

## Steps to reproduce  

1. Create a "test" database
2. Create a "MyV" vertex
3. Create a dummy function
4. Export only functions as per https://orientdb.com/docs/2.1.x/Console-Command-Export.html
5. Import functions.gz

**Comment by markodjurovic** [comment]
Hi @jymcheong 
thank you for reporting this one. Fix will be in release 3.0.10, or you can build it from 3.0.x branch right now.
