### ISSUE TITLE
Multiple bugs with date methods

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#8618]
## datetime.asDate() is applicable only for strings and longs
It's pretty natural to expect that asDate() also applicable to `datetime` to extract particular date

## datetime.asLong().asDate() doesn't return date - but rather timestamp
Per description it's expected to see date, rather date with time

## datetime.asString().asDate() doesn't work at all
It's common sense to expect that after serialization to string and then back to date at least it should be the same timestamp as previously. And it should not depends on default date/time format. But in reality this chain return nothing.

**Comment by PhantomYdn** [comment]
It would be useful to have something like this:

```java
public class OSQLMethodDateToString extends OAbstractSQLMethod {

	public static final String NAME = "dateFormat";

	public OSQLMethodDateToString() {
		super(NAME, 0, 1);
	}

	@Override
	public String getSyntax() {
		return "dateFormat(<date format>)";
	}

	@Override
	public Object execute(Object iThis, OIdentifiable iCurrentRecord, OCommandContext iContext, Object ioResult,
			Object[] iParams) {
		if (iThis == null)
			return null;
		else if (!(iThis instanceof Date))
			throw new OCommandSQLParsingException("Method '" + getSyntax() + "' can be invoked only on Date instances");
		else {
			DateFormat dateFormat;
			if (iParams == null || iParams.length == 0 || iParams[0] == null) {
				dateFormat = ODatabaseRecordThreadLocal.instance().get().getStorage().getConfiguration()
						.getDateFormatInstance();
			} else {
				dateFormat = new SimpleDateFormat(iParams[0].toString());
			}
			return dateFormat.format((Date) iThis);
		}
	}
}
```

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

Thank you for reporting, I'll look at this asap.

Luigi

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I'm pushing a fix to make toDate() work on datetime objects.
It will be released with v 3.0.10 and I'll backport it to 2.2.x

`datetime.asLong().asDate()` works fine in v 3.0, that means that probably the problem in v 2.2 is deeper than just the function itself, I'll see if I can fix it, but I cannot give you an ETA now

For the third point, asString() is just intended to provide a human readable representation. If you need a proper format, you can do the following: `date.format("yyyy:MM:dd")` 

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I also backported the fix to v 2.2.x

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Oh, I didn't notice that, let me check again

Thanks

Luigi

**Comment by luigidellaquila** [comment]
ok, fixed.

Thanks!

Luigi
