### ISSUE TITLE
IN keyword issue in Orient 3.0.8

### ISSUE THREAD

**Issue by milankyada** [orientechnologies/orientdb#8619]
## Expected behavior  
Query should return same result as returning in OrientDB 2.2.35 but it is returning empty resultset

## Actual behavior  
**select from Company where outE('is_a')[type="Tenant"].inV()['@rid'] in [#28:9,#28:8,#28:7] limit 5** 
This query is working fine with OrientDB 2.2.35 but the same query is not returning same result with OrientDB 3.0.8

## Steps to reproduce  
```
CREATE CLASS Company EXTENDS V
CREATE PROPERTY Company.name string
Insert into Company(name) values("webix pvt. ltd."),("diversity pvt. ltd.")

CREATE CLASS Tenant EXTENDS V
CREATE PROPERTY Tenant.name string
Insert into Tenant(name) values("DotNet"),("pdev")

CREATE CLASS is_a EXTENDS E
CREATE EDGE is_a FROM #18:0 TO #22:0
CREATE EDGE is_a FROM #18:0 TO #23:0
CREATE EDGE is_a FROM #19:0 TO #22:0
CREATE EDGE is_a FROM #19:0 TO #23:0

select from Company where outE('is_a')[type="Tenant"].inV()["@rid"] in [#22:0,#23:0] 
```

**Comment by luigidellaquila** [comment]
Hi @milankyada 

Thank you for reporting, I'd say it's a bug, I'll check it asap and let you know

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @milankyada 

I just pushed a fix for the problem with square bracket selection

Thanks

Luigi

**Comment by milankyada** [comment]
Thank you @luigidellaquila 
I'll be waiting for next release.
