### ISSUE TITLE
traversedVertex(0) function throws java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Y0ba** [orientechnologies/orientdb#8624]
## Expected behavior  
No exception

## Actual behavior  
`java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1`

Exception thrown here:

https://github.com/orientechnologies/orientdb/blob/6296c890a07960ee7002ceb417e1cdf8c6c2f1f9/core/src/main/java/com/orientechnologies/orient/core/sql/functions/coll/OSQLFunctionTraversedElement.java#L131-L132

Seems like `x` should be initialized to `listStack.size() - 1`.

**Comment by luigidellaquila** [comment]
Hi @Y0ba 

I'm pushing the fix right now, it will be released with v 3.0.10

Thanks

Luigi
