### ISSUE TITLE
Batch sql scripts still do not work with console

### ISSUE THREAD

**Issue by mbhulin** [orientechnologies/orientdb#8627]
## Expected behavior (using version 2.2.27) 
orientdb {db=demodb}\> load script "C:/mh/tmp/demodbSqlScriptTest.txt"

Loading script C:/mh/tmp/demodbSqlScriptTest.txt...[Started multi-line command. Type just 'end' to finish and execute]

orientdb {db=demodb}\> script sql begin; let v1 = create vertex V set Name = "Source", Id = 1; let v2 = create vertex V set Name = "Destination", Id = 2; create edge E from $v1 to $v2; commit;

+----+-----+------+----+-----+
|#   |@RID |@CLASS|out |in   |
+----+-----+------+----+-----+
|0   |#13:0|E     |#9:0|#10:0|
+----+-----+------+----+-----+
Server side script executed in 0,203000 sec(s). Returned 1 records
orientdb {db=demodb}\>  

## Actual behavior with 3.0.8
<orientdb {db=demodb}\> load script C:\mh\tmp\demodbSqlScriptTest.txt

Loading script C:\mh\tmp\demodbSqlScriptTest.txt...[Started multi-line command. Type just 'end' to finish and execute]

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:

^
Encountered " <BEGIN> "begin "" at line 1, column 1.
Was expecting one of:
    \<WHILE\> ...
    \<IF\> ...
    \<FOREACH\> ...
    ";" ...

DB name="demodb"
Error Code="1"

Loaded script C:\mh\tmp\demodbSqlScriptTest.txt
orientdb {db=demodb}\>  

## Steps to reproduce  
Content of sql script file:
`script sql;`
`begin;`
`let v1 = create vertex V set Name = "Source", Id = 1;`
`let v2 = create vertex V set Name = "Destination", Id = 2;`
`create edge E from $v1 to $v2;`
`commit;`
`end;`

**Comment by luigidellaquila** [comment]
Hi @mbhulin 

I just pushed a fix that solves this problem. It will be released with v 3.0.11

Thanks

Luigi
