### ISSUE TITLE
Missing session or token

### ISSUE THREAD

**Issue by soujiro32167** [orientechnologies/orientdb#8628]
### OS: 
- Alpine Linux in Docker: https://github.com/orientechnologies/orientdb-docker/blob/3d7d8070e903149126c7d691afa3be5f2de58742/3.0-tp3/x86_64/alpine/Dockerfile

- Running on Google Cloud Kubernetes 1.9.7 (Container Optimized OS)

Using https://github.com/orientechnologies/spark-orientdb, I write vertices and edges to the graph using Spark. Occasionally, at the **edge writing step** I get an exception while writing:

`missing session and token` (stacktrace TBD)

## Expected behavior  
No connection error

**Comment by tglman** [comment]
Hi @soujiro32167,

Did you try the latest hotfix (currently 3.0.10)? we fixed similar issues already.

Regards

**Comment by soujiro32167** [comment]
@tglman will try, thanks for the quick reply!

**Comment by soujiro32167** [comment]
So far so good! I haven't  seen the error since upgrading =]

**Comment by CanonTino** [comment]
I'm using 3.0.10 version and I'm having the same problem. Do you know if there's some work around in order to avoid these  exception?
