### ISSUE TITLE
Return only records which contains links (in LINKSET) to records with certain values.

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8629]
## The situation :

Let say I have a table `TheClassA` which contains only column `linkedRecords`, type LINKSET. 
This field contains links to records from `TheClassB`. 
`TheClassB` has two columns `columnOne` and `columnTwo`.

## Issue :

I need to get records from `TheClassA` where field `linkedRecords` contains links to records with certain values, let's say `columnOne='foo'` and also `columnTwo=2`.

How can I do this please ? How should the query looks like please. Thank you !

**Comment by mmacfadden** [comment]
@petervavro This is fairly straight forward to do in OrientDB. You can use the CONTAINS filter. Here is an example. This will select all records from TheClassA where the record has a link to TheClassB in its LINKSET where at least one value in the LINKSET has a TheClassB record with the values you mentioned.

```SQL
SELECT FROM TheClassA WHERE linkedRecords CONTAINS (columnOne="foo" AND columnTwo=2);
```
More info can be found here [http://orientdb.com/docs/3.0.x/sql/SQL-Where.html](http://orientdb.com/docs/3.0.x/sql/SQL-Where.html)

**Comment by mmacfadden** [comment]
@petervavro Was this able to solve your issue?

**Comment by mmacfadden** [comment]
@petervavro if there is no update, can we assume we can close this issue?
