### ISSUE TITLE
Suggestions on SQL REMOVE syntax and multiple-item support

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientdb#8633]
A suggestion: It's possible to remove a single item from a list using:
`UPDATE Account REMOVE addresses = addresses[1]`

Add support to allow removing a range of items at once:
`UPDATE Account REMOVE addresses = addresses[1,4]`

Although, I suggest that this syntax be changed anyway, to this:
`UPDATE Account REMOVE addresses[1]`
`UPDATE Account REMOVE addresses[1,4]`

And add support for negative values, meaning "from the end". So to remove the last item from the list:
`UPDATE Account REMOVE addresses[-1]`

**Comment by luigidellaquila** [comment]
Hi @Eric24 

Thank you very much, we will take these suggestions into consideration. In the meantime, you can try the following (v 3.0 and following):

```
UPDATE Account SET addresses = addresses[0] || addresses[4 .. addresses.size()]
```

I hope it helps

Thanks

Luigi

**Comment by Eric24** [comment]
I'll try that on 3.0, but wouldn't address.size() be one more than the last item index?

I've also tried various approaches to removing the "last" item in a list under 2.2.x (including .size(), eval(), and others), but nothing has worked. Any idea on how to remove the last item under 2.2.x without knowing in advance what it's index is?

_By the way, the main reason we have not upgraded to 3.x yet is because of the orientjs driver. As soon as it's out of beta for 3.x, we'll move to 3.x._
