### ISSUE TITLE
Index hints for SQL commands?

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientdb#8643]
### OS: Amazon

I know that the 3.x query optimizer is supposed to be much better (waiting on orientjs 3.0 release), but currently, and even with 3.x, a common feature of may databases is to allow "hints" in the query that tell the optimizer which index to use. I have a case right now that could use this (where a Lucene full-text index would be preferred, but the 2.2.29 optimizer still chooses a different SB-TREE index, resulting in an unnecessary read of several thousand records). Perhaps the 3.0 optimizer can make this decision on its own, although in my experience with other databases, there will be edge cases where it won't make the right decision.

**Comment by luigidellaquila** [comment]
Hi @Eric24 

This is something we are considering. I'm flagging it as an ehancement, hopefully it will be implemented soon

Thanks

Luigi
