### ISSUE TITLE
object API registerClasses causes large and rapid wal file growth

### ISSUE THREAD

**Issue by zerovian** [orientechnologies/orientdb#8648]
## Expected behavior  
When calling OEntityManager.registerEntityClass, the .wal file should grow a reasonable amount.   Instead due to large number of registered classes, the disk IO is nearly 1GB simply to create a database.

## Actual behavior  
It is observed the more classes are registered, the growth of the .wal file increases rapidly for each new class that is registered.  In my application I register some 100 different classes during database creation, and .wal file writes to disk exceed 700MB.  When the database is finally closed after creation, the entire database is only about 40MB on disk.

Expectation is that creating a 40MB database from some 100 or so registered classes should not generate nearly >700MB of disk writes, virtually all of which are to the .wal files.

Below is screenshot showing file channel writes to disk over the course of about 1 minute ( slow due to profiler).

![image](https://user-images.githubusercontent.com/3799244/48152742-ae2baa80-e292-11e8-8f50-c9a5e193d83d.png)

Another pic from yourkit showing total writes to each file.  Note that the .wal file is configured for max of 256MB which each segment set to 32MB.   This doesn't seem to matter as having 1 large .wal file can still result in the same high IO

![image](https://user-images.githubusercontent.com/3799244/48152831-e501c080-e292-11e8-8203-7833c02eb07a.png)

Below is pic of final file size on disk which is < 40MB. 

![image](https://user-images.githubusercontent.com/3799244/48152779-c3a0d480-e292-11e8-9840-0daedef3e006.png)

## Steps to reproduce  
create a database
Using object manager use OEntityManager.registerClasses() and register some 100 java classes (in my case most classes have from 4 to 15 fields.  I can provide test .zip file if needed.
Using yourkit profile tracing mode, monitor the performance behavior of file channel writes and notice the extremely high amount of writes to disk.

**Comment by zerovian** [comment]
attached is .zip file with example test code.  If you run this in yourkit yo'll see the disk IO start small and increase the more classes there are, eventually the .wal file will end up at 70MB and yourkit shows almost 200MB of data written to disk with this test (this is cut down from the full set of classes we use).

[TestDiskIO.zip](https://github.com/orientechnologies/orientdb/files/2558900/TestDiskIO.zip)

**Comment by zerovian** [comment]
![image](https://user-images.githubusercontent.com/3799244/48156153-bee01e80-e29a-11e8-8756-d1c8af06306c.png)

image showing writes per second increasing significantly to nearly 20MB per second as more classes are added.

**Comment by zerovian** [comment]
Seems this isn't a problem in 3.0.10

![image](https://user-images.githubusercontent.com/3799244/48156652-d370e680-e29b-11e8-8da7-d8c6fd97f06d.png)

**Comment by laa** [comment]
Closed because fixed in 3.0.x
