### ISSUE TITLE
Can't create remote database in distributed mode

### ISSUE THREAD

**Issue by roksolana-d** [orientechnologies/orientdb#8651]
## Expected behavior  and ## Actual behavior  
I wanted to create the database with these configs:

`connect remote:localhost/Test root rootpassword`
Then after reloading this database distirbuted setup the data should replicate to all the nodes and the database should be available on all the nodes. 
When I run the database creation with this config I get an error:

```
Creating database [remote:localhost/Test] using the storage type [PLOCAL]...
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance
```

The database is not created. But when I try to create a local database, it is created:

`connect plocal:databases/Test admin admin`

Also, after reload the data seems to be replicated to other nodes in a cluster, however, I cannot connect to this database from other nodes:

```
connect plocal:databases/Test3 admin admin
Connecting to database [plocal:databases/Test3] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'Test3'
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'Test3' because it does not exist in path: /orientdb/databases/Test3
```
Also, there is such a message in the cluster logs:

```
+-----------------------+------+----------------------------+-----+---------+---------------+---------------+------------------------+
|Name                   |Status|Databases                   |Conns|StartedOn|Binary         |HTTP           |UsedMemory              |
+-----------------------+------+----------------------------+-----+---------+---------------+---------------+------------------------+
|node1541765068082(*)(@)|ONLINE|Test3=ONLINE (MASTER)       |0    |12:04:26 |172.17.0.7:2424|172.17.0.7:2480|224.70MB/1.93GB (11.35%)|
|node1541765085041      |ONLINE|Test3=NOT_AVAILABLE (MASTER)|4    |12:04:43 |172.17.0.9:2424|172.17.0.9:2480|217.87MB/1.93GB (11.01%)|
|node1541765072342      |ONLINE|Test3=NOT_AVAILABLE (MASTER)|4    |12:04:30 |172.17.0.8:2424|172.17.0.8:2480|217.88MB/1.93GB (11.01%)|
+-----------------------+------+----------------------------+-----+---------+---------------+---------------+------------------------+
```
What could be the reason of such behavior?

## Steps to reproduce  
1. Create and setup OrientDB cluster with Kubernetes
2. As soon as all the nodes up enter the console from one of the Kubernetes pods
3. Create the database with server credentials or db admin credentials
4. Check the creation status
5. Connect to the database from the same pod and then from all the others
6. Check the logs on the pod to see whether the database is available on the cluster nodes.

**Comment by saranrajj** [comment]
I tried creating something similar recently with 3.0.10 docker image with kubernetes & i was able to create the database via remote connection and the replication worked as expected. But the plocal type database replication did not happen, not sure if that is a limitation in the distribution mode.
