### ISSUE TITLE
Do you have an agent in China?

### ISSUE THREAD

**Issue by yhuiz** [orientechnologies/orientdb#8652]
## Expected behavior  
<add here>  
Do you have an agent in China?

## Actual behavior  
<add here>  
Do you have an agent in China?

## Steps to reproduce  
<add here>  
Do you have an agent in China?

**Comment by luigidellaquila** [comment]
Hi @yhuiz 

This issue tracker is for technical topics mainly. For commercial information please refer to the contacts here https://orientdb.com/contact-us/

Thanks

Luigi
