### ISSUE TITLE
CONTAINS(EMBEDDED LIST) problem 

### ISSUE THREAD

**Issue by ttamatt** [orientechnologies/orientdb#8654]
## Create class test  with property dict
| Name |     Type     | Linked_Type |
|:----:|:------------:|-------------|
| dict | EMBEDDEDLIST | EMBEDDEDMAP |

## Create a record of test
```
insert into test set dict=[{"name":"Jack"},{"age":"21"}]

```
##successful sql
```
select * from `test` where `dict` CONTAINS(`name` = "Jack")
```

## Failed sql
```
select * from `test` where `dict` CONTAINS(`age` = "21")
```
Only the first map returned values, please figure out the reason.

Thanks,
Matt

**Comment by luigidellaquila** [comment]
Hi @ttamatt 

I pushed a fix for this issue, it will be released with v 3.0.11

Thanks

Luigi
