### ISSUE TITLE
which distributed, sharding setup does work for 10TB dbase ?

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8656]
## Expected behavior  
A distributed, sharded database over 6 nodes, supporting a 10TB dbase with order of 40G records ('documents'). Queries should be distributed automatically to achieve highest performance, data storing should be spread over the 6 nodes in a redundant way (eg each cluster on 3 nodes, 6 clusters per class), the combined cluster should continue to perform when a node fails and should automatically recover when such node re-joins.

## Actual behavior  
Many, many issues are logged on this forum by people having problems getting distributed operation mode working in a stable way.

A class cannot have more then some 2-3G records, or the Java engine grounds to a halt with OOM situations; so we had to limit the number of records per class, and hence work with multiple classes, say N days worth of records in each class. However even by forcing each class to consist of 6 predefined clusters, not too many classes can be created or ODB runs out of max allowed number of clusters. We had to opt for 7 days worth of records per class, 6 clusters per class, storing 55 weeks of data, so 55x6=330 clusters. And this only for one type of class... Mind you that a typical database consists of multiple types of classes.

What is a recommended configuration for such 6 nodes to obtain a distributed, highly performant, automatically recovering cluster for very big databases ?

**Comment by arpitaagarwal** [comment]
I am using Orient 3.0.10 and facing same issue on concurrent write. I have created following setup -

2 node cluster
copied orientdb folder at 2 different locations and started ./dserver.sh file. Both nodes connected to each other through multicast
Using Person-FriendOf example code to write 10k Person-FriendOf-Person (vertex-edge-vertex). There are multiple threads writing same data each.
Person:name has unique index
It works well for 2 threads but as number of threads increases, it times out.
Getting following logs - Timeout (1244ms) on waiting for synchronous responses from nodes=[node2, node1] responsesSoFar=[node2] request=(id=1.105226 task=TxPhase1) [ODistributedDatabaseImpl]

Any clues?
