### ISSUE TITLE
Studio does not let me connect to an encrypted DB.

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8657]
## Expected behavior  
Ability to manage data of encrypted DB via Studio.

## Actual behavior  
Studio does not let me connect to the DB.

## Steps to reproduce  
I wish to make my database encrypted, so I am following [Database Encryption](https://orientdb.org/docs//3.0.x/security/Database-Encryption.html)

1. `sudo /Applications/orientdb-3.0.10/bin/console.sh`
2. `orientdb> CONFIG SET storage.encryptionKey MyEncryptionKey`
3. `orientdb> CREATE DATABASE plocal:/Applications/orientdb/databases/test-db admin admin plocal graph -encryption=aes`

Studio does not let me connect to the DB using submitted _user and password_ neither _root_. Reason : **Invalid username or password**

**Is this behaviour proper ? So encrypted DB can not be managed via Studio ?**

**Comment by SameerChorge94** [comment]
Getting same issue encrytpted databases not able to access via orientDB studio.
Also how to connect orientDB database from **orientjs**  package if it is not accessible using the studio also ?
