### ISSUE TITLE
thread state: waiting(parking)

### ISSUE THREAD

**Issue by yhuiz** [orientechnologies/orientdb#8659]
## Expected behavior  
<add here>  
read record's performance is good. And all read threads share data.

## Actual behavior  
<add here>  
![image](https://user-images.githubusercontent.com/15354480/48525516-68d53180-e8bf-11e8-827d-edd252e2966a.png)
## Steps to reproduce  
<add here>  
jstack JAVAPID > stack.txt
![image](https://user-images.githubusercontent.com/15354480/48525765-4db6f180-e8c0-11e8-9f3e-47e60843895c.png)
if entry.status do not include open,dead,retired, will lead to dead lock.

**Comment by arpitaagarwal** [comment]
I am using Orient 3.0.10 and facing same issue on concurrent write. I have created following setup -

2 node cluster
copied orientdb folder at 2 different locations and started ./dserver.sh file. Both nodes connected to each other through multicast
Using Person-FriendOf example code to write 10k Person-FriendOf-Person (vertex-edge-vertex). There are multiple threads writing same data each.
Person:name has unique index
It works well for 2 threads but as number of threads increases, it times out.
Getting following logs - Timeout (1244ms) on waiting for synchronous responses from nodes=[node2, node1] responsesSoFar=[node2] request=(id=1.105226 task=TxPhase1) [ODistributedDatabaseImpl]

Any clues?
