### ISSUE TITLE
Migration to 2.2 to 3.0: IndexManager does not give the indexes values

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#8660]
## Expected behavior  
Let indexName the existing Vertex index namea and let open a remote connection to OrientDB:
V2.2
OIndex<?> aIdx = **OrientBaseGraph**.getRawGraph().getMetadata().getIndexManager().getIndex(indexName); 
give me the correct OIndex.

V.3.0
OIndex<?> aIdx = ODatabaseSession getMetadata().getIndexManager().getIndex(indexName); 
give me the correct OIndex.

## Actual behavior  
V.3.0
OIndex<?> aIdx = **ODatabaseSession** getMetadata().getIndexManager().getIndex(indexName); 
give me null

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

Are you running in plocal or in remote?

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi Luigi,
I'm running in remote. 
The strange situation is that getIndexes() give me an empty result

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
I update the java client to 3.0.10 (server side I have v3.0.8) and now it seems working fine

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

Thanks for the update, it must have been a bug that is already fixed

I'm closing this ticket, please feel free to re-open if needed

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @gianluca-valentini 
I update the server version to 3.0.10 too but **OrientGraphNoTx** remote connection does not work.
It seems that it remains blocked...

So I have to use java client 3.0.10 but server 3.0.8...I think there is something wrong with these distributions

Gianluca

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

Can you please provide a sample project to reproduce the problem?

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila,
I just have kubernetes node with a OrientDB 3.0.10 POD. 
This pod coming from a Docker image (https://hub.docker.com/r/library/orientdb/tags/ TAG 3.0.10)

Using java client, I have a main class that use the lib coming from
```
<dependency>
  <groupId>com.orientechnologies</groupId>
  <artifactId>orientdb-core</artifactId>
  <version>3.0.10</version>
</dependency>
```
The line where I have the problem is

```
OrientBaseGraph graph = new OrientGraphNoTx("remote:" + host + ":" + port + "/" + dbName, "admin", "admin");
```

Using this code, with OrientDB server 3.0.10 I cannot have the graph instance...it seems locked on a synchronized operation or something similar.

While using OrientDB server 3.0.8 the same code works fine

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

I tried it locally, but I couldn't manage to reproduce the problem.
Please try to check the following:
- see if you are passing the right host/port
- check that both host and port have no additional spaces
- in case it still happens, try to take a thread dump of the client (eg. `jstack <pid>`), it could help us to get some more info

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
about the indexmanager issue now I have the same error with the v3.0.10 too.
The behavior is casual...sometimes it works and sometimes not, on the same Vertex, with the same java code!!

It is very strange and frustrating

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

About the server versions, I still didn't manage to reproduce the problem, if you have a chance to do a thread dump of the blocked client it will help a lot

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @gianluca-valentini 
I will try to give you what you need to be able to understand the issue. 
Currently I think that we will downgrade the OrientDB version because with the v3 we are founding too many problems.
We are trying to contact OrientDB support too (paying for any advice) without an answer. 
Any suggestion is welcome
Gianluca

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

Thank you very much, I'll see if I can find something in the meantime.

About the support, who are you contacting (eg. which email address)? Consider that today is Thanksgiving, so probably our sales dept in the USA is not very active

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
we contacted support and had a call on 06/11/2018. We talked with **Stacey Doshi** <sdoshi@calliduscloud.com> and **Matthew Lyman** <mlyman@calliduscloud.com>. After this call we sent a datailed document with our architecture and situation on 16/112018.
Currently we didn't have any answer about the cost and the time for the support. We are working on Rome and asked an italian language support asap.
On 20/11/2018 we sent another email to know the support situation
