### ISSUE TITLE
Batch FOREACH doesn't work at all

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8664]
### OS: docker openjdk:8-jdk-alpine

I understand FOREACH is in experimental state but simple example must work as in documentation 

## Steps to reproduce  
```sql
CREATE CLASS Test;
FOREACH ($i IN [1, 2, 3]){
  INSERT INTO Test SET value = $i;
}
```
Returns parsing error

**Comment by luigidellaquila** [comment]
Hi @freeart 

I just tested it and it seems to work fine.
Did you run it as a BATCH script? (FOREACH is not available as a single command)

Thanks

Luigi

**Comment by luigidellaquila** [comment]
See https://orientdb.com/docs/2.2.x/SQL-batch.html#http-rest-api

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Oh, and this https://orientdb.com/docs/2.2.x/OrientDB-REST.html#post---batch

**Comment by luigidellaquila** [comment]
(still valid for 3.x of course)

**Comment by freeart** [comment]
@luigidellaquila Cool! Thanks! I'll check

**Comment by luigidellaquila** [comment]
👍 
I'm closing this ticket, but please feel free to re-open if you need further help

Thanks

Luigi

**Comment by freeart** [comment]
@luigidellaquila Thanks! Cool!
