### ISSUE TITLE
INSERT with CONTENT synax error when using named params v3.0.x

### ISSUE THREAD

**Issue by myflowpl** [orientechnologies/orientdb#8666]
OrientDB Version: 3.0.10
Java Version: 1.8.0_111
OS: Ubuntu 18.04
OrientJS Version:  3.0.1 
and the same error with Java driver as mentioned here: orientechnologies/orientjs#346

### this works if you put json inline:
````typescript
session.command('INSERT INTO Log CONTENT {test: "inline json"}')
````
### and this not if you use named parameters:
```typescript
session.command( 'INSERT INTO Log CONTENT :log',  {
    params: {log: { test: 'json in params' }}
})
```

### it throws error:
````
OrientDB.RequestError: Error parsing query:
      INSERT INTO Log CONTENT ":log"
                            ^
      Encountered " <CONTENT> "CONTENT "" at line 1, column 17.
      Was expecting one of:
          <EOF> 
          <SELECT> ...
          <FROM> ...
          <RETURN> ...
          <UNSAFE> ...
          "(" ...
          ";" ...
          <CLUSTER> ...
          "(" ...
          
      	DB name="smdb_dev"
      	Error Code="1"
      at child.Object.<anonymous>.Operation.parseError (node_modules/orientjs/lib/client/network/protocol37/operation.js:1224:13)
      at child.Object.<anonymous>.Operation.consume (node_modules/orientjs/lib/client/network/protocol37/operation.js:566:35)
      at ONetworkConnection.Object.<anonymous>.Connection.process (node_modules/orientjs/lib/client/network/conn.js:460:17)
      at ONetworkConnection.Object.<anonymous>.Connection.handleSocketData (node_modules/orientjs/lib/client/network/conn.js:342:20)

````

It was working on 2.2 version
any ideas what i'm doing wrong ?

**Comment by luigidellaquila** [comment]
Hi @myflowpl 

OrientDB v 3.0 does not support parameters for INSERT CONTENT, but it should be an easy addition. I'll work on it asap and let you know

Thanks

Luigi

**Comment by myflowpl** [comment]
Thanks @luigidellaquila for quick answer.
This is very use full syntax, and if it's quick it will be really helpful to have it back.

Other way it should be added to the 3.0 migration guide as breaking change.
I check the migration guide before and couldn't find any info about it

waiting for your info

**Comment by luigidellaquila** [comment]
Hi @myflowpl 

I think this particular this just fell through the cracks (we can consider it a regression)

Thanks

Luigi
