### ISSUE TITLE
MATCHES function doesn't work with special chars

### ISSUE THREAD

**Issue by mpomet** [orientechnologies/orientdb#8670]
## Expected behavior  
MATCHES works if the field contains special char

## Actual behavior  
MATCHES function doesn't work if the field contains special char

## Steps to reproduce  
```sql
CREATE VERTEX item SET content = 'some text ...  uniquetexthere';
SELECT FROM item WHERE content MATCHES '(.*)uniquetexthere(.*)'
```

The SELECT statement above doesn't returns any result.
Do I miss something or is it a bug ?

**Comment by luigidellaquila** [comment]
Hi @mpomet 

I tested it in v 3.0 and it seems to work fine, so I'd say it could be a problem in the old SQL layer.
I'll check it as soon as I can

Thanks

Luigi

**Comment by mpomet** [comment]
@luigidellaquila Did you get any news ?

**Comment by mpomet** [comment]
I just tested it with version 3.0.14 and it doesn't work neither...
@luigidellaquila Can you provide the sql statements you've tested because nothing work on my side :/

**Comment by luigidellaquila** [comment]
Hi @mpomet 

From Studio:

```
create class item extends v
CREATE VERTEX item SET content = 'some text ... uniquetexthere';
SELECT FROM item WHERE content MATCHES '(.*)uniquetexthere(.*)'
```

**Comment by mpomet** [comment]
@luigidellaquila Yes it works with your statements as it doesn't contains any special char.
Could you test-it with the following please : 
```sql
create class item extends v
CREATE VERTEX item SET content = 'some text ...  uniquetexthere';
SELECT FROM item WHERE content MATCHES '(.*)uniquetexthere(.*)'
```

**Comment by mpomet** [comment]
I just realize why you didn't respond.
Some browser doesn't display special chars so you might not have see the difference between your dataset and mine. But they are different.

Could you try with exactly what I wrote (copy paste entier statement) from my previous comments ? Then you'll see the bug
