### ISSUE TITLE
WAL issue adding edges to the same Vertex from more than one connection

### ISSUE THREAD

**Issue by andrea-tomassi** [orientechnologies/orientdb#8673]
### OS: Alpine Linux, Windows 7

* Start a standalone server (default configuration, 4GB ram) and **-Dstorage.useWAL=true**.
* From a Java Client insert one Vertex of the class B (with just few simple fields, aka name, description an so on).
* Start two or more instances of the Java Client inserting Vertex of class A (with just few simple fields, aka name, description an so on), all of them connected to Vertex B with one directed edge (see picture). Clients can run either fro different threads or different computers, the result is exactly the same.

![issue](https://user-images.githubusercontent.com/4680279/48939774-ad8f4700-ef15-11e8-9af3-826c56df6e48.png)

## Actual behavior  
After a certain number of insert (15k max) the server hangs, no error are displayed. The clients hangs, too.

## Steps to reproduce  
Just start the server, create the schema with classes A and B and an edge A2B.
Start 2 or more Java main on different threads/JVM/host, in order to insert a list of A vertexes, all of them connected to B vertex through edges A2B.
Wait to find the server and the clients being blocked.   

The same test works properly if you disable WAL on the server (**-Dstorage.useWAL=false**) 
Setting up the bulk insert mode on the client connections do not resolve the problem.

**Comment by laa** [comment]
Hi.
Could you provide of thread dump of the server when it hangs?

**Comment by laa** [comment]
Closed because of no reply.
