### ISSUE TITLE
JDBC Driver does not properly implement wasNull

### ISSUE THREAD

**Issue by escabe** [orientechnologies/orientdb#8674]
## Expected behavior  
When having executed a query and having obtained a ResultSet `rs`, I should normally be able to:

```
while(rs.next() {
  string val = rs.getString(colnum);
  if  (rs.wasNull()) {
    // Do something special in case string was NULL
  } else {
    // Assume val is not NULL
  }
}
```
I _should_ not have to also check for `val==null`.

## Actual behavior  
`wasNull()` in OrientDB JDBC driver simply always returns `false`.

**Comment by luigidellaquila** [comment]
Hi @escabe 

I just pushed a fix, now it should work fine.
It will be released with v 3.0.12

Thanks

Luigi
