### ISSUE TITLE
Escaping character doesn't work on delete edge subqueries

### ISSUE THREAD

**Issue by DiarmaidEverycs** [orientechnologies/orientdb#8678]
## Expected behavior  
I was attempting to delete the edges from a vertex where there was a ' in the name.   So my select statement was
delete edge from (select from test where name = 'Blah\'s Blah')
I expected this to delete all edges from the vertices in test which had name Blah's Blah

## Actual behavior  
Threw the following error:

Error parsing query: SELECT FROM test WHERE name = 'Blah's Blah' ^ Encountered " <IDENTIFIER> "s "" at line 1, column 37. Was expecting one of: <EOF> <AND> ... <OR> ... <ORDER> ... <GROUP> ... <LIMIT> ... <SKIP2> ... <OFFSET> ... <TIMEOUT> ... <FETCHPLAN> ... <LOCK> ... <NOCACHE> ... <PARALLEL> ... <UNWIND> ... ";" ... <AND> ... <OR> ... <GROUP> ... <ORDER> ... <UNWIND> ... <SKIP2> ... <OFFSET> ... <LIMIT> ... <FETCHPLAN> ... <TIMEOUT> ... <LOCK> ... <PARALLEL> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... <NOCACHE> ... DB name="Temp"

## Steps to reproduce  
Create a new database (temp)
Create a new class (test)
Insert a object into the class which has a field containing an apostraphe (insert into test content {"name": "Blah's Blah")
Try to delete edges from that vertex while using apostraphes and escaping the apostraphe (delete edge from (select from test where name = 'Blah\'s Blah') )
This command will throw an error.

FWIW, when you do a simple select (select from test where name = 'Blah\'s Blah') you get the record back (i.e., the query succeeds).   It appears to only be subqueries when you are deleteing edges that it fails on.

Workaround: Use " instead of '.   delete edge from (select from test where name = "Blah\'s Blah") works fine.

**Comment by luigidellaquila** [comment]
Hi @DiarmaidEverycs 

You have a problem in the quoting of `'Blah's Blah'`

Try to use `"Blah's Blah"` instead or to quote the `'` with backslash

Thanks

Luigi
