### ISSUE TITLE
Log level for Gremlin Server

### ISSUE THREAD

**Issue by giuseppe-martinelli** [orientechnologies/orientdb#8680]
## Expected behavior  
I want to remove all logs from console except for SEVERE level.

## Actual behavior  
Is not possible to suppress all console logging,
org.apache.tinkerpop.gremlin.server.* logs are showed.

## Steps to reproduce  
Start server and execute a Gremlin query

[orientdb-3.0.8.log](https://github.com/orientechnologies/orientdb/files/2624933/orientdb-3.0.8.log)

[orientdb-server-log.txt](https://github.com/orientechnologies/orientdb/files/2624937/orientdb-server-log.txt)

**Comment by wolf4ood** [comment]
Hi @giuseppe-martinelli 

gremlin server is configured via `$ORIENTDB_HOME/config/gremlin-server.yaml`.

You can disable the metrics logger from there

Thanks

**Comment by giuseppe-martinelli** [comment]
Is that the section I've to modify?

metrics: {
  consoleReporter: {disabled: true, interval: 180000},
  csvReporter: {disabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {disabled: true},
  slf4jReporter: {disabled: true, interval: 180000}}

**Comment by wolf4ood** [comment]
@giuseppe-martinelli 

yes it should be `enabled: false` i guess

**Comment by giuseppe-martinelli** [comment]
@wolf4ood Thank you very much, it seems to work!
