### ISSUE TITLE
[3.0.11] Cannot write Line break symbol.

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#8681]
## Expected behavior  
write `\n` success, select that record and return `\n`

## Actual behavior  
write `\n` changed in to `n`

## Steps to reproduce  
execute sql below and check memo property
```
create vertex v content { name: "jack", memo: "this is a \n multi line text" }
select from v
```

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

I just pushed a fix for this problem, it will be released with v 3.0.12

Thanks

Luigi
