### ISSUE TITLE
Get expanded object if projection contains '*,@rid'

### ISSUE THREAD

**Issue by rrpatilcse** [orientechnologies/orientdb#8684]
## Expected behavior  
Should return rid value

## Actual behavior  
Returns complete object 

## Steps to reproduce  
Use orientjs to access database
1. Create class
2. Add vertex
3. Read data of same class with projection '*, @rid' 
4. Observe the result(Contains object with property rid=> rid again contains whole object)

**Comment by luigidellaquila** [comment]
Hi @rrpatilcse 

The problem is already fixed with the new SQL executor, but  OrientJS v 2.2.2 uses the old SQL executor, that has such kind of problems. 
I strongly suggest you to migrate to OrientJS v 3.0 with the new API (and use latest OrientDB v 3.0.11)

Thanks

Luigi

**Comment by rrpatilcse** [comment]
@luigidellaquila thanks for the reply,
Today I will test the 3.0.11 and let you know what happens.
