### ISSUE TITLE
mybatis 连接orientDB，mysql多数据源配置

### ISSUE THREAD

**Issue by djjduan** [orientechnologies/orientdb#8686]
## Expected behavior  
<add here>  

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>
想在mapper.xml文件中执行orient DB 和 MySQL 数据库的sql，怎么配置？怎么让mapper文件区分找到他们对应的数据库并执行sql?

**Comment by luigidellaquila** [comment]
Hi @djjduan 

I'm afraid none of the OrientDB core developers understands Chinese, I tried with Google Translate but it didn't help much... 
Any chance to have a brief description of the problem in English? (just in case, we can try to manage Italian, French, Spanish too)

Thanks

Luigi
