### ISSUE TITLE
Does mybatis mapper.xml sql support graph database (orientDB)?

### ISSUE THREAD

**Issue by djjduan** [orientechnologies/orientdb#8688]
## Expected behavior  
<add here>  

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

In java, how does orientDB execute sql, mybatis supports orientDB?

**Comment by luigidellaquila** [comment]
Hi @djjduan 

There is no official support for MyBatis. As far as I know you should be able to use it with the JDBC driver, but I also can tell you that in the past some users reported some problems

Thanks

Luigi
