### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by andyflatt** [orientechnologies/orientdb#8699]
### OrientDB Version: 
orientdb-tp3-3.0.9  
### Java Version: 
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)  
### OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

## Expected behavior  
Server to use a consistent amount of CPU and stay responsive

## Actual behavior  
After a short (< 4 hours) time of 2 threads consume 100% of 2 CPU cores. 

![image](https://user-images.githubusercontent.com/8034630/49868432-50e0c700-fe05-11e8-87db-1754cd1b612c.png)

[orient-threaddump.log](https://github.com/orientechnologies/orientdb/files/2671794/orient-threaddump.log)

## Reproducable steps
I have 8 databases with each having two Java clients (one read, one write) connecting using these connections:

```
@Bean
    public OrientGraphFactory createOrientDbFactory() throws IOException {
        OrientGraphFactory factory = new OrientGraphFactory(iUrl + nameDb, username, password).setupPool(1, 10);
        factory.setStandardElementConstraints(false);
        return factory;
    }

    @Bean
    public OPartitionedDatabasePool createOrientDatabaseFactory(){
        return new OPartitionedDatabasePool(iUrl + nameDb, username, password, 1, 10);
    } 
```

The orientdb is configured to have both binary and http listeners over HTTPS/SSL and is running with  -Xms1G -Xmx1G

**Comment by andyflatt** [comment]
I have resolved this issue by switching to JDK 8 and bumping orient version to 3.0.11 (without TP3).  Not sure which change fixed it.  I was able to reproduce this issue with JDK 8 and 3.0.9-tp3.

**Comment by laa** [comment]
good, closing it then.
