### ISSUE TITLE
REST API > POST COMMAND > COMMAND TEXT > FETCHPLAN in SELECT command not working

### ISSUE THREAD

**Issue by octal-laurence** [orientechnologies/orientdb#8700]
## Expected behavior  
the field applicant should expand as I use fetching strategies 

## Actual behavior  
"result": [
            {
                "applicant": [
                    "#14:171"
                ],
                "address": [
                    "#13:167"
                ],
                "machineId": "DDDDD",
                "dateCreated": "2018-12-13 12:02:12",
                "purpose": ".",
                "in_certificationApplicants": [
                    "#15:155"
                ],
                "station": "DDDDD",
                "stationName": "DDDDD",
                "remarks": "",
                "dateUpdated": "2018-12-13 12:02:12",
                "status": "OPEN",
                "@rid": "#12:174",
                "@version": 1,
                "@class": "policeClearanceCertifications"
            }
        ],

## Steps to reproduce  
My code is

return rp.post('http://localhost/command/database/sql', {
    command: `SELECT 
        IN('${this._edgePoliceClearanceCertifications.tbl}') as applicant, 
        IN('${this._edgePoliceClearanceCertifications.tbl}').IN('${this._edgeApplicantsAddress.tbl}') as address, 
        * FROM ${rid} fetchplan *:1`
});

**Comment by luigidellaquila** [comment]
Hi @octal-laurence 

Which version are you using? If it's v 3.0, I strongly suggest you to use nested projections instead  https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections (fetch plans are deprecated)

Thanks

Luigi

**Comment by octal-laurence** [comment]
> Hi @octal-laurence
> 
> Which version are you using? If it's v 3.0, I strongly suggest you to use nested projections instead https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections (fetch plans are deprecated)
> 
> Thanks
> 
> Luigi

I'd check on it just now.

Hi, thanks for the assistance, May I ask is this solution can be use also in querying the edges? like in my given example query.
