### ISSUE TITLE
[Question] and [BUG] what is the embeded value order by algorithm ?

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#8702]
## Here is my data scripts
```json
create vertex v content {"math": 1, "english": 9}
create vertex v content {"math": 2, "english": 8}
create vertex v content {"math": 3, "english": 7}

create vertex content {"name": "jack"}
create vertex content {"name": "rose"}
create vertex content {"name": "pete"}

create edge e from (select from v where name = 'jack') to (select from v where math = 1)
create edge e from (select from v where name = 'rose') to (select from v where math = 2)
create edge e from (select from v where name = 'pete') to (select from v where math = 2)
create edge e from (select from v where name = 'pete') to (select from v where math = 3)
```

## I order by them like this:
```
select *, both('e').include('math', 'english') as socre from v where name is defined order by socre asc
select *, both('e').include('math', 'english') as socre from v where name is defined order by socre desc
select *, both('e').include('math', 'english') as socre from v where name is defined order by socre.math asc
select *, both('e').include('math', 'english') as socre from v where name is defined order by socre.math desc
select *, both('e').include('math', 'english') as socre from v where name is defined order by socre.english asc
select *, both('e').include('math', 'english') as socre from v where name is defined order by socre.english desc
```

## Question 1
well, it looks like you take the first element's value to order by, I just want a right  and precise answer
, and hope you write on the document.

## Question 2 [BUG]
these embeded order by work only on orientdb 2.2.x, doesn't work on orientdb 3.0.11

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

I'd say these ORDER BY conditions make no much sense in general, this is why they don't work on v 3.0.
All the expressions (`socre`, `socre.math`, `socre.english`) return a collection, and ordering by a collection is not actually a well defined operation. I'd suggest you to change the expressions a bit to make them return a single value, eg. `ORDER BY socre.english[0]`

Thanks

Luigi

**Comment by lightjiao** [comment]
I don't want to use orientdb anymore，so manny bug and undefined behavior, and document don't tell us. 🙁
