### ISSUE TITLE
Decimal issues

### ISSUE THREAD

**Issue by Y0ba** [orientechnologies/orientdb#8706]
### OS: Windows

This is duplicate of bug #6742 fix of which seems like missed from versions 3.X.X. Here are steps to reproduce:
https://gist.github.com/Y0ba/0373a773bf2e65cd9df04b8e6a51cd3a

I use stripTrailingZeros() method to workaround this bug. Maybe OrientDB should use it internally too?

**Comment by luigidellaquila** [comment]
Hi @Y0ba 

Thank you for reporting, I just pushed a fix for this problem, it will be released with next v 3.0.14

Thanks

Luigi
