### ISSUE TITLE
rebuilding index fail cause index file missing

### ISSUE THREAD

**Issue by FriedEggsWithLeek** [orientechnologies/orientdb#8709]
## Expected behavior  
rebuild index on Studio

## Actual behavior  
missing .irs or (.sbt and irs) 

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by laa** [comment]
@FriedEggsWithLeek could you provide more details on how do you work with the database? How did you get the database?
