### ISSUE TITLE
Dependency between thread during data writing in orient

### ISSUE THREAD

**Issue by rbaarathinms** [orientechnologies/orientdb#8712]
OrientDB Version: 2.2.20
Java Version: 1.8
OS: Linux

We are adding some binary datatype and document datatype in orient database. After nearly 75% completion of orient, the thread for orient persistence are in waiting state.

New strange behavior is observed now. the same build of ours has been working so far.
As analysed there are no deadlocks found.

It is observed that some threads are waiting for the below thread(InvWriter - POR_POINT-a - AddEntities) to complete. 

The threads that are in waiting state are as below:
InvWriter - POR_POINT-1
InvWriter - POR_POINT-2
InvWriter - POR_POINT-3
InvWriter - POR_POINT-4
InvWriter - POR_POINT-5
InvWriter - POR_POINT-6

InvWriter - POR_POINT-a - AddEntities thread obtained java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync's lock & did not release it. Due to that 12 threads are BLOCKED as shown in the below graph. If threads are BLOCKED for prolonged period, application will become unresponsive.

But the respective thread itself is waiting for something.

The stack observed during the persistence in orient database is given below :

InvWriter - POR_POINT-a - AddEntities - priority:5 - threadId:0x00002ae21c5a2000 - nativeId:0xc2cc - nativeId (decimal):49868 - state:WAITING
stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00002ace497e2390> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:
- <0x00002ac2aef42e08> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)

Why ReentrantReadWriteLock$NonfairSync lock is happening..?

The persistence in the orient database is done through multithreading but we have maintained different threads to persist the data parallely into different clusters. 

Still we found the threads are waiting for some other thread to complete.

There we have two issues:

1. InvWriter - POR_POINT-a - AddEntities - why this thread is in waiting state for a long time..??
2. What is dependency to wait for some of the threads to write in orient database ..??

Please explain the root cause of the issue so that we can able to resolve from our side.

This is happenning during every orient building. (min : 5 instances)

**Comment by rbaarathinms** [comment]
Can u please update or assign someone to look into this issue..?? 
Its been 5 days since i posted this issue but still no response from orient side..??

Please do the needful. This issue need to be fixed.

**Comment by luigidellaquila** [comment]
Hi @rbaarathinms 

We will look into this asap. 
In the meantime I see you are still on v 2.2.20, that is quite old and had a lot of hot fixes. I'd suggest to update to latest stable version (2.2.37 if you are still on 2.2.x branch, but if you have a chance to upgrade to v 3.0 you will have a lot of advantages), there is a chance that your problem is already fixed

Thanks

Luigi
