### ISSUE TITLE
OStorageException: Cluster Id -1 is invalid in database 'X' and crash with indexes and abstract classes

### ISSUE THREAD

**Issue by Y0ba** [orientechnologies/orientdb#8715]
## Expected behavior  
No crash and exception. Or at least make exception non-fatal and less cryptic if such usage of abstract classes is forbidden.

## Actual behavior  
OrientDB throws exception and crashes.

## Steps to reproduce  
```Java
OClass c = session.createClass("A");
c.createProperty("id", OType.LONG);
c.createIndex("A.id", OClass.INDEX_TYPE.UNIQUE, "id");

OClass c1 = session.createClass("B", "A");
c1.setAbstract(true); // <- exception throws here
```

**Comment by laa** [comment]
It is already fixed on the latest 3.0.x version because we started to use durable version of storage configuration.
