### ISSUE TITLE
Embedded Orientdb is not working in cluster

### ISSUE THREAD

**Issue by abhaypratap122** [orientechnologies/orientdb#8716]
## Expected behavior  
Embedded Orientdb should work in distributed 

## Actual behavior  
It is not working. 

## Steps to reproduce  
Try to configure an embedded orientdb in distributed mode. It is unable to connect it.

**Comment by luigidellaquila** [comment]
Hi @abhaypratap122 

We have plenty of tests with this scenario and a lot of users and customers using it in production. Could you please be a bit more specific on your problem?

Thanks

Luigi

**Comment by abhaypratap122** [comment]
We made some change in the configuration. It is working fine now.
