### ISSUE TITLE
OPageIsBrokenException Causing DB to Switch into Read Only Mode

### ISSUE THREAD

**Issue by jbylund** [orientechnologies/orientdb#8718]
### OrientDB Version: 
2.2.37

### Java Version: 
1.8.0_171

### OS: 
Linux 4.4.0-1020-aws 

## Expected behavior  
No OPageIsBrokenException

## Actual behavior  
OrientDB is switching into read only mode with a bad/missing page magic number, error message is as follows.
```
PyOrientCommandException: com.orientechnologies.orient.core.exception.OPageIsBrokenException - Following files and pages are detected to be broken ['walexecutedtransaction.pcl' :31;], storage is switched to 'read only' mode. Any modification operations are prohibited. To restore database and make it fully operational you may export and import database to and from JSON.
```

## Steps to reproduce  
Part of the reason why we're having such difficulty reproducing is that we are unsure what queries are causing the behavior.  Server seems to run for a couple days before encountering the error.

**Comment by laa** [comment]
Should be fixed in latest 3.0.x version but you should import/export database in a new version to avoid those issues.
