### ISSUE TITLE
Database function not working properly

### ISSUE THREAD

**Issue by gskarewad** [orientechnologies/orientdb#8721]
### OrientJS Version : 3.0.1

I have a function in database which goes like this
var g = orient.getDatabase();
newComponent = g.command("insert into " + component.ObjectClass + " content " + JSON.stringify(dataToClone));
g.commit();
operationResult.push(newComponent);
When i run this funtion in orientdb version 3.0.1 or lower it works perfectly fine.
## Expected behavior  
operationResult has records which are newly created.

## Actual behavior  
Do not create records or add value to operationResult array.

## Steps to reproduce  
execute the fumction using database connection with orientjs driver.

**Comment by wolf4ood** [comment]
Hi @gskarewad 

do you have any errors?

how do you execute it with OrientJS?

Do you have a complete example of a  server side function  that replicate this problem?

Thanks

**Comment by prasad-yadav** [comment]
Hi, Thanks for the quick reply and sorry for the delay.

The database doesn't throw any error but it logs following error to the console.
 TypeError: g.getRecord is not a function [ScriptObjectMirror]

Execution of the function is by using orient js database API as follows where db is an instance of OrientDB.Db

            db.let('result', function (db) {
                db.select('expand(result)').from("select myFunction('data')")
            })
            .commit()
            .return('$result')
            .all();

 I can not share the complete function but I was able to pinpoint exact lines where it was failing which are as follows
     var newRecord = g.command("insert into " + class + " content " + JSON.stringify(dataToInserte));
     var newRecordRID = newRecord.getRecord().field("@rid").toString();
 where the function calculates some data and inserts into the class.
Let me know if you need any more details

**Comment by ganesh-karewad** [comment]
Hi @wolf4ood ,
function to replicate the issue

       function addVert() {
          var g = orient.getDatabase();
          com.orientechnologies.common.log.OLogManager.instance().info(this, "adding to database");
          var retry = true;
          var retryCounter = 0;
            var operationResult = [];
          while (retry && retryCounter < 1) {
            try {
                retry = false;
                var dataToClone = {}
                dataToClone.Description = "Testing functions";
                dataToClone.Name = "TestG";
                var newComponent;
                com.orientechnologies.common.log.OLogManager.instance().info(this, "Cloning data ");
                newComponent = g.command("insert into V content " + JSON.stringify(dataToClone));
                //this is the line where orient db logs a TypeError as
                //TypeError: a.getRecord is not a function [ScriptObjectMirror]
                var newComponentDBID = newComponent.getRecord().field("@rid").toString();
                com.orientechnologies.common.log.OLogManager.instance().info(this, "@rid of new component :" + newComponentDBID);
                g.commit();
                operationResult.push(newComponent);
            } catch (err) {
                com.orientechnologies.common.log.OLogManager.instance().info(this, err.toString());
                retry = true;
                retryCounter++;
                g.rollback();
            }
         }
        return operationResult;
       }
     exports.fn = addVert;

**Comment by rrpatilcse** [comment]
Hi,
I am also facing the same issue. Is there any solution or workaround available?
