### ISSUE TITLE
Linear increase of storage size for create-delete iterations with EMBEDDEDMAP

### ISSUE THREAD

**Issue by foriam** [orientechnologies/orientdb#8722]
## Expected behavior  
create-delete iterations of documents with nested EMBEDDEDMAP should not increase physical storage (dump) size (works correctly when using LINKMAP)

## Actual behavior  
create-delete iterations of documents with nested EMBEDDEDMAP show linear increase of physical storage (dump) size (see attached graph)
<img width="499" alt="embeddedmap" src="https://user-images.githubusercontent.com/8378549/50913833-8a711600-1435-11e9-9d9e-0c2424a7bad7.png">

## Steps to reproduce  
- OElement with at least one level of nested EMBEDDEDMAP
- sufficiently large String properties
- sufficient create-delete iterations to show saturation of used disk space at reasonable size

Example test in groovy:
```
OClass embeddedMaps = db.createClass("EmbeddedMaps")
embeddedMaps.createProperty("embedded", OType.EMBEDDEDMAP)
embeddedMaps.createProperty("payload", OType.STRING)

// nesting depth (at least 2)
int depth = 2
// map entries per nesting level
// saturation of dump size below 4
int entries = 4

File dbDump = new File('testdb/testdb.zip')
long sizeInitial
long sizeBeforeDelete
long sizeAfterDelete

Closure make = {
    OElement el = db.newInstance("EmbeddedMaps")
    // Dummy data to validate file size
    String payload = ''
    for (int i = 0; i < 200; i++) {
        payload += UUID.randomUUID().toString()
    }
    el.setProperty('payload', payload)
    el.setProperty('embedded', new HashMap())
    return el
}

Closure backupSize = {
    db.backup(new FileOutputStream('testdb/testdb.zip'), null, null, null, 9, 2048)
    return dbDump.size()
}

sizeInitial = backupSize()

OElement base

Closure makeNested = {
    base?.delete()

    base = make()
    base.save()

    List<OElement> currentDepthEls = [base]

    for (int nest = 0; nest < depth; nest++) {
        List<OElement> nextDepthEls = []

        currentDepthEls.each { OElement current ->
            for (Integer entry = 0I; entry < entries; entry++) {
                OElement nested = make()
                current.getProperty('embedded').put(entry, nested)
                nextDepthEls.add(nested)
            }
        }

        currentDepthEls = nextDepthEls
    }

    base.save()
}

makeNested()

assert db.query("SELECT count(*) FROM EmbeddedMaps").next().getProperty('count(*)') == 1
sizeBeforeDelete = backupSize()
assert sizeInitial < sizeBeforeDelete

// iterate create-delete - the backup size should not grow any more after a certain point
for (int j = 0; j < 100; j++) {
    makeNested()
}

// make sure db entries are gone
base.delete()
assert db.query("SELECT count(*) FROM EmbeddedMaps").next().getProperty('count(*)') == 0

sizeAfterDelete = backupSize()
assert sizeAfterDelete < 3 * sizeBeforeDelete
```

**Comment by laa** [comment]
Hi @foriam , do you store documents inside of embedded map, in such case that is normal that space grows, because during serialization they are treated like they are inside of the map, so DB size is growing.

**Comment by foriam** [comment]
Hi @laa , yes, documents within documents within documents...
I don't think it can be expected behaviour, because:
* It depends on the degree of nesting.
* It is unexpected that this space is not released after deleting the documents. They cannot be queried any more, the db seems empty, but the space is still reserved. This can only be solved with a TRUNCATE on the top class. This makes the persistence of temporary data impossible, for example intermediate calculation results.

**Comment by laa** [comment]
I see reasigned to @tglman

**Comment by tglman** [comment]
Hi @foriam,

This issue was fixed a while ago please update to the latest hotfix (currenty 3.0.21).

bye
