### ISSUE TITLE
Question: Is it possible to use the exclude operator at the top level attributes?

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8731]
### Java Version: 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
### OS: centos07  

I would like to select a record and get all of its attributes except one or two. I saw the exclude operator for nested projections, is it possible to do something similar unnested?

For example if I have some record in V

```json
{
    "name": "bob",
    "cousin": "alice"
}
```
And I want to select all of its attributes except cousin. I tried

```SQL
SELECT *, !cousin from V
```

But that gives me errors. Is there a way to achieve this?

**Comment by luigidellaquila** [comment]
Hi @creisle 

Right now this is not supported, but I'd say it's definitely reasonable, I'll work on it and see if I can add support for it quickly.

In the meantime, you can try 

```
SELECT @this:{*, !cousin} FROM V
```

the result will be a bit different, but it should do the job

Thanks

Luigi
