### ISSUE TITLE
OTokenSecurityException

### ISSUE THREAD

**Issue by denisbakalov** [orientechnologies/orientdb#8734]
## Expected behavior  
Normal query execution  

## Actual behavior  
"com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token" after 15 min of inactivity

## Configs:
[default-distributed-db-config.json.txt](https://github.com/orientechnologies/orientdb/files/2783100/default-distributed-db-config.json.txt)
[hazelcast.xml.txt](https://github.com/orientechnologies/orientdb/files/2783101/hazelcast.xml.txt)
[orientdb-server-config.xml.txt](https://github.com/orientechnologies/orientdb/files/2783102/orientdb-server-config.xml.txt)

## Steps to reproduce  
We use a connection pool.

// this is a part of a singletone (spring bean autowired with services and components)
db = new OrientDB("remote:127.0.0.1", OrientDBConfig.defaultConfig());
graphPool = new ODatabasePool(db, "dbname", "admin", "admin"); 

// this part is executed in multiple threads each time we have a request from client
// query API is used https://orientdb.org/docs/3.0.x/java/Java-Query-API.html
while (true) { // retry loop in case of concurrency exceptions
    ODatabaseSession session = graphPool.acquire();
    try {
      resultSet = session.query("select from V where uuid = ?", someParamsHere); // also update/delete quries used
    	// query result is processed 
      resultSet.close(); // closing resultSet quietly
      // multiple queries executed same as one above
    } finally {
    	try {
    		session.commit();
    		break; 
    	} finally {
    	  session.close();
      }
    }
}

OTokenSecurityException pops up after some time of inactivity (no client requests)

1. Are there some difference between connecting to standfalone orientdb instance and distributed cluster (except connection ursl like remote:192.168.0.1,192.168.0.2/dbname)?

2. Should we somehow refresh our pool time to time to prevent security exceptions?

3. OTokenSecurityException pops up after some time (15 min usually) of inactivity (no client requests)

**Comment by dr-wolf** [comment]
We develop a Spring application, the point is that each request represents a pretty complicable object that is converted into a set of select or create/update queries, that are executed one by one in a single session aquired once per request.
