### ISSUE TITLE
Skip is ignored in complex query with outer expand

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#8737]
### OS: 14.04  

Might be related to #8736

Hi,

Suppose there are two classes `Test` and `Test2` which are connected with an outgoing `has` edge to `Test2` class, then changing `skip` in the following has no effect (i.e. as if the skip is always 0):

```
select expand(@this.include('@rid', '@class', 'id', 'name', 'name2')) 
from (
    select *, out('has')[@class='Test2'].name as name2
    from Test 
    order by name
    skip 0
    limit 10
)
```

Original query from our system is more complex and used to work very well on `2.2` we are also using PhpOrient as the library to manage our client data. For the reasons of non-disclosure, I had to mock up the query above, but the concept is the same.

I am still not sure, as the studio/console give no results at all (see issue #8736), but the problem is also related to `order by` somehow. When I comment out a portion of PHP code that adds the sorting to the query, then everything looks like it's working.

**Comment by MironAtHome** [comment]
This worked for me in console on OrientDB version 3.0.12

SELECT @this.`@rid`, @this.NAME as CityName, @this.CountryName as CountryName FROM (select *, out('CountryCity')[@class='Country'].NAME AS CountryName from City skip 1 limit 5)

Seems to work for skip.

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

In v 3.0 you should use nested projections instead of `include()` (https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections), the problem is that PhpOrient still has to be updated to support the new executor...

Thanks

Luigi

**Comment by MironAtHome** [comment]
> Hi @andreyvk
> 
> In v 3.0 you should use nested projections instead of `include()` (https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections), the problem is that PhpOrient still has to be updated to support the new executor...
> 
> Thanks
> 
> Luigi

Luigi,

Any chance documentation can be updated, this 
`SELECT 1 as a, 2 as a
will return [{"@rid": "-2:0", "a":2}]`

actually reads
`+----+----+
|#   |a   |
+----+----+
|0   |2   |
+----+----+`
or
`[{"#": "0", "a":2}]``

**Comment by luigidellaquila** [comment]
Oh yes, thank you for pointing it out, I'm updating it now

Thanks

Luigi

**Comment by MironAtHome** [comment]
Here is one more.
I have created an vertex childParent with a single property name:string.
Linked parents and children via edge parentLink
And added 3 edges in total:
Miron ( child )
Mark and Yevgeniya ( parents )
and tried to run query using  nested projections.

Here is how it looks in console:
Query
select name, out_parentLink.in:{name} from ParentChild WHERE name = 'Miron'
Result:
+----+-----+------------------------------+
|#   |name |out_parentLink.in             |
+----+-----+------------------------------+
|0   |Miron|[{name:Yevgeniya},{name:Mark}]|
+----+-----+------------------------------+

Note field out_parentLink.in produces an output string.

Then, if I use an alternate approach with expand function it looks very different:
select expand(out_parentLink.in.include('name')) from ParentChild WHERE name = 'Miron'
+----+---------+
|#   |name     |
+----+---------+
|0   |Yevgeniya|
|1   |Mark     |
+----+---------+

And so, it does look to me like the difference is not only in the style of query, but also, in how, at least console application, produces the output. I haven't yet delved if it looks different at the level of record. So, my apologies, if this is just an formatting issue.

Hope it helps.

**Comment by andreyvk** [comment]
> @luigidellaquila

As per previous comment: is include not supported now in orient 3?

https://github.com/orientechnologies/orientdb/issues/8737#issuecomment-457469397
