### ISSUE TITLE
How to use variable more times in batch ?

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8739]
### This runs without issues:
```
BEGIN;
LET createTestValue = CREATE vertex Table1 SET field = "testValue";
LET testResult = UPDATE #185:0 SET link1=[$createTestValue];
COMMIT;
RETURN $testResult;
```

### But this , returns error : 

```
BEGIN;
LET createTestValue = CREATE vertex Table1 SET field = "testValue";
LET testResult = UPDATE #185:0 SET link1=[$createTestValue],link2=[$createTestValue];
COMMIT;
RETURN $testResult;
```
Returns : 
com.orientechnologies.orient.core.exception.OValidationException: The field 'Table2.link2' has been declared as LINK but the value is not a record or a record-id DB name="testdb" Error Code="4"

Everytime, I use variable more times in the same line I get error.

How can I make this work please ? Thank you 
## Steps to reproduce  
```
CREATE CLASS Table1 IF NOT EXISTS EXTENDS V;
CREATE PROPERTY Table1.field STRING;

CREATE CLASS Table2 IF NOT EXISTS EXTENDS V;
CREATE PROPERTY Table2.someTextfield STRING;
CREATE PROPERTY Table2.link1 LINK Table1;
CREATE PROPERTY Table2.link2 LINK Table1;

CREATE VERTEX Table2 SET someTextfield = 'text';
```

**Comment by luigidellaquila** [comment]
Hi @petervavro 

I'd say it's just a bug, probably the result set from the first query is not reset correctly after the first assignment.
I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @petervavro 

We fixed this problem a few releases ago, please try latest v 3.0.14, I tested it and it works fine

Thanks

Luigi
