### ISSUE TITLE
Disable "executionPlan" in Rest API json response

### ISSUE THREAD

**Issue by abdusahin** [orientechnologies/orientdb#8743]
## Expected behavior  
Do not return "executionPlan" field in the REST API response, or add configuration parameter to enable or disable it.

## Actual behavior  
"executionPlan" field is returned in REST API response, which results in a huge json response size.

```
{"result":[{"@type":"d"," ..... ,
"executionPlan":{"@type":"d","@version":0,"cost":0,"prettyPrint":"+ .....
}
```

## Steps to reproduce  
curl -v -u username:password `http://localhost:2480/query/<db-name>/sql/select%20from%20<table>`

**Comment by luigidellaquila** [comment]
Hi @abdusahin 

It makes a lot of sense and we already discussed it internally.
We'll implement it ASAP, probably with a header parameter in the REST API

I'll keep you updated

Thanks

Luigi

**Comment by abdusahin** [comment]
Woow, that's the fastest response I've ever got on github. 
Thanks @luigidellaquila, I'll give it a try.

**Comment by kevin-holbrook-epicor** [comment]
From the documentation this looks like it was only added to the POST command, but what about the "GET - Query" variant?

**Comment by luigidellaquila** [comment]
Hi @kevin-holbrook-epicor 

As of now it is not supported, but we can consider to add it as a query string param, eg.

```
http://localhost:2480/query/test/sql/select from v?returnExecutionPlan=false
```

or as an http header 

Thanks

Luigi

**Comment by octavonu** [comment]
Hello,

Do you have any solution for GET requests? It is still returning the executionPlan object.

Thank you
