### ISSUE TITLE
OrientDB Studio consumes tuns of CPU and memory

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#8746]
## Expected behavior  
Studio should be quick and responsive

## Actual behavior  
pegs the processor and consumes tons of memory and is slow to response ( like I type a character and 20 seconds later it catches up ).
cpu is at 100.9 % and memory is at 1.3 G

## Steps to reproduce  
use a browser and connect to server

**Comment by wolf4ood** [comment]
Hi @grimace 

can you try to clean the local storage and see if it helps?


Thanks
![screenshot from 2019-01-29 11-23-12](https://user-images.githubusercontent.com/98812/51931817-0b507b80-23fe-11e9-9723-8dc799867f31.png)

**Comment by grimace** [comment]
that definitely worked.  Thx
