### ISSUE TITLE
database.ocf from v2.2.31 unreadable by higher versions

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8748]
## Expected behavior  
Re-use a database that was created under version < 2.2.32 by some version > 2.2.32

## Actual behavior  
Starting the server with version 2.2.31 is fine, opening the existing databases via "console.sh" is fine, shutting that server throws no issues.

Start the server with version 2.2.35 is fine, opening that same database via "console.sh" throws this error:
```
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb/databases/cdrarch' with mode=rw
        DB name="cdrarch"
        DB name="cdrarch"
Error: com.orientechnologies.orient.core.exception.OStorageException: Invalid format for configuration file /opt/orientdb/databases/cdrarch/database.ocf for storagecdrarch
        DB name="cdrarch"
```

If I shut this v2.2.35 version again, and start the v2.2.31, then all is working fine still and the dbase can be opened fine:
```
Connecting to database [remote:localhost/cdrarch] with user 'admin'...OK
```

I read other posts about this "database.ocf" as if there would be other simultaneous processes running that have the file already open, but in our case there is absolutely not other OrientDB server process active.

I have a snapshot of the underlying filesystem that contains the database, so I can rollback always to the state of the database that opens fine under v2.2.31

## Steps to reproduce  
Database created with some old version like v2.2.23, then upgrade versions (each time opening that server, using/adding classes to the database), till v2.2.31. All good till that stage.
Then install and start v2.2.35, try opening the dbase -> error about "database.ocf"

**Comment by rdelangh** [comment]
update: opening the database with version 2.2.32 is working without error:
```
$ /opt/orientdb/orientdb-current/bin/console.sh
OrientDB console v.2.2.32-SNAPSHOT (build 4940dfb8f7d66f50f6c103698866ffa2fff33668, branch branches/2-2-x.15993v/workspace/core) https://www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0
orientdb> CONNECT remote:localhost/cdrarch admin $mypwd
Connecting to database [remote:localhost/cdrarch] with user 'admin'...OK
```
I will go gradually a version higher until we find the one that can not process the contents of "database.ocf" correctly...

**Comment by rdelangh** [comment]
version 2.2.33 : 
```
$ /opt/orientdb/orientdb-current/bin/console.sh
OrientDB console v.2.2.33-SNAPSHOT (build 73886462eeddfdb1c71d07c4ea1c75ae3f574993, branch branches/2-2-x.15993v/workspace/core) https://www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0
orientdb> CONNECT remote:localhost/cdrarch admin $mypwd
Connecting to database [remote:localhost/cdrarch] with user 'admin'...OK
```

**Comment by rdelangh** [comment]
version 2.2.34 : error
```
$ /opt/orientdb/orientdb-current/bin/console.sh
OrientDB console v.2.2.34-SNAPSHOT (build d5c61aaed9100cb04e314f7a614b86434155a355, branch branches/2-2-x.15993v/workspace/core) https://www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0
orientdb> CONNECT remote:localhost/cdrarch admin $mypwd
Connecting to database [remote:localhost/cdrarch] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb/databases/cdrarch' with mode=rw
        DB name="cdrarch"
        DB name="cdrarch"
Error: com.orientechnologies.orient.core.exception.OStorageException: Invalid format for configuration file /opt/orientdb/databases/cdrarch/database.ocf for storagecdrarch
        DB name="cdrarch"
```

**Comment by rdelangh** [comment]
same with all following 2.2.3* and 3.* versions :
  * orientdb-community-2.2.35-20180426.152041-9.tar.gz
  * orientdb-community-2.2.35-20180509.103031-14.tar.gz
  * orientdb-community-2.2.36-20180612.121415-11.tar.gz
  * orientdb-community-2.2.37-20180613.120656-1.tar.gz
  * orientdb-community-2.2.38-20181205.092933-7.tar.gz
  * orientdb-community-3.1.0-20190129.135629-283.tar.gz

Starting the server-version 2.2.33 again, causes no single problem to open our database...
```
$ /opt/orientdb/orientdb-current/bin/console.sh
OrientDB console v.2.2.33-SNAPSHOT (build 73886462eeddfdb1c71d07c4ea1c75ae3f574993, branch branches/2-2-x.15993v/workspace/core) https://www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0
orientdb> CONNECT remote:localhost/cdrarch admin $mypwd
Connecting to database [remote:localhost/cdrarch] with user 'admin'... OK
```

**Comment by rdelangh** [comment]
SOLVED: apparently some file under the "OSystem" directory was corrupted compared to our snapshot of this filesystem. After restoring this entire "OSystem" directory from the snapshot, the database can be opened under all 2.2.3* versions, likely also under v3.* (will test right away).

Very strange though that version 2.2.33 has no problems with this corrupted "OSystem" contents.

**Comment by laa** [comment]
That is cool. Closing the issue then.
