### ISSUE TITLE
DATE comparison in WHERE does not work as expected

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8753]
## Expected behavior  
`SELECT dateField FROM TableA WHERE dateField=date("2019-02-01 05:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")`

Some of the records has value in field **dateField = "2019-02-01T05:00:00.000Z",** so these records should be found.

### My config
timezone = _GMT-05:00_
dateTimeFormat = _yyyy-MM-dd'T'HH:mm:ss.SSS'Z'_
dateFormat = _yyyy-MM-dd_

_Btw.. this "date("2019-02-01 05:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")" is generated using "orientjs"._

## Actual behavior  

**But : Query executed in 0.064 sec. Returned 0 record(s).** 

Thanks.

**Comment by luigidellaquila** [comment]
Hi @petervavro 

I did the following

```
create class TableA
create property TableA.dateField DATETIME

insert into TableA set dateField = date("2019-02-01 05:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")
SELECT dateField FROM TableA WHERE dateField=date("2019-02-01 05:00:00.000", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")
```

and it seems to work fine. I also tried to define an index on `dateField` and it still works fine.

Any clue on how to reproduce?

Thanks

Luigi

**Comment by petervavro** [comment]
But, I'm inserting DATETIME following way :
`insert into TableA set dateField = DATE("2019-02-05T05:00:00.000Z")`

I guess my problem here is the timezone. I am inserting time in default DB timezone "**GMT-05:00**" and then I am trying to compare it against "**GMT-00:00**" ? Might this be my case ?

**Comment by luigidellaquila** [comment]
Hi @petervavro 

yes, I'd say it could be the case

Thanks

Luigi
