### ISSUE TITLE
ORecordDuplicatedException: datetime key wrong format

### ISSUE THREAD

**Issue by JoaquinSV** [orientechnologies/orientdb#8754]
### OrientDB Version: 
Orientdb on Docker  latest
### Java Version: 
1.8.0_191
### OS: 
Orientdb on Docker

## Expected behavior 
The Loader should parse the datetime in this format
`2009-02-16 11:56:33`

## Actual behavior 

Mon Feb 16 00:00:00 GMT 2009

## Steps to reproduce  
I'm using a DateTime column as key when creating the vertex using the Loader.

` {"class":"PersonalEmpresas", "fields":{"class":"PersonalEmpresas", "fields":["ID_EMPRESA:string","ID_PERSONA:string","CONTRATO:string","FECHA_TRANSACCION:datetime"], "type":"UNIQUE" }`

But when reads the next lines:

```
"76592520-7","750165719","8600002046",2009-02-16 11:56:33
"76592520-7","750165719","8600002046",2009-02-16 11:21:41
```

The CSV Loader translates the DateTime to the format "E L d", deleting the time and throwing a duplicate key error.

` Error in Pipeline execution: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #523:493: found duplicated key 'OCompositeKey{keys=[76592520-7, 750165719, 8600002046, **Mon Feb 16 00:00:00 GMT 2009**]}' in index 'PersonalEmpresas.ID_EMPRESA_ID_PERSONA_CONTRATO_FECHA_TRANSACCION' previously assigned to the record #533:461`

My actual dateTimeFormat is yyyy-MM-dd HH:mm:ss

The oetl file:

```
{
  "source": { "file": { "path": "/home/orientdb/SGCAS321.csv" } },
  "extractor": { "csv": {} },
  "transformers": [
    { "vertex": { "class": "PersonalEmpresas","skipDuplicates": true} },
    { "edge": {"class":"tieneTurno","joinFieldName":"ID_TURNO","lookup":"Turnos.ID_TURNO"}}
  ],
  "loader": {
    "orientdb": {
       "dbURL": "remote:localhost:2424/Opendat",
       "serverUser": "root",
       "serverPassword": "rootpwd",
       "dbType": "graph",
       "classes": [
         {"name": "PersonalEmpresas", "extends": "V"}
       ], "indexes": [
         {"class":"PersonalEmpresas", "fields":["ID_EMPRESA:string","ID_PERSONA:string","CONTRATO:string","FECHA_TRANSACCION:datetime"], "type":"UNIQUE" }
       ]
    }
  }
}
```

**Comment by luigidellaquila** [comment]
Hi @JoaquinSV 

Can you please provide a SQL script to reproduce the problem?

Thanks

Luigi

**Comment by JoaquinSV** [comment]
Posted the oetl JSON file. I'm not using any SQL script, I'm importing a CSV using the ETL tool.
