### ISSUE TITLE
Binary protocol allows replacing edge information in one record with edge data from another record

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#8756]
### OrientDB Version:  2.x, 3.x

Hi guys,

We have a problem in our data right now that was not supposed to happen. First of all we are using PhpOrient as our main driver. Here's a scenario:

1. Pull 2 records from DB. Suppose records have `in_has_a` edges. In very basic understanding, a driver would return 2 associative arrays and each array will contain an `in_has_a` key.

2. Replace `in_has_a` data from Record 1 with `in_has_a` data from Record 2 and save Record 1. 

3. So what happens now is that Record 1 and Record 2 now both contain edge information from Record 2!

4. If you do a `delete edge`, then reference of the edge will be removed properly from Record 2, but Record 1 will still contain a dangling edge info, because it was manually replaced

## Expected behavior  
When saving a record on DB, edge information must be validated and DB should throw an error saying that edge exists but it's originally linking different records. 

## Actual behavior  
DB allows storing arbitrary edge data on a record w/o verifying it at the save time.

---
Just out of curiosity, is it somehow possible to fix our DB data right now? Any practical description of steps to do that would be much appreciated.

**Comment by andreyvk** [comment]
Just out of curiosity, is it somehow possible to fix our DB data right now? Any practical description of steps to do that would be much appreciated.

**Comment by tglman** [comment]
Hi @andreyvk,

If you do not declare a schema that enforce the `in` and  `out`  of you edge is perfectly valid as orient prospective to replace the content of an edge with another edge, the possible solution are declaring the properties in and out readonly, and if your domain allow it, define the specific linked type of in and out with the right vertex type.

As today we cannot do this generic for all the edges from orient side, so the best way is that you add this constraint to your domain.

Regards
