### ISSUE TITLE
Unable to use Studio after upgrading to 3.0.14

### ISSUE THREAD

**Issue by helgiv** [orientechnologies/orientdb#8759]
## Expected behavior

OrientDb Studio connects to an existing database

## Actual behavior
OrientDb server response with an internal server error 500 due to the following exception: 

com.orientechnologies.orient.core.exception.OStorageException: Database is locked by another process, please shutdown process and try again"

## Steps to reproduce
We are in the process of upgrading from 2.2.37 (where this worked as expected) to 3.0.14, OrientDb is embedded in our application and using plocal. 

1. Start the application
2. Try to connect to the database via OrientDB Studio.

**Comment by luigidellaquila** [comment]
Hi @helgiv 

did you upgrade to the new version of Studio?

Thanks

Luigi

**Comment by helgiv** [comment]
Hi @luigidellaquila,

Yes, we did upgrade to the newest version of the Studio. And, by the way, we're getting the same error when using the console.sh.

Thanks,
Helgi.

**Comment by laa** [comment]
Hi, @helgiv are you sure that you do not have another process which uses the same database? If you move files to another location do you still experience this error?

**Comment by laa** [comment]
Hi if that is still an issue we can work on the solution. Otherwise, it will be closed.
