### ISSUE TITLE
java.lang.NullPointerException in ALTER PROPERTY

### ISSUE THREAD

**Issue by askorohod** [orientechnologies/orientdb#8763]
## Expected behavior  
Property type is altered

## Actual behavior  
java.lang.NullPointerException

## Steps to reproduce  
Create a class X with property y of type STRING
Enter ALTER PROPERTY X.Y TYPE LINK in Studio
The response is a java.lang.NullPointerException

**Comment by luigidellaquila** [comment]
Hi @askorohod 

I just pushed a fix that solves the NPE, but please consider that changing the type of a property in most cases is not allowed (ie. if there is no natural way to convert from the old type to the new one, eg. from INTEGER to LONG)

Thanks

Luigi

**Comment by askorohod** [comment]
Hi @luigidellaquila,
First of all thank you for the quick fix.
I have to disagree with you though on your comment. The ALTER TABLE name ALTER COLUMN column_name SET DATA TYPE data_type is SQL standard and is supported by every SQL DB if the table is empty (otherwise the only solution would be drop the table and re-create). Additionally a lot of SQL DBs support the extension USING in which you can specify how to migrate the data from old type to new type. Incidentally re-typing to a "bigger" type (e.g. INTEGER o LONG) does not require the USING clause at all and will be executed on tables with data (though locking the whole table in the process).
But nevertheless thanks for the quick fix.

Alex

**Comment by luigidellaquila** [comment]
Hi @askorohod 

I agree with you, technically speaking it's possible, but right now the implementation is like that, so that's the behaviour you will see for now

Thanks

Luigi
