### ISSUE TITLE
Nested query with a star and additional attributes does not return expected result

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#8764]
### Java Version: 1.8  

Hi,

Consider the following example:

```
create class Temp

insert into Temp content {"a": 1, "grp": "a"}
insert into Temp content {"a": 1, "grp": "a"}

insert into Temp content {"a": 1, "grp": "b"}

select *, sum(a) as a from (select a, grp from Temp) group by grp
```
I am aware that the query above can be made simpler and does not require a nested approach in this particular case.

## Expected behavior  
![grp1](https://user-images.githubusercontent.com/1415506/52565235-75224980-2e30-11e9-958c-3f81130b43dc.png)

## Actual behavior  
![grp2](https://user-images.githubusercontent.com/1415506/52565241-794e6700-2e30-11e9-8ea7-54396314bf9c.png)

1. If that's a bug, what are possible approaches on making this work?
2. Also what is the reason that `_$$$OALIAS$$_0` returned to the user? Is this an expected behavior?

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

For sure there is a problem with the aliases, I'll check it ASAP.

About the query itself, what it the meaning of `*` in a grouped query? The following makes sense

```
select sum(a) as a from (select a, grp from Temp) group by grp

select grp, sum(a) as a from (select a, grp from Temp) group by grp
```

but what do you expect for the other attributes?

Thanks

Luigi

**Comment by andreyvk** [comment]
hi @luigidellaquila,

We have nested queries in which inner queries would have a bunch of attributes which would still contain values that are the same, even if records are grouped by one or another attribute. For instance,

```
insert into Temp content {"a": 1, "grp": "a",  "type1": "y", "type2": "m", ... etc}
insert into Temp content {"a": 1, "grp": "a",  "type1": "y", "type2": "m", ... etc}

insert into Temp content {"a": 1, "grp": "b",  "type1": "z", "type2": "m", ... etc}
```

So imagine that besides `type1` and `type2` there are more like them. Now lets also assume that one or more `Temp` records have an incoming `has_a` egde from Temp2. In which case:

```
select *, sum(a) as a from (
   select expand(out('has_a')) from Temp2
)
group by grp
```

should give me all the attributes plus sum of `a`'s grouped by `grp`. And I dont want to bother listing the attributes that I need. This is our case right now. 

This approach works, i believe, in 3.0.12 with PhpOrient driver. Beyond 3.0.12 PhpOrient stopped working properly unfortunatelly. So we are currently stuck on .12 until my REST driver is ready and code is fully revised.

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

I think PHPOrient is still using the old SQL executor, that we did not touch for months, so it's unlikely that its behaviour changed from v 3.0.12. 
I'd also check the queries on PHPOrient directly, because the result will be slightly different from what you see in Studio (that uses the new executor)

Thanks

Luigi

**Comment by andreyvk** [comment]
@luigidellaquila ,

Like i mentioned we are moving away completely from PhpOrient but some problems still remain.

In any case, will `select *, sum(a) as a` issue be considered? Or should I find an alternative solution?

**Comment by luigidellaquila** [comment]
It doesn't make much sense in general( ie. if an attribute has different values for different records, then the result will be completely non-deterministic), but probably we can make it work as a syntax

Thanks

Luigi
