### ISSUE TITLE
Not hitting index on a lightweight edge property in 3.0.14?

### ISSUE THREAD

**Issue by ismaelpernas** [orientechnologies/orientdb#8766]
## Actual behavior  
We have a class called Status with Id and Name properties. There is a NONUNIQUE index on the Id property. Then a CatItemCategory class that has a lightweight edge to the Status class. 

In 2.2.17 we could do this query and hit an index:
```
select from catITemCategory where CatItemCategory_Status.Id = 1
```

When I run an explain of the same query in 3.0.14 I don't see any evidence of the query hitting an index:

```
+ FETCH FROM CLASS catITemCategory
  + FETCH FROM CLUSTER 27 ASC
  + FETCH NEW RECORDS FROM CURRENT TRANSACTION SCOPE (if any)
+ FILTER ITEMS WHERE 
  (CatItemCategory_Status.Id = 1 )
```

If I run a query on the Status class it does says it is hitting the index. Something like "select from status where Id = 1" shows
```
+ FETCH FROM INDEX Status.Id
  Id = 1
+ EXTRACT VALUE FROM INDEX ENTRY
  filtering clusters [19]
+ FILTER ITEMS BY CLASS 
  status
```

Is this something that has changed from 2.2.X to 3.0.X? Is it a bug?

**Comment by luigidellaquila** [comment]
Hi @ismaelpernas 

Does the Status class have an index on Id?

Thanks

Luigi

**Comment by ismaelpernas** [comment]
Hi @luigidellaquila,

There is an index on the Id field in the class Status:

`Status.Id | NOTUNIQUE | ["Id"] | CELL_BTREE`

Interestingly enough, today I restarted the server and ran the same explain query and got a different explain description:
```
+ LET (once)
  $$$SUBQUERY$$_0 = 
    +-------------------------
    | + FETCH FROM INDEX Status.Id
    |   Id = 1
    | + EXTRACT VALUE FROM INDEX ENTRY
    |   filtering clusters [19]
    | + FILTER ITEMS BY CLASS 
    |   Status
    +-------------------------
+ FETCH FROM INDEX CatItemCategory.CatItemCategory_Status
  CatItemCategory_Status IN $$$SUBQUERY$$_0
+ EXTRACT VALUE FROM INDEX ENTRY
  filtering clusters [27]
+ DISTINCT
+ FILTER ITEMS BY CLASS 
  catITemCategory
```
I assume this one means it is hitting the index. I mentioned the restart because it is the only thing I've done from yesterday to today.

**Comment by luigidellaquila** [comment]
Hi @ismaelpernas 

Yes, it's using the index and that is the expected behaviour.
Hard to say why the behaviour changed after restart, I'll try to investigate

Thanks

Luigi

**Comment by ismaelpernas** [comment]
Thanks @luigidellaquila 

If I see the query not hitting the index again I'll let you know in case you want more information from our side.
