### ISSUE TITLE
Not hitting index on multiple conditions with AND operator in 3.0.14?

### ISSUE THREAD

**Issue by ismaelpernas** [orientechnologies/orientdb#8767]
## Actual behavior  
When running a query with two filters using the AND operator I cannot see the index hitting on the second condition. This leads me to believe that it will not be performance in the case that the first condition hits a large number of items and the second condition needs to be evaluated on the result set.

The query looks like this

`select PrimaryName from catItemCategory where PrimaryName LUCENE 'Market' AND Description LUCENE '*data*'`

The explain shows:
```
+ FETCH FROM INDEXED FUNCTION search_fields(["PrimaryName"], 'Market') = true
+ FILTER ITEMS BY CLUSTERS 
  catitemcategory
+ FILTER ITEMS WHERE 
  search_fields(["Description"], '*data*') = true
+ FILTER ITEMS BY CLASS 
  catItemCategory
+ CALCULATE PROJECTIONS
  PrimaryName
```

When I change the operator to an OR, then the explain shows that the index is perform in parallel giving me a more confident view that the index is being used:
```
+ PARALLEL
      +-------------------------
 +----| + FETCH FROM INDEXED FUNCTION search_fields(["PrimaryName"], 'Market') = true
 |    +-------------------------
 |    +-------------------------
 |  +-| + FETCH FROM INDEXED FUNCTION search_fields(["Description"], '*data*') = true
 |  | +-------------------------
 V  V 
+ FILTER ITEMS BY CLUSTERS 
  catitemcategory
+ DISTINCT
+ FILTER ITEMS BY CLASS 
  catItemCategory
+ CALCULATE PROJECTIONS
  PrimaryName
```

could this this be a bug?

**Comment by luigidellaquila** [comment]
Hi @ismaelpernas 

That's correct, for AND operators OrientDB chooses the most convenient index to use and then filters based on the rest of the conditions (it was the same in previous versions).
With the OR operator and complex conditions though, OrientDB can use multiple indexes and merge the results.
Hopefully, in the near future we will be able to do additional optimizations and do index intersection for AND operators as well

Thanks

Luigi
