### ISSUE TITLE
What is "CHM based async"?

### ISSUE THREAD

**Issue by FriedEggsWithLeek** [orientechnologies/orientdb#8769]
Please explain what is the "CHM",Thanks! 

## Expected behavior  
<add here>  

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by laa** [comment]
@FriedEggsWithLeek What do you mean? Could you be more precise? CHM means - ConcurrentHashMap

**Comment by FriedEggsWithLeek** [comment]
> @FriedEggsWithLeek What do you mean? Could you be more precise? CHM means - ConcurrentHashMap

Thank you for your reply.
I saw this word in orientd 3.0.15 change log. 

`CHM based async. cache and WTinyLFU policy are introduced.`

Should I assume that it can improve the speed of replication between two instances?

**Comment by laa** [comment]
No, that is a different case.
