### ISSUE TITLE
"missing session and token" after a period of time without interacting with OrientDB

### ISSUE THREAD

**Issue by ismaelpernas** [orientechnologies/orientdb#8772]
## Actual behavior  
We are getting the following exception consistently when our system is not being used for while and a new request comes in that requires querying OrientDB. Before that all idle time the queries work fine. The exception is:

```
! com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
! DB name="map"
! DB name="map"
! at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
! at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
! at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
...
```

Not sure if this is a bug or I am confused about the java Document API described: [here](http://orientdb.com/docs/3.0.x/java/Document-API-Database.html)

The current usage of the Document API looks like this:

1. When our product starts up I create a singleton instance of OrientDB and another of ODatabasePool. 
2. User requests comes in, I build up a query based on the user needs
3. perform `session = odbPool.acquire();` to get a ODatabaseSession
4. perform `session.execute("SQL", command)` to get the results
5. read necessary data from results
6. perform `session.close();`
7. return results

I thought the ODatabasePool was a pool of connections to a database. But looking at the javadoc on ODatabasePool says that it is "A Pool of databases". The documentation also mentions that we should close the database and it goes back to the pool. So I am not sure if I am hitting a bug or misusing the API.

Should I be creating a new ODatabasePool per request instead of having it as a singleton?  

My goal is to have the equivalent of the `factory.setupPool(10, 30);` of the OrientGraphFactory in 2.2.X.

**Comment by ismaelpernas** [comment]
@luigidellaquila Any update on this possible issue?

Thanks

**Comment by luigidellaquila** [comment]
Hi @ismaelpernas 

@wolf4ood is working on it, I'll let you know as soon as it's fixed

Thanks

Luigi

**Comment by wolf4ood** [comment]
Hi @ismaelpernas 

i've just proposed a fix in this PR, 

https://github.com/orientechnologies/orientdb/pull/8805

Once merged it will solve the issue and it will be available hopefully in 3.0.18

Thanks

**Comment by ismaelpernas** [comment]
thanks @wolf4ood !

I'll keep an eye on the 3.0.18 release.

**Comment by matanshukry** [comment]
Same thing just happened to me now, on 3.0.19, please reopen.
Let me know if you prefer I'll open a new one, although everything is exactly the same.
