### ISSUE TITLE
The error is thrown, if @rid does not exist.

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8777]
### OS: Mac OS X 10.14.3

Running query : `SELECT * FROM Table WHERE @rid=#77534534534:2l;`
`#77534534534:2l` does not exists in my DB.

## Expected behavior  
**0 records found.**

## Actual behavior  
Returns error : `com.orientechnologies.orient.core.exception.ODatabaseException: RecordId cannot support cluster id major than 32767. Found: 225123206 DB name="terminal"
`
## Why is this a BUG
I am using OrientJS client for OrientDB. If somebody searching for a non-existing record id the script in my API catches the error and it stops. In my opinion, it supposed to return just "0 records" instead. 

In the current situation, I gonna have to write extra lines, everywhere where this situation might occur to prevent unwanted response to a user in form of the error message which explains something about clusters in OrientDB. 

The information: "RecordId cannot support cluster id major than 32767." might be stated in somewhere in the documentation.

What do you think?

**Comment by luigidellaquila** [comment]
Hi @petervavro 

The information is actually present in the docs: https://orientdb.com/docs/3.0.x/internals/Limits.html
The problem here is not that the RID does not exist, but that's an invalid RID.
The error message seems absolutely reasonable.

Thanks

Luigi
