### ISSUE TITLE
Range on in() using nested projection fails

### ISSUE THREAD

**Issue by scrabb** [orientechnologies/orientdb#8778]
## Steps to reproduce  
The Document class has 3 vertices, 2 of which have an edge called IsA and 1 with no edge.  The following 3 queries all return the correct data.
`select Name.Default as Name,in('IsA'):{@class as Label,Name.Default as Name} as All_in from Document limit 3`
`select Name.Default as Name,in('IsA')[0]:{@class as Label,Name.Default as Name} as All_in from Document limit 3`
`select Name.Default as Name,in('IsA')[1]:{@class as Label,Name.Default as Name} as All_in from Document limit 3`

however

`select Name.Default as Name,in('IsA')[0..2]:{@class as Label,Name.Default as Name} as All_in from Document limit 3`
causes the following error
`java.lang.UnsupportedOperationException: Cannot convert [Ljava.lang.Object;@8461eaa - class [Ljava.lang.Object; to JSON`

**Comment by luigidellaquila** [comment]
Hi @scrabb 

I just pushed a fix, it will be released with v 3.0.18

Thanks

Luigi
