### ISSUE TITLE
SELECT with WHERE clause containing variables that match multiple indexes returns duplicate records.

### ISSUE THREAD

**Issue by jmdority** [orientechnologies/orientdb#8779]
## Expected behavior  
SELECT should return a single vertex when a single vertex matches the WHERE clause.

## Actual behavior  
SELECT returns duplicate vertices.

## Steps to reproduce  
In a graph DB (demodb works for this):

CREATE CLASS Test IF NOT EXISTS EXTENDS V;

CREATE PROPERTY Test.A IF NOT EXISTS INTEGER;
CREATE PROPERTY Test.B IF NOT EXISTS INTEGER;
CREATE PROPERTY Test.C IF NOT EXISTS STRING;
CREATE PROPERTY Test.D IF NOT EXISTS INTEGER;

INSERT INTO Test (A, B, C, D) VALUES (1, 2, NULL, 2);
INSERT INTO Test (A, B, C, D) VALUES (2, 3, NULL, 1);
INSERT INTO Test (A, B, C, D) VALUES (3, 1, NULL, 1);

-- At this point, everything works fine, adding the indexes below causes the issue:
CREATE INDEX Test.A_B_C IF NOT EXISTS ON Test (A, B, C) UNIQUE;
CREATE INDEX Test.B_C_D IF NOT EXISTS ON Test (B, C, D) NOTUNIQUE;
CREATE INDEX Test.A_C_D IF NOT EXISTS ON Test (A, C, D) NOTUNIQUE;

Create a function (or anything that allows the use of variables) containing the statements below:
LET $a = 1;
LET $c = NULL;

SELECT B,D FROM Test WHERE A = $a AND (C = $c OR ($c IS NULL AND C IS NULL));

Before the indexes are created, the single record with A = 1 is returned.  After the indexes are created, two copies of the record with A = 1 are returned by the query.  If the query is written without variables (replacing $a with 1 and $c with NULL in the query), the correct result (1 record) is returned.  It appears that the query is being executed against the two indexes and the results from each are merged without detecting that they returned the same record.

**Comment by luigidellaquila** [comment]
Hi @jmdority 

Thank you very much for reporting, I managed to reproduce the bug and I'm working to a fix

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @jmdority 

I just pushed a fix, it will be released with v 3.0.16

Thanks

Luigi
