### ISSUE TITLE
OIndexOneValue.iterateEntries breaks for Lists as keys.

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#8780]
## Expected behavior  
The API call should work.  

## Actual behavior  
The following exception is thrown:

```
java.lang.IllegalStateException: Object of class 'java.util.ArrayList' cannot be compared
[info]     at com.orientechnologies.common.comparator.ODefaultComparator.compare(ODefaultComparator.java:59)
[info]     at java.util.Collections$ReverseComparator2.compare(Collections.java:5178)
[info]     at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
[info]     at java.util.TimSort.sort(TimSort.java:220)
[info]     at java.util.Arrays.sort(Arrays.java:1512)
[info]     at java.util.ArrayList.sort(ArrayList.java:1462)
[info]     at java.util.Collections.sort(Collections.java:175)
[info]     at com.orientechnologies.orient.core.index.OIndexOneValue.iterateEntries(OIndexOneValue.java:99)
[info]     at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.iterateEntries(OIndexAbstractDelegate.java:210)
[info]     at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.iterateEntries(OIndexTxAwareOneValue.java:335)
```
The issue here is the following code:
```
@Override
  public OIndexCursor iterateEntries(Collection<?> keys, boolean ascSortOrder) {
    final List<Object> sortedKeys = new ArrayList<Object>(keys);
    final Comparator<Object> comparator;

    if (ascSortOrder)
      comparator = ODefaultComparator.INSTANCE;
    else
      comparator = Collections.reverseOrder(ODefaultComparator.INSTANCE);

    Collections.sort(sortedKeys, comparator);
```
The issue is that a List<String> (as the key) does not implement Comparable, so the sort fails.

## Steps to reproduce  
This only happens when the database is Embedded (e.g. local).  The OIndexRemote class does not perform this sorting operation.

**Comment by laa** [comment]
We do not support lists as a key in indexes. How do you add them as a key in index?

**Comment by mmacfadden** [comment]
@laa Thanks for the quick response. I am in this situation because of this other issue: https://github.com/orientechnologies/orientdb/issues/8751

In this instance I HAVE to use lists as the key value.  Which works fine when you are using a remote database, since it ultimately gets turned into a Query.  This issue is happening when I am doing unit tests against an in memory database. So at the moment... Using OCompositeKey does not work against a remote database, and using the Lists does not work against an in memory database. So there is no code that will work in both production and unit test.

I am going to probably fall back to using SQL to select from the index instead for now, since that might work for both.

**Comment by mmacfadden** [comment]
I should also add that using Lists seem to work in SQL, either directly in the SQL Text or using them as parameters:

```
db.query("SELECT FROM INDEX:TEST WHERE keys IN [["k1", "k2"], "k1", "k3"]");
```

or 

```
HashMap<String, Objects> params = new HashMap<>();
final List<Object>keys = new ArrayList<Object>();
keys.add(Arrays.asList("k1", "k2"));
keys.add(Arrays.asList("k1", "k2"));
params.put("keys", keys);
db.query("SELECT FROM INDEX:TEST WHERE keys IN :keys", params);
```

Both seem to work.

**Comment by mmacfadden** [comment]
I'd much rather be using the OCompositeKey. But I can't right now due to the other referenced issue.

**Comment by laa** [comment]
I understand but what you reported is not a bug, indexes do not support lists by definition. Exactly because of the reason you wrote.

**Comment by mmacfadden** [comment]
Gotcha. This is a bit confusing for a few reasons:

- You CAN use a list in the very same API, when using a remote database. 
- You CAN use a list when SELECTing from an index over SQL
- There doesn't seem to be any documentation saying that lists are not supported.

**Comment by mmacfadden** [comment]
I have a work around for now. I am just using SQL and passing the Keys as lists.  When #8751 is fixed I can use this API again.

**Comment by mmacfadden** [comment]
@laa I am going to go ahead and mark this closed base on your comments!  Thanks for your help.
