### ISSUE TITLE
String Manipulation Methods Not Working As Expected in Nested Projections

### ISSUE THREAD

**Issue by big213** [orientechnologies/orientdb#8783]
## Expected behavior  
Returns `ClassA_1`

## Actual behavior  
Returns `ClassB_1`

## Steps to reproduce  
`CREATE VERTEX ClassA set id= 1` `//#9:1`
`CREATE VERTEX ClassB SET foo = #9:1` `//#9:2`
`SELECT foo: { id.prefix(@class + '_') } FROM #9:2`

Same effect for `append` and I assume any other "String Manipulation" methods. It appears to take the `@class` and any other fields from the top level SELECT statement.

However using `SELECT foo: { eval("@class + '_' + id") } FROM #9:2` results in the expected behavior.

**Comment by luigidellaquila** [comment]
hi @big213 

With v 3.0.x please avoid to use `eval()`, `prefix()` and other string manipulation methods, use `+` operator instead, it works much better

Thanks

Luigi

**Comment by big213** [comment]
@luigidellaquila Can confirm that using the `+` operator works fine for string manipulation, so that solves my problem then, thanks! Could probably just get rid of `prefix` and `append` methods then, although you might still need to keep methods like `replace` and the others.

**Comment by luigidellaquila** [comment]
Hi @big213 

Yes, for sure some of them are still needed, I'll check them (but there are a few, so it will probably take some time)

Thanks

Luigi
