### ISSUE TITLE
Get @rid and @class attributes for records in projection

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8784]
### Java Version: 
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

### OS: 
MacOS 10.14.2

## Expected behavior  
Expect the nested records to contain @rid and @class attributes

## Actual behavior  
The records returned included all other attributes but not the @rid, @class , @version, etc. attributes

## Steps to reproduce  

Using the default demodb distributed with 3.0.14

```sql
select in_IsFromCountry:{*} from countries
```

result
```json
{
    "result": [
        {
            "in_IsFromCountry": [
                {
                    "in": "#33:1",
                    "out": "#122:46"
                }
            ]
        },
      ...
```

Is there a way to force the returned edges (or linked records, etc). To retain their @rid and @class fields? Previously using the fetchplans in v2 the equivalent query would return these

**Comment by luigidellaquila** [comment]
Hi @creisle 

Yes, you just have to declare them explicitly:

```
select in_IsFromCountry:{*, @rid, @class, @version} from countries
```

Thanks

Luigi

**Comment by creisle** [comment]
Yup! that works, I thought I tried that but I must have missed it. Thanks for the quick reply!
