### ISSUE TITLE
Slow performance on querying V class in 3.0.14

### ISSUE THREAD

**Issue by ismaelpernas** [orientechnologies/orientdb#8785]
## Actual behavior  
Querying the V class filtering by an Id property is very slow compared to how it was working on 2.2.14. The query itself looks like this:

`select * from V  where Id = '2' skip 0 limit 1`

This query was performing well enough on previous version but when running it in 3.0.14 takes 142 seconds when there are only 3K vertices in the V class. 

Is this a bug on the new query engine?

**Comment by luigidellaquila** [comment]
Hi Ismael,

Are indexes involved in this query?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Mmm... 142 seconds is not a matter of indexes, there must be something wrong.
Did you export-import the DB from 2.2.x to 3.0.x or did you just copy/paste the directory?
Are you using a remote connection? Do the client and server have the same OrientDB version?

Thanks

Luigi

**Comment by ismaelpernas** [comment]
Hi Luigi,

The database is created on 3.0.X. We have an indexing process that creates the db and index the data through oetl.exe commands. All the classes have an Id property and all Id properties have a index.

Our product executes the query through the HTTP API. I also copied the query and executed it from OrientDB studio and got the same performance.

Let me know if you need any additional information

**Comment by luigidellaquila** [comment]
Hi @ismaelpernas 

Any chance to have the DB with this problem?
Did you also try it with v 3.0.16?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @ismaelpernas 

I verified that in your case the query is actually fast, but the execution plan is huge (V has hundreds of subclasses with indexes on `Id`, all the indexes are used) and the serialization of the execution plan on the HTTP request is the real bottleneck.

At application level you can disable the serialization of the execution plan (see https://github.com/orientechnologies/orientdb/issues/8743) so it should not be a problem.

I'm closing this issue, please feel free to re-open if needed

Thanks

Luigi

**Comment by ismaelpernas** [comment]
Thanks @luigidellaquila 

All good from our side.
