### ISSUE TITLE
Error on batch create: declared as LINK but the value is not a record or a record-id

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8786]
### OrientDB Version: 
3.0.15
### Java Version: 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)  
### OS: 
centos07

## Expected behavior  
I was expecting the first record to be linked to the second. This worked previously with the 2.2.X series 

## Actual behavior  
Got the following error
```text

Error: com.orientechnologies.orient.core.exception.OValidationException: The field 'V.linked_attr' has been declared as LINK but the value is not a record or a record-id
	DB name="test_db"
	Error Code="4"
	DB name="test_db"
	Error Code="4"
```

## Steps to reproduce  

In a new database (using the console)

```SQL
create property V.linked_attr LINK V;

script sql
begin;
let first = create vertex v set name = 'first';
let second = create vertex v set name = 'second', linked_attr = $first;
commit;
end
```

**Comment by luigidellaquila** [comment]
Hi @creisle 

The $first value is a collection (the result of a query is always a result set, that is translated to a collection), this is why the query is failing.
You can try to use square brackets to pick the first element:

```
let second = create vertex v set name = 'second', linked_attr = $first[0];
```

Thanks

Luigi

**Comment by creisle** [comment]
Thanks @luigidellaquila that solved the above problem. I've created https://github.com/orientechnologies/orientjs/issues/363 to avoid other users running into similar issues.

**Comment by creisle** [comment]
I am having a related issue now that the above error is gone and still cannot get the full transaction to complete tho. 

The problem occurs when I try to include a subquery selecting from a variable.

For example

```sql
let subquery_example = select * from $first

OR

let subquery_example = select * from $first[0]
```

I had assumed either of those would work since you can select from a list of RIDs, is that accurate?

## steps to reproduce

In the console

```sql
script sql
begin;
let first = create vertex v set name = 'first';
let result = select * from $first;
commit;
return $result;
end
```

PS. Would you like me to move this to a new issue or is it ok to comment here?

**Comment by luigidellaquila** [comment]
Hi @creisle 

In this case, the variable name is treated as a normal identifier, so it is interpreted as a class name.
You can change the query as follows:

```
let result = select expand($first);
```

or, if you need further filtering/projections:

```
let result = select foo, bar from (select expand($first)) where baz = 1;
```

Thanks

Luigi

**Comment by creisle** [comment]
@luigidellaquila I think I am still missing something. When I try this I get the record but it is returned in the format

```json
{
  '@rid': { ....} // record contents
}
```

rather than the record itself, is that expected?

**Comment by creisle** [comment]
Worth noting that this only seems to happen when the variable being expanded is an edge

**Comment by luigidellaquila** [comment]
Hi @creisle 

I'm not sure I got the use case exactly, can you please send me a script to reproduce it exaclty?

Thanks

Luigi

**Comment by creisle** [comment]
I've been unable to reproduce this with 3.0.X versions so I will close this for now and open a new ticket if I re-encounter this issue
