### ISSUE TITLE
Error with spacial functions in projection

### ISSUE THREAD

**Issue by CapitaineCookies** [orientechnologies/orientdb#8788]
## Expected behavior  
Some result with the distance value

## Actual behavior  
java.lang.NullPointerException

## Steps to reproduce  
Code similar to #8051
```
CREATE class Restaurant;
CREATE PROPERTY Restaurant.name STRING;
CREATE PROPERTY Restaurant.location EMBEDDED OPoint;

INSERT INTO  Restaurant SET name = 'London', location = St_GeomFromText("POINT (-0.1277583 51.5073509)");
INSERT INTO  Restaurant SET name = 'Trafalgar', location = St_GeomFromText("POINT (-0.1280688 51.5080388)");
INSERT INTO  Restaurant SET name = 'Lambeth North Station', location = St_GeomFromText("POINT (-0.1120681 51.4989103)");
INSERT INTO  Restaurant SET name = 'Montreal', location = St_GeomFromText("POINT (-73.567256 45.5016889)");

CREATE INDEX bla ON Restaurant (location) SPATIAL ENGINE LUCENE;

/* should return values*/
SELECT  ST_Distance_Sphere(location, St_GeomFromText("POINT (-0.1277583 51.5073509)")) as dist from Restaurant;
```
Works well without using fields in the function

```SELECT  ST_Distance_Sphere(St_GeomFromText("POINT (-0.1277583 51.5073509)")), St_GeomFromText("POINT (-0.1277583 51.5073509)")) as dist from Restaurant```

Similar probleme with ST_Distance but response is different
```SELECT  ST_Distance(location, St_GeomFromText("POINT (-0.1277583 51.5073509)")) as dist from Restaurant```

Response 

> org.locationtech.spatial4j.exception.InvalidShapeException: can't make Geometry from: null

### Stacktrace
> java.lang.NullPointerException
> 	at com.orientechnologies.spatial.functions.OSTDistanceSphereFunction.execute(OSTDistanceSphereFunction.java:52)
> 	at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:136)
> 	at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:90)
> 	at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.execute(OLevelZeroIdentifier.java:60)
> 	at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.execute(OBaseIdentifier.java:70)
> 	at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:120)
> 	at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:110)
> 	at com.orientechnologies.orient.core.sql.parser.OProjectionItem.execute(OProjectionItem.java:147)
> 	at com.orientechnologies.orient.core.sql.parser.OProjection.calculateSingle(OProjection.java:115)
> 	at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.calculateProjections(ProjectionCalculationStep.java:66)
> 	at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.access$000(ProjectionCalculationStep.java:13)
> 	at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.next(ProjectionCalculationStep.java:41)
> 	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.next(OLocalResultSet.java:69)
> 	at com.orientechnologies.orient.core.sql.parser.OLocalResultSetLifecycleDecorator.next(OLocalResultSetLifecycleDecorator.java:56)
> 	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:97)
> 	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
> 	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:223)
> 	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:702)
> 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by Solver42** [comment]
I get same results with:
OrientDB Version: 3.0.17
Java Version: 1.8
OS: Windows 10

**Comment by machocr** [comment]
Same here:
OrientDB Version: 3.0.23
OS: macOS 10.14.6 (18G95)
