### ISSUE TITLE
DISTINCT query too way slow

### ISSUE THREAD

**Issue by mosynaq** [orientechnologies/orientdb#8789]
## Expected behavior  
return distinct values of a key in a reasonable time

## Actual behavior  
returns distinct values of a key after a long time

## Steps to reproduce and the issue in detail
I have a big dataset and imported more than 24,000,000 document into OrientDB. As part of my job I need to have distinct values for a key named, say `my_key`. The key always receives an integer number. I created a `NOTUNIQUE` index for that.
When I issue the following I have to wait for a really long time to get the distinct values:
`select distinct(my_key) from my_class;`
Changing the index type to `NOTUNIQUE_HASH_INDEX` did not solve the problem. I even tried `FULLTEXT` with lucene engine but the big delay remained.
Furthuremore, `select distinct(my_key) from indexvalues:my_class.index_name;` did not work.
Meanwhile, I have a bigger portion (about twice) of my dataset in another NoSQLDBMS (MongoDB) and it returns the distinct values in few second if not less; so the document count shouldn't be the problem.
I really like OrientDB for its features and specially Lucene integration. But this small problem (maybe bug?) prevents me from using OrientDB in my project and recommending to others.

Is the any way to resolve this issue?

**Comment by quanghaisoft** [comment]
using facet term in lucene search, but  lucene in orientdb not support facet or aggregate .
