### ISSUE TITLE
Memory is full after ETL process finish

### ISSUE THREAD

**Issue by ColdXzero** [orientechnologies/orientdb#8794]
### OS: <Red Hat 7.4>  
Memory:16G
Vcpu: 8

After importing data from Oracle database (8 millions record, 8 millions vertex,24 millions edges), the memory has only 1 GB free noting that the total size is 16GB.

Here the configuration for Server.sh

 ORIENTDB_SETTINGS="-Dstorage.diskCache.writeCachePageTTL=3600 -Dstorage.useWAL=false"
 ORIENTDB_OPTS_MEMORY="-Xms1G -Xmx3G"

here the configuration "orientdb-server-config
.xml"
[Config.zip](https://github.com/orientechnologies/orientdb/files/2922895/Config.zip)

**Comment by hossein-md** [comment]
Any update on this issue?
