### ISSUE TITLE
Is it possible to restore deleted rows or select from deleted rows

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8798]
Just deleted few rows by mistake. Is it possible to restore or just see what I deleted?
.pcl file contains rows, but maybe there is possibility to restore it through some command/tool

**Comment by luigidellaquila** [comment]
Hi @freeart 

There are no tools to restore deleted records unfortunately. There is a chance that your data are still there, but it's not easy to know where and to restore them...

Thanks

Luigi

**Comment by freeart** [comment]
Thanks, I restored manually from this garbage of raw bytes=)
