### ISSUE TITLE
"Group by" has issue when use field as a condition.

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8799]
## Expected behavior  
```sql
select document, max(timestamp), type from TForm GROUP BY document
```
```
191212121212 | 2019-03-05 14:41:29 | payment
```
```sql
select document, min(timestamp), type from TForm GROUP BY document
```
```
191212121212 | 2019-03-05 14:41:01 | profile
```

## Actual behavior  
```sql
select document, max(timestamp), type from TForm GROUP BY document
```
```
191212121212 | 2019-03-05 14:41:29 | profile
```
```sql
select document, min(timestamp), type from TForm GROUP BY document
```
```
191212121212 | 2019-03-05 14:41:01 | profile
```

## Information about db  
```sql
select document, timestamp, type from TForm
```
```
191212121212 | 2019-03-05 14:41:29 | payment
191212121212 | 2019-03-05 14:41:01 | profile
```
I know this is little bit hacky to use field as a condition in group by. But it is a simple way to get last document by group. 
This syntax works right only in mysql as I know and "max(timestamp)" returns "payment" instead of "profile".

**Comment by luigidellaquila** [comment]
Hi @freeart 

As long as you do not use all the "non aggregate" projections in the GROUP BY, the behaviour is undefined and unpredictable.
The correct query would be

```
select document, max(timestamp) as ts, type from TForm GROUP BY document, type ORDER BY ts LIMIT 1
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
(oh, `ORDER BY ts ASC` or `DESC` depending on your needs)

**Comment by freeart** [comment]
@luigidellaquila 
Actually there is a problem. Real data looks like:
```
191212121212 | 2019-03-04 11:22:02 | payment 
191212121212 | 2019-03-05 14:41:29 | payment <--last record of type "payment"
191212121212 | 2019-03-05 14:30:05 | profile
191212121212 | 2019-03-05 13:15:22 | profile
191212121212 | 2019-03-05 14:41:01 | profile <--last record of type "profile"
```
I need to get last records per each type
```sql
select max(timestamp) as timestamp, type, @rid from TForm GROUP BY type
```
result should be 
```
191212121212 | 2019-03-05 14:41:29 | payment | #xx:xx
191212121212 | 2019-03-05 14:41:01 | profile | #xx:xx
```

**Comment by luigidellaquila** [comment]
Hi @freeart 

again, you cannot do a SELECT on `document, max(timestamp) as timestamp, type, @rid` and then group by `type` only, as for `document` and `@rid` you have no aggregation rule to deterministically calculate the result.

This is not about OrientDB, it's about SQL in general, see https://stackoverflow.com/questions/20074562/group-by-without-aggregate-function

You can do it with a query like following:

```
SELECT doc[0], ts, type, rid[0] FROM (
  SELECT list(document) as doc, max(timestamp) as ts, type, list(@rid) as rid from (
     SELECT FROM TForm ORDER BY timestamp DESC
  ) GROUP BY type
)
```

but i don't expect it to be very efficient...

Thanks

Luigi

**Comment by freeart** [comment]
@luigidellaquila list() is a really good idea to do what I want! Thank you! You help me a lot!
I didn't mean that was an issue of orientdb. I just didn't know how to resolve this on orientdb sql.
I improved little bit a query to
SELECT expand(rids[0]) FROM (
    SELECT max(timestamp) as timestamp, list(@rid) as rids FROM (
        SELECT FROM TForm ORDER BY timestamp DESC
    ) 
    GROUP BY type
)
*maybe it helps to somebody who needs the same solution*
