### ISSUE TITLE
trying to select items with non empty embedded list

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#8806]
OrientDB Version: 3.0.13
Java Version: JDK 8
OS: Ubuntu 18.x

## Expected behavior  
query for items with empty embedded list

## Actual behavior  
how do I do this?  

## Steps to reproduce  
select @rid, subarticles as SA from (traverse content from (traverse pageData from (select expand(both('HasWebsite')) from `V` where uccid=36))) where SA is NON '**EMPTY**'

**Comment by luigidellaquila** [comment]
Hi @grimace 

Just use `subarticles.size() > 0`

Thanks

Luigi
