### ISSUE TITLE
Incorrect result of function

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#8811]
## Expected behavior  
function returns collection of @rid insteed objects  

## Actual behavior  
function must return result objects

## Steps to reproduce  
I have function:
return orient.getDatabase().query("select expand(outE(?).inV()) from " + fromRID)
The function is developed by JS.
orientdb {db=test}> select expand(outE(?).inV()) from #29:0

+----+-----+------+------+---------+
|#   |@RID |@CLASS|title |in_Author|
+----+-----+------+------+---------+
|0   |#33:0|Book  |Ivahoe|[#37:0]  |
+----+-----+------+------+---------+

but function returns:
orientdb {db=test}> select findv(#29:0)

+----+------------+
|#   |findv(#29:0)|
+----+------------+
|0   |[#33:0]     |
+----+------------+

Content of table OFuction:
orientdb {db=test}> select from OFunction;

+----+----+---------+----------+---------+----------+---------------------------------------------------------------------------------+----------+
|#   |@RID|@CLASS   |idempotent|name     |language  |code                                                                             |parameters|
+----+----+---------+----------+---------+----------+---------------------------------------------------------------------------------+----------+
|0   |#6:0|OFunction|          |getNumber|groovy    |return 1;                                                                        |          |
|1   |#6:1|OFunction|          |findV    |javascript|return orient.getDatabase().query("select expand(outE(?).inV()) from " + fromRID)|[fromRID] |
+----+----+---------+----------+---------+----------+---------------------------------------------------------------------------------+----------+

**Comment by schernolyas** [comment]
How I can get result of the query by function ?
I saw to code . Method "query" returns collection of @rid only.

**Comment by schernolyas** [comment]
The https://orientdb.com/docs/2.0/orientdb.wiki/Functions.html#usage-via-java-api don't work correctly.

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

I think the function is working fine, the problem is the way you are using it. 
The function returns a result set, the `SELECT function()` returns a projection of that result set, that is why you are seeing the difference.

The solution is to expand the result of the function as follows:

```
select expand(findv(#29:0))
```

I hope it helps

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila !

orientdb {db=test}> select findv(#29:0)                      

+----+------------+
|#   |findv(#29:0)|
+----+------------+
|0   |[#33:0]     |
+----+------------+

1 item(s) found. Query executed in 0.014 sec(s).
orientdb {db=test}> select expand(findv(#29:0))              


0 item(s) found. Query executed in 0.003 sec(s).
orientdb {db=test}> 

Nothing :-(
It isn't help :-(

**Comment by schernolyas** [comment]
@luigidellaquila 
But your idea is right:
orientdb {db=test}> select expand(#29:0)       

+----+-----+------+------------+----------+
|#   |@RID |@CLASS|name        |out_Author|
+----+-----+------+------------+----------+
|0   |#29:0|Writer|Walter Scott|[#37:0]   |
+----+-----+------+------------+----------+

1 item(s) found. Query executed in 0.008 sec(s).
orientdb {db=test}>
