### ISSUE TITLE
Live query: throws LINKBAG should never appear in a projection

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#8812]
## Expected behavior  
During execute live query on Vertex, the Create/Update/Delete (and other events) should be notificated without exception even if the vertex is joined to other vertex with edges.

## Actual behavior  
I have a ODatabaseSession graph where I execute a live query using `live() method`.
When I start the live execution I have a server error:

> $ANSI{green {db=MySchema}} Error executing live query subscriber.
java.lang.UnsupportedOperationException: LINKBAG should never appear in a projec
tion
        at com.orientechnologies.orient.core.serialization.serializer.result.bin
ary.OResultSerializerNetwork.serializeValue(OResultSerializerNetwork.java:426)
        at com.orientechnologies.orient.core.serialization.serializer.result.bin
ary.OResultSerializerNetwork.serialize(OResultSerializerNetwork.java:134)
        at com.orientechnologies.orient.core.serialization.serializer.result.bin
ary.OResultSerializerNetwork.toStream(OResultSerializerNetwork.java:649)
        at com.orientechnologies.orient.client.remote.message.OMessageHelper.wri
teProjection(OMessageHelper.java:411)
        at com.orientechnologies.orient.client.remote.message.OMessageHelper.wri
teResult(OMessageHelper.java:448)
        at com.orientechnologies.orient.client.remote.message.OLiveQueryPushRequ
est.write(OLiveQueryPushRequest.java:64)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkP
rotocolBinary.push(ONetworkProtocolBinary.java:875)
        at com.orientechnologies.orient.server.OServerLiveQueryResultListener.se
ndEvent(OServerLiveQueryResultListener.java:34)
        at com.orientechnologies.orient.server.OServerLiveQueryResultListener.on
Update(OServerLiveQueryResultListener.java:47)
        at com.orientechnologies.orient.core.sql.executor.LiveQueryListenerImpl.
onLiveResult(LiveQueryListenerImpl.java:147)
        at com.orientechnologies.orient.core.query.live.OLiveQueryQueueThreadV2.
run(OLiveQueryQueueThreadV2.java:57)

I tried version **3.0.16** too but I have the same exceptions. In the **3.0.15** it worked on Linux env only

## Steps to reproduce  
Create two Vertices A, B and an edge E from A to B like this:

`A (out) --- E ---> (in) B`

Now create a java code where execute a live query:

> 
                     graph.live("select from B", new OLiveQueryResultListener() {

			@Override
			public void onUpdate(ODatabaseDocument database, OResult before, OResult after) {
				System.out.println("onUpdate");
				
			}

			@Override
			public void onError(ODatabaseDocument database, OException exception) {
				System.out.println("onError");
			}

			@Override
			public void onEnd(ODatabaseDocument database) {
				System.out.println("Live query terminate with unsubscribe");

			}

			@Override
			public void onDelete(ODatabaseDocument database, OResult data) {
				System.out.println("onDelete");
				
			}

			@Override
			public void onCreate(ODatabaseDocument database, OResult data) {
				System.out.println("onCreate");
			}
		}, new HashMap<String, String>());

When I update a data on the Vertex B, live query does not works but give me the exposed exception.

**Comment by andrea-tomassi** [comment]
@luigidellaquila any news on that issue? I want to underline that the Linux version  3.0.15 is affected as well. Actually, all recent versions are affected, and this is not related to underlying operating system. 
I think this is a quite basic feature and now this is not usable at all. The latest working version is 3.0.8 (but that version causes more and more different problems, so we had to upgrade). 
Please give us some feedback on that. Do we need to avoid using live queries at all? Thank you.

**Comment by luigidellaquila** [comment]
Hi @andrea-tomassi @gianluca-valentini 

I still cannot manage to reproduce this issue... I tried to write a test case in v 3.0.17 but it seems to work fine.
Can you please share a failing test case?

Thanks

Luigi

**Comment by gianluca-valentini** [comment]
Hi @luigidellaquila 
thanks for your answer. I can give you the same test case that 'm using and that I post you in the issue [8752](https://github.com/orientechnologies/orientdb/issues/8752#issuecomment-461066559).

To avoid wasting any more time, can you give me your test case instead? I would like to understand if there is something I am doing wrong without being aware of it. 
As you know I'm using remote connection to OrientDB and with the 3.0.17 version I have [the same java exception](https://github.com/orientechnologies/orientdb/issues/8752#issuecomment-461039056) that I had using 3.0.14

I'm starting to think that probably wasn't working even in 3.0.15. It seems to work fine **ONLY** when the LiveQuery is executed on Vertices without edges.

Please give me a feedback about it.

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

I just added a specific test case to the main repo:

https://github.com/orientechnologies/orientdb/commit/027da7633a6ff27f3f4531d283dc4a70be1eb270

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @gianluca-valentini 

Ok, it makes sense. Probably the problem is related to the REST API (see https://github.com/orientechnologies/orientdb/issues/8762). I'll check it and let you know

Thanks

Luigi
