### ISSUE TITLE
doc.field('@rid') is negative when onAfterCreate dynamic hook is called

### ISSUE THREAD

**Issue by jymcheong** [orientechnologies/orientdb#8814]
## Expected behavior  
@rid should be usable.

## Actual behavior  
Note the left console is output; negative @rid from doc.field('@rid')

![](https://www.dropbox.com/s/l09oja7z1mckf3y/Screenshot%202019-03-14%2013.40.52.png?raw=1)

## Steps to reproduce  

As per screenshot above.

**Comment by dnaeon** [comment]
Same issue observed here as well.

In my case I'm using a dynamic hook to create edge between newly created record and some other pre-existing ones, but cannot do that since I get an invalid record id.

When can we expect a fix for this issue?

**Comment by luigidellaquila** [comment]
Hi @jymcheong @dnaeon 

I'm afraid this issue cannot be fixed in v 3.0 as it has a big impact on the tx lifecycle.
What I can suggest is to use live queries instead (see https://orientdb.com/docs/3.0.x/java/Live-Query-Java.html).

Thanks

Luigi

**Comment by jymcheong** [comment]
@luigidellaquila 

Noted with thanks.

**Comment by fgnm** [comment]
@luigidellaquila are there any progress on this issue?
