### ISSUE TITLE
Impossible to read a chunk of length:553648128 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings

### ISSUE THREAD

**Issue by taal25** [orientechnologies/orientdb#8816]
### OS: <MacOsX>  

I'm developing a platform with node js as backend and orientdb as db. 
During a stress test I runned multiple times a single api's and I received this error: 
"Impossible to read a chunk of length:553648128 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings" 
I tried to change the setting NETWORK_BINARY_MAX_CONTENT_LENGTH to another value from the terminal when I started the server but it doesn't change anythings. 

How could I fix it?

**Comment by wolf4ood** [comment]
Hi @taal25 

which driver are you using and which version?

Thanks

**Comment by taal25** [comment]
> Hi @taal25
> 
> which driver are you using and which version?
> 
> Thanks

I'm using orientjs version 3.0.3

**Comment by wolf4ood** [comment]
@taal25 

do you have a reproducer that i can use for debugging this issue?

do you have also the stacktrace of the exception?

Thanks

**Comment by taal25** [comment]
@wolf4ood 
Unfortunately I haven't a reproducer

The error it was generate after several times that my api run this method "db.select().from(id).one()"

'id' it's the id of the vertex, and it generate this error "OrientDB.RequestError: Impossible to read a chunk of length:553648128 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings"

The first times that I run the api's all is ok but after several times it generates this error and every other following requests remain in pending

**Comment by wolf4ood** [comment]
Hi @taal25 

are you using the latest APIs with `OrientDBClient`? 

https://orientdb.com/docs/3.0.x/orientjs/OrientJS.html#connect-to-orientdb

Is the id a internal OrientDB record id right?

Can you also check the logs on OrientDB side in file
`${ORIENTDB_HOME}/log/orient-server.log.*` you should have the entire exception 
on the server

Thanks

**Comment by taal25** [comment]
@wolf4ood 
Thanks so much, I fixed it.
The error was generated by an uncorrect configuration of the orientjs driver, above all when I initialized the driver I didn't imported OrientDbClient but just orientjs
