### ISSUE TITLE
How to remove duplicates from UNWIND query result ?

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8822]
## Expected behavior  
I have a case when UNWIND is used in query, it sometimes returns the same items more times. This behavior is totally correct but, how do I eliminate duplicates in it, please?

Thanks.

**Comment by luigidellaquila** [comment]
Hi @petervavro 

Which is the exact query? Typically a `SELECT DISTINCT` is enough to solve the problem

Thanks

Luigi

**Comment by petervavro** [comment]
@luigidellaquila Thank you for answer, is this documented somewhere please?
