### ISSUE TITLE
Select float returns different value

### ISSUE THREAD

**Issue by Solver42** [orientechnologies/orientdb#8823]
## Expected behavior  
Returning `53.546754`

## Actual behavior  
Returning `53.546753`

## Steps to reproduce  
`SELECT 53.546754`

**Comment by luigidellaquila** [comment]
Hi @Solver42 

This is because of number precision. By default floating point numbers are treated ad Java Float, but you can force OrientDB to use Double instead:

```
SELECT 53.546754d
```

If it's not enough, you can use absolute precision Decimal:

```
SELECT SELECT decimal("53.546754")
```


I hope it helps

Thanks

Luigi

**Comment by Solver42** [comment]
I see, that helps. Thank you!
