### ISSUE TITLE
how to check is exists before creating edge

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#8830]
## Expected behavior  
would like to only create one edge, but need to check if exists first

## Actual behavior  
just don't know how to do this 

## Steps to reproduce  
something like:
CREATE EDGE E FROM #22:33 TO #22:55 IF NOT EXISTS

**Comment by luigidellaquila** [comment]
Hi @grimace 

You can do it in a single statement with CREATE EDGE UPSERT:

```
CREATE EDGE E UPSERT FROM #22:33 TO #22:55 
```
The UPSERT requires a UNIQUE index on EdgeClass[out, in] and only checks if the edge exists between the two vertices (it doesn't check other properties)

docs here:

https://orientdb.com/docs/3.0.x/sql/SQL-Create-Edge.html

Thanks

Luigi

**Comment by grimace** [comment]
Thank you!

**Comment by grimace** [comment]
Why do I get this exception while trying to create an edge?
```
Relationship content is invalid on field in_OwnsContent. Found: {delegate={entries=[#303:0]}}
```
I don't think I'm trying to set any properties on the Edge.

here's how I'm executing the create/upsert:
```
              res.locals.db.create("EDGE", "OwnsContent", "UPSERT")
                .from(repo_id).to(rid)
                .one()
                .then(edge => {
                    console.log('created edge from repo to article : '+edge);
                    cb(edge);
                });
```
cb is a callback in nodejs...
