### ISSUE TITLE
Question about SQL IN operator with rids

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#8835]
### OrientDB Version: 2.2.37

I have a question regarding the usage of the IN operator when it applies to rids.
Using my demo data:

This query returns all the cars belonging to Ferrari or Mclaren:
`SELECT  FROM Car WHERE team.name IN ['Ferrari', 'McLaren F1']`

But this one returns no cars at all (the ids are the ones of Ferrari and McLaren):
`SELECT  FROM Car WHERE team.@rid IN ['#44:0', '#41:0']`

What is the reason? How should the query be rewritten?

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

Do you have a SQL script to reproduce the problem?
Have you tried the following?

```
SELECT FROM Car WHERE team IN ['#44:0', '#41:0']
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Oh, I just noticed that you have quotes around the RIDs, did you try to remove them?

```
SELECT FROM Car WHERE team.@rid IN [#44:0, #41:0]
```

Thanks

Luigi

**Comment by diegomtassis** [comment]
Hi Luigi,

It works removing the quotes, thanks.

But why are they needed when using equals instead of IN?

I mean this query works with quotes:
`SELECT  FROM Car WHERE team.@rid = '#41:0'`

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

I'd say that in that case there is an automatic conversion that does not happen with the IN operator. In general, the correct expression is without quotes

Thanks

Luigi

**Comment by diegomtassis** [comment]
Ok, when using equals they are not needed but they are supported.

`SELECT FROM Car WHERE team.@rid = '#41:0'`
`SELECT FROM Car WHERE team.@rid = #41:0`

These 2 queries are both valid, but when it comes to the IN operator only the unquoted version is supported.

In contrast, if the field is not the rid the values have to be quoted.

`SELECT FROM Car WHERE team.name IN ['Ferrari', 'McLaren F1']`
`SELECT FROM Car WHERE team.name = 'McLaren F1'`

When queries are generated manually is not a big thing, but when they are generated using a compiler from an AST it really matters. If the values can be quoted it means that for compiling a literal it is not needed to visit its parent node in the AST, but if they have to be quoted or not depending on the scenario (if it's a simple binary condition or an IN operator, if the field is a id or not), then it means the parent node has to be visited.

We have a compiler from an ANSI SQL AST to OrientDB SQL and this would be the only scenario where visiting the parent of a node would be needed.

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

The point here is that strings are quoted, while other data types are not. 
A RID is not a string and is not quoted, the same way an integer and a floating point number are not quoted, there is no difference.

Thanks

Luigi

**Comment by diegomtassis** [comment]
Understood.

I think the solution for us will be to have 2 different keys per each entity, use the rid as a surrogate key and add a string business key, though obviously using the business key will perform worse.

Thanks.
