### ISSUE TITLE
Custom key on property subset

### ISSUE THREAD

**Issue by bplumejeau** [orientechnologies/orientdb#8838]
Using OrientDB 2.2.19 and remote storage ,set strictSql=false 

I need to define index on part of property of type byte[] (from index 2 to 3 for example)
I tried to use Custom Key [http://orientdb.com/docs/2.2.x/Indexes.html Custom Keys]  and I faced an issue

when I create a custom index on remote database 
I get exception : com.orientechnologies.orient.core.exception.OConfigurationException: Runtime index definition cannot find binary serializer with id=101. Assure to plug custom serializer into the server.
whereas I registered my custom serializer  server side by statement :
OBinarySerializerFactory.getInstance().registerSerializer(new ComparablePartialBinarySerializer(), null)

Currently to solve this issue, i forked class OBinarySerializerFactory to register my serializer.
but  I search a better solution to use custom key (without fork orientdb).

If custom key is not the good way,  is there a feature to create index on property subset.

**Comment by laa** [comment]
Hi, @bplumejeau could you provide full stack trace which you get when registering binary serializer. I need to warn you that when we fix this issue you still will need to wait quite a while for the next 2.2.x release. Could you try 3.0.x version instead?

**Comment by laa** [comment]
Closed because of no reply
