### ISSUE TITLE
Load balancing issie

### ISSUE THREAD

**Issue by fpra** [orientechnologies/orientdb#8842]
## Expected behavior  
Every connection is created with a different URL

## Actual behavior  
As for issue #7110 i'm having issues with client load balancing.
I create a graphFactory at BE startup as shown below:
```java
graphFactory = new OrientGraphFactory(url, user, pass);
graphFactory.setConnectionStrategy(OStorageRemote.CONNECTION_STRATEGY.ROUND_ROBIN_CONNECT.toString());
graphFactory.setupPool(1, 100);
```
Url is composed as this: remote:ip1;ip2;ip3/dbName

We noticed that every connection is created with the first ip of the list.
In debug mode the behaviour was exactly the same as the one described here: https://github.com/orientechnologies/orientdb/issues/7110#issuecomment-274836931

Regards

**Comment by ozgursucu** [comment]
Hi @luigidellaquila 
I have made some fixes regarding this issue (Appears in orientdb 3.0) but I cannot push to a remote branch as I have no permission. Would you please give me permission to be able to push the fix so that I can make a pull request.

**Comment by luigidellaquila** [comment]
Hi @ozgursucu 

I'm afraid I cannot authorise you to push, but you can fork the project, push on your fork and then provide a PR (see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

Thanks

Luigi

**Comment by ozgursucu** [comment]
hİ @luigidellaquila 
Here is the pull request: https://github.com/orientechnologies/orientdb/pull/9078
