### ISSUE TITLE
Encountered " "(" "( "" at line 1

### ISSUE THREAD

**Issue by gaithoben** [orientechnologies/orientdb#8848]
## Expected behavior  
Execute sql statement

## Actual behavior  

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
insert into student(FirstName, LastName, DOB) values(Ben, WildKid 1983)
                   ^
Encountered " "(" "( "" at line 1, column 20.
Was expecting one of:
    <SELECT> ...
    <FROM> ...
    <RETURN> ...
    <CLUSTER> ...
    
	DB name="boilerplate"
	Error Code="1"
	DB name="boilerplate"

orientdb {db=boilerplate}> 

## Steps to reproduce  

INSERT INTO Student (FirstName, LastName, DOB) values('Ben', 'WildKid' 1983)

**Comment by luigidellaquila** [comment]
Hi @gaithoben 

You miss a comma between `'WildKid'` and `1983`

Thanks

Luigi

**Comment by gaithoben** [comment]
Indeed!! Thank you so much @luigidellaquila 

Thank you so much for OrientDB. I am developing a "Better" to use with sailsjs since i find most of the available ones old and no longer supported.

Please let me know what you think about this.
