### ISSUE TITLE
How to limit number of clusters per class?

### ISSUE THREAD

**Issue by thenesk** [orientechnologies/orientdb#8849]
### OrientDB Version: 2.2  

How do I limit the number of clusters created per class?  My application, currently using Pyorient 1.5.5 to communicate with OrientDB 2.2, runs significantly slower on my 32 core production servers than it runs on my 4 core test VMs.  I suspect it is because OrientDB is splitting the data across more clusters when there are more cores.  Rather than let OrientDB set the number of clusters per class based on the number of processor cores, I would like to try setting a fixed number clusters per class to see if that improves performance for my app.  How do I limit the number of clusters per class?

**Comment by luigidellaquila** [comment]
Hi @thenesk 

This is the command:

```
ALTER DATABASE MINIMUMCLUSTERS 4
```

(or just choose the number of clusters you prefer)

Thanks

Luigi

**Comment by thenesk** [comment]
Thanks for the quick reply!  Would the same format command work for setting a maximum?
`ALTER DATABASE MAXIMUMCLUSTERS 4`

**Comment by thenesk** [comment]
I think I have too many clusters on my production server, and would like to reduce the maximum number of clusters created per class

**Comment by luigidellaquila** [comment]
Hi @thenesk 

just use MINIMUMCLUSTERS, it actually sets a maximum ;-)

Thanks

Luigi

**Comment by thenesk** [comment]
That appears to have worked.  Feel free to close the issue.  Thanks!
