### ISSUE TITLE
Comparison via = doesn't work in projections

### ISSUE THREAD

**Issue by AlexTalker** [orientechnologies/orientdb#8856]
## Expected behavior  
```select `field` == "String" from Edge```  works
```select sum(`field` = "String") from Edge``` works

## Actual behavior  
Syntax error

## Steps to reproduce  
Documentation contains comparison of strings(via `==`) inside of `projections` part of `SELECT` query.
https://orientdb.com/docs/3.0.x/sql/SQL-Methods.html
But it doesn't work for me, I get syntax error.
Single `=` doesn't work also.
I do not understand what's so hard in supporting this.
Inside `eval()`  this seems to work but I can't `sum` after `group by` values.
Checked only in `OrientDB` studio.

**Comment by luigidellaquila** [comment]
Hi @AlexTalker 

This syntax is not supported (and never was), could you please point me to the docs where it is reported?

Thanks

Luigi

**Comment by AlexTalker** [comment]
@lucafrosini Did I not made myself clear?
If you look into https://orientdb.com/docs/3.0.x/sql/SQL-Methods.html , you can see things like:
```
SELECT name.trim() == 'Luke' FROM Actors
```
And I do not know why this is not supported along with other methods since it looks like calling `.equals()` for me, so I would highly appreciate if you could add a workaround for that.
For my case I can call `.indexOf()` but it would not satisfy everyone.

**Comment by AlexTalker** [comment]
@luigidellaquila Just like I can't understand why I can't convert `Boolean` into `Integer` for summing up.

**Comment by luigidellaquila** [comment]
Hi @AlexTalker 

Thank you very much for pointing it out, that's definitely wrong docs, I'll update it asap

I'd really like have boolean expressions in projections, I'll see if I can add it to the roadmap, but I cannot guarantee for a quick solution

Thanks

Luigi

**Comment by AlexTalker** [comment]
@luigidellaquila These wrong docs came since version `2.0` I think or maybe earlier.
I just saying that if you have so many methods `Java-like` why do not bring a bit of functionality duplication in place where you already can all them.

As a matter of fact, I can use `eval` to utilize the comparison but I can't convert resulting `Boolean` into `Integer` there, `sum` just gives me nothing(or syntax error, can't remember exact).

**Comment by ivanfrolovmd** [comment]
@luigidellaquila, can you please explain why this syntax is not supported? What is the principal difference between these queries?
```sql
select 1 + 3 -- works, returns 4
select 1 > 3 -- doesn't work
```
Both use expressions in projections, which evaluate to different types of results (Int vs Bool).

Workaround I've found so far is to use eval, but this is dependant on formatting, so I'm worried to use it in the wild:
```sql
select eval('1>3') -- returns 1
select eval('1 > 3') -- returns false
```
Not sure if eval is also adding an overhead to query execution.


The documentation still says the following:
in https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html:
> A projection has the following syntax:
> `<expression> [<nestedProjection>] [ AS <alias> ]`
> `<expression>` is an expression (see SQL Syntax) that represents the way to calculate the value of the single projection

and in SQL Syntax it says in https://orientdb.com/docs/3.0.x/sql/SQL-Syntax.html
> Valid expressions are:
> `<expression> <binary operator> <expression>`: for operator precedence, see below table.

And it seems that all binary operators are supported except for boolean operators. 

It would be nice to have at least a warning/disclaimer in the docs stating what are the limitations in defining projections (like expressions resulting in boolean types are not supported etc).

**Comment by ivanfrolovmd** [comment]
Here's another confusing set of examples:
```
select if(1 < 3, "yes", "no") -- doesn't work
select if(true, "yes", "no") -- works, returns yes
select if(false, "yes", "no") -- works, returns no
```
