### ISSUE TITLE
How integrate OAuth2 authentification with OrientDb

### ISSUE THREAD

**Issue by vitalii-honchar** [orientechnologies/orientdb#8857]
### OS: Ubunu 18.04

I'm looking for add support of OAuth2 with our web application in Orienteer.
I found OToken in OrienDB and JWT implementation, but I can't found how to login in OrientDb with OAuth2.

How can I use OAuth2 with OrientDB?

Right now my implementation is like this:

1. I found user throughout code which I received in OAuth2 communication
2. Then generate random password and updates user password for login in application and open database.
https://github.com/WeaxMe/Orienteer/blob/develop/orienteer-users/src/main/java/org/orienteer/users/service/impl/DefaultOAuth2ServiceImpl.java#L58-L77
3. Then I login in this user

But this looks like a hack. I didn't found something about OAuth2 with OrientDB.

Thanks,
Vitalii

**Comment by wolf4ood** [comment]
Hi @WeaxMe 

there is no proper support for JWT or OAuth2. OToken it is used for authentication of clients so the api exposed are in the network protocol. 

In this case you should implement that at application level

**Comment by WeaxMe** [comment]
Got it, thanks.
Do you consider possibility for include support JWT or OAuth2 in OrentDB ?
