### ISSUE TITLE
Usage of $parent.$current in sub-query ?

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8860]
## Steps to reproduce  
```
SELECT * FROM (
    SELECT $a FROM TableA LET $a = $parent.$current.fieldA CONTAINSTEXT 'foo'
) ORDER BY (fieldB ASC)
```

## Actual behavior  
It looks for "$parent.$current.fieldA" in top level `SELECT * FROM (...) ORDER BY (fieldB ASC)` so the result is incorrect.

## Expected behavior  
How do I make it to look for it in `SELECT $a FROM TableA` ?

Thanks.

**Comment by luigidellaquila** [comment]
Hi @petervavro 

What do you exactly want to achieve? The query you posted is syntactically incorrect

Thanks

Luigi

**Comment by tglman** [comment]
Hi,

No replies since a while, closing
