### ISSUE TITLE
UPSERT doesn't properly when call it twice in parallel

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8862]
## Expected behavior
Number of clusters doesn't matter. 
I thought to set cluster to 1 is fixing this problem. 
The records have the same cluster id, but it still inserts twice

## Actual behavior  
Sometimes (nearly 30%) it creates two records with the same data but different @rid.

## Steps to reproduce 
```sql
CREATE PROPERTY `TForm`.`timestamp` DATETIME
ALTER PROPERTY `TForm`.`timestamp` DEFAULT sysdate("yyyy-MM-dd HH:mm:ss")
CREATE PROPERTY `TForm`.`answer` EMBEDDEDMAP STRING
CREATE PROPERTY `TForm`.`document` STRING
CREATE PROPERTY `TForm`.`type` STRING
```
Call this sql twice via REST API in parallel with the same variables
```sql
UPDATE TForm 
SET
    answer.test = :test
UPSERT
RETURN AFTER
    $current.@rid, $current.answer
WHERE 
    type = :type AND 
    document = :owner
```

**Comment by luigidellaquila** [comment]
Hi @freeart 

The UPSERT relies on a simple query to retrieve the existing record, if you do it concurrently there is a chance of a race condition.
To avoid it, you should define a unique index on the UPSERT condition.

BTW, you should also set the WHERE condition explicitly, ie.

```UPDATE TForm 
SET
    answer.test = :test,
    type = :type,
    document = :owner
UPSERT
RETURN AFTER
    $current.@rid, $current.answer
WHERE 
    type = :type AND 
    document = :owner
```

**Comment by freeart** [comment]
@luigidellaquila Thanks for advice about WHERE.
Can I use transactions to prevent it?

**Comment by luigidellaquila** [comment]
Hi @freeart 

Transactions guarantee isolation, but not uniqueness of application level keys, so it won't help much

Thanks

Luigi

**Comment by freeart** [comment]
@luigidellaquila Thanks! So, I should change the logic little bit because in my case document and type is not unique for some cases.
