### ISSUE TITLE
OrientDB with ORM, spring, and graph (updated!)

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8873]
### OS: Windows/Linux

I'm using Spring and would like to use OrientDB with the graph model. I've looked at multiple projects that aim to help with that, but I had problem with all of them. As far as I can tell the most performant way of doing things right now is to use the graph api natively, while filling pojos manually. Is there really no better way?

- spring-data-orientdb: very outdated. I even tried to fork the v3.0.0 branch. The differences are not subtle.
- TinkerPop Frames: seems very old. Last updated at Sep 2014
- Totorom: Doesn't even support tinkerpop3. Old either way, Dec 2014.
- Object API (not really): The documentation clearly says combining the graph api with the document api will provide sub-optimal performance.
- Ferma: This seems to be the best chance, sort of. Although right now I'm stuck on doing sort. I can't find anything on google nor their documentation, which is almost non-existing (they have javadoc, but with almost no comments/description).

Is there any other alternative? Or is there really no "easy"(or normal) way of using orientdb as a graph db with Spring?

**Comment by stozk** [comment]
https://github.com/microsoft/spring-data-gremlin also looks interesting but I cannot get it working with the latest orientdb-tp3

I have this problem there:

https://github.com/microsoft/spring-data-gremlin/issues/231

**Comment by simonmulser** [comment]
any updates or more insights on that?
