### ISSUE TITLE
DATETIME DEFAULT sysdate() works wrong

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8874]
## Expected behavior  
```timestamp``` contains ```2019-05-20 23:45:34``` current timestamp of insertion 

## Actual behavior  
```timestamp``` contains ```2019-05-20 23:37:14``` timestamp of execution ```sql ALTER PROPERTY `Table`.`timestamp`...```

## Steps to reproduce  
```sql
CREATE CLASS Table
CREATE PROPERTY `Table`.`test` STRING
CREATE PROPERTY `Table`.`timestamp` DATETIME
ALTER PROPERTY `Table`.`timestamp` DEFAULT sysdate("yyyy-MM-dd HH:mm:ss") #2019-05-20 23:37:14
INSERT INTO Table SET test = "1" #2019-05-20 23:45:34
```

**Comment by luigidellaquila** [comment]
Hi @freeart 

Try the following:

```
ALTER PROPERTY `Table`.`timestamp` DEFAULT 'sysdate("yyyy-MM-dd HH:mm:ss")'
```

In your case, the sysdate() function is evaluated only once, when you create the schema and the value is assigned as default value.

If you quote it, the funciton is evaluated at each record creation

Thanks

Luigi
