### ISSUE TITLE
CREATE EDGE query prformance slowes down gradually

### ISSUE THREAD

**Issue by malharT** [orientechnologies/orientdb#8876]
## Expected behavior  
'CREATE EDGE' query time should stay same irrespective of entries in database 

## Actual behavior  
'CREATE EDGE' query time increases with no. of entries in database

## Steps to reproduce  
I'm using pyorient client to add edges(100k) in loop as follows:
```
for id1,id2 in zip(parents,children):
    client.command("CREATE EDGE HAS_CONCEPT FROM (SELECT FROM V WHERE Cid = '" + id1 + "') TO (SELECT FROM V WHERE Cid = '" + id2 + "')")
```

**Comment by wolf4ood** [comment]
Hi @malharT 

Did you define an index on the property `V.Cid` ?

Thanks

**Comment by malharT** [comment]
hey @wolf4ood 

No, I haven't yet. I'll try now.

**Comment by malharT** [comment]
Thanks! @wolf4ood 
The query is giving uniform performance now.
