### ISSUE TITLE
Issue with batch and WAL

### ISSUE THREAD

**Issue by Amitai-Madar** [orientechnologies/orientdb#8879]
## Expected behavior  
I ran an sql batch query to create several vertex and edges at once using graph api like this
"command(new OCommandScript("sql", query)).execute(objects)"
I run it again and again with different values ( but same set of actions)
the batch look like "begin\n create object\n create edge\n ........ commit\n"

## issue
after several iterations ( not a fixed number but it always happens) I get 
 "Magic number verification failed for page '26' of 'namespace.pcl'." when doing a select
and immediately after I get
"Following files and pages are detected to be broken ['namespace.pcl' :26;], storage is switched to 'read only' mode. Any modification operations are prohibited. To restore database and make it fully operational you may export and import database to and from JSON."
the page that broke is not always the same.
If I disable the WAL it works ( but that's not a solution...)
this is a prod DB so repairing ( which works btw) every time is not an option

I tried adding sleep time between each calls, I tried to connect remote and not local, to use a new connection for each call, to do smaller batch nothing helped.

Any idea?

Thanks

**Comment by laa** [comment]
Hi, that is an issue in the cluster it should be fixed in version 3.0.18 and later. Please try on this version. You need to either export/import data or migrate data manually on this version.

**Comment by laa** [comment]
You should not use the broken database you should re-create it from scratch.

**Comment by Amitai-Madar** [comment]
thanks for the fast answer.
since there are breaking changes between the version 2 and 3,
upgrading to 3.0 will not be easy for us. 
I there a way to workaround the issue?

**Comment by laa** [comment]
Sorry, no we cannot apply a patch to 2.2.x there are some architectural changes. Also, community 2.2.x is not supported any more. So I do suggest to migrate to 3.0.x any way.

**Comment by Amitai-Madar** [comment]
ok thanks a lot for your help

**Comment by laa** [comment]
Hi @Amitai-Madar any updates about this issue ?

**Comment by Amitai-Madar** [comment]
Since upgrading was too risky for us, I rolled back to a non batch approach (creating the vertex and edges one by one). way slower but works.
Thanks

**Comment by laa** [comment]
I see, thank you.
