### ISSUE TITLE
Question: UDF with recordId input parameter

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8883]
### Java Version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)  
### OS: centos07

Is there a way to have the input for a user-defined function a record ID? I'd like to simplify my queries by having parts of them as custom functions but I can't seem to get this to work. I've tried both js and sql-only functions. I suspect I am doing something wrong but I am not sure what.

Here's what I tried. (simplified to try to figure out how to use an rid as input) Using the console I created a function

name = simple
language = sql
idempotent = true
parameter = ridInput

content (I tried multiple variations here since I was unsure of the substitution syntax)

```sql
select * from [:ridInput]
```
error: Error on parsing query at position #12: Error on parsing query\nQuery:  [\"#63:5438\"]\n-----------------^\r\n\tDB name=\"local\"

```sql
select * from [?]
```
error: java.lang.ClassCastException: key should be a String

```sql
select * from [ridInput]
```
error: Error on parsing query at position #10: Error on parsing query\nQuery:  [ridInput]\n---------------^\r\n\tDB name=\"local\"

Is there a proper way to do this?

**Comment by luigidellaquila** [comment]
Hi @creisle 

I think the only viable solution here is to use a `SELECT expand(:ridParam)`, and if you need further elaboration, use it as a subquery: `SELECT ... FROM (SELECT expand(:ridParam))`

I hope it helps

Thanks

Luigi

**Comment by creisle** [comment]
Thanks @luigidellaquila . I am able to make this work now. However I cannot see the result when I test the function from the functionsManagement page. It always returns an empty list.

**Comment by creisle** [comment]
I'll make a separate issue for the results problem
