### ISSUE TITLE
Java 11 performance

### ISSUE THREAD

**Issue by thenesk** [orientechnologies/orientdb#8886]
### OrientDB Version: 3.0.19  

Does OrientDB work with Java 11?  If so, how does the performance and stability compare with Java 8?

**Comment by luigidellaquila** [comment]
Hi @thenesk 

Yes, OrientDB v 3.0.19 works fine in Java 11. 
In terms of stability, there is absolutely no difference.
We do not have an accurate comparison in performance between Java 8 and Java 11 unfortunately. For sure you will not have a performance degradation with java 11.

Thanks

Luigi

**Comment by tglman** [comment]
Hi,
As said we support java 11, closing
