### ISSUE TITLE
Class exists error, although it doesn't. Possible ghost transaction?

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8890]
## Expected behavior
Class creaated

## Actual behavior  
Exception thrown:
```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class news already exists
```  

## Steps to reproduce
Long story short: run the sql `create class news extends v`

Long story:
When my app (java) starts, it will try to create the class. Pretty much this way:
a. Create a pool (ODatabasePool)
b. acquire a session from the pool (pool.acquire())
c. call .createClass() method on the session

At the beginning I got an exception about changing the schema while inside a transaction. Note that although I do use the same sessions for transactions, I call .begin(), .commit() and .close() before trying to change the scheme.

After I got that exception, I kept getting the class already exist exception. I also ran `list classes` command through the console, and "news" class was not in the list (I tried to create the class after listing available classes)

My guess is:
(a) I'm probably not using ODatabasePool/sessions correctly, since it said I can't change the scheme while being in transaction, even though I wasn't in one. What am I missing here?
(b) Orient did try to create the class, and did it "half-way" or something like that. Since an exception was thrown, it didn't finish though, so the class exists "part-way".

p.s.
Found a known limitation regarding `reload schema`. Try that, class still doesn't show in `list classes`, and still throws an exception when calling `create class`

p.s. 2
Trying to drop the class through console with `drop class news`:
```
Error: com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: drop class news
        DB name="my_db"

Error: java.lang.IllegalArgumentException: Class 'news' not found in database
```

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

Just a couple of questions to better understand the context and reproduce:
- is the CREATE CLASS the first operation you do after creating the pool?
- is the problem reproducible and deterministic
- what if you restart the server? Does it start working properly or is the problem still there?

Thanks

Luigi

**Comment by matanshukry** [comment]
Hi @luigidellaquila 
- I'll assume you mean the resource acquired from the pool rather than the pool it self (since the pool has only acquire() method on it), and no, I'm doing .begin(), .commit() and .close() on the session acquired from the pool, then calling create class. The session is suppose to be reusable, and I closed it.. right?
- Yup, happens every time.
- It does, same thing that happens if I just wait a minute or 2 (timeout I guess). Keep in mind though hat "working properly" means I'm getting the exception again from the session.
