### ISSUE TITLE
Paginated Queries fail with ROUND_ROBIN_REQUEST

### ISSUE THREAD

**Issue by hrishirc** [orientechnologies/orientdb#8893]
## Expected behavior  
Should send request for OResultSet.hasNext() back to the original server.

## Actual behavior  
Sends request to a new server who can't find the 'query ' as it has been made on the server from which the first page has been fetched.

**Comment by tglman** [comment]
Hi,

This should already be fixed in a more recent version of 3.0.x. 

Closing
