### ISSUE TITLE
Regression - OnAfterCreate trigger fires before record save is completed

### ISSUE THREAD

**Issue by askorohod** [orientechnologies/orientdb#8898]
## Expected behavior  
The record id of the triggered record should be valid

## Actual behavior  
The record id of the triggered record has negative value - temporary id

This is a regression from version 2.2 where OnAfterCreate trigger works correctly.

**Comment by xavierdenis** [comment]
Hello,

I am trying to develop a plugin for db synchronization and this issue is a blocker.
Should be fixed asap
