### ISSUE TITLE
Fetch vertex by key value - low performance after addEdge operation

### ISSUE THREAD

**Issue by rafasantodomingo** [orientechnologies/orientdb#8900]
## Expected behavior  
Time to fetch vertex by key value was not affected by other operations in OrientDB 2.2.12 Graph API. The fact that the fetch-vertex operation was immediatly after an add-edge operation did not significantly worsen the performance of the former.
It was expected that the same occured in OrientDB 3.0.17 Tinkerpops 3 implementation.    

## Actual behavior  
Tests were carried out where 5 records of a particular class were fetched in a loop 100,000 times by using an indexed key. 
- In ODB 2.2.12 the average fetch time per record was ~0.5ms
- In ODB 3.0.17 TP3 the average fetch time per record was ~0.25ms

Additional tests were then performed to see the impact of add-edge operations on the fetch-vertex operations (see steps to reproduce). The results were:
- In ODB 2.2.12 the avergage fetch time per rectord retrieved after an add-edge operation was ~0.6ms
- In ODB 3.0.17 TP3 the average fetch time per record retrieved after an add-edge operation was ~40ms (that is, **almost 200 times slower than expected!**)

## Steps to reproduce  

- Define class "A" with indexed property "property" (index "A.property")
- Define edge "EdgeA" 
- Create 1,000,000 instances of A

- **Test 1: Just fetch-vertex operations:**

-- Fetch 5 A vertices by their "A.property" valule in a loop 100,000 times and get average fetch time per vertex
-- In OrientDB 2.2.12 vertices are fetched with graph.getVertices("A.property", value).iterator().next();
-- In OrientDB 3.0.17 TP3 vertices are fetched with: 
--- String query  = "SELECT FROM A WHERE property = ?";
--- graph.querySql(odbSqlSelection, value).stream().map(gr -> gr.getVertex().get()).findFirst().orElse(null);
-- The results show that OrientDB 3.0.17 TP3 gets vertices faster (0.25ms vs 0.5ms)

- **Test 2:  Fetch vertices after add-edge:**

-- Create three sets S1, S2, S3 of 1,000 "property" values each 
-- In a 1,000 size loop
--- Using property value from S1 fetch vertex v1
--- Using property value from S2 fetch vertex v2
--- Add edge v1.addEdge("EdgeA", v2)
--- Using property value from S3 fetch vertex v3
-- In OrientDB 2.2.12 all three vertices were fetched in ~0.6ms
-- In OrientDB 3.0.17 TP3, v1 & v2 were fetched in ~0.3ms & v3 in ~40ms

**Comment by ozgursucu** [comment]
I am also facing this issue too.

**Comment by laa** [comment]
Hi guys, please let me know if this issue still actual I will work on it.
