### ISSUE TITLE
Create edge with ODB SQL  - Low performance & exceptions in 3.0.17 TP3

### ISSUE THREAD

**Issue by rafasantodomingo** [orientechnologies/orientdb#8901]
## Expected behavior  
In OrientDB 2.2.12 we could read edge info (label, source id, target id) from external tables and produce ODB SQL commands to create edges in ODB very efficiently.
It was expected that the same could be done with OrientDB 3.0.17 TP3

## Actual behavior  
The ODB SQL commands created from the external tables were executed at an unacceptable speed (~10ms per command, compared to less than 1ms in OrientDB 2.2.12). The process also threw vague exceptions that did not appear in the same tests in OrientDB 2.2.12, nor did they appear when instead of using ODB SQL commands we changed to the v.addEdge() methods in OrientDB 3.0.17 TP3. The exceptions found were:

- **ODatabaseException: No Transaction Active.** This exception tends to happen when more than one edge connected to the same vertex was included within the same commit batch. Nevertheless, cases were identified where this pattern didn’t result on this exception. Given the lack of detailed information on the causes of the exception, the only way to partially cope with it is to catch the exception and log the commands affected by it. This obviously results in missing edges in OrientDB database.

- **OConcurrentModificationException.** This exception should not apply here, since only one client is accessing the server data. The easiest way to cope with it is to catch the exception and re-try the commit.

## Steps to reproduce  

- Create class "A", populate 1,000 instances and get the list of their @rids
- Create class "B", populate 1,000 instances and get the list of their @rids
- Create edge "EdgeC"
- Create external table (e.g. in CSV or RDBMS) with EdgeC instances linking "A" with "B" vertices
- Read table and create per row the ODB SQL command = "CREATE EDGE EdgeC FROM " + vertexAId + " TO " + vertexBId;
- Get the time per command execution
- Compare with OrientDB 2.2.12 and with execution times using vA.addEdge("EdgeC", vB);

**Comment by ozgursucu** [comment]
I am also facing this issue too.

**Comment by wolf4ood** [comment]
Hi @rafasantodomingo @ozgursucu 

do you have a simple java code to reproduce this issue?

Are you running this in transaction?

Thanks

**Comment by wolf4ood** [comment]
Also Which APIs are you using?

**Comment by rafasantodomingo** [comment]
package com.odb.test;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import org.apache.tinkerpop.gremlin.orientdb.OrientGraph;
import org.apache.tinkerpop.gremlin.orientdb.OrientGraphFactory;
import org.apache.tinkerpop.gremlin.structure.T;
import org.apache.tinkerpop.gremlin.structure.Vertex;

import com.orientechnologies.orient.core.index.OIndex;

public class Test_LoadEdgesWithOdbSql {
  
  private static final long COMMIT_SIZE = 1000;
  
  public static void main(String[] args) {
    
   String dbUri = "remote:localhost/";
    String dbName = "database";
    String user = "admin"; 
    String pwd = "admin";
    
    class EdgeInfo {
      String label;
      String sourceId;
      String targetId;
      EdgeInfo(String l, String s, String t) {
        label = l;
        sourceId = s;
        targetId = t;
      }
    }
    
    // Connect to graph DB
    System.out.println("Connecting to ODB database");
    OrientGraphFactory factory = new OrientGraphFactory(dbUri + dbName, user, pwd).setupPool(1,10);
    OrientGraph graph = factory.getTx();
    System.out.println();
    
    // Create Set<EdgeInfo>
    System.out.println("Create edgeInfos...");
    Set<EdgeInfo> edgeInfos = new HashSet<>();
    System.out.println("\tGet Vertices A");
    String getVerticesA = "SELECT FROM ClassA LIMIT 22479";
    List<Vertex> verticesA = graph.executeSql(getVerticesA).stream().map(gr -> gr.getVertex().get()).collect(Collectors.toList());
    System.out.println("\tLink to Vertices B");
    int i = 0;
    for (Vertex vAt : verticesA) {
      String name = (String) vA.property("Name").value();
      Vertex vB = getVertexByName(graph, name);      
      edgeInfos.add(new EdgeInfo("EdgeC", vA.id(), vB.id()));
      i++;
    }
    graph.commit();
    
    // Load edges
    System.out.println();
    System.out.println("Load Edges C");
    long totalTimeInMillis = 0;
    double averageTimeInMillis = 0;
    int count = 0;
    for (EdgeInfo edgeInfo : edgeInfos) {
      count++;
      String command = "CREATE EDGE EdgeC FROM " + edgeInfo.sourceId + " TO " + edgeInfo.targetId;
      Date date = new Date();
      graph.executeSql(command);
      long time = getLoadTime(date.getTime());
      totalTimeInMillis += time;
      if (totalTimeInMillis > 0) {
        averageTimeInMillis = totalTimeInMillis / (double) count;
      }
      System.out.println("Command " + command + " executed in " + time + " ms; Average time =  " + averageTimeInMillis + " ms");
      if (count % COMMIT_SIZE == 0) {
        graph.commit();
      }
    }
    
    graph.commit();
    
    // Print Results
    System.out.println();
    System.out.println("The total time in ODB3 was = " + totalTimeInMillis  + " ms");
    System.out.println("The average time in ODB3 was = " + averageTimeInMillis + " ms");
    System.out.println("Number of edges loaded = " + count);
    
    // Close graph
    graph.close();
  }
 
  private static Vertex getVertexByName(OrientGraph g, Name) {
    OIndex<Object> index = (OIndex<Object>) g.getRawDatabase().getClass("ClassB").getClassIndex("ClassB.Name");
    List<Object> list = new ArrayList<>();
    list.add(componentAlias);
    return g.getIndexedVertices(index, list.iterator()).findFirst().orElse(null);
  }
  
  private static long getLoadTime(long initialTimeInMillies) {
    long finalTimeInMillies = new Date().getTime();
    return finalTimeInMillies - initialTimeInMillies;
  }

}

**Comment by wolf4ood** [comment]
Hi @rafasantodomingo 


In ODB 2.2.x are you using SQL statement or using the api addEdge ?

Thanks

**Comment by rafasantodomingo** [comment]
Both, in different parts of the code. The thing is that the SQL statement has even better performance than the API addEdge in ODB 2.2.x

**Comment by wolf4ood** [comment]
@rafasantodomingo 

2.2.x sql statement were executed without transactional state of the server all. 
In 3.0.x  the statement are executed but the changes are saved at commit time.

in my machine with our code i do . 

```
The total time in ODB3 was = 781 ms
The average time in ODB3 was = 0.781 ms
Number of edges loaded = 1000
```

In your code you can reduce the execution time by using prepared statement

```
 String command = "CREATE EDGE EdgeC FROM :from TO :to";
      Date date = new Date();
      Map<String, Object> params = new HashMap<String, Object>() {{
        put("from", new ORecordId(edgeInfo.sourceId));
        put("to", new ORecordId(edgeInfo.targetId));
      }};
      graph.executeSql(command, params);
```

In this way the execution plan of the query is cached the first time and reused for each queries

Let me know if this improves

Thanks

**Comment by tglman** [comment]
Hi,

The difference in performance are depending on API use, so the right use of the API should bring similar performances.

Closing this
