### ISSUE TITLE
Edges direction confusion/bug + docs

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8902]
## Expected behavior  
To me it seems creating an edge from A to B should create an edge with A=in, and B=out.
```
+----+-------+--------+
|#   |in.name|out.name|
+----+-------+--------+
|0   |foo    |bar     |
+----+-------+--------+
```

## Actual behavior

```
+----+-------+--------+
|#   |in.name|out.name|
+----+-------+--------+
|0   |bar    |foo     |
+----+-------+--------+
```

## Steps to reproduce 
```
create class person extends v
create class friend extends e
create vertex person set name="foo"
create vertex person set name="bar"
create edge friend from (select from person where name="foo") to (select from person where name="bar")
select in.name,out.name from friend
```

## Suggested solution
I was a bit lazy to try an older version and see if it recently changed, since I remember it was working as I expected, but even if it always was like that it sounds counter-intuitive to me.

Either way I think it should be added to the documentation to clarify the issue and clear any confusion one might have.

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

This is not our choice, it is a standard convention in the graph databases, see Tinkerpop docs http://tinkerpop.apache.org/docs/current/reference/

Thanks

Luigi

**Comment by matanshukry** [comment]
@luigidellaquila That page is huge, can you link me to the specific part that shows that?
As far as I can tell in there, .out() is being used on vertices rather than edges, and the edges has .from() and .to(). Again though, it's a really long docs.

Either way though, I think it should at least be in the documentation. I don't think you expect people to know Tinkerpop before using OrientDB, so most users wouldn't know that either way.

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

See http://tinkerpop.apache.org/docs/current/reference/#vertex-steps in particular outV() and inV()

Thanks

Luigi

**Comment by matanshukry** [comment]
@luigidellaquila Honestly I still don't see it, I'm looking for a correlation between the outV(), inV() and the create command, such that creating an edge from <A> to <B> would result in outV() being <A> and inV() being <B>.

But I don't think it matters too much either way.
As I said, I don't have a problem with the decision - just with the fact that it's not in the OrientDB docs.
