### ISSUE TITLE
matches filter doesn't work when using match deep traversal

### ISSUE THREAD

**Issue by adepase** [orientechnologies/orientdb#8904]
### OrientDB Version: 2.2.23  
(using yet this version because of https://github.com/orientechnologies/spring-data-orientdb/issues/82#issuecomment-440965157 not yet answered and I cannot find a way to complete my porting to more recent versions)
### Java Version: 1.8.0_171
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11,
mixed mode)

## Expected behavior  
I have a database from which I can get this (correct) result :
![image](https://user-images.githubusercontent.com/6826606/59110256-0157ff80-893f-11e9-92ca-03817abeb064.png)
SQL: match {class:Knowledge, as:knowledge, where: (name like '%Napoleone%')}.out('ISA'){class:Knowledge, as:isa, where: (purePOS = 'RD APs noun')} return knowledge, isa

But this one doesn't (just changed the '=' in the where clause  with 'matches' - this is not my real match, but it's simpler to show the difference in behaviour, matching the same string as when using the '=' operator):
![image](https://user-images.githubusercontent.com/6826606/59110346-349a8e80-893f-11e9-8a05-b1d42c2979b6.png)
SQL: match {class:Knowledge, as:knowledge, where: (name like '%Napoleone%')}.out('ISA'){class:Knowledge, as:isa, where: (purePOS matches 'RD APs noun')} return knowledge, isa

**There is no error in the log.**

And the matches clause is not wrong (just matching at the first level, to see if the sintax was uncorrect - but it isn't)
![image](https://user-images.githubusercontent.com/6826606/59110397-572ca780-893f-11e9-80b5-37d11db65e20.png)
SQL: match {class:Knowledge, as:knowledge, where: (purePOS matches 'RD APs noun')} return knowledge

The expected behaviour was that the same match with '=' and 'matches' in the same match subquery, in the conditions shown above, returned the same result.

## Actual behavior  
The matches clause seems not to work in a deep (well, 1 level...) traversal match clause, while it works in the first level.

## Steps to reproduce  
See above

**Comment by adepase** [comment]
You can reproduce it with this very simple sequence:
create class Prova extends V
create vertex Prova set  id=1
create vertex Prova set  id=2, purePOS='RD APs noun'
create class ISA extends E
create edge ISA from (select from Prova where id=1) to (select from Prova where id=2)
**The following works:**
match {class:Prova, as:knowledge, where: (id=1)}.out('ISA'){class:Prova, as:isa, where: (purePOS = 'RD APs noun')} return knowledge, isa 
**The following doesn't work:**
match {class:Prova, as:knowledge, where: (id=1)}.out('ISA'){class:Prova, as:isa, where: (purePOS matches 'RD APs noun')} return knowledge, isa
**But the following works:**
match {class:Prova, as:knowledge, where: (purePOS matches 'RD APs noun')} return knowledge

**Comment by luigidellaquila** [comment]
Hi @adepase 

Thank you for reporting.
I'm testing it and I managed to reproduce a different problem in v 3.0, that I'm fixing now.
Then I'll check v 2.2.
In general, if you have a chance, I strongly suggest you to consider migrating to v 3.0, you will have a lot of advantages in terms of stability

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @adepase 

I pushed a fix for the problem in v 3.0, now it works fine.
Checking v 2.2 now

Thanks

Luigi

**Comment by adepase** [comment]
Waiting for your check.
I really would like to migrate to v 3.0, I already tried it at the very first date of GA release. But I could not succeed, until now, since I cannot find a repository to download spring-boot-orientdb-autoconfigure for version 3.X with Gradle (as already stated at the beginning of this thread, with a cross-link in the version part). I know that was another thread, but it would be very kind if you can answer also that one or give me an hint to find the above mentioned repository.
Thank you in advance
Alessandro

**Comment by luigidellaquila** [comment]
Hi @adepase 

I just pushed a fix for this problem, the snapshot will be available in a few minutes.

Closing, please feel free to re-open if you see further problems

Thanks

Luigi
