### ISSUE TITLE
(please..)infinite error: java.lang.IllegalArgumentException: COLLATE cannot be null

### ISSUE THREAD

**Issue by efenzha** [orientechnologies/orientdb#8906]
## Expected behavior  
connect to database without ERROR log

## Actual behavior  
ERROR log is reported, but can connect to database successfully

## Steps to reproduce  
1. create a new database from console.
2. create a new vertex type from code, and set an index.
3. connect to this database, then it reports lots of "java.lang.IllegalArgumentException: COLLATE cannot be null" every time.

every time, every time, every time, every time for every Index, even for class OFunction

**Comment by luigidellaquila** [comment]
Hi @efenzha 

Could you please post a SQL script to reproduce it exactly?

Thanks

Luigi

**Comment by efenzha** [comment]
Hi @luigidellaquila ,

The ERROR is logged when connectiong to database from code:
`val graph = new OrientGraphNoTx(dbUrl)`

How to create a "SQL script" to reproduce it?

**Comment by luigidellaquila** [comment]
Hi @efenzha 

I just need the exact commands you execute in console

Thanks

Luigi

**Comment by efenzha** [comment]
Hi @luigidellaquila ,

but it has no relation with console, the error is printed when running **the code** `val graph = new OrientGraphNoTx(dbUrl)`

Did I misunderstand your meaning?

**Comment by luigidellaquila** [comment]
Hi @efenzha 

- create a new database from console.

OK

- create a new vertex type from code, and set an index.

how do you create a vertex type if you still did not connect to the db? Are you using the console? Studio? Which is the sequence of commands you are executing?

- connect to this database, then it reports lots of "java.lang.IllegalArgumentException: COLLATE cannot be null" every time.

Java connection? From remote or plocal?

Thanks

Luigi

Luigi

**Comment by efenzha** [comment]
Hi @luigidellaquila ,

- create a new vertex type from code, and set an index.
`
val graph = new OrientGraphNoTx(dbUrl)

    try {
      if (graph.getVertexType("EiffelEvent") == null) {
        graph.command(new OCommandSQL("ALTER DATABASE DATETIMEFORMAT \"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\"")).execute()

        val eType = graph.createVertexType("EiffelEvent")

        eType.createProperty("eventId", OType.STRING)
        eType.createProperty("eventType", OType.STRING)
        eType.createProperty("eventTime", OType.DATETIME)
        eType.createProperty("stage", OType.STRING)
        
        eType.createProperty("moreInfo", OType.STRING)
        eType.setOverSize(3)

        graph.createKeyIndex("eventId", classOf[Vertex], new Parameter("type", "UNIQUE"), new Parameter("class", "EiffelEvent"))
      }

      if (graph.getEdgeType("inputEventId") == null) {
        graph.createEdgeType("inputEventId")
      }
    }
    finally {
      graph.shutdown()
    }
`

- connect to this database
`
val graph = new OrientGraphNoTx(dbUrl)
`

- orientDb url
`
orientdb.iurl=remote:ssekilxv7869.rnd.ericsson.se/fromMongo1
`

**Comment by luigidellaquila** [comment]
Hi @efenzha 

Thank you very much.
So you are using the legacy TinkerPop 2.6 API, is there any specific reason for doing it?

If you have a chance I strongly suggest you to use the MultiModel API https://orientdb.com/docs/3.0.x/java/Java-MultiModel-API.html

(or in case the new TinkerPop 3).

I have to double-check it, but I suspect the problem is due to the usage of the usage of the index APIs and how the legacy API uses them. I'd suggest to replace the API call with a simple SQL statement:

```
CREATE INDEX EiffelEvent.eventId on EiffelEvent (eventId) UNIQUE
```

It should solve the problem

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Oh, and please double-check that the client and server have the exact same version (eg. both 3.0.18), as it could lead to such kind of problems

Thanks

Luigi

**Comment by efenzha** [comment]
Hi @luigidellaquila ,

Yes, SQL solves this problem perfectly! Thanks!

I am using  2.6 API since I follow orientdb java api examples. Maybe I need to use this multi model api, it sounds better.
