### ISSUE TITLE
How to use CONTAINS inside LET block?

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8909]
### OS: 10.14.4  

- There are two tables `TableA` and `TableB`.
- `TableA` has `fieldOne` column of LINKSET type containing records of `TableB`.
- `TableB` has `otherField` column of BOOLEAN type.

I would like to get information in `$testVar` whether there are records in the `TableA` which are linked via `fieldOne` to the records of `TableB` where `otherField=true`.

The other option, I figure is :
```
SELECT $testVar FROM `TableA` LET $testVar = ( 
SELECT * FROM `TableB` WHERE @rid IN $parent.$current.fieldOne AND otherField=true
)
```
The result is what I expected but that is absolutely slow, unacceptable.

**Is there other faster solution on how to achieve that, please?**

maybe, something like this :
```
SELECT $testVar FROM `TableA` LET $testVar = ( 
$parent.$current.fieldOne CONTAINS (otherField=true) 
)
```
But it results in : `Error parsing query`

Thank you for your ideas in advance.

**Comment by luigidellaquila** [comment]
Hi @petervavro 

This seems extremely convoluted and inefficient... 
Why don't you just write it as a simple expression:

```
SELECT expand(fieldOne[otherField = true]) FROM TableA
```

Thanks

Luigi

**Comment by petervavro** [comment]
Hi @luigidellaquila,

Thank you for your reply. In my case, the condition is a little more complicated e.g. :
`(otherField = true OR (fieldX > 24 AND fieldY = 4))`

But, I figured it is possible to do this:
```
SELECT fieldOne[(otherField = true OR (fieldX > 24 AND fieldY = 4))] FROM `TableA`;
```
and that seems to solve my problem. Thank you!
