### ISSUE TITLE
v3.0.20 : how avoid many log messages about 'native Linux API'

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8911]
## Expected behavior  
Do not display continuously the log messages about native Linux API when extra clusters get opened:
```
...
2019-06-17 22:35:53:042 WARNI Can not allocate space (error 95) for file /opt/orientdb/databases/cdrarch/cl_cdr_af_20181028_p4_4111.cpm using native Linux API, more slower methods will be used [OFileClassic]
...
```

## Actual behavior  
Polluting log messages.

## Steps to reproduce  
1) Install ZFS as disk volume manager
2) create a ZFS volume and mount it on e.g. "/opt/orientdb/databases"
3) point the "databases" subdir of the OrientDB installation to this ZFS mountpoint
4) startup the server and access or create a new database, e.g. "cdrarch"
5) let a client connect and access this dbase; the logs will be displayed by the server

**Comment by laa** [comment]
You can disable this logging, just by disabling logging for the "com.orientechnologies.orient.core.storage.fs.OFileClassic" logger in Java Logging Framework. 
It can be done by setting of JUL property, for example:
`com.orientechnologies.orient.core.storage.fs.OFileClassic.level = SEVERE`

**Comment by rdelangh** [comment]
hi @laa,
1) thx for your swift feedback !
2) what is a "JUL property" ?
3) how do I set such a property ?

**Comment by laa** [comment]
Hi @rdelangh , because you use server configuration, you should add this property to the orientdb-server-log.properties .

**Comment by rdelangh** [comment]
ok done, no more such logs.
thx @laa !
