### ISSUE TITLE
[SQL Question] Find all vertices between 2 vertices

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8913]
### OS: Windows 10

I need to find all the vertices that exist between 2 specific vertices.
Of course, assuming there is an edge that connects between them.

e.g. 

```
CREATE VERTEX Person
CREATE PROPERTY Person.id STRING

CREATE EDGE Friend
CREATE PROPERTY Friend.createdAt LONG
```

Example query:
```
SELECT both("Friend").both("Friend")[id = "targetUser"] FROM Person WHERE id="sourceUser"
```

However, that query will return the targetUser. I actually want to find all the `Person` vertices that are between 'sourceUser' and 'targetUser'

(In a different count I only need to know how many, if it matters)

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

This is the typical use case for a MATCH statement:

```
MATCH
  {class:Person, where:(id = 'sourceUser').both(){as:thePerson}.both(){class:Person, where:(id = 'targetUser')}
RETURN $elements
```

Thanks

Luigi

**Comment by matanshukry** [comment]
Awesome, I didn't even know about it!

extra:
1. Just for anyone else who needs it, you missed a '}'. The fixed query:
```
MATCH {class:Person, where:(id = 'sourceUser')}.both(){as:thePerson}.both(){class:Person, where:(id = 'targetUser')} RETURN $elements
```

2. I would recommend adding a link to the MATCH command from the TRAVERSE command; something like 'See Also'.
