### ISSUE TITLE
[SQL Question] UPDATE a record with MATCH (+return too) ?

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8918]
### OS: Windows 10

Is there a way to update a record that is found by using match operator?
Specifically, I need to update an edge between user A and user B (parameters are ids), and return the updated edge and user B.
I tried the following query:
```
UPDATE EDGE (MATCH {class: Person, where:(userId="matan")}.bothE("friend"){as:edgeData, where:(status=1)}.bothV("Person"){where:(userId="bulu")} RETURN edgeData) SET status=2 RETURN AFTER $current:{*} as edgeData
```

I'm getting the following exception though:
```
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: record {
edgeData: #49:0
}
 is not an instance of E
	DB name="mydb"
	DB name="mydb"
```

Just to clarify, record #49:0 is an edge of type 'friend' which does inherit from E.

Also, note that my current query doesn't return the friend (in this case it would be `bulu`). Not sure how to do that either.

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

Just replace ` RETURN edgeData` (that return edgeData RID) with ` RETURN expand(edgeData)` and you should be good ;-)

Thanks

Luigi

**Comment by matanshukry** [comment]
@luigidellaquila awesome, that does work!

What about returning the other friend? I thought about this:
```
UPDATE ... RETURN AFTER $current:{*} as edgeData, $current.bothV("Person")[userId="bulu"][0] as friend
```
And it does seem to work, but it seems a bit wrong since I already have him in the Match, and also because I'm using the `[0]` operator, which seems a bit wrong.

Is there any other way to do that?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

The UPDATE is designed to work on a single record at once, so even if you have it in the MATCH, you cannot propagate it to the RETURN of the UPDATE. I'm afraid there is no better solution for now

Thanks

Luigi

**Comment by matanshukry** [comment]
@luigidellaquila Is there any other solution that is not implemented yet, with hopefully and issue I can follow up on?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

Not in this case, it is by design, so I'm afraid we cannot do much on this

Thanks

Luigi
