### ISSUE TITLE
[SQL UPDATE] Field name with dash (-) char Eg domain-profile

### ISSUE THREAD

**Issue by jayaramcs** [orientechnologies/orientdb#8919]
## Expected behavior  
Per this [link ](https://orientdb.com/docs/3.0.x/release/3.0/What-is-new-in-OrientDB-3.0.html), the Property names can now contain any character, including blank spaces, dots, brackets and special characters.

## Actual behavior  
Error when running the following from studio as well as code.

update mytable set domain-profile ="awesome" where id=1

I am upgrading from 2.x and we are using this field name already. kindly advice.

**Comment by luigidellaquila** [comment]
Hi @jayaramcs 

That's correct, field names can contain any character, but if you use special characters (different from letters, numbers, "\$" and "_") you have to quote them with back-ticks in SQL:

```
update mytable set `domain-profile` ="awesome" where id=1
```

The `-` character is particularly critical, as it represents the subtraction, eg. in your case, if you had two numeric properties, `domain` and `profile`, your query would do the subtraction of the two

Thanks

Luigi

**Comment by jayaramcs** [comment]
Thanks for the quick reply @luigidellaquila . 
it works now! I had not tried with the back-ticks.
