### ISSUE TITLE
How do I remove a certain element of a list?

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8921]
### OS: 10.14.4

My query is : `SELECT fieldWithIds FROM TableA;` where `fieldWithIds` is of LINKLIST type. Let's say it contains e.g. [#20:1,#20:2,#20:3,#20:4].

Is there a way to remove the element with index number 2 to get [#20:1,#20:2,#20:4]?

Thank you !

**Comment by luigidellaquila** [comment]
Hi @petervavro 

If you know the position of the item, then you can use square bracket filters (http://orientdb.com/docs/3.0.x/sql/SQL-Syntax.html#square-bracket-filters)

```
UPDATE TableA SET fieldWithIds = fieldWithIds[0..2] || fieldWithIds[3..1000000]
```

Thanks

Luigi
