### ISSUE TITLE
[SQL] Delete Edge + Match

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8922]
### OS: Windows 10

Is there anyway to combine a delete statement with a match statement? I tried the following:
```
DELETE EDGE (MATCH {class: Person, where:(id="matan")}.inE("friend"){as:edgeData, where:(status=2)}.outV("Person"){where:(id="bulu")} RETURN expand(edgeData))
```

But I'm getting an exception:
```
DELETE EDGE (MATCH ...
                      ^
Encountered " "(" "( "" at line 1, column 13.
Was expecting one of:
```
Note: the ^ sign points to '('

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

That syntax is not supported, you have to re-write the query as follows:

```
DELETE EDGE WHERE @rid in (MATCH {class: Person, where:(id="matan")}.inE("friend"){as:edgeData, where:(status=2)}.outV("Person"){where:(id="bulu")} RETURN expand(edgeData))
```

In general, that syntax makes sense, so I'll see if I can support it

Thanks

Luigi

**Comment by matanshukry** [comment]
Awesome, works! :)
