### ISSUE TITLE
What are the differences between Orientdb Enterprise Edition and Community Edition

### ISSUE THREAD

**Issue by czs1993** [orientechnologies/orientdb#8927]
Where can I find the difference between the enterprise version and the community version of OrientdB? 
suchu as Feature Matrix or other comparative forms.

**Comment by luigidellaquila** [comment]
Hi @czs1993 

Here you can find all the features available in OrientDB Enterprise

https://orientdb.com/orientdb-enterprise/

In particular, this is the list of features that is specific of EE:

- 24/7 Production Support Round-the-clock**
- Quick Priority Issue Resolution with SLA
- Non-Stop Incremental Backup and Restore
- Query Profiler
- Live Monitor
- Metrics Recording
- Full Auditing Capabilities


Thanks

Luigi

**Comment by czs1993** [comment]
Thank you very much for your answer!
