### ISSUE TITLE
Question: How to get content of selected record in javascript UDF

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8937]
### Java Version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)  
## Expected behavior  
I am not sure if this is possible, but I would like to be able to grab a record by ID, then based on its content, return some string representation

## Actual behavior  
It only returns the RID and I can't access the properties

## Steps to reproduce  

In the function editor. With an input paramter named ridParam
```js
var record = orient.getDatabase().query('SELECT expand(?)', ridParam);
return record[0].name;  // also tried record.name
```
then call the function with an rid of a record we know has the name property

```sql
select getName(85:1)
```

this is always null. Am I doing something incorrectly?

**Comment by luigidellaquila** [comment]
Hi @creisle 

Sure, you just have to change the following:

```
return record[0].getProperty("name");
```

Thanks

Luigi

**Comment by creisle** [comment]
yup! that works. Thank you!
