### ISSUE TITLE
Database is not encrypted when using Java 3.0.19 API

### ISSUE THREAD

**Issue by WarpPL** [orientechnologies/orientdb#8941]
## Expected behavior  
Database should be encrypted at file-level when using Java 3.x API (OrientDB.createIfNotExists(..))

## Actual behavior  
STORAGE_ENCRYPTION_METHOD and STORAGE_ENCRYPTION_KEY config keys are ignored, database is created but stays unencrypted.
Also creation encrypted db using deprected api works, but that db cannot be opened using new API.

## Steps to reproduce  
//==================
//In new API:
//==================

			//encryption config values are ignored, db stays unencrypted

			private static final String ENC_KEY = "T1JJRU5UREJfSVNfQ09PTA==";
			private static final String EAC_DB_NAME = "TestDb";
			private static final String ENC_METHOD = "aes";
			
			orient.createIfNotExists(
                    EAC_DB_NAME,
                    ODatabaseType.PLOCAL,
                    OrientDBConfig.builder()
                            .addConfig(OGlobalConfiguration.STORAGE_ENCRYPTION_METHOD, ENC_METHOD)
                            .addConfig(OGlobalConfiguration.STORAGE_ENCRYPTION_KEY, ENC_KEY)
                            .build());

            try (ODatabaseSession session = orient.open(EAC_DB_NAME, "admin", "admin",
                    OrientDBConfig.builder()
                            .addConfig(OGlobalConfiguration.STORAGE_ENCRYPTION_METHOD, ENC_METHOD)
                            .addConfig(OGlobalConfiguration.STORAGE_ENCRYPTION_KEY, ENC_KEY + "InvalidKey") //FIXME Test if provided key is verfied (is not!)
                            .build())) {

                return session;
            }

//==================
//Mixed old API and new API:
//==================

            //Db creation with old API
            ODatabaseDocumentTx db = new ODatabaseDocumentTx("plocal:"+ OrientConfiguration.orientDbHomeDirStatic + "/databases/temp3_enc");
            db.setProperty(OGlobalConfiguration.STORAGE_ENCRYPTION_METHOD.getKey(), "aes");
            db.setProperty(OGlobalConfiguration.STORAGE_ENCRYPTION_KEY.getKey(), "T1JJRU5UREJfSVNfQ09PTA==");
            db.create();

            db.command(new OCommandSQL("create class TestEncryption")).execute();
            db.command(new OCommandSQL("insert into TestEncryption set name = 'Jay'")).execute();

            List result = db.query(new OSQLSynchQuery<ODocument>("select from TestEncryption"));
            db.close();

            //Old API opening - works
            db.open("admin", "admin");
            OStorage storage = ((ODatabaseDocumentInternal) db).getStorage();
            db.close();
            storage.close(true, false);

            db.setProperty(OGlobalConfiguration.STORAGE_ENCRYPTION_KEY.getKey(), "T1JJRU5UREJfSVNfQ09PTA==");
            db.open("admin", "admin");
            result = db.query(new OSQLSynchQuery<ODocument>("select from TestEncryption"));
            LOG.warn("result size (should be 1): " + result.size());
            LOG.warn("result value (should be \"Jay\"): " + result.get(0).toString());
            storage = ((ODatabaseDocumentInternal) db).getStorage();
            db.close();

            storage.close(true, false);

            //New API
            //throws: Suppressed: com.orientechnologies.orient.core.exception.OSecurityException: AES encryption has been selected, but no key was found. Please configure it by passing the key as property at database create/open. The property key is: 'storage.encryptionKey'
            try (ODatabaseSession session = orient.open("temp3_enc", "admin", "admin",
                    OrientDBConfig.builder()
                            .addConfig(OGlobalConfiguration.STORAGE_ENCRYPTION_METHOD, ENC_METHOD)
                            .addConfig(OGlobalConfiguration.STORAGE_ENCRYPTION_KEY, "T1JJRU5UREJfSVNfQ09PTA==")
                            .build())) {
            }

**Comment by WhoNeedszZz** [comment]
I'm still having this issue today. Why has there been no resolution on this obviously critical issue?

**Comment by laa** [comment]
The first test is incorrect, you already opened storage during createIfDoesNotExist method, AES key is used only once during storage opening/creation and can not be replaced till the next storage close. Checking the second test.

**Comment by laa** [comment]
The second test passed both with invalid and valid way.

**Comment by laa** [comment]
Closing the issue as invalid.

**Comment by laa** [comment]
Sorry checked under the 3.1 version. Let me check on 3.0

**Comment by laa** [comment]
Has got the same result on 3.0.33 version. Closing as invalid.
