### ISSUE TITLE
Nested projection: how to select only Links and not direct properties

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8942]
### Java Version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
## Expected behavior  
not sure if this is expected behaviour or not. But I was hoping to have a projection where I could expand the links without selecting any of the immediate properties. Using the demodb

```sql
select in_IsFromCountry:{!*, *:{*}} from Countries
select @this:{!*, *:{*}} from Countries
select @this:{*:{*}} from Countries
```

I was expecting any of the above to return expanded edges/links but no direct properties. Is there a way to achieve this?

## Actual behavior  

the result contains the direct properties

## Steps to reproduce  
selecting a single record to show a simple result
```sql
select @this:{*:{*}} from Countries where both().size() > 0 limit 1
```
the result contains the direct properties
```json
{
    "result": [
        {
            "@this": {
                "in_IsFromCountry": [
                    {
                        "in": "#48:2",
                        "out": "#201:2"
                    },
                    {
                        "in": "#48:2",
                        "out": "#193:24"
                    }
                ],
                "Id": 27,
                "Code": "BM",
                "Name": "Bermuda"
            }
        }
    ],
}
```
For the above I wasn't expecting Id, Code, or Name to be in the result

**Comment by luigidellaquila** [comment]
Hi @creisle 

I'm afraid there is no way to do it with nested projections.
What you can try to do is 

```
select @this.values()[@class is not null]:{*} as a from V
```

Thanks

Luigi

**Comment by creisle** [comment]
ok. Is this something that would be a reasonable feature to request? so that something like

```sql
select !*, *:{*} from Countries
```

could be used? (once top-level ! operator is added?)

**Comment by luigidellaquila** [comment]
Hi @creisle 

In general it's something we can consider, but I think we have to find a reasonable syntax

Thanks

Luigi

**Comment by creisle** [comment]
@luigidellaquila , that makes sense. thanks for getting back to me!
