### ISSUE TITLE
Several minor (and one major) issues regarding non-simplified names

### ISSUE THREAD

**Issue by muneebshere** [orientechnologies/orientdb#8943]
## Expected behavior  
Non-simplified identifiers (those with spaces and other characters) should be treated exactly as simplified identifiers when they are properly qualified with back-ticks (``).

## Actual behavior  
There are several ways in which this is not true, one of which is quite problematic. In order of least to most priority:

1. When creating a property from Java API using `OClass.createProperty()`, the function rejects non-simplified identifiers when properly qualified with back-ticks. <br> <br> This will work:
`OClass.createProperty("First Name", ...)` <br> <br> This will fail:
``OClass.createProperty("`First Name`")`` <br> <br> This seems to be because the function itself qualifies ALL identifiers - simplified or not - with back-ticks, so a name that already has them will then look like \`\`First Name\`\`, which is not a valid identifier. A simple fix would be to check whether an identifier is already surrounded with `` before surrounding it.

2. The Java API does not recognise identifiers properly qualified with back-ticks. If a class called `Customer` has a property called `` `First Name` ``:  <br> <br> This will return true:
`customerClass.existsProperty("First Name")` <br> <br> This will return false:
``customerClass.existsProperty("`First Name`")`` <br> <br> They should both return true.

3. As covered in the previous issue (https://github.com/orientechnologies/orientdb/issues/8761), it was previously not possible to create indexes on properties with non-simplified names. Since the 3.0.18 release, it has been possible to do so through SQL commands, i.e.  <br> <br> ``create index Name on Customer ( `First Name`, `Last Name` ) UNIQUE STRING, STRING``  <br> <br> It is STILL not possible to do so through the Java API. For example:  <br> <br> (a) ``customerClass.createIndex("Name", "Unique", (OProgressListener)null, (ODocument)null, "`First Name`", "`Last Name`")`` and <br> <br> (b) `customerClass.createIndex("Name", "Unique", (OProgressListener)null, (ODocument)null, "First Name", "Last Name")`  will both throw exceptions, though for different reasons. (a) will throw an exception because `existsProperty()` will return false, and (b) will throw an exception because the invocation gets translated into the SQL command:  <br> ``create index Name on Customer ( First Name, Last Name ) UNIQUE STRING, STRING``, i.e. WITHOUT the back-ticks, which makes it an invalid command. The reason for this is that `createIndex()` obtains field names from the `OIndexDefinition`, where they are stored as `"First Name"` and `"Last Name"` respectively, i.e. without back-ticks. <br> <br> A simple fix would be to surround field names with back-ticks after getting them from `OIndexDefinition`. It would not even be necessary to check whether the identifier is simplified or not, because it would be valid in both cases with back-ticks.

**Comment by muneebshere** [comment]
@luigidellaquila

**Comment by luigidellaquila** [comment]
Hi @muneebshere 

The back-tick quoting is specific ti SQL syntax, it does not apply to the java API in general (there would be no reason for this, in Java you have no ambiguity, you just have a single string for a class/property/index name)

Thanks

Luigi

**Comment by muneebshere** [comment]
@luigidellaquila 
As I said, 1 and 2 are minor inconsistencies, but they lead to 3, which IS a problem. It is still not possible to create an index on non-simplified field names from Java API, because Java API converts it to an SQL query and executes it, and the query produced doesn't have back-ticks, so it throws an error.

**Comment by luigidellaquila** [comment]
Hi @muneebshere 

I see, I'd say it needs a fix.
I'll check it ASAP and let you know

Thanks

Luigi

**Comment by muneebshere** [comment]
@luigidellaquila 
And moreover, while it is correct that Java API doesn't need back-ticks, the proper way to handle that would be to not require back-ticks, but allow them nevertheless. So `customerClass.existsProperty("First Name")` should be fine, but so should ``customerClass.existsProperty("`First Name`")``.

**Comment by muneebshere** [comment]
@luigidellaquila 
So, all in all, I propose two fixes with minimum impact on the existing code base:

1. For the minor issue of being indifferent rather than rejecting of back-ticks where SQL syntax requires them, remove any existing surrounding back-ticks from user supplied identifiers, i.e. in the case of both ``OClass.createProperty("`First Name`")`` and ``customerClass.existsProperty("`First Name`")`` and any other such instances in the API, the provided identifier should be subjected to something like ``String.removeSurrounding('`')`` (this is an extension function in Kotlin) before further processing. Just adding this call first thing in the method at all such occurrences in the code should be sufficient to accept back-tick qualified names without interfering with the already established working of the API. I quote an example of the solution from the code (`OClassImpl.java`):

````
@Override
  public boolean existsProperty(String propertyName) {
    removeSurroundings(propertyName, '`') // removeSurroundings(String, Char) would have to be implemented in Java
    acquireSchemaReadLock();
    try {
      boolean result = properties.containsKey(propertyName);
      if (result)
        return true;
      for (OClassImpl superClass : superClasses) {
        result = superClass.existsProperty(propertyName);
        if (result)
          return true;
      }
      return false;
    } finally {
      releaseSchemaReadLock();
    }
  }
````

2. For the more major issue of indexes not being created, when obtaining field names from `OIndexDefinition` surround them with back-ticks before injecting them into the query. The edited code below is from `OCompositeIndexDefinition.java`. The idea is that back-ticks in a query can't hurt where they're not needed (i.e. simplified identifiers), so add them without checking.

````
public String toCreateIndexDDL(final String indexName, final String indexType, String engine) {
    final StringBuilder ddl = new StringBuilder("create index ");
    ddl.append(indexName).append(" on ").append("`").append(className).append("`").append(" ( "); // original: ddl.append(indexName).append(" on ").append(className).append(" ( ");

    final Iterator<String> fieldIterator = getFieldsToIndex().iterator();
    if (fieldIterator.hasNext()) {
      ddl.append("`").append(fieldIterator.next()).append("`"); // original:  ddl.append(fieldIterator.next());
      while (fieldIterator.hasNext()) {
        ddl.append(", ").append("`").append(fieldIterator.next()).append("`"); // original:  ddl.append(", ").append(fieldIterator.next()); 
      }
    }
    ddl.append(" ) ").append(indexType).append(' ');
````

**Comment by muneebshere** [comment]
@luigidellaquila 
While unrelated to the current issue, could you please see to that the Javadoc remains updated? The /latest port of Javadoc at https://orientdb.com/javadoc/ shows OrientDB 2.2.32-SNAPSHOT API (which is the same as the /2.2.x port incidentally) where it should probably show 3.0.22 and the /develop port shows OrientDB 3.0.0-SNAPSHOT API, which is better that 2.2.32, but still, shouldn't it be reflecting even more current changes than 3.0.22?

**Comment by muneebshere** [comment]
@luigidellaquila 
Any progress?
