### ISSUE TITLE
[Console] List sequences?

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8944]
### OS: Windows 10

I couldn't find any way to list the available sequences. Is that a missing documentation or a missing feature?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

A sequence is represented as a simple document in the DB, so you can easily list them with a query:

```
select from OSequence
```

Thanks

Luigi

**Comment by matanshukry** [comment]
Cool, thanks!
