### ISSUE TITLE
Object API does not propagate cascade save over Set fields

### ISSUE THREAD

**Issue by fuss86** [orientechnologies/orientdb#8947]
## Expected behavior  
Update/removal on `Set` object should work in the cascaded way.

## Actual behavior  
Update/removal on `Set` object does not work in the cascaded way.

## Steps to reproduce  
Thanks to https://github.com/orientechnologies/orientdb/commit/9538c7902c9aa5c5a0713de7a8e53256a02ee914 https://github.com/orientechnologies/orientdb/issues/8272 has been fixed. Unfortunately it does not work in the cascaded way.  

Integration test for 3.0.X can be found [here](https://github.com/fuss86/orientdb-tryouts/blob/master/3.0.x/src/test/java/com/compart/tec/orientdb/object/PropagateRemoveOnSetFieldIT.java).

It also doesn't work in [2.2.X ](https://github.com/fuss86/orientdb-tryouts/blob/master/2.2.x/src/test/java/com/compart/tec/orientdb/object/PropagateRemoveOnSetFieldIT.java).

**Comment by steve-todorov** [comment]
@luigidellaquila as the author of the fix for #8272 - would you, perhaps, have any ideas on how this can be fixed or if it's being worked on?

**Comment by carlspring** [comment]
@luigidellaquila : Any updates on this?

**Comment by steve-todorov** [comment]
@luigidellaquila, @tglman, @laa guys could we get an update on this issue? :)

**Comment by fuss86** [comment]
@lvca,  any chances to take a look ?

**Comment by carlspring** [comment]
We would like to upgrade to a newer version of OrientDB, but we're hitting this issue. Any chance you guys could have a look at this and prioritize it?

**Comment by fuss86** [comment]
I bet they took a veeeerrryyy long vacation time ;)

**Comment by carlspring** [comment]
@lvca , @luigidellaquila, @tglman, @laa, @wolf4ood .

Would anyone at all care to give us some sort of update...? Is this being looked at? Are there any known workarounds? Any hints, or advice...?

**Comment by luigidellaquila** [comment]
Hi guys,

Sorry for the long silence, the Object API for now is low priority in the roadmap.
Unfortunately I do not have a work-around to propose... I'll try to check it when I have a moment

Thanks

Luigi

**Comment by carlspring** [comment]
@luigidellaquila ,

Any luck with this? Have you had a chance to take a look? :)
