### ISSUE TITLE
[Question] Create simple direct link (foreign key) - how? (+little console bug)

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8952]
### OS: Windows 10

I'm trying to create a simple direct link between 2 classes, same as a foreign key. Link seems to be the answer, but I can't get it to work; or perhaps I'm not sure what it's supposed to do, since I'm expecting an RDBMS behavior?

The current SQL:
```
CREATE CLASS City EXTENDS V
CREATE PROPERTY City.code STRING
CREATE PROPERTY City.name STRING

CREATE VERTEX City SET code="eilat",name="Eilat"
CREATE VERTEX City SET code="tlv",name="Tel Aviv"


CREATE CLASS Person EXTENDS V
CREATE PROPERTY Person.name STRING
CREATE PROPERTY Person.age INTEGER
CREATE LINK personCity TYPE LINK FROM Person.City to City.code

CREATE VERTEX Person SET name="Danny",age=24,city="eilat"
CREATE VERTEX Person SET name="Matan",age=26,city="tlv"
CREATE VERTEX Person SET name="BadHacker",age=0,city="non-existing-city"

SELECT name,city.name FROM Person
```

Obviously, the last line will return null. If I'll query all Persons:
```
+----+------+------+---------+----+-----------------+
|#   |@RID  |@CLASS|name     |age |city             |
+----+------+------+---------+----+-----------------+
|0   |#137:0|Person|Danny    |24  |eilat            |
|1   |#138:0|Person|Matan    |26  |tlv              |
|2   |#139:0|Person|BadHacker|0   |non-existing-city|
+----+------+------+---------+----+-----------------+
```

am I mistaken what a Link is? I guess I can probably set the city property to the actual record with a sub-select, but is that what I'm supposed to do? and even if so, shouldn't the create property disallow any other property value?

p.s.
There's another client-side issue in the console with create link. It throws an exception. This seems to be client side only though, due to a simple format bug. The exception:
```
Error: java.util.IllegalFormatConversionException: d != java.util.ArrayList
```

The problematic line:
https://github.com/orientechnologies/orientdb/blob/develop/tools/src/main/java/com/orientechnologies/orient/console/OConsoleDatabaseApp.java#L664

Specifically the first argument, which the code expect to be the number of links, although it is actually the link it self. Args as seen by inspection:
```
0 = {ArrayList@2443}  size = 1
 0 = {ODocument@2465} "{operation:create link,name:personCity,fromClass:Person,toClass:City}"
1 = {Float@2449} 1.237
```

As far as I can tell though, this happens after the operation was successful, so it shouldn't change anything else said above.

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

The CREATE LINK statement does not define a foreign key, but it just creates links from existing data. If you launch it on empty classes, it just does nothing.

If you need to create links/linksets, you have to use UPDATE or INSERT statements as follows:

```
UPDATE ADocument SET theProperty = #12:0; /* the RID of the linked object */

UPDATE ADocument SET theProperty = (SELECT  From SomethingElse)
```

I hope it helps

I'll check the console bug asap

Thanks

Luigi

**Comment by matanshukry** [comment]
What does it mean exactly then, "it just creates links from existing data" ? What do I get from executing the `CREATE LINK` query? Assuming:
(1) I've created classes, like above
(2) I've created properties including `Person.City` with type `String`
(3) I've created actual data, vertices, with persons and cities. Person.City is set to City RID
(4) Then I've made the `CREATE LINK` query?

What happens exactly on step 4? What does it give me?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

Step 4 creates a link based on the correspondence of the keys on the records of the two classes.

Try the following ;-)

```
create class foo;
create class bar;

insert into foo set name = 'a';
insert into foo set name = 'b';

insert into bar set name = 'x', foo = 'a';
insert into bar set name = 'y', foo = 'a';
insert into bar set name = 'z', foo = 'b';

create link fooLink TYPE LINK from bar.foo to foo.name;

select from bar;
```

Thanks

Luigi

**Comment by matanshukry** [comment]
Ha ok, got it now. Just to clarify for others now:

It sets the value on the source class on a property named <link-name> to the RID of the destination class.
It finds the destination records by querying the destination class with the destination property, where it is equal to the source property.

Not the best explanation, but it's more than what I could find in the documentation.
Your example is also one I couldn't find better - would be really useful to put it in there.

Anyway closing it - thank you!

**Comment by matanshukry** [comment]
Second thought: Keeping this open for the console bug. Let me know if you prefer a new issue for it

**Comment by tglman** [comment]
Hi @matanshukry,

Could you open a different issue for the console bug?

I'm closing this.
Regards
