### ISSUE TITLE
sql output

### ISSUE THREAD

**Issue by RGURALNICK** [orientechnologies/orientdb#8954]
## Expected behavior  
select myfield from someclass should just bring back myfield's data and not the rid,type,version  

## Actual behavior  
you always get these in your http rest call before the property in the select statement output
## Steps to reproduce  
just create a simple SQL against a class

**Comment by RGURALNICK** [comment]
I don't want this in my output on every record returned. my command is select payL from Reservation. If I do this the studio I get what I want but using the HTTP calls I always get these
"@type": "d",
      "@rid": "#-2:1",
      "@version": 0,

**Comment by luigidellaquila** [comment]
Hi @RGURALNICK 

It was a known problem in v 2.2 and it's already addressed in v 3.0. I'd strongly suggest you to upgrade

Thanks

Luigi

**Comment by RGURALNICK** [comment]
Thanks for the prompt reply.  I will investigate that as a possibility.

**Comment by tglman** [comment]
Fixed already in 3.0.0, closing
