### ISSUE TITLE
Strange logic for filtering against linkset properties

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8956]
### Java Version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

## Expected behavior  

For the = operator I expected it to check against the whole set.
For the contains operator I expected either that this would not work, or that it would check as a subset operation? or that it would check that the two iterables had common elements. 

## Actual behavior  
It doesn't seem to do any of these consistently

## Steps to reproduce  

start with the demo db

```sql
create class testLinkSet extends V
create property hasCastles linkset Castles
create vertex testLinkSet set hasCastles = [#152:0 , #152:1]
create vertex testLinkSet set hasCastles = [#152:0, #152:3, #152:1]
create vertex testLinkSet set hasCastles = [#152:0, #152:3, #152:1]
create vertex testLinkSet set hasCastles = [#152:0, #152:4, #152:1]
```

I tried to use intersect to verify something i expected to work. I thought this would return all links since they are all classes

```sql
select * from statement where intersect(hasCastles, (select * from castles)).size() > 0```

but it returns nothing

next I tried using the contains operator. this works for a single element in a list or the element not in a list

```sql
select * from statement where hasCastles contains [152:0]
select * from statement where hasCastles contains 152:0
select * from statement where hasCastles = [152:0]
select * from statement where hasCastles = 152:0
```

but fails (returns nothing) when there are two

```sql
select * from statement where hasCastles contains [152:0, 152:1]
```

Is there a valid way to check if some linkset has records in common with a subquery? perhaps a containsany operator or some such?

**Comment by luigidellaquila** [comment]
Hi @creisle 

CONTAINS operator only checks if a single element is contained in a collection. If you need more complex logic, you can use CONTAINSALL (checks that all the elements on the right are contained in the collection on the left) or CONTAINSANY (checks that at least one of the elements on the right is contained in the collection on the left)

I hope it helps

Thanks

Luigi

**Comment by creisle** [comment]
Thanks @luigidellaquila the containsany operator isn't listed in the docs so I wasn't aware of it

http://orientdb.com/docs/3.0.x/sql/SQL-Where.html

That does seem to work!

**Comment by creisle** [comment]
I opened a ticket for adding this documentation here https://github.com/orientechnologies/orientdb-docs/issues/351
