### ISSUE TITLE
timeout during index creation

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8957]
## Expected behavior  
Creating an index should not give any timeout error

## Actual behavior  
running this command:
```
orientdb {db=cdrarch}> create index idx_cdr_icx_20190609_1 on cdr_icx_20190609(ENV, FILENAME, PRT_DATE, CALLING_NUMBER, CALLED_NUMBER, MGC8INCTRKGRPNAME, MGC8OUTTRKGRPNAME) FULLTEXT ENGINE LUCENE metadata {"allowLeadingWildcard": true, "closeAfterInterval": 86400000, "directory_type": "nio" }
Creating index...
```
produces this error after approx 1h50' (=110 mins = 6600 secs):
```
Error: com.orientechnologies.common.io.OIOException: Read timed out
Error: java.net.SocketTimeoutException: Read timed out
```
The index seems to get created though.

What's this ? What can be done to avoid this ?

**Comment by tglman** [comment]
Hi,

This is pretty normal behaviour,  the operation will continue in background till it finish, if you want the application client wait longer and not timeout before it finish you can set the https://orientdb.com/docs/3.0.x/admin/Configuration.html#networkrequesttimeout to a different value.

Regards
