### ISSUE TITLE
query optimizer does not use index on linked attribute filter

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8958]
### Java Version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
## Expected behavior  
Use the index in the query plan

## Actual behavior  
Does not use the index in the query plan

## Steps to reproduce  

Set up two classes and index the link property

```sql
create class Evidence extends V
create class Source extends V
create property Source.name string
create property Evidence.source link source
create index Evidence.source on Evidence(source) NOTUNIQUE
```
If I use a subquery, the index is picked up and used

```sql
select * from evidence where source in (select * from source where name = 'bob')
```

```text
+ LET (once)
  $$$SUBQUERY$$_0 = 
    +-------------------------
    | + FETCH FROM CLASS source
    |   + FETCH FROM CLUSTER 17 ASC
    |   + FETCH FROM CLUSTER 18 ASC
    |   + FETCH NEW RECORDS FROM CURRENT TRANSACTION SCOPE (if any)
    | + FILTER ITEMS WHERE 
    |   name = 'bob'
    | + CALCULATE PROJECTIONS
    |   *
    +-------------------------
+ FETCH FROM INDEX Evidence.source
  source IN $$$SUBQUERY$$_0
+ EXTRACT VALUE FROM INDEX ENTRY
  filtering clusters [15,16]
+ DISTINCT
+ FILTER ITEMS BY CLASS 
  evidence
+ CALCULATE PROJECTIONS
  *
```

but if I do the same thing using the link it is not

```sql
select * from evidence where source.name = 'bob'
```

```text
+ FETCH FROM CLASS evidence
  + FETCH FROM CLUSTER 15 ASC
  + FETCH FROM CLUSTER 16 ASC
  + FETCH NEW RECORDS FROM CURRENT TRANSACTION SCOPE (if any)
+ FILTER ITEMS WHERE 
  source.name = 'bob'
+ CALCULATE PROJECTIONS
  *
```

This is possibly related to https://github.com/orientechnologies/orientdb/issues/5546 tho it doesn't use a linkset, just a single link

**Comment by luigidellaquila** [comment]
Hi @creisle 

That's strange, it's supposed to work...
I'll check it ASAP and let you know

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Oh, ok, I got it, to use an index chain you also need an index on `Source.name`... 
This is because the subquery is not always the best strategy, eg. if you only have a few Evidence entries and millions of Source entries, traversing the link directly (without doing a subquery) is much more efficient

Thanks

Luigi

**Comment by creisle** [comment]
@luigidellaquila ok thanks! that makes sense. Does the query optimizer take into account the class size? in this example (a larger version) Evidence would be more than 100X the size of source

**Comment by luigidellaquila** [comment]
Hi @creisle 

The query execution planner takes into consideration the class size in some contexts, but not in this case (yet).

My advice in the short term is to just define an index on `Source.name`, if you need the index chain to be used

Thanks

Luigi

**Comment by creisle** [comment]
Ok, do you have a ticket for a feature request for this already? or should I leave this one open for that?

**Comment by luigidellaquila** [comment]
Hi @creisle 

I'd prefer to have a specific ticket for that

Thanks

Luigi
