### ISSUE TITLE
Rebuilding Indexes results in java.util.IllegalFormatConversionException: d != java.util.ArrayList

### ISSUE THREAD

**Issue by dullahan8** [orientechnologies/orientdb#8965]
### Java Version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)  
## Expected behavior  
Successful rebuilding of indexes 

## Actual behavior  
```
Rebuilding index(es)...
Rebuilt index(es). Found 
Error: java.util.IllegalFormatConversionException: d != java.util.ArrayList
```

## Steps to reproduce 
After a database crash, I ran a `CHECK DATABASE` in console which gave me 
```
Total errors found on indexes: 65590
```
So I try a `REBUILD INDEX` on any index and it throws the error message above.

**Comment by laa** [comment]
@dullahan8 are you sure that is 3.0.22 version? Looks like you use old configuration format.

**Comment by dullahan8** [comment]
Quite certain it is Orientdb 3.0.22.
```
[root@orientdbdev bin]# ./console.sh 

OrientDB console v.3.0.22 - Veloce (build 8afc634a2ea9c351898ae57dee8d739ff4851252, branch 3.0.x) https://www.orientdb.com
Type 'help' to display all the supported commands.
orientdb> connect plocal:/opt/orientdb-3.0.22/databases/pre-production admin         
Enter password: 

Connecting to database [plocal:/opt/orientdb-3.0.22/databases/pre-production] with user 'admin'...OK
orientdb {db=pre-production}> rebuild index *


Rebuilding index(es)...
Rebuilt index(es). Found 
Error: java.util.IllegalFormatConversionException: d != java.util.ArrayList

```

**Comment by dullahan8** [comment]
Does it make a difference if I am on the community edition? I'm trying to debug this further and I am running into issues previously resolved in version 2.2.x

**Comment by laa** [comment]
@dullahan8 No. Could you provide me full stack trace?

**Comment by dullahan8** [comment]
Can you explain further how to obtain the stack trace? The console doesn't print anything else and I don't find anything in orientdb-server.log.0

**Comment by zhangsenhua** [comment]
I have the same problem
OrientDB Version: 3.0.23

**Comment by leszekgruchala** [comment]
@laa I have the same problem. Upgraded DB from 2.2.27 to 3.0.26.
```
orientdb {db=adalog}> rebuild index *;


Rebuilding index(es)...
Rebuilt index(es). Found
Error: java.util.IllegalFormatConversionException: d != java.util.ArrayList
```
That's all we have. No error in the logs.

**Comment by mxns** [comment]
Same problem here on upgrade 2.2.37->3.0.28. Any update?

**Comment by leszekgruchala** [comment]
You can ignore this error, as the indexes are rebuilt. It seems this is an error on the console only. It does not occur on UI.
Make sure to rebuild all indexes after upgrade **before** ingesting any new data!

**Comment by laa** [comment]
Hi, if someone is interested to work on this issue please let us know, otherwise, it will be closed in one week
