### ISSUE TITLE
Copying of links

### ISSUE THREAD

**Issue by holubova** [orientechnologies/orientdb#8967]
### OS: Win 10

Hello,
I need to copy values of LINKs from one class to another. A simplified version of what I need and I think that should work but it doesn't is below. 
Thank you for your help!

----- create classes, add data:
CREATE CLASS A; 
CREATE PROPERTY A.a STRING (MANDATORY TRUE, NOTNULL TRUE);
INSERT INTO A (a) VALUES ("a1"), ("a2"), ("a3");

CREATE CLASS B;
CREATE PROPERTY B.b   STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY B.la  LINK A  (MANDATORY TRUE, NOTNULL TRUE);
INSERT INTO B SET 
  b  = "b1",
  la = (SELECT @rid FROM A WHERE a   = "a1");
INSERT INTO B SET 
  b  = "b3",
  la = (SELECT @rid FROM A WHERE a   = "a3");

----- check the values:
select * from A;
select b, la, la.a from B;

----- create a new class where the LINKs shoudl be copied:
CREATE CLASS C;
CREATE PROPERTY C.c   STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY C.la  LINK A ;
INSERT INTO C SET 
  c  = "b1";
INSERT INTO C SET 
  c  = "b3";
INSERT INTO C SET 
  c  = "something";

------ check the values: (la is correctly empty)
select * from C;

------ copy la from B to C: (copy to C the links from B)
UPDATE C SET la = 
   (SELECT B.la FROM B WHERE $parent.$current.c = B.b);

------ check the values: (la is set to null, whereas at 2 rows there should be @rids of A copied from B)
select * from C;

----- remove testing classes:
drop class B;
drop class C;
drop class A;

**Comment by luigidellaquila** [comment]
Hi @holubova 

It could be due to the `$parent.$current`, I'm not sure it works fine in UPDATE statements.
I'll check it ASAP and let you know

Thanks

Luigi
