### ISSUE TITLE
CONTAINSANY fails when used filtering against edge collection

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8973]
### Java Version:
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
## Behavior  

I can use CONTAINSANY to filter against a linkset ok, but when I try to filter against edges, none of the operators work

## Steps to reproduce  

Using the demodb, say I were to search for all castles a specific set of customers has visited

I make a query to find the customers, for example
```sql
select * from customers where Phone like '+141%'
```

Then I want to see what castles these customers have visited. I've tried a couple different queries for this

```sql
select * from castles where in('HasVisited') containsany (select * from customers where Phone like '+141%')

select * from castles where in('HasVisited') containsany (select @rid from customers where Phone like '+141%')

select * from castles where inE('HasVisited').outV() containsany (select * from customers where Phone like '+141%')

select * from castles where inE('HasVisited').outV() containsany (select @rid from customers where Phone like '+141%')

select * from castles where in('HasVisited') containsany (Phone like '+141%')
```

But none of the above return anything even tho we can verify that there are castles where customers with this phone pattern have visited

```sql
select count(*)  from (select in('HasVisited').Phone as customerPhone, @rid, Name from castles unwind customerPhone) where customerPhone like '+141%'
```
returns 26 records

note: this used to be possible in 2.2.X using `edgeCollection in otherCollection`

**Comment by luigidellaquila** [comment]
Hi @creisle 

I managed to reproduce the problem and fix it, you can find the fix in latest snapshot (available in a few minutes)

Thanks

Luigi

**Comment by creisle** [comment]
great! thank you!
