### ISSUE TITLE
Analog for OPartitionedDatabasePool in OrientDB 3.0.22

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#8977]
### OS: Ubuntu 18.04

I'm working on migration from 2.2.37 to 3.0.22. We used OPartitionedDatabasePool for create separated database connection for each user, but it doesn't works in 3.0.22. 

Is there is present analog of class OPartitionedDatabasePool for 3.0.22?

I see class ODatabasePoolImpl, but I'm not sure that I understand how to use it. Can you please explain:
What I must to do for get same experience in 3.0.22 with creation database as in 2.2.37

**Comment by WeaxMe** [comment]
I see similar issue #8845 
Can you please explain how works with OrientDBEmbedded, ODatabasePoolInternal, etc.
I will try implement own poll if there is no pool in OrientDB

**Comment by wolf4ood** [comment]
Hi @WeaxMe 

here it's an example on using pools. 
http://orientdb.com/docs/3.0.x/java/Document-API-Database.html#using-database-pools

Let me know if this helps

Thanks

**Comment by WeaxMe** [comment]
Hello @wolf4ood 
I create PR #8980 with implementation of database pool factory which I described in issue.
Please see my PR

**Comment by WeaxMe** [comment]
This was implemented and merged in #8980
