### ISSUE TITLE
Orient reading causing slowness because of some strange behavior.

### ISSUE THREAD

**Issue by rbaarathi** [orientechnologies/orientdb#8985]
OrientDB - 2.2.20  
 JAVA 8
 Centos - 7

  Expected behavior :
                      

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by wolf4ood** [comment]
Hi @rbaarathi 

do you have more insight about this?

Thanks

**Comment by rbaarathi** [comment]
Kindly refer issue number 8986.. 

We can close this issue..
