### ISSUE TITLE
Read performance of SELECT query is very slow when retrieving vertices using OrientDB 3.0.14 when compare to 2.1.18

### ISSUE THREAD

**Issue by Shanmugasundaram-V** [orientechnologies/orientdb#8987]
Recently we migrated to latest OrientDB 3.0.14, after that the existing query takes more time.
We tired the same in sample DB of 2.1.18 and 3.0.14, then found the result as,

OrientDB - 2.1.18
DB - GratefulDeadConcerts
select * from V
Query executed in 0.051 sec. Returned 500 record(s). Limit: 500 

OrientDB - 3.0.14
DB - DemoDB
select * from `Attractions`
Query executed in 0.324 sec. Returned 436 record(s). Limit: 500

Did anyone face such issue with the latest version or did I miss any settings?

**Comment by luigidellaquila** [comment]
Hi @Shanmugasundaram-V 

If you are running the query from Studio, can you please
- run the query again and see if it's just a matter of cold cache
- check the "raw" query execution, at the very end you will find an "elapsedMs" attribute that gives you the exact query execution time in milliseconds (all the rest is just result (un)marshalling and networking)

Thanks

Luigi

**Comment by luigidellaquila** [comment]
This is what I see on my machine with warm cache:
```
    "elapsedMs": 7,
    "notification": "Query executed in 0.066 sec. Returned 436 record(s)"
```

Thanks

Luigi

**Comment by Shanmugasundaram-V** [comment]
Hi luigidellaquila,

Thanks fof your reply.

I checked the "RAW" and the results are below,

OrientDB - 2.1.18
DB - GratefulDeadConcerts
select * from V
Query executed in 0.059 sec. Returned 500 record(s). Limit: 500 

OrientDB - 3.0.14
DB - DemoDB
select * from Attractions
Query executed in 0.14 sec. Returned 436 record(s). Limit: 500
