### ISSUE TITLE
Duplicate keys exist though using dictionary SB-Tree index

### ISSUE THREAD

**Issue by Tracy0231** [orientechnologies/orientdb#8988]
## Expected behavior  
As the Orientdb Manual says, dictionary indexes “are similar to those that use UNIQUE, but in the case of duplicate keys, they replaces the existing record with the new record”. 

## Actual behavior  
I tried to create dictionary SB-Tree indexes and insert records with duplicate keys, and it didn’t replace the existing record but created two records with the same key, just as the following picture shows.
[https://aws1.discourse-cdn.com/standard10/uploads/orientdb/optimized/1X/272411f06d34ae7992700e082b234ed1b3c56b67_2_690x221.png](url)

## Steps to reproduce  
create class test extends V;
create property test.test string;
create index test.test on test(test) dictionary;
create vertex test set test='123';
create vertex test set test='123';

**Comment by laa** [comment]
Hi @Tracy0231 dictionaries are buggy by definition we are going to deprecate them in 3.1 and remove in later versions. So I do not suggest to use them.

**Comment by Tracy0231** [comment]
> 
> 
> Hi @Tracy0231 dictionaries are buggy by definition we are going to deprecate them in 3.1 and remove in later versions. So I do not suggest to use them.

Now I need to merge duplicate records by multiple fields, but when I tried to create a compositeKey index  and use the merge transformer to  achieve this as below, it failed, so I tried the dictionary index, but..
`{ “merge”:
{ “joinFieldName”: [“NAME”, “PHONE”], “lookup”: “urgent_person.urg_name_phone” }
}`

So how can I use compositeKey index when using the merge transformer?

**Comment by laa** [comment]
Hi @Tracy0231 dictionaries are broken by design and we deprecated them. Please use unique indexes instead.
