### ISSUE TITLE
Setting the “SkipDuplicates” option "true" but not work

### ISSUE THREAD

**Issue by Tracy0231** [orientechnologies/orientdb#8990]
## Expected behavior  
As the manual says, edge transformer option "skipDuplicates" defines whether to skip duplicate edges when the UNIQUE constraint is set on both the out and in properties, when the option is set 'TRUE', it should skip duplicate edges.

## Actual behavior  
It still threw the error about duplicate edges.

## Steps to reproduce  
I created unique index for the in and out fields of an edge class, and set the “SkipDuplicates” option "true" when importing data using oetl but it still threw the error about duplicate edges:

https://aws1.discourse-cdn.com/standard10/uploads/orientdb/original/1X/acf0e3e8129644cdcfa9649d20afdf74fcd82298.png
https://aws1.discourse-cdn.com/standard10/uploads/orientdb/original/1X/b4dbfd6610ad2fd787e69af1c98a3839b3edf708.png

**Comment by Fab96** [comment]
@Tracy0231 
How did you define the UNIQUE index for the in and out fields of the edge class?

Thanks,
