### ISSUE TITLE
Please mark Fetching Strategies section clearly as "Deprecated" in documentation

### ISSUE THREAD

**Issue by muneebshere** [orientechnologies/orientdb#8992]
### OrientDB Version: 3.0 - 3.1

Fetchplans have been deprecated as of 3.0 onwards, but in only one location in documentation are they marked as such.

- In "Fetching Strategies" section - which is the main section dealing with Fetchplans in both 3.0.x and 3.1.x (beta) versions of the documentation - there is no mention that Fetchplans are deprecated: 3.0.x (http://orientdb.com/docs/3.0.x/java/Fetching-Strategies.html) and 3.1.x (http://orientdb.com/docs/3.1.x/java/Fetching-Strategies.html)

- In the "SELECT" SQL statement section which documents the FETCHPLAN parameter of the SELECT statement, again in both 3.0.x and 3.1.x versions, there is no mention that Fetchplans are deprecated: 3.0.x (http://orientdb.com/docs/3.0.x/java/Fetching-Strategies.html) and 3.1.x (http://orientdb.com/docs/3.1.x/java/Fetching-Strategies.html)

- Only in the "Upgrading to OrientDB 3.0" section is there a note that "In v 3.0 FETCH PLAN is deprecated, and no longer works in most of the scenarios. It was replaced by a much more flexible syntax: nested projections": (http://orientdb.com/docs/3.0.x/release/3.0/Upgrading-to-OrientDB-3.0.html)

This lack of information caused me to spend a significant amount of time into trying to work in Fetchplans in my implementation, and only by reading through all of the issues regarding Fetchplans posted here did I find out in a comment that they're deprecated. This information should be more clearly visible in the relevant sections.

**Comment by luigidellaquila** [comment]
Hi @muneebshere 

Thank you very much for reporting, I added a couple of more explicit notes in the docs, they will be updated in a few hours

Thanks

Luigi
