### ISSUE TITLE
SQL TRANSACTION STATEMENTS WITH IF STATEMENTS

### ISSUE THREAD

**Issue by octal-laurence** [orientechnologies/orientdb#8998]
## Expected behavior  
let record_version = ${version}

let getRecord = SELECT * FROM myTable WHERE @rid = #12:1
let updateRecord = UPDATE myTable SET text = 'my statement' WHERE @rid = #12:1 AND version = ${version}

// do not process if version is not equal to 1
if (record_version = 1) {
  let createSibling = INSERT INTO mySibling SET name = 'rudolf'
  let createEdge = CREATE EDGE recordSiblings FROM $createSibling TO getRecord.@rid
}

return $updateRecord

## Actual behavior  
<add here>  

## Steps to reproduce
Hi, I have a transaction sql, and I wanna know if I can use an "if" statement to execute a certain sql command, or what can you suggest me.
my plan is when my "if statement" didn't meet the version I have in my table, is not to execute the sql "insert & create edge"

Please see above my ideal and sample code of sql statement

**Comment by luigidellaquila** [comment]
Hi @octal-laurence 

You can definitely use IF statements in SQL batch scripts, see http://orientdb.com/docs/3.0.x/sql/SQL-batch.html

Thanks

Luigi

**Comment by octal-laurence** [comment]
> Hi @octal-laurence
> 
> You can definitely use IF statements in SQL batch scripts, see http://orientdb.com/docs/3.0.x/sql/SQL-batch.html
> 
> Thanks
> 
> Luigi

I'm checking on it now, this method you show me, 
So I can apply this on, REST API sql command?
currently im using the batch command in set of array. so I ll have to figure it out, how to apply this method on REST API Sql command.

**Comment by octal-laurence** [comment]
> Hi @octal-laurence
> 
> You can definitely use IF statements in SQL batch scripts, see http://orientdb.com/docs/3.0.x/sql/SQL-batch.html
> 
> Thanks
> 
> Luigi

currently im trying it to apply in my REST API SQL COMMAND, im using semicolon seperator features,
but im getting error.

heres my sql code
```
let getWorkPermitApplication = 
          SELECT 
            IN('${WorkPermitApplicationFingerPrints.tbl}') as fingerPrints, 
            IN('${WorkPermitApplicationPayments.tbl}') as payment,
            IN('${WorkPermitApplicationRequirementsClearances.tbl}') as requirementsClearances,
            @rid as id, 
            * 
            FROM ${this._tbl} 
          WHERE @rid = ${id};

        let updateWorkpermitApplication = UPDATE ${this._tbl} SET ${`
              ${schemaInText}
            `},
            version = ${version} + 1 
          WHERE @rid = ${id} AND softDelete != '1' AND version = ${version};

        if ($getWorkPermitApplication.version = ${version}) {
          let sample = SELECT
            @rid as id,
            FROM ${this._tbl} 
          WHERE @rid = ${id};
        };
```

**Comment by luigidellaquila** [comment]
HI @octal-laurence 

I think this will help: https://orientdb.com/docs/3.0.x/misc/OrientDB-REST.html#sql-batch

Thanks

Luigi

**Comment by octal-laurence** [comment]
> HI @octal-laurence
> 
> I think this will help: https://orientdb.com/docs/3.0.x/misc/OrientDB-REST.html#sql-batch
> 
> Thanks
> 
> Luigi

yes, im already working on it,
currently I'm using the semicolon batch seperator, and checking how to apply "if statement with bracket" to it. just having issue on it , if you don't mind checking my sql code

```
let getWorkPermitApplication = 
  SELECT 
    IN('${WorkPermitApplicationFingerPrints.tbl}') as fingerPrints, 
    IN('${WorkPermitApplicationPayments.tbl}') as payment,
    IN('${WorkPermitApplicationRequirementsClearances.tbl}') as requirementsClearances,
    @rid as id, 
    * 
    FROM ${this._tbl} 
  WHERE @rid = ${id};

let updateWorkpermitApplication = UPDATE ${this._tbl} SET ${`
      ${schemaInText}
    `},
    version = ${version} + 1 
  WHERE @rid = ${id} AND softDelete != '1' AND version = ${version};

if ($getWorkPermitApplication.version = ${version}) {
  let sample = SELECT
    @rid as id,
    FROM ${this._tbl} 
  WHERE @rid = ${id};
};
```

the semicolon is and transaction is working fine, but when I added a "if statement with bracket" it throws an error

**Comment by luigidellaquila** [comment]
Hi @octal-laurence 

I see you have a comma before a FROM in the IF block

```
if ($getWorkPermitApplication.version = ${version}) {
  let sample = SELECT
    @rid as id,                             <-------------
    FROM ${this._tbl} 
  WHERE @rid = ${id};
};
```

I think removing it will solve the problem

Thanks

Luigi

**Comment by octal-laurence** [comment]
> Hi @octal-laurence
> 
> I see you have a comma before a FROM in the IF block
> 
> ```
> if ($getWorkPermitApplication.version = ${version}) {
>   let sample = SELECT
>     @rid as id,                             <-------------
>     FROM ${this._tbl} 
>   WHERE @rid = ${id};
> };
> ```
> 
> I think removing it will solve the problem
> 
> Thanks
> 
> Luigi

Oh, I got it, i'm so blind, sorry about that. thank you very much

**Comment by luigidellaquila** [comment]
No problem ;-)

Thanks

Luigi
