### ISSUE TITLE
About "com.orientechnologies.orient.core.exception.ORecordNotFoundException"

### ISSUE THREAD

**Issue by MRWEI-zhbit** [orientechnologies/orientdb#8999]
## Expected behavior  
I want to query `@rid as rid and orther field` of the class.

## Actual behavior  
I use `SELECT @rid as rid,*  FROM PHONE_NO` ，I get the Exception bellow:
`"com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#306:571' was not found\u000d\u000a\u0009DB name=\"YibaoDB_dev\"\u000d\u000a--> java.lang.IllegalArgumentException: Cluster 306 is null"`

![image](https://user-images.githubusercontent.com/12880381/63574713-fc5c3100-c5ba-11e9-8da5-b97b14d80d65.png)

When I use `SELECT @rid as rid  FROM PHONE_NO` ,it run successfully.
![image](https://user-images.githubusercontent.com/12880381/63575011-a63bbd80-c5bb-11e9-9d7c-949ae9a34202.png)

My class :
![image](https://user-images.githubusercontent.com/12880381/63575582-fcf5c700-c5bc-11e9-99f5-72221fd7a608.png)

## Steps to reproduce  
`SELECT @rid as rid,*  FROM PHONE_NO`

**Comment by luigidellaquila** [comment]
Hi @MRWEI-zhbit 

I tried it on a sample DB and it seems to work fine. 
There must be a problem strictly related to your dataset, any chance to have a reproducer?

Thanks

Luigi

**Comment by MRWEI-zhbit** [comment]
Hi,@luigidellaquila 
Thanks for your reply.
I can't send you my dataset ,because it is so large and contains some confidential data.
But I can tell you that I have deleted some data before and there are some errors in the process.
It there any way to clean the data?

**Comment by luigidellaquila** [comment]
Hi @MRWEI-zhbit 

Depending on what kind of inconsistencies you have, you can try with a REPAIR DATABASE
https://orientdb.org/docs/3.0.x/console/Console-Command-Repair-Database.html

Thanks

Luigi

**Comment by MRWEI-zhbit** [comment]
Hi, @luigidellaquila  i'm trying this.
But I find another problem, when i use console.sh

`orientdb> connect plocal:/mnt/disk1/databases/YibaoDB root`
I get the error
```
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'YibaoDB'
        DB name="YibaoDB"
```
![image](https://user-images.githubusercontent.com/12880381/63580783-1d774e80-c5c8-11e9-891d-36571d33553b.png)

After i restoring the password of root  I can connect my database on the STUDIO.
When i use console.sh to connect the database , i get the same Error.
At the same time i can't connect my database on the STUDIO.

**Comment by luigidellaquila** [comment]
Hi @MRWEI-zhbit 

Try to use database users (eg. admin) instead of server users (eg. root)

Please consider that when you connect from console in plocal you cannot have another server running on the same databases 

Thanks

Luigi

**Comment by MRWEI-zhbit** [comment]
Hi, @luigidellaquila  
I can connect my database using  admin .
And I tried ` REPAIR DATABASE --fix-graph` .
But i get the same error after running `SELECT @rid as rid,* FROM PHONE_NO`

**Comment by luigidellaquila** [comment]
Hi @MRWEI-zhbit 

Probably the best thing to do here is to try to isolate the record that is creating the problem.

Try to add different SKIP/LIMIT to the query and see which record is corrupted

Thanks

Luigi

**Comment by MRWEI-zhbit** [comment]
Hi,@luigidellaquila 
I found the cause of the error:
![image](https://user-images.githubusercontent.com/12880381/63583605-ee63db80-c5cd-11e9-9c92-8990bb3257d8.png)

The "office_phone" VERTEX has been deleted before . 
But the edge has not been updated.

**Comment by luigidellaquila** [comment]
Hi @MRWEI-zhbit 

That's strange, the `--fix-graph` option of REPAIR DATABASE should have fixed it

Thanks

Luigi

**Comment by MRWEI-zhbit** [comment]
Hi @luigidellaquila 
Yes ,I am also confused about this .  
And I have to use `update  PHONE_NO remove in_office_phone` to fix it.
