### ISSUE TITLE
Endless loop when updating a record after creation in batch mode

### ISSUE THREAD

**Issue by VincentMarrec** [orientechnologies/orientdb#9000]
## Expected behavior  
The record should be updated just once.
 

## Actual behavior  
There is an endless loop. The record is updated multiple times.

## Steps to reproduce  
Use the following SQL script in batch mode :
`let a = CREATE VERTEX V SET test = 0;
UPDATE $a SET test = $a.@rid;`

Hope this helps.
Cheers.

**Comment by CortneyKnorr** [comment]
Same problem
