### ISSUE TITLE
java.lang.ClassException occurred when creating edges on Graph Editor

### ISSUE THREAD

**Issue by tomlee** [orientechnologies/orientdb#9008]
## Expected behavior  
An edge can successfully be created on the Graph Editor without any error when with the command:
```text
CREATE edge FriendOf FROM #21:1 TO #22:0
```

## Actual behavior 
The following error occurred in a red box:
```text
java.lang.ClassCastException: com.orientechnologies.orient.core.record.impl.ODocument cannot be cast to com.orientechnologies.orient.core.record.OEdge
```
The created edge cannot be shown on the graph after the execution of the above command. 

However, when the nodes are selected with:

```text
SELECT * FROM V LIMIT 10;
```
The edge has actually be created and shown on the graph.

## Steps to reproduce  

The error can easily be repeated as above.

**Comment by luigidellaquila** [comment]
Hi @tomlee 

I managed to reproduce and fix the problem. I'm pushing the fix now

Thanks

Luigi

**Comment by tomlee** [comment]
Thanks.
