### ISSUE TITLE
engine 'PLOCAL' was not found

### ISSUE THREAD

**Issue by tidepodz** [orientechnologies/orientdb#9009]
### OS: Ubuntu 18.04  

I see lots of examples online where they do things like  
```CREATE DATABASE PLOCAL:/tmp/mydb```
or
```CONNECT plocal:../databases/GratefulDeadConcerts admin my_admin_password```

When I try using PLOCAL I get the following error:
```
Error: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'PLOCAL' was not found. URL was: PLOCAL:/tmp/mydb. Registered engines are: ["embedded","remote"]
```

I can still connect doing this

```CONNECT remote:localhost root my_root_password```

**Comment by mpomet** [comment]
Also there is a lot of `CONNECT REMOTE:localhost...` in the documentation.    
All of these doesn't work.     
Lowercase is the only working pattern.
