### ISSUE TITLE
Disabling the local record cache

### ISSUE THREAD

**Issue by ymesika** [orientechnologies/orientdb#9010]
## Expected behavior  
The ability to disable the local record cache.  

## Actual behavior  
Currently user can choose (with configuration) from two cache implementations: `ORecordCacheWeakRefs` and `ORecordCacheSoftRefs`.
However disabling is not possible.

My suggestion is to add a new implementation (e.g. `ORecordCacheDisabled`) and add it to the registry so users can choose this one to disable the local record cache.

I can contribute this if it makes sense.

**Comment by laa** [comment]
That is impossible. Disabling of the local cache will lead to false concurrent modification exceptions.
