### ISSUE TITLE
Query filtering by @rid does not use ID to optimize

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#9014]
### Java Version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
## Expected behavior  
I am not sure if this behaviour is the expected behaviour or not? When I use `@rid` in the filter conditions of the query the query isn't optimized at all. I thought that it would use the rid to speed up the query

## Actual behavior  
The query goes through all records to check Ids

## Steps to reproduce  
```sql
SELECT * FROM V WHERE @rid = #13:0 OR @rid = #14:0
```

The explain

```
+ FETCH FROM CLASS V
  + FETCH FROM CLUSTER 9 ASC
  + FETCH FROM CLUSTER 10 ASC
  + FETCH FROM CLUSTER 23 ASC
...
  + FETCH FROM CLUSTER 85 ASC
  + FETCH FROM CLUSTER 86 ASC
  + FETCH NEW RECORDS FROM CURRENT TRANSACTION SCOPE (if any)
+ FILTER ITEMS WHERE 
  @rid = #13:0 OR @rid = #14:0
+ CALCULATE PROJECTIONS
```

**Comment by luigidellaquila** [comment]
Hi @creisle 

I'll check it ASAP. In the meantime, you can replace the query with the following, that is already optimized

```
SELECT * FROM [#13:0, #14:0]
```

Thanks

Luigi
