### ISSUE TITLE
OrientDB ETL CSV , Import only edges 

### ISSUE THREAD

**Issue by masaddatmallick** [orientechnologies/orientdb#9015]
We have a city.csv file which contains

    cityname,citystdcode
    KOLKATA,033
    MUMBAI,022
    HYDERABAD,040

this csv is already imported using etl , now we have CITY class Vertex with 3 records.

Now we have route.csv which contains only edges which we need to import

    from,to
    MUMBAI,HYDERABAD
    KOLKATA,MUMBAI

This is the route.json , we tried so many ways but nothing works.

    {
        	"config": {
        		"log": "debug"
        	},
        	"source": {
        		"file": {
        			"path": "route.csv"
        		}
        	},
        	    "extractor": { "csv": {"separator": ",",
                      }
                       } ,
        	"transformers": [
        		{
        			"merge": {
        				"joinFieldName": "from",//${input.from} also tried
        				"lookup": "City.cityname"
        			}
        		},
        		{
        			"vertex": {
        				"class": "City"
        			}
        		},
        		{
        			"edge": {
        				"class": "Route",
        				"joinFieldName": "to", //${input.to} also tried
        				"lookup": "City.cityname",
        				"unresolvedLinkAction": "CREATE"
        			}
        		}
        	],
        	"loader": {
        		"orientdb": {
        			"dbURL": "plocal:C:/ODB/databases/large14",
        			"dbType": "graph",
        			"wal": false,
        			"batchCommit": 10,
        			"tx": true,
        			"txUseLog": true,
        			"useLightweightEdges": true,
        			"classes": [{
        					"name": "City",
        					"extends": "V"
        				},
        				{
        					"name": "Route",
        					"extends": "E"
        				}
        			],
        			"indexes": []
        		}
        	}
        }

Need to import this using etl , We tried all available json configuration example of edge import but nothing works , we are confused with merge,lookup,join fields(how it works). command statement(create edge) is not preferable as we need to import huge (2Million) relationships. we are using orientdb 3.0.2

Kindly help with simple json to import this.

**Comment by alexandre-melard** [comment]
Dear @masaddatmallick 
Would you be so kind to share how you solved this issue please?
Best Regards
Alexandre
