### ISSUE TITLE
Support gzip compression of HTTP Rest API Response in Orient DB

### ISSUE THREAD

**Issue by cijo-uc** [orientechnologies/orientdb#9019]
## Expected behavior  
The REST API response from the server should support compression when Studio makes a large API request. 

## Actual behavior  
The request headers ask for compression. 
But the response from the server is not compressed.
When the response is over 70Mb, there's a major lag.

![f1](https://user-images.githubusercontent.com/46745502/65421231-de375a00-de20-11e9-8fac-234bba543319.png)

On the console, the query takes 0.344 sec(s). 

`2486 item(s) found. Traverse executed in 0.344 sec(s).`

**Comment by madmac2501** [comment]
I have the same use case with big responses. This ticket would help.
