### ISSUE TITLE
Could not create an edge between two vertices. Complaining about the ridbag with an index which is no more in the database

### ISSUE THREAD

**Issue by ssenapat** [orientechnologies/orientdb#9024]
## Expected behavior  
When i try to create a new edge between two vertex using below command it fails
create edge orgLocatedAt from 30:104 to 25:232
It should create with no errors.

## Actual behavior  
below error is reported
com.oreintechnologies.orient.core.exception.OSerializationException: Found null entry in ridbag with rid=#49:-1 DB name = "XXXX"

## Steps to reproduce  
I can provide you the sample database connection  along with credentials or I can export and share the database.

Then try to execute the command below you will see the error.
create edge orgLocatedAt from 30:104 to 25:232

**Comment by fortuneyan** [comment]
It looks like you need to "create edge orgLocatedAt extends E" first.
