### ISSUE TITLE
Create edge via Rest API issue

### ISSUE THREAD

**Issue by henryagyei** [orientechnologies/orientdb#9034]
### OS: <rest api>  

Im using the rest api version 2.2 to create edges but continuously receive error code 400 even though I am creating exactly the same was as in REST API docs. Please help with where I am going wrong.

Please see the below image to reproduce in postman
Any help would be greatly appreciated

Thanks

![image](https://user-images.githubusercontent.com/20363763/66042801-64d0f300-e515-11e9-8c99-dd57c2401620.png)

**Comment by wolf4ood** [comment]
Resolved here

https://community.orientdb.org/t/create-edge-problem-in-rest-api/760/7
