### ISSUE TITLE
NullPointerException checking database

### ISSUE THREAD

**Issue by johny65** [orientechnologies/orientdb#9036]
For some reason my data got corrupted, some queries log multiple lines like this one:

    Record (#{the rid}) is null [OEdgeIterator]

So I wanted to check the database and in some point it throws:

    Checking cluster {the_class_name}  for index {the_index_name}
    cluster {the_class_name} (789) |                    | 0%
    Error: java.lang.NullPointerException

and the check is stopped.

## Expected behavior  
To check the database correctly.

## Actual behavior  
When I run the command "check database" from console, a NullPointerException is thrown when checking cluster.

**Comment by johny65** [comment]
@luigidellaquila I'm afraid I can't share a copy of the database, it has sensitive information and it's several GB of size.

**Comment by moses-everette** [comment]
I too have discovered this issue. Moreover, it would be nice to log the errant cluster when this exception occurs.

Regards.

**Comment by tglman** [comment]
Hi,

Similar issue where fixed in some more recent version of OrientDB, could check this problem in a updated version?

Regards

**Comment by johny65** [comment]
Hi @tglman, I tested with 3.0.32 version, I can't tell if this specific problem was solved because now I get another... I have a Lucene index and in some point in the check process it throws this:

```
Checking cluster {the_class_name}  for index {the_index_name}
cluster {the_class_name} (1521) |                    | 0%
Error: com.orientechnologies.orient.core.index.OIndexEngineException: Error parsing lucene query
	DB name="{the_database_name}"

Error: com.orientechnologies.orient.core.sql.parser.ParseException: Cannot parse ' DANIEL MARINI -': Encountered "<EOF>" at line 1, column 16.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
```

I dropped and recreated the index but the same error happens. However I can use it in queries without problem, giving me correct results.
The index is created in the following way on the "lucene" property of the class:

```
CREATE INDEX the_index ON TheClass(lucene) FULLTEXT ENGINE LUCENE METADATA {"analyzer":"org.apache.lucene.analysis.standard.StandardAnalyzer"} ;
```

I think the problem is because the indexed string has a `-` character.
