### ISSUE TITLE
Connection issue for  "component" and "config" Orientdb databases while using it along with NEXUS repository 

### ISSUE THREAD

**Issue by Sandhya131** [orientechnologies/orientdb#9040]
### Issue
We are using orientdb for our nexus repository. We are facing issues connecting to the nexus repo since the orientdb got corrupted after the file system got full. We have error in two of the db components "**component**" and "**config**" . When we try to connet to these two db's using the following command it is throwing the following error

![orienterror](https://user-images.githubusercontent.com/45095404/66464720-1daaab00-ea9d-11e9-9bcd-ee1a417c3e9a.png)

![Screenshot from 2019-10-09 14-01-59](https://user-images.githubusercontent.com/45095404/66464853-619db000-ea9d-11e9-824e-c48dfb26ac82.png)

Any suggestions to fix this error?

**Comment by wolf4ood** [comment]
Hi @Sandhya131 

do you have an orientdb server running?

Thanks

**Comment by Sandhya131** [comment]
Hi @wolf4ood 
I'm not sure because we are using this with the Nexus repository. Can you help me check if we have the orientdb server running?

**Comment by wolf4ood** [comment]
Hi @Sandhya131 

probably you can check with `jps` the java process running on that machine.

**Comment by Sandhya131** [comment]
@wolf4ood  
Got this result for jps 

**bash-4.2$ jps
4336 nexus-orient-console.jar
4458 Jps
63 UnixLauncher**

**Comment by wolf4ood** [comment]
@Sandhya131 

not sure if the unixlauncher is part of nexus. Do you have the nexus server running?

can you check if ports 2480/2424 are opened?

Thanks

**Comment by Sandhya131** [comment]
@wolf4ood 
Nexus is not running. When we try to start it we are getting this error

**bash-4.2$ ./nexus status
nexus is stopped.
bash-4.2$ ./nexus run   
Unable to delete file: /nexus-data/cache/bundle3/bundle.info**
Thank you

**Comment by Sandhya131** [comment]
@wolf4ood 
The above error is solved and we are successfully able to connect to the "component" and "config" databases but when we are trying to start the nexus using the command "**./nexus run**" , we have the following error now.

![Screenshot from 2019-10-11 12-19-40](https://user-images.githubusercontent.com/45095404/66644773-68642880-ec3f-11e9-99ce-9706a7799657.png)

Any idea how to solve this error?

**Comment by tglman** [comment]
Hi @Sandhya131, 

This errors seems more related to nexus than to OrientDB, could you report the issue there ?

Regards
