### ISSUE TITLE
API Documentation link broken:   http://orientdb.com/docs/last/orientjs/OrientJS.html

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#9049]
### OS: Web
Documentation Only

## Expected behavior  
should bring me to the OrientJS API documentation

## Actual behavior  
get a page 404 error

## Steps to reproduce  
go to : ```http://orientdb.com/docs/3.0.x/orientjs/OrientJS.html```
find the link for ```API Docs```
click it.

**Comment by luigidellaquila** [comment]
Fixed, thanks

Luigi
