### ISSUE TITLE
Studio showing session expired error while using OrientDB in distributed mode

### ISSUE THREAD

**Issue by vikram-shityalkar** [orientechnologies/orientdb#9050]
## Expected behavior  
By using a studio, I should be able to login and add some records. 

## Actual behavior  
Unable to login to the studio, the studio is throwing session expired error.

## Steps to reproduce  
I have created a GitHub repository. 
https://github.com/vikram-shityalkar/kubernetes-orientdb-distributed 

This repository contains the Docker file to use Hazelcast configuration and nginx-ingress rules to expose the studio from the Kubernetes cluster.
To reproduce this, I have used Docker Desktop CE and enabled the Kubernetes. This gives us a single node cluster. The [repository](https://github.com/vikram-shityalkar/kubernetes-orientdb-distributed) has the steps to install ingress and OrientDB with the stateful state.

Once everything is running, Open https://localhost/studio/studio/index.html#/. Using studio try to create a database. This works but fails to login and enter into studio.

I have tested with latest docker image but the behavior is same.

**Comment by wolf4ood** [comment]
Hi @vikram-shityalkar 

 By default kubernetes loadbalance http request. That is an issue for Studio, which require a sticky session. If you want to access studio you should port-forward from a pod to your local machine and access studio in localhost

Let me know if this helps. 

Thanks

**Comment by vikram-shityalkar** [comment]
Hi @wolf4ood 

I did try port-forward. I have used two replicas in StatefulSet, I am seeing two pods, orientdbservice-0 and oriendservice-1. I was able to login by port-forward to first pods, but for second pods it is throwing the same error.

I logged continued with the first pod and logged in. I tried to create a vertex Person. It failed with the following error:
``
com.orientechnologies.orient.server.distributed.ODistributedException: Error on creating cluster 'person' on distributed nodes: local and remote ids assigned are different
``
I will continue to explore this by looking into reported issues. 

I have another question, Does OrientJS support this distributed mode?

**Comment by wolf4ood** [comment]
Hi @vikram-shityalkar 

that is a different issue i guess. Let me know if you have a reproducer for that issue

```
com.orientechnologies.orient.server.distributed.ODistributedException: Error on creating cluster 'person' on distributed nodes: local and remote ids assigned are different
```


Yes  OrientJS supports distributed. Use the new APIs documented here

http://orientdb.com/docs/3.0.x/orientjs/Client.html#configuration-with-orientdb-cluster

Thanks
