### ISSUE TITLE
SQL composition

### ISSUE THREAD

**Issue by tomazk8** [orientechnologies/orientdb#9051]
### OS: Windows 10

Hey guys. I am storing tasks where each task can have sub-tasks. I have only one collection, Tasks and one edge, HasSubTask. I want to construct a composite query that returns all tasks and for these tasks, all sub-tasks. Here is a query:

```
select expand($0)
let $AA = (select *, '$AA' as _subQueryId from Task),
$AB = (select *, '$AB' as _subQueryId from (traverse out('HasChildTask') from (select expand($AA)) MAXDEPTH 1) where $depth > 0),
$0 = unionall($AA, $AB)
```

Why do I do it like this? I want to make dynamic queries by composing same SQL parts together, meaning, I want to start with a base select and then expand it if needed. I.e. select Tasks, then extend with Subtasks or with Delegatees, DueDates, etc if needed. SQL will never be static. So $AB may or may not be there. With this I have the flexibility that I can grow/adjust the query depending on the client's request, so I don't need to do N separate database requests.

It actually works great, but there is one problem. Imagine that I have two tasks in the DB, Task1 and ClientTask1, with one edge where Task1 -HasChildTask-> ChildTask1. The SQL above will return both tasks in $AA collection but $AB will be empty, although ChildTask1 should be there. I believe the reason is that OrientDB doesn't return duplicated entities since ChildTask1 was already returned in $AA. I added a where clause to filter out ChildTask1 from $AA and then it did appear in $AB, proving this. But the problem is now that the query should return ChildTask1 twice, both in $AA and $AB. I thought that using "let" to do subselects, the subselects are independant and unionall will simply union all results, but this is not the case. I actually need to have duplicates in this case (well I am actually adding _subQueryId column to distinguish the collection from which it came from - I need it to reconstruct entity-tree in business logic).

Is there something I can do about it because without duplicates, I have a big limitation here when selecting from same collection in more than one subquery. I think that subselects should be independant of each other, or what do you think?

I hope I wrote it clearly enough to understand the problem that I have :).

Best regards
Tomaz

**Comment by luigidellaquila** [comment]
Hi @tomazk8 

I think the problem is exactly how you described it: the TRAVERSE never returns duplicates.

As long as you have MAXDEPTH 1, you can replace the TRAVERSE in $AB with a much easier 

```
SELECT expand(out('HasChildTask')) FROM from (select expand($AA)
```

If you need deep traversal, you can try with a MATCH with WHILE conditions, that does not have the limitation of discarding already traversed elements

Thanks

Luigi

**Comment by tomazk8** [comment]
Hi Luigi,

Thank you very much for such a super fast reply. You're right, this works now, great. Case closed :).

Best regards
Tomaz
