### ISSUE TITLE
FullText Lucene Index with 'containstext' contraint

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#9057]
### OS: alpine 3.4

Is there the possibility to create a FullText Lucene index on a field so that I can use containstext with ignorcase option?

I remember the issue [8519](https://github.com/orientechnologies/orientdb/issues/8519) but I need to search part of text in Vertex field using ignorcase strategy.

When I use FULLTEXT - LUCENE I can find vertices using a string that is present in the V field (lucene engine works fine) but I need to specify the string case.

Using SUBTREE it works for ignoracase text and filter, but I need to specify all the V field value.

Is there a compromise?

Suppose I have the message Vertex field with this value:
`Lorem ipsum dolor sit amet, consectetur AdipiSCing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua`

now I need to search _where message containstext 'scing'_ (using Lucene I need to use **SCing**, while SBTREE need all text)

What kind of index I should create in it to have the correct output?

## Actual behavior  
<add here>

**Comment by wolf4ood** [comment]
Hi @gianluca-valentini 

how do you insert data? Do you have a simple SQL snippet to reproduce this issue?

Thanks

**Comment by gianluca-valentini** [comment]
Hi @wolf4ood 
I created a database with the scenario that currently generate this issue
[support_database.zip](https://github.com/orientechnologies/orientdb/files/4633329/support_database.zip)

I have Book vertex with some fields. The Description one with LUCENE-LUCENE index.

if you execute `select from Book where description containstext 'scing'` the result is empty.

While there is a vertex with description: _Lorem ipsum dolor sit amet, consectetur **AdipiSCing** elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua_
