### ISSUE TITLE
hangs with OutOfMemoryError: Java Heap space when trying to create an edge

### ISSUE THREAD

**Issue by ssenapat** [orientechnologies/orientdb#9061]
## Expected behavior  
Should be able to create an edge with no error.

## Actual behavior  
OrientDB hangs and throws OutofmemoryError: Java Heap space when trying to create an edge.

## Steps to reproduce  
Adding the sample database with three vertex, one edge and one function.
Please execute the function vertex_job_create to reproduce the issue.
 
[db1.gz](https://github.com/orientechnologies/orientdb/files/3831189/db1.gz)

**Comment by laa** [comment]
Hi guys, please let me know if this issue still actual I will work on it.
