### ISSUE TITLE
EMBEDDEDMAP LINK doesn't work properly with subquery

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#9062]
### OS: docker from openjdk:8-jdk-slim

The same situation with EMBEDDEDLIST was in https://github.com/orientechnologies/orientdb/issues/8510

## Steps to reproduce
```sql
CREATE CLASS TForm;
CREATE PROPERTY `TForm`.`links` EMBEDDEDMAP LINK

CREATE CLASS TOrganization;
CREATE PROPERTY `TOrganization`.`name` STRING
INSERT INTO TOrganization SET name = "test"

INSERT INTO TForm 
SET links = {"organization": (select from TOrganization where name = "test")}
#returns {"organization":[]}

INSERT INTO TForm 
SET links = {"organization": #17:0}
#returns {"organization":"#17:0"}
```

**Comment by luigidellaquila** [comment]
Hi @freeart 

EMBEDDEDMAP is intended to store embedded elements, not links. You should use LINKMAP instead

Thanks

Luigi

**Comment by freeart** [comment]
@luigidellaquila Cool, thanks. I thought LINKMAP can be created with defined CLASS only
