### ISSUE TITLE
How to check if query result isn't empty in server side function?

### ISSUE THREAD

**Issue by kamil11145** [orientechnologies/orientdb#9064]
### OS: Linux Ubuntu 18

OrientDB allows for creating server side functions by using "Functions Management" in OrientDB Studio. I'm using demo database and trying to find out if id from parameter exist in database (easy case). My problem is how to check if query result is empty? Code and more details below.

I have easy function in JS:

var queryResult = db.query('select Name from Castles where Id=?',id);
if(**queryResult == null**){
    response.send(404,"Castle not found", "text/plain", "Error: Castle not found");
}else{
    return queryResult;
}

When I run this function with parameter 1 (id=1) then I got execution result:
[ { "Name": "Castel Sant’Angelo" } ]
BUT (and here is a problem) when I do the same with parameter id=1234 then I got:
[

]

In second case I should get response "Error: Castle not found".

I tried change second line of code as:

if(queryResult == undefined)
if(queryResult["Name"] == null)
if(queryResult.length == 0)
and so on...but the result is the same.

I open this case on stackoverflow: https://stackoverflow.com/questions/58894384/orientdb-how-to-check-if-query-result-isnt-empty-in-server-side-function

**Comment by jonsalvas** [comment]
Try the following:

`
var queryResult = db.query('select Name from Castles where Id=?',id);
if(!queryResult.hasNext()){
   print("empty");
} else {
  print(" non empty");
}
`

Maybe as general idea: If you are unsure what kind of objects are returned, you can print .getClass() from an object to return its type e.g.:
`
queryResult.getClass() 
`
which returns OLocalResultSetLifecycleDecorator -> you can look up this class in the orientdb api:
https://orientdb.com/javadoc/develop/com/orientechnologies/orient/core/sql/parser/OLocalResultSetLifecycleDecorator.html
