### ISSUE TITLE
OrientGraphFactory graph connection leak，I think it is fatal error

### ISSUE THREAD

**Issue by zfaster** [orientechnologies/orientdb#9066]
### maven depend
`<dependency>
      <groupId>com.orientechnologies</groupId>
      <artifactId>orientdb-gremlin</artifactId>
      <version>3.0.24</version>
    </dependency>`
## Steps to reproduce  
1、 config：
`OrientGraphBaseFactory factory = new OrientGraphFactory(config.getUrl(), config.getUsername(), config.getPassword())
                    .setupPool(config.getMaxConnection());
            return new OrientDBGraphDataSource(factory);`
2、use GraphTraversalSource to addVertex， when throw ORecordDuplicatedException,
![image](https://user-images.githubusercontent.com/8341790/69038428-bcbfac80-0a24-11ea-87c7-6e02ac6a3e91.png)

![image](https://user-images.githubusercontent.com/8341790/69037758-69009380-0a23-11ea-8c03-2448e80d3339.png)

3、Multiple loop calls reporting errors ：
![image](https://user-images.githubusercontent.com/8341790/69037940-cbf22a80-0a23-11ea-9304-a9d832a212e3.png)

4、When multithreaded requests occur, this error will immediately deplete connection pool resources then throw 

> com.orientechnologies.common.concur.lock.OLockException: No more resources available in pool (max=xx). Requested resource: null

I think this is bug，when cause exception pool connection was not close and open new

this error cause I can't use orientdb to project

**Comment by wolf4ood** [comment]
Hi @zfaster 

thanks for the report. Do you have a sample script to reproduce this issue?

Thanks

**Comment by zfaster** [comment]
```java
@Test
    public void save2() throws Exception {
        List<TestData> ts = new ArrayList<>();
        for(int i=0;i<100;i++){
            TestData testData = new TestData();
            testData.setId(1+"");
            testData.setStr("1");
            ts.add(testData);
        }
        int count  = 50;
        CountDownLatch countDownLatch = new CountDownLatch(count);
        for (int i = 0; i < count; i++) {
            int finalI = i;
            CompletableFuture.supplyAsync(() -> {
                graphTemplate.save(ts);
                return finalI;
            },threadPoolTaskExecutor).whenComplete((exeTask, throwable) -> {
                System.out.println(exeTask);
                countDownLatch.countDown();
                if(throwable!=null){
                    throwable.printStackTrace();
                }
            });
        }
        countDownLatch.await();
        System.out.println("done");
    }
```

The general principle is to start several threads to add the same data. **The id of the TestData table is a custom field with a unique index**. The graphTemplate is wrapped by myself, and I actually call GraphTraversal. addV internally

@wolf4ood  thank you reply ，I hope it can be fix as soon as possible

**Comment by wolf4ood** [comment]
Hi @zfaster 

let me check on this, i'm sure it can be fixed for the next release.

**Comment by zfaster** [comment]
@wolf4ood May I ask why we need to call makeActive? If I mask this logic seems to have no effect, when do we need to reconnect？

**Comment by wolf4ood** [comment]
Hi @zfaster 

probably it's not needed and it's a leftover when we took over the driver.

Just a question of `graphTemplate` can you share the code on save?

Thanks

**Comment by wolf4ood** [comment]
Hi @zfaster 

ok i've pushed a fix it will be available in the next release.

You can also try the snapshot . It will be available here once the test passes on the CI

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-gremlin/

**Comment by zfaster** [comment]
@wolf4ood Thank you for fixing the bug in time

Because the project decided to use the specification of gremlin for development, in case of subsequent database changes, I originally intended to use [Spring Data Gremlin](https://github.com/microsoft/spring-data-gremlin), but after testing, I found that it was not compatible with orientdb, and I could not find other good frameworks, so I had to develop a simple tool myself

graphTemplate is adding  properties in a class through Java reflection, and managing GraphTraversalSource open and close with spring aop

beacuse it's company project ，so I can't offer source code
