### ISSUE TITLE
Orientdb USES the etl tool to import the large CSV file, causing the memory to not be freed

### ISSUE THREAD

**Issue by easonjim** [orientechnologies/orientdb#9067]
## Expected behavior  
Automatic memory release  

## Actual behavior  
Automatic memory release

## Steps to reproduce  
Orientdb USES the etl tool to import the large CSV file, causing the memory to not be freed.
My CSV has 10G, and when I import 3G, the system memory has reached 15G. What I import is the graph type, and the JSON file automatically creates fixed vertex and edges.
How to make ETP program import part of the data to free up memory to achieve memory balance.

**Comment by Lhosnlhos** [comment]
Hello, plz can you make a tutorial about how to import than load data from csv to an orientdb database

**Comment by Lhosnlhos** [comment]
Hello, plz can you make a tutorial about how to import than load data from csv to an orientdb database
