### ISSUE TITLE
Docker image for Raspberry Pi

### ISSUE THREAD

**Issue by aleklisi** [orientechnologies/orientdb#9072]
## Expected behavior  
As a user I want have a docker image for Raspberry Pi (ARM).

## Actual behavior  
There is no such docker image.

## Steps to reproduce  
```bash
pi@raspberrypi:~ $ docker run -d --restart=always --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=root orientdb
Unable to find image 'orientdb:latest' locally
latest: Pulling from library/orientdb
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
```

**Comment by luigidellaquila** [comment]
Hi @aleklisi 

We reviewed the Docker images structure, could you please try again and let me know if it works now?

Thanks

Luigi
