### ISSUE TITLE
How to avoid OConcurrentModificationException？

### ISSUE THREAD

**Issue by zfaster** [orientechnologies/orientdb#9079]
### Java Version: 1.8  

OConcurrentModificationException frequently occurs when multi-threaded operation establishes a relationship between a node in orientdb cluster

How can I avoid this exception frequently? For example, is it possible to configure automatic retry? Or automatically accumulate updates? At present, this problem can only be handled through code lock control concurrency, which is very unfriendly

Expect reply~

**Comment by luigidellaquila** [comment]
Hi @zfaster 

OrientDB v 3.0.x has a specific API for this, see https://orientdb.com/docs/3.0.x/java/Java-Multi-Threading-Concurrency.html

Thanks

Luigi

**Comment by zfaster** [comment]
@luigidellaquila  thank you~

**Comment by zfaster** [comment]
@luigidellaquila 
![image](https://user-images.githubusercontent.com/8341790/70772213-d3042280-1dae-11ea-8239-6d2fd60aca7f.png)
I found automerge can merges the changes.
but when i execute 
![image](https://user-images.githubusercontent.com/8341790/70772295-0181fd80-1daf-11ea-9768-22c9c1d6d719.png)
the db page result is 
![image](https://user-images.githubusercontent.com/8341790/70772314-152d6400-1daf-11ea-878f-8d9eb39c3eb9.png)

why it can‘t change to automerge ?
I use server console to execute the sql ,it will same result
it's bug?

**Comment by tglman** [comment]
Hi,

The strategies for merging request are deprecated, please handle the Councurrent Modification in you application, is most of the time data concurrent access that should be handled anyway, there is no way to avoid this.

Regads
