### ISSUE TITLE
DEADLOCK in distributed Mode after: Found null entry in ridbag with rid=#245:-13

### ISSUE THREAD

**Issue by jonsalvas** [orientechnologies/orientdb#9081]
## Expected behavior  
Update vertices and its edges as usual in distributed mode

## Actual behavior  
1. OConcurrentModificationExceptions are thrown for the record #119:2: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #119:2 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v73 your=v72)
2. Our retry logic retries the transaction 5 times. After retrying 2 times we receive:
 [OHazelcastPlugin]Exception `2FE1AD2D` in storage `plocal:/orientdb/databases/xxx`: 3.0.25 - Veloce (build 2a229d542568b8d413b8633cca1f34239449d13e, branch UNKNOWN)
com.orientechnologies.orient.core.exception.OSerializationException: Found null entry in ridbag with rid=#245:-13
	DB name="xxx"
3. From then on the database is completely blocked. Even if we cut the load from the database and only insert one single vertex, we receive:
com.orientechnologies.orient.server.distributed.task.ODistributedOperationException: quorum of '3' not reached, responses: [node: xxx-odb-orientdb-0 success,concurrent modification record (node xxx-odb-orientdb-2): #119:2 database version: 109 transaction version: 108,concurrent modification record (node xxx-odb-orientdb-1): #119:2 database version: 109 transaction version: 108]

## Steps to reproduce  
I don't have a minimal example to reproduce the issue, but I can reproduce it on our database. I can provide a heapdump or stacktrace of the database in the blocked state if required. Please let me know if you need more info.

**Comment by wolf4ood** [comment]
Hi @jonsalvas 

yes the dump and stack trace would be helpful as well as the dump of the record which give the exception like in this case ` #119:2` taken from all the nodes.

you can send them to `e.risa@sap.com`. 

Thanks
