### ISSUE TITLE
dropClass fails when class name contains dash

### ISSUE THREAD

**Issue by wmccusker** [orientechnologies/orientdb#9087]
## Expected behavior  
Expected that when "dropClass" is called for a class name that contains a dash that it succeeds.

## Actual behavior  
Actual behavior is that an exception is thrown that the command cannot be parsed.

## Steps to reproduce  
1. Use OSchema to create a new class named "test-class" 
2. OSchema method "dropClass" with the same name. An exception is thrown.

The same behavior is observed trying to use SQL to execute the drop class.
See attached junit 4 test where "dropClass" throws an exception when a dash is in the class name.
[UnitTestClasses.zip](https://github.com/orientechnologies/orientdb/files/3952793/UnitTestClasses.zip)

**Comment by wmccusker** [comment]
Forgot a class that wraps the creation of the OServer, attaching a new zip that contains both classes.
[UnitTestClasses.zip](https://github.com/orientechnologies/orientdb/files/3952793/UnitTestClasses.zip)

**Comment by luigidellaquila** [comment]
Hi @wmccusker 

Thank you very much for reporting, I managed to reproduce and fix the issue.

The fix will be released with v 3.0.27

Thanks

Luigi

**Comment by wmccusker** [comment]
Thanks for the quick fix!
