### ISSUE TITLE
INFO: Local queue for database 'allevents' is full, cannot process further requests [ODistributedWorker]

### ISSUE THREAD

**Issue by efenzha** [orientechnologies/orientdb#9090]
### OS: <os here>  
Linux 2.6.32-696.16.1.el6.x86_64 x86_64

## Expected behavior  
No such INFO  

## Actual behavior  
OrientDB prints this INFO a lot.

2019-12-12 10:40:53:860 INFO  [01901] Local queue for database 'allevents' is full, cannot process further requests [ODistributedWorker]

## Steps to reproduce  
Writing massive data to OrientDB continuously. 

**Question**:
What is the meaning of this INFO? What shall I do to solve the problem behind this INFO?

**Comment by wolf4ood** [comment]
Hi @efenzha 

this means that the replica has a lot of message to process in the queue. Usually that's only an info.


You could increase the queue size but also increase the workers number.

See here

http://orientdb.com/docs/3.0.x/admin/Configuration.html#distributeddbworkerthreads

the two configs are 
```
distributed.dbWorkerThreads
```

and 

```
 distributed.queueMaxSize
```

Let me know if that helps.

**Comment by efenzha** [comment]
Hi @wolf4ood ,

Yes, it works. After setting these two parameters, this INFO disappears. 
Thanks!
