### ISSUE TITLE
create index error when property names are numbers

### ISSUE THREAD

**Issue by wmccusker** [orientechnologies/orientdb#9092]
## Expected behavior  
As a user I need to be able to create an index on properties of a class that a numbers, e.g. "1" or "2"

## Actual behavior  
When I use create index with property names that are numbers I the following exception.

com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
create index _idx_me on IndexMe ( 1, 2 ) UNIQUE STRING, STRING

## Steps to reproduce
This snippet of code reproduces the issue. The properties are created without issue however the call to "createIndex" fails with the exception mentioned above.
 
try (ODatabaseDocument connection = getConnection()) {
            ODocument doc = new ODocument("IndexMe");
            doc.setProperty("1", "one");
            doc.setProperty("2", "two");
            doc.save();

            OClass oclass = connection.getMetadata().getSchema().getClass("IndexMe");
            oclass.createProperty("1", OType.STRING).setMandatory(false);
            oclass.createProperty("2", OType.STRING).setMandatory(false);

            oclass.createIndex("_idx_me", INDEX_TYPE.UNIQUE, "1", "2");
        }

**Comment by luigidellaquila** [comment]
Hi @wmccusker 

I managed to reproduce and fix the problem, the fix will be released with v 3.0.27

Thanks

Luigi

**Comment by wmccusker** [comment]
Thanks!
