### ISSUE TITLE
Performance issue  When a vertex link with millions of edges 

### ISSUE THREAD

**Issue by zfaster** [orientechnologies/orientdb#9093]
## Steps to reproduce  
When there are millions of edges on a vertex , it will be very slow to operate this vertex , such as adding another edge, and the more edges on the vertex , the more performance degradation is more obvious

How to optimize this scenario to improve vertex storage and modification performance?

**Comment by Jotschi** [comment]
I had a similar problem and ended up removing the edges and replacing them with indices.

See also this stackoverflow question:
https://stackoverflow.com/questions/58730049/how-to-improve-write-performance-in-orientdb-graph-for-supernodes

**Comment by zfaster** [comment]
@Jotschi thank you
After verification, the performance of orientdb is too poor when the node contains a large number of relationships. The performance degradation of nodes with more than 10,000 relationships is very severe. In the end, I can only switch to neo4j
