### ISSUE TITLE
size() counts incorrectly

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9095]
### OS: Linux

I have a simple query:
```sql
select scopeItems.risks from #75:2
```
Which returns me:
```json
{"@type":"d","@rid":"#-2:0","@version":0,"scopeItems":["#81:14","#81:18","#81:16","#81:17","#82:17","#81:22","#82:18","#82:20","#81:25","#82:14","#81:19","#81:23","#82:19","#82:15","#81:24","#81:20","#82:16","#81:21"],"@fieldTypes":"scopeItems=z"}
```
As you can see - there are 18 records.
But if I execute the following query:
```sql
select scopeItems.risks.size() from #75:2
```
It returns:
```
{"@type":"d","@rid":"#-2:0","@version":0,"scopeItems":28}
```
28 records?! How might that be?

## Expected behavior  
18 records

## Actual behavior  
returns wrong number: 28

**Comment by luigidellaquila** [comment]
HI @PhantomYdn 

I'd say it's pretty strange. What kind of data type is `risks`? Any chance to have a copy of the db to test it?

(btw, I see you are using v 2.x, which version exactly? In general, if you have a chance to do it, I'd suggest to try 3.0.x)

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila ,
We use version 2.2.37. I can share with you docker version with DB embedded over dropbox or google Drive. Please share email to which I can send invite.

**Comment by luigidellaquila** [comment]
HI @PhantomYdn 

Please send it to l.dell-aquila AT sap dot com

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila , thank you! Just shared with you database.
You can either run a provided docker or pick OrientDB database from `runtime/databases/Orienteer`
Username / password can be found in docker-compose.yml
