### ISSUE TITLE
how to fix "Relationship content is invalid on field" 

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#9098]
## Expected behavior  
I saved a Vertex ( which already had relationships ) and the relation should have persisted ( IMHO ).

## Actual behavior  
the relationship is still there but is empty ( has no in or out vertex ids ).   And I can delete the relationship and recreate it.

I'm getting 
       `Relationship content is invalid on field  ...`

## Steps to reproduce  
not quite sure
Would just like to know how to proceed in removing the broken link and then I can recreate it.

**Comment by luigidellaquila** [comment]
Hi @grimace 

Cleaning up the data should be easy, if you have the edge RID you can manually remove it with 

```
DELETE EDGE #xxx:xxx
```

If it does not work for some reason, you can force the delete with 

```
delete from #xxx:xxx UNSAFE
```

Please check the vertex records, if there are references to the edge in some out/in fields, you can remove them with an UPDATE:

```
UPDATE <theVertexRid> REMOVE out_TheEdgeClass = <theEdgeRid>
```

Thanks

Luigi
