### ISSUE TITLE
Writes cannot be executed in distributed mode when one node becomes unavailable.

### ISSUE THREAD

**Issue by eduardnegru** [orientechnologies/orientdb#9108]
## Expected behavior  
Start a 2 node distributed cluster. When a node goes down, writes should be redirected to the node that is up.

## Actual behavior  
Writes cannot be performed on the cluster anymore.

com.orientechnologies.orient.server.distributed.ODistributedException: No enough nodes online to execute the operation, online nodes:[master2]

## Steps to reproduce  
1) Start a 2 node cluster(master1, master2) using dserver.sh.
2) Close dserver.sh from from the first server, master1.
3) Go to OrientDB Studio using the IP of the healthy node.
4) Edit a node. For example, edit the country name of a node from the demo database.

The default-distributed-db-config.json on both servers:
```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": []
    }
  }
}
```

The issue relates to the closed issue [1], but the solutions provided did not solve the problem.
Reads work as expected.

[1] [https://github.com/orientechnologies/orientdb/issues/6918](url)

**Comment by wolf4ood** [comment]
Hi @eduardnegru 

you have 2 nodes and the `writeQuorum` is majority.

That is calculated with the formula `N/2+1`, so in your case 2.

That's why you are not able to write. 

You should use 3 nodes to have High availability in writes

Let me know if that helps

Thanks

**Comment by eduardnegru** [comment]
I will try a 3 node setup as soon as possible and tell the result. However, if a node goes down, N should become 1 resulting in N/2 + 1 = 0 + 1 = 1. I am using "newNodeStrategy": "dynamic", so shouldn't N change when nodes go offline/online?

**Comment by eduardnegru** [comment]
I also tried using writeQuorum: 1, and the problem still persists.

**Comment by eduardnegru** [comment]
I have tested with a cluster of 3 nodes and writes can be executed successfully when 1 node fails. 

But still, why can't I execute writes when 1 out of 2 nodes is down with a writeQuorum = 1 and "newNodeStrategy" = "dynamic", shouldn't N change when nodes go up/down?

**Comment by eduardnegru** [comment]
*** New discoveries ***

The following line is logged when closing 'master3' node in 'master1' and 'master2' console.
```
2020-01-20 16:03:59:662 INFO  [master6] Removing server 'master3' from all the databases (removeOnlyDynamicServers=true)... [OHazelcastPlugin]
```

**Comment by eduardnegru** [comment]
The problem is that I had an old distributed-config.json in the /databases/demo/ folder that had static configurations from an old default-distributed-config.json. I had to delete the distributed-config.json from both machines, restart the cluster and it worked well. distributed-config.json is copied from /config to /databases at startup. It is copied only once and subsequent changes to default-distributed-config.json do not affect /databases/distributed-config.json.
