### ISSUE TITLE
Cannot execute with UPDATE PUT/ADD/INCREMENT new executor: ADD members = #xxxx:xxx DB name="XXXX"

### ISSUE THREAD

**Issue by fortuneyan** [orientechnologies/orientdb#9111]
### OS: <os here>  
windows 10

## Expected behavior  
Add a new link target to exist LINKSET by SQL like:
update #13:358 add members = #151:160
## Actual behavior  
Oritent DB Ver3.0.23 popup error message: "Cannot execute with UPDATE PUT/ADD/INCREMENT new executor: ADD roles = #xxxx:xxx"
## Steps to reproduce  
 
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>
class property MyTeam.members defined as LINKSET, could not use SQL:
 update <recordid: #xxx.xx> ADD members = <userid: #xxx.xxx>.

but insteadof 'ADD', 'SET/REMOVE' work well

**Comment by luigidellaquila** [comment]
hi @fortuneyan 

Can you please try the following:

```
update #13:358 SET members = members || #151:160
```

it should work fine

Thanks

Luigi

**Comment by fortuneyan** [comment]
Greate! it works

**Comment by ebingeorgedct** [comment]
how to use isSet() with this query , to add only if it does not exist in the array ?
