### ISSUE TITLE
Fulltext Index with Lucene: boost option does not work

### ISSUE THREAD

**Issue by apetropavlovskiy** [orientechnologies/orientdb#9118]
## Expected behavior  
`SELECT FROM City WHERE SEARCH_CLASS("+name:cas*  +description:beautiful", {
"allowLeadingWildcard": true ,
"boost": {
    "name": 2
} } ) = true`  

## Actual behavior  
Error: java.lang.ClassCastException: **java.lang.Integer** cannot be cast to **java.lang.Float**  

## Steps to reproduce  
`SELECT FROM City WHERE SEARCH_CLASS("+name:cas*  +description:beautiful", {
"allowLeadingWildcard": true ,
"boost": {
    "name": 2.0f
} } ) = true`

## Returns:
Error: java.lang.ClassCastException: **java.lang.Double** cannot be cast to **java.lang.Float**

**Comment by wolf4ood** [comment]
Hi @apetropavlovskiy 

how are you running this query?

Studio or Java API?

Thanks

**Comment by wolf4ood** [comment]
Hi @apetropavlovskiy 
i've just landed a fix. It will be available in the next release or snapshot after test validation here
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.28-SNAPSHOT/


Thanks

**Comment by apetropavlovskiy** [comment]
Thank you!
