### ISSUE TITLE
Run OrientDB in Context to manage Studio redirect

### ISSUE THREAD

**Issue by christian-bettermann** [orientechnologies/orientdb#9120]
### OrientDB Version: latest

General Problem is that OrientDB isn't able to work with a reverse Proxy, at least I don't know how if possible.
I have an OrientDB Docker Running in my Kubernetes Cluster on Google Cloud Platform. To access the Pod running this Container, I have build an Ingress. The Ingress is accessible at domain.com/abc/ . 
When I make a request to this endpoint the OrientDB Conatiner is starting the Studio. The Studio ist started with an absolute meta redirect. Therefore I get an error because the Container can't run at domain.com/studio/index.html,but in my /abc/ context. The Problem is that the OrientDB is working with absolute links.

Is there a way to run OrientDB in a context? Is there a way to solve this by changing the metadata of the OrientDB Configs?

## Expected behavior  
I need a solution that makes the OrientDB work in the Context of my directory: domain.com/abc, that would answer my request with domain.com/abc/studio/index.html. 

## Actual behavior  
The answer is out of context because the Studio meta redirect is absolute. The request is answered without my /abc/ Path

**Comment by wolf4ood** [comment]
Hi @christian-bettermann 

dunno for GCP on the ingress, but usually behind nginx or apache i did in the past url rewrite with proxy pass, and it did work. There is not config currently on the context.
