### ISSUE TITLE
Simple index overriding composite index

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9121]
## Expected behavior  
Composite index that fully matches the query is used instead of using the simple index and then filtering.

## Actual behavior  
The simple index is used and filtering is applied over the index result

## Steps to reproduce  

I'm running the schema at the end of the page. I notice a big slow down and with an "explain" I got this result where the simple index is used instead of using the compose index.

+ FETCH FROM INDEX IndexTest.e
  e = ''
+ EXTRACT VALUE FROM INDEX ENTRY
  filtering clusters [17,25,26,18,19,20,21,22,23,24]
+ FILTER ITEMS WHERE 
  d = '' AND f = '0' AND g = '0' AND a = '100'
+ FILTER ITEMS BY CLASS 
  IndexTest

In my case the field "e" has very low dispersion and the field "a" dispersion is enormous. Which then leads to the slow down when running the query.

I've taken a look at the code in OSelectExecutionPlanner method findBestIndexFor and I think that the problem is that the index cost of the simple index is better than the composite index, this prevents the composite index for being used. I think that it would be better to first select the index based on number of fields indexed and then filter by cost.

The schema structure that I'm using

CREATE CLASS IndexTest EXTENDS V;
CREATE PROPERTY IndexTest.a STRING;
CREATE PROPERTY IndexTest.b STRING;
CREATE PROPERTY IndexTest.c STRING;
CREATE PROPERTY IndexTest.d STRING;
CREATE PROPERTY IndexTest.e STRING;
CREATE PROPERTY IndexTest.f STRING;
CREATE PROPERTY IndexTest.g STRING;

CREATE INDEX IndexTest.a NOTUNIQUE_HASH_INDEX;
CREATE INDEX IndexTest.b NOTUNIQUE_HASH_INDEX;
CREATE INDEX IndexTest.c NOTUNIQUE_HASH_INDEX;
CREATE INDEX IndexTest.d NOTUNIQUE_HASH_INDEX;
CREATE INDEX IndexTest.e NOTUNIQUE_HASH_INDEX;
CREATE INDEX IndexTest.f NOTUNIQUE_HASH_INDEX;
CREATE INDEX IndexTest.g NOTUNIQUE_HASH_INDEX;

CREATE INDEX composeIndex ON IndexTest (a, d, e, f, g) NOTUNIQUE;
CREATE INDEX composeIndex1 ON IndexTest (a, b, d, e, f, g) NOTUNIQUE;
CREATE INDEX composeIndex2 ON IndexTest (b, d, e, f, g) NOTUNIQUE;

**Comment by luigidellaquila** [comment]
Hi @madmac2501 

Indexes with multiple fields should already be selected first, I'll double-check and let you know

Thanks

Luigi

**Comment by madmac2501** [comment]
@luigidellaquila  Did you check the index selection criteria with indexes with multiple fields?

Thanks

**Comment by luigidellaquila** [comment]
Hi @madmac2501 

I managed to reproduce the problem launching the following two queries in sequence

```
select from IndexTest where e = '';
select from IndexTest where e = '' and d = '' AND f = '0' AND g = '0' AND a = '100';
```

The problem here is that the choice of the index is based on statistics on index "efficiency" that are collected at runtime. 
Running the first query, the execution planner collects stats about `IndexTest.e`; running the second query, the execution plan has no stats about `composeIndex` but it has stats on `IndexTest.e`, so it assumes that it is better and picks it.

I'm working to make this stats collection more dynamic (ie. pre-collect index stats in a different way and use single property indexes to predict composite index stats), so in the near future it should be more accurate.

Thanks

Luigi

**Comment by madmac2501** [comment]
Thanks a lot!

**Comment by madmac2501** [comment]
Hi @luigidellaquila, any update on this ticket?

**Comment by madmac2501** [comment]
3.0.33 is still affected by this issue.

any update on this?

**Comment by madmac2501** [comment]
I tested in 3.0.34 and it worked for me, thanks!
