### ISSUE TITLE
Release 3.0.28 on Docker HUB

### ISSUE THREAD

**Issue by leszekgruchala** [orientechnologies/orientdb#9135]
Version 3.0.28 was released a week ago, together with Java SDK, but there is no docker tag.
https://hub.docker.com/_/orientdb?tab=tags&page=1

Thanks

**Comment by luigidellaquila** [comment]
Hi @leszekgruchala 

It's just taking a bit more than expected (there was an error in the dockerfiles and I had to re-submit the release), hopefully it will be available in next few hours

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @leszekgruchala 

Now you can find OrientDB v 3.0.28 on DockerHub https://hub.docker.com/_/orientdb

Thanks

Luigi
