### ISSUE TITLE
Record ID and Cluster behavior

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientdb#9138]
### OrientDB Version: 3.0.x

Hi guys, i have a little question about the rid's behavior, [here](http://orientdb.com/docs/3.0.x/datamodeling/Concepts.html#record-id) according to the documentation about RID you say: 
> The format is like this:
>
>#cluster:position.
>
>Cluster Identifier: This number indicates the cluster to which the record belongs. Positive numbers in the cluster identifier indicate persistent records. Negative numbers indicate temporary records, such as those that appear in result-sets for queries that use projections.
>
>Position: This number defines the absolute position of the record in the cluster.
>
>NOTE: The prefix character # is mandatory to recognize a Record ID.
>
>Records never lose their identifiers unless they are deleted. When deleted, OrientDB never recycles identifiers. Additionally, you can access records directly through their Record ID's. For this reason, you don't need to create a field to serve as the primary key, as you do in Relational databases.

And later about [Clusters](http://orientdb.com/docs/3.0.x/datamodeling/Concepts.html#cluster) you say:
>Beginning with version 2.2, OrientDB creates additional clusters for each class, (one for each CPU core on the server), to improve performance of parallelism.

So my question is: If I deploy my database on a server with four cores, and then change to a server with more or less cores. Does this affect my existing RIDs? Will all my RIDs always remain the same? How does OrientDB adjust existing clusters to the new server with more or less cores?

**Comment by luigidellaquila** [comment]
Hi @alexmm11 

The clusters for a class are created when you create the class itself, so they never change, even if you move the DB to a different server (unless you alter the class manually of course).
In general, you can rely on a high level rule: record IDs are immutable, a record will always have the same RID

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Just for completeness, record IDs become immutable as soon as the record is persisted (eg. the transaction is committed)

Thanks

Luigi

**Comment by alexmm11** [comment]
@luigidellaquila Ok, thanks man!
