### ISSUE TITLE
[SEARCH] Error using boost (ClassCastException)

### ISSUE THREAD

**Issue by mpomet** [orientechnologies/orientdb#9142]
## Expected behavior  
Using `boost` works

## Actual behavior  
Using `boost` leads to an error:
`java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float`

## Steps to reproduce  
```SQL
CREATE CLASS MyClass EXTENDS V;
CREATE PROPERTY MyClass.title STRING;
CREATE PROPERTY MyClass.description STRING;

CREATE INDEX MyClass.fulltxtindex ON MyClass(title, description) FULLTEXT ENGINE LUCENE;

INSERT INTO MyClass (title, description) VALUES ("my test", "qwerty");
INSERT INTO MyClass (title, description) VALUES ("qwerty", "my test");


SELECT $score, title, description FROM MyClass
WHERE SEARCH_CLASS("test", {
    "boost": {
        "title": 2,
        "description": 1
    }
}) = true;
```

Same behaviour with `2.0` as value

**Comment by mpomet** [comment]
@luigidellaquila Is there something wrong with my syntax or is there any chance to have this bug fixed ?

**Comment by luigidellaquila** [comment]
Hi @mpomet 

I just tested it with latest snapshot and it works fine.
We have some recent fixes on Lucene index querying, so there is a chance it is already fixed

Thanks

Luigi

**Comment by mpomet** [comment]
Ok it works with 3.0.29.
@luigidellaquila you can close this issue now thanks
