### ISSUE TITLE
Any plans to remove Hazelcast dependencies in the future?

### ISSUE THREAD

**Issue by ygyg70** [orientechnologies/orientdb#9146]
100% SSL in production environments is becoming the norm these days
Unlike OrientDB and many other open source projects, Hazelcast community edition doesn't support SSL..
Are there any plans to remove Hazelcast as a distributed dependency?

**Comment by tglman** [comment]
Hi @ygyg70,

We do not have plan to remove Hazelcast in short term, to add a bit of prospective we do transmit on Hazelcast only metadata, no data is actually transmitted, is still important to have encryption everywhere, but for OrientDB is less critical the encryption of hazelcast channels.
