### ISSUE TITLE
Backward compatibility in JavaScript db.command()

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#9149]
## Expected behavior  
`db.command()` returns number of changed records

## Actual behavior  
`db.command()` returns `com.orientechnologies.orient.core.sql.parser.OLocalResultSetLifecycleDecorator` with element which contains field `count` with changed records.

As for me this is very inconvenient, because I think that JavaScript must be used in simple functions and this is very verbose for simple function.

## Steps to reproduce  
I created test with demonstration of this behavior: [FunctionTest.java](https://github.com/WeaxMe/orienteer-test/blob/master/orientdb-function-test/src/main/java/com/weaxme/test/function/FunctionTest.java#L45)

Is this new expected behavior of `db.command()` in OrientDB 3 or just not finished feature?

**Comment by wolf4ood** [comment]
Hi @WeaxMe 

it's not an unfinished feature. It's the default behaviour of the new Executor in 3.0.x.
By default it return the count of the updated records

Do you want to return the records also?

check here

http://orientdb.com/docs/3.0.x/sql/SQL-Update.html

return  operator. By default is `COUNT`

Let me know if this helps

Thanks

**Comment by WeaxMe** [comment]
Hello @wolf4ood 
No I want return count of updated records as just number, not result set. I want this feature in JavaScript OrientDB API. 

But if this is not possible, so no problem - I will use new API.

My point was this (this is only for JavaScript API, not for Java API):
`db.command()` returns count of changed queries just like number is more convenient then when it returns result set and need do a lot of actions for retrieve number of changed records. In Java API this is not a problem, because we develop big and complex applications in Java. But JavaScript API looks for me as simple API which can be used in simple scripts inside Java applications, thus I want more simple API in JavaScript OrientDB API.

This is not a problem, this is just my wish.

Thank you for your attention.

**Comment by wolf4ood** [comment]
Hi @WeaxMe 

i get your point but the API exposed in JS are the same as Java.

You could do something like this for one-liner 

```JS
var count  = db.command("update OUser set firstName='Test' where name = ?", "reader").next().getProperty("count");

return {
  count : count
}
                                                                                                     
```

Thanks

**Comment by WeaxMe** [comment]
This is exactly right. But JavaScript is not Java, so method `getProperty()` is uneccessary. Even if `db.command()` return result set, but not count of changed records, so it will be better if API will be like this:
```
var result  = db.command("update OUser set firstName='Test' where name = ?", "reader");

var element = result.next();
var count = element.count;

return {
  count : count
}
         
```
Why we can't use JavaScript object here? As for me this is convenient.

My main point is about simplify JavaScript API. 

Let's look in code which looks ideally for me (even `db.command()` returns result set):
```
var result  = db.command("update OUser set firstName='Test' where name = ?", "reader");

var element = result[0];  // without method result.next()
var count = element.count; // without method element.getProperty()

return {
  count : count
}
         
```

**Comment by wolf4ood** [comment]
Hi @WeaxMe 

that's because we expose in the JS engine the database API. and the results of the query are the same object as Java. and you cannot use the JS syntax. We don't do any conversion to JS objects,

**Comment by WeaxMe** [comment]
Hello @wolf4ood 
OK. I see that you don't do any conversions to JS objects. Will you do conversions to JS objects in future?

**Comment by WeaxMe** [comment]
Thanks for your attention. I close this issue, because there is no answer on last question during long period of time
