### ISSUE TITLE
Error while set role rules

### ISSUE THREAD

**Issue by blackmittel** [orientechnologies/orientdb#9153]
### OS: Windows 7  
###also
## Expected behavior  
correct updating of ORole rules field 

## Actual behavior  
Message
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot execute with UPDATE PUT/ADD/INCREMENT new executor: PUT rules = "database.class.*", 15
        DB name="tst"
        DB name="tst"

### start orientdb console and connect to database
orientdb {db=tst}> insert into ORole set name = 'developer', mode = 0;
orientdb {db=tst}> update ORole put rules = "database.class.*", 15 where name = "developer";

**Comment by wolf4ood** [comment]
Hi @blackmittel 

PUT/ADD/INCREMENT are not available in the new executor 3.0.x

try 

```
update ORole set rules["database.class.*"] = 15 where name = "developer";
update ORole remove rules["database.class.*"]  where name = "developer";
```

Here the link to the new SQL reference

http://orientdb.com/docs/3.0.x/sql/SQL-Update.html

Let me know if this helps

Thanks
