### ISSUE TITLE
Edges between edges

### ISSUE THREAD

**Issue by toledoroy** [orientechnologies/orientdb#9154]
## Expected behavior  
edges between edges

## Actual behavior  
Exception:
com.orientechnologies.orient.core.exception.OCommandExecutionException: Invalid vertex for edge creation

## Steps to reproduce  
CREATE EDGE E from (SELECT from E LIMIT 1) to (SELECT from E LIMIT 1) ;

Hi Luca
I working on a semantic graph prototype that's currently on mango, and I would really love to migrate to your engine. However, there are some constraints that limit what seems to be a natural capability. 
Is there any way to make this constraint optional perhaps? 
This will really make your engine far more powerful in the long run.  

[Sorry if the request is inappropriate]

**Comment by toledoroy** [comment]
Real world example

Person1 -Friend-> Person2
                | Better / closer 
Person1 -Friend-> Person3

**Comment by luigidellaquila** [comment]
Hi @toledoroy 

I'm not sure why you need to create edges between edges. Edges are supposed to connect vertices, this is a natural concept in property graphs.

This said, in OrientDB you can define class hierarchies with multiple inheritance, so you can have a class that extends both V and E. This *should* be enough to work around that specific check, but I STRONGLY SUGGEST YOU TO AVOID FORCING THE GRAPH MODEL THIS WAY, and I can expect other significant problems after that.

sample code:
```
CREATE CLASS MyEdgeVertex EXTENDS V, E;

create vertex V set name ='a';
create vertex V set name ='b';
create vertex V set name ='c';

create edge MyEdgeVertex from (select from V where name = 'a') to (select from V where name = 'b')
create edge E from (select from MyEdgeVertex) to (select from V where name = 'c')
```

Thanks

Luigi

**Comment by toledoroy** [comment]
Thank you so much @luigidellaquila !
This workaround seems to work.

Well, I'm trying to go a little beyond the standard graphs and represent real-life objects and relationships, so this is a must. I'm sure you'll see more such usage in the future as people try to fit more complex entities into their DBs. I am kind of surprised though that such a flexible product like yours doesn't support this... Is that due to visualizations issues? Because I do have this working flawlessly on MongoDB.

As expected, the studio's visual graph can't cope with that. What other issues do you expect I'll run into with this structure?  (The machine did just crash once as I was messing with the studio)

**Comment by abrandst** [comment]
A better way would be to do what is refered to in semantic web technologies as reification: In essence, make your Edge that you want to describe a vertex. So instead of Anne being friends(Edge) with Bert, Anne and Bert both have an edge to a Friendship (Vertex), that can have additional properties. 

A side effect of this is that this model suddenly allows for three-way friendships  - you might want to prevent this in the application software.

**Comment by toledoroy** [comment]
Thanks for the advice @abrandst 
I already have the entire architecture up and running on Mongo, I'm just trying to see if I can migrate it.
