### ISSUE TITLE
 Error "java.net.SocketException: Too many open files" when create class

### ISSUE THREAD

**Issue by thanhphi0401** [orientechnologies/orientdb#9157]
## Expected behavior  
Created success, not raise any error

## Actual behavior  
  java.net.SocketException: Too many open files

## Steps to reproduce  
My OrientDB system has over 100 classes with over 50GB data, setup in cluster mode with 6 node.
1. Open console (run ./console) and login to server....
2. Run command "create class ..." -> nothing problem
3. Run command "create property ..." -> nothing problem
4. Run command "create index....." -> nothing problem
..........................
4. Run command to create other class  : "create class gameapp_platform extends V", it has been error .
Detail error: 
`Error on client connection
java.net.SocketException: Too many open files (Accept failed)
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:188)
`
I've tried create again but still has this error. Cluster seem to be failed.
I've set **ulimit open file** for linux but seem to be not working.

Please help me. 
Thank you

**Comment by laa** [comment]
Hi, do you have several nodes installed on the same server?

**Comment by quanghaisoft** [comment]
only one node on one server/IP

**Comment by quanghaisoft** [comment]
![ordn](https://user-images.githubusercontent.com/10042800/75545368-b942b500-5a58-11ea-87b2-f8a4c830f278.jpg)

**Comment by quanghaisoft** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/10042800/75545440-e68f6300-5a58-11ea-9b86-1ccb93ee7fa4.jpg)

**Comment by quanghaisoft** [comment]
cluster mode with 6 node on 6 server.but if i drop some class ,the error disappear

**Comment by laa** [comment]
I see how many connections do you have? Could you send me the output of the server during the start?

**Comment by 1412392** [comment]
> I see how many connections do you have? Could you send me the output of the server during the start?

![image](https://user-images.githubusercontent.com/32038840/75546722-cd3be600-5a5b-11ea-84a1-67270b7fd584.png)
you can see, about 56 connections now, some time up to 200 connections .

**Comment by 1412392** [comment]
> I see how many connections do you have? Could you send me the output of the server during the start?

![image](https://user-images.githubusercontent.com/32038840/75546908-476c6a80-5a5c-11ea-882d-ff0b5492a3ba.png)
after start success, this is status.

**Comment by laa** [comment]
Send me all server log just from the begging

**Comment by 1412392** [comment]
> Send me whole server log just from the begging

5000 line logs, can't send all :)
i will send you what main infomation
![image](https://user-images.githubusercontent.com/32038840/75548022-c5ca0c00-5a5e-11ea-9107-4d818066c97c.png)
Do you need whole log file, i will send for you?

**Comment by laa** [comment]
OK, I have seen what I need, could you send me the current limit of open files inside of OS? Do you use container inside of the cloud?

**Comment by 1412392** [comment]
> OK, I have seen what I need, could you send me the current limit of open files inside of OS? Do you use container inside of the cloud?

No i don't use docker. 
This is current limit
![image](https://user-images.githubusercontent.com/32038840/75557698-13e90a80-5a73-11ea-944f-584a5952d045.png)

**Comment by laa** [comment]
You see you have size 65K open files but database for som reason detects a bigger amount of open files. What you need is to change open files limit in DB to the 32K open files. Using this system property `-Dstorage.openFiles.limit=32000`

**Comment by 1412392** [comment]
it's mean "Dstorage.openFiles.limit" will always set smaller than system limit?

**Comment by laa** [comment]
yes sure, you need to have room to open more files for "system" needs too.

**Comment by 1412392** [comment]
> yes sure, you need to have room to open more files for "system" needs too.

i want to ask more: Do i need to add "LimitNOFILE=<number limit>" to .service file? (because i run orientDB as service on Linux)

**Comment by quanghaisoft** [comment]
> You see you have size 65K open files but database for som reason detects a bigger amount of open files. What you need is to change open files limit in DB to the 32K open files. Using this system property `-Dstorage.openFiles.limit=32000`

OK thanks you very much!

**Comment by 1412392** [comment]
> You see you have size 65K open files but database for som reason detects a bigger amount of open files. What you need is to change open files limit in DB to the 32K open files. Using this system property `-Dstorage.openFiles.limit=32000`

thank you too much for the good solution for us <3
