### ISSUE TITLE
Lastest version 3.0.29 on docker hub

### ISSUE THREAD

**Issue by mpomet** [orientechnologies/orientdb#9159]
Hello,

I need to use the latest version of OrientDB (3.0.29) with docker.
Can you push the image to docker hub ?

Thank you

**Comment by luigidellaquila** [comment]
Hi @mpomet 

I just submitted the PR to docker hub, it will probably take a few hours to be merged

Thanks

Luigi

**Comment by mpomet** [comment]
@luigidellaquila It's ok you can close this issue. Thank you
