### ISSUE TITLE
Error "com.orientechnologies.orient.server.distributed.task.ODistributedOperationException: Quorum 5 not reached for request " when create property on class has more million record

### ISSUE THREAD

**Issue by thanhphi0401** [orientechnologies/orientdb#9162]
## Expected behavior  
Created success, not raise any error

## Steps to reproduce  
My OrientDB system has over 100 classes with over 50GB data, setup in cluster mode with 6 node, on 6 different IP.

1. Open console (run ./console) and login to server....
2. Run command to create property on class : "create property news.authorid STRING;", it has been error .
**(Noted: This class has more 1 million record)** 
Detail error
```
orientdb {db=web}> create property news.authorid STRING;

Error: com.orientechnologies.orient.server.distributed.task.ODistributedOperationException: Quorum 5 not reached for request (id=0.476014 task=command_sql(create property `news`.`authorid` String)). Elapsed=25135ms. Servers in timeout/conflict are:
 - ograph03-73: 132
Received:
 - ograph06-76: waiting-for-response
 - ograph04-74: waiting-for-response
 - ograph05-75: 133
 - ograph02-72: 133
 - ograph03-73: 132
        DB name="web"
        DB name="web"
```
When i see log in service, i see this WARN:
```WARNI [ograph01-71] Timeout (25004ms) on waiting for synchronous responses from nodes=[ograph06-76, ograph04-74, ograph05-75, ograph02-72, ograph03-73] responsesSoFar=[ograph05-75, ograph02-72, ograph03-73] request=(id=0.92998 task=command_sql(create property `news`.`authorid` String) user=#69:0) [ODistributedDatabaseImpl]
2```
In previous time, this error didn't appear, i think maybe OrientDB has problem with big data system. 
Any idea to resolve this problem? 
Please help me

**Comment by quanghaisoft** [comment]
some error please help
![Screenshot_1](https://user-images.githubusercontent.com/10042800/76141563-38a73880-6098-11ea-8852-6f1313f73c22.jpg)
