### ISSUE TITLE
Connect to the Gremlin Server via Java 

### ISSUE THREAD

**Issue by christian-bettermann** [orientechnologies/orientdb#9163]
### OrientDB Version: 3.3.1

How do I build up a proper connection to the gremlin server via Java? I want to parse the graph that is running on localhost. 
The final result should look like this:
* I am able to pass gremlin traversals to the server via java
* I get a response from the server that I can parse through

**Comment by wolf4ood** [comment]
Hi @christian-bettermann 

by default OrientDB tp3 edition spawn a gremlin server. You should use the official java driver against the gremlin server shipped with OrientDB

Let me know if this helps

https://tinkerpop.apache.org/docs/current/reference/#_connecting

Thanks

**Comment by christian-bettermann** [comment]
Yes, i have got it running.
Thanks!

But now I have a different question. Gremlin is always runninga Server for the database "demodb".
I want the Gremlin Server to run a different database in my orientdb. I have tried changing the graph file from "demodb.properties" to "_mydatabase_.properties" and copied the modified file content into it. However, Gremlin is still serving the demodb. How do I change this?

More infos regarding my setup.
I get the container "orientdb:3.0.29-tp3" directtly from docker hub to run it locally. I change a few things for example root password via an interactive /bin/bash in another cmd. I change the gremlin files like that too. Do I have to restart the Gremlin server somehow to make it use the updated files?

**Comment by wolf4ood** [comment]
Hi @christian-bettermann 

yes once changed the `gremlin-server.yaml` the server needs to be restarted

Let me know if this helps

**Comment by christian-bettermann** [comment]
How do I restart it without deleting the container?

**Comment by wolf4ood** [comment]
Hi @christian-bettermann 

i think the clean way would be provide custom config  without modifying directly the files via `/bin/bash/`

**Comment by christian-bettermann** [comment]
Thanks @wolf4ood 
I will try to incluide that.
Thank you!
