### ISSUE TITLE
[Question] filter match any union of 2 arrays?

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9165]
### OS: Windows 10

I have vertices with property `colors` (favorite colors). It's a link array connected to a color class with name for the color name.
I then want to find all people that have either `'red'` or `'blue'` as one of their favorite colors.

I tried to do this:
`select from people where colors.name in ['Green', 'Blue']`

But if there is a person with favorite colors `['Green', 'Red']`, it won't return them. I'm assuming because it would end up doing `['Green', 'Red'] in ['Green', 'Blue']`.

How can I do that then?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

I'd suggest to use `CONTAINSANY` in this case. 
Just for reference, there is also a `CONTAINSALL` operator that checks if all the elements in the right collection are contained in the left one

Thanks

Luigi

**Comment by matanshukry** [comment]
@luigidellaquila cool, that seems to work.

btw, what's the difference between `CONTAINSANY` and `CONTAINS` ? docs seem to have pretty much the same description in different words.

**Comment by luigidellaquila** [comment]
Consider the following

```
[a, b, c] CONTAINSANY [a, d] -> true

[a, b, c] CONTAINSANY [a, b] -> false

[[a, b], c] CONTAINSANY [a, b] -> true
```

I hope it makes sense

Thanks

Luigi

**Comment by matanshukry** [comment]
@luigidellaquila oh that's cool. The docs only talk about a condition when using `CONTAINS` and `CONTAINSANY`, not actual values - might want to add it there.

To clarify, I was comparing these (which is the syntax shown in the documentation):
```
[{'name': 'a'}, {'name': 'b'}, {'name': 'c'}] CONTAINS (name IN ['a', 'd'])
[{'name': 'a'}, {'name': 'b'}, {'name': 'c'}] CONTAINSANY (name IN ['a', 'd'])
```

Am I correct those 2 are the same?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

For the first case yes, they work the same

The two queries below have the same performance

Thanks

Luigi

**Comment by matanshukry** [comment]
Great thanks
