### ISSUE TITLE
[Bug] Database is closed - Locally and in the cloud

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9167]
The same exception happens in 2 environment, so I'll list them both

## Expected behavior
An exception not too happen ? or at least some info on why it happens and how to avoid it

## Actual behavior
Every now and then an exception in the form of database is closed will be thrown. example:
```
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'remote:localhost/mydb/mydb' is closed
	DB name="mydb"
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.checkOpenness(ODatabaseDocumentAbstract.java:2255) ~[orientdb-core-3.1.0-M3.jar:3.1.0-M3]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.rollback(ODatabaseDocumentAbstract.java:2086) ~[orientdb-core-3.1.0-M3.jar:3.1.0-M3]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.rollback(ODatabaseDocumentAbstract.java:2081) ~[orientdb-core-3.1.0-M3.jar:3.1.0-M3]
```

## Steps to reproduce  
This seems to happen randomly

## Notes

1. The exception happens both in the cloud and locally. Locally it's all running on my computer, so there is no network issues that can interfere
2. At first I thought the exception only happen when the connection hasn't been used for some time, but it seems not true;
for example, I've done 4 calls in a minute, and the fourth caused the exception.

**Comment by tglman** [comment]
Hi,

This seems like an instance of the database was bound to the thread local while it was closed, or that the `OrientDB` context was closed before the session instance spawn from it was closed.

let me know if this info helps.
Regards

**Comment by matanshukry** [comment]
@tglman I don't know, but I've been using the database on a daily basis and I haven't seen this exception since. It was probably fixed, either on your side or mine.

If it happens again I'll reopen this issue
