### ISSUE TITLE
High CPU utilization for OrientDB - JDBC pool

### ISSUE THREAD

**Issue by omiadgaonkar** [orientechnologies/orientdb#9170]
### OS: windows and linux
tomcat 7.5

## Expected behavior  
Low CPU utilization or decrease of CPU after query is executed

## Actual behavior  
Orientdb process keep on having almost 45-50% cpu utilization out of 4 cores. It keep on utilization unless I shut down my application server. I am using JDBC connection pool

## Steps to reproduce  
Initiliasing connection pool :
 OrientDBConfigBuilder poolCfg = OrientDBConfig.builder();
    poolCfg.addConfig(OGlobalConfiguration.NETWORK_TOKEN_EXPIRE_TIMEOUT, 240);
    poolCfg.addConfig(OGlobalConfiguration.DB_POOL_MIN, 2);
    poolCfg.addConfig(OGlobalConfiguration.DB_POOL_MAX, 5);
    OrientDBConfig orientDBConfig = poolCfg.build();
    OrientDB orientDB = new OrientDB(OrientDbConFactory.SERVER,OrientDbConFactory.USER,OrientDbConFactory.PASSWORD,orientDBConfig);

ODatabasePool pool = new ODatabasePool(orientDB,databasename,OrientDbConFactory.USER,OrientDbConFactory.PASSWORD, orientDBConfig);
    connPool.put(projectId,pool);
---------------------------------------
 OResultSet rs;
    try(ODatabaseSession ses_orient = getConnPool(projectId).acquire();){
        rs = ses_orient.query(query);
        ...
        some operations
        ...
    }finally{
       rs.close()
    }

**Comment by tglman** [comment]
Hi,

From your example it looks all fine, do you have a reproducer for test the problem?

Regards
