### ISSUE TITLE
Server cluster is not working(distributed server)

### ISSUE THREAD

**Issue by la6803** [orientechnologies/orientdb#9171]
### OS: <os here>  centos8

Orientdb was installed on three different computers and the cluster was configured. (modified sudo nano /opt/orientdb/config/hazelcast.xml, sudo nano /opt/orientdb/config/default-distributed-db-config.json, sudo nano /opt/orientdb/config/orientdb-server-config.xml )

However, many errors occurred on each server.
![image](https://user-images.githubusercontent.com/62277355/76840514-add5f300-687a-11ea-8ed8-312d3f67e3ba.png)
![image](https://user-images.githubusercontent.com/62277355/76840617-d827b080-687a-11ea-8a14-32e907ed3b95.png)

How should I fix this error? Help!

**Comment by tglman** [comment]
hi @la6803,

This error seems to come from miss-configuration, first error seems to have a wrong json in default-distributed-db-config.json, the second errors seems that some network ports where wrongly set in the configurations files.

Double check your configurations files and let us know.

Regards
