### ISSUE TITLE
[Feature Request] Match with "movement" direction

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9172]
# Explanation
Currently when we use `match` we can either follow the direction `.in()` or `.out()` or `.both()` for both.
This is quite simple and fine when not traversing far from the "root".

However many times directions are logically bi-directional, and when we start traversing a bit more "further away" (even just 2 or 3 vertices ahead), .in() and .out() lose their meaning and we need to be creative in how to get it.

# Example

We can take a basic Facebook user/friend example (used little details as possible):
```
User (userId: String)
Friend (in: User, out: User, createdAt: int)
```

If we want to find mutual friends, our connection is something like this:
```
target user -> friend(f1) -> mutualFriend -> friend (f2) -> source user
```

Since direction has no meaning, we need to use .both() every time. While the first .bothE() (for f1) will work fine, we don't know the result direction; that is, is target user in or out? is mutual friend in or out?

In this specific case we can solve it "simply" by checking mutualFriend isn't target user nor source user.
But as the use case gets bit more complex, the solutions will as well, and not always easy or possible.

# Example usage

My suggestion would be to have an operator like .in()/.out()/.both(), that would follow the direction. 
With the example above, we could do something like `match {class:Person, as: targetUser}.bothE("Friend"){as: f1}.nextV("User"){as: mutualFriend}`

.next() in this case will match differently depending on the edge friendship; if targetUser is 'in' for 'f1', 'mutualFriend' will be out; and vice versa.

This can go on more than once, of course.

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

Thank you for suggesting it, this is a general problem and your solution is really interesting from the point of view of usability.
Even though you can already do it using `$matched` and `$currentMatch`, it's definitely complicated.

On the technical side it's not trivial to implement, but not impossible.
I'm marking it as an enhancement and I'll try to work on it ASAP

Thanks

Luigi
