### ISSUE TITLE
[Query Question] Find users and edge info for each - query review + fix?

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9173]
# Question

Assuming the following model:

```
User (userId: string)
Friendship (in: Person, out: Person, status: 1=bad, 2=good)
```

Current query:
```
SELECT targetUser, friendship[0]:{*} as friendship, friendshipCreatorUserId[0] as friendshipCreatorUserId, mutualFriends FROM (SELECT targetUser:{*} as targetUser, list(friendship) as friendship, list(friendship.out.userId) as friendshipCreatorUserId, list(mutualFriends) as mutualFriends FROM (SELECT expand(unionAll($a, $b, $c)) LET $a = (MATCH {class:User, as:targetUser, where: (userId != 'matanshukry')}.bothE("Friendship"){where:(status=2),as:f1}.bothV("User"){as:mutualFriend, where:($matched.targetUser != $currentMatch AND userId != 'matanshukry')}.bothE("Friendship"){where:(status=2 AND $matched.f1 != $currentMatch)}.bothV("User"){as:user, where:(userId='matanshukry')} RETURN targetUser, null as friendship, list(mutualFriend.userId) as mutualFriends group by user, targetUser),$b = (MATCH {class:User, as:targetUser, where: (userId != 'matanshukry')}.bothE("Friendship"){as:friendship}.bothV("User"){as:user, where:(userId='matanshukry')} RETURN targetUser, friendship, [] as mutualFriends),$c = (SELECT $current as targetUser, null as friendship, [] as mutualFriends FROM User where (userId != 'matanshukry'))) group by targetUser)
```

- The main problem:
there is no limit to the amount of mutual friends. I tried to add `limit` clause to `let $a`, but it will limit all the rows returned - that is, 5 mutual friends in total, rather than 5 mutual friends for each person

- Also:
1. I'm repeating the same query multiple times: `MATCH {class:User, as:targetUser, where: (userId != 'matanshukry')}` - does all occurrences in the same query return the same data? does orientdb even execute it multiple times or just once?

2.  It looks really complex, and it's mostly because of repeating parts. Is there any way to simplify it?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

I'm pretty sure in this case the subquery is executed multiple times, but you can check the EXPLAIN of the query to be sure. For now, I'm afraid there is no way to split it in a simple way...

To limit the mutual friends (if I got it right) you can simply do the following:

```
RETURN ... list(mutualFriend.userId)[0..5]
```

I hope it helps

thanks

Luigi

**Comment by matanshukry** [comment]
It's not what I meant in the sense that it will still fetch all the `mutualFriend`s, but at least it won't return them all - so that's great!

I was hoping there can be something to make it simpler, but either way I have a feature request that will help as well ( #9174 ) - so I'll close this one. Thanks!
