### ISSUE TITLE
Nested projections in REST API

### ISSUE THREAD

**Issue by Andrjuxa** [orientechnologies/orientdb#9180]
## Expected behavior  
Is it possible to use Nested projections in REST API instead of Fetch Plan, which deprecated ?

**Comment by wolf4ood** [comment]
Hi @Andrjuxa 

in which REST API? if you use command or query you will be able to use nested projection since it uses the new SQL executor

Let me know if you need more info

Thanks

**Comment by Andrjuxa** [comment]
![document](https://user-images.githubusercontent.com/12463504/77157078-b3694e00-6ab1-11ea-8642-ea15678917b9.png)

I meant using instead of fetchPlan in Rest Api GET - Document.

**Comment by tglman** [comment]
Hi,
The direct lookup of records do not support nested projections, and it won't support them in the short future, use the rest query API instead: https://orientdb.org/docs/3.0.x/misc/OrientDB-REST.html#query

Regards
