### ISSUE TITLE
[Feature Request] [SQL Syntax] Collection range specifiers 

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9181]
# Explanation

Currently when selecting a collection one can choose a specific or multiple indices:
```
SELECT path[1,3] from shortestPath(#8:32, #8:10)
```

However, what if we want to select all elements except the 1st? or all elements except the last?

# Example

Syntax:
`[<start>, <end>]`
- start: index of first element. use negative numbers to select an element from the end of the collection.
- end: index of the last element. Use negative numbers to select an element from the end of the collection. if omitted, all elements until the end are selected

note: start may be bigger than end, which will return "reverse elements".

Select all elements from index 2 until 4
- `SELECT path[2,4] from shortestPath(#8:32, #8:10)`

Select all elements from index 1 until the end
- `SELECT path[1,] from shortestPath(#8:32, #8:10)`

Select all elements from 1 item before the last, up until the 2nd item:
- `SELECT path[-1,1] from shortestPath(#8:32, #8:10)`

Select all elements from 2 items before the last, up until 1 item before the last:
- `SELECT path[-2,-1] from shortestPath(#8:32, #8:10)`

# Use Case

I'm using shortestPath which return an array of elements, but:
- The last element is a known element and I don't need it. Since I'm returning a lot of values, I want to omit it.
- The first element is the target, so I want more information about it
- the elements in between are less important, so I only want a few fields about them.

The result of my query once implemented:

`SELECT path[0]:{*} as target, path[1,-1]:{@RID, name} as between FROM (select shortestPath(#8:32, #8:10))`

Which will return:

```
| target | between |
---------------------
| {#8:32, name, location, etc} | [{#8:24, name}, {#8:5, name}] |
```

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

the `[a..b]` and `[a...b]` syntax is already supported, see https://orientdb.com/docs/3.0.x/sql/SQL-Syntax.html#square-bracket-filters
But as of now it does not use negative indexes to select from the end (it's a good idea btw)

I'll keep this issue open and and mark it as an enhancement. I'll see if I can improve it further

Thanks

Luigi
