### ISSUE TITLE
[Query Question] filter based on edge (non-)existence ?

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9182]
### OS: Windows 10

I have a somewhat simple query such as
`SELECT FROM User WHERE userId != 'msh'`

and I want to also return users that don't have a specific direct relationship. I tried something like this:
`SELECT FROM User WHERE userId != 'msh' AND (SELECT FROM like WHERE ( (in.userId = 'msh' AND out = #66:77) OR (out.userId = 'msh' AND in= #66:77 ) ) ) is null`

but it simply returned all records. Debugging the server, it's because the result was a collection with size 0.

I tried to then do this:
`SELECT FROM User WHERE userId != 'msh' AND (SELECT FROM like WHERE ( (in.userId = 'msh' AND out = #66:77) OR (out.userId = 'msh' AND in= #66:77 ) ) ).size() = 0`

But then I got a syntax error.

Is there another way perhaps I'm missing?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

You can try with `AND (SELECT...) = []`, it should work fine

Thanks

Luigi

**Comment by matanshukry** [comment]
Cool it's working greaat!
