### ISSUE TITLE
[Bug] Full Text (search_class) return duplicates?

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9187]
## Expected behavior
Return non duplicate rows

## Actual behavior
Return duplicate rows

## Steps to reproduce
1. Create a vertex with multiple columns
2. Create a full text lucene index on 4 fields
3. Add a row with data in the 4 fields. have 2 of those fields have a common text.
4. Execute the following query: `select from user where search_class('matan*') = true`
  note: in my case 'matan' existed in 2 of the 4 fields

The query returns 3 rows, with the exact same data of the vertex in each row

**Comment by wolf4ood** [comment]
Hi @matanshukry 

which kind of field do you have?

Do you have simple sql snippet to reproduce this issue?

Thanks

**Comment by matanshukry** [comment]
Currently indexes can be in a corrupted state, which I believe was the issue.
I'll try to reproduce it, but the my entire dataset was removed already.

I'm closing it, although I think the fact an index can be in a corrupted state and still "function" is a bug.
