### ISSUE TITLE
exclude() in SQL does not work

### ISSUE THREAD

**Issue by fgnm** [orientechnologies/orientdb#9192]
## Expected behavior  
Get the list of elements inside a class without all `in` and `out` edge information

## Actual behavior  
Empty returned

## Steps to reproduce  
Just copy and paste the example command provided in official documentation: http://orientdb.com/docs/3.0.x/sql/SQL-Methods.html#exclude
```SQL
SELECT EXPAND( @this.exclude( 'out_*', 'in_*' ) ) FROM V
```

Console output:
```
orientdb {db=MyDB}> SELECT EXPAND( @this.exclude( 'out_*', 'in_*' ) ) FROM V


0 item(s) found. Query executed in 0.001 sec(s).
```

**Comment by fgnm** [comment]
I've tried everything but nothing seems to work.. There must be a bug here
```
orientdb {db=D-Game}> SELECT @this.exclude( 'out_*', 'in_*' ) FROM V          

+----+------------------------------+
|#   |@this.exclude('out_*', 'in_*')|
+----+------------------------------+
|0   |                              |
|1   |                              |
|2   |                              |
|3   |                              |
|4   |                              |
|5   |                              |
|6   |                              |
|7   |                              |
+----+------------------------------+

8 item(s) found. Query executed in 0.005 sec(s).
orientdb {db=D-Game}> 
```
The column is always empty so `expand` does not work.
After many failure I've found that this query does more o less the job:
```
SELECT @rid.exclude( 'out_*', 'in_*' ).toJSON() FROM V 
```
However it's very very tricky and I hope that someone could answer as soon as possible,
Many Thanks

**Comment by luigidellaquila** [comment]
Hi @fgnm 

In v 3.0 I'd strongly suggest you to use nested projections instead, eg.

```
select  @this:{!out*, !in*} as a from v
```

or 

```
select expand(a) from (select  @this:{!out*, !in*} as a from v)
```

see https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html#nested-projections

Thanks

Luigi

**Comment by fgnm** [comment]
Many thanks!! I didn't understand that `@this` can be used in nested projection too
