### ISSUE TITLE
[Bug?] Full Text field not finding results

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9193]
## Expected behavior  
Query for rows indexed by lucene return results

## Actual behavior  
Query for rows indexed by lucene return none

## Steps to reproduce  

I'm using the following basic query:
```
SELECT * FROM User WHERE SEARCH_CLASS('Mata*') = true
```
While class `User` has multiple indices but only 1 full text index:
```
|0   |User.all                |[email,firstName,lastName,location]|
```

The query returns 0 results
```
0 item(s) found. Query executed in 0.021 sec(s).
```

While there are 2 rows that have firstName set to 'Matan'

- This seems to only happen on my stage env and not locally, so I can't debug orient source (I can still query the database)
- I tried querying the index, but I'm not really sure the kind of query I need (or even can) do, since it's all very limited. I tried using 'key' for the userId which found a row, but it only returned the key and the @rid, so it wasn't really helpful.

Any other way I can debug this?

**Comment by wolf4ood** [comment]
Hi @matanshukry 

Can you try to rebuild the index and check if it works after?

Thanks

**Comment by matanshukry** [comment]
@wolf4ood 

(1) That seems to solve it - however it happened somehow, and likely will happen again; any way I can query the index or trouble the problem in the future?

(2) When executing the query `REBUILD INDEX User.All` I got an error in the console:
```
Error: java.util.IllegalFormatConversionException: d != java.util.ArrayList
```
Looking at the server logs the operation was successful and there are no logs, so I'm assuming it's only issue with the console reading the response. But thought I'll add it anyway.

**Comment by wolf4ood** [comment]
Hi @matanshukry 

1) if the server crashes, it could happen to leave the index in bad shape. If there is no soft shutdown 

you have to rebuild the lucene indexes since they are not integrated yet to ODB Journal system

2) yeah it should be related to console only

**Comment by wolf4ood** [comment]
Hi @matanshukry 

i'm closing this. Let me know if there is more questions please re-open it 

Thanks :)
