### ISSUE TITLE
Different behavior of distinct() from 2.2.37 to 3.0.30

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#9195]
Having a ODatabaseDocument with masters and details:

SELECT expand(distinct(master)) FROM Detail WHERE name LIKE 'foo%'.

Executed via `com.orientechnologies.orient.core.db.ODatabase.query(String, Object...).`

Using 2.2.37 it returns 1 document.
Using 3.0.30 it returns 3 times the same document, one per each detail, distinct is not working.

Has "distinct()" changed?

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

If you use the legacy API (ie. the old executor) the behaviour should be the same, but if you use the new one (`db.query(String, Object...)`) then yes, I expect different results. 

In general, I'd suggest to use DISTINCT keyword instead, eg.

```
SELECT expand(master) FROM (
   SELECT DISTINCT master FROM Detail WHERE name LIKE 'foo%'.
)
```

Thanks

Luigi

**Comment by diegomtassis** [comment]
Thanks @luigidellaquila
