### ISSUE TITLE
Different query result between 2.2.37 and 3.0.30

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#9199]
We are migrating one of our applications from OrientDB 2.2.37 to 3.0.30.

The following query returns different results depending on the OrientDB version. 

`SELECT  FROM Detail WHERE (name = 'foo' AND master.labels LIKE '%bar%')`

labels is an EMBEDDEDSET.

With 2.2.37 it does return the expected results.
With 3.0.30 it returns 0 documents, regardless we use the old or the new query api.

- `com.orientechnologies.orient.core.db.ODatabase.query(OQuery<?>, Object...)`
- `com.orientechnologies.orient.core.db.ODatabase.query(String, Object...)`

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

What type of objects are `master` and `labels`?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

That's one of the strange behaviours of version <= 2.x that we could not re-implement in the new executor (just because they don't make much sense in general).

LIKE operator is defined on strings, not on EMBEDDEDLIST.

you can try one of the following:

```
SELECT FROM Detail WHERE (name = 'foo' AND master CONTAINS (labels LIKE '%bar%'))
```

Thanks

Luigi

**Comment by diegomtassis** [comment]
Thanks @luigidellaquila 

master is another document connected via a OType.LINK
labels is an EMBEDDEDSET of String

Everything we do is via the java API.

The query you suggested doesn't return any document either.

I'll try to isolate the behavior in an integration test without our application code.

**Comment by diegomtassis** [comment]
@luigidellaquila  I've done some rearch on the topic.

In 2.2.37, LIKE works for EMBEDDEDSET but only when the set contains one element. [See the following test](https://github.com/CompartAG/orientdb-tryouts/blob/issues/9199/2.2.x/src/test/java/com/compart/tec/orientdb/document/Issue9199RegressionTest.java). First scenario passes, second fails.

In 3.0.30 none of the scenarios pass, which seems correct to me. As you said, LIKE doesn't seem a correct operator for a collection. The query you suggested doesn't provide the expected result either.
[See the scenarios here](https://github.com/CompartAG/orientdb-tryouts/blob/issues/9199/3.0.x/src/test/java/com/compart/tec/orientdb/document/Issue9199RegressionTest.java).

**Comment by diegomtassis** [comment]
@luigidellaquila @tglman any progress on this topic?
