### ISSUE TITLE
Any console.sh command involving plocal does not work

### ISSUE THREAD

**Issue by edmiralagic** [orientechnologies/orientdb#9212]
## Expected behavior  
`CONNECT` & `CREATE DATABASE` command to respond with status `OK` 
Actually since the database is running, `CONNECT` should respond with the 'already in use' error
```
Connecting to database [plocal:../../databases/test] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'test'

Error: com.orientechnologies.orient.core.exception.OStorageException: Database is locked by another process, please shutdown process and try again
```

## Actual behavior  
**On 3.0.30:**
- `CONNECT PLOCAL` results in 
```
Connecting to database [plocal:/Orient/databases/test] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'knol'

Error: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.NullPointerException

Error: java.util.concurrent.ExecutionException: java.lang.NullPointerException

Error: java.lang.NullPointerException
```
- `CONNECT REMOTE:LOCALHOST` results in `Connecting to database [remote:localhost/test] with user 'admin'...OK`
- `CREATE DATABASE PLOCAL` results in same error message as `CONNECT PLOCAL`

**On 3.0.18**
- `CONNECT PLOCAL` results in 
```
Connecting to database [plocal:/Orient/databases/test] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'test'

Error: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /Orient/databases/test/test.473.wal

Error: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /Orient/databases/test/test.473.wal

Error: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /Orient/databases/test/test.473.wal

Error: java.nio.file.FileAlreadyExistsException: /Orient/databases/test/test.473.wal
```
- `CREATE DATABASE PLOCAL` results in 
```
Creating database [plocal:/Orient/tester] using the storage type [PLOCAL]...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'tester'

Error: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /Orient/tester/tester.1.wal

Error: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /Orient/tester/tester.1.wal

Error: java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: /Orient/tester/tester.1.wal

Error: java.nio.file.FileAlreadyExistsException: /Orient/tester/tester.1.wal
```

## More info
- This is in a distributed set up with 2 nodes
- dserver starts up fine and all works well as far as transactions go
- Creating a database from studio works as expected, same with connecting
- 3.0.30 was meant as an upgrade from 3.0.18, all binaries and configs are seperate, but they share the same directories for databases (has been abstracted out of the orientdb directory)
- This only occurs in one of our 3 environments (with same binary/configs minor tweaks for hostnames and such), the other two are able to use all plocal functionality in console without issue
- This is not only console.sh, backup.sh also does not work when using a plocal url
- File permissions are not the issue as far as I know, user has rw access to all db files
- Binaries have been deleted and reinserted multiple times
- Server logs don't mention a thing of any of this
- These commands fail for all databases (there are multiple) not just this one test
- Repair database has been run through remote:localhost connection
- Doesn't matter if server is running or not

## Steps to reproduce  
- Navigate to bin folder of orientdb
- Run console.sh
- Execute any command that utilizes plocal
- 3.0.30 > NPE, 3.0.18 FileAlreadyExistsException

I am assuming this is something specific with this environment thats causing orientdb plocal to not work, any ideas?

**Comment by luigidellaquila** [comment]
Hi @edmiralagic 

If you have a server running, you cannot connect in plocal to the same databases, as they are locked by the server 

Thanks

Luigi

**Comment by edmiralagic** [comment]
> Hi @edmiralagic
> 
> If you have a server running, you cannot connect in plocal to the same databases, as they are locked by the server
> 
> Thanks
> 
> Luigi

Hey @luigidellaquila ,

I don't think that is the solution here. I expect to get the "resource already in use" error when trying to connect to these databases but I can't even get that. Also, `CREATE DATABASE PLOCAL` command does not work. This error persists if the server is running or not, I've tried both.

Regards,
Edmir

**Comment by luppu** [comment]
Hello,

I'm experiencing same problem on version 3.0.24. I've tried @luigidellaquila's suggestion but did not solve the issue. I could not connect plocal whether server is running or not. 

Regards,
luppu

**Comment by edmiralagic** [comment]
After some time debugging the conclusion I came to is that there is something in the vm environment, or lack of something, that is causing these issues with plocal. The lack of information in the output logs is the most concerning aspect. I have migrated the binaries/configs/data to a fresh linux vm and everything seems to be working as expected now.

**Comment by luppu** [comment]
> Hello,
> 
> I'm experiencing same problem on version 3.0.24. I've tried @luigidellaquila's suggestion but did not solve the issue. I could not connect plocal whether server is running or not.
> 
> Regards,
> luppu

I've tried with version 3.0.18 on same machine and got same error. But when I tried with version 3.0.9 on the same machine, I could use commands includes plocal.

**Comment by laa** [comment]
Hi guys, please let me know if this issue still actual I will work on it.

**Comment by edmiralagic** [comment]
@laa Since switching over to a new vm I have not experienced this problem anymore (and probably would not be able to reproduce it). If @luppu is not experiencing the problem anymore either, then you guys can probably just ignore it. Thank you.
