### ISSUE TITLE
% in select like queries does not work as expected

### ISSUE THREAD

**Issue by cmichon** [orientechnologies/orientdb#9213]
## select * from ArchaeologicalSites where Name like 'M%en%'
The query above on demodb should give 1 result "Menhir", yet no vertex is returned.

## select * from ArchaeologicalSites where Name like '%%%'
The query above on demodb should return all ArchaeologicalSites vertices, yet no vertex is returned.

**Comment by cmichon** [comment]
I checked on Win10 family PC: same behavior on 3.0.30 community edition, demodb, with JDK 1.8.0_231.

I noticed this bug as well on other graph databases: it's not just related to demodb.

**Comment by luigidellaquila** [comment]
Hi @cmichon 

I just pushed a fix to `develop` branch (ie. next v 3.1.x). I'm considering if I can backport this fix to v 3.0, as it changes the behaviour a bit and typically it's not desirable in a hotfix release

Thanks

Luigi

**Comment by cmichon** [comment]
Thanks @luigidellaquila.

I had a quick look at that commit: it seems in your test you're not testing '?%?%' for instance or '%%%', which would cover the cases you were missing in the previous code. 

I also read in the diff the previous code, and indeed it looks like a big code change, yet I wasn't expecting the like operator to be coded like this. The new code is much leaner.

**Comment by Eric24** [comment]
@cmichon Just for my own education, what is the point of the triple percent syntax? Would a single percent not achieve the "all wildcard" effect"? Or better yet, why not just omit that field from the WHERE clause?

**Comment by luigidellaquila** [comment]
I think the point is to do "%foo%bar%"

Thanks

Luigi

**Comment by cmichon** [comment]
Exactly Luigi.

In the end, while waiting for the fix, I'm using lucene full text indexing.

Great tool!

**Comment by tglman** [comment]
Hi,

The release 3.1.0 is out with this fix, will leave this open just to see if we will backport the fix or not.

Regards
