### ISSUE TITLE
Console or client is hanging when connecting a 'STARTING' database

### ISSUE THREAD

**Issue by efenzha** [orientechnologies/orientdb#9215]
OrientDB Version: orientdb-3.0.21
Java Version:
OS: Linux 2.6.32-696.16.1.el6.x86_64 x86_64

## Expected behavior  
Return the result (successfully connected or an exception) quickly.

## Actual behavior  
Console or the client application is hanging there waiting for database finishes its starting process.

## Steps to reproduce  
1. Setting up a distributed database, one master node and one replia node.
2. Startup two nodes, and they start to do full syncing. 
3. Using Console.sh or a client application which creates OrientGraphNoTx towards **the replia node**.
4. Console or the client application is hanging.

My expectation is the code can return quickly to inform success or exception.

**Comment by tglman** [comment]
Hi,

Thanks for reporting this, reporting an error instead of waiting to be ready is a breaking change, so this will be solved in a major version.

Regards

**Comment by efenzha** [comment]
Hi @tglman ,
Thanks for the reply!
It can also add a 'timeout' parameter.
What does 'major version' mean? 3.0.x or 3.1.x ?
