### ISSUE TITLE
Live Queries issue with cluster target

### ISSUE THREAD

**Issue by wolf4ood** [orientechnologies/orientdb#9216]
https://community.orientdb.org/t/listen-to-events-from-cluster-default/1095

**Comment by stoica-florian** [comment]
@wolf4ood 
This does not seem to work for the following:
`ODatabaseDocument database = dbConnection.getFactory().getDatabase(false, false);
            OLiveQueryMonitor monitor = database.live("select FROM CLUSTER:default", listener);
            database.command("TRUNCATE RECORD [" + String.join(", ", result) + "]", new HashMap<>());
            monitor.unSubscribe();`
