### ISSUE TITLE
Illegal reflective access by org.apache.lucene.store.MMapDirectory

### ISSUE THREAD

**Issue by anandsingh1019** [orientechnologies/orientdb#9218]
After installing ElasticSearch, ES is not accessible at localhst:9200. Following error can be seen in logs:

Note: I have Java 11 installed on machine.

2020-04-19 19:26:18 Commons Daemon procrun stderr initialized
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.lucene.store.MMapDirectory (file:/D:/ElasticSearch/elasticsearch-6.5.1/lib/lucene-core-7.5.0.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.apache.lucene.store.MMapDirectory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by tglman** [comment]
Hi @anandsingh1019,

I do not see a reference to OrientDB in this report, I will close this, please re-open another issue if you have problems with OrientDB.
Regards
