### ISSUE TITLE
Bug: `match` query returns no results in OrientDB Studio via REST API

### ISSUE THREAD

**Issue by NSExceptional** [orientechnologies/orientdb#9221]
***OrientDB Version: 2.2.23***
***Java Version: 1.8***
***OS: Windows 10***

## Expected behavior  
Data is returned

## Actual behavior  
No data is returned

# Background  

I noticed that when I make a `match` query in OrientDB Studio, no results are returned, no matter what. It does work in a project I'm working on, though, which also uses the REST API. For example, this query does return results in ODB Studio:

```sql
select * from Person
```

but this does not:

```sql
match {class:Person, as:P} return $paths
```
When I started inspecting the payloads being sent, I made note of the only difference and tested them both. ODB Studio was sending this payload:

```js
{ command: ..., mode: "graph" }
```

and my project was sending this:

```js
{ command: ..., parameters: null }
```

**Why does one work and the other does not?** I assume this is a bug, because my coworker does not have this problem, despite us being on the same version of OrientDB.

**Comment by luigidellaquila** [comment]
Hi @NSExceptional 

This query has a syntax error:

```
match {class:Person, as P} return $paths
```

vs

```
match {class:Person, as:P} return $paths
```

Could it be the reason for the problem?

Thanks

Luigi

**Comment by NSExceptional** [comment]
Hi,

No, that is just a typo I made when I typed out this issue. OrientDB Studio would tell me if there was a syntax error. I double checked and I did not forget the colon in my tests.

**Comment by luigidellaquila** [comment]
Ok, let me double-check it then

I'll keep you updated

Thanks

Luigi

**Comment by tglman** [comment]
Hi,

the 2.2.x is out of support since a while, please update to a more recent version.

Regards
