### ISSUE TITLE
question about 'OIntentMassiveInsert'

### ISSUE THREAD

**Issue by efenzha** [orientechnologies/orientdb#9222]
### OS: Linux 2.6.32-696.16.1.el6.x86_64 x86_64

Hi,

I have some questions about **how and when** to use 'OIntentMassiveInsert', since there are very few related introduction in OrientDB docs.

1. Are there any **cost** to use 'OIntentMassiveInsert'? For example, consuming more memory? slower syncing between distributed nodes?

2. Can I always use 'OIntentMassiveInsert', even inserting few vertices? 

3. When using 'OIntentMassiveInsert', it applies on the whole database or only the connection created by this client? Or in other words, does it have impact on other clients?

**Comment by luigidellaquila** [comment]
Hi @efenzha 

In v 3.0.x MassiveInsert intent does not do much (it's a legacy component), I'd suggest you to just ignore it

Thanks

Luigi

**Comment by efenzha** [comment]
Hi @luigidellaquila,

Thanks for the reply.

Maybe it is better to mention this in OrientDB docs.
