### ISSUE TITLE
'UPSERT' in 'SQL - CREATE EDGE' does not work as expected

### ISSUE THREAD

**Issue by efenzha** [orientechnologies/orientdb#9223]
OrientDB Version: orientdb-3.0.21
Java Version:
OS: Linux 2.6.32-696.16.1.el6.x86_64 x86_64

## Steps to reproduce  
1. Creating database, and creating a UNIQUE index on in out of edge.

2. Adding vertices and creating edges using below command:
"CREATE EDGE $edgeName UPSERT FROM $from TO $to"

3. Creating same edges using the same command:
"CREATE EDGE $edgeName UPSERT FROM $from TO $to"

## Expected behavior  
In step 3, there should be no 'ORecordDuplicatedException', since OrientDB should skip the creation of edges that already exist between two vertices **automaticlly**.

## Actual behavior  
It throws 'ORecordDuplicatedException' everytime it executes "CREATE EDGE $edgeName UPSERT FROM $from TO $to".

Here is the information of the UNIQUE INDEX of in out of edge.
|InputEventId.out_in    |UNIQUE           | 371546|InputEventId   |       |

**Comment by jbreiding** [comment]
I am getting a similar error during the UPDATE command attempting to insert a vertex with a composite key for an index.

I actually have the index in my inheritance structure, the class I am writing/updating inherits from the class that has the index.

Only my vertex classes have this structure, my edge indexes are on the actual class I am inserting/updating.
