### ISSUE TITLE
Unable to update document values in embeddedset

### ISSUE THREAD

**Issue by asdfghjkai** [orientechnologies/orientdb#9234]
## Expected behavior  
When executing an SQL UPDATE command against a value within the embeddedset (selected by document attribute), the value should be altered in line with that presented in the command, eg = false should change the boolean value to false if already true. This was the case in OrientDB 2.2.12.

## Actual behavior  
Value does not change, and remains in it's original state. Many different approaches have been tried, including and excluding the element id [0], value appears to remain immutable. 

## Steps to reproduce  
CREATE CLASS TestClass EXTENDS V
CREATE PROPERTY TestClass.Name string;
CREATE PROPERTY TestClass.Value embeddedset;
CREATE CLASS EmbVals;
CREATE PROPERTY EmbVals.Alias string;
CREATE PROPERTY EmbVals.Omit Boolean;

INSERT INTO TestClass(Name,Value) VALUES ("InitialTest", [{
        "@type": "d",
        "@version": 0,
        "@class": "EmbVals",
        "Alias": "EmbeddedTest",
        "Omit": true
    }
])

SELECT Value[Alias='EmbeddedTest'].Omit[0] FROM TestClass WHERE Name = 'InitialTest' 

> Check is true as set above

UPDATE TestClass SET Value[Alias='EmbeddedTest'].Omit[0] = false WHERE Name = 'InitialTest' 

> Update, and set to false

SELECT Value[Alias='EmbeddedTest'].Omit[0] FROM TestClass WHERE Name = 'InitialTest' 

> Check value is false (is not)

**Comment by luigidellaquila** [comment]
Hi @asdfghjkai 

I just pushed a fix for this issue, it will be released with next v 3.0.31

Just please consider that the correct syntax is 

```
UPDATE TestClass SET Value[Alias='EmbeddedTest'][0].Omit = false WHERE Name = 'InitialTest'
```

Thanks

Luigi
