### ISSUE TITLE
Fails to use Linux API in common.jna.ONative

### ISSUE THREAD

**Issue by WhoNeedszZz** [orientechnologies/orientdb#9237]
## Expected behavior  
Native Linux API should be used 

## Actual behavior  
```
Can not open file using Linux API, Java FileChannel will be used instead
com.sun.jna.LastErrorException: [22] Invalid argument
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:419)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at com.sun.proxy.$Proxy2.open(Unknown Source)
	at com.orientechnologies.common.jna.ONative.open(ONative.java:234)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:29)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1838)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

## Steps to reproduce  
Run `server.sh` as usual

**Comment by laa** [comment]
Hi, we run ./server.sh every day and the never happens, I suppose you mixed different versions of libraries.

**Comment by WhoNeedszZz** [comment]
> Hi, we run ./server.sh every day and the never happens, I suppose you mixed different versions of libraries.

Are you seriously going to deny this error? I downloaded the official 3.0.30 archive and did nothing to it. I'm also using the official Oracle JDK. The stacktrace is quite clear - you're using an invalid argument. It's extremely frustrating that you would rather accuse the user of doing something wrong instead of owning up to your own issue.

**Comment by laa** [comment]
@WhoNeedszZz the first thing that people should learn at least in 2020 that is polite conversion. We will look at that issue.

**Comment by WhoNeedszZz** [comment]
> @WhoNeedszZz the first thing that people should learn at least in 2020 that is polite conversion. We will look at that issue.

I completely agree about polite conversation. And accusing someone who's knowledge and skill set you know nothing about as having doing something wrong right off of the bat is impolite and going to provoke the type of response you received. I'd be happy to provide further information if you need it, but being defensive immediately is not the way to go about it. I'd even be willing to fix it myself and create a PR if we can determine the exact cause.

What I'm testing currently is the running user. The database this was happening on was running as a non-privileged user. So far I'm not seeing it happening when running as `root`, but given that you support running as other users I'd rather not run as root. Apparently your tests don't cover running as a non-privileged user so you're getting a false confidence in those tests. :wink:

**Comment by laa** [comment]
I am not a root user and I am running the server on Linux machine without problems.
https://i.imgur.com/jBstFw3.png , https://i.imgur.com/esrLVSO.png , https://i.imgur.com/33qVOiw.png .  Also, all our tests are running on Linux distribution and all of them do not use root privileges during their run. Once we will have time we will look deeper on your issue. Almost all our customers run the server on Linux without root privileges and you are the first who raised this issue.

**Comment by WhoNeedszZz** [comment]
Which directory is your test installation located?

**Comment by WhoNeedszZz** [comment]
I have found the issue. I had the directory within my home directory and my home directory is actually private - set to 700. Due to the directory not having access for other the JNA functionality fails. I don't understand why this is an issue given the server is being ran by my user. I've never seen this behavior with any other application and I've always set my home directory private.

**Comment by WhoNeedszZz** [comment]
Upon further testing it's not the directory permissions. Setting home directory to 755 resulted in the same behavior. Moving to /opt and keeping the user ownership works, even setting /opt/orientdb-3.0.30 to 700 works. It only gives the error when located at /home/user/orientdb-3.0.30.

**Comment by WhoNeedszZz** [comment]
Finally figured out the culprit. I created a new user just to rule out some user-specific oddity. It worked fine with the new user. I figured then the likely culprit was ECryptfs and sure enough it was. As soon as I encrypted the new user's home directory the same error came up. I'm not sure why this is the case since the files are decrypted when accessing it, but this is the issue. Again, I've never seen this behavior in any other application while using ECryptfs.

**Comment by WhoNeedszZz** [comment]
So I see the thumbs up, but I'm not understanding why you would just close this issue. While I found the culprit, it's still an issue. I can't say whether it is something you have control over in your JNA code or if it's something intrinsic of how JNA is implemented, but at the very least I would think you would document this behavior in your installation documentation as a warning to people who use eCryptFS to encrypt their home directory and wanted to install in there. That it would be recommended to install it outside of their home directory if they don't want to fall back to non-native file access. Don't you think?

**Comment by laa** [comment]
Yes, a good suggestion we would do that.
