### ISSUE TITLE
LUCENE FULLTEXT Index return 0 items from EMBEDDEBMAP property when search.

### ISSUE THREAD

**Issue by njasm** [orientechnologies/orientdb#9245]
### OrientDB Version: 
3.0.30 community
### Java Version: 
root@3bfce6364476:/orientdb# java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode) 
### OS: 
Docker official image build

## Expected behavior  
results returned

## Actual behavior  
Zero results are returned

## Steps to reproduce  

Create class "test"
- add property "id" type INTEGER
- add property "action" type STRING
- add property "data" type EMBEDDEDMAP

- Create FULLTEXT with LUCENE engine and no METADATA via studio for all 3 fields.

Insert test record:
```
INSERT INTO test(id, action, data) VALUES (2, "Comments", {
    "model": "Comments",
    "primarykeys": {
        "CommentID": 2
    },
    "attributes": {
        "CommentID": 2,
        "CommentTypeID": 1,
        "Description": "Hello world how are you today?",
        "UserID": 122,
        "CreationDate": "2020-05-10 14:54:47",
        "IsActive": 1,
        "ActivityDate": "2020-05-10 14:54:47",
        "ActivityUserID": 122
    }
})
```

Query returning zero results:
```
SELECT DISTINCT action,  
	data.attributes.Description AS description,
	data
FROM test
WHERE SEARCH_CLASS('World', {
    "allowLeadingWildcard": true ,
    "lowercaseExpandedTerms": true
}) = true
ORDER BY action ASC
LIMIT 1000
```

tried also with:
 ```
 SEARCH_CLASS('data.attributes.Description:World'...
```
- no error logs in oDB.

So is possible to index in lucene engine all properties of a document included nested EMBEDDEMAPs types and query those with SEARCH_CLASS/SEARCH_FIELDS or other functions so to use the LUCENE index?

In Solr 8.5 real world, schemaless example returning values:
```
q=(type:event) && (action:'EntityAddresses * Update') && +(context:model) && (data.attributes.Address:BARRO)
```

**Comment by dritter-sap** [comment]
Although you might have already found your mistake, https://github.com/orientechnologies/orientdb/pull/9277 adds some more explanation, testing and an exception to EMBEDDED for you or others interested in the solution.
