### ISSUE TITLE
[Client lib bug, cluster die, important] Result sets not closing in 3.0.28 , 3.0.31

### ISSUE THREAD

**Issue by quanghaisoft** [orientechnologies/orientdb#9249]
OrientDB Version: 3.0.28
Java Version: 1.8.0_131
OS: Ubuntu
Expected behavior
Error  appears on version 3.0.28, 3.0.31 when calling the wrong function parameter
Function name:  gameapp_GetGalleryByProductIDTest(p1,p2,p3) 
but when ran: select gameapp_GetGalleryByProductIDTest(p1,p2) as rs
function body sample: 
 `select
	expand(x)
from
(
select
  	 abc
	
from
	product
let
	$x = out('e_a')[isactived = 1 and isdeleted = 0 and siteid = :p2 
                                               and (imagetype = :p3 or :p3 < 1)]
where
	productid = :p1
)     `
Actual behavior
y 14 10:07:00 ograph01-beta server.sh[6217]: 2020-05-14 10:06:59:656 WARNI {db=web} This database instance has 90 open command/query result sets, please make sure you close them with OResultSet.close() [ODatabaseDocumentEmbedded]
May 14 10:07:02 ograph01-beta server.sh[6217]: 2020-05-14 10:07:00:845 WARNI {db=web} This database instance has 100 open command/query result sets, please make sure you close them with OResultSet.close() [ODatabaseDocumentEmbedded]
May 14 10:07:03 ograph01-beta server.sh[6217]: 2020-05-14 10:07:02:018 WARNI {db=web} This database instance has 110 open command/query result sets, please make sure you close them with OResultSet.close() [ODatabaseDocumentEmbedded]
May 14 10:07:04 ograph01-beta server.sh[6217]: 2020-05-14 10:07:03:193 WARNI {db=web} This database instance has 120 open command/query result sets, please make sure you close them with OResultSet.close() [ODatabaseDocumentEmbedded]
May 14 10:07:05 ograph01-beta server.sh[6217]: 2020-05-14 10:07:04:395 WARNI {db=web} This database instance has 130 open command/query result sets, please make sure you close them with OResultSet.close() [ODatabaseDocumentEmbedded]
May 14 10:07:06 ograph01-beta server.sh[6217]: 2020-05-14 10:07:05:605 WARNI {db=web} This database instance has 140 open command/query result sets, please make sure you close them with OResultSet.close() [ODatabaseDocumentEmbedded]
May 14 10:07:08 ograph01-beta server.sh[6217]: 2020-05-14 10:07:06:785 WARNI {db=web} This database instance has 150 open command/query result sets, please make sure you close them with OResultSet.close() [ODatabaseDocumentEmbedded]
May 14 10:07:09 ograph01-beta server.sh[6217]: 2020-05-14 10:07:08:087 WARNI {db=web} This database instance has 160 open command/query result sets, please make sure you close them with OResultSet.close() [ODatabaseDocumentEmbedded]

**Comment by quanghaisoft** [comment]
<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-graphdb</artifactId>
			<version>3.0.28</version>
		</dependency>
		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-gremlin</artifactId>
			<version>3.0.28</version>
		</dependency>

**Comment by quanghaisoft** [comment]
`
OrientGraphFactory factory=.......
public  void testA( )   {

		OResultSet rs = null; 
		OrientGraph orG = null;
		try {
			orG = factory.getNoTx();
		
			Map<String, Object> paramsmap = new HashMap<String, Object>();
			rs = orG.querySql("select gameapp_GetGalleryByProductIDTest(219915,1) as rs", paramsmap).getRawResultSet();
			 
		} catch (Throwable e) {
		  Exeption appear here and  rs =null , so nothing to close in finally
			 
		} finally {
			if(rs!=null)rs.close();
			if(orG!=null)orG.close();

		}
		  
	}`

**Comment by matanshukry** [comment]
@quanghaisoft I'm on 3.0.31 and I don't see any functions named `querySql` nor `getRawResultSet`. 

Can you tell what's the class they're actually defined on?

**Comment by quanghaisoft** [comment]
I using multi process and multithread for upsert data so i using 
class OrientGraphFactory in package:
package org.apache.tinkerpop.gremlin.orientdb

same issue if i using:
 ORODatabasePool dbPool=new ORODatabasePool(  "IP", "db", "admin",
	 		"pass", 2424); 
 var rs=dbPool.Query("select gameapp_GetGalleryByProductIDTest(p1,p2) as rs");

**Comment by quanghaisoft** [comment]
thi has find a way to by pass this error by using:
orG = factory.getNoTx(); 
ORS = orG.execute("sql", query, params);

instead of querySql
