### ISSUE TITLE
Direct memory violation exception on RIDs

### ISSUE THREAD

**Issue by HackerTheMonkey** [orientechnologies/orientdb#9264]
## Expected behaviour
Expecting data to be returned when I perform the following query:

```
select from #11:123
```

## Actual behaviour 
The following exceptions are thrown:

```
2020-05-25 15:26:51:315 SEVER Internal server error:
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Last position of provided data interval [1919308488] is more than size of allocated area [65552] [ONetworkProtocolHttpDb]
```

What does the above exactly mean to you?

Which led me to think that I have some sort of corrupted data, attempting to hide that particular rid with the `hide` command does not seem to affect this at all and I still get the same exception over and over again. Also running a `repair database` does not seem to have much effect either.

Following are the JVM settings that the mentioned orient db is running with:

- Xms: 1GB
- Xmx: 1GB
- MaxDirectMemorySize: 70G

Can someone please shed some lights on how do we go from here, knowing that upgrading to a more recent version is not an option at the moment due to the size of the DB and the fact that we've failed on more than one occasion to do so.

Is there a way that we can load up the cpm file and somehow have that mapping fixed or cleared ?

Cheers

**Comment by tglman** [comment]
Hi,

the 2.2.x version is out of support, no new hotfix releases have been produced for this version since a while, please update to a newer release.

Regards
