### ISSUE TITLE
[Contribute Help] how to change syntax (add operator)

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9267]
I want to introduce a new operator - the null coalescing operator (??).

I tried to simply implement a class like `OQueryOperatorMultiply` and add it in `ODefaultQueryOperatorFactory`, but it seems I also need to change the parser.

I tried to add the new operator in the .jjt file (in the core/src/main/grammer) and then use the mvn goal to generate it `mvn javacc:jjtree`, but the changes to the existing files seems a lot bigger than the change I introduced.

Am I missing something? is there a different way something like this should be done?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

When you change the grammar, a lot of files are impacted. JavaCC generates new classes (that have to be filled with the new logic) and changes the parser classes (that should never be touched manually). See `OMathExpression` for an example, but please consider that it's not trivial.

`OQueryOperatorMultiply` is for the legacy SQL executor, so you can ignore it

Thanks

Luigi

**Comment by matanshukry** [comment]
@luigidellaquila
 
Yeah I actually did look at `OMathExpression` and tried to create the new operator based on it. I think there are still more changes that what I made to the grammer file, but I'll send the PR and let you decide, you'll probably know more by looking at the actual changes as well.

And thanks for the `OQueryOperator` tip, I'll ignore that.
