### ISSUE TITLE
[Question] how to create an index in Java with multiple properties?

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9275]
It seems since 3.0 using the `OIndexManager` is deprecated and indices should be created on properties, such as:

`schema.getClass("Employee").getProperty("address").createIndex(OClass.INDEX_TYPE.NOTUNIQUE, new ODocument().field("ignoreNullValues",true));`

however - how do you create an index on multiple properties?

I noticed there's a `createIndedx` method on `OClass`:
1. Is that how it should be done? If not, how then?
2. If so, what name should one give it? does it matter or any name can be chosen? is there any recommendation?

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

Yes, you should use the OClass method. The index name does not matter much, you can use whatever you want, but by convention we use `ClassName.prop1_prop2_propN`

Thanks

Luigi

**Comment by matanshukry** [comment]
@luigidellaquila great, thanks!

It should probably be added the documentation btw. I'm closing this issue, but reopen it if you want it as a task reminder to add it to the doc.
