### ISSUE TITLE
v3.1.0 and v3.0.30: Unable to use zfs for databases

### ISSUE THREAD

**Issue by mmariuzzo** [orientechnologies/orientdb#9278]
## Expected behavior  
place orientdb databases on a zfs filesystem to take advantages of native compression

## Actual behavior  
OrientDB crashes on startup 

## Steps to reproduce  
I'm using OrientDB to store datas with a good compression trend. I've tested the internal compression and I'm gaining around 45% of space. Because internal compression is on record level I want to move databases into a zfs filesystem which will provide more space gain.

To reproduce
* install zfs-on-linux
* create a zfs filesystem and mount it as "/mnt/datas"
* move the "databases" subdir inside "/mnt/datas/orientdb" and symlink it
* start orientdb using "server.sh" command
* exception occurs

```
Exception `269A1467` in storage `plocal:/mnt/datas/orientdb/databases/OSystem`: 3.1.0 - Veloce (build da09ce5af52267b70035d8600551a5032065807a, branch develop)
com.orientechnologies.common.jnr.LastErrorException: Error during execution of native call, error code 95
        at com.orientechnologies.common.jnr.ONative.checkLastError(ONative.java:270)
        at com.orientechnologies.common.jnr.ONative.fallocate(ONative.java:245)
        at com.orientechnologies.orient.core.storage.fs.AsyncFile.allocateSpace(AsyncFile.java:273)

```
[orient-server.log](https://github.com/orientechnologies/orientdb/files/4724658/orient-server.log)

Same error with "-Dstorage.wal.allowDirectIO=false"

This is the content of OSystem folder
[osystem-files.txt](https://github.com/orientechnologies/orientdb/files/4724694/osystem-files.txt)

**Comment by mmariuzzo** [comment]
Great. `storage.diskCache.useAsyncIO=false` is the solution :+1:

**Comment by laa** [comment]
Well, that is not a solution. This flag is introduced only to smooth database development. I will fix it in next version.

**Comment by laa** [comment]
Sorry guys for the silence we were pretty busy on working on 3.1 release.

**Comment by laa** [comment]
Fixed. Parameter "storage.disk.useNativeOsAPI" please set it to false, to avoid problems with ZFS.

**Comment by laa** [comment]
We are going to release hotfix next week.
