### ISSUE TITLE
Can't find nearly inserted record by unique field within transaction

### ISSUE THREAD

**Issue by arch7tect** [orientechnologies/orientdb#9281]
## Expected behavior  
in transaction: 
--insert record in the class with unique index
--select this record by indexed field
expected: nearly inserted record is found

## Actual behavior  
no records found

## Steps to reproduce  
```
drop class TestClass if exists unsafe;
create class TestClass extends V;
create property TestClass.name STRING;
create index TestClass.name on TestClass(name) unique;
begin;
let b = CREATE VERTEX TestClass SET name = 'b';
let last = (select * from TestClass where name='b');
commit;
return $last.size();
```
This code returns 0.
If we comment out 'create index' statement, we got 1.

**Comment by laa** [comment]
That is a known issue I am already working on it.

**Comment by laa** [comment]
Fixed.
