### ISSUE TITLE
Aggregation functions return incorrect values when using LIMIT keyword

### ISSUE THREAD

**Issue by evy126** [orientechnologies/orientdb#9288]
## Expected behavior  
`LIMIT` keyword may limit number of returned rows but not modify aggregation calculations 

## Actual behavior  
When an aggregation (`count, sum`, ..) is used on a property, it's applied only on `LIMIT` rows.
Works correctly when using `count(*)`.
Works correctly in OrientDB 2.2.24.

## Steps to reproduce  
Using demodb : 

`select count(*) from countries;`
`count(*) : 249` .. ok

`select count(*) from countries limit 10;`
`count(*) : 249` .. ok

`select count(Id) from countries;`
`count(*) : 249` .. ok

`select count(Id) from countries limit 10;`
`count(*) : 10` .. NOT OK

`select sum(Amount) from orders;`
`sum(Amount) : 438635` .. ok

`select sum(Amount) from orders limit 10;`
`sum(Amount) : 5702` .. NOT OK

**Comment by luigidellaquila** [comment]
Hi @evy126 

Thank you for reporting, I'm fixing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @evy126 

I just pushed a fix, it will be released with v 3.0.32

Thanks

Luigi

**Comment by evy126** [comment]
Wow .. that was really a quick fix.
Thank you Luigi
