### ISSUE TITLE
Migrating from 3.0.30 to 3.1.0 - Impossible to remove last cluster of ORole

### ISSUE THREAD

**Issue by everette00** [orientechnologies/orientdb#9290]
## Expected behavior  
Migrating from version X -> Y should accept a valid database layout. I have upgraded from prior versions for OrientDB before without issue.  

## Actual behavior  
On evaluating version 3.1.0, an export from 3.0.30 is apparently not compatible with 3.1.0.
I receive this error:  
`com.orientechnologies.orient.core.exception.ODatabaseException:  Impossible to remove the last cluster of class 'ORole' drop the class instead`

## Steps to reproduce  
1. Export from 3.0.30 with DB users
2. Create a new database inside of 3.1.0 named exactly the same as it is in 3.0.30
3. Connect to the 3.1.0's database and import 3.0.30's export

**Comment by luigidellaquila** [comment]
Hi @everette00 

We are already investigating this problem (it's high priority).
You can monitor the advancement here https://github.com/orientechnologies/orientdb/issues/9287

Closing as duplicate

Thanks

Luigi
