### ISSUE TITLE
Skip / Count Java Datatype Inconsistency

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#9298]
### OS: MacOS 

I am not sure if this is a bug, a question, or an enhancement request!  I have noticed that there is an inconsistency in how OrientDB hands `count` vs how it deals with `SKIP` / `LIMIT`.

If we look at the OSkip class we can see that it essentially wraps an `int`.  Meaning that the max value you can `SKIP` is the max value of an `int`.

https://github.com/orientechnologies/orientdb/blob/14003ca55ef095c754bf37d49ea146adf02397ee/core/src/main/java/com/orientechnologies/orient/core/sql/parser/OSkip.java#L13

However, if we have a OrientDB Class that we are going to query using the `count(*)` function like so:  

```SQL
SELECT count(*) as count FROM MyClass
```

We will see that the count is returned as a `long`. We can see this by looking at the OSQLFunctionCount class.

https://github.com/orientechnologies/orientdb/blob/47a44a54f858982273b74636cb02bbbf3f67c0b3/core/src/main/java/com/orientechnologies/orient/core/sql/functions/misc/OSQLFunctionCount.java#L37

This leads to an interesting result.  If I am paging through result, and I count how many total results. I will get a `long` value. But if I want to then page in to those results using `SKIP` I can only use an `int`. This seems to imply that I can't actually `SKIP` "all the way" into the results since the max value of an `int` is less than the max value of a `long`. In other words if I do a `count` I may get a count that is larger than `Integer.MAX_VALUE` since the count is a long.  But there is no way for me to `SKIP` past `Integer.MAX_VALUE`, so I can not effectively get pages of data beyond `Integer.MAX_VALUE`

It seems like `SKIP` and `count` are logically related and that there should be consistency in the numeric primitive that represents them.

Thoughts?

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

The constructor of Skip class takes an ID that is only needed by the SQL parser, the actual skip value is in the 

```
protected OInteger num;
```

that can also contain a Long value.
The following will work just fine:

```
select from V limit 1L
```

Thanks

Luigi

**Comment by mmacfadden** [comment]
@luigidellaquila Perfect that clarifies things!
