### ISSUE TITLE
Restore Database Hangs on "Uncompressing file dirty.fl..."

### ISSUE THREAD

**Issue by dullahan8** [orientechnologies/orientdb#9300]
## Expected behavior  
Restore completes in roughly 15 seconds.

## Actual behavior  
Restore hangs on this line until I kill the process.
```
- Uncompressing file dirty.fl...
```
The whole restore takes about 15 seconds when restoring into Orientdb-3.0.25. As far as I can tell from successful restores, this is the final file to uncompress before the restore completes.

## Steps to reproduce  
1. Create a backup from our production environment
```
/opt/orientdb-3.0.22/bin/console.sh "connect plocal:/opt/orientdb-3.0.22/databases/production $user $pw ; backup database /path/to/backupdir/production-$(date +%Y-%m-%d-%T).zip" 
```
2. Drop the old database and create a new database in our dev environment
```
/opt/orientdb-community-3.1.1-SNAPSHOT/bin/console.sh "drop database plocal:/opt/orientdb-community-3.1.1-SNAPSHOT/databases/prod-sync-dev $user $pw"
/opt/orientdb-community-3.1.1-SNAPSHOT/bin/console.sh "create database plocal:/opt/orientdb-community-3.1.1-SNAPSHOT/databases/prod-sync-dev $user $pw" 
```
3. Connect to the new dev database and restore from the backup file
```
/opt/orientdb-community-3.1.1-SNAPSHOT/bin/console.sh "connect plocal:/opt/orientdb-community-3.1.1-SNAPSHOT/databases/prod-sync-dev $user $pw ; restore database /path/to/latest_backup"
```

**Comment by laa** [comment]
Hi @dullahan8 could you provide full thread dump?

**Comment by dullahan8** [comment]
Here it is.[](url)
[orientdb-3.1-thread-dump.txt](https://github.com/orientechnologies/orientdb/files/4794369/orientdb-3.1-thread-dump.txt)

**Comment by laa** [comment]
@luigidellaquila that is a deadlock on record security mechanics. Assing it to you.

**Comment by dullahan8** [comment]
Any updates on this one?

**Comment by luigidellaquila** [comment]
Hi all

This issue should be fixed in v 3.1.2

Could you please confirm?

Thanks
Luigi

**Comment by dullahan8** [comment]
Thank you. I will take a look.

**Comment by dullahan8** [comment]
Confirming that the issue is fixed.

Thank you for your help.
