### ISSUE TITLE
Question about Storage

### ISSUE THREAD

**Issue by everette00** [orientechnologies/orientdb#9301]
### OS: CentOS 7  

Reading on OrientDB limitations, there is a blurb about concurrency. It is stated that OrientDB retrieves an exclusive lock on storage and serializes transactions to achieve concrrency. Do you mean that OrientDB blocks the internal system for storing data? Or do you mean the whole disk drive for the time the exclusive lock is held?

Thanks,
Everette

**Comment by laa** [comment]
Hi, that is not true for a long time. Currently, we block on the level of the components. Since 4.0 we plan to introduce SI level of isolation so will block only on record/key level. But the last one only in plans not confirmed completely yet.

**Comment by everette00** [comment]
Thanks @laa!
