### ISSUE TITLE
OrientDB 3.1.0 and java library orientdb-graphdb 3.1.0 EDGE creation issue

### ISSUE THREAD

**Issue by CanonTino** [orientechnologies/orientdb#9313]
## Behavior  

1. When I run my test case in order to create a new vertex and create an edge which has **APP3** vertex as target (which **does not** have any other **in** nor **out** edges) transaction is committed successfully (WHICH IS OKAY)
2. When I run my test case in order to create a new vertex and create an edge which has **APP1** or **APP2** vertex as target  (which **does have** any other **in** or **out** edges) transaction fails indicating this exception: `java.lang.AssertionError: Cx ollection timeline required for link types serialization`

## Notes:
I am using this deopendency:
`		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-graphdb</artifactId>
			<version>3.1.0</version>
		</dependency>
`

But if I use the previous version:
`		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-graphdb</artifactId>
			<version>3.0.31</version>
		</dependency>
`
 then the issue does not appear any more
We are currently using OrientDB 3.1.0 server versión so we need to upgrade the API too

### I have this test case (using spock framework)

`package com.globaldoc.document.registryandquery.service.orientdb310

import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory
import spock.lang.Ignore
import spock.lang.Shared
import spock.lang.Specification

class OrientDB310Spec extends Specification {

    @Shared
    OrientGraphFactory factory

    def setupSpec() {
        factory = new OrientGraphFactory("remote:localhost:2424/MAPP", "***", "****")
                .setupPool(5, 10)
    }

    def "create edge from a new vertex to an existing one"() {

        given: ""
        def g = factory.getTx()
        def target = g.getVertices("LID","APP1").first()
        println target.getProperty("ID")
        when: ""
        def currentTime = new Date().getTime()
        def v1 = g.addVertex("class:KEYDOK")
        v1.setProperty("ID", UUID.randomUUID().toString())
        v1.setProperty("LID", UUID.randomUUID().toString())
        v1.setProperty("current", true)
        v1.setProperty("insertedOn", currentTime)
        v1.setProperty("version", 1)

        def e1 = v1.addEdge("HAS_AS_FAVORITE", target)
        e1.setProperty("insertedOn", currentTime)
        e1.setProperty("isActive", true)
        e1.setProperty("isCurrent", true)
        e1.setProperty("versioning", 1)
        e1.setProperty("since", currentTime)

        then: "changes must be successfully committed"
        g.commit()
        g.shutdown()
    }

    def cleanupSpec() {
        factory.close()
    }
}
`
### I have this graph
![image](https://user-images.githubusercontent.com/24844797/85592260-a0639e00-b60b-11ea-8dad-a64bcb2beb8e.png)

**Comment by dritter-sap** [comment]
@CanonTino `orientdb-graphdb` is TinkerPop version 2.6 and is actually deprecated. It will be removed eventually. I suggest to use `orientdb-gremlin` instead in the future (cf. https://github.com/orientechnologies/orientdb-gremlin).

Regarding your issue: I could not reproduce it in 3.1.x (cf. https://github.com/orientechnologies/orientdb/commit/31814476a7449cba20af06817563764263e225d7), probably because some information is missing. Could you kindly add information on a minimal graph schema and data for testing / a complete test case as well as your system setup (single / distributed), plus the stacktrace? Thanks

**Comment by CanonTino** [comment]
I’ ll provide more information but right now I can share this:
My setup is single.
About clients/servers: this the weird part
I’m always using 3.1.0 server version
when I try to use the same version at clien (3.1.0) the test fails,
the test will only pass when I use 3.0.x client version.

**Comment by CanonTino** [comment]
Make sure to use 3.1.0 server version and use a **single setup**

Steps to reproduce:
1. Create  BD MAPP
2. Create APP vertex class with attributes:
    1. ID (string)
    2. LID(string)
3. Create KEYDOK vertex class with attributes:
    1. ID (string)
    2. LID (string)
    3. current (boolean)
    4. insertedOn (datetime)
    5. version (integer)
4. CREATE UNDER  edge class with attributes:
    1. insertedOn (datetime)
    2. isActive (boolean)
    3. isCurrent (boolean)
    4. versioning (integer)
    5. since (datetime)
5. CREATE HAS_AS_FAVORITE  edge class with attributes:
    1. insertedOn (datetime)
    2. isActive (boolean)
    3. isCurrent (boolean)
    4. versioning (integer)
    5. since (datetime)
6. On OrientDB Studio go to O GRAPH tab
7. Add new vertex of class APP
    1. ID = APP1-ID
    2. LID = APP1
8. Add new vertex of class APP
    1. ID = APP2-ID
    2. LID = APP2
9. Add new vertex of class APP
    1. ID = APP3-ID
    2. LID = APP3
10. Add new edge of class UNDER from APP1 tp APP2 with attributes:
    1. isCurrent = true
    2. isActive = true
    3. versioning = 1
    4. insertedOn = currentDate
    5. since = currentDate
11. Clone repository with contains the project: [https://github.com/CanonTino/dummy-demo-test.git](https://github.com/CanonTino/dummy-demo-test.git)
12. Execute test case orient.test.OrientDB310Test.createEdgeFromANewVertexTpAnExistingOne() which should fail. If you change String targetAppId = "APP1"; for String targetAppId = "APP3"; test will pass

**Example GRAPH**
![image](https://user-images.githubusercontent.com/24844797/86292093-b3e7a980-bbb5-11ea-8634-b58c31060ab3.png)

**Comment by dritter-sap** [comment]
Thanks, I extended your test to create everything automatically and I could reproduce it. It could be that the issue relates to this: https://github.com/orientechnologies/orientdb/issues/9179, which might already been fixed (but not yet merged). Let me check.

**Comment by vikashk77** [comment]
Hey buddy,

Thanks for your quick response. Let me know if it’s merged.

Also I tried 3.1.0 snapshot but couldn’t find the link for “Importers” in Server Management Page.

As you are aware, Inside “Importers” we have Teleporter, ETL and Neo4j Importer etc.

Kind regards,
Vikash Kumar


Advanced Leave Notification:

**Comment by CanonTino** [comment]
> Thanks, I extended your test to create everything automatically and I could reproduce it. It could be that the issue relates to this: #9179, which might already been fixed (but not yet merged). Let me check.

Hi @dritter-sap any news on this?

**Comment by CanonTino** [comment]
Thank you so much @dritter-sap

**Comment by melbarra88** [comment]
Hi, any news on this ? 
I have a similar issue. When I try to save a new edge, an exception is thrown when it tries to update the vertices. Although I tried to upgrade to 3.1.1 for both java dependencies and the db server, the error keeps being thrown. Note that, this error occurs only when I use a remote database, but when I use an embedded in memory database, it works. 

The stacktrace :
`
Cx ollection timeline required for link types serialization
java.lang.AssertionError: Cx ollection timeline required for link types serialization
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaLinkBag(ODocumentSerializerDelta.java:659)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaValue(ODocumentSerializerDelta.java:638)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaEntry(ODocumentSerializerDelta.java:610)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDelta(ODocumentSerializerDelta.java:592)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDelta(ODocumentSerializerDelta.java:95)
	at com.orientechnologies.orient.client.remote.message.OCommit38Request.<init>(OCommit38Request.java:63)
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1302)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2466)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:602)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:87)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.saveAll(ODatabaseDocumentRemote.java:686)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:208)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:1854)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1802)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1685)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:135)
	at com.amigos.cybermanager.riskmanager.infrastructure.repository.threat.graph.OrientAttackSpaceGraphEdgeRepository.save(OrientAttackSpaceGraphEdgeRepository.java:81)
`

**Comment by dritter-sap** [comment]
@melbarra88 this looks very similar and I also noticed that it worked in the embedded case. We plan to solve this in the next patch, i.e. 3.1.2, which will hopefully come soon.

**Comment by dritter-sap** [comment]
@CanonTino and @melbarra88 : Fixes in `3.1.x` and `develop` were merged. Kindly retest, in `SNAPSHOT` or when `3.1.2` is released. Thanks

**Comment by CanonTino** [comment]
@dritter-sap I've already tested 3.1.2 release and the problem is solved. Test is passing now and edges are being correctly created.
Thank you so much.
