### ISSUE TITLE
Exception in POJO save that class is Final

### ISSUE THREAD

**Issue by Paritosh-Anand** [orientechnologies/orientdb#9330]
## Expected behavior  
New object must be saved without error

## Actual behavior  
Jul 08, 2020 4:51:16 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on creating object of class AutoScalingGroup
java.lang.RuntimeException: software.amazon.awssdk.services.autoscaling.model.AutoScalingGroup is final

## Steps to reproduce  
Use case is to store AWS resource information in orientDB that will serve as a DB for other automation requirements.
 
1. Query AWS ASG resource using AWS Java SDK 2
2. Try to save ASG information in orient DB

```
String[] autoScalingGroupName = { "asg1", "asg2" };

DescribeAutoScalingGroupsResponse response = new ASGExample(region).asgResponse(autoScalingGroupName);
	
for (AutoScalingGroup asgDetails : response.autoScalingGroups()) {
	logger.info(asgDetails.autoScalingGroupName() + "======" + asgDetails.maxSize());
	dbObj.getEntityManager().registerEntityClass(AutoScalingGroup.class);
	dbObj.save(asgDetails);
}
```

pom.xml 
```
<!-- Orient DB -->
<dependency>
	<groupId>com.orientechnologies</groupId>
	<artifactId>orientdb-client</artifactId>
	<version>3.1.1</version>
</dependency>
<dependency>
	<groupId>com.orientechnologies</groupId>
	<artifactId>orientdb-object</artifactId>
	<version>3.1.1</version>
</dependency>
```

**Comment by lvca** [comment]
Do you have the full exception stack trace?

**Comment by Paritosh-Anand** [comment]
Not handy as of now. Though I believe it can be reproduced using the steps mentioned above.
