### ISSUE TITLE
Distributed nodes competing to be a master

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9331]
## Expected behavior  
After a database synchronization the nodes are stable and don't request more database syncs.

## Actual behavior  
Nodes are in an infinite loop.
The nodes that participated in the database sync are showing this log in a loop

2020-07-09 08:24:03:194 INFO  [oriendb-cluster-1-demo-cloud-se-aws-us-east-1] Publishing ONLINE status for database oriendb-cluster-1-demo-cloud-se-aws-us-east-1

## Steps to reproduce  
Setup 3 distributed nodes in master-master configuration
stop one node and delete it's copy of the database and the wal files for the database
start the node and wait until synchronization finishes
stopping and starting all nodes don't fix the problem, they continue competing for master

After all this, I tried to create an index in node 1 and I got this null pointer exception
[exception_node_1.txt](https://github.com/orientechnologies/orientdb/files/4895546/exception_node_1.txt)

there are some thread dumps at the end of the logs meanwhile the nodes 1 and 2 are competing

[node1_orient-server-boot.log.gz](https://github.com/orientechnologies/orientdb/files/4895488/node1_orient-server-boot.log.gz)
[node2_orient-server-boot.log.gz](https://github.com/orientechnologies/orientdb/files/4895489/node2_orient-server-boot.log.gz)
[node3_orient-server-boot.log.gz](https://github.com/orientechnologies/orientdb/files/4895490/node3_orient-server-boot.log.gz)

**Comment by lvca** [comment]
Please upgrade to the latest 3.1.x where such issues have been resolved.
