### ISSUE TITLE
New index getting created with Engine as CELL_BTREE instead of SBTREE

### ISSUE THREAD

**Issue by sanketprabhu34** [orientechnologies/orientdb#9342]
## Expected behavior    
After creating an index, the type defined as UNIQUE so engine allocated must be SBTREE which is the default engine for OrientDB.

## Actual behavior  
An index is getting created having the engine as CELL_BTREE instead of SBTREE  

## Steps to reproduce  
CREATE INDEX `V.uuid` ON `V`(`uuid`) UNIQUE;

**Comment by sanketprabhu34** [comment]
first

**Comment by laa** [comment]
That is correct, in 3.0.x we introduced a new engine.

**Comment by sanketprabhu34** [comment]
is there any difference between both?
