### ISSUE TITLE
Command runs successfully, but returns an error message

### ISSUE THREAD

**Issue by Robson96** [orientechnologies/orientdb#9345]
### Java Version: openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 14 Linux amd64-64-Bit Compressed References 20200416_44 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 5757187cae based on jdk-14.0.1+7)

## Expected behavior  
Return success message when changing property restrictions 

## Actual behavior  
returns an error message: 'Command failed.'  

## Steps to reproduce  

1. create class Student
2. create property Student.name string
3. alter property  Student.name max 60 (or any other command to change ownership restrictions)

![bug](https://user-images.githubusercontent.com/53229150/88217717-57682f00-cc35-11ea-8d23-0057de72d97a.png)

**Comment by lvca** [comment]
Resolved on the latest 3.1.x. Please upgrade.
