### ISSUE TITLE
GRANT not working on last release (3.1.1)

### ISSUE THREAD

**Issue by jamy23** [orientechnologies/orientdb#9348]
## Expected behavior  
Granted permission to `readYourRecords` on V to reader

## Actual behavior 

`
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
grant "readYourRecords" ON V to "reader"
    ^
Encountered " <GRANT> "grant "" at line 1, column 1.
Was expecting one of:
    \<LET\> ...
    \<EXPLAIN\> ...
    
        DB name="test"
        Error Code="1"
        DB name="test"

`

## Steps to reproduce  
`
orientdb> CREATE SECURITY POLICY readYourRecords SET READ = (owner = $currentUser)
orientdb> GRANT readYourRecords ON database.class.V TO reader
`

**Comment by Solido** [comment]
Working Update 
`GRANT POLICY readYourRecords ON database.class.MyClass TO developer`

Just need to update the documentation
