### ISSUE TITLE
Running Simple Query through Java API But not getting Result

### ISSUE THREAD

**Issue by somnath157** [orientechnologies/orientdb#9379]
OrientDB Version: 3.0.30  
Java Version: 1.8
OS: windows 10

```
          
        try(ODatabaseSession db = pool.acquire()){
            String query = "select * from Song where out_SungBy.in.id=?";
            OResultSet rs = db.query(query,artistId);

            while (rs.hasNext()) {
                OResult item = rs.next();
                Artist ar = new Artist();
                System.out.println("count : "+ item.getProperty("Title"));
                data.add(ar);
            }
            ObjectMapper mapper =new ObjectMapper();
            JsonArray ob = new JsonArray(mapper.writeValueAsString(data));
            promise.complete(ob);
        }
        catch(Exception e){
            e.printStackTrace();
            promise.fail(e.fillInStackTrace());
        }
```

Trying to Run this simple Query but result set is empty, same query is working fine from OrientDB Studio.
if i change the query to  "select * from Song" than its working fine.

**Comment by luigidellaquila** [comment]
Hi @somnath157 

I'd say `out_SungBy` is a collection, so you have to use CONTAINS instead of =

```
String query = "select * from Song where out_SungBy.in.id CONTAINS ?";
```

In general, I strongly discourage you from using the low level mechanics of edge representations, and use the normal graph API instead:

```
String query = "select * from Song where out("SungBy").id CONTAINS ?";
```

Thanks

Luigi

**Comment by somnath157** [comment]
Hi @luigidellaquila 

Thanks worked with using Contains.
But Facing one more issue here

out('SungBy').in is returning null while out_SungBy.in return values correctly.
is there some difference?

![image](https://user-images.githubusercontent.com/19746163/90748399-c649ae00-e2ef-11ea-9070-c239b0058557.png)

**Comment by luigidellaquila** [comment]
you don't need the `.in` after `out("SungBy")`

in fact, `out("SungBy")` is equivalent to `out_SungBy.in`

**Comment by somnath157** [comment]
Okay and what if i have to access a parameter of the edge than this won't work so i will have to use out_SungBy.fieldName
or is there any better way?

**Comment by luigidellaquila** [comment]
Hi @somnath157 

you can access the edge with `outE("EdgeClassName")` (see out**E**() instead of out())
Then you can access to the following vertex with `inV()`

So the following are equivalent

```
out("EdgeClass")

outE("EdgeClass").inV()
```

To filter based on edge properties, you can use square bracket filtering:

```
outE("EdgeClass")[foo > 5].inV()
```

I hope it helps

Thanks

Luigi

**Comment by somnath157** [comment]
Thanks

Somnath
