### ISSUE TITLE
ShortestPath with multiple edges is returning empty list

### ISSUE THREAD

**Issue by tomazk8** [orientechnologies/orientdb#9388]
## Expected behavior  
ShortestPath should support a list of edges like shows in the documentation: SELECT shortestPath(#8:32, #8:10, 'IN', ['Friend', 'Colleague'])

## Actual behavior  
Empty list is returned when array of edges is used, but works if only one edge without array is given.

## Steps to reproduce
I added one class Person and edges Knows and Loves. A graph was created: P1(Id = #22:0) -Knows-> P2 (Id = #22:1) -Loves-> P3 (Id = #22:2)

This queries returns empty array
  SELECT shortestPath(#22:0, #22:2, 'OUT', ['Knows', 'Loves'])
  SELECT shortestPath(#22:0, #22:1, 'OUT', ['Knows'])
This query returns P1 and P2
  SELECT shortestPath(#22:0, #22:1, 'OUT', 'Knows')

Whenever a list of edges is given, the result is empty. Am I doing something wrong? I searched through all of the examples and the documentation, and the query seems to be correct.

Thanks

**Comment by luigidellaquila** [comment]
Hi @tomazk8 

I just pushed a fix for this problem. The fix will be released with v 3.1.3

Thanks

Luigi
