### ISSUE TITLE
Can't login into forum

### ISSUE THREAD

**Issue by johny65** [orientechnologies/orientdb#9408]
I can't log in into the [OrientDB Community](https://discourse.orientdb.org/) anymore since some days ago. I can't log in with a password because I don't have one, I always logged in using my GitHub account but now the result is an error page with the following message:

```
Oops

The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.

Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it.

No further action is necessary. However, if the error condition persists, you can provide additional detail, including steps to reproduce the error, by posting a discussion topic in the site's feedback category.
```

Trying the "with email" option, it says that my account was found and "should receive an email with a login link shortly", but the email is never received.

**Comment by johny65** [comment]
It seems that now the login is working again.

**Comment by luigidellaquila** [comment]
Hi @johny65 

Sorry for this inconvenience and yes, we just fixed it

Thanks

Luigi
