### ISSUE TITLE
not support gremlin multi-properties

### ISSUE THREAD

**Issue by dptr** [orientechnologies/orientdb#9419]
## Expected behavior  
standard gremlin url: https://tinkerpop.apache.org/docs/current/reference/#vertex-properties

input this gremlin:
g.addV().property('name','hello').property('name','world')
g.V('#13:2').properties('name').count()

the property count is 1,but the gremlin standard is 2, name is overwritten by 'world'

also, it does not support such this: g.addV().property(set, 'key', 'aa', 'bb', 'cc', 'dd') . by the standard gremlin api, it will create a set property with 4 elements.

## Actual behavior  
count is 1

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by dptr** [comment]
i found this method just ignored the first argument cardinality, so the gremlin cardinality feature will not work.
  org.apache.tinkerpop.gremlin.orientdb.OrientVertex#property(org.apache.tinkerpop.gremlin.structure.VertexProperty.Cardinality, java.lang.String, V, java.lang.Object...)

**Comment by lvca** [comment]
Multi values properties are not supported by OrientDB.
