### ISSUE TITLE
cant register on orientdb discourse

### ISSUE THREAD

**Issue by misu200** [orientechnologies/orientdb#9428]
Hello,

I dont know where to send a message about it ... but it is not possible to open new account on dicourse forum from https://discourse.orientdb.org/ 

Rgds,

**Comment by luigidellaquila** [comment]
Hi @misu200 

Yes, you should be able to connect with GitHub or Twitter SSO, or to register with email/pw.
What kind of problems are you experiencing?

BTW, we also just enabled GitHub Discussions, probably you also want to post your questions there https://github.com/orientechnologies/orientdb/discussions

Thanks

Luigi

**Comment by misu200** [comment]
I ve tried with github to create account on discourse ...but not working
Also I ve tried by email but i dont receive the validation email

**Comment by lvca** [comment]
Still not working?

**Comment by tglman** [comment]
Not relevant anymore, use github discussions.
