### ISSUE TITLE
Default cluster size does shrink after records truncate

### ISSUE THREAD

**Issue by stoica-florian** [orientechnologies/orientdb#9431]
## Expected behavior  
After executing TRUCNCATE RECORD [<list of records>]; I expect that the default_*.pcl file to be smaller

## Actual behavior  
The file keeps the exact same size even If I truncate the records

## Steps to reproduce  
Had a lot of records 400k to be more exact, the default cluster had 18.2 GB.
executed TRUNCATE RECORD for 361k of them.
The file kept its size.

## Extra note
I've exported the DB and already the export file had 1.2 GB and after reimporting the file the default_*.pcl file had only 1.9GB

**Comment by stoica-florian** [comment]
I did dig up a bit more and found out that as per documentation this is expected, but please tell me that there is another way to trigger reindexing of the default cluster and not just export/import. Having a function call that does that will help, doing a periodic export/import of a DB that has let's say around 20GB for sure is not a viable solution there must be another way.

**Comment by andrii0lomakin** [comment]
Hi, as for now there is no solution for that. But I have in mind some design changes which will help you in future.

**Comment by stoica-florian** [comment]
Hi, is it by any chance something that will be in the near future?

**Comment by lvca** [comment]
The only way to size down a cluster file is to drop it and re-create it by assigning the same id.
