### ISSUE TITLE
Disk usage is increasing over time without limit, deleting vertex don't reduce disk usage.

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9444]
## Expected behavior  
Disk usage is stable.

## Actual behavior  
Disk usage is growing over time without limit.

.cpm files are growing on each iteration with these steps to reproduce, I think other files related to indexes may be affected too.

## Steps to reproduce  
Run these commands in OrientDB web ui

CREATE CLASS MyClass IF NOT EXISTS EXTENDS V;
CREATE CLASS ConnectsTo IF NOT EXISTS EXTENDS E;
CREATE PROPERTY ConnectsTo.out IF NOT EXISTS LINK MyClass;
CREATE PROPERTY ConnectsTo.in IF NOT EXISTS LINK MyClass;
CREATE INDEX ConnectsTo_out_in IF NOT EXISTS ON ConnectsTo (out, in) UNIQUE_HASH_INDEX;

Insert vertex and edges and then delete them, after each insertion/deletion of vertex database files are growing in disk

LET $i = 0;
WHILE ($i < 1000000){
  LET m1 = INSERT INTO MyClass set value = 1;
  LET m2 = INSERT INTO MyClass set value = 1;
  CREATE EDGE ConnectsTo UPSERT FROM ($m1) TO ($m2);
  LET $i = $i + 1;
}

delete vertex myclass;

**Comment by andrii0lomakin** [comment]
Hi,
I am working on the fix right now.
But unfortunately, it will be placed only in 3.1 version because it requires changes in the binary structure of the cluster.

**Comment by madmac2501** [comment]
Thanks a lot for the good news even if it's only in 3.1.

Please let me know when it's on a git branch to test it.

Thanks!

**Comment by andrii0lomakin** [comment]
It is on https://github.com/orientechnologies/orientdb/tree/laa_free_space_map but not fully fixed yet. There is not too much to test. I will let you know when you can test. Likely it will take two weeks.

**Comment by Jotschi** [comment]
@laa This seems to be related to our OrientDB 3.1.x support ticket `734751 / 2020 Database fragmentation / tombstoning not working as expected` can you confirm this?

**Comment by andrii0lomakin** [comment]
@Jotschi yes that is same.

**Comment by andrii0lomakin** [comment]
Fixed. Please try and provide feedack.
