### ISSUE TITLE
The OrientDB always shutdown automatically after a few hours

### ISSUE THREAD

**Issue by cyberjac0630** [orientechnologies/orientdb#9445]
## Expected behavior  
<When I was start the OrientDB server in my server, I hope the OrientDB server can keep running in the background of the server.>  

## Actual behavior  
<The OrientDB always shutdown automatically after a few hours. When I start the server.sh, I can connect to the OrientDB, but a few hours later, I can't connect to the OrientDB and the system show the OrientDB server not runnning.>  

## Steps to reproduce  
<
1.  ./server.sh>
2.  Just waiting or normal use  
3.  The OrientDB server was shutdown
![微信图片_20201118090915](https://user-images.githubusercontent.com/37230753/99469785-74f89b80-297e-11eb-940d-c908d28af087.png)
![微信图片_202011180909151](https://user-images.githubusercontent.com/37230753/99469789-7629c880-297e-11eb-8aeb-c34840520e03.png)
![微信图片_20201118090915](https://user-images.githubusercontent.com/37230753/99469797-7b871300-297e-11eb-958b-e0fd51117773.png)
![微信图片_202011180909151](https://user-images.githubusercontent.com/37230753/99469805-7f1a9a00-297e-11eb-9f08-e10e14b0c130.png)

<
[root@localhost ~]# service orientdb status
OrientDB server daemon is running with PID: 21928
[root@localhost ~]# service orientdb status
OrientDB server daemon is NOT running
>

**Comment by andrii0lomakin** [comment]
Hi, very likely you will have issues with OOM killer. The process consumes more memory than there is the amount of limit set.

**Comment by xiaowenzh630** [comment]
> Hi, very likely you will have issues with OOM killer. The process consumes more memory than there is the amount of limit set.
