### ISSUE TITLE
Enterpise web sites are not working, how to buy licence

### ISSUE THREAD

**Issue by tolgaulas** [orientechnologies/orientdb#9458]
https://orientdb.com/orientdb-enterprise/ and many other sub page  or orientdb.org is ending with a landing page inviting to SAP Enterprise OrientDB, for sometime?

How one can purchase a license?

**Comment by tglman** [comment]
Hi,

OrientDB Enterprise is now open source here: https://github.com/sap/orientdb-enterprise-agent.

Regards
