### ISSUE TITLE
factory.close() keeps the java process hanging indefinitely

### ISSUE THREAD

**Issue by florian-stoica-tlabs** [orientechnologies/orientdb#9465]
## Expected behavior  
factory.close() keeps the java process hanging indefinitely

## Actual behavior  
factory.close() to eventually end

## Steps to reproduce  
![image](https://user-images.githubusercontent.com/71690732/100433059-2e542100-30a3-11eb-9870-ca88b2864337.png)

I just browse around my app therefore data will be written in db and when I close the app I have a shutdown hook that calls factory.close() this will trigger the above calls and the process hangs indefinitely.

**Comment by andrii0lomakin** [comment]
Hi @florian-stoica-tlabs ,
I am sorry, but we perform tasks which you describe many times a day without any problems.
Could you send us the test to reproduce?

**Comment by tglman** [comment]
Hi @florian-stoica-tlabs,

We had in the past similar issues, but not related to the stack you are posting, can you try the latest hotfix of 3.0.x series (current 3.0.35)
Bye

**Comment by lvca** [comment]
No answer, closing the issue for now. In case, please comment on this very issue.
