### ISSUE TITLE
Index size in disk is increasing over time without limit, deleting vertex don't reduce disk usage by indexes

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9467]
## Expected behavior  
Index file size don't grow indefinitely.

## Actual behavior  
Index files with extension .cbt grows over time without limit.

## Steps to reproduce  
Run these commands in OrientDB web ui. Insert vertex and then delete them, after each insertion/deletion of vertex index files are growing in disk

CREATE CLASS MyClass IF NOT EXISTS EXTENDS V;
CREATE PROPERTY MyClass.longProperty IF NOT EXISTS LONG;
CREATE INDEX MyClass.longProperty IF NOT EXISTS NOTUNIQUE;

LET $i = 0;
WHILE ($i < 1000000){
LET m1 = INSERT INTO MyClass set longProperty = date().aslong();
LET $i = $i + 1;
}

delete vertex myClass;

**Comment by andrii0lomakin** [comment]
Hi,
We aware about this issue.
It will be addressed soon.

**Comment by madmac2501** [comment]
Any update on this? Thanks for the work

**Comment by andrii0lomakin** [comment]
Hi @madmac2501 , we have started to work on this, but the change was paused because of an issue with higher importance. None the less we plan to continue with this change once we fix the issue on which we are working right now. But I can not provide ETA as for now.

**Comment by andrii0lomakin** [comment]
Hi fixed both in 3.1 and 3.2 versions.
