### ISSUE TITLE
HashSet available in JavaScript server functions?

### ISSUE THREAD

**Issue by thenesk** [orientechnologies/orientdb#9490]
### OrientDB Version: >3.0.19 
In OrientDB 3.0.19 and earlier I was able to use the Java HashSet object to get sets in JavaScript server functions.  I just tried 3.0.34 and it seems this no longer works.  The relevant code looks something like this:

`var myHashSet = Java.type("java.util.HashSet");
var aSet = myHashSet();`

Are there any easy fixes to get sets working?  Are there any longer term recommendations since the nashorn engine is deprecated?

**Comment by PhantomYdn** [comment]
This issue is related to #9432 . I recommend to read it and adjust settings correspondingly. Also you can use workaround as we do:
https://github.com/OrienteerBAP/Orienteer/blob/e25ed7e43dc1e745de1269a4cf5bbec34b972235/orienteer-core/src/main/java/org/orienteer/core/service/OrienteerEmbeddedStartupListener.java#L72-L81

**Comment by thenesk** [comment]
@PhantomYdn, thanks for pointing me to the related issue and showing me your workaround!  I am not currently using any java code, so I am not sure how difficult it will be to incorporate this workaround.  But I am glad to see I am not the only one getting class errors with javascript.  Hopefully there will be a fix or a workaround in JavaScript.

**Comment by lvca** [comment]
Thanks @PhantomYdn for the workaround. @thenesk we're not supporting Nashorn anymore for the new releases because GraalVM is the future for Java (in good and bad...)

**Comment by thenesk** [comment]
@lvca, do you have any guidance or documentation on how to migrate JavaScript server functions from Nashorn to GraalVM?

**Comment by lvca** [comment]
You can find some resources below:
- https://docs.oracle.com/en/graalvm/enterprise/20/docs/reference-manual/js/NashornMigrationGuide/
- https://www.graalvm.org/reference-manual/js/NashornMigrationGuide/

Please bear in mind that we're not using the compatibility mode `--experimental-options --nashorn-compat`
