### ISSUE TITLE
OSchedule events do not scheduled on server startup

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9500]
## Expected behavior  
All scheduled events (OSchedule) should start again after server restart.  

## Actual behavior  
No events actually scheduled and only "touching" of required events helps to schedule them again.

## Steps to reproduce  
1. Schedule any event with some visible sideeffect
2. Make sure that after scheduling - everything is OK
3. Restart server
4. Previously scheduled events are not fired anymore

# Issue Root Cause:

Please check the following 2 snippets:

### OSchedulerImpl.load()
```java
public void load(ODatabaseDocumentInternal database) {

    if (database.getMetadata().getSchema().existsClass(OScheduledEvent.CLASS_NAME)) {
      final Iterable<ODocument> result = database.browseClass(OScheduledEvent.CLASS_NAME);
      for (ODocument d : result) {
        final OScheduledEvent event = new OScheduledEvent(d);

        if (events.putIfAbsent(event.getName(), event) == null) this.scheduleEvent(event);
      }
    }
  }
```
### OSchedulerImpl.scheduleEvent()
```java
public void scheduleEvent(final OScheduledEvent event) {
    if (event.getDocument().getIdentity().isNew())
      // FIST TIME: SAVE IT
      event.save();

    if (events.putIfAbsent(event.getName(), event) == null) {
      String database = event.getDocument().getDatabase().getName();
      event.schedule(database, "admin", orientDB);
    }
  }
```

During startup load is invoked and first `putIfAbsent` putting event in the queue, but method `scheduleEvent()` doesn't actually schedule event because second `putIfAbsent` returns previous event.

**Comment by lvca** [comment]
Cherry-picked on 3.1.x too.

**Comment by lvca** [comment]
Thanks, Ilia!
