### ISSUE TITLE
Edge Insertion throughput slows down over time

### ISSUE THREAD

**Issue by ahannes** [orientechnologies/orientdb#9511]
## Expected behavior  
Constant Edge insertion throughput

## Actual behavior  
Exponential slowdown of Edge insertion throughput

## Steps to reproduce  
We observed exponential write throughput degradation over time when creating Edges between two Nodes. A particular testcase was inserting 1,000,000 edges between the same two vertices. The observations is the same for using jdbc directly or the java api for “create edge”. 
 
We analyzed the create edge and determined the following steps being executed:

- Create the Edge as new "Document"
- Setting "from" and "to" properties on the Edge
- Save the Edge 
- Load  Source- und Target-Node out of the DB 
- **Enter the rid of the Edge in the "out"-List of the Source node and in the "in"-List of the Target Node**
- **Saving the updated Nodes**

We observed the last step to take longer, the longer the lists become.
 
Our current assumption is that the management of big LINKLIST is the reason for the performance observation.
 
Another test we made inserted only one edge per two nodes and we didn’t observe the exponential slowdown, which seems to confirm our assumption.
 
Or immediate questions would be:
1.	Is our assumption correct that the observed slowdown is caused by the LINKLIST?
2.	What does CREATE EDGE do exactly? 
3.	Can the steps performed by CREATE EDGE be done manually? 
 
Our current approach is to not use "CREATE EDGE", and instead insert the EDGE via standard INSERT, maintain the "in" and "out" LINKLISTS of the source and target nodes manually and only perform an update on the source and target nodes once all Edges have been inserted.
Any input on the viability of this approach, potential pitfalls or different best practices for similar workarounds would be highly appreciated.

**Comment by lvca** [comment]
@Ariana9 create edge does pretty much what you're describing. As far as you keep the lists updated it should work.
