### ISSUE TITLE
ORemoteSchema sometimes doesn't contain all the classes.

### ISSUE THREAD

**Issue by gunaskr** [orientechnologies/orientdb#9519]
## Expected behavior  
After creating all the classes in orient db. When i get db instance from ODatabaseRecordThreadLocal.instance().getDBIfDefined() and get shema and call getOrCreateClass, with my class name. I expect it to give me the class without creating new classs.

## Actual behavior  
It seems like the db instance and the metadata from there doesn't contain any of the classes that we created and tries to create a new class. Since the classes are clearly already present we get Class '<class name >' already exists exception.

## Steps to reproduce  
In a multithreaded environment getDB instance from ODatabaseRecordThreadLocal and see if the schema gives all the classes.
Will update with proper test case ASAP.

**Comment by tglman** [comment]
Refer to a really outdated version, in case the version was mistaken reopen please
