### ISSUE TITLE
java.lang.IllegalStateException: RidBag is not properly initialized, can not load tree implementation

### ISSUE THREAD

**Issue by rhdxmr** [orientechnologies/orientdb#9520]
## Actual behavior  

> Exception `62ECA034` in storage `plocal:/orientdb/databases/demodb`: 3.2.0-SNAPSHOT (build d0aff5deb84c96f64df8fa4d2bfe1d02cd4734d0, branch develop)
> java.lang.IllegalStateException: RidBag is not properly initialized, can not load tree implementation                                                          
>         at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:955)
>         at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:660)
>         at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:236)                                                                   
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeSBTreeRidbag(HelperClasses.java:426)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeRidBag(HelperClasses.java:356)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.writeRidBag(ORecordSerializerBinaryV1.java:731)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValue(ORecordSerializerBinaryV1.java:102
> 0)                                     
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValues(ORecordSerializerBinaryV1.java:40
> 4)                                     
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeDocument(ORecordSerializerBinaryV1.java:
> 462)                                   
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serialize(ORecordSerializerBinaryV1.java:483)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:132)
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:5965)
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2396)
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2219)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2275)
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:627)
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:119)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1795)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1765)
>         at org.apache.tinkerpop.gremlin.orientdb.OrientTransaction.doCommit(OrientTransaction.java:70)                                                         
>         at org.apache.tinkerpop.gremlin.orientdb.OrientStandardTransaction.doCommit(OrientStandardTransaction.java:27)
>         at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
>         at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.onTraversalSuccess(TraversalOpProcessor.java:471)
>         at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.handleIterator(TraversalOpProcessor.java:521)
>         at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.lambda$iterateBytecodeTraversal$4(TraversalOpProcessor.java:411)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                            
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                            
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                     
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                     
>         at java.lang.Thread.run(Thread.java:748)                               
> $ANSI{green {db=demodb}} Error on transaction commit `62ECA034`                                                                                                
> java.lang.IllegalStateException: RidBag is not properly initialized, can not load tree implementation                                                          
>         at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:955)
>         at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:660)
>         at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:236)                                                                   
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeSBTreeRidbag(HelperClasses.java:426)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeRidBag(HelperClasses.java:356)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.writeRidBag(ORecordSerializerBinaryV1.java:731)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValue(ORecordSerializerBinaryV1.java:102
> 0)                                     
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValues(ORecordSerializerBinaryV1.java:40
> 4)                                     
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeDocument(ORecordSerializerBinaryV1.java:
> 462)                                   
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serialize(ORecordSerializerBinaryV1.java:483)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:132)
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:5965)
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2396)
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2219)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2275)
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:627)
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:119)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1795)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1765)
>         at org.apache.tinkerpop.gremlin.orientdb.OrientTransaction.doCommit(OrientTransaction.java:70)                                                         
>         at org.apache.tinkerpop.gremlin.orientdb.OrientStandardTransaction.doCommit(OrientStandardTransaction.java:27)
>         at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
>         at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.onTraversalSuccess(TraversalOpProcessor.java:471)
>         at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.handleIterator(TraversalOpProcessor.java:521)
>         at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.lambda$iterateBytecodeTraversal$4(TraversalOpProcessor.java:411)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                            
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                             
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                            
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                     
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                     
>         at java.lang.Thread.run(Thread.java:748)                               
> Exception processing a Traversal on iteration for request [534481e3-43da-486c-be0d-8c2c79112570].                                                              
> java.lang.IllegalStateException: RidBag is not properly initialized, can not load tree implementation                                                          
>         at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:955)
>         at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:660)
>         at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:236)                                                                   
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeSBTreeRidbag(HelperClasses.java:426)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeRidBag(HelperClasses.java:356)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.writeRidBag(ORecordSerializerBinaryV1.java:731)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValue(ORecordSerializerBinaryV1.java:102
> 0)                                     
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValues(ORecordSerializerBinaryV1.java:40
> 4)                                     
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeDocument(ORecordSerializerBinaryV1.java:
> 462)                                   
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serialize(ORecordSerializerBinaryV1.java:483)
>         at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:132)
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:5965)
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2396)
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2219)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2275)
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:627)
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:119)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1795)
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1765)
>         at org.apache.tinkerpop.gremlin.orientdb.OrientTransaction.doCommit(OrientTransaction.java:70)                                                         
>         at org.apache.tinkerpop.gremlin.orientdb.OrientStandardTransaction.doCommit(OrientStandardTransaction.java:27)
>         at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
>         at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.onTraversalSuccess(TraversalOpProcessor.java:471)
>         at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.handleIterator(TraversalOpProcessor.java:521)
>         at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.lambda$iterateBytecodeTraversal$4(TraversalOpProcessor.java:411)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                            
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                             
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                            
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                     
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                     
>         at java.lang.Thread.run(Thread.java:748)
> 

## Steps to reproduce  
This error occurs in the middle of uploading triples using gremlin.
The server became totally unavailable after uploading triples for 16 minutes..

There are nothing special in the gremlin traversal code.
just called  normal gremlin traversal code like .addV, .property, .has, addE, .to, and so on..

**Comment by pergrand** [comment]
Hello, have you solved this problem? I also encountered this problem。

**Comment by tglman** [comment]
Hi,

I would suggest to try this case with the latest 3.2.x series, our tests works all pretty OK since a while so I guess this was a temporary failure on the develop branch.

Regars
