### ISSUE TITLE
OrientDB 3.0.36 database deadlocked

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9527]
## Expected behavior  
OrientDB doesn't deadlock

## Actual behavior  
OrientDB database deadlocked. One thread consuming 100% cpu and cannot login into the database

## Steps to reproduce  
Write in parallel using transactions to the same database.

See thread dumps attached
[dump1.log](https://github.com/orientechnologies/orientdb/files/5911332/dump1.log)
[dump2.log](https://github.com/orientechnologies/orientdb/files/5911334/dump2.log)

**Comment by madmac2501** [comment]
is there any mechanism to get what queries are running? or any other info so I can try to debug this

**Comment by andrii0lomakin** [comment]
HIi @madmac2501 sorry there is no such one. I am quite busy right now with customer issues as for now. Once I have time I will look on that one too.

**Comment by ozgursucu** [comment]
Hi @madmac2501 what is the current situation of this problem?

**Comment by madmac2501** [comment]
Hi, I moved to another solution and no longer use OrientDB.

Thanks for asking.
