### ISSUE TITLE
Where is the best place to get support for OrientDB?

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientdb#9536]
It appears that https://discourse.orientdb.org/ has been abandoned, and even https://orientdb.com/ has been a placeholder for months, but steady work still continues on the product. What is the recommended best place to get support? Is paid support available?

**Comment by luigidellaquila** [comment]
Hi Eric,

Sorry for the inconvenience with Discourse, we are having some problems with the server... 
A few months ago we activated GitHub Discussions as an attempt to unify the Community topics on a single platform, I'd suggest to use it for your questions (https://github.com/orientechnologies/orientdb/discussions).

For paid support, you can send an email to orientdb_enquiries@sap.com

Thanks

Luigi
