### ISSUE TITLE
Meterian reports vulnerable and outdated dependencies

### ISSUE THREAD

**Issue by MarttiR** [orientechnologies/orientdb#9545]
### OrientDB Version: 3.1.8

Meterian [reports](https://www.meterian.io/projects/?pid=29a79522-f62e-4d2e-910c-28ebdcebb111&branch=3.1.8) several CVEs for dependencies on the 3.1.8 branch.

1. Are there plans to update these dependencies?
2. What is the overall impact of these vulnerabilities considering mitigation?

**Comment by luigidellaquila** [comment]
Hi @MarttiR 

Yes, we are addressing these vulnerabilities now. 
The impact should be very limited anyway, the we use FasterXML only for some import procedures, not in the core functionalities

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @MarttiR 

I just pushed some fixes for the most relevant security problems reported

Thanks

Luigi

**Comment by MarttiR** [comment]
Awesome, thank you for the swift action @luigidellaquila !

**Comment by tglman** [comment]
Closing this, all the dependencies that could be update have been updated.
