### ISSUE TITLE
Multiple issues in OrientDB ETL

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9559]
### OS: any

There are multiple issues in OrientDB ETL. To be honest, it's hard to say: is it working at all?:) So my main question is: **is OrientDB ETL recommended for actual use? Isn't it deprecated?**
If it's active - not a problem - will fix and send PRs.

Few examples:

1) There is NPE if lock was requested for source file
2) There is NPE in processing simple CSV (still investigating source - it's harder to do due to p.3)
3) Logs are not relevant. For example: `OETLContextWrapper.getInstance().getMessageHandler().error(this, "ETL process halted: ", e);` - there is "ETL process halted: " is actually `format` for message - as a result passed exception not even shown in logs.
4) `OETLContextWrapper.getInstance().getMessageHandler()` - is taking global MessageHandler. Bersion 2 allowed to configure Message Handler per execution - but due to this change - there is no ability to catch "grouped" errors logs per execution.
5) `OETLProcessor.execute()` is just sequencial execution of underlying methods - so no catch/finally and etc. As a result - if something happened during records processing - nothing will be "closed" properly.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

Yes, the ETL module is still supported.
I'll try to check the issues you reported, but if you have a fix it will be much appreciated 

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila , just bts: I'm collecting all proposals in the following my branch: https://github.com/PhantomYdn/orientdb/tree/orientdbetl_fix

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

Perfect, thanks!
Please let me know when you have something ready to check

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila , please check PR #9577

**Comment by PhantomYdn** [comment]
@luigidellaquila , please consider merging.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

Checking now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Merged, thanks!
