### ISSUE TITLE
Can't insert new key,value pair in embedded map using pure SQL

### ISSUE THREAD

**Issue by mcasatti** [orientechnologies/orientdb#9565]
## Expected behavior  
Embedded map field with new key,value pair inserted

## Actual behavior  
com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot execute with UPDATE PUT/ADD/INCREMENT new executor: PUT Equivalencias = 'KEY', 1, Error

 
--

## Steps to reproduce  
update Concepto PUT Equivalencias = 'KEY', 1 where Nombre = 'TESTTRES'

**Comment by luigidellaquila** [comment]
Hi @mcasatti 

Does the map exist already?
In this case, you can try the following:

```
update Concepto SET Equivalencias.KEY = 1 where Nombre = 'TESTTRES'

update Concepto SET Equivalencias['KEY'] = 1 where Nombre = 'TESTTRES'

```
Thanks

Luigi

**Comment by mcasatti** [comment]
It works! Thanks @luigidellaquila

**Comment by tglman** [comment]
seems solved, closing
