### ISSUE TITLE
AMI removed from AWS ?

### ISSUE THREAD

**Issue by grv87** [orientechnologies/orientdb#9574]
I want to launch a fresh OrentDB instance in AWS.
I perform steps according to [documentation](https://orientdb.org/cloud/orientdb-amazon-web-services).
But there are no OrientDB AMIs in AWS Marketplace (except one provided by Miritech).

I found [this AMI](https://aws.amazon.com/marketplace/pp/B00M07FHAO) in archives, but it says:
> This version has been removed and is no longer available to new customers

Is it permanent situation, i.e. AMI has been removed from AWS, and there will be no OrientDB Community Edition AMI? What is current recommended way to deploy to cloud then, and when documentation will be updated?
Or is it just temporary blink, and I should wait?

**Comment by kristianmandrup** [comment]
I have the same issue. Looks like we would have to find or manually create a docker image then install that on AWS on Fargate or an EC2 instance. I would recommend looking into AWS CDK for easy deployment.

https://www.qwant.com/?client=ext-chrome-sb&q=docker+on+aws+fargate&t=web

https://github.com/markusl/cdk-fargate-docker-starter

https://pypi.org/project/aws-cdk.aws-ecs-patterns/

https://hub.docker.com/_/orientdb/

https://orientdb.org/docs/3.0.x/admin/Docker-Home.html - Installing orientDB in docker container

You can find loads of useful CDK templates here - https://github.com/miztiik/my-first-cdk-project (also has a Udemy course where he goes through all of them)

I will try to build an OrientDB CDK construct for OrientDB 3.11 (with parameterised version number)

**Comment by kristianmandrup** [comment]
I created a CDK construct for OrientDB here - https://github.com/kristianmandrup/orientdb-aws-cdk-construct

Have yet to test it but will do so shortly. Feel free to try it out, debug, make suggestions etc :)

**Comment by kristianmandrup** [comment]
To use it, I would recommend a setup similar to: https://github.com/dabit3/cdk-appsync-neptune

**Comment by kristianmandrup** [comment]
I've done a "hell of a lot" of research to provide a good foundation to build on and work from. Hope it works out for you.
I would love to collaborate to build a solid solution.

**Comment by lvca** [comment]
Thanks @kristianmandrup for your contributions.

Unfortunately for company policy, we had to remove our official AMI from AWS and MS Azure. I hope there will be even more contributions on this in the future.

**Comment by grv87** [comment]
@lvca, then please remove AWS and MS Azure from documentation.
