### ISSUE TITLE
OrientDB ver 2.2.14

### ISSUE THREAD

**Issue by phihong89** [orientechnologies/orientdb#9586]
### OS: window server 2012

the orientdb data I deleted a lot but the capacity is not decreasing, hope everyone can help
![A5A5360B-7DE6-467D-A835-2489201B297C](https://user-images.githubusercontent.com/22212634/114804637-d016a900-9dcb-11eb-9c3b-506bd5a9ef8e.jpeg)

## Expected behavior  
<add here>  

## Actual behavior  
<add here> 

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by luigidellaquila** [comment]
Hi @phihong89 

OrientDB does not recollect space from the clusters when records are deleted. 
The easy solution to defragment a DB is to export and re-import it

In general, v 2.2.14 is really very outdated, I'd strongly suggest to upgrade to latest 3.1.11 or, if you have constraints on v 2.2.x, to use 2.2.37

Thanks

Luigi
