### ISSUE TITLE
Javadoc reference is broken

### ISSUE THREAD

**Issue by qualitesys** [orientechnologies/orientdb#9587]
The Javadocs url seams broken http://www.orientechnologies.com/javadoc/latest/
Is it possible to fix it ?
Thanks

**Comment by luigidellaquila** [comment]
Hi @qualitesys 

For now orientechnologies.com domain is not active, I'd suggest to use the following instead

http://www.orientdb.com/javadoc/latest/

Thanks

Luigi

**Comment by qualitesys** [comment]
Closed
