### ISSUE TITLE
server.sh fail to start

### ISSUE THREAD

**Issue by rahul2240** [orientechnologies/orientdb#9600]
## Expected behavior  
should start orient db

## Actual behavior  
![Screen Shot 2021-05-04 at 11 27 54 AM](https://user-images.githubusercontent.com/25618739/116965584-ce098100-accb-11eb-85a5-b706afe3f04d.png)

## Steps to reproduce  
1. run server.sh

**Comment by luigidellaquila** [comment]
Hi @rahul2240 

It's due to removed APIs in Java > 15.
It's a known problem and we will address it soon, but for now I'd suggest to use Java 8 - 11

Thanks

Luigi

**Comment by rahul2240** [comment]
Hi @luigidellaquila 

Yes, it worked. 

Thanks
