### ISSUE TITLE
Use of SecureRandom.getInstanceStrong can cause database creation to block

### ISSUE THREAD

**Issue by timw** [orientechnologies/orientdb#9603]
## Expected behavior  
Database creation does not block on startup.

## Actual behavior  
When instantiating a database (e.g. an in-memory DB) the database creation blocks for a significant period (over 1 minute in our case).

## Steps to reproduce  
Create an embedded, in-memory, database without specifying a `NETWORK_TOKEN_SECRETKEY` configuration parameter.

## Root Cause Analysis
In 3.1, `OTokenHandlerImpl` used a `new RandomI()` to generate key bytes in the event that `NETWORK_TOKEN_SECRETKEY` was not defined in the configuration.
This was non-blocking (good) but not a secure PRNG (bad).

In 3.2 this has been changed (in `OTokenSignImpl`) to use `SecureRandom.getInstanceStrong()`, which (on Linux and Mac at least) defaults to the `NativePRNGBlocking` implementation, which uses the (blocking) `/dev/random` device.

A static `new SecureRandom()`, which will choose a secure non-blocking PRNG, would be the right thing to use in this scenario.

This issue has come up in a bunch of projects:
- https://tersesystems.com/blog/2015/12/17/the-right-way-to-use-securerandom/ explains what is going on in the SecureRandom
- https://github.com/akka/akka/issues/20908 is an example of Akka making this change

**Comment by luigidellaquila** [comment]
Hi @timw 

Thank you very much for your suggestion, I'd say it makes sense.
I'm flagging this as an enhancement and I'll see if we can add it to the roadmap ASAP

Thanks

Luigi

**Comment by johny65** [comment]
Because of this issue we were unable to install 3.2 version in our remote servers, because the start process stuck waiting for hours due to this blocking way of generating a key, and we didn't know why. Then we found a solution using the `haveged` tool, as [this article shows](https://github.com/orientechnologies/orientdb-helm/blob/master/havegedSetup.md) (the recommendation is given in orientdb-helm, I think the same recommendation must be given in the normal use-case).

**Comment by mmacfadden** [comment]
@luigidellaquila I might be able to offer up a PR on this if you guys are interested.

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

That would be great, thanks!

Luigi

**Comment by timw** [comment]
Apologies - I already had a branch for this fix and got distracted before I raised a PR.

**Comment by mmacfadden** [comment]
@timw No worries you caught it before I wasted any time on it! Thanks.  I can take a look at it.
