### ISSUE TITLE
Upsert Not working with the class cluster name in Update query

### ISSUE THREAD

**Issue by SameerChorge94** [orientechnologies/orientdb#9630]
### Java Version: 
```
java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```
## Expected behavior  
Update class record query should work with UPSERT keyword and the CLUSTER name provided 

## Actual behavior  
Not able to execute the Update query consisting of the UPSERT Keycword and  CLUSTER name 
![image](https://user-images.githubusercontent.com/55871576/123652753-326b3b80-d84a-11eb-97f3-c2ceebcd43fc.png)

## Steps to reproduce  
1. I added one class Customer with the two properties name and customerNo
2. added the cluster for the class using below query
` ALTER CLASS customer ADDCLUSTER UK_Customers`
3. given the Unique index name in the customer vertex
4. Executed the below UPDATE query
```
UPDATE customer CLUSTER:UK_Customers SET name = “David”, customerNo =“C001”
UPSERT RETURN AFTER @rid, * WHERE customerNo =“C001”
```

but getting this error mentioned in Actual result section 

Is there any workaround for UPSERT for the queries using cluster names Or is there any syntax error in above update query with UPSERT keyword

**Comment by luigidellaquila** [comment]
Hi @SameerChorge94 

I just pushed a fix that solves this problem, it will be released with v 3.1.13

Please consider that your SQL syntax is wrong anyway: you have to specify the class OR the cluster as target, not both: eg.

```
UPDATE CLUSTER:UK_Customers SET name = “David”, customerNo =“C001”
UPSERT RETURN AFTER @rid, * WHERE customerNo =“C001”
```

Thanks

Luigi
