### ISSUE TITLE
Really slow drop of indexes

### ISSUE THREAD

**Issue by johny65** [orientechnologies/orientdb#9637]
## Expected behavior  

To drop indexes instantaneously (or fast enough).

### Discussed in https://github.com/orientechnologies/orientdb/discussions/9592

<div type='discussions-op-text'>

<sup>Originally posted by **johny65** April 27, 2021</sup>
Is it normal to take so much time to drop an index? I have an index over 3 millions of vertices, dropping it takes almost 7 minutes:

    Server side script executed in 270,993988 sec(s). Value returned is: [][Started multi-line command. Type just 'end' to finish and execute]

I have a migrated database with several auxiliary indexes for the migration process, deleting all of those auxiliary indexes takes an hour or more. Even so, if I don't run the drop commands in separate scripts, then all my RAM is exhausted. Is this an issue or is it normal? (Using 3.1.x version).</div>

I have to add that yesterday I had a case where dropping an index took more than 5 hours!

```
orientdb {db=heimdall}> drop index myindex;

Removing index...
Dropped index in 20118,683594 sec(s).

Index removed successfully
```

## Steps to reproduce  

Create a large index and drop it.

**Comment by tglman** [comment]
Hi,

In newer versions like 3.2.13 and 3.2.14 the drop of the index should be faster.

Regards

**Comment by tglman** [comment]
Hi,

Other optimization came in 3.2.17 (just released), is it the performance with the latest release good enough for you ?

Regards

**Comment by johny65** [comment]
Hi @tglman, I will check the new version as soon as possible. Thank you.

**Comment by tglman** [comment]
Hi,

Closing this, please re-open if you can still reproduce the problem.
