### ISSUE TITLE
OrientDb starts for a very long time

### ISSUE THREAD

**Issue by Malamut54** [orientechnologies/orientdb#9644]
## Expected behavior  
OrientDb Starts quickly

## Actual behavior  
I am using the following configuration

ersion: "3"
services:
  odb1:
    image: orientdb
    command: dserver.sh
    environment:
      ORIENTDB_ROOT_PASSWORD: root
      ORIENTDB_NODE_NAME: odb1
      ORIENTDB_OPTS_MEMORY: -Xmx8g
    ports:
      - 2480:2480
      - 2424:2424

  odb2:
    image: orientdb
    command: dserver.sh
    environment:
      ORIENTDB_ROOT_PASSWORD: root
      ORIENTDB_NODE_NAME: odb2
      ORIENTDB_OPTS_MEMORY: -Xmx8g
    depends_on:
      - odb1

And when I run docker I get the next log

2021-07-28 09:39:12:437 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2021-07-28 09:39:12:438 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2021-07-28 09:39:12:438 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2021-07-28 09:47:38:140 INFO  Databases directory: /orientdb/databases [OServer]
2021-07-28 09:47:38:162 INFO  Creating the system database 'OSystem' for current server [OSystemDatabase]

it takes almost 10 minutes to start app

**Comment by andrii0lomakin** [comment]
Hi, @Malamut54 do you have those problems only if you start the OrientDB server in a distributed configuration, or do you have such problems even with a single server started?

**Comment by Malamut54** [comment]
> even with a single server

**Comment by andrii0lomakin** [comment]
OK. Then could you send us series of thread dumps to understand the root cause of the problem?

**Comment by andrii0lomakin** [comment]
Hi @Malamut54 how much memory do you have ?

**Comment by suhassumukh** [comment]
I encountered the same problem with the 3.2.0 release. The issue disappeared after switching to 3.2.1.

**Comment by andrii0lomakin** [comment]
Good to know. Thank you :-)
