### ISSUE TITLE
HashCode contract of OClassRemote is not respected

### ISSUE THREAD

**Issue by kai-baumann** [orientechnologies/orientdb#9650]
## Expected behavior  
HashCode for a given OClassRemote (e.g. "Person") should be equals to another OClassRemote of a given Vertex with Class Person. Is this intended?

The general contract of hashCode is: (from the javadoc of hashcode)

Whenever it is invoked on the same object more than once during an execution of a Java application, the hashCode method must consistently return the same integer, provided no information used in equals comparisons on the object is modified. This integer need not remain consistent from one execution of an application to another execution of the same application.
If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.
It is not required that if two objects are unequal according to the equals(java.lang.Object) method, then calling the hashCode method on each of the two objects must produce distinct integer results. However, the programmer should be aware that producing distinct integer results for unequal objects may improve the performance of hash tables.

## Actual behavior  
The HashCode of the two Objects is not equals. But the equals method returns true.

## Steps to reproduce  
```
OClass superclass = ... fetch class;
OVertex vertex = repository.create(data);

OVertex fetchedVertex = repository.findAll().get(0); // vertex
Collection<OClass> allSuperClasses = fetchedVertex.getAllSuperClasses();
allSuperClasses .contains(superclass) = false

allSuperClasses.get(0).equals(superclass) = true
```

**Comment by andrii0lomakin** [comment]
Yes, that is definitely an issue. That is not a high priority but we should look at it.
