### ISSUE TITLE
compability  problem with LocalDateTime object

### ISSUE THREAD

**Issue by khalidmrabti** [orientechnologies/orientdb#9653]
Hello everyone,
I have a problem when saving a LocalDateTime object in the database, it shows as a string, so I cant query it.
but when retrieving from the database, it gets retrieved as java.time.LocalDateTime.

user version and platforms:
## Expected behavior  
saving java.time.LocalDateTime object in database is **datetime** type

## Actual behavior  
saving java.time.LocalDateTime object in database is a **string** like this "rO0ABXNyAA1qYXZhLnRpbWUuU2VylV2EuhsiSLIMAAB4cHcOBQAAB+UIERAWNAfO5sB4"

## Steps to reproduce  
OElement testingClass = db.newInstance("TestingClass");
testingClass.setProperty("test_date", LocalDateTime.now());
testingClass.save();
//then see the result from the web UI 
am sorry for my English, but i hope you got the idea

**Comment by andrii0lomakin** [comment]
Hi @khalidmrabti .
We do not support LocalDateTime type, you should convert it into the DateTime or Date type to use it.
OrientDB is general use database and can not cover all existing data types.

**Comment by andrii0lomakin** [comment]
@khalidmrabti I am closing the issue if you encounter problems with Date or DateTime objects please reopen it.
