### ISSUE TITLE
OETL command window hangs indefinitely

### ISSUE THREAD

**Issue by amgiorgi** [orientechnologies/orientdb#9659]
## Expected behavior  
<add here>  

## Actual behavior  
When running oetl to populate class from database the command window hangs indefinitely reporting

""
create contextembedded:../databases
""

In spite of never giving any other output, the ETL process succeeds and records are loaded. The window, however, has to be terminated abruptly with CTRL+C or from Windows task manager.

## Steps to reproduce  
Create a JSON similaro to this, I am using Vertica but I have experienced same behavior with MySQL

#oetl_config.json

{
  "config": {
    "log": "debug"
  },
  "extractor" : {
    "jdbc": { "driver": "com.vertica.jdbc.Driver",
              "url": "jdbc:vertica://192.168.56.13:5433/STORE",
              "userName": "dbadmin",
              "userPassword": "xxxxxxxxxx",
              "query": "select col, col2, col3, ......... from tablename limit 10000" }
  },
  "transformers" : [
   { "vertex": { "class": "articles"} }
  ],
  "loader" : {
    "orientdb": {
      "dbURL": "plocal:../databases/Articles",
      "dbAutoCreate": true,
	  "dbUser" : "admin",
	  "dbPassword" : "xxxxxxxxxxxxx",
	  "batchCommit" : 1000
    }
  }
}

run:   oetl.bat  oetl_config.json

**Comment by ghost** [comment]
I got the same issue on a clean OrientDB 3.2.2, using the [official docker image](https://hub.docker.com/layers/orientdb/library/orientdb/3.2.2/images/sha256-b65e1b583cc8da31e1c7d1bd1bf93e121b3f95a461c3fa829a4f1b025380aeb3?context=explore) and following [the OrientDB tutorial for ETL+csv](https://orientdb.org/docs/3.2.x/etl/Import-from-CSV-to-a-Graph.html).

```
OrientDB etl v.3.2.2 (build 6df1d1942b88896dabea123fe1b8b0c6975e025a, branch UNKNOWN) https://www.orientdb.com
create contextembedded:/orientdb/databases

=> Hangs, need to do Ctrl+C to interrupt the process
```

Do you have any workaround to avoid having the process hanging ?

**Comment by amgiorgi** [comment]
I can confirm that this bug still persists also with version 3.2.3.

**Comment by NicolasRuiz99** [comment]
Same issue with ver. 3.2.4 :/

**Comment by tglman** [comment]
Hi,

Is there anyone that can provide a thread dump of the etl process, that would help to fix this.

Regards

**Comment by NicolasRuiz99** [comment]
[threaddump.txt](https://github.com/orientechnologies/orientdb/files/9236470/threaddump.txt)

**Comment by tglman** [comment]
Hi,

This may be fixed in 3.2.9, can you double check it?

Regards

**Comment by NicolasRuiz99** [comment]
Yes, now it works without any problem. Thanks!

**Comment by tglman** [comment]
Perfect, closing
