### ISSUE TITLE
Cannot start embedded server in OSGI environment

### ISSUE THREAD

**Issue by condast** [orientechnologies/orientdb#9664]
## Expected behavior  
I am trying to start an embedded server in an OSGI Bundle:

			String orientdbHome = new File("").getAbsolutePath(); 
			System.setProperty("ORIENTDB_HOME", orientdbHome);

			OServer server = OServerMain.create();
			InputStream inp = getClass().getResourceAsStream(S_DEFAULT_CONFIG_FILE);
			server.startup( inp);

This should start the server without problems

## Actual behavior  

When I run the application I get the following error:

```
2021-09-01 10:30:58:293 INFO  Loading configuration from input stream [OServerConfigurationLoaderXml]Invalid syntax. Below an example of how it should be:
java.lang.NullPointerException
	at javax.xml.bind.ContextFinder.handleClassCastException(ContextFinder.java:129)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:265)
```
However, I cannot debug this problem because ContextFinder is as follows at line 129:

    /**
     * Create an instance of a class using the specified ClassLoader
     */
    static JAXBContext newInstance( String contextPath,
                               String className,
                               ClassLoader classLoader,
                               Map properties )
        throws JAXBException {
 **129**       try {
            Class spFactory = safeLoadClass(className,classLoader);
            return newInstance(contextPath, spFactory, classLoader, properties);
        } catch (ClassNotFoundException x) {

I am pretty sure that the problem is related to classloading issues, and that JAXBContext is expecting a class that is not on the classpath. However it is impossible to find out which class is missing, due to debugging problems.

It is interesting to notice that when I start the server with a default configuration with  OServerConfiguration  (without using files, strings or input streams), everything starts fine.   

## Steps to reproduce  

1: Create an OSGI bundle in Eclipse IDE
2: Programmatically start the Orientdb server, according to the tutorials, using a file, String or inputstream
3: run the bundle  

NOTE: OrientDB does not compile in OSGI. The nashorn.jar needs to be added to the bundle.

**Comment by andrii0lomakin** [comment]
@condast I am sorry , but we don't have plans as for now to support OSGi environment.
