### ISSUE TITLE
Reopening #9164

### ISSUE THREAD

**Issue by KiyoshiCMF** [orientechnologies/orientdb#9691]
Reopening closed Issue requested by SAP represent.
See detail in https://github.com/orientechnologies/orientdb/issues/9164

**Comment by ikysil** [comment]
We observe the same issue as described in #9164 in all releases of OrientDB 3 - 3.0.x, 3.1.x, and 3.2.x included.

This issue and #9689 are blockers for migration from OrientDB 2 (2.2.37) to OrientDB 3.

**Comment by andrii0lomakin** [comment]
Closed as a duplicate of #9164 . We have already reopened it.
