### ISSUE TITLE
OrientDB shows terminal but will not run

### ISSUE THREAD

**Issue by AMOfficialGithub** [orientechnologies/orientdb#9697]
## Expected behavior  
Once clicking the .batch file the server is supposed to boot up and show logs

## Actual behavior  
While the window launches nothing else happens, it just stays stuck in the terminal.

## Steps to reproduce  
1. Boot up OrientDB in Windows 10 using the .batch file found in bin folder after unzipping.

**Comment by andrii0lomakin** [comment]
Hello. 
We have implemented Java 17 support, but this version is not released yet. You use the version which does not have support for Java 17.

**Comment by andrii0lomakin** [comment]
Update. Tinkerpop as of now only supports Java 11 so we need to wait for the upgrade till the gremlin console will be able to run on Java 17 version.

**Comment by tglman** [comment]
Hi,

This should work fine with recent versions, could you try again ?

Regards

**Comment by AMOfficialGithub** [comment]
Hello,

This problem has already been resolved last year. Please take me off the mailing list.

April McBroom
________________________________
From: tglman ***@***.***>
Sent: Friday, December 23, 2022 9:32 AM
To: orientechnologies/orientdb ***@***.***>
Cc: McBroom, April ***@***.***>; Author ***@***.***>
Subject: [External]: Re: [orientechnologies/orientdb] OrientDB shows terminal but will not run (#9697)

**External Email**

Hi,

This should work fine with recent versions, could you try again ?

Regards
