### ISSUE TITLE
Recommended way to shutdown OrientDB embedded when using Blueprints?

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#9698]
## Expected behavior  

Orient DB in embedded mode prevents program termination on server shutdown through presence of a non-daemon thread pool that never gets shutdown.

## Actual behavior  

Thread pool created OrientDBEmbedded in line 155 (Orient DB 3.1.7) is never shutdown, except by deprecated class ODatabaseDocumentTx closeAll(). The closeAll() function doesn't appear as though it is called indirectly via GraphFactory unless done so explicitly by the user. I'd appreciate if you could indicate the recommended way to shutdown Orient DB via Blueprints.

I would have assumed the method GraphFactory.close()   /** Closes all pooled databases and clear the pool. */ would have done the job and nothing further would need to be done, but alas this doesn't appear to be the case. Any recommendation on how to shutdown Orient DB via Blueprints or is this an issue in the product that need to be looked it?

## Aside comment

OrientDBEmbedded.java - Isn't creating thread pool in a constructor considered bad practice?
OrientDBEmbedded.java - Thread Pool on line 167 need a name. It took a while to track the issue down due to the generic name of the thread.

**Comment by andrii0lomakin** [comment]
Hi @jamieb22, thank you very much that you did work for us to investigate the reason for the problem.
Does not matter do you use Blueprints API or pure OrientDB API. 
The database should be created and shut down using OrientDB class. 
If OrientDB class does not shut down the thread pool, which seems to be the case according to your description, we will fix this problem.

**Comment by andrii0lomakin** [comment]
`OrientDBEmbedded.java - Isn't creating thread pool in a constructor considered bad practice? ` probably you mean that creation of threads is a bad practice because of leakage of not-initialized fields. 
`OrientDBEmbedded.java - Thread Pool on line 167 need a name. It took a while to track the issue down due to the generic name of the thread.` - sure I will give it a name. Thank you for this observation.

**Comment by andrii0lomakin** [comment]
Hi @jamieb22 ,
I have checked the code, this thread pool is actually closed https://github.com/orientechnologies/orientdb/blob/3.1.7/core/src/main/java/com/orientechnologies/orient/core/db/OrientDBEmbedded.java#L893 in OrientDBEmbedded#close method. This method is called from OreintDB#close(). All OrientDB lifecycle should be wrapped inside of this method. Do you call this method inside of your application?

**Comment by jamieb22** [comment]
Thanks for your thoughts We don't construct an OrientDB object directly since we are using Blueprints. This is how we create an Orient Graph Factory...

```
        graphFactory = new OrientGraphFactory(settings.getUrl(), settings.getLogin(), settings.getPassword(), false);
        graphFactory.setupPool(1, maxPoolSize)
```

This is how we shut it down

` graphFactory.close();`

The documentation of this method states:

**_Closes all pooled databases and clear the pool._**

In this scenario, are we still required to explicitly call OrientDB.close()? If so, how do we get a reference to the OrientDB object?

Jamie

**Comment by andrii0lomakin** [comment]
@jamieb22 do you use TP 2 or TP 3 API ?

**Comment by jamieb22** [comment]
We use the defined maven dependencies for Orient Db 3.1.7.
```

[INFO] +- com.orientechnologies:orientdb-graphdb:jar:3.1.7:compile
[INFO] |  +- com.orientechnologies:orientdb-server:jar:3.1.7:compile
[INFO] |  |  \- com.orientechnologies:orientdb-client:jar:3.1.7:compile
[INFO] |  +- com.orientechnologies:orientdb-tools:jar:3.1.7:compile
[INFO] |  +- com.orientechnologies:orientdb-core:jar:3.1.7:compile
[INFO] |  |  +- com.github.jnr:jnr-posix:jar:3.0.50:compile
[INFO] |  |  |  +- com.github.jnr:jnr-ffi:jar:2.1.10:compile
[INFO] |  |  |  |  +- com.github.jnr:jffi:jar:1.2.19:compile
[INFO] |  |  |  |  +- com.github.jnr:jffi:jar:native:1.2.19:runtime
[INFO] |  |  |  |  +- org.ow2.asm:asm-analysis:jar:7.1:compile
[INFO] |  |  |  |  +- org.ow2.asm:asm-util:jar:7.1:compile
[INFO] |  |  |  |  +- com.github.jnr:jnr-a64asm:jar:1.0.0:compile
[INFO] |  |  |  |  \- com.github.jnr:jnr-x86asm:jar:1.0.2:compile
[INFO] |  |  |  \- com.github.jnr:jnr-constants:jar:0.9.12:compile
[INFO] |  |  +- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.4.2:compile
[INFO] |  |  \- org.lz4:lz4-java:jar:1.4.0:compile
[INFO] |  +- com.tinkerpop.blueprints:blueprints-core:jar:2.6.0:compile
[INFO] |  |  +- org.codehaus.jettison:jettison:jar:1.3.3:compile
[INFO] |  |  |  \- stax:stax-api:jar:1.0.1:compile
[INFO] |  |  \- com.carrotsearch:hppc:jar:0.6.0:compile
[INFO] |  +- org.codehaus.groovy:groovy:jar:2.5.8:compile
[INFO] |  \- org.codehaus.groovy:groovy-jsr223:jar:2.5.8:compile
```

**Comment by jamieb22** [comment]
Andrey. I see in your commits you added Thread name's. Thank you for this. Please don't forget to add names for Timer's too (i.e. https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html). I see you are using non-daemon Timers. Hopefully, these get shutdown cleanly in all shutdown execution paths.

**Comment by andrii0lomakin** [comment]
@jamieb22 you use TP 2, it is kept only for API compatibility and is not evolved. If that is possible for you to use TP 3  you will find methods there to work with OrientDB instance. Otherwise, Orient.instance().shutdown() will help.

**Comment by andrii0lomakin** [comment]
> Andrey. I see in your commits you added Thread name's. Thank you for this. Please don't forget to add names for Timer's too (i.e. https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html). I see you are using non-daemon Timers. Hopefully, these get shutdown cleanly in all shutdown execution paths.

Thank you for your suggestions.

**Comment by jamieb22** [comment]
Andrey. Thanks for the tip. Although, I tried Orient.instance().shutdown(), it doesn't help. There is still the non-daemon thread pool on line 167 that is preventing shutdown. The only thing that works is the deprecated method ODatabaseDocumentTx.closeAll();

**Comment by andrii0lomakin** [comment]
Hi @jamieb22 , we have discussed this inside the team. Unfortunately, the only way in TP2 to close threads is the one that you found. You need to migrate to the TP3 to use the new OrientDB API. TP2 is not supported by the vendor for a long time, so I suggest you do that. I will keep the issue open till I will not add names to the timers. I am sorry for the inconvenience but we do not see too many reasons to support API which is not supported even by its vendor.

**Comment by jamieb22** [comment]
Thank you for the response. We will follow your suggestion and migrate to TP3 in due course. If I may ask, why is TP2 still a maven dependency of Orient DB v3.x? How are Orient DB users to know to integrate with TP3 and not TP2? I suppose it is in the documentation somewhere. Thanks in advance.

**Comment by andrii0lomakin** [comment]
That is kept to simplify migration to the TP 3. We can not obviously put both dependencies but all server distributions of OrientDB use TP 3 versions inside. We have a separate implementation of it, https://github.com/orientechnologies/orientdb-gremlin .

**Comment by jamieb22** [comment]
Andrey, are you sure this is a blue prints issue? Surely calling Orient.instance().shutdown() is going direct to Orient DB, not via Blueprints, and yet when we call this method directly the same behaviour is observed (i.e. Orient DB is not shutdown entirely).

**Comment by andrii0lomakin** [comment]
Yes, that is because Orient is not used in 3.0 versions. There were done attempts to keep it synchronized with the new implementation but now you should use OrientDB class to manage instances of OrientDB. If you check TP 3 there is a constructor in GraphFactory which accepts OrientDB instance as a parameter and then the factory manages it internally.

**Comment by andrii0lomakin** [comment]
It is not an issue of Blue Prints itself, of course. It is only a consequence of the fact that TP 2 was created and supported for the ODB 2 versions. And now all support and development are done in TP 3 version. 
As for documentation, we are working one new version of the site and documentation which we plan to make much more user friendly. If the fact that users should now use TP 3 is absent in documentation of course we will add it. I will check that with the team.

**Comment by jamieb22** [comment]
Thanks for the clarification, although I still feel like I am missing something. The class Orient is part of the package  com.orientechnologies.orient.core. This is the Orient core and has no outward dependency on Blueprints. When calling Orient.instance().shutdown(), Orient DB doesn't shutdown. Therefore, surely, this issue is impacting the Orient DB Core itself?

**Comment by jamieb22** [comment]
Ahh.. so we mustn't call Orient.instance().shutdown(). We must use the OrientDB class? Is this correct? Ok. Let me put it to you this way. What is the recommended way to shut OrientDB down completely?

**Comment by andrii0lomakin** [comment]
@jamieb22 for 2.x versions you used: TP2 + Oreint.shutdown() for 3.x versions you should use TP3 + OrientDB.open()/shutdown. You use TP2 API created for ODB 2 in ODB 3. Most of the times it is transparent for users. But sometimes abstractions leak, as in your case. 
Migration to TP 3 should not be painful for you because it should support the same queries.

**Comment by jamieb22** [comment]
To clarify, TP2 + Orient.instance().shutdown() doesn't work. It doesn't shutdown all threads. The only thing that works is ODatabaseDocumentTx closeAll().

**Comment by andrii0lomakin** [comment]
@jamieb22 "r 2.x versions you used: TP2 + Oreint.shutdown() for 3.x versions you should use TP3 + OrientDB.open()/shutdown." you work with ODB 3.x version :-) .

**Comment by jamieb22** [comment]
Andrey. You are still not getting what I am saying. TP2 + Orient.instance().shutdown() doesn't shutdown the server. It is doesn't work!

**Comment by andrii0lomakin** [comment]
@jamieb22 because you used it in 3.x version. 
"for 2.x versions you used: TP2 + Oreint.shutdown() for 3.x versions you should use TP3 + OrientDB.open()/shutdown. " It is approach for 2.x version to use TP2 with orient.shutdown() . For 3.x versions you should use approach which I wrote above. What is not clear in my message ?

**Comment by jamieb22** [comment]
Ok. Thanks for clarification. If we are stuck using Orient DB 3.0 and TP2 for now, what should we use?

**Comment by andrii0lomakin** [comment]
@jamieb22 I suppose you already answered this question. You can use the deprecated method and then migrate to the TP3 version.

**Comment by jamieb22** [comment]
Thank you!
