### ISSUE TITLE
Infinite loop when trying to import a database containing a vertex having an attribut's class type equals to Opoint

### ISSUE THREAD

**Issue by aberdev** [orientechnologies/orientdb#9700]
## Expected behavior  
Import any exported database will succeed

## Actual behavior  
Database import never finish until the timeout is triggered.  

## Steps to reproduce  

- Export an existing database (v 3.0.27 ) with vertices that at least one have an attribut with class type equals to Opoint
- Try to import the exported database in 3.2.0 or 3.2.2 instance 
Debugging shows that an infinite loop is in progress as shown by the attached capture
![orientdb_debug](https://user-images.githubusercontent.com/72909882/136820198-b8110eac-85bf-4dfe-8510-f5ce24e7bddb.png)

There is any fix or idea to avoid that ?
Thanks

**Comment by aberdev** [comment]
Hello ,
Finally , I fixed the issue like shown by the attached screenshot.
Is it Ok for you ?
![fix_orientdb_issue-9700](https://user-images.githubusercontent.com/72909882/136926517-c5e7560a-176f-422a-b798-0fa563c2edf6.png)
It goes in infinite loop because the value of firstRecord does never change inside the while loop.
Thanks

**Comment by andrii0lomakin** [comment]
@tglman could you take a look?

**Comment by andrii0lomakin** [comment]
@aberdev any chances that you will provide a pull request?

**Comment by aberdev** [comment]
@laa Yes , it's done(#9702)

**Comment by andrii0lomakin** [comment]
@aberdev thank you very much for the help we will release new versions soon.
