### ISSUE TITLE
 db.objectQuery() - results are not of type List<MyClass> but List<OResultInternal>

### ISSUE THREAD

**Issue by stozk** [orientechnologies/orientdb#9711]
## Expected behavior  
1. Send HTTP/REST Get-Request to Spring Boot Application (2.5.4) 
2. orientdb-core / orientdb-object (3.2.2) query returns all objects of "MyClass" and nested objects via the JAVA Object API using `db.objectQuery(query)` and pass them to the REST interface as a `List<MyClass>`.

## Actual behavior  

```

public List<MyClass> findAll() {
  ODatabaseObject db = orientDBObjectConnection.getDb();
  //my query to get all objects with their nested objects
  String query = "SELECT *:{*} FROM MyClass";
  List<MyClass> result = db.objectQuery(query);
  
  //prints the correct data as a JSON Array
  log.info(Arrays.toString(result.toArray()))
  
  db.close();
  
  //but returned result object which is passed to REST interface and serialized 
  via Jackson is a List<OResultInternal> instead of List<MyClass>
  return result;
}
```

The list of objects returned through the REST interface looks like this, which is obviously not of the type MyClass but OResultInternal?

```
[{
    "element": null,
    "temporaryProperties": [],
    "propertyNames": [
      "....",
      "....",
      "....",
      "@rid",
      "@version",
      "@class"
    ],
    "identity": null,
    "projection": true,
    "record": null,
    "blob": null,
    "metadataKeys": [],
    "vertex": null,
    "edge": null
  },...]
```

## Steps to reproduce  (none)
The post here https://github.com/orientechnologies/orientdb/issues/8153#issuecomment-373659147 doesn't mention anything further beyond using `List<POJO> result = db.objectQuery(query)` to query my Objects and get them back as my POJOs. Is there something that has to be done to extract the actual data from this resultset?

When I try to access one element:

```
MyClass element = result.get(0);
log.info(element.getIdShort());
```

I get a ClassCastException (... OResultInternal incompatible with MyClass).

THX&BR

**Comment by andrii0lomakin** [comment]
Hi @stozk, ObjectDb is not supported anymore, it is going to be removed in the next releases. If you wish to work with ORM you can use https://github.com/OrienteerBAP/Transponder for example.
