### ISSUE TITLE
Warning 'illegal reflective access operation' starting server 3.2.2 with Java11 on Linux (Ubuntu)

### ISSUE THREAD

**Issue by kgsw-de** [orientechnologies/orientdb#9712]
### OrientDB Version: 3.2.2  
via https://orientdb.org/download -- for Linux and any other *NIX

### Java Version: openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
  
### OS: Linux Mint 20.2 (Uma)
  = Ubuntu 20.04, kernel 5.4.0-89-generic, x86_64

## Expected behavior  
(throwing no WARNINGs?)

## Actual behavior  

```
~/orientdb-3.2.2/bin$ ./server.sh  
<ascii-logo>
2021-11-01 22:39:22:024 INFO  Detected limit of amount of simultaneously open files is 1048576,  limit of open files for disk cache will be set to 523776 [ONative]
2021-11-01 22:39:22:038 INFO  Loading configuration from: /home/user/orientdb-3.2.2/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/home/user/orientdb-3.2.2/lib/jaxb-impl-2.3.0.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

2021-11-01 22:39:22:360 INFO  OrientDB Server v3.2.2 (build 6df1d1942b88896dabea123fe1b8b0c6975e025a, branch develop) is starting up... [OServer]
...
```

## Steps to reproduce  
Installed due to steps at orientdb.org online (unpack .tgz, ... / no Docker installed)
http://orientdb.com/docs/3.0.x/fiveminute/java.html

## REM
- Using Python, PHP, JavaScript, some other stuff, and mugs of coffee - but not a Java programmer - so desperately seeking some clues how to deal with that, to work "out of box" or with little changes or different version?
- I have tried different search engines and queries, but not found anything concrete up to date information - looks like s.th. related to deprecated JAXB of EE, but I am not into maven artefacts nor javac compiling - looks to me, that this should be fixed on root side of the OrientDB release? 
- The documentation of OrientDB seems currently broken or lagging (last is 3.0.x GA and 3.1.0-beta1) due to Enterprise/SAP changes...?

If I should provide some more logs or infos, please let me know (and please in detail how to provide or where to find). All hints welcome.

**Comment by andrii0lomakin** [comment]
Hello, that should be already fixed in nightly build.

**Comment by andrii0lomakin** [comment]
We have plans to improve documentation but it will take some time.

**Comment by kgsw-de** [comment]
Oops, okay, thanks for the really fast answer, but it confuses me more, than it helps?

   I was looking for a stable database for my own programming, which bridges "simple" (key/value) or relational structures and new features like graphs - so I was looking for leaning and getting to known the new base and for using that as a solid(!) base for data. 
   When there is an errata or a bug or even a feature planned in software, typically(?!) there is a kind of list with bug-tracking (i.e. it will be assigned an ID to handle that) - and there will be a reference like "fixed by release #xyz" - and s.th. like "will merge into GA x.y.z" ??

> should be already fixed in nightly build

Is OrientDB that far away from "production"?  Or did I just use the "wrong" GA (general availability) version - like for example 3.0.y is really stable??

**Comment by andrii0lomakin** [comment]
@kgsw-de OrientDB is used in production by many clients. The warning which you can see when you run in Java 11 does not affect the functions of this product. That warning was introduced by the JVM team to inform developers about upcoming changes. That is a very minor issue and do we do not plan such changes in the bug tracker as it does not affect the functionality of the product.

**Comment by kgsw-de** [comment]
### Update: new JDK17 will break 3.2.2? 
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Corretto-17.0.1.12.1 (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.1.12.1 (build 17.0.1+12-LTS, mixed mode, sharing)

```
$ ./server.sh
...
INFO  Loading configuration from: /home/mobi/orientdb-3.2.2/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]null
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
...
Error on reading server configuration from file: /home/mobi/orientdb-3.2.2/config/orientdb-server-config.xml
...
Error during server execution
...
INFO  OrientDB Server is shutting down... [OServer]
INFO  OrientDB Server shutdown complete
```
Please, which JDK versions (elder ones) are supported by 3.2.2?
- JDK11 is current standard in Ubuntu based LTS
- JDK17 is new amazon LTS

**Comment by andrii0lomakin** [comment]
JDK 11 is already supported by the released version, JDK 17 will be supported in 3.2.3

**Comment by andrii0lomakin** [comment]
@kgsw-de Do you have any additional questions?

**Comment by kgsw-de** [comment]
Thank you very much for your friendly support. 
Hopefully, this gaps in documentation will be filled soon, especially focusing on newbies to OrientDB to ease their first encounter, and will not degrade the successful way of OrientDB, which looks very promising to me. 
So I will continue my study and learning of OrientDB.

**Comment by andrii0lomakin** [comment]
@kgsw-de thank you :-) do not hesitate to ask if you have additional questions :-)
