### ISSUE TITLE
DELETE EDGE don't work

### ISSUE THREAD

**Issue by Phantasie71** [orientechnologies/orientdb#9718]
## Expected behavior  
In SQL, deleting edges should work.

## Actual behavior  
No problem when useLightweightEdges is disabled.
But with useLightweightEdges=true, although the query returns a success message, the edges are still present in the database.

## Steps to reproduce  
DELETE EDGE FROM #456:78 TO #123:45

**Comment by andrii0lomakin** [comment]
Hi @Phantasie71. 
Lightweight edges are deprecated and not supported anymore. They are left only for binary/API compatibility. We do suggest using non-lightweight edges as we are going to remove them at the next release.

**Comment by Phantasie71** [comment]
Hi,
Thank you for your answer. I did not know. It is not specified in the documentation.
Does this mean that I have to convert all my data to migrate from v2.2.31 to v3.1.14?
If so, is there a function to do this easily?

**Comment by andrii0lomakin** [comment]
@Phantasie71 , the only way to do that right now automatically is to use export/import from/to JSON.

**Comment by andrii0lomakin** [comment]
@Phantasie71 do you have any other questions?

**Comment by Phantasie71** [comment]
No, it's OK. I am going to convert my data with an OrientDB Function because I don't know how to do this using the export/import to JSON.
Thank you so much
