### ISSUE TITLE
Upgrade dependencies: groovy2, commons-lang, commons-configuration to newer versions

### ISSUE THREAD

**Issue by dijef** [orientechnologies/orientdb#9723]
## Actual behavior  
Our whitesource reports multiple libraries only used by OrientDB requiring updating. Please resolve if possible:
groovy-2.5.11
commons-lang-2.6
commons-configuration-1.10

## Expected behavior 
New dependencies used:
groovy3
commons-lang2
commons-configuration2

**Comment by tglman** [comment]
Hi,

All of the dependencies that could be upgraded have been upgrade in recent hotfixes, closing this.

Regards
