### ISSUE TITLE
Unable to restore a database backed up from OrientDB v3.0.15 to OrientDB v3.2.3

### ISSUE THREAD

**Issue by ablieux** [orientechnologies/orientdb#9732]
## Expected behavior  
`Database restored in 2.77 seconds`

## Actual behavior  
`Error: com.orientechnologies.orient.core.exception.OStorageException: Storage <DBNAME> is in wrong state MIGRATION and can not be opened.` 

## Comments
Hi, I'm trying to restore a database backed up from OrientDB v3.0.15 to OrientDB v3.2.3. First, it seems work fine and the process ends with the expected message, but I also get this error message just after : `Error: com.orientechnologies.orient.core.exception.OStorageException: Storage <DBNAME> is in wrong state MIGRATION and can not be opened.`

I don't really understand this message, so please can you tell me what's wrong with this ?
Thank you very much.

**Comment by andrii0lomakin** [comment]
Hi, we do not support the compatibility of backups between versions. You should be able to restore the backup using the same version and then update the version using the already restored database. But I would suggest doing export/import of data from old to new version.

**Comment by tglman** [comment]
Hi, 

I this fix some concurrency issue related to this problem in recent hotfixes, you should not see this problem on the latest hotfix. closing
