### ISSUE TITLE
SAP dropped support for OrientDB on Sept 1 2021

### ISSUE THREAD

**Issue by n0mer** [orientechnologies/orientdb#9734]
Quote from https://en.wikipedia.org/wiki/OrientDB
 
> On September 15, 2017, OrientDB LTD company has been acquired by CallidusCloud a public company traded on NASDAQ.

> On January 30, 2018, it was announced SAP (company) acquired CallidusCloud for $2.4 billion. and therefore OrientDB is now supported by SAP (company).
 

> On September 1st, 2021, the original founder Luca Garulli left SAP (company) and forked the project into ArcadeDB after **SAP decided to stop providing commercial support for OrientDB**.
 

https://blog.arcadedb.com/welcome-to-arcadedb  new project home

**Comment by andrii0lomakin** [comment]
ArcadeDB is a separate project which shares the same model. It is not a fork of OrientDB. Would be strange to call MySQL to be a fork of PostreSQL only because they share the same model.

**Comment by andrii0lomakin** [comment]
Also as you can see ODB team is still here and still working on the project. And it is quite past of Sept 1 2021.

**Comment by lvca** [comment]
The page on Wikipedia reported "SAP decided to stop providing commercial support for OrientDB." - And this is 100% factually true. SAP doesn't provide commercial support for OrientDB anymore. Try contact yourself SAP and ask for it :-) Or @laa please provide the link where I can buy support.

There is no shame in telling the truth.

Perhaps everybody can see only 3 people (and 1 bot) are contributing to the code base: https://github.com/orientechnologies/orientdb/pulse/monthly.

**Comment by andrii0lomakin** [comment]
@lvca truth is that ArcadeDB is not a fork of OrientDB. And truth is that SAP still pays for the team to provide support of open source project and if we check ArcadeDB GitHub page we see that it has only a single contributor and bot itself. My main message that ArcadeDB is not fork of OrientDB it is a completely separate project with single major contributor.

**Comment by lvca** [comment]
@laa ArcadeDB was born as a fork of OrientDB: same idea, similar features but only took the code that was worth saving. There is no definition about how much of the original codebase must be used to be considered a "fork". ArcadeDB codebase today is only about 10% the same as OrientDB, mainly only the SQL engine is the same with some small adaptations. This means all the applications developed by using SQL (and/or Gremlin) are >90% portable and that was the goal.

About OrientDB, it's nice that SAP still continues to pay a few of you to support the existing clients, but as I said, **there is no support for new clients**, the product was removed from the official price list a long time ago. There is no trace of OrientDB on the SAP website and https://orientdb.com/ is still a static ugly page that for more than 2 years has not been updated.

I think OrientDB users deserve better than this. 

An official press release about the official position of SAP would be the best for OrientDB users, but I think SAP is too busy with its own business that has no time to do a proper one.

If an OrientDB user is looking for a community with a future, that supports the product by fixing bugs quickly and introducing new features following the community wishes, ArcadeDB is the right place.

**Comment by n0mer** [comment]
@laa i sent e-mail to orientdb_enquiries@sap.com on "Wed 01-Dec-21" - no reply for 2 weeks. Will re-post question here, maybe this place is more visible:
 

I read here https://groups.google.com/g/orient-database/c/fmo0WKnfXUc message from orientdb contributor "Luigi Dell'Aquila" that v2 is EOL’ed.

1. Is that true?

2. If so - what are the steps to migrate from 2.x to 3.x?

3. What amount of support does your enterprise subscription practically offers in such upgrade?

**Comment by andrii0lomakin** [comment]
@lvca  If one database uses only SQL code of another database that is not a fork :-) that is a completely new database with its own principles and only one library borrowed.  Only you alone push the code into the repository, which is clearly seen from the commit list. No one from current and former developers agreed to participate in the development of ArcadeDB.

@n0mer as for your questions:
1. Yes v2 is EOL.
2. Ideally you need to export data to and from JSON in related versions. 
3. If you have an EE subscription it is fully supported by now, but you can not buy a new subscription.

**Comment by andrii0lomakin** [comment]
@n0mer do you have any other questions?

**Comment by smolinari** [comment]
I'm confused and sad to get wind of all this. 

I'm confused, because it sounds like SAP is letting OrientDB "sunset", despite the valiant efforts of the couple three devs here (who I have great respect for). What can be said, to counter this impression? Is it incorrect?

I'm sad, because it seems a slight animosity between you Luca, and the team that stayed by your side for so long. Maybe that impression is also incorrect? It seems and makes me also sad, to see you are also a bit frustrated from the situation overall i.e. having to break up with your baby. I guess there is a whole story behind the breakup? At any rate, I wish you all the best. 

Scott
