### ISSUE TITLE
SQL TRUNCATE not supported by ODatabase#command(String)

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#9745]
### OrientDB Version: 3.0.41

We have a product where we originally used OrientDB 2.2.x and then migrated to 3.0.x.
We do the following:
`database.command(new OCommandSQL("TRUNCATE CLASS Whatever POLYMORPHIC UNSAFE")).execute();`
The result is the expected.

With OrientDB 3.0x, the OCommandSQL class is deprecated. The suggestion is to pass directly the SQL string to the command method.

`database.command("TRUNCATE CLASS Whatever POLYMORPHIC UNSAFE");`

However, this throws the following exception.

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
TRUNCATE CLASS ? POLYMORPHIC UNSAFE
       ^
Encountered " <TRUNCATE> "TRUNCATE "" at line 1, column 1.
Was expecting one of:
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    <RETURN> ...
    <FIND> ...
    <REBUILD> ...
    <OPTIMIZE> ...
    <GRANT> ...
    <REVOKE> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ...
    <IF> ...
    <SLEEP> ...
    <CONSOLE> ...
    <MOVE> ...
    <SELECT> ...
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <FIND> ...
    <INSERT> ...
    <MOVE> ...
```

**Comment by luigidellaquila** [comment]
Hi @diegomtassis 

The problem here is the `?` as target, that is not supported.
The same command, with the class name hardcoded, should work fine

Thanks

Luigi

**Comment by diegomtassis** [comment]
Indeed, the bind parameter didn't work either with the old OCommand class.

Thanks!
