### ISSUE TITLE
getting account suspended from orientdb.org and orientdb.com

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#9747]
## Expected behavior  
hit the web pages to download new version

## Actual behavior  
no longer able to get to orientdb web pages  
getting:
```

    Account Suspended
    Please contact your hosting provider to correct issues causing your website to be offline.

```

## Steps to reproduce  
navigate a web browser to : http://orientdb.com

**Comment by cr4igo** [comment]
orientdb.org is working again (for now)

**Comment by tglman** [comment]
Hi,

yep this should be fixed now, usual holiday hickups.

Closing
