### ISSUE TITLE
OrientDB 3.2 from 3.0.27

### ISSUE THREAD

**Issue by lfen21** [orientechnologies/orientdb#9759]
## Expected behavior  
Hi,

I'm using Orientdb , and i want to upgrade in 3.2.4. Should i use export / import or binary compatibility ? 

Why export / import is recommanded ? 

I prefer the second option. 

"When upgrading OrientDB to a newer major/minor version, we recommend to perform an export and import of the databases. Anyway, OrientDB guarantees binary format compatibility, so export/import is not striclty needed."

Thanks

## Actual behavior  
<add here>  

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by lfen21** [comment]
@tglman ?

**Comment by andrii0lomakin** [comment]
Answered in https://github.com/orientechnologies/orientdb/discussions/9481 . Please use discussions for the questions .
