### ISSUE TITLE
shortestPath() throwing ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ironluca** [orientechnologies/orientdb#9774]
## Expected behavior  
The shortestPath() function with 3 parameters [SELECT shortestPath(source,destination,'OUT')] should return shortest path between the source and destination nodes following the out edge from source.

## Actual behavior  
Throws the following: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

## Steps to reproduce  
All the steps below are executed from OrientDB Studio
1) Create new database
2) Create 2 vertices with graph editor (of class V) (refer first image)
3) Create 1 edge between then (of class E)
4) Execute the following : `select shortestPath(#10:0,#11:0,'OUT') (where #10:0 is the source and #11:0 the destination)`
5) Produces the above error

NOTE: The 4 parameter variant of shortestPath() function seems to be working: `select shortestPath(#10:0,#11:0,'OUT','E')` works, gives the right output (refer second image)

The SQL script: `select shortestPath(#10:0,#11:0,'OUT')`

![image](https://user-images.githubusercontent.com/40290578/159125171-1e8a6ecd-d1be-410b-a170-2bddcb796db3.png)

![image](https://user-images.githubusercontent.com/40290578/159125364-632d8a14-c90d-4812-8c57-f46b360c5263.png)

**Comment by tglman** [comment]
Hi, 
Do you have any stacktrace of this? do you see anything on the server logs ?


Regards

**Comment by ironluca** [comment]
@tglman , there is no specific stacktrace for the above in the server log. I checked the '<orient install dir>\log' (where '<orient install dir>' is the dir in which the server is installed. It has bin, log dirs ...) directory and the orient-server.log.x files. If you let me know any specific commands or log levels that I have to enable, I could do that and check.

There is perhaps a similar issue [here](https://github.com/orientechnologies/orientdb/issues/8013)

**Comment by tglman** [comment]
Hi,
ported the fix will be released in the next hotfix (3.2.6).

Regards

**Comment by tglman** [comment]
released
