### ISSUE TITLE
Performance issue with Orient 3.x when removing non lightweight edges

### ISSUE THREAD

**Issue by jacquipre** [orientechnologies/orientdb#9821]
## Expected behavior  
Removing non lightweight edges is not slower than in OrientDB 2.x  

## Actual behavior  
Hi!
We are updating OrientDB from version 2.2.37 to 3.2.6 and detected some performance issues with removing edges.
We have some not lightweighted edges which should be removed. This takes now 40% more time than before.

With some research and debugging we found out, that the reason for that is this [code change](https://github.com/orientechnologies/orientdb/commit/ae196eb597528a826efc98be9e288a87e1d6351a#diff-ef2eea58e389df40d5fab493270f82b760e14372dbfc91d57b56e53d1bee17ff) that was made for OrientDB 3.0.0. Unfortunately, we cannot see why this change was made (no issue linked).
In this commit, outcoming and incoming vertices were detached when removing an edge, which at first sounds correct.

We made a profiling where you can see that the `OEdgeDelegate.deleteLinks` method takes over 60% of the time, see

![removeEdge_00](https://user-images.githubusercontent.com/99176577/172372326-f7eeb98f-473f-49d0-a555-ed30db834d5a.jpg)

While debugging we saw, that this method is called twice for each edge:

1. `com.tinkerpop.blueprints.impls.orient.OrientGraph.removeEdgeInternal(OrientEdge)` --> line 438 calls `edge.removeRecord()`
2. this calls `com.orientechnologies.orient.core.record.impl.OEdgeDocument.delete()` 

![removeEdge_03](https://user-images.githubusercontent.com/99176577/172373365-98f959e9-dfac-448e-b3dd-f1778d1bb4dd.JPG)

This deletes the links first (no 1) and delegates to the `super.delete()` (no 2) which finally leads to `com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.delete(ORecord)` which also deletes the links in line 1030 if the document is an edge

![removeEdge_04](https://user-images.githubusercontent.com/99176577/172373737-32891fb9-0a1b-4890-b2d7-f264d488f268.JPG)

Is this expected? 

## Steps to reproduce  
remove a non-lightweight edge

**Comment by tglman** [comment]
Hi,

This should be fixed in the last release 3.2.14.

Closing
