### ISSUE TITLE
No function with name 'search_cross'

### ISSUE THREAD

**Issue by NicolasJuanF** [orientechnologies/orientdb#9827]
## Expected behavior  
To search across every lucene index using function "search_cross" mentioned in the documentation [http://orientdb.org/docs/3.2.x/indexing/Full-Text-Index.html#cross-class-search-enterprise-edition](url) 

## Actual behavior  
There is no function with name 'search_cross';

## Steps to reproduce  
```sql
SELECT  EXPAND(SEARCH_CROSS('beautiful')); --taken from documentation

-- throws  no function with name 'search_cross' exception
```

**Comment by tglman** [comment]
Hi,

This should work correctly since 3.2.25 

Regards
