### ISSUE TITLE
Incorrect warning message or performance issue

### ISSUE THREAD

**Issue by ufwtfcu** [orientechnologies/orientdb#9868]
### OS: Windows 10  
While importing data and creating edges between two types of vertices, match one vertex by using key value (index created). 

Vertex Product has unique CELL_BTREE index created by the property request_no. Product contains records > 20K rows

Here is the configuration part
`	"transformers": [
		{ "merge": 
			  { "joinFieldName": "sample_request_no", 
				"lookup":"Sample.sample_request_no" 
			  } 
		},

		{ "edge": { "class": "PRODUCT_SAMPLE",
                "joinFieldName": "request_no",
				"lookup": "SELECT expand(u) from (match {class: Product, as: u} return u) where u.request_no = ? limit 1", 
                "direction": "in",
				"unresolvedLinkAction":"WARNING",
				"skipDuplicates": true
            },
		},
	],
`
## Expected behavior  
Importing should finish quickly and no such incorrect messages -- as I use limit and also the SQL should return only 1 record as the request_no is key even if no limit is used.

## Actual behavior  
Many warning messages from server console and it's slow to finish
`[TIP] Query 'SELECT FROM Product' returned a result set with more than 10000 records. Check if you really need all these records, or reduce the resultset by using a LIMIT to improve both performance and used RAM [OProfilerStub]`  

## Steps to reproduce  
1. Import a vertex and create an unique index with its key column with many records (> 1000)
2. Import another vertex with a small number of records
3. Import and create an edge between 2 type of vertices.

**Comment by tglman** [comment]
Hi,

you are doing two queries, one inside one outside, the outside is the one that is filtering the data and has the limit, the one inside is producing the warning, consider to move the condition inside, like:
` match {class: Product, as: u, where:(request_no=?)} return u`
