### ISSUE TITLE
ETL hung when unique index is turned on and data contains duplicate key

### ISSUE THREAD

**Issue by ufwtfcu** [orientechnologies/orientdb#9869]
### OS: Windows 10  
Run oetl job to load data. (unique) Index is turned on and data contains duplicate key.

## Expected behavior  
Report error just like executing SQL command to create unique index in web UI.  

## Actual behavior  
ETL is hung forever and there is no message from server console. 

## Steps to reproduce  
1. Add unique index in .json configuration file
2. Data file contains 2 records which have same key value for the index property
3. Launch the .json by using oetl.

**Comment by tglman** [comment]
Hi,

have you try the 3.2.9 version ? it may already fix this problem.

Regards

**Comment by tglman** [comment]
Hi,

Should be already fixed. closing
