### ISSUE TITLE
Size of remote database is zero

### ISSUE THREAD

**Issue by leszekgruchala** [orientechnologies/orientdb#9870]
## Expected behavior  
The size of DB should be returned.

## Actual behavior  
The size is always zero.

## Steps to reproduce  
I try to obtain the size of a database.

The metadata returns zero.
![image](https://user-images.githubusercontent.com/89165/188150474-b8c6981f-df72-4801-9580-784e92dbf877.png)

The session object returns zero (scala snippet):
`session.asInstanceOf[ODatabaseDocumentRemotePooled].getSize`

Obtaining storages from the Orient instance also does not work because the `getStorages` returns an empty sequence:
```scala
val storages = Orient.instance.getStorages.asScala
storages.headOption.map(_.getSize).getOrElse(-1L)
```

Is it a bug or I do something wrong?

**Comment by tglman** [comment]
Hi,

A fix for this case was released in 3.2.10, anyway what was missing was the tracking of the information during the CUD (create,update,delete) operations, so existing database would display still a wrong number.

Regards
