### ISSUE TITLE
Exceptions are not triggered correctly when querying property after sorting vertices with a specific property using Gremlin API

### ISSUE THREAD

**Issue by zhengyingying** [orientechnologies/orientdb#9885]
## Expected behavior 
When we execute the query `g.V().order().by("vp0").has("vp1")`, where the property `vp1` of vertex `v2` is NULL , we expect OrientDB throws an exception, just like `The property does not exist as the key has no associated value for the provided element: v[#276:3]:vp0`. 

## Actual behavior  
OrientDB does not throw an exception correctly.

## Reproduce
```
OrientGraph graph = OrientGraph.open("remote:localhost/demodb", "root", "root");
GraphTraversalSource g = graph.traversal();
Vertex v1 = graph.addVertex("vl0");
v1.property("vp0", 1);
Vertex v2 = graph.addVertex("vl0");
v2.property("vp1");
```
 
We find that when we sorting vertices with the property `vp0`, an exception `The property does not exist as the key has no associated value for the provided element: v[#276:3]:vp0` can be triggered because vertex `v2` has not a property `vp0`.

Therefore,  when we execute the query `g.V().order().by("vp0").has("vp1")`, where the property `vp1` of vertex `v2` is NULL , we expect OrientDB throws an exception. 

However, OrientDB does not throw an exception correctly.

We also find that when we create the property `vp1` with a value, like `v2.property("vp1", 2)`, the exception can be triggered correctly.

**Comment by tglman** [comment]
Hi,

This is an expected behaviour, OrientDB is schemaless/schamamixed, so not having a property is not a failure, accessing a not existing property just return null.

Regards

**Comment by zhengyingying** [comment]
Thanks! I got it.
