### ISSUE TITLE
Database truncate fails in 3.1.x

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#9887]
When using 3.1.x, database truncate throws **java.lang.IllegalArgumentException: The clusterId is invalid** per each class to truncate.
https://github.com/CompartAG/orientdb-tryouts/blob/issues/9887/3.1.x/src/test/java/com/compart/tec/orientdb/document/truncate/TruncateRegressionTest.java

Same code using 3.0.x works as expected.
https://github.com/CompartAG/orientdb-tryouts/blob/issues/9887/3.0.x/src/test/java/com/compart/tec/orientdb/document/truncate/TruncateRegressionTest.java

**Comment by tglman** [comment]
Hi,

This should be fixed in the last development version of 3.1.x and 3.2.x

**Comment by tglman** [comment]
Hi,

Fixed, Closing
