### ISSUE TITLE
Create database not working in console

### ISSUE THREAD

**Issue by johny65** [orientechnologies/orientdb#9889]
## Expected behavior  

Use command `create database` from console without problems.

## Actual behavior  

Using the console (`console.sh` script), it is not possible to create a new database because it fails with error `java.util.NoSuchElementException: No value present`.

## Steps to reproduce  

Run `console.sh`:

```
OrientDB console v.3.2.8 (build f32d1127bf572e0a0367bea11ed5554f1f7e9fe0, branch UNKNOWN) https://www.orientdb.com
Type 'help' to display all the supported commands.
orientdb> create database remote:localhost/testdb root nimda;

Creating database [remote:localhost/testdb] using the storage type [PLOCAL]...
Error: java.util.NoSuchElementException: No value present
```

Using a previous version of console, it works fine (although server can be greater).

Error is introduced in version 3.2.8 of console, version 3.2.11 still has it.

**Comment by tglman** [comment]
Hi,

Thanks for reporting this, I could reproduced it, it is some problem of compatibility we introduced recently, anyway you can work around using the new way to connect to a server and create/open databases:

```

OrientDB console v.3.2.12-SNAPSHOT (build b24727c752422c10b7ef367af2fe49d438e77fbe, branch develop) https://www.orientdb.com
Type 'help' to display all the supported commands.
orientdb> connect env remote:localhost root nimda;           

orientdb> create database testdb plocal users (admin identified by 'admin' role admin);

+----+-------+------+---------------+
|#   |created|name  |operation      |
+----+-------+------+---------------+
|0   |true   |testdb|create database|
+----+-------+------+---------------+
orientdb> open testdb admin admin;
OK
orientdb {db=testdb}> 
```

Will try to fix this anyway for backward compatibility.

**Comment by tglman** [comment]
Hi

the 3.2.12 is out with the fix for this case, closing, feel free to reopen if you still experience the problem.

Bye
