### ISSUE TITLE
Distributed mode: OClass.setCustom() has no effect

### ISSUE THREAD

**Issue by sa-MatteoHausner** [orientechnologies/orientdb#9890]
## Expected behavior  
The following code should add three custom values to the schema class.
```
OClass oc = ...
oc.setCustom("key1", "world"); // has no effect
oc.setCustom("key2", "true");  // works - probably because it gets parsed as a boolean value
oc.setCustom("key3", "false"); // also works
```

## Actual behavior  
However when running the above example in **distributed mode** only "key2" and "key3" are added.

## Workaround
Enclosing the value in single quotes fixes the issue, .e.g: `"world" -> "'world'"`

## Fix
After patching `OClassDistributed.java` as follows the example above works as intended for me.
```
--- src/main/java/com/orientechnologies/orient/server/distributed/impl/metadata/OClassDistributed.java.orig     2022-10-31 14:49:17.000000000 +0100
+++ src/main/java/com/orientechnologies/orient/server/distributed/impl/metadata/OClassDistributed.java  2022-10-31 14:51:57.000000000 +0100
@@ -182,7 +182,7 @@
                acquireSchemaWriteLock();
                try {
                        if (isDistributedCommand(database)) {
-                               final String cmd = String.format("alter class `%s` custom `%s`=%s", getName(), name, value);
+                               final String cmd = String.format("alter class `%s` custom `%s`='%s'", getName(), name, value);
                                owner.sendCommand(database, cmd);
                        } else {
                                setCustomInternal(name, value);
```

**Comment by tglman** [comment]
Hi,

Thanks for the report, it looks good! if you can do a PR will merge directly that, otherwise i will copy from this.

Regards

**Comment by sa-MatteoHausner** [comment]
> Hi,
> 
> Thanks for the report, it looks good! if you can do a PR will merge directly that, otherwise i will copy from this.
> 
> Regards

Hi @tglman,

just opened the PR. -> #9891

Cheers!
