### ISSUE TITLE
high CPU usage on Orient DB 3.2.9 from 3.1.17

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#9892]
Hi,
I update OrientDB version from 3.1.17 to 3.2.9
While in the 3.1.17 the cpu usage **was equals to 2**, after the version update it **starts to be 12**!!!
At the startup I can see the different cpu increased value.

Is there some configuration  or workaround to fix this cpu increaded value?
Gianluca

**Comment by tglman** [comment]
Hi,

This should not be a change of load between 3.1.17 and 3.2.9, it may be there some data migration that will run at the first start with 3.2.x but when is done everything should be back to normal load, you can check the log to see if there is some migration happening.

In case you see more load for longer, it may be useful if you can capture some thread dumps and share them with us.

Bye

**Comment by gianluca-valentini** [comment]
Hi @tglman 
thanks for your response. 
Currently the migrated environment is up for a few days. I restart it more that one time but the core number does not change.

Please tell me how I can execute the thread dump (I don't know it) so that I can share it with you

Thanks
Gianluca

**Comment by tglman** [comment]
hi,

this may help: https://examples.javacodegeeks.com/java-thread-dump/

**Comment by tglman** [comment]
In any case, are you seeing constant high CPU in your system monitor, or you just see a high thread count?

Regards

**Comment by gianluca-valentini** [comment]
Hi @tglman 
I see constant high cpu in my system monitor.
After  execute the java thread dump as descibed in your suggested, I attached the zip with the file
[orientdb-jstack.zip](https://github.com/orientechnologies/orientdb/files/9954373/orientdb-jstack.zip)

Let me know if you see something strange
Thanks
Gianluca

**Comment by tglman** [comment]
Hi,

I went through the stack, I did not see anything too exceptional, only some query running, we are aware of some slow down that where introduced with some new security module in 3.2.x, that we tried to remove with the release 3.2.12 so feel free to double check that release to see if you see any reduction of CPU use.

Regards

**Comment by gianluca-valentini** [comment]
Hi @tglman 
I update the OrientDB version to the 3.2.12  and it seems that the situation is coming to be normal.
Now I'll monitor it in order to understand if it is fixed
Thanks

**Comment by gianluca-valentini** [comment]
Hi @tglman 
we can consider it fixed after 3.2.12
