### ISSUE TITLE
Impracticable Performance to Many Edges Creation to One Vertex

### ISSUE THREAD

**Issue by GustavoMD2** [orientechnologies/orientdb#9906]
## Expected behavior  
Create many edges to one vertex with a reasonable performance.

VertexA1 -> VertexB1
VertexA2 -> VertexB1
VertexA3 -> VertexB1
...             -> VertexB1

## Actual behavior  
When I've tried create many edges to one vertex the performance slow down very quickly and turns to impracticable.

What can I do to guarantee a reasonable performance?

Note: I've tested with sql.graphConsistencyMode=notx_async_repair and ridBag.embeddedToSbtreeBonsaiThreshold=-1 trying to improve the performance, but the behavior was the same.

## Steps to reproduce  
I've used Post Command Rest Api with CREATE EDGE E1 UPSERT #rid to #rid. To create edges between vertex class that don't have a "Supernode" we have a reasonable performance.

Regards.

**Comment by tglman** [comment]
Hi,

At first suggestion is to update to the last hotfix 3.2.13, there have been performance improvements, over all OrientDB that should show significant boost, on the other side can you share some numbers just to try to understand what is slow and fast for you.

Regards

**Comment by GustavoMD2** [comment]
Hi tglman,

Thank you for your return. I'll try with this hotfix.

The best performance that I've got to this situation is 500000 edges on 8 hours, it's 17 Edges per second. With another type of Edges where I don't have one "supernode" the performance is more than 1500 edges per second.

Regards.

**Comment by tglman** [comment]
Hi,

Yes for sure there have been performance improvements in recent release with supernodes, can you see improvement in your use case ?

More changes in performance are coming with the next hotfix release mainly in the use case of deleting vertices/edges.

Regards

**Comment by GustavoMD2** [comment]
Hi tglman,

I'll try apply the hotfix on this week and return my sight.

Thank you so much for your help.

Regards

**Comment by GustavoMD2** [comment]
Hi tglman,

Sorry for late to return, but I need to apply and test the hotfix. The performance is better than the old one that I reported. We can create Edges with one vertex of destination with more than 2000 lines per second.

Thank you so much for your help.

Regards

**Comment by tglman** [comment]
Hi,

Thank you for reporting back, I will close this.

Regards
