### ISSUE TITLE
OrientDB Spatial Dependency Update

### ISSUE THREAD

**Issue by rrowlands** [orientechnologies/orientdb#9908]
Hey all,

I am a developer at TerraFrame and we are using OrientDB in a few of our products. I am reaching out because the [OrientDB spatial library](https://github.com/orientechnologies/orientdb-spatial) is getting quite out of date and we need updates of dependent libraries, especially JTS (upgraded to locationtech).

Is this something that we can get on the roadmap for next year? We're happy to help with this effort but would want some guidance to make sure we're following correct procedures and maximizing efficiency

Thanks

**Comment by tglman** [comment]
Hi, @rrowlands,

what version of OrientDB  are you using? in the recent version all the spatial logic is included in the `orientdb-lucene` module, so the https://github.com/orientechnologies/orientdb-spatial is consider deprecated, I will update it with relative informations.

feel free to check and do PR for update the lucene module here: https://github.com/orientechnologies/orientdb/tree/develop/lucene

We usually do accept most of version updates that are compatible with disk layout and in case are exposed functionality and APIs.

Regards

**Comment by rrowlands** [comment]
Hi @tglman,

We are using the orientdb-client jar to communicate with OrientDB in java to java for persistence. We are using the orientdb-spatial library to convert JTS objects into OrientDB's OShape representation (which then get sent through the orientdb-client). Unfortunately the orientdb-lucene library has a dependency on orientdb-server, which pulls in too many dependencies for us (all of OrientDB?)

We are also unclear of where the orientdb-spatial v3.0.0 was actually released from as we do not see any tags or commits in the orientdb-spatial project which are related to that verison.

Thanks

**Comment by tglman** [comment]
Hi, 

I see, I think the dependency on the orientdb-server  for the orientdb-lucene module is not actually required, it should depends only on the core (which client already depends on), we will check and maybe remove the specific dependency.

as well orientdb-spatial was never release because it was merged inside orientdb-lucene.

Regards

**Comment by tglman** [comment]
Hi,

in the last develop orientdb-lucene only depends on orientdb-core now, will be released like this in 3.2.15.

Regards

**Comment by rrowlands** [comment]
Hi @tglman,

I noticed that the orientdb-core requires jnr. Correct me if I'm wrong, but isn't this used to execute binaries which would only exist in a server context? I attempted to exclude this dependency but the client wouldn't boot. Is it possible this could be refactored in a future release?

Thanks

**Comment by tglman** [comment]
Hi,

The jnr module is used exclusively for the off heap memory allocation,  you should be able to boot without it for a client only use case, so feel free to report an issue with the error you get, in a long term this dependency may be moved to a more specific module that is not needed for the client, but in short term is not possible.

Bye

**Comment by tglman** [comment]
Hi @rrowlands,

the 3.2.15 has been released without this dependency. can I close this ?

Regards

**Comment by rrowlands** [comment]
Hi @tglman,

Yes you may close this ticket.

Thanks for your help!
