### ISSUE TITLE
Embedded Attribute ClassCastException

### ISSUE THREAD

**Issue by rrowlands** [orientechnologies/orientdb#9910]
## Summary

When updating an existing embedded vertex outside of a transaction an unexpected ClassCastException is thrown from the remote OrientDB server.

    OVertex outerVertex2 = session.load(outerVertex.getIdentity());
    OElement embeddedVertex2 = outerVertex2.getProperty(EMBEDDED_ATTRIBUTE_NAME);
    embeddedVertex2.setProperty(EMBEDDED_ATTRIBUTE_TEXT, "123");
    outerVertex2.setProperty(EMBEDDED_ATTRIBUTE_NAME, embeddedVertex2);
    outerVertex2.save(); // Error is thrown here

Produces:

    Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.record.impl.OVertexDelegate cannot be cast to com.orientechnologies.orient.core.record.impl.ODocument
		at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.deserializeDeltaValue(ODocumentSerializerDelta.java:222)
		at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.deserializeDeltaEntry(ODocumentSerializerDelta.java:207)
		at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.deserializeDelta(ODocumentSerializerDelta.java:186)
		at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.deserializeDelta(ODocumentSerializerDelta.java:168)
		at com.orientechnologies.orient.server.tx.OTransactionOptimisticServer.begin(OTransactionOptimisticServer.java:106)
		... 6 more

This code works just fine on OrientDB v3.0.X, however on versions 3.2.13 and 3.1.20 we are encountering a ClassCastException. Additionally, the error is NOT thrown if inside a transaction.

## Minimal Test Code

A reproduceable example using only OrientDB is attached as follows:

[OrientDBEmbeddedAttributeTest.txt](https://github.com/orientechnologies/orientdb/files/10356267/OrientDBEmbeddedAttributeTest.txt)

**Full stacktrace**:
[orientdb-embedded-output.txt](https://github.com/orientechnologies/orientdb/files/10356030/orientdb-embedded-output.txt)

**Comment by tglman** [comment]
Hi,

This is a strange error, we will try to fix it, anyway this is down to the fact that vertex are not supported in embedded, it's not correct that a embedded document has a type vertex, the easy work around is to change the embedded document to a linked document, or to make the embedded class not a vertex, anyway changing in your test the create property creation is enough to fix the test, example:
`oClass.createProperty(EMBEDDED_ATTRIBUTE_NAME, OType.LINK, embeddedClass);`

even if in old version this seemed to work I will still produce some semantic problems, for example you would not be able to select/iterate over the vertex that are embedded, so we definitely suggest to not use vertex type as embedded, or use instead links.

Regards

**Comment by rrowlands** [comment]
Thanks a bunch for your help. This seems like something that could use better documentation. An exception could be thrown as well, for example when creating a property of type EMBEDDED and also referencing a vertex type.

We will investigate what it means for our stack to move away from embedded vertices in favor of embedded documents.

**Comment by tglman** [comment]
Hi,

yep adding it : https://github.com/orientechnologies/orientdb/commit/05d83b22cf98149f7d38b2d279c1bb914a54a075

Regards

**Comment by rrowlands** [comment]
Hi @tglman,

Sorry to bother again but we are a little unsure of the best way to architect things here.

We cannot use an embedded document because our document needs to be able to reference geometries. If I attempt to do this, OrientDB throws the error:

```
Suppressed: com.orientechnologies.orient.core.exception.OSchemaException: Document belongs to abstract class OPoint and cannot be saved
	DB name="testdb"
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.assignAndCheckCluster(ODatabaseDocumentAbstract.java:916)
		at com.orientechnologies.orient.server.tx.OTransactionOptimisticServer.assignClusters(OTransactionOptimisticServer.java:499)
		at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommit38(OConnectionBinaryExecutor.java:1560)
```

I have noticed that it works if I use a class instead of a document or a vertex. I have also noticed that class creates a table in the database, however this is reminding me of what happens with vertex: a table is created for the class definition, however that table never has any data in it because it is only used in an embedded context.

This begs the question: how can we architect things such that we can guarantee compatibility with current and future versions of OrientDB? Should we use a class? Perhaps an abstract class? Or perhaps a view? I noticed that your back-end contains concepts of an `EmbeddedClass`. Can we somehow use this?

If using class instead of vertex is the solution, for data migration can we simply remove the super type of `V` via your `ALTER CLASS` command?

What is also interesting is that it appears like we can define indexes on this class, however we are uncertain if these indexes do anything since they might be operating on this table which contains no data since the type is actually embedded.

Thanks

**Comment by tglman** [comment]
Hi,

Just to put down some simple rule:
Embedded Document can have associate any class Abstract or not, but the class do not have to extend E and V.
Abstract class cannot be used to save directly documents, you can save a document of a class that extend the abstract class and you can save a document with an Embedded Document that has a abstract class as type.

Knowing this, it should be enough to remove the extends from V and E from the class that you use for embedded type to resolve the problem.

You can make the class abstract to make sure that you never have record saved directly with the specific class, so only embedded or subclass.

Types like OPoint are abstract specifically because are required to be embedded.

Also be aware that all the index logic works only at the first level of the document, so you cannot index and query using the index properties that are in a depth > 1, and also for the case of spatial the embedded OPoint( ecc.) type need to be in a property at the root of the document to be indexed.

We do have some specific concept for handle better embedded types in the code, anyway is correct use the public type ODocument for everything.

**Comment by rrowlands** [comment]
Thanks for your help!
