### ISSUE TITLE
3.2.14 no docker image found

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#9911]
Hi,
I see the lastes OrientDB release on 27 Dec 2022
https://github.com/orientechnologies/orientdb/releases/tag/3.2.14
but I don't find it's docker image on

https://hub.docker.com/_/orientdb/tags

When it should be released?
Thanks
Gianluca Valentini

**Comment by tglman** [comment]
Hi,

Thank you to make me notice that, the PR is on  https://github.com/docker-library/official-images/pull/13861  when that will be merged it should be visible.

Regards
