### ISSUE TITLE
Inside Web Container property is not being set properly.

### ISSUE THREAD

**Issue by odysseaspenta** [orientechnologies/orientdb#9912]
## Expected behavior  
When starting the OrientDB engine through the startUp method, the inside web container property should be set according to the parameter passed into the method.

## Actual behavior  
The parameter is set to false explicitly regardless of what the value of the parameter is.

## Steps to reproduce  
```
public static Orient startUp(boolean insideWebContainer) {
    initLock.lock();
    try {
      if (initInProgress) {
        return null;
      }

      initInProgress = true;
      if (instance != null)
        return instance;

      **final Orient orient = new Orient(false);**
      orient.startup();

      instance = orient;
    } finally {
      initInProgress = false;
      initLock.unlock();
    }

    return instance;
  }
`
```

**Comment by tglman** [comment]
Hi,

Thanks to report this, I corrected it even though do not have much of an impact on runtime logic, the only thing that use the flag as today seems to be some warning logging.

Regards
