### ISSUE TITLE
Vertex delete with problems of performance

### ISSUE THREAD

**Issue by eduardoanl** [orientechnologies/orientdb#9917]
## Expected behavior  
Deletion around 5000 of records in classes V (Vertex)

## Actual behavior  
Some of these records are showing failures with the following message: "Read Time out".
Delete processing stay in long time and access to Orientdb Studio blocked

## Steps to reproduce  
delete commands are HTTP requests:

'{
  "command": "DELETE VERTEX EnderecoUnico WHERE @rid=:ridEnderecoUnico",
  "parameters": {
    "ridEnderecoUnico": "#':NullToEmpty(LnkIn.ridEnderecoUnico):'"
  }
}'

I already tried with the "LIMIT" and "BATCH" options, but without success

'{
  "command": "DELETE VERTEX EnderecoUnico WHERE @rid=:ridEnderecoUnico LIMIT 10",
  "parameters": {
    "ridEnderecoUnico": "#':NullToEmpty(LnkIn.ridEnderecoUnico):'"
  }
}'

And 

'{
  "command": "DELETE VERTEX EnderecoUnico WHERE @rid=:ridEnderecoUnico BATCH 10",
  "parameters": {
    "ridEnderecoUnico": "#':NullToEmpty(LnkIn.ridEnderecoUnico):'"
  }
}'

It still take a very long time.

Do you know how can I solve the performance issue?

**Comment by eduardoanl** [comment]
Do you know how can I solve the performance issue?

**Comment by tglman** [comment]
Hi,

Some improvements have been done in recent release, I think 3.2.14 has fixes related to this, so I would definitely suggest to update, also another suggestion is to batch the delete inside a transaction, with a script like this:
```sql
begin;
DELETE VERTEX EnderecoUnico WHERE @Rid=:ridEnderecoUnico LIMIT 100;
commit;
```

Regards

**Comment by tglman** [comment]
Hi,

Just released 3.2.16, please try this release it should solve most of this performance problem on vertex delete.

Regards

**Comment by eduardoanl** [comment]
Thanks for the info.

I have some active bases, so it was providing a backup of them, but without success.

firt, I tried the backup with connecting to remote database

![Error_Backup_Databnases_1](https://user-images.githubusercontent.com/22370778/217606504-ea514eae-e5c2-401d-8cb4-b56fe312c2e0.png)

In second,  I tried with connecting to local database 

![Error_Backup_Databnases](https://user-images.githubusercontent.com/22370778/217606906-ba0d254f-c97d-4558-a1d5-047258c39233.png)

@tglman 

Do you have any suggestions for correctly backing up to ensure the integrity of the data in these databases after deploying release 3.2.16?

**Comment by eduardoanl** [comment]
After the update from version 3.2.16, the performance of the delete vertex command still was bad.

so I got a performance improvement in changing the command syntax

From:

'{
"command": "DELETE VERTEX EnderecoUnico WHERE @Rid=:ridEnderecoUnico",
"parameters": {
"ridEnderecoUnico": "#':NullToEmpty(LnkIn.ridEnderecoUnico):'"
}
}'

To:

'{
"command": "DELETE VERTEX :ridEnderecoUnico",
"parameters": {
"ridEnderecoUnico": "#':NullToEmpty(LnkIn.ridEnderecoUnico):'"
}
}'
