### ISSUE TITLE
database backup procedure occours errors

### ISSUE THREAD

**Issue by eduardoanl** [orientechnologies/orientdb#9919]
## Expected behavior  
Database backup procedure performed successfully

## Actual behavior  
database backup procedure occours errors

I tried with connecting to remote database

![Error_Backup_Databnases_1](https://user-images.githubusercontent.com/22370778/217567832-7e3c3583-3439-43b8-88bb-0e84fabd2b2b.png)

So I tried with connecting to local database but wihout successfully

![Error_Backup_Databnases](https://user-images.githubusercontent.com/22370778/217567174-08150d62-65a3-42ea-8f22-f431620046e2.png)

## Steps to reproduce  
1º) connecting to remote database and backup database - error

![Error_Backup_Databnases_1](https://user-images.githubusercontent.com/22370778/217567832-7e3c3583-3439-43b8-88bb-0e84fabd2b2b.png)

2º) connecting to local database and backup database - error

![Error_Backup_Databnases](https://user-images.githubusercontent.com/22370778/217567174-08150d62-65a3-42ea-8f22-f431620046e2.png)

Do you know how can I solve the performance issue?

**Comment by eduardoanl** [comment]
All,

Do you know how can I solve the performance issue?

**Comment by tglman** [comment]
Hi,

Thanks to report we will double check the logic of the backup in the console.

Regards

**Comment by eduardoanl** [comment]
> Hi,
> 
> Thanks to report we will double check the logic of the backup in the console.
> 
> Regards

Hi,

Is there workaround to backup the databases?

**Comment by eduardoanl** [comment]
> Do you know how can I solve the performance issue?

Hi @tglman 

Is there workaround to backup the databases?

**Comment by tglman** [comment]
Hi,

Is not possible to backup the database from remote with the base backup system, it is possible to do if you have installed the `agent.jar` and to run a backup from the console with the ` -incremental`  ( [docs here](https://orientdb.com/docs/3.2.x/admin/Incremental-Backup-And-Restore.html?highlight=increm#executing-an-incremental-backup) ) option, as well is possible to schedule buckups on the server, here is the docs about it: https://orientdb.com/docs/3.2.x/plugins/Automatic-Backup.html?highlight=automatic%20backup#automatic-backup-server-plugin  or as a well if you have the agent.jar you can use the dashboard to schedule incremental backups: https://orientdb.com/docs/3.2.x/ee/Backup-Management.html?highlight=backup#backup-scheduling

I hope this help

**Comment by tglman** [comment]
Hi,

The alternative solutions should be enough to fix this problem, closing
