### ISSUE TITLE
Joining documents

### ISSUE THREAD

**Issue by ChambreNoire** [orientechnologies/orientdb#9925]
## Expected behavior  
I'm fairly new to OrientDb and I can't figure out the following:
I have a simple document model setup using generic classes.
```
create class Role;
create property Role.name string (mandatory true, notnull true);
create property Role.permissions embeddedset (mandatory true, notnull true);

create class User;
create property User.email string (mandatory true, notnull true);
create property User.password string (mandatory true, notnull true);
create property User.role link Role (mandatory true, notnull true);
```
I want to retrieve all Users and the Roles assigned to each.
If I were to do this using the Graph model it would look like this:

`traverse out(ERole) from VUser`

However I can't figure out an equivalent using the document approach.

Any ideas?

Cheers

**Comment by tglman** [comment]
Hi,

that would be something `select expand(role) from user` regards.
