### ISSUE TITLE
Docker image for Apple silicon 

### ISSUE THREAD

**Issue by adubkov** [orientechnologies/orientdb#9926]
Hi,

Would be great to have docker image build for Apple silicon to run on macs with M1 chip.

**Comment by adubkov** [comment]
Never mind. I found https://arcadedb.com/ which seems to be based of orientdb.

**Comment by nerdynikhil** [comment]
Hey @adubkov , I could work on this. They have a post on their official blog. https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by tglman** [comment]
Hi,

for OrientDB we do have docker images here: https://github.com/orientechnologies/orientdb-docker in the specific in this path https://github.com/orientechnologies/orientdb-docker/tree/master/release/3.2.x 

I do not know how to make them compatible with Apple silicon, but I'm happy to review and merge PRs.

Regards

**Comment by nerdynikhil** [comment]
Hey @tglman, I have raised a PR in the repo you mentioned.

**Comment by tglman** [comment]
Hi, 
The problem was not there was that in the official images where missing the architectures list, added it: https://github.com/docker-library/official-images/pull/14458/files  now the image should be already published
