### ISSUE TITLE
Server-Side transactions

### ISSUE THREAD

**Issue by Mr-Dispatch** [orientechnologies/orientdb#9935]
Would server-side transactions be a possibility ? Perhaps even (to not encumber the core) as additional service, or even separate process ?

---

I was very enthusiastic about OrientDB, up to the point where I dived deep-enough to realize that transactions are only supported client-side (previously I just glazed over "tranactions are there", "oooh, they mention MVCC", and thought "supported"). Nearly everything else is "exactly how I'd wanted it", but for this one giant hole. In some settings you cannot even fully trust the clients. And it is - I imagine - a fuck-ton of finicky work to get it right -- so should it even be offloaded to "driver authors" ?.

---

Would it be possible to leverage the existing Java Client-side transactions ? Wrap the session in something / stick something in the session, and gain server-side transactions this way ?

**Comment by tglman** [comment]
Hi,

Transaction in java are both client side and server side, you can do only server side transactions doing a sql script like:

```
begin;
insert ....
update ...
commit;
```

like explained here: https://orientechnologies.github.io/docs/3.2.x/sql/SQL-batch.html

**Comment by Mr-Dispatch** [comment]
I never said I wanted to use Java client-side. Quite the contrary, I'll never write anything new on JVM (the most I'm willing to do is patch mission-critical Java crap).

Even if Java is a popular platform, most of the world will, forever, use something else. IMO if OrientDB is to be considered as serious player on the graph-database playing field, transactions are a *MUST* for each and every client (must be moved to the server).

I'd re-open this, and assign it some "would-be-nice-in-future" tag.
[EDIT: slight correction]

**Comment by Mr-Dispatch** [comment]
Or do you propose that even JavaScript/REST clients should manage transactions, browser-side ?

What about needless round-trips when transactions are client-side, should this be included in the "blindingly fast" (MySQL-like "we lack features therefore we fast") ?

I don't wanna sound overly negative, but I want to stress that such approach to transactions will drive majority of perspective users away. Or, in another way, this is why I never heard about OrientDB in all those years it existed.

And there is still the possibility to have OrientDB as it always was: lean and mean, curruption-prone fighting machine ;-) And just supply another endpoint, with transactions, and use configuration / firewalling to force everyone (or all-but-select-few; or all-but-sacred-java-appz) to use the "transactioned" endpoint.

**Comment by tglman** [comment]
Hi, 

OrientDB do support transactions server side already ! in the form of batch sql operations.

It depends on what client/protocol you are using, the orientdb http protocol as today, do not support transactions that go across a request, still you can do a whole transaction server side with batch operations, like described here: https://orientdb.com/docs/2.2.x/OrientDB-REST.html#post---batch

Regards

**Comment by Mr-Dispatch** [comment]
Would batches support use-cases that include, as a sub-part, the following:
1) I have a class of "unique by all fields" vertices. In my case Software(Name,Language,Version,Vendor)
2) I have another class (LogonEvent), that has "set-of Software" field
3) New software will not exist in the DB, "select-or-insert"-like functionality is needed
4) In one transaction, I need to insert a new LogonEvent, having all Software as detected, without any mishaps happening
5) Software is just one of such fields (and there are many more tables/classes), and for example different kinds of Hardware even call inheritance into the question
6) Multiple such transactions (?batches?) could occur simultaneously

I really wanted to avoid relational db's for this one, and hoped to find "the default graph-db I'll reach for: schema + multiple inheritance + transactions". Hopefully with nice admin GUI.

OrientDB seemed "just the right one", sans transactions.

**Comment by Mr-Dispatch** [comment]
Shiiiiit, let variable, conditions, waits, loops, my Turing-tarpit heaven-hell, it seems like "if you are willing to learn another scripting language, *YOU CAN nearly HAS TRANSACTIONS*".

Thanks a lot for the patience!
