### ISSUE TITLE
Possibly wrong class name in OGraphRepair#repairVertices

### ISSUE THREAD

**Issue by gbaudic** [orientechnologies/orientdb#9970]
While browsing through the code of OGraphRepair, a line caught my attention: 

https://github.com/orientechnologies/orientdb/blob/6e94047200f6b7a15c02902eea21a26a85351fe6/core/src/main/java/com/orientechnologies/orient/core/db/tool/OGraphRepair.java#L276

I think that at this line, `OClass.EDGE_CLASS_NAME` should read `OClass.VERTEX_CLASS_NAME`.

**Comment by tglman** [comment]
Hi,

Thanks for reporting this, this looks clearly wrong.

will check and fix it.

Regards

**Comment by tglman** [comment]
Hi,

This should be fixed and released since 3.2.19, closing
