### ISSUE TITLE
Raise NegativeArraySizeException with requiring huge memory size when reading a specific record in a query on s390x Linux

### ISSUE THREAD

**Issue by kxc1573** [orientechnologies/orientdb#9972]
## Expected behavior  
Returns the desired result when using a unique index in the docker both on x86 Linux and s390x Linux.

## Actual behavior  
In the docker on the S390X Linux, when a query SQL goes through the unique index, raises` java.lang.NegativeArraySizeException: -2057971028` and the log shows the record `size=1677747200 bytes` which is wrong.

But the same operation runs OK in the docker on the x86 Linux.

Here is the log during query:
```
2023-04-21 05:58:29:670 FINE  {db=Demo} Read record #52:2 v.2 size=1677747200 bytes [OLocalPaginatedStorage]
2023-04-21 05:58:29:671 WARNI {db=Demo} Invalid type index: 97 [OType]
2023-04-21 05:58:29:679 FINE  {db=Demo} Sent run-time exception to the client /127.0.0.1:49358: java.lang.NegativeArraySizeException: -2057971028 [ONetworkProtocolBinary]
2023-04-21 05:58:29:682 FINE  {db=Demo} Request id:1 type:5 [ONetworkProtocolBinary]
2023-04-21 05:58:29:682 FINE  {db=Demo} Disconnecting connection OClientConnection [id=1, source=/127.0.0.1:49358, since=1682056707935]... [OClientConnectionManager]
2023-04-21 05:58:29:682 FINE  {db=Demo} onClose [OLuceneIndexFactory]
2023-04-21 05:58:29:682 FINE  Disconnected connection OClientConnection [id=1, source=/127.0.0.1:49358, since=1682056707935] found 1 channels [OClientConnectionManager]
```
Here is the log for writing data on `#52:2` :
```
2023-04-21 08:12:17:890 FINE  {db=Demo} 34 Committed transaction 95 on database 'Demo' (result=[ORecordOperation [record=Program#52:2{id:******,source:***,date:2022-01-04T03:08:50Z,label:******,name:***,description:null,group:null,****,language:null,displayName:***,type:***} v1, type=CREATE]]) [OLocalPaginatedStorage]
``` 
At the same time, when we try to use the condition 'id = "*****"' to execute a query on the native UI or in the console mode, both failed.

## Steps to reproduce  
In the docker on the s390x Linux.

<1> Raise Exception
1) We load 26 data file, less than 10MB, into the OrientDB 3.1.15.
2) We execute a query using the tinkergraph-gremlin with parameters `direction=both&&depth=3`, most of those data should be returned. But it is failed during reading the `#52:2`, there are 3778 pieces of data of the same type.
3) We  execute a query on the native UI or inner the console mode using the SQL statement `select * from program where @RID="#52:2"`, both are failed.

The detail log shows above.

<2> Runs OK
For the sake of data confidentiality, we cannot provide specific test data, so we try to minimize the scope for error data.
1) We just load only 1 data file, which is related to the previous `#52:2`
2) The data is stored on the same position `#52:2`
3) It runs OK using the SQL statement `select * from program where @RID="#52:2"`.

**Comment by tglman** [comment]
Hi, 

This is a bit strange also because seems architecture dependent, what kind of index are you using for this data ? also looking at the log I see `Invalid type index: 97 [OType]` for that kind of index type we have just up to `23` so there is clearly something wrong.

As far as I understood all the operations and the creation of the database is done on the same "machine" with the same architecture, do you confirm ?!

Also is the client application using similar CPU architecture ?

The architecture itself should not have an impact on the logic in the way the data is stored, OrientDB databases should be portable across architectures.

The specific error "NegativeArraySizeException"  should have been sent to the client application, so you should be able to locate it, in the application log, and find the full stack trace, that would be really useful to pin-point where the error come from.

At last, we do have more recent version of the 3.1.x series released (as time of writing 3.1.20) also the 3.2.x version is available, consider to check a more recent version as well, this may be already solved.

Bye

**Comment by kxc1573** [comment]
What kind of index? I don't have idea about it, can you give me more hints?

Let me make some more clarification about our test environment：
1. we have two machine, one x86 Linux and one s390x Linux
2. we package an all-in-one image including PostgreSQL, OrientDB and our application
3. the PostgreSQL and OrientDB use different image for different architecture, but our application is same, it's Java application
4. we use the same test data and perform the same operation

And here is more information about what we have tried:
1. we have tried the OrientDB 3.1.20 on the s390x Linux, it's same to 3.1.15
2. we have tried the IBM JDK, it's same the OpenJDK
3. Assume the data stored on `#52:2` is `program A`, we have checked that it only has 1 edge. So we have tried to reload those data without the `program A` and its edge. After trying the same operation, another error raises, but the error can only be seen in our application's log
```
java.lang.IllegalStateException: The property does not exist as the key has no associated value for the provided element: v[#50:3]:id
	at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.propertyDoesNotExist(Property.java:155) ~[gremlin-core-3.4.6.jar:3.4.6]
	at org.apache.tinkerpop.gremlin.structure.Element.lambda$value$1(Element.java:94) ~[gremlin-core-3.4.6.jar:3.4.6]
	at org.apache.tinkerpop.gremlin.structure.Property.orElseThrow(Property.java:101) ~[gremlin-core-3.4.6.jar:3.4.6]
	at org.apache.tinkerpop.gremlin.structure.Element.value(Element.java:94) ~[gremlin-core-3.4.6.jar:3.4.6]
``` 
What we can see in the OrientDB's log seems that `the client disconnect the connectioin`
```
2023-04-24 08:55:02:398 FINE  {db=Demo} Read record #34:0 v.2 size=176 bytes [OLocalPaginatedStorage]
2023-04-24 08:55:02:418 FINE  {db=Demo} Request id:10 type:5 [ONetworkProtocolBinary]
2023-04-24 08:55:02:418 FINE  {db=Demo} Disconnecting connection OClientConnection [id=10, source=/127.0.0.1:43630, since=1682326500922]... [OClientConnectionManager]
2023-04-24 08:55:02:419 FINE  {db=Demo} onClose [OLuceneIndexFactory]
2023-04-24 08:55:02:419 FINE  Disconnected connection OClientConnection [id=10, source=/127.0.0.1:43630, since=1682326500922] found 1 channels [OClientConnectionManager]
```

Hope this information helps

**Comment by kxc1573** [comment]
Unfortunately, we just tried 3.2.18, still the same problem.

**Comment by kxc1573** [comment]
It also appears on 3.2.20.

**Comment by tglman** [comment]
Hi,

This problem seems due to some serialization alignment, do you have any instructions to run tests on this architecture? or if you can you could run yourself a `mvn clean install` of this project on that environment and see if there are any failing tests.

Maybe is even possible to run the CI on this architecture if it's available as docker image that can be used from github actions.

We should be agnostic from the architecture, so this is for sure a bug.

Regards

**Comment by kxc1573** [comment]
I'm sure that we run the `mvn clean install` and `docker build` on the same s390x Linux machine.

If we build the image on the x86 Linux and then run it on the s390x Linux, the application runs failed.

**Comment by tglman** [comment]
Hi,

Does the building of the image include the creation and population of the database ? maybe (by mistake) in some cases our persistent data format is not agnostic from the architecture. So the reason of this error is the creation of the data in one architecture and reading in a different architecture.

Regards

**Comment by kxc1573** [comment]
Hi,

Just check our Dockerfile, we download the tar file from the orientdb-community, then extract the orientdb and set bin PATH.

The `DOWNLOAD_URL` is https://repo1.maven.org/maven2/com/orientechnologies}/orientdb-community/$ORIENTDB_VERSION/orientdb-community-$ORIENTDB_VERSION.tar.gz

**Comment by vbsiegem** [comment]
@tglman I work with @kxc1573 . This zLinux issue -- as well as the [other one @kxc1573 reported](https://github.com/orientechnologies/orientdb/issues/10019) -- are a major pain point for some of our customers.

When I pull the latest release code (3.2.26) and run `mvn clean test` on a zLinux system, I get failures in the _OrientDB Tests_ bucket that look very similar to the issue reported here.

I am attaching the build output and the test report files here.
[OrientDB-3.2.26_on_zLinux.tar.gz](https://github.com/orientechnologies/orientdb/files/13890008/OrientDB-3.2.26_on_zLinux.tar.gz)

Can you provide us with an outlook for when these issues might be fixed?
What other information / resources do you need from us to be able to proceed?

**Comment by tglman** [comment]
Hi,

This should be fixed from 3.2.30, could you try again and check?

Regards

**Comment by kxc1573** [comment]
Yes, I know it.
We will have a new release soon, which will include OrientDB 3.2.30. I will close it after the integration testing is completed.

**Comment by tglman** [comment]
Hi @kxc1573,

Can we consider this closed ?
