### ISSUE TITLE
OrientDB docker: Property creation of class showing success but INFO CLASS <class name> not showing information of property

### ISSUE THREAD

**Issue by vamshh** [orientechnologies/orientdb#9981]
### Java Version: openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.372-b07, mixed mode)
## Expected behavior  
INFO CLASS <class name> should show properties created using REST-API

## Actual behavior  

CLASS 'Student'

Records..............: 0
Default cluster......: student (id=38)
Supported clusters...: student(38), student_1(39), student_2(40), student_3(41)
Cluster selection....: round-robin
Oversize.............: 0.0

## Steps to reproduce  
POST  http://ip:port/class/demo/Student
Body
{
    "name": {
    "propertyType": "STRING"
    }
}

**Comment by vamshh** [comment]
Pls Suggest any workaround on this. Am looking to use Rest APi in my code to communicate with orientdb for class, properties creation operations

**Comment by tglman** [comment]
Hi,

This sound a bit strange, I understood the way you create the class, but is not clear for me where you run the INFO class operation, are you running this from studio ? as well can you see the class created from the schema tab in studio ?

Regards

**Comment by vamshh** [comment]
Yes am running from console screen

**Comment by vamshh** [comment]
Figured Out i was using wrong url format: 
Correct url: POST http://ip:port/**property**/demo/Student
