### ISSUE TITLE
"account suspended" accessing class/interface documentation

### ISSUE THREAD

**Issue by TDavidHudson** [orientechnologies/orientdb#9983]
## Expected behavior  
Opening, e.g., https://orientdb.com/javadoc/develop/com/orientechnologies/orient/core/hook/ORecordHookAbstract.html in browser shows documentation.  (Class documentation would be useful; the documentation at https://orientdb.org/docs/3.2.x/java/Java-Hooks.html refers to an ODatabaseComplex class/interface that apparently doesn't exist, among other problems relative to orientdb-core 3.2.19 .)

## Actual behavior  
Last Wednesday, it worked.  This week, both on Windows 10 Enterprise 22H2 build 19045.2965 Edge browser and in Android Chrome browser, HTTP status 404 is returned, resulting in "Account Suspended
Please contact your hosting provider to correct issues causing your website to be offline." screen.  This seems related to closed bug https://github.com/orientechnologies/orientdb/issues/9747 , in which holiday hiccoughs are blamed.

## Steps to reproduce  
Open https://orientdb.com/javadoc/develop/com/orientechnologies/orient/core/hook/ORecordHookAbstract.html in browser.  This is a result of searching for, e.g., "orientdb orecordhookabstract".

**Comment by tglman** [comment]
Hi,

Thanks to report this, will have a look to fix this, in the man while I will try to keep the docs update here https://orientechnologies.github.io/ 

Regards

**Comment by TDavidHudson** [comment]
@tglman Where would I find documentation on, say, ORecordHook under https://orientechnologies.github.io/ docs?  I didn't find it earlier.

**Comment by tglman** [comment]
hi,

This is now fixed. closing
