### ISSUE TITLE
Race condition on completion in ODistributedDatabaseChunk

### ISSUE THREAD

**Issue by timw** [orientechnologies/orientdb#9985]
There is a race condition in the [ODistributedDatabaseChunk](https://github.com/orientechnologies/orientdb/blob/develop/distributed/src/main/java/com/orientechnologies/orient/server/distributed/impl/ODistributedDatabaseChunk.java#L71) constructor used when streaming a full database to a distributed node.

At the end of a read, a check is made (apparently to avoid a network round trip and a zero byte chunk if the backup completes while the last chunk is being actively read).

```
        if (in.available() == 0 && backgroundBackup.getFinished().await(0, TimeUnit.NANOSECONDS)) {
          // BACKUP COMPLETED
          last = true;
        }
```

`in` is a `PipedInputStream`, which is fed from a `PipedOutputStream`, and maintains a buffer of bytes that can be read without blocking, which after a read could be empty, even if not at the end of stream.
If returns `in.available()` 0, then data is written to the pipe, and then the background backup completion await succeeds, then the data in the input buffer will be lost.

Inverting the condition to check for stream completion first will remove the race condition: 
```
```
        if (backgroundBackup.getFinished().await(0, TimeUnit.NANOSECONDS) && in.available() == 0) {
          // BACKUP COMPLETED
          last = true;
        }
```
In this case, any data written between the previous read and the completion check will be kept in the buffer and read in the next chunk, which will hit this block again, detect EOF, and be marked as the last chunk.

**Comment by tglman** [comment]
Hi, 

Thanks for this detailed issue, will fix it straight away.

**Comment by tglman** [comment]
Hi, 

This has been fixed and released, closing
