### ISSUE TITLE
The count query takes an excessive amount of time to complete

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#9987]
### OS: Ubuntu 22

I'm using a 4 nodes cluster each one with 32 CPU and 16Gb. Orientdb started and running with dserver.sh on each node

## Expected behavior  
The count query should return the result in a reasonable amount of time, considering the size of the graph.

## Actual behavior  
Executing count queries in OrientDB with a large number of vertices (over 200,000). The count query takes an excessive amount of time to complete.

##Steps to Reproduce:
1. Set up a graph database in OrientDB with over 200,000 vertices.
2. Execute a count query on the vertices, such as "SELECT COUNT(1) FROM V".

Additional Notes:
I have observed that the performance issue becomes more noticeable as the number of vertices increases. Other types of queries perform well, but count queries specifically exhibit this problem.
How does it changes when the vertex has one or more unique indexes?

Please let me know if any additional information or test cases are needed to investigate and address this performance issue.

Thank you.
Gianluca Valentini

**Comment by tglman** [comment]
Hi,

Could you collect the execution plan of both cases ? 

In any case using the count with a parameter other than the `*` will make the query engine to try to filter values based on that property, which may skip the use of any index/cluster precomputed size, so making the execution slower.

Bye

**Comment by tglman** [comment]
Hi,

There have been improvement on this in 3.2.23, can you double check that version ?

Regards

**Comment by tglman** [comment]
Hi,

This should be solved for cases where is possible to have a faster count, closing this, feel free to re-open if you still see issues.
