### ISSUE TITLE
Add ability to reuse indexes in OR expressions [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#999]
This is [Issue 999](http://code.google.com/p/orient/issues/detail?id=999) moved from a Google Code project.
Added by 2012-08-03T12:51:50.000Z by [lomakin....@gmail.com](http://code.google.com/u/110615750300902819680/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

### Original description

    Currently, indexes are used in complex expression only if they are connected using AND operators.
    It will be useful to add support to reuse indexes in OR operators if both parts of this operator can be evaluated indexes too.
    Also possibility to switch of this behavior should be added. 
    The last switch should prevent cases when amount of data fetched form indexes is more than amount of records that will should be tested by iterating over DB.

**Comment by luigidellaquila** [comment]
Usage of multiple indexes with OR conditions was implemented in 2.1.

Closing

Thanks

Luigi
